In [67]:
import pathlib as Path
import numpy as np
import pandas as pd

## Create dataframe from embeddings

In [68]:
#-----Frequency Embeddings dataframe creation-----
def create_embeddings_dataframe(root_path):
    emb_root = Path.Path(root_path)
    emb_files = emb_root.rglob("embeddings_samples.npz")
    
    all_data = []
    
    for emb_file in emb_files:
        emb = np.load(emb_file)
        X = emb['X']
        y = emb['y']
        subjects = emb['subs']
        
        for i in range(X.shape[0]):
            data_point = {
                'embedding': X[i],
                'label': y[i],
                'subject': subjects[i],
                'file_path': str(emb_file)
            }
            all_data.append(data_point)
    
    df = pd.DataFrame(all_data)
    return df

In [69]:
def df_cleaning(df, emb_size=384):
        # --- Expand embedding column into 381 separate columns ---
    embedding_df = pd.DataFrame(df["embedding"].tolist(),
                                columns=[f"emb_{i}" for i in range(emb_size)])

    # --- Concatenate back to the original DataFrame (optional) ---
    df_expanded = pd.concat([df.drop(columns=["embedding"]), embedding_df], axis=1)
    return df_expanded

In [70]:
#-----Frequency Embeddings dataframe creation-----
freq_emb= create_embeddings_dataframe("C://dev//dolphin_initial_testing//DOLPHIN//out_prelbd_task_wise//frequency_emb_stored//")
#-----Temporal Embeddings dataframe creation-----
temp_emb= create_embeddings_dataframe("C://dev//dolphin_initial_testing//DOLPHIN//out_prelbd_task_wise//temporal_emb_stored//")
#-----Combined Embeddings dataframe creation-----
comb_emb= create_embeddings_dataframe("C://dev//dolphin_initial_testing//DOLPHIN//out_prelbd_task_wise//emb_stored//")

freq_emb_df= df_cleaning(freq_emb, emb_size=384)
temp_emb_df= df_cleaning(temp_emb, emb_size=384)
comb_emb_df= df_cleaning(comb_emb, emb_size=768)

In [71]:
freq_emb_df.sample(5)

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_374,emb_375,emb_376,emb_377,emb_378,emb_379,emb_380,emb_381,emb_382,emb_383
239,1,pre-LBD-48#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.026829,-0.037561,0.012212,-0.047020,0.024748,-0.035392,0.046189,...,0.022111,0.126247,-0.033947,0.023330,-0.005869,0.110748,0.002101,0.030808,0.025347,0.048743
993,1,pre-LBD-72#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.007746,-0.119414,-0.096543,0.007971,-0.034161,-0.039081,0.060631,...,0.026341,0.095504,0.020670,-0.031900,0.056306,0.029541,0.099522,-0.012130,0.021537,-0.048232
913,1,pre-LBD-103#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.006091,-0.122542,-0.097042,0.007439,-0.035012,-0.037619,0.061736,...,0.024269,0.096376,0.021212,-0.031216,0.056705,0.028116,0.097500,-0.013545,0.020749,-0.046550
124,1,pre-LBD-79#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.003713,0.040947,-0.102968,0.045758,0.034926,-0.030015,0.006690,...,0.078143,0.062993,0.058206,-0.027473,-0.028143,0.006273,0.008161,-0.037082,-0.032695,-0.039703
231,1,pre-LBD-4#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.023560,-0.033300,0.005409,-0.053382,0.022268,-0.039408,0.042200,...,0.022690,0.127628,-0.041221,0.026466,-0.001108,0.113712,0.000516,0.033044,0.026210,0.045985

In [72]:
temp_emb_df.sample(5)

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_374,emb_375,emb_376,emb_377,emb_378,emb_379,emb_380,emb_381,emb_382,emb_383
1374,1,pre-LBD-15#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.072782,0.034710,-0.039587,-0.020371,0.089312,0.032138,-0.004606,...,-0.043482,0.046901,-0.001693,0.079785,0.018602,0.035085,-0.006108,0.062380,0.021124,-0.017660
782,1,pre-LBD-116#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.028852,-0.028504,-0.002088,0.079480,0.029286,-0.024515,-0.038351,...,-0.004113,0.002134,-0.070211,0.040174,-0.061012,-0.057692,0.043160,0.010722,0.062937,-0.042202
837,1,pre-LBD-61#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.034455,-0.009454,0.000486,0.088870,0.024815,-0.022061,-0.050019,...,-0.000842,0.008465,-0.069420,0.032619,-0.061646,-0.058760,0.051590,0.007967,0.065390,-0.045500
1210,1,pre-LBD-106#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.013444,0.000117,-0.004020,-0.012621,0.032116,0.033671,-0.023083,...,0.039705,0.034761,0.042621,-0.040136,0.007026,0.067041,0.021651,0.018673,0.025703,0.021640
1808,1,pre-LBD-12#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.013239,-0.040882,0.024400,-0.055079,-0.014620,0.010625,-0.064201,...,0.019777,-0.073483,0.026999,0.080754,-0.003973,-0.008127,0.048084,0.059806,0.063131,0.162505

In [73]:
comb_emb_df.sample(5)

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_758,emb_759,emb_760,emb_761,emb_762,emb_763,emb_764,emb_765,emb_766,emb_767
515,1,pre-LBD-30#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.054891,0.023616,0.029865,0.013956,-0.061379,0.063497,-0.005428,...,-0.037852,-0.038421,0.000336,0.006482,0.031445,0.033240,0.020176,-0.021619,-0.034384,-0.029052
1435,1,pre-LBD-74#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.005197,0.033889,0.046267,-0.018016,0.000173,-0.047002,0.024773,...,-0.001178,0.036760,0.023915,0.030995,0.018438,0.028437,-0.036605,-0.027379,0.004752,-0.055482
1031,0,HC-18#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.053051,-0.016040,0.003169,0.015450,-0.100921,0.042919,0.012869,...,0.030790,-0.055749,0.038751,0.018162,-0.040069,0.013775,-0.051406,0.002137,0.020295,0.014173
346,1,pre-LBD-119#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.039520,-0.009753,0.006910,0.039528,0.045146,-0.018873,-0.061653,...,0.000499,-0.002708,-0.047119,0.059782,-0.001132,-0.049402,-0.008109,-0.004787,0.003716,0.037838
51,1,pre-LBD-118#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.004838,-0.084137,0.003182,-0.020603,-0.020748,0.046657,-0.065704,...,0.030596,-0.017201,-0.024265,0.016454,-0.006532,0.011949,-0.076281,0.000632,-0.019008,0.003844

In [74]:
def task_wise_df_creation(df, task_name):
    task_df = df[df['file_path'].str.contains(task_name)].reset_index(drop=True)
    return task_df

In [75]:
task_list = ['1_1', '3_1', '3_2', '3_3', '3_4', '3_5', '9_1', '10_1', '15_1', '16_1', '17_1', '18_1', '19_1']

task_freq_dfs = {task: task_wise_df_creation(freq_emb_df, task) for task in task_list}
task_temp_dfs = {task: task_wise_df_creation(freq_emb_df, task) for task in task_list}
task_comb_dfs = {task: task_wise_df_creation(freq_emb_df, task) for task in task_list}

In [76]:
task_freq_dfs.get("3_1").sample(15)

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_374,emb_375,emb_376,emb_377,emb_378,emb_379,emb_380,emb_381,emb_382,emb_383
93,1,pre-LBD-49#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.025570,0.081931,-0.013505,0.009018,-0.116183,-0.026485,-0.033332,...,0.039413,-0.041263,0.020840,-0.004276,-0.049099,0.034478,-0.065123,-0.015089,0.002810,-0.059363
136,1,pre-LBD-9#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.018721,0.081927,-0.010418,0.001998,-0.117634,-0.025292,-0.031785,...,0.036665,-0.038815,0.019437,-0.002878,-0.046651,0.036924,-0.064980,-0.014711,-0.004201,-0.063378
123,1,pre-LBD-78#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.019524,0.081369,-0.007641,0.009783,-0.114131,-0.033370,-0.031553,...,0.032844,-0.030420,0.023112,-0.001709,-0.052515,0.039440,-0.059261,-0.020329,-0.002682,-0.059311
24,0,HC-31#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.020676,0.081833,-0.008087,0.010638,-0.116799,-0.030684,-0.032455,...,0.034569,-0.035206,0.021831,-0.004647,-0.050852,0.039896,-0.061662,-0.019066,-0.000568,-0.057273
91,1,pre-LBD-47#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.020102,0.080821,-0.009853,0.009671,-0.114418,-0.031540,-0.032411,...,0.031674,-0.029105,0.023281,-0.000472,-0.049428,0.041171,-0.063274,-0.017340,-0.000682,-0.059505
38,1,pre-LBD-103#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.020236,0.081759,-0.008424,0.009276,-0.115209,-0.030145,-0.032695,...,0.032214,-0.032790,0.021979,-0.002656,-0.051434,0.039761,-0.061657,-0.019571,-0.002411,-0.058873
133,1,pre-LBD-87#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.020353,0.081825,-0.010217,0.008826,-0.113884,-0.028939,-0.033813,...,0.033737,-0.032606,0.020480,-0.002645,-0.051493,0.040450,-0.062977,-0.018187,0.000387,-0.059231
54,1,pre-LBD-120#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.020379,0.082506,-0.009032,0.013731,-0.116217,-0.033883,-0.034782,...,0.032991,-0.036044,0.023143,-0.004842,-0.050248,0.042101,-0.061835,-0.019287,-0.000293,-0.053892
121,1,pre-LBD-76#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.019539,0.079011,-0.015013,0.007018,-0.111438,-0.030025,-0.033130,...,0.031044,-0.027128,0.022969,0.004412,-0.047450,0.036385,-0.064244,-0.015139,-0.002766,-0.063278
100,1,pre-LBD-55#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.020786,0.080664,-0.010544,0.010554,-0.111780,-0.029734,-0.034320,...,0.034555,-0.032969,0.020447,-0.000964,-0.052547,0.038277,-0.061269,-0.018033,-0.000678,-0.059951
145,1,pre-LBD-98#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.023650,0.082128,-0.013285,0.008044,-0.113671,-0.024967,-0.032775,...,0.036425,-0.033664,0.020819,-0.001577,-0.049763,0.038362,-0.064215,-0.015112,0.000056,-0.060256
61,1,pre-LBD-18#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.021553,0.081026,-0.009876,0.007957,-0.115876,-0.031374,-0.031656,...,0.034516,-0.034468,0.021693,-0.003879,-0.051767,0.038641,-0.060882,-0.018528,-0.002593,-0.058147
138,1,pre-LBD-91#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.020727,0.081019,-0.010819,0.009694,-0.114165,-0.028424,-0.031667,...,0.037299,-0.035691,0.022536,-0.000615,-0.050098,0.040154,-0.064722,-0.018412,0.000068,-0.061039
57,1,pre-LBD-14#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.015944,0.080661,-0.006830,0.010052,-0.115370,-0.033410,-0.033333,...,0.029632,-0.032336,0.021827,-0.003415,-0.049775,0.042920,-0.060795,-0.020692,-0.004642,-0.056170
112,1,pre-LBD-67#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.021381,0.079730,-0.010148,0.008695,-0.109966,-0.030376,-0.033927,...,0.035821,-0.033162,0.019941,-0.000692,-0.050567,0.040126,-0.064558,-0.018815,0.001659,-0.062460

In [77]:
def x_y_split(df):
    embedding_cols = [c for c in df.columns if c.startswith("emb_")]
    X = df[embedding_cols].values
    y = df["label"].values
    
    return X, y

In [78]:
df_3_1 = task_freq_dfs.get("3_1")
X, y = x_y_split(df_3_1)
X.shape
y.shape

(147,)

# OPTUNA + XGBoost

In [79]:
import xgboost as xgb
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

# Defining the objective function
def objective(trial):
    param = {
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1),
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0, 5),
    }
    
    # initializing the XGBoost model
    model = xgb.XGBClassifier(**param, 
                              tree_method = 'hist',  # Using GPU for training 
                              device =  'cuda')       # If you have multiple GPUs, you can specify the GPU ID
                              
    # if you try in the computer without GPU, just remove the last 2 params (tree_method & device)
    X, y = x_y_split(df_3_1)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
    score = cross_val_score(model, X_train, y_train, cv=10).mean()   # calculating score using cross-validation
    return score

In [80]:
import optuna

# Create and run the optimization process with 100 trials
study = optuna.create_study(study_name="preLBD_task", direction='maximize') 
study.optimize(objective, n_trials=100, show_progress_bar=True, n_jobs=-1)   

# Retrieve the best parameter values
best_params = study.best_params
print(f"\nBest parameters: {best_params}")

[I 2025-11-10 13:33:01,060] A new study created in memory with name: preLBD_task
Best trial: 1. Best value: 0.794545:   1%|          | 1/100 [00:12<19:55, 12.08s/it]

[I 2025-11-10 13:33:13,135] Trial 1 finished with value: 0.7945454545454546 and parameters: {'max_depth': 10, 'learning_rate': 0.05237129638271615, 'n_estimators': 216, 'subsample': 0.6609299165445001, 'colsample_bytree': 0.7539932157774187, 'min_child_weight': 3, 'gamma': 4.244764194118254}. Best is trial 1 with value: 0.7945454545454546.

Best trial: 1. Best value: 0.794545:   2%|▏         | 2/100 [00:17<13:45,  8.43s/it]

[I 2025-11-10 13:33:19,006] Trial 2 finished with value: 0.7845454545454545 and parameters: {'max_depth': 6, 'learning_rate': 0.08330962292419715, 'n_estimators': 353, 'subsample': 0.7105026869160295, 'colsample_bytree': 0.698523897844277, 'min_child_weight': 4, 'gamma': 3.9284379489163044}. Best is trial 1 with value: 0.7945454545454546.

Best trial: 1. Best value: 0.794545:   3%|▎         | 3/100 [00:21<10:10,  6.29s/it]

[I 2025-11-10 13:33:22,761] Trial 0 finished with value: 0.7836363636363636 and parameters: {'max_depth': 6, 'learning_rate': 0.08546960605971507, 'n_estimators': 430, 'subsample': 0.712627499774434, 'colsample_bytree': 0.5407879243843869, 'min_child_weight': 1, 'gamma': 2.9614262347277003}. Best is trial 1 with value: 0.7945454545454546.

Best trial: 4. Best value: 0.813636:   4%|▍         | 4/100 [00:27<09:54,  6.20s/it]

[I 2025-11-10 13:33:28,814] Trial 4 finished with value: 0.8136363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.05228730955979085, 'n_estimators': 308, 'subsample': 0.6228271253198983, 'colsample_bytree': 0.5784089158769181, 'min_child_weight': 7, 'gamma': 2.210183195251947}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:   5%|▌         | 5/100 [00:28<06:38,  4.20s/it]

[I 2025-11-10 13:33:29,465] Trial 3 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.0756515455591825, 'n_estimators': 584, 'subsample': 0.7229446659829755, 'colsample_bytree': 0.522262183950764, 'min_child_weight': 5, 'gamma': 4.066417279740292}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:   6%|▌         | 6/100 [00:39<10:26,  6.67s/it]

[I 2025-11-10 13:33:40,928] Trial 8 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.011723638693323336, 'n_estimators': 240, 'subsample': 0.6782894174646137, 'colsample_bytree': 0.7343264194026204, 'min_child_weight': 8, 'gamma': 2.30917502468806}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:   7%|▋         | 7/100 [00:40<07:14,  4.68s/it]

[I 2025-11-10 13:33:41,501] Trial 6 finished with value: 0.8036363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.020898620712195965, 'n_estimators': 336, 'subsample': 0.550544009472763, 'colsample_bytree': 0.9287784371711888, 'min_child_weight': 3, 'gamma': 2.5562167175107913}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:   8%|▊         | 8/100 [00:45<07:12,  4.70s/it]

[I 2025-11-10 13:33:46,259] Trial 7 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.028622082658130557, 'n_estimators': 331, 'subsample': 0.9305007400284548, 'colsample_bytree': 0.8863711983116018, 'min_child_weight': 8, 'gamma': 0.8255400945505864}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:   9%|▉         | 9/100 [00:55<09:47,  6.46s/it]

[I 2025-11-10 13:33:56,585] Trial 5 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.0898087767011117, 'n_estimators': 791, 'subsample': 0.976483228988857, 'colsample_bytree': 0.5637677273111834, 'min_child_weight': 7, 'gamma': 0.5242008661909131}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  10%|█         | 10/100 [01:05<11:14,  7.49s/it]

[I 2025-11-10 13:34:06,379] Trial 9 finished with value: 0.8136363636363637 and parameters: {'max_depth': 10, 'learning_rate': 0.052261062628710296, 'n_estimators': 497, 'subsample': 0.6458532727468136, 'colsample_bytree': 0.6981825527436862, 'min_child_weight': 9, 'gamma': 3.6199785148376495}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  11%|█         | 11/100 [01:11<10:32,  7.11s/it]

[I 2025-11-10 13:34:12,617] Trial 12 finished with value: 0.8036363636363637 and parameters: {'max_depth': 10, 'learning_rate': 0.05109745621845674, 'n_estimators': 288, 'subsample': 0.7833290895930591, 'colsample_bytree': 0.7829955293931206, 'min_child_weight': 4, 'gamma': 4.5623229119228625}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  12%|█▏        | 12/100 [01:23<12:36,  8.59s/it]

[I 2025-11-10 13:34:24,615] Trial 11 finished with value: 0.7654545454545454 and parameters: {'max_depth': 10, 'learning_rate': 0.09177959577206304, 'n_estimators': 639, 'subsample': 0.5705642773030586, 'colsample_bytree': 0.7828406094751386, 'min_child_weight': 2, 'gamma': 1.7903735107888596}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  13%|█▎        | 13/100 [01:31<12:13,  8.44s/it]

[I 2025-11-10 13:34:32,685] Trial 10 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.06425481260004799, 'n_estimators': 972, 'subsample': 0.5631642421043068, 'colsample_bytree': 0.715535124655048, 'min_child_weight': 9, 'gamma': 1.034120930919638}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  14%|█▍        | 14/100 [01:38<11:13,  7.83s/it]

[I 2025-11-10 13:34:39,111] Trial 16 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.07101694195022339, 'n_estimators': 111, 'subsample': 0.8033027425244043, 'colsample_bytree': 0.6160668589832518, 'min_child_weight': 6, 'gamma': 3.1459659514125655}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  15%|█▌        | 15/100 [01:45<10:50,  7.66s/it]

[I 2025-11-10 13:34:46,371] Trial 13 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.06988847706117483, 'n_estimators': 718, 'subsample': 0.8238103704150324, 'colsample_bytree': 0.9975705080683676, 'min_child_weight': 5, 'gamma': 4.990469557713311}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  16%|█▌        | 16/100 [01:47<08:15,  5.90s/it]

[I 2025-11-10 13:34:48,205] Trial 14 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.06988954258874792, 'n_estimators': 632, 'subsample': 0.827093711089057, 'colsample_bytree': 0.6026747734238133, 'min_child_weight': 6, 'gamma': 1.504949245271201}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  17%|█▋        | 17/100 [02:01<11:32,  8.34s/it]

[I 2025-11-10 13:35:02,219] Trial 15 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.06760310741973428, 'n_estimators': 662, 'subsample': 0.8070911174577968, 'colsample_bytree': 0.5063147760498117, 'min_child_weight': 6, 'gamma': 1.4841546500015204}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  18%|█▊        | 18/100 [02:14<13:26,  9.84s/it]

[I 2025-11-10 13:35:15,547] Trial 19 finished with value: 0.8136363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.03911597992120319, 'n_estimators': 512, 'subsample': 0.6034485722513626, 'colsample_bytree': 0.5004820443373257, 'min_child_weight': 7, 'gamma': 0.12781529365741484}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  19%|█▉        | 19/100 [02:15<09:32,  7.06s/it]

[I 2025-11-10 13:35:16,142] Trial 17 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.03906815627226556, 'n_estimators': 673, 'subsample': 0.8419472939809087, 'colsample_bytree': 0.5102161332374261, 'min_child_weight': 6, 'gamma': 1.6417262615728623}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  20%|██        | 20/100 [02:15<06:50,  5.13s/it]

[I 2025-11-10 13:35:16,768] Trial 18 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.03848445986009868, 'n_estimators': 552, 'subsample': 0.8834775206541126, 'colsample_bytree': 0.501108109934402, 'min_child_weight': 6, 'gamma': 1.5542066863978157}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  21%|██        | 21/100 [02:27<09:33,  7.26s/it]

[I 2025-11-10 13:35:28,996] Trial 20 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.037734833123093524, 'n_estimators': 503, 'subsample': 0.6068153463245102, 'colsample_bytree': 0.6374222180175388, 'min_child_weight': 10, 'gamma': 0.11903693706406449}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  22%|██▏       | 22/100 [02:57<18:16, 14.06s/it]

[I 2025-11-10 13:35:58,907] Trial 21 finished with value: 0.8036363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.09896720888128702, 'n_estimators': 847, 'subsample': 0.8818474524616634, 'colsample_bytree': 0.6529328526105461, 'min_child_weight': 5, 'gamma': 3.3833121563515576}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  23%|██▎       | 23/100 [03:00<13:29, 10.52s/it]

[I 2025-11-10 13:36:01,165] Trial 22 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.08003815686929404, 'n_estimators': 875, 'subsample': 0.744997154739556, 'colsample_bytree': 0.6368520583544002, 'min_child_weight': 5, 'gamma': 3.523835027365089}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  24%|██▍       | 24/100 [03:02<10:23,  8.20s/it]

[I 2025-11-10 13:36:03,962] Trial 23 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.0791735939230716, 'n_estimators': 936, 'subsample': 0.7433026036888485, 'colsample_bytree': 0.6342819869058608, 'min_child_weight': 10, 'gamma': 3.4563440330028996}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  25%|██▌       | 25/100 [03:11<10:25,  8.34s/it]

[I 2025-11-10 13:36:12,635] Trial 24 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.09816371572601243, 'n_estimators': 806, 'subsample': 0.9783386266961146, 'colsample_bytree': 0.5770521272434807, 'min_child_weight': 7, 'gamma': 0.6874545194294908}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  26%|██▌       | 26/100 [03:17<09:31,  7.72s/it]

[I 2025-11-10 13:36:18,891] Trial 28 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.061887962073832, 'n_estimators': 119, 'subsample': 0.5204232926101491, 'colsample_bytree': 0.5606918164174698, 'min_child_weight': 7, 'gamma': 2.213470875130741}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  27%|██▋       | 27/100 [03:35<12:52, 10.59s/it]

[I 2025-11-10 13:36:36,174] Trial 25 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.08405552483272889, 'n_estimators': 788, 'subsample': 0.74478000199568, 'colsample_bytree': 0.5765792887809272, 'min_child_weight': 7, 'gamma': 2.4465431374367688}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  28%|██▊       | 28/100 [03:39<10:36,  8.84s/it]

[I 2025-11-10 13:36:40,925] Trial 26 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.06023521591000129, 'n_estimators': 832, 'subsample': 0.7489643750195216, 'colsample_bytree': 0.5687966849108632, 'min_child_weight': 7, 'gamma': 2.5107447413636814}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  29%|██▉       | 29/100 [03:40<07:40,  6.49s/it]

[I 2025-11-10 13:36:41,937] Trial 27 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.06008892881506145, 'n_estimators': 788, 'subsample': 0.9917871974593147, 'colsample_bytree': 0.5650436830028742, 'min_child_weight': 7, 'gamma': 0.6665804660493793}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  30%|███       | 30/100 [03:57<11:00,  9.43s/it]

[I 2025-11-10 13:36:58,235] Trial 29 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.05829396498581228, 'n_estimators': 735, 'subsample': 0.9890056671809847, 'colsample_bytree': 0.5771297577759193, 'min_child_weight': 8, 'gamma': 2.8768180172622966}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  31%|███       | 31/100 [04:03<09:37,  8.38s/it]

[I 2025-11-10 13:37:04,147] Trial 32 finished with value: 0.8136363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.0896364810871704, 'n_estimators': 427, 'subsample': 0.6999354120608552, 'colsample_bytree': 0.5403210161717591, 'min_child_weight': 8, 'gamma': 2.8985123221362112}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  32%|███▏      | 32/100 [04:12<09:47,  8.64s/it]

[I 2025-11-10 13:37:13,410] Trial 30 finished with value: 0.8136363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.058782558807777614, 'n_estimators': 733, 'subsample': 0.9813910980278043, 'colsample_bytree': 0.5518262541930552, 'min_child_weight': 8, 'gamma': 2.834235873559731}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  33%|███▎      | 33/100 [04:18<08:47,  7.87s/it]

[I 2025-11-10 13:37:19,487] Trial 31 finished with value: 0.8136363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.09125071620886299, 'n_estimators': 749, 'subsample': 0.9903999732297672, 'colsample_bytree': 0.5369788625688923, 'min_child_weight': 8, 'gamma': 2.9282650499970675}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  34%|███▍      | 34/100 [04:20<06:54,  6.27s/it]

[I 2025-11-10 13:37:22,034] Trial 33 finished with value: 0.7936363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.07589600766606511, 'n_estimators': 429, 'subsample': 0.6974780528312411, 'colsample_bytree': 0.5306064378314775, 'min_child_weight': 4, 'gamma': 1.9541752988753351}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  35%|███▌      | 35/100 [04:25<06:05,  5.62s/it]

[I 2025-11-10 13:37:26,132] Trial 34 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.028780872550744907, 'n_estimators': 431, 'subsample': 0.9448116900119327, 'colsample_bytree': 0.8729078346237812, 'min_child_weight': 9, 'gamma': 1.0739347343373207}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  36%|███▌      | 36/100 [04:29<05:36,  5.26s/it]

[I 2025-11-10 13:37:30,546] Trial 36 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.02857950194944766, 'n_estimators': 208, 'subsample': 0.9360065872657607, 'colsample_bytree': 0.8291017939921507, 'min_child_weight': 9, 'gamma': 1.0138052765834669}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  37%|███▋      | 37/100 [04:32<04:56,  4.71s/it]

[I 2025-11-10 13:37:33,974] Trial 35 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.047858033406170016, 'n_estimators': 393, 'subsample': 0.9100683313581609, 'colsample_bytree': 0.8946152054079782, 'min_child_weight': 9, 'gamma': 1.0273662135198296}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  38%|███▊      | 38/100 [04:38<05:10,  5.01s/it]

[I 2025-11-10 13:37:39,672] Trial 38 finished with value: 0.8036363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.017861282216206194, 'n_estimators': 208, 'subsample': 0.9475230404463513, 'colsample_bytree': 0.8652979427241091, 'min_child_weight': 5, 'gamma': 0.39823747414785343}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  39%|███▉      | 39/100 [04:39<03:49,  3.76s/it]

[I 2025-11-10 13:37:40,529] Trial 37 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.04598320097682586, 'n_estimators': 349, 'subsample': 0.9245089456287874, 'colsample_bytree': 0.8587324377230929, 'min_child_weight': 9, 'gamma': 1.047613156108537}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  40%|████      | 40/100 [04:56<07:35,  7.60s/it]

[I 2025-11-10 13:37:57,081] Trial 39 finished with value: 0.8136363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.015099408791776014, 'n_estimators': 349, 'subsample': 0.6430774686479555, 'colsample_bytree': 0.9210532905249693, 'min_child_weight': 1, 'gamma': 0.512870044009174}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  41%|████      | 41/100 [05:06<08:13,  8.36s/it]

[I 2025-11-10 13:38:07,217] Trial 40 finished with value: 0.8036363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.0162981025565058, 'n_estimators': 578, 'subsample': 0.6472821278630827, 'colsample_bytree': 0.6793019278491079, 'min_child_weight': 3, 'gamma': 4.044016051818408}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  42%|████▏     | 42/100 [05:10<06:59,  7.23s/it]

[I 2025-11-10 13:38:11,804] Trial 41 finished with value: 0.7936363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.04600107518376329, 'n_estimators': 580, 'subsample': 0.6428565838413226, 'colsample_bytree': 0.9709823628158101, 'min_child_weight': 3, 'gamma': 4.054293269493958}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  43%|████▎     | 43/100 [05:12<05:13,  5.51s/it]

[I 2025-11-10 13:38:13,296] Trial 43 finished with value: 0.7936363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.0872376935566078, 'n_estimators': 280, 'subsample': 0.8613925962373125, 'colsample_bytree': 0.6795615516174235, 'min_child_weight': 4, 'gamma': 4.0636122599776865}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  44%|████▍     | 44/100 [05:13<04:03,  4.35s/it]

[I 2025-11-10 13:38:14,942] Trial 42 finished with value: 0.8036363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.012149310693935947, 'n_estimators': 566, 'subsample': 0.6347304484666022, 'colsample_bytree': 0.9720614980033867, 'min_child_weight': 1, 'gamma': 4.147641757743193}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  45%|████▌     | 45/100 [05:22<05:03,  5.52s/it]

[I 2025-11-10 13:38:23,191] Trial 44 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.02324364010385834, 'n_estimators': 274, 'subsample': 0.6754713481100204, 'colsample_bytree': 0.7363662395542526, 'min_child_weight': 8, 'gamma': 2.218707355517785}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  46%|████▌     | 46/100 [05:25<04:24,  4.89s/it]

[I 2025-11-10 13:38:26,622] Trial 45 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.010698406414745534, 'n_estimators': 256, 'subsample': 0.6755775760082519, 'colsample_bytree': 0.7478546489626212, 'min_child_weight': 8, 'gamma': 2.0465999572448643}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  47%|████▋     | 47/100 [05:28<03:46,  4.28s/it]

[I 2025-11-10 13:38:29,476] Trial 46 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.024548976125953515, 'n_estimators': 275, 'subsample': 0.6711541400608251, 'colsample_bytree': 0.7424784313756093, 'min_child_weight': 8, 'gamma': 4.73754425249699}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  48%|████▊     | 48/100 [05:30<03:03,  3.54s/it]

[I 2025-11-10 13:38:31,274] Trial 47 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.024133490586098337, 'n_estimators': 274, 'subsample': 0.6769508869683408, 'colsample_bytree': 0.7337457812075856, 'min_child_weight': 8, 'gamma': 2.2001293364828527}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  49%|████▉     | 49/100 [05:31<02:25,  2.86s/it]

[I 2025-11-10 13:38:32,550] Trial 48 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.026905616823687088, 'n_estimators': 161, 'subsample': 0.7808676729858322, 'colsample_bytree': 0.7896917128230285, 'min_child_weight': 6, 'gamma': 4.507525875988849}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  50%|█████     | 50/100 [05:36<02:52,  3.45s/it]

[I 2025-11-10 13:38:37,388] Trial 50 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.07508028700492608, 'n_estimators': 149, 'subsample': 0.7227105613222629, 'colsample_bytree': 0.7842229177073908, 'min_child_weight': 6, 'gamma': 1.270902109635943}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  51%|█████     | 51/100 [05:41<03:19,  4.06s/it]

[I 2025-11-10 13:38:42,877] Trial 49 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.024803573795446742, 'n_estimators': 311, 'subsample': 0.7219039522321108, 'colsample_bytree': 0.7820829592958106, 'min_child_weight': 6, 'gamma': 4.643500643278033}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  52%|█████▏    | 52/100 [05:46<03:22,  4.23s/it]

[I 2025-11-10 13:38:47,494] Trial 51 finished with value: 0.8136363636363637 and parameters: {'max_depth': 9, 'learning_rate': 0.03445035952455888, 'n_estimators': 317, 'subsample': 0.6172000920729331, 'colsample_bytree': 0.7800021513415887, 'min_child_weight': 6, 'gamma': 1.215740346241985}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  53%|█████▎    | 53/100 [05:47<02:31,  3.23s/it]

[I 2025-11-10 13:38:48,390] Trial 52 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.034600552319567185, 'n_estimators': 316, 'subsample': 0.6114903789990772, 'colsample_bytree': 0.6044606843008214, 'min_child_weight': 6, 'gamma': 1.2571723207126015}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  54%|█████▍    | 54/100 [05:51<02:48,  3.65s/it]

[I 2025-11-10 13:38:53,036] Trial 53 finished with value: 0.8136363636363637 and parameters: {'max_depth': 9, 'learning_rate': 0.031528338893243295, 'n_estimators': 315, 'subsample': 0.6107178403636543, 'colsample_bytree': 0.6077648951846906, 'min_child_weight': 7, 'gamma': 3.1280525609145964}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  55%|█████▌    | 55/100 [06:01<04:00,  5.35s/it]

[I 2025-11-10 13:39:02,361] Trial 54 finished with value: 0.8136363636363637 and parameters: {'max_depth': 9, 'learning_rate': 0.032034009657328694, 'n_estimators': 401, 'subsample': 0.601686539849879, 'colsample_bytree': 0.6090570538936324, 'min_child_weight': 10, 'gamma': 3.7826544441497285}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  56%|█████▌    | 56/100 [06:10<04:50,  6.60s/it]

[I 2025-11-10 13:39:11,880] Trial 56 finished with value: 0.8136363636363637 and parameters: {'max_depth': 9, 'learning_rate': 0.0543319524184569, 'n_estimators': 491, 'subsample': 0.5647821206616721, 'colsample_bytree': 0.689118074287827, 'min_child_weight': 10, 'gamma': 3.24068576796542}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  57%|█████▋    | 57/100 [06:11<03:21,  4.68s/it]

[I 2025-11-10 13:39:12,085] Trial 55 finished with value: 0.8136363636363637 and parameters: {'max_depth': 9, 'learning_rate': 0.06598367259382512, 'n_estimators': 482, 'subsample': 0.5763042269845358, 'colsample_bytree': 0.6003144920540812, 'min_child_weight': 9, 'gamma': 3.8391352017330154}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  58%|█████▊    | 58/100 [06:15<03:19,  4.75s/it]

[I 2025-11-10 13:39:16,994] Trial 57 finished with value: 0.8136363636363637 and parameters: {'max_depth': 9, 'learning_rate': 0.05419796424759923, 'n_estimators': 490, 'subsample': 0.5799960292661321, 'colsample_bytree': 0.715016653084461, 'min_child_weight': 10, 'gamma': 3.6935830311678814}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  59%|█████▉    | 59/100 [06:24<04:03,  5.93s/it]

[I 2025-11-10 13:39:25,668] Trial 58 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.06555124212471375, 'n_estimators': 478, 'subsample': 0.5663665732752099, 'colsample_bytree': 0.6911688528390909, 'min_child_weight': 9, 'gamma': 3.6420543282342344}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  60%|██████    | 60/100 [06:40<05:57,  8.94s/it]

[I 2025-11-10 13:39:41,621] Trial 59 finished with value: 0.8136363636363637 and parameters: {'max_depth': 10, 'learning_rate': 0.09541032339089585, 'n_estimators': 614, 'subsample': 0.7737993983892526, 'colsample_bytree': 0.709304781147005, 'min_child_weight': 9, 'gamma': 3.7989345247803237}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  61%|██████    | 61/100 [06:46<05:14,  8.07s/it]

[I 2025-11-10 13:39:47,675] Trial 61 finished with value: 0.8136363636363637 and parameters: {'max_depth': 10, 'learning_rate': 0.051468010547828486, 'n_estimators': 624, 'subsample': 0.7957395278925081, 'colsample_bytree': 0.6606833043316298, 'min_child_weight': 7, 'gamma': 1.731126394823403}. Best is trial 4 with value: 0.8136363636363637.
[I 2025-11-10 13:39:47,677] Trial 60 finished with value: 0.8136363636363637 and parameters: {'max_depth': 10, 'learning_rate': 0.049523882459627765, 'n_estimators': 686, 'subsample': 0.7836890047890145, 'colsample_bytree': 0.7043038504407517, 'min_child_weight': 7, 'gamma': 3.6858899771223768}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  63%|██████▎   | 63/100 [06:55<03:56,  6.40s/it]

[I 2025-11-10 13:39:56,582] Trial 62 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.0950360005431514, 'n_estimators': 632, 'subsample': 0.9620034448835857, 'colsample_bytree': 0.5212743935361428, 'min_child_weight': 7, 'gamma': 2.661175854639188}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  64%|██████▍   | 64/100 [07:26<07:26, 12.39s/it]

[I 2025-11-10 13:40:27,150] Trial 63 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.04333465471969946, 'n_estimators': 934, 'subsample': 0.9688971457077467, 'colsample_bytree': 0.5221666819957761, 'min_child_weight': 5, 'gamma': 4.368589578915669}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  65%|██████▌   | 65/100 [07:34<06:33, 11.23s/it]

[I 2025-11-10 13:40:35,100] Trial 64 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.07176403221988455, 'n_estimators': 961, 'subsample': 0.5152852647027791, 'colsample_bytree': 0.5203887526735262, 'min_child_weight': 5, 'gamma': 2.668277856506055}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 65. Best value: 0.823636:  66%|██████▌   | 66/100 [07:40<05:33,  9.80s/it]

[I 2025-11-10 13:40:41,080] Trial 65 finished with value: 0.8236363636363638 and parameters: {'max_depth': 5, 'learning_rate': 0.08001257951806276, 'n_estimators': 998, 'subsample': 0.7017966259166858, 'colsample_bytree': 0.8107701969894145, 'min_child_weight': 5, 'gamma': 2.667370889853929}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  67%|██████▋   | 67/100 [07:42<04:14,  7.72s/it]

[I 2025-11-10 13:40:43,434] Trial 66 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.042014912744446936, 'n_estimators': 959, 'subsample': 0.5310290403260794, 'colsample_bytree': 0.7662933081836284, 'min_child_weight': 5, 'gamma': 0.29770526238425}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  68%|██████▊   | 68/100 [07:55<05:00,  9.38s/it]

[I 2025-11-10 13:40:56,967] Trial 70 finished with value: 0.7936363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.08068928092712355, 'n_estimators': 237, 'subsample': 0.7038850388739296, 'colsample_bytree': 0.8119305312419037, 'min_child_weight': 4, 'gamma': 0.7953416687005204}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  69%|██████▉   | 69/100 [08:08<05:22, 10.40s/it]

[I 2025-11-10 13:41:09,883] Trial 67 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.08164035213932821, 'n_estimators': 873, 'subsample': 0.5226389629563558, 'colsample_bytree': 0.8086782630392862, 'min_child_weight': 8, 'gamma': 0.7547097213343048}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  70%|███████   | 70/100 [08:17<05:01, 10.04s/it]

[I 2025-11-10 13:41:19,031] Trial 68 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.0835109855077596, 'n_estimators': 892, 'subsample': 0.5336592301829232, 'colsample_bytree': 0.8274281284794538, 'min_child_weight': 8, 'gamma': 0.7777255963607783}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  71%|███████   | 71/100 [08:27<04:48,  9.94s/it]

[I 2025-11-10 13:41:28,732] Trial 69 finished with value: 0.8036363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.08407326577365341, 'n_estimators': 877, 'subsample': 0.6889403063993729, 'colsample_bytree': 0.8230776475717678, 'min_child_weight': 4, 'gamma': 0.8564048722256367}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  72%|███████▏  | 72/100 [08:37<04:37,  9.90s/it]

[I 2025-11-10 13:41:38,535] Trial 73 finished with value: 0.7936363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.07748946287770372, 'n_estimators': 383, 'subsample': 0.6909042236146286, 'colsample_bytree': 0.5870470793480158, 'min_child_weight': 4, 'gamma': 2.42521501766473}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  73%|███████▎  | 73/100 [08:43<03:56,  8.76s/it]

[I 2025-11-10 13:41:44,614] Trial 71 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.0855640249436848, 'n_estimators': 995, 'subsample': 0.761819361265675, 'colsample_bytree': 0.8335901991364265, 'min_child_weight': 8, 'gamma': 2.4168379771278063}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  74%|███████▍  | 74/100 [08:55<04:13,  9.75s/it]

[I 2025-11-10 13:41:56,676] Trial 72 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.08632452950158045, 'n_estimators': 995, 'subsample': 0.7315278316597038, 'colsample_bytree': 0.5903561641602021, 'min_child_weight': 8, 'gamma': 2.34614483591164}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  75%|███████▌  | 75/100 [09:08<04:28, 10.76s/it]

[I 2025-11-10 13:42:09,812] Trial 76 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.07250750015560423, 'n_estimators': 522, 'subsample': 0.7297425227139328, 'colsample_bytree': 0.5462634016320622, 'min_child_weight': 9, 'gamma': 1.9188049378969172}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  76%|███████▌  | 76/100 [09:18<04:12, 10.52s/it]

[I 2025-11-10 13:42:19,759] Trial 74 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.06332725819591804, 'n_estimators': 988, 'subsample': 0.6610568053142014, 'colsample_bytree': 0.5872928586718725, 'min_child_weight': 9, 'gamma': 0.032628344529039066}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  77%|███████▋  | 77/100 [09:22<03:13,  8.39s/it]

[I 2025-11-10 13:42:23,182] Trial 77 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.062140870973859806, 'n_estimators': 522, 'subsample': 0.6582262796186323, 'colsample_bytree': 0.7214251866068306, 'min_child_weight': 9, 'gamma': 0.26076416454488077}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  78%|███████▊  | 78/100 [09:27<02:41,  7.35s/it]

[I 2025-11-10 13:42:28,095] Trial 75 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.06366845048602891, 'n_estimators': 990, 'subsample': 0.7294817530236208, 'colsample_bytree': 0.5512592863059715, 'min_child_weight': 9, 'gamma': 1.481343006563347}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  79%|███████▉  | 79/100 [09:36<02:46,  7.92s/it]

[I 2025-11-10 13:42:37,338] Trial 81 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.020485446576397042, 'n_estimators': 180, 'subsample': 0.7137838495879578, 'colsample_bytree': 0.8926421529900531, 'min_child_weight': 7, 'gamma': 3.3124829061004224}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  80%|████████  | 80/100 [09:50<03:14,  9.73s/it]

[I 2025-11-10 13:42:51,315] Trial 78 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.06351149152408592, 'n_estimators': 822, 'subsample': 0.6576111551840773, 'colsample_bytree': 0.6279361004311806, 'min_child_weight': 9, 'gamma': 1.4902283337574302}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  81%|████████  | 81/100 [09:59<02:59,  9.47s/it]

[I 2025-11-10 13:43:00,173] Trial 80 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.06931613201872797, 'n_estimators': 757, 'subsample': 0.6309952206377424, 'colsample_bytree': 0.6446194792524996, 'min_child_weight': 7, 'gamma': 0.5378289913892484}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  82%|████████▏ | 82/100 [10:07<02:45,  9.20s/it]

[I 2025-11-10 13:43:08,760] Trial 79 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.05686750570492534, 'n_estimators': 920, 'subsample': 0.5000066279148162, 'colsample_bytree': 0.6256523865243385, 'min_child_weight': 7, 'gamma': 1.4353595255777138}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  83%|████████▎ | 83/100 [10:14<02:22,  8.37s/it]

[I 2025-11-10 13:43:15,188] Trial 82 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.05767878599510934, 'n_estimators': 774, 'subsample': 0.625878846996287, 'colsample_bytree': 0.7616043955963373, 'min_child_weight': 5, 'gamma': 1.3964388267231427}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  84%|████████▍ | 84/100 [10:26<02:34,  9.68s/it]

[I 2025-11-10 13:43:27,903] Trial 83 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.05677835448458094, 'n_estimators': 770, 'subsample': 0.6300761314669379, 'colsample_bytree': 0.6565613559306183, 'min_child_weight': 5, 'gamma': 0.528335075607653}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  85%|████████▌ | 85/100 [10:31<02:04,  8.31s/it]

[I 2025-11-10 13:43:33,023] Trial 85 finished with value: 0.8036363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.06849601960199957, 'n_estimators': 453, 'subsample': 0.846885407266223, 'colsample_bytree': 0.948695188061978, 'min_child_weight': 5, 'gamma': 4.882974069365169}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  86%|████████▌ | 86/100 [10:32<01:22,  5.90s/it]

[I 2025-11-10 13:43:33,284] Trial 84 finished with value: 0.8136363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.0576175994153275, 'n_estimators': 700, 'subsample': 0.8248190506471488, 'colsample_bytree': 0.9623585547563784, 'min_child_weight': 6, 'gamma': 4.817552476119154}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  87%|████████▋ | 87/100 [10:46<01:50,  8.48s/it]

[I 2025-11-10 13:43:47,779] Trial 86 finished with value: 0.8136363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.07433681328989329, 'n_estimators': 678, 'subsample': 0.8944665601651816, 'colsample_bytree': 0.9411671970864536, 'min_child_weight': 5, 'gamma': 4.963701431154417}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  88%|████████▊ | 88/100 [11:00<01:59,  9.93s/it]

[I 2025-11-10 13:44:01,118] Trial 87 finished with value: 0.8136363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.07524876353611702, 'n_estimators': 694, 'subsample': 0.826399331749387, 'colsample_bytree': 0.996237430082452, 'min_child_weight': 5, 'gamma': 4.872705182676401}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  89%|████████▉ | 89/100 [11:06<01:36,  8.77s/it]

[I 2025-11-10 13:44:07,164] Trial 89 finished with value: 0.7845454545454545 and parameters: {'max_depth': 6, 'learning_rate': 0.07417672338095418, 'n_estimators': 710, 'subsample': 0.9107852769379753, 'colsample_bytree': 0.9049902492902011, 'min_child_weight': 4, 'gamma': 4.4018641903195235}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  90%|█████████ | 90/100 [11:09<01:12,  7.22s/it]

[I 2025-11-10 13:44:10,787] Trial 88 finished with value: 0.8136363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.07324452030514073, 'n_estimators': 710, 'subsample': 0.9061105884927549, 'colsample_bytree': 0.9260410939820967, 'min_child_weight': 6, 'gamma': 4.259425202746808}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  91%|█████████ | 91/100 [11:20<01:14,  8.33s/it]

[I 2025-11-10 13:44:21,682] Trial 90 finished with value: 0.8136363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.0888017686965733, 'n_estimators': 714, 'subsample': 0.5966272503476178, 'colsample_bytree': 0.9111043422903858, 'min_child_weight': 10, 'gamma': 3.03400357044024}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  92%|█████████▏| 92/100 [11:22<00:52,  6.54s/it]

[I 2025-11-10 13:44:24,045] Trial 93 finished with value: 0.8136363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.08929855312926444, 'n_estimators': 240, 'subsample': 0.5954401997191388, 'colsample_bytree': 0.7302438513924584, 'min_child_weight': 10, 'gamma': 3.006979214047333}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  93%|█████████▎| 93/100 [11:24<00:35,  5.11s/it]

[I 2025-11-10 13:44:25,826] Trial 92 finished with value: 0.8136363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.08859543516482382, 'n_estimators': 377, 'subsample': 0.5921633922206863, 'colsample_bytree': 0.5005025252801152, 'min_child_weight': 6, 'gamma': 3.061074565458107}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  94%|█████████▍| 94/100 [11:32<00:35,  6.00s/it]

[I 2025-11-10 13:44:33,884] Trial 91 finished with value: 0.8136363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.06701483944094813, 'n_estimators': 653, 'subsample': 0.9288625252571733, 'colsample_bytree': 0.9054477005330187, 'min_child_weight': 6, 'gamma': 4.449347831924835}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  95%|█████████▌| 95/100 [11:47<00:43,  8.75s/it]

[I 2025-11-10 13:44:49,051] Trial 94 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.07822525723702405, 'n_estimators': 550, 'subsample': 0.5880431808934299, 'colsample_bytree': 0.5606937641491855, 'min_child_weight': 6, 'gamma': 0.9141734545021115}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  96%|█████████▌| 96/100 [11:54<00:32,  8.20s/it]

[I 2025-11-10 13:44:55,972] Trial 95 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.0772443124352036, 'n_estimators': 601, 'subsample': 0.874855680410721, 'colsample_bytree': 0.6687412757392796, 'min_child_weight': 6, 'gamma': 1.802577727141083}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  97%|█████████▋| 97/100 [11:56<00:18,  6.24s/it]

[I 2025-11-10 13:44:57,657] Trial 96 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.06994067756447428, 'n_estimators': 657, 'subsample': 0.7563376441956012, 'colsample_bytree': 0.5584606326785528, 'min_child_weight': 6, 'gamma': 1.670687567138181}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  98%|█████████▊| 98/100 [12:00<00:10,  5.49s/it]

[I 2025-11-10 13:45:01,383] Trial 97 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.07783264632541503, 'n_estimators': 604, 'subsample': 0.5528024399990554, 'colsample_bytree': 0.5651168356090639, 'min_child_weight': 8, 'gamma': 0.9279264988703535}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  99%|█████████▉| 99/100 [12:07<00:05,  5.99s/it]

[I 2025-11-10 13:45:08,541] Trial 98 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.07044292745655996, 'n_estimators': 602, 'subsample': 0.8669882446669668, 'colsample_bytree': 0.6650198517560678, 'min_child_weight': 8, 'gamma': 1.6224998403790343}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636: 100%|██████████| 100/100 [12:13<00:00,  7.34s/it]

[I 2025-11-10 13:45:14,718] Trial 99 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.0693070056729431, 'n_estimators': 855, 'subsample': 0.9975020518277293, 'colsample_bytree': 0.573228964957697, 'min_child_weight': 8, 'gamma': 1.1153908844214375}. Best is trial 65 with value: 0.8236363636363638.

Best parameters: {'max_depth': 5, 'learning_rate': 0.08001257951806276, 'n_estimators': 998, 'subsample': 0.7017966259166858, 'colsample_bytree': 0.8107701969894145, 'min_child_weight': 5, 'gamma': 2.667370889853929}

In [81]:
import sys, pkgutil
print("Python:", sys.executable)
print("plotly installed?", pkgutil.find_loader("plotly") is not None)

Python: c:\Users\tenNovy\miniconda3\envs\dolphin\python.exe
plotly installed? True

In [82]:
import sys
!{sys.executable} -m pip install -U "optuna[visualization]" plotly kaleido
# (Conda option) conda install -c conda-forge python-kaleido plotly

Requirement already satisfied: plotly in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (6.4.0)
Requirement already satisfied: kaleido in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (1.2.0)
Requirement already satisfied: optuna[visualization] in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (4.6.0)
Requirement already satisfied: alembic>=1.5.0 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from optuna[visualization]) (1.17.1)
Requirement already satisfied: colorlog in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from optuna[visualization]) (6.10.1)
Requirement already satisfied: numpy in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from optuna[visualization]) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from optuna[visualization]) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from optuna[visualization]) (2.0.44)
Requirement already satisfied: tqdm in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from optuna[visualization]) (4.67.1)
Requirement already satisfied: PyYAML in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from optuna[visualization]) (6.0.3)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from plotly) (2.10.2)
Requirement already satisfied: choreographer>=1.1.1 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from kaleido) (1.2.1)
Requirement already satisfied: logistro>=1.0.8 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from kaleido) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from kaleido) (3.11.4)
Requirement already satisfied: pytest-timeout>=2.4.0 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from kaleido) (2.4.0)
Requirement already satisfied: Mako in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from alembic>=1.5.0->optuna[visualization]) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from alembic>=1.5.0->optuna[visualization]) (4.12.2)
Requirement already satisfied: simplejson>=3.19.3 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from choreographer>=1.1.1->kaleido) (3.20.2)
Requirement already satisfied: pytest>=7.0.0 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from pytest-timeout>=2.4.0->kaleido) (9.0.0)
Requirement already satisfied: greenlet>=1 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from sqlalchemy>=1.4.2->optuna[visualization]) (3.2.4)
Requirement already satisfied: colorama in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from colorlog->optuna[visualization]) (0.4.6)
Requirement already satisfied: iniconfig>=1.0.1 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.19.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from Mako->alembic>=1.5.0->optuna[visualization]) (3.0.3)

WARNING: optuna 4.6.0 does not provide the extra 'visualization'

In [83]:
import plotly.io as pio
pio.renderers.default = "notebook_connected"  # or "vscode", "browser"

In [86]:
from plotly.io import show
import optuna.visualization as vis

fig = vis.plot_optimization_history(study)
show(fig)

In [ ]:

from plotly.io import show
import optuna.visualization as vis

fig = vis.plot_optimization_history(study)
show(fig)

In [ ]:

fig = vis.plot_contour(study, params = ["","max_depth"])
show(fig)

[W 2025-11-10 13:51:09,763] The length of params must be greater than 1.

In [88]:

from sklearn.metrics import accuracy_score, classification_report

X, y = x_y_split(df_3_1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Train the model with the best parameters
best_model = xgb.XGBClassifier(**best_params)
best_model.fit(X_train, y_train)

# Predict the test data
y_pred = best_model.predict(X_test)

# Calculate the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# Generate a classification report
cr = classification_report(y_test, y_pred)
print(f"\nReport:\n{cr}")

Accuracy: 0.6888888888888889

Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        14
           1       0.69      1.00      0.82        31

    accuracy                           0.69        45
   macro avg       0.34      0.50      0.41        45
weighted avg       0.47      0.69      0.56        45

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

In [ ]:
datasets = {
    "3_1": df_3_1,
    "3_2": df_3_2,
    # ... add all 13
}

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    n_trials=100,
    n_splits=5,
    output_dir="xgb_results",
)
print(summary)

In [103]:
import os, json
import numpy as np
import pandas as pd
import optuna, xgboost as xgb
from typing import Dict, Tuple
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.metrics import (
    balanced_accuracy_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    RocCurveDisplay,
    ConfusionMatrixDisplay,
)

# def x_y_split(df): ...  # your splitter (must return X, y)

def _pick_device():
    try:
        _ = xgb.core.get_cuda_compute_capabilities()
        return {"tree_method": "hist", "device": "cuda"}
    except Exception:
        return {"tree_method": "hist", "device": "cpu"}

def _ensure_dir(path: str):
    os.makedirs(path, exist_ok=True)

def _save_json(d: dict, path: str):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(d, f, indent=2, ensure_ascii=False)

def make_xgb_objective(X, y, scoring: str = "balanced_accuracy", n_splits: int = 5, random_state: int = 42):
    if scoring == "balanced_accuracy":
        from sklearn.metrics import balanced_accuracy_score as metric_fn
        needs_proba = False
        eval_metric = "logloss"
    elif scoring == "roc_auc":
        from sklearn.metrics import roc_auc_score as metric_fn
        needs_proba = True
        eval_metric = "auc"
    else:
        raise ValueError("scoring must be 'balanced_accuracy' or 'roc_auc'")

    folds = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    device_kwargs = _pick_device()

    pos_ratio = float(np.mean(y))
    scale_pos_weight = ((1.0 - pos_ratio) / pos_ratio) if 0 < pos_ratio < 1 else 1.0

    def objective(trial: optuna.Trial) -> float:
        params = {
            "max_depth": trial.suggest_int("max_depth", 3, 10),
            "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
            "n_estimators": trial.suggest_int("n_estimators", 200, 1500),
            "subsample": trial.suggest_float("subsample", 0.5, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
            "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
            "gamma": trial.suggest_float("gamma", 0.0, 5.0),
            "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
            "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
            "max_delta_step": trial.suggest_int("max_delta_step", 0, 10),
            "objective": "binary:logistic",
            "eval_metric": eval_metric,
            "n_jobs": 1,  # keep each trial single-threaded
            "scale_pos_weight": scale_pos_weight,
            **device_kwargs,
        }

        scores = []
        for tr_idx, va_idx in folds.split(X, y):
            if hasattr(X, "iloc"):
                X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
                y_tr, y_va = y.iloc[tr_idx], y.iloc[va_idx]
            else:
                X_tr, X_va = X[tr_idx], X[va_idx]
                y_tr, y_va = y[tr_idx], y[va_idx]

            model = xgb.XGBClassifier(**params)
            model.fit(
                X_tr, y_tr,
                eval_set=[(X_va, y_va)],
                #early_stopping_rounds=50,
                verbose=False,
            )

            if needs_proba:
                y_score = model.predict_proba(X_va)[:, 1]
                score = metric_fn(y_va, y_score)
            else:
                y_pred = model.predict(X_va)
                score = metric_fn(y_va, y_pred)
            scores.append(score)

            trial.report(np.mean(scores), len(scores))
            if trial.should_prune():
                raise optuna.TrialPruned()

        return float(np.mean(scores))

    return objective

def _evaluate_and_save(name: str, model, X_test, y_test, out_dir: str):
    """Compute metrics, plot ROC + confusion matrix, and save everything."""
    _ensure_dir(out_dir)

    # Predictions
    y_proba = None
    try:
        y_proba = model.predict_proba(X_test)[:, 1]
    except Exception:
        pass
    y_pred = model.predict(X_test)

    # Metrics
    metrics = {}
    metrics["balanced_accuracy"] = float(balanced_accuracy_score(y_test, y_pred))
    # ROC-AUC if both classes present and proba available
    try:
        if y_proba is not None and len(np.unique(y_test)) == 2:
            metrics["roc_auc"] = float(roc_auc_score(y_test, y_proba))
        else:
            metrics["roc_auc"] = None
    except Exception:
        metrics["roc_auc"] = None

    # Classification report (as dict)
    try:
        metrics["classification_report"] = classification_report(y_test, y_pred, output_dict=True)
    except Exception:
        metrics["classification_report"] = None

    # Confusion matrix plot
    try:
        cm = confusion_matrix(y_test, y_pred)
        disp = ConfusionMatrixDisplay(cm)
        import matplotlib.pyplot as plt
        plt.figure()
        disp.plot(values_format="d")
        plt.title(f"Confusion Matrix — {name}")
        plt.savefig(os.path.join(out_dir, "confusion_matrix.png"), dpi=200, bbox_inches="tight")
        plt.close()
    except Exception:
        pass

    # ROC curve plot
    try:
        if y_proba is not None and len(np.unique(y_test)) == 2:
            import matplotlib.pyplot as plt
            plt.figure()
            RocCurveDisplay.from_predictions(y_test, y_proba)
            plt.title(f"ROC Curve — {name}")
            plt.savefig(os.path.join(out_dir, "roc_curve.png"), dpi=200, bbox_inches="tight")
            plt.close()
    except Exception:
        pass

    # Save metrics JSON
    _save_json(metrics, os.path.join(out_dir, "metrics.json"))
    return metrics

def optimize_many(
    dfs: Dict[str, pd.DataFrame],
    x_y_split_fn,
    scoring: str = "balanced_accuracy",
    n_trials: int = 100,
    n_splits: int = 5,
    random_state: int = 42,
    n_jobs_trials: int = -1,
    output_dir: str = "xgb_results",
    test_size: float = 0.20,
) -> Tuple[pd.DataFrame, Dict[str, xgb.XGBClassifier], Dict[str, optuna.Study]]:
    """
    Runs Optuna per dataset, evaluates on a held-out test set,
    and saves plots + metrics in output_dir/<dataset_name>/
    """
    results = []
    best_models: Dict[str, xgb.XGBClassifier] = {}
    studies: Dict[str, optuna.Study] = {}

    _ensure_dir(output_dir)

    for name, df in dfs.items():
        X, y = x_y_split_fn(df)

        # To numpy for fast indexing, but keep DataFrame support
        X_arr = X.values if hasattr(X, "values") else X
        y_arr = y.values if hasattr(y, "values") else y

        # Hold-out test split (kept untouched for final evaluation)
        X_train, X_test, y_train, y_test = train_test_split(
            X_arr, y_arr, test_size=test_size, random_state=random_state, stratify=y_arr
        )

        # Build objective on TRAIN ONLY
        objective = make_xgb_objective(X_train, y_train, scoring=scoring, n_splits=n_splits, random_state=random_state)

        study = optuna.create_study(
            study_name=f"{name}_{scoring}",
            direction="maximize",
            sampler=optuna.samplers.TPESampler(seed=random_state),
            pruner=optuna.pruners.MedianPruner(n_startup_trials=10),
        )
        study.optimize(objective, n_trials=n_trials, show_progress_bar=True, n_jobs=n_jobs_trials)
        studies[name] = study

        # Train final model on TRAIN using best params (with small VA split for early stopping)
        device_kwargs = _pick_device()
        pos_ratio = float(np.mean(y_train))
        spw = ((1.0 - pos_ratio) / pos_ratio) if 0 < pos_ratio < 1 else 1.0

        best_params = {
            **study.best_params,
            "objective": "binary:logistic",
            "eval_metric": "auc" if scoring == "roc_auc" else "logloss",
            "n_jobs": 0,
            "scale_pos_weight": spw,
            **device_kwargs,
        }
        final_model = xgb.XGBClassifier(**best_params)

        # Early stopping split inside TRAIN
        X_tr, X_va, y_tr, y_va = train_test_split(
            X_train, y_train, test_size=0.15, random_state=random_state, stratify=y_train
        )
        final_model.fit(
            X_tr, y_tr,
            eval_set=[(X_va, y_va)],
            #early_stopping_rounds=50,
            verbose=False,
        )

        # Save per-dataset artifacts
        ds_out = os.path.join(output_dir, name)
        _ensure_dir(ds_out)

        # Evaluate on TEST and save plots/metrics
        metrics = _evaluate_and_save(name, final_model, X_test, y_test, ds_out)

        # Save best params + study summary
        _save_json({"best_params": study.best_params, "best_value": study.best_value}, os.path.join(ds_out, "best.json"))

        # Optional: save model
        try:
            import joblib
            joblib.dump(final_model, os.path.join(ds_out, "model.joblib"))
        except Exception:
            pass

        best_models[name] = final_model
        results.append({
            "dataset": name,
            "cv_best_value": study.best_value,
            "test_balanced_accuracy": metrics.get("balanced_accuracy"),
            "test_roc_auc": metrics.get("roc_auc"),
            "n_trials": len(study.trials),
        })

    summary_df = pd.DataFrame(results).sort_values(by="test_balanced_accuracy", ascending=False).reset_index(drop=True)
    # Save a global summary too
    summary_df.to_csv(os.path.join(output_dir, "summary.csv"), index=False)
    return summary_df, best_models, studies

In [104]:
datasets = task_freq_dfs

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    n_trials=200,
    n_splits=5,
    output_dir="xgb_results",
)
print(summary)

[I 2025-11-10 14:08:10,400] A new study created in memory with name: 1_1_balanced_accuracy
Best trial: 3. Best value: 0.5:   0%|          | 1/200 [00:03<10:32,  3.18s/it]

[I 2025-11-10 14:08:13,571] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.048266717457626784, 'n_estimators': 751, 'subsample': 0.615637322222104, 'colsample_bytree': 0.7584191568534198, 'min_child_weight': 8, 'gamma': 3.4260854731678907, 'reg_alpha': 5.379288797134016e-05, 'reg_lambda': 3.603078631881983, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   1%|          | 2/200 [00:04<05:59,  1.82s/it]

[I 2025-11-10 14:08:14,439] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.21587293847247946, 'n_estimators': 999, 'subsample': 0.9900796183059499, 'colsample_bytree': 0.5594715699164307, 'min_child_weight': 8, 'gamma': 1.8403960900404654, 'reg_alpha': 6.316297962136111e-08, 'reg_lambda': 0.07282625123096396, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   2%|▏         | 3/200 [00:06<07:17,  2.22s/it]

[I 2025-11-10 14:08:17,135] Trial 2 finished with value: 0.44397660818713447 and parameters: {'max_depth': 6, 'learning_rate': 0.012841192297365763, 'n_estimators': 1362, 'subsample': 0.9219440870853534, 'colsample_bytree': 0.7899972214837037, 'min_child_weight': 4, 'gamma': 3.528436229652801, 'reg_alpha': 1.9439590774457276e-05, 'reg_lambda': 0.05117218358267857, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   2%|▏         | 4/200 [00:07<04:57,  1.52s/it]

[I 2025-11-10 14:08:17,586] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.056227802405171765, 'n_estimators': 872, 'subsample': 0.8676905040154115, 'colsample_bytree': 0.9938923759460558, 'min_child_weight': 9, 'gamma': 3.417121745262901, 'reg_alpha': 6.40753957751729e-07, 'reg_lambda': 8.784837811700483e-08, 'max_delta_step': 0}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   2%|▎         | 5/200 [00:08<04:55,  1.52s/it]

[I 2025-11-10 14:08:19,096] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.042932559636600094, 'n_estimators': 284, 'subsample': 0.7468612262123348, 'colsample_bytree': 0.6510115028957751, 'min_child_weight': 9, 'gamma': 0.22945275122159714, 'reg_alpha': 0.006401716030018806, 'reg_lambda': 6.404832574395367e-06, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   3%|▎         | 6/200 [00:08<03:26,  1.07s/it]

[I 2025-11-10 14:08:19,285] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.18436689927445862, 'n_estimators': 1125, 'subsample': 0.6210027883164205, 'colsample_bytree': 0.860658675435515, 'min_child_weight': 10, 'gamma': 4.922330364643101, 'reg_alpha': 1.2345735247340377e-07, 'reg_lambda': 3.6916572828600274e-08, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   4%|▎         | 7/200 [00:09<03:01,  1.06it/s]

[I 2025-11-10 14:08:19,973] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08618554226484854, 'n_estimators': 632, 'subsample': 0.6451266237987092, 'colsample_bytree': 0.5085769931405466, 'min_child_weight': 10, 'gamma': 0.23299429371949787, 'reg_alpha': 1.0211185460751636e-06, 'reg_lambda': 7.222725026332201e-06, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   4%|▍         | 8/200 [00:10<03:02,  1.05it/s]

[I 2025-11-10 14:08:20,936] Trial 0 finished with value: 0.47976608187134506 and parameters: {'max_depth': 5, 'learning_rate': 0.016916838008207348, 'n_estimators': 1228, 'subsample': 0.6566526185448436, 'colsample_bytree': 0.9190080925188242, 'min_child_weight': 1, 'gamma': 1.4728511135741085, 'reg_alpha': 1.0564250260314212e-05, 'reg_lambda': 0.0001570666259226304, 'max_delta_step': 1}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   4%|▍         | 9/200 [00:11<03:08,  1.01it/s]

[I 2025-11-10 14:08:22,002] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.22565194875813754, 'n_estimators': 654, 'subsample': 0.9558404645191203, 'colsample_bytree': 0.906490389767255, 'min_child_weight': 10, 'gamma': 1.8823303158813143, 'reg_alpha': 5.039107159917156e-07, 'reg_lambda': 0.010553077707274839, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   5%|▌         | 10/200 [00:12<03:18,  1.04s/it]

[I 2025-11-10 14:08:23,179] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.034795571393397916, 'n_estimators': 911, 'subsample': 0.5129995518499123, 'colsample_bytree': 0.8344203670890229, 'min_child_weight': 8, 'gamma': 0.40421463856063544, 'reg_alpha': 1.5249090516644572e-08, 'reg_lambda': 0.0005595524305441581, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   6%|▌         | 11/200 [00:13<02:56,  1.07it/s]

[I 2025-11-10 14:08:23,862] Trial 10 finished with value: 0.4892397660818714 and parameters: {'max_depth': 8, 'learning_rate': 0.1527415619008579, 'n_estimators': 587, 'subsample': 0.9476782024686141, 'colsample_bytree': 0.6696297084722163, 'min_child_weight': 1, 'gamma': 4.752435040124521, 'reg_alpha': 0.001293439448963321, 'reg_lambda': 3.415976344976173e-05, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   6%|▌         | 12/200 [00:14<03:28,  1.11s/it]

[I 2025-11-10 14:08:25,378] Trial 12 finished with value: 0.49725146198830406 and parameters: {'max_depth': 3, 'learning_rate': 0.014852055016916032, 'n_estimators': 287, 'subsample': 0.964209967885078, 'colsample_bytree': 0.8186166426330905, 'min_child_weight': 2, 'gamma': 1.0398224997452155, 'reg_alpha': 0.016867740042961727, 'reg_lambda': 4.009785253595468e-08, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   6%|▋         | 13/200 [00:17<05:12,  1.67s/it]

[I 2025-11-10 14:08:28,333] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.09521321884042863, 'n_estimators': 1044, 'subsample': 0.811172304949748, 'colsample_bytree': 0.6951221803655677, 'min_child_weight': 6, 'gamma': 3.10983591383415, 'reg_alpha': 0.8187409870522303, 'reg_lambda': 4.49191510652106, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   7%|▋         | 14/200 [00:18<03:53,  1.25s/it]

[I 2025-11-10 14:08:28,626] Trial 11 finished with value: 0.49064327485380116 and parameters: {'max_depth': 6, 'learning_rate': 0.0632959621838723, 'n_estimators': 1382, 'subsample': 0.7206256092194179, 'colsample_bytree': 0.7060457932365221, 'min_child_weight': 2, 'gamma': 3.003587560320466, 'reg_alpha': 7.130030716668965e-08, 'reg_lambda': 1.8927451253226445e-08, 'max_delta_step': 0}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   8%|▊         | 15/200 [00:19<03:29,  1.13s/it]

[I 2025-11-10 14:08:29,481] Trial 13 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.13355855179046336, 'n_estimators': 1492, 'subsample': 0.811851725971969, 'colsample_bytree': 0.6257575212992053, 'min_child_weight': 6, 'gamma': 2.289474750251033, 'reg_alpha': 4.027876219466933, 'reg_lambda': 1.3874979112490065, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   8%|▊         | 16/200 [00:20<03:19,  1.08s/it]

[I 2025-11-10 14:08:30,452] Trial 15 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.0791223429093267, 'n_estimators': 1013, 'subsample': 0.8153120440048136, 'colsample_bytree': 0.7086532631644262, 'min_child_weight': 6, 'gamma': 2.8992339842514836, 'reg_alpha': 1.3305334573465002, 'reg_lambda': 8.608458932379971, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   8%|▊         | 17/200 [00:21<03:38,  1.20s/it]

[I 2025-11-10 14:08:31,911] Trial 18 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.296446829782424, 'n_estimators': 465, 'subsample': 0.529043188163618, 'colsample_bytree': 0.5559366755174382, 'min_child_weight': 7, 'gamma': 4.247153312770465, 'reg_alpha': 0.00011523325771614999, 'reg_lambda': 0.19314694205027413, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   9%|▉         | 18/200 [00:21<02:47,  1.09it/s]

[I 2025-11-10 14:08:32,183] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.024455094240337094, 'n_estimators': 726, 'subsample': 0.5010633618756429, 'colsample_bytree': 0.5466538644456888, 'min_child_weight': 7, 'gamma': 2.6361595160176603, 'reg_alpha': 5.8242563342423195e-05, 'reg_lambda': 3.5630541680755226, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  10%|▉         | 19/200 [00:22<02:15,  1.34it/s]

[I 2025-11-10 14:08:32,525] Trial 17 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.02772773462120597, 'n_estimators': 774, 'subsample': 0.504576806267886, 'colsample_bytree': 0.5681804631655497, 'min_child_weight': 7, 'gamma': 2.530757088492412, 'reg_alpha': 4.7235776921507134e-05, 'reg_lambda': 6.242033329705765, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  10%|█         | 20/200 [00:23<02:52,  1.04it/s]

[I 2025-11-10 14:08:33,980] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.02695763783299232, 'n_estimators': 754, 'subsample': 0.5218649325783863, 'colsample_bytree': 0.5777609980214088, 'min_child_weight': 8, 'gamma': 4.128467528291092, 'reg_alpha': 0.00011363994454011518, 'reg_lambda': 0.08226542822836697, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 22. Best value: 0.501754:  10%|█         | 21/200 [00:24<02:55,  1.02it/s]

[I 2025-11-10 14:08:35,010] Trial 22 finished with value: 0.5017543859649123 and parameters: {'max_depth': 3, 'learning_rate': 0.10837558619000484, 'n_estimators': 461, 'subsample': 0.6063537649855955, 'colsample_bytree': 0.7550156171441376, 'min_child_weight': 4, 'gamma': 4.010693461285667, 'reg_alpha': 0.11345069973183525, 'reg_lambda': 0.007441349068988221, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  11%|█         | 22/200 [00:24<02:13,  1.33it/s]

[I 2025-11-10 14:08:35,223] Trial 23 pruned.

Best trial: 22. Best value: 0.501754:  12%|█▏        | 23/200 [00:25<01:46,  1.67it/s]

[I 2025-11-10 14:08:35,470] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.020697905918685547, 'n_estimators': 733, 'subsample': 0.5730702964774617, 'colsample_bytree': 0.5933672737309299, 'min_child_weight': 4, 'gamma': 4.010812705887382, 'reg_alpha': 1.0903023139784145e-05, 'reg_lambda': 0.005038617938632568, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  12%|█▏        | 24/200 [00:25<01:50,  1.59it/s]

[I 2025-11-10 14:08:36,164] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.02772259243354577, 'n_estimators': 755, 'subsample': 0.5840251863221414, 'colsample_bytree': 0.753185757294888, 'min_child_weight': 4, 'gamma': 4.111998613360592, 'reg_alpha': 0.10078079554087256, 'reg_lambda': 0.002901168637624296, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  12%|█▎        | 25/200 [00:26<02:10,  1.34it/s]

[I 2025-11-10 14:08:37,184] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.12143441600502916, 'n_estimators': 436, 'subsample': 0.5897539175337351, 'colsample_bytree': 0.7553067666117038, 'min_child_weight': 4, 'gamma': 3.8487033222132383, 'reg_alpha': 0.06618683381973506, 'reg_lambda': 0.006609542941614817, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  14%|█▎        | 27/200 [00:27<01:26,  2.00it/s]

[I 2025-11-10 14:08:37,592] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.23536256753370977, 'n_estimators': 461, 'subsample': 0.571823074830894, 'colsample_bytree': 0.7541519052237451, 'min_child_weight': 4, 'gamma': 3.9129575788026454, 'reg_alpha': 0.0014246097394102497, 'reg_lambda': 0.3914652056631548, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:08:37,755] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.21819827346046186, 'n_estimators': 448, 'subsample': 0.6849586075466754, 'colsample_bytree': 0.7471143827085469, 'min_child_weight': 5, 'gamma': 3.6888422132121494, 'reg_alpha': 0.0009001017167450566, 'reg_lambda': 0.3559971332296791, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  14%|█▍        | 28/200 [00:28<01:38,  1.75it/s]

[I 2025-11-10 14:08:38,495] Trial 27 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.24024637301053678, 'n_estimators': 455, 'subsample': 0.6880689918198944, 'colsample_bytree': 0.7824423480880227, 'min_child_weight': 5, 'gamma': 1.4128523527058265, 'reg_alpha': 0.0011296265859394104, 'reg_lambda': 0.4863784117360405, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  14%|█▍        | 29/200 [00:29<02:15,  1.26it/s]

[I 2025-11-10 14:08:39,801] Trial 28 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.22544468558570568, 'n_estimators': 531, 'subsample': 0.709973582126965, 'colsample_bytree': 0.7221264609217941, 'min_child_weight': 5, 'gamma': 1.0056781533249022, 'reg_alpha': 0.0012199390174298527, 'reg_lambda': 0.4299204515927921, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  15%|█▌        | 30/200 [00:31<03:25,  1.21s/it]

[I 2025-11-10 14:08:41,974] Trial 30 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.16346629931378728, 'n_estimators': 940, 'subsample': 0.6993783572090314, 'colsample_bytree': 0.6339229161295411, 'min_child_weight': 8, 'gamma': 4.627593943503633, 'reg_alpha': 3.00888914351226e-06, 'reg_lambda': 0.02932470606289733, 'max_delta_step': 7}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  16%|█▌        | 31/200 [00:31<02:40,  1.06it/s]

[I 2025-11-10 14:08:42,315] Trial 29 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.044456896188511105, 'n_estimators': 962, 'subsample': 0.6821181038385433, 'colsample_bytree': 0.7996901015465947, 'min_child_weight': 5, 'gamma': 1.089927073139057, 'reg_alpha': 0.0007114440525791503, 'reg_lambda': 0.03110468443874737, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  16%|█▋        | 33/200 [00:32<01:51,  1.49it/s]

[I 2025-11-10 14:08:43,051] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04055795890684684, 'n_estimators': 978, 'subsample': 0.8952435806501184, 'colsample_bytree': 0.6174231263554479, 'min_child_weight': 8, 'gamma': 4.498388512372799, 'reg_alpha': 1.7976363294785763e-06, 'reg_lambda': 0.026581292482414014, 'max_delta_step': 7}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:08:43,225] Trial 33 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.04641845597401043, 'n_estimators': 219, 'subsample': 0.9938144820441012, 'colsample_bytree': 0.8724297784126948, 'min_child_weight': 9, 'gamma': 4.445388227719742, 'reg_alpha': 3.7793571901966087e-06, 'reg_lambda': 0.0009687098740781587, 'max_delta_step': 1}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  17%|█▋        | 34/200 [00:33<01:33,  1.78it/s]

[I 2025-11-10 14:08:43,530] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.061685748002600384, 'n_estimators': 208, 'subsample': 0.8782425043585517, 'colsample_bytree': 0.9801787677467191, 'min_child_weight': 9, 'gamma': 3.4436107442873416, 'reg_alpha': 1.2825998798566198e-08, 'reg_lambda': 0.00029822180308059344, 'max_delta_step': 0}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  18%|█▊        | 35/200 [00:34<01:57,  1.40it/s]

[I 2025-11-10 14:08:44,600] Trial 37 pruned.

Best trial: 22. Best value: 0.501754:  18%|█▊        | 36/200 [00:34<01:37,  1.68it/s]

[I 2025-11-10 14:08:44,915] Trial 32 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.042225263382705325, 'n_estimators': 993, 'subsample': 0.643672207349757, 'colsample_bytree': 0.8851984214129106, 'min_child_weight': 8, 'gamma': 4.665528855376378, 'reg_alpha': 2.166707122730778e-06, 'reg_lambda': 0.0303813986759047, 'max_delta_step': 1}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  18%|█▊        | 37/200 [00:36<03:03,  1.12s/it]

[I 2025-11-10 14:08:47,280] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.0640572238003097, 'n_estimators': 852, 'subsample': 0.8821903709008154, 'colsample_bytree': 0.9896465338878864, 'min_child_weight': 9, 'gamma': 3.375124359189933, 'reg_alpha': 1.7339535143417448e-07, 'reg_lambda': 0.0002390900259599066, 'max_delta_step': 0}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:08:47,310] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.06163195852410356, 'n_estimators': 869, 'subsample': 0.8723680192971583, 'colsample_bytree': 0.9964577967460275, 'min_child_weight': 9, 'gamma': 3.518743036302814, 'reg_alpha': 1.0586793618367925e-08, 'reg_lambda': 0.0003126549097971942, 'max_delta_step': 0}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  20%|█▉        | 39/200 [00:39<03:18,  1.23s/it]

[I 2025-11-10 14:08:50,003] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.10249494953330053, 'n_estimators': 1098, 'subsample': 0.6469672757891731, 'colsample_bytree': 0.9572576270733382, 'min_child_weight': 9, 'gamma': 3.267350533489603, 'reg_alpha': 3.194139864614852e-07, 'reg_lambda': 4.5559989065210885e-05, 'max_delta_step': 2}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:08:50,067] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.05450364714636726, 'n_estimators': 1087, 'subsample': 0.7588031847087612, 'colsample_bytree': 0.9310397449915003, 'min_child_weight': 10, 'gamma': 3.2759123482559422, 'reg_alpha': 5.616141985990145e-07, 'reg_lambda': 6.296382490846326e-07, 'max_delta_step': 2}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  22%|██▏       | 43/200 [00:42<02:18,  1.13it/s]

[I 2025-11-10 14:08:53,025] Trial 40 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1020565963527149, 'n_estimators': 1088, 'subsample': 0.7620242756998031, 'colsample_bytree': 0.9486905667413299, 'min_child_weight': 10, 'gamma': 1.9249888932565629, 'reg_alpha': 4.163439742975368e-07, 'reg_lambda': 5.8621626414649894e-05, 'max_delta_step': 2}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:08:53,069] Trial 41 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.10184262495892675, 'n_estimators': 1077, 'subsample': 0.7619389434551538, 'colsample_bytree': 0.9548844227545563, 'min_child_weight': 10, 'gamma': 2.113122070976769, 'reg_alpha': 3.109509894300446e-07, 'reg_lambda': 1.234976558470105e-06, 'max_delta_step': 2}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:08:53,177] Trial 42 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.03469846166225413, 'n_estimators': 635, 'subsample': 0.7774136192964303, 'colsample_bytree': 0.5201447529928596, 'min_child_weight': 10, 'gamma': 2.177642377496676, 'reg_alpha': 7.844439984339711e-07, 'reg_lambda': 1.1341896242648523e-06, 'max_delta_step': 4}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  22%|██▏       | 44/200 [00:43<02:28,  1.05it/s]

[I 2025-11-10 14:08:54,385] Trial 46 pruned.

Best trial: 22. Best value: 0.501754:  22%|██▎       | 45/200 [00:45<02:54,  1.13s/it]

[I 2025-11-10 14:08:56,108] Trial 43 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.010975834796068023, 'n_estimators': 1254, 'subsample': 0.7786476520210117, 'colsample_bytree': 0.8469057496628857, 'min_child_weight': 7, 'gamma': 2.1743818161070627, 'reg_alpha': 1.933886305957632e-05, 'reg_lambda': 2.490215532897426e-06, 'max_delta_step': 4}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  23%|██▎       | 46/200 [00:48<03:44,  1.46s/it]

[I 2025-11-10 14:08:58,600] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.17613249117505494, 'n_estimators': 1203, 'subsample': 0.6113265877950171, 'colsample_bytree': 0.8446863718229721, 'min_child_weight': 10, 'gamma': 2.689879295174101, 'reg_alpha': 3.728769849355372e-08, 'reg_lambda': 5.5085147110666175e-08, 'max_delta_step': 7}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:08:58,610] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1721987048305369, 'n_estimators': 1207, 'subsample': 0.6267365897085562, 'colsample_bytree': 0.86082363057436, 'min_child_weight': 10, 'gamma': 4.946699403724258, 'reg_alpha': 4.1137919220444174e-08, 'reg_lambda': 8.228968930526803e-08, 'max_delta_step': 7}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  24%|██▍       | 48/200 [00:49<02:55,  1.16s/it]

[I 2025-11-10 14:09:00,016] Trial 47 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1839925979906372, 'n_estimators': 1202, 'subsample': 0.5519368682694827, 'colsample_bytree': 0.8235768585261429, 'min_child_weight': 7, 'gamma': 4.961191507828394, 'reg_alpha': 3.814127436760651e-08, 'reg_lambda': 1.4504753903685653e-07, 'max_delta_step': 8}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  24%|██▍       | 49/200 [00:50<02:59,  1.19s/it]

[I 2025-11-10 14:09:01,338] Trial 48 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.15040701619914584, 'n_estimators': 1157, 'subsample': 0.6162966107185768, 'colsample_bytree': 0.6718931688430765, 'min_child_weight': 9, 'gamma': 4.907068536257872, 'reg_alpha': 3.141044298155542e-08, 'reg_lambda': 1.3439225340582253e-07, 'max_delta_step': 8}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:09:01,343] Trial 49 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.14336197556263494, 'n_estimators': 552, 'subsample': 0.9310789800634375, 'colsample_bytree': 0.6746718236075842, 'min_child_weight': 8, 'gamma': 4.927973843061391, 'reg_alpha': 0.003698599084701574, 'reg_lambda': 1.0546541278519497e-07, 'max_delta_step': 8}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  26%|██▌       | 51/200 [00:51<02:09,  1.15it/s]

[I 2025-11-10 14:09:02,096] Trial 51 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.28129550887500515, 'n_estimators': 343, 'subsample': 0.7327118426089829, 'colsample_bytree': 0.9051970119352585, 'min_child_weight': 9, 'gamma': 1.603133484650757, 'reg_alpha': 0.0041768301559188745, 'reg_lambda': 1.3138171193684608e-08, 'max_delta_step': 5}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  26%|██▌       | 52/200 [00:52<02:03,  1.20it/s]

[I 2025-11-10 14:09:02,795] Trial 54 pruned.

Best trial: 22. Best value: 0.501754:  26%|██▋       | 53/200 [00:52<01:39,  1.47it/s]

[I 2025-11-10 14:09:02,991] Trial 52 pruned.
[I 2025-11-10 14:09:03,066] Trial 53 pruned.

Best trial: 22. Best value: 0.501754:  28%|██▊       | 55/200 [00:54<01:47,  1.35it/s]

[I 2025-11-10 14:09:04,641] Trial 50 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.14019875920976999, 'n_estimators': 1324, 'subsample': 0.5486275631617906, 'colsample_bytree': 0.6614569151134435, 'min_child_weight': 9, 'gamma': 4.958845478950966, 'reg_alpha': 0.026098660631272547, 'reg_lambda': 1.6602633982004857e-08, 'max_delta_step': 8}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  28%|██▊       | 57/200 [00:55<02:07,  1.12it/s]

[I 2025-11-10 14:09:06,055] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.12064606979794863, 'n_estimators': 617, 'subsample': 0.6592099111443163, 'colsample_bytree': 0.7287270842952365, 'min_child_weight': 8, 'gamma': 3.0518872035651388, 'reg_alpha': 1.0895369400184063e-06, 'reg_lambda': 0.1510895242704475, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:09:06,060] Trial 55 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08273541515952697, 'n_estimators': 678, 'subsample': 0.5412559004821169, 'colsample_bytree': 0.7857453900783951, 'min_child_weight': 10, 'gamma': 3.082206333480685, 'reg_alpha': 1.658758536683531e-07, 'reg_lambda': 1.316018629402226, 'max_delta_step': 6}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:09:06,066] Trial 58 pruned.

Best trial: 22. Best value: 0.501754:  30%|██▉       | 59/200 [00:56<01:29,  1.57it/s]

[I 2025-11-10 14:09:07,180] Trial 56 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07311240752476726, 'n_estimators': 815, 'subsample': 0.5481986486701889, 'colsample_bytree': 0.5444980685088722, 'min_child_weight': 8, 'gamma': 0.10936015748317925, 'reg_alpha': 9.332472303464815e-07, 'reg_lambda': 1.166300478288447, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  30%|███       | 60/200 [00:59<02:36,  1.12s/it]

[I 2025-11-10 14:09:10,347] Trial 60 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.033811361600032834, 'n_estimators': 813, 'subsample': 0.9603232708280999, 'colsample_bytree': 0.5050720248442969, 'min_child_weight': 6, 'gamma': 3.7226197253047557, 'reg_alpha': 0.00020944209805203205, 'reg_lambda': 0.00010987495525096004, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:09:10,383] Trial 59 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04946133107612193, 'n_estimators': 815, 'subsample': 0.8419441564866136, 'colsample_bytree': 0.5994956192453472, 'min_child_weight': 6, 'gamma': 3.6786627273791384, 'reg_alpha': 0.00015919900306454287, 'reg_lambda': 0.008149748625700188, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  31%|███       | 62/200 [01:00<01:49,  1.26it/s]

[I 2025-11-10 14:09:10,729] Trial 61 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.052835165160881256, 'n_estimators': 897, 'subsample': 0.9631024493813212, 'colsample_bytree': 0.5950374285833028, 'min_child_weight': 6, 'gamma': 2.441344010766194, 'reg_alpha': 7.347050767007914, 'reg_lambda': 0.013140133962568318, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  32%|███▏      | 64/200 [01:01<01:23,  1.62it/s]

[I 2025-11-10 14:09:11,286] Trial 62 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05423443521650653, 'n_estimators': 792, 'subsample': 0.9733922872526792, 'colsample_bytree': 0.7726285051767426, 'min_child_weight': 6, 'gamma': 2.4220816249004047, 'reg_alpha': 0.00015009218906072863, 'reg_lambda': 0.0014195585895145368, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:09:11,460] Trial 63 pruned.

Best trial: 22. Best value: 0.501754:  32%|███▎      | 65/200 [01:01<01:32,  1.46it/s]

[I 2025-11-10 14:09:12,358] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03926795434686418, 'n_estimators': 373, 'subsample': 0.5920063470074217, 'colsample_bytree': 0.5742586217205226, 'min_child_weight': 9, 'gamma': 0.5757415529880594, 'reg_alpha': 0.24438874146009407, 'reg_lambda': 9.685532107798275e-06, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  33%|███▎      | 66/200 [01:02<01:16,  1.75it/s]

[I 2025-11-10 14:09:12,600] Trial 65 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03965222573070859, 'n_estimators': 347, 'subsample': 0.5753012534139712, 'colsample_bytree': 0.6955652442167366, 'min_child_weight': 9, 'gamma': 0.43522552984379326, 'reg_alpha': 3.861151853388306e-05, 'reg_lambda': 9.448462076977204e-06, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  34%|███▍      | 68/200 [01:03<01:03,  2.06it/s]

[I 2025-11-10 14:09:13,324] Trial 66 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.031728094630955696, 'n_estimators': 383, 'subsample': 0.5901332986681851, 'colsample_bytree': 0.6912762181260403, 'min_child_weight': 9, 'gamma': 0.40429041065905436, 'reg_alpha': 0.032241248445827764, 'reg_lambda': 5.7136331932836614e-06, 'max_delta_step': 1}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:09:13,481] Trial 67 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.038457350268254795, 'n_estimators': 377, 'subsample': 0.912630002559964, 'colsample_bytree': 0.7025537448612107, 'min_child_weight': 9, 'gamma': 0.4115056352019426, 'reg_alpha': 0.4526508197800493, 'reg_lambda': 1.0072520758373135e-05, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  34%|███▍      | 69/200 [01:03<01:18,  1.67it/s]

[I 2025-11-10 14:09:14,362] Trial 68 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.06779837879238419, 'n_estimators': 368, 'subsample': 0.5686147892567424, 'colsample_bytree': 0.6410423952797996, 'min_child_weight': 10, 'gamma': 0.8336417568441493, 'reg_alpha': 0.006647637453261508, 'reg_lambda': 3.7887200237828598e-06, 'max_delta_step': 1}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  35%|███▌      | 70/200 [01:04<01:22,  1.57it/s]

[I 2025-11-10 14:09:15,095] Trial 69 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.019473526494934914, 'n_estimators': 511, 'subsample': 0.7201459488744529, 'colsample_bytree': 0.6349002225546941, 'min_child_weight': 10, 'gamma': 0.7533138655801697, 'reg_alpha': 0.008471256438781691, 'reg_lambda': 2.3361268368879814e-07, 'max_delta_step': 1}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  36%|███▌      | 72/200 [01:05<01:02,  2.03it/s]

[I 2025-11-10 14:09:15,775] Trial 72 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.018650643794488355, 'n_estimators': 261, 'subsample': 0.6346015836018148, 'colsample_bytree': 0.7413499312978695, 'min_child_weight': 8, 'gamma': 0.7508837932198182, 'reg_alpha': 6.993355158569494e-08, 'reg_lambda': 3.1050538728067653e-07, 'max_delta_step': 4}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:09:15,887] Trial 70 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.022205301060575174, 'n_estimators': 508, 'subsample': 0.7358474235541796, 'colsample_bytree': 0.6448785102196378, 'min_child_weight': 10, 'gamma': 0.740023328794609, 'reg_alpha': 0.007591938850460173, 'reg_lambda': 3.9853875133950154e-07, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  36%|███▋      | 73/200 [01:05<00:57,  2.21it/s]

[I 2025-11-10 14:09:16,250] Trial 71 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.06782541228818006, 'n_estimators': 510, 'subsample': 0.8260259634031979, 'colsample_bytree': 0.6396092964930794, 'min_child_weight': 7, 'gamma': 1.2229332148462468, 'reg_alpha': 8.741752268677483e-08, 'reg_lambda': 2.6541809583493805e-08, 'max_delta_step': 4}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  37%|███▋      | 74/200 [01:06<01:06,  1.90it/s]

[I 2025-11-10 14:09:16,947] Trial 73 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.20547146482076256, 'n_estimators': 269, 'subsample': 0.6374955424753141, 'colsample_bytree': 0.5250847115740525, 'min_child_weight': 8, 'gamma': 1.257127191662239, 'reg_alpha': 1.313560309895377, 'reg_lambda': 0.0008083522315505778, 'max_delta_step': 4}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  38%|███▊      | 76/200 [01:08<01:23,  1.48it/s]

[I 2025-11-10 14:09:18,734] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2023497648608535, 'n_estimators': 580, 'subsample': 0.9468625165143032, 'colsample_bytree': 0.8045996665272535, 'min_child_weight': 10, 'gamma': 1.3888176947696198, 'reg_alpha': 0.00041268234688167637, 'reg_lambda': 0.09492503971455836, 'max_delta_step': 8}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:09:18,837] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.20597096377960228, 'n_estimators': 569, 'subsample': 0.9798527425044292, 'colsample_bytree': 0.810254172588109, 'min_child_weight': 10, 'gamma': 0.1811761597516713, 'reg_alpha': 0.00042732880805576345, 'reg_lambda': 0.08498515494842115, 'max_delta_step': 8}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  38%|███▊      | 77/200 [01:10<02:24,  1.18s/it]

[I 2025-11-10 14:09:21,234] Trial 76 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.20899375450556937, 'n_estimators': 1029, 'subsample': 0.9804631179176229, 'colsample_bytree': 0.815407551557742, 'min_child_weight': 10, 'gamma': 0.20433760954446029, 'reg_alpha': 2.077672625339223e-08, 'reg_lambda': 0.09330390357811462, 'max_delta_step': 0}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  39%|███▉      | 78/200 [01:11<02:02,  1.00s/it]

[I 2025-11-10 14:09:21,825] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.23967869579566467, 'n_estimators': 1018, 'subsample': 0.9246701018382399, 'colsample_bytree': 0.8088293075534635, 'min_child_weight': 10, 'gamma': 0.2383219296812152, 'reg_alpha': 1.9078570913403594e-08, 'reg_lambda': 0.061266603489932854, 'max_delta_step': 0}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  40%|███▉      | 79/200 [01:11<01:43,  1.17it/s]

[I 2025-11-10 14:09:22,331] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.11058481334443634, 'n_estimators': 732, 'subsample': 0.8629403886736345, 'colsample_bytree': 0.5564348100907228, 'min_child_weight': 9, 'gamma': 1.8017776672573875, 'reg_alpha': 1.8933861345297115e-08, 'reg_lambda': 0.0036777791732411345, 'max_delta_step': 7}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  40%|████      | 80/200 [01:12<01:21,  1.47it/s]

[I 2025-11-10 14:09:22,585] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2462998964639658, 'n_estimators': 727, 'subsample': 0.9775746062783637, 'colsample_bytree': 0.8848218891330722, 'min_child_weight': 10, 'gamma': 1.7559326485526117, 'reg_alpha': 2.3291896007433337e-08, 'reg_lambda': 0.002467676567654499, 'max_delta_step': 0}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  40%|████      | 81/200 [01:14<02:24,  1.22s/it]

[I 2025-11-10 14:09:25,075] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1289997546489938, 'n_estimators': 429, 'subsample': 0.7855566739125632, 'colsample_bytree': 0.9460563278923662, 'min_child_weight': 7, 'gamma': 2.8081731441814317, 'reg_alpha': 1.7115440309063635e-06, 'reg_lambda': 2.735346464304704e-05, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  41%|████      | 82/200 [01:15<01:59,  1.01s/it]

[I 2025-11-10 14:09:25,614] Trial 80 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.09246567843357653, 'n_estimators': 721, 'subsample': 0.7972363741974591, 'colsample_bytree': 0.973915993366003, 'min_child_weight': 9, 'gamma': 1.8281559900351332, 'reg_alpha': 5.440401531667296e-07, 'reg_lambda': 0.003830470641092794, 'max_delta_step': 7}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  42%|████▏     | 83/200 [01:15<01:32,  1.26it/s]

[I 2025-11-10 14:09:25,889] Trial 82 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.2573128753067896, 'n_estimators': 621, 'subsample': 0.9095881496140793, 'colsample_bytree': 0.8915379511182961, 'min_child_weight': 9, 'gamma': 4.096812671055344, 'reg_alpha': 1.6773903154610175e-06, 'reg_lambda': 0.0005355367078366305, 'max_delta_step': 2}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  42%|████▏     | 84/200 [01:15<01:19,  1.45it/s]

[I 2025-11-10 14:09:26,339] Trial 81 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.13059315738087035, 'n_estimators': 727, 'subsample': 0.7930846095784222, 'colsample_bytree': 0.7675372732801118, 'min_child_weight': 9, 'gamma': 4.114228754706579, 'reg_alpha': 1.6743900086194405e-06, 'reg_lambda': 0.002760202631198231, 'max_delta_step': 2}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  42%|████▎     | 85/200 [01:18<02:34,  1.35s/it]

[I 2025-11-10 14:09:29,220] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.049380967741836944, 'n_estimators': 877, 'subsample': 0.5233517001982088, 'colsample_bytree': 0.8299936067037129, 'min_child_weight': 8, 'gamma': 4.2905695590067126, 'reg_alpha': 2.2943179478109734e-07, 'reg_lambda': 0.0005247031598439761, 'max_delta_step': 7}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  43%|████▎     | 86/200 [01:19<02:22,  1.25s/it]

[I 2025-11-10 14:09:30,234] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.048567765758493066, 'n_estimators': 965, 'subsample': 0.6746750058048481, 'colsample_bytree': 0.7677042941980374, 'min_child_weight': 8, 'gamma': 3.868099807631083, 'reg_alpha': 2.4211050307367505e-07, 'reg_lambda': 2.81674560007404e-05, 'max_delta_step': 6}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  44%|████▎     | 87/200 [01:20<01:59,  1.06s/it]

[I 2025-11-10 14:09:30,848] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04712880615858679, 'n_estimators': 1133, 'subsample': 0.5111752410781126, 'colsample_bytree': 0.8286481377394614, 'min_child_weight': 8, 'gamma': 4.334064873847019, 'reg_alpha': 2.2178852695987868e-07, 'reg_lambda': 0.000669907685945072, 'max_delta_step': 6}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  44%|████▍     | 88/200 [01:21<01:43,  1.08it/s]

[I 2025-11-10 14:09:31,464] Trial 87 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.030587246609427972, 'n_estimators': 1128, 'subsample': 0.5025590592545897, 'colsample_bytree': 0.9292111460727956, 'min_child_weight': 8, 'gamma': 4.747427218483237, 'reg_alpha': 4.056168788630855e-06, 'reg_lambda': 0.00012627223666742416, 'max_delta_step': 6}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  44%|████▍     | 89/200 [01:23<02:34,  1.39s/it]

[I 2025-11-10 14:09:33,938] Trial 89 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.028427367882432795, 'n_estimators': 765, 'subsample': 0.6174678066255492, 'colsample_bytree': 0.9249824843154608, 'min_child_weight': 5, 'gamma': 2.907037484839258, 'reg_alpha': 6.714711617903067e-08, 'reg_lambda': 0.019546852723351493, 'max_delta_step': 8}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  45%|████▌     | 90/200 [01:23<01:58,  1.07s/it]

[I 2025-11-10 14:09:34,267] Trial 88 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.030525501832099046, 'n_estimators': 1065, 'subsample': 0.6734721052935253, 'colsample_bytree': 0.9341939712094884, 'min_child_weight': 7, 'gamma': 0.008447606352781828, 'reg_alpha': 3.964935487192415e-06, 'reg_lambda': 0.0001357368016216604, 'max_delta_step': 6}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  46%|████▌     | 91/200 [01:24<01:48,  1.01it/s]

[I 2025-11-10 14:09:35,086] Trial 92 pruned.

Best trial: 22. Best value: 0.501754:  46%|████▋     | 93/200 [01:25<01:05,  1.63it/s]

[I 2025-11-10 14:09:35,507] Trial 91 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03612135522562072, 'n_estimators': 776, 'subsample': 0.9428789020716429, 'colsample_bytree': 0.8614082648836976, 'min_child_weight': 7, 'gamma': 2.954977218439844, 'reg_alpha': 1.2687729461026512e-07, 'reg_lambda': 0.019750450178850958, 'max_delta_step': 8}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:09:35,628] Trial 90 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1626242349430904, 'n_estimators': 937, 'subsample': 0.6199209578667645, 'colsample_bytree': 0.9285066059327836, 'min_child_weight': 7, 'gamma': 2.938461478757779, 'reg_alpha': 6.215124565510955e-08, 'reg_lambda': 0.018117373645087045, 'max_delta_step': 5}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  47%|████▋     | 94/200 [01:26<01:41,  1.05it/s]

[I 2025-11-10 14:09:37,390] Trial 93 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.036776219149525606, 'n_estimators': 645, 'subsample': 0.7033101325780248, 'colsample_bytree': 0.5331788830952631, 'min_child_weight': 9, 'gamma': 3.2580167405653455, 'reg_alpha': 2.632263202399709e-05, 'reg_lambda': 2.9294183665408524, 'max_delta_step': 5}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  48%|████▊     | 95/200 [01:29<02:16,  1.30s/it]

[I 2025-11-10 14:09:39,494] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.16883460752718768, 'n_estimators': 939, 'subsample': 0.6498580757303126, 'colsample_bytree': 0.5620844899198948, 'min_child_weight': 7, 'gamma': 2.3159976800297444, 'reg_alpha': 0.1340704721751666, 'reg_lambda': 5.215222660531024, 'max_delta_step': 4}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  48%|████▊     | 96/200 [01:29<01:43,  1.01it/s]

[I 2025-11-10 14:09:39,768] Trial 96 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.05892979150350227, 'n_estimators': 844, 'subsample': 0.8637650843795577, 'colsample_bytree': 0.7199570171469633, 'min_child_weight': 9, 'gamma': 2.3034196778819607, 'reg_alpha': 0.0018669415491714193, 'reg_lambda': 3.7724105460754105, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  48%|████▊     | 97/200 [01:31<02:22,  1.39s/it]

[I 2025-11-10 14:09:42,074] Trial 95 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.16322866541579653, 'n_estimators': 1418, 'subsample': 0.6505182966332403, 'colsample_bytree': 0.7265589551220731, 'min_child_weight': 5, 'gamma': 2.09128900236131, 'reg_alpha': 0.0017981735715026964, 'reg_lambda': 5.317092855603126, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  49%|████▉     | 98/200 [01:33<02:43,  1.60s/it]

[I 2025-11-10 14:09:44,129] Trial 97 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.05831822404026252, 'n_estimators': 1459, 'subsample': 0.8145483092296806, 'colsample_bytree': 0.6179740285789632, 'min_child_weight': 10, 'gamma': 2.2319836700422626, 'reg_alpha': 0.0656725008018305, 'reg_lambda': 0.6942689585093195, 'max_delta_step': 4}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  50%|█████     | 100/200 [01:36<02:19,  1.39s/it]

[I 2025-11-10 14:09:46,841] Trial 99 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.04202804302294139, 'n_estimators': 1474, 'subsample': 0.6051512480207856, 'colsample_bytree': 0.6156623613911258, 'min_child_weight': 10, 'gamma': 4.520637511681685, 'reg_alpha': 2.315469491146242, 'reg_lambda': 0.7385174846048085, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:09:47,007] Trial 98 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.06068132305698212, 'n_estimators': 1486, 'subsample': 0.6029316005903321, 'colsample_bytree': 0.73331100855252, 'min_child_weight': 5, 'gamma': 2.08715360996963, 'reg_alpha': 8.631567606250679e-05, 'reg_lambda': 9.299056553723718, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  50%|█████     | 101/200 [01:37<01:57,  1.19s/it]

[I 2025-11-10 14:09:47,712] Trial 100 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.10966855457026077, 'n_estimators': 995, 'subsample': 0.8184724667079789, 'colsample_bytree': 0.8997398828071734, 'min_child_weight': 10, 'gamma': 3.6577409771485394, 'reg_alpha': 5.485199497146138, 'reg_lambda': 0.6445893830814625, 'max_delta_step': 7}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  51%|█████     | 102/200 [01:40<02:54,  1.78s/it]

[I 2025-11-10 14:09:50,889] Trial 101 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04390987950650178, 'n_estimators': 1492, 'subsample': 0.6077039619025573, 'colsample_bytree': 0.5862557791087994, 'min_child_weight': 8, 'gamma': 4.528667833597199, 'reg_alpha': 6.068853426153771, 'reg_lambda': 8.94608657442347, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  52%|█████▏    | 103/200 [01:41<02:20,  1.45s/it]

[I 2025-11-10 14:09:51,568] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.11221506819231236, 'n_estimators': 989, 'subsample': 0.894452212225648, 'colsample_bytree': 0.5060584714869243, 'min_child_weight': 8, 'gamma': 3.97614704318528, 'reg_alpha': 8.053544098893319, 'reg_lambda': 0.2002398959342518, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:09:51,578] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.10946971247101224, 'n_estimators': 1002, 'subsample': 0.8474454637954242, 'colsample_bytree': 0.5826132950494631, 'min_child_weight': 8, 'gamma': 2.6566448537607465, 'reg_alpha': 9.46896549810661, 'reg_lambda': 0.3109921615943575, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  52%|█████▎    | 105/200 [01:42<01:38,  1.04s/it]

[I 2025-11-10 14:09:52,681] Trial 104 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.22572186611485137, 'n_estimators': 1041, 'subsample': 0.8933613812203953, 'colsample_bytree': 0.6534589404634839, 'min_child_weight': 6, 'gamma': 3.3948087122415824, 'reg_alpha': 1.2583835239819885, 'reg_lambda': 0.24025020558075716, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  53%|█████▎    | 106/200 [01:42<01:26,  1.08it/s]

[I 2025-11-10 14:09:53,253] Trial 107 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.09187251667248096, 'n_estimators': 316, 'subsample': 0.7656562258241206, 'colsample_bytree': 0.6586976711090227, 'min_child_weight': 6, 'gamma': 3.1216230331547754, 'reg_alpha': 1.1743808693212947, 'reg_lambda': 2.431036122877386, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  54%|█████▎    | 107/200 [01:45<01:56,  1.26s/it]

[I 2025-11-10 14:09:55,446] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.09886439829282993, 'n_estimators': 912, 'subsample': 0.7442557012126186, 'colsample_bytree': 0.6789420341289869, 'min_child_weight': 6, 'gamma': 3.4049111228765536, 'reg_alpha': 2.7934940349558692, 'reg_lambda': 0.32305970267914724, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  54%|█████▍    | 108/200 [01:45<01:36,  1.05s/it]

[I 2025-11-10 14:09:55,937] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.09406090886020492, 'n_estimators': 907, 'subsample': 0.8442151717199031, 'colsample_bytree': 0.65727485194519, 'min_child_weight': 6, 'gamma': 3.4117556732689396, 'reg_alpha': 0.9735879595410093, 'reg_lambda': 0.044105721261651895, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  55%|█████▍    | 109/200 [01:46<01:39,  1.10s/it]

[I 2025-11-10 14:09:57,159] Trial 108 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09592352951840898, 'n_estimators': 915, 'subsample': 0.7469730590555138, 'colsample_bytree': 0.6870520438584391, 'min_child_weight': 6, 'gamma': 3.541923439275943, 'reg_alpha': 2.185469499786752, 'reg_lambda': 1.7854634925387993, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  55%|█████▌    | 110/200 [01:47<01:21,  1.10it/s]

[I 2025-11-10 14:09:57,605] Trial 109 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.18957433815104052, 'n_estimators': 913, 'subsample': 0.5651178051031011, 'colsample_bytree': 0.7132755851770846, 'min_child_weight': 6, 'gamma': 0.5834074172412125, 'reg_alpha': 0.6739907559286689, 'reg_lambda': 0.001565630619071538, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  56%|█████▌    | 111/200 [01:47<01:09,  1.29it/s]

[I 2025-11-10 14:09:58,059] Trial 112 pruned.

Best trial: 22. Best value: 0.501754:  56%|█████▌    | 112/200 [01:48<00:59,  1.47it/s]

[I 2025-11-10 14:09:58,498] Trial 113 pruned.

Best trial: 22. Best value: 0.501754:  56%|█████▋    | 113/200 [01:49<01:24,  1.03it/s]

[I 2025-11-10 14:10:00,154] Trial 114 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.07529625207212512, 'n_estimators': 413, 'subsample': 0.7185411312220057, 'colsample_bytree': 0.750551871327259, 'min_child_weight': 5, 'gamma': 3.165725867763957, 'reg_alpha': 5.111937867085318e-07, 'reg_lambda': 0.006127638483732936, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  57%|█████▋    | 114/200 [01:50<01:13,  1.18it/s]

[I 2025-11-10 14:10:00,729] Trial 116 pruned.

Best trial: 22. Best value: 0.501754:  57%|█████▊    | 115/200 [01:51<01:14,  1.15it/s]

[I 2025-11-10 14:10:01,660] Trial 115 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07798318904218753, 'n_estimators': 656, 'subsample': 0.8075304632714253, 'colsample_bytree': 0.7510099707010877, 'min_child_weight': 5, 'gamma': 3.174301474687516, 'reg_alpha': 0.20016854101300932, 'reg_lambda': 6.514821092181022e-08, 'max_delta_step': 2}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  58%|█████▊    | 116/200 [01:51<00:56,  1.48it/s]

[I 2025-11-10 14:10:01,868] Trial 110 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.19001993215536575, 'n_estimators': 1285, 'subsample': 0.5623814757583481, 'colsample_bytree': 0.7123713099051708, 'min_child_weight': 5, 'gamma': 3.5874540262368186, 'reg_alpha': 5.039896043967342e-07, 'reg_lambda': 0.04562715027424438, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  58%|█████▊    | 117/200 [01:51<00:51,  1.61it/s]

[I 2025-11-10 14:10:02,351] Trial 111 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.18362919051481064, 'n_estimators': 1285, 'subsample': 0.5615874695876566, 'colsample_bytree': 0.7160588116901141, 'min_child_weight': 5, 'gamma': 1.9505886551129166, 'reg_alpha': 0.717205256417119, 'reg_lambda': 0.0012544170000379897, 'max_delta_step': 8}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  59%|█████▉    | 118/200 [01:54<01:42,  1.25s/it]

[I 2025-11-10 14:10:05,076] Trial 117 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1347273194798917, 'n_estimators': 863, 'subsample': 0.8284013300698454, 'colsample_bytree': 0.969508112893708, 'min_child_weight': 7, 'gamma': 3.5781472240989127, 'reg_alpha': 1.2018937785666355e-08, 'reg_lambda': 3.9799422342914106, 'max_delta_step': 4}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  60%|██████    | 120/200 [01:56<01:12,  1.11it/s]

[I 2025-11-10 14:10:06,247] Trial 119 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2645097316910448, 'n_estimators': 871, 'subsample': 0.8236227912562001, 'colsample_bytree': 0.7932892613381674, 'min_child_weight': 9, 'gamma': 2.018021504888915, 'reg_alpha': 3.9717736805960504, 'reg_lambda': 5.736901069456853e-05, 'max_delta_step': 4}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:10:06,401] Trial 118 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.06877090369757136, 'n_estimators': 864, 'subsample': 0.8305556415556338, 'colsample_bytree': 0.9713042718484459, 'min_child_weight': 7, 'gamma': 3.5848048668132946, 'reg_alpha': 0.04232553760928139, 'reg_lambda': 7.101192915263957e-05, 'max_delta_step': 4}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  60%|██████    | 121/200 [01:56<00:58,  1.35it/s]

[I 2025-11-10 14:10:06,776] Trial 120 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.13957416465168457, 'n_estimators': 859, 'subsample': 0.7866570915668514, 'colsample_bytree': 0.7621493144943546, 'min_child_weight': 9, 'gamma': 1.6029398894247073, 'reg_alpha': 1.0056402532559568e-08, 'reg_lambda': 0.00021236546287772872, 'max_delta_step': 4}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  61%|██████    | 122/200 [01:57<01:03,  1.24it/s]

[I 2025-11-10 14:10:07,733] Trial 123 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.08661892542805452, 'n_estimators': 230, 'subsample': 0.5374250456492577, 'colsample_bytree': 0.7030120695851281, 'min_child_weight': 10, 'gamma': 2.7850318603972335, 'reg_alpha': 9.014880410153037e-07, 'reg_lambda': 1.1596164776228945, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  62%|██████▏   | 123/200 [01:57<00:58,  1.31it/s]

[I 2025-11-10 14:10:08,377] Trial 121 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.06971593228214619, 'n_estimators': 602, 'subsample': 0.8583274202661066, 'colsample_bytree': 0.9985777683845088, 'min_child_weight': 9, 'gamma': 2.810188706845338, 'reg_alpha': 3.5527730590175706, 'reg_lambda': 7.018646405670937e-05, 'max_delta_step': 7}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  62%|██████▏   | 124/200 [01:59<01:11,  1.06it/s]

[I 2025-11-10 14:10:09,762] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01639324302560248, 'n_estimators': 602, 'subsample': 0.5111305712454223, 'colsample_bytree': 0.5416054955520797, 'min_child_weight': 7, 'gamma': 2.744029143568468, 'reg_alpha': 9.217222608078816e-07, 'reg_lambda': 1.2678566676234244, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  62%|██████▎   | 125/200 [02:00<01:23,  1.11s/it]

[I 2025-11-10 14:10:11,248] Trial 122 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07102473185909003, 'n_estimators': 952, 'subsample': 0.7707760030563243, 'colsample_bytree': 0.6990485502665943, 'min_child_weight': 10, 'gamma': 2.811676054506959, 'reg_alpha': 0.0474901168756312, 'reg_lambda': 1.8077718310777928, 'max_delta_step': 7}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  64%|██████▎   | 127/200 [02:02<01:00,  1.20it/s]

[I 2025-11-10 14:10:12,430] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.016832033042891974, 'n_estimators': 955, 'subsample': 0.51360327713751, 'colsample_bytree': 0.5526058881028172, 'min_child_weight': 7, 'gamma': 2.8650845189674783, 'reg_alpha': 1.8185541096599675e-05, 'reg_lambda': 6.122479025395737, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:10:12,567] Trial 126 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.05278540899599083, 'n_estimators': 827, 'subsample': 0.5134024806610767, 'colsample_bytree': 0.5375483306151717, 'min_child_weight': 6, 'gamma': 2.554547052769219, 'reg_alpha': 0.01917063129000522, 'reg_lambda': 7.003987218095475, 'max_delta_step': 1}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  64%|██████▍   | 128/200 [02:03<01:16,  1.07s/it]

[I 2025-11-10 14:10:14,173] Trial 127 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.024314185073254967, 'n_estimators': 812, 'subsample': 0.5250763855250985, 'colsample_bytree': 0.872264170694769, 'min_child_weight': 6, 'gamma': 2.619517765509077, 'reg_alpha': 1.4754186020910647e-05, 'reg_lambda': 1.5997519650260854e-05, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  64%|██████▍   | 129/200 [02:05<01:20,  1.14s/it]

[I 2025-11-10 14:10:15,482] Trial 128 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02633885562537904, 'n_estimators': 815, 'subsample': 0.6265258261468225, 'colsample_bytree': 0.836939779465092, 'min_child_weight': 6, 'gamma': 3.0104643830366413, 'reg_alpha': 1.9588509395947925e-05, 'reg_lambda': 2.4390267674855513, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  65%|██████▌   | 130/200 [02:05<01:12,  1.03s/it]

[I 2025-11-10 14:10:16,266] Trial 130 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.022073970688560398, 'n_estimators': 795, 'subsample': 0.5316394246411396, 'colsample_bytree': 0.6074425134346693, 'min_child_weight': 8, 'gamma': 0.9951713879796784, 'reg_alpha': 2.9514231850993535e-07, 'reg_lambda': 6.082172593094211e-07, 'max_delta_step': 5}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  66%|██████▌   | 131/200 [02:06<00:55,  1.24it/s]

[I 2025-11-10 14:10:16,537] Trial 129 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02400547920745501, 'n_estimators': 823, 'subsample': 0.5343730879715757, 'colsample_bytree': 0.8405815564373186, 'min_child_weight': 6, 'gamma': 2.609822302195766, 'reg_alpha': 0.01720255323868803, 'reg_lambda': 3.385513612417503, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  66%|██████▌   | 132/200 [02:08<01:30,  1.33s/it]

[I 2025-11-10 14:10:19,085] Trial 132 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04620863513171455, 'n_estimators': 754, 'subsample': 0.9880939134659832, 'colsample_bytree': 0.5186481720955887, 'min_child_weight': 8, 'gamma': 3.2918826523263123, 'reg_alpha': 3.491994298323853e-08, 'reg_lambda': 1.571503614782919e-07, 'max_delta_step': 1}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  66%|██████▋   | 133/200 [02:09<01:14,  1.11s/it]

[I 2025-11-10 14:10:19,687] Trial 131 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.013019212527171033, 'n_estimators': 1118, 'subsample': 0.8798355628895278, 'colsample_bytree': 0.6057766261200069, 'min_child_weight': 8, 'gamma': 3.0445531079833725, 'reg_alpha': 4.0011462255722144e-05, 'reg_lambda': 2.4532840452598808, 'max_delta_step': 2}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  67%|██████▋   | 134/200 [02:10<01:05,  1.01it/s]

[I 2025-11-10 14:10:20,399] Trial 134 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.029385964306864455, 'n_estimators': 747, 'subsample': 0.5476708823352967, 'colsample_bytree': 0.5656789806481268, 'min_child_weight': 7, 'gamma': 2.4259240818583847, 'reg_alpha': 2.9113316796453755e-05, 'reg_lambda': 1.7084246509451554e-07, 'max_delta_step': 2}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  68%|██████▊   | 135/200 [02:11<01:15,  1.16s/it]

[I 2025-11-10 14:10:21,963] Trial 133 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04525998039190347, 'n_estimators': 1115, 'subsample': 0.9862492460413134, 'colsample_bytree': 0.9137745595888853, 'min_child_weight': 8, 'gamma': 2.3439411449342464, 'reg_alpha': 7.793688267706826e-05, 'reg_lambda': 1.86209767967742e-07, 'max_delta_step': 2}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  68%|██████▊   | 136/200 [02:12<01:16,  1.20s/it]

[I 2025-11-10 14:10:23,257] Trial 136 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.033089476724446024, 'n_estimators': 749, 'subsample': 0.5054133024453307, 'colsample_bytree': 0.5676432433733007, 'min_child_weight': 7, 'gamma': 0.3109391160761388, 'reg_alpha': 8.186611083873006e-05, 'reg_lambda': 4.392913057273022, 'max_delta_step': 2}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  68%|██████▊   | 137/200 [02:13<01:11,  1.14s/it]

[I 2025-11-10 14:10:24,258] Trial 135 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03297355276959142, 'n_estimators': 1105, 'subsample': 0.8850671859396084, 'colsample_bytree': 0.5715286484413248, 'min_child_weight': 7, 'gamma': 2.453100866477051, 'reg_alpha': 0.0003190193521405097, 'reg_lambda': 4.588887669668057, 'max_delta_step': 2}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  69%|██████▉   | 138/200 [02:14<01:09,  1.12s/it]

[I 2025-11-10 14:10:25,340] Trial 137 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03469448085919462, 'n_estimators': 1041, 'subsample': 0.503504467863668, 'colsample_bytree': 0.6802408259087371, 'min_child_weight': 7, 'gamma': 2.349841764213361, 'reg_alpha': 9.433534221725777e-05, 'reg_lambda': 9.333382802720516, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  70%|██████▉   | 139/200 [02:16<01:23,  1.37s/it]

[I 2025-11-10 14:10:27,292] Trial 138 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03336378140418303, 'n_estimators': 1164, 'subsample': 0.9673346903704055, 'colsample_bytree': 0.5774247859780705, 'min_child_weight': 10, 'gamma': 0.3615491648130007, 'reg_alpha': 0.00030426918947978594, 'reg_lambda': 5.093996389034905, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  70%|███████   | 140/200 [02:17<01:12,  1.21s/it]

[I 2025-11-10 14:10:28,108] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.0265197723727879, 'n_estimators': 554, 'subsample': 0.9581578868245816, 'colsample_bytree': 0.6665436246698284, 'min_child_weight': 10, 'gamma': 2.6787787465882884, 'reg_alpha': 4.888586033773581e-05, 'reg_lambda': 1.8482560733082956e-06, 'max_delta_step': 6}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  70%|███████   | 141/200 [02:18<01:06,  1.13s/it]

[I 2025-11-10 14:10:29,066] Trial 140 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.026291429780481462, 'n_estimators': 1039, 'subsample': 0.9557627197406131, 'colsample_bytree': 0.5048854196998501, 'min_child_weight': 10, 'gamma': 0.06708749391987062, 'reg_alpha': 0.0006682201167682519, 'reg_lambda': 9.326576503970891, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  71%|███████   | 142/200 [02:18<00:49,  1.17it/s]

[I 2025-11-10 14:10:29,279] Trial 139 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.2149178164454178, 'n_estimators': 1165, 'subsample': 0.5000807735427749, 'colsample_bytree': 0.6835199917914441, 'min_child_weight': 10, 'gamma': 0.029584036909003186, 'reg_alpha': 1.8254551959083545, 'reg_lambda': 8.140461940142552, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  72%|███████▏  | 143/200 [02:20<01:03,  1.11s/it]

[I 2025-11-10 14:10:30,997] Trial 142 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.06372417699438018, 'n_estimators': 781, 'subsample': 0.5969677451379466, 'colsample_bytree': 0.6684200019865258, 'min_child_weight': 9, 'gamma': 1.705205917982423, 'reg_alpha': 0.0008980815395107508, 'reg_lambda': 2.383428570829986e-06, 'max_delta_step': 6}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  72%|███████▏  | 144/200 [02:21<00:54,  1.02it/s]

[I 2025-11-10 14:10:31,659] Trial 143 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.08974969916005636, 'n_estimators': 776, 'subsample': 0.9364391922498091, 'colsample_bytree': 0.5009756195433661, 'min_child_weight': 9, 'gamma': 0.5686651281884962, 'reg_alpha': 8.877670572960114e-08, 'reg_lambda': 4.047739277639408e-08, 'max_delta_step': 8}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  72%|███████▎  | 145/200 [02:21<00:47,  1.17it/s]

[I 2025-11-10 14:10:32,232] Trial 144 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.22472889064185972, 'n_estimators': 668, 'subsample': 0.5259555371638561, 'colsample_bytree': 0.5512616576319287, 'min_child_weight': 8, 'gamma': 1.7115642319445628, 'reg_alpha': 6.576596744733604e-06, 'reg_lambda': 0.44799673363692516, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  73%|███████▎  | 146/200 [02:22<00:38,  1.42it/s]

[I 2025-11-10 14:10:32,581] Trial 145 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2307801690558924, 'n_estimators': 678, 'subsample': 0.5970623921599578, 'colsample_bytree': 0.5250298683989003, 'min_child_weight': 7, 'gamma': 4.175909558498889, 'reg_alpha': 5.890185798014796e-06, 'reg_lambda': 0.010445034989124616, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  74%|███████▎  | 147/200 [02:23<00:52,  1.02it/s]

[I 2025-11-10 14:10:34,214] Trial 149 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10141223374064387, 'n_estimators': 304, 'subsample': 0.6391575463821173, 'colsample_bytree': 0.5873261545144282, 'min_child_weight': 6, 'gamma': 2.214624369272877, 'reg_alpha': 0.000141756204847156, 'reg_lambda': 0.12156929653163222, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  74%|███████▍  | 148/200 [02:24<00:41,  1.26it/s]

[I 2025-11-10 14:10:34,562] Trial 146 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.281927035205541, 'n_estimators': 682, 'subsample': 0.9355904980983356, 'colsample_bytree': 0.5255829666299655, 'min_child_weight': 7, 'gamma': 4.817205334880462, 'reg_alpha': 0.00018946831089145116, 'reg_lambda': 0.8394581729113026, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  74%|███████▍  | 149/200 [02:24<00:39,  1.30it/s]

[I 2025-11-10 14:10:35,274] Trial 147 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.29456126582641196, 'n_estimators': 662, 'subsample': 0.5257296425509271, 'colsample_bytree': 0.5525574733646271, 'min_child_weight': 7, 'gamma': 4.268348882636879, 'reg_alpha': 0.00014335660689506646, 'reg_lambda': 0.1455492115868057, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  75%|███████▌  | 150/200 [02:26<00:47,  1.05it/s]

[I 2025-11-10 14:10:36,661] Trial 151 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.041807831680506266, 'n_estimators': 465, 'subsample': 0.5163726281790051, 'colsample_bytree': 0.6304543793014306, 'min_child_weight': 6, 'gamma': 3.9778744086676308, 'reg_alpha': 5.186510994659458e-08, 'reg_lambda': 0.0003873715773600213, 'max_delta_step': 4}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:10:36,846] Trial 150 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2712792288414484, 'n_estimators': 484, 'subsample': 0.5180313811328412, 'colsample_bytree': 0.6289490534829306, 'min_child_weight': 7, 'gamma': 4.872362844497413, 'reg_alpha': 0.35245417900785037, 'reg_lambda': 0.8785186164505592, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  76%|███████▌  | 152/200 [02:27<00:32,  1.46it/s]

[I 2025-11-10 14:10:37,446] Trial 152 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.25549655850120734, 'n_estimators': 473, 'subsample': 0.8017605538128297, 'colsample_bytree': 0.6261925922493237, 'min_child_weight': 8, 'gamma': 0.18022087560449748, 'reg_alpha': 5.46459745099697e-05, 'reg_lambda': 0.00035089323376068655, 'max_delta_step': 4}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  76%|███████▋  | 153/200 [02:28<00:40,  1.17it/s]

[I 2025-11-10 14:10:38,690] Trial 148 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.29475369884315356, 'n_estimators': 1397, 'subsample': 0.5224594583421245, 'colsample_bytree': 0.527778783524652, 'min_child_weight': 7, 'gamma': 4.612225293354437, 'reg_alpha': 0.00017166110867591777, 'reg_lambda': 0.12873098996580767, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  77%|███████▋  | 154/200 [02:29<00:49,  1.07s/it]

[I 2025-11-10 14:10:40,267] Trial 153 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.10585970583548886, 'n_estimators': 717, 'subsample': 0.6231118490944889, 'colsample_bytree': 0.7767561518648596, 'min_child_weight': 8, 'gamma': 4.664912718982547, 'reg_alpha': 0.003396051080894899, 'reg_lambda': 1.7967581001943647e-08, 'max_delta_step': 0}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  78%|███████▊  | 155/200 [02:30<00:37,  1.19it/s]

[I 2025-11-10 14:10:40,555] Trial 154 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2536091216528251, 'n_estimators': 721, 'subsample': 0.549108478141013, 'colsample_bytree': 0.6460036831065906, 'min_child_weight': 4, 'gamma': 3.8236555445502263, 'reg_alpha': 6.963737845242592e-05, 'reg_lambda': 0.07278361717469281, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  78%|███████▊  | 156/200 [02:30<00:34,  1.28it/s]

[I 2025-11-10 14:10:41,217] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0374331175615226, 'n_estimators': 713, 'subsample': 0.5415340225983691, 'colsample_bytree': 0.5597181499710302, 'min_child_weight': 8, 'gamma': 4.442778621237424, 'reg_alpha': 0.00010825072318007545, 'reg_lambda': 0.02581850495291631, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  78%|███████▊  | 157/200 [02:32<00:41,  1.04it/s]

[I 2025-11-10 14:10:42,578] Trial 156 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.037912376774049565, 'n_estimators': 709, 'subsample': 0.8542059184608739, 'colsample_bytree': 0.5632059372700614, 'min_child_weight': 8, 'gamma': 4.440536575908565, 'reg_alpha': 1.3880138174262285e-07, 'reg_lambda': 0.03188510763825699, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  79%|███████▉  | 158/200 [02:32<00:31,  1.35it/s]

[I 2025-11-10 14:10:42,800] Trial 158 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.023973735134400598, 'n_estimators': 407, 'subsample': 0.5368501076648263, 'colsample_bytree': 0.5589740972668866, 'min_child_weight': 8, 'gamma': 1.4333017526177096, 'reg_alpha': 0.00011203686456736628, 'reg_lambda': 0.03869194869267379, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  80%|███████▉  | 159/200 [02:33<00:31,  1.32it/s]

[I 2025-11-10 14:10:43,613] Trial 157 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.037361523238762816, 'n_estimators': 534, 'subsample': 0.9102502535991684, 'colsample_bytree': 0.8796035991531918, 'min_child_weight': 8, 'gamma': 4.0735714929948, 'reg_alpha': 1.37504261863649e-07, 'reg_lambda': 0.031342024672930374, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  80%|████████  | 160/200 [02:34<00:36,  1.08it/s]

[I 2025-11-10 14:10:44,921] Trial 160 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.11750873915099212, 'n_estimators': 414, 'subsample': 0.9061781452441667, 'colsample_bytree': 0.8870099953830217, 'min_child_weight': 9, 'gamma': 3.763791124590692, 'reg_alpha': 1.3185186577714708e-06, 'reg_lambda': 3.042113989868259, 'max_delta_step': 5}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  80%|████████  | 161/200 [02:35<00:37,  1.03it/s]

[I 2025-11-10 14:10:46,002] Trial 163 pruned.

Best trial: 22. Best value: 0.501754:  81%|████████  | 162/200 [02:36<00:30,  1.24it/s]

[I 2025-11-10 14:10:46,423] Trial 159 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.020083343558281855, 'n_estimators': 975, 'subsample': 0.7570383858056212, 'colsample_bytree': 0.8818315781029934, 'min_child_weight': 8, 'gamma': 4.065171692560938, 'reg_alpha': 1.3874069914474118e-07, 'reg_lambda': 0.05053802029542994, 'max_delta_step': 7}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  82%|████████▏ | 163/200 [02:37<00:39,  1.07s/it]

[I 2025-11-10 14:10:48,089] Trial 162 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.12073186238753929, 'n_estimators': 885, 'subsample': 0.8382222578944548, 'colsample_bytree': 0.5413923501608743, 'min_child_weight': 9, 'gamma': 3.3442681875707354, 'reg_alpha': 3.540204225087626e-07, 'reg_lambda': 0.21251676867253497, 'max_delta_step': 5}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  82%|████████▏ | 164/200 [02:37<00:29,  1.24it/s]

[I 2025-11-10 14:10:48,291] Trial 161 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.11664799101246281, 'n_estimators': 1003, 'subsample': 0.9149027548085967, 'colsample_bytree': 0.8872369064206583, 'min_child_weight': 9, 'gamma': 4.087068953206846, 'reg_alpha': 2.542145206379329e-06, 'reg_lambda': 1.6483895659291055, 'max_delta_step': 8}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  82%|████████▎ | 165/200 [02:40<00:48,  1.37s/it]

[I 2025-11-10 14:10:50,990] Trial 164 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01784854974023685, 'n_estimators': 1011, 'subsample': 0.556903702670212, 'colsample_bytree': 0.5892818768463574, 'min_child_weight': 4, 'gamma': 4.197875328808009, 'reg_alpha': 1.0367477254769718e-05, 'reg_lambda': 0.0041144206161447885, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  83%|████████▎ | 166/200 [02:41<00:41,  1.23s/it]

[I 2025-11-10 14:10:51,881] Trial 165 finished with value: 0.4822222222222222 and parameters: {'max_depth': 3, 'learning_rate': 0.020509719473270648, 'n_estimators': 1068, 'subsample': 0.6133223166938435, 'colsample_bytree': 0.5894696559295527, 'min_child_weight': 4, 'gamma': 4.219833728698081, 'reg_alpha': 3.262462527783947e-05, 'reg_lambda': 5.2408733617404215e-06, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  84%|████████▎ | 167/200 [02:41<00:32,  1.01it/s]

[I 2025-11-10 14:10:52,311] Trial 167 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02118763059928048, 'n_estimators': 843, 'subsample': 0.6109228242245841, 'colsample_bytree': 0.5914048418083716, 'min_child_weight': 6, 'gamma': 4.270083531495078, 'reg_alpha': 1.059808013522947e-05, 'reg_lambda': 0.014172677166814774, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  84%|████████▍ | 168/200 [02:42<00:28,  1.13it/s]

[I 2025-11-10 14:10:52,958] Trial 166 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01935033327821071, 'n_estimators': 1010, 'subsample': 0.5857728013940625, 'colsample_bytree': 0.5918874897936305, 'min_child_weight': 4, 'gamma': 4.375484715767397, 'reg_alpha': 5.267955449946534e-05, 'reg_lambda': 0.006287435616472118, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  84%|████████▍ | 169/200 [02:44<00:35,  1.15s/it]

[I 2025-11-10 14:10:54,711] Trial 168 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.02307306272503444, 'n_estimators': 760, 'subsample': 0.5734957491056918, 'colsample_bytree': 0.5830246392624092, 'min_child_weight': 4, 'gamma': 3.9709965813084107, 'reg_alpha': 0.09300549026513907, 'reg_lambda': 0.00823618456867924, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  85%|████████▌ | 170/200 [02:45<00:31,  1.06s/it]

[I 2025-11-10 14:10:55,578] Trial 169 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.05757859097195061, 'n_estimators': 747, 'subsample': 0.5728686896871453, 'colsample_bytree': 0.5787857792476523, 'min_child_weight': 4, 'gamma': 3.918390888273033, 'reg_alpha': 4.326245841049197e-05, 'reg_lambda': 0.006113297757363867, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  86%|████████▌ | 171/200 [02:45<00:26,  1.08it/s]

[I 2025-11-10 14:10:56,173] Trial 170 finished with value: 0.4632748538011696 and parameters: {'max_depth': 10, 'learning_rate': 0.02556181957579228, 'n_estimators': 756, 'subsample': 0.6332630315367701, 'colsample_bytree': 0.5719439503741385, 'min_child_weight': 4, 'gamma': 3.8995192604141242, 'reg_alpha': 5.615773433757877e-05, 'reg_lambda': 0.002641604914434599, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  86%|████████▌ | 172/200 [02:46<00:24,  1.13it/s]

[I 2025-11-10 14:10:56,959] Trial 171 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.028891948757661035, 'n_estimators': 776, 'subsample': 0.778021124798677, 'colsample_bytree': 0.6056323847423558, 'min_child_weight': 5, 'gamma': 3.886862869367145, 'reg_alpha': 0.12240593901295163, 'reg_lambda': 0.0021682501465863065, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  86%|████████▋ | 173/200 [02:48<00:32,  1.19s/it]

[I 2025-11-10 14:10:58,862] Trial 173 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.028550448408083916, 'n_estimators': 634, 'subsample': 0.8687612961331685, 'colsample_bytree': 0.6064260918615552, 'min_child_weight': 10, 'gamma': 0.469582288454126, 'reg_alpha': 0.00028872042033445037, 'reg_lambda': 0.002335023047452519, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  87%|████████▋ | 174/200 [02:48<00:23,  1.11it/s]

[I 2025-11-10 14:10:59,100] Trial 172 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.027754982371995824, 'n_estimators': 791, 'subsample': 0.8102218743680053, 'colsample_bytree': 0.6051692832117694, 'min_child_weight': 10, 'gamma': 3.487146728728252, 'reg_alpha': 2.9267190845285096e-08, 'reg_lambda': 1.0869267518168702e-08, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  88%|████████▊ | 175/200 [02:49<00:20,  1.23it/s]

[I 2025-11-10 14:10:59,693] Trial 174 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.08342357101988848, 'n_estimators': 645, 'subsample': 0.5878740021528188, 'colsample_bytree': 0.7546871085873643, 'min_child_weight': 10, 'gamma': 3.5079284535101225, 'reg_alpha': 0.011338456127829829, 'reg_lambda': 0.0034985117331082947, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  88%|████████▊ | 176/200 [02:49<00:16,  1.48it/s]

[I 2025-11-10 14:11:00,051] Trial 176 pruned.

Best trial: 22. Best value: 0.501754:  88%|████████▊ | 177/200 [02:50<00:17,  1.32it/s]

[I 2025-11-10 14:11:01,012] Trial 175 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.15723236207175456, 'n_estimators': 804, 'subsample': 0.6029170391050126, 'colsample_bytree': 0.7608190466757072, 'min_child_weight': 10, 'gamma': 2.487292024724572, 'reg_alpha': 0.011245806721224112, 'reg_lambda': 6.3687889751752325, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  89%|████████▉ | 178/200 [02:53<00:33,  1.51s/it]

[I 2025-11-10 14:11:04,258] Trial 180 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.024840803816590266, 'n_estimators': 736, 'subsample': 0.5117839432559302, 'colsample_bytree': 0.7456192641406888, 'min_child_weight': 3, 'gamma': 3.6715821142574017, 'reg_alpha': 3.5044062973990866, 'reg_lambda': 3.317781704744739, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  90%|████████▉ | 179/200 [02:54<00:27,  1.30s/it]

[I 2025-11-10 14:11:05,081] Trial 177 finished with value: 0.48888888888888893 and parameters: {'max_depth': 4, 'learning_rate': 0.08276931631342056, 'n_estimators': 1228, 'subsample': 0.5907334442840372, 'colsample_bytree': 0.7437066084802019, 'min_child_weight': 3, 'gamma': 3.6538679349957746, 'reg_alpha': 1.7611287003603265e-08, 'reg_lambda': 5.632897530764786, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  90%|█████████ | 180/200 [02:55<00:21,  1.05s/it]

[I 2025-11-10 14:11:05,560] Trial 178 finished with value: 0.49444444444444446 and parameters: {'max_depth': 4, 'learning_rate': 0.030944004489308462, 'n_estimators': 1226, 'subsample': 0.5083357503409945, 'colsample_bytree': 0.7421323450704435, 'min_child_weight': 3, 'gamma': 2.5009956293056677, 'reg_alpha': 3.6731102349849976, 'reg_lambda': 0.0009466741962565044, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  90%|█████████ | 181/200 [02:55<00:17,  1.10it/s]

[I 2025-11-10 14:11:06,128] Trial 179 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.15223726280669542, 'n_estimators': 1228, 'subsample': 0.5094911412827017, 'colsample_bytree': 0.9410740063278997, 'min_child_weight': 4, 'gamma': 3.6928010581247, 'reg_alpha': 2.205311650883156e-05, 'reg_lambda': 0.01338239395663482, 'max_delta_step': 10}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  92%|█████████▏| 183/200 [02:56<00:09,  1.86it/s]

[I 2025-11-10 14:11:06,337] Trial 181 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.031030667521728957, 'n_estimators': 330, 'subsample': 0.7920010295873311, 'colsample_bytree': 0.7322350889115721, 'min_child_weight': 6, 'gamma': 1.3303222751096055, 'reg_alpha': 1.4713734146592627, 'reg_lambda': 3.068052393093714e-08, 'max_delta_step': 8}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:11:06,496] Trial 183 pruned.

Best trial: 22. Best value: 0.501754:  92%|█████████▏| 184/200 [02:56<00:06,  2.34it/s]

[I 2025-11-10 14:11:06,669] Trial 184 pruned.

Best trial: 22. Best value: 0.501754:  93%|█████████▎| 186/200 [02:56<00:04,  3.10it/s]

[I 2025-11-10 14:11:07,057] Trial 185 pruned.
[I 2025-11-10 14:11:07,155] Trial 182 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02256181194474129, 'n_estimators': 251, 'subsample': 0.9998355045472594, 'colsample_bytree': 0.5479679052987356, 'min_child_weight': 6, 'gamma': 4.030899475338706, 'reg_alpha': 1.7467327831605723, 'reg_lambda': 0.010841001730823986, 'max_delta_step': 8}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  94%|█████████▍| 188/200 [02:58<00:06,  1.73it/s]

[I 2025-11-10 14:11:08,920] Trial 187 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.09922720021427357, 'n_estimators': 449, 'subsample': 0.5001707390972198, 'colsample_bytree': 0.5476864960515492, 'min_child_weight': 5, 'gamma': 4.047477561232893, 'reg_alpha': 0.06245943025666407, 'reg_lambda': 0.019907176812128634, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:11:09,089] Trial 186 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.12411749107099682, 'n_estimators': 447, 'subsample': 0.5004452508633837, 'colsample_bytree': 0.8181324124956287, 'min_child_weight': 4, 'gamma': 4.019951541766302, 'reg_alpha': 0.027726053253482683, 'reg_lambda': 0.005694526062251311, 'max_delta_step': 7}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  94%|█████████▍| 189/200 [02:59<00:06,  1.67it/s]

[I 2025-11-10 14:11:09,739] Trial 189 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1756441682063603, 'n_estimators': 499, 'subsample': 0.6195116506003299, 'colsample_bytree': 0.9561298248405605, 'min_child_weight': 5, 'gamma': 2.6861138258304122, 'reg_alpha': 0.12007379428230226, 'reg_lambda': 2.674645625998014, 'max_delta_step': 4}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  95%|█████████▌| 190/200 [02:59<00:05,  1.84it/s]

[I 2025-11-10 14:11:10,158] Trial 188 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.09555618739089809, 'n_estimators': 587, 'subsample': 0.6189972627314906, 'colsample_bytree': 0.9556253052483312, 'min_child_weight': 5, 'gamma': 3.991521663991584, 'reg_alpha': 0.14220021898402654, 'reg_lambda': 0.0172705016797453, 'max_delta_step': 4}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  96%|█████████▌| 191/200 [03:01<00:09,  1.04s/it]

[I 2025-11-10 14:11:12,330] Trial 190 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1749891576949192, 'n_estimators': 593, 'subsample': 0.6198804814614668, 'colsample_bytree': 0.8987967312890383, 'min_child_weight': 7, 'gamma': 4.1525619848039685, 'reg_alpha': 0.14886883068620932, 'reg_lambda': 3.931180885062946, 'max_delta_step': 4}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:11:12,338] Trial 191 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.20511430410460865, 'n_estimators': 568, 'subsample': 0.61889427505386, 'colsample_bytree': 0.9625521914983457, 'min_child_weight': 8, 'gamma': 2.7455865962582093, 'reg_alpha': 0.00021890178664035235, 'reg_lambda': 1.0307075088719761e-07, 'max_delta_step': 4}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  96%|█████████▋| 193/200 [03:04<00:07,  1.03s/it]

[I 2025-11-10 14:11:14,395] Trial 195 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.21881787262006752, 'n_estimators': 380, 'subsample': 0.5819711434429468, 'colsample_bytree': 0.7211013717237099, 'min_child_weight': 4, 'gamma': 3.7501909559617097, 'reg_alpha': 0.003385201436273036, 'reg_lambda': 0.23248013280202956, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  98%|█████████▊| 195/200 [03:04<00:03,  1.51it/s]

[I 2025-11-10 14:11:14,693] Trial 192 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.20678037663815865, 'n_estimators': 931, 'subsample': 0.5982483307302134, 'colsample_bytree': 0.7226968606566704, 'min_child_weight': 8, 'gamma': 1.1638385583433424, 'reg_alpha': 0.7196886432535307, 'reg_lambda': 9.280522064441669e-08, 'max_delta_step': 3}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:11:14,833] Trial 193 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.041488597433585815, 'n_estimators': 933, 'subsample': 0.6002711078302314, 'colsample_bytree': 0.7233951177512095, 'min_child_weight': 7, 'gamma': 4.143705123876823, 'reg_alpha': 0.8216568483135828, 'reg_lambda': 6.574118041291332e-07, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  98%|█████████▊| 196/200 [03:04<00:02,  1.59it/s]

[I 2025-11-10 14:11:15,363] Trial 194 finished with value: 0.5017543859649123 and parameters: {'max_depth': 3, 'learning_rate': 0.22131187909310512, 'n_estimators': 527, 'subsample': 0.6007017537430105, 'colsample_bytree': 0.7734905807130378, 'min_child_weight': 4, 'gamma': 3.809837433250392, 'reg_alpha': 0.001692981627149003, 'reg_lambda': 0.09363298233951717, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754:  98%|█████████▊| 197/200 [03:06<00:02,  1.00it/s]

[I 2025-11-10 14:11:17,317] Trial 196 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.24859407500921152, 'n_estimators': 525, 'subsample': 0.5521069967731398, 'colsample_bytree': 0.726312035027101, 'min_child_weight': 4, 'gamma': 1.1034055968885546, 'reg_alpha': 0.00047134022634602455, 'reg_lambda': 0.600148454416301, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754: 100%|█████████▉| 199/200 [03:07<00:00,  1.61it/s]

[I 2025-11-10 14:11:17,629] Trial 197 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.23937143357149188, 'n_estimators': 520, 'subsample': 0.5563739272493553, 'colsample_bytree': 0.7639410293627027, 'min_child_weight': 4, 'gamma': 4.342400829209259, 'reg_alpha': 0.0015135624942870904, 'reg_lambda': 0.4214363365430435, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.
[I 2025-11-10 14:11:17,810] Trial 199 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10755158355960322, 'n_estimators': 523, 'subsample': 0.5271577232497783, 'colsample_bytree': 0.7507973382172336, 'min_child_weight': 4, 'gamma': 3.208252310588658, 'reg_alpha': 0.0005469743644858309, 'reg_lambda': 0.13132310604148867, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

Best trial: 22. Best value: 0.501754: 100%|██████████| 200/200 [03:08<00:00,  1.06it/s]

[I 2025-11-10 14:11:18,477] Trial 198 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.10855480950024057, 'n_estimators': 844, 'subsample': 0.5489450948134961, 'colsample_bytree': 0.7724405717724148, 'min_child_weight': 4, 'gamma': 3.844852937508314, 'reg_alpha': 2.964284796998746e-07, 'reg_lambda': 0.47797553619101923, 'max_delta_step': 9}. Best is trial 22 with value: 0.5017543859649123.

[I 2025-11-10 14:11:19,377] A new study created in memory with name: 3_1_balanced_accuracy
Best trial: 2. Best value: 0.5:   0%|          | 1/200 [00:02<08:42,  2.63s/it]

[I 2025-11-10 14:11:21,993] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.18807975504663482, 'n_estimators': 531, 'subsample': 0.7496183943212442, 'colsample_bytree': 0.5965121517943893, 'min_child_weight': 6, 'gamma': 3.688218663161358, 'reg_alpha': 1.892812094615156, 'reg_lambda': 4.512380813804612e-07, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 0. Best value: 0.516257:   1%|          | 2/200 [00:03<04:40,  1.42s/it]

[I 2025-11-10 14:11:22,567] Trial 0 finished with value: 0.5162573099415205 and parameters: {'max_depth': 3, 'learning_rate': 0.022963861330145174, 'n_estimators': 481, 'subsample': 0.7972235515104495, 'colsample_bytree': 0.9065762349207809, 'min_child_weight': 4, 'gamma': 4.3098583987616434, 'reg_alpha': 2.379108662710202e-06, 'reg_lambda': 1.0074587580669527e-06, 'max_delta_step': 2}. Best is trial 0 with value: 0.5162573099415205.

Best trial: 0. Best value: 0.516257:   2%|▏         | 3/200 [00:03<03:14,  1.01it/s]

[I 2025-11-10 14:11:23,044] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10775583911318505, 'n_estimators': 763, 'subsample': 0.599655946097551, 'colsample_bytree': 0.6163986105317499, 'min_child_weight': 10, 'gamma': 2.251555499575657, 'reg_alpha': 7.22101920821981e-08, 'reg_lambda': 5.8866598899194405e-08, 'max_delta_step': 3}. Best is trial 0 with value: 0.5162573099415205.

Best trial: 4. Best value: 0.540117:   2%|▏         | 4/200 [00:05<04:49,  1.48s/it]

[I 2025-11-10 14:11:25,276] Trial 4 finished with value: 0.5401169590643276 and parameters: {'max_depth': 8, 'learning_rate': 0.17031731881473866, 'n_estimators': 355, 'subsample': 0.8748374246455775, 'colsample_bytree': 0.9682000134116855, 'min_child_weight': 1, 'gamma': 2.458986524909479, 'reg_alpha': 2.8213518551356864e-07, 'reg_lambda': 1.6728348959307506e-07, 'max_delta_step': 8}. Best is trial 4 with value: 0.5401169590643276.

Best trial: 6. Best value: 0.542632:   2%|▎         | 5/200 [00:07<04:32,  1.40s/it]

[I 2025-11-10 14:11:26,521] Trial 6 finished with value: 0.5426315789473685 and parameters: {'max_depth': 8, 'learning_rate': 0.08971454664761502, 'n_estimators': 596, 'subsample': 0.5574863741384304, 'colsample_bytree': 0.8096117848343762, 'min_child_weight': 3, 'gamma': 1.4840466362841198, 'reg_alpha': 0.755924545661762, 'reg_lambda': 0.014412994416004946, 'max_delta_step': 7}. Best is trial 6 with value: 0.5426315789473685.

Best trial: 6. Best value: 0.542632:   3%|▎         | 6/200 [00:07<03:17,  1.02s/it]

[I 2025-11-10 14:11:26,810] Trial 1 finished with value: 0.5151461988304094 and parameters: {'max_depth': 4, 'learning_rate': 0.014013394392948244, 'n_estimators': 1093, 'subsample': 0.649218308661703, 'colsample_bytree': 0.7981590449517092, 'min_child_weight': 2, 'gamma': 4.278224081489737, 'reg_alpha': 7.056754821439026e-05, 'reg_lambda': 1.523767222536187, 'max_delta_step': 10}. Best is trial 6 with value: 0.5426315789473685.

Best trial: 6. Best value: 0.542632:   4%|▎         | 7/200 [00:08<03:25,  1.06s/it]

[I 2025-11-10 14:11:27,967] Trial 7 finished with value: 0.49818713450292407 and parameters: {'max_depth': 4, 'learning_rate': 0.017761961012150163, 'n_estimators': 413, 'subsample': 0.9669333632219328, 'colsample_bytree': 0.57488676442023, 'min_child_weight': 4, 'gamma': 1.3575088310896377, 'reg_alpha': 0.20694047479163472, 'reg_lambda': 0.0024152798856003485, 'max_delta_step': 0}. Best is trial 6 with value: 0.5426315789473685.

Best trial: 6. Best value: 0.542632:   4%|▍         | 9/200 [00:11<05:41,  1.79s/it]

[I 2025-11-10 14:11:31,297] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1355332032403287, 'n_estimators': 1116, 'subsample': 0.711413059072247, 'colsample_bytree': 0.5033027329167344, 'min_child_weight': 6, 'gamma': 1.6187001713631082, 'reg_alpha': 1.1230095336912181e-07, 'reg_lambda': 1.1636326733958469e-06, 'max_delta_step': 5}. Best is trial 6 with value: 0.5426315789473685.
[I 2025-11-10 14:11:31,304] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.044506891809142586, 'n_estimators': 1341, 'subsample': 0.8267659478608829, 'colsample_bytree': 0.7193146455360253, 'min_child_weight': 1, 'gamma': 2.5446234125399263, 'reg_alpha': 5.401983115292596, 'reg_lambda': 0.0625098526729631, 'max_delta_step': 3}. Best is trial 6 with value: 0.5426315789473685.
[I 2025-11-10 14:11:31,311] Trial 9 finished with value: 0.522046783625731 and parameters: {'max_depth': 4, 'learning_rate': 0.07344561217179217, 'n_estimators': 617, 'subsample': 0.8876211562640899, 'colsample_bytree': 0.724852080695352, 'min_child_weight': 1, 'gamma': 1.0107204109778334, 'reg_alpha': 0.002254684324053969, 'reg_lambda': 0.002515974729805862, 'max_delta_step': 8}. Best is trial 6 with value: 0.5426315789473685.

Best trial: 6. Best value: 0.542632:   6%|▌         | 12/200 [00:13<03:09,  1.01s/it]

[I 2025-11-10 14:11:32,608] Trial 13 pruned.
[I 2025-11-10 14:11:32,683] Trial 11 pruned.
[I 2025-11-10 14:11:32,685] Trial 12 pruned.

Best trial: 6. Best value: 0.542632:   7%|▋         | 14/200 [00:13<01:54,  1.63it/s]

[I 2025-11-10 14:11:33,022] Trial 14 pruned.

Best trial: 6. Best value: 0.542632:   8%|▊         | 15/200 [00:14<02:01,  1.53it/s]

[I 2025-11-10 14:11:33,867] Trial 16 pruned.

Best trial: 6. Best value: 0.542632:   8%|▊         | 16/200 [00:15<02:23,  1.28it/s]

[I 2025-11-10 14:11:35,151] Trial 18 pruned.

Best trial: 6. Best value: 0.542632:   8%|▊         | 17/200 [00:16<02:04,  1.47it/s]

[I 2025-11-10 14:11:35,474] Trial 10 pruned.

Best trial: 6. Best value: 0.542632:   9%|▉         | 18/200 [00:16<01:57,  1.55it/s]

[I 2025-11-10 14:11:36,019] Trial 20 pruned.

Best trial: 6. Best value: 0.542632:  10%|▉         | 19/200 [00:17<02:05,  1.45it/s]

[I 2025-11-10 14:11:36,843] Trial 21 pruned.

Best trial: 6. Best value: 0.542632:  10%|█         | 20/200 [00:18<02:34,  1.16it/s]

[I 2025-11-10 14:11:38,159] Trial 15 finished with value: 0.5253801169590643 and parameters: {'max_depth': 9, 'learning_rate': 0.2534961336543582, 'n_estimators': 803, 'subsample': 0.922735404630021, 'colsample_bytree': 0.9954689247852055, 'min_child_weight': 3, 'gamma': 2.9840808555507765, 'reg_alpha': 2.0887261308543646e-05, 'reg_lambda': 0.046029286852589, 'max_delta_step': 9}. Best is trial 6 with value: 0.5426315789473685.

Best trial: 6. Best value: 0.542632:  10%|█         | 21/200 [00:19<02:04,  1.44it/s]

[I 2025-11-10 14:11:38,416] Trial 17 finished with value: 0.5256725146198831 and parameters: {'max_depth': 9, 'learning_rate': 0.08387872579657862, 'n_estimators': 763, 'subsample': 0.8541517928753453, 'colsample_bytree': 0.9868310158498512, 'min_child_weight': 3, 'gamma': 1.986842385424073, 'reg_alpha': 1.1278330910475815e-08, 'reg_lambda': 0.06980430353066532, 'max_delta_step': 10}. Best is trial 6 with value: 0.5426315789473685.

Best trial: 6. Best value: 0.542632:  11%|█         | 22/200 [00:19<01:43,  1.73it/s]

[I 2025-11-10 14:11:38,709] Trial 19 pruned.

Best trial: 6. Best value: 0.542632:  12%|█▏        | 23/200 [00:20<02:01,  1.45it/s]

[I 2025-11-10 14:11:39,669] Trial 22 pruned.

Best trial: 6. Best value: 0.542632:  12%|█▏        | 24/200 [00:20<01:46,  1.66it/s]

[I 2025-11-10 14:11:40,065] Trial 24 pruned.

Best trial: 6. Best value: 0.542632:  12%|█▎        | 25/200 [00:21<01:34,  1.85it/s]

[I 2025-11-10 14:11:40,448] Trial 25 pruned.

Best trial: 6. Best value: 0.542632:  13%|█▎        | 26/200 [00:21<01:25,  2.03it/s]

[I 2025-11-10 14:11:40,835] Trial 27 pruned.

Best trial: 6. Best value: 0.542632:  14%|█▎        | 27/200 [00:22<01:32,  1.87it/s]

[I 2025-11-10 14:11:41,473] Trial 23 pruned.
[I 2025-11-10 14:11:41,491] Trial 26 pruned.

Best trial: 6. Best value: 0.542632:  14%|█▍        | 29/200 [00:22<01:05,  2.63it/s]

[I 2025-11-10 14:11:41,865] Trial 28 pruned.

Best trial: 6. Best value: 0.542632:  15%|█▌        | 30/200 [00:22<01:08,  2.49it/s]

[I 2025-11-10 14:11:42,329] Trial 29 pruned.

Best trial: 6. Best value: 0.542632:  16%|█▌        | 32/200 [00:23<00:57,  2.93it/s]

[I 2025-11-10 14:11:42,777] Trial 31 pruned.
[I 2025-11-10 14:11:42,921] Trial 30 pruned.

Best trial: 6. Best value: 0.542632:  16%|█▋        | 33/200 [00:23<00:49,  3.36it/s]

[I 2025-11-10 14:11:43,112] Trial 32 pruned.

Best trial: 6. Best value: 0.542632:  17%|█▋        | 34/200 [00:24<00:48,  3.42it/s]

[I 2025-11-10 14:11:43,386] Trial 33 pruned.

Best trial: 6. Best value: 0.542632:  18%|█▊        | 36/200 [00:24<00:38,  4.22it/s]

[I 2025-11-10 14:11:43,596] Trial 34 pruned.
[I 2025-11-10 14:11:43,762] Trial 35 pruned.

Best trial: 6. Best value: 0.542632:  18%|█▊        | 37/200 [00:25<01:00,  2.70it/s]

[I 2025-11-10 14:11:44,449] Trial 36 pruned.

Best trial: 6. Best value: 0.542632:  19%|█▉        | 38/200 [00:25<01:01,  2.62it/s]

[I 2025-11-10 14:11:44,857] Trial 37 pruned.

Best trial: 6. Best value: 0.542632:  20%|█▉        | 39/200 [00:25<01:03,  2.54it/s]

[I 2025-11-10 14:11:45,280] Trial 39 pruned.

Best trial: 6. Best value: 0.542632:  20%|██        | 40/200 [00:26<00:53,  2.98it/s]

[I 2025-11-10 14:11:45,480] Trial 38 pruned.

Best trial: 6. Best value: 0.542632:  20%|██        | 41/200 [00:27<01:21,  1.94it/s]

[I 2025-11-10 14:11:46,416] Trial 41 pruned.

Best trial: 6. Best value: 0.542632:  22%|██▏       | 43/200 [00:27<01:01,  2.54it/s]

[I 2025-11-10 14:11:46,862] Trial 42 pruned.
[I 2025-11-10 14:11:47,022] Trial 40 pruned.

Best trial: 6. Best value: 0.542632:  22%|██▏       | 44/200 [00:28<01:09,  2.26it/s]

[I 2025-11-10 14:11:47,575] Trial 43 pruned.

Best trial: 6. Best value: 0.542632:  22%|██▎       | 45/200 [00:28<01:01,  2.53it/s]

[I 2025-11-10 14:11:47,863] Trial 46 pruned.

Best trial: 6. Best value: 0.542632:  23%|██▎       | 46/200 [00:29<01:35,  1.61it/s]

[I 2025-11-10 14:11:49,014] Trial 44 pruned.

Best trial: 6. Best value: 0.542632:  24%|██▎       | 47/200 [00:29<01:17,  1.98it/s]

[I 2025-11-10 14:11:49,234] Trial 48 pruned.
[I 2025-11-10 14:11:49,324] Trial 47 pruned.

Best trial: 6. Best value: 0.542632:  24%|██▍       | 49/200 [00:30<01:02,  2.41it/s]

[I 2025-11-10 14:11:49,862] Trial 51 pruned.

Best trial: 6. Best value: 0.542632:  25%|██▌       | 50/200 [00:30<00:54,  2.75it/s]

[I 2025-11-10 14:11:50,073] Trial 49 pruned.

Best trial: 6. Best value: 0.542632:  26%|██▌       | 51/200 [00:31<00:57,  2.58it/s]

[I 2025-11-10 14:11:50,530] Trial 53 pruned.

Best trial: 6. Best value: 0.542632:  26%|██▌       | 52/200 [00:31<01:11,  2.07it/s]

[I 2025-11-10 14:11:51,264] Trial 52 pruned.

Best trial: 6. Best value: 0.542632:  26%|██▋       | 53/200 [00:32<01:13,  2.01it/s]

[I 2025-11-10 14:11:51,799] Trial 54 pruned.

Best trial: 45. Best value: 0.543392:  27%|██▋       | 54/200 [00:32<01:03,  2.31it/s]

[I 2025-11-10 14:11:52,066] Trial 45 finished with value: 0.543391812865497 and parameters: {'max_depth': 3, 'learning_rate': 0.06668017051857461, 'n_estimators': 583, 'subsample': 0.898482068545196, 'colsample_bytree': 0.7310754508071053, 'min_child_weight': 1, 'gamma': 1.0838154849458053, 'reg_alpha': 0.20027459189131572, 'reg_lambda': 0.0012462473119125405, 'max_delta_step': 8}. Best is trial 45 with value: 0.543391812865497.

Best trial: 45. Best value: 0.543392:  28%|██▊       | 55/200 [00:32<00:56,  2.55it/s]

[I 2025-11-10 14:11:52,361] Trial 50 finished with value: 0.5214619883040936 and parameters: {'max_depth': 5, 'learning_rate': 0.2613237633004645, 'n_estimators': 445, 'subsample': 0.9617011211084369, 'colsample_bytree': 0.6699852203014437, 'min_child_weight': 3, 'gamma': 1.917470737528656, 'reg_alpha': 0.002898152888567968, 'reg_lambda': 0.003332945454082053, 'max_delta_step': 6}. Best is trial 45 with value: 0.543391812865497.

Best trial: 45. Best value: 0.543392:  28%|██▊       | 57/200 [00:33<00:44,  3.23it/s]

[I 2025-11-10 14:11:52,702] Trial 55 pruned.
[I 2025-11-10 14:11:52,820] Trial 56 pruned.

Best trial: 45. Best value: 0.543392:  29%|██▉       | 58/200 [00:33<00:43,  3.23it/s]

[I 2025-11-10 14:11:53,160] Trial 57 pruned.

Best trial: 45. Best value: 0.543392:  30%|██▉       | 59/200 [00:34<00:43,  3.21it/s]

[I 2025-11-10 14:11:53,461] Trial 58 pruned.

Best trial: 45. Best value: 0.543392:  30%|███       | 60/200 [00:34<00:46,  2.98it/s]

[I 2025-11-10 14:11:53,867] Trial 60 pruned.
[I 2025-11-10 14:11:53,930] Trial 59 pruned.

Best trial: 45. Best value: 0.543392:  31%|███       | 62/200 [00:35<00:43,  3.16it/s]

[I 2025-11-10 14:11:54,460] Trial 61 pruned.

Best trial: 45. Best value: 0.543392:  32%|███▏      | 63/200 [00:35<00:43,  3.15it/s]

[I 2025-11-10 14:11:54,777] Trial 62 pruned.

Best trial: 45. Best value: 0.543392:  32%|███▎      | 65/200 [00:35<00:39,  3.38it/s]

[I 2025-11-10 14:11:55,195] Trial 64 pruned.
[I 2025-11-10 14:11:55,359] Trial 63 pruned.

Best trial: 45. Best value: 0.543392:  33%|███▎      | 66/200 [00:36<00:46,  2.90it/s]

[I 2025-11-10 14:11:55,836] Trial 65 pruned.

Best trial: 45. Best value: 0.543392:  34%|███▍      | 68/200 [00:37<00:42,  3.14it/s]

[I 2025-11-10 14:11:56,345] Trial 67 pruned.
[I 2025-11-10 14:11:56,481] Trial 68 pruned.

Best trial: 45. Best value: 0.543392:  34%|███▍      | 69/200 [00:37<00:37,  3.45it/s]

[I 2025-11-10 14:11:56,703] Trial 66 pruned.

Best trial: 45. Best value: 0.543392:  36%|███▌      | 71/200 [00:37<00:33,  3.82it/s]

[I 2025-11-10 14:11:57,072] Trial 70 pruned.
[I 2025-11-10 14:11:57,210] Trial 69 pruned.

Best trial: 45. Best value: 0.543392:  36%|███▌      | 72/200 [00:38<00:39,  3.24it/s]

[I 2025-11-10 14:11:57,632] Trial 71 pruned.

Best trial: 45. Best value: 0.543392:  37%|███▋      | 74/200 [00:38<00:29,  4.31it/s]

[I 2025-11-10 14:11:57,827] Trial 74 pruned.
[I 2025-11-10 14:11:57,955] Trial 72 pruned.

Best trial: 45. Best value: 0.543392:  38%|███▊      | 75/200 [00:38<00:30,  4.13it/s]

[I 2025-11-10 14:11:58,222] Trial 73 pruned.

Best trial: 45. Best value: 0.543392:  38%|███▊      | 76/200 [00:39<00:38,  3.25it/s]

[I 2025-11-10 14:11:58,684] Trial 77 pruned.

Best trial: 45. Best value: 0.543392:  38%|███▊      | 77/200 [00:39<00:37,  3.30it/s]

[I 2025-11-10 14:11:58,977] Trial 76 pruned.

Best trial: 45. Best value: 0.543392:  39%|███▉      | 78/200 [00:39<00:32,  3.71it/s]

[I 2025-11-10 14:11:59,169] Trial 78 pruned.

Best trial: 45. Best value: 0.543392:  40%|███▉      | 79/200 [00:40<00:43,  2.77it/s]

[I 2025-11-10 14:11:59,743] Trial 79 pruned.

Best trial: 45. Best value: 0.543392:  40%|████      | 80/200 [00:40<00:48,  2.50it/s]

[I 2025-11-10 14:12:00,235] Trial 82 pruned.

Best trial: 45. Best value: 0.543392:  41%|████      | 82/200 [00:41<00:37,  3.18it/s]

[I 2025-11-10 14:12:00,616] Trial 81 pruned.
[I 2025-11-10 14:12:00,743] Trial 80 pruned.

Best trial: 45. Best value: 0.543392:  42%|████▏     | 83/200 [00:42<00:54,  2.13it/s]

[I 2025-11-10 14:12:01,576] Trial 84 pruned.
[I 2025-11-10 14:12:01,614] Trial 75 finished with value: 0.5237426900584795 and parameters: {'max_depth': 4, 'learning_rate': 0.09590328111874254, 'n_estimators': 502, 'subsample': 0.8027252817511366, 'colsample_bytree': 0.9511533988129912, 'min_child_weight': 4, 'gamma': 2.096517102796142, 'reg_alpha': 5.299824267134503e-07, 'reg_lambda': 2.423635412604695e-07, 'max_delta_step': 8}. Best is trial 45 with value: 0.543391812865497.

Best trial: 45. Best value: 0.543392:  42%|████▎     | 85/200 [00:43<01:01,  1.86it/s]

[I 2025-11-10 14:12:02,809] Trial 85 pruned.

Best trial: 45. Best value: 0.543392:  43%|████▎     | 86/200 [00:44<01:02,  1.84it/s]

[I 2025-11-10 14:12:03,377] Trial 87 pruned.
[I 2025-11-10 14:12:03,436] Trial 83 pruned.

Best trial: 45. Best value: 0.543392:  44%|████▍     | 88/200 [00:44<00:52,  2.12it/s]

[I 2025-11-10 14:12:04,110] Trial 86 pruned.
[I 2025-11-10 14:12:04,128] Trial 89 pruned.

Best trial: 45. Best value: 0.543392:  45%|████▌     | 90/200 [00:45<00:40,  2.68it/s]

[I 2025-11-10 14:12:04,525] Trial 90 pruned.

Best trial: 45. Best value: 0.543392:  46%|████▌     | 91/200 [00:45<00:41,  2.62it/s]

[I 2025-11-10 14:12:04,881] Trial 88 pruned.

Best trial: 45. Best value: 0.543392:  46%|████▋     | 93/200 [00:46<00:33,  3.17it/s]

[I 2025-11-10 14:12:05,273] Trial 91 pruned.
[I 2025-11-10 14:12:05,417] Trial 92 pruned.

Best trial: 45. Best value: 0.543392:  47%|████▋     | 94/200 [00:46<00:47,  2.23it/s]

[I 2025-11-10 14:12:06,248] Trial 93 pruned.
[I 2025-11-10 14:12:06,337] Trial 95 pruned.

Best trial: 45. Best value: 0.543392:  48%|████▊     | 96/200 [00:47<00:40,  2.56it/s]

[I 2025-11-10 14:12:06,875] Trial 94 pruned.

Best trial: 45. Best value: 0.543392:  48%|████▊     | 97/200 [00:47<00:37,  2.74it/s]

[I 2025-11-10 14:12:07,155] Trial 98 pruned.

Best trial: 45. Best value: 0.543392:  49%|████▉     | 98/200 [00:48<00:46,  2.17it/s]

[I 2025-11-10 14:12:07,899] Trial 97 pruned.

Best trial: 45. Best value: 0.543392:  50%|████▉     | 99/200 [00:49<00:47,  2.12it/s]

[I 2025-11-10 14:12:08,400] Trial 101 pruned.

Best trial: 45. Best value: 0.543392:  50%|█████     | 100/200 [00:49<00:50,  1.97it/s]

[I 2025-11-10 14:12:09,010] Trial 102 pruned.

Best trial: 45. Best value: 0.543392:  50%|█████     | 101/200 [00:50<00:49,  1.99it/s]

[I 2025-11-10 14:12:09,495] Trial 103 pruned.

Best trial: 100. Best value: 0.55848:  51%|█████     | 102/200 [00:50<00:40,  2.42it/s]

[I 2025-11-10 14:12:09,687] Trial 100 finished with value: 0.5584795321637428 and parameters: {'max_depth': 4, 'learning_rate': 0.23294080294118555, 'n_estimators': 517, 'subsample': 0.6166086959774403, 'colsample_bytree': 0.711164939094349, 'min_child_weight': 4, 'gamma': 2.091346916752934, 'reg_alpha': 0.1268685327826909, 'reg_lambda': 0.4911608266665908, 'max_delta_step': 7}. Best is trial 100 with value: 0.5584795321637428.

Best trial: 100. Best value: 0.55848:  52%|█████▏    | 103/200 [00:51<00:56,  1.71it/s]

[I 2025-11-10 14:12:10,691] Trial 104 pruned.

Best trial: 100. Best value: 0.55848:  52%|█████▏    | 104/200 [00:51<00:57,  1.68it/s]

[I 2025-11-10 14:12:11,314] Trial 105 pruned.

Best trial: 100. Best value: 0.55848:  52%|█████▎    | 105/200 [00:53<01:15,  1.26it/s]

[I 2025-11-10 14:12:12,584] Trial 107 pruned.

Best trial: 106. Best value: 0.564327:  54%|█████▎    | 107/200 [00:54<01:00,  1.54it/s]

[I 2025-11-10 14:12:13,642] Trial 106 finished with value: 0.564327485380117 and parameters: {'max_depth': 4, 'learning_rate': 0.24355873157790492, 'n_estimators': 422, 'subsample': 0.6707885130387546, 'colsample_bytree': 0.7475998177013831, 'min_child_weight': 4, 'gamma': 2.2396144102982873, 'reg_alpha': 0.22205929662616997, 'reg_lambda': 1.95297581847166, 'max_delta_step': 6}. Best is trial 106 with value: 0.564327485380117.
[I 2025-11-10 14:12:13,758] Trial 108 pruned.

Best trial: 106. Best value: 0.564327:  55%|█████▍    | 109/200 [00:54<00:38,  2.36it/s]

[I 2025-11-10 14:12:14,086] Trial 109 pruned.
[I 2025-11-10 14:12:14,211] Trial 96 finished with value: 0.5076608187134504 and parameters: {'max_depth': 4, 'learning_rate': 0.06184641249474678, 'n_estimators': 1217, 'subsample': 0.9293398728491418, 'colsample_bytree': 0.7984304701893655, 'min_child_weight': 2, 'gamma': 4.788200359184167, 'reg_alpha': 0.00024849223129185975, 'reg_lambda': 2.974599711568543e-08, 'max_delta_step': 9}. Best is trial 106 with value: 0.564327485380117.

Best trial: 106. Best value: 0.564327:  55%|█████▌    | 110/200 [00:55<00:32,  2.76it/s]

[I 2025-11-10 14:12:14,430] Trial 110 pruned.

Best trial: 106. Best value: 0.564327:  56%|█████▌    | 111/200 [00:55<00:40,  2.21it/s]

[I 2025-11-10 14:12:15,091] Trial 113 pruned.

Best trial: 106. Best value: 0.564327:  56%|█████▌    | 112/200 [00:56<00:51,  1.70it/s]

[I 2025-11-10 14:12:15,995] Trial 114 pruned.

Best trial: 111. Best value: 0.582398:  56%|█████▋    | 113/200 [00:56<00:41,  2.12it/s]

[I 2025-11-10 14:12:16,196] Trial 111 finished with value: 0.5823976608187135 and parameters: {'max_depth': 5, 'learning_rate': 0.24473687906246036, 'n_estimators': 471, 'subsample': 0.6254040312038925, 'colsample_bytree': 0.674818243448047, 'min_child_weight': 4, 'gamma': 2.5547229183415503, 'reg_alpha': 1.1196329132760605, 'reg_lambda': 3.843620099659124e-08, 'max_delta_step': 5}. Best is trial 111 with value: 0.5823976608187135.

Best trial: 111. Best value: 0.582398:  57%|█████▊    | 115/200 [00:57<00:31,  2.74it/s]

[I 2025-11-10 14:12:16,672] Trial 115 pruned.
[I 2025-11-10 14:12:16,785] Trial 116 pruned.

Best trial: 111. Best value: 0.582398:  58%|█████▊    | 117/200 [00:57<00:20,  4.07it/s]

[I 2025-11-10 14:12:16,929] Trial 112 finished with value: 0.541812865497076 and parameters: {'max_depth': 5, 'learning_rate': 0.24396521460878642, 'n_estimators': 518, 'subsample': 0.617680085210437, 'colsample_bytree': 0.7717594543988252, 'min_child_weight': 4, 'gamma': 2.256174196869813, 'reg_alpha': 0.11352072050824584, 'reg_lambda': 1.0500847973985489e-07, 'max_delta_step': 7}. Best is trial 111 with value: 0.5823976608187135.
[I 2025-11-10 14:12:17,049] Trial 99 finished with value: 0.5009356725146199 and parameters: {'max_depth': 5, 'learning_rate': 0.23676466730207177, 'n_estimators': 1273, 'subsample': 0.868037732350063, 'colsample_bytree': 0.7738464436071683, 'min_child_weight': 1, 'gamma': 4.484819773542575, 'reg_alpha': 0.17005440295012708, 'reg_lambda': 0.03947617939140468, 'max_delta_step': 9}. Best is trial 111 with value: 0.5823976608187135.

Best trial: 111. Best value: 0.582398:  59%|█████▉    | 118/200 [00:57<00:18,  4.51it/s]

[I 2025-11-10 14:12:17,217] Trial 118 pruned.

Best trial: 111. Best value: 0.582398:  60%|█████▉    | 119/200 [00:58<00:36,  2.22it/s]

[I 2025-11-10 14:12:18,195] Trial 117 pruned.
[I 2025-11-10 14:12:18,201] Trial 119 pruned.

Best trial: 111. Best value: 0.582398:  60%|██████    | 121/200 [00:59<00:23,  3.32it/s]

[I 2025-11-10 14:12:18,451] Trial 120 pruned.

Best trial: 111. Best value: 0.582398:  61%|██████    | 122/200 [00:59<00:25,  3.12it/s]

[I 2025-11-10 14:12:18,834] Trial 122 pruned.

Best trial: 111. Best value: 0.582398:  62%|██████▏   | 123/200 [01:00<00:29,  2.58it/s]

[I 2025-11-10 14:12:19,408] Trial 125 pruned.

Best trial: 111. Best value: 0.582398:  62%|██████▏   | 124/200 [01:00<00:29,  2.55it/s]

[I 2025-11-10 14:12:19,812] Trial 121 finished with value: 0.5539766081871346 and parameters: {'max_depth': 6, 'learning_rate': 0.16696560039017241, 'n_estimators': 437, 'subsample': 0.6177680223340009, 'colsample_bytree': 0.6892905408753983, 'min_child_weight': 4, 'gamma': 2.056473172171176, 'reg_alpha': 0.638846436327895, 'reg_lambda': 3.1328981048993014e-08, 'max_delta_step': 5}. Best is trial 111 with value: 0.5823976608187135.

Best trial: 111. Best value: 0.582398:  62%|██████▎   | 125/200 [01:00<00:26,  2.84it/s]

[I 2025-11-10 14:12:20,062] Trial 126 pruned.

Best trial: 111. Best value: 0.582398:  64%|██████▎   | 127/200 [01:01<00:21,  3.39it/s]

[I 2025-11-10 14:12:20,422] Trial 127 pruned.
[I 2025-11-10 14:12:20,573] Trial 128 pruned.

Best trial: 111. Best value: 0.582398:  64%|██████▍   | 128/200 [01:01<00:21,  3.41it/s]

[I 2025-11-10 14:12:20,862] Trial 123 finished with value: 0.5307017543859649 and parameters: {'max_depth': 5, 'learning_rate': 0.1834230649197768, 'n_estimators': 441, 'subsample': 0.6218854256922389, 'colsample_bytree': 0.7571725897365265, 'min_child_weight': 4, 'gamma': 2.4424965657101723, 'reg_alpha': 2.139381897720112, 'reg_lambda': 4.280305379268319e-08, 'max_delta_step': 5}. Best is trial 111 with value: 0.5823976608187135.

Best trial: 111. Best value: 0.582398:  64%|██████▍   | 129/200 [01:01<00:20,  3.40it/s]

[I 2025-11-10 14:12:21,158] Trial 130 pruned.

Best trial: 111. Best value: 0.582398:  66%|██████▌   | 132/200 [01:02<00:12,  5.57it/s]

[I 2025-11-10 14:12:21,380] Trial 124 finished with value: 0.5126315789473683 and parameters: {'max_depth': 5, 'learning_rate': 0.24890522198212428, 'n_estimators': 433, 'subsample': 0.6298450244847328, 'colsample_bytree': 0.757356849665211, 'min_child_weight': 3, 'gamma': 1.9138861120283412, 'reg_alpha': 0.11232193188477133, 'reg_lambda': 3.6449272180568576e-08, 'max_delta_step': 5}. Best is trial 111 with value: 0.5823976608187135.
[I 2025-11-10 14:12:21,474] Trial 129 pruned.
[I 2025-11-10 14:12:21,515] Trial 131 pruned.

Best trial: 111. Best value: 0.582398:  66%|██████▋   | 133/200 [01:02<00:14,  4.59it/s]

[I 2025-11-10 14:12:21,856] Trial 132 pruned.

Best trial: 111. Best value: 0.582398:  67%|██████▋   | 134/200 [01:02<00:13,  4.73it/s]

[I 2025-11-10 14:12:22,049] Trial 135 pruned.
[I 2025-11-10 14:12:22,074] Trial 133 pruned.

Best trial: 111. Best value: 0.582398:  68%|██████▊   | 136/200 [01:02<00:10,  6.09it/s]

[I 2025-11-10 14:12:22,245] Trial 134 pruned.

Best trial: 111. Best value: 0.582398:  69%|██████▉   | 138/200 [01:03<00:11,  5.42it/s]

[I 2025-11-10 14:12:22,557] Trial 138 pruned.
[I 2025-11-10 14:12:22,703] Trial 139 pruned.

Best trial: 111. Best value: 0.582398:  70%|███████   | 140/200 [01:03<00:09,  6.17it/s]

[I 2025-11-10 14:12:22,824] Trial 136 pruned.
[I 2025-11-10 14:12:22,972] Trial 137 pruned.

Best trial: 111. Best value: 0.582398:  71%|███████   | 142/200 [01:04<00:11,  5.13it/s]

[I 2025-11-10 14:12:23,385] Trial 140 pruned.
[I 2025-11-10 14:12:23,491] Trial 141 pruned.

Best trial: 111. Best value: 0.582398:  72%|███████▏  | 143/200 [01:04<00:11,  4.77it/s]

[I 2025-11-10 14:12:23,730] Trial 142 pruned.

Best trial: 111. Best value: 0.582398:  72%|███████▏  | 144/200 [01:04<00:12,  4.65it/s]

[I 2025-11-10 14:12:23,953] Trial 143 pruned.

Best trial: 111. Best value: 0.582398:  73%|███████▎  | 146/200 [01:04<00:10,  5.12it/s]

[I 2025-11-10 14:12:24,169] Trial 145 pruned.
[I 2025-11-10 14:12:24,313] Trial 144 pruned.

Best trial: 111. Best value: 0.582398:  74%|███████▎  | 147/200 [01:05<00:10,  5.22it/s]

[I 2025-11-10 14:12:24,509] Trial 146 pruned.

Best trial: 111. Best value: 0.582398:  74%|███████▍  | 148/200 [01:05<00:12,  4.22it/s]

[I 2025-11-10 14:12:24,842] Trial 147 pruned.

Best trial: 111. Best value: 0.582398:  74%|███████▍  | 149/200 [01:05<00:13,  3.67it/s]

[I 2025-11-10 14:12:25,201] Trial 148 pruned.
[I 2025-11-10 14:12:25,258] Trial 149 pruned.

Best trial: 111. Best value: 0.582398:  76%|███████▌  | 151/200 [01:06<00:10,  4.74it/s]

[I 2025-11-10 14:12:25,479] Trial 150 pruned.

Best trial: 111. Best value: 0.582398:  76%|███████▌  | 152/200 [01:06<00:11,  4.01it/s]

[I 2025-11-10 14:12:25,853] Trial 152 pruned.
[I 2025-11-10 14:12:25,918] Trial 153 pruned.

Best trial: 111. Best value: 0.582398:  77%|███████▋  | 154/200 [01:07<00:16,  2.77it/s]

[I 2025-11-10 14:12:26,884] Trial 154 pruned.

Best trial: 111. Best value: 0.582398:  78%|███████▊  | 155/200 [01:07<00:16,  2.73it/s]

[I 2025-11-10 14:12:27,270] Trial 155 pruned.

Best trial: 111. Best value: 0.582398:  78%|███████▊  | 156/200 [01:08<00:14,  2.97it/s]

[I 2025-11-10 14:12:27,520] Trial 156 pruned.
[I 2025-11-10 14:12:27,695] Trial 151 finished with value: 0.5237426900584795 and parameters: {'max_depth': 3, 'learning_rate': 0.09682972582540582, 'n_estimators': 411, 'subsample': 0.8741433274820596, 'colsample_bytree': 0.98337815166953, 'min_child_weight': 4, 'gamma': 0.8016635582472853, 'reg_alpha': 6.610912677254466e-06, 'reg_lambda': 0.020261460691534554, 'max_delta_step': 8}. Best is trial 111 with value: 0.5823976608187135.

Best trial: 111. Best value: 0.582398:  79%|███████▉  | 158/200 [01:08<00:13,  3.16it/s]

[I 2025-11-10 14:12:28,064] Trial 157 pruned.

Best trial: 111. Best value: 0.582398:  80%|████████  | 160/200 [01:09<00:12,  3.30it/s]

[I 2025-11-10 14:12:28,524] Trial 161 pruned.
[I 2025-11-10 14:12:28,693] Trial 160 pruned.

Best trial: 111. Best value: 0.582398:  80%|████████  | 161/200 [01:09<00:11,  3.38it/s]

[I 2025-11-10 14:12:28,972] Trial 158 pruned.
[I 2025-11-10 14:12:29,068] Trial 162 pruned.

Best trial: 111. Best value: 0.582398:  82%|████████▏ | 163/200 [01:09<00:08,  4.61it/s]

[I 2025-11-10 14:12:29,222] Trial 163 pruned.

Best trial: 111. Best value: 0.582398:  82%|████████▏ | 164/200 [01:10<00:09,  3.73it/s]

[I 2025-11-10 14:12:29,641] Trial 165 pruned.

[I 2025-11-10 14:12:30,661] Trial 167 pruned.

Best trial: 111. Best value: 0.582398:  83%|████████▎ | 166/200 [01:11<00:13,  2.57it/s]

[I 2025-11-10 14:12:30,845] Trial 159 finished with value: 0.5121052631578948 and parameters: {'max_depth': 5, 'learning_rate': 0.018795173836545793, 'n_estimators': 625, 'subsample': 0.6025652729061335, 'colsample_bytree': 0.8871898861051095, 'min_child_weight': 4, 'gamma': 1.7618672230049488, 'reg_alpha': 8.202516185440443e-05, 'reg_lambda': 0.05422157315269239, 'max_delta_step': 9}. Best is trial 111 with value: 0.5823976608187135.

Best trial: 111. Best value: 0.582398:  84%|████████▎ | 167/200 [01:12<00:15,  2.19it/s]

[I 2025-11-10 14:12:31,485] Trial 168 pruned.

Best trial: 111. Best value: 0.582398:  84%|████████▍ | 168/200 [01:12<00:14,  2.27it/s]

[I 2025-11-10 14:12:31,891] Trial 170 pruned.

Best trial: 111. Best value: 0.582398:  84%|████████▍ | 169/200 [01:13<00:15,  2.02it/s]

[I 2025-11-10 14:12:32,522] Trial 171 pruned.

Best trial: 111. Best value: 0.582398:  85%|████████▌ | 170/200 [01:13<00:15,  1.92it/s]

[I 2025-11-10 14:12:33,093] Trial 172 pruned.
[I 2025-11-10 14:12:33,138] Trial 166 finished with value: 0.533157894736842 and parameters: {'max_depth': 5, 'learning_rate': 0.028214648093533006, 'n_estimators': 518, 'subsample': 0.8985355970823344, 'colsample_bytree': 0.9903109651085866, 'min_child_weight': 3, 'gamma': 1.0893354793733725, 'reg_alpha': 1.5555744507462376e-05, 'reg_lambda': 0.034768765328813754, 'max_delta_step': 9}. Best is trial 111 with value: 0.5823976608187135.

Best trial: 111. Best value: 0.582398:  86%|████████▌ | 172/200 [01:14<00:11,  2.35it/s]

[I 2025-11-10 14:12:33,726] Trial 173 pruned.

Best trial: 111. Best value: 0.582398:  87%|████████▋ | 174/200 [01:15<00:09,  2.70it/s]

[I 2025-11-10 14:12:34,240] Trial 164 finished with value: 0.518187134502924 and parameters: {'max_depth': 9, 'learning_rate': 0.02806699820631503, 'n_estimators': 950, 'subsample': 0.8034750640223217, 'colsample_bytree': 0.990816424657971, 'min_child_weight': 4, 'gamma': 0.8056748912156904, 'reg_alpha': 1.3262402920741228e-05, 'reg_lambda': 0.0020626368172482704, 'max_delta_step': 9}. Best is trial 111 with value: 0.5823976608187135.
[I 2025-11-10 14:12:34,384] Trial 175 pruned.

Best trial: 111. Best value: 0.582398:  88%|████████▊ | 175/200 [01:15<00:08,  3.05it/s]

[I 2025-11-10 14:12:34,607] Trial 174 pruned.

Best trial: 111. Best value: 0.582398:  88%|████████▊ | 177/200 [01:15<00:07,  3.24it/s]

[I 2025-11-10 14:12:35,070] Trial 177 pruned.
[I 2025-11-10 14:12:35,232] Trial 178 pruned.

Best trial: 111. Best value: 0.582398:  89%|████████▉ | 178/200 [01:16<00:06,  3.32it/s]

[I 2025-11-10 14:12:35,522] Trial 176 pruned.

Best trial: 111. Best value: 0.582398:  90%|█████████ | 180/200 [01:16<00:05,  3.55it/s]

[I 2025-11-10 14:12:35,982] Trial 181 pruned.
[I 2025-11-10 14:12:36,099] Trial 180 pruned.

Best trial: 111. Best value: 0.582398:  90%|█████████ | 181/200 [01:17<00:07,  2.56it/s]

[I 2025-11-10 14:12:36,757] Trial 169 finished with value: 0.5509356725146198 and parameters: {'max_depth': 4, 'learning_rate': 0.22481860934670073, 'n_estimators': 699, 'subsample': 0.8296562906152026, 'colsample_bytree': 0.9715048907109642, 'min_child_weight': 1, 'gamma': 4.631156727542751, 'reg_alpha': 2.2289243920688843e-05, 'reg_lambda': 0.030168430310885983, 'max_delta_step': 7}. Best is trial 111 with value: 0.5823976608187135.

Best trial: 111. Best value: 0.582398:  91%|█████████ | 182/200 [01:17<00:07,  2.49it/s]

[I 2025-11-10 14:12:37,175] Trial 183 pruned.

Best trial: 111. Best value: 0.582398:  92%|█████████▏| 183/200 [01:18<00:07,  2.22it/s]

[I 2025-11-10 14:12:37,750] Trial 184 pruned.

Best trial: 111. Best value: 0.582398:  92%|█████████▏| 184/200 [01:18<00:06,  2.39it/s]

[I 2025-11-10 14:12:38,090] Trial 185 pruned.

Best trial: 111. Best value: 0.582398:  93%|█████████▎| 186/200 [01:19<00:05,  2.58it/s]

[I 2025-11-10 14:12:38,803] Trial 186 pruned.
[I 2025-11-10 14:12:38,909] Trial 187 pruned.

Best trial: 111. Best value: 0.582398:  94%|█████████▍| 188/200 [01:20<00:04,  2.80it/s]

[I 2025-11-10 14:12:39,472] Trial 188 pruned.
[I 2025-11-10 14:12:39,636] Trial 189 pruned.

Best trial: 111. Best value: 0.582398:  94%|█████████▍| 189/200 [01:20<00:05,  2.18it/s]

[I 2025-11-10 14:12:40,330] Trial 190 pruned.

Best trial: 111. Best value: 0.582398:  95%|█████████▌| 190/200 [01:21<00:03,  2.58it/s]

[I 2025-11-10 14:12:40,554] Trial 191 pruned.

Best trial: 111. Best value: 0.582398:  96%|█████████▌| 191/200 [01:21<00:03,  2.59it/s]

[I 2025-11-10 14:12:40,934] Trial 179 finished with value: 0.5015204678362574 and parameters: {'max_depth': 9, 'learning_rate': 0.029994899061763988, 'n_estimators': 1005, 'subsample': 0.8155917717918999, 'colsample_bytree': 0.964493689657903, 'min_child_weight': 4, 'gamma': 0.6774234952703277, 'reg_alpha': 0.0033657232476530623, 'reg_lambda': 0.003609824254294364, 'max_delta_step': 9}. Best is trial 111 with value: 0.5823976608187135.

Best trial: 111. Best value: 0.582398:  96%|█████████▌| 192/200 [01:21<00:02,  2.95it/s]

[I 2025-11-10 14:12:41,158] Trial 182 finished with value: 0.49040935672514613 and parameters: {'max_depth': 9, 'learning_rate': 0.06947579563862101, 'n_estimators': 977, 'subsample': 0.7769017736114306, 'colsample_bytree': 0.959326483098369, 'min_child_weight': 4, 'gamma': 0.4181036455299678, 'reg_alpha': 1.3408814133887467e-05, 'reg_lambda': 0.07072098725127732, 'max_delta_step': 5}. Best is trial 111 with value: 0.5823976608187135.

Best trial: 111. Best value: 0.582398:  96%|█████████▋| 193/200 [01:21<00:02,  3.37it/s]

[I 2025-11-10 14:12:41,359] Trial 193 pruned.

Best trial: 111. Best value: 0.582398:  97%|█████████▋| 194/200 [01:22<00:01,  3.77it/s]

[I 2025-11-10 14:12:41,553] Trial 192 pruned.

Best trial: 111. Best value: 0.582398:  98%|█████████▊| 195/200 [01:22<00:01,  3.83it/s]

[I 2025-11-10 14:12:41,810] Trial 194 pruned.

Best trial: 111. Best value: 0.582398:  98%|█████████▊| 196/200 [01:22<00:01,  3.60it/s]

[I 2025-11-10 14:12:42,128] Trial 196 pruned.

Best trial: 111. Best value: 0.582398:  98%|█████████▊| 197/200 [01:23<00:00,  3.70it/s]

[I 2025-11-10 14:12:42,371] Trial 195 pruned.
[I 2025-11-10 14:12:42,446] Trial 197 pruned.

Best trial: 111. Best value: 0.582398: 100%|█████████▉| 199/200 [01:23<00:00,  2.79it/s]

[I 2025-11-10 14:12:43,300] Trial 199 pruned.

Best trial: 111. Best value: 0.582398: 100%|██████████| 200/200 [01:24<00:00,  2.36it/s]

[I 2025-11-10 14:12:44,019] Trial 198 finished with value: 0.55093567251462 and parameters: {'max_depth': 4, 'learning_rate': 0.06396479186042917, 'n_estimators': 446, 'subsample': 0.6226854765199322, 'colsample_bytree': 0.6785423303559142, 'min_child_weight': 1, 'gamma': 4.380762004180233, 'reg_alpha': 3.963099022013516e-05, 'reg_lambda': 3.4407936730562654e-08, 'max_delta_step': 10}. Best is trial 111 with value: 0.5823976608187135.

[I 2025-11-10 14:12:44,934] A new study created in memory with name: 3_2_balanced_accuracy
Best trial: 0. Best value: 0.468538:   0%|          | 1/200 [00:02<09:00,  2.72s/it]

[I 2025-11-10 14:12:47,651] Trial 0 finished with value: 0.4685380116959064 and parameters: {'max_depth': 6, 'learning_rate': 0.19489778046290007, 'n_estimators': 429, 'subsample': 0.6364224738513012, 'colsample_bytree': 0.8068297128862943, 'min_child_weight': 1, 'gamma': 2.4218278434620784, 'reg_alpha': 4.421140322586624, 'reg_lambda': 4.86943539204888e-07, 'max_delta_step': 10}. Best is trial 0 with value: 0.4685380116959064.

Best trial: 1. Best value: 0.5:   1%|          | 2/200 [00:03<04:51,  1.47s/it]

[I 2025-11-10 14:12:48,243] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.08568276111565959, 'n_estimators': 771, 'subsample': 0.8481874058550692, 'colsample_bytree': 0.9743480488204959, 'min_child_weight': 6, 'gamma': 2.419800414525271, 'reg_alpha': 0.00780183671166559, 'reg_lambda': 5.150139012724175e-08, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   2%|▏         | 3/200 [00:05<05:35,  1.70s/it]

[I 2025-11-10 14:12:50,218] Trial 3 finished with value: 0.4212280701754386 and parameters: {'max_depth': 4, 'learning_rate': 0.017159259011197855, 'n_estimators': 1061, 'subsample': 0.8555126127327887, 'colsample_bytree': 0.516095899023528, 'min_child_weight': 3, 'gamma': 3.8778702200109945, 'reg_alpha': 0.0001823464039814973, 'reg_lambda': 0.0003942723838777592, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   2%|▏         | 4/200 [00:05<04:12,  1.29s/it]

[I 2025-11-10 14:12:50,879] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.012449321685949647, 'n_estimators': 733, 'subsample': 0.6394269510598493, 'colsample_bytree': 0.7204703707569493, 'min_child_weight': 9, 'gamma': 4.237224112829091, 'reg_alpha': 0.0004569173481724084, 'reg_lambda': 1.1551131130968858e-05, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 7. Best value: 0.50117:   2%|▎         | 5/200 [00:07<04:46,  1.47s/it]

[I 2025-11-10 14:12:52,657] Trial 7 finished with value: 0.5011695906432749 and parameters: {'max_depth': 6, 'learning_rate': 0.045916235198462343, 'n_estimators': 403, 'subsample': 0.6168870734725844, 'colsample_bytree': 0.6600667991543716, 'min_child_weight': 4, 'gamma': 1.6440057440002387, 'reg_alpha': 7.670622189175752e-06, 'reg_lambda': 2.1029856900329633e-07, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:   3%|▎         | 6/200 [00:07<03:23,  1.05s/it]

[I 2025-11-10 14:12:52,905] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.22047667448231567, 'n_estimators': 589, 'subsample': 0.676436554460441, 'colsample_bytree': 0.8394966929911832, 'min_child_weight': 7, 'gamma': 2.4041611363938005, 'reg_alpha': 9.590674228400901e-06, 'reg_lambda': 5.386726456167968e-07, 'max_delta_step': 3}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:   4%|▎         | 7/200 [00:08<02:52,  1.12it/s]

[I 2025-11-10 14:12:53,472] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.012822361369901702, 'n_estimators': 1244, 'subsample': 0.5406653606195978, 'colsample_bytree': 0.6626993883019732, 'min_child_weight': 9, 'gamma': 1.962538980372654, 'reg_alpha': 6.993386623138322, 'reg_lambda': 1.1686342602700168, 'max_delta_step': 4}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:   4%|▍         | 8/200 [00:09<02:36,  1.23it/s]

[I 2025-11-10 14:12:54,112] Trial 2 finished with value: 0.4614619883040936 and parameters: {'max_depth': 6, 'learning_rate': 0.010731175222860297, 'n_estimators': 1351, 'subsample': 0.9924413717403007, 'colsample_bytree': 0.7165638516050634, 'min_child_weight': 2, 'gamma': 1.6633061871884092, 'reg_alpha': 0.0016524324127892539, 'reg_lambda': 0.274204064744416, 'max_delta_step': 10}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:   4%|▍         | 9/200 [00:09<02:04,  1.53it/s]

[I 2025-11-10 14:12:54,414] Trial 8 finished with value: 0.4323391812865497 and parameters: {'max_depth': 8, 'learning_rate': 0.05692745021287748, 'n_estimators': 274, 'subsample': 0.5769829102978838, 'colsample_bytree': 0.9243435266588093, 'min_child_weight': 2, 'gamma': 4.58565963236137, 'reg_alpha': 0.00017697656046033775, 'reg_lambda': 3.228750362942497e-08, 'max_delta_step': 4}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:   5%|▌         | 10/200 [00:10<02:25,  1.31it/s]

[I 2025-11-10 14:12:55,429] Trial 10 finished with value: 0.4931578947368422 and parameters: {'max_depth': 7, 'learning_rate': 0.025460343317638606, 'n_estimators': 240, 'subsample': 0.9015565898144678, 'colsample_bytree': 0.7170943330533002, 'min_child_weight': 3, 'gamma': 0.9237373710392022, 'reg_alpha': 0.1343303467925165, 'reg_lambda': 9.303719634797188e-06, 'max_delta_step': 4}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:   6%|▌         | 12/200 [00:11<01:33,  2.02it/s]

[I 2025-11-10 14:12:55,768] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2841368300335215, 'n_estimators': 688, 'subsample': 0.837063355860169, 'colsample_bytree': 0.617590038977509, 'min_child_weight': 10, 'gamma': 3.4104117602651995, 'reg_alpha': 1.6734865072175243e-05, 'reg_lambda': 0.0002238694321416928, 'max_delta_step': 8}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:12:55,936] Trial 11 pruned.

Best trial: 7. Best value: 0.50117:   6%|▋         | 13/200 [00:13<03:24,  1.09s/it]

[I 2025-11-10 14:12:58,418] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1698888163640209, 'n_estimators': 836, 'subsample': 0.8618769440394713, 'colsample_bytree': 0.8219814961728706, 'min_child_weight': 8, 'gamma': 0.8313383198916896, 'reg_alpha': 1.9963935782913562e-05, 'reg_lambda': 7.060827876888502e-07, 'max_delta_step': 4}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:   7%|▋         | 14/200 [00:14<03:39,  1.18s/it]

[I 2025-11-10 14:12:59,805] Trial 13 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.030851281994719468, 'n_estimators': 978, 'subsample': 0.7512453097114075, 'colsample_bytree': 0.5691098269263821, 'min_child_weight': 5, 'gamma': 0.4323567360892917, 'reg_alpha': 2.1629990564642366e-08, 'reg_lambda': 0.0076002021361775175, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:   8%|▊         | 15/200 [00:15<02:54,  1.06it/s]

[I 2025-11-10 14:13:00,204] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.0751043571949844, 'n_estimators': 888, 'subsample': 0.7549079906946985, 'colsample_bytree': 0.9871931857749782, 'min_child_weight': 5, 'gamma': 0.0417192477943229, 'reg_alpha': 5.723588016824175e-08, 'reg_lambda': 1.0354282157793278e-08, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:   8%|▊         | 16/200 [00:15<02:13,  1.38it/s]

[I 2025-11-10 14:13:00,417] Trial 15 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.07976229802676015, 'n_estimators': 929, 'subsample': 0.741675529380604, 'colsample_bytree': 0.9961088427536181, 'min_child_weight': 5, 'gamma': 0.18086316427110383, 'reg_alpha': 1.2070493120866306e-08, 'reg_lambda': 1.2360811332546397e-08, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:   8%|▊         | 17/200 [00:15<01:59,  1.53it/s]

[I 2025-11-10 14:13:00,903] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07386561614151652, 'n_estimators': 531, 'subsample': 0.7431044925033472, 'colsample_bytree': 0.9126173617689347, 'min_child_weight': 5, 'gamma': 0.03377324342784238, 'reg_alpha': 1.20486238070265e-07, 'reg_lambda': 1.5600512959274804e-08, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:   9%|▉         | 18/200 [00:17<02:41,  1.13it/s]

[I 2025-11-10 14:13:02,320] Trial 17 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09753425692435798, 'n_estimators': 514, 'subsample': 0.7554989529039723, 'colsample_bytree': 0.9499613974105909, 'min_child_weight': 5, 'gamma': 3.134473102795134, 'reg_alpha': 0.02283902839113257, 'reg_lambda': 2.6482867742780973e-08, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  10%|▉         | 19/200 [00:18<02:20,  1.29it/s]

[I 2025-11-10 14:13:02,845] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.12102505607634843, 'n_estimators': 501, 'subsample': 0.9396777313691111, 'colsample_bytree': 0.9000999517250394, 'min_child_weight': 6, 'gamma': 3.034572504849098, 'reg_alpha': 0.00937398091974007, 'reg_lambda': 1.3362528759830547e-05, 'max_delta_step': 6}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:13:02,935] Trial 18 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.10700624041078957, 'n_estimators': 551, 'subsample': 0.5098523522011421, 'colsample_bytree': 0.8689257052753755, 'min_child_weight': 6, 'gamma': 2.9661524250939144, 'reg_alpha': 0.01712087175845234, 'reg_lambda': 7.652581312675337e-08, 'max_delta_step': 6}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  10%|█         | 21/200 [00:19<02:02,  1.46it/s]

[I 2025-11-10 14:13:03,998] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.040706698464952444, 'n_estimators': 340, 'subsample': 0.508612145238893, 'colsample_bytree': 0.8705502004607789, 'min_child_weight': 7, 'gamma': 1.3969693487050616, 'reg_alpha': 1.570494570005209e-06, 'reg_lambda': 2.0986276036582337e-05, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:13:04,016] Trial 23 pruned.

Best trial: 7. Best value: 0.50117:  12%|█▏        | 23/200 [00:21<02:21,  1.25it/s]

[I 2025-11-10 14:13:05,948] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.037519368739003314, 'n_estimators': 1118, 'subsample': 0.9818842532274741, 'colsample_bytree': 0.6505680203606562, 'min_child_weight': 7, 'gamma': 3.1576179085597245, 'reg_alpha': 0.027268220180516615, 'reg_lambda': 6.368023166974994e-06, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  12%|█▏        | 24/200 [00:22<02:53,  1.02it/s]

[I 2025-11-10 14:13:07,586] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.022147110443134055, 'n_estimators': 725, 'subsample': 0.6484317282516022, 'colsample_bytree': 0.7544890521157874, 'min_child_weight': 10, 'gamma': 4.669091366894924, 'reg_alpha': 0.0010580604408996315, 'reg_lambda': 3.261212255336328e-06, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  12%|█▎        | 25/200 [00:22<02:19,  1.26it/s]

[I 2025-11-10 14:13:07,776] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.02430959186249098, 'n_estimators': 741, 'subsample': 0.8127157007933228, 'colsample_bytree': 0.6754085076391961, 'min_child_weight': 10, 'gamma': 4.690875049952572, 'reg_alpha': 0.0007704737889484281, 'reg_lambda': 2.0064552275458586e-06, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  13%|█▎        | 26/200 [00:23<01:54,  1.52it/s]

[I 2025-11-10 14:13:08,037] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.04160191781163321, 'n_estimators': 1103, 'subsample': 0.6899460614944986, 'colsample_bytree': 0.7790161031046625, 'min_child_weight': 7, 'gamma': 1.6471347773295049, 'reg_alpha': 3.1121034262550376e-06, 'reg_lambda': 2.1348243241602125e-07, 'max_delta_step': 2}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  14%|█▎        | 27/200 [00:24<02:20,  1.23it/s]

[I 2025-11-10 14:13:09,278] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.020773471119508377, 'n_estimators': 704, 'subsample': 0.6819557068566665, 'colsample_bytree': 0.7213156805540388, 'min_child_weight': 10, 'gamma': 4.8895665924991984, 'reg_alpha': 0.0012036789027415765, 'reg_lambda': 2.4498592555745426e-07, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  14%|█▍        | 28/200 [00:26<03:07,  1.09s/it]

[I 2025-11-10 14:13:11,092] Trial 29 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05191250333668871, 'n_estimators': 641, 'subsample': 0.5839121218290502, 'colsample_bytree': 0.7187546271184672, 'min_child_weight': 8, 'gamma': 2.1213779276295317, 'reg_alpha': 0.7241933876111074, 'reg_lambda': 6.732685518606568e-05, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:13:11,189] Trial 28 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05278250850552291, 'n_estimators': 656, 'subsample': 0.5841520505947613, 'colsample_bytree': 0.7160048736830574, 'min_child_weight': 8, 'gamma': 4.218623349993269, 'reg_alpha': 0.3776036699444016, 'reg_lambda': 1.5108686384040546e-07, 'max_delta_step': 2}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  15%|█▌        | 30/200 [00:26<01:52,  1.51it/s]

[I 2025-11-10 14:13:11,336] Trial 27 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.052321412708766425, 'n_estimators': 735, 'subsample': 0.8191077080799664, 'colsample_bytree': 0.6950156908825669, 'min_child_weight': 8, 'gamma': 4.103600824902405, 'reg_alpha': 0.36589000169722063, 'reg_lambda': 7.33967265759476e-05, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  16%|█▌        | 31/200 [00:27<01:54,  1.48it/s]

[I 2025-11-10 14:13:12,051] Trial 32 pruned.

Best trial: 7. Best value: 0.50117:  16%|█▌        | 32/200 [00:27<01:54,  1.47it/s]

[I 2025-11-10 14:13:12,744] Trial 33 pruned.

Best trial: 7. Best value: 0.50117:  16%|█▋        | 33/200 [00:28<01:42,  1.63it/s]

[I 2025-11-10 14:13:13,176] Trial 30 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.13449919821153347, 'n_estimators': 811, 'subsample': 0.5914473803897792, 'colsample_bytree': 0.6088870735397065, 'min_child_weight': 8, 'gamma': 4.220931808404861, 'reg_alpha': 0.7981254549324822, 'reg_lambda': 9.103252531899852e-05, 'max_delta_step': 2}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  17%|█▋        | 34/200 [00:29<02:29,  1.11it/s]

[I 2025-11-10 14:13:14,838] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.15809898729773608, 'n_estimators': 790, 'subsample': 0.5651270509531564, 'colsample_bytree': 0.6068512129360224, 'min_child_weight': 4, 'gamma': 4.100000165132519, 'reg_alpha': 8.209450773172909e-05, 'reg_lambda': 0.0076481272593502915, 'max_delta_step': 2}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  18%|█▊        | 35/200 [00:33<04:15,  1.55s/it]

[I 2025-11-10 14:13:18,013] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.014432577978473138, 'n_estimators': 1342, 'subsample': 0.5368417061985895, 'colsample_bytree': 0.6521903312389001, 'min_child_weight': 9, 'gamma': 2.1767575845823472, 'reg_alpha': 4.709152506442657, 'reg_lambda': 7.9788960104929405, 'max_delta_step': 10}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  18%|█▊        | 36/200 [00:33<03:17,  1.21s/it]

[I 2025-11-10 14:13:18,377] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01000755458039811, 'n_estimators': 1261, 'subsample': 0.5353138483997562, 'colsample_bytree': 0.6540744839700222, 'min_child_weight': 9, 'gamma': 2.085637396925722, 'reg_alpha': 3.369694305309495, 'reg_lambda': 7.057342042247794, 'max_delta_step': 9}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  18%|█▊        | 37/200 [00:33<02:42,  1.00it/s]

[I 2025-11-10 14:13:18,860] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.010083834678238443, 'n_estimators': 1236, 'subsample': 0.551218980460016, 'colsample_bytree': 0.6586887160696908, 'min_child_weight': 9, 'gamma': 2.094528301282675, 'reg_alpha': 9.608547162410009, 'reg_lambda': 8.081857997120178, 'max_delta_step': 9}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  19%|█▉        | 38/200 [00:35<03:05,  1.15s/it]

[I 2025-11-10 14:13:20,365] Trial 40 pruned.

Best trial: 7. Best value: 0.50117:  20%|█▉        | 39/200 [00:35<02:22,  1.13it/s]

[I 2025-11-10 14:13:20,642] Trial 37 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01053401862660164, 'n_estimators': 1285, 'subsample': 0.5288727093525087, 'colsample_bytree': 0.6637893020496631, 'min_child_weight': 9, 'gamma': 2.024083984021272, 'reg_alpha': 4.685772424026759, 'reg_lambda': 2.3379661975908306, 'max_delta_step': 5}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  20%|██        | 40/200 [00:36<01:55,  1.38it/s]

[I 2025-11-10 14:13:20,972] Trial 41 pruned.

Best trial: 7. Best value: 0.50117:  20%|██        | 41/200 [00:37<02:38,  1.00it/s]

[I 2025-11-10 14:13:22,613] Trial 43 pruned.
[I 2025-11-10 14:13:22,616] Trial 42 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.018254247022625045, 'n_estimators': 435, 'subsample': 0.6506643384752775, 'colsample_bytree': 0.5359063683958407, 'min_child_weight': 6, 'gamma': 2.746943162672213, 'reg_alpha': 0.003845299391572638, 'reg_lambda': 0.0018171492503385063, 'max_delta_step': 3}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  22%|██▏       | 43/200 [00:37<01:31,  1.72it/s]

[I 2025-11-10 14:13:22,797] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.011870408533642268, 'n_estimators': 1013, 'subsample': 0.6501795230954337, 'colsample_bytree': 0.5205957294423778, 'min_child_weight': 9, 'gamma': 1.2476579128834304, 'reg_alpha': 0.0051275426873205, 'reg_lambda': 0.16473752663610464, 'max_delta_step': 3}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  22%|██▏       | 44/200 [00:38<01:29,  1.74it/s]

[I 2025-11-10 14:13:23,350] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.018586949301461805, 'n_estimators': 1213, 'subsample': 0.5471578907732311, 'colsample_bytree': 0.5247484491829042, 'min_child_weight': 9, 'gamma': 2.0532683011432713, 'reg_alpha': 0.0033212796851042198, 'reg_lambda': 0.1020754552786896, 'max_delta_step': 3}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  22%|██▎       | 45/200 [00:39<01:53,  1.37it/s]

[I 2025-11-10 14:13:24,524] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2544739643590515, 'n_estimators': 323, 'subsample': 0.6195688676126061, 'colsample_bytree': 0.8346310135247035, 'min_child_weight': 7, 'gamma': 2.3088415526679156, 'reg_alpha': 9.66957975336837e-06, 'reg_lambda': 6.939889488013075e-07, 'max_delta_step': 4}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  23%|██▎       | 46/200 [00:40<02:12,  1.17it/s]

[I 2025-11-10 14:13:25,724] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2893529439114996, 'n_estimators': 585, 'subsample': 0.6203699496175888, 'colsample_bytree': 0.9604954974626791, 'min_child_weight': 7, 'gamma': 2.301418405342146, 'reg_alpha': 8.297062037845957e-06, 'reg_lambda': 6.595394240714877e-07, 'max_delta_step': 4}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:13:25,733] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.24552791160681886, 'n_estimators': 605, 'subsample': 0.6168028159289414, 'colsample_bytree': 0.8350313534335138, 'min_child_weight': 7, 'gamma': 2.383409551363075, 'reg_alpha': 9.396702015677631e-06, 'reg_lambda': 6.991111551187691e-07, 'max_delta_step': 4}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  24%|██▍       | 48/200 [00:41<01:31,  1.67it/s]

[I 2025-11-10 14:13:26,263] Trial 47 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.25266484958853647, 'n_estimators': 619, 'subsample': 0.6093009222487712, 'colsample_bytree': 0.8361563838755139, 'min_child_weight': 7, 'gamma': 2.430975798891863, 'reg_alpha': 1.485311852950894e-05, 'reg_lambda': 7.212124917759847e-07, 'max_delta_step': 4}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  24%|██▍       | 49/200 [00:41<01:30,  1.67it/s]

[I 2025-11-10 14:13:26,866] Trial 50 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.20626264269239697, 'n_estimators': 212, 'subsample': 0.6811538354975083, 'colsample_bytree': 0.6957576901557391, 'min_child_weight': 6, 'gamma': 3.5600265246445586, 'reg_alpha': 3.1827794626950865e-07, 'reg_lambda': 1.0005392655613731e-07, 'max_delta_step': 5}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  25%|██▌       | 50/200 [00:42<01:31,  1.63it/s]

[I 2025-11-10 14:13:27,508] Trial 48 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2528809127250539, 'n_estimators': 606, 'subsample': 0.6052925738819981, 'colsample_bytree': 0.963548608973518, 'min_child_weight': 6, 'gamma': 3.6543296746225575, 'reg_alpha': 1.0784433423387367e-05, 'reg_lambda': 5.856134367634312e-07, 'max_delta_step': 6}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  26%|██▌       | 51/200 [00:42<01:21,  1.82it/s]

[I 2025-11-10 14:13:27,889] Trial 52 pruned.

Best trial: 7. Best value: 0.50117:  26%|██▋       | 53/200 [00:43<01:08,  2.16it/s]

[I 2025-11-10 14:13:28,601] Trial 53 pruned.
[I 2025-11-10 14:13:28,727] Trial 49 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2221028020373563, 'n_estimators': 628, 'subsample': 0.675942715125356, 'colsample_bytree': 0.6926683886584464, 'min_child_weight': 6, 'gamma': 3.5388080469172007, 'reg_alpha': 4.854950471130075e-07, 'reg_lambda': 8.157539246638506e-08, 'max_delta_step': 6}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  27%|██▋       | 54/200 [00:45<01:44,  1.40it/s]

[I 2025-11-10 14:13:30,068] Trial 54 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.20102515466873006, 'n_estimators': 460, 'subsample': 0.8540565774540546, 'colsample_bytree': 0.6314319805909787, 'min_child_weight': 10, 'gamma': 1.791202795359943, 'reg_alpha': 4.865244736197034e-05, 'reg_lambda': 2.246297257994111e-05, 'max_delta_step': 8}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  28%|██▊       | 55/200 [00:45<01:28,  1.63it/s]

[I 2025-11-10 14:13:30,430] Trial 51 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.02922252608717684, 'n_estimators': 889, 'subsample': 0.6752136310147652, 'colsample_bytree': 0.6902626457485882, 'min_child_weight': 6, 'gamma': 3.5201722188286464, 'reg_alpha': 5.0182843649668715e-05, 'reg_lambda': 4.9541134764076754e-08, 'max_delta_step': 5}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  28%|██▊       | 56/200 [00:45<01:20,  1.78it/s]

[I 2025-11-10 14:13:30,868] Trial 56 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.09354922082859649, 'n_estimators': 455, 'subsample': 0.8635067905313608, 'colsample_bytree': 0.5557994549768972, 'min_child_weight': 10, 'gamma': 1.7967938970299488, 'reg_alpha': 3.3140662081257374e-06, 'reg_lambda': 2.6808397083426583e-05, 'max_delta_step': 8}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  28%|██▊       | 57/200 [00:46<01:35,  1.50it/s]

[I 2025-11-10 14:13:31,784] Trial 55 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.20121296204182673, 'n_estimators': 683, 'subsample': 0.8476065661807164, 'colsample_bytree': 0.6382250492602033, 'min_child_weight': 10, 'gamma': 1.7900895447202503, 'reg_alpha': 3.30315866961212e-05, 'reg_lambda': 0.024857470090575217, 'max_delta_step': 8}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  29%|██▉       | 58/200 [00:47<01:25,  1.67it/s]

[I 2025-11-10 14:13:32,235] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.08948112342008993, 'n_estimators': 373, 'subsample': 0.8443020909733764, 'colsample_bytree': 0.894340179246766, 'min_child_weight': 10, 'gamma': 3.359054353989105, 'reg_alpha': 8.72532670345738e-07, 'reg_lambda': 0.03277632056188056, 'max_delta_step': 8}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  30%|███       | 60/200 [00:47<00:56,  2.47it/s]

[I 2025-11-10 14:13:32,547] Trial 58 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.09235095941920896, 'n_estimators': 368, 'subsample': 0.7146450639792021, 'colsample_bytree': 0.6324635677684047, 'min_child_weight': 10, 'gamma': 3.8451345198936866, 'reg_alpha': 4.383682987946626e-06, 'reg_lambda': 0.025877875043212335, 'max_delta_step': 8}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:13:32,691] Trial 60 pruned.

Best trial: 7. Best value: 0.50117:  30%|███       | 61/200 [00:48<00:49,  2.81it/s]

[I 2025-11-10 14:13:32,933] Trial 61 pruned.

Best trial: 7. Best value: 0.50117:  31%|███       | 62/200 [00:48<00:55,  2.49it/s]

[I 2025-11-10 14:13:33,437] Trial 62 pruned.

Best trial: 7. Best value: 0.50117:  32%|███▏      | 63/200 [00:49<01:36,  1.42it/s]

[I 2025-11-10 14:13:34,836] Trial 59 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.05982429172589134, 'n_estimators': 782, 'subsample': 0.7244908129092175, 'colsample_bytree': 0.6358431239322596, 'min_child_weight': 5, 'gamma': 3.90827204720591, 'reg_alpha': 3.540369839379421e-06, 'reg_lambda': 0.025144711547661975, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  32%|███▏      | 64/200 [00:50<01:33,  1.46it/s]

[I 2025-11-10 14:13:35,490] Trial 63 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1146030182508465, 'n_estimators': 557, 'subsample': 0.9035096924559521, 'colsample_bytree': 0.9357785248985451, 'min_child_weight': 8, 'gamma': 0.47703351936259875, 'reg_alpha': 0.04084107391637893, 'reg_lambda': 0.00017668582160602466, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  32%|███▎      | 65/200 [00:51<01:36,  1.40it/s]

[I 2025-11-10 14:13:36,269] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.17264617392188464, 'n_estimators': 693, 'subsample': 0.8288187312056081, 'colsample_bytree': 0.8663278999420306, 'min_child_weight': 8, 'gamma': 0.4166962898893676, 'reg_alpha': 3.52092719212667e-05, 'reg_lambda': 0.00015159605611462834, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  33%|███▎      | 66/200 [00:52<01:52,  1.19it/s]

[I 2025-11-10 14:13:37,407] Trial 65 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1608270408595798, 'n_estimators': 842, 'subsample': 0.8935098902401029, 'colsample_bytree': 0.8044665726468611, 'min_child_weight': 8, 'gamma': 0.3954227025105159, 'reg_alpha': 2.8860506571152208e-05, 'reg_lambda': 2.4524757222070056e-07, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  34%|███▎      | 67/200 [00:53<02:18,  1.04s/it]

[I 2025-11-10 14:13:38,917] Trial 66 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.17535127418979365, 'n_estimators': 844, 'subsample': 0.8732630405968573, 'colsample_bytree': 0.7971847913633259, 'min_child_weight': 8, 'gamma': 0.7688990190361955, 'reg_alpha': 0.00012007990726033518, 'reg_lambda': 0.0001422485349824669, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  34%|███▍      | 68/200 [00:54<01:59,  1.10it/s]

[I 2025-11-10 14:13:39,511] Trial 67 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.18175572767405276, 'n_estimators': 845, 'subsample': 0.8320864344985064, 'colsample_bytree': 0.7765541805703299, 'min_child_weight': 8, 'gamma': 0.43906035548542266, 'reg_alpha': 2.8318538829822587e-05, 'reg_lambda': 1.2992638342444618e-06, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  34%|███▍      | 69/200 [00:55<01:53,  1.15it/s]

[I 2025-11-10 14:13:40,290] Trial 68 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.17476489610372675, 'n_estimators': 840, 'subsample': 0.8705620328028647, 'colsample_bytree': 0.7375718132872813, 'min_child_weight': 8, 'gamma': 0.7807648800867205, 'reg_alpha': 2.0290885343325416e-05, 'reg_lambda': 2.8381831452166936e-07, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  35%|███▌      | 70/200 [00:55<01:30,  1.43it/s]

[I 2025-11-10 14:13:40,592] Trial 69 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1767395035097161, 'n_estimators': 667, 'subsample': 0.8201816914214021, 'colsample_bytree': 0.5912470580981394, 'min_child_weight': 9, 'gamma': 1.0259812354179176, 'reg_alpha': 0.0001771722779906445, 'reg_lambda': 1.6314001719044898e-06, 'max_delta_step': 5}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  36%|███▌      | 71/200 [00:57<01:54,  1.12it/s]

[I 2025-11-10 14:13:41,929] Trial 73 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.12916918798159707, 'n_estimators': 267, 'subsample': 0.5642240494292443, 'colsample_bytree': 0.6830405869341079, 'min_child_weight': 9, 'gamma': 1.566282257313452, 'reg_alpha': 0.00047469223595547833, 'reg_lambda': 2.03342642496073e-08, 'max_delta_step': 10}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  36%|███▌      | 72/200 [00:57<01:34,  1.36it/s]

[I 2025-11-10 14:13:42,308] Trial 70 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.2880362855069376, 'n_estimators': 668, 'subsample': 0.5031504698582899, 'colsample_bytree': 0.5888869726250675, 'min_child_weight': 9, 'gamma': 1.5120887828382519, 'reg_alpha': 0.0005561782877340876, 'reg_lambda': 2.467471888549903e-06, 'max_delta_step': 10}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  36%|███▋      | 73/200 [00:57<01:24,  1.49it/s]

[I 2025-11-10 14:13:42,821] Trial 71 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.12265165551003156, 'n_estimators': 666, 'subsample': 0.6369116049717708, 'colsample_bytree': 0.7346368170551293, 'min_child_weight': 9, 'gamma': 4.984254891368366, 'reg_alpha': 0.0004954043747947534, 'reg_lambda': 3.0978579457555895e-07, 'max_delta_step': 10}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  38%|███▊      | 75/200 [00:58<00:56,  2.20it/s]

[I 2025-11-10 14:13:43,218] Trial 75 pruned.
[I 2025-11-10 14:13:43,366] Trial 74 pruned.

Best trial: 7. Best value: 0.50117:  38%|███▊      | 76/200 [00:58<00:58,  2.10it/s]

[I 2025-11-10 14:13:43,893] Trial 76 pruned.

Best trial: 7. Best value: 0.50117:  38%|███▊      | 77/200 [01:00<01:49,  1.12it/s]

[I 2025-11-10 14:13:45,757] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03427978892065597, 'n_estimators': 490, 'subsample': 0.7634498931902973, 'colsample_bytree': 0.7096191346078669, 'min_child_weight': 7, 'gamma': 2.6511672158822917, 'reg_alpha': 1.2841640508235775e-06, 'reg_lambda': 0.5103156384064975, 'max_delta_step': 2}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  39%|███▉      | 78/200 [01:01<01:49,  1.11it/s]

[I 2025-11-10 14:13:46,663] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.05906888868862123, 'n_estimators': 503, 'subsample': 0.7328860057207257, 'colsample_bytree': 0.8530389190080179, 'min_child_weight': 7, 'gamma': 0.6642140584462694, 'reg_alpha': 0.001600610592232386, 'reg_lambda': 0.0005498155273026412, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  40%|███▉      | 79/200 [01:02<01:39,  1.22it/s]

[I 2025-11-10 14:13:47,308] Trial 72 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.015826544658715025, 'n_estimators': 1454, 'subsample': 0.8032339899060714, 'colsample_bytree': 0.6763201065415605, 'min_child_weight': 9, 'gamma': 2.654457309092887, 'reg_alpha': 0.0017870079039420891, 'reg_lambda': 1.1396529647821738e-08, 'max_delta_step': 10}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  40%|████      | 80/200 [01:02<01:30,  1.33it/s]

[I 2025-11-10 14:13:47,901] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.016170161308120948, 'n_estimators': 948, 'subsample': 0.7404219652911603, 'colsample_bytree': 0.5022161071652506, 'min_child_weight': 7, 'gamma': 2.495401705714321, 'reg_alpha': 1.4219096430537276e-08, 'reg_lambda': 0.0005764140613286608, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  40%|████      | 81/200 [01:06<03:02,  1.54s/it]

[I 2025-11-10 14:13:51,270] Trial 80 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.01612986380179669, 'n_estimators': 1194, 'subsample': 0.596086793636786, 'colsample_bytree': 0.7670017761787224, 'min_child_weight': 5, 'gamma': 0.6743914342102244, 'reg_alpha': 0.010756190769620899, 'reg_lambda': 1.2251308942395555e-05, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  41%|████      | 82/200 [01:07<02:31,  1.28s/it]

[I 2025-11-10 14:13:51,940] Trial 81 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.016014874392960912, 'n_estimators': 1166, 'subsample': 0.6940835399790259, 'colsample_bytree': 0.7663886390077915, 'min_child_weight': 5, 'gamma': 1.9658265439355365, 'reg_alpha': 2.2299285113736032e-07, 'reg_lambda': 1.1408542527759152e-05, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  42%|████▏     | 83/200 [01:07<01:55,  1.01it/s]

[I 2025-11-10 14:13:52,251] Trial 82 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.022029886689680436, 'n_estimators': 1085, 'subsample': 0.7037760572736927, 'colsample_bytree': 0.7676504495540665, 'min_child_weight': 6, 'gamma': 1.229315394115591, 'reg_alpha': 0.011361639369443694, 'reg_lambda': 1.4442851271876756e-05, 'max_delta_step': 3}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  42%|████▏     | 84/200 [01:08<01:53,  1.02it/s]

[I 2025-11-10 14:13:53,218] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.021806918284684455, 'n_estimators': 1137, 'subsample': 0.5983910879013876, 'colsample_bytree': 0.7906802137568364, 'min_child_weight': 5, 'gamma': 1.95372064658246, 'reg_alpha': 1.3912165861716392, 'reg_lambda': 1.236041463674836e-07, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  42%|████▎     | 85/200 [01:10<02:49,  1.48s/it]

[I 2025-11-10 14:13:55,851] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02059488274100759, 'n_estimators': 809, 'subsample': 0.660551335888756, 'colsample_bytree': 0.9824327930439922, 'min_child_weight': 6, 'gamma': 0.02499420349786215, 'reg_alpha': 5.4822424954251816e-08, 'reg_lambda': 1.376537769565403e-07, 'max_delta_step': 9}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  43%|████▎     | 86/200 [01:11<02:04,  1.10s/it]

[I 2025-11-10 14:13:56,064] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02091430920553799, 'n_estimators': 1001, 'subsample': 0.7034824419362542, 'colsample_bytree': 0.9982628263659027, 'min_child_weight': 6, 'gamma': 0.015084093644830234, 'reg_alpha': 1.241926525562266e-07, 'reg_lambda': 0.004783657487692515, 'max_delta_step': 9}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  44%|████▎     | 87/200 [01:12<02:01,  1.07s/it]

[I 2025-11-10 14:13:57,076] Trial 87 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.012363903569944665, 'n_estimators': 793, 'subsample': 0.750977204415857, 'colsample_bytree': 0.9963461957003027, 'min_child_weight': 6, 'gamma': 0.04311080716280663, 'reg_alpha': 4.881054359258138e-08, 'reg_lambda': 0.006146376567990505, 'max_delta_step': 9}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  44%|████▍     | 88/200 [01:12<01:33,  1.20it/s]

[I 2025-11-10 14:13:57,350] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.08323439417735724, 'n_estimators': 1047, 'subsample': 0.6667479806458965, 'colsample_bytree': 0.9783219900192447, 'min_child_weight': 5, 'gamma': 0.2557993074215632, 'reg_alpha': 5.612905107198219e-08, 'reg_lambda': 1.1400114972845007e-07, 'max_delta_step': 9}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  44%|████▍     | 89/200 [01:13<01:26,  1.29it/s]

[I 2025-11-10 14:13:58,000] Trial 90 pruned.

Best trial: 7. Best value: 0.50117:  45%|████▌     | 90/200 [01:13<01:10,  1.55it/s]

[I 2025-11-10 14:13:58,334] Trial 91 pruned.

Best trial: 7. Best value: 0.50117:  46%|████▌     | 91/200 [01:15<01:50,  1.02s/it]

[I 2025-11-10 14:14:00,222] Trial 88 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.011593606181150625, 'n_estimators': 896, 'subsample': 0.5171884960189518, 'colsample_bytree': 0.9133158813753863, 'min_child_weight': 4, 'gamma': 2.2538377733130464, 'reg_alpha': 1.0668448760968506e-08, 'reg_lambda': 2.4254920273687154e-08, 'max_delta_step': 5}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:14:00,241] Trial 89 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07777135633568043, 'n_estimators': 874, 'subsample': 0.5685280123030475, 'colsample_bytree': 0.8221725493301703, 'min_child_weight': 4, 'gamma': 0.18921300458733775, 'reg_alpha': 0.0001015132247129734, 'reg_lambda': 3.781724746437595e-05, 'max_delta_step': 5}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  46%|████▋     | 93/200 [01:16<01:23,  1.29it/s]

[I 2025-11-10 14:14:01,217] Trial 94 pruned.

Best trial: 7. Best value: 0.50117:  47%|████▋     | 94/200 [01:17<01:46,  1.01s/it]

[I 2025-11-10 14:14:02,916] Trial 93 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01348244113606024, 'n_estimators': 987, 'subsample': 0.5681229512137983, 'colsample_bytree': 0.6207483079570455, 'min_child_weight': 10, 'gamma': 3.017160792826349, 'reg_alpha': 1.8932268207636775e-06, 'reg_lambda': 1.1853989624450008e-06, 'max_delta_step': 4}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  48%|████▊     | 95/200 [01:19<01:48,  1.03s/it]

[I 2025-11-10 14:14:04,016] Trial 95 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.10695538392565153, 'n_estimators': 756, 'subsample': 0.7842216640481676, 'colsample_bytree': 0.9630173720091594, 'min_child_weight': 5, 'gamma': 0.5312685550750804, 'reg_alpha': 2.0501122885095083e-06, 'reg_lambda': 4.977574474835912e-08, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:14:04,016] Trial 92 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.10917579617707038, 'n_estimators': 1316, 'subsample': 0.7827810092631149, 'colsample_bytree': 0.6194062062711291, 'min_child_weight': 10, 'gamma': 2.188688949548555, 'reg_alpha': 5.773971069764085e-06, 'reg_lambda': 6.089473085477013e-08, 'max_delta_step': 5}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  48%|████▊     | 97/200 [01:20<01:21,  1.27it/s]

[I 2025-11-10 14:14:04,943] Trial 98 pruned.

Best trial: 7. Best value: 0.50117:  49%|████▉     | 98/200 [01:21<01:35,  1.07it/s]

[I 2025-11-10 14:14:06,371] Trial 97 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1011909581864256, 'n_estimators': 712, 'subsample': 0.7826744012632416, 'colsample_bytree': 0.9533694009395546, 'min_child_weight': 7, 'gamma': 0.5544500025239425, 'reg_alpha': 1.6611966970239864e-08, 'reg_lambda': 1.574486829807823e-08, 'max_delta_step': 6}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  50%|████▉     | 99/200 [01:22<01:41,  1.01s/it]

[I 2025-11-10 14:14:07,574] Trial 96 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.11055244806488339, 'n_estimators': 1309, 'subsample': 0.7895159469081452, 'colsample_bytree': 0.9572663119042077, 'min_child_weight': 10, 'gamma': 0.6466909732292947, 'reg_alpha': 1.6478164875303985e-08, 'reg_lambda': 1.1546972801715596e-06, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  50%|█████     | 100/200 [01:22<01:22,  1.21it/s]

[I 2025-11-10 14:14:07,905] Trial 99 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.037599990902383515, 'n_estimators': 731, 'subsample': 0.8778925794709505, 'colsample_bytree': 0.9732462662935798, 'min_child_weight': 8, 'gamma': 2.7940778703202405, 'reg_alpha': 1.4720585682155946e-05, 'reg_lambda': 4.0165313025889893e-07, 'max_delta_step': 6}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  50%|█████     | 101/200 [01:23<01:25,  1.16it/s]

[I 2025-11-10 14:14:08,843] Trial 100 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.049206149892314435, 'n_estimators': 820, 'subsample': 0.8863907415095481, 'colsample_bytree': 0.5934324527010463, 'min_child_weight': 8, 'gamma': 0.8659239117372042, 'reg_alpha': 1.6988229262554557e-07, 'reg_lambda': 1.7719093041209124e-08, 'max_delta_step': 6}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  51%|█████     | 102/200 [01:26<01:57,  1.20s/it]

[I 2025-11-10 14:14:10,918] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.06372189122302283, 'n_estimators': 576, 'subsample': 0.861451429790144, 'colsample_bytree': 0.7049185776508048, 'min_child_weight': 9, 'gamma': 4.484902117418064, 'reg_alpha': 1.0220493953094346e-07, 'reg_lambda': 0.015244574964822162, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:14:10,956] Trial 101 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.032011647194411706, 'n_estimators': 928, 'subsample': 0.742151086596404, 'colsample_bytree': 0.6620236490884176, 'min_child_weight': 9, 'gamma': 4.363151494217525, 'reg_alpha': 0.07649039972660086, 'reg_lambda': 1.7523326949724036e-07, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  52%|█████▏    | 104/200 [01:26<01:08,  1.40it/s]

[I 2025-11-10 14:14:11,138] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.049050819603541615, 'n_estimators': 642, 'subsample': 0.8804787602784468, 'colsample_bytree': 0.9719395932828595, 'min_child_weight': 9, 'gamma': 0.3425619751221757, 'reg_alpha': 1.4493920369311227e-05, 'reg_lambda': 4.0533711942155605e-07, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  52%|█████▎    | 105/200 [01:26<01:08,  1.39it/s]

[I 2025-11-10 14:14:11,877] Trial 104 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05621320147182474, 'n_estimators': 583, 'subsample': 0.7451368260722627, 'colsample_bytree': 0.8828933580326153, 'min_child_weight': 5, 'gamma': 0.3426475108265675, 'reg_alpha': 3.9552231819325176e-07, 'reg_lambda': 0.0013671610252322486, 'max_delta_step': 8}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  53%|█████▎    | 106/200 [01:28<01:18,  1.19it/s]

[I 2025-11-10 14:14:13,057] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05510702619243062, 'n_estimators': 394, 'subsample': 0.7665815808447451, 'colsample_bytree': 0.8822137184813414, 'min_child_weight': 5, 'gamma': 0.33887102161760124, 'reg_alpha': 1.09088833052228e-08, 'reg_lambda': 1.0376608375840839e-08, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  54%|█████▎    | 107/200 [01:28<01:06,  1.39it/s]

[I 2025-11-10 14:14:13,449] Trial 108 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.024266136228638897, 'n_estimators': 302, 'subsample': 0.7614244968804419, 'colsample_bytree': 0.5444175299320156, 'min_child_weight': 6, 'gamma': 0.11056036177647965, 'reg_alpha': 3.5441777682165024e-08, 'reg_lambda': 3.917270398859699e-08, 'max_delta_step': 8}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  55%|█████▍    | 109/200 [01:29<00:45,  2.01it/s]

[I 2025-11-10 14:14:13,923] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07687327874248504, 'n_estimators': 527, 'subsample': 0.7407139563125223, 'colsample_bytree': 0.9465038585004862, 'min_child_weight': 5, 'gamma': 2.4247234058330474, 'reg_alpha': 3.18998747653435e-07, 'reg_lambda': 1.6585558627733363e-07, 'max_delta_step': 8}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:14:14,032] Trial 107 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07515094689201297, 'n_estimators': 522, 'subsample': 0.7625005327308223, 'colsample_bytree': 0.9866101100611953, 'min_child_weight': 5, 'gamma': 0.1457812474519516, 'reg_alpha': 2.9816065062734446e-07, 'reg_lambda': 4.7394859007668796e-05, 'max_delta_step': 8}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  55%|█████▌    | 110/200 [01:30<00:56,  1.60it/s]

[I 2025-11-10 14:14:14,968] Trial 112 pruned.

Best trial: 7. Best value: 0.50117:  56%|█████▌    | 111/200 [01:31<01:05,  1.36it/s]

[I 2025-11-10 14:14:15,977] Trial 109 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.024350907795718895, 'n_estimators': 516, 'subsample': 0.7280916406894213, 'colsample_bytree': 0.5695596213702134, 'min_child_weight': 6, 'gamma': 0.07823544090067291, 'reg_alpha': 9.652403885345299, 'reg_lambda': 4.1048341032597683e-08, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  56%|█████▌    | 112/200 [01:31<00:59,  1.49it/s]

[I 2025-11-10 14:14:16,494] Trial 111 finished with value: 0.45432748538011697 and parameters: {'max_depth': 6, 'learning_rate': 0.23071423672714836, 'n_estimators': 467, 'subsample': 0.815196297001591, 'colsample_bytree': 0.5748012203508209, 'min_child_weight': 4, 'gamma': 4.795007391811523, 'reg_alpha': 7.635508748965033e-05, 'reg_lambda': 4.636813515474468e-05, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  56%|█████▋    | 113/200 [01:32<00:54,  1.61it/s]

[I 2025-11-10 14:14:17,004] Trial 110 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2737166945077055, 'n_estimators': 541, 'subsample': 0.7129986036066377, 'colsample_bytree': 0.9467401106432917, 'min_child_weight': 6, 'gamma': 1.6777948863047225, 'reg_alpha': 8.561241671596714e-07, 'reg_lambda': 8.935548292263851e-08, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  57%|█████▋    | 114/200 [01:33<01:15,  1.13it/s]

[I 2025-11-10 14:14:18,494] Trial 114 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.08543424976912395, 'n_estimators': 465, 'subsample': 0.7163788072700226, 'colsample_bytree': 0.9478109767024403, 'min_child_weight': 5, 'gamma': 2.9466531051175013, 'reg_alpha': 0.031472930472591885, 'reg_lambda': 8.331869383525758e-08, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  57%|█████▊    | 115/200 [01:33<01:01,  1.39it/s]

[I 2025-11-10 14:14:18,829] Trial 113 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.2711526419063287, 'n_estimators': 782, 'subsample': 0.7294987263513282, 'colsample_bytree': 0.5743479431002538, 'min_child_weight': 6, 'gamma': 3.1286072356664874, 'reg_alpha': 8.439035458630136e-07, 'reg_lambda': 0.04867516572525878, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  58%|█████▊    | 116/200 [01:34<00:52,  1.61it/s]

[I 2025-11-10 14:14:19,220] Trial 116 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.1430973291728068, 'n_estimators': 429, 'subsample': 0.7530585637871433, 'colsample_bytree': 0.9247907343676901, 'min_child_weight': 5, 'gamma': 2.5482849842029904, 'reg_alpha': 0.02272235478972338, 'reg_lambda': 0.04815780462635703, 'max_delta_step': 6}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  58%|█████▊    | 117/200 [01:35<01:05,  1.26it/s]

[I 2025-11-10 14:14:20,412] Trial 115 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.08673772565286571, 'n_estimators': 773, 'subsample': 0.7097283373919294, 'colsample_bytree': 0.9284241810993269, 'min_child_weight': 5, 'gamma': 3.305510506735203, 'reg_alpha': 0.0008743343571983301, 'reg_lambda': 7.85955472816712e-08, 'max_delta_step': 6}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  59%|█████▉    | 118/200 [01:36<01:15,  1.09it/s]

[I 2025-11-10 14:14:21,618] Trial 117 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.04054880587581354, 'n_estimators': 616, 'subsample': 0.5840816571476474, 'colsample_bytree': 0.9323344037996976, 'min_child_weight': 5, 'gamma': 3.784211921538438, 'reg_alpha': 0.5187502891207468, 'reg_lambda': 1.717599919161104e-08, 'max_delta_step': 6}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  60%|█████▉    | 119/200 [01:37<01:00,  1.35it/s]

[I 2025-11-10 14:14:21,955] Trial 118 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09407923045862032, 'n_estimators': 624, 'subsample': 0.8447202464669694, 'colsample_bytree': 0.8572713434752219, 'min_child_weight': 5, 'gamma': 2.5134663192164943, 'reg_alpha': 1.6406397416597736, 'reg_lambda': 1.6728982749882766e-08, 'max_delta_step': 6}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  60%|██████    | 120/200 [01:37<00:50,  1.57it/s]

[I 2025-11-10 14:14:22,340] Trial 119 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.09936583765402232, 'n_estimators': 613, 'subsample': 0.6251987425137906, 'colsample_bytree': 0.8497502293221337, 'min_child_weight': 7, 'gamma': 1.3164197993788256, 'reg_alpha': 2.95309345051814, 'reg_lambda': 2.9162059478691722e-08, 'max_delta_step': 4}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  60%|██████    | 121/200 [01:38<01:12,  1.09it/s]

[I 2025-11-10 14:14:23,921] Trial 120 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.0952926855642886, 'n_estimators': 695, 'subsample': 0.6927994321285245, 'colsample_bytree': 0.8542968450993843, 'min_child_weight': 7, 'gamma': 3.896559108915824, 'reg_alpha': 0.002285473403412379, 'reg_lambda': 1.3086112432211328e-08, 'max_delta_step': 4}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  62%|██████▏   | 123/200 [01:40<01:06,  1.15it/s]

[I 2025-11-10 14:14:25,757] Trial 123 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.07269060575794434, 'n_estimators': 691, 'subsample': 0.6884909559848291, 'colsample_bytree': 0.9884266398068728, 'min_child_weight': 8, 'gamma': 3.963572506971334, 'reg_alpha': 2.2553237480294844e-05, 'reg_lambda': 0.0026278552822695694, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:14:25,872] Trial 121 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.014057677775099746, 'n_estimators': 818, 'subsample': 0.6667574716987051, 'colsample_bytree': 0.968599521977831, 'min_child_weight': 7, 'gamma': 3.1774223411591924, 'reg_alpha': 0.003035758771883536, 'reg_lambda': 2.955098970727933e-06, 'max_delta_step': 4}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  62%|██████▏   | 124/200 [01:41<01:09,  1.09it/s]

[I 2025-11-10 14:14:26,899] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.07431975849609507, 'n_estimators': 564, 'subsample': 0.671373684191034, 'colsample_bytree': 0.9681020138195727, 'min_child_weight': 6, 'gamma': 1.098273321808645, 'reg_alpha': 0.1077929600303123, 'reg_lambda': 3.6509706533284203, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  63%|██████▎   | 126/200 [01:43<01:05,  1.14it/s]

[I 2025-11-10 14:14:28,704] Trial 122 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.09948690412758704, 'n_estimators': 1392, 'subsample': 0.6308286319608476, 'colsample_bytree': 0.7255764088027363, 'min_child_weight': 7, 'gamma': 4.083889181098527, 'reg_alpha': 0.002332763435460478, 'reg_lambda': 0.29716383125023293, 'max_delta_step': 4}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:14:28,880] Trial 126 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.08169177214806607, 'n_estimators': 566, 'subsample': 0.5257722431843396, 'colsample_bytree': 0.8179422653914927, 'min_child_weight': 6, 'gamma': 3.4502952427211446, 'reg_alpha': 0.006636765640883406, 'reg_lambda': 0.341563374140305, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  64%|██████▎   | 127/200 [01:44<01:03,  1.16it/s]

[I 2025-11-10 14:14:29,712] Trial 127 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06275940386732907, 'n_estimators': 489, 'subsample': 0.7727021167130872, 'colsample_bytree': 0.8886792496690146, 'min_child_weight': 6, 'gamma': 2.7396039824038803, 'reg_alpha': 0.008695039027848232, 'reg_lambda': 2.2568096063097886e-07, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  64%|██████▍   | 128/200 [01:45<01:02,  1.16it/s]

[I 2025-11-10 14:14:30,557] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.08257031281090128, 'n_estimators': 935, 'subsample': 0.5159417076717514, 'colsample_bytree': 0.8764979141243737, 'min_child_weight': 6, 'gamma': 3.4693653072747646, 'reg_alpha': 0.006479844606462151, 'reg_lambda': 2.4444328883718815e-06, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  64%|██████▍   | 129/200 [01:46<00:54,  1.29it/s]

[I 2025-11-10 14:14:31,134] Trial 128 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06291196391514337, 'n_estimators': 486, 'subsample': 0.5575716705072777, 'colsample_bytree': 0.8838055871091532, 'min_child_weight': 6, 'gamma': 2.9030199854829264, 'reg_alpha': 0.005827781103816188, 'reg_lambda': 9.569245253905644e-05, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  65%|██████▌   | 130/200 [01:46<00:43,  1.62it/s]

[I 2025-11-10 14:14:31,382] Trial 129 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06305846065874678, 'n_estimators': 484, 'subsample': 0.5591384915497808, 'colsample_bytree': 0.8844222855627811, 'min_child_weight': 4, 'gamma': 2.0800315601840613, 'reg_alpha': 0.019087180709073122, 'reg_lambda': 3.034921627473294e-08, 'max_delta_step': 5}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  66%|██████▌   | 131/200 [01:47<00:55,  1.25it/s]

[I 2025-11-10 14:14:32,605] Trial 131 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1277166833173774, 'n_estimators': 397, 'subsample': 0.500483262906819, 'colsample_bytree': 0.5998849656372345, 'min_child_weight': 4, 'gamma': 3.1023423348722687, 'reg_alpha': 0.2100440360871108, 'reg_lambda': 2.4446593069426688e-08, 'max_delta_step': 2}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  66%|██████▌   | 132/200 [01:48<00:49,  1.38it/s]

[I 2025-11-10 14:14:33,152] Trial 132 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.11889880355459574, 'n_estimators': 361, 'subsample': 0.5312339330141939, 'colsample_bytree': 0.8666308864060366, 'min_child_weight': 4, 'gamma': 3.128227542619151, 'reg_alpha': 0.01542055422414204, 'reg_lambda': 3.2555875839567285e-08, 'max_delta_step': 5}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  66%|██████▋   | 133/200 [01:48<00:39,  1.68it/s]

[I 2025-11-10 14:14:33,441] Trial 134 pruned.

Best trial: 7. Best value: 0.50117:  67%|██████▋   | 134/200 [01:49<00:43,  1.53it/s]

[I 2025-11-10 14:14:34,233] Trial 135 pruned.

Best trial: 7. Best value: 0.50117:  68%|██████▊   | 135/200 [01:49<00:35,  1.83it/s]

[I 2025-11-10 14:14:34,537] Trial 130 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.011000234448031021, 'n_estimators': 930, 'subsample': 0.5461294603176726, 'colsample_bytree': 0.8384963627141891, 'min_child_weight': 4, 'gamma': 3.663084163200445, 'reg_alpha': 0.016162829306734416, 'reg_lambda': 3.25512081238647e-08, 'max_delta_step': 8}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  68%|██████▊   | 136/200 [01:50<00:36,  1.77it/s]

[I 2025-11-10 14:14:35,140] Trial 133 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.011099610405179072, 'n_estimators': 750, 'subsample': 0.539385270596228, 'colsample_bytree': 0.5999983504350637, 'min_child_weight': 5, 'gamma': 3.058630759014375, 'reg_alpha': 4.5323724411791444e-05, 'reg_lambda': 8.167471814101257e-06, 'max_delta_step': 8}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  68%|██████▊   | 137/200 [01:52<00:58,  1.07it/s]

[I 2025-11-10 14:14:36,938] Trial 137 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.19242557744102967, 'n_estimators': 540, 'subsample': 0.6444109411350721, 'colsample_bytree': 0.8990888944358322, 'min_child_weight': 10, 'gamma': 2.852266864265228, 'reg_alpha': 3.168557559953572e-08, 'reg_lambda': 5.8182800816633346e-08, 'max_delta_step': 6}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  69%|██████▉   | 138/200 [01:52<00:48,  1.28it/s]

[I 2025-11-10 14:14:37,365] Trial 138 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.13901725911029705, 'n_estimators': 546, 'subsample': 0.9692477357685941, 'colsample_bytree': 0.9016652130978283, 'min_child_weight': 6, 'gamma': 2.8534391766547422, 'reg_alpha': 3.8201923939227413e-08, 'reg_lambda': 1.9350883194375062e-05, 'max_delta_step': 6}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  70%|██████▉   | 139/200 [01:53<00:50,  1.21it/s]

[I 2025-11-10 14:14:38,299] Trial 136 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.14456843860558197, 'n_estimators': 977, 'subsample': 0.974144757461819, 'colsample_bytree': 0.9012687621541787, 'min_child_weight': 10, 'gamma': 3.694517469608337, 'reg_alpha': 8.624546209903173e-08, 'reg_lambda': 7.958097153409359e-06, 'max_delta_step': 6}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  70%|███████   | 140/200 [01:54<01:03,  1.06s/it]

[I 2025-11-10 14:14:39,916] Trial 140 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0900554416165741, 'n_estimators': 596, 'subsample': 0.9164725405634891, 'colsample_bytree': 0.9072785157293661, 'min_child_weight': 9, 'gamma': 0.26903584074724163, 'reg_alpha': 0.056641040992879144, 'reg_lambda': 0.0006898284006398209, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  71%|███████   | 142/200 [01:55<00:37,  1.56it/s]

[I 2025-11-10 14:14:40,314] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10571181822866621, 'n_estimators': 592, 'subsample': 0.9239573147692335, 'colsample_bytree': 0.9059349389376693, 'min_child_weight': 9, 'gamma': 2.4003059297448077, 'reg_alpha': 5.072931853067627e-06, 'reg_lambda': 1.0432759872743801e-08, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:14:40,433] Trial 142 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09037534012479166, 'n_estimators': 438, 'subsample': 0.798078272974446, 'colsample_bytree': 0.6472211076968549, 'min_child_weight': 9, 'gamma': 0.24667857893740716, 'reg_alpha': 9.609543034055547e-06, 'reg_lambda': 2.133023171739027e-07, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  72%|███████▏  | 143/200 [01:56<00:41,  1.36it/s]

[I 2025-11-10 14:14:41,391] Trial 139 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1868758817373029, 'n_estimators': 1240, 'subsample': 0.9349609820575873, 'colsample_bytree': 0.9998878417446868, 'min_child_weight': 10, 'gamma': 1.9091858600830418, 'reg_alpha': 3.596135988012968e-08, 'reg_lambda': 0.000750544641750372, 'max_delta_step': 6}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  72%|███████▏  | 144/200 [02:00<01:30,  1.62s/it]

[I 2025-11-10 14:14:45,066] Trial 143 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06753861563711402, 'n_estimators': 1083, 'subsample': 0.8020359883655195, 'colsample_bytree': 0.6508455843434086, 'min_child_weight': 6, 'gamma': 1.901428751443723, 'reg_alpha': 0.00013114553268623675, 'reg_lambda': 1.165759324300276e-07, 'max_delta_step': 5}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  73%|███████▎  | 146/200 [02:01<00:58,  1.08s/it]

[I 2025-11-10 14:14:46,246] Trial 146 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.043838023426384105, 'n_estimators': 1031, 'subsample': 0.9830950687217094, 'colsample_bytree': 0.6683001044146223, 'min_child_weight': 8, 'gamma': 3.38550690131554, 'reg_alpha': 0.02911247398345849, 'reg_lambda': 0.011097270850006953, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:14:46,374] Trial 145 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.038252148667373566, 'n_estimators': 1260, 'subsample': 0.9955741073980816, 'colsample_bytree': 0.6718704228890084, 'min_child_weight': 8, 'gamma': 3.3587666323635172, 'reg_alpha': 0.02695977814392142, 'reg_lambda': 3.2107838458687763e-05, 'max_delta_step': 3}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:14:46,414] Trial 144 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.04376955400898771, 'n_estimators': 1267, 'subsample': 0.94605466600556, 'colsample_bytree': 0.6447480014848724, 'min_child_weight': 8, 'gamma': 1.9072775119414813, 'reg_alpha': 0.010905316125199722, 'reg_lambda': 0.010303497061342854, 'max_delta_step': 3}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  74%|███████▍  | 148/200 [02:04<01:04,  1.25s/it]

[I 2025-11-10 14:14:49,269] Trial 147 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.2072785934853339, 'n_estimators': 858, 'subsample': 0.9501124329919992, 'colsample_bytree': 0.6715508373853293, 'min_child_weight': 8, 'gamma': 3.2999582174777666, 'reg_alpha': 0.03898076927469018, 'reg_lambda': 5.82357483255349e-07, 'max_delta_step': 3}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  74%|███████▍  | 149/200 [02:05<01:00,  1.19s/it]

[I 2025-11-10 14:14:50,258] Trial 148 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.21182992849608445, 'n_estimators': 805, 'subsample': 0.7325473529602557, 'colsample_bytree': 0.6785266990663067, 'min_child_weight': 7, 'gamma': 2.7494120141675613, 'reg_alpha': 0.041952581525809225, 'reg_lambda': 3.333201693197171e-05, 'max_delta_step': 2}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  75%|███████▌  | 150/200 [02:06<01:04,  1.29s/it]

[I 2025-11-10 14:14:51,848] Trial 150 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03369822488413, 'n_estimators': 1133, 'subsample': 0.7524375311762418, 'colsample_bytree': 0.6829339935720529, 'min_child_weight': 7, 'gamma': 2.745588080968719, 'reg_alpha': 1.6796608700573786e-07, 'reg_lambda': 1.9916369408211564e-05, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  76%|███████▌  | 151/200 [02:07<00:49,  1.01s/it]

[I 2025-11-10 14:14:52,112] Trial 149 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.21440061090472184, 'n_estimators': 1208, 'subsample': 0.9509041111518028, 'colsample_bytree': 0.6289481924146905, 'min_child_weight': 7, 'gamma': 0.0035996045142530075, 'reg_alpha': 0.0525303129495484, 'reg_lambda': 0.12207161025947942, 'max_delta_step': 2}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  76%|███████▌  | 152/200 [02:08<00:48,  1.00s/it]

[I 2025-11-10 14:14:53,092] Trial 151 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.026976544120586688, 'n_estimators': 793, 'subsample': 0.7561637641408425, 'colsample_bytree': 0.6844071901788326, 'min_child_weight': 7, 'gamma': 2.991203735120067, 'reg_alpha': 0.05781788655578024, 'reg_lambda': 0.14262203981378274, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  76%|███████▋  | 153/200 [02:08<00:43,  1.09it/s]

[I 2025-11-10 14:14:53,788] Trial 154 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.040920984317480376, 'n_estimators': 334, 'subsample': 0.605660355111113, 'colsample_bytree': 0.6096803387307635, 'min_child_weight': 5, 'gamma': 1.6904261257873814, 'reg_alpha': 8.092627017122114e-06, 'reg_lambda': 1.2490726609716948e-05, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  77%|███████▋  | 154/200 [02:09<00:42,  1.08it/s]

[I 2025-11-10 14:14:54,750] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.051980336803114875, 'n_estimators': 309, 'subsample': 0.5104331877003143, 'colsample_bytree': 0.8685587644655046, 'min_child_weight': 5, 'gamma': 1.6834417372329133, 'reg_alpha': 1.8734233947471865e-06, 'reg_lambda': 6.777095762993612e-05, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  78%|███████▊  | 155/200 [02:10<00:43,  1.03it/s]

[I 2025-11-10 14:14:55,811] Trial 152 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03320045714707785, 'n_estimators': 1172, 'subsample': 0.753855076379054, 'colsample_bytree': 0.6870820623540256, 'min_child_weight': 5, 'gamma': 0.0909613567160062, 'reg_alpha': 0.19538470984690148, 'reg_lambda': 1.7326286714049542e-06, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  78%|███████▊  | 156/200 [02:12<00:47,  1.09s/it]

[I 2025-11-10 14:14:57,190] Trial 158 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.03936324474540454, 'n_estimators': 267, 'subsample': 0.8543847167299746, 'colsample_bytree': 0.8734966745256413, 'min_child_weight': 6, 'gamma': 1.4246916434895438, 'reg_alpha': 1.3993049900592752e-05, 'reg_lambda': 0.0002447960912384366, 'max_delta_step': 9}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  79%|███████▉  | 158/200 [02:12<00:27,  1.54it/s]

[I 2025-11-10 14:14:57,536] Trial 153 finished with value: 0.4666666666666667 and parameters: {'max_depth': 10, 'learning_rate': 0.051333150740064754, 'n_estimators': 1195, 'subsample': 0.854622369743819, 'colsample_bytree': 0.6351278158470971, 'min_child_weight': 5, 'gamma': 2.987226016929384, 'reg_alpha': 0.003983156346346085, 'reg_lambda': 0.00034297350289935237, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:14:57,676] Trial 159 pruned.

Best trial: 7. Best value: 0.50117:  80%|███████▉  | 159/200 [02:14<00:35,  1.15it/s]

[I 2025-11-10 14:14:59,050] Trial 161 pruned.

Best trial: 7. Best value: 0.50117:  80%|████████  | 160/200 [02:14<00:31,  1.29it/s]

[I 2025-11-10 14:14:59,617] Trial 156 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.013369197884689125, 'n_estimators': 1183, 'subsample': 0.5132027563851934, 'colsample_bytree': 0.872855330482013, 'min_child_weight': 6, 'gamma': 1.3629007954698387, 'reg_alpha': 2.2849441523298922e-06, 'reg_lambda': 8.419769335945666e-07, 'max_delta_step': 9}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  81%|████████  | 162/200 [02:15<00:20,  1.83it/s]

[I 2025-11-10 14:15:00,198] Trial 160 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.013152335480476349, 'n_estimators': 507, 'subsample': 0.5168446586208859, 'colsample_bytree': 0.7071292514207075, 'min_child_weight': 6, 'gamma': 1.075963575339886, 'reg_alpha': 2.0931216078870322e-05, 'reg_lambda': 7.121814505070127e-06, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:15:00,331] Trial 157 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.03108063443401194, 'n_estimators': 1178, 'subsample': 0.8587885421370645, 'colsample_bytree': 0.7037896754240663, 'min_child_weight': 6, 'gamma': 1.4082887530849788, 'reg_alpha': 1.3402551752847792e-05, 'reg_lambda': 4.63910246765095e-06, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  82%|████████▏ | 163/200 [02:16<00:28,  1.28it/s]

[I 2025-11-10 14:15:01,665] Trial 163 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.10314139527797014, 'n_estimators': 396, 'subsample': 0.7755877899882063, 'colsample_bytree': 0.8596531377186519, 'min_child_weight': 7, 'gamma': 1.5130916499523637, 'reg_alpha': 1.0353486740154923e-08, 'reg_lambda': 5.118547745444869e-08, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  82%|████████▏ | 164/200 [02:18<00:35,  1.01it/s]

[I 2025-11-10 14:15:03,157] Trial 162 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.013158130204807224, 'n_estimators': 832, 'subsample': 0.5766231086985408, 'colsample_bytree': 0.7048081260076074, 'min_child_weight': 6, 'gamma': 1.0794889879691474, 'reg_alpha': 5.7752253526303456e-08, 'reg_lambda': 1.749996288093461e-08, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  83%|████████▎ | 166/200 [02:20<00:33,  1.01it/s]

[I 2025-11-10 14:15:05,349] Trial 164 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.0413692111210813, 'n_estimators': 1080, 'subsample': 0.7223249925243896, 'colsample_bytree': 0.8291616010959391, 'min_child_weight': 7, 'gamma': 1.5969229786982055, 'reg_alpha': 4.135438550514192e-06, 'reg_lambda': 1.8524146742050888e-08, 'max_delta_step': 2}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:15:05,481] Trial 165 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.0367149516197857, 'n_estimators': 1107, 'subsample': 0.6549921031834012, 'colsample_bytree': 0.8116928359630118, 'min_child_weight': 7, 'gamma': 0.7970543622275873, 'reg_alpha': 3.828080490738231e-06, 'reg_lambda': 3.2946716453745694e-07, 'max_delta_step': 2}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  84%|████████▎ | 167/200 [02:21<00:34,  1.05s/it]

[I 2025-11-10 14:15:06,680] Trial 166 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.041846975304422405, 'n_estimators': 1095, 'subsample': 0.8971091175249694, 'colsample_bytree': 0.8102292380656125, 'min_child_weight': 7, 'gamma': 0.9240458960053374, 'reg_alpha': 4.111979817937409e-06, 'reg_lambda': 3.8297806276636255e-07, 'max_delta_step': 2}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  84%|████████▍ | 168/200 [02:22<00:32,  1.01s/it]

[I 2025-11-10 14:15:07,594] Trial 168 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.010099225698381252, 'n_estimators': 446, 'subsample': 0.650811012293505, 'colsample_bytree': 0.8017857872939044, 'min_child_weight': 7, 'gamma': 1.7689842290662647, 'reg_alpha': 1.5028666135999307e-06, 'reg_lambda': 3.783036451297145e-07, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  84%|████████▍ | 169/200 [02:23<00:30,  1.02it/s]

[I 2025-11-10 14:15:08,509] Trial 167 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.04127711778396429, 'n_estimators': 1103, 'subsample': 0.7008844417306602, 'colsample_bytree': 0.8286987934638438, 'min_child_weight': 7, 'gamma': 0.8130987166411114, 'reg_alpha': 3.425308562898409e-06, 'reg_lambda': 1.4391866944214063e-07, 'max_delta_step': 2}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  85%|████████▌ | 170/200 [02:25<00:33,  1.12s/it]

[I 2025-11-10 14:15:09,951] Trial 169 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.27267689595801525, 'n_estimators': 893, 'subsample': 0.7392040728287457, 'colsample_bytree': 0.7839618332988112, 'min_child_weight': 7, 'gamma': 1.8239758382157565, 'reg_alpha': 1.1263023525908501e-06, 'reg_lambda': 0.00012033956552544294, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  86%|████████▌ | 171/200 [02:26<00:34,  1.20s/it]

[I 2025-11-10 14:15:11,343] Trial 171 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.08219236104655415, 'n_estimators': 712, 'subsample': 0.6849907982904913, 'colsample_bytree': 0.7433380143052604, 'min_child_weight': 7, 'gamma': 0.14850224487727448, 'reg_alpha': 7.227843748587256e-06, 'reg_lambda': 1.6132515906320615e-07, 'max_delta_step': 3}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  86%|████████▌ | 172/200 [02:27<00:32,  1.18s/it]

[I 2025-11-10 14:15:12,463] Trial 170 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.16437003947746065, 'n_estimators': 1059, 'subsample': 0.7421048921214122, 'colsample_bytree': 0.981072403983946, 'min_child_weight': 7, 'gamma': 1.8029613764162775, 'reg_alpha': 1.5768262769141225e-06, 'reg_lambda': 1.6401949924222005e-07, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  86%|████████▋ | 173/200 [02:28<00:26,  1.02it/s]

[I 2025-11-10 14:15:12,980] Trial 172 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.12739617449839194, 'n_estimators': 878, 'subsample': 0.6787831262247328, 'colsample_bytree': 0.78120039160954, 'min_child_weight': 5, 'gamma': 1.2312627607859474, 'reg_alpha': 6.31701854111179e-06, 'reg_lambda': 8.748757050871978e-08, 'max_delta_step': 4}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  87%|████████▋ | 174/200 [02:28<00:24,  1.04it/s]

[I 2025-11-10 14:15:13,895] Trial 173 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.07975549133381071, 'n_estimators': 713, 'subsample': 0.61632222356847, 'colsample_bytree': 0.7430719297115682, 'min_child_weight': 5, 'gamma': 1.2276756225723007, 'reg_alpha': 3.476147841778819e-05, 'reg_lambda': 8.035261062105949e-08, 'max_delta_step': 3}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  88%|████████▊ | 175/200 [02:30<00:26,  1.07s/it]

[I 2025-11-10 14:15:15,219] Trial 174 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.01932703393842876, 'n_estimators': 669, 'subsample': 0.6770831543162906, 'colsample_bytree': 0.7519368570586533, 'min_child_weight': 10, 'gamma': 4.316182414764245, 'reg_alpha': 0.0003603074006120461, 'reg_lambda': 3.1659125114582162e-06, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  88%|████████▊ | 176/200 [02:31<00:27,  1.16s/it]

[I 2025-11-10 14:15:16,576] Trial 175 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.019026018674856638, 'n_estimators': 670, 'subsample': 0.6601348292876622, 'colsample_bytree': 0.9912297125855544, 'min_child_weight': 10, 'gamma': 4.61253721676782, 'reg_alpha': 0.00035309759855375655, 'reg_lambda': 1.1621801685701164e-06, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  88%|████████▊ | 177/200 [02:31<00:20,  1.13it/s]

[I 2025-11-10 14:15:16,837] Trial 176 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.017331007163887253, 'n_estimators': 667, 'subsample': 0.661271827633888, 'colsample_bytree': 0.7481433539354638, 'min_child_weight': 10, 'gamma': 4.858426348758385, 'reg_alpha': 0.000733676590731227, 'reg_lambda': 1.7584799942043076e-05, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  89%|████████▉ | 178/200 [02:34<00:28,  1.30s/it]

[I 2025-11-10 14:15:19,099] Trial 178 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.017404716318007638, 'n_estimators': 757, 'subsample': 0.6620513414273119, 'colsample_bytree': 0.7634532380735657, 'min_child_weight': 10, 'gamma': 2.0020397702824826, 'reg_alpha': 0.011046069372145317, 'reg_lambda': 9.146656103013994e-07, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  90%|████████▉ | 179/200 [02:35<00:27,  1.31s/it]

[I 2025-11-10 14:15:20,418] Trial 179 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03486114711693967, 'n_estimators': 746, 'subsample': 0.6447001575838648, 'colsample_bytree': 0.9174056174732415, 'min_child_weight': 10, 'gamma': 2.050826802564681, 'reg_alpha': 0.0006809041881803535, 'reg_lambda': 1.0508336275180064e-08, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:15:20,426] Trial 180 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09647801397084071, 'n_estimators': 744, 'subsample': 0.6455781526274177, 'colsample_bytree': 0.7610698738781438, 'min_child_weight': 8, 'gamma': 3.216075811575289, 'reg_alpha': 0.00940151715181736, 'reg_lambda': 2.577284551016442e-07, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  90%|█████████ | 181/200 [02:35<00:14,  1.29it/s]

[I 2025-11-10 14:15:20,742] Trial 177 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.03636238038897471, 'n_estimators': 1360, 'subsample': 0.6420237393656403, 'colsample_bytree': 0.7586113568871325, 'min_child_weight': 10, 'gamma': 4.145370946563761, 'reg_alpha': 2.353618580298879e-08, 'reg_lambda': 1.1774864253411732e-06, 'max_delta_step': 1}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  91%|█████████ | 182/200 [02:37<00:15,  1.13it/s]

[I 2025-11-10 14:15:21,952] Trial 184 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.046404591928374955, 'n_estimators': 237, 'subsample': 0.8234333784287939, 'colsample_bytree': 0.7195687751753134, 'min_child_weight': 9, 'gamma': 4.591487257562652, 'reg_alpha': 0.0015670448127395624, 'reg_lambda': 2.573706860542464e-06, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  92%|█████████▏| 183/200 [02:38<00:15,  1.08it/s]

[I 2025-11-10 14:15:22,989] Trial 181 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03568545577819353, 'n_estimators': 737, 'subsample': 0.6403786314613991, 'colsample_bytree': 0.9583083676175609, 'min_child_weight': 9, 'gamma': 4.153131201496599, 'reg_alpha': 0.00019501659487036185, 'reg_lambda': 1.0755202405422966, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  92%|█████████▏| 184/200 [02:39<00:18,  1.18s/it]

[I 2025-11-10 14:15:24,840] Trial 185 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.014709896534430472, 'n_estimators': 517, 'subsample': 0.6303208971707606, 'colsample_bytree': 0.9596257628391758, 'min_child_weight': 9, 'gamma': 4.893570210605968, 'reg_alpha': 0.0002507001744850977, 'reg_lambda': 1.0789770584909367e-05, 'max_delta_step': 5}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  92%|█████████▎| 185/200 [02:42<00:22,  1.49s/it]

[I 2025-11-10 14:15:27,125] Trial 186 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.02457215630744282, 'n_estimators': 780, 'subsample': 0.8109701363829109, 'colsample_bytree': 0.6951231933675756, 'min_child_weight': 10, 'gamma': 2.5928402635556473, 'reg_alpha': 0.001116552266495347, 'reg_lambda': 1.0953139854780156e-05, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  94%|█████████▎| 187/200 [02:42<00:11,  1.13it/s]

[I 2025-11-10 14:15:27,563] Trial 183 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.030088431431212058, 'n_estimators': 1336, 'subsample': 0.8243385060912186, 'colsample_bytree': 0.8485133041892368, 'min_child_weight': 9, 'gamma': 2.476562258409269, 'reg_alpha': 2.4238456952808243e-08, 'reg_lambda': 0.7640595442390608, 'max_delta_step': 5}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:15:27,717] Trial 187 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.02783630495295817, 'n_estimators': 564, 'subsample': 0.8672697862550244, 'colsample_bytree': 0.657502126392995, 'min_child_weight': 10, 'gamma': 2.3410422419369774, 'reg_alpha': 0.0030573787708204595, 'reg_lambda': 2.3838059427720444e-08, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  94%|█████████▍| 188/200 [02:43<00:08,  1.45it/s]

[I 2025-11-10 14:15:27,934] Trial 182 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.04640143228476188, 'n_estimators': 1355, 'subsample': 0.5053598092351829, 'colsample_bytree': 0.9587308149589026, 'min_child_weight': 9, 'gamma': 2.638269855271858, 'reg_alpha': 2.678312093274586e-08, 'reg_lambda': 1.2718724025349595e-05, 'max_delta_step': 8}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  94%|█████████▍| 189/200 [02:45<00:13,  1.19s/it]

[I 2025-11-10 14:15:30,306] Trial 189 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.10912817593225116, 'n_estimators': 553, 'subsample': 0.837865803792791, 'colsample_bytree': 0.6614125669452202, 'min_child_weight': 10, 'gamma': 2.357992443072198, 'reg_alpha': 0.0004594945532584952, 'reg_lambda': 3.833932803442685e-08, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  96%|█████████▌| 191/200 [02:46<00:06,  1.35it/s]

[I 2025-11-10 14:15:30,855] Trial 190 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.1148926404026954, 'n_estimators': 644, 'subsample': 0.8475340432044112, 'colsample_bytree': 0.6415952535564877, 'min_child_weight': 5, 'gamma': 4.7069266667892355, 'reg_alpha': 0.0005121688300198817, 'reg_lambda': 1.7492168232475204e-06, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.
[I 2025-11-10 14:15:31,001] Trial 191 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.011912416018838107, 'n_estimators': 632, 'subsample': 0.8422990204254692, 'colsample_bytree': 0.730239372185461, 'min_child_weight': 5, 'gamma': 4.731408583551799, 'reg_alpha': 0.0005516530941543683, 'reg_lambda': 1.6119638230493707e-06, 'max_delta_step': 7}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  96%|█████████▌| 192/200 [02:46<00:05,  1.52it/s]

[I 2025-11-10 14:15:31,447] Trial 188 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.012121417444501955, 'n_estimators': 823, 'subsample': 0.8662295443060565, 'colsample_bytree': 0.7239776385521429, 'min_child_weight': 10, 'gamma': 4.431136151895942, 'reg_alpha': 0.002942135453167389, 'reg_lambda': 1.6058930268181e-06, 'max_delta_step': 10}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  96%|█████████▋| 193/200 [02:47<00:04,  1.42it/s]

[I 2025-11-10 14:15:32,262] Trial 193 pruned.

Best trial: 7. Best value: 0.50117:  97%|█████████▋| 194/200 [02:49<00:07,  1.24s/it]

[I 2025-11-10 14:15:34,773] Trial 194 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.022011598751758114, 'n_estimators': 693, 'subsample': 0.765805731925347, 'colsample_bytree': 0.7217061463624486, 'min_child_weight': 10, 'gamma': 4.61361596288427, 'reg_alpha': 0.018641692906648136, 'reg_lambda': 5.89769985316251e-07, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  98%|█████████▊| 195/200 [02:50<00:05,  1.09s/it]

[I 2025-11-10 14:15:35,521] Trial 192 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.022322231537628055, 'n_estimators': 1020, 'subsample': 0.5243777609704532, 'colsample_bytree': 0.73056415081261, 'min_child_weight': 8, 'gamma': 4.659564293501886, 'reg_alpha': 9.338783900238608e-06, 'reg_lambda': 1.7399473391431547e-06, 'max_delta_step': 4}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  98%|█████████▊| 196/200 [02:50<00:03,  1.21it/s]

[I 2025-11-10 14:15:35,722] Trial 195 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.021871678989364266, 'n_estimators': 710, 'subsample': 0.7026498885559883, 'colsample_bytree': 0.9396322360876209, 'min_child_weight': 10, 'gamma': 4.986331648354049, 'reg_alpha': 0.0009709422321026471, 'reg_lambda': 5.313932595358958e-07, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  98%|█████████▊| 197/200 [02:51<00:02,  1.34it/s]

[I 2025-11-10 14:15:36,267] Trial 196 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.08467023371289256, 'n_estimators': 695, 'subsample': 0.7893307439025554, 'colsample_bytree': 0.5569779758652655, 'min_child_weight': 10, 'gamma': 4.998645231439497, 'reg_alpha': 0.001342542731511496, 'reg_lambda': 7.257549530666192e-07, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117:  99%|█████████▉| 198/200 [02:53<00:02,  1.03s/it]

[I 2025-11-10 14:15:37,975] Trial 197 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08969167016125472, 'n_estimators': 713, 'subsample': 0.7072184345651837, 'colsample_bytree': 0.8904290165300158, 'min_child_weight': 10, 'gamma': 3.0569649307103637, 'reg_alpha': 0.0011410709816557527, 'reg_lambda': 5.396604652890262e-07, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117: 100%|█████████▉| 199/200 [02:53<00:00,  1.12it/s]

[I 2025-11-10 14:15:38,562] Trial 199 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.026564924472075018, 'n_estimators': 771, 'subsample': 0.7193664166962611, 'colsample_bytree': 0.8931911859701669, 'min_child_weight': 6, 'gamma': 4.906810099998788, 'reg_alpha': 0.0014560037938749404, 'reg_lambda': 2.572787990598157, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

Best trial: 7. Best value: 0.50117: 100%|██████████| 200/200 [02:53<00:00,  1.15it/s]

[I 2025-11-10 14:15:38,918] Trial 198 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.08789826122855317, 'n_estimators': 954, 'subsample': 0.6994582630625138, 'colsample_bytree': 0.8910865475019156, 'min_child_weight': 10, 'gamma': 0.2102382426685569, 'reg_alpha': 0.0014587668232425056, 'reg_lambda': 2.341213781045102, 'max_delta_step': 0}. Best is trial 7 with value: 0.5011695906432749.

[I 2025-11-10 14:15:39,725] A new study created in memory with name: 3_3_balanced_accuracy
Best trial: 2. Best value: 0.5:   0%|          | 1/200 [00:01<06:26,  1.94s/it]

[I 2025-11-10 14:15:41,668] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.17164984687834411, 'n_estimators': 348, 'subsample': 0.742532452679958, 'colsample_bytree': 0.9172513414737913, 'min_child_weight': 9, 'gamma': 0.007232033853677988, 'reg_alpha': 0.9248815644390904, 'reg_lambda': 4.359666606962513e-06, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   1%|          | 2/200 [00:03<04:52,  1.48s/it]

[I 2025-11-10 14:15:42,818] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.010735147833071699, 'n_estimators': 596, 'subsample': 0.7777067149718297, 'colsample_bytree': 0.8152033909051868, 'min_child_weight': 10, 'gamma': 1.045721934943461, 'reg_alpha': 9.003133206995896, 'reg_lambda': 0.00022333562755353604, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▏         | 3/200 [00:04<04:40,  1.42s/it]

[I 2025-11-10 14:15:44,184] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.012302892569294491, 'n_estimators': 499, 'subsample': 0.7110264716768433, 'colsample_bytree': 0.6610473110235553, 'min_child_weight': 4, 'gamma': 0.08887911835328666, 'reg_alpha': 4.417140523787982, 'reg_lambda': 0.003197692828545207, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▏         | 4/200 [00:04<03:25,  1.05s/it]

[I 2025-11-10 14:15:44,645] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07123710566927427, 'n_estimators': 1077, 'subsample': 0.7384519375788053, 'colsample_bytree': 0.6315793537687955, 'min_child_weight': 9, 'gamma': 2.600458902459307, 'reg_alpha': 1.0649317314301918, 'reg_lambda': 0.057716606439321326, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▎         | 5/200 [00:06<03:59,  1.23s/it]

[I 2025-11-10 14:15:46,201] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04109044612942312, 'n_estimators': 1432, 'subsample': 0.5361728531709663, 'colsample_bytree': 0.5192465340464792, 'min_child_weight': 8, 'gamma': 1.366685181588096, 'reg_alpha': 0.06060561673748863, 'reg_lambda': 6.241050450365668, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   3%|▎         | 6/200 [00:06<03:10,  1.02it/s]

[I 2025-11-10 14:15:46,696] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.12561348147853732, 'n_estimators': 698, 'subsample': 0.636006044285006, 'colsample_bytree': 0.9209199724877348, 'min_child_weight': 9, 'gamma': 1.792072756312526, 'reg_alpha': 0.2932667171118782, 'reg_lambda': 2.241891920645681e-06, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   4%|▎         | 7/200 [00:07<02:38,  1.22it/s]

[I 2025-11-10 14:15:47,187] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.054936424031634346, 'n_estimators': 540, 'subsample': 0.9326412236676731, 'colsample_bytree': 0.8018568229943375, 'min_child_weight': 6, 'gamma': 0.29167396891436825, 'reg_alpha': 2.0810098887420927e-06, 'reg_lambda': 0.27613542642076366, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 8. Best value: 0.636199:   4%|▍         | 8/200 [00:07<02:00,  1.60it/s]

[I 2025-11-10 14:15:47,398] Trial 8 finished with value: 0.6361988304093568 and parameters: {'max_depth': 4, 'learning_rate': 0.11257356031240223, 'n_estimators': 233, 'subsample': 0.9930122828311967, 'colsample_bytree': 0.702175611240353, 'min_child_weight': 5, 'gamma': 3.613317368078999, 'reg_alpha': 1.7564311462090858e-07, 'reg_lambda': 2.5423621944812824, 'max_delta_step': 10}. Best is trial 8 with value: 0.6361988304093568.

Best trial: 8. Best value: 0.636199:   4%|▍         | 9/200 [00:10<04:22,  1.37s/it]

[I 2025-11-10 14:15:50,413] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.0416738817659142, 'n_estimators': 787, 'subsample': 0.8221157658291447, 'colsample_bytree': 0.7036503062690376, 'min_child_weight': 9, 'gamma': 2.9679548375457028, 'reg_alpha': 1.1385461017240181e-08, 'reg_lambda': 0.008626991253244443, 'max_delta_step': 10}. Best is trial 8 with value: 0.6361988304093568.

Best trial: 8. Best value: 0.636199:   5%|▌         | 10/200 [00:11<03:24,  1.08s/it]

[I 2025-11-10 14:15:50,821] Trial 9 finished with value: 0.4867251461988304 and parameters: {'max_depth': 7, 'learning_rate': 0.2171347200924539, 'n_estimators': 667, 'subsample': 0.8431810394059631, 'colsample_bytree': 0.612172211490787, 'min_child_weight': 1, 'gamma': 3.5831159953090768, 'reg_alpha': 1.0355602739507654e-08, 'reg_lambda': 3.860773336715411e-05, 'max_delta_step': 4}. Best is trial 8 with value: 0.6361988304093568.

Best trial: 13. Best value: 0.677544:   6%|▌         | 11/200 [00:12<03:25,  1.09s/it]

[I 2025-11-10 14:15:51,945] Trial 13 finished with value: 0.6775438596491228 and parameters: {'max_depth': 5, 'learning_rate': 0.29055787497372687, 'n_estimators': 201, 'subsample': 0.9775203567808107, 'colsample_bytree': 0.503286777752679, 'min_child_weight': 4, 'gamma': 4.409580056799068, 'reg_alpha': 9.858134775475493e-05, 'reg_lambda': 1.316708007340881e-08, 'max_delta_step': 7}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:   6%|▌         | 12/200 [00:13<03:33,  1.14s/it]

[I 2025-11-10 14:15:53,184] Trial 14 finished with value: 0.5976023391812866 and parameters: {'max_depth': 5, 'learning_rate': 0.279749444470585, 'n_estimators': 217, 'subsample': 0.9822951632828976, 'colsample_bytree': 0.5159733969310738, 'min_child_weight': 4, 'gamma': 4.887351192883286, 'reg_alpha': 6.776166604539256e-05, 'reg_lambda': 2.8651421525752316e-08, 'max_delta_step': 7}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:   6%|▋         | 13/200 [00:14<03:20,  1.07s/it]

[I 2025-11-10 14:15:54,107] Trial 6 finished with value: 0.5111111111111112 and parameters: {'max_depth': 6, 'learning_rate': 0.06353780667175264, 'n_estimators': 1407, 'subsample': 0.9756256698783211, 'colsample_bytree': 0.950510647697292, 'min_child_weight': 2, 'gamma': 1.430469600819952, 'reg_alpha': 7.35297049205885e-08, 'reg_lambda': 0.0002606668376024155, 'max_delta_step': 10}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:   7%|▋         | 14/200 [00:14<02:32,  1.22it/s]

[I 2025-11-10 14:15:54,346] Trial 15 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.10571127472311122, 'n_estimators': 203, 'subsample': 0.9996290701577584, 'colsample_bytree': 0.5765493423347162, 'min_child_weight': 5, 'gamma': 4.456120488434358, 'reg_alpha': 1.3981369226645834e-06, 'reg_lambda': 8.183445732883809e-08, 'max_delta_step': 6}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:   8%|▊         | 15/200 [00:15<02:41,  1.15it/s]

[I 2025-11-10 14:15:55,342] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.11879913568149597, 'n_estimators': 226, 'subsample': 0.8963712802729082, 'colsample_bytree': 0.5637900431646468, 'min_child_weight': 6, 'gamma': 4.3632849351550655, 'reg_alpha': 0.002102591508782804, 'reg_lambda': 1.3383936452808804e-08, 'max_delta_step': 7}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:   8%|▊         | 16/200 [00:15<02:08,  1.43it/s]

[I 2025-11-10 14:15:55,645] Trial 11 finished with value: 0.5533918128654971 and parameters: {'max_depth': 10, 'learning_rate': 0.018650848121863343, 'n_estimators': 1484, 'subsample': 0.8649530033172741, 'colsample_bytree': 0.9476489946653115, 'min_child_weight': 4, 'gamma': 1.5244023705162442, 'reg_alpha': 0.05072081616876988, 'reg_lambda': 0.02995913764767446, 'max_delta_step': 5}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:   8%|▊         | 17/200 [00:16<02:06,  1.45it/s]

[I 2025-11-10 14:15:56,309] Trial 12 finished with value: 0.6287134502923977 and parameters: {'max_depth': 9, 'learning_rate': 0.01750825384198563, 'n_estimators': 1239, 'subsample': 0.8688972190026079, 'colsample_bytree': 0.7333174473292141, 'min_child_weight': 5, 'gamma': 1.5524906743557543, 'reg_alpha': 8.049951951286066e-07, 'reg_lambda': 8.43229144384042e-05, 'max_delta_step': 3}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:   9%|▉         | 18/200 [00:19<03:48,  1.25s/it]

[I 2025-11-10 14:15:58,871] Trial 17 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.2865989435409234, 'n_estimators': 1005, 'subsample': 0.8978943803169166, 'colsample_bytree': 0.767562048161563, 'min_child_weight': 6, 'gamma': 3.9727266799219842, 'reg_alpha': 0.0028034645163043746, 'reg_lambda': 1.585903802476382, 'max_delta_step': 0}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:  10%|▉         | 19/200 [00:21<04:30,  1.49s/it]

[I 2025-11-10 14:16:00,929] Trial 21 finished with value: 0.5756140350877192 and parameters: {'max_depth': 5, 'learning_rate': 0.18079602298364036, 'n_estimators': 406, 'subsample': 0.6485298330268083, 'colsample_bytree': 0.8715737120716778, 'min_child_weight': 3, 'gamma': 3.3042220029187317, 'reg_alpha': 4.145597836184473e-05, 'reg_lambda': 4.468251594088809e-07, 'max_delta_step': 7}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:  10%|█         | 20/200 [00:21<03:27,  1.15s/it]

[I 2025-11-10 14:16:01,298] Trial 18 finished with value: 0.539766081871345 and parameters: {'max_depth': 5, 'learning_rate': 0.29844810963134366, 'n_estimators': 1102, 'subsample': 0.8861422793184809, 'colsample_bytree': 0.7518811030240466, 'min_child_weight': 3, 'gamma': 3.7170320842873377, 'reg_alpha': 3.749840301887208e-05, 'reg_lambda': 0.7304580505386011, 'max_delta_step': 4}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:  10%|█         | 21/200 [00:21<02:47,  1.07it/s]

[I 2025-11-10 14:16:01,728] Trial 22 pruned.

Best trial: 13. Best value: 0.677544:  11%|█         | 22/200 [00:22<02:13,  1.33it/s]

[I 2025-11-10 14:16:02,042] Trial 23 pruned.

Best trial: 13. Best value: 0.677544:  12%|█▏        | 23/200 [00:22<01:58,  1.50it/s]

[I 2025-11-10 14:16:02,512] Trial 19 finished with value: 0.5470760233918128 and parameters: {'max_depth': 5, 'learning_rate': 0.18211108580340823, 'n_estimators': 1052, 'subsample': 0.9229010627132536, 'colsample_bytree': 0.7408452414607345, 'min_child_weight': 2, 'gamma': 3.6690048658459005, 'reg_alpha': 4.16316129653136e-05, 'reg_lambda': 4.169521009161545, 'max_delta_step': 0}. Best is trial 13 with value: 0.6775438596491228.
[I 2025-11-10 14:16:02,540] Trial 20 finished with value: 0.5599999999999999 and parameters: {'max_depth': 5, 'learning_rate': 0.2630120097429408, 'n_estimators': 960, 'subsample': 0.9251557211188306, 'colsample_bytree': 0.7905910214926736, 'min_child_weight': 2, 'gamma': 3.5827760330182503, 'reg_alpha': 6.164468240521261e-05, 'reg_lambda': 8.180577760735659, 'max_delta_step': 0}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:  12%|█▎        | 25/200 [00:23<01:23,  2.09it/s]

[I 2025-11-10 14:16:03,031] Trial 24 finished with value: 0.6361988304093568 and parameters: {'max_depth': 4, 'learning_rate': 0.11004849401417251, 'n_estimators': 206, 'subsample': 0.9962820422559872, 'colsample_bytree': 0.5718722044747028, 'min_child_weight': 5, 'gamma': 4.9807475015729485, 'reg_alpha': 8.113765252007821e-07, 'reg_lambda': 1.3249832577021687e-07, 'max_delta_step': 6}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:  13%|█▎        | 26/200 [00:23<01:19,  2.18it/s]

[I 2025-11-10 14:16:03,428] Trial 25 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.13052396003711772, 'n_estimators': 243, 'subsample': 0.9853704477506535, 'colsample_bytree': 0.5738198300875036, 'min_child_weight': 5, 'gamma': 4.557487411760065, 'reg_alpha': 1.0190872585669457e-07, 'reg_lambda': 1.4010257132482872e-07, 'max_delta_step': 6}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:  14%|█▎        | 27/200 [00:24<01:13,  2.35it/s]

[I 2025-11-10 14:16:03,761] Trial 26 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.12882003112367998, 'n_estimators': 204, 'subsample': 0.9935843436083973, 'colsample_bytree': 0.6113633720981978, 'min_child_weight': 5, 'gamma': 4.349848373801235, 'reg_alpha': 2.631131527004894e-07, 'reg_lambda': 1.5345236679121913e-07, 'max_delta_step': 6}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:  14%|█▍        | 28/200 [00:24<01:11,  2.42it/s]

[I 2025-11-10 14:16:04,146] Trial 27 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.11817026746649088, 'n_estimators': 282, 'subsample': 0.9976930397524318, 'colsample_bytree': 0.5659718344527804, 'min_child_weight': 5, 'gamma': 4.293609033229426, 'reg_alpha': 4.2107745486707617e-07, 'reg_lambda': 1.4641242414637992e-07, 'max_delta_step': 6}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:  14%|█▍        | 29/200 [00:24<01:16,  2.23it/s]

[I 2025-11-10 14:16:04,678] Trial 28 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.03638414379390326, 'n_estimators': 289, 'subsample': 0.9978801477534437, 'colsample_bytree': 0.5721887039849631, 'min_child_weight': 5, 'gamma': 4.34710512907879, 'reg_alpha': 2.3869291888173067e-07, 'reg_lambda': 1.6583372806632236e-07, 'max_delta_step': 6}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:  16%|█▌        | 31/200 [00:26<01:43,  1.63it/s]

[I 2025-11-10 14:16:06,323] Trial 29 finished with value: 0.5739766081871345 and parameters: {'max_depth': 3, 'learning_rate': 0.03645538567389255, 'n_estimators': 470, 'subsample': 0.8174936328268406, 'colsample_bytree': 0.543130262540382, 'min_child_weight': 3, 'gamma': 4.278464585856341, 'reg_alpha': 0.000342978202332683, 'reg_lambda': 5.034889511462161e-07, 'max_delta_step': 6}. Best is trial 13 with value: 0.6775438596491228.
[I 2025-11-10 14:16:06,499] Trial 30 finished with value: 0.6303508771929824 and parameters: {'max_depth': 4, 'learning_rate': 0.03889538306664585, 'n_estimators': 453, 'subsample': 0.8239219525417069, 'colsample_bytree': 0.5001903831408634, 'min_child_weight': 3, 'gamma': 4.201113260444049, 'reg_alpha': 0.0005462830826165465, 'reg_lambda': 6.457459573683884e-07, 'max_delta_step': 5}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:  16%|█▋        | 33/200 [00:27<01:08,  2.44it/s]

[I 2025-11-10 14:16:06,836] Trial 33 pruned.
[I 2025-11-10 14:16:06,957] Trial 34 pruned.

Best trial: 13. Best value: 0.677544:  17%|█▋        | 34/200 [00:27<00:54,  3.04it/s]

[I 2025-11-10 14:16:07,088] Trial 31 finished with value: 0.6114035087719298 and parameters: {'max_depth': 4, 'learning_rate': 0.03335518518038788, 'n_estimators': 465, 'subsample': 0.8041968850011294, 'colsample_bytree': 0.50355327367815, 'min_child_weight': 3, 'gamma': 2.978772196053624, 'reg_alpha': 0.0004397501378674382, 'reg_lambda': 9.00392070201344e-07, 'max_delta_step': 10}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:  18%|█▊        | 36/200 [00:28<00:49,  3.30it/s]

[I 2025-11-10 14:16:07,594] Trial 36 pruned.
[I 2025-11-10 14:16:07,715] Trial 37 pruned.
[I 2025-11-10 14:16:07,734] Trial 32 finished with value: 0.5605847953216375 and parameters: {'max_depth': 4, 'learning_rate': 0.07230539001831561, 'n_estimators': 471, 'subsample': 0.8107678504709678, 'colsample_bytree': 0.5195569827557793, 'min_child_weight': 3, 'gamma': 2.5158182843744052, 'reg_alpha': 0.0006757456411180208, 'reg_lambda': 8.078302799334595e-07, 'max_delta_step': 10}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:  19%|█▉        | 38/200 [00:28<00:42,  3.79it/s]

[I 2025-11-10 14:16:08,152] Trial 39 pruned.

Best trial: 13. Best value: 0.677544:  20%|█▉        | 39/200 [00:28<00:47,  3.37it/s]

[I 2025-11-10 14:16:08,548] Trial 41 pruned.

Best trial: 13. Best value: 0.677544:  20%|██        | 41/200 [00:29<00:41,  3.79it/s]

[I 2025-11-10 14:16:08,907] Trial 42 pruned.
[I 2025-11-10 14:16:09,038] Trial 35 finished with value: 0.5773099415204678 and parameters: {'max_depth': 4, 'learning_rate': 0.09902540850013304, 'n_estimators': 321, 'subsample': 0.9558604134144234, 'colsample_bytree': 0.5969535207402796, 'min_child_weight': 4, 'gamma': 4.725019965229198, 'reg_alpha': 3.49235892048546e-08, 'reg_lambda': 4.1902909520182496e-08, 'max_delta_step': 4}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:  21%|██        | 42/200 [00:29<00:58,  2.72it/s]

[I 2025-11-10 14:16:09,670] Trial 43 pruned.

Best trial: 13. Best value: 0.677544:  22%|██▏       | 44/200 [00:30<00:41,  3.74it/s]

[I 2025-11-10 14:16:09,881] Trial 38 finished with value: 0.5681286549707603 and parameters: {'max_depth': 4, 'learning_rate': 0.16430666136475086, 'n_estimators': 330, 'subsample': 0.9097711461443924, 'colsample_bytree': 0.5922656617595602, 'min_child_weight': 4, 'gamma': 4.618724421841992, 'reg_alpha': 1.367723543962876e-06, 'reg_lambda': 6.071292873570759e-08, 'max_delta_step': 8}. Best is trial 13 with value: 0.6775438596491228.
[I 2025-11-10 14:16:10,013] Trial 40 finished with value: 0.5903508771929824 and parameters: {'max_depth': 4, 'learning_rate': 0.2146030805286885, 'n_estimators': 322, 'subsample': 0.9106980856250412, 'colsample_bytree': 0.8342163233661037, 'min_child_weight': 4, 'gamma': 4.6745003882060265, 'reg_alpha': 9.906291248541083e-07, 'reg_lambda': 4.836839057393279e-08, 'max_delta_step': 2}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 13. Best value: 0.677544:  22%|██▎       | 45/200 [00:30<00:54,  2.87it/s]

[I 2025-11-10 14:16:10,562] Trial 44 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.06269135151860715, 'n_estimators': 203, 'subsample': 0.9718889400122931, 'colsample_bytree': 0.63936298155104, 'min_child_weight': 5, 'gamma': 4.64113091362305, 'reg_alpha': 1.0986507337386815e-07, 'reg_lambda': 1.9473310048278866e-07, 'max_delta_step': 6}. Best is trial 13 with value: 0.6775438596491228.

Best trial: 45. Best value: 0.68538:  24%|██▎       | 47/200 [00:31<00:43,  3.55it/s]

[I 2025-11-10 14:16:10,836] Trial 48 pruned.
[I 2025-11-10 14:16:11,010] Trial 45 finished with value: 0.6853801169590643 and parameters: {'max_depth': 3, 'learning_rate': 0.22284444350595695, 'n_estimators': 231, 'subsample': 0.9765294378721485, 'colsample_bytree': 0.5819803966966483, 'min_child_weight': 5, 'gamma': 4.5862641921394545, 'reg_alpha': 1.1919958173630419e-07, 'reg_lambda': 0.06963644435272849, 'max_delta_step': 6}. Best is trial 45 with value: 0.6853801169590643.

Best trial: 45. Best value: 0.68538:  24%|██▍       | 48/200 [00:31<00:43,  3.50it/s]

[I 2025-11-10 14:16:11,307] Trial 46 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.06061703143034861, 'n_estimators': 245, 'subsample': 0.9779674307569135, 'colsample_bytree': 0.6410441813711631, 'min_child_weight': 5, 'gamma': 4.618487995160019, 'reg_alpha': 1.1974466753866968e-07, 'reg_lambda': 1.7356604083435593e-07, 'max_delta_step': 6}. Best is trial 45 with value: 0.6853801169590643.
[I 2025-11-10 14:16:11,404] Trial 47 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.0626355572893869, 'n_estimators': 216, 'subsample': 0.979652009279272, 'colsample_bytree': 0.7079229218273645, 'min_child_weight': 5, 'gamma': 4.0660530229766625, 'reg_alpha': 1.5294790392609322e-07, 'reg_lambda': 0.04645910367267053, 'max_delta_step': 6}. Best is trial 45 with value: 0.6853801169590643.

Best trial: 45. Best value: 0.68538:  25%|██▌       | 50/200 [00:31<00:30,  4.85it/s]

[I 2025-11-10 14:16:11,537] Trial 49 pruned.

Best trial: 45. Best value: 0.68538:  26%|██▌       | 51/200 [00:32<00:36,  4.07it/s]

[I 2025-11-10 14:16:11,904] Trial 50 pruned.
[I 2025-11-10 14:16:11,970] Trial 53 pruned.

Best trial: 45. Best value: 0.68538:  27%|██▋       | 54/200 [00:32<00:26,  5.43it/s]

[I 2025-11-10 14:16:12,212] Trial 51 pruned.
[I 2025-11-10 14:16:12,305] Trial 55 pruned.

Best trial: 45. Best value: 0.68538:  28%|██▊       | 55/200 [00:32<00:24,  5.81it/s]

[I 2025-11-10 14:16:12,445] Trial 52 pruned.
[I 2025-11-10 14:16:12,447] Trial 54 pruned.

Best trial: 45. Best value: 0.68538:  28%|██▊       | 57/200 [00:32<00:20,  7.09it/s]

[I 2025-11-10 14:16:12,637] Trial 56 pruned.

Best trial: 45. Best value: 0.68538:  29%|██▉       | 58/200 [00:34<00:56,  2.53it/s]

[I 2025-11-10 14:16:13,896] Trial 58 finished with value: 0.6361988304093568 and parameters: {'max_depth': 4, 'learning_rate': 0.10978691575774234, 'n_estimators': 251, 'subsample': 0.9996994191257391, 'colsample_bytree': 0.5226619020782828, 'min_child_weight': 5, 'gamma': 4.780178717733323, 'reg_alpha': 8.855890443032006e-06, 'reg_lambda': 0.00019797388283755197, 'max_delta_step': 6}. Best is trial 45 with value: 0.6853801169590643.

Best trial: 45. Best value: 0.68538:  30%|██▉       | 59/200 [00:34<00:52,  2.67it/s]

[I 2025-11-10 14:16:14,206] Trial 61 pruned.

Best trial: 45. Best value: 0.68538:  30%|███       | 60/200 [00:35<00:57,  2.43it/s]

[I 2025-11-10 14:16:14,733] Trial 62 pruned.

Best trial: 45. Best value: 0.68538:  30%|███       | 61/200 [00:38<02:57,  1.28s/it]

[I 2025-11-10 14:16:18,345] Trial 59 finished with value: 0.6423391812865497 and parameters: {'max_depth': 4, 'learning_rate': 0.116377661548117, 'n_estimators': 1191, 'subsample': 0.9739589470662359, 'colsample_bytree': 0.523768017364002, 'min_child_weight': 5, 'gamma': 1.9531510776436303, 'reg_alpha': 1.671345481771661e-05, 'reg_lambda': 0.00011719951381402717, 'max_delta_step': 6}. Best is trial 45 with value: 0.6853801169590643.

Best trial: 45. Best value: 0.68538:  31%|███       | 62/200 [00:39<02:30,  1.09s/it]

[I 2025-11-10 14:16:18,936] Trial 60 finished with value: 0.6361988304093568 and parameters: {'max_depth': 9, 'learning_rate': 0.1150522393429886, 'n_estimators': 1274, 'subsample': 0.998535838887761, 'colsample_bytree': 0.5274958386354867, 'min_child_weight': 5, 'gamma': 4.817030267066424, 'reg_alpha': 1.894357319112504e-05, 'reg_lambda': 0.0005524000960140679, 'max_delta_step': 6}. Best is trial 45 with value: 0.6853801169590643.
[I 2025-11-10 14:16:18,980] Trial 57 finished with value: 0.6417543859649124 and parameters: {'max_depth': 4, 'learning_rate': 0.15084462542499924, 'n_estimators': 1333, 'subsample': 0.9386735415846641, 'colsample_bytree': 0.5833210916894422, 'min_child_weight': 5, 'gamma': 4.746680034337539, 'reg_alpha': 1.1922667806609401e-05, 'reg_lambda': 0.0001386740126749239, 'max_delta_step': 6}. Best is trial 45 with value: 0.6853801169590643.

Best trial: 45. Best value: 0.68538:  32%|███▏      | 64/200 [00:39<01:32,  1.47it/s]

[I 2025-11-10 14:16:19,276] Trial 63 finished with value: 0.6315204678362573 and parameters: {'max_depth': 3, 'learning_rate': 0.2979150867806107, 'n_estimators': 906, 'subsample': 0.8959336597344623, 'colsample_bytree': 0.615825985862798, 'min_child_weight': 5, 'gamma': 3.450438415491667, 'reg_alpha': 2.425838721280754e-06, 'reg_lambda': 1.8772330142506584e-08, 'max_delta_step': 9}. Best is trial 45 with value: 0.6853801169590643.

Best trial: 45. Best value: 0.68538:  32%|███▎      | 65/200 [00:39<01:21,  1.66it/s]

[I 2025-11-10 14:16:19,636] Trial 64 pruned.

Best trial: 45. Best value: 0.68538:  33%|███▎      | 66/200 [00:41<01:42,  1.30it/s]

[I 2025-11-10 14:16:20,883] Trial 68 pruned.

Best trial: 45. Best value: 0.68538:  34%|███▎      | 67/200 [00:43<02:25,  1.10s/it]

[I 2025-11-10 14:16:22,876] Trial 69 pruned.

Best trial: 45. Best value: 0.68538:  34%|███▍      | 68/200 [00:45<02:58,  1.35s/it]

[I 2025-11-10 14:16:24,888] Trial 67 finished with value: 0.6509356725146198 and parameters: {'max_depth': 5, 'learning_rate': 0.09287471637102333, 'n_estimators': 1178, 'subsample': 0.9472748701709823, 'colsample_bytree': 0.5108680345269561, 'min_child_weight': 5, 'gamma': 2.047348291864501, 'reg_alpha': 0.00017535877625458283, 'reg_lambda': 7.780224006188923e-05, 'max_delta_step': 1}. Best is trial 45 with value: 0.6853801169590643.

Best trial: 45. Best value: 0.68538:  34%|███▍      | 69/200 [00:45<02:32,  1.17s/it]

[I 2025-11-10 14:16:25,585] Trial 65 finished with value: 0.6434502923976607 and parameters: {'max_depth': 3, 'learning_rate': 0.13971505583670882, 'n_estimators': 1358, 'subsample': 0.9509891675386662, 'colsample_bytree': 0.6092274097413077, 'min_child_weight': 5, 'gamma': 1.906287594258059, 'reg_alpha': 2.7127361197005027e-06, 'reg_lambda': 1.7024749986402075e-08, 'max_delta_step': 6}. Best is trial 45 with value: 0.6853801169590643.
[I 2025-11-10 14:16:25,589] Trial 66 finished with value: 0.662046783625731 and parameters: {'max_depth': 5, 'learning_rate': 0.27083974394018334, 'n_estimators': 1372, 'subsample': 0.9508752886148806, 'colsample_bytree': 0.5118260837761317, 'min_child_weight': 5, 'gamma': 1.2799278691101286, 'reg_alpha': 2.5610211288982933e-05, 'reg_lambda': 8.543573863214193e-05, 'max_delta_step': 6}. Best is trial 45 with value: 0.6853801169590643.

Best trial: 45. Best value: 0.68538:  36%|███▌      | 71/200 [00:47<01:57,  1.10it/s]

[I 2025-11-10 14:16:26,779] Trial 71 pruned.

Best trial: 45. Best value: 0.68538:  36%|███▌      | 72/200 [00:47<01:38,  1.31it/s]

[I 2025-11-10 14:16:27,093] Trial 73 pruned.

Best trial: 45. Best value: 0.68538:  36%|███▋      | 73/200 [00:48<01:47,  1.18it/s]

[I 2025-11-10 14:16:28,169] Trial 74 pruned.
[I 2025-11-10 14:16:28,279] Trial 75 pruned.

Best trial: 45. Best value: 0.68538:  38%|███▊      | 75/200 [00:49<01:36,  1.30it/s]

[I 2025-11-10 14:16:29,504] Trial 76 pruned.

Best trial: 45. Best value: 0.68538:  38%|███▊      | 76/200 [00:50<01:20,  1.54it/s]

[I 2025-11-10 14:16:29,751] Trial 77 pruned.

Best trial: 45. Best value: 0.68538:  38%|███▊      | 77/200 [00:50<01:05,  1.87it/s]

[I 2025-11-10 14:16:29,938] Trial 70 finished with value: 0.6287134502923977 and parameters: {'max_depth': 5, 'learning_rate': 0.02689825202734096, 'n_estimators': 1428, 'subsample': 0.9489513108558308, 'colsample_bytree': 0.6068098750107161, 'min_child_weight': 5, 'gamma': 1.6930948734087798, 'reg_alpha': 0.0012020897936411068, 'reg_lambda': 0.14199835120666465, 'max_delta_step': 4}. Best is trial 45 with value: 0.6853801169590643.

Best trial: 45. Best value: 0.68538:  39%|███▉      | 78/200 [00:51<01:20,  1.52it/s]

[I 2025-11-10 14:16:30,941] Trial 79 pruned.

Best trial: 45. Best value: 0.68538:  40%|████      | 80/200 [00:53<01:26,  1.38it/s]

[I 2025-11-10 14:16:32,632] Trial 81 pruned.
[I 2025-11-10 14:16:32,814] Trial 72 finished with value: 0.5877777777777777 and parameters: {'max_depth': 6, 'learning_rate': 0.2718017636598179, 'n_estimators': 1411, 'subsample': 0.8843596501466683, 'colsample_bytree': 0.5479997281396775, 'min_child_weight': 3, 'gamma': 1.684947490938407, 'reg_alpha': 0.000178313500448418, 'reg_lambda': 8.709449839239646e-05, 'max_delta_step': 1}. Best is trial 45 with value: 0.6853801169590643.

Best trial: 45. Best value: 0.68538:  40%|████      | 81/200 [00:54<01:43,  1.15it/s]

[I 2025-11-10 14:16:34,041] Trial 83 pruned.
[I 2025-11-10 14:16:34,079] Trial 82 pruned.

Best trial: 45. Best value: 0.68538:  42%|████▏     | 83/200 [00:55<01:24,  1.38it/s]

[I 2025-11-10 14:16:35,148] Trial 85 pruned.

Best trial: 45. Best value: 0.68538:  42%|████▏     | 84/200 [00:55<01:08,  1.68it/s]

[I 2025-11-10 14:16:35,330] Trial 84 pruned.

Best trial: 45. Best value: 0.68538:  42%|████▎     | 85/200 [00:55<00:56,  2.03it/s]

[I 2025-11-10 14:16:35,517] Trial 80 finished with value: 0.5845029239766081 and parameters: {'max_depth': 4, 'learning_rate': 0.1675184208973893, 'n_estimators': 1080, 'subsample': 0.933994050585884, 'colsample_bytree': 0.544101444919855, 'min_child_weight': 4, 'gamma': 1.9169392054793546, 'reg_alpha': 0.006881087985591857, 'reg_lambda': 0.0006362185798215526, 'max_delta_step': 5}. Best is trial 45 with value: 0.6853801169590643.

Best trial: 45. Best value: 0.68538:  43%|████▎     | 86/200 [00:56<01:05,  1.74it/s]

[I 2025-11-10 14:16:36,326] Trial 86 pruned.

Best trial: 45. Best value: 0.68538:  44%|████▎     | 87/200 [00:57<00:55,  2.02it/s]

[I 2025-11-10 14:16:36,611] Trial 78 finished with value: 0.538362573099415 and parameters: {'max_depth': 5, 'learning_rate': 0.17036827007694155, 'n_estimators': 1336, 'subsample': 0.9374386194426523, 'colsample_bytree': 0.6029675439937489, 'min_child_weight': 4, 'gamma': 2.199553031083613, 'reg_alpha': 3.312681222848811e-05, 'reg_lambda': 0.0004354717004561919, 'max_delta_step': 7}. Best is trial 45 with value: 0.6853801169590643.
[I 2025-11-10 14:16:36,787] Trial 87 pruned.

Best trial: 45. Best value: 0.68538:  44%|████▍     | 89/200 [00:58<01:08,  1.62it/s]

[I 2025-11-10 14:16:37,927] Trial 89 pruned.
[I 2025-11-10 14:16:37,946] Trial 90 pruned.

Best trial: 45. Best value: 0.68538:  46%|████▌     | 91/200 [00:58<00:48,  2.26it/s]

[I 2025-11-10 14:16:38,398] Trial 91 pruned.

Best trial: 45. Best value: 0.68538:  46%|████▌     | 92/200 [00:59<00:45,  2.38it/s]

[I 2025-11-10 14:16:38,749] Trial 92 pruned.

Best trial: 45. Best value: 0.68538:  46%|████▋     | 93/200 [00:59<00:45,  2.34it/s]

[I 2025-11-10 14:16:39,192] Trial 94 pruned.

Best trial: 45. Best value: 0.68538:  47%|████▋     | 94/200 [00:59<00:41,  2.54it/s]

[I 2025-11-10 14:16:39,489] Trial 93 pruned.
[I 2025-11-10 14:16:39,499] Trial 96 pruned.

Best trial: 45. Best value: 0.68538:  48%|████▊     | 96/200 [01:00<00:33,  3.15it/s]

[I 2025-11-10 14:16:39,932] Trial 98 pruned.

Best trial: 45. Best value: 0.68538:  48%|████▊     | 97/200 [01:00<00:38,  2.66it/s]

[I 2025-11-10 14:16:40,493] Trial 95 finished with value: 0.6361988304093568 and parameters: {'max_depth': 4, 'learning_rate': 0.1163294102480555, 'n_estimators': 290, 'subsample': 0.9915943602151396, 'colsample_bytree': 0.5604154630529968, 'min_child_weight': 5, 'gamma': 4.849229330712057, 'reg_alpha': 1.0641705180226205e-06, 'reg_lambda': 0.00014426671435319047, 'max_delta_step': 6}. Best is trial 45 with value: 0.6853801169590643.

Best trial: 45. Best value: 0.68538:  49%|████▉     | 98/200 [01:01<00:43,  2.36it/s]

[I 2025-11-10 14:16:41,066] Trial 99 pruned.

Best trial: 45. Best value: 0.68538:  50%|████▉     | 99/200 [01:01<00:40,  2.52it/s]

[I 2025-11-10 14:16:41,378] Trial 101 pruned.

Best trial: 45. Best value: 0.68538:  50%|█████     | 100/200 [01:02<00:48,  2.07it/s]

[I 2025-11-10 14:16:42,090] Trial 88 finished with value: 0.6309356725146198 and parameters: {'max_depth': 3, 'learning_rate': 0.09560343011701355, 'n_estimators': 1191, 'subsample': 0.9776167523152854, 'colsample_bytree': 0.6296252775617281, 'min_child_weight': 5, 'gamma': 2.733941798095437, 'reg_alpha': 1.5858317343613555e-05, 'reg_lambda': 0.00017126598903645704, 'max_delta_step': 6}. Best is trial 45 with value: 0.6853801169590643.

Best trial: 45. Best value: 0.68538:  50%|█████     | 101/200 [01:03<01:01,  1.60it/s]

[I 2025-11-10 14:16:43,070] Trial 103 pruned.

Best trial: 45. Best value: 0.68538:  51%|█████     | 102/200 [01:04<01:28,  1.11it/s]

[I 2025-11-10 14:16:44,674] Trial 104 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.012729819151705467, 'n_estimators': 263, 'subsample': 0.9895216035625952, 'colsample_bytree': 0.5376188923450104, 'min_child_weight': 5, 'gamma': 4.715207690331193, 'reg_alpha': 7.278849437253689e-06, 'reg_lambda': 8.01589342037462e-08, 'max_delta_step': 6}. Best is trial 45 with value: 0.6853801169590643.

Best trial: 45. Best value: 0.68538:  52%|█████▏    | 103/200 [01:06<01:53,  1.16s/it]

[I 2025-11-10 14:16:46,478] Trial 105 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.12572375473226707, 'n_estimators': 306, 'subsample': 0.9499771511133578, 'colsample_bytree': 0.5723419422375302, 'min_child_weight': 5, 'gamma': 4.99896053349678, 'reg_alpha': 3.376523895003705e-08, 'reg_lambda': 1.2960446426796534e-08, 'max_delta_step': 10}. Best is trial 45 with value: 0.6853801169590643.

Best trial: 45. Best value: 0.68538:  52%|█████▏    | 104/200 [01:06<01:25,  1.13it/s]

[I 2025-11-10 14:16:46,698] Trial 97 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.12429681394809881, 'n_estimators': 1305, 'subsample': 0.9901797667702694, 'colsample_bytree': 0.6487284048316556, 'min_child_weight': 5, 'gamma': 4.708704224532724, 'reg_alpha': 3.447806968516192e-07, 'reg_lambda': 1.6174787388799444e-08, 'max_delta_step': 5}. Best is trial 45 with value: 0.6853801169590643.
[I 2025-11-10 14:16:46,715] Trial 102 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.20583504154477658, 'n_estimators': 922, 'subsample': 0.9912395613972201, 'colsample_bytree': 0.5365221179260357, 'min_child_weight': 5, 'gamma': 4.7167428702798295, 'reg_alpha': 8.281586964916065e-06, 'reg_lambda': 1.5167342642005293e-08, 'max_delta_step': 10}. Best is trial 45 with value: 0.6853801169590643.

Best trial: 45. Best value: 0.68538:  53%|█████▎    | 106/200 [01:07<00:51,  1.84it/s]

[I 2025-11-10 14:16:46,955] Trial 106 pruned.

Best trial: 45. Best value: 0.68538:  54%|█████▎    | 107/200 [01:07<00:43,  2.13it/s]

[I 2025-11-10 14:16:47,216] Trial 108 pruned.

Best trial: 45. Best value: 0.68538:  54%|█████▍    | 108/200 [01:08<00:46,  1.97it/s]

[I 2025-11-10 14:16:47,828] Trial 100 finished with value: 0.6456725146198831 and parameters: {'max_depth': 3, 'learning_rate': 0.08736414620400967, 'n_estimators': 1317, 'subsample': 0.9220085180198272, 'colsample_bytree': 0.5968517724394127, 'min_child_weight': 5, 'gamma': 4.511844611367548, 'reg_alpha': 3.654494766627829e-07, 'reg_lambda': 1.5918076842454684e-05, 'max_delta_step': 10}. Best is trial 45 with value: 0.6853801169590643.

Best trial: 45. Best value: 0.68538:  55%|█████▍    | 109/200 [01:08<00:48,  1.88it/s]

[I 2025-11-10 14:16:48,417] Trial 107 pruned.
[I 2025-11-10 14:16:48,594] Trial 109 finished with value: 0.6309356725146198 and parameters: {'max_depth': 4, 'learning_rate': 0.22578162589962325, 'n_estimators': 267, 'subsample': 0.974955063467203, 'colsample_bytree': 0.522189720081915, 'min_child_weight': 5, 'gamma': 4.566528291134149, 'reg_alpha': 7.360565166068767e-08, 'reg_lambda': 1.2610188119227626e-07, 'max_delta_step': 9}. Best is trial 45 with value: 0.6853801169590643.

Best trial: 45. Best value: 0.68538:  56%|█████▌    | 111/200 [01:09<00:31,  2.86it/s]

[I 2025-11-10 14:16:48,748] Trial 110 pruned.

Best trial: 45. Best value: 0.68538:  56%|█████▌    | 112/200 [01:09<00:40,  2.17it/s]

[I 2025-11-10 14:16:49,471] Trial 111 pruned.

Best trial: 45. Best value: 0.68538:  56%|█████▋    | 113/200 [01:10<00:38,  2.28it/s]

[I 2025-11-10 14:16:49,863] Trial 112 pruned.

Best trial: 114. Best value: 0.690643:  57%|█████▋    | 114/200 [01:10<00:35,  2.43it/s]

[I 2025-11-10 14:16:50,214] Trial 114 finished with value: 0.6906432748538012 and parameters: {'max_depth': 3, 'learning_rate': 0.08766969983244909, 'n_estimators': 207, 'subsample': 0.9488356816945472, 'colsample_bytree': 0.597226628401322, 'min_child_weight': 5, 'gamma': 4.8958212481314405, 'reg_alpha': 5.1989777780564576e-05, 'reg_lambda': 0.0002635111100987934, 'max_delta_step': 10}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  57%|█████▊    | 115/200 [01:11<00:44,  1.93it/s]

[I 2025-11-10 14:16:50,981] Trial 116 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.07939849299310796, 'n_estimators': 203, 'subsample': 0.9429855034207175, 'colsample_bytree': 0.5775628352482974, 'min_child_weight': 5, 'gamma': 4.89273419507495, 'reg_alpha': 2.646405218022771e-05, 'reg_lambda': 4.4145341333351136e-05, 'max_delta_step': 6}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  58%|█████▊    | 116/200 [01:11<00:40,  2.05it/s]

[I 2025-11-10 14:16:51,392] Trial 117 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.10223428236383342, 'n_estimators': 202, 'subsample': 0.943851171634984, 'colsample_bytree': 0.5764892025189061, 'min_child_weight': 5, 'gamma': 4.878002989833549, 'reg_alpha': 2.1469484930419175e-05, 'reg_lambda': 6.241937494434142e-05, 'max_delta_step': 10}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  58%|█████▊    | 117/200 [01:12<01:00,  1.36it/s]

[I 2025-11-10 14:16:52,712] Trial 119 pruned.

Best trial: 114. Best value: 0.690643:  59%|█████▉    | 118/200 [01:14<01:24,  1.03s/it]

[I 2025-11-10 14:16:54,419] Trial 120 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.08432826235178081, 'n_estimators': 267, 'subsample': 0.9542198981335221, 'colsample_bytree': 0.5904212998462759, 'min_child_weight': 5, 'gamma': 4.788304520818064, 'reg_alpha': 9.422169711349909e-05, 'reg_lambda': 2.6488879220473642e-05, 'max_delta_step': 10}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  60%|█████▉    | 119/200 [01:15<01:28,  1.09s/it]

[I 2025-11-10 14:16:55,650] Trial 113 finished with value: 0.5783625730994152 and parameters: {'max_depth': 5, 'learning_rate': 0.0797092212796924, 'n_estimators': 1230, 'subsample': 0.9255069021510431, 'colsample_bytree': 0.7876872239761173, 'min_child_weight': 4, 'gamma': 1.6262963816142042, 'reg_alpha': 5.330073855947099e-05, 'reg_lambda': 1.874924612576736e-05, 'max_delta_step': 9}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  60%|██████    | 120/200 [01:16<01:09,  1.15it/s]

[I 2025-11-10 14:16:56,005] Trial 121 finished with value: 0.6361988304093568 and parameters: {'max_depth': 5, 'learning_rate': 0.07337358915882881, 'n_estimators': 302, 'subsample': 0.9807762039161371, 'colsample_bytree': 0.5492786770342232, 'min_child_weight': 5, 'gamma': 4.224361574330868, 'reg_alpha': 5.168573979481966e-05, 'reg_lambda': 9.990778573670881e-05, 'max_delta_step': 10}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  60%|██████    | 121/200 [01:16<00:53,  1.48it/s]

[I 2025-11-10 14:16:56,221] Trial 115 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.10236445867872138, 'n_estimators': 1307, 'subsample': 0.9478513233703328, 'colsample_bytree': 0.5921538301830853, 'min_child_weight': 5, 'gamma': 4.898997557362061, 'reg_alpha': 5.888917166071391e-07, 'reg_lambda': 0.00029377717769921976, 'max_delta_step': 10}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  61%|██████    | 122/200 [01:17<00:52,  1.47it/s]

[I 2025-11-10 14:16:56,914] Trial 122 pruned.

Best trial: 114. Best value: 0.690643:  62%|██████▏   | 123/200 [01:17<00:41,  1.84it/s]

[I 2025-11-10 14:16:57,147] Trial 123 pruned.

Best trial: 114. Best value: 0.690643:  62%|██████▏   | 124/200 [01:18<00:59,  1.28it/s]

[I 2025-11-10 14:16:58,468] Trial 124 finished with value: 0.6264912280701754 and parameters: {'max_depth': 3, 'learning_rate': 0.13565342669947145, 'n_estimators': 234, 'subsample': 0.9980308195885398, 'colsample_bytree': 0.6055591344663329, 'min_child_weight': 5, 'gamma': 2.0417429219487824, 'reg_alpha': 2.6248957448237315e-07, 'reg_lambda': 3.64263188519697e-08, 'max_delta_step': 6}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  62%|██████▎   | 125/200 [01:19<00:53,  1.40it/s]

[I 2025-11-10 14:16:59,032] Trial 118 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.10719079622665599, 'n_estimators': 1322, 'subsample': 0.9494437233050562, 'colsample_bytree': 0.6148298770891087, 'min_child_weight': 5, 'gamma': 4.322440988340233, 'reg_alpha': 2.3110514600847216e-05, 'reg_lambda': 6.55101703284456e-05, 'max_delta_step': 10}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  63%|██████▎   | 126/200 [01:20<01:00,  1.22it/s]

[I 2025-11-10 14:17:00,088] Trial 128 pruned.
[I 2025-11-10 14:17:00,097] Trial 125 finished with value: 0.6309356725146198 and parameters: {'max_depth': 3, 'learning_rate': 0.13214090117639962, 'n_estimators': 233, 'subsample': 0.9735863500180874, 'colsample_bytree': 0.6031747790941376, 'min_child_weight': 5, 'gamma': 3.1404266758868746, 'reg_alpha': 1.5788099562595347e-07, 'reg_lambda': 7.065756158441211e-05, 'max_delta_step': 6}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  64%|██████▍   | 129/200 [01:21<00:35,  2.02it/s]

[I 2025-11-10 14:17:00,817] Trial 127 finished with value: 0.6361988304093568 and parameters: {'max_depth': 6, 'learning_rate': 0.11620479295013517, 'n_estimators': 225, 'subsample': 0.9715856570100032, 'colsample_bytree': 0.5602528124397486, 'min_child_weight': 5, 'gamma': 3.069028227741364, 'reg_alpha': 1.810604795504649e-07, 'reg_lambda': 1.09940942516873e-07, 'max_delta_step': 8}. Best is trial 114 with value: 0.6906432748538012.
[I 2025-11-10 14:17:00,975] Trial 126 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.11475220207762175, 'n_estimators': 331, 'subsample': 0.9991062220073157, 'colsample_bytree': 0.6362159160254424, 'min_child_weight': 5, 'gamma': 3.722078288861246, 'reg_alpha': 1.6226061889940514e-07, 'reg_lambda': 6.303365251045767e-05, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  65%|██████▌   | 130/200 [01:21<00:31,  2.19it/s]

[I 2025-11-10 14:17:01,319] Trial 131 pruned.

Best trial: 114. Best value: 0.690643:  66%|██████▌   | 132/200 [01:21<00:21,  3.14it/s]

[I 2025-11-10 14:17:01,554] Trial 129 pruned.
[I 2025-11-10 14:17:01,679] Trial 130 pruned.
[I 2025-11-10 14:17:01,679] Trial 133 pruned.

Best trial: 114. Best value: 0.690643:  67%|██████▋   | 134/200 [01:22<00:21,  3.05it/s]

[I 2025-11-10 14:17:02,343] Trial 132 pruned.

Best trial: 114. Best value: 0.690643:  68%|██████▊   | 135/200 [01:22<00:21,  3.02it/s]

[I 2025-11-10 14:17:02,693] Trial 137 pruned.

Best trial: 114. Best value: 0.690643:  68%|██████▊   | 136/200 [01:23<00:22,  2.81it/s]

[I 2025-11-10 14:17:03,123] Trial 136 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.12706221403746037, 'n_estimators': 208, 'subsample': 0.9586448125896448, 'colsample_bytree': 0.683919635489856, 'min_child_weight': 5, 'gamma': 4.418703492170798, 'reg_alpha': 4.589481487493085e-08, 'reg_lambda': 9.006927630681882e-07, 'max_delta_step': 6}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  69%|██████▉   | 138/200 [01:23<00:17,  3.54it/s]

[I 2025-11-10 14:17:03,438] Trial 134 finished with value: 0.6906432748538012 and parameters: {'max_depth': 3, 'learning_rate': 0.18173361461709098, 'n_estimators': 263, 'subsample': 0.9857321613316761, 'colsample_bytree': 0.5750426986816988, 'min_child_weight': 5, 'gamma': 4.6476905502992665, 'reg_alpha': 2.6264020554825534e-07, 'reg_lambda': 2.1677540841484291e-07, 'max_delta_step': 6}. Best is trial 114 with value: 0.6906432748538012.
[I 2025-11-10 14:17:03,559] Trial 135 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.12629604728592006, 'n_estimators': 279, 'subsample': 0.9578683398126998, 'colsample_bytree': 0.6558282266958931, 'min_child_weight': 5, 'gamma': 4.070584127231555, 'reg_alpha': 0.000529272919243154, 'reg_lambda': 7.830177337082287e-07, 'max_delta_step': 6}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  70%|██████▉   | 139/200 [01:25<00:33,  1.85it/s]

[I 2025-11-10 14:17:04,754] Trial 139 pruned.

Best trial: 114. Best value: 0.690643:  70%|███████   | 141/200 [01:25<00:21,  2.75it/s]

[I 2025-11-10 14:17:04,959] Trial 141 finished with value: 0.6906432748538012 and parameters: {'max_depth': 3, 'learning_rate': 0.1949456419151461, 'n_estimators': 250, 'subsample': 0.9867628250003022, 'colsample_bytree': 0.5443942435109054, 'min_child_weight': 5, 'gamma': 4.658278126843551, 'reg_alpha': 2.34662509863764e-08, 'reg_lambda': 3.5724012079752657e-07, 'max_delta_step': 7}. Best is trial 114 with value: 0.6906432748538012.
[I 2025-11-10 14:17:05,131] Trial 142 pruned.

Best trial: 114. Best value: 0.690643:  72%|███████▏  | 143/200 [01:25<00:15,  3.63it/s]

[I 2025-11-10 14:17:05,344] Trial 143 pruned.
[I 2025-11-10 14:17:05,514] Trial 140 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.17404740690596632, 'n_estimators': 365, 'subsample': 0.934900878298381, 'colsample_bytree': 0.5486238624177853, 'min_child_weight': 5, 'gamma': 4.6254001624345165, 'reg_alpha': 6.225364547681651e-07, 'reg_lambda': 2.638906538459531e-07, 'max_delta_step': 6}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  72%|███████▏  | 144/200 [01:26<00:21,  2.59it/s]

[I 2025-11-10 14:17:06,148] Trial 138 finished with value: 0.6345614035087719 and parameters: {'max_depth': 3, 'learning_rate': 0.12020911466746152, 'n_estimators': 635, 'subsample': 0.9353129824996471, 'colsample_bytree': 0.5438013708803642, 'min_child_weight': 5, 'gamma': 4.080493743400567, 'reg_alpha': 5.590127601833737e-07, 'reg_lambda': 8.925606010236904e-07, 'max_delta_step': 6}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  73%|███████▎  | 146/200 [01:26<00:15,  3.38it/s]

[I 2025-11-10 14:17:06,410] Trial 144 finished with value: 0.6906432748538012 and parameters: {'max_depth': 3, 'learning_rate': 0.19138368881898724, 'n_estimators': 200, 'subsample': 0.9705979464402678, 'colsample_bytree': 0.5671431793853638, 'min_child_weight': 5, 'gamma': 4.650647220222705, 'reg_alpha': 2.3966029937741597e-08, 'reg_lambda': 5.945786873982325e-08, 'max_delta_step': 7}. Best is trial 114 with value: 0.6906432748538012.
[I 2025-11-10 14:17:06,576] Trial 145 finished with value: 0.6906432748538012 and parameters: {'max_depth': 3, 'learning_rate': 0.2167228846704578, 'n_estimators': 200, 'subsample': 0.9692673679959947, 'colsample_bytree': 0.5012035786201265, 'min_child_weight': 5, 'gamma': 4.770969172451779, 'reg_alpha': 2.457413743488405e-08, 'reg_lambda': 5.912311718339312e-06, 'max_delta_step': 6}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  74%|███████▎  | 147/200 [01:26<00:12,  4.14it/s]

[I 2025-11-10 14:17:06,694] Trial 147 pruned.

Best trial: 114. Best value: 0.690643:  74%|███████▍  | 148/200 [01:27<00:11,  4.35it/s]

[I 2025-11-10 14:17:06,900] Trial 148 pruned.

Best trial: 114. Best value: 0.690643:  74%|███████▍  | 149/200 [01:27<00:18,  2.80it/s]

[I 2025-11-10 14:17:07,553] Trial 146 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.21038204377126787, 'n_estimators': 309, 'subsample': 0.967694460931578, 'colsample_bytree': 0.514220865722712, 'min_child_weight': 5, 'gamma': 4.754444121287381, 'reg_alpha': 1.7033432493960084e-08, 'reg_lambda': 0.05977419107370191, 'max_delta_step': 7}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  76%|███████▌  | 151/200 [01:28<00:14,  3.44it/s]

[I 2025-11-10 14:17:07,886] Trial 152 pruned.
[I 2025-11-10 14:17:08,030] Trial 149 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.2387620981057522, 'n_estimators': 200, 'subsample': 0.9658813246483978, 'colsample_bytree': 0.5177874203449676, 'min_child_weight': 5, 'gamma': 4.777732278875022, 'reg_alpha': 2.4921126466996318e-08, 'reg_lambda': 6.235657887230626e-08, 'max_delta_step': 7}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  76%|███████▋  | 153/200 [01:28<00:09,  5.07it/s]

[I 2025-11-10 14:17:08,139] Trial 150 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.20232243816088896, 'n_estimators': 200, 'subsample': 0.9684551224269704, 'colsample_bytree': 0.5206887771641795, 'min_child_weight': 5, 'gamma': 4.765509346021616, 'reg_alpha': 2.3519225698897432e-08, 'reg_lambda': 2.9909446152778145e-05, 'max_delta_step': 8}. Best is trial 114 with value: 0.6906432748538012.
[I 2025-11-10 14:17:08,246] Trial 153 pruned.

Best trial: 114. Best value: 0.690643:  78%|███████▊  | 156/200 [01:28<00:06,  6.72it/s]

[I 2025-11-10 14:17:08,479] Trial 151 finished with value: 0.6884210526315789 and parameters: {'max_depth': 3, 'learning_rate': 0.21905588941480794, 'n_estimators': 226, 'subsample': 0.9638865599938166, 'colsample_bytree': 0.516638627694202, 'min_child_weight': 5, 'gamma': 4.776131553760008, 'reg_alpha': 1.481322627893073e-08, 'reg_lambda': 3.463002929925826e-06, 'max_delta_step': 7}. Best is trial 114 with value: 0.6906432748538012.
[I 2025-11-10 14:17:08,559] Trial 154 pruned.
[I 2025-11-10 14:17:08,642] Trial 155 pruned.

Best trial: 114. Best value: 0.690643:  79%|███████▉  | 158/200 [01:29<00:07,  5.85it/s]

[I 2025-11-10 14:17:08,899] Trial 157 pruned.
[I 2025-11-10 14:17:09,059] Trial 159 pruned.

Best trial: 114. Best value: 0.690643:  80%|███████▉  | 159/200 [01:29<00:08,  5.06it/s]

[I 2025-11-10 14:17:09,330] Trial 160 pruned.

Best trial: 114. Best value: 0.690643:  80%|████████  | 160/200 [01:30<00:12,  3.23it/s]

[I 2025-11-10 14:17:09,923] Trial 156 finished with value: 0.638421052631579 and parameters: {'max_depth': 4, 'learning_rate': 0.21982484589928208, 'n_estimators': 247, 'subsample': 0.9842887005647023, 'colsample_bytree': 0.5963717689589031, 'min_child_weight': 5, 'gamma': 4.5374664329209775, 'reg_alpha': 2.8272963401440945e-07, 'reg_lambda': 1.5627121433738245e-07, 'max_delta_step': 2}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  80%|████████  | 161/200 [01:30<00:12,  3.25it/s]

[I 2025-11-10 14:17:10,230] Trial 158 finished with value: 0.6884210526315789 and parameters: {'max_depth': 3, 'learning_rate': 0.2184183938802413, 'n_estimators': 274, 'subsample': 0.9561491171622706, 'colsample_bytree': 0.536610031191313, 'min_child_weight': 5, 'gamma': 4.511786905531017, 'reg_alpha': 1.3267738660674063e-08, 'reg_lambda': 2.9169177911471756e-06, 'max_delta_step': 7}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  81%|████████  | 162/200 [01:30<00:13,  2.82it/s]

[I 2025-11-10 14:17:10,692] Trial 162 pruned.

Best trial: 114. Best value: 0.690643:  82%|████████▏ | 163/200 [01:31<00:14,  2.49it/s]

[I 2025-11-10 14:17:11,209] Trial 163 finished with value: 0.6906432748538012 and parameters: {'max_depth': 4, 'learning_rate': 0.2562670876798537, 'n_estimators': 230, 'subsample': 0.9793400850290186, 'colsample_bytree': 0.6004023723334646, 'min_child_weight': 5, 'gamma': 4.604308563576581, 'reg_alpha': 3.6668590553871133e-05, 'reg_lambda': 2.7643130245840777e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  82%|████████▏ | 164/200 [01:31<00:14,  2.46it/s]

[I 2025-11-10 14:17:11,626] Trial 164 pruned.

Best trial: 114. Best value: 0.690643:  82%|████████▎ | 165/200 [01:32<00:15,  2.32it/s]

[I 2025-11-10 14:17:12,115] Trial 165 finished with value: 0.6361988304093568 and parameters: {'max_depth': 4, 'learning_rate': 0.21489116293707256, 'n_estimators': 229, 'subsample': 0.9611513998302249, 'colsample_bytree': 0.9292430046155196, 'min_child_weight': 5, 'gamma': 4.254289757647078, 'reg_alpha': 3.760481768524151e-08, 'reg_lambda': 6.981601595651434e-06, 'max_delta_step': 3}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  83%|████████▎ | 166/200 [01:33<00:16,  2.02it/s]

[I 2025-11-10 14:17:12,761] Trial 166 finished with value: 0.6339766081871345 and parameters: {'max_depth': 4, 'learning_rate': 0.2104983923508729, 'n_estimators': 269, 'subsample': 0.9634427338304946, 'colsample_bytree': 0.5895741669325598, 'min_child_weight': 5, 'gamma': 4.644391900548821, 'reg_alpha': 1.3749634655590092e-08, 'reg_lambda': 8.412662714399574e-06, 'max_delta_step': 1}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  84%|████████▎ | 167/200 [01:33<00:13,  2.43it/s]

[I 2025-11-10 14:17:12,976] Trial 167 finished with value: 0.6884210526315789 and parameters: {'max_depth': 3, 'learning_rate': 0.253811882340726, 'n_estimators': 227, 'subsample': 0.9623200667856402, 'colsample_bytree': 0.5994919489509389, 'min_child_weight': 5, 'gamma': 4.361880038360386, 'reg_alpha': 0.0001085753474249806, 'reg_lambda': 8.737611662337109e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  84%|████████▍ | 168/200 [01:33<00:15,  2.03it/s]

[I 2025-11-10 14:17:13,660] Trial 168 finished with value: 0.6361988304093568 and parameters: {'max_depth': 6, 'learning_rate': 0.24041652406342698, 'n_estimators': 269, 'subsample': 0.946530839674773, 'colsample_bytree': 0.6186875976851469, 'min_child_weight': 5, 'gamma': 4.410361028115457, 'reg_alpha': 0.00010114900447454197, 'reg_lambda': 3.7097304220813718e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  84%|████████▍ | 169/200 [01:34<00:18,  1.71it/s]

[I 2025-11-10 14:17:14,463] Trial 170 finished with value: 0.6817543859649123 and parameters: {'max_depth': 3, 'learning_rate': 0.2385381878652297, 'n_estimators': 231, 'subsample': 0.944424124650695, 'colsample_bytree': 0.5221014518599574, 'min_child_weight': 5, 'gamma': 4.38592863559164, 'reg_alpha': 3.4249912192531434e-05, 'reg_lambda': 1.6558302204413776e-05, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  85%|████████▌ | 170/200 [01:35<00:19,  1.57it/s]

[I 2025-11-10 14:17:15,218] Trial 171 finished with value: 0.6906432748538012 and parameters: {'max_depth': 3, 'learning_rate': 0.25566386900043414, 'n_estimators': 230, 'subsample': 0.9257235265806643, 'colsample_bytree': 0.5268113254218243, 'min_child_weight': 5, 'gamma': 4.290456128561088, 'reg_alpha': 3.941807625616261e-05, 'reg_lambda': 2.2349417479997313e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  86%|████████▌ | 171/200 [01:35<00:15,  1.91it/s]

[I 2025-11-10 14:17:15,482] Trial 173 pruned.

Best trial: 114. Best value: 0.690643:  86%|████████▌ | 172/200 [01:36<00:12,  2.19it/s]

[I 2025-11-10 14:17:15,780] Trial 172 finished with value: 0.67953216374269 and parameters: {'max_depth': 3, 'learning_rate': 0.2749880641918644, 'n_estimators': 230, 'subsample': 0.9511378345897443, 'colsample_bytree': 0.5260561507060703, 'min_child_weight': 5, 'gamma': 4.35020897369006, 'reg_alpha': 3.353033927956225e-05, 'reg_lambda': 2.266818379198746e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  86%|████████▋ | 173/200 [01:36<00:11,  2.43it/s]

[I 2025-11-10 14:17:16,068] Trial 175 pruned.

Best trial: 114. Best value: 0.690643:  87%|████████▋ | 174/200 [01:37<00:14,  1.80it/s]

[I 2025-11-10 14:17:16,977] Trial 161 finished with value: 0.6139766081871345 and parameters: {'max_depth': 3, 'learning_rate': 0.26360668968493595, 'n_estimators': 1351, 'subsample': 0.9429200740695884, 'colsample_bytree': 0.5956669674619978, 'min_child_weight': 4, 'gamma': 4.631874130041586, 'reg_alpha': 8.463663354683017e-05, 'reg_lambda': 1.2421057335189427e-05, 'max_delta_step': 6}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  88%|████████▊ | 175/200 [01:37<00:14,  1.72it/s]

[I 2025-11-10 14:17:17,619] Trial 176 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.2544789793433648, 'n_estimators': 305, 'subsample': 0.9296785704809941, 'colsample_bytree': 0.527092002470511, 'min_child_weight': 5, 'gamma': 4.376016740348396, 'reg_alpha': 5.6674249690716365e-05, 'reg_lambda': 1.969458561213237e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  88%|████████▊ | 176/200 [01:38<00:15,  1.60it/s]

[I 2025-11-10 14:17:18,344] Trial 177 finished with value: 0.61953216374269 and parameters: {'max_depth': 3, 'learning_rate': 0.25242901032459086, 'n_estimators': 297, 'subsample': 0.9298199145227867, 'colsample_bytree': 0.5258442626553378, 'min_child_weight': 5, 'gamma': 4.3095131543510785, 'reg_alpha': 4.4034591540642545e-05, 'reg_lambda': 2.7355921305616342e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  88%|████████▊ | 177/200 [01:38<00:12,  1.83it/s]

[I 2025-11-10 14:17:18,704] Trial 178 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.23831996538176659, 'n_estimators': 223, 'subsample': 0.9518811301938096, 'colsample_bytree': 0.5171159855381355, 'min_child_weight': 5, 'gamma': 4.2758371006945, 'reg_alpha': 3.549276648440127e-05, 'reg_lambda': 4.216023971874484e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  89%|████████▉ | 178/200 [01:39<00:13,  1.65it/s]

[I 2025-11-10 14:17:19,455] Trial 179 finished with value: 0.6906432748538012 and parameters: {'max_depth': 3, 'learning_rate': 0.23663260795231428, 'n_estimators': 224, 'subsample': 0.9516059210502472, 'colsample_bytree': 0.5405905355387309, 'min_child_weight': 5, 'gamma': 4.469436607982415, 'reg_alpha': 0.00019636096920198494, 'reg_lambda': 4.818330136319833e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  90%|████████▉ | 179/200 [01:40<00:11,  1.90it/s]

[I 2025-11-10 14:17:19,794] Trial 181 pruned.

Best trial: 114. Best value: 0.690643:  90%|█████████ | 180/200 [01:40<00:09,  2.21it/s]

[I 2025-11-10 14:17:20,075] Trial 169 finished with value: 0.6273099415204679 and parameters: {'max_depth': 5, 'learning_rate': 0.23888464007998086, 'n_estimators': 1446, 'subsample': 0.9433865137668291, 'colsample_bytree': 0.5260871035122411, 'min_child_weight': 5, 'gamma': 4.410838624275693, 'reg_alpha': 3.727389946696809e-05, 'reg_lambda': 3.0185131417635724e-06, 'max_delta_step': 1}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  90%|█████████ | 181/200 [01:40<00:07,  2.48it/s]

[I 2025-11-10 14:17:20,348] Trial 180 finished with value: 0.5973099415204679 and parameters: {'max_depth': 3, 'learning_rate': 0.23402284009995053, 'n_estimators': 270, 'subsample': 0.9381104114913501, 'colsample_bytree': 0.5394872532959775, 'min_child_weight': 5, 'gamma': 4.491218735656893, 'reg_alpha': 0.0001668873857638285, 'reg_lambda': 2.5515742478032694e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  91%|█████████ | 182/200 [01:41<00:07,  2.56it/s]

[I 2025-11-10 14:17:20,703] Trial 174 finished with value: 0.6617543859649123 and parameters: {'max_depth': 3, 'learning_rate': 0.25809489130645086, 'n_estimators': 970, 'subsample': 0.925698063846398, 'colsample_bytree': 0.5274970272254309, 'min_child_weight': 5, 'gamma': 4.390273771067039, 'reg_alpha': 6.658219606786525e-05, 'reg_lambda': 2.4775148486642247e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  92%|█████████▏| 183/200 [01:42<00:12,  1.33it/s]

[I 2025-11-10 14:17:22,323] Trial 182 finished with value: 0.6906432748538012 and parameters: {'max_depth': 3, 'learning_rate': 0.229422179310488, 'n_estimators': 200, 'subsample': 0.9696467479302526, 'colsample_bytree': 0.5104906901761874, 'min_child_weight': 5, 'gamma': 4.16286295743057, 'reg_alpha': 0.00023591860589882303, 'reg_lambda': 7.541366139693175e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  92%|█████████▎| 185/200 [01:43<00:07,  1.99it/s]

[I 2025-11-10 14:17:22,711] Trial 183 finished with value: 0.6228654970760235 and parameters: {'max_depth': 3, 'learning_rate': 0.22848709799462286, 'n_estimators': 223, 'subsample': 0.960619462856587, 'colsample_bytree': 0.5107685362478463, 'min_child_weight': 5, 'gamma': 4.150252342426364, 'reg_alpha': 0.00011265785658475156, 'reg_lambda': 6.996024294393356e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.
[I 2025-11-10 14:17:22,886] Trial 184 finished with value: 0.6339766081871345 and parameters: {'max_depth': 3, 'learning_rate': 0.27044869279927103, 'n_estimators': 225, 'subsample': 0.9555934544456176, 'colsample_bytree': 0.5516407075281594, 'min_child_weight': 5, 'gamma': 4.6813678197427, 'reg_alpha': 0.0002474509948930954, 'reg_lambda': 6.185240084494315e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  93%|█████████▎| 186/200 [01:43<00:05,  2.39it/s]

[I 2025-11-10 14:17:23,109] Trial 187 pruned.

Best trial: 114. Best value: 0.690643:  94%|█████████▎| 187/200 [01:43<00:04,  2.63it/s]

[I 2025-11-10 14:17:23,398] Trial 189 pruned.

Best trial: 114. Best value: 0.690643:  94%|█████████▍| 188/200 [01:44<00:05,  2.30it/s]

[I 2025-11-10 14:17:23,954] Trial 188 pruned.

Best trial: 114. Best value: 0.690643:  94%|█████████▍| 189/200 [01:45<00:06,  1.82it/s]

[I 2025-11-10 14:17:24,775] Trial 190 finished with value: 0.6339766081871345 and parameters: {'max_depth': 3, 'learning_rate': 0.24953524767036028, 'n_estimators': 254, 'subsample': 0.9679479731530343, 'colsample_bytree': 0.5351427338069156, 'min_child_weight': 5, 'gamma': 4.200204805765227, 'reg_alpha': 0.00025357354978317286, 'reg_lambda': 1.0032678087952663e-05, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  95%|█████████▌| 190/200 [01:45<00:05,  1.95it/s]

[I 2025-11-10 14:17:25,200] Trial 192 pruned.

Best trial: 114. Best value: 0.690643:  96%|█████████▌| 191/200 [01:45<00:04,  2.17it/s]

[I 2025-11-10 14:17:25,544] Trial 191 finished with value: 0.6339766081871345 and parameters: {'max_depth': 3, 'learning_rate': 0.25302204134239964, 'n_estimators': 253, 'subsample': 0.9697062843252859, 'colsample_bytree': 0.5347958412266268, 'min_child_weight': 5, 'gamma': 4.587431284979284, 'reg_alpha': 2.5491504385910033e-05, 'reg_lambda': 4.195934531694666e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  96%|█████████▋| 193/200 [01:47<00:03,  1.91it/s]

[I 2025-11-10 14:17:26,726] Trial 194 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.028810564953753195, 'n_estimators': 223, 'subsample': 0.9491748079861931, 'colsample_bytree': 0.560142028876056, 'min_child_weight': 5, 'gamma': 4.360355367935015, 'reg_alpha': 0.00020042739824249964, 'reg_lambda': 2.156188823742122e-05, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.
[I 2025-11-10 14:17:26,893] Trial 185 finished with value: 0.6884210526315789 and parameters: {'max_depth': 3, 'learning_rate': 0.2683955219012878, 'n_estimators': 977, 'subsample': 0.9592721387650662, 'colsample_bytree': 0.511011151305251, 'min_child_weight': 5, 'gamma': 4.187577618599446, 'reg_alpha': 0.0002366787457018521, 'reg_lambda': 5.416047907985971e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  98%|█████████▊| 195/200 [01:47<00:01,  3.08it/s]

[I 2025-11-10 14:17:27,042] Trial 195 pruned.
[I 2025-11-10 14:17:27,161] Trial 193 finished with value: 0.5894736842105264 and parameters: {'max_depth': 3, 'learning_rate': 0.22694049488567816, 'n_estimators': 249, 'subsample': 0.9663185842483883, 'colsample_bytree': 0.5345031918886227, 'min_child_weight': 3, 'gamma': 4.341496237879958, 'reg_alpha': 0.0001581597052222418, 'reg_lambda': 4.882948747498803e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  98%|█████████▊| 196/200 [01:47<00:01,  3.02it/s]

[I 2025-11-10 14:17:27,513] Trial 186 finished with value: 0.6250877192982457 and parameters: {'max_depth': 3, 'learning_rate': 0.26921316630790876, 'n_estimators': 959, 'subsample': 0.968636909975183, 'colsample_bytree': 0.5107017022126001, 'min_child_weight': 5, 'gamma': 3.9310167422916003, 'reg_alpha': 0.00023159600304896723, 'reg_lambda': 5.103725935464993e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  98%|█████████▊| 197/200 [01:48<00:01,  2.23it/s]

[I 2025-11-10 14:17:28,225] Trial 197 finished with value: 0.6217543859649123 and parameters: {'max_depth': 3, 'learning_rate': 0.2723460610566419, 'n_estimators': 200, 'subsample': 0.9613105853756093, 'colsample_bytree': 0.5225983509106468, 'min_child_weight': 5, 'gamma': 4.303555670628619, 'reg_alpha': 0.00032351827667345516, 'reg_lambda': 2.663109946158255e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643:  99%|█████████▉| 198/200 [01:50<00:02,  1.03s/it]

[I 2025-11-10 14:17:30,608] Trial 198 finished with value: 0.6884210526315789 and parameters: {'max_depth': 3, 'learning_rate': 0.26751332033013375, 'n_estimators': 977, 'subsample': 0.9571617778759453, 'colsample_bytree': 0.5218813280601826, 'min_child_weight': 5, 'gamma': 4.846757778566637, 'reg_alpha': 0.0002856922024544684, 'reg_lambda': 2.196432747885782e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.
[I 2025-11-10 14:17:30,660] Trial 196 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.22446120856331372, 'n_estimators': 1044, 'subsample': 0.9588399826685036, 'colsample_bytree': 0.5019376483752032, 'min_child_weight': 5, 'gamma': 3.980824114184415, 'reg_alpha': 0.0001246394844679264, 'reg_lambda': 2.4294565459314686e-06, 'max_delta_step': 1}. Best is trial 114 with value: 0.6906432748538012.

Best trial: 114. Best value: 0.690643: 100%|██████████| 200/200 [01:51<00:00,  1.80it/s]

[I 2025-11-10 14:17:30,902] Trial 199 finished with value: 0.6361988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.24912972618806736, 'n_estimators': 1024, 'subsample': 0.9570833881194057, 'colsample_bytree': 0.5008546365313096, 'min_child_weight': 5, 'gamma': 4.2288922942321525, 'reg_alpha': 0.00037145462754191314, 'reg_lambda': 2.5990094763440157e-06, 'max_delta_step': 0}. Best is trial 114 with value: 0.6906432748538012.

[I 2025-11-10 14:17:31,723] A new study created in memory with name: 3_4_balanced_accuracy
Best trial: 0. Best value: 0.5:   0%|          | 1/200 [00:01<06:28,  1.95s/it]

[I 2025-11-10 14:17:33,673] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.15737309324855553, 'n_estimators': 345, 'subsample': 0.5556733481251355, 'colsample_bytree': 0.8582517176885047, 'min_child_weight': 2, 'gamma': 3.566453506888025, 'reg_alpha': 8.718960576743687, 'reg_lambda': 3.467551865770755e-06, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.
[I 2025-11-10 14:17:33,704] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.020788439164351847, 'n_estimators': 454, 'subsample': 0.8686723507089974, 'colsample_bytree': 0.6651567041294043, 'min_child_weight': 6, 'gamma': 0.7270408040536025, 'reg_alpha': 2.335702836710584e-08, 'reg_lambda': 0.006384350839284805, 'max_delta_step': 10}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   2%|▏         | 3/200 [00:02<01:57,  1.67it/s]

[I 2025-11-10 14:17:33,925] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.28638297928768414, 'n_estimators': 522, 'subsample': 0.9417662930529803, 'colsample_bytree': 0.5048020840988415, 'min_child_weight': 7, 'gamma': 3.876100175650335, 'reg_alpha': 5.9060042348521785e-08, 'reg_lambda': 0.019992288083294604, 'max_delta_step': 2}. Best is trial 0 with value: 0.5.

Best trial: 3. Best value: 0.549766:   2%|▏         | 4/200 [00:03<03:01,  1.08it/s]

[I 2025-11-10 14:17:35,466] Trial 3 finished with value: 0.549766081871345 and parameters: {'max_depth': 7, 'learning_rate': 0.022759470207161726, 'n_estimators': 462, 'subsample': 0.8793123583264848, 'colsample_bytree': 0.9384678703422781, 'min_child_weight': 2, 'gamma': 2.839451827031768, 'reg_alpha': 4.8462023143271734e-05, 'reg_lambda': 0.039229512014317895, 'max_delta_step': 4}. Best is trial 3 with value: 0.549766081871345.

Best trial: 3. Best value: 0.549766:   2%|▎         | 5/200 [00:04<02:58,  1.09it/s]

[I 2025-11-10 14:17:36,367] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2658470479622487, 'n_estimators': 574, 'subsample': 0.9875377193750343, 'colsample_bytree': 0.5494448424413383, 'min_child_weight': 6, 'gamma': 0.5402685541866775, 'reg_alpha': 1.0028142996839465e-06, 'reg_lambda': 0.0011001996299149024, 'max_delta_step': 5}. Best is trial 3 with value: 0.549766081871345.

Best trial: 4. Best value: 0.555614:   4%|▎         | 7/200 [00:05<02:04,  1.55it/s]

[I 2025-11-10 14:17:37,177] Trial 4 finished with value: 0.5556140350877193 and parameters: {'max_depth': 7, 'learning_rate': 0.051380070104986256, 'n_estimators': 594, 'subsample': 0.5236517337715664, 'colsample_bytree': 0.5528569370631835, 'min_child_weight': 1, 'gamma': 3.0541536028973795, 'reg_alpha': 0.17625102462515443, 'reg_lambda': 7.121926200037971e-06, 'max_delta_step': 10}. Best is trial 4 with value: 0.5556140350877193.
[I 2025-11-10 14:17:37,296] Trial 7 finished with value: 0.46426900584795316 and parameters: {'max_depth': 6, 'learning_rate': 0.035363102235260936, 'n_estimators': 384, 'subsample': 0.6469449141017338, 'colsample_bytree': 0.6185401481327023, 'min_child_weight': 4, 'gamma': 2.840922483810116, 'reg_alpha': 0.31017398787000844, 'reg_lambda': 3.955060238130361e-06, 'max_delta_step': 8}. Best is trial 4 with value: 0.5556140350877193.

Best trial: 4. Best value: 0.555614:   4%|▍         | 8/200 [00:08<04:11,  1.31s/it]

[I 2025-11-10 14:17:40,087] Trial 5 finished with value: 0.5278362573099415 and parameters: {'max_depth': 10, 'learning_rate': 0.06255051947572093, 'n_estimators': 1183, 'subsample': 0.5258268667656678, 'colsample_bytree': 0.5590909743597188, 'min_child_weight': 1, 'gamma': 4.408266915383584, 'reg_alpha': 1.4868170611262642e-08, 'reg_lambda': 4.3637899675497894e-05, 'max_delta_step': 9}. Best is trial 4 with value: 0.5556140350877193.

Best trial: 4. Best value: 0.555614:   4%|▍         | 9/200 [00:09<04:24,  1.39s/it]

[I 2025-11-10 14:17:41,648] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.07556387536873223, 'n_estimators': 985, 'subsample': 0.8041877751217645, 'colsample_bytree': 0.996936629043317, 'min_child_weight': 6, 'gamma': 2.285316302020746, 'reg_alpha': 0.00011925586238923466, 'reg_lambda': 1.3376621183641084, 'max_delta_step': 3}. Best is trial 4 with value: 0.5556140350877193.

Best trial: 4. Best value: 0.555614:   5%|▌         | 10/200 [00:10<03:47,  1.20s/it]

[I 2025-11-10 14:17:42,423] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.010458748695599247, 'n_estimators': 1227, 'subsample': 0.8150367136548333, 'colsample_bytree': 0.9127675439992108, 'min_child_weight': 8, 'gamma': 4.481246344396644, 'reg_alpha': 0.008970697847424412, 'reg_lambda': 3.2790958632834007e-06, 'max_delta_step': 8}. Best is trial 4 with value: 0.5556140350877193.

Best trial: 4. Best value: 0.555614:   6%|▌         | 11/200 [00:11<02:55,  1.07it/s]

[I 2025-11-10 14:17:42,725] Trial 8 finished with value: 0.49421052631578954 and parameters: {'max_depth': 10, 'learning_rate': 0.03232264045843624, 'n_estimators': 1149, 'subsample': 0.9897148148414905, 'colsample_bytree': 0.6422164754061616, 'min_child_weight': 3, 'gamma': 4.793530641462781, 'reg_alpha': 0.20003568397086977, 'reg_lambda': 5.5404640201342024e-08, 'max_delta_step': 6}. Best is trial 4 with value: 0.5556140350877193.

Best trial: 4. Best value: 0.555614:   6%|▌         | 12/200 [00:13<04:49,  1.54s/it]

[I 2025-11-10 14:17:45,685] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.013272379318997678, 'n_estimators': 1339, 'subsample': 0.6016297327837455, 'colsample_bytree': 0.690625450868783, 'min_child_weight': 9, 'gamma': 4.750219910502153, 'reg_alpha': 1.8573351767176203e-08, 'reg_lambda': 1.8795522911906421e-06, 'max_delta_step': 4}. Best is trial 4 with value: 0.5556140350877193.
[I 2025-11-10 14:17:45,691] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.12634166093174887, 'n_estimators': 872, 'subsample': 0.9144399718954185, 'colsample_bytree': 0.8944384589682771, 'min_child_weight': 6, 'gamma': 4.628952698723305, 'reg_alpha': 7.946899270011039, 'reg_lambda': 1.5797599165874167e-05, 'max_delta_step': 1}. Best is trial 4 with value: 0.5556140350877193.

Best trial: 4. Best value: 0.555614:   7%|▋         | 14/200 [00:16<04:34,  1.48s/it]

[I 2025-11-10 14:17:48,489] Trial 13 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.11433515306712802, 'n_estimators': 1500, 'subsample': 0.6750623483325112, 'colsample_bytree': 0.7561059084018262, 'min_child_weight': 10, 'gamma': 1.5841008001773642, 'reg_alpha': 0.006724522486319572, 'reg_lambda': 1.0122538340539914e-08, 'max_delta_step': 0}. Best is trial 4 with value: 0.5556140350877193.

Best trial: 14. Best value: 0.566433:   8%|▊         | 15/200 [00:17<04:02,  1.31s/it]

[I 2025-11-10 14:17:49,299] Trial 14 finished with value: 0.5664327485380117 and parameters: {'max_depth': 7, 'learning_rate': 0.0151564153091196, 'n_estimators': 752, 'subsample': 0.6795151307198947, 'colsample_bytree': 0.7664016919870641, 'min_child_weight': 1, 'gamma': 1.7977473162279378, 'reg_alpha': 5.6429583983869886e-05, 'reg_lambda': 0.40239436585689814, 'max_delta_step': 0}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:   8%|▊         | 16/200 [00:18<04:05,  1.33s/it]

[I 2025-11-10 14:17:50,697] Trial 15 finished with value: 0.5553216374269007 and parameters: {'max_depth': 7, 'learning_rate': 0.03468750990604624, 'n_estimators': 674, 'subsample': 0.6925776882219499, 'colsample_bytree': 0.7806657005521949, 'min_child_weight': 1, 'gamma': 1.9519487621948806, 'reg_alpha': 6.27396905988786e-05, 'reg_lambda': 0.49815635743276643, 'max_delta_step': 7}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:   8%|▊         | 17/200 [00:19<03:14,  1.06s/it]

[I 2025-11-10 14:17:51,035] Trial 16 finished with value: 0.5386549707602339 and parameters: {'max_depth': 7, 'learning_rate': 0.03316393754181049, 'n_estimators': 707, 'subsample': 0.6871886517856693, 'colsample_bytree': 0.7977252857849454, 'min_child_weight': 1, 'gamma': 2.109502978837492, 'reg_alpha': 6.952025397493054e-05, 'reg_lambda': 0.7435674479213022, 'max_delta_step': 7}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:   9%|▉         | 18/200 [00:20<03:21,  1.11s/it]

[I 2025-11-10 14:17:52,249] Trial 18 finished with value: 0.48953216374269004 and parameters: {'max_depth': 6, 'learning_rate': 0.04194209766455994, 'n_estimators': 704, 'subsample': 0.7093546427826722, 'colsample_bytree': 0.7900932361616856, 'min_child_weight': 4, 'gamma': 1.7568231896681865, 'reg_alpha': 5.8635902918140415e-06, 'reg_lambda': 8.196841980273138, 'max_delta_step': 0}. Best is trial 14 with value: 0.5664327485380117.
[I 2025-11-10 14:17:52,318] Trial 19 finished with value: 0.5025730994152047 and parameters: {'max_depth': 6, 'learning_rate': 0.020124283913242627, 'n_estimators': 203, 'subsample': 0.7292194721134646, 'colsample_bytree': 0.79292462708848, 'min_child_weight': 3, 'gamma': 1.551972614723571, 'reg_alpha': 1.919825724041966e-06, 'reg_lambda': 0.00018306416528239235, 'max_delta_step': 10}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:  10%|█         | 21/200 [00:22<02:09,  1.38it/s]

[I 2025-11-10 14:17:53,626] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.017478905288125037, 'n_estimators': 250, 'subsample': 0.5739572157681324, 'colsample_bytree': 0.7143559654736865, 'min_child_weight': 4, 'gamma': 0.9938882568017178, 'reg_alpha': 0.0022232434231236266, 'reg_lambda': 0.0002728748078717746, 'max_delta_step': 10}. Best is trial 14 with value: 0.5664327485380117.
[I 2025-11-10 14:17:53,726] Trial 17 finished with value: 0.5242105263157896 and parameters: {'max_depth': 7, 'learning_rate': 0.0334129665094384, 'n_estimators': 684, 'subsample': 0.7310498117609545, 'colsample_bytree': 0.7912315870827763, 'min_child_weight': 1, 'gamma': 3.003210352882199, 'reg_alpha': 6.401635268637055e-05, 'reg_lambda': 0.4773000240655232, 'max_delta_step': 7}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:  11%|█         | 22/200 [00:22<02:14,  1.33it/s]

[I 2025-11-10 14:17:54,578] Trial 23 pruned.

Best trial: 14. Best value: 0.566433:  12%|█▏        | 23/200 [00:23<01:54,  1.54it/s]

[I 2025-11-10 14:17:54,932] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.016662789830393855, 'n_estimators': 814, 'subsample': 0.5013834905736618, 'colsample_bytree': 0.8416298916959962, 'min_child_weight': 4, 'gamma': 1.1548434521347117, 'reg_alpha': 2.898893027427182e-06, 'reg_lambda': 0.00040760259233871667, 'max_delta_step': 10}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:  12%|█▏        | 24/200 [00:24<02:33,  1.15it/s]

[I 2025-11-10 14:17:56,375] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.08424006609215058, 'n_estimators': 901, 'subsample': 0.5012292963138698, 'colsample_bytree': 0.5935867354505497, 'min_child_weight': 4, 'gamma': 1.1297940927257542, 'reg_alpha': 0.0016044474618378687, 'reg_lambda': 1.1236840870984867e-07, 'max_delta_step': 2}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:  12%|█▎        | 25/200 [00:26<02:58,  1.02s/it]

[I 2025-11-10 14:17:57,771] Trial 25 finished with value: 0.48619883040935674 and parameters: {'max_depth': 5, 'learning_rate': 0.046569439794151866, 'n_estimators': 636, 'subsample': 0.6258821680692157, 'colsample_bytree': 0.7310240185109174, 'min_child_weight': 3, 'gamma': 3.4222420341170867, 'reg_alpha': 0.0003624022998834024, 'reg_lambda': 0.12238955315568331, 'max_delta_step': 8}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:  13%|█▎        | 26/200 [00:26<02:34,  1.13it/s]

[I 2025-11-10 14:17:58,335] Trial 24 finished with value: 0.43532163742690055 and parameters: {'max_depth': 9, 'learning_rate': 0.047546353955377256, 'n_estimators': 825, 'subsample': 0.6272195941815495, 'colsample_bytree': 0.7337772138442163, 'min_child_weight': 2, 'gamma': 0.027759298213885675, 'reg_alpha': 0.0010477598699120403, 'reg_lambda': 0.14139806576083713, 'max_delta_step': 8}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:  14%|█▎        | 27/200 [00:27<02:22,  1.21it/s]

[I 2025-11-10 14:17:59,013] Trial 26 finished with value: 0.5042105263157896 and parameters: {'max_depth': 5, 'learning_rate': 0.051226186129754936, 'n_estimators': 598, 'subsample': 0.6235327329055564, 'colsample_bytree': 0.727338733464157, 'min_child_weight': 1, 'gamma': 3.313363766268878, 'reg_alpha': 0.0006785286854828763, 'reg_lambda': 0.15082998630716127, 'max_delta_step': 8}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:  14%|█▍        | 28/200 [00:28<02:49,  1.01it/s]

[I 2025-11-10 14:18:00,384] Trial 27 finished with value: 0.5189473684210526 and parameters: {'max_depth': 5, 'learning_rate': 0.05056420159858749, 'n_estimators': 592, 'subsample': 0.6384549056997347, 'colsample_bytree': 0.7259601680522523, 'min_child_weight': 1, 'gamma': 3.380462952744298, 'reg_alpha': 0.0008389860491824798, 'reg_lambda': 0.09135406489801728, 'max_delta_step': 8}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:  14%|█▍        | 29/200 [00:31<04:21,  1.53s/it]

[I 2025-11-10 14:18:03,203] Trial 28 finished with value: 0.5236842105263158 and parameters: {'max_depth': 9, 'learning_rate': 0.02715449644139912, 'n_estimators': 787, 'subsample': 0.7881171721841396, 'colsample_bytree': 0.7590932424680793, 'min_child_weight': 1, 'gamma': 2.09364727166259, 'reg_alpha': 2.2725617666167208e-07, 'reg_lambda': 9.820203715088386, 'max_delta_step': 5}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:  15%|█▌        | 30/200 [00:31<03:18,  1.17s/it]

[I 2025-11-10 14:18:03,515] Trial 29 finished with value: 0.5200584795321637 and parameters: {'max_depth': 5, 'learning_rate': 0.0264027107554237, 'n_estimators': 765, 'subsample': 0.7792125905747606, 'colsample_bytree': 0.6782778776027111, 'min_child_weight': 1, 'gamma': 2.0417680183049556, 'reg_alpha': 1.4768017698174166e-05, 'reg_lambda': 6.7634475086507395, 'max_delta_step': 5}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:  16%|█▌        | 31/200 [00:33<03:22,  1.20s/it]

[I 2025-11-10 14:18:04,780] Trial 30 finished with value: 0.5311695906432747 and parameters: {'max_depth': 7, 'learning_rate': 0.02707398822274922, 'n_estimators': 776, 'subsample': 0.770983055562448, 'colsample_bytree': 0.8408880714866275, 'min_child_weight': 1, 'gamma': 2.4753308610639833, 'reg_alpha': 1.2326179821470865e-05, 'reg_lambda': 5.64490483227067, 'max_delta_step': 5}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:  16%|█▌        | 32/200 [00:35<04:12,  1.50s/it]

[I 2025-11-10 14:18:07,005] Trial 31 finished with value: 0.5000584795321638 and parameters: {'max_depth': 7, 'learning_rate': 0.026230503162935317, 'n_estimators': 1028, 'subsample': 0.769751449755795, 'colsample_bytree': 0.8405860358876852, 'min_child_weight': 2, 'gamma': 2.407486255072492, 'reg_alpha': 1.3261523786672097e-05, 'reg_lambda': 2.873444025863666, 'max_delta_step': 5}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:  16%|█▋        | 33/200 [00:37<04:35,  1.65s/it]

[I 2025-11-10 14:18:08,988] Trial 34 finished with value: 0.5530994152046784 and parameters: {'max_depth': 7, 'learning_rate': 0.013288067538695335, 'n_estimators': 484, 'subsample': 0.8526847441313238, 'colsample_bytree': 0.9191052433131532, 'min_child_weight': 2, 'gamma': 2.9400725684950935, 'reg_alpha': 3.318771500080737e-05, 'reg_lambda': 0.01530843828520263, 'max_delta_step': 4}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:  17%|█▋        | 34/200 [00:37<03:32,  1.28s/it]

[I 2025-11-10 14:18:09,415] Trial 33 finished with value: 0.5170175438596492 and parameters: {'max_depth': 7, 'learning_rate': 0.012280707348509596, 'n_estimators': 1015, 'subsample': 0.5616503879056478, 'colsample_bytree': 0.8596812980778736, 'min_child_weight': 2, 'gamma': 3.8879541332941026, 'reg_alpha': 0.034938609406847135, 'reg_lambda': 0.005918856908596687, 'max_delta_step': 6}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:  18%|█▊        | 35/200 [00:37<02:40,  1.03it/s]

[I 2025-11-10 14:18:09,671] Trial 32 finished with value: 0.5045029239766082 and parameters: {'max_depth': 7, 'learning_rate': 0.01021724959936567, 'n_estimators': 1011, 'subsample': 0.5612682074717809, 'colsample_bytree': 0.8448601616342438, 'min_child_weight': 2, 'gamma': 2.5839213277996613, 'reg_alpha': 0.024128760246851424, 'reg_lambda': 0.004112630146093047, 'max_delta_step': 6}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:  18%|█▊        | 36/200 [00:39<02:52,  1.05s/it]

[I 2025-11-10 14:18:10,897] Trial 35 finished with value: 0.558654970760234 and parameters: {'max_depth': 7, 'learning_rate': 0.013488147956731054, 'n_estimators': 458, 'subsample': 0.85881330833025, 'colsample_bytree': 0.9094302123648796, 'min_child_weight': 2, 'gamma': 2.859470382904515, 'reg_alpha': 0.0001293035782534108, 'reg_lambda': 0.00580160726235888, 'max_delta_step': 3}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:  18%|█▊        | 37/200 [00:39<02:32,  1.07it/s]

[I 2025-11-10 14:18:11,576] Trial 39 pruned.

Best trial: 14. Best value: 0.566433:  19%|█▉        | 38/200 [00:40<02:08,  1.26it/s]

[I 2025-11-10 14:18:12,027] Trial 40 pruned.

Best trial: 14. Best value: 0.566433:  20%|██        | 40/200 [00:41<01:34,  1.69it/s]

[I 2025-11-10 14:18:12,859] Trial 37 finished with value: 0.5003508771929825 and parameters: {'max_depth': 8, 'learning_rate': 0.01492932062469585, 'n_estimators': 482, 'subsample': 0.8397728247268929, 'colsample_bytree': 0.9936645427411989, 'min_child_weight': 3, 'gamma': 3.835760962342105, 'reg_alpha': 4.483677483512679e-07, 'reg_lambda': 0.006567041468180544, 'max_delta_step': 3}. Best is trial 14 with value: 0.5664327485380117.
[I 2025-11-10 14:18:12,958] Trial 38 finished with value: 0.5278362573099414 and parameters: {'max_depth': 8, 'learning_rate': 0.014398383888981604, 'n_estimators': 468, 'subsample': 0.8386683991437235, 'colsample_bytree': 0.9682088672810553, 'min_child_weight': 3, 'gamma': 3.8450610253460256, 'reg_alpha': 2.4599970966630407, 'reg_lambda': 0.008165960603725677, 'max_delta_step': 3}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 14. Best value: 0.566433:  20%|██        | 41/200 [00:41<01:19,  2.01it/s]

[I 2025-11-10 14:18:13,233] Trial 42 pruned.

Best trial: 14. Best value: 0.566433:  21%|██        | 42/200 [00:41<01:07,  2.33it/s]

[I 2025-11-10 14:18:13,511] Trial 36 finished with value: 0.5419883040935672 and parameters: {'max_depth': 8, 'learning_rate': 0.010742204193343836, 'n_estimators': 475, 'subsample': 0.8417027978164833, 'colsample_bytree': 0.97944888703522, 'min_child_weight': 2, 'gamma': 3.8196958456054855, 'reg_alpha': 0.035740481301934184, 'reg_lambda': 0.006728346778925131, 'max_delta_step': 6}. Best is trial 14 with value: 0.5664327485380117.

Best trial: 41. Best value: 0.567544:  22%|██▏       | 43/200 [00:42<01:17,  2.03it/s]

[I 2025-11-10 14:18:14,139] Trial 41 finished with value: 0.5675438596491228 and parameters: {'max_depth': 8, 'learning_rate': 0.06707796363742162, 'n_estimators': 413, 'subsample': 0.9490985651279942, 'colsample_bytree': 0.5342432964265902, 'min_child_weight': 3, 'gamma': 2.6424271322035473, 'reg_alpha': 5.65706118038337e-07, 'reg_lambda': 0.3606335351234033, 'max_delta_step': 3}. Best is trial 41 with value: 0.5675438596491228.

Best trial: 41. Best value: 0.567544:  22%|██▏       | 44/200 [00:44<02:37,  1.01s/it]

[I 2025-11-10 14:18:16,362] Trial 46 finished with value: 0.5419883040935672 and parameters: {'max_depth': 9, 'learning_rate': 0.06550777814597257, 'n_estimators': 301, 'subsample': 0.941781443904306, 'colsample_bytree': 0.6487772091939645, 'min_child_weight': 1, 'gamma': 3.134034352403377, 'reg_alpha': 4.71023397205049e-08, 'reg_lambda': 0.3940677020751026, 'max_delta_step': 1}. Best is trial 41 with value: 0.5675438596491228.
[I 2025-11-10 14:18:16,402] Trial 43 finished with value: 0.5336842105263158 and parameters: {'max_depth': 9, 'learning_rate': 0.06375408444683013, 'n_estimators': 422, 'subsample': 0.9020509541795633, 'colsample_bytree': 0.8774588241497557, 'min_child_weight': 1, 'gamma': 2.699092353815283, 'reg_alpha': 0.00022754377757832692, 'reg_lambda': 0.036787529457928146, 'max_delta_step': 9}. Best is trial 41 with value: 0.5675438596491228.

Best trial: 41. Best value: 0.567544:  23%|██▎       | 46/200 [00:45<01:41,  1.52it/s]

[I 2025-11-10 14:18:16,848] Trial 44 finished with value: 0.5530994152046784 and parameters: {'max_depth': 7, 'learning_rate': 0.06140059758325595, 'n_estimators': 542, 'subsample': 0.9360119238060943, 'colsample_bytree': 0.8823286269210313, 'min_child_weight': 2, 'gamma': 3.11907107598622, 'reg_alpha': 3.7822391042584515e-05, 'reg_lambda': 0.01648487983753911, 'max_delta_step': 4}. Best is trial 41 with value: 0.5675438596491228.

Best trial: 41. Best value: 0.567544:  24%|██▍       | 48/200 [00:45<01:13,  2.06it/s]

[I 2025-11-10 14:18:17,351] Trial 49 pruned.
[I 2025-11-10 14:18:17,462] Trial 45 finished with value: 0.5173099415204678 and parameters: {'max_depth': 6, 'learning_rate': 0.01189029070128416, 'n_estimators': 306, 'subsample': 0.9572786239869421, 'colsample_bytree': 0.8946509497888919, 'min_child_weight': 1, 'gamma': 3.1128846297360653, 'reg_alpha': 2.1939276851498352e-05, 'reg_lambda': 0.01865624676129082, 'max_delta_step': 4}. Best is trial 41 with value: 0.5675438596491228.

Best trial: 41. Best value: 0.567544:  24%|██▍       | 49/200 [00:46<01:26,  1.74it/s]

[I 2025-11-10 14:18:18,280] Trial 50 pruned.

Best trial: 41. Best value: 0.567544:  25%|██▌       | 50/200 [00:47<01:24,  1.78it/s]

[I 2025-11-10 14:18:18,799] Trial 47 finished with value: 0.5639181286549707 and parameters: {'max_depth': 6, 'learning_rate': 0.06110701478899594, 'n_estimators': 404, 'subsample': 0.9575610854052208, 'colsample_bytree': 0.5371725015623413, 'min_child_weight': 2, 'gamma': 2.7394259814223147, 'reg_alpha': 1.5409931089949046e-07, 'reg_lambda': 1.1583844970105488, 'max_delta_step': 4}. Best is trial 41 with value: 0.5675438596491228.

Best trial: 48. Best value: 0.580585:  26%|██▌       | 51/200 [00:47<01:37,  1.53it/s]

[I 2025-11-10 14:18:19,684] Trial 48 finished with value: 0.5805847953216373 and parameters: {'max_depth': 6, 'learning_rate': 0.1046813724077516, 'n_estimators': 557, 'subsample': 0.9738954334249204, 'colsample_bytree': 0.5693698747345197, 'min_child_weight': 2, 'gamma': 1.4308308108564531, 'reg_alpha': 3.5379812149601997e-07, 'reg_lambda': 1.2864849958026958, 'max_delta_step': 4}. Best is trial 48 with value: 0.5805847953216373.

Best trial: 51. Best value: 0.580643:  26%|██▌       | 52/200 [00:48<01:47,  1.37it/s]

[I 2025-11-10 14:18:20,600] Trial 51 finished with value: 0.5806432748538011 and parameters: {'max_depth': 3, 'learning_rate': 0.2016677835329904, 'n_estimators': 729, 'subsample': 0.5424241004824912, 'colsample_bytree': 0.561859302902139, 'min_child_weight': 3, 'gamma': 4.126082407897997, 'reg_alpha': 0.004851072726062904, 'reg_lambda': 1.3091697391814525e-05, 'max_delta_step': 0}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  26%|██▋       | 53/200 [00:49<01:34,  1.56it/s]

[I 2025-11-10 14:18:21,024] Trial 53 finished with value: 0.4902923976608188 and parameters: {'max_depth': 6, 'learning_rate': 0.17625862968571565, 'n_estimators': 406, 'subsample': 0.9910011371631141, 'colsample_bytree': 0.5598236307858929, 'min_child_weight': 3, 'gamma': 2.7412663948095126, 'reg_alpha': 1.1038882283596338e-08, 'reg_lambda': 1.6888903618163373, 'max_delta_step': 3}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  27%|██▋       | 54/200 [00:49<01:21,  1.78it/s]

[I 2025-11-10 14:18:21,398] Trial 56 pruned.

Best trial: 51. Best value: 0.580643:  28%|██▊       | 55/200 [00:50<01:31,  1.58it/s]

[I 2025-11-10 14:18:22,196] Trial 54 finished with value: 0.5533918128654971 and parameters: {'max_depth': 3, 'learning_rate': 0.16443129202543696, 'n_estimators': 417, 'subsample': 0.9986172554263713, 'colsample_bytree': 0.5229566592357923, 'min_child_weight': 3, 'gamma': 1.466810354546311, 'reg_alpha': 7.930113355272108e-08, 'reg_lambda': 2.0524788938855747, 'max_delta_step': 3}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  28%|██▊       | 56/200 [00:50<01:19,  1.81it/s]

[I 2025-11-10 14:18:22,559] Trial 52 finished with value: 0.5111695906432748 and parameters: {'max_depth': 7, 'learning_rate': 0.03829189896895499, 'n_estimators': 642, 'subsample': 0.7437548678092677, 'colsample_bytree': 0.7012512490390345, 'min_child_weight': 2, 'gamma': 4.208041230781236, 'reg_alpha': 0.0043326821467580936, 'reg_lambda': 0.34930768732890777, 'max_delta_step': 3}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  28%|██▊       | 57/200 [00:51<01:17,  1.86it/s]

[I 2025-11-10 14:18:23,070] Trial 55 finished with value: 0.5286549707602339 and parameters: {'max_depth': 3, 'learning_rate': 0.2365884081400131, 'n_estimators': 404, 'subsample': 0.9944619493949695, 'colsample_bytree': 0.5170346225701458, 'min_child_weight': 3, 'gamma': 4.221962667725479, 'reg_alpha': 6.345329106419815e-08, 'reg_lambda': 1.9101697852300048, 'max_delta_step': 3}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  29%|██▉       | 58/200 [00:51<01:19,  1.78it/s]

[I 2025-11-10 14:18:23,689] Trial 60 pruned.

Best trial: 51. Best value: 0.580643:  30%|██▉       | 59/200 [00:52<01:09,  2.03it/s]

[I 2025-11-10 14:18:24,017] Trial 61 pruned.

Best trial: 51. Best value: 0.580643:  30%|███       | 60/200 [00:53<01:39,  1.40it/s]

[I 2025-11-10 14:18:25,250] Trial 57 finished with value: 0.5219883040935672 and parameters: {'max_depth': 3, 'learning_rate': 0.14493996610488646, 'n_estimators': 539, 'subsample': 0.8738769665154098, 'colsample_bytree': 0.6331458880215368, 'min_child_weight': 2, 'gamma': 4.113232117163934, 'reg_alpha': 6.031312242844733e-07, 'reg_lambda': 2.62433900255714, 'max_delta_step': 1}. Best is trial 51 with value: 0.5806432748538011.
[I 2025-11-10 14:18:25,335] Trial 59 finished with value: 0.54953216374269 and parameters: {'max_depth': 4, 'learning_rate': 0.12745896237303345, 'n_estimators': 543, 'subsample': 0.8800162367730336, 'colsample_bytree': 0.5786370730099626, 'min_child_weight': 5, 'gamma': 0.6756934449560981, 'reg_alpha': 3.4008230202020413e-06, 'reg_lambda': 5.912363173304303e-07, 'max_delta_step': 1}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  31%|███       | 62/200 [00:54<01:17,  1.78it/s]

[I 2025-11-10 14:18:26,020] Trial 58 finished with value: 0.5678362573099415 and parameters: {'max_depth': 4, 'learning_rate': 0.10672397001478488, 'n_estimators': 552, 'subsample': 0.9265697372582151, 'colsample_bytree': 0.6221810783946466, 'min_child_weight': 2, 'gamma': 4.141975608152791, 'reg_alpha': 0.00661080842129544, 'reg_lambda': 6.931419543865659e-05, 'max_delta_step': 1}. Best is trial 51 with value: 0.5806432748538011.
[I 2025-11-10 14:18:26,060] Trial 64 pruned.

Best trial: 51. Best value: 0.580643:  32%|███▏      | 64/200 [00:54<00:56,  2.39it/s]

[I 2025-11-10 14:18:26,414] Trial 63 pruned.

Best trial: 51. Best value: 0.580643:  32%|███▎      | 65/200 [00:55<01:00,  2.23it/s]

[I 2025-11-10 14:18:26,971] Trial 66 pruned.
[I 2025-11-10 14:18:26,998] Trial 65 pruned.

Best trial: 51. Best value: 0.580643:  34%|███▎      | 67/200 [00:55<00:44,  2.98it/s]

[I 2025-11-10 14:18:27,283] Trial 67 pruned.

Best trial: 51. Best value: 0.580643:  34%|███▍      | 68/200 [00:55<00:46,  2.82it/s]

[I 2025-11-10 14:18:27,704] Trial 69 pruned.

Best trial: 51. Best value: 0.580643:  34%|███▍      | 69/200 [00:56<00:52,  2.49it/s]

[I 2025-11-10 14:18:28,264] Trial 62 finished with value: 0.5605847953216374 and parameters: {'max_depth': 5, 'learning_rate': 0.07426206311875441, 'n_estimators': 534, 'subsample': 0.9721253185905326, 'colsample_bytree': 0.6195736184638722, 'min_child_weight': 2, 'gamma': 1.3211615695481749, 'reg_alpha': 1.728318051996299e-07, 'reg_lambda': 0.7651375887332166, 'max_delta_step': 2}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  35%|███▌      | 70/200 [00:56<00:45,  2.84it/s]

[I 2025-11-10 14:18:28,463] Trial 71 pruned.

Best trial: 51. Best value: 0.580643:  36%|███▌      | 72/200 [00:57<00:44,  2.91it/s]

[I 2025-11-10 14:18:29,104] Trial 72 pruned.
[I 2025-11-10 14:18:29,230] Trial 68 finished with value: 0.5475438596491228 and parameters: {'max_depth': 6, 'learning_rate': 0.055356810300741036, 'n_estimators': 353, 'subsample': 0.9355012328189558, 'colsample_bytree': 0.5674418487560032, 'min_child_weight': 3, 'gamma': 4.528068864275703, 'reg_alpha': 0.003484928516122641, 'reg_lambda': 0.0010090511451216046, 'max_delta_step': 0}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  36%|███▋      | 73/200 [00:57<00:37,  3.41it/s]

[I 2025-11-10 14:18:29,395] Trial 73 pruned.

Best trial: 51. Best value: 0.580643:  37%|███▋      | 74/200 [00:58<00:38,  3.27it/s]

[I 2025-11-10 14:18:29,729] Trial 74 pruned.

Best trial: 51. Best value: 0.580643:  38%|███▊      | 75/200 [00:58<00:45,  2.76it/s]

[I 2025-11-10 14:18:30,229] Trial 75 pruned.

Best trial: 51. Best value: 0.580643:  38%|███▊      | 76/200 [00:58<00:38,  3.21it/s]

[I 2025-11-10 14:18:30,421] Trial 70 finished with value: 0.5386549707602338 and parameters: {'max_depth': 6, 'learning_rate': 0.2051087961300602, 'n_estimators': 508, 'subsample': 0.9207899627074086, 'colsample_bytree': 0.6544230618765234, 'min_child_weight': 3, 'gamma': 3.555820646358576, 'reg_alpha': 0.0020461267832054763, 'reg_lambda': 0.000806493044475227, 'max_delta_step': 2}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  38%|███▊      | 77/200 [00:58<00:35,  3.43it/s]

[I 2025-11-10 14:18:30,665] Trial 77 pruned.

Best trial: 51. Best value: 0.580643:  40%|███▉      | 79/200 [00:59<00:35,  3.37it/s]

[I 2025-11-10 14:18:31,234] Trial 79 pruned.
[I 2025-11-10 14:18:31,347] Trial 78 pruned.

Best trial: 51. Best value: 0.580643:  40%|████      | 80/200 [00:59<00:36,  3.30it/s]

[I 2025-11-10 14:18:31,665] Trial 81 pruned.

Best trial: 51. Best value: 0.580643:  40%|████      | 81/200 [01:01<01:11,  1.67it/s]

[I 2025-11-10 14:18:32,965] Trial 83 pruned.

Best trial: 51. Best value: 0.580643:  41%|████      | 82/200 [01:02<01:41,  1.16it/s]

[I 2025-11-10 14:18:34,409] Trial 76 finished with value: 0.5753216374269007 and parameters: {'max_depth': 6, 'learning_rate': 0.04297718038889834, 'n_estimators': 735, 'subsample': 0.9537990445773835, 'colsample_bytree': 0.6181443600639629, 'min_child_weight': 2, 'gamma': 1.9462072026559523, 'reg_alpha': 8.929296667617998e-05, 'reg_lambda': 3.626349283597474e-06, 'max_delta_step': 1}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  42%|████▏     | 83/200 [01:03<01:26,  1.35it/s]

[I 2025-11-10 14:18:34,887] Trial 82 finished with value: 0.5245029239766081 and parameters: {'max_depth': 4, 'learning_rate': 0.10329132091532024, 'n_estimators': 454, 'subsample': 0.8034530479686817, 'colsample_bytree': 0.773128418453048, 'min_child_weight': 1, 'gamma': 2.1519307239140106, 'reg_alpha': 1.3004283158195624e-06, 'reg_lambda': 0.6534944276044095, 'max_delta_step': 3}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  42%|████▏     | 84/200 [01:03<01:24,  1.37it/s]

[I 2025-11-10 14:18:35,601] Trial 80 finished with value: 0.5556140350877193 and parameters: {'max_depth': 7, 'learning_rate': 0.09362050884674644, 'n_estimators': 738, 'subsample': 0.8076737241114724, 'colsample_bytree': 0.5383853960375248, 'min_child_weight': 1, 'gamma': 1.936582036246949, 'reg_alpha': 1.408283582677828e-06, 'reg_lambda': 1.883158679369265e-06, 'max_delta_step': 1}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  42%|████▎     | 85/200 [01:04<01:08,  1.68it/s]

[I 2025-11-10 14:18:35,879] Trial 86 pruned.

Best trial: 51. Best value: 0.580643:  43%|████▎     | 86/200 [01:05<01:20,  1.42it/s]

[I 2025-11-10 14:18:36,841] Trial 88 pruned.

Best trial: 51. Best value: 0.580643:  44%|████▎     | 87/200 [01:05<01:13,  1.54it/s]

[I 2025-11-10 14:18:37,363] Trial 84 finished with value: 0.5078362573099415 and parameters: {'max_depth': 7, 'learning_rate': 0.05038511988920134, 'n_estimators': 570, 'subsample': 0.579673396675, 'colsample_bytree': 0.7679023680709202, 'min_child_weight': 1, 'gamma': 3.2514619754133687, 'reg_alpha': 0.3427908209099317, 'reg_lambda': 4.754901679753541e-06, 'max_delta_step': 5}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  44%|████▍     | 88/200 [01:07<02:08,  1.14s/it]

[I 2025-11-10 14:18:39,663] Trial 87 finished with value: 0.5589473684210526 and parameters: {'max_depth': 6, 'learning_rate': 0.03045310514328648, 'n_estimators': 573, 'subsample': 0.9799357348964878, 'colsample_bytree': 0.6111834481640547, 'min_child_weight': 2, 'gamma': 2.4224617009409304, 'reg_alpha': 9.71356280269978e-05, 'reg_lambda': 8.863710395512357e-06, 'max_delta_step': 1}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  44%|████▍     | 89/200 [01:08<01:38,  1.12it/s]

[I 2025-11-10 14:18:39,956] Trial 85 finished with value: 0.5445029239766082 and parameters: {'max_depth': 6, 'learning_rate': 0.05986634588432306, 'n_estimators': 795, 'subsample': 0.9809020325993028, 'colsample_bytree': 0.6850039678184033, 'min_child_weight': 2, 'gamma': 1.877312001362523, 'reg_alpha': 0.011392649987581558, 'reg_lambda': 2.5912301524382286e-06, 'max_delta_step': 1}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  45%|████▌     | 90/200 [01:08<01:26,  1.28it/s]

[I 2025-11-10 14:18:40,493] Trial 91 pruned.

Best trial: 51. Best value: 0.580643:  46%|████▌     | 91/200 [01:09<01:13,  1.48it/s]

[I 2025-11-10 14:18:40,914] Trial 89 finished with value: 0.5583625730994152 and parameters: {'max_depth': 6, 'learning_rate': 0.058836598856835266, 'n_estimators': 573, 'subsample': 0.9776921996841322, 'colsample_bytree': 0.5657816239266353, 'min_child_weight': 2, 'gamma': 2.4260590689348427, 'reg_alpha': 0.001153933196693741, 'reg_lambda': 9.805455902631046e-06, 'max_delta_step': 5}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  46%|████▌     | 92/200 [01:09<01:08,  1.58it/s]

[I 2025-11-10 14:18:41,443] Trial 93 pruned.

Best trial: 51. Best value: 0.580643:  46%|████▋     | 93/200 [01:10<00:58,  1.83it/s]

[I 2025-11-10 14:18:41,786] Trial 94 pruned.

Best trial: 51. Best value: 0.580643:  47%|████▋     | 94/200 [01:10<01:07,  1.58it/s]

[I 2025-11-10 14:18:42,618] Trial 90 finished with value: 0.5275438596491229 and parameters: {'max_depth': 5, 'learning_rate': 0.05978640547966553, 'n_estimators': 892, 'subsample': 0.9835599375017755, 'colsample_bytree': 0.5000084295457808, 'min_child_weight': 3, 'gamma': 2.445823995406469, 'reg_alpha': 0.0011771201341018616, 'reg_lambda': 1.0760556911008136e-05, 'max_delta_step': 0}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  48%|████▊     | 95/200 [01:11<01:09,  1.51it/s]

[I 2025-11-10 14:18:43,361] Trial 95 pruned.

Best trial: 51. Best value: 0.580643:  48%|████▊     | 96/200 [01:11<00:54,  1.90it/s]

[I 2025-11-10 14:18:43,573] Trial 96 pruned.

Best trial: 51. Best value: 0.580643:  48%|████▊     | 97/200 [01:13<01:16,  1.35it/s]

[I 2025-11-10 14:18:44,799] Trial 92 finished with value: 0.553391812865497 and parameters: {'max_depth': 5, 'learning_rate': 0.030461857046462835, 'n_estimators': 697, 'subsample': 0.9475042002566373, 'colsample_bytree': 0.7439398406529003, 'min_child_weight': 3, 'gamma': 2.4056914128055316, 'reg_alpha': 3.211607195711963e-06, 'reg_lambda': 3.0588203147947926e-05, 'max_delta_step': 0}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  49%|████▉     | 98/200 [01:14<01:40,  1.02it/s]

[I 2025-11-10 14:18:46,354] Trial 98 finished with value: 0.5445029239766082 and parameters: {'max_depth': 3, 'learning_rate': 0.03619413149958059, 'n_estimators': 386, 'subsample': 0.998501535319825, 'colsample_bytree': 0.6097177166880597, 'min_child_weight': 2, 'gamma': 1.7024355447549642, 'reg_alpha': 0.00025562769721382625, 'reg_lambda': 0.00048374953258268174, 'max_delta_step': 1}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  50%|████▉     | 99/200 [01:15<01:23,  1.20it/s]

[I 2025-11-10 14:18:46,832] Trial 99 finished with value: 0.5661403508771929 and parameters: {'max_depth': 7, 'learning_rate': 0.04162338909219859, 'n_estimators': 389, 'subsample': 0.8610143070160078, 'colsample_bytree': 0.6972217026254318, 'min_child_weight': 2, 'gamma': 1.681672769931761, 'reg_alpha': 0.00016422248722044303, 'reg_lambda': 0.0005188858599026407, 'max_delta_step': 1}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  50%|█████     | 100/200 [01:18<02:35,  1.55s/it]

[I 2025-11-10 14:18:50,062] Trial 100 finished with value: 0.5694736842105262 and parameters: {'max_depth': 7, 'learning_rate': 0.011714031478585072, 'n_estimators': 379, 'subsample': 0.9128979575687324, 'colsample_bytree': 0.7071295969214476, 'min_child_weight': 2, 'gamma': 2.036133321668226, 'reg_alpha': 0.0001627828683712503, 'reg_lambda': 7.728936588285841e-07, 'max_delta_step': 1}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  50%|█████     | 101/200 [01:18<02:01,  1.23s/it]

[I 2025-11-10 14:18:50,530] Trial 103 pruned.

Best trial: 51. Best value: 0.580643:  51%|█████     | 102/200 [01:19<01:40,  1.02s/it]

[I 2025-11-10 14:18:51,077] Trial 104 pruned.

Best trial: 51. Best value: 0.580643:  52%|█████▏    | 103/200 [01:20<01:37,  1.00s/it]

[I 2025-11-10 14:18:52,041] Trial 97 finished with value: 0.5583625730994152 and parameters: {'max_depth': 3, 'learning_rate': 0.03655574456080771, 'n_estimators': 1345, 'subsample': 0.9313862555186443, 'colsample_bytree': 0.6120624001829831, 'min_child_weight': 2, 'gamma': 2.8637165187747353, 'reg_alpha': 0.00015867571260993674, 'reg_lambda': 2.6394833402803662e-05, 'max_delta_step': 2}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 51. Best value: 0.580643:  52%|█████▏    | 104/200 [01:21<01:42,  1.07s/it]

[I 2025-11-10 14:18:53,270] Trial 102 finished with value: 0.5753216374269007 and parameters: {'max_depth': 7, 'learning_rate': 0.04271715669149356, 'n_estimators': 639, 'subsample': 0.9642414427827731, 'colsample_bytree': 0.7025401087835588, 'min_child_weight': 1, 'gamma': 1.4738297652932966, 'reg_alpha': 2.6805240520731644e-08, 'reg_lambda': 5.907438960005068e-07, 'max_delta_step': 1}. Best is trial 51 with value: 0.5806432748538011.

Best trial: 101. Best value: 0.580877:  52%|█████▎    | 105/200 [01:22<01:26,  1.09it/s]

[I 2025-11-10 14:18:53,815] Trial 101 finished with value: 0.5808771929824562 and parameters: {'max_depth': 7, 'learning_rate': 0.011493176940856657, 'n_estimators': 524, 'subsample': 0.8602077961288592, 'colsample_bytree': 0.7022264741699333, 'min_child_weight': 1, 'gamma': 1.5233710429203924, 'reg_alpha': 2.2267730179393205e-05, 'reg_lambda': 9.010181456638177e-07, 'max_delta_step': 4}. Best is trial 101 with value: 0.5808771929824562.

Best trial: 101. Best value: 0.580877:  53%|█████▎    | 106/200 [01:22<01:22,  1.15it/s]

[I 2025-11-10 14:18:54,591] Trial 105 finished with value: 0.569766081871345 and parameters: {'max_depth': 7, 'learning_rate': 0.011650291882885024, 'n_estimators': 278, 'subsample': 0.960296055810698, 'colsample_bytree': 0.706446414698824, 'min_child_weight': 2, 'gamma': 1.5626849370297136, 'reg_alpha': 1.965254410119049e-05, 'reg_lambda': 5.939988023817012e-07, 'max_delta_step': 1}. Best is trial 101 with value: 0.5808771929824562.

Best trial: 101. Best value: 0.580877:  54%|█████▎    | 107/200 [01:25<02:03,  1.32s/it]

[I 2025-11-10 14:18:56,967] Trial 106 finished with value: 0.549766081871345 and parameters: {'max_depth': 7, 'learning_rate': 0.01112076950494731, 'n_estimators': 285, 'subsample': 0.9588481211906124, 'colsample_bytree': 0.6472406376522846, 'min_child_weight': 1, 'gamma': 1.6009501484369573, 'reg_alpha': 2.309153299538976e-05, 'reg_lambda': 1.1363673668521378e-06, 'max_delta_step': 1}. Best is trial 101 with value: 0.5808771929824562.

Best trial: 101. Best value: 0.580877:  54%|█████▍    | 108/200 [01:26<01:56,  1.27s/it]

[I 2025-11-10 14:18:58,097] Trial 110 pruned.

Best trial: 101. Best value: 0.580877:  55%|█████▍    | 109/200 [01:27<01:59,  1.31s/it]

[I 2025-11-10 14:18:59,526] Trial 109 finished with value: 0.5664327485380117 and parameters: {'max_depth': 7, 'learning_rate': 0.011202686255246602, 'n_estimators': 202, 'subsample': 0.868124000451764, 'colsample_bytree': 0.7081500901267183, 'min_child_weight': 1, 'gamma': 1.571955707454314, 'reg_alpha': 4.845439367523105e-05, 'reg_lambda': 1.467616629288025e-07, 'max_delta_step': 0}. Best is trial 101 with value: 0.5808771929824562.

Best trial: 101. Best value: 0.580877:  55%|█████▌    | 110/200 [01:28<01:49,  1.22s/it]

[I 2025-11-10 14:19:00,520] Trial 112 pruned.

Best trial: 101. Best value: 0.580877:  56%|█████▌    | 111/200 [01:29<01:45,  1.18s/it]

[I 2025-11-10 14:19:01,616] Trial 113 pruned.

Best trial: 101. Best value: 0.580877:  56%|█████▌    | 112/200 [01:30<01:35,  1.09s/it]

[I 2025-11-10 14:19:02,480] Trial 108 finished with value: 0.5642105263157895 and parameters: {'max_depth': 7, 'learning_rate': 0.01078239388109238, 'n_estimators': 647, 'subsample': 0.8696219163630368, 'colsample_bytree': 0.7105930812809375, 'min_child_weight': 1, 'gamma': 1.5650114462823872, 'reg_alpha': 1.950839646607921e-05, 'reg_lambda': 1.128266639681425e-07, 'max_delta_step': 5}. Best is trial 101 with value: 0.5808771929824562.

Best trial: 101. Best value: 0.580877:  56%|█████▋    | 113/200 [01:31<01:16,  1.13it/s]

[I 2025-11-10 14:19:02,891] Trial 107 finished with value: 0.5608771929824562 and parameters: {'max_depth': 7, 'learning_rate': 0.01096212769525458, 'n_estimators': 635, 'subsample': 0.9607463890872971, 'colsample_bytree': 0.7028209570137071, 'min_child_weight': 1, 'gamma': 1.1067509359954186, 'reg_alpha': 9.400318766909451e-08, 'reg_lambda': 2.05134055965524e-07, 'max_delta_step': 1}. Best is trial 101 with value: 0.5808771929824562.

Best trial: 101. Best value: 0.580877:  57%|█████▋    | 114/200 [01:32<01:31,  1.06s/it]

[I 2025-11-10 14:19:04,364] Trial 111 finished with value: 0.5719883040935673 and parameters: {'max_depth': 8, 'learning_rate': 0.012139149633008578, 'n_estimators': 374, 'subsample': 0.7524437287645261, 'colsample_bytree': 0.7513621238071877, 'min_child_weight': 1, 'gamma': 1.5118543121743733, 'reg_alpha': 4.394732011872026e-05, 'reg_lambda': 2.6127134996165687e-07, 'max_delta_step': 0}. Best is trial 101 with value: 0.5808771929824562.

Best trial: 101. Best value: 0.580877:  57%|█████▊    | 115/200 [01:35<02:04,  1.47s/it]

[I 2025-11-10 14:19:06,778] Trial 116 finished with value: 0.5553216374269007 and parameters: {'max_depth': 7, 'learning_rate': 0.011801226728799234, 'n_estimators': 213, 'subsample': 0.9316841122413857, 'colsample_bytree': 0.7194359528922531, 'min_child_weight': 1, 'gamma': 1.734888708771308, 'reg_alpha': 2.3888900814654026e-05, 'reg_lambda': 5.567470231266198e-07, 'max_delta_step': 0}. Best is trial 101 with value: 0.5808771929824562.

Best trial: 101. Best value: 0.580877:  58%|█████▊    | 116/200 [01:35<01:33,  1.11s/it]

[I 2025-11-10 14:19:07,053] Trial 114 finished with value: 0.558654970760234 and parameters: {'max_depth': 7, 'learning_rate': 0.01157473084398904, 'n_estimators': 330, 'subsample': 0.8589926000205169, 'colsample_bytree': 0.7181208958167976, 'min_child_weight': 1, 'gamma': 1.686867583570328, 'reg_alpha': 4.7711216336802027e-05, 'reg_lambda': 9.17430052711878e-07, 'max_delta_step': 1}. Best is trial 101 with value: 0.5808771929824562.

Best trial: 101. Best value: 0.580877:  58%|█████▊    | 117/200 [01:35<01:16,  1.09it/s]

[I 2025-11-10 14:19:07,522] Trial 115 finished with value: 0.5642105263157895 and parameters: {'max_depth': 7, 'learning_rate': 0.012918569793400095, 'n_estimators': 331, 'subsample': 0.8873988403230225, 'colsample_bytree': 0.7198496593409247, 'min_child_weight': 1, 'gamma': 1.7114137836788579, 'reg_alpha': 4.361382817719745e-05, 'reg_lambda': 5.03878244955513e-07, 'max_delta_step': 1}. Best is trial 101 with value: 0.5808771929824562.

Best trial: 101. Best value: 0.580877:  59%|█████▉    | 118/200 [01:35<00:57,  1.43it/s]

[I 2025-11-10 14:19:07,715] Trial 119 pruned.

Best trial: 101. Best value: 0.580877:  60%|█████▉    | 119/200 [01:36<00:48,  1.69it/s]

[I 2025-11-10 14:19:08,061] Trial 117 finished with value: 0.5772514619883041 and parameters: {'max_depth': 8, 'learning_rate': 0.011763178806379032, 'n_estimators': 208, 'subsample': 0.7513495067420637, 'colsample_bytree': 0.6704345107337463, 'min_child_weight': 1, 'gamma': 1.781773559606614, 'reg_alpha': 4.511048783896882e-05, 'reg_lambda': 5.780565306100578e-07, 'max_delta_step': 0}. Best is trial 101 with value: 0.5808771929824562.

Best trial: 101. Best value: 0.580877:  60%|██████    | 120/200 [01:37<00:52,  1.51it/s]

[I 2025-11-10 14:19:08,880] Trial 120 pruned.

Best trial: 101. Best value: 0.580877:  60%|██████    | 121/200 [01:37<00:52,  1.50it/s]

[I 2025-11-10 14:19:09,558] Trial 122 pruned.

Best trial: 118. Best value: 0.583099:  61%|██████    | 122/200 [01:39<01:18,  1.00s/it]

[I 2025-11-10 14:19:11,343] Trial 118 finished with value: 0.5830994152046783 and parameters: {'max_depth': 8, 'learning_rate': 0.012795602755594451, 'n_estimators': 330, 'subsample': 0.7600051789249563, 'colsample_bytree': 0.7272773917071033, 'min_child_weight': 1, 'gamma': 1.4079594052065099, 'reg_alpha': 4.6839885204617116e-05, 'reg_lambda': 4.099142446289631e-07, 'max_delta_step': 0}. Best is trial 118 with value: 0.5830994152046783.

Best trial: 118. Best value: 0.583099:  62%|██████▏   | 123/200 [01:40<01:18,  1.01s/it]

[I 2025-11-10 14:19:12,381] Trial 124 finished with value: 0.5719883040935673 and parameters: {'max_depth': 8, 'learning_rate': 0.016317476244935902, 'n_estimators': 201, 'subsample': 0.7556784512825316, 'colsample_bytree': 0.7330403290528433, 'min_child_weight': 1, 'gamma': 1.9936582147115556, 'reg_alpha': 7.731061850867292e-05, 'reg_lambda': 8.158613057059223e-08, 'max_delta_step': 0}. Best is trial 118 with value: 0.5830994152046783.

Best trial: 118. Best value: 0.583099:  62%|██████▏   | 124/200 [01:42<01:41,  1.34s/it]

[I 2025-11-10 14:19:14,485] Trial 121 finished with value: 0.5630994152046783 and parameters: {'max_depth': 8, 'learning_rate': 0.015732286142041082, 'n_estimators': 736, 'subsample': 0.7168055239682786, 'colsample_bytree': 0.7851250562773264, 'min_child_weight': 1, 'gamma': 1.3633795001675413, 'reg_alpha': 2.5368507977048643e-06, 'reg_lambda': 3.046920964328956e-08, 'max_delta_step': 0}. Best is trial 118 with value: 0.5830994152046783.

Best trial: 123. Best value: 0.591988:  62%|██████▎   | 125/200 [01:43<01:20,  1.08s/it]

[I 2025-11-10 14:19:14,954] Trial 123 finished with value: 0.5919883040935673 and parameters: {'max_depth': 9, 'learning_rate': 0.015543663552521708, 'n_estimators': 768, 'subsample': 0.7486894492258113, 'colsample_bytree': 0.6566602065314661, 'min_child_weight': 1, 'gamma': 1.9883249424097311, 'reg_alpha': 8.283129565571844e-06, 'reg_lambda': 4.1407079158314694e-07, 'max_delta_step': 0}. Best is trial 123 with value: 0.5919883040935673.

Best trial: 123. Best value: 0.591988:  63%|██████▎   | 126/200 [01:44<01:13,  1.01it/s]

[I 2025-11-10 14:19:15,750] Trial 125 finished with value: 0.5775438596491228 and parameters: {'max_depth': 8, 'learning_rate': 0.015834978688592873, 'n_estimators': 429, 'subsample': 0.7348901608458652, 'colsample_bytree': 0.7368884740533973, 'min_child_weight': 1, 'gamma': 1.3888524920040606, 'reg_alpha': 2.9905850716764448e-05, 'reg_lambda': 3.745668946401238e-07, 'max_delta_step': 0}. Best is trial 123 with value: 0.5919883040935673.

Best trial: 123. Best value: 0.591988:  64%|██████▎   | 127/200 [01:44<00:59,  1.22it/s]

[I 2025-11-10 14:19:16,169] Trial 126 finished with value: 0.5775438596491228 and parameters: {'max_depth': 9, 'learning_rate': 0.01619338034750126, 'n_estimators': 293, 'subsample': 0.7457611730132384, 'colsample_bytree': 0.7319782102334035, 'min_child_weight': 1, 'gamma': 1.3859078010646422, 'reg_alpha': 2.7582228438047962e-05, 'reg_lambda': 7.031137859170018e-08, 'max_delta_step': 0}. Best is trial 123 with value: 0.5919883040935673.

Best trial: 123. Best value: 0.591988:  64%|██████▍   | 128/200 [01:46<01:23,  1.16s/it]

[I 2025-11-10 14:19:18,103] Trial 127 finished with value: 0.5664327485380117 and parameters: {'max_depth': 8, 'learning_rate': 0.013873758080111756, 'n_estimators': 296, 'subsample': 0.7554893928509071, 'colsample_bytree': 0.733761199715558, 'min_child_weight': 1, 'gamma': 2.0239239103401863, 'reg_alpha': 3.05367825023719e-05, 'reg_lambda': 3.9055775619227207e-07, 'max_delta_step': 0}. Best is trial 123 with value: 0.5919883040935673.

Best trial: 123. Best value: 0.591988:  64%|██████▍   | 129/200 [01:46<01:06,  1.08it/s]

[I 2025-11-10 14:19:18,507] Trial 128 finished with value: 0.5408771929824562 and parameters: {'max_depth': 9, 'learning_rate': 0.01400034150955658, 'n_estimators': 298, 'subsample': 0.7515664138154001, 'colsample_bytree': 0.7316808543540335, 'min_child_weight': 1, 'gamma': 2.006792666888858, 'reg_alpha': 1.7589262790490388e-05, 'reg_lambda': 8.139287495905913e-08, 'max_delta_step': 0}. Best is trial 123 with value: 0.5919883040935673.

Best trial: 123. Best value: 0.591988:  66%|██████▌   | 131/200 [01:47<00:45,  1.53it/s]

[I 2025-11-10 14:19:19,184] Trial 129 finished with value: 0.5719883040935673 and parameters: {'max_depth': 9, 'learning_rate': 0.013988407256147044, 'n_estimators': 246, 'subsample': 0.7444047928834, 'colsample_bytree': 0.7336032381875628, 'min_child_weight': 1, 'gamma': 2.012674826513284, 'reg_alpha': 1.5902535560506812e-05, 'reg_lambda': 7.528141216993298e-08, 'max_delta_step': 0}. Best is trial 123 with value: 0.5919883040935673.
[I 2025-11-10 14:19:19,369] Trial 130 finished with value: 0.5716959064327486 and parameters: {'max_depth': 10, 'learning_rate': 0.020209294532346503, 'n_estimators': 250, 'subsample': 0.752792426062341, 'colsample_bytree': 0.7362684528676654, 'min_child_weight': 1, 'gamma': 1.2439212200809047, 'reg_alpha': 1.6669334234600248e-05, 'reg_lambda': 2.2288775701436976e-08, 'max_delta_step': 0}. Best is trial 123 with value: 0.5919883040935673.

Best trial: 123. Best value: 0.591988:  66%|██████▌   | 132/200 [01:49<01:14,  1.10s/it]

[I 2025-11-10 14:19:21,513] Trial 131 finished with value: 0.5830994152046783 and parameters: {'max_depth': 9, 'learning_rate': 0.020619934167510644, 'n_estimators': 246, 'subsample': 0.7484950106948619, 'colsample_bytree': 0.7502793517869331, 'min_child_weight': 1, 'gamma': 1.2680629792666582, 'reg_alpha': 1.629800225125831e-05, 'reg_lambda': 9.716818890029174e-08, 'max_delta_step': 0}. Best is trial 123 with value: 0.5919883040935673.

Best trial: 123. Best value: 0.591988:  66%|██████▋   | 133/200 [01:50<00:59,  1.13it/s]

[I 2025-11-10 14:19:21,887] Trial 132 finished with value: 0.5886549707602339 and parameters: {'max_depth': 9, 'learning_rate': 0.021318171321086623, 'n_estimators': 260, 'subsample': 0.7373290614604668, 'colsample_bytree': 0.7509241261702223, 'min_child_weight': 1, 'gamma': 1.2428540807277126, 'reg_alpha': 4.777102602238729e-06, 'reg_lambda': 2.275046142478696e-08, 'max_delta_step': 0}. Best is trial 123 with value: 0.5919883040935673.

Best trial: 123. Best value: 0.591988:  67%|██████▋   | 134/200 [01:50<00:55,  1.18it/s]

[I 2025-11-10 14:19:22,643] Trial 133 finished with value: 0.5886549707602339 and parameters: {'max_depth': 10, 'learning_rate': 0.019358898801148446, 'n_estimators': 241, 'subsample': 0.7345212147378009, 'colsample_bytree': 0.744250588650834, 'min_child_weight': 1, 'gamma': 1.2402563632725536, 'reg_alpha': 7.398067510075388e-05, 'reg_lambda': 2.0023876498964763e-08, 'max_delta_step': 0}. Best is trial 123 with value: 0.5919883040935673.

Best trial: 123. Best value: 0.591988:  68%|██████▊   | 135/200 [01:51<00:43,  1.50it/s]

[I 2025-11-10 14:19:22,893] Trial 134 finished with value: 0.5830994152046783 and parameters: {'max_depth': 10, 'learning_rate': 0.01765404664304536, 'n_estimators': 238, 'subsample': 0.7360450818902408, 'colsample_bytree': 0.7468364433984785, 'min_child_weight': 1, 'gamma': 1.2524060721818184, 'reg_alpha': 9.515777261066805e-06, 'reg_lambda': 3.0643369243576706e-08, 'max_delta_step': 0}. Best is trial 123 with value: 0.5919883040935673.

Best trial: 123. Best value: 0.591988:  68%|██████▊   | 136/200 [01:52<01:03,  1.00it/s]

[I 2025-11-10 14:19:24,668] Trial 136 finished with value: 0.5608771929824561 and parameters: {'max_depth': 9, 'learning_rate': 0.02171347040213681, 'n_estimators': 208, 'subsample': 0.769086560092939, 'colsample_bytree': 0.7468387933451481, 'min_child_weight': 1, 'gamma': 1.3677600535739893, 'reg_alpha': 4.806228199164117e-06, 'reg_lambda': 1.6952979960289287e-07, 'max_delta_step': 0}. Best is trial 123 with value: 0.5919883040935673.

Best trial: 123. Best value: 0.591988:  68%|██████▊   | 137/200 [01:53<00:52,  1.21it/s]

[I 2025-11-10 14:19:25,095] Trial 135 finished with value: 0.5686549707602339 and parameters: {'max_depth': 9, 'learning_rate': 0.016355483732150327, 'n_estimators': 233, 'subsample': 0.739387667602697, 'colsample_bytree': 0.7536307409763435, 'min_child_weight': 1, 'gamma': 1.3893496016912275, 'reg_alpha': 4.783402542309354e-06, 'reg_lambda': 8.014375940330067e-08, 'max_delta_step': 0}. Best is trial 123 with value: 0.5919883040935673.

Best trial: 123. Best value: 0.591988:  69%|██████▉   | 138/200 [01:54<00:51,  1.21it/s]

[I 2025-11-10 14:19:25,918] Trial 138 finished with value: 0.5742105263157894 and parameters: {'max_depth': 10, 'learning_rate': 0.021983473324865523, 'n_estimators': 216, 'subsample': 0.7288815596030302, 'colsample_bytree': 0.7625167190685177, 'min_child_weight': 1, 'gamma': 1.4058636722182514, 'reg_alpha': 4.587896671869869e-06, 'reg_lambda': 2.713473526931864e-08, 'max_delta_step': 0}. Best is trial 123 with value: 0.5919883040935673.
[I 2025-11-10 14:19:25,949] Trial 137 finished with value: 0.5686549707602339 and parameters: {'max_depth': 10, 'learning_rate': 0.018380667021640987, 'n_estimators': 228, 'subsample': 0.7256379417501299, 'colsample_bytree': 0.7488202373630356, 'min_child_weight': 1, 'gamma': 1.405029967784848, 'reg_alpha': 9.776510441641865e-06, 'reg_lambda': 1.7767696830739972e-07, 'max_delta_step': 0}. Best is trial 123 with value: 0.5919883040935673.

Best trial: 123. Best value: 0.591988:  70%|███████   | 140/200 [01:56<01:04,  1.08s/it]

[I 2025-11-10 14:19:28,656] Trial 139 finished with value: 0.5686549707602339 and parameters: {'max_depth': 10, 'learning_rate': 0.024515902505320313, 'n_estimators': 243, 'subsample': 0.7338034712476859, 'colsample_bytree': 0.7644413042294005, 'min_child_weight': 1, 'gamma': 1.1834721803681398, 'reg_alpha': 9.479845984466921e-06, 'reg_lambda': 1.6390729032805573e-08, 'max_delta_step': 0}. Best is trial 123 with value: 0.5919883040935673.

Best trial: 123. Best value: 0.591988:  70%|███████   | 141/200 [01:58<01:05,  1.11s/it]

[I 2025-11-10 14:19:29,855] Trial 142 finished with value: 0.5739181286549708 and parameters: {'max_depth': 10, 'learning_rate': 0.019433491990838894, 'n_estimators': 262, 'subsample': 0.6981817975677967, 'colsample_bytree': 0.7665012731297447, 'min_child_weight': 1, 'gamma': 1.1926985637328302, 'reg_alpha': 2.7538053243862823e-05, 'reg_lambda': 1.1768802558683193e-08, 'max_delta_step': 0}. Best is trial 123 with value: 0.5919883040935673.

Best trial: 140. Best value: 0.605029:  71%|███████   | 142/200 [02:01<01:39,  1.71s/it]

[I 2025-11-10 14:19:33,263] Trial 140 finished with value: 0.6050292397660819 and parameters: {'max_depth': 10, 'learning_rate': 0.018331082845741902, 'n_estimators': 781, 'subsample': 0.7256240776408219, 'colsample_bytree': 0.7730526967378333, 'min_child_weight': 1, 'gamma': 1.1789859706024792, 'reg_alpha': 9.523036784070109e-06, 'reg_lambda': 1.4857612015732845e-08, 'max_delta_step': 0}. Best is trial 140 with value: 0.6050292397660819.

Best trial: 140. Best value: 0.605029:  72%|███████▏  | 143/200 [02:02<01:21,  1.42s/it]

[I 2025-11-10 14:19:33,936] Trial 143 finished with value: 0.5797660818713449 and parameters: {'max_depth': 9, 'learning_rate': 0.02003400540541951, 'n_estimators': 268, 'subsample': 0.7094701862398379, 'colsample_bytree': 0.8012290399880322, 'min_child_weight': 1, 'gamma': 0.8302652967335403, 'reg_alpha': 2.9263147644698246e-05, 'reg_lambda': 1.0146402313556514e-08, 'max_delta_step': 0}. Best is trial 140 with value: 0.6050292397660819.

Best trial: 140. Best value: 0.605029:  72%|███████▏  | 144/200 [02:02<01:02,  1.11s/it]

[I 2025-11-10 14:19:34,229] Trial 141 finished with value: 0.5739181286549708 and parameters: {'max_depth': 10, 'learning_rate': 0.018099321509314623, 'n_estimators': 771, 'subsample': 0.7182806687334763, 'colsample_bytree': 0.6899385529443312, 'min_child_weight': 1, 'gamma': 1.1795663892004042, 'reg_alpha': 9.081011382449282e-06, 'reg_lambda': 1.1990346875192565e-08, 'max_delta_step': 0}. Best is trial 140 with value: 0.6050292397660819.

Best trial: 140. Best value: 0.605029:  72%|███████▎  | 145/200 [02:03<01:02,  1.13s/it]

[I 2025-11-10 14:19:35,427] Trial 144 finished with value: 0.5994736842105264 and parameters: {'max_depth': 10, 'learning_rate': 0.017620765693310555, 'n_estimators': 334, 'subsample': 0.7206543842397336, 'colsample_bytree': 0.691861796902332, 'min_child_weight': 1, 'gamma': 1.0520911405449964, 'reg_alpha': 5.897590746918525e-06, 'reg_lambda': 2.983136793404303e-08, 'max_delta_step': 0}. Best is trial 140 with value: 0.6050292397660819.

Best trial: 140. Best value: 0.605029:  73%|███████▎  | 146/200 [02:03<00:46,  1.16it/s]

[I 2025-11-10 14:19:35,627] Trial 146 pruned.

Best trial: 140. Best value: 0.605029:  74%|███████▎  | 147/200 [02:07<01:24,  1.59s/it]

[I 2025-11-10 14:19:38,971] Trial 147 finished with value: 0.5686549707602339 and parameters: {'max_depth': 9, 'learning_rate': 0.01697969654356765, 'n_estimators': 320, 'subsample': 0.7644546111400407, 'colsample_bytree': 0.7766060964007641, 'min_child_weight': 1, 'gamma': 0.8463581659803394, 'reg_alpha': 6.942427403201562e-05, 'reg_lambda': 3.317299072564612e-08, 'max_delta_step': 0}. Best is trial 140 with value: 0.6050292397660819.

Best trial: 140. Best value: 0.605029:  74%|███████▍  | 148/200 [02:08<01:10,  1.36s/it]

[I 2025-11-10 14:19:39,766] Trial 149 finished with value: 0.5353216374269005 and parameters: {'max_depth': 9, 'learning_rate': 0.021117537155942206, 'n_estimators': 324, 'subsample': 0.7709557919783758, 'colsample_bytree': 0.813544916469159, 'min_child_weight': 1, 'gamma': 1.0858578043305078, 'reg_alpha': 2.2375364151810603e-06, 'reg_lambda': 1.814007085779928e-08, 'max_delta_step': 0}. Best is trial 140 with value: 0.6050292397660819.

Best trial: 140. Best value: 0.605029:  74%|███████▍  | 149/200 [02:08<00:54,  1.07s/it]

[I 2025-11-10 14:19:40,142] Trial 148 finished with value: 0.5742105263157894 and parameters: {'max_depth': 9, 'learning_rate': 0.01687898261434599, 'n_estimators': 317, 'subsample': 0.7688815948814959, 'colsample_bytree': 0.8038268814384355, 'min_child_weight': 1, 'gamma': 0.8156334877506948, 'reg_alpha': 1.9946690925663934e-06, 'reg_lambda': 3.9859291981351174e-08, 'max_delta_step': 0}. Best is trial 140 with value: 0.6050292397660819.

Best trial: 140. Best value: 0.605029:  75%|███████▌  | 150/200 [02:08<00:40,  1.22it/s]

[I 2025-11-10 14:19:40,367] Trial 145 finished with value: 0.5686549707602339 and parameters: {'max_depth': 9, 'learning_rate': 0.01786975859012622, 'n_estimators': 785, 'subsample': 0.7651546099639273, 'colsample_bytree': 0.6881070245107809, 'min_child_weight': 1, 'gamma': 1.093775001118087, 'reg_alpha': 7.1535569723451225e-06, 'reg_lambda': 1.0100783698889544e-08, 'max_delta_step': 0}. Best is trial 140 with value: 0.6050292397660819.

Best trial: 140. Best value: 0.605029:  76%|███████▌  | 151/200 [02:09<00:38,  1.26it/s]

[I 2025-11-10 14:19:41,114] Trial 153 pruned.
[I 2025-11-10 14:19:41,126] Trial 152 pruned.

Best trial: 140. Best value: 0.605029:  76%|███████▋  | 153/200 [02:11<00:42,  1.11it/s]

[I 2025-11-10 14:19:43,177] Trial 150 finished with value: 0.5519883040935673 and parameters: {'max_depth': 10, 'learning_rate': 0.019115837069996262, 'n_estimators': 346, 'subsample': 0.7951427612783634, 'colsample_bytree': 0.7913150331822014, 'min_child_weight': 1, 'gamma': 1.032933167012522, 'reg_alpha': 2.216473082875497e-06, 'reg_lambda': 1.0063837056525831e-08, 'max_delta_step': 0}. Best is trial 140 with value: 0.6050292397660819.

Best trial: 140. Best value: 0.605029:  77%|███████▋  | 154/200 [02:12<00:39,  1.18it/s]

[I 2025-11-10 14:19:43,859] Trial 151 finished with value: 0.5464327485380116 and parameters: {'max_depth': 10, 'learning_rate': 0.01938900288157281, 'n_estimators': 346, 'subsample': 0.7965002317751221, 'colsample_bytree': 0.8046259123314471, 'min_child_weight': 1, 'gamma': 1.272968418973688, 'reg_alpha': 1.3883408855968972e-05, 'reg_lambda': 4.1226468855921835e-08, 'max_delta_step': 0}. Best is trial 140 with value: 0.6050292397660819.

Best trial: 140. Best value: 0.605029:  78%|███████▊  | 156/200 [02:12<00:23,  1.84it/s]

[I 2025-11-10 14:19:44,167] Trial 157 pruned.
[I 2025-11-10 14:19:44,276] Trial 155 finished with value: 0.5742105263157894 and parameters: {'max_depth': 10, 'learning_rate': 0.025463569723641204, 'n_estimators': 294, 'subsample': 0.7386051548573837, 'colsample_bytree': 0.6607816634634263, 'min_child_weight': 1, 'gamma': 1.2564781986193778, 'reg_alpha': 3.047365437434131e-05, 'reg_lambda': 5.2686873337606676e-08, 'max_delta_step': 0}. Best is trial 140 with value: 0.6050292397660819.

Best trial: 140. Best value: 0.605029:  78%|███████▊  | 157/200 [02:13<00:24,  1.72it/s]

[I 2025-11-10 14:19:44,947] Trial 159 pruned.

Best trial: 140. Best value: 0.605029:  79%|███████▉  | 158/200 [02:14<00:33,  1.24it/s]

[I 2025-11-10 14:19:46,321] Trial 156 finished with value: 0.5686549707602339 and parameters: {'max_depth': 10, 'learning_rate': 0.025151820212328105, 'n_estimators': 291, 'subsample': 0.7375270322749521, 'colsample_bytree': 0.6619798000317247, 'min_child_weight': 1, 'gamma': 1.2846599650939097, 'reg_alpha': 2.7768991351246098e-05, 'reg_lambda': 5.1098769158480085e-08, 'max_delta_step': 0}. Best is trial 140 with value: 0.6050292397660819.

Best trial: 140. Best value: 0.605029:  80%|███████▉  | 159/200 [02:15<00:35,  1.15it/s]

[I 2025-11-10 14:19:47,354] Trial 154 finished with value: 0.5575438596491228 and parameters: {'max_depth': 10, 'learning_rate': 0.02453799540949756, 'n_estimators': 818, 'subsample': 0.7414450435479804, 'colsample_bytree': 0.660445297743688, 'min_child_weight': 1, 'gamma': 1.2897467451730118, 'reg_alpha': 1.4566465326162602e-05, 'reg_lambda': 5.0047278980262046e-08, 'max_delta_step': 0}. Best is trial 140 with value: 0.6050292397660819.

Best trial: 140. Best value: 0.605029:  80%|████████  | 161/200 [02:15<00:20,  1.92it/s]

[I 2025-11-10 14:19:47,563] Trial 158 finished with value: 0.5430994152046783 and parameters: {'max_depth': 10, 'learning_rate': 0.024711262381331943, 'n_estimators': 287, 'subsample': 0.7428526095137818, 'colsample_bytree': 0.6744217257337368, 'min_child_weight': 1, 'gamma': 1.2872274990059809, 'reg_alpha': 4.333975061884947e-06, 'reg_lambda': 1.3314758478063054e-07, 'max_delta_step': 0}. Best is trial 140 with value: 0.6050292397660819.
[I 2025-11-10 14:19:47,709] Trial 161 pruned.

Best trial: 140. Best value: 0.605029:  81%|████████  | 162/200 [02:16<00:18,  2.01it/s]

[I 2025-11-10 14:19:48,150] Trial 164 pruned.

Best trial: 165. Best value: 0.608655:  82%|████████▏ | 163/200 [02:19<00:48,  1.31s/it]

[I 2025-11-10 14:19:51,398] Trial 165 finished with value: 0.6086549707602339 and parameters: {'max_depth': 9, 'learning_rate': 0.020616907411815398, 'n_estimators': 269, 'subsample': 0.7252627792799562, 'colsample_bytree': 0.775233331551374, 'min_child_weight': 1, 'gamma': 1.5144344528078355, 'reg_alpha': 2.031110993984937e-05, 'reg_lambda': 2.1736717833319063e-06, 'max_delta_step': 0}. Best is trial 165 with value: 0.6086549707602339.

Best trial: 165. Best value: 0.608655:  82%|████████▏ | 164/200 [02:20<00:44,  1.24s/it]

[I 2025-11-10 14:19:52,448] Trial 162 finished with value: 0.5486549707602338 and parameters: {'max_depth': 9, 'learning_rate': 0.01570202245095081, 'n_estimators': 436, 'subsample': 0.7255201067258338, 'colsample_bytree': 0.7575375200785179, 'min_child_weight': 1, 'gamma': 1.1508115215441508, 'reg_alpha': 5.942302436489382e-05, 'reg_lambda': 1.952882302234224e-08, 'max_delta_step': 0}. Best is trial 165 with value: 0.6086549707602339.
[I 2025-11-10 14:19:52,472] Trial 160 finished with value: 0.5630994152046783 and parameters: {'max_depth': 10, 'learning_rate': 0.015650837876830893, 'n_estimators': 933, 'subsample': 0.7134924352778631, 'colsample_bytree': 0.6523119903886232, 'min_child_weight': 1, 'gamma': 1.3292726661907215, 'reg_alpha': 4.718596173079085e-05, 'reg_lambda': 1.8780568833850017e-08, 'max_delta_step': 0}. Best is trial 165 with value: 0.6086549707602339.

Best trial: 165. Best value: 0.608655:  83%|████████▎ | 166/200 [02:21<00:26,  1.28it/s]

[I 2025-11-10 14:19:52,945] Trial 167 pruned.

Best trial: 165. Best value: 0.608655:  84%|████████▎ | 167/200 [02:22<00:28,  1.16it/s]

[I 2025-11-10 14:19:54,056] Trial 163 finished with value: 0.5742105263157894 and parameters: {'max_depth': 9, 'learning_rate': 0.020742500619321487, 'n_estimators': 759, 'subsample': 0.7120790450824449, 'colsample_bytree': 0.7749752220985947, 'min_child_weight': 1, 'gamma': 0.9753206792162645, 'reg_alpha': 5.505425817528112e-05, 'reg_lambda': 2.4060857588524117e-08, 'max_delta_step': 0}. Best is trial 165 with value: 0.6086549707602339.

Best trial: 165. Best value: 0.608655:  84%|████████▍ | 168/200 [02:23<00:26,  1.21it/s]

[I 2025-11-10 14:19:54,777] Trial 170 pruned.

Best trial: 165. Best value: 0.608655:  84%|████████▍ | 169/200 [02:23<00:24,  1.27it/s]

[I 2025-11-10 14:19:55,450] Trial 166 finished with value: 0.5739181286549707 and parameters: {'max_depth': 9, 'learning_rate': 0.01575397598380177, 'n_estimators': 259, 'subsample': 0.7256753080684994, 'colsample_bytree': 0.7694299406892978, 'min_child_weight': 1, 'gamma': 1.1524370083019437, 'reg_alpha': 2.051866282847394e-05, 'reg_lambda': 1.5297648517439594e-06, 'max_delta_step': 0}. Best is trial 165 with value: 0.6086549707602339.

Best trial: 165. Best value: 0.608655:  85%|████████▌ | 170/200 [02:24<00:20,  1.48it/s]

[I 2025-11-10 14:19:55,841] Trial 168 finished with value: 0.5575438596491228 and parameters: {'max_depth': 9, 'learning_rate': 0.021241727164156697, 'n_estimators': 262, 'subsample': 0.6976180418244485, 'colsample_bytree': 0.7741636175613434, 'min_child_weight': 1, 'gamma': 1.6492331311854238, 'reg_alpha': 2.0112968857336528e-05, 'reg_lambda': 3.2857855739885845e-06, 'max_delta_step': 0}. Best is trial 165 with value: 0.6086549707602339.

Best trial: 165. Best value: 0.608655:  86%|████████▌ | 171/200 [02:26<00:35,  1.22s/it]

[I 2025-11-10 14:19:58,422] Trial 171 finished with value: 0.5719883040935673 and parameters: {'max_depth': 9, 'learning_rate': 0.020587789308349435, 'n_estimators': 235, 'subsample': 0.7595623145358239, 'colsample_bytree': 0.7699902680384246, 'min_child_weight': 1, 'gamma': 1.4605899485036298, 'reg_alpha': 0.00010355680521095086, 'reg_lambda': 1.7125373651040786e-06, 'max_delta_step': 0}. Best is trial 165 with value: 0.6086549707602339.

Best trial: 165. Best value: 0.608655:  86%|████████▌ | 172/200 [02:27<00:28,  1.01s/it]

[I 2025-11-10 14:19:58,930] Trial 172 finished with value: 0.5553216374269005 and parameters: {'max_depth': 10, 'learning_rate': 0.017520234056263767, 'n_estimators': 223, 'subsample': 0.7610070652774614, 'colsample_bytree': 0.551261435895237, 'min_child_weight': 1, 'gamma': 1.5089320910943886, 'reg_alpha': 0.00011542181116829991, 'reg_lambda': 2.2037668470237767e-06, 'max_delta_step': 1}. Best is trial 165 with value: 0.6086549707602339.

Best trial: 165. Best value: 0.608655:  86%|████████▋ | 173/200 [02:28<00:28,  1.04s/it]

[I 2025-11-10 14:20:00,046] Trial 173 finished with value: 0.5572514619883041 and parameters: {'max_depth': 10, 'learning_rate': 0.01790799984316951, 'n_estimators': 233, 'subsample': 0.7792260016498109, 'colsample_bytree': 0.8270053630670853, 'min_child_weight': 1, 'gamma': 1.4830547779161054, 'reg_alpha': 0.00011872658319487082, 'reg_lambda': 1.926319343729077e-06, 'max_delta_step': 1}. Best is trial 165 with value: 0.6086549707602339.

Best trial: 165. Best value: 0.608655:  87%|████████▋ | 174/200 [02:28<00:22,  1.14it/s]

[I 2025-11-10 14:20:00,526] Trial 169 finished with value: 0.5975438596491228 and parameters: {'max_depth': 9, 'learning_rate': 0.020982937624124058, 'n_estimators': 864, 'subsample': 0.7618124895077283, 'colsample_bytree': 0.7701872911110266, 'min_child_weight': 1, 'gamma': 1.5184909332781311, 'reg_alpha': 0.0001051371758215378, 'reg_lambda': 1.737899247050271e-06, 'max_delta_step': 0}. Best is trial 165 with value: 0.6086549707602339.

Best trial: 165. Best value: 0.608655:  88%|████████▊ | 175/200 [02:31<00:34,  1.37s/it]

[I 2025-11-10 14:20:03,068] Trial 174 finished with value: 0.5719883040935673 and parameters: {'max_depth': 8, 'learning_rate': 0.0177709584877938, 'n_estimators': 309, 'subsample': 0.7474324977892097, 'colsample_bytree': 0.7273019184663133, 'min_child_weight': 1, 'gamma': 1.5219377174876456, 'reg_alpha': 3.632713046651389e-05, 'reg_lambda': 2.6930584153849545e-07, 'max_delta_step': 7}. Best is trial 165 with value: 0.6086549707602339.

Best trial: 165. Best value: 0.608655:  88%|████████▊ | 176/200 [02:32<00:31,  1.32s/it]

[I 2025-11-10 14:20:04,270] Trial 178 pruned.

Best trial: 165. Best value: 0.608655:  88%|████████▊ | 177/200 [02:33<00:24,  1.06s/it]

[I 2025-11-10 14:20:04,723] Trial 177 finished with value: 0.5775438596491228 and parameters: {'max_depth': 8, 'learning_rate': 0.02305733773399096, 'n_estimators': 309, 'subsample': 0.7521010657939733, 'colsample_bytree': 0.7923565823465124, 'min_child_weight': 1, 'gamma': 1.7738053906025537, 'reg_alpha': 1.2157159257567678e-05, 'reg_lambda': 2.2456720767808483e-07, 'max_delta_step': 0}. Best is trial 165 with value: 0.6086549707602339.

Best trial: 165. Best value: 0.608655:  89%|████████▉ | 178/200 [02:33<00:18,  1.22it/s]

[I 2025-11-10 14:20:04,964] Trial 180 pruned.

Best trial: 165. Best value: 0.608655:  90%|████████▉ | 179/200 [02:34<00:19,  1.07it/s]

[I 2025-11-10 14:20:06,174] Trial 181 pruned.

Best trial: 165. Best value: 0.608655:  90%|█████████ | 180/200 [02:35<00:18,  1.07it/s]

[I 2025-11-10 14:20:07,113] Trial 176 finished with value: 0.5775438596491228 and parameters: {'max_depth': 8, 'learning_rate': 0.01442929369259091, 'n_estimators': 670, 'subsample': 0.7478884097844284, 'colsample_bytree': 0.6977765510970083, 'min_child_weight': 1, 'gamma': 1.3852129959668633, 'reg_alpha': 4.071730789570799e-05, 'reg_lambda': 3.1102103760283625e-07, 'max_delta_step': 0}. Best is trial 165 with value: 0.6086549707602339.

Best trial: 165. Best value: 0.608655:  90%|█████████ | 181/200 [02:35<00:14,  1.27it/s]

[I 2025-11-10 14:20:07,547] Trial 182 pruned.
[I 2025-11-10 14:20:07,564] Trial 175 finished with value: 0.5664327485380117 and parameters: {'max_depth': 8, 'learning_rate': 0.014863410104670264, 'n_estimators': 872, 'subsample': 0.7482235310724686, 'colsample_bytree': 0.7252079339383297, 'min_child_weight': 1, 'gamma': 1.5599940282227742, 'reg_alpha': 1.1744902147645743e-05, 'reg_lambda': 2.845218996320136e-07, 'max_delta_step': 1}. Best is trial 165 with value: 0.6086549707602339.

Best trial: 179. Best value: 0.614211:  92%|█████████▏| 183/200 [02:39<00:23,  1.38s/it]

[I 2025-11-10 14:20:11,702] Trial 179 finished with value: 0.6142105263157894 and parameters: {'max_depth': 8, 'learning_rate': 0.02176817715154648, 'n_estimators': 883, 'subsample': 0.7331929521618454, 'colsample_bytree': 0.7405671695397694, 'min_child_weight': 1, 'gamma': 1.2115598232562956, 'reg_alpha': 3.481884647067803e-05, 'reg_lambda': 3.974410707094074e-07, 'max_delta_step': 0}. Best is trial 179 with value: 0.6142105263157894.

Best trial: 179. Best value: 0.614211:  92%|█████████▏| 184/200 [02:40<00:19,  1.19s/it]

[I 2025-11-10 14:20:12,325] Trial 184 finished with value: 0.5775438596491228 and parameters: {'max_depth': 8, 'learning_rate': 0.013240784189011475, 'n_estimators': 304, 'subsample': 0.7449357160973276, 'colsample_bytree': 0.7928141187678137, 'min_child_weight': 1, 'gamma': 1.6153913297991227, 'reg_alpha': 4.041661935775005e-05, 'reg_lambda': 1.063270813584591e-07, 'max_delta_step': 0}. Best is trial 179 with value: 0.6142105263157894.

Best trial: 179. Best value: 0.614211:  92%|█████████▎| 185/200 [02:41<00:15,  1.04s/it]

[I 2025-11-10 14:20:12,941] Trial 185 finished with value: 0.5830994152046783 and parameters: {'max_depth': 8, 'learning_rate': 0.013016155605566949, 'n_estimators': 370, 'subsample': 0.7318478636306341, 'colsample_bytree': 0.7608574393267719, 'min_child_weight': 1, 'gamma': 1.4014507069847433, 'reg_alpha': 2.458292257099948e-05, 'reg_lambda': 1.1346564682183002e-07, 'max_delta_step': 0}. Best is trial 179 with value: 0.6142105263157894.

Best trial: 179. Best value: 0.614211:  93%|█████████▎| 186/200 [02:42<00:17,  1.23s/it]

[I 2025-11-10 14:20:14,668] Trial 183 finished with value: 0.6030994152046784 and parameters: {'max_depth': 9, 'learning_rate': 0.02003237813249521, 'n_estimators': 890, 'subsample': 0.7354974366425077, 'colsample_bytree': 0.7441912690100878, 'min_child_weight': 1, 'gamma': 1.3831350274910639, 'reg_alpha': 3.138231139986884e-05, 'reg_lambda': 1.0932935022771312e-07, 'max_delta_step': 0}. Best is trial 179 with value: 0.6142105263157894.

Best trial: 179. Best value: 0.614211:  94%|█████████▎| 187/200 [02:44<00:15,  1.20s/it]

[I 2025-11-10 14:20:15,795] Trial 186 finished with value: 0.5886549707602339 and parameters: {'max_depth': 9, 'learning_rate': 0.02318730128656971, 'n_estimators': 367, 'subsample': 0.7227371688318314, 'colsample_bytree': 0.7903711426025151, 'min_child_weight': 1, 'gamma': 1.0965267793808147, 'reg_alpha': 2.4043861389949502e-05, 'reg_lambda': 3.571112384952786e-07, 'max_delta_step': 0}. Best is trial 179 with value: 0.6142105263157894.

Best trial: 179. Best value: 0.614211:  94%|█████████▍| 188/200 [02:45<00:13,  1.12s/it]

[I 2025-11-10 14:20:16,729] Trial 187 finished with value: 0.5994736842105264 and parameters: {'max_depth': 9, 'learning_rate': 0.018682251417241683, 'n_estimators': 374, 'subsample': 0.723337266752105, 'colsample_bytree': 0.7475536620074421, 'min_child_weight': 1, 'gamma': 1.0882981723939147, 'reg_alpha': 1.7145850745511462e-05, 'reg_lambda': 3.503148245013384e-07, 'max_delta_step': 0}. Best is trial 179 with value: 0.6142105263157894.

Best trial: 179. Best value: 0.614211:  94%|█████████▍| 189/200 [02:45<00:10,  1.03it/s]

[I 2025-11-10 14:20:17,334] Trial 190 pruned.

Best trial: 179. Best value: 0.614211:  95%|█████████▌| 190/200 [02:46<00:08,  1.17it/s]

[I 2025-11-10 14:20:17,911] Trial 188 finished with value: 0.5994736842105264 and parameters: {'max_depth': 9, 'learning_rate': 0.016538893853006918, 'n_estimators': 417, 'subsample': 0.7203926638425994, 'colsample_bytree': 0.7459483584643178, 'min_child_weight': 1, 'gamma': 1.1171529691008835, 'reg_alpha': 2.236520772517662e-05, 'reg_lambda': 2.986127884551759e-08, 'max_delta_step': 0}. Best is trial 179 with value: 0.6142105263157894.

Best trial: 179. Best value: 0.614211:  96%|█████████▌| 191/200 [02:50<00:16,  1.88s/it]

[I 2025-11-10 14:20:22,195] Trial 189 finished with value: 0.5994736842105264 and parameters: {'max_depth': 9, 'learning_rate': 0.018835684254268282, 'n_estimators': 877, 'subsample': 0.7225340856355148, 'colsample_bytree': 0.7435907481825897, 'min_child_weight': 1, 'gamma': 1.100388358081281, 'reg_alpha': 2.4315283601339227e-05, 'reg_lambda': 9.887533556523107e-08, 'max_delta_step': 0}. Best is trial 179 with value: 0.6142105263157894.

Best trial: 179. Best value: 0.614211:  96%|█████████▌| 192/200 [02:51<00:13,  1.67s/it]

[I 2025-11-10 14:20:23,420] Trial 193 finished with value: 0.5942105263157894 and parameters: {'max_depth': 9, 'learning_rate': 0.020706482600021444, 'n_estimators': 393, 'subsample': 0.7235266604156959, 'colsample_bytree': 0.7635702602208864, 'min_child_weight': 1, 'gamma': 1.1756878276250022, 'reg_alpha': 6.74757593342678e-06, 'reg_lambda': 1.1875283233861323e-07, 'max_delta_step': 0}. Best is trial 179 with value: 0.6142105263157894.

Best trial: 179. Best value: 0.614211:  96%|█████████▋| 193/200 [02:53<00:12,  1.74s/it]

[I 2025-11-10 14:20:25,320] Trial 191 finished with value: 0.5850292397660819 and parameters: {'max_depth': 9, 'learning_rate': 0.02053283300508299, 'n_estimators': 929, 'subsample': 0.7208497362734632, 'colsample_bytree': 0.7599305495802088, 'min_child_weight': 1, 'gamma': 1.0615227810863834, 'reg_alpha': 1.970084625275659e-05, 'reg_lambda': 7.095941554580927e-07, 'max_delta_step': 0}. Best is trial 179 with value: 0.6142105263157894.

Best trial: 179. Best value: 0.614211:  97%|█████████▋| 194/200 [02:53<00:08,  1.34s/it]

[I 2025-11-10 14:20:25,711] Trial 192 finished with value: 0.599766081871345 and parameters: {'max_depth': 9, 'learning_rate': 0.020604384602681523, 'n_estimators': 867, 'subsample': 0.7227237045647702, 'colsample_bytree': 0.7630387497736243, 'min_child_weight': 1, 'gamma': 0.891245578258231, 'reg_alpha': 1.499019897632685e-05, 'reg_lambda': 2.8437128427791108e-08, 'max_delta_step': 0}. Best is trial 179 with value: 0.6142105263157894.

Best trial: 179. Best value: 0.614211:  98%|█████████▊| 195/200 [02:55<00:06,  1.28s/it]

[I 2025-11-10 14:20:26,849] Trial 196 pruned.

Best trial: 179. Best value: 0.614211:  98%|█████████▊| 196/200 [02:56<00:05,  1.34s/it]

[I 2025-11-10 14:20:28,347] Trial 198 pruned.

Best trial: 179. Best value: 0.614211:  98%|█████████▊| 197/200 [02:58<00:04,  1.39s/it]

[I 2025-11-10 14:20:29,856] Trial 194 finished with value: 0.5739181286549708 and parameters: {'max_depth': 9, 'learning_rate': 0.021172588815089825, 'n_estimators': 893, 'subsample': 0.6854203872946555, 'colsample_bytree': 0.7656346812775032, 'min_child_weight': 1, 'gamma': 1.1766276753471325, 'reg_alpha': 6.792272572552994e-06, 'reg_lambda': 1.3552670626314763e-07, 'max_delta_step': 0}. Best is trial 179 with value: 0.6142105263157894.

Best trial: 179. Best value: 0.614211:  99%|█████████▉| 198/200 [02:58<00:02,  1.06s/it]

[I 2025-11-10 14:20:30,122] Trial 195 finished with value: 0.5994736842105264 and parameters: {'max_depth': 9, 'learning_rate': 0.020972956189421813, 'n_estimators': 861, 'subsample': 0.7239998535526659, 'colsample_bytree': 0.7585820724394116, 'min_child_weight': 1, 'gamma': 1.144410627554583, 'reg_alpha': 6.629887015727774e-06, 'reg_lambda': 1.0241451025553256e-07, 'max_delta_step': 0}. Best is trial 179 with value: 0.6142105263157894.

Best trial: 179. Best value: 0.614211: 100%|█████████▉| 199/200 [03:00<00:01,  1.28s/it]

[I 2025-11-10 14:20:31,921] Trial 197 finished with value: 0.5650292397660819 and parameters: {'max_depth': 9, 'learning_rate': 0.021412940029083595, 'n_estimators': 877, 'subsample': 0.7222255529056864, 'colsample_bytree': 0.7606059213298177, 'min_child_weight': 1, 'gamma': 0.953528073542562, 'reg_alpha': 6.800728221979337e-06, 'reg_lambda': 1.1372585867156893e-07, 'max_delta_step': 0}. Best is trial 179 with value: 0.6142105263157894.

Best trial: 179. Best value: 0.614211: 100%|██████████| 200/200 [03:01<00:00,  1.10it/s]

[I 2025-11-10 14:20:33,660] Trial 199 finished with value: 0.5742105263157894 and parameters: {'max_depth': 9, 'learning_rate': 0.01874562170181195, 'n_estimators': 862, 'subsample': 0.7062211883552061, 'colsample_bytree': 0.7656877095500801, 'min_child_weight': 1, 'gamma': 0.9942587318929574, 'reg_alpha': 6.862075290253368e-06, 'reg_lambda': 3.111644896026026e-08, 'max_delta_step': 0}. Best is trial 179 with value: 0.6142105263157894.

[I 2025-11-10 14:20:34,768] A new study created in memory with name: 3_5_balanced_accuracy
Best trial: 2. Best value: 0.5:   0%|          | 1/200 [00:03<12:09,  3.67s/it]

[I 2025-11-10 14:20:38,428] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03321241516333246, 'n_estimators': 922, 'subsample': 0.8021470350687092, 'colsample_bytree': 0.9276673871821204, 'min_child_weight': 5, 'gamma': 0.7104130583572404, 'reg_alpha': 0.10003924899774215, 'reg_lambda': 0.013546199816536559, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   1%|          | 2/200 [00:04<06:39,  2.02s/it]

[I 2025-11-10 14:20:39,286] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.19194011419673238, 'n_estimators': 1142, 'subsample': 0.5366924237915232, 'colsample_bytree': 0.9060068034722344, 'min_child_weight': 10, 'gamma': 4.403068976313484, 'reg_alpha': 0.0029226136482108237, 'reg_lambda': 2.292838906829808e-05, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▏         | 3/200 [00:04<04:00,  1.22s/it]

[I 2025-11-10 14:20:39,566] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.01687043367574878, 'n_estimators': 229, 'subsample': 0.6200347921933353, 'colsample_bytree': 0.9342272127589615, 'min_child_weight': 7, 'gamma': 2.937392210982568, 'reg_alpha': 4.917375793960692e-05, 'reg_lambda': 9.035220434300939, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▏         | 4/200 [00:05<03:21,  1.03s/it]

[I 2025-11-10 14:20:40,296] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.08824051741526177, 'n_estimators': 1362, 'subsample': 0.6004430394240443, 'colsample_bytree': 0.959658912427673, 'min_child_weight': 7, 'gamma': 0.005805178651797638, 'reg_alpha': 0.26456786010453703, 'reg_lambda': 0.2541923441828269, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▎         | 5/200 [00:09<06:55,  2.13s/it]

[I 2025-11-10 14:20:44,385] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03392192783856264, 'n_estimators': 767, 'subsample': 0.6445649413567439, 'colsample_bytree': 0.6504551590906138, 'min_child_weight': 7, 'gamma': 2.8761590412150935, 'reg_alpha': 1.2350706682349308e-07, 'reg_lambda': 1.0868168936556225e-05, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.
[I 2025-11-10 14:20:44,449] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.037251511030128914, 'n_estimators': 962, 'subsample': 0.6429464729291615, 'colsample_bytree': 0.9067902736285847, 'min_child_weight': 6, 'gamma': 4.4490154196587035, 'reg_alpha': 1.4315746845273443, 'reg_lambda': 0.039400719095748986, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   4%|▎         | 7/200 [00:10<04:17,  1.33s/it]

[I 2025-11-10 14:20:45,502] Trial 6 finished with value: 0.43508771929824563 and parameters: {'max_depth': 3, 'learning_rate': 0.028962842673076965, 'n_estimators': 1173, 'subsample': 0.8878792383394059, 'colsample_bytree': 0.6777926736051869, 'min_child_weight': 5, 'gamma': 1.785015280889017, 'reg_alpha': 0.012729197170877088, 'reg_lambda': 0.0004269516760240499, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   4%|▍         | 8/200 [00:11<04:02,  1.27s/it]

[I 2025-11-10 14:20:46,578] Trial 1 finished with value: 0.4339766081871345 and parameters: {'max_depth': 5, 'learning_rate': 0.053422853657757806, 'n_estimators': 1357, 'subsample': 0.8983281790628481, 'colsample_bytree': 0.9928185168809901, 'min_child_weight': 1, 'gamma': 1.6368104615757688, 'reg_alpha': 6.619412039802399e-07, 'reg_lambda': 1.3548550924071459, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   4%|▍         | 9/200 [00:12<03:09,  1.01it/s]

[I 2025-11-10 14:20:46,853] Trial 8 finished with value: 0.47923976608187135 and parameters: {'max_depth': 9, 'learning_rate': 0.2114300077098302, 'n_estimators': 488, 'subsample': 0.7906296621537917, 'colsample_bytree': 0.6864893380512229, 'min_child_weight': 3, 'gamma': 0.5554943298968334, 'reg_alpha': 9.86448635299153e-08, 'reg_lambda': 1.8327303794193675e-05, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   5%|▌         | 10/200 [00:14<04:09,  1.31s/it]

[I 2025-11-10 14:20:48,978] Trial 9 finished with value: 0.4492397660818714 and parameters: {'max_depth': 4, 'learning_rate': 0.1529665257728046, 'n_estimators': 943, 'subsample': 0.6877599761483528, 'colsample_bytree': 0.9956713970479508, 'min_child_weight': 4, 'gamma': 4.264431491022599, 'reg_alpha': 0.000653105209359562, 'reg_lambda': 0.0001619027676965862, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   6%|▌         | 11/200 [00:15<03:43,  1.18s/it]

[I 2025-11-10 14:20:49,829] Trial 10 pruned.

Best trial: 2. Best value: 0.5:   6%|▌         | 12/200 [00:17<04:49,  1.54s/it]

[I 2025-11-10 14:20:52,254] Trial 13 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.29096751936306825, 'n_estimators': 576, 'subsample': 0.5418490277330068, 'colsample_bytree': 0.7846231200802674, 'min_child_weight': 10, 'gamma': 3.5809163913962987, 'reg_alpha': 1.832581078202328e-05, 'reg_lambda': 1.5446092604601253e-08, 'max_delta_step': 10}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   6%|▋         | 13/200 [00:17<03:41,  1.19s/it]

[I 2025-11-10 14:20:52,578] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.042729643847468884, 'n_estimators': 1233, 'subsample': 0.5738005541730704, 'colsample_bytree': 0.8838763545233548, 'min_child_weight': 4, 'gamma': 1.0532979158672946, 'reg_alpha': 0.0001785342954940859, 'reg_lambda': 9.947085673191776, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   7%|▋         | 14/200 [00:18<03:07,  1.01s/it]

[I 2025-11-10 14:20:53,184] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.029246641611063325, 'n_estimators': 1287, 'subsample': 0.6594166560270684, 'colsample_bytree': 0.9088602473328913, 'min_child_weight': 8, 'gamma': 1.7209895952466918, 'reg_alpha': 0.0013696620043388821, 'reg_lambda': 1.5258876147193257, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   8%|▊         | 15/200 [00:18<02:25,  1.27it/s]

[I 2025-11-10 14:20:53,442] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.012086767753331553, 'n_estimators': 720, 'subsample': 0.5358561682446562, 'colsample_bytree': 0.5423124039435916, 'min_child_weight': 10, 'gamma': 3.783402270040105, 'reg_alpha': 0.004537374757583384, 'reg_lambda': 1.856035742017201e-08, 'max_delta_step': 10}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   8%|▊         | 17/200 [00:22<03:33,  1.16s/it]

[I 2025-11-10 14:20:57,001] Trial 15 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.012659231332882106, 'n_estimators': 1123, 'subsample': 0.8140193631697535, 'colsample_bytree': 0.5023041736643521, 'min_child_weight': 10, 'gamma': 1.424589505601316, 'reg_alpha': 0.0056129922236495, 'reg_lambda': 2.5323317272772626e-07, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.
[I 2025-11-10 14:20:57,119] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.017886374174390544, 'n_estimators': 1075, 'subsample': 0.8084316512027521, 'colsample_bytree': 0.5590163949104161, 'min_child_weight': 10, 'gamma': 2.174514005650031, 'reg_alpha': 0.022447873763362023, 'reg_lambda': 2.3655659505287477e-07, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   9%|▉         | 18/200 [00:22<02:54,  1.05it/s]

[I 2025-11-10 14:20:57,583] Trial 17 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01033447779211366, 'n_estimators': 1017, 'subsample': 0.81317612445137, 'colsample_bytree': 0.5291734738657701, 'min_child_weight': 10, 'gamma': 3.500675884376728, 'reg_alpha': 0.03228519195536435, 'reg_lambda': 2.0086282965676524e-07, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  10%|▉         | 19/200 [00:23<02:40,  1.13it/s]

[I 2025-11-10 14:20:58,297] Trial 18 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07954921522746479, 'n_estimators': 1032, 'subsample': 0.7993294724324661, 'colsample_bytree': 0.8336924140593687, 'min_child_weight': 9, 'gamma': 2.224023725496332, 'reg_alpha': 0.0709612224471731, 'reg_lambda': 0.0020333291829295955, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  10%|█         | 20/200 [00:24<02:42,  1.11it/s]

[I 2025-11-10 14:20:59,240] Trial 22 pruned.

Best trial: 2. Best value: 0.5:  11%|█         | 22/200 [00:26<02:39,  1.12it/s]

[I 2025-11-10 14:21:01,196] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08901575726883997, 'n_estimators': 920, 'subsample': 0.9959791328433258, 'colsample_bytree': 0.8123191685969423, 'min_child_weight': 8, 'gamma': 4.948391658531978, 'reg_alpha': 0.10691694386819582, 'reg_lambda': 0.0027923756866130847, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.
[I 2025-11-10 14:21:01,333] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08608559141036606, 'n_estimators': 842, 'subsample': 0.9936705076225336, 'colsample_bytree': 0.8258792105221356, 'min_child_weight': 8, 'gamma': 2.5771559354275384, 'reg_alpha': 0.12429520906925916, 'reg_lambda': 0.002082275438563356, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  12%|█▏        | 23/200 [00:27<02:18,  1.27it/s]

[I 2025-11-10 14:21:01,864] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08580647027082408, 'n_estimators': 1034, 'subsample': 0.9891357987978118, 'colsample_bytree': 0.8206003041335657, 'min_child_weight': 8, 'gamma': 2.2379758095999085, 'reg_alpha': 0.08915549622978897, 'reg_lambda': 0.0027733675704919867, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  12%|█▏        | 24/200 [00:27<02:14,  1.31it/s]

[I 2025-11-10 14:21:02,510] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.022486449101349084, 'n_estimators': 601, 'subsample': 0.74247904683477, 'colsample_bytree': 0.8375682333245985, 'min_child_weight': 5, 'gamma': 0.845268418100955, 'reg_alpha': 0.3386309965701261, 'reg_lambda': 2.5883640542864127e-05, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  12%|█▎        | 25/200 [00:34<07:25,  2.55s/it]

[I 2025-11-10 14:21:09,287] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.13857867313293676, 'n_estimators': 1435, 'subsample': 0.5007304171094368, 'colsample_bytree': 0.9531500616678624, 'min_child_weight': 6, 'gamma': 0.08693225571840624, 'reg_alpha': 0.48447433830613895, 'reg_lambda': 0.20995923523937457, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.
[I 2025-11-10 14:21:09,348] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.13693796956175777, 'n_estimators': 1482, 'subsample': 0.5103279805576072, 'colsample_bytree': 0.9510066678675924, 'min_child_weight': 6, 'gamma': 0.009358414518649938, 'reg_alpha': 0.4656638609832719, 'reg_lambda': 0.16568709935410422, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  14%|█▎        | 27/200 [00:35<04:41,  1.63s/it]

[I 2025-11-10 14:21:10,394] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.13762077502389988, 'n_estimators': 1475, 'subsample': 0.5080975667724584, 'colsample_bytree': 0.944673726179004, 'min_child_weight': 6, 'gamma': 0.014187322298670728, 'reg_alpha': 0.5273650463281077, 'reg_lambda': 0.16370930469828202, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  14%|█▍        | 28/200 [00:35<03:45,  1.31s/it]

[I 2025-11-10 14:21:10,753] Trial 27 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.14051012848557923, 'n_estimators': 1462, 'subsample': 0.5884511006353152, 'colsample_bytree': 0.947914384218921, 'min_child_weight': 6, 'gamma': 0.07533438975631879, 'reg_alpha': 7.187443482743971, 'reg_lambda': 0.10381743094689375, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  14%|█▍        | 29/200 [00:41<06:45,  2.37s/it]

[I 2025-11-10 14:21:16,109] Trial 29 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.06158626904903122, 'n_estimators': 1288, 'subsample': 0.574903960753565, 'colsample_bytree': 0.8816361487895765, 'min_child_weight': 7, 'gamma': 0.4585387639809798, 'reg_alpha': 3.3248443408147623, 'reg_lambda': 0.00015606645774840323, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  15%|█▌        | 30/200 [00:41<05:09,  1.82s/it]

[I 2025-11-10 14:21:16,452] Trial 28 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.06421083761844773, 'n_estimators': 1333, 'subsample': 0.5905041475771837, 'colsample_bytree': 0.9524452563236531, 'min_child_weight': 7, 'gamma': 0.07817838042476466, 'reg_alpha': 9.75313169693349, 'reg_lambda': 0.08370456870393264, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  16%|█▌        | 31/200 [00:42<04:22,  1.55s/it]

[I 2025-11-10 14:21:17,326] Trial 30 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.05546852368373777, 'n_estimators': 1303, 'subsample': 0.587747043091917, 'colsample_bytree': 0.8699615181391247, 'min_child_weight': 9, 'gamma': 0.5950700123619541, 'reg_alpha': 8.952755299887956, 'reg_lambda': 0.0003510905484005749, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  16%|█▌        | 32/200 [00:43<03:32,  1.27s/it]

[I 2025-11-10 14:21:17,872] Trial 34 pruned.
[I 2025-11-10 14:21:17,891] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.05663704955832019, 'n_estimators': 1304, 'subsample': 0.7470199993090718, 'colsample_bytree': 0.8746139690023754, 'min_child_weight': 9, 'gamma': 0.6947950270631221, 'reg_alpha': 0.002097292327410386, 'reg_lambda': 0.0001804308452400763, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  17%|█▋        | 34/200 [00:44<02:59,  1.08s/it]

[I 2025-11-10 14:21:19,564] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.02304252342477221, 'n_estimators': 298, 'subsample': 0.6113507030899205, 'colsample_bytree': 0.9174126292651391, 'min_child_weight': 5, 'gamma': 1.2756501479202198, 'reg_alpha': 4.194027932946742e-05, 'reg_lambda': 8.477297654481236, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  18%|█▊        | 35/200 [00:45<02:24,  1.14it/s]

[I 2025-11-10 14:21:19,808] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.04485966827404684, 'n_estimators': 345, 'subsample': 0.619336521254913, 'colsample_bytree': 0.916473859752939, 'min_child_weight': 9, 'gamma': 4.076709266178021, 'reg_alpha': 2.7209387163577883e-06, 'reg_lambda': 7.813248575920162, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  18%|█▊        | 36/200 [00:48<04:13,  1.55s/it]

[I 2025-11-10 14:21:23,288] Trial 33 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.046325193484671054, 'n_estimators': 1199, 'subsample': 0.8942596488751887, 'colsample_bytree': 0.9991658876106194, 'min_child_weight': 9, 'gamma': 1.240666148528853, 'reg_alpha': 0.0018775068993825837, 'reg_lambda': 0.8166299446823845, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  18%|█▊        | 37/200 [00:48<03:20,  1.23s/it]

[I 2025-11-10 14:21:23,649] Trial 32 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.056412893743856336, 'n_estimators': 1330, 'subsample': 0.8743167513906493, 'colsample_bytree': 0.9845212225960361, 'min_child_weight': 9, 'gamma': 1.1491163630793293, 'reg_alpha': 0.0036420223826178237, 'reg_lambda': 1.0217623162584155, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  19%|█▉        | 38/200 [00:49<03:07,  1.16s/it]

[I 2025-11-10 14:21:24,628] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.20018005488078217, 'n_estimators': 231, 'subsample': 0.848834617979177, 'colsample_bytree': 0.7172545949512692, 'min_child_weight': 7, 'gamma': 2.98803765308251, 'reg_alpha': 2.959171481331478e-08, 'reg_lambda': 0.02131690412733325, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  20%|█▉        | 39/200 [00:51<03:20,  1.24s/it]

[I 2025-11-10 14:21:26,087] Trial 41 pruned.
[I 2025-11-10 14:21:26,105] Trial 37 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.044347639757469574, 'n_estimators': 1180, 'subsample': 0.709517941280657, 'colsample_bytree': 0.987686035955081, 'min_child_weight': 7, 'gamma': 4.0988880241174055, 'reg_alpha': 6.326591824058941e-06, 'reg_lambda': 3.2041125725776447, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  20%|██        | 41/200 [00:51<02:06,  1.25it/s]

[I 2025-11-10 14:21:26,585] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2451174565618775, 'n_estimators': 1213, 'subsample': 0.8561375727682436, 'colsample_bytree': 0.9948262711822903, 'min_child_weight': 7, 'gamma': 3.1332455166351716, 'reg_alpha': 0.00044520878517147856, 'reg_lambda': 0.5946231260238782, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  22%|██▏       | 43/200 [00:52<01:22,  1.91it/s]

[I 2025-11-10 14:21:26,857] Trial 42 pruned.
[I 2025-11-10 14:21:26,963] Trial 43 pruned.

Best trial: 2. Best value: 0.5:  22%|██▏       | 44/200 [00:52<01:07,  2.32it/s]

[I 2025-11-10 14:21:27,146] Trial 40 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.229478240699475, 'n_estimators': 710, 'subsample': 0.7039489287055104, 'colsample_bytree': 0.7264157587022648, 'min_child_weight': 7, 'gamma': 3.0485080855599813, 'reg_alpha': 0.0004949442467199094, 'reg_lambda': 2.391869774175905e-06, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  22%|██▎       | 45/200 [00:53<01:21,  1.91it/s]

[I 2025-11-10 14:21:27,910] Trial 45 pruned.

Best trial: 2. Best value: 0.5:  23%|██▎       | 46/200 [00:55<02:41,  1.05s/it]

[I 2025-11-10 14:21:30,286] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.025022508789099864, 'n_estimators': 690, 'subsample': 0.6642019211580716, 'colsample_bytree': 0.9132620756368364, 'min_child_weight': 5, 'gamma': 4.5817079917922445, 'reg_alpha': 2.12380515248393, 'reg_lambda': 0.009477543945735717, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  24%|██▎       | 47/200 [00:56<02:32,  1.00it/s]

[I 2025-11-10 14:21:31,160] Trial 48 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.038231982416356246, 'n_estimators': 658, 'subsample': 0.5327748614429121, 'colsample_bytree': 0.8596677040889029, 'min_child_weight': 6, 'gamma': 3.775404112980025, 'reg_alpha': 4.169652722816042e-07, 'reg_lambda': 3.785962047036918e-05, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  24%|██▍       | 48/200 [00:56<02:06,  1.20it/s]

[I 2025-11-10 14:21:31,596] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.038181685765431655, 'n_estimators': 932, 'subsample': 0.5535204772594, 'colsample_bytree': 0.8979743273203586, 'min_child_weight': 6, 'gamma': 4.526455002405411, 'reg_alpha': 0.9529641626193629, 'reg_lambda': 3.85981992405024e-05, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.
[I 2025-11-10 14:21:31,618] Trial 47 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.037984551574253136, 'n_estimators': 935, 'subsample': 0.6377024368927813, 'colsample_bytree': 0.9011361097692114, 'min_child_weight': 6, 'gamma': 4.437520779207558, 'reg_alpha': 1.6094807239043603, 'reg_lambda': 0.03817441986159958, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  25%|██▌       | 50/200 [00:57<01:40,  1.49it/s]

[I 2025-11-10 14:21:32,540] Trial 50 pruned.

Best trial: 2. Best value: 0.5:  26%|██▌       | 51/200 [00:58<01:39,  1.50it/s]

[I 2025-11-10 14:21:33,190] Trial 52 pruned.
[I 2025-11-10 14:21:33,250] Trial 51 pruned.

Best trial: 2. Best value: 0.5:  26%|██▋       | 53/200 [01:00<01:47,  1.36it/s]

[I 2025-11-10 14:21:34,852] Trial 53 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.013646384288122669, 'n_estimators': 495, 'subsample': 0.6145265841622933, 'colsample_bytree': 0.9336817323453045, 'min_child_weight': 8, 'gamma': 3.390053324086775, 'reg_alpha': 0.19311743971656026, 'reg_lambda': 0.009545187583340952, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  28%|██▊       | 55/200 [01:00<01:18,  1.85it/s]

[I 2025-11-10 14:21:35,312] Trial 54 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.029134012620625652, 'n_estimators': 480, 'subsample': 0.6155224631103143, 'colsample_bytree': 0.6581402604089264, 'min_child_weight': 8, 'gamma': 3.5046583865323244, 'reg_alpha': 3.81342317244301e-07, 'reg_lambda': 6.506253548297505e-07, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.
[I 2025-11-10 14:21:35,452] Trial 49 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03698168278001893, 'n_estimators': 1098, 'subsample': 0.6338444876186458, 'colsample_bytree': 0.931269498500926, 'min_child_weight': 6, 'gamma': 3.81877385417633, 'reg_alpha': 0.03907303704745463, 'reg_lambda': 4.166011461581488e-05, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  28%|██▊       | 56/200 [01:02<01:54,  1.25it/s]

[I 2025-11-10 14:21:36,976] Trial 55 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.031345961371768725, 'n_estimators': 873, 'subsample': 0.6157836595850225, 'colsample_bytree': 0.6254674101632118, 'min_child_weight': 8, 'gamma': 2.7353303624969625, 'reg_alpha': 1.2965996997944845e-07, 'reg_lambda': 1.0784546780867305e-05, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  28%|██▊       | 57/200 [01:03<02:25,  1.02s/it]

[I 2025-11-10 14:21:38,589] Trial 56 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.029658532543638157, 'n_estimators': 859, 'subsample': 0.5606017931641243, 'colsample_bytree': 0.6528396426439784, 'min_child_weight': 5, 'gamma': 3.774841389154437, 'reg_alpha': 1.2111235642012931e-08, 'reg_lambda': 9.832297692158176e-06, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  29%|██▉       | 58/200 [01:04<02:14,  1.06it/s]

[I 2025-11-10 14:21:39,360] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03319516100507494, 'n_estimators': 866, 'subsample': 0.6843850879056934, 'colsample_bytree': 0.9678423992875754, 'min_child_weight': 5, 'gamma': 2.7925446928950803, 'reg_alpha': 1.197951684611333e-08, 'reg_lambda': 1.1430380138590652e-05, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  30%|██▉       | 59/200 [01:05<02:00,  1.17it/s]

[I 2025-11-10 14:21:39,975] Trial 58 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.025912430285428827, 'n_estimators': 1002, 'subsample': 0.6810459424217957, 'colsample_bytree': 0.796311987080819, 'min_child_weight': 5, 'gamma': 2.6639792397253403, 'reg_alpha': 3.110582208870678e-08, 'reg_lambda': 8.039225036927061e-06, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  30%|███       | 60/200 [01:05<01:48,  1.29it/s]

[I 2025-11-10 14:21:40,573] Trial 59 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07335671539327084, 'n_estimators': 794, 'subsample': 0.6798676820441164, 'colsample_bytree': 0.8010247015144777, 'min_child_weight': 5, 'gamma': 4.730641084334728, 'reg_alpha': 2.4155338871649176e-08, 'reg_lambda': 0.0006765063648314043, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  30%|███       | 61/200 [01:07<02:25,  1.05s/it]

[I 2025-11-10 14:21:42,255] Trial 60 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.17493508476464578, 'n_estimators': 792, 'subsample': 0.5334880137433289, 'colsample_bytree': 0.8558696086313538, 'min_child_weight': 7, 'gamma': 4.758934477364546, 'reg_alpha': 0.1784571410485818, 'reg_lambda': 0.3474524250416074, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  31%|███       | 62/200 [01:08<02:31,  1.09s/it]

[I 2025-11-10 14:21:43,471] Trial 62 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.06587949261956007, 'n_estimators': 801, 'subsample': 0.5280526917428219, 'colsample_bytree': 0.8530357832998374, 'min_child_weight': 7, 'gamma': 2.3783046706145736, 'reg_alpha': 0.172670433265017, 'reg_lambda': 9.826995868861789e-05, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  32%|███▏      | 63/200 [01:09<01:58,  1.16it/s]

[I 2025-11-10 14:21:43,778] Trial 61 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.06821441935116561, 'n_estimators': 998, 'subsample': 0.7322731748476761, 'colsample_bytree': 0.8471989297713093, 'min_child_weight': 7, 'gamma': 2.3590219815415576, 'reg_alpha': 0.18692259828573765, 'reg_lambda': 9.837269590090324e-05, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  32%|███▏      | 64/200 [01:10<02:13,  1.02it/s]

[I 2025-11-10 14:21:45,044] Trial 66 pruned.

Best trial: 2. Best value: 0.5:  32%|███▎      | 65/200 [01:11<02:15,  1.00s/it]

[I 2025-11-10 14:21:46,104] Trial 63 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04966002400496014, 'n_estimators': 1243, 'subsample': 0.7332113341273468, 'colsample_bytree': 0.7675320872655667, 'min_child_weight': 7, 'gamma': 2.1178504735445687, 'reg_alpha': 0.2513867931038948, 'reg_lambda': 8.699948085163082e-05, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  33%|███▎      | 66/200 [01:12<02:11,  1.02it/s]

[I 2025-11-10 14:21:47,034] Trial 68 pruned.

Best trial: 2. Best value: 0.5:  34%|███▎      | 67/200 [01:13<02:05,  1.06it/s]

[I 2025-11-10 14:21:47,882] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.04739920394352394, 'n_estimators': 1240, 'subsample': 0.5671507685920305, 'colsample_bytree': 0.8869839502687727, 'min_child_weight': 10, 'gamma': 0.9608665051639245, 'reg_alpha': 0.00016671108930320667, 'reg_lambda': 3.0098476828087657, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 65. Best value: 0.508889:  34%|███▍      | 68/200 [01:14<02:17,  1.04s/it]

[I 2025-11-10 14:21:49,157] Trial 65 finished with value: 0.5088888888888888 and parameters: {'max_depth': 7, 'learning_rate': 0.04962131741930602, 'n_estimators': 1243, 'subsample': 0.5719483330582805, 'colsample_bytree': 0.8879790827534604, 'min_child_weight': 4, 'gamma': 0.32215142181705003, 'reg_alpha': 1.66829548015714e-05, 'reg_lambda': 3.0949911320617116, 'max_delta_step': 9}. Best is trial 65 with value: 0.5088888888888888.

Best trial: 65. Best value: 0.508889:  34%|███▍      | 69/200 [01:15<02:14,  1.03s/it]

[I 2025-11-10 14:21:50,148] Trial 71 pruned.

Best trial: 67. Best value: 0.526667:  35%|███▌      | 70/200 [01:15<01:55,  1.13it/s]

[I 2025-11-10 14:21:50,714] Trial 67 finished with value: 0.5266666666666666 and parameters: {'max_depth': 7, 'learning_rate': 0.05075684667476908, 'n_estimators': 1224, 'subsample': 0.57901399025215, 'colsample_bytree': 0.9648209459617578, 'min_child_weight': 4, 'gamma': 0.22090647724400894, 'reg_alpha': 1.8602266208930516e-05, 'reg_lambda': 4.038863041859815e-08, 'max_delta_step': 10}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 67. Best value: 0.526667:  36%|███▌      | 71/200 [01:16<01:59,  1.08it/s]

[I 2025-11-10 14:21:51,742] Trial 73 pruned.

Best trial: 67. Best value: 0.526667:  36%|███▌      | 72/200 [01:17<01:42,  1.25it/s]

[I 2025-11-10 14:21:52,232] Trial 69 finished with value: 0.5077777777777778 and parameters: {'max_depth': 10, 'learning_rate': 0.021068898148928768, 'n_estimators': 1146, 'subsample': 0.5982504113370891, 'colsample_bytree': 0.9684587014195161, 'min_child_weight': 4, 'gamma': 0.9331694487565858, 'reg_alpha': 0.0010100043961223406, 'reg_lambda': 5.467119649835968, 'max_delta_step': 0}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 67. Best value: 0.526667:  36%|███▋      | 73/200 [01:18<01:47,  1.18it/s]

[I 2025-11-10 14:21:53,200] Trial 70 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.29144844400185876, 'n_estimators': 1162, 'subsample': 0.6019870828729845, 'colsample_bytree': 0.9625688659009031, 'min_child_weight': 6, 'gamma': 4.169014772306616, 'reg_alpha': 0.0069873307472519885, 'reg_lambda': 1.3062027957348957e-06, 'max_delta_step': 4}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 67. Best value: 0.526667:  37%|███▋      | 74/200 [01:19<02:07,  1.01s/it]

[I 2025-11-10 14:21:54,580] Trial 72 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.022686821311827296, 'n_estimators': 973, 'subsample': 0.5946282674055019, 'colsample_bytree': 0.9581672587546838, 'min_child_weight': 6, 'gamma': 0.6798368188808747, 'reg_alpha': 2.2769826261832317e-06, 'reg_lambda': 5.1467658119047594e-08, 'max_delta_step': 0}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 67. Best value: 0.526667:  38%|███▊      | 75/200 [01:22<03:16,  1.57s/it]

[I 2025-11-10 14:21:57,461] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.02009567427448288, 'n_estimators': 1167, 'subsample': 0.5478573946097812, 'colsample_bytree': 0.9744576034470002, 'min_child_weight': 4, 'gamma': 0.46261016708063035, 'reg_alpha': 0.001075045862039361, 'reg_lambda': 4.588220007765093e-08, 'max_delta_step': 0}. Best is trial 67 with value: 0.5266666666666666.
[I 2025-11-10 14:21:57,461] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.04196981954785021, 'n_estimators': 1271, 'subsample': 0.6010318699582737, 'colsample_bytree': 0.9660006607066255, 'min_child_weight': 6, 'gamma': 0.1818123822770115, 'reg_alpha': 1.5908343635283191e-06, 'reg_lambda': 5.988101156903642e-08, 'max_delta_step': 10}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 67. Best value: 0.526667:  38%|███▊      | 77/200 [01:24<02:22,  1.16s/it]

[I 2025-11-10 14:21:58,803] Trial 76 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.022597229664935027, 'n_estimators': 1276, 'subsample': 0.5190246357381191, 'colsample_bytree': 0.9472746316309815, 'min_child_weight': 4, 'gamma': 0.6960790714225582, 'reg_alpha': 1.532113745054363e-06, 'reg_lambda': 7.320144831305007e-08, 'max_delta_step': 0}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 67. Best value: 0.526667:  39%|███▉      | 78/200 [01:24<01:54,  1.07it/s]

[I 2025-11-10 14:21:59,065] Trial 79 pruned.

Best trial: 67. Best value: 0.526667:  40%|███▉      | 79/200 [01:25<02:08,  1.06s/it]

[I 2025-11-10 14:22:00,493] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.020385920851515183, 'n_estimators': 1272, 'subsample': 0.5431461911433373, 'colsample_bytree': 0.9817172839885567, 'min_child_weight': 4, 'gamma': 0.5444562114566579, 'reg_alpha': 2.4344227880794668e-05, 'reg_lambda': 6.847530534347164, 'max_delta_step': 10}. Best is trial 67 with value: 0.5266666666666666.
[I 2025-11-10 14:22:00,512] Trial 81 pruned.

Best trial: 67. Best value: 0.526667:  40%|████      | 81/200 [01:26<01:23,  1.43it/s]

[I 2025-11-10 14:22:00,924] Trial 80 pruned.

Best trial: 67. Best value: 0.526667:  41%|████      | 82/200 [01:27<01:33,  1.26it/s]

[I 2025-11-10 14:22:02,032] Trial 82 pruned.

Best trial: 67. Best value: 0.526667:  42%|████▏     | 83/200 [01:29<02:04,  1.06s/it]

[I 2025-11-10 14:22:03,882] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.013141343875045414, 'n_estimators': 1415, 'subsample': 0.5150039530776503, 'colsample_bytree': 0.9152414537232594, 'min_child_weight': 4, 'gamma': 0.7408070949832499, 'reg_alpha': 7.108245569413768e-05, 'reg_lambda': 1.7765842751354624, 'max_delta_step': 8}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 67. Best value: 0.526667:  42%|████▏     | 84/200 [01:29<01:52,  1.03it/s]

[I 2025-11-10 14:22:04,594] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.010146666147891163, 'n_estimators': 898, 'subsample': 0.6297282073107484, 'colsample_bytree': 0.921462056242571, 'min_child_weight': 5, 'gamma': 1.1043779318742404, 'reg_alpha': 0.001066562311416047, 'reg_lambda': 1.0886447809293054, 'max_delta_step': 6}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 67. Best value: 0.526667:  42%|████▎     | 85/200 [01:31<02:09,  1.13s/it]

[I 2025-11-10 14:22:06,138] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.052467953030028096, 'n_estimators': 906, 'subsample': 0.6284464109861481, 'colsample_bytree': 0.9063214935118628, 'min_child_weight': 8, 'gamma': 0.18678121276792878, 'reg_alpha': 0.003005990678285463, 'reg_lambda': 0.21659085876938394, 'max_delta_step': 0}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 67. Best value: 0.526667:  43%|████▎     | 86/200 [01:31<01:38,  1.15it/s]

[I 2025-11-10 14:22:06,340] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.0105147796405598, 'n_estimators': 1208, 'subsample': 0.6248275173474899, 'colsample_bytree': 0.9420336055799318, 'min_child_weight': 5, 'gamma': 0.17794845966442735, 'reg_alpha': 4.532606540612213, 'reg_lambda': 1.637174581449178, 'max_delta_step': 0}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 67. Best value: 0.526667:  44%|████▎     | 87/200 [01:32<01:44,  1.08it/s]

[I 2025-11-10 14:22:07,398] Trial 89 pruned.

Best trial: 67. Best value: 0.526667:  44%|████▍     | 88/200 [01:32<01:24,  1.33it/s]

[I 2025-11-10 14:22:07,735] Trial 88 pruned.

Best trial: 67. Best value: 0.526667:  44%|████▍     | 89/200 [01:33<01:29,  1.24it/s]

[I 2025-11-10 14:22:08,687] Trial 90 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03430009070195724, 'n_estimators': 202, 'subsample': 0.6710334493039398, 'colsample_bytree': 0.978416449020426, 'min_child_weight': 8, 'gamma': 3.9384559013408937, 'reg_alpha': 0.00028081241773947395, 'reg_lambda': 0.016120107619292046, 'max_delta_step': 5}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 67. Best value: 0.526667:  45%|████▌     | 90/200 [01:34<01:14,  1.47it/s]

[I 2025-11-10 14:22:09,060] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.051527101202114685, 'n_estimators': 1116, 'subsample': 0.6350027913518264, 'colsample_bytree': 0.9027904901358722, 'min_child_weight': 5, 'gamma': 0.10332541758985597, 'reg_alpha': 0.0011165380783848481, 'reg_lambda': 0.14641481014017027, 'max_delta_step': 1}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 67. Best value: 0.526667:  46%|████▌     | 91/200 [01:34<01:05,  1.66it/s]

[I 2025-11-10 14:22:09,469] Trial 87 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.052425567307219756, 'n_estimators': 1061, 'subsample': 0.6484553855735703, 'colsample_bytree': 0.944690808253422, 'min_child_weight': 8, 'gamma': 2.918903269623779, 'reg_alpha': 0.7080005271324207, 'reg_lambda': 0.01726963239884943, 'max_delta_step': 1}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 67. Best value: 0.526667:  46%|████▌     | 92/200 [01:39<03:12,  1.78s/it]

[I 2025-11-10 14:22:14,035] Trial 91 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03617554124599795, 'n_estimators': 1105, 'subsample': 0.5004080787379399, 'colsample_bytree': 0.9740447884429706, 'min_child_weight': 5, 'gamma': 0.381980623546364, 'reg_alpha': 0.00023363305113669543, 'reg_lambda': 0.004604290696233251, 'max_delta_step': 3}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 67. Best value: 0.526667:  46%|████▋     | 93/200 [01:40<02:42,  1.52s/it]

[I 2025-11-10 14:22:14,952] Trial 92 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09746840687346718, 'n_estimators': 1113, 'subsample': 0.5864895189908517, 'colsample_bytree': 0.8655774506338263, 'min_child_weight': 9, 'gamma': 4.309541909064056, 'reg_alpha': 0.05209182161752724, 'reg_lambda': 0.061611624105411496, 'max_delta_step': 4}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 67. Best value: 0.526667:  47%|████▋     | 94/200 [01:40<02:13,  1.26s/it]

[I 2025-11-10 14:22:15,588] Trial 93 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.15382199968463214, 'n_estimators': 1192, 'subsample': 0.584110978399474, 'colsample_bytree': 0.7449567323334592, 'min_child_weight': 10, 'gamma': 0.41123703865459416, 'reg_alpha': 0.07015287444055354, 'reg_lambda': 0.5955939793198656, 'max_delta_step': 7}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 67. Best value: 0.526667:  48%|████▊     | 95/200 [01:41<01:59,  1.14s/it]

[I 2025-11-10 14:22:16,437] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03560842373405224, 'n_estimators': 1316, 'subsample': 0.585614445428245, 'colsample_bytree': 0.7480276595955088, 'min_child_weight': 4, 'gamma': 4.3200489503744315, 'reg_alpha': 0.0001568546526825723, 'reg_lambda': 0.7482002188913246, 'max_delta_step': 10}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 67. Best value: 0.526667:  48%|████▊     | 96/200 [01:45<03:11,  1.84s/it]

[I 2025-11-10 14:22:19,918] Trial 95 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.041053892561911526, 'n_estimators': 1322, 'subsample': 0.5550889763003569, 'colsample_bytree': 0.8658479823415842, 'min_child_weight': 4, 'gamma': 0.8759689580337758, 'reg_alpha': 3.498399935745801e-05, 'reg_lambda': 9.549767887986762, 'max_delta_step': 7}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 67. Best value: 0.526667:  48%|████▊     | 97/200 [01:45<02:34,  1.50s/it]

[I 2025-11-10 14:22:20,634] Trial 96 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.0407577261074005, 'n_estimators': 1311, 'subsample': 0.6059258577117801, 'colsample_bytree': 0.8219094689006486, 'min_child_weight': 4, 'gamma': 4.890567312547359, 'reg_alpha': 3.4634733990574965e-05, 'reg_lambda': 4.938999370533219, 'max_delta_step': 10}. Best is trial 67 with value: 0.5266666666666666.

Best trial: 97. Best value: 0.547135:  49%|████▉     | 98/200 [01:46<02:03,  1.21s/it]

[I 2025-11-10 14:22:21,171] Trial 97 finished with value: 0.5471345029239766 and parameters: {'max_depth': 10, 'learning_rate': 0.041489419476377846, 'n_estimators': 1303, 'subsample': 0.6052718026894885, 'colsample_bytree': 0.8300082429194923, 'min_child_weight': 4, 'gamma': 0.01892426491410157, 'reg_alpha': 3.350243348856222e-05, 'reg_lambda': 4.606765872045982, 'max_delta_step': 10}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  50%|████▉     | 99/200 [01:46<01:42,  1.02s/it]

[I 2025-11-10 14:22:21,739] Trial 98 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.042378973814552134, 'n_estimators': 1224, 'subsample': 0.5577155834141184, 'colsample_bytree': 0.9560378981305726, 'min_child_weight': 7, 'gamma': 0.002687994792051923, 'reg_alpha': 5.2642406269927146e-05, 'reg_lambda': 9.456102688143107, 'max_delta_step': 7}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  50%|█████     | 100/200 [01:50<02:50,  1.70s/it]

[I 2025-11-10 14:22:25,043] Trial 99 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.059691971400105896, 'n_estimators': 1221, 'subsample': 0.6061329048634931, 'colsample_bytree': 0.9252905452401975, 'min_child_weight': 7, 'gamma': 3.2789123507074334, 'reg_alpha': 0.0006294232181426168, 'reg_lambda': 4.285432768884566, 'max_delta_step': 6}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  50%|█████     | 101/200 [01:50<02:18,  1.40s/it]

[I 2025-11-10 14:22:25,724] Trial 100 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.027164286533602564, 'n_estimators': 1233, 'subsample': 0.7984193457511345, 'colsample_bytree': 0.8405074617405965, 'min_child_weight': 7, 'gamma': 0.9841708532741229, 'reg_alpha': 9.704509140820264e-05, 'reg_lambda': 2.5542903859617496, 'max_delta_step': 8}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  51%|█████     | 102/200 [01:51<01:53,  1.16s/it]

[I 2025-11-10 14:22:26,316] Trial 104 pruned.

Best trial: 97. Best value: 0.547135:  52%|█████▏    | 103/200 [01:52<01:51,  1.15s/it]

[I 2025-11-10 14:22:27,440] Trial 101 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.027668694020175726, 'n_estimators': 1440, 'subsample': 0.5708586598600963, 'colsample_bytree': 0.9550751053473441, 'min_child_weight': 7, 'gamma': 0.08667804051362685, 'reg_alpha': 0.00011222467719635986, 'reg_lambda': 3.068463095914093e-07, 'max_delta_step': 6}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  52%|█████▏    | 104/200 [01:53<01:28,  1.09it/s]

[I 2025-11-10 14:22:27,833] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.027004609993084006, 'n_estimators': 582, 'subsample': 0.6961078387112106, 'colsample_bytree': 0.8385808630032288, 'min_child_weight': 6, 'gamma': 0.3071885258766841, 'reg_alpha': 5.65857532725756e-06, 'reg_lambda': 4.983735675552923e-07, 'max_delta_step': 10}. Best is trial 97 with value: 0.5471345029239766.
[I 2025-11-10 14:22:27,837] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.031004233878186863, 'n_estimators': 1450, 'subsample': 0.7905110622091807, 'colsample_bytree': 0.832532579925995, 'min_child_weight': 6, 'gamma': 0.2837431540701845, 'reg_alpha': 2.1267773598452216e-07, 'reg_lambda': 0.0014276562815798617, 'max_delta_step': 6}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  53%|█████▎    | 106/200 [01:54<01:10,  1.34it/s]

[I 2025-11-10 14:22:28,926] Trial 108 pruned.

Best trial: 97. Best value: 0.547135:  54%|█████▎    | 107/200 [01:55<01:22,  1.13it/s]

[I 2025-11-10 14:22:30,234] Trial 109 pruned.

Best trial: 97. Best value: 0.547135:  54%|█████▍    | 108/200 [01:56<01:30,  1.02it/s]

[I 2025-11-10 14:22:31,472] Trial 107 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.04424099105090701, 'n_estimators': 758, 'subsample': 0.5425691820358418, 'colsample_bytree': 0.8799184338707677, 'min_child_weight': 4, 'gamma': 0.7981140393530934, 'reg_alpha': 1.0534859081152418e-05, 'reg_lambda': 3.9854879887243935, 'max_delta_step': 10}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  55%|█████▍    | 109/200 [01:57<01:13,  1.25it/s]

[I 2025-11-10 14:22:31,800] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.046015365927171925, 'n_estimators': 1175, 'subsample': 0.5660993785603924, 'colsample_bytree': 0.8810009985621946, 'min_child_weight': 4, 'gamma': 0.30310413580773454, 'reg_alpha': 1.3879871440131111e-05, 'reg_lambda': 9.113211008911363e-07, 'max_delta_step': 10}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  55%|█████▌    | 110/200 [01:57<01:04,  1.39it/s]

[I 2025-11-10 14:22:32,318] Trial 110 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.044103560638871775, 'n_estimators': 382, 'subsample': 0.6194378024717249, 'colsample_bytree': 0.9881783918106655, 'min_child_weight': 5, 'gamma': 3.1882493236252634, 'reg_alpha': 0.0018469432093686166, 'reg_lambda': 0.0002393749165127099, 'max_delta_step': 4}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  56%|█████▌    | 111/200 [01:58<01:03,  1.40it/s]

[I 2025-11-10 14:22:33,011] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.015575967296378515, 'n_estimators': 1153, 'subsample': 0.6213026995062342, 'colsample_bytree': 0.8738719553547772, 'min_child_weight': 6, 'gamma': 0.2514314778084446, 'reg_alpha': 1.2514779605889042e-05, 'reg_lambda': 2.2266447480593827, 'max_delta_step': 10}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  56%|█████▌    | 112/200 [01:58<00:59,  1.47it/s]

[I 2025-11-10 14:22:33,608] Trial 111 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03868027613957947, 'n_estimators': 414, 'subsample': 0.6186080539910462, 'colsample_bytree': 0.5746611611877677, 'min_child_weight': 5, 'gamma': 3.629018766338937, 'reg_alpha': 0.00044634573548722663, 'reg_lambda': 0.0001779803593272647, 'max_delta_step': 4}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  56%|█████▋    | 113/200 [02:02<02:13,  1.54s/it]

[I 2025-11-10 14:22:37,213] Trial 112 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.12257001873885884, 'n_estimators': 1021, 'subsample': 0.7610350865045274, 'colsample_bytree': 0.9353274182118992, 'min_child_weight': 5, 'gamma': 2.5998978124962244, 'reg_alpha': 2.377566488850856e-05, 'reg_lambda': 0.0002928372864824451, 'max_delta_step': 4}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  57%|█████▋    | 114/200 [02:02<01:42,  1.20s/it]

[I 2025-11-10 14:22:37,599] Trial 113 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03912302270609821, 'n_estimators': 1019, 'subsample': 0.6707499323418478, 'colsample_bytree': 0.9100140285766127, 'min_child_weight': 5, 'gamma': 2.1254132064707267, 'reg_alpha': 0.00036688928846222954, 'reg_lambda': 5.786284625995895, 'max_delta_step': 0}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  57%|█████▊    | 115/200 [02:04<02:02,  1.45s/it]

[I 2025-11-10 14:22:39,639] Trial 114 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.024604173949932594, 'n_estimators': 1290, 'subsample': 0.6077978045511875, 'colsample_bytree': 0.9103677275717538, 'min_child_weight': 8, 'gamma': 1.2686872087588688, 'reg_alpha': 0.010860588795370144, 'reg_lambda': 0.9114187219319504, 'max_delta_step': 3}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  58%|█████▊    | 116/200 [02:05<01:51,  1.32s/it]

[I 2025-11-10 14:22:40,666] Trial 115 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02420726993303479, 'n_estimators': 1380, 'subsample': 0.662050378259568, 'colsample_bytree': 0.9070272391790544, 'min_child_weight': 9, 'gamma': 2.573581903173424, 'reg_alpha': 0.00844793405747819, 'reg_lambda': 2.523299811789143e-08, 'max_delta_step': 3}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  58%|█████▊    | 117/200 [02:08<02:29,  1.80s/it]

[I 2025-11-10 14:22:43,574] Trial 116 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.023811182012257636, 'n_estimators': 1291, 'subsample': 0.6561083029510262, 'colsample_bytree': 0.8952868868628147, 'min_child_weight': 8, 'gamma': 1.4716974143556065, 'reg_alpha': 0.0064957104876411445, 'reg_lambda': 0.000500694709209714, 'max_delta_step': 3}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  59%|█████▉    | 118/200 [02:09<01:55,  1.41s/it]

[I 2025-11-10 14:22:44,071] Trial 117 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.033412137044725405, 'n_estimators': 1296, 'subsample': 0.7201312675641647, 'colsample_bytree': 0.8928617144669719, 'min_child_weight': 10, 'gamma': 1.4591560268299837, 'reg_alpha': 0.005264305632911875, 'reg_lambda': 2.1571783552056425e-06, 'max_delta_step': 5}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  60%|█████▉    | 119/200 [02:11<02:17,  1.70s/it]

[I 2025-11-10 14:22:46,463] Trial 118 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.034220086956967856, 'n_estimators': 1362, 'subsample': 0.6623445681448286, 'colsample_bytree': 0.8963841270048003, 'min_child_weight': 7, 'gamma': 0.9935242757104282, 'reg_alpha': 0.004825165122587509, 'reg_lambda': 1.2853431726899196, 'max_delta_step': 5}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  60%|██████    | 120/200 [02:12<01:52,  1.40s/it]

[I 2025-11-10 14:22:47,173] Trial 119 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.034521643699335934, 'n_estimators': 1296, 'subsample': 0.5907726454279966, 'colsample_bytree': 0.8947413787039846, 'min_child_weight': 10, 'gamma': 1.7139506230563708, 'reg_alpha': 0.003494461575408095, 'reg_lambda': 0.21837112777169124, 'max_delta_step': 5}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  60%|██████    | 121/200 [02:14<02:00,  1.53s/it]

[I 2025-11-10 14:22:48,987] Trial 121 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.021060684013382208, 'n_estimators': 971, 'subsample': 0.5219592092385664, 'colsample_bytree': 0.9268540801322794, 'min_child_weight': 7, 'gamma': 1.8512361331907332, 'reg_alpha': 0.019153686632201298, 'reg_lambda': 1.3626074978638116, 'max_delta_step': 2}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  61%|██████    | 122/200 [02:16<02:08,  1.65s/it]

[I 2025-11-10 14:22:50,911] Trial 122 finished with value: 0.5011111111111111 and parameters: {'max_depth': 8, 'learning_rate': 0.05548387878306339, 'n_estimators': 828, 'subsample': 0.5934783109387498, 'colsample_bytree': 0.927032046857103, 'min_child_weight': 4, 'gamma': 1.9279125169074338, 'reg_alpha': 0.02210937123541117, 'reg_lambda': 0.23828516663548027, 'max_delta_step': 9}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  62%|██████▏   | 123/200 [02:16<01:34,  1.22s/it]

[I 2025-11-10 14:22:51,132] Trial 120 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03226628068399159, 'n_estimators': 1337, 'subsample': 0.5250067201062573, 'colsample_bytree': 0.9318107913025304, 'min_child_weight': 10, 'gamma': 4.612325381468713, 'reg_alpha': 0.00432852602910806, 'reg_lambda': 1.3990255783010692, 'max_delta_step': 5}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  62%|██████▏   | 124/200 [02:17<01:18,  1.03s/it]

[I 2025-11-10 14:22:51,725] Trial 125 pruned.
[I 2025-11-10 14:22:51,819] Trial 123 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.021414666999086524, 'n_estimators': 840, 'subsample': 0.5501135757302407, 'colsample_bytree': 0.9252866482308408, 'min_child_weight': 4, 'gamma': 2.0133275306325618, 'reg_alpha': 0.0008883225606396174, 'reg_lambda': 9.645475043130336e-08, 'max_delta_step': 9}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  63%|██████▎   | 126/200 [02:17<00:55,  1.33it/s]

[I 2025-11-10 14:22:52,573] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.2613158143002395, 'n_estimators': 650, 'subsample': 0.5483613775423558, 'colsample_bytree': 0.7830132525952691, 'min_child_weight': 9, 'gamma': 3.9821238693314607, 'reg_alpha': 0.0016171537362025424, 'reg_lambda': 9.847698431312514e-08, 'max_delta_step': 9}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  64%|██████▎   | 127/200 [02:18<00:58,  1.25it/s]

[I 2025-11-10 14:22:53,530] Trial 128 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.01881863161122945, 'n_estimators': 308, 'subsample': 0.5935018858339722, 'colsample_bytree': 0.7748063333861246, 'min_child_weight': 4, 'gamma': 2.289933531659171, 'reg_alpha': 0.02888407558825624, 'reg_lambda': 3.55280462710601, 'max_delta_step': 8}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  64%|██████▍   | 128/200 [02:19<01:04,  1.11it/s]

[I 2025-11-10 14:22:54,704] Trial 130 pruned.

Best trial: 97. Best value: 0.547135:  64%|██████▍   | 129/200 [02:20<01:05,  1.08it/s]

[I 2025-11-10 14:22:55,696] Trial 126 finished with value: 0.48625730994152044 and parameters: {'max_depth': 7, 'learning_rate': 0.05435588767362256, 'n_estimators': 841, 'subsample': 0.6387701439432049, 'colsample_bytree': 0.9415686826738671, 'min_child_weight': 4, 'gamma': 2.0767979075410534, 'reg_alpha': 0.09132197972496728, 'reg_lambda': 4.042919458366726, 'max_delta_step': 9}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  66%|██████▌   | 131/200 [02:21<00:41,  1.68it/s]

[I 2025-11-10 14:22:56,079] Trial 131 pruned.
[I 2025-11-10 14:22:56,237] Trial 127 finished with value: 0.4988888888888889 and parameters: {'max_depth': 6, 'learning_rate': 0.018665785681472834, 'n_estimators': 829, 'subsample': 0.5966930645988884, 'colsample_bytree': 0.9605642002275063, 'min_child_weight': 4, 'gamma': 2.2751687500996116, 'reg_alpha': 0.002250974088057571, 'reg_lambda': 0.034158095117949164, 'max_delta_step': 9}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  66%|██████▌   | 132/200 [02:22<00:47,  1.42it/s]

[I 2025-11-10 14:22:57,199] Trial 132 pruned.

Best trial: 97. Best value: 0.547135:  66%|██████▋   | 133/200 [02:24<01:12,  1.08s/it]

[I 2025-11-10 14:22:59,203] Trial 129 finished with value: 0.5259649122807017 and parameters: {'max_depth': 6, 'learning_rate': 0.050189252587338105, 'n_estimators': 1196, 'subsample': 0.5942004922025711, 'colsample_bytree': 0.9615155744913144, 'min_child_weight': 4, 'gamma': 0.15883345990469375, 'reg_alpha': 0.030191701915441047, 'reg_lambda': 0.03885812302483978, 'max_delta_step': 8}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  67%|██████▋   | 134/200 [02:25<01:17,  1.18s/it]

[I 2025-11-10 14:23:00,610] Trial 136 pruned.

Best trial: 97. Best value: 0.547135:  68%|██████▊   | 136/200 [02:26<00:45,  1.40it/s]

[I 2025-11-10 14:23:01,102] Trial 134 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.22368799839457323, 'n_estimators': 899, 'subsample': 0.5610167866308963, 'colsample_bytree': 0.8123442474852706, 'min_child_weight': 10, 'gamma': 0.00021030641346331258, 'reg_alpha': 2.127760676426167e-05, 'reg_lambda': 2.8077435503607383e-08, 'max_delta_step': 10}. Best is trial 97 with value: 0.5471345029239766.
[I 2025-11-10 14:23:01,209] Trial 133 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.06263687675968409, 'n_estimators': 895, 'subsample': 0.6082805239573622, 'colsample_bytree': 0.9512814193101765, 'min_child_weight': 6, 'gamma': 1.1559559545805311, 'reg_alpha': 2.539113809642964, 'reg_lambda': 0.366389178374067, 'max_delta_step': 8}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  68%|██████▊   | 137/200 [02:27<00:48,  1.29it/s]

[I 2025-11-10 14:23:02,115] Trial 135 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.16229073300319577, 'n_estimators': 894, 'subsample': 0.5602097229153399, 'colsample_bytree': 0.8028273078640363, 'min_child_weight': 10, 'gamma': 0.005706117864151414, 'reg_alpha': 1.7222205017238906e-05, 'reg_lambda': 3.709109704301335e-08, 'max_delta_step': 10}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  69%|██████▉   | 138/200 [02:27<00:41,  1.51it/s]

[I 2025-11-10 14:23:02,517] Trial 139 pruned.

Best trial: 97. Best value: 0.547135:  70%|██████▉   | 139/200 [02:30<01:16,  1.25s/it]

[I 2025-11-10 14:23:05,149] Trial 137 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.049634797564248614, 'n_estimators': 898, 'subsample': 0.5627302421869107, 'colsample_bytree': 0.9829997397219025, 'min_child_weight': 5, 'gamma': 0.1612450199714733, 'reg_alpha': 0.3025464069153644, 'reg_lambda': 0.06043164695341517, 'max_delta_step': 10}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  70%|███████   | 140/200 [02:31<01:09,  1.15s/it]

[I 2025-11-10 14:23:06,071] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04985993286280908, 'n_estimators': 756, 'subsample': 0.5796047331902295, 'colsample_bytree': 0.9145797619383814, 'min_child_weight': 5, 'gamma': 0.8100632547282242, 'reg_alpha': 0.013728352033111808, 'reg_lambda': 0.012147300527329399, 'max_delta_step': 9}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  70%|███████   | 141/200 [02:31<00:51,  1.14it/s]

[I 2025-11-10 14:23:06,294] Trial 142 pruned.
[I 2025-11-10 14:23:06,317] Trial 138 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.0509455648882649, 'n_estimators': 1079, 'subsample': 0.5747096928836799, 'colsample_bytree': 0.9171003574631819, 'min_child_weight': 6, 'gamma': 1.3411542119211235, 'reg_alpha': 0.013560253864461096, 'reg_lambda': 0.06116656206111309, 'max_delta_step': 9}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  72%|███████▏  | 143/200 [02:32<00:41,  1.38it/s]

[I 2025-11-10 14:23:07,402] Trial 144 pruned.

Best trial: 97. Best value: 0.547135:  72%|███████▏  | 144/200 [02:32<00:34,  1.60it/s]

[I 2025-11-10 14:23:07,715] Trial 140 finished with value: 0.5411111111111111 and parameters: {'max_depth': 6, 'learning_rate': 0.0361100670134233, 'n_estimators': 1128, 'subsample': 0.5788155052950785, 'colsample_bytree': 0.9816907796754717, 'min_child_weight': 4, 'gamma': 0.129202723161356, 'reg_alpha': 5.804149409838944e-05, 'reg_lambda': 0.007686669766802276, 'max_delta_step': 9}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  72%|███████▎  | 145/200 [02:33<00:38,  1.43it/s]

[I 2025-11-10 14:23:08,628] Trial 147 pruned.

Best trial: 97. Best value: 0.547135:  73%|███████▎  | 146/200 [02:37<01:13,  1.36s/it]

[I 2025-11-10 14:23:11,742] Trial 145 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.20155201306160012, 'n_estimators': 1130, 'subsample': 0.51080734899358, 'colsample_bytree': 0.8538015040950018, 'min_child_weight': 4, 'gamma': 3.3728499278203596, 'reg_alpha': 5.227345744298779e-05, 'reg_lambda': 9.709487231842065, 'max_delta_step': 6}. Best is trial 97 with value: 0.5471345029239766.
[I 2025-11-10 14:23:11,797] Trial 143 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.016931221971266033, 'n_estimators': 1138, 'subsample': 0.5993719775384537, 'colsample_bytree': 0.9382240780813331, 'min_child_weight': 7, 'gamma': 0.37036893947878413, 'reg_alpha': 5.541854052781593e-05, 'reg_lambda': 0.09451934428021216, 'max_delta_step': 6}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  74%|███████▍  | 148/200 [02:38<00:52,  1.02s/it]

[I 2025-11-10 14:23:12,910] Trial 149 pruned.
[I 2025-11-10 14:23:12,951] Trial 150 pruned.

Best trial: 97. Best value: 0.547135:  75%|███████▌  | 150/200 [02:38<00:33,  1.50it/s]

[I 2025-11-10 14:23:13,123] Trial 146 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03731397603356794, 'n_estimators': 1188, 'subsample': 0.5349991980621336, 'colsample_bytree': 0.7620560337182838, 'min_child_weight': 7, 'gamma': 4.449850961760793, 'reg_alpha': 3.8035111726617356e-05, 'reg_lambda': 1.6076293721882342e-08, 'max_delta_step': 10}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  76%|███████▌  | 151/200 [02:39<00:37,  1.31it/s]

[I 2025-11-10 14:23:14,231] Trial 151 pruned.

Best trial: 97. Best value: 0.547135:  76%|███████▌  | 152/200 [02:39<00:33,  1.42it/s]

[I 2025-11-10 14:23:14,736] Trial 148 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.043595066294152, 'n_estimators': 1186, 'subsample': 0.617668477265869, 'colsample_bytree': 0.969798679847132, 'min_child_weight': 7, 'gamma': 0.3152982057166148, 'reg_alpha': 0.00015693785609337176, 'reg_lambda': 0.023343408885186993, 'max_delta_step': 9}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  76%|███████▋  | 153/200 [02:40<00:34,  1.37it/s]

[I 2025-11-10 14:23:15,551] Trial 154 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03175338528591021, 'n_estimators': 260, 'subsample': 0.5833833313732381, 'colsample_bytree': 0.9507847982941625, 'min_child_weight': 9, 'gamma': 3.0115255603633178, 'reg_alpha': 2.7063227972799338e-05, 'reg_lambda': 0.0224114773199189, 'max_delta_step': 10}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  77%|███████▋  | 154/200 [02:42<00:43,  1.06it/s]

[I 2025-11-10 14:23:17,074] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.17959474625248284, 'n_estimators': 474, 'subsample': 0.5845920980446037, 'colsample_bytree': 0.9553936782231286, 'min_child_weight': 9, 'gamma': 4.800880323571585, 'reg_alpha': 0.00027437227338556857, 'reg_lambda': 5.960484009234248, 'max_delta_step': 10}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  78%|███████▊  | 155/200 [02:43<00:42,  1.05it/s]

[I 2025-11-10 14:23:18,055] Trial 157 pruned.

Best trial: 97. Best value: 0.547135:  78%|███████▊  | 156/200 [02:44<00:39,  1.10it/s]

[I 2025-11-10 14:23:18,847] Trial 152 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02944094689949432, 'n_estimators': 1199, 'subsample': 0.6512578733591747, 'colsample_bytree': 0.9499827831442739, 'min_child_weight': 9, 'gamma': 4.41295200867202, 'reg_alpha': 0.0007438806496521786, 'reg_lambda': 2.2468863803547188, 'max_delta_step': 9}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  78%|███████▊  | 157/200 [02:44<00:30,  1.40it/s]

[I 2025-11-10 14:23:19,085] Trial 153 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.030023147681033705, 'n_estimators': 1242, 'subsample': 0.6469010256087663, 'colsample_bytree': 0.9513714191247303, 'min_child_weight': 8, 'gamma': 0.6170299890635484, 'reg_alpha': 0.00027968275076597495, 'reg_lambda': 0.7278803291064364, 'max_delta_step': 1}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  79%|███████▉  | 158/200 [02:45<00:40,  1.03it/s]

[I 2025-11-10 14:23:20,684] Trial 156 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.26154770169982444, 'n_estimators': 984, 'subsample': 0.568308878479555, 'colsample_bytree': 0.9895106624536567, 'min_child_weight': 8, 'gamma': 2.8454597389451566, 'reg_alpha': 0.00026755151740772505, 'reg_lambda': 5.973185518268734, 'max_delta_step': 10}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  80%|███████▉  | 159/200 [02:47<00:46,  1.14s/it]

[I 2025-11-10 14:23:22,232] Trial 161 pruned.
[I 2025-11-10 14:23:22,252] Trial 160 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.057309039461856844, 'n_estimators': 621, 'subsample': 0.5518780393221366, 'colsample_bytree': 0.7876023209373642, 'min_child_weight': 4, 'gamma': 3.631453509338292, 'reg_alpha': 0.111710886262772, 'reg_lambda': 0.22462757842925982, 'max_delta_step': 7}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  80%|████████  | 161/200 [02:49<00:46,  1.19s/it]

[I 2025-11-10 14:23:24,733] Trial 158 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.26759403681624383, 'n_estimators': 1248, 'subsample': 0.6482055312523468, 'colsample_bytree': 0.989335873839682, 'min_child_weight': 8, 'gamma': 0.0817044016885104, 'reg_alpha': 0.0013165042014544298, 'reg_lambda': 2.6830147243569717, 'max_delta_step': 10}. Best is trial 97 with value: 0.5471345029239766.
[I 2025-11-10 14:23:24,743] Trial 159 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.27494326805058106, 'n_estimators': 1245, 'subsample': 0.566352922554777, 'colsample_bytree': 0.7909195001127615, 'min_child_weight': 8, 'gamma': 1.9539900273443769, 'reg_alpha': 0.0015126485719438808, 'reg_lambda': 0.22812864045108416, 'max_delta_step': 8}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  82%|████████▏ | 163/200 [02:51<00:34,  1.07it/s]

[I 2025-11-10 14:23:25,818] Trial 163 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04086241415434143, 'n_estimators': 716, 'subsample': 0.5406196309117984, 'colsample_bytree': 0.9073714461056578, 'min_child_weight': 5, 'gamma': 3.0997203577011256, 'reg_alpha': 9.077267094804305e-06, 'reg_lambda': 3.05276710408928, 'max_delta_step': 9}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  82%|████████▏ | 164/200 [02:53<00:44,  1.24s/it]

[I 2025-11-10 14:23:28,134] Trial 165 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.011204132555948059, 'n_estimators': 730, 'subsample': 0.5343714281811892, 'colsample_bytree': 0.5069677484017843, 'min_child_weight': 5, 'gamma': 4.022295953007897, 'reg_alpha': 9.179348961725491e-06, 'reg_lambda': 1.7068035253511272e-07, 'max_delta_step': 10}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  82%|████████▎ | 165/200 [02:53<00:35,  1.01s/it]

[I 2025-11-10 14:23:28,399] Trial 164 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.012494777319497932, 'n_estimators': 721, 'subsample': 0.5405256394110154, 'colsample_bytree': 0.9033014439362242, 'min_child_weight': 10, 'gamma': 3.4414717256349086, 'reg_alpha': 0.007812370157908585, 'reg_lambda': 1.540315425421339e-08, 'max_delta_step': 10}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  83%|████████▎ | 166/200 [02:53<00:27,  1.24it/s]

[I 2025-11-10 14:23:28,607] Trial 162 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.056198352348430625, 'n_estimators': 1273, 'subsample': 0.5426444790179678, 'colsample_bytree': 0.9060700440253515, 'min_child_weight': 5, 'gamma': 3.6569875321973293, 'reg_alpha': 0.0013082555025401416, 'reg_lambda': 0.002673915701876552, 'max_delta_step': 8}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  84%|████████▎ | 167/200 [02:54<00:28,  1.17it/s]

[I 2025-11-10 14:23:29,584] Trial 166 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.011716806956970926, 'n_estimators': 788, 'subsample': 0.5285677366328186, 'colsample_bytree': 0.5247382323667708, 'min_child_weight': 10, 'gamma': 4.040064874027497, 'reg_alpha': 0.008942733061034987, 'reg_lambda': 1.4501838668645791e-08, 'max_delta_step': 10}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  84%|████████▍ | 168/200 [02:57<00:39,  1.25s/it]

[I 2025-11-10 14:23:31,877] Trial 167 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.23387980361672778, 'n_estimators': 809, 'subsample': 0.5262421415572515, 'colsample_bytree': 0.5465756372730768, 'min_child_weight': 10, 'gamma': 3.841678380524689, 'reg_alpha': 0.05981954216903037, 'reg_lambda': 1.774322434916141e-08, 'max_delta_step': 10}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  84%|████████▍ | 169/200 [02:57<00:32,  1.06s/it]

[I 2025-11-10 14:23:32,482] Trial 168 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.014376724664292299, 'n_estimators': 808, 'subsample': 0.8540128107631518, 'colsample_bytree': 0.639687756334827, 'min_child_weight': 10, 'gamma': 3.8531532456524853, 'reg_alpha': 6.977139914457577e-05, 'reg_lambda': 2.5679310290823165e-08, 'max_delta_step': 10}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  85%|████████▌ | 170/200 [02:57<00:24,  1.23it/s]

[I 2025-11-10 14:23:32,682] Trial 171 pruned.

Best trial: 97. Best value: 0.547135:  86%|████████▌ | 171/200 [02:58<00:20,  1.43it/s]

[I 2025-11-10 14:23:33,088] Trial 169 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.09835655126362987, 'n_estimators': 869, 'subsample': 0.6001464899424978, 'colsample_bytree': 0.9234650889462964, 'min_child_weight': 10, 'gamma': 1.7094290309132796, 'reg_alpha': 1.6519404322165987e-05, 'reg_lambda': 1.682342296526647e-08, 'max_delta_step': 3}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  86%|████████▌ | 172/200 [02:58<00:15,  1.76it/s]

[I 2025-11-10 14:23:33,353] Trial 170 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03383714337786965, 'n_estimators': 750, 'subsample': 0.6030809120606224, 'colsample_bytree': 0.884406174245916, 'min_child_weight': 10, 'gamma': 3.27226783615476, 'reg_alpha': 6.611002085084208e-05, 'reg_lambda': 4.383547751455688, 'max_delta_step': 9}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  86%|████████▋ | 173/200 [03:00<00:28,  1.07s/it]

[I 2025-11-10 14:23:35,617] Trial 174 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03314149475406761, 'n_estimators': 533, 'subsample': 0.7839228919717872, 'colsample_bytree': 0.5074777836626458, 'min_child_weight': 10, 'gamma': 1.0955320095254768, 'reg_alpha': 0.0034520957711504127, 'reg_lambda': 4.4210345103459983e-08, 'max_delta_step': 5}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  87%|████████▋ | 174/200 [03:01<00:25,  1.02it/s]

[I 2025-11-10 14:23:36,369] Trial 172 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.034676950509657516, 'n_estimators': 762, 'subsample': 0.5542428318688466, 'colsample_bytree': 0.7084803830933445, 'min_child_weight': 4, 'gamma': 1.695994037716502, 'reg_alpha': 0.038600465843744415, 'reg_lambda': 9.834929594492646, 'max_delta_step': 3}. Best is trial 97 with value: 0.5471345029239766.
[I 2025-11-10 14:23:36,393] Trial 173 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.0934188872284983, 'n_estimators': 756, 'subsample': 0.6008480842188316, 'colsample_bytree': 0.5965367335652918, 'min_child_weight': 10, 'gamma': 1.6998868943948426, 'reg_alpha': 0.0025688277783251657, 'reg_lambda': 1.0078337607511704e-08, 'max_delta_step': 3}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  88%|████████▊ | 176/200 [03:03<00:23,  1.04it/s]

[I 2025-11-10 14:23:38,267] Trial 175 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.016086270342439198, 'n_estimators': 1059, 'subsample': 0.7556489647396355, 'colsample_bytree': 0.5378477020666428, 'min_child_weight': 10, 'gamma': 1.0174077494923783, 'reg_alpha': 0.02136859398198644, 'reg_lambda': 3.5033918301937434e-07, 'max_delta_step': 5}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  88%|████████▊ | 177/200 [03:06<00:34,  1.50s/it]

[I 2025-11-10 14:23:41,390] Trial 176 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.016220903078543337, 'n_estimators': 1166, 'subsample': 0.8391867852328349, 'colsample_bytree': 0.6041642218369638, 'min_child_weight': 6, 'gamma': 1.537446499146888, 'reg_alpha': 3.696347778341975e-06, 'reg_lambda': 1.0128602901066128e-08, 'max_delta_step': 8}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  89%|████████▉ | 178/200 [03:07<00:26,  1.21s/it]

[I 2025-11-10 14:23:41,778] Trial 177 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.012224915410482772, 'n_estimators': 1153, 'subsample': 0.8301501541326881, 'colsample_bytree': 0.5373767397219429, 'min_child_weight': 10, 'gamma': 1.4346439084424556, 'reg_alpha': 0.0026785093658791555, 'reg_lambda': 0.009867643465256409, 'max_delta_step': 8}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  90%|████████▉ | 179/200 [03:07<00:20,  1.02it/s]

[I 2025-11-10 14:23:42,164] Trial 178 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.012780221062264509, 'n_estimators': 1109, 'subsample': 0.8064910998518713, 'colsample_bytree': 0.8647949725947061, 'min_child_weight': 7, 'gamma': 1.1708352807439506, 'reg_alpha': 3.7899620907767106e-06, 'reg_lambda': 1.745343367359452e-05, 'max_delta_step': 8}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  90%|█████████ | 180/200 [03:08<00:19,  1.01it/s]

[I 2025-11-10 14:23:43,153] Trial 181 pruned.

Best trial: 97. Best value: 0.547135:  90%|█████████ | 181/200 [03:08<00:14,  1.27it/s]

[I 2025-11-10 14:23:43,438] Trial 179 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01312853060631576, 'n_estimators': 1105, 'subsample': 0.5778266541188597, 'colsample_bytree': 0.565148604430867, 'min_child_weight': 6, 'gamma': 2.4912061953501725, 'reg_alpha': 3.2438427351615007e-06, 'reg_lambda': 1.87932256094076e-07, 'max_delta_step': 8}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  91%|█████████ | 182/200 [03:11<00:22,  1.24s/it]

[I 2025-11-10 14:23:45,780] Trial 184 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.11068674503576403, 'n_estimators': 435, 'subsample': 0.7876832028901563, 'colsample_bytree': 0.5467262683498115, 'min_child_weight': 10, 'gamma': 1.8200420938439505, 'reg_alpha': 0.01547820860515734, 'reg_lambda': 1.167653149575317e-06, 'max_delta_step': 7}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  92%|█████████▏| 183/200 [03:12<00:20,  1.19s/it]

[I 2025-11-10 14:23:46,867] Trial 182 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.013530915793644578, 'n_estimators': 932, 'subsample': 0.6248777900309189, 'colsample_bytree': 0.9608744320867388, 'min_child_weight': 4, 'gamma': 2.4948843043020092, 'reg_alpha': 0.005122847138610941, 'reg_lambda': 4.487748414396523, 'max_delta_step': 7}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  92%|█████████▏| 184/200 [03:12<00:14,  1.08it/s]

[I 2025-11-10 14:23:47,152] Trial 180 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.013422613107070571, 'n_estimators': 1105, 'subsample': 0.8185616838980388, 'colsample_bytree': 0.9664751335368097, 'min_child_weight': 9, 'gamma': 1.1857341088804039, 'reg_alpha': 0.005385885293025721, 'reg_lambda': 9.202880998959495e-08, 'max_delta_step': 7}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  92%|█████████▎| 185/200 [03:14<00:19,  1.30s/it]

[I 2025-11-10 14:23:49,331] Trial 183 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01458384266800105, 'n_estimators': 1307, 'subsample': 0.5743824624074401, 'colsample_bytree': 0.6655800588760106, 'min_child_weight': 9, 'gamma': 1.310422387591588, 'reg_alpha': 0.005759196409617925, 'reg_lambda': 2.1316839768862046e-06, 'max_delta_step': 7}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  93%|█████████▎| 186/200 [03:15<00:17,  1.25s/it]

[I 2025-11-10 14:23:50,473] Trial 185 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.017765534711551623, 'n_estimators': 1027, 'subsample': 0.5910237439906975, 'colsample_bytree': 0.5538130273882919, 'min_child_weight': 10, 'gamma': 2.143943873179118, 'reg_alpha': 0.20165283161659225, 'reg_lambda': 3.7836827226546503e-08, 'max_delta_step': 7}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  94%|█████████▎| 187/200 [03:16<00:13,  1.05s/it]

[I 2025-11-10 14:23:51,050] Trial 188 pruned.

Best trial: 97. Best value: 0.547135:  94%|█████████▍| 188/200 [03:17<00:12,  1.03s/it]

[I 2025-11-10 14:23:52,016] Trial 187 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.015028312688810918, 'n_estimators': 1039, 'subsample': 0.8068502552102226, 'colsample_bytree': 0.5873434576264497, 'min_child_weight': 10, 'gamma': 4.216913119370285, 'reg_alpha': 2.39091585502722e-05, 'reg_lambda': 0.13955156885613224, 'max_delta_step': 6}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  94%|█████████▍| 189/200 [03:18<00:10,  1.02it/s]

[I 2025-11-10 14:23:52,917] Trial 186 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.017665848687629618, 'n_estimators': 1216, 'subsample': 0.8160462896279431, 'colsample_bytree': 0.8123246637106869, 'min_child_weight': 10, 'gamma': 1.892046586746238, 'reg_alpha': 2.642660757432415e-05, 'reg_lambda': 8.928074530297153e-08, 'max_delta_step': 7}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  95%|█████████▌| 190/200 [03:18<00:07,  1.28it/s]

[I 2025-11-10 14:23:53,214] Trial 191 pruned.

Best trial: 97. Best value: 0.547135:  96%|█████████▌| 191/200 [03:19<00:07,  1.20it/s]

[I 2025-11-10 14:23:54,163] Trial 192 pruned.

Best trial: 97. Best value: 0.547135:  96%|█████████▌| 192/200 [03:20<00:06,  1.31it/s]

[I 2025-11-10 14:23:54,764] Trial 193 pruned.

Best trial: 97. Best value: 0.547135:  96%|█████████▋| 193/200 [03:21<00:06,  1.03it/s]

[I 2025-11-10 14:23:56,234] Trial 189 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.043785661980904514, 'n_estimators': 1203, 'subsample': 0.7985791529385111, 'colsample_bytree': 0.520187515963431, 'min_child_weight': 10, 'gamma': 1.9537724871123827, 'reg_alpha': 0.42291722358250844, 'reg_lambda': 0.12029152109352427, 'max_delta_step': 6}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  97%|█████████▋| 194/200 [03:22<00:05,  1.18it/s]

[I 2025-11-10 14:23:56,775] Trial 190 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04099512796104437, 'n_estimators': 1205, 'subsample': 0.8003539223773244, 'colsample_bytree': 0.5171902200980176, 'min_child_weight': 10, 'gamma': 1.9741451661383203, 'reg_alpha': 2.959224375878631e-05, 'reg_lambda': 0.14139883522024432, 'max_delta_step': 6}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  98%|█████████▊| 195/200 [03:24<00:06,  1.28s/it]

[I 2025-11-10 14:23:59,085] Trial 194 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.010154434825887404, 'n_estimators': 954, 'subsample': 0.8087013134177545, 'colsample_bytree': 0.5409641526482234, 'min_child_weight': 10, 'gamma': 2.711499274548369, 'reg_alpha': 0.11761266124838214, 'reg_lambda': 2.658534743355004e-07, 'max_delta_step': 8}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  98%|█████████▊| 196/200 [03:24<00:04,  1.05s/it]

[I 2025-11-10 14:23:59,585] Trial 195 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.010950210050656719, 'n_estimators': 1015, 'subsample': 0.8277403521573121, 'colsample_bytree': 0.5204342078358336, 'min_child_weight': 10, 'gamma': 2.6914614748817516, 'reg_alpha': 0.07874996628848649, 'reg_lambda': 2.1137390149482766e-07, 'max_delta_step': 8}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135:  98%|█████████▊| 197/200 [03:25<00:03,  1.06s/it]

[I 2025-11-10 14:24:00,676] Trial 199 pruned.

Best trial: 97. Best value: 0.547135:  99%|█████████▉| 198/200 [03:26<00:01,  1.09it/s]

[I 2025-11-10 14:24:01,272] Trial 197 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.010320613587031168, 'n_estimators': 1018, 'subsample': 0.5632116734456887, 'colsample_bytree': 0.5372848521470054, 'min_child_weight': 10, 'gamma': 3.742571852847659, 'reg_alpha': 0.13313344887878203, 'reg_lambda': 0.0007428650068898905, 'max_delta_step': 8}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135: 100%|█████████▉| 199/200 [03:26<00:00,  1.42it/s]

[I 2025-11-10 14:24:01,474] Trial 196 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01012096787007241, 'n_estimators': 975, 'subsample': 0.8075295177352998, 'colsample_bytree': 0.9166205936178599, 'min_child_weight': 10, 'gamma': 3.4674667459301425, 'reg_alpha': 0.014576946580633923, 'reg_lambda': 6.572178022239939e-07, 'max_delta_step': 8}. Best is trial 97 with value: 0.5471345029239766.

Best trial: 97. Best value: 0.547135: 100%|██████████| 200/200 [03:28<00:00,  1.04s/it]

[I 2025-11-10 14:24:02,783] Trial 198 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.011350604003639873, 'n_estimators': 1078, 'subsample': 0.5848823763191108, 'colsample_bytree': 0.9168657217887943, 'min_child_weight': 7, 'gamma': 3.5135952585698744, 'reg_alpha': 0.009600921685570378, 'reg_lambda': 4.4266859835158985e-07, 'max_delta_step': 8}. Best is trial 97 with value: 0.5471345029239766.

[I 2025-11-10 14:24:04,241] A new study created in memory with name: 9_1_balanced_accuracy
Best trial: 0. Best value: 0.5:   1%|          | 2/200 [00:06<08:21,  2.53s/it]

[I 2025-11-10 14:24:10,224] Trial 1 finished with value: 0.46343773873185634 and parameters: {'max_depth': 8, 'learning_rate': 0.11285975889361673, 'n_estimators': 473, 'subsample': 0.9962240829256914, 'colsample_bytree': 0.8700790886402088, 'min_child_weight': 5, 'gamma': 1.613605127931868, 'reg_alpha': 0.00013830921899808896, 'reg_lambda': 9.604650478663547e-07, 'max_delta_step': 0}. Best is trial 1 with value: 0.46343773873185634.
[I 2025-11-10 14:24:10,339] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.01747680712347379, 'n_estimators': 723, 'subsample': 0.5178469483661139, 'colsample_bytree': 0.8909463606434691, 'min_child_weight': 5, 'gamma': 2.414841108645903, 'reg_alpha': 6.3943770958261625, 'reg_lambda': 0.1820963239005321, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 3. Best value: 0.530008:   2%|▏         | 3/200 [00:09<08:57,  2.73s/it]

[I 2025-11-10 14:24:13,305] Trial 3 finished with value: 0.5300076394194042 and parameters: {'max_depth': 6, 'learning_rate': 0.016058455796529824, 'n_estimators': 601, 'subsample': 0.7795736036432194, 'colsample_bytree': 0.821967674003447, 'min_child_weight': 6, 'gamma': 0.7845800135519754, 'reg_alpha': 0.0009658618115808943, 'reg_lambda': 1.3481768960148566e-08, 'max_delta_step': 7}. Best is trial 3 with value: 0.5300076394194042.
[I 2025-11-10 14:24:13,360] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.035175988373746796, 'n_estimators': 1369, 'subsample': 0.6895923576448422, 'colsample_bytree': 0.5384430458129079, 'min_child_weight': 8, 'gamma': 3.783909902303375, 'reg_alpha': 2.7109188799152464, 'reg_lambda': 1.3540297300671538e-08, 'max_delta_step': 9}. Best is trial 3 with value: 0.5300076394194042.

Best trial: 3. Best value: 0.530008:   2%|▎         | 5/200 [00:12<06:43,  2.07s/it]

[I 2025-11-10 14:24:16,437] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01619893285833913, 'n_estimators': 444, 'subsample': 0.5751026066281635, 'colsample_bytree': 0.8253070939531841, 'min_child_weight': 7, 'gamma': 3.8358557763573344, 'reg_alpha': 1.9161694469910386e-05, 'reg_lambda': 1.3273233334702694e-08, 'max_delta_step': 1}. Best is trial 3 with value: 0.5300076394194042.

Best trial: 3. Best value: 0.530008:   3%|▎         | 6/200 [00:12<05:21,  1.66s/it]

[I 2025-11-10 14:24:17,064] Trial 5 finished with value: 0.4762948815889992 and parameters: {'max_depth': 6, 'learning_rate': 0.12824388090869307, 'n_estimators': 673, 'subsample': 0.7191757953510424, 'colsample_bytree': 0.7152451665354594, 'min_child_weight': 3, 'gamma': 1.270627124932191, 'reg_alpha': 4.302590558103385, 'reg_lambda': 5.320654415349023, 'max_delta_step': 9}. Best is trial 3 with value: 0.5300076394194042.

Best trial: 4. Best value: 0.531742:   4%|▎         | 7/200 [00:13<04:07,  1.28s/it]

[I 2025-11-10 14:24:17,444] Trial 4 finished with value: 0.5317417876241406 and parameters: {'max_depth': 9, 'learning_rate': 0.158103092081174, 'n_estimators': 862, 'subsample': 0.8870181728279496, 'colsample_bytree': 0.5158527111282294, 'min_child_weight': 5, 'gamma': 1.9403412468060672, 'reg_alpha': 0.0001991155302554033, 'reg_lambda': 3.007873942459278e-05, 'max_delta_step': 6}. Best is trial 4 with value: 0.5317417876241406.

Best trial: 4. Best value: 0.531742:   4%|▍         | 8/200 [00:14<04:34,  1.43s/it]

[I 2025-11-10 14:24:19,227] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01655137367762115, 'n_estimators': 844, 'subsample': 0.5237519458062386, 'colsample_bytree': 0.9284701893264765, 'min_child_weight': 7, 'gamma': 3.8227799374515232, 'reg_alpha': 4.8065963412254055e-05, 'reg_lambda': 0.20497553202451843, 'max_delta_step': 1}. Best is trial 4 with value: 0.5317417876241406.

Best trial: 4. Best value: 0.531742:   4%|▍         | 9/200 [00:21<09:27,  2.97s/it]

[I 2025-11-10 14:24:25,861] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.013959378662097434, 'n_estimators': 1276, 'subsample': 0.5464494442847316, 'colsample_bytree': 0.929578847867572, 'min_child_weight': 8, 'gamma': 3.01457173709395, 'reg_alpha': 8.304199554988084e-07, 'reg_lambda': 0.000885356181752463, 'max_delta_step': 8}. Best is trial 4 with value: 0.5317417876241406.

Best trial: 4. Best value: 0.531742:   6%|▌         | 11/200 [00:23<06:04,  1.93s/it]

[I 2025-11-10 14:24:27,836] Trial 8 finished with value: 0.4879755538579068 and parameters: {'max_depth': 9, 'learning_rate': 0.019337638793663244, 'n_estimators': 1452, 'subsample': 0.5444828380244631, 'colsample_bytree': 0.8490650411067928, 'min_child_weight': 5, 'gamma': 4.769867838254985, 'reg_alpha': 1.3663420669201434e-06, 'reg_lambda': 3.297838315604173e-08, 'max_delta_step': 6}. Best is trial 4 with value: 0.5317417876241406.
[I 2025-11-10 14:24:28,001] Trial 11 finished with value: 0.41883116883116883 and parameters: {'max_depth': 4, 'learning_rate': 0.08189512645804443, 'n_estimators': 833, 'subsample': 0.9780623903557293, 'colsample_bytree': 0.9127754045468892, 'min_child_weight': 5, 'gamma': 3.2631196565753546, 'reg_alpha': 8.826666857690869e-08, 'reg_lambda': 2.779553101785306, 'max_delta_step': 7}. Best is trial 4 with value: 0.5317417876241406.

Best trial: 4. Best value: 0.531742:   6%|▌         | 12/200 [00:25<05:43,  1.83s/it]

[I 2025-11-10 14:24:29,603] Trial 13 pruned.

Best trial: 4. Best value: 0.531742:   6%|▋         | 13/200 [00:26<05:06,  1.64s/it]

[I 2025-11-10 14:24:30,802] Trial 15 pruned.

Best trial: 4. Best value: 0.531742:   7%|▋         | 14/200 [00:29<06:43,  2.17s/it]

[I 2025-11-10 14:24:34,216] Trial 10 finished with value: 0.5122459893048128 and parameters: {'max_depth': 6, 'learning_rate': 0.013920454304526752, 'n_estimators': 646, 'subsample': 0.5750668649020632, 'colsample_bytree': 0.9269316747478962, 'min_child_weight': 1, 'gamma': 2.2801619180334614, 'reg_alpha': 2.4971886318405383e-05, 'reg_lambda': 0.012684382082197724, 'max_delta_step': 2}. Best is trial 4 with value: 0.5317417876241406.

Best trial: 4. Best value: 0.531742:   8%|▊         | 15/200 [00:31<06:25,  2.08s/it]

[I 2025-11-10 14:24:36,095] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.2449951249110387, 'n_estimators': 1119, 'subsample': 0.8536687349991918, 'colsample_bytree': 0.6563908859975892, 'min_child_weight': 10, 'gamma': 0.3122644629949858, 'reg_alpha': 0.01381371042572162, 'reg_lambda': 1.1602579204563633e-05, 'max_delta_step': 4}. Best is trial 4 with value: 0.5317417876241406.

Best trial: 4. Best value: 0.531742:   8%|▊         | 16/200 [00:32<04:45,  1.55s/it]

[I 2025-11-10 14:24:36,409] Trial 17 pruned.

Best trial: 4. Best value: 0.531742:   8%|▊         | 17/200 [00:35<06:03,  1.99s/it]

[I 2025-11-10 14:24:39,416] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.2719533824650915, 'n_estimators': 1132, 'subsample': 0.8137186930871154, 'colsample_bytree': 0.6285661024303475, 'min_child_weight': 10, 'gamma': 1.532357870951734, 'reg_alpha': 0.013703483153516927, 'reg_lambda': 0.0016269209865570674, 'max_delta_step': 10}. Best is trial 4 with value: 0.5317417876241406.

Best trial: 4. Best value: 0.531742:   9%|▉         | 18/200 [00:36<05:21,  1.77s/it]

[I 2025-11-10 14:24:40,665] Trial 19 finished with value: 0.5014362108479755 and parameters: {'max_depth': 5, 'learning_rate': 0.0599396132883778, 'n_estimators': 475, 'subsample': 0.6548066175291156, 'colsample_bytree': 0.7724001644184015, 'min_child_weight': 7, 'gamma': 1.8148754866753558, 'reg_alpha': 0.0016780828653468007, 'reg_lambda': 4.213591406867037e-07, 'max_delta_step': 7}. Best is trial 4 with value: 0.5317417876241406.

Best trial: 4. Best value: 0.531742:  10%|▉         | 19/200 [00:37<04:15,  1.41s/it]

[I 2025-11-10 14:24:41,244] Trial 12 finished with value: 0.5086325439266617 and parameters: {'max_depth': 9, 'learning_rate': 0.010437544295883895, 'n_estimators': 991, 'subsample': 0.938822593113515, 'colsample_bytree': 0.7336441723807923, 'min_child_weight': 2, 'gamma': 3.495940847466347, 'reg_alpha': 0.0015876466685201104, 'reg_lambda': 0.22624644634623803, 'max_delta_step': 9}. Best is trial 4 with value: 0.5317417876241406.

Best trial: 4. Best value: 0.531742:  10%|█         | 20/200 [00:39<05:31,  1.84s/it]

[I 2025-11-10 14:24:44,096] Trial 20 finished with value: 0.5114362108479755 and parameters: {'max_depth': 5, 'learning_rate': 0.028814254891871238, 'n_estimators': 464, 'subsample': 0.6471387459965131, 'colsample_bytree': 0.999357496919545, 'min_child_weight': 7, 'gamma': 0.9095744075855641, 'reg_alpha': 0.0005846355005830609, 'reg_lambda': 4.842065694850894e-07, 'max_delta_step': 7}. Best is trial 4 with value: 0.5317417876241406.

Best trial: 4. Best value: 0.531742:  10%|█         | 21/200 [00:40<04:50,  1.62s/it]

[I 2025-11-10 14:24:45,205] Trial 22 finished with value: 0.502864782276547 and parameters: {'max_depth': 9, 'learning_rate': 0.15778892841607764, 'n_estimators': 292, 'subsample': 0.8855933063460142, 'colsample_bytree': 0.7935307297941542, 'min_child_weight': 6, 'gamma': 0.7578637935469198, 'reg_alpha': 1.4769963796602644e-06, 'reg_lambda': 0.00012801011029647694, 'max_delta_step': 6}. Best is trial 4 with value: 0.5317417876241406.

Best trial: 4. Best value: 0.531742:  11%|█         | 22/200 [00:45<07:27,  2.51s/it]

[I 2025-11-10 14:24:49,791] Trial 18 finished with value: 0.49424751718869364 and parameters: {'max_depth': 7, 'learning_rate': 0.0588308431614737, 'n_estimators': 997, 'subsample': 0.8134261567444835, 'colsample_bytree': 0.7879299111053899, 'min_child_weight': 3, 'gamma': 1.170809853439603, 'reg_alpha': 0.0037952934907095537, 'reg_lambda': 3.087510085588243e-07, 'max_delta_step': 7}. Best is trial 4 with value: 0.5317417876241406.

Best trial: 4. Best value: 0.531742:  12%|█▏        | 23/200 [00:48<08:11,  2.77s/it]

[I 2025-11-10 14:24:53,154] Trial 21 finished with value: 0.5112223071046601 and parameters: {'max_depth': 9, 'learning_rate': 0.16627642495092043, 'n_estimators': 933, 'subsample': 0.9008240458444328, 'colsample_bytree': 0.9817016494370978, 'min_child_weight': 4, 'gamma': 0.9923521201414801, 'reg_alpha': 0.12786911070785706, 'reg_lambda': 1.7728080308546826e-07, 'max_delta_step': 6}. Best is trial 4 with value: 0.5317417876241406.

Best trial: 4. Best value: 0.531742:  12%|█▏        | 24/200 [00:50<07:01,  2.39s/it]

[I 2025-11-10 14:24:54,682] Trial 23 finished with value: 0.5302139037433155 and parameters: {'max_depth': 3, 'learning_rate': 0.1530503309908474, 'n_estimators': 916, 'subsample': 0.8939025901841227, 'colsample_bytree': 0.7916697176613877, 'min_child_weight': 4, 'gamma': 0.8305566833411904, 'reg_alpha': 0.26936203652035035, 'reg_lambda': 0.00013837359495895302, 'max_delta_step': 5}. Best is trial 4 with value: 0.5317417876241406.

Best trial: 24. Best value: 0.543071:  12%|█▎        | 25/200 [00:52<06:33,  2.25s/it]

[I 2025-11-10 14:24:56,587] Trial 24 finished with value: 0.5430710466004584 and parameters: {'max_depth': 6, 'learning_rate': 0.024112563338192526, 'n_estimators': 684, 'subsample': 0.7568042700176691, 'colsample_bytree': 0.575346997628426, 'min_child_weight': 1, 'gamma': 2.2673369073776213, 'reg_alpha': 1.7785567116546995e-05, 'reg_lambda': 0.009321055145446953, 'max_delta_step': 3}. Best is trial 24 with value: 0.5430710466004584.

Best trial: 24. Best value: 0.543071:  13%|█▎        | 26/200 [00:54<06:31,  2.25s/it]

[I 2025-11-10 14:24:58,853] Trial 28 pruned.

Best trial: 24. Best value: 0.543071:  14%|█▎        | 27/200 [01:01<10:19,  3.58s/it]

[I 2025-11-10 14:25:05,525] Trial 27 finished with value: 0.5380595874713522 and parameters: {'max_depth': 3, 'learning_rate': 0.08347862282288214, 'n_estimators': 778, 'subsample': 0.7637405344325175, 'colsample_bytree': 0.7052853693970551, 'min_child_weight': 4, 'gamma': 2.0474653997150414, 'reg_alpha': 0.09740852742873948, 'reg_lambda': 6.470678524512723e-06, 'max_delta_step': 4}. Best is trial 24 with value: 0.5430710466004584.

Best trial: 25. Best value: 0.564416:  14%|█▍        | 28/200 [01:03<09:20,  3.26s/it]

[I 2025-11-10 14:25:08,053] Trial 25 finished with value: 0.5644155844155845 and parameters: {'max_depth': 6, 'learning_rate': 0.02448678594959317, 'n_estimators': 643, 'subsample': 0.7567858945382553, 'colsample_bytree': 0.9850446601835319, 'min_child_weight': 1, 'gamma': 2.2879784285463494, 'reg_alpha': 0.18924614316412344, 'reg_lambda': 0.0105224777711991, 'max_delta_step': 3}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  14%|█▍        | 29/200 [01:04<07:08,  2.50s/it]

[I 2025-11-10 14:25:08,791] Trial 26 finished with value: 0.5561955691367456 and parameters: {'max_depth': 6, 'learning_rate': 0.02461409962229754, 'n_estimators': 650, 'subsample': 0.7534051307651936, 'colsample_bytree': 0.834365340469438, 'min_child_weight': 1, 'gamma': 2.3357863880099785, 'reg_alpha': 9.106403271093907e-06, 'reg_lambda': 0.009161097125198962, 'max_delta_step': 3}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  15%|█▌        | 30/200 [01:08<08:04,  2.85s/it]

[I 2025-11-10 14:25:12,454] Trial 29 finished with value: 0.48703590527119944 and parameters: {'max_depth': 4, 'learning_rate': 0.024925565820489944, 'n_estimators': 903, 'subsample': 0.947517654013494, 'colsample_bytree': 0.5773112882540349, 'min_child_weight': 4, 'gamma': 1.891139791915556, 'reg_alpha': 8.028492062520745e-06, 'reg_lambda': 7.758340741565891e-06, 'max_delta_step': 3}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  16%|█▌        | 31/200 [01:08<05:56,  2.11s/it]

[I 2025-11-10 14:25:12,835] Trial 30 finished with value: 0.5209167303284951 and parameters: {'max_depth': 4, 'learning_rate': 0.07884056999232802, 'n_estimators': 578, 'subsample': 0.7676332782930929, 'colsample_bytree': 0.5785303354625686, 'min_child_weight': 4, 'gamma': 1.953658350638706, 'reg_alpha': 6.109816813849109e-06, 'reg_lambda': 5.384564181518575e-06, 'max_delta_step': 3}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  16%|█▌        | 32/200 [01:13<08:10,  2.92s/it]

[I 2025-11-10 14:25:17,644] Trial 31 finished with value: 0.5110389610389611 and parameters: {'max_depth': 4, 'learning_rate': 0.026776198952415294, 'n_estimators': 570, 'subsample': 0.7623986131233514, 'colsample_bytree': 0.5648472131776088, 'min_child_weight': 1, 'gamma': 2.0851922918218895, 'reg_alpha': 0.09346920796176841, 'reg_lambda': 0.0386379058557922, 'max_delta_step': 3}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  16%|█▋        | 33/200 [01:15<07:24,  2.66s/it]

[I 2025-11-10 14:25:19,710] Trial 35 pruned.

Best trial: 25. Best value: 0.564416:  17%|█▋        | 34/200 [01:16<06:01,  2.18s/it]

[I 2025-11-10 14:25:20,758] Trial 32 finished with value: 0.5472727272727272 and parameters: {'max_depth': 4, 'learning_rate': 0.023336822263641973, 'n_estimators': 585, 'subsample': 0.687682258900904, 'colsample_bytree': 0.8875824706139667, 'min_child_weight': 1, 'gamma': 2.5833967161548244, 'reg_alpha': 5.156931352954465e-06, 'reg_lambda': 0.046119773779542676, 'max_delta_step': 3}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  18%|█▊        | 35/200 [01:17<04:48,  1.75s/it]

[I 2025-11-10 14:25:21,498] Trial 36 pruned.

Best trial: 25. Best value: 0.564416:  18%|█▊        | 36/200 [01:18<04:20,  1.59s/it]

[I 2025-11-10 14:25:22,723] Trial 38 pruned.

Best trial: 25. Best value: 0.564416:  18%|█▊        | 37/200 [01:19<03:30,  1.29s/it]

[I 2025-11-10 14:25:23,320] Trial 34 finished with value: 0.5058594346829641 and parameters: {'max_depth': 5, 'learning_rate': 0.04653565692205874, 'n_estimators': 734, 'subsample': 0.7015467173873375, 'colsample_bytree': 0.7054500458969171, 'min_child_weight': 1, 'gamma': 2.4703657655021605, 'reg_alpha': 1.1418044532159766, 'reg_lambda': 0.027031813086929268, 'max_delta_step': 2}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  19%|█▉        | 38/200 [01:20<03:36,  1.34s/it]

[I 2025-11-10 14:25:24,757] Trial 33 finished with value: 0.5210389610389611 and parameters: {'max_depth': 5, 'learning_rate': 0.021968921775652052, 'n_estimators': 568, 'subsample': 0.6967281055391236, 'colsample_bytree': 0.9723468340654636, 'min_child_weight': 1, 'gamma': 2.5425314613743657, 'reg_alpha': 3.210865801391694e-07, 'reg_lambda': 0.024875183411198414, 'max_delta_step': 2}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  20%|█▉        | 39/200 [01:21<02:54,  1.09s/it]

[I 2025-11-10 14:25:25,264] Trial 40 pruned.

Best trial: 25. Best value: 0.564416:  20%|██        | 40/200 [01:23<03:38,  1.36s/it]

[I 2025-11-10 14:25:27,269] Trial 41 pruned.

Best trial: 25. Best value: 0.564416:  20%|██        | 41/200 [01:24<03:54,  1.48s/it]

[I 2025-11-10 14:25:29,009] Trial 43 pruned.

Best trial: 25. Best value: 0.564416:  21%|██        | 42/200 [01:27<04:44,  1.80s/it]

[I 2025-11-10 14:25:31,562] Trial 44 pruned.

Best trial: 25. Best value: 0.564416:  22%|██▏       | 43/200 [01:28<04:29,  1.72s/it]

[I 2025-11-10 14:25:33,081] Trial 37 finished with value: 0.5339801375095493 and parameters: {'max_depth': 6, 'learning_rate': 0.020972417105540476, 'n_estimators': 539, 'subsample': 0.6898466605925666, 'colsample_bytree': 0.9560810530813615, 'min_child_weight': 1, 'gamma': 2.544401154811283, 'reg_alpha': 1.853191116248406e-07, 'reg_lambda': 0.04734908507888846, 'max_delta_step': 2}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  22%|██▏       | 44/200 [01:29<03:49,  1.47s/it]

[I 2025-11-10 14:25:33,991] Trial 39 finished with value: 0.5180137509549274 and parameters: {'max_depth': 5, 'learning_rate': 0.02067358823165164, 'n_estimators': 525, 'subsample': 0.6720976073181324, 'colsample_bytree': 0.8493259468641843, 'min_child_weight': 1, 'gamma': 2.627561553135345, 'reg_alpha': 2.3263954746637795e-07, 'reg_lambda': 0.058951072845369754, 'max_delta_step': 0}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  22%|██▎       | 45/200 [01:31<03:50,  1.49s/it]

[I 2025-11-10 14:25:35,507] Trial 46 pruned.

Best trial: 25. Best value: 0.564416:  23%|██▎       | 46/200 [01:31<02:58,  1.16s/it]

[I 2025-11-10 14:25:35,908] Trial 42 finished with value: 0.5119938884644767 and parameters: {'max_depth': 6, 'learning_rate': 0.033801989735064285, 'n_estimators': 642, 'subsample': 0.7397254195936034, 'colsample_bytree': 0.8681093778850081, 'min_child_weight': 2, 'gamma': 2.2785857893806742, 'reg_alpha': 6.140086872271228e-06, 'reg_lambda': 0.12369141754930825, 'max_delta_step': 5}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  24%|██▎       | 47/200 [01:32<02:35,  1.02s/it]

[I 2025-11-10 14:25:36,586] Trial 47 pruned.

Best trial: 25. Best value: 0.564416:  24%|██▍       | 48/200 [01:41<08:36,  3.40s/it]

[I 2025-11-10 14:25:45,548] Trial 49 finished with value: 0.5245989304812835 and parameters: {'max_depth': 3, 'learning_rate': 0.10207937058132995, 'n_estimators': 754, 'subsample': 0.8380007317751047, 'colsample_bytree': 0.7441663534754365, 'min_child_weight': 3, 'gamma': 3.3205471040713777, 'reg_alpha': 0.0001418180187269324, 'reg_lambda': 0.0003069777784883053, 'max_delta_step': 4}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  24%|██▍       | 49/200 [01:41<06:15,  2.49s/it]

[I 2025-11-10 14:25:45,915] Trial 45 finished with value: 0.5051718869365928 and parameters: {'max_depth': 3, 'learning_rate': 0.012863252708710492, 'n_estimators': 666, 'subsample': 0.7550407053444084, 'colsample_bytree': 0.9543359094093822, 'min_child_weight': 3, 'gamma': 2.153941757231763, 'reg_alpha': 3.5289213323384314e-05, 'reg_lambda': 0.09068866260447175, 'max_delta_step': 3}. Best is trial 25 with value: 0.5644155844155845.
[I 2025-11-10 14:25:45,934] Trial 50 finished with value: 0.5394881588999236 and parameters: {'max_depth': 3, 'learning_rate': 0.01718510270478595, 'n_estimators': 799, 'subsample': 0.8248513249431987, 'colsample_bytree': 0.8119371931303236, 'min_child_weight': 6, 'gamma': 3.3144599369297643, 'reg_alpha': 0.00011334803869595635, 'reg_lambda': 0.0004602723959608915, 'max_delta_step': 4}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  26%|██▌       | 51/200 [01:42<03:32,  1.43s/it]

[I 2025-11-10 14:25:46,288] Trial 48 finished with value: 0.5358594346829642 and parameters: {'max_depth': 3, 'learning_rate': 0.017435276859327373, 'n_estimators': 636, 'subsample': 0.8302198621643442, 'colsample_bytree': 0.7577715898899899, 'min_child_weight': 2, 'gamma': 3.5094868979695515, 'reg_alpha': 0.0664261377421745, 'reg_lambda': 2.6017910606813626e-06, 'max_delta_step': 4}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  26%|██▋       | 53/200 [01:43<02:28,  1.01s/it]

[I 2025-11-10 14:25:47,264] Trial 53 pruned.
[I 2025-11-10 14:25:47,405] Trial 51 pruned.

Best trial: 25. Best value: 0.564416:  27%|██▋       | 54/200 [01:44<02:55,  1.20s/it]

[I 2025-11-10 14:25:49,118] Trial 56 pruned.

Best trial: 25. Best value: 0.564416:  28%|██▊       | 55/200 [01:45<02:34,  1.07s/it]

[I 2025-11-10 14:25:49,848] Trial 55 pruned.

Best trial: 25. Best value: 0.564416:  28%|██▊       | 56/200 [01:46<02:42,  1.13s/it]

[I 2025-11-10 14:25:51,134] Trial 57 pruned.

Best trial: 25. Best value: 0.564416:  28%|██▊       | 57/200 [01:52<05:30,  2.31s/it]

[I 2025-11-10 14:25:56,346] Trial 58 finished with value: 0.5267150496562261 and parameters: {'max_depth': 7, 'learning_rate': 0.029495654391832847, 'n_estimators': 417, 'subsample': 0.8718003622110623, 'colsample_bytree': 0.6578313220324236, 'min_child_weight': 5, 'gamma': 1.5426479889659346, 'reg_alpha': 9.886181937416976e-07, 'reg_lambda': 0.0003545824508285093, 'max_delta_step': 5}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  29%|██▉       | 58/200 [01:53<05:02,  2.13s/it]

[I 2025-11-10 14:25:58,041] Trial 59 finished with value: 0.5622612681436211 and parameters: {'max_depth': 3, 'learning_rate': 0.04104565575159258, 'n_estimators': 499, 'subsample': 0.8122740079543274, 'colsample_bytree': 0.6159669024271184, 'min_child_weight': 1, 'gamma': 4.0443194585889, 'reg_alpha': 7.869466161696017e-07, 'reg_lambda': 4.015840936136842e-05, 'max_delta_step': 5}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  30%|██▉       | 59/200 [01:54<04:03,  1.73s/it]

[I 2025-11-10 14:25:58,802] Trial 54 finished with value: 0.5412681436210848 and parameters: {'max_depth': 4, 'learning_rate': 0.015589820264196872, 'n_estimators': 863, 'subsample': 0.7790195970585354, 'colsample_bytree': 0.8026442795601137, 'min_child_weight': 6, 'gamma': 1.781067180798268, 'reg_alpha': 8.045024798477614e-05, 'reg_lambda': 0.3891314747406304, 'max_delta_step': 4}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  30%|███       | 61/200 [02:00<04:40,  2.02s/it]

[I 2025-11-10 14:26:04,209] Trial 52 finished with value: 0.5492207792207793 and parameters: {'max_depth': 8, 'learning_rate': 0.017053014063009235, 'n_estimators': 861, 'subsample': 0.7791103061553086, 'colsample_bytree': 0.6522319911176583, 'min_child_weight': 1, 'gamma': 1.7229012051300103, 'reg_alpha': 4.2100313892713954e-08, 'reg_lambda': 0.4233933873897903, 'max_delta_step': 1}. Best is trial 25 with value: 0.5644155844155845.
[I 2025-11-10 14:26:04,347] Trial 62 finished with value: 0.5472192513368984 and parameters: {'max_depth': 5, 'learning_rate': 0.0412078947278252, 'n_estimators': 500, 'subsample': 0.8659843319972614, 'colsample_bytree': 0.6098156607929797, 'min_child_weight': 1, 'gamma': 4.935497327009276, 'reg_alpha': 3.09232690035302e-08, 'reg_lambda': 2.3553158875214835, 'max_delta_step': 5}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  31%|███       | 62/200 [02:00<03:20,  1.45s/it]

[I 2025-11-10 14:26:04,466] Trial 61 finished with value: 0.5464629488158901 and parameters: {'max_depth': 10, 'learning_rate': 0.037857747104935946, 'n_estimators': 500, 'subsample': 0.819728356818335, 'colsample_bytree': 0.6232170024701679, 'min_child_weight': 1, 'gamma': 4.215623145450631, 'reg_alpha': 1.548361134818778e-08, 'reg_lambda': 3.4845854420730215e-05, 'max_delta_step': 5}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  32%|███▏      | 64/200 [02:01<02:05,  1.08it/s]

[I 2025-11-10 14:26:05,260] Trial 65 pruned.
[I 2025-11-10 14:26:05,405] Trial 64 pruned.

Best trial: 25. Best value: 0.564416:  32%|███▎      | 65/200 [02:01<01:49,  1.24it/s]

[I 2025-11-10 14:26:05,941] Trial 60 finished with value: 0.5335217723453017 and parameters: {'max_depth': 3, 'learning_rate': 0.023757554188015416, 'n_estimators': 766, 'subsample': 0.8019620915737458, 'colsample_bytree': 0.620400085066241, 'min_child_weight': 1, 'gamma': 4.352635273031882, 'reg_alpha': 0.045689701201982985, 'reg_lambda': 3.093502256315209e-05, 'max_delta_step': 3}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  33%|███▎      | 66/200 [02:02<01:39,  1.35it/s]

[I 2025-11-10 14:26:06,518] Trial 68 pruned.

Best trial: 25. Best value: 0.564416:  34%|███▎      | 67/200 [02:02<01:34,  1.41it/s]

[I 2025-11-10 14:26:07,161] Trial 69 pruned.

Best trial: 25. Best value: 0.564416:  34%|███▍      | 68/200 [02:05<03:01,  1.38s/it]

[I 2025-11-10 14:26:10,094] Trial 63 finished with value: 0.5285485103132161 and parameters: {'max_depth': 10, 'learning_rate': 0.041120853910542696, 'n_estimators': 507, 'subsample': 0.8069676878813971, 'colsample_bytree': 0.6098890476338735, 'min_child_weight': 1, 'gamma': 4.404025348815312, 'reg_alpha': 2.2762918233049353e-08, 'reg_lambda': 2.653969075469504, 'max_delta_step': 2}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  35%|███▌      | 70/200 [02:06<01:59,  1.09it/s]

[I 2025-11-10 14:26:11,055] Trial 67 finished with value: 0.5175553857906798 and parameters: {'max_depth': 8, 'learning_rate': 0.05273330082153929, 'n_estimators': 438, 'subsample': 0.8590490642571869, 'colsample_bytree': 0.6292305355953525, 'min_child_weight': 1, 'gamma': 4.242717106379313, 'reg_alpha': 5.003126385617473e-08, 'reg_lambda': 3.4340458896299154e-05, 'max_delta_step': 8}. Best is trial 25 with value: 0.5644155844155845.
[I 2025-11-10 14:26:11,190] Trial 71 pruned.
[I 2025-11-10 14:26:11,196] Trial 66 finished with value: 0.49399541634835753 and parameters: {'max_depth': 10, 'learning_rate': 0.04899648599084514, 'n_estimators': 460, 'subsample': 0.8650380600652239, 'colsample_bytree': 0.6101353592760069, 'min_child_weight': 1, 'gamma': 4.11067159970202, 'reg_alpha': 2.937265004827753e-08, 'reg_lambda': 5.4317571033680744e-05, 'max_delta_step': 5}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  36%|███▌      | 72/200 [02:08<01:45,  1.22it/s]

[I 2025-11-10 14:26:12,618] Trial 74 pruned.
[I 2025-11-10 14:26:12,644] Trial 72 pruned.

Best trial: 25. Best value: 0.564416:  37%|███▋      | 74/200 [02:08<01:15,  1.66it/s]

[I 2025-11-10 14:26:13,144] Trial 70 finished with value: 0.5557066462948816 and parameters: {'max_depth': 8, 'learning_rate': 0.04802032071042237, 'n_estimators': 502, 'subsample': 0.8765652749911044, 'colsample_bytree': 0.635722128732256, 'min_child_weight': 1, 'gamma': 4.667497887960241, 'reg_alpha': 5.26060321646197e-07, 'reg_lambda': 1.6348154325795097, 'max_delta_step': 6}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  38%|███▊      | 75/200 [02:09<01:05,  1.92it/s]

[I 2025-11-10 14:26:13,388] Trial 73 pruned.

Best trial: 25. Best value: 0.564416:  38%|███▊      | 76/200 [02:09<01:08,  1.80it/s]

[I 2025-11-10 14:26:14,054] Trial 77 pruned.

Best trial: 25. Best value: 0.564416:  38%|███▊      | 77/200 [02:10<01:25,  1.44it/s]

[I 2025-11-10 14:26:15,160] Trial 79 pruned.

Best trial: 25. Best value: 0.564416:  39%|███▉      | 78/200 [02:15<03:38,  1.79s/it]

[I 2025-11-10 14:26:19,967] Trial 78 finished with value: 0.5144461420932009 and parameters: {'max_depth': 9, 'learning_rate': 0.03149852399619061, 'n_estimators': 543, 'subsample': 0.8268498308452028, 'colsample_bytree': 0.6823946620056883, 'min_child_weight': 1, 'gamma': 4.580651764508563, 'reg_alpha': 1.2219230336685227e-07, 'reg_lambda': 1.6267106777582334, 'max_delta_step': 6}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  40%|███▉      | 79/200 [02:16<03:05,  1.54s/it]

[I 2025-11-10 14:26:20,822] Trial 75 finished with value: 0.5113063407181053 and parameters: {'max_depth': 5, 'learning_rate': 0.030918197716488342, 'n_estimators': 697, 'subsample': 0.7293664758157453, 'colsample_bytree': 0.5857088400331777, 'min_child_weight': 1, 'gamma': 4.598891001277079, 'reg_alpha': 1.1555468596061018e-07, 'reg_lambda': 0.00011970032486128132, 'max_delta_step': 2}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  40%|████      | 80/200 [02:16<02:24,  1.21s/it]

[I 2025-11-10 14:26:21,197] Trial 80 finished with value: 0.5519251336898396 and parameters: {'max_depth': 5, 'learning_rate': 0.03741043696525166, 'n_estimators': 552, 'subsample': 0.8418792928765492, 'colsample_bytree': 0.590949619496324, 'min_child_weight': 1, 'gamma': 4.179230936939992, 'reg_alpha': 1.4867461284845085e-07, 'reg_lambda': 4.133404037385683, 'max_delta_step': 8}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  40%|████      | 81/200 [02:17<02:12,  1.11s/it]

[I 2025-11-10 14:26:22,079] Trial 81 pruned.

Best trial: 25. Best value: 0.564416:  41%|████      | 82/200 [02:18<01:42,  1.15it/s]

[I 2025-11-10 14:26:22,349] Trial 76 finished with value: 0.5145836516424752 and parameters: {'max_depth': 6, 'learning_rate': 0.031139632234648634, 'n_estimators': 549, 'subsample': 0.7228883470124272, 'colsample_bytree': 0.5916310356722444, 'min_child_weight': 1, 'gamma': 1.384529809636017, 'reg_alpha': 1.0439980297967557e-07, 'reg_lambda': 0.013034998761652846, 'max_delta_step': 2}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  42%|████▏     | 83/200 [02:19<01:58,  1.01s/it]

[I 2025-11-10 14:26:23,703] Trial 82 pruned.

Best trial: 25. Best value: 0.564416:  42%|████▏     | 84/200 [02:20<01:59,  1.03s/it]

[I 2025-11-10 14:26:24,777] Trial 86 pruned.

Best trial: 25. Best value: 0.564416:  42%|████▎     | 85/200 [02:21<01:57,  1.03s/it]

[I 2025-11-10 14:26:25,792] Trial 85 pruned.

Best trial: 25. Best value: 0.564416:  43%|████▎     | 86/200 [02:25<03:34,  1.88s/it]

[I 2025-11-10 14:26:29,694] Trial 83 finished with value: 0.5061268143621085 and parameters: {'max_depth': 5, 'learning_rate': 0.04471513227110324, 'n_estimators': 559, 'subsample': 0.8427311288211655, 'colsample_bytree': 0.9940731984560802, 'min_child_weight': 2, 'gamma': 3.8618162621112573, 'reg_alpha': 2.540108977102557e-06, 'reg_lambda': 4.4608961530005224, 'max_delta_step': 10}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  44%|████▎     | 87/200 [02:26<03:09,  1.68s/it]

[I 2025-11-10 14:26:30,898] Trial 89 pruned.

Best trial: 25. Best value: 0.564416:  44%|████▍     | 88/200 [02:28<03:24,  1.82s/it]

[I 2025-11-10 14:26:33,057] Trial 88 finished with value: 0.5087165775401069 and parameters: {'max_depth': 6, 'learning_rate': 0.05305044183208441, 'n_estimators': 484, 'subsample': 0.9018106354454432, 'colsample_bytree': 0.6672422618700841, 'min_child_weight': 1, 'gamma': 3.6766985258477156, 'reg_alpha': 9.617458688451042e-07, 'reg_lambda': 0.1721147884104525, 'max_delta_step': 8}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  44%|████▍     | 89/200 [02:29<02:40,  1.45s/it]

[I 2025-11-10 14:26:33,626] Trial 84 finished with value: 0.5408326967150497 and parameters: {'max_depth': 5, 'learning_rate': 0.03785694488651651, 'n_estimators': 567, 'subsample': 0.83583797452533, 'colsample_bytree': 0.7267642132833261, 'min_child_weight': 1, 'gamma': 1.109677418708349, 'reg_alpha': 1.575327298509854e-08, 'reg_lambda': 6.591525192757118, 'max_delta_step': 10}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  45%|████▌     | 90/200 [02:29<02:00,  1.09s/it]

[I 2025-11-10 14:26:33,885] Trial 90 pruned.

Best trial: 25. Best value: 0.564416:  46%|████▌     | 91/200 [02:31<02:08,  1.18s/it]

[I 2025-11-10 14:26:35,279] Trial 91 pruned.

Best trial: 25. Best value: 0.564416:  46%|████▌     | 92/200 [02:33<02:40,  1.48s/it]

[I 2025-11-10 14:26:37,462] Trial 92 pruned.

Best trial: 25. Best value: 0.564416:  46%|████▋     | 93/200 [02:36<03:29,  1.96s/it]

[I 2025-11-10 14:26:40,532] Trial 87 finished with value: 0.506646294881589 and parameters: {'max_depth': 8, 'learning_rate': 0.03779965457771911, 'n_estimators': 1214, 'subsample': 0.816599235585539, 'colsample_bytree': 0.6669857477769257, 'min_child_weight': 1, 'gamma': 4.869838157160989, 'reg_alpha': 1.9774489196466706e-07, 'reg_lambda': 0.16816214401278906, 'max_delta_step': 8}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  47%|████▋     | 94/200 [02:38<03:29,  1.98s/it]

[I 2025-11-10 14:26:42,550] Trial 93 finished with value: 0.5575401069518717 and parameters: {'max_depth': 4, 'learning_rate': 0.022446815086710373, 'n_estimators': 378, 'subsample': 0.822202568799249, 'colsample_bytree': 0.9387166097686747, 'min_child_weight': 1, 'gamma': 2.7132964606729733, 'reg_alpha': 1.2106293649342473e-05, 'reg_lambda': 1.2327286798786235e-05, 'max_delta_step': 5}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  48%|████▊     | 95/200 [02:40<03:29,  2.00s/it]

[I 2025-11-10 14:26:44,601] Trial 97 pruned.

Best trial: 25. Best value: 0.564416:  48%|████▊     | 96/200 [02:42<03:27,  2.00s/it]

[I 2025-11-10 14:26:46,597] Trial 95 finished with value: 0.5079297173414821 and parameters: {'max_depth': 7, 'learning_rate': 0.03359214135774211, 'n_estimators': 614, 'subsample': 0.7456555774168069, 'colsample_bytree': 0.565787702867778, 'min_child_weight': 1, 'gamma': 2.2958522415441176, 'reg_alpha': 1.0631318789973227e-05, 'reg_lambda': 0.6027142312409053, 'max_delta_step': 3}. Best is trial 25 with value: 0.5644155844155845.
[I 2025-11-10 14:26:46,611] Trial 94 finished with value: 0.5266692131398014 and parameters: {'max_depth': 7, 'learning_rate': 0.018366376267494537, 'n_estimators': 682, 'subsample': 0.7709984031643153, 'colsample_bytree': 0.5701460593639875, 'min_child_weight': 1, 'gamma': 2.6264130248031337, 'reg_alpha': 1.8368129648214298e-06, 'reg_lambda': 1.6811468314548462e-05, 'max_delta_step': 3}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  49%|████▉     | 98/200 [02:47<03:42,  2.18s/it]

[I 2025-11-10 14:26:51,382] Trial 96 finished with value: 0.545118411000764 and parameters: {'max_depth': 7, 'learning_rate': 0.018218234381874455, 'n_estimators': 618, 'subsample': 0.746704658146126, 'colsample_bytree': 0.6190006759414812, 'min_child_weight': 1, 'gamma': 2.3861922684089665, 'reg_alpha': 1.0478767392427873e-05, 'reg_lambda': 0.5983978585605638, 'max_delta_step': 3}. Best is trial 25 with value: 0.5644155844155845.

Best trial: 25. Best value: 0.564416:  50%|████▉     | 99/200 [02:48<03:31,  2.09s/it]

[I 2025-11-10 14:26:53,211] Trial 101 pruned.

Best trial: 99. Best value: 0.588869:  50%|█████     | 100/200 [02:49<02:45,  1.65s/it]

[I 2025-11-10 14:26:53,626] Trial 99 finished with value: 0.5888693659281895 and parameters: {'max_depth': 4, 'learning_rate': 0.028493718990306293, 'n_estimators': 300, 'subsample': 0.7691277020796791, 'colsample_bytree': 0.9695388521804291, 'min_child_weight': 1, 'gamma': 2.724739993990795, 'reg_alpha': 4.601355337565294e-06, 'reg_lambda': 2.1015239203189402e-05, 'max_delta_step': 6}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  50%|█████     | 101/200 [02:50<02:25,  1.47s/it]

[I 2025-11-10 14:26:54,616] Trial 102 pruned.

Best trial: 99. Best value: 0.588869:  51%|█████     | 102/200 [02:50<01:55,  1.18s/it]

[I 2025-11-10 14:26:55,030] Trial 98 finished with value: 0.5462796027501909 and parameters: {'max_depth': 4, 'learning_rate': 0.03376300504907951, 'n_estimators': 612, 'subsample': 0.7496743475651327, 'colsample_bytree': 0.88999165931422, 'min_child_weight': 1, 'gamma': 2.687171478715359, 'reg_alpha': 9.986197385848994e-06, 'reg_lambda': 0.7420662385692142, 'max_delta_step': 6}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  52%|█████▏    | 103/200 [02:51<01:54,  1.18s/it]

[I 2025-11-10 14:26:56,217] Trial 100 finished with value: 0.5242475171886937 and parameters: {'max_depth': 4, 'learning_rate': 0.028459471127154034, 'n_estimators': 521, 'subsample': 0.6734781147329336, 'colsample_bytree': 0.9739796422515754, 'min_child_weight': 1, 'gamma': 3.4747396478939168, 'reg_alpha': 1.2214670485945949e-05, 'reg_lambda': 2.397474532060725e-06, 'max_delta_step': 6}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  52%|█████▏    | 104/200 [02:54<02:28,  1.55s/it]

[I 2025-11-10 14:26:58,671] Trial 103 finished with value: 0.5291520244461421 and parameters: {'max_depth': 4, 'learning_rate': 0.023445262979853693, 'n_estimators': 259, 'subsample': 0.6775878600115139, 'colsample_bytree': 0.9831039344035222, 'min_child_weight': 2, 'gamma': 2.67267894650714, 'reg_alpha': 4.778505459094284e-06, 'reg_lambda': 2.238437165316048, 'max_delta_step': 6}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  52%|█████▎    | 105/200 [02:56<02:29,  1.57s/it]

[I 2025-11-10 14:27:00,292] Trial 104 finished with value: 0.546279602750191 and parameters: {'max_depth': 4, 'learning_rate': 0.027898228174991515, 'n_estimators': 258, 'subsample': 0.8075145232034571, 'colsample_bytree': 0.9408984896495677, 'min_child_weight': 1, 'gamma': 3.1807676591502694, 'reg_alpha': 1.4117089514829052e-05, 'reg_lambda': 1.8969129781411272e-05, 'max_delta_step': 6}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  53%|█████▎    | 106/200 [02:58<02:39,  1.70s/it]

[I 2025-11-10 14:27:02,302] Trial 106 finished with value: 0.5608326967150497 and parameters: {'max_depth': 4, 'learning_rate': 0.02500878225789178, 'n_estimators': 236, 'subsample': 0.8071671529309288, 'colsample_bytree': 0.9925895023915862, 'min_child_weight': 1, 'gamma': 2.974967502346965, 'reg_alpha': 7.430651269916961e-07, 'reg_lambda': 7.470864394565764e-05, 'max_delta_step': 5}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  54%|█████▎    | 107/200 [02:58<01:56,  1.26s/it]

[I 2025-11-10 14:27:02,511] Trial 105 finished with value: 0.5421619556913675 and parameters: {'max_depth': 5, 'learning_rate': 0.028292836769938778, 'n_estimators': 255, 'subsample': 0.8049313843150121, 'colsample_bytree': 0.9425135804795349, 'min_child_weight': 1, 'gamma': 1.9072351384766104, 'reg_alpha': 5.092592645832832e-06, 'reg_lambda': 7.200381156659085e-06, 'max_delta_step': 6}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  55%|█████▍    | 109/200 [02:59<01:17,  1.17it/s]

[I 2025-11-10 14:27:03,402] Trial 109 pruned.
[I 2025-11-10 14:27:03,573] Trial 110 pruned.

Best trial: 99. Best value: 0.588869:  55%|█████▌    | 110/200 [03:00<01:26,  1.04it/s]

[I 2025-11-10 14:27:04,775] Trial 111 pruned.

Best trial: 99. Best value: 0.588869:  56%|█████▌    | 111/200 [03:00<01:08,  1.29it/s]

[I 2025-11-10 14:27:05,116] Trial 112 pruned.

Best trial: 99. Best value: 0.588869:  56%|█████▌    | 112/200 [03:01<00:57,  1.52it/s]

[I 2025-11-10 14:27:05,500] Trial 107 finished with value: 0.5499236058059587 and parameters: {'max_depth': 3, 'learning_rate': 0.020396748750680697, 'n_estimators': 290, 'subsample': 0.8038882440343108, 'colsample_bytree': 0.9431773266770991, 'min_child_weight': 1, 'gamma': 3.1682994901034736, 'reg_alpha': 2.6136762352857774e-05, 'reg_lambda': 8.605636326056015e-05, 'max_delta_step': 5}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  56%|█████▋    | 113/200 [03:04<01:56,  1.34s/it]

[I 2025-11-10 14:27:08,422] Trial 108 finished with value: 0.532987012987013 and parameters: {'max_depth': 5, 'learning_rate': 0.02572013282387508, 'n_estimators': 359, 'subsample': 0.7089740797867804, 'colsample_bytree': 0.917280624031682, 'min_child_weight': 1, 'gamma': 2.9777295294372026, 'reg_alpha': 3.3127213788173006e-07, 'reg_lambda': 7.669642343740601e-05, 'max_delta_step': 5}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  57%|█████▋    | 114/200 [03:06<02:28,  1.72s/it]

[I 2025-11-10 14:27:11,044] Trial 113 finished with value: 0.5286172650878533 and parameters: {'max_depth': 5, 'learning_rate': 0.03011288562410563, 'n_estimators': 375, 'subsample': 0.8831301344806216, 'colsample_bytree': 0.9716907172031065, 'min_child_weight': 2, 'gamma': 3.1044537809393433, 'reg_alpha': 2.4542375399850518e-05, 'reg_lambda': 8.901617365044434e-05, 'max_delta_step': 7}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  57%|█████▊    | 115/200 [03:07<01:56,  1.37s/it]

[I 2025-11-10 14:27:11,579] Trial 115 finished with value: 0.5352864782276547 and parameters: {'max_depth': 3, 'learning_rate': 0.023078070327626758, 'n_estimators': 296, 'subsample': 0.8498128467154872, 'colsample_bytree': 0.9613425157422453, 'min_child_weight': 1, 'gamma': 3.0896533787320646, 'reg_alpha': 2.281429678665976e-05, 'reg_lambda': 0.00010838291856175401, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  58%|█████▊    | 116/200 [03:08<01:45,  1.25s/it]

[I 2025-11-10 14:27:12,563] Trial 114 finished with value: 0.5619098548510314 and parameters: {'max_depth': 5, 'learning_rate': 0.04279253692838216, 'n_estimators': 419, 'subsample': 0.8301632111632379, 'colsample_bytree': 0.9807688163417629, 'min_child_weight': 1, 'gamma': 2.753315775457214, 'reg_alpha': 2.673663726404543e-05, 'reg_lambda': 2.4277591382354977e-05, 'max_delta_step': 5}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  58%|█████▊    | 117/200 [03:10<02:09,  1.56s/it]

[I 2025-11-10 14:27:14,831] Trial 116 finished with value: 0.559572192513369 and parameters: {'max_depth': 3, 'learning_rate': 0.022787313399220552, 'n_estimators': 316, 'subsample': 0.8302434248722631, 'colsample_bytree': 0.9580358404770419, 'min_child_weight': 1, 'gamma': 2.7554129502722025, 'reg_alpha': 2.3082595663297723e-05, 'reg_lambda': 0.00023770440758554687, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  59%|█████▉    | 118/200 [03:12<02:17,  1.68s/it]

[I 2025-11-10 14:27:16,798] Trial 120 pruned.

Best trial: 99. Best value: 0.588869:  60%|█████▉    | 119/200 [03:13<02:03,  1.53s/it]

[I 2025-11-10 14:27:17,965] Trial 117 finished with value: 0.5380595874713523 and parameters: {'max_depth': 3, 'learning_rate': 0.016446437769366894, 'n_estimators': 287, 'subsample': 0.8511733596034929, 'colsample_bytree': 0.9489336787718816, 'min_child_weight': 1, 'gamma': 2.779483950072609, 'reg_alpha': 2.195287055998798e-05, 'reg_lambda': 0.02215223156543101, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  60%|██████    | 120/200 [03:14<01:39,  1.24s/it]

[I 2025-11-10 14:27:18,546] Trial 118 finished with value: 0.5304812834224599 and parameters: {'max_depth': 3, 'learning_rate': 0.043503190163518335, 'n_estimators': 402, 'subsample': 0.734068381960226, 'colsample_bytree': 0.9839659830838758, 'min_child_weight': 1, 'gamma': 3.2312352217108895, 'reg_alpha': 0.0011486384614649505, 'reg_lambda': 0.00026017918753528085, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  60%|██████    | 121/200 [03:14<01:16,  1.03it/s]

[I 2025-11-10 14:27:18,877] Trial 119 finished with value: 0.556279602750191 and parameters: {'max_depth': 3, 'learning_rate': 0.01904760535763525, 'n_estimators': 232, 'subsample': 0.8291875485757042, 'colsample_bytree': 0.9819773648307776, 'min_child_weight': 1, 'gamma': 2.734454552625032, 'reg_alpha': 7.973058654636684e-05, 'reg_lambda': 0.0001823271642630361, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  61%|██████    | 122/200 [03:15<01:01,  1.26it/s]

[I 2025-11-10 14:27:19,259] Trial 122 pruned.

Best trial: 99. Best value: 0.588869:  62%|██████▏   | 123/200 [03:18<01:57,  1.53s/it]

[I 2025-11-10 14:27:22,514] Trial 121 finished with value: 0.5315584415584416 and parameters: {'max_depth': 3, 'learning_rate': 0.021556622022939145, 'n_estimators': 236, 'subsample': 0.7692584759306931, 'colsample_bytree': 0.9502854770164301, 'min_child_weight': 1, 'gamma': 2.7410325207806636, 'reg_alpha': 5.378020747612898e-05, 'reg_lambda': 0.00025423455915723017, 'max_delta_step': 5}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  62%|██████▏   | 124/200 [03:18<01:37,  1.29s/it]

[I 2025-11-10 14:27:23,229] Trial 126 pruned.

Best trial: 99. Best value: 0.588869:  62%|██████▎   | 125/200 [03:20<01:49,  1.46s/it]

[I 2025-11-10 14:27:25,104] Trial 123 finished with value: 0.5060275019098548 and parameters: {'max_depth': 3, 'learning_rate': 0.019671192532456198, 'n_estimators': 304, 'subsample': 0.7937858417127883, 'colsample_bytree': 0.9672053537177279, 'min_child_weight': 1, 'gamma': 3.370745011341342, 'reg_alpha': 6.717019378178678e-05, 'reg_lambda': 0.0005848107502711554, 'max_delta_step': 5}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  63%|██████▎   | 126/200 [03:21<01:26,  1.17s/it]

[I 2025-11-10 14:27:25,577] Trial 124 finished with value: 0.5435064935064935 and parameters: {'max_depth': 3, 'learning_rate': 0.02020493467051763, 'n_estimators': 286, 'subsample': 0.8331290760510088, 'colsample_bytree': 0.9635769673062319, 'min_child_weight': 1, 'gamma': 2.8699474997431147, 'reg_alpha': 0.00018900043094171475, 'reg_lambda': 0.0006862383523110933, 'max_delta_step': 5}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  64%|██████▎   | 127/200 [03:22<01:15,  1.03s/it]

[I 2025-11-10 14:27:26,283] Trial 125 finished with value: 0.5529870129870129 and parameters: {'max_depth': 3, 'learning_rate': 0.020320840797206963, 'n_estimators': 285, 'subsample': 0.7674477342926054, 'colsample_bytree': 0.9993501285838962, 'min_child_weight': 1, 'gamma': 2.7364733996867834, 'reg_alpha': 5.615506346179244e-05, 'reg_lambda': 0.0007585503757264216, 'max_delta_step': 5}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  64%|██████▍   | 128/200 [03:23<01:22,  1.14s/it]

[I 2025-11-10 14:27:27,695] Trial 129 pruned.

Best trial: 99. Best value: 0.588869:  64%|██████▍   | 129/200 [03:27<02:20,  1.99s/it]

[I 2025-11-10 14:27:31,646] Trial 127 finished with value: 0.54012987012987 and parameters: {'max_depth': 3, 'learning_rate': 0.014375559496013322, 'n_estimators': 321, 'subsample': 0.8362177244948108, 'colsample_bytree': 0.9985589903086227, 'min_child_weight': 1, 'gamma': 2.5580331303679067, 'reg_alpha': 0.00016904353287061318, 'reg_lambda': 0.0006337061555469081, 'max_delta_step': 5}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  65%|██████▌   | 130/200 [03:28<01:56,  1.67s/it]

[I 2025-11-10 14:27:32,579] Trial 132 pruned.

Best trial: 99. Best value: 0.588869:  66%|██████▌   | 131/200 [03:29<01:43,  1.50s/it]

[I 2025-11-10 14:27:33,666] Trial 130 finished with value: 0.5491367456073338 and parameters: {'max_depth': 3, 'learning_rate': 0.025938824691072122, 'n_estimators': 345, 'subsample': 0.8092036931627196, 'colsample_bytree': 0.9983775574230485, 'min_child_weight': 1, 'gamma': 2.3747243115891767, 'reg_alpha': 0.00021692653660621038, 'reg_lambda': 4.647285110270646e-05, 'max_delta_step': 5}. Best is trial 99 with value: 0.5888693659281895.
[I 2025-11-10 14:27:33,749] Trial 128 finished with value: 0.5461955691367456 and parameters: {'max_depth': 3, 'learning_rate': 0.014125878080504445, 'n_estimators': 336, 'subsample': 0.8110790077847537, 'colsample_bytree': 0.9991509278216011, 'min_child_weight': 1, 'gamma': 2.5681734414071737, 'reg_alpha': 0.00020296191426105763, 'reg_lambda': 4.3456950164931386e-05, 'max_delta_step': 5}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  66%|██████▋   | 133/200 [03:30<01:14,  1.11s/it]

[I 2025-11-10 14:27:34,974] Trial 131 finished with value: 0.5590527119938884 and parameters: {'max_depth': 3, 'learning_rate': 0.02613147753787361, 'n_estimators': 332, 'subsample': 0.8093090969366226, 'colsample_bytree': 0.9975470700746663, 'min_child_weight': 1, 'gamma': 2.348302674485652, 'reg_alpha': 2.8657345057204415e-05, 'reg_lambda': 0.00018010157861728628, 'max_delta_step': 5}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  67%|██████▋   | 134/200 [03:34<01:59,  1.81s/it]

[I 2025-11-10 14:27:38,936] Trial 133 finished with value: 0.5461955691367456 and parameters: {'max_depth': 3, 'learning_rate': 0.021750706346268824, 'n_estimators': 224, 'subsample': 0.8122802779224501, 'colsample_bytree': 0.9813383537526364, 'min_child_weight': 1, 'gamma': 2.2022450934374724, 'reg_alpha': 8.453531604496956e-05, 'reg_lambda': 0.0001729116986304206, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  68%|██████▊   | 135/200 [03:36<01:50,  1.69s/it]

[I 2025-11-10 14:27:40,283] Trial 134 finished with value: 0.5445836516424751 and parameters: {'max_depth': 8, 'learning_rate': 0.022716864924967342, 'n_estimators': 221, 'subsample': 0.7588553749017242, 'colsample_bytree': 0.981222355968433, 'min_child_weight': 1, 'gamma': 2.7673792669777364, 'reg_alpha': 7.682893043075579e-05, 'reg_lambda': 0.00016848418842536615, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  68%|██████▊   | 136/200 [03:37<01:49,  1.71s/it]

[I 2025-11-10 14:27:42,030] Trial 136 finished with value: 0.5369365928189458 and parameters: {'max_depth': 3, 'learning_rate': 0.024110700216352046, 'n_estimators': 270, 'subsample': 0.8251512581195628, 'colsample_bytree': 0.9789390567702142, 'min_child_weight': 1, 'gamma': 2.115561612597452, 'reg_alpha': 1.595706295146795e-05, 'reg_lambda': 0.00015684163704909787, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  68%|██████▊   | 137/200 [03:37<01:21,  1.29s/it]

[I 2025-11-10 14:27:42,232] Trial 135 finished with value: 0.5602979373567608 and parameters: {'max_depth': 8, 'learning_rate': 0.022844240060921353, 'n_estimators': 266, 'subsample': 0.7565090148159933, 'colsample_bytree': 0.9804393769376368, 'min_child_weight': 1, 'gamma': 2.0934061850505143, 'reg_alpha': 1.6477438746655724e-05, 'reg_lambda': 0.00018646888437209608, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  69%|██████▉   | 138/200 [03:39<01:21,  1.32s/it]

[I 2025-11-10 14:27:43,636] Trial 139 pruned.

Best trial: 99. Best value: 0.588869:  70%|██████▉   | 139/200 [03:41<01:40,  1.65s/it]

[I 2025-11-10 14:27:46,101] Trial 137 finished with value: 0.547440794499618 and parameters: {'max_depth': 3, 'learning_rate': 0.024073178203452228, 'n_estimators': 266, 'subsample': 0.7685131911024885, 'colsample_bytree': 0.9511339603342939, 'min_child_weight': 1, 'gamma': 2.101163115534738, 'reg_alpha': 1.772715402940867e-05, 'reg_lambda': 0.0004427453383210451, 'max_delta_step': 5}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  70%|███████   | 140/200 [03:42<01:16,  1.27s/it]

[I 2025-11-10 14:27:46,441] Trial 138 finished with value: 0.5731168831168831 and parameters: {'max_depth': 3, 'learning_rate': 0.024013667302843992, 'n_estimators': 270, 'subsample': 0.8229969017042262, 'colsample_bytree': 0.9537194547483351, 'min_child_weight': 1, 'gamma': 3.0113988871586717, 'reg_alpha': 1.626528060435365e-05, 'reg_lambda': 2.457279196289889e-05, 'max_delta_step': 5}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  70%|███████   | 141/200 [03:43<01:17,  1.31s/it]

[I 2025-11-10 14:27:47,853] Trial 143 pruned.

Best trial: 99. Best value: 0.588869:  71%|███████   | 142/200 [03:45<01:20,  1.38s/it]

[I 2025-11-10 14:27:49,411] Trial 140 finished with value: 0.5524293353705118 and parameters: {'max_depth': 4, 'learning_rate': 0.03315758016230655, 'n_estimators': 390, 'subsample': 0.8719702081334947, 'colsample_bytree': 0.9593557017293578, 'min_child_weight': 2, 'gamma': 2.6444927556315796, 'reg_alpha': 8.106823780325479e-06, 'reg_lambda': 0.00038357095519676334, 'max_delta_step': 3}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  72%|███████▏  | 143/200 [03:47<01:30,  1.60s/it]

[I 2025-11-10 14:27:51,511] Trial 145 pruned.

Best trial: 99. Best value: 0.588869:  72%|███████▏  | 144/200 [03:48<01:27,  1.57s/it]

[I 2025-11-10 14:27:53,005] Trial 146 pruned.

Best trial: 99. Best value: 0.588869:  72%|███████▎  | 145/200 [03:49<01:15,  1.36s/it]

[I 2025-11-10 14:27:53,895] Trial 141 finished with value: 0.5512070282658518 and parameters: {'max_depth': 6, 'learning_rate': 0.028624963839611342, 'n_estimators': 393, 'subsample': 0.7662982700438755, 'colsample_bytree': 0.9881506564633663, 'min_child_weight': 1, 'gamma': 2.2634998619558315, 'reg_alpha': 6.925063595189908e-06, 'reg_lambda': 0.000373717198002487, 'max_delta_step': 3}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  73%|███████▎  | 146/200 [03:52<01:36,  1.79s/it]

[I 2025-11-10 14:27:56,672] Trial 144 finished with value: 0.5238579067990832 and parameters: {'max_depth': 4, 'learning_rate': 0.029736617979489087, 'n_estimators': 391, 'subsample': 0.8584749533650928, 'colsample_bytree': 0.9667040223531662, 'min_child_weight': 1, 'gamma': 2.6894008402424427, 'reg_alpha': 7.894213250374586e-06, 'reg_lambda': 0.0009650366089419449, 'max_delta_step': 3}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  74%|███████▎  | 147/200 [03:52<01:13,  1.38s/it]

[I 2025-11-10 14:27:57,108] Trial 142 finished with value: 0.5702979373567609 and parameters: {'max_depth': 6, 'learning_rate': 0.027099850247452876, 'n_estimators': 422, 'subsample': 0.7417799246836121, 'colsample_bytree': 0.9858702258565017, 'min_child_weight': 1, 'gamma': 2.293125159596236, 'reg_alpha': 4.297513525495815e-05, 'reg_lambda': 0.0008622186360645983, 'max_delta_step': 3}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  74%|███████▍  | 148/200 [03:54<01:13,  1.41s/it]

[I 2025-11-10 14:27:58,575] Trial 149 pruned.

Best trial: 99. Best value: 0.588869:  74%|███████▍  | 149/200 [03:58<01:52,  2.20s/it]

[I 2025-11-10 14:28:02,642] Trial 148 finished with value: 0.5433384262796027 and parameters: {'max_depth': 4, 'learning_rate': 0.05009687498018231, 'n_estimators': 418, 'subsample': 0.7842927681946662, 'colsample_bytree': 0.9713290076914722, 'min_child_weight': 1, 'gamma': 2.734448550638449, 'reg_alpha': 1.3838875318171559e-05, 'reg_lambda': 0.0008153384333198432, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  75%|███████▌  | 150/200 [03:59<01:31,  1.83s/it]

[I 2025-11-10 14:28:03,606] Trial 147 finished with value: 0.5285332314744079 and parameters: {'max_depth': 4, 'learning_rate': 0.022427280474576584, 'n_estimators': 431, 'subsample': 0.8571732697494023, 'colsample_bytree': 0.9727279118293646, 'min_child_weight': 1, 'gamma': 2.6704501283281834, 'reg_alpha': 2.1711828539850947e-06, 'reg_lambda': 3.977660930660029e-06, 'max_delta_step': 3}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  76%|███████▌  | 151/200 [04:00<01:18,  1.60s/it]

[I 2025-11-10 14:28:04,653] Trial 152 pruned.

Best trial: 99. Best value: 0.588869:  76%|███████▌  | 152/200 [04:02<01:25,  1.78s/it]

[I 2025-11-10 14:28:06,846] Trial 151 finished with value: 0.5460122230710466 and parameters: {'max_depth': 6, 'learning_rate': 0.06031686594613532, 'n_estimators': 330, 'subsample': 0.7380538854449927, 'colsample_bytree': 0.9730093356032906, 'min_child_weight': 1, 'gamma': 1.863809840999443, 'reg_alpha': 5.629285426280945e-05, 'reg_lambda': 4.312957019192175e-06, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  76%|███████▋  | 153/200 [04:03<01:13,  1.56s/it]

[I 2025-11-10 14:28:07,914] Trial 155 pruned.

Best trial: 99. Best value: 0.588869:  77%|███████▋  | 154/200 [04:04<00:59,  1.30s/it]

[I 2025-11-10 14:28:08,601] Trial 150 finished with value: 0.5526355996944232 and parameters: {'max_depth': 6, 'learning_rate': 0.02244346835628816, 'n_estimators': 320, 'subsample': 0.7782015660762974, 'colsample_bytree': 0.9802882489644615, 'min_child_weight': 1, 'gamma': 1.8481127763888259, 'reg_alpha': 1.6303018939451268e-05, 'reg_lambda': 0.003816809313540315, 'max_delta_step': 6}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  78%|███████▊  | 155/200 [04:09<01:44,  2.32s/it]

[I 2025-11-10 14:28:13,316] Trial 154 finished with value: 0.5236440030557677 and parameters: {'max_depth': 6, 'learning_rate': 0.03496869091357574, 'n_estimators': 323, 'subsample': 0.8765530903947669, 'colsample_bytree': 0.9999945054509344, 'min_child_weight': 1, 'gamma': 2.3179776588575147, 'reg_alpha': 2.9124409938678127e-05, 'reg_lambda': 0.003770691266991623, 'max_delta_step': 2}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  78%|███████▊  | 156/200 [04:09<01:17,  1.77s/it]

[I 2025-11-10 14:28:13,789] Trial 153 finished with value: 0.5665317035905271 and parameters: {'max_depth': 6, 'learning_rate': 0.018511781029397725, 'n_estimators': 201, 'subsample': 0.7407502746188197, 'colsample_bytree': 0.9996537230457658, 'min_child_weight': 1, 'gamma': 1.8691232353649048, 'reg_alpha': 5.337786668715374e-05, 'reg_lambda': 0.0036422328068495546, 'max_delta_step': 6}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  78%|███████▊  | 157/200 [04:09<00:58,  1.36s/it]

[I 2025-11-10 14:28:14,185] Trial 156 finished with value: 0.532566844919786 and parameters: {'max_depth': 3, 'learning_rate': 0.02546635240395998, 'n_estimators': 201, 'subsample': 0.8779682743306891, 'colsample_bytree': 0.9992548448054451, 'min_child_weight': 1, 'gamma': 2.335241989844986, 'reg_alpha': 3.96131522227263e-06, 'reg_lambda': 9.807072169164438e-06, 'max_delta_step': 2}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  79%|███████▉  | 158/200 [04:10<00:51,  1.23s/it]

[I 2025-11-10 14:28:15,130] Trial 158 pruned.

Best trial: 99. Best value: 0.588869:  80%|████████  | 160/200 [04:11<00:30,  1.33it/s]

[I 2025-11-10 14:28:15,629] Trial 161 pruned.
[I 2025-11-10 14:28:15,780] Trial 159 pruned.

Best trial: 99. Best value: 0.588869:  80%|████████  | 161/200 [04:12<00:28,  1.39it/s]

[I 2025-11-10 14:28:16,419] Trial 160 pruned.

Best trial: 99. Best value: 0.588869:  81%|████████  | 162/200 [04:12<00:27,  1.40it/s]

[I 2025-11-10 14:28:17,127] Trial 157 finished with value: 0.548785332314744 and parameters: {'max_depth': 6, 'learning_rate': 0.026286791188811942, 'n_estimators': 206, 'subsample': 0.7535402600125849, 'colsample_bytree': 0.9889857734536153, 'min_child_weight': 1, 'gamma': 2.016052528251697, 'reg_alpha': 0.00011469661721750343, 'reg_lambda': 0.005456349787281454, 'max_delta_step': 5}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  82%|████████▏ | 163/200 [04:13<00:22,  1.64it/s]

[I 2025-11-10 14:28:17,490] Trial 162 pruned.
[I 2025-11-10 14:28:17,510] Trial 163 pruned.

Best trial: 99. Best value: 0.588869:  82%|████████▎ | 165/200 [04:23<01:33,  2.67s/it]

[I 2025-11-10 14:28:27,632] Trial 165 finished with value: 0.5363177998472116 and parameters: {'max_depth': 6, 'learning_rate': 0.0208145671026925, 'n_estimators': 239, 'subsample': 0.772981584657713, 'colsample_bytree': 0.9760530125923916, 'min_child_weight': 1, 'gamma': 1.844063677327274, 'reg_alpha': 5.977882044264286e-07, 'reg_lambda': 0.0023314245999084796, 'max_delta_step': 6}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  83%|████████▎ | 166/200 [04:23<01:10,  2.06s/it]

[I 2025-11-10 14:28:27,842] Trial 164 finished with value: 0.5627196333078686 and parameters: {'max_depth': 6, 'learning_rate': 0.02095752246903072, 'n_estimators': 240, 'subsample': 0.7748254250563618, 'colsample_bytree': 0.9767168132891385, 'min_child_weight': 1, 'gamma': 1.6186420151800684, 'reg_alpha': 6.406808047663185e-07, 'reg_lambda': 0.002876200060010362, 'max_delta_step': 6}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  84%|████████▎ | 167/200 [04:24<00:58,  1.76s/it]

[I 2025-11-10 14:28:28,758] Trial 167 finished with value: 0.5512070282658518 and parameters: {'max_depth': 8, 'learning_rate': 0.023970947982543973, 'n_estimators': 307, 'subsample': 0.7721059000698532, 'colsample_bytree': 0.9775652263435166, 'min_child_weight': 1, 'gamma': 1.835023649791762, 'reg_alpha': 6.143179364078596e-07, 'reg_lambda': 0.0018259573095517768, 'max_delta_step': 6}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  84%|████████▍ | 168/200 [04:25<00:48,  1.50s/it]

[I 2025-11-10 14:28:29,562] Trial 166 finished with value: 0.5390909090909091 and parameters: {'max_depth': 6, 'learning_rate': 0.021287378380193414, 'n_estimators': 302, 'subsample': 0.7741902059280148, 'colsample_bytree': 0.9780478864000941, 'min_child_weight': 1, 'gamma': 1.7876853051942272, 'reg_alpha': 2.153227125113473e-05, 'reg_lambda': 0.00010455067208597447, 'max_delta_step': 6}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  84%|████████▍ | 169/200 [04:25<00:38,  1.24s/it]

[I 2025-11-10 14:28:30,118] Trial 168 pruned.

Best trial: 99. Best value: 0.588869:  85%|████████▌ | 170/200 [04:26<00:33,  1.12s/it]

[I 2025-11-10 14:28:30,931] Trial 169 pruned.

Best trial: 99. Best value: 0.588869:  86%|████████▌ | 171/200 [04:27<00:26,  1.11it/s]

[I 2025-11-10 14:28:31,296] Trial 170 pruned.

Best trial: 99. Best value: 0.588869:  86%|████████▌ | 172/200 [04:36<01:35,  3.41s/it]

[I 2025-11-10 14:28:40,776] Trial 172 finished with value: 0.5344155844155845 and parameters: {'max_depth': 7, 'learning_rate': 0.02677211249888824, 'n_estimators': 475, 'subsample': 0.7449694674418154, 'colsample_bytree': 0.8353790065995628, 'min_child_weight': 1, 'gamma': 2.869076590671749, 'reg_alpha': 1.1190244830839276e-06, 'reg_lambda': 3.172894647184791e-05, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  86%|████████▋ | 173/200 [04:36<01:08,  2.54s/it]

[I 2025-11-10 14:28:41,230] Trial 171 finished with value: 0.5578762414056532 and parameters: {'max_depth': 7, 'learning_rate': 0.04574578177657793, 'n_estimators': 472, 'subsample': 0.8010870072636994, 'colsample_bytree': 0.9601610822940645, 'min_child_weight': 1, 'gamma': 1.4229536653844552, 'reg_alpha': 3.2660223085395386e-07, 'reg_lambda': 0.015414657814790554, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  87%|████████▋ | 174/200 [04:38<00:54,  2.10s/it]

[I 2025-11-10 14:28:42,282] Trial 173 finished with value: 0.556279602750191 and parameters: {'max_depth': 7, 'learning_rate': 0.017391855350767267, 'n_estimators': 362, 'subsample': 0.8368052529013368, 'colsample_bytree': 0.9660514953668682, 'min_child_weight': 1, 'gamma': 2.8848875216589427, 'reg_alpha': 0.19866530721296902, 'reg_lambda': 4.522667459163764e-05, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  88%|████████▊ | 175/200 [04:39<00:50,  2.03s/it]

[I 2025-11-10 14:28:44,138] Trial 174 finished with value: 0.5416424751718869 and parameters: {'max_depth': 6, 'learning_rate': 0.022234507168024813, 'n_estimators': 361, 'subsample': 0.7606436243011103, 'colsample_bytree': 0.9703000594633712, 'min_child_weight': 1, 'gamma': 1.5760924197868498, 'reg_alpha': 3.7079339315189406e-05, 'reg_lambda': 0.004661747837836289, 'max_delta_step': 6}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  88%|████████▊ | 176/200 [04:40<00:36,  1.52s/it]

[I 2025-11-10 14:28:44,462] Trial 175 pruned.

Best trial: 99. Best value: 0.588869:  88%|████████▊ | 177/200 [04:42<00:39,  1.72s/it]

[I 2025-11-10 14:28:46,668] Trial 179 pruned.

Best trial: 99. Best value: 0.588869:  89%|████████▉ | 178/200 [04:45<00:45,  2.09s/it]

[I 2025-11-10 14:28:49,613] Trial 176 finished with value: 0.5634224598930482 and parameters: {'max_depth': 9, 'learning_rate': 0.04202337840118033, 'n_estimators': 368, 'subsample': 0.7615824672139717, 'colsample_bytree': 0.9664524470427489, 'min_child_weight': 1, 'gamma': 3.0755134923785232, 'reg_alpha': 0.5440854188398694, 'reg_lambda': 0.012603682314748432, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  90%|████████▉ | 179/200 [04:46<00:39,  1.88s/it]

[I 2025-11-10 14:28:51,022] Trial 177 finished with value: 0.5752711993888464 and parameters: {'max_depth': 7, 'learning_rate': 0.05706802180509221, 'n_estimators': 372, 'subsample': 0.8345127092006912, 'colsample_bytree': 0.905557467980489, 'min_child_weight': 1, 'gamma': 1.3283160811608339, 'reg_alpha': 0.21799607202361884, 'reg_lambda': 0.011797038842290698, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  90%|█████████ | 180/200 [04:49<00:42,  2.10s/it]

[I 2025-11-10 14:28:53,627] Trial 178 finished with value: 0.5591367456073338 and parameters: {'max_depth': 7, 'learning_rate': 0.01717266796826874, 'n_estimators': 359, 'subsample': 0.8364902251872262, 'colsample_bytree': 0.9510894508992482, 'min_child_weight': 1, 'gamma': 3.0230068168200495, 'reg_alpha': 8.148231751908931e-07, 'reg_lambda': 0.016919246899810208, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  90%|█████████ | 181/200 [04:54<00:57,  3.00s/it]

[I 2025-11-10 14:28:58,732] Trial 180 finished with value: 0.5591367456073338 and parameters: {'max_depth': 7, 'learning_rate': 0.017211845996426577, 'n_estimators': 516, 'subsample': 0.8174435817757213, 'colsample_bytree': 0.9525637329709351, 'min_child_weight': 1, 'gamma': 2.8871810786778287, 'reg_alpha': 0.03497656183189022, 'reg_lambda': 0.02773255501468341, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.

Best trial: 99. Best value: 0.588869:  92%|█████████▏| 183/200 [04:55<00:42,  2.48s/it]

[I 2025-11-10 14:29:00,006] Trial 182 finished with value: 0.5699923605805959 and parameters: {'max_depth': 9, 'learning_rate': 0.06230866808015995, 'n_estimators': 411, 'subsample': 0.8231339283542101, 'colsample_bytree': 0.9504450558293132, 'min_child_weight': 1, 'gamma': 1.3093842712844677, 'reg_alpha': 0.25265671888652447, 'reg_lambda': 0.01837914643455892, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.
[I 2025-11-10 14:29:00,016] Trial 181 finished with value: 0.5447669977081742 and parameters: {'max_depth': 7, 'learning_rate': 0.017446461771350036, 'n_estimators': 413, 'subsample': 0.8196393549383746, 'colsample_bytree': 0.951149548353648, 'min_child_weight': 1, 'gamma': 2.9485956906356456, 'reg_alpha': 0.22604766863473044, 'reg_lambda': 0.03529433133144748, 'max_delta_step': 4}. Best is trial 99 with value: 0.5888693659281895.
[I 2025-11-10 14:29:00,035] Trial 184 pruned.

Best trial: 99. Best value: 0.588869:  92%|█████████▎| 185/200 [04:57<00:21,  1.44s/it]

[I 2025-11-10 14:29:01,896] Trial 186 pruned.

Best trial: 99. Best value: 0.588869:  93%|█████████▎| 186/200 [04:57<00:16,  1.19s/it]

[I 2025-11-10 14:29:02,147] Trial 185 pruned.
[I 2025-11-10 14:29:02,198] Trial 187 pruned.

Best trial: 183. Best value: 0.595355:  94%|█████████▍| 188/200 [04:58<00:09,  1.25it/s]

[I 2025-11-10 14:29:02,473] Trial 183 finished with value: 0.5953552330022918 and parameters: {'max_depth': 9, 'learning_rate': 0.06004734140339164, 'n_estimators': 338, 'subsample': 0.824223164919342, 'colsample_bytree': 0.9506392745133562, 'min_child_weight': 1, 'gamma': 1.327361799835039, 'reg_alpha': 0.4255388408388601, 'reg_lambda': 0.030844096456124175, 'max_delta_step': 4}. Best is trial 183 with value: 0.5953552330022918.

Best trial: 183. Best value: 0.595355:  94%|█████████▍| 189/200 [04:59<00:10,  1.04it/s]

[I 2025-11-10 14:29:04,045] Trial 189 pruned.

Best trial: 183. Best value: 0.595355:  95%|█████████▌| 190/200 [05:04<00:19,  1.92s/it]

[I 2025-11-10 14:29:09,128] Trial 190 finished with value: 0.5637738731856379 and parameters: {'max_depth': 7, 'learning_rate': 0.0634089079497947, 'n_estimators': 384, 'subsample': 0.8463866965148701, 'colsample_bytree': 0.9263834027235378, 'min_child_weight': 1, 'gamma': 3.0897802843485938, 'reg_alpha': 0.6647789145957376, 'reg_lambda': 0.010337586031354767, 'max_delta_step': 4}. Best is trial 183 with value: 0.5953552330022918.

Best trial: 183. Best value: 0.595355:  96%|█████████▌| 191/200 [05:05<00:14,  1.60s/it]

[I 2025-11-10 14:29:09,750] Trial 188 finished with value: 0.5716424751718868 and parameters: {'max_depth': 7, 'learning_rate': 0.060644734333692045, 'n_estimators': 340, 'subsample': 0.8445824501613783, 'colsample_bytree': 0.9475858191154458, 'min_child_weight': 1, 'gamma': 1.3212146511316845, 'reg_alpha': 0.042215605290011685, 'reg_lambda': 0.010783163693879199, 'max_delta_step': 4}. Best is trial 183 with value: 0.5953552330022918.

Best trial: 183. Best value: 0.595355:  96%|█████████▌| 192/200 [05:06<00:10,  1.31s/it]

[I 2025-11-10 14:29:10,249] Trial 193 pruned.

Best trial: 183. Best value: 0.595355:  96%|█████████▋| 193/200 [05:07<00:09,  1.29s/it]

[I 2025-11-10 14:29:11,468] Trial 194 pruned.

Best trial: 183. Best value: 0.595355:  97%|█████████▋| 194/200 [05:07<00:06,  1.01s/it]

[I 2025-11-10 14:29:11,788] Trial 191 finished with value: 0.5363177998472116 and parameters: {'max_depth': 9, 'learning_rate': 0.06544142975152682, 'n_estimators': 401, 'subsample': 0.8470520485821553, 'colsample_bytree': 0.932292765870563, 'min_child_weight': 1, 'gamma': 1.0062160249148089, 'reg_alpha': 0.708448822247168, 'reg_lambda': 0.02826818536182475, 'max_delta_step': 4}. Best is trial 183 with value: 0.5953552330022918.

Best trial: 183. Best value: 0.595355:  98%|█████████▊| 195/200 [05:08<00:04,  1.08it/s]

[I 2025-11-10 14:29:12,483] Trial 192 finished with value: 0.5613750954927426 and parameters: {'max_depth': 9, 'learning_rate': 0.0612642154732286, 'n_estimators': 339, 'subsample': 0.8493966534995357, 'colsample_bytree': 0.9229799061864528, 'min_child_weight': 1, 'gamma': 1.1105869019607597, 'reg_alpha': 0.2970823658975108, 'reg_lambda': 0.012224857461811997, 'max_delta_step': 4}. Best is trial 183 with value: 0.5953552330022918.

Best trial: 183. Best value: 0.595355:  98%|█████████▊| 196/200 [05:14<00:10,  2.57s/it]

[I 2025-11-10 14:29:19,078] Trial 195 finished with value: 0.5471734148204737 and parameters: {'max_depth': 9, 'learning_rate': 0.06272189839957852, 'n_estimators': 342, 'subsample': 0.8429533109884303, 'colsample_bytree': 0.92189777821438, 'min_child_weight': 1, 'gamma': 1.1403859441367243, 'reg_alpha': 0.4943069973694907, 'reg_lambda': 0.028417182634849384, 'max_delta_step': 4}. Best is trial 183 with value: 0.5953552330022918.

Best trial: 183. Best value: 0.595355:  98%|█████████▊| 197/200 [05:16<00:06,  2.27s/it]

[I 2025-11-10 14:29:20,630] Trial 197 finished with value: 0.5611229946524064 and parameters: {'max_depth': 7, 'learning_rate': 0.06326399130975525, 'n_estimators': 378, 'subsample': 0.8426851487608327, 'colsample_bytree': 0.9395253411747889, 'min_child_weight': 1, 'gamma': 0.8853722112976803, 'reg_alpha': 0.028198997250457686, 'reg_lambda': 0.012205136904947875, 'max_delta_step': 4}. Best is trial 183 with value: 0.5953552330022918.

Best trial: 183. Best value: 0.595355:  99%|█████████▉| 198/200 [05:16<00:03,  1.68s/it]

[I 2025-11-10 14:29:20,899] Trial 196 finished with value: 0.5164858670741024 and parameters: {'max_depth': 7, 'learning_rate': 0.060898640847691844, 'n_estimators': 373, 'subsample': 0.8475195177631278, 'colsample_bytree': 0.9415181009286512, 'min_child_weight': 1, 'gamma': 0.965764688128183, 'reg_alpha': 0.8026793889763633, 'reg_lambda': 0.010787368139393254, 'max_delta_step': 4}. Best is trial 183 with value: 0.5953552330022918.

Best trial: 183. Best value: 0.595355: 100%|█████████▉| 199/200 [05:17<00:01,  1.43s/it]

[I 2025-11-10 14:29:21,745] Trial 198 finished with value: 0.5503819709702062 and parameters: {'max_depth': 9, 'learning_rate': 0.053796556667499745, 'n_estimators': 373, 'subsample': 0.847494149241626, 'colsample_bytree': 0.9446690906609765, 'min_child_weight': 1, 'gamma': 1.1099175716279, 'reg_alpha': 0.02850761802071971, 'reg_lambda': 0.010731120372059087, 'max_delta_step': 4}. Best is trial 183 with value: 0.5953552330022918.

Best trial: 183. Best value: 0.595355: 100%|██████████| 200/200 [05:22<00:00,  1.61s/it]

[I 2025-11-10 14:29:26,991] Trial 199 finished with value: 0.5623300229182583 and parameters: {'max_depth': 9, 'learning_rate': 0.06037582537439807, 'n_estimators': 377, 'subsample': 0.8447495540972131, 'colsample_bytree': 0.9417069497554417, 'min_child_weight': 1, 'gamma': 0.8657723030095805, 'reg_alpha': 0.3318126635958983, 'reg_lambda': 0.011841052987041167, 'max_delta_step': 4}. Best is trial 183 with value: 0.5953552330022918.

[I 2025-11-10 14:29:28,425] A new study created in memory with name: 10_1_balanced_accuracy
Best trial: 1. Best value: 0.485673:   0%|          | 1/200 [00:02<06:56,  2.09s/it]

[I 2025-11-10 14:29:30,515] Trial 1 finished with value: 0.4856725146198831 and parameters: {'max_depth': 4, 'learning_rate': 0.09007312611985153, 'n_estimators': 253, 'subsample': 0.5043517911493333, 'colsample_bytree': 0.6845826989327745, 'min_child_weight': 1, 'gamma': 1.6577346298195912, 'reg_alpha': 2.1683420088693017, 'reg_lambda': 0.0025575658162954027, 'max_delta_step': 5}. Best is trial 1 with value: 0.4856725146198831.

Best trial: 2. Best value: 0.5:   1%|          | 2/200 [00:02<04:02,  1.22s/it]

[I 2025-11-10 14:29:31,123] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.010255190917471322, 'n_estimators': 532, 'subsample': 0.7783444116411633, 'colsample_bytree': 0.9259724082241588, 'min_child_weight': 10, 'gamma': 1.0842432585538964, 'reg_alpha': 0.0005667746099185092, 'reg_lambda': 0.032677299421607756, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▏         | 3/200 [00:03<03:33,  1.09s/it]

[I 2025-11-10 14:29:32,047] Trial 4 finished with value: 0.44988304093567255 and parameters: {'max_depth': 3, 'learning_rate': 0.0458679106310633, 'n_estimators': 316, 'subsample': 0.6979644746225242, 'colsample_bytree': 0.8493623233770062, 'min_child_weight': 4, 'gamma': 4.141584378869516, 'reg_alpha': 0.0007791647745031821, 'reg_lambda': 0.05653304270851414, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▏         | 4/200 [00:03<02:30,  1.30it/s]

[I 2025-11-10 14:29:32,333] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.02220908562661444, 'n_estimators': 871, 'subsample': 0.8720297322812804, 'colsample_bytree': 0.5927468115754417, 'min_child_weight': 9, 'gamma': 4.017645432268254, 'reg_alpha': 0.00014690602817049093, 'reg_lambda': 5.063511732199084e-05, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▎         | 5/200 [00:05<03:32,  1.09s/it]

[I 2025-11-10 14:29:33,964] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.048733517987964846, 'n_estimators': 292, 'subsample': 0.7490820224762107, 'colsample_bytree': 0.8635635604965359, 'min_child_weight': 7, 'gamma': 4.0795214389837655, 'reg_alpha': 0.00012380807262019392, 'reg_lambda': 3.721070338520076e-07, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   4%|▎         | 7/200 [00:06<01:58,  1.63it/s]

[I 2025-11-10 14:29:34,363] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1166811336102587, 'n_estimators': 1341, 'subsample': 0.9269205573580417, 'colsample_bytree': 0.6624310884970515, 'min_child_weight': 10, 'gamma': 3.2450093485455866, 'reg_alpha': 0.00014414597141817445, 'reg_lambda': 0.02741910806970775, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.
[I 2025-11-10 14:29:34,495] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.29143585756053797, 'n_estimators': 723, 'subsample': 0.5247762915331617, 'colsample_bytree': 0.6007098290783717, 'min_child_weight': 8, 'gamma': 2.759955910456468, 'reg_alpha': 0.0005530098080280873, 'reg_lambda': 0.00032133081863437284, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   4%|▍         | 8/200 [00:07<02:40,  1.20it/s]

[I 2025-11-10 14:29:35,811] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.03357020470440804, 'n_estimators': 784, 'subsample': 0.565261965496235, 'colsample_bytree': 0.8058215965740034, 'min_child_weight': 5, 'gamma': 2.8106571739600614, 'reg_alpha': 5.7140216717394135e-08, 'reg_lambda': 2.0291668036525063e-06, 'max_delta_step': 10}. Best is trial 2 with value: 0.5.

Best trial: 9. Best value: 0.537661:   4%|▍         | 9/200 [00:08<02:43,  1.17it/s]

[I 2025-11-10 14:29:36,714] Trial 9 finished with value: 0.5376608187134503 and parameters: {'max_depth': 5, 'learning_rate': 0.018558715080959173, 'n_estimators': 468, 'subsample': 0.9161792013217673, 'colsample_bytree': 0.7066231287541178, 'min_child_weight': 5, 'gamma': 0.41864688896578295, 'reg_alpha': 0.0007217558702916626, 'reg_lambda': 0.003559017451730509, 'max_delta_step': 2}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:   5%|▌         | 10/200 [00:09<03:18,  1.04s/it]

[I 2025-11-10 14:29:38,175] Trial 8 finished with value: 0.5259064327485381 and parameters: {'max_depth': 5, 'learning_rate': 0.14968152111942612, 'n_estimators': 766, 'subsample': 0.6330330071169757, 'colsample_bytree': 0.9481657407025024, 'min_child_weight': 4, 'gamma': 1.040367480665313, 'reg_alpha': 0.0016685752450509368, 'reg_lambda': 0.021239948928269622, 'max_delta_step': 6}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:   6%|▌         | 11/200 [00:11<03:30,  1.11s/it]

[I 2025-11-10 14:29:39,443] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.18143697754844532, 'n_estimators': 1050, 'subsample': 0.8240639342014517, 'colsample_bytree': 0.9699417850747223, 'min_child_weight': 5, 'gamma': 3.8550821673975206, 'reg_alpha': 7.302004564828398e-07, 'reg_lambda': 0.7968419202232403, 'max_delta_step': 7}. Best is trial 9 with value: 0.5376608187134503.
[I 2025-11-10 14:29:39,483] Trial 12 pruned.

Best trial: 9. Best value: 0.537661:   6%|▋         | 13/200 [00:11<02:13,  1.40it/s]

[I 2025-11-10 14:29:39,955] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.14172337254726117, 'n_estimators': 779, 'subsample': 0.5274229313467602, 'colsample_bytree': 0.9675971255952157, 'min_child_weight': 6, 'gamma': 1.6924027735008869, 'reg_alpha': 0.00012329526586183858, 'reg_lambda': 1.774540620378927e-07, 'max_delta_step': 4}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:   7%|▋         | 14/200 [00:12<01:58,  1.57it/s]

[I 2025-11-10 14:29:40,365] Trial 14 pruned.
[I 2025-11-10 14:29:40,457] Trial 15 pruned.

Best trial: 9. Best value: 0.537661:   8%|▊         | 16/200 [00:12<01:32,  2.00it/s]

[I 2025-11-10 14:29:40,982] Trial 16 pruned.

Best trial: 9. Best value: 0.537661:   8%|▊         | 17/200 [00:12<01:21,  2.24it/s]

[I 2025-11-10 14:29:41,244] Trial 17 pruned.

Best trial: 9. Best value: 0.537661:   9%|▉         | 18/200 [00:13<01:39,  1.83it/s]

[I 2025-11-10 14:29:42,103] Trial 13 pruned.

Best trial: 9. Best value: 0.537661:  10%|▉         | 19/200 [00:16<03:49,  1.27s/it]

[I 2025-11-10 14:29:45,413] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.28094135188796165, 'n_estimators': 667, 'subsample': 0.719263069443963, 'colsample_bytree': 0.7890132013180973, 'min_child_weight': 6, 'gamma': 0.9705308741911339, 'reg_alpha': 3.813086380890273e-06, 'reg_lambda': 0.0019586680328611016, 'max_delta_step': 4}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  10%|█         | 20/200 [00:17<02:56,  1.02it/s]

[I 2025-11-10 14:29:45,607] Trial 18 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.06934848610359064, 'n_estimators': 1121, 'subsample': 0.9985019229955117, 'colsample_bytree': 0.5029660834402555, 'min_child_weight': 6, 'gamma': 0.820949311977659, 'reg_alpha': 0.009696806683443492, 'reg_lambda': 3.678397532006986e-05, 'max_delta_step': 2}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  10%|█         | 21/200 [00:17<02:43,  1.09it/s]

[I 2025-11-10 14:29:46,359] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.07852472015645777, 'n_estimators': 1100, 'subsample': 0.9993012207245365, 'colsample_bytree': 0.7783893496885058, 'min_child_weight': 6, 'gamma': 0.8960754057653447, 'reg_alpha': 4.198109060366431e-06, 'reg_lambda': 2.4534805443131525e-05, 'max_delta_step': 3}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  11%|█         | 22/200 [00:18<02:18,  1.29it/s]

[I 2025-11-10 14:29:46,797] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.29019524889331494, 'n_estimators': 1097, 'subsample': 0.7119262770361204, 'colsample_bytree': 0.7915067128515321, 'min_child_weight': 6, 'gamma': 1.0107624087903013, 'reg_alpha': 1.737668146266258e-06, 'reg_lambda': 0.002276064296049196, 'max_delta_step': 4}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  12%|█▏        | 23/200 [00:19<02:51,  1.03it/s]

[I 2025-11-10 14:29:48,240] Trial 25 pruned.

Best trial: 9. Best value: 0.537661:  12%|█▏        | 24/200 [00:22<04:11,  1.43s/it]

[I 2025-11-10 14:29:50,778] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.023056584162186332, 'n_estimators': 980, 'subsample': 0.6128012475664674, 'colsample_bytree': 0.9078516839072263, 'min_child_weight': 7, 'gamma': 4.839541921465347, 'reg_alpha': 6.548030980571243, 'reg_lambda': 0.003997406139237082, 'max_delta_step': 0}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  12%|█▎        | 25/200 [00:22<03:08,  1.07s/it]

[I 2025-11-10 14:29:51,000] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.06979572589992074, 'n_estimators': 1037, 'subsample': 0.6042350985026488, 'colsample_bytree': 0.9100710298495392, 'min_child_weight': 7, 'gamma': 4.940322907200329, 'reg_alpha': 0.00513480601946783, 'reg_lambda': 0.004077118944201395, 'max_delta_step': 0}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  13%|█▎        | 26/200 [00:23<03:12,  1.11s/it]

[I 2025-11-10 14:29:52,182] Trial 27 pruned.

Best trial: 9. Best value: 0.537661:  14%|█▎        | 27/200 [00:24<03:12,  1.11s/it]

[I 2025-11-10 14:29:53,310] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.11583707363587231, 'n_estimators': 1467, 'subsample': 0.9188402088597659, 'colsample_bytree': 0.6800670529208213, 'min_child_weight': 8, 'gamma': 3.172462391575495, 'reg_alpha': 0.006423420925405061, 'reg_lambda': 0.06019677680709741, 'max_delta_step': 4}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  14%|█▍        | 28/200 [00:25<03:04,  1.07s/it]

[I 2025-11-10 14:29:54,290] Trial 29 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10784426318229798, 'n_estimators': 375, 'subsample': 0.9322176850220284, 'colsample_bytree': 0.6383445135583993, 'min_child_weight': 10, 'gamma': 2.1256124344522487, 'reg_alpha': 0.002494128067553734, 'reg_lambda': 0.33365482055298096, 'max_delta_step': 6}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  14%|█▍        | 29/200 [00:27<03:06,  1.09s/it]

[I 2025-11-10 14:29:55,426] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1793579370595997, 'n_estimators': 1454, 'subsample': 0.9271646751764465, 'colsample_bytree': 0.6823582147152637, 'min_child_weight': 10, 'gamma': 3.396186293511689, 'reg_alpha': 2.816602481806357e-05, 'reg_lambda': 0.25706195677829247, 'max_delta_step': 0}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  15%|█▌        | 30/200 [00:28<03:41,  1.30s/it]

[I 2025-11-10 14:29:57,228] Trial 28 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1839167741818821, 'n_estimators': 1299, 'subsample': 0.9266705566541802, 'colsample_bytree': 0.6827275526827774, 'min_child_weight': 10, 'gamma': 2.232954861257524, 'reg_alpha': 1.5456060132742904e-05, 'reg_lambda': 0.16377291437037642, 'max_delta_step': 3}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  16%|█▌        | 31/200 [00:31<04:26,  1.58s/it]

[I 2025-11-10 14:29:59,455] Trial 30 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.18878488273220845, 'n_estimators': 1278, 'subsample': 0.8051776923776172, 'colsample_bytree': 0.6274020405284498, 'min_child_weight': 5, 'gamma': 2.0807763121748604, 'reg_alpha': 2.5350969634120743e-05, 'reg_lambda': 0.31500174314149143, 'max_delta_step': 6}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  16%|█▌        | 32/200 [00:32<03:54,  1.40s/it]

[I 2025-11-10 14:30:00,423] Trial 33 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.09375763681780254, 'n_estimators': 658, 'subsample': 0.8126737563436539, 'colsample_bytree': 0.7328857971791664, 'min_child_weight': 5, 'gamma': 0.5178053928584715, 'reg_alpha': 0.6094489506356947, 'reg_lambda': 0.00038792036443613344, 'max_delta_step': 5}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  16%|█▋        | 33/200 [00:32<03:06,  1.12s/it]

[I 2025-11-10 14:30:00,890] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.17929317430779357, 'n_estimators': 1310, 'subsample': 0.7955612855640481, 'colsample_bytree': 0.7125953993691849, 'min_child_weight': 5, 'gamma': 0.546974855614708, 'reg_alpha': 1.9581983983512862e-05, 'reg_lambda': 0.00029858978742917583, 'max_delta_step': 3}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  17%|█▋        | 34/200 [00:33<02:49,  1.02s/it]

[I 2025-11-10 14:30:01,672] Trial 32 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.09272989480682968, 'n_estimators': 1279, 'subsample': 0.7944848512454356, 'colsample_bytree': 0.7212013183625524, 'min_child_weight': 5, 'gamma': 0.5415976342553099, 'reg_alpha': 1.574230689857528, 'reg_lambda': 0.0004456028033914937, 'max_delta_step': 5}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  18%|█▊        | 37/200 [00:34<01:38,  1.66it/s]

[I 2025-11-10 14:30:02,819] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.01028178299465575, 'n_estimators': 414, 'subsample': 0.7762987449319212, 'colsample_bytree': 0.996858387110256, 'min_child_weight': 9, 'gamma': 1.335781128557291, 'reg_alpha': 0.000579368426213089, 'reg_lambda': 0.014855874253573051, 'max_delta_step': 9}. Best is trial 9 with value: 0.5376608187134503.
[I 2025-11-10 14:30:02,840] Trial 37 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.01858256327809442, 'n_estimators': 211, 'subsample': 0.8714928672985965, 'colsample_bytree': 0.9440162701830412, 'min_child_weight': 9, 'gamma': 1.3496262514121669, 'reg_alpha': 0.0008713531259201993, 'reg_lambda': 0.014589996306535782, 'max_delta_step': 10}. Best is trial 9 with value: 0.5376608187134503.
[I 2025-11-10 14:30:02,965] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.01062655749837777, 'n_estimators': 631, 'subsample': 0.7802453417346676, 'colsample_bytree': 0.9276281890160448, 'min_child_weight': 9, 'gamma': 0.6506973219946866, 'reg_alpha': 0.0009141064546827768, 'reg_lambda': 0.0004475802099803882, 'max_delta_step': 9}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  19%|█▉        | 38/200 [00:34<01:21,  1.99it/s]

[I 2025-11-10 14:30:03,154] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.019367848349297234, 'n_estimators': 382, 'subsample': 0.8690641372406822, 'colsample_bytree': 0.9394695016583754, 'min_child_weight': 9, 'gamma': 1.2877362169443387, 'reg_alpha': 0.0009586932848854953, 'reg_lambda': 0.012505251926257814, 'max_delta_step': 9}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  20%|██        | 40/200 [00:37<02:18,  1.16it/s]

[I 2025-11-10 14:30:06,071] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03693879925518874, 'n_estimators': 630, 'subsample': 0.8738102175173739, 'colsample_bytree': 0.5521404997691857, 'min_child_weight': 8, 'gamma': 1.3557028730463772, 'reg_alpha': 0.0016958624671932264, 'reg_lambda': 0.04659725350455605, 'max_delta_step': 7}. Best is trial 9 with value: 0.5376608187134503.
[I 2025-11-10 14:30:06,214] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.022576736395308526, 'n_estimators': 618, 'subsample': 0.8670460048457718, 'colsample_bytree': 0.9141651106112303, 'min_child_weight': 9, 'gamma': 1.3126158188406611, 'reg_alpha': 0.0011059851564137195, 'reg_lambda': 0.013164928814840942, 'max_delta_step': 10}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  21%|██        | 42/200 [00:38<01:41,  1.56it/s]

[I 2025-11-10 14:30:07,001] Trial 42 pruned.
[I 2025-11-10 14:30:07,141] Trial 43 pruned.
[I 2025-11-10 14:30:07,149] Trial 40 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.027200963634650587, 'n_estimators': 840, 'subsample': 0.8728995829011591, 'colsample_bytree': 0.5509657454158068, 'min_child_weight': 8, 'gamma': 1.3692242412092193, 'reg_alpha': 0.0002462105695370792, 'reg_lambda': 0.04933301783234731, 'max_delta_step': 8}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  22%|██▏       | 44/200 [00:39<01:10,  2.21it/s]

[I 2025-11-10 14:30:07,587] Trial 41 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.05315411259357546, 'n_estimators': 870, 'subsample': 0.6800351750707958, 'colsample_bytree': 0.8653424305675957, 'min_child_weight': 8, 'gamma': 2.5200481830132233, 'reg_alpha': 2.054527090727535e-07, 'reg_lambda': 0.04999600372522181, 'max_delta_step': 8}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  22%|██▎       | 45/200 [00:42<02:56,  1.14s/it]

[I 2025-11-10 14:30:10,858] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.013247649800609542, 'n_estimators': 728, 'subsample': 0.850577239370403, 'colsample_bytree': 0.6030876265945342, 'min_child_weight': 10, 'gamma': 4.4213641904084096, 'reg_alpha': 8.382656965966676e-05, 'reg_lambda': 1.628813668643045e-06, 'max_delta_step': 1}. Best is trial 9 with value: 0.5376608187134503.
[I 2025-11-10 14:30:10,870] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.012843526714724631, 'n_estimators': 757, 'subsample': 0.9588717412826597, 'colsample_bytree': 0.6055850390189641, 'min_child_weight': 10, 'gamma': 4.497345498804087, 'reg_alpha': 6.915087490224162e-08, 'reg_lambda': 0.002100085595461774, 'max_delta_step': 1}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  24%|██▎       | 47/200 [00:42<01:50,  1.38it/s]

[I 2025-11-10 14:30:11,120] Trial 47 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.013367884743733025, 'n_estimators': 724, 'subsample': 0.751417717118773, 'colsample_bytree': 0.5955438086754737, 'min_child_weight': 10, 'gamma': 3.8953503108721326, 'reg_alpha': 5.7064526315782373e-05, 'reg_lambda': 0.000836992779440665, 'max_delta_step': 1}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  24%|██▍       | 49/200 [00:43<01:16,  1.98it/s]

[I 2025-11-10 14:30:11,440] Trial 48 pruned.
[I 2025-11-10 14:30:11,549] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.026999752974608285, 'n_estimators': 914, 'subsample': 0.9639112370189095, 'colsample_bytree': 0.5742841403221984, 'min_child_weight': 10, 'gamma': 4.433806708742302, 'reg_alpha': 0.0002043892257202975, 'reg_lambda': 9.716187947468942e-06, 'max_delta_step': 1}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  25%|██▌       | 50/200 [00:43<01:01,  2.44it/s]

[I 2025-11-10 14:30:11,685] Trial 50 pruned.

Best trial: 9. Best value: 0.537661:  26%|██▌       | 51/200 [00:43<01:06,  2.23it/s]

[I 2025-11-10 14:30:12,240] Trial 49 pruned.

Best trial: 9. Best value: 0.537661:  26%|██▌       | 52/200 [00:45<01:54,  1.30it/s]

[I 2025-11-10 14:30:13,854] Trial 52 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.1425357057597628, 'n_estimators': 472, 'subsample': 0.895606179989048, 'colsample_bytree': 0.6503697079391061, 'min_child_weight': 7, 'gamma': 0.3299182186258802, 'reg_alpha': 0.0213637876572159, 'reg_lambda': 5.6359941612751335e-06, 'max_delta_step': 5}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  26%|██▋       | 53/200 [00:45<01:41,  1.45it/s]

[I 2025-11-10 14:30:14,326] Trial 53 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.13846180656311127, 'n_estimators': 489, 'subsample': 0.8943780396742042, 'colsample_bytree': 0.7621783816147335, 'min_child_weight': 7, 'gamma': 0.313121815462725, 'reg_alpha': 7.990648063654013e-06, 'reg_lambda': 0.0011344439177533225, 'max_delta_step': 2}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  27%|██▋       | 54/200 [00:46<01:30,  1.61it/s]

[I 2025-11-10 14:30:14,788] Trial 54 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.24206217811339711, 'n_estimators': 464, 'subsample': 0.5230322208904895, 'colsample_bytree': 0.621647081480609, 'min_child_weight': 9, 'gamma': 0.28465242970268967, 'reg_alpha': 0.0005400128244628516, 'reg_lambda': 9.839659097446493e-05, 'max_delta_step': 7}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  28%|██▊       | 55/200 [00:47<02:01,  1.19it/s]

[I 2025-11-10 14:30:16,142] Trial 51 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.1439937571575338, 'n_estimators': 924, 'subsample': 0.5157641051486104, 'colsample_bytree': 0.6591817440023613, 'min_child_weight': 7, 'gamma': 3.476068186275974, 'reg_alpha': 0.015064785864235708, 'reg_lambda': 0.11967408835767272, 'max_delta_step': 5}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  28%|██▊       | 56/200 [00:48<02:04,  1.16it/s]

[I 2025-11-10 14:30:17,067] Trial 55 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.24058559510747698, 'n_estimators': 491, 'subsample': 0.5225677466048088, 'colsample_bytree': 0.5758814070786581, 'min_child_weight': 9, 'gamma': 3.047053258374585, 'reg_alpha': 0.0023952704488412633, 'reg_lambda': 6.373569720386445e-05, 'max_delta_step': 7}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  28%|██▊       | 57/200 [00:49<01:55,  1.24it/s]

[I 2025-11-10 14:30:17,736] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.24261114792241054, 'n_estimators': 559, 'subsample': 0.5666944896923829, 'colsample_bytree': 0.7008735381657414, 'min_child_weight': 9, 'gamma': 2.958194349043885, 'reg_alpha': 0.00283437750493677, 'reg_lambda': 1.4804935749314442e-08, 'max_delta_step': 6}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  29%|██▉       | 58/200 [00:50<02:30,  1.06s/it]

[I 2025-11-10 14:30:19,392] Trial 58 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.016055213133322446, 'n_estimators': 546, 'subsample': 0.5763601716128721, 'colsample_bytree': 0.7120603586676839, 'min_child_weight': 8, 'gamma': 2.9401190682032396, 'reg_alpha': 0.0031566960412811105, 'reg_lambda': 0.0065684568231586605, 'max_delta_step': 6}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  30%|██▉       | 59/200 [00:51<02:23,  1.02s/it]

[I 2025-11-10 14:30:20,321] Trial 59 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2419110320984224, 'n_estimators': 568, 'subsample': 0.5825646676773913, 'colsample_bytree': 0.9713039062830544, 'min_child_weight': 8, 'gamma': 1.786731535649118, 'reg_alpha': 0.0001179448693773439, 'reg_lambda': 1.3679546170545513e-08, 'max_delta_step': 4}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  30%|███       | 60/200 [00:52<01:51,  1.25it/s]

[I 2025-11-10 14:30:20,604] Trial 56 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2289253992307234, 'n_estimators': 1190, 'subsample': 0.5112215936938986, 'colsample_bytree': 0.9745513874196116, 'min_child_weight': 9, 'gamma': 2.9710777853921573, 'reg_alpha': 0.0004995768854512668, 'reg_lambda': 0.00012822915670556117, 'max_delta_step': 6}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  30%|███       | 61/200 [00:53<01:53,  1.22it/s]

[I 2025-11-10 14:30:21,471] Trial 61 pruned.
[I 2025-11-10 14:30:21,510] Trial 62 pruned.

Best trial: 9. Best value: 0.537661:  32%|███▏      | 63/200 [00:53<01:11,  1.90it/s]

[I 2025-11-10 14:30:21,837] Trial 63 pruned.

Best trial: 9. Best value: 0.537661:  32%|███▏      | 64/200 [00:54<01:22,  1.65it/s]

[I 2025-11-10 14:30:22,679] Trial 60 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.016535241467275016, 'n_estimators': 985, 'subsample': 0.8287354418336766, 'colsample_bytree': 0.529130903202772, 'min_child_weight': 8, 'gamma': 1.708521172308509, 'reg_alpha': 5.421254485917699e-05, 'reg_lambda': 1.640803951953158, 'max_delta_step': 4}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  32%|███▎      | 65/200 [00:56<02:25,  1.08s/it]

[I 2025-11-10 14:30:25,099] Trial 66 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.0221616437944252, 'n_estimators': 676, 'subsample': 0.5422329431616576, 'colsample_bytree': 0.7580957358862236, 'min_child_weight': 6, 'gamma': 0.7995860313177405, 'reg_alpha': 2.518902611278091e-06, 'reg_lambda': 5.685805735478002e-07, 'max_delta_step': 10}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  33%|███▎      | 66/200 [00:57<02:04,  1.08it/s]

[I 2025-11-10 14:30:25,628] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.031815060545455014, 'n_estimators': 785, 'subsample': 0.5451204035367513, 'colsample_bytree': 0.8878816293703664, 'min_child_weight': 6, 'gamma': 2.327303128698763, 'reg_alpha': 6.950567448385258e-07, 'reg_lambda': 8.22711954062799e-07, 'max_delta_step': 10}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  34%|███▎      | 67/200 [00:58<02:05,  1.06it/s]

[I 2025-11-10 14:30:26,620] Trial 65 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06318904344300923, 'n_estimators': 1014, 'subsample': 0.9467513880460564, 'colsample_bytree': 0.7523015957063296, 'min_child_weight': 6, 'gamma': 2.3458113137754864, 'reg_alpha': 0.18455553290408358, 'reg_lambda': 0.004336046346250155, 'max_delta_step': 10}. Best is trial 9 with value: 0.5376608187134503.
[I 2025-11-10 14:30:26,701] Trial 67 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.05976499945161224, 'n_estimators': 787, 'subsample': 0.5358877469021017, 'colsample_bytree': 0.9562925080602506, 'min_child_weight': 5, 'gamma': 3.1859423032786562, 'reg_alpha': 0.14980714765302675, 'reg_lambda': 1.2866445763751215e-06, 'max_delta_step': 10}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  34%|███▍      | 69/200 [00:58<01:21,  1.62it/s]

[I 2025-11-10 14:30:27,038] Trial 69 pruned.

Best trial: 9. Best value: 0.537661:  35%|███▌      | 70/200 [01:01<02:21,  1.09s/it]

[I 2025-11-10 14:30:29,589] Trial 68 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06209251758281559, 'n_estimators': 782, 'subsample': 0.6025270667699825, 'colsample_bytree': 0.6956256831496976, 'min_child_weight': 5, 'gamma': 2.3140545369377046, 'reg_alpha': 8.584000994539863e-07, 'reg_lambda': 0.025405414647062363, 'max_delta_step': 9}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  36%|███▌      | 71/200 [01:01<02:04,  1.03it/s]

[I 2025-11-10 14:30:30,210] Trial 72 finished with value: 0.49333333333333335 and parameters: {'max_depth': 4, 'learning_rate': 0.011637959951622498, 'n_estimators': 595, 'subsample': 0.5984662840317019, 'colsample_bytree': 0.8835459395529361, 'min_child_weight': 4, 'gamma': 4.224110309264255, 'reg_alpha': 1.1185665485850373e-05, 'reg_lambda': 0.0002129012294332334, 'max_delta_step': 9}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  36%|███▌      | 72/200 [01:02<01:44,  1.22it/s]

[I 2025-11-10 14:30:30,636] Trial 70 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07880970354316377, 'n_estimators': 802, 'subsample': 0.5985099019103486, 'colsample_bytree': 0.5755067817110288, 'min_child_weight': 5, 'gamma': 2.0176325418752312, 'reg_alpha': 0.006847024679815746, 'reg_lambda': 0.5039782302483767, 'max_delta_step': 9}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  36%|███▋      | 73/200 [01:03<01:44,  1.22it/s]

[I 2025-11-10 14:30:31,447] Trial 73 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.011456995895009545, 'n_estimators': 356, 'subsample': 0.6896571154986464, 'colsample_bytree': 0.894645913142618, 'min_child_weight': 10, 'gamma': 2.731806318307205, 'reg_alpha': 1.1312725982833775e-05, 'reg_lambda': 2.6728167990656846e-07, 'max_delta_step': 3}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  37%|███▋      | 74/200 [01:03<01:33,  1.35it/s]

[I 2025-11-10 14:30:31,987] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.0448816383168672, 'n_estimators': 258, 'subsample': 0.7100694634101712, 'colsample_bytree': 0.9006073623925065, 'min_child_weight': 10, 'gamma': 4.71177272624169, 'reg_alpha': 0.00014069281783129182, 'reg_lambda': 1.1513327506514841e-07, 'max_delta_step': 2}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  38%|███▊      | 75/200 [01:03<01:21,  1.54it/s]

[I 2025-11-10 14:30:32,360] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.08095903149601033, 'n_estimators': 420, 'subsample': 0.689716884229722, 'colsample_bytree': 0.7781734716661524, 'min_child_weight': 10, 'gamma': 4.055303795745226, 'reg_alpha': 0.00011391591413656036, 'reg_lambda': 3.6341279723487136e-07, 'max_delta_step': 8}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  38%|███▊      | 76/200 [01:05<01:35,  1.29it/s]

[I 2025-11-10 14:30:33,489] Trial 71 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.08286169268478513, 'n_estimators': 1398, 'subsample': 0.5016011025873202, 'colsample_bytree': 0.8038778266787139, 'min_child_weight': 5, 'gamma': 1.9450524791803154, 'reg_alpha': 0.007592748512863292, 'reg_lambda': 0.00021039884635693743, 'max_delta_step': 3}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  38%|███▊      | 77/200 [01:06<02:06,  1.03s/it]

[I 2025-11-10 14:30:35,133] Trial 76 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.10377675922785183, 'n_estimators': 734, 'subsample': 0.6321920366633664, 'colsample_bytree': 0.8514489800735899, 'min_child_weight': 10, 'gamma': 4.202640509459098, 'reg_alpha': 0.00014156327571262855, 'reg_lambda': 0.08963351980915528, 'max_delta_step': 6}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  39%|███▉      | 78/200 [01:07<01:50,  1.10it/s]

[I 2025-11-10 14:30:35,756] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03434164719049734, 'n_estimators': 684, 'subsample': 0.9000930514139536, 'colsample_bytree': 0.928534183666774, 'min_child_weight': 7, 'gamma': 4.044677920939055, 'reg_alpha': 0.0014531735686815947, 'reg_lambda': 2.678679319872648e-06, 'max_delta_step': 8}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  40%|███▉      | 79/200 [01:08<01:41,  1.19it/s]

[I 2025-11-10 14:30:36,425] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.019609038391633214, 'n_estimators': 689, 'subsample': 0.5010684160711081, 'colsample_bytree': 0.930424354310851, 'min_child_weight': 4, 'gamma': 3.985501219847627, 'reg_alpha': 0.000440012926233518, 'reg_lambda': 0.025582130281747235, 'max_delta_step': 6}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  40%|████      | 80/200 [01:08<01:31,  1.31it/s]

[I 2025-11-10 14:30:37,011] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.10866946732305721, 'n_estimators': 678, 'subsample': 0.6393207238653037, 'colsample_bytree': 0.9271315592460813, 'min_child_weight': 7, 'gamma': 2.5824469935160863, 'reg_alpha': 0.001398624294827551, 'reg_lambda': 2.7192090746935445e-06, 'max_delta_step': 6}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  40%|████      | 81/200 [01:09<01:29,  1.33it/s]

[I 2025-11-10 14:30:37,752] Trial 82 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02452274005183118, 'n_estimators': 232, 'subsample': 0.7390529267766413, 'colsample_bytree': 0.8442843595647704, 'min_child_weight': 9, 'gamma': 3.6289090847136336, 'reg_alpha': 0.0003169480103737618, 'reg_lambda': 2.53876558269733e-05, 'max_delta_step': 7}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  41%|████      | 82/200 [01:11<02:12,  1.12s/it]

[I 2025-11-10 14:30:39,729] Trial 80 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02618344896097755, 'n_estimators': 879, 'subsample': 0.9030607354126573, 'colsample_bytree': 0.9237834447619503, 'min_child_weight': 9, 'gamma': 1.560698170561603, 'reg_alpha': 0.0003779262997959784, 'reg_lambda': 2.408802152366192e-06, 'max_delta_step': 7}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  42%|████▏     | 83/200 [01:12<02:29,  1.28s/it]

[I 2025-11-10 14:30:41,384] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.024083689362072936, 'n_estimators': 889, 'subsample': 0.7474168019601718, 'colsample_bytree': 0.7343889901443833, 'min_child_weight': 9, 'gamma': 1.5568530855140172, 'reg_alpha': 2.137008434524415e-08, 'reg_lambda': 3.654103974167225e-08, 'max_delta_step': 7}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  42%|████▏     | 84/200 [01:13<01:59,  1.03s/it]

[I 2025-11-10 14:30:41,834] Trial 81 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02664199438604438, 'n_estimators': 1069, 'subsample': 0.7378356708558973, 'colsample_bytree': 0.8507936111934566, 'min_child_weight': 9, 'gamma': 1.5837474102198468, 'reg_alpha': 0.0003926512514165104, 'reg_lambda': 0.026355578833898274, 'max_delta_step': 7}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  42%|████▎     | 85/200 [01:13<01:33,  1.23it/s]

[I 2025-11-10 14:30:42,135] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.2937957760916187, 'n_estimators': 429, 'subsample': 0.8535626539310511, 'colsample_bytree': 0.9516054000135216, 'min_child_weight': 6, 'gamma': 3.7634284867191212, 'reg_alpha': 1.2574666830527605e-08, 'reg_lambda': 0.20877818728251948, 'max_delta_step': 7}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  43%|████▎     | 86/200 [01:13<01:14,  1.53it/s]

[I 2025-11-10 14:30:42,408] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1602005533362621, 'n_estimators': 838, 'subsample': 0.8137976183139631, 'colsample_bytree': 0.9568860906626662, 'min_child_weight': 6, 'gamma': 4.297614337935287, 'reg_alpha': 4.937774679259208e-08, 'reg_lambda': 8.509123482820383e-08, 'max_delta_step': 7}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  44%|████▎     | 87/200 [01:15<01:54,  1.01s/it]

[I 2025-11-10 14:30:44,270] Trial 87 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.2768326868792722, 'n_estimators': 432, 'subsample': 0.855807995751951, 'colsample_bytree': 0.9904382729030061, 'min_child_weight': 6, 'gamma': 0.7074382499992684, 'reg_alpha': 1.0514453906148698e-07, 'reg_lambda': 0.00980424058329939, 'max_delta_step': 5}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  44%|████▍     | 88/200 [01:17<02:19,  1.25s/it]

[I 2025-11-10 14:30:46,028] Trial 89 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.20256707271734903, 'n_estimators': 708, 'subsample': 0.7770145025096274, 'colsample_bytree': 0.6676718363555291, 'min_child_weight': 5, 'gamma': 3.4143062531561537, 'reg_alpha': 4.435496440196589e-07, 'reg_lambda': 0.0009202930135280155, 'max_delta_step': 2}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  44%|████▍     | 89/200 [01:18<02:17,  1.23s/it]

[I 2025-11-10 14:30:47,272] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.29500929354804556, 'n_estimators': 1079, 'subsample': 0.8166081198362557, 'colsample_bytree': 0.9900418888479267, 'min_child_weight': 6, 'gamma': 3.688880825678779, 'reg_alpha': 6.144025452086015e-08, 'reg_lambda': 0.02636849855344323, 'max_delta_step': 5}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  45%|████▌     | 90/200 [01:19<02:02,  1.11s/it]

[I 2025-11-10 14:30:48,100] Trial 92 pruned.

Best trial: 9. Best value: 0.537661:  46%|████▌     | 91/200 [01:20<02:00,  1.10s/it]

[I 2025-11-10 14:30:49,191] Trial 91 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.04806043233119688, 'n_estimators': 600, 'subsample': 0.5602649730750451, 'colsample_bytree': 0.6376686949807704, 'min_child_weight': 4, 'gamma': 2.8756092963624367, 'reg_alpha': 0.000948386122193028, 'reg_lambda': 6.418699582113453, 'max_delta_step': 8}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  46%|████▌     | 92/200 [01:21<01:45,  1.02it/s]

[I 2025-11-10 14:30:49,872] Trial 93 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04903154068637394, 'n_estimators': 337, 'subsample': 0.7945992222305355, 'colsample_bytree': 0.5890193718718583, 'min_child_weight': 8, 'gamma': 2.8539958687396445, 'reg_alpha': 2.327826834881235e-07, 'reg_lambda': 0.0005712537029710774, 'max_delta_step': 8}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  46%|████▋     | 93/200 [01:21<01:26,  1.24it/s]

[I 2025-11-10 14:30:50,279] Trial 90 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.20479862754142575, 'n_estimators': 1135, 'subsample': 0.7719025465770942, 'colsample_bytree': 0.6678004131850256, 'min_child_weight': 5, 'gamma': 1.0793955819510912, 'reg_alpha': 2.6258353112088363e-07, 'reg_lambda': 0.002437008391757258, 'max_delta_step': 2}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  47%|████▋     | 94/200 [01:22<01:11,  1.49it/s]

[I 2025-11-10 14:30:50,631] Trial 88 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1649476483992813, 'n_estimators': 1493, 'subsample': 0.7708660438019052, 'colsample_bytree': 0.9845935549163698, 'min_child_weight': 5, 'gamma': 3.360238034993764, 'reg_alpha': 2.7534216767609275e-07, 'reg_lambda': 4.9870510207775146e-05, 'max_delta_step': 5}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  48%|████▊     | 95/200 [01:22<01:07,  1.55it/s]

[I 2025-11-10 14:30:51,212] Trial 95 pruned.

Best trial: 9. Best value: 0.537661:  48%|████▊     | 96/200 [01:23<00:56,  1.84it/s]

[I 2025-11-10 14:30:51,482] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.17012825752675556, 'n_estimators': 346, 'subsample': 0.7948734885230864, 'colsample_bytree': 0.969452059884683, 'min_child_weight': 5, 'gamma': 1.2145228744212822, 'reg_alpha': 2.6121058357214436e-05, 'reg_lambda': 1.2210899481412493e-07, 'max_delta_step': 4}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  48%|████▊     | 97/200 [01:25<01:50,  1.08s/it]

[I 2025-11-10 14:30:53,836] Trial 98 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.11516129217361154, 'n_estimators': 519, 'subsample': 0.5265866778242101, 'colsample_bytree': 0.5604930748029717, 'min_child_weight': 8, 'gamma': 0.013983781810945173, 'reg_alpha': 4.859151923593171e-06, 'reg_lambda': 8.936894088201106e-06, 'max_delta_step': 6}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  49%|████▉     | 98/200 [01:25<01:34,  1.08it/s]

[I 2025-11-10 14:30:54,406] Trial 99 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.04035113487293561, 'n_estimators': 517, 'subsample': 0.5311064329080121, 'colsample_bytree': 0.9411077064927933, 'min_child_weight': 7, 'gamma': 0.4529796992402568, 'reg_alpha': 5.229256566563557e-06, 'reg_lambda': 4.871337576775157e-07, 'max_delta_step': 6}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  50%|████▉     | 99/200 [01:26<01:27,  1.15it/s]

[I 2025-11-10 14:30:55,157] Trial 97 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.04239147455995984, 'n_estimators': 851, 'subsample': 0.9231298830482378, 'colsample_bytree': 0.9687146283680289, 'min_child_weight': 7, 'gamma': 0.4500544229607655, 'reg_alpha': 3.1507223281690265e-05, 'reg_lambda': 0.08836149945131458, 'max_delta_step': 3}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  50%|█████     | 100/200 [01:27<01:17,  1.29it/s]

[I 2025-11-10 14:30:55,693] Trial 101 pruned.

Best trial: 9. Best value: 0.537661:  50%|█████     | 101/200 [01:28<01:38,  1.01it/s]

[I 2025-11-10 14:30:57,192] Trial 100 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.04234122640985791, 'n_estimators': 645, 'subsample': 0.5846717489454863, 'colsample_bytree': 0.9403870274281491, 'min_child_weight': 7, 'gamma': 3.1013127853782336, 'reg_alpha': 0.0042296067002781075, 'reg_lambda': 3.83118158092308e-08, 'max_delta_step': 3}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  51%|█████     | 102/200 [01:29<01:41,  1.04s/it]

[I 2025-11-10 14:30:58,335] Trial 96 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.16310835325967155, 'n_estimators': 1493, 'subsample': 0.9180108519510308, 'colsample_bytree': 0.9090119820305913, 'min_child_weight': 7, 'gamma': 0.16613536204671142, 'reg_alpha': 0.00017377861430380135, 'reg_lambda': 1.5791460363119144e-07, 'max_delta_step': 4}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  52%|█████▏    | 103/200 [01:31<02:00,  1.25s/it]

[I 2025-11-10 14:31:00,076] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0709005071104252, 'n_estimators': 800, 'subsample': 0.9771723858874969, 'colsample_bytree': 0.9122223288567091, 'min_child_weight': 10, 'gamma': 4.593164605330797, 'reg_alpha': 0.004114817305229568, 'reg_lambda': 1.4801790800883379e-05, 'max_delta_step': 0}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  52%|█████▏    | 104/200 [01:31<01:33,  1.03it/s]

[I 2025-11-10 14:31:00,388] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.020691012869178432, 'n_estimators': 929, 'subsample': 0.8866107790105618, 'colsample_bytree': 0.9987062937618172, 'min_child_weight': 10, 'gamma': 0.8680587617209031, 'reg_alpha': 0.002339648065365643, 'reg_lambda': 3.317762711462414e-08, 'max_delta_step': 3}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  52%|█████▎    | 105/200 [01:34<02:09,  1.36s/it]

[I 2025-11-10 14:31:02,677] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.12697864801691025, 'n_estimators': 812, 'subsample': 0.9807580485284163, 'colsample_bytree': 0.5429191546795169, 'min_child_weight': 6, 'gamma': 0.7973951045998808, 'reg_alpha': 0.002060312606081226, 'reg_lambda': 5.1911068855016955e-05, 'max_delta_step': 0}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  53%|█████▎    | 106/200 [01:35<02:02,  1.30s/it]

[I 2025-11-10 14:31:03,827] Trial 104 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.08892115703099743, 'n_estimators': 1265, 'subsample': 0.965998965857172, 'colsample_bytree': 0.5408763547343254, 'min_child_weight': 6, 'gamma': 0.13947996128017515, 'reg_alpha': 0.04913927874026757, 'reg_lambda': 4.817098533248923e-05, 'max_delta_step': 0}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  54%|█████▎    | 107/200 [01:36<01:49,  1.18s/it]

[I 2025-11-10 14:31:04,724] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.034945627667336096, 'n_estimators': 908, 'subsample': 0.9920064030501741, 'colsample_bytree': 0.5058575675226286, 'min_child_weight': 6, 'gamma': 0.7961331822466173, 'reg_alpha': 0.0008640055876545109, 'reg_lambda': 4.6677846654911524e-05, 'max_delta_step': 5}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  54%|█████▍    | 108/200 [01:38<02:11,  1.43s/it]

[I 2025-11-10 14:31:06,726] Trial 107 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.09938579869700703, 'n_estimators': 1327, 'subsample': 0.9690832697896119, 'colsample_bytree': 0.5325819688212846, 'min_child_weight': 6, 'gamma': 0.8006526895504101, 'reg_alpha': 0.06657582683421741, 'reg_lambda': 4.3522145598712246e-05, 'max_delta_step': 5}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  55%|█████▍    | 109/200 [01:39<01:55,  1.27s/it]

[I 2025-11-10 14:31:07,636] Trial 111 pruned.

Best trial: 9. Best value: 0.537661:  55%|█████▌    | 110/200 [01:40<01:50,  1.23s/it]

[I 2025-11-10 14:31:08,787] Trial 108 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.014304329848783463, 'n_estimators': 1242, 'subsample': 0.6178246442956997, 'colsample_bytree': 0.7725715623057801, 'min_child_weight': 6, 'gamma': 0.5996555206280627, 'reg_alpha': 0.009631324666439477, 'reg_lambda': 0.007395535279547256, 'max_delta_step': 1}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  56%|█████▌    | 111/200 [01:41<01:40,  1.13s/it]

[I 2025-11-10 14:31:09,677] Trial 109 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.033227873047466785, 'n_estimators': 1244, 'subsample': 0.9983254718254926, 'colsample_bytree': 0.7207772346877328, 'min_child_weight': 8, 'gamma': 4.346457878688025, 'reg_alpha': 0.010835880745140853, 'reg_lambda': 4.576479622531959e-06, 'max_delta_step': 2}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  56%|█████▌    | 112/200 [01:41<01:27,  1.01it/s]

[I 2025-11-10 14:31:10,344] Trial 110 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.014776399353845043, 'n_estimators': 1031, 'subsample': 0.5538565031988155, 'colsample_bytree': 0.8751157115121517, 'min_child_weight': 5, 'gamma': 0.6360847189901482, 'reg_alpha': 9.724452422329965e-05, 'reg_lambda': 8.36059155872995e-07, 'max_delta_step': 1}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  56%|█████▋    | 113/200 [01:42<01:09,  1.25it/s]

[I 2025-11-10 14:31:10,700] Trial 114 pruned.

Best trial: 9. Best value: 0.537661:  57%|█████▋    | 114/200 [01:44<01:49,  1.27s/it]

[I 2025-11-10 14:31:13,071] Trial 112 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.14844861866565556, 'n_estimators': 1129, 'subsample': 0.616959299727655, 'colsample_bytree': 0.5155989908154199, 'min_child_weight': 8, 'gamma': 3.8786079273605614, 'reg_alpha': 0.010302573955245618, 'reg_lambda': 5.2375871983774175e-06, 'max_delta_step': 2}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  57%|█████▊    | 115/200 [01:46<01:51,  1.32s/it]

[I 2025-11-10 14:31:14,488] Trial 117 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.13447986113611515, 'n_estimators': 279, 'subsample': 0.5166367820529343, 'colsample_bytree': 0.7368680933193421, 'min_child_weight': 6, 'gamma': 3.4964067190872883, 'reg_alpha': 1.3614545065611076e-06, 'reg_lambda': 0.01817752328494411, 'max_delta_step': 4}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  58%|█████▊    | 116/200 [01:46<01:22,  1.02it/s]

[I 2025-11-10 14:31:14,688] Trial 113 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.014970227234631097, 'n_estimators': 1043, 'subsample': 0.758942205663971, 'colsample_bytree': 0.6980195357568879, 'min_child_weight': 4, 'gamma': 4.311076163418256, 'reg_alpha': 0.0007011101100427542, 'reg_lambda': 3.6282287725022013, 'max_delta_step': 2}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  58%|█████▊    | 117/200 [01:47<01:25,  1.03s/it]

[I 2025-11-10 14:31:15,828] Trial 115 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1494941582447708, 'n_estimators': 1066, 'subsample': 0.5121961634913277, 'colsample_bytree': 0.51435011251571, 'min_child_weight': 5, 'gamma': 3.833752006021338, 'reg_alpha': 0.00027441273109840743, 'reg_lambda': 2.559673168470268e-05, 'max_delta_step': 4}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  59%|█████▉    | 118/200 [01:48<01:14,  1.11it/s]

[I 2025-11-10 14:31:16,450] Trial 116 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.18628144645677705, 'n_estimators': 1119, 'subsample': 0.841081996533685, 'colsample_bytree': 0.805219157738522, 'min_child_weight': 6, 'gamma': 2.574982182486037, 'reg_alpha': 2.813428340450378e-06, 'reg_lambda': 2.428355362282354e-05, 'max_delta_step': 4}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  60%|█████▉    | 119/200 [01:48<01:04,  1.26it/s]

[I 2025-11-10 14:31:16,989] Trial 120 pruned.

Best trial: 9. Best value: 0.537661:  60%|██████    | 120/200 [01:49<01:01,  1.31it/s]

[I 2025-11-10 14:31:17,684] Trial 121 pruned.

Best trial: 9. Best value: 0.537661:  60%|██████    | 121/200 [01:51<01:35,  1.21s/it]

[I 2025-11-10 14:31:19,926] Trial 123 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.055552228642924306, 'n_estimators': 381, 'subsample': 0.8062948716511621, 'colsample_bytree': 0.7478272790900063, 'min_child_weight': 7, 'gamma': 3.263552749866103, 'reg_alpha': 0.00020689135216964667, 'reg_lambda': 0.03505821799405868, 'max_delta_step': 9}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 9. Best value: 0.537661:  61%|██████    | 122/200 [01:52<01:24,  1.09s/it]

[I 2025-11-10 14:31:20,725] Trial 119 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.181714977172669, 'n_estimators': 1099, 'subsample': 0.8802819362983041, 'colsample_bytree': 0.7981670150753233, 'min_child_weight': 6, 'gamma': 2.6501990039362244, 'reg_alpha': 2.705991380693853e-06, 'reg_lambda': 2.779287493147103e-05, 'max_delta_step': 4}. Best is trial 9 with value: 0.5376608187134503.

Best trial: 118. Best value: 0.572047:  62%|██████▏   | 123/200 [01:52<01:06,  1.15it/s]

[I 2025-11-10 14:31:21,079] Trial 122 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.05765077511406301, 'n_estimators': 711, 'subsample': 0.8247664327691746, 'colsample_bytree': 0.74507333904573, 'min_child_weight': 10, 'gamma': 2.1884370996830746, 'reg_alpha': 2.4791716902693917e-08, 'reg_lambda': 0.00021069538360248458, 'max_delta_step': 9}. Best is trial 9 with value: 0.5376608187134503.
[I 2025-11-10 14:31:21,085] Trial 118 finished with value: 0.572046783625731 and parameters: {'max_depth': 3, 'learning_rate': 0.11848221161961525, 'n_estimators': 1192, 'subsample': 0.8407247053502654, 'colsample_bytree': 0.7907866490897522, 'min_child_weight': 4, 'gamma': 2.662981596978313, 'reg_alpha': 0.00028133898328325805, 'reg_lambda': 2.682364384965733e-05, 'max_delta_step': 4}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  62%|██████▎   | 125/200 [01:53<00:56,  1.33it/s]

[I 2025-11-10 14:31:22,323] Trial 127 pruned.
[I 2025-11-10 14:31:22,348] Trial 126 pruned.

Best trial: 118. Best value: 0.572047:  64%|██████▎   | 127/200 [01:55<00:55,  1.32it/s]

[I 2025-11-10 14:31:23,851] Trial 129 pruned.

Best trial: 118. Best value: 0.572047:  64%|██████▍   | 128/200 [01:55<00:48,  1.49it/s]

[I 2025-11-10 14:31:24,211] Trial 128 pruned.

Best trial: 118. Best value: 0.572047:  64%|██████▍   | 129/200 [01:56<00:54,  1.31it/s]

[I 2025-11-10 14:31:25,263] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.2701733776670831, 'n_estimators': 985, 'subsample': 0.6613033065931645, 'colsample_bytree': 0.7707315295497805, 'min_child_weight': 6, 'gamma': 0.9900063574517856, 'reg_alpha': 4.416886537278405e-07, 'reg_lambda': 0.0007521287909106276, 'max_delta_step': 5}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  65%|██████▌   | 130/200 [01:57<00:55,  1.27it/s]

[I 2025-11-10 14:31:26,124] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.2784449512234166, 'n_estimators': 972, 'subsample': 0.7045734664573253, 'colsample_bytree': 0.5868547198838548, 'min_child_weight': 6, 'gamma': 1.4662530296786662, 'reg_alpha': 5.047482517486262e-07, 'reg_lambda': 0.0005434385108385599, 'max_delta_step': 5}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  66%|██████▌   | 131/200 [02:00<01:38,  1.43s/it]

[I 2025-11-10 14:31:29,340] Trial 130 finished with value: 0.4515204678362574 and parameters: {'max_depth': 7, 'learning_rate': 0.2673886293070992, 'n_estimators': 993, 'subsample': 0.5709018042014797, 'colsample_bytree': 0.9491868649886167, 'min_child_weight': 3, 'gamma': 4.042567194915604, 'reg_alpha': 0.0006688956715148252, 'reg_lambda': 0.0033529540598536646, 'max_delta_step': 4}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  66%|██████▌   | 132/200 [02:01<01:15,  1.12s/it]

[I 2025-11-10 14:31:29,617] Trial 132 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.06524949620451731, 'n_estimators': 778, 'subsample': 0.8478851809009976, 'colsample_bytree': 0.6806490452174053, 'min_child_weight': 5, 'gamma': 3.972666207016632, 'reg_alpha': 1.0474246279382722e-07, 'reg_lambda': 0.003427600109117998, 'max_delta_step': 4}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  66%|██████▋   | 133/200 [02:01<01:07,  1.01s/it]

[I 2025-11-10 14:31:30,348] Trial 133 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.0773931060978082, 'n_estimators': 824, 'subsample': 0.9068413449564593, 'colsample_bytree': 0.6771425682353225, 'min_child_weight': 9, 'gamma': 2.3793720323418297, 'reg_alpha': 1.3900482988571586e-07, 'reg_lambda': 1.7033653638737843e-05, 'max_delta_step': 4}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  67%|██████▋   | 134/200 [02:03<01:09,  1.05s/it]

[I 2025-11-10 14:31:31,518] Trial 131 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.012198115033468683, 'n_estimators': 1450, 'subsample': 0.6611084297288857, 'colsample_bytree': 0.5619087826172828, 'min_child_weight': 9, 'gamma': 4.138665184866394, 'reg_alpha': 0.0006398106292186995, 'reg_lambda': 1.4797266555160478e-05, 'max_delta_step': 4}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  68%|██████▊   | 135/200 [02:05<01:31,  1.41s/it]

[I 2025-11-10 14:31:33,800] Trial 135 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.10876003557775403, 'n_estimators': 761, 'subsample': 0.90748740671678, 'colsample_bytree': 0.7864105266979816, 'min_child_weight': 7, 'gamma': 2.415195990441487, 'reg_alpha': 1.2867767218596671e-06, 'reg_lambda': 0.006859991004173165, 'max_delta_step': 4}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  68%|██████▊   | 136/200 [02:07<01:42,  1.60s/it]

[I 2025-11-10 14:31:35,855] Trial 137 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.21712118236416533, 'n_estimators': 862, 'subsample': 0.7186777384587514, 'colsample_bytree': 0.78329908058319, 'min_child_weight': 7, 'gamma': 1.2073997184923895, 'reg_alpha': 0.0001430059217746626, 'reg_lambda': 0.06697477488055018, 'max_delta_step': 3}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  68%|██████▊   | 137/200 [02:07<01:21,  1.29s/it]

[I 2025-11-10 14:31:36,406] Trial 134 finished with value: 0.49000000000000005 and parameters: {'max_depth': 5, 'learning_rate': 0.10955699057772558, 'n_estimators': 1432, 'subsample': 0.8521957290609135, 'colsample_bytree': 0.7811740110696552, 'min_child_weight': 5, 'gamma': 3.0176649301345786, 'reg_alpha': 1.4783134550243235e-06, 'reg_lambda': 0.01115983671808108, 'max_delta_step': 4}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  69%|██████▉   | 138/200 [02:08<01:11,  1.16s/it]

[I 2025-11-10 14:31:37,250] Trial 136 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.09983644502135361, 'n_estimators': 1428, 'subsample': 0.543710042112805, 'colsample_bytree': 0.788673471481084, 'min_child_weight': 7, 'gamma': 1.2489338278604638, 'reg_alpha': 1.2408209398685502e-06, 'reg_lambda': 0.05059574223270058, 'max_delta_step': 3}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  70%|██████▉   | 139/200 [02:11<01:36,  1.58s/it]

[I 2025-11-10 14:31:39,824] Trial 138 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10020539487033968, 'n_estimators': 1174, 'subsample': 0.78757383886273, 'colsample_bytree': 0.7267041738736836, 'min_child_weight': 5, 'gamma': 1.2724718562350121, 'reg_alpha': 0.00017995495198933512, 'reg_lambda': 0.0003328224651450687, 'max_delta_step': 10}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  70%|███████   | 140/200 [02:12<01:29,  1.50s/it]

[I 2025-11-10 14:31:41,134] Trial 139 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.010110153337550677, 'n_estimators': 1093, 'subsample': 0.5396591895258063, 'colsample_bytree': 0.794372856359742, 'min_child_weight': 5, 'gamma': 3.0020875390721855, 'reg_alpha': 6.434028545945712e-05, 'reg_lambda': 0.15477040179751517, 'max_delta_step': 10}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  70%|███████   | 141/200 [02:13<01:18,  1.33s/it]

[I 2025-11-10 14:31:42,062] Trial 140 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.010206790153512753, 'n_estimators': 1093, 'subsample': 0.7869739025845791, 'colsample_bytree': 0.8345475525151034, 'min_child_weight': 10, 'gamma': 2.688110079865714, 'reg_alpha': 0.00032853179716275027, 'reg_lambda': 1.9457096098671145e-07, 'max_delta_step': 10}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  71%|███████   | 142/200 [02:15<01:17,  1.34s/it]

[I 2025-11-10 14:31:43,421] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.25212660704118406, 'n_estimators': 1173, 'subsample': 0.7615483507336911, 'colsample_bytree': 0.8394313289967341, 'min_child_weight': 10, 'gamma': 2.678098779789393, 'reg_alpha': 6.581534613904358, 'reg_lambda': 0.0003524534079352446, 'max_delta_step': 10}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  72%|███████▏  | 143/200 [02:16<01:22,  1.46s/it]

[I 2025-11-10 14:31:45,158] Trial 142 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2574583870805069, 'n_estimators': 1079, 'subsample': 0.7583967878804262, 'colsample_bytree': 0.7133120986778161, 'min_child_weight': 10, 'gamma': 0.3638051023075781, 'reg_alpha': 7.418047333257228, 'reg_lambda': 0.17733961620030939, 'max_delta_step': 7}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  72%|███████▏  | 144/200 [02:17<01:04,  1.15s/it]

[I 2025-11-10 14:31:45,606] Trial 144 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.25439091239454337, 'n_estimators': 656, 'subsample': 0.765198626604168, 'colsample_bytree': 0.9773190186760878, 'min_child_weight': 6, 'gamma': 1.0559791942040628, 'reg_alpha': 8.830644859144007e-06, 'reg_lambda': 0.004819727264190472, 'max_delta_step': 4}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  72%|███████▎  | 145/200 [02:18<00:58,  1.07s/it]

[I 2025-11-10 14:31:46,468] Trial 145 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.13412048594090523, 'n_estimators': 573, 'subsample': 0.9856462750950163, 'colsample_bytree': 0.8136584511068524, 'min_child_weight': 6, 'gamma': 1.0374659721882096, 'reg_alpha': 1.8497337516114773e-06, 'reg_lambda': 0.004546299257542812, 'max_delta_step': 7}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  73%|███████▎  | 146/200 [02:18<00:44,  1.23it/s]

[I 2025-11-10 14:31:46,693] Trial 143 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.13153199438983781, 'n_estimators': 1051, 'subsample': 0.7619923962525496, 'colsample_bytree': 0.9785404819790738, 'min_child_weight': 10, 'gamma': 0.29276531178277776, 'reg_alpha': 0.0003050442136623525, 'reg_lambda': 1.3396391876463617e-06, 'max_delta_step': 1}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  74%|███████▎  | 147/200 [02:20<00:58,  1.10s/it]

[I 2025-11-10 14:31:48,472] Trial 146 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.051814569431155304, 'n_estimators': 663, 'subsample': 0.9903373414231523, 'colsample_bytree': 0.8082205809442354, 'min_child_weight': 6, 'gamma': 1.0899081468276761, 'reg_alpha': 7.183206592176663e-06, 'reg_lambda': 0.001480993397044093, 'max_delta_step': 5}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  74%|███████▍  | 148/200 [02:20<00:44,  1.18it/s]

[I 2025-11-10 14:31:48,723] Trial 147 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.23119588682660672, 'n_estimators': 575, 'subsample': 0.9993097115847979, 'colsample_bytree': 0.8114651502690324, 'min_child_weight': 6, 'gamma': 0.874737464630858, 'reg_alpha': 4.9133304656962085e-06, 'reg_lambda': 0.0018246187813926696, 'max_delta_step': 5}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  75%|███████▌  | 150/200 [02:21<00:33,  1.48it/s]

[I 2025-11-10 14:31:49,781] Trial 150 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.2978114175158295, 'n_estimators': 205, 'subsample': 0.6725611568747921, 'colsample_bytree': 0.6553646243331386, 'min_child_weight': 6, 'gamma': 0.8744676225193467, 'reg_alpha': 2.772308901214048e-06, 'reg_lambda': 0.001872020857387743, 'max_delta_step': 4}. Best is trial 118 with value: 0.572046783625731.
[I 2025-11-10 14:31:49,916] Trial 148 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.23039168714315839, 'n_estimators': 625, 'subsample': 0.7151117430415147, 'colsample_bytree': 0.6330917158678142, 'min_child_weight': 6, 'gamma': 0.7281678833948169, 'reg_alpha': 3.7732444270562697e-06, 'reg_lambda': 0.002124962482638311, 'max_delta_step': 5}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  76%|███████▌  | 151/200 [02:21<00:29,  1.69it/s]

[I 2025-11-10 14:31:50,311] Trial 149 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.2963437200571138, 'n_estimators': 732, 'subsample': 0.6476905519065377, 'colsample_bytree': 0.7591303338316983, 'min_child_weight': 6, 'gamma': 0.7154423245969478, 'reg_alpha': 6.7493107304050694e-06, 'reg_lambda': 0.0018052981355465938, 'max_delta_step': 5}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  76%|███████▋  | 153/200 [02:24<00:40,  1.17it/s]

[I 2025-11-10 14:31:52,774] Trial 151 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.288449656349061, 'n_estimators': 731, 'subsample': 0.7040529330714695, 'colsample_bytree': 0.9585268419068488, 'min_child_weight': 6, 'gamma': 3.124569333024229, 'reg_alpha': 3.2992894887006037e-06, 'reg_lambda': 5.827682817907131e-08, 'max_delta_step': 3}. Best is trial 118 with value: 0.572046783625731.
[I 2025-11-10 14:31:52,940] Trial 152 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.020608638109592806, 'n_estimators': 615, 'subsample': 0.6469075534273295, 'colsample_bytree': 0.7573232767616231, 'min_child_weight': 5, 'gamma': 0.7164284544812779, 'reg_alpha': 0.00045163551329042127, 'reg_lambda': 0.00011832317250996489, 'max_delta_step': 3}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  77%|███████▋  | 154/200 [02:25<00:36,  1.27it/s]

[I 2025-11-10 14:31:53,565] Trial 153 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.021857948371254834, 'n_estimators': 737, 'subsample': 0.6898993058189551, 'colsample_bytree': 0.6077606700764785, 'min_child_weight': 8, 'gamma': 0.5485714794479695, 'reg_alpha': 0.00105892818974987, 'reg_lambda': 0.000151889028488656, 'max_delta_step': 8}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  78%|███████▊  | 155/200 [02:25<00:31,  1.43it/s]

[I 2025-11-10 14:31:54,051] Trial 154 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.06856967730281256, 'n_estimators': 691, 'subsample': 0.5906148854400015, 'colsample_bytree': 0.919789053593195, 'min_child_weight': 8, 'gamma': 4.485542437290064, 'reg_alpha': 0.003814269697558456, 'reg_lambda': 0.0011090328113217396, 'max_delta_step': 0}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  78%|███████▊  | 156/200 [02:26<00:37,  1.18it/s]

[I 2025-11-10 14:31:55,257] Trial 156 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.08439541768763423, 'n_estimators': 451, 'subsample': 0.7261551784494573, 'colsample_bytree': 0.9194409031235558, 'min_child_weight': 8, 'gamma': 4.4879868631517725, 'reg_alpha': 0.004185613573608036, 'reg_lambda': 0.0009629177793968433, 'max_delta_step': 0}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  78%|███████▊  | 157/200 [02:27<00:39,  1.08it/s]

[I 2025-11-10 14:31:56,360] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.07228447046511832, 'n_estimators': 693, 'subsample': 0.591321784566803, 'colsample_bytree': 0.918154119247974, 'min_child_weight': 8, 'gamma': 4.4779609312209345, 'reg_alpha': 0.005173944566991806, 'reg_lambda': 0.0011057923896530518, 'max_delta_step': 0}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  79%|███████▉  | 158/200 [02:31<01:06,  1.58s/it]

[I 2025-11-10 14:31:59,455] Trial 157 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.07337454758788614, 'n_estimators': 1225, 'subsample': 0.5832558482727579, 'colsample_bytree': 0.9311719627221112, 'min_child_weight': 7, 'gamma': 4.1659219333672, 'reg_alpha': 0.005040185432145903, 'reg_lambda': 0.01754018385113921, 'max_delta_step': 0}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  80%|███████▉  | 159/200 [02:31<00:53,  1.30s/it]

[I 2025-11-10 14:32:00,092] Trial 158 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.07525286577806625, 'n_estimators': 1219, 'subsample': 0.6048601077250593, 'colsample_bytree': 0.8560712816621068, 'min_child_weight': 7, 'gamma': 4.8271469292749165, 'reg_alpha': 0.0028014090482679065, 'reg_lambda': 0.008225238816052787, 'max_delta_step': 0}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  80%|████████  | 160/200 [02:32<00:45,  1.14s/it]

[I 2025-11-10 14:32:00,881] Trial 159 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07187936820254592, 'n_estimators': 1130, 'subsample': 0.8283864692766679, 'colsample_bytree': 0.9377596034299337, 'min_child_weight': 7, 'gamma': 0.9340202535646701, 'reg_alpha': 0.0069715013329857516, 'reg_lambda': 0.019239329468148693, 'max_delta_step': 0}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  80%|████████  | 161/200 [02:33<00:42,  1.09s/it]

[I 2025-11-10 14:32:01,849] Trial 160 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01817036893153528, 'n_estimators': 1013, 'subsample': 0.8225316161753188, 'colsample_bytree': 0.8583839299326976, 'min_child_weight': 7, 'gamma': 4.7154621632044025, 'reg_alpha': 0.0019472356886190828, 'reg_lambda': 0.017289382772627166, 'max_delta_step': 1}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  81%|████████  | 162/200 [02:33<00:32,  1.19it/s]

[I 2025-11-10 14:32:02,097] Trial 163 pruned.

Best trial: 118. Best value: 0.572047:  82%|████████▏ | 163/200 [02:35<00:45,  1.24s/it]

[I 2025-11-10 14:32:04,283] Trial 161 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1765373814532288, 'n_estimators': 778, 'subsample': 0.6074675362766713, 'colsample_bytree': 0.893684775810961, 'min_child_weight': 7, 'gamma': 4.7622561001031265, 'reg_alpha': 4.0374449655902274e-08, 'reg_lambda': 0.008739650105481457, 'max_delta_step': 1}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  82%|████████▏ | 164/200 [02:37<00:53,  1.49s/it]

[I 2025-11-10 14:32:06,358] Trial 164 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02362549548890837, 'n_estimators': 779, 'subsample': 0.6200333711676631, 'colsample_bytree': 0.8954933726832337, 'min_child_weight': 5, 'gamma': 4.8311863584069865, 'reg_alpha': 0.7355891686665837, 'reg_lambda': 0.0005757898588600003, 'max_delta_step': 1}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  82%|████████▎ | 165/200 [02:38<00:46,  1.33s/it]

[I 2025-11-10 14:32:07,305] Trial 162 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.060677547364141056, 'n_estimators': 1288, 'subsample': 0.8266272497157288, 'colsample_bytree': 0.9002372288261844, 'min_child_weight': 9, 'gamma': 1.1713376028896207, 'reg_alpha': 0.00011634000565391802, 'reg_lambda': 7.167155026778662e-07, 'max_delta_step': 9}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  83%|████████▎ | 166/200 [02:39<00:36,  1.08s/it]

[I 2025-11-10 14:32:07,799] Trial 165 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.028234202944109995, 'n_estimators': 1044, 'subsample': 0.6270076644807561, 'colsample_bytree': 0.8921689341121737, 'min_child_weight': 9, 'gamma': 4.589992381269822, 'reg_alpha': 3.478827092126314e-08, 'reg_lambda': 9.22605867881198, 'max_delta_step': 6}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  84%|████████▎ | 167/200 [02:41<00:43,  1.32s/it]

[I 2025-11-10 14:32:09,692] Trial 166 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.028006270273044146, 'n_estimators': 953, 'subsample': 0.6202250564938311, 'colsample_bytree': 0.9052433825440329, 'min_child_weight': 5, 'gamma': 4.91011698442003, 'reg_alpha': 0.48138540086901777, 'reg_lambda': 0.002824548935877834, 'max_delta_step': 6}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  84%|████████▍ | 168/200 [02:43<00:48,  1.52s/it]

[I 2025-11-10 14:32:11,688] Trial 167 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.030079981828152122, 'n_estimators': 1038, 'subsample': 0.6339563162731264, 'colsample_bytree': 0.9085245350684561, 'min_child_weight': 9, 'gamma': 4.97965108407999, 'reg_alpha': 0.00011299791526306938, 'reg_lambda': 0.0027909039145444805, 'max_delta_step': 4}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  84%|████████▍ | 169/200 [02:44<00:42,  1.38s/it]

[I 2025-11-10 14:32:12,720] Trial 168 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.027930696640878154, 'n_estimators': 1050, 'subsample': 0.631690794924766, 'colsample_bytree': 0.9674672694723663, 'min_child_weight': 6, 'gamma': 1.8347894772292963, 'reg_alpha': 0.2506003508893557, 'reg_lambda': 0.8384008749579931, 'max_delta_step': 6}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  85%|████████▌ | 170/200 [02:44<00:32,  1.07s/it]

[I 2025-11-10 14:32:13,078] Trial 169 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.032214649294808, 'n_estimators': 959, 'subsample': 0.8087279695200176, 'colsample_bytree': 0.9450191227816641, 'min_child_weight': 6, 'gamma': 3.2655967373387864, 'reg_alpha': 0.0002490691585632857, 'reg_lambda': 0.002887207889465099, 'max_delta_step': 4}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  86%|████████▌ | 171/200 [02:45<00:32,  1.14s/it]

[I 2025-11-10 14:32:14,371] Trial 170 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.02555285342518177, 'n_estimators': 894, 'subsample': 0.5670516963401991, 'colsample_bytree': 0.9635236697650138, 'min_child_weight': 6, 'gamma': 4.935134867281467, 'reg_alpha': 3.213723539838811, 'reg_lambda': 0.6946475377501893, 'max_delta_step': 4}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  86%|████████▌ | 172/200 [02:48<00:43,  1.57s/it]

[I 2025-11-10 14:32:16,950] Trial 172 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.12060739313031892, 'n_estimators': 812, 'subsample': 0.5734365797022807, 'colsample_bytree': 0.9506448505015161, 'min_child_weight': 7, 'gamma': 4.993061917867488, 'reg_alpha': 2.48684413729326, 'reg_lambda': 0.29692356065225356, 'max_delta_step': 0}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  86%|████████▋ | 173/200 [02:48<00:32,  1.21s/it]

[I 2025-11-10 14:32:17,315] Trial 171 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04629912628298065, 'n_estimators': 1071, 'subsample': 0.5749807792799166, 'colsample_bytree': 0.9480473399288459, 'min_child_weight': 6, 'gamma': 2.9078716152641793, 'reg_alpha': 0.00022487711795673204, 'reg_lambda': 0.005444464391766049, 'max_delta_step': 0}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  87%|████████▋ | 174/200 [02:49<00:29,  1.15s/it]

[I 2025-11-10 14:32:18,299] Trial 173 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.12502441319277188, 'n_estimators': 891, 'subsample': 0.9725929251858718, 'colsample_bytree': 0.7745044672933488, 'min_child_weight': 6, 'gamma': 3.5030276011326538, 'reg_alpha': 2.0885707530306257, 'reg_lambda': 0.03391252881423455, 'max_delta_step': 0}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  88%|████████▊ | 176/200 [02:51<00:22,  1.05it/s]

[I 2025-11-10 14:32:19,941] Trial 177 pruned.
[I 2025-11-10 14:32:20,114] Trial 174 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1246152169942438, 'n_estimators': 829, 'subsample': 0.8807106555867039, 'colsample_bytree': 0.7982075877904891, 'min_child_weight': 7, 'gamma': 2.911181578429725, 'reg_alpha': 0.000786942135772846, 'reg_lambda': 0.030469530660090276, 'max_delta_step': 4}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  88%|████████▊ | 176/200 [02:51<00:22,  1.05it/s]

[I 2025-11-10 14:32:20,191] Trial 176 pruned.

Best trial: 118. Best value: 0.572047:  89%|████████▉ | 178/200 [02:57<00:40,  1.85s/it]

[I 2025-11-10 14:32:25,914] Trial 175 finished with value: 0.5287134502923976 and parameters: {'max_depth': 5, 'learning_rate': 0.1405436354854778, 'n_estimators': 1371, 'subsample': 0.930209779970894, 'colsample_bytree': 0.6890669388393582, 'min_child_weight': 4, 'gamma': 3.6886461377029627, 'reg_alpha': 0.0008436247400428438, 'reg_lambda': 0.0955342814072169, 'max_delta_step': 4}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  90%|████████▉ | 179/200 [02:58<00:34,  1.63s/it]

[I 2025-11-10 14:32:26,869] Trial 179 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1417316700256035, 'n_estimators': 1365, 'subsample': 0.8914553556069533, 'colsample_bytree': 0.7060786166212719, 'min_child_weight': 8, 'gamma': 2.551287071494371, 'reg_alpha': 5.5174236522388606e-05, 'reg_lambda': 4.0617917427871886e-07, 'max_delta_step': 7}. Best is trial 118 with value: 0.572046783625731.
[I 2025-11-10 14:32:26,930] Trial 180 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.06532665001071887, 'n_estimators': 1407, 'subsample': 0.5287567427631972, 'colsample_bytree': 0.7116418609413894, 'min_child_weight': 5, 'gamma': 3.943325672479193, 'reg_alpha': 1.3567353963434715e-05, 'reg_lambda': 3.0104083860125276e-07, 'max_delta_step': 3}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  90%|█████████ | 181/200 [02:58<00:19,  1.01s/it]

[I 2025-11-10 14:32:27,142] Trial 178 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.14339697730808668, 'n_estimators': 1475, 'subsample': 0.888234584490218, 'colsample_bytree': 0.7080989255527901, 'min_child_weight': 8, 'gamma': 2.572248083414747, 'reg_alpha': 0.0006288938966923481, 'reg_lambda': 0.037779924601900376, 'max_delta_step': 4}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  91%|█████████ | 182/200 [02:59<00:15,  1.16it/s]

[I 2025-11-10 14:32:27,494] Trial 181 pruned.

Best trial: 118. Best value: 0.572047:  92%|█████████▏| 183/200 [03:00<00:16,  1.01it/s]

[I 2025-11-10 14:32:28,864] Trial 183 pruned.

Best trial: 118. Best value: 0.572047:  92%|█████████▏| 184/200 [03:01<00:17,  1.07s/it]

[I 2025-11-10 14:32:30,181] Trial 184 pruned.

Best trial: 118. Best value: 0.572047:  92%|█████████▎| 185/200 [03:01<00:12,  1.20it/s]

[I 2025-11-10 14:32:30,381] Trial 185 pruned.

Best trial: 118. Best value: 0.572047:  93%|█████████▎| 186/200 [03:02<00:09,  1.43it/s]

[I 2025-11-10 14:32:30,721] Trial 187 pruned.

Best trial: 118. Best value: 0.572047:  94%|█████████▎| 187/200 [03:02<00:08,  1.49it/s]

[I 2025-11-10 14:32:31,330] Trial 188 pruned.

Best trial: 118. Best value: 0.572047:  94%|█████████▍| 189/200 [03:03<00:05,  2.04it/s]

[I 2025-11-10 14:32:31,838] Trial 186 pruned.
[I 2025-11-10 14:32:32,002] Trial 190 pruned.

Best trial: 118. Best value: 0.572047:  95%|█████████▌| 190/200 [03:06<00:11,  1.11s/it]

[I 2025-11-10 14:32:34,580] Trial 189 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.017115814226686284, 'n_estimators': 710, 'subsample': 0.9373651351658968, 'colsample_bytree': 0.9333947108685247, 'min_child_weight': 10, 'gamma': 3.5149264602370733, 'reg_alpha': 0.014569735229240025, 'reg_lambda': 1.934764902393962e-06, 'max_delta_step': 5}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  96%|█████████▌| 191/200 [03:08<00:12,  1.36s/it]

[I 2025-11-10 14:32:36,548] Trial 182 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.21030999523307367, 'n_estimators': 1400, 'subsample': 0.5262014748222539, 'colsample_bytree': 0.8722579428904303, 'min_child_weight': 4, 'gamma': 3.7033763167336353, 'reg_alpha': 0.00042808845203021835, 'reg_lambda': 2.420924079332, 'max_delta_step': 3}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  96%|█████████▌| 192/200 [03:09<00:10,  1.34s/it]

[I 2025-11-10 14:32:37,822] Trial 193 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.01875059687574315, 'n_estimators': 479, 'subsample': 0.7494912519159244, 'colsample_bytree': 0.8702281966570917, 'min_child_weight': 7, 'gamma': 3.3567969565833105, 'reg_alpha': 1.815400361056081e-06, 'reg_lambda': 0.1335422822546007, 'max_delta_step': 2}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  96%|█████████▋| 193/200 [03:09<00:07,  1.10s/it]

[I 2025-11-10 14:32:38,355] Trial 191 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01999563006643666, 'n_estimators': 1082, 'subsample': 0.7487637064332517, 'colsample_bytree': 0.9308603528237661, 'min_child_weight': 10, 'gamma': 3.336740764393222, 'reg_alpha': 1.89406272368738e-06, 'reg_lambda': 1.9122546151821986e-06, 'max_delta_step': 5}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  97%|█████████▋| 194/200 [03:10<00:06,  1.07s/it]

[I 2025-11-10 14:32:39,361] Trial 192 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.019444557583691305, 'n_estimators': 1300, 'subsample': 0.5213139404841121, 'colsample_bytree': 0.7945775618793048, 'min_child_weight': 10, 'gamma': 3.38311593209341, 'reg_alpha': 2.0013246089131304e-06, 'reg_lambda': 0.12273547845846768, 'max_delta_step': 5}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  98%|█████████▊| 195/200 [03:14<00:09,  1.86s/it]

[I 2025-11-10 14:32:43,084] Trial 194 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.17064071951711315, 'n_estimators': 1450, 'subsample': 0.9014014251975002, 'colsample_bytree': 0.5960394156471626, 'min_child_weight': 10, 'gamma': 3.3739087455128787, 'reg_alpha': 7.422370776725894e-05, 'reg_lambda': 0.2766100057932094, 'max_delta_step': 0}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  98%|█████████▊| 196/200 [03:16<00:06,  1.67s/it]

[I 2025-11-10 14:32:44,294] Trial 195 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.17004262946800092, 'n_estimators': 1447, 'subsample': 0.924664566386371, 'colsample_bytree': 0.6902360420331562, 'min_child_weight': 6, 'gamma': 3.43284041507892, 'reg_alpha': 7.008434258153983e-05, 'reg_lambda': 0.024461036258529228, 'max_delta_step': 0}. Best is trial 118 with value: 0.572046783625731.
[I 2025-11-10 14:32:44,475] Trial 198 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.011052888736153713, 'n_estimators': 283, 'subsample': 0.9196969079653147, 'colsample_bytree': 0.6842802476257906, 'min_child_weight': 10, 'gamma': 4.0964847654890155, 'reg_alpha': 0.00012050651908542201, 'reg_lambda': 0.00456340220546298, 'max_delta_step': 0}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047:  99%|█████████▉| 198/200 [03:16<00:01,  1.07it/s]

[I 2025-11-10 14:32:44,748] Trial 196 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.16756234867141018, 'n_estimators': 1444, 'subsample': 0.9040542627788971, 'colsample_bytree': 0.6902383833824934, 'min_child_weight': 10, 'gamma': 3.070884137675882, 'reg_alpha': 0.00014733089547651186, 'reg_lambda': 0.37499473036953607, 'max_delta_step': 0}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047: 100%|█████████▉| 199/200 [03:16<00:00,  1.21it/s]

[I 2025-11-10 14:32:45,306] Trial 197 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1345776059318991, 'n_estimators': 1448, 'subsample': 0.8391784862278057, 'colsample_bytree': 0.6890732694714592, 'min_child_weight': 10, 'gamma': 4.115283552994015, 'reg_alpha': 7.405629760691586e-05, 'reg_lambda': 6.903308604831177e-06, 'max_delta_step': 0}. Best is trial 118 with value: 0.572046783625731.

Best trial: 118. Best value: 0.572047: 100%|██████████| 200/200 [03:19<00:00,  1.00it/s]

[I 2025-11-10 14:32:47,793] Trial 199 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.1891505615377845, 'n_estimators': 1497, 'subsample': 0.5085791216359865, 'colsample_bytree': 0.7231326227422146, 'min_child_weight': 10, 'gamma': 3.5903680194596626, 'reg_alpha': 0.00019698980771269608, 'reg_lambda': 0.5808705949041479, 'max_delta_step': 0}. Best is trial 118 with value: 0.572046783625731.

[I 2025-11-10 14:32:49,209] A new study created in memory with name: 15_1_balanced_accuracy
Best trial: 3. Best value: 0.477018:   0%|          | 1/200 [00:03<11:39,  3.51s/it]

[I 2025-11-10 14:32:52,714] Trial 3 finished with value: 0.47701754385964906 and parameters: {'max_depth': 5, 'learning_rate': 0.02578899617707039, 'n_estimators': 657, 'subsample': 0.7726574906050738, 'colsample_bytree': 0.6026553734251021, 'min_child_weight': 3, 'gamma': 2.3044712710236004, 'reg_alpha': 9.64341800127169e-08, 'reg_lambda': 1.6759315921831895e-08, 'max_delta_step': 0}. Best is trial 3 with value: 0.47701754385964906.

Best trial: 0. Best value: 0.5:   1%|          | 2/200 [00:03<05:08,  1.56s/it]

[I 2025-11-10 14:32:52,905] Trial 2 finished with value: 0.44754385964912285 and parameters: {'max_depth': 8, 'learning_rate': 0.02208930283525458, 'n_estimators': 546, 'subsample': 0.5090541067715428, 'colsample_bytree': 0.843107004630494, 'min_child_weight': 2, 'gamma': 0.9297507291269369, 'reg_alpha': 3.11584586360539e-08, 'reg_lambda': 2.6736567399693036e-05, 'max_delta_step': 9}. Best is trial 3 with value: 0.47701754385964906.
[I 2025-11-10 14:32:52,980] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2603730461206972, 'n_estimators': 889, 'subsample': 0.8276960951297128, 'colsample_bytree': 0.9326857228914038, 'min_child_weight': 9, 'gamma': 1.2806672312026968, 'reg_alpha': 4.81160937978738, 'reg_lambda': 0.00015175184446534882, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   2%|▏         | 4/200 [00:04<02:58,  1.10it/s]

[I 2025-11-10 14:32:53,955] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.015909527957528646, 'n_estimators': 219, 'subsample': 0.5295781519192981, 'colsample_bytree': 0.7604460829527737, 'min_child_weight': 10, 'gamma': 1.879312910284325, 'reg_alpha': 0.00014241173436439964, 'reg_lambda': 0.003602884409093346, 'max_delta_step': 10}. Best is trial 0 with value: 0.5.

Best trial: 5. Best value: 0.529766:   2%|▎         | 5/200 [00:05<03:01,  1.08it/s]

[I 2025-11-10 14:32:54,931] Trial 5 finished with value: 0.529766081871345 and parameters: {'max_depth': 10, 'learning_rate': 0.14049175434942657, 'n_estimators': 442, 'subsample': 0.6077668782511179, 'colsample_bytree': 0.8627880181430012, 'min_child_weight': 4, 'gamma': 0.8779558923041547, 'reg_alpha': 8.63071126088316e-07, 'reg_lambda': 0.08019461287695201, 'max_delta_step': 8}. Best is trial 5 with value: 0.529766081871345.

Best trial: 5. Best value: 0.529766:   3%|▎         | 6/200 [00:06<02:36,  1.24it/s]

[I 2025-11-10 14:32:55,447] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07403245151223638, 'n_estimators': 1463, 'subsample': 0.5766002751891999, 'colsample_bytree': 0.9136900338253687, 'min_child_weight': 5, 'gamma': 4.82270843897953, 'reg_alpha': 9.566461806966182e-06, 'reg_lambda': 4.235138836301633, 'max_delta_step': 3}. Best is trial 5 with value: 0.529766081871345.

Best trial: 5. Best value: 0.529766:   4%|▎         | 7/200 [00:09<04:32,  1.41s/it]

[I 2025-11-10 14:32:58,260] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.046249776087009156, 'n_estimators': 765, 'subsample': 0.6540087680423963, 'colsample_bytree': 0.7136375098203942, 'min_child_weight': 9, 'gamma': 0.5626499029180593, 'reg_alpha': 5.065156703233419, 'reg_lambda': 5.1852673083456515e-05, 'max_delta_step': 2}. Best is trial 5 with value: 0.529766081871345.

Best trial: 5. Best value: 0.529766:   4%|▍         | 8/200 [00:09<03:32,  1.11s/it]

[I 2025-11-10 14:32:58,657] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.1073907461107329, 'n_estimators': 1401, 'subsample': 0.566438515423134, 'colsample_bytree': 0.9787383216452166, 'min_child_weight': 8, 'gamma': 2.600261368409333, 'reg_alpha': 3.9768664693987383, 'reg_lambda': 5.9783391119208174e-05, 'max_delta_step': 7}. Best is trial 5 with value: 0.529766081871345.

Best trial: 5. Best value: 0.529766:   4%|▍         | 9/200 [00:10<03:39,  1.15s/it]

[I 2025-11-10 14:32:59,898] Trial 7 finished with value: 0.5110526315789474 and parameters: {'max_depth': 9, 'learning_rate': 0.039672596074558676, 'n_estimators': 1352, 'subsample': 0.603148851327111, 'colsample_bytree': 0.9192944137724299, 'min_child_weight': 4, 'gamma': 1.935343780340143, 'reg_alpha': 0.016190769868515153, 'reg_lambda': 3.016488674649168e-08, 'max_delta_step': 2}. Best is trial 5 with value: 0.529766081871345.

Best trial: 5. Best value: 0.529766:   5%|▌         | 10/200 [00:10<02:45,  1.15it/s]

[I 2025-11-10 14:33:00,123] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.011819983969904867, 'n_estimators': 356, 'subsample': 0.5003990875177846, 'colsample_bytree': 0.5035624106630635, 'min_child_weight': 9, 'gamma': 4.990789675434356, 'reg_alpha': 4.38822925045458e-05, 'reg_lambda': 0.11681065649591214, 'max_delta_step': 4}. Best is trial 5 with value: 0.529766081871345.
[I 2025-11-10 14:33:00,157] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.056541727734057155, 'n_estimators': 1086, 'subsample': 0.8541720916557884, 'colsample_bytree': 0.7667750894640264, 'min_child_weight': 10, 'gamma': 0.43831527531711656, 'reg_alpha': 2.6147765145670117e-08, 'reg_lambda': 5.470334831426922, 'max_delta_step': 5}. Best is trial 5 with value: 0.529766081871345.

Best trial: 5. Best value: 0.529766:   6%|▌         | 12/200 [00:12<02:28,  1.27it/s]

[I 2025-11-10 14:33:01,512] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.027723939820406517, 'n_estimators': 705, 'subsample': 0.7008702659574451, 'colsample_bytree': 0.848294663872361, 'min_child_weight': 8, 'gamma': 0.9366099977208259, 'reg_alpha': 1.6114474741023616e-06, 'reg_lambda': 0.09804768550636941, 'max_delta_step': 6}. Best is trial 5 with value: 0.529766081871345.

Best trial: 5. Best value: 0.529766:   6%|▋         | 13/200 [00:12<02:04,  1.50it/s]

[I 2025-11-10 14:33:01,812] Trial 13 pruned.

Best trial: 5. Best value: 0.529766:   7%|▋         | 14/200 [00:14<03:12,  1.03s/it]

[I 2025-11-10 14:33:03,880] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.014879691664124435, 'n_estimators': 805, 'subsample': 0.6177491820990901, 'colsample_bytree': 0.994602942247474, 'min_child_weight': 8, 'gamma': 4.164925644238437, 'reg_alpha': 0.0010599983232459432, 'reg_lambda': 7.604215075303244e-07, 'max_delta_step': 7}. Best is trial 5 with value: 0.529766081871345.

Best trial: 14. Best value: 0.555673:   8%|▊         | 15/200 [00:16<03:44,  1.21s/it]

[I 2025-11-10 14:33:05,519] Trial 14 finished with value: 0.5556725146198831 and parameters: {'max_depth': 10, 'learning_rate': 0.1797818462269994, 'n_estimators': 1132, 'subsample': 0.9883982957477451, 'colsample_bytree': 0.8493837907882208, 'min_child_weight': 5, 'gamma': 3.336376084902999, 'reg_alpha': 0.03655007180803731, 'reg_lambda': 1.2491107660620641e-08, 'max_delta_step': 7}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:   8%|▊         | 16/200 [00:17<03:40,  1.20s/it]

[I 2025-11-10 14:33:06,729] Trial 15 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.16994544237595605, 'n_estimators': 1218, 'subsample': 0.641736948470242, 'colsample_bytree': 0.8528536441647373, 'min_child_weight': 5, 'gamma': 3.6439343995664903, 'reg_alpha': 0.014183100816347329, 'reg_lambda': 2.4823427361726966e-08, 'max_delta_step': 8}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:   8%|▊         | 17/200 [00:17<02:53,  1.05it/s]

[I 2025-11-10 14:33:07,051] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.1296232049252832, 'n_estimators': 1189, 'subsample': 0.642974695765581, 'colsample_bytree': 0.8972843861527506, 'min_child_weight': 5, 'gamma': 3.1988598360542095, 'reg_alpha': 0.016541869303645887, 'reg_lambda': 4.179719074199589e-08, 'max_delta_step': 0}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:   9%|▉         | 18/200 [00:19<03:41,  1.21s/it]

[I 2025-11-10 14:33:08,916] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1222473900381563, 'n_estimators': 483, 'subsample': 0.9720075593636422, 'colsample_bytree': 0.7275317368463409, 'min_child_weight': 6, 'gamma': 3.1502722861773824, 'reg_alpha': 0.11801086389296331, 'reg_lambda': 0.005085166969106357, 'max_delta_step': 10}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  10%|▉         | 19/200 [00:20<02:54,  1.03it/s]

[I 2025-11-10 14:33:09,293] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.0940291468382967, 'n_estimators': 462, 'subsample': 0.9326012210181696, 'colsample_bytree': 0.6676306008447432, 'min_child_weight': 6, 'gamma': 3.3983326068772195, 'reg_alpha': 0.14863905881810585, 'reg_lambda': 0.0035912811064151163, 'max_delta_step': 10}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  10%|█         | 20/200 [00:20<02:12,  1.36it/s]

[I 2025-11-10 14:33:09,480] Trial 17 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.12697593816908895, 'n_estimators': 1241, 'subsample': 0.692774313674899, 'colsample_bytree': 0.8826039464954705, 'min_child_weight': 5, 'gamma': 3.276522640662093, 'reg_alpha': 0.07518381724809711, 'reg_lambda': 1.642340352141103e-08, 'max_delta_step': 0}. Best is trial 14 with value: 0.5556725146198831.
[I 2025-11-10 14:33:09,573] Trial 22 pruned.

Best trial: 14. Best value: 0.555673:  11%|█         | 22/200 [00:21<01:50,  1.62it/s]

[I 2025-11-10 14:33:10,428] Trial 23 pruned.

Best trial: 14. Best value: 0.555673:  12%|█▏        | 23/200 [00:21<01:41,  1.75it/s]

[I 2025-11-10 14:33:10,852] Trial 24 pruned.
[I 2025-11-10 14:33:10,914] Trial 18 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.12732163594593252, 'n_estimators': 1175, 'subsample': 0.9931824660273145, 'colsample_bytree': 0.6810779298086677, 'min_child_weight': 6, 'gamma': 3.313163147362748, 'reg_alpha': 0.03017669703295031, 'reg_lambda': 0.0024993971621825096, 'max_delta_step': 8}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  12%|█▎        | 25/200 [00:22<01:33,  1.87it/s]

[I 2025-11-10 14:33:11,829] Trial 25 pruned.

Best trial: 14. Best value: 0.555673:  13%|█▎        | 26/200 [00:22<01:23,  2.08it/s]

[I 2025-11-10 14:33:12,118] Trial 26 pruned.

Best trial: 14. Best value: 0.555673:  14%|█▎        | 27/200 [00:23<01:30,  1.92it/s]

[I 2025-11-10 14:33:12,774] Trial 28 pruned.

Best trial: 14. Best value: 0.555673:  14%|█▍        | 28/200 [00:24<01:37,  1.77it/s]

[I 2025-11-10 14:33:13,456] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.28685398068219004, 'n_estimators': 987, 'subsample': 0.7344298369402005, 'colsample_bytree': 0.6541722462520605, 'min_child_weight': 6, 'gamma': 4.108457060938621, 'reg_alpha': 0.001401174776436466, 'reg_lambda': 1.1383599226256616e-06, 'max_delta_step': 8}. Best is trial 14 with value: 0.5556725146198831.
[I 2025-11-10 14:33:13,550] Trial 29 pruned.

Best trial: 14. Best value: 0.555673:  15%|█▌        | 30/200 [00:27<03:01,  1.07s/it]

[I 2025-11-10 14:33:16,964] Trial 27 finished with value: 0.5440350877192982 and parameters: {'max_depth': 9, 'learning_rate': 0.06497889837319218, 'n_estimators': 1342, 'subsample': 0.588639169494545, 'colsample_bytree': 0.9537608883713966, 'min_child_weight': 4, 'gamma': 2.519182917955942, 'reg_alpha': 0.3836911066038027, 'reg_lambda': 2.495924470172355e-07, 'max_delta_step': 2}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  16%|█▌        | 31/200 [00:28<02:41,  1.05it/s]

[I 2025-11-10 14:33:17,545] Trial 32 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.036032355999297216, 'n_estimators': 910, 'subsample': 0.6953456745167798, 'colsample_bytree': 0.9248617072750267, 'min_child_weight': 7, 'gamma': 1.4078514917263854, 'reg_alpha': 0.006489662616763969, 'reg_lambda': 0.0004451208827365563, 'max_delta_step': 5}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  16%|█▌        | 32/200 [00:29<02:46,  1.01it/s]

[I 2025-11-10 14:33:18,633] Trial 34 pruned.

Best trial: 14. Best value: 0.555673:  16%|█▋        | 33/200 [00:29<02:12,  1.26it/s]

[I 2025-11-10 14:33:18,867] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.16602602108781145, 'n_estimators': 1302, 'subsample': 0.688081367640918, 'colsample_bytree': 0.8216834416809161, 'min_child_weight': 7, 'gamma': 1.3446508165441595, 'reg_alpha': 3.939072808378108e-07, 'reg_lambda': 0.0007615558476307611, 'max_delta_step': 6}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  17%|█▋        | 34/200 [00:29<01:45,  1.58it/s]

[I 2025-11-10 14:33:19,084] Trial 30 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.18304156223477874, 'n_estimators': 1499, 'subsample': 0.7266363066359462, 'colsample_bytree': 0.9056812627693842, 'min_child_weight': 7, 'gamma': 1.4011978778107759, 'reg_alpha': 5.492112937745275e-07, 'reg_lambda': 3.30336174027447e-06, 'max_delta_step': 6}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  18%|█▊        | 37/200 [00:31<01:19,  2.06it/s]

[I 2025-11-10 14:33:20,423] Trial 37 pruned.
[I 2025-11-10 14:33:20,494] Trial 36 pruned.
[I 2025-11-10 14:33:20,523] Trial 33 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.2216133313736226, 'n_estimators': 847, 'subsample': 0.5431346789981389, 'colsample_bytree': 0.8132371244830987, 'min_child_weight': 7, 'gamma': 2.799041425177, 'reg_alpha': 7.856636685987835e-05, 'reg_lambda': 0.0005052924144255171, 'max_delta_step': 5}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  20%|█▉        | 39/200 [00:32<01:20,  1.99it/s]

[I 2025-11-10 14:33:21,643] Trial 38 pruned.
[I 2025-11-10 14:33:21,750] Trial 40 pruned.

Best trial: 14. Best value: 0.555673:  20%|██        | 40/200 [00:34<02:08,  1.25it/s]

[I 2025-11-10 14:33:23,375] Trial 42 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.02326232584235466, 'n_estimators': 304, 'subsample': 0.8206777550852614, 'colsample_bytree': 0.7860887207436301, 'min_child_weight': 5, 'gamma': 0.9906037045697669, 'reg_alpha': 0.04987484138611197, 'reg_lambda': 1.2097795519375903e-08, 'max_delta_step': 1}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  20%|██        | 41/200 [00:34<01:59,  1.33it/s]

[I 2025-11-10 14:33:23,997] Trial 43 pruned.

Best trial: 14. Best value: 0.555673:  21%|██        | 42/200 [00:35<02:01,  1.30it/s]

[I 2025-11-10 14:33:24,803] Trial 41 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09279914035725984, 'n_estimators': 621, 'subsample': 0.5505717415203214, 'colsample_bytree': 0.9962956626614731, 'min_child_weight': 5, 'gamma': 0.8959143755705687, 'reg_alpha': 0.004725784531530099, 'reg_lambda': 1.1249176496404574e-08, 'max_delta_step': 9}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  22%|██▏       | 43/200 [00:36<01:45,  1.49it/s]

[I 2025-11-10 14:33:25,239] Trial 35 finished with value: 0.5007602339181287 and parameters: {'max_depth': 10, 'learning_rate': 0.2113892022664293, 'n_estimators': 1477, 'subsample': 0.6162885298631399, 'colsample_bytree': 0.9166323696723743, 'min_child_weight': 4, 'gamma': 2.1640094563762657, 'reg_alpha': 1.862497217901433, 'reg_lambda': 6.327764022241053e-08, 'max_delta_step': 3}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  22%|██▏       | 44/200 [00:37<02:16,  1.14it/s]

[I 2025-11-10 14:33:26,615] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09238939131347598, 'n_estimators': 1393, 'subsample': 0.5404709109202614, 'colsample_bytree': 0.8411423737882853, 'min_child_weight': 4, 'gamma': 2.113943372166779, 'reg_alpha': 0.004262596904304586, 'reg_lambda': 1.0221933094483555e-08, 'max_delta_step': 4}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  22%|██▎       | 45/200 [00:39<02:53,  1.12s/it]

[I 2025-11-10 14:33:28,313] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.15433807203600766, 'n_estimators': 733, 'subsample': 0.8209049134831984, 'colsample_bytree': 0.8653944732297563, 'min_child_weight': 9, 'gamma': 0.6075071387152078, 'reg_alpha': 5.939332174055687, 'reg_lambda': 5.942465475787782e-05, 'max_delta_step': 7}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  23%|██▎       | 46/200 [00:39<02:40,  1.04s/it]

[I 2025-11-10 14:33:29,169] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2390067915637546, 'n_estimators': 1109, 'subsample': 0.5191055638940741, 'colsample_bytree': 0.966128483924845, 'min_child_weight': 5, 'gamma': 0.5151416238456425, 'reg_alpha': 8.54220011692032, 'reg_lambda': 0.00018540507446074422, 'max_delta_step': 7}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  24%|██▎       | 47/200 [00:40<02:19,  1.10it/s]

[I 2025-11-10 14:33:29,769] Trial 48 pruned.

Best trial: 14. Best value: 0.555673:  24%|██▍       | 48/200 [00:41<02:14,  1.13it/s]

[I 2025-11-10 14:33:30,600] Trial 49 pruned.

Best trial: 14. Best value: 0.555673:  24%|██▍       | 49/200 [00:42<02:12,  1.14it/s]

[I 2025-11-10 14:33:31,464] Trial 50 pruned.

Best trial: 14. Best value: 0.555673:  25%|██▌       | 50/200 [00:42<01:49,  1.37it/s]

[I 2025-11-10 14:33:31,841] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.15139209537211692, 'n_estimators': 1410, 'subsample': 0.6720803544247319, 'colsample_bytree': 0.863757689226726, 'min_child_weight': 4, 'gamma': 1.5928891304649673, 'reg_alpha': 6.610648889912078, 'reg_lambda': 4.55171510015817e-07, 'max_delta_step': 1}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  26%|██▌       | 51/200 [00:43<01:33,  1.60it/s]

[I 2025-11-10 14:33:32,221] Trial 51 pruned.

Best trial: 14. Best value: 0.555673:  26%|██▌       | 52/200 [00:44<02:27,  1.00it/s]

[I 2025-11-10 14:33:34,090] Trial 47 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1500092450595288, 'n_estimators': 1277, 'subsample': 0.6197445308503031, 'colsample_bytree': 0.8927611051205501, 'min_child_weight': 3, 'gamma': 1.6284126956712122, 'reg_alpha': 7.096209777375865, 'reg_lambda': 5.710823924542712e-07, 'max_delta_step': 1}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  26%|██▋       | 53/200 [00:48<04:14,  1.73s/it]

[I 2025-11-10 14:33:37,543] Trial 55 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.18880103136585938, 'n_estimators': 815, 'subsample': 0.9478999064868857, 'colsample_bytree': 0.9233237687872546, 'min_child_weight': 10, 'gamma': 1.1149011985698518, 'reg_alpha': 0.2577533493858519, 'reg_lambda': 1.9180874178258005, 'max_delta_step': 3}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  27%|██▋       | 54/200 [00:48<03:22,  1.38s/it]

[I 2025-11-10 14:33:38,110] Trial 54 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.19554297890136038, 'n_estimators': 1170, 'subsample': 0.5727241961662298, 'colsample_bytree': 0.9299672822327821, 'min_child_weight': 5, 'gamma': 1.1438288352579618, 'reg_alpha': 0.19197921889986777, 'reg_lambda': 0.9714814290848246, 'max_delta_step': 3}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  28%|██▊       | 55/200 [00:49<02:54,  1.20s/it]

[I 2025-11-10 14:33:38,897] Trial 52 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.11437986450956943, 'n_estimators': 1431, 'subsample': 0.6534298636338982, 'colsample_bytree': 0.8321096127424349, 'min_child_weight': 5, 'gamma': 1.6114695510929948, 'reg_alpha': 0.270173758552215, 'reg_lambda': 3.5731105564567035e-08, 'max_delta_step': 3}. Best is trial 14 with value: 0.5556725146198831.
[I 2025-11-10 14:33:38,960] Trial 53 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.05466669008807766, 'n_estimators': 1455, 'subsample': 0.5765339663806263, 'colsample_bytree': 0.8343355044813943, 'min_child_weight': 5, 'gamma': 3.054641081353725, 'reg_alpha': 0.33471683362597665, 'reg_lambda': 2.9570390869024756e-08, 'max_delta_step': 3}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  28%|██▊       | 57/200 [00:52<03:14,  1.36s/it]

[I 2025-11-10 14:33:41,989] Trial 59 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.24783719099132984, 'n_estimators': 670, 'subsample': 0.8971632910344347, 'colsample_bytree': 0.7731813717392396, 'min_child_weight': 8, 'gamma': 0.7167944005737585, 'reg_alpha': 2.3184420887293498, 'reg_lambda': 0.01308547928641644, 'max_delta_step': 5}. Best is trial 14 with value: 0.5556725146198831.
[I 2025-11-10 14:33:42,048] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.24483568090134825, 'n_estimators': 899, 'subsample': 0.6411659559354577, 'colsample_bytree': 0.5307741554182865, 'min_child_weight': 6, 'gamma': 0.7424935679479926, 'reg_alpha': 0.04700129629479904, 'reg_lambda': 0.030436413702158976, 'max_delta_step': 5}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  30%|██▉       | 59/200 [00:53<02:28,  1.06s/it]

[I 2025-11-10 14:33:43,172] Trial 56 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.24297431374035405, 'n_estimators': 1163, 'subsample': 0.5733608043470901, 'colsample_bytree': 0.8311262616206755, 'min_child_weight': 5, 'gamma': 1.9506822926863188, 'reg_alpha': 0.9348417012584206, 'reg_lambda': 8.494456245334254e-08, 'max_delta_step': 5}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  30%|███       | 60/200 [00:55<02:34,  1.11s/it]

[I 2025-11-10 14:33:44,451] Trial 61 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.29842586360279283, 'n_estimators': 382, 'subsample': 0.9883831133759347, 'colsample_bytree': 0.9835298601517994, 'min_child_weight': 6, 'gamma': 4.469750900470078, 'reg_alpha': 0.93603259959825, 'reg_lambda': 1.188478800710442e-06, 'max_delta_step': 0}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  30%|███       | 61/200 [00:55<02:21,  1.02s/it]

[I 2025-11-10 14:33:45,188] Trial 60 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.25833683518539613, 'n_estimators': 472, 'subsample': 0.6333718019367965, 'colsample_bytree': 0.742599059859454, 'min_child_weight': 6, 'gamma': 4.466578548583122, 'reg_alpha': 0.03219469362549656, 'reg_lambda': 1.108566122687019e-07, 'max_delta_step': 9}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  32%|███▏      | 63/200 [00:57<01:51,  1.23it/s]

[I 2025-11-10 14:33:46,378] Trial 58 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.26220000885021555, 'n_estimators': 1499, 'subsample': 0.8970265517367941, 'colsample_bytree': 0.7740709567857923, 'min_child_weight': 6, 'gamma': 1.9594781825472158, 'reg_alpha': 0.043625717007435484, 'reg_lambda': 0.019548477729579284, 'max_delta_step': 5}. Best is trial 14 with value: 0.5556725146198831.
[I 2025-11-10 14:33:46,416] Trial 63 pruned.

Best trial: 14. Best value: 0.555673:  32%|███▏      | 64/200 [00:58<02:05,  1.08it/s]

[I 2025-11-10 14:33:47,731] Trial 66 pruned.

Best trial: 14. Best value: 0.555673:  32%|███▎      | 65/200 [00:59<02:09,  1.04it/s]

[I 2025-11-10 14:33:48,778] Trial 62 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04739187392588725, 'n_estimators': 1040, 'subsample': 0.9921070828477845, 'colsample_bytree': 0.7391857932852274, 'min_child_weight': 6, 'gamma': 2.2560408290910674, 'reg_alpha': 3.451887156528476e-06, 'reg_lambda': 0.0012944947917714986, 'max_delta_step': 0}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  33%|███▎      | 66/200 [01:03<03:58,  1.78s/it]

[I 2025-11-10 14:33:52,590] Trial 64 finished with value: 0.49333333333333335 and parameters: {'max_depth': 4, 'learning_rate': 0.04496618963415218, 'n_estimators': 1331, 'subsample': 0.5998349477357504, 'colsample_bytree': 0.9515184253011341, 'min_child_weight': 4, 'gamma': 2.3475910725060634, 'reg_alpha': 5.9582736982921914e-08, 'reg_lambda': 2.9014532264949087, 'max_delta_step': 2}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  34%|███▎      | 67/200 [01:04<03:26,  1.55s/it]

[I 2025-11-10 14:33:53,577] Trial 65 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.044309929940409575, 'n_estimators': 1352, 'subsample': 0.5008382713950887, 'colsample_bytree': 0.9538892059120073, 'min_child_weight': 4, 'gamma': 3.5944864391464835, 'reg_alpha': 2.850527092744504e-06, 'reg_lambda': 3.132977679398921, 'max_delta_step': 2}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  34%|███▍      | 68/200 [01:05<03:12,  1.46s/it]

[I 2025-11-10 14:33:54,817] Trial 67 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.06525480994187098, 'n_estimators': 1334, 'subsample': 0.7180240054534929, 'colsample_bytree': 0.9155888360127885, 'min_child_weight': 5, 'gamma': 2.276602128815839, 'reg_alpha': 3.4550149220655943e-06, 'reg_lambda': 3.237810305407709, 'max_delta_step': 4}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  34%|███▍      | 69/200 [01:05<02:25,  1.11s/it]

[I 2025-11-10 14:33:55,107] Trial 68 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.07762824892289254, 'n_estimators': 1206, 'subsample': 0.712676344839059, 'colsample_bytree': 0.9132741063682713, 'min_child_weight': 5, 'gamma': 2.401921100978277, 'reg_alpha': 0.08928761094846897, 'reg_lambda': 3.2392949914191775, 'max_delta_step': 4}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  35%|███▌      | 70/200 [01:06<02:00,  1.08it/s]

[I 2025-11-10 14:33:55,566] Trial 71 pruned.

Best trial: 14. Best value: 0.555673:  36%|███▌      | 71/200 [01:07<02:06,  1.02it/s]

[I 2025-11-10 14:33:56,718] Trial 72 pruned.

Best trial: 14. Best value: 0.555673:  36%|███▌      | 72/200 [01:09<02:26,  1.15s/it]

[I 2025-11-10 14:33:58,235] Trial 70 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07050711162901886, 'n_estimators': 976, 'subsample': 0.7082760363168767, 'colsample_bytree': 0.9165113437472767, 'min_child_weight': 5, 'gamma': 3.0748217718194573, 'reg_alpha': 7.4594036612812435e-06, 'reg_lambda': 9.946119974549248, 'max_delta_step': 4}. Best is trial 14 with value: 0.5556725146198831.
[I 2025-11-10 14:33:58,409] Trial 69 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.06541985500911966, 'n_estimators': 1202, 'subsample': 0.7567784603712713, 'colsample_bytree': 0.9167504994789242, 'min_child_weight': 5, 'gamma': 0.2866133151715188, 'reg_alpha': 0.08170419706744164, 'reg_lambda': 0.00013020494777582318, 'max_delta_step': 4}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  37%|███▋      | 74/200 [01:13<03:57,  1.89s/it]

[I 2025-11-10 14:34:02,707] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2058026482749156, 'n_estimators': 1274, 'subsample': 0.5612751540592215, 'colsample_bytree': 0.9803428863906037, 'min_child_weight': 10, 'gamma': 2.5322571522788753, 'reg_alpha': 2.8233838801713738, 'reg_lambda': 7.363802969454137e-05, 'max_delta_step': 8}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  38%|███▊      | 75/200 [01:13<02:57,  1.42s/it]

[I 2025-11-10 14:34:03,041] Trial 73 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.037994458756852686, 'n_estimators': 1497, 'subsample': 0.5557528479142123, 'colsample_bytree': 0.978170708729733, 'min_child_weight': 9, 'gamma': 2.989801337408382, 'reg_alpha': 1.349075153586952e-05, 'reg_lambda': 2.619905691679246e-07, 'max_delta_step': 8}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  38%|███▊      | 76/200 [01:16<03:32,  1.71s/it]

[I 2025-11-10 14:34:05,435] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10635203312198206, 'n_estimators': 1477, 'subsample': 0.5604705866419312, 'colsample_bytree': 0.9758186334554688, 'min_child_weight': 9, 'gamma': 2.5362066888399015, 'reg_alpha': 3.2162684303889097, 'reg_lambda': 3.701276299099435e-05, 'max_delta_step': 7}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  38%|███▊      | 77/200 [01:16<02:51,  1.40s/it]

[I 2025-11-10 14:34:06,100] Trial 76 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.105037905817276, 'n_estimators': 1480, 'subsample': 0.5336509099246438, 'colsample_bytree': 0.9790841445635324, 'min_child_weight': 9, 'gamma': 2.5449655941834104, 'reg_alpha': 3.9609644106656807, 'reg_lambda': 2.2841139853156726e-07, 'max_delta_step': 8}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  40%|███▉      | 79/200 [01:20<03:04,  1.53s/it]

[I 2025-11-10 14:34:09,879] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.10544661063329201, 'n_estimators': 1385, 'subsample': 0.5887499407438881, 'colsample_bytree': 0.9697813740979953, 'min_child_weight': 4, 'gamma': 2.6374832353457847, 'reg_alpha': 3.831304223973585, 'reg_lambda': 2.0961590942972568e-07, 'max_delta_step': 7}. Best is trial 14 with value: 0.5556725146198831.
[I 2025-11-10 14:34:10,040] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.10450257058781018, 'n_estimators': 1376, 'subsample': 0.5842314867043293, 'colsample_bytree': 0.9672455994785789, 'min_child_weight': 10, 'gamma': 2.567420843330949, 'reg_alpha': 3.422165036921962, 'reg_lambda': 3.0823805115983566e-05, 'max_delta_step': 6}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  40%|████      | 80/200 [01:23<03:37,  1.82s/it]

[I 2025-11-10 14:34:12,530] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.16509353471370333, 'n_estimators': 1391, 'subsample': 0.5329400349866477, 'colsample_bytree': 0.881768298119504, 'min_child_weight': 9, 'gamma': 3.9470329151202828, 'reg_alpha': 1.1676011421437746, 'reg_lambda': 1.929235565407475e-08, 'max_delta_step': 6}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  40%|████      | 81/200 [01:23<02:46,  1.40s/it]

[I 2025-11-10 14:34:12,965] Trial 80 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.12200831158558831, 'n_estimators': 1380, 'subsample': 0.5902151378140083, 'colsample_bytree': 0.8809105744631481, 'min_child_weight': 8, 'gamma': 0.021090367184370185, 'reg_alpha': 1.12190270226643e-06, 'reg_lambda': 1.730297792904532e-08, 'max_delta_step': 6}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  42%|████▏     | 83/200 [01:25<02:01,  1.04s/it]

[I 2025-11-10 14:34:14,397] Trial 81 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.16518035803681846, 'n_estimators': 768, 'subsample': 0.6739915108355647, 'colsample_bytree': 0.8858710343372878, 'min_child_weight': 10, 'gamma': 3.421373957887404, 'reg_alpha': 0.44183212681923095, 'reg_lambda': 6.219844474527161e-06, 'max_delta_step': 6}. Best is trial 14 with value: 0.5556725146198831.
[I 2025-11-10 14:34:14,562] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.011940295442334192, 'n_estimators': 211, 'subsample': 0.795735040872014, 'colsample_bytree': 0.7010989993751202, 'min_child_weight': 10, 'gamma': 1.8826869406445454, 'reg_alpha': 3.944652477328696e-05, 'reg_lambda': 0.006497442954747341, 'max_delta_step': 10}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  42%|████▏     | 84/200 [01:26<02:07,  1.10s/it]

[I 2025-11-10 14:34:15,799] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.012598416274630604, 'n_estimators': 243, 'subsample': 0.5229780547934663, 'colsample_bytree': 0.9361269349788356, 'min_child_weight': 8, 'gamma': 1.8247629881072176, 'reg_alpha': 9.630998628782618e-05, 'reg_lambda': 0.22680112135067027, 'max_delta_step': 10}. Best is trial 14 with value: 0.5556725146198831.
[I 2025-11-10 14:34:15,845] Trial 82 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.13582373418679825, 'n_estimators': 1078, 'subsample': 0.7949147735712181, 'colsample_bytree': 0.8828729628273354, 'min_child_weight': 8, 'gamma': 1.8431892931377392, 'reg_alpha': 1.1481772464038602, 'reg_lambda': 1.948301341228657e-06, 'max_delta_step': 10}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  43%|████▎     | 86/200 [01:26<01:17,  1.47it/s]

[I 2025-11-10 14:34:16,195] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.016924885415428408, 'n_estimators': 251, 'subsample': 0.6112932981527236, 'colsample_bytree': 0.6434148308389696, 'min_child_weight': 8, 'gamma': 1.8329622096277571, 'reg_alpha': 0.0007725488121579331, 'reg_lambda': 0.11650784012146938, 'max_delta_step': 2}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  44%|████▍     | 88/200 [01:27<01:01,  1.83it/s]

[I 2025-11-10 14:34:16,853] Trial 88 pruned.
[I 2025-11-10 14:34:17,029] Trial 87 pruned.

Best trial: 14. Best value: 0.555673:  44%|████▍     | 88/200 [01:27<01:01,  1.83it/s]

[I 2025-11-10 14:34:17,047] Trial 89 pruned.

Best trial: 14. Best value: 0.555673:  45%|████▌     | 90/200 [01:28<00:43,  2.52it/s]

[I 2025-11-10 14:34:17,402] Trial 90 pruned.

Best trial: 14. Best value: 0.555673:  46%|████▌     | 91/200 [01:29<01:10,  1.55it/s]

[I 2025-11-10 14:34:18,882] Trial 92 pruned.
[I 2025-11-10 14:34:18,897] Trial 91 pruned.

Best trial: 14. Best value: 0.555673:  46%|████▋     | 93/200 [01:30<01:09,  1.54it/s]

[I 2025-11-10 14:34:20,185] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.13404800939081088, 'n_estimators': 1432, 'subsample': 0.6769288975036167, 'colsample_bytree': 0.7084581626225813, 'min_child_weight': 8, 'gamma': 1.8171770427928986, 'reg_alpha': 0.4687649209059199, 'reg_lambda': 7.176694884989627e-06, 'max_delta_step': 3}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  47%|████▋     | 94/200 [01:33<01:57,  1.10s/it]

[I 2025-11-10 14:34:22,884] Trial 95 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.06041872115346411, 'n_estimators': 566, 'subsample': 0.5718764844192844, 'colsample_bytree': 0.7563185720227671, 'min_child_weight': 9, 'gamma': 0.538446593872397, 'reg_alpha': 0.6804600984647615, 'reg_lambda': 1.2817240657800487e-05, 'max_delta_step': 1}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  48%|████▊     | 95/200 [01:33<01:33,  1.12it/s]

[I 2025-11-10 14:34:23,106] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03207728531487191, 'n_estimators': 595, 'subsample': 0.5688194416020564, 'colsample_bytree': 0.7113552424960997, 'min_child_weight': 9, 'gamma': 0.9165269459740908, 'reg_alpha': 9.003947890140708, 'reg_lambda': 1.3626631304829525e-05, 'max_delta_step': 1}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  48%|████▊     | 96/200 [01:34<01:22,  1.26it/s]

[I 2025-11-10 14:34:23,609] Trial 96 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.059575683429052, 'n_estimators': 549, 'subsample': 0.6448767898604625, 'colsample_bytree': 0.6865823657993819, 'min_child_weight': 9, 'gamma': 0.9024117990621496, 'reg_alpha': 0.00022005507293704256, 'reg_lambda': 0.0008860638838645065, 'max_delta_step': 9}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  48%|████▊     | 97/200 [01:35<01:41,  1.02it/s]

[I 2025-11-10 14:34:25,107] Trial 93 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.17640300993829117, 'n_estimators': 1437, 'subsample': 0.9210310591650053, 'colsample_bytree': 0.9426043325609869, 'min_child_weight': 9, 'gamma': 2.0751578816850347, 'reg_alpha': 0.00042556027050311563, 'reg_lambda': 0.0004847252559098513, 'max_delta_step': 9}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  49%|████▉     | 98/200 [01:37<01:54,  1.13s/it]

[I 2025-11-10 14:34:26,608] Trial 99 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.0524959510249623, 'n_estimators': 644, 'subsample': 0.7446909581880033, 'colsample_bytree': 0.9599409663369414, 'min_child_weight': 7, 'gamma': 0.7911119967869489, 'reg_alpha': 4.935545237557838, 'reg_lambda': 0.004089464560736353, 'max_delta_step': 2}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  50%|█████     | 100/200 [01:37<01:06,  1.50it/s]

[I 2025-11-10 14:34:26,916] Trial 97 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.08508875647808578, 'n_estimators': 857, 'subsample': 0.7387443909866356, 'colsample_bytree': 0.7121487224566886, 'min_child_weight': 7, 'gamma': 0.8936933825296927, 'reg_alpha': 9.691491280934342, 'reg_lambda': 0.0008995096478300037, 'max_delta_step': 9}. Best is trial 14 with value: 0.5556725146198831.
[I 2025-11-10 14:34:27,032] Trial 98 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.010212371539019879, 'n_estimators': 888, 'subsample': 0.651816005616994, 'colsample_bytree': 0.6738782114967478, 'min_child_weight': 7, 'gamma': 1.0613770790955825, 'reg_alpha': 0.13950111494613013, 'reg_lambda': 0.0006673487533476079, 'max_delta_step': 9}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  50%|█████     | 101/200 [01:39<01:40,  1.01s/it]

[I 2025-11-10 14:34:28,884] Trial 100 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.010405410377710145, 'n_estimators': 687, 'subsample': 0.5425062901607967, 'colsample_bytree': 0.8474680858316087, 'min_child_weight': 7, 'gamma': 4.8995400759999646, 'reg_alpha': 0.15946341823723392, 'reg_lambda': 4.825196184483568e-05, 'max_delta_step': 2}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  51%|█████     | 102/200 [01:41<01:59,  1.22s/it]

[I 2025-11-10 14:34:30,586] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03781642068983686, 'n_estimators': 690, 'subsample': 0.5976018683833514, 'colsample_bytree': 0.8709630689464154, 'min_child_weight': 10, 'gamma': 4.904322888115482, 'reg_alpha': 0.002270604646064907, 'reg_lambda': 5.067891991319267e-05, 'max_delta_step': 7}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  52%|█████▏    | 103/200 [01:42<01:48,  1.12s/it]

[I 2025-11-10 14:34:31,484] Trial 101 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.08428518367801194, 'n_estimators': 919, 'subsample': 0.5413689278844014, 'colsample_bytree': 0.924735963782151, 'min_child_weight': 10, 'gamma': 4.9017115395681365, 'reg_alpha': 1.6341769389490122, 'reg_lambda': 7.1994205277832e-05, 'max_delta_step': 2}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  52%|█████▏    | 104/200 [01:43<01:55,  1.20s/it]

[I 2025-11-10 14:34:32,874] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.020778830811670666, 'n_estimators': 1306, 'subsample': 0.5932016548313628, 'colsample_bytree': 0.7255975790396596, 'min_child_weight': 10, 'gamma': 4.827278856014403, 'reg_alpha': 1.658636649573727, 'reg_lambda': 7.75641181853264e-05, 'max_delta_step': 7}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  52%|█████▎    | 105/200 [01:45<02:06,  1.33s/it]

[I 2025-11-10 14:34:34,515] Trial 104 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.05226235369382697, 'n_estimators': 1300, 'subsample': 0.8250587417144735, 'colsample_bytree': 0.7284263187518266, 'min_child_weight': 10, 'gamma': 0.3828595275137669, 'reg_alpha': 6.123154994867983e-06, 'reg_lambda': 6.258837259564833, 'max_delta_step': 5}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  54%|█████▎    | 107/200 [01:46<01:22,  1.13it/s]

[I 2025-11-10 14:34:35,452] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.07214871081426798, 'n_estimators': 1113, 'subsample': 0.8291357405279598, 'colsample_bytree': 0.7286606475747691, 'min_child_weight': 10, 'gamma': 0.4745309385994096, 'reg_alpha': 1.0489003493743614e-08, 'reg_lambda': 9.971214358056619e-05, 'max_delta_step': 5}. Best is trial 14 with value: 0.5556725146198831.
[I 2025-11-10 14:34:35,572] Trial 108 pruned.

Best trial: 14. Best value: 0.555673:  54%|█████▍    | 108/200 [01:47<01:26,  1.06it/s]

[I 2025-11-10 14:34:36,636] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.07257094351066931, 'n_estimators': 1143, 'subsample': 0.7816527492308991, 'colsample_bytree': 0.7603444171825768, 'min_child_weight': 10, 'gamma': 0.4273659440262222, 'reg_alpha': 1.3818307052644425e-08, 'reg_lambda': 6.6306715811657915, 'max_delta_step': 5}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  55%|█████▍    | 109/200 [01:48<01:36,  1.07s/it]

[I 2025-11-10 14:34:37,997] Trial 107 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.05170208631991214, 'n_estimators': 1101, 'subsample': 0.8767072643847579, 'colsample_bytree': 0.7718000114637142, 'min_child_weight': 10, 'gamma': 2.1929358871401505, 'reg_alpha': 6.723016269232596e-06, 'reg_lambda': 0.008573661579153994, 'max_delta_step': 5}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  55%|█████▌    | 110/200 [01:49<01:35,  1.06s/it]

[I 2025-11-10 14:34:39,056] Trial 112 pruned.

Best trial: 14. Best value: 0.555673:  56%|█████▌    | 111/200 [01:51<01:47,  1.21s/it]

[I 2025-11-10 14:34:40,602] Trial 110 finished with value: 0.4932748538011696 and parameters: {'max_depth': 6, 'learning_rate': 0.050615480580298806, 'n_estimators': 1062, 'subsample': 0.6184692666780235, 'colsample_bytree': 0.7913341135105729, 'min_child_weight': 4, 'gamma': 0.6793311151529815, 'reg_alpha': 1.0210852639295215e-06, 'reg_lambda': 1.8312548055157036, 'max_delta_step': 5}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  56%|█████▌    | 112/200 [01:51<01:21,  1.08it/s]

[I 2025-11-10 14:34:40,879] Trial 113 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1879575716628262, 'n_estimators': 379, 'subsample': 0.6211264272579164, 'colsample_bytree': 0.8018888442643612, 'min_child_weight': 5, 'gamma': 2.7128033038785664, 'reg_alpha': 3.2444541195388617e-08, 'reg_lambda': 1.351623375686961, 'max_delta_step': 8}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  56%|█████▋    | 113/200 [01:52<01:11,  1.21it/s]

[I 2025-11-10 14:34:41,464] Trial 109 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.050195055233538156, 'n_estimators': 1231, 'subsample': 0.6149645535445281, 'colsample_bytree': 0.7602527891142912, 'min_child_weight': 5, 'gamma': 0.6223755795132344, 'reg_alpha': 2.2382219752866985e-07, 'reg_lambda': 0.0021430581788938127, 'max_delta_step': 6}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  57%|█████▋    | 114/200 [01:52<01:01,  1.39it/s]

[I 2025-11-10 14:34:41,932] Trial 111 finished with value: 0.5022222222222222 and parameters: {'max_depth': 6, 'learning_rate': 0.04998108936995758, 'n_estimators': 1057, 'subsample': 0.5800894298152071, 'colsample_bytree': 0.9484777719637342, 'min_child_weight': 4, 'gamma': 0.6787404610657608, 'reg_alpha': 7.662834981335073e-07, 'reg_lambda': 1.5158308318896039, 'max_delta_step': 3}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  58%|█████▊    | 116/200 [01:56<01:35,  1.14s/it]

[I 2025-11-10 14:34:45,532] Trial 115 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.04014922518579879, 'n_estimators': 828, 'subsample': 0.6984638775910766, 'colsample_bytree': 0.8920442274237922, 'min_child_weight': 9, 'gamma': 0.5815303433032896, 'reg_alpha': 6.324637665094417e-07, 'reg_lambda': 0.22154473232465646, 'max_delta_step': 6}. Best is trial 14 with value: 0.5556725146198831.
[I 2025-11-10 14:34:45,633] Trial 116 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.2809418616366841, 'n_estimators': 793, 'subsample': 0.5538470663725765, 'colsample_bytree': 0.8578797049088276, 'min_child_weight': 9, 'gamma': 1.6916967228875164, 'reg_alpha': 5.151072589369291e-07, 'reg_lambda': 0.4952389362641571, 'max_delta_step': 1}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  58%|█████▊    | 117/200 [01:57<01:36,  1.17s/it]

[I 2025-11-10 14:34:46,867] Trial 114 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03391185048305496, 'n_estimators': 1228, 'subsample': 0.6266856762200999, 'colsample_bytree': 0.805080160609827, 'min_child_weight': 9, 'gamma': 1.701781524960418, 'reg_alpha': 4.6189670075159774e-08, 'reg_lambda': 0.3246350370284252, 'max_delta_step': 6}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  59%|█████▉    | 118/200 [01:58<01:16,  1.07it/s]

[I 2025-11-10 14:34:47,256] Trial 117 finished with value: 0.5051461988304095 and parameters: {'max_depth': 6, 'learning_rate': 0.272841306556839, 'n_estimators': 996, 'subsample': 0.5846625674096271, 'colsample_bytree': 0.9492551930645596, 'min_child_weight': 4, 'gamma': 0.0552418032385803, 'reg_alpha': 1.203623616609808e-07, 'reg_lambda': 0.23543402280186487, 'max_delta_step': 3}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  60%|█████▉    | 119/200 [02:00<02:02,  1.51s/it]

[I 2025-11-10 14:34:50,126] Trial 119 finished with value: 0.5211111111111111 and parameters: {'max_depth': 6, 'learning_rate': 0.04514742742630129, 'n_estimators': 989, 'subsample': 0.5785155631101, 'colsample_bytree': 0.9483350223241571, 'min_child_weight': 4, 'gamma': 2.394311450723966, 'reg_alpha': 1.3782777121502701e-07, 'reg_lambda': 2.2571631211644384e-08, 'max_delta_step': 3}. Best is trial 14 with value: 0.5556725146198831.
[I 2025-11-10 14:34:50,168] Trial 118 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03429976957102011, 'n_estimators': 998, 'subsample': 0.553706845784932, 'colsample_bytree': 0.9602269044053259, 'min_child_weight': 4, 'gamma': 0.1784467063321058, 'reg_alpha': 4.316985035105791e-08, 'reg_lambda': 1.2866958351373162e-07, 'max_delta_step': 3}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  60%|██████    | 121/200 [02:02<01:28,  1.12s/it]

[I 2025-11-10 14:34:51,467] Trial 120 finished with value: 0.5281286549707602 and parameters: {'max_depth': 6, 'learning_rate': 0.06483820464785066, 'n_estimators': 1012, 'subsample': 0.585476498315702, 'colsample_bytree': 0.9501669124800213, 'min_child_weight': 4, 'gamma': 2.393331767700914, 'reg_alpha': 1.0043272252363484e-07, 'reg_lambda': 2.2454015984471764e-08, 'max_delta_step': 3}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 14. Best value: 0.555673:  61%|██████    | 122/200 [02:02<01:12,  1.07it/s]

[I 2025-11-10 14:34:51,808] Trial 121 finished with value: 0.5098245614035088 and parameters: {'max_depth': 6, 'learning_rate': 0.22998682336207796, 'n_estimators': 950, 'subsample': 0.5811835599569104, 'colsample_bytree': 0.9882188267911773, 'min_child_weight': 4, 'gamma': 1.9730162040793726, 'reg_alpha': 1.0085922253999607e-07, 'reg_lambda': 1.3484744325814407e-07, 'max_delta_step': 3}. Best is trial 14 with value: 0.5556725146198831.

Best trial: 122. Best value: 0.582573:  62%|██████▏   | 123/200 [02:05<01:48,  1.41s/it]

[I 2025-11-10 14:34:54,576] Trial 122 finished with value: 0.5825730994152047 and parameters: {'max_depth': 6, 'learning_rate': 0.2708675517227252, 'n_estimators': 1002, 'subsample': 0.5852602859613907, 'colsample_bytree': 0.9503781476309808, 'min_child_weight': 4, 'gamma': 2.422287735692338, 'reg_alpha': 7.912521854798675e-08, 'reg_lambda': 2.5896950607626054e-08, 'max_delta_step': 3}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  62%|██████▏   | 124/200 [02:05<01:23,  1.10s/it]

[I 2025-11-10 14:34:54,848] Trial 123 finished with value: 0.5142690058479532 and parameters: {'max_depth': 6, 'learning_rate': 0.09668371543847756, 'n_estimators': 1044, 'subsample': 0.5835243404423724, 'colsample_bytree': 0.950716545795548, 'min_child_weight': 4, 'gamma': 2.384732158621871, 'reg_alpha': 1.935650990912586e-07, 'reg_lambda': 2.166488860450403e-08, 'max_delta_step': 3}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  62%|██████▎   | 125/200 [02:06<01:24,  1.13s/it]

[I 2025-11-10 14:34:56,046] Trial 124 finished with value: 0.5031578947368421 and parameters: {'max_depth': 6, 'learning_rate': 0.09708286759724256, 'n_estimators': 936, 'subsample': 0.5838954140758198, 'colsample_bytree': 0.9867925318101832, 'min_child_weight': 4, 'gamma': 2.340368908157614, 'reg_alpha': 7.012025582351747e-08, 'reg_lambda': 2.7167050791991615e-08, 'max_delta_step': 3}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  63%|██████▎   | 126/200 [02:07<01:04,  1.15it/s]

[I 2025-11-10 14:34:56,251] Trial 125 finished with value: 0.5242690058479533 and parameters: {'max_depth': 6, 'learning_rate': 0.22775156220603238, 'n_estimators': 949, 'subsample': 0.5839625066044797, 'colsample_bytree': 0.9468628598574687, 'min_child_weight': 4, 'gamma': 2.4108402120174888, 'reg_alpha': 1.0683308693122763e-07, 'reg_lambda': 1.6365596115718524e-08, 'max_delta_step': 3}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  64%|██████▎   | 127/200 [02:09<01:46,  1.46s/it]

[I 2025-11-10 14:34:59,177] Trial 126 finished with value: 0.5242690058479533 and parameters: {'max_depth': 6, 'learning_rate': 0.22701555298095316, 'n_estimators': 962, 'subsample': 0.5809746532739598, 'colsample_bytree': 0.9469348353654583, 'min_child_weight': 4, 'gamma': 2.3155610057762566, 'reg_alpha': 1.7890895976352412e-07, 'reg_lambda': 2.548830763786046e-08, 'max_delta_step': 3}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  64%|██████▍   | 128/200 [02:10<01:20,  1.11s/it]

[I 2025-11-10 14:34:59,447] Trial 127 finished with value: 0.5242690058479533 and parameters: {'max_depth': 6, 'learning_rate': 0.23107774074149984, 'n_estimators': 955, 'subsample': 0.5822494173249935, 'colsample_bytree': 0.9482530572891504, 'min_child_weight': 4, 'gamma': 2.4506560871387313, 'reg_alpha': 1.2800780808910245e-07, 'reg_lambda': 1.4304765039777214e-08, 'max_delta_step': 3}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  65%|██████▌   | 130/200 [02:11<00:57,  1.23it/s]

[I 2025-11-10 14:35:00,514] Trial 128 finished with value: 0.5409356725146199 and parameters: {'max_depth': 6, 'learning_rate': 0.23883474480354128, 'n_estimators': 949, 'subsample': 0.5819379243689629, 'colsample_bytree': 0.987560433501143, 'min_child_weight': 4, 'gamma': 2.4253580305024833, 'reg_alpha': 1.4266357161373084e-07, 'reg_lambda': 2.3698214560278093e-08, 'max_delta_step': 3}. Best is trial 122 with value: 0.5825730994152047.
[I 2025-11-10 14:35:00,662] Trial 129 finished with value: 0.5409356725146199 and parameters: {'max_depth': 6, 'learning_rate': 0.2253535102183612, 'n_estimators': 961, 'subsample': 0.5803886816839906, 'colsample_bytree': 0.9883025785490774, 'min_child_weight': 4, 'gamma': 2.3396701033771046, 'reg_alpha': 1.4736474443149298e-07, 'reg_lambda': 1.964752189747579e-08, 'max_delta_step': 3}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  66%|██████▌   | 131/200 [02:12<00:59,  1.16it/s]

[I 2025-11-10 14:35:01,622] Trial 133 pruned.

Best trial: 122. Best value: 0.582573:  66%|██████▌   | 132/200 [02:14<01:17,  1.15s/it]

[I 2025-11-10 14:35:03,437] Trial 130 finished with value: 0.5442690058479532 and parameters: {'max_depth': 6, 'learning_rate': 0.2222994778307638, 'n_estimators': 934, 'subsample': 0.5900592355711758, 'colsample_bytree': 0.985251570650148, 'min_child_weight': 4, 'gamma': 2.3785518516128215, 'reg_alpha': 1.328070042180449e-07, 'reg_lambda': 2.4325109009681715e-08, 'max_delta_step': 3}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  66%|██████▋   | 133/200 [02:14<01:03,  1.06it/s]

[I 2025-11-10 14:35:03,905] Trial 131 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.22868383408261775, 'n_estimators': 959, 'subsample': 0.5664927061560057, 'colsample_bytree': 0.932254130758972, 'min_child_weight': 4, 'gamma': 2.413029808214396, 'reg_alpha': 1.1066666690215305e-07, 'reg_lambda': 1.0256893266024102e-08, 'max_delta_step': 3}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  67%|██████▋   | 134/200 [02:15<01:02,  1.05it/s]

[I 2025-11-10 14:35:04,866] Trial 136 pruned.

Best trial: 122. Best value: 0.582573:  68%|██████▊   | 135/200 [02:16<00:52,  1.23it/s]

[I 2025-11-10 14:35:05,360] Trial 132 finished with value: 0.5003508771929824 and parameters: {'max_depth': 6, 'learning_rate': 0.23278072113109077, 'n_estimators': 954, 'subsample': 0.566381297381277, 'colsample_bytree': 0.987906950767607, 'min_child_weight': 3, 'gamma': 2.443208031602665, 'reg_alpha': 1.48771210885635e-07, 'reg_lambda': 1.325850998355465e-08, 'max_delta_step': 4}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  68%|██████▊   | 136/200 [02:17<00:54,  1.17it/s]

[I 2025-11-10 14:35:06,323] Trial 138 pruned.
[I 2025-11-10 14:35:06,341] Trial 134 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.22890792245292227, 'n_estimators': 941, 'subsample': 0.5624762988902591, 'colsample_bytree': 0.9891217169647618, 'min_child_weight': 4, 'gamma': 2.3826850720254393, 'reg_alpha': 2.0890500892635515e-08, 'reg_lambda': 1.9608610961765186e-08, 'max_delta_step': 3}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  69%|██████▉   | 138/200 [02:18<00:55,  1.12it/s]

[I 2025-11-10 14:35:08,181] Trial 135 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.26071898866980603, 'n_estimators': 955, 'subsample': 0.5665849258945745, 'colsample_bytree': 0.9318672553250343, 'min_child_weight': 4, 'gamma': 2.8547380065163415, 'reg_alpha': 2.024467915831984e-08, 'reg_lambda': 1.8036707649075604e-08, 'max_delta_step': 3}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  70%|██████▉   | 139/200 [02:19<00:54,  1.11it/s]

[I 2025-11-10 14:35:09,112] Trial 141 pruned.

Best trial: 122. Best value: 0.582573:  70%|███████   | 140/200 [02:20<00:45,  1.31it/s]

[I 2025-11-10 14:35:09,479] Trial 137 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.19849681798245106, 'n_estimators': 940, 'subsample': 0.5720768920722776, 'colsample_bytree': 0.9728073384368107, 'min_child_weight': 4, 'gamma': 2.2319505098866896, 'reg_alpha': 1.6020556027686655e-07, 'reg_lambda': 3.981825303491786e-08, 'max_delta_step': 3}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  71%|███████   | 142/200 [02:21<00:40,  1.43it/s]

[I 2025-11-10 14:35:10,849] Trial 139 finished with value: 0.49315789473684213 and parameters: {'max_depth': 6, 'learning_rate': 0.2505029908954326, 'n_estimators': 980, 'subsample': 0.577292997317938, 'colsample_bytree': 0.9466841759219567, 'min_child_weight': 4, 'gamma': 2.619677121171533, 'reg_alpha': 3.2827740970295756e-07, 'reg_lambda': 2.3157831624324285e-08, 'max_delta_step': 3}. Best is trial 122 with value: 0.5825730994152047.
[I 2025-11-10 14:35:10,973] Trial 140 finished with value: 0.5142690058479532 and parameters: {'max_depth': 6, 'learning_rate': 0.29155320272803703, 'n_estimators': 988, 'subsample': 0.5787284906738765, 'colsample_bytree': 0.9419218421602987, 'min_child_weight': 4, 'gamma': 2.6719060101667895, 'reg_alpha': 6.765802827103583e-08, 'reg_lambda': 2.661017443746087e-08, 'max_delta_step': 4}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  72%|███████▏  | 143/200 [02:24<01:13,  1.29s/it]

[I 2025-11-10 14:35:13,743] Trial 142 finished with value: 0.5164912280701754 and parameters: {'max_depth': 6, 'learning_rate': 0.29462233700137436, 'n_estimators': 990, 'subsample': 0.5902534293228642, 'colsample_bytree': 0.9997826704945293, 'min_child_weight': 4, 'gamma': 2.7234668365632544, 'reg_alpha': 6.204598717442401e-08, 'reg_lambda': 2.8147793035802523e-08, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  72%|███████▏  | 144/200 [02:25<01:00,  1.08s/it]

[I 2025-11-10 14:35:14,302] Trial 143 finished with value: 0.5209356725146199 and parameters: {'max_depth': 6, 'learning_rate': 0.29558372900027524, 'n_estimators': 1041, 'subsample': 0.5889820767988918, 'colsample_bytree': 0.9575942879855709, 'min_child_weight': 4, 'gamma': 2.73057783828361, 'reg_alpha': 7.351635873267353e-08, 'reg_lambda': 8.453628313547011e-08, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  72%|███████▎  | 145/200 [02:26<01:05,  1.19s/it]

[I 2025-11-10 14:35:15,771] Trial 144 finished with value: 0.5673684210526316 and parameters: {'max_depth': 6, 'learning_rate': 0.21545042172460868, 'n_estimators': 1038, 'subsample': 0.5877367068064484, 'colsample_bytree': 0.9581446966839481, 'min_child_weight': 4, 'gamma': 2.025526435728712, 'reg_alpha': 6.989038243793069e-08, 'reg_lambda': 7.646108119402218e-08, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  73%|███████▎  | 146/200 [02:26<00:48,  1.11it/s]

[I 2025-11-10 14:35:15,965] Trial 145 finished with value: 0.5331578947368422 and parameters: {'max_depth': 6, 'learning_rate': 0.2846387640243193, 'n_estimators': 1049, 'subsample': 0.591065968107209, 'colsample_bytree': 0.9572959851625057, 'min_child_weight': 4, 'gamma': 2.745526489224983, 'reg_alpha': 4.0075055395345654e-08, 'reg_lambda': 7.296505201987856e-08, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  74%|███████▎  | 147/200 [02:27<00:46,  1.15it/s]

[I 2025-11-10 14:35:16,776] Trial 148 pruned.

Best trial: 122. Best value: 0.582573:  74%|███████▍  | 148/200 [02:27<00:36,  1.42it/s]

[I 2025-11-10 14:35:17,070] Trial 149 pruned.

Best trial: 122. Best value: 0.582573:  74%|███████▍  | 149/200 [02:29<00:49,  1.03it/s]

[I 2025-11-10 14:35:18,690] Trial 146 finished with value: 0.5276023391812865 and parameters: {'max_depth': 6, 'learning_rate': 0.2967460506267436, 'n_estimators': 1025, 'subsample': 0.5888437143353215, 'colsample_bytree': 0.9985042244258352, 'min_child_weight': 4, 'gamma': 2.763022217125244, 'reg_alpha': 5.6900304870915753e-08, 'reg_lambda': 7.986795032197193e-08, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  75%|███████▌  | 150/200 [02:30<00:46,  1.08it/s]

[I 2025-11-10 14:35:19,513] Trial 147 finished with value: 0.4942690058479532 and parameters: {'max_depth': 6, 'learning_rate': 0.2999861569288782, 'n_estimators': 1042, 'subsample': 0.5907797286474593, 'colsample_bytree': 0.999976265599343, 'min_child_weight': 4, 'gamma': 2.780209493168619, 'reg_alpha': 6.215422721715862e-08, 'reg_lambda': 9.866707205795545e-08, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  76%|███████▌  | 151/200 [02:31<00:53,  1.10s/it]

[I 2025-11-10 14:35:21,013] Trial 150 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.21334531102542065, 'n_estimators': 865, 'subsample': 0.6067574556347323, 'colsample_bytree': 0.9586168064681471, 'min_child_weight': 5, 'gamma': 2.495425071322236, 'reg_alpha': 9.27131698973675e-08, 'reg_lambda': 9.06139671012011e-08, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  76%|███████▌  | 152/200 [02:32<00:41,  1.15it/s]

[I 2025-11-10 14:35:21,334] Trial 151 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2494524176594951, 'n_estimators': 900, 'subsample': 0.5465290139238635, 'colsample_bytree': 0.9572502255684332, 'min_child_weight': 5, 'gamma': 3.1739585887129884, 'reg_alpha': 1.0188023595726866e-07, 'reg_lambda': 3.492367251855459e-07, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  76%|███████▋  | 153/200 [02:34<00:59,  1.27s/it]

[I 2025-11-10 14:35:23,533] Trial 153 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.24994440708598098, 'n_estimators': 873, 'subsample': 0.5476908801372085, 'colsample_bytree': 0.9792459592872057, 'min_child_weight': 5, 'gamma': 3.1910209702692085, 'reg_alpha': 9.66942677390041e-08, 'reg_lambda': 5.7055690778789487e-08, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  77%|███████▋  | 154/200 [02:34<00:45,  1.01it/s]

[I 2025-11-10 14:35:23,868] Trial 152 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.26805043954535906, 'n_estimators': 1073, 'subsample': 0.5463632812199775, 'colsample_bytree': 0.9822876821334161, 'min_child_weight': 5, 'gamma': 2.499597578846011, 'reg_alpha': 1.1984710924649005e-07, 'reg_lambda': 5.695002537756889e-08, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  78%|███████▊  | 155/200 [02:36<00:50,  1.12s/it]

[I 2025-11-10 14:35:25,308] Trial 154 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.269695925416836, 'n_estimators': 897, 'subsample': 0.5535411297805914, 'colsample_bytree': 0.9793411318797748, 'min_child_weight': 4, 'gamma': 2.279979820780863, 'reg_alpha': 4.7757255761826615e-08, 'reg_lambda': 5.706099072823868e-08, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  78%|███████▊  | 156/200 [02:37<00:46,  1.06s/it]

[I 2025-11-10 14:35:26,237] Trial 158 pruned.

Best trial: 122. Best value: 0.582573:  78%|███████▊  | 157/200 [02:37<00:35,  1.20it/s]

[I 2025-11-10 14:35:26,531] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2753249312316888, 'n_estimators': 1084, 'subsample': 0.5585413784937432, 'colsample_bytree': 0.9791547701710096, 'min_child_weight': 4, 'gamma': 3.2976224449230735, 'reg_alpha': 4.4955404528770466e-08, 'reg_lambda': 5.5070063600210266e-08, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  79%|███████▉  | 158/200 [02:39<00:52,  1.24s/it]

[I 2025-11-10 14:35:28,722] Trial 156 finished with value: 0.5031578947368421 and parameters: {'max_depth': 6, 'learning_rate': 0.2698522189446584, 'n_estimators': 1087, 'subsample': 0.5734635562112744, 'colsample_bytree': 0.9778460022542771, 'min_child_weight': 4, 'gamma': 2.517605433913913, 'reg_alpha': 4.064782088203828e-08, 'reg_lambda': 4.781439589018068e-08, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  80%|███████▉  | 159/200 [02:39<00:38,  1.06it/s]

[I 2025-11-10 14:35:28,976] Trial 157 finished with value: 0.5031578947368421 and parameters: {'max_depth': 6, 'learning_rate': 0.27212023951683795, 'n_estimators': 1092, 'subsample': 0.5737679542851548, 'colsample_bytree': 0.9263123035996944, 'min_child_weight': 4, 'gamma': 2.300286748430076, 'reg_alpha': 3.828172433971908e-08, 'reg_lambda': 1.445796819129509e-08, 'max_delta_step': 3}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  80%|████████  | 160/200 [02:40<00:40,  1.00s/it]

[I 2025-11-10 14:35:30,117] Trial 162 pruned.

Best trial: 122. Best value: 0.582573:  81%|████████  | 162/200 [02:41<00:26,  1.44it/s]

[I 2025-11-10 14:35:30,906] Trial 160 finished with value: 0.5098245614035088 and parameters: {'max_depth': 6, 'learning_rate': 0.24155023664157765, 'n_estimators': 914, 'subsample': 0.5780767899375113, 'colsample_bytree': 0.9534704080034848, 'min_child_weight': 4, 'gamma': 2.5896564321395146, 'reg_alpha': 2.3329781029661291e-07, 'reg_lambda': 3.02546676166019e-08, 'max_delta_step': 3}. Best is trial 122 with value: 0.5825730994152047.
[I 2025-11-10 14:35:31,030] Trial 163 pruned.

Best trial: 122. Best value: 0.582573:  82%|████████▏ | 163/200 [02:42<00:24,  1.48it/s]

[I 2025-11-10 14:35:31,656] Trial 159 finished with value: 0.49315789473684213 and parameters: {'max_depth': 6, 'learning_rate': 0.24021888576578138, 'n_estimators': 1139, 'subsample': 0.5743495614881424, 'colsample_bytree': 0.9237941959560306, 'min_child_weight': 4, 'gamma': 2.5903201210152234, 'reg_alpha': 3.9459688378294333e-07, 'reg_lambda': 1.592518645627682e-08, 'max_delta_step': 3}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  82%|████████▏ | 164/200 [02:44<00:36,  1.01s/it]

[I 2025-11-10 14:35:33,433] Trial 161 finished with value: 0.49315789473684213 and parameters: {'max_depth': 6, 'learning_rate': 0.2209021538867544, 'n_estimators': 978, 'subsample': 0.5756258764059052, 'colsample_bytree': 0.9248523672123768, 'min_child_weight': 4, 'gamma': 2.622095905566991, 'reg_alpha': 4.2169703041071505e-07, 'reg_lambda': 3.2808216808369435e-08, 'max_delta_step': 3}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  82%|████████▎ | 165/200 [02:46<00:45,  1.30s/it]

[I 2025-11-10 14:35:35,435] Trial 165 finished with value: 0.5498245614035089 and parameters: {'max_depth': 6, 'learning_rate': 0.2985389729038531, 'n_estimators': 978, 'subsample': 0.5887127378514926, 'colsample_bytree': 0.992602405590935, 'min_child_weight': 4, 'gamma': 2.698156877716681, 'reg_alpha': 7.503619744412912e-08, 'reg_lambda': 1.8258298628361068e-07, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.
[I 2025-11-10 14:35:35,450] Trial 164 finished with value: 0.5098245614035088 and parameters: {'max_depth': 6, 'learning_rate': 0.2986651293550941, 'n_estimators': 979, 'subsample': 0.5903772010579816, 'colsample_bytree': 0.9942477904197143, 'min_child_weight': 4, 'gamma': 2.760444773345849, 'reg_alpha': 7.607207207313472e-08, 'reg_lambda': 1.8308863008424988e-07, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  84%|████████▎ | 167/200 [02:47<00:30,  1.10it/s]

[I 2025-11-10 14:35:36,347] Trial 166 finished with value: 0.5653801169590643 and parameters: {'max_depth': 6, 'learning_rate': 0.2996374027086284, 'n_estimators': 983, 'subsample': 0.5874100341262594, 'colsample_bytree': 0.9985202791704003, 'min_child_weight': 4, 'gamma': 2.7602917076957083, 'reg_alpha': 7.369233585579894e-08, 'reg_lambda': 1.3595594061819881e-07, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  84%|████████▍ | 168/200 [02:47<00:24,  1.29it/s]

[I 2025-11-10 14:35:36,706] Trial 168 pruned.
[I 2025-11-10 14:35:36,710] Trial 169 pruned.

Best trial: 122. Best value: 0.582573:  85%|████████▌ | 170/200 [02:48<00:17,  1.68it/s]

[I 2025-11-10 14:35:37,391] Trial 170 pruned.

Best trial: 122. Best value: 0.582573:  86%|████████▌ | 171/200 [02:49<00:18,  1.54it/s]

[I 2025-11-10 14:35:38,227] Trial 167 finished with value: 0.5498245614035089 and parameters: {'max_depth': 6, 'learning_rate': 0.2991923103750085, 'n_estimators': 969, 'subsample': 0.5900159091931045, 'colsample_bytree': 0.9995494093476869, 'min_child_weight': 4, 'gamma': 2.727078334230012, 'reg_alpha': 6.453721531739542e-08, 'reg_lambda': 2.123193168830586e-07, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  86%|████████▌ | 172/200 [02:51<00:34,  1.22s/it]

[I 2025-11-10 14:35:41,186] Trial 172 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.196569825997902, 'n_estimators': 963, 'subsample': 0.5631430888949456, 'colsample_bytree': 0.9986914812405834, 'min_child_weight': 4, 'gamma': 2.459937724926937, 'reg_alpha': 2.6001366701571407e-08, 'reg_lambda': 1.0263320227009808e-08, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.
[I 2025-11-10 14:35:41,189] Trial 171 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.20215104930721686, 'n_estimators': 959, 'subsample': 0.5642507063118206, 'colsample_bytree': 0.9696535979987024, 'min_child_weight': 4, 'gamma': 2.1876521821444954, 'reg_alpha': 1.7930176302926482e-07, 'reg_lambda': 1.8085320294944974e-07, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  87%|████████▋ | 174/200 [02:52<00:23,  1.11it/s]

[I 2025-11-10 14:35:42,083] Trial 173 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.20224872976025018, 'n_estimators': 1012, 'subsample': 0.562731474507801, 'colsample_bytree': 0.9720297085269033, 'min_child_weight': 4, 'gamma': 2.1745215769262756, 'reg_alpha': 2.2768837498061217e-08, 'reg_lambda': 1.3350671939683923e-08, 'max_delta_step': 4}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 122. Best value: 0.582573:  88%|████████▊ | 175/200 [02:53<00:22,  1.10it/s]

[I 2025-11-10 14:35:43,026] Trial 174 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2538713433314165, 'n_estimators': 1006, 'subsample': 0.5646890409560182, 'colsample_bytree': 0.9717174473294931, 'min_child_weight': 4, 'gamma': 3.072249829047962, 'reg_alpha': 2.5687663093987494e-08, 'reg_lambda': 2.1642385460326756e-07, 'max_delta_step': 2}. Best is trial 122 with value: 0.5825730994152047.

Best trial: 176. Best value: 0.584795:  88%|████████▊ | 176/200 [02:56<00:33,  1.39s/it]

[I 2025-11-10 14:35:45,870] Trial 176 finished with value: 0.584795321637427 and parameters: {'max_depth': 6, 'learning_rate': 0.25700973240113006, 'n_estimators': 1003, 'subsample': 0.5852004978615809, 'colsample_bytree': 0.9870955296118333, 'min_child_weight': 4, 'gamma': 2.3520794132908165, 'reg_alpha': 5.661242526753873e-08, 'reg_lambda': 1.9630377775080323e-08, 'max_delta_step': 2}. Best is trial 176 with value: 0.584795321637427.
[I 2025-11-10 14:35:45,875] Trial 175 finished with value: 0.5564912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.2600054007853388, 'n_estimators': 1009, 'subsample': 0.5889967514883272, 'colsample_bytree': 0.9860528444951266, 'min_child_weight': 4, 'gamma': 3.4497547791071517, 'reg_alpha': 6.175103163256062e-08, 'reg_lambda': 1.9893693137840978e-08, 'max_delta_step': 2}. Best is trial 176 with value: 0.584795321637427.

Best trial: 176. Best value: 0.584795:  89%|████████▉ | 178/200 [02:56<00:19,  1.15it/s]

[I 2025-11-10 14:35:46,128] Trial 177 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.253080591826428, 'n_estimators': 840, 'subsample': 0.5843227914634485, 'colsample_bytree': 0.9870752889134539, 'min_child_weight': 4, 'gamma': 3.4494166632674688, 'reg_alpha': 5.7344625936210506e-08, 'reg_lambda': 1.9550947133828076e-08, 'max_delta_step': 2}. Best is trial 176 with value: 0.584795321637427.

Best trial: 176. Best value: 0.584795:  90%|████████▉ | 179/200 [02:58<00:20,  1.01it/s]

[I 2025-11-10 14:35:47,524] Trial 178 finished with value: 0.5533333333333333 and parameters: {'max_depth': 6, 'learning_rate': 0.27926574618232514, 'n_estimators': 935, 'subsample': 0.5864761603994055, 'colsample_bytree': 0.9864685186324996, 'min_child_weight': 4, 'gamma': 3.79890108627592, 'reg_alpha': 6.68890854355895e-08, 'reg_lambda': 2.0701278547265586e-08, 'max_delta_step': 3}. Best is trial 176 with value: 0.584795321637427.

Best trial: 176. Best value: 0.584795:  90%|█████████ | 180/200 [02:59<00:19,  1.04it/s]

[I 2025-11-10 14:35:48,391] Trial 182 pruned.

Best trial: 176. Best value: 0.584795:  90%|█████████ | 181/200 [03:00<00:20,  1.09s/it]

[I 2025-11-10 14:35:49,853] Trial 179 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.27865294401972457, 'n_estimators': 839, 'subsample': 0.6287567500832099, 'colsample_bytree': 0.9880924132078884, 'min_child_weight': 5, 'gamma': 3.947784893380566, 'reg_alpha': 5.923674689604937e-08, 'reg_lambda': 3.7286387199939144e-08, 'max_delta_step': 2}. Best is trial 176 with value: 0.584795321637427.

Best trial: 176. Best value: 0.584795:  91%|█████████ | 182/200 [03:01<00:16,  1.07it/s]

[I 2025-11-10 14:35:50,378] Trial 180 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.27792053618796425, 'n_estimators': 926, 'subsample': 0.5930157214012047, 'colsample_bytree': 0.9998132114361984, 'min_child_weight': 5, 'gamma': 3.435468473986338, 'reg_alpha': 4.949567094270088e-08, 'reg_lambda': 1.170090331634223e-07, 'max_delta_step': 2}. Best is trial 176 with value: 0.584795321637427.

Best trial: 176. Best value: 0.584795:  92%|█████████▏| 183/200 [03:01<00:12,  1.37it/s]

[I 2025-11-10 14:35:50,579] Trial 181 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.27822377276337557, 'n_estimators': 923, 'subsample': 0.6203514293284714, 'colsample_bytree': 0.9937963041754052, 'min_child_weight': 5, 'gamma': 3.3767176414346727, 'reg_alpha': 4.5312614012963356e-08, 'reg_lambda': 1.1746526976489225e-07, 'max_delta_step': 2}. Best is trial 176 with value: 0.584795321637427.

Best trial: 176. Best value: 0.584795:  92%|█████████▏| 184/200 [03:03<00:20,  1.26s/it]

[I 2025-11-10 14:35:53,167] Trial 183 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.27991768128077416, 'n_estimators': 1054, 'subsample': 0.5970737057900907, 'colsample_bytree': 0.9874120483396193, 'min_child_weight': 5, 'gamma': 3.680155907572504, 'reg_alpha': 1.7133404630171094e-08, 'reg_lambda': 4.971550928352026e-07, 'max_delta_step': 2}. Best is trial 176 with value: 0.584795321637427.

Best trial: 176. Best value: 0.584795:  92%|█████████▎| 185/200 [03:05<00:21,  1.40s/it]

[I 2025-11-10 14:35:54,920] Trial 184 finished with value: 0.5366666666666667 and parameters: {'max_depth': 6, 'learning_rate': 0.254771498785478, 'n_estimators': 1064, 'subsample': 0.5941511565943023, 'colsample_bytree': 0.999779449889172, 'min_child_weight': 4, 'gamma': 3.692375283169187, 'reg_alpha': 1.3255653842466333e-08, 'reg_lambda': 5.222259088164198e-07, 'max_delta_step': 2}. Best is trial 176 with value: 0.584795321637427.

Best trial: 176. Best value: 0.584795:  94%|█████████▎| 187/200 [03:06<00:10,  1.27it/s]

[I 2025-11-10 14:35:55,102] Trial 186 finished with value: 0.5366666666666667 and parameters: {'max_depth': 6, 'learning_rate': 0.2617093035442333, 'n_estimators': 998, 'subsample': 0.594257126527202, 'colsample_bytree': 0.9802984120973255, 'min_child_weight': 4, 'gamma': 3.6918453331935104, 'reg_alpha': 8.443100020897811e-08, 'reg_lambda': 4.322761189828902e-08, 'max_delta_step': 2}. Best is trial 176 with value: 0.584795321637427.
[I 2025-11-10 14:35:55,274] Trial 185 finished with value: 0.5077777777777779 and parameters: {'max_depth': 6, 'learning_rate': 0.253531753596297, 'n_estimators': 1059, 'subsample': 0.5941360645978201, 'colsample_bytree': 0.9781001954595958, 'min_child_weight': 4, 'gamma': 4.235635493119199, 'reg_alpha': 7.876543026961702e-08, 'reg_lambda': 4.3494627175009405e-08, 'max_delta_step': 2}. Best is trial 176 with value: 0.584795321637427.

Best trial: 176. Best value: 0.584795:  94%|█████████▍| 188/200 [03:06<00:09,  1.30it/s]

[I 2025-11-10 14:35:55,992] Trial 188 pruned.

Best trial: 176. Best value: 0.584795:  94%|█████████▍| 189/200 [03:07<00:06,  1.64it/s]

[I 2025-11-10 14:35:56,227] Trial 189 pruned.

Best trial: 176. Best value: 0.584795:  95%|█████████▌| 190/200 [03:07<00:07,  1.42it/s]

[I 2025-11-10 14:35:57,151] Trial 191 pruned.

Best trial: 176. Best value: 0.584795:  96%|█████████▌| 191/200 [03:08<00:05,  1.74it/s]

[I 2025-11-10 14:35:57,433] Trial 192 pruned.

Best trial: 176. Best value: 0.584795:  96%|█████████▌| 192/200 [03:09<00:05,  1.55it/s]

[I 2025-11-10 14:35:58,232] Trial 187 finished with value: 0.5177777777777778 and parameters: {'max_depth': 6, 'learning_rate': 0.2570529453341911, 'n_estimators': 999, 'subsample': 0.5860139836431941, 'colsample_bytree': 0.9816234802948742, 'min_child_weight': 4, 'gamma': 4.541200026307235, 'reg_alpha': 1.0199127345645182e-07, 'reg_lambda': 4.124866424815169e-08, 'max_delta_step': 1}. Best is trial 176 with value: 0.584795321637427.

Best trial: 176. Best value: 0.584795:  96%|█████████▋| 193/200 [03:10<00:06,  1.02it/s]

[I 2025-11-10 14:35:59,985] Trial 190 finished with value: 0.5088888888888888 and parameters: {'max_depth': 6, 'learning_rate': 0.2599715219501989, 'n_estimators': 1020, 'subsample': 0.6119413418456178, 'colsample_bytree': 0.5600294225439948, 'min_child_weight': 4, 'gamma': 3.747398448008322, 'reg_alpha': 3.2379260806660517e-08, 'reg_lambda': 7.033431663500526e-08, 'max_delta_step': 1}. Best is trial 176 with value: 0.584795321637427.

Best trial: 176. Best value: 0.584795:  98%|█████████▊| 195/200 [03:12<00:04,  1.05it/s]

[I 2025-11-10 14:36:02,007] Trial 194 finished with value: 0.5533333333333333 and parameters: {'max_depth': 6, 'learning_rate': 0.29772321951229547, 'n_estimators': 982, 'subsample': 0.5854039042167455, 'colsample_bytree': 0.9656055538731158, 'min_child_weight': 4, 'gamma': 3.5816806439424056, 'reg_alpha': 8.295657131569192e-08, 'reg_lambda': 1.878821903359549e-08, 'max_delta_step': 2}. Best is trial 176 with value: 0.584795321637427.
[I 2025-11-10 14:36:02,177] Trial 193 finished with value: 0.5533333333333333 and parameters: {'max_depth': 5, 'learning_rate': 0.297411877879617, 'n_estimators': 1072, 'subsample': 0.5877913885614834, 'colsample_bytree': 0.9640845369123906, 'min_child_weight': 4, 'gamma': 3.861642410741643, 'reg_alpha': 3.5484593979093804e-08, 'reg_lambda': 7.698232540263826e-08, 'max_delta_step': 2}. Best is trial 176 with value: 0.584795321637427.

Best trial: 176. Best value: 0.584795:  98%|█████████▊| 197/200 [03:14<00:02,  1.42it/s]

[I 2025-11-10 14:36:03,061] Trial 195 finished with value: 0.5533333333333333 and parameters: {'max_depth': 6, 'learning_rate': 0.294250785052024, 'n_estimators': 987, 'subsample': 0.5875895351568279, 'colsample_bytree': 0.9660868386104513, 'min_child_weight': 4, 'gamma': 3.5700334746603395, 'reg_alpha': 7.707066781100523e-08, 'reg_lambda': 2.4124666195848568e-08, 'max_delta_step': 2}. Best is trial 176 with value: 0.584795321637427.
[I 2025-11-10 14:36:03,233] Trial 197 pruned.

Best trial: 176. Best value: 0.584795:  99%|█████████▉| 198/200 [03:14<00:01,  1.47it/s]

[I 2025-11-10 14:36:03,856] Trial 199 pruned.

Best trial: 176. Best value: 0.584795: 100%|█████████▉| 199/200 [03:15<00:00,  1.71it/s]

[I 2025-11-10 14:36:04,222] Trial 196 finished with value: 0.5533333333333333 and parameters: {'max_depth': 6, 'learning_rate': 0.2982612898587851, 'n_estimators': 984, 'subsample': 0.5880190262862484, 'colsample_bytree': 0.9660038584040216, 'min_child_weight': 4, 'gamma': 3.9695019718319386, 'reg_alpha': 7.859062189047668e-08, 'reg_lambda': 1.896791101553138e-08, 'max_delta_step': 2}. Best is trial 176 with value: 0.584795321637427.

Best trial: 176. Best value: 0.584795: 100%|██████████| 200/200 [03:16<00:00,  1.02it/s]

[I 2025-11-10 14:36:05,571] Trial 198 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.29698487533474566, 'n_estimators': 1073, 'subsample': 0.5710809831972974, 'colsample_bytree': 0.9661389649349268, 'min_child_weight': 4, 'gamma': 3.563543693143111, 'reg_alpha': 7.089129467970073e-08, 'reg_lambda': 2.4357877280507285e-08, 'max_delta_step': 2}. Best is trial 176 with value: 0.584795321637427.

[I 2025-11-10 14:36:06,965] A new study created in memory with name: 16_1_balanced_accuracy
Best trial: 1. Best value: 0.539883:   0%|          | 1/200 [00:02<06:56,  2.09s/it]

[I 2025-11-10 14:36:09,051] Trial 1 finished with value: 0.5398830409356725 and parameters: {'max_depth': 5, 'learning_rate': 0.10130739690532146, 'n_estimators': 474, 'subsample': 0.8773188391716207, 'colsample_bytree': 0.6322576595366523, 'min_child_weight': 5, 'gamma': 1.1341560737097267, 'reg_alpha': 0.40895178138962074, 'reg_lambda': 0.012644900178701209, 'max_delta_step': 5}. Best is trial 1 with value: 0.5398830409356725.
[I 2025-11-10 14:36:09,136] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04586825031139338, 'n_estimators': 480, 'subsample': 0.987489326833527, 'colsample_bytree': 0.8353187271235285, 'min_child_weight': 7, 'gamma': 4.220287686503245, 'reg_alpha': 6.2270624949786235e-06, 'reg_lambda': 0.07244328661263534, 'max_delta_step': 9}. Best is trial 1 with value: 0.5398830409356725.

Best trial: 1. Best value: 0.539883:   2%|▏         | 3/200 [00:04<04:20,  1.32s/it]

[I 2025-11-10 14:36:11,152] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02675881247432974, 'n_estimators': 963, 'subsample': 0.6377788367269793, 'colsample_bytree': 0.924113347924711, 'min_child_weight': 5, 'gamma': 1.5967570731124925, 'reg_alpha': 0.0006076739169049631, 'reg_lambda': 2.1894163659858483e-05, 'max_delta_step': 5}. Best is trial 1 with value: 0.5398830409356725.

Best trial: 4. Best value: 0.589591:   2%|▏         | 4/200 [00:04<03:01,  1.08it/s]

[I 2025-11-10 14:36:11,334] Trial 4 finished with value: 0.5895906432748539 and parameters: {'max_depth': 8, 'learning_rate': 0.0442655001441629, 'n_estimators': 571, 'subsample': 0.8993247300421967, 'colsample_bytree': 0.5031948858390463, 'min_child_weight': 5, 'gamma': 0.8345153329721106, 'reg_alpha': 1.6472547684747187e-06, 'reg_lambda': 1.7138519938232299e-06, 'max_delta_step': 5}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:   2%|▎         | 5/200 [00:06<03:49,  1.18s/it]

[I 2025-11-10 14:36:13,017] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.010903546308047398, 'n_estimators': 984, 'subsample': 0.6042982495920397, 'colsample_bytree': 0.5295672629636954, 'min_child_weight': 6, 'gamma': 4.042720123983518, 'reg_alpha': 1.8287595136104385e-05, 'reg_lambda': 4.636726023242253e-08, 'max_delta_step': 3}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:   3%|▎         | 6/200 [00:06<03:26,  1.06s/it]

[I 2025-11-10 14:36:13,840] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.06532522693433548, 'n_estimators': 543, 'subsample': 0.8022647140358785, 'colsample_bytree': 0.9656825831563067, 'min_child_weight': 9, 'gamma': 1.0603487900634985, 'reg_alpha': 0.4161624593060565, 'reg_lambda': 1.0091824813074925e-05, 'max_delta_step': 6}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:   4%|▎         | 7/200 [00:08<04:14,  1.32s/it]

[I 2025-11-10 14:36:15,724] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.12651705444991854, 'n_estimators': 627, 'subsample': 0.7950482646586792, 'colsample_bytree': 0.5008722119997919, 'min_child_weight': 7, 'gamma': 3.1502403491738256, 'reg_alpha': 1.097376116986307, 'reg_lambda': 3.6406239469990824e-05, 'max_delta_step': 3}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:   4%|▍         | 8/200 [00:09<03:52,  1.21s/it]

[I 2025-11-10 14:36:16,692] Trial 0 finished with value: 0.5361988304093568 and parameters: {'max_depth': 9, 'learning_rate': 0.038163313403385433, 'n_estimators': 1467, 'subsample': 0.8995413601339082, 'colsample_bytree': 0.8931018951032008, 'min_child_weight': 2, 'gamma': 4.999342623677582, 'reg_alpha': 6.169531359690231e-08, 'reg_lambda': 0.05918436751187623, 'max_delta_step': 3}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:   4%|▍         | 9/200 [00:09<02:55,  1.09it/s]

[I 2025-11-10 14:36:16,949] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.014165828516336567, 'n_estimators': 720, 'subsample': 0.639391689667367, 'colsample_bytree': 0.8019904094257373, 'min_child_weight': 9, 'gamma': 0.8097257202061314, 'reg_alpha': 0.0007057006365421128, 'reg_lambda': 1.2150354639460828e-08, 'max_delta_step': 7}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:   5%|▌         | 10/200 [00:10<02:54,  1.09it/s]

[I 2025-11-10 14:36:17,863] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.028672033976204457, 'n_estimators': 1494, 'subsample': 0.6309131889216464, 'colsample_bytree': 0.8817426612598991, 'min_child_weight': 7, 'gamma': 4.07250277273555, 'reg_alpha': 1.9017143862762057e-05, 'reg_lambda': 1.0916412187966003e-06, 'max_delta_step': 7}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:   6%|▌         | 11/200 [00:11<02:37,  1.20it/s]

[I 2025-11-10 14:36:18,496] Trial 11 finished with value: 0.4650877192982456 and parameters: {'max_depth': 3, 'learning_rate': 0.11237115979660535, 'n_estimators': 241, 'subsample': 0.9175324357822439, 'colsample_bytree': 0.9730497355556491, 'min_child_weight': 3, 'gamma': 2.173154228525242, 'reg_alpha': 2.6726072879568016e-08, 'reg_lambda': 8.641605265209327e-08, 'max_delta_step': 4}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:   6%|▋         | 13/200 [00:12<02:00,  1.55it/s]

[I 2025-11-10 14:36:19,382] Trial 13 finished with value: 0.5125730994152047 and parameters: {'max_depth': 7, 'learning_rate': 0.29673879815934967, 'n_estimators': 291, 'subsample': 0.5218615272952047, 'colsample_bytree': 0.6852573709920138, 'min_child_weight': 2, 'gamma': 0.07668620652674463, 'reg_alpha': 1.7403374137329935e-08, 'reg_lambda': 3.218205289805234, 'max_delta_step': 0}. Best is trial 4 with value: 0.5895906432748539.
[I 2025-11-10 14:36:19,553] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.026873776784879514, 'n_estimators': 931, 'subsample': 0.6916019100608914, 'colsample_bytree': 0.5025005867834238, 'min_child_weight': 7, 'gamma': 1.1547152261133742, 'reg_alpha': 0.0008701036458250348, 'reg_lambda': 2.4276382741036738e-08, 'max_delta_step': 0}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:   7%|▋         | 14/200 [00:12<01:39,  1.86it/s]

[I 2025-11-10 14:36:19,840] Trial 14 finished with value: 0.4942690058479532 and parameters: {'max_depth': 7, 'learning_rate': 0.21173073671309, 'n_estimators': 281, 'subsample': 0.8703491652308244, 'colsample_bytree': 0.6436890178370589, 'min_child_weight': 4, 'gamma': 0.12090412906990577, 'reg_alpha': 0.02564921431942159, 'reg_lambda': 0.00227406185296809, 'max_delta_step': 0}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:   8%|▊         | 15/200 [00:13<01:34,  1.96it/s]

[I 2025-11-10 14:36:20,295] Trial 15 pruned.

Best trial: 4. Best value: 0.589591:   8%|▊         | 16/200 [00:14<02:18,  1.32it/s]

[I 2025-11-10 14:36:21,617] Trial 16 finished with value: 0.4742690058479532 and parameters: {'max_depth': 6, 'learning_rate': 0.10190641086394066, 'n_estimators': 415, 'subsample': 0.8740594532588506, 'colsample_bytree': 0.6278036056299566, 'min_child_weight': 4, 'gamma': 0.05349729218816224, 'reg_alpha': 0.042163729606608566, 'reg_lambda': 0.0036626691241579746, 'max_delta_step': 10}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:   9%|▉         | 18/200 [00:15<01:59,  1.53it/s]

[I 2025-11-10 14:36:22,806] Trial 18 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.07734480180370107, 'n_estimators': 442, 'subsample': 0.9921982019696862, 'colsample_bytree': 0.5817476498913758, 'min_child_weight': 1, 'gamma': 2.2714038325335575, 'reg_alpha': 9.890171227692894, 'reg_lambda': 0.00038831522990574854, 'max_delta_step': 8}. Best is trial 4 with value: 0.5895906432748539.
[I 2025-11-10 14:36:22,924] Trial 19 pruned.

Best trial: 4. Best value: 0.589591:  10%|▉         | 19/200 [00:16<01:54,  1.58it/s]

[I 2025-11-10 14:36:23,502] Trial 17 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.08623855160475946, 'n_estimators': 783, 'subsample': 0.9969415332096999, 'colsample_bytree': 0.6174170311947683, 'min_child_weight': 4, 'gamma': 2.2479204357643403, 'reg_alpha': 8.326900410788111, 'reg_lambda': 0.0008995859891252534, 'max_delta_step': 9}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  10%|█         | 20/200 [00:18<03:27,  1.15s/it]

[I 2025-11-10 14:36:25,865] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.15870072826546114, 'n_estimators': 675, 'subsample': 0.803398193555815, 'colsample_bytree': 0.7168700664587471, 'min_child_weight': 5, 'gamma': 1.6189728331585798, 'reg_alpha': 6.360133832824715e-07, 'reg_lambda': 3.028347303733901, 'max_delta_step': 2}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  10%|█         | 21/200 [00:19<02:36,  1.15it/s]

[I 2025-11-10 14:36:26,086] Trial 12 finished with value: 0.5011111111111111 and parameters: {'max_depth': 5, 'learning_rate': 0.03026081991601013, 'n_estimators': 1324, 'subsample': 0.9605025902314466, 'colsample_bytree': 0.8034793700127094, 'min_child_weight': 1, 'gamma': 3.7688343920664478, 'reg_alpha': 4.940763726392724, 'reg_lambda': 2.2449438691308064e-05, 'max_delta_step': 8}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  11%|█         | 22/200 [00:19<02:07,  1.40it/s]

[I 2025-11-10 14:36:26,446] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1496873637000078, 'n_estimators': 655, 'subsample': 0.8006260333242371, 'colsample_bytree': 0.7144973399458665, 'min_child_weight': 10, 'gamma': 1.6136131689843576, 'reg_alpha': 3.0695616589905014e-07, 'reg_lambda': 0.05895462795767363, 'max_delta_step': 4}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  12%|█▏        | 23/200 [00:20<02:46,  1.06it/s]

[I 2025-11-10 14:36:27,913] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.15624351599013497, 'n_estimators': 1175, 'subsample': 0.7797030267690895, 'colsample_bytree': 0.716688907378652, 'min_child_weight': 5, 'gamma': 1.6687017967090152, 'reg_alpha': 7.608456204768513e-07, 'reg_lambda': 1.7112701105295167e-06, 'max_delta_step': 5}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  12%|█▏        | 24/200 [00:23<04:27,  1.52s/it]

[I 2025-11-10 14:36:30,770] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.018996021391012363, 'n_estimators': 1151, 'subsample': 0.7507028893157847, 'colsample_bytree': 0.7594492558303394, 'min_child_weight': 6, 'gamma': 0.7078973387681832, 'reg_alpha': 0.00010726105449641415, 'reg_lambda': 0.03432244521113606, 'max_delta_step': 6}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  12%|█▎        | 25/200 [00:25<04:55,  1.69s/it]

[I 2025-11-10 14:36:32,862] Trial 27 finished with value: 0.4945614035087719 and parameters: {'max_depth': 9, 'learning_rate': 0.043122809860641896, 'n_estimators': 381, 'subsample': 0.9238826761222558, 'colsample_bytree': 0.5570537492885888, 'min_child_weight': 3, 'gamma': 4.873530074836502, 'reg_alpha': 3.737387573399273e-08, 'reg_lambda': 0.332095655629017, 'max_delta_step': 2}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  13%|█▎        | 26/200 [00:26<03:44,  1.29s/it]

[I 2025-11-10 14:36:33,214] Trial 24 finished with value: 0.5109356725146199 and parameters: {'max_depth': 9, 'learning_rate': 0.04493272807054473, 'n_estimators': 1288, 'subsample': 0.9266138632295069, 'colsample_bytree': 0.751161880441338, 'min_child_weight': 3, 'gamma': 4.876585297338502, 'reg_alpha': 1.176944723109928e-07, 'reg_lambda': 0.1422101472119242, 'max_delta_step': 2}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  14%|█▎        | 27/200 [00:26<02:59,  1.03s/it]

[I 2025-11-10 14:36:33,656] Trial 25 finished with value: 0.5256725146198831 and parameters: {'max_depth': 9, 'learning_rate': 0.043990788600131926, 'n_estimators': 1235, 'subsample': 0.9317945178421907, 'colsample_bytree': 0.7811670032667477, 'min_child_weight': 3, 'gamma': 4.9054051169580255, 'reg_alpha': 1.1614879921883249e-07, 'reg_lambda': 0.042619363589533735, 'max_delta_step': 2}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  14%|█▍        | 28/200 [00:29<04:51,  1.69s/it]

[I 2025-11-10 14:36:36,876] Trial 26 finished with value: 0.4909356725146198 and parameters: {'max_depth': 9, 'learning_rate': 0.043561925245577275, 'n_estimators': 1494, 'subsample': 0.9195055723794687, 'colsample_bytree': 0.7692307765979787, 'min_child_weight': 3, 'gamma': 2.9174169259564193, 'reg_alpha': 7.335914067241939e-05, 'reg_lambda': 0.04460160435135202, 'max_delta_step': 2}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  14%|█▍        | 29/200 [00:30<04:06,  1.44s/it]

[I 2025-11-10 14:36:37,735] Trial 28 finished with value: 0.4964912280701754 and parameters: {'max_depth': 9, 'learning_rate': 0.04292355638725685, 'n_estimators': 582, 'subsample': 0.8428331152987816, 'colsample_bytree': 0.8994047820021855, 'min_child_weight': 3, 'gamma': 3.3008368291917156, 'reg_alpha': 1.0303142097466601e-07, 'reg_lambda': 0.01339345434034826, 'max_delta_step': 2}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  15%|█▌        | 30/200 [00:31<03:12,  1.14s/it]

[I 2025-11-10 14:36:38,158] Trial 29 finished with value: 0.5545029239766082 and parameters: {'max_depth': 9, 'learning_rate': 0.039586561260842826, 'n_estimators': 554, 'subsample': 0.8435829334537583, 'colsample_bytree': 0.6649840043031197, 'min_child_weight': 2, 'gamma': 3.0815432111763768, 'reg_alpha': 0.007302860507802776, 'reg_lambda': 0.009493524742525971, 'max_delta_step': 4}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  16%|█▌        | 31/200 [00:31<02:52,  1.02s/it]

[I 2025-11-10 14:36:38,917] Trial 30 finished with value: 0.5378362573099416 and parameters: {'max_depth': 7, 'learning_rate': 0.03623913402168253, 'n_estimators': 555, 'subsample': 0.840551657124305, 'colsample_bytree': 0.8610022736780197, 'min_child_weight': 2, 'gamma': 3.0203027707571066, 'reg_alpha': 0.003383714779596046, 'reg_lambda': 0.6998047727533061, 'max_delta_step': 4}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  16%|█▌        | 32/200 [00:35<04:56,  1.76s/it]

[I 2025-11-10 14:36:42,409] Trial 32 finished with value: 0.4686549707602339 and parameters: {'max_depth': 7, 'learning_rate': 0.05531345158498758, 'n_estimators': 458, 'subsample': 0.855469877470241, 'colsample_bytree': 0.6739461494505391, 'min_child_weight': 2, 'gamma': 0.424441698601729, 'reg_alpha': 0.003401411577434808, 'reg_lambda': 0.7313198163286985, 'max_delta_step': 4}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  16%|█▋        | 33/200 [00:35<03:36,  1.30s/it]

[I 2025-11-10 14:36:42,616] Trial 33 finished with value: 0.5381286549707602 and parameters: {'max_depth': 7, 'learning_rate': 0.05824996341024254, 'n_estimators': 492, 'subsample': 0.8436162932349565, 'colsample_bytree': 0.6763843674801944, 'min_child_weight': 2, 'gamma': 2.8362677040062803, 'reg_alpha': 0.0042957832181250676, 'reg_lambda': 0.00015919490224097698, 'max_delta_step': 4}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  17%|█▋        | 34/200 [00:36<03:23,  1.22s/it]

[I 2025-11-10 14:36:43,671] Trial 34 finished with value: 0.5331578947368422 and parameters: {'max_depth': 7, 'learning_rate': 0.057607951248416375, 'n_estimators': 543, 'subsample': 0.8418482501926844, 'colsample_bytree': 0.6856457545967793, 'min_child_weight': 2, 'gamma': 2.761038864050922, 'reg_alpha': 0.00608341984637323, 'reg_lambda': 1.2050355817968914, 'max_delta_step': 4}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  18%|█▊        | 35/200 [00:37<02:39,  1.04it/s]

[I 2025-11-10 14:36:44,031] Trial 37 pruned.

Best trial: 4. Best value: 0.589591:  18%|█▊        | 36/200 [00:37<02:04,  1.31it/s]

[I 2025-11-10 14:36:44,320] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.021822750948697088, 'n_estimators': 354, 'subsample': 0.8356025827156714, 'colsample_bytree': 0.6673838849861816, 'min_child_weight': 6, 'gamma': 2.6715481742684144, 'reg_alpha': 0.00871470051709748, 'reg_lambda': 0.0001179958260336234, 'max_delta_step': 6}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  19%|█▉        | 38/200 [00:37<01:21,  1.98it/s]

[I 2025-11-10 14:36:44,750] Trial 31 finished with value: 0.49754385964912284 and parameters: {'max_depth': 7, 'learning_rate': 0.020405727222520393, 'n_estimators': 571, 'subsample': 0.8553941297531896, 'colsample_bytree': 0.8648714525341841, 'min_child_weight': 2, 'gamma': 0.5954022644460794, 'reg_alpha': 0.0033883069979410404, 'reg_lambda': 0.8274692719282378, 'max_delta_step': 4}. Best is trial 4 with value: 0.5895906432748539.
[I 2025-11-10 14:36:44,884] Trial 38 pruned.

Best trial: 4. Best value: 0.589591:  20%|█▉        | 39/200 [00:38<01:14,  2.17it/s]

[I 2025-11-10 14:36:45,246] Trial 39 pruned.

Best trial: 4. Best value: 0.589591:  20%|██        | 40/200 [00:38<01:10,  2.28it/s]

[I 2025-11-10 14:36:45,633] Trial 40 pruned.
[I 2025-11-10 14:36:45,661] Trial 41 pruned.

Best trial: 4. Best value: 0.589591:  21%|██        | 42/200 [00:39<00:49,  3.19it/s]

[I 2025-11-10 14:36:45,970] Trial 43 pruned.
[I 2025-11-10 14:36:46,048] Trial 42 pruned.

Best trial: 4. Best value: 0.589591:  22%|██▏       | 44/200 [00:40<01:06,  2.34it/s]

[I 2025-11-10 14:36:47,166] Trial 35 finished with value: 0.539766081871345 and parameters: {'max_depth': 7, 'learning_rate': 0.0227550509266332, 'n_estimators': 514, 'subsample': 0.840782990227427, 'colsample_bytree': 0.8452608837267616, 'min_child_weight': 2, 'gamma': 2.647107670595756, 'reg_alpha': 0.0057622425917764775, 'reg_lambda': 0.0001227890501531757, 'max_delta_step': 6}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  22%|██▎       | 45/200 [00:44<03:08,  1.22s/it]

[I 2025-11-10 14:36:51,173] Trial 46 finished with value: 0.45532163742690057 and parameters: {'max_depth': 7, 'learning_rate': 0.029087138627075154, 'n_estimators': 641, 'subsample': 0.8991080291989458, 'colsample_bytree': 0.8455121987412737, 'min_child_weight': 1, 'gamma': 2.9633508475015655, 'reg_alpha': 0.0012690328027837787, 'reg_lambda': 0.0006675816027971081, 'max_delta_step': 7}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  23%|██▎       | 46/200 [00:45<03:05,  1.21s/it]

[I 2025-11-10 14:36:52,341] Trial 44 finished with value: 0.5126315789473684 and parameters: {'max_depth': 7, 'learning_rate': 0.05285866859557301, 'n_estimators': 909, 'subsample': 0.9600625791830061, 'colsample_bytree': 0.829461936981692, 'min_child_weight': 1, 'gamma': 3.132000827560335, 'reg_alpha': 0.00023897973500440064, 'reg_lambda': 8.39223066037723, 'max_delta_step': 4}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  24%|██▎       | 47/200 [00:45<02:27,  1.04it/s]

[I 2025-11-10 14:36:52,591] Trial 45 finished with value: 0.5034502923976608 and parameters: {'max_depth': 7, 'learning_rate': 0.023664276925869376, 'n_estimators': 893, 'subsample': 0.827101992782174, 'colsample_bytree': 0.8268406244264395, 'min_child_weight': 1, 'gamma': 3.017872907321131, 'reg_alpha': 0.0015931044432913849, 'reg_lambda': 7.629072256232786, 'max_delta_step': 6}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  24%|██▍       | 48/200 [00:46<02:01,  1.25it/s]

[I 2025-11-10 14:36:52,952] Trial 49 pruned.
[I 2025-11-10 14:36:52,993] Trial 47 finished with value: 0.48643274853801166 and parameters: {'max_depth': 6, 'learning_rate': 0.015237221035387492, 'n_estimators': 631, 'subsample': 0.9021026892796253, 'colsample_bytree': 0.8133652840323126, 'min_child_weight': 1, 'gamma': 2.5639737976264763, 'reg_alpha': 0.0002666040098157329, 'reg_lambda': 9.226766940211621e-06, 'max_delta_step': 7}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  25%|██▌       | 50/200 [00:48<02:28,  1.01it/s]

[I 2025-11-10 14:36:55,412] Trial 52 finished with value: 0.579766081871345 and parameters: {'max_depth': 8, 'learning_rate': 0.12659041839340676, 'n_estimators': 397, 'subsample': 0.8741030394342921, 'colsample_bytree': 0.7008445686681362, 'min_child_weight': 2, 'gamma': 3.4229741067084194, 'reg_alpha': 0.05212871199544741, 'reg_lambda': 0.001362654389550468, 'max_delta_step': 5}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  26%|██▌       | 51/200 [00:48<02:06,  1.18it/s]

[I 2025-11-10 14:36:55,806] Trial 53 pruned.

Best trial: 4. Best value: 0.589591:  26%|██▌       | 52/200 [00:49<01:47,  1.38it/s]

[I 2025-11-10 14:36:56,175] Trial 51 finished with value: 0.5581286549707601 and parameters: {'max_depth': 5, 'learning_rate': 0.015800382131367627, 'n_estimators': 386, 'subsample': 0.7751802841381971, 'colsample_bytree': 0.6984691101878611, 'min_child_weight': 2, 'gamma': 2.449943438737981, 'reg_alpha': 0.00029062863179817413, 'reg_lambda': 8.129432631308063e-06, 'max_delta_step': 5}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  26%|██▋       | 53/200 [00:50<02:02,  1.20it/s]

[I 2025-11-10 14:36:57,310] Trial 50 finished with value: 0.5428070175438597 and parameters: {'max_depth': 6, 'learning_rate': 0.01021063276784322, 'n_estimators': 400, 'subsample': 0.874981244601389, 'colsample_bytree': 0.9967577640573749, 'min_child_weight': 2, 'gamma': 1.9201373168890186, 'reg_alpha': 1.4227516656160257e-05, 'reg_lambda': 4.9505049592013446e-05, 'max_delta_step': 7}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  27%|██▋       | 54/200 [00:51<02:20,  1.04it/s]

[I 2025-11-10 14:36:58,607] Trial 54 finished with value: 0.5578362573099416 and parameters: {'max_depth': 8, 'learning_rate': 0.12418422993003, 'n_estimators': 486, 'subsample': 0.8668971724330172, 'colsample_bytree': 0.6421511625934447, 'min_child_weight': 2, 'gamma': 3.389282900238962, 'reg_alpha': 0.009996132097650285, 'reg_lambda': 0.0019161282978177115, 'max_delta_step': 6}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  28%|██▊       | 55/200 [00:51<01:51,  1.30it/s]

[I 2025-11-10 14:36:58,889] Trial 55 finished with value: 0.5175438596491228 and parameters: {'max_depth': 5, 'learning_rate': 0.014535681335979676, 'n_estimators': 298, 'subsample': 0.8663164703847683, 'colsample_bytree': 0.7299021954178918, 'min_child_weight': 2, 'gamma': 3.423952013976585, 'reg_alpha': 0.36759433524270185, 'reg_lambda': 4.156858377388573e-07, 'max_delta_step': 6}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  28%|██▊       | 56/200 [00:52<01:43,  1.39it/s]

[I 2025-11-10 14:36:59,489] Trial 48 finished with value: 0.48643274853801166 and parameters: {'max_depth': 6, 'learning_rate': 0.015704666430357898, 'n_estimators': 895, 'subsample': 0.7794572237884679, 'colsample_bytree': 0.8232889687528369, 'min_child_weight': 1, 'gamma': 1.8641288122535764, 'reg_alpha': 0.00024111611910754922, 'reg_lambda': 4.815454005183987e-05, 'max_delta_step': 6}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  28%|██▊       | 57/200 [00:53<01:34,  1.52it/s]

[I 2025-11-10 14:36:59,985] Trial 56 finished with value: 0.48508771929824557 and parameters: {'max_depth': 5, 'learning_rate': 0.011152762223513133, 'n_estimators': 291, 'subsample': 0.8735554667516805, 'colsample_bytree': 0.6475019721563826, 'min_child_weight': 3, 'gamma': 1.4259342167586888, 'reg_alpha': 3.300078133774094e-06, 'reg_lambda': 3.598583588459578e-07, 'max_delta_step': 8}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  29%|██▉       | 58/200 [00:53<01:16,  1.86it/s]

[I 2025-11-10 14:37:00,238] Trial 59 pruned.

Best trial: 4. Best value: 0.589591:  30%|██▉       | 59/200 [00:53<01:10,  2.01it/s]

[I 2025-11-10 14:37:00,644] Trial 60 pruned.

Best trial: 4. Best value: 0.589591:  30%|███       | 60/200 [00:54<01:02,  2.24it/s]

[I 2025-11-10 14:37:00,967] Trial 62 pruned.

Best trial: 4. Best value: 0.589591:  30%|███       | 61/200 [00:54<01:10,  1.98it/s]

[I 2025-11-10 14:37:01,613] Trial 57 finished with value: 0.5175438596491228 and parameters: {'max_depth': 5, 'learning_rate': 0.010545906905558029, 'n_estimators': 286, 'subsample': 0.8762756090607994, 'colsample_bytree': 0.7294472523904362, 'min_child_weight': 2, 'gamma': 3.4456864727288, 'reg_alpha': 3.0438973494777543e-06, 'reg_lambda': 3.2726123855064784e-06, 'max_delta_step': 8}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  31%|███       | 62/200 [00:55<01:28,  1.56it/s]

[I 2025-11-10 14:37:02,572] Trial 58 finished with value: 0.5259649122807017 and parameters: {'max_depth': 8, 'learning_rate': 0.011082250102433423, 'n_estimators': 427, 'subsample': 0.8844943532817716, 'colsample_bytree': 0.9917307533003284, 'min_child_weight': 3, 'gamma': 3.8192603688022353, 'reg_alpha': 3.293956324060674e-06, 'reg_lambda': 6.272424392773564e-06, 'max_delta_step': 8}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  32%|███▏      | 63/200 [00:55<01:17,  1.77it/s]

[I 2025-11-10 14:37:02,955] Trial 65 pruned.

Best trial: 4. Best value: 0.589591:  32%|███▏      | 64/200 [00:56<01:09,  1.96it/s]

[I 2025-11-10 14:37:03,341] Trial 66 pruned.
[I 2025-11-10 14:37:03,436] Trial 64 finished with value: 0.5673684210526315 and parameters: {'max_depth': 8, 'learning_rate': 0.10492715655044318, 'n_estimators': 347, 'subsample': 0.9096311953117202, 'colsample_bytree': 0.6307595895283752, 'min_child_weight': 5, 'gamma': 0.8787752874482069, 'reg_alpha': 1.1683057913774502e-06, 'reg_lambda': 0.004579459539521384, 'max_delta_step': 5}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  33%|███▎      | 66/200 [00:56<00:42,  3.12it/s]

[I 2025-11-10 14:37:03,544] Trial 61 finished with value: 0.5039766081871345 and parameters: {'max_depth': 9, 'learning_rate': 0.010035888980528719, 'n_estimators': 363, 'subsample': 0.5090710921714122, 'colsample_bytree': 0.9962454966967067, 'min_child_weight': 2, 'gamma': 3.457671654178527, 'reg_alpha': 4.059452551397578e-05, 'reg_lambda': 0.0018692063633631054, 'max_delta_step': 5}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  34%|███▍      | 68/200 [00:57<00:36,  3.63it/s]

[I 2025-11-10 14:37:03,907] Trial 67 pruned.
[I 2025-11-10 14:37:04,016] Trial 68 pruned.

Best trial: 4. Best value: 0.589591:  34%|███▍      | 69/200 [00:57<00:40,  3.20it/s]

[I 2025-11-10 14:37:04,431] Trial 69 pruned.

Best trial: 4. Best value: 0.589591:  35%|███▌      | 70/200 [00:57<00:40,  3.21it/s]

[I 2025-11-10 14:37:04,742] Trial 63 finished with value: 0.5036842105263158 and parameters: {'max_depth': 8, 'learning_rate': 0.010325112726464244, 'n_estimators': 373, 'subsample': 0.5694738065471592, 'colsample_bytree': 0.6975416189073755, 'min_child_weight': 2, 'gamma': 2.1449170192280875, 'reg_alpha': 1.3582805050749672e-06, 'reg_lambda': 0.000345944140826983, 'max_delta_step': 5}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  36%|███▌      | 71/200 [00:58<00:38,  3.37it/s]

[I 2025-11-10 14:37:05,003] Trial 70 pruned.

Best trial: 4. Best value: 0.589591:  36%|███▌      | 72/200 [00:58<00:43,  2.93it/s]

[I 2025-11-10 14:37:05,456] Trial 73 pruned.

Best trial: 4. Best value: 0.589591:  36%|███▋      | 73/200 [00:58<00:39,  3.20it/s]

[I 2025-11-10 14:37:05,694] Trial 74 pruned.

Best trial: 4. Best value: 0.589591:  37%|███▋      | 74/200 [00:59<00:38,  3.25it/s]

[I 2025-11-10 14:37:05,990] Trial 72 pruned.

Best trial: 4. Best value: 0.589591:  38%|███▊      | 75/200 [00:59<00:36,  3.40it/s]

[I 2025-11-10 14:37:06,252] Trial 76 pruned.
[I 2025-11-10 14:37:06,278] Trial 75 pruned.

Best trial: 4. Best value: 0.589591:  38%|███▊      | 77/200 [00:59<00:30,  4.04it/s]

[I 2025-11-10 14:37:06,635] Trial 79 pruned.

Best trial: 4. Best value: 0.589591:  39%|███▉      | 78/200 [01:00<00:30,  3.97it/s]

[I 2025-11-10 14:37:06,905] Trial 78 pruned.
[I 2025-11-10 14:37:06,992] Trial 80 pruned.

Best trial: 4. Best value: 0.589591:  40%|████      | 81/200 [01:00<00:24,  4.91it/s]

[I 2025-11-10 14:37:07,268] Trial 77 pruned.
[I 2025-11-10 14:37:07,404] Trial 81 pruned.

Best trial: 4. Best value: 0.589591:  41%|████      | 82/200 [01:00<00:24,  4.75it/s]

[I 2025-11-10 14:37:07,633] Trial 82 pruned.

Best trial: 4. Best value: 0.589591:  42%|████▏     | 83/200 [01:01<00:29,  3.92it/s]

[I 2025-11-10 14:37:08,019] Trial 83 pruned.

Best trial: 4. Best value: 0.589591:  42%|████▏     | 84/200 [01:01<00:47,  2.43it/s]

[I 2025-11-10 14:37:08,854] Trial 71 finished with value: 0.5119883040935672 and parameters: {'max_depth': 8, 'learning_rate': 0.07224849675218349, 'n_estimators': 529, 'subsample': 0.8611517461577847, 'colsample_bytree': 0.657930989175657, 'min_child_weight': 1, 'gamma': 0.9660571412746869, 'reg_alpha': 1.5209885774772542e-06, 'reg_lambda': 2.5114325058522353e-05, 'max_delta_step': 6}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  42%|████▎     | 85/200 [01:04<01:49,  1.05it/s]

[I 2025-11-10 14:37:11,221] Trial 84 finished with value: 0.5653216374269006 and parameters: {'max_depth': 7, 'learning_rate': 0.03943431846076958, 'n_estimators': 524, 'subsample': 0.7933909227325097, 'colsample_bytree': 0.9151248105503689, 'min_child_weight': 2, 'gamma': 2.6525647161334707, 'reg_alpha': 0.0015188670297699772, 'reg_lambda': 2.715207951519904e-05, 'max_delta_step': 7}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  43%|████▎     | 86/200 [01:04<01:29,  1.27it/s]

[I 2025-11-10 14:37:11,584] Trial 85 finished with value: 0.5489473684210526 and parameters: {'max_depth': 7, 'learning_rate': 0.026146501759659168, 'n_estimators': 520, 'subsample': 0.8278394407135673, 'colsample_bytree': 0.8995402205961743, 'min_child_weight': 2, 'gamma': 2.6748115099476117, 'reg_alpha': 0.0021466369860239512, 'reg_lambda': 6.890323218639586e-05, 'max_delta_step': 7}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  44%|████▎     | 87/200 [01:05<01:20,  1.40it/s]

[I 2025-11-10 14:37:12,125] Trial 87 finished with value: 0.5489473684210526 and parameters: {'max_depth': 7, 'learning_rate': 0.02589001590508685, 'n_estimators': 507, 'subsample': 0.853981229288264, 'colsample_bytree': 0.5966343972992333, 'min_child_weight': 2, 'gamma': 2.725464609880806, 'reg_alpha': 0.0017959338268107535, 'reg_lambda': 7.899297619328195e-05, 'max_delta_step': 7}. Best is trial 4 with value: 0.5895906432748539.
[I 2025-11-10 14:37:12,127] Trial 86 finished with value: 0.559766081871345 and parameters: {'max_depth': 7, 'learning_rate': 0.017011285611579906, 'n_estimators': 518, 'subsample': 0.8362474865042115, 'colsample_bytree': 0.9111831513918367, 'min_child_weight': 2, 'gamma': 2.784777713151759, 'reg_alpha': 0.0015391559894029306, 'reg_lambda': 7.069981465863894e-05, 'max_delta_step': 5}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  44%|████▍     | 89/200 [01:07<01:45,  1.06it/s]

[I 2025-11-10 14:37:14,577] Trial 88 finished with value: 0.5639766081871345 and parameters: {'max_depth': 7, 'learning_rate': 0.03173902650076507, 'n_estimators': 450, 'subsample': 0.7632852971885287, 'colsample_bytree': 0.9196475152065406, 'min_child_weight': 2, 'gamma': 2.783029038962543, 'reg_alpha': 0.0014696946176364918, 'reg_lambda': 6.335201239010276e-05, 'max_delta_step': 7}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  45%|████▌     | 90/200 [01:08<01:33,  1.17it/s]

[I 2025-11-10 14:37:15,144] Trial 89 finished with value: 0.5436842105263158 and parameters: {'max_depth': 7, 'learning_rate': 0.02599901216531642, 'n_estimators': 463, 'subsample': 0.7912367045686002, 'colsample_bytree': 0.9319310067084685, 'min_child_weight': 2, 'gamma': 2.7517735136938595, 'reg_alpha': 0.0021509840133351645, 'reg_lambda': 8.098573803523003e-05, 'max_delta_step': 7}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  46%|████▌     | 91/200 [01:08<01:17,  1.41it/s]

[I 2025-11-10 14:37:15,445] Trial 92 pruned.

Best trial: 4. Best value: 0.589591:  46%|████▌     | 92/200 [01:08<01:08,  1.57it/s]

[I 2025-11-10 14:37:15,883] Trial 93 pruned.

Best trial: 4. Best value: 0.589591:  46%|████▋     | 93/200 [01:09<01:01,  1.75it/s]

[I 2025-11-10 14:37:16,282] Trial 90 finished with value: 0.5639766081871345 and parameters: {'max_depth': 7, 'learning_rate': 0.03137689439064336, 'n_estimators': 568, 'subsample': 0.7674510337905882, 'colsample_bytree': 0.9160551940984448, 'min_child_weight': 2, 'gamma': 2.8307913091222563, 'reg_alpha': 0.0021366584252133663, 'reg_lambda': 2.2211857073023265e-05, 'max_delta_step': 1}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  47%|████▋     | 94/200 [01:09<00:50,  2.08it/s]

[I 2025-11-10 14:37:16,531] Trial 91 finished with value: 0.512280701754386 and parameters: {'max_depth': 7, 'learning_rate': 0.03966725187149107, 'n_estimators': 601, 'subsample': 0.8297548105671817, 'colsample_bytree': 0.9038947291866731, 'min_child_weight': 2, 'gamma': 2.8592224993756243, 'reg_alpha': 0.0023052382933870202, 'reg_lambda': 2.282712293134416e-06, 'max_delta_step': 5}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  48%|████▊     | 95/200 [01:09<00:47,  2.19it/s]

[I 2025-11-10 14:37:16,930] Trial 95 pruned.

Best trial: 4. Best value: 0.589591:  48%|████▊     | 96/200 [01:10<00:45,  2.30it/s]

[I 2025-11-10 14:37:17,311] Trial 96 pruned.

Best trial: 4. Best value: 0.589591:  48%|████▊     | 97/200 [01:12<01:34,  1.09it/s]

[I 2025-11-10 14:37:19,383] Trial 94 finished with value: 0.5711695906432748 and parameters: {'max_depth': 7, 'learning_rate': 0.047532419942012766, 'n_estimators': 573, 'subsample': 0.7690392319025359, 'colsample_bytree': 0.8948497966716632, 'min_child_weight': 2, 'gamma': 2.6105876579321268, 'reg_alpha': 0.011609863027892789, 'reg_lambda': 0.00024675404330443655, 'max_delta_step': 7}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  49%|████▉     | 98/200 [01:13<01:38,  1.04it/s]

[I 2025-11-10 14:37:20,457] Trial 98 finished with value: 0.5600584795321637 and parameters: {'max_depth': 8, 'learning_rate': 0.049877101454057694, 'n_estimators': 443, 'subsample': 0.776271130678141, 'colsample_bytree': 0.907871051571318, 'min_child_weight': 1, 'gamma': 3.5702330856081193, 'reg_alpha': 0.006156209787588637, 'reg_lambda': 8.037970892742033e-06, 'max_delta_step': 1}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  50%|████▉     | 99/200 [01:13<01:20,  1.26it/s]

[I 2025-11-10 14:37:20,847] Trial 97 finished with value: 0.5073099415204678 and parameters: {'max_depth': 7, 'learning_rate': 0.04819466956547518, 'n_estimators': 572, 'subsample': 0.7623420875826276, 'colsample_bytree': 0.8779604074410204, 'min_child_weight': 1, 'gamma': 3.665159266913373, 'reg_alpha': 0.00538153486983128, 'reg_lambda': 1.1315840531516714e-05, 'max_delta_step': 0}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  50%|█████     | 100/200 [01:14<01:17,  1.30it/s]

[I 2025-11-10 14:37:21,566] Trial 101 pruned.

Best trial: 4. Best value: 0.589591:  50%|█████     | 101/200 [01:16<01:48,  1.10s/it]

[I 2025-11-10 14:37:23,427] Trial 100 finished with value: 0.47339181286549703 and parameters: {'max_depth': 8, 'learning_rate': 0.016890924025556628, 'n_estimators': 459, 'subsample': 0.7693493568294891, 'colsample_bytree': 0.8765842799453155, 'min_child_weight': 1, 'gamma': 3.617981207876953, 'reg_alpha': 0.016178318738619094, 'reg_lambda': 8.597206793642217e-06, 'max_delta_step': 0}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  51%|█████     | 102/200 [01:17<01:33,  1.04it/s]

[I 2025-11-10 14:37:24,061] Trial 104 pruned.
[I 2025-11-10 14:37:24,068] Trial 99 finished with value: 0.4847953216374269 and parameters: {'max_depth': 8, 'learning_rate': 0.017049035370013396, 'n_estimators': 813, 'subsample': 0.7684203098392469, 'colsample_bytree': 0.9683155020920686, 'min_child_weight': 1, 'gamma': 3.6186803768214815, 'reg_alpha': 0.005265358246935953, 'reg_lambda': 3.579784726500684e-05, 'max_delta_step': 0}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  52%|█████▏    | 104/200 [01:18<01:10,  1.37it/s]

[I 2025-11-10 14:37:24,995] Trial 106 pruned.

Best trial: 4. Best value: 0.589591:  52%|█████▎    | 105/200 [01:18<01:12,  1.31it/s]

[I 2025-11-10 14:37:25,848] Trial 102 finished with value: 0.4445029239766082 and parameters: {'max_depth': 8, 'learning_rate': 0.016860850820182786, 'n_estimators': 447, 'subsample': 0.7024761661791392, 'colsample_bytree': 0.9133237736128024, 'min_child_weight': 1, 'gamma': 2.5287228816852774, 'reg_alpha': 0.02074737706591039, 'reg_lambda': 6.305908014291897e-06, 'max_delta_step': 1}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  53%|█████▎    | 106/200 [01:19<01:04,  1.46it/s]

[I 2025-11-10 14:37:26,313] Trial 108 pruned.

Best trial: 4. Best value: 0.589591:  54%|█████▍    | 108/200 [01:20<00:53,  1.73it/s]

[I 2025-11-10 14:37:27,289] Trial 107 finished with value: 0.527017543859649 and parameters: {'max_depth': 7, 'learning_rate': 0.05029771477851204, 'n_estimators': 335, 'subsample': 0.7907821207199649, 'colsample_bytree': 0.9788729212903299, 'min_child_weight': 2, 'gamma': 3.260554841112946, 'reg_alpha': 0.0008389906309128577, 'reg_lambda': 2.2551616146568375e-06, 'max_delta_step': 1}. Best is trial 4 with value: 0.5895906432748539.
[I 2025-11-10 14:37:27,391] Trial 105 finished with value: 0.5836842105263158 and parameters: {'max_depth': 8, 'learning_rate': 0.060786445361753115, 'n_estimators': 491, 'subsample': 0.7884500254630297, 'colsample_bytree': 0.943990061132007, 'min_child_weight': 2, 'gamma': 3.4036829257743393, 'reg_alpha': 0.01709006917338935, 'reg_lambda': 5.50408565827486e-06, 'max_delta_step': 1}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  55%|█████▌    | 110/200 [01:21<00:39,  2.28it/s]

[I 2025-11-10 14:37:27,883] Trial 103 finished with value: 0.5047953216374269 and parameters: {'max_depth': 8, 'learning_rate': 0.017693380017264383, 'n_estimators': 655, 'subsample': 0.7788471040185124, 'colsample_bytree': 0.9462374451257202, 'min_child_weight': 1, 'gamma': 3.5647573616851536, 'reg_alpha': 0.023312934190516763, 'reg_lambda': 9.25144349083425e-08, 'max_delta_step': 1}. Best is trial 4 with value: 0.5895906432748539.
[I 2025-11-10 14:37:28,041] Trial 111 pruned.

Best trial: 4. Best value: 0.589591:  56%|█████▌    | 111/200 [01:21<00:32,  2.71it/s]

[I 2025-11-10 14:37:28,240] Trial 110 pruned.

Best trial: 4. Best value: 0.589591:  56%|█████▌    | 112/200 [01:21<00:27,  3.18it/s]

[I 2025-11-10 14:37:28,426] Trial 112 pruned.

Best trial: 4. Best value: 0.589591:  56%|█████▋    | 113/200 [01:21<00:27,  3.15it/s]

[I 2025-11-10 14:37:28,750] Trial 113 pruned.

Best trial: 4. Best value: 0.589591:  57%|█████▋    | 114/200 [01:22<00:27,  3.12it/s]

[I 2025-11-10 14:37:29,078] Trial 115 pruned.

Best trial: 4. Best value: 0.589591:  57%|█████▊    | 115/200 [01:23<01:03,  1.33it/s]

[I 2025-11-10 14:37:30,834] Trial 109 finished with value: 0.5325730994152046 and parameters: {'max_depth': 8, 'learning_rate': 0.059764287843485725, 'n_estimators': 661, 'subsample': 0.7811986360149874, 'colsample_bytree': 0.9779484106182605, 'min_child_weight': 2, 'gamma': 2.989296576779571, 'reg_alpha': 0.013829035212007625, 'reg_lambda': 0.0002066969336267143, 'max_delta_step': 8}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  58%|█████▊    | 116/200 [01:24<01:00,  1.40it/s]

[I 2025-11-10 14:37:31,474] Trial 114 finished with value: 0.5476023391812865 and parameters: {'max_depth': 8, 'learning_rate': 0.02032850140756369, 'n_estimators': 381, 'subsample': 0.8177349623271044, 'colsample_bytree': 0.917507268792403, 'min_child_weight': 2, 'gamma': 3.3588503301330634, 'reg_alpha': 0.0892549195860184, 'reg_lambda': 2.9527787584998e-05, 'max_delta_step': 1}. Best is trial 4 with value: 0.5895906432748539.
[I 2025-11-10 14:37:31,556] Trial 118 pruned.

Best trial: 4. Best value: 0.589591:  59%|█████▉    | 118/200 [01:25<00:52,  1.55it/s]

[I 2025-11-10 14:37:32,604] Trial 117 finished with value: 0.5642690058479533 and parameters: {'max_depth': 7, 'learning_rate': 0.12312870983988404, 'n_estimators': 533, 'subsample': 0.755223417658592, 'colsample_bytree': 0.9628263521964732, 'min_child_weight': 2, 'gamma': 3.741689457893828, 'reg_alpha': 0.007723810300036609, 'reg_lambda': 0.00013012417825219305, 'max_delta_step': 7}. Best is trial 4 with value: 0.5895906432748539.
[I 2025-11-10 14:37:32,658] Trial 116 finished with value: 0.5525730994152047 and parameters: {'max_depth': 8, 'learning_rate': 0.05736905538369928, 'n_estimators': 542, 'subsample': 0.7865765346185628, 'colsample_bytree': 0.9231153596418339, 'min_child_weight': 2, 'gamma': 3.8167462628506237, 'reg_alpha': 0.007298985658629117, 'reg_lambda': 0.0038102775409809076, 'max_delta_step': 7}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  60%|██████    | 120/200 [01:27<01:01,  1.31it/s]

[I 2025-11-10 14:37:34,489] Trial 120 finished with value: 0.519766081871345 and parameters: {'max_depth': 8, 'learning_rate': 0.09490521990157397, 'n_estimators': 507, 'subsample': 0.7396742029942088, 'colsample_bytree': 0.8838689641828058, 'min_child_weight': 2, 'gamma': 2.3476179174385696, 'reg_alpha': 0.007019103154481826, 'reg_lambda': 0.0016886175989414898, 'max_delta_step': 10}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  60%|██████    | 121/200 [01:28<00:56,  1.40it/s]

[I 2025-11-10 14:37:35,030] Trial 119 finished with value: 0.56953216374269 and parameters: {'max_depth': 7, 'learning_rate': 0.1321234534866942, 'n_estimators': 540, 'subsample': 0.7553147028834695, 'colsample_bytree': 0.9583731096110704, 'min_child_weight': 2, 'gamma': 3.7490245719659945, 'reg_alpha': 0.008682833468719408, 'reg_lambda': 0.0015463214492631115, 'max_delta_step': 6}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  61%|██████    | 122/200 [01:30<01:25,  1.10s/it]

[I 2025-11-10 14:37:37,334] Trial 121 finished with value: 0.527017543859649 and parameters: {'max_depth': 6, 'learning_rate': 0.09867500928020796, 'n_estimators': 589, 'subsample': 0.7874833907003743, 'colsample_bytree': 0.9617627152577066, 'min_child_weight': 1, 'gamma': 3.7327992547010447, 'reg_alpha': 0.00716120184099436, 'reg_lambda': 5.325186658326522e-05, 'max_delta_step': 1}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  62%|██████▏   | 123/200 [01:30<01:13,  1.05it/s]

[I 2025-11-10 14:37:37,868] Trial 123 finished with value: 0.5492397660818714 and parameters: {'max_depth': 6, 'learning_rate': 0.037103026956823285, 'n_estimators': 305, 'subsample': 0.7560497315889075, 'colsample_bytree': 0.9587984301358269, 'min_child_weight': 1, 'gamma': 4.551099582763762, 'reg_alpha': 0.034682991878617675, 'reg_lambda': 5.475849847587256e-05, 'max_delta_step': 6}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  62%|██████▏   | 124/200 [01:31<01:02,  1.22it/s]

[I 2025-11-10 14:37:38,335] Trial 125 pruned.

Best trial: 4. Best value: 0.589591:  62%|██████▎   | 125/200 [01:31<00:48,  1.53it/s]

[I 2025-11-10 14:37:38,536] Trial 122 finished with value: 0.4775438596491228 and parameters: {'max_depth': 6, 'learning_rate': 0.024103751981063664, 'n_estimators': 513, 'subsample': 0.7401677546461226, 'colsample_bytree': 0.9587157038035442, 'min_child_weight': 1, 'gamma': 1.0914083510814894, 'reg_alpha': 0.00035367526485247184, 'reg_lambda': 6.31071498770016e-05, 'max_delta_step': 6}. Best is trial 4 with value: 0.5895906432748539.
[I 2025-11-10 14:37:38,544] Trial 126 pruned.

Best trial: 4. Best value: 0.589591:  64%|██████▎   | 127/200 [01:32<00:38,  1.88it/s]

[I 2025-11-10 14:37:39,303] Trial 129 pruned.

Best trial: 4. Best value: 0.589591:  64%|██████▍   | 129/200 [01:33<00:32,  2.21it/s]

[I 2025-11-10 14:37:39,994] Trial 124 finished with value: 0.5270175438596492 and parameters: {'max_depth': 7, 'learning_rate': 0.10733413788629945, 'n_estimators': 591, 'subsample': 0.770715511006141, 'colsample_bytree': 0.958882844598291, 'min_child_weight': 1, 'gamma': 3.9487749723555083, 'reg_alpha': 0.004005310198739103, 'reg_lambda': 6.577291530197773e-05, 'max_delta_step': 6}. Best is trial 4 with value: 0.5895906432748539.
[I 2025-11-10 14:37:40,102] Trial 130 pruned.

Best trial: 4. Best value: 0.589591:  65%|██████▌   | 130/200 [01:34<00:51,  1.36it/s]

[I 2025-11-10 14:37:41,606] Trial 128 finished with value: 0.5584210526315789 and parameters: {'max_depth': 7, 'learning_rate': 0.05425234464330411, 'n_estimators': 464, 'subsample': 0.7701158266213077, 'colsample_bytree': 0.8910629354270861, 'min_child_weight': 2, 'gamma': 3.9023060709774398, 'reg_alpha': 0.003010551689803488, 'reg_lambda': 1.620959954691804e-05, 'max_delta_step': 5}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  66%|██████▌   | 131/200 [01:35<00:48,  1.43it/s]

[I 2025-11-10 14:37:42,225] Trial 133 pruned.

Best trial: 4. Best value: 0.589591:  66%|██████▌   | 132/200 [01:35<00:38,  1.76it/s]

[I 2025-11-10 14:37:42,455] Trial 127 finished with value: 0.5492397660818714 and parameters: {'max_depth': 7, 'learning_rate': 0.11243073188079246, 'n_estimators': 634, 'subsample': 0.7786578001316793, 'colsample_bytree': 0.9411111056893986, 'min_child_weight': 2, 'gamma': 3.9500625980862005, 'reg_alpha': 0.0035341048236034907, 'reg_lambda': 1.5236371771814415e-05, 'max_delta_step': 5}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  66%|██████▋   | 133/200 [01:36<00:49,  1.34it/s]

[I 2025-11-10 14:37:43,638] Trial 132 finished with value: 0.5414619883040935 and parameters: {'max_depth': 7, 'learning_rate': 0.04031730707534534, 'n_estimators': 463, 'subsample': 0.9068160552435018, 'colsample_bytree': 0.8919132394904277, 'min_child_weight': 2, 'gamma': 3.7163789196030086, 'reg_alpha': 0.04362389975217035, 'reg_lambda': 2.480364798117353e-06, 'max_delta_step': 5}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  68%|██████▊   | 135/200 [01:37<00:42,  1.55it/s]

[I 2025-11-10 14:37:44,755] Trial 134 finished with value: 0.5267251461988304 and parameters: {'max_depth': 7, 'learning_rate': 0.05476656840145305, 'n_estimators': 349, 'subsample': 0.7956499716453336, 'colsample_bytree': 0.9048724040852116, 'min_child_weight': 2, 'gamma': 4.185773729294373, 'reg_alpha': 0.0015315137076687285, 'reg_lambda': 7.261252686552361e-06, 'max_delta_step': 5}. Best is trial 4 with value: 0.5895906432748539.
[I 2025-11-10 14:37:44,909] Trial 135 finished with value: 0.5322807017543859 and parameters: {'max_depth': 7, 'learning_rate': 0.05368192717642508, 'n_estimators': 348, 'subsample': 0.7962465658925943, 'colsample_bytree': 0.8918856622580531, 'min_child_weight': 2, 'gamma': 3.8336698653769496, 'reg_alpha': 6.233415635711723e-08, 'reg_lambda': 2.6552378517947903e-06, 'max_delta_step': 5}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  68%|██████▊   | 136/200 [01:38<00:36,  1.75it/s]

[I 2025-11-10 14:37:45,292] Trial 137 pruned.
[I 2025-11-10 14:37:45,368] Trial 131 finished with value: 0.5178362573099415 and parameters: {'max_depth': 7, 'learning_rate': 0.029050910704393154, 'n_estimators': 698, 'subsample': 0.9082232145776598, 'colsample_bytree': 0.9451127945911784, 'min_child_weight': 2, 'gamma': 1.7208385147624112, 'reg_alpha': 0.0007633517468336131, 'reg_lambda': 0.00031410309777451834, 'max_delta_step': 5}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  69%|██████▉   | 138/200 [01:38<00:23,  2.66it/s]

[I 2025-11-10 14:37:45,584] Trial 138 pruned.

Best trial: 4. Best value: 0.589591:  70%|███████   | 140/200 [01:39<00:19,  3.07it/s]

[I 2025-11-10 14:37:46,045] Trial 139 pruned.
[I 2025-11-10 14:37:46,171] Trial 140 pruned.

Best trial: 4. Best value: 0.589591:  70%|███████   | 141/200 [01:39<00:17,  3.39it/s]

[I 2025-11-10 14:37:46,390] Trial 136 finished with value: 0.5267251461988304 and parameters: {'max_depth': 7, 'learning_rate': 0.05209268546641217, 'n_estimators': 347, 'subsample': 0.7978671643581562, 'colsample_bytree': 0.872209534358613, 'min_child_weight': 2, 'gamma': 2.606040451916365, 'reg_alpha': 6.440816079830897e-08, 'reg_lambda': 0.00010494379940003503, 'max_delta_step': 5}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  71%|███████   | 142/200 [01:39<00:19,  2.91it/s]

[I 2025-11-10 14:37:46,853] Trial 143 pruned.

Best trial: 4. Best value: 0.589591:  72%|███████▏  | 143/200 [01:40<00:20,  2.81it/s]

[I 2025-11-10 14:37:47,246] Trial 142 pruned.

Best trial: 4. Best value: 0.589591:  72%|███████▏  | 144/200 [01:41<00:41,  1.35it/s]

[I 2025-11-10 14:37:48,939] Trial 141 finished with value: 0.5439766081871344 and parameters: {'max_depth': 6, 'learning_rate': 0.04480238905915296, 'n_estimators': 385, 'subsample': 0.7629496567510328, 'colsample_bytree': 0.9313438163331634, 'min_child_weight': 2, 'gamma': 2.6743949799336164, 'reg_alpha': 0.14998515894868922, 'reg_lambda': 0.00011748461467746353, 'max_delta_step': 6}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  72%|███████▎  | 145/200 [01:42<00:38,  1.41it/s]

[I 2025-11-10 14:37:49,553] Trial 146 finished with value: 0.5129239766081871 and parameters: {'max_depth': 8, 'learning_rate': 0.12340795358686286, 'n_estimators': 480, 'subsample': 0.8856413448258211, 'colsample_bytree': 0.8953822190747773, 'min_child_weight': 5, 'gamma': 0.5932028924850545, 'reg_alpha': 0.030359108934447272, 'reg_lambda': 0.002492142017455105, 'max_delta_step': 6}. Best is trial 4 with value: 0.5895906432748539.
[I 2025-11-10 14:37:49,640] Trial 144 finished with value: 0.5572514619883041 and parameters: {'max_depth': 8, 'learning_rate': 0.12260608568260313, 'n_estimators': 480, 'subsample': 0.8862112090841497, 'colsample_bytree': 0.7430606953037875, 'min_child_weight': 2, 'gamma': 3.520204046435393, 'reg_alpha': 0.009754334655317361, 'reg_lambda': 0.0013698224417970023, 'max_delta_step': 6}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  74%|███████▎  | 147/200 [01:44<00:39,  1.35it/s]

[I 2025-11-10 14:37:51,112] Trial 145 finished with value: 0.589298245614035 and parameters: {'max_depth': 8, 'learning_rate': 0.1532883518405091, 'n_estimators': 974, 'subsample': 0.8906664937744248, 'colsample_bytree': 0.691285146987224, 'min_child_weight': 5, 'gamma': 0.6164488573120602, 'reg_alpha': 0.004860898620777891, 'reg_lambda': 0.0024269304423663665, 'max_delta_step': 6}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  74%|███████▍  | 148/200 [01:45<00:42,  1.23it/s]

[I 2025-11-10 14:37:52,149] Trial 150 pruned.
[I 2025-11-10 14:37:52,170] Trial 147 finished with value: 0.5356140350877193 and parameters: {'max_depth': 8, 'learning_rate': 0.1284724079632857, 'n_estimators': 475, 'subsample': 0.8846587626112818, 'colsample_bytree': 0.7080183870853055, 'min_child_weight': 2, 'gamma': 3.5555667191181066, 'reg_alpha': 0.005037008658482, 'reg_lambda': 0.0013632018412065596, 'max_delta_step': 8}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  75%|███████▌  | 150/200 [01:46<00:41,  1.21it/s]

[I 2025-11-10 14:37:53,828] Trial 148 finished with value: 0.545906432748538 and parameters: {'max_depth': 8, 'learning_rate': 0.11714168191765147, 'n_estimators': 546, 'subsample': 0.8520390311147503, 'colsample_bytree': 0.8608808172833774, 'min_child_weight': 2, 'gamma': 3.534882101739495, 'reg_alpha': 0.004793020987142224, 'reg_lambda': 0.013436996615941011, 'max_delta_step': 8}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  76%|███████▌  | 151/200 [01:47<00:36,  1.35it/s]

[I 2025-11-10 14:37:54,294] Trial 153 pruned.

Best trial: 4. Best value: 0.589591:  76%|███████▌  | 152/200 [01:49<00:54,  1.13s/it]

[I 2025-11-10 14:37:56,597] Trial 154 finished with value: 0.5856725146198831 and parameters: {'max_depth': 8, 'learning_rate': 0.1432678026376167, 'n_estimators': 411, 'subsample': 0.9174829178351934, 'colsample_bytree': 0.716277595793626, 'min_child_weight': 5, 'gamma': 3.3764992291991107, 'reg_alpha': 0.0021435266253809807, 'reg_lambda': 2.0951433692724514e-05, 'max_delta_step': 5}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  76%|███████▋  | 153/200 [01:50<00:46,  1.01it/s]

[I 2025-11-10 14:37:57,193] Trial 149 finished with value: 0.4772514619883041 and parameters: {'max_depth': 8, 'learning_rate': 0.013581107244698987, 'n_estimators': 423, 'subsample': 0.8487623999591555, 'colsample_bytree': 0.710689766764627, 'min_child_weight': 1, 'gamma': 0.7450754841966929, 'reg_alpha': 0.0050988522493722694, 'reg_lambda': 2.1597978868569287e-05, 'max_delta_step': 7}. Best is trial 4 with value: 0.5895906432748539.

Best trial: 4. Best value: 0.589591:  77%|███████▋  | 154/200 [01:50<00:39,  1.15it/s]

[I 2025-11-10 14:37:57,739] Trial 156 pruned.

Best trial: 152. Best value: 0.611228:  78%|███████▊  | 155/200 [01:51<00:32,  1.36it/s]

[I 2025-11-10 14:37:58,119] Trial 152 finished with value: 0.6112280701754387 and parameters: {'max_depth': 7, 'learning_rate': 0.14079070374422856, 'n_estimators': 1012, 'subsample': 0.9194401519013389, 'colsample_bytree': 0.8577341737685967, 'min_child_weight': 5, 'gamma': 0.7750878641656996, 'reg_alpha': 0.001077572752671421, 'reg_lambda': 2.0608262433496195e-05, 'max_delta_step': 1}. Best is trial 152 with value: 0.6112280701754387.
[I 2025-11-10 14:37:58,155] Trial 151 finished with value: 0.5834502923976608 and parameters: {'max_depth': 8, 'learning_rate': 0.1443921161889689, 'n_estimators': 1077, 'subsample': 0.918322332831571, 'colsample_bytree': 0.7171558672608194, 'min_child_weight': 5, 'gamma': 0.49674994592784305, 'reg_alpha': 0.002441471520922656, 'reg_lambda': 0.0047960744029602745, 'max_delta_step': 8}. Best is trial 152 with value: 0.6112280701754387.

Best trial: 152. Best value: 0.611228:  78%|███████▊  | 157/200 [01:51<00:24,  1.78it/s]

[I 2025-11-10 14:37:58,823] Trial 157 pruned.

Best trial: 152. Best value: 0.611228:  79%|███████▉  | 158/200 [01:55<00:53,  1.28s/it]

[I 2025-11-10 14:38:02,347] Trial 155 finished with value: 0.5745614035087719 and parameters: {'max_depth': 8, 'learning_rate': 0.1495259275608719, 'n_estimators': 1059, 'subsample': 0.9219617627225929, 'colsample_bytree': 0.7140896164751793, 'min_child_weight': 5, 'gamma': 2.4457245325403703, 'reg_alpha': 0.0027365402344230495, 'reg_lambda': 1.9689631069565983e-05, 'max_delta_step': 5}. Best is trial 152 with value: 0.6112280701754387.

Best trial: 152. Best value: 0.611228:  80%|███████▉  | 159/200 [01:56<00:50,  1.23s/it]

[I 2025-11-10 14:38:03,429] Trial 159 finished with value: 0.5745614035087719 and parameters: {'max_depth': 8, 'learning_rate': 0.141001005170042, 'n_estimators': 1059, 'subsample': 0.9281581433803373, 'colsample_bytree': 0.7220678602958414, 'min_child_weight': 5, 'gamma': 0.5351450007899197, 'reg_alpha': 0.0005556661519637758, 'reg_lambda': 0.0036244979521160223, 'max_delta_step': 9}. Best is trial 152 with value: 0.6112280701754387.
[I 2025-11-10 14:38:03,531] Trial 158 finished with value: 0.5601169590643275 and parameters: {'max_depth': 7, 'learning_rate': 0.14423680051692928, 'n_estimators': 1108, 'subsample': 0.9294522022374362, 'colsample_bytree': 0.7211429062034944, 'min_child_weight': 5, 'gamma': 3.2094925763139446, 'reg_alpha': 0.0011385676396057961, 'reg_lambda': 3.2571721636344455e-05, 'max_delta_step': 1}. Best is trial 152 with value: 0.6112280701754387.

Best trial: 152. Best value: 0.611228:  80%|████████  | 161/200 [01:56<00:31,  1.22it/s]

[I 2025-11-10 14:38:03,955] Trial 160 finished with value: 0.5545614035087719 and parameters: {'max_depth': 9, 'learning_rate': 0.13820620344726778, 'n_estimators': 1044, 'subsample': 0.9172512795584764, 'colsample_bytree': 0.7626959209826883, 'min_child_weight': 5, 'gamma': 0.20171597691190446, 'reg_alpha': 0.001057580600121541, 'reg_lambda': 0.003452463665340639, 'max_delta_step': 9}. Best is trial 152 with value: 0.6112280701754387.

Best trial: 152. Best value: 0.611228:  81%|████████  | 162/200 [01:57<00:29,  1.28it/s]

[I 2025-11-10 14:38:04,603] Trial 163 pruned.

Best trial: 152. Best value: 0.611228:  82%|████████▏ | 163/200 [01:59<00:37,  1.00s/it]

[I 2025-11-10 14:38:06,260] Trial 164 pruned.

Best trial: 152. Best value: 0.611228:  82%|████████▏ | 164/200 [02:00<00:38,  1.07s/it]

[I 2025-11-10 14:38:07,529] Trial 166 pruned.

Best trial: 152. Best value: 0.611228:  82%|████████▎ | 165/200 [02:02<00:42,  1.21s/it]

[I 2025-11-10 14:38:09,124] Trial 161 finished with value: 0.5745614035087719 and parameters: {'max_depth': 8, 'learning_rate': 0.15334093537512333, 'n_estimators': 1065, 'subsample': 0.9543584226900539, 'colsample_bytree': 0.8040895975318549, 'min_child_weight': 5, 'gamma': 0.5488244959551523, 'reg_alpha': 0.0010597701426161177, 'reg_lambda': 0.004139198961392727, 'max_delta_step': 9}. Best is trial 152 with value: 0.6112280701754387.

Best trial: 152. Best value: 0.611228:  83%|████████▎ | 166/200 [02:03<00:39,  1.16s/it]

[I 2025-11-10 14:38:10,160] Trial 162 finished with value: 0.5892982456140351 and parameters: {'max_depth': 9, 'learning_rate': 0.15749662737959516, 'n_estimators': 1093, 'subsample': 0.9172945105810164, 'colsample_bytree': 0.7211715820274427, 'min_child_weight': 5, 'gamma': 0.274274453730677, 'reg_alpha': 0.0004227314316175202, 'reg_lambda': 0.003307355423878482, 'max_delta_step': 9}. Best is trial 152 with value: 0.6112280701754387.

Best trial: 152. Best value: 0.611228:  84%|████████▎ | 167/200 [02:04<00:38,  1.17s/it]

[I 2025-11-10 14:38:11,369] Trial 165 finished with value: 0.5948538011695906 and parameters: {'max_depth': 8, 'learning_rate': 0.1770395789426856, 'n_estimators': 1087, 'subsample': 0.9369004544998301, 'colsample_bytree': 0.7154789334461376, 'min_child_weight': 5, 'gamma': 0.3300129313398623, 'reg_alpha': 0.0008888091495929162, 'reg_lambda': 0.012979609796381077, 'max_delta_step': 8}. Best is trial 152 with value: 0.6112280701754387.

Best trial: 152. Best value: 0.611228:  84%|████████▍ | 168/200 [02:06<00:46,  1.45s/it]

[I 2025-11-10 14:38:13,479] Trial 167 finished with value: 0.5948538011695907 and parameters: {'max_depth': 8, 'learning_rate': 0.150462773437248, 'n_estimators': 1181, 'subsample': 0.9199741800652643, 'colsample_bytree': 0.7364923048569539, 'min_child_weight': 5, 'gamma': 0.3582709595777711, 'reg_alpha': 0.0010606524252376084, 'reg_lambda': 0.010547870563197129, 'max_delta_step': 1}. Best is trial 152 with value: 0.6112280701754387.

Best trial: 152. Best value: 0.611228:  84%|████████▍ | 169/200 [02:07<00:42,  1.36s/it]

[I 2025-11-10 14:38:14,635] Trial 168 finished with value: 0.5537426900584795 and parameters: {'max_depth': 8, 'learning_rate': 0.1691047921437485, 'n_estimators': 1070, 'subsample': 0.9680222676433109, 'colsample_bytree': 0.8006559914454622, 'min_child_weight': 5, 'gamma': 0.4136181084006987, 'reg_alpha': 0.0008078499357391788, 'reg_lambda': 0.012004067314028574, 'max_delta_step': 9}. Best is trial 152 with value: 0.6112280701754387.

Best trial: 152. Best value: 0.611228:  85%|████████▌ | 170/200 [02:07<00:31,  1.05s/it]

[I 2025-11-10 14:38:14,954] Trial 171 pruned.

Best trial: 152. Best value: 0.611228:  86%|████████▌ | 171/200 [02:08<00:28,  1.00it/s]

[I 2025-11-10 14:38:15,814] Trial 172 pruned.

Best trial: 152. Best value: 0.611228:  86%|████████▌ | 172/200 [02:09<00:22,  1.25it/s]

[I 2025-11-10 14:38:16,156] Trial 173 pruned.

Best trial: 169. Best value: 0.631813:  86%|████████▋ | 173/200 [02:09<00:17,  1.54it/s]

[I 2025-11-10 14:38:16,439] Trial 169 finished with value: 0.631812865497076 and parameters: {'max_depth': 9, 'learning_rate': 0.17702423054730684, 'n_estimators': 1166, 'subsample': 0.9165471528853015, 'colsample_bytree': 0.8056447896092562, 'min_child_weight': 5, 'gamma': 0.402831012972312, 'reg_alpha': 0.0002390769331865595, 'reg_lambda': 0.008743507637465743, 'max_delta_step': 9}. Best is trial 169 with value: 0.631812865497076.

Best trial: 169. Best value: 0.631813:  87%|████████▋ | 174/200 [02:09<00:15,  1.65it/s]

[I 2025-11-10 14:38:16,955] Trial 170 finished with value: 0.5245614035087719 and parameters: {'max_depth': 8, 'learning_rate': 0.17625219554838067, 'n_estimators': 1064, 'subsample': 0.9654452908979291, 'colsample_bytree': 0.8173649418655431, 'min_child_weight': 5, 'gamma': 0.3644768566143449, 'reg_alpha': 0.0008253113662362011, 'reg_lambda': 0.015109144554734747, 'max_delta_step': 9}. Best is trial 169 with value: 0.631812865497076.

Best trial: 169. Best value: 0.631813:  88%|████████▊ | 175/200 [02:10<00:17,  1.40it/s]

[I 2025-11-10 14:38:17,915] Trial 176 pruned.

Best trial: 169. Best value: 0.631813:  88%|████████▊ | 176/200 [02:13<00:33,  1.41s/it]

[I 2025-11-10 14:38:20,958] Trial 174 finished with value: 0.5798245614035087 and parameters: {'max_depth': 8, 'learning_rate': 0.15151734265537034, 'n_estimators': 1008, 'subsample': 0.9253563518429128, 'colsample_bytree': 0.6913751791938326, 'min_child_weight': 5, 'gamma': 0.09980478344730087, 'reg_alpha': 0.00018978620355958531, 'reg_lambda': 0.004487182866244521, 'max_delta_step': 10}. Best is trial 169 with value: 0.631812865497076.

Best trial: 169. Best value: 0.631813:  88%|████████▊ | 177/200 [02:14<00:26,  1.15s/it]

[I 2025-11-10 14:38:21,489] Trial 175 finished with value: 0.5951461988304093 and parameters: {'max_depth': 8, 'learning_rate': 0.15368908698690717, 'n_estimators': 1021, 'subsample': 0.9403981230187685, 'colsample_bytree': 0.6941064268322024, 'min_child_weight': 5, 'gamma': 0.48642742796818617, 'reg_alpha': 0.0006937353851197596, 'reg_lambda': 0.004343281122144859, 'max_delta_step': 8}. Best is trial 169 with value: 0.631812865497076.

Best trial: 177. Best value: 0.657368:  89%|████████▉ | 178/200 [02:14<00:19,  1.15it/s]

[I 2025-11-10 14:38:21,705] Trial 177 finished with value: 0.6573684210526316 and parameters: {'max_depth': 9, 'learning_rate': 0.15281097610018635, 'n_estimators': 1008, 'subsample': 0.9393350744952598, 'colsample_bytree': 0.7150065835231102, 'min_child_weight': 5, 'gamma': 0.009331632962451486, 'reg_alpha': 0.00017735173789045256, 'reg_lambda': 0.004214908567749089, 'max_delta_step': 10}. Best is trial 177 with value: 0.6573684210526316.

Best trial: 177. Best value: 0.657368:  90%|████████▉ | 179/200 [02:15<00:15,  1.36it/s]

[I 2025-11-10 14:38:22,131] Trial 179 pruned.

Best trial: 177. Best value: 0.657368:  90%|█████████ | 180/200 [02:15<00:13,  1.51it/s]

[I 2025-11-10 14:38:22,624] Trial 180 pruned.

Best trial: 177. Best value: 0.657368:  90%|█████████ | 181/200 [02:15<00:10,  1.85it/s]

[I 2025-11-10 14:38:22,882] Trial 178 finished with value: 0.5248538011695907 and parameters: {'max_depth': 8, 'learning_rate': 0.19502388622354128, 'n_estimators': 1010, 'subsample': 0.9235798094825862, 'colsample_bytree': 0.7124146929598806, 'min_child_weight': 5, 'gamma': 0.48307408915317596, 'reg_alpha': 0.0005394838418628276, 'reg_lambda': 0.05623643096508014, 'max_delta_step': 8}. Best is trial 177 with value: 0.6573684210526316.

Best trial: 177. Best value: 0.657368:  91%|█████████ | 182/200 [02:16<00:11,  1.62it/s]

[I 2025-11-10 14:38:23,678] Trial 183 pruned.

Best trial: 177. Best value: 0.657368:  92%|█████████▏| 183/200 [02:19<00:21,  1.26s/it]

[I 2025-11-10 14:38:26,425] Trial 181 finished with value: 0.5384795321637427 and parameters: {'max_depth': 10, 'learning_rate': 0.23019750306378223, 'n_estimators': 1006, 'subsample': 0.9247880919503648, 'colsample_bytree': 0.835771443323546, 'min_child_weight': 5, 'gamma': 0.16497527714271173, 'reg_alpha': 0.00016507746729813464, 'reg_lambda': 0.008528825555572425, 'max_delta_step': 10}. Best is trial 177 with value: 0.6573684210526316.

Best trial: 177. Best value: 0.657368:  92%|█████████▏| 184/200 [02:19<00:16,  1.04s/it]

[I 2025-11-10 14:38:26,949] Trial 182 finished with value: 0.589298245614035 and parameters: {'max_depth': 10, 'learning_rate': 0.19863247445738524, 'n_estimators': 1019, 'subsample': 0.9540564319550855, 'colsample_bytree': 0.7075966248622904, 'min_child_weight': 5, 'gamma': 0.48336300496512985, 'reg_alpha': 6.818131349740511e-05, 'reg_lambda': 0.003828343434397959, 'max_delta_step': 10}. Best is trial 177 with value: 0.6573684210526316.

Best trial: 177. Best value: 0.657368:  92%|█████████▎| 185/200 [02:20<00:13,  1.13it/s]

[I 2025-11-10 14:38:27,470] Trial 186 pruned.

Best trial: 177. Best value: 0.657368:  93%|█████████▎| 186/200 [02:20<00:10,  1.38it/s]

[I 2025-11-10 14:38:27,833] Trial 184 finished with value: 0.5926315789473684 and parameters: {'max_depth': 9, 'learning_rate': 0.13754903827700837, 'n_estimators': 1084, 'subsample': 0.9312007057902204, 'colsample_bytree': 0.700446052971146, 'min_child_weight': 5, 'gamma': 0.23836931691226793, 'reg_alpha': 7.91777371110816e-05, 'reg_lambda': 0.003676759180852843, 'max_delta_step': 10}. Best is trial 177 with value: 0.6573684210526316.

Best trial: 177. Best value: 0.657368:  94%|█████████▎| 187/200 [02:21<00:08,  1.53it/s]

[I 2025-11-10 14:38:28,313] Trial 187 pruned.

Best trial: 177. Best value: 0.657368:  94%|█████████▍| 189/200 [02:21<00:05,  2.18it/s]

[I 2025-11-10 14:38:28,800] Trial 188 pruned.
[I 2025-11-10 14:38:28,927] Trial 185 finished with value: 0.5959649122807018 and parameters: {'max_depth': 9, 'learning_rate': 0.1374042201906597, 'n_estimators': 1083, 'subsample': 0.9325590466755669, 'colsample_bytree': 0.7009785522202736, 'min_child_weight': 5, 'gamma': 0.6476603789654096, 'reg_alpha': 0.00027115515916267764, 'reg_lambda': 0.0018386099723001759, 'max_delta_step': 10}. Best is trial 177 with value: 0.6573684210526316.

Best trial: 177. Best value: 0.657368:  95%|█████████▌| 190/200 [02:22<00:04,  2.34it/s]

[I 2025-11-10 14:38:29,282] Trial 189 pruned.

Best trial: 177. Best value: 0.657368:  96%|█████████▌| 191/200 [02:23<00:05,  1.78it/s]

[I 2025-11-10 14:38:30,148] Trial 192 pruned.

Best trial: 177. Best value: 0.657368:  96%|█████████▌| 192/200 [02:23<00:04,  1.84it/s]

[I 2025-11-10 14:38:30,648] Trial 193 pruned.

Best trial: 177. Best value: 0.657368:  96%|█████████▋| 193/200 [02:24<00:04,  1.52it/s]

[I 2025-11-10 14:38:31,572] Trial 194 pruned.

Best trial: 177. Best value: 0.657368:  97%|█████████▋| 194/200 [02:27<00:07,  1.25s/it]

[I 2025-11-10 14:38:34,209] Trial 190 finished with value: 0.5970760233918128 and parameters: {'max_depth': 10, 'learning_rate': 0.156696957163361, 'n_estimators': 1097, 'subsample': 0.9325791340383136, 'colsample_bytree': 0.7201690457766752, 'min_child_weight': 5, 'gamma': 0.28750694471059757, 'reg_alpha': 4.1437980009403466e-05, 'reg_lambda': 0.005410950410384698, 'max_delta_step': 10}. Best is trial 177 with value: 0.6573684210526316.

Best trial: 177. Best value: 0.657368:  98%|█████████▊| 195/200 [02:27<00:04,  1.04it/s]

[I 2025-11-10 14:38:34,495] Trial 191 finished with value: 0.5862573099415205 and parameters: {'max_depth': 9, 'learning_rate': 0.15310627289231682, 'n_estimators': 1078, 'subsample': 0.9090668070198329, 'colsample_bytree': 0.7215880758445723, 'min_child_weight': 5, 'gamma': 0.290950290526655, 'reg_alpha': 0.0004809928136344295, 'reg_lambda': 0.006672132956389649, 'max_delta_step': 10}. Best is trial 177 with value: 0.6573684210526316.

Best trial: 177. Best value: 0.657368:  98%|█████████▊| 196/200 [02:28<00:03,  1.10it/s]

[I 2025-11-10 14:38:35,293] Trial 197 pruned.

Best trial: 177. Best value: 0.657368:  98%|█████████▊| 197/200 [02:28<00:02,  1.30it/s]

[I 2025-11-10 14:38:35,733] Trial 198 pruned.

Best trial: 177. Best value: 0.657368:  99%|█████████▉| 198/200 [02:29<00:01,  1.42it/s]

[I 2025-11-10 14:38:36,280] Trial 195 finished with value: 0.5912280701754385 and parameters: {'max_depth': 9, 'learning_rate': 0.15622067615738516, 'n_estimators': 1050, 'subsample': 0.9328413788184357, 'colsample_bytree': 0.6818374278108112, 'min_child_weight': 5, 'gamma': 0.5942482483489242, 'reg_alpha': 9.306069255206267e-05, 'reg_lambda': 0.004231827565171528, 'max_delta_step': 10}. Best is trial 177 with value: 0.6573684210526316.

Best trial: 177. Best value: 0.657368: 100%|██████████| 200/200 [02:29<00:00,  1.34it/s]

[I 2025-11-10 14:38:36,587] Trial 199 pruned.
[I 2025-11-10 14:38:36,644] Trial 196 finished with value: 0.5690058479532164 and parameters: {'max_depth': 8, 'learning_rate': 0.15373891162677603, 'n_estimators': 976, 'subsample': 0.9532776427284945, 'colsample_bytree': 0.7394044696687277, 'min_child_weight': 5, 'gamma': 0.41455462171221946, 'reg_alpha': 2.067164292185469e-05, 'reg_lambda': 0.006976960490984614, 'max_delta_step': 10}. Best is trial 177 with value: 0.6573684210526316.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\utils\_plotting.py:28: RuntimeWarning:

More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.

[I 2025-11-10 14:38:37,774] A new study created in memory with name: 17_1_balanced_accuracy
Best trial: 1. Best value: 0.5:   0%|          | 1/200 [00:02<08:22,  2.52s/it]

[I 2025-11-10 14:38:40,293] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1230203933933827, 'n_estimators': 510, 'subsample': 0.6655143634265654, 'colsample_bytree': 0.9568889341654598, 'min_child_weight': 7, 'gamma': 2.496071572378339, 'reg_alpha': 0.024061433460733778, 'reg_lambda': 0.00016069688499533805, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   1%|          | 2/200 [00:03<04:37,  1.40s/it]

[I 2025-11-10 14:38:40,905] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05054532434053242, 'n_estimators': 650, 'subsample': 0.5270880330369608, 'colsample_bytree': 0.7991229959737425, 'min_child_weight': 10, 'gamma': 0.5238474960163403, 'reg_alpha': 0.0006914855474812082, 'reg_lambda': 3.813912417344552e-07, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   2%|▏         | 4/200 [00:06<04:30,  1.38s/it]

[I 2025-11-10 14:38:44,012] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.06524077550485755, 'n_estimators': 1237, 'subsample': 0.574970851846722, 'colsample_bytree': 0.875930608767573, 'min_child_weight': 7, 'gamma': 4.489084063079319, 'reg_alpha': 0.05425929087859957, 'reg_lambda': 0.00012567955285995862, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.
[I 2025-11-10 14:38:44,160] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.17221237724618912, 'n_estimators': 1295, 'subsample': 0.5072567801057967, 'colsample_bytree': 0.7320045341034003, 'min_child_weight': 7, 'gamma': 3.0531758541051373, 'reg_alpha': 2.6751218381290265, 'reg_lambda': 0.0002930312963575058, 'max_delta_step': 1}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   2%|▎         | 5/200 [00:06<03:30,  1.08s/it]

[I 2025-11-10 14:38:44,715] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.11391994390723706, 'n_estimators': 915, 'subsample': 0.9816966488520291, 'colsample_bytree': 0.5324537200708738, 'min_child_weight': 6, 'gamma': 0.15481258245855112, 'reg_alpha': 0.00016659953554306535, 'reg_lambda': 1.1317898857853679e-08, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   3%|▎         | 6/200 [00:08<03:49,  1.18s/it]

[I 2025-11-10 14:38:46,100] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.21759357601137921, 'n_estimators': 1059, 'subsample': 0.8811706724842845, 'colsample_bytree': 0.7223052237950891, 'min_child_weight': 10, 'gamma': 1.340785021785082, 'reg_alpha': 0.0026977203307232255, 'reg_lambda': 0.18137756724396667, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 7. Best value: 0.526199:   4%|▎         | 7/200 [00:08<02:59,  1.08it/s]

[I 2025-11-10 14:38:46,509] Trial 7 finished with value: 0.5261988304093568 and parameters: {'max_depth': 7, 'learning_rate': 0.016717154601701607, 'n_estimators': 437, 'subsample': 0.6539715864920487, 'colsample_bytree': 0.9959423650663202, 'min_child_weight': 4, 'gamma': 2.004196485499852, 'reg_alpha': 2.0237399527735137e-05, 'reg_lambda': 1.9605701704238405e-05, 'max_delta_step': 7}. Best is trial 7 with value: 0.5261988304093568.

Best trial: 7. Best value: 0.526199:   4%|▍         | 8/200 [00:08<02:16,  1.40it/s]

[I 2025-11-10 14:38:46,757] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.2071703860568861, 'n_estimators': 592, 'subsample': 0.6698428778716861, 'colsample_bytree': 0.5587954175946339, 'min_child_weight': 10, 'gamma': 0.303935542741961, 'reg_alpha': 9.084361559605158, 'reg_lambda': 0.0056839259837134426, 'max_delta_step': 0}. Best is trial 7 with value: 0.5261988304093568.

Best trial: 7. Best value: 0.526199:   4%|▍         | 9/200 [00:11<03:40,  1.16s/it]

[I 2025-11-10 14:38:48,888] Trial 11 finished with value: 0.45064327485380123 and parameters: {'max_depth': 3, 'learning_rate': 0.04469256911943187, 'n_estimators': 262, 'subsample': 0.979843676385239, 'colsample_bytree': 0.7059240963384055, 'min_child_weight': 3, 'gamma': 1.0256474026327718, 'reg_alpha': 0.0018992874810277996, 'reg_lambda': 1.173374453135738e-06, 'max_delta_step': 9}. Best is trial 7 with value: 0.5261988304093568.

Best trial: 7. Best value: 0.526199:   5%|▌         | 10/200 [00:12<04:04,  1.29s/it]

[I 2025-11-10 14:38:50,462] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.2746661821036929, 'n_estimators': 1192, 'subsample': 0.8859148510081798, 'colsample_bytree': 0.796340314081257, 'min_child_weight': 9, 'gamma': 1.0501251521798016, 'reg_alpha': 1.622350372464236e-08, 'reg_lambda': 6.030148592794939e-07, 'max_delta_step': 6}. Best is trial 7 with value: 0.5261988304093568.

Best trial: 7. Best value: 0.526199:   6%|▌         | 11/200 [00:13<03:34,  1.13s/it]

[I 2025-11-10 14:38:51,257] Trial 13 pruned.

Best trial: 7. Best value: 0.526199:   6%|▌         | 12/200 [00:14<03:06,  1.01it/s]

[I 2025-11-10 14:38:51,911] Trial 14 pruned.

Best trial: 7. Best value: 0.526199:   6%|▋         | 13/200 [00:14<02:32,  1.23it/s]

[I 2025-11-10 14:38:52,330] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.012824710128073631, 'n_estimators': 1282, 'subsample': 0.6216653557115721, 'colsample_bytree': 0.5488266166611049, 'min_child_weight': 10, 'gamma': 4.804533187618124, 'reg_alpha': 3.0432587286055544e-07, 'reg_lambda': 0.03684354230063208, 'max_delta_step': 0}. Best is trial 7 with value: 0.5261988304093568.

Best trial: 7. Best value: 0.526199:   7%|▋         | 14/200 [00:15<02:20,  1.33it/s]

[I 2025-11-10 14:38:52,940] Trial 15 pruned.

Best trial: 7. Best value: 0.526199:   8%|▊         | 15/200 [00:15<02:08,  1.44it/s]

[I 2025-11-10 14:38:53,501] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.012504484285335607, 'n_estimators': 858, 'subsample': 0.5872935346875958, 'colsample_bytree': 0.520152701709771, 'min_child_weight': 5, 'gamma': 1.5981878275164463, 'reg_alpha': 0.00012093053858419208, 'reg_lambda': 1.0378864459938297e-05, 'max_delta_step': 3}. Best is trial 7 with value: 0.5261988304093568.

Best trial: 7. Best value: 0.526199:   8%|▊         | 17/200 [00:17<02:15,  1.35it/s]

[I 2025-11-10 14:38:55,214] Trial 9 finished with value: 0.47257309941520476 and parameters: {'max_depth': 4, 'learning_rate': 0.012366197079281788, 'n_estimators': 1227, 'subsample': 0.66825881768688, 'colsample_bytree': 0.6193932342712829, 'min_child_weight': 2, 'gamma': 1.260895963455742, 'reg_alpha': 4.253686345999728e-06, 'reg_lambda': 0.6674066385768966, 'max_delta_step': 3}. Best is trial 7 with value: 0.5261988304093568.
[I 2025-11-10 14:38:55,351] Trial 17 finished with value: 0.46456140350877195 and parameters: {'max_depth': 7, 'learning_rate': 0.045804595734510845, 'n_estimators': 446, 'subsample': 0.7276151275227587, 'colsample_bytree': 0.8921889030354118, 'min_child_weight': 4, 'gamma': 1.7753850969928069, 'reg_alpha': 6.623548425291062e-05, 'reg_lambda': 2.0051627990561657e-05, 'max_delta_step': 3}. Best is trial 7 with value: 0.5261988304093568.

Best trial: 7. Best value: 0.526199:   9%|▉         | 18/200 [00:17<01:53,  1.61it/s]

[I 2025-11-10 14:38:55,696] Trial 18 finished with value: 0.5087134502923977 and parameters: {'max_depth': 7, 'learning_rate': 0.04875421899261019, 'n_estimators': 426, 'subsample': 0.730379006838635, 'colsample_bytree': 0.8966963829785579, 'min_child_weight': 4, 'gamma': 0.49086174802706184, 'reg_alpha': 2.9316076339779965e-05, 'reg_lambda': 1.6806858294552312e-07, 'max_delta_step': 7}. Best is trial 7 with value: 0.5261988304093568.

Best trial: 7. Best value: 0.526199:  10%|▉         | 19/200 [00:19<02:48,  1.07it/s]

[I 2025-11-10 14:38:57,353] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.023256184902334002, 'n_estimators': 401, 'subsample': 0.7648888409043775, 'colsample_bytree': 0.7971562107932414, 'min_child_weight': 8, 'gamma': 0.5799357703158976, 'reg_alpha': 0.0027882518827910627, 'reg_lambda': 1.0227574754550034e-07, 'max_delta_step': 8}. Best is trial 7 with value: 0.5261988304093568.
[I 2025-11-10 14:38:57,432] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.05160891068930525, 'n_estimators': 417, 'subsample': 0.7754484277481324, 'colsample_bytree': 0.879323906880545, 'min_child_weight': 8, 'gamma': 0.4379526706433574, 'reg_alpha': 3.7238753047085414e-05, 'reg_lambda': 1.6342633637541188e-07, 'max_delta_step': 7}. Best is trial 7 with value: 0.5261988304093568.

Best trial: 7. Best value: 0.526199:  10%|█         | 21/200 [00:19<01:43,  1.74it/s]

[I 2025-11-10 14:38:57,667] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02583524325490359, 'n_estimators': 403, 'subsample': 0.7659202446788198, 'colsample_bytree': 0.9339501260799435, 'min_child_weight': 5, 'gamma': 3.169467678059895, 'reg_alpha': 6.021233104381373e-08, 'reg_lambda': 9.079114662990861e-08, 'max_delta_step': 8}. Best is trial 7 with value: 0.5261988304093568.

Best trial: 7. Best value: 0.526199:  11%|█         | 22/200 [00:20<01:45,  1.69it/s]

[I 2025-11-10 14:38:58,316] Trial 16 finished with value: 0.5181286549707603 and parameters: {'max_depth': 7, 'learning_rate': 0.028375285680379586, 'n_estimators': 774, 'subsample': 0.7494347208442316, 'colsample_bytree': 0.622731934631817, 'min_child_weight': 1, 'gamma': 3.585849816863581, 'reg_alpha': 3.695786368914947e-05, 'reg_lambda': 1.8376797894393022e-08, 'max_delta_step': 7}. Best is trial 7 with value: 0.5261988304093568.

Best trial: 7. Best value: 0.526199:  12%|█▏        | 23/200 [00:21<02:02,  1.45it/s]

[I 2025-11-10 14:38:59,288] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.03196224037100639, 'n_estimators': 345, 'subsample': 0.8260587273792458, 'colsample_bytree': 0.9315407000272203, 'min_child_weight': 5, 'gamma': 3.5235297023854164, 'reg_alpha': 8.776086757964767e-08, 'reg_lambda': 1.0585580369470921e-05, 'max_delta_step': 7}. Best is trial 7 with value: 0.5261988304093568.

Best trial: 7. Best value: 0.526199:  12%|█▏        | 24/200 [00:23<03:08,  1.07s/it]

[I 2025-11-10 14:39:01,375] Trial 24 finished with value: 0.46649122807017546 and parameters: {'max_depth': 6, 'learning_rate': 0.07615275466813887, 'n_estimators': 721, 'subsample': 0.7081484731652496, 'colsample_bytree': 0.9982788935738082, 'min_child_weight': 4, 'gamma': 0.0002463387495225122, 'reg_alpha': 0.000901847962825574, 'reg_lambda': 8.813784354493478e-06, 'max_delta_step': 5}. Best is trial 7 with value: 0.5261988304093568.

Best trial: 7. Best value: 0.526199:  12%|█▎        | 25/200 [00:26<04:14,  1.45s/it]

[I 2025-11-10 14:39:03,814] Trial 23 finished with value: 0.4866666666666667 and parameters: {'max_depth': 8, 'learning_rate': 0.08128209036780766, 'n_estimators': 1463, 'subsample': 0.8306859196996007, 'colsample_bytree': 0.9310979587932329, 'min_child_weight': 5, 'gamma': 3.438344557932802, 'reg_alpha': 7.599996791900473e-08, 'reg_lambda': 0.0025997021387532664, 'max_delta_step': 6}. Best is trial 7 with value: 0.5261988304093568.

Best trial: 25. Best value: 0.529825:  13%|█▎        | 26/200 [00:28<05:03,  1.75s/it]

[I 2025-11-10 14:39:06,290] Trial 25 finished with value: 0.5298245614035089 and parameters: {'max_depth': 8, 'learning_rate': 0.03587886922481094, 'n_estimators': 1007, 'subsample': 0.7240749686765052, 'colsample_bytree': 0.9953664116504055, 'min_child_weight': 1, 'gamma': 4.055029230949864, 'reg_alpha': 8.036938221779755e-06, 'reg_lambda': 1.4499727473047921e-05, 'max_delta_step': 6}. Best is trial 25 with value: 0.5298245614035089.

Best trial: 28. Best value: 0.54924:  14%|█▎        | 27/200 [00:33<07:53,  2.74s/it]

[I 2025-11-10 14:39:11,456] Trial 28 finished with value: 0.5492397660818713 and parameters: {'max_depth': 7, 'learning_rate': 0.019287984807251427, 'n_estimators': 990, 'subsample': 0.7117290813058995, 'colsample_bytree': 0.6098609056469422, 'min_child_weight': 1, 'gamma': 4.163923021185333, 'reg_alpha': 9.877711011996169e-06, 'reg_lambda': 3.3062389582402395e-08, 'max_delta_step': 8}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  14%|█▍        | 28/200 [00:34<06:01,  2.10s/it]

[I 2025-11-10 14:39:12,023] Trial 27 finished with value: 0.5220467836257311 and parameters: {'max_depth': 7, 'learning_rate': 0.017486372468133525, 'n_estimators': 1484, 'subsample': 0.8270550370966647, 'colsample_bytree': 0.6050787215090148, 'min_child_weight': 1, 'gamma': 4.197442831794092, 'reg_alpha': 7.925908622962123e-06, 'reg_lambda': 0.004270682501208427, 'max_delta_step': 6}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  14%|█▍        | 29/200 [00:34<04:33,  1.60s/it]

[I 2025-11-10 14:39:12,430] Trial 26 finished with value: 0.5076023391812866 and parameters: {'max_depth': 6, 'learning_rate': 0.018235667654377084, 'n_estimators': 1478, 'subsample': 0.7111981749684709, 'colsample_bytree': 0.9917985101929156, 'min_child_weight': 1, 'gamma': 4.16865992528521, 'reg_alpha': 8.471129316454764e-06, 'reg_lambda': 2.7113805969554577e-08, 'max_delta_step': 5}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  15%|█▌        | 30/200 [00:35<03:31,  1.24s/it]

[I 2025-11-10 14:39:12,822] Trial 30 pruned.

Best trial: 28. Best value: 0.54924:  16%|█▌        | 31/200 [00:36<03:50,  1.36s/it]

[I 2025-11-10 14:39:14,469] Trial 29 finished with value: 0.5239766081871345 and parameters: {'max_depth': 9, 'learning_rate': 0.01813602617951713, 'n_estimators': 995, 'subsample': 0.6950000535065449, 'colsample_bytree': 0.6325647781202751, 'min_child_weight': 1, 'gamma': 4.050116014831466, 'reg_alpha': 3.7464601023010486e-06, 'reg_lambda': 0.0016390950929535731, 'max_delta_step': 5}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  16%|█▌        | 32/200 [00:41<06:29,  2.32s/it]

[I 2025-11-10 14:39:19,040] Trial 33 finished with value: 0.5364912280701755 and parameters: {'max_depth': 8, 'learning_rate': 0.03644490901551291, 'n_estimators': 1047, 'subsample': 0.552513497258561, 'colsample_bytree': 0.6623413471290551, 'min_child_weight': 3, 'gamma': 2.0970127790921707, 'reg_alpha': 5.22065887454737e-07, 'reg_lambda': 5.467516724831415e-05, 'max_delta_step': 8}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  16%|█▋        | 33/200 [00:41<04:46,  1.72s/it]

[I 2025-11-10 14:39:19,337] Trial 31 finished with value: 0.5367836257309941 and parameters: {'max_depth': 9, 'learning_rate': 0.03733555732510733, 'n_estimators': 1079, 'subsample': 0.6359471323220921, 'colsample_bytree': 0.6587655183626753, 'min_child_weight': 2, 'gamma': 4.203133374836783, 'reg_alpha': 7.507538389094053e-07, 'reg_lambda': 4.800967131644713e-05, 'max_delta_step': 8}. Best is trial 28 with value: 0.5492397660818713.
[I 2025-11-10 14:39:19,404] Trial 32 finished with value: 0.5184210526315789 and parameters: {'max_depth': 9, 'learning_rate': 0.037093751480754826, 'n_estimators': 1004, 'subsample': 0.6318604422171945, 'colsample_bytree': 0.6951019513889524, 'min_child_weight': 2, 'gamma': 2.076786283214161, 'reg_alpha': 1.021892509707385e-06, 'reg_lambda': 4.759189074572093e-05, 'max_delta_step': 8}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  18%|█▊        | 35/200 [00:42<03:13,  1.18s/it]

[I 2025-11-10 14:39:20,417] Trial 37 pruned.

Best trial: 28. Best value: 0.54924:  18%|█▊        | 36/200 [00:43<02:41,  1.01it/s]

[I 2025-11-10 14:39:20,831] Trial 34 finished with value: 0.5417543859649123 and parameters: {'max_depth': 9, 'learning_rate': 0.03511607650930495, 'n_estimators': 1051, 'subsample': 0.6827973386172362, 'colsample_bytree': 0.6678513574035592, 'min_child_weight': 3, 'gamma': 2.1562790773316802, 'reg_alpha': 8.961488795789524e-07, 'reg_lambda': 3.2763435638262813e-05, 'max_delta_step': 8}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  18%|█▊        | 37/200 [00:46<04:42,  1.73s/it]

[I 2025-11-10 14:39:24,671] Trial 35 finished with value: 0.5161988304093568 and parameters: {'max_depth': 8, 'learning_rate': 0.03449494783886016, 'n_estimators': 1101, 'subsample': 0.5780682223842242, 'colsample_bytree': 0.6718100541017866, 'min_child_weight': 3, 'gamma': 2.05158250655312, 'reg_alpha': 6.262621524041448e-07, 'reg_lambda': 5.301440142222874e-05, 'max_delta_step': 8}. Best is trial 28 with value: 0.5492397660818713.
[I 2025-11-10 14:39:24,687] Trial 36 finished with value: 0.5164912280701753 and parameters: {'max_depth': 8, 'learning_rate': 0.03605251865696597, 'n_estimators': 1092, 'subsample': 0.5449118478837223, 'colsample_bytree': 0.6926809430390208, 'min_child_weight': 3, 'gamma': 4.979831873857211, 'reg_alpha': 1.1087787347389223e-06, 'reg_lambda': 7.369011549554701e-05, 'max_delta_step': 9}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  20%|█▉        | 39/200 [00:47<03:09,  1.18s/it]

[I 2025-11-10 14:39:25,541] Trial 40 pruned.

Best trial: 28. Best value: 0.54924:  20%|██        | 40/200 [00:48<02:51,  1.07s/it]

[I 2025-11-10 14:39:26,279] Trial 38 finished with value: 0.5139766081871345 and parameters: {'max_depth': 8, 'learning_rate': 0.0364433244972051, 'n_estimators': 1107, 'subsample': 0.5535683222976613, 'colsample_bytree': 0.7534819464745821, 'min_child_weight': 3, 'gamma': 2.8360330129650926, 'reg_alpha': 1.8316823119110483e-07, 'reg_lambda': 8.762573916023657e-05, 'max_delta_step': 9}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  20%|██        | 41/200 [00:48<02:15,  1.18it/s]

[I 2025-11-10 14:39:26,467] Trial 39 finished with value: 0.5473099415204679 and parameters: {'max_depth': 10, 'learning_rate': 0.06252378054283549, 'n_estimators': 1121, 'subsample': 0.552047434588157, 'colsample_bytree': 0.5819558573747466, 'min_child_weight': 3, 'gamma': 2.676209030080145, 'reg_alpha': 1.9916908386468007e-07, 'reg_lambda': 2.6257803391126027e-06, 'max_delta_step': 10}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  21%|██        | 42/200 [00:51<03:34,  1.36s/it]

[I 2025-11-10 14:39:29,243] Trial 43 pruned.

Best trial: 28. Best value: 0.54924:  22%|██▏       | 43/200 [00:51<02:43,  1.04s/it]

[I 2025-11-10 14:39:29,437] Trial 41 finished with value: 0.45397660818713453 and parameters: {'max_depth': 10, 'learning_rate': 0.06528562871176558, 'n_estimators': 839, 'subsample': 0.6102866044456496, 'colsample_bytree': 0.579616568570451, 'min_child_weight': 2, 'gamma': 2.697537168386249, 'reg_alpha': 2.389073733313143e-07, 'reg_lambda': 0.0004574214125134607, 'max_delta_step': 10}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  22%|██▏       | 44/200 [00:52<02:44,  1.05s/it]

[I 2025-11-10 14:39:30,521] Trial 45 pruned.

Best trial: 28. Best value: 0.54924:  22%|██▎       | 45/200 [00:54<03:16,  1.27s/it]

[I 2025-11-10 14:39:32,329] Trial 44 finished with value: 0.4798245614035088 and parameters: {'max_depth': 9, 'learning_rate': 0.10492437084579873, 'n_estimators': 1168, 'subsample': 0.6082241256648838, 'colsample_bytree': 0.5784464159441437, 'min_child_weight': 2, 'gamma': 2.339387383833018, 'reg_alpha': 0.3391164754829454, 'reg_lambda': 3.67992933346293e-06, 'max_delta_step': 10}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  23%|██▎       | 46/200 [00:55<03:01,  1.18s/it]

[I 2025-11-10 14:39:33,279] Trial 42 finished with value: 0.5147953216374269 and parameters: {'max_depth': 9, 'learning_rate': 0.11383768389959946, 'n_estimators': 1367, 'subsample': 0.6839652981354162, 'colsample_bytree': 0.7517654659158046, 'min_child_weight': 2, 'gamma': 2.6620652857292657, 'reg_alpha': 1.964353806000138e-07, 'reg_lambda': 0.0003668233415453815, 'max_delta_step': 10}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  24%|██▎       | 47/200 [00:55<02:22,  1.08it/s]

[I 2025-11-10 14:39:33,617] Trial 48 pruned.

Best trial: 28. Best value: 0.54924:  24%|██▍       | 48/200 [00:58<03:20,  1.32s/it]

[I 2025-11-10 14:39:35,873] Trial 46 finished with value: 0.4742690058479532 and parameters: {'max_depth': 10, 'learning_rate': 0.09998425283971094, 'n_estimators': 1179, 'subsample': 0.6888225576836453, 'colsample_bytree': 0.6496176471297223, 'min_child_weight': 2, 'gamma': 3.135677629210893, 'reg_alpha': 2.8521586551759303e-08, 'reg_lambda': 3.2557067966970917e-06, 'max_delta_step': 8}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  25%|██▌       | 50/200 [00:59<02:33,  1.02s/it]

[I 2025-11-10 14:39:37,452] Trial 51 pruned.
[I 2025-11-10 14:39:37,591] Trial 47 finished with value: 0.4837426900584796 and parameters: {'max_depth': 9, 'learning_rate': 0.07920768723287386, 'n_estimators': 1310, 'subsample': 0.6532275111971213, 'colsample_bytree': 0.6463470501245974, 'min_child_weight': 3, 'gamma': 3.2019575601615697, 'reg_alpha': 0.6855750309646517, 'reg_lambda': 6.242220233542793e-07, 'max_delta_step': 8}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  26%|██▌       | 52/200 [01:01<01:55,  1.28it/s]

[I 2025-11-10 14:39:38,733] Trial 53 pruned.
[I 2025-11-10 14:39:38,862] Trial 49 finished with value: 0.5106432748538012 and parameters: {'max_depth': 9, 'learning_rate': 0.021319279597718843, 'n_estimators': 927, 'subsample': 0.5201092297931227, 'colsample_bytree': 0.648918260226931, 'min_child_weight': 3, 'gamma': 3.272814105316988, 'reg_alpha': 2.0730769994902337e-06, 'reg_lambda': 9.007214050199383e-07, 'max_delta_step': 8}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  26%|██▋       | 53/200 [01:01<01:38,  1.49it/s]

[I 2025-11-10 14:39:39,273] Trial 50 finished with value: 0.5112280701754386 and parameters: {'max_depth': 9, 'learning_rate': 0.09502041534604763, 'n_estimators': 1042, 'subsample': 0.663691178196655, 'colsample_bytree': 0.5444042132789804, 'min_child_weight': 3, 'gamma': 3.22555201347844, 'reg_alpha': 1.6505621519237292e-06, 'reg_lambda': 3.7570177965837944e-07, 'max_delta_step': 8}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  27%|██▋       | 54/200 [01:03<02:55,  1.20s/it]

[I 2025-11-10 14:39:41,708] Trial 52 finished with value: 0.48619883040935663 and parameters: {'max_depth': 9, 'learning_rate': 0.0554644852935248, 'n_estimators': 943, 'subsample': 0.6584423490478918, 'colsample_bytree': 0.5396840936476781, 'min_child_weight': 4, 'gamma': 1.5686554771018786, 'reg_alpha': 0.0002940073713972201, 'reg_lambda': 0.0246693079642328, 'max_delta_step': 8}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  28%|██▊       | 55/200 [01:06<04:10,  1.73s/it]

[I 2025-11-10 14:39:44,666] Trial 55 finished with value: 0.5312280701754386 and parameters: {'max_depth': 8, 'learning_rate': 0.04132251081665178, 'n_estimators': 988, 'subsample': 0.8004355338438314, 'colsample_bytree': 0.6040780292190908, 'min_child_weight': 1, 'gamma': 4.525900309573178, 'reg_alpha': 4.3072585712295255e-07, 'reg_lambda': 0.018845712878161884, 'max_delta_step': 7}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  28%|██▊       | 56/200 [01:07<03:13,  1.34s/it]

[I 2025-11-10 14:39:45,112] Trial 54 finished with value: 0.5273099415204678 and parameters: {'max_depth': 8, 'learning_rate': 0.042301579917498666, 'n_estimators': 995, 'subsample': 0.7988576141486489, 'colsample_bytree': 0.7203711950668366, 'min_child_weight': 1, 'gamma': 3.8751430912236864, 'reg_alpha': 2.986964279821966e-06, 'reg_lambda': 0.00011885442320011824, 'max_delta_step': 6}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  28%|██▊       | 57/200 [01:07<02:29,  1.05s/it]

[I 2025-11-10 14:39:45,471] Trial 56 finished with value: 0.5350877192982456 and parameters: {'max_depth': 8, 'learning_rate': 0.028859412241662472, 'n_estimators': 969, 'subsample': 0.7313636870422809, 'colsample_bytree': 0.7170400885519196, 'min_child_weight': 1, 'gamma': 3.9427751475342996, 'reg_alpha': 1.670635563751541e-05, 'reg_lambda': 0.015409046031564962, 'max_delta_step': 7}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  29%|██▉       | 58/200 [01:08<02:12,  1.07it/s]

[I 2025-11-10 14:39:46,131] Trial 58 pruned.

Best trial: 28. Best value: 0.54924:  30%|██▉       | 59/200 [01:09<02:08,  1.10it/s]

[I 2025-11-10 14:39:47,000] Trial 60 pruned.

Best trial: 28. Best value: 0.54924:  30%|███       | 60/200 [01:09<02:00,  1.17it/s]

[I 2025-11-10 14:39:47,731] Trial 62 pruned.

Best trial: 28. Best value: 0.54924:  30%|███       | 61/200 [01:10<01:43,  1.34it/s]

[I 2025-11-10 14:39:48,206] Trial 57 finished with value: 0.49064327485380116 and parameters: {'max_depth': 8, 'learning_rate': 0.041232350379932906, 'n_estimators': 1222, 'subsample': 0.7324346598482652, 'colsample_bytree': 0.6112967571698636, 'min_child_weight': 1, 'gamma': 3.8206426048847524, 'reg_alpha': 5.180484066882027e-07, 'reg_lambda': 2.0569509729301034e-05, 'max_delta_step': 7}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  31%|███       | 62/200 [01:11<01:39,  1.38it/s]

[I 2025-11-10 14:39:48,880] Trial 63 pruned.

Best trial: 28. Best value: 0.54924:  32%|███▏      | 63/200 [01:11<01:25,  1.60it/s]

[I 2025-11-10 14:39:49,278] Trial 64 pruned.

Best trial: 28. Best value: 0.54924:  32%|███▏      | 64/200 [01:12<01:27,  1.56it/s]

[I 2025-11-10 14:39:49,959] Trial 65 pruned.

Best trial: 28. Best value: 0.54924:  32%|███▎      | 65/200 [01:12<01:29,  1.51it/s]

[I 2025-11-10 14:39:50,667] Trial 61 finished with value: 0.5017543859649123 and parameters: {'max_depth': 4, 'learning_rate': 0.029933658412749645, 'n_estimators': 860, 'subsample': 0.9570497485460812, 'colsample_bytree': 0.6098035078817403, 'min_child_weight': 2, 'gamma': 2.9285451269356835, 'reg_alpha': 1.5878612913924637e-05, 'reg_lambda': 0.15343403675039904, 'max_delta_step': 9}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  33%|███▎      | 66/200 [01:13<01:44,  1.28it/s]

[I 2025-11-10 14:39:51,729] Trial 68 pruned.

Best trial: 28. Best value: 0.54924:  34%|███▎      | 67/200 [01:14<01:25,  1.55it/s]

[I 2025-11-10 14:39:52,059] Trial 59 finished with value: 0.5334502923976608 and parameters: {'max_depth': 7, 'learning_rate': 0.02916205822831426, 'n_estimators': 1240, 'subsample': 0.880551803874285, 'colsample_bytree': 0.6121627485258935, 'min_child_weight': 1, 'gamma': 4.5723838541374295, 'reg_alpha': 4.1277083721117085e-07, 'reg_lambda': 0.2192129248650512, 'max_delta_step': 7}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  34%|███▍      | 68/200 [01:15<01:35,  1.38it/s]

[I 2025-11-10 14:39:52,969] Trial 70 pruned.

Best trial: 28. Best value: 0.54924:  34%|███▍      | 69/200 [01:15<01:34,  1.39it/s]

[I 2025-11-10 14:39:53,678] Trial 71 pruned.

Best trial: 28. Best value: 0.54924:  35%|███▌      | 70/200 [01:16<01:41,  1.28it/s]

[I 2025-11-10 14:39:54,597] Trial 66 finished with value: 0.5184210526315789 and parameters: {'max_depth': 7, 'learning_rate': 0.03195192188126138, 'n_estimators': 884, 'subsample': 0.8845011628372969, 'colsample_bytree': 0.6277510949917602, 'min_child_weight': 1, 'gamma': 2.231478336158211, 'reg_alpha': 1.3450351055562283e-05, 'reg_lambda': 0.009382059062049598, 'max_delta_step': 4}. Best is trial 28 with value: 0.5492397660818713.

Best trial: 28. Best value: 0.54924:  36%|███▌      | 71/200 [01:17<01:26,  1.50it/s]

[I 2025-11-10 14:39:55,002] Trial 72 pruned.

Best trial: 28. Best value: 0.54924:  36%|███▌      | 72/200 [01:17<01:14,  1.73it/s]

[I 2025-11-10 14:39:55,376] Trial 73 pruned.

Best trial: 67. Best value: 0.554795:  36%|███▋      | 73/200 [01:18<01:19,  1.59it/s]

[I 2025-11-10 14:39:56,119] Trial 67 finished with value: 0.5547953216374268 and parameters: {'max_depth': 6, 'learning_rate': 0.03162308091173779, 'n_estimators': 1062, 'subsample': 0.8695866694183785, 'colsample_bytree': 0.6279742177044447, 'min_child_weight': 1, 'gamma': 4.331509821889435, 'reg_alpha': 1.5028021667843054e-05, 'reg_lambda': 5.82015548003016e-06, 'max_delta_step': 4}. Best is trial 67 with value: 0.5547953216374268.
[I 2025-11-10 14:39:56,185] Trial 74 pruned.

Best trial: 67. Best value: 0.554795:  38%|███▊      | 75/200 [01:18<00:52,  2.38it/s]

[I 2025-11-10 14:39:56,472] Trial 69 finished with value: 0.5184210526315789 and parameters: {'max_depth': 6, 'learning_rate': 0.03185147035208099, 'n_estimators': 792, 'subsample': 0.5287526828208019, 'colsample_bytree': 0.704597107304723, 'min_child_weight': 1, 'gamma': 2.182181078041954, 'reg_alpha': 4.058952249985875e-06, 'reg_lambda': 0.01178361054743685, 'max_delta_step': 4}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  38%|███▊      | 76/200 [01:19<01:10,  1.76it/s]

[I 2025-11-10 14:39:57,490] Trial 76 pruned.
[I 2025-11-10 14:39:57,514] Trial 77 pruned.

Best trial: 67. Best value: 0.554795:  39%|███▉      | 78/200 [01:19<00:45,  2.68it/s]

[I 2025-11-10 14:39:57,683] Trial 78 pruned.

Best trial: 67. Best value: 0.554795:  40%|███▉      | 79/200 [01:20<00:53,  2.25it/s]

[I 2025-11-10 14:39:58,372] Trial 80 pruned.

Best trial: 67. Best value: 0.554795:  40%|████      | 80/200 [01:20<00:50,  2.36it/s]

[I 2025-11-10 14:39:58,730] Trial 81 pruned.

Best trial: 67. Best value: 0.554795:  40%|████      | 81/200 [01:22<01:32,  1.29it/s]

[I 2025-11-10 14:40:00,517] Trial 83 pruned.

Best trial: 67. Best value: 0.554795:  41%|████      | 82/200 [01:23<01:35,  1.23it/s]

[I 2025-11-10 14:40:01,423] Trial 75 finished with value: 0.5436842105263158 and parameters: {'max_depth': 8, 'learning_rate': 0.019395703741681022, 'n_estimators': 1022, 'subsample': 0.8623211986264677, 'colsample_bytree': 0.5634207312264694, 'min_child_weight': 1, 'gamma': 4.011327118058363, 'reg_alpha': 3.2025034503809214e-07, 'reg_lambda': 0.0010415064728251443, 'max_delta_step': 7}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  42%|████▏     | 83/200 [01:23<01:18,  1.49it/s]

[I 2025-11-10 14:40:01,731] Trial 84 pruned.

Best trial: 67. Best value: 0.554795:  42%|████▏     | 84/200 [01:24<01:16,  1.51it/s]

[I 2025-11-10 14:40:02,364] Trial 79 finished with value: 0.5092397660818714 and parameters: {'max_depth': 6, 'learning_rate': 0.020138245936893277, 'n_estimators': 964, 'subsample': 0.5956447478763078, 'colsample_bytree': 0.6601958158560346, 'min_child_weight': 2, 'gamma': 2.549619023790814, 'reg_alpha': 5.055589069580083e-05, 'reg_lambda': 2.3043109111606233e-06, 'max_delta_step': 5}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  42%|████▎     | 85/200 [01:25<01:21,  1.41it/s]

[I 2025-11-10 14:40:03,190] Trial 82 finished with value: 0.5217543859649123 and parameters: {'max_depth': 10, 'learning_rate': 0.047082506963928954, 'n_estimators': 1189, 'subsample': 0.7184631513784263, 'colsample_bytree': 0.6429110546099236, 'min_child_weight': 3, 'gamma': 4.38222046543772, 'reg_alpha': 0.0045084517687008115, 'reg_lambda': 1.4025484206723098e-08, 'max_delta_step': 9}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  43%|████▎     | 86/200 [01:28<02:53,  1.52s/it]

[I 2025-11-10 14:40:06,685] Trial 85 finished with value: 0.5436842105263158 and parameters: {'max_depth': 8, 'learning_rate': 0.02842741520250447, 'n_estimators': 912, 'subsample': 0.8708044004271749, 'colsample_bytree': 0.6213866198000295, 'min_child_weight': 1, 'gamma': 3.6917555567848415, 'reg_alpha': 7.011098832430963e-07, 'reg_lambda': 0.0028391810397601224, 'max_delta_step': 6}. Best is trial 67 with value: 0.5547953216374268.
[I 2025-11-10 14:40:06,736] Trial 86 finished with value: 0.5233918128654971 and parameters: {'max_depth': 9, 'learning_rate': 0.023992224301725634, 'n_estimators': 907, 'subsample': 0.8761305090879797, 'colsample_bytree': 0.5198880067116332, 'min_child_weight': 1, 'gamma': 2.5360178337349186, 'reg_alpha': 7.072497194754031e-07, 'reg_lambda': 0.003256380081178406, 'max_delta_step': 6}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  44%|████▍     | 88/200 [01:29<01:42,  1.09it/s]

[I 2025-11-10 14:40:07,070] Trial 87 finished with value: 0.5184210526315789 and parameters: {'max_depth': 9, 'learning_rate': 0.03510875169855641, 'n_estimators': 908, 'subsample': 0.8605806101217937, 'colsample_bytree': 0.518829180471515, 'min_child_weight': 1, 'gamma': 3.7052338263792794, 'reg_alpha': 8.738439975921146e-07, 'reg_lambda': 6.865919626596186e-05, 'max_delta_step': 6}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  44%|████▍     | 89/200 [01:29<01:32,  1.20it/s]

[I 2025-11-10 14:40:07,656] Trial 88 finished with value: 0.4756140350877193 and parameters: {'max_depth': 9, 'learning_rate': 0.07136703913842672, 'n_estimators': 912, 'subsample': 0.6966573520879071, 'colsample_bytree': 0.5271949743660987, 'min_child_weight': 1, 'gamma': 3.3712532023690285, 'reg_alpha': 7.311668081342858e-07, 'reg_lambda': 0.003533537158702717, 'max_delta_step': 6}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  45%|████▌     | 90/200 [01:30<01:20,  1.36it/s]

[I 2025-11-10 14:40:08,095] Trial 91 pruned.

Best trial: 67. Best value: 0.554795:  46%|████▌     | 91/200 [01:30<01:08,  1.58it/s]

[I 2025-11-10 14:40:08,458] Trial 92 pruned.

Best trial: 67. Best value: 0.554795:  46%|████▌     | 92/200 [01:30<00:56,  1.90it/s]

[I 2025-11-10 14:40:08,710] Trial 93 pruned.

Best trial: 67. Best value: 0.554795:  46%|████▋     | 93/200 [01:32<01:18,  1.37it/s]

[I 2025-11-10 14:40:09,950] Trial 95 pruned.

Best trial: 67. Best value: 0.554795:  47%|████▋     | 94/200 [01:33<01:34,  1.12it/s]

[I 2025-11-10 14:40:11,252] Trial 90 finished with value: 0.5239766081871344 and parameters: {'max_depth': 8, 'learning_rate': 0.0729068806296619, 'n_estimators': 1021, 'subsample': 0.6811083682322249, 'colsample_bytree': 0.5758260255173071, 'min_child_weight': 2, 'gamma': 3.4032801789057174, 'reg_alpha': 1.247198359777795e-08, 'reg_lambda': 0.0017942304987031482, 'max_delta_step': 6}. Best is trial 67 with value: 0.5547953216374268.
[I 2025-11-10 14:40:11,282] Trial 96 pruned.

Best trial: 67. Best value: 0.554795:  48%|████▊     | 96/200 [01:34<01:06,  1.56it/s]

[I 2025-11-10 14:40:11,921] Trial 89 finished with value: 0.5184210526315789 and parameters: {'max_depth': 9, 'learning_rate': 0.023751453060201228, 'n_estimators': 897, 'subsample': 0.8681159233709387, 'colsample_bytree': 0.5197210877341288, 'min_child_weight': 1, 'gamma': 3.4156841671837483, 'reg_alpha': 4.2386117776437616e-08, 'reg_lambda': 0.0021682107392451133, 'max_delta_step': 6}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  48%|████▊     | 97/200 [01:34<01:11,  1.44it/s]

[I 2025-11-10 14:40:12,769] Trial 99 pruned.

Best trial: 67. Best value: 0.554795:  49%|████▉     | 98/200 [01:36<01:27,  1.16it/s]

[I 2025-11-10 14:40:14,119] Trial 100 pruned.

Best trial: 67. Best value: 0.554795:  50%|████▉     | 99/200 [01:36<01:12,  1.39it/s]

[I 2025-11-10 14:40:14,464] Trial 94 finished with value: 0.5184210526315789 and parameters: {'max_depth': 7, 'learning_rate': 0.05338243863773262, 'n_estimators': 1065, 'subsample': 0.8686355627568014, 'colsample_bytree': 0.6196132467083161, 'min_child_weight': 1, 'gamma': 4.028512449998896, 'reg_alpha': 2.3066774940570345e-07, 'reg_lambda': 1.691508843823824e-05, 'max_delta_step': 7}. Best is trial 67 with value: 0.5547953216374268.
[I 2025-11-10 14:40:14,476] Trial 98 finished with value: 0.5239766081871344 and parameters: {'max_depth': 7, 'learning_rate': 0.05207968348119961, 'n_estimators': 526, 'subsample': 0.8717746604307067, 'colsample_bytree': 0.6578488026124514, 'min_child_weight': 1, 'gamma': 3.8311554623743946, 'reg_alpha': 1.9049458424302237e-06, 'reg_lambda': 3.455356348807465e-05, 'max_delta_step': 7}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  50%|█████     | 101/200 [01:38<01:26,  1.14it/s]

[I 2025-11-10 14:40:16,572] Trial 103 pruned.

Best trial: 67. Best value: 0.554795:  51%|█████     | 102/200 [01:41<02:02,  1.25s/it]

[I 2025-11-10 14:40:19,057] Trial 97 finished with value: 0.54953216374269 and parameters: {'max_depth': 7, 'learning_rate': 0.051708867153781805, 'n_estimators': 1106, 'subsample': 0.9134047616034973, 'colsample_bytree': 0.6585985445243147, 'min_child_weight': 1, 'gamma': 3.7761522838047368, 'reg_alpha': 5.209803798148936e-08, 'reg_lambda': 0.0006174185973324331, 'max_delta_step': 7}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  52%|█████▏    | 103/200 [01:42<01:57,  1.21s/it]

[I 2025-11-10 14:40:20,155] Trial 102 finished with value: 0.5423391812865497 and parameters: {'max_depth': 8, 'learning_rate': 0.029422949775540313, 'n_estimators': 966, 'subsample': 0.6428081893025742, 'colsample_bytree': 0.5517533567422153, 'min_child_weight': 2, 'gamma': 4.434598874765395, 'reg_alpha': 2.416700299645956e-05, 'reg_lambda': 2.4799599531695446e-07, 'max_delta_step': 8}. Best is trial 67 with value: 0.5547953216374268.
[I 2025-11-10 14:40:20,195] Trial 105 pruned.

Best trial: 67. Best value: 0.554795:  52%|█████▎    | 105/200 [01:43<01:23,  1.13it/s]

[I 2025-11-10 14:40:21,012] Trial 106 pruned.

Best trial: 67. Best value: 0.554795:  53%|█████▎    | 106/200 [01:44<01:21,  1.16it/s]

[I 2025-11-10 14:40:21,809] Trial 101 finished with value: 0.5347953216374269 and parameters: {'max_depth': 7, 'learning_rate': 0.052529393127909794, 'n_estimators': 1059, 'subsample': 0.8354958376702748, 'colsample_bytree': 0.6808277075290676, 'min_child_weight': 1, 'gamma': 4.463983547966585, 'reg_alpha': 3.471171633422346e-07, 'reg_lambda': 0.0001100203225377752, 'max_delta_step': 9}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  54%|█████▎    | 107/200 [01:44<01:05,  1.43it/s]

[I 2025-11-10 14:40:22,018] Trial 108 pruned.

Best trial: 67. Best value: 0.554795:  54%|█████▍    | 108/200 [01:44<00:52,  1.77it/s]

[I 2025-11-10 14:40:22,200] Trial 104 finished with value: 0.4739766081871345 and parameters: {'max_depth': 8, 'learning_rate': 0.2747994930649749, 'n_estimators': 982, 'subsample': 0.7977156257955514, 'colsample_bytree': 0.6041141196316578, 'min_child_weight': 1, 'gamma': 4.488814817194451, 'reg_alpha': 3.763933301615763e-07, 'reg_lambda': 0.04816800458977175, 'max_delta_step': 7}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  55%|█████▍    | 109/200 [01:45<00:54,  1.67it/s]

[I 2025-11-10 14:40:22,887] Trial 111 pruned.

Best trial: 67. Best value: 0.554795:  55%|█████▌    | 110/200 [01:46<01:18,  1.14it/s]

[I 2025-11-10 14:40:24,470] Trial 107 finished with value: 0.5276023391812865 and parameters: {'max_depth': 8, 'learning_rate': 0.04535145501487591, 'n_estimators': 1041, 'subsample': 0.6389476004233386, 'colsample_bytree': 0.5472864414797053, 'min_child_weight': 3, 'gamma': 2.4392943836107475, 'reg_alpha': 2.9195154768304422e-05, 'reg_lambda': 6.143355310934384e-08, 'max_delta_step': 8}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  56%|█████▌    | 111/200 [01:46<01:02,  1.42it/s]

[I 2025-11-10 14:40:24,756] Trial 112 pruned.

Best trial: 67. Best value: 0.554795:  56%|█████▌    | 112/200 [01:49<01:35,  1.09s/it]

[I 2025-11-10 14:40:26,774] Trial 110 finished with value: 0.5164912280701756 and parameters: {'max_depth': 9, 'learning_rate': 0.022080236751462222, 'n_estimators': 1091, 'subsample': 0.5379497950953128, 'colsample_bytree': 0.8268317237804964, 'min_child_weight': 3, 'gamma': 1.6631287214633197, 'reg_alpha': 3.6026177402384898e-06, 'reg_lambda': 0.0006037825085766952, 'max_delta_step': 8}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  57%|█████▋    | 114/200 [01:49<00:57,  1.51it/s]

[I 2025-11-10 14:40:27,136] Trial 114 pruned.
[I 2025-11-10 14:40:27,298] Trial 109 finished with value: 0.5239766081871344 and parameters: {'max_depth': 8, 'learning_rate': 0.04490228588858789, 'n_estimators': 1095, 'subsample': 0.6699968050391851, 'colsample_bytree': 0.7145202507468356, 'min_child_weight': 2, 'gamma': 3.694404085219467, 'reg_alpha': 8.394142423904708e-08, 'reg_lambda': 0.0006214293423102477, 'max_delta_step': 9}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  57%|█████▊    | 115/200 [01:50<00:59,  1.44it/s]

[I 2025-11-10 14:40:28,063] Trial 115 pruned.

Best trial: 67. Best value: 0.554795:  58%|█████▊    | 116/200 [01:50<00:48,  1.73it/s]

[I 2025-11-10 14:40:28,372] Trial 116 pruned.

Best trial: 67. Best value: 0.554795:  58%|█████▊    | 117/200 [01:51<00:55,  1.50it/s]

[I 2025-11-10 14:40:29,250] Trial 118 pruned.

Best trial: 67. Best value: 0.554795:  59%|█████▉    | 118/200 [01:51<00:43,  1.87it/s]

[I 2025-11-10 14:40:29,476] Trial 119 pruned.

Best trial: 67. Best value: 0.554795:  60%|█████▉    | 119/200 [01:52<00:42,  1.90it/s]

[I 2025-11-10 14:40:29,977] Trial 113 finished with value: 0.5325730994152047 and parameters: {'max_depth': 10, 'learning_rate': 0.03374246449944176, 'n_estimators': 1096, 'subsample': 0.7118304798672759, 'colsample_bytree': 0.719128268583483, 'min_child_weight': 2, 'gamma': 3.043338411120134, 'reg_alpha': 3.42157505599396e-06, 'reg_lambda': 1.0416686566629686e-05, 'max_delta_step': 8}. Best is trial 67 with value: 0.5547953216374268.
[I 2025-11-10 14:40:30,070] Trial 117 pruned.

Best trial: 67. Best value: 0.554795:  60%|██████    | 121/200 [01:53<00:44,  1.78it/s]

[I 2025-11-10 14:40:31,180] Trial 123 pruned.

Best trial: 67. Best value: 0.554795:  61%|██████    | 122/200 [01:53<00:38,  2.01it/s]

[I 2025-11-10 14:40:31,484] Trial 120 pruned.

Best trial: 67. Best value: 0.554795:  62%|██████▏   | 123/200 [01:57<01:39,  1.30s/it]

[I 2025-11-10 14:40:35,038] Trial 121 finished with value: 0.5236842105263158 and parameters: {'max_depth': 8, 'learning_rate': 0.038990428545998365, 'n_estimators': 1059, 'subsample': 0.560150382358743, 'colsample_bytree': 0.6670664902436648, 'min_child_weight': 1, 'gamma': 4.677837031037784, 'reg_alpha': 6.035759495283362e-08, 'reg_lambda': 0.0011881916067676833, 'max_delta_step': 0}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  62%|██████▏   | 124/200 [01:58<01:28,  1.17s/it]

[I 2025-11-10 14:40:35,863] Trial 122 finished with value: 0.5347953216374269 and parameters: {'max_depth': 8, 'learning_rate': 0.038502894221706524, 'n_estimators': 1063, 'subsample': 0.738161516815263, 'colsample_bytree': 0.6517452347341438, 'min_child_weight': 1, 'gamma': 2.1509958406636325, 'reg_alpha': 9.745651857708787e-07, 'reg_lambda': 0.0011016485467171399, 'max_delta_step': 0}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  62%|██████▎   | 125/200 [01:58<01:17,  1.03s/it]

[I 2025-11-10 14:40:36,533] Trial 126 pruned.

Best trial: 67. Best value: 0.554795:  63%|██████▎   | 126/200 [01:59<01:05,  1.13it/s]

[I 2025-11-10 14:40:37,057] Trial 124 finished with value: 0.5381286549707602 and parameters: {'max_depth': 7, 'learning_rate': 0.028052878390360605, 'n_estimators': 994, 'subsample': 0.8833253263645706, 'colsample_bytree': 0.612397609921467, 'min_child_weight': 1, 'gamma': 4.503440940792919, 'reg_alpha': 3.1519076381841607e-07, 'reg_lambda': 3.542387657979972e-07, 'max_delta_step': 0}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  64%|██████▎   | 127/200 [01:59<00:57,  1.27it/s]

[I 2025-11-10 14:40:37,597] Trial 125 finished with value: 0.5439766081871344 and parameters: {'max_depth': 7, 'learning_rate': 0.028362839496867843, 'n_estimators': 1002, 'subsample': 0.8577685332076206, 'colsample_bytree': 0.6696630360355846, 'min_child_weight': 1, 'gamma': 4.551042075367549, 'reg_alpha': 3.126453609215068e-07, 'reg_lambda': 5.485932857202244e-05, 'max_delta_step': 0}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  64%|██████▍   | 128/200 [02:00<01:02,  1.15it/s]

[I 2025-11-10 14:40:38,679] Trial 130 pruned.

Best trial: 67. Best value: 0.554795:  64%|██████▍   | 129/200 [02:01<00:54,  1.31it/s]

[I 2025-11-10 14:40:39,184] Trial 129 pruned.

Best trial: 67. Best value: 0.554795:  65%|██████▌   | 130/200 [02:03<01:16,  1.10s/it]

[I 2025-11-10 14:40:41,083] Trial 132 pruned.

Best trial: 67. Best value: 0.554795:  66%|██████▌   | 131/200 [02:04<01:10,  1.02s/it]

[I 2025-11-10 14:40:41,926] Trial 133 pruned.

Best trial: 67. Best value: 0.554795:  66%|██████▌   | 132/200 [02:04<00:57,  1.19it/s]

[I 2025-11-10 14:40:42,336] Trial 128 finished with value: 0.5270175438596493 and parameters: {'max_depth': 8, 'learning_rate': 0.24051183174638205, 'n_estimators': 1000, 'subsample': 0.7238708469439812, 'colsample_bytree': 0.6492735963816686, 'min_child_weight': 1, 'gamma': 1.9778000663541881, 'reg_alpha': 1.4503345394844522e-06, 'reg_lambda': 0.00028966817412543947, 'max_delta_step': 1}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  66%|██████▋   | 133/200 [02:05<00:50,  1.34it/s]

[I 2025-11-10 14:40:42,864] Trial 127 finished with value: 0.5295321637426901 and parameters: {'max_depth': 8, 'learning_rate': 0.04034504129875668, 'n_estimators': 995, 'subsample': 0.7337136880640418, 'colsample_bytree': 0.6711676210846662, 'min_child_weight': 1, 'gamma': 2.3154037467672577, 'reg_alpha': 2.949570997144701e-07, 'reg_lambda': 0.0003651608487157461, 'max_delta_step': 8}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  67%|██████▋   | 134/200 [02:06<00:57,  1.15it/s]

[I 2025-11-10 14:40:44,017] Trial 136 pruned.

Best trial: 67. Best value: 0.554795:  68%|██████▊   | 135/200 [02:08<01:13,  1.13s/it]

[I 2025-11-10 14:40:45,769] Trial 137 pruned.

Best trial: 67. Best value: 0.554795:  68%|██████▊   | 136/200 [02:08<00:57,  1.11it/s]

[I 2025-11-10 14:40:46,125] Trial 131 finished with value: 0.4981286549707603 and parameters: {'max_depth': 6, 'learning_rate': 0.02411488314438542, 'n_estimators': 863, 'subsample': 0.8570566410650531, 'colsample_bytree': 0.7670625675449424, 'min_child_weight': 1, 'gamma': 4.074433886931807, 'reg_alpha': 2.5004711502977713e-07, 'reg_lambda': 1.6037399837262977e-07, 'max_delta_step': 1}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 67. Best value: 0.554795:  68%|██████▊   | 137/200 [02:09<01:07,  1.07s/it]

[I 2025-11-10 14:40:47,584] Trial 139 pruned.

Best trial: 67. Best value: 0.554795:  69%|██████▉   | 138/200 [02:11<01:09,  1.12s/it]

[I 2025-11-10 14:40:48,819] Trial 140 pruned.

Best trial: 67. Best value: 0.554795:  70%|██████▉   | 139/200 [02:11<00:56,  1.08it/s]

[I 2025-11-10 14:40:49,256] Trial 135 finished with value: 0.5181286549707603 and parameters: {'max_depth': 7, 'learning_rate': 0.03049901604610608, 'n_estimators': 1034, 'subsample': 0.8561947601497377, 'colsample_bytree': 0.5583802396372312, 'min_child_weight': 1, 'gamma': 4.434124372768391, 'reg_alpha': 2.425427951078414e-07, 'reg_lambda': 2.279795284726204e-05, 'max_delta_step': 0}. Best is trial 67 with value: 0.5547953216374268.

Best trial: 134. Best value: 0.563977:  70%|███████   | 140/200 [02:11<00:44,  1.34it/s]

[I 2025-11-10 14:40:49,630] Trial 134 finished with value: 0.5639766081871345 and parameters: {'max_depth': 7, 'learning_rate': 0.03310852685712894, 'n_estimators': 1033, 'subsample': 0.8178321958149397, 'colsample_bytree': 0.6978308711869252, 'min_child_weight': 1, 'gamma': 4.440252083575991, 'reg_alpha': 2.3909058114882453e-07, 'reg_lambda': 4.60112811839634e-05, 'max_delta_step': 1}. Best is trial 134 with value: 0.5639766081871345.

Best trial: 134. Best value: 0.563977:  70%|███████   | 141/200 [02:12<00:50,  1.16it/s]

[I 2025-11-10 14:40:50,747] Trial 143 pruned.

Best trial: 134. Best value: 0.563977:  71%|███████   | 142/200 [02:14<00:53,  1.07it/s]

[I 2025-11-10 14:40:51,847] Trial 141 pruned.

Best trial: 134. Best value: 0.563977:  72%|███████▏  | 143/200 [02:14<00:45,  1.26it/s]

[I 2025-11-10 14:40:52,321] Trial 138 finished with value: 0.5206432748538011 and parameters: {'max_depth': 7, 'learning_rate': 0.03584542835577465, 'n_estimators': 1033, 'subsample': 0.9033253431850894, 'colsample_bytree': 0.659855524463469, 'min_child_weight': 2, 'gamma': 4.1511583156669225, 'reg_alpha': 4.523286098677353e-07, 'reg_lambda': 2.5180208001231984e-05, 'max_delta_step': 0}. Best is trial 134 with value: 0.5639766081871345.

Best trial: 134. Best value: 0.563977:  72%|███████▏  | 144/200 [02:15<00:46,  1.21it/s]

[I 2025-11-10 14:40:53,222] Trial 145 pruned.

Best trial: 134. Best value: 0.563977:  72%|███████▎  | 145/200 [02:16<00:42,  1.28it/s]

[I 2025-11-10 14:40:53,899] Trial 146 pruned.

Best trial: 134. Best value: 0.563977:  73%|███████▎  | 146/200 [02:16<00:41,  1.32it/s]

[I 2025-11-10 14:40:54,614] Trial 147 pruned.

Best trial: 134. Best value: 0.563977:  74%|███████▎  | 147/200 [02:17<00:34,  1.55it/s]

[I 2025-11-10 14:40:54,978] Trial 142 finished with value: 0.5039766081871344 and parameters: {'max_depth': 8, 'learning_rate': 0.03469995610231122, 'n_estimators': 925, 'subsample': 0.9132536573243119, 'colsample_bytree': 0.6428680487318552, 'min_child_weight': 2, 'gamma': 4.170467454098798, 'reg_alpha': 2.266117790852895e-06, 'reg_lambda': 0.0125767502639568, 'max_delta_step': 7}. Best is trial 134 with value: 0.5639766081871345.

Best trial: 134. Best value: 0.563977:  74%|███████▍  | 148/200 [02:18<00:35,  1.45it/s]

[I 2025-11-10 14:40:55,774] Trial 149 pruned.

Best trial: 134. Best value: 0.563977:  74%|███████▍  | 149/200 [02:18<00:36,  1.40it/s]

[I 2025-11-10 14:40:56,553] Trial 150 pruned.

Best trial: 134. Best value: 0.563977:  75%|███████▌  | 150/200 [02:19<00:32,  1.52it/s]

[I 2025-11-10 14:40:57,080] Trial 151 pruned.

Best trial: 144. Best value: 0.569532:  76%|███████▌  | 151/200 [02:20<00:42,  1.16it/s]

[I 2025-11-10 14:40:58,414] Trial 144 finished with value: 0.5695321637426901 and parameters: {'max_depth': 7, 'learning_rate': 0.03595986096494462, 'n_estimators': 1161, 'subsample': 0.8180131496334234, 'colsample_bytree': 0.679298020003281, 'min_child_weight': 1, 'gamma': 4.174363050509664, 'reg_alpha': 1.1630090424647919e-07, 'reg_lambda': 5.8281599553080624e-05, 'max_delta_step': 1}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  76%|███████▌  | 152/200 [02:22<00:48,  1.02s/it]

[I 2025-11-10 14:40:59,801] Trial 148 finished with value: 0.5661988304093568 and parameters: {'max_depth': 8, 'learning_rate': 0.027712566945386277, 'n_estimators': 987, 'subsample': 0.51824198467726, 'colsample_bytree': 0.5033982017803436, 'min_child_weight': 1, 'gamma': 4.2797554355051926, 'reg_alpha': 2.268877591422247e-06, 'reg_lambda': 0.00015252289468937195, 'max_delta_step': 2}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  76%|███████▋  | 153/200 [02:22<00:38,  1.22it/s]

[I 2025-11-10 14:41:00,154] Trial 154 pruned.

Best trial: 144. Best value: 0.569532:  77%|███████▋  | 154/200 [02:25<01:15,  1.64s/it]

[I 2025-11-10 14:41:03,720] Trial 153 finished with value: 0.5347953216374269 and parameters: {'max_depth': 8, 'learning_rate': 0.02892903816024156, 'n_estimators': 1111, 'subsample': 0.5207706844356752, 'colsample_bytree': 0.6182113336794859, 'min_child_weight': 1, 'gamma': 3.7727619968855506, 'reg_alpha': 7.425620937436171e-08, 'reg_lambda': 8.636852625025734e-08, 'max_delta_step': 8}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  78%|███████▊  | 155/200 [02:26<00:57,  1.29s/it]

[I 2025-11-10 14:41:04,171] Trial 152 finished with value: 0.5184210526315789 and parameters: {'max_depth': 9, 'learning_rate': 0.03162968741081562, 'n_estimators': 1119, 'subsample': 0.8866486444593895, 'colsample_bytree': 0.6146486599108145, 'min_child_weight': 1, 'gamma': 3.5903964343224057, 'reg_alpha': 6.817863946741224e-08, 'reg_lambda': 0.002643026473672166, 'max_delta_step': 5}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  78%|███████▊  | 156/200 [02:28<01:08,  1.55s/it]

[I 2025-11-10 14:41:06,326] Trial 156 finished with value: 0.5439766081871344 and parameters: {'max_depth': 8, 'learning_rate': 0.026027091357371485, 'n_estimators': 959, 'subsample': 0.8836711611064999, 'colsample_bytree': 0.5115722103320509, 'min_child_weight': 1, 'gamma': 4.016167882828006, 'reg_alpha': 1.1297311086772394e-05, 'reg_lambda': 1.707338114719656e-05, 'max_delta_step': 3}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  78%|███████▊  | 157/200 [02:29<00:56,  1.30s/it]

[I 2025-11-10 14:41:07,058] Trial 155 finished with value: 0.5239766081871345 and parameters: {'max_depth': 8, 'learning_rate': 0.029136700373054804, 'n_estimators': 955, 'subsample': 0.5153281822952374, 'colsample_bytree': 0.6253189050783655, 'min_child_weight': 1, 'gamma': 3.7736855969629413, 'reg_alpha': 8.203147599622877e-06, 'reg_lambda': 1.198723743954084e-05, 'max_delta_step': 1}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  79%|███████▉  | 158/200 [02:30<00:48,  1.15s/it]

[I 2025-11-10 14:41:07,871] Trial 159 pruned.

Best trial: 144. Best value: 0.569532:  80%|███████▉  | 159/200 [02:30<00:38,  1.06it/s]

[I 2025-11-10 14:41:08,322] Trial 160 pruned.

Best trial: 144. Best value: 0.569532:  80%|████████  | 160/200 [02:31<00:37,  1.06it/s]

[I 2025-11-10 14:41:09,258] Trial 162 pruned.

Best trial: 144. Best value: 0.569532:  81%|████████  | 162/200 [02:33<00:32,  1.18it/s]

[I 2025-11-10 14:41:10,901] Trial 157 finished with value: 0.5461988304093567 and parameters: {'max_depth': 8, 'learning_rate': 0.02596396192746524, 'n_estimators': 962, 'subsample': 0.5426508424556784, 'colsample_bytree': 0.5061769693339716, 'min_child_weight': 1, 'gamma': 4.030349869607854, 'reg_alpha': 6.5929914507523486e-06, 'reg_lambda': 8.274752775954563e-06, 'max_delta_step': 3}. Best is trial 144 with value: 0.5695321637426901.
[I 2025-11-10 14:41:11,039] Trial 158 finished with value: 0.5517543859649123 and parameters: {'max_depth': 8, 'learning_rate': 0.026799002113638233, 'n_estimators': 970, 'subsample': 0.5486836860530211, 'colsample_bytree': 0.531683654049419, 'min_child_weight': 1, 'gamma': 4.064181581955038, 'reg_alpha': 6.489253417541192e-06, 'reg_lambda': 0.00017366990004073145, 'max_delta_step': 3}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  82%|████████▏ | 163/200 [02:34<00:34,  1.09it/s]

[I 2025-11-10 14:41:12,123] Trial 164 pruned.
[I 2025-11-10 14:41:12,152] Trial 163 finished with value: 0.5350877192982456 and parameters: {'max_depth': 7, 'learning_rate': 0.02675284838721017, 'n_estimators': 285, 'subsample': 0.5325823619668689, 'colsample_bytree': 0.5006739133586604, 'min_child_weight': 1, 'gamma': 2.6375109656957147, 'reg_alpha': 1.2119679599433898e-05, 'reg_lambda': 0.0001699895177922673, 'max_delta_step': 2}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  82%|████████▎ | 165/200 [02:38<00:47,  1.37s/it]

[I 2025-11-10 14:41:15,911] Trial 161 finished with value: 0.5328654970760234 and parameters: {'max_depth': 8, 'learning_rate': 0.025493834194344513, 'n_estimators': 1168, 'subsample': 0.7767958319249282, 'colsample_bytree': 0.529688163081264, 'min_child_weight': 1, 'gamma': 4.25948359670831, 'reg_alpha': 5.4124202254344585e-06, 'reg_lambda': 8.359642954503434e-06, 'max_delta_step': 4}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  83%|████████▎ | 166/200 [02:39<00:49,  1.46s/it]

[I 2025-11-10 14:41:17,637] Trial 165 finished with value: 0.5350877192982456 and parameters: {'max_depth': 8, 'learning_rate': 0.026161924230446405, 'n_estimators': 986, 'subsample': 0.5340638961660217, 'colsample_bytree': 0.5142327688421501, 'min_child_weight': 1, 'gamma': 3.9147259852436003, 'reg_alpha': 1.0269618462534508e-05, 'reg_lambda': 4.037245270116353e-06, 'max_delta_step': 3}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  84%|████████▎ | 167/200 [02:40<00:42,  1.29s/it]

[I 2025-11-10 14:41:18,452] Trial 166 finished with value: 0.5295321637426901 and parameters: {'max_depth': 8, 'learning_rate': 0.02538872235338302, 'n_estimators': 972, 'subsample': 0.5343847149420665, 'colsample_bytree': 0.5050032690537088, 'min_child_weight': 1, 'gamma': 4.19845392222429, 'reg_alpha': 1.1262133189341392e-05, 'reg_lambda': 0.00017577633258446286, 'max_delta_step': 3}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  84%|████████▍ | 168/200 [02:41<00:36,  1.14s/it]

[I 2025-11-10 14:41:19,181] Trial 169 pruned.

Best trial: 144. Best value: 0.569532:  84%|████████▍ | 169/200 [02:41<00:28,  1.08it/s]

[I 2025-11-10 14:41:19,566] Trial 167 finished with value: 0.5439766081871344 and parameters: {'max_depth': 8, 'learning_rate': 0.024973534982489436, 'n_estimators': 972, 'subsample': 0.8797243595381454, 'colsample_bytree': 0.5121545552556451, 'min_child_weight': 1, 'gamma': 4.362686780181742, 'reg_alpha': 3.262802907668314e-06, 'reg_lambda': 4.3763769140886336e-06, 'max_delta_step': 3}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  85%|████████▌ | 170/200 [02:44<00:44,  1.48s/it]

[I 2025-11-10 14:41:22,410] Trial 168 finished with value: 0.5184210526315789 and parameters: {'max_depth': 8, 'learning_rate': 0.02478489554137563, 'n_estimators': 977, 'subsample': 0.5695903316229098, 'colsample_bytree': 0.5204407717595001, 'min_child_weight': 1, 'gamma': 4.354892015354735, 'reg_alpha': 7.979709730203667e-06, 'reg_lambda': 4.851891936577737e-06, 'max_delta_step': 3}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  86%|████████▌ | 171/200 [02:46<00:42,  1.46s/it]

[I 2025-11-10 14:41:23,847] Trial 173 pruned.

Best trial: 144. Best value: 0.569532:  86%|████████▌ | 172/200 [02:47<00:38,  1.39s/it]

[I 2025-11-10 14:41:25,069] Trial 170 finished with value: 0.5184210526315789 and parameters: {'max_depth': 9, 'learning_rate': 0.020596571812912766, 'n_estimators': 942, 'subsample': 0.5632317273451144, 'colsample_bytree': 0.5426353512379167, 'min_child_weight': 1, 'gamma': 4.359866121918347, 'reg_alpha': 3.4103523443495658e-06, 'reg_lambda': 1.5595718109912654e-06, 'max_delta_step': 3}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  86%|████████▋ | 173/200 [02:48<00:33,  1.25s/it]

[I 2025-11-10 14:41:25,980] Trial 172 finished with value: 0.5439766081871344 and parameters: {'max_depth': 8, 'learning_rate': 0.020901583822598352, 'n_estimators': 914, 'subsample': 0.5615124641151579, 'colsample_bytree': 0.5357280150195608, 'min_child_weight': 1, 'gamma': 4.495555379288394, 'reg_alpha': 3.9410956460512336e-06, 'reg_lambda': 1.3847998503816239e-06, 'max_delta_step': 3}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  87%|████████▋ | 174/200 [02:48<00:27,  1.06s/it]

[I 2025-11-10 14:41:26,572] Trial 171 finished with value: 0.5625730994152047 and parameters: {'max_depth': 9, 'learning_rate': 0.030785436618275857, 'n_estimators': 1015, 'subsample': 0.5618550094250725, 'colsample_bytree': 0.52188185226072, 'min_child_weight': 1, 'gamma': 3.999005695109173, 'reg_alpha': 6.605685460615056e-06, 'reg_lambda': 1.4346416313942497e-06, 'max_delta_step': 4}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  88%|████████▊ | 175/200 [02:49<00:23,  1.05it/s]

[I 2025-11-10 14:41:27,273] Trial 176 pruned.

Best trial: 144. Best value: 0.569532:  88%|████████▊ | 176/200 [02:52<00:38,  1.59s/it]

[I 2025-11-10 14:41:30,361] Trial 174 finished with value: 0.5436842105263159 and parameters: {'max_depth': 8, 'learning_rate': 0.030247669815897337, 'n_estimators': 1013, 'subsample': 0.8925138481499851, 'colsample_bytree': 0.5440185313048381, 'min_child_weight': 1, 'gamma': 4.1751330882628945, 'reg_alpha': 3.2486046618489066e-06, 'reg_lambda': 5.1912346677959784e-05, 'max_delta_step': 3}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  88%|████████▊ | 177/200 [02:54<00:36,  1.58s/it]

[I 2025-11-10 14:41:31,937] Trial 175 finished with value: 0.5436842105263159 and parameters: {'max_depth': 7, 'learning_rate': 0.030086571587055525, 'n_estimators': 1020, 'subsample': 0.8831968653464503, 'colsample_bytree': 0.5239894996866511, 'min_child_weight': 1, 'gamma': 4.128497434979494, 'reg_alpha': 1.981438569030787e-05, 'reg_lambda': 5.192634787671615e-05, 'max_delta_step': 2}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  89%|████████▉ | 178/200 [02:55<00:30,  1.39s/it]

[I 2025-11-10 14:41:32,868] Trial 177 finished with value: 0.554795321637427 and parameters: {'max_depth': 8, 'learning_rate': 0.023386036097094765, 'n_estimators': 1019, 'subsample': 0.5787422896378528, 'colsample_bytree': 0.5286139316172034, 'min_child_weight': 1, 'gamma': 4.008542574781891, 'reg_alpha': 7.155932073188017e-06, 'reg_lambda': 8.86519085903448e-07, 'max_delta_step': 4}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  90%|████████▉ | 179/200 [02:55<00:25,  1.22s/it]

[I 2025-11-10 14:41:33,689] Trial 178 finished with value: 0.5461988304093567 and parameters: {'max_depth': 8, 'learning_rate': 0.021921836335145658, 'n_estimators': 1019, 'subsample': 0.548342919141697, 'colsample_bytree': 0.5415900484992323, 'min_child_weight': 1, 'gamma': 3.998016207704398, 'reg_alpha': 1.4068521337675319e-05, 'reg_lambda': 4.541450179462088e-06, 'max_delta_step': 4}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  90%|█████████ | 180/200 [02:56<00:23,  1.17s/it]

[I 2025-11-10 14:41:34,742] Trial 180 pruned.

Best trial: 144. Best value: 0.569532:  90%|█████████ | 181/200 [02:57<00:21,  1.12s/it]

[I 2025-11-10 14:41:35,761] Trial 179 finished with value: 0.5436842105263158 and parameters: {'max_depth': 8, 'learning_rate': 0.022501598445325715, 'n_estimators': 851, 'subsample': 0.5769491626378473, 'colsample_bytree': 0.5454278926191399, 'min_child_weight': 1, 'gamma': 4.029826741668246, 'reg_alpha': 1.5750821312649584e-05, 'reg_lambda': 0.0003081660948401323, 'max_delta_step': 3}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  91%|█████████ | 182/200 [03:01<00:30,  1.70s/it]

[I 2025-11-10 14:41:38,818] Trial 181 finished with value: 0.5461988304093567 and parameters: {'max_depth': 8, 'learning_rate': 0.022540576585941403, 'n_estimators': 1030, 'subsample': 0.5435366115574687, 'colsample_bytree': 0.5408111743390054, 'min_child_weight': 1, 'gamma': 4.028961610752705, 'reg_alpha': 1.5756202312313976e-05, 'reg_lambda': 1.3924585014889455e-06, 'max_delta_step': 4}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  92%|█████████▏| 183/200 [03:02<00:25,  1.50s/it]

[I 2025-11-10 14:41:39,848] Trial 182 finished with value: 0.5492397660818713 and parameters: {'max_depth': 8, 'learning_rate': 0.02282056738779573, 'n_estimators': 1023, 'subsample': 0.5744511079462572, 'colsample_bytree': 0.5001901703914993, 'min_child_weight': 1, 'gamma': 4.128696080353483, 'reg_alpha': 1.582463959548748e-05, 'reg_lambda': 2.851961894593955e-06, 'max_delta_step': 4}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  92%|█████████▏| 184/200 [03:03<00:23,  1.49s/it]

[I 2025-11-10 14:41:41,309] Trial 183 finished with value: 0.5347953216374269 and parameters: {'max_depth': 7, 'learning_rate': 0.02194564855039397, 'n_estimators': 1049, 'subsample': 0.5602784466176565, 'colsample_bytree': 0.5316480872258132, 'min_child_weight': 1, 'gamma': 4.147412429046464, 'reg_alpha': 2.021700701298227e-05, 'reg_lambda': 2.1849107589924735e-06, 'max_delta_step': 4}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  92%|█████████▎| 185/200 [03:04<00:19,  1.27s/it]

[I 2025-11-10 14:41:42,085] Trial 184 finished with value: 0.5461988304093567 and parameters: {'max_depth': 8, 'learning_rate': 0.0196079169881789, 'n_estimators': 1028, 'subsample': 0.5534593330904112, 'colsample_bytree': 0.5349149960770162, 'min_child_weight': 1, 'gamma': 4.154809861228968, 'reg_alpha': 7.571429910316996e-06, 'reg_lambda': 1.2702187857816143e-06, 'max_delta_step': 4}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  93%|█████████▎| 186/200 [03:05<00:19,  1.37s/it]

[I 2025-11-10 14:41:43,679] Trial 188 pruned.

Best trial: 144. Best value: 0.569532:  94%|█████████▎| 187/200 [03:07<00:19,  1.50s/it]

[I 2025-11-10 14:41:45,490] Trial 185 finished with value: 0.5514619883040935 and parameters: {'max_depth': 8, 'learning_rate': 0.021130200794052475, 'n_estimators': 1040, 'subsample': 0.5508003087916522, 'colsample_bytree': 0.5147583006267018, 'min_child_weight': 1, 'gamma': 4.14725884164807, 'reg_alpha': 7.701708358805984e-06, 'reg_lambda': 2.289269898426365e-06, 'max_delta_step': 4}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  94%|█████████▍| 188/200 [03:08<00:16,  1.38s/it]

[I 2025-11-10 14:41:46,598] Trial 186 finished with value: 0.5436842105263158 and parameters: {'max_depth': 8, 'learning_rate': 0.02142326187041501, 'n_estimators': 1058, 'subsample': 0.5871966736202954, 'colsample_bytree': 0.5125379804719808, 'min_child_weight': 1, 'gamma': 3.951542844224499, 'reg_alpha': 7.628231498551317e-06, 'reg_lambda': 1.2351355157614481e-06, 'max_delta_step': 4}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  94%|█████████▍| 189/200 [03:09<00:11,  1.03s/it]

[I 2025-11-10 14:41:46,820] Trial 190 pruned.

Best trial: 144. Best value: 0.569532:  95%|█████████▌| 190/200 [03:10<00:10,  1.10s/it]

[I 2025-11-10 14:41:48,052] Trial 191 pruned.
[I 2025-11-10 14:41:48,085] Trial 187 finished with value: 0.5461988304093567 and parameters: {'max_depth': 8, 'learning_rate': 0.017937293294786136, 'n_estimators': 1074, 'subsample': 0.5455748048144067, 'colsample_bytree': 0.5148303025020134, 'min_child_weight': 1, 'gamma': 3.9559121714297865, 'reg_alpha': 9.917710111606381e-06, 'reg_lambda': 1.2026741094176914e-06, 'max_delta_step': 4}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  96%|█████████▌| 192/200 [03:11<00:07,  1.14it/s]

[I 2025-11-10 14:41:49,296] Trial 193 pruned.

Best trial: 144. Best value: 0.569532:  96%|█████████▋| 193/200 [03:12<00:06,  1.13it/s]

[I 2025-11-10 14:41:50,213] Trial 189 finished with value: 0.5606432748538012 and parameters: {'max_depth': 8, 'learning_rate': 0.020368547213223943, 'n_estimators': 1082, 'subsample': 0.5483886407364835, 'colsample_bytree': 0.5147579668507977, 'min_child_weight': 1, 'gamma': 3.9833856814332225, 'reg_alpha': 1.376128601648396e-05, 'reg_lambda': 1.1878594332122101e-06, 'max_delta_step': 4}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  97%|█████████▋| 194/200 [03:15<00:09,  1.51s/it]

[I 2025-11-10 14:41:53,465] Trial 192 finished with value: 0.5461988304093567 and parameters: {'max_depth': 8, 'learning_rate': 0.024587954409242642, 'n_estimators': 1086, 'subsample': 0.5441095075067108, 'colsample_bytree': 0.5150226752324151, 'min_child_weight': 1, 'gamma': 4.049430424514729, 'reg_alpha': 1.299099325007784e-05, 'reg_lambda': 4.709337171148762e-06, 'max_delta_step': 4}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  98%|█████████▊| 195/200 [03:16<00:06,  1.34s/it]

[I 2025-11-10 14:41:54,369] Trial 194 finished with value: 0.5239766081871345 and parameters: {'max_depth': 8, 'learning_rate': 0.019307753526776498, 'n_estimators': 1040, 'subsample': 0.574160320440806, 'colsample_bytree': 0.5248675277440626, 'min_child_weight': 1, 'gamma': 4.086060795028109, 'reg_alpha': 4.087108874079322e-05, 'reg_lambda': 2.8187472768109364e-06, 'max_delta_step': 4}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  98%|█████████▊| 196/200 [03:17<00:05,  1.31s/it]

[I 2025-11-10 14:41:55,604] Trial 195 finished with value: 0.5461988304093567 and parameters: {'max_depth': 8, 'learning_rate': 0.019472980817830582, 'n_estimators': 1036, 'subsample': 0.5484447337082639, 'colsample_bytree': 0.5249440401791767, 'min_child_weight': 1, 'gamma': 4.241338265734619, 'reg_alpha': 6.503306662459193e-06, 'reg_lambda': 2.12674052423053e-06, 'max_delta_step': 4}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  98%|█████████▊| 197/200 [03:19<00:03,  1.29s/it]

[I 2025-11-10 14:41:56,847] Trial 196 finished with value: 0.5406432748538011 and parameters: {'max_depth': 8, 'learning_rate': 0.017953793843566802, 'n_estimators': 1041, 'subsample': 0.5474112484488789, 'colsample_bytree': 0.523507719679922, 'min_child_weight': 1, 'gamma': 3.844137466068211, 'reg_alpha': 2.8530741869759766e-05, 'reg_lambda': 5.184983013416525e-07, 'max_delta_step': 4}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532:  99%|█████████▉| 198/200 [03:19<00:02,  1.00s/it]

[I 2025-11-10 14:41:57,134] Trial 198 pruned.

Best trial: 144. Best value: 0.569532: 100%|█████████▉| 199/200 [03:21<00:01,  1.36s/it]

[I 2025-11-10 14:41:59,366] Trial 197 finished with value: 0.5295321637426901 and parameters: {'max_depth': 8, 'learning_rate': 0.01906839502092185, 'n_estimators': 1082, 'subsample': 0.5521122161508845, 'colsample_bytree': 0.5255317367289916, 'min_child_weight': 1, 'gamma': 3.818976542944871, 'reg_alpha': 2.5871288211047754e-05, 'reg_lambda': 2.0954209100755826e-06, 'max_delta_step': 4}. Best is trial 144 with value: 0.5695321637426901.

Best trial: 144. Best value: 0.569532: 100%|██████████| 200/200 [03:22<00:00,  1.01s/it]

[I 2025-11-10 14:42:00,595] Trial 199 finished with value: 0.5406432748538011 and parameters: {'max_depth': 8, 'learning_rate': 0.017518076191046776, 'n_estimators': 1089, 'subsample': 0.5468335679050079, 'colsample_bytree': 0.5353697998358673, 'min_child_weight': 1, 'gamma': 3.8143105884707063, 'reg_alpha': 2.654538512663867e-05, 'reg_lambda': 6.51398806049138e-07, 'max_delta_step': 4}. Best is trial 144 with value: 0.5695321637426901.

C:\Users\tenNovy\AppData\Local\Temp\ipykernel_11656\1094786132.py:137: RuntimeWarning:

More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.

[I 2025-11-10 14:42:02,168] A new study created in memory with name: 18_1_balanced_accuracy
Best trial: 3. Best value: 0.5:   0%|          | 1/200 [00:04<14:27,  4.36s/it]

[I 2025-11-10 14:42:06,518] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.012655527064134588, 'n_estimators': 905, 'subsample': 0.9025699260655236, 'colsample_bytree': 0.8834809329492521, 'min_child_weight': 7, 'gamma': 2.461597192635501, 'reg_alpha': 0.029983049011182233, 'reg_lambda': 2.419518152228622e-08, 'max_delta_step': 1}. Best is trial 3 with value: 0.5.

Best trial: 0. Best value: 0.511228:   1%|          | 2/200 [00:04<06:50,  2.07s/it]

[I 2025-11-10 14:42:06,991] Trial 0 finished with value: 0.5112280701754386 and parameters: {'max_depth': 4, 'learning_rate': 0.013644524713598519, 'n_estimators': 582, 'subsample': 0.5553211565766819, 'colsample_bytree': 0.9825148157233297, 'min_child_weight': 2, 'gamma': 1.7018762402044685, 'reg_alpha': 0.04986945318020988, 'reg_lambda': 0.0002051213468182106, 'max_delta_step': 2}. Best is trial 0 with value: 0.5112280701754386.

Best trial: 1. Best value: 0.57345:   2%|▏         | 3/200 [00:07<06:49,  2.08s/it]

[I 2025-11-10 14:42:09,072] Trial 2 finished with value: 0.5334502923976607 and parameters: {'max_depth': 10, 'learning_rate': 0.020723012184851966, 'n_estimators': 1090, 'subsample': 0.837094612070481, 'colsample_bytree': 0.671616278751008, 'min_child_weight': 2, 'gamma': 3.7729725100156033, 'reg_alpha': 7.1016513766468e-07, 'reg_lambda': 2.325832221184143e-08, 'max_delta_step': 6}. Best is trial 2 with value: 0.5334502923976607.
[I 2025-11-10 14:42:09,170] Trial 1 finished with value: 0.5734502923976608 and parameters: {'max_depth': 10, 'learning_rate': 0.01261555390602742, 'n_estimators': 928, 'subsample': 0.8801505052621197, 'colsample_bytree': 0.6045800261300402, 'min_child_weight': 2, 'gamma': 1.5121166626767835, 'reg_alpha': 1.4811932328521533, 'reg_lambda': 2.9973689678040785, 'max_delta_step': 6}. Best is trial 1 with value: 0.5734502923976608.

Best trial: 1. Best value: 0.57345:   2%|▎         | 5/200 [00:08<04:16,  1.31s/it]

[I 2025-11-10 14:42:10,533] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.07098772225052404, 'n_estimators': 690, 'subsample': 0.5689687282923139, 'colsample_bytree': 0.9642789955552875, 'min_child_weight': 8, 'gamma': 2.7671014958446545, 'reg_alpha': 1.7501979368598813e-05, 'reg_lambda': 3.062428734716135e-08, 'max_delta_step': 0}. Best is trial 1 with value: 0.5734502923976608.

Best trial: 1. Best value: 0.57345:   4%|▎         | 7/200 [00:09<02:54,  1.10it/s]

[I 2025-11-10 14:42:11,560] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.023801083091189657, 'n_estimators': 1005, 'subsample': 0.8825700405934428, 'colsample_bytree': 0.7180988504655256, 'min_child_weight': 6, 'gamma': 4.3391500615696845, 'reg_alpha': 1.1029596232176878e-08, 'reg_lambda': 1.3542048233219262, 'max_delta_step': 3}. Best is trial 1 with value: 0.5734502923976608.
[I 2025-11-10 14:42:11,673] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.2672435433914834, 'n_estimators': 462, 'subsample': 0.9858597696853721, 'colsample_bytree': 0.77284206573179, 'min_child_weight': 9, 'gamma': 4.804262669189935, 'reg_alpha': 0.07100001889198042, 'reg_lambda': 2.0502331634923863, 'max_delta_step': 1}. Best is trial 1 with value: 0.5734502923976608.

Best trial: 1. Best value: 0.57345:   4%|▍         | 8/200 [00:10<02:44,  1.17it/s]

[I 2025-11-10 14:42:12,411] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.016978567582119908, 'n_estimators': 624, 'subsample': 0.6945684722372936, 'colsample_bytree': 0.9331780823700385, 'min_child_weight': 10, 'gamma': 4.375435068341846, 'reg_alpha': 7.151131407128937e-08, 'reg_lambda': 0.6000103265468916, 'max_delta_step': 9}. Best is trial 1 with value: 0.5734502923976608.

Best trial: 1. Best value: 0.57345:   4%|▍         | 9/200 [00:11<02:40,  1.19it/s]

[I 2025-11-10 14:42:13,215] Trial 9 finished with value: 0.5453801169590644 and parameters: {'max_depth': 6, 'learning_rate': 0.047220317983633214, 'n_estimators': 311, 'subsample': 0.9200806821765595, 'colsample_bytree': 0.8703297296833252, 'min_child_weight': 5, 'gamma': 4.871666928595737, 'reg_alpha': 0.1791041840218347, 'reg_lambda': 8.559689209516936e-07, 'max_delta_step': 0}. Best is trial 1 with value: 0.5734502923976608.

Best trial: 1. Best value: 0.57345:   5%|▌         | 10/200 [00:12<02:48,  1.13it/s]

[I 2025-11-10 14:42:14,203] Trial 10 finished with value: 0.5283625730994153 and parameters: {'max_depth': 9, 'learning_rate': 0.10936944276656484, 'n_estimators': 432, 'subsample': 0.5213161913863282, 'colsample_bytree': 0.5603842021417902, 'min_child_weight': 1, 'gamma': 2.7405345070239457, 'reg_alpha': 0.07754607369305204, 'reg_lambda': 6.851498715006087e-06, 'max_delta_step': 4}. Best is trial 1 with value: 0.5734502923976608.

Best trial: 1. Best value: 0.57345:   6%|▌         | 11/200 [00:14<03:50,  1.22s/it]

[I 2025-11-10 14:42:16,211] Trial 8 pruned.

Best trial: 1. Best value: 0.57345:   6%|▋         | 13/200 [00:15<02:34,  1.21it/s]

[I 2025-11-10 14:42:17,088] Trial 11 pruned.
[I 2025-11-10 14:42:17,224] Trial 14 pruned.

Best trial: 1. Best value: 0.57345:   7%|▋         | 14/200 [00:15<01:57,  1.58it/s]

[I 2025-11-10 14:42:17,406] Trial 12 pruned.

Best trial: 1. Best value: 0.57345:   8%|▊         | 15/200 [00:16<02:18,  1.34it/s]

[I 2025-11-10 14:42:18,424] Trial 15 pruned.

Best trial: 1. Best value: 0.57345:   8%|▊         | 16/200 [00:16<02:10,  1.41it/s]

[I 2025-11-10 14:42:19,039] Trial 16 pruned.

Best trial: 1. Best value: 0.57345:   8%|▊         | 17/200 [00:17<02:07,  1.44it/s]

[I 2025-11-10 14:42:19,703] Trial 13 pruned.
[I 2025-11-10 14:42:19,766] Trial 18 pruned.

Best trial: 1. Best value: 0.57345:  10%|▉         | 19/200 [00:17<01:23,  2.18it/s]

[I 2025-11-10 14:42:20,070] Trial 19 pruned.

Best trial: 1. Best value: 0.57345:  10%|█         | 20/200 [00:18<01:36,  1.87it/s]

[I 2025-11-10 14:42:20,843] Trial 20 pruned.

Best trial: 1. Best value: 0.57345:  10%|█         | 21/200 [00:18<01:20,  2.23it/s]

[I 2025-11-10 14:42:21,044] Trial 21 pruned.

Best trial: 1. Best value: 0.57345:  11%|█         | 22/200 [00:20<02:02,  1.45it/s]

[I 2025-11-10 14:42:22,379] Trial 24 pruned.

Best trial: 1. Best value: 0.57345:  12%|█▏        | 23/200 [00:20<01:39,  1.78it/s]

[I 2025-11-10 14:42:22,617] Trial 17 pruned.

Best trial: 1. Best value: 0.57345:  12%|█▎        | 25/200 [00:21<01:45,  1.66it/s]

[I 2025-11-10 14:42:23,930] Trial 23 finished with value: 0.5394736842105263 and parameters: {'max_depth': 6, 'learning_rate': 0.274212513522344, 'n_estimators': 381, 'subsample': 0.8629860295298558, 'colsample_bytree': 0.7719098245167414, 'min_child_weight': 1, 'gamma': 3.291782175895646, 'reg_alpha': 6.16125682907047e-05, 'reg_lambda': 6.64237847480454e-07, 'max_delta_step': 5}. Best is trial 1 with value: 0.5734502923976608.
[I 2025-11-10 14:42:24,096] Trial 26 pruned.

Best trial: 1. Best value: 0.57345:  13%|█▎        | 26/200 [00:22<01:36,  1.80it/s]

[I 2025-11-10 14:42:24,537] Trial 27 pruned.

Best trial: 1. Best value: 0.57345:  14%|█▎        | 27/200 [00:22<01:17,  2.24it/s]

[I 2025-11-10 14:42:24,727] Trial 28 pruned.

Best trial: 1. Best value: 0.57345:  14%|█▍        | 28/200 [00:22<01:03,  2.71it/s]

[I 2025-11-10 14:42:24,917] Trial 29 pruned.

Best trial: 1. Best value: 0.57345:  14%|█▍        | 29/200 [00:23<01:38,  1.74it/s]

[I 2025-11-10 14:42:25,972] Trial 31 pruned.

Best trial: 22. Best value: 0.605906:  15%|█▌        | 30/200 [00:24<01:45,  1.62it/s]

[I 2025-11-10 14:42:26,698] Trial 22 finished with value: 0.6059064327485381 and parameters: {'max_depth': 6, 'learning_rate': 0.24387210526843045, 'n_estimators': 848, 'subsample': 0.8929011774377762, 'colsample_bytree': 0.7732611419137523, 'min_child_weight': 1, 'gamma': 3.371090103529701, 'reg_alpha': 6.856613070391311e-05, 'reg_lambda': 1.1585532718092394e-06, 'max_delta_step': 4}. Best is trial 22 with value: 0.6059064327485381.

Best trial: 22. Best value: 0.605906:  16%|█▌        | 31/200 [00:24<01:24,  2.01it/s]

[I 2025-11-10 14:42:26,904] Trial 25 pruned.

Best trial: 22. Best value: 0.605906:  16%|█▌        | 32/200 [00:25<01:12,  2.31it/s]

[I 2025-11-10 14:42:27,185] Trial 32 pruned.

Best trial: 22. Best value: 0.605906:  16%|█▋        | 33/200 [00:25<01:15,  2.22it/s]

[I 2025-11-10 14:42:27,676] Trial 34 pruned.
[I 2025-11-10 14:42:27,678] Trial 30 finished with value: 0.5645029239766082 and parameters: {'max_depth': 6, 'learning_rate': 0.09507123547520385, 'n_estimators': 525, 'subsample': 0.8730198006895578, 'colsample_bytree': 0.8641255584660605, 'min_child_weight': 5, 'gamma': 4.032932014401863, 'reg_alpha': 0.007676460921064444, 'reg_lambda': 0.0010266656888930435, 'max_delta_step': 3}. Best is trial 22 with value: 0.6059064327485381.

Best trial: 22. Best value: 0.605906:  18%|█▊        | 35/200 [00:26<01:04,  2.55it/s]

[I 2025-11-10 14:42:28,329] Trial 35 pruned.

Best trial: 22. Best value: 0.605906:  18%|█▊        | 36/200 [00:26<00:59,  2.75it/s]

[I 2025-11-10 14:42:28,603] Trial 33 pruned.

Best trial: 22. Best value: 0.605906:  18%|█▊        | 37/200 [00:27<01:12,  2.23it/s]

[I 2025-11-10 14:42:29,296] Trial 36 pruned.

Best trial: 22. Best value: 0.605906:  19%|█▉        | 38/200 [00:27<01:01,  2.63it/s]

[I 2025-11-10 14:42:29,485] Trial 37 pruned.

Best trial: 22. Best value: 0.605906:  20%|█▉        | 39/200 [00:28<01:20,  1.99it/s]

[I 2025-11-10 14:42:30,306] Trial 38 pruned.

Best trial: 22. Best value: 0.605906:  20%|██        | 40/200 [00:28<01:10,  2.28it/s]

[I 2025-11-10 14:42:30,589] Trial 39 pruned.

Best trial: 22. Best value: 0.605906:  20%|██        | 41/200 [00:28<01:02,  2.53it/s]

[I 2025-11-10 14:42:30,874] Trial 41 pruned.

Best trial: 22. Best value: 0.605906:  21%|██        | 42/200 [00:29<01:04,  2.44it/s]

[I 2025-11-10 14:42:31,324] Trial 40 pruned.

Best trial: 22. Best value: 0.605906:  22%|██▏       | 43/200 [00:29<01:15,  2.09it/s]

[I 2025-11-10 14:42:31,965] Trial 43 pruned.

Best trial: 22. Best value: 0.605906:  22%|██▏       | 44/200 [00:30<01:26,  1.80it/s]

[I 2025-11-10 14:42:32,703] Trial 42 pruned.

Best trial: 22. Best value: 0.605906:  22%|██▎       | 45/200 [00:31<01:30,  1.72it/s]

[I 2025-11-10 14:42:33,350] Trial 47 pruned.

Best trial: 22. Best value: 0.605906:  23%|██▎       | 46/200 [00:31<01:16,  2.03it/s]

[I 2025-11-10 14:42:33,633] Trial 45 finished with value: 0.5745029239766082 and parameters: {'max_depth': 6, 'learning_rate': 0.2312344359614785, 'n_estimators': 304, 'subsample': 0.8701361998158395, 'colsample_bytree': 0.7803796562971235, 'min_child_weight': 1, 'gamma': 2.8402995487331477, 'reg_alpha': 2.146715729771313e-06, 'reg_lambda': 0.050985022739503914, 'max_delta_step': 4}. Best is trial 22 with value: 0.6059064327485381.

Best trial: 22. Best value: 0.605906:  24%|██▎       | 47/200 [00:31<01:07,  2.28it/s]

[I 2025-11-10 14:42:33,944] Trial 48 pruned.

Best trial: 22. Best value: 0.605906:  24%|██▍       | 48/200 [00:32<01:03,  2.38it/s]

[I 2025-11-10 14:42:34,320] Trial 49 pruned.

Best trial: 22. Best value: 0.605906:  25%|██▌       | 50/200 [00:32<00:54,  2.76it/s]

[I 2025-11-10 14:42:34,828] Trial 44 finished with value: 0.5725730994152047 and parameters: {'max_depth': 6, 'learning_rate': 0.22079579181494435, 'n_estimators': 446, 'subsample': 0.876424151469603, 'colsample_bytree': 0.8449506264733523, 'min_child_weight': 1, 'gamma': 3.689812062735424, 'reg_alpha': 1.779564432731153e-06, 'reg_lambda': 0.06786996011442085, 'max_delta_step': 4}. Best is trial 22 with value: 0.6059064327485381.
[I 2025-11-10 14:42:34,996] Trial 50 pruned.

Best trial: 46. Best value: 0.638655:  26%|██▌       | 52/200 [00:33<00:41,  3.54it/s]

[I 2025-11-10 14:42:35,244] Trial 51 pruned.
[I 2025-11-10 14:42:35,421] Trial 46 finished with value: 0.638654970760234 and parameters: {'max_depth': 6, 'learning_rate': 0.28911079489474933, 'n_estimators': 426, 'subsample': 0.8675170943918382, 'colsample_bytree': 0.7728080789558434, 'min_child_weight': 1, 'gamma': 2.9815200804455504, 'reg_alpha': 9.965539550807405e-07, 'reg_lambda': 6.544876560169713e-05, 'max_delta_step': 2}. Best is trial 46 with value: 0.638654970760234.

Best trial: 46. Best value: 0.638655:  27%|██▋       | 54/200 [00:33<00:38,  3.75it/s]

[I 2025-11-10 14:42:35,850] Trial 52 pruned.
[I 2025-11-10 14:42:35,977] Trial 53 pruned.

Best trial: 46. Best value: 0.638655:  28%|██▊       | 56/200 [00:34<00:34,  4.21it/s]

[I 2025-11-10 14:42:36,264] Trial 54 pruned.
[I 2025-11-10 14:42:36,419] Trial 55 pruned.
[I 2025-11-10 14:42:36,429] Trial 57 pruned.

Best trial: 46. Best value: 0.638655:  29%|██▉       | 58/200 [00:34<00:29,  4.85it/s]

[I 2025-11-10 14:42:36,763] Trial 56 pruned.
[I 2025-11-10 14:42:36,797] Trial 58 pruned.

Best trial: 46. Best value: 0.638655:  30%|███       | 60/200 [00:34<00:26,  5.21it/s]

[I 2025-11-10 14:42:37,099] Trial 60 pruned.

Best trial: 46. Best value: 0.638655:  30%|███       | 61/200 [00:35<00:30,  4.51it/s]

[I 2025-11-10 14:42:37,387] Trial 62 pruned.
[I 2025-11-10 14:42:37,401] Trial 61 pruned.

Best trial: 46. Best value: 0.638655:  32%|███▏      | 63/200 [00:35<00:25,  5.30it/s]

[I 2025-11-10 14:42:37,697] Trial 63 pruned.

Best trial: 46. Best value: 0.638655:  32%|███▏      | 64/200 [00:35<00:32,  4.17it/s]

[I 2025-11-10 14:42:38,129] Trial 64 pruned.

Best trial: 46. Best value: 0.638655:  33%|███▎      | 66/200 [00:37<00:44,  2.99it/s]

[I 2025-11-10 14:42:39,026] Trial 59 finished with value: 0.5639766081871345 and parameters: {'max_depth': 5, 'learning_rate': 0.24710281505763007, 'n_estimators': 345, 'subsample': 0.8595979554470731, 'colsample_bytree': 0.7004490775373095, 'min_child_weight': 2, 'gamma': 2.7585617420770934, 'reg_alpha': 4.569239661043815e-06, 'reg_lambda': 0.0023669624830388643, 'max_delta_step': 3}. Best is trial 46 with value: 0.638654970760234.
[I 2025-11-10 14:42:39,179] Trial 66 finished with value: 0.5942690058479532 and parameters: {'max_depth': 6, 'learning_rate': 0.29399174267846895, 'n_estimators': 200, 'subsample': 0.8958784839873646, 'colsample_bytree': 0.818134901273484, 'min_child_weight': 3, 'gamma': 4.651420910181589, 'reg_alpha': 1.2720400373039764, 'reg_lambda': 0.17435095812938223, 'max_delta_step': 0}. Best is trial 46 with value: 0.638654970760234.

Best trial: 46. Best value: 0.638655:  34%|███▎      | 67/200 [00:37<00:40,  3.31it/s]

[I 2025-11-10 14:42:39,383] Trial 67 finished with value: 0.5631578947368421 and parameters: {'max_depth': 6, 'learning_rate': 0.03054348450542647, 'n_estimators': 207, 'subsample': 0.9439007203115828, 'colsample_bytree': 0.5753445708147494, 'min_child_weight': 4, 'gamma': 3.521230607891088, 'reg_alpha': 3.1814963068146733, 'reg_lambda': 9.440723311842763e-06, 'max_delta_step': 4}. Best is trial 46 with value: 0.638654970760234.

Best trial: 46. Best value: 0.638655:  34%|███▍      | 68/200 [00:37<00:43,  3.07it/s]

[I 2025-11-10 14:42:39,780] Trial 69 pruned.

Best trial: 46. Best value: 0.638655:  35%|███▌      | 70/200 [00:38<00:38,  3.37it/s]

[I 2025-11-10 14:42:40,212] Trial 70 pruned.
[I 2025-11-10 14:42:40,357] Trial 68 pruned.

Best trial: 46. Best value: 0.638655:  36%|███▌      | 71/200 [00:38<00:42,  3.05it/s]

[I 2025-11-10 14:42:40,762] Trial 71 pruned.

Best trial: 46. Best value: 0.638655:  37%|███▋      | 74/200 [00:39<00:29,  4.34it/s]

[I 2025-11-10 14:42:41,252] Trial 74 pruned.
[I 2025-11-10 14:42:41,345] Trial 73 pruned.
[I 2025-11-10 14:42:41,350] Trial 72 pruned.

Best trial: 46. Best value: 0.638655:  38%|███▊      | 75/200 [00:39<00:37,  3.31it/s]

[I 2025-11-10 14:42:41,887] Trial 65 pruned.

Best trial: 46. Best value: 0.638655:  38%|███▊      | 76/200 [00:40<00:42,  2.94it/s]

[I 2025-11-10 14:42:42,330] Trial 76 pruned.
[I 2025-11-10 14:42:42,427] Trial 77 pruned.

Best trial: 46. Best value: 0.638655:  39%|███▉      | 78/200 [00:40<00:36,  3.39it/s]

[I 2025-11-10 14:42:42,810] Trial 75 pruned.

Best trial: 46. Best value: 0.638655:  40%|███▉      | 79/200 [00:41<00:43,  2.79it/s]

[I 2025-11-10 14:42:43,374] Trial 81 pruned.

Best trial: 46. Best value: 0.638655:  40%|████      | 80/200 [00:41<00:40,  2.96it/s]

[I 2025-11-10 14:42:43,652] Trial 79 pruned.

Best trial: 46. Best value: 0.638655:  40%|████      | 81/200 [00:42<00:53,  2.21it/s]

[I 2025-11-10 14:42:44,421] Trial 82 pruned.

Best trial: 46. Best value: 0.638655:  41%|████      | 82/200 [00:42<00:47,  2.46it/s]

[I 2025-11-10 14:42:44,707] Trial 80 pruned.
[I 2025-11-10 14:42:44,772] Trial 84 pruned.

Best trial: 46. Best value: 0.638655:  42%|████▎     | 85/200 [00:43<00:30,  3.74it/s]

[I 2025-11-10 14:42:45,094] Trial 85 pruned.
[I 2025-11-10 14:42:45,217] Trial 86 pruned.

Best trial: 46. Best value: 0.638655:  43%|████▎     | 86/200 [00:43<00:42,  2.71it/s]

[I 2025-11-10 14:42:45,880] Trial 87 pruned.

Best trial: 46. Best value: 0.638655:  44%|████▎     | 87/200 [00:44<00:49,  2.27it/s]

[I 2025-11-10 14:42:46,514] Trial 88 pruned.

Best trial: 46. Best value: 0.638655:  44%|████▍     | 88/200 [00:45<01:19,  1.41it/s]

[I 2025-11-10 14:42:47,940] Trial 83 finished with value: 0.5839181286549707 and parameters: {'max_depth': 4, 'learning_rate': 0.2034180655592097, 'n_estimators': 720, 'subsample': 0.8925149670027545, 'colsample_bytree': 0.5471275138095856, 'min_child_weight': 1, 'gamma': 0.04641587560779259, 'reg_alpha': 6.59603649880119e-05, 'reg_lambda': 0.0012717388135860465, 'max_delta_step': 3}. Best is trial 46 with value: 0.638654970760234.

Best trial: 46. Best value: 0.638655:  44%|████▍     | 89/200 [00:46<01:14,  1.49it/s]

[I 2025-11-10 14:42:48,500] Trial 90 finished with value: 0.6028654970760233 and parameters: {'max_depth': 5, 'learning_rate': 0.10505101274644911, 'n_estimators': 320, 'subsample': 0.8739913460202339, 'colsample_bytree': 0.5049739831209895, 'min_child_weight': 5, 'gamma': 3.7524427054831286, 'reg_alpha': 1.0723153036577828, 'reg_lambda': 4.663266856034356e-06, 'max_delta_step': 4}. Best is trial 46 with value: 0.638654970760234.

Best trial: 46. Best value: 0.638655:  45%|████▌     | 90/200 [00:46<01:05,  1.68it/s]

[I 2025-11-10 14:42:48,919] Trial 91 pruned.

Best trial: 46. Best value: 0.638655:  46%|████▌     | 91/200 [00:47<01:00,  1.82it/s]

[I 2025-11-10 14:42:49,362] Trial 92 pruned.

Best trial: 46. Best value: 0.638655:  46%|████▌     | 92/200 [00:47<00:51,  2.08it/s]

[I 2025-11-10 14:42:49,678] Trial 93 pruned.

Best trial: 46. Best value: 0.638655:  46%|████▋     | 93/200 [00:48<00:53,  1.99it/s]

[I 2025-11-10 14:42:50,229] Trial 94 pruned.

Best trial: 46. Best value: 0.638655:  48%|████▊     | 95/200 [00:49<00:48,  2.16it/s]

[I 2025-11-10 14:42:51,005] Trial 78 finished with value: 0.5964912280701755 and parameters: {'max_depth': 7, 'learning_rate': 0.1970958738901521, 'n_estimators': 1210, 'subsample': 0.9273908782006415, 'colsample_bytree': 0.7297407828528314, 'min_child_weight': 2, 'gamma': 4.335115344462703, 'reg_alpha': 1.2368363246368678e-06, 'reg_lambda': 5.192636023273289, 'max_delta_step': 3}. Best is trial 46 with value: 0.638654970760234.
[I 2025-11-10 14:42:51,185] Trial 96 pruned.

Best trial: 46. Best value: 0.638655:  48%|████▊     | 96/200 [00:49<00:43,  2.38it/s]

[I 2025-11-10 14:42:51,512] Trial 89 finished with value: 0.5687134502923976 and parameters: {'max_depth': 10, 'learning_rate': 0.21314666331836285, 'n_estimators': 1054, 'subsample': 0.8898361705703349, 'colsample_bytree': 0.6178795185099696, 'min_child_weight': 5, 'gamma': 3.69640905630452, 'reg_alpha': 1.6318319286686647, 'reg_lambda': 2.1981507558298754e-05, 'max_delta_step': 5}. Best is trial 46 with value: 0.638654970760234.

Best trial: 46. Best value: 0.638655:  48%|████▊     | 97/200 [00:49<00:49,  2.09it/s]

[I 2025-11-10 14:42:52,129] Trial 98 pruned.

Best trial: 46. Best value: 0.638655:  49%|████▉     | 98/200 [00:50<01:04,  1.57it/s]

[I 2025-11-10 14:42:53,127] Trial 99 pruned.

Best trial: 46. Best value: 0.638655:  50%|████▉     | 99/200 [00:51<01:14,  1.35it/s]

[I 2025-11-10 14:42:54,100] Trial 100 pruned.

Best trial: 46. Best value: 0.638655:  50%|█████     | 100/200 [00:52<00:59,  1.68it/s]

[I 2025-11-10 14:42:54,355] Trial 95 finished with value: 0.5798245614035087 and parameters: {'max_depth': 10, 'learning_rate': 0.20640654392722274, 'n_estimators': 957, 'subsample': 0.89266018251903, 'colsample_bytree': 0.5607630868060584, 'min_child_weight': 5, 'gamma': 0.34520480307583545, 'reg_alpha': 6.929981984058378e-06, 'reg_lambda': 2.830359916363802e-07, 'max_delta_step': 3}. Best is trial 46 with value: 0.638654970760234.

Best trial: 46. Best value: 0.638655:  50%|█████     | 101/200 [00:52<00:48,  2.03it/s]

[I 2025-11-10 14:42:54,618] Trial 101 pruned.
[I 2025-11-10 14:42:54,666] Trial 97 pruned.

Best trial: 46. Best value: 0.638655:  52%|█████▏    | 103/200 [00:53<00:52,  1.85it/s]

[I 2025-11-10 14:42:55,811] Trial 105 pruned.
[I 2025-11-10 14:42:55,825] Trial 103 pruned.

Best trial: 46. Best value: 0.638655:  52%|█████▎    | 105/200 [00:54<00:38,  2.49it/s]

[I 2025-11-10 14:42:56,200] Trial 102 pruned.

Best trial: 46. Best value: 0.638655:  54%|█████▎    | 107/200 [00:54<00:37,  2.50it/s]

[I 2025-11-10 14:42:56,955] Trial 106 pruned.
[I 2025-11-10 14:42:57,095] Trial 107 pruned.

Best trial: 46. Best value: 0.638655:  54%|█████▍    | 108/200 [00:55<00:46,  1.98it/s]

[I 2025-11-10 14:42:57,913] Trial 109 pruned.

Best trial: 46. Best value: 0.638655:  55%|█████▍    | 109/200 [00:55<00:39,  2.31it/s]

[I 2025-11-10 14:42:58,146] Trial 110 pruned.

Best trial: 46. Best value: 0.638655:  55%|█████▌    | 110/200 [00:56<00:36,  2.43it/s]

[I 2025-11-10 14:42:58,499] Trial 108 pruned.

Best trial: 46. Best value: 0.638655:  56%|█████▌    | 111/200 [00:56<00:39,  2.23it/s]

[I 2025-11-10 14:42:59,037] Trial 111 pruned.

Best trial: 46. Best value: 0.638655:  56%|█████▌    | 112/200 [00:57<00:43,  2.01it/s]

[I 2025-11-10 14:42:59,661] Trial 112 pruned.

Best trial: 46. Best value: 0.638655:  56%|█████▋    | 113/200 [00:57<00:35,  2.44it/s]

[I 2025-11-10 14:42:59,852] Trial 113 pruned.

Best trial: 46. Best value: 0.638655:  57%|█████▊    | 115/200 [00:58<00:36,  2.34it/s]

[I 2025-11-10 14:43:00,736] Trial 116 pruned.
[I 2025-11-10 14:43:00,879] Trial 104 finished with value: 0.5742690058479532 and parameters: {'max_depth': 9, 'learning_rate': 0.27008618419785985, 'n_estimators': 1111, 'subsample': 0.8949253605929196, 'colsample_bytree': 0.5922595210822543, 'min_child_weight': 5, 'gamma': 0.14056188150185095, 'reg_alpha': 5.592840036859311e-07, 'reg_lambda': 2.3512002102691367, 'max_delta_step': 3}. Best is trial 46 with value: 0.638654970760234.

Best trial: 46. Best value: 0.638655:  58%|█████▊    | 116/200 [00:58<00:29,  2.86it/s]

[I 2025-11-10 14:43:01,039] Trial 115 pruned.

Best trial: 46. Best value: 0.638655:  58%|█████▊    | 117/200 [00:59<00:25,  3.23it/s]

[I 2025-11-10 14:43:01,263] Trial 117 pruned.

Best trial: 46. Best value: 0.638655:  59%|█████▉    | 118/200 [00:59<00:25,  3.26it/s]

[I 2025-11-10 14:43:01,548] Trial 114 pruned.

Best trial: 46. Best value: 0.638655:  60%|█████▉    | 119/200 [01:00<00:38,  2.11it/s]

[I 2025-11-10 14:43:02,419] Trial 118 pruned.

Best trial: 46. Best value: 0.638655:  60%|██████    | 120/200 [01:00<00:31,  2.51it/s]

[I 2025-11-10 14:43:02,640] Trial 119 pruned.

Best trial: 46. Best value: 0.638655:  60%|██████    | 121/200 [01:00<00:28,  2.76it/s]

[I 2025-11-10 14:43:02,920] Trial 120 pruned.
[I 2025-11-10 14:43:02,966] Trial 121 pruned.

Best trial: 46. Best value: 0.638655:  62%|██████▏   | 123/200 [01:01<00:19,  3.85it/s]

[I 2025-11-10 14:43:03,199] Trial 123 pruned.

Best trial: 46. Best value: 0.638655:  62%|██████▏   | 124/200 [01:01<00:19,  3.83it/s]

[I 2025-11-10 14:43:03,465] Trial 125 pruned.

Best trial: 46. Best value: 0.638655:  62%|██████▎   | 125/200 [01:01<00:27,  2.69it/s]

[I 2025-11-10 14:43:04,151] Trial 124 pruned.

Best trial: 46. Best value: 0.638655:  63%|██████▎   | 126/200 [01:02<00:30,  2.42it/s]

[I 2025-11-10 14:43:04,676] Trial 126 pruned.

Best trial: 46. Best value: 0.638655:  64%|██████▍   | 128/200 [01:05<01:06,  1.09it/s]

[I 2025-11-10 14:43:08,006] Trial 128 finished with value: 0.6314619883040936 and parameters: {'max_depth': 6, 'learning_rate': 0.28441173614743187, 'n_estimators': 470, 'subsample': 0.9044836692961196, 'colsample_bytree': 0.5699887936426015, 'min_child_weight': 1, 'gamma': 3.830554606056189, 'reg_alpha': 1.1868094614588783e-06, 'reg_lambda': 3.9949313828715964e-05, 'max_delta_step': 3}. Best is trial 46 with value: 0.638654970760234.
[I 2025-11-10 14:43:08,137] Trial 129 pruned.

Best trial: 46. Best value: 0.638655:  64%|██████▍   | 129/200 [01:06<00:52,  1.35it/s]

[I 2025-11-10 14:43:08,444] Trial 122 finished with value: 0.5819883040935673 and parameters: {'max_depth': 7, 'learning_rate': 0.2572535771150447, 'n_estimators': 1029, 'subsample': 0.8563449472331423, 'colsample_bytree': 0.6180283237182215, 'min_child_weight': 1, 'gamma': 0.19787491109478336, 'reg_alpha': 2.5949139862494356e-06, 'reg_lambda': 0.10237068379853125, 'max_delta_step': 4}. Best is trial 46 with value: 0.638654970760234.

Best trial: 46. Best value: 0.638655:  65%|██████▌   | 130/200 [01:06<00:48,  1.44it/s]

[I 2025-11-10 14:43:09,027] Trial 132 pruned.

Best trial: 46. Best value: 0.638655:  66%|██████▌   | 131/200 [01:07<00:40,  1.71it/s]

[I 2025-11-10 14:43:09,357] Trial 130 pruned.

Best trial: 46. Best value: 0.638655:  66%|██████▌   | 132/200 [01:08<00:47,  1.44it/s]

[I 2025-11-10 14:43:10,304] Trial 133 pruned.

Best trial: 46. Best value: 0.638655:  66%|██████▋   | 133/200 [01:08<00:42,  1.56it/s]

[I 2025-11-10 14:43:10,822] Trial 127 finished with value: 0.5976023391812866 and parameters: {'max_depth': 6, 'learning_rate': 0.07076058404633082, 'n_estimators': 1036, 'subsample': 0.9053676834897317, 'colsample_bytree': 0.5704980918223684, 'min_child_weight': 1, 'gamma': 4.567310165819495, 'reg_alpha': 1.1594875833092458e-06, 'reg_lambda': 4.300201799426458, 'max_delta_step': 3}. Best is trial 46 with value: 0.638654970760234.

Best trial: 46. Best value: 0.638655:  67%|██████▋   | 134/200 [01:09<00:49,  1.34it/s]

[I 2025-11-10 14:43:11,826] Trial 134 pruned.
[I 2025-11-10 14:43:11,863] Trial 135 pruned.

Best trial: 46. Best value: 0.638655:  68%|██████▊   | 136/200 [01:09<00:29,  2.15it/s]

[I 2025-11-10 14:43:12,079] Trial 136 pruned.

Best trial: 46. Best value: 0.638655:  68%|██████▊   | 137/200 [01:10<00:38,  1.66it/s]

[I 2025-11-10 14:43:13,115] Trial 138 pruned.

Best trial: 46. Best value: 0.638655:  69%|██████▉   | 138/200 [01:11<00:34,  1.81it/s]

[I 2025-11-10 14:43:13,527] Trial 139 pruned.

Best trial: 46. Best value: 0.638655:  70%|██████▉   | 139/200 [01:12<00:38,  1.58it/s]

[I 2025-11-10 14:43:14,367] Trial 137 finished with value: 0.6119883040935672 and parameters: {'max_depth': 6, 'learning_rate': 0.227783760017245, 'n_estimators': 418, 'subsample': 0.9188099672733943, 'colsample_bytree': 0.5443520191832583, 'min_child_weight': 1, 'gamma': 0.5067470333452551, 'reg_alpha': 6.169899879889933e-07, 'reg_lambda': 0.054788180711061674, 'max_delta_step': 3}. Best is trial 46 with value: 0.638654970760234.

Best trial: 131. Best value: 0.642281:  70%|███████   | 140/200 [01:12<00:40,  1.50it/s]

[I 2025-11-10 14:43:15,127] Trial 131 finished with value: 0.6422807017543859 and parameters: {'max_depth': 7, 'learning_rate': 0.28230366124185763, 'n_estimators': 941, 'subsample': 0.9105944276847177, 'colsample_bytree': 0.5750603131981658, 'min_child_weight': 1, 'gamma': 3.4660010975891495, 'reg_alpha': 0.14528345666906087, 'reg_lambda': 0.0001328203202855639, 'max_delta_step': 5}. Best is trial 131 with value: 0.6422807017543859.

Best trial: 131. Best value: 0.642281:  70%|███████   | 141/200 [01:13<00:33,  1.77it/s]

[I 2025-11-10 14:43:15,435] Trial 141 pruned.

Best trial: 131. Best value: 0.642281:  71%|███████   | 142/200 [01:14<00:45,  1.28it/s]

[I 2025-11-10 14:43:16,740] Trial 140 pruned.

Best trial: 131. Best value: 0.642281:  72%|███████▏  | 143/200 [01:14<00:37,  1.54it/s]

[I 2025-11-10 14:43:17,085] Trial 144 pruned.
[I 2025-11-10 14:43:17,132] Trial 143 pruned.

Best trial: 131. Best value: 0.642281:  72%|███████▎  | 145/200 [01:15<00:30,  1.78it/s]

[I 2025-11-10 14:43:17,994] Trial 145 pruned.

Best trial: 131. Best value: 0.642281:  73%|███████▎  | 146/200 [01:16<00:28,  1.90it/s]

[I 2025-11-10 14:43:18,408] Trial 146 pruned.

Best trial: 131. Best value: 0.642281:  74%|███████▎  | 147/200 [01:16<00:23,  2.26it/s]

[I 2025-11-10 14:43:18,610] Trial 148 pruned.

Best trial: 131. Best value: 0.642281:  74%|███████▍  | 148/200 [01:16<00:21,  2.37it/s]

[I 2025-11-10 14:43:18,980] Trial 149 pruned.

Best trial: 131. Best value: 0.642281:  74%|███████▍  | 149/200 [01:17<00:18,  2.80it/s]

[I 2025-11-10 14:43:19,167] Trial 150 pruned.

Best trial: 131. Best value: 0.642281:  76%|███████▌  | 151/200 [01:18<00:23,  2.05it/s]

[I 2025-11-10 14:43:20,477] Trial 152 pruned.
[I 2025-11-10 14:43:20,615] Trial 151 pruned.

Best trial: 131. Best value: 0.642281:  76%|███████▋  | 153/200 [01:19<00:17,  2.68it/s]

[I 2025-11-10 14:43:21,037] Trial 142 finished with value: 0.5842105263157894 and parameters: {'max_depth': 4, 'learning_rate': 0.2635770199649693, 'n_estimators': 1018, 'subsample': 0.9272973716937087, 'colsample_bytree': 0.718088606731434, 'min_child_weight': 1, 'gamma': 0.5417736145427603, 'reg_alpha': 1.0581905576158038e-07, 'reg_lambda': 0.02730129430756641, 'max_delta_step': 3}. Best is trial 131 with value: 0.6422807017543859.
[I 2025-11-10 14:43:21,183] Trial 153 pruned.

Best trial: 131. Best value: 0.642281:  78%|███████▊  | 155/200 [01:20<00:22,  2.04it/s]

[I 2025-11-10 14:43:22,450] Trial 155 pruned.
[I 2025-11-10 14:43:22,589] Trial 156 pruned.

Best trial: 131. Best value: 0.642281:  78%|███████▊  | 156/200 [01:21<00:24,  1.78it/s]

[I 2025-11-10 14:43:23,318] Trial 157 pruned.

Best trial: 131. Best value: 0.642281:  78%|███████▊  | 157/200 [01:21<00:19,  2.20it/s]

[I 2025-11-10 14:43:23,522] Trial 147 finished with value: 0.558654970760234 and parameters: {'max_depth': 8, 'learning_rate': 0.2059294585730898, 'n_estimators': 971, 'subsample': 0.9207490179535749, 'colsample_bytree': 0.6037711122796413, 'min_child_weight': 1, 'gamma': 0.948396675510782, 'reg_alpha': 4.6243095900154345e-05, 'reg_lambda': 0.032958121427745665, 'max_delta_step': 3}. Best is trial 131 with value: 0.6422807017543859.

Best trial: 131. Best value: 0.642281:  79%|███████▉  | 158/200 [01:21<00:15,  2.64it/s]

[I 2025-11-10 14:43:23,721] Trial 158 pruned.

Best trial: 131. Best value: 0.642281:  80%|███████▉  | 159/200 [01:21<00:15,  2.58it/s]

[I 2025-11-10 14:43:24,132] Trial 160 pruned.

Best trial: 131. Best value: 0.642281:  80%|████████  | 160/200 [01:22<00:17,  2.34it/s]

[I 2025-11-10 14:43:24,652] Trial 159 pruned.

Best trial: 131. Best value: 0.642281:  80%|████████  | 161/200 [01:22<00:15,  2.53it/s]

[I 2025-11-10 14:43:24,971] Trial 162 pruned.
[I 2025-11-10 14:43:24,978] Trial 154 finished with value: 0.6105847953216375 and parameters: {'max_depth': 6, 'learning_rate': 0.22329756949922963, 'n_estimators': 465, 'subsample': 0.8826812725857076, 'colsample_bytree': 0.7339852947974501, 'min_child_weight': 1, 'gamma': 3.5100655275326336, 'reg_alpha': 3.884566026150191e-06, 'reg_lambda': 0.0643836730528549, 'max_delta_step': 4}. Best is trial 131 with value: 0.6422807017543859.

Best trial: 131. Best value: 0.642281:  82%|████████▏ | 163/200 [01:23<00:12,  2.90it/s]

[I 2025-11-10 14:43:25,549] Trial 161 pruned.

Best trial: 131. Best value: 0.642281:  82%|████████▏ | 164/200 [01:23<00:13,  2.70it/s]

[I 2025-11-10 14:43:25,990] Trial 164 pruned.
[I 2025-11-10 14:43:26,009] Trial 165 pruned.

Best trial: 131. Best value: 0.642281:  83%|████████▎ | 166/200 [01:24<00:10,  3.26it/s]

[I 2025-11-10 14:43:26,423] Trial 166 pruned.

Best trial: 131. Best value: 0.642281:  84%|████████▎ | 167/200 [01:24<00:09,  3.54it/s]

[I 2025-11-10 14:43:26,626] Trial 163 pruned.

Best trial: 131. Best value: 0.642281:  84%|████████▍ | 168/200 [01:25<00:11,  2.81it/s]

[I 2025-11-10 14:43:27,205] Trial 169 pruned.

Best trial: 131. Best value: 0.642281:  84%|████████▍ | 169/200 [01:25<00:11,  2.65it/s]

[I 2025-11-10 14:43:27,643] Trial 168 pruned.

Best trial: 131. Best value: 0.642281:  85%|████████▌ | 170/200 [01:25<00:09,  3.07it/s]

[I 2025-11-10 14:43:27,832] Trial 170 pruned.
[I 2025-11-10 14:43:27,852] Trial 167 pruned.

Best trial: 131. Best value: 0.642281:  86%|████████▌ | 172/200 [01:26<00:09,  2.82it/s]

[I 2025-11-10 14:43:28,616] Trial 174 pruned.

Best trial: 131. Best value: 0.642281:  86%|████████▋ | 173/200 [01:26<00:08,  3.08it/s]

[I 2025-11-10 14:43:28,843] Trial 171 pruned.

Best trial: 131. Best value: 0.642281:  87%|████████▋ | 174/200 [01:29<00:23,  1.10it/s]

[I 2025-11-10 14:43:31,470] Trial 175 finished with value: 0.559766081871345 and parameters: {'max_depth': 6, 'learning_rate': 0.27817829943960243, 'n_estimators': 427, 'subsample': 0.8616189150592246, 'colsample_bytree': 0.8498568594517211, 'min_child_weight': 1, 'gamma': 3.649162199829112, 'reg_alpha': 1.1814123075185814e-06, 'reg_lambda': 0.10049761628145733, 'max_delta_step': 4}. Best is trial 131 with value: 0.6422807017543859.

Best trial: 131. Best value: 0.642281:  88%|████████▊ | 175/200 [01:29<00:20,  1.24it/s]

[I 2025-11-10 14:43:31,987] Trial 176 finished with value: 0.4886549707602338 and parameters: {'max_depth': 6, 'learning_rate': 0.19127069983074096, 'n_estimators': 442, 'subsample': 0.8602639554076708, 'colsample_bytree': 0.8126285326555458, 'min_child_weight': 1, 'gamma': 3.6580802367124416, 'reg_alpha': 1.0522436271485897e-06, 'reg_lambda': 0.11709391408511528, 'max_delta_step': 3}. Best is trial 131 with value: 0.6422807017543859.

Best trial: 131. Best value: 0.642281:  88%|████████▊ | 176/200 [01:30<00:15,  1.58it/s]

[I 2025-11-10 14:43:32,173] Trial 177 pruned.

Best trial: 131. Best value: 0.642281:  88%|████████▊ | 177/200 [01:30<00:14,  1.55it/s]

[I 2025-11-10 14:43:32,841] Trial 179 pruned.

Best trial: 131. Best value: 0.642281:  89%|████████▉ | 178/200 [01:30<00:11,  1.88it/s]

[I 2025-11-10 14:43:33,098] Trial 178 pruned.

Best trial: 131. Best value: 0.642281:  90%|████████▉ | 179/200 [01:31<00:11,  1.85it/s]

[I 2025-11-10 14:43:33,655] Trial 180 pruned.

Best trial: 131. Best value: 0.642281:  90%|█████████ | 180/200 [01:31<00:08,  2.30it/s]

[I 2025-11-10 14:43:33,837] Trial 173 finished with value: 0.6314619883040936 and parameters: {'max_depth': 5, 'learning_rate': 0.27361694746365683, 'n_estimators': 883, 'subsample': 0.9079581856697133, 'colsample_bytree': 0.6860902712601906, 'min_child_weight': 1, 'gamma': 3.5891294802227343, 'reg_alpha': 1.334322956415706e-08, 'reg_lambda': 0.0015991032925555325, 'max_delta_step': 4}. Best is trial 131 with value: 0.6422807017543859.

Best trial: 131. Best value: 0.642281:  90%|█████████ | 181/200 [01:32<00:11,  1.70it/s]

[I 2025-11-10 14:43:34,799] Trial 181 pruned.

Best trial: 131. Best value: 0.642281:  91%|█████████ | 182/200 [01:32<00:08,  2.07it/s]

[I 2025-11-10 14:43:35,033] Trial 182 pruned.
[I 2025-11-10 14:43:35,081] Trial 183 pruned.

Best trial: 131. Best value: 0.642281:  92%|█████████▏| 184/200 [01:33<00:05,  2.79it/s]

[I 2025-11-10 14:43:35,452] Trial 172 finished with value: 0.5764327485380116 and parameters: {'max_depth': 5, 'learning_rate': 0.20189958943768338, 'n_estimators': 1127, 'subsample': 0.8534231617371641, 'colsample_bytree': 0.7500099959353294, 'min_child_weight': 1, 'gamma': 3.5996200507719824, 'reg_alpha': 9.983139180949976e-07, 'reg_lambda': 1.4178169173658206e-07, 'max_delta_step': 3}. Best is trial 131 with value: 0.6422807017543859.

Best trial: 131. Best value: 0.642281:  93%|█████████▎| 186/200 [01:34<00:05,  2.45it/s]

[I 2025-11-10 14:43:36,447] Trial 185 pruned.
[I 2025-11-10 14:43:36,547] Trial 186 pruned.

Best trial: 131. Best value: 0.642281:  94%|█████████▎| 187/200 [01:35<00:06,  1.95it/s]

[I 2025-11-10 14:43:37,342] Trial 184 pruned.

Best trial: 131. Best value: 0.642281:  94%|█████████▍| 188/200 [01:35<00:05,  2.00it/s]

[I 2025-11-10 14:43:37,805] Trial 190 pruned.

Best trial: 131. Best value: 0.642281:  94%|█████████▍| 189/200 [01:36<00:05,  2.01it/s]

[I 2025-11-10 14:43:38,300] Trial 189 pruned.

Best trial: 131. Best value: 0.642281:  95%|█████████▌| 190/200 [01:37<00:08,  1.18it/s]

[I 2025-11-10 14:43:40,004] Trial 192 pruned.

Best trial: 131. Best value: 0.642281:  96%|█████████▌| 191/200 [01:38<00:08,  1.10it/s]

[I 2025-11-10 14:43:41,056] Trial 193 pruned.

Best trial: 131. Best value: 0.642281:  96%|█████████▌| 192/200 [01:40<00:08,  1.02s/it]

[I 2025-11-10 14:43:42,335] Trial 194 pruned.
[I 2025-11-10 14:43:42,345] Trial 188 finished with value: 0.5986549707602339 and parameters: {'max_depth': 5, 'learning_rate': 0.28032219232387445, 'n_estimators': 1144, 'subsample': 0.9154963870613195, 'colsample_bytree': 0.7529524579115158, 'min_child_weight': 1, 'gamma': 0.26133533728023617, 'reg_alpha': 7.361558013305727e-07, 'reg_lambda': 2.264291053273656e-07, 'max_delta_step': 3}. Best is trial 131 with value: 0.6422807017543859.

Best trial: 131. Best value: 0.642281:  97%|█████████▋| 194/200 [01:41<00:04,  1.21it/s]

[I 2025-11-10 14:43:43,529] Trial 196 pruned.

Best trial: 131. Best value: 0.642281:  98%|█████████▊| 195/200 [01:42<00:04,  1.17it/s]

[I 2025-11-10 14:43:44,472] Trial 187 finished with value: 0.6173099415204678 and parameters: {'max_depth': 5, 'learning_rate': 0.29934752396935055, 'n_estimators': 1210, 'subsample': 0.9151320613063902, 'colsample_bytree': 0.763818735975302, 'min_child_weight': 1, 'gamma': 3.1144358996932464, 'reg_alpha': 1.1023842114221816e-08, 'reg_lambda': 0.0007784724663544629, 'max_delta_step': 3}. Best is trial 131 with value: 0.6422807017543859.

Best trial: 131. Best value: 0.642281:  98%|█████████▊| 196/200 [01:42<00:02,  1.37it/s]

[I 2025-11-10 14:43:44,844] Trial 197 pruned.

Best trial: 131. Best value: 0.642281:  99%|█████████▉| 198/200 [01:43<00:01,  1.59it/s]

[I 2025-11-10 14:43:45,909] Trial 191 finished with value: 0.6003508771929824 and parameters: {'max_depth': 7, 'learning_rate': 0.24876776894245042, 'n_estimators': 1158, 'subsample': 0.9000194740008036, 'colsample_bytree': 0.754739588802779, 'min_child_weight': 1, 'gamma': 3.5813704375797304, 'reg_alpha': 2.62023232836863e-07, 'reg_lambda': 4.699037156412628e-08, 'max_delta_step': 3}. Best is trial 131 with value: 0.6422807017543859.
[I 2025-11-10 14:43:46,044] Trial 198 pruned.

Best trial: 131. Best value: 0.642281: 100%|█████████▉| 199/200 [01:44<00:00,  1.81it/s]

[I 2025-11-10 14:43:46,412] Trial 199 pruned.

Best trial: 131. Best value: 0.642281: 100%|██████████| 200/200 [01:45<00:00,  1.89it/s]

[I 2025-11-10 14:43:47,786] Trial 195 finished with value: 0.5530994152046784 and parameters: {'max_depth': 5, 'learning_rate': 0.252638065695535, 'n_estimators': 1129, 'subsample': 0.9013340060504319, 'colsample_bytree': 0.7606266219203905, 'min_child_weight': 1, 'gamma': 0.4360952419074522, 'reg_alpha': 3.013102797136946e-07, 'reg_lambda': 1.601681872644004e-07, 'max_delta_step': 3}. Best is trial 131 with value: 0.6422807017543859.

[I 2025-11-10 14:43:49,251] A new study created in memory with name: 19_1_balanced_accuracy
Best trial: 2. Best value: 0.5:   0%|          | 1/200 [00:01<05:41,  1.71s/it]

[I 2025-11-10 14:43:50,960] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.058210338442954986, 'n_estimators': 290, 'subsample': 0.9006123910387088, 'colsample_bytree': 0.9968880559003234, 'min_child_weight': 7, 'gamma': 4.5475031332596565, 'reg_alpha': 0.014096343911254562, 'reg_lambda': 0.02828412862849114, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   1%|          | 2/200 [00:04<07:57,  2.41s/it]

[I 2025-11-10 14:43:53,851] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.1511720384937706, 'n_estimators': 1049, 'subsample': 0.8003302521533333, 'colsample_bytree': 0.5270144497354479, 'min_child_weight': 5, 'gamma': 1.7646864552438757, 'reg_alpha': 5.498805251153687e-05, 'reg_lambda': 0.051329485446714604, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 0. Best value: 0.667451:   2%|▏         | 3/200 [00:05<05:59,  1.83s/it]

[I 2025-11-10 14:43:54,985] Trial 0 finished with value: 0.6674509803921568 and parameters: {'max_depth': 9, 'learning_rate': 0.035064109750770706, 'n_estimators': 1157, 'subsample': 0.7117654415448145, 'colsample_bytree': 0.736055148851887, 'min_child_weight': 4, 'gamma': 0.035468312769578736, 'reg_alpha': 5.535896467360319e-07, 'reg_lambda': 0.6415195415348252, 'max_delta_step': 9}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:   2%|▏         | 4/200 [00:06<04:11,  1.28s/it]

[I 2025-11-10 14:43:55,435] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.13998023100788334, 'n_estimators': 980, 'subsample': 0.8928771160650526, 'colsample_bytree': 0.7023640568310068, 'min_child_weight': 6, 'gamma': 4.931411954614879, 'reg_alpha': 0.0045044050188277705, 'reg_lambda': 0.03716405732931765, 'max_delta_step': 8}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:   2%|▎         | 5/200 [00:07<03:43,  1.15s/it]

[I 2025-11-10 14:43:56,342] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.11525205719916196, 'n_estimators': 1494, 'subsample': 0.5156240359780644, 'colsample_bytree': 0.6484599931679738, 'min_child_weight': 9, 'gamma': 0.8043483069900192, 'reg_alpha': 0.008832646922661032, 'reg_lambda': 3.221483916496192e-05, 'max_delta_step': 8}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:   3%|▎         | 6/200 [00:09<04:49,  1.49s/it]

[I 2025-11-10 14:43:58,507] Trial 5 finished with value: 0.6498039215686274 and parameters: {'max_depth': 7, 'learning_rate': 0.024583156672990148, 'n_estimators': 912, 'subsample': 0.9380633695711047, 'colsample_bytree': 0.5333102618938093, 'min_child_weight': 5, 'gamma': 3.1251699095906664, 'reg_alpha': 0.0007146388145512955, 'reg_lambda': 1.0023864789533045e-07, 'max_delta_step': 5}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:   4%|▎         | 7/200 [00:10<04:04,  1.27s/it]

[I 2025-11-10 14:43:59,316] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.015501698623711169, 'n_estimators': 651, 'subsample': 0.6995930604261437, 'colsample_bytree': 0.6605428302433969, 'min_child_weight': 9, 'gamma': 4.325325504161984, 'reg_alpha': 2.7249355869233456e-06, 'reg_lambda': 0.3984893411920807, 'max_delta_step': 6}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:   4%|▍         | 8/200 [00:13<06:34,  2.05s/it]

[I 2025-11-10 14:44:03,047] Trial 7 finished with value: 0.5190196078431373 and parameters: {'max_depth': 3, 'learning_rate': 0.016195007039783733, 'n_estimators': 862, 'subsample': 0.9817175967293565, 'colsample_bytree': 0.5972275099086553, 'min_child_weight': 2, 'gamma': 0.18346138673091428, 'reg_alpha': 1.20375842191974, 'reg_lambda': 1.201014493877021e-07, 'max_delta_step': 4}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:   4%|▍         | 9/200 [00:15<05:55,  1.86s/it]

[I 2025-11-10 14:44:04,486] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02329340104641168, 'n_estimators': 1163, 'subsample': 0.5449164236439495, 'colsample_bytree': 0.9972705619926151, 'min_child_weight': 6, 'gamma': 0.07057160710958632, 'reg_alpha': 3.7804351397726395, 'reg_lambda': 1.1863815640951602e-05, 'max_delta_step': 4}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:   5%|▌         | 10/200 [00:15<04:34,  1.45s/it]

[I 2025-11-10 14:44:05,004] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.02308239427809568, 'n_estimators': 1421, 'subsample': 0.6509220554255164, 'colsample_bytree': 0.7641494677397707, 'min_child_weight': 10, 'gamma': 1.0276212919377703, 'reg_alpha': 7.2667388223601176e-06, 'reg_lambda': 3.4852421656304446e-08, 'max_delta_step': 2}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:   6%|▌         | 11/200 [00:16<03:54,  1.24s/it]

[I 2025-11-10 14:44:05,777] Trial 6 finished with value: 0.5763398692810456 and parameters: {'max_depth': 8, 'learning_rate': 0.1034909890515985, 'n_estimators': 1428, 'subsample': 0.9029449287081464, 'colsample_bytree': 0.7429374315024, 'min_child_weight': 1, 'gamma': 0.5669256716827531, 'reg_alpha': 4.799582072159162e-07, 'reg_lambda': 9.687022049879937, 'max_delta_step': 5}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:   6%|▌         | 12/200 [00:16<03:03,  1.03it/s]

[I 2025-11-10 14:44:06,146] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.014309813273016796, 'n_estimators': 511, 'subsample': 0.6367907300202043, 'colsample_bytree': 0.5568307568640717, 'min_child_weight': 1, 'gamma': 1.6674724205204998, 'reg_alpha': 9.158537310006125, 'reg_lambda': 2.138843646845453e-05, 'max_delta_step': 1}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:   6%|▋         | 13/200 [00:19<04:25,  1.42s/it]

[I 2025-11-10 14:44:08,596] Trial 13 finished with value: 0.5756862745098039 and parameters: {'max_depth': 10, 'learning_rate': 0.052542509703037754, 'n_estimators': 459, 'subsample': 0.7868612693525322, 'colsample_bytree': 0.8355501552433952, 'min_child_weight': 1, 'gamma': 2.858946231289945, 'reg_alpha': 2.5005928285498972e-08, 'reg_lambda': 8.798961132150897, 'max_delta_step': 10}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:   7%|▋         | 14/200 [00:19<03:27,  1.12s/it]

[I 2025-11-10 14:44:09,010] Trial 14 finished with value: 0.6498039215686273 and parameters: {'max_depth': 9, 'learning_rate': 0.040340818622610825, 'n_estimators': 609, 'subsample': 0.7869610136829374, 'colsample_bytree': 0.8519743788921816, 'min_child_weight': 4, 'gamma': 3.1849481003353537, 'reg_alpha': 9.375882746611488e-08, 'reg_lambda': 0.0007115422619852821, 'max_delta_step': 7}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:   8%|▊         | 15/200 [00:22<05:08,  1.67s/it]

[I 2025-11-10 14:44:11,945] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.026972584945503284, 'n_estimators': 1497, 'subsample': 0.5565283432502094, 'colsample_bytree': 0.8506153133189767, 'min_child_weight': 10, 'gamma': 4.048766184090609, 'reg_alpha': 2.866015061021439, 'reg_lambda': 2.73252631801204e-07, 'max_delta_step': 5}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:   8%|▊         | 16/200 [00:23<03:52,  1.26s/it]

[I 2025-11-10 14:44:12,276] Trial 15 finished with value: 0.6412418300653595 and parameters: {'max_depth': 8, 'learning_rate': 0.042630541348684194, 'n_estimators': 1185, 'subsample': 0.7891130947455623, 'colsample_bytree': 0.8862452411388992, 'min_child_weight': 4, 'gamma': 3.396454573492499, 'reg_alpha': 2.2407365456841563e-08, 'reg_lambda': 0.0007087074819347221, 'max_delta_step': 10}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:   8%|▊         | 17/200 [00:25<04:36,  1.51s/it]

[I 2025-11-10 14:44:14,357] Trial 16 finished with value: 0.635686274509804 and parameters: {'max_depth': 8, 'learning_rate': 0.04194633134554074, 'n_estimators': 1181, 'subsample': 0.7371755263135858, 'colsample_bytree': 0.870414787052028, 'min_child_weight': 4, 'gamma': 3.3059861694099673, 'reg_alpha': 0.0004882038391339492, 'reg_lambda': 0.00044535395283299166, 'max_delta_step': 6}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:   9%|▉         | 18/200 [00:26<04:45,  1.57s/it]

[I 2025-11-10 14:44:16,062] Trial 17 finished with value: 0.6314379084967321 and parameters: {'max_depth': 8, 'learning_rate': 0.03246955483901086, 'n_estimators': 1264, 'subsample': 0.7168649324858596, 'colsample_bytree': 0.8469371314264771, 'min_child_weight': 3, 'gamma': 3.629156956041175, 'reg_alpha': 0.00021520196513543423, 'reg_lambda': 6.615850775338739e-07, 'max_delta_step': 0}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:  10%|▉         | 19/200 [00:27<04:02,  1.34s/it]

[I 2025-11-10 14:44:16,873] Trial 21 pruned.

Best trial: 0. Best value: 0.667451:  10%|█         | 20/200 [00:28<03:30,  1.17s/it]

[I 2025-11-10 14:44:17,631] Trial 19 finished with value: 0.5472549019607843 and parameters: {'max_depth': 7, 'learning_rate': 0.07695140877214605, 'n_estimators': 797, 'subsample': 0.9888949754299662, 'colsample_bytree': 0.5893124603956776, 'min_child_weight': 3, 'gamma': 2.1591998806625194, 'reg_alpha': 0.0002236397338162922, 'reg_lambda': 1.1774884602524878e-06, 'max_delta_step': 0}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:  10%|█         | 21/200 [00:29<03:07,  1.05s/it]

[I 2025-11-10 14:44:18,409] Trial 18 finished with value: 0.5413725490196079 and parameters: {'max_depth': 8, 'learning_rate': 0.2939085040370863, 'n_estimators': 1210, 'subsample': 0.9963364013474005, 'colsample_bytree': 0.5099564050666857, 'min_child_weight': 3, 'gamma': 3.611490403042399, 'reg_alpha': 0.00031978417365553433, 'reg_lambda': 0.00039126303759567726, 'max_delta_step': 0}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:  11%|█         | 22/200 [00:29<02:22,  1.25it/s]

[I 2025-11-10 14:44:18,616] Trial 23 pruned.

Best trial: 0. Best value: 0.667451:  12%|█▏        | 23/200 [00:29<02:11,  1.35it/s]

[I 2025-11-10 14:44:19,228] Trial 24 pruned.

Best trial: 0. Best value: 0.667451:  12%|█▏        | 24/200 [00:30<02:14,  1.31it/s]

[I 2025-11-10 14:44:20,033] Trial 20 finished with value: 0.5390196078431373 and parameters: {'max_depth': 7, 'learning_rate': 0.010782375937614, 'n_estimators': 774, 'subsample': 0.9919167569990434, 'colsample_bytree': 0.6012764007927558, 'min_child_weight': 3, 'gamma': 2.1815636970585057, 'reg_alpha': 0.00015099603728196682, 'reg_lambda': 8.89519867505851e-07, 'max_delta_step': 0}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 0. Best value: 0.667451:  12%|█▎        | 25/200 [00:32<03:21,  1.15s/it]

[I 2025-11-10 14:44:22,108] Trial 25 finished with value: 0.6164705882352941 and parameters: {'max_depth': 9, 'learning_rate': 0.03421678194556689, 'n_estimators': 647, 'subsample': 0.6570471960894799, 'colsample_bytree': 0.9193813386446537, 'min_child_weight': 4, 'gamma': 2.9231942725289017, 'reg_alpha': 3.6768008503517957e-07, 'reg_lambda': 0.004831662309938181, 'max_delta_step': 8}. Best is trial 0 with value: 0.6674509803921568.

Best trial: 26. Best value: 0.687451:  14%|█▎        | 27/200 [00:33<01:58,  1.46it/s]

[I 2025-11-10 14:44:22,534] Trial 26 finished with value: 0.6874509803921568 and parameters: {'max_depth': 9, 'learning_rate': 0.03300490256467764, 'n_estimators': 618, 'subsample': 0.6362571069313698, 'colsample_bytree': 0.8044567754111966, 'min_child_weight': 4, 'gamma': 2.9769653987051274, 'reg_alpha': 3.1083175988802676e-07, 'reg_lambda': 0.9612059157732706, 'max_delta_step': 7}. Best is trial 26 with value: 0.6874509803921568.
[I 2025-11-10 14:44:22,632] Trial 22 finished with value: 0.6025490196078431 and parameters: {'max_depth': 9, 'learning_rate': 0.010067668452604902, 'n_estimators': 814, 'subsample': 0.8620136707229292, 'colsample_bytree': 0.7627265722913918, 'min_child_weight': 3, 'gamma': 2.437807923068018, 'reg_alpha': 3.100209587476839e-05, 'reg_lambda': 1.6176310674278445e-08, 'max_delta_step': 8}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  15%|█▌        | 30/200 [00:33<00:59,  2.86it/s]

[I 2025-11-10 14:44:22,996] Trial 29 pruned.
[I 2025-11-10 14:44:23,065] Trial 30 pruned.
[I 2025-11-10 14:44:23,133] Trial 27 finished with value: 0.6649019607843137 and parameters: {'max_depth': 9, 'learning_rate': 0.033601511574715096, 'n_estimators': 539, 'subsample': 0.6628731373135577, 'colsample_bytree': 0.7994252264027227, 'min_child_weight': 4, 'gamma': 2.9755480679650637, 'reg_alpha': 3.5810314746493886e-07, 'reg_lambda': 0.6723539128259759, 'max_delta_step': 7}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  16%|█▌        | 31/200 [00:34<00:49,  3.38it/s]

[I 2025-11-10 14:44:23,261] Trial 28 pruned.

Best trial: 26. Best value: 0.687451:  16%|█▌        | 32/200 [00:34<01:11,  2.36it/s]

[I 2025-11-10 14:44:24,048] Trial 33 pruned.
[I 2025-11-10 14:44:24,150] Trial 31 pruned.

Best trial: 26. Best value: 0.687451:  18%|█▊        | 35/200 [00:35<00:41,  3.93it/s]

[I 2025-11-10 14:44:24,300] Trial 34 pruned.
[I 2025-11-10 14:44:24,421] Trial 35 pruned.

Best trial: 26. Best value: 0.687451:  18%|█▊        | 36/200 [00:35<00:35,  4.59it/s]

[I 2025-11-10 14:44:24,529] Trial 32 pruned.

Best trial: 26. Best value: 0.687451:  18%|█▊        | 37/200 [00:35<00:40,  4.04it/s]

[I 2025-11-10 14:44:24,802] Trial 36 pruned.

Best trial: 26. Best value: 0.687451:  19%|█▉        | 38/200 [00:36<01:21,  1.98it/s]

[I 2025-11-10 14:44:26,045] Trial 37 finished with value: 0.6498039215686273 and parameters: {'max_depth': 7, 'learning_rate': 0.026466140505522002, 'n_estimators': 223, 'subsample': 0.7403717369743456, 'colsample_bytree': 0.904597065647194, 'min_child_weight': 4, 'gamma': 1.748749979383386, 'reg_alpha': 2.3816624408218927e-05, 'reg_lambda': 0.12119767159228531, 'max_delta_step': 4}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  20%|█▉        | 39/200 [00:37<01:44,  1.53it/s]

[I 2025-11-10 14:44:27,073] Trial 41 pruned.

Best trial: 26. Best value: 0.687451:  20%|██        | 40/200 [00:40<03:06,  1.17s/it]

[I 2025-11-10 14:44:29,520] Trial 40 finished with value: 0.6449019607843136 and parameters: {'max_depth': 7, 'learning_rate': 0.04889403039928155, 'n_estimators': 714, 'subsample': 0.9439524096437582, 'colsample_bytree': 0.9651705946082785, 'min_child_weight': 4, 'gamma': 2.439021042461553, 'reg_alpha': 0.058283328943015855, 'reg_lambda': 8.569017358269207e-05, 'max_delta_step': 4}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  20%|██        | 41/200 [00:40<02:28,  1.07it/s]

[I 2025-11-10 14:44:29,882] Trial 39 finished with value: 0.6560130718954248 and parameters: {'max_depth': 7, 'learning_rate': 0.047992008840763156, 'n_estimators': 1084, 'subsample': 0.7530020265224895, 'colsample_bytree': 0.629220629674614, 'min_child_weight': 4, 'gamma': 2.4657576788906086, 'reg_alpha': 0.012113987336336564, 'reg_lambda': 8.510475116585072e-05, 'max_delta_step': 4}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  21%|██        | 42/200 [00:41<02:15,  1.17it/s]

[I 2025-11-10 14:44:30,557] Trial 38 finished with value: 0.6304575163398692 and parameters: {'max_depth': 7, 'learning_rate': 0.050723558405777434, 'n_estimators': 1090, 'subsample': 0.7607966445265602, 'colsample_bytree': 0.9360169373981495, 'min_child_weight': 4, 'gamma': 1.6705399113577952, 'reg_alpha': 0.017222399869879963, 'reg_lambda': 0.009522855384520535, 'max_delta_step': 7}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  22%|██▏       | 44/200 [00:42<01:38,  1.58it/s]

[I 2025-11-10 14:44:31,362] Trial 43 pruned.
[I 2025-11-10 14:44:31,499] Trial 42 finished with value: 0.6242483660130719 and parameters: {'max_depth': 4, 'learning_rate': 0.08770840154167452, 'n_estimators': 707, 'subsample': 0.9177333028095329, 'colsample_bytree': 0.9567870756414203, 'min_child_weight': 4, 'gamma': 4.117059739524057, 'reg_alpha': 0.037879840922432004, 'reg_lambda': 0.01061676937872707, 'max_delta_step': 5}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  23%|██▎       | 46/200 [00:43<01:23,  1.85it/s]

[I 2025-11-10 14:44:32,440] Trial 46 pruned.
[I 2025-11-10 14:44:32,550] Trial 47 pruned.

Best trial: 26. Best value: 0.687451:  24%|██▎       | 47/200 [00:44<01:44,  1.47it/s]

[I 2025-11-10 14:44:33,563] Trial 49 pruned.
[I 2025-11-10 14:44:33,596] Trial 48 pruned.

Best trial: 26. Best value: 0.687451:  24%|██▍       | 49/200 [00:45<01:44,  1.45it/s]

[I 2025-11-10 14:44:34,965] Trial 50 pruned.
[I 2025-11-10 14:44:34,992] Trial 51 pruned.

Best trial: 26. Best value: 0.687451:  26%|██▌       | 51/200 [00:46<01:34,  1.58it/s]

[I 2025-11-10 14:44:36,052] Trial 52 pruned.

Best trial: 26. Best value: 0.687451:  26%|██▌       | 52/200 [00:47<01:20,  1.83it/s]

[I 2025-11-10 14:44:36,283] Trial 44 finished with value: 0.6556862745098039 and parameters: {'max_depth': 6, 'learning_rate': 0.07938171553283117, 'n_estimators': 1091, 'subsample': 0.9270926303167273, 'colsample_bytree': 0.5675068022661774, 'min_child_weight': 4, 'gamma': 4.163301376213678, 'reg_alpha': 0.016620558105622414, 'reg_lambda': 0.023501307037426235, 'max_delta_step': 5}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  26%|██▋       | 53/200 [00:47<01:32,  1.59it/s]

[I 2025-11-10 14:44:37,186] Trial 45 finished with value: 0.5925490196078431 and parameters: {'max_depth': 6, 'learning_rate': 0.03814865869774744, 'n_estimators': 1304, 'subsample': 0.8272171871941274, 'colsample_bytree': 0.5486743764395211, 'min_child_weight': 5, 'gamma': 0.3642789430492831, 'reg_alpha': 0.23448968689399757, 'reg_lambda': 0.019997510505643436, 'max_delta_step': 5}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  27%|██▋       | 54/200 [00:49<02:00,  1.21it/s]

[I 2025-11-10 14:44:38,583] Trial 56 pruned.

Best trial: 26. Best value: 0.687451:  28%|██▊       | 55/200 [00:50<01:55,  1.26it/s]

[I 2025-11-10 14:44:39,296] Trial 54 finished with value: 0.655359477124183 and parameters: {'max_depth': 9, 'learning_rate': 0.04351908637053145, 'n_estimators': 560, 'subsample': 0.8170532811867925, 'colsample_bytree': 0.8631260206650123, 'min_child_weight': 4, 'gamma': 3.2151851502457913, 'reg_alpha': 3.946015066803352e-08, 'reg_lambda': 2.9130999341453878e-06, 'max_delta_step': 7}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  28%|██▊       | 57/200 [00:50<01:16,  1.86it/s]

[I 2025-11-10 14:44:39,774] Trial 53 finished with value: 0.6498039215686273 and parameters: {'max_depth': 9, 'learning_rate': 0.013637194805289054, 'n_estimators': 865, 'subsample': 0.7138893193147959, 'colsample_bytree': 0.7808235872844813, 'min_child_weight': 4, 'gamma': 3.33993249782975, 'reg_alpha': 7.591656345322052e-05, 'reg_lambda': 3.2947394602952464e-06, 'max_delta_step': 10}. Best is trial 26 with value: 0.6874509803921568.
[I 2025-11-10 14:44:39,878] Trial 55 finished with value: 0.6331372549019608 and parameters: {'max_depth': 5, 'learning_rate': 0.17057262900207995, 'n_estimators': 558, 'subsample': 0.9152102695157289, 'colsample_bytree': 0.5033347496209044, 'min_child_weight': 4, 'gamma': 4.971539884614, 'reg_alpha': 8.596009141176199e-05, 'reg_lambda': 0.02394761132847352, 'max_delta_step': 5}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  30%|██▉       | 59/200 [00:53<01:53,  1.24it/s]

[I 2025-11-10 14:44:42,311] Trial 60 finished with value: 0.5996732026143791 and parameters: {'max_depth': 9, 'learning_rate': 0.04544658132622903, 'n_estimators': 394, 'subsample': 0.7756038742271935, 'colsample_bytree': 0.8734336706326831, 'min_child_weight': 3, 'gamma': 4.598213546155302, 'reg_alpha': 6.766398461142723e-07, 'reg_lambda': 0.0014588485235509001, 'max_delta_step': 8}. Best is trial 26 with value: 0.6874509803921568.
[I 2025-11-10 14:44:42,434] Trial 58 finished with value: 0.612483660130719 and parameters: {'max_depth': 9, 'learning_rate': 0.044027109213282664, 'n_estimators': 544, 'subsample': 0.7183158995564568, 'colsample_bytree': 0.8750898903593567, 'min_child_weight': 4, 'gamma': 4.5515343607271594, 'reg_alpha': 3.6846323299772035e-07, 'reg_lambda': 3.51871079909361e-06, 'max_delta_step': 8}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  30%|███       | 60/200 [00:53<01:42,  1.37it/s]

[I 2025-11-10 14:44:42,997] Trial 61 pruned.

Best trial: 26. Best value: 0.687451:  30%|███       | 61/200 [00:54<01:24,  1.65it/s]

[I 2025-11-10 14:44:43,302] Trial 62 pruned.

Best trial: 26. Best value: 0.687451:  31%|███       | 62/200 [00:54<01:10,  1.95it/s]

[I 2025-11-10 14:44:43,592] Trial 59 finished with value: 0.6193464052287583 and parameters: {'max_depth': 9, 'learning_rate': 0.04534587948323359, 'n_estimators': 600, 'subsample': 0.7648402435469196, 'colsample_bytree': 0.8684248248851278, 'min_child_weight': 3, 'gamma': 4.996542350488673, 'reg_alpha': 6.35750648932133e-07, 'reg_lambda': 0.0013456744547943877, 'max_delta_step': 8}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  32%|███▏      | 63/200 [00:55<01:24,  1.63it/s]

[I 2025-11-10 14:44:44,444] Trial 57 finished with value: 0.6386928104575162 and parameters: {'max_depth': 4, 'learning_rate': 0.06603937226763147, 'n_estimators': 1054, 'subsample': 0.9503945337043508, 'colsample_bytree': 0.5013940583819286, 'min_child_weight': 4, 'gamma': 4.983744017414389, 'reg_alpha': 0.000598814412452165, 'reg_lambda': 0.04482848789564763, 'max_delta_step': 3}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  32%|███▏      | 64/200 [00:55<01:08,  1.99it/s]

[I 2025-11-10 14:44:44,685] Trial 63 pruned.

Best trial: 26. Best value: 0.687451:  32%|███▎      | 65/200 [00:59<03:18,  1.47s/it]

[I 2025-11-10 14:44:48,414] Trial 67 finished with value: 0.6473202614379086 and parameters: {'max_depth': 7, 'learning_rate': 0.025225587329543702, 'n_estimators': 746, 'subsample': 0.8729102245946407, 'colsample_bytree': 0.5840923127123763, 'min_child_weight': 5, 'gamma': 2.6924725066278277, 'reg_alpha': 3.981420259435917e-08, 'reg_lambda': 3.6217599710120177e-07, 'max_delta_step': 6}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  33%|███▎      | 66/200 [00:59<02:39,  1.19s/it]

[I 2025-11-10 14:44:48,959] Trial 64 finished with value: 0.6760130718954248 and parameters: {'max_depth': 7, 'learning_rate': 0.05189564337551343, 'n_estimators': 1157, 'subsample': 0.9586646458442176, 'colsample_bytree': 0.5386190675418512, 'min_child_weight': 5, 'gamma': 2.03249979650658, 'reg_alpha': 1.7390148880249658e-07, 'reg_lambda': 1.414600825076724e-07, 'max_delta_step': 3}. Best is trial 26 with value: 0.6874509803921568.
[I 2025-11-10 14:44:49,142] Trial 65 finished with value: 0.6642483660130719 and parameters: {'max_depth': 7, 'learning_rate': 0.05726985534237853, 'n_estimators': 1156, 'subsample': 0.9619267745457738, 'colsample_bytree': 0.5318191195262577, 'min_child_weight': 5, 'gamma': 3.808368417461992, 'reg_alpha': 3.1769637056369643e-06, 'reg_lambda': 1.7588213156834136e-07, 'max_delta_step': 3}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  34%|███▍      | 68/200 [01:00<01:51,  1.18it/s]

[I 2025-11-10 14:44:49,894] Trial 66 finished with value: 0.6492156862745099 and parameters: {'max_depth': 7, 'learning_rate': 0.05662988664766043, 'n_estimators': 1167, 'subsample': 0.8743309656705222, 'colsample_bytree': 0.5810017249459614, 'min_child_weight': 5, 'gamma': 2.6339642803123433, 'reg_alpha': 2.959492116109692e-06, 'reg_lambda': 1.4266740081923715e-07, 'max_delta_step': 6}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  34%|███▍      | 69/200 [01:01<01:32,  1.42it/s]

[I 2025-11-10 14:44:50,275] Trial 69 pruned.

Best trial: 26. Best value: 0.687451:  35%|███▌      | 70/200 [01:01<01:11,  1.81it/s]

[I 2025-11-10 14:44:50,467] Trial 70 pruned.

Best trial: 26. Best value: 0.687451:  36%|███▌      | 71/200 [01:01<01:18,  1.65it/s]

[I 2025-11-10 14:44:51,189] Trial 71 pruned.

Best trial: 26. Best value: 0.687451:  36%|███▌      | 72/200 [01:02<01:19,  1.60it/s]

[I 2025-11-10 14:44:51,858] Trial 72 pruned.

Best trial: 26. Best value: 0.687451:  36%|███▋      | 73/200 [01:04<02:21,  1.11s/it]

[I 2025-11-10 14:44:54,098] Trial 74 finished with value: 0.6674509803921568 and parameters: {'max_depth': 8, 'learning_rate': 0.04118804251699818, 'n_estimators': 476, 'subsample': 0.962355557195254, 'colsample_bytree': 0.6081899980636079, 'min_child_weight': 4, 'gamma': 3.4807571673424627, 'reg_alpha': 1.1901301566694438e-07, 'reg_lambda': 7.350409131984796e-06, 'max_delta_step': 4}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  37%|███▋      | 74/200 [01:05<02:14,  1.07s/it]

[I 2025-11-10 14:44:55,063] Trial 68 finished with value: 0.6615686274509803 and parameters: {'max_depth': 8, 'learning_rate': 0.028205702872437927, 'n_estimators': 1223, 'subsample': 0.9681018866394007, 'colsample_bytree': 0.5306147325197131, 'min_child_weight': 4, 'gamma': 2.552270077135325, 'reg_alpha': 1.334473007705147e-07, 'reg_lambda': 4.745192363479281e-08, 'max_delta_step': 6}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  38%|███▊      | 75/200 [01:07<02:46,  1.33s/it]

[I 2025-11-10 14:44:57,027] Trial 73 finished with value: 0.6711111111111111 and parameters: {'max_depth': 7, 'learning_rate': 0.09082955775739762, 'n_estimators': 1229, 'subsample': 0.9309694111627436, 'colsample_bytree': 0.5168847935370716, 'min_child_weight': 5, 'gamma': 1.4392994922833722, 'reg_alpha': 9.474612778757116e-08, 'reg_lambda': 1.3583133210246408, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  38%|███▊      | 76/200 [01:08<02:27,  1.19s/it]

[I 2025-11-10 14:44:57,889] Trial 75 finished with value: 0.6213725490196078 and parameters: {'max_depth': 8, 'learning_rate': 0.040878225555169685, 'n_estimators': 958, 'subsample': 0.9318414508819719, 'colsample_bytree': 0.607295661230024, 'min_child_weight': 4, 'gamma': 2.8338698968687543, 'reg_alpha': 7.623249956053417e-08, 'reg_lambda': 1.0844468320732332e-08, 'max_delta_step': 2}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  38%|███▊      | 77/200 [01:09<02:22,  1.16s/it]

[I 2025-11-10 14:44:58,949] Trial 78 finished with value: 0.6498039215686274 and parameters: {'max_depth': 8, 'learning_rate': 0.030582613759055435, 'n_estimators': 370, 'subsample': 0.9593318390340143, 'colsample_bytree': 0.5136652850376315, 'min_child_weight': 5, 'gamma': 2.26976783368573, 'reg_alpha': 8.569606289079458e-08, 'reg_lambda': 4.1733639667566257e-07, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  39%|███▉      | 78/200 [01:09<01:46,  1.14it/s]

[I 2025-11-10 14:44:59,176] Trial 76 finished with value: 0.6649019607843136 and parameters: {'max_depth': 8, 'learning_rate': 0.029761535803847064, 'n_estimators': 950, 'subsample': 0.9346732360708394, 'colsample_bytree': 0.6169280475334964, 'min_child_weight': 5, 'gamma': 2.322637246078988, 'reg_alpha': 7.871668670102505e-08, 'reg_lambda': 1.424818626606652e-06, 'max_delta_step': 4}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  40%|███▉      | 79/200 [01:10<01:36,  1.26it/s]

[I 2025-11-10 14:44:59,786] Trial 77 finished with value: 0.6698039215686274 and parameters: {'max_depth': 8, 'learning_rate': 0.02820283632276219, 'n_estimators': 958, 'subsample': 0.9292835621237594, 'colsample_bytree': 0.6124800712209875, 'min_child_weight': 5, 'gamma': 2.3279505957727045, 'reg_alpha': 1.0657079939346335e-07, 'reg_lambda': 1.2960521036901565e-08, 'max_delta_step': 4}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  40%|████      | 80/200 [01:10<01:21,  1.47it/s]

[I 2025-11-10 14:45:00,200] Trial 81 pruned.

Best trial: 26. Best value: 0.687451:  40%|████      | 81/200 [01:13<02:42,  1.37s/it]

[I 2025-11-10 14:45:03,174] Trial 82 finished with value: 0.6560130718954248 and parameters: {'max_depth': 8, 'learning_rate': 0.03356189478640804, 'n_estimators': 648, 'subsample': 0.9106925105923245, 'colsample_bytree': 0.6107621266751481, 'min_child_weight': 5, 'gamma': 1.5906855674760014, 'reg_alpha': 1.781555871466885e-08, 'reg_lambda': 1.2718017625616162e-05, 'max_delta_step': 4}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  41%|████      | 82/200 [01:15<02:43,  1.39s/it]

[I 2025-11-10 14:45:04,604] Trial 79 finished with value: 0.6698039215686274 and parameters: {'max_depth': 8, 'learning_rate': 0.028817647251736175, 'n_estimators': 1372, 'subsample': 0.9996350013773455, 'colsample_bytree': 0.5393001611064041, 'min_child_weight': 5, 'gamma': 1.4635731951164113, 'reg_alpha': 1.04699107423282e-06, 'reg_lambda': 4.819958136718205e-07, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.
[I 2025-11-10 14:45:04,613] Trial 83 finished with value: 0.6674509803921568 and parameters: {'max_depth': 9, 'learning_rate': 0.02330446724916914, 'n_estimators': 894, 'subsample': 0.911243599190742, 'colsample_bytree': 0.6116391292230989, 'min_child_weight': 5, 'gamma': 2.325501952950256, 'reg_alpha': 9.557930396640798e-07, 'reg_lambda': 1.4471535771961408, 'max_delta_step': 4}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  42%|████▏     | 84/200 [01:16<02:02,  1.06s/it]

[I 2025-11-10 14:45:05,941] Trial 80 finished with value: 0.6698039215686274 and parameters: {'max_depth': 8, 'learning_rate': 0.02811844989257584, 'n_estimators': 1381, 'subsample': 0.9995000134179189, 'colsample_bytree': 0.5418362058623295, 'min_child_weight': 5, 'gamma': 1.5069482808700718, 'reg_alpha': 2.1843981508831916e-08, 'reg_lambda': 2.154912500012851e-07, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  42%|████▎     | 85/200 [01:18<02:09,  1.13s/it]

[I 2025-11-10 14:45:07,285] Trial 86 finished with value: 0.6698039215686274 and parameters: {'max_depth': 9, 'learning_rate': 0.022406372326337055, 'n_estimators': 425, 'subsample': 0.9949049562844124, 'colsample_bytree': 0.6500556889311075, 'min_child_weight': 5, 'gamma': 1.0778407051069503, 'reg_alpha': 1.0522548540604693e-06, 'reg_lambda': 3.811892811953003, 'max_delta_step': 0}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  43%|████▎     | 86/200 [01:18<01:49,  1.04it/s]

[I 2025-11-10 14:45:07,791] Trial 84 finished with value: 0.6560130718954248 and parameters: {'max_depth': 9, 'learning_rate': 0.039261554239533085, 'n_estimators': 968, 'subsample': 0.9024483827319335, 'colsample_bytree': 0.6860245820209001, 'min_child_weight': 5, 'gamma': 2.3811554461897706, 'reg_alpha': 7.683620629616783e-07, 'reg_lambda': 4.51956507160822, 'max_delta_step': 4}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  44%|████▎     | 87/200 [01:19<01:51,  1.02it/s]

[I 2025-11-10 14:45:08,823] Trial 88 pruned.

Best trial: 26. Best value: 0.687451:  44%|████▍     | 88/200 [01:20<01:44,  1.08it/s]

[I 2025-11-10 14:45:09,614] Trial 89 pruned.

Best trial: 26. Best value: 0.687451:  44%|████▍     | 89/200 [01:22<02:27,  1.33s/it]

[I 2025-11-10 14:45:11,930] Trial 85 finished with value: 0.6556862745098039 and parameters: {'max_depth': 9, 'learning_rate': 0.023352477902172757, 'n_estimators': 1394, 'subsample': 0.9904840039330168, 'colsample_bytree': 0.6445311769989377, 'min_child_weight': 5, 'gamma': 0.8721206839168141, 'reg_alpha': 9.577809701589571e-07, 'reg_lambda': 1.160231564776696, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  45%|████▌     | 90/200 [01:23<02:17,  1.25s/it]

[I 2025-11-10 14:45:13,013] Trial 87 finished with value: 0.6756862745098039 and parameters: {'max_depth': 9, 'learning_rate': 0.02278520986040098, 'n_estimators': 1395, 'subsample': 0.9966290210858327, 'colsample_bytree': 0.6532784725807483, 'min_child_weight': 5, 'gamma': 1.076994860998857, 'reg_alpha': 1.3273021955936437e-06, 'reg_lambda': 3.9110025124880807, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  46%|████▌     | 91/200 [01:25<02:19,  1.28s/it]

[I 2025-11-10 14:45:14,343] Trial 93 pruned.

Best trial: 26. Best value: 0.687451:  46%|████▌     | 92/200 [01:26<02:19,  1.29s/it]

[I 2025-11-10 14:45:15,654] Trial 90 finished with value: 0.6556862745098039 and parameters: {'max_depth': 8, 'learning_rate': 0.0185784891272919, 'n_estimators': 1387, 'subsample': 0.9829756822062462, 'colsample_bytree': 0.6470518527375549, 'min_child_weight': 5, 'gamma': 1.4731501354335528, 'reg_alpha': 2.500591315673321e-08, 'reg_lambda': 2.549651147289037e-08, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  46%|████▋     | 93/200 [01:26<01:52,  1.05s/it]

[I 2025-11-10 14:45:16,157] Trial 91 finished with value: 0.6556862745098039 and parameters: {'max_depth': 9, 'learning_rate': 0.019416608695915077, 'n_estimators': 1358, 'subsample': 0.9867398778616745, 'colsample_bytree': 0.594306345500525, 'min_child_weight': 5, 'gamma': 1.3952287140489192, 'reg_alpha': 1.5811206983781587e-05, 'reg_lambda': 4.921368810971287e-07, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  47%|████▋     | 94/200 [01:28<02:02,  1.16s/it]

[I 2025-11-10 14:45:17,548] Trial 96 pruned.

Best trial: 26. Best value: 0.687451:  48%|████▊     | 95/200 [01:29<02:12,  1.26s/it]

[I 2025-11-10 14:45:19,070] Trial 92 finished with value: 0.6556862745098039 and parameters: {'max_depth': 10, 'learning_rate': 0.026922263794093234, 'n_estimators': 1461, 'subsample': 0.9499601490035283, 'colsample_bytree': 0.594105452940658, 'min_child_weight': 5, 'gamma': 1.3325848780512783, 'reg_alpha': 1.4939481321280149e-05, 'reg_lambda': 1.8569755686173035e-07, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  48%|████▊     | 96/200 [01:30<01:46,  1.02s/it]

[I 2025-11-10 14:45:19,529] Trial 98 pruned.

Best trial: 26. Best value: 0.687451:  48%|████▊     | 97/200 [01:30<01:27,  1.18it/s]

[I 2025-11-10 14:45:19,974] Trial 97 finished with value: 0.6501307189542483 and parameters: {'max_depth': 9, 'learning_rate': 0.024814540592053874, 'n_estimators': 428, 'subsample': 0.9523252572633663, 'colsample_bytree': 0.5442929144590128, 'min_child_weight': 5, 'gamma': 1.1942204775580703, 'reg_alpha': 4.7010941936359506e-07, 'reg_lambda': 0.38177948547193874, 'max_delta_step': 0}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  49%|████▉     | 98/200 [01:31<01:30,  1.13it/s]

[I 2025-11-10 14:45:20,940] Trial 94 finished with value: 0.6615686274509803 and parameters: {'max_depth': 9, 'learning_rate': 0.027327777283959288, 'n_estimators': 1262, 'subsample': 0.9783573039063863, 'colsample_bytree': 0.5157844452218744, 'min_child_weight': 5, 'gamma': 1.2217638309696794, 'reg_alpha': 4.7193711317470477e-07, 'reg_lambda': 0.3830393920038348, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  50%|████▉     | 99/200 [01:32<01:41,  1.01s/it]

[I 2025-11-10 14:45:22,227] Trial 101 pruned.

Best trial: 26. Best value: 0.687451:  50%|█████     | 100/200 [01:33<01:23,  1.20it/s]

[I 2025-11-10 14:45:22,661] Trial 95 finished with value: 0.6498039215686274 and parameters: {'max_depth': 9, 'learning_rate': 0.026816106967710442, 'n_estimators': 1353, 'subsample': 0.9801287839211351, 'colsample_bytree': 0.5186908762753786, 'min_child_weight': 5, 'gamma': 1.0763367436021307, 'reg_alpha': 2.940215425966067e-07, 'reg_lambda': 9.527549127850936, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  50%|█████     | 101/200 [01:34<01:43,  1.04s/it]

[I 2025-11-10 14:45:24,185] Trial 103 pruned.

Best trial: 26. Best value: 0.687451:  51%|█████     | 102/200 [01:36<02:05,  1.28s/it]

[I 2025-11-10 14:45:26,012] Trial 99 finished with value: 0.6698039215686274 and parameters: {'max_depth': 8, 'learning_rate': 0.01665055023484208, 'n_estimators': 1263, 'subsample': 0.9980132861277455, 'colsample_bytree': 0.6893589591103789, 'min_child_weight': 5, 'gamma': 1.5312884344088808, 'reg_alpha': 2.706957455291225e-07, 'reg_lambda': 0.37404474500757273, 'max_delta_step': 2}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  52%|█████▏    | 103/200 [01:37<01:58,  1.22s/it]

[I 2025-11-10 14:45:27,112] Trial 100 finished with value: 0.6698039215686274 and parameters: {'max_depth': 8, 'learning_rate': 0.03210801193204072, 'n_estimators': 1356, 'subsample': 0.9957128588152483, 'colsample_bytree': 0.7260868136140786, 'min_child_weight': 5, 'gamma': 0.6594427978463433, 'reg_alpha': 2.9801132822488646e-07, 'reg_lambda': 8.64282763463212, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  52%|█████▏    | 104/200 [01:38<01:41,  1.06s/it]

[I 2025-11-10 14:45:27,777] Trial 105 pruned.

Best trial: 26. Best value: 0.687451:  52%|█████▎    | 105/200 [01:39<01:30,  1.05it/s]

[I 2025-11-10 14:45:28,480] Trial 106 pruned.

Best trial: 26. Best value: 0.687451:  53%|█████▎    | 106/200 [01:40<01:25,  1.11it/s]

[I 2025-11-10 14:45:29,279] Trial 107 pruned.

Best trial: 26. Best value: 0.687451:  54%|█████▎    | 107/200 [01:40<01:08,  1.36it/s]

[I 2025-11-10 14:45:29,621] Trial 104 finished with value: 0.6815686274509803 and parameters: {'max_depth': 9, 'learning_rate': 0.017200894775883817, 'n_estimators': 1031, 'subsample': 0.9261957701613857, 'colsample_bytree': 0.5730787063739962, 'min_child_weight': 5, 'gamma': 2.0574834010608916, 'reg_alpha': 5.9560212338718625e-06, 'reg_lambda': 2.621860883565206, 'max_delta_step': 2}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  54%|█████▍    | 108/200 [01:40<00:58,  1.56it/s]

[I 2025-11-10 14:45:30,029] Trial 102 finished with value: 0.655359477124183 and parameters: {'max_depth': 8, 'learning_rate': 0.030846761729421336, 'n_estimators': 1365, 'subsample': 0.9399048156147557, 'colsample_bytree': 0.6984827438719411, 'min_child_weight': 4, 'gamma': 3.477855538417966, 'reg_alpha': 5.20705623305883e-08, 'reg_lambda': 7.520909440790264e-07, 'max_delta_step': 2}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  55%|█████▌    | 110/200 [01:45<02:06,  1.41s/it]

[I 2025-11-10 14:45:35,018] Trial 110 finished with value: 0.6321568627450981 and parameters: {'max_depth': 7, 'learning_rate': 0.012989205702147733, 'n_estimators': 1130, 'subsample': 0.9698914456656756, 'colsample_bytree': 0.5680772877318128, 'min_child_weight': 5, 'gamma': 2.059134057035358, 'reg_alpha': 1.7157770660879923e-06, 'reg_lambda': 4.959205974834119, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.
[I 2025-11-10 14:45:35,174] Trial 109 finished with value: 0.64359477124183 and parameters: {'max_depth': 7, 'learning_rate': 0.01331496762621554, 'n_estimators': 1132, 'subsample': 0.9658157393301994, 'colsample_bytree': 0.7369441686826635, 'min_child_weight': 5, 'gamma': 0.13948003476206794, 'reg_alpha': 1.7891973281304662e-06, 'reg_lambda': 0.5200256801162046, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  56%|█████▌    | 111/200 [01:46<01:33,  1.05s/it]

[I 2025-11-10 14:45:35,393] Trial 111 finished with value: 0.6498039215686274 and parameters: {'max_depth': 7, 'learning_rate': 0.012955908856004075, 'n_estimators': 1126, 'subsample': 0.9692225925093135, 'colsample_bytree': 0.6620671037242853, 'min_child_weight': 5, 'gamma': 1.652437709968358, 'reg_alpha': 2.2309333275786882e-06, 'reg_lambda': 4.845059144795456, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  56%|█████▌    | 112/200 [01:46<01:21,  1.08it/s]

[I 2025-11-10 14:45:36,015] Trial 108 finished with value: 0.6498039215686274 and parameters: {'max_depth': 7, 'learning_rate': 0.014034549808754215, 'n_estimators': 1435, 'subsample': 0.9673794379415616, 'colsample_bytree': 0.7673659993654901, 'min_child_weight': 5, 'gamma': 1.7785049169886429, 'reg_alpha': 3.444682121962616e-08, 'reg_lambda': 4.7785648727746155, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  56%|█████▋    | 113/200 [01:47<01:24,  1.03it/s]

[I 2025-11-10 14:45:37,098] Trial 115 pruned.

Best trial: 26. Best value: 0.687451:  57%|█████▋    | 114/200 [01:49<01:28,  1.03s/it]

[I 2025-11-10 14:45:38,260] Trial 116 pruned.

Best trial: 26. Best value: 0.687451:  57%|█████▊    | 115/200 [01:50<01:34,  1.12s/it]

[I 2025-11-10 14:45:39,589] Trial 117 pruned.

Best trial: 26. Best value: 0.687451:  58%|█████▊    | 117/200 [01:51<01:06,  1.26it/s]

[I 2025-11-10 14:45:40,589] Trial 112 finished with value: 0.6698039215686274 and parameters: {'max_depth': 10, 'learning_rate': 0.015994572960543595, 'n_estimators': 1043, 'subsample': 0.9686310966193769, 'colsample_bytree': 0.6643774763155806, 'min_child_weight': 5, 'gamma': 1.614056112059887, 'reg_alpha': 2.1033192269545504e-07, 'reg_lambda': 4.690274034568491, 'max_delta_step': 0}. Best is trial 26 with value: 0.6874509803921568.
[I 2025-11-10 14:45:40,722] Trial 113 finished with value: 0.6756862745098039 and parameters: {'max_depth': 9, 'learning_rate': 0.015262972670127616, 'n_estimators': 1034, 'subsample': 0.9239451580262091, 'colsample_bytree': 0.5773520193293321, 'min_child_weight': 5, 'gamma': 1.5359333524348748, 'reg_alpha': 5.085373330578357e-06, 'reg_lambda': 5.430985398536843, 'max_delta_step': 0}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  59%|█████▉    | 118/200 [01:51<00:50,  1.64it/s]

[I 2025-11-10 14:45:40,898] Trial 118 pruned.

Best trial: 26. Best value: 0.687451:  60%|██████    | 120/200 [01:52<00:40,  1.96it/s]

[I 2025-11-10 14:45:41,757] Trial 120 pruned.
[I 2025-11-10 14:45:41,861] Trial 119 pruned.

Best trial: 26. Best value: 0.687451:  60%|██████    | 121/200 [01:52<00:35,  2.20it/s]

[I 2025-11-10 14:45:42,177] Trial 114 finished with value: 0.6815686274509803 and parameters: {'max_depth': 9, 'learning_rate': 0.01588818353980897, 'n_estimators': 1192, 'subsample': 0.9860777586231455, 'colsample_bytree': 0.7168702722265439, 'min_child_weight': 5, 'gamma': 1.521329903835193, 'reg_alpha': 6.8731340856263e-07, 'reg_lambda': 1.102993213160459, 'max_delta_step': 0}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  61%|██████    | 122/200 [01:53<00:36,  2.11it/s]

[I 2025-11-10 14:45:42,697] Trial 121 pruned.

Best trial: 26. Best value: 0.687451:  62%|██████▏   | 123/200 [01:54<00:38,  2.02it/s]

[I 2025-11-10 14:45:43,251] Trial 122 pruned.
[I 2025-11-10 14:45:43,346] Trial 123 pruned.

Best trial: 26. Best value: 0.687451:  62%|██████▎   | 125/200 [01:54<00:28,  2.64it/s]

[I 2025-11-10 14:45:43,740] Trial 124 pruned.

Best trial: 26. Best value: 0.687451:  63%|██████▎   | 126/200 [01:55<00:42,  1.74it/s]

[I 2025-11-10 14:45:44,900] Trial 128 pruned.

Best trial: 26. Best value: 0.687451:  64%|██████▎   | 127/200 [01:56<00:47,  1.55it/s]

[I 2025-11-10 14:45:45,746] Trial 129 pruned.

Best trial: 26. Best value: 0.687451:  64%|██████▍   | 128/200 [01:59<01:35,  1.32s/it]

[I 2025-11-10 14:45:48,877] Trial 125 finished with value: 0.6815686274509803 and parameters: {'max_depth': 8, 'learning_rate': 0.016781268359434984, 'n_estimators': 1275, 'subsample': 0.9520887260653182, 'colsample_bytree': 0.5605475965451218, 'min_child_weight': 5, 'gamma': 1.5004016099698863, 'reg_alpha': 3.827902504589982e-05, 'reg_lambda': 1.1499725350270404, 'max_delta_step': 0}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  64%|██████▍   | 129/200 [02:00<01:24,  1.18s/it]

[I 2025-11-10 14:45:49,709] Trial 127 finished with value: 0.6698039215686274 and parameters: {'max_depth': 9, 'learning_rate': 0.017014099028699686, 'n_estimators': 1203, 'subsample': 0.9892168114454734, 'colsample_bytree': 0.6991651031617458, 'min_child_weight': 5, 'gamma': 1.4607147054863248, 'reg_alpha': 5.546199844354334e-07, 'reg_lambda': 1.1727836538449845e-08, 'max_delta_step': 0}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  65%|██████▌   | 130/200 [02:01<01:12,  1.04s/it]

[I 2025-11-10 14:45:50,392] Trial 126 finished with value: 0.6662745098039217 and parameters: {'max_depth': 9, 'learning_rate': 0.2121048795376248, 'n_estimators': 1415, 'subsample': 0.988792591035478, 'colsample_bytree': 0.7110260113580499, 'min_child_weight': 5, 'gamma': 1.4878921520032249, 'reg_alpha': 1.660254694998382e-07, 'reg_lambda': 9.537411119682393, 'max_delta_step': 0}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  66%|██████▌   | 131/200 [02:01<01:01,  1.12it/s]

[I 2025-11-10 14:45:50,911] Trial 132 pruned.

Best trial: 26. Best value: 0.687451:  66%|██████▌   | 132/200 [02:02<00:58,  1.16it/s]

[I 2025-11-10 14:45:51,712] Trial 133 pruned.

Best trial: 26. Best value: 0.687451:  66%|██████▋   | 133/200 [02:03<00:52,  1.28it/s]

[I 2025-11-10 14:45:52,289] Trial 130 finished with value: 0.6556862745098039 and parameters: {'max_depth': 3, 'learning_rate': 0.0164999241521337, 'n_estimators': 1280, 'subsample': 0.9848546226832305, 'colsample_bytree': 0.5387787020471384, 'min_child_weight': 5, 'gamma': 1.8925477884814375, 'reg_alpha': 4.948677220528357e-06, 'reg_lambda': 0.5994707376268786, 'max_delta_step': 2}. Best is trial 26 with value: 0.6874509803921568.
[I 2025-11-10 14:45:52,305] Trial 134 pruned.

Best trial: 26. Best value: 0.687451:  68%|██████▊   | 135/200 [02:04<00:46,  1.40it/s]

[I 2025-11-10 14:45:53,573] Trial 136 pruned.

Best trial: 26. Best value: 0.687451:  68%|██████▊   | 136/200 [02:05<00:57,  1.10it/s]

[I 2025-11-10 14:45:55,054] Trial 138 pruned.

Best trial: 26. Best value: 0.687451:  68%|██████▊   | 137/200 [02:06<00:47,  1.34it/s]

[I 2025-11-10 14:45:55,359] Trial 131 finished with value: 0.6874509803921568 and parameters: {'max_depth': 9, 'learning_rate': 0.21537647915167468, 'n_estimators': 1277, 'subsample': 0.9006732268705462, 'colsample_bytree': 0.5417684096665932, 'min_child_weight': 5, 'gamma': 1.8476894977974974, 'reg_alpha': 2.1821457581393766e-05, 'reg_lambda': 1.3254307076195308e-08, 'max_delta_step': 0}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  69%|██████▉   | 138/200 [02:08<01:19,  1.28s/it]

[I 2025-11-10 14:45:58,062] Trial 137 finished with value: 0.6756862745098039 and parameters: {'max_depth': 8, 'learning_rate': 0.02423209333777653, 'n_estimators': 1072, 'subsample': 0.9999833242941881, 'colsample_bytree': 0.5517671327555311, 'min_child_weight': 5, 'gamma': 1.1269119017929863, 'reg_alpha': 3.915835488798811e-05, 'reg_lambda': 2.3419013833017277, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.
[I 2025-11-10 14:45:58,106] Trial 135 finished with value: 0.6590196078431373 and parameters: {'max_depth': 8, 'learning_rate': 0.025499068099155996, 'n_estimators': 1274, 'subsample': 0.9435033267986545, 'colsample_bytree': 0.5556030538406658, 'min_child_weight': 5, 'gamma': 0.8399290980733751, 'reg_alpha': 4.11286794463414e-06, 'reg_lambda': 0.5282856088518524, 'max_delta_step': 2}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  70%|███████   | 140/200 [02:09<00:57,  1.05it/s]

[I 2025-11-10 14:45:59,137] Trial 141 pruned.
[I 2025-11-10 14:45:59,182] Trial 142 pruned.

Best trial: 26. Best value: 0.687451:  71%|███████   | 142/200 [02:11<00:46,  1.26it/s]

[I 2025-11-10 14:46:00,208] Trial 143 pruned.
[I 2025-11-10 14:46:00,242] Trial 144 pruned.

Best trial: 26. Best value: 0.687451:  72%|███████▏  | 144/200 [02:12<00:40,  1.39it/s]

[I 2025-11-10 14:46:01,386] Trial 145 pruned.

Best trial: 26. Best value: 0.687451:  72%|███████▎  | 145/200 [02:13<00:44,  1.23it/s]

[I 2025-11-10 14:46:02,561] Trial 139 finished with value: 0.6498039215686273 and parameters: {'max_depth': 8, 'learning_rate': 0.015049436694974556, 'n_estimators': 1463, 'subsample': 0.9755069935629987, 'colsample_bytree': 0.6720627176320865, 'min_child_weight': 5, 'gamma': 1.1414624217416263, 'reg_alpha': 3.3954590557914667e-07, 'reg_lambda': 1.7293256485333577, 'max_delta_step': 3}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  73%|███████▎  | 146/200 [02:13<00:38,  1.40it/s]

[I 2025-11-10 14:46:02,931] Trial 140 finished with value: 0.6815686274509803 and parameters: {'max_depth': 9, 'learning_rate': 0.014919978210656496, 'n_estimators': 1465, 'subsample': 0.9298136487647531, 'colsample_bytree': 0.5416268378975356, 'min_child_weight': 5, 'gamma': 1.9913821839309385, 'reg_alpha': 3.463310325459636e-05, 'reg_lambda': 2.7722490857177837e-08, 'max_delta_step': 0}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  74%|███████▎  | 147/200 [02:16<01:07,  1.27s/it]

[I 2025-11-10 14:46:05,922] Trial 146 finished with value: 0.6756862745098039 and parameters: {'max_depth': 8, 'learning_rate': 0.015232391411043378, 'n_estimators': 1175, 'subsample': 0.9784040607918049, 'colsample_bytree': 0.5467642039924315, 'min_child_weight': 5, 'gamma': 1.5712544606952659, 'reg_alpha': 6.880125367340685e-05, 'reg_lambda': 1.3044073862944684e-08, 'max_delta_step': 0}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  74%|███████▍  | 148/200 [02:17<01:00,  1.17s/it]

[I 2025-11-10 14:46:06,817] Trial 147 finished with value: 0.6756862745098039 and parameters: {'max_depth': 8, 'learning_rate': 0.01924037258240466, 'n_estimators': 1102, 'subsample': 0.999739606603978, 'colsample_bytree': 0.5830660371317571, 'min_child_weight': 5, 'gamma': 1.5860025325639744, 'reg_alpha': 4.6037648739026495e-05, 'reg_lambda': 1.777057542973209e-08, 'max_delta_step': 0}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  74%|███████▍  | 149/200 [02:18<00:51,  1.01s/it]

[I 2025-11-10 14:46:07,395] Trial 150 pruned.

[I 2025-11-10 14:46:07,847] Trial 148 finished with value: 0.6698039215686274 and parameters: {'max_depth': 9, 'learning_rate': 0.019149368281721573, 'n_estimators': 976, 'subsample': 0.9979224910330311, 'colsample_bytree': 0.6194421444931008, 'min_child_weight': 5, 'gamma': 1.661380989334883, 'reg_alpha': 5.47562139507592e-05, 'reg_lambda': 0.29196777595759804, 'max_delta_step': 0}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  76%|███████▌  | 151/200 [02:18<00:32,  1.50it/s]

[I 2025-11-10 14:46:08,027] Trial 151 pruned.

Best trial: 26. Best value: 0.687451:  76%|███████▌  | 152/200 [02:19<00:33,  1.45it/s]

[I 2025-11-10 14:46:08,783] Trial 152 pruned.

Best trial: 26. Best value: 0.687451:  76%|███████▋  | 153/200 [02:20<00:38,  1.22it/s]

[I 2025-11-10 14:46:09,920] Trial 155 pruned.

Best trial: 26. Best value: 0.687451:  77%|███████▋  | 154/200 [02:21<00:31,  1.48it/s]

[I 2025-11-10 14:46:10,248] Trial 149 finished with value: 0.635686274509804 and parameters: {'max_depth': 9, 'learning_rate': 0.018583872433927014, 'n_estimators': 1484, 'subsample': 0.9322539651678768, 'colsample_bytree': 0.5432232806926919, 'min_child_weight': 5, 'gamma': 2.1223742292286936, 'reg_alpha': 9.017956192034057e-05, 'reg_lambda': 1.7960513510904815e-08, 'max_delta_step': 0}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  78%|███████▊  | 155/200 [02:21<00:34,  1.31it/s]

[I 2025-11-10 14:46:11,223] Trial 156 pruned.

Best trial: 26. Best value: 0.687451:  78%|███████▊  | 156/200 [02:23<00:37,  1.18it/s]

[I 2025-11-10 14:46:12,264] Trial 158 pruned.

Best trial: 26. Best value: 0.687451:  78%|███████▊  | 157/200 [02:24<00:43,  1.02s/it]

[I 2025-11-10 14:46:13,685] Trial 153 finished with value: 0.6698039215686274 and parameters: {'max_depth': 6, 'learning_rate': 0.012250031246120997, 'n_estimators': 1147, 'subsample': 0.9570762482829124, 'colsample_bytree': 0.5870509388534689, 'min_child_weight': 5, 'gamma': 1.7958141715540008, 'reg_alpha': 8.548048727754338e-05, 'reg_lambda': 1.7862744438620497e-08, 'max_delta_step': 0}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  79%|███████▉  | 158/200 [02:25<00:37,  1.11it/s]

[I 2025-11-10 14:46:14,325] Trial 154 finished with value: 0.6792156862745097 and parameters: {'max_depth': 8, 'learning_rate': 0.012316952073973124, 'n_estimators': 1169, 'subsample': 0.9073866586443142, 'colsample_bytree': 0.5851088275672829, 'min_child_weight': 5, 'gamma': 1.782122293166641, 'reg_alpha': 0.0002678400454613193, 'reg_lambda': 1.0294925107852895e-08, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  80%|███████▉  | 159/200 [02:26<00:40,  1.02it/s]

[I 2025-11-10 14:46:15,479] Trial 161 pruned.

Best trial: 26. Best value: 0.687451:  80%|████████  | 160/200 [02:26<00:34,  1.16it/s]

[I 2025-11-10 14:46:16,070] Trial 157 finished with value: 0.6556862745098039 and parameters: {'max_depth': 8, 'learning_rate': 0.015768977641011452, 'n_estimators': 1168, 'subsample': 0.9595033593014921, 'colsample_bytree': 0.5338766794769382, 'min_child_weight': 5, 'gamma': 1.4156202540265714, 'reg_alpha': 1.6483550278901145e-05, 'reg_lambda': 3.2247590568903466e-08, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  80%|████████  | 161/200 [02:28<00:46,  1.20s/it]

[I 2025-11-10 14:46:18,062] Trial 159 finished with value: 0.6449019607843137 and parameters: {'max_depth': 7, 'learning_rate': 0.01397581868773671, 'n_estimators': 1211, 'subsample': 0.9433504911699341, 'colsample_bytree': 0.5612948620866176, 'min_child_weight': 5, 'gamma': 2.2373455728688225, 'reg_alpha': 7.593099029333101e-06, 'reg_lambda': 2.954296099342976e-07, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  81%|████████  | 162/200 [02:30<00:48,  1.27s/it]

[I 2025-11-10 14:46:19,499] Trial 164 pruned.

Best trial: 26. Best value: 0.687451:  82%|████████▏ | 163/200 [02:31<00:48,  1.31s/it]

[I 2025-11-10 14:46:20,896] Trial 160 finished with value: 0.6390196078431373 and parameters: {'max_depth': 7, 'learning_rate': 0.028023684973822082, 'n_estimators': 1433, 'subsample': 0.9412656529502237, 'colsample_bytree': 0.5649379448665958, 'min_child_weight': 5, 'gamma': 2.2862036093753577, 'reg_alpha': 0.0002001684457177034, 'reg_lambda': 2.6512710766176935e-07, 'max_delta_step': 1}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 26. Best value: 0.687451:  82%|████████▏ | 164/200 [02:32<00:37,  1.04s/it]

[I 2025-11-10 14:46:21,303] Trial 163 finished with value: 0.6639215686274509 and parameters: {'max_depth': 7, 'learning_rate': 0.013503452816813895, 'n_estimators': 1046, 'subsample': 0.9176168062357719, 'colsample_bytree': 0.5998067433218349, 'min_child_weight': 5, 'gamma': 1.9533306912894854, 'reg_alpha': 0.00031918751732406, 'reg_lambda': 1.365715169738637e-08, 'max_delta_step': 0}. Best is trial 26 with value: 0.6874509803921568.

Best trial: 162. Best value: 0.699216:  82%|████████▎ | 165/200 [02:32<00:28,  1.24it/s]

[I 2025-11-10 14:46:21,562] Trial 162 finished with value: 0.6992156862745097 and parameters: {'max_depth': 8, 'learning_rate': 0.013807116248478276, 'n_estimators': 1182, 'subsample': 0.9130476787436426, 'colsample_bytree': 0.6039498951084883, 'min_child_weight': 5, 'gamma': 1.9760055112300203, 'reg_alpha': 0.0003299570188050603, 'reg_lambda': 1.05798556041437e-08, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.

Best trial: 162. Best value: 0.699216:  83%|████████▎ | 166/200 [02:32<00:24,  1.38it/s]

[I 2025-11-10 14:46:22,106] Trial 166 pruned.

Best trial: 162. Best value: 0.699216:  84%|████████▎ | 167/200 [02:33<00:24,  1.36it/s]

[I 2025-11-10 14:46:22,871] Trial 167 pruned.

Best trial: 162. Best value: 0.699216:  84%|████████▍ | 168/200 [02:34<00:29,  1.08it/s]

[I 2025-11-10 14:46:24,221] Trial 170 pruned.

Best trial: 162. Best value: 0.699216:  84%|████████▍ | 169/200 [02:35<00:25,  1.22it/s]

[I 2025-11-10 14:46:24,793] Trial 165 finished with value: 0.6933333333333332 and parameters: {'max_depth': 8, 'learning_rate': 0.02829520856169942, 'n_estimators': 1076, 'subsample': 0.8961420182010991, 'colsample_bytree': 0.5516628627933224, 'min_child_weight': 5, 'gamma': 1.9918082932316508, 'reg_alpha': 0.00041525677866873764, 'reg_lambda': 9.965539148493146e-08, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.

Best trial: 162. Best value: 0.699216:  85%|████████▌ | 170/200 [02:36<00:26,  1.13it/s]

[I 2025-11-10 14:46:25,828] Trial 172 pruned.

Best trial: 162. Best value: 0.699216:  86%|████████▌ | 171/200 [02:38<00:34,  1.17s/it]

[I 2025-11-10 14:46:27,681] Trial 169 finished with value: 0.6698039215686274 and parameters: {'max_depth': 8, 'learning_rate': 0.01252899215728307, 'n_estimators': 1088, 'subsample': 0.9236351801585873, 'colsample_bytree': 0.6115835220904552, 'min_child_weight': 5, 'gamma': 2.041156842367427, 'reg_alpha': 0.00097755493376599, 'reg_lambda': 2.310012614694092e-08, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.

Best trial: 162. Best value: 0.699216:  86%|████████▌ | 172/200 [02:38<00:25,  1.09it/s]

[I 2025-11-10 14:46:27,992] Trial 168 finished with value: 0.6458823529411765 and parameters: {'max_depth': 8, 'learning_rate': 0.017380543891027715, 'n_estimators': 1191, 'subsample': 0.901983400544387, 'colsample_bytree': 0.6046041094185479, 'min_child_weight': 5, 'gamma': 2.418996559224718, 'reg_alpha': 0.0009340750906248692, 'reg_lambda': 1.0543395186323107e-08, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.

Best trial: 162. Best value: 0.699216:  86%|████████▋ | 173/200 [02:39<00:24,  1.10it/s]

[I 2025-11-10 14:46:28,889] Trial 174 pruned.

Best trial: 162. Best value: 0.699216:  87%|████████▋ | 174/200 [02:39<00:19,  1.36it/s]

[I 2025-11-10 14:46:29,213] Trial 175 pruned.

Best trial: 162. Best value: 0.699216:  88%|████████▊ | 175/200 [02:40<00:20,  1.23it/s]

[I 2025-11-10 14:46:30,221] Trial 176 pruned.

Best trial: 162. Best value: 0.699216:  88%|████████▊ | 176/200 [02:41<00:15,  1.50it/s]

[I 2025-11-10 14:46:30,543] Trial 171 finished with value: 0.6792156862745097 and parameters: {'max_depth': 8, 'learning_rate': 0.014400681769405416, 'n_estimators': 1183, 'subsample': 0.908251717592721, 'colsample_bytree': 0.5856199724734056, 'min_child_weight': 5, 'gamma': 1.7094937498617562, 'reg_alpha': 0.0007079409477229506, 'reg_lambda': 9.763956559426164e-08, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.

Best trial: 162. Best value: 0.699216:  88%|████████▊ | 177/200 [02:42<00:16,  1.37it/s]

[I 2025-11-10 14:46:31,421] Trial 178 pruned.
[I 2025-11-10 14:46:31,453] Trial 173 finished with value: 0.6756862745098039 and parameters: {'max_depth': 8, 'learning_rate': 0.014523209049014591, 'n_estimators': 1008, 'subsample': 0.917854367468861, 'colsample_bytree': 0.7922081218574667, 'min_child_weight': 5, 'gamma': 2.4617862967777606, 'reg_alpha': 0.0015372339171658284, 'reg_lambda': 1.1501956218816812e-07, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.

Best trial: 162. Best value: 0.699216:  90%|████████▉ | 179/200 [02:43<00:14,  1.42it/s]

[I 2025-11-10 14:46:32,771] Trial 180 pruned.

Best trial: 162. Best value: 0.699216:  90%|█████████ | 180/200 [02:44<00:17,  1.15it/s]

[I 2025-11-10 14:46:34,122] Trial 182 pruned.

Best trial: 162. Best value: 0.699216:  90%|█████████ | 181/200 [02:45<00:17,  1.09it/s]

[I 2025-11-10 14:46:35,188] Trial 183 pruned.

Best trial: 162. Best value: 0.699216:  91%|█████████ | 182/200 [02:46<00:14,  1.21it/s]

[I 2025-11-10 14:46:35,780] Trial 177 finished with value: 0.6815686274509803 and parameters: {'max_depth': 8, 'learning_rate': 0.021476535311926944, 'n_estimators': 1225, 'subsample': 0.9118660048413879, 'colsample_bytree': 0.5516683601065584, 'min_child_weight': 5, 'gamma': 1.3270292761901188, 'reg_alpha': 0.0004959604388037402, 'reg_lambda': 1.0955907752029916e-07, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.

Best trial: 162. Best value: 0.699216:  92%|█████████▏| 183/200 [02:47<00:12,  1.32it/s]

[I 2025-11-10 14:46:36,354] Trial 184 pruned.

Best trial: 162. Best value: 0.699216:  92%|█████████▏| 184/200 [02:47<00:10,  1.50it/s]

[I 2025-11-10 14:46:36,802] Trial 179 finished with value: 0.6874509803921568 and parameters: {'max_depth': 9, 'learning_rate': 0.015238156189782012, 'n_estimators': 1232, 'subsample': 0.9123398210647449, 'colsample_bytree': 0.5932740140656994, 'min_child_weight': 5, 'gamma': 1.9031550755280622, 'reg_alpha': 0.0010437787430486883, 'reg_lambda': 3.745346573941621e-08, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.

Best trial: 162. Best value: 0.699216:  92%|█████████▎| 185/200 [02:48<00:10,  1.37it/s]

[I 2025-11-10 14:46:37,680] Trial 181 finished with value: 0.6733333333333332 and parameters: {'max_depth': 9, 'learning_rate': 0.014932053158697544, 'n_estimators': 1217, 'subsample': 0.892074039603568, 'colsample_bytree': 0.7958900463268624, 'min_child_weight': 5, 'gamma': 2.7444372413950293, 'reg_alpha': 0.002422500003218396, 'reg_lambda': 1.0919215440344274e-07, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.
[I 2025-11-10 14:46:37,691] Trial 186 pruned.

Best trial: 162. Best value: 0.699216:  94%|█████████▎| 187/200 [02:49<00:08,  1.49it/s]

[I 2025-11-10 14:46:38,875] Trial 189 pruned.
[I 2025-11-10 14:46:38,905] Trial 188 pruned.

Best trial: 162. Best value: 0.699216:  94%|█████████▍| 189/200 [02:50<00:07,  1.50it/s]

[I 2025-11-10 14:46:40,193] Trial 191 pruned.

Best trial: 162. Best value: 0.699216:  95%|█████████▌| 190/200 [02:52<00:08,  1.22it/s]

[I 2025-11-10 14:46:41,555] Trial 192 pruned.

Best trial: 162. Best value: 0.699216:  96%|█████████▌| 191/200 [02:52<00:06,  1.29it/s]

[I 2025-11-10 14:46:42,187] Trial 185 finished with value: 0.6350980392156863 and parameters: {'max_depth': 8, 'learning_rate': 0.016450949131889693, 'n_estimators': 1234, 'subsample': 0.8904577151763835, 'colsample_bytree': 0.5534839669817666, 'min_child_weight': 5, 'gamma': 1.3331641667081666, 'reg_alpha': 0.0016063317458944975, 'reg_lambda': 1.3200258555896056, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.

Best trial: 162. Best value: 0.699216:  96%|█████████▌| 192/200 [02:54<00:07,  1.14it/s]

[I 2025-11-10 14:46:43,377] Trial 187 finished with value: 0.5950980392156863 and parameters: {'max_depth': 9, 'learning_rate': 0.01417077145024798, 'n_estimators': 1208, 'subsample': 0.868371285405579, 'colsample_bytree': 0.7957160788247207, 'min_child_weight': 5, 'gamma': 2.946819246229235, 'reg_alpha': 0.0015732688785827437, 'reg_lambda': 1.0577099519208614e-07, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.

Best trial: 162. Best value: 0.699216:  96%|█████████▋| 193/200 [02:55<00:07,  1.14s/it]

[I 2025-11-10 14:46:45,228] Trial 190 finished with value: 0.6233333333333333 and parameters: {'max_depth': 9, 'learning_rate': 0.01664563784244172, 'n_estimators': 1202, 'subsample': 0.8759707828890773, 'colsample_bytree': 0.8446604611781939, 'min_child_weight': 5, 'gamma': 2.0847091201153343, 'reg_alpha': 0.00027571084312974004, 'reg_lambda': 3.0952296018913584e-08, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.

Best trial: 162. Best value: 0.699216:  97%|█████████▋| 194/200 [02:58<00:08,  1.39s/it]

[I 2025-11-10 14:46:47,270] Trial 193 finished with value: 0.6756862745098039 and parameters: {'max_depth': 8, 'learning_rate': 0.01996843966431811, 'n_estimators': 1130, 'subsample': 0.9400544108410646, 'colsample_bytree': 0.8087579828954772, 'min_child_weight': 5, 'gamma': 3.003650147902216, 'reg_alpha': 0.005559452550698123, 'reg_lambda': 3.104253287529438e-08, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.

Best trial: 162. Best value: 0.699216:  98%|█████████▊| 195/200 [02:58<00:06,  1.23s/it]

[I 2025-11-10 14:46:48,087] Trial 194 finished with value: 0.6815686274509803 and parameters: {'max_depth': 9, 'learning_rate': 0.015313558339367917, 'n_estimators': 1206, 'subsample': 0.8959182180332211, 'colsample_bytree': 0.8168793123245618, 'min_child_weight': 5, 'gamma': 2.9984607454024537, 'reg_alpha': 0.00618729122897029, 'reg_lambda': 1.1074031909854867e-07, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.

Best trial: 162. Best value: 0.699216:  98%|█████████▊| 196/200 [02:59<00:04,  1.18s/it]

[I 2025-11-10 14:46:49,146] Trial 195 finished with value: 0.6756862745098039 and parameters: {'max_depth': 9, 'learning_rate': 0.015604779620229473, 'n_estimators': 1153, 'subsample': 0.8966659781348555, 'colsample_bytree': 0.8184850439304875, 'min_child_weight': 5, 'gamma': 3.219645019467748, 'reg_alpha': 0.0035361727305215905, 'reg_lambda': 8.936028566981652e-08, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.

Best trial: 162. Best value: 0.699216:  98%|█████████▊| 197/200 [03:02<00:04,  1.64s/it]

[I 2025-11-10 14:46:51,917] Trial 196 finished with value: 0.6756862745098038 and parameters: {'max_depth': 9, 'learning_rate': 0.01503694229178023, 'n_estimators': 1294, 'subsample': 0.8960398017345835, 'colsample_bytree': 0.7714099058402633, 'min_child_weight': 5, 'gamma': 2.799405939951633, 'reg_alpha': 0.003160738422452737, 'reg_lambda': 7.667432149758494e-08, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.

Best trial: 162. Best value: 0.699216:  99%|█████████▉| 198/200 [03:03<00:02,  1.36s/it]

[I 2025-11-10 14:46:52,612] Trial 197 finished with value: 0.6756862745098039 and parameters: {'max_depth': 8, 'learning_rate': 0.021525275954469694, 'n_estimators': 1070, 'subsample': 0.9344028093408835, 'colsample_bytree': 0.8336021144811544, 'min_child_weight': 5, 'gamma': 1.5853588887680283, 'reg_alpha': 0.000614706817399027, 'reg_lambda': 7.282960947564935e-08, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.

Best trial: 162. Best value: 0.699216: 100%|█████████▉| 199/200 [03:03<00:01,  1.13s/it]

[I 2025-11-10 14:46:53,192] Trial 198 finished with value: 0.6556862745098039 and parameters: {'max_depth': 9, 'learning_rate': 0.015052818619326785, 'n_estimators': 1162, 'subsample': 0.9053046288500237, 'colsample_bytree': 0.8189881902690188, 'min_child_weight': 5, 'gamma': 1.5808104353453607, 'reg_alpha': 0.0006794228302045399, 'reg_lambda': 7.025652558853064e-08, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.

Best trial: 162. Best value: 0.699216: 100%|██████████| 200/200 [03:04<00:00,  1.08it/s]

[I 2025-11-10 14:46:53,650] Trial 199 finished with value: 0.6674509803921568 and parameters: {'max_depth': 9, 'learning_rate': 0.015071448227567352, 'n_estimators': 1068, 'subsample': 0.9086320031937613, 'colsample_bytree': 0.8280620660848316, 'min_child_weight': 5, 'gamma': 1.5688096773246283, 'reg_alpha': 0.0004964892225298934, 'reg_lambda': 1.7746965325451376e-07, 'max_delta_step': 0}. Best is trial 162 with value: 0.6992156862745097.
   dataset  cv_best_value  test_balanced_accuracy  test_roc_auc  n_trials
0      3_3       0.690643                0.819876      0.863354       200
1     16_1       0.657368                0.649068      0.686335       200
2      3_5       0.547135                0.639752      0.614907       200
3     17_1       0.569532                0.627329      0.795031       200
4      1_1       0.501754                0.596273      0.649068       200
5     10_1       0.572047                0.568323      0.531056       200
6      9_1       0.595355                0.562937      0.568182       200
7      3_2       0.501170                0.540373      0.527950       200
8     18_1       0.642281                0.506211      0.568323       200
9      3_1       0.582398                0.447205      0.428571       200
10    19_1       0.699216                0.439394      0.416667       200
11     3_4       0.614211                0.397516      0.559006       200
12    15_1       0.584795                0.360248      0.385093       200