In [1398]:
import pathlib as Path
import numpy as np
import pandas as pd


## Create dataframe from embeddings

In [1399]:
#-----Frequency Embeddings dataframe creation-----
def create_embeddings_dataframe(root_path):
    emb_root = Path.Path(root_path)
    emb_files = emb_root.rglob("embeddings_samples.npz")
    
    all_data = []
    
    for emb_file in emb_files:
        emb = np.load(emb_file)
        X = emb['X']
        y = emb['y']
        subjects = emb['subs']
        
        for i in range(X.shape[0]):
            data_point = {
                'embedding': X[i],
                'label': y[i],
                'subject': subjects[i],
                'file_path': str(emb_file)
            }
            all_data.append(data_point)
    
    df = pd.DataFrame(all_data)
    return df


## Clean embedding DF

In [1400]:

def df_cleaning(df, emb_size=384):
        # --- Expand embedding column into 381 separate columns ---
    embedding_df = pd.DataFrame(df["embedding"].tolist(),
                                columns=[f"emb_{i}" for i in range(emb_size)])

    # --- Concatenate back to the original DataFrame (optional) ---
    df_expanded = pd.concat([df.drop(columns=["embedding"]), embedding_df], axis=1)
    return df_expanded

In [1401]:
#-----Frequency Embeddings dataframe creation-----
freq_emb= create_embeddings_dataframe("C://dev//dolphin_initial_testing//DOLPHIN//out_prelbd_task_wise//frequency_emb_stored//")
#-----Temporal Embeddings dataframe creation-----
temp_emb= create_embeddings_dataframe("C://dev//dolphin_initial_testing//DOLPHIN//out_prelbd_task_wise//temporal_emb_stored//")
#-----Combined Embeddings dataframe creation-----
comb_emb= create_embeddings_dataframe("C://dev//dolphin_initial_testing//DOLPHIN//out_prelbd_task_wise//emb_stored//")

freq_emb_df= df_cleaning(freq_emb, emb_size=384)
temp_emb_df= df_cleaning(temp_emb, emb_size=384)
comb_emb_df= df_cleaning(comb_emb, emb_size=768)

In [1402]:
freq_emb_df

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_374,emb_375,emb_376,emb_377,emb_378,emb_379,emb_380,emb_381,emb_382,emb_383
0,1,COBEN-WTABLET-AS-HCD05,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.020803,0.024742,-0.001459,-0.030411,0.005069,-0.071482,0.019421,...,0.009478,0.034411,0.014662,-0.090859,0.069126,-0.047900,0.006064,0.018750,0.061787,-0.008002
1,1,COBEN-WTABLET-BB-PD08,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.019917,0.024111,-0.002791,-0.029054,0.005171,-0.070701,0.019973,...,0.010498,0.034390,0.016988,-0.092144,0.067938,-0.048388,0.005863,0.019660,0.060609,-0.008458
2,1,COBEN-WTABLET-DM-AD15,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.018108,0.025302,-0.001694,-0.028552,0.005417,-0.068487,0.017704,...,0.009714,0.035088,0.015138,-0.094040,0.067323,-0.048907,0.007274,0.020602,0.062291,-0.008537
3,1,COBEN-WTABLET-DM-PD17,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.019036,0.021408,-0.004025,-0.027294,0.004202,-0.070225,0.019877,...,0.012248,0.033855,0.017426,-0.091839,0.065746,-0.050177,0.005471,0.024139,0.059553,-0.007032
4,1,COBEN-WTABLET-DS-HC36,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.021802,0.026779,-0.001436,-0.032483,0.004540,-0.069463,0.018237,...,0.008617,0.035733,0.016321,-0.092127,0.071785,-0.046817,0.006332,0.016091,0.062483,-0.007423
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3430,1,pre-LBD-94#2,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.005028,0.034374,0.061780,0.096021,-0.090914,0.009212,-0.036042,...,0.008554,0.041628,0.071675,-0.009670,-0.037761,-0.050154,-0.028794,-0.038353,0.011298,-0.001504
3431,1,pre-LBD-96#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.000751,0.024619,0.056822,0.087980,-0.087306,0.005802,-0.030083,...,-0.002332,0.043072,0.091577,0.005234,-0.022814,-0.044438,-0.027096,-0.046104,0.014481,0.000398
3432,1,pre-LBD-97#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.002169,0.023951,0.058569,0.092896,-0.085801,0.012066,-0.028993,...,0.001909,0.046956,0.091510,-0.001470,-0.026675,-0.046634,-0.031475,-0.044283,0.010021,-0.001683
3433,1,pre-LBD-98#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.003187,0.033540,0.066936,0.097512,-0.089142,0.006719,-0.040898,...,0.002540,0.036012,0.074694,-0.002932,-0.039761,-0.050872,-0.029519,-0.038850,0.010978,-0.004932
3434,1,pre-LBD-99#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.003345,0.023292,0.056422,0.090034,-0.088472,0.011161,-0.024125,...,-0.000490,0.048869,0.095669,0.000146,-0.021082,-0.044887,-0.032762,-0.042210,0.009381,-0.000027

In [1403]:

metadata_path = ('C://dev//dolphin_initial_testing//DOLPHIN//data-raw//LBD_CZ_002_metadata//preDLB_shared(PSY_RAW).csv')
df_metadata = pd.read_csv(metadata_path, sep=";", encoding="utf-8-sig")

In [1404]:
clinical_data_path = ('C://dev//dolphin_initial_testing//DOLPHIN//data-raw//LBD_CZ_002_metadata//clinical_data_csv.csv')
df_clinical = pd.read_csv(clinical_data_path, sep=",", encoding="utf-8-sig")

In [1405]:
handcrafted_features_path = ('C://dev//dolphin_initial_testing//DOLPHIN//data-raw//LBD_CZ_002_hf//corpus_LBD_CZ_002_writing_results_table_original_filtered_extended.csv')
df_handcrafted_features = pd.read_csv(handcrafted_features_path, sep=";", encoding="utf-8-sig")

In [1406]:
import re
import pandas as pd

def append_col_when_main_contains_source(
    df_main, df_source, *, 
    match_col_main="subject",            # in df_main
    match_col_source="ID_1.meranie",     # in df_source
    value_col="HC0_nHC1_MCI2_MCILB3_baseline",
    new_col_name="diagnosis",
    case=False
):
    df_main = df_main.copy()
    df_source = df_source.copy()

    # normalize + keep only rows in source with non-missing values
    df_main[match_col_main] = df_main[match_col_main].astype(str).str.strip()
    df_source[match_col_source] = df_source[match_col_source].astype(str).str.strip()
    df_source = df_source.dropna(subset=[value_col])

    # init target column
    if new_col_name not in df_main:
        df_main[new_col_name] = pd.NA

    # for each source row, mark all main rows whose subject CONTAINS the source token
    for _, r in df_source.iterrows():
        token = r[match_col_source]
        if not token:
            continue
        mask = df_main[match_col_main].str.contains(re.escape(token), na=False, case=not case)
        # write only where we don't have a value yet (keeps first hit)
        to_set = mask & df_main[new_col_name].isna()
        df_main.loc[to_set, new_col_name] = r[value_col]

    return df_main

In [1407]:
freq_emb_df_lbl = append_col_when_main_contains_source(
    df_main=freq_emb_df,
    df_source=df_metadata,
    match_col_main="subject",
    match_col_source="ID_1.meranie",
    value_col="HC0_nHC1_MCI2_MCILB3_baseline",
    new_col_name="diagnosis",
    case=False
)

In [1408]:
freq_emb_df_lbl.to_csv("LBD_CZ_002_COBEN_dfs/freq_emb_df_half_lbl.csv", sep=";")

In [1409]:

temp_emb_df_lbl = append_col_when_main_contains_source(
    df_main=temp_emb_df,
    df_source=df_metadata,
    match_col_main="subject",
    match_col_source="ID_1.meranie",
    value_col="HC0_nHC1_MCI2_MCILB3_baseline",
    new_col_name="diagnosis",
    case=False
)

In [1410]:

temp_emb_df_lbl.to_csv("LBD_CZ_002_COBEN_dfs/temp_emb_df_half__lbl.csv", sep=";")

In [1411]:

comb_emb_df_lbl = append_col_when_main_contains_source(
    df_main=comb_emb_df,
    df_source=df_metadata,
    match_col_main="subject",
    match_col_source="ID_1.meranie",
    value_col="HC0_nHC1_MCI2_MCILB3_baseline",
    new_col_name="diagnosis",
    case=False
)

In [1412]:
comb_emb_df_lbl.to_csv("LBD_CZ_002_COBEN_dfs/comb_emb_df_half__lbl.csv", sep=";")

In [1413]:

df_handcrafted_lbl = append_col_when_main_contains_source(
    df_main=df_handcrafted_features,
    df_source=df_metadata,
    match_col_main="ID",
    match_col_source="ID_1.meranie",
    value_col="HC0_nHC1_MCI2_MCILB3_baseline",
    new_col_name="diagnosis",
    case=False
)

In [1414]:

df_handcrafted_lbl.to_csv("LBD_CZ_002_COBEN_dfs/df_handcrafted_half_lbl.csv", sep=";")

In [1415]:
#temp_emb_df_complet_lbl = pd.read_csv("LBD_CZ_002_COBEN_dfs/temp_emb_df_lbl.csv", sep=";")

#freq_emb_df_complet_lbl= pd.read_csv("./LBD_CZ_002_COBEN_dfs/freq_emb_df_lbl.csv", sep=";")

#comb_emb_df_complet_lbl= pd.read_csv("LBD_CZ_002_COBEN_dfs/comb_emb_df_lbl.csv", sep=";")

hf_emb_df_complet_lbl= pd.read_csv("LBD_CZ_002_COBEN_dfs/df_handcrafted_lbl.csv", sep=";")

In [1416]:

import pandas as pd

def assign_diagnosis(df: pd.DataFrame,
                     subject_col: str = "subject",
                     diagnosis_col: str = "diagnosis") -> pd.DataFrame:
    """Populate `diagnosis_col` based on text in `subject_col`.

    - rows whose subject contains '#' are left untouched
    - 'HC' → 0.0, 'AD' → 2.0, 'PD' → 4.0
    """
    if diagnosis_col not in df.columns:
        df[diagnosis_col] = pd.NA

    subj = df[subject_col].astype(str)
    has_hash = subj.str.contains("#", na=False)

    mapping = {"HC": 0.0, "AD": 2.0, "PD": 4.0}
    for key, value in mapping.items():
        mask = (~has_hash) & subj.str.contains(key, na=False)
        df.loc[mask, diagnosis_col] = value

    return df

In [1417]:
temp_emb_df_complet_lbl = assign_diagnosis(temp_emb_df_lbl)

freq_emb_df_complet_lbl= assign_diagnosis(freq_emb_df_lbl)

comb_emb_df_complet_lbl=assign_diagnosis(comb_emb_df_lbl)

In [1418]:
import pandas as pd

def assign_diagnosis(df: pd.DataFrame,
                     subject_col: str = "subject",
                     diagnosis_col: str = "diagnosis") -> pd.DataFrame:
    """Populate `diagnosis_col` based on text in `subject_col`.

    - rows whose subject contains '#' are left untouched
    - 'HC' → 0.0, 'AD' → 2.0, 'PD' → 4.0
    """
    if diagnosis_col not in df.columns:
        df[diagnosis_col] = pd.NA

    subj = df[subject_col].astype(str)
    has_hash = subj.str.contains("#", na=False)

    mapping = {"HC": 0.0, "AD": 2.0, "PD": 4.0}
    for key, value in mapping.items():
        mask = (~has_hash) & subj.str.contains(key, na=False)
        df.loc[mask, diagnosis_col] = value

    return df

In [1419]:
def append_multiple_cols_when_main_contains_source(
    df_main, df_source, *,
    match_col_main="subject",
    match_col_source="ID_1.meranie",
    value_cols=("HC0_nHC1_MCI2_MCILB3_baseline",),
    case=False
):
    df_main = df_main.copy()
    df_source = df_source.copy()

    # normalize + clean
    df_main[match_col_main] = df_main[match_col_main].astype(str).str.strip()
    df_source[match_col_source] = df_source[match_col_source].astype(str).str.strip()

    # initialize missing columns
    for col in value_cols:
        if col not in df_main.columns:
            df_main[col] = pd.NA

    # iterate through source
    for _, r in df_source.iterrows():
        token = r[match_col_source]
        if not token or pd.isna(token):
            continue

        # use 'case' argument as passed (was inverted before)
        mask = df_main[match_col_main].str.contains(re.escape(str(token)), na=False, case=case)
        to_set = mask

        # assign all defined value columns
        for col in value_cols:
            if col not in r or pd.isna(r[col]):
                continue
            df_main.loc[to_set & df_main[col].isna(), col] = r[col]

    return df_main

In [1420]:
clinical_hf_emb_df_complet_lbl = append_multiple_cols_when_main_contains_source(
    df_main=hf_emb_df_complet_lbl,
    df_source=df_clinical,
    match_col_main="ID",
    match_col_source="#personalID",
    value_cols=["age",
                "gender",
                "MOCA",
                "education type",
                "education length",
                "memory z-score",
                "visuo-spatial z-score",
                "attention z-score",
                "executive function z-score",
                "GDS"]
)

In [1421]:
temp_emb_df_complet_lbl_2 = temp_emb_df_complet_lbl.drop(temp_emb_df_complet_lbl.columns[0], axis=1)
freq_emb_df_complet_lbl_2 = freq_emb_df_complet_lbl.drop(freq_emb_df_complet_lbl.columns[0], axis=1)
comb_emb_df_complet_lbl_2 = comb_emb_df_complet_lbl.drop(comb_emb_df_complet_lbl.columns[0], axis=1)
hf_emb_df_complet_lbl_2 = hf_emb_df_complet_lbl.drop(hf_emb_df_complet_lbl.columns[0], axis=1)

In [1422]:

hf_emb_df_complet_lbl = hf_emb_df_complet_lbl.drop(hf_emb_df_complet_lbl.columns[0], axis=1)

# Spearsman correlation / finding covariants

In [1423]:

cols_to_convert = clinical_hf_emb_df_complet_lbl.columns[1:]

clinical_hf_emb_df_complet_lbl[cols_to_convert] = (
    clinical_hf_emb_df_complet_lbl[cols_to_convert]
    .apply(lambda col: pd.to_numeric(col.astype(str).str.replace(',', '.'), errors='coerce'))
)

In [1424]:
clinical_hf_emb_df_complet_lbl.dtypes

Unnamed: 0                                                    int64
ID                                                          float64
w.cz.fnusa.15_1_95th percentile of acceleration (in-air)    float64
w.cz.fnusa.16_1_95th percentile of acceleration (in-air)    float64
w.cz.fnusa.17_1_95th percentile of acceleration (in-air)    float64
                                                             ...
memory z-score                                              float64
visuo-spatial z-score                                       float64
attention z-score                                           float64
executive function z-score                                  float64
GDS                                                         float64
Length: 463, dtype: object

In [1425]:

from scipy import stats
import numpy as np

meta_cols=["age",
         #   "gender",
            "MOCA",
            "education type",
            "education length",
            "memory z-score",
            "visuo-spatial z-score",
            "attention z-score",
            "executive function z-score",
            "GDS"]

feature_cols = clinical_hf_emb_df_complet_lbl.drop(columns=['ID', 'diagnosis','gender'] + meta_cols).columns.tolist()


def correlation_to_df(df, feature_cols, meta_cols, corr_type='spearman'):
    from scipy import stats
    corr_results = []
    for feature in feature_cols:
        for meta in meta_cols:
            feature_data = pd.to_numeric(df[feature], errors='coerce')
            meta_data = pd.to_numeric(df[meta], errors='coerce')
            if corr_type == 'spearman':
                corr, p_value = stats.spearmanr(feature_data, meta_data, nan_policy='omit')
            elif corr_type == 'pearson':
                corr, p_value = stats.pearsonr(feature_data.dropna(), meta_data.dropna())
            else:
                raise ValueError("corr_type must be 'spearman' or 'pearson'")
            corr_results.append({
                'feature': feature,
                'meta_variable': meta,
                'correlation': corr,
                'p_value': p_value
            })
    corr_df = pd.DataFrame(corr_results)
    return corr_df

In [1426]:
import numpy as np
import pandas as pd
from scipy import stats

def safe_spearman(x, y, min_n=3):
    """
    x, y: 1D array-like
    returns (rho, p, n_used)
    """
    x = pd.to_numeric(pd.Series(x), errors="coerce")
    y = pd.to_numeric(pd.Series(y), errors="coerce")

    mask = x.notna() & y.notna()
    x2 = x[mask].values
    y2 = y[mask].values
    n = len(x2)

    if n < min_n:
        return np.nan, np.nan, n

    # constant vectors -> undefined correlation
    if np.all(x2 == x2[0]) or np.all(y2 == y2[0]):
        return np.nan, np.nan, n

    rho, p = stats.spearmanr(x2, y2)
    # spearmanr can still return nan if ties/degenerate
    if not np.isfinite(rho):
        rho, p = np.nan, np.nan
    return rho, p, n


def correlation_to_df(df, feature_cols, meta_cols, corr_type="spearman", min_n=3):
    rows = []
    for feat in feature_cols:
        feature_data = df[feat]

        for meta in meta_cols:
            meta_data = df[meta]

            if corr_type == "spearman":
                corr, p_value, n_used = safe_spearman(feature_data, meta_data, min_n=min_n)
            elif corr_type == "pearson":
                # paired dropna for pearson too
                x = pd.to_numeric(feature_data, errors="coerce")
                y = pd.to_numeric(meta_data, errors="coerce")
                mask = x.notna() & y.notna()
                x2, y2 = x[mask].values, y[mask].values
                n_used = len(x2)
                if n_used < min_n or np.all(x2 == x2[0]) or np.all(y2 == y2[0]):
                    corr, p_value = np.nan, np.nan
                else:
                    corr, p_value = stats.pearsonr(x2, y2)
            else:
                raise ValueError("corr_type must be 'spearman' or 'pearson'")

            rows.append({
                "feature": feat,
                "meta": meta,
                "corr": corr,
                "p_value": p_value,
                "n_used": n_used
            })

    return pd.DataFrame(rows)

In [1427]:
clinical_hf_emb_df_complet_lbl

,Unnamed: 0,ID,w.cz.fnusa.15_1_95th percentile of acceleration (in-air),w.cz.fnusa.16_1_95th percentile of acceleration (in-air),w.cz.fnusa.17_1_95th percentile of acceleration (in-air),w.cz.fnusa.18_1_95th percentile of acceleration (in-air),w.cz.fnusa.19_1_95th percentile of acceleration (in-air),w.cz.fnusa.9_1_95th percentile of acceleration (in-air),w.cz.fnusa.15_1_95th percentile of acceleration (on-surface),w.cz.fnusa.16_1_95th percentile of acceleration (on-surface),...,age,gender,MOCA,education type,education length,memory z-score,visuo-spatial z-score,attention z-score,executive function z-score,GDS
0,0,NaN,1382.947668,2062.000865,2892.979665,2192.046228,2013.070361,2235.580284,586.734694,1627.424458,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,2184.038058,2960.491263,2833.151798,NaN,2643.941418,2704.362771,1705.984308,1274.972304,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,NaN,2129.216623,3373.868306,1686.794432,NaN,3212.659823,3435.479391,1657.058812,1573.868658,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,NaN,3973.130385,3650.787752,2810.386562,NaN,3278.226429,2390.344711,2226.888919,2314.558206,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,NaN,973.083976,1194.677753,2163.527710,NaN,1601.144846,1533.402248,581.075743,1754.342814,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,261,NaN,1771.638967,2223.266011,2726.863796,NaN,NaN,NaN,1248.437707,2379.581423,...,55.0,1.0,27.0,2.0,12.0,-0.43,-0.25,0.00,0.22,13.0
262,262,NaN,1587.495217,3116.456725,5244.552340,NaN,3146.502315,3071.576595,1670.497532,5487.155540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,263,NaN,1529.780961,2846.530626,3170.341400,NaN,2702.591544,1901.945515,914.354564,4092.897902,...,70.0,0.0,26.0,3.0,13.0,-0.66,1.08,-0.33,-1.17,4.0
264,264,NaN,1875.912627,2772.534223,3176.331668,NaN,2088.759949,2417.683099,775.466348,1565.536158,...,75.0,1.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,19.0
265,265,NaN,2703.445789,2786.521814,3986.122126,NaN,3537.716624,3013.638309,1474.404309,4968.999221,...,75.0,0.0,21.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0

In [1428]:
df_hf_clinical_corr = correlation_to_df(clinical_hf_emb_df_complet_lbl, feature_cols, meta_cols, corr_type='spearman')

In [1429]:
df_hf_clinical_corr

,feature,meta,corr,p_value,n_used
0,Unnamed: 0,age,0.221721,0.027412,99
1,Unnamed: 0,MOCA,-0.371650,0.000178,97
2,Unnamed: 0,education type,-0.337577,0.000769,96
3,Unnamed: 0,education length,-0.358016,0.000342,96
4,Unnamed: 0,memory z-score,0.102028,0.325190,95
...,...,...,...,...,...
4054,w.cz.fnusa.1_1_zero-crossing rate of spiral,memory z-score,0.142506,0.168318,95
4055,w.cz.fnusa.1_1_zero-crossing rate of spiral,visuo-spatial z-score,0.122164,0.240807,94
4056,w.cz.fnusa.1_1_zero-crossing rate of spiral,attention z-score,0.209750,0.041343,95
4057,w.cz.fnusa.1_1_zero-crossing rate of spiral,executive function z-score,0.268764,0.008450,95
4058,w.cz.fnusa.1_1_zero-crossing rate of spiral,GDS,-0.162664,0.111405,97

In [1430]:
df_hf_clinical_corr = df_hf_clinical_corr.drop(df_hf_clinical_corr.columns[-1], axis=1)

In [1431]:
df_hf_clinical_corr

,feature,meta,corr,p_value
0,Unnamed: 0,age,0.221721,0.027412
1,Unnamed: 0,MOCA,-0.371650,0.000178
2,Unnamed: 0,education type,-0.337577,0.000769
3,Unnamed: 0,education length,-0.358016,0.000342
4,Unnamed: 0,memory z-score,0.102028,0.325190
...,...,...,...,...
4054,w.cz.fnusa.1_1_zero-crossing rate of spiral,memory z-score,0.142506,0.168318
4055,w.cz.fnusa.1_1_zero-crossing rate of spiral,visuo-spatial z-score,0.122164,0.240807
4056,w.cz.fnusa.1_1_zero-crossing rate of spiral,attention z-score,0.209750,0.041343
4057,w.cz.fnusa.1_1_zero-crossing rate of spiral,executive function z-score,0.268764,0.008450
4058,w.cz.fnusa.1_1_zero-crossing rate of spiral,GDS,-0.162664,0.111405

In [1432]:
# Create separate pivots for correlation and p-value
#df_corr_pivot = df_hf_clinical_corr.pivot(
#    index='feature',
#    columns='meta',
#    values='corr'
#)

df_pval_pivot = df_hf_clinical_corr.pivot(
    index='feature',
    columns='meta',
    values='p_value'
)

In [1433]:
df_pval_pivot[df_pval_pivot < 0.05].count()

meta
GDS                           70
MOCA                          66
age                           43
attention z-score             61
education length              53
education type                53
executive function z-score    24
memory z-score                11
visuo-spatial z-score         69
dtype: int64

# FDR correction

In [1434]:

import numpy as np
import pandas as pd
from statsmodels.stats.multitest import multipletests

def fdr_correction_matrix(df_pvals: pd.DataFrame, alpha: float = 0.05, method: str = "fdr_bh"):
    df = df_pvals.copy()

    # Only numeric columns (skip "feature")
    numeric_cols = df.select_dtypes(include=[float, int]).columns
    arr = df[numeric_cols].to_numpy(dtype=float)

    # Mask NaNs
    mask_na = np.isnan(arr)

    # Take only valid p-values (flatten)
    pvals_flat = arr[~mask_na]

    # FDR
    reject, pvals_corr, _, _ = multipletests(pvals_flat, alpha=alpha, method=method)

    # Prepare output arrays
    arr_fdr = np.full_like(arr, np.nan, dtype=float)
    arr_sig = np.zeros_like(arr, dtype=bool)

    # Fill corrected values
    arr_fdr[~mask_na] = pvals_corr
    arr_sig[~mask_na] = reject

    # Back to DataFrames
    df_fdr = df.copy()
    df_sig = df.copy()

    df_fdr[numeric_cols] = arr_fdr
    df_sig[numeric_cols] = arr_sig

    return df_fdr, df_sig

In [1435]:

df_fdr, df_sig = fdr_correction_matrix(df_pval_pivot, alpha=0.05)

#Show significant (feature, metadata) pairs
significant_pairs = (
    df_sig
         .iloc[:, 1:]         # skip the 'feature' column
         .stack()             # long format
         .loc[lambda s: s]    # keep only True
         .index
         .to_frame(name=["feature", "metadata"])
)
##
significant_pairs

                                                                                                                    feature  \
feature                                            meta
Unnamed: 0                                         MOCA                                                          Unnamed: 0
                                                   visuo-spatial z-score                                         Unnamed: 0
w.cz.fnusa.17_1_slope of velocity (in-air)         visuo-spatial z-score         w.cz.fnusa.17_1_slope of velocity (in-air)
w.cz.fnusa.17_1_slope of vertical velocity (in-... visuo-spatial z-score  w.cz.fnusa.17_1_slope of vertical velocity (in...

                                                                                       metadata
feature                                            meta
Unnamed: 0                                         MOCA                                    MOCA
                                                   visuo-spatial z-score  visuo-spatial z-score
w.cz.fnusa.17_1_slope of velocity (in-air)         visuo-spatial z-score  visuo-spatial z-score
w.cz.fnusa.17_1_slope of vertical velocity (in-... visuo-spatial z-score  visuo-spatial z-score

In [1436]:

df_after_fdr = df_fdr[df_sig]

In [1437]:

df_after_fdr.dropna(how='all', inplace=True)
df_after_fdr

meta,GDS,MOCA,age,attention z-score,education length,education type,executive function z-score,memory z-score,visuo-spatial z-score
feature,,,,,,,,,
Unnamed: 0,0.000039,0.044494,NaN,NaN,NaN,NaN,NaN,NaN,0.032332
w.cz.fnusa.16_1_95th percentile of acceleration (on-surface),0.036790,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.16_1_95th percentile of horizontal acceleration (on-surface),0.044494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.16_1_95th percentile of velocity (on-surface),0.032332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.16_1_95th percentile of vertical acceleration (on-surface),0.040616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.16_1_95th percentile of vertical velocity (on-surface),0.036790,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.17_1_95th percentile of acceleration (on-surface),0.032332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.17_1_95th percentile of angular velocity (on-surface),0.044494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.17_1_95th percentile of horizontal acceleration (on-surface),0.036790,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.17_1_95th percentile of velocity (on-surface),0.040616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.17_1_95th percentile of vertical acceleration (on-surface),0.044494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.17_1_95th percentile of vertical velocity (on-surface),0.040616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.17_1_median of horizontal velocity (on-surface),0.044494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.17_1_slope of velocity (in-air),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.032332
w.cz.fnusa.17_1_slope of vertical velocity (in-air),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.044494
w.cz.fnusa.19_1_95th percentile of angular velocity (on-surface),0.044160,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.19_1_95th percentile of horizontal velocity (on-surface),0.044494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Task-wise Dataframe dictionaries creation

- temp_emb_df_complet_lbl_2
- freq_emb_df_complet_lbl_2
- comb_emb_df_complet_lbl_2
- hf_emb_df_complet_lbl_2

In [1438]:
import re

_TASK_RE_CACHE = {}

def task_wise_df_creation(df, task_name):
    # compile once per task to avoid recompilation on every call
    if task_name not in _TASK_RE_CACHE:
        pattern = rf"(?<!\d){re.escape(task_name)}(?!\d)"
        _TASK_RE_CACHE[task_name] = re.compile(pattern)
    mask = df['file_path'].str.contains(_TASK_RE_CACHE[task_name])
    return df[mask].reset_index(drop=True)

In [1439]:

task_list = [ '9_1', '15_1', '17_1', '19_1']

task_freq_dfs = {task: task_wise_df_creation(freq_emb_df_complet_lbl, task) for task in task_list}
task_temp_dfs = {task: task_wise_df_creation(temp_emb_df_complet_lbl, task) for task in task_list}
task_comb_dfs = {task: task_wise_df_creation(comb_emb_df_complet_lbl, task) for task in task_list}

In [1440]:
task_freq_dfs.get('19_1')

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_375,emb_376,emb_377,emb_378,emb_379,emb_380,emb_381,emb_382,emb_383,diagnosis
0,1,COBEN-WTABLET-AS-HCD05,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.025234,0.044658,-0.009985,0.059004,0.047672,-0.002233,0.009344,...,0.040955,-0.017115,0.088644,-0.007014,0.035387,-0.014119,-0.013487,0.033013,-0.017306,0.0
1,1,COBEN-WTABLET-BB-PD08,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.024688,0.044020,-0.011453,0.058312,0.048458,-0.002063,0.007827,...,0.039469,-0.016422,0.089392,-0.006976,0.037800,-0.015683,-0.014417,0.032570,-0.016883,4.0
2,1,COBEN-WTABLET-DM-AD15,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.023702,0.045272,-0.009258,0.055696,0.050931,-0.001124,0.010300,...,0.038831,-0.017001,0.084592,-0.005806,0.035355,-0.015312,-0.014527,0.034473,-0.016139,2.0
3,1,COBEN-WTABLET-DM-PD17,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.023332,0.046235,-0.012230,0.057625,0.049248,0.000590,0.008439,...,0.041855,-0.016114,0.087540,-0.005224,0.036952,-0.014927,-0.016284,0.036253,-0.016281,4.0
4,1,COBEN-WTABLET-DS-HC36,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.025088,0.042088,-0.005406,0.056024,0.050460,-0.007326,0.012778,...,0.037596,-0.018475,0.084470,-0.010858,0.031069,-0.015011,-0.011322,0.026292,-0.018325,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
251,1,pre-LBD-94#2,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.025037,0.043282,-0.010769,0.057130,0.048627,-0.002043,0.008821,...,0.039250,-0.016778,0.088408,-0.007602,0.036532,-0.015635,-0.014940,0.031837,-0.017821,1.0
252,1,pre-LBD-96#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.025337,0.045688,-0.009079,0.059209,0.047094,-0.002675,0.010767,...,0.041326,-0.017593,0.087716,-0.007099,0.032943,-0.013806,-0.013249,0.033177,-0.018244,1.0
253,1,pre-LBD-97#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.024352,0.045682,-0.011283,0.057876,0.047752,0.001140,0.007783,...,0.041632,-0.015559,0.088350,-0.005173,0.036674,-0.012681,-0.016115,0.036967,-0.016982,1.0
254,1,pre-LBD-98#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.024986,0.045938,-0.008785,0.059049,0.046561,-0.002105,0.012714,...,0.044116,-0.017637,0.086476,-0.008090,0.031446,-0.013032,-0.014446,0.033572,-0.019951,1.0
255,1,pre-LBD-99#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.023472,0.045858,-0.012113,0.058663,0.048171,0.001104,0.007370,...,0.042343,-0.016178,0.089131,-0.005532,0.037060,-0.012662,-0.015977,0.036766,-0.017308,1.0

In [1441]:
import re

task_list = [ '9_1', '15_1', '17_1', '19_1']

task_hf_dfs = {
    task: hf_emb_df_complet_lbl.loc[
        :,
        hf_emb_df_complet_lbl.columns.astype(str).str.contains(
            rf"(?<!\d){re.escape(task)}(?!\d)", case=False
        )
        | hf_emb_df_complet_lbl.columns.isin(['diagnosis', 'ID'])
    ].copy()
    for task in task_list
}

## MCI-LBD vs HC

In [1442]:

task_freq_dfs_lbd_hc = {k: v[~v["diagnosis"].isin([1, 2, 4])].reset_index(drop=True) for k, v in task_freq_dfs.items()}
task_temp_dfs_lbd_hc = {k: v[~v["diagnosis"].isin([1, 2, 4])].reset_index(drop=True) for k, v in task_temp_dfs.items()}
task_comb_dfs_lbd_hc = {k: v[~v["diagnosis"].isin([1, 2, 4])].reset_index(drop=True) for k, v in task_comb_dfs.items()}
task_hf_dfs_lbd_hc = {k: v[~v["diagnosis"].isin([1, 2, 4])].reset_index(drop=True) for k, v in task_hf_dfs.items()}

## MCI-AD vs HC

In [1443]:
task_freq_dfs_ad_hc = {k: v[~v["diagnosis"].isin([1, 3, 4])].reset_index(drop=True) for k, v in task_freq_dfs.items()}
task_temp_dfs_ad_hc = {k: v[~v["diagnosis"].isin([1, 3, 4])].reset_index(drop=True) for k, v in task_temp_dfs.items()}
task_comb_dfs_ad_hc = {k: v[~v["diagnosis"].isin([1, 3, 4])].reset_index(drop=True) for k, v in task_comb_dfs.items()}
task_hf_dfs_ad_hc = {k: v[~v["diagnosis"].isin([1, 3, 4])].reset_index(drop=True) for k, v in task_hf_dfs.items()}

## MCI-PD vs HC

In [1444]:

task_freq_dfs_pd_hc = {k: v[~v["diagnosis"].isin([1, 3, 2])].reset_index(drop=True) for k, v in task_freq_dfs.items()}
task_temp_dfs_pd_hc = {k: v[~v["diagnosis"].isin([1, 3, 2])].reset_index(drop=True) for k, v in task_temp_dfs.items()}
task_comb_dfs_pd_hc = {k: v[~v["diagnosis"].isin([1, 3, 2])].reset_index(drop=True) for k, v in task_comb_dfs.items()}
task_hf_dfs_pd_hc = {k: v[~v["diagnosis"].isin([1, 3, 2])].reset_index(drop=True) for k, v in task_hf_dfs.items()}

## MCI-LBD vs MCI-AD

In [1445]:

task_freq_dfs_ad_lbd = {k: v[~v["diagnosis"].isin([1, 0, 4])].reset_index(drop=True) for k, v in task_freq_dfs.items()}
task_temp_dfs_ad_lbd = {k: v[~v["diagnosis"].isin([1, 0, 4])].reset_index(drop=True) for k, v in task_temp_dfs.items()}
task_comb_dfs_ad_lbd = {k: v[~v["diagnosis"].isin([1, 0, 4])].reset_index(drop=True) for k, v in task_comb_dfs.items()}
task_hf_dfs_ad_lbd = {k: v[~v["diagnosis"].isin([1, 0, 4])].reset_index(drop=True) for k, v in task_hf_dfs.items()}

In [1446]:
task_freq_dfs_lbd_hc = {k: v.drop(columns=['label', 'file_path']) for k, v in task_freq_dfs_lbd_hc.items()}
task_temp_dfs_lbd_hc = {k: v.drop(columns=['label', 'file_path']) for k, v in task_temp_dfs_lbd_hc.items()}
task_comb_dfs_lbd_hc = {k: v.drop(columns=['label', 'file_path']) for k, v in task_comb_dfs_lbd_hc.items()}

In [1447]:

task_freq_dfs_ad_hc = {k: v.drop(columns=['label', 'file_path']) for k, v in task_freq_dfs_ad_hc.items()}
task_temp_dfs_ad_hc = {k: v.drop(columns=['label', 'file_path']) for k, v in task_temp_dfs_ad_hc.items()}
task_comb_dfs_ad_hc = {k: v.drop(columns=['label', 'file_path']) for k, v in task_comb_dfs_ad_hc.items()}

In [1448]:
task_freq_dfs_pd_hc = {k: v.drop(columns=['label', 'file_path']) for k, v in task_freq_dfs_pd_hc.items()}
task_temp_dfs_pd_hc = {k: v.drop(columns=['label', 'file_path']) for k, v in task_temp_dfs_pd_hc.items()}
task_comb_dfs_pd_hc = {k: v.drop(columns=['label', 'file_path']) for k, v in task_comb_dfs_pd_hc.items()}

In [1449]:

task_freq_dfs_ad_lbd = {k: v.drop(columns=['label', 'file_path']) for k, v in task_freq_dfs_ad_lbd.items()}
task_temp_dfs_ad_lbd = {k: v.drop(columns=['label', 'file_path']) for k, v in task_temp_dfs_ad_lbd.items()}
task_comb_dfs_ad_lbd = {k: v.drop(columns=['label', 'file_path']) for k, v in task_comb_dfs_ad_lbd.items()}

In [1450]:
for dfs in (task_freq_dfs_lbd_hc, task_temp_dfs_lbd_hc, task_comb_dfs_lbd_hc, task_hf_dfs_lbd_hc):
    
    for k, v in dfs.items():
        if "diagnosis" in v.columns:
            v["diagnosis"] = v["diagnosis"].replace({3.0: 1, 0.0: 0})

C:\Users\tenNovy\AppData\Local\Temp\ipykernel_1420\2570176340.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  v["diagnosis"] = v["diagnosis"].replace({3.0: 1, 0.0: 0})

In [1451]:
for dfs in (task_freq_dfs_ad_hc, task_temp_dfs_ad_hc, task_comb_dfs_ad_hc, task_hf_dfs_ad_hc):
    
    for k, v in dfs.items():
        if "diagnosis" in v.columns:
            v["diagnosis"] = v["diagnosis"].replace({2.0: 1, 0.0: 0})

C:\Users\tenNovy\AppData\Local\Temp\ipykernel_1420\856415710.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  v["diagnosis"] = v["diagnosis"].replace({2.0: 1, 0.0: 0})

In [1452]:

for dfs in (task_freq_dfs_ad_lbd, task_temp_dfs_ad_lbd, task_comb_dfs_ad_lbd, task_hf_dfs_ad_lbd):
    
    for k, v in dfs.items():
        if "diagnosis" in v.columns:
            v["diagnosis"] = v["diagnosis"].replace({3.0: 1, 2.0: 0})

C:\Users\tenNovy\AppData\Local\Temp\ipykernel_1420\676543069.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  v["diagnosis"] = v["diagnosis"].replace({3.0: 1, 2.0: 0})

In [1453]:
for dfs in (task_freq_dfs_pd_hc, task_temp_dfs_pd_hc, task_comb_dfs_pd_hc, task_hf_dfs_pd_hc):
    
    for k, v in dfs.items():
        if "diagnosis" in v.columns:
            v["diagnosis"] = v["diagnosis"].replace({4.0: 1, 0.0: 0})

C:\Users\tenNovy\AppData\Local\Temp\ipykernel_1420\1503130897.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  v["diagnosis"] = v["diagnosis"].replace({4.0: 1, 0.0: 0})

In [1454]:
task_freq_dfs_ad_hc.get("1_1")

In [1455]:

def miss_val_clean(df, percent_threshold=0.8):
    """
    Cleans the DataFrame by removing columns with more than the specified percentage of missing values.
    
    Parameters
    ----------
    df : pd.DataFrame
        The input DataFrame to be cleaned.
    percent_threshold : float
        The maximum allowed percentage of missing values in a column (between 0 and 1).
        
    Returns
    -------
    pd.DataFrame
        The cleaned DataFrame with columns exceeding the missing value threshold removed.
    """
    df_cleaned = df.copy()
    df_cleaned = df_cleaned.loc[:, df_cleaned.isnull().mean() <= percent_threshold]
    
    cols_to_convert = df_cleaned.columns[1:-1]

    df_cleaned[cols_to_convert] = (
        df_cleaned[cols_to_convert]
        .apply(lambda col: pd.to_numeric(col.astype(str).str.replace(',', '.'), errors='coerce'))
    )

    df_cleaned = df_cleaned.fillna(df_cleaned.mean(numeric_only=True))
    return df_cleaned

In [1456]:

task_hf_dfs_clean_lbd_hc = {k: miss_val_clean(v, percent_threshold=0.8) for k, v in task_hf_dfs_lbd_hc.items()}
task_hf_dfs_clean_ad_hc = {k: miss_val_clean(v, percent_threshold=0.8) for k, v in task_hf_dfs_ad_hc.items()}
task_hf_dfs_clean_ad_lbd = {k: miss_val_clean(v, percent_threshold=0.8) for k, v in task_hf_dfs_ad_lbd.items()}
task_hf_dfs_clean_pd_hc = {k: miss_val_clean(v, percent_threshold=0.8) for k, v in task_hf_dfs_pd_hc.items()}

In [1457]:
task_temp_dfs_lbd_hc.get('19_1')

,subject,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,emb_7,emb_8,...,emb_375,emb_376,emb_377,emb_378,emb_379,emb_380,emb_381,emb_382,emb_383,diagnosis
0,COBEN-WTABLET-AS-HCD05,0.044137,0.033558,-0.009980,0.031295,-0.007999,-0.008453,-0.069193,-0.039807,-0.050593,...,-0.038257,0.076220,0.029331,0.023654,-0.035232,-0.002878,0.065463,0.000019,-0.006608,0.0
1,COBEN-WTABLET-DS-HC36,0.034489,0.037964,0.003997,0.031308,-0.002415,-0.009024,-0.078374,-0.034994,-0.045366,...,-0.031089,0.074446,0.033181,0.028262,-0.014137,0.009263,0.067702,-0.005802,-0.015393,0.0
2,COBEN-WTABLET-EH-HC35,0.051136,0.032852,-0.015713,0.023723,-0.002616,-0.011697,-0.076546,-0.047947,-0.032787,...,-0.044151,0.075471,0.016568,0.011069,-0.041066,0.001635,0.057435,-0.007803,-0.002143,0.0
3,COBEN-WTABLET-FG-HC38,0.047692,0.038489,-0.005572,0.029724,-0.011133,-0.003979,-0.073912,-0.039604,-0.044156,...,-0.037085,0.077435,0.025195,0.023164,-0.034982,-0.006782,0.066221,-0.007095,-0.004949,0.0
4,COBEN-WTABLET-HJ-HC21,0.041262,0.036884,-0.009382,0.027450,-0.008000,-0.012799,-0.077835,-0.040124,-0.046470,...,-0.040431,0.074910,0.036196,0.019268,-0.038466,0.003476,0.060327,-0.001568,0.003168,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,pre-LBD-55#1,0.049228,0.026564,-0.017499,0.013733,-0.012341,-0.015982,-0.064792,-0.053930,-0.025792,...,-0.043439,0.079570,0.013259,0.012788,-0.046558,-0.017028,0.047610,-0.004162,-0.007690,1.0
76,pre-LBD-56#1,0.039396,0.038528,-0.007188,0.028694,-0.004399,-0.008700,-0.075656,-0.037884,-0.044863,...,-0.038566,0.074768,0.030143,0.022276,-0.031223,0.002259,0.066468,-0.001591,-0.005065,1.0
77,pre-LBD-57#1,0.042064,0.030457,-0.011426,0.024247,-0.011918,-0.011414,-0.069730,-0.047618,-0.033913,...,-0.039286,0.082370,0.022495,0.023492,-0.044708,-0.005118,0.060154,0.002665,-0.001658,1.0
78,pre-LBD-58#1,0.049798,0.037552,-0.017068,0.024141,-0.002132,-0.009525,-0.076057,-0.045164,-0.039771,...,-0.044604,0.073156,0.021164,0.012106,-0.039805,0.003914,0.061573,-0.009695,-0.002529,1.0
79,pre-LBD-59#1,0.047183,0.032963,-0.017407,0.016141,-0.011077,-0.013201,-0.076177,-0.051287,-0.023722,...,-0.043026,0.075884,0.016293,0.005327,-0.045433,-0.007430,0.049516,-0.009370,-0.008692,1.0

In [1458]:

# Use this one 
def merge_on_subject_agg_right(df1, df2):
    df1 = df1.copy(); df2 = df2.copy()
    if 'subject' not in df1 and 'ID' in df1: df1 = df1.rename(columns={'ID':'subject'})
    if 'subject' not in df2 and 'ID' in df2: df2 = df2.rename(columns={'ID':'subject'})
    num_cols = df2.select_dtypes('number').columns.tolist()
    agg = {c:'first' for c in df2.columns if c not in num_cols and c!='subject'}
    agg.update({c:'mean' for c in num_cols})
    df2 = df2.groupby('subject', as_index=False).agg(agg)
    return pd.merge(df1, df2, on='subject', how='inner', validate='many_to_one', sort=False)

### MCI-LBD vs HC

In [1459]:
task_hf_compensated_freq_emb_lbl_lbd_hc = {
    k: merge_on_subject_agg_right(task_freq_dfs_lbd_hc[k], task_hf_dfs_clean_lbd_hc[k])
    for k in task_freq_dfs_lbd_hc.keys() & task_hf_dfs_clean_lbd_hc.keys()
}

In [1460]:

task_hf_compensated_temp_emb_lbl_lbd_hc = {
    k: merge_on_subject_agg_right(task_temp_dfs_lbd_hc[k], task_hf_dfs_clean_lbd_hc[k])
    for k in task_temp_dfs_lbd_hc.keys() & task_hf_dfs_clean_lbd_hc.keys()
}

In [1461]:

task_hf_compensated_comb_emb_lbl_lbd_hc = {
    k: merge_on_subject_agg_right(task_comb_dfs_lbd_hc[k], task_hf_dfs_clean_lbd_hc[k])
    for k in task_comb_dfs_lbd_hc.keys() & task_hf_dfs_clean_lbd_hc.keys()
}

In [1462]:
task_hf_comb_emb_lbl_lbd_hc = {
    k: merge_on_subject_agg_right(task_comb_dfs_lbd_hc[k], task_hf_dfs_clean_lbd_hc[k])
    for k in task_comb_dfs_lbd_hc.keys() & task_hf_dfs_clean_lbd_hc.keys()
}

In [1463]:
task_hf_freq_emb_lbl_lbd_hc = {
    k: merge_on_subject_agg_right(task_freq_dfs_lbd_hc[k], task_hf_dfs_clean_lbd_hc[k])
    for k in task_freq_dfs_lbd_hc.keys() & task_hf_dfs_clean_lbd_hc.keys()
}

In [1464]:
task_hf_temp_emb_lbl_lbd_hc = {
    k: merge_on_subject_agg_right(task_temp_dfs_lbd_hc[k], task_hf_dfs_clean_lbd_hc[k])
    for k in task_temp_dfs_lbd_hc.keys() & task_hf_dfs_clean_lbd_hc.keys()
}

### MCI-AD vs HC

In [1465]:
### MCI-AD vs HC
task_hf_compensated_freq_emb_lbl_ad_hc = {
    k: merge_on_subject_agg_right(task_freq_dfs_ad_hc[k], task_hf_dfs_clean_ad_hc[k])
    for k in task_freq_dfs_ad_hc.keys() & task_hf_dfs_clean_ad_hc.keys()
}

task_hf_compensated_temp_emb_lbl_ad_hc = {
    k: merge_on_subject_agg_right(task_temp_dfs_ad_hc[k], task_hf_dfs_clean_ad_hc[k])
    for k in task_temp_dfs_ad_hc.keys() & task_hf_dfs_clean_ad_hc.keys()
}

task_hf_compensated_comb_emb_lbl_ad_hc = {
    k: merge_on_subject_agg_right(task_comb_dfs_ad_hc[k], task_hf_dfs_clean_ad_hc[k])
    for k in task_comb_dfs_ad_hc.keys() & task_hf_dfs_clean_ad_hc.keys()
}
task_hf_comb_emb_lbl_ad_hc= {
    k: merge_on_subject_agg_right(task_comb_dfs_ad_hc[k], task_hf_dfs_clean_ad_hc[k])
    for k in task_comb_dfs_ad_hc.keys() & task_hf_dfs_clean_ad_hc.keys()
}
task_hf_freq_emb_lbl_ad_hc = {
    k: merge_on_subject_agg_right(task_freq_dfs_ad_hc[k], task_hf_dfs_clean_ad_hc[k])
    for k in task_freq_dfs_ad_hc.keys() & task_hf_dfs_clean_ad_hc.keys()
}
task_hf_temp_emb_lbl_ad_hc = {
    k: merge_on_subject_agg_right(task_temp_dfs_ad_hc[k], task_hf_dfs_clean_ad_hc[k])
    for k in task_temp_dfs_ad_hc.keys() & task_hf_dfs_clean_ad_hc.keys()
}

### MCI-LBD vs MCI-AD

In [1466]:
### MCI-LBD vs MCI-LBD
task_hf_compensated_freq_emb_lbl_ad_lbd = {
    k: merge_on_subject_agg_right(task_freq_dfs_ad_lbd[k], task_hf_dfs_clean_ad_lbd[k])
    for k in task_freq_dfs_ad_lbd.keys() & task_hf_dfs_clean_ad_lbd.keys()
}

task_hf_compensated_temp_emb_lbl_ad_lbd = {
    k: merge_on_subject_agg_right(task_temp_dfs_ad_lbd[k], task_hf_dfs_clean_ad_lbd[k])
    for k in task_temp_dfs_ad_lbd.keys() & task_hf_dfs_clean_ad_lbd.keys()
}

task_hf_compensated_comb_emb_lbl_ad_lbd = {
    k: merge_on_subject_agg_right(task_comb_dfs_ad_lbd[k], task_hf_dfs_clean_ad_lbd[k])
    for k in task_comb_dfs_ad_lbd.keys() & task_hf_dfs_clean_ad_lbd.keys()
}
task_hf_comb_emb_lbl_ad_lbd= {
    k: merge_on_subject_agg_right(task_comb_dfs_ad_lbd[k], task_hf_dfs_clean_ad_lbd[k])
    for k in task_comb_dfs_ad_lbd.keys() & task_hf_dfs_clean_ad_lbd.keys()
}
task_hf_freq_emb_lbl_ad_lbd = {
    k: merge_on_subject_agg_right(task_freq_dfs_ad_lbd[k], task_hf_dfs_clean_ad_lbd[k])
    for k in task_freq_dfs_ad_lbd.keys() & task_hf_dfs_clean_ad_lbd.keys()
}
task_hf_temp_emb_lbl_ad_lbd = {
    k: merge_on_subject_agg_right(task_temp_dfs_ad_lbd[k], task_hf_dfs_clean_ad_lbd[k])
    for k in task_temp_dfs_ad_lbd.keys() & task_hf_dfs_clean_ad_lbd.keys()
}

### PD vs HC

In [1467]:

### MCI-AD vs HC
task_hf_compensated_freq_emb_lbl_pd_hc = {
    k: merge_on_subject_agg_right(task_freq_dfs_pd_hc[k], task_hf_dfs_clean_pd_hc[k])
    for k in task_freq_dfs_pd_hc.keys() & task_hf_dfs_clean_pd_hc.keys()
}

task_hf_compensated_temp_emb_lbl_pd_hc = {
    k: merge_on_subject_agg_right(task_temp_dfs_pd_hc[k], task_hf_dfs_clean_pd_hc[k])
    for k in task_temp_dfs_pd_hc.keys() & task_hf_dfs_clean_pd_hc.keys()
}

task_hf_compensated_comb_emb_lbl_pd_hc = {
    k: merge_on_subject_agg_right(task_comb_dfs_pd_hc[k], task_hf_dfs_clean_pd_hc[k])
    for k in task_comb_dfs_pd_hc.keys() & task_hf_dfs_clean_pd_hc.keys()
}
task_hf_comp_emb_lbl_pd_hc= {
    k: merge_on_subject_agg_right(task_comb_dfs_pd_hc[k], task_hf_dfs_clean_pd_hc[k])
    for k in task_comb_dfs_pd_hc.keys() & task_hf_dfs_clean_pd_hc.keys()
}
task_hf_freq_emb_lbl_pd_hc = {
    k: merge_on_subject_agg_right(task_freq_dfs_pd_hc[k], task_hf_dfs_clean_pd_hc[k])
    for k in task_freq_dfs_pd_hc.keys() & task_hf_dfs_clean_pd_hc.keys()
}
task_hf_temp_emb_lbl_pd_hc = {
    k: merge_on_subject_agg_right(task_temp_dfs_pd_hc[k], task_hf_dfs_clean_pd_hc[k])
    for k in task_temp_dfs_pd_hc.keys() & task_hf_dfs_clean_pd_hc.keys()
}

In [1468]:
def x_y_split(df, split_param):
    if split_param is None or split_param == "diagnosis_y":
        #embedding_cols = df[1:-1]
        X = df.iloc[:,1:-2].values
        y = df["diagnosis_y"].values
    elif split_param != None: 
        embedding_cols = [c for c in df.columns if c.startswith(split_param)]
        #X = df[embedding_cols].values
        X = df.iloc[:,1:-2].values
        y = df["diagnosis"].values
    
    return X, y

In [1469]:
def remove_leaking_labels(df, label_string = 'diagnosis_x'):
    df_cleaned = df.copy()
    df_cleaned = df_cleaned.drop(label_string, axis = 1)
    return df_cleaned

In [1470]:
task_hf_compensated_freq_emb_lbl_ad_hc = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_freq_emb_lbl_ad_hc.items()}
task_hf_compensated_temp_emb_lbl_ad_hc = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_temp_emb_lbl_ad_hc.items()}
task_hf_compensated_comb_emb_lbl_ad_hc = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_comb_emb_lbl_ad_hc.items()}

task_hf_compensated_freq_emb_lbl_lbd_hc = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_freq_emb_lbl_lbd_hc.items()}
task_hf_compensated_temp_emb_lbl_lbd_hc = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_temp_emb_lbl_lbd_hc.items()}
task_hf_compensated_comb_emb_lbl_lbd_hc = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_comb_emb_lbl_lbd_hc.items()}


task_hf_compensated_freq_emb_lbl_ad_lbd = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_freq_emb_lbl_ad_lbd.items()}
task_hf_compensated_temp_emb_lbl_ad_lbd = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_temp_emb_lbl_ad_lbd.items()}
task_hf_compensated_comb_emb_lbl_ad_lbd = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_comb_emb_lbl_ad_lbd.items()}

task_hf_compensated_freq_emb_lbl_pd_hc = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_freq_emb_lbl_pd_hc.items()}
task_hf_compensated_temp_emb_lbl_pd_hc = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_temp_emb_lbl_pd_hc.items()}
task_hf_compensated_comb_emb_lbl_pd_hc = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_comb_emb_lbl_pd_hc.items()}

In [1471]:
def leaking_sanity_test(df, label_string='diagnosis_x'):
    if label_string in df.columns:
        print(f"Leaking label '{label_string}' found in DataFrame columns.")
    else:
        print(f"No leaking label '{label_string}' found in DataFrame columns.")

In [1472]:
{k: leaking_sanity_test(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_freq_emb_lbl_ad_hc.items()}
{k: leaking_sanity_test(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_temp_emb_lbl_ad_hc.items()}
{k: leaking_sanity_test(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_comb_emb_lbl_ad_hc.items()}

{k: leaking_sanity_test(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_freq_emb_lbl_lbd_hc.items()}
{k: leaking_sanity_test(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_temp_emb_lbl_lbd_hc.items()}
{k: leaking_sanity_test(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_comb_emb_lbl_lbd_hc.items()}


{k: leaking_sanity_test(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_freq_emb_lbl_ad_lbd.items()}
{k: leaking_sanity_test(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_temp_emb_lbl_ad_lbd.items()}
{k: leaking_sanity_test(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_comb_emb_lbl_ad_lbd.items()}

No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.

{'9_1': None, '15_1': None, '19_1': None, '17_1': None}

# OPTUNA + XGBoost

In [1473]:

#import os, json
#import numpy as np
#import pandas as pd
#import optuna, xgboost as xgb
#from typing import Dict, Tuple
#from sklearn.model_selection import StratifiedKFold, train_test_split
#from sklearn.model_selection import LeaveOneOut
#from sklearn.metrics import (
    #balanced_accuracy_score,
    #roc_auc_score,
    #confusion_matrix,
    #classification_report,
    #RocCurveDisplay,
    #ConfusionMatrixDisplay,
    #matthews_corrcoef
#)
#
## def x_y_split(df): ...  # your splitter (must return X, y)
#def _safe_feature_names(X, fallback_dim=None):
    #if hasattr(X, "columns"):
        #return list(X.columns)
    #if hasattr(X, "feature_names_in_"):
        #return list(X.feature_names_in_)
    #if fallback_dim is None and hasattr(X, "shape"):
        #fallback_dim = X.shape[1]
    #return [f"f{i}" for i in range(int(fallback_dim or 0))]
#
#def _plot_feature_importance(model, feature_names, out_dir: str):
    #"""Save multiple feature-importance views from XGBoost."""
    #import matplotlib.pyplot as plt
    #import numpy as np
    #from collections import defaultdict
    #os.makedirs(out_dir, exist_ok=True)
#
    ## 1) sklearn API importances (gain-based)
    #try:
        #importances = getattr(model, "feature_importances_", None)
        #if importances is not None and len(importances) == len(feature_names):
            #order = np.argsort(importances)[::-1]
            #top_idx = order[:50]  # limit to top-50 for readability
            #plt.figure()
            #plt.barh([feature_names[i] for i in top_idx][::-1], importances[top_idx][::-1])
            #plt.title("XGB feature_importances_ (top-50)")
            #plt.tight_layout()
            #plt.savefig(os.path.join(out_dir, "feature_importances_sklearn.png"), dpi=200, bbox_inches="tight")
            #plt.close()
    #except Exception:
        #pass
#
    ## 2) Booster importances (weight/gain/cover)
    #try:
        #booster = model.get_booster()
        #for typ in ["weight", "gain", "cover", "total_gain", "total_cover"]:
            #score_dict = booster.get_score(importance_type=typ)
            #if not score_dict:
                #continue
            ## Map 'f0'.. to friendly names
            #vals = []
            #names = []
            #for k, v in score_dict.items():
                #if k.startswith("f"):
                    #idx = int(k[1:])
                    #if 0 <= idx < len(feature_names):
                        #names.append(feature_names[idx])
                    #else:
                        #names.append(k)
                #else:
                    #names.append(k)
                #vals.append(v)
            #order = np.argsort(vals)[::-1]
            #top = min(50, len(order))
            #plt.figure()
            #plt.barh([names[i] for i in order[:top]][::-1], np.array(vals)[order[:top]][::-1])
            #plt.title(f"Booster feature importance — {typ} (top-{top})")
            #plt.tight_layout()
            #plt.savefig(os.path.join(out_dir, f"feature_importances_{typ}.png"), dpi=200, bbox_inches="tight")
            #plt.close()
    #except Exception:
        #pass
#
#def _save_shap_summaries(model, X_ref, feature_names, out_dir: str, max_display: int = 30, sample: int = 1000):
    #"""
    #Compute SHAP (TreeExplainer) and save bar + beeswarm plots.
    #Skips silently if shap not installed or backend issues arise.
    #"""
    #try:
        #import shap
        #import numpy as np
        #import matplotlib.pyplot as plt
    #except Exception:
        #return
#
    #try:
        ## Downsample for speed
        #if hasattr(X_ref, "iloc"):
            #X_use = X_ref.sample(min(sample, len(X_ref)), random_state=0)
            #X_np = X_use.values
        #else:
            #X_np = X_ref
            #if X_np.shape[0] > sample:
                #rng = np.random.default_rng(0)
                #idx = rng.choice(X_np.shape[0], size=sample, replace=False)
                #X_np = X_np[idx]
#
        #explainer = shap.TreeExplainer(model)
        #shap_values = explainer.shap_values(X_np)
#
        ## Handle binary classification: shap returns array (n, p)
        #if isinstance(shap_values, list) and len(shap_values) == 2:
            ## pick positive class
            #sv = shap_values[1]
        #else:
            #sv = shap_values
#
        ## Bar plot (mean |SHAP|)
        #try:
            #plt.figure()
            #shap.summary_plot(sv, X_np, feature_names=feature_names, plot_type="bar", show=False, max_display=max_display)
            #plt.tight_layout()
            #plt.savefig(os.path.join(out_dir, "shap_summary_bar.png"), dpi=200, bbox_inches="tight")
            #plt.close()
        #except Exception:
            #pass
#
        ## Beeswarm
        #try:
            #plt.figure()
            #shap.summary_plot(sv, X_np, feature_names=feature_names, show=False, max_display=max_display)
            #plt.tight_layout()
            #plt.savefig(os.path.join(out_dir, "shap_summary_beeswarm.png"), dpi=200, bbox_inches="tight")
            #plt.close()
        #except Exception:
            #pass
    #except Exception:
        ## Any SHAP error -> skip silently
        #return
#
#def _pick_device():
    #try:
        #_ = xgb.core.get_cuda_compute_capabilities()
        #return {"tree_method": "hist", "device": "cuda"}
    #except Exception:
        #return {"tree_method": "hist", "device": "cpu"}
#
#def _ensure_dir(path: str):
    #os.makedirs(path, exist_ok=True)
#
#def _save_json(d: dict, path: str):
    #with open(path, "w", encoding="utf-8") as f:
        #json.dump(d, f, indent=2, ensure_ascii=False)
#
#def make_xgb_objective(X, y, scoring: str = "balanced_accuracy", n_splits: int = 5, random_state: int = 42):
    #if scoring == "balanced_accuracy":
        #from sklearn.metrics import balanced_accuracy_score as metric_fn
        #needs_proba = False
        #eval_metric = "logloss"
    #elif scoring == "roc_auc":
        #from sklearn.metrics import roc_auc_score as metric_fn
        #needs_proba = True
        #eval_metric = "auc"
    #else:
        #raise ValueError("scoring must be 'balanced_accuracy' or 'roc_auc'")
#
    #folds = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    ##folds = LeaveOneOut()
    #device_kwargs = _pick_device()
#
    #pos_ratio = float(np.mean(y))
    #scale_pos_weight = ((1.0 - pos_ratio) / pos_ratio) if 0 < pos_ratio < 1 else 1.0
#
    #def objective(trial: optuna.Trial) -> float:
        #params = {
            #"max_depth": trial.suggest_int("max_depth", 3, 10),
            #"learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
            #"n_estimators": trial.suggest_int("n_estimators", 200, 1500),
            #"subsample": trial.suggest_float("subsample", 0.5, 1.0),
            #"colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
            #"min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
            #"gamma": trial.suggest_float("gamma", 0.0, 5.0),
            #"reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
            #"reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
            #"max_delta_step": trial.suggest_int("max_delta_step", 0, 10),
            #"objective": "binary:logistic",
            #"eval_metric": eval_metric,
            #"n_jobs": 1,  # keep each trial single-threaded
            #"scale_pos_weight": scale_pos_weight,
            #**device_kwargs,
        #}
#
        #scores = []
        #for tr_idx, va_idx in folds.split(X, y):
            #if hasattr(X, "iloc"):
                #X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
                #y_tr, y_va = y.iloc[tr_idx], y.iloc[va_idx]
            #else:
                #X_tr, X_va = X[tr_idx], X[va_idx]
                #y_tr, y_va = y[tr_idx], y[va_idx]
#
            #model = xgb.XGBClassifier(**params)
            #model.fit(
                #X_tr, y_tr,
                #eval_set=[(X_va, y_va)],
                ##early_stopping_rounds=50,
                #verbose=False,
            #)
#
            #if needs_proba:
                #y_score = model.predict_proba(X_va)[:, 1]
                #score = metric_fn(y_va, y_score)
            #else:
                #y_pred = model.predict(X_va)
                #score = metric_fn(y_va, y_pred)
            #scores.append(score)
#
            #trial.report(np.mean(scores), len(scores))
            #if trial.should_prune():
                #raise optuna.TrialPruned()
#
        #return float(np.mean(scores))
#
    #return objective
#
#def _evaluate_and_save(name: str, model, X_test, y_test, out_dir: str, feature_names=None, X_ref_for_shap=None):
    #"""Compute metrics, plot ROC + confusion matrix, and save everything."""
    #_ensure_dir(out_dir)
#
    ## Predictions
    #y_proba = None
    #try:
        #y_proba = model.predict_proba(X_test)[:, 1]
    #except Exception:
        #pass
    #y_pred = model.predict(X_test)
#
    ## Metrics
    #metrics = {
        #"balanced_accuracy": float(balanced_accuracy_score(y_test, y_pred)),
        #"mcc": None,
        #"roc_auc": None,
        #"sensitivity": None,   # <-- NEW
        #"specificity": None,   # <-- NEW
        #"classification_report": None,
    #}
    ## MCC
    #try:
        #metrics["mcc"] = float(matthews_corrcoef(y_test, y_pred))
    #except Exception:
        #pass
    ## ROC-AUC if both classes present and proba available
    #try:
        #if y_proba is not None and len(np.unique(y_test)) == 2:
            #metrics["roc_auc"] = float(roc_auc_score(y_test, y_proba))
        #else:
            #metrics["roc_auc"] = None
    #except Exception:
        #metrics["roc_auc"] = None
    ## --- Sensitivity & Specificity (labels fixed to [0,1]) ---
    #try:
        #cm = confusion_matrix(y_test, y_pred, labels=[0, 1])
        #tn, fp, fn, tp = cm.ravel()
        #sens_den = tp + fn
        #spec_den = tn + fp
        #metrics["sensitivity"] = float(tp / sens_den) if sens_den > 0 else None
        #metrics["specificity"] = float(tn / spec_den) if spec_den > 0 else None
    #except Exception:
        #pass
#
#
    ## Classification report (as dict)
    #try:
        #metrics["classification_report"] = classification_report(y_test, y_pred, output_dict=True)
    #except Exception:
        #metrics["classification_report"] = None
#
    ## Confusion matrix plot
    #try:
        #cm = confusion_matrix(y_test, y_pred)
        #disp = ConfusionMatrixDisplay(cm)
        #import matplotlib.pyplot as plt
        #plt.figure()
        #disp.plot(values_format="d")
        #plt.title(f"Confusion Matrix — {name}")
        #plt.savefig(os.path.join(out_dir, "confusion_matrix.png"), dpi=200, bbox_inches="tight")
        #plt.close()
    #except Exception:
        #pass
#
    ## ROC curve plot
    #try:
        #if y_proba is not None and len(np.unique(y_test)) == 2:
            #import matplotlib.pyplot as plt
            #plt.figure()
            #RocCurveDisplay.from_predictions(y_test, y_proba)
            #plt.title(f"ROC Curve — {name}")
            #plt.savefig(os.path.join(out_dir, "roc_curve.png"), dpi=200, bbox_inches="tight")
            #plt.close()
    #except Exception:
        #pass
#
    ## Feature names
    #if feature_names is None:
        #feature_names = _safe_feature_names(X_test)
#
    ## Feature importance plots
    #try:
        #_plot_feature_importance(model, feature_names, out_dir)
    #except Exception:
        #pass
#
    ## SHAP plots (optional)
    #try:
        #if X_ref_for_shap is None:
            #X_ref_for_shap = X_test
        #_save_shap_summaries(model, X_ref_for_shap, feature_names, out_dir)
    #except Exception:
        #pass
#
    ## Save metrics JSON
    #_save_json(metrics, os.path.join(out_dir, "metrics.json"))
    #return metrics
#
#def optimize_many(
    #dfs: Dict[str, pd.DataFrame],
    #x_y_split_fn,
    #scoring: str = "balanced_accuracy",
    #n_trials: int = 500,
    #n_splits: int = 5,
    #random_state: int = 42,
    #n_jobs_trials: int = -1,
    #output_dir: str = "xgb_results",
    #test_size: float = 0.20,
    #split_param: str = "emb_",
#) -> Tuple[pd.DataFrame, Dict[str, xgb.XGBClassifier], Dict[str, optuna.Study]]:
    #"""
    #Runs Optuna per dataset, evaluates on a held-out test set,
    #and saves plots + metrics in output_dir/<dataset_name>/
    #"""
    #results = []
    #best_models: Dict[str, xgb.XGBClassifier] = {}
    #studies: Dict[str, optuna.Study] = {}
#
    #_ensure_dir(output_dir)
#
    #for name, df in dfs.items():
        #X, y = x_y_split_fn(df, split_param=split_param)
#
        ## To numpy for fast indexing, but keep DataFrame support
        #X_arr = X.values if hasattr(X, "values") else X
        #y_arr = y.values if hasattr(y, "values") else y
#
        #feature_names = _safe_feature_names(X)
        ## Keep names before converting to numpy
#
        ## Hold-out test split (kept untouched for final evaluation)
        #X_train, X_test, y_train, y_test = train_test_split(
            #X_arr, y_arr, test_size=test_size, random_state=random_state, stratify=y_arr
        #)
#
        ## Build objective on TRAIN ONLY
        #objective = make_xgb_objective(X_train, y_train, scoring=scoring, n_splits=n_splits, random_state=random_state)
#
        #study = optuna.create_study(
            #study_name=f"{name}_{scoring}",
            #direction="maximize",
            #sampler=optuna.samplers.TPESampler(seed=random_state),
            #pruner=optuna.pruners.MedianPruner(n_startup_trials=10),
        #)
        #study.optimize(objective, n_trials=n_trials, show_progress_bar=True, n_jobs=n_jobs_trials)
        #studies[name] = study
#
        ## Train final model on TRAIN using best params (with small VA split for early stopping)
        #device_kwargs = _pick_device()
        #pos_ratio = float(np.mean(y_train))
        #spw = ((1.0 - pos_ratio) / pos_ratio) if 0 < pos_ratio < 1 else 1.0
#
        #best_params = {
            #**study.best_params,
            #"objective": "binary:logistic",
            #"eval_metric": "auc" if scoring == "roc_auc" else "logloss",
            #"n_jobs": 0,
            #"scale_pos_weight": spw,
            #**device_kwargs,
        #}
        #final_model = xgb.XGBClassifier(**best_params)
#
        ## Early stopping split inside TRAIN
        #X_tr, X_va, y_tr, y_va = train_test_split(
            #X_train, y_train, test_size=0.15, random_state=random_state, stratify=y_train
        #)
        #final_model.fit(
            #X_tr, y_tr,
            #eval_set=[(X_va, y_va)],
            ##early_stopping_rounds=50,
            #verbose=False,
        #)
#
        ## Save per-dataset artifacts
        #ds_out = os.path.join(output_dir, name)
        #_ensure_dir(ds_out)
#
        ## Evaluate on TEST and save plots/metrics
        #metrics = _evaluate_and_save(
            #name, final_model, X_test, y_test, ds_out,
            #feature_names=feature_names,
            #X_ref_for_shap=X_test
        #)
#
        ## Save best params + study summary
        #_save_json({"best_params": study.best_params, "best_value": study.best_value}, os.path.join(ds_out, "best.json"))
#
        ## Optional: save model
        #try:
            #import joblib
            #joblib.dump(final_model, os.path.join(ds_out, "model.joblib"))
        #except Exception:
            #pass
#
        #best_models[name] = final_model
        #results.append({
            #"dataset": name,
            #"cv_best_value": study.best_value,
            #"test_balanced_accuracy": metrics.get("balanced_accuracy"),
            #"test_roc_auc": metrics.get("roc_auc"),
            #"n_trials": len(study.trials),
        #})
#
    #summary_df = pd.DataFrame(results).sort_values(by="test_balanced_accuracy", ascending=False).reset_index(drop=True)
    ## Save a global summary too
    #summary_df.to_csv(os.path.join(output_dir, "summary.csv"), index=False)
    #return summary_df, best_models, studies
#

In [1474]:
#import os, json
#import numpy as np
#import pandas as pd
#import optuna, xgboost as xgb
#from typing import Dict, Tuple
#from sklearn.model_selection import StratifiedKFold, train_test_split, LeaveOneOut
#from sklearn.metrics import (
    #balanced_accuracy_score,
    #roc_auc_score,
    #confusion_matrix,
    #classification_report,
    #RocCurveDisplay,
    #ConfusionMatrixDisplay,
    #matthews_corrcoef
#)
#
## def x_y_split(df): ...  # your splitter (must return X, y)
#def _safe_feature_names(X, fallback_dim=None):
    #if hasattr(X, "columns"):
        #return list(X.columns)
    #if hasattr(X, "feature_names_in_"):
        #return list(X.feature_names_in_)
    #if fallback_dim is None and hasattr(X, "shape"):
        #fallback_dim = X.shape[1]
    #return [f"f{i}" for i in range(int(fallback_dim or 0))]
#
#def _plot_feature_importance(model, feature_names, out_dir: str):
    #"""Save multiple feature-importance views from XGBoost."""
    #import matplotlib.pyplot as plt
    #import numpy as np
    #from collections import defaultdict
    #os.makedirs(out_dir, exist_ok=True)
#
    ## 1) sklearn API importances (gain-based)
    #try:
        #importances = getattr(model, "feature_importances_", None)
        #if importances is not None and len(importances) == len(feature_names):
            #order = np.argsort(importances)[::-1]
            #top_idx = order[:50]  # limit to top-50 for readability
            #plt.figure()
            #plt.barh([feature_names[i] for i in top_idx][::-1], importances[top_idx][::-1])
            #plt.title("XGB feature_importances_ (top-50)")
            #plt.tight_layout()
            #plt.savefig(os.path.join(out_dir, "feature_importances_sklearn.png"), dpi=200, bbox_inches="tight")
            #plt.close()
    #except Exception:
        #pass
#
    ## 2) Booster importances (weight/gain/cover)
    #try:
        #booster = model.get_booster()
        #for typ in ["weight", "gain", "cover", "total_gain", "total_cover"]:
            #score_dict = booster.get_score(importance_type=typ)
            #if not score_dict:
                #continue
            ## Map 'f0'.. to friendly names
            #vals = []
            #names = []
            #for k, v in score_dict.items():
                #if k.startswith("f"):
                    #idx = int(k[1:])
                    #if 0 <= idx < len(feature_names):
                        #names.append(feature_names[idx])
                    #else:
                        #names.append(k)
                #else:
                    #names.append(k)
                #vals.append(v)
            #order = np.argsort(vals)[::-1]
            #top = min(50, len(order))
            #plt.figure()
            #plt.barh([names[i] for i in order[:top]][::-1], np.array(vals)[order[:top]][::-1])
            #plt.title(f"Booster feature importance — {typ} (top-{top})")
            #plt.tight_layout()
            #plt.savefig(os.path.join(out_dir, f"feature_importances_{typ}.png"), dpi=200, bbox_inches="tight")
            #plt.close()
    #except Exception:
        #pass
#
#def _save_shap_summaries(model, X_ref, feature_names, out_dir: str, max_display: int = 30, sample: int = 1000):
    #"""
    #Compute SHAP (TreeExplainer) and save bar + beeswarm plots.
    #Skips silently if shap not installed or backend issues arise.
    #"""
    #try:
        #import shap
        #import numpy as np
        #import matplotlib.pyplot as plt
    #except Exception:
        #return
#
    #try:
        ## Downsample for speed
        #if hasattr(X_ref, "iloc"):
            #X_use = X_ref.sample(min(sample, len(X_ref)), random_state=0)
            #X_np = X_use.values
        #else:
            #X_np = X_ref
            #if X_np.shape[0] > sample:
                #rng = np.random.default_rng(0)
                #idx = rng.choice(X_np.shape[0], size=sample, replace=False)
                #X_np = X_np[idx]
#
        #explainer = shap.TreeExplainer(model)
        #shap_values = explainer.shap_values(X_np)
#
        ## Handle binary classification: shap returns array (n, p)
        #if isinstance(shap_values, list) and len(shap_values) == 2:
            ## pick positive class
            #sv = shap_values[1]
        #else:
            #sv = shap_values
#
        ## Bar plot (mean |SHAP|)
        #try:
            #plt.figure()
            #shap.summary_plot(sv, X_np, feature_names=feature_names, plot_type="bar", show=False, max_display=max_display)
            #plt.tight_layout()
            #plt.savefig(os.path.join(out_dir, "shap_summary_bar.png"), dpi=200, bbox_inches="tight")
            #plt.close()
        #except Exception:
            #pass
#
        ## Beeswarm
        #try:
            #plt.figure()
            #shap.summary_plot(sv, X_np, feature_names=feature_names, show=False, max_display=max_display)
            #plt.tight_layout()
            #plt.savefig(os.path.join(out_dir, "shap_summary_beeswarm.png"), dpi=200, bbox_inches="tight")
            #plt.close()
        #except Exception:
            #pass
    #except Exception:
        ## Any SHAP error -> skip silently
        #return
#
#def _pick_device():
    #try:
        #_ = xgb.core.get_cuda_compute_capabilities()
        #return {"tree_method": "hist", "device": "cuda"}
    #except Exception:
        #return {"tree_method": "hist", "device": "cpu"}
#
#def _ensure_dir(path: str):
    #os.makedirs(path, exist_ok=True)
#
#def _save_json(d: dict, path: str):
    #with open(path, "w", encoding="utf-8") as f:
        #json.dump(d, f, indent=2, ensure_ascii=False)
#
#def make_xgb_objective(X, y, scoring: str = "balanced_accuracy", cv_strategy: str = "loo", 
                       #n_splits: int = 5, random_state: int = 42):
    #"""
    #Create Optuna objective function with configurable CV strategy.
    #
    #Parameters:
    #-----------
    #cv_strategy : str
        #Either 'skf' (StratifiedKFold) or 'loo' (LeaveOneOut)
    #n_splits : int
        #Number of splits for StratifiedKFold (ignored for LOO)
    #"""
    #if scoring == "balanced_accuracy":
        #from sklearn.metrics import balanced_accuracy_score as metric_fn
        #needs_proba = False
        #eval_metric = "logloss"
    #elif scoring == "roc_auc":
        #from sklearn.metrics import roc_auc_score as metric_fn
        #needs_proba = True
        #eval_metric = "auc"
    #else:
        #raise ValueError("scoring must be 'balanced_accuracy' or 'roc_auc'")
#
    ## Choose CV strategy
    #if cv_strategy == "loo":
        #folds = LeaveOneOut()
        #print(f"Using Leave-One-Out CV with {len(y)} folds")
    #elif cv_strategy == "skf":
        #folds = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=random_state)
        #print(f"Using Stratified K-Fold CV with {n_splits} folds")
    #else:
        #raise ValueError("cv_strategy must be 'skf' or 'loo'")
#
    #device_kwargs = _pick_device()
#
    #pos_ratio = float(np.mean(y))
    #scale_pos_weight = ((1.0 - pos_ratio) / pos_ratio) if 0 < pos_ratio < 1 else 1.0
#
    #def objective(trial: optuna.Trial) -> float:
        #params = {
            #"max_depth": trial.suggest_int("max_depth", 3, 10),
            #"learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
            #"n_estimators": trial.suggest_int("n_estimators", 200, 1500),
            #"subsample": trial.suggest_float("subsample", 0.5, 1.0),
            #"colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
            #"min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
            #"gamma": trial.suggest_float("gamma", 0.0, 5.0),
            #"reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
            #"reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
            #"max_delta_step": trial.suggest_int("max_delta_step", 0, 10),
            #"objective": "binary:logistic",
            #"eval_metric": eval_metric,
            #"n_jobs": 1,  # keep each trial single-threaded
            #"scale_pos_weight": scale_pos_weight,
            #**device_kwargs,
        #}
#
        #scores = []
        #for fold_idx, (tr_idx, va_idx) in enumerate(folds.split(X, y)):
            #if hasattr(X, "iloc"):
                #X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
                #y_tr, y_va = y.iloc[tr_idx], y.iloc[va_idx]
            #else:
                #X_tr, X_va = X[tr_idx], X[va_idx]
                #y_tr, y_va = y[tr_idx], y[va_idx]
#
            #model = xgb.XGBClassifier(**params)
            #
            ## For LOO, skip early stopping (only 1 validation sample)
            #if cv_strategy == "loo":
                #model.fit(X_tr, y_tr, verbose=False)
            #else:
                #model.fit(
                    #X_tr, y_tr,
                    #eval_set=[(X_va, y_va)],
                    #verbose=False,
                #)
#
            #if needs_proba:
                #y_score = model.predict_proba(X_va)[:, 1]
                #score = metric_fn(y_va, y_score)
            #else:
                #y_pred = model.predict(X_va)
                #score = metric_fn(y_va, y_pred)
            #scores.append(score)
#
            ## Report intermediate values and check for pruning
            ## For LOO: report every 10 folds to reduce overhead
            #if cv_strategy == "loo":
                #if (fold_idx + 1) % 10 == 0:
                    #trial.report(np.mean(scores), fold_idx)
                    #if trial.should_prune():
                        #raise optuna.TrialPruned()
            #else:
                #trial.report(np.mean(scores), fold_idx)
                #if trial.should_prune():
                    #raise optuna.TrialPruned()
#
        #return float(np.mean(scores))
#
    #return objective
#
#def _evaluate_and_save(name: str, model, X_test, y_test, out_dir: str, feature_names=None, X_ref_for_shap=None):
    #"""Compute metrics, plot ROC + confusion matrix, and save everything."""
    #_ensure_dir(out_dir)
#
    ## Predictions
    #y_proba = None
    #try:
        #y_proba = model.predict_proba(X_test)[:, 1]
    #except Exception:
        #pass
    #y_pred = model.predict(X_test)
#
    ## Metrics
    #metrics = {
        #"balanced_accuracy": float(balanced_accuracy_score(y_test, y_pred)),
        #"mcc": None,
        #"roc_auc": None,
        #"sensitivity": None,
        #"specificity": None,
        #"classification_report": None,
    #}
    ## MCC
    #try:
        #metrics["mcc"] = float(matthews_corrcoef(y_test, y_pred))
    #except Exception:
        #pass
    ## ROC-AUC if both classes present and proba available
    #try:
        #if y_proba is not None and len(np.unique(y_test)) == 2:
            #metrics["roc_auc"] = float(roc_auc_score(y_test, y_proba))
        #else:
            #metrics["roc_auc"] = None
    #except Exception:
        #metrics["roc_auc"] = None
    ## --- Sensitivity & Specificity (labels fixed to [0,1]) ---
    #try:
        #cm = confusion_matrix(y_test, y_pred, labels=[0, 1])
        #tn, fp, fn, tp = cm.ravel()
        #sens_den = tp + fn
        #spec_den = tn + fp
        #metrics["sensitivity"] = float(tp / sens_den) if sens_den > 0 else None
        #metrics["specificity"] = float(tn / spec_den) if spec_den > 0 else None
    #except Exception:
        #pass
#
    ## Classification report (as dict)
    #try:
        #metrics["classification_report"] = classification_report(y_test, y_pred, output_dict=True)
    #except Exception:
        #metrics["classification_report"] = None
#
    ## Confusion matrix plot
    #try:
        #cm = confusion_matrix(y_test, y_pred)
        #disp = ConfusionMatrixDisplay(cm)
        #import matplotlib.pyplot as plt
        #plt.figure()
        #disp.plot(values_format="d")
        #plt.title(f"Confusion Matrix — {name}")
        #plt.savefig(os.path.join(out_dir, "confusion_matrix.png"), dpi=200, bbox_inches="tight")
        #plt.close()
    #except Exception:
        #pass
#
    ## ROC curve plot
    #try:
        #if y_proba is not None and len(np.unique(y_test)) == 2:
            #import matplotlib.pyplot as plt
            #plt.figure()
            #RocCurveDisplay.from_predictions(y_test, y_proba)
            #plt.title(f"ROC Curve — {name}")
            #plt.savefig(os.path.join(out_dir, "roc_curve.png"), dpi=200, bbox_inches="tight")
            #plt.close()
    #except Exception:
        #pass
#
    ## Feature names
    #if feature_names is None:
        #feature_names = _safe_feature_names(X_test)
#
    ## Feature importance plots
    #try:
        #_plot_feature_importance(model, feature_names, out_dir)
    #except Exception:
        #pass
#
    ## SHAP plots (optional)
    #try:
        #if X_ref_for_shap is None:
            #X_ref_for_shap = X_test
        #_save_shap_summaries(model, X_ref_for_shap, feature_names, out_dir)
    #except Exception:
        #pass
#
    ## Save metrics JSON
    #_save_json(metrics, os.path.join(out_dir, "metrics.json"))
    #return metrics
#
#def optimize_many(
    #dfs: Dict[str, pd.DataFrame],
    #x_y_split_fn,
    #scoring: str = "balanced_accuracy",
    #cv_strategy: str = "loo",  # NEW: 'skf' or 'loo'
    #n_trials: int = 500,
    #n_splits: int = 5,
    #random_state: int = 42,
    #n_jobs_trials: int = -1,
    #output_dir: str = "xgb_results",
    #test_size: float = 0.20,
    #split_param: str = "emb_",
#) -> Tuple[pd.DataFrame, Dict[str, xgb.XGBClassifier], Dict[str, optuna.Study]]:
    #"""
    #Runs Optuna per dataset, evaluates on a held-out test set,
    #and saves plots + metrics in output_dir/<dataset_name>/
    #
    #Parameters:
    #-----------
    #cv_strategy : str
        #Either 'skf' (StratifiedKFold) or 'loo' (LeaveOneOut)
    #"""
    #results = []
    #best_models: Dict[str, xgb.XGBClassifier] = {}
    #studies: Dict[str, optuna.Study] = {}
#
    #_ensure_dir(output_dir)
#
    #for name, df in dfs.items():
        #print(f"\n{'='*60}")
        #print(f"Processing dataset: {name}")
        #print(f"{'='*60}")
        #
        #X, y = x_y_split_fn(df, split_param=split_param)
#
        ## To numpy for fast indexing, but keep DataFrame support
        #X_arr = X.values if hasattr(X, "values") else X
        #y_arr = y.values if hasattr(y, "values") else y
#
        #feature_names = _safe_feature_names(X)
#
        ## Hold-out test split (kept untouched for final evaluation)
        #X_train, X_test, y_train, y_test = train_test_split(
            #X_arr, y_arr, test_size=test_size, random_state=random_state, stratify=y_arr
        #)
#
        #print(f"Train size: {len(X_train)}, Test size: {len(X_test)}")
#
        ## Build objective on TRAIN ONLY
        #objective = make_xgb_objective(
            #X_train, y_train, 
            #scoring=scoring, 
            #cv_strategy=cv_strategy,
            #n_splits=n_splits, 
            #random_state=random_state
        #)
#
        #study = optuna.create_study(
            #study_name=f"{name}_{scoring}",
            #direction="maximize",
            #sampler=optuna.samplers.TPESampler(seed=random_state),
            #pruner=optuna.pruners.MedianPruner(n_startup_trials=10),
        #)
        #
        #print(f"Starting optimization with {n_trials} trials...")
        #study.optimize(objective, n_trials=n_trials, show_progress_bar=True, n_jobs=n_jobs_trials)
        #studies[name] = study
#
        ## Train final model on TRAIN using best params
        #device_kwargs = _pick_device()
        #pos_ratio = float(np.mean(y_train))
        #spw = ((1.0 - pos_ratio) / pos_ratio) if 0 < pos_ratio < 1 else 1.0
#
        #best_params = {
            #**study.best_params,
            #"objective": "binary:logistic",
            #"eval_metric": "auc" if scoring == "roc_auc" else "logloss",
            #"n_jobs": 0,
            #"scale_pos_weight": spw,
            #**device_kwargs,
        #}
        #final_model = xgb.XGBClassifier(**best_params)
#
        ## For final model training:
        ## - If LOO was used in CV, train on full training set
        ## - If SKF was used, use early stopping split
        #if cv_strategy == "loo":
            #print("Training final model on full training set (LOO strategy)...")
            #final_model.fit(X_train, y_train, verbose=False)
        #else:
            #print("Training final model with early stopping validation split...")
            #X_tr, X_va, y_tr, y_va = train_test_split(
                #X_train, y_train, test_size=0.15, random_state=random_state, stratify=y_train
            #)
            #final_model.fit(
                #X_tr, y_tr,
                #eval_set=[(X_va, y_va)],
                #verbose=False,
            #)
#
        ## Save per-dataset artifacts
        #ds_out = os.path.join(output_dir, name)
        #_ensure_dir(ds_out)
#
        ## Evaluate on TEST and save plots/metrics
        #print("Evaluating on test set...")
        #metrics = _evaluate_and_save(
            #name, final_model, X_test, y_test, ds_out,
            #feature_names=feature_names,
            #X_ref_for_shap=X_test
        #)
#
        ## Save best params + study summary
        #_save_json({
            #"best_params": study.best_params, 
            #"best_value": study.best_value,
            #"cv_strategy": cv_strategy,
            #"n_folds": len(y_train) if cv_strategy == "loo" else n_splits
        #}, os.path.join(ds_out, "best.json"))
#
        ## Optional: save model
        #try:
            #import joblib
            #joblib.dump(final_model, os.path.join(ds_out, "model.joblib"))
        #except Exception:
            #pass
#
        #best_models[name] = final_model
        #results.append({
            #"dataset": name,
            #"cv_strategy": cv_strategy,
            #"cv_best_value": study.best_value,
            #"test_balanced_accuracy": metrics.get("balanced_accuracy"),
            #"test_roc_auc": metrics.get("roc_auc"),
            #"test_mcc": metrics.get("mcc"),
            #"test_sensitivity": metrics.get("sensitivity"),
            #"test_specificity": metrics.get("specificity"),
            #"n_trials": len(study.trials),
            #"train_size": len(X_train),
            #"test_size": len(X_test),
        #})
#
    #summary_df = pd.DataFrame(results).sort_values(by="test_balanced_accuracy", ascending=False).reset_index(drop=True)
    ## Save a global summary too
    #summary_df.to_csv(os.path.join(output_dir, "summary.csv"), index=False)
    #
    #print(f"\n{'='*60}")
    #print("All datasets processed. Summary:")
    #print(f"{'='*60}")
    #print(summary_df)
    #
    #return summary_df, best_models, studies

In [1475]:
import os, json
import numpy as np
import pandas as pd
import optuna, xgboost as xgb
from typing import Dict, Tuple
from sklearn.model_selection import StratifiedKFold, train_test_split, LeaveOneOut
from sklearn.metrics import (
    balanced_accuracy_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    RocCurveDisplay,
    ConfusionMatrixDisplay,
    matthews_corrcoef
)

# def x_y_split(df): ...  # your splitter (must return X, y)
def _safe_feature_names(X, fallback_dim=None):
    if hasattr(X, "columns"):
        return list(X.columns)
    if hasattr(X, "feature_names_in_"):
        return list(X.feature_names_in_)
    if fallback_dim is None and hasattr(X, "shape"):
        fallback_dim = X.shape[1]
    return [f"f{i}" for i in range(int(fallback_dim or 0))]

def _plot_feature_importance(model, feature_names, out_dir: str):
    """Save multiple feature-importance views from XGBoost."""
    import matplotlib.pyplot as plt
    import numpy as np
    from collections import defaultdict
    os.makedirs(out_dir, exist_ok=True)

    # 1) sklearn API importances (gain-based)
    try:
        importances = getattr(model, "feature_importances_", None)
        if importances is not None and len(importances) == len(feature_names):
            order = np.argsort(importances)[::-1]
            top_idx = order[:50]  # limit to top-50 for readability
            plt.figure()
            plt.barh([feature_names[i] for i in top_idx][::-1], importances[top_idx][::-1])
            plt.title("XGB feature_importances_ (top-50)")
            plt.tight_layout()
            plt.savefig(os.path.join(out_dir, "feature_importances_sklearn.png"), dpi=200, bbox_inches="tight")
            plt.close()
    except Exception:
        pass

    # 2) Booster importances (weight/gain/cover)
    try:
        booster = model.get_booster()
        for typ in ["weight", "gain", "cover", "total_gain", "total_cover"]:
            score_dict = booster.get_score(importance_type=typ)
            if not score_dict:
                continue
            vals, names = [], []
            for k, v in score_dict.items():
                if k.startswith("f"):
                    idx = int(k[1:])
                    names.append(feature_names[idx] if 0 <= idx < len(feature_names) else k)
                else:
                    names.append(k)
                vals.append(v)
            order = np.argsort(vals)[::-1]
            top = min(50, len(order))
            plt.figure()
            plt.barh([names[i] for i in order[:top]][::-1], np.array(vals)[order[:top]][::-1])
            plt.title(f"Booster feature importance — {typ} (top-{top})")
            plt.tight_layout()
            plt.savefig(os.path.join(out_dir, f"feature_importances_{typ}.png"), dpi=200, bbox_inches="tight")
            plt.close()
    except Exception:
        pass

def _save_shap_summaries(model, X_ref, feature_names, out_dir: str, max_display: int = 30, sample: int = 1000):
    """
    Compute SHAP (TreeExplainer) and save bar + beeswarm plots.
    Skips silently if shap not installed or backend issues arise.
    """
    try:
        import shap
        import numpy as np
        import matplotlib.pyplot as plt
    except Exception:
        return

    try:
        if hasattr(X_ref, "iloc"):
            X_use = X_ref.sample(min(sample, len(X_ref)), random_state=0)
            X_np = X_use.values
        else:
            X_np = X_ref
            if X_np.shape[0] > sample:
                rng = np.random.default_rng(0)
                idx = rng.choice(X_np.shape[0], size=sample, replace=False)
                X_np = X_np[idx]

        explainer = shap.TreeExplainer(model)
        shap_values = explainer.shap_values(X_np)
        sv = shap_values[1] if isinstance(shap_values, list) and len(shap_values) == 2 else shap_values

        try:
            plt.figure()
            shap.summary_plot(sv, X_np, feature_names=feature_names, plot_type="bar", show=False, max_display=max_display)
            plt.tight_layout()
            plt.savefig(os.path.join(out_dir, "shap_summary_bar.png"), dpi=200, bbox_inches="tight")
            plt.close()
        except Exception:
            pass

        try:
            plt.figure()
            shap.summary_plot(sv, X_np, feature_names=feature_names, show=False, max_display=max_display)
            plt.tight_layout()
            plt.savefig(os.path.join(out_dir, "shap_summary_beeswarm.png"), dpi=200, bbox_inches="tight")
            plt.close()
        except Exception:
            pass
    except Exception:
        return

def _pick_device():
    try:
        _ = xgb.core.get_cuda_compute_capabilities()
        return {"tree_method": "hist", "device": "cuda"}
    except Exception:
        return {"tree_method": "hist", "device": "cpu"}

def _ensure_dir(path: str):
    os.makedirs(path, exist_ok=True)

def _save_json(d: dict, path: str):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(d, f, indent=2, ensure_ascii=False)

def make_xgb_objective(
    X, y,
    scoring: str = "balanced_accuracy",
    cv_strategy: str = "loo",
    n_splits: int = 5,
    random_state: int = 42
):
    """Create Optuna objective with configurable CV strategy."""
    if scoring == "balanced_accuracy":
        from sklearn.metrics import balanced_accuracy_score as metric_fn
        needs_proba = False
        eval_metric = "logloss"
    elif scoring == "roc_auc":
        from sklearn.metrics import roc_auc_score as metric_fn
        needs_proba = True
        eval_metric = "auc"
    else:
        raise ValueError("scoring must be 'balanced_accuracy' or 'roc_auc'")

    if cv_strategy == "loo":
        folds = LeaveOneOut()
        print(f"Using Leave-One-Out CV with {len(y)} folds")
    elif cv_strategy == "skf":
        folds = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=random_state)
        print(f"Using Stratified K-Fold CV with {n_splits} folds")
    else:
        raise ValueError("cv_strategy must be 'skf' or 'loo'")

    device_kwargs = _pick_device()
    pos_ratio = float(np.mean(y))
    scale_pos_weight = ((1.0 - pos_ratio) / pos_ratio) if 0 < pos_ratio < 1 else 1.0

    y_array = y.to_numpy() if hasattr(y, "to_numpy") else np.asarray(y)
    n_samples = len(y_array)

    def objective(trial: optuna.Trial) -> float:
        params = {
            #To Tune leabes, branches, trees, regularization
            "max_depth": trial.suggest_int("max_depth", 3, 10),
            "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
            "n_estimators": trial.suggest_int("n_estimators", 200, 1500),
            "subsample": trial.suggest_float("subsample", 0.5, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
            "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
            "gamma": trial.suggest_float("gamma", 0.0, 5.0),
            "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
            "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
            "max_delta_step": trial.suggest_int("max_delta_step", 0, 10),
            "objective": "binary:logistic",
            "eval_metric": eval_metric,
            "n_jobs": 1,
            "scale_pos_weight": scale_pos_weight,
            **device_kwargs,
        }

        oof_predictions = np.zeros(n_samples, dtype=float)
        filled_mask = np.zeros(n_samples, dtype=bool)

        for fold_idx, (tr_idx, va_idx) in enumerate(folds.split(X, y)):
            if hasattr(X, "iloc"):
                X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
                y_tr, y_va = y.iloc[tr_idx], y.iloc[va_idx]
            else:
                X_tr, X_va = X[tr_idx], X[va_idx]
                y_tr, y_va = y[tr_idx], y[va_idx]

            model = xgb.XGBClassifier(**params)
            model.fit(X_tr, y_tr, verbose=False)

            preds = model.predict_proba(X_va)[:, 1] if needs_proba else model.predict(X_va)
            oof_predictions[va_idx] = preds
            filled_mask[va_idx] = True

            y_seen = y_array[filled_mask]
            preds_seen = oof_predictions[filled_mask]

            if np.unique(y_seen).size < 2:
                continue

            score = metric_fn(y_seen, preds_seen)
            if cv_strategy == "loo":
                if (fold_idx + 1) % 10 == 0:
                    trial.report(score, fold_idx)
                    if trial.should_prune():
                        raise optuna.TrialPruned()
            else:
                trial.report(score, fold_idx)
                if trial.should_prune():
                    raise optuna.TrialPruned()

        final_score = metric_fn(y_array, oof_predictions)
        return float(final_score)

    return objective

def _evaluate_and_save(name: str, model, X_test, y_test, out_dir: str, feature_names=None, X_ref_for_shap=None):
    """Compute metrics, plot ROC + confusion matrix, and save everything."""
    _ensure_dir(out_dir)

    y_proba = None
    try:
        y_proba = model.predict_proba(X_test)[:, 1]
    except Exception:
        pass
    y_pred = model.predict(X_test)

    metrics = {
        "balanced_accuracy": float(balanced_accuracy_score(y_test, y_pred)),
        "mcc": None,
        "roc_auc": None,
        "sensitivity": None,
        "specificity": None,
        "classification_report": None,
    }
    try:
        metrics["mcc"] = float(matthews_corrcoef(y_test, y_pred))
    except Exception:
        pass
    try:
        if y_proba is not None and len(np.unique(y_test)) == 2:
            metrics["roc_auc"] = float(roc_auc_score(y_test, y_proba))
        else:
            metrics["roc_auc"] = None
    except Exception:
        metrics["roc_auc"] = None
    try:
        cm = confusion_matrix(y_test, y_pred, labels=[0, 1])
        tn, fp, fn, tp = cm.ravel()
        sens_den = tp + fn
        spec_den = tn + fp
        metrics["sensitivity"] = float(tp / sens_den) if sens_den > 0 else None
        metrics["specificity"] = float(tn / spec_den) if spec_den > 0 else None
    except Exception:
        pass
    try:
        metrics["classification_report"] = classification_report(y_test, y_pred, output_dict=True)
    except Exception:
        metrics["classification_report"] = None

    try:
        cm = confusion_matrix(y_test, y_pred)
        disp = ConfusionMatrixDisplay(cm)
        import matplotlib.pyplot as plt
        plt.figure()
        disp.plot(values_format="d")
        plt.title(f"Confusion Matrix — {name}")
        plt.savefig(os.path.join(out_dir, "confusion_matrix.png"), dpi=200, bbox_inches="tight")
        plt.close()
    except Exception:
        pass

    try:
        if y_proba is not None and len(np.unique(y_test)) == 2:
            import matplotlib.pyplot as plt
            plt.figure()
            RocCurveDisplay.from_predictions(y_test, y_proba)
            plt.title(f"ROC Curve — {name}")
            plt.savefig(os.path.join(out_dir, "roc_curve.png"), dpi=200, bbox_inches="tight")
            plt.close()
    except Exception:
        pass

    if feature_names is None:
        feature_names = _safe_feature_names(X_test)

    try:
        _plot_feature_importance(model, feature_names, out_dir)
    except Exception:
        pass

    try:
        if X_ref_for_shap is None:
            X_ref_for_shap = X_test
        _save_shap_summaries(model, X_ref_for_shap, feature_names, out_dir)
    except Exception:
        pass

    _save_json(metrics, os.path.join(out_dir, "metrics.json"))
    return metrics

def optimize_many(
    dfs: Dict[str, pd.DataFrame],
    x_y_split_fn,
    scoring: str = "balanced_accuracy",
    cv_strategy: str = "loo",
    n_trials: int = 500,
    n_splits: int = 5,
    random_state: int = 42,
    n_jobs_trials: int = -1,
    output_dir: str = "xgb_results",
    test_size: float = 0.20,
    split_param: str = "emb_",
) -> Tuple[pd.DataFrame, Dict[str, xgb.XGBClassifier], Dict[str, optuna.Study]]:
    """
    Runs Optuna per dataset, evaluates on a held-out test set,
    and saves plots + metrics in output_dir/<dataset_name>/
    """
    results = []
    best_models: Dict[str, xgb.XGBClassifier] = {}
    studies: Dict[str, optuna.Study] = {}

    _ensure_dir(output_dir)

    for name, df in dfs.items():
        print(f"\n{'='*60}")
        print(f"Processing dataset: {name}")
        print(f"{'='*60}")
        
        X, y = x_y_split_fn(df, split_param=split_param)

        X_arr = X.values if hasattr(X, "values") else X
        y_arr = y.values if hasattr(y, "values") else y

        feature_names = _safe_feature_names(X)

        X_train, X_test, y_train, y_test = train_test_split(
            X_arr, y_arr, test_size=test_size, random_state=random_state, stratify=y_arr
        )

        print(f"Train size: {len(X_train)}, Test size: {len(X_test)}")

        objective = make_xgb_objective(
            X_train, y_train,
            scoring=scoring,
            cv_strategy=cv_strategy,
            n_splits=n_splits,
            random_state=random_state
        )

        study = optuna.create_study(
            study_name=f"{name}_{scoring}",
            direction="maximize",
            sampler=optuna.samplers.TPESampler(seed=random_state),
            pruner=optuna.pruners.MedianPruner(n_startup_trials=10),
        )
        
        print(f"Starting optimization with {n_trials} trials...")
        study.optimize(objective, n_trials=n_trials, show_progress_bar=True, n_jobs=n_jobs_trials)
        studies[name] = study

        device_kwargs = _pick_device()
        pos_ratio = float(np.mean(y_train))
        spw = ((1.0 - pos_ratio) / pos_ratio) if 0 < pos_ratio < 1 else 1.0

        best_params = {
            **study.best_params,
            "objective": "binary:logistic",
            "eval_metric": "auc" if scoring == "roc_auc" else "logloss",
            "n_jobs": 0,
            "scale_pos_weight": spw,
            **device_kwargs,
        }
        final_model = xgb.XGBClassifier(**best_params)

        if cv_strategy == "loo":
            print("Training final model on full training set (LOO strategy)...")
            final_model.fit(X_train, y_train, verbose=False)
        else:
            print("Training final model with early stopping validation split...")
            X_tr, X_va, y_tr, y_va = train_test_split(
                X_train, y_train, test_size=0.15, random_state=random_state, stratify=y_train
            )
            final_model.fit(
                X_tr, y_tr,
                eval_set=[(X_va, y_va)],
                verbose=False,
            )

        ds_out = os.path.join(output_dir, name)
        _ensure_dir(ds_out)

        print("Evaluating on test set...")
        metrics = _evaluate_and_save(
            name, final_model, X_test, y_test, ds_out,
            feature_names=feature_names,
            X_ref_for_shap=X_test
        )

        _save_json({
            "best_params": study.best_params,
            "best_value": study.best_value,
            "cv_strategy": cv_strategy,
            "n_folds": len(y_train) if cv_strategy == "loo" else n_splits
        }, os.path.join(ds_out, "best.json"))

        try:
            import joblib
            joblib.dump(final_model, os.path.join(ds_out, "model.joblib"))
        except Exception:
            pass

        best_models[name] = final_model
        results.append({
            "dataset": name,
            "cv_strategy": cv_strategy,
            "cv_best_value": study.best_value,
            "test_balanced_accuracy": metrics.get("balanced_accuracy"),
            "test_roc_auc": metrics.get("roc_auc"),
            "test_mcc": metrics.get("mcc"),
            "test_sensitivity": metrics.get("sensitivity"),
            "test_specificity": metrics.get("specificity"),
            "n_trials": len(study.trials),
            "train_size": len(X_train),
            "test_size": len(X_test),
        })

    summary_df = pd.DataFrame(results).sort_values(by="test_balanced_accuracy", ascending=False).reset_index(drop=True)
    summary_df.to_csv(os.path.join(output_dir, "summary.csv"), index=False)
    
    print(f"\n{'='*60}")
    print("All datasets processed. Summary:")
    print(f"{'='*60}")
    print(summary_df)
    
    return summary_df, best_models, studies

In [1476]:
print(
task_hf_compensated_comb_emb_lbl_lbd_hc.get('17_1').shape,
task_hf_compensated_temp_emb_lbl_lbd_hc.get('17_1').shape,
task_hf_compensated_freq_emb_lbl_lbd_hc.get('17_1').shape,

task_comb_dfs_lbd_hc.get('17_1').shape,
task_temp_dfs_lbd_hc.get('17_1').shape,
task_freq_dfs_lbd_hc.get('17_1').shape,

task_hf_dfs_clean_lbd_hc.get('17_1').shape,
)

(84, 836) (84, 452) (84, 452) (84, 770) (84, 386) (84, 386) (84, 68)

In [1477]:

task_hf_dfs_clean_lbd_hc.get('19_1')

,ID,w.cz.fnusa.19_1_95th percentile of acceleration (in-air),w.cz.fnusa.19_1_95th percentile of acceleration (on-surface),w.cz.fnusa.19_1_95th percentile of angular velocity (in-air),w.cz.fnusa.19_1_95th percentile of angular velocity (on-surface),w.cz.fnusa.19_1_95th percentile of horizontal acceleration (in-air),w.cz.fnusa.19_1_95th percentile of horizontal acceleration (on-surface),w.cz.fnusa.19_1_95th percentile of horizontal velocity (in-air),w.cz.fnusa.19_1_95th percentile of horizontal velocity (on-surface),w.cz.fnusa.19_1_95th percentile of velocity (in-air),...,w.cz.fnusa.19_1_slope of horizontal velocity (on-surface),w.cz.fnusa.19_1_slope of pressure,w.cz.fnusa.19_1_slope of ratio of the on-surface/in-air stroke duration,w.cz.fnusa.19_1_slope of velocity (in-air),w.cz.fnusa.19_1_slope of velocity (on-surface),w.cz.fnusa.19_1_slope of vertical velocity (in-air),w.cz.fnusa.19_1_slope of vertical velocity (on-surface),w.cz.fnusa.19_1_tempo (in-air),w.cz.fnusa.19_1_tempo (on-surface),diagnosis
0,COBEN-WTABLET-AS-HCD05,2013.070361,1642.987099,46.843778,48.470925,1748.565051,1239.397321,76.366071,38.571429,87.376313,...,0.001500,-0.000006,0.102963,0.037244,0.000153,0.006966,-0.001003,3.020668,1.249609,0.0
1,COBEN-WTABLET-DS-HC36,1601.144846,1391.497940,49.003420,36.335628,1122.448980,714.285714,47.500000,25.714286,72.653394,...,-0.000333,0.000026,0.207307,-0.017636,-0.002187,-0.021440,-0.002413,3.143666,1.281504,0.0
2,COBEN-WTABLET-EH-HC35,1652.772266,1688.511011,37.926735,42.858113,1645.169005,1084.183673,61.875000,39.343750,74.940719,...,0.001398,0.000016,0.014616,-0.000928,0.001441,-0.004459,0.000301,2.909620,1.786778,0.0
3,COBEN-WTABLET-FG-HC38,2362.984031,1948.188792,57.365741,48.811784,2256.377551,1464.923469,71.464286,46.285714,84.637299,...,0.000362,-0.000023,0.020852,-0.006053,-0.003346,-0.006564,-0.004395,1.870972,1.785031,0.0
4,COBEN-WTABLET-HJ-HC21,1418.678841,2158.744274,48.235334,48.685071,1493.463010,1709.183673,43.572981,53.125000,53.282775,...,-0.001205,0.000059,0.008865,0.001029,-0.005189,-0.000683,-0.005806,1.783040,1.852116,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,pre-LBD-56#1,4023.215341,2231.029217,68.107989,54.928067,4410.873724,2015.306122,126.125000,62.857143,134.421706,...,0.000308,0.000045,-0.039991,-0.040449,-0.000562,-0.002531,-0.001846,3.220612,1.202008,1.0
80,pre-LBD-57#1,2283.694720,3340.507560,39.631727,38.770321,2346.938776,2345.663265,85.513393,49.312500,93.657516,...,0.000338,0.000014,0.005092,-0.000391,-0.001769,-0.002900,-0.003869,3.606103,6.519806,1.0
81,pre-LBD-57#2,2649.771312,2386.383366,49.519532,53.682256,2498.955580,1798.121612,87.127092,54.564397,107.131158,...,0.000661,0.000037,0.030424,-0.016281,-0.002721,-0.014982,-0.004203,3.361922,1.718276,1.0
82,pre-LBD-58#1,2287.153015,1848.561662,35.755660,57.841684,2835.937500,1190.609056,131.875000,37.857143,134.361918,...,0.002208,0.000017,0.177180,-0.026706,0.001567,0.009638,0.000220,3.263052,1.099937,1.0
83,pre-LBD-59#1,1892.883348,1561.286701,44.802950,43.614013,1618.781888,1309.311224,72.937500,39.285714,87.139827,...,0.007033,0.000094,0.053816,-0.001149,0.005414,-0.002069,0.000218,2.769100,3.215176,1.0

# MCI_LBD vs HC -> OPTUNA + XGB

In [1560]:
# parameters
NUM_TRIALS = 50
CV_STRATEGY = 'loo'  # 'loo' or 'skf'

# From this one

In [1561]:
datasets = task_hf_compensated_comb_emb_lbl_lbd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir= f"xgb_lbd_hc_{CV_STRATEGY}_tasks/xgb_results_handcrafted_combined_emb_lbd_hc_{CV_STRATEGY}_tasks",
    split_param= "diagnosis_y",
)
print(summary)

[I 2025-12-01 15:15:33,948] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 63, Test size: 16
Using Leave-One-Out CV with 63 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.498913:   2%|▏         | 1/50 [00:44<36:21, 44.52s/it]

[I 2025-12-01 15:16:18,458] Trial 2 finished with value: 0.4989130434782609 and parameters: {'max_depth': 10, 'learning_rate': 0.05350133903078539, 'n_estimators': 233, 'subsample': 0.5818948577672767, 'colsample_bytree': 0.6398153765044493, 'min_child_weight': 5, 'gamma': 1.7866867707119298, 'reg_alpha': 9.443178837478057e-05, 'reg_lambda': 9.187377692491501e-06, 'max_delta_step': 3}. Best is trial 2 with value: 0.4989130434782609.

Best trial: 3. Best value: 0.61413:   4%|▍         | 2/50 [01:24<33:34, 41.96s/it]

[I 2025-12-01 15:16:58,628] Trial 3 finished with value: 0.6141304347826086 and parameters: {'max_depth': 5, 'learning_rate': 0.013108558733196727, 'n_estimators': 716, 'subsample': 0.8628781529455458, 'colsample_bytree': 0.5279320484102688, 'min_child_weight': 6, 'gamma': 3.872793576055631, 'reg_alpha': 0.010813703268682787, 'reg_lambda': 2.2924834394656717, 'max_delta_step': 0}. Best is trial 3 with value: 0.6141304347826086.

Best trial: 3. Best value: 0.61413:   6%|▌         | 3/50 [01:40<23:37, 30.15s/it]

[I 2025-12-01 15:17:14,723] Trial 1 finished with value: 0.5891304347826087 and parameters: {'max_depth': 6, 'learning_rate': 0.11150330598583368, 'n_estimators': 1270, 'subsample': 0.8431438716240423, 'colsample_bytree': 0.9145890806328474, 'min_child_weight': 6, 'gamma': 2.9607643020557326, 'reg_alpha': 1.6862571896483538e-06, 'reg_lambda': 4.002560871332922e-05, 'max_delta_step': 0}. Best is trial 3 with value: 0.6141304347826086.

Best trial: 3. Best value: 0.61413:   8%|▊         | 4/50 [02:02<20:42, 27.01s/it]

[I 2025-12-01 15:17:36,927] Trial 0 finished with value: 0.6141304347826086 and parameters: {'max_depth': 6, 'learning_rate': 0.02994253219349439, 'n_estimators': 1233, 'subsample': 0.9586950899596662, 'colsample_bytree': 0.5403298908439229, 'min_child_weight': 3, 'gamma': 2.707360781552308, 'reg_alpha': 0.0001840617217456366, 'reg_lambda': 0.016377187417201247, 'max_delta_step': 4}. Best is trial 3 with value: 0.6141304347826086.

Best trial: 3. Best value: 0.61413:  10%|█         | 5/50 [02:15<16:14, 21.67s/it]

[I 2025-12-01 15:17:49,114] Trial 5 finished with value: 0.4706521739130435 and parameters: {'max_depth': 9, 'learning_rate': 0.019385548925799134, 'n_estimators': 852, 'subsample': 0.6689077894507817, 'colsample_bytree': 0.559377617940928, 'min_child_weight': 8, 'gamma': 0.9431302445296613, 'reg_alpha': 6.157021108750304e-08, 'reg_lambda': 0.10943365185117922, 'max_delta_step': 5}. Best is trial 3 with value: 0.6141304347826086.

Best trial: 3. Best value: 0.61413:  12%|█▏        | 6/50 [02:44<17:48, 24.28s/it]

[I 2025-12-01 15:18:18,483] Trial 7 finished with value: 0.5706521739130435 and parameters: {'max_depth': 3, 'learning_rate': 0.2527756844702966, 'n_estimators': 610, 'subsample': 0.9090625958478167, 'colsample_bytree': 0.7087127338235815, 'min_child_weight': 5, 'gamma': 0.3169114781459198, 'reg_alpha': 0.06875885174269075, 'reg_lambda': 3.260255319338096e-08, 'max_delta_step': 10}. Best is trial 3 with value: 0.6141304347826086.

Best trial: 3. Best value: 0.61413:  14%|█▍        | 7/50 [03:01<15:40, 21.86s/it]

[I 2025-12-01 15:18:35,362] Trial 6 finished with value: 0.2608695652173913 and parameters: {'max_depth': 6, 'learning_rate': 0.06998925762137394, 'n_estimators': 1284, 'subsample': 0.705151197082389, 'colsample_bytree': 0.8531249094093734, 'min_child_weight': 9, 'gamma': 2.6405467476643816, 'reg_alpha': 5.81705494360714e-07, 'reg_lambda': 0.22931769162414167, 'max_delta_step': 0}. Best is trial 3 with value: 0.6141304347826086.

Best trial: 3. Best value: 0.61413:  16%|█▌        | 8/50 [03:18<14:20, 20.48s/it]

[I 2025-12-01 15:18:52,877] Trial 8 finished with value: 0.5114130434782609 and parameters: {'max_depth': 4, 'learning_rate': 0.027984678389104928, 'n_estimators': 864, 'subsample': 0.7251157344497965, 'colsample_bytree': 0.8514997971134373, 'min_child_weight': 7, 'gamma': 1.1275060991188501, 'reg_alpha': 0.0010432560950889903, 'reg_lambda': 0.8539670882044681, 'max_delta_step': 9}. Best is trial 3 with value: 0.6141304347826086.

Best trial: 3. Best value: 0.61413:  18%|█▊        | 9/50 [03:52<16:47, 24.58s/it]

[I 2025-12-01 15:19:26,448] Trial 11 finished with value: 0.4706521739130435 and parameters: {'max_depth': 8, 'learning_rate': 0.21837976435577647, 'n_estimators': 446, 'subsample': 0.6995740278458222, 'colsample_bytree': 0.793577593782474, 'min_child_weight': 7, 'gamma': 0.9839515532762705, 'reg_alpha': 3.377266615435854, 'reg_lambda': 1.116324320477412e-08, 'max_delta_step': 1}. Best is trial 3 with value: 0.6141304347826086.

Best trial: 9. Best value: 0.62663:  20%|██        | 10/50 [04:07<14:29, 21.74s/it]

[I 2025-12-01 15:19:41,861] Trial 9 finished with value: 0.6266304347826087 and parameters: {'max_depth': 8, 'learning_rate': 0.0247941283023142, 'n_estimators': 850, 'subsample': 0.9674342735850923, 'colsample_bytree': 0.9693050694044767, 'min_child_weight': 6, 'gamma': 2.0642410552388695, 'reg_alpha': 6.490226376039669e-08, 'reg_lambda': 0.002201490943972385, 'max_delta_step': 4}. Best is trial 9 with value: 0.6266304347826087.

Best trial: 9. Best value: 0.62663:  22%|██▏       | 11/50 [04:17<11:40, 17.96s/it]

[I 2025-12-01 15:19:51,252] Trial 10 pruned.

Best trial: 9. Best value: 0.62663:  24%|██▍       | 12/50 [04:56<15:23, 24.32s/it]

[I 2025-12-01 15:20:30,100] Trial 4 finished with value: 0.6048913043478261 and parameters: {'max_depth': 6, 'learning_rate': 0.016425500612721335, 'n_estimators': 1426, 'subsample': 0.7795581711786475, 'colsample_bytree': 0.8788115571924869, 'min_child_weight': 1, 'gamma': 1.8457590659757128, 'reg_alpha': 8.366441655018358e-07, 'reg_lambda': 2.332557444700971, 'max_delta_step': 1}. Best is trial 9 with value: 0.6266304347826087.

Best trial: 9. Best value: 0.62663:  26%|██▌       | 13/50 [05:16<14:18, 23.19s/it]

[I 2025-12-01 15:20:50,708] Trial 15 pruned.

Best trial: 12. Best value: 0.63913:  28%|██▊       | 14/50 [05:23<10:51, 18.09s/it]

[I 2025-12-01 15:20:56,882] Trial 12 finished with value: 0.6391304347826088 and parameters: {'max_depth': 7, 'learning_rate': 0.017400967082570506, 'n_estimators': 673, 'subsample': 0.8824408546853488, 'colsample_bytree': 0.8900433253671831, 'min_child_weight': 5, 'gamma': 1.0009370198623806, 'reg_alpha': 0.035945857334246704, 'reg_lambda': 0.04470277343539222, 'max_delta_step': 10}. Best is trial 12 with value: 0.6391304347826088.

Best trial: 12. Best value: 0.63913:  30%|███       | 15/50 [06:36<20:16, 34.76s/it]

[I 2025-12-01 15:22:10,413] Trial 14 finished with value: 0.5766304347826088 and parameters: {'max_depth': 8, 'learning_rate': 0.03265412311943035, 'n_estimators': 1010, 'subsample': 0.9899713587634206, 'colsample_bytree': 0.9676959283623113, 'min_child_weight': 2, 'gamma': 4.889332400690542, 'reg_alpha': 1.0876094741766096e-08, 'reg_lambda': 0.003535705185884593, 'max_delta_step': 5}. Best is trial 12 with value: 0.6391304347826088.

Best trial: 12. Best value: 0.63913:  32%|███▏      | 16/50 [06:51<16:19, 28.82s/it]

[I 2025-12-01 15:22:25,425] Trial 17 finished with value: 0.5581521739130435 and parameters: {'max_depth': 8, 'learning_rate': 0.010109300158662952, 'n_estimators': 580, 'subsample': 0.9274393374475703, 'colsample_bytree': 0.9981027853741019, 'min_child_weight': 4, 'gamma': 4.886400273020138, 'reg_alpha': 1.1464188571860746e-08, 'reg_lambda': 0.009238033042912881, 'max_delta_step': 7}. Best is trial 12 with value: 0.6391304347826088.

Best trial: 12. Best value: 0.63913:  34%|███▍      | 17/50 [06:53<11:25, 20.78s/it]

[I 2025-12-01 15:22:27,502] Trial 16 finished with value: 0.6141304347826086 and parameters: {'max_depth': 8, 'learning_rate': 0.03078187877785729, 'n_estimators': 1020, 'subsample': 0.9890335205996614, 'colsample_bytree': 0.656682082187434, 'min_child_weight': 3, 'gamma': 2.1348770657705263, 'reg_alpha': 1.1506802051161895e-08, 'reg_lambda': 0.00857197707531564, 'max_delta_step': 3}. Best is trial 12 with value: 0.6391304347826088.

Best trial: 12. Best value: 0.63913:  36%|███▌      | 18/50 [06:58<08:28, 15.88s/it]

[I 2025-12-01 15:22:31,985] Trial 20 pruned.

Best trial: 12. Best value: 0.63913:  38%|███▊      | 19/50 [07:17<08:47, 17.00s/it]

[I 2025-12-01 15:22:51,609] Trial 13 finished with value: 0.5983695652173913 and parameters: {'max_depth': 8, 'learning_rate': 0.012462032338180998, 'n_estimators': 1038, 'subsample': 0.9983450275116637, 'colsample_bytree': 0.9923433097259614, 'min_child_weight': 1, 'gamma': 4.879444240206967, 'reg_alpha': 1.0887852847013352e-08, 'reg_lambda': 0.0011370398224018194, 'max_delta_step': 7}. Best is trial 12 with value: 0.6391304347826088.

Best trial: 12. Best value: 0.63913:  40%|████      | 20/50 [07:54<11:25, 22.86s/it]

[I 2025-12-01 15:23:28,124] Trial 19 finished with value: 0.629891304347826 and parameters: {'max_depth': 7, 'learning_rate': 0.021414694930428267, 'n_estimators': 376, 'subsample': 0.8178352565965105, 'colsample_bytree': 0.9165147621068324, 'min_child_weight': 4, 'gamma': 1.9389078875558727, 'reg_alpha': 0.0940445342351273, 'reg_lambda': 9.430258952291381e-05, 'max_delta_step': 7}. Best is trial 12 with value: 0.6391304347826088.

Best trial: 12. Best value: 0.63913:  42%|████▏     | 21/50 [07:54<07:48, 16.16s/it]

[I 2025-12-01 15:23:28,664] Trial 21 finished with value: 0.5766304347826088 and parameters: {'max_depth': 7, 'learning_rate': 0.05175634305898725, 'n_estimators': 696, 'subsample': 0.8868854814514001, 'colsample_bytree': 0.9373914829022971, 'min_child_weight': 7, 'gamma': 1.3362659826732766, 'reg_alpha': 8.144453158551816e-06, 'reg_lambda': 1.4633973649203161e-06, 'max_delta_step': 7}. Best is trial 12 with value: 0.6391304347826088.

Best trial: 18. Best value: 0.65163:  44%|████▍     | 22/50 [08:14<08:03, 17.28s/it]

[I 2025-12-01 15:23:48,547] Trial 18 finished with value: 0.6516304347826087 and parameters: {'max_depth': 7, 'learning_rate': 0.011830474661553106, 'n_estimators': 531, 'subsample': 0.8144054490876111, 'colsample_bytree': 0.934674820116489, 'min_child_weight': 4, 'gamma': 0.10050046145816105, 'reg_alpha': 0.21538201000036328, 'reg_lambda': 7.914493875654964e-05, 'max_delta_step': 7}. Best is trial 18 with value: 0.6516304347826087.

Best trial: 18. Best value: 0.65163:  46%|████▌     | 23/50 [08:23<06:34, 14.61s/it]

[I 2025-12-01 15:23:56,946] Trial 22 finished with value: 0.6483695652173913 and parameters: {'max_depth': 7, 'learning_rate': 0.05067989688494802, 'n_estimators': 718, 'subsample': 0.8862590557233183, 'colsample_bytree': 0.9262164459410944, 'min_child_weight': 4, 'gamma': 1.4690311881698819, 'reg_alpha': 9.631367300198895e-06, 'reg_lambda': 1.6648173476630354e-06, 'max_delta_step': 10}. Best is trial 18 with value: 0.6516304347826087.

Best trial: 18. Best value: 0.65163:  48%|████▊     | 24/50 [08:32<05:41, 13.13s/it]

[I 2025-12-01 15:24:06,623] Trial 23 finished with value: 0.6266304347826087 and parameters: {'max_depth': 7, 'learning_rate': 0.05433601676715388, 'n_estimators': 298, 'subsample': 0.886646659094486, 'colsample_bytree': 0.8111889835554903, 'min_child_weight': 4, 'gamma': 1.40497738738826, 'reg_alpha': 0.26364991713626207, 'reg_lambda': 1.56241282920933e-06, 'max_delta_step': 10}. Best is trial 18 with value: 0.6516304347826087.

Best trial: 18. Best value: 0.65163:  50%|█████     | 25/50 [08:44<05:15, 12.62s/it]

[I 2025-12-01 15:24:18,064] Trial 24 finished with value: 0.6173913043478261 and parameters: {'max_depth': 7, 'learning_rate': 0.019845633809136582, 'n_estimators': 258, 'subsample': 0.7914985707269926, 'colsample_bytree': 0.8844671527962802, 'min_child_weight': 4, 'gamma': 2.168656735535726, 'reg_alpha': 0.004409622223262792, 'reg_lambda': 1.222936562023361e-06, 'max_delta_step': 10}. Best is trial 18 with value: 0.6516304347826087.

Best trial: 18. Best value: 0.65163:  52%|█████▏    | 26/50 [09:26<08:39, 21.65s/it]

[I 2025-12-01 15:25:00,763] Trial 25 finished with value: 0.629891304347826 and parameters: {'max_depth': 7, 'learning_rate': 0.015050392444375832, 'n_estimators': 396, 'subsample': 0.7773984322237334, 'colsample_bytree': 0.8020217574627133, 'min_child_weight': 4, 'gamma': 0.5320639307922104, 'reg_alpha': 0.47314530651451314, 'reg_lambda': 1.0211936351493825e-06, 'max_delta_step': 10}. Best is trial 18 with value: 0.6516304347826087.

Best trial: 18. Best value: 0.65163:  54%|█████▍    | 27/50 [09:33<06:31, 17.01s/it]

[I 2025-12-01 15:25:06,943] Trial 28 finished with value: 0.5798913043478261 and parameters: {'max_depth': 5, 'learning_rate': 0.014610749675713675, 'n_estimators': 509, 'subsample': 0.5073832329039579, 'colsample_bytree': 0.7632926241561021, 'min_child_weight': 5, 'gamma': 0.7219640025539109, 'reg_alpha': 0.012586326737238487, 'reg_lambda': 2.1668179646802785e-07, 'max_delta_step': 9}. Best is trial 18 with value: 0.6516304347826087.

Best trial: 18. Best value: 0.65163:  56%|█████▌    | 28/50 [09:46<05:48, 15.85s/it]

[I 2025-12-01 15:25:20,082] Trial 27 finished with value: 0.6016304347826087 and parameters: {'max_depth': 5, 'learning_rate': 0.014401401679261619, 'n_estimators': 523, 'subsample': 0.7773313213992555, 'colsample_bytree': 0.870215151243405, 'min_child_weight': 5, 'gamma': 0.5589475271372857, 'reg_alpha': 0.0029895742569383548, 'reg_lambda': 4.90915455365301e-07, 'max_delta_step': 9}. Best is trial 18 with value: 0.6516304347826087.

Best trial: 18. Best value: 0.65163:  58%|█████▊    | 29/50 [09:53<04:41, 13.43s/it]

[I 2025-12-01 15:25:27,861] Trial 26 finished with value: 0.6048913043478261 and parameters: {'max_depth': 7, 'learning_rate': 0.010089610816662691, 'n_estimators': 511, 'subsample': 0.7693768429536796, 'colsample_bytree': 0.7910126981754427, 'min_child_weight': 4, 'gamma': 0.6008122794927634, 'reg_alpha': 0.0024679015091968394, 'reg_lambda': 2.2671639727022515e-07, 'max_delta_step': 10}. Best is trial 18 with value: 0.6516304347826087.

Best trial: 18. Best value: 0.65163:  60%|██████    | 30/50 [10:04<04:09, 12.49s/it]

[I 2025-12-01 15:25:38,180] Trial 32 pruned.

Best trial: 18. Best value: 0.65163:  62%|██████▏   | 31/50 [10:16<03:57, 12.52s/it]

[I 2025-12-01 15:25:50,772] Trial 29 finished with value: 0.6266304347826087 and parameters: {'max_depth': 5, 'learning_rate': 0.07564917143194518, 'n_estimators': 518, 'subsample': 0.5081834206618789, 'colsample_bytree': 0.8487803405036108, 'min_child_weight': 2, 'gamma': 0.6560778162986642, 'reg_alpha': 0.017268579510287905, 'reg_lambda': 9.830192011313895e-08, 'max_delta_step': 9}. Best is trial 18 with value: 0.6516304347826087.

Best trial: 18. Best value: 0.65163:  64%|██████▍   | 32/50 [11:32<09:26, 31.46s/it]

[I 2025-12-01 15:27:06,409] Trial 34 finished with value: 0.6048913043478261 and parameters: {'max_depth': 9, 'learning_rate': 0.04095286333112905, 'n_estimators': 647, 'subsample': 0.8323271477786743, 'colsample_bytree': 0.9034635085240413, 'min_child_weight': 3, 'gamma': 1.53742357079082, 'reg_alpha': 1.3146837003006795, 'reg_lambda': 0.00019082589624147106, 'max_delta_step': 6}. Best is trial 18 with value: 0.6516304347826087.

Best trial: 18. Best value: 0.65163:  66%|██████▌   | 33/50 [11:33<06:18, 22.29s/it]

[I 2025-12-01 15:27:07,318] Trial 33 finished with value: 0.6173913043478261 and parameters: {'max_depth': 9, 'learning_rate': 0.042686722766646285, 'n_estimators': 767, 'subsample': 0.8550053122868458, 'colsample_bytree': 0.7255225838574514, 'min_child_weight': 2, 'gamma': 1.5250328702413398, 'reg_alpha': 1.2793591379706992, 'reg_lambda': 0.03179302752070856, 'max_delta_step': 8}. Best is trial 18 with value: 0.6516304347826087.

Best trial: 18. Best value: 0.65163:  68%|██████▊   | 34/50 [12:21<08:02, 30.14s/it]

[I 2025-12-01 15:27:55,750] Trial 36 finished with value: 0.5891304347826087 and parameters: {'max_depth': 6, 'learning_rate': 0.02370736503117077, 'n_estimators': 333, 'subsample': 0.815586835368319, 'colsample_bytree': 0.9476308264160811, 'min_child_weight': 6, 'gamma': 2.431830299060143, 'reg_alpha': 2.8052604819702583e-05, 'reg_lambda': 1.2695675175364634e-05, 'max_delta_step': 6}. Best is trial 18 with value: 0.6516304347826087.

Best trial: 18. Best value: 0.65163:  70%|███████   | 35/50 [12:30<05:53, 23.59s/it]

[I 2025-12-01 15:28:04,057] Trial 35 finished with value: 0.6266304347826087 and parameters: {'max_depth': 6, 'learning_rate': 0.024888674300229105, 'n_estimators': 343, 'subsample': 0.8420312704957843, 'colsample_bytree': 0.9439794312080977, 'min_child_weight': 5, 'gamma': 0.01871507767356806, 'reg_alpha': 1.8923056809133588e-05, 'reg_lambda': 3.33054182897523e-05, 'max_delta_step': 8}. Best is trial 18 with value: 0.6516304347826087.

Best trial: 18. Best value: 0.65163:  72%|███████▏  | 36/50 [12:57<05:44, 24.61s/it]

[I 2025-12-01 15:28:31,066] Trial 31 finished with value: 0.6048913043478261 and parameters: {'max_depth': 9, 'learning_rate': 0.010079977338384052, 'n_estimators': 724, 'subsample': 0.8477744970809817, 'colsample_bytree': 0.944115610540929, 'min_child_weight': 2, 'gamma': 1.3540724708440428, 'reg_alpha': 1.236367703895964, 'reg_lambda': 1.3267579087545886e-05, 'max_delta_step': 8}. Best is trial 18 with value: 0.6516304347826087.

Best trial: 18. Best value: 0.65163:  74%|███████▍  | 37/50 [13:01<04:02, 18.63s/it]

[I 2025-12-01 15:28:35,728] Trial 38 finished with value: 0.6266304347826087 and parameters: {'max_depth': 7, 'learning_rate': 0.122656081928868, 'n_estimators': 200, 'subsample': 0.8846526037788446, 'colsample_bytree': 0.9115478190219298, 'min_child_weight': 3, 'gamma': 2.995657475133651, 'reg_alpha': 0.1028290147621884, 'reg_lambda': 0.000435491391952367, 'max_delta_step': 6}. Best is trial 18 with value: 0.6516304347826087.

Best trial: 18. Best value: 0.65163:  76%|███████▌  | 38/50 [13:04<02:44, 13.71s/it]

[I 2025-12-01 15:28:37,950] Trial 37 finished with value: 0.6266304347826087 and parameters: {'max_depth': 7, 'learning_rate': 0.12311176475513515, 'n_estimators': 438, 'subsample': 0.8766945043729695, 'colsample_bytree': 0.9044047919779361, 'min_child_weight': 5, 'gamma': 1.8038948677350612, 'reg_alpha': 8.786564337985531e-06, 'reg_lambda': 4.0845352612305924e-05, 'max_delta_step': 6}. Best is trial 18 with value: 0.6516304347826087.

Best trial: 18. Best value: 0.65163:  78%|███████▊  | 39/50 [13:05<01:49,  9.93s/it]

[I 2025-12-01 15:28:39,079] Trial 30 finished with value: 0.6048913043478261 and parameters: {'max_depth': 9, 'learning_rate': 0.01018388865637477, 'n_estimators': 726, 'subsample': 0.8495644107460758, 'colsample_bytree': 0.8514781533791944, 'min_child_weight': 2, 'gamma': 0.0032922417294841827, 'reg_alpha': 1.2565900701349642, 'reg_lambda': 1.0040727916520948e-05, 'max_delta_step': 9}. Best is trial 18 with value: 0.6516304347826087.

Best trial: 18. Best value: 0.65163:  80%|████████  | 40/50 [14:02<04:00, 24.03s/it]

[I 2025-12-01 15:29:36,008] Trial 41 pruned.

Best trial: 18. Best value: 0.65163:  82%|████████▏ | 41/50 [15:37<06:48, 45.33s/it]

[I 2025-12-01 15:31:11,047] Trial 43 finished with value: 0.5766304347826088 and parameters: {'max_depth': 6, 'learning_rate': 0.0177860917392031, 'n_estimators': 626, 'subsample': 0.745847164797317, 'colsample_bytree': 0.9664973066999665, 'min_child_weight': 6, 'gamma': 1.1720001038252787, 'reg_alpha': 0.00027762043496896207, 'reg_lambda': 0.052290089876278006, 'max_delta_step': 3}. Best is trial 18 with value: 0.6516304347826087.

Best trial: 18. Best value: 0.65163:  84%|████████▍ | 42/50 [15:53<04:54, 36.79s/it]

[I 2025-12-01 15:31:27,903] Trial 44 pruned.

Best trial: 40. Best value: 0.67337:  86%|████████▌ | 43/50 [16:01<03:15, 27.99s/it]

[I 2025-12-01 15:31:35,359] Trial 40 finished with value: 0.6733695652173912 and parameters: {'max_depth': 6, 'learning_rate': 0.017424565152638762, 'n_estimators': 948, 'subsample': 0.9207611782282246, 'colsample_bytree': 0.8907558834510986, 'min_child_weight': 4, 'gamma': 1.8336691090042923, 'reg_alpha': 0.028799886808028495, 'reg_lambda': 5.094324909876611e-06, 'max_delta_step': 9}. Best is trial 40 with value: 0.6733695652173912.

Best trial: 40. Best value: 0.67337:  88%|████████▊ | 44/50 [16:01<01:58, 19.73s/it]

[I 2025-12-01 15:31:35,823] Trial 42 finished with value: 0.6391304347826088 and parameters: {'max_depth': 6, 'learning_rate': 0.01788969981007902, 'n_estimators': 926, 'subsample': 0.9175669166526097, 'colsample_bytree': 0.8839640434538353, 'min_child_weight': 4, 'gamma': 1.085131390817926, 'reg_alpha': 0.000521542862595706, 'reg_lambda': 0.032082213120727704, 'max_delta_step': 4}. Best is trial 40 with value: 0.6733695652173912.

Best trial: 40. Best value: 0.67337:  90%|█████████ | 45/50 [16:16<01:30, 18.06s/it]

[I 2025-12-01 15:31:49,974] Trial 39 finished with value: 0.592391304347826 and parameters: {'max_depth': 7, 'learning_rate': 0.017237265129478922, 'n_estimators': 936, 'subsample': 0.8798411516190804, 'colsample_bytree': 0.9099639319156705, 'min_child_weight': 3, 'gamma': 1.8039071672734546, 'reg_alpha': 0.0396428122349213, 'reg_lambda': 7.060398954854387e-05, 'max_delta_step': 6}. Best is trial 40 with value: 0.6733695652173912.

Best trial: 40. Best value: 0.67337:  92%|█████████▏| 46/50 [16:24<01:00, 15.24s/it]

[I 2025-12-01 15:31:58,635] Trial 46 pruned.

Best trial: 40. Best value: 0.67337:  94%|█████████▍| 47/50 [18:12<02:09, 43.16s/it]

[I 2025-12-01 15:33:46,930] Trial 49 finished with value: 0.6733695652173912 and parameters: {'max_depth': 4, 'learning_rate': 0.09777977016380336, 'n_estimators': 1162, 'subsample': 0.9120647158328599, 'colsample_bytree': 0.5574178829202162, 'min_child_weight': 5, 'gamma': 0.9206421248084787, 'reg_alpha': 0.0008037491249027859, 'reg_lambda': 0.2606620882539958, 'max_delta_step': 4}. Best is trial 40 with value: 0.6733695652173912.

Best trial: 40. Best value: 0.67337:  96%|█████████▌| 48/50 [18:26<01:08, 34.24s/it]

[I 2025-12-01 15:34:00,369] Trial 45 finished with value: 0.629891304347826 and parameters: {'max_depth': 7, 'learning_rate': 0.014799933406643397, 'n_estimators': 810, 'subsample': 0.742947396370859, 'colsample_bytree': 0.5778361372912918, 'min_child_weight': 3, 'gamma': 0.4597447478274605, 'reg_alpha': 0.3623609621656216, 'reg_lambda': 5.233103880661561e-05, 'max_delta_step': 10}. Best is trial 40 with value: 0.6733695652173912.

Best trial: 40. Best value: 0.67337:  98%|█████████▊| 49/50 [18:56<00:33, 33.11s/it]

[I 2025-12-01 15:34:30,839] Trial 47 finished with value: 0.592391304347826 and parameters: {'max_depth': 6, 'learning_rate': 0.012252745577911674, 'n_estimators': 1110, 'subsample': 0.9448721255766227, 'colsample_bytree': 0.5639429925618583, 'min_child_weight': 3, 'gamma': 1.6690730565627794, 'reg_alpha': 0.025396333228962543, 'reg_lambda': 0.4497159600846176, 'max_delta_step': 4}. Best is trial 40 with value: 0.6733695652173912.

Best trial: 40. Best value: 0.67337: 100%|██████████| 50/50 [19:04<00:00, 22.89s/it]

[I 2025-12-01 15:34:38,200] Trial 48 finished with value: 0.6391304347826088 and parameters: {'max_depth': 4, 'learning_rate': 0.012785191777302187, 'n_estimators': 1126, 'subsample': 0.944823271927647, 'colsample_bytree': 0.8749204454928893, 'min_child_weight': 5, 'gamma': 0.8335578942065143, 'reg_alpha': 1.3306592185901839e-06, 'reg_lambda': 0.5864379987045877, 'max_delta_step': 4}. Best is trial 40 with value: 0.6733695652173912.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 15:34:46,964] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 66, Test size: 17
Using Leave-One-Out CV with 66 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.392683:   2%|▏         | 1/50 [00:42<34:52, 42.70s/it]

[I 2025-12-01 15:35:29,648] Trial 2 finished with value: 0.3926829268292683 and parameters: {'max_depth': 5, 'learning_rate': 0.013924920504050411, 'n_estimators': 246, 'subsample': 0.8307017742654486, 'colsample_bytree': 0.7720641042240872, 'min_child_weight': 8, 'gamma': 4.404546645073205, 'reg_alpha': 3.566853381885392, 'reg_lambda': 0.0026293218551127298, 'max_delta_step': 7}. Best is trial 2 with value: 0.3926829268292683.

Best trial: 3. Best value: 0.533659:   4%|▍         | 2/50 [01:13<28:46, 35.97s/it]

[I 2025-12-01 15:36:00,912] Trial 3 finished with value: 0.5336585365853659 and parameters: {'max_depth': 10, 'learning_rate': 0.08165912768272823, 'n_estimators': 589, 'subsample': 0.8279474957472247, 'colsample_bytree': 0.7523703918201275, 'min_child_weight': 5, 'gamma': 2.5373425566897154, 'reg_alpha': 2.103382510139167e-06, 'reg_lambda': 2.0773551659086035e-08, 'max_delta_step': 3}. Best is trial 3 with value: 0.5336585365853659.

Best trial: 3. Best value: 0.533659:   6%|▌         | 3/50 [02:06<34:15, 43.73s/it]

[I 2025-12-01 15:36:53,865] Trial 1 finished with value: 0.3097560975609756 and parameters: {'max_depth': 5, 'learning_rate': 0.03104502198403461, 'n_estimators': 1444, 'subsample': 0.7169430930256523, 'colsample_bytree': 0.6687041603856053, 'min_child_weight': 9, 'gamma': 0.44690331804170813, 'reg_alpha': 0.0006159181426022362, 'reg_lambda': 0.651574391430494, 'max_delta_step': 0}. Best is trial 3 with value: 0.5336585365853659.

Best trial: 3. Best value: 0.533659:   8%|▊         | 4/50 [02:24<25:31, 33.29s/it]

[I 2025-12-01 15:37:11,162] Trial 0 finished with value: 0.4970731707317073 and parameters: {'max_depth': 5, 'learning_rate': 0.13753379498692647, 'n_estimators': 1195, 'subsample': 0.9664936724896744, 'colsample_bytree': 0.8269552636722552, 'min_child_weight': 6, 'gamma': 4.225206749098388, 'reg_alpha': 2.2614727321409514e-05, 'reg_lambda': 0.00397023155503604, 'max_delta_step': 5}. Best is trial 3 with value: 0.5336585365853659.

Best trial: 3. Best value: 0.533659:  10%|█         | 5/50 [02:37<19:34, 26.11s/it]

[I 2025-12-01 15:37:24,532] Trial 4 finished with value: 0.4448780487804878 and parameters: {'max_depth': 7, 'learning_rate': 0.12473385348892795, 'n_estimators': 1225, 'subsample': 0.9201903207767264, 'colsample_bytree': 0.6949419381814468, 'min_child_weight': 7, 'gamma': 0.49807845578441423, 'reg_alpha': 0.0006161659977242399, 'reg_lambda': 4.000079588639925e-08, 'max_delta_step': 4}. Best is trial 3 with value: 0.5336585365853659.

Best trial: 3. Best value: 0.533659:  12%|█▏        | 6/50 [04:03<34:06, 46.51s/it]

[I 2025-12-01 15:38:50,659] Trial 5 finished with value: 0.5214634146341464 and parameters: {'max_depth': 3, 'learning_rate': 0.1503256360078508, 'n_estimators': 809, 'subsample': 0.8365099744254927, 'colsample_bytree': 0.9876190568390251, 'min_child_weight': 1, 'gamma': 4.967999427340647, 'reg_alpha': 0.021499245526371658, 'reg_lambda': 0.23098717575355435, 'max_delta_step': 8}. Best is trial 3 with value: 0.5336585365853659.

Best trial: 3. Best value: 0.533659:  14%|█▍        | 7/50 [04:46<32:26, 45.26s/it]

[I 2025-12-01 15:39:33,310] Trial 7 finished with value: 0.47268292682926827 and parameters: {'max_depth': 8, 'learning_rate': 0.11890280150212698, 'n_estimators': 1334, 'subsample': 0.5401323529594051, 'colsample_bytree': 0.7989875300589953, 'min_child_weight': 6, 'gamma': 1.2314110713492026, 'reg_alpha': 4.6033534769907565, 'reg_lambda': 5.307857781301182e-06, 'max_delta_step': 3}. Best is trial 3 with value: 0.5336585365853659.

Best trial: 3. Best value: 0.533659:  16%|█▌        | 8/50 [04:56<23:44, 33.93s/it]

[I 2025-12-01 15:39:42,996] Trial 6 finished with value: 0.5136585365853659 and parameters: {'max_depth': 4, 'learning_rate': 0.025503102921599415, 'n_estimators': 961, 'subsample': 0.8421362348701682, 'colsample_bytree': 0.5999333691243276, 'min_child_weight': 2, 'gamma': 0.8769075429684153, 'reg_alpha': 0.009142913533633579, 'reg_lambda': 4.774776287059493e-07, 'max_delta_step': 0}. Best is trial 3 with value: 0.5336585365853659.

Best trial: 3. Best value: 0.533659:  18%|█▊        | 9/50 [05:24<21:58, 32.17s/it]

[I 2025-12-01 15:40:11,303] Trial 8 finished with value: 0.4892682926829268 and parameters: {'max_depth': 4, 'learning_rate': 0.01764739551223098, 'n_estimators': 1324, 'subsample': 0.8163436909344208, 'colsample_bytree': 0.631916609773099, 'min_child_weight': 6, 'gamma': 4.207175859280568, 'reg_alpha': 0.001092448336821134, 'reg_lambda': 4.08038058352972e-05, 'max_delta_step': 10}. Best is trial 3 with value: 0.5336585365853659.

Best trial: 3. Best value: 0.533659:  20%|██        | 10/50 [06:27<27:43, 41.60s/it]

[I 2025-12-01 15:41:14,018] Trial 9 finished with value: 0.4970731707317073 and parameters: {'max_depth': 8, 'learning_rate': 0.04252937739740841, 'n_estimators': 1274, 'subsample': 0.676233354390653, 'colsample_bytree': 0.8549759567691273, 'min_child_weight': 5, 'gamma': 2.1067810568979994, 'reg_alpha': 2.4600656709968603e-08, 'reg_lambda': 0.7888900122822926, 'max_delta_step': 9}. Best is trial 3 with value: 0.5336585365853659.

Best trial: 3. Best value: 0.533659:  22%|██▏       | 11/50 [06:30<19:27, 29.94s/it]

[I 2025-12-01 15:41:17,512] Trial 12 pruned.

Best trial: 3. Best value: 0.533659:  24%|██▍       | 12/50 [06:32<13:35, 21.47s/it]

[I 2025-12-01 15:41:19,610] Trial 11 pruned.

Best trial: 13. Best value: 0.610244:  26%|██▌       | 13/50 [07:15<17:18, 28.07s/it]

[I 2025-12-01 15:42:02,887] Trial 13 finished with value: 0.6102439024390244 and parameters: {'max_depth': 10, 'learning_rate': 0.2894236483817044, 'n_estimators': 463, 'subsample': 0.6122783088457345, 'colsample_bytree': 0.5311977713588572, 'min_child_weight': 3, 'gamma': 2.933867980719233, 'reg_alpha': 5.487158612797057e-07, 'reg_lambda': 1.2080293921126268e-08, 'max_delta_step': 2}. Best is trial 13 with value: 0.6102439024390244.

Best trial: 13. Best value: 0.610244:  28%|██▊       | 14/50 [07:17<11:59, 19.98s/it]

[I 2025-12-01 15:42:04,177] Trial 10 finished with value: 0.5458536585365854 and parameters: {'max_depth': 9, 'learning_rate': 0.017228299408356473, 'n_estimators': 1071, 'subsample': 0.6582321997444671, 'colsample_bytree': 0.5256814139401689, 'min_child_weight': 3, 'gamma': 1.6295677229311167, 'reg_alpha': 2.8131877647542236e-05, 'reg_lambda': 0.0759574141771608, 'max_delta_step': 4}. Best is trial 13 with value: 0.6102439024390244.

Best trial: 13. Best value: 0.610244:  30%|███       | 15/50 [07:34<11:14, 19.28s/it]

[I 2025-12-01 15:42:21,841] Trial 17 pruned.

Best trial: 13. Best value: 0.610244:  32%|███▏      | 16/50 [07:53<10:53, 19.22s/it]

[I 2025-12-01 15:42:40,914] Trial 15 finished with value: 0.5414634146341464 and parameters: {'max_depth': 10, 'learning_rate': 0.28448375305203855, 'n_estimators': 676, 'subsample': 0.8966637189299552, 'colsample_bytree': 0.5339134303753224, 'min_child_weight': 3, 'gamma': 3.2288936086074727, 'reg_alpha': 0.0551593382060173, 'reg_lambda': 0.06009294917410456, 'max_delta_step': 2}. Best is trial 13 with value: 0.6102439024390244.

Best trial: 13. Best value: 0.610244:  34%|███▍      | 17/50 [08:03<08:56, 16.25s/it]

[I 2025-12-01 15:42:50,238] Trial 14 finished with value: 0.4892682926829268 and parameters: {'max_depth': 10, 'learning_rate': 0.22484587646159115, 'n_estimators': 674, 'subsample': 0.8871071649137972, 'colsample_bytree': 0.5275019438987838, 'min_child_weight': 3, 'gamma': 3.335382621111469, 'reg_alpha': 5.116969090224254e-07, 'reg_lambda': 6.960084472158389, 'max_delta_step': 2}. Best is trial 13 with value: 0.6102439024390244.

Best trial: 13. Best value: 0.610244:  36%|███▌      | 18/50 [08:04<06:17, 11.81s/it]

[I 2025-12-01 15:42:51,712] Trial 16 finished with value: 0.5814634146341464 and parameters: {'max_depth': 10, 'learning_rate': 0.2950843689030246, 'n_estimators': 449, 'subsample': 0.639174300737404, 'colsample_bytree': 0.5229141599637949, 'min_child_weight': 4, 'gamma': 3.045092884264805, 'reg_alpha': 1.5817868534845138e-07, 'reg_lambda': 2.751332352087945e-08, 'max_delta_step': 2}. Best is trial 13 with value: 0.6102439024390244.

Best trial: 13. Best value: 0.610244:  38%|███▊      | 19/50 [08:21<06:52, 13.29s/it]

[I 2025-12-01 15:43:08,469] Trial 21 pruned.

Best trial: 13. Best value: 0.610244:  40%|████      | 20/50 [09:04<11:02, 22.08s/it]

[I 2025-12-01 15:43:51,029] Trial 18 finished with value: 0.5058536585365854 and parameters: {'max_depth': 9, 'learning_rate': 0.28111745047991565, 'n_estimators': 906, 'subsample': 0.615989103662704, 'colsample_bytree': 0.5096745500846962, 'min_child_weight': 3, 'gamma': 3.279939728064723, 'reg_alpha': 4.4049252640805675e-07, 'reg_lambda': 8.986798324302907e-05, 'max_delta_step': 6}. Best is trial 13 with value: 0.6102439024390244.

Best trial: 13. Best value: 0.610244:  42%|████▏     | 21/50 [09:24<10:29, 21.71s/it]

[I 2025-12-01 15:44:11,871] Trial 22 finished with value: 0.5258536585365854 and parameters: {'max_depth': 8, 'learning_rate': 0.07173173224278437, 'n_estimators': 439, 'subsample': 0.7718305436692017, 'colsample_bytree': 0.6989422235861988, 'min_child_weight': 4, 'gamma': 2.912582958093368, 'reg_alpha': 1.1018049529506197e-05, 'reg_lambda': 7.038422177280047e-07, 'max_delta_step': 6}. Best is trial 13 with value: 0.6102439024390244.

Best trial: 13. Best value: 0.610244:  44%|████▍     | 22/50 [09:49<10:36, 22.72s/it]

[I 2025-12-01 15:44:36,941] Trial 19 finished with value: 0.5014634146341463 and parameters: {'max_depth': 9, 'learning_rate': 0.05215201540146857, 'n_estimators': 1018, 'subsample': 0.6080001450610993, 'colsample_bytree': 0.5616865752001199, 'min_child_weight': 4, 'gamma': 3.4263497735039614, 'reg_alpha': 2.7528563850738357e-07, 'reg_lambda': 8.849218157322012e-05, 'max_delta_step': 6}. Best is trial 13 with value: 0.6102439024390244.

Best trial: 13. Best value: 0.610244:  46%|████▌     | 23/50 [10:20<11:19, 25.16s/it]

[I 2025-12-01 15:45:07,754] Trial 23 finished with value: 0.5536585365853659 and parameters: {'max_depth': 8, 'learning_rate': 0.07575287852060472, 'n_estimators': 467, 'subsample': 0.7382642908623716, 'colsample_bytree': 0.6987979967844539, 'min_child_weight': 4, 'gamma': 3.848722535127843, 'reg_alpha': 9.995334393451307e-06, 'reg_lambda': 2.8445642156927987e-07, 'max_delta_step': 1}. Best is trial 13 with value: 0.6102439024390244.

Best trial: 13. Best value: 0.610244:  48%|████▊     | 24/50 [11:01<12:57, 29.90s/it]

[I 2025-12-01 15:45:48,753] Trial 20 finished with value: 0.5214634146341464 and parameters: {'max_depth': 9, 'learning_rate': 0.011431183318233255, 'n_estimators': 1038, 'subsample': 0.6144338975444168, 'colsample_bytree': 0.5820587921776326, 'min_child_weight': 4, 'gamma': 1.3918755777086949, 'reg_alpha': 1.8203842663464274e-05, 'reg_lambda': 0.000120661057579112, 'max_delta_step': 5}. Best is trial 13 with value: 0.6102439024390244.

Best trial: 26. Best value: 0.625854:  50%|█████     | 25/50 [11:24<11:36, 27.84s/it]

[I 2025-12-01 15:46:11,805] Trial 26 finished with value: 0.6258536585365854 and parameters: {'max_depth': 7, 'learning_rate': 0.18898384500964466, 'n_estimators': 390, 'subsample': 0.7442687817380886, 'colsample_bytree': 0.6377538569756722, 'min_child_weight': 2, 'gamma': 3.783266489553323, 'reg_alpha': 3.1780259048799667e-06, 'reg_lambda': 1.0035775283683155e-08, 'max_delta_step': 1}. Best is trial 26 with value: 0.6258536585365854.

Best trial: 26. Best value: 0.625854:  52%|█████▏    | 26/50 [12:03<12:23, 30.99s/it]

[I 2025-12-01 15:46:50,126] Trial 27 finished with value: 0.6258536585365854 and parameters: {'max_depth': 7, 'learning_rate': 0.1907741202062687, 'n_estimators': 391, 'subsample': 0.7471231742470927, 'colsample_bytree': 0.6380392531892114, 'min_child_weight': 2, 'gamma': 3.7734091728731385, 'reg_alpha': 9.73875812672082e-08, 'reg_lambda': 7.760884590789049e-08, 'max_delta_step': 1}. Best is trial 26 with value: 0.6258536585365854.

Best trial: 26. Best value: 0.625854:  54%|█████▍    | 27/50 [12:09<09:04, 23.66s/it]

[I 2025-12-01 15:46:56,704] Trial 28 finished with value: 0.5536585365853659 and parameters: {'max_depth': 7, 'learning_rate': 0.1807304540647087, 'n_estimators': 282, 'subsample': 0.5612453007963237, 'colsample_bytree': 0.6318270825684529, 'min_child_weight': 2, 'gamma': 2.2379076156821434, 'reg_alpha': 7.18119720537634e-08, 'reg_lambda': 1.3357286243881586e-08, 'max_delta_step': 1}. Best is trial 26 with value: 0.6258536585365854.

Best trial: 26. Best value: 0.625854:  56%|█████▌    | 28/50 [12:20<07:13, 19.69s/it]

[I 2025-12-01 15:47:07,115] Trial 24 finished with value: 0.578048780487805 and parameters: {'max_depth': 9, 'learning_rate': 0.011892218126054573, 'n_estimators': 1066, 'subsample': 0.6566666296796142, 'colsample_bytree': 0.5668416319736027, 'min_child_weight': 4, 'gamma': 1.5566928508949043, 'reg_alpha': 3.506922811611886e-05, 'reg_lambda': 4.4609279585021555e-08, 'max_delta_step': 4}. Best is trial 26 with value: 0.6258536585365854.

Best trial: 26. Best value: 0.625854:  58%|█████▊    | 29/50 [12:27<05:34, 15.92s/it]

[I 2025-12-01 15:47:14,235] Trial 30 pruned.

Best trial: 26. Best value: 0.625854:  60%|██████    | 30/50 [12:35<04:34, 13.75s/it]

[I 2025-12-01 15:47:22,916] Trial 31 pruned.

Best trial: 26. Best value: 0.625854:  62%|██████▏   | 31/50 [12:41<03:32, 11.18s/it]

[I 2025-12-01 15:47:28,124] Trial 25 finished with value: 0.5580487804878049 and parameters: {'max_depth': 9, 'learning_rate': 0.023986770296457006, 'n_estimators': 1127, 'subsample': 0.6677663177522406, 'colsample_bytree': 0.632595100089511, 'min_child_weight': 2, 'gamma': 1.3784071490337657, 'reg_alpha': 1.3283096312759388e-05, 'reg_lambda': 4.4579078478774564e-08, 'max_delta_step': 4}. Best is trial 26 with value: 0.6258536585365854.

Best trial: 26. Best value: 0.625854:  64%|██████▍   | 32/50 [13:04<04:28, 14.92s/it]

[I 2025-12-01 15:47:51,773] Trial 29 finished with value: 0.5414634146341464 and parameters: {'max_depth': 7, 'learning_rate': 0.19073440215696155, 'n_estimators': 327, 'subsample': 0.7783666749258675, 'colsample_bytree': 0.6544815232174247, 'min_child_weight': 2, 'gamma': 3.72892201521719, 'reg_alpha': 2.9458267103090628e-06, 'reg_lambda': 4.929068213841211e-06, 'max_delta_step': 1}. Best is trial 26 with value: 0.6258536585365854.

Best trial: 26. Best value: 0.625854:  66%|██████▌   | 33/50 [13:39<05:54, 20.84s/it]

[I 2025-12-01 15:48:26,429] Trial 33 pruned.

Best trial: 26. Best value: 0.625854:  68%|██████▊   | 34/50 [14:03<05:49, 21.82s/it]

[I 2025-12-01 15:48:50,544] Trial 34 finished with value: 0.5980487804878049 and parameters: {'max_depth': 7, 'learning_rate': 0.10236573160650819, 'n_estimators': 522, 'subsample': 0.7190684836984569, 'colsample_bytree': 0.5530750009235507, 'min_child_weight': 1, 'gamma': 2.932940468782035, 'reg_alpha': 1.0079567056745903e-07, 'reg_lambda': 1.228392556963216e-07, 'max_delta_step': 3}. Best is trial 26 with value: 0.6258536585365854.

Best trial: 26. Best value: 0.625854:  70%|███████   | 35/50 [14:05<03:55, 15.72s/it]

[I 2025-12-01 15:48:52,025] Trial 36 pruned.

Best trial: 26. Best value: 0.625854:  72%|███████▏  | 36/50 [14:09<02:54, 12.46s/it]

[I 2025-12-01 15:48:56,886] Trial 32 finished with value: 0.5258536585365854 and parameters: {'max_depth': 7, 'learning_rate': 0.10413094257672698, 'n_estimators': 550, 'subsample': 0.9860087671356315, 'colsample_bytree': 0.7313075331440918, 'min_child_weight': 1, 'gamma': 4.755265813751617, 'reg_alpha': 0.00010141391851029756, 'reg_lambda': 1.42321990697414e-07, 'max_delta_step': 3}. Best is trial 26 with value: 0.6258536585365854.

Best trial: 26. Best value: 0.625854:  74%|███████▍  | 37/50 [14:17<02:22, 10.95s/it]

[I 2025-12-01 15:49:04,303] Trial 35 finished with value: 0.5214634146341464 and parameters: {'max_depth': 7, 'learning_rate': 0.15336674393401428, 'n_estimators': 507, 'subsample': 0.7081061466281966, 'colsample_bytree': 0.553431728015177, 'min_child_weight': 1, 'gamma': 2.871562551418005, 'reg_alpha': 1.2591184603446073e-07, 'reg_lambda': 1.220168896893872e-07, 'max_delta_step': 3}. Best is trial 26 with value: 0.6258536585365854.

Best trial: 26. Best value: 0.625854:  76%|███████▌  | 38/50 [15:21<05:24, 27.04s/it]

[I 2025-12-01 15:50:08,857] Trial 38 pruned.

Best trial: 26. Best value: 0.625854:  78%|███████▊  | 39/50 [15:38<04:23, 24.00s/it]

[I 2025-12-01 15:50:25,771] Trial 39 pruned.

Best trial: 26. Best value: 0.625854:  80%|████████  | 40/50 [15:46<03:12, 19.22s/it]

[I 2025-12-01 15:50:33,866] Trial 41 pruned.

Best trial: 26. Best value: 0.625854:  82%|████████▏ | 41/50 [16:24<03:42, 24.69s/it]

[I 2025-12-01 15:51:11,291] Trial 40 finished with value: 0.40487804878048783 and parameters: {'max_depth': 6, 'learning_rate': 0.1378999823546637, 'n_estimators': 675, 'subsample': 0.7139936546431136, 'colsample_bytree': 0.6046259018212212, 'min_child_weight': 7, 'gamma': 2.4609088863859334, 'reg_alpha': 1.5038639055491753e-08, 'reg_lambda': 1.043955951434517e-08, 'max_delta_step': 1}. Best is trial 26 with value: 0.6258536585365854.

Best trial: 26. Best value: 0.625854:  84%|████████▍ | 42/50 [16:31<02:36, 19.54s/it]

[I 2025-12-01 15:51:18,805] Trial 37 finished with value: 0.5692682926829269 and parameters: {'max_depth': 6, 'learning_rate': 0.15322159044190234, 'n_estimators': 529, 'subsample': 0.7142546948189743, 'colsample_bytree': 0.6079659012024262, 'min_child_weight': 1, 'gamma': 4.235007067892727, 'reg_alpha': 3.923149184876276e-08, 'reg_lambda': 1.1610337996584008e-08, 'max_delta_step': 3}. Best is trial 26 with value: 0.6258536585365854.

Best trial: 26. Best value: 0.625854:  86%|████████▌ | 43/50 [16:35<01:44, 14.89s/it]

[I 2025-12-01 15:51:22,873] Trial 42 pruned.

Best trial: 26. Best value: 0.625854:  88%|████████▊ | 44/50 [16:39<01:08, 11.36s/it]

[I 2025-12-01 15:51:25,990] Trial 44 pruned.

Best trial: 26. Best value: 0.625854:  90%|█████████ | 45/50 [16:42<00:45,  9.03s/it]

[I 2025-12-01 15:51:29,573] Trial 45 pruned.

Best trial: 26. Best value: 0.625854:  92%|█████████▏| 46/50 [16:45<00:28,  7.05s/it]

[I 2025-12-01 15:51:31,984] Trial 46 pruned.

Best trial: 26. Best value: 0.625854:  94%|█████████▍| 47/50 [16:56<00:24,  8.24s/it]

[I 2025-12-01 15:51:43,023] Trial 47 pruned.

Best trial: 26. Best value: 0.625854:  96%|█████████▌| 48/50 [16:58<00:13,  6.57s/it]

[I 2025-12-01 15:51:45,714] Trial 43 finished with value: 0.5536585365853659 and parameters: {'max_depth': 8, 'learning_rate': 0.12352803858533382, 'n_estimators': 237, 'subsample': 0.8701039871608858, 'colsample_bytree': 0.7846844915139123, 'min_child_weight': 2, 'gamma': 4.442330846878432, 'reg_alpha': 1.0400118437666814e-06, 'reg_lambda': 1.485847945990251e-05, 'max_delta_step': 0}. Best is trial 26 with value: 0.6258536585365854.

Best trial: 26. Best value: 0.625854:  98%|█████████▊| 49/50 [17:00<00:05,  5.12s/it]

[I 2025-12-01 15:51:47,440] Trial 48 pruned.

Best trial: 26. Best value: 0.625854: 100%|██████████| 50/50 [17:14<00:00, 20.68s/it]

[I 2025-12-01 15:52:01,153] Trial 49 pruned.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 15:52:07,756] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 64, Test size: 16
Using Leave-One-Out CV with 64 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.204167:   2%|▏         | 1/50 [00:29<24:20, 29.81s/it]

[I 2025-12-01 15:52:37,552] Trial 2 finished with value: 0.20416666666666666 and parameters: {'max_depth': 6, 'learning_rate': 0.15294708469548565, 'n_estimators': 450, 'subsample': 0.5269183754987716, 'colsample_bytree': 0.666475371869657, 'min_child_weight': 10, 'gamma': 1.9271762540230197, 'reg_alpha': 1.214710004820551, 'reg_lambda': 5.47423020446307e-06, 'max_delta_step': 6}. Best is trial 2 with value: 0.20416666666666666.

Best trial: 1. Best value: 0.65:   4%|▍         | 2/50 [00:52<20:43, 25.90s/it]

[I 2025-12-01 15:53:00,706] Trial 1 finished with value: 0.65 and parameters: {'max_depth': 8, 'learning_rate': 0.2353332987141879, 'n_estimators': 704, 'subsample': 0.5926037314641934, 'colsample_bytree': 0.9060255336445959, 'min_child_weight': 4, 'gamma': 2.9435999765289855, 'reg_alpha': 7.85035882606629e-07, 'reg_lambda': 4.1695010965370266e-07, 'max_delta_step': 9}. Best is trial 1 with value: 0.65.

Best trial: 1. Best value: 0.65:   6%|▌         | 3/50 [01:48<30:51, 39.39s/it]

[I 2025-12-01 15:53:56,159] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.010129601020754836, 'n_estimators': 1281, 'subsample': 0.5375375848440385, 'colsample_bytree': 0.853724945128316, 'min_child_weight': 9, 'gamma': 3.7643167747571975, 'reg_alpha': 6.774475079177393e-05, 'reg_lambda': 0.23125536018491716, 'max_delta_step': 6}. Best is trial 1 with value: 0.65.

Best trial: 5. Best value: 0.7125:   8%|▊         | 4/50 [02:36<32:41, 42.64s/it]

[I 2025-12-01 15:54:43,769] Trial 5 finished with value: 0.7125 and parameters: {'max_depth': 6, 'learning_rate': 0.035384365613788514, 'n_estimators': 835, 'subsample': 0.9312929296113694, 'colsample_bytree': 0.6722651028604822, 'min_child_weight': 7, 'gamma': 1.9733840576904367, 'reg_alpha': 1.5876494916929362e-07, 'reg_lambda': 1.1077808788350218e-08, 'max_delta_step': 5}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  10%|█         | 5/50 [03:00<27:04, 36.11s/it]

[I 2025-12-01 15:55:08,299] Trial 0 finished with value: 0.6375 and parameters: {'max_depth': 3, 'learning_rate': 0.025695747385512925, 'n_estimators': 1452, 'subsample': 0.8505635565309172, 'colsample_bytree': 0.7679677815719386, 'min_child_weight': 4, 'gamma': 3.494475798440591, 'reg_alpha': 4.339577824639732e-06, 'reg_lambda': 0.005356923079327908, 'max_delta_step': 4}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  12%|█▏        | 6/50 [03:12<20:25, 27.85s/it]

[I 2025-12-01 15:55:20,139] Trial 4 finished with value: 0.6125 and parameters: {'max_depth': 7, 'learning_rate': 0.11438713727670383, 'n_estimators': 1147, 'subsample': 0.6608477795614534, 'colsample_bytree': 0.9907006035721291, 'min_child_weight': 1, 'gamma': 0.2583960055179879, 'reg_alpha': 3.915256611889276e-06, 'reg_lambda': 0.382459009368464, 'max_delta_step': 0}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  14%|█▍        | 7/50 [04:14<28:00, 39.07s/it]

[I 2025-12-01 15:56:22,305] Trial 6 finished with value: 0.175 and parameters: {'max_depth': 5, 'learning_rate': 0.1688403122145923, 'n_estimators': 1453, 'subsample': 0.701259045811788, 'colsample_bytree': 0.662619349191116, 'min_child_weight': 9, 'gamma': 3.366264874564015, 'reg_alpha': 0.47411732378764015, 'reg_lambda': 2.4548348441110615e-07, 'max_delta_step': 3}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  16%|█▌        | 8/50 [04:28<21:48, 31.15s/it]

[I 2025-12-01 15:56:36,504] Trial 7 finished with value: 0.5458333333333334 and parameters: {'max_depth': 6, 'learning_rate': 0.21361286892475223, 'n_estimators': 989, 'subsample': 0.7452578709892158, 'colsample_bytree': 0.9942980533168371, 'min_child_weight': 8, 'gamma': 2.584637905934091, 'reg_alpha': 0.0028527153827993704, 'reg_lambda': 0.00035136326936582797, 'max_delta_step': 0}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  18%|█▊        | 9/50 [04:53<20:01, 29.31s/it]

[I 2025-12-01 15:57:01,742] Trial 8 finished with value: 0.6166666666666667 and parameters: {'max_depth': 8, 'learning_rate': 0.06358174189145391, 'n_estimators': 1158, 'subsample': 0.8783960624806486, 'colsample_bytree': 0.6266131797442622, 'min_child_weight': 8, 'gamma': 0.7967478678927342, 'reg_alpha': 8.595507615488025e-05, 'reg_lambda': 1.6709620551612218e-06, 'max_delta_step': 10}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  20%|██        | 10/50 [05:20<18:52, 28.32s/it]

[I 2025-12-01 15:57:27,862] Trial 10 finished with value: 0.6833333333333333 and parameters: {'max_depth': 7, 'learning_rate': 0.14437352847259766, 'n_estimators': 624, 'subsample': 0.7415682057524271, 'colsample_bytree': 0.5625401537495065, 'min_child_weight': 6, 'gamma': 1.8536024956608492, 'reg_alpha': 1.6702632852740122e-05, 'reg_lambda': 2.800244228532253e-08, 'max_delta_step': 9}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  22%|██▏       | 11/50 [05:59<20:34, 31.64s/it]

[I 2025-12-01 15:58:07,042] Trial 13 finished with value: 0.6583333333333333 and parameters: {'max_depth': 10, 'learning_rate': 0.028383802143351455, 'n_estimators': 203, 'subsample': 0.9904250828643703, 'colsample_bytree': 0.7506895105759518, 'min_child_weight': 6, 'gamma': 4.853393829831166, 'reg_alpha': 1.4514788420450674e-08, 'reg_lambda': 3.6811505156064565e-05, 'max_delta_step': 2}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  24%|██▍       | 12/50 [06:09<15:56, 25.17s/it]

[I 2025-12-01 15:58:17,372] Trial 9 finished with value: 0.625 and parameters: {'max_depth': 10, 'learning_rate': 0.014755391654369487, 'n_estimators': 1177, 'subsample': 0.7759967709430096, 'colsample_bytree': 0.7032753725830216, 'min_child_weight': 4, 'gamma': 1.0298854115150846, 'reg_alpha': 0.00024694660224023376, 'reg_lambda': 2.892609728391109e-08, 'max_delta_step': 3}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  26%|██▌       | 13/50 [07:06<21:28, 34.82s/it]

[I 2025-12-01 15:59:14,427] Trial 14 finished with value: 0.6583333333333333 and parameters: {'max_depth': 9, 'learning_rate': 0.0698357672864415, 'n_estimators': 686, 'subsample': 0.8379577495118626, 'colsample_bytree': 0.5048357019306092, 'min_child_weight': 6, 'gamma': 1.4106233875057017, 'reg_alpha': 1.0654497971032208e-08, 'reg_lambda': 1.4817714292200202e-08, 'max_delta_step': 8}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  28%|██▊       | 14/50 [07:19<16:49, 28.03s/it]

[I 2025-12-01 15:59:26,769] Trial 15 finished with value: 0.6916666666666667 and parameters: {'max_depth': 4, 'learning_rate': 0.07255352673694063, 'n_estimators': 729, 'subsample': 0.9987933038115377, 'colsample_bytree': 0.5097560887737729, 'min_child_weight': 7, 'gamma': 1.7301742700756377, 'reg_alpha': 1.9921058413717803e-08, 'reg_lambda': 1.0331942199450013e-08, 'max_delta_step': 8}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  30%|███       | 15/50 [08:09<20:21, 34.90s/it]

[I 2025-12-01 16:00:17,568] Trial 11 finished with value: 0.6333333333333333 and parameters: {'max_depth': 10, 'learning_rate': 0.022177234758078947, 'n_estimators': 1387, 'subsample': 0.6080501687192792, 'colsample_bytree': 0.5384867360236856, 'min_child_weight': 1, 'gamma': 3.3441003881730795, 'reg_alpha': 1.5208166302714346e-06, 'reg_lambda': 0.00011435895246891638, 'max_delta_step': 9}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  32%|███▏      | 16/50 [08:26<16:35, 29.27s/it]

[I 2025-12-01 16:00:33,782] Trial 12 finished with value: 0.6291666666666667 and parameters: {'max_depth': 6, 'learning_rate': 0.03594527525499201, 'n_estimators': 1213, 'subsample': 0.8462520155958095, 'colsample_bytree': 0.6247725177303148, 'min_child_weight': 1, 'gamma': 2.025291008053593, 'reg_alpha': 1.354572214455498e-07, 'reg_lambda': 0.16273614697174285, 'max_delta_step': 2}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  34%|███▍      | 17/50 [08:30<12:04, 21.96s/it]

[I 2025-12-01 16:00:38,733] Trial 16 finished with value: 0.6916666666666667 and parameters: {'max_depth': 4, 'learning_rate': 0.03749658248895976, 'n_estimators': 769, 'subsample': 0.9908451773959221, 'colsample_bytree': 0.5467571906951282, 'min_child_weight': 7, 'gamma': 1.9289202722912921, 'reg_alpha': 2.2664558107386976e-07, 'reg_lambda': 1.3264902042970844e-08, 'max_delta_step': 7}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  36%|███▌      | 18/50 [08:55<12:08, 22.75s/it]

[I 2025-12-01 16:01:03,332] Trial 17 finished with value: 0.7125 and parameters: {'max_depth': 3, 'learning_rate': 0.03482539950478314, 'n_estimators': 884, 'subsample': 0.9864921055018895, 'colsample_bytree': 0.5737411324627107, 'min_child_weight': 7, 'gamma': 2.1275870734989857, 'reg_alpha': 1.7063850267627027e-07, 'reg_lambda': 0.0012365610197887468, 'max_delta_step': 7}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  38%|███▊      | 19/50 [09:52<16:59, 32.89s/it]

[I 2025-12-01 16:01:59,829] Trial 18 finished with value: 0.6916666666666667 and parameters: {'max_depth': 3, 'learning_rate': 0.042279141956399154, 'n_estimators': 851, 'subsample': 0.9981376498674386, 'colsample_bytree': 0.5917583557263482, 'min_child_weight': 7, 'gamma': 2.0717353050034646, 'reg_alpha': 1.4419431035724632e-07, 'reg_lambda': 4.5620162809152, 'max_delta_step': 7}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  40%|████      | 20/50 [10:09<14:08, 28.29s/it]

[I 2025-12-01 16:02:17,405] Trial 19 finished with value: 0.6916666666666667 and parameters: {'max_depth': 3, 'learning_rate': 0.046633784386945404, 'n_estimators': 918, 'subsample': 0.9916339215219494, 'colsample_bytree': 0.594238985486878, 'min_child_weight': 7, 'gamma': 0.08780217063713192, 'reg_alpha': 0.009095200133370243, 'reg_lambda': 6.766670604275024, 'max_delta_step': 7}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  42%|████▏     | 21/50 [10:37<13:37, 28.20s/it]

[I 2025-12-01 16:02:45,380] Trial 20 finished with value: 0.6458333333333333 and parameters: {'max_depth': 3, 'learning_rate': 0.09109536947044888, 'n_estimators': 877, 'subsample': 0.9267952909129509, 'colsample_bytree': 0.8057897579786071, 'min_child_weight': 5, 'gamma': 4.213102940072378, 'reg_alpha': 0.008245509151479603, 'reg_lambda': 6.266897090357437, 'max_delta_step': 5}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  44%|████▍     | 22/50 [10:46<10:25, 22.33s/it]

[I 2025-12-01 16:02:54,043] Trial 24 pruned.

Best trial: 5. Best value: 0.7125:  46%|████▌     | 23/50 [10:58<08:43, 19.37s/it]

[I 2025-12-01 16:03:06,513] Trial 21 finished with value: 0.6375 and parameters: {'max_depth': 3, 'learning_rate': 0.0470643142461119, 'n_estimators': 982, 'subsample': 0.9305844814124875, 'colsample_bytree': 0.8082904698640109, 'min_child_weight': 5, 'gamma': 2.6231805786530793, 'reg_alpha': 0.03312787462083709, 'reg_lambda': 0.010828380702642653, 'max_delta_step': 5}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  48%|████▊     | 24/50 [11:53<12:56, 29.86s/it]

[I 2025-12-01 16:04:00,813] Trial 23 finished with value: 0.625 and parameters: {'max_depth': 4, 'learning_rate': 0.01585339356669384, 'n_estimators': 518, 'subsample': 0.9338758315512569, 'colsample_bytree': 0.7960571110331556, 'min_child_weight': 5, 'gamma': 4.222873527092251, 'reg_alpha': 0.0030902703521053644, 'reg_lambda': 0.004385191515084605, 'max_delta_step': 5}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  50%|█████     | 25/50 [12:17<11:42, 28.10s/it]

[I 2025-12-01 16:04:24,811] Trial 26 finished with value: 0.6916666666666667 and parameters: {'max_depth': 4, 'learning_rate': 0.018536390894316263, 'n_estimators': 535, 'subsample': 0.9424878455331975, 'colsample_bytree': 0.5033891972030079, 'min_child_weight': 7, 'gamma': 1.5261785088408664, 'reg_alpha': 7.003481370120713e-08, 'reg_lambda': 1.6575184549664475e-07, 'max_delta_step': 8}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  52%|█████▏    | 26/50 [12:26<09:03, 22.64s/it]

[I 2025-12-01 16:04:34,715] Trial 27 pruned.

Best trial: 5. Best value: 0.7125:  54%|█████▍    | 27/50 [12:29<06:22, 16.62s/it]

[I 2025-12-01 16:04:37,313] Trial 22 finished with value: 0.625 and parameters: {'max_depth': 4, 'learning_rate': 0.01622467500802044, 'n_estimators': 958, 'subsample': 0.93181590118669, 'colsample_bytree': 0.8026813118783285, 'min_child_weight': 5, 'gamma': 4.227531638520682, 'reg_alpha': 0.004944755185901516, 'reg_lambda': 0.003191975334085909, 'max_delta_step': 5}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  56%|█████▌    | 28/50 [12:34<04:49, 13.16s/it]

[I 2025-12-01 16:04:42,393] Trial 28 pruned.

Best trial: 5. Best value: 0.7125:  58%|█████▊    | 29/50 [12:44<04:16, 12.23s/it]

[I 2025-12-01 16:04:52,463] Trial 29 pruned.

Best trial: 5. Best value: 0.7125:  60%|██████    | 30/50 [12:47<03:08,  9.40s/it]

[I 2025-12-01 16:04:55,248] Trial 30 pruned.

Best trial: 5. Best value: 0.7125:  62%|██████▏   | 31/50 [12:53<02:41,  8.50s/it]

[I 2025-12-01 16:05:01,606] Trial 31 pruned.

Best trial: 5. Best value: 0.7125:  64%|██████▍   | 32/50 [13:09<03:11, 10.64s/it]

[I 2025-12-01 16:05:17,264] Trial 34 pruned.

Best trial: 5. Best value: 0.7125:  66%|██████▌   | 33/50 [13:19<02:58, 10.52s/it]

[I 2025-12-01 16:05:27,523] Trial 25 finished with value: 0.6375 and parameters: {'max_depth': 4, 'learning_rate': 0.018570455173733406, 'n_estimators': 996, 'subsample': 0.9287492629886246, 'colsample_bytree': 0.5010728985225189, 'min_child_weight': 5, 'gamma': 1.4403828750203806, 'reg_alpha': 7.666652739708255e-08, 'reg_lambda': 0.0017474211171236533, 'max_delta_step': 6}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  68%|██████▊   | 34/50 [14:24<07:10, 26.88s/it]

[I 2025-12-01 16:06:32,564] Trial 33 finished with value: 0.625 and parameters: {'max_depth': 3, 'learning_rate': 0.02178653436072477, 'n_estimators': 357, 'subsample': 0.8813341945295681, 'colsample_bytree': 0.6453190137930631, 'min_child_weight': 3, 'gamma': 2.3619605024578276, 'reg_alpha': 1.1622241596275468e-05, 'reg_lambda': 0.0003987156449808871, 'max_delta_step': 4}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  70%|███████   | 35/50 [14:33<05:22, 21.49s/it]

[I 2025-12-01 16:06:41,438] Trial 35 finished with value: 0.6916666666666667 and parameters: {'max_depth': 3, 'learning_rate': 0.02344223390617383, 'n_estimators': 633, 'subsample': 0.8988065521555864, 'colsample_bytree': 0.5487073495318061, 'min_child_weight': 7, 'gamma': 1.7808723311907857, 'reg_alpha': 2.698934307369381e-07, 'reg_lambda': 7.608534256669172e-08, 'max_delta_step': 4}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  72%|███████▏  | 36/50 [14:44<04:14, 18.18s/it]

[I 2025-12-01 16:06:51,941] Trial 32 finished with value: 0.625 and parameters: {'max_depth': 3, 'learning_rate': 0.0315316056941779, 'n_estimators': 635, 'subsample': 0.8146753032942226, 'colsample_bytree': 0.6364058048550612, 'min_child_weight': 3, 'gamma': 2.3723676636619486, 'reg_alpha': 1.5958713428031704e-05, 'reg_lambda': 0.03683178766640763, 'max_delta_step': 10}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  74%|███████▍  | 37/50 [14:44<02:46, 12.82s/it]

[I 2025-12-01 16:06:52,255] Trial 36 finished with value: 0.6916666666666667 and parameters: {'max_depth': 3, 'learning_rate': 0.024994635750911622, 'n_estimators': 629, 'subsample': 0.8989788010541196, 'colsample_bytree': 0.6978959006946588, 'min_child_weight': 7, 'gamma': 3.014294922576933, 'reg_alpha': 3.4667237461794564e-07, 'reg_lambda': 6.356461729439659e-08, 'max_delta_step': 4}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  76%|███████▌  | 38/50 [14:53<02:19, 11.66s/it]

[I 2025-12-01 16:07:01,208] Trial 37 pruned.

Best trial: 5. Best value: 0.7125:  78%|███████▊  | 39/50 [15:22<03:05, 16.90s/it]

[I 2025-12-01 16:07:30,340] Trial 40 pruned.

Best trial: 5. Best value: 0.7125:  80%|████████  | 40/50 [15:38<02:45, 16.59s/it]

[I 2025-12-01 16:07:46,218] Trial 42 pruned.

Best trial: 5. Best value: 0.7125:  82%|████████▏ | 41/50 [16:14<03:20, 22.28s/it]

[I 2025-12-01 16:08:21,749] Trial 39 finished with value: 0.6708333333333334 and parameters: {'max_depth': 7, 'learning_rate': 0.0869571552593867, 'n_estimators': 741, 'subsample': 0.9723281994683901, 'colsample_bytree': 0.6768159516838284, 'min_child_weight': 6, 'gamma': 3.0055563151787057, 'reg_alpha': 3.5887459847299385e-08, 'reg_lambda': 5.773053630815699e-08, 'max_delta_step': 7}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  84%|████████▍ | 42/50 [16:28<02:39, 19.90s/it]

[I 2025-12-01 16:08:36,107] Trial 44 pruned.

Best trial: 5. Best value: 0.7125:  86%|████████▌ | 43/50 [16:37<01:56, 16.71s/it]

[I 2025-12-01 16:08:45,379] Trial 38 finished with value: 0.6708333333333334 and parameters: {'max_depth': 6, 'learning_rate': 0.08104630648358394, 'n_estimators': 1077, 'subsample': 0.9997672645154521, 'colsample_bytree': 0.7118115942471258, 'min_child_weight': 6, 'gamma': 1.132110877238862, 'reg_alpha': 2.7888515781956855e-08, 'reg_lambda': 8.65108388896865e-08, 'max_delta_step': 7}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  88%|████████▊ | 44/50 [16:47<01:27, 14.60s/it]

[I 2025-12-01 16:08:55,063] Trial 45 pruned.

Best trial: 5. Best value: 0.7125:  90%|█████████ | 45/50 [16:56<01:04, 12.98s/it]

[I 2025-12-01 16:09:04,248] Trial 46 pruned.

Best trial: 5. Best value: 0.7125:  92%|█████████▏| 46/50 [17:03<00:44, 11.22s/it]

[I 2025-12-01 16:09:11,378] Trial 47 pruned.

Best trial: 5. Best value: 0.7125:  94%|█████████▍| 47/50 [17:08<00:27,  9.30s/it]

[I 2025-12-01 16:09:16,204] Trial 41 finished with value: 0.65 and parameters: {'max_depth': 7, 'learning_rate': 0.07321857186129682, 'n_estimators': 1084, 'subsample': 0.965427115249307, 'colsample_bytree': 0.9402842568510844, 'min_child_weight': 6, 'gamma': 1.0743074153472851, 'reg_alpha': 3.569997186062922e-08, 'reg_lambda': 1.8415512387102719e-06, 'max_delta_step': 8}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125:  96%|█████████▌| 48/50 [17:08<00:13,  6.59s/it]

[I 2025-12-01 16:09:16,424] Trial 48 pruned.

Best trial: 5. Best value: 0.7125:  98%|█████████▊| 49/50 [17:09<00:04,  4.93s/it]

[I 2025-12-01 16:09:17,516] Trial 43 finished with value: 0.6916666666666667 and parameters: {'max_depth': 8, 'learning_rate': 0.04991242100509145, 'n_estimators': 740, 'subsample': 0.6261759977491996, 'colsample_bytree': 0.6764478424247986, 'min_child_weight': 6, 'gamma': 2.0316418189060275, 'reg_alpha': 2.511701341322404, 'reg_lambda': 1.7285872697278782e-06, 'max_delta_step': 9}. Best is trial 5 with value: 0.7125.

Best trial: 5. Best value: 0.7125: 100%|██████████| 50/50 [17:13<00:00, 20.67s/it]

[I 2025-12-01 16:09:21,437] Trial 49 pruned.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 16:09:29,148] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 67, Test size: 17
Using Leave-One-Out CV with 67 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.584428:   2%|▏         | 1/50 [01:27<1:11:28, 87.53s/it]

[I 2025-12-01 16:10:56,661] Trial 3 finished with value: 0.5844277673545966 and parameters: {'max_depth': 9, 'learning_rate': 0.03384794334546327, 'n_estimators': 482, 'subsample': 0.8609989029091318, 'colsample_bytree': 0.5875065804058717, 'min_child_weight': 5, 'gamma': 3.5868928789495653, 'reg_alpha': 2.583593107735476e-06, 'reg_lambda': 4.688064121990167e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.5844277673545966.

Best trial: 2. Best value: 0.659475:   4%|▍         | 2/50 [02:03<45:45, 57.19s/it]

[I 2025-12-01 16:11:32,618] Trial 2 finished with value: 0.6594746716697937 and parameters: {'max_depth': 10, 'learning_rate': 0.04282293784396696, 'n_estimators': 502, 'subsample': 0.8428096047404634, 'colsample_bytree': 0.9622204259933047, 'min_child_weight': 3, 'gamma': 0.2757541376546774, 'reg_alpha': 0.10513489458569573, 'reg_lambda': 0.06130361330218249, 'max_delta_step': 10}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:   6%|▌         | 3/50 [03:25<53:39, 68.50s/it]

[I 2025-12-01 16:12:54,583] Trial 1 finished with value: 0.5773921200750469 and parameters: {'max_depth': 10, 'learning_rate': 0.08261998800532318, 'n_estimators': 1124, 'subsample': 0.6822692906161116, 'colsample_bytree': 0.7476460129651462, 'min_child_weight': 1, 'gamma': 1.2600673288814646, 'reg_alpha': 0.011119010562474855, 'reg_lambda': 6.564899808681571e-06, 'max_delta_step': 1}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:   8%|▊         | 4/50 [03:44<37:35, 49.03s/it]

[I 2025-12-01 16:13:13,753] Trial 5 finished with value: 0.5966228893058161 and parameters: {'max_depth': 7, 'learning_rate': 0.051477001144707005, 'n_estimators': 676, 'subsample': 0.7233032873080669, 'colsample_bytree': 0.641182128608184, 'min_child_weight': 4, 'gamma': 0.18053084712858491, 'reg_alpha': 2.310679498137964e-06, 'reg_lambda': 8.558773644801901e-06, 'max_delta_step': 4}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  10%|█         | 5/50 [04:12<31:09, 41.54s/it]

[I 2025-12-01 16:13:42,011] Trial 0 finished with value: 0.5792682926829269 and parameters: {'max_depth': 10, 'learning_rate': 0.05034549806712755, 'n_estimators': 1302, 'subsample': 0.9605663919182292, 'colsample_bytree': 0.7160616532634876, 'min_child_weight': 2, 'gamma': 2.5585149344782003, 'reg_alpha': 0.019591877511583786, 'reg_lambda': 0.00928831661569492, 'max_delta_step': 2}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  12%|█▏        | 6/50 [04:18<21:35, 29.44s/it]

[I 2025-12-01 16:13:47,982] Trial 6 finished with value: 0.14634146341463414 and parameters: {'max_depth': 9, 'learning_rate': 0.024885097100525156, 'n_estimators': 378, 'subsample': 0.549058218403131, 'colsample_bytree': 0.9496520437912316, 'min_child_weight': 10, 'gamma': 1.4145390698531983, 'reg_alpha': 1.340759895322635e-06, 'reg_lambda': 1.3628877919237684e-06, 'max_delta_step': 4}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  14%|█▍        | 7/50 [06:10<40:25, 56.40s/it]

[I 2025-12-01 16:15:39,893] Trial 7 finished with value: 0.5408067542213884 and parameters: {'max_depth': 3, 'learning_rate': 0.01825452454142867, 'n_estimators': 689, 'subsample': 0.9739937372324639, 'colsample_bytree': 0.5923844094954729, 'min_child_weight': 6, 'gamma': 2.3445102646065608, 'reg_alpha': 8.026151759980997e-06, 'reg_lambda': 0.7434894973139222, 'max_delta_step': 2}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  16%|█▌        | 8/50 [06:12<27:23, 39.13s/it]

[I 2025-12-01 16:15:42,036] Trial 9 finished with value: 0.4146341463414634 and parameters: {'max_depth': 10, 'learning_rate': 0.015680219786799496, 'n_estimators': 932, 'subsample': 0.5759177119203351, 'colsample_bytree': 0.6777235731957068, 'min_child_weight': 10, 'gamma': 1.3584763965841122, 'reg_alpha': 2.574491795244503, 'reg_lambda': 3.091823453652343e-08, 'max_delta_step': 9}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  18%|█▊        | 9/50 [06:25<21:06, 30.89s/it]

[I 2025-12-01 16:15:54,788] Trial 4 finished with value: 0.5984990619136961 and parameters: {'max_depth': 6, 'learning_rate': 0.10325649942853353, 'n_estimators': 1405, 'subsample': 0.7826184497757063, 'colsample_bytree': 0.7654852092841737, 'min_child_weight': 1, 'gamma': 2.8643077997477433, 'reg_alpha': 0.20019118476262274, 'reg_lambda': 1.8892110906245437e-08, 'max_delta_step': 10}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  20%|██        | 10/50 [06:45<18:14, 27.37s/it]

[I 2025-12-01 16:16:14,293] Trial 11 finished with value: 0.17073170731707318 and parameters: {'max_depth': 9, 'learning_rate': 0.029362647942418663, 'n_estimators': 264, 'subsample': 0.5490320111797321, 'colsample_bytree': 0.7639565685065086, 'min_child_weight': 10, 'gamma': 1.2038002156065997, 'reg_alpha': 0.0006059672314256048, 'reg_lambda': 2.28575709203091e-07, 'max_delta_step': 3}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  22%|██▏       | 11/50 [06:59<15:16, 23.51s/it]

[I 2025-12-01 16:16:29,032] Trial 12 pruned.

Best trial: 2. Best value: 0.659475:  24%|██▍       | 12/50 [07:00<10:28, 16.55s/it]

[I 2025-12-01 16:16:29,647] Trial 8 finished with value: 0.6280487804878049 and parameters: {'max_depth': 3, 'learning_rate': 0.050364372812423036, 'n_estimators': 435, 'subsample': 0.6202861207653134, 'colsample_bytree': 0.8722338473148938, 'min_child_weight': 2, 'gamma': 0.491978822584454, 'reg_alpha': 2.9728655928903134, 'reg_lambda': 1.9668831381469656, 'max_delta_step': 7}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  26%|██▌       | 13/50 [07:57<17:43, 28.75s/it]

[I 2025-12-01 16:17:26,481] Trial 13 finished with value: 0.5478424015009381 and parameters: {'max_depth': 6, 'learning_rate': 0.2691407600004751, 'n_estimators': 580, 'subsample': 0.8506626218600666, 'colsample_bytree': 0.993149764529645, 'min_child_weight': 7, 'gamma': 4.6347436908824085, 'reg_alpha': 4.239887381215157, 'reg_lambda': 3.876863144536294, 'max_delta_step': 7}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  28%|██▊       | 14/50 [08:40<19:49, 33.05s/it]

[I 2025-12-01 16:18:09,503] Trial 15 finished with value: 0.5548780487804879 and parameters: {'max_depth': 3, 'learning_rate': 0.2806111374488459, 'n_estimators': 555, 'subsample': 0.8435263871666322, 'colsample_bytree': 0.9662340803798837, 'min_child_weight': 3, 'gamma': 0.10271763220945812, 'reg_alpha': 9.361343000956525, 'reg_lambda': 2.344369247727656, 'max_delta_step': 7}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  30%|███       | 15/50 [09:32<22:36, 38.75s/it]

[I 2025-12-01 16:19:01,449] Trial 16 finished with value: 0.5844277673545966 and parameters: {'max_depth': 3, 'learning_rate': 0.09874010362987458, 'n_estimators': 880, 'subsample': 0.6285120919747024, 'colsample_bytree': 0.8717657285661083, 'min_child_weight': 3, 'gamma': 0.06325778493688039, 'reg_alpha': 0.16828620321003487, 'reg_lambda': 0.05359240493294675, 'max_delta_step': 7}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  32%|███▏      | 16/50 [09:37<16:13, 28.62s/it]

[I 2025-12-01 16:19:06,539] Trial 10 finished with value: 0.6036585365853658 and parameters: {'max_depth': 10, 'learning_rate': 0.024087739822021705, 'n_estimators': 1330, 'subsample': 0.8099369913363719, 'colsample_bytree': 0.6977226857991534, 'min_child_weight': 2, 'gamma': 2.182743217464742, 'reg_alpha': 0.008006565556186986, 'reg_lambda': 0.0003861006624038064, 'max_delta_step': 4}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  34%|███▍      | 17/50 [09:58<14:29, 26.34s/it]

[I 2025-12-01 16:19:27,569] Trial 17 finished with value: 0.6036585365853658 and parameters: {'max_depth': 4, 'learning_rate': 0.011379670897073126, 'n_estimators': 211, 'subsample': 0.6513860645161716, 'colsample_bytree': 0.8681298105291697, 'min_child_weight': 3, 'gamma': 0.5828698241808811, 'reg_alpha': 2.0603362723441935e-08, 'reg_lambda': 0.018400536837677412, 'max_delta_step': 7}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  36%|███▌      | 18/50 [10:27<14:31, 27.23s/it]

[I 2025-12-01 16:19:56,886] Trial 18 finished with value: 0.5722326454033771 and parameters: {'max_depth': 5, 'learning_rate': 0.13966167841843047, 'n_estimators': 377, 'subsample': 0.5006550599639881, 'colsample_bytree': 0.8570013822848193, 'min_child_weight': 3, 'gamma': 0.7216768487769742, 'reg_alpha': 0.0008434692099284071, 'reg_lambda': 0.0019141522849489188, 'max_delta_step': 6}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  38%|███▊      | 19/50 [10:46<12:45, 24.68s/it]

[I 2025-12-01 16:20:15,620] Trial 19 finished with value: 0.5600375234521576 and parameters: {'max_depth': 5, 'learning_rate': 0.011274562810022707, 'n_estimators': 216, 'subsample': 0.6305469120623352, 'colsample_bytree': 0.8485344674201626, 'min_child_weight': 4, 'gamma': 0.8325416029887585, 'reg_alpha': 2.709370498252605e-08, 'reg_lambda': 0.0638255022344514, 'max_delta_step': 6}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  40%|████      | 20/50 [10:53<09:36, 19.23s/it]

[I 2025-12-01 16:20:22,157] Trial 14 finished with value: 0.574108818011257 and parameters: {'max_depth': 6, 'learning_rate': 0.23606445076402602, 'n_estimators': 1481, 'subsample': 0.8402597626919054, 'colsample_bytree': 0.9997115909495253, 'min_child_weight': 3, 'gamma': 4.982863727612551, 'reg_alpha': 6.617202853245537, 'reg_lambda': 0.0017243929609686206, 'max_delta_step': 7}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  42%|████▏     | 21/50 [10:55<06:56, 14.35s/it]

[I 2025-12-01 16:20:25,127] Trial 20 finished with value: 0.6088180112570356 and parameters: {'max_depth': 5, 'learning_rate': 0.16011971442055561, 'n_estimators': 393, 'subsample': 0.910932731542219, 'colsample_bytree': 0.8919719706842489, 'min_child_weight': 5, 'gamma': 0.8269288036113651, 'reg_alpha': 0.3259908240427122, 'reg_lambda': 0.259126288866133, 'max_delta_step': 10}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  44%|████▍     | 22/50 [12:02<14:04, 30.15s/it]

[I 2025-12-01 16:21:32,034] Trial 24 finished with value: 0.5895872420262664 and parameters: {'max_depth': 4, 'learning_rate': 0.0721618488229423, 'n_estimators': 391, 'subsample': 0.914549736680075, 'colsample_bytree': 0.9193758110452174, 'min_child_weight': 5, 'gamma': 1.6703709153001887, 'reg_alpha': 0.39016648674932924, 'reg_lambda': 0.36522594473422837, 'max_delta_step': 10}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  46%|████▌     | 23/50 [12:12<10:50, 24.09s/it]

[I 2025-12-01 16:21:42,067] Trial 21 finished with value: 0.6280487804878049 and parameters: {'max_depth': 8, 'learning_rate': 0.07312726761736181, 'n_estimators': 785, 'subsample': 0.9062573525918185, 'colsample_bytree': 0.9056821849539715, 'min_child_weight': 5, 'gamma': 0.773160261246086, 'reg_alpha': 0.3250755447889084, 'reg_lambda': 0.1095612798266761, 'max_delta_step': 10}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  48%|████▊     | 24/50 [12:19<08:06, 18.71s/it]

[I 2025-12-01 16:21:48,247] Trial 22 finished with value: 0.5670731707317074 and parameters: {'max_depth': 8, 'learning_rate': 0.07395732475442339, 'n_estimators': 735, 'subsample': 0.9066387470118753, 'colsample_bytree': 0.9154266400751275, 'min_child_weight': 7, 'gamma': 3.6082093397330617, 'reg_alpha': 0.38639025000723287, 'reg_lambda': 0.39686052686848683, 'max_delta_step': 10}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  50%|█████     | 25/50 [13:04<11:05, 26.61s/it]

[I 2025-12-01 16:22:33,291] Trial 23 finished with value: 0.5459662288930581 and parameters: {'max_depth': 8, 'learning_rate': 0.0380846754206427, 'n_estimators': 1006, 'subsample': 0.7625242859534977, 'colsample_bytree': 0.9103723821492489, 'min_child_weight': 5, 'gamma': 1.684678531608137, 'reg_alpha': 0.26354342948900494, 'reg_lambda': 0.4069182241109594, 'max_delta_step': 10}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  52%|█████▏    | 26/50 [13:21<09:34, 23.93s/it]

[I 2025-12-01 16:22:50,959] Trial 25 finished with value: 0.5914634146341464 and parameters: {'max_depth': 8, 'learning_rate': 0.16256053703572274, 'n_estimators': 759, 'subsample': 0.9054236794055712, 'colsample_bytree': 0.9089058539695722, 'min_child_weight': 7, 'gamma': 0.528304440923534, 'reg_alpha': 0.8484964165622769, 'reg_lambda': 0.18774345645559318, 'max_delta_step': 9}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  54%|█████▍    | 27/50 [13:57<10:30, 27.42s/it]

[I 2025-12-01 16:23:26,533] Trial 26 finished with value: 0.5530018761726079 and parameters: {'max_depth': 8, 'learning_rate': 0.039366127595836936, 'n_estimators': 765, 'subsample': 0.9057753782136766, 'colsample_bytree': 0.8127157885023442, 'min_child_weight': 7, 'gamma': 0.4216670391697081, 'reg_alpha': 0.039865304389259094, 'reg_lambda': 7.745402455709902, 'max_delta_step': 9}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  56%|█████▌    | 28/50 [15:50<19:29, 53.15s/it]

[I 2025-12-01 16:25:19,700] Trial 30 finished with value: 0.6228893058161351 and parameters: {'max_depth': 9, 'learning_rate': 0.05408720124148008, 'n_estimators': 579, 'subsample': 0.997636166819375, 'colsample_bytree': 0.8179538164502799, 'min_child_weight': 2, 'gamma': 0.9982640364795544, 'reg_alpha': 0.0014960691277599203, 'reg_lambda': 5.703752079398933e-05, 'max_delta_step': 8}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  58%|█████▊    | 29/50 [16:04<14:26, 41.28s/it]

[I 2025-12-01 16:25:33,284] Trial 29 finished with value: 0.5966228893058161 and parameters: {'max_depth': 7, 'learning_rate': 0.06298632630394783, 'n_estimators': 567, 'subsample': 0.8092664977514323, 'colsample_bytree': 0.8087686411993791, 'min_child_weight': 2, 'gamma': 0.33574549861114045, 'reg_alpha': 0.0484498473675156, 'reg_lambda': 9.525844134803938, 'max_delta_step': 8}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  60%|██████    | 30/50 [16:33<12:35, 37.79s/it]

[I 2025-12-01 16:26:02,934] Trial 27 finished with value: 0.6158536585365854 and parameters: {'max_depth': 8, 'learning_rate': 0.038003203031707136, 'n_estimators': 1010, 'subsample': 0.7583788647049382, 'colsample_bytree': 0.8199288559465443, 'min_child_weight': 2, 'gamma': 0.4076534145999755, 'reg_alpha': 0.031947774585119555, 'reg_lambda': 9.178454005453764, 'max_delta_step': 9}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  62%|██████▏   | 31/50 [16:45<09:26, 29.82s/it]

[I 2025-12-01 16:26:14,177] Trial 28 finished with value: 0.6543151969981238 and parameters: {'max_depth': 8, 'learning_rate': 0.03895209698125647, 'n_estimators': 734, 'subsample': 0.9927287886827791, 'colsample_bytree': 0.8150165298803549, 'min_child_weight': 2, 'gamma': 0.33735595035453336, 'reg_alpha': 0.035550803869719996, 'reg_lambda': 7.325374653928226, 'max_delta_step': 8}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  64%|██████▍   | 32/50 [17:02<07:51, 26.21s/it]

[I 2025-12-01 16:26:31,954] Trial 31 finished with value: 0.5966228893058161 and parameters: {'max_depth': 7, 'learning_rate': 0.06554929046519259, 'n_estimators': 493, 'subsample': 0.7961276771826349, 'colsample_bytree': 0.9575330493448337, 'min_child_weight': 4, 'gamma': 1.7482981849188903, 'reg_alpha': 0.06137724330929891, 'reg_lambda': 0.008759752641564651, 'max_delta_step': 8}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  66%|██████▌   | 33/50 [17:26<07:14, 25.58s/it]

[I 2025-12-01 16:26:56,060] Trial 33 finished with value: 0.6036585365853658 and parameters: {'max_depth': 7, 'learning_rate': 0.1112762048498046, 'n_estimators': 470, 'subsample': 0.7265162963551742, 'colsample_bytree': 0.9422697295034411, 'min_child_weight': 4, 'gamma': 1.8068294872295256, 'reg_alpha': 0.00012017508712303999, 'reg_lambda': 0.010681420567867476, 'max_delta_step': 8}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  68%|██████▊   | 34/50 [18:14<08:32, 32.05s/it]

[I 2025-12-01 16:27:43,214] Trial 32 finished with value: 0.6088180112570356 and parameters: {'max_depth': 7, 'learning_rate': 0.11288573351461106, 'n_estimators': 1119, 'subsample': 0.957120542128487, 'colsample_bytree': 0.9508563949865791, 'min_child_weight': 4, 'gamma': 1.6926858450745828, 'reg_alpha': 1.5309680248326807, 'reg_lambda': 0.004040131608454535, 'max_delta_step': 8}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  70%|███████   | 35/50 [20:07<14:06, 56.44s/it]

[I 2025-12-01 16:29:36,564] Trial 34 finished with value: 0.5966228893058161 and parameters: {'max_depth': 9, 'learning_rate': 0.04667738957699609, 'n_estimators': 485, 'subsample': 0.9551222203437066, 'colsample_bytree': 0.9311718858326498, 'min_child_weight': 1, 'gamma': 0.02730302906503468, 'reg_alpha': 1.0786450267246377, 'reg_lambda': 1.6399284699574688, 'max_delta_step': 8}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  72%|███████▏  | 36/50 [20:21<10:12, 43.77s/it]

[I 2025-12-01 16:29:50,781] Trial 35 finished with value: 0.5844277673545966 and parameters: {'max_depth': 10, 'learning_rate': 0.04436885186087417, 'n_estimators': 840, 'subsample': 0.9513511241331111, 'colsample_bytree': 0.9427600323103661, 'min_child_weight': 1, 'gamma': 1.0378170026618636, 'reg_alpha': 0.0032219915109469427, 'reg_lambda': 1.9282145957148398, 'max_delta_step': 6}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  74%|███████▍  | 37/50 [20:40<07:52, 36.33s/it]

[I 2025-12-01 16:30:09,734] Trial 37 finished with value: 0.6036585365853658 and parameters: {'max_depth': 10, 'learning_rate': 0.045104795102901454, 'n_estimators': 823, 'subsample': 0.938755276324456, 'colsample_bytree': 0.5009670466648748, 'min_child_weight': 1, 'gamma': 0.9907031307190686, 'reg_alpha': 0.007924964867877509, 'reg_lambda': 1.3277052511939564, 'max_delta_step': 0}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  76%|███████▌  | 38/50 [21:11<06:55, 34.60s/it]

[I 2025-12-01 16:30:40,283] Trial 36 finished with value: 0.6036585365853658 and parameters: {'max_depth': 10, 'learning_rate': 0.04328967767112763, 'n_estimators': 1179, 'subsample': 0.9417083062721503, 'colsample_bytree': 0.7810377260423105, 'min_child_weight': 1, 'gamma': 1.0619075558286677, 'reg_alpha': 0.004739748551335314, 'reg_lambda': 1.2672526572743132, 'max_delta_step': 6}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  78%|███████▊  | 39/50 [21:58<07:01, 38.33s/it]

[I 2025-12-01 16:31:27,319] Trial 40 finished with value: 0.5600375234521576 and parameters: {'max_depth': 9, 'learning_rate': 0.0305536473680348, 'n_estimators': 687, 'subsample': 0.8803211633873946, 'colsample_bytree': 0.7250671562616149, 'min_child_weight': 6, 'gamma': 2.986574434496534, 'reg_alpha': 0.00011806574931610415, 'reg_lambda': 0.06159009011036988, 'max_delta_step': 5}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  80%|████████  | 40/50 [22:36<06:22, 38.27s/it]

[I 2025-12-01 16:32:05,452] Trial 39 finished with value: 0.5863039399624765 and parameters: {'max_depth': 9, 'learning_rate': 0.030806155876742066, 'n_estimators': 646, 'subsample': 0.9897629001730658, 'colsample_bytree': 0.7385596659584346, 'min_child_weight': 1, 'gamma': 3.447310704254208, 'reg_alpha': 0.010765621078924524, 'reg_lambda': 0.05667391014061259, 'max_delta_step': 5}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  82%|████████▏ | 41/50 [23:05<05:18, 35.44s/it]

[I 2025-12-01 16:32:34,288] Trial 42 finished with value: 0.6088180112570356 and parameters: {'max_depth': 4, 'learning_rate': 0.08603771483028338, 'n_estimators': 318, 'subsample': 0.9938941516122761, 'colsample_bytree': 0.8356905043314081, 'min_child_weight': 2, 'gamma': 0.3558030337806628, 'reg_alpha': 0.10583023396878999, 'reg_lambda': 0.11798756985632405, 'max_delta_step': 9}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  84%|████████▍ | 42/50 [23:06<03:22, 25.36s/it]

[I 2025-12-01 16:32:36,124] Trial 41 finished with value: 0.5914634146341464 and parameters: {'max_depth': 9, 'learning_rate': 0.03166745573081098, 'n_estimators': 618, 'subsample': 0.9965498552369138, 'colsample_bytree': 0.7185573796132573, 'min_child_weight': 2, 'gamma': 3.057640797535598, 'reg_alpha': 0.00011245403671430724, 'reg_lambda': 0.05719066856621081, 'max_delta_step': 5}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  86%|████████▌ | 43/50 [23:07<02:05, 17.90s/it]

[I 2025-12-01 16:32:36,640] Trial 38 finished with value: 0.5722326454033771 and parameters: {'max_depth': 10, 'learning_rate': 0.03139354362909431, 'n_estimators': 820, 'subsample': 0.8744663368703838, 'colsample_bytree': 0.781264651257809, 'min_child_weight': 1, 'gamma': 1.0246731922615295, 'reg_alpha': 0.005005107990118488, 'reg_lambda': 0.05672998004274904, 'max_delta_step': 0}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  88%|████████▊ | 44/50 [24:26<03:37, 36.31s/it]

[I 2025-12-01 16:33:55,882] Trial 45 finished with value: 0.5722326454033771 and parameters: {'max_depth': 9, 'learning_rate': 0.055995216808991846, 'n_estimators': 539, 'subsample': 0.8705769144628327, 'colsample_bytree': 0.7887241184101424, 'min_child_weight': 3, 'gamma': 0.7016099310867272, 'reg_alpha': 0.0018122142456313797, 'reg_lambda': 7.076479354045504e-05, 'max_delta_step': 10}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  90%|█████████ | 45/50 [24:48<02:39, 31.90s/it]

[I 2025-12-01 16:34:17,501] Trial 46 finished with value: 0.6280487804878049 and parameters: {'max_depth': 9, 'learning_rate': 0.05483819480980061, 'n_estimators': 527, 'subsample': 0.9737426194225988, 'colsample_bytree': 0.8855829005760075, 'min_child_weight': 2, 'gamma': 0.7314673851026705, 'reg_alpha': 0.001549477299250361, 'reg_lambda': 0.00013847844746448686, 'max_delta_step': 10}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  92%|█████████▏| 46/50 [24:55<01:38, 24.59s/it]

[I 2025-12-01 16:34:25,041] Trial 44 finished with value: 0.5914634146341464 and parameters: {'max_depth': 9, 'learning_rate': 0.055319392547221326, 'n_estimators': 622, 'subsample': 0.9976814549364136, 'colsample_bytree': 0.788363610194862, 'min_child_weight': 2, 'gamma': 0.7086076944554279, 'reg_alpha': 0.023995280255158558, 'reg_lambda': 0.00021850788221872733, 'max_delta_step': 10}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  94%|█████████▍| 47/50 [25:22<01:15, 25.09s/it]

[I 2025-12-01 16:34:51,228] Trial 43 finished with value: 0.6088180112570356 and parameters: {'max_depth': 4, 'learning_rate': 0.022591343281749585, 'n_estimators': 643, 'subsample': 0.8767779333533242, 'colsample_bytree': 0.8444366105030616, 'min_child_weight': 2, 'gamma': 0.6747494223118478, 'reg_alpha': 0.07292313735071813, 'reg_lambda': 0.0003286093874455835, 'max_delta_step': 10}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  96%|█████████▌| 48/50 [25:45<00:49, 24.53s/it]

[I 2025-12-01 16:35:14,532] Trial 49 finished with value: 0.549718574108818 and parameters: {'max_depth': 8, 'learning_rate': 0.02473445635107879, 'n_estimators': 328, 'subsample': 0.8204279937365877, 'colsample_bytree': 0.8828930016695982, 'min_child_weight': 8, 'gamma': 1.415538631402336, 'reg_alpha': 4.0528433568355275, 'reg_lambda': 1.2303766664928278e-05, 'max_delta_step': 9}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475:  98%|█████████▊| 49/50 [26:03<00:22, 22.62s/it]

[I 2025-12-01 16:35:32,670] Trial 48 finished with value: 0.5600375234521576 and parameters: {'max_depth': 8, 'learning_rate': 0.023434848536610205, 'n_estimators': 433, 'subsample': 0.9234402980890579, 'colsample_bytree': 0.8858421026203923, 'min_child_weight': 6, 'gamma': 1.316118076150017, 'reg_alpha': 0.02167683085865159, 'reg_lambda': 0.00010192229611522604, 'max_delta_step': 9}. Best is trial 2 with value: 0.6594746716697937.

Best trial: 2. Best value: 0.659475: 100%|██████████| 50/50 [26:18<00:00, 31.57s/it]

[I 2025-12-01 16:35:47,727] Trial 47 finished with value: 0.5722326454033771 and parameters: {'max_depth': 8, 'learning_rate': 0.02461316133915377, 'n_estimators': 436, 'subsample': 0.9782453692661837, 'colsample_bytree': 0.8838855474803821, 'min_child_weight': 2, 'gamma': 1.409635908693526, 'reg_alpha': 0.019063492730847044, 'reg_lambda': 5.1014964326964516e-05, 'max_delta_step': 9}. Best is trial 2 with value: 0.6594746716697937.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.673370                0.633333      0.700000
1    19_1         loo       0.712500                0.633333      0.566667
2    17_1         loo       0.659475                0.535714      0.457143
3    15_1         loo       0.625854                0.492857      0.600000

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.258199          0.666667               0.6        50          63
1  0.258199          0.666667               0.6        50          64
2  0.070430          0.571429               0.5        50          67
3 -0.015430          0.285714               0.7        50          66

   test_size
0         16
1         16
2         17
3         17
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.673370                0.633333      0.700000
1    19_1         loo       0.712500                0.633333      0.566667
2    17_1         loo       0.659475                0.535714      0.457143
3    15_1         loo       0.625854                0.492857      0.600000

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.258199          0.666667               0.6        50          63
1  0.258199          0.666667               0.6        50          64
2  0.070430          0.571429               0.5        50          67
3 -0.015430          0.285714               0.7        50          66

   test_size
0         16
1         16
2         17
3         17

In [1562]:

datasets = task_hf_compensated_temp_emb_lbl_lbd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir="xgb_lbd_hc_{CV_STRATEGY}_tasks/xgb_results_handcrafted_temporal_emb_compensated_{CV_STRATEGY}_tasks",
    split_param= "diagnosis_y",
)
print(summary)

[I 2025-12-01 16:35:55,829] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 63, Test size: 16
Using Leave-One-Out CV with 63 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.558152:   2%|▏         | 1/50 [00:48<39:32, 48.42s/it]

[I 2025-12-01 16:36:44,235] Trial 3 finished with value: 0.5581521739130435 and parameters: {'max_depth': 8, 'learning_rate': 0.011206200009148081, 'n_estimators': 413, 'subsample': 0.5707002612132918, 'colsample_bytree': 0.7682439742855438, 'min_child_weight': 3, 'gamma': 1.5714442133692053, 'reg_alpha': 0.03301834817308351, 'reg_lambda': 1.3929127151721231e-06, 'max_delta_step': 10}. Best is trial 3 with value: 0.5581521739130435.

Best trial: 3. Best value: 0.558152:   4%|▍         | 2/50 [00:53<18:13, 22.78s/it]

[I 2025-12-01 16:36:49,073] Trial 0 finished with value: 0.27119565217391306 and parameters: {'max_depth': 3, 'learning_rate': 0.08983420016852224, 'n_estimators': 722, 'subsample': 0.6560894046437828, 'colsample_bytree': 0.847397125009209, 'min_child_weight': 4, 'gamma': 1.7751859194732211, 'reg_alpha': 8.977060021358051, 'reg_lambda': 1.0721959712808076, 'max_delta_step': 9}. Best is trial 3 with value: 0.5581521739130435.

Best trial: 1. Best value: 0.579891:   6%|▌         | 3/50 [01:04<13:53, 17.73s/it]

[I 2025-12-01 16:37:00,788] Trial 1 finished with value: 0.5798913043478261 and parameters: {'max_depth': 6, 'learning_rate': 0.2748930933358368, 'n_estimators': 1187, 'subsample': 0.6103042706652033, 'colsample_bytree': 0.7478913694173135, 'min_child_weight': 6, 'gamma': 0.8859655045020198, 'reg_alpha': 0.003270734131381064, 'reg_lambda': 0.006455568769571552, 'max_delta_step': 8}. Best is trial 1 with value: 0.5798913043478261.

Best trial: 1. Best value: 0.579891:   8%|▊         | 4/50 [01:20<12:55, 16.85s/it]

[I 2025-12-01 16:37:16,297] Trial 2 finished with value: 0.46141304347826084 and parameters: {'max_depth': 9, 'learning_rate': 0.014128657087155872, 'n_estimators': 1369, 'subsample': 0.6310255481866814, 'colsample_bytree': 0.9042092503638576, 'min_child_weight': 7, 'gamma': 2.936485292891482, 'reg_alpha': 6.479210089686748e-08, 'reg_lambda': 0.0001214127370799116, 'max_delta_step': 8}. Best is trial 1 with value: 0.5798913043478261.

Best trial: 1. Best value: 0.579891:  10%|█         | 5/50 [01:39<13:15, 17.68s/it]

[I 2025-12-01 16:37:35,441] Trial 4 finished with value: 0.5548913043478261 and parameters: {'max_depth': 10, 'learning_rate': 0.20799646550660464, 'n_estimators': 737, 'subsample': 0.8147337282900892, 'colsample_bytree': 0.9087897882287479, 'min_child_weight': 4, 'gamma': 0.028116771409680275, 'reg_alpha': 0.03128116787222456, 'reg_lambda': 5.1479686717638645e-06, 'max_delta_step': 7}. Best is trial 1 with value: 0.5798913043478261.

Best trial: 1. Best value: 0.579891:  12%|█▏        | 6/50 [02:04<14:42, 20.06s/it]

[I 2025-12-01 16:38:00,125] Trial 5 finished with value: 0.5423913043478261 and parameters: {'max_depth': 3, 'learning_rate': 0.019194057612151424, 'n_estimators': 959, 'subsample': 0.8042694956920616, 'colsample_bytree': 0.8942254021172193, 'min_child_weight': 5, 'gamma': 2.724093390261349, 'reg_alpha': 0.028407301906042615, 'reg_lambda': 0.006685445998381148, 'max_delta_step': 5}. Best is trial 1 with value: 0.5798913043478261.

Best trial: 1. Best value: 0.579891:  14%|█▍        | 7/50 [02:12<11:42, 16.34s/it]

[I 2025-12-01 16:38:08,818] Trial 6 finished with value: 0.4679347826086957 and parameters: {'max_depth': 7, 'learning_rate': 0.07256921325606301, 'n_estimators': 705, 'subsample': 0.950914949854296, 'colsample_bytree': 0.827538383386091, 'min_child_weight': 1, 'gamma': 4.431420883485673, 'reg_alpha': 0.0016463007609499476, 'reg_lambda': 1.9288969173661134e-07, 'max_delta_step': 0}. Best is trial 1 with value: 0.5798913043478261.

Best trial: 1. Best value: 0.579891:  16%|█▌        | 8/50 [02:15<08:21, 11.93s/it]

[I 2025-12-01 16:38:11,299] Trial 8 finished with value: 0.3652173913043478 and parameters: {'max_depth': 3, 'learning_rate': 0.08220719135675641, 'n_estimators': 751, 'subsample': 0.7041338662785892, 'colsample_bytree': 0.876893159251098, 'min_child_weight': 10, 'gamma': 4.4572022002778935, 'reg_alpha': 1.0273190837873522e-06, 'reg_lambda': 0.0006168369900967998, 'max_delta_step': 5}. Best is trial 1 with value: 0.5798913043478261.

Best trial: 1. Best value: 0.579891:  18%|█▊        | 9/50 [02:24<07:32, 11.04s/it]

[I 2025-12-01 16:38:20,371] Trial 7 finished with value: 0.5423913043478261 and parameters: {'max_depth': 8, 'learning_rate': 0.03331128515152806, 'n_estimators': 618, 'subsample': 0.8364426565115519, 'colsample_bytree': 0.783772150909011, 'min_child_weight': 1, 'gamma': 3.940228280747014, 'reg_alpha': 0.0006310153492168848, 'reg_lambda': 1.657301947968347e-05, 'max_delta_step': 6}. Best is trial 1 with value: 0.5798913043478261.

Best trial: 1. Best value: 0.579891:  20%|██        | 10/50 [02:25<05:20,  8.01s/it]

[I 2025-12-01 16:38:21,612] Trial 9 finished with value: 0.567391304347826 and parameters: {'max_depth': 4, 'learning_rate': 0.23289956434851566, 'n_estimators': 291, 'subsample': 0.8101132761259506, 'colsample_bytree': 0.5936846327079192, 'min_child_weight': 5, 'gamma': 3.634796382650732, 'reg_alpha': 0.0005720561981788406, 'reg_lambda': 1.7076235704790424e-07, 'max_delta_step': 4}. Best is trial 1 with value: 0.5798913043478261.

Best trial: 1. Best value: 0.579891:  22%|██▏       | 11/50 [02:28<04:14,  6.53s/it]

[I 2025-12-01 16:38:24,762] Trial 11 pruned.

Best trial: 1. Best value: 0.579891:  24%|██▍       | 12/50 [02:35<04:03,  6.41s/it]

[I 2025-12-01 16:38:30,900] Trial 12 pruned.

Best trial: 1. Best value: 0.579891:  26%|██▌       | 13/50 [02:36<03:01,  4.90s/it]

[I 2025-12-01 16:38:32,344] Trial 13 pruned.

Best trial: 1. Best value: 0.579891:  28%|██▊       | 14/50 [02:38<02:26,  4.07s/it]

[I 2025-12-01 16:38:34,504] Trial 14 pruned.

Best trial: 1. Best value: 0.579891:  30%|███       | 15/50 [02:39<01:44,  2.98s/it]

[I 2025-12-01 16:38:34,965] Trial 16 pruned.

Best trial: 1. Best value: 0.579891:  32%|███▏      | 16/50 [02:42<01:40,  2.97s/it]

[I 2025-12-01 16:38:37,886] Trial 17 pruned.

Best trial: 1. Best value: 0.579891:  34%|███▍      | 17/50 [02:45<01:37,  2.96s/it]

[I 2025-12-01 16:38:40,821] Trial 15 pruned.

Best trial: 1. Best value: 0.579891:  36%|███▌      | 18/50 [02:50<02:02,  3.82s/it]

[I 2025-12-01 16:38:46,666] Trial 19 pruned.

Best trial: 1. Best value: 0.579891:  38%|███▊      | 19/50 [02:52<01:35,  3.09s/it]

[I 2025-12-01 16:38:48,058] Trial 18 pruned.

Best trial: 10. Best value: 0.58587:  40%|████      | 20/50 [03:03<02:42,  5.41s/it]

[I 2025-12-01 16:38:58,865] Trial 10 finished with value: 0.5858695652173913 and parameters: {'max_depth': 3, 'learning_rate': 0.16407152743525213, 'n_estimators': 903, 'subsample': 0.7262533827639978, 'colsample_bytree': 0.6007428362487155, 'min_child_weight': 5, 'gamma': 3.7296844598081957, 'reg_alpha': 4.184766761389475e-08, 'reg_lambda': 7.012512152896942e-05, 'max_delta_step': 3}. Best is trial 10 with value: 0.5858695652173913.

Best trial: 10. Best value: 0.58587:  42%|████▏     | 21/50 [03:23<04:44,  9.80s/it]

[I 2025-12-01 16:39:18,901] Trial 22 finished with value: 0.567391304347826 and parameters: {'max_depth': 4, 'learning_rate': 0.043330737994763766, 'n_estimators': 475, 'subsample': 0.7752871189514708, 'colsample_bytree': 0.6023523137855604, 'min_child_weight': 5, 'gamma': 1.2924302034820458, 'reg_alpha': 0.005549321787284319, 'reg_lambda': 4.5469284594695976e-05, 'max_delta_step': 10}. Best is trial 10 with value: 0.5858695652173913.

Best trial: 10. Best value: 0.58587:  44%|████▍     | 22/50 [03:26<03:40,  7.89s/it]

[I 2025-12-01 16:39:22,332] Trial 20 pruned.

Best trial: 10. Best value: 0.58587:  46%|████▌     | 23/50 [03:42<04:35, 10.19s/it]

[I 2025-12-01 16:39:37,853] Trial 24 pruned.

Best trial: 10. Best value: 0.58587:  48%|████▊     | 24/50 [03:50<04:09,  9.60s/it]

[I 2025-12-01 16:39:46,117] Trial 26 pruned.

Best trial: 10. Best value: 0.58587:  50%|█████     | 25/50 [04:08<05:01, 12.04s/it]

[I 2025-12-01 16:40:03,859] Trial 21 finished with value: 0.5766304347826088 and parameters: {'max_depth': 4, 'learning_rate': 0.03505849349150105, 'n_estimators': 1490, 'subsample': 0.7746854287855663, 'colsample_bytree': 0.5950866600630538, 'min_child_weight': 5, 'gamma': 2.3533641500521814, 'reg_alpha': 0.004074302627315651, 'reg_lambda': 5.869665748543673e-05, 'max_delta_step': 10}. Best is trial 10 with value: 0.5858695652173913.

Best trial: 10. Best value: 0.58587:  52%|█████▏    | 26/50 [04:13<04:00, 10.01s/it]

[I 2025-12-01 16:40:09,128] Trial 25 finished with value: 0.5766304347826088 and parameters: {'max_depth': 4, 'learning_rate': 0.1924919710812742, 'n_estimators': 901, 'subsample': 0.590997872079341, 'colsample_bytree': 0.5752979342966771, 'min_child_weight': 4, 'gamma': 4.861552047288702, 'reg_alpha': 0.003626972157796251, 'reg_lambda': 1.9607089383490396e-07, 'max_delta_step': 2}. Best is trial 10 with value: 0.5858695652173913.

Best trial: 10. Best value: 0.58587:  54%|█████▍    | 27/50 [04:13<02:45,  7.19s/it]

[I 2025-12-01 16:40:09,730] Trial 23 finished with value: 0.5706521739130435 and parameters: {'max_depth': 4, 'learning_rate': 0.052737037086908196, 'n_estimators': 1093, 'subsample': 0.7080879380606578, 'colsample_bytree': 0.7296497112374697, 'min_child_weight': 3, 'gamma': 4.953309586012654, 'reg_alpha': 1.2040412210021002e-08, 'reg_lambda': 6.716982172024174e-05, 'max_delta_step': 9}. Best is trial 10 with value: 0.5858695652173913.

Best trial: 10. Best value: 0.58587:  56%|█████▌    | 28/50 [04:22<02:45,  7.54s/it]

[I 2025-12-01 16:40:18,086] Trial 27 finished with value: 0.5364130434782608 and parameters: {'max_depth': 4, 'learning_rate': 0.19000957029881546, 'n_estimators': 468, 'subsample': 0.8548132043530843, 'colsample_bytree': 0.5637374868231017, 'min_child_weight': 3, 'gamma': 2.943287652407154, 'reg_alpha': 5.715149993557326e-07, 'reg_lambda': 2.905291114765126e-07, 'max_delta_step': 6}. Best is trial 10 with value: 0.5858695652173913.

Best trial: 10. Best value: 0.58587:  58%|█████▊    | 29/50 [04:23<01:59,  5.67s/it]

[I 2025-12-01 16:40:19,384] Trial 28 pruned.

Best trial: 10. Best value: 0.58587:  60%|██████    | 30/50 [04:27<01:43,  5.19s/it]

[I 2025-12-01 16:40:23,469] Trial 30 pruned.

Best trial: 10. Best value: 0.58587:  62%|██████▏   | 31/50 [04:36<01:57,  6.18s/it]

[I 2025-12-01 16:40:31,948] Trial 32 pruned.

Best trial: 10. Best value: 0.58587:  64%|██████▍   | 32/50 [04:37<01:27,  4.88s/it]

[I 2025-12-01 16:40:33,819] Trial 31 pruned.

Best trial: 10. Best value: 0.58587:  66%|██████▌   | 33/50 [04:59<02:48,  9.90s/it]

[I 2025-12-01 16:40:55,412] Trial 29 pruned.

Best trial: 10. Best value: 0.58587:  68%|██████▊   | 34/50 [05:14<03:01, 11.35s/it]

[I 2025-12-01 16:41:10,159] Trial 36 pruned.

Best trial: 34. Best value: 0.63587:  70%|███████   | 35/50 [05:24<02:44, 10.97s/it]

[I 2025-12-01 16:41:20,251] Trial 34 finished with value: 0.6358695652173914 and parameters: {'max_depth': 3, 'learning_rate': 0.10036441525192474, 'n_estimators': 896, 'subsample': 0.5711532488944848, 'colsample_bytree': 0.5462897574313383, 'min_child_weight': 4, 'gamma': 4.071866127695684, 'reg_alpha': 0.004305871710760368, 'reg_lambda': 7.992431742264143e-06, 'max_delta_step': 1}. Best is trial 34 with value: 0.6358695652173914.

Best trial: 34. Best value: 0.63587:  72%|███████▏  | 36/50 [05:27<02:01,  8.69s/it]

[I 2025-12-01 16:41:23,626] Trial 35 finished with value: 0.6266304347826087 and parameters: {'max_depth': 3, 'learning_rate': 0.09770799884718587, 'n_estimators': 923, 'subsample': 0.5699597262277738, 'colsample_bytree': 0.553215048564642, 'min_child_weight': 4, 'gamma': 4.085465623773168, 'reg_alpha': 0.00398723061854799, 'reg_lambda': 9.478901316222816e-06, 'max_delta_step': 2}. Best is trial 34 with value: 0.6358695652173914.

Best trial: 34. Best value: 0.63587:  74%|███████▍  | 37/50 [05:36<01:52,  8.63s/it]

[I 2025-12-01 16:41:32,099] Trial 33 pruned.

Best trial: 34. Best value: 0.63587:  76%|███████▌  | 38/50 [05:42<01:35,  7.97s/it]

[I 2025-12-01 16:41:38,540] Trial 39 pruned.

Best trial: 34. Best value: 0.63587:  78%|███████▊  | 39/50 [05:49<01:23,  7.61s/it]

[I 2025-12-01 16:41:45,296] Trial 40 pruned.

Best trial: 34. Best value: 0.63587:  80%|████████  | 40/50 [05:56<01:13,  7.38s/it]

[I 2025-12-01 16:41:52,166] Trial 42 pruned.

Best trial: 34. Best value: 0.63587:  82%|████████▏ | 41/50 [06:00<00:58,  6.53s/it]

[I 2025-12-01 16:41:56,712] Trial 41 pruned.

Best trial: 34. Best value: 0.63587:  84%|████████▍ | 42/50 [06:08<00:53,  6.73s/it]

[I 2025-12-01 16:42:03,897] Trial 43 pruned.

Best trial: 34. Best value: 0.63587:  86%|████████▌ | 43/50 [06:11<00:40,  5.72s/it]

[I 2025-12-01 16:42:07,263] Trial 37 finished with value: 0.5858695652173913 and parameters: {'max_depth': 3, 'learning_rate': 0.09413584796927703, 'n_estimators': 940, 'subsample': 0.5845409797345233, 'colsample_bytree': 0.5523004051410123, 'min_child_weight': 5, 'gamma': 4.184342313174277, 'reg_alpha': 0.13471866044359448, 'reg_lambda': 2.016775641332971e-06, 'max_delta_step': 10}. Best is trial 34 with value: 0.6358695652173914.

Best trial: 34. Best value: 0.63587:  88%|████████▊ | 44/50 [06:17<00:35,  5.89s/it]

[I 2025-12-01 16:42:13,540] Trial 44 pruned.

Best trial: 34. Best value: 0.63587:  90%|█████████ | 45/50 [06:18<00:22,  4.43s/it]

[I 2025-12-01 16:42:14,571] Trial 45 pruned.

Best trial: 34. Best value: 0.63587:  92%|█████████▏| 46/50 [06:33<00:30,  7.64s/it]

[I 2025-12-01 16:42:29,698] Trial 47 pruned.

Best trial: 34. Best value: 0.63587:  94%|█████████▍| 47/50 [06:41<00:22,  7.63s/it]

[I 2025-12-01 16:42:37,314] Trial 38 finished with value: 0.5983695652173913 and parameters: {'max_depth': 3, 'learning_rate': 0.10068119916495935, 'n_estimators': 1355, 'subsample': 0.6253064885380375, 'colsample_bytree': 0.5604547109991673, 'min_child_weight': 5, 'gamma': 4.125446047103232, 'reg_alpha': 0.1122789195984316, 'reg_lambda': 0.2540006997954997, 'max_delta_step': 10}. Best is trial 34 with value: 0.6358695652173914.

Best trial: 34. Best value: 0.63587:  96%|█████████▌| 48/50 [06:52<00:17,  8.78s/it]

[I 2025-12-01 16:42:48,772] Trial 46 finished with value: 0.5706521739130435 and parameters: {'max_depth': 3, 'learning_rate': 0.15306037988412913, 'n_estimators': 812, 'subsample': 0.5675586350365103, 'colsample_bytree': 0.5508919556752574, 'min_child_weight': 4, 'gamma': 4.182457287540568, 'reg_alpha': 0.06620347597412159, 'reg_lambda': 6.33986427349792e-06, 'max_delta_step': 2}. Best is trial 34 with value: 0.6358695652173914.

Best trial: 34. Best value: 0.63587:  98%|█████████▊| 49/50 [07:05<00:10, 10.02s/it]

[I 2025-12-01 16:43:01,685] Trial 48 finished with value: 0.5641304347826087 and parameters: {'max_depth': 3, 'learning_rate': 0.1607694291153171, 'n_estimators': 1174, 'subsample': 0.6817234793659478, 'colsample_bytree': 0.5546227083115639, 'min_child_weight': 4, 'gamma': 4.240927317507957, 'reg_alpha': 0.05358869272267815, 'reg_lambda': 6.458877820489644e-07, 'max_delta_step': 3}. Best is trial 34 with value: 0.6358695652173914.

Best trial: 49. Best value: 0.66087: 100%|██████████| 50/50 [07:14<00:00,  8.68s/it]

[I 2025-12-01 16:43:09,899] Trial 49 finished with value: 0.6608695652173913 and parameters: {'max_depth': 3, 'learning_rate': 0.11477064138825296, 'n_estimators': 1166, 'subsample': 0.5195762376024116, 'colsample_bytree': 0.6510851472670012, 'min_child_weight': 4, 'gamma': 2.6425641828713458, 'reg_alpha': 6.312782079628918e-08, 'reg_lambda': 4.414757511090811e-06, 'max_delta_step': 3}. Best is trial 49 with value: 0.6608695652173913.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 16:43:16,141] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 66, Test size: 17
Using Leave-One-Out CV with 66 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.469268:   2%|▏         | 1/50 [00:35<29:01, 35.54s/it]

[I 2025-12-01 16:43:51,671] Trial 0 finished with value: 0.46926829268292686 and parameters: {'max_depth': 5, 'learning_rate': 0.13026508642040383, 'n_estimators': 636, 'subsample': 0.6957340284476052, 'colsample_bytree': 0.5770455821054252, 'min_child_weight': 3, 'gamma': 0.9953246914675595, 'reg_alpha': 9.761046797832172e-08, 'reg_lambda': 0.00013199863778375772, 'max_delta_step': 9}. Best is trial 0 with value: 0.46926829268292686.

Best trial: 0. Best value: 0.469268:   4%|▍         | 2/50 [00:43<15:24, 19.27s/it]

[I 2025-12-01 16:43:59,552] Trial 3 finished with value: 0.44926829268292684 and parameters: {'max_depth': 9, 'learning_rate': 0.1489848880106022, 'n_estimators': 638, 'subsample': 0.6307560954555295, 'colsample_bytree': 0.7525991141047852, 'min_child_weight': 2, 'gamma': 3.049941537994499, 'reg_alpha': 4.700850291281434e-08, 'reg_lambda': 0.000876528009178146, 'max_delta_step': 5}. Best is trial 0 with value: 0.46926829268292686.

Best trial: 0. Best value: 0.469268:   6%|▌         | 3/50 [00:48<10:01, 12.79s/it]

[I 2025-12-01 16:44:04,621] Trial 1 finished with value: 0.036585365853658534 and parameters: {'max_depth': 7, 'learning_rate': 0.16859710233779093, 'n_estimators': 1037, 'subsample': 0.8835738913563502, 'colsample_bytree': 0.5159832877387045, 'min_child_weight': 10, 'gamma': 1.3312024084489509, 'reg_alpha': 0.08594404126259125, 'reg_lambda': 0.038484927561127376, 'max_delta_step': 10}. Best is trial 0 with value: 0.46926829268292686.

Best trial: 4. Best value: 0.497073:   8%|▊         | 4/50 [01:00<09:34, 12.49s/it]

[I 2025-12-01 16:44:16,641] Trial 4 finished with value: 0.4970731707317073 and parameters: {'max_depth': 8, 'learning_rate': 0.07253348371235115, 'n_estimators': 297, 'subsample': 0.5992460299161981, 'colsample_bytree': 0.965042237942356, 'min_child_weight': 4, 'gamma': 2.10645988886379, 'reg_alpha': 0.011084751169510179, 'reg_lambda': 3.736283010032913e-05, 'max_delta_step': 6}. Best is trial 4 with value: 0.4970731707317073.

Best trial: 4. Best value: 0.497073:  10%|█         | 5/50 [01:02<06:31,  8.70s/it]

[I 2025-12-01 16:44:18,623] Trial 2 finished with value: 0.45707317073170733 and parameters: {'max_depth': 8, 'learning_rate': 0.011079782971613304, 'n_estimators': 1042, 'subsample': 0.7484847802175932, 'colsample_bytree': 0.5448393498739337, 'min_child_weight': 7, 'gamma': 2.8015591853293076, 'reg_alpha': 1.9050697883562844e-07, 'reg_lambda': 0.04871895996711392, 'max_delta_step': 4}. Best is trial 4 with value: 0.4970731707317073.

Best trial: 4. Best value: 0.497073:  12%|█▏        | 6/50 [01:04<04:47,  6.54s/it]

[I 2025-12-01 16:44:20,966] Trial 6 finished with value: 0.37609756097560976 and parameters: {'max_depth': 3, 'learning_rate': 0.11130157568038922, 'n_estimators': 214, 'subsample': 0.741172190178504, 'colsample_bytree': 0.6928901088227863, 'min_child_weight': 8, 'gamma': 0.418542117188177, 'reg_alpha': 0.02377168656956024, 'reg_lambda': 0.2144199741677854, 'max_delta_step': 0}. Best is trial 4 with value: 0.4970731707317073.

Best trial: 4. Best value: 0.497073:  14%|█▍        | 7/50 [01:59<15:59, 22.30s/it]

[I 2025-12-01 16:45:15,732] Trial 8 finished with value: 0.2682926829268293 and parameters: {'max_depth': 3, 'learning_rate': 0.05959202469388484, 'n_estimators': 997, 'subsample': 0.6426388768348461, 'colsample_bytree': 0.8195173318879336, 'min_child_weight': 10, 'gamma': 1.1299966869811389, 'reg_alpha': 1.3321747479542065e-05, 'reg_lambda': 7.790485956096007e-05, 'max_delta_step': 4}. Best is trial 4 with value: 0.4970731707317073.

Best trial: 4. Best value: 0.497073:  16%|█▌        | 8/50 [02:15<14:12, 20.29s/it]

[I 2025-12-01 16:45:31,726] Trial 10 finished with value: 0.3960975609756098 and parameters: {'max_depth': 8, 'learning_rate': 0.201141534837515, 'n_estimators': 266, 'subsample': 0.9772936152965659, 'colsample_bytree': 0.6205107951033887, 'min_child_weight': 9, 'gamma': 0.3871859680512829, 'reg_alpha': 0.03227087580916562, 'reg_lambda': 1.0014620220441895e-05, 'max_delta_step': 0}. Best is trial 4 with value: 0.4970731707317073.

Best trial: 7. Best value: 0.521463:  18%|█▊        | 9/50 [02:22<10:58, 16.06s/it]

[I 2025-12-01 16:45:38,468] Trial 7 finished with value: 0.5214634146341464 and parameters: {'max_depth': 7, 'learning_rate': 0.06586209821672388, 'n_estimators': 984, 'subsample': 0.7663877872225004, 'colsample_bytree': 0.9829914742996521, 'min_child_weight': 3, 'gamma': 3.417960051628488, 'reg_alpha': 8.780905429438312e-07, 'reg_lambda': 0.0032940093099481965, 'max_delta_step': 3}. Best is trial 7 with value: 0.5214634146341464.

Best trial: 7. Best value: 0.521463:  20%|██        | 10/50 [02:22<07:28, 11.21s/it]

[I 2025-12-01 16:45:38,832] Trial 5 finished with value: 0.49365853658536585 and parameters: {'max_depth': 8, 'learning_rate': 0.05640981525081951, 'n_estimators': 1087, 'subsample': 0.9777479061032837, 'colsample_bytree': 0.8717895761470652, 'min_child_weight': 2, 'gamma': 0.5499201905863266, 'reg_alpha': 0.2976899713107261, 'reg_lambda': 0.8112701816790252, 'max_delta_step': 9}. Best is trial 7 with value: 0.5214634146341464.

Best trial: 7. Best value: 0.521463:  22%|██▏       | 11/50 [02:26<05:49,  8.96s/it]

[I 2025-12-01 16:45:42,668] Trial 11 pruned.

Best trial: 7. Best value: 0.521463:  24%|██▍       | 12/50 [02:31<04:55,  7.77s/it]

[I 2025-12-01 16:45:47,726] Trial 12 pruned.

Best trial: 7. Best value: 0.521463:  26%|██▌       | 13/50 [02:38<04:41,  7.61s/it]

[I 2025-12-01 16:45:54,962] Trial 13 pruned.

Best trial: 7. Best value: 0.521463:  28%|██▊       | 14/50 [02:42<03:52,  6.45s/it]

[I 2025-12-01 16:45:58,743] Trial 14 pruned.

Best trial: 7. Best value: 0.521463:  30%|███       | 15/50 [02:46<03:15,  5.59s/it]

[I 2025-12-01 16:46:02,341] Trial 16 pruned.

Best trial: 7. Best value: 0.521463:  32%|███▏      | 16/50 [02:47<02:21,  4.17s/it]

[I 2025-12-01 16:46:03,203] Trial 15 pruned.

Best trial: 7. Best value: 0.521463:  34%|███▍      | 17/50 [03:06<04:50,  8.80s/it]

[I 2025-12-01 16:46:22,764] Trial 19 pruned.

Best trial: 7. Best value: 0.521463:  36%|███▌      | 18/50 [03:12<04:09,  7.79s/it]

[I 2025-12-01 16:46:28,223] Trial 20 pruned.

Best trial: 7. Best value: 0.521463:  38%|███▊      | 19/50 [03:36<06:35, 12.77s/it]

[I 2025-12-01 16:46:52,584] Trial 17 finished with value: 0.4326829268292683 and parameters: {'max_depth': 6, 'learning_rate': 0.08493802720269775, 'n_estimators': 460, 'subsample': 0.8281066032306835, 'colsample_bytree': 0.9038996898742107, 'min_child_weight': 1, 'gamma': 3.5377363943561946, 'reg_alpha': 0.0011066069576917234, 'reg_lambda': 0.0032562911452453072, 'max_delta_step': 7}. Best is trial 7 with value: 0.5214634146341464.

Best trial: 7. Best value: 0.521463:  40%|████      | 20/50 [03:41<05:11, 10.39s/it]

[I 2025-12-01 16:46:57,434] Trial 18 finished with value: 0.4892682926829268 and parameters: {'max_depth': 6, 'learning_rate': 0.08034911672546867, 'n_estimators': 457, 'subsample': 0.8016888816115628, 'colsample_bytree': 0.9118444118259389, 'min_child_weight': 1, 'gamma': 2.091950525604223, 'reg_alpha': 0.0008694514641154333, 'reg_lambda': 5.155344376661127e-06, 'max_delta_step': 3}. Best is trial 7 with value: 0.5214634146341464.

Best trial: 7. Best value: 0.521463:  42%|████▏     | 21/50 [03:45<04:07,  8.53s/it]

[I 2025-12-01 16:47:01,632] Trial 9 finished with value: 0.45707317073170733 and parameters: {'max_depth': 7, 'learning_rate': 0.010679344520363131, 'n_estimators': 855, 'subsample': 0.763268124811209, 'colsample_bytree': 0.9127957907895585, 'min_child_weight': 1, 'gamma': 1.5835783838852713, 'reg_alpha': 6.826220820451364e-07, 'reg_lambda': 0.11040512175652976, 'max_delta_step': 7}. Best is trial 7 with value: 0.5214634146341464.

Best trial: 7. Best value: 0.521463:  44%|████▍     | 22/50 [04:06<05:47, 12.41s/it]

[I 2025-12-01 16:47:23,089] Trial 22 pruned.

Best trial: 7. Best value: 0.521463:  46%|████▌     | 23/50 [04:13<04:46, 10.61s/it]

[I 2025-12-01 16:47:29,506] Trial 21 finished with value: 0.5214634146341464 and parameters: {'max_depth': 6, 'learning_rate': 0.08714670592308985, 'n_estimators': 898, 'subsample': 0.5915405218327427, 'colsample_bytree': 0.929313538306219, 'min_child_weight': 3, 'gamma': 2.2143578610562433, 'reg_alpha': 0.0032707361396295395, 'reg_lambda': 0.0028565611760655594, 'max_delta_step': 6}. Best is trial 7 with value: 0.5214634146341464.

Best trial: 7. Best value: 0.521463:  48%|████▊     | 24/50 [04:15<03:29,  8.08s/it]

[I 2025-12-01 16:47:31,664] Trial 23 pruned.

Best trial: 7. Best value: 0.521463:  50%|█████     | 25/50 [04:31<04:23, 10.55s/it]

[I 2025-12-01 16:47:47,996] Trial 24 pruned.

Best trial: 7. Best value: 0.521463:  52%|█████▏    | 26/50 [04:51<05:16, 13.20s/it]

[I 2025-12-01 16:48:07,382] Trial 27 pruned.

Best trial: 7. Best value: 0.521463:  54%|█████▍    | 27/50 [04:54<03:51, 10.07s/it]

[I 2025-12-01 16:48:10,152] Trial 26 pruned.

Best trial: 7. Best value: 0.521463:  56%|█████▌    | 28/50 [05:02<03:31,  9.62s/it]

[I 2025-12-01 16:48:18,725] Trial 28 pruned.

Best trial: 7. Best value: 0.521463:  58%|█████▊    | 29/50 [05:07<02:50,  8.10s/it]

[I 2025-12-01 16:48:23,266] Trial 25 pruned.

Best trial: 7. Best value: 0.521463:  60%|██████    | 30/50 [05:16<02:48,  8.41s/it]

[I 2025-12-01 16:48:32,382] Trial 32 pruned.

Best trial: 7. Best value: 0.521463:  62%|██████▏   | 31/50 [05:21<02:18,  7.31s/it]

[I 2025-12-01 16:48:37,148] Trial 33 pruned.

Best trial: 7. Best value: 0.521463:  64%|██████▍   | 32/50 [05:22<01:41,  5.65s/it]

[I 2025-12-01 16:48:38,901] Trial 30 pruned.

Best trial: 7. Best value: 0.521463:  66%|██████▌   | 33/50 [05:35<02:14,  7.90s/it]

[I 2025-12-01 16:48:52,068] Trial 35 pruned.

Best trial: 7. Best value: 0.521463:  68%|██████▊   | 34/50 [05:53<02:54, 10.88s/it]

[I 2025-12-01 16:49:09,887] Trial 29 finished with value: 0.4814634146341464 and parameters: {'max_depth': 7, 'learning_rate': 0.09968946315094326, 'n_estimators': 742, 'subsample': 0.6795590026469521, 'colsample_bytree': 0.9433532770305529, 'min_child_weight': 2, 'gamma': 3.1746216186302396, 'reg_alpha': 0.006425031676888768, 'reg_lambda': 0.00046763861652041603, 'max_delta_step': 6}. Best is trial 7 with value: 0.5214634146341464.

Best trial: 7. Best value: 0.521463:  70%|███████   | 35/50 [06:03<02:36, 10.45s/it]

[I 2025-12-01 16:49:19,335] Trial 31 finished with value: 0.4770731707317073 and parameters: {'max_depth': 7, 'learning_rate': 0.06961904333563024, 'n_estimators': 758, 'subsample': 0.6722146907502449, 'colsample_bytree': 0.7693677543860389, 'min_child_weight': 2, 'gamma': 3.095367324882623, 'reg_alpha': 8.235066195806801e-05, 'reg_lambda': 0.0005402799804401115, 'max_delta_step': 4}. Best is trial 7 with value: 0.5214634146341464.

Best trial: 7. Best value: 0.521463:  72%|███████▏  | 36/50 [06:03<01:43,  7.39s/it]

[I 2025-12-01 16:49:19,592] Trial 37 pruned.

Best trial: 7. Best value: 0.521463:  74%|███████▍  | 37/50 [06:11<01:38,  7.58s/it]

[I 2025-12-01 16:49:27,618] Trial 39 pruned.

Best trial: 7. Best value: 0.521463:  76%|███████▌  | 38/50 [06:13<01:11,  5.93s/it]

[I 2025-12-01 16:49:29,628] Trial 38 pruned.

Best trial: 7. Best value: 0.521463:  78%|███████▊  | 39/50 [06:21<01:10,  6.41s/it]

[I 2025-12-01 16:49:37,214] Trial 41 pruned.

Best trial: 7. Best value: 0.521463:  80%|████████  | 40/50 [06:33<01:21,  8.15s/it]

[I 2025-12-01 16:49:49,444] Trial 42 pruned.

Best trial: 7. Best value: 0.521463:  82%|████████▏ | 41/50 [06:34<00:54,  6.10s/it]

[I 2025-12-01 16:49:50,757] Trial 40 pruned.

Best trial: 7. Best value: 0.521463:  84%|████████▍ | 42/50 [06:41<00:50,  6.26s/it]

[I 2025-12-01 16:49:57,402] Trial 44 pruned.

Best trial: 7. Best value: 0.521463:  86%|████████▌ | 43/50 [06:47<00:42,  6.14s/it]

[I 2025-12-01 16:50:03,240] Trial 45 pruned.

Best trial: 7. Best value: 0.521463:  88%|████████▊ | 44/50 [06:55<00:40,  6.68s/it]

[I 2025-12-01 16:50:11,185] Trial 34 finished with value: 0.4370731707317073 and parameters: {'max_depth': 8, 'learning_rate': 0.06593449628872868, 'n_estimators': 957, 'subsample': 0.9038118371033508, 'colsample_bytree': 0.8875698900003428, 'min_child_weight': 2, 'gamma': 1.678337911265277, 'reg_alpha': 0.5208281942438203, 'reg_lambda': 0.720084316582143, 'max_delta_step': 9}. Best is trial 7 with value: 0.5214634146341464.

Best trial: 7. Best value: 0.521463:  90%|█████████ | 45/50 [07:02<00:34,  6.80s/it]

[I 2025-12-01 16:50:18,282] Trial 43 pruned.

Best trial: 7. Best value: 0.521463:  92%|█████████▏| 46/50 [07:03<00:20,  5.16s/it]

[I 2025-12-01 16:50:19,621] Trial 47 pruned.

Best trial: 7. Best value: 0.521463:  94%|█████████▍| 47/50 [07:22<00:28,  9.39s/it]

[I 2025-12-01 16:50:38,887] Trial 36 finished with value: 0.4814634146341464 and parameters: {'max_depth': 9, 'learning_rate': 0.03298054925129826, 'n_estimators': 1096, 'subsample': 0.9061452753450463, 'colsample_bytree': 0.9343055983832628, 'min_child_weight': 2, 'gamma': 0.8140288255228814, 'reg_alpha': 0.04793006982517385, 'reg_lambda': 0.0244496964267941, 'max_delta_step': 3}. Best is trial 7 with value: 0.5214634146341464.

Best trial: 7. Best value: 0.521463:  96%|█████████▌| 48/50 [07:32<00:18,  9.50s/it]

[I 2025-12-01 16:50:48,616] Trial 46 finished with value: 0.46146341463414636 and parameters: {'max_depth': 7, 'learning_rate': 0.05769322007815149, 'n_estimators': 316, 'subsample': 0.998871339329269, 'colsample_bytree': 0.9713226725042586, 'min_child_weight': 2, 'gamma': 1.2443668457277266, 'reg_alpha': 0.00045981633357404517, 'reg_lambda': 3.8577826603046197e-07, 'max_delta_step': 1}. Best is trial 7 with value: 0.5214634146341464.

Best trial: 7. Best value: 0.521463:  98%|█████████▊| 49/50 [07:50<00:12, 12.10s/it]

[I 2025-12-01 16:51:06,781] Trial 49 finished with value: 0.5214634146341464 and parameters: {'max_depth': 6, 'learning_rate': 0.04178123368045924, 'n_estimators': 296, 'subsample': 0.9940641730013801, 'colsample_bytree': 0.9793770911625859, 'min_child_weight': 1, 'gamma': 1.174524907734174, 'reg_alpha': 0.0630206830401157, 'reg_lambda': 5.060456980998642e-07, 'max_delta_step': 5}. Best is trial 7 with value: 0.5214634146341464.

Best trial: 7. Best value: 0.521463: 100%|██████████| 50/50 [08:04<00:00,  9.68s/it]

[I 2025-12-01 16:51:20,155] Trial 48 finished with value: 0.4970731707317073 and parameters: {'max_depth': 7, 'learning_rate': 0.05644792894248338, 'n_estimators': 589, 'subsample': 0.9996484103346067, 'colsample_bytree': 0.9767450399911568, 'min_child_weight': 1, 'gamma': 1.2502728292474696, 'reg_alpha': 0.04927950744433492, 'reg_lambda': 0.08375314678194161, 'max_delta_step': 5}. Best is trial 7 with value: 0.5214634146341464.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 16:51:26,423] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 64, Test size: 16
Using Leave-One-Out CV with 64 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.579167:   2%|▏         | 1/50 [00:21<17:27, 21.38s/it]

[I 2025-12-01 16:51:47,795] Trial 3 finished with value: 0.5791666666666666 and parameters: {'max_depth': 8, 'learning_rate': 0.21625981960403612, 'n_estimators': 383, 'subsample': 0.8274946456510224, 'colsample_bytree': 0.523035055817054, 'min_child_weight': 4, 'gamma': 0.9171214601569211, 'reg_alpha': 0.008815486532269478, 'reg_lambda': 9.47050567323647e-07, 'max_delta_step': 1}. Best is trial 3 with value: 0.5791666666666666.

Best trial: 3. Best value: 0.579167:   4%|▍         | 2/50 [00:30<11:25, 14.28s/it]

[I 2025-12-01 16:51:57,107] Trial 1 finished with value: 0.225 and parameters: {'max_depth': 5, 'learning_rate': 0.011848644374226076, 'n_estimators': 597, 'subsample': 0.8068969482881295, 'colsample_bytree': 0.9930920567400047, 'min_child_weight': 9, 'gamma': 0.8430151885480297, 'reg_alpha': 0.001542979393084358, 'reg_lambda': 3.494750487741174e-07, 'max_delta_step': 7}. Best is trial 3 with value: 0.5791666666666666.

Best trial: 4. Best value: 0.625:   6%|▌         | 3/50 [00:46<11:34, 14.78s/it]

[I 2025-12-01 16:52:12,490] Trial 4 finished with value: 0.625 and parameters: {'max_depth': 4, 'learning_rate': 0.13367214994879995, 'n_estimators': 430, 'subsample': 0.5599485914077389, 'colsample_bytree': 0.8239560432940745, 'min_child_weight': 6, 'gamma': 4.967492992269397, 'reg_alpha': 9.808643970321536e-08, 'reg_lambda': 2.960977874773875e-06, 'max_delta_step': 10}. Best is trial 4 with value: 0.625.

Best trial: 2. Best value: 0.695833:   8%|▊         | 4/50 [00:54<09:19, 12.16s/it]

[I 2025-12-01 16:52:20,626] Trial 2 finished with value: 0.6958333333333333 and parameters: {'max_depth': 5, 'learning_rate': 0.10729699080611124, 'n_estimators': 965, 'subsample': 0.7491679883257748, 'colsample_bytree': 0.7644766434598345, 'min_child_weight': 3, 'gamma': 1.175753345389925, 'reg_alpha': 0.36450644734112086, 'reg_lambda': 2.776923073609667e-07, 'max_delta_step': 4}. Best is trial 2 with value: 0.6958333333333333.

Best trial: 2. Best value: 0.695833:  10%|█         | 5/50 [01:01<07:48, 10.42s/it]

[I 2025-12-01 16:52:27,960] Trial 5 finished with value: 0.6375 and parameters: {'max_depth': 5, 'learning_rate': 0.17399185417911384, 'n_estimators': 358, 'subsample': 0.969422687014829, 'colsample_bytree': 0.590531308076585, 'min_child_weight': 1, 'gamma': 0.6691076347716585, 'reg_alpha': 2.7240663309548714e-07, 'reg_lambda': 0.00096474962587932, 'max_delta_step': 10}. Best is trial 2 with value: 0.6958333333333333.

Best trial: 2. Best value: 0.695833:  12%|█▏        | 6/50 [01:30<12:11, 16.62s/it]

[I 2025-12-01 16:52:56,602] Trial 0 finished with value: 0.625 and parameters: {'max_depth': 4, 'learning_rate': 0.018810363966619312, 'n_estimators': 1441, 'subsample': 0.8658195523784735, 'colsample_bytree': 0.7872873142841349, 'min_child_weight': 5, 'gamma': 1.0464892907667815, 'reg_alpha': 0.49904524588005766, 'reg_lambda': 0.027717625270032523, 'max_delta_step': 8}. Best is trial 2 with value: 0.6958333333333333.

Best trial: 2. Best value: 0.695833:  14%|█▍        | 7/50 [01:42<10:58, 15.32s/it]

[I 2025-12-01 16:53:09,263] Trial 8 finished with value: 0.6 and parameters: {'max_depth': 8, 'learning_rate': 0.21734598075747477, 'n_estimators': 453, 'subsample': 0.9389372861889654, 'colsample_bytree': 0.7817941067431736, 'min_child_weight': 1, 'gamma': 1.7582932022761777, 'reg_alpha': 2.608187168101987e-05, 'reg_lambda': 5.112064988187833e-06, 'max_delta_step': 1}. Best is trial 2 with value: 0.6958333333333333.

Best trial: 2. Best value: 0.695833:  16%|█▌        | 8/50 [02:03<11:54, 17.00s/it]

[I 2025-12-01 16:53:29,858] Trial 7 finished with value: 0.6583333333333333 and parameters: {'max_depth': 10, 'learning_rate': 0.0166149805642283, 'n_estimators': 820, 'subsample': 0.5766792398990231, 'colsample_bytree': 0.7960418026427424, 'min_child_weight': 2, 'gamma': 2.593947235682081, 'reg_alpha': 0.0010306485993016447, 'reg_lambda': 0.06155219566419712, 'max_delta_step': 10}. Best is trial 2 with value: 0.6958333333333333.

Best trial: 2. Best value: 0.695833:  18%|█▊        | 9/50 [02:07<08:50, 12.95s/it]

[I 2025-12-01 16:53:33,902] Trial 6 finished with value: 0.6708333333333334 and parameters: {'max_depth': 9, 'learning_rate': 0.1309251685630811, 'n_estimators': 1404, 'subsample': 0.7886024797098581, 'colsample_bytree': 0.5272078481374067, 'min_child_weight': 2, 'gamma': 1.3249903544503139, 'reg_alpha': 1.8807205780397587, 'reg_lambda': 0.01478793252021011, 'max_delta_step': 2}. Best is trial 2 with value: 0.6958333333333333.

Best trial: 2. Best value: 0.695833:  20%|██        | 10/50 [02:30<10:41, 16.03s/it]

[I 2025-12-01 16:53:56,835] Trial 9 finished with value: 0.6541666666666667 and parameters: {'max_depth': 5, 'learning_rate': 0.10915593246623939, 'n_estimators': 665, 'subsample': 0.7877768177293044, 'colsample_bytree': 0.8420702053054852, 'min_child_weight': 1, 'gamma': 3.884519356676466, 'reg_alpha': 4.995292911172613e-07, 'reg_lambda': 0.0014475272039777597, 'max_delta_step': 5}. Best is trial 2 with value: 0.6958333333333333.

Best trial: 2. Best value: 0.695833:  22%|██▏       | 11/50 [02:34<08:03, 12.39s/it]

[I 2025-12-01 16:54:00,955] Trial 11 pruned.

Best trial: 2. Best value: 0.695833:  24%|██▍       | 12/50 [02:39<06:29, 10.24s/it]

[I 2025-12-01 16:54:06,279] Trial 13 pruned.

Best trial: 2. Best value: 0.695833:  26%|██▌       | 13/50 [02:45<05:26,  8.82s/it]

[I 2025-12-01 16:54:11,854] Trial 14 pruned.

Best trial: 2. Best value: 0.695833:  28%|██▊       | 14/50 [03:03<06:57, 11.59s/it]

[I 2025-12-01 16:54:29,842] Trial 10 finished with value: 0.6625 and parameters: {'max_depth': 4, 'learning_rate': 0.03041311672557874, 'n_estimators': 1334, 'subsample': 0.6448457722914673, 'colsample_bytree': 0.8224272524548297, 'min_child_weight': 3, 'gamma': 2.219486627216688, 'reg_alpha': 0.0006967039634494815, 'reg_lambda': 3.2028230568488813e-07, 'max_delta_step': 9}. Best is trial 2 with value: 0.6958333333333333.

Best trial: 2. Best value: 0.695833:  30%|███       | 15/50 [03:23<08:10, 14.02s/it]

[I 2025-12-01 16:54:49,465] Trial 15 pruned.

Best trial: 2. Best value: 0.695833:  32%|███▏      | 16/50 [03:23<05:41, 10.04s/it]

[I 2025-12-01 16:54:50,268] Trial 12 finished with value: 0.6833333333333333 and parameters: {'max_depth': 6, 'learning_rate': 0.05639837916630231, 'n_estimators': 1045, 'subsample': 0.6288623309544633, 'colsample_bytree': 0.8480172148554439, 'min_child_weight': 2, 'gamma': 3.930254401864095, 'reg_alpha': 3.037011026012661e-08, 'reg_lambda': 0.0030834793296877273, 'max_delta_step': 3}. Best is trial 2 with value: 0.6958333333333333.

Best trial: 2. Best value: 0.695833:  34%|███▍      | 17/50 [03:33<05:30, 10.02s/it]

[I 2025-12-01 16:55:00,250] Trial 17 pruned.

Best trial: 2. Best value: 0.695833:  36%|███▌      | 18/50 [03:35<03:56,  7.38s/it]

[I 2025-12-01 16:55:01,467] Trial 18 pruned.

Best trial: 2. Best value: 0.695833:  38%|███▊      | 19/50 [03:42<03:48,  7.37s/it]

[I 2025-12-01 16:55:08,842] Trial 20 pruned.

Best trial: 2. Best value: 0.695833:  40%|████      | 20/50 [03:43<02:42,  5.41s/it]

[I 2025-12-01 16:55:09,656] Trial 21 pruned.

Best trial: 2. Best value: 0.695833:  42%|████▏     | 21/50 [03:51<02:57,  6.12s/it]

[I 2025-12-01 16:55:17,435] Trial 22 pruned.

Best trial: 16. Best value: 0.704167:  44%|████▍     | 22/50 [03:51<02:03,  4.43s/it]

[I 2025-12-01 16:55:17,921] Trial 16 finished with value: 0.7041666666666666 and parameters: {'max_depth': 10, 'learning_rate': 0.08766618356336629, 'n_estimators': 1058, 'subsample': 0.8844480326291604, 'colsample_bytree': 0.6967447066835555, 'min_child_weight': 3, 'gamma': 1.4397398363430791, 'reg_alpha': 0.12479120081026325, 'reg_lambda': 6.935501355402376e-05, 'max_delta_step': 3}. Best is trial 16 with value: 0.7041666666666666.

Best trial: 16. Best value: 0.704167:  46%|████▌     | 23/50 [03:57<02:11,  4.86s/it]

[I 2025-12-01 16:55:23,775] Trial 19 pruned.

Best trial: 16. Best value: 0.704167:  48%|████▊     | 24/50 [05:00<09:39, 22.29s/it]

[I 2025-12-01 16:56:26,739] Trial 23 finished with value: 0.65 and parameters: {'max_depth': 6, 'learning_rate': 0.27474973818576287, 'n_estimators': 1167, 'subsample': 0.6040126576508743, 'colsample_bytree': 0.8741747847762076, 'min_child_weight': 2, 'gamma': 3.2159656194544364, 'reg_alpha': 1.0498535333365339e-08, 'reg_lambda': 0.5812328315048237, 'max_delta_step': 4}. Best is trial 16 with value: 0.7041666666666666.

Best trial: 16. Best value: 0.704167:  50%|█████     | 25/50 [05:16<08:30, 20.43s/it]

[I 2025-12-01 16:56:42,837] Trial 25 finished with value: 0.6375 and parameters: {'max_depth': 8, 'learning_rate': 0.07335812497274863, 'n_estimators': 1150, 'subsample': 0.7522332277447684, 'colsample_bytree': 0.7477219088724145, 'min_child_weight': 2, 'gamma': 3.134931373058297, 'reg_alpha': 0.006215993540608116, 'reg_lambda': 0.46233061761653066, 'max_delta_step': 2}. Best is trial 16 with value: 0.7041666666666666.

Best trial: 16. Best value: 0.704167:  52%|█████▏    | 26/50 [05:22<06:23, 15.98s/it]

[I 2025-12-01 16:56:48,430] Trial 26 finished with value: 0.6708333333333334 and parameters: {'max_depth': 8, 'learning_rate': 0.06712376410651424, 'n_estimators': 1172, 'subsample': 0.737228902799635, 'colsample_bytree': 0.7438734713082381, 'min_child_weight': 2, 'gamma': 3.16069811998193, 'reg_alpha': 0.008274491457963905, 'reg_lambda': 0.3313688970295876, 'max_delta_step': 2}. Best is trial 16 with value: 0.7041666666666666.

Best trial: 16. Best value: 0.704167:  54%|█████▍    | 27/50 [05:32<05:30, 14.39s/it]

[I 2025-12-01 16:56:59,112] Trial 24 finished with value: 0.6916666666666667 and parameters: {'max_depth': 8, 'learning_rate': 0.06758746839950162, 'n_estimators': 1460, 'subsample': 0.7359520640502639, 'colsample_bytree': 0.7417784466861301, 'min_child_weight': 2, 'gamma': 3.0374885920232533, 'reg_alpha': 0.010214603174875578, 'reg_lambda': 0.016384028928472644, 'max_delta_step': 2}. Best is trial 16 with value: 0.7041666666666666.

Best trial: 27. Best value: 0.716667:  56%|█████▌    | 28/50 [05:44<04:59, 13.59s/it]

[I 2025-12-01 16:57:10,840] Trial 27 finished with value: 0.7166666666666667 and parameters: {'max_depth': 8, 'learning_rate': 0.06752409296025376, 'n_estimators': 666, 'subsample': 0.7376536565588135, 'colsample_bytree': 0.7419133687809396, 'min_child_weight': 4, 'gamma': 1.5501653956929928, 'reg_alpha': 0.010093061325181162, 'reg_lambda': 0.00035622324506183375, 'max_delta_step': 2}. Best is trial 27 with value: 0.7166666666666667.

Best trial: 27. Best value: 0.716667:  58%|█████▊    | 29/50 [05:45<03:23,  9.71s/it]

[I 2025-12-01 16:57:11,482] Trial 30 pruned.

Best trial: 27. Best value: 0.716667:  60%|██████    | 30/50 [05:50<02:51,  8.56s/it]

[I 2025-12-01 16:57:17,354] Trial 31 pruned.

Best trial: 27. Best value: 0.716667:  62%|██████▏   | 31/50 [05:53<02:09,  6.81s/it]

[I 2025-12-01 16:57:20,089] Trial 32 pruned.

Best trial: 27. Best value: 0.716667:  64%|██████▍   | 32/50 [05:59<01:56,  6.46s/it]

[I 2025-12-01 16:57:25,738] Trial 33 pruned.

Best trial: 27. Best value: 0.716667:  66%|██████▌   | 33/50 [06:03<01:38,  5.78s/it]

[I 2025-12-01 16:57:29,931] Trial 28 finished with value: 0.6583333333333333 and parameters: {'max_depth': 7, 'learning_rate': 0.05946269288803686, 'n_estimators': 737, 'subsample': 0.7201749357535816, 'colsample_bytree': 0.6033096176432654, 'min_child_weight': 4, 'gamma': 1.7169926416684276, 'reg_alpha': 0.019177772541496236, 'reg_lambda': 7.101788976171869e-06, 'max_delta_step': 2}. Best is trial 27 with value: 0.7166666666666667.

Best trial: 27. Best value: 0.716667:  68%|██████▊   | 34/50 [06:15<02:03,  7.72s/it]

[I 2025-12-01 16:57:42,186] Trial 29 finished with value: 0.7041666666666666 and parameters: {'max_depth': 7, 'learning_rate': 0.04713450997753977, 'n_estimators': 800, 'subsample': 0.8442706411227505, 'colsample_bytree': 0.6065101787220455, 'min_child_weight': 4, 'gamma': 0.4662222133011483, 'reg_alpha': 0.00013896813765881298, 'reg_lambda': 0.00028369377195211796, 'max_delta_step': 4}. Best is trial 27 with value: 0.7166666666666667.

Best trial: 27. Best value: 0.716667:  70%|███████   | 35/50 [06:23<01:55,  7.70s/it]

[I 2025-12-01 16:57:49,850] Trial 34 finished with value: 0.6708333333333334 and parameters: {'max_depth': 7, 'learning_rate': 0.04744321055366735, 'n_estimators': 201, 'subsample': 0.712571474688165, 'colsample_bytree': 0.7801514472257338, 'min_child_weight': 3, 'gamma': 2.082104206883687, 'reg_alpha': 0.03431886409962806, 'reg_lambda': 0.010561960792933749, 'max_delta_step': 1}. Best is trial 27 with value: 0.7166666666666667.

Best trial: 27. Best value: 0.716667:  72%|███████▏  | 36/50 [06:38<02:20, 10.06s/it]

[I 2025-12-01 16:58:05,390] Trial 35 finished with value: 0.6708333333333334 and parameters: {'max_depth': 7, 'learning_rate': 0.08527009469010775, 'n_estimators': 525, 'subsample': 0.714402709836042, 'colsample_bytree': 0.7039970293614085, 'min_child_weight': 3, 'gamma': 2.0880946527299917, 'reg_alpha': 0.03190333215298804, 'reg_lambda': 0.006759300177243805, 'max_delta_step': 1}. Best is trial 27 with value: 0.7166666666666667.

Best trial: 27. Best value: 0.716667:  74%|███████▍  | 37/50 [06:52<02:23, 11.04s/it]

[I 2025-12-01 16:58:18,734] Trial 39 pruned.

Best trial: 27. Best value: 0.716667:  76%|███████▌  | 38/50 [06:58<01:55,  9.62s/it]

[I 2025-12-01 16:58:25,027] Trial 37 finished with value: 0.6916666666666667 and parameters: {'max_depth': 7, 'learning_rate': 0.0886099237395691, 'n_estimators': 539, 'subsample': 0.9213353323367247, 'colsample_bytree': 0.7122283865632744, 'min_child_weight': 3, 'gamma': 0.8119980691691233, 'reg_alpha': 0.00021068346940165578, 'reg_lambda': 0.0005624451101823042, 'max_delta_step': 7}. Best is trial 27 with value: 0.7166666666666667.

Best trial: 27. Best value: 0.716667:  78%|███████▊  | 39/50 [07:02<01:27,  7.99s/it]

[I 2025-12-01 16:58:29,233] Trial 38 finished with value: 0.6375 and parameters: {'max_depth': 5, 'learning_rate': 0.08313120061502755, 'n_estimators': 519, 'subsample': 0.7750242226924045, 'colsample_bytree': 0.5506066537327687, 'min_child_weight': 4, 'gamma': 0.873550120809702, 'reg_alpha': 0.00015393062821863367, 'reg_lambda': 0.0004922790301188484, 'max_delta_step': 7}. Best is trial 27 with value: 0.7166666666666667.

Best trial: 27. Best value: 0.716667:  80%|████████  | 40/50 [07:03<00:59,  5.93s/it]

[I 2025-12-01 16:58:30,318] Trial 40 pruned.

Best trial: 27. Best value: 0.716667:  82%|████████▏ | 41/50 [07:08<00:49,  5.52s/it]

[I 2025-12-01 16:58:34,903] Trial 41 pruned.

Best trial: 27. Best value: 0.716667:  84%|████████▍ | 42/50 [07:12<00:41,  5.18s/it]

[I 2025-12-01 16:58:39,306] Trial 36 finished with value: 0.7125 and parameters: {'max_depth': 8, 'learning_rate': 0.08275649385901977, 'n_estimators': 964, 'subsample': 0.7656624566153393, 'colsample_bytree': 0.6956005251935253, 'min_child_weight': 3, 'gamma': 2.780133968700619, 'reg_alpha': 0.028413467358670032, 'reg_lambda': 1.0613066558571658e-06, 'max_delta_step': 1}. Best is trial 27 with value: 0.7166666666666667.

Best trial: 27. Best value: 0.716667:  86%|████████▌ | 43/50 [07:13<00:26,  3.77s/it]

[I 2025-12-01 16:58:39,793] Trial 43 pruned.

Best trial: 27. Best value: 0.716667:  88%|████████▊ | 44/50 [07:14<00:17,  2.93s/it]

[I 2025-12-01 16:58:40,743] Trial 42 pruned.

Best trial: 27. Best value: 0.716667:  90%|█████████ | 45/50 [07:22<00:22,  4.52s/it]

[I 2025-12-01 16:58:48,980] Trial 46 pruned.

Best trial: 27. Best value: 0.716667:  92%|█████████▏| 46/50 [07:23<00:13,  3.40s/it]

[I 2025-12-01 16:58:49,760] Trial 44 pruned.

Best trial: 27. Best value: 0.716667:  94%|█████████▍| 47/50 [07:24<00:08,  2.71s/it]

[I 2025-12-01 16:58:50,852] Trial 47 pruned.

Best trial: 27. Best value: 0.716667:  96%|█████████▌| 48/50 [07:28<00:06,  3.21s/it]

[I 2025-12-01 16:58:55,238] Trial 45 pruned.

Best trial: 27. Best value: 0.716667:  98%|█████████▊| 49/50 [07:32<00:03,  3.46s/it]

[I 2025-12-01 16:58:59,296] Trial 49 pruned.

Best trial: 27. Best value: 0.716667: 100%|██████████| 50/50 [07:36<00:00,  9.12s/it]

[I 2025-12-01 16:59:02,563] Trial 48 pruned.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 16:59:10,749] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 67, Test size: 17
Using Leave-One-Out CV with 67 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.610694:   2%|▏         | 1/50 [00:40<32:54, 40.30s/it]

[I 2025-12-01 16:59:51,037] Trial 1 finished with value: 0.6106941838649156 and parameters: {'max_depth': 7, 'learning_rate': 0.06218313580068132, 'n_estimators': 657, 'subsample': 0.951058821759283, 'colsample_bytree': 0.7836431773996229, 'min_child_weight': 9, 'gamma': 4.614313891392157, 'reg_alpha': 0.270348957975892, 'reg_lambda': 1.091496302977937e-07, 'max_delta_step': 7}. Best is trial 1 with value: 0.6106941838649156.

Best trial: 1. Best value: 0.610694:   4%|▍         | 2/50 [00:49<17:31, 21.92s/it]

[I 2025-12-01 17:00:00,073] Trial 3 finished with value: 0.36585365853658536 and parameters: {'max_depth': 9, 'learning_rate': 0.23700483747886567, 'n_estimators': 849, 'subsample': 0.8756801613364036, 'colsample_bytree': 0.5514643312615433, 'min_child_weight': 10, 'gamma': 0.15008740294155443, 'reg_alpha': 0.46658624942987276, 'reg_lambda': 5.526496512512535e-08, 'max_delta_step': 9}. Best is trial 1 with value: 0.6106941838649156.

Best trial: 1. Best value: 0.610694:   6%|▌         | 3/50 [00:57<12:16, 15.66s/it]

[I 2025-12-01 17:00:08,302] Trial 2 finished with value: 0.2804878048780488 and parameters: {'max_depth': 9, 'learning_rate': 0.02028504602781579, 'n_estimators': 994, 'subsample': 0.7421289353113925, 'colsample_bytree': 0.5203185544575012, 'min_child_weight': 9, 'gamma': 1.7032481628400182, 'reg_alpha': 0.0063098758713702515, 'reg_lambda': 1.21051619455499, 'max_delta_step': 3}. Best is trial 1 with value: 0.6106941838649156.

Best trial: 1. Best value: 0.610694:   8%|▊         | 4/50 [01:20<14:16, 18.62s/it]

[I 2025-12-01 17:00:31,464] Trial 0 finished with value: 0.5548780487804879 and parameters: {'max_depth': 10, 'learning_rate': 0.25902060302912033, 'n_estimators': 1372, 'subsample': 0.776341827660818, 'colsample_bytree': 0.7242731121569268, 'min_child_weight': 9, 'gamma': 2.231487767197719, 'reg_alpha': 2.186085038252324, 'reg_lambda': 2.5297048099070505, 'max_delta_step': 1}. Best is trial 1 with value: 0.6106941838649156.

Best trial: 6. Best value: 0.697936:  10%|█         | 5/50 [01:32<12:00, 16.00s/it]

[I 2025-12-01 17:00:42,828] Trial 6 finished with value: 0.6979362101313321 and parameters: {'max_depth': 4, 'learning_rate': 0.1491660229818428, 'n_estimators': 339, 'subsample': 0.8474675628529441, 'colsample_bytree': 0.8805134611433385, 'min_child_weight': 5, 'gamma': 4.338540516001775, 'reg_alpha': 0.0002643539159517772, 'reg_lambda': 7.448158266534603e-08, 'max_delta_step': 8}. Best is trial 6 with value: 0.6979362101313321.

Best trial: 6. Best value: 0.697936:  12%|█▏        | 6/50 [02:13<17:59, 24.52s/it]

[I 2025-12-01 17:01:23,891] Trial 4 finished with value: 0.6735459662288931 and parameters: {'max_depth': 9, 'learning_rate': 0.05518161261269335, 'n_estimators': 1310, 'subsample': 0.882418088556468, 'colsample_bytree': 0.6215860184923281, 'min_child_weight': 8, 'gamma': 0.8493387487349513, 'reg_alpha': 0.021099514902150996, 'reg_lambda': 1.517333733248246e-06, 'max_delta_step': 0}. Best is trial 6 with value: 0.6979362101313321.

Best trial: 6. Best value: 0.697936:  14%|█▍        | 7/50 [02:24<14:35, 20.37s/it]

[I 2025-12-01 17:01:35,713] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.0249089288958188, 'n_estimators': 1396, 'subsample': 0.9247989518235615, 'colsample_bytree': 0.7103517259583938, 'min_child_weight': 10, 'gamma': 2.2697290336718607, 'reg_alpha': 8.15683777743303, 'reg_lambda': 2.3108140801396853e-08, 'max_delta_step': 7}. Best is trial 6 with value: 0.6979362101313321.

Best trial: 6. Best value: 0.697936:  16%|█▌        | 8/50 [02:55<16:35, 23.70s/it]

[I 2025-12-01 17:02:06,535] Trial 10 finished with value: 0.6299249530956847 and parameters: {'max_depth': 6, 'learning_rate': 0.033482583140613746, 'n_estimators': 330, 'subsample': 0.7074567525703324, 'colsample_bytree': 0.6349027538927965, 'min_child_weight': 6, 'gamma': 3.296001812990124, 'reg_alpha': 1.7177675386353868e-08, 'reg_lambda': 8.759975212126732e-06, 'max_delta_step': 7}. Best is trial 6 with value: 0.6979362101313321.

Best trial: 6. Best value: 0.697936:  18%|█▊        | 9/50 [03:02<12:29, 18.29s/it]

[I 2025-12-01 17:02:12,922] Trial 8 finished with value: 0.6683864915572233 and parameters: {'max_depth': 10, 'learning_rate': 0.04425585760555395, 'n_estimators': 1312, 'subsample': 0.9435829368683232, 'colsample_bytree': 0.6534162667340679, 'min_child_weight': 8, 'gamma': 4.016143041070713, 'reg_alpha': 8.273595791892836e-05, 'reg_lambda': 2.8519980108765023e-07, 'max_delta_step': 9}. Best is trial 6 with value: 0.6979362101313321.

Best trial: 7. Best value: 0.722326:  20%|██        | 10/50 [03:17<11:38, 17.45s/it]

[I 2025-12-01 17:02:28,508] Trial 7 finished with value: 0.722326454033771 and parameters: {'max_depth': 6, 'learning_rate': 0.029086433810504943, 'n_estimators': 1041, 'subsample': 0.9584698114314141, 'colsample_bytree': 0.7950821660317646, 'min_child_weight': 4, 'gamma': 1.6599592351243841, 'reg_alpha': 3.8305936529645715e-07, 'reg_lambda': 5.795840341051741, 'max_delta_step': 6}. Best is trial 7 with value: 0.722326454033771.

Best trial: 7. Best value: 0.722326:  22%|██▏       | 11/50 [03:25<09:21, 14.39s/it]

[I 2025-12-01 17:02:35,960] Trial 12 pruned.

Best trial: 7. Best value: 0.722326:  24%|██▍       | 12/50 [03:29<07:14, 11.44s/it]

[I 2025-12-01 17:02:40,636] Trial 9 finished with value: 0.7049718574108819 and parameters: {'max_depth': 9, 'learning_rate': 0.037425098475082935, 'n_estimators': 802, 'subsample': 0.5352062418608148, 'colsample_bytree': 0.921975538676183, 'min_child_weight': 2, 'gamma': 1.329791534123665, 'reg_alpha': 0.12728198212675523, 'reg_lambda': 0.0038823208415115548, 'max_delta_step': 0}. Best is trial 7 with value: 0.722326454033771.

Best trial: 7. Best value: 0.722326:  26%|██▌       | 13/50 [03:36<06:10, 10.02s/it]

[I 2025-12-01 17:02:47,417] Trial 11 pruned.

Best trial: 7. Best value: 0.722326:  28%|██▊       | 14/50 [03:44<05:37,  9.38s/it]

[I 2025-12-01 17:02:55,297] Trial 13 pruned.

Best trial: 7. Best value: 0.722326:  30%|███       | 15/50 [03:53<05:27,  9.37s/it]

[I 2025-12-01 17:03:04,648] Trial 15 pruned.

Best trial: 7. Best value: 0.722326:  32%|███▏      | 16/50 [03:54<03:44,  6.61s/it]

[I 2025-12-01 17:03:04,843] Trial 17 pruned.

Best trial: 7. Best value: 0.722326:  34%|███▍      | 17/50 [03:58<03:14,  5.88s/it]

[I 2025-12-01 17:03:09,029] Trial 16 pruned.

Best trial: 7. Best value: 0.722326:  36%|███▌      | 18/50 [04:19<05:39, 10.61s/it]

[I 2025-12-01 17:03:30,665] Trial 14 finished with value: 0.7030956848030019 and parameters: {'max_depth': 3, 'learning_rate': 0.013349715601746968, 'n_estimators': 271, 'subsample': 0.8193971890463732, 'colsample_bytree': 0.9291865402215804, 'min_child_weight': 2, 'gamma': 3.156879689147673, 'reg_alpha': 2.9642288001740744e-06, 'reg_lambda': 0.0089542106532139, 'max_delta_step': 5}. Best is trial 7 with value: 0.722326454033771.

Best trial: 7. Best value: 0.722326:  38%|███▊      | 19/50 [04:28<05:05,  9.85s/it]

[I 2025-12-01 17:03:38,745] Trial 21 pruned.

Best trial: 7. Best value: 0.722326:  40%|████      | 20/50 [04:40<05:23, 10.78s/it]

[I 2025-12-01 17:03:51,689] Trial 19 finished with value: 0.7101313320825516 and parameters: {'max_depth': 8, 'learning_rate': 0.08413332845599868, 'n_estimators': 746, 'subsample': 0.7967798574092616, 'colsample_bytree': 0.8647322112381624, 'min_child_weight': 4, 'gamma': 2.8080193329017002, 'reg_alpha': 1.2358053978118316e-08, 'reg_lambda': 6.137921043665154e-05, 'max_delta_step': 5}. Best is trial 7 with value: 0.722326454033771.

Best trial: 7. Best value: 0.722326:  42%|████▏     | 21/50 [04:44<04:08,  8.56s/it]

[I 2025-12-01 17:03:55,089] Trial 20 finished with value: 0.6665103189493433 and parameters: {'max_depth': 8, 'learning_rate': 0.08408824580588177, 'n_estimators': 722, 'subsample': 0.8184010866041447, 'colsample_bytree': 0.8755673789251529, 'min_child_weight': 4, 'gamma': 2.98867746736323, 'reg_alpha': 1.6042298495662407e-08, 'reg_lambda': 6.743516481667385e-05, 'max_delta_step': 0}. Best is trial 7 with value: 0.722326454033771.

Best trial: 7. Best value: 0.722326:  44%|████▍     | 22/50 [04:47<03:11,  6.85s/it]

[I 2025-12-01 17:03:57,939] Trial 23 pruned.

Best trial: 7. Best value: 0.722326:  46%|████▌     | 23/50 [04:50<02:33,  5.68s/it]

[I 2025-12-01 17:04:00,907] Trial 24 pruned.

Best trial: 7. Best value: 0.722326:  48%|████▊     | 24/50 [04:53<02:11,  5.06s/it]

[I 2025-12-01 17:04:04,507] Trial 25 pruned.

Best trial: 7. Best value: 0.722326:  50%|█████     | 25/50 [05:02<02:35,  6.24s/it]

[I 2025-12-01 17:04:13,496] Trial 18 finished with value: 0.6402439024390244 and parameters: {'max_depth': 8, 'learning_rate': 0.020048521171442523, 'n_estimators': 646, 'subsample': 0.9947325448031906, 'colsample_bytree': 0.8798249914559247, 'min_child_weight': 3, 'gamma': 2.9938528803894044, 'reg_alpha': 1.1815942879841406e-05, 'reg_lambda': 0.0008013522694229523, 'max_delta_step': 2}. Best is trial 7 with value: 0.722326454033771.

Best trial: 7. Best value: 0.722326:  52%|█████▏    | 26/50 [05:02<01:46,  4.43s/it]

[I 2025-12-01 17:04:13,717] Trial 22 finished with value: 0.6665103189493433 and parameters: {'max_depth': 6, 'learning_rate': 0.031220855642298935, 'n_estimators': 529, 'subsample': 0.5974592618854917, 'colsample_bytree': 0.846403226456689, 'min_child_weight': 6, 'gamma': 1.940240755898436, 'reg_alpha': 0.045787590150041864, 'reg_lambda': 0.23352537751311775, 'max_delta_step': 6}. Best is trial 7 with value: 0.722326454033771.

Best trial: 7. Best value: 0.722326:  54%|█████▍    | 27/50 [05:03<01:14,  3.22s/it]

[I 2025-12-01 17:04:14,125] Trial 27 pruned.

Best trial: 7. Best value: 0.722326:  58%|█████▊    | 29/50 [05:13<01:18,  3.72s/it]

[I 2025-12-01 17:04:24,044] Trial 30 pruned.
[I 2025-12-01 17:04:24,222] Trial 28 pruned.

Best trial: 7. Best value: 0.722326:  60%|██████    | 30/50 [05:14<00:56,  2.82s/it]

[I 2025-12-01 17:04:24,949] Trial 29 pruned.

Best trial: 7. Best value: 0.722326:  62%|██████▏   | 31/50 [05:25<01:43,  5.47s/it]

[I 2025-12-01 17:04:36,602] Trial 31 pruned.

Best trial: 7. Best value: 0.722326:  64%|██████▍   | 32/50 [05:26<01:11,  3.95s/it]

[I 2025-12-01 17:04:37,015] Trial 32 pruned.

Best trial: 26. Best value: 0.729362:  66%|██████▌   | 33/50 [05:53<03:07, 11.05s/it]

[I 2025-12-01 17:05:04,626] Trial 26 finished with value: 0.7293621013133209 and parameters: {'max_depth': 7, 'learning_rate': 0.02980011500805046, 'n_estimators': 898, 'subsample': 0.6550930041292855, 'colsample_bytree': 0.9281051414843267, 'min_child_weight': 4, 'gamma': 3.673358065413838, 'reg_alpha': 6.483276081751931e-08, 'reg_lambda': 0.0007974015836992717, 'max_delta_step': 10}. Best is trial 26 with value: 0.7293621013133209.

Best trial: 26. Best value: 0.729362:  68%|██████▊   | 34/50 [06:03<02:47, 10.48s/it]

[I 2025-12-01 17:05:13,763] Trial 36 pruned.

Best trial: 26. Best value: 0.729362:  70%|███████   | 35/50 [06:12<02:30, 10.06s/it]

[I 2025-12-01 17:05:22,835] Trial 37 pruned.

Best trial: 26. Best value: 0.729362:  72%|███████▏  | 36/50 [06:16<01:57,  8.42s/it]

[I 2025-12-01 17:05:27,433] Trial 35 finished with value: 0.7152908067542214 and parameters: {'max_depth': 4, 'learning_rate': 0.015552835787990027, 'n_estimators': 202, 'subsample': 0.8113553839794356, 'colsample_bytree': 0.9524776148905153, 'min_child_weight': 2, 'gamma': 2.45634461287564, 'reg_alpha': 3.2620674155500112e-06, 'reg_lambda': 0.004847881814485733, 'max_delta_step': 5}. Best is trial 26 with value: 0.7293621013133209.

Best trial: 26. Best value: 0.729362:  74%|███████▍  | 37/50 [06:20<01:32,  7.13s/it]

[I 2025-12-01 17:05:31,561] Trial 34 finished with value: 0.7152908067542214 and parameters: {'max_depth': 4, 'learning_rate': 0.014472910837577728, 'n_estimators': 230, 'subsample': 0.7960223858384974, 'colsample_bytree': 0.9635160164575303, 'min_child_weight': 2, 'gamma': 2.3659578085065966, 'reg_alpha': 2.0872551770351072e-06, 'reg_lambda': 0.0040143335582793985, 'max_delta_step': 5}. Best is trial 26 with value: 0.7293621013133209.

Best trial: 26. Best value: 0.729362:  76%|███████▌  | 38/50 [06:22<01:07,  5.58s/it]

[I 2025-12-01 17:05:33,519] Trial 38 pruned.

Best trial: 26. Best value: 0.729362:  78%|███████▊  | 39/50 [06:24<00:48,  4.40s/it]

[I 2025-12-01 17:05:35,172] Trial 33 finished with value: 0.7030956848030019 and parameters: {'max_depth': 10, 'learning_rate': 0.10384228110160121, 'n_estimators': 1163, 'subsample': 0.7647902787207288, 'colsample_bytree': 0.6937752018979005, 'min_child_weight': 2, 'gamma': 0.7506992147928472, 'reg_alpha': 0.0006182483074339938, 'reg_lambda': 0.00018804658386471063, 'max_delta_step': 5}. Best is trial 26 with value: 0.7293621013133209.

Best trial: 26. Best value: 0.729362:  80%|████████  | 40/50 [06:25<00:33,  3.33s/it]

[I 2025-12-01 17:05:36,021] Trial 40 pruned.

Best trial: 26. Best value: 0.729362:  82%|████████▏ | 41/50 [06:28<00:28,  3.15s/it]

[I 2025-12-01 17:05:38,754] Trial 39 pruned.

Best trial: 26. Best value: 0.729362:  84%|████████▍ | 42/50 [06:30<00:24,  3.03s/it]

[I 2025-12-01 17:05:41,487] Trial 42 pruned.

Best trial: 26. Best value: 0.729362:  86%|████████▌ | 43/50 [06:39<00:33,  4.85s/it]

[I 2025-12-01 17:05:50,600] Trial 43 pruned.

Best trial: 26. Best value: 0.729362:  88%|████████▊ | 44/50 [06:42<00:25,  4.19s/it]

[I 2025-12-01 17:05:53,248] Trial 45 pruned.

Best trial: 26. Best value: 0.729362:  90%|█████████ | 45/50 [07:14<01:02, 12.54s/it]

[I 2025-12-01 17:06:25,282] Trial 47 finished with value: 0.6787054409005628 and parameters: {'max_depth': 5, 'learning_rate': 0.17180547576625316, 'n_estimators': 396, 'subsample': 0.9087186471797355, 'colsample_bytree': 0.9971701965107695, 'min_child_weight': 3, 'gamma': 2.0122140892293015, 'reg_alpha': 3.3813484865547356e-08, 'reg_lambda': 1.805742570207271, 'max_delta_step': 4}. Best is trial 26 with value: 0.7293621013133209.

Best trial: 26. Best value: 0.729362:  92%|█████████▏| 46/50 [07:27<00:50, 12.67s/it]

[I 2025-12-01 17:06:38,254] Trial 46 finished with value: 0.7101313320825516 and parameters: {'max_depth': 5, 'learning_rate': 0.01450499929224583, 'n_estimators': 383, 'subsample': 0.801390863320804, 'colsample_bytree': 0.9933874017465726, 'min_child_weight': 4, 'gamma': 2.824176396789672, 'reg_alpha': 7.725781480729083e-08, 'reg_lambda': 1.1038518009670888, 'max_delta_step': 6}. Best is trial 26 with value: 0.7293621013133209.

Best trial: 26. Best value: 0.729362:  94%|█████████▍| 47/50 [07:34<00:33, 11.04s/it]

[I 2025-12-01 17:06:45,473] Trial 41 finished with value: 0.6646341463414633 and parameters: {'max_depth': 4, 'learning_rate': 0.01941140924374286, 'n_estimators': 420, 'subsample': 0.7574160219745959, 'colsample_bytree': 0.9546394756560029, 'min_child_weight': 1, 'gamma': 2.3568802899098844, 'reg_alpha': 4.529695271098688e-06, 'reg_lambda': 0.05258129474577299, 'max_delta_step': 8}. Best is trial 26 with value: 0.7293621013133209.

Best trial: 44. Best value: 0.741557:  96%|█████████▌| 48/50 [07:43<00:20, 10.22s/it]

[I 2025-12-01 17:06:53,773] Trial 44 finished with value: 0.7415572232645403 and parameters: {'max_depth': 4, 'learning_rate': 0.19345863603256683, 'n_estimators': 1461, 'subsample': 0.8996906245525109, 'colsample_bytree': 0.900957918949481, 'min_child_weight': 4, 'gamma': 2.3038918829424917, 'reg_alpha': 5.224183261974318e-08, 'reg_lambda': 0.07711014659333403, 'max_delta_step': 6}. Best is trial 44 with value: 0.7415572232645403.

Best trial: 44. Best value: 0.741557:  98%|█████████▊| 49/50 [07:47<00:08,  8.60s/it]

[I 2025-12-01 17:06:58,621] Trial 48 finished with value: 0.7030956848030019 and parameters: {'max_depth': 3, 'learning_rate': 0.014150481432519468, 'n_estimators': 331, 'subsample': 0.7204496874781442, 'colsample_bytree': 0.7569923460824, 'min_child_weight': 4, 'gamma': 4.274334713480342, 'reg_alpha': 3.873049751528006e-07, 'reg_lambda': 3.8484137834266054e-05, 'max_delta_step': 7}. Best is trial 44 with value: 0.7415572232645403.

Best trial: 44. Best value: 0.741557: 100%|██████████| 50/50 [08:02<00:00,  9.66s/it]

[I 2025-12-01 17:07:13,702] Trial 49 finished with value: 0.6716697936210132 and parameters: {'max_depth': 3, 'learning_rate': 0.02254825788403581, 'n_estimators': 314, 'subsample': 0.72661873031345, 'colsample_bytree': 0.7606927287164958, 'min_child_weight': 1, 'gamma': 4.1776904397463515, 'reg_alpha': 0.0001045257081923749, 'reg_lambda': 2.7338795372932436e-06, 'max_delta_step': 5}. Best is trial 44 with value: 0.7415572232645403.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.660870                0.716667      0.700000
1    17_1         loo       0.741557                0.707143      0.600000
2    19_1         loo       0.716667                0.683333      0.833333
3    15_1         loo       0.521463                0.635714      0.585714

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.422890          0.833333               0.6        50          63
1  0.408491          0.714286               0.7        50          67
2  0.357830          0.666667               0.7        50          64
3  0.271429          0.571429               0.7        50          66

   test_size
0         16
1         17
2         16
3         17
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.660870                0.716667      0.700000
1    17_1         loo       0.741557                0.707143      0.600000
2    19_1         loo       0.716667                0.683333      0.833333
3    15_1         loo       0.521463                0.635714      0.585714

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.422890          0.833333               0.6        50          63
1  0.408491          0.714286               0.7        50          67
2  0.357830          0.666667               0.7        50          64
3  0.271429          0.571429               0.7        50          66

   test_size
0         16
1         17
2         16
3         17

In [1563]:

datasets = task_hf_compensated_freq_emb_lbl_lbd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
   output_dir="xgb_lbd_hc_{CV_STRATEGY}_tasks/xgb_results_handcrafted_frerq_emb_compensated_extended_{CV_STRATEGY}_tasks",
    split_param= "diagnosis_y",
)
print(summary)
## MCI-AD vs HC -> OPTUNA + XGB

[I 2025-12-01 17:07:23,066] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 63, Test size: 16
Using Leave-One-Out CV with 63 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.0434783:   2%|▏         | 1/50 [00:33<27:12, 33.32s/it]

[I 2025-12-01 17:07:56,379] Trial 3 finished with value: 0.043478260869565216 and parameters: {'max_depth': 6, 'learning_rate': 0.05036528298943637, 'n_estimators': 643, 'subsample': 0.5713371458258536, 'colsample_bytree': 0.6869390024717151, 'min_child_weight': 9, 'gamma': 1.091196925094418, 'reg_alpha': 0.0031732190710326417, 'reg_lambda': 2.3841094926685905e-06, 'max_delta_step': 10}. Best is trial 3 with value: 0.043478260869565216.

Best trial: 2. Best value: 0.62663:   4%|▍         | 2/50 [00:46<17:16, 21.58s/it]

[I 2025-12-01 17:08:09,746] Trial 2 finished with value: 0.6266304347826087 and parameters: {'max_depth': 9, 'learning_rate': 0.03841443314765995, 'n_estimators': 482, 'subsample': 0.936503160617816, 'colsample_bytree': 0.7995677572329383, 'min_child_weight': 2, 'gamma': 2.69716221638284, 'reg_alpha': 0.1435624472735576, 'reg_lambda': 0.093463500589397, 'max_delta_step': 3}. Best is trial 2 with value: 0.6266304347826087.

Best trial: 2. Best value: 0.62663:   6%|▌         | 3/50 [00:49<10:01, 12.81s/it]

[I 2025-12-01 17:08:12,112] Trial 0 finished with value: 0.5423913043478261 and parameters: {'max_depth': 10, 'learning_rate': 0.06966286585409927, 'n_estimators': 1002, 'subsample': 0.7762091002747918, 'colsample_bytree': 0.5475980891586298, 'min_child_weight': 6, 'gamma': 2.308207421748314, 'reg_alpha': 2.889685188590621e-07, 'reg_lambda': 0.9888634896652047, 'max_delta_step': 9}. Best is trial 2 with value: 0.6266304347826087.

Best trial: 2. Best value: 0.62663:   8%|▊         | 4/50 [01:05<10:55, 14.24s/it]

[I 2025-12-01 17:08:28,551] Trial 1 finished with value: 0.6173913043478261 and parameters: {'max_depth': 4, 'learning_rate': 0.04796376915111573, 'n_estimators': 876, 'subsample': 0.8372049472376795, 'colsample_bytree': 0.7388855305262843, 'min_child_weight': 2, 'gamma': 4.150896428122018, 'reg_alpha': 6.90862399341623e-07, 'reg_lambda': 6.89267970134035e-06, 'max_delta_step': 8}. Best is trial 2 with value: 0.6266304347826087.

Best trial: 6. Best value: 0.63587:  10%|█         | 5/50 [01:25<12:21, 16.47s/it]

[I 2025-12-01 17:08:48,968] Trial 6 finished with value: 0.6358695652173914 and parameters: {'max_depth': 5, 'learning_rate': 0.1357662583030279, 'n_estimators': 779, 'subsample': 0.5209805238536942, 'colsample_bytree': 0.5499878096126126, 'min_child_weight': 2, 'gamma': 2.35917407418136, 'reg_alpha': 3.0318615840749764e-07, 'reg_lambda': 0.5721284724309023, 'max_delta_step': 4}. Best is trial 6 with value: 0.6358695652173914.

Best trial: 6. Best value: 0.63587:  12%|█▏        | 6/50 [01:32<09:36, 13.10s/it]

[I 2025-12-01 17:08:55,533] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.050756548509472886, 'n_estimators': 1357, 'subsample': 0.965471001808561, 'colsample_bytree': 0.7335084005074474, 'min_child_weight': 10, 'gamma': 2.7162051067717496, 'reg_alpha': 0.012559251232473546, 'reg_lambda': 0.004959927984037476, 'max_delta_step': 3}. Best is trial 6 with value: 0.6358695652173914.

Best trial: 6. Best value: 0.63587:  14%|█▍        | 7/50 [01:43<09:00, 12.58s/it]

[I 2025-12-01 17:09:07,044] Trial 5 finished with value: 0.5983695652173913 and parameters: {'max_depth': 3, 'learning_rate': 0.04623477932476319, 'n_estimators': 1181, 'subsample': 0.8812050103372018, 'colsample_bytree': 0.9972797892294031, 'min_child_weight': 7, 'gamma': 4.506253006127753, 'reg_alpha': 2.0258996931978115, 'reg_lambda': 0.5535261403888131, 'max_delta_step': 2}. Best is trial 6 with value: 0.6358695652173914.

Best trial: 6. Best value: 0.63587:  16%|█▌        | 8/50 [02:02<10:05, 14.41s/it]

[I 2025-12-01 17:09:25,356] Trial 8 finished with value: 0.6173913043478261 and parameters: {'max_depth': 8, 'learning_rate': 0.04545161394748512, 'n_estimators': 443, 'subsample': 0.6305312244910363, 'colsample_bytree': 0.8971517528128614, 'min_child_weight': 2, 'gamma': 2.8661975546066105, 'reg_alpha': 0.2728362843118517, 'reg_lambda': 4.4439278747673e-05, 'max_delta_step': 1}. Best is trial 6 with value: 0.6358695652173914.

Best trial: 6. Best value: 0.63587:  18%|█▊        | 9/50 [02:05<07:24, 10.85s/it]

[I 2025-12-01 17:09:28,375] Trial 10 finished with value: 0.5983695652173913 and parameters: {'max_depth': 3, 'learning_rate': 0.035575871476695727, 'n_estimators': 455, 'subsample': 0.5868228669464042, 'colsample_bytree': 0.868126936794892, 'min_child_weight': 7, 'gamma': 3.9478939178000405, 'reg_alpha': 0.21135438050969116, 'reg_lambda': 0.038276694415156506, 'max_delta_step': 2}. Best is trial 6 with value: 0.6358695652173914.

Best trial: 6. Best value: 0.63587:  20%|██        | 10/50 [02:05<05:05,  7.64s/it]

[I 2025-12-01 17:09:28,826] Trial 7 finished with value: 0.5891304347826087 and parameters: {'max_depth': 3, 'learning_rate': 0.08110672006706245, 'n_estimators': 1276, 'subsample': 0.8335616911486567, 'colsample_bytree': 0.9406198897591215, 'min_child_weight': 5, 'gamma': 0.5187611291265382, 'reg_alpha': 0.01528195862941597, 'reg_lambda': 3.524800217130936e-08, 'max_delta_step': 8}. Best is trial 6 with value: 0.6358695652173914.

Best trial: 6. Best value: 0.63587:  22%|██▏       | 11/50 [02:15<05:27,  8.40s/it]

[I 2025-12-01 17:09:38,943] Trial 11 pruned.

Best trial: 6. Best value: 0.63587:  24%|██▍       | 12/50 [02:26<05:39,  8.94s/it]

[I 2025-12-01 17:09:49,113] Trial 12 pruned.

Best trial: 6. Best value: 0.63587:  26%|██▌       | 13/50 [02:32<04:59,  8.10s/it]

[I 2025-12-01 17:09:55,296] Trial 15 pruned.

Best trial: 6. Best value: 0.63587:  28%|██▊       | 14/50 [02:42<05:14,  8.74s/it]

[I 2025-12-01 17:10:05,501] Trial 13 finished with value: 0.6326086956521739 and parameters: {'max_depth': 6, 'learning_rate': 0.2434059743178544, 'n_estimators': 702, 'subsample': 0.5071605000556471, 'colsample_bytree': 0.5079744125849235, 'min_child_weight': 4, 'gamma': 1.460670001984942, 'reg_alpha': 1.833067929311651e-05, 'reg_lambda': 5.669293283011006, 'max_delta_step': 6}. Best is trial 6 with value: 0.6358695652173914.

Best trial: 6. Best value: 0.63587:  30%|███       | 15/50 [02:46<04:11,  7.20s/it]

[I 2025-12-01 17:10:09,126] Trial 14 finished with value: 0.6141304347826086 and parameters: {'max_depth': 5, 'learning_rate': 0.2544836184351174, 'n_estimators': 347, 'subsample': 0.998855223444921, 'colsample_bytree': 0.5023744664070586, 'min_child_weight': 1, 'gamma': 1.6113707529363939, 'reg_alpha': 1.0953571096459371e-08, 'reg_lambda': 6.474781164595168, 'max_delta_step': 5}. Best is trial 6 with value: 0.6358695652173914.

Best trial: 6. Best value: 0.63587:  32%|███▏      | 16/50 [02:52<03:57,  6.98s/it]

[I 2025-12-01 17:10:15,597] Trial 16 pruned.

Best trial: 9. Best value: 0.63913:  34%|███▍      | 17/50 [03:00<03:56,  7.17s/it]

[I 2025-12-01 17:10:23,230] Trial 9 finished with value: 0.6391304347826088 and parameters: {'max_depth': 10, 'learning_rate': 0.025132537352492913, 'n_estimators': 1119, 'subsample': 0.552228897039837, 'colsample_bytree': 0.6585543948222226, 'min_child_weight': 1, 'gamma': 0.3999769603538861, 'reg_alpha': 1.2336286075551586e-05, 'reg_lambda': 0.02036330270294512, 'max_delta_step': 4}. Best is trial 9 with value: 0.6391304347826088.

Best trial: 9. Best value: 0.63913:  36%|███▌      | 18/50 [03:02<03:00,  5.65s/it]

[I 2025-12-01 17:10:25,293] Trial 17 pruned.

Best trial: 19. Best value: 0.645109:  38%|███▊      | 19/50 [03:37<07:30, 14.53s/it]

[I 2025-12-01 17:11:00,558] Trial 19 finished with value: 0.6451086956521739 and parameters: {'max_depth': 7, 'learning_rate': 0.14493206428016572, 'n_estimators': 759, 'subsample': 0.5183537325619983, 'colsample_bytree': 0.624615338868267, 'min_child_weight': 4, 'gamma': 0.010950121588253703, 'reg_alpha': 9.318640545963343e-06, 'reg_lambda': 0.2654018410691415, 'max_delta_step': 7}. Best is trial 19 with value: 0.6451086956521739.

Best trial: 18. Best value: 0.679348:  40%|████      | 20/50 [03:47<06:34, 13.14s/it]

[I 2025-12-01 17:11:10,462] Trial 18 finished with value: 0.6793478260869565 and parameters: {'max_depth': 6, 'learning_rate': 0.015731724315896325, 'n_estimators': 837, 'subsample': 0.5018196607800038, 'colsample_bytree': 0.619315101560613, 'min_child_weight': 4, 'gamma': 0.3415218786306875, 'reg_alpha': 7.986445025054545e-06, 'reg_lambda': 0.0018737352175590097, 'max_delta_step': 6}. Best is trial 18 with value: 0.6793478260869565.

Best trial: 18. Best value: 0.679348:  42%|████▏     | 21/50 [03:50<04:55, 10.20s/it]

[I 2025-12-01 17:11:13,788] Trial 21 pruned.

Best trial: 18. Best value: 0.679348:  44%|████▍     | 22/50 [04:07<05:41, 12.19s/it]

[I 2025-12-01 17:11:30,613] Trial 22 pruned.

Best trial: 18. Best value: 0.679348:  46%|████▌     | 23/50 [04:10<04:15,  9.46s/it]

[I 2025-12-01 17:11:33,703] Trial 24 pruned.

Best trial: 20. Best value: 0.682609:  48%|████▊     | 24/50 [04:39<06:35, 15.22s/it]

[I 2025-12-01 17:12:02,368] Trial 20 finished with value: 0.682608695652174 and parameters: {'max_depth': 7, 'learning_rate': 0.019299036733292182, 'n_estimators': 1481, 'subsample': 0.5616360558205012, 'colsample_bytree': 0.5969639312090831, 'min_child_weight': 3, 'gamma': 0.16922275644539259, 'reg_alpha': 4.5245514029009825e-06, 'reg_lambda': 0.0030397969949108117, 'max_delta_step': 4}. Best is trial 20 with value: 0.682608695652174.

Best trial: 20. Best value: 0.682609:  50%|█████     | 25/50 [04:42<04:52, 11.70s/it]

[I 2025-12-01 17:12:05,863] Trial 25 pruned.

Best trial: 20. Best value: 0.682609:  52%|█████▏    | 26/50 [04:53<04:37, 11.55s/it]

[I 2025-12-01 17:12:17,045] Trial 23 finished with value: 0.6668478260869566 and parameters: {'max_depth': 7, 'learning_rate': 0.012640496607805411, 'n_estimators': 933, 'subsample': 0.633787647167337, 'colsample_bytree': 0.6014788653269034, 'min_child_weight': 5, 'gamma': 0.9006961424661388, 'reg_alpha': 0.00027018954399591266, 'reg_lambda': 0.000878621458150501, 'max_delta_step': 7}. Best is trial 20 with value: 0.682608695652174.

Best trial: 20. Best value: 0.682609:  54%|█████▍    | 27/50 [05:10<04:57, 12.96s/it]

[I 2025-12-01 17:12:33,295] Trial 29 pruned.

Best trial: 20. Best value: 0.682609:  56%|█████▌    | 28/50 [05:40<06:38, 18.13s/it]

[I 2025-12-01 17:13:03,485] Trial 30 pruned.

Best trial: 20. Best value: 0.682609:  58%|█████▊    | 29/50 [05:43<04:43, 13.52s/it]

[I 2025-12-01 17:13:06,260] Trial 26 finished with value: 0.6483695652173913 and parameters: {'max_depth': 7, 'learning_rate': 0.012636162790623786, 'n_estimators': 1135, 'subsample': 0.5602174460725903, 'colsample_bytree': 0.6873140870984429, 'min_child_weight': 3, 'gamma': 0.7639047107954992, 'reg_alpha': 5.176780387492125e-05, 'reg_lambda': 0.10022646022118294, 'max_delta_step': 6}. Best is trial 20 with value: 0.682608695652174.

Best trial: 20. Best value: 0.682609:  60%|██████    | 30/50 [05:51<03:58, 11.93s/it]

[I 2025-12-01 17:13:14,490] Trial 32 pruned.

Best trial: 20. Best value: 0.682609:  62%|██████▏   | 31/50 [05:51<02:41,  8.51s/it]

[I 2025-12-01 17:13:15,007] Trial 28 finished with value: 0.6233695652173913 and parameters: {'max_depth': 7, 'learning_rate': 0.01655357510648895, 'n_estimators': 891, 'subsample': 0.6265680819392623, 'colsample_bytree': 0.5794892604955416, 'min_child_weight': 3, 'gamma': 1.1642670031658886, 'reg_alpha': 1.949037866865857e-06, 'reg_lambda': 0.0003018089384191576, 'max_delta_step': 6}. Best is trial 20 with value: 0.682608695652174.

Best trial: 20. Best value: 0.682609:  64%|██████▍   | 32/50 [06:01<02:38,  8.82s/it]

[I 2025-12-01 17:13:24,549] Trial 27 finished with value: 0.6576086956521738 and parameters: {'max_depth': 7, 'learning_rate': 0.011321696274499275, 'n_estimators': 887, 'subsample': 0.6225434469185349, 'colsample_bytree': 0.5830152360207032, 'min_child_weight': 3, 'gamma': 0.7326119454990845, 'reg_alpha': 6.891945286078482e-05, 'reg_lambda': 0.0002498561245623855, 'max_delta_step': 6}. Best is trial 20 with value: 0.682608695652174.

Best trial: 20. Best value: 0.682609:  66%|██████▌   | 33/50 [06:13<02:45,  9.73s/it]

[I 2025-12-01 17:13:36,404] Trial 33 pruned.

Best trial: 20. Best value: 0.682609:  68%|██████▊   | 34/50 [06:14<01:54,  7.15s/it]

[I 2025-12-01 17:13:37,540] Trial 31 pruned.

Best trial: 20. Best value: 0.682609:  70%|███████   | 35/50 [06:22<01:51,  7.40s/it]

[I 2025-12-01 17:13:45,502] Trial 34 pruned.

Best trial: 20. Best value: 0.682609:  72%|███████▏  | 36/50 [06:31<01:52,  8.01s/it]

[I 2025-12-01 17:13:54,943] Trial 35 pruned.

Best trial: 20. Best value: 0.682609:  74%|███████▍  | 37/50 [06:33<01:17,  5.97s/it]

[I 2025-12-01 17:13:56,097] Trial 36 pruned.

Best trial: 20. Best value: 0.682609:  76%|███████▌  | 38/50 [07:16<03:26, 17.17s/it]

[I 2025-12-01 17:14:39,475] Trial 38 finished with value: 0.6701086956521739 and parameters: {'max_depth': 5, 'learning_rate': 0.019514909906989994, 'n_estimators': 712, 'subsample': 0.5998614114640011, 'colsample_bytree': 0.5356397502296726, 'min_child_weight': 5, 'gamma': 0.8922712906938917, 'reg_alpha': 0.0008813959857938731, 'reg_lambda': 0.0030398231136579963, 'max_delta_step': 3}. Best is trial 20 with value: 0.682608695652174.

Best trial: 20. Best value: 0.682609:  78%|███████▊  | 39/50 [07:24<02:37, 14.30s/it]

[I 2025-12-01 17:14:47,083] Trial 41 pruned.

Best trial: 20. Best value: 0.682609:  80%|████████  | 40/50 [07:42<02:34, 15.46s/it]

[I 2025-12-01 17:15:05,234] Trial 37 finished with value: 0.6701086956521739 and parameters: {'max_depth': 5, 'learning_rate': 0.012036364298064164, 'n_estimators': 1069, 'subsample': 0.6002080129605218, 'colsample_bytree': 0.5338765660405365, 'min_child_weight': 4, 'gamma': 0.4226054545039738, 'reg_alpha': 0.00012318759558720455, 'reg_lambda': 0.003123338268805185, 'max_delta_step': 9}. Best is trial 20 with value: 0.682608695652174.

Best trial: 20. Best value: 0.682609:  82%|████████▏ | 41/50 [07:42<01:38, 10.97s/it]

[I 2025-12-01 17:15:05,742] Trial 42 pruned.

Best trial: 20. Best value: 0.682609:  84%|████████▍ | 42/50 [07:56<01:34, 11.82s/it]

[I 2025-12-01 17:15:19,533] Trial 39 finished with value: 0.6266304347826087 and parameters: {'max_depth': 8, 'learning_rate': 0.012224789859401695, 'n_estimators': 667, 'subsample': 0.6020247471190132, 'colsample_bytree': 0.5402868041561699, 'min_child_weight': 2, 'gamma': 0.274431588692967, 'reg_alpha': 0.005713150547492267, 'reg_lambda': 0.0034302753290366868, 'max_delta_step': 3}. Best is trial 20 with value: 0.682608695652174.

Best trial: 20. Best value: 0.682609:  86%|████████▌ | 43/50 [08:04<01:15, 10.76s/it]

[I 2025-12-01 17:15:27,831] Trial 40 finished with value: 0.6173913043478261 and parameters: {'max_depth': 8, 'learning_rate': 0.06498191778187928, 'n_estimators': 1405, 'subsample': 0.6874324006947949, 'colsample_bytree': 0.7120988243931282, 'min_child_weight': 2, 'gamma': 1.04059175579018, 'reg_alpha': 0.00763002038813074, 'reg_lambda': 7.962081455356968e-05, 'max_delta_step': 3}. Best is trial 20 with value: 0.682608695652174.

Best trial: 20. Best value: 0.682609:  88%|████████▊ | 44/50 [08:07<00:49,  8.33s/it]

[I 2025-12-01 17:15:30,491] Trial 43 pruned.

Best trial: 20. Best value: 0.682609:  90%|█████████ | 45/50 [08:13<00:38,  7.63s/it]

[I 2025-12-01 17:15:36,467] Trial 45 pruned.

Best trial: 20. Best value: 0.682609:  92%|█████████▏| 46/50 [08:14<00:22,  5.74s/it]

[I 2025-12-01 17:15:37,820] Trial 46 pruned.

Best trial: 20. Best value: 0.682609:  94%|█████████▍| 47/50 [08:21<00:18,  6.13s/it]

[I 2025-12-01 17:15:44,857] Trial 48 pruned.

Best trial: 20. Best value: 0.682609:  96%|█████████▌| 48/50 [08:24<00:09,  4.99s/it]

[I 2025-12-01 17:15:47,171] Trial 47 pruned.

Best trial: 20. Best value: 0.682609:  98%|█████████▊| 49/50 [08:25<00:03,  3.81s/it]

[I 2025-12-01 17:15:48,234] Trial 49 pruned.

Best trial: 20. Best value: 0.682609: 100%|██████████| 50/50 [08:35<00:00, 10.31s/it]

[I 2025-12-01 17:15:58,340] Trial 44 finished with value: 0.6701086956521739 and parameters: {'max_depth': 5, 'learning_rate': 0.01476258854003032, 'n_estimators': 819, 'subsample': 0.5980806570700763, 'colsample_bytree': 0.5284721391886458, 'min_child_weight': 5, 'gamma': 0.2575372631824501, 'reg_alpha': 0.000586191428944113, 'reg_lambda': 0.0025289006267118883, 'max_delta_step': 3}. Best is trial 20 with value: 0.682608695652174.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 17:16:06,535] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 66, Test size: 17
Using Leave-One-Out CV with 66 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0:   2%|▏         | 1/50 [00:53<43:53, 53.75s/it]

[I 2025-12-01 17:17:00,277] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.08686391995692397, 'n_estimators': 990, 'subsample': 0.5264148859097992, 'colsample_bytree': 0.9131558586349742, 'min_child_weight': 10, 'gamma': 1.6819671597454744, 'reg_alpha': 0.20056628889502878, 'reg_lambda': 0.3487826998307241, 'max_delta_step': 4}. Best is trial 1 with value: 0.0.

Best trial: 2. Best value: 0.492683:   4%|▍         | 2/50 [00:59<20:14, 25.31s/it]

[I 2025-12-01 17:17:05,679] Trial 2 finished with value: 0.4926829268292683 and parameters: {'max_depth': 4, 'learning_rate': 0.018118861871569022, 'n_estimators': 654, 'subsample': 0.9481853717875206, 'colsample_bytree': 0.9513468831591868, 'min_child_weight': 6, 'gamma': 3.48702471215797, 'reg_alpha': 0.00010994140286064772, 'reg_lambda': 4.678008087279396e-08, 'max_delta_step': 6}. Best is trial 2 with value: 0.4926829268292683.

Best trial: 2. Best value: 0.492683:   6%|▌         | 3/50 [01:12<15:43, 20.07s/it]

[I 2025-12-01 17:17:19,498] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.013536439435045174, 'n_estimators': 1316, 'subsample': 0.5811344235362996, 'colsample_bytree': 0.9559390864191548, 'min_child_weight': 10, 'gamma': 0.7110513492932097, 'reg_alpha': 7.933924312019464e-07, 'reg_lambda': 1.3581837010101063, 'max_delta_step': 2}. Best is trial 2 with value: 0.4926829268292683.

Best trial: 2. Best value: 0.492683:   8%|▊         | 4/50 [01:44<18:57, 24.72s/it]

[I 2025-12-01 17:17:51,373] Trial 6 finished with value: 0.24292682926829268 and parameters: {'max_depth': 5, 'learning_rate': 0.010721881425597844, 'n_estimators': 562, 'subsample': 0.6766377370699195, 'colsample_bytree': 0.7386768749370989, 'min_child_weight': 8, 'gamma': 0.8577484585338918, 'reg_alpha': 3.021657456871973e-05, 'reg_lambda': 1.245688423961878e-08, 'max_delta_step': 3}. Best is trial 2 with value: 0.4926829268292683.

Best trial: 0. Best value: 0.621463:  10%|█         | 5/50 [01:57<15:22, 20.49s/it]

[I 2025-12-01 17:18:04,362] Trial 0 finished with value: 0.6214634146341464 and parameters: {'max_depth': 5, 'learning_rate': 0.19542233924833433, 'n_estimators': 1372, 'subsample': 0.9590845971780257, 'colsample_bytree': 0.8824018068238988, 'min_child_weight': 1, 'gamma': 1.252647258284259, 'reg_alpha': 4.4425664219970715e-05, 'reg_lambda': 3.714510455807318e-07, 'max_delta_step': 10}. Best is trial 0 with value: 0.6214634146341464.

Best trial: 0. Best value: 0.621463:  12%|█▏        | 6/50 [02:18<15:09, 20.66s/it]

[I 2025-12-01 17:18:25,350] Trial 7 finished with value: 0.6092682926829269 and parameters: {'max_depth': 5, 'learning_rate': 0.28266070703145396, 'n_estimators': 455, 'subsample': 0.8792978363995575, 'colsample_bytree': 0.6493413332373197, 'min_child_weight': 4, 'gamma': 0.38945250332254155, 'reg_alpha': 2.3922885441764847e-06, 'reg_lambda': 5.353157889643443e-07, 'max_delta_step': 8}. Best is trial 0 with value: 0.6214634146341464.

Best trial: 0. Best value: 0.621463:  14%|█▍        | 7/50 [02:28<12:19, 17.20s/it]

[I 2025-12-01 17:18:35,416] Trial 5 finished with value: 0.4448780487804878 and parameters: {'max_depth': 7, 'learning_rate': 0.015503471433334814, 'n_estimators': 1129, 'subsample': 0.798260763854184, 'colsample_bytree': 0.6823552700026823, 'min_child_weight': 6, 'gamma': 0.8677596912006608, 'reg_alpha': 2.8433376943506716e-07, 'reg_lambda': 4.7591835662256335e-06, 'max_delta_step': 0}. Best is trial 0 with value: 0.6214634146341464.

Best trial: 0. Best value: 0.621463:  16%|█▌        | 8/50 [02:49<12:43, 18.18s/it]

[I 2025-12-01 17:18:55,698] Trial 4 finished with value: 0.5458536585365854 and parameters: {'max_depth': 10, 'learning_rate': 0.038070641204298455, 'n_estimators': 1403, 'subsample': 0.7385989596302793, 'colsample_bytree': 0.5838918560316563, 'min_child_weight': 1, 'gamma': 0.8548005633241573, 'reg_alpha': 9.3783565337277e-05, 'reg_lambda': 0.0007388131845082257, 'max_delta_step': 8}. Best is trial 0 with value: 0.6214634146341464.

Best trial: 0. Best value: 0.621463:  18%|█▊        | 9/50 [03:02<11:18, 16.55s/it]

[I 2025-12-01 17:19:08,667] Trial 9 finished with value: 0.4892682926829268 and parameters: {'max_depth': 6, 'learning_rate': 0.05221768260783322, 'n_estimators': 548, 'subsample': 0.5344699444824386, 'colsample_bytree': 0.7921555812937094, 'min_child_weight': 3, 'gamma': 4.499182364731683, 'reg_alpha': 1.178866596878693e-06, 'reg_lambda': 8.79665511872544e-08, 'max_delta_step': 9}. Best is trial 0 with value: 0.6214634146341464.

Best trial: 0. Best value: 0.621463:  20%|██        | 10/50 [03:08<09:00, 13.50s/it]

[I 2025-12-01 17:19:15,342] Trial 10 finished with value: 0.4604878048780488 and parameters: {'max_depth': 3, 'learning_rate': 0.17817397188563436, 'n_estimators': 705, 'subsample': 0.6504637802904775, 'colsample_bytree': 0.5818267389090777, 'min_child_weight': 4, 'gamma': 3.6485460528930993, 'reg_alpha': 3.942541277174689e-05, 'reg_lambda': 1.674632571473942e-07, 'max_delta_step': 4}. Best is trial 0 with value: 0.6214634146341464.

Best trial: 0. Best value: 0.621463:  22%|██▏       | 11/50 [03:11<06:39, 10.23s/it]

[I 2025-12-01 17:19:18,161] Trial 12 pruned.

Best trial: 0. Best value: 0.621463:  24%|██▍       | 12/50 [03:14<05:08,  8.11s/it]

[I 2025-12-01 17:19:21,422] Trial 8 finished with value: 0.5336585365853659 and parameters: {'max_depth': 4, 'learning_rate': 0.07187297887604219, 'n_estimators': 1024, 'subsample': 0.6522554025961771, 'colsample_bytree': 0.6048349848121359, 'min_child_weight': 1, 'gamma': 0.319882659907782, 'reg_alpha': 0.00025652068764183376, 'reg_lambda': 6.418441611959974e-05, 'max_delta_step': 2}. Best is trial 0 with value: 0.6214634146341464.

Best trial: 13. Best value: 0.633659:  26%|██▌       | 13/50 [03:36<07:29, 12.15s/it]

[I 2025-12-01 17:19:42,847] Trial 13 finished with value: 0.6336585365853659 and parameters: {'max_depth': 8, 'learning_rate': 0.12978074392212077, 'n_estimators': 202, 'subsample': 0.9918024440931807, 'colsample_bytree': 0.8284150820526667, 'min_child_weight': 1, 'gamma': 2.1665715541935633, 'reg_alpha': 0.042997487292860265, 'reg_lambda': 8.580410126869518e-05, 'max_delta_step': 10}. Best is trial 13 with value: 0.6336585365853659.

Best trial: 14. Best value: 0.641463:  28%|██▊       | 14/50 [03:36<05:11,  8.66s/it]

[I 2025-12-01 17:19:43,415] Trial 14 finished with value: 0.6414634146341464 and parameters: {'max_depth': 7, 'learning_rate': 0.24456591235065386, 'n_estimators': 228, 'subsample': 0.9818977115523003, 'colsample_bytree': 0.8282059164303607, 'min_child_weight': 1, 'gamma': 0.011053241542361647, 'reg_alpha': 0.010478447753382615, 'reg_lambda': 6.8860027447757725e-06, 'max_delta_step': 7}. Best is trial 14 with value: 0.6414634146341464.

Best trial: 14. Best value: 0.641463:  30%|███       | 15/50 [03:41<04:21,  7.46s/it]

[I 2025-12-01 17:19:48,133] Trial 11 finished with value: 0.5858536585365853 and parameters: {'max_depth': 3, 'learning_rate': 0.231968139666588, 'n_estimators': 697, 'subsample': 0.565480986360144, 'colsample_bytree': 0.544667455956167, 'min_child_weight': 1, 'gamma': 3.545195610946601, 'reg_alpha': 2.136580137302003e-07, 'reg_lambda': 1.278461281523983e-05, 'max_delta_step': 4}. Best is trial 14 with value: 0.6414634146341464.

Best trial: 14. Best value: 0.641463:  32%|███▏      | 16/50 [03:50<04:29,  7.94s/it]

[I 2025-12-01 17:19:57,115] Trial 15 finished with value: 0.6014634146341464 and parameters: {'max_depth': 7, 'learning_rate': 0.288220786510905, 'n_estimators': 338, 'subsample': 0.9837376092153356, 'colsample_bytree': 0.837119921891125, 'min_child_weight': 3, 'gamma': 2.0149049269797668, 'reg_alpha': 0.016390239537967057, 'reg_lambda': 2.5329354618931447e-06, 'max_delta_step': 7}. Best is trial 14 with value: 0.6414634146341464.

Best trial: 14. Best value: 0.641463:  34%|███▍      | 17/50 [04:17<07:27, 13.56s/it]

[I 2025-12-01 17:20:23,820] Trial 17 finished with value: 0.6336585365853659 and parameters: {'max_depth': 8, 'learning_rate': 0.1359566037206372, 'n_estimators': 221, 'subsample': 0.9959346072393508, 'colsample_bytree': 0.8144509165276689, 'min_child_weight': 3, 'gamma': 1.948218675527892, 'reg_alpha': 0.02610631217203186, 'reg_lambda': 0.005834706800242014, 'max_delta_step': 6}. Best is trial 14 with value: 0.6414634146341464.

Best trial: 14. Best value: 0.641463:  36%|███▌      | 18/50 [04:21<05:42, 10.69s/it]

[I 2025-12-01 17:20:27,827] Trial 18 finished with value: 0.5092682926829268 and parameters: {'max_depth': 8, 'learning_rate': 0.11456501654267032, 'n_estimators': 204, 'subsample': 0.9902871771496436, 'colsample_bytree': 0.8278667692381925, 'min_child_weight': 3, 'gamma': 1.9992513212509726, 'reg_alpha': 0.031101183882823374, 'reg_lambda': 0.0050807672024873445, 'max_delta_step': 6}. Best is trial 14 with value: 0.6414634146341464.

Best trial: 14. Best value: 0.641463:  38%|███▊      | 19/50 [04:21<03:57,  7.67s/it]

[I 2025-12-01 17:20:28,381] Trial 16 finished with value: 0.5692682926829269 and parameters: {'max_depth': 8, 'learning_rate': 0.13285195212429687, 'n_estimators': 219, 'subsample': 0.9994552332943556, 'colsample_bytree': 0.8448490668257317, 'min_child_weight': 2, 'gamma': 2.023661987216137, 'reg_alpha': 0.031099813967748458, 'reg_lambda': 0.012565853325370788, 'max_delta_step': 7}. Best is trial 14 with value: 0.6414634146341464.

Best trial: 14. Best value: 0.641463:  40%|████      | 20/50 [04:28<03:38,  7.28s/it]

[I 2025-12-01 17:20:34,823] Trial 20 pruned.

Best trial: 14. Best value: 0.641463:  42%|████▏     | 21/50 [04:30<02:45,  5.71s/it]

[I 2025-12-01 17:20:36,848] Trial 22 pruned.

Best trial: 14. Best value: 0.641463:  44%|████▍     | 22/50 [04:32<02:08,  4.57s/it]

[I 2025-12-01 17:20:38,727] Trial 19 finished with value: 0.5048780487804878 and parameters: {'max_depth': 8, 'learning_rate': 0.12453295758122762, 'n_estimators': 209, 'subsample': 0.8908115665103746, 'colsample_bytree': 0.7852257532048694, 'min_child_weight': 3, 'gamma': 2.135231840523351, 'reg_alpha': 0.007631775371682917, 'reg_lambda': 0.02143957689654994, 'max_delta_step': 6}. Best is trial 14 with value: 0.6414634146341464.
[I 2025-12-01 17:20:38,807] Trial 21 pruned.

Best trial: 14. Best value: 0.641463:  48%|████▊     | 24/50 [05:04<04:17,  9.89s/it]

[I 2025-12-01 17:21:10,977] Trial 24 finished with value: 0.6136585365853658 and parameters: {'max_depth': 7, 'learning_rate': 0.15874432700492042, 'n_estimators': 299, 'subsample': 0.8350567435313899, 'colsample_bytree': 0.8848086259212147, 'min_child_weight': 2, 'gamma': 1.4943832757141013, 'reg_alpha': 0.0027716396315775114, 'reg_lambda': 0.04362863597657761, 'max_delta_step': 6}. Best is trial 14 with value: 0.6414634146341464.

Best trial: 14. Best value: 0.641463:  50%|█████     | 25/50 [05:05<03:14,  7.77s/it]

[I 2025-12-01 17:21:12,303] Trial 26 finished with value: 0.5858536585365853 and parameters: {'max_depth': 7, 'learning_rate': 0.1595171063527797, 'n_estimators': 284, 'subsample': 0.9314939732264037, 'colsample_bytree': 0.8908432604871367, 'min_child_weight': 2, 'gamma': 1.4009569163354203, 'reg_alpha': 0.0024621488722928243, 'reg_lambda': 3.083314601143578e-05, 'max_delta_step': 5}. Best is trial 14 with value: 0.6414634146341464.

Best trial: 14. Best value: 0.641463:  52%|█████▏    | 26/50 [05:06<02:24,  6.01s/it]

[I 2025-12-01 17:21:13,347] Trial 25 finished with value: 0.5814634146341464 and parameters: {'max_depth': 7, 'learning_rate': 0.18510766232489614, 'n_estimators': 315, 'subsample': 0.8287152750009876, 'colsample_bytree': 0.8940551032481301, 'min_child_weight': 2, 'gamma': 0.01109189379410507, 'reg_alpha': 0.41188959278707404, 'reg_lambda': 0.00014264714243094497, 'max_delta_step': 5}. Best is trial 14 with value: 0.6414634146341464.

Best trial: 14. Best value: 0.641463:  54%|█████▍    | 27/50 [05:15<02:35,  6.75s/it]

[I 2025-12-01 17:21:22,088] Trial 27 pruned.

Best trial: 14. Best value: 0.641463:  56%|█████▌    | 28/50 [05:19<02:09,  5.89s/it]

[I 2025-12-01 17:21:25,778] Trial 29 pruned.

Best trial: 14. Best value: 0.641463:  58%|█████▊    | 29/50 [05:23<01:54,  5.44s/it]

[I 2025-12-01 17:21:30,077] Trial 30 pruned.

Best trial: 14. Best value: 0.641463:  60%|██████    | 30/50 [05:30<01:55,  5.75s/it]

[I 2025-12-01 17:21:36,596] Trial 31 pruned.

Best trial: 14. Best value: 0.641463:  62%|██████▏   | 31/50 [05:35<01:50,  5.80s/it]

[I 2025-12-01 17:21:42,524] Trial 33 pruned.

Best trial: 14. Best value: 0.641463:  64%|██████▍   | 32/50 [05:48<02:21,  7.87s/it]

[I 2025-12-01 17:21:55,322] Trial 23 finished with value: 0.45707317073170733 and parameters: {'max_depth': 9, 'learning_rate': 0.02787827779811546, 'n_estimators': 837, 'subsample': 0.8797467631035361, 'colsample_bytree': 0.7611457019857304, 'min_child_weight': 5, 'gamma': 0.022535187321925776, 'reg_alpha': 0.0018684982389704664, 'reg_lambda': 3.136872980012256e-05, 'max_delta_step': 9}. Best is trial 14 with value: 0.6414634146341464.

Best trial: 14. Best value: 0.641463:  66%|██████▌   | 33/50 [06:02<02:44,  9.69s/it]

[I 2025-12-01 17:22:09,351] Trial 28 finished with value: 0.5292682926829269 and parameters: {'max_depth': 9, 'learning_rate': 0.08360394205511225, 'n_estimators': 553, 'subsample': 0.8332633452872132, 'colsample_bytree': 0.8060005921643705, 'min_child_weight': 4, 'gamma': 4.690054786952685, 'reg_alpha': 0.41637947949431525, 'reg_lambda': 0.0002761912533632236, 'max_delta_step': 9}. Best is trial 14 with value: 0.6414634146341464.

Best trial: 14. Best value: 0.641463:  68%|██████▊   | 34/50 [06:12<02:35,  9.74s/it]

[I 2025-12-01 17:22:19,204] Trial 32 finished with value: 0.6014634146341464 and parameters: {'max_depth': 6, 'learning_rate': 0.2362132795273674, 'n_estimators': 373, 'subsample': 0.9709583140649156, 'colsample_bytree': 0.8487977375121716, 'min_child_weight': 1, 'gamma': 3.079585744373209, 'reg_alpha': 0.0009795535038753561, 'reg_lambda': 9.026733617444486e-07, 'max_delta_step': 10}. Best is trial 14 with value: 0.6414634146341464.

Best trial: 14. Best value: 0.641463:  70%|███████   | 35/50 [07:47<08:44, 34.98s/it]

[I 2025-12-01 17:23:53,574] Trial 34 finished with value: 0.6258536585365854 and parameters: {'max_depth': 10, 'learning_rate': 0.0999450052685162, 'n_estimators': 1231, 'subsample': 0.9653933809967438, 'colsample_bytree': 0.9148059849186123, 'min_child_weight': 1, 'gamma': 1.240938660851377, 'reg_alpha': 0.0014516519494366937, 'reg_lambda': 4.992246233243339e-07, 'max_delta_step': 10}. Best is trial 14 with value: 0.6414634146341464.

Best trial: 35. Best value: 0.653659:  72%|███████▏  | 36/50 [07:53<06:10, 26.45s/it]

[I 2025-12-01 17:24:00,012] Trial 35 finished with value: 0.6536585365853658 and parameters: {'max_depth': 6, 'learning_rate': 0.2200702237224465, 'n_estimators': 1140, 'subsample': 0.9756227180934598, 'colsample_bytree': 0.9848191232315371, 'min_child_weight': 1, 'gamma': 1.7383080967176359, 'reg_alpha': 1.606767839921331, 'reg_lambda': 1.4079250658387133e-06, 'max_delta_step': 10}. Best is trial 35 with value: 0.6536585365853658.

Best trial: 35. Best value: 0.653659:  74%|███████▍  | 37/50 [08:10<05:08, 23.74s/it]

[I 2025-12-01 17:24:17,412] Trial 36 finished with value: 0.6180487804878049 and parameters: {'max_depth': 10, 'learning_rate': 0.21955200954342374, 'n_estimators': 1193, 'subsample': 0.9662782594365175, 'colsample_bytree': 0.9898920492715126, 'min_child_weight': 1, 'gamma': 1.6717394873789646, 'reg_alpha': 0.08508173953405453, 'reg_lambda': 9.399007406658209e-07, 'max_delta_step': 10}. Best is trial 35 with value: 0.6536585365853658.

Best trial: 35. Best value: 0.653659:  76%|███████▌  | 38/50 [09:11<06:58, 34.90s/it]

[I 2025-12-01 17:25:18,416] Trial 37 finished with value: 0.5414634146341464 and parameters: {'max_depth': 4, 'learning_rate': 0.10321274800507174, 'n_estimators': 1491, 'subsample': 0.9570577252325154, 'colsample_bytree': 0.9964140137417044, 'min_child_weight': 1, 'gamma': 1.6879143830683034, 'reg_alpha': 0.11505376294068154, 'reg_lambda': 7.741265523589654, 'max_delta_step': 10}. Best is trial 35 with value: 0.6536585365853658.

Best trial: 35. Best value: 0.653659:  78%|███████▊  | 39/50 [09:43<06:13, 33.95s/it]

[I 2025-12-01 17:25:50,165] Trial 40 finished with value: 0.5292682926829269 and parameters: {'max_depth': 7, 'learning_rate': 0.1577828757979059, 'n_estimators': 998, 'subsample': 0.9128214307784737, 'colsample_bytree': 0.9259597865137613, 'min_child_weight': 3, 'gamma': 2.2422958884732647, 'reg_alpha': 2.387813280216627, 'reg_lambda': 8.836084659857274, 'max_delta_step': 7}. Best is trial 35 with value: 0.6536585365853658.

Best trial: 35. Best value: 0.653659:  80%|████████  | 40/50 [09:57<04:38, 27.85s/it]

[I 2025-12-01 17:26:03,743] Trial 38 finished with value: 0.6214634146341464 and parameters: {'max_depth': 10, 'learning_rate': 0.10164297291096086, 'n_estimators': 1299, 'subsample': 0.9257104813269068, 'colsample_bytree': 0.9292891781327802, 'min_child_weight': 1, 'gamma': 1.691675833374529, 'reg_alpha': 0.006370493349588277, 'reg_lambda': 0.0014497074369519507, 'max_delta_step': 10}. Best is trial 35 with value: 0.6536585365853658.

Best trial: 35. Best value: 0.653659:  82%|████████▏ | 41/50 [10:30<04:26, 29.57s/it]

[I 2025-12-01 17:26:37,346] Trial 39 finished with value: 0.5614634146341464 and parameters: {'max_depth': 7, 'learning_rate': 0.14775514527859124, 'n_estimators': 1480, 'subsample': 0.9163116757259212, 'colsample_bytree': 0.9961046466489079, 'min_child_weight': 1, 'gamma': 2.2744944792405857, 'reg_alpha': 1.729194439814552, 'reg_lambda': 4.437755079100373, 'max_delta_step': 7}. Best is trial 35 with value: 0.6536585365853658.

Best trial: 35. Best value: 0.653659:  84%|████████▍ | 42/50 [10:46<03:23, 25.40s/it]

[I 2025-12-01 17:26:52,994] Trial 41 finished with value: 0.5814634146341464 and parameters: {'max_depth': 7, 'learning_rate': 0.1463981820522513, 'n_estimators': 1007, 'subsample': 0.9191138784203533, 'colsample_bytree': 0.9122848625516252, 'min_child_weight': 3, 'gamma': 2.35543313432476, 'reg_alpha': 1.0202128496697742, 'reg_lambda': 0.0006440585819929211, 'max_delta_step': 7}. Best is trial 35 with value: 0.6536585365853658.

Best trial: 35. Best value: 0.653659:  86%|████████▌ | 43/50 [11:21<03:18, 28.34s/it]

[I 2025-12-01 17:27:28,196] Trial 42 finished with value: 0.5858536585365853 and parameters: {'max_depth': 8, 'learning_rate': 0.2581664579326326, 'n_estimators': 939, 'subsample': 0.9176240837106453, 'colsample_bytree': 0.9478118320433768, 'min_child_weight': 2, 'gamma': 1.0102232609522213, 'reg_alpha': 1.0291404232491628, 'reg_lambda': 0.001968906648770154, 'max_delta_step': 0}. Best is trial 35 with value: 0.6536585365853658.

Best trial: 35. Best value: 0.653659:  88%|████████▊ | 44/50 [11:48<02:47, 27.98s/it]

[I 2025-12-01 17:27:55,345] Trial 43 finished with value: 0.5658536585365854 and parameters: {'max_depth': 8, 'learning_rate': 0.13874144590439072, 'n_estimators': 1120, 'subsample': 0.8577368914343669, 'colsample_bytree': 0.8661457357228362, 'min_child_weight': 2, 'gamma': 1.0392794288417981, 'reg_alpha': 2.139775648401294, 'reg_lambda': 2.5972319818466808e-06, 'max_delta_step': 8}. Best is trial 35 with value: 0.6536585365853658.

Best trial: 35. Best value: 0.653659:  90%|█████████ | 45/50 [12:14<02:15, 27.17s/it]

[I 2025-12-01 17:28:20,627] Trial 44 finished with value: 0.578048780487805 and parameters: {'max_depth': 8, 'learning_rate': 0.25276310074485575, 'n_estimators': 1117, 'subsample': 0.9895441867792012, 'colsample_bytree': 0.945028250878337, 'min_child_weight': 2, 'gamma': 1.0835120890859455, 'reg_alpha': 0.0002853472170288865, 'reg_lambda': 2.5475869927470806e-07, 'max_delta_step': 8}. Best is trial 35 with value: 0.6536585365853658.

Best trial: 35. Best value: 0.653659:  92%|█████████▏| 46/50 [12:30<01:35, 23.87s/it]

[I 2025-12-01 17:28:36,807] Trial 45 finished with value: 0.5492682926829269 and parameters: {'max_depth': 8, 'learning_rate': 0.2984627685523633, 'n_estimators': 1135, 'subsample': 0.9971288767377471, 'colsample_bytree': 0.9540017187979718, 'min_child_weight': 2, 'gamma': 1.0091273382153205, 'reg_alpha': 0.0002631913225926956, 'reg_lambda': 2.1044248376610227e-08, 'max_delta_step': 8}. Best is trial 35 with value: 0.6536585365853658.

Best trial: 35. Best value: 0.653659:  94%|█████████▍| 47/50 [13:01<01:18, 26.18s/it]

[I 2025-12-01 17:29:08,375] Trial 46 finished with value: 0.5980487804878049 and parameters: {'max_depth': 10, 'learning_rate': 0.1978430346732432, 'n_estimators': 1179, 'subsample': 0.9960034009654367, 'colsample_bytree': 0.8626235562011518, 'min_child_weight': 2, 'gamma': 0.5462016793512338, 'reg_alpha': 0.00027129188358234943, 'reg_lambda': 1.7890145660687535e-08, 'max_delta_step': 8}. Best is trial 35 with value: 0.6536585365853658.

Best trial: 35. Best value: 0.653659:  96%|█████████▌| 48/50 [13:36<00:57, 28.65s/it]

[I 2025-12-01 17:29:42,798] Trial 47 finished with value: 0.5614634146341464 and parameters: {'max_depth': 10, 'learning_rate': 0.19416032968539096, 'n_estimators': 1251, 'subsample': 0.9981254622606602, 'colsample_bytree': 0.9646105031194645, 'min_child_weight': 1, 'gamma': 0.5791983272556748, 'reg_alpha': 0.0001873944424736062, 'reg_lambda': 2.113290699161511e-08, 'max_delta_step': 8}. Best is trial 35 with value: 0.6536585365853658.

Best trial: 35. Best value: 0.653659:  98%|█████████▊| 49/50 [13:46<00:23, 23.19s/it]

[I 2025-12-01 17:29:53,257] Trial 48 finished with value: 0.6458536585365854 and parameters: {'max_depth': 6, 'learning_rate': 0.18877753936297387, 'n_estimators': 1265, 'subsample': 0.9988813183897749, 'colsample_bytree': 0.8653915252368538, 'min_child_weight': 1, 'gamma': 0.3482911191982918, 'reg_alpha': 0.007832066013838393, 'reg_lambda': 2.2795840442029328e-08, 'max_delta_step': 3}. Best is trial 35 with value: 0.6536585365853658.

Best trial: 35. Best value: 0.653659: 100%|██████████| 50/50 [13:56<00:00, 16.74s/it]

[I 2025-12-01 17:30:03,312] Trial 49 finished with value: 0.5414634146341464 and parameters: {'max_depth': 6, 'learning_rate': 0.1941105953571445, 'n_estimators': 1280, 'subsample': 0.9527440364374317, 'colsample_bytree': 0.8216038058696202, 'min_child_weight': 1, 'gamma': 0.6279474653161116, 'reg_alpha': 0.007418493167963266, 'reg_lambda': 5.590083439459965e-08, 'max_delta_step': 3}. Best is trial 35 with value: 0.6536585365853658.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 17:30:12,732] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 64, Test size: 16
Using Leave-One-Out CV with 64 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.645833:   2%|▏         | 1/50 [00:28<23:16, 28.49s/it]

[I 2025-12-01 17:30:41,209] Trial 0 finished with value: 0.6458333333333333 and parameters: {'max_depth': 6, 'learning_rate': 0.0985344860638261, 'n_estimators': 298, 'subsample': 0.5861834610063201, 'colsample_bytree': 0.5380617120512035, 'min_child_weight': 4, 'gamma': 4.2482365617878415, 'reg_alpha': 0.12105765750196679, 'reg_lambda': 0.00032293877203518696, 'max_delta_step': 4}. Best is trial 0 with value: 0.6458333333333333.

Best trial: 3. Best value: 0.670833:   4%|▍         | 2/50 [00:44<17:01, 21.27s/it]

[I 2025-12-01 17:30:57,437] Trial 3 finished with value: 0.6708333333333334 and parameters: {'max_depth': 8, 'learning_rate': 0.08494290753419588, 'n_estimators': 586, 'subsample': 0.619103712446907, 'colsample_bytree': 0.991433445205785, 'min_child_weight': 7, 'gamma': 0.7322082916018846, 'reg_alpha': 2.382640812530927e-07, 'reg_lambda': 0.001228876066568717, 'max_delta_step': 3}. Best is trial 3 with value: 0.6708333333333334.

Best trial: 3. Best value: 0.670833:   6%|▌         | 3/50 [00:53<12:16, 15.67s/it]

[I 2025-12-01 17:31:06,401] Trial 2 finished with value: 0.43333333333333335 and parameters: {'max_depth': 6, 'learning_rate': 0.2979480335020083, 'n_estimators': 805, 'subsample': 0.631241640732203, 'colsample_bytree': 0.7562545685247901, 'min_child_weight': 10, 'gamma': 0.35216846891959863, 'reg_alpha': 7.926527785947805e-08, 'reg_lambda': 0.0005604917362519396, 'max_delta_step': 1}. Best is trial 3 with value: 0.6708333333333334.

Best trial: 3. Best value: 0.670833:   8%|▊         | 4/50 [00:54<07:36,  9.92s/it]

[I 2025-12-01 17:31:07,536] Trial 1 finished with value: 0.6583333333333333 and parameters: {'max_depth': 6, 'learning_rate': 0.06670490843571426, 'n_estimators': 544, 'subsample': 0.9236688617417264, 'colsample_bytree': 0.6471754616961667, 'min_child_weight': 3, 'gamma': 0.518976893943639, 'reg_alpha': 0.029519713725691926, 'reg_lambda': 3.2670453604167347, 'max_delta_step': 2}. Best is trial 3 with value: 0.6708333333333334.

Best trial: 7. Best value: 0.683333:  10%|█         | 5/50 [01:26<13:14, 17.65s/it]

[I 2025-12-01 17:31:38,888] Trial 7 finished with value: 0.6833333333333333 and parameters: {'max_depth': 8, 'learning_rate': 0.07479992426210302, 'n_estimators': 601, 'subsample': 0.626230797834884, 'colsample_bytree': 0.6358372892137356, 'min_child_weight': 5, 'gamma': 3.0372956879220094, 'reg_alpha': 0.0005564039641018522, 'reg_lambda': 0.016871652591375203, 'max_delta_step': 7}. Best is trial 7 with value: 0.6833333333333333.

Best trial: 7. Best value: 0.683333:  12%|█▏        | 6/50 [01:35<10:51, 14.80s/it]

[I 2025-12-01 17:31:48,153] Trial 5 finished with value: 0.6791666666666667 and parameters: {'max_depth': 9, 'learning_rate': 0.014985904294742086, 'n_estimators': 450, 'subsample': 0.7049549099758083, 'colsample_bytree': 0.9400420713031776, 'min_child_weight': 3, 'gamma': 3.0281091878323747, 'reg_alpha': 3.2250745814693347e-07, 'reg_lambda': 2.9157713455747394, 'max_delta_step': 0}. Best is trial 7 with value: 0.6833333333333333.

Best trial: 7. Best value: 0.683333:  14%|█▍        | 7/50 [01:41<08:34, 11.97s/it]

[I 2025-12-01 17:31:54,287] Trial 4 finished with value: 0.6791666666666667 and parameters: {'max_depth': 10, 'learning_rate': 0.15333129306790497, 'n_estimators': 1323, 'subsample': 0.8940103735013886, 'colsample_bytree': 0.5781905418300741, 'min_child_weight': 3, 'gamma': 2.9976520522426133, 'reg_alpha': 0.0017753966305858653, 'reg_lambda': 4.037120613523957e-06, 'max_delta_step': 4}. Best is trial 7 with value: 0.6833333333333333.

Best trial: 7. Best value: 0.683333:  16%|█▌        | 8/50 [01:42<05:52,  8.39s/it]

[I 2025-12-01 17:31:55,004] Trial 6 finished with value: 0.2875 and parameters: {'max_depth': 3, 'learning_rate': 0.06185471052788069, 'n_estimators': 971, 'subsample': 0.6241690465665577, 'colsample_bytree': 0.9066554404974545, 'min_child_weight': 10, 'gamma': 1.2616458283392673, 'reg_alpha': 0.10866840081819046, 'reg_lambda': 3.796000759490107e-07, 'max_delta_step': 4}. Best is trial 7 with value: 0.6833333333333333.

Best trial: 7. Best value: 0.683333:  18%|█▊        | 9/50 [01:47<04:58,  7.28s/it]

[I 2025-12-01 17:31:59,864] Trial 8 finished with value: 0.5166666666666666 and parameters: {'max_depth': 6, 'learning_rate': 0.07553296665591161, 'n_estimators': 267, 'subsample': 0.5639087004914556, 'colsample_bytree': 0.9363818860605073, 'min_child_weight': 7, 'gamma': 4.833849683839181, 'reg_alpha': 3.653602356049204, 'reg_lambda': 1.0987832922105965e-08, 'max_delta_step': 10}. Best is trial 7 with value: 0.6833333333333333.

Best trial: 9. Best value: 0.729167:  20%|██        | 10/50 [02:02<06:33,  9.85s/it]

[I 2025-12-01 17:32:15,461] Trial 9 finished with value: 0.7291666666666667 and parameters: {'max_depth': 10, 'learning_rate': 0.13766297036428538, 'n_estimators': 234, 'subsample': 0.9761035423565811, 'colsample_bytree': 0.7338811927408153, 'min_child_weight': 1, 'gamma': 4.9795991124646735, 'reg_alpha': 0.01824026918163132, 'reg_lambda': 0.019170137966120732, 'max_delta_step': 2}. Best is trial 9 with value: 0.7291666666666667.

Best trial: 9. Best value: 0.729167:  22%|██▏       | 11/50 [02:07<05:25,  8.34s/it]

[I 2025-12-01 17:32:20,382] Trial 10 pruned.

Best trial: 9. Best value: 0.729167:  24%|██▍       | 12/50 [02:09<04:01,  6.35s/it]

[I 2025-12-01 17:32:22,173] Trial 11 pruned.

Best trial: 9. Best value: 0.729167:  26%|██▌       | 13/50 [02:24<05:27,  8.85s/it]

[I 2025-12-01 17:32:36,781] Trial 12 finished with value: 0.7041666666666666 and parameters: {'max_depth': 9, 'learning_rate': 0.03464530100166799, 'n_estimators': 578, 'subsample': 0.8528898501853505, 'colsample_bytree': 0.6015530956760036, 'min_child_weight': 6, 'gamma': 4.241656741335296, 'reg_alpha': 7.072480800806962e-07, 'reg_lambda': 3.0353697349067857e-05, 'max_delta_step': 9}. Best is trial 9 with value: 0.7291666666666667.

Best trial: 9. Best value: 0.729167:  28%|██▊       | 14/50 [03:10<12:11, 20.31s/it]

[I 2025-12-01 17:33:23,578] Trial 14 pruned.

Best trial: 15. Best value: 0.754167:  30%|███       | 15/50 [03:15<09:06, 15.60s/it]

[I 2025-12-01 17:33:28,266] Trial 15 finished with value: 0.7541666666666667 and parameters: {'max_depth': 8, 'learning_rate': 0.18036412529316456, 'n_estimators': 722, 'subsample': 0.9913000070265859, 'colsample_bytree': 0.7856731854022285, 'min_child_weight': 1, 'gamma': 2.1324349400442726, 'reg_alpha': 0.0001610363491211682, 'reg_lambda': 0.01880995909311476, 'max_delta_step': 7}. Best is trial 15 with value: 0.7541666666666667.

Best trial: 15. Best value: 0.754167:  32%|███▏      | 16/50 [03:45<11:15, 19.88s/it]

[I 2025-12-01 17:33:58,082] Trial 17 finished with value: 0.7166666666666667 and parameters: {'max_depth': 10, 'learning_rate': 0.021966217013920514, 'n_estimators': 465, 'subsample': 0.9861620851356724, 'colsample_bytree': 0.840435184754514, 'min_child_weight': 7, 'gamma': 3.9116345672825332, 'reg_alpha': 2.4567106997818294e-05, 'reg_lambda': 1.9734359086054485e-05, 'max_delta_step': 7}. Best is trial 15 with value: 0.7541666666666667.

Best trial: 15. Best value: 0.754167:  34%|███▍      | 17/50 [03:55<09:17, 16.91s/it]

[I 2025-12-01 17:34:08,070] Trial 16 finished with value: 0.7416666666666667 and parameters: {'max_depth': 10, 'learning_rate': 0.02362156563215013, 'n_estimators': 786, 'subsample': 0.9945744183774682, 'colsample_bytree': 0.8010040292132934, 'min_child_weight': 1, 'gamma': 3.9639062710569934, 'reg_alpha': 5.161859076174334e-06, 'reg_lambda': 0.025328526378328668, 'max_delta_step': 8}. Best is trial 15 with value: 0.7541666666666667.

Best trial: 15. Best value: 0.754167:  36%|███▌      | 18/50 [04:18<10:03, 18.86s/it]

[I 2025-12-01 17:34:31,480] Trial 13 finished with value: 0.7 and parameters: {'max_depth': 3, 'learning_rate': 0.024970114171699313, 'n_estimators': 1458, 'subsample': 0.8304283220984309, 'colsample_bytree': 0.7923618787471894, 'min_child_weight': 1, 'gamma': 1.8171261951469813, 'reg_alpha': 1.797445622017243e-05, 'reg_lambda': 0.0587009725384611, 'max_delta_step': 7}. Best is trial 15 with value: 0.7541666666666667.

Best trial: 15. Best value: 0.754167:  38%|███▊      | 19/50 [04:47<11:18, 21.89s/it]

[I 2025-12-01 17:35:00,290] Trial 21 pruned.

Best trial: 15. Best value: 0.754167:  40%|████      | 20/50 [05:04<10:11, 20.37s/it]

[I 2025-12-01 17:35:17,261] Trial 18 finished with value: 0.7416666666666667 and parameters: {'max_depth': 10, 'learning_rate': 0.29621099995181693, 'n_estimators': 1307, 'subsample': 0.9928050636668645, 'colsample_bytree': 0.8243420648368465, 'min_child_weight': 1, 'gamma': 1.6652678864393318, 'reg_alpha': 4.828807703902754e-05, 'reg_lambda': 0.06400810277425742, 'max_delta_step': 6}. Best is trial 15 with value: 0.7541666666666667.

Best trial: 15. Best value: 0.754167:  42%|████▏     | 21/50 [05:46<12:54, 26.71s/it]

[I 2025-12-01 17:35:58,748] Trial 19 finished with value: 0.6875 and parameters: {'max_depth': 9, 'learning_rate': 0.2776945982962587, 'n_estimators': 1485, 'subsample': 0.9954230142974794, 'colsample_bytree': 0.8452725835036141, 'min_child_weight': 1, 'gamma': 1.8290932716964887, 'reg_alpha': 0.0055551449999052035, 'reg_lambda': 0.10371144551331746, 'max_delta_step': 6}. Best is trial 15 with value: 0.7541666666666667.

Best trial: 15. Best value: 0.754167:  44%|████▍     | 22/50 [05:58<10:30, 22.53s/it]

[I 2025-12-01 17:36:11,535] Trial 22 pruned.

Best trial: 15. Best value: 0.754167:  46%|████▌     | 23/50 [06:24<10:36, 23.57s/it]

[I 2025-12-01 17:36:37,528] Trial 23 pruned.

Best trial: 15. Best value: 0.754167:  48%|████▊     | 24/50 [06:29<07:44, 17.88s/it]

[I 2025-12-01 17:36:42,126] Trial 20 finished with value: 0.6916666666666667 and parameters: {'max_depth': 9, 'learning_rate': 0.010674168304071604, 'n_estimators': 1145, 'subsample': 0.7746683801073376, 'colsample_bytree': 0.844520226442853, 'min_child_weight': 1, 'gamma': 1.8369625135703462, 'reg_alpha': 7.29603878002065e-05, 'reg_lambda': 0.2651550871029004, 'max_delta_step': 6}. Best is trial 15 with value: 0.7541666666666667.

Best trial: 15. Best value: 0.754167:  50%|█████     | 25/50 [06:37<06:16, 15.07s/it]

[I 2025-12-01 17:36:50,639] Trial 27 pruned.

Best trial: 15. Best value: 0.754167:  52%|█████▏    | 26/50 [07:00<06:56, 17.36s/it]

[I 2025-12-01 17:37:13,349] Trial 25 finished with value: 0.6541666666666667 and parameters: {'max_depth': 10, 'learning_rate': 0.2152327525279926, 'n_estimators': 916, 'subsample': 0.9346534824759796, 'colsample_bytree': 0.7408981929293326, 'min_child_weight': 2, 'gamma': 1.494578409715764, 'reg_alpha': 0.0001057393385853888, 'reg_lambda': 0.8223039673756476, 'max_delta_step': 8}. Best is trial 15 with value: 0.7541666666666667.

Best trial: 15. Best value: 0.754167:  54%|█████▍    | 27/50 [07:09<05:42, 14.88s/it]

[I 2025-12-01 17:37:22,427] Trial 29 pruned.

Best trial: 15. Best value: 0.754167:  56%|█████▌    | 28/50 [07:15<04:30, 12.28s/it]

[I 2025-12-01 17:37:28,642] Trial 26 pruned.

Best trial: 15. Best value: 0.754167:  58%|█████▊    | 29/50 [07:20<03:29,  9.98s/it]

[I 2025-12-01 17:37:33,262] Trial 24 pruned.

Best trial: 15. Best value: 0.754167:  60%|██████    | 30/50 [07:27<03:03,  9.19s/it]

[I 2025-12-01 17:37:40,605] Trial 31 pruned.

Best trial: 15. Best value: 0.754167:  62%|██████▏   | 31/50 [07:34<02:37,  8.31s/it]

[I 2025-12-01 17:37:46,848] Trial 33 pruned.

Best trial: 15. Best value: 0.754167:  64%|██████▍   | 32/50 [07:58<03:54, 13.01s/it]

[I 2025-12-01 17:38:10,839] Trial 34 finished with value: 0.6958333333333333 and parameters: {'max_depth': 10, 'learning_rate': 0.13233360826960272, 'n_estimators': 207, 'subsample': 0.9659944540627178, 'colsample_bytree': 0.7153856294742558, 'min_child_weight': 1, 'gamma': 4.52983757724784, 'reg_alpha': 0.009028798746476129, 'reg_lambda': 0.010206347462303743, 'max_delta_step': 3}. Best is trial 15 with value: 0.7541666666666667.

Best trial: 15. Best value: 0.754167:  66%|██████▌   | 33/50 [08:15<04:04, 14.37s/it]

[I 2025-12-01 17:38:28,388] Trial 28 finished with value: 0.6791666666666667 and parameters: {'max_depth': 5, 'learning_rate': 0.10948988091100562, 'n_estimators': 1251, 'subsample': 0.8818887078944728, 'colsample_bytree': 0.8907628374457958, 'min_child_weight': 2, 'gamma': 3.581777367634459, 'reg_alpha': 4.411783345151405e-06, 'reg_lambda': 0.0052209294372172355, 'max_delta_step': 8}. Best is trial 15 with value: 0.7541666666666667.

Best trial: 15. Best value: 0.754167:  68%|██████▊   | 34/50 [08:16<02:44, 10.30s/it]

[I 2025-12-01 17:38:29,185] Trial 30 finished with value: 0.7291666666666667 and parameters: {'max_depth': 8, 'learning_rate': 0.19454782054013492, 'n_estimators': 842, 'subsample': 0.9590037848333239, 'colsample_bytree': 0.8899858093839164, 'min_child_weight': 2, 'gamma': 2.7124149794731016, 'reg_alpha': 0.0004027473839776965, 'reg_lambda': 0.009356950043033682, 'max_delta_step': 8}. Best is trial 15 with value: 0.7541666666666667.

Best trial: 15. Best value: 0.754167:  70%|███████   | 35/50 [08:29<02:45, 11.04s/it]

[I 2025-12-01 17:38:41,954] Trial 32 pruned.

Best trial: 37. Best value: 0.775:  72%|███████▏  | 36/50 [08:46<03:02, 13.04s/it]

[I 2025-12-01 17:38:59,675] Trial 37 finished with value: 0.775 and parameters: {'max_depth': 9, 'learning_rate': 0.27587732133510967, 'n_estimators': 378, 'subsample': 0.9753099832263115, 'colsample_bytree': 0.8237406459640705, 'min_child_weight': 1, 'gamma': 4.467664607548047, 'reg_alpha': 0.03523239155718852, 'reg_lambda': 0.0003756791644731541, 'max_delta_step': 0}. Best is trial 37 with value: 0.775.

Best trial: 37. Best value: 0.775:  74%|███████▍  | 37/50 [08:58<02:42, 12.48s/it]

[I 2025-12-01 17:39:10,825] Trial 36 finished with value: 0.7125 and parameters: {'max_depth': 9, 'learning_rate': 0.049327725566580494, 'n_estimators': 425, 'subsample': 0.971036566165477, 'colsample_bytree': 0.8170099837984146, 'min_child_weight': 1, 'gamma': 0.05715706627497763, 'reg_alpha': 0.03846142716111431, 'reg_lambda': 0.026073926348606544, 'max_delta_step': 2}. Best is trial 37 with value: 0.775.

Best trial: 37. Best value: 0.775:  76%|███████▌  | 38/50 [09:01<01:55,  9.66s/it]

[I 2025-12-01 17:39:13,890] Trial 35 finished with value: 0.7208333333333333 and parameters: {'max_depth': 9, 'learning_rate': 0.04547640912932616, 'n_estimators': 834, 'subsample': 0.9694988108492357, 'colsample_bytree': 0.659851493737728, 'min_child_weight': 1, 'gamma': 4.29102458708324, 'reg_alpha': 0.09627175644041157, 'reg_lambda': 0.02129094774774413, 'max_delta_step': 2}. Best is trial 37 with value: 0.775.

Best trial: 37. Best value: 0.775:  78%|███████▊  | 39/50 [09:05<01:28,  8.09s/it]

[I 2025-12-01 17:39:18,336] Trial 41 pruned.

Best trial: 37. Best value: 0.775:  80%|████████  | 40/50 [09:09<01:08,  6.88s/it]

[I 2025-12-01 17:39:22,377] Trial 38 finished with value: 0.7333333333333334 and parameters: {'max_depth': 9, 'learning_rate': 0.2622308628268025, 'n_estimators': 498, 'subsample': 0.9123421645590976, 'colsample_bytree': 0.8172830558116316, 'min_child_weight': 1, 'gamma': 4.52708600077177, 'reg_alpha': 0.029529854553003148, 'reg_lambda': 0.028920565688650094, 'max_delta_step': 2}. Best is trial 37 with value: 0.775.

Best trial: 37. Best value: 0.775:  82%|████████▏ | 41/50 [09:13<00:53,  5.97s/it]

[I 2025-12-01 17:39:26,220] Trial 39 pruned.

Best trial: 37. Best value: 0.775:  84%|████████▍ | 42/50 [09:15<00:39,  4.92s/it]

[I 2025-12-01 17:39:28,690] Trial 43 pruned.

Best trial: 37. Best value: 0.775:  86%|████████▌ | 43/50 [09:18<00:30,  4.29s/it]

[I 2025-12-01 17:39:31,509] Trial 42 pruned.

Best trial: 37. Best value: 0.775:  88%|████████▊ | 44/50 [09:22<00:24,  4.15s/it]

[I 2025-12-01 17:39:35,342] Trial 45 pruned.

Best trial: 37. Best value: 0.775:  90%|█████████ | 45/50 [09:28<00:23,  4.80s/it]

[I 2025-12-01 17:39:41,653] Trial 47 pruned.

Best trial: 37. Best value: 0.775:  92%|█████████▏| 46/50 [09:35<00:21,  5.25s/it]

[I 2025-12-01 17:39:47,960] Trial 40 finished with value: 0.7541666666666667 and parameters: {'max_depth': 9, 'learning_rate': 0.24539024857324238, 'n_estimators': 503, 'subsample': 0.9084257849294028, 'colsample_bytree': 0.7611191355095398, 'min_child_weight': 3, 'gamma': 4.523474123535306, 'reg_alpha': 8.333875808468601e-07, 'reg_lambda': 0.0001905104371403173, 'max_delta_step': 0}. Best is trial 37 with value: 0.775.

Best trial: 37. Best value: 0.775:  94%|█████████▍| 47/50 [09:51<00:25,  8.47s/it]

[I 2025-12-01 17:40:03,924] Trial 46 finished with value: 0.7208333333333333 and parameters: {'max_depth': 8, 'learning_rate': 0.17442204004623868, 'n_estimators': 382, 'subsample': 0.9428498190205513, 'colsample_bytree': 0.867293984125804, 'min_child_weight': 1, 'gamma': 4.557234858709051, 'reg_alpha': 0.0013107372484597317, 'reg_lambda': 0.1254615597945776, 'max_delta_step': 3}. Best is trial 37 with value: 0.775.

Best trial: 37. Best value: 0.775:  96%|█████████▌| 48/50 [09:54<00:14,  7.06s/it]

[I 2025-12-01 17:40:07,702] Trial 48 pruned.

Best trial: 37. Best value: 0.775:  98%|█████████▊| 49/50 [10:02<00:07,  7.28s/it]

[I 2025-12-01 17:40:15,502] Trial 44 finished with value: 0.7208333333333333 and parameters: {'max_depth': 10, 'learning_rate': 0.2432040971920236, 'n_estimators': 653, 'subsample': 0.9518686090066172, 'colsample_bytree': 0.861703137152931, 'min_child_weight': 1, 'gamma': 4.538765917278877, 'reg_alpha': 8.401707978778057e-07, 'reg_lambda': 0.0010887130404241912, 'max_delta_step': 1}. Best is trial 37 with value: 0.775.

Best trial: 37. Best value: 0.775: 100%|██████████| 50/50 [10:13<00:00, 12.27s/it]

[I 2025-12-01 17:40:26,032] Trial 49 finished with value: 0.7416666666666667 and parameters: {'max_depth': 9, 'learning_rate': 0.08695487973562878, 'n_estimators': 609, 'subsample': 0.9801966397842001, 'colsample_bytree': 0.7739411807045884, 'min_child_weight': 2, 'gamma': 3.8711063223137816, 'reg_alpha': 6.576635721403563e-07, 'reg_lambda': 7.573933676438872e-06, 'max_delta_step': 3}. Best is trial 37 with value: 0.775.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 17:40:29,745] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 67, Test size: 17
Using Leave-One-Out CV with 67 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0:   2%|▏         | 1/50 [00:18<14:56, 18.29s/it]

[I 2025-12-01 17:40:48,031] Trial 0 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.02963288464684295, 'n_estimators': 380, 'subsample': 0.872353641362146, 'colsample_bytree': 0.5153454881824332, 'min_child_weight': 10, 'gamma': 2.982093983437097, 'reg_alpha': 0.017245719002525466, 'reg_lambda': 7.092344686626303e-06, 'max_delta_step': 2}. Best is trial 0 with value: 0.0.

Best trial: 2. Best value: 0.516417:   4%|▍         | 2/50 [00:24<09:03, 11.32s/it]

[I 2025-12-01 17:40:54,467] Trial 2 finished with value: 0.5164165103189493 and parameters: {'max_depth': 6, 'learning_rate': 0.02758763815226128, 'n_estimators': 466, 'subsample': 0.6006313415357245, 'colsample_bytree': 0.8161630512076923, 'min_child_weight': 7, 'gamma': 3.226001441866298, 'reg_alpha': 0.007315451779752433, 'reg_lambda': 1.5804328827471728e-05, 'max_delta_step': 1}. Best is trial 2 with value: 0.5164165103189493.

Best trial: 2. Best value: 0.516417:   6%|▌         | 3/50 [00:31<07:06,  9.07s/it]

[I 2025-12-01 17:41:00,869] Trial 3 finished with value: 0.4849906191369606 and parameters: {'max_depth': 3, 'learning_rate': 0.06923582581997416, 'n_estimators': 270, 'subsample': 0.9638552768696349, 'colsample_bytree': 0.6198218410956922, 'min_child_weight': 1, 'gamma': 1.2793852725495647, 'reg_alpha': 0.12205389743713116, 'reg_lambda': 2.9009557179044227, 'max_delta_step': 7}. Best is trial 2 with value: 0.5164165103189493.

Best trial: 5. Best value: 0.540807:   8%|▊         | 4/50 [00:58<12:37, 16.46s/it]

[I 2025-12-01 17:41:28,661] Trial 5 finished with value: 0.5408067542213884 and parameters: {'max_depth': 4, 'learning_rate': 0.010681249204664131, 'n_estimators': 417, 'subsample': 0.518335170650373, 'colsample_bytree': 0.9319277824101218, 'min_child_weight': 5, 'gamma': 2.7740948533814307, 'reg_alpha': 1.7675602408890165e-07, 'reg_lambda': 0.00454832969197663, 'max_delta_step': 7}. Best is trial 5 with value: 0.5408067542213884.

Best trial: 4. Best value: 0.547842:  10%|█         | 5/50 [01:05<09:41, 12.92s/it]

[I 2025-12-01 17:41:35,301] Trial 4 finished with value: 0.5478424015009381 and parameters: {'max_depth': 5, 'learning_rate': 0.014738625944020832, 'n_estimators': 484, 'subsample': 0.50646048943528, 'colsample_bytree': 0.8389052973026969, 'min_child_weight': 3, 'gamma': 4.326972495930855, 'reg_alpha': 0.00018611753055732875, 'reg_lambda': 5.612104895513515e-07, 'max_delta_step': 0}. Best is trial 4 with value: 0.5478424015009381.

Best trial: 4. Best value: 0.547842:  12%|█▏        | 6/50 [01:18<09:27, 12.90s/it]

[I 2025-12-01 17:41:48,174] Trial 6 finished with value: 0.5356472795497186 and parameters: {'max_depth': 9, 'learning_rate': 0.03815286201368038, 'n_estimators': 477, 'subsample': 0.8192257270939189, 'colsample_bytree': 0.6838094078308897, 'min_child_weight': 2, 'gamma': 0.6549755013621611, 'reg_alpha': 6.801031010740191e-07, 'reg_lambda': 1.8803893216311058e-06, 'max_delta_step': 0}. Best is trial 4 with value: 0.5478424015009381.

Best trial: 4. Best value: 0.547842:  14%|█▍        | 7/50 [01:34<10:05, 14.07s/it]

[I 2025-12-01 17:42:04,654] Trial 1 finished with value: 0.5459662288930581 and parameters: {'max_depth': 5, 'learning_rate': 0.09872314177150657, 'n_estimators': 1481, 'subsample': 0.9929499625462295, 'colsample_bytree': 0.5260802586470044, 'min_child_weight': 2, 'gamma': 3.5165339550655705, 'reg_alpha': 0.0026746766006625995, 'reg_lambda': 6.633869224373884e-05, 'max_delta_step': 3}. Best is trial 4 with value: 0.5478424015009381.

Best trial: 4. Best value: 0.547842:  16%|█▌        | 8/50 [02:06<13:49, 19.75s/it]

[I 2025-12-01 17:42:36,552] Trial 9 finished with value: 0.5356472795497186 and parameters: {'max_depth': 7, 'learning_rate': 0.05067106083780452, 'n_estimators': 961, 'subsample': 0.5905206404815846, 'colsample_bytree': 0.6069002602140035, 'min_child_weight': 4, 'gamma': 2.1175457586775193, 'reg_alpha': 1.4529259124808154e-05, 'reg_lambda': 0.00520771437417638, 'max_delta_step': 0}. Best is trial 4 with value: 0.5478424015009381.

Best trial: 4. Best value: 0.547842:  18%|█▊        | 9/50 [02:20<12:08, 17.78s/it]

[I 2025-12-01 17:42:49,990] Trial 7 finished with value: 0.47983114446529085 and parameters: {'max_depth': 10, 'learning_rate': 0.04679520829029704, 'n_estimators': 1253, 'subsample': 0.9875731991649244, 'colsample_bytree': 0.9944614167291044, 'min_child_weight': 4, 'gamma': 0.666701131056861, 'reg_alpha': 2.0392489654968587e-05, 'reg_lambda': 0.21731637233919615, 'max_delta_step': 6}. Best is trial 4 with value: 0.5478424015009381.

Best trial: 10. Best value: 0.572233:  20%|██        | 10/50 [02:30<10:16, 15.40s/it]

[I 2025-12-01 17:43:00,056] Trial 10 finished with value: 0.5722326454033771 and parameters: {'max_depth': 6, 'learning_rate': 0.031490578275522506, 'n_estimators': 396, 'subsample': 0.6071160032023748, 'colsample_bytree': 0.90676380877217, 'min_child_weight': 1, 'gamma': 1.7141167746178017, 'reg_alpha': 5.957272675570853e-05, 'reg_lambda': 0.2561784126720398, 'max_delta_step': 2}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  22%|██▏       | 11/50 [02:37<08:24, 12.94s/it]

[I 2025-12-01 17:43:07,443] Trial 13 pruned.

Best trial: 10. Best value: 0.572233:  24%|██▍       | 12/50 [02:49<07:59, 12.61s/it]

[I 2025-12-01 17:43:19,285] Trial 12 finished with value: 0.5286116322701688 and parameters: {'max_depth': 3, 'learning_rate': 0.10341554336604956, 'n_estimators': 340, 'subsample': 0.7665039587831974, 'colsample_bytree': 0.5384492662443323, 'min_child_weight': 3, 'gamma': 0.25123854917352084, 'reg_alpha': 1.7380481280606073e-05, 'reg_lambda': 0.47733295431261036, 'max_delta_step': 7}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  26%|██▌       | 13/50 [03:02<07:50, 12.73s/it]

[I 2025-12-01 17:43:32,284] Trial 8 finished with value: 0.5042213883677298 and parameters: {'max_depth': 7, 'learning_rate': 0.029870230589032605, 'n_estimators': 1255, 'subsample': 0.7578467618287257, 'colsample_bytree': 0.8474202991920987, 'min_child_weight': 2, 'gamma': 2.540148240998093, 'reg_alpha': 0.03674460264224819, 'reg_lambda': 6.986916033106542, 'max_delta_step': 0}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  28%|██▊       | 14/50 [03:10<06:43, 11.22s/it]

[I 2025-12-01 17:43:40,019] Trial 11 finished with value: 0.5042213883677298 and parameters: {'max_depth': 6, 'learning_rate': 0.043359234737105255, 'n_estimators': 1123, 'subsample': 0.8668481029884919, 'colsample_bytree': 0.7320916716946075, 'min_child_weight': 7, 'gamma': 2.5672846736777526, 'reg_alpha': 0.018889518254337788, 'reg_lambda': 0.519724610757769, 'max_delta_step': 10}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  30%|███       | 15/50 [04:00<13:26, 23.05s/it]

[I 2025-12-01 17:44:30,489] Trial 14 finished with value: 0.5548780487804879 and parameters: {'max_depth': 5, 'learning_rate': 0.012996175142524487, 'n_estimators': 716, 'subsample': 0.5078449123168041, 'colsample_bytree': 0.7968864870894434, 'min_child_weight': 1, 'gamma': 4.608205919136227, 'reg_alpha': 9.679399329483932e-05, 'reg_lambda': 4.9169097124016783e-08, 'max_delta_step': 4}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  32%|███▏      | 16/50 [04:10<10:49, 19.12s/it]

[I 2025-12-01 17:44:40,469] Trial 16 finished with value: 0.5530018761726079 and parameters: {'max_depth': 5, 'learning_rate': 0.012344152766484685, 'n_estimators': 668, 'subsample': 0.5050218005016247, 'colsample_bytree': 0.7315340326619679, 'min_child_weight': 1, 'gamma': 4.772524996506374, 'reg_alpha': 3.8711662879687636, 'reg_lambda': 6.548543715908448e-08, 'max_delta_step': 4}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  34%|███▍      | 17/50 [04:17<08:27, 15.37s/it]

[I 2025-12-01 17:44:47,127] Trial 15 finished with value: 0.5722326454033771 and parameters: {'max_depth': 5, 'learning_rate': 0.010328971639966605, 'n_estimators': 705, 'subsample': 0.5011150626663642, 'colsample_bytree': 0.8002265648835467, 'min_child_weight': 1, 'gamma': 4.461096115662571, 'reg_alpha': 0.00025510734270025356, 'reg_lambda': 4.7232139152523215e-08, 'max_delta_step': 4}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  36%|███▌      | 18/50 [04:23<06:44, 12.64s/it]

[I 2025-12-01 17:44:53,419] Trial 20 pruned.

Best trial: 10. Best value: 0.572233:  38%|███▊      | 19/50 [04:34<06:11, 11.97s/it]

[I 2025-12-01 17:45:03,835] Trial 21 pruned.

Best trial: 10. Best value: 0.572233:  40%|████      | 20/50 [04:34<04:16,  8.57s/it]

[I 2025-12-01 17:45:04,446] Trial 17 finished with value: 0.5600375234521576 and parameters: {'max_depth': 5, 'learning_rate': 0.014213734396075378, 'n_estimators': 672, 'subsample': 0.5423007322095029, 'colsample_bytree': 0.9216643759406007, 'min_child_weight': 1, 'gamma': 4.710194874409396, 'reg_alpha': 3.079951207877738, 'reg_lambda': 1.3058723612863737e-07, 'max_delta_step': 3}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  42%|████▏     | 21/50 [04:37<03:21,  6.94s/it]

[I 2025-12-01 17:45:07,603] Trial 22 pruned.

Best trial: 10. Best value: 0.572233:  44%|████▍     | 22/50 [04:41<02:50,  6.09s/it]

[I 2025-12-01 17:45:11,716] Trial 23 pruned.

Best trial: 10. Best value: 0.572233:  46%|████▌     | 23/50 [05:07<05:21, 11.90s/it]

[I 2025-12-01 17:45:37,171] Trial 18 finished with value: 0.5126641651031895 and parameters: {'max_depth': 5, 'learning_rate': 0.01801035984532412, 'n_estimators': 728, 'subsample': 0.6329166611936627, 'colsample_bytree': 0.926706668622065, 'min_child_weight': 1, 'gamma': 4.889370956256795, 'reg_alpha': 7.744167042312609, 'reg_lambda': 1.0819260286359386e-08, 'max_delta_step': 4}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  48%|████▊     | 24/50 [05:40<07:56, 18.34s/it]

[I 2025-12-01 17:46:10,536] Trial 19 finished with value: 0.5093808630393997 and parameters: {'max_depth': 4, 'learning_rate': 0.01861089704013554, 'n_estimators': 692, 'subsample': 0.6474848653226473, 'colsample_bytree': 0.9382472086533526, 'min_child_weight': 1, 'gamma': 3.548761670884646, 'reg_alpha': 0.0003095984637457781, 'reg_lambda': 0.001979944937585704, 'max_delta_step': 4}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  50%|█████     | 25/50 [05:52<06:52, 16.49s/it]

[I 2025-12-01 17:46:22,719] Trial 24 finished with value: 0.5600375234521576 and parameters: {'max_depth': 6, 'learning_rate': 0.019241395010417845, 'n_estimators': 593, 'subsample': 0.5520511981095193, 'colsample_bytree': 0.8922566320450139, 'min_child_weight': 1, 'gamma': 4.866937619217688, 'reg_alpha': 0.3686443055599163, 'reg_lambda': 3.490756012684789e-07, 'max_delta_step': 2}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  52%|█████▏    | 26/50 [06:12<06:58, 17.46s/it]

[I 2025-12-01 17:46:42,426] Trial 25 finished with value: 0.5600375234521576 and parameters: {'max_depth': 6, 'learning_rate': 0.018241040610352262, 'n_estimators': 790, 'subsample': 0.5592355704142677, 'colsample_bytree': 0.887195073739371, 'min_child_weight': 1, 'gamma': 4.987234166071714, 'reg_alpha': 0.22024626850563153, 'reg_lambda': 2.717348554475148e-07, 'max_delta_step': 2}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  54%|█████▍    | 27/50 [06:40<07:50, 20.46s/it]

[I 2025-12-01 17:47:09,901] Trial 26 finished with value: 0.5408067542213884 and parameters: {'max_depth': 6, 'learning_rate': 0.01002541699083241, 'n_estimators': 576, 'subsample': 0.5598258041439566, 'colsample_bytree': 0.8821297699999497, 'min_child_weight': 2, 'gamma': 2.087973068269037, 'reg_alpha': 0.23641362466770832, 'reg_lambda': 2.2209905036914387e-07, 'max_delta_step': 2}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  56%|█████▌    | 28/50 [06:49<06:15, 17.05s/it]

[I 2025-12-01 17:47:18,977] Trial 30 pruned.

Best trial: 10. Best value: 0.572233:  58%|█████▊    | 29/50 [07:09<06:18, 18.01s/it]

[I 2025-12-01 17:47:39,220] Trial 27 finished with value: 0.5286116322701688 and parameters: {'max_depth': 6, 'learning_rate': 0.010007451514974331, 'n_estimators': 592, 'subsample': 0.5543826040997802, 'colsample_bytree': 0.7851567639187094, 'min_child_weight': 2, 'gamma': 2.1332367220509756, 'reg_alpha': 0.21805987946424576, 'reg_lambda': 3.3442896718393095e-07, 'max_delta_step': 2}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  60%|██████    | 30/50 [07:14<04:43, 14.17s/it]

[I 2025-12-01 17:47:44,438] Trial 32 pruned.

Best trial: 10. Best value: 0.572233:  62%|██████▏   | 31/50 [07:21<03:48, 12.05s/it]

[I 2025-12-01 17:47:51,549] Trial 33 pruned.

Best trial: 10. Best value: 0.572233:  64%|██████▍   | 32/50 [07:23<02:42,  9.05s/it]

[I 2025-12-01 17:47:53,608] Trial 28 finished with value: 0.5600375234521576 and parameters: {'max_depth': 6, 'learning_rate': 0.01056927911884263, 'n_estimators': 845, 'subsample': 0.5498564255722385, 'colsample_bytree': 0.7774049656933703, 'min_child_weight': 2, 'gamma': 4.405928653803343, 'reg_alpha': 0.0016675274363723966, 'reg_lambda': 9.198542971878407e-07, 'max_delta_step': 3}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  66%|██████▌   | 33/50 [07:31<02:28,  8.72s/it]

[I 2025-12-01 17:48:01,541] Trial 34 pruned.

Best trial: 10. Best value: 0.572233:  68%|██████▊   | 34/50 [08:04<04:16, 16.03s/it]

[I 2025-12-01 17:48:34,632] Trial 29 finished with value: 0.5408067542213884 and parameters: {'max_depth': 8, 'learning_rate': 0.01010506536838276, 'n_estimators': 1038, 'subsample': 0.5435862069482961, 'colsample_bytree': 0.7642099618461632, 'min_child_weight': 2, 'gamma': 2.0834195843741066, 'reg_alpha': 0.0012362175041864538, 'reg_lambda': 2.429178504395644e-06, 'max_delta_step': 3}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  70%|███████   | 35/50 [08:24<04:15, 17.05s/it]

[I 2025-12-01 17:48:54,054] Trial 31 finished with value: 0.5408067542213884 and parameters: {'max_depth': 5, 'learning_rate': 0.014248817530678035, 'n_estimators': 929, 'subsample': 0.6912973689044145, 'colsample_bytree': 0.7723559142934306, 'min_child_weight': 2, 'gamma': 4.383426720040439, 'reg_alpha': 0.0026132206272190483, 'reg_lambda': 4.8446290004643316e-05, 'max_delta_step': 1}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  72%|███████▏  | 36/50 [08:30<03:12, 13.77s/it]

[I 2025-12-01 17:49:00,179] Trial 36 finished with value: 0.5600375234521576 and parameters: {'max_depth': 5, 'learning_rate': 0.023665402209948415, 'n_estimators': 394, 'subsample': 0.5330154476046516, 'colsample_bytree': 0.8588520137546255, 'min_child_weight': 1, 'gamma': 3.384759716155653, 'reg_alpha': 1.1975005394401905, 'reg_lambda': 6.556577161065251e-06, 'max_delta_step': 3}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  74%|███████▍  | 37/50 [08:37<02:33, 11.81s/it]

[I 2025-12-01 17:49:07,423] Trial 39 pruned.

Best trial: 10. Best value: 0.572233:  76%|███████▌  | 38/50 [08:38<01:42,  8.51s/it]

[I 2025-12-01 17:49:08,240] Trial 35 finished with value: 0.5356472795497186 and parameters: {'max_depth': 5, 'learning_rate': 0.023171199585504277, 'n_estimators': 593, 'subsample': 0.5966506378676418, 'colsample_bytree': 0.8960655653746966, 'min_child_weight': 1, 'gamma': 4.532652555922069, 'reg_alpha': 1.9773832469849364, 'reg_lambda': 5.3252498074371656e-08, 'max_delta_step': 1}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  78%|███████▊  | 39/50 [09:04<02:30, 13.67s/it]

[I 2025-12-01 17:49:33,935] Trial 41 finished with value: 0.5023452157598499 and parameters: {'max_depth': 6, 'learning_rate': 0.015575879377838388, 'n_estimators': 461, 'subsample': 0.503637904510408, 'colsample_bytree': 0.9608843192553113, 'min_child_weight': 6, 'gamma': 4.108047053677531, 'reg_alpha': 0.011100548676089292, 'reg_lambda': 1.4942748466782808e-07, 'max_delta_step': 4}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  80%|████████  | 40/50 [09:14<02:06, 12.68s/it]

[I 2025-12-01 17:49:44,305] Trial 37 finished with value: 0.5408067542213884 and parameters: {'max_depth': 5, 'learning_rate': 0.023363003440490124, 'n_estimators': 520, 'subsample': 0.6170665498993992, 'colsample_bytree': 0.871660733644999, 'min_child_weight': 1, 'gamma': 4.051292380602371, 'reg_alpha': 1.1008434586347295, 'reg_lambda': 1.0559307303244043e-05, 'max_delta_step': 1}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  82%|████████▏ | 41/50 [09:23<01:42, 11.44s/it]

[I 2025-12-01 17:49:52,847] Trial 43 pruned.

Best trial: 10. Best value: 0.572233:  84%|████████▍ | 42/50 [09:27<01:14,  9.31s/it]

[I 2025-12-01 17:49:57,187] Trial 38 finished with value: 0.5651969981238274 and parameters: {'max_depth': 7, 'learning_rate': 0.022588393830521615, 'n_estimators': 420, 'subsample': 0.6176733426270061, 'colsample_bytree': 0.8596013132092446, 'min_child_weight': 1, 'gamma': 3.4940808100655474, 'reg_alpha': 1.0040303661768237, 'reg_lambda': 1.1238309615058004e-05, 'max_delta_step': 2}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  86%|████████▌ | 43/50 [09:52<01:38, 14.08s/it]

[I 2025-12-01 17:50:22,391] Trial 42 finished with value: 0.5426829268292683 and parameters: {'max_depth': 7, 'learning_rate': 0.06292353794779247, 'n_estimators': 778, 'subsample': 0.6217097415032701, 'colsample_bytree': 0.6905840969884787, 'min_child_weight': 3, 'gamma': 4.997888010506047, 'reg_alpha': 8.68175308872413e-06, 'reg_lambda': 6.763281501346471e-06, 'max_delta_step': 6}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  88%|████████▊ | 44/50 [10:16<01:42, 17.08s/it]

[I 2025-12-01 17:50:46,473] Trial 40 finished with value: 0.5722326454033771 and parameters: {'max_depth': 7, 'learning_rate': 0.01677207028086958, 'n_estimators': 788, 'subsample': 0.6199837765119738, 'colsample_bytree': 0.9624694863701724, 'min_child_weight': 1, 'gamma': 4.001668418477518, 'reg_alpha': 0.6296947089336233, 'reg_lambda': 1.1424346715776207e-07, 'max_delta_step': 4}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 10. Best value: 0.572233:  90%|█████████ | 45/50 [10:17<01:00, 12.15s/it]

[I 2025-12-01 17:50:47,107] Trial 45 finished with value: 0.5530018761726079 and parameters: {'max_depth': 7, 'learning_rate': 0.030245060555864005, 'n_estimators': 401, 'subsample': 0.6630014200619192, 'colsample_bytree': 0.8269829978762182, 'min_child_weight': 1, 'gamma': 3.150362071779137, 'reg_alpha': 0.06894801872506724, 'reg_lambda': 8.856340074828646e-07, 'max_delta_step': 2}. Best is trial 10 with value: 0.5722326454033771.

Best trial: 46. Best value: 0.584428:  92%|█████████▏| 46/50 [10:41<01:03, 15.76s/it]

[I 2025-12-01 17:51:11,315] Trial 46 finished with value: 0.5844277673545966 and parameters: {'max_depth': 9, 'learning_rate': 0.03620214742123787, 'n_estimators': 408, 'subsample': 0.580409463519065, 'colsample_bytree': 0.8328794430604384, 'min_child_weight': 1, 'gamma': 3.2509119557089803, 'reg_alpha': 0.5276156545194036, 'reg_lambda': 9.091199765461583e-07, 'max_delta_step': 2}. Best is trial 46 with value: 0.5844277673545966.

Best trial: 46. Best value: 0.584428:  94%|█████████▍| 47/50 [10:47<00:38, 12.73s/it]

[I 2025-12-01 17:51:16,944] Trial 49 pruned.

Best trial: 46. Best value: 0.584428:  96%|█████████▌| 48/50 [10:53<00:21, 10.82s/it]

[I 2025-12-01 17:51:23,334] Trial 44 finished with value: 0.5670731707317074 and parameters: {'max_depth': 6, 'learning_rate': 0.017068543009459883, 'n_estimators': 796, 'subsample': 0.5716520496390726, 'colsample_bytree': 0.9035582696241313, 'min_child_weight': 1, 'gamma': 4.877883179084295, 'reg_alpha': 0.3464564146356548, 'reg_lambda': 6.485024940785445e-07, 'max_delta_step': 2}. Best is trial 46 with value: 0.5844277673545966.

Best trial: 46. Best value: 0.584428:  98%|█████████▊| 49/50 [10:56<00:08,  8.44s/it]

[I 2025-12-01 17:51:26,218] Trial 47 finished with value: 0.5215759849906192 and parameters: {'max_depth': 9, 'learning_rate': 0.032166772165038694, 'n_estimators': 242, 'subsample': 0.6602170016648755, 'colsample_bytree': 0.8386623194009171, 'min_child_weight': 1, 'gamma': 3.056623189166511, 'reg_alpha': 0.06363485178764192, 'reg_lambda': 9.691387708560822e-07, 'max_delta_step': 5}. Best is trial 46 with value: 0.5844277673545966.

Best trial: 46. Best value: 0.584428: 100%|██████████| 50/50 [11:45<00:00, 14.10s/it]

[I 2025-12-01 17:52:14,808] Trial 48 finished with value: 0.5600375234521576 and parameters: {'max_depth': 9, 'learning_rate': 0.039894244362195415, 'n_estimators': 1488, 'subsample': 0.7347989992965863, 'colsample_bytree': 0.9425393866529712, 'min_child_weight': 2, 'gamma': 2.744161201926828, 'reg_alpha': 6.398426559194082e-05, 'reg_lambda': 0.00017241782248535103, 'max_delta_step': 5}. Best is trial 46 with value: 0.5844277673545966.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    19_1         loo       0.775000                0.716667      0.666667
1    17_1         loo       0.584428                0.707143      0.671429
2     9_1         loo       0.682609                0.633333      0.700000
3    15_1         loo       0.653659                0.614286      0.700000

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.422890          0.833333               0.6        50          64
1  0.408491          0.714286               0.7        50          67
2  0.258199          0.666667               0.6        50          63
3  0.246885          0.428571               0.8        50          66

   test_size
0         16
1         17
2         16
3         17
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    19_1         loo       0.775000                0.716667      0.666667
1    17_1         loo       0.584428                0.707143      0.671429
2     9_1         loo       0.682609                0.633333      0.700000
3    15_1         loo       0.653659                0.614286      0.700000

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.422890          0.833333               0.6        50          64
1  0.408491          0.714286               0.7        50          67
2  0.258199          0.666667               0.6        50          63
3  0.246885          0.428571               0.8        50          66

   test_size
0         16
1         17
2         16
3         17

In [1564]:

datasets = task_freq_dfs_lbd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir="xgb_lbd_hc_{CV_STRATEGY}_tasks/xgb_results_freq_lbd_hc_extended_{CV_STRATEGY}_tasks",
    split_param="emb_",
)
print(summary)

[I 2025-12-01 17:52:20,856] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 63, Test size: 16
Using Leave-One-Out CV with 63 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.632609:   2%|▏         | 1/50 [00:19<16:12, 19.84s/it]

[I 2025-12-01 17:52:40,691] Trial 1 finished with value: 0.6326086956521739 and parameters: {'max_depth': 4, 'learning_rate': 0.01065497696097756, 'n_estimators': 422, 'subsample': 0.6192603982108258, 'colsample_bytree': 0.6237109727928767, 'min_child_weight': 7, 'gamma': 0.6085319936699607, 'reg_alpha': 0.025925912152258045, 'reg_lambda': 6.576684876476011e-06, 'max_delta_step': 6}. Best is trial 1 with value: 0.6326086956521739.

Best trial: 0. Best value: 0.657609:   4%|▍         | 2/50 [00:27<10:18, 12.89s/it]

[I 2025-12-01 17:52:48,717] Trial 0 finished with value: 0.6576086956521738 and parameters: {'max_depth': 6, 'learning_rate': 0.0375259862214887, 'n_estimators': 401, 'subsample': 0.5216424730671307, 'colsample_bytree': 0.8381237313732952, 'min_child_weight': 2, 'gamma': 3.771961556513971, 'reg_alpha': 0.00021605783944104694, 'reg_lambda': 0.0004946082853854678, 'max_delta_step': 8}. Best is trial 0 with value: 0.6576086956521738.

Best trial: 0. Best value: 0.657609:   6%|▌         | 3/50 [00:40<09:56, 12.70s/it]

[I 2025-12-01 17:53:01,192] Trial 3 finished with value: 0.6326086956521739 and parameters: {'max_depth': 9, 'learning_rate': 0.04410095914147122, 'n_estimators': 854, 'subsample': 0.9525945819404193, 'colsample_bytree': 0.8426016471318545, 'min_child_weight': 8, 'gamma': 3.20861419922351, 'reg_alpha': 1.4445928117063942e-07, 'reg_lambda': 0.00739271321568975, 'max_delta_step': 5}. Best is trial 0 with value: 0.6576086956521738.

Best trial: 0. Best value: 0.657609:   8%|▊         | 4/50 [00:54<10:02, 13.09s/it]

[I 2025-12-01 17:53:14,881] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.0536464421412016, 'n_estimators': 1010, 'subsample': 0.7153194446323278, 'colsample_bytree': 0.9337850772309317, 'min_child_weight': 5, 'gamma': 3.4192891109878283, 'reg_alpha': 9.953190199648141, 'reg_lambda': 0.0027464262253750287, 'max_delta_step': 0}. Best is trial 0 with value: 0.6576086956521738.

Best trial: 0. Best value: 0.657609:  10%|█         | 5/50 [00:56<07:02,  9.39s/it]

[I 2025-12-01 17:53:17,706] Trial 4 finished with value: 0.6293478260869565 and parameters: {'max_depth': 4, 'learning_rate': 0.14206962553319605, 'n_estimators': 759, 'subsample': 0.871428425751577, 'colsample_bytree': 0.8420539885270064, 'min_child_weight': 6, 'gamma': 3.9213853704170667, 'reg_alpha': 0.019570317191178216, 'reg_lambda': 1.1221352390136966e-08, 'max_delta_step': 4}. Best is trial 0 with value: 0.6576086956521738.

Best trial: 0. Best value: 0.657609:  14%|█▍        | 7/50 [01:31<08:43, 12.17s/it]

[I 2025-12-01 17:53:52,506] Trial 5 finished with value: 0.6358695652173914 and parameters: {'max_depth': 3, 'learning_rate': 0.1394748947546244, 'n_estimators': 1216, 'subsample': 0.8416199386505868, 'colsample_bytree': 0.6566424698572453, 'min_child_weight': 2, 'gamma': 3.631775424244856, 'reg_alpha': 0.006667687226060945, 'reg_lambda': 1.4106304109181e-07, 'max_delta_step': 3}. Best is trial 0 with value: 0.6576086956521738.
[I 2025-12-01 17:53:52,617] Trial 6 finished with value: 0.6293478260869565 and parameters: {'max_depth': 7, 'learning_rate': 0.014538202379036566, 'n_estimators': 1202, 'subsample': 0.8727193998529743, 'colsample_bytree': 0.5382656772235606, 'min_child_weight': 7, 'gamma': 3.8805374414595617, 'reg_alpha': 6.606636961125278e-05, 'reg_lambda': 0.0004501701011969288, 'max_delta_step': 0}. Best is trial 0 with value: 0.6576086956521738.

Best trial: 0. Best value: 0.657609:  16%|█▌        | 8/50 [01:43<08:24, 12.00s/it]

[I 2025-12-01 17:54:04,257] Trial 7 finished with value: 0.6141304347826086 and parameters: {'max_depth': 6, 'learning_rate': 0.02651377110965348, 'n_estimators': 873, 'subsample': 0.9847368784979642, 'colsample_bytree': 0.5577986757737323, 'min_child_weight': 3, 'gamma': 3.5346820294596535, 'reg_alpha': 0.11872785052141928, 'reg_lambda': 2.084735916282394e-07, 'max_delta_step': 7}. Best is trial 0 with value: 0.6576086956521738.

Best trial: 0. Best value: 0.657609:  18%|█▊        | 9/50 [01:52<07:37, 11.15s/it]

[I 2025-12-01 17:54:13,540] Trial 10 finished with value: 0.021739130434782608 and parameters: {'max_depth': 8, 'learning_rate': 0.1070049759738878, 'n_estimators': 411, 'subsample': 0.6307852075081649, 'colsample_bytree': 0.7015466630996532, 'min_child_weight': 10, 'gamma': 2.710387986757678, 'reg_alpha': 1.474410844255937e-08, 'reg_lambda': 0.010265681919601264, 'max_delta_step': 6}. Best is trial 0 with value: 0.6576086956521738.

Best trial: 0. Best value: 0.657609:  20%|██        | 10/50 [02:08<08:29, 12.74s/it]

[I 2025-12-01 17:54:29,847] Trial 8 finished with value: 0.6391304347826088 and parameters: {'max_depth': 6, 'learning_rate': 0.021226299239592305, 'n_estimators': 1194, 'subsample': 0.9579699069348722, 'colsample_bytree': 0.7220788219295395, 'min_child_weight': 3, 'gamma': 1.0203053933706379, 'reg_alpha': 0.00019112634896239995, 'reg_lambda': 6.408031297425355e-07, 'max_delta_step': 8}. Best is trial 0 with value: 0.6576086956521738.

Best trial: 0. Best value: 0.657609:  22%|██▏       | 11/50 [02:12<06:22,  9.81s/it]

[I 2025-12-01 17:54:33,022] Trial 13 pruned.

Best trial: 0. Best value: 0.657609:  24%|██▍       | 12/50 [02:19<05:47,  9.15s/it]

[I 2025-12-01 17:54:40,646] Trial 11 pruned.

Best trial: 0. Best value: 0.657609:  26%|██▌       | 13/50 [02:25<05:00,  8.13s/it]

[I 2025-12-01 17:54:46,431] Trial 15 pruned.

Best trial: 0. Best value: 0.657609:  28%|██▊       | 14/50 [02:27<03:48,  6.36s/it]

[I 2025-12-01 17:54:48,705] Trial 12 finished with value: 0.6418478260869566 and parameters: {'max_depth': 5, 'learning_rate': 0.13556396488221112, 'n_estimators': 786, 'subsample': 0.6028492075303651, 'colsample_bytree': 0.7056057011992747, 'min_child_weight': 7, 'gamma': 2.9886602306744585, 'reg_alpha': 2.6891133667537257e-08, 'reg_lambda': 1.9195394815912585, 'max_delta_step': 3}. Best is trial 0 with value: 0.6576086956521738.

Best trial: 0. Best value: 0.657609:  30%|███       | 15/50 [02:32<03:21,  5.75s/it]

[I 2025-12-01 17:54:53,030] Trial 17 pruned.

Best trial: 0. Best value: 0.657609:  32%|███▏      | 16/50 [02:39<03:32,  6.24s/it]

[I 2025-12-01 17:55:00,403] Trial 9 finished with value: 0.6418478260869566 and parameters: {'max_depth': 8, 'learning_rate': 0.04650640201049499, 'n_estimators': 1406, 'subsample': 0.650477655654521, 'colsample_bytree': 0.9101343185614506, 'min_child_weight': 6, 'gamma': 1.8889139321842396, 'reg_alpha': 2.43680145488267, 'reg_lambda': 1.0258732949526109e-05, 'max_delta_step': 4}. Best is trial 0 with value: 0.6576086956521738.

Best trial: 0. Best value: 0.657609:  34%|███▍      | 17/50 [02:46<03:27,  6.30s/it]

[I 2025-12-01 17:55:06,859] Trial 18 finished with value: 0.620108695652174 and parameters: {'max_depth': 10, 'learning_rate': 0.2890137252446082, 'n_estimators': 204, 'subsample': 0.7022045918153883, 'colsample_bytree': 0.6245368641667987, 'min_child_weight': 1, 'gamma': 2.193576860092504, 'reg_alpha': 4.865191604030673e-08, 'reg_lambda': 0.24136305977102845, 'max_delta_step': 2}. Best is trial 0 with value: 0.6576086956521738.

Best trial: 0. Best value: 0.657609:  36%|███▌      | 18/50 [02:46<02:23,  4.49s/it]

[I 2025-12-01 17:55:07,113] Trial 14 pruned.

Best trial: 0. Best value: 0.657609:  38%|███▊      | 19/50 [02:54<02:54,  5.63s/it]

[I 2025-12-01 17:55:15,398] Trial 21 pruned.

Best trial: 0. Best value: 0.657609:  40%|████      | 20/50 [02:56<02:16,  4.55s/it]

[I 2025-12-01 17:55:17,422] Trial 20 pruned.

Best trial: 0. Best value: 0.657609:  42%|████▏     | 21/50 [03:09<03:21,  6.95s/it]

[I 2025-12-01 17:55:29,979] Trial 23 pruned.

Best trial: 0. Best value: 0.657609:  44%|████▍     | 22/50 [03:14<03:03,  6.55s/it]

[I 2025-12-01 17:55:35,593] Trial 22 pruned.

Best trial: 0. Best value: 0.657609:  46%|████▌     | 23/50 [03:21<02:54,  6.48s/it]

[I 2025-12-01 17:55:41,909] Trial 25 pruned.

Best trial: 0. Best value: 0.657609:  48%|████▊     | 24/50 [03:24<02:23,  5.51s/it]

[I 2025-12-01 17:55:45,173] Trial 26 pruned.

Best trial: 0. Best value: 0.657609:  50%|█████     | 25/50 [03:35<03:00,  7.22s/it]

[I 2025-12-01 17:55:56,369] Trial 24 pruned.

Best trial: 0. Best value: 0.657609:  52%|█████▏    | 26/50 [03:58<04:45, 11.89s/it]

[I 2025-12-01 17:56:19,159] Trial 27 finished with value: 0.6510869565217392 and parameters: {'max_depth': 5, 'learning_rate': 0.10163577628300706, 'n_estimators': 741, 'subsample': 0.5540834281262861, 'colsample_bytree': 0.8990114437207648, 'min_child_weight': 6, 'gamma': 2.991067826303195, 'reg_alpha': 0.1612802849197376, 'reg_lambda': 1.2197640126515924e-06, 'max_delta_step': 4}. Best is trial 0 with value: 0.6576086956521738.

Best trial: 0. Best value: 0.657609:  54%|█████▍    | 27/50 [04:01<03:36,  9.42s/it]

[I 2025-12-01 17:56:22,811] Trial 29 pruned.

Best trial: 0. Best value: 0.657609:  56%|█████▌    | 28/50 [04:07<03:02,  8.29s/it]

[I 2025-12-01 17:56:28,457] Trial 30 pruned.

Best trial: 28. Best value: 0.663587:  58%|█████▊    | 29/50 [04:08<02:10,  6.22s/it]

[I 2025-12-01 17:56:29,833] Trial 28 finished with value: 0.6635869565217392 and parameters: {'max_depth': 6, 'learning_rate': 0.10527472736815392, 'n_estimators': 729, 'subsample': 0.5472884655907042, 'colsample_bytree': 0.7560781894488545, 'min_child_weight': 6, 'gamma': 3.0389359064873496, 'reg_alpha': 0.20776364769339842, 'reg_lambda': 1.5161387364354214e-06, 'max_delta_step': 4}. Best is trial 28 with value: 0.6635869565217392.

Best trial: 28. Best value: 0.663587:  60%|██████    | 30/50 [04:09<01:32,  4.61s/it]

[I 2025-12-01 17:56:30,702] Trial 31 pruned.

Best trial: 28. Best value: 0.663587:  62%|██████▏   | 31/50 [04:12<01:15,  3.99s/it]

[I 2025-12-01 17:56:33,232] Trial 32 pruned.

Best trial: 28. Best value: 0.663587:  64%|██████▍   | 32/50 [04:12<00:52,  2.90s/it]

[I 2025-12-01 17:56:33,612] Trial 16 finished with value: 0.6608695652173913 and parameters: {'max_depth': 5, 'learning_rate': 0.027729605366459627, 'n_estimators': 1494, 'subsample': 0.7709217375576387, 'colsample_bytree': 0.883375912751126, 'min_child_weight': 1, 'gamma': 1.6451072294692728, 'reg_alpha': 5.22400583441914e-06, 'reg_lambda': 1.680060385384427e-05, 'max_delta_step': 10}. Best is trial 28 with value: 0.6635869565217392.

Best trial: 28. Best value: 0.663587:  66%|██████▌   | 33/50 [04:14<00:41,  2.44s/it]

[I 2025-12-01 17:56:34,968] Trial 33 pruned.

Best trial: 19. Best value: 0.67337:  68%|██████▊   | 34/50 [04:29<01:40,  6.26s/it]

[I 2025-12-01 17:56:50,137] Trial 19 finished with value: 0.6733695652173912 and parameters: {'max_depth': 10, 'learning_rate': 0.038479514752493074, 'n_estimators': 1492, 'subsample': 0.7375426421682892, 'colsample_bytree': 0.9446002830589562, 'min_child_weight': 1, 'gamma': 2.0357851600158234, 'reg_alpha': 1.871962389662024, 'reg_lambda': 5.1287265190223654e-05, 'max_delta_step': 5}. Best is trial 19 with value: 0.6733695652173912.

Best trial: 19. Best value: 0.67337:  70%|███████   | 35/50 [04:50<02:42, 10.83s/it]

[I 2025-12-01 17:57:11,650] Trial 34 finished with value: 0.6635869565217392 and parameters: {'max_depth': 7, 'learning_rate': 0.10100710517315481, 'n_estimators': 922, 'subsample': 0.5959235262822222, 'colsample_bytree': 0.8028808588317564, 'min_child_weight': 6, 'gamma': 4.1129762659809845, 'reg_alpha': 0.6973788426458095, 'reg_lambda': 4.846860203005531e-06, 'max_delta_step': 4}. Best is trial 19 with value: 0.6733695652173912.

Best trial: 19. Best value: 0.67337:  72%|███████▏  | 36/50 [04:51<01:49,  7.81s/it]

[I 2025-12-01 17:57:12,415] Trial 37 pruned.

Best trial: 19. Best value: 0.67337:  74%|███████▍  | 37/50 [05:07<02:14, 10.34s/it]

[I 2025-12-01 17:57:28,635] Trial 36 finished with value: 0.6608695652173913 and parameters: {'max_depth': 5, 'learning_rate': 0.017783553535803905, 'n_estimators': 764, 'subsample': 0.7408313745319262, 'colsample_bytree': 0.7935290263423079, 'min_child_weight': 2, 'gamma': 3.900768194267952, 'reg_alpha': 1.2400630595205913e-05, 'reg_lambda': 0.002576342156089379, 'max_delta_step': 9}. Best is trial 19 with value: 0.6733695652173912.

Best trial: 19. Best value: 0.67337:  76%|███████▌  | 38/50 [05:15<01:55,  9.64s/it]

[I 2025-12-01 17:57:36,640] Trial 38 pruned.

Best trial: 19. Best value: 0.67337:  78%|███████▊  | 39/50 [05:17<01:20,  7.31s/it]

[I 2025-12-01 17:57:38,514] Trial 35 finished with value: 0.6608695652173913 and parameters: {'max_depth': 4, 'learning_rate': 0.01874853980573655, 'n_estimators': 938, 'subsample': 0.7543871569819129, 'colsample_bytree': 0.8032744622388063, 'min_child_weight': 2, 'gamma': 0.7222344818325444, 'reg_alpha': 1.333054986386755e-05, 'reg_lambda': 2.9560034788395148e-08, 'max_delta_step': 9}. Best is trial 19 with value: 0.6733695652173912.

Best trial: 19. Best value: 0.67337:  80%|████████  | 40/50 [05:26<01:17,  7.74s/it]

[I 2025-12-01 17:57:47,263] Trial 42 pruned.

Best trial: 19. Best value: 0.67337:  82%|████████▏ | 41/50 [05:54<02:03, 13.70s/it]

[I 2025-12-01 17:58:14,861] Trial 43 pruned.

Best trial: 19. Best value: 0.67337:  84%|████████▍ | 42/50 [06:02<01:37, 12.22s/it]

[I 2025-12-01 17:58:23,644] Trial 39 finished with value: 0.6701086956521739 and parameters: {'max_depth': 7, 'learning_rate': 0.021339884969593142, 'n_estimators': 922, 'subsample': 0.8281073548923702, 'colsample_bytree': 0.8553889589341771, 'min_child_weight': 1, 'gamma': 0.587765558577354, 'reg_alpha': 8.066018701107872, 'reg_lambda': 2.131693159093231e-06, 'max_delta_step': 5}. Best is trial 19 with value: 0.6733695652173912.

Best trial: 19. Best value: 0.67337:  86%|████████▌ | 43/50 [06:36<02:09, 18.56s/it]

[I 2025-12-01 17:58:56,989] Trial 41 finished with value: 0.6483695652173913 and parameters: {'max_depth': 10, 'learning_rate': 0.011328846622721014, 'n_estimators': 926, 'subsample': 0.8110054335584655, 'colsample_bytree': 0.8467621353619913, 'min_child_weight': 1, 'gamma': 4.357446150313047, 'reg_alpha': 0.4530546092095469, 'reg_lambda': 3.635441506008026e-05, 'max_delta_step': 5}. Best is trial 19 with value: 0.6733695652173912.

Best trial: 19. Best value: 0.67337:  88%|████████▊ | 44/50 [06:46<01:36, 16.16s/it]

[I 2025-12-01 17:59:07,551] Trial 40 finished with value: 0.6701086956521739 and parameters: {'max_depth': 10, 'learning_rate': 0.0109936795299506, 'n_estimators': 1112, 'subsample': 0.831622445132187, 'colsample_bytree': 0.8579766739368062, 'min_child_weight': 1, 'gamma': 0.6859753255232035, 'reg_alpha': 7.658764940911935, 'reg_lambda': 4.245785067999066e-06, 'max_delta_step': 5}. Best is trial 19 with value: 0.6733695652173912.

Best trial: 19. Best value: 0.67337:  90%|█████████ | 45/50 [06:55<01:10, 14.06s/it]

[I 2025-12-01 17:59:16,707] Trial 46 pruned.

Best trial: 19. Best value: 0.67337:  92%|█████████▏| 46/50 [07:11<00:57, 14.46s/it]

[I 2025-12-01 17:59:32,094] Trial 47 pruned.

Best trial: 19. Best value: 0.67337:  94%|█████████▍| 47/50 [07:15<00:34, 11.53s/it]

[I 2025-12-01 17:59:36,804] Trial 44 finished with value: 0.6608695652173913 and parameters: {'max_depth': 4, 'learning_rate': 0.01364516876153536, 'n_estimators': 832, 'subsample': 0.7775232680235932, 'colsample_bytree': 0.7359545486220671, 'min_child_weight': 1, 'gamma': 0.7022425772247225, 'reg_alpha': 4.987460066381746e-07, 'reg_lambda': 4.650835324457668e-08, 'max_delta_step': 10}. Best is trial 19 with value: 0.6733695652173912.

Best trial: 19. Best value: 0.67337:  96%|█████████▌| 48/50 [07:25<00:21, 10.99s/it]

[I 2025-12-01 17:59:46,538] Trial 48 pruned.

Best trial: 19. Best value: 0.67337:  98%|█████████▊| 49/50 [07:25<00:07,  7.79s/it]

[I 2025-12-01 17:59:46,846] Trial 45 finished with value: 0.6701086956521739 and parameters: {'max_depth': 7, 'learning_rate': 0.011774029557642965, 'n_estimators': 913, 'subsample': 0.8154713121874698, 'colsample_bytree': 0.848709469991058, 'min_child_weight': 1, 'gamma': 0.16296695793759497, 'reg_alpha': 8.772268837304127, 'reg_lambda': 6.880948180593203e-06, 'max_delta_step': 6}. Best is trial 19 with value: 0.6733695652173912.

Best trial: 19. Best value: 0.67337: 100%|██████████| 50/50 [08:20<00:00, 10.02s/it]

[I 2025-12-01 18:00:41,749] Trial 49 finished with value: 0.6483695652173913 and parameters: {'max_depth': 7, 'learning_rate': 0.010462124641585413, 'n_estimators': 867, 'subsample': 0.9128346411032817, 'colsample_bytree': 0.8287416680580886, 'min_child_weight': 2, 'gamma': 0.6502836066849164, 'reg_alpha': 3.2270452413782484, 'reg_lambda': 3.181398678886212e-07, 'max_delta_step': 4}. Best is trial 19 with value: 0.6733695652173912.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 18:00:47,474] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 66, Test size: 17
Using Leave-One-Out CV with 66 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.5:   2%|▏         | 1/50 [00:12<10:00, 12.25s/it]

[I 2025-12-01 18:00:59,718] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.11873382656172143, 'n_estimators': 207, 'subsample': 0.5374996232704052, 'colsample_bytree': 0.7920173643290951, 'min_child_weight': 9, 'gamma': 0.09191196471592278, 'reg_alpha': 3.447707499395297e-08, 'reg_lambda': 0.0025170568261234697, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   4%|▍         | 2/50 [00:20<07:58,  9.98s/it]

[I 2025-12-01 18:01:08,104] Trial 3 finished with value: 0.3795121951219512 and parameters: {'max_depth': 7, 'learning_rate': 0.022080860087479375, 'n_estimators': 322, 'subsample': 0.9249215545795133, 'colsample_bytree': 0.5894307173359915, 'min_child_weight': 9, 'gamma': 0.7155797963626903, 'reg_alpha': 0.0007889711980504004, 'reg_lambda': 1.0306841565050125e-08, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   6%|▌         | 3/50 [00:39<11:03, 14.12s/it]

[I 2025-12-01 18:01:27,151] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.01736545219943456, 'n_estimators': 853, 'subsample': 0.8813433720002224, 'colsample_bytree': 0.7684166036468736, 'min_child_weight': 10, 'gamma': 0.043108975780023484, 'reg_alpha': 0.03236769727756702, 'reg_lambda': 4.344693792613735, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   8%|▊         | 4/50 [00:45<08:10, 10.67s/it]

[I 2025-12-01 18:01:32,526] Trial 0 finished with value: 0.37170731707317073 and parameters: {'max_depth': 5, 'learning_rate': 0.02983285526669971, 'n_estimators': 849, 'subsample': 0.880413737265002, 'colsample_bytree': 0.5893353518299407, 'min_child_weight': 7, 'gamma': 3.680041265754868, 'reg_alpha': 0.010136302701444907, 'reg_lambda': 0.5120169070378067, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  10%|█         | 5/50 [01:16<13:38, 18.20s/it]

[I 2025-12-01 18:02:04,086] Trial 7 finished with value: 0.37609756097560976 and parameters: {'max_depth': 6, 'learning_rate': 0.08534735999540655, 'n_estimators': 660, 'subsample': 0.7609786383150954, 'colsample_bytree': 0.5802596831894835, 'min_child_weight': 6, 'gamma': 2.547862102115949, 'reg_alpha': 1.2816353517624212e-05, 'reg_lambda': 0.0017148989143454928, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 4. Best value: 0.501463:  12%|█▏        | 6/50 [01:18<09:11, 12.53s/it]

[I 2025-12-01 18:02:05,594] Trial 4 finished with value: 0.5014634146341463 and parameters: {'max_depth': 7, 'learning_rate': 0.06522539563420729, 'n_estimators': 1166, 'subsample': 0.9150637228133975, 'colsample_bytree': 0.7259829500560537, 'min_child_weight': 3, 'gamma': 1.12744483044589, 'reg_alpha': 7.777607067266663e-05, 'reg_lambda': 1.593412268662271e-06, 'max_delta_step': 3}. Best is trial 4 with value: 0.5014634146341463.

Best trial: 4. Best value: 0.501463:  14%|█▍        | 7/50 [01:34<09:58, 13.93s/it]

[I 2025-12-01 18:02:22,419] Trial 6 finished with value: 0.3960975609756098 and parameters: {'max_depth': 3, 'learning_rate': 0.04224582886471688, 'n_estimators': 1177, 'subsample': 0.9747016833432278, 'colsample_bytree': 0.7056733864943154, 'min_child_weight': 8, 'gamma': 0.5770162407961582, 'reg_alpha': 0.009313829790306842, 'reg_lambda': 0.00011062004825703282, 'max_delta_step': 0}. Best is trial 4 with value: 0.5014634146341463.

Best trial: 4. Best value: 0.501463:  16%|█▌        | 8/50 [01:45<09:00, 12.86s/it]

[I 2025-12-01 18:02:32,983] Trial 8 finished with value: 0.4648780487804878 and parameters: {'max_depth': 9, 'learning_rate': 0.011207606474102443, 'n_estimators': 212, 'subsample': 0.7568864749244522, 'colsample_bytree': 0.7002826710755244, 'min_child_weight': 2, 'gamma': 4.621901035199151, 'reg_alpha': 2.5283315892819673, 'reg_lambda': 0.013014946471624326, 'max_delta_step': 9}. Best is trial 4 with value: 0.5014634146341463.

Best trial: 4. Best value: 0.501463:  18%|█▊        | 9/50 [01:54<07:54, 11.58s/it]

[I 2025-12-01 18:02:41,756] Trial 9 finished with value: 0.40390243902439027 and parameters: {'max_depth': 9, 'learning_rate': 0.14592757967334047, 'n_estimators': 890, 'subsample': 0.9387112969159002, 'colsample_bytree': 0.5801071556332756, 'min_child_weight': 9, 'gamma': 4.707905544257768, 'reg_alpha': 1.0158512729161129e-05, 'reg_lambda': 1.8497787623056e-07, 'max_delta_step': 0}. Best is trial 4 with value: 0.5014634146341463.

Best trial: 5. Best value: 0.521463:  20%|██        | 10/50 [02:14<09:32, 14.31s/it]

[I 2025-12-01 18:03:02,173] Trial 5 finished with value: 0.5214634146341464 and parameters: {'max_depth': 9, 'learning_rate': 0.01939144958226401, 'n_estimators': 1446, 'subsample': 0.6286469244831592, 'colsample_bytree': 0.8181327500399043, 'min_child_weight': 1, 'gamma': 3.972687107399553, 'reg_alpha': 4.448189770874408e-06, 'reg_lambda': 2.1325853002632345e-08, 'max_delta_step': 10}. Best is trial 5 with value: 0.5214634146341464.

Best trial: 5. Best value: 0.521463:  22%|██▏       | 11/50 [02:17<06:56, 10.68s/it]

[I 2025-12-01 18:03:04,631] Trial 11 finished with value: 0.4146341463414634 and parameters: {'max_depth': 6, 'learning_rate': 0.13415774304833192, 'n_estimators': 721, 'subsample': 0.5755911335820818, 'colsample_bytree': 0.7378052027542935, 'min_child_weight': 8, 'gamma': 3.0810650600925937, 'reg_alpha': 0.00012362145277120036, 'reg_lambda': 7.528386848895875e-05, 'max_delta_step': 9}. Best is trial 5 with value: 0.5214634146341464.

Best trial: 5. Best value: 0.521463:  24%|██▍       | 12/50 [02:26<06:25, 10.14s/it]

[I 2025-12-01 18:03:13,535] Trial 10 finished with value: 0.4448780487804878 and parameters: {'max_depth': 5, 'learning_rate': 0.024097523307661534, 'n_estimators': 933, 'subsample': 0.8074702765060043, 'colsample_bytree': 0.6236786243174521, 'min_child_weight': 5, 'gamma': 4.362072236945329, 'reg_alpha': 0.0008867155045629599, 'reg_lambda': 4.151613483643874e-06, 'max_delta_step': 0}. Best is trial 5 with value: 0.5214634146341464.

Best trial: 12. Best value: 0.561463:  26%|██▌       | 13/50 [02:51<09:02, 14.67s/it]

[I 2025-12-01 18:03:38,629] Trial 12 finished with value: 0.5614634146341464 and parameters: {'max_depth': 5, 'learning_rate': 0.07867801012207448, 'n_estimators': 1035, 'subsample': 0.8824196935512159, 'colsample_bytree': 0.6565907746766585, 'min_child_weight': 4, 'gamma': 4.368195836170465, 'reg_alpha': 1.2629347342454689e-06, 'reg_lambda': 9.392425705993876e-07, 'max_delta_step': 8}. Best is trial 12 with value: 0.5614634146341464.

Best trial: 12. Best value: 0.561463:  28%|██▊       | 14/50 [03:47<16:18, 27.18s/it]

[I 2025-12-01 18:04:34,720] Trial 13 finished with value: 0.4370731707317073 and parameters: {'max_depth': 10, 'learning_rate': 0.010694651647216362, 'n_estimators': 1496, 'subsample': 0.5403003355191065, 'colsample_bytree': 0.9616134067572593, 'min_child_weight': 4, 'gamma': 3.102323298863361, 'reg_alpha': 9.107635650341195e-08, 'reg_lambda': 2.41773029103453e-05, 'max_delta_step': 5}. Best is trial 12 with value: 0.5614634146341464.

Best trial: 12. Best value: 0.561463:  30%|███       | 15/50 [03:51<11:50, 20.31s/it]

[I 2025-12-01 18:04:39,106] Trial 14 finished with value: 0.5258536585365854 and parameters: {'max_depth': 10, 'learning_rate': 0.05883916896128173, 'n_estimators': 1499, 'subsample': 0.6229560938244306, 'colsample_bytree': 0.9142473172314904, 'min_child_weight': 1, 'gamma': 1.4440005554314457, 'reg_alpha': 2.1832058154150467e-07, 'reg_lambda': 9.082405339744049e-07, 'max_delta_step': 4}. Best is trial 12 with value: 0.5614634146341464.

Best trial: 12. Best value: 0.561463:  32%|███▏      | 16/50 [04:00<09:32, 16.84s/it]

[I 2025-12-01 18:04:47,882] Trial 15 finished with value: 0.5336585365853659 and parameters: {'max_depth': 10, 'learning_rate': 0.061282369380372535, 'n_estimators': 1491, 'subsample': 0.6329351969348862, 'colsample_bytree': 0.9293565517694757, 'min_child_weight': 1, 'gamma': 1.5610822609596997, 'reg_alpha': 1.1169112960931999e-07, 'reg_lambda': 5.556440920231527e-07, 'max_delta_step': 3}. Best is trial 12 with value: 0.5614634146341464.

Best trial: 12. Best value: 0.561463:  34%|███▍      | 17/50 [04:01<06:43, 12.23s/it]

[I 2025-12-01 18:04:49,399] Trial 18 pruned.

Best trial: 12. Best value: 0.561463:  36%|███▌      | 18/50 [04:22<07:49, 14.67s/it]

[I 2025-12-01 18:05:09,752] Trial 16 finished with value: 0.4770731707317073 and parameters: {'max_depth': 10, 'learning_rate': 0.24094390031149862, 'n_estimators': 1473, 'subsample': 0.6447123533524225, 'colsample_bytree': 0.8968763738305334, 'min_child_weight': 1, 'gamma': 3.862483225018985, 'reg_alpha': 8.330987158269558e-08, 'reg_lambda': 2.3349609563146366e-08, 'max_delta_step': 6}. Best is trial 12 with value: 0.5614634146341464.

Best trial: 20. Best value: 0.573659:  38%|███▊      | 19/50 [04:59<11:03, 21.39s/it]

[I 2025-12-01 18:05:46,784] Trial 20 finished with value: 0.5736585365853658 and parameters: {'max_depth': 3, 'learning_rate': 0.22836101127014777, 'n_estimators': 1304, 'subsample': 0.6942661326303011, 'colsample_bytree': 0.5052455435588847, 'min_child_weight': 3, 'gamma': 2.056599118314795, 'reg_alpha': 1.1032937261083637e-08, 'reg_lambda': 9.228988467886912e-06, 'max_delta_step': 3}. Best is trial 20 with value: 0.5736585365853658.

Best trial: 20. Best value: 0.573659:  40%|████      | 20/50 [04:59<07:32, 15.08s/it]

[I 2025-12-01 18:05:47,178] Trial 19 finished with value: 0.5136585365853659 and parameters: {'max_depth': 8, 'learning_rate': 0.2739194331711, 'n_estimators': 1252, 'subsample': 0.68082471078555, 'colsample_bytree': 0.866934175548466, 'min_child_weight': 3, 'gamma': 1.7187026379024453, 'reg_alpha': 9.423427928559442e-07, 'reg_lambda': 2.4554952682974405e-07, 'max_delta_step': 6}. Best is trial 20 with value: 0.5736585365853658.

Best trial: 20. Best value: 0.573659:  42%|████▏     | 21/50 [05:21<08:16, 17.11s/it]

[I 2025-12-01 18:06:08,996] Trial 21 finished with value: 0.5092682926829268 and parameters: {'max_depth': 3, 'learning_rate': 0.04129306916914268, 'n_estimators': 1063, 'subsample': 0.6960379366920553, 'colsample_bytree': 0.5060686549111608, 'min_child_weight': 3, 'gamma': 1.9534200744213794, 'reg_alpha': 1.2502523251557643e-08, 'reg_lambda': 1.1312109641203058e-05, 'max_delta_step': 2}. Best is trial 20 with value: 0.5736585365853658.

Best trial: 17. Best value: 0.593659:  44%|████▍     | 22/50 [05:23<05:49, 12.49s/it]

[I 2025-12-01 18:06:10,738] Trial 17 finished with value: 0.5936585365853658 and parameters: {'max_depth': 8, 'learning_rate': 0.2841501515334172, 'n_estimators': 1426, 'subsample': 0.646291576713802, 'colsample_bytree': 0.8537589990658099, 'min_child_weight': 1, 'gamma': 3.9126074989287556, 'reg_alpha': 7.036485103719416e-07, 'reg_lambda': 1.7680648412288567e-08, 'max_delta_step': 6}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  46%|████▌     | 23/50 [05:51<07:48, 17.35s/it]

[I 2025-12-01 18:06:39,427] Trial 23 finished with value: 0.44926829268292684 and parameters: {'max_depth': 3, 'learning_rate': 0.1803872702983465, 'n_estimators': 1022, 'subsample': 0.8358233304428948, 'colsample_bytree': 0.5192585877876028, 'min_child_weight': 5, 'gamma': 2.964086894852504, 'reg_alpha': 1.4695186656642179e-08, 'reg_lambda': 3.036387150238486e-05, 'max_delta_step': 2}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  48%|████▊     | 24/50 [05:52<05:22, 12.39s/it]

[I 2025-12-01 18:06:40,245] Trial 22 finished with value: 0.49365853658536585 and parameters: {'max_depth': 3, 'learning_rate': 0.16086721830735712, 'n_estimators': 1020, 'subsample': 0.80167993106892, 'colsample_bytree': 0.5089015743094921, 'min_child_weight': 4, 'gamma': 2.4466414500151257, 'reg_alpha': 1.2182616367435008e-06, 'reg_lambda': 1.0231697417501766e-05, 'max_delta_step': 2}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  50%|█████     | 25/50 [06:31<08:26, 20.25s/it]

[I 2025-12-01 18:07:18,825] Trial 24 finished with value: 0.5136585365853659 and parameters: {'max_depth': 4, 'learning_rate': 0.08874302786219891, 'n_estimators': 1358, 'subsample': 0.8222795925216483, 'colsample_bytree': 0.5051755557775238, 'min_child_weight': 4, 'gamma': 2.3693425276688727, 'reg_alpha': 1.2192046050805118e-08, 'reg_lambda': 6.002336962059078e-06, 'max_delta_step': 3}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  52%|█████▏    | 26/50 [06:33<05:52, 14.70s/it]

[I 2025-12-01 18:07:20,585] Trial 25 finished with value: 0.4848780487804878 and parameters: {'max_depth': 4, 'learning_rate': 0.18715774823957687, 'n_estimators': 1360, 'subsample': 0.8171979898663905, 'colsample_bytree': 0.650376053837768, 'min_child_weight': 4, 'gamma': 2.625225159764894, 'reg_alpha': 1.7844789582218698e-06, 'reg_lambda': 9.291124594765922e-08, 'max_delta_step': 4}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  54%|█████▍    | 27/50 [06:56<06:35, 17.18s/it]

[I 2025-12-01 18:07:43,533] Trial 26 finished with value: 0.5214634146341464 and parameters: {'max_depth': 4, 'learning_rate': 0.19287758355618878, 'n_estimators': 1356, 'subsample': 0.7159988259539456, 'colsample_bytree': 0.667947718401141, 'min_child_weight': 4, 'gamma': 2.335098865943099, 'reg_alpha': 1.464522604808749e-06, 'reg_lambda': 7.730846096768985e-08, 'max_delta_step': 7}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  56%|█████▌    | 28/50 [07:09<05:52, 16.02s/it]

[I 2025-12-01 18:07:56,855] Trial 27 finished with value: 0.5136585365853659 and parameters: {'max_depth': 4, 'learning_rate': 0.0831984300164429, 'n_estimators': 1344, 'subsample': 0.7109663781941932, 'colsample_bytree': 0.6591439337376324, 'min_child_weight': 2, 'gamma': 3.483240594881951, 'reg_alpha': 2.575512126265873e-06, 'reg_lambda': 6.959782910283719e-08, 'max_delta_step': 7}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  58%|█████▊    | 29/50 [07:17<04:48, 13.74s/it]

[I 2025-12-01 18:08:05,283] Trial 31 pruned.

Best trial: 17. Best value: 0.593659:  60%|██████    | 30/50 [07:39<05:22, 16.11s/it]

[I 2025-12-01 18:08:26,907] Trial 28 finished with value: 0.5336585365853659 and parameters: {'max_depth': 4, 'learning_rate': 0.2192702494156644, 'n_estimators': 1335, 'subsample': 0.7223291749385388, 'colsample_bytree': 0.6575401115926295, 'min_child_weight': 2, 'gamma': 3.566831942472101, 'reg_alpha': 2.2423713861401667e-06, 'reg_lambda': 7.598470419220235e-08, 'max_delta_step': 7}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  62%|██████▏   | 31/50 [07:42<03:51, 12.16s/it]

[I 2025-12-01 18:08:29,853] Trial 29 finished with value: 0.5414634146341464 and parameters: {'max_depth': 8, 'learning_rate': 0.21796208648003843, 'n_estimators': 1342, 'subsample': 0.6954556836559348, 'colsample_bytree': 0.6653913309058492, 'min_child_weight': 2, 'gamma': 4.982872913753597, 'reg_alpha': 3.0760977661619606e-05, 'reg_lambda': 0.0003869988874800194, 'max_delta_step': 7}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  64%|██████▍   | 32/50 [07:44<02:46,  9.28s/it]

[I 2025-12-01 18:08:32,409] Trial 33 pruned.

Best trial: 17. Best value: 0.593659:  66%|██████▌   | 33/50 [07:52<02:27,  8.69s/it]

[I 2025-12-01 18:08:39,740] Trial 34 pruned.

Best trial: 17. Best value: 0.593659:  68%|██████▊   | 34/50 [07:54<01:49,  6.84s/it]

[I 2025-12-01 18:08:42,251] Trial 35 pruned.

Best trial: 17. Best value: 0.593659:  70%|███████   | 35/50 [08:02<01:46,  7.08s/it]

[I 2025-12-01 18:08:49,899] Trial 30 finished with value: 0.4970731707317073 and parameters: {'max_depth': 8, 'learning_rate': 0.10243012285930395, 'n_estimators': 1145, 'subsample': 0.7269975891790341, 'colsample_bytree': 0.8203477070755733, 'min_child_weight': 2, 'gamma': 3.484594094948399, 'reg_alpha': 1.8570899779564587e-05, 'reg_lambda': 0.0005485122925455881, 'max_delta_step': 5}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  72%|███████▏  | 36/50 [08:03<01:14,  5.31s/it]

[I 2025-12-01 18:08:51,070] Trial 36 pruned.

Best trial: 17. Best value: 0.593659:  74%|███████▍  | 37/50 [08:19<01:51,  8.60s/it]

[I 2025-12-01 18:09:07,351] Trial 32 finished with value: 0.3726829268292683 and parameters: {'max_depth': 6, 'learning_rate': 0.10793264798419828, 'n_estimators': 1254, 'subsample': 0.8714076900130575, 'colsample_bytree': 0.864037958745536, 'min_child_weight': 6, 'gamma': 3.5089664882836145, 'reg_alpha': 3.4756428090732204e-07, 'reg_lambda': 0.05193761605737062, 'max_delta_step': 8}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  76%|███████▌  | 38/50 [08:30<01:49,  9.13s/it]

[I 2025-12-01 18:09:17,736] Trial 38 finished with value: 0.4770731707317073 and parameters: {'max_depth': 5, 'learning_rate': 0.22188239565829698, 'n_estimators': 497, 'subsample': 0.8544205143761875, 'colsample_bytree': 0.7716150032786805, 'min_child_weight': 5, 'gamma': 4.960890936745421, 'reg_alpha': 0.00047247562340324085, 'reg_lambda': 0.00794307957307044, 'max_delta_step': 4}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  78%|███████▊  | 39/50 [08:32<01:16,  6.96s/it]

[I 2025-12-01 18:09:19,623] Trial 39 finished with value: 0.4892682926829268 and parameters: {'max_depth': 5, 'learning_rate': 0.1568875292026129, 'n_estimators': 523, 'subsample': 0.7727789072784239, 'colsample_bytree': 0.7650986831280332, 'min_child_weight': 5, 'gamma': 4.091450669525252, 'reg_alpha': 0.00022562264850322421, 'reg_lambda': 0.006682446596761605, 'max_delta_step': 6}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  80%|████████  | 40/50 [08:41<01:17,  7.70s/it]

[I 2025-12-01 18:09:29,047] Trial 41 pruned.

Best trial: 17. Best value: 0.593659:  82%|████████▏ | 41/50 [08:44<00:55,  6.18s/it]

[I 2025-12-01 18:09:31,678] Trial 42 pruned.

Best trial: 17. Best value: 0.593659:  84%|████████▍ | 42/50 [08:50<00:50,  6.26s/it]

[I 2025-12-01 18:09:38,137] Trial 40 finished with value: 0.47268292682926827 and parameters: {'max_depth': 5, 'learning_rate': 0.13814059706438225, 'n_estimators': 549, 'subsample': 0.780412339264009, 'colsample_bytree': 0.7597182056293144, 'min_child_weight': 5, 'gamma': 4.992298393346645, 'reg_alpha': 4.3549978163070514e-08, 'reg_lambda': 1.096344576191293, 'max_delta_step': 6}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  86%|████████▌ | 43/50 [08:54<00:39,  5.60s/it]

[I 2025-12-01 18:09:42,197] Trial 43 pruned.

Best trial: 17. Best value: 0.593659:  88%|████████▊ | 44/50 [08:58<00:30,  5.00s/it]

[I 2025-12-01 18:09:45,797] Trial 37 finished with value: 0.5536585365853659 and parameters: {'max_depth': 5, 'learning_rate': 0.21718744767722017, 'n_estimators': 1103, 'subsample': 0.8614402525711864, 'colsample_bytree': 0.6147540296332241, 'min_child_weight': 2, 'gamma': 4.941484349192061, 'reg_alpha': 0.0007789906344734764, 'reg_lambda': 0.001529749736694431, 'max_delta_step': 6}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  90%|█████████ | 45/50 [10:03<01:55, 23.02s/it]

[I 2025-12-01 18:10:50,871] Trial 47 finished with value: 0.4604878048780488 and parameters: {'max_depth': 6, 'learning_rate': 0.24782391486407587, 'n_estimators': 1086, 'subsample': 0.9389956494769067, 'colsample_bytree': 0.7197446043238048, 'min_child_weight': 1, 'gamma': 4.40848256126603, 'reg_alpha': 0.001713102794245169, 'reg_lambda': 0.0011943540183784556, 'max_delta_step': 5}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  92%|█████████▏| 46/50 [10:07<01:09, 17.49s/it]

[I 2025-12-01 18:10:55,452] Trial 46 finished with value: 0.44926829268292684 and parameters: {'max_depth': 8, 'learning_rate': 0.050567706993500806, 'n_estimators': 1092, 'subsample': 0.6296199855517048, 'colsample_bytree': 0.9477783567143523, 'min_child_weight': 1, 'gamma': 1.0334065656507399, 'reg_alpha': 1.540055473523349e-07, 'reg_lambda': 8.689804718726476e-07, 'max_delta_step': 3}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  94%|█████████▍| 47/50 [10:15<00:43, 14.50s/it]

[I 2025-12-01 18:11:02,958] Trial 45 finished with value: 0.4980487804878049 and parameters: {'max_depth': 7, 'learning_rate': 0.052859000962111546, 'n_estimators': 1388, 'subsample': 0.6349490545557256, 'colsample_bytree': 0.9228769447982964, 'min_child_weight': 1, 'gamma': 0.8715332124858663, 'reg_alpha': 8.876736905953407e-08, 'reg_lambda': 7.790017550651702e-07, 'max_delta_step': 4}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  96%|█████████▌| 48/50 [10:23<00:24, 12.44s/it]

[I 2025-12-01 18:11:10,606] Trial 44 finished with value: 0.5770731707317074 and parameters: {'max_depth': 7, 'learning_rate': 0.06791174089453235, 'n_estimators': 1412, 'subsample': 0.9991794902919158, 'colsample_bytree': 0.9426560276302259, 'min_child_weight': 1, 'gamma': 1.0310549496079715, 'reg_alpha': 5.1057667617025845e-08, 'reg_lambda': 4.654086757203534e-07, 'max_delta_step': 3}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659:  98%|█████████▊| 49/50 [10:48<00:16, 16.19s/it]

[I 2025-12-01 18:11:35,553] Trial 49 finished with value: 0.5248780487804878 and parameters: {'max_depth': 7, 'learning_rate': 0.19137262836086302, 'n_estimators': 960, 'subsample': 0.8820882348992996, 'colsample_bytree': 0.59492373639846, 'min_child_weight': 2, 'gamma': 4.199648282741814, 'reg_alpha': 6.111622788352366e-05, 'reg_lambda': 3.5661958803250624e-05, 'max_delta_step': 7}. Best is trial 17 with value: 0.5936585365853658.

Best trial: 17. Best value: 0.593659: 100%|██████████| 50/50 [10:54<00:00, 13.09s/it]

[I 2025-12-01 18:11:41,835] Trial 48 finished with value: 0.4770731707317073 and parameters: {'max_depth': 7, 'learning_rate': 0.014308588608286531, 'n_estimators': 926, 'subsample': 0.9144518999271207, 'colsample_bytree': 0.5951349582783806, 'min_child_weight': 2, 'gamma': 3.7514146278740084, 'reg_alpha': 6.321900399241831e-05, 'reg_lambda': 2.7492817014527837e-06, 'max_delta_step': 7}. Best is trial 17 with value: 0.5936585365853658.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 18:11:46,029] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 67, Test size: 17
Using Leave-One-Out CV with 67 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.5:   2%|▏         | 1/50 [00:28<23:16, 28.49s/it]

[I 2025-12-01 18:12:14,504] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.048850238564642476, 'n_estimators': 566, 'subsample': 0.5737303609049718, 'colsample_bytree': 0.5451406499559162, 'min_child_weight': 8, 'gamma': 1.1608409323695712, 'reg_alpha': 0.7836839665387731, 'reg_lambda': 5.044794033470335e-07, 'max_delta_step': 0}. Best is trial 3 with value: 0.5.

Best trial: 0. Best value: 0.542683:   4%|▍         | 2/50 [00:38<14:08, 17.67s/it]

[I 2025-12-01 18:12:24,596] Trial 0 finished with value: 0.5426829268292683 and parameters: {'max_depth': 9, 'learning_rate': 0.14272574047740735, 'n_estimators': 705, 'subsample': 0.9659723532729142, 'colsample_bytree': 0.8594263394321495, 'min_child_weight': 8, 'gamma': 2.6925556028766517, 'reg_alpha': 0.013362564357601765, 'reg_lambda': 0.00010420240049485877, 'max_delta_step': 8}. Best is trial 0 with value: 0.5426829268292683.

Best trial: 0. Best value: 0.542683:   6%|▌         | 3/50 [00:44<09:39, 12.33s/it]

[I 2025-12-01 18:12:30,586] Trial 2 finished with value: 0.4634146341463415 and parameters: {'max_depth': 3, 'learning_rate': 0.09357313578798941, 'n_estimators': 874, 'subsample': 0.724704083780372, 'colsample_bytree': 0.7326195715210972, 'min_child_weight': 10, 'gamma': 3.073333047315731, 'reg_alpha': 4.8953409456534945e-05, 'reg_lambda': 0.11677164972888265, 'max_delta_step': 0}. Best is trial 0 with value: 0.5426829268292683.

Best trial: 0. Best value: 0.542683:   8%|▊         | 4/50 [00:47<06:33,  8.55s/it]

[I 2025-12-01 18:12:33,348] Trial 4 finished with value: 0.5356472795497186 and parameters: {'max_depth': 7, 'learning_rate': 0.22645637828106713, 'n_estimators': 343, 'subsample': 0.9643819818615113, 'colsample_bytree': 0.8438859288614088, 'min_child_weight': 9, 'gamma': 2.8307816087417588, 'reg_alpha': 0.02241236518312366, 'reg_lambda': 1.1551858140566764e-06, 'max_delta_step': 7}. Best is trial 0 with value: 0.5426829268292683.

Best trial: 0. Best value: 0.542683:  10%|█         | 5/50 [01:04<08:41, 11.58s/it]

[I 2025-12-01 18:12:50,304] Trial 1 finished with value: 0.5164165103189493 and parameters: {'max_depth': 8, 'learning_rate': 0.10518933354330877, 'n_estimators': 1036, 'subsample': 0.8425869455573309, 'colsample_bytree': 0.9905233299503149, 'min_child_weight': 5, 'gamma': 3.7980751096622596, 'reg_alpha': 2.4922536542972177e-07, 'reg_lambda': 0.1528539940708906, 'max_delta_step': 1}. Best is trial 0 with value: 0.5426829268292683.

Best trial: 0. Best value: 0.542683:  12%|█▏        | 6/50 [01:26<11:01, 15.05s/it]

[I 2025-12-01 18:13:12,069] Trial 5 finished with value: 0.5164165103189493 and parameters: {'max_depth': 8, 'learning_rate': 0.15695156701897436, 'n_estimators': 827, 'subsample': 0.9602549177352131, 'colsample_bytree': 0.7819303878280597, 'min_child_weight': 4, 'gamma': 0.3130768340850154, 'reg_alpha': 3.676816163843674e-05, 'reg_lambda': 3.7525572163348704, 'max_delta_step': 6}. Best is trial 0 with value: 0.5426829268292683.

Best trial: 0. Best value: 0.542683:  14%|█▍        | 7/50 [01:31<08:31, 11.89s/it]

[I 2025-12-01 18:13:17,463] Trial 8 finished with value: 0.5164165103189493 and parameters: {'max_depth': 4, 'learning_rate': 0.09241656209209119, 'n_estimators': 426, 'subsample': 0.6421731023736522, 'colsample_bytree': 0.8478971029084346, 'min_child_weight': 4, 'gamma': 1.8753847080046233, 'reg_alpha': 0.0016828681520957992, 'reg_lambda': 0.0002709130010031854, 'max_delta_step': 2}. Best is trial 0 with value: 0.5426829268292683.

Best trial: 0. Best value: 0.542683:  16%|█▌        | 8/50 [01:33<06:02,  8.62s/it]

[I 2025-12-01 18:13:19,082] Trial 6 finished with value: 0.5408067542213884 and parameters: {'max_depth': 6, 'learning_rate': 0.024619979809371986, 'n_estimators': 781, 'subsample': 0.9839196115622246, 'colsample_bytree': 0.5288423771420273, 'min_child_weight': 5, 'gamma': 2.5933129801341637, 'reg_alpha': 0.0005751856230555144, 'reg_lambda': 3.688623469365491, 'max_delta_step': 10}. Best is trial 0 with value: 0.5426829268292683.

Best trial: 0. Best value: 0.542683:  18%|█▊        | 9/50 [01:41<05:45,  8.43s/it]

[I 2025-12-01 18:13:27,086] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.023321772494735674, 'n_estimators': 1164, 'subsample': 0.8771285093222595, 'colsample_bytree': 0.6152950536234857, 'min_child_weight': 10, 'gamma': 0.4152227798817415, 'reg_alpha': 1.1668135229182495, 'reg_lambda': 0.015790091130297373, 'max_delta_step': 7}. Best is trial 0 with value: 0.5426829268292683.

Best trial: 9. Best value: 0.560038:  20%|██        | 10/50 [01:43<04:24,  6.62s/it]

[I 2025-12-01 18:13:29,663] Trial 9 finished with value: 0.5600375234521576 and parameters: {'max_depth': 10, 'learning_rate': 0.16505938503365847, 'n_estimators': 315, 'subsample': 0.579745439132034, 'colsample_bytree': 0.5473514277998015, 'min_child_weight': 6, 'gamma': 4.937853816832854, 'reg_alpha': 0.9152723347089947, 'reg_lambda': 0.0007614393004531579, 'max_delta_step': 1}. Best is trial 9 with value: 0.5600375234521576.

Best trial: 9. Best value: 0.560038:  22%|██▏       | 11/50 [02:00<06:23,  9.83s/it]

[I 2025-12-01 18:13:46,778] Trial 12 finished with value: 0.5042213883677298 and parameters: {'max_depth': 10, 'learning_rate': 0.01735487098557437, 'n_estimators': 333, 'subsample': 0.6995336233493572, 'colsample_bytree': 0.7166136909667742, 'min_child_weight': 7, 'gamma': 1.5303506542221212, 'reg_alpha': 0.00019950525388771968, 'reg_lambda': 0.5238059660801774, 'max_delta_step': 5}. Best is trial 9 with value: 0.5600375234521576.

Best trial: 14. Best value: 0.596623:  24%|██▍       | 12/50 [02:16<07:17, 11.52s/it]

[I 2025-12-01 18:14:02,157] Trial 14 finished with value: 0.5966228893058161 and parameters: {'max_depth': 10, 'learning_rate': 0.2740911329478944, 'n_estimators': 202, 'subsample': 0.5145227137907293, 'colsample_bytree': 0.9938989297086792, 'min_child_weight': 2, 'gamma': 4.850381494110364, 'reg_alpha': 6.130880770423045, 'reg_lambda': 0.00011053458375240507, 'max_delta_step': 3}. Best is trial 14 with value: 0.5966228893058161.

Best trial: 14. Best value: 0.596623:  26%|██▌       | 13/50 [02:21<05:59,  9.70s/it]

[I 2025-12-01 18:14:07,663] Trial 10 finished with value: 0.5234521575984991 and parameters: {'max_depth': 7, 'learning_rate': 0.1992009116972405, 'n_estimators': 1225, 'subsample': 0.8722893366949355, 'colsample_bytree': 0.5674299316898702, 'min_child_weight': 9, 'gamma': 1.2258476596003027, 'reg_alpha': 2.5873562880558303e-06, 'reg_lambda': 1.4800213380164536e-05, 'max_delta_step': 5}. Best is trial 14 with value: 0.5966228893058161.

Best trial: 14. Best value: 0.596623:  28%|██▊       | 14/50 [02:37<06:53, 11.49s/it]

[I 2025-12-01 18:14:23,298] Trial 16 finished with value: 0.5581613508442776 and parameters: {'max_depth': 10, 'learning_rate': 0.2836458290328629, 'n_estimators': 220, 'subsample': 0.5017116048501741, 'colsample_bytree': 0.9959865479664468, 'min_child_weight': 2, 'gamma': 4.9059149321610205, 'reg_alpha': 6.950527880111122, 'reg_lambda': 1.5068828766222972e-08, 'max_delta_step': 3}. Best is trial 14 with value: 0.5966228893058161.

Best trial: 14. Best value: 0.596623:  30%|███       | 15/50 [02:43<05:44,  9.83s/it]

[I 2025-12-01 18:14:29,285] Trial 17 pruned.

Best trial: 14. Best value: 0.596623:  32%|███▏      | 16/50 [02:47<04:36,  8.13s/it]

[I 2025-12-01 18:14:33,472] Trial 11 finished with value: 0.5966228893058161 and parameters: {'max_depth': 6, 'learning_rate': 0.010325427980399395, 'n_estimators': 826, 'subsample': 0.5211737957852481, 'colsample_bytree': 0.9850838349783235, 'min_child_weight': 2, 'gamma': 4.169771412894402, 'reg_alpha': 1.370852039016137e-05, 'reg_lambda': 1.2140080312370654e-08, 'max_delta_step': 6}. Best is trial 14 with value: 0.5966228893058161.

Best trial: 14. Best value: 0.596623:  34%|███▍      | 17/50 [03:03<05:43, 10.40s/it]

[I 2025-12-01 18:14:49,142] Trial 19 pruned.

Best trial: 14. Best value: 0.596623:  36%|███▌      | 18/50 [03:03<04:00,  7.52s/it]

[I 2025-12-01 18:14:49,953] Trial 13 finished with value: 0.5581613508442776 and parameters: {'max_depth': 10, 'learning_rate': 0.2804883684639999, 'n_estimators': 1439, 'subsample': 0.5198388822547578, 'colsample_bytree': 0.6361661923036809, 'min_child_weight': 1, 'gamma': 4.744501141369008, 'reg_alpha': 7.175048619230411, 'reg_lambda': 1.654001712977721e-05, 'max_delta_step': 3}. Best is trial 14 with value: 0.5966228893058161.

Best trial: 14. Best value: 0.596623:  38%|███▊      | 19/50 [03:39<08:18, 16.08s/it]

[I 2025-12-01 18:15:25,994] Trial 21 finished with value: 0.5773921200750469 and parameters: {'max_depth': 8, 'learning_rate': 0.044641852154835376, 'n_estimators': 575, 'subsample': 0.6553816045985155, 'colsample_bytree': 0.9210369500674795, 'min_child_weight': 3, 'gamma': 4.074801320445514, 'reg_alpha': 4.496284447573224e-06, 'reg_lambda': 1.8513294679195393e-07, 'max_delta_step': 9}. Best is trial 14 with value: 0.5966228893058161.

Best trial: 14. Best value: 0.596623:  40%|████      | 20/50 [03:55<08:01, 16.06s/it]

[I 2025-12-01 18:15:42,012] Trial 15 finished with value: 0.5651969981238274 and parameters: {'max_depth': 10, 'learning_rate': 0.2951761480387501, 'n_estimators': 1487, 'subsample': 0.5119110799260467, 'colsample_bytree': 0.9953923587777704, 'min_child_weight': 1, 'gamma': 4.652430733354281, 'reg_alpha': 7.533134370174129, 'reg_lambda': 1.5595360542805442e-05, 'max_delta_step': 3}. Best is trial 14 with value: 0.5966228893058161.

Best trial: 14. Best value: 0.596623:  42%|████▏     | 21/50 [04:05<06:45, 13.97s/it]

[I 2025-12-01 18:15:51,090] Trial 18 finished with value: 0.5389305816135084 and parameters: {'max_depth': 9, 'learning_rate': 0.05187771276357912, 'n_estimators': 1456, 'subsample': 0.5956168842529288, 'colsample_bytree': 0.9327091065812098, 'min_child_weight': 3, 'gamma': 4.127439144952474, 'reg_alpha': 8.226339824060691, 'reg_lambda': 0.0029732495291496797, 'max_delta_step': 3}. Best is trial 14 with value: 0.5966228893058161.

Best trial: 14. Best value: 0.596623:  44%|████▍     | 22/50 [04:25<07:26, 15.95s/it]

[I 2025-12-01 18:16:11,659] Trial 20 finished with value: 0.5895872420262664 and parameters: {'max_depth': 8, 'learning_rate': 0.041300056632730855, 'n_estimators': 1447, 'subsample': 0.6573629011512161, 'colsample_bytree': 0.9264136625834625, 'min_child_weight': 3, 'gamma': 4.111217692149463, 'reg_alpha': 3.1760734485712714e-06, 'reg_lambda': 2.4220460859210983e-07, 'max_delta_step': 9}. Best is trial 14 with value: 0.5966228893058161.

Best trial: 14. Best value: 0.596623:  46%|████▌     | 23/50 [04:37<06:37, 14.74s/it]

[I 2025-12-01 18:16:23,562] Trial 25 pruned.

Best trial: 14. Best value: 0.596623:  48%|████▊     | 24/50 [05:02<07:40, 17.72s/it]

[I 2025-12-01 18:16:48,261] Trial 24 finished with value: 0.5530018761726079 and parameters: {'max_depth': 8, 'learning_rate': 0.010682423781666063, 'n_estimators': 585, 'subsample': 0.6589941712731947, 'colsample_bytree': 0.9121062714560259, 'min_child_weight': 3, 'gamma': 3.508205239030244, 'reg_alpha': 4.352539634337336e-06, 'reg_lambda': 1.7010023433656962e-07, 'max_delta_step': 10}. Best is trial 14 with value: 0.5966228893058161.

Best trial: 14. Best value: 0.596623:  50%|█████     | 25/50 [05:04<05:27, 13.11s/it]

[I 2025-12-01 18:16:50,592] Trial 22 finished with value: 0.5530018761726079 and parameters: {'max_depth': 5, 'learning_rate': 0.010510744968298751, 'n_estimators': 985, 'subsample': 0.7757251724517791, 'colsample_bytree': 0.9360289108664065, 'min_child_weight': 3, 'gamma': 3.3659209202630365, 'reg_alpha': 2.0223376436157078e-06, 'reg_lambda': 8.19647040369532e-06, 'max_delta_step': 5}. Best is trial 14 with value: 0.5966228893058161.

Best trial: 14. Best value: 0.596623:  52%|█████▏    | 26/50 [05:13<04:41, 11.72s/it]

[I 2025-12-01 18:16:59,080] Trial 28 pruned.

Best trial: 14. Best value: 0.596623:  54%|█████▍    | 27/50 [05:19<03:53, 10.13s/it]

[I 2025-12-01 18:17:05,522] Trial 23 finished with value: 0.5408067542213884 and parameters: {'max_depth': 5, 'learning_rate': 0.010381033716930037, 'n_estimators': 986, 'subsample': 0.7786614922119048, 'colsample_bytree': 0.9380880285468838, 'min_child_weight': 3, 'gamma': 3.6310865484650616, 'reg_alpha': 1.2160187897411292e-06, 'reg_lambda': 6.33514403759943e-08, 'max_delta_step': 5}. Best is trial 14 with value: 0.5966228893058161.

Best trial: 14. Best value: 0.596623:  56%|█████▌    | 28/50 [05:24<03:11,  8.69s/it]

[I 2025-12-01 18:17:10,829] Trial 29 pruned.

Best trial: 14. Best value: 0.596623:  58%|█████▊    | 29/50 [05:31<02:46,  7.95s/it]

[I 2025-12-01 18:17:17,050] Trial 30 pruned.

Best trial: 14. Best value: 0.596623:  60%|██████    | 30/50 [05:58<04:34, 13.74s/it]

[I 2025-12-01 18:17:44,303] Trial 27 finished with value: 0.5914634146341464 and parameters: {'max_depth': 9, 'learning_rate': 0.06724865059357271, 'n_estimators': 920, 'subsample': 0.5597421457065144, 'colsample_bytree': 0.8820056732417152, 'min_child_weight': 2, 'gamma': 4.309937307586385, 'reg_alpha': 1.2183552923648087e-07, 'reg_lambda': 1.8861785628434784e-06, 'max_delta_step': 8}. Best is trial 14 with value: 0.5966228893058161.

Best trial: 14. Best value: 0.596623:  62%|██████▏   | 31/50 [06:05<03:45, 11.84s/it]

[I 2025-12-01 18:17:51,721] Trial 33 pruned.

Best trial: 14. Best value: 0.596623:  64%|██████▍   | 32/50 [06:06<02:32,  8.46s/it]

[I 2025-12-01 18:17:52,294] Trial 26 finished with value: 0.5722326454033771 and parameters: {'max_depth': 9, 'learning_rate': 0.010442487479529038, 'n_estimators': 998, 'subsample': 0.6535140387097507, 'colsample_bytree': 0.8833660154569704, 'min_child_weight': 2, 'gamma': 3.618519577092433, 'reg_alpha': 2.25440671935881e-07, 'reg_lambda': 1.963811682121089e-06, 'max_delta_step': 8}. Best is trial 14 with value: 0.5966228893058161.

Best trial: 14. Best value: 0.596623:  66%|██████▌   | 33/50 [06:11<02:07,  7.50s/it]

[I 2025-12-01 18:17:57,551] Trial 32 finished with value: 0.5773921200750469 and parameters: {'max_depth': 9, 'learning_rate': 0.030389429709276782, 'n_estimators': 461, 'subsample': 0.555367595105925, 'colsample_bytree': 0.9623673497765737, 'min_child_weight': 2, 'gamma': 2.0469333341944833, 'reg_alpha': 1.8618222710063225e-05, 'reg_lambda': 4.6294405078637104e-05, 'max_delta_step': 8}. Best is trial 14 with value: 0.5966228893058161.

Best trial: 14. Best value: 0.596623:  68%|██████▊   | 34/50 [06:14<01:39,  6.23s/it]

[I 2025-12-01 18:18:00,804] Trial 34 pruned.

Best trial: 14. Best value: 0.596623:  70%|███████   | 35/50 [06:15<01:07,  4.49s/it]

[I 2025-12-01 18:18:01,234] Trial 31 finished with value: 0.5895872420262664 and parameters: {'max_depth': 9, 'learning_rate': 0.03810986273049405, 'n_estimators': 688, 'subsample': 0.5529225174931709, 'colsample_bytree': 0.9741440312818087, 'min_child_weight': 2, 'gamma': 2.1225325637548154, 'reg_alpha': 3.45693888067808e-05, 'reg_lambda': 0.00010109551731073619, 'max_delta_step': 8}. Best is trial 14 with value: 0.5966228893058161.

Best trial: 14. Best value: 0.596623:  72%|███████▏  | 36/50 [06:22<01:13,  5.27s/it]

[I 2025-12-01 18:18:08,337] Trial 38 pruned.

Best trial: 14. Best value: 0.596623:  74%|███████▍  | 37/50 [06:31<01:25,  6.58s/it]

[I 2025-12-01 18:18:17,958] Trial 39 pruned.

Best trial: 14. Best value: 0.596623:  76%|███████▌  | 38/50 [06:59<02:35, 12.95s/it]

[I 2025-12-01 18:18:45,779] Trial 36 finished with value: 0.5651969981238274 and parameters: {'max_depth': 8, 'learning_rate': 0.06990931867769229, 'n_estimators': 677, 'subsample': 0.6915085791026335, 'colsample_bytree': 0.8191620212661207, 'min_child_weight': 1, 'gamma': 4.182718015366694, 'reg_alpha': 1.8405328895044704e-05, 'reg_lambda': 5.340269335279437e-07, 'max_delta_step': 9}. Best is trial 14 with value: 0.5966228893058161.

Best trial: 35. Best value: 0.610694:  78%|███████▊  | 39/50 [07:03<01:52, 10.27s/it]

[I 2025-12-01 18:18:49,780] Trial 35 finished with value: 0.6106941838649156 and parameters: {'max_depth': 9, 'learning_rate': 0.03627350627945288, 'n_estimators': 697, 'subsample': 0.5474772173964376, 'colsample_bytree': 0.9630077811070352, 'min_child_weight': 1, 'gamma': 4.188664105124253, 'reg_alpha': 6.119862492627884e-05, 'reg_lambda': 5.086018447636887e-07, 'max_delta_step': 9}. Best is trial 35 with value: 0.6106941838649156.

Best trial: 35. Best value: 0.610694:  80%|████████  | 40/50 [07:04<01:13,  7.39s/it]

[I 2025-12-01 18:18:50,474] Trial 40 finished with value: 0.5286116322701688 and parameters: {'max_depth': 8, 'learning_rate': 0.07259522834750078, 'n_estimators': 779, 'subsample': 0.5297037584434428, 'colsample_bytree': 0.8267942378488775, 'min_child_weight': 6, 'gamma': 4.5987726505406945, 'reg_alpha': 8.592434133531256e-07, 'reg_lambda': 3.6934062613196497e-07, 'max_delta_step': 7}. Best is trial 35 with value: 0.6106941838649156.

Best trial: 35. Best value: 0.610694:  82%|████████▏ | 41/50 [07:11<01:05,  7.24s/it]

[I 2025-12-01 18:18:57,343] Trial 43 pruned.

Best trial: 35. Best value: 0.610694:  84%|████████▍ | 42/50 [07:30<01:26, 10.79s/it]

[I 2025-12-01 18:19:16,415] Trial 37 finished with value: 0.6106941838649156 and parameters: {'max_depth': 8, 'learning_rate': 0.0823474293492404, 'n_estimators': 1112, 'subsample': 0.6956925689175018, 'colsample_bytree': 0.8217351141217138, 'min_child_weight': 1, 'gamma': 3.940526497504464, 'reg_alpha': 4.687743717170905e-07, 'reg_lambda': 4.088582324684916e-07, 'max_delta_step': 9}. Best is trial 35 with value: 0.6106941838649156.

Best trial: 35. Best value: 0.610694:  86%|████████▌ | 43/50 [07:36<01:04,  9.29s/it]

[I 2025-12-01 18:19:22,197] Trial 41 finished with value: 0.5337711069418387 and parameters: {'max_depth': 7, 'learning_rate': 0.022693307143623227, 'n_estimators': 760, 'subsample': 0.5239939790548384, 'colsample_bytree': 0.8986018457640795, 'min_child_weight': 6, 'gamma': 4.600953674326368, 'reg_alpha': 0.02520923129349711, 'reg_lambda': 4.006611280021097e-08, 'max_delta_step': 7}. Best is trial 35 with value: 0.6106941838649156.

Best trial: 35. Best value: 0.610694:  88%|████████▊ | 44/50 [07:40<00:46,  7.68s/it]

[I 2025-12-01 18:19:26,119] Trial 42 finished with value: 0.5459662288930581 and parameters: {'max_depth': 3, 'learning_rate': 0.024253418372872728, 'n_estimators': 777, 'subsample': 0.5288166992656248, 'colsample_bytree': 0.7508964738681823, 'min_child_weight': 6, 'gamma': 4.6144188292945305, 'reg_alpha': 0.014950623079203064, 'reg_lambda': 0.0002419592675632218, 'max_delta_step': 7}. Best is trial 35 with value: 0.6106941838649156.

Best trial: 35. Best value: 0.610694:  90%|█████████ | 45/50 [07:48<00:39,  7.81s/it]

[I 2025-12-01 18:19:34,238] Trial 44 finished with value: 0.5966228893058161 and parameters: {'max_depth': 10, 'learning_rate': 0.04154567224562815, 'n_estimators': 453, 'subsample': 0.5696656740126246, 'colsample_bytree': 0.971423104219346, 'min_child_weight': 2, 'gamma': 3.8777095364613654, 'reg_alpha': 0.00047522679913695527, 'reg_lambda': 3.931668555407775e-08, 'max_delta_step': 10}. Best is trial 35 with value: 0.6106941838649156.

Best trial: 35. Best value: 0.610694:  92%|█████████▏| 46/50 [08:07<00:44, 11.14s/it]

[I 2025-12-01 18:19:53,134] Trial 48 finished with value: 0.5914634146341464 and parameters: {'max_depth': 10, 'learning_rate': 0.2182836693957067, 'n_estimators': 200, 'subsample': 0.7326601929962188, 'colsample_bytree': 0.9689481455093483, 'min_child_weight': 1, 'gamma': 3.8373828543604755, 'reg_alpha': 0.001271651213066634, 'reg_lambda': 3.729964272979642e-08, 'max_delta_step': 1}. Best is trial 35 with value: 0.6106941838649156.

Best trial: 35. Best value: 0.610694:  94%|█████████▍| 47/50 [08:12<00:28,  9.48s/it]

[I 2025-12-01 18:19:58,760] Trial 49 pruned.

Best trial: 46. Best value: 0.628049:  98%|█████████▊| 49/50 [08:44<00:11, 11.40s/it]

[I 2025-12-01 18:20:30,760] Trial 46 finished with value: 0.6280487804878049 and parameters: {'max_depth': 10, 'learning_rate': 0.10004710180998895, 'n_estimators': 1132, 'subsample': 0.5713201910108339, 'colsample_bytree': 0.8543728924415269, 'min_child_weight': 1, 'gamma': 3.80079121401842, 'reg_alpha': 4.918970534999779e-07, 'reg_lambda': 1.2428689982686547e-06, 'max_delta_step': 1}. Best is trial 46 with value: 0.6280487804878049.
[I 2025-12-01 18:20:30,874] Trial 45 finished with value: 0.6106941838649156 and parameters: {'max_depth': 10, 'learning_rate': 0.059076181983637455, 'n_estimators': 1112, 'subsample': 0.5732850130265885, 'colsample_bytree': 0.9691346191724349, 'min_child_weight': 1, 'gamma': 3.872684349442595, 'reg_alpha': 6.911309345664105e-07, 'reg_lambda': 1.5457933838147236e-06, 'max_delta_step': 10}. Best is trial 46 with value: 0.6280487804878049.

Best trial: 46. Best value: 0.628049: 100%|██████████| 50/50 [08:46<00:00, 10.54s/it]

[I 2025-12-01 18:20:32,883] Trial 47 finished with value: 0.5844277673545966 and parameters: {'max_depth': 10, 'learning_rate': 0.09669904496662896, 'n_estimators': 1118, 'subsample': 0.5682270962802427, 'colsample_bytree': 0.845505374136936, 'min_child_weight': 1, 'gamma': 3.8189600441621665, 'reg_alpha': 0.00013019650563782752, 'reg_lambda': 1.2860448089376784e-06, 'max_delta_step': 1}. Best is trial 46 with value: 0.6280487804878049.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 18:20:39,272] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 64, Test size: 16
Using Leave-One-Out CV with 64 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.7:   2%|▏         | 1/50 [00:16<13:46, 16.87s/it]

[I 2025-12-01 18:20:56,134] Trial 3 finished with value: 0.7 and parameters: {'max_depth': 5, 'learning_rate': 0.05388712651708806, 'n_estimators': 289, 'subsample': 0.9645514624089482, 'colsample_bytree': 0.7190769848548073, 'min_child_weight': 5, 'gamma': 4.47479237468911, 'reg_alpha': 7.913098719822661e-06, 'reg_lambda': 0.0020898123636813467, 'max_delta_step': 8}. Best is trial 3 with value: 0.7.

Best trial: 3. Best value: 0.7:   4%|▍         | 2/50 [00:17<06:04,  7.59s/it]

[I 2025-12-01 18:20:57,227] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.07966705696877989, 'n_estimators': 424, 'subsample': 0.9458332172105979, 'colsample_bytree': 0.7452403702997666, 'min_child_weight': 10, 'gamma': 1.8697977273181525, 'reg_alpha': 1.358680817439131e-05, 'reg_lambda': 0.17004954691750448, 'max_delta_step': 6}. Best is trial 3 with value: 0.7.

Best trial: 3. Best value: 0.7:   6%|▌         | 3/50 [00:40<11:25, 14.60s/it]

[I 2025-12-01 18:21:20,160] Trial 0 finished with value: 0.6041666666666666 and parameters: {'max_depth': 6, 'learning_rate': 0.09703251444578266, 'n_estimators': 1024, 'subsample': 0.5975749390568716, 'colsample_bytree': 0.7109871624548398, 'min_child_weight': 7, 'gamma': 0.5773332345618476, 'reg_alpha': 0.003297024850187202, 'reg_lambda': 0.12734520178056333, 'max_delta_step': 5}. Best is trial 3 with value: 0.7.

Best trial: 3. Best value: 0.7:   8%|▊         | 4/50 [00:46<08:26, 11.00s/it]

[I 2025-12-01 18:21:25,650] Trial 5 finished with value: 0.6583333333333333 and parameters: {'max_depth': 5, 'learning_rate': 0.030448493500563518, 'n_estimators': 641, 'subsample': 0.667815393515679, 'colsample_bytree': 0.8260630393453191, 'min_child_weight': 7, 'gamma': 2.3515227711570104, 'reg_alpha': 0.9428928684344785, 'reg_lambda': 0.0012794633559730976, 'max_delta_step': 10}. Best is trial 3 with value: 0.7.

Best trial: 3. Best value: 0.7:  10%|█         | 5/50 [00:58<08:28, 11.29s/it]

[I 2025-12-01 18:21:37,460] Trial 7 finished with value: 0.7 and parameters: {'max_depth': 9, 'learning_rate': 0.17244842943848915, 'n_estimators': 212, 'subsample': 0.5201141757301437, 'colsample_bytree': 0.8917371558999072, 'min_child_weight': 5, 'gamma': 2.2035921823317315, 'reg_alpha': 0.0008079096770591984, 'reg_lambda': 1.8628899913779024e-07, 'max_delta_step': 0}. Best is trial 3 with value: 0.7.

Best trial: 1. Best value: 0.720833:  12%|█▏        | 6/50 [01:05<07:21, 10.03s/it]

[I 2025-12-01 18:21:45,048] Trial 1 finished with value: 0.7208333333333333 and parameters: {'max_depth': 7, 'learning_rate': 0.01540568436053032, 'n_estimators': 547, 'subsample': 0.9391427412683737, 'colsample_bytree': 0.9578223372118556, 'min_child_weight': 2, 'gamma': 1.5496434105865924, 'reg_alpha': 0.29453394725516746, 'reg_lambda': 5.193127322655468, 'max_delta_step': 9}. Best is trial 1 with value: 0.7208333333333333.

Best trial: 4. Best value: 0.725:  14%|█▍        | 7/50 [01:23<09:02, 12.61s/it]

[I 2025-12-01 18:22:02,976] Trial 4 finished with value: 0.725 and parameters: {'max_depth': 4, 'learning_rate': 0.03879955084074784, 'n_estimators': 1419, 'subsample': 0.7840397680101104, 'colsample_bytree': 0.8213188519121234, 'min_child_weight': 3, 'gamma': 0.8011812240954719, 'reg_alpha': 1.7741375653723863e-07, 'reg_lambda': 1.686079466075274e-06, 'max_delta_step': 7}. Best is trial 4 with value: 0.725.

Best trial: 4. Best value: 0.725:  16%|█▌        | 8/50 [01:26<06:40,  9.54s/it]

[I 2025-12-01 18:22:05,929] Trial 8 finished with value: 0.6875 and parameters: {'max_depth': 9, 'learning_rate': 0.045858424883257885, 'n_estimators': 480, 'subsample': 0.7188337031951889, 'colsample_bytree': 0.6000378707710914, 'min_child_weight': 2, 'gamma': 4.689125756246253, 'reg_alpha': 4.5365523677690674e-08, 'reg_lambda': 1.547123928130712e-06, 'max_delta_step': 9}. Best is trial 4 with value: 0.725.

Best trial: 4. Best value: 0.725:  18%|█▊        | 9/50 [01:43<08:02, 11.76s/it]

[I 2025-12-01 18:22:22,572] Trial 9 finished with value: 0.6666666666666667 and parameters: {'max_depth': 10, 'learning_rate': 0.03079977411230068, 'n_estimators': 496, 'subsample': 0.5883532305996413, 'colsample_bytree': 0.5872066079494718, 'min_child_weight': 2, 'gamma': 0.9473445914945045, 'reg_alpha': 2.164829862256461, 'reg_lambda': 2.978886759354593e-06, 'max_delta_step': 8}. Best is trial 4 with value: 0.725.

Best trial: 4. Best value: 0.725:  20%|██        | 10/50 [02:16<12:16, 18.42s/it]

[I 2025-12-01 18:22:55,920] Trial 11 finished with value: 0.6333333333333333 and parameters: {'max_depth': 4, 'learning_rate': 0.06267829881155627, 'n_estimators': 1137, 'subsample': 0.9970486552572118, 'colsample_bytree': 0.7174996285343933, 'min_child_weight': 9, 'gamma': 2.1504111359974507, 'reg_alpha': 0.01283852396153797, 'reg_lambda': 0.012241158593292818, 'max_delta_step': 1}. Best is trial 4 with value: 0.725.

Best trial: 4. Best value: 0.725:  22%|██▏       | 11/50 [02:21<09:15, 14.26s/it]

[I 2025-12-01 18:23:00,726] Trial 12 pruned.

Best trial: 4. Best value: 0.725:  24%|██▍       | 12/50 [02:24<06:57, 10.97s/it]

[I 2025-12-01 18:23:04,194] Trial 6 finished with value: 0.6791666666666667 and parameters: {'max_depth': 8, 'learning_rate': 0.010299179393634504, 'n_estimators': 1415, 'subsample': 0.6119308952243239, 'colsample_bytree': 0.8655707369584605, 'min_child_weight': 2, 'gamma': 2.381635100498989, 'reg_alpha': 5.5564090507958025e-08, 'reg_lambda': 1.5381636589520536e-08, 'max_delta_step': 1}. Best is trial 4 with value: 0.725.

Best trial: 10. Best value: 0.766667:  26%|██▌       | 13/50 [02:33<06:21, 10.31s/it]

[I 2025-12-01 18:23:12,957] Trial 10 finished with value: 0.7666666666666666 and parameters: {'max_depth': 4, 'learning_rate': 0.1184712572752172, 'n_estimators': 1375, 'subsample': 0.6883412288541488, 'colsample_bytree': 0.8553530631488842, 'min_child_weight': 2, 'gamma': 2.907275059864371, 'reg_alpha': 1.1086401531477913e-05, 'reg_lambda': 0.0323655405927129, 'max_delta_step': 9}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  28%|██▊       | 14/50 [03:11<11:09, 18.59s/it]

[I 2025-12-01 18:23:50,695] Trial 13 finished with value: 0.7333333333333334 and parameters: {'max_depth': 3, 'learning_rate': 0.2969295450452791, 'n_estimators': 1470, 'subsample': 0.8112790408733856, 'colsample_bytree': 0.5070879763598959, 'min_child_weight': 4, 'gamma': 3.5437411237295553, 'reg_alpha': 1.211333149534118e-08, 'reg_lambda': 1.0326568390410876e-08, 'max_delta_step': 3}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  30%|███       | 15/50 [03:12<07:44, 13.27s/it]

[I 2025-12-01 18:23:51,633] Trial 15 finished with value: 0.725 and parameters: {'max_depth': 3, 'learning_rate': 0.0190967843702512, 'n_estimators': 795, 'subsample': 0.837884243254476, 'colsample_bytree': 0.9387058324315198, 'min_child_weight': 4, 'gamma': 0.06042966288661755, 'reg_alpha': 5.714957613688206e-06, 'reg_lambda': 5.0170103724601745e-05, 'max_delta_step': 6}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  32%|███▏      | 16/50 [03:23<07:11, 12.68s/it]

[I 2025-12-01 18:24:02,939] Trial 16 finished with value: 0.7541666666666667 and parameters: {'max_depth': 3, 'learning_rate': 0.25924185376093917, 'n_estimators': 1212, 'subsample': 0.8252940309278375, 'colsample_bytree': 0.9755059616008608, 'min_child_weight': 4, 'gamma': 3.3197289756881467, 'reg_alpha': 2.7475791526721663e-06, 'reg_lambda': 2.411813464689426e-05, 'max_delta_step': 6}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  34%|███▍      | 17/50 [03:47<08:52, 16.15s/it]

[I 2025-12-01 18:24:27,152] Trial 19 pruned.

Best trial: 10. Best value: 0.766667:  36%|███▌      | 18/50 [03:56<07:27, 13.98s/it]

[I 2025-12-01 18:24:36,079] Trial 17 finished with value: 0.7541666666666667 and parameters: {'max_depth': 3, 'learning_rate': 0.2929998288523109, 'n_estimators': 1233, 'subsample': 0.8113893314767148, 'colsample_bytree': 0.5208808983247715, 'min_child_weight': 4, 'gamma': 3.35374252594987, 'reg_alpha': 3.7628634216113657e-06, 'reg_lambda': 0.00012211920850898985, 'max_delta_step': 4}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  38%|███▊      | 19/50 [04:10<07:10, 13.89s/it]

[I 2025-12-01 18:24:49,782] Trial 18 finished with value: 0.7083333333333333 and parameters: {'max_depth': 3, 'learning_rate': 0.2567859217588018, 'n_estimators': 1196, 'subsample': 0.8512484757427167, 'colsample_bytree': 0.5038987182021483, 'min_child_weight': 1, 'gamma': 3.4647501681160304, 'reg_alpha': 6.836513566444229e-07, 'reg_lambda': 5.87980176193902e-05, 'max_delta_step': 4}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  40%|████      | 20/50 [04:19<06:13, 12.44s/it]

[I 2025-12-01 18:24:58,847] Trial 20 pruned.

Best trial: 10. Best value: 0.766667:  42%|████▏     | 21/50 [04:43<07:38, 15.81s/it]

[I 2025-12-01 18:25:22,504] Trial 14 pruned.

Best trial: 10. Best value: 0.766667:  44%|████▍     | 22/50 [04:56<07:05, 15.19s/it]

[I 2025-12-01 18:25:36,261] Trial 22 finished with value: 0.7125 and parameters: {'max_depth': 5, 'learning_rate': 0.12867448906254378, 'n_estimators': 1038, 'subsample': 0.7123879742769677, 'colsample_bytree': 0.7939474314905518, 'min_child_weight': 3, 'gamma': 4.068621140007117, 'reg_alpha': 9.385461604058432e-05, 'reg_lambda': 0.169748834265339, 'max_delta_step': 10}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  46%|████▌     | 23/50 [04:58<04:57, 11.03s/it]

[I 2025-12-01 18:25:37,559] Trial 24 pruned.

Best trial: 10. Best value: 0.766667:  48%|████▊     | 24/50 [04:59<03:31,  8.13s/it]

[I 2025-12-01 18:25:38,943] Trial 23 finished with value: 0.7 and parameters: {'max_depth': 5, 'learning_rate': 0.12586538112407905, 'n_estimators': 956, 'subsample': 0.888246082144107, 'colsample_bytree': 0.8019919770780077, 'min_child_weight': 6, 'gamma': 3.8534548066094425, 'reg_alpha': 0.00010037739592506723, 'reg_lambda': 0.3193127612968366, 'max_delta_step': 7}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  50%|█████     | 25/50 [05:09<03:34,  8.58s/it]

[I 2025-12-01 18:25:48,578] Trial 21 finished with value: 0.7 and parameters: {'max_depth': 5, 'learning_rate': 0.15211108182401367, 'n_estimators': 1023, 'subsample': 0.7265964878000132, 'colsample_bytree': 0.9112155837099549, 'min_child_weight': 1, 'gamma': 4.104751198719442, 'reg_alpha': 3.2588384522546633e-07, 'reg_lambda': 5.008405864148186, 'max_delta_step': 10}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  52%|█████▏    | 26/50 [05:10<02:32,  6.37s/it]

[I 2025-12-01 18:25:49,800] Trial 27 pruned.

Best trial: 10. Best value: 0.766667:  54%|█████▍    | 27/50 [05:20<02:49,  7.39s/it]

[I 2025-12-01 18:25:59,520] Trial 28 pruned.

Best trial: 10. Best value: 0.766667:  56%|█████▌    | 28/50 [05:22<02:06,  5.77s/it]

[I 2025-12-01 18:26:01,556] Trial 29 pruned.

Best trial: 10. Best value: 0.766667:  58%|█████▊    | 29/50 [05:30<02:13,  6.36s/it]

[I 2025-12-01 18:26:09,298] Trial 31 pruned.

Best trial: 10. Best value: 0.766667:  60%|██████    | 30/50 [06:03<04:47, 14.37s/it]

[I 2025-12-01 18:26:42,342] Trial 25 finished with value: 0.7 and parameters: {'max_depth': 4, 'learning_rate': 0.19259191034798684, 'n_estimators': 1261, 'subsample': 0.899911323912158, 'colsample_bytree': 0.6706936020809027, 'min_child_weight': 6, 'gamma': 2.903788446513226, 'reg_alpha': 1.2672284537946843e-06, 'reg_lambda': 0.00040066872386387376, 'max_delta_step': 3}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  62%|██████▏   | 31/50 [06:07<03:37, 11.43s/it]

[I 2025-12-01 18:26:46,915] Trial 26 finished with value: 0.7333333333333334 and parameters: {'max_depth': 3, 'learning_rate': 0.20955476539291445, 'n_estimators': 1308, 'subsample': 0.7663457524253275, 'colsample_bytree': 0.6682428676245238, 'min_child_weight': 3, 'gamma': 2.9324131979084687, 'reg_alpha': 1.2507419422697277e-06, 'reg_lambda': 1.4043650781370383e-05, 'max_delta_step': 5}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  64%|██████▍   | 32/50 [06:12<02:49,  9.43s/it]

[I 2025-12-01 18:26:51,668] Trial 33 pruned.

Best trial: 10. Best value: 0.766667:  66%|██████▌   | 33/50 [06:31<03:27, 12.23s/it]

[I 2025-12-01 18:27:10,447] Trial 32 finished with value: 0.7208333333333333 and parameters: {'max_depth': 6, 'learning_rate': 0.10575445074526396, 'n_estimators': 1125, 'subsample': 0.8920665617074282, 'colsample_bytree': 0.9979323453292406, 'min_child_weight': 7, 'gamma': 2.5911896516177118, 'reg_alpha': 0.005900402333017239, 'reg_lambda': 0.0028412185964394082, 'max_delta_step': 2}. Best is trial 10 with value: 0.7666666666666666.
[I 2025-12-01 18:27:10,531] Trial 30 finished with value: 0.7125 and parameters: {'max_depth': 4, 'learning_rate': 0.08986761142689591, 'n_estimators': 1310, 'subsample': 0.6635048544382107, 'colsample_bytree': 0.8540533780520786, 'min_child_weight': 5, 'gamma': 2.7375798949623187, 'reg_alpha': 2.6243176326772803e-05, 'reg_lambda': 0.018233323017818832, 'max_delta_step': 2}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  70%|███████   | 35/50 [07:24<04:44, 18.95s/it]

[I 2025-12-01 18:28:04,003] Trial 34 finished with value: 0.7333333333333334 and parameters: {'max_depth': 3, 'learning_rate': 0.29201032593695875, 'n_estimators': 1481, 'subsample': 0.8075399083281, 'colsample_bytree': 0.5368534699333833, 'min_child_weight': 4, 'gamma': 3.4801865693869356, 'reg_alpha': 1.464431962529197e-07, 'reg_lambda': 2.909733116485609e-08, 'max_delta_step': 2}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  72%|███████▏  | 36/50 [07:30<03:40, 15.72s/it]

[I 2025-12-01 18:28:09,938] Trial 35 finished with value: 0.7333333333333334 and parameters: {'max_depth': 3, 'learning_rate': 0.2791320489155877, 'n_estimators': 1482, 'subsample': 0.8194842583568246, 'colsample_bytree': 0.533938524226531, 'min_child_weight': 4, 'gamma': 3.481065887970569, 'reg_alpha': 1.1149544694688041e-07, 'reg_lambda': 1.863019544947024e-08, 'max_delta_step': 2}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  74%|███████▍  | 37/50 [07:42<03:10, 14.62s/it]

[I 2025-12-01 18:28:21,461] Trial 39 pruned.

Best trial: 10. Best value: 0.766667:  76%|███████▌  | 38/50 [07:48<02:27, 12.27s/it]

[I 2025-12-01 18:28:27,455] Trial 37 finished with value: 0.7458333333333333 and parameters: {'max_depth': 3, 'learning_rate': 0.2936116655154601, 'n_estimators': 1445, 'subsample': 0.7999801803112679, 'colsample_bytree': 0.5055572981399692, 'min_child_weight': 4, 'gamma': 3.4550105775732076, 'reg_alpha': 1.0258375054971479e-08, 'reg_lambda': 2.23017878991203e-08, 'max_delta_step': 4}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  78%|███████▊  | 39/50 [07:49<01:41,  9.22s/it]

[I 2025-12-01 18:28:28,796] Trial 36 finished with value: 0.7666666666666666 and parameters: {'max_depth': 3, 'learning_rate': 0.2949820584003772, 'n_estimators': 1485, 'subsample': 0.8034866899926938, 'colsample_bytree': 0.5123348634679081, 'min_child_weight': 4, 'gamma': 3.433970402084013, 'reg_alpha': 1.2510895075432365e-08, 'reg_lambda': 1.724332013620061e-08, 'max_delta_step': 4}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  80%|████████  | 40/50 [08:00<01:38,  9.85s/it]

[I 2025-12-01 18:28:40,215] Trial 41 pruned.

Best trial: 10. Best value: 0.766667:  82%|████████▏ | 41/50 [08:21<01:55, 12.87s/it]

[I 2025-12-01 18:29:00,523] Trial 43 pruned.

Best trial: 10. Best value: 0.766667:  84%|████████▍ | 42/50 [08:36<01:48, 13.54s/it]

[I 2025-12-01 18:29:15,680] Trial 38 finished with value: 0.7375 and parameters: {'max_depth': 3, 'learning_rate': 0.255948334625773, 'n_estimators': 1469, 'subsample': 0.8057206414738123, 'colsample_bytree': 0.5015487308763796, 'min_child_weight': 4, 'gamma': 4.343913561326437, 'reg_alpha': 1.3350764066933344e-05, 'reg_lambda': 2.9670637422180314e-07, 'max_delta_step': 8}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  86%|████████▌ | 43/50 [08:56<01:47, 15.35s/it]

[I 2025-12-01 18:29:35,334] Trial 40 finished with value: 0.7333333333333334 and parameters: {'max_depth': 7, 'learning_rate': 0.07457427748259407, 'n_estimators': 1500, 'subsample': 0.7926186853853798, 'colsample_bytree': 0.5577888495646933, 'min_child_weight': 3, 'gamma': 1.872207577906587, 'reg_alpha': 1.569899887390684e-05, 'reg_lambda': 1.7704265883397594e-07, 'max_delta_step': 8}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  88%|████████▊ | 44/50 [08:59<01:10, 11.80s/it]

[I 2025-12-01 18:29:38,713] Trial 42 finished with value: 0.7 and parameters: {'max_depth': 4, 'learning_rate': 0.07161968538351829, 'n_estimators': 1378, 'subsample': 0.6952513523228816, 'colsample_bytree': 0.5502866324825453, 'min_child_weight': 2, 'gamma': 1.864927856916968, 'reg_alpha': 1.1743814479524948e-05, 'reg_lambda': 2.760848736590165e-07, 'max_delta_step': 8}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667:  90%|█████████ | 45/50 [09:05<00:49,  9.97s/it]

[I 2025-12-01 18:29:44,362] Trial 45 pruned.

Best trial: 10. Best value: 0.766667:  92%|█████████▏| 46/50 [09:07<00:30,  7.65s/it]

[I 2025-12-01 18:29:46,541] Trial 46 pruned.

Best trial: 10. Best value: 0.766667:  94%|█████████▍| 47/50 [09:10<00:18,  6.29s/it]

[I 2025-12-01 18:29:49,633] Trial 47 pruned.

Best trial: 10. Best value: 0.766667:  96%|█████████▌| 48/50 [09:16<00:12,  6.22s/it]

[I 2025-12-01 18:29:55,708] Trial 49 pruned.

Best trial: 10. Best value: 0.766667:  98%|█████████▊| 49/50 [09:24<00:06,  6.63s/it]

[I 2025-12-01 18:30:03,299] Trial 44 finished with value: 0.7375 and parameters: {'max_depth': 4, 'learning_rate': 0.24124820894584534, 'n_estimators': 1488, 'subsample': 0.6890845754001753, 'colsample_bytree': 0.5474678275474585, 'min_child_weight': 4, 'gamma': 3.8545332164982407, 'reg_alpha': 3.450179061938582e-07, 'reg_lambda': 8.969804373333653e-08, 'max_delta_step': 6}. Best is trial 10 with value: 0.7666666666666666.

Best trial: 10. Best value: 0.766667: 100%|██████████| 50/50 [09:41<00:00, 11.64s/it]

[I 2025-12-01 18:30:21,160] Trial 48 finished with value: 0.7333333333333334 and parameters: {'max_depth': 3, 'learning_rate': 0.18171228080612487, 'n_estimators': 1414, 'subsample': 0.7440225612345861, 'colsample_bytree': 0.5261048805633053, 'min_child_weight': 5, 'gamma': 3.2905811357357666, 'reg_alpha': 2.5352911352169075e-07, 'reg_lambda': 1.1728056093768214e-06, 'max_delta_step': 4}. Best is trial 10 with value: 0.7666666666666666.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.673370                0.633333      0.566667
1    19_1         loo       0.766667                0.616667      0.683333
2    15_1         loo       0.593659                0.564286      0.557143
3    17_1         loo       0.628049                0.564286      0.585714

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.258199          0.666667               0.6        50          63
1  0.289414          0.333333               0.9        50          64
2  0.132410          0.428571               0.7        50          66
3  0.132410          0.428571               0.7        50          67

   test_size
0         16
1         16
2         17
3         17
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.673370                0.633333      0.566667
1    19_1         loo       0.766667                0.616667      0.683333
2    15_1         loo       0.593659                0.564286      0.557143
3    17_1         loo       0.628049                0.564286      0.585714

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.258199          0.666667               0.6        50          63
1  0.289414          0.333333               0.9        50          64
2  0.132410          0.428571               0.7        50          66
3  0.132410          0.428571               0.7        50          67

   test_size
0         16
1         16
2         17
3         17

In [1565]:

# Temporal embedings
datasets = task_temp_dfs_lbd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    #    scoring="balanced_accuracy",     # or "roc_auc"
    scoring="balanced_accuracy",      
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir="xgb_lbd_hc_{CV_STRATEGY}_tasks/xgb_results_temp_lbd_hc_extended_{CV_STRATEGY}_tasks",
    split_param="emb_",
)
print(summary)

[I 2025-12-01 18:30:28,867] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 63, Test size: 16
Using Leave-One-Out CV with 63 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.439674:   2%|▏         | 1/50 [00:24<19:54, 24.38s/it]

[I 2025-12-01 18:30:53,241] Trial 0 finished with value: 0.43967391304347825 and parameters: {'max_depth': 9, 'learning_rate': 0.2584072840981181, 'n_estimators': 442, 'subsample': 0.9460033520331401, 'colsample_bytree': 0.8739305143095246, 'min_child_weight': 6, 'gamma': 4.157311284934943, 'reg_alpha': 0.35412638473403985, 'reg_lambda': 2.557091724156759e-06, 'max_delta_step': 3}. Best is trial 0 with value: 0.43967391304347825.

Best trial: 1. Best value: 0.458152:   4%|▍         | 2/50 [00:29<10:26, 13.04s/it]

[I 2025-12-01 18:30:58,349] Trial 1 finished with value: 0.4581521739130435 and parameters: {'max_depth': 3, 'learning_rate': 0.2403600838730496, 'n_estimators': 587, 'subsample': 0.5459679087931406, 'colsample_bytree': 0.842491131300797, 'min_child_weight': 5, 'gamma': 2.5604527369821177, 'reg_alpha': 0.05410456007919026, 'reg_lambda': 4.5019411963483335e-07, 'max_delta_step': 5}. Best is trial 1 with value: 0.4581521739130435.

Best trial: 3. Best value: 0.604348:   6%|▌         | 3/50 [00:42<10:12, 13.02s/it]

[I 2025-12-01 18:31:11,340] Trial 3 finished with value: 0.6043478260869566 and parameters: {'max_depth': 5, 'learning_rate': 0.15011650843626187, 'n_estimators': 905, 'subsample': 0.7662419873305653, 'colsample_bytree': 0.9622228785762855, 'min_child_weight': 9, 'gamma': 2.119855235910737, 'reg_alpha': 1.7850738404413335e-05, 'reg_lambda': 0.00017528013418899774, 'max_delta_step': 9}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:   8%|▊         | 4/50 [01:03<12:26, 16.23s/it]

[I 2025-12-01 18:31:32,488] Trial 5 finished with value: 0.48641304347826086 and parameters: {'max_depth': 4, 'learning_rate': 0.13244628007868453, 'n_estimators': 693, 'subsample': 0.8744115525715684, 'colsample_bytree': 0.9858933151110949, 'min_child_weight': 5, 'gamma': 2.4704101772796334, 'reg_alpha': 0.02856649290147469, 'reg_lambda': 1.8528483304193084, 'max_delta_step': 9}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  10%|█         | 5/50 [01:15<10:51, 14.49s/it]

[I 2025-12-01 18:31:43,884] Trial 2 finished with value: 0.48641304347826086 and parameters: {'max_depth': 9, 'learning_rate': 0.014120519285923788, 'n_estimators': 1259, 'subsample': 0.909788373870256, 'colsample_bytree': 0.7430545479933337, 'min_child_weight': 4, 'gamma': 4.439611737302387, 'reg_alpha': 8.149851027237118e-08, 'reg_lambda': 1.7640259189133871, 'max_delta_step': 7}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  12%|█▏        | 6/50 [01:19<08:14, 11.24s/it]

[I 2025-12-01 18:31:48,837] Trial 4 finished with value: 0.5706521739130435 and parameters: {'max_depth': 10, 'learning_rate': 0.05961303086213066, 'n_estimators': 755, 'subsample': 0.7496940450698155, 'colsample_bytree': 0.7652001904179452, 'min_child_weight': 1, 'gamma': 0.7864333049305128, 'reg_alpha': 8.53533822209782e-08, 'reg_lambda': 1.6813126165028922, 'max_delta_step': 0}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  14%|█▍        | 7/50 [01:53<13:12, 18.44s/it]

[I 2025-12-01 18:32:22,082] Trial 7 finished with value: 0.5548913043478261 and parameters: {'max_depth': 10, 'learning_rate': 0.17205496167194173, 'n_estimators': 1223, 'subsample': 0.9736378849684244, 'colsample_bytree': 0.5157885554243398, 'min_child_weight': 3, 'gamma': 0.1640176153348416, 'reg_alpha': 0.11563168426554561, 'reg_lambda': 1.4664996498146114e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  16%|█▌        | 8/50 [01:58<09:55, 14.17s/it]

[I 2025-12-01 18:32:27,118] Trial 6 finished with value: 0.5614130434782609 and parameters: {'max_depth': 3, 'learning_rate': 0.014731278261747867, 'n_estimators': 1228, 'subsample': 0.6158263874776186, 'colsample_bytree': 0.9599730869861303, 'min_child_weight': 3, 'gamma': 3.3933483340179094, 'reg_alpha': 4.4769412159977925e-06, 'reg_lambda': 0.04938980570920505, 'max_delta_step': 7}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  18%|█▊        | 9/50 [02:16<10:34, 15.49s/it]

[I 2025-12-01 18:32:45,500] Trial 8 finished with value: 0.4771739130434783 and parameters: {'max_depth': 8, 'learning_rate': 0.058203461155068796, 'n_estimators': 1161, 'subsample': 0.890522197737827, 'colsample_bytree': 0.959801872768699, 'min_child_weight': 5, 'gamma': 2.901620855634093, 'reg_alpha': 5.253398510577685e-06, 'reg_lambda': 0.0004550817755559496, 'max_delta_step': 10}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  20%|██        | 10/50 [02:17<07:16, 10.92s/it]

[I 2025-12-01 18:32:46,196] Trial 9 finished with value: 0.4989130434782609 and parameters: {'max_depth': 7, 'learning_rate': 0.23142053871188822, 'n_estimators': 1061, 'subsample': 0.9016715062813434, 'colsample_bytree': 0.9314080682483428, 'min_child_weight': 4, 'gamma': 3.8020911496303, 'reg_alpha': 8.820203828459464e-05, 'reg_lambda': 3.0495887680534823e-05, 'max_delta_step': 5}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  22%|██▏       | 11/50 [02:23<06:10,  9.50s/it]

[I 2025-12-01 18:32:52,485] Trial 10 finished with value: 0.4956521739130435 and parameters: {'max_depth': 4, 'learning_rate': 0.129742597651326, 'n_estimators': 616, 'subsample': 0.739425641714309, 'colsample_bytree': 0.6616735762079844, 'min_child_weight': 7, 'gamma': 0.8218572434808352, 'reg_alpha': 0.00011681385212513003, 'reg_lambda': 3.9986723266531755e-08, 'max_delta_step': 8}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  24%|██▍       | 12/50 [02:28<05:11,  8.20s/it]

[I 2025-12-01 18:32:57,688] Trial 13 pruned.

Best trial: 3. Best value: 0.604348:  26%|██▌       | 13/50 [02:30<03:48,  6.16s/it]

[I 2025-12-01 18:32:59,177] Trial 14 pruned.

Best trial: 3. Best value: 0.604348:  28%|██▊       | 14/50 [02:34<03:22,  5.61s/it]

[I 2025-12-01 18:33:03,521] Trial 11 finished with value: 0.529891304347826 and parameters: {'max_depth': 4, 'learning_rate': 0.040745870700832874, 'n_estimators': 709, 'subsample': 0.8031448525732353, 'colsample_bytree': 0.7197570742587065, 'min_child_weight': 7, 'gamma': 3.708399294794204, 'reg_alpha': 0.22351907173655583, 'reg_lambda': 0.00011439868270809572, 'max_delta_step': 10}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  30%|███       | 15/50 [02:43<03:55,  6.73s/it]

[I 2025-12-01 18:33:12,841] Trial 12 finished with value: 0.5081521739130435 and parameters: {'max_depth': 6, 'learning_rate': 0.11406138617117416, 'n_estimators': 551, 'subsample': 0.914340622531989, 'colsample_bytree': 0.8528359111294022, 'min_child_weight': 7, 'gamma': 2.4220318627027355, 'reg_alpha': 0.0007469941610481994, 'reg_lambda': 0.25402648130628297, 'max_delta_step': 3}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  32%|███▏      | 16/50 [02:45<02:54,  5.14s/it]

[I 2025-12-01 18:33:14,290] Trial 17 pruned.

Best trial: 3. Best value: 0.604348:  34%|███▍      | 17/50 [02:49<02:40,  4.87s/it]

[I 2025-12-01 18:33:18,539] Trial 15 pruned.

Best trial: 3. Best value: 0.604348:  36%|███▌      | 18/50 [02:53<02:24,  4.51s/it]

[I 2025-12-01 18:33:22,194] Trial 16 pruned.

Best trial: 3. Best value: 0.604348:  38%|███▊      | 19/50 [02:54<01:50,  3.56s/it]

[I 2025-12-01 18:33:23,553] Trial 18 pruned.

Best trial: 3. Best value: 0.604348:  40%|████      | 20/50 [03:00<02:09,  4.31s/it]

[I 2025-12-01 18:33:29,623] Trial 21 pruned.

Best trial: 3. Best value: 0.604348:  42%|████▏     | 21/50 [03:03<01:49,  3.77s/it]

[I 2025-12-01 18:33:32,115] Trial 22 pruned.

Best trial: 3. Best value: 0.604348:  44%|████▍     | 22/50 [03:04<01:22,  2.95s/it]

[I 2025-12-01 18:33:33,156] Trial 20 pruned.

Best trial: 3. Best value: 0.604348:  46%|████▌     | 23/50 [03:04<00:57,  2.14s/it]

[I 2025-12-01 18:33:33,408] Trial 23 pruned.

Best trial: 3. Best value: 0.604348:  48%|████▊     | 24/50 [03:31<04:06,  9.47s/it]

[I 2025-12-01 18:33:59,992] Trial 19 finished with value: 0.5331521739130435 and parameters: {'max_depth': 7, 'learning_rate': 0.07791802805782883, 'n_estimators': 906, 'subsample': 0.8100862793308129, 'colsample_bytree': 0.5335783024343788, 'min_child_weight': 1, 'gamma': 0.3018360704288585, 'reg_alpha': 3.021583401243064e-07, 'reg_lambda': 0.0023183570638033017, 'max_delta_step': 2}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  50%|█████     | 25/50 [03:47<04:48, 11.55s/it]

[I 2025-12-01 18:34:16,393] Trial 24 pruned.

Best trial: 3. Best value: 0.604348:  52%|█████▏    | 26/50 [04:05<05:22, 13.43s/it]

[I 2025-12-01 18:34:34,197] Trial 28 pruned.

Best trial: 3. Best value: 0.604348:  54%|█████▍    | 27/50 [04:29<06:20, 16.56s/it]

[I 2025-12-01 18:34:58,078] Trial 25 finished with value: 0.5489130434782609 and parameters: {'max_depth': 3, 'learning_rate': 0.010407500559907568, 'n_estimators': 1404, 'subsample': 0.5871584312538445, 'colsample_bytree': 0.9842615403724436, 'min_child_weight': 3, 'gamma': 3.296164155373825, 'reg_alpha': 7.83624423838678e-06, 'reg_lambda': 0.27755514987930513, 'max_delta_step': 7}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  56%|█████▌    | 28/50 [04:46<06:07, 16.71s/it]

[I 2025-12-01 18:35:15,142] Trial 26 finished with value: 0.5364130434782608 and parameters: {'max_depth': 3, 'learning_rate': 0.010128270623298805, 'n_estimators': 1500, 'subsample': 0.5707011092424863, 'colsample_bytree': 0.9991971130353778, 'min_child_weight': 2, 'gamma': 3.214248634179649, 'reg_alpha': 5.7164491262485505e-06, 'reg_lambda': 0.13096176812682836, 'max_delta_step': 7}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  58%|█████▊    | 29/50 [05:02<05:47, 16.53s/it]

[I 2025-12-01 18:35:31,229] Trial 27 finished with value: 0.5614130434782609 and parameters: {'max_depth': 3, 'learning_rate': 0.010229678817253103, 'n_estimators': 1428, 'subsample': 0.6914019852588935, 'colsample_bytree': 0.9791481072438303, 'min_child_weight': 3, 'gamma': 3.1979327726998155, 'reg_alpha': 9.75085096600455e-06, 'reg_lambda': 0.22446256354405464, 'max_delta_step': 7}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  60%|██████    | 30/50 [05:16<05:16, 15.84s/it]

[I 2025-12-01 18:35:45,454] Trial 29 finished with value: 0.5614130434782609 and parameters: {'max_depth': 5, 'learning_rate': 0.018185881466323987, 'n_estimators': 1319, 'subsample': 0.5936393648938123, 'colsample_bytree': 0.6361460077873635, 'min_child_weight': 2, 'gamma': 3.06709246536163, 'reg_alpha': 1.0548224828745539e-07, 'reg_lambda': 0.578046697478761, 'max_delta_step': 6}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  62%|██████▏   | 31/50 [05:23<04:10, 13.16s/it]

[I 2025-12-01 18:35:52,367] Trial 33 pruned.

Best trial: 3. Best value: 0.604348:  64%|██████▍   | 32/50 [05:28<03:10, 10.61s/it]

[I 2025-12-01 18:35:57,006] Trial 32 pruned.

Best trial: 3. Best value: 0.604348:  66%|██████▌   | 33/50 [05:34<02:38,  9.30s/it]

[I 2025-12-01 18:36:03,276] Trial 30 pruned.

Best trial: 3. Best value: 0.604348:  68%|██████▊   | 34/50 [05:41<02:18,  8.64s/it]

[I 2025-12-01 18:36:10,371] Trial 31 finished with value: 0.5489130434782609 and parameters: {'max_depth': 5, 'learning_rate': 0.1749780783559988, 'n_estimators': 1305, 'subsample': 0.6852491517136612, 'colsample_bytree': 0.6960650389148147, 'min_child_weight': 2, 'gamma': 0.87866695786328, 'reg_alpha': 0.00675143528237473, 'reg_lambda': 0.015303672398966057, 'max_delta_step': 6}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  70%|███████   | 35/50 [05:55<02:33, 10.25s/it]

[I 2025-12-01 18:36:24,375] Trial 35 pruned.

Best trial: 3. Best value: 0.604348:  72%|███████▏  | 36/50 [06:06<02:24, 10.33s/it]

[I 2025-12-01 18:36:34,883] Trial 37 pruned.

Best trial: 3. Best value: 0.604348:  74%|███████▍  | 37/50 [06:15<02:09,  9.94s/it]

[I 2025-12-01 18:36:43,926] Trial 36 pruned.

Best trial: 3. Best value: 0.604348:  76%|███████▌  | 38/50 [06:29<02:13, 11.14s/it]

[I 2025-12-01 18:36:57,865] Trial 34 pruned.

Best trial: 3. Best value: 0.604348:  78%|███████▊  | 39/50 [06:51<02:38, 14.40s/it]

[I 2025-12-01 18:37:19,867] Trial 38 finished with value: 0.5489130434782609 and parameters: {'max_depth': 3, 'learning_rate': 0.013043696654507345, 'n_estimators': 785, 'subsample': 0.6306211873626733, 'colsample_bytree': 0.7706749842456314, 'min_child_weight': 3, 'gamma': 2.777559165371202, 'reg_alpha': 1.6776129213637314e-06, 'reg_lambda': 1.0298836183760174, 'max_delta_step': 4}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  80%|████████  | 40/50 [07:05<02:23, 14.38s/it]

[I 2025-12-01 18:37:34,204] Trial 39 finished with value: 0.5489130434782609 and parameters: {'max_depth': 3, 'learning_rate': 0.1765727232218931, 'n_estimators': 1199, 'subsample': 0.7168627752730137, 'colsample_bytree': 0.7815994328282325, 'min_child_weight': 3, 'gamma': 2.790833682316956, 'reg_alpha': 1.2210534938523868e-06, 'reg_lambda': 1.2060149851455695, 'max_delta_step': 4}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  82%|████████▏ | 41/50 [07:08<01:39, 11.10s/it]

[I 2025-12-01 18:37:37,660] Trial 42 pruned.

Best trial: 3. Best value: 0.604348:  84%|████████▍ | 42/50 [07:10<01:06,  8.30s/it]

[I 2025-12-01 18:37:39,419] Trial 40 finished with value: 0.567391304347826 and parameters: {'max_depth': 3, 'learning_rate': 0.17424749478604118, 'n_estimators': 1187, 'subsample': 0.6741043868989203, 'colsample_bytree': 0.9606545058921542, 'min_child_weight': 5, 'gamma': 2.061052937571116, 'reg_alpha': 0.00021149509453318214, 'reg_lambda': 0.0005528243291375409, 'max_delta_step': 4}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  86%|████████▌ | 43/50 [07:21<01:04,  9.24s/it]

[I 2025-12-01 18:37:50,843] Trial 41 finished with value: 0.5456521739130434 and parameters: {'max_depth': 3, 'learning_rate': 0.18210593469646255, 'n_estimators': 1143, 'subsample': 0.6631864250294994, 'colsample_bytree': 0.8623143428886618, 'min_child_weight': 5, 'gamma': 2.073791419128184, 'reg_alpha': 0.0003049482041867901, 'reg_lambda': 0.8710641847165421, 'max_delta_step': 4}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  88%|████████▊ | 44/50 [07:47<01:25, 14.17s/it]

[I 2025-12-01 18:38:16,520] Trial 45 pruned.

Best trial: 3. Best value: 0.604348:  90%|█████████ | 45/50 [07:48<00:50, 10.18s/it]

[I 2025-12-01 18:38:17,391] Trial 43 pruned.

Best trial: 3. Best value: 0.604348:  92%|█████████▏| 46/50 [07:58<00:39, 10.00s/it]

[I 2025-12-01 18:38:26,962] Trial 48 pruned.

Best trial: 3. Best value: 0.604348:  94%|█████████▍| 47/50 [07:59<00:22,  7.36s/it]

[I 2025-12-01 18:38:28,160] Trial 46 pruned.

Best trial: 3. Best value: 0.604348:  96%|█████████▌| 48/50 [08:15<00:19,  9.91s/it]

[I 2025-12-01 18:38:44,033] Trial 47 finished with value: 0.567391304347826 and parameters: {'max_depth': 4, 'learning_rate': 0.1432669408115785, 'n_estimators': 637, 'subsample': 0.7168284791342603, 'colsample_bytree': 0.965211472305774, 'min_child_weight': 6, 'gamma': 2.520124110048295, 'reg_alpha': 0.0008422871736717174, 'reg_lambda': 3.36857022434317e-07, 'max_delta_step': 1}. Best is trial 3 with value: 0.6043478260869566.

Best trial: 3. Best value: 0.604348:  98%|█████████▊| 49/50 [08:19<00:08,  8.30s/it]

[I 2025-12-01 18:38:48,587] Trial 49 pruned.

Best trial: 3. Best value: 0.604348: 100%|██████████| 50/50 [08:21<00:00, 10.04s/it]

[I 2025-12-01 18:38:50,719] Trial 44 pruned.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 18:38:53,234] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 66, Test size: 17
Using Leave-One-Out CV with 66 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.472683:   2%|▏         | 1/50 [00:26<21:48, 26.71s/it]

[I 2025-12-01 18:39:19,934] Trial 1 finished with value: 0.47268292682926827 and parameters: {'max_depth': 7, 'learning_rate': 0.028606865228421176, 'n_estimators': 535, 'subsample': 0.9000937640011056, 'colsample_bytree': 0.5008477740252302, 'min_child_weight': 8, 'gamma': 4.584722296876894, 'reg_alpha': 6.430834317780911e-08, 'reg_lambda': 0.00012408465906263338, 'max_delta_step': 4}. Best is trial 1 with value: 0.47268292682926827.

Best trial: 2. Best value: 0.477073:   4%|▍         | 2/50 [00:45<17:52, 22.34s/it]

[I 2025-12-01 18:39:39,220] Trial 2 finished with value: 0.4770731707317073 and parameters: {'max_depth': 3, 'learning_rate': 0.047773269927408976, 'n_estimators': 827, 'subsample': 0.9020402457385841, 'colsample_bytree': 0.8863660420956179, 'min_child_weight': 6, 'gamma': 3.0804794809013574, 'reg_alpha': 2.229268107411444e-06, 'reg_lambda': 7.728781766274092e-05, 'max_delta_step': 1}. Best is trial 2 with value: 0.4770731707317073.

Best trial: 2. Best value: 0.477073:   6%|▌         | 3/50 [01:01<15:13, 19.43s/it]

[I 2025-12-01 18:39:55,190] Trial 4 finished with value: 0.4082926829268293 and parameters: {'max_depth': 4, 'learning_rate': 0.024225808134099056, 'n_estimators': 734, 'subsample': 0.9162631176541056, 'colsample_bytree': 0.5149771094853185, 'min_child_weight': 8, 'gamma': 4.033944014816743, 'reg_alpha': 2.125722753114483, 'reg_lambda': 6.226093068502386e-06, 'max_delta_step': 3}. Best is trial 2 with value: 0.4770731707317073.

Best trial: 2. Best value: 0.477073:   8%|▊         | 4/50 [01:13<12:28, 16.28s/it]

[I 2025-12-01 18:40:06,632] Trial 3 finished with value: 0.36829268292682926 and parameters: {'max_depth': 6, 'learning_rate': 0.055970146188141785, 'n_estimators': 1289, 'subsample': 0.7059358177708233, 'colsample_bytree': 0.7973089202104, 'min_child_weight': 2, 'gamma': 1.6229493903895564, 'reg_alpha': 1.7661059740686992e-08, 'reg_lambda': 8.298508044968215e-08, 'max_delta_step': 4}. Best is trial 2 with value: 0.4770731707317073.

Best trial: 2. Best value: 0.477073:  10%|█         | 5/50 [01:25<11:02, 14.72s/it]

[I 2025-12-01 18:40:18,598] Trial 7 finished with value: 0.26 and parameters: {'max_depth': 3, 'learning_rate': 0.02621511258036657, 'n_estimators': 216, 'subsample': 0.5962776338069049, 'colsample_bytree': 0.8464749700039129, 'min_child_weight': 10, 'gamma': 1.0202236591408564, 'reg_alpha': 3.3268011435617554e-08, 'reg_lambda': 9.496810304345697e-08, 'max_delta_step': 7}. Best is trial 2 with value: 0.4770731707317073.

Best trial: 2. Best value: 0.477073:  12%|█▏        | 6/50 [01:28<07:47, 10.63s/it]

[I 2025-12-01 18:40:21,294] Trial 0 finished with value: 0.47268292682926827 and parameters: {'max_depth': 6, 'learning_rate': 0.015207781960254073, 'n_estimators': 1376, 'subsample': 0.9515855528094106, 'colsample_bytree': 0.9951022343598193, 'min_child_weight': 7, 'gamma': 0.46262147339882154, 'reg_alpha': 1.0589028235907122e-06, 'reg_lambda': 8.592964670388997e-06, 'max_delta_step': 10}. Best is trial 2 with value: 0.4770731707317073.

Best trial: 2. Best value: 0.477073:  14%|█▍        | 7/50 [01:47<09:37, 13.44s/it]

[I 2025-12-01 18:40:40,514] Trial 6 finished with value: 0.44926829268292684 and parameters: {'max_depth': 6, 'learning_rate': 0.0833705738326297, 'n_estimators': 694, 'subsample': 0.5841689944225184, 'colsample_bytree': 0.8805857241387292, 'min_child_weight': 1, 'gamma': 0.8055283954209663, 'reg_alpha': 5.915827235826363e-08, 'reg_lambda': 0.004204813421445737, 'max_delta_step': 10}. Best is trial 2 with value: 0.4770731707317073.

Best trial: 2. Best value: 0.477073:  16%|█▌        | 8/50 [01:51<07:22, 10.53s/it]

[I 2025-12-01 18:40:44,817] Trial 9 finished with value: 0.4326829268292683 and parameters: {'max_depth': 7, 'learning_rate': 0.02388236446037379, 'n_estimators': 251, 'subsample': 0.7944100267335927, 'colsample_bytree': 0.9014113942585441, 'min_child_weight': 5, 'gamma': 1.4515165917713118, 'reg_alpha': 2.1843865940653595e-05, 'reg_lambda': 0.39785088255923723, 'max_delta_step': 6}. Best is trial 2 with value: 0.4770731707317073.

Best trial: 2. Best value: 0.477073:  18%|█▊        | 9/50 [01:58<06:31,  9.54s/it]

[I 2025-12-01 18:40:52,171] Trial 8 finished with value: 0.4370731707317073 and parameters: {'max_depth': 6, 'learning_rate': 0.01581474358396675, 'n_estimators': 353, 'subsample': 0.5475588128356862, 'colsample_bytree': 0.706149457696416, 'min_child_weight': 2, 'gamma': 3.9660230973456416, 'reg_alpha': 0.002868927834058258, 'reg_lambda': 1.423016697270627, 'max_delta_step': 5}. Best is trial 2 with value: 0.4770731707317073.

Best trial: 2. Best value: 0.477073:  20%|██        | 10/50 [02:09<06:31,  9.78s/it]

[I 2025-12-01 18:41:02,501] Trial 5 finished with value: 0.3882926829268293 and parameters: {'max_depth': 4, 'learning_rate': 0.019127807062151746, 'n_estimators': 1116, 'subsample': 0.9037053660800907, 'colsample_bytree': 0.8308486582060954, 'min_child_weight': 4, 'gamma': 1.9688131706276535, 'reg_alpha': 0.1680861375431735, 'reg_lambda': 6.086370312301515, 'max_delta_step': 1}. Best is trial 2 with value: 0.4770731707317073.

Best trial: 2. Best value: 0.477073:  22%|██▏       | 11/50 [02:09<04:31,  6.95s/it]

[I 2025-12-01 18:41:03,039] Trial 11 pruned.

Best trial: 2. Best value: 0.477073:  24%|██▍       | 12/50 [02:15<04:12,  6.65s/it]

[I 2025-12-01 18:41:09,004] Trial 13 pruned.

Best trial: 2. Best value: 0.477073:  26%|██▌       | 13/50 [02:33<06:13, 10.10s/it]

[I 2025-12-01 18:41:27,037] Trial 15 pruned.

Best trial: 2. Best value: 0.477073:  28%|██▊       | 14/50 [02:38<05:06,  8.50s/it]

[I 2025-12-01 18:41:31,854] Trial 12 pruned.

Best trial: 2. Best value: 0.477073:  30%|███       | 15/50 [03:12<09:30, 16.29s/it]

[I 2025-12-01 18:42:06,186] Trial 14 finished with value: 0.4370731707317073 and parameters: {'max_depth': 9, 'learning_rate': 0.278438776279645, 'n_estimators': 1475, 'subsample': 0.985903209090725, 'colsample_bytree': 0.9886848107166621, 'min_child_weight': 6, 'gamma': 0.01099914188756801, 'reg_alpha': 1.3497509161832492e-05, 'reg_lambda': 9.555426759982178e-06, 'max_delta_step': 10}. Best is trial 2 with value: 0.4770731707317073.

Best trial: 2. Best value: 0.477073:  32%|███▏      | 16/50 [03:15<06:49, 12.04s/it]

[I 2025-12-01 18:42:08,340] Trial 10 finished with value: 0.4282926829268293 and parameters: {'max_depth': 8, 'learning_rate': 0.017748493779715574, 'n_estimators': 939, 'subsample': 0.9715662050258373, 'colsample_bytree': 0.8861634716133742, 'min_child_weight': 3, 'gamma': 0.3725267485065964, 'reg_alpha': 3.085682873814387, 'reg_lambda': 6.682564596968948e-05, 'max_delta_step': 5}. Best is trial 2 with value: 0.4770731707317073.

Best trial: 2. Best value: 0.477073:  34%|███▍      | 17/50 [03:21<05:42, 10.37s/it]

[I 2025-12-01 18:42:14,850] Trial 18 pruned.

Best trial: 2. Best value: 0.477073:  36%|███▌      | 18/50 [03:23<04:13,  7.93s/it]

[I 2025-12-01 18:42:17,088] Trial 19 pruned.

Best trial: 2. Best value: 0.477073:  38%|███▊      | 19/50 [03:37<04:58,  9.63s/it]

[I 2025-12-01 18:42:30,686] Trial 17 finished with value: 0.41707317073170735 and parameters: {'max_depth': 3, 'learning_rate': 0.01107435123941961, 'n_estimators': 793, 'subsample': 0.9903305064389918, 'colsample_bytree': 0.9519440065882239, 'min_child_weight': 6, 'gamma': 2.942156364767844, 'reg_alpha': 2.117682450136111e-06, 'reg_lambda': 2.056103028970719e-06, 'max_delta_step': 2}. Best is trial 2 with value: 0.4770731707317073.

Best trial: 2. Best value: 0.477073:  40%|████      | 20/50 [03:42<04:05,  8.20s/it]

[I 2025-12-01 18:42:35,542] Trial 21 pruned.

Best trial: 2. Best value: 0.477073:  42%|████▏     | 21/50 [03:50<03:59,  8.24s/it]

[I 2025-12-01 18:42:43,892] Trial 23 pruned.

Best trial: 20. Best value: 0.480488:  44%|████▍     | 22/50 [03:54<03:15,  6.97s/it]

[I 2025-12-01 18:42:47,901] Trial 20 finished with value: 0.4804878048780488 and parameters: {'max_depth': 5, 'learning_rate': 0.047020636658823216, 'n_estimators': 563, 'subsample': 0.8494631245358304, 'colsample_bytree': 0.9399465039596218, 'min_child_weight': 7, 'gamma': 2.4265651718537353, 'reg_alpha': 1.2922087799835807e-06, 'reg_lambda': 0.002341834747965721, 'max_delta_step': 8}. Best is trial 20 with value: 0.4804878048780488.

Best trial: 20. Best value: 0.480488:  46%|████▌     | 23/50 [04:03<03:24,  7.59s/it]

[I 2025-12-01 18:42:56,918] Trial 22 finished with value: 0.40926829268292686 and parameters: {'max_depth': 5, 'learning_rate': 0.040116779331595326, 'n_estimators': 538, 'subsample': 0.6492004063203483, 'colsample_bytree': 0.6187155436818375, 'min_child_weight': 8, 'gamma': 2.331077530422008, 'reg_alpha': 5.380121347536408e-05, 'reg_lambda': 0.001175521398251354, 'max_delta_step': 8}. Best is trial 20 with value: 0.4804878048780488.

Best trial: 20. Best value: 0.480488:  48%|████▊     | 24/50 [04:11<03:20,  7.72s/it]

[I 2025-12-01 18:43:04,957] Trial 24 finished with value: 0.45268292682926825 and parameters: {'max_depth': 7, 'learning_rate': 0.03509621534651833, 'n_estimators': 393, 'subsample': 0.871777331598796, 'colsample_bytree': 0.5220209375005749, 'min_child_weight': 8, 'gamma': 4.702683357192544, 'reg_alpha': 2.080782874015652e-07, 'reg_lambda': 0.00016950697682311384, 'max_delta_step': 4}. Best is trial 20 with value: 0.4804878048780488.

Best trial: 20. Best value: 0.480488:  50%|█████     | 25/50 [04:14<02:36,  6.26s/it]

[I 2025-12-01 18:43:07,814] Trial 26 pruned.

Best trial: 20. Best value: 0.480488:  52%|█████▏    | 26/50 [04:16<01:57,  4.88s/it]

[I 2025-12-01 18:43:09,466] Trial 16 finished with value: 0.41707317073170735 and parameters: {'max_depth': 3, 'learning_rate': 0.010499484391921018, 'n_estimators': 1494, 'subsample': 0.9916363217411904, 'colsample_bytree': 0.9744232323200048, 'min_child_weight': 6, 'gamma': 2.8885556505434407, 'reg_alpha': 3.050119413666402e-06, 'reg_lambda': 4.705703956484525e-06, 'max_delta_step': 8}. Best is trial 20 with value: 0.4804878048780488.

Best trial: 20. Best value: 0.480488:  54%|█████▍    | 27/50 [04:17<01:28,  3.86s/it]

[I 2025-12-01 18:43:10,960] Trial 27 pruned.

Best trial: 20. Best value: 0.480488:  56%|█████▌    | 28/50 [04:24<01:44,  4.73s/it]

[I 2025-12-01 18:43:17,712] Trial 25 finished with value: 0.47268292682926827 and parameters: {'max_depth': 4, 'learning_rate': 0.07416426342386699, 'n_estimators': 538, 'subsample': 0.8471265931183908, 'colsample_bytree': 0.8473484610747758, 'min_child_weight': 8, 'gamma': 3.4929415570109854, 'reg_alpha': 3.65391176034629e-07, 'reg_lambda': 0.0015584707676127236, 'max_delta_step': 9}. Best is trial 20 with value: 0.4804878048780488.

Best trial: 28. Best value: 0.517073:  58%|█████▊    | 29/50 [04:49<03:46, 10.78s/it]

[I 2025-12-01 18:43:42,596] Trial 28 finished with value: 0.5170731707317073 and parameters: {'max_depth': 4, 'learning_rate': 0.11162156806014228, 'n_estimators': 598, 'subsample': 0.7910222925877599, 'colsample_bytree': 0.8367392077412086, 'min_child_weight': 5, 'gamma': 3.568006527895322, 'reg_alpha': 0.00015387855411180517, 'reg_lambda': 0.0007429065523401742, 'max_delta_step': 9}. Best is trial 28 with value: 0.5170731707317073.

Best trial: 28. Best value: 0.517073:  60%|██████    | 30/50 [04:53<02:56,  8.84s/it]

[I 2025-12-01 18:43:46,933] Trial 32 pruned.

Best trial: 28. Best value: 0.517073:  62%|██████▏   | 31/50 [04:54<02:02,  6.45s/it]

[I 2025-12-01 18:43:47,804] Trial 29 finished with value: 0.4848780487804878 and parameters: {'max_depth': 6, 'learning_rate': 0.1359398277035837, 'n_estimators': 689, 'subsample': 0.7809568874225209, 'colsample_bytree': 0.8491543897790401, 'min_child_weight': 5, 'gamma': 3.4497165125830285, 'reg_alpha': 0.00014568462494892536, 'reg_lambda': 0.000678759206200461, 'max_delta_step': 9}. Best is trial 28 with value: 0.5170731707317073.

Best trial: 28. Best value: 0.517073:  64%|██████▍   | 32/50 [05:01<02:01,  6.74s/it]

[I 2025-12-01 18:43:55,215] Trial 33 pruned.

Best trial: 28. Best value: 0.517073:  66%|██████▌   | 33/50 [05:02<01:24,  4.95s/it]

[I 2025-12-01 18:43:55,975] Trial 34 pruned.

Best trial: 30. Best value: 0.549268:  68%|██████▊   | 34/50 [05:05<01:08,  4.30s/it]

[I 2025-12-01 18:43:58,755] Trial 30 finished with value: 0.5492682926829269 and parameters: {'max_depth': 6, 'learning_rate': 0.1261005299006758, 'n_estimators': 915, 'subsample': 0.943072949954174, 'colsample_bytree': 0.9125162822076583, 'min_child_weight': 9, 'gamma': 1.5814113328235069, 'reg_alpha': 5.486443050642634e-07, 'reg_lambda': 0.0008180370651260816, 'max_delta_step': 9}. Best is trial 30 with value: 0.5492682926829269.

Best trial: 30. Best value: 0.549268:  70%|███████   | 35/50 [05:10<01:08,  4.58s/it]

[I 2025-12-01 18:44:03,987] Trial 31 finished with value: 0.47268292682926827 and parameters: {'max_depth': 6, 'learning_rate': 0.1412788272969286, 'n_estimators': 903, 'subsample': 0.9469271992602463, 'colsample_bytree': 0.7967698650090018, 'min_child_weight': 9, 'gamma': 1.1161587555205372, 'reg_alpha': 2.126567372898988e-05, 'reg_lambda': 0.0005813879017548535, 'max_delta_step': 6}. Best is trial 30 with value: 0.5492682926829269.

Best trial: 30. Best value: 0.549268:  72%|███████▏  | 36/50 [05:14<00:59,  4.28s/it]

[I 2025-12-01 18:44:07,561] Trial 36 pruned.

Best trial: 30. Best value: 0.549268:  74%|███████▍  | 37/50 [05:21<01:08,  5.28s/it]

[I 2025-12-01 18:44:15,185] Trial 38 pruned.

Best trial: 30. Best value: 0.549268:  76%|███████▌  | 38/50 [05:38<01:45,  8.77s/it]

[I 2025-12-01 18:44:32,106] Trial 35 finished with value: 0.4848780487804878 and parameters: {'max_depth': 6, 'learning_rate': 0.18397707999233498, 'n_estimators': 674, 'subsample': 0.7527878656418875, 'colsample_bytree': 0.7913564316214703, 'min_child_weight': 5, 'gamma': 3.7258036676617245, 'reg_alpha': 0.000827047930329978, 'reg_lambda': 0.0005265397123628142, 'max_delta_step': 9}. Best is trial 30 with value: 0.5492682926829269.

Best trial: 30. Best value: 0.549268:  78%|███████▊  | 39/50 [05:39<01:09,  6.28s/it]

[I 2025-12-01 18:44:32,589] Trial 37 finished with value: 0.5082926829268293 and parameters: {'max_depth': 6, 'learning_rate': 0.20547699614671872, 'n_estimators': 658, 'subsample': 0.8095571140490118, 'colsample_bytree': 0.798238087801419, 'min_child_weight': 9, 'gamma': 1.4011882320196265, 'reg_alpha': 0.013190277869965648, 'reg_lambda': 0.05810096332156303, 'max_delta_step': 9}. Best is trial 30 with value: 0.5492682926829269.

Best trial: 30. Best value: 0.549268:  80%|████████  | 40/50 [05:45<01:03,  6.32s/it]

[I 2025-12-01 18:44:38,986] Trial 39 finished with value: 0.4682926829268293 and parameters: {'max_depth': 7, 'learning_rate': 0.18332131237915503, 'n_estimators': 609, 'subsample': 0.8779268872868349, 'colsample_bytree': 0.8692134173189242, 'min_child_weight': 9, 'gamma': 2.057492874666099, 'reg_alpha': 1.5771262455371557e-08, 'reg_lambda': 0.002037868979899099, 'max_delta_step': 10}. Best is trial 30 with value: 0.5492682926829269.

Best trial: 30. Best value: 0.549268:  82%|████████▏ | 41/50 [05:48<00:48,  5.36s/it]

[I 2025-12-01 18:44:42,095] Trial 43 pruned.

Best trial: 30. Best value: 0.549268:  84%|████████▍ | 42/50 [05:51<00:36,  4.51s/it]

[I 2025-12-01 18:44:44,637] Trial 41 pruned.

Best trial: 30. Best value: 0.549268:  86%|████████▌ | 43/50 [05:55<00:29,  4.25s/it]

[I 2025-12-01 18:44:48,264] Trial 42 pruned.

Best trial: 30. Best value: 0.549268:  88%|████████▊ | 44/50 [05:58<00:23,  3.98s/it]

[I 2025-12-01 18:44:51,626] Trial 45 pruned.

Best trial: 30. Best value: 0.549268:  90%|█████████ | 45/50 [06:02<00:20,  4.06s/it]

[I 2025-12-01 18:44:55,881] Trial 47 pruned.

Best trial: 30. Best value: 0.549268:  92%|█████████▏| 46/50 [06:03<00:11,  2.96s/it]

[I 2025-12-01 18:44:56,284] Trial 44 pruned.

Best trial: 30. Best value: 0.549268:  94%|█████████▍| 47/50 [06:05<00:08,  2.92s/it]

[I 2025-12-01 18:44:59,096] Trial 40 finished with value: 0.46146341463414636 and parameters: {'max_depth': 5, 'learning_rate': 0.10273965846100826, 'n_estimators': 600, 'subsample': 0.8770769917028863, 'colsample_bytree': 0.9322207898514909, 'min_child_weight': 3, 'gamma': 1.8858217542832139, 'reg_alpha': 6.384643521166632e-05, 'reg_lambda': 0.0019466994028308976, 'max_delta_step': 10}. Best is trial 30 with value: 0.5492682926829269.

Best trial: 30. Best value: 0.549268:  96%|█████████▌| 48/50 [06:25<00:15,  7.80s/it]

[I 2025-12-01 18:45:18,297] Trial 48 pruned.

Best trial: 30. Best value: 0.549268:  98%|█████████▊| 49/50 [06:36<00:08,  8.83s/it]

[I 2025-12-01 18:45:29,530] Trial 46 finished with value: 0.4814634146341464 and parameters: {'max_depth': 6, 'learning_rate': 0.21175294496486194, 'n_estimators': 1039, 'subsample': 0.7560115827485946, 'colsample_bytree': 0.8181760806809029, 'min_child_weight': 4, 'gamma': 0.7005509967978754, 'reg_alpha': 0.0009361413897514087, 'reg_lambda': 0.0103157281766892, 'max_delta_step': 9}. Best is trial 30 with value: 0.5492682926829269.

Best trial: 30. Best value: 0.549268: 100%|██████████| 50/50 [06:40<00:00,  8.01s/it]

[I 2025-12-01 18:45:33,633] Trial 49 finished with value: 0.5014634146341463 and parameters: {'max_depth': 7, 'learning_rate': 0.23505532095857043, 'n_estimators': 1041, 'subsample': 0.5068928314071508, 'colsample_bytree': 0.83292378432284, 'min_child_weight': 3, 'gamma': 4.860630415672814, 'reg_alpha': 8.991182682403155e-05, 'reg_lambda': 0.0004072848081180588, 'max_delta_step': 8}. Best is trial 30 with value: 0.5492682926829269.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 18:45:37,078] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 67, Test size: 17
Using Leave-One-Out CV with 67 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.64212:   2%|▏         | 1/50 [00:51<41:45, 51.14s/it]

[I 2025-12-01 18:46:28,205] Trial 2 finished with value: 0.6421200750469043 and parameters: {'max_depth': 4, 'learning_rate': 0.16120153013697475, 'n_estimators': 779, 'subsample': 0.9386464864017117, 'colsample_bytree': 0.5159509282384065, 'min_child_weight': 1, 'gamma': 2.482136041187242, 'reg_alpha': 0.03611108536207545, 'reg_lambda': 3.3190681991321956e-08, 'max_delta_step': 6}. Best is trial 2 with value: 0.6421200750469043.

Best trial: 2. Best value: 0.64212:   4%|▍         | 2/50 [01:04<22:58, 28.72s/it]

[I 2025-12-01 18:46:41,236] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.06008109568833577, 'n_estimators': 1447, 'subsample': 0.6956716046039875, 'colsample_bytree': 0.5099669074468876, 'min_child_weight': 10, 'gamma': 3.866812651450568, 'reg_alpha': 7.091422634276174, 'reg_lambda': 0.003559619546205311, 'max_delta_step': 4}. Best is trial 2 with value: 0.6421200750469043.

Best trial: 2. Best value: 0.64212:   6%|▌         | 3/50 [01:07<13:29, 17.22s/it]

[I 2025-12-01 18:46:44,774] Trial 0 finished with value: 0.6421200750469043 and parameters: {'max_depth': 5, 'learning_rate': 0.015625947847515788, 'n_estimators': 1151, 'subsample': 0.8714585686704857, 'colsample_bytree': 0.6949217623363368, 'min_child_weight': 6, 'gamma': 2.1296262944103637, 'reg_alpha': 1.702398054845145e-05, 'reg_lambda': 0.6706539451661768, 'max_delta_step': 2}. Best is trial 2 with value: 0.6421200750469043.

Best trial: 2. Best value: 0.64212:   8%|▊         | 4/50 [01:16<10:36, 13.84s/it]

[I 2025-12-01 18:46:53,440] Trial 5 finished with value: 0.5581613508442776 and parameters: {'max_depth': 6, 'learning_rate': 0.11545245974957166, 'n_estimators': 211, 'subsample': 0.6225491015620832, 'colsample_bytree': 0.8299932464065973, 'min_child_weight': 8, 'gamma': 2.865922606292786, 'reg_alpha': 0.4266021159137411, 'reg_lambda': 0.00027865003558119714, 'max_delta_step': 9}. Best is trial 2 with value: 0.6421200750469043.

Best trial: 2. Best value: 0.64212:  10%|█         | 5/50 [01:20<07:46, 10.37s/it]

[I 2025-12-01 18:46:57,659] Trial 1 finished with value: 0.6088180112570356 and parameters: {'max_depth': 3, 'learning_rate': 0.22450285305129317, 'n_estimators': 1477, 'subsample': 0.7300604786624288, 'colsample_bytree': 0.8657269249042095, 'min_child_weight': 3, 'gamma': 4.376620287401013, 'reg_alpha': 4.1350466072433324e-07, 'reg_lambda': 4.5497052584289075e-08, 'max_delta_step': 0}. Best is trial 2 with value: 0.6421200750469043.

Best trial: 8. Best value: 0.673546:  12%|█▏        | 6/50 [01:50<12:24, 16.92s/it]

[I 2025-12-01 18:47:27,275] Trial 8 finished with value: 0.6735459662288931 and parameters: {'max_depth': 8, 'learning_rate': 0.03308355103166953, 'n_estimators': 547, 'subsample': 0.9454080297306047, 'colsample_bytree': 0.638013752612361, 'min_child_weight': 6, 'gamma': 1.425364772135449, 'reg_alpha': 0.0012805183354351914, 'reg_lambda': 6.245307950442344e-08, 'max_delta_step': 4}. Best is trial 8 with value: 0.6735459662288931.

Best trial: 8. Best value: 0.673546:  14%|█▍        | 7/50 [01:54<09:16, 12.94s/it]

[I 2025-12-01 18:47:32,029] Trial 6 finished with value: 0.5966228893058161 and parameters: {'max_depth': 4, 'learning_rate': 0.025855178511443283, 'n_estimators': 326, 'subsample': 0.6340540393970427, 'colsample_bytree': 0.9621997126292197, 'min_child_weight': 1, 'gamma': 1.97598435129053, 'reg_alpha': 0.00013607412391963776, 'reg_lambda': 2.5338400752363963, 'max_delta_step': 8}. Best is trial 8 with value: 0.6735459662288931.

Best trial: 8. Best value: 0.673546:  16%|█▌        | 8/50 [01:58<06:58,  9.97s/it]

[I 2025-12-01 18:47:35,653] Trial 4 finished with value: 0.6299249530956847 and parameters: {'max_depth': 3, 'learning_rate': 0.014829904749573715, 'n_estimators': 1465, 'subsample': 0.7963535458092055, 'colsample_bytree': 0.9207679364599248, 'min_child_weight': 8, 'gamma': 2.02155979431832, 'reg_alpha': 1.3910841459209891e-08, 'reg_lambda': 1.1052744513399262e-06, 'max_delta_step': 6}. Best is trial 8 with value: 0.6735459662288931.

Best trial: 8. Best value: 0.673546:  18%|█▊        | 9/50 [02:10<07:15, 10.62s/it]

[I 2025-12-01 18:47:47,707] Trial 9 finished with value: 0.6036585365853658 and parameters: {'max_depth': 7, 'learning_rate': 0.12018352531728833, 'n_estimators': 371, 'subsample': 0.9924462592534291, 'colsample_bytree': 0.6056507400142255, 'min_child_weight': 6, 'gamma': 4.441480066044564, 'reg_alpha': 0.2181970974419437, 'reg_lambda': 4.103685673215533e-06, 'max_delta_step': 8}. Best is trial 8 with value: 0.6735459662288931.

Best trial: 8. Best value: 0.673546:  20%|██        | 10/50 [02:13<05:24,  8.11s/it]

[I 2025-12-01 18:47:50,185] Trial 7 finished with value: 0.6088180112570356 and parameters: {'max_depth': 5, 'learning_rate': 0.04194138235197654, 'n_estimators': 796, 'subsample': 0.8047773965254801, 'colsample_bytree': 0.6234744619935009, 'min_child_weight': 1, 'gamma': 3.323958228115287, 'reg_alpha': 7.003661708614674e-08, 'reg_lambda': 0.0316546213632681, 'max_delta_step': 3}. Best is trial 8 with value: 0.6735459662288931.

Best trial: 8. Best value: 0.673546:  22%|██▏       | 11/50 [02:20<05:07,  7.90s/it]

[I 2025-12-01 18:47:57,604] Trial 12 pruned.

Best trial: 10. Best value: 0.680582:  24%|██▍       | 12/50 [02:35<06:23, 10.08s/it]

[I 2025-12-01 18:48:12,676] Trial 10 finished with value: 0.6805816135084428 and parameters: {'max_depth': 7, 'learning_rate': 0.10991243988433555, 'n_estimators': 767, 'subsample': 0.5554216451658844, 'colsample_bytree': 0.9220575404493363, 'min_child_weight': 4, 'gamma': 3.1322855173711894, 'reg_alpha': 0.0005646592829304116, 'reg_lambda': 0.0063864432141424515, 'max_delta_step': 7}. Best is trial 10 with value: 0.6805816135084428.

Best trial: 10. Best value: 0.680582:  26%|██▌       | 13/50 [02:38<04:55,  7.98s/it]

[I 2025-12-01 18:48:15,818] Trial 11 finished with value: 0.6787054409005628 and parameters: {'max_depth': 3, 'learning_rate': 0.05816616277199367, 'n_estimators': 845, 'subsample': 0.6793084312201403, 'colsample_bytree': 0.6338863884594919, 'min_child_weight': 7, 'gamma': 2.5117279483696935, 'reg_alpha': 0.6805245323332101, 'reg_lambda': 5.707878703703265e-06, 'max_delta_step': 10}. Best is trial 10 with value: 0.6805816135084428.

Best trial: 10. Best value: 0.680582:  28%|██▊       | 14/50 [02:45<04:36,  7.68s/it]

[I 2025-12-01 18:48:22,821] Trial 15 pruned.

Best trial: 10. Best value: 0.680582:  30%|███       | 15/50 [02:50<03:59,  6.83s/it]

[I 2025-12-01 18:48:27,683] Trial 13 finished with value: 0.6787054409005628 and parameters: {'max_depth': 10, 'learning_rate': 0.049119457311140646, 'n_estimators': 588, 'subsample': 0.903334426455282, 'colsample_bytree': 0.747180815109006, 'min_child_weight': 4, 'gamma': 0.3746975432718975, 'reg_alpha': 0.002428190131045543, 'reg_lambda': 3.161816228173016e-05, 'max_delta_step': 0}. Best is trial 10 with value: 0.6805816135084428.

Best trial: 10. Best value: 0.680582:  32%|███▏      | 16/50 [02:52<03:01,  5.33s/it]

[I 2025-12-01 18:48:29,541] Trial 17 pruned.

Best trial: 10. Best value: 0.680582:  34%|███▍      | 17/50 [02:58<02:59,  5.45s/it]

[I 2025-12-01 18:48:35,246] Trial 18 pruned.

Best trial: 10. Best value: 0.680582:  36%|███▌      | 18/50 [03:03<02:55,  5.49s/it]

[I 2025-12-01 18:48:40,838] Trial 20 pruned.

Best trial: 10. Best value: 0.680582:  38%|███▊      | 19/50 [03:22<04:52,  9.44s/it]

[I 2025-12-01 18:48:59,490] Trial 19 pruned.

Best trial: 10. Best value: 0.680582:  40%|████      | 20/50 [03:29<04:22,  8.77s/it]

[I 2025-12-01 18:49:06,676] Trial 14 finished with value: 0.6543151969981238 and parameters: {'max_depth': 10, 'learning_rate': 0.0120824054286245, 'n_estimators': 1035, 'subsample': 0.879073087661688, 'colsample_bytree': 0.7323727654866803, 'min_child_weight': 6, 'gamma': 0.957835623303914, 'reg_alpha': 0.00011064866850268916, 'reg_lambda': 3.839429855543319e-05, 'max_delta_step': 1}. Best is trial 10 with value: 0.6805816135084428.

Best trial: 10. Best value: 0.680582:  42%|████▏     | 21/50 [03:30<03:08,  6.50s/it]

[I 2025-12-01 18:49:07,888] Trial 16 finished with value: 0.6683864915572233 and parameters: {'max_depth': 10, 'learning_rate': 0.0817080541744015, 'n_estimators': 999, 'subsample': 0.5308083400404849, 'colsample_bytree': 0.7323278137128038, 'min_child_weight': 4, 'gamma': 1.1195048736048858, 'reg_alpha': 0.0049207035236933, 'reg_lambda': 9.431969045914289e-05, 'max_delta_step': 10}. Best is trial 10 with value: 0.6805816135084428.

Best trial: 10. Best value: 0.680582:  44%|████▍     | 22/50 [03:37<02:59,  6.42s/it]

[I 2025-12-01 18:49:14,140] Trial 24 pruned.

Best trial: 10. Best value: 0.680582:  46%|████▌     | 23/50 [03:39<02:22,  5.28s/it]

[I 2025-12-01 18:49:16,767] Trial 23 pruned.

Best trial: 10. Best value: 0.680582:  48%|████▊     | 24/50 [03:46<02:28,  5.71s/it]

[I 2025-12-01 18:49:23,455] Trial 26 pruned.

Best trial: 10. Best value: 0.680582:  50%|█████     | 25/50 [03:52<02:28,  5.95s/it]

[I 2025-12-01 18:49:29,968] Trial 21 finished with value: 0.6472795497185742 and parameters: {'max_depth': 8, 'learning_rate': 0.2876946776766686, 'n_estimators': 967, 'subsample': 0.5761009155572949, 'colsample_bytree': 0.5615972588317113, 'min_child_weight': 3, 'gamma': 2.7657659189139583, 'reg_alpha': 0.0673521764030337, 'reg_lambda': 1.0193533301763404e-06, 'max_delta_step': 7}. Best is trial 10 with value: 0.6805816135084428.

Best trial: 10. Best value: 0.680582:  52%|█████▏    | 26/50 [04:07<03:26,  8.62s/it]

[I 2025-12-01 18:49:44,811] Trial 28 pruned.

Best trial: 10. Best value: 0.680582:  56%|█████▌    | 28/50 [04:16<02:13,  6.07s/it]

[I 2025-12-01 18:49:53,393] Trial 25 finished with value: 0.6299249530956847 and parameters: {'max_depth': 4, 'learning_rate': 0.024837774379940846, 'n_estimators': 669, 'subsample': 0.5673703760502826, 'colsample_bytree': 0.5610127163581213, 'min_child_weight': 5, 'gamma': 1.68355298328201, 'reg_alpha': 0.00109795439525358, 'reg_lambda': 0.0012148651085371275, 'max_delta_step': 0}. Best is trial 10 with value: 0.6805816135084428.
[I 2025-12-01 18:49:53,531] Trial 29 pruned.

Best trial: 10. Best value: 0.680582:  58%|█████▊    | 29/50 [04:21<02:03,  5.90s/it]

[I 2025-12-01 18:49:59,044] Trial 30 pruned.

Best trial: 10. Best value: 0.680582:  60%|██████    | 30/50 [04:23<01:31,  4.58s/it]

[I 2025-12-01 18:50:00,561] Trial 22 finished with value: 0.6613508442776735 and parameters: {'max_depth': 4, 'learning_rate': 0.2369602799599633, 'n_estimators': 1177, 'subsample': 0.5676074150455179, 'colsample_bytree': 0.6867438331843619, 'min_child_weight': 3, 'gamma': 1.4688913777854793, 'reg_alpha': 0.12516359198492732, 'reg_lambda': 1.4674223229115387e-06, 'max_delta_step': 7}. Best is trial 10 with value: 0.6805816135084428.

Best trial: 27. Best value: 0.710131:  62%|██████▏   | 31/50 [04:31<01:45,  5.57s/it]

[I 2025-12-01 18:50:08,421] Trial 27 finished with value: 0.7101313320825516 and parameters: {'max_depth': 6, 'learning_rate': 0.2961865616165566, 'n_estimators': 882, 'subsample': 0.5987648912991246, 'colsample_bytree': 0.8017113206038656, 'min_child_weight': 5, 'gamma': 1.5166069971087763, 'reg_alpha': 0.4523914858534321, 'reg_lambda': 4.280294074395693e-07, 'max_delta_step': 9}. Best is trial 27 with value: 0.7101313320825516.

Best trial: 27. Best value: 0.710131:  64%|██████▍   | 32/50 [04:46<02:30,  8.38s/it]

[I 2025-12-01 18:50:23,367] Trial 33 pruned.

Best trial: 27. Best value: 0.710131:  66%|██████▌   | 33/50 [04:51<02:04,  7.32s/it]

[I 2025-12-01 18:50:28,209] Trial 34 pruned.

Best trial: 27. Best value: 0.710131:  68%|██████▊   | 34/50 [04:56<01:48,  6.79s/it]

[I 2025-12-01 18:50:33,747] Trial 31 finished with value: 0.6927767354596623 and parameters: {'max_depth': 9, 'learning_rate': 0.06767665691413703, 'n_estimators': 731, 'subsample': 0.8436565255163156, 'colsample_bytree': 0.907595541968216, 'min_child_weight': 7, 'gamma': 2.36587105435942, 'reg_alpha': 1.2592171701517097e-05, 'reg_lambda': 2.216543633730123e-07, 'max_delta_step': 5}. Best is trial 27 with value: 0.7101313320825516.

Best trial: 27. Best value: 0.710131:  70%|███████   | 35/50 [05:03<01:42,  6.85s/it]

[I 2025-12-01 18:50:40,737] Trial 35 pruned.

Best trial: 27. Best value: 0.710131:  72%|███████▏  | 36/50 [05:08<01:28,  6.36s/it]

[I 2025-12-01 18:50:45,949] Trial 37 pruned.

Best trial: 27. Best value: 0.710131:  74%|███████▍  | 37/50 [05:13<01:14,  5.76s/it]

[I 2025-12-01 18:50:50,314] Trial 32 finished with value: 0.6665103189493433 and parameters: {'max_depth': 5, 'learning_rate': 0.01852502149343202, 'n_estimators': 879, 'subsample': 0.8708837186106854, 'colsample_bytree': 0.7072808893716669, 'min_child_weight': 7, 'gamma': 3.678530519565527, 'reg_alpha': 2.443815519908325e-05, 'reg_lambda': 3.334232120223037e-07, 'max_delta_step': 2}. Best is trial 27 with value: 0.7101313320825516.

Best trial: 27. Best value: 0.710131:  76%|███████▌  | 38/50 [05:21<01:18,  6.53s/it]

[I 2025-12-01 18:50:58,645] Trial 36 pruned.

Best trial: 27. Best value: 0.710131:  78%|███████▊  | 39/50 [05:27<01:08,  6.22s/it]

[I 2025-12-01 18:51:04,156] Trial 39 pruned.

Best trial: 27. Best value: 0.710131:  80%|████████  | 40/50 [05:36<01:10,  7.07s/it]

[I 2025-12-01 18:51:13,189] Trial 41 pruned.

Best trial: 27. Best value: 0.710131:  82%|████████▏ | 41/50 [05:38<00:50,  5.56s/it]

[I 2025-12-01 18:51:15,223] Trial 40 pruned.

Best trial: 27. Best value: 0.710131:  84%|████████▍ | 42/50 [05:44<00:45,  5.73s/it]

[I 2025-12-01 18:51:21,355] Trial 44 pruned.

Best trial: 27. Best value: 0.710131:  86%|████████▌ | 43/50 [05:48<00:36,  5.23s/it]

[I 2025-12-01 18:51:25,417] Trial 38 finished with value: 0.6543151969981238 and parameters: {'max_depth': 7, 'learning_rate': 0.06922557566566125, 'n_estimators': 769, 'subsample': 0.668066514398667, 'colsample_bytree': 0.8842370733241645, 'min_child_weight': 5, 'gamma': 2.2796445691357174, 'reg_alpha': 7.574082627416403e-07, 'reg_lambda': 1.2466275739138157e-08, 'max_delta_step': 5}. Best is trial 27 with value: 0.7101313320825516.

Best trial: 27. Best value: 0.710131:  88%|████████▊ | 44/50 [05:49<00:24,  4.02s/it]

[I 2025-12-01 18:51:26,612] Trial 45 pruned.

Best trial: 27. Best value: 0.710131:  90%|█████████ | 45/50 [05:59<00:29,  5.92s/it]

[I 2025-12-01 18:51:36,980] Trial 43 pruned.
[I 2025-12-01 18:51:37,030] Trial 42 pruned.

Best trial: 27. Best value: 0.710131:  94%|█████████▍| 47/50 [06:04<00:12,  4.16s/it]

[I 2025-12-01 18:51:41,207] Trial 46 pruned.

Best trial: 27. Best value: 0.710131:  96%|█████████▌| 48/50 [06:06<00:07,  3.67s/it]

[I 2025-12-01 18:51:43,356] Trial 47 pruned.

Best trial: 27. Best value: 0.710131: 100%|██████████| 50/50 [06:06<00:00,  7.34s/it]

[I 2025-12-01 18:51:43,893] Trial 49 pruned.
[I 2025-12-01 18:51:43,995] Trial 48 pruned.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 18:51:47,939] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 64, Test size: 16
Using Leave-One-Out CV with 64 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.566667:   2%|▏         | 1/50 [00:45<37:07, 45.47s/it]

[I 2025-12-01 18:52:33,394] Trial 2 finished with value: 0.5666666666666667 and parameters: {'max_depth': 10, 'learning_rate': 0.11576384331487861, 'n_estimators': 961, 'subsample': 0.5352895788397267, 'colsample_bytree': 0.6572953453026509, 'min_child_weight': 6, 'gamma': 2.302346379049073, 'reg_alpha': 2.422442593280875, 'reg_lambda': 0.07697032140977897, 'max_delta_step': 10}. Best is trial 2 with value: 0.5666666666666667.

Best trial: 3. Best value: 0.704167:   4%|▍         | 2/50 [00:46<15:17, 19.12s/it]

[I 2025-12-01 18:52:34,070] Trial 3 finished with value: 0.7041666666666666 and parameters: {'max_depth': 8, 'learning_rate': 0.07411829234343704, 'n_estimators': 824, 'subsample': 0.7586392062683038, 'colsample_bytree': 0.9153374856756553, 'min_child_weight': 3, 'gamma': 0.9058700980803785, 'reg_alpha': 9.86147542426249e-05, 'reg_lambda': 0.09405181304098391, 'max_delta_step': 9}. Best is trial 3 with value: 0.7041666666666666.

Best trial: 3. Best value: 0.704167:   6%|▌         | 3/50 [00:48<09:00, 11.50s/it]

[I 2025-12-01 18:52:36,517] Trial 0 finished with value: 0.1375 and parameters: {'max_depth': 6, 'learning_rate': 0.2634820912438678, 'n_estimators': 1039, 'subsample': 0.6633308505166988, 'colsample_bytree': 0.8806552150445616, 'min_child_weight': 9, 'gamma': 3.159738848441704, 'reg_alpha': 1.3978750584514761e-06, 'reg_lambda': 0.0040516346846073735, 'max_delta_step': 10}. Best is trial 3 with value: 0.7041666666666666.

Best trial: 3. Best value: 0.704167:   8%|▊         | 4/50 [00:58<08:12, 10.71s/it]

[I 2025-12-01 18:52:46,007] Trial 1 finished with value: 0.6916666666666667 and parameters: {'max_depth': 8, 'learning_rate': 0.19192704089769522, 'n_estimators': 1203, 'subsample': 0.8022329817220151, 'colsample_bytree': 0.9329228259142759, 'min_child_weight': 4, 'gamma': 1.241431223548655, 'reg_alpha': 0.27470611237452724, 'reg_lambda': 2.7356258620515147e-07, 'max_delta_step': 2}. Best is trial 3 with value: 0.7041666666666666.

Best trial: 3. Best value: 0.704167:  10%|█         | 5/50 [01:15<09:43, 12.96s/it]

[I 2025-12-01 18:53:02,950] Trial 5 finished with value: 0.6083333333333334 and parameters: {'max_depth': 6, 'learning_rate': 0.017080498324559577, 'n_estimators': 598, 'subsample': 0.6880525357507782, 'colsample_bytree': 0.5483265716191036, 'min_child_weight': 7, 'gamma': 1.5185359676570953, 'reg_alpha': 0.12734527808680876, 'reg_lambda': 0.00022672483774020816, 'max_delta_step': 3}. Best is trial 3 with value: 0.7041666666666666.

Best trial: 3. Best value: 0.704167:  12%|█▏        | 6/50 [01:29<09:53, 13.49s/it]

[I 2025-12-01 18:53:17,486] Trial 7 finished with value: 0.1 and parameters: {'max_depth': 9, 'learning_rate': 0.06556375740485253, 'n_estimators': 789, 'subsample': 0.5337104097009906, 'colsample_bytree': 0.5092588385367915, 'min_child_weight': 10, 'gamma': 0.23802135258379264, 'reg_alpha': 3.1848024453697423, 'reg_lambda': 0.0504147015663247, 'max_delta_step': 3}. Best is trial 3 with value: 0.7041666666666666.

Best trial: 3. Best value: 0.704167:  14%|█▍        | 7/50 [01:33<07:28, 10.42s/it]

[I 2025-12-01 18:53:21,575] Trial 6 finished with value: 0.5083333333333333 and parameters: {'max_depth': 3, 'learning_rate': 0.2889372537496331, 'n_estimators': 943, 'subsample': 0.5740985220072197, 'colsample_bytree': 0.7434392998532804, 'min_child_weight': 4, 'gamma': 3.12255009689465, 'reg_alpha': 4.272696048349973, 'reg_lambda': 0.0028090655212853572, 'max_delta_step': 0}. Best is trial 3 with value: 0.7041666666666666.

Best trial: 3. Best value: 0.704167:  16%|█▌        | 8/50 [02:07<12:33, 17.95s/it]

[I 2025-12-01 18:53:55,644] Trial 4 finished with value: 0.6458333333333333 and parameters: {'max_depth': 8, 'learning_rate': 0.07444232957148621, 'n_estimators': 1104, 'subsample': 0.8551164735854448, 'colsample_bytree': 0.966959565535012, 'min_child_weight': 1, 'gamma': 3.4607948074877832, 'reg_alpha': 5.639689972795882e-07, 'reg_lambda': 1.2974699690012107e-05, 'max_delta_step': 1}. Best is trial 3 with value: 0.7041666666666666.

Best trial: 3. Best value: 0.704167:  18%|█▊        | 9/50 [02:13<09:44, 14.26s/it]

[I 2025-12-01 18:54:01,808] Trial 9 finished with value: 0.5666666666666667 and parameters: {'max_depth': 4, 'learning_rate': 0.050073402014267326, 'n_estimators': 1089, 'subsample': 0.9368909255338607, 'colsample_bytree': 0.9971661438424972, 'min_child_weight': 9, 'gamma': 0.20331079389412976, 'reg_alpha': 0.00012820945289083934, 'reg_lambda': 6.897105032945442e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.7041666666666666.

Best trial: 3. Best value: 0.704167:  20%|██        | 10/50 [02:21<08:09, 12.23s/it]

[I 2025-12-01 18:54:09,485] Trial 10 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.12307881833838827, 'n_estimators': 1282, 'subsample': 0.9106576889981487, 'colsample_bytree': 0.7870267385495342, 'min_child_weight': 10, 'gamma': 4.217422018818491, 'reg_alpha': 2.495097276543367e-07, 'reg_lambda': 1.6114006159869466e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.7041666666666666.

Best trial: 3. Best value: 0.704167:  22%|██▏       | 11/50 [02:29<07:11, 11.06s/it]

[I 2025-12-01 18:54:17,874] Trial 12 pruned.

Best trial: 3. Best value: 0.704167:  24%|██▍       | 12/50 [02:32<05:17,  8.35s/it]

[I 2025-12-01 18:54:20,031] Trial 11 finished with value: 0.5375 and parameters: {'max_depth': 4, 'learning_rate': 0.23389249914028926, 'n_estimators': 382, 'subsample': 0.717513957612329, 'colsample_bytree': 0.9556734688464437, 'min_child_weight': 2, 'gamma': 4.435558492855873, 'reg_alpha': 2.033600317308334e-07, 'reg_lambda': 0.01364067524809753, 'max_delta_step': 8}. Best is trial 3 with value: 0.7041666666666666.

Best trial: 14. Best value: 0.745833:  26%|██▌       | 13/50 [02:44<05:56,  9.63s/it]

[I 2025-12-01 18:54:32,601] Trial 14 finished with value: 0.7458333333333333 and parameters: {'max_depth': 7, 'learning_rate': 0.12929562851229945, 'n_estimators': 229, 'subsample': 0.7644709894811179, 'colsample_bytree': 0.851407745192103, 'min_child_weight': 3, 'gamma': 1.1859138235998976, 'reg_alpha': 0.00309803256897294, 'reg_lambda': 9.252706172570732e-08, 'max_delta_step': 7}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  28%|██▊       | 14/50 [02:47<04:27,  7.43s/it]

[I 2025-12-01 18:54:34,966] Trial 8 finished with value: 0.675 and parameters: {'max_depth': 4, 'learning_rate': 0.020266002022384676, 'n_estimators': 1170, 'subsample': 0.7285211431024783, 'colsample_bytree': 0.993017712477668, 'min_child_weight': 1, 'gamma': 0.4299391476711917, 'reg_alpha': 8.423499864951493e-08, 'reg_lambda': 5.1512975823654185e-06, 'max_delta_step': 10}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  30%|███       | 15/50 [03:00<05:25,  9.30s/it]

[I 2025-12-01 18:54:48,605] Trial 13 finished with value: 0.6583333333333333 and parameters: {'max_depth': 5, 'learning_rate': 0.02662217491303736, 'n_estimators': 217, 'subsample': 0.7476006845870264, 'colsample_bytree': 0.8111915178844525, 'min_child_weight': 1, 'gamma': 1.4058165356734247, 'reg_alpha': 0.0006184649302061018, 'reg_lambda': 6.421238327716963, 'max_delta_step': 7}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  32%|███▏      | 16/50 [03:04<04:20,  7.67s/it]

[I 2025-12-01 18:54:52,488] Trial 16 finished with value: 0.7375 and parameters: {'max_depth': 7, 'learning_rate': 0.03583525833426145, 'n_estimators': 211, 'subsample': 0.7859714803646833, 'colsample_bytree': 0.8339422111258883, 'min_child_weight': 4, 'gamma': 1.0697156512192323, 'reg_alpha': 0.0009732497835807244, 'reg_lambda': 3.0065385000331354e-08, 'max_delta_step': 7}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  34%|███▍      | 17/50 [03:41<09:01, 16.40s/it]

[I 2025-12-01 18:55:29,200] Trial 15 finished with value: 0.725 and parameters: {'max_depth': 7, 'learning_rate': 0.03354426138849996, 'n_estimators': 1412, 'subsample': 0.7945504932820148, 'colsample_bytree': 0.8428525003466435, 'min_child_weight': 4, 'gamma': 1.3590747937163152, 'reg_alpha': 0.0009507020470200437, 'reg_lambda': 1.9168026135521558e-08, 'max_delta_step': 6}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  36%|███▌      | 18/50 [03:43<06:26, 12.08s/it]

[I 2025-12-01 18:55:31,229] Trial 20 pruned.

Best trial: 14. Best value: 0.745833:  38%|███▊      | 19/50 [04:00<07:01, 13.61s/it]

[I 2025-12-01 18:55:48,396] Trial 17 finished with value: 0.7375 and parameters: {'max_depth': 7, 'learning_rate': 0.037012048357743396, 'n_estimators': 1464, 'subsample': 0.7875363336210036, 'colsample_bytree': 0.8376621200896129, 'min_child_weight': 4, 'gamma': 1.2124979361598998, 'reg_alpha': 0.00025538709776581805, 'reg_lambda': 1.2709308917404399e-08, 'max_delta_step': 7}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  40%|████      | 20/50 [04:04<05:24, 10.83s/it]

[I 2025-12-01 18:55:52,743] Trial 22 pruned.

Best trial: 14. Best value: 0.745833:  42%|████▏     | 21/50 [04:05<03:45,  7.79s/it]

[I 2025-12-01 18:55:53,439] Trial 21 finished with value: 0.6791666666666667 and parameters: {'max_depth': 6, 'learning_rate': 0.12629063392140585, 'n_estimators': 418, 'subsample': 0.8222187232792016, 'colsample_bytree': 0.6959813617519752, 'min_child_weight': 5, 'gamma': 0.7280411385664559, 'reg_alpha': 9.726361271163058e-06, 'reg_lambda': 2.1848453650321576e-07, 'max_delta_step': 8}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  44%|████▍     | 22/50 [04:17<04:11,  9.00s/it]

[I 2025-12-01 18:56:05,263] Trial 18 finished with value: 0.7333333333333334 and parameters: {'max_depth': 7, 'learning_rate': 0.0426279136377342, 'n_estimators': 1430, 'subsample': 0.9971169661585411, 'colsample_bytree': 0.8574885302110505, 'min_child_weight': 4, 'gamma': 0.8752295334418172, 'reg_alpha': 0.000823740981868977, 'reg_lambda': 1.7881455229154612e-08, 'max_delta_step': 7}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  46%|████▌     | 23/50 [04:26<04:01,  8.96s/it]

[I 2025-12-01 18:56:14,128] Trial 19 finished with value: 0.6541666666666667 and parameters: {'max_depth': 6, 'learning_rate': 0.01127371882720586, 'n_estimators': 1484, 'subsample': 0.6240510255778895, 'colsample_bytree': 0.8311500402077808, 'min_child_weight': 5, 'gamma': 2.129329349873577, 'reg_alpha': 0.0027898193272170684, 'reg_lambda': 2.179591809457925e-08, 'max_delta_step': 6}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  48%|████▊     | 24/50 [04:27<02:51,  6.61s/it]

[I 2025-12-01 18:56:15,263] Trial 23 finished with value: 0.7 and parameters: {'max_depth': 9, 'learning_rate': 0.1209086590229938, 'n_estimators': 381, 'subsample': 0.6078571229291532, 'colsample_bytree': 0.8803190997390027, 'min_child_weight': 5, 'gamma': 2.5411716580602843, 'reg_alpha': 0.00893823658502758, 'reg_lambda': 8.233499009738911e-05, 'max_delta_step': 5}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  50%|█████     | 25/50 [04:43<03:53,  9.35s/it]

[I 2025-12-01 18:56:31,015] Trial 25 finished with value: 0.7166666666666667 and parameters: {'max_depth': 9, 'learning_rate': 0.03524928418478543, 'n_estimators': 329, 'subsample': 0.7740515589571596, 'colsample_bytree': 0.7957305971677083, 'min_child_weight': 3, 'gamma': 1.7839239064717287, 'reg_alpha': 0.013230113190684577, 'reg_lambda': 6.386280841260463e-05, 'max_delta_step': 6}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  52%|█████▏    | 26/50 [04:53<03:49,  9.58s/it]

[I 2025-12-01 18:56:41,113] Trial 28 pruned.
[I 2025-12-01 18:56:41,294] Trial 26 finished with value: 0.7375 and parameters: {'max_depth': 9, 'learning_rate': 0.0284572513115254, 'n_estimators': 319, 'subsample': 0.7741902175124998, 'colsample_bytree': 0.7833819376817405, 'min_child_weight': 3, 'gamma': 1.6006196158087083, 'reg_alpha': 0.015843113743205406, 'reg_lambda': 0.0001275109412729124, 'max_delta_step': 5}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  56%|█████▌    | 28/50 [05:00<02:32,  6.94s/it]

[I 2025-12-01 18:56:48,657] Trial 29 pruned.

Best trial: 14. Best value: 0.745833:  58%|█████▊    | 29/50 [05:05<02:09,  6.18s/it]

[I 2025-12-01 18:56:53,044] Trial 27 finished with value: 0.7375 and parameters: {'max_depth': 5, 'learning_rate': 0.032723366362589434, 'n_estimators': 605, 'subsample': 0.775827714355928, 'colsample_bytree': 0.7827205390611605, 'min_child_weight': 3, 'gamma': 1.7927652880261686, 'reg_alpha': 0.04020361943369981, 'reg_lambda': 1.0286775371396107e-06, 'max_delta_step': 7}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  60%|██████    | 30/50 [05:05<01:30,  4.55s/it]

[I 2025-12-01 18:56:53,784] Trial 31 pruned.

Best trial: 14. Best value: 0.745833:  62%|██████▏   | 31/50 [05:09<01:22,  4.37s/it]

[I 2025-12-01 18:56:57,744] Trial 32 pruned.

Best trial: 14. Best value: 0.745833:  64%|██████▍   | 32/50 [05:10<01:00,  3.39s/it]

[I 2025-12-01 18:56:58,848] Trial 33 pruned.

Best trial: 14. Best value: 0.745833:  66%|██████▌   | 33/50 [05:13<00:52,  3.06s/it]

[I 2025-12-01 18:57:01,145] Trial 30 pruned.

Best trial: 14. Best value: 0.745833:  68%|██████▊   | 34/50 [05:13<00:36,  2.27s/it]

[I 2025-12-01 18:57:01,577] Trial 35 pruned.

Best trial: 14. Best value: 0.745833:  70%|███████   | 35/50 [05:16<00:38,  2.56s/it]

[I 2025-12-01 18:57:04,827] Trial 36 pruned.

Best trial: 14. Best value: 0.745833:  72%|███████▏  | 36/50 [05:20<00:38,  2.75s/it]

[I 2025-12-01 18:57:07,999] Trial 24 finished with value: 0.7041666666666666 and parameters: {'max_depth': 7, 'learning_rate': 0.03994754668133497, 'n_estimators': 1474, 'subsample': 0.7757473459410844, 'colsample_bytree': 0.8624338177680905, 'min_child_weight': 3, 'gamma': 0.8325456506564899, 'reg_alpha': 0.005743319432344826, 'reg_lambda': 5.245996861993394e-08, 'max_delta_step': 6}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  74%|███████▍  | 37/50 [05:32<01:14,  5.76s/it]

[I 2025-12-01 18:57:20,790] Trial 34 finished with value: 0.6916666666666667 and parameters: {'max_depth': 8, 'learning_rate': 0.02569276102134252, 'n_estimators': 282, 'subsample': 0.7349635463742827, 'colsample_bytree': 0.7697237142806577, 'min_child_weight': 4, 'gamma': 1.5711948082663685, 'reg_alpha': 0.0025435422832655154, 'reg_lambda': 0.0017328522458866778, 'max_delta_step': 5}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  76%|███████▌  | 38/50 [05:37<01:05,  5.44s/it]

[I 2025-12-01 18:57:25,466] Trial 39 finished with value: 0.7125 and parameters: {'max_depth': 8, 'learning_rate': 0.10074372665546207, 'n_estimators': 321, 'subsample': 0.7467563764714363, 'colsample_bytree': 0.8096992982906375, 'min_child_weight': 5, 'gamma': 0.5129764112843715, 'reg_alpha': 0.00020289276315189377, 'reg_lambda': 2.9685624554296936e-05, 'max_delta_step': 5}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  78%|███████▊  | 39/50 [05:38<00:43,  3.96s/it]

[I 2025-12-01 18:57:25,970] Trial 37 finished with value: 0.725 and parameters: {'max_depth': 10, 'learning_rate': 0.040250339048245244, 'n_estimators': 282, 'subsample': 0.733871215646072, 'colsample_bytree': 0.8172929920996507, 'min_child_weight': 3, 'gamma': 0.4734275828093253, 'reg_alpha': 0.0020259849346556504, 'reg_lambda': 5.739033410874832e-07, 'max_delta_step': 5}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  80%|████████  | 40/50 [05:56<01:22,  8.23s/it]

[I 2025-12-01 18:57:44,169] Trial 42 pruned.

Best trial: 14. Best value: 0.745833:  82%|████████▏ | 41/50 [06:00<01:02,  6.93s/it]

[I 2025-12-01 18:57:48,076] Trial 38 finished with value: 0.725 and parameters: {'max_depth': 10, 'learning_rate': 0.09577118389106212, 'n_estimators': 921, 'subsample': 0.7546838896826809, 'colsample_bytree': 0.6232306767383973, 'min_child_weight': 3, 'gamma': 0.4031325153188021, 'reg_alpha': 0.0030303534732018036, 'reg_lambda': 2.413896463504056e-06, 'max_delta_step': 5}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  84%|████████▍ | 42/50 [06:09<01:00,  7.60s/it]

[I 2025-12-01 18:57:57,228] Trial 41 finished with value: 0.6958333333333333 and parameters: {'max_depth': 8, 'learning_rate': 0.05970418123977314, 'n_estimators': 453, 'subsample': 0.8420312048170064, 'colsample_bytree': 0.9114816462812166, 'min_child_weight': 3, 'gamma': 2.88717850361734, 'reg_alpha': 0.5019613017187833, 'reg_lambda': 2.371266955569212e-06, 'max_delta_step': 8}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  86%|████████▌ | 43/50 [06:18<00:56,  8.13s/it]

[I 2025-12-01 18:58:06,601] Trial 40 finished with value: 0.7 and parameters: {'max_depth': 10, 'learning_rate': 0.09409049714073936, 'n_estimators': 950, 'subsample': 0.843857024084667, 'colsample_bytree': 0.8167797530354187, 'min_child_weight': 5, 'gamma': 0.41374565012402964, 'reg_alpha': 0.00020160385320181843, 'reg_lambda': 0.9628512938220224, 'max_delta_step': 8}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  88%|████████▊ | 44/50 [06:31<00:56,  9.46s/it]

[I 2025-12-01 18:58:19,166] Trial 45 pruned.

Best trial: 14. Best value: 0.745833:  90%|█████████ | 45/50 [06:33<00:36,  7.24s/it]

[I 2025-12-01 18:58:21,215] Trial 44 finished with value: 0.7375 and parameters: {'max_depth': 5, 'learning_rate': 0.030846834308336096, 'n_estimators': 471, 'subsample': 0.7883889081168514, 'colsample_bytree': 0.724746482488422, 'min_child_weight': 3, 'gamma': 1.7954101477743856, 'reg_alpha': 0.038974531902721994, 'reg_lambda': 0.0006454422298648005, 'max_delta_step': 7}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  92%|█████████▏| 46/50 [06:42<00:31,  7.79s/it]

[I 2025-12-01 18:58:30,291] Trial 43 finished with value: 0.6916666666666667 and parameters: {'max_depth': 8, 'learning_rate': 0.1511394164380457, 'n_estimators': 998, 'subsample': 0.7094897195466572, 'colsample_bytree': 0.722914932397607, 'min_child_weight': 4, 'gamma': 0.10114281891182897, 'reg_alpha': 0.027389018398332424, 'reg_lambda': 3.1406943476920257e-06, 'max_delta_step': 3}. Best is trial 14 with value: 0.7458333333333333.

Best trial: 14. Best value: 0.745833:  94%|█████████▍| 47/50 [06:49<00:22,  7.66s/it]

[I 2025-12-01 18:58:37,652] Trial 47 pruned.

Best trial: 14. Best value: 0.745833:  96%|█████████▌| 48/50 [06:52<00:12,  6.15s/it]

[I 2025-12-01 18:58:40,288] Trial 49 pruned.

Best trial: 14. Best value: 0.745833:  98%|█████████▊| 49/50 [07:06<00:08,  8.57s/it]

[I 2025-12-01 18:58:54,513] Trial 48 pruned.

Best trial: 14. Best value: 0.745833: 100%|██████████| 50/50 [07:07<00:00,  8.55s/it]

[I 2025-12-01 18:58:55,612] Trial 46 finished with value: 0.7041666666666666 and parameters: {'max_depth': 5, 'learning_rate': 0.03021207617436613, 'n_estimators': 1037, 'subsample': 0.789636749511077, 'colsample_bytree': 0.7298304282959057, 'min_child_weight': 3, 'gamma': 1.98254919441052, 'reg_alpha': 0.048452458898503394, 'reg_lambda': 0.00035877130724407537, 'max_delta_step': 7}. Best is trial 14 with value: 0.7458333333333333.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    19_1         loo       0.745833                0.766667      0.883333
1     9_1         loo       0.604348                0.700000      0.733333
2    15_1         loo       0.549268                0.614286      0.542857
3    17_1         loo       0.710131                0.464286      0.528571

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.516398          0.833333               0.7        50          64
1  0.447214          0.500000               0.9        50          63
2  0.246885          0.428571               0.8        50          66
3 -0.070430          0.428571               0.5        50          67

   test_size
0         16
1         16
2         17
3         17
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    19_1         loo       0.745833                0.766667      0.883333
1     9_1         loo       0.604348                0.700000      0.733333
2    15_1         loo       0.549268                0.614286      0.542857
3    17_1         loo       0.710131                0.464286      0.528571

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.516398          0.833333               0.7        50          64
1  0.447214          0.500000               0.9        50          63
2  0.246885          0.428571               0.8        50          66
3 -0.070430          0.428571               0.5        50          67

   test_size
0         16
1         16
2         17
3         17

In [1566]:
# Combined embedings
datasets = task_comb_dfs_lbd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir="xgb_lbd_hc_{CV_STRATEGY}_tasks/xgb_results_comb_lbd_hc_extended_{CV_STRATEGY}_tasks",
    split_param="emb_",
)
print(summary)

[I 2025-12-01 18:59:00,899] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 63, Test size: 16
Using Leave-One-Out CV with 63 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.495652:   2%|▏         | 1/50 [00:42<34:37, 42.40s/it]

[I 2025-12-01 18:59:43,297] Trial 0 finished with value: 0.4956521739130435 and parameters: {'max_depth': 5, 'learning_rate': 0.012677563350542893, 'n_estimators': 635, 'subsample': 0.8290574498058024, 'colsample_bytree': 0.6867695003496679, 'min_child_weight': 8, 'gamma': 3.0478636950727935, 'reg_alpha': 4.5731271266275055e-08, 'reg_lambda': 2.5346581893303726e-07, 'max_delta_step': 6}. Best is trial 0 with value: 0.4956521739130435.

Best trial: 0. Best value: 0.495652:   4%|▍         | 2/50 [00:46<16:05, 20.11s/it]

[I 2025-12-01 18:59:47,797] Trial 3 finished with value: 0.45652173913043476 and parameters: {'max_depth': 3, 'learning_rate': 0.11007981730655289, 'n_estimators': 877, 'subsample': 0.5050663038922952, 'colsample_bytree': 0.853555714229028, 'min_child_weight': 10, 'gamma': 4.434356116109694, 'reg_alpha': 0.0936936126375401, 'reg_lambda': 2.0231543381787442e-07, 'max_delta_step': 10}. Best is trial 0 with value: 0.4956521739130435.

Best trial: 0. Best value: 0.495652:   6%|▌         | 3/50 [01:03<14:33, 18.59s/it]

[I 2025-12-01 19:00:04,576] Trial 1 finished with value: 0.45652173913043476 and parameters: {'max_depth': 7, 'learning_rate': 0.1930732028656427, 'n_estimators': 1202, 'subsample': 0.6069813565452218, 'colsample_bytree': 0.7651469257875865, 'min_child_weight': 10, 'gamma': 3.3358695130510494, 'reg_alpha': 0.012107315151278601, 'reg_lambda': 4.897723074849555e-05, 'max_delta_step': 9}. Best is trial 0 with value: 0.4956521739130435.

Best trial: 2. Best value: 0.654348:   8%|▊         | 4/50 [01:21<14:08, 18.44s/it]

[I 2025-12-01 19:00:22,790] Trial 2 finished with value: 0.6543478260869565 and parameters: {'max_depth': 9, 'learning_rate': 0.03840175491738105, 'n_estimators': 1350, 'subsample': 0.5094429761939421, 'colsample_bytree': 0.9609559709179873, 'min_child_weight': 5, 'gamma': 1.7231433706936417, 'reg_alpha': 1.1491419986905547e-07, 'reg_lambda': 0.36480201628300096, 'max_delta_step': 3}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  10%|█         | 5/50 [01:25<09:50, 13.12s/it]

[I 2025-12-01 19:00:26,487] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.01654732184089301, 'n_estimators': 821, 'subsample': 0.5413941427646458, 'colsample_bytree': 0.5929447349709367, 'min_child_weight': 9, 'gamma': 1.8267926849626481, 'reg_alpha': 0.008386752481683517, 'reg_lambda': 0.7079281127615255, 'max_delta_step': 8}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  12%|█▏        | 6/50 [01:51<12:55, 17.63s/it]

[I 2025-12-01 19:00:52,861] Trial 6 finished with value: 0.46739130434782605 and parameters: {'max_depth': 6, 'learning_rate': 0.11990641356999529, 'n_estimators': 828, 'subsample': 0.8512173334904025, 'colsample_bytree': 0.999222825524303, 'min_child_weight': 9, 'gamma': 4.609965234201802, 'reg_alpha': 0.3880520769459167, 'reg_lambda': 7.594564966445448e-06, 'max_delta_step': 8}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  14%|█▍        | 7/50 [02:21<15:30, 21.64s/it]

[I 2025-12-01 19:01:22,772] Trial 7 finished with value: 0.5951086956521738 and parameters: {'max_depth': 8, 'learning_rate': 0.03211296714020572, 'n_estimators': 1036, 'subsample': 0.5711064853572458, 'colsample_bytree': 0.7956493095471056, 'min_child_weight': 6, 'gamma': 4.770552016390054, 'reg_alpha': 1.2417256909873573e-07, 'reg_lambda': 1.3200949435563435e-08, 'max_delta_step': 4}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  16%|█▌        | 8/50 [02:22<10:34, 15.10s/it]

[I 2025-12-01 19:01:23,859] Trial 5 finished with value: 0.6108695652173912 and parameters: {'max_depth': 4, 'learning_rate': 0.03844229267190438, 'n_estimators': 1244, 'subsample': 0.9765847016186711, 'colsample_bytree': 0.667549814564908, 'min_child_weight': 4, 'gamma': 4.173294170490456, 'reg_alpha': 0.003884151257495568, 'reg_lambda': 0.00026892989400470355, 'max_delta_step': 9}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  18%|█▊        | 9/50 [02:35<09:39, 14.14s/it]

[I 2025-12-01 19:01:35,899] Trial 8 finished with value: 0.6141304347826086 and parameters: {'max_depth': 8, 'learning_rate': 0.14421584958709985, 'n_estimators': 1123, 'subsample': 0.5923450056060078, 'colsample_bytree': 0.8739551774102872, 'min_child_weight': 2, 'gamma': 0.2438827131906085, 'reg_alpha': 1.6695306681691996e-06, 'reg_lambda': 0.016598839070847346, 'max_delta_step': 6}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  20%|██        | 10/50 [03:09<13:35, 20.38s/it]

[I 2025-12-01 19:02:10,250] Trial 12 finished with value: 0.6016304347826087 and parameters: {'max_depth': 8, 'learning_rate': 0.11364252229638837, 'n_estimators': 266, 'subsample': 0.7287890859171371, 'colsample_bytree': 0.8092529509098673, 'min_child_weight': 1, 'gamma': 0.8738055887851653, 'reg_alpha': 0.21755477499732578, 'reg_lambda': 0.10147751592314903, 'max_delta_step': 6}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  22%|██▏       | 11/50 [03:12<09:50, 15.14s/it]

[I 2025-12-01 19:02:13,502] Trial 10 finished with value: 0.6233695652173913 and parameters: {'max_depth': 6, 'learning_rate': 0.06812088501293717, 'n_estimators': 844, 'subsample': 0.5647202195295655, 'colsample_bytree': 0.5882453316126465, 'min_child_weight': 3, 'gamma': 2.807367906859577, 'reg_alpha': 2.2995576820640934e-05, 'reg_lambda': 0.00581450610651896, 'max_delta_step': 8}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  24%|██▍       | 12/50 [03:16<07:19, 11.57s/it]

[I 2025-12-01 19:02:16,922] Trial 9 finished with value: 0.6266304347826087 and parameters: {'max_depth': 4, 'learning_rate': 0.05042064315978568, 'n_estimators': 925, 'subsample': 0.9050089060852361, 'colsample_bytree': 0.5468079898934171, 'min_child_weight': 1, 'gamma': 1.0378962557419036, 'reg_alpha': 1.1275442225577239e-08, 'reg_lambda': 0.003666996050273919, 'max_delta_step': 6}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  26%|██▌       | 13/50 [03:29<07:32, 12.23s/it]

[I 2025-12-01 19:02:30,673] Trial 11 finished with value: 0.5548913043478261 and parameters: {'max_depth': 9, 'learning_rate': 0.16752463039436152, 'n_estimators': 1255, 'subsample': 0.65439112640614, 'colsample_bytree': 0.6925787114753497, 'min_child_weight': 6, 'gamma': 2.9228743847191896, 'reg_alpha': 1.0745374234109144, 'reg_lambda': 1.8711904207765277e-05, 'max_delta_step': 2}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  28%|██▊       | 14/50 [04:31<16:20, 27.24s/it]

[I 2025-12-01 19:03:32,603] Trial 14 finished with value: 0.6326086956521739 and parameters: {'max_depth': 10, 'learning_rate': 0.06481835762836603, 'n_estimators': 1454, 'subsample': 0.6752039044947198, 'colsample_bytree': 0.5469544718841111, 'min_child_weight': 4, 'gamma': 1.8955846693168588, 'reg_alpha': 2.12395282718252e-05, 'reg_lambda': 0.007085737221659904, 'max_delta_step': 1}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  30%|███       | 15/50 [04:45<13:33, 23.24s/it]

[I 2025-12-01 19:03:46,567] Trial 13 finished with value: 0.6266304347826087 and parameters: {'max_depth': 9, 'learning_rate': 0.06693374527914468, 'n_estimators': 1487, 'subsample': 0.6945138921538675, 'colsample_bytree': 0.9912311259023193, 'min_child_weight': 5, 'gamma': 1.7185563526633998, 'reg_alpha': 2.2021323204627688e-05, 'reg_lambda': 3.581839681646238, 'max_delta_step': 0}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  32%|███▏      | 16/50 [05:19<14:57, 26.39s/it]

[I 2025-12-01 19:04:20,278] Trial 15 finished with value: 0.6543478260869565 and parameters: {'max_depth': 10, 'learning_rate': 0.02348663119211318, 'n_estimators': 1477, 'subsample': 0.9920638242508147, 'colsample_bytree': 0.9535626484800538, 'min_child_weight': 6, 'gamma': 1.5416237094322782, 'reg_alpha': 1.1188508323444832e-08, 'reg_lambda': 6.382736538188482, 'max_delta_step': 1}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  34%|███▍      | 17/50 [05:20<10:20, 18.81s/it]

[I 2025-12-01 19:04:21,456] Trial 16 finished with value: 0.6016304347826087 and parameters: {'max_depth': 10, 'learning_rate': 0.024616410818182166, 'n_estimators': 1469, 'subsample': 0.991040848432493, 'colsample_bytree': 0.5072412712036886, 'min_child_weight': 4, 'gamma': 1.5879062403902884, 'reg_alpha': 1.70573602823254e-08, 'reg_lambda': 4.3603424967268305, 'max_delta_step': 0}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  36%|███▌      | 18/50 [06:37<19:24, 36.39s/it]

[I 2025-12-01 19:05:38,782] Trial 18 finished with value: 0.6451086956521739 and parameters: {'max_depth': 10, 'learning_rate': 0.02149798124797115, 'n_estimators': 1465, 'subsample': 0.7581626211812625, 'colsample_bytree': 0.9095411530028056, 'min_child_weight': 4, 'gamma': 2.018683162653956, 'reg_alpha': 9.541609627344171e-07, 'reg_lambda': 0.17458149636546413, 'max_delta_step': 2}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  38%|███▊      | 19/50 [06:41<13:43, 26.55s/it]

[I 2025-12-01 19:05:42,409] Trial 17 finished with value: 0.6233695652173913 and parameters: {'max_depth': 10, 'learning_rate': 0.023898811927618724, 'n_estimators': 1497, 'subsample': 0.6993165926905986, 'colsample_bytree': 0.9987444189016836, 'min_child_weight': 4, 'gamma': 2.1445131668602926, 'reg_alpha': 4.187995461148411e-05, 'reg_lambda': 4.619909651526417, 'max_delta_step': 0}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  40%|████      | 20/50 [06:50<10:34, 21.16s/it]

[I 2025-12-01 19:05:50,996] Trial 20 finished with value: 0.5548913043478261 and parameters: {'max_depth': 10, 'learning_rate': 0.018779345893936605, 'n_estimators': 1316, 'subsample': 0.7963519147097693, 'colsample_bytree': 0.9295672959814776, 'min_child_weight': 7, 'gamma': 2.2085992742426925, 'reg_alpha': 6.130079669855033e-07, 'reg_lambda': 0.29873852455440336, 'max_delta_step': 3}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  42%|████▏     | 21/50 [06:55<08:00, 16.56s/it]

[I 2025-12-01 19:05:56,831] Trial 21 pruned.

Best trial: 2. Best value: 0.654348:  44%|████▍     | 22/50 [07:01<06:11, 13.26s/it]

[I 2025-12-01 19:06:02,410] Trial 19 finished with value: 0.5081521739130435 and parameters: {'max_depth': 10, 'learning_rate': 0.022169394191003628, 'n_estimators': 1362, 'subsample': 0.7912277165636296, 'colsample_bytree': 0.9210622139095321, 'min_child_weight': 7, 'gamma': 1.0843737394710515, 'reg_alpha': 4.0528946804770503e-07, 'reg_lambda': 7.957514668153933, 'max_delta_step': 3}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  46%|████▌     | 23/50 [07:11<05:28, 12.17s/it]

[I 2025-12-01 19:06:12,031] Trial 24 pruned.

Best trial: 2. Best value: 0.654348:  48%|████▊     | 24/50 [07:31<06:23, 14.77s/it]

[I 2025-12-01 19:06:32,854] Trial 23 finished with value: 0.6233695652173913 and parameters: {'max_depth': 9, 'learning_rate': 0.010847622855063023, 'n_estimators': 271, 'subsample': 0.9175720778613212, 'colsample_bytree': 0.9390550211406713, 'min_child_weight': 7, 'gamma': 1.2071547981953168, 'reg_alpha': 2.1217504097587073e-07, 'reg_lambda': 0.04422049049914656, 'max_delta_step': 4}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  50%|█████     | 25/50 [08:23<10:43, 25.74s/it]

[I 2025-12-01 19:07:24,197] Trial 25 finished with value: 0.6326086956521739 and parameters: {'max_depth': 9, 'learning_rate': 0.03487329373130643, 'n_estimators': 1096, 'subsample': 0.9175843514702551, 'colsample_bytree': 0.8850846988308195, 'min_child_weight': 5, 'gamma': 1.3386198506475493, 'reg_alpha': 2.5014574725801176e-06, 'reg_lambda': 0.07279703402885, 'max_delta_step': 2}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  52%|█████▏    | 26/50 [08:24<07:21, 18.40s/it]

[I 2025-12-01 19:07:25,460] Trial 22 finished with value: 0.567391304347826 and parameters: {'max_depth': 9, 'learning_rate': 0.010860684459085916, 'n_estimators': 1336, 'subsample': 0.7954127691374808, 'colsample_bytree': 0.9357934486556437, 'min_child_weight': 7, 'gamma': 0.007762011567284954, 'reg_alpha': 3.0769017365164846e-07, 'reg_lambda': 0.31269521388048005, 'max_delta_step': 4}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  54%|█████▍    | 27/50 [08:37<06:24, 16.71s/it]

[I 2025-12-01 19:07:38,237] Trial 26 finished with value: 0.6483695652173913 and parameters: {'max_depth': 9, 'learning_rate': 0.0418509321739257, 'n_estimators': 1080, 'subsample': 0.6378199641333187, 'colsample_bytree': 0.8826972433227804, 'min_child_weight': 3, 'gamma': 3.7093373633219615, 'reg_alpha': 3.3634602555817312e-06, 'reg_lambda': 0.405537829777501, 'max_delta_step': 2}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 2. Best value: 0.654348:  56%|█████▌    | 28/50 [09:02<07:06, 19.36s/it]

[I 2025-12-01 19:08:03,792] Trial 27 finished with value: 0.6483695652173913 and parameters: {'max_depth': 7, 'learning_rate': 0.034816966803256084, 'n_estimators': 1118, 'subsample': 0.6296425743680496, 'colsample_bytree': 0.8656940045539419, 'min_child_weight': 3, 'gamma': 0.5460020439825455, 'reg_alpha': 2.5954286580767244e-06, 'reg_lambda': 0.5687605399769476, 'max_delta_step': 2}. Best is trial 2 with value: 0.6543478260869565.

Best trial: 29. Best value: 0.679348:  58%|█████▊    | 29/50 [09:22<06:46, 19.35s/it]

[I 2025-12-01 19:08:23,112] Trial 29 finished with value: 0.6793478260869565 and parameters: {'max_depth': 7, 'learning_rate': 0.04728699408443922, 'n_estimators': 641, 'subsample': 0.6340046780458677, 'colsample_bytree': 0.8348121437108709, 'min_child_weight': 3, 'gamma': 0.5964043489930837, 'reg_alpha': 0.0004826528046407034, 'reg_lambda': 0.5095160541167386, 'max_delta_step': 1}. Best is trial 29 with value: 0.6793478260869565.

Best trial: 29. Best value: 0.679348:  60%|██████    | 30/50 [09:50<07:19, 21.99s/it]

[I 2025-12-01 19:08:51,261] Trial 31 finished with value: 0.6608695652173913 and parameters: {'max_depth': 8, 'learning_rate': 0.05165783087031783, 'n_estimators': 637, 'subsample': 0.5016388205461013, 'colsample_bytree': 0.8226490791803801, 'min_child_weight': 3, 'gamma': 3.6492464511378024, 'reg_alpha': 0.00045999732149403085, 'reg_lambda': 0.0010695437075932753, 'max_delta_step': 1}. Best is trial 29 with value: 0.6793478260869565.

Best trial: 29. Best value: 0.679348:  62%|██████▏   | 31/50 [09:57<05:30, 17.40s/it]

[I 2025-12-01 19:08:57,967] Trial 30 finished with value: 0.6233695652173913 and parameters: {'max_depth': 7, 'learning_rate': 0.05011943904026855, 'n_estimators': 1001, 'subsample': 0.6294748049048685, 'colsample_bytree': 0.8371703062650176, 'min_child_weight': 3, 'gamma': 3.7249149081276474, 'reg_alpha': 0.0002414446353906895, 'reg_lambda': 1.1253484847868853, 'max_delta_step': 1}. Best is trial 29 with value: 0.6793478260869565.

Best trial: 29. Best value: 0.679348:  64%|██████▍   | 32/50 [09:57<03:43, 12.41s/it]

[I 2025-12-01 19:08:58,735] Trial 33 pruned.

Best trial: 29. Best value: 0.679348:  66%|██████▌   | 33/50 [10:04<02:59, 10.59s/it]

[I 2025-12-01 19:09:05,057] Trial 28 finished with value: 0.6358695652173914 and parameters: {'max_depth': 7, 'learning_rate': 0.0459826450944808, 'n_estimators': 1402, 'subsample': 0.6390367347506412, 'colsample_bytree': 0.8281177847601151, 'min_child_weight': 3, 'gamma': 0.6065927719463751, 'reg_alpha': 0.00026084360159869867, 'reg_lambda': 0.8022478214079514, 'max_delta_step': 1}. Best is trial 29 with value: 0.6793478260869565.

Best trial: 29. Best value: 0.679348:  68%|██████▊   | 34/50 [10:10<02:28,  9.30s/it]

[I 2025-12-01 19:09:11,363] Trial 36 pruned.

Best trial: 29. Best value: 0.679348:  70%|███████   | 35/50 [10:18<02:13,  8.91s/it]

[I 2025-12-01 19:09:19,376] Trial 32 finished with value: 0.6576086956521738 and parameters: {'max_depth': 7, 'learning_rate': 0.05077051883288559, 'n_estimators': 606, 'subsample': 0.5075857405962034, 'colsample_bytree': 0.820493974665072, 'min_child_weight': 2, 'gamma': 2.5507120608972595, 'reg_alpha': 0.0002360248075917653, 'reg_lambda': 0.0008775053957742843, 'max_delta_step': 1}. Best is trial 29 with value: 0.6793478260869565.

Best trial: 29. Best value: 0.679348:  72%|███████▏  | 36/50 [10:46<03:26, 14.73s/it]

[I 2025-12-01 19:09:47,668] Trial 34 finished with value: 0.6701086956521739 and parameters: {'max_depth': 8, 'learning_rate': 0.07945813979447669, 'n_estimators': 602, 'subsample': 0.5183036877090897, 'colsample_bytree': 0.725559237248947, 'min_child_weight': 2, 'gamma': 2.563997750040908, 'reg_alpha': 0.0003955749480907222, 'reg_lambda': 0.0005424057738864043, 'max_delta_step': 1}. Best is trial 29 with value: 0.6793478260869565.

Best trial: 29. Best value: 0.679348:  74%|███████▍  | 37/50 [11:01<03:09, 14.60s/it]

[I 2025-12-01 19:10:01,966] Trial 38 finished with value: 0.5798913043478261 and parameters: {'max_depth': 6, 'learning_rate': 0.07792920618738396, 'n_estimators': 506, 'subsample': 0.5478086590610022, 'colsample_bytree': 0.7018309111442986, 'min_child_weight': 2, 'gamma': 2.454143231840707, 'reg_alpha': 0.02503092451733502, 'reg_lambda': 0.0009119454609286363, 'max_delta_step': 0}. Best is trial 29 with value: 0.6793478260869565.

Best trial: 29. Best value: 0.679348:  76%|███████▌  | 38/50 [11:08<02:29, 12.47s/it]

[I 2025-12-01 19:10:09,457] Trial 40 pruned.

Best trial: 29. Best value: 0.679348:  78%|███████▊  | 39/50 [11:14<01:55, 10.53s/it]

[I 2025-12-01 19:10:15,466] Trial 35 finished with value: 0.6391304347826088 and parameters: {'max_depth': 8, 'learning_rate': 0.029591078374942275, 'n_estimators': 630, 'subsample': 0.5449905266718201, 'colsample_bytree': 0.7440247327490076, 'min_child_weight': 2, 'gamma': 0.7223366152160657, 'reg_alpha': 0.0011125111188677933, 'reg_lambda': 0.00023630965349502988, 'max_delta_step': 1}. Best is trial 29 with value: 0.6793478260869565.

Best trial: 29. Best value: 0.679348:  80%|████████  | 40/50 [11:23<01:39,  9.99s/it]

[I 2025-12-01 19:10:24,185] Trial 42 pruned.

Best trial: 37. Best value: 0.68587:  82%|████████▏ | 41/50 [11:25<01:08,  7.65s/it]

[I 2025-12-01 19:10:26,376] Trial 37 finished with value: 0.6858695652173913 and parameters: {'max_depth': 8, 'learning_rate': 0.014934020884615044, 'n_estimators': 498, 'subsample': 0.5425228485330207, 'colsample_bytree': 0.7203472136222085, 'min_child_weight': 2, 'gamma': 2.4264752014179916, 'reg_alpha': 0.0013313576764468758, 'reg_lambda': 0.0010605461192090006, 'max_delta_step': 0}. Best is trial 37 with value: 0.6858695652173913.

Best trial: 37. Best value: 0.68587:  84%|████████▍ | 42/50 [11:31<00:56,  7.04s/it]

[I 2025-12-01 19:10:32,001] Trial 39 finished with value: 0.6266304347826087 and parameters: {'max_depth': 6, 'learning_rate': 0.08337990287078403, 'n_estimators': 510, 'subsample': 0.5483951469225176, 'colsample_bytree': 0.7214784702134518, 'min_child_weight': 2, 'gamma': 3.2232356659748067, 'reg_alpha': 0.0013928490366319642, 'reg_lambda': 0.0006520224654245634, 'max_delta_step': 0}. Best is trial 37 with value: 0.6858695652173913.

Best trial: 37. Best value: 0.68587:  86%|████████▌ | 43/50 [11:36<00:45,  6.47s/it]

[I 2025-12-01 19:10:37,138] Trial 44 pruned.

Best trial: 37. Best value: 0.68587:  88%|████████▊ | 44/50 [11:36<00:27,  4.62s/it]

[I 2025-12-01 19:10:37,451] Trial 43 pruned.

Best trial: 37. Best value: 0.68587:  90%|█████████ | 45/50 [11:41<00:23,  4.61s/it]

[I 2025-12-01 19:10:42,040] Trial 47 pruned.

Best trial: 37. Best value: 0.68587:  92%|█████████▏| 46/50 [11:51<00:25,  6.29s/it]

[I 2025-12-01 19:10:52,251] Trial 45 pruned.

Best trial: 37. Best value: 0.68587:  94%|█████████▍| 47/50 [11:54<00:15,  5.22s/it]

[I 2025-12-01 19:10:54,962] Trial 48 pruned.

Best trial: 37. Best value: 0.68587:  96%|█████████▌| 48/50 [12:05<00:13,  6.97s/it]

[I 2025-12-01 19:11:06,031] Trial 41 finished with value: 0.6391304347826088 and parameters: {'max_depth': 5, 'learning_rate': 0.08929834749976504, 'n_estimators': 723, 'subsample': 0.5386833262313531, 'colsample_bytree': 0.7345691178861369, 'min_child_weight': 2, 'gamma': 4.00599212030942, 'reg_alpha': 0.0014732361858677343, 'reg_lambda': 7.108545991103692e-05, 'max_delta_step': 0}. Best is trial 37 with value: 0.6858695652173913.

Best trial: 46. Best value: 0.695109:  98%|█████████▊| 49/50 [12:44<00:16, 16.71s/it]

[I 2025-12-01 19:11:45,453] Trial 46 finished with value: 0.6951086956521739 and parameters: {'max_depth': 7, 'learning_rate': 0.014028071730911373, 'n_estimators': 716, 'subsample': 0.5954859071405089, 'colsample_bytree': 0.7594725205183814, 'min_child_weight': 3, 'gamma': 2.713016966159256, 'reg_alpha': 0.019584767032178495, 'reg_lambda': 1.6641015007437898e-06, 'max_delta_step': 1}. Best is trial 46 with value: 0.6951086956521739.

Best trial: 46. Best value: 0.695109: 100%|██████████| 50/50 [12:45<00:00, 15.31s/it]

[I 2025-12-01 19:11:46,463] Trial 49 finished with value: 0.6733695652173912 and parameters: {'max_depth': 8, 'learning_rate': 0.01442937484907193, 'n_estimators': 533, 'subsample': 0.5274299087796173, 'colsample_bytree': 0.765118351165204, 'min_child_weight': 2, 'gamma': 3.634863210842068, 'reg_alpha': 0.005569808180816247, 'reg_lambda': 0.014557657319960553, 'max_delta_step': 10}. Best is trial 46 with value: 0.6951086956521739.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 19:11:52,255] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 66, Test size: 17
Using Leave-One-Out CV with 66 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.116585:   2%|▏         | 1/50 [00:28<23:25, 28.69s/it]

[I 2025-12-01 19:12:20,937] Trial 3 finished with value: 0.11658536585365853 and parameters: {'max_depth': 4, 'learning_rate': 0.19241970609127826, 'n_estimators': 447, 'subsample': 0.5413121978100478, 'colsample_bytree': 0.9597184094481922, 'min_child_weight': 10, 'gamma': 1.441554889208534, 'reg_alpha': 0.722416782226003, 'reg_lambda': 2.846157344531359e-05, 'max_delta_step': 2}. Best is trial 3 with value: 0.11658536585365853.

Best trial: 1. Best value: 0.464878:   4%|▍         | 2/50 [00:54<21:22, 26.72s/it]

[I 2025-12-01 19:12:46,275] Trial 1 finished with value: 0.4648780487804878 and parameters: {'max_depth': 5, 'learning_rate': 0.015375367010943773, 'n_estimators': 816, 'subsample': 0.8599177935801601, 'colsample_bytree': 0.7971276562996894, 'min_child_weight': 9, 'gamma': 3.4552884699633477, 'reg_alpha': 4.107937873890534e-08, 'reg_lambda': 0.0007133986524667662, 'max_delta_step': 5}. Best is trial 1 with value: 0.4648780487804878.

Best trial: 2. Best value: 0.529268:   6%|▌         | 3/50 [01:26<23:05, 29.47s/it]

[I 2025-12-01 19:13:19,015] Trial 2 finished with value: 0.5292682926829269 and parameters: {'max_depth': 10, 'learning_rate': 0.01300312249067593, 'n_estimators': 913, 'subsample': 0.8782876250630777, 'colsample_bytree': 0.5263721908950151, 'min_child_weight': 4, 'gamma': 3.9939565645325086, 'reg_alpha': 1.6151010613215277e-07, 'reg_lambda': 0.14820123557819015, 'max_delta_step': 6}. Best is trial 2 with value: 0.5292682926829269.

Best trial: 2. Best value: 0.529268:   8%|▊         | 4/50 [01:29<14:29, 18.91s/it]

[I 2025-12-01 19:13:21,740] Trial 0 finished with value: 0.4273170731707317 and parameters: {'max_depth': 10, 'learning_rate': 0.01680716253513766, 'n_estimators': 1472, 'subsample': 0.5416305436784359, 'colsample_bytree': 0.9117292902891894, 'min_child_weight': 7, 'gamma': 3.5448929938068585, 'reg_alpha': 1.1719820924741426e-05, 'reg_lambda': 0.0536150519691777, 'max_delta_step': 3}. Best is trial 2 with value: 0.5292682926829269.

Best trial: 2. Best value: 0.529268:  10%|█         | 5/50 [02:01<17:41, 23.59s/it]

[I 2025-12-01 19:13:53,636] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.016414665636634164, 'n_estimators': 1312, 'subsample': 0.8754285894109614, 'colsample_bytree': 0.5034841191334223, 'min_child_weight': 10, 'gamma': 1.7423182526765413, 'reg_alpha': 9.244228387564382e-08, 'reg_lambda': 0.3437823814838418, 'max_delta_step': 4}. Best is trial 2 with value: 0.5292682926829269.

Best trial: 2. Best value: 0.529268:  12%|█▏        | 6/50 [02:04<12:05, 16.49s/it]

[I 2025-12-01 19:13:56,331] Trial 4 finished with value: 0.5248780487804878 and parameters: {'max_depth': 8, 'learning_rate': 0.041803923520071444, 'n_estimators': 1063, 'subsample': 0.6805290789777051, 'colsample_bytree': 0.9100744035647119, 'min_child_weight': 4, 'gamma': 4.038741447498616, 'reg_alpha': 0.011384406648578255, 'reg_lambda': 2.4397455370400074, 'max_delta_step': 7}. Best is trial 2 with value: 0.5292682926829269.

Best trial: 2. Best value: 0.529268:  14%|█▍        | 7/50 [02:40<16:34, 23.12s/it]

[I 2025-12-01 19:14:33,109] Trial 8 finished with value: 0.32926829268292684 and parameters: {'max_depth': 8, 'learning_rate': 0.238308730465209, 'n_estimators': 714, 'subsample': 0.508268883711221, 'colsample_bytree': 0.5389434222943563, 'min_child_weight': 8, 'gamma': 2.5176575884031065, 'reg_alpha': 1.57983519400751e-08, 'reg_lambda': 0.010048132419694687, 'max_delta_step': 8}. Best is trial 2 with value: 0.5292682926829269.

Best trial: 2. Best value: 0.529268:  16%|█▌        | 8/50 [02:41<11:12, 16.01s/it]

[I 2025-12-01 19:14:33,898] Trial 7 finished with value: 0.08878048780487804 and parameters: {'max_depth': 6, 'learning_rate': 0.14179315692953712, 'n_estimators': 1354, 'subsample': 0.8166991219122522, 'colsample_bytree': 0.7002404309665178, 'min_child_weight': 10, 'gamma': 0.6317623840760123, 'reg_alpha': 0.013838188340937599, 'reg_lambda': 5.86732570133636, 'max_delta_step': 4}. Best is trial 2 with value: 0.5292682926829269.

Best trial: 2. Best value: 0.529268:  18%|█▊        | 9/50 [02:42<07:47, 11.40s/it]

[I 2025-12-01 19:14:35,159] Trial 9 finished with value: 0.45268292682926825 and parameters: {'max_depth': 8, 'learning_rate': 0.01572439964500535, 'n_estimators': 586, 'subsample': 0.9813908417209549, 'colsample_bytree': 0.5530081414707477, 'min_child_weight': 9, 'gamma': 4.516517668400958, 'reg_alpha': 0.3330872527202427, 'reg_lambda': 1.0119059541061441e-07, 'max_delta_step': 4}. Best is trial 2 with value: 0.5292682926829269.

Best trial: 6. Best value: 0.532683:  20%|██        | 10/50 [02:44<05:35,  8.39s/it]

[I 2025-12-01 19:14:36,826] Trial 6 finished with value: 0.5326829268292683 and parameters: {'max_depth': 4, 'learning_rate': 0.07651155089150825, 'n_estimators': 1363, 'subsample': 0.5835591286600966, 'colsample_bytree': 0.7991473024889509, 'min_child_weight': 7, 'gamma': 2.7556694543391416, 'reg_alpha': 6.027303238826421e-05, 'reg_lambda': 0.6135885696417633, 'max_delta_step': 10}. Best is trial 6 with value: 0.5326829268292683.

Best trial: 13. Best value: 0.618049:  22%|██▏       | 11/50 [03:18<10:30, 16.17s/it]

[I 2025-12-01 19:15:10,617] Trial 13 finished with value: 0.6180487804878049 and parameters: {'max_depth': 3, 'learning_rate': 0.07836873573850524, 'n_estimators': 215, 'subsample': 0.6844443383404349, 'colsample_bytree': 0.7516213713697709, 'min_child_weight': 1, 'gamma': 2.5804528026377658, 'reg_alpha': 2.1989594418591154e-05, 'reg_lambda': 1.774287479637663e-05, 'max_delta_step': 10}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  24%|██▍       | 12/50 [03:21<07:48, 12.32s/it]

[I 2025-12-01 19:15:14,148] Trial 11 finished with value: 0.5326829268292683 and parameters: {'max_depth': 6, 'learning_rate': 0.0259374029044707, 'n_estimators': 390, 'subsample': 0.5063935319406061, 'colsample_bytree': 0.6238646473712524, 'min_child_weight': 4, 'gamma': 0.7364508858758945, 'reg_alpha': 5.56286766499796e-07, 'reg_lambda': 2.1208592316369288e-08, 'max_delta_step': 9}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  26%|██▌       | 13/50 [03:23<05:31,  8.95s/it]

[I 2025-12-01 19:15:15,342] Trial 12 finished with value: 0.5126829268292683 and parameters: {'max_depth': 4, 'learning_rate': 0.11123990581441533, 'n_estimators': 586, 'subsample': 0.795465684468716, 'colsample_bytree': 0.6048242112732432, 'min_child_weight': 6, 'gamma': 0.5323025382761709, 'reg_alpha': 0.0015162103530003328, 'reg_lambda': 0.0001678395786560384, 'max_delta_step': 7}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  28%|██▊       | 14/50 [03:50<08:47, 14.66s/it]

[I 2025-12-01 19:15:43,181] Trial 10 finished with value: 0.5248780487804878 and parameters: {'max_depth': 3, 'learning_rate': 0.2819620540180146, 'n_estimators': 1274, 'subsample': 0.6821981922998237, 'colsample_bytree': 0.5717649459598539, 'min_child_weight': 5, 'gamma': 1.3174833015497018, 'reg_alpha': 0.007393659051225948, 'reg_lambda': 1.1228311633405654, 'max_delta_step': 5}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  30%|███       | 15/50 [03:57<07:12, 12.36s/it]

[I 2025-12-01 19:15:50,209] Trial 15 finished with value: 0.5302439024390244 and parameters: {'max_depth': 3, 'learning_rate': 0.08870588341229277, 'n_estimators': 240, 'subsample': 0.6589714870051453, 'colsample_bytree': 0.8007555655550846, 'min_child_weight': 1, 'gamma': 2.504696506300423, 'reg_alpha': 6.781008148775608e-05, 'reg_lambda': 6.494770368353376e-06, 'max_delta_step': 10}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  32%|███▏      | 16/50 [04:01<05:32,  9.77s/it]

[I 2025-12-01 19:15:53,987] Trial 17 pruned.

Best trial: 13. Best value: 0.618049:  34%|███▍      | 17/50 [04:04<04:17,  7.80s/it]

[I 2025-12-01 19:15:57,206] Trial 16 finished with value: 0.5502439024390244 and parameters: {'max_depth': 3, 'learning_rate': 0.062329207613382474, 'n_estimators': 267, 'subsample': 0.651716078014828, 'colsample_bytree': 0.7855944228354492, 'min_child_weight': 1, 'gamma': 2.5819722447613995, 'reg_alpha': 5.971298025541766e-06, 'reg_lambda': 3.7794772155740715e-06, 'max_delta_step': 10}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  36%|███▌      | 18/50 [04:12<04:06,  7.71s/it]

[I 2025-12-01 19:16:04,713] Trial 14 finished with value: 0.578048780487805 and parameters: {'max_depth': 3, 'learning_rate': 0.08205839041673875, 'n_estimators': 409, 'subsample': 0.6697147052141258, 'colsample_bytree': 0.7488592707331353, 'min_child_weight': 1, 'gamma': 2.594401073862217, 'reg_alpha': 2.4884986783113613e-05, 'reg_lambda': 2.6546986661670495e-06, 'max_delta_step': 10}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  38%|███▊      | 19/50 [05:00<10:10, 19.69s/it]

[I 2025-12-01 19:16:52,305] Trial 20 finished with value: 0.5502439024390244 and parameters: {'max_depth': 5, 'learning_rate': 0.04106387983601501, 'n_estimators': 382, 'subsample': 0.7472102372909449, 'colsample_bytree': 0.7110166595901486, 'min_child_weight': 2, 'gamma': 1.856982229742692, 'reg_alpha': 1.3483993897361077e-06, 'reg_lambda': 2.28039670200529e-06, 'max_delta_step': 8}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  40%|████      | 20/50 [05:08<08:07, 16.26s/it]

[I 2025-12-01 19:17:00,565] Trial 21 finished with value: 0.5902439024390245 and parameters: {'max_depth': 5, 'learning_rate': 0.041277929549412645, 'n_estimators': 441, 'subsample': 0.7204489505681978, 'colsample_bytree': 0.7068217248528731, 'min_child_weight': 2, 'gamma': 1.9442975564568297, 'reg_alpha': 1.9750264890329585e-06, 'reg_lambda': 0.0012804765872230753, 'max_delta_step': 8}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  42%|████▏     | 21/50 [05:34<09:14, 19.11s/it]

[I 2025-12-01 19:17:26,328] Trial 19 finished with value: 0.5936585365853658 and parameters: {'max_depth': 4, 'learning_rate': 0.05010564133595631, 'n_estimators': 1022, 'subsample': 0.6095332708656834, 'colsample_bytree': 0.6821518731868326, 'min_child_weight': 2, 'gamma': 3.0994566233151004, 'reg_alpha': 4.161608222368755e-06, 'reg_lambda': 0.003396874797327015, 'max_delta_step': 9}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  44%|████▍     | 22/50 [05:50<08:35, 18.42s/it]

[I 2025-12-01 19:17:43,144] Trial 18 finished with value: 0.5302439024390244 and parameters: {'max_depth': 3, 'learning_rate': 0.0633177061468929, 'n_estimators': 1084, 'subsample': 0.6096646497858625, 'colsample_bytree': 0.691540968331154, 'min_child_weight': 1, 'gamma': 3.0684730769735147, 'reg_alpha': 6.731026740647826e-06, 'reg_lambda': 1.7995079170613524e-06, 'max_delta_step': 0}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  46%|████▌     | 23/50 [06:03<07:29, 16.64s/it]

[I 2025-12-01 19:17:55,639] Trial 22 finished with value: 0.5858536585365853 and parameters: {'max_depth': 7, 'learning_rate': 0.039372385578718916, 'n_estimators': 552, 'subsample': 0.745435637820394, 'colsample_bytree': 0.862560742343806, 'min_child_weight': 3, 'gamma': 4.993816027549051, 'reg_alpha': 0.000269024333547396, 'reg_lambda': 0.0005744568505422836, 'max_delta_step': 0}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  48%|████▊     | 24/50 [06:10<05:56, 13.72s/it]

[I 2025-12-01 19:18:02,551] Trial 23 finished with value: 0.5414634146341464 and parameters: {'max_depth': 7, 'learning_rate': 0.030845734884613868, 'n_estimators': 576, 'subsample': 0.731760628401001, 'colsample_bytree': 0.668970702522066, 'min_child_weight': 3, 'gamma': 3.267515452253419, 'reg_alpha': 0.00030865018810303884, 'reg_lambda': 0.002918835110996942, 'max_delta_step': 0}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  50%|█████     | 25/50 [07:02<10:31, 25.24s/it]

[I 2025-12-01 19:18:54,659] Trial 24 finished with value: 0.5658536585365854 and parameters: {'max_depth': 4, 'learning_rate': 0.041869561825963277, 'n_estimators': 1037, 'subsample': 0.7329519120085508, 'colsample_bytree': 0.6701657885636989, 'min_child_weight': 3, 'gamma': 3.3019289752282344, 'reg_alpha': 2.621658563350262e-06, 'reg_lambda': 0.0038299280661741675, 'max_delta_step': 8}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  52%|█████▏    | 26/50 [07:15<08:35, 21.50s/it]

[I 2025-12-01 19:19:07,427] Trial 25 finished with value: 0.578048780487805 and parameters: {'max_depth': 4, 'learning_rate': 0.039949991342586394, 'n_estimators': 1031, 'subsample': 0.7310694452957379, 'colsample_bytree': 0.6513924615296411, 'min_child_weight': 3, 'gamma': 2.0520788907764533, 'reg_alpha': 0.00045901065509842303, 'reg_lambda': 0.0025507702587789496, 'max_delta_step': 8}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  54%|█████▍    | 27/50 [07:17<06:05, 15.89s/it]

[I 2025-12-01 19:19:10,238] Trial 28 pruned.

Best trial: 13. Best value: 0.618049:  56%|█████▌    | 28/50 [07:29<05:22, 14.65s/it]

[I 2025-12-01 19:19:22,000] Trial 29 pruned.

Best trial: 13. Best value: 0.618049:  58%|█████▊    | 29/50 [07:33<03:59, 11.39s/it]

[I 2025-12-01 19:19:25,777] Trial 30 pruned.

Best trial: 13. Best value: 0.618049:  60%|██████    | 30/50 [07:39<03:15,  9.77s/it]

[I 2025-12-01 19:19:31,777] Trial 26 finished with value: 0.5536585365853659 and parameters: {'max_depth': 4, 'learning_rate': 0.02635459150885705, 'n_estimators': 1062, 'subsample': 0.7125085506524795, 'colsample_bytree': 0.6550226041211564, 'min_child_weight': 3, 'gamma': 2.0531183836244327, 'reg_alpha': 8.794684040454528e-07, 'reg_lambda': 0.007052412318486234, 'max_delta_step': 8}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  62%|██████▏   | 31/50 [07:45<02:42,  8.55s/it]

[I 2025-12-01 19:19:37,483] Trial 32 pruned.

Best trial: 13. Best value: 0.618049:  64%|██████▍   | 32/50 [07:51<02:23,  7.97s/it]

[I 2025-12-01 19:19:44,078] Trial 33 pruned.

Best trial: 13. Best value: 0.618049:  66%|██████▌   | 33/50 [08:00<02:18,  8.13s/it]

[I 2025-12-01 19:19:52,593] Trial 27 finished with value: 0.5658536585365854 and parameters: {'max_depth': 4, 'learning_rate': 0.02437001227182322, 'n_estimators': 1052, 'subsample': 0.6995129057623521, 'colsample_bytree': 0.6494617715428553, 'min_child_weight': 2, 'gamma': 2.0468423036121153, 'reg_alpha': 1.198218861921944e-06, 'reg_lambda': 0.00012033224355296084, 'max_delta_step': 8}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  68%|██████▊   | 34/50 [08:14<02:37,  9.86s/it]

[I 2025-12-01 19:20:06,503] Trial 35 pruned.

Best trial: 13. Best value: 0.618049:  70%|███████   | 35/50 [08:17<01:59,  7.98s/it]

[I 2025-12-01 19:20:10,099] Trial 36 pruned.

Best trial: 13. Best value: 0.618049:  72%|███████▏  | 36/50 [08:25<01:50,  7.90s/it]

[I 2025-12-01 19:20:17,816] Trial 37 pruned.

Best trial: 13. Best value: 0.618049:  74%|███████▍  | 37/50 [08:35<01:52,  8.63s/it]

[I 2025-12-01 19:20:28,135] Trial 38 pruned.

Best trial: 13. Best value: 0.618049:  76%|███████▌  | 38/50 [08:43<01:39,  8.29s/it]

[I 2025-12-01 19:20:35,628] Trial 39 pruned.

Best trial: 13. Best value: 0.618049:  78%|███████▊  | 39/50 [08:43<01:04,  5.88s/it]

[I 2025-12-01 19:20:35,880] Trial 34 finished with value: 0.6014634146341464 and parameters: {'max_depth': 7, 'learning_rate': 0.04911332177897497, 'n_estimators': 507, 'subsample': 0.566173240109141, 'colsample_bytree': 0.8592295564399819, 'min_child_weight': 2, 'gamma': 4.9167027835321955, 'reg_alpha': 0.00047380828039618727, 'reg_lambda': 0.0009234479728126424, 'max_delta_step': 2}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  80%|████████  | 40/50 [08:55<01:15,  7.58s/it]

[I 2025-12-01 19:20:47,426] Trial 31 finished with value: 0.5336585365853659 and parameters: {'max_depth': 6, 'learning_rate': 0.11880014824952724, 'n_estimators': 1209, 'subsample': 0.6231926998832487, 'colsample_bytree': 0.8404599907399879, 'min_child_weight': 2, 'gamma': 1.0348117496824625, 'reg_alpha': 2.8593635065547258e-06, 'reg_lambda': 0.01854591135333021, 'max_delta_step': 7}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  82%|████████▏ | 41/50 [09:00<01:02,  6.91s/it]

[I 2025-12-01 19:20:52,788] Trial 40 pruned.

Best trial: 13. Best value: 0.618049:  84%|████████▍ | 42/50 [09:00<00:39,  4.94s/it]

[I 2025-12-01 19:20:53,141] Trial 43 pruned.

Best trial: 13. Best value: 0.618049:  86%|████████▌ | 43/50 [09:17<00:59,  8.52s/it]

[I 2025-12-01 19:21:10,002] Trial 44 pruned.

Best trial: 13. Best value: 0.618049:  88%|████████▊ | 44/50 [09:19<00:39,  6.57s/it]

[I 2025-12-01 19:21:12,024] Trial 41 pruned.

Best trial: 13. Best value: 0.618049:  90%|█████████ | 45/50 [09:39<00:51, 10.38s/it]

[I 2025-12-01 19:21:31,296] Trial 47 pruned.

Best trial: 13. Best value: 0.618049:  92%|█████████▏| 46/50 [10:03<00:57, 14.46s/it]

[I 2025-12-01 19:21:55,265] Trial 45 finished with value: 0.5736585365853658 and parameters: {'max_depth': 7, 'learning_rate': 0.06540699008572112, 'n_estimators': 676, 'subsample': 0.5946142753824577, 'colsample_bytree': 0.8765318304928265, 'min_child_weight': 3, 'gamma': 4.763344440400369, 'reg_alpha': 0.0001293702202191849, 'reg_lambda': 0.0009047972947796768, 'max_delta_step': 3}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  94%|█████████▍| 47/50 [10:37<01:01, 20.33s/it]

[I 2025-12-01 19:22:29,310] Trial 46 finished with value: 0.5736585365853658 and parameters: {'max_depth': 8, 'learning_rate': 0.03662614971660812, 'n_estimators': 628, 'subsample': 0.5821044369036895, 'colsample_bytree': 0.8753524179688671, 'min_child_weight': 2, 'gamma': 3.7299722657704484, 'reg_alpha': 2.968864410589196e-05, 'reg_lambda': 0.00032395037119948715, 'max_delta_step': 1}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  96%|█████████▌| 48/50 [10:37<00:28, 14.33s/it]

[I 2025-12-01 19:22:29,647] Trial 42 finished with value: 0.5580487804878049 and parameters: {'max_depth': 5, 'learning_rate': 0.01172828991136902, 'n_estimators': 640, 'subsample': 0.5665355190011633, 'colsample_bytree': 0.936254813699527, 'min_child_weight': 2, 'gamma': 3.6688225053563053, 'reg_alpha': 3.8955558157404135e-06, 'reg_lambda': 0.18216537747195316, 'max_delta_step': 5}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049:  98%|█████████▊| 49/50 [10:46<00:12, 12.89s/it]

[I 2025-12-01 19:22:39,183] Trial 48 finished with value: 0.5980487804878049 and parameters: {'max_depth': 7, 'learning_rate': 0.045180728444038296, 'n_estimators': 650, 'subsample': 0.6514566928183787, 'colsample_bytree': 0.771703213876659, 'min_child_weight': 2, 'gamma': 2.937133594364412, 'reg_alpha': 2.5436935013131487e-05, 'reg_lambda': 0.009591959257496554, 'max_delta_step': 0}. Best is trial 13 with value: 0.6180487804878049.

Best trial: 13. Best value: 0.618049: 100%|██████████| 50/50 [10:58<00:00, 13.17s/it]

[I 2025-12-01 19:22:50,783] Trial 49 pruned.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 19:22:55,821] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 67, Test size: 17
Using Leave-One-Out CV with 67 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.579268:   2%|▏         | 1/50 [00:34<28:30, 34.91s/it]

[I 2025-12-01 19:23:30,722] Trial 2 finished with value: 0.5792682926829269 and parameters: {'max_depth': 10, 'learning_rate': 0.02883388239856963, 'n_estimators': 345, 'subsample': 0.5339939440898486, 'colsample_bytree': 0.5224978168668346, 'min_child_weight': 3, 'gamma': 4.615644116708081, 'reg_alpha': 6.9727885847197794e-06, 'reg_lambda': 2.6104993627674906, 'max_delta_step': 7}. Best is trial 2 with value: 0.5792682926829269.

Best trial: 0. Best value: 0.598499:   4%|▍         | 2/50 [00:35<11:54, 14.89s/it]

[I 2025-12-01 19:23:31,603] Trial 0 finished with value: 0.5984990619136961 and parameters: {'max_depth': 4, 'learning_rate': 0.07281446278528927, 'n_estimators': 547, 'subsample': 0.6265270243840325, 'colsample_bytree': 0.7300973777178031, 'min_child_weight': 6, 'gamma': 4.231989686090408, 'reg_alpha': 0.002539455329136922, 'reg_lambda': 6.834706115557962e-08, 'max_delta_step': 8}. Best is trial 0 with value: 0.5984990619136961.

Best trial: 0. Best value: 0.598499:   6%|▌         | 3/50 [00:37<06:56,  8.87s/it]

[I 2025-12-01 19:23:33,309] Trial 1 finished with value: 0.17448405253283303 and parameters: {'max_depth': 3, 'learning_rate': 0.2661092897254058, 'n_estimators': 636, 'subsample': 0.6024498445321864, 'colsample_bytree': 0.6829946140913079, 'min_child_weight': 9, 'gamma': 0.7507142019794949, 'reg_alpha': 0.00015100594066827597, 'reg_lambda': 0.09870259591646148, 'max_delta_step': 6}. Best is trial 0 with value: 0.5984990619136961.

Best trial: 0. Best value: 0.598499:   8%|▊         | 4/50 [01:24<18:23, 24.00s/it]

[I 2025-12-01 19:24:20,488] Trial 5 finished with value: 0.5530018761726079 and parameters: {'max_depth': 8, 'learning_rate': 0.03331396713988172, 'n_estimators': 444, 'subsample': 0.9250290776847323, 'colsample_bytree': 0.5778242737041359, 'min_child_weight': 6, 'gamma': 0.6624456499428288, 'reg_alpha': 0.6972422642511342, 'reg_lambda': 2.683271185183877e-05, 'max_delta_step': 5}. Best is trial 0 with value: 0.5984990619136961.

Best trial: 0. Best value: 0.598499:  10%|█         | 5/50 [01:38<15:16, 20.37s/it]

[I 2025-12-01 19:24:34,434] Trial 3 finished with value: 0.5914634146341464 and parameters: {'max_depth': 5, 'learning_rate': 0.04621071602041898, 'n_estimators': 680, 'subsample': 0.5658435577966809, 'colsample_bytree': 0.7778585725353182, 'min_child_weight': 1, 'gamma': 1.664003935699544, 'reg_alpha': 5.220895238846278, 'reg_lambda': 0.00010861878683350404, 'max_delta_step': 4}. Best is trial 0 with value: 0.5984990619136961.

Best trial: 0. Best value: 0.598499:  12%|█▏        | 6/50 [02:18<19:48, 27.02s/it]

[I 2025-12-01 19:25:14,352] Trial 6 finished with value: 0.5530018761726079 and parameters: {'max_depth': 8, 'learning_rate': 0.045033707219051956, 'n_estimators': 702, 'subsample': 0.7512380872674855, 'colsample_bytree': 0.6738479256079336, 'min_child_weight': 1, 'gamma': 0.003790890056772356, 'reg_alpha': 0.15554020833790536, 'reg_lambda': 0.00010436850775300072, 'max_delta_step': 9}. Best is trial 0 with value: 0.5984990619136961.

Best trial: 0. Best value: 0.598499:  14%|█▍        | 7/50 [02:21<13:46, 19.23s/it]

[I 2025-12-01 19:25:17,553] Trial 4 finished with value: 0.5600375234521576 and parameters: {'max_depth': 9, 'learning_rate': 0.011250451969327427, 'n_estimators': 1137, 'subsample': 0.8287072093088675, 'colsample_bytree': 0.9906510167099318, 'min_child_weight': 7, 'gamma': 1.4856510801908724, 'reg_alpha': 3.390627682945389e-08, 'reg_lambda': 2.9054000823411084e-07, 'max_delta_step': 8}. Best is trial 0 with value: 0.5984990619136961.

Best trial: 0. Best value: 0.598499:  16%|█▌        | 8/50 [02:23<09:40, 13.82s/it]

[I 2025-12-01 19:25:19,781] Trial 7 finished with value: 0.3991557223264541 and parameters: {'max_depth': 6, 'learning_rate': 0.16172283186984107, 'n_estimators': 938, 'subsample': 0.6517676137077012, 'colsample_bytree': 0.9380246924939754, 'min_child_weight': 10, 'gamma': 0.10823623443328045, 'reg_alpha': 2.168859388377956, 'reg_lambda': 2.6404194376025905e-06, 'max_delta_step': 2}. Best is trial 0 with value: 0.5984990619136961.

Best trial: 8. Best value: 0.61773:  18%|█▊        | 9/50 [02:40<09:56, 14.54s/it]

[I 2025-12-01 19:25:35,920] Trial 8 finished with value: 0.6177298311444652 and parameters: {'max_depth': 6, 'learning_rate': 0.24786458329614272, 'n_estimators': 953, 'subsample': 0.5678094374313128, 'colsample_bytree': 0.653022885560313, 'min_child_weight': 3, 'gamma': 4.9903641753097485, 'reg_alpha': 0.00011652672264683173, 'reg_lambda': 0.0025179495015116965, 'max_delta_step': 3}. Best is trial 8 with value: 0.6177298311444652.

Best trial: 8. Best value: 0.61773:  20%|██        | 10/50 [03:21<15:10, 22.77s/it]

[I 2025-12-01 19:26:17,103] Trial 11 finished with value: 0.6036585365853658 and parameters: {'max_depth': 4, 'learning_rate': 0.03240140282097939, 'n_estimators': 573, 'subsample': 0.5661592911061666, 'colsample_bytree': 0.5177656671105368, 'min_child_weight': 3, 'gamma': 1.8544494208586582, 'reg_alpha': 6.047284286343476e-08, 'reg_lambda': 4.662983505554313e-08, 'max_delta_step': 0}. Best is trial 8 with value: 0.6177298311444652.

Best trial: 8. Best value: 0.61773:  22%|██▏       | 11/50 [03:24<10:48, 16.64s/it]

[I 2025-12-01 19:26:19,839] Trial 12 pruned.

Best trial: 8. Best value: 0.61773:  24%|██▍       | 12/50 [03:33<09:08, 14.42s/it]

[I 2025-12-01 19:26:29,198] Trial 13 pruned.

Best trial: 8. Best value: 0.61773:  26%|██▌       | 13/50 [03:41<07:47, 12.63s/it]

[I 2025-12-01 19:26:37,682] Trial 9 finished with value: 0.5914634146341464 and parameters: {'max_depth': 4, 'learning_rate': 0.019061090669048174, 'n_estimators': 1066, 'subsample': 0.5988716019460335, 'colsample_bytree': 0.7578410472561243, 'min_child_weight': 6, 'gamma': 2.5578778368201895, 'reg_alpha': 2.6140303897146516e-07, 'reg_lambda': 2.5026618627964043, 'max_delta_step': 4}. Best is trial 8 with value: 0.6177298311444652.

Best trial: 8. Best value: 0.61773:  28%|██▊       | 14/50 [03:54<07:39, 12.76s/it]

[I 2025-12-01 19:26:50,748] Trial 16 pruned.

Best trial: 8. Best value: 0.61773:  30%|███       | 15/50 [04:10<07:52, 13.50s/it]

[I 2025-12-01 19:27:05,955] Trial 10 finished with value: 0.5844277673545966 and parameters: {'max_depth': 3, 'learning_rate': 0.010055597042907823, 'n_estimators': 440, 'subsample': 0.6483281038076746, 'colsample_bytree': 0.8651098577916718, 'min_child_weight': 2, 'gamma': 2.7078426682428307, 'reg_alpha': 6.67327778873772e-06, 'reg_lambda': 0.001386666925760038, 'max_delta_step': 3}. Best is trial 8 with value: 0.6177298311444652.

Best trial: 8. Best value: 0.61773:  32%|███▏      | 16/50 [04:29<08:35, 15.15s/it]

[I 2025-12-01 19:27:24,941] Trial 17 finished with value: 0.5530018761726079 and parameters: {'max_depth': 3, 'learning_rate': 0.016632368162570514, 'n_estimators': 201, 'subsample': 0.7033170353803155, 'colsample_bytree': 0.507501640601141, 'min_child_weight': 4, 'gamma': 3.3777577555763223, 'reg_alpha': 1.3469638287469128e-08, 'reg_lambda': 1.3465824397406056e-08, 'max_delta_step': 0}. Best is trial 8 with value: 0.6177298311444652.

Best trial: 8. Best value: 0.61773:  34%|███▍      | 17/50 [04:42<08:02, 14.62s/it]

[I 2025-12-01 19:27:38,343] Trial 18 finished with value: 0.5722326454033771 and parameters: {'max_depth': 5, 'learning_rate': 0.019767079809759246, 'n_estimators': 208, 'subsample': 0.711515767630891, 'colsample_bytree': 0.5018161950512561, 'min_child_weight': 4, 'gamma': 3.4909816647211396, 'reg_alpha': 1.0122027092980421e-08, 'reg_lambda': 1.6991575261297082e-08, 'max_delta_step': 0}. Best is trial 8 with value: 0.6177298311444652.

Best trial: 8. Best value: 0.61773:  36%|███▌      | 18/50 [05:10<09:57, 18.69s/it]

[I 2025-12-01 19:28:06,489] Trial 14 finished with value: 0.5722326454033771 and parameters: {'max_depth': 5, 'learning_rate': 0.016501537657712156, 'n_estimators': 1219, 'subsample': 0.7059727103120993, 'colsample_bytree': 0.5937476777317932, 'min_child_weight': 4, 'gamma': 3.338841381397907, 'reg_alpha': 1.03625097303332e-08, 'reg_lambda': 0.003345766995280153, 'max_delta_step': 0}. Best is trial 8 with value: 0.6177298311444652.

Best trial: 8. Best value: 0.61773:  38%|███▊      | 19/50 [05:34<10:26, 20.22s/it]

[I 2025-12-01 19:28:30,275] Trial 15 finished with value: 0.6106941838649156 and parameters: {'max_depth': 5, 'learning_rate': 0.014804606713340204, 'n_estimators': 1445, 'subsample': 0.5015071854706841, 'colsample_bytree': 0.5876047817330594, 'min_child_weight': 3, 'gamma': 3.0299690698061834, 'reg_alpha': 2.264003951169212e-08, 'reg_lambda': 0.002479006749521347, 'max_delta_step': 0}. Best is trial 8 with value: 0.6177298311444652.

Best trial: 8. Best value: 0.61773:  40%|████      | 20/50 [06:05<11:40, 23.36s/it]

[I 2025-12-01 19:29:00,967] Trial 20 finished with value: 0.6106941838649156 and parameters: {'max_depth': 6, 'learning_rate': 0.07528429812654325, 'n_estimators': 1005, 'subsample': 0.7965184308992876, 'colsample_bytree': 0.6175795794986105, 'min_child_weight': 3, 'gamma': 4.719288413399038, 'reg_alpha': 7.59070716492591e-07, 'reg_lambda': 6.135510709337453e-07, 'max_delta_step': 1}. Best is trial 8 with value: 0.6177298311444652.

Best trial: 8. Best value: 0.61773:  42%|████▏     | 21/50 [06:10<08:38, 17.88s/it]

[I 2025-12-01 19:29:06,064] Trial 19 finished with value: 0.6106941838649156 and parameters: {'max_depth': 6, 'learning_rate': 0.08792575584686899, 'n_estimators': 1378, 'subsample': 0.8079602849019325, 'colsample_bytree': 0.614815579682225, 'min_child_weight': 4, 'gamma': 4.957427998715357, 'reg_alpha': 2.7551517778245653e-07, 'reg_lambda': 3.599177129806079e-06, 'max_delta_step': 1}. Best is trial 8 with value: 0.6177298311444652.

Best trial: 8. Best value: 0.61773:  44%|████▍     | 22/50 [06:54<11:58, 25.67s/it]

[I 2025-12-01 19:29:49,902] Trial 21 finished with value: 0.6158536585365854 and parameters: {'max_depth': 6, 'learning_rate': 0.07818982193948985, 'n_estimators': 1340, 'subsample': 0.8008055300824374, 'colsample_bytree': 0.6557627628810783, 'min_child_weight': 2, 'gamma': 1.879719774417464, 'reg_alpha': 2.988995708706578e-07, 'reg_lambda': 5.959362048678996e-06, 'max_delta_step': 2}. Best is trial 8 with value: 0.6177298311444652.

Best trial: 8. Best value: 0.61773:  46%|████▌     | 23/50 [07:39<14:10, 31.52s/it]

[I 2025-12-01 19:30:35,057] Trial 24 finished with value: 0.5984990619136961 and parameters: {'max_depth': 6, 'learning_rate': 0.1921903008659353, 'n_estimators': 1411, 'subsample': 0.8828763262963754, 'colsample_bytree': 0.6569311736807806, 'min_child_weight': 5, 'gamma': 4.949281761518995, 'reg_alpha': 8.398078887391262e-05, 'reg_lambda': 8.47701043240092e-06, 'max_delta_step': 2}. Best is trial 8 with value: 0.6177298311444652.

Best trial: 8. Best value: 0.61773:  48%|████▊     | 24/50 [07:47<10:38, 24.57s/it]

[I 2025-12-01 19:30:43,423] Trial 23 finished with value: 0.5914634146341464 and parameters: {'max_depth': 6, 'learning_rate': 0.18661472288667758, 'n_estimators': 1494, 'subsample': 0.9536169568957885, 'colsample_bytree': 0.6624693147455514, 'min_child_weight': 5, 'gamma': 4.199298543545741, 'reg_alpha': 0.00016074879468131243, 'reg_lambda': 0.13551127665739304, 'max_delta_step': 2}. Best is trial 8 with value: 0.6177298311444652.

Best trial: 8. Best value: 0.61773:  50%|█████     | 25/50 [07:51<07:37, 18.31s/it]

[I 2025-12-01 19:30:47,126] Trial 22 finished with value: 0.5792682926829269 and parameters: {'max_depth': 6, 'learning_rate': 0.07349419910486593, 'n_estimators': 1443, 'subsample': 0.9964820905786353, 'colsample_bytree': 0.6445685393104981, 'min_child_weight': 2, 'gamma': 4.812881873876714, 'reg_alpha': 6.899268999804733e-07, 'reg_lambda': 0.2253603911845712, 'max_delta_step': 2}. Best is trial 8 with value: 0.6177298311444652.

Best trial: 8. Best value: 0.61773:  52%|█████▏    | 26/50 [07:59<06:05, 15.23s/it]

[I 2025-12-01 19:30:55,167] Trial 26 pruned.

Best trial: 8. Best value: 0.61773:  54%|█████▍    | 27/50 [07:59<04:08, 10.81s/it]

[I 2025-12-01 19:30:55,675] Trial 27 pruned.

Best trial: 8. Best value: 0.61773:  56%|█████▌    | 28/50 [08:08<03:42, 10.10s/it]

[I 2025-12-01 19:31:04,125] Trial 28 pruned.

Best trial: 8. Best value: 0.61773:  58%|█████▊    | 29/50 [08:18<03:32, 10.10s/it]

[I 2025-12-01 19:31:14,206] Trial 30 pruned.

Best trial: 8. Best value: 0.61773:  60%|██████    | 30/50 [08:26<03:09,  9.50s/it]

[I 2025-12-01 19:31:22,299] Trial 31 pruned.

Best trial: 8. Best value: 0.61773:  62%|██████▏   | 31/50 [08:27<02:12,  6.96s/it]

[I 2025-12-01 19:31:23,338] Trial 32 pruned.

Best trial: 8. Best value: 0.61773:  64%|██████▍   | 32/50 [08:46<03:10, 10.57s/it]

[I 2025-12-01 19:31:42,321] Trial 25 finished with value: 0.6055347091932457 and parameters: {'max_depth': 7, 'learning_rate': 0.16654148936340243, 'n_estimators': 1316, 'subsample': 0.8867421961348857, 'colsample_bytree': 0.6815852367537757, 'min_child_weight': 2, 'gamma': 2.1805969345505565, 'reg_alpha': 0.00014374931667789065, 'reg_lambda': 0.3591852547841806, 'max_delta_step': 2}. Best is trial 8 with value: 0.6177298311444652.

Best trial: 8. Best value: 0.61773:  66%|██████▌   | 33/50 [09:42<06:51, 24.21s/it]

[I 2025-12-01 19:32:38,360] Trial 33 finished with value: 0.5792682926829269 and parameters: {'max_depth': 4, 'learning_rate': 0.05747650123225472, 'n_estimators': 1174, 'subsample': 0.667374760227558, 'colsample_bytree': 0.7988166667684524, 'min_child_weight': 5, 'gamma': 4.012827381217515, 'reg_alpha': 0.0005671441624356388, 'reg_lambda': 3.0239981472234576e-05, 'max_delta_step': 5}. Best is trial 8 with value: 0.6177298311444652.

Best trial: 8. Best value: 0.61773:  68%|██████▊   | 34/50 [09:46<04:50, 18.13s/it]

[I 2025-12-01 19:32:42,322] Trial 29 finished with value: 0.6036585365853658 and parameters: {'max_depth': 8, 'learning_rate': 0.04996880359708862, 'n_estimators': 1274, 'subsample': 0.5016736982543887, 'colsample_bytree': 0.5544490670447536, 'min_child_weight': 1, 'gamma': 1.954246410443896, 'reg_alpha': 0.005203956911278901, 'reg_lambda': 0.004705223382388993, 'max_delta_step': 4}. Best is trial 8 with value: 0.6177298311444652.

Best trial: 8. Best value: 0.61773:  70%|███████   | 35/50 [10:01<04:16, 17.07s/it]

[I 2025-12-01 19:32:56,915] Trial 37 pruned.

Best trial: 34. Best value: 0.622889:  72%|███████▏  | 36/50 [10:10<03:25, 14.66s/it]

[I 2025-12-01 19:33:05,935] Trial 34 finished with value: 0.6228893058161351 and parameters: {'max_depth': 5, 'learning_rate': 0.10065798515373221, 'n_estimators': 1360, 'subsample': 0.810509388527619, 'colsample_bytree': 0.6271057383551868, 'min_child_weight': 3, 'gamma': 3.9856262823276714, 'reg_alpha': 1.5936548124844627e-07, 'reg_lambda': 3.234401057259318e-06, 'max_delta_step': 1}. Best is trial 34 with value: 0.6228893058161351.

Best trial: 34. Best value: 0.622889:  74%|███████▍  | 37/50 [10:32<03:40, 16.94s/it]

[I 2025-12-01 19:33:28,192] Trial 35 finished with value: 0.6106941838649156 and parameters: {'max_depth': 5, 'learning_rate': 0.08654586455064069, 'n_estimators': 1404, 'subsample': 0.8169833963731064, 'colsample_bytree': 0.6235599461771909, 'min_child_weight': 3, 'gamma': 4.188606215249737, 'reg_alpha': 1.2772398694051864e-07, 'reg_lambda': 8.726361895306172e-07, 'max_delta_step': 1}. Best is trial 34 with value: 0.6228893058161351.

Best trial: 34. Best value: 0.622889:  76%|███████▌  | 38/50 [10:41<02:53, 14.49s/it]

[I 2025-12-01 19:33:36,992] Trial 40 pruned.

Best trial: 34. Best value: 0.622889:  78%|███████▊  | 39/50 [10:52<02:29, 13.62s/it]

[I 2025-12-01 19:33:48,565] Trial 41 pruned.

Best trial: 34. Best value: 0.622889:  80%|████████  | 40/50 [11:25<03:12, 19.24s/it]

[I 2025-12-01 19:34:20,913] Trial 39 finished with value: 0.5914634146341464 and parameters: {'max_depth': 5, 'learning_rate': 0.09107087823637126, 'n_estimators': 1103, 'subsample': 0.6010130517185738, 'colsample_bytree': 0.7479839520614152, 'min_child_weight': 3, 'gamma': 3.8538810025521, 'reg_alpha': 2.402596875518097e-06, 'reg_lambda': 1.7908228053970893e-07, 'max_delta_step': 3}. Best is trial 34 with value: 0.6228893058161351.

Best trial: 34. Best value: 0.622889:  82%|████████▏ | 41/50 [11:26<02:04, 13.86s/it]

[I 2025-12-01 19:34:22,229] Trial 36 finished with value: 0.5670731707317074 and parameters: {'max_depth': 5, 'learning_rate': 0.09577138268362057, 'n_estimators': 1375, 'subsample': 0.7970716318625326, 'colsample_bytree': 0.618455822899468, 'min_child_weight': 3, 'gamma': 4.480286258337514, 'reg_alpha': 1.7173626444588177e-07, 'reg_lambda': 1.1205114920724589e-06, 'max_delta_step': 1}. Best is trial 34 with value: 0.6228893058161351.

Best trial: 34. Best value: 0.622889:  84%|████████▍ | 42/50 [11:34<01:37, 12.14s/it]

[I 2025-12-01 19:34:30,350] Trial 38 finished with value: 0.5914634146341464 and parameters: {'max_depth': 5, 'learning_rate': 0.08705279424194935, 'n_estimators': 1368, 'subsample': 0.7862033236334625, 'colsample_bytree': 0.62662851255638, 'min_child_weight': 4, 'gamma': 4.392429862280814, 'reg_alpha': 1.7391521949001765e-07, 'reg_lambda': 1.5530935092984384e-07, 'max_delta_step': 1}. Best is trial 34 with value: 0.6228893058161351.

Best trial: 34. Best value: 0.622889:  86%|████████▌ | 43/50 [12:19<02:33, 21.95s/it]

[I 2025-12-01 19:35:15,205] Trial 42 finished with value: 0.5792682926829269 and parameters: {'max_depth': 5, 'learning_rate': 0.09269414281648165, 'n_estimators': 1197, 'subsample': 0.5481526751965586, 'colsample_bytree': 0.6417997580906039, 'min_child_weight': 2, 'gamma': 4.4749738854888825, 'reg_alpha': 0.0009661295327187418, 'reg_lambda': 8.322207961625135e-05, 'max_delta_step': 3}. Best is trial 34 with value: 0.6228893058161351.

Best trial: 34. Best value: 0.622889:  88%|████████▊ | 44/50 [13:05<02:54, 29.13s/it]

[I 2025-12-01 19:36:01,066] Trial 45 finished with value: 0.5863039399624765 and parameters: {'max_depth': 6, 'learning_rate': 0.06395421393591122, 'n_estimators': 1202, 'subsample': 0.8547045997699536, 'colsample_bytree': 0.6478136842089802, 'min_child_weight': 4, 'gamma': 4.855535113287655, 'reg_alpha': 3.756181037791079e-07, 'reg_lambda': 6.560542267418598e-06, 'max_delta_step': 0}. Best is trial 34 with value: 0.6228893058161351.

Best trial: 44. Best value: 0.635084:  90%|█████████ | 45/50 [13:06<01:43, 20.79s/it]

[I 2025-12-01 19:36:02,407] Trial 44 finished with value: 0.6350844277673546 and parameters: {'max_depth': 6, 'learning_rate': 0.06704532636914028, 'n_estimators': 1500, 'subsample': 0.8659876654430524, 'colsample_bytree': 0.644131505793671, 'min_child_weight': 4, 'gamma': 2.428322918941835, 'reg_alpha': 2.666618143529442e-07, 'reg_lambda': 4.264097930861012e-06, 'max_delta_step': 1}. Best is trial 44 with value: 0.6350844277673546.

Best trial: 44. Best value: 0.635084:  92%|█████████▏| 46/50 [13:18<01:12, 18.00s/it]

[I 2025-12-01 19:36:13,897] Trial 43 finished with value: 0.5600375234521576 and parameters: {'max_depth': 6, 'learning_rate': 0.06445808507550888, 'n_estimators': 1214, 'subsample': 0.5673626044399102, 'colsample_bytree': 0.6454267714950096, 'min_child_weight': 1, 'gamma': 2.4923870875555725, 'reg_alpha': 0.0005031054624454462, 'reg_lambda': 6.775382612450894e-05, 'max_delta_step': 3}. Best is trial 44 with value: 0.6350844277673546.

Best trial: 44. Best value: 0.635084:  94%|█████████▍| 47/50 [13:22<00:41, 14.00s/it]

[I 2025-12-01 19:36:18,555] Trial 47 pruned.

Best trial: 44. Best value: 0.635084:  96%|█████████▌| 48/50 [14:02<00:43, 21.83s/it]

[I 2025-12-01 19:36:58,663] Trial 46 finished with value: 0.5984990619136961 and parameters: {'max_depth': 6, 'learning_rate': 0.0660752397838921, 'n_estimators': 1495, 'subsample': 0.8591229917540073, 'colsample_bytree': 0.5931289158579329, 'min_child_weight': 4, 'gamma': 4.725708506247527, 'reg_alpha': 6.312770879378636e-07, 'reg_lambda': 4.965607272249086e-06, 'max_delta_step': 0}. Best is trial 44 with value: 0.6350844277673546.

Best trial: 44. Best value: 0.635084:  98%|█████████▊| 49/50 [14:12<00:18, 18.17s/it]

[I 2025-12-01 19:37:08,278] Trial 48 finished with value: 0.6092870544090057 and parameters: {'max_depth': 6, 'learning_rate': 0.0667872088324508, 'n_estimators': 1475, 'subsample': 0.9060198371473419, 'colsample_bytree': 0.54018949478284, 'min_child_weight': 10, 'gamma': 2.470134138033548, 'reg_alpha': 2.4713954205725146e-08, 'reg_lambda': 0.023634621357910682, 'max_delta_step': 2}. Best is trial 44 with value: 0.6350844277673546.

Best trial: 44. Best value: 0.635084: 100%|██████████| 50/50 [15:08<00:00, 18.16s/it]

[I 2025-12-01 19:38:04,026] Trial 49 finished with value: 0.5984990619136961 and parameters: {'max_depth': 4, 'learning_rate': 0.03812728087931233, 'n_estimators': 1490, 'subsample': 0.8587756222170433, 'colsample_bytree': 0.6822324632106774, 'min_child_weight': 2, 'gamma': 2.387322606557502, 'reg_alpha': 3.208919176052864e-08, 'reg_lambda': 0.016658905469063942, 'max_delta_step': 2}. Best is trial 44 with value: 0.6350844277673546.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 19:38:09,674] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 64, Test size: 16
Using Leave-One-Out CV with 64 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.595833:   2%|▏         | 1/50 [00:20<16:44, 20.51s/it]

[I 2025-12-01 19:38:30,163] Trial 2 finished with value: 0.5958333333333333 and parameters: {'max_depth': 5, 'learning_rate': 0.27767393320846867, 'n_estimators': 280, 'subsample': 0.873973957343288, 'colsample_bytree': 0.8594779461960613, 'min_child_weight': 6, 'gamma': 0.5887235841403898, 'reg_alpha': 0.00401909951977005, 'reg_lambda': 1.9536500195084863e-05, 'max_delta_step': 10}. Best is trial 2 with value: 0.5958333333333333.

Best trial: 1. Best value: 0.645833:   4%|▍         | 2/50 [01:22<35:46, 44.73s/it]

[I 2025-12-01 19:39:31,850] Trial 1 finished with value: 0.6458333333333333 and parameters: {'max_depth': 3, 'learning_rate': 0.05772295174688168, 'n_estimators': 754, 'subsample': 0.9444851902775119, 'colsample_bytree': 0.611273577203371, 'min_child_weight': 1, 'gamma': 2.6079820926830894, 'reg_alpha': 0.00039781811973214253, 'reg_lambda': 6.583312085436002, 'max_delta_step': 5}. Best is trial 1 with value: 0.6458333333333333.

Best trial: 1. Best value: 0.645833:   6%|▌         | 3/50 [01:27<21:06, 26.95s/it]

[I 2025-12-01 19:39:37,642] Trial 4 finished with value: 0.6458333333333333 and parameters: {'max_depth': 3, 'learning_rate': 0.025383444598070116, 'n_estimators': 851, 'subsample': 0.6993773578535207, 'colsample_bytree': 0.6730460958406939, 'min_child_weight': 4, 'gamma': 0.7321593771136209, 'reg_alpha': 0.0012093414458102991, 'reg_lambda': 1.63636484736442e-07, 'max_delta_step': 1}. Best is trial 1 with value: 0.6458333333333333.

Best trial: 1. Best value: 0.645833:   8%|▊         | 4/50 [01:46<18:02, 23.52s/it]

[I 2025-12-01 19:39:55,921] Trial 5 finished with value: 0.3958333333333333 and parameters: {'max_depth': 5, 'learning_rate': 0.06033601019326363, 'n_estimators': 378, 'subsample': 0.5961032665092978, 'colsample_bytree': 0.8891703683461908, 'min_child_weight': 8, 'gamma': 4.430890273574886, 'reg_alpha': 3.273458233885934e-06, 'reg_lambda': 0.001115974665196377, 'max_delta_step': 0}. Best is trial 1 with value: 0.6458333333333333.

Best trial: 1. Best value: 0.645833:  10%|█         | 5/50 [01:52<12:50, 17.11s/it]

[I 2025-12-01 19:40:01,670] Trial 6 finished with value: 0.325 and parameters: {'max_depth': 9, 'learning_rate': 0.0670362624575526, 'n_estimators': 413, 'subsample': 0.5956163798549328, 'colsample_bytree': 0.5775260466857397, 'min_child_weight': 10, 'gamma': 2.897970954114903, 'reg_alpha': 3.844426105748159e-08, 'reg_lambda': 7.50386743902808e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.6458333333333333.

Best trial: 1. Best value: 0.645833:  12%|█▏        | 6/50 [01:54<08:48, 12.00s/it]

[I 2025-12-01 19:40:03,750] Trial 0 finished with value: 0.6041666666666666 and parameters: {'max_depth': 8, 'learning_rate': 0.01921525052701092, 'n_estimators': 615, 'subsample': 0.5160520903456094, 'colsample_bytree': 0.894221741662518, 'min_child_weight': 1, 'gamma': 0.6390624812880724, 'reg_alpha': 1.0977900125011247e-07, 'reg_lambda': 2.0838253329594925e-06, 'max_delta_step': 4}. Best is trial 1 with value: 0.6458333333333333.

Best trial: 1. Best value: 0.645833:  14%|█▍        | 7/50 [02:30<14:16, 19.93s/it]

[I 2025-12-01 19:40:39,998] Trial 3 finished with value: 0.6375 and parameters: {'max_depth': 7, 'learning_rate': 0.0455257288213489, 'n_estimators': 1378, 'subsample': 0.7779918407867897, 'colsample_bytree': 0.8011281290795436, 'min_child_weight': 1, 'gamma': 4.361573605141469, 'reg_alpha': 0.0008220772852275752, 'reg_lambda': 0.0018512232661152786, 'max_delta_step': 5}. Best is trial 1 with value: 0.6458333333333333.

Best trial: 7. Best value: 0.65:  16%|█▌        | 8/50 [02:36<10:50, 15.50s/it]

[I 2025-12-01 19:40:46,009] Trial 7 finished with value: 0.65 and parameters: {'max_depth': 9, 'learning_rate': 0.017864372581726948, 'n_estimators': 845, 'subsample': 0.7674579419698986, 'colsample_bytree': 0.770566138438264, 'min_child_weight': 8, 'gamma': 4.815025610319007, 'reg_alpha': 0.025777135615341343, 'reg_lambda': 2.8144511002676896e-07, 'max_delta_step': 7}. Best is trial 7 with value: 0.65.

Best trial: 9. Best value: 0.658333:  18%|█▊        | 9/50 [02:56<11:33, 16.91s/it]

[I 2025-12-01 19:41:06,017] Trial 9 finished with value: 0.6583333333333333 and parameters: {'max_depth': 5, 'learning_rate': 0.025716746350242545, 'n_estimators': 456, 'subsample': 0.6703805252487196, 'colsample_bytree': 0.508805976118172, 'min_child_weight': 3, 'gamma': 0.4330337320006561, 'reg_alpha': 0.2588289203337096, 'reg_lambda': 8.417391584073783, 'max_delta_step': 6}. Best is trial 9 with value: 0.6583333333333333.

Best trial: 9. Best value: 0.658333:  20%|██        | 10/50 [03:03<09:10, 13.76s/it]

[I 2025-12-01 19:41:12,725] Trial 8 finished with value: 0.425 and parameters: {'max_depth': 4, 'learning_rate': 0.09174041473529133, 'n_estimators': 1354, 'subsample': 0.5095550525330004, 'colsample_bytree': 0.6498933267691689, 'min_child_weight': 9, 'gamma': 0.18050862537342782, 'reg_alpha': 0.0001275905966346089, 'reg_lambda': 0.004081400993757935, 'max_delta_step': 5}. Best is trial 9 with value: 0.6583333333333333.

Best trial: 9. Best value: 0.658333:  22%|██▏       | 11/50 [03:06<06:55, 10.65s/it]

[I 2025-12-01 19:41:16,331] Trial 11 pruned.

Best trial: 9. Best value: 0.658333:  24%|██▍       | 12/50 [03:23<07:50, 12.39s/it]

[I 2025-12-01 19:41:32,694] Trial 13 pruned.

Best trial: 9. Best value: 0.658333:  26%|██▌       | 13/50 [03:35<07:35, 12.32s/it]

[I 2025-12-01 19:41:44,847] Trial 15 pruned.

Best trial: 9. Best value: 0.658333:  28%|██▊       | 14/50 [04:07<10:58, 18.29s/it]

[I 2025-12-01 19:42:16,949] Trial 12 finished with value: 0.6333333333333333 and parameters: {'max_depth': 5, 'learning_rate': 0.04600733810284508, 'n_estimators': 704, 'subsample': 0.7953226714886785, 'colsample_bytree': 0.6425757719260103, 'min_child_weight': 2, 'gamma': 4.153999704889861, 'reg_alpha': 0.014287964118413671, 'reg_lambda': 0.004407359709710143, 'max_delta_step': 1}. Best is trial 9 with value: 0.6583333333333333.

Best trial: 14. Best value: 0.675:  30%|███       | 15/50 [05:05<17:41, 30.34s/it]

[I 2025-12-01 19:43:15,206] Trial 14 finished with value: 0.675 and parameters: {'max_depth': 9, 'learning_rate': 0.01016257530641476, 'n_estimators': 1030, 'subsample': 0.7931406509060874, 'colsample_bytree': 0.5231870401324348, 'min_child_weight': 4, 'gamma': 1.7051453024394623, 'reg_alpha': 2.447375912300144, 'reg_lambda': 7.420324676542021, 'max_delta_step': 8}. Best is trial 14 with value: 0.675.

Best trial: 14. Best value: 0.675:  32%|███▏      | 16/50 [05:06<12:15, 21.63s/it]

[I 2025-12-01 19:43:16,602] Trial 16 finished with value: 0.6166666666666667 and parameters: {'max_depth': 7, 'learning_rate': 0.027259102662823984, 'n_estimators': 1070, 'subsample': 0.7742433176886694, 'colsample_bytree': 0.7297155205809019, 'min_child_weight': 3, 'gamma': 1.624439402847556, 'reg_alpha': 0.05415135403708697, 'reg_lambda': 0.11876631356988979, 'max_delta_step': 7}. Best is trial 14 with value: 0.675.

Best trial: 14. Best value: 0.675:  34%|███▍      | 17/50 [05:19<10:23, 18.88s/it]

[I 2025-12-01 19:43:29,100] Trial 10 finished with value: 0.6625 and parameters: {'max_depth': 4, 'learning_rate': 0.01675547029875271, 'n_estimators': 1032, 'subsample': 0.8463874238559687, 'colsample_bytree': 0.9906186779791839, 'min_child_weight': 1, 'gamma': 3.6126881194052145, 'reg_alpha': 2.7961187455184908e-05, 'reg_lambda': 0.0013407957177364036, 'max_delta_step': 7}. Best is trial 14 with value: 0.675.

Best trial: 14. Best value: 0.675:  36%|███▌      | 18/50 [05:23<07:42, 14.46s/it]

[I 2025-12-01 19:43:33,263] Trial 19 pruned.

Best trial: 14. Best value: 0.675:  38%|███▊      | 19/50 [05:26<05:41, 11.00s/it]

[I 2025-12-01 19:43:36,212] Trial 17 finished with value: 0.625 and parameters: {'max_depth': 7, 'learning_rate': 0.02724998009564394, 'n_estimators': 1043, 'subsample': 0.6296870077634279, 'colsample_bytree': 0.7262003509778953, 'min_child_weight': 4, 'gamma': 1.8418891758593365, 'reg_alpha': 0.0803014920269518, 'reg_lambda': 0.20537074185362955, 'max_delta_step': 7}. Best is trial 14 with value: 0.675.

Best trial: 14. Best value: 0.675:  40%|████      | 20/50 [05:29<04:21,  8.73s/it]

[I 2025-12-01 19:43:39,646] Trial 18 pruned.

Best trial: 14. Best value: 0.675:  42%|████▏     | 21/50 [05:43<04:54, 10.14s/it]

[I 2025-12-01 19:43:53,075] Trial 21 pruned.

Best trial: 14. Best value: 0.675:  44%|████▍     | 22/50 [05:58<05:29, 11.76s/it]

[I 2025-12-01 19:44:08,605] Trial 20 pruned.

Best trial: 14. Best value: 0.675:  46%|████▌     | 23/50 [06:13<05:39, 12.59s/it]

[I 2025-12-01 19:44:23,134] Trial 22 pruned.

Best trial: 14. Best value: 0.675:  48%|████▊     | 24/50 [06:43<07:46, 17.95s/it]

[I 2025-12-01 19:44:53,581] Trial 25 pruned.

Best trial: 14. Best value: 0.675:  50%|█████     | 25/50 [06:53<06:29, 15.58s/it]

[I 2025-12-01 19:45:03,645] Trial 26 pruned.

Best trial: 14. Best value: 0.675:  52%|█████▏    | 26/50 [07:59<12:13, 30.58s/it]

[I 2025-12-01 19:46:09,211] Trial 27 finished with value: 0.6375 and parameters: {'max_depth': 6, 'learning_rate': 0.014103028831906981, 'n_estimators': 568, 'subsample': 0.7277981130282407, 'colsample_bytree': 0.5638345014272628, 'min_child_weight': 3, 'gamma': 2.309338050380077, 'reg_alpha': 9.662382303061047e-07, 'reg_lambda': 0.030748357676036744, 'max_delta_step': 6}. Best is trial 14 with value: 0.675.

Best trial: 14. Best value: 0.675:  54%|█████▍    | 27/50 [08:02<08:30, 22.18s/it]

[I 2025-12-01 19:46:11,787] Trial 23 finished with value: 0.65 and parameters: {'max_depth': 8, 'learning_rate': 0.1449418690935164, 'n_estimators': 1448, 'subsample': 0.8630010743596946, 'colsample_bytree': 0.9908650526963478, 'min_child_weight': 2, 'gamma': 3.5312207902948645, 'reg_alpha': 1.603614412727068e-05, 'reg_lambda': 0.018552487326703546, 'max_delta_step': 9}. Best is trial 14 with value: 0.675.

Best trial: 14. Best value: 0.675:  56%|█████▌    | 28/50 [08:07<06:13, 17.00s/it]

[I 2025-12-01 19:46:16,694] Trial 29 pruned.

Best trial: 14. Best value: 0.675:  58%|█████▊    | 29/50 [08:08<04:21, 12.47s/it]

[I 2025-12-01 19:46:18,605] Trial 30 pruned.

Best trial: 14. Best value: 0.675:  60%|██████    | 30/50 [08:13<03:22, 10.14s/it]

[I 2025-12-01 19:46:23,299] Trial 28 finished with value: 0.6375 and parameters: {'max_depth': 6, 'learning_rate': 0.02237786290426405, 'n_estimators': 609, 'subsample': 0.7223069186868645, 'colsample_bytree': 0.8223650432652929, 'min_child_weight': 3, 'gamma': 2.3555806710664626, 'reg_alpha': 1.5707530662330178e-06, 'reg_lambda': 1.3398459038622723, 'max_delta_step': 8}. Best is trial 14 with value: 0.675.

Best trial: 14. Best value: 0.675:  62%|██████▏   | 31/50 [08:17<02:35,  8.19s/it]

[I 2025-12-01 19:46:26,945] Trial 24 finished with value: 0.6041666666666666 and parameters: {'max_depth': 4, 'learning_rate': 0.01448304098438449, 'n_estimators': 953, 'subsample': 0.8524674418307557, 'colsample_bytree': 0.568355164799115, 'min_child_weight': 2, 'gamma': 1.1132064455803916, 'reg_alpha': 0.6328605911396405, 'reg_lambda': 1.9485644940772973, 'max_delta_step': 6}. Best is trial 14 with value: 0.675.

Best trial: 14. Best value: 0.675:  64%|██████▍   | 32/50 [08:18<01:51,  6.17s/it]

[I 2025-12-01 19:46:28,411] Trial 31 pruned.

Best trial: 14. Best value: 0.675:  66%|██████▌   | 33/50 [08:25<01:48,  6.36s/it]

[I 2025-12-01 19:46:35,204] Trial 34 pruned.

Best trial: 14. Best value: 0.675:  68%|██████▊   | 34/50 [08:27<01:22,  5.15s/it]

[I 2025-12-01 19:46:37,516] Trial 35 pruned.

Best trial: 14. Best value: 0.675:  70%|███████   | 35/50 [09:34<05:53, 23.56s/it]

[I 2025-12-01 19:47:44,049] Trial 32 finished with value: 0.65 and parameters: {'max_depth': 5, 'learning_rate': 0.03468613429435793, 'n_estimators': 709, 'subsample': 0.5507983684393876, 'colsample_bytree': 0.5482354948051712, 'min_child_weight': 1, 'gamma': 0.4975555291158396, 'reg_alpha': 0.31497592117559636, 'reg_lambda': 0.00022929279986462915, 'max_delta_step': 4}. Best is trial 14 with value: 0.675.

Best trial: 14. Best value: 0.675:  72%|███████▏  | 36/50 [09:43<04:30, 19.35s/it]

[I 2025-12-01 19:47:53,555] Trial 38 pruned.

Best trial: 14. Best value: 0.675:  74%|███████▍  | 37/50 [10:22<05:25, 25.02s/it]

[I 2025-12-01 19:48:31,802] Trial 33 finished with value: 0.65 and parameters: {'max_depth': 5, 'learning_rate': 0.03329483673922536, 'n_estimators': 1279, 'subsample': 0.9227961474652446, 'colsample_bytree': 0.5394539713529433, 'min_child_weight': 1, 'gamma': 3.0291500773981204, 'reg_alpha': 0.22036069293171504, 'reg_lambda': 0.0002169710965627843, 'max_delta_step': 4}. Best is trial 14 with value: 0.675.

Best trial: 14. Best value: 0.675:  76%|███████▌  | 38/50 [10:26<03:46, 18.87s/it]

[I 2025-12-01 19:48:36,345] Trial 40 pruned.

Best trial: 14. Best value: 0.675:  78%|███████▊  | 39/50 [10:31<02:42, 14.78s/it]

[I 2025-12-01 19:48:41,558] Trial 36 finished with value: 0.6375 and parameters: {'max_depth': 9, 'learning_rate': 0.018544384010509327, 'n_estimators': 1211, 'subsample': 0.6579076122166674, 'colsample_bytree': 0.5410211656593744, 'min_child_weight': 1, 'gamma': 3.8895795633111603, 'reg_alpha': 0.01813194873032715, 'reg_lambda': 0.0002143222075427231, 'max_delta_step': 4}. Best is trial 14 with value: 0.675.

Best trial: 14. Best value: 0.675:  80%|████████  | 40/50 [10:34<01:50, 11.09s/it]

[I 2025-12-01 19:48:44,043] Trial 41 pruned.

Best trial: 14. Best value: 0.675:  82%|████████▏ | 41/50 [10:37<01:18,  8.71s/it]

[I 2025-12-01 19:48:47,191] Trial 43 pruned.

Best trial: 14. Best value: 0.675:  84%|████████▍ | 42/50 [10:40<00:55,  6.96s/it]

[I 2025-12-01 19:48:50,061] Trial 42 pruned.

Best trial: 14. Best value: 0.675:  86%|████████▌ | 43/50 [10:53<01:01,  8.78s/it]

[I 2025-12-01 19:49:03,087] Trial 37 finished with value: 0.65 and parameters: {'max_depth': 3, 'learning_rate': 0.012607064461308602, 'n_estimators': 1285, 'subsample': 0.6573699887896471, 'colsample_bytree': 0.5388527414029115, 'min_child_weight': 1, 'gamma': 3.9960505154076733, 'reg_alpha': 2.2730357973023776, 'reg_lambda': 0.00018377572803741468, 'max_delta_step': 5}. Best is trial 14 with value: 0.675.

Best trial: 14. Best value: 0.675:  88%|████████▊ | 44/50 [11:09<01:06, 11.01s/it]

[I 2025-12-01 19:49:19,298] Trial 46 pruned.
[I 2025-12-01 19:49:19,375] Trial 39 finished with value: 0.65 and parameters: {'max_depth': 9, 'learning_rate': 0.01794551549623925, 'n_estimators': 460, 'subsample': 0.6669119331576081, 'colsample_bytree': 0.8667015665509253, 'min_child_weight': 1, 'gamma': 3.926085295774766, 'reg_alpha': 0.0015283393551360398, 'reg_lambda': 5.9580200839614155e-08, 'max_delta_step': 9}. Best is trial 14 with value: 0.675.

Best trial: 14. Best value: 0.675:  92%|█████████▏| 46/50 [11:24<00:37,  9.39s/it]

[I 2025-12-01 19:49:34,302] Trial 45 pruned.

Best trial: 14. Best value: 0.675:  94%|█████████▍| 47/50 [12:18<01:01, 20.48s/it]

[I 2025-12-01 19:50:28,409] Trial 48 finished with value: 0.65 and parameters: {'max_depth': 8, 'learning_rate': 0.11751314209561443, 'n_estimators': 1022, 'subsample': 0.7971336128565978, 'colsample_bytree': 0.9648413093629922, 'min_child_weight': 2, 'gamma': 0.8086072466286449, 'reg_alpha': 4.168509877287092e-07, 'reg_lambda': 0.0063320503164221355, 'max_delta_step': 7}. Best is trial 14 with value: 0.675.

Best trial: 14. Best value: 0.675:  96%|█████████▌| 48/50 [12:39<00:41, 20.59s/it]

[I 2025-12-01 19:50:49,333] Trial 47 finished with value: 0.6375 and parameters: {'max_depth': 8, 'learning_rate': 0.10822613999535588, 'n_estimators': 1007, 'subsample': 0.8314246530514651, 'colsample_bytree': 0.9686410457861602, 'min_child_weight': 2, 'gamma': 3.3199141642453642, 'reg_alpha': 3.371627797850122e-07, 'reg_lambda': 0.019516112254866838, 'max_delta_step': 8}. Best is trial 14 with value: 0.675.

Best trial: 14. Best value: 0.675:  98%|█████████▊| 49/50 [12:46<00:16, 16.93s/it]

[I 2025-12-01 19:50:56,457] Trial 49 finished with value: 0.6375 and parameters: {'max_depth': 7, 'learning_rate': 0.05480544470996655, 'n_estimators': 888, 'subsample': 0.7899399109900169, 'colsample_bytree': 0.912777519732652, 'min_child_weight': 2, 'gamma': 3.2987650108160924, 'reg_alpha': 4.139722237343725e-07, 'reg_lambda': 0.0008453812222835974, 'max_delta_step': 7}. Best is trial 14 with value: 0.675.

Best trial: 14. Best value: 0.675: 100%|██████████| 50/50 [13:04<00:00, 15.68s/it]

[I 2025-12-01 19:51:13,855] Trial 44 finished with value: 0.65 and parameters: {'max_depth': 8, 'learning_rate': 0.09675845639901172, 'n_estimators': 1376, 'subsample': 0.8610866867405604, 'colsample_bytree': 0.9580399451999116, 'min_child_weight': 1, 'gamma': 4.661669497227887, 'reg_alpha': 5.528727670011915e-05, 'reg_lambda': 0.012114639548872808, 'max_delta_step': 9}. Best is trial 14 with value: 0.675.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.618049                0.635714      0.671429
1    17_1         loo       0.635084                0.635714      0.542857
2     9_1         loo       0.695109                0.550000      0.650000
3    19_1         loo       0.675000                0.550000      0.550000

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.271429          0.571429               0.7        50          66
1  0.271429          0.571429               0.7        50          67
2  0.097590          0.500000               0.6        50          63
3  0.097590          0.500000               0.6        50          64

   test_size
0         17
1         17
2         16
3         16
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.618049                0.635714      0.671429
1    17_1         loo       0.635084                0.635714      0.542857
2     9_1         loo       0.695109                0.550000      0.650000
3    19_1         loo       0.675000                0.550000      0.550000

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.271429          0.571429               0.7        50          66
1  0.271429          0.571429               0.7        50          67
2  0.097590          0.500000               0.6        50          63
3  0.097590          0.500000               0.6        50          64

   test_size
0         17
1         17
2         16
3         16

In [1567]:

datasets = task_hf_dfs_clean_lbd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir="xgb_lbd_hc_{CV_STRATEGY}_tasks/xgb_results_handcrafted_lbd_hc_extended_{CV_STRATEGY}_tasks",
    split_param="w.cz.fnusa",
)
print(summary)

[I 2025-12-01 19:51:19,934] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 67, Test size: 17
Using Leave-One-Out CV with 67 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.574109:   2%|▏         | 1/50 [00:26<21:23, 26.20s/it]

[I 2025-12-01 19:51:46,130] Trial 3 finished with value: 0.574108818011257 and parameters: {'max_depth': 8, 'learning_rate': 0.0628067961652193, 'n_estimators': 415, 'subsample': 0.666860742717033, 'colsample_bytree': 0.7458995913139805, 'min_child_weight': 4, 'gamma': 0.47364578224974474, 'reg_alpha': 0.21601388033512597, 'reg_lambda': 1.3892527831398477e-07, 'max_delta_step': 6}. Best is trial 3 with value: 0.574108818011257.

Best trial: 3. Best value: 0.574109:   4%|▍         | 2/50 [00:37<13:53, 17.37s/it]

[I 2025-12-01 19:51:57,309] Trial 1 finished with value: 0.5286116322701688 and parameters: {'max_depth': 8, 'learning_rate': 0.09969088836241696, 'n_estimators': 640, 'subsample': 0.6956224977765406, 'colsample_bytree': 0.8562719927784476, 'min_child_weight': 5, 'gamma': 4.617852832059051, 'reg_alpha': 0.4391456423327759, 'reg_lambda': 2.5062478431257182, 'max_delta_step': 8}. Best is trial 3 with value: 0.574108818011257.

Best trial: 3. Best value: 0.574109:   6%|▌         | 3/50 [00:53<13:03, 16.67s/it]

[I 2025-12-01 19:52:13,148] Trial 4 finished with value: 0.49718574108818014 and parameters: {'max_depth': 3, 'learning_rate': 0.011525655128493203, 'n_estimators': 431, 'subsample': 0.6596523315920745, 'colsample_bytree': 0.5250898039036493, 'min_child_weight': 5, 'gamma': 1.894400830657872, 'reg_alpha': 1.2245901989595618e-07, 'reg_lambda': 3.785089577118035e-08, 'max_delta_step': 7}. Best is trial 3 with value: 0.574108818011257.

Best trial: 5. Best value: 0.598499:   8%|▊         | 4/50 [00:53<07:56, 10.35s/it]

[I 2025-12-01 19:52:13,811] Trial 5 finished with value: 0.5984990619136961 and parameters: {'max_depth': 7, 'learning_rate': 0.09992201050839437, 'n_estimators': 239, 'subsample': 0.6857556446403237, 'colsample_bytree': 0.9428184017035293, 'min_child_weight': 3, 'gamma': 0.39493053554470914, 'reg_alpha': 0.00801649309193653, 'reg_lambda': 0.015387938658358765, 'max_delta_step': 3}. Best is trial 5 with value: 0.5984990619136961.

Best trial: 5. Best value: 0.598499:  10%|█         | 5/50 [01:12<09:53, 13.19s/it]

[I 2025-12-01 19:52:32,030] Trial 2 finished with value: 0.5215759849906192 and parameters: {'max_depth': 5, 'learning_rate': 0.05352602313975398, 'n_estimators': 1311, 'subsample': 0.6846863789688586, 'colsample_bytree': 0.6805769225838976, 'min_child_weight': 7, 'gamma': 0.7608329330196134, 'reg_alpha': 0.17391469232247403, 'reg_lambda': 0.00018877661615328625, 'max_delta_step': 5}. Best is trial 5 with value: 0.5984990619136961.

Best trial: 5. Best value: 0.598499:  12%|█▏        | 6/50 [01:18<08:05, 11.04s/it]

[I 2025-12-01 19:52:38,907] Trial 0 finished with value: 0.5356472795497186 and parameters: {'max_depth': 3, 'learning_rate': 0.03626665033097265, 'n_estimators': 1405, 'subsample': 0.7747641132203016, 'colsample_bytree': 0.7366338550351554, 'min_child_weight': 5, 'gamma': 3.7732689590004527, 'reg_alpha': 1.5179488916614424e-08, 'reg_lambda': 8.504007941684408e-06, 'max_delta_step': 9}. Best is trial 5 with value: 0.5984990619136961.

Best trial: 5. Best value: 0.598499:  14%|█▍        | 7/50 [01:58<14:32, 20.28s/it]

[I 2025-12-01 19:53:18,218] Trial 8 finished with value: 0.2926829268292683 and parameters: {'max_depth': 9, 'learning_rate': 0.023212788853394832, 'n_estimators': 854, 'subsample': 0.643477825659803, 'colsample_bytree': 0.6067802626303312, 'min_child_weight': 9, 'gamma': 1.58156386952595, 'reg_alpha': 3.6903299489231946e-05, 'reg_lambda': 0.002539658781204869, 'max_delta_step': 7}. Best is trial 5 with value: 0.5984990619136961.

Best trial: 5. Best value: 0.598499:  16%|█▌        | 8/50 [02:00<10:09, 14.52s/it]

[I 2025-12-01 19:53:20,398] Trial 6 finished with value: 0.5112570356472796 and parameters: {'max_depth': 9, 'learning_rate': 0.0439614503117401, 'n_estimators': 1209, 'subsample': 0.8617724246821782, 'colsample_bytree': 0.7865678455153859, 'min_child_weight': 5, 'gamma': 3.1547551897430273, 'reg_alpha': 0.24179581500256314, 'reg_lambda': 0.4385372552302837, 'max_delta_step': 4}. Best is trial 5 with value: 0.5984990619136961.

Best trial: 5. Best value: 0.598499:  18%|█▊        | 9/50 [02:11<09:16, 13.58s/it]

[I 2025-12-01 19:53:31,898] Trial 10 finished with value: 0.3522514071294559 and parameters: {'max_depth': 7, 'learning_rate': 0.08509823074916889, 'n_estimators': 222, 'subsample': 0.6180169399485054, 'colsample_bytree': 0.6320244757212639, 'min_child_weight': 8, 'gamma': 2.5582363671409416, 'reg_alpha': 0.005367095989769043, 'reg_lambda': 0.4798648750145815, 'max_delta_step': 0}. Best is trial 5 with value: 0.5984990619136961.

Best trial: 5. Best value: 0.598499:  20%|██        | 10/50 [02:14<06:50, 10.26s/it]

[I 2025-12-01 19:53:34,743] Trial 7 finished with value: 0.5914634146341464 and parameters: {'max_depth': 4, 'learning_rate': 0.016863686289461652, 'n_estimators': 1211, 'subsample': 0.6480997981005892, 'colsample_bytree': 0.9573466467151416, 'min_child_weight': 1, 'gamma': 0.23264853035332878, 'reg_alpha': 2.833015209608454e-06, 'reg_lambda': 3.1381357172732996e-05, 'max_delta_step': 9}. Best is trial 5 with value: 0.5984990619136961.

Best trial: 5. Best value: 0.598499:  22%|██▏       | 11/50 [02:19<05:35,  8.59s/it]

[I 2025-12-01 19:53:39,551] Trial 12 pruned.

Best trial: 5. Best value: 0.598499:  24%|██▍       | 12/50 [02:33<06:32, 10.32s/it]

[I 2025-12-01 19:53:53,807] Trial 9 finished with value: 0.5408067542213884 and parameters: {'max_depth': 7, 'learning_rate': 0.019150605650557984, 'n_estimators': 1339, 'subsample': 0.7403259577595622, 'colsample_bytree': 0.7187650452135934, 'min_child_weight': 8, 'gamma': 0.789001567393055, 'reg_alpha': 1.1166076327089515e-07, 'reg_lambda': 6.471655672071142e-08, 'max_delta_step': 5}. Best is trial 5 with value: 0.5984990619136961.

Best trial: 5. Best value: 0.598499:  26%|██▌       | 13/50 [02:42<05:57,  9.67s/it]

[I 2025-12-01 19:54:02,001] Trial 11 finished with value: 0.44840525328330205 and parameters: {'max_depth': 7, 'learning_rate': 0.03237018345664735, 'n_estimators': 714, 'subsample': 0.8780180666800781, 'colsample_bytree': 0.8454662704457029, 'min_child_weight': 9, 'gamma': 4.5651530359724894, 'reg_alpha': 2.7903192844941164e-05, 'reg_lambda': 3.100289902547379e-06, 'max_delta_step': 4}. Best is trial 5 with value: 0.5984990619136961.

Best trial: 5. Best value: 0.598499:  28%|██▊       | 14/50 [02:51<05:45,  9.59s/it]

[I 2025-12-01 19:54:11,387] Trial 16 pruned.

Best trial: 5. Best value: 0.598499:  30%|███       | 15/50 [03:01<05:40,  9.72s/it]

[I 2025-12-01 19:54:21,410] Trial 17 pruned.

Best trial: 5. Best value: 0.598499:  32%|███▏      | 16/50 [03:04<04:18,  7.62s/it]

[I 2025-12-01 19:54:24,147] Trial 18 pruned.

Best trial: 13. Best value: 0.624765:  34%|███▍      | 17/50 [03:07<03:26,  6.25s/it]

[I 2025-12-01 19:54:27,221] Trial 13 finished with value: 0.6247654784240151 and parameters: {'max_depth': 6, 'learning_rate': 0.2829686604302764, 'n_estimators': 896, 'subsample': 0.5445635890760314, 'colsample_bytree': 0.9919993534604383, 'min_child_weight': 2, 'gamma': 1.4335007155463648, 'reg_alpha': 0.0006929649689987628, 'reg_lambda': 0.01756815907534471, 'max_delta_step': 2}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 13. Best value: 0.624765:  36%|███▌      | 18/50 [03:12<03:06,  5.83s/it]

[I 2025-12-01 19:54:32,067] Trial 20 pruned.

Best trial: 13. Best value: 0.624765:  38%|███▊      | 19/50 [03:23<03:48,  7.37s/it]

[I 2025-12-01 19:54:43,020] Trial 14 finished with value: 0.5792682926829269 and parameters: {'max_depth': 5, 'learning_rate': 0.2839822945956091, 'n_estimators': 1073, 'subsample': 0.5527652877706649, 'colsample_bytree': 0.9751244208681149, 'min_child_weight': 1, 'gamma': 0.04922916585472237, 'reg_alpha': 1.9236895224449547e-06, 'reg_lambda': 0.0067437399189631975, 'max_delta_step': 3}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 13. Best value: 0.624765:  40%|████      | 20/50 [03:35<04:22,  8.75s/it]

[I 2025-12-01 19:54:55,008] Trial 15 finished with value: 0.5722326454033771 and parameters: {'max_depth': 5, 'learning_rate': 0.28540285340615756, 'n_estimators': 1034, 'subsample': 0.5280184018024165, 'colsample_bytree': 0.9781639213904796, 'min_child_weight': 1, 'gamma': 0.02750816925591401, 'reg_alpha': 0.002033350518799304, 'reg_lambda': 0.00478023647247807, 'max_delta_step': 2}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 13. Best value: 0.624765:  42%|████▏     | 21/50 [04:07<07:37, 15.76s/it]

[I 2025-12-01 19:55:27,113] Trial 21 finished with value: 0.5478424015009381 and parameters: {'max_depth': 6, 'learning_rate': 0.18783659023360438, 'n_estimators': 968, 'subsample': 0.5844590402889352, 'colsample_bytree': 0.8204046734700587, 'min_child_weight': 3, 'gamma': 2.3267757243319425, 'reg_alpha': 0.017990728690934134, 'reg_lambda': 0.04106583016577306, 'max_delta_step': 0}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 13. Best value: 0.624765:  44%|████▍     | 22/50 [04:09<05:26, 11.65s/it]

[I 2025-12-01 19:55:29,159] Trial 19 finished with value: 0.49718574108818014 and parameters: {'max_depth': 10, 'learning_rate': 0.018885484846680452, 'n_estimators': 1050, 'subsample': 0.5433020042773679, 'colsample_bytree': 0.9027748224942582, 'min_child_weight': 3, 'gamma': 2.2057439712762736, 'reg_alpha': 1.9119225581160297e-06, 'reg_lambda': 4.2301764358395066e-05, 'max_delta_step': 2}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 13. Best value: 0.624765:  46%|████▌     | 23/50 [04:17<04:45, 10.57s/it]

[I 2025-12-01 19:55:37,218] Trial 22 finished with value: 0.5600375234521576 and parameters: {'max_depth': 6, 'learning_rate': 0.1646477098119878, 'n_estimators': 935, 'subsample': 0.5891267341930531, 'colsample_bytree': 0.8070114244833987, 'min_child_weight': 3, 'gamma': 2.1702888310248762, 'reg_alpha': 0.01371226830697656, 'reg_lambda': 0.06002120944012776, 'max_delta_step': 0}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 13. Best value: 0.624765:  48%|████▊     | 24/50 [04:27<04:32, 10.48s/it]

[I 2025-12-01 19:55:47,490] Trial 23 finished with value: 0.5600375234521576 and parameters: {'max_depth': 6, 'learning_rate': 0.15884860493574077, 'n_estimators': 891, 'subsample': 0.5930277374440666, 'colsample_bytree': 0.8068900668506195, 'min_child_weight': 3, 'gamma': 2.419601130233733, 'reg_alpha': 0.024162725075082922, 'reg_lambda': 0.07123216871610302, 'max_delta_step': 0}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 13. Best value: 0.624765:  50%|█████     | 25/50 [04:58<06:58, 16.72s/it]

[I 2025-12-01 19:56:18,768] Trial 25 finished with value: 0.5478424015009381 and parameters: {'max_depth': 4, 'learning_rate': 0.11504696410203925, 'n_estimators': 848, 'subsample': 0.6108489954856947, 'colsample_bytree': 0.9419162516046309, 'min_child_weight': 2, 'gamma': 0.9647333626032542, 'reg_alpha': 0.0004241061321201788, 'reg_lambda': 0.0009278600224689776, 'max_delta_step': 4}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 13. Best value: 0.624765:  52%|█████▏    | 26/50 [05:18<07:05, 17.73s/it]

[I 2025-12-01 19:56:38,863] Trial 24 finished with value: 0.5670731707317074 and parameters: {'max_depth': 4, 'learning_rate': 0.12327460261219844, 'n_estimators': 1212, 'subsample': 0.6146256787547582, 'colsample_bytree': 0.9215742701774834, 'min_child_weight': 2, 'gamma': 0.8872799547231334, 'reg_alpha': 0.0005593831875583752, 'reg_lambda': 0.00010249186925104914, 'max_delta_step': 10}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 13. Best value: 0.624765:  54%|█████▍    | 27/50 [05:26<05:38, 14.72s/it]

[I 2025-12-01 19:56:46,550] Trial 26 finished with value: 0.5286116322701688 and parameters: {'max_depth': 4, 'learning_rate': 0.11019850926215072, 'n_estimators': 1203, 'subsample': 0.7274098697832567, 'colsample_bytree': 0.9449942097737575, 'min_child_weight': 2, 'gamma': 0.9214846429809139, 'reg_alpha': 0.00020504596628746066, 'reg_lambda': 0.0006469782361623221, 'max_delta_step': 10}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 13. Best value: 0.624765:  56%|█████▌    | 28/50 [05:33<04:29, 12.27s/it]

[I 2025-12-01 19:56:53,099] Trial 30 pruned.

Best trial: 13. Best value: 0.624765:  58%|█████▊    | 29/50 [05:36<03:23,  9.68s/it]

[I 2025-12-01 19:56:56,741] Trial 27 finished with value: 0.5914634146341464 and parameters: {'max_depth': 4, 'learning_rate': 0.09271131397223507, 'n_estimators': 1201, 'subsample': 0.7196470670040088, 'colsample_bytree': 0.9445318052185234, 'min_child_weight': 2, 'gamma': 0.8923298891539944, 'reg_alpha': 0.00013799197571135735, 'reg_lambda': 0.0006484469772036995, 'max_delta_step': 4}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 13. Best value: 0.624765:  60%|██████    | 30/50 [05:39<02:32,  7.65s/it]

[I 2025-12-01 19:56:59,641] Trial 28 finished with value: 0.5792682926829269 and parameters: {'max_depth': 4, 'learning_rate': 0.10755516526223585, 'n_estimators': 679, 'subsample': 0.7092138663946737, 'colsample_bytree': 0.955015580933836, 'min_child_weight': 2, 'gamma': 0.5253223795826694, 'reg_alpha': 0.0003189125764370598, 'reg_lambda': 4.0475215486280886e-05, 'max_delta_step': 10}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 13. Best value: 0.624765:  62%|██████▏   | 31/50 [05:46<02:20,  7.41s/it]

[I 2025-12-01 19:57:06,504] Trial 31 pruned.

Best trial: 13. Best value: 0.624765:  64%|██████▍   | 32/50 [06:30<05:32, 18.46s/it]

[I 2025-12-01 19:57:50,732] Trial 29 finished with value: 0.5548780487804879 and parameters: {'max_depth': 4, 'learning_rate': 0.06951244515856923, 'n_estimators': 1208, 'subsample': 0.7153743000951203, 'colsample_bytree': 0.9509198931608637, 'min_child_weight': 4, 'gamma': 0.4970559559353823, 'reg_alpha': 0.00010453907198372022, 'reg_lambda': 5.076578774869345, 'max_delta_step': 3}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 13. Best value: 0.624765:  66%|██████▌   | 33/50 [06:57<05:55, 20.91s/it]

[I 2025-12-01 19:58:17,365] Trial 32 finished with value: 0.49718574108818014 and parameters: {'max_depth': 7, 'learning_rate': 0.03651379304192227, 'n_estimators': 1385, 'subsample': 0.7895718126402613, 'colsample_bytree': 0.9558335160850718, 'min_child_weight': 6, 'gamma': 1.4676846818053566, 'reg_alpha': 4.0472519408465653e-07, 'reg_lambda': 3.433075490793719e-05, 'max_delta_step': 9}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 13. Best value: 0.624765:  68%|██████▊   | 34/50 [07:03<04:21, 16.32s/it]

[I 2025-12-01 19:58:22,968] Trial 36 pruned.

Best trial: 13. Best value: 0.624765:  70%|███████   | 35/50 [07:03<02:52, 11.48s/it]

[I 2025-12-01 19:58:23,163] Trial 33 finished with value: 0.46575984990619135 and parameters: {'max_depth': 7, 'learning_rate': 0.030717469896226982, 'n_estimators': 1437, 'subsample': 0.7730152903189258, 'colsample_bytree': 0.8991662604734116, 'min_child_weight': 6, 'gamma': 1.5575400773662191, 'reg_alpha': 6.750246855555378e-08, 'reg_lambda': 5.49825143569834e-07, 'max_delta_step': 8}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 13. Best value: 0.624765:  72%|███████▏  | 36/50 [07:06<02:07,  9.09s/it]

[I 2025-12-01 19:58:26,681] Trial 38 pruned.

Best trial: 13. Best value: 0.624765:  74%|███████▍  | 37/50 [07:09<01:31,  7.07s/it]

[I 2025-12-01 19:58:29,030] Trial 34 finished with value: 0.49718574108818014 and parameters: {'max_depth': 3, 'learning_rate': 0.04655249585988217, 'n_estimators': 1438, 'subsample': 0.6520549014389464, 'colsample_bytree': 0.9102979257544557, 'min_child_weight': 6, 'gamma': 1.4142999263333826, 'reg_alpha': 6.480006969061504e-05, 'reg_lambda': 0.0018624973847016963, 'max_delta_step': 1}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 13. Best value: 0.624765:  76%|███████▌  | 38/50 [07:18<01:32,  7.72s/it]

[I 2025-12-01 19:58:38,287] Trial 39 pruned.

Best trial: 13. Best value: 0.624765:  78%|███████▊  | 39/50 [07:20<01:07,  6.15s/it]

[I 2025-12-01 19:58:40,753] Trial 40 pruned.

Best trial: 13. Best value: 0.624765:  80%|████████  | 40/50 [07:25<00:55,  5.59s/it]

[I 2025-12-01 19:58:45,044] Trial 41 pruned.

Best trial: 13. Best value: 0.624765:  82%|████████▏ | 41/50 [07:31<00:51,  5.71s/it]

[I 2025-12-01 19:58:51,022] Trial 42 pruned.

Best trial: 13. Best value: 0.624765:  84%|████████▍ | 42/50 [07:55<01:29, 11.20s/it]

[I 2025-12-01 19:59:15,046] Trial 35 finished with value: 0.4849906191369606 and parameters: {'max_depth': 3, 'learning_rate': 0.2033690830098971, 'n_estimators': 1458, 'subsample': 0.7711542335630248, 'colsample_bytree': 0.8519322253534654, 'min_child_weight': 6, 'gamma': 1.2824989368911344, 'reg_alpha': 1.1950477297016253e-08, 'reg_lambda': 0.0013815357350212163, 'max_delta_step': 8}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 13. Best value: 0.624765:  86%|████████▌ | 43/50 [08:17<01:41, 14.49s/it]

[I 2025-12-01 19:59:37,217] Trial 37 finished with value: 0.5914634146341464 and parameters: {'max_depth': 8, 'learning_rate': 0.21611863757026878, 'n_estimators': 1284, 'subsample': 0.6475852746348604, 'colsample_bytree': 0.8565119476964025, 'min_child_weight': 2, 'gamma': 0.35674554756037935, 'reg_alpha': 1.0402203665668885e-05, 'reg_lambda': 7.885755872085675e-06, 'max_delta_step': 1}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 13. Best value: 0.624765:  88%|████████▊ | 44/50 [08:34<01:31, 15.22s/it]

[I 2025-12-01 19:59:54,147] Trial 43 finished with value: 0.5984990619136961 and parameters: {'max_depth': 9, 'learning_rate': 0.2143113489304929, 'n_estimators': 1168, 'subsample': 0.6293061890306972, 'colsample_bytree': 0.7699171935432761, 'min_child_weight': 2, 'gamma': 0.30359393818567865, 'reg_alpha': 0.006411149459905585, 'reg_lambda': 0.00015048417684470453, 'max_delta_step': 7}. Best is trial 13 with value: 0.6247654784240151.

Best trial: 44. Best value: 0.629925:  90%|█████████ | 45/50 [08:39<01:00, 12.17s/it]

[I 2025-12-01 19:59:59,180] Trial 44 finished with value: 0.6299249530956847 and parameters: {'max_depth': 5, 'learning_rate': 0.22323220720128714, 'n_estimators': 1138, 'subsample': 0.5603635663623246, 'colsample_bytree': 0.9919585450662506, 'min_child_weight': 2, 'gamma': 0.24646822471300514, 'reg_alpha': 8.196401602077888e-06, 'reg_lambda': 1.226565338066812, 'max_delta_step': 3}. Best is trial 44 with value: 0.6299249530956847.

Best trial: 44. Best value: 0.629925:  92%|█████████▏| 46/50 [08:44<00:39,  9.99s/it]

[I 2025-12-01 20:00:04,079] Trial 47 pruned.

Best trial: 44. Best value: 0.629925:  94%|█████████▍| 47/50 [08:56<00:31, 10.62s/it]

[I 2025-12-01 20:00:16,179] Trial 49 pruned.

Best trial: 44. Best value: 0.629925:  96%|█████████▌| 48/50 [09:01<00:18,  9.12s/it]

[I 2025-12-01 20:00:21,793] Trial 45 finished with value: 0.6106941838649156 and parameters: {'max_depth': 5, 'learning_rate': 0.14111390948178135, 'n_estimators': 1134, 'subsample': 0.5544014485079861, 'colsample_bytree': 0.9761648230540139, 'min_child_weight': 2, 'gamma': 0.24407360476498396, 'reg_alpha': 7.686088412085737e-06, 'reg_lambda': 0.02376722020672741, 'max_delta_step': 3}. Best is trial 44 with value: 0.6299249530956847.

Best trial: 44. Best value: 0.629925:  98%|█████████▊| 49/50 [09:14<00:10, 10.08s/it]

[I 2025-12-01 20:00:34,110] Trial 46 finished with value: 0.5356472795497186 and parameters: {'max_depth': 9, 'learning_rate': 0.13103401111418814, 'n_estimators': 1333, 'subsample': 0.7341131380607201, 'colsample_bytree': 0.7529401776143163, 'min_child_weight': 2, 'gamma': 0.3029623401638234, 'reg_alpha': 9.780630840801015e-06, 'reg_lambda': 1.4590923461144836e-06, 'max_delta_step': 1}. Best is trial 44 with value: 0.6299249530956847.

Best trial: 44. Best value: 0.629925: 100%|██████████| 50/50 [09:16<00:00, 11.13s/it]

[I 2025-12-01 20:00:36,553] Trial 48 finished with value: 0.5093808630393997 and parameters: {'max_depth': 9, 'learning_rate': 0.14052245678069786, 'n_estimators': 1130, 'subsample': 0.5703654299570022, 'colsample_bytree': 0.7554660601119627, 'min_child_weight': 4, 'gamma': 0.6954658407333454, 'reg_alpha': 0.09309174196587663, 'reg_lambda': 0.5133258016552216, 'max_delta_step': 7}. Best is trial 44 with value: 0.6299249530956847.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 20:00:43,123] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 67, Test size: 17
Using Leave-One-Out CV with 67 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.379925:   2%|▏         | 1/50 [00:27<22:36, 27.69s/it]

[I 2025-12-01 20:01:10,802] Trial 2 finished with value: 0.37992495309568486 and parameters: {'max_depth': 6, 'learning_rate': 0.0336274359673502, 'n_estimators': 464, 'subsample': 0.942348000088671, 'colsample_bytree': 0.6460820959895344, 'min_child_weight': 10, 'gamma': 1.7349894512632502, 'reg_alpha': 2.106263720439176e-08, 'reg_lambda': 4.289159554297509, 'max_delta_step': 1}. Best is trial 2 with value: 0.37992495309568486.

Best trial: 2. Best value: 0.379925:   4%|▍         | 2/50 [00:29<10:03, 12.57s/it]

[I 2025-12-01 20:01:12,794] Trial 1 finished with value: 0.11538461538461539 and parameters: {'max_depth': 10, 'learning_rate': 0.1287402867100224, 'n_estimators': 504, 'subsample': 0.7099977488266668, 'colsample_bytree': 0.687226648488398, 'min_child_weight': 10, 'gamma': 2.4885901591665425, 'reg_alpha': 0.0021164709325571743, 'reg_lambda': 0.003149497927371169, 'max_delta_step': 6}. Best is trial 2 with value: 0.37992495309568486.

Best trial: 3. Best value: 0.560038:   6%|▌         | 3/50 [00:58<15:37, 19.95s/it]

[I 2025-12-01 20:01:41,525] Trial 3 finished with value: 0.5600375234521576 and parameters: {'max_depth': 5, 'learning_rate': 0.02599331479738875, 'n_estimators': 917, 'subsample': 0.5067985837626813, 'colsample_bytree': 0.5787014990303959, 'min_child_weight': 2, 'gamma': 0.9383147836930777, 'reg_alpha': 0.0006453289029541421, 'reg_lambda': 5.983807443775996, 'max_delta_step': 2}. Best is trial 3 with value: 0.5600375234521576.

Best trial: 3. Best value: 0.560038:   8%|▊         | 4/50 [01:20<15:58, 20.83s/it]

[I 2025-12-01 20:02:03,695] Trial 0 finished with value: 0.3048780487804878 and parameters: {'max_depth': 5, 'learning_rate': 0.2698970051422924, 'n_estimators': 1414, 'subsample': 0.568421197478662, 'colsample_bytree': 0.7568205844905793, 'min_child_weight': 8, 'gamma': 0.8725262057308564, 'reg_alpha': 0.0007380442737598228, 'reg_lambda': 0.01027853094994788, 'max_delta_step': 4}. Best is trial 3 with value: 0.5600375234521576.

Best trial: 3. Best value: 0.560038:  10%|█         | 5/50 [01:39<15:03, 20.08s/it]

[I 2025-12-01 20:02:22,465] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.016093067837693095, 'n_estimators': 1254, 'subsample': 0.9838842874666849, 'colsample_bytree': 0.9746224230660125, 'min_child_weight': 9, 'gamma': 2.0004280383407593, 'reg_alpha': 9.840144215617624, 'reg_lambda': 9.712611913833851e-05, 'max_delta_step': 8}. Best is trial 3 with value: 0.5600375234521576.

Best trial: 3. Best value: 0.560038:  12%|█▏        | 6/50 [01:45<11:12, 15.29s/it]

[I 2025-12-01 20:02:28,435] Trial 5 finished with value: 0.21951219512195122 and parameters: {'max_depth': 7, 'learning_rate': 0.0698055254424142, 'n_estimators': 1350, 'subsample': 0.5375995636545408, 'colsample_bytree': 0.6468202095735225, 'min_child_weight': 10, 'gamma': 4.648599569415896, 'reg_alpha': 1.6535634766733286e-05, 'reg_lambda': 0.0027476742708747314, 'max_delta_step': 1}. Best is trial 3 with value: 0.5600375234521576.

Best trial: 3. Best value: 0.560038:  14%|█▍        | 7/50 [02:12<13:38, 19.03s/it]

[I 2025-12-01 20:02:55,187] Trial 6 finished with value: 0.5112570356472796 and parameters: {'max_depth': 6, 'learning_rate': 0.08000259894944026, 'n_estimators': 1248, 'subsample': 0.6991650233142996, 'colsample_bytree': 0.9027758865175952, 'min_child_weight': 3, 'gamma': 4.598662928925937, 'reg_alpha': 7.515143506717722, 'reg_lambda': 0.0023226670342091625, 'max_delta_step': 5}. Best is trial 3 with value: 0.5600375234521576.

Best trial: 7. Best value: 0.572233:  16%|█▌        | 8/50 [02:16<10:00, 14.30s/it]

[I 2025-12-01 20:02:59,343] Trial 7 finished with value: 0.5722326454033771 and parameters: {'max_depth': 10, 'learning_rate': 0.08382441110028804, 'n_estimators': 917, 'subsample': 0.6835104212687372, 'colsample_bytree': 0.8347309522210362, 'min_child_weight': 1, 'gamma': 1.2714999456391196, 'reg_alpha': 0.05505037891014427, 'reg_lambda': 2.4334538335145172e-06, 'max_delta_step': 0}. Best is trial 7 with value: 0.5722326454033771.

Best trial: 7. Best value: 0.572233:  18%|█▊        | 9/50 [02:24<08:27, 12.37s/it]

[I 2025-12-01 20:03:07,487] Trial 8 finished with value: 0.5356472795497186 and parameters: {'max_depth': 6, 'learning_rate': 0.03095808855425524, 'n_estimators': 803, 'subsample': 0.7569141043389962, 'colsample_bytree': 0.6931593190977078, 'min_child_weight': 8, 'gamma': 4.911777844230037, 'reg_alpha': 8.128469898880971e-06, 'reg_lambda': 9.691613020351484, 'max_delta_step': 5}. Best is trial 7 with value: 0.5722326454033771.

Best trial: 7. Best value: 0.572233:  20%|██        | 10/50 [02:29<06:40, 10.01s/it]

[I 2025-12-01 20:03:12,218] Trial 10 finished with value: 0.5530018761726079 and parameters: {'max_depth': 10, 'learning_rate': 0.024936827540460307, 'n_estimators': 234, 'subsample': 0.8928275385737706, 'colsample_bytree': 0.65009046690729, 'min_child_weight': 4, 'gamma': 1.0403128967710313, 'reg_alpha': 0.00046203790231636946, 'reg_lambda': 2.8446029845346046, 'max_delta_step': 2}. Best is trial 7 with value: 0.5722326454033771.

Best trial: 7. Best value: 0.572233:  22%|██▏       | 11/50 [02:30<04:53,  7.52s/it]

[I 2025-12-01 20:03:14,088] Trial 11 pruned.

Best trial: 7. Best value: 0.572233:  24%|██▍       | 12/50 [02:39<05:01,  7.93s/it]

[I 2025-12-01 20:03:22,945] Trial 14 pruned.

Best trial: 7. Best value: 0.572233:  26%|██▌       | 13/50 [02:53<06:00,  9.74s/it]

[I 2025-12-01 20:03:36,844] Trial 9 finished with value: 0.5459662288930581 and parameters: {'max_depth': 9, 'learning_rate': 0.06828728492480843, 'n_estimators': 1220, 'subsample': 0.8862536914785024, 'colsample_bytree': 0.8190239687278991, 'min_child_weight': 5, 'gamma': 3.7508865464259262, 'reg_alpha': 0.7806243649414168, 'reg_lambda': 2.573369078153779e-06, 'max_delta_step': 3}. Best is trial 7 with value: 0.5722326454033771.

Best trial: 7. Best value: 0.572233:  28%|██▊       | 14/50 [03:02<05:39,  9.43s/it]

[I 2025-12-01 20:03:45,556] Trial 16 pruned.

Best trial: 7. Best value: 0.572233:  30%|███       | 15/50 [03:09<05:07,  8.78s/it]

[I 2025-12-01 20:03:52,841] Trial 12 finished with value: 0.5215759849906192 and parameters: {'max_depth': 8, 'learning_rate': 0.02625376094106551, 'n_estimators': 735, 'subsample': 0.8333077591697913, 'colsample_bytree': 0.7271717998425833, 'min_child_weight': 2, 'gamma': 2.8143005905299274, 'reg_alpha': 0.0038194645549260654, 'reg_lambda': 3.4520341579909832, 'max_delta_step': 1}. Best is trial 7 with value: 0.5722326454033771.

Best trial: 7. Best value: 0.572233:  32%|███▏      | 16/50 [03:23<05:45, 10.16s/it]

[I 2025-12-01 20:04:06,188] Trial 13 finished with value: 0.5651969981238274 and parameters: {'max_depth': 3, 'learning_rate': 0.15828804373943273, 'n_estimators': 961, 'subsample': 0.8276837988749306, 'colsample_bytree': 0.8304785316708967, 'min_child_weight': 1, 'gamma': 0.08517461913290214, 'reg_alpha': 0.0862737187617127, 'reg_lambda': 1.245820608234782e-07, 'max_delta_step': 9}. Best is trial 7 with value: 0.5722326454033771.

Best trial: 15. Best value: 0.635084:  34%|███▍      | 17/50 [03:42<07:02, 12.82s/it]

[I 2025-12-01 20:04:25,185] Trial 15 finished with value: 0.6350844277673546 and parameters: {'max_depth': 4, 'learning_rate': 0.05721603760106247, 'n_estimators': 1040, 'subsample': 0.6122946831170041, 'colsample_bytree': 0.826977234313296, 'min_child_weight': 1, 'gamma': 0.2174252506101677, 'reg_alpha': 0.030793323131287822, 'reg_lambda': 7.1488533692075426e-06, 'max_delta_step': 3}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  36%|███▌      | 18/50 [03:43<04:56,  9.27s/it]

[I 2025-12-01 20:04:26,189] Trial 17 finished with value: 0.5530018761726079 and parameters: {'max_depth': 4, 'learning_rate': 0.12827957511265312, 'n_estimators': 689, 'subsample': 0.6179572445549377, 'colsample_bytree': 0.8257566812038641, 'min_child_weight': 2, 'gamma': 0.1031282168803136, 'reg_alpha': 0.01951757522128717, 'reg_lambda': 0.05479251626708026, 'max_delta_step': 3}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  38%|███▊      | 19/50 [04:02<06:24, 12.41s/it]

[I 2025-12-01 20:04:45,923] Trial 19 finished with value: 0.5478424015009381 and parameters: {'max_depth': 3, 'learning_rate': 0.1334196821537039, 'n_estimators': 666, 'subsample': 0.6345309426828107, 'colsample_bytree': 0.8402301201123776, 'min_child_weight': 5, 'gamma': 0.11857626472315874, 'reg_alpha': 0.03548928929929603, 'reg_lambda': 1.0699947190397084e-08, 'max_delta_step': 10}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  40%|████      | 20/50 [04:12<05:51, 11.71s/it]

[I 2025-12-01 20:04:55,992] Trial 18 finished with value: 0.5478424015009381 and parameters: {'max_depth': 4, 'learning_rate': 0.14116167349658879, 'n_estimators': 1061, 'subsample': 0.6180419864010711, 'colsample_bytree': 0.8365209936238932, 'min_child_weight': 3, 'gamma': 0.3269949827804671, 'reg_alpha': 1.2417304821167117e-05, 'reg_lambda': 0.09003177696900412, 'max_delta_step': 10}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  42%|████▏     | 21/50 [04:49<09:13, 19.10s/it]

[I 2025-12-01 20:05:32,321] Trial 20 finished with value: 0.5914634146341464 and parameters: {'max_depth': 4, 'learning_rate': 0.10812302170753067, 'n_estimators': 1105, 'subsample': 0.615369839838931, 'colsample_bytree': 0.8798921727009655, 'min_child_weight': 6, 'gamma': 0.4604017191999398, 'reg_alpha': 0.01436375531225156, 'reg_lambda': 8.698595103988591e-06, 'max_delta_step': 3}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  44%|████▍     | 22/50 [04:50<06:23, 13.68s/it]

[I 2025-12-01 20:05:33,360] Trial 21 finished with value: 0.5984990619136961 and parameters: {'max_depth': 9, 'learning_rate': 0.04744714160513741, 'n_estimators': 1096, 'subsample': 0.6443748921778147, 'colsample_bytree': 0.9052746967570261, 'min_child_weight': 6, 'gamma': 1.684401215949526, 'reg_alpha': 1.733728610461058e-05, 'reg_lambda': 8.518746255632354e-06, 'max_delta_step': 10}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  46%|████▌     | 23/50 [05:08<06:44, 14.98s/it]

[I 2025-12-01 20:05:51,370] Trial 22 finished with value: 0.6106941838649156 and parameters: {'max_depth': 9, 'learning_rate': 0.04807736460390349, 'n_estimators': 1079, 'subsample': 0.6764092970910011, 'colsample_bytree': 0.9119092952238784, 'min_child_weight': 6, 'gamma': 1.6116000137311515, 'reg_alpha': 3.0280320843317844e-05, 'reg_lambda': 3.5052667564296835e-06, 'max_delta_step': 3}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  48%|████▊     | 24/50 [05:20<06:04, 14.01s/it]

[I 2025-12-01 20:06:03,118] Trial 23 finished with value: 0.6106941838649156 and parameters: {'max_depth': 9, 'learning_rate': 0.04780046829233829, 'n_estimators': 1132, 'subsample': 0.6799366803138113, 'colsample_bytree': 0.9238880665398577, 'min_child_weight': 6, 'gamma': 1.7080387871698788, 'reg_alpha': 0.8672133169386094, 'reg_lambda': 5.254852505368907e-06, 'max_delta_step': 3}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  50%|█████     | 25/50 [05:54<08:25, 20.22s/it]

[I 2025-12-01 20:06:37,807] Trial 24 finished with value: 0.6228893058161351 and parameters: {'max_depth': 5, 'learning_rate': 0.05162534252592363, 'n_estimators': 1117, 'subsample': 0.692063412088467, 'colsample_bytree': 0.9196798347598277, 'min_child_weight': 7, 'gamma': 1.5665552038422694, 'reg_alpha': 1.4099652829931222, 'reg_lambda': 6.779216268598916e-06, 'max_delta_step': 3}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  52%|█████▏    | 26/50 [05:56<05:53, 14.75s/it]

[I 2025-12-01 20:06:39,810] Trial 25 finished with value: 0.5914634146341464 and parameters: {'max_depth': 5, 'learning_rate': 0.04841812503332167, 'n_estimators': 1130, 'subsample': 0.57705391642695, 'colsample_bytree': 0.9317264868123475, 'min_child_weight': 7, 'gamma': 0.6530027904042648, 'reg_alpha': 7.713060074069216e-07, 'reg_lambda': 1.1094603253982692e-05, 'max_delta_step': 3}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  54%|█████▍    | 27/50 [06:14<06:02, 15.77s/it]

[I 2025-12-01 20:06:57,959] Trial 26 finished with value: 0.5914634146341464 and parameters: {'max_depth': 7, 'learning_rate': 0.04868428726854922, 'n_estimators': 1144, 'subsample': 0.6691946411964029, 'colsample_bytree': 0.9881608641457913, 'min_child_weight': 7, 'gamma': 1.7792764947948698, 'reg_alpha': 4.2389532833086195e-07, 'reg_lambda': 0.0002115204012048464, 'max_delta_step': 4}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  56%|█████▌    | 28/50 [06:48<07:45, 21.14s/it]

[I 2025-12-01 20:07:31,617] Trial 27 finished with value: 0.6158536585365854 and parameters: {'max_depth': 9, 'learning_rate': 0.052977530415828575, 'n_estimators': 1489, 'subsample': 0.7578888166725422, 'colsample_bytree': 0.979142403281515, 'min_child_weight': 7, 'gamma': 2.279925875211859, 'reg_alpha': 0.936689616532125, 'reg_lambda': 2.152985156041831e-07, 'max_delta_step': 4}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  58%|█████▊    | 29/50 [07:12<07:41, 21.99s/it]

[I 2025-12-01 20:07:55,609] Trial 29 finished with value: 0.5844277673545966 and parameters: {'max_depth': 7, 'learning_rate': 0.05848191528655194, 'n_estimators': 1333, 'subsample': 0.736553691586113, 'colsample_bytree': 0.9896700955920196, 'min_child_weight': 7, 'gamma': 2.3129087737538248, 'reg_alpha': 9.591189206659194e-05, 'reg_lambda': 1.7688706124716778e-07, 'max_delta_step': 4}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  60%|██████    | 30/50 [07:25<06:23, 19.15s/it]

[I 2025-12-01 20:08:08,132] Trial 28 finished with value: 0.6158536585365854 and parameters: {'max_depth': 5, 'learning_rate': 0.0533388788611568, 'n_estimators': 1492, 'subsample': 0.7402942061486607, 'colsample_bytree': 0.99389927689992, 'min_child_weight': 7, 'gamma': 2.4248565692341075, 'reg_alpha': 1.010949573802712e-06, 'reg_lambda': 3.680448905649052e-07, 'max_delta_step': 4}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  62%|██████▏   | 31/50 [07:38<05:30, 17.40s/it]

[I 2025-12-01 20:08:21,444] Trial 33 pruned.

Best trial: 15. Best value: 0.635084:  64%|██████▍   | 32/50 [07:45<04:15, 14.20s/it]

[I 2025-12-01 20:08:28,169] Trial 30 finished with value: 0.5844277673545966 and parameters: {'max_depth': 5, 'learning_rate': 0.06511395780904225, 'n_estimators': 1468, 'subsample': 0.7375214918253086, 'colsample_bytree': 0.777519919612788, 'min_child_weight': 4, 'gamma': 2.3295285388798064, 'reg_alpha': 0.000132973871241834, 'reg_lambda': 2.2612615189095781e-07, 'max_delta_step': 4}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  66%|██████▌   | 33/50 [08:17<05:35, 19.71s/it]

[I 2025-12-01 20:09:00,751] Trial 31 finished with value: 0.6036585365853658 and parameters: {'max_depth': 5, 'learning_rate': 0.062188955259738665, 'n_estimators': 1497, 'subsample': 0.7439191372761595, 'colsample_bytree': 0.7896002712139676, 'min_child_weight': 8, 'gamma': 2.6736104225319766, 'reg_alpha': 1.0462118422261029, 'reg_lambda': 2.1564403689314766e-07, 'max_delta_step': 6}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  68%|██████▊   | 34/50 [08:34<05:01, 18.86s/it]

[I 2025-12-01 20:09:17,638] Trial 32 finished with value: 0.5600375234521576 and parameters: {'max_depth': 5, 'learning_rate': 0.0947589247995484, 'n_estimators': 1428, 'subsample': 0.7707238557026912, 'colsample_bytree': 0.7836338631999108, 'min_child_weight': 8, 'gamma': 3.2610950520481063, 'reg_alpha': 0.6252278025034714, 'reg_lambda': 3.3233696365902643e-07, 'max_delta_step': 5}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  70%|███████   | 35/50 [08:46<04:10, 16.69s/it]

[I 2025-12-01 20:09:29,258] Trial 37 pruned.

Best trial: 15. Best value: 0.635084:  72%|███████▏  | 36/50 [09:05<04:04, 17.48s/it]

[I 2025-12-01 20:09:48,587] Trial 35 finished with value: 0.5670731707317074 and parameters: {'max_depth': 5, 'learning_rate': 0.09446539161396184, 'n_estimators': 1382, 'subsample': 0.7728611854229469, 'colsample_bytree': 0.9554969124977108, 'min_child_weight': 9, 'gamma': 2.8532554420667156, 'reg_alpha': 0.32469577912663344, 'reg_lambda': 6.742924228506187e-07, 'max_delta_step': 6}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  74%|███████▍  | 37/50 [09:06<02:43, 12.61s/it]

[I 2025-12-01 20:09:49,842] Trial 34 finished with value: 0.5914634146341464 and parameters: {'max_depth': 5, 'learning_rate': 0.09155301211615653, 'n_estimators': 1499, 'subsample': 0.7644127158665369, 'colsample_bytree': 0.9427756470377111, 'min_child_weight': 7, 'gamma': 2.186141748682634, 'reg_alpha': 0.42171962418400655, 'reg_lambda': 4.3250169325554236e-07, 'max_delta_step': 4}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  76%|███████▌  | 38/50 [09:17<02:23, 11.96s/it]

[I 2025-12-01 20:10:00,286] Trial 40 pruned.

Best trial: 15. Best value: 0.635084:  78%|███████▊  | 39/50 [09:35<02:31, 13.80s/it]

[I 2025-12-01 20:10:18,372] Trial 36 finished with value: 0.5548780487804879 and parameters: {'max_depth': 6, 'learning_rate': 0.0886983593148311, 'n_estimators': 1352, 'subsample': 0.7871200353276327, 'colsample_bytree': 0.9557146762701292, 'min_child_weight': 9, 'gamma': 3.3043006161212314, 'reg_alpha': 0.3321161367574742, 'reg_lambda': 5.407575781043621e-07, 'max_delta_step': 2}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  80%|████████  | 40/50 [10:04<03:05, 18.54s/it]

[I 2025-12-01 20:10:47,987] Trial 38 finished with value: 0.6228893058161351 and parameters: {'max_depth': 4, 'learning_rate': 0.03901031938317622, 'n_estimators': 1382, 'subsample': 0.7908846687485881, 'colsample_bytree': 0.9507215445350069, 'min_child_weight': 7, 'gamma': 2.02886074589445, 'reg_alpha': 0.005520619086907637, 'reg_lambda': 4.7732308288683735e-05, 'max_delta_step': 2}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  82%|████████▏ | 41/50 [10:08<02:05, 14.00s/it]

[I 2025-12-01 20:10:51,369] Trial 42 finished with value: 0.6106941838649156 and parameters: {'max_depth': 4, 'learning_rate': 0.03025294567873684, 'n_estimators': 531, 'subsample': 0.8219316648863475, 'colsample_bytree': 0.9989231776436214, 'min_child_weight': 7, 'gamma': 1.3392452395047163, 'reg_alpha': 2.752476092982444, 'reg_lambda': 0.0004049941470519958, 'max_delta_step': 5}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  84%|████████▍ | 42/50 [10:15<01:34, 11.83s/it]

[I 2025-12-01 20:10:58,161] Trial 39 finished with value: 0.6106941838649156 and parameters: {'max_depth': 4, 'learning_rate': 0.03894369560907446, 'n_estimators': 1218, 'subsample': 0.831337940327937, 'colsample_bytree': 0.8664917225182796, 'min_child_weight': 7, 'gamma': 2.0103499068076403, 'reg_alpha': 3.870087877782121, 'reg_lambda': 3.8060357791218865e-05, 'max_delta_step': 4}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  86%|████████▌ | 43/50 [10:33<01:37, 13.97s/it]

[I 2025-12-01 20:11:17,099] Trial 41 finished with value: 0.5863039399624765 and parameters: {'max_depth': 6, 'learning_rate': 0.029433102295911256, 'n_estimators': 1281, 'subsample': 0.8153833652100319, 'colsample_bytree': 0.998980720154067, 'min_child_weight': 7, 'gamma': 1.2912247936508945, 'reg_alpha': 4.798379527836185, 'reg_lambda': 4.371333008856247e-08, 'max_delta_step': 5}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  88%|████████▊ | 44/50 [10:46<01:20, 13.42s/it]

[I 2025-12-01 20:11:29,260] Trial 46 pruned.

Best trial: 15. Best value: 0.635084:  90%|█████████ | 45/50 [11:23<01:43, 20.60s/it]

[I 2025-12-01 20:12:06,612] Trial 44 finished with value: 0.6036585365853658 and parameters: {'max_depth': 3, 'learning_rate': 0.04089457231176341, 'n_estimators': 1307, 'subsample': 0.7212568477806972, 'colsample_bytree': 0.8839447473545405, 'min_child_weight': 7, 'gamma': 2.4938662331184225, 'reg_alpha': 2.455902714738579, 'reg_lambda': 2.6624404472721454e-05, 'max_delta_step': 1}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  92%|█████████▏| 46/50 [11:24<00:58, 14.68s/it]

[I 2025-12-01 20:12:07,483] Trial 43 finished with value: 0.5530018761726079 and parameters: {'max_depth': 3, 'learning_rate': 0.02990963991715843, 'n_estimators': 1293, 'subsample': 0.8212685438074008, 'colsample_bytree': 0.8795828327701284, 'min_child_weight': 4, 'gamma': 1.3379862641926574, 'reg_alpha': 3.032874414594925, 'reg_lambda': 0.0006376030712685281, 'max_delta_step': 1}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  94%|█████████▍| 47/50 [11:29<00:35, 11.85s/it]

[I 2025-12-01 20:12:12,715] Trial 45 finished with value: 0.5408067542213884 and parameters: {'max_depth': 3, 'learning_rate': 0.07204088788603366, 'n_estimators': 1305, 'subsample': 0.7158506616807842, 'colsample_bytree': 0.8913708199946548, 'min_child_weight': 8, 'gamma': 2.590798223158215, 'reg_alpha': 0.002866282329788575, 'reg_lambda': 0.0006336550828817266, 'max_delta_step': 1}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  96%|█████████▌| 48/50 [11:59<00:34, 17.21s/it]

[I 2025-12-01 20:12:42,439] Trial 47 finished with value: 0.6177298311444652 and parameters: {'max_depth': 7, 'learning_rate': 0.021978544873115017, 'n_estimators': 1423, 'subsample': 0.8761302448212588, 'colsample_bytree': 0.9651696559711659, 'min_child_weight': 8, 'gamma': 2.052224105778818, 'reg_alpha': 0.17686083786608953, 'reg_lambda': 1.8360841079494032e-06, 'max_delta_step': 2}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084:  98%|█████████▊| 49/50 [12:14<00:16, 16.53s/it]

[I 2025-12-01 20:12:57,382] Trial 49 finished with value: 0.5984990619136961 and parameters: {'max_depth': 7, 'learning_rate': 0.29459328924172357, 'n_estimators': 1392, 'subsample': 0.8577448478840173, 'colsample_bytree': 0.9711241634207374, 'min_child_weight': 8, 'gamma': 0.7886963474808768, 'reg_alpha': 0.17087807548784084, 'reg_lambda': 2.656281497466426e-06, 'max_delta_step': 2}. Best is trial 15 with value: 0.6350844277673546.

Best trial: 15. Best value: 0.635084: 100%|██████████| 50/50 [12:14<00:00, 14.69s/it]

[I 2025-12-01 20:12:57,680] Trial 48 finished with value: 0.5844277673545966 and parameters: {'max_depth': 7, 'learning_rate': 0.05536793515118317, 'n_estimators': 1404, 'subsample': 0.8618366536082361, 'colsample_bytree': 0.9634459807606226, 'min_child_weight': 8, 'gamma': 0.910054307684411, 'reg_alpha': 1.6289912808294267e-08, 'reg_lambda': 2.543808180688693e-06, 'max_delta_step': 2}. Best is trial 15 with value: 0.6350844277673546.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 20:13:02,945] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 67, Test size: 17
Using Leave-One-Out CV with 67 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.292683:   2%|▏         | 1/50 [00:14<11:31, 14.12s/it]

[I 2025-12-01 20:13:17,058] Trial 3 finished with value: 0.2926829268292683 and parameters: {'max_depth': 9, 'learning_rate': 0.01107605737458049, 'n_estimators': 216, 'subsample': 0.7218947040966324, 'colsample_bytree': 0.9176307666490316, 'min_child_weight': 10, 'gamma': 3.7628033293594667, 'reg_alpha': 0.0003472877760384859, 'reg_lambda': 4.877101368914217e-05, 'max_delta_step': 4}. Best is trial 3 with value: 0.2926829268292683.

Best trial: 2. Best value: 0.528612:   4%|▍         | 2/50 [00:27<10:45, 13.46s/it]

[I 2025-12-01 20:13:30,048] Trial 2 finished with value: 0.5286116322701688 and parameters: {'max_depth': 4, 'learning_rate': 0.12153157422871017, 'n_estimators': 446, 'subsample': 0.6537673425174537, 'colsample_bytree': 0.6322928538358699, 'min_child_weight': 4, 'gamma': 4.6412219563619175, 'reg_alpha': 5.434620740869717, 'reg_lambda': 6.79556993534643e-06, 'max_delta_step': 10}. Best is trial 2 with value: 0.5286116322701688.

Best trial: 2. Best value: 0.528612:   6%|▌         | 3/50 [00:31<07:28,  9.53s/it]

[I 2025-12-01 20:13:34,911] Trial 1 finished with value: 0.18292682926829268 and parameters: {'max_depth': 6, 'learning_rate': 0.01483429866823952, 'n_estimators': 537, 'subsample': 0.6101445597972207, 'colsample_bytree': 0.9760711946540271, 'min_child_weight': 10, 'gamma': 1.9966987121549025, 'reg_alpha': 5.87290290112308e-08, 'reg_lambda': 1.3418100361820137e-05, 'max_delta_step': 4}. Best is trial 2 with value: 0.5286116322701688.

Best trial: 2. Best value: 0.528612:   8%|▊         | 4/50 [00:58<12:30, 16.31s/it]

[I 2025-12-01 20:14:01,611] Trial 4 finished with value: 0.44652908067542213 and parameters: {'max_depth': 6, 'learning_rate': 0.10788949005395572, 'n_estimators': 799, 'subsample': 0.8063882505124325, 'colsample_bytree': 0.549064373758956, 'min_child_weight': 5, 'gamma': 1.1735066134866545, 'reg_alpha': 1.566007661564088e-05, 'reg_lambda': 0.014434005933971773, 'max_delta_step': 9}. Best is trial 2 with value: 0.5286116322701688.

Best trial: 6. Best value: 0.577392:  10%|█         | 5/50 [01:24<14:44, 19.65s/it]

[I 2025-12-01 20:14:27,175] Trial 6 finished with value: 0.5773921200750469 and parameters: {'max_depth': 7, 'learning_rate': 0.03749752801288084, 'n_estimators': 861, 'subsample': 0.7183271761955522, 'colsample_bytree': 0.8494860032896141, 'min_child_weight': 1, 'gamma': 3.341573271483345, 'reg_alpha': 6.939955402415584e-08, 'reg_lambda': 1.4102951465241229e-08, 'max_delta_step': 10}. Best is trial 6 with value: 0.5773921200750469.

Best trial: 6. Best value: 0.577392:  12%|█▏        | 6/50 [01:26<09:59, 13.62s/it]

[I 2025-12-01 20:14:29,081] Trial 0 finished with value: 0.5600375234521576 and parameters: {'max_depth': 8, 'learning_rate': 0.246446315522021, 'n_estimators': 1473, 'subsample': 0.8454088871474381, 'colsample_bytree': 0.8383023489688963, 'min_child_weight': 1, 'gamma': 3.821918838269795, 'reg_alpha': 1.875691300295488e-08, 'reg_lambda': 4.39292274032261e-06, 'max_delta_step': 5}. Best is trial 6 with value: 0.5773921200750469.

Best trial: 6. Best value: 0.577392:  14%|█▍        | 7/50 [01:36<08:54, 12.44s/it]

[I 2025-12-01 20:14:39,107] Trial 5 finished with value: 0.5619136960600375 and parameters: {'max_depth': 4, 'learning_rate': 0.032642111414513, 'n_estimators': 1234, 'subsample': 0.8715691912207554, 'colsample_bytree': 0.8235740582558253, 'min_child_weight': 8, 'gamma': 0.13357344293614737, 'reg_alpha': 5.9262395327352015, 'reg_lambda': 0.09755867211195428, 'max_delta_step': 1}. Best is trial 6 with value: 0.5773921200750469.

Best trial: 6. Best value: 0.577392:  16%|█▌        | 8/50 [02:00<11:21, 16.23s/it]

[I 2025-12-01 20:15:03,452] Trial 9 finished with value: 0.5408067542213884 and parameters: {'max_depth': 4, 'learning_rate': 0.037847216003628795, 'n_estimators': 621, 'subsample': 0.66128995487271, 'colsample_bytree': 0.8335512869544315, 'min_child_weight': 7, 'gamma': 4.994353292984577, 'reg_alpha': 0.00045820545194677145, 'reg_lambda': 0.00023744462937113587, 'max_delta_step': 5}. Best is trial 6 with value: 0.5773921200750469.

Best trial: 6. Best value: 0.577392:  18%|█▊        | 9/50 [02:00<07:42, 11.28s/it]

[I 2025-12-01 20:15:03,858] Trial 10 finished with value: 0.5337711069418387 and parameters: {'max_depth': 6, 'learning_rate': 0.1319474729513793, 'n_estimators': 409, 'subsample': 0.74510732414845, 'colsample_bytree': 0.6929876986240546, 'min_child_weight': 2, 'gamma': 4.833830209700579, 'reg_alpha': 0.8752592190447142, 'reg_lambda': 6.530045680496949e-05, 'max_delta_step': 7}. Best is trial 6 with value: 0.5773921200750469.

Best trial: 8. Best value: 0.596623:  20%|██        | 10/50 [02:09<06:54, 10.36s/it]

[I 2025-12-01 20:15:12,157] Trial 8 finished with value: 0.5966228893058161 and parameters: {'max_depth': 10, 'learning_rate': 0.09182815345810419, 'n_estimators': 769, 'subsample': 0.974936700606118, 'colsample_bytree': 0.6171616415622387, 'min_child_weight': 2, 'gamma': 1.5021392211702722, 'reg_alpha': 1.688979633440296e-05, 'reg_lambda': 0.005710020715374019, 'max_delta_step': 6}. Best is trial 8 with value: 0.5966228893058161.

Best trial: 8. Best value: 0.596623:  22%|██▏       | 11/50 [02:10<04:56,  7.60s/it]

[I 2025-12-01 20:15:13,499] Trial 11 pruned.

Best trial: 8. Best value: 0.596623:  24%|██▍       | 12/50 [02:11<03:35,  5.66s/it]

[I 2025-12-01 20:15:14,716] Trial 12 pruned.

Best trial: 7. Best value: 0.636961:  26%|██▌       | 13/50 [02:26<05:15,  8.52s/it]

[I 2025-12-01 20:15:29,832] Trial 7 finished with value: 0.6369606003752346 and parameters: {'max_depth': 3, 'learning_rate': 0.029410779384726658, 'n_estimators': 1491, 'subsample': 0.9646079511715818, 'colsample_bytree': 0.8159847016106841, 'min_child_weight': 1, 'gamma': 3.72704736211084, 'reg_alpha': 3.528612288901193, 'reg_lambda': 0.0037184109246410006, 'max_delta_step': 7}. Best is trial 7 with value: 0.6369606003752346.

Best trial: 7. Best value: 0.636961:  28%|██▊       | 14/50 [02:35<05:02,  8.41s/it]

[I 2025-12-01 20:15:37,987] Trial 16 pruned.

Best trial: 7. Best value: 0.636961:  30%|███       | 15/50 [03:02<08:19, 14.26s/it]

[I 2025-12-01 20:16:05,813] Trial 15 finished with value: 0.6158536585365854 and parameters: {'max_depth': 8, 'learning_rate': 0.06378240695745309, 'n_estimators': 895, 'subsample': 0.9998093290672325, 'colsample_bytree': 0.5261730499019706, 'min_child_weight': 3, 'gamma': 2.8523852815324133, 'reg_alpha': 6.537174428337032e-07, 'reg_lambda': 2.0041922421525845e-07, 'max_delta_step': 7}. Best is trial 7 with value: 0.6369606003752346.

Best trial: 7. Best value: 0.636961:  32%|███▏      | 16/50 [03:04<05:53, 10.39s/it]

[I 2025-12-01 20:16:07,216] Trial 14 finished with value: 0.5844277673545966 and parameters: {'max_depth': 10, 'learning_rate': 0.024738014912472323, 'n_estimators': 921, 'subsample': 0.9711468778092843, 'colsample_bytree': 0.504594300917727, 'min_child_weight': 3, 'gamma': 1.7874942151439825, 'reg_alpha': 8.939659775125196e-07, 'reg_lambda': 2.6125112514295486e-08, 'max_delta_step': 1}. Best is trial 7 with value: 0.6369606003752346.

Best trial: 7. Best value: 0.636961:  34%|███▍      | 17/50 [03:09<04:48,  8.75s/it]

[I 2025-12-01 20:16:12,136] Trial 13 finished with value: 0.5530018761726079 and parameters: {'max_depth': 10, 'learning_rate': 0.2938305544848202, 'n_estimators': 1072, 'subsample': 0.9902967404019843, 'colsample_bytree': 0.5121351750815129, 'min_child_weight': 3, 'gamma': 1.8919605736228875, 'reg_alpha': 0.025334138254910578, 'reg_lambda': 2.743593550492436, 'max_delta_step': 1}. Best is trial 7 with value: 0.6369606003752346.

Best trial: 7. Best value: 0.636961:  36%|███▌      | 18/50 [03:15<04:11,  7.87s/it]

[I 2025-12-01 20:16:17,960] Trial 19 pruned.

Best trial: 7. Best value: 0.636961:  38%|███▊      | 19/50 [03:22<03:59,  7.73s/it]

[I 2025-12-01 20:16:25,363] Trial 20 pruned.

Best trial: 7. Best value: 0.636961:  40%|████      | 20/50 [03:27<03:29,  6.97s/it]

[I 2025-12-01 20:16:30,566] Trial 21 pruned.

Best trial: 7. Best value: 0.636961:  42%|████▏     | 21/50 [03:33<03:13,  6.69s/it]

[I 2025-12-01 20:16:36,586] Trial 22 pruned.

Best trial: 7. Best value: 0.636961:  44%|████▍     | 22/50 [03:54<05:03, 10.84s/it]

[I 2025-12-01 20:16:57,120] Trial 17 finished with value: 0.5286116322701688 and parameters: {'max_depth': 8, 'learning_rate': 0.08421098376658699, 'n_estimators': 1429, 'subsample': 0.993680142716669, 'colsample_bytree': 0.5962107817773102, 'min_child_weight': 3, 'gamma': 0.7224917556752698, 'reg_alpha': 0.01313944108509039, 'reg_lambda': 2.0253150016344406, 'max_delta_step': 7}. Best is trial 7 with value: 0.6369606003752346.

Best trial: 7. Best value: 0.636961:  46%|████▌     | 23/50 [04:07<05:10, 11.51s/it]

[I 2025-12-01 20:17:10,174] Trial 23 finished with value: 0.5356472795497186 and parameters: {'max_depth': 3, 'learning_rate': 0.020705473755098028, 'n_estimators': 674, 'subsample': 0.9207125581870095, 'colsample_bytree': 0.5797826951921939, 'min_child_weight': 4, 'gamma': 3.61768000345881, 'reg_alpha': 0.002621375235600362, 'reg_lambda': 0.0013743990461987936, 'max_delta_step': 6}. Best is trial 7 with value: 0.6369606003752346.

Best trial: 7. Best value: 0.636961:  48%|████▊     | 24/50 [04:13<04:15,  9.83s/it]

[I 2025-12-01 20:17:16,092] Trial 24 finished with value: 0.6036585365853658 and parameters: {'max_depth': 9, 'learning_rate': 0.084894950165577, 'n_estimators': 681, 'subsample': 0.9259567104110066, 'colsample_bytree': 0.590876529037394, 'min_child_weight': 2, 'gamma': 3.554987591958487, 'reg_alpha': 7.21919093995903e-06, 'reg_lambda': 0.002145483471539081, 'max_delta_step': 6}. Best is trial 7 with value: 0.6369606003752346.

Best trial: 7. Best value: 0.636961:  50%|█████     | 25/50 [04:22<03:59,  9.56s/it]

[I 2025-12-01 20:17:25,034] Trial 27 pruned.

Best trial: 7. Best value: 0.636961:  52%|█████▏    | 26/50 [04:27<03:18,  8.28s/it]

[I 2025-12-01 20:17:30,312] Trial 18 finished with value: 0.5722326454033771 and parameters: {'max_depth': 8, 'learning_rate': 0.018888336975210814, 'n_estimators': 1410, 'subsample': 0.9113274299368219, 'colsample_bytree': 0.7534327374323804, 'min_child_weight': 3, 'gamma': 2.5758926304866914, 'reg_alpha': 0.04618404694808984, 'reg_lambda': 4.093436716092263, 'max_delta_step': 3}. Best is trial 7 with value: 0.6369606003752346.

Best trial: 7. Best value: 0.636961:  54%|█████▍    | 27/50 [04:28<02:19,  6.09s/it]

[I 2025-12-01 20:17:31,288] Trial 28 pruned.

Best trial: 7. Best value: 0.636961:  56%|█████▌    | 28/50 [04:33<02:05,  5.69s/it]

[I 2025-12-01 20:17:36,050] Trial 30 pruned.

Best trial: 7. Best value: 0.636961:  58%|█████▊    | 29/50 [04:33<01:25,  4.07s/it]

[I 2025-12-01 20:17:36,345] Trial 29 pruned.

Best trial: 7. Best value: 0.636961:  60%|██████    | 30/50 [04:36<01:15,  3.80s/it]

[I 2025-12-01 20:17:39,510] Trial 25 finished with value: 0.5792682926829269 and parameters: {'max_depth': 9, 'learning_rate': 0.08696955216218408, 'n_estimators': 725, 'subsample': 0.9348127963161887, 'colsample_bytree': 0.5888375291843992, 'min_child_weight': 2, 'gamma': 3.4262162609986797, 'reg_alpha': 5.724094705630829e-06, 'reg_lambda': 0.001885947060036338, 'max_delta_step': 6}. Best is trial 7 with value: 0.6369606003752346.

Best trial: 7. Best value: 0.636961:  62%|██████▏   | 31/50 [04:42<01:23,  4.42s/it]

[I 2025-12-01 20:17:45,376] Trial 31 pruned.

Best trial: 7. Best value: 0.636961:  64%|██████▍   | 32/50 [04:43<01:03,  3.52s/it]

[I 2025-12-01 20:17:46,798] Trial 32 pruned.

Best trial: 7. Best value: 0.636961:  66%|██████▌   | 33/50 [04:46<00:54,  3.19s/it]

[I 2025-12-01 20:17:49,216] Trial 33 pruned.

Best trial: 7. Best value: 0.636961:  68%|██████▊   | 34/50 [04:49<00:52,  3.30s/it]

[I 2025-12-01 20:17:52,764] Trial 34 pruned.

Best trial: 7. Best value: 0.636961:  70%|███████   | 35/50 [04:51<00:41,  2.76s/it]

[I 2025-12-01 20:17:54,271] Trial 35 pruned.

Best trial: 7. Best value: 0.636961:  72%|███████▏  | 36/50 [04:52<00:32,  2.33s/it]

[I 2025-12-01 20:17:55,585] Trial 26 finished with value: 0.5651969981238274 and parameters: {'max_depth': 9, 'learning_rate': 0.1592368057453344, 'n_estimators': 772, 'subsample': 0.9387778638710691, 'colsample_bytree': 0.6617514939859921, 'min_child_weight': 2, 'gamma': 1.272761971192943, 'reg_alpha': 6.8554844112710075e-06, 'reg_lambda': 0.01544611129254746, 'max_delta_step': 6}. Best is trial 7 with value: 0.6369606003752346.

Best trial: 7. Best value: 0.636961:  74%|███████▍  | 37/50 [04:53<00:24,  1.88s/it]

[I 2025-12-01 20:17:56,427] Trial 36 pruned.

Best trial: 7. Best value: 0.636961:  76%|███████▌  | 38/50 [04:58<00:32,  2.70s/it]

[I 2025-12-01 20:18:01,032] Trial 40 pruned.

Best trial: 7. Best value: 0.636961:  78%|███████▊  | 39/50 [05:06<00:47,  4.35s/it]

[I 2025-12-01 20:18:09,251] Trial 41 pruned.

Best trial: 7. Best value: 0.636961:  80%|████████  | 40/50 [05:24<01:24,  8.40s/it]

[I 2025-12-01 20:18:27,096] Trial 38 finished with value: 0.5478424015009381 and parameters: {'max_depth': 8, 'learning_rate': 0.06092035897621796, 'n_estimators': 560, 'subsample': 0.9957830299640139, 'colsample_bytree': 0.5354432494823423, 'min_child_weight': 3, 'gamma': 1.4456111878666145, 'reg_alpha': 0.00019432315011065618, 'reg_lambda': 0.00013292821880071465, 'max_delta_step': 8}. Best is trial 7 with value: 0.6369606003752346.

Best trial: 7. Best value: 0.636961:  82%|████████▏ | 41/50 [05:24<00:54,  6.05s/it]

[I 2025-12-01 20:18:27,657] Trial 37 finished with value: 0.6158536585365854 and parameters: {'max_depth': 10, 'learning_rate': 0.06604451302504664, 'n_estimators': 557, 'subsample': 0.9532760575731005, 'colsample_bytree': 0.9798677418590701, 'min_child_weight': 2, 'gamma': 2.2341334211877353, 'reg_alpha': 1.4693074380567077e-07, 'reg_lambda': 0.005808152654262909, 'max_delta_step': 4}. Best is trial 7 with value: 0.6369606003752346.

Best trial: 7. Best value: 0.636961:  84%|████████▍ | 42/50 [05:28<00:43,  5.47s/it]

[I 2025-12-01 20:18:31,763] Trial 44 pruned.

Best trial: 7. Best value: 0.636961:  86%|████████▌ | 43/50 [05:36<00:42,  6.09s/it]

[I 2025-12-01 20:18:39,306] Trial 43 pruned.

Best trial: 7. Best value: 0.636961:  88%|████████▊ | 44/50 [05:40<00:33,  5.56s/it]

[I 2025-12-01 20:18:43,638] Trial 42 finished with value: 0.5478424015009381 and parameters: {'max_depth': 8, 'learning_rate': 0.07764924386610636, 'n_estimators': 599, 'subsample': 0.9881127975681487, 'colsample_bytree': 0.538447338738384, 'min_child_weight': 4, 'gamma': 4.518822990637523, 'reg_alpha': 1.340454225997685e-05, 'reg_lambda': 2.8386219512743048e-05, 'max_delta_step': 9}. Best is trial 7 with value: 0.6369606003752346.

Best trial: 7. Best value: 0.636961:  92%|█████████▏| 46/50 [05:43<00:13,  3.39s/it]

[I 2025-12-01 20:18:46,579] Trial 39 finished with value: 0.5164165103189493 and parameters: {'max_depth': 8, 'learning_rate': 0.06212867191876719, 'n_estimators': 895, 'subsample': 0.894971277484224, 'colsample_bytree': 0.7033399678583379, 'min_child_weight': 3, 'gamma': 2.20627984312358, 'reg_alpha': 0.0002609540070186882, 'reg_lambda': 7.31910318026418e-05, 'max_delta_step': 8}. Best is trial 7 with value: 0.6369606003752346.
[I 2025-12-01 20:18:46,739] Trial 47 pruned.

Best trial: 7. Best value: 0.636961:  94%|█████████▍| 47/50 [05:47<00:10,  3.57s/it]

[I 2025-12-01 20:18:50,721] Trial 49 pruned.

Best trial: 45. Best value: 0.654315:  96%|█████████▌| 48/50 [06:01<00:13,  6.57s/it]

[I 2025-12-01 20:19:04,286] Trial 45 finished with value: 0.6543151969981238 and parameters: {'max_depth': 9, 'learning_rate': 0.06911161495549605, 'n_estimators': 619, 'subsample': 0.9993357211304564, 'colsample_bytree': 0.9551005948006194, 'min_child_weight': 2, 'gamma': 3.6732812147979415, 'reg_alpha': 1.4218883895622705e-05, 'reg_lambda': 7.2155813790214565e-06, 'max_delta_step': 4}. Best is trial 45 with value: 0.6543151969981238.

Best trial: 45. Best value: 0.654315:  98%|█████████▊| 49/50 [06:01<00:04,  4.67s/it]

[I 2025-12-01 20:19:04,532] Trial 48 finished with value: 0.6543151969981238 and parameters: {'max_depth': 10, 'learning_rate': 0.03394003455153337, 'n_estimators': 381, 'subsample': 0.9703553966350146, 'colsample_bytree': 0.5595756241734088, 'min_child_weight': 2, 'gamma': 3.7647686984692923, 'reg_alpha': 1.0223719570588809e-07, 'reg_lambda': 0.15541622223444068, 'max_delta_step': 4}. Best is trial 45 with value: 0.6543151969981238.

Best trial: 45. Best value: 0.654315: 100%|██████████| 50/50 [06:03<00:00,  7.27s/it]

[I 2025-12-01 20:19:06,252] Trial 46 finished with value: 0.6177298311444652 and parameters: {'max_depth': 9, 'learning_rate': 0.03397924671790243, 'n_estimators': 613, 'subsample': 0.9956907364196121, 'colsample_bytree': 0.9324226607397545, 'min_child_weight': 4, 'gamma': 3.74446196280416, 'reg_alpha': 1.721105524951153e-07, 'reg_lambda': 3.1140137556901868e-06, 'max_delta_step': 6}. Best is trial 45 with value: 0.6543151969981238.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 20:19:10,153] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 67, Test size: 17
Using Leave-One-Out CV with 67 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.589587:   2%|▏         | 1/50 [00:27<22:07, 27.09s/it]

[I 2025-12-01 20:19:37,238] Trial 0 finished with value: 0.5895872420262664 and parameters: {'max_depth': 10, 'learning_rate': 0.12701695736923319, 'n_estimators': 483, 'subsample': 0.5532111728320577, 'colsample_bytree': 0.8104343535470522, 'min_child_weight': 2, 'gamma': 2.4931298311816104, 'reg_alpha': 7.198529462472795e-08, 'reg_lambda': 0.041543916423253634, 'max_delta_step': 8}. Best is trial 0 with value: 0.5895872420262664.

Best trial: 2. Best value: 0.601782:   4%|▍         | 2/50 [00:27<09:05, 11.37s/it]

[I 2025-12-01 20:19:37,603] Trial 2 finished with value: 0.601782363977486 and parameters: {'max_depth': 8, 'learning_rate': 0.027952056934578605, 'n_estimators': 365, 'subsample': 0.6750475339324535, 'colsample_bytree': 0.6944033594847635, 'min_child_weight': 1, 'gamma': 0.550586074343129, 'reg_alpha': 0.0010946105456060235, 'reg_lambda': 3.2677748254989223, 'max_delta_step': 4}. Best is trial 2 with value: 0.601782363977486.

Best trial: 2. Best value: 0.601782:   6%|▌         | 3/50 [00:32<06:28,  8.27s/it]

[I 2025-12-01 20:19:42,186] Trial 1 finished with value: 0.5984990619136961 and parameters: {'max_depth': 7, 'learning_rate': 0.14113364670732098, 'n_estimators': 591, 'subsample': 0.699365841448669, 'colsample_bytree': 0.5598275105889162, 'min_child_weight': 7, 'gamma': 2.506709321400629, 'reg_alpha': 8.414635624286259, 'reg_lambda': 8.138798685375015e-06, 'max_delta_step': 8}. Best is trial 2 with value: 0.601782363977486.

Best trial: 3. Best value: 0.640244:   8%|▊         | 4/50 [01:21<18:55, 24.69s/it]

[I 2025-12-01 20:20:32,038] Trial 3 finished with value: 0.6402439024390244 and parameters: {'max_depth': 9, 'learning_rate': 0.0962683761306353, 'n_estimators': 1485, 'subsample': 0.733410468135431, 'colsample_bytree': 0.8526732344940307, 'min_child_weight': 4, 'gamma': 3.044092240976086, 'reg_alpha': 0.003094635969163603, 'reg_lambda': 1.64503691323593e-05, 'max_delta_step': 9}. Best is trial 3 with value: 0.6402439024390244.

Best trial: 3. Best value: 0.640244:  10%|█         | 5/50 [01:26<13:06, 17.48s/it]

[I 2025-12-01 20:20:36,755] Trial 5 finished with value: 0.6158536585365854 and parameters: {'max_depth': 5, 'learning_rate': 0.14723406302103695, 'n_estimators': 1055, 'subsample': 0.7628699516169811, 'colsample_bytree': 0.840663363882749, 'min_child_weight': 5, 'gamma': 3.022222175802265, 'reg_alpha': 0.007459459399374866, 'reg_lambda': 2.5500617956329034e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.6402439024390244.

Best trial: 3. Best value: 0.640244:  12%|█▏        | 6/50 [01:30<09:32, 13.01s/it]

[I 2025-12-01 20:20:41,090] Trial 6 finished with value: 0.5651969981238274 and parameters: {'max_depth': 4, 'learning_rate': 0.010141845977915636, 'n_estimators': 902, 'subsample': 0.6808024743403898, 'colsample_bytree': 0.5671736628749561, 'min_child_weight': 1, 'gamma': 2.5727689310191537, 'reg_alpha': 1.2951578604182095e-06, 'reg_lambda': 1.873378332615255e-05, 'max_delta_step': 5}. Best is trial 3 with value: 0.6402439024390244.

Best trial: 3. Best value: 0.640244:  14%|█▍        | 7/50 [01:37<07:55, 11.05s/it]

[I 2025-12-01 20:20:48,112] Trial 4 finished with value: 0.5792682926829269 and parameters: {'max_depth': 8, 'learning_rate': 0.17052877114353382, 'n_estimators': 1307, 'subsample': 0.8045021316558667, 'colsample_bytree': 0.6744295908335048, 'min_child_weight': 9, 'gamma': 2.8416160144561515, 'reg_alpha': 3.935720648487025e-05, 'reg_lambda': 0.0010216067384875493, 'max_delta_step': 9}. Best is trial 3 with value: 0.6402439024390244.

Best trial: 3. Best value: 0.640244:  16%|█▌        | 8/50 [01:46<07:12, 10.29s/it]

[I 2025-12-01 20:20:56,772] Trial 8 finished with value: 0.5389305816135084 and parameters: {'max_depth': 7, 'learning_rate': 0.10039067815530119, 'n_estimators': 311, 'subsample': 0.7067118781719338, 'colsample_bytree': 0.817037709410512, 'min_child_weight': 2, 'gamma': 1.7043027118582348, 'reg_alpha': 1.1788988591630418, 'reg_lambda': 2.4969874675397697e-05, 'max_delta_step': 10}. Best is trial 3 with value: 0.6402439024390244.

Best trial: 3. Best value: 0.640244:  18%|█▊        | 9/50 [01:59<07:32, 11.03s/it]

[I 2025-12-01 20:21:09,413] Trial 9 finished with value: 0.5984990619136961 and parameters: {'max_depth': 5, 'learning_rate': 0.12863854530140503, 'n_estimators': 474, 'subsample': 0.9979563992335574, 'colsample_bytree': 0.7250079384763549, 'min_child_weight': 4, 'gamma': 2.877450555562937, 'reg_alpha': 1.3470894578716928e-06, 'reg_lambda': 7.287327154512611e-05, 'max_delta_step': 9}. Best is trial 3 with value: 0.6402439024390244.

Best trial: 3. Best value: 0.640244:  20%|██        | 10/50 [02:13<08:01, 12.05s/it]

[I 2025-12-01 20:21:23,746] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.14731831662652572, 'n_estimators': 234, 'subsample': 0.5484990601772963, 'colsample_bytree': 0.8975133500784147, 'min_child_weight': 9, 'gamma': 1.2448875117457814, 'reg_alpha': 0.0002542526915224825, 'reg_lambda': 1.4506424084088948e-08, 'max_delta_step': 6}. Best is trial 3 with value: 0.6402439024390244.

Best trial: 3. Best value: 0.640244:  22%|██▏       | 11/50 [02:16<05:55,  9.12s/it]

[I 2025-12-01 20:21:26,229] Trial 11 pruned.

Best trial: 3. Best value: 0.640244:  24%|██▍       | 12/50 [02:25<05:48,  9.17s/it]

[I 2025-12-01 20:21:35,526] Trial 10 pruned.

Best trial: 3. Best value: 0.640244:  26%|██▌       | 13/50 [02:25<03:59,  6.47s/it]

[I 2025-12-01 20:21:35,783] Trial 13 pruned.

Best trial: 3. Best value: 0.640244:  28%|██▊       | 14/50 [02:39<05:14,  8.75s/it]

[I 2025-12-01 20:21:49,788] Trial 7 finished with value: 0.5530018761726079 and parameters: {'max_depth': 5, 'learning_rate': 0.042822355497150646, 'n_estimators': 1324, 'subsample': 0.6923673675865978, 'colsample_bytree': 0.8975033520993252, 'min_child_weight': 2, 'gamma': 4.94354368961319, 'reg_alpha': 1.4512450426001782e-05, 'reg_lambda': 0.15963543967835842, 'max_delta_step': 6}. Best is trial 3 with value: 0.6402439024390244.

Best trial: 3. Best value: 0.640244:  30%|███       | 15/50 [03:29<12:18, 21.10s/it]

[I 2025-12-01 20:22:39,511] Trial 16 finished with value: 0.6280487804878049 and parameters: {'max_depth': 5, 'learning_rate': 0.2830519270519989, 'n_estimators': 1092, 'subsample': 0.8349042402626167, 'colsample_bytree': 0.8989760328618721, 'min_child_weight': 5, 'gamma': 3.983848923779987, 'reg_alpha': 0.057305152328758026, 'reg_lambda': 4.618912198482152e-07, 'max_delta_step': 6}. Best is trial 3 with value: 0.6402439024390244.

Best trial: 3. Best value: 0.640244:  32%|███▏      | 16/50 [03:30<08:33, 15.12s/it]

[I 2025-12-01 20:22:40,741] Trial 15 finished with value: 0.6210131332082551 and parameters: {'max_depth': 10, 'learning_rate': 0.2873248939434686, 'n_estimators': 1111, 'subsample': 0.8615718311208092, 'colsample_bytree': 0.9843898326044175, 'min_child_weight': 4, 'gamma': 4.388751787187266, 'reg_alpha': 0.03652454907123036, 'reg_lambda': 1.285516261751641e-07, 'max_delta_step': 2}. Best is trial 3 with value: 0.6402439024390244.

Best trial: 3. Best value: 0.640244:  34%|███▍      | 17/50 [03:39<07:15, 13.19s/it]

[I 2025-12-01 20:22:49,451] Trial 18 pruned.

Best trial: 3. Best value: 0.640244:  38%|███▊      | 19/50 [03:42<03:40,  7.11s/it]

[I 2025-12-01 20:22:52,342] Trial 14 finished with value: 0.5966228893058161 and parameters: {'max_depth': 10, 'learning_rate': 0.29577724401046074, 'n_estimators': 1495, 'subsample': 0.8777481322428999, 'colsample_bytree': 0.982202923722396, 'min_child_weight': 5, 'gamma': 4.47075471347736, 'reg_alpha': 0.02089357996156358, 'reg_lambda': 1.5966255867933784e-07, 'max_delta_step': 2}. Best is trial 3 with value: 0.6402439024390244.
[I 2025-12-01 20:22:52,490] Trial 17 finished with value: 0.5773921200750469 and parameters: {'max_depth': 3, 'learning_rate': 0.2991850154285471, 'n_estimators': 1079, 'subsample': 0.8261320809656524, 'colsample_bytree': 0.8998478715241015, 'min_child_weight': 5, 'gamma': 3.8032381838985687, 'reg_alpha': 0.05666557608467127, 'reg_lambda': 3.266839022488369e-07, 'max_delta_step': 3}. Best is trial 3 with value: 0.6402439024390244.

Best trial: 3. Best value: 0.640244:  40%|████      | 20/50 [03:49<03:38,  7.27s/it]

[I 2025-12-01 20:23:00,134] Trial 22 pruned.

Best trial: 3. Best value: 0.640244:  42%|████▏     | 21/50 [03:51<02:43,  5.65s/it]

[I 2025-12-01 20:23:01,997] Trial 20 pruned.

Best trial: 3. Best value: 0.640244:  44%|████▍     | 22/50 [04:00<03:03,  6.54s/it]

[I 2025-12-01 20:23:10,611] Trial 23 pruned.

Best trial: 3. Best value: 0.640244:  46%|████▌     | 23/50 [04:02<02:21,  5.23s/it]

[I 2025-12-01 20:23:12,783] Trial 24 pruned.

Best trial: 3. Best value: 0.640244:  48%|████▊     | 24/50 [04:10<02:39,  6.13s/it]

[I 2025-12-01 20:23:21,009] Trial 25 pruned.

Best trial: 3. Best value: 0.640244:  50%|█████     | 25/50 [04:19<02:50,  6.81s/it]

[I 2025-12-01 20:23:29,411] Trial 27 pruned.

Best trial: 3. Best value: 0.640244:  52%|█████▏    | 26/50 [04:34<03:45,  9.41s/it]

[I 2025-12-01 20:23:44,883] Trial 21 finished with value: 0.6088180112570356 and parameters: {'max_depth': 6, 'learning_rate': 0.07207804477807078, 'n_estimators': 879, 'subsample': 0.9476236516433325, 'colsample_bytree': 0.895562210512189, 'min_child_weight': 6, 'gamma': 3.6026190759633914, 'reg_alpha': 0.0008467881716142099, 'reg_lambda': 0.0004972184713958182, 'max_delta_step': 10}. Best is trial 3 with value: 0.6402439024390244.

Best trial: 19. Best value: 0.659475:  54%|█████▍    | 27/50 [04:36<02:44,  7.17s/it]

[I 2025-12-01 20:23:46,816] Trial 19 finished with value: 0.6594746716697937 and parameters: {'max_depth': 3, 'learning_rate': 0.07071154157252472, 'n_estimators': 1145, 'subsample': 0.6165146998592452, 'colsample_bytree': 0.9230805549653646, 'min_child_weight': 5, 'gamma': 3.9395488515523076, 'reg_alpha': 0.23325642980940017, 'reg_lambda': 4.924932234874673e-07, 'max_delta_step': 7}. Best is trial 19 with value: 0.6594746716697937.

Best trial: 19. Best value: 0.659475:  56%|█████▌    | 28/50 [04:41<02:19,  6.35s/it]

[I 2025-12-01 20:23:51,253] Trial 29 pruned.

Best trial: 19. Best value: 0.659475:  58%|█████▊    | 29/50 [04:58<03:23,  9.68s/it]

[I 2025-12-01 20:24:08,726] Trial 26 finished with value: 0.6228893058161351 and parameters: {'max_depth': 9, 'learning_rate': 0.21582424801614328, 'n_estimators': 964, 'subsample': 0.8023885226308374, 'colsample_bytree': 0.9447665582895397, 'min_child_weight': 3, 'gamma': 4.112556903833715, 'reg_alpha': 0.0052164614181041645, 'reg_lambda': 1.3748893812629844e-08, 'max_delta_step': 0}. Best is trial 19 with value: 0.6594746716697937.

Best trial: 19. Best value: 0.659475:  60%|██████    | 30/50 [05:07<03:09,  9.47s/it]

[I 2025-12-01 20:24:17,704] Trial 28 finished with value: 0.6088180112570356 and parameters: {'max_depth': 10, 'learning_rate': 0.09329281051789408, 'n_estimators': 817, 'subsample': 0.8474216530059699, 'colsample_bytree': 0.8572994510968184, 'min_child_weight': 3, 'gamma': 2.1971812243853415, 'reg_alpha': 0.015167161004153922, 'reg_lambda': 0.0036846978522260113, 'max_delta_step': 4}. Best is trial 19 with value: 0.6594746716697937.

Best trial: 19. Best value: 0.659475:  62%|██████▏   | 31/50 [05:09<02:15,  7.14s/it]

[I 2025-12-01 20:24:19,403] Trial 32 pruned.

Best trial: 19. Best value: 0.659475:  64%|██████▍   | 32/50 [05:18<02:20,  7.78s/it]

[I 2025-12-01 20:24:28,672] Trial 33 pruned.

Best trial: 19. Best value: 0.659475:  66%|██████▌   | 33/50 [05:20<01:43,  6.11s/it]

[I 2025-12-01 20:24:30,893] Trial 30 finished with value: 0.5581613508442776 and parameters: {'max_depth': 4, 'learning_rate': 0.02916941742207705, 'n_estimators': 730, 'subsample': 0.633703622386447, 'colsample_bytree': 0.8541078680261496, 'min_child_weight': 3, 'gamma': 1.834595213082901, 'reg_alpha': 8.649275294888836, 'reg_lambda': 0.004240609548353726, 'max_delta_step': 8}. Best is trial 19 with value: 0.6594746716697937.

Best trial: 19. Best value: 0.659475:  68%|██████▊   | 34/50 [05:27<01:40,  6.30s/it]

[I 2025-12-01 20:24:37,636] Trial 35 pruned.

Best trial: 19. Best value: 0.659475:  70%|███████   | 35/50 [05:39<01:58,  7.92s/it]

[I 2025-12-01 20:24:49,334] Trial 31 finished with value: 0.6402439024390244 and parameters: {'max_depth': 4, 'learning_rate': 0.05295127506038633, 'n_estimators': 975, 'subsample': 0.6110013651467101, 'colsample_bytree': 0.7871579134239393, 'min_child_weight': 3, 'gamma': 3.117487642592031, 'reg_alpha': 0.2151492241669217, 'reg_lambda': 0.0030993136192563543, 'max_delta_step': 8}. Best is trial 19 with value: 0.6594746716697937.

Best trial: 19. Best value: 0.659475:  72%|███████▏  | 36/50 [06:06<03:12, 13.75s/it]

[I 2025-12-01 20:25:16,691] Trial 34 finished with value: 0.6280487804878049 and parameters: {'max_depth': 3, 'learning_rate': 0.05072726897890299, 'n_estimators': 974, 'subsample': 0.5071711104176322, 'colsample_bytree': 0.9360389312938201, 'min_child_weight': 3, 'gamma': 3.992823796054894, 'reg_alpha': 0.0034907649563134246, 'reg_lambda': 6.021727878917155e-07, 'max_delta_step': 7}. Best is trial 19 with value: 0.6594746716697937.

Best trial: 19. Best value: 0.659475:  74%|███████▍  | 37/50 [06:18<02:51, 13.19s/it]

[I 2025-12-01 20:25:28,575] Trial 36 finished with value: 0.6139774859287055 and parameters: {'max_depth': 3, 'learning_rate': 0.24031991243913414, 'n_estimators': 997, 'subsample': 0.7275624126171366, 'colsample_bytree': 0.9392913148252292, 'min_child_weight': 3, 'gamma': 3.92636845456632, 'reg_alpha': 0.004443029618489082, 'reg_lambda': 1.0395401919310773e-08, 'max_delta_step': 7}. Best is trial 19 with value: 0.6594746716697937.

Best trial: 19. Best value: 0.659475:  76%|███████▌  | 38/50 [06:22<02:04, 10.37s/it]

[I 2025-12-01 20:25:32,363] Trial 37 finished with value: 0.6261726078799249 and parameters: {'max_depth': 8, 'learning_rate': 0.179033173496653, 'n_estimators': 965, 'subsample': 0.7940359587621065, 'colsample_bytree': 0.9220499578304184, 'min_child_weight': 5, 'gamma': 4.699100020550619, 'reg_alpha': 1.2745368010745773e-08, 'reg_lambda': 6.34352334026753e-07, 'max_delta_step': 9}. Best is trial 19 with value: 0.6594746716697937.

Best trial: 19. Best value: 0.659475:  78%|███████▊  | 39/50 [06:28<01:40,  9.15s/it]

[I 2025-12-01 20:25:38,663] Trial 40 pruned.

Best trial: 19. Best value: 0.659475:  80%|████████  | 40/50 [06:32<01:16,  7.63s/it]

[I 2025-12-01 20:25:42,734] Trial 41 pruned.

Best trial: 19. Best value: 0.659475:  82%|████████▏ | 41/50 [06:45<01:22,  9.18s/it]

[I 2025-12-01 20:25:55,526] Trial 38 finished with value: 0.5966228893058161 and parameters: {'max_depth': 5, 'learning_rate': 0.03324308270078902, 'n_estimators': 1156, 'subsample': 0.6492643036962193, 'colsample_bytree': 0.816916671427606, 'min_child_weight': 5, 'gamma': 2.6088402089785045, 'reg_alpha': 2.3714530902278415, 'reg_lambda': 9.359295331676093e-05, 'max_delta_step': 9}. Best is trial 19 with value: 0.6594746716697937.

Best trial: 19. Best value: 0.659475:  84%|████████▍ | 42/50 [07:08<01:47, 13.42s/it]

[I 2025-12-01 20:26:18,836] Trial 43 finished with value: 0.6088180112570356 and parameters: {'max_depth': 4, 'learning_rate': 0.021597568438727014, 'n_estimators': 581, 'subsample': 0.5767368736354594, 'colsample_bytree': 0.8211471281033758, 'min_child_weight': 2, 'gamma': 2.7300130686999635, 'reg_alpha': 0.11361605222913619, 'reg_lambda': 1.1466098122414214e-05, 'max_delta_step': 6}. Best is trial 19 with value: 0.6594746716697937.

Best trial: 19. Best value: 0.659475:  86%|████████▌ | 43/50 [07:14<01:18, 11.25s/it]

[I 2025-12-01 20:26:25,048] Trial 39 finished with value: 0.5703564727954972 and parameters: {'max_depth': 5, 'learning_rate': 0.036547055865179284, 'n_estimators': 1178, 'subsample': 0.6472055326340251, 'colsample_bytree': 0.6442941069803094, 'min_child_weight': 1, 'gamma': 2.7013538879472634, 'reg_alpha': 2.2051124776814226, 'reg_lambda': 7.576294915402196e-05, 'max_delta_step': 9}. Best is trial 19 with value: 0.6594746716697937.

Best trial: 19. Best value: 0.659475:  88%|████████▊ | 44/50 [07:16<00:50,  8.42s/it]

[I 2025-12-01 20:26:26,837] Trial 42 finished with value: 0.5511257035647279 and parameters: {'max_depth': 5, 'learning_rate': 0.020009248354916263, 'n_estimators': 792, 'subsample': 0.5762582914318293, 'colsample_bytree': 0.8165811604725435, 'min_child_weight': 2, 'gamma': 2.671201726766931, 'reg_alpha': 0.9128140407476757, 'reg_lambda': 2.0121061191979438e-05, 'max_delta_step': 6}. Best is trial 19 with value: 0.6594746716697937.

Best trial: 19. Best value: 0.659475:  90%|█████████ | 45/50 [07:31<00:51, 10.39s/it]

[I 2025-12-01 20:26:41,823] Trial 44 finished with value: 0.5633208255159474 and parameters: {'max_depth': 3, 'learning_rate': 0.06011042142055019, 'n_estimators': 815, 'subsample': 0.5768742814665355, 'colsample_bytree': 0.5122322589418387, 'min_child_weight': 2, 'gamma': 3.252496097609709, 'reg_alpha': 0.12175010052081157, 'reg_lambda': 8.40478624712265e-06, 'max_delta_step': 6}. Best is trial 19 with value: 0.6594746716697937.

Best trial: 19. Best value: 0.659475:  92%|█████████▏| 46/50 [07:54<00:56, 14.22s/it]

[I 2025-12-01 20:27:04,992] Trial 45 finished with value: 0.5825515947467167 and parameters: {'max_depth': 3, 'learning_rate': 0.05675376341672349, 'n_estimators': 772, 'subsample': 0.5677253625104841, 'colsample_bytree': 0.7593559268068312, 'min_child_weight': 2, 'gamma': 3.270988436477564, 'reg_alpha': 0.72929036288334, 'reg_lambda': 0.0038463982051622253, 'max_delta_step': 7}. Best is trial 19 with value: 0.6594746716697937.

Best trial: 19. Best value: 0.659475:  94%|█████████▍| 47/50 [08:03<00:37, 12.54s/it]

[I 2025-12-01 20:27:13,595] Trial 46 finished with value: 0.5966228893058161 and parameters: {'max_depth': 3, 'learning_rate': 0.05661077020902255, 'n_estimators': 823, 'subsample': 0.5111823638122736, 'colsample_bytree': 0.7528153272889306, 'min_child_weight': 2, 'gamma': 3.212779009592528, 'reg_alpha': 0.00025637656971432785, 'reg_lambda': 0.004498811434457757, 'max_delta_step': 7}. Best is trial 19 with value: 0.6594746716697937.

Best trial: 19. Best value: 0.659475:  96%|█████████▌| 48/50 [08:05<00:18,  9.46s/it]

[I 2025-12-01 20:27:15,881] Trial 49 pruned.

Best trial: 19. Best value: 0.659475:  98%|█████████▊| 49/50 [08:11<00:08,  8.21s/it]

[I 2025-12-01 20:27:21,161] Trial 47 finished with value: 0.6454033771106942 and parameters: {'max_depth': 3, 'learning_rate': 0.059250041217076346, 'n_estimators': 1055, 'subsample': 0.6699705494514085, 'colsample_bytree': 0.8781839618157545, 'min_child_weight': 4, 'gamma': 3.2321407622807863, 'reg_alpha': 0.00011102392080124788, 'reg_lambda': 0.0371771848829774, 'max_delta_step': 7}. Best is trial 19 with value: 0.6594746716697937.

Best trial: 48. Best value: 0.690901: 100%|██████████| 50/50 [08:18<00:00,  9.98s/it]

[I 2025-12-01 20:27:28,958] Trial 48 finished with value: 0.6909005628517824 and parameters: {'max_depth': 3, 'learning_rate': 0.04714695716445562, 'n_estimators': 1403, 'subsample': 0.507115457110043, 'colsample_bytree': 0.8781844766163182, 'min_child_weight': 4, 'gamma': 4.966322496746148, 'reg_alpha': 0.00012626961172118668, 'reg_lambda': 0.0028911670043363573, 'max_delta_step': 7}. Best is trial 48 with value: 0.6909005628517824.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.635084                0.614286      0.600000
1    19_1         loo       0.690901                0.585714      0.642857
2     9_1         loo       0.629925                0.535714      0.600000
3    17_1         loo       0.654315                0.485714      0.457143

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.246885          0.428571               0.8        50          67
1  0.169031          0.571429               0.6        50          67
2  0.070430          0.571429               0.5        50          67
3 -0.028571          0.571429               0.4        50          67

   test_size
0         17
1         17
2         17
3         17
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.635084                0.614286      0.600000
1    19_1         loo       0.690901                0.585714      0.642857
2     9_1         loo       0.629925                0.535714      0.600000
3    17_1         loo       0.654315                0.485714      0.457143

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.246885          0.428571               0.8        50          67
1  0.169031          0.571429               0.6        50          67
2  0.070430          0.571429               0.5        50          67
3 -0.028571          0.571429               0.4        50          67

   test_size
0         17
1         17
2         17
3         17

## MCI-AD vs HC -> OPTUNA + XGB

In [1568]:

datasets = task_hf_compensated_comb_emb_lbl_ad_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir="xgb_ad_hc_{CV_STRATEGY}_tasks/xgb_results_handcrafted_comb_emb_ad_hc_extended_{CV_STRATEGY}_tasks",
    split_param= "diagnosis_y",
)
print(summary)

[I 2025-12-01 20:27:33,451] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.2375:   2%|▏         | 1/50 [00:15<12:19, 15.09s/it]

[I 2025-12-01 20:27:48,533] Trial 3 finished with value: 0.2375 and parameters: {'max_depth': 4, 'learning_rate': 0.024306265084379164, 'n_estimators': 267, 'subsample': 0.7975462159106153, 'colsample_bytree': 0.6449537649749021, 'min_child_weight': 9, 'gamma': 4.954664734025675, 'reg_alpha': 4.591710049680401e-06, 'reg_lambda': 8.054958566179737e-07, 'max_delta_step': 8}. Best is trial 3 with value: 0.2375.

Best trial: 3. Best value: 0.2375:   4%|▍         | 2/50 [00:32<13:17, 16.61s/it]

[I 2025-12-01 20:28:06,202] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.011900574147486118, 'n_estimators': 415, 'subsample': 0.7771381771742122, 'colsample_bytree': 0.6862553669222817, 'min_child_weight': 3, 'gamma': 3.1457240420982213, 'reg_alpha': 8.672174669936684, 'reg_lambda': 1.8831056718156558e-06, 'max_delta_step': 0}. Best is trial 3 with value: 0.2375.

Best trial: 3. Best value: 0.2375:   6%|▌         | 3/50 [00:35<08:00, 10.23s/it]

[I 2025-12-01 20:28:08,838] Trial 2 finished with value: 0.07631578947368421 and parameters: {'max_depth': 5, 'learning_rate': 0.10389429028456289, 'n_estimators': 681, 'subsample': 0.5284430604515885, 'colsample_bytree': 0.7941686616682779, 'min_child_weight': 8, 'gamma': 1.3418721062167416, 'reg_alpha': 0.00854215213271087, 'reg_lambda': 1.0952035049691649, 'max_delta_step': 6}. Best is trial 3 with value: 0.2375.

Best trial: 4. Best value: 0.546711:   8%|▊         | 4/50 [00:56<11:04, 14.45s/it]

[I 2025-12-01 20:28:29,777] Trial 4 finished with value: 0.5467105263157894 and parameters: {'max_depth': 3, 'learning_rate': 0.05002999708887337, 'n_estimators': 533, 'subsample': 0.9451702870028862, 'colsample_bytree': 0.7809021918831816, 'min_child_weight': 4, 'gamma': 1.9248370758047173, 'reg_alpha': 4.503722636233091e-07, 'reg_lambda': 1.307494898309631e-06, 'max_delta_step': 7}. Best is trial 4 with value: 0.5467105263157894.

Best trial: 4. Best value: 0.546711:  10%|█         | 5/50 [01:10<10:48, 14.41s/it]

[I 2025-12-01 20:28:44,091] Trial 6 finished with value: 0.444078947368421 and parameters: {'max_depth': 7, 'learning_rate': 0.26700103721186563, 'n_estimators': 623, 'subsample': 0.9182949025289331, 'colsample_bytree': 0.6134319062463229, 'min_child_weight': 7, 'gamma': 4.722191221778728, 'reg_alpha': 5.866975649393994, 'reg_lambda': 0.0016737811413161789, 'max_delta_step': 0}. Best is trial 4 with value: 0.5467105263157894.

Best trial: 5. Best value: 0.600658:  12%|█▏        | 6/50 [01:16<08:26, 11.51s/it]

[I 2025-12-01 20:28:49,998] Trial 5 finished with value: 0.6006578947368422 and parameters: {'max_depth': 7, 'learning_rate': 0.010321100796469923, 'n_estimators': 676, 'subsample': 0.7885078895424509, 'colsample_bytree': 0.996466003088573, 'min_child_weight': 8, 'gamma': 1.7077000806350096, 'reg_alpha': 0.005574825168956558, 'reg_lambda': 1.2501918718171152e-07, 'max_delta_step': 8}. Best is trial 5 with value: 0.6006578947368422.

Best trial: 5. Best value: 0.600658:  14%|█▍        | 7/50 [02:11<18:31, 25.85s/it]

[I 2025-12-01 20:29:45,359] Trial 0 finished with value: 0.5217105263157895 and parameters: {'max_depth': 3, 'learning_rate': 0.04568394875105007, 'n_estimators': 1223, 'subsample': 0.5360857410330706, 'colsample_bytree': 0.8872663111750113, 'min_child_weight': 1, 'gamma': 2.737218602246357, 'reg_alpha': 5.246453022999061, 'reg_lambda': 4.432112391643863, 'max_delta_step': 9}. Best is trial 5 with value: 0.6006578947368422.

Best trial: 5. Best value: 0.600658:  16%|█▌        | 8/50 [02:20<14:08, 20.21s/it]

[I 2025-12-01 20:29:53,491] Trial 8 finished with value: 0.3888157894736842 and parameters: {'max_depth': 6, 'learning_rate': 0.05773891227834196, 'n_estimators': 1414, 'subsample': 0.7517796627280431, 'colsample_bytree': 0.8666116339412088, 'min_child_weight': 9, 'gamma': 0.23010970049712143, 'reg_alpha': 0.26274136446787527, 'reg_lambda': 1.4318054868361842e-07, 'max_delta_step': 0}. Best is trial 5 with value: 0.6006578947368422.

Best trial: 5. Best value: 0.600658:  18%|█▊        | 9/50 [02:29<11:26, 16.74s/it]

[I 2025-12-01 20:30:02,606] Trial 7 finished with value: 0.5592105263157895 and parameters: {'max_depth': 4, 'learning_rate': 0.03272363529317554, 'n_estimators': 1067, 'subsample': 0.6982836899094902, 'colsample_bytree': 0.528306720040955, 'min_child_weight': 1, 'gamma': 3.648567383647902, 'reg_alpha': 1.1005872419419178e-05, 'reg_lambda': 0.06316838479651493, 'max_delta_step': 5}. Best is trial 5 with value: 0.6006578947368422.

Best trial: 5. Best value: 0.600658:  20%|██        | 10/50 [02:37<09:21, 14.04s/it]

[I 2025-12-01 20:30:10,596] Trial 9 finished with value: 0.5480263157894737 and parameters: {'max_depth': 3, 'learning_rate': 0.015458415368056647, 'n_estimators': 1184, 'subsample': 0.8909917840617065, 'colsample_bytree': 0.8187739389808997, 'min_child_weight': 6, 'gamma': 4.204440354261349, 'reg_alpha': 0.0015565160818399853, 'reg_lambda': 0.00014253985634585259, 'max_delta_step': 7}. Best is trial 5 with value: 0.6006578947368422.

Best trial: 5. Best value: 0.600658:  22%|██▏       | 11/50 [02:44<07:48, 12.02s/it]

[I 2025-12-01 20:30:18,018] Trial 13 pruned.

Best trial: 5. Best value: 0.600658:  24%|██▍       | 12/50 [02:48<06:01,  9.52s/it]

[I 2025-12-01 20:30:21,830] Trial 10 finished with value: 0.5868421052631578 and parameters: {'max_depth': 8, 'learning_rate': 0.02162421081513424, 'n_estimators': 588, 'subsample': 0.6209026177882871, 'colsample_bytree': 0.8347952776654541, 'min_child_weight': 7, 'gamma': 0.219003789118985, 'reg_alpha': 0.001666896162989995, 'reg_lambda': 9.930808697078884e-08, 'max_delta_step': 7}. Best is trial 5 with value: 0.6006578947368422.

Best trial: 5. Best value: 0.600658:  26%|██▌       | 13/50 [03:01<06:31, 10.57s/it]

[I 2025-12-01 20:30:34,816] Trial 12 finished with value: 0.5980263157894736 and parameters: {'max_depth': 6, 'learning_rate': 0.1263282055478233, 'n_estimators': 578, 'subsample': 0.8482467525004298, 'colsample_bytree': 0.5971679915259411, 'min_child_weight': 6, 'gamma': 1.2166736192979482, 'reg_alpha': 7.008808855515324e-07, 'reg_lambda': 5.61430614037896e-05, 'max_delta_step': 8}. Best is trial 5 with value: 0.6006578947368422.

Best trial: 5. Best value: 0.600658:  28%|██▊       | 14/50 [03:03<04:48,  8.01s/it]

[I 2025-12-01 20:30:36,928] Trial 11 finished with value: 0.5868421052631578 and parameters: {'max_depth': 6, 'learning_rate': 0.121769183008351, 'n_estimators': 756, 'subsample': 0.6619999715616697, 'colsample_bytree': 0.8429191684814588, 'min_child_weight': 7, 'gamma': 0.13400619069265818, 'reg_alpha': 0.003372672580429439, 'reg_lambda': 0.041068909037826944, 'max_delta_step': 1}. Best is trial 5 with value: 0.6006578947368422.

Best trial: 5. Best value: 0.600658:  30%|███       | 15/50 [03:09<04:14,  7.27s/it]

[I 2025-12-01 20:30:42,490] Trial 16 pruned.

Best trial: 5. Best value: 0.600658:  32%|███▏      | 16/50 [03:13<03:39,  6.46s/it]

[I 2025-12-01 20:30:47,076] Trial 18 pruned.

Best trial: 5. Best value: 0.600658:  34%|███▍      | 17/50 [03:44<07:39, 13.93s/it]

[I 2025-12-01 20:31:18,350] Trial 15 finished with value: 0.5993421052631579 and parameters: {'max_depth': 8, 'learning_rate': 0.019726986447988096, 'n_estimators': 839, 'subsample': 0.6309315627864387, 'colsample_bytree': 0.989637342985107, 'min_child_weight': 6, 'gamma': 1.3784236537176646, 'reg_alpha': 0.02682916580618342, 'reg_lambda': 5.25915910999372e-05, 'max_delta_step': 3}. Best is trial 5 with value: 0.6006578947368422.

Best trial: 17. Best value: 0.611842:  36%|███▌      | 18/50 [03:51<06:16, 11.77s/it]

[I 2025-12-01 20:31:25,116] Trial 17 finished with value: 0.6118421052631579 and parameters: {'max_depth': 10, 'learning_rate': 0.16172795840117474, 'n_estimators': 969, 'subsample': 0.8347360056732636, 'colsample_bytree': 0.5166073178064072, 'min_child_weight': 5, 'gamma': 1.5999775872260762, 'reg_alpha': 4.8643044741121495e-05, 'reg_lambda': 2.9287369210333665e-05, 'max_delta_step': 10}. Best is trial 17 with value: 0.6118421052631579.

Best trial: 17. Best value: 0.611842:  38%|███▊      | 19/50 [03:54<04:43,  9.15s/it]

[I 2025-12-01 20:31:28,161] Trial 20 pruned.

Best trial: 17. Best value: 0.611842:  40%|████      | 20/50 [03:59<03:55,  7.84s/it]

[I 2025-12-01 20:31:32,947] Trial 19 pruned.

Best trial: 17. Best value: 0.611842:  42%|████▏     | 21/50 [04:14<04:53, 10.13s/it]

[I 2025-12-01 20:31:48,408] Trial 14 finished with value: 0.5592105263157895 and parameters: {'max_depth': 8, 'learning_rate': 0.02257025623686213, 'n_estimators': 967, 'subsample': 0.6616393229883383, 'colsample_bytree': 0.5032152608723643, 'min_child_weight': 1, 'gamma': 3.4794441564575163, 'reg_alpha': 1.0814323809644817e-08, 'reg_lambda': 0.014517553494272924, 'max_delta_step': 4}. Best is trial 17 with value: 0.6118421052631579.

Best trial: 17. Best value: 0.611842:  44%|████▍     | 22/50 [04:57<09:19, 19.97s/it]

[I 2025-12-01 20:32:31,320] Trial 22 finished with value: 0.5980263157894736 and parameters: {'max_depth': 10, 'learning_rate': 0.08734379680190592, 'n_estimators': 1040, 'subsample': 0.717362806638197, 'colsample_bytree': 0.9234367919715719, 'min_child_weight': 3, 'gamma': 2.5669163827111543, 'reg_alpha': 8.196300775379022e-05, 'reg_lambda': 1.0375943960634268e-08, 'max_delta_step': 10}. Best is trial 17 with value: 0.6118421052631579.

Best trial: 17. Best value: 0.611842:  46%|████▌     | 23/50 [04:58<06:21, 14.12s/it]

[I 2025-12-01 20:32:31,786] Trial 24 finished with value: 0.5980263157894736 and parameters: {'max_depth': 10, 'learning_rate': 0.20130856013980303, 'n_estimators': 789, 'subsample': 0.6981074728250758, 'colsample_bytree': 0.9221870711392444, 'min_child_weight': 4, 'gamma': 0.8800316031009208, 'reg_alpha': 0.04690097622914347, 'reg_lambda': 9.414666527698946e-06, 'max_delta_step': 10}. Best is trial 17 with value: 0.6118421052631579.

Best trial: 17. Best value: 0.611842:  48%|████▊     | 24/50 [05:02<04:50, 11.16s/it]

[I 2025-12-01 20:32:36,067] Trial 21 finished with value: 0.5605263157894737 and parameters: {'max_depth': 10, 'learning_rate': 0.07186415764094348, 'n_estimators': 1019, 'subsample': 0.8423595917481745, 'colsample_bytree': 0.9232247310157354, 'min_child_weight': 3, 'gamma': 2.3581869541867007, 'reg_alpha': 0.00013142383273747862, 'reg_lambda': 0.0030711045019714603, 'max_delta_step': 10}. Best is trial 17 with value: 0.6118421052631579.

Best trial: 17. Best value: 0.611842:  50%|█████     | 25/50 [05:16<04:59, 11.97s/it]

[I 2025-12-01 20:32:49,899] Trial 23 finished with value: 0.5605263157894737 and parameters: {'max_depth': 10, 'learning_rate': 0.18184317462250052, 'n_estimators': 1451, 'subsample': 0.7219255884189986, 'colsample_bytree': 0.9357731311113846, 'min_child_weight': 4, 'gamma': 2.9473675945379183, 'reg_alpha': 0.00020289797936253744, 'reg_lambda': 1.2731248896163455e-08, 'max_delta_step': 10}. Best is trial 17 with value: 0.6118421052631579.

Best trial: 17. Best value: 0.611842:  52%|█████▏    | 26/50 [05:34<05:29, 13.73s/it]

[I 2025-12-01 20:33:07,762] Trial 27 pruned.

Best trial: 17. Best value: 0.611842:  54%|█████▍    | 27/50 [05:34<03:44,  9.76s/it]

[I 2025-12-01 20:33:08,245] Trial 26 pruned.

Best trial: 17. Best value: 0.611842:  56%|█████▌    | 28/50 [05:41<03:16,  8.95s/it]

[I 2025-12-01 20:33:15,304] Trial 25 finished with value: 0.5980263157894736 and parameters: {'max_depth': 9, 'learning_rate': 0.19129892746546612, 'n_estimators': 766, 'subsample': 0.8180267642789311, 'colsample_bytree': 0.9350118456776286, 'min_child_weight': 4, 'gamma': 0.7502995953070651, 'reg_alpha': 0.06778998784312919, 'reg_lambda': 1.1662731339219603e-05, 'max_delta_step': 9}. Best is trial 17 with value: 0.6118421052631579.

Best trial: 17. Best value: 0.611842:  58%|█████▊    | 29/50 [05:48<02:54,  8.33s/it]

[I 2025-12-01 20:33:22,197] Trial 28 pruned.

Best trial: 17. Best value: 0.611842:  60%|██████    | 30/50 [06:14<04:31, 13.57s/it]

[I 2025-12-01 20:33:47,969] Trial 30 finished with value: 0.5717105263157894 and parameters: {'max_depth': 7, 'learning_rate': 0.03233205783972147, 'n_estimators': 702, 'subsample': 0.5643005326434833, 'colsample_bytree': 0.7514025835669254, 'min_child_weight': 6, 'gamma': 0.6685124611398228, 'reg_alpha': 0.0008818037975895, 'reg_lambda': 6.660843956467001e-06, 'max_delta_step': 2}. Best is trial 17 with value: 0.6118421052631579.

Best trial: 17. Best value: 0.611842:  62%|██████▏   | 31/50 [06:17<03:18, 10.44s/it]

[I 2025-12-01 20:33:51,109] Trial 29 finished with value: 0.6105263157894737 and parameters: {'max_depth': 9, 'learning_rate': 0.014154316825404177, 'n_estimators': 703, 'subsample': 0.5696104816747602, 'colsample_bytree': 0.732310744805646, 'min_child_weight': 6, 'gamma': 0.8030143442230032, 'reg_alpha': 0.04961609345243085, 'reg_lambda': 4.5250758953578905e-06, 'max_delta_step': 3}. Best is trial 17 with value: 0.6118421052631579.

Best trial: 32. Best value: 0.636842:  64%|██████▍   | 32/50 [06:30<03:19, 11.07s/it]

[I 2025-12-01 20:34:03,663] Trial 32 finished with value: 0.6368421052631579 and parameters: {'max_depth': 7, 'learning_rate': 0.012759777597053172, 'n_estimators': 711, 'subsample': 0.5647060070029333, 'colsample_bytree': 0.5592003050819251, 'min_child_weight': 6, 'gamma': 0.9977773452355115, 'reg_alpha': 0.0006010808736309192, 'reg_lambda': 2.0184664911413845e-07, 'max_delta_step': 8}. Best is trial 32 with value: 0.6368421052631579.

Best trial: 32. Best value: 0.636842:  66%|██████▌   | 33/50 [06:36<02:43,  9.62s/it]

[I 2025-12-01 20:34:09,902] Trial 31 finished with value: 0.5980263157894736 and parameters: {'max_depth': 7, 'learning_rate': 0.01012123243622563, 'n_estimators': 881, 'subsample': 0.5729843398485177, 'colsample_bytree': 0.7275918476416855, 'min_child_weight': 6, 'gamma': 0.9860834428248649, 'reg_alpha': 2.3068496218431762e-05, 'reg_lambda': 3.4425387893236276e-06, 'max_delta_step': 2}. Best is trial 32 with value: 0.6368421052631579.

Best trial: 32. Best value: 0.636842:  68%|██████▊   | 34/50 [06:38<01:59,  7.48s/it]

[I 2025-12-01 20:34:12,394] Trial 34 pruned.

Best trial: 32. Best value: 0.636842:  70%|███████   | 35/50 [06:43<01:37,  6.47s/it]

[I 2025-12-01 20:34:16,492] Trial 35 pruned.

Best trial: 32. Best value: 0.636842:  72%|███████▏  | 36/50 [06:49<01:31,  6.56s/it]

[I 2025-12-01 20:34:23,259] Trial 36 pruned.

Best trial: 32. Best value: 0.636842:  74%|███████▍  | 37/50 [06:55<01:23,  6.44s/it]

[I 2025-12-01 20:34:29,426] Trial 37 pruned.

Best trial: 32. Best value: 0.636842:  76%|███████▌  | 38/50 [07:04<01:25,  7.13s/it]

[I 2025-12-01 20:34:38,150] Trial 38 pruned.

Best trial: 32. Best value: 0.636842:  78%|███████▊  | 39/50 [07:12<01:21,  7.39s/it]

[I 2025-12-01 20:34:46,164] Trial 39 pruned.

Best trial: 32. Best value: 0.636842:  80%|████████  | 40/50 [07:15<01:00,  6.08s/it]

[I 2025-12-01 20:34:49,195] Trial 40 pruned.

Best trial: 32. Best value: 0.636842:  82%|████████▏ | 41/50 [07:18<00:45,  5.08s/it]

[I 2025-12-01 20:34:51,921] Trial 43 pruned.

Best trial: 32. Best value: 0.636842:  84%|████████▍ | 42/50 [07:25<00:44,  5.62s/it]

[I 2025-12-01 20:34:58,794] Trial 42 pruned.

Best trial: 32. Best value: 0.636842:  86%|████████▌ | 43/50 [07:26<00:30,  4.39s/it]

[I 2025-12-01 20:35:00,308] Trial 41 pruned.

Best trial: 32. Best value: 0.636842:  88%|████████▊ | 44/50 [07:32<00:29,  4.89s/it]

[I 2025-12-01 20:35:06,359] Trial 33 finished with value: 0.5980263157894736 and parameters: {'max_depth': 7, 'learning_rate': 0.017961606429827814, 'n_estimators': 921, 'subsample': 0.7511229746133969, 'colsample_bytree': 0.8962022552312703, 'min_child_weight': 5, 'gamma': 2.106476696472971, 'reg_alpha': 2.14007632316721e-05, 'reg_lambda': 4.100119431490347e-07, 'max_delta_step': 8}. Best is trial 32 with value: 0.6368421052631579.

Best trial: 32. Best value: 0.636842:  90%|█████████ | 45/50 [07:50<00:42,  8.57s/it]

[I 2025-12-01 20:35:23,534] Trial 46 pruned.

Best trial: 32. Best value: 0.636842:  92%|█████████▏| 46/50 [08:04<00:41, 10.32s/it]

[I 2025-12-01 20:35:37,948] Trial 44 finished with value: 0.6243421052631579 and parameters: {'max_depth': 8, 'learning_rate': 0.0127500593183627, 'n_estimators': 727, 'subsample': 0.6051178136102537, 'colsample_bytree': 0.5807183208768019, 'min_child_weight': 6, 'gamma': 1.434317165256947, 'reg_alpha': 0.00298336424200495, 'reg_lambda': 2.336281034106791e-06, 'max_delta_step': 3}. Best is trial 32 with value: 0.6368421052631579.

Best trial: 32. Best value: 0.636842:  94%|█████████▍| 47/50 [08:11<00:27,  9.33s/it]

[I 2025-12-01 20:35:44,947] Trial 45 finished with value: 0.5592105263157895 and parameters: {'max_depth': 8, 'learning_rate': 0.012301774190970734, 'n_estimators': 735, 'subsample': 0.5500196750670433, 'colsample_bytree': 0.7946705341166309, 'min_child_weight': 6, 'gamma': 1.247315771498157, 'reg_alpha': 0.15731936404632185, 'reg_lambda': 3.362688954957002e-06, 'max_delta_step': 4}. Best is trial 32 with value: 0.6368421052631579.

Best trial: 32. Best value: 0.636842:  96%|█████████▌| 48/50 [08:15<00:15,  7.67s/it]

[I 2025-12-01 20:35:48,745] Trial 49 pruned.

Best trial: 32. Best value: 0.636842:  98%|█████████▊| 49/50 [08:17<00:05,  5.92s/it]

[I 2025-12-01 20:35:50,580] Trial 47 finished with value: 0.5592105263157895 and parameters: {'max_depth': 8, 'learning_rate': 0.012171857198994428, 'n_estimators': 748, 'subsample': 0.5467744181312809, 'colsample_bytree': 0.8051412885338596, 'min_child_weight': 6, 'gamma': 1.2163119935418392, 'reg_alpha': 0.21376258825053152, 'reg_lambda': 3.081287855767935e-06, 'max_delta_step': 3}. Best is trial 32 with value: 0.6368421052631579.

Best trial: 32. Best value: 0.636842: 100%|██████████| 50/50 [08:33<00:00, 10.26s/it]

[I 2025-12-01 20:36:06,674] Trial 48 finished with value: 0.6118421052631579 and parameters: {'max_depth': 9, 'learning_rate': 0.011771608364888685, 'n_estimators': 741, 'subsample': 0.6191969428947232, 'colsample_bytree': 0.7921020645850435, 'min_child_weight': 6, 'gamma': 0.018020832239789897, 'reg_alpha': 0.0021256966356331727, 'reg_lambda': 8.358061905995362e-05, 'max_delta_step': 1}. Best is trial 32 with value: 0.6368421052631579.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 20:36:12,438] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.476893:   2%|▏         | 1/50 [00:22<18:12, 22.30s/it]

[I 2025-12-01 20:36:34,729] Trial 3 finished with value: 0.4768934531450577 and parameters: {'max_depth': 8, 'learning_rate': 0.05233382489410305, 'n_estimators': 377, 'subsample': 0.7448346906876563, 'colsample_bytree': 0.7121517601763478, 'min_child_weight': 8, 'gamma': 2.319105252346396, 'reg_alpha': 0.003785288736195815, 'reg_lambda': 8.234678876442965e-06, 'max_delta_step': 8}. Best is trial 3 with value: 0.4768934531450577.

Best trial: 3. Best value: 0.476893:   4%|▍         | 2/50 [00:43<17:19, 21.67s/it]

[I 2025-12-01 20:36:55,950] Trial 1 finished with value: 0.42233632862644416 and parameters: {'max_depth': 9, 'learning_rate': 0.06037069962991559, 'n_estimators': 390, 'subsample': 0.588929811204308, 'colsample_bytree': 0.7085698237728151, 'min_child_weight': 1, 'gamma': 4.879789194676265, 'reg_alpha': 8.677544917797917e-06, 'reg_lambda': 7.84530985903998e-07, 'max_delta_step': 6}. Best is trial 3 with value: 0.4768934531450577.

Best trial: 2. Best value: 0.509628:   6%|▌         | 3/50 [01:05<17:11, 21.95s/it]

[I 2025-12-01 20:37:18,228] Trial 2 finished with value: 0.5096277278562259 and parameters: {'max_depth': 5, 'learning_rate': 0.23215936129394457, 'n_estimators': 1151, 'subsample': 0.7412959096213458, 'colsample_bytree': 0.7085646975810709, 'min_child_weight': 2, 'gamma': 1.7346253548281032, 'reg_alpha': 2.832617133866049e-05, 'reg_lambda': 3.5774339866996394e-08, 'max_delta_step': 8}. Best is trial 2 with value: 0.5096277278562259.

Best trial: 2. Best value: 0.509628:   8%|▊         | 4/50 [01:11<11:46, 15.36s/it]

[I 2025-12-01 20:37:23,484] Trial 0 finished with value: 0.39473684210526316 and parameters: {'max_depth': 6, 'learning_rate': 0.05359293686183795, 'n_estimators': 1436, 'subsample': 0.646553588357575, 'colsample_bytree': 0.7605514108610889, 'min_child_weight': 9, 'gamma': 0.5351060977265115, 'reg_alpha': 0.024380206463877202, 'reg_lambda': 6.741934238415798e-05, 'max_delta_step': 2}. Best is trial 2 with value: 0.5096277278562259.

Best trial: 2. Best value: 0.509628:  10%|█         | 5/50 [01:36<14:11, 18.92s/it]

[I 2025-12-01 20:37:48,729] Trial 4 finished with value: 0.4871630295250321 and parameters: {'max_depth': 5, 'learning_rate': 0.19243905609094317, 'n_estimators': 734, 'subsample': 0.8478590297958897, 'colsample_bytree': 0.9499832469713233, 'min_child_weight': 2, 'gamma': 3.822941287987443, 'reg_alpha': 7.781010953478424e-05, 'reg_lambda': 1.447478486090079e-08, 'max_delta_step': 9}. Best is trial 2 with value: 0.5096277278562259.

Best trial: 2. Best value: 0.509628:  12%|█▏        | 6/50 [01:37<09:25, 12.86s/it]

[I 2025-12-01 20:37:49,788] Trial 6 finished with value: 0.43645699614890887 and parameters: {'max_depth': 4, 'learning_rate': 0.17998235003613963, 'n_estimators': 223, 'subsample': 0.8872175424081541, 'colsample_bytree': 0.9268386086037022, 'min_child_weight': 2, 'gamma': 3.341521761154966, 'reg_alpha': 3.469102606507195e-06, 'reg_lambda': 3.5193965172721714e-05, 'max_delta_step': 5}. Best is trial 2 with value: 0.5096277278562259.

Best trial: 2. Best value: 0.509628:  14%|█▍        | 7/50 [01:56<10:42, 14.95s/it]

[I 2025-12-01 20:38:09,069] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.014080680620071877, 'n_estimators': 225, 'subsample': 0.719108180887995, 'colsample_bytree': 0.683364734754637, 'min_child_weight': 10, 'gamma': 1.3089066686610225, 'reg_alpha': 0.00015628566053635563, 'reg_lambda': 0.9153599129044173, 'max_delta_step': 4}. Best is trial 2 with value: 0.5096277278562259.

Best trial: 2. Best value: 0.509628:  16%|█▌        | 8/50 [02:26<13:53, 19.84s/it]

[I 2025-12-01 20:38:39,390] Trial 8 finished with value: 0.40821566110397944 and parameters: {'max_depth': 3, 'learning_rate': 0.041372427941718116, 'n_estimators': 433, 'subsample': 0.5540928928181685, 'colsample_bytree': 0.9234750624266734, 'min_child_weight': 3, 'gamma': 0.8266187164611166, 'reg_alpha': 3.0157285964488664e-07, 'reg_lambda': 3.1960638465113975e-06, 'max_delta_step': 4}. Best is trial 2 with value: 0.5096277278562259.

Best trial: 2. Best value: 0.509628:  18%|█▊        | 9/50 [02:37<11:32, 16.88s/it]

[I 2025-12-01 20:38:49,768] Trial 7 finished with value: 0.3960205391527599 and parameters: {'max_depth': 9, 'learning_rate': 0.2196018542594364, 'n_estimators': 1309, 'subsample': 0.9957566764933865, 'colsample_bytree': 0.8347945434730739, 'min_child_weight': 4, 'gamma': 1.1065751350583675, 'reg_alpha': 8.741118257443571e-07, 'reg_lambda': 1.984716487652245e-06, 'max_delta_step': 9}. Best is trial 2 with value: 0.5096277278562259.

Best trial: 2. Best value: 0.509628:  20%|██        | 10/50 [02:38<07:55, 11.88s/it]

[I 2025-12-01 20:38:50,453] Trial 5 finished with value: 0.4871630295250321 and parameters: {'max_depth': 3, 'learning_rate': 0.012954934138865925, 'n_estimators': 839, 'subsample': 0.7878236966641501, 'colsample_bytree': 0.8296630551421847, 'min_child_weight': 3, 'gamma': 3.81644558952019, 'reg_alpha': 0.0022551132604323922, 'reg_lambda': 3.371296425857375e-08, 'max_delta_step': 1}. Best is trial 2 with value: 0.5096277278562259.

Best trial: 2. Best value: 0.509628:  22%|██▏       | 11/50 [02:41<05:59,  9.21s/it]

[I 2025-12-01 20:38:53,587] Trial 10 pruned.

Best trial: 2. Best value: 0.509628:  24%|██▍       | 12/50 [02:41<04:05,  6.47s/it]

[I 2025-12-01 20:38:53,806] Trial 11 pruned.

Best trial: 2. Best value: 0.509628:  26%|██▌       | 13/50 [02:48<04:08,  6.71s/it]

[I 2025-12-01 20:39:01,076] Trial 13 pruned.

Best trial: 2. Best value: 0.509628:  28%|██▊       | 14/50 [02:56<04:13,  7.03s/it]

[I 2025-12-01 20:39:08,851] Trial 12 pruned.

Best trial: 2. Best value: 0.509628:  30%|███       | 15/50 [02:58<03:09,  5.41s/it]

[I 2025-12-01 20:39:10,497] Trial 16 pruned.

Best trial: 2. Best value: 0.509628:  32%|███▏      | 16/50 [03:03<03:03,  5.39s/it]

[I 2025-12-01 20:39:15,844] Trial 17 pruned.

Best trial: 2. Best value: 0.509628:  34%|███▍      | 17/50 [03:09<03:01,  5.49s/it]

[I 2025-12-01 20:39:21,576] Trial 18 pruned.

Best trial: 2. Best value: 0.509628:  36%|███▌      | 18/50 [03:28<05:08,  9.64s/it]

[I 2025-12-01 20:39:40,862] Trial 19 pruned.

Best trial: 2. Best value: 0.509628:  38%|███▊      | 19/50 [03:42<05:39, 10.95s/it]

[I 2025-12-01 20:39:54,877] Trial 15 finished with value: 0.4486521181001284 and parameters: {'max_depth': 5, 'learning_rate': 0.11388914596705822, 'n_estimators': 1153, 'subsample': 0.8513864241569389, 'colsample_bytree': 0.547441798580901, 'min_child_weight': 6, 'gamma': 3.2676499026083157, 'reg_alpha': 1.3006069673345173, 'reg_lambda': 0.004995720584348157, 'max_delta_step': 9}. Best is trial 2 with value: 0.5096277278562259.

Best trial: 2. Best value: 0.509628:  40%|████      | 20/50 [03:45<04:21,  8.72s/it]

[I 2025-12-01 20:39:58,397] Trial 14 finished with value: 0.46277278562259305 and parameters: {'max_depth': 5, 'learning_rate': 0.1235681837328839, 'n_estimators': 1115, 'subsample': 0.8528386753148851, 'colsample_bytree': 0.5537437926798799, 'min_child_weight': 6, 'gamma': 2.346435405336636, 'reg_alpha': 5.615233539993986, 'reg_lambda': 1.0808671860495893e-08, 'max_delta_step': 10}. Best is trial 2 with value: 0.5096277278562259.

Best trial: 2. Best value: 0.509628:  42%|████▏     | 21/50 [03:53<04:06,  8.51s/it]

[I 2025-12-01 20:40:06,399] Trial 22 pruned.

Best trial: 2. Best value: 0.509628:  44%|████▍     | 22/50 [04:01<03:48,  8.16s/it]

[I 2025-12-01 20:40:13,757] Trial 23 pruned.

Best trial: 2. Best value: 0.509628:  46%|████▌     | 23/50 [04:33<06:57, 15.47s/it]

[I 2025-12-01 20:40:46,274] Trial 21 finished with value: 0.4608472400513479 and parameters: {'max_depth': 4, 'learning_rate': 0.079743373842622, 'n_estimators': 1196, 'subsample': 0.8068762081524581, 'colsample_bytree': 0.76375299956506, 'min_child_weight': 7, 'gamma': 4.316970390713884, 'reg_alpha': 8.159825259515435e-05, 'reg_lambda': 1.597810017944995e-07, 'max_delta_step': 8}. Best is trial 2 with value: 0.5096277278562259.

Best trial: 2. Best value: 0.509628:  48%|████▊     | 24/50 [04:50<06:53, 15.90s/it]

[I 2025-12-01 20:41:03,163] Trial 26 pruned.

Best trial: 2. Best value: 0.509628:  50%|█████     | 25/50 [04:58<05:38, 13.54s/it]

[I 2025-12-01 20:41:11,207] Trial 20 finished with value: 0.4974326059050064 and parameters: {'max_depth': 4, 'learning_rate': 0.08347160107851583, 'n_estimators': 1252, 'subsample': 0.7885226878380448, 'colsample_bytree': 0.9989441450829496, 'min_child_weight': 2, 'gamma': 1.604932959880661, 'reg_alpha': 0.6343448105778572, 'reg_lambda': 0.0012172619391181548, 'max_delta_step': 8}. Best is trial 2 with value: 0.5096277278562259.

Best trial: 2. Best value: 0.509628:  52%|█████▏    | 26/50 [05:05<04:32, 11.37s/it]

[I 2025-12-01 20:41:17,526] Trial 27 pruned.

Best trial: 2. Best value: 0.509628:  54%|█████▍    | 27/50 [05:14<04:08, 10.79s/it]

[I 2025-12-01 20:41:26,968] Trial 28 pruned.

Best trial: 2. Best value: 0.509628:  56%|█████▌    | 28/50 [05:24<03:52, 10.55s/it]

[I 2025-12-01 20:41:36,934] Trial 29 pruned.

Best trial: 2. Best value: 0.509628:  58%|█████▊    | 29/50 [05:34<03:36, 10.32s/it]

[I 2025-12-01 20:41:46,711] Trial 30 pruned.

Best trial: 2. Best value: 0.509628:  60%|██████    | 30/50 [05:39<02:57,  8.89s/it]

[I 2025-12-01 20:41:52,270] Trial 31 pruned.

Best trial: 2. Best value: 0.509628:  64%|██████▍   | 32/50 [05:45<01:40,  5.59s/it]

[I 2025-12-01 20:41:57,952] Trial 32 pruned.
[I 2025-12-01 20:41:58,085] Trial 24 finished with value: 0.4608472400513479 and parameters: {'max_depth': 3, 'learning_rate': 0.01209334439284875, 'n_estimators': 828, 'subsample': 0.7770777469681808, 'colsample_bytree': 0.9909360871524369, 'min_child_weight': 3, 'gamma': 4.029070140794351, 'reg_alpha': 0.00010584299564373198, 'reg_lambda': 1.5044804687376695e-07, 'max_delta_step': 0}. Best is trial 2 with value: 0.5096277278562259.

Best trial: 2. Best value: 0.509628:  66%|██████▌   | 33/50 [05:52<01:41,  5.99s/it]

[I 2025-12-01 20:42:05,025] Trial 33 pruned.

Best trial: 2. Best value: 0.509628:  68%|██████▊   | 34/50 [05:58<01:33,  5.82s/it]

[I 2025-12-01 20:42:10,454] Trial 25 finished with value: 0.4608472400513479 and parameters: {'max_depth': 3, 'learning_rate': 0.010017111774542472, 'n_estimators': 788, 'subsample': 0.7834147780469412, 'colsample_bytree': 0.8103840366479995, 'min_child_weight': 2, 'gamma': 4.240490611554062, 'reg_alpha': 0.00010415778564382239, 'reg_lambda': 6.023740209333988e-08, 'max_delta_step': 0}. Best is trial 2 with value: 0.5096277278562259.

Best trial: 2. Best value: 0.509628:  70%|███████   | 35/50 [06:13<02:09,  8.66s/it]

[I 2025-12-01 20:42:25,736] Trial 34 pruned.

Best trial: 2. Best value: 0.509628:  72%|███████▏  | 36/50 [06:33<02:51, 12.26s/it]

[I 2025-12-01 20:42:46,404] Trial 35 pruned.

Best trial: 2. Best value: 0.509628:  74%|███████▍  | 37/50 [06:49<02:50, 13.15s/it]

[I 2025-12-01 20:43:01,629] Trial 37 pruned.

Best trial: 2. Best value: 0.509628:  76%|███████▌  | 38/50 [06:53<02:05, 10.48s/it]

[I 2025-12-01 20:43:05,868] Trial 38 pruned.

Best trial: 2. Best value: 0.509628:  78%|███████▊  | 39/50 [07:14<02:29, 13.56s/it]

[I 2025-12-01 20:43:26,620] Trial 41 pruned.

Best trial: 2. Best value: 0.509628:  80%|████████  | 40/50 [07:22<01:58, 11.90s/it]

[I 2025-12-01 20:43:34,639] Trial 40 pruned.

Best trial: 2. Best value: 0.509628:  82%|████████▏ | 41/50 [07:23<01:18,  8.70s/it]

[I 2025-12-01 20:43:35,875] Trial 39 pruned.

Best trial: 2. Best value: 0.509628:  84%|████████▍ | 42/50 [07:24<00:52,  6.52s/it]

[I 2025-12-01 20:43:37,306] Trial 42 pruned.

Best trial: 2. Best value: 0.509628:  86%|████████▌ | 43/50 [07:27<00:36,  5.21s/it]

[I 2025-12-01 20:43:39,468] Trial 44 pruned.

Best trial: 2. Best value: 0.509628:  88%|████████▊ | 44/50 [07:27<00:22,  3.78s/it]

[I 2025-12-01 20:43:39,890] Trial 45 pruned.

Best trial: 2. Best value: 0.509628:  90%|█████████ | 45/50 [07:32<00:21,  4.21s/it]

[I 2025-12-01 20:43:45,123] Trial 36 finished with value: 0.4486521181001284 and parameters: {'max_depth': 3, 'learning_rate': 0.01757796781624958, 'n_estimators': 771, 'subsample': 0.7142805006936568, 'colsample_bytree': 0.7328198701817477, 'min_child_weight': 1, 'gamma': 4.561586365168842, 'reg_alpha': 0.0005948357596391758, 'reg_lambda': 5.762413835416468e-08, 'max_delta_step': 2}. Best is trial 2 with value: 0.5096277278562259.

Best trial: 2. Best value: 0.509628:  92%|█████████▏| 46/50 [07:34<00:13,  3.46s/it]

[I 2025-12-01 20:43:46,846] Trial 43 pruned.

Best trial: 2. Best value: 0.509628:  94%|█████████▍| 47/50 [07:38<00:10,  3.62s/it]

[I 2025-12-01 20:43:50,836] Trial 47 pruned.

Best trial: 2. Best value: 0.509628:  96%|█████████▌| 48/50 [07:45<00:09,  4.77s/it]

[I 2025-12-01 20:43:58,285] Trial 46 finished with value: 0.4871630295250321 and parameters: {'max_depth': 8, 'learning_rate': 0.04265589510267175, 'n_estimators': 221, 'subsample': 0.8705533326867688, 'colsample_bytree': 0.7994235644738593, 'min_child_weight': 8, 'gamma': 1.0220706050997785, 'reg_alpha': 0.005068132178242495, 'reg_lambda': 3.332063909966325e-06, 'max_delta_step': 8}. Best is trial 2 with value: 0.5096277278562259.

Best trial: 2. Best value: 0.509628:  98%|█████████▊| 49/50 [07:48<00:04,  4.10s/it]

[I 2025-12-01 20:44:00,828] Trial 49 pruned.

Best trial: 48. Best value: 0.55199: 100%|██████████| 50/50 [08:12<00:00,  9.85s/it]

[I 2025-12-01 20:44:24,806] Trial 48 finished with value: 0.5519897304236201 and parameters: {'max_depth': 7, 'learning_rate': 0.03227247839155076, 'n_estimators': 881, 'subsample': 0.7784234212166523, 'colsample_bytree': 0.9122094112231279, 'min_child_weight': 8, 'gamma': 1.5747693567231176, 'reg_alpha': 0.0003447994597841088, 'reg_lambda': 3.878363377544826e-06, 'max_delta_step': 7}. Best is trial 48 with value: 0.5519897304236201.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 20:44:29,953] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.495395:   2%|▏         | 1/50 [00:26<21:19, 26.11s/it]

[I 2025-12-01 20:44:56,054] Trial 0 finished with value: 0.4953947368421053 and parameters: {'max_depth': 6, 'learning_rate': 0.03039994893593894, 'n_estimators': 269, 'subsample': 0.6435433505667904, 'colsample_bytree': 0.5637966633214818, 'min_child_weight': 4, 'gamma': 3.02752229704169, 'reg_alpha': 3.792035813640974e-05, 'reg_lambda': 1.8337884937920742e-08, 'max_delta_step': 0}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:   4%|▍         | 2/50 [01:15<31:47, 39.74s/it]

[I 2025-12-01 20:45:45,338] Trial 1 finished with value: 0.45789473684210524 and parameters: {'max_depth': 4, 'learning_rate': 0.15332028206392181, 'n_estimators': 804, 'subsample': 0.5312061879754819, 'colsample_bytree': 0.9717624454502712, 'min_child_weight': 2, 'gamma': 4.43347143514658, 'reg_alpha': 2.177800435891148e-08, 'reg_lambda': 8.843698406926942, 'max_delta_step': 1}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:   6%|▌         | 3/50 [01:31<22:48, 29.12s/it]

[I 2025-12-01 20:46:01,814] Trial 3 finished with value: 0.39013157894736844 and parameters: {'max_depth': 3, 'learning_rate': 0.054341115471672426, 'n_estimators': 1102, 'subsample': 0.9615568575214142, 'colsample_bytree': 0.6475543670269248, 'min_child_weight': 2, 'gamma': 2.9124187662103256, 'reg_alpha': 0.02884619198754706, 'reg_lambda': 1.6431488490679899e-07, 'max_delta_step': 3}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:   8%|▊         | 4/50 [01:53<20:08, 26.28s/it]

[I 2025-12-01 20:46:23,742] Trial 4 finished with value: 0.4052631578947368 and parameters: {'max_depth': 5, 'learning_rate': 0.019199125408462053, 'n_estimators': 759, 'subsample': 0.9689129859657148, 'colsample_bytree': 0.7645617903086634, 'min_child_weight': 3, 'gamma': 2.79824452124984, 'reg_alpha': 2.230645504787622, 'reg_lambda': 0.11608014202335437, 'max_delta_step': 1}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  10%|█         | 5/50 [02:04<15:32, 20.73s/it]

[I 2025-12-01 20:46:34,620] Trial 2 finished with value: 0.4164473684210527 and parameters: {'max_depth': 6, 'learning_rate': 0.01866864261993166, 'n_estimators': 1282, 'subsample': 0.9948666359047456, 'colsample_bytree': 0.8159980856949309, 'min_child_weight': 3, 'gamma': 2.1294122747281845, 'reg_alpha': 2.166242089711645e-06, 'reg_lambda': 0.014082715440575268, 'max_delta_step': 6}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  12%|█▏        | 6/50 [02:19<13:46, 18.78s/it]

[I 2025-12-01 20:46:49,637] Trial 6 finished with value: 0.4026315789473684 and parameters: {'max_depth': 7, 'learning_rate': 0.07821583084829847, 'n_estimators': 522, 'subsample': 0.7636673271718819, 'colsample_bytree': 0.855931758423621, 'min_child_weight': 3, 'gamma': 0.44662700920238274, 'reg_alpha': 0.0056117993379201465, 'reg_lambda': 2.5624222931647015e-07, 'max_delta_step': 1}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  14%|█▍        | 7/50 [02:30<11:40, 16.29s/it]

[I 2025-12-01 20:47:00,788] Trial 7 finished with value: 0.44276315789473686 and parameters: {'max_depth': 7, 'learning_rate': 0.04974581453911812, 'n_estimators': 512, 'subsample': 0.6925038765409788, 'colsample_bytree': 0.5909312491846582, 'min_child_weight': 5, 'gamma': 4.716849593544216, 'reg_alpha': 3.659839622663345e-05, 'reg_lambda': 0.6225166228326252, 'max_delta_step': 8}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  16%|█▌        | 8/50 [02:40<09:50, 14.06s/it]

[I 2025-12-01 20:47:10,066] Trial 5 finished with value: 0.48289473684210527 and parameters: {'max_depth': 4, 'learning_rate': 0.024069292170654608, 'n_estimators': 1466, 'subsample': 0.8995290271427938, 'colsample_bytree': 0.511191829949907, 'min_child_weight': 7, 'gamma': 1.0807682385549733, 'reg_alpha': 2.0418528416088443e-07, 'reg_lambda': 4.833621057105629e-05, 'max_delta_step': 0}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  18%|█▊        | 9/50 [02:50<08:48, 12.89s/it]

[I 2025-12-01 20:47:20,389] Trial 8 finished with value: 0.43157894736842106 and parameters: {'max_depth': 7, 'learning_rate': 0.054263100318793625, 'n_estimators': 716, 'subsample': 0.5232680425770184, 'colsample_bytree': 0.5241070360682748, 'min_child_weight': 5, 'gamma': 1.5898301062206293, 'reg_alpha': 5.33739426389816, 'reg_lambda': 5.828221982263823e-06, 'max_delta_step': 4}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  20%|██        | 10/50 [03:12<10:30, 15.77s/it]

[I 2025-12-01 20:47:42,609] Trial 9 finished with value: 0.48289473684210527 and parameters: {'max_depth': 9, 'learning_rate': 0.01835147601962544, 'n_estimators': 883, 'subsample': 0.6757556825576865, 'colsample_bytree': 0.7985253112433686, 'min_child_weight': 7, 'gamma': 1.3611367667066125, 'reg_alpha': 0.007891288260646038, 'reg_lambda': 6.763529171530308e-08, 'max_delta_step': 5}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  22%|██▏       | 11/50 [03:15<07:41, 11.83s/it]

[I 2025-12-01 20:47:45,512] Trial 12 pruned.

Best trial: 0. Best value: 0.495395:  24%|██▍       | 12/50 [03:16<05:19,  8.40s/it]

[I 2025-12-01 20:47:46,051] Trial 13 pruned.

Best trial: 0. Best value: 0.495395:  26%|██▌       | 13/50 [03:17<03:56,  6.40s/it]

[I 2025-12-01 20:47:47,850] Trial 14 pruned.

Best trial: 0. Best value: 0.495395:  28%|██▊       | 14/50 [03:26<04:15,  7.11s/it]

[I 2025-12-01 20:47:56,602] Trial 16 pruned.

Best trial: 0. Best value: 0.495395:  30%|███       | 15/50 [03:28<03:17,  5.63s/it]

[I 2025-12-01 20:47:58,820] Trial 10 finished with value: 0.481578947368421 and parameters: {'max_depth': 6, 'learning_rate': 0.038996556212685114, 'n_estimators': 852, 'subsample': 0.9274899536264816, 'colsample_bytree': 0.7505484275567791, 'min_child_weight': 6, 'gamma': 2.9582666874085737, 'reg_alpha': 0.00011301643230519078, 'reg_lambda': 0.1046794699994261, 'max_delta_step': 4}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  32%|███▏      | 16/50 [03:33<02:58,  5.24s/it]

[I 2025-12-01 20:48:03,132] Trial 18 pruned.

Best trial: 0. Best value: 0.495395:  34%|███▍      | 17/50 [03:37<02:43,  4.95s/it]

[I 2025-12-01 20:48:07,423] Trial 15 finished with value: 0.48289473684210527 and parameters: {'max_depth': 5, 'learning_rate': 0.02923668479764177, 'n_estimators': 236, 'subsample': 0.8590720189831178, 'colsample_bytree': 0.500508622717701, 'min_child_weight': 7, 'gamma': 0.3417820838321779, 'reg_alpha': 9.85782199630074e-08, 'reg_lambda': 3.8152753174911324e-05, 'max_delta_step': 0}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  36%|███▌      | 18/50 [03:45<03:11,  5.99s/it]

[I 2025-12-01 20:48:15,826] Trial 11 finished with value: 0.4565789473684211 and parameters: {'max_depth': 8, 'learning_rate': 0.07361088836293364, 'n_estimators': 903, 'subsample': 0.9907097120879333, 'colsample_bytree': 0.7010128517954722, 'min_child_weight': 5, 'gamma': 4.106650868053691, 'reg_alpha': 1.7907658230748217e-06, 'reg_lambda': 0.6465454357792073, 'max_delta_step': 4}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  38%|███▊      | 19/50 [04:55<13:01, 25.21s/it]

[I 2025-12-01 20:49:25,816] Trial 17 finished with value: 0.4552631578947368 and parameters: {'max_depth': 5, 'learning_rate': 0.02765539302445073, 'n_estimators': 1494, 'subsample': 0.8559129394446376, 'colsample_bytree': 0.685473640780311, 'min_child_weight': 6, 'gamma': 1.397440106087595, 'reg_alpha': 1.1237960056618538e-08, 'reg_lambda': 1.3124666043787852e-08, 'max_delta_step': 0}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  40%|████      | 20/50 [04:57<09:06, 18.22s/it]

[I 2025-12-01 20:49:27,740] Trial 19 finished with value: 0.46907894736842104 and parameters: {'max_depth': 8, 'learning_rate': 0.027143693504917778, 'n_estimators': 1464, 'subsample': 0.6035627094085596, 'colsample_bytree': 0.5822959229057649, 'min_child_weight': 4, 'gamma': 3.963232446973426, 'reg_alpha': 2.896993494477146e-06, 'reg_lambda': 0.0006747412684955206, 'max_delta_step': 2}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  42%|████▏     | 21/50 [05:02<06:48, 14.08s/it]

[I 2025-12-01 20:49:32,175] Trial 20 finished with value: 0.4164473684210527 and parameters: {'max_depth': 8, 'learning_rate': 0.024982492175513023, 'n_estimators': 1466, 'subsample': 0.6101740329222824, 'colsample_bytree': 0.5741174316102994, 'min_child_weight': 4, 'gamma': 3.798120990953266, 'reg_alpha': 4.039417752415256e-06, 'reg_lambda': 0.0010810451463971616, 'max_delta_step': 2}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  44%|████▍     | 22/50 [05:14<06:16, 13.44s/it]

[I 2025-12-01 20:49:44,115] Trial 24 pruned.

Best trial: 0. Best value: 0.495395:  46%|████▌     | 23/50 [05:15<04:23,  9.77s/it]

[I 2025-12-01 20:49:45,319] Trial 21 finished with value: 0.481578947368421 and parameters: {'max_depth': 4, 'learning_rate': 0.024759410810266794, 'n_estimators': 1491, 'subsample': 0.6021175276612027, 'colsample_bytree': 0.5810377704857193, 'min_child_weight': 4, 'gamma': 1.9683926447881794, 'reg_alpha': 7.38671230571383e-06, 'reg_lambda': 0.0023138814814851402, 'max_delta_step': 2}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  48%|████▊     | 24/50 [05:54<08:02, 18.57s/it]

[I 2025-12-01 20:50:24,420] Trial 26 finished with value: 0.4953947368421053 and parameters: {'max_depth': 9, 'learning_rate': 0.015022845023028903, 'n_estimators': 603, 'subsample': 0.7166625316313636, 'colsample_bytree': 0.6321768468230864, 'min_child_weight': 7, 'gamma': 1.009179828231877, 'reg_alpha': 0.21951847763474733, 'reg_lambda': 2.029583775255091e-06, 'max_delta_step': 8}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  50%|█████     | 25/50 [06:01<06:20, 15.20s/it]

[I 2025-12-01 20:50:31,775] Trial 23 finished with value: 0.419078947368421 and parameters: {'max_depth': 4, 'learning_rate': 0.015092575956006968, 'n_estimators': 1237, 'subsample': 0.751675781021083, 'colsample_bytree': 0.5574545376483082, 'min_child_weight': 8, 'gamma': 1.9124823622084426, 'reg_alpha': 0.0009113768482270943, 'reg_lambda': 1.6498833694339771e-06, 'max_delta_step': 7}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  52%|█████▏    | 26/50 [06:11<05:25, 13.57s/it]

[I 2025-12-01 20:50:41,514] Trial 25 finished with value: 0.48289473684210527 and parameters: {'max_depth': 4, 'learning_rate': 0.013954123185012471, 'n_estimators': 960, 'subsample': 0.7141624823445338, 'colsample_bytree': 0.620458601310902, 'min_child_weight': 7, 'gamma': 0.7025767704456535, 'reg_alpha': 0.0006426985046075858, 'reg_lambda': 2.121142659209321e-06, 'max_delta_step': 8}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  54%|█████▍    | 27/50 [06:17<04:16, 11.17s/it]

[I 2025-12-01 20:50:47,100] Trial 29 pruned.

Best trial: 0. Best value: 0.495395:  56%|█████▌    | 28/50 [06:21<03:21,  9.15s/it]

[I 2025-12-01 20:50:51,541] Trial 30 pruned.

Best trial: 0. Best value: 0.495395:  58%|█████▊    | 29/50 [06:25<02:41,  7.69s/it]

[I 2025-12-01 20:50:55,826] Trial 22 finished with value: 0.44276315789473686 and parameters: {'max_depth': 4, 'learning_rate': 0.014167838900152375, 'n_estimators': 1225, 'subsample': 0.5938240266969733, 'colsample_bytree': 0.5753519638108763, 'min_child_weight': 4, 'gamma': 2.023575680877159, 'reg_alpha': 0.0011423493128990953, 'reg_lambda': 0.0007366488349335628, 'max_delta_step': 2}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  60%|██████    | 30/50 [06:26<01:53,  5.67s/it]

[I 2025-12-01 20:50:56,794] Trial 31 pruned.

Best trial: 0. Best value: 0.495395:  62%|██████▏   | 31/50 [06:28<01:27,  4.62s/it]

[I 2025-12-01 20:50:58,939] Trial 27 finished with value: 0.4953947368421053 and parameters: {'max_depth': 6, 'learning_rate': 0.013216892797061668, 'n_estimators': 425, 'subsample': 0.7405314842250239, 'colsample_bytree': 0.6278094989916004, 'min_child_weight': 7, 'gamma': 0.8399772751557334, 'reg_alpha': 0.11945406589522788, 'reg_lambda': 1.7860812509193762e-06, 'max_delta_step': 8}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  64%|██████▍   | 32/50 [06:32<01:19,  4.40s/it]

[I 2025-12-01 20:51:02,823] Trial 33 pruned.

Best trial: 0. Best value: 0.495395:  66%|██████▌   | 33/50 [06:33<00:54,  3.21s/it]

[I 2025-12-01 20:51:03,268] Trial 32 pruned.

Best trial: 0. Best value: 0.495395:  68%|██████▊   | 34/50 [06:47<01:42,  6.43s/it]

[I 2025-12-01 20:51:17,211] Trial 28 finished with value: 0.4953947368421053 and parameters: {'max_depth': 6, 'learning_rate': 0.012940160667619683, 'n_estimators': 624, 'subsample': 0.7055058403861271, 'colsample_bytree': 0.6295749447740832, 'min_child_weight': 7, 'gamma': 0.9703545731952257, 'reg_alpha': 0.7854268279218266, 'reg_lambda': 5.3843719842325686e-05, 'max_delta_step': 10}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  70%|███████   | 35/50 [07:03<02:19,  9.27s/it]

[I 2025-12-01 20:51:33,107] Trial 34 finished with value: 0.4677631578947368 and parameters: {'max_depth': 7, 'learning_rate': 0.02174207181807476, 'n_estimators': 372, 'subsample': 0.7323903480162999, 'colsample_bytree': 0.6168754440397721, 'min_child_weight': 6, 'gamma': 1.0654283972372003, 'reg_alpha': 0.238800712727558, 'reg_lambda': 6.431896115126533e-08, 'max_delta_step': 9}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  72%|███████▏  | 36/50 [07:03<01:32,  6.62s/it]

[I 2025-12-01 20:51:33,537] Trial 35 finished with value: 0.47039473684210525 and parameters: {'max_depth': 6, 'learning_rate': 0.0209620412326164, 'n_estimators': 470, 'subsample': 0.7852648537087736, 'colsample_bytree': 0.6204530635827876, 'min_child_weight': 8, 'gamma': 0.9325603785885136, 'reg_alpha': 0.06698755813122131, 'reg_lambda': 5.026479444858382e-08, 'max_delta_step': 7}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  74%|███████▍  | 37/50 [07:04<01:02,  4.78s/it]

[I 2025-12-01 20:51:34,013] Trial 36 finished with value: 0.48289473684210527 and parameters: {'max_depth': 7, 'learning_rate': 0.02121152813604424, 'n_estimators': 468, 'subsample': 0.787527756836153, 'colsample_bytree': 0.6162631877915238, 'min_child_weight': 8, 'gamma': 0.9475775466383882, 'reg_alpha': 0.18549783999132036, 'reg_lambda': 1.3887666148581125e-05, 'max_delta_step': 6}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  76%|███████▌  | 38/50 [07:18<01:30,  7.58s/it]

[I 2025-12-01 20:51:48,130] Trial 37 finished with value: 0.47039473684210525 and parameters: {'max_depth': 7, 'learning_rate': 0.02021102565722249, 'n_estimators': 464, 'subsample': 0.7858030692428106, 'colsample_bytree': 0.6313963053423972, 'min_child_weight': 8, 'gamma': 0.6629308490947066, 'reg_alpha': 0.30335363893885675, 'reg_lambda': 4.5960508973856615e-08, 'max_delta_step': 9}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  78%|███████▊  | 39/50 [07:40<02:10, 11.88s/it]

[I 2025-12-01 20:52:10,046] Trial 38 finished with value: 0.45789473684210524 and parameters: {'max_depth': 6, 'learning_rate': 0.012488647860646032, 'n_estimators': 492, 'subsample': 0.7867237254474236, 'colsample_bytree': 0.6600747178621955, 'min_child_weight': 8, 'gamma': 0.04184410578435083, 'reg_alpha': 1.221851958437124, 'reg_lambda': 9.371346857983574e-06, 'max_delta_step': 8}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  80%|████████  | 40/50 [09:02<05:31, 33.12s/it]

[I 2025-12-01 20:53:32,705] Trial 40 finished with value: 0.43026315789473685 and parameters: {'max_depth': 6, 'learning_rate': 0.011482500140008435, 'n_estimators': 725, 'subsample': 0.7038905369561697, 'colsample_bytree': 0.6521265224058729, 'min_child_weight': 3, 'gamma': 0.5848655527011923, 'reg_alpha': 1.4411525883281993, 'reg_lambda': 2.3181479112087213e-07, 'max_delta_step': 8}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  82%|████████▏ | 41/50 [09:06<03:37, 24.20s/it]

[I 2025-12-01 20:53:36,123] Trial 43 pruned.

Best trial: 0. Best value: 0.495395:  84%|████████▍ | 42/50 [09:13<02:32, 19.05s/it]

[I 2025-12-01 20:53:43,143] Trial 42 finished with value: 0.44276315789473686 and parameters: {'max_depth': 5, 'learning_rate': 0.011244722914541686, 'n_estimators': 710, 'subsample': 0.6996016518818561, 'colsample_bytree': 0.5444933080518322, 'min_child_weight': 2, 'gamma': 1.5468484070307746, 'reg_alpha': 6.766148156533532, 'reg_lambda': 0.008883339123620635, 'max_delta_step': 10}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  86%|████████▌ | 43/50 [09:21<01:49, 15.71s/it]

[I 2025-12-01 20:53:51,049] Trial 41 finished with value: 0.44276315789473686 and parameters: {'max_depth': 6, 'learning_rate': 0.01297425632708788, 'n_estimators': 692, 'subsample': 0.6972763642437015, 'colsample_bytree': 0.6546555502035155, 'min_child_weight': 2, 'gamma': 1.6799598265213478, 'reg_alpha': 1.4911802717917926, 'reg_lambda': 3.1259044115618947e-07, 'max_delta_step': 8}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  88%|████████▊ | 44/50 [09:35<01:31, 15.24s/it]

[I 2025-12-01 20:54:05,198] Trial 39 finished with value: 0.41776315789473684 and parameters: {'max_depth': 6, 'learning_rate': 0.01189827962496544, 'n_estimators': 728, 'subsample': 0.7008547078694167, 'colsample_bytree': 0.6586169003607563, 'min_child_weight': 2, 'gamma': 0.5747831213287888, 'reg_alpha': 1.5308582157144417, 'reg_lambda': 1.4400331953935388e-05, 'max_delta_step': 8}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  90%|█████████ | 45/50 [09:59<01:29, 17.82s/it]

[I 2025-12-01 20:54:29,049] Trial 44 finished with value: 0.48289473684210527 and parameters: {'max_depth': 5, 'learning_rate': 0.015847175839815264, 'n_estimators': 565, 'subsample': 0.9254974627591043, 'colsample_bytree': 0.5257198304930916, 'min_child_weight': 7, 'gamma': 1.748552854068394, 'reg_alpha': 0.044128727996710845, 'reg_lambda': 0.00290210281310117, 'max_delta_step': 5}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  92%|█████████▏| 46/50 [10:04<00:56, 14.08s/it]

[I 2025-12-01 20:54:34,409] Trial 45 finished with value: 0.48289473684210527 and parameters: {'max_depth': 8, 'learning_rate': 0.016620676994414506, 'n_estimators': 571, 'subsample': 0.9210045874909454, 'colsample_bytree': 0.5290003755063594, 'min_child_weight': 7, 'gamma': 0.3220551309748939, 'reg_alpha': 0.019342651085606385, 'reg_lambda': 3.1944537246801915e-06, 'max_delta_step': 5}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  94%|█████████▍| 47/50 [10:21<00:45, 15.05s/it]

[I 2025-12-01 20:54:51,713] Trial 46 finished with value: 0.48289473684210527 and parameters: {'max_depth': 8, 'learning_rate': 0.016552416626004495, 'n_estimators': 792, 'subsample': 0.9173708614273721, 'colsample_bytree': 0.5203335729977363, 'min_child_weight': 7, 'gamma': 1.1668763435016332, 'reg_alpha': 0.0200134141587803, 'reg_lambda': 2.901746947291484e-06, 'max_delta_step': 5}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  96%|█████████▌| 48/50 [10:29<00:25, 12.87s/it]

[I 2025-12-01 20:54:59,511] Trial 47 finished with value: 0.4565789473684211 and parameters: {'max_depth': 8, 'learning_rate': 0.01627709379392135, 'n_estimators': 549, 'subsample': 0.940612797059768, 'colsample_bytree': 0.7793142175458683, 'min_child_weight': 7, 'gamma': 1.227479531750313, 'reg_alpha': 0.046785432520883775, 'reg_lambda': 2.452861971292205e-06, 'max_delta_step': 5}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 0. Best value: 0.495395:  98%|█████████▊| 49/50 [10:52<00:15, 15.87s/it]

[I 2025-12-01 20:55:22,388] Trial 49 finished with value: 0.4677631578947368 and parameters: {'max_depth': 9, 'learning_rate': 0.03365487182793014, 'n_estimators': 786, 'subsample': 0.7422162082622165, 'colsample_bytree': 0.7892495722804789, 'min_child_weight': 5, 'gamma': 1.1376800407772865, 'reg_alpha': 0.008551464181693086, 'reg_lambda': 2.421645621699321e-05, 'max_delta_step': 1}. Best is trial 0 with value: 0.4953947368421053.

Best trial: 48. Best value: 0.546711: 100%|██████████| 50/50 [10:59<00:00, 13.19s/it]

[I 2025-12-01 20:55:29,409] Trial 48 finished with value: 0.5467105263157894 and parameters: {'max_depth': 8, 'learning_rate': 0.04667497857362228, 'n_estimators': 1374, 'subsample': 0.7396627300141392, 'colsample_bytree': 0.7330470350703284, 'min_child_weight': 7, 'gamma': 1.2003576213431066, 'reg_alpha': 0.008173623039197313, 'reg_lambda': 3.1031343556540126e-06, 'max_delta_step': 1}. Best is trial 48 with value: 0.5467105263157894.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 20:55:35,007] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.56611:   2%|▏         | 1/50 [00:43<35:26, 43.40s/it]

[I 2025-12-01 20:56:18,396] Trial 0 finished with value: 0.5661103979460848 and parameters: {'max_depth': 4, 'learning_rate': 0.019020817328880484, 'n_estimators': 408, 'subsample': 0.7672743536089437, 'colsample_bytree': 0.9977430841682642, 'min_child_weight': 6, 'gamma': 1.9359791608959032, 'reg_alpha': 1.154428132852521e-07, 'reg_lambda': 0.014832956969906793, 'max_delta_step': 5}. Best is trial 0 with value: 0.5661103979460848.

Best trial: 0. Best value: 0.56611:   4%|▍         | 2/50 [00:49<17:16, 21.59s/it]

[I 2025-12-01 20:56:24,719] Trial 3 finished with value: 0.5012836970474968 and parameters: {'max_depth': 9, 'learning_rate': 0.22022715086395453, 'n_estimators': 898, 'subsample': 0.9794648268229187, 'colsample_bytree': 0.7042270427217656, 'min_child_weight': 7, 'gamma': 1.5873759244524799, 'reg_alpha': 1.3361336446556613, 'reg_lambda': 0.0003415393729866962, 'max_delta_step': 6}. Best is trial 0 with value: 0.5661103979460848.

Best trial: 0. Best value: 0.56611:   6%|▌         | 3/50 [01:12<17:15, 22.04s/it]

[I 2025-12-01 20:56:47,290] Trial 1 finished with value: 0.503209242618742 and parameters: {'max_depth': 9, 'learning_rate': 0.09080075477245987, 'n_estimators': 1268, 'subsample': 0.8462870884388308, 'colsample_bytree': 0.8953258909712885, 'min_child_weight': 7, 'gamma': 3.509348230652874, 'reg_alpha': 0.00016899566382411383, 'reg_lambda': 2.6429806357618624, 'max_delta_step': 0}. Best is trial 0 with value: 0.5661103979460848.

Best trial: 0. Best value: 0.56611:   8%|▊         | 4/50 [01:12<10:25, 13.60s/it]

[I 2025-12-01 20:56:47,963] Trial 2 finished with value: 0.503209242618742 and parameters: {'max_depth': 9, 'learning_rate': 0.11284215937003535, 'n_estimators': 1448, 'subsample': 0.6176226092670736, 'colsample_bytree': 0.5463724953781051, 'min_child_weight': 6, 'gamma': 1.9612454609902814, 'reg_alpha': 0.011552253556717408, 'reg_lambda': 0.0007324160113996208, 'max_delta_step': 1}. Best is trial 0 with value: 0.5661103979460848.

Best trial: 4. Best value: 0.659178:  10%|█         | 5/50 [01:14<07:03,  9.41s/it]

[I 2025-12-01 20:56:49,946] Trial 4 finished with value: 0.6591784338896021 and parameters: {'max_depth': 5, 'learning_rate': 0.13363029188299722, 'n_estimators': 596, 'subsample': 0.8810578947106504, 'colsample_bytree': 0.7757939929029085, 'min_child_weight': 9, 'gamma': 2.823337027520597, 'reg_alpha': 1.2270230266673477e-05, 'reg_lambda': 0.24887818320010827, 'max_delta_step': 2}. Best is trial 4 with value: 0.6591784338896021.

Best trial: 4. Best value: 0.659178:  12%|█▏        | 6/50 [01:32<08:58, 12.23s/it]

[I 2025-12-01 20:57:07,651] Trial 5 finished with value: 0.5860077021822849 and parameters: {'max_depth': 6, 'learning_rate': 0.08528506877391182, 'n_estimators': 834, 'subsample': 0.5130692574969595, 'colsample_bytree': 0.7892640946105978, 'min_child_weight': 7, 'gamma': 2.519735109800141, 'reg_alpha': 3.204865352953901e-07, 'reg_lambda': 0.09813057559305037, 'max_delta_step': 0}. Best is trial 4 with value: 0.6591784338896021.

Best trial: 4. Best value: 0.659178:  14%|█▍        | 7/50 [01:50<10:10, 14.20s/it]

[I 2025-12-01 20:57:25,917] Trial 7 finished with value: 0.5885750962772786 and parameters: {'max_depth': 5, 'learning_rate': 0.05994490002295058, 'n_estimators': 301, 'subsample': 0.9547497425188163, 'colsample_bytree': 0.9586202831582012, 'min_child_weight': 3, 'gamma': 3.4924228667577886, 'reg_alpha': 1.4834585702800659e-08, 'reg_lambda': 1.1876935156714647e-05, 'max_delta_step': 2}. Best is trial 4 with value: 0.6591784338896021.

Best trial: 4. Best value: 0.659178:  16%|█▌        | 8/50 [02:11<11:16, 16.10s/it]

[I 2025-12-01 20:57:46,073] Trial 6 finished with value: 0.5577663671373556 and parameters: {'max_depth': 6, 'learning_rate': 0.06791307210529074, 'n_estimators': 1118, 'subsample': 0.5080378977998685, 'colsample_bytree': 0.8915303612809504, 'min_child_weight': 7, 'gamma': 1.7129638241123497, 'reg_alpha': 0.11116301544511221, 'reg_lambda': 5.4605531904700756e-08, 'max_delta_step': 10}. Best is trial 4 with value: 0.6591784338896021.

Best trial: 4. Best value: 0.659178:  18%|█▊        | 9/50 [02:19<09:21, 13.69s/it]

[I 2025-12-01 20:57:54,478] Trial 8 finished with value: 0.13157894736842105 and parameters: {'max_depth': 9, 'learning_rate': 0.029488396075460957, 'n_estimators': 1343, 'subsample': 0.6697859534079449, 'colsample_bytree': 0.5896735098680135, 'min_child_weight': 9, 'gamma': 2.712183878291036, 'reg_alpha': 0.03016756345914315, 'reg_lambda': 2.638380047325382e-07, 'max_delta_step': 5}. Best is trial 4 with value: 0.6591784338896021.

Best trial: 4. Best value: 0.659178:  20%|██        | 10/50 [02:50<12:41, 19.04s/it]

[I 2025-12-01 20:58:25,493] Trial 9 finished with value: 0.4974326059050064 and parameters: {'max_depth': 3, 'learning_rate': 0.01235532676181279, 'n_estimators': 458, 'subsample': 0.9381243207160309, 'colsample_bytree': 0.5292984972952988, 'min_child_weight': 2, 'gamma': 0.9126672263075397, 'reg_alpha': 1.17619515478467e-05, 'reg_lambda': 0.0007928885603600028, 'max_delta_step': 5}. Best is trial 4 with value: 0.6591784338896021.

Best trial: 4. Best value: 0.659178:  22%|██▏       | 11/50 [02:53<09:14, 14.21s/it]

[I 2025-12-01 20:58:28,761] Trial 12 pruned.

Best trial: 4. Best value: 0.659178:  24%|██▍       | 12/50 [02:56<06:52, 10.85s/it]

[I 2025-12-01 20:58:31,906] Trial 13 pruned.

Best trial: 4. Best value: 0.659178:  26%|██▌       | 13/50 [03:02<05:47,  9.39s/it]

[I 2025-12-01 20:58:37,961] Trial 15 pruned.

Best trial: 4. Best value: 0.659178:  28%|██▊       | 14/50 [03:07<04:40,  7.79s/it]

[I 2025-12-01 20:58:42,028] Trial 16 pruned.

Best trial: 4. Best value: 0.659178:  30%|███       | 15/50 [03:17<04:57,  8.49s/it]

[I 2025-12-01 20:58:52,150] Trial 14 finished with value: 0.5378690629011553 and parameters: {'max_depth': 5, 'learning_rate': 0.2034595634103036, 'n_estimators': 215, 'subsample': 0.8910711543718339, 'colsample_bytree': 0.9937988914679077, 'min_child_weight': 3, 'gamma': 3.8269911436635637, 'reg_alpha': 1.1974367035612213e-08, 'reg_lambda': 4.431539174317602e-06, 'max_delta_step': 3}. Best is trial 4 with value: 0.6591784338896021.

Best trial: 4. Best value: 0.659178:  32%|███▏      | 16/50 [03:22<04:19,  7.64s/it]

[I 2025-12-01 20:58:57,832] Trial 11 finished with value: 0.5417201540436457 and parameters: {'max_depth': 3, 'learning_rate': 0.015700331455173293, 'n_estimators': 1397, 'subsample': 0.5144034502058742, 'colsample_bytree': 0.5563565206980534, 'min_child_weight': 6, 'gamma': 1.028229619226226, 'reg_alpha': 2.8154565597567194e-07, 'reg_lambda': 0.0014815637533769621, 'max_delta_step': 10}. Best is trial 4 with value: 0.6591784338896021.

Best trial: 4. Best value: 0.659178:  34%|███▍      | 17/50 [03:45<06:42, 12.20s/it]

[I 2025-12-01 20:59:20,619] Trial 10 finished with value: 0.616816431322208 and parameters: {'max_depth': 5, 'learning_rate': 0.0414997270879472, 'n_estimators': 909, 'subsample': 0.9152379491255962, 'colsample_bytree': 0.8979325603876112, 'min_child_weight': 1, 'gamma': 1.2592155746701157, 'reg_alpha': 6.2303375024058925, 'reg_lambda': 0.0003206687935822054, 'max_delta_step': 5}. Best is trial 4 with value: 0.6591784338896021.

Best trial: 4. Best value: 0.659178:  36%|███▌      | 18/50 [04:02<07:18, 13.71s/it]

[I 2025-12-01 20:59:37,838] Trial 20 pruned.

Best trial: 4. Best value: 0.659178:  38%|███▊      | 19/50 [04:13<06:40, 12.91s/it]

[I 2025-12-01 20:59:48,900] Trial 17 finished with value: 0.5885750962772786 and parameters: {'max_depth': 5, 'learning_rate': 0.04648445195752675, 'n_estimators': 654, 'subsample': 0.9844331628359291, 'colsample_bytree': 0.6227269646923641, 'min_child_weight': 1, 'gamma': 4.09094260639138, 'reg_alpha': 1.4560226419585103e-08, 'reg_lambda': 1.2122897487770472e-05, 'max_delta_step': 2}. Best is trial 4 with value: 0.6591784338896021.

Best trial: 4. Best value: 0.659178:  40%|████      | 20/50 [04:19<05:24, 10.83s/it]

[I 2025-12-01 20:59:54,880] Trial 22 pruned.

Best trial: 4. Best value: 0.659178:  42%|████▏     | 21/50 [04:28<04:53, 10.11s/it]

[I 2025-12-01 21:00:03,296] Trial 19 finished with value: 0.5905006418485237 and parameters: {'max_depth': 7, 'learning_rate': 0.05133111531412376, 'n_estimators': 622, 'subsample': 0.9755122218307438, 'colsample_bytree': 0.6275951581778698, 'min_child_weight': 1, 'gamma': 3.040810162502413, 'reg_alpha': 0.00016924189236312625, 'reg_lambda': 0.12936830392173826, 'max_delta_step': 8}. Best is trial 4 with value: 0.6591784338896021.

Best trial: 4. Best value: 0.659178:  44%|████▍     | 22/50 [04:33<03:58,  8.53s/it]

[I 2025-12-01 21:00:08,139] Trial 18 finished with value: 0.5622593068035944 and parameters: {'max_depth': 3, 'learning_rate': 0.04725021877983888, 'n_estimators': 628, 'subsample': 0.9914886707576706, 'colsample_bytree': 0.8329125268042317, 'min_child_weight': 1, 'gamma': 2.897780263802556, 'reg_alpha': 6.801738341830627e-07, 'reg_lambda': 0.13112874022744211, 'max_delta_step': 7}. Best is trial 4 with value: 0.6591784338896021.

Best trial: 4. Best value: 0.659178:  46%|████▌     | 23/50 [04:35<02:59,  6.64s/it]

[I 2025-12-01 21:00:10,375] Trial 23 pruned.

Best trial: 4. Best value: 0.659178:  48%|████▊     | 24/50 [04:36<02:06,  4.87s/it]

[I 2025-12-01 21:00:11,122] Trial 21 finished with value: 0.6469833119383825 and parameters: {'max_depth': 4, 'learning_rate': 0.13155063714815352, 'n_estimators': 626, 'subsample': 0.9986149711041015, 'colsample_bytree': 0.6453661575658386, 'min_child_weight': 9, 'gamma': 0.5520836487910774, 'reg_alpha': 1.0462935768816528, 'reg_lambda': 0.07983474799319691, 'max_delta_step': 7}. Best is trial 4 with value: 0.6591784338896021.

Best trial: 4. Best value: 0.659178:  50%|█████     | 25/50 [04:38<01:39,  4.00s/it]

[I 2025-12-01 21:00:13,077] Trial 24 pruned.

Best trial: 4. Best value: 0.659178:  52%|█████▏    | 26/50 [04:45<02:02,  5.11s/it]

[I 2025-12-01 21:00:20,776] Trial 25 pruned.

Best trial: 4. Best value: 0.659178:  54%|█████▍    | 27/50 [04:48<01:40,  4.35s/it]

[I 2025-12-01 21:00:23,363] Trial 26 pruned.

Best trial: 27. Best value: 0.671374:  56%|█████▌    | 28/50 [05:18<04:25, 12.09s/it]

[I 2025-12-01 21:00:53,483] Trial 27 finished with value: 0.6713735558408216 and parameters: {'max_depth': 4, 'learning_rate': 0.15024651729317953, 'n_estimators': 832, 'subsample': 0.8984547632253718, 'colsample_bytree': 0.7444361157998555, 'min_child_weight': 9, 'gamma': 0.7154663087690634, 'reg_alpha': 0.6456287654685885, 'reg_lambda': 1.1156224520992306, 'max_delta_step': 4}. Best is trial 27 with value: 0.6713735558408216.

Best trial: 27. Best value: 0.671374:  58%|█████▊    | 29/50 [05:21<03:15,  9.29s/it]

[I 2025-12-01 21:00:56,256] Trial 28 finished with value: 0.6591784338896021 and parameters: {'max_depth': 4, 'learning_rate': 0.15941879023041566, 'n_estimators': 836, 'subsample': 0.8948294260977546, 'colsample_bytree': 0.7226405749824883, 'min_child_weight': 9, 'gamma': 0.646794172013664, 'reg_alpha': 0.5560389958408983, 'reg_lambda': 0.9930849017340492, 'max_delta_step': 4}. Best is trial 27 with value: 0.6713735558408216.

Best trial: 27. Best value: 0.671374:  62%|██████▏   | 31/50 [05:25<01:43,  5.43s/it]

[I 2025-12-01 21:01:00,263] Trial 32 pruned.
[I 2025-12-01 21:01:00,384] Trial 29 finished with value: 0.6065468549422337 and parameters: {'max_depth': 4, 'learning_rate': 0.15587482800285452, 'n_estimators': 779, 'subsample': 0.9163791567348282, 'colsample_bytree': 0.7513662304997608, 'min_child_weight': 9, 'gamma': 0.709036756067576, 'reg_alpha': 0.4414935666660466, 'reg_lambda': 0.9476022572105423, 'max_delta_step': 4}. Best is trial 27 with value: 0.6713735558408216.

Best trial: 27. Best value: 0.671374:  64%|██████▍   | 32/50 [05:36<02:08,  7.14s/it]

[I 2025-12-01 21:01:11,512] Trial 30 finished with value: 0.6187419768934532 and parameters: {'max_depth': 4, 'learning_rate': 0.150535642888246, 'n_estimators': 964, 'subsample': 0.9316550419836093, 'colsample_bytree': 0.7356957926348021, 'min_child_weight': 9, 'gamma': 0.6580399709099523, 'reg_alpha': 0.45763635489847354, 'reg_lambda': 0.5876880923738947, 'max_delta_step': 6}. Best is trial 27 with value: 0.6713735558408216.

Best trial: 27. Best value: 0.671374:  66%|██████▌   | 33/50 [05:44<02:07,  7.48s/it]

[I 2025-12-01 21:01:19,775] Trial 31 finished with value: 0.6591784338896021 and parameters: {'max_depth': 4, 'learning_rate': 0.15580197441636018, 'n_estimators': 470, 'subsample': 0.8171064205797289, 'colsample_bytree': 0.7348809901893855, 'min_child_weight': 9, 'gamma': 0.455012581018362, 'reg_alpha': 0.42568280003476, 'reg_lambda': 1.3606030788985226, 'max_delta_step': 4}. Best is trial 27 with value: 0.6713735558408216.

Best trial: 27. Best value: 0.671374:  68%|██████▊   | 34/50 [06:06<03:07, 11.69s/it]

[I 2025-12-01 21:01:41,312] Trial 35 finished with value: 0.6206675224646983 and parameters: {'max_depth': 3, 'learning_rate': 0.09302786753399137, 'n_estimators': 515, 'subsample': 0.8144849254339799, 'colsample_bytree': 0.6740117511077415, 'min_child_weight': 8, 'gamma': 0.3288067096627689, 'reg_alpha': 1.622240425842362, 'reg_lambda': 9.38144297334589, 'max_delta_step': 6}. Best is trial 27 with value: 0.6713735558408216.

Best trial: 27. Best value: 0.671374:  70%|███████   | 35/50 [06:13<02:36, 10.40s/it]

[I 2025-12-01 21:01:48,712] Trial 36 finished with value: 0.6450577663671373 and parameters: {'max_depth': 3, 'learning_rate': 0.09460999449549103, 'n_estimators': 513, 'subsample': 0.8121305367009839, 'colsample_bytree': 0.7996429782936736, 'min_child_weight': 8, 'gamma': 1.324446482039665, 'reg_alpha': 0.059611829140404485, 'reg_lambda': 5.8210542147508635, 'max_delta_step': 2}. Best is trial 27 with value: 0.6713735558408216.

Best trial: 27. Best value: 0.671374:  72%|███████▏  | 36/50 [06:15<01:48,  7.78s/it]

[I 2025-12-01 21:01:50,362] Trial 33 finished with value: 0.6065468549422337 and parameters: {'max_depth': 3, 'learning_rate': 0.17188461443749636, 'n_estimators': 991, 'subsample': 0.8141180579221818, 'colsample_bytree': 0.746992662165056, 'min_child_weight': 8, 'gamma': 2.315207686394428, 'reg_alpha': 0.0025180970378563174, 'reg_lambda': 1.0023413637716774, 'max_delta_step': 4}. Best is trial 27 with value: 0.6713735558408216.

Best trial: 27. Best value: 0.671374:  74%|███████▍  | 37/50 [06:18<01:21,  6.29s/it]

[I 2025-12-01 21:01:53,173] Trial 34 finished with value: 0.6591784338896021 and parameters: {'max_depth': 3, 'learning_rate': 0.1601934133872887, 'n_estimators': 1014, 'subsample': 0.8152449880272001, 'colsample_bytree': 0.6740729713944642, 'min_child_weight': 8, 'gamma': 0.41214023981750286, 'reg_alpha': 1.4268707371445535, 'reg_lambda': 6.668368523570187, 'max_delta_step': 6}. Best is trial 27 with value: 0.6713735558408216.

Best trial: 27. Best value: 0.671374:  76%|███████▌  | 38/50 [06:19<00:56,  4.70s/it]

[I 2025-12-01 21:01:54,156] Trial 39 pruned.

Best trial: 27. Best value: 0.671374:  78%|███████▊  | 39/50 [06:22<00:46,  4.24s/it]

[I 2025-12-01 21:01:57,325] Trial 40 pruned.

Best trial: 27. Best value: 0.671374:  80%|████████  | 40/50 [06:23<00:31,  3.19s/it]

[I 2025-12-01 21:01:58,057] Trial 38 pruned.

Best trial: 27. Best value: 0.671374:  82%|████████▏ | 41/50 [06:29<00:36,  4.08s/it]

[I 2025-12-01 21:02:04,222] Trial 37 finished with value: 0.527599486521181 and parameters: {'max_depth': 5, 'learning_rate': 0.20060303228608678, 'n_estimators': 368, 'subsample': 0.8641561470550991, 'colsample_bytree': 0.7227259186420352, 'min_child_weight': 8, 'gamma': 1.4237500426317529, 'reg_alpha': 0.03093688776402278, 'reg_lambda': 2.44718485083733, 'max_delta_step': 2}. Best is trial 27 with value: 0.6713735558408216.

Best trial: 27. Best value: 0.671374:  84%|████████▍ | 42/50 [06:32<00:30,  3.86s/it]

[I 2025-12-01 21:02:07,551] Trial 42 pruned.

Best trial: 27. Best value: 0.671374:  86%|████████▌ | 43/50 [06:34<00:23,  3.30s/it]

[I 2025-12-01 21:02:09,546] Trial 43 pruned.

Best trial: 27. Best value: 0.671374:  88%|████████▊ | 44/50 [06:37<00:18,  3.10s/it]

[I 2025-12-01 21:02:12,179] Trial 44 pruned.

Best trial: 27. Best value: 0.671374:  90%|█████████ | 45/50 [06:43<00:19,  3.98s/it]

[I 2025-12-01 21:02:18,220] Trial 41 finished with value: 0.5417201540436457 and parameters: {'max_depth': 5, 'learning_rate': 0.07652311433009741, 'n_estimators': 354, 'subsample': 0.7238273887437577, 'colsample_bytree': 0.8012880770493618, 'min_child_weight': 7, 'gamma': 1.388144642534019, 'reg_alpha': 0.13214538483327593, 'reg_lambda': 0.0062462971953919115, 'max_delta_step': 0}. Best is trial 27 with value: 0.6713735558408216.

Best trial: 27. Best value: 0.671374:  92%|█████████▏| 46/50 [06:47<00:15,  3.94s/it]

[I 2025-12-01 21:02:22,073] Trial 47 pruned.

Best trial: 27. Best value: 0.671374:  94%|█████████▍| 47/50 [06:53<00:13,  4.62s/it]

[I 2025-12-01 21:02:28,282] Trial 48 pruned.

Best trial: 27. Best value: 0.671374:  96%|█████████▌| 48/50 [07:13<00:18,  9.25s/it]

[I 2025-12-01 21:02:48,325] Trial 46 finished with value: 0.6206675224646983 and parameters: {'max_depth': 3, 'learning_rate': 0.10369770211660333, 'n_estimators': 831, 'subsample': 0.8325488224707287, 'colsample_bytree': 0.6863929513340536, 'min_child_weight': 9, 'gamma': 0.2843392899880926, 'reg_alpha': 2.606487860700248, 'reg_lambda': 0.39004360205952165, 'max_delta_step': 5}. Best is trial 27 with value: 0.6713735558408216.

Best trial: 27. Best value: 0.671374:  98%|█████████▊| 49/50 [07:24<00:09,  9.90s/it]

[I 2025-12-01 21:02:59,753] Trial 45 finished with value: 0.5699614890885751 and parameters: {'max_depth': 3, 'learning_rate': 0.10850013336133343, 'n_estimators': 1224, 'subsample': 0.7744990770673879, 'colsample_bytree': 0.6662976086950237, 'min_child_weight': 9, 'gamma': 0.9679386240214709, 'reg_alpha': 2.4554428884509556, 'reg_lambda': 0.4102154187191235, 'max_delta_step': 5}. Best is trial 27 with value: 0.6713735558408216.

Best trial: 27. Best value: 0.671374: 100%|██████████| 50/50 [07:25<00:00,  8.92s/it]

[I 2025-12-01 21:03:00,978] Trial 49 finished with value: 0.5558408215661104 and parameters: {'max_depth': 3, 'learning_rate': 0.24663410238943392, 'n_estimators': 941, 'subsample': 0.816944264972676, 'colsample_bytree': 0.6956576037882538, 'min_child_weight': 8, 'gamma': 0.289191933865177, 'reg_alpha': 0.8047148875809021, 'reg_lambda': 0.0517490911621258, 'max_delta_step': 5}. Best is trial 27 with value: 0.6713735558408216.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.551990                    0.70          0.82
1     9_1         loo       0.636842                    0.65          0.70
2    17_1         loo       0.671374                    0.55          0.52
3    19_1         loo       0.546711                    0.50          0.64

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.377964               0.8               0.6        50          60
1  0.288675               0.6               0.7        50          59
2  0.106600               0.8               0.3        50          60
3  0.000000               0.4               0.6        50          59

   test_size
0         15
1         15
2         15
3         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.551990                    0.70          0.82
1     9_1         loo       0.636842                    0.65          0.70
2    17_1         loo       0.671374                    0.55          0.52
3    19_1         loo       0.546711                    0.50          0.64

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.377964               0.8               0.6        50          60
1  0.288675               0.6               0.7        50          59
2  0.106600               0.8               0.3        50          60
3  0.000000               0.4               0.6        50          59

   test_size
0         15
1         15
2         15
3         15

In [1569]:

datasets = task_hf_compensated_temp_emb_lbl_ad_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir="xgb_ad_hc_{CV_STRATEGY}_tasks/xgb_results_handcrafted_temp_emb_compensated_ad_hc_extended_{CV_STRATEGY}_tasks",
    split_param= "diagnosis_y",
)
print(summary)

[I 2025-12-01 21:03:04,557] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.456579:   2%|▏         | 1/50 [00:23<19:30, 23.89s/it]

[I 2025-12-01 21:03:28,440] Trial 3 finished with value: 0.4565789473684211 and parameters: {'max_depth': 7, 'learning_rate': 0.04708601911553175, 'n_estimators': 342, 'subsample': 0.5834094048262242, 'colsample_bytree': 0.9868139490922815, 'min_child_weight': 4, 'gamma': 3.5488805391878446, 'reg_alpha': 1.5302015041171753, 'reg_lambda': 2.4755392581145088e-08, 'max_delta_step': 5}. Best is trial 3 with value: 0.4565789473684211.

Best trial: 1. Best value: 0.509211:   4%|▍         | 2/50 [00:36<13:57, 17.45s/it]

[I 2025-12-01 21:03:41,389] Trial 1 finished with value: 0.5092105263157894 and parameters: {'max_depth': 10, 'learning_rate': 0.12445434350363759, 'n_estimators': 822, 'subsample': 0.9168873806620625, 'colsample_bytree': 0.8542952230513602, 'min_child_weight': 7, 'gamma': 4.821842327593778, 'reg_alpha': 2.472245482836575e-07, 'reg_lambda': 8.516108457751439e-05, 'max_delta_step': 1}. Best is trial 1 with value: 0.5092105263157894.

Best trial: 4. Best value: 0.523026:   6%|▌         | 3/50 [00:42<09:35, 12.24s/it]

[I 2025-12-01 21:03:47,421] Trial 4 finished with value: 0.5230263157894737 and parameters: {'max_depth': 8, 'learning_rate': 0.15951651978099346, 'n_estimators': 435, 'subsample': 0.6926667545946462, 'colsample_bytree': 0.5096289699707086, 'min_child_weight': 7, 'gamma': 4.576132771835474, 'reg_alpha': 3.9839513780300355e-08, 'reg_lambda': 0.0013040816256236105, 'max_delta_step': 10}. Best is trial 4 with value: 0.5230263157894737.

Best trial: 4. Best value: 0.523026:   8%|▊         | 4/50 [00:50<08:07, 10.60s/it]

[I 2025-12-01 21:03:55,515] Trial 0 finished with value: 0.49407894736842106 and parameters: {'max_depth': 10, 'learning_rate': 0.0740425324227306, 'n_estimators': 968, 'subsample': 0.670912458222019, 'colsample_bytree': 0.662866413904106, 'min_child_weight': 2, 'gamma': 0.8078401344848818, 'reg_alpha': 3.0337975689179363e-07, 'reg_lambda': 2.092188624858915, 'max_delta_step': 6}. Best is trial 4 with value: 0.5230263157894737.

Best trial: 4. Best value: 0.523026:  10%|█         | 5/50 [00:55<06:25,  8.56s/it]

[I 2025-12-01 21:04:00,441] Trial 2 finished with value: 0.5203947368421052 and parameters: {'max_depth': 6, 'learning_rate': 0.04924410219044801, 'n_estimators': 1085, 'subsample': 0.7049809656707974, 'colsample_bytree': 0.8786953717552877, 'min_child_weight': 3, 'gamma': 2.455002790682114, 'reg_alpha': 0.12147458672150203, 'reg_lambda': 0.0044042601265434555, 'max_delta_step': 7}. Best is trial 4 with value: 0.5230263157894737.

Best trial: 4. Best value: 0.523026:  12%|█▏        | 6/50 [01:00<05:12,  7.11s/it]

[I 2025-12-01 21:04:04,759] Trial 5 finished with value: 0.49407894736842106 and parameters: {'max_depth': 3, 'learning_rate': 0.07904661778748434, 'n_estimators': 421, 'subsample': 0.8815529229362892, 'colsample_bytree': 0.6906624339264069, 'min_child_weight': 4, 'gamma': 1.9714222333552622, 'reg_alpha': 6.683798124074527e-05, 'reg_lambda': 0.0001311358600893935, 'max_delta_step': 9}. Best is trial 4 with value: 0.5230263157894737.

Best trial: 7. Best value: 0.704605:  14%|█▍        | 7/50 [01:12<06:11,  8.65s/it]

[I 2025-12-01 21:04:16,562] Trial 7 finished with value: 0.7046052631578947 and parameters: {'max_depth': 3, 'learning_rate': 0.0207676124713793, 'n_estimators': 438, 'subsample': 0.9286356386288339, 'colsample_bytree': 0.8007381882276804, 'min_child_weight': 9, 'gamma': 2.0718180416583305, 'reg_alpha': 6.757586717261732e-08, 'reg_lambda': 7.4880094879057e-08, 'max_delta_step': 3}. Best is trial 7 with value: 0.7046052631578947.

Best trial: 7. Best value: 0.704605:  16%|█▌        | 8/50 [01:24<07:00, 10.02s/it]

[I 2025-12-01 21:04:29,528] Trial 9 finished with value: 0.5993421052631579 and parameters: {'max_depth': 4, 'learning_rate': 0.23246228400277866, 'n_estimators': 440, 'subsample': 0.8698808563744229, 'colsample_bytree': 0.801567938914519, 'min_child_weight': 3, 'gamma': 4.3419658192431285, 'reg_alpha': 7.07823228198551, 'reg_lambda': 1.269220690399658e-05, 'max_delta_step': 6}. Best is trial 7 with value: 0.7046052631578947.

Best trial: 7. Best value: 0.704605:  18%|█▊        | 9/50 [01:32<06:19,  9.25s/it]

[I 2025-12-01 21:04:37,083] Trial 8 finished with value: 0.7032894736842106 and parameters: {'max_depth': 6, 'learning_rate': 0.017713671085875352, 'n_estimators': 840, 'subsample': 0.9151998632697056, 'colsample_bytree': 0.9382005391248701, 'min_child_weight': 9, 'gamma': 3.241815908436196, 'reg_alpha': 0.009164033016943789, 'reg_lambda': 0.01161376487264254, 'max_delta_step': 2}. Best is trial 7 with value: 0.7046052631578947.

Best trial: 7. Best value: 0.704605:  20%|██        | 10/50 [01:32<04:20,  6.52s/it]

[I 2025-12-01 21:04:37,474] Trial 6 finished with value: 0.41776315789473684 and parameters: {'max_depth': 10, 'learning_rate': 0.16914664675489863, 'n_estimators': 982, 'subsample': 0.7750953645265551, 'colsample_bytree': 0.9184182892225208, 'min_child_weight': 3, 'gamma': 4.000830984709473, 'reg_alpha': 0.018918450834170226, 'reg_lambda': 1.9842607374177204e-07, 'max_delta_step': 2}. Best is trial 7 with value: 0.7046052631578947.

Best trial: 7. Best value: 0.704605:  22%|██▏       | 11/50 [01:34<03:15,  5.02s/it]

[I 2025-12-01 21:04:39,108] Trial 10 pruned.

Best trial: 7. Best value: 0.704605:  24%|██▍       | 12/50 [01:40<03:19,  5.24s/it]

[I 2025-12-01 21:04:44,839] Trial 12 pruned.

Best trial: 7. Best value: 0.704605:  26%|██▌       | 13/50 [01:40<02:19,  3.77s/it]

[I 2025-12-01 21:04:45,222] Trial 11 pruned.

Best trial: 7. Best value: 0.704605:  28%|██▊       | 14/50 [01:43<02:04,  3.45s/it]

[I 2025-12-01 21:04:47,941] Trial 13 pruned.

Best trial: 7. Best value: 0.704605:  30%|███       | 15/50 [01:45<01:43,  2.97s/it]

[I 2025-12-01 21:04:49,796] Trial 17 pruned.

Best trial: 7. Best value: 0.704605:  32%|███▏      | 16/50 [01:52<02:22,  4.18s/it]

[I 2025-12-01 21:04:56,791] Trial 16 pruned.

Best trial: 7. Best value: 0.704605:  34%|███▍      | 17/50 [01:52<01:39,  3.03s/it]

[I 2025-12-01 21:04:57,128] Trial 15 pruned.

Best trial: 7. Best value: 0.704605:  36%|███▌      | 18/50 [01:57<01:51,  3.48s/it]

[I 2025-12-01 21:05:01,664] Trial 18 pruned.

Best trial: 7. Best value: 0.704605:  38%|███▊      | 19/50 [02:03<02:18,  4.47s/it]

[I 2025-12-01 21:05:08,452] Trial 21 pruned.

Best trial: 7. Best value: 0.704605:  40%|████      | 20/50 [02:26<04:59,  9.99s/it]

[I 2025-12-01 21:05:31,306] Trial 19 finished with value: 0.5993421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.030714416617352823, 'n_estimators': 713, 'subsample': 0.8006174684156038, 'colsample_bytree': 0.9434226418934571, 'min_child_weight': 8, 'gamma': 2.368012628229032, 'reg_alpha': 0.002491721085764145, 'reg_lambda': 0.022041709541168707, 'max_delta_step': 3}. Best is trial 7 with value: 0.7046052631578947.

Best trial: 7. Best value: 0.704605:  42%|████▏     | 21/50 [02:27<03:28,  7.18s/it]

[I 2025-12-01 21:05:31,915] Trial 20 finished with value: 0.6118421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.01531732542886396, 'n_estimators': 708, 'subsample': 0.7976484469263879, 'colsample_bytree': 0.7986000793451642, 'min_child_weight': 8, 'gamma': 2.3116876324718985, 'reg_alpha': 0.0021726111013299658, 'reg_lambda': 1.943423718160019e-08, 'max_delta_step': 2}. Best is trial 7 with value: 0.7046052631578947.

Best trial: 7. Best value: 0.704605:  44%|████▍     | 22/50 [02:42<04:25,  9.47s/it]

[I 2025-12-01 21:05:46,726] Trial 14 finished with value: 0.7032894736842106 and parameters: {'max_depth': 5, 'learning_rate': 0.010369199461760787, 'n_estimators': 1488, 'subsample': 0.9951551939973033, 'colsample_bytree': 0.755346223771296, 'min_child_weight': 9, 'gamma': 3.1425306338941725, 'reg_alpha': 1.4537074680044107e-05, 'reg_lambda': 0.24712060554574125, 'max_delta_step': 3}. Best is trial 7 with value: 0.7046052631578947.

Best trial: 7. Best value: 0.704605:  46%|████▌     | 23/50 [03:00<05:29, 12.22s/it]

[I 2025-12-01 21:06:05,355] Trial 24 finished with value: 0.638157894736842 and parameters: {'max_depth': 4, 'learning_rate': 0.01512545405648499, 'n_estimators': 621, 'subsample': 0.8460273295425595, 'colsample_bytree': 0.8215807262734945, 'min_child_weight': 8, 'gamma': 1.68548890315436, 'reg_alpha': 0.03686857803176545, 'reg_lambda': 9.708300427823645e-08, 'max_delta_step': 1}. Best is trial 7 with value: 0.7046052631578947.

Best trial: 7. Best value: 0.704605:  48%|████▊     | 24/50 [03:07<04:37, 10.66s/it]

[I 2025-12-01 21:06:12,377] Trial 22 finished with value: 0.638157894736842 and parameters: {'max_depth': 6, 'learning_rate': 0.013817515253505719, 'n_estimators': 1301, 'subsample': 0.8229913621950485, 'colsample_bytree': 0.9370328575697728, 'min_child_weight': 8, 'gamma': 1.843780563597868, 'reg_alpha': 1.454327165089472e-06, 'reg_lambda': 0.4407408869704629, 'max_delta_step': 1}. Best is trial 7 with value: 0.7046052631578947.

Best trial: 7. Best value: 0.704605:  50%|█████     | 25/50 [03:30<05:53, 14.14s/it]

[I 2025-12-01 21:06:34,650] Trial 23 finished with value: 0.6118421052631579 and parameters: {'max_depth': 6, 'learning_rate': 0.016555327766839545, 'n_estimators': 1289, 'subsample': 0.8465646236052417, 'colsample_bytree': 0.8258017272282355, 'min_child_weight': 8, 'gamma': 1.655841402509452, 'reg_alpha': 9.639375377725668e-07, 'reg_lambda': 1.72858910641179e-05, 'max_delta_step': 1}. Best is trial 7 with value: 0.7046052631578947.

Best trial: 28. Best value: 0.755921:  52%|█████▏    | 26/50 [03:43<05:32, 13.84s/it]

[I 2025-12-01 21:06:47,769] Trial 28 finished with value: 0.7559210526315789 and parameters: {'max_depth': 5, 'learning_rate': 0.010123088634411819, 'n_estimators': 200, 'subsample': 0.946766463088734, 'colsample_bytree': 0.7411647068093845, 'min_child_weight': 9, 'gamma': 3.6513486610212733, 'reg_alpha': 0.00039659206559193995, 'reg_lambda': 0.0008539143342249704, 'max_delta_step': 4}. Best is trial 28 with value: 0.7559210526315789.

Best trial: 28. Best value: 0.755921:  54%|█████▍    | 27/50 [03:45<03:55, 10.23s/it]

[I 2025-12-01 21:06:49,585] Trial 25 finished with value: 0.6519736842105264 and parameters: {'max_depth': 6, 'learning_rate': 0.010315416778907864, 'n_estimators': 1339, 'subsample': 0.9345815145002206, 'colsample_bytree': 0.6325445687364492, 'min_child_weight': 9, 'gamma': 1.6700925071797432, 'reg_alpha': 7.000692971441027e-07, 'reg_lambda': 0.27028999494110534, 'max_delta_step': 4}. Best is trial 28 with value: 0.7559210526315789.

Best trial: 28. Best value: 0.755921:  56%|█████▌    | 28/50 [03:48<03:02,  8.28s/it]

[I 2025-12-01 21:06:53,320] Trial 30 pruned.

Best trial: 28. Best value: 0.755921:  58%|█████▊    | 29/50 [03:49<02:04,  5.92s/it]

[I 2025-12-01 21:06:53,726] Trial 29 pruned.

Best trial: 28. Best value: 0.755921:  60%|██████    | 30/50 [03:54<01:51,  5.59s/it]

[I 2025-12-01 21:06:58,567] Trial 31 pruned.

Best trial: 28. Best value: 0.755921:  62%|██████▏   | 31/50 [04:03<02:09,  6.79s/it]

[I 2025-12-01 21:07:08,158] Trial 26 finished with value: 0.6519736842105264 and parameters: {'max_depth': 6, 'learning_rate': 0.010009991747140628, 'n_estimators': 1372, 'subsample': 0.9376775190506446, 'colsample_bytree': 0.6259545939268646, 'min_child_weight': 9, 'gamma': 3.576990576990208, 'reg_alpha': 2.0009249814732514e-06, 'reg_lambda': 0.3447556910223619, 'max_delta_step': 4}. Best is trial 28 with value: 0.7559210526315789.

Best trial: 28. Best value: 0.755921:  64%|██████▍   | 32/50 [04:09<01:57,  6.51s/it]

[I 2025-12-01 21:07:14,007] Trial 27 finished with value: 0.6782894736842104 and parameters: {'max_depth': 6, 'learning_rate': 0.011164679084487074, 'n_estimators': 1314, 'subsample': 0.9388636707635832, 'colsample_bytree': 0.7428895814669505, 'min_child_weight': 9, 'gamma': 2.6519236301433122, 'reg_alpha': 3.1630749741445812e-06, 'reg_lambda': 0.37176792413375026, 'max_delta_step': 4}. Best is trial 28 with value: 0.7559210526315789.

Best trial: 28. Best value: 0.755921:  66%|██████▌   | 33/50 [04:10<01:24,  4.96s/it]

[I 2025-12-01 21:07:15,347] Trial 33 finished with value: 0.6907894736842105 and parameters: {'max_depth': 8, 'learning_rate': 0.07099263713324552, 'n_estimators': 327, 'subsample': 0.9619944970144697, 'colsample_bytree': 0.7376826566900327, 'min_child_weight': 9, 'gamma': 4.156538793639875, 'reg_alpha': 0.014386802036890257, 'reg_lambda': 2.6448947476733398e-05, 'max_delta_step': 6}. Best is trial 28 with value: 0.7559210526315789.

Best trial: 28. Best value: 0.755921:  68%|██████▊   | 34/50 [04:18<01:33,  5.86s/it]

[I 2025-12-01 21:07:23,326] Trial 36 pruned.

Best trial: 28. Best value: 0.755921:  70%|███████   | 35/50 [04:37<02:24,  9.66s/it]

[I 2025-12-01 21:07:41,837] Trial 32 finished with value: 0.638157894736842 and parameters: {'max_depth': 7, 'learning_rate': 0.020127192570747795, 'n_estimators': 881, 'subsample': 0.9073977211689063, 'colsample_bytree': 0.7389239267149043, 'min_child_weight': 7, 'gamma': 3.4283501314770795, 'reg_alpha': 0.014119105597619044, 'reg_lambda': 9.397489506209123, 'max_delta_step': 7}. Best is trial 28 with value: 0.7559210526315789.

Best trial: 28. Best value: 0.755921:  72%|███████▏  | 36/50 [04:45<02:09,  9.24s/it]

[I 2025-12-01 21:07:50,100] Trial 34 finished with value: 0.6644736842105263 and parameters: {'max_depth': 5, 'learning_rate': 0.013570538386303673, 'n_estimators': 895, 'subsample': 0.9666840912534866, 'colsample_bytree': 0.74988230074462, 'min_child_weight': 9, 'gamma': 2.7508053728328963, 'reg_alpha': 1.4217819411035265e-07, 'reg_lambda': 0.00036955578535599875, 'max_delta_step': 3}. Best is trial 28 with value: 0.7559210526315789.

Best trial: 28. Best value: 0.755921:  74%|███████▍  | 37/50 [04:50<01:43,  7.95s/it]

[I 2025-12-01 21:07:55,045] Trial 35 finished with value: 0.6769736842105263 and parameters: {'max_depth': 5, 'learning_rate': 0.017428927747627082, 'n_estimators': 881, 'subsample': 0.9692600300689751, 'colsample_bytree': 0.7599880611016948, 'min_child_weight': 9, 'gamma': 4.216241653626772, 'reg_alpha': 1.0835727575772735e-07, 'reg_lambda': 0.00045876027780418553, 'max_delta_step': 3}. Best is trial 28 with value: 0.7559210526315789.

Best trial: 28. Best value: 0.755921:  76%|███████▌  | 38/50 [04:58<01:36,  8.06s/it]

[I 2025-12-01 21:08:03,375] Trial 40 pruned.

Best trial: 28. Best value: 0.755921:  78%|███████▊  | 39/50 [05:06<01:27,  8.00s/it]

[I 2025-12-01 21:08:11,217] Trial 39 pruned.

Best trial: 28. Best value: 0.755921:  80%|████████  | 40/50 [05:10<01:07,  6.78s/it]

[I 2025-12-01 21:08:15,149] Trial 37 finished with value: 0.7032894736842106 and parameters: {'max_depth': 5, 'learning_rate': 0.014028268364496992, 'n_estimators': 1130, 'subsample': 0.9694564047208099, 'colsample_bytree': 0.6711665002987388, 'min_child_weight': 9, 'gamma': 2.900342422201713, 'reg_alpha': 7.955210402570633e-06, 'reg_lambda': 5.427256079189076, 'max_delta_step': 3}. Best is trial 28 with value: 0.7559210526315789.

Best trial: 28. Best value: 0.755921:  82%|████████▏ | 41/50 [05:12<00:47,  5.24s/it]

[I 2025-12-01 21:08:16,795] Trial 42 pruned.

Best trial: 28. Best value: 0.755921:  84%|████████▍ | 42/50 [05:18<00:45,  5.64s/it]

[I 2025-12-01 21:08:23,379] Trial 43 pruned.

Best trial: 28. Best value: 0.755921:  86%|████████▌ | 43/50 [05:19<00:28,  4.06s/it]

[I 2025-12-01 21:08:23,760] Trial 41 pruned.

Best trial: 28. Best value: 0.755921:  88%|████████▊ | 44/50 [05:19<00:18,  3.03s/it]

[I 2025-12-01 21:08:24,389] Trial 44 pruned.

Best trial: 28. Best value: 0.755921:  90%|█████████ | 45/50 [05:29<00:25,  5.10s/it]

[I 2025-12-01 21:08:34,309] Trial 38 finished with value: 0.7559210526315789 and parameters: {'max_depth': 5, 'learning_rate': 0.012093414460908282, 'n_estimators': 1130, 'subsample': 0.9698270349758117, 'colsample_bytree': 0.678573870176938, 'min_child_weight': 9, 'gamma': 4.918392055798439, 'reg_alpha': 1.3666343714287493e-07, 'reg_lambda': 0.007129562214112515, 'max_delta_step': 3}. Best is trial 28 with value: 0.7559210526315789.

Best trial: 28. Best value: 0.755921:  92%|█████████▏| 46/50 [05:42<00:29,  7.44s/it]

[I 2025-12-01 21:08:47,199] Trial 48 pruned.

Best trial: 28. Best value: 0.755921:  94%|█████████▍| 47/50 [06:11<00:41, 13.94s/it]

[I 2025-12-01 21:09:16,310] Trial 45 finished with value: 0.7559210526315789 and parameters: {'max_depth': 6, 'learning_rate': 0.04061757614755189, 'n_estimators': 1175, 'subsample': 0.9716820973683562, 'colsample_bytree': 0.8260075385787907, 'min_child_weight': 9, 'gamma': 3.0522920208662567, 'reg_alpha': 0.0005678442778460382, 'reg_lambda': 6.536062287817627, 'max_delta_step': 4}. Best is trial 28 with value: 0.7559210526315789.

Best trial: 28. Best value: 0.755921:  96%|█████████▌| 48/50 [06:15<00:21, 10.73s/it]

[I 2025-12-01 21:09:19,559] Trial 46 finished with value: 0.7032894736842106 and parameters: {'max_depth': 6, 'learning_rate': 0.012129751315761874, 'n_estimators': 1183, 'subsample': 0.9823451357637822, 'colsample_bytree': 0.8974241635426917, 'min_child_weight': 9, 'gamma': 2.932703245294113, 'reg_alpha': 8.455844645264249e-05, 'reg_lambda': 1.274510277048953, 'max_delta_step': 1}. Best is trial 28 with value: 0.7559210526315789.

Best trial: 28. Best value: 0.755921:  98%|█████████▊| 49/50 [06:16<00:08,  8.09s/it]

[I 2025-12-01 21:09:21,472] Trial 47 finished with value: 0.7296052631578948 and parameters: {'max_depth': 4, 'learning_rate': 0.01217531251435245, 'n_estimators': 1230, 'subsample': 0.9153192518102858, 'colsample_bytree': 0.8300262793829589, 'min_child_weight': 9, 'gamma': 1.0111918442012156, 'reg_alpha': 0.0005922825412014148, 'reg_lambda': 4.722030138713805, 'max_delta_step': 4}. Best is trial 28 with value: 0.7559210526315789.

Best trial: 28. Best value: 0.755921: 100%|██████████| 50/50 [06:26<00:00,  7.74s/it]

[I 2025-12-01 21:09:31,492] Trial 49 finished with value: 0.6769736842105263 and parameters: {'max_depth': 3, 'learning_rate': 0.026633175247687987, 'n_estimators': 1210, 'subsample': 0.9901417689347328, 'colsample_bytree': 0.8974055403969083, 'min_child_weight': 9, 'gamma': 4.482510572018662, 'reg_alpha': 6.441476637504643e-08, 'reg_lambda': 0.003550904860172884, 'max_delta_step': 4}. Best is trial 28 with value: 0.7559210526315789.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 21:09:36,208] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.447368:   2%|▏         | 1/50 [00:19<15:49, 19.39s/it]

[I 2025-12-01 21:09:55,589] Trial 3 finished with value: 0.4473684210526316 and parameters: {'max_depth': 4, 'learning_rate': 0.010269671185156067, 'n_estimators': 510, 'subsample': 0.56066785119301, 'colsample_bytree': 0.8017695117558137, 'min_child_weight': 9, 'gamma': 1.6683868168663207, 'reg_alpha': 0.0003022836355425748, 'reg_lambda': 1.631891318781445e-08, 'max_delta_step': 10}. Best is trial 3 with value: 0.4473684210526316.

Best trial: 3. Best value: 0.447368:   4%|▍         | 2/50 [00:36<14:33, 18.20s/it]

[I 2025-12-01 21:10:12,955] Trial 2 finished with value: 0.4037227214377407 and parameters: {'max_depth': 4, 'learning_rate': 0.14661239046524643, 'n_estimators': 1023, 'subsample': 0.6152157744084268, 'colsample_bytree': 0.7762207534716963, 'min_child_weight': 8, 'gamma': 4.1287395234650015, 'reg_alpha': 1.6597206896123409, 'reg_lambda': 0.0011260556538182146, 'max_delta_step': 8}. Best is trial 3 with value: 0.4473684210526316.

Best trial: 3. Best value: 0.447368:   6%|▌         | 3/50 [00:38<08:22, 10.69s/it]

[I 2025-12-01 21:10:14,716] Trial 0 finished with value: 0.3979460847240051 and parameters: {'max_depth': 7, 'learning_rate': 0.021328090011751347, 'n_estimators': 433, 'subsample': 0.987800758765382, 'colsample_bytree': 0.9129090304387855, 'min_child_weight': 3, 'gamma': 3.430698661480748, 'reg_alpha': 1.991999111032437e-07, 'reg_lambda': 1.9812698344990997e-07, 'max_delta_step': 1}. Best is trial 3 with value: 0.4473684210526316.

Best trial: 3. Best value: 0.447368:   8%|▊         | 4/50 [01:01<12:01, 15.70s/it]

[I 2025-12-01 21:10:38,080] Trial 5 finished with value: 0.41014120667522463 and parameters: {'max_depth': 9, 'learning_rate': 0.09056177761256375, 'n_estimators': 595, 'subsample': 0.9159509240273594, 'colsample_bytree': 0.6318039920939983, 'min_child_weight': 7, 'gamma': 0.4313956539895275, 'reg_alpha': 0.043752946117191334, 'reg_lambda': 1.4044142994667979, 'max_delta_step': 2}. Best is trial 3 with value: 0.4473684210526316.

Best trial: 3. Best value: 0.447368:  10%|█         | 5/50 [01:14<10:58, 14.62s/it]

[I 2025-12-01 21:10:50,805] Trial 6 finished with value: 0.42041078305519897 and parameters: {'max_depth': 6, 'learning_rate': 0.1258161330393127, 'n_estimators': 622, 'subsample': 0.8567554507569297, 'colsample_bytree': 0.822589912724907, 'min_child_weight': 2, 'gamma': 2.4315376825497776, 'reg_alpha': 1.3244293812079625e-07, 'reg_lambda': 0.00014152335768100507, 'max_delta_step': 9}. Best is trial 3 with value: 0.4473684210526316.

Best trial: 3. Best value: 0.447368:  12%|█▏        | 6/50 [01:15<07:21, 10.04s/it]

[I 2025-12-01 21:10:51,941] Trial 1 finished with value: 0.3940949935815148 and parameters: {'max_depth': 10, 'learning_rate': 0.038705608809098846, 'n_estimators': 849, 'subsample': 0.5414723367656253, 'colsample_bytree': 0.7461076611543449, 'min_child_weight': 1, 'gamma': 0.2687563776464652, 'reg_alpha': 2.1467988859640914, 'reg_lambda': 0.00018827713106855633, 'max_delta_step': 4}. Best is trial 3 with value: 0.4473684210526316.

Best trial: 3. Best value: 0.447368:  14%|█▍        | 7/50 [01:16<05:02,  7.05s/it]

[I 2025-12-01 21:10:52,830] Trial 4 finished with value: 0.38189987163029526 and parameters: {'max_depth': 7, 'learning_rate': 0.012162360347324345, 'n_estimators': 820, 'subsample': 0.5496699907784168, 'colsample_bytree': 0.6174462913285574, 'min_child_weight': 2, 'gamma': 2.8556083438668907, 'reg_alpha': 0.01912260444676756, 'reg_lambda': 1.7662571302139854e-06, 'max_delta_step': 6}. Best is trial 3 with value: 0.4473684210526316.

Best trial: 3. Best value: 0.447368:  16%|█▌        | 8/50 [01:34<07:26, 10.63s/it]

[I 2025-12-01 21:11:11,130] Trial 10 finished with value: 0.3138639281129654 and parameters: {'max_depth': 5, 'learning_rate': 0.11398257088921786, 'n_estimators': 415, 'subsample': 0.5031111269170014, 'colsample_bytree': 0.7301429592923083, 'min_child_weight': 8, 'gamma': 3.6439359719813744, 'reg_alpha': 2.1027777103146374e-06, 'reg_lambda': 4.510730967933519e-07, 'max_delta_step': 4}. Best is trial 3 with value: 0.4473684210526316.

Best trial: 3. Best value: 0.447368:  18%|█▊        | 9/50 [01:35<05:03,  7.41s/it]

[I 2025-12-01 21:11:11,471] Trial 7 finished with value: 0.15404364569961487 and parameters: {'max_depth': 10, 'learning_rate': 0.0338332785834046, 'n_estimators': 811, 'subsample': 0.7310914624465759, 'colsample_bytree': 0.9878394824264097, 'min_child_weight': 9, 'gamma': 0.28698733379091346, 'reg_alpha': 0.004661580955744707, 'reg_lambda': 3.2486528224344706, 'max_delta_step': 7}. Best is trial 3 with value: 0.4473684210526316.

Best trial: 12. Best value: 0.681643:  20%|██        | 10/50 [02:00<08:40, 13.02s/it]

[I 2025-12-01 21:11:37,049] Trial 12 finished with value: 0.6816431322207959 and parameters: {'max_depth': 6, 'learning_rate': 0.24999208476163087, 'n_estimators': 633, 'subsample': 0.8299600747646594, 'colsample_bytree': 0.8521482851448778, 'min_child_weight': 9, 'gamma': 2.475933349296172, 'reg_alpha': 0.0029607668106128196, 'reg_lambda': 3.288972518953812, 'max_delta_step': 10}. Best is trial 12 with value: 0.6816431322207959.

Best trial: 12. Best value: 0.681643:  22%|██▏       | 11/50 [02:07<07:13, 11.12s/it]

[I 2025-12-01 21:11:43,868] Trial 9 finished with value: 0.5417201540436457 and parameters: {'max_depth': 9, 'learning_rate': 0.05263081951154548, 'n_estimators': 1320, 'subsample': 0.7386037887881123, 'colsample_bytree': 0.9231781788148419, 'min_child_weight': 9, 'gamma': 1.7926103151696715, 'reg_alpha': 0.006016811518029551, 'reg_lambda': 2.9775624733250892e-05, 'max_delta_step': 5}. Best is trial 12 with value: 0.6816431322207959.

Best trial: 12. Best value: 0.681643:  24%|██▍       | 12/50 [02:18<06:53, 10.89s/it]

[I 2025-12-01 21:11:54,223] Trial 14 pruned.

Best trial: 12. Best value: 0.681643:  26%|██▌       | 13/50 [02:25<06:05,  9.88s/it]

[I 2025-12-01 21:12:01,774] Trial 15 pruned.

Best trial: 12. Best value: 0.681643:  28%|██▊       | 14/50 [02:34<05:48,  9.68s/it]

[I 2025-12-01 21:12:10,984] Trial 11 finished with value: 0.43645699614890887 and parameters: {'max_depth': 10, 'learning_rate': 0.016020481232008423, 'n_estimators': 1113, 'subsample': 0.9059099613312284, 'colsample_bytree': 0.9879961823113592, 'min_child_weight': 7, 'gamma': 0.07586995127527252, 'reg_alpha': 1.928560124499377e-08, 'reg_lambda': 8.004781643089875e-06, 'max_delta_step': 8}. Best is trial 12 with value: 0.6816431322207959.

Best trial: 12. Best value: 0.681643:  30%|███       | 15/50 [02:44<05:42,  9.79s/it]

[I 2025-12-01 21:12:21,028] Trial 17 pruned.

Best trial: 12. Best value: 0.681643:  32%|███▏      | 16/50 [02:46<04:12,  7.42s/it]

[I 2025-12-01 21:12:22,955] Trial 18 pruned.

Best trial: 12. Best value: 0.681643:  34%|███▍      | 17/50 [02:55<04:17,  7.79s/it]

[I 2025-12-01 21:12:31,614] Trial 19 pruned.

Best trial: 12. Best value: 0.681643:  36%|███▌      | 18/50 [02:58<03:20,  6.26s/it]

[I 2025-12-01 21:12:34,314] Trial 13 finished with value: 0.44030808729139925 and parameters: {'max_depth': 3, 'learning_rate': 0.2909203366496012, 'n_estimators': 1448, 'subsample': 0.7564386986301772, 'colsample_bytree': 0.5289581844128901, 'min_child_weight': 5, 'gamma': 4.930898857249678, 'reg_alpha': 4.747736806429938e-05, 'reg_lambda': 0.041796042571645216, 'max_delta_step': 10}. Best is trial 12 with value: 0.6816431322207959.

Best trial: 12. Best value: 0.681643:  38%|███▊      | 19/50 [03:04<03:18,  6.41s/it]

[I 2025-12-01 21:12:41,079] Trial 8 finished with value: 0.38189987163029526 and parameters: {'max_depth': 9, 'learning_rate': 0.014237497588448214, 'n_estimators': 1378, 'subsample': 0.5344343900504711, 'colsample_bytree': 0.6824358575127708, 'min_child_weight': 1, 'gamma': 0.6794079351748256, 'reg_alpha': 0.1268968414872247, 'reg_lambda': 0.0014696493813991646, 'max_delta_step': 4}. Best is trial 12 with value: 0.6816431322207959.

Best trial: 12. Best value: 0.681643:  40%|████      | 20/50 [03:14<03:41,  7.37s/it]

[I 2025-12-01 21:12:50,668] Trial 16 finished with value: 0.4768934531450577 and parameters: {'max_depth': 8, 'learning_rate': 0.27260682165524663, 'n_estimators': 1121, 'subsample': 0.8158849069231242, 'colsample_bytree': 0.8900990033214622, 'min_child_weight': 6, 'gamma': 2.392333596476797, 'reg_alpha': 0.002873139146513645, 'reg_lambda': 1.0576465820581288e-05, 'max_delta_step': 6}. Best is trial 12 with value: 0.6816431322207959.

Best trial: 12. Best value: 0.681643:  42%|████▏     | 21/50 [03:19<03:14,  6.71s/it]

[I 2025-12-01 21:12:55,858] Trial 23 pruned.

Best trial: 12. Best value: 0.681643:  44%|████▍     | 22/50 [03:30<03:44,  8.03s/it]

[I 2025-12-01 21:13:06,957] Trial 21 finished with value: 0.6713735558408216 and parameters: {'max_depth': 5, 'learning_rate': 0.1773886140195931, 'n_estimators': 682, 'subsample': 0.8313320524716777, 'colsample_bytree': 0.6803189840525017, 'min_child_weight': 9, 'gamma': 2.949392312012565, 'reg_alpha': 0.0009596695584983834, 'reg_lambda': 0.00198410654750917, 'max_delta_step': 5}. Best is trial 12 with value: 0.6816431322207959.

Best trial: 12. Best value: 0.681643:  46%|████▌     | 23/50 [03:39<03:46,  8.38s/it]

[I 2025-12-01 21:13:16,166] Trial 24 pruned.

Best trial: 12. Best value: 0.681643:  48%|████▊     | 24/50 [03:46<03:21,  7.75s/it]

[I 2025-12-01 21:13:22,428] Trial 26 pruned.

Best trial: 12. Best value: 0.681643:  50%|█████     | 25/50 [03:55<03:23,  8.13s/it]

[I 2025-12-01 21:13:31,449] Trial 20 finished with value: 0.6450577663671373 and parameters: {'max_depth': 5, 'learning_rate': 0.18694994876747703, 'n_estimators': 1320, 'subsample': 0.8233372886713066, 'colsample_bytree': 0.6982977508217818, 'min_child_weight': 9, 'gamma': 2.9182318954558752, 'reg_alpha': 0.00039174825212535817, 'reg_lambda': 0.004379326686541643, 'max_delta_step': 6}. Best is trial 12 with value: 0.6816431322207959.

Best trial: 12. Best value: 0.681643:  52%|█████▏    | 26/50 [04:01<03:01,  7.58s/it]

[I 2025-12-01 21:13:37,733] Trial 27 pruned.

Best trial: 12. Best value: 0.681643:  54%|█████▍    | 27/50 [04:02<02:09,  5.62s/it]

[I 2025-12-01 21:13:38,805] Trial 28 pruned.

Best trial: 12. Best value: 0.681643:  56%|█████▌    | 28/50 [04:06<01:50,  5.04s/it]

[I 2025-12-01 21:13:42,479] Trial 25 finished with value: 0.5154043645699615 and parameters: {'max_depth': 5, 'learning_rate': 0.20904327238582093, 'n_estimators': 738, 'subsample': 0.850610094070861, 'colsample_bytree': 0.667523143559047, 'min_child_weight': 8, 'gamma': 1.842297814339433, 'reg_alpha': 0.00582878686404731, 'reg_lambda': 6.521310844220513, 'max_delta_step': 5}. Best is trial 12 with value: 0.6816431322207959.

Best trial: 12. Best value: 0.681643:  58%|█████▊    | 29/50 [04:06<01:15,  3.62s/it]

[I 2025-12-01 21:13:42,779] Trial 22 finished with value: 0.5962772785622593 and parameters: {'max_depth': 5, 'learning_rate': 0.16890392188483944, 'n_estimators': 1286, 'subsample': 0.83613584234815, 'colsample_bytree': 0.8410150470311727, 'min_child_weight': 9, 'gamma': 2.72074998667658, 'reg_alpha': 0.0062511904989266745, 'reg_lambda': 7.368114652993995, 'max_delta_step': 6}. Best is trial 12 with value: 0.6816431322207959.

Best trial: 12. Best value: 0.681643:  60%|██████    | 30/50 [04:07<00:53,  2.66s/it]

[I 2025-12-01 21:13:43,214] Trial 29 pruned.

Best trial: 12. Best value: 0.681643:  62%|██████▏   | 31/50 [04:10<00:56,  3.00s/it]

[I 2025-12-01 21:13:46,990] Trial 33 pruned.

Best trial: 12. Best value: 0.681643:  64%|██████▍   | 32/50 [04:11<00:39,  2.17s/it]

[I 2025-12-01 21:13:47,227] Trial 31 pruned.

Best trial: 12. Best value: 0.681643:  66%|██████▌   | 33/50 [04:32<02:17,  8.06s/it]

[I 2025-12-01 21:14:09,037] Trial 32 finished with value: 0.41014120667522463 and parameters: {'max_depth': 7, 'learning_rate': 0.09433140646885335, 'n_estimators': 384, 'subsample': 0.9982873822017169, 'colsample_bytree': 0.7647583383429624, 'min_child_weight': 4, 'gamma': 3.4613649917154152, 'reg_alpha': 1.5928853127607786e-06, 'reg_lambda': 0.00741544750112773, 'max_delta_step': 7}. Best is trial 12 with value: 0.6816431322207959.

Best trial: 12. Best value: 0.681643:  68%|██████▊   | 34/50 [04:35<01:40,  6.29s/it]

[I 2025-12-01 21:14:11,208] Trial 30 finished with value: 0.5397946084724006 and parameters: {'max_depth': 5, 'learning_rate': 0.15642907181486232, 'n_estimators': 714, 'subsample': 0.8527158201042461, 'colsample_bytree': 0.6887101445846309, 'min_child_weight': 8, 'gamma': 3.353745921562925, 'reg_alpha': 0.0005021606242743828, 'reg_lambda': 0.008827382990061996, 'max_delta_step': 7}. Best is trial 12 with value: 0.6816431322207959.

Best trial: 12. Best value: 0.681643:  70%|███████   | 35/50 [04:35<01:09,  4.67s/it]

[I 2025-12-01 21:14:12,074] Trial 35 finished with value: 0.5436456996148908 and parameters: {'max_depth': 5, 'learning_rate': 0.13155155286835415, 'n_estimators': 523, 'subsample': 0.8409612018752619, 'colsample_bytree': 0.7274027985111885, 'min_child_weight': 9, 'gamma': 2.734103291285019, 'reg_alpha': 0.0001285129371859475, 'reg_lambda': 0.11647907747159958, 'max_delta_step': 7}. Best is trial 12 with value: 0.6816431322207959.

Best trial: 12. Best value: 0.681643:  72%|███████▏  | 36/50 [05:00<02:28, 10.61s/it]

[I 2025-12-01 21:14:36,540] Trial 37 finished with value: 0.5539152759948652 and parameters: {'max_depth': 4, 'learning_rate': 0.1378327794635335, 'n_estimators': 501, 'subsample': 0.8777387254867028, 'colsample_bytree': 0.7350904745065459, 'min_child_weight': 9, 'gamma': 2.7817435708639633, 'reg_alpha': 0.5711716045999119, 'reg_lambda': 0.0003030258158476889, 'max_delta_step': 9}. Best is trial 12 with value: 0.6816431322207959.

Best trial: 12. Best value: 0.681643:  74%|███████▍  | 37/50 [05:04<01:53,  8.76s/it]

[I 2025-12-01 21:14:40,996] Trial 34 finished with value: 0.5436456996148908 and parameters: {'max_depth': 6, 'learning_rate': 0.1466114514111149, 'n_estimators': 1185, 'subsample': 0.8009342188016493, 'colsample_bytree': 0.716034676350107, 'min_child_weight': 9, 'gamma': 2.848215779790541, 'reg_alpha': 0.0001374050080858513, 'reg_lambda': 0.12725749219957685, 'max_delta_step': 7}. Best is trial 12 with value: 0.6816431322207959.

Best trial: 12. Best value: 0.681643:  76%|███████▌  | 38/50 [05:08<01:28,  7.38s/it]

[I 2025-12-01 21:14:45,153] Trial 39 pruned.

Best trial: 12. Best value: 0.681643:  78%|███████▊  | 39/50 [05:16<01:21,  7.41s/it]

[I 2025-12-01 21:14:52,625] Trial 41 pruned.

Best trial: 12. Best value: 0.681643:  80%|████████  | 40/50 [05:26<01:22,  8.30s/it]

[I 2025-12-01 21:15:02,999] Trial 42 pruned.

Best trial: 12. Best value: 0.681643:  82%|████████▏ | 41/50 [05:27<00:53,  5.96s/it]

[I 2025-12-01 21:15:03,499] Trial 36 finished with value: 0.6187419768934532 and parameters: {'max_depth': 5, 'learning_rate': 0.15356745886262502, 'n_estimators': 1166, 'subsample': 0.8329369273790918, 'colsample_bytree': 0.7206043775826292, 'min_child_weight': 9, 'gamma': 2.7759488219984134, 'reg_alpha': 8.170283387670353e-05, 'reg_lambda': 0.18681544588016885, 'max_delta_step': 9}. Best is trial 12 with value: 0.6816431322207959.

Best trial: 12. Best value: 0.681643:  84%|████████▍ | 42/50 [05:31<00:44,  5.57s/it]

[I 2025-12-01 21:15:08,173] Trial 38 finished with value: 0.6328626444159178 and parameters: {'max_depth': 4, 'learning_rate': 0.150461837632455, 'n_estimators': 1168, 'subsample': 0.7957983845324119, 'colsample_bytree': 0.8628332966863886, 'min_child_weight': 9, 'gamma': 2.6545592338435684, 'reg_alpha': 0.3957726718828226, 'reg_lambda': 0.0006004183131466608, 'max_delta_step': 9}. Best is trial 12 with value: 0.6816431322207959.

Best trial: 12. Best value: 0.681643:  86%|████████▌ | 43/50 [05:34<00:32,  4.68s/it]

[I 2025-12-01 21:15:10,765] Trial 43 pruned.

Best trial: 12. Best value: 0.681643:  88%|████████▊ | 44/50 [05:40<00:30,  5.01s/it]

[I 2025-12-01 21:15:16,565] Trial 45 pruned.

Best trial: 12. Best value: 0.681643:  90%|█████████ | 45/50 [05:43<00:21,  4.34s/it]

[I 2025-12-01 21:15:19,328] Trial 46 pruned.

Best trial: 12. Best value: 0.681643:  92%|█████████▏| 46/50 [05:45<00:15,  3.90s/it]

[I 2025-12-01 21:15:22,181] Trial 47 pruned.

Best trial: 12. Best value: 0.681643:  94%|█████████▍| 47/50 [05:55<00:16,  5.66s/it]

[I 2025-12-01 21:15:31,958] Trial 49 pruned.

Best trial: 12. Best value: 0.681643:  96%|█████████▌| 48/50 [06:05<00:13,  6.97s/it]

[I 2025-12-01 21:15:41,994] Trial 40 finished with value: 0.45057766367137353 and parameters: {'max_depth': 4, 'learning_rate': 0.24978363536769463, 'n_estimators': 1327, 'subsample': 0.9232952905779309, 'colsample_bytree': 0.810389118062034, 'min_child_weight': 7, 'gamma': 2.116141979785778, 'reg_alpha': 0.017713259460271157, 'reg_lambda': 1.7080860306999353, 'max_delta_step': 9}. Best is trial 12 with value: 0.6816431322207959.

Best trial: 44. Best value: 0.72208:  98%|█████████▊| 49/50 [06:18<00:08,  8.79s/it]

[I 2025-12-01 21:15:55,017] Trial 44 finished with value: 0.7220795892169447 and parameters: {'max_depth': 4, 'learning_rate': 0.22896275104277458, 'n_estimators': 1404, 'subsample': 0.8356241870429203, 'colsample_bytree': 0.7638129773633047, 'min_child_weight': 9, 'gamma': 2.67848969293932, 'reg_alpha': 7.714195724260587, 'reg_lambda': 3.138896445428199, 'max_delta_step': 10}. Best is trial 44 with value: 0.7220795892169447.

Best trial: 44. Best value: 0.72208: 100%|██████████| 50/50 [06:23<00:00,  7.66s/it]

[I 2025-12-01 21:15:59,347] Trial 48 finished with value: 0.47881899871630296 and parameters: {'max_depth': 4, 'learning_rate': 0.11718300263356295, 'n_estimators': 1196, 'subsample': 0.8836910479346085, 'colsample_bytree': 0.8005784454513548, 'min_child_weight': 8, 'gamma': 3.720341739765594, 'reg_alpha': 1.0250821371709016, 'reg_lambda': 0.001189994711606139, 'max_delta_step': 8}. Best is trial 44 with value: 0.7220795892169447.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 21:16:02,947] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.430263:   2%|▏         | 1/50 [00:16<13:17, 16.27s/it]

[I 2025-12-01 21:16:19,207] Trial 2 finished with value: 0.43026315789473685 and parameters: {'max_depth': 5, 'learning_rate': 0.03728022419307199, 'n_estimators': 342, 'subsample': 0.862115527774284, 'colsample_bytree': 0.7970823787163241, 'min_child_weight': 9, 'gamma': 0.16146654720043507, 'reg_alpha': 0.053243519652673134, 'reg_lambda': 0.004408292052117907, 'max_delta_step': 2}. Best is trial 2 with value: 0.43026315789473685.

Best trial: 1. Best value: 0.442763:   4%|▍         | 2/50 [00:22<08:08, 10.18s/it]

[I 2025-12-01 21:16:25,118] Trial 1 finished with value: 0.44276315789473686 and parameters: {'max_depth': 7, 'learning_rate': 0.01057805627754166, 'n_estimators': 438, 'subsample': 0.7711883656971044, 'colsample_bytree': 0.7952693324658523, 'min_child_weight': 8, 'gamma': 3.6080039795062095, 'reg_alpha': 0.00037716152098290416, 'reg_lambda': 1.1649177230710212e-05, 'max_delta_step': 0}. Best is trial 1 with value: 0.44276315789473686.

Best trial: 1. Best value: 0.442763:   6%|▌         | 3/50 [00:29<07:02,  8.98s/it]

[I 2025-12-01 21:16:32,683] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.02370312854081368, 'n_estimators': 256, 'subsample': 0.8728269368413588, 'colsample_bytree': 0.9909901491870524, 'min_child_weight': 10, 'gamma': 4.6161517201369024, 'reg_alpha': 0.09640980517931363, 'reg_lambda': 2.3353146630482993e-08, 'max_delta_step': 7}. Best is trial 1 with value: 0.44276315789473686.

Best trial: 3. Best value: 0.480263:   8%|▊         | 4/50 [00:32<05:05,  6.65s/it]

[I 2025-12-01 21:16:35,742] Trial 3 finished with value: 0.48026315789473684 and parameters: {'max_depth': 6, 'learning_rate': 0.036435193710158485, 'n_estimators': 510, 'subsample': 0.6205911505506649, 'colsample_bytree': 0.7946915082617966, 'min_child_weight': 4, 'gamma': 0.3943232106041461, 'reg_alpha': 1.3523861143574136, 'reg_lambda': 4.5585733948693377e-07, 'max_delta_step': 7}. Best is trial 3 with value: 0.48026315789473684.

Best trial: 3. Best value: 0.480263:  10%|█         | 5/50 [00:41<05:37,  7.51s/it]

[I 2025-12-01 21:16:44,783] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.03699080852596953, 'n_estimators': 435, 'subsample': 0.9673545646980715, 'colsample_bytree': 0.7196805842918514, 'min_child_weight': 10, 'gamma': 2.2506355622646868, 'reg_alpha': 3.097697050000658e-08, 'reg_lambda': 4.4296813147634094e-07, 'max_delta_step': 8}. Best is trial 3 with value: 0.48026315789473684.

Best trial: 0. Best value: 0.481579:  12%|█▏        | 6/50 [00:50<05:47,  7.90s/it]

[I 2025-12-01 21:16:53,451] Trial 0 finished with value: 0.481578947368421 and parameters: {'max_depth': 5, 'learning_rate': 0.29601302724561535, 'n_estimators': 1267, 'subsample': 0.8511978672391776, 'colsample_bytree': 0.72536867896023, 'min_child_weight': 9, 'gamma': 2.031744450351156, 'reg_alpha': 1.7097988904521234e-06, 'reg_lambda': 0.01700366814204214, 'max_delta_step': 7}. Best is trial 0 with value: 0.481578947368421.

Best trial: 6. Best value: 0.506579:  14%|█▍        | 7/50 [01:03<06:45,  9.44s/it]

[I 2025-12-01 21:17:06,047] Trial 6 finished with value: 0.506578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.018674738907755926, 'n_estimators': 329, 'subsample': 0.8309539381335758, 'colsample_bytree': 0.8135131414923341, 'min_child_weight': 3, 'gamma': 1.9093860698849496, 'reg_alpha': 9.462891911943e-05, 'reg_lambda': 2.0989823024016547, 'max_delta_step': 0}. Best is trial 6 with value: 0.506578947368421.

Best trial: 8. Best value: 0.519079:  16%|█▌        | 8/50 [01:15<07:11, 10.27s/it]

[I 2025-12-01 21:17:18,100] Trial 8 finished with value: 0.5190789473684211 and parameters: {'max_depth': 6, 'learning_rate': 0.03932523673022371, 'n_estimators': 666, 'subsample': 0.957244626280736, 'colsample_bytree': 0.6861425101101332, 'min_child_weight': 6, 'gamma': 2.9232204531362935, 'reg_alpha': 0.7373043011520902, 'reg_lambda': 3.4353344757093123e-06, 'max_delta_step': 2}. Best is trial 8 with value: 0.5190789473684211.

Best trial: 8. Best value: 0.519079:  18%|█▊        | 9/50 [01:15<04:59,  7.30s/it]

[I 2025-12-01 21:17:18,867] Trial 9 finished with value: 0.49276315789473685 and parameters: {'max_depth': 6, 'learning_rate': 0.1445296639903431, 'n_estimators': 571, 'subsample': 0.952794922437231, 'colsample_bytree': 0.6518259983284678, 'min_child_weight': 6, 'gamma': 0.021353712530602365, 'reg_alpha': 0.002070498698340287, 'reg_lambda': 0.0003119134961916192, 'max_delta_step': 2}. Best is trial 8 with value: 0.5190789473684211.

Best trial: 8. Best value: 0.519079:  20%|██        | 10/50 [01:21<04:30,  6.77s/it]

[I 2025-12-01 21:17:24,452] Trial 7 finished with value: 0.5078947368421052 and parameters: {'max_depth': 6, 'learning_rate': 0.045226515777474975, 'n_estimators': 1157, 'subsample': 0.9617775765260228, 'colsample_bytree': 0.6981382965985554, 'min_child_weight': 8, 'gamma': 1.206336622538771, 'reg_alpha': 0.003921952467427653, 'reg_lambda': 2.055248320153656, 'max_delta_step': 3}. Best is trial 8 with value: 0.5190789473684211.

Best trial: 11. Best value: 0.532895:  22%|██▏       | 11/50 [01:29<04:36,  7.08s/it]

[I 2025-12-01 21:17:32,246] Trial 11 finished with value: 0.5328947368421053 and parameters: {'max_depth': 4, 'learning_rate': 0.03534241863563329, 'n_estimators': 219, 'subsample': 0.7346061167453155, 'colsample_bytree': 0.6046374209237885, 'min_child_weight': 6, 'gamma': 2.558225332894486, 'reg_alpha': 0.06507660452563138, 'reg_lambda': 5.34993630988744e-05, 'max_delta_step': 2}. Best is trial 11 with value: 0.5328947368421053.

Best trial: 10. Best value: 0.534211:  24%|██▍       | 12/50 [01:45<06:09,  9.73s/it]

[I 2025-12-01 21:17:48,014] Trial 10 finished with value: 0.5342105263157895 and parameters: {'max_depth': 5, 'learning_rate': 0.03779104211690729, 'n_estimators': 899, 'subsample': 0.8660391161742819, 'colsample_bytree': 0.8089169698931793, 'min_child_weight': 8, 'gamma': 0.8928241402578474, 'reg_alpha': 5.088695961461395e-07, 'reg_lambda': 2.130396690449354, 'max_delta_step': 5}. Best is trial 10 with value: 0.5342105263157895.

Best trial: 10. Best value: 0.534211:  26%|██▌       | 13/50 [02:02<07:23, 11.99s/it]

[I 2025-12-01 21:18:05,223] Trial 12 finished with value: 0.49407894736842106 and parameters: {'max_depth': 9, 'learning_rate': 0.15511013041626626, 'n_estimators': 985, 'subsample': 0.694897977414666, 'colsample_bytree': 0.9121910024257088, 'min_child_weight': 4, 'gamma': 2.7608468204460928, 'reg_alpha': 1.644523210270086e-05, 'reg_lambda': 8.643872283931136e-07, 'max_delta_step': 6}. Best is trial 10 with value: 0.5342105263157895.

Best trial: 10. Best value: 0.534211:  28%|██▊       | 14/50 [02:06<05:45,  9.60s/it]

[I 2025-12-01 21:18:09,294] Trial 14 finished with value: 0.5217105263157895 and parameters: {'max_depth': 10, 'learning_rate': 0.09933465368208265, 'n_estimators': 850, 'subsample': 0.6321475651095207, 'colsample_bytree': 0.5330821519153719, 'min_child_weight': 6, 'gamma': 3.439724385155655, 'reg_alpha': 2.222141018358962, 'reg_lambda': 3.98614344433602e-05, 'max_delta_step': 4}. Best is trial 10 with value: 0.5342105263157895.

Best trial: 10. Best value: 0.534211:  30%|███       | 15/50 [02:11<04:52,  8.35s/it]

[I 2025-12-01 21:18:14,736] Trial 13 finished with value: 0.5190789473684211 and parameters: {'max_depth': 10, 'learning_rate': 0.09721493375954297, 'n_estimators': 860, 'subsample': 0.5010614969032454, 'colsample_bytree': 0.540310699382456, 'min_child_weight': 1, 'gamma': 3.323705926831552, 'reg_alpha': 7.249071790942138, 'reg_lambda': 3.362353092202108e-05, 'max_delta_step': 10}. Best is trial 10 with value: 0.5342105263157895.

Best trial: 10. Best value: 0.534211:  32%|███▏      | 16/50 [02:21<04:54,  8.67s/it]

[I 2025-12-01 21:18:24,144] Trial 15 pruned.

Best trial: 10. Best value: 0.534211:  34%|███▍      | 17/50 [02:42<06:51, 12.47s/it]

[I 2025-12-01 21:18:45,447] Trial 18 pruned.

Best trial: 10. Best value: 0.534211:  36%|███▌      | 18/50 [02:46<05:13,  9.80s/it]

[I 2025-12-01 21:18:49,028] Trial 16 finished with value: 0.5190789473684211 and parameters: {'max_depth': 3, 'learning_rate': 0.07017569954161261, 'n_estimators': 848, 'subsample': 0.5028915230656988, 'colsample_bytree': 0.5277197673856634, 'min_child_weight': 1, 'gamma': 1.1661709127702633, 'reg_alpha': 1.4362616302111373e-08, 'reg_lambda': 0.029538990922458402, 'max_delta_step': 4}. Best is trial 10 with value: 0.5342105263157895.

Best trial: 10. Best value: 0.534211:  38%|███▊      | 19/50 [02:49<04:04,  7.89s/it]

[I 2025-12-01 21:18:52,465] Trial 17 finished with value: 0.5052631578947369 and parameters: {'max_depth': 3, 'learning_rate': 0.07356293842794441, 'n_estimators': 799, 'subsample': 0.5284387895257758, 'colsample_bytree': 0.5759603226670001, 'min_child_weight': 1, 'gamma': 1.1074418589285329, 'reg_alpha': 1.2018523881382815e-07, 'reg_lambda': 0.06321942413110256, 'max_delta_step': 10}. Best is trial 10 with value: 0.5342105263157895.

Best trial: 10. Best value: 0.534211:  40%|████      | 20/50 [02:55<03:37,  7.25s/it]

[I 2025-12-01 21:18:58,248] Trial 20 pruned.

Best trial: 10. Best value: 0.534211:  42%|████▏     | 21/50 [02:56<02:40,  5.54s/it]

[I 2025-12-01 21:18:59,806] Trial 19 finished with value: 0.49407894736842106 and parameters: {'max_depth': 3, 'learning_rate': 0.019286887828155887, 'n_estimators': 718, 'subsample': 0.7535140605507917, 'colsample_bytree': 0.6168190611207478, 'min_child_weight': 7, 'gamma': 1.1562656403465097, 'reg_alpha': 2.07771543671491e-08, 'reg_lambda': 0.0007511463791086163, 'max_delta_step': 4}. Best is trial 10 with value: 0.5342105263157895.

Best trial: 10. Best value: 0.534211:  44%|████▍     | 22/50 [02:58<02:03,  4.40s/it]

[I 2025-12-01 21:19:01,535] Trial 21 pruned.

Best trial: 10. Best value: 0.534211:  46%|████▌     | 23/50 [03:07<02:35,  5.77s/it]

[I 2025-12-01 21:19:10,498] Trial 22 pruned.

Best trial: 10. Best value: 0.534211:  48%|████▊     | 24/50 [03:15<02:45,  6.38s/it]

[I 2025-12-01 21:19:18,316] Trial 25 pruned.

Best trial: 10. Best value: 0.534211:  50%|█████     | 25/50 [03:16<02:02,  4.89s/it]

[I 2025-12-01 21:19:19,718] Trial 23 pruned.

Best trial: 10. Best value: 0.534211:  52%|█████▏    | 26/50 [03:22<02:02,  5.09s/it]

[I 2025-12-01 21:19:25,277] Trial 24 pruned.

Best trial: 10. Best value: 0.534211:  54%|█████▍    | 27/50 [03:23<01:27,  3.83s/it]

[I 2025-12-01 21:19:26,149] Trial 27 pruned.

Best trial: 10. Best value: 0.534211:  56%|█████▌    | 28/50 [03:38<02:41,  7.32s/it]

[I 2025-12-01 21:19:41,629] Trial 28 pruned.

Best trial: 10. Best value: 0.534211:  58%|█████▊    | 29/50 [03:45<02:29,  7.12s/it]

[I 2025-12-01 21:19:48,282] Trial 29 pruned.

Best trial: 10. Best value: 0.534211:  60%|██████    | 30/50 [03:45<01:41,  5.09s/it]

[I 2025-12-01 21:19:48,622] Trial 30 pruned.

Best trial: 10. Best value: 0.534211:  62%|██████▏   | 31/50 [03:55<02:04,  6.54s/it]

[I 2025-12-01 21:19:58,540] Trial 32 pruned.

Best trial: 10. Best value: 0.534211:  64%|██████▍   | 32/50 [03:56<01:26,  4.78s/it]

[I 2025-12-01 21:19:59,222] Trial 26 finished with value: 0.49407894736842106 and parameters: {'max_depth': 8, 'learning_rate': 0.11729223016511138, 'n_estimators': 1040, 'subsample': 0.601069176792211, 'colsample_bytree': 0.5738628951383408, 'min_child_weight': 5, 'gamma': 3.534697706552729, 'reg_alpha': 0.5249149710524957, 'reg_lambda': 3.733101283399816e-05, 'max_delta_step': 3}. Best is trial 10 with value: 0.5342105263157895.

Best trial: 10. Best value: 0.534211:  66%|██████▌   | 33/50 [04:18<02:51, 10.07s/it]

[I 2025-12-01 21:20:21,645] Trial 31 finished with value: 0.49407894736842106 and parameters: {'max_depth': 9, 'learning_rate': 0.028993036556607007, 'n_estimators': 576, 'subsample': 0.6314882152944298, 'colsample_bytree': 0.755439040161481, 'min_child_weight': 3, 'gamma': 2.9664800927499386, 'reg_alpha': 4.866605151342867, 'reg_lambda': 3.4854253791477254e-08, 'max_delta_step': 6}. Best is trial 10 with value: 0.5342105263157895.

Best trial: 10. Best value: 0.534211:  68%|██████▊   | 34/50 [04:28<02:39,  9.94s/it]

[I 2025-12-01 21:20:31,276] Trial 34 finished with value: 0.49407894736842106 and parameters: {'max_depth': 7, 'learning_rate': 0.05738441026612468, 'n_estimators': 617, 'subsample': 0.9292597646178454, 'colsample_bytree': 0.6927077779611006, 'min_child_weight': 4, 'gamma': 2.9461044975937147, 'reg_alpha': 0.19857379142376888, 'reg_lambda': 4.171519460387349e-06, 'max_delta_step': 2}. Best is trial 10 with value: 0.5342105263157895.

Best trial: 10. Best value: 0.534211:  70%|███████   | 35/50 [04:32<02:03,  8.26s/it]

[I 2025-12-01 21:20:35,621] Trial 37 pruned.

Best trial: 10. Best value: 0.534211:  72%|███████▏  | 36/50 [04:39<01:49,  7.83s/it]

[I 2025-12-01 21:20:42,445] Trial 33 finished with value: 0.481578947368421 and parameters: {'max_depth': 9, 'learning_rate': 0.22029238072752885, 'n_estimators': 1308, 'subsample': 0.8949485291375211, 'colsample_bytree': 0.5480330880953579, 'min_child_weight': 9, 'gamma': 2.1690502436806742, 'reg_alpha': 3.287312362031099e-05, 'reg_lambda': 0.0035879913801887676, 'max_delta_step': 6}. Best is trial 10 with value: 0.5342105263157895.

Best trial: 10. Best value: 0.534211:  74%|███████▍  | 37/50 [04:41<01:18,  6.02s/it]

[I 2025-12-01 21:20:44,251] Trial 35 finished with value: 0.49407894736842106 and parameters: {'max_depth': 7, 'learning_rate': 0.05574837199079874, 'n_estimators': 898, 'subsample': 0.9265633826578284, 'colsample_bytree': 0.6937558961172293, 'min_child_weight': 4, 'gamma': 2.941656339669736, 'reg_alpha': 1.9930956851705878e-05, 'reg_lambda': 5.640446015412153e-06, 'max_delta_step': 4}. Best is trial 10 with value: 0.5342105263157895.

Best trial: 10. Best value: 0.534211:  76%|███████▌  | 38/50 [04:47<01:13,  6.10s/it]

[I 2025-12-01 21:20:50,525] Trial 39 pruned.

Best trial: 10. Best value: 0.534211:  78%|███████▊  | 39/50 [04:50<00:56,  5.10s/it]

[I 2025-12-01 21:20:53,294] Trial 40 pruned.

Best trial: 10. Best value: 0.534211:  80%|████████  | 40/50 [04:51<00:40,  4.02s/it]

[I 2025-12-01 21:20:54,806] Trial 38 pruned.

Best trial: 10. Best value: 0.534211:  82%|████████▏ | 41/50 [04:54<00:33,  3.74s/it]

[I 2025-12-01 21:20:57,900] Trial 43 pruned.

Best trial: 10. Best value: 0.534211:  84%|████████▍ | 42/50 [04:59<00:31,  3.91s/it]

[I 2025-12-01 21:21:02,206] Trial 42 pruned.

Best trial: 10. Best value: 0.534211:  86%|████████▌ | 43/50 [05:11<00:45,  6.48s/it]

[I 2025-12-01 21:21:14,666] Trial 36 finished with value: 0.5092105263157894 and parameters: {'max_depth': 7, 'learning_rate': 0.05296124467583047, 'n_estimators': 934, 'subsample': 0.9979184774625481, 'colsample_bytree': 0.704675191695665, 'min_child_weight': 4, 'gamma': 2.9815966484143126, 'reg_alpha': 1.4469718256013657e-05, 'reg_lambda': 5.495151466552722e-06, 'max_delta_step': 2}. Best is trial 10 with value: 0.5342105263157895.

Best trial: 41. Best value: 0.560526:  88%|████████▊ | 44/50 [05:21<00:45,  7.55s/it]

[I 2025-12-01 21:21:24,725] Trial 41 finished with value: 0.5605263157894737 and parameters: {'max_depth': 4, 'learning_rate': 0.040655758735801864, 'n_estimators': 775, 'subsample': 0.8497433652381231, 'colsample_bytree': 0.5043766066652738, 'min_child_weight': 8, 'gamma': 3.7609810165580493, 'reg_alpha': 0.0005184698529517026, 'reg_lambda': 1.1880925802380235e-07, 'max_delta_step': 5}. Best is trial 41 with value: 0.5605263157894737.

Best trial: 41. Best value: 0.560526:  90%|█████████ | 45/50 [05:25<00:32,  6.46s/it]

[I 2025-12-01 21:21:28,630] Trial 47 pruned.

Best trial: 41. Best value: 0.560526:  92%|█████████▏| 46/50 [05:31<00:25,  6.32s/it]

[I 2025-12-01 21:21:34,637] Trial 48 pruned.

Best trial: 41. Best value: 0.560526:  94%|█████████▍| 47/50 [05:39<00:20,  6.76s/it]

[I 2025-12-01 21:21:42,418] Trial 44 finished with value: 0.506578947368421 and parameters: {'max_depth': 10, 'learning_rate': 0.09213400469496735, 'n_estimators': 849, 'subsample': 0.5521211794216617, 'colsample_bytree': 0.7646770517027233, 'min_child_weight': 2, 'gamma': 3.2480254427363495, 'reg_alpha': 0.1790593735778194, 'reg_lambda': 2.2111223998939184e-05, 'max_delta_step': 9}. Best is trial 41 with value: 0.5605263157894737.

Best trial: 41. Best value: 0.560526:  96%|█████████▌| 48/50 [05:40<00:10,  5.09s/it]

[I 2025-12-01 21:21:43,619] Trial 45 finished with value: 0.49407894736842106 and parameters: {'max_depth': 10, 'learning_rate': 0.10432952261824416, 'n_estimators': 793, 'subsample': 0.5460184526480825, 'colsample_bytree': 0.550762449442864, 'min_child_weight': 2, 'gamma': 3.314474545040578, 'reg_alpha': 2.265505955908074, 'reg_lambda': 1.4230053361311454e-05, 'max_delta_step': 7}. Best is trial 41 with value: 0.5605263157894737.

Best trial: 41. Best value: 0.560526:  98%|█████████▊| 49/50 [05:42<00:04,  4.20s/it]

[I 2025-12-01 21:21:45,737] Trial 49 pruned.

Best trial: 41. Best value: 0.560526: 100%|██████████| 50/50 [05:45<00:00,  6.90s/it]

[I 2025-12-01 21:21:48,118] Trial 46 finished with value: 0.506578947368421 and parameters: {'max_depth': 10, 'learning_rate': 0.09365841961732893, 'n_estimators': 812, 'subsample': 0.5556787697187355, 'colsample_bytree': 0.5410662744904905, 'min_child_weight': 5, 'gamma': 3.310078354617106, 'reg_alpha': 2.5565628940803546, 'reg_lambda': 1.623183249251494e-05, 'max_delta_step': 7}. Best is trial 41 with value: 0.5605263157894737.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 21:21:51,730] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.487163:   2%|▏         | 1/50 [00:28<23:27, 28.73s/it]

[I 2025-12-01 21:22:20,449] Trial 0 finished with value: 0.4871630295250321 and parameters: {'max_depth': 8, 'learning_rate': 0.0814853526364599, 'n_estimators': 521, 'subsample': 0.8805088291454265, 'colsample_bytree': 0.9023428148839303, 'min_child_weight': 3, 'gamma': 2.971768891729149, 'reg_alpha': 0.0018311638998875853, 'reg_lambda': 9.17073728792331e-06, 'max_delta_step': 4}. Best is trial 0 with value: 0.4871630295250321.

Best trial: 0. Best value: 0.487163:   4%|▍         | 2/50 [00:32<11:15, 14.08s/it]

[I 2025-12-01 21:22:24,279] Trial 1 finished with value: 0.4711168164313222 and parameters: {'max_depth': 3, 'learning_rate': 0.01827834266159642, 'n_estimators': 202, 'subsample': 0.8894734124435717, 'colsample_bytree': 0.6641056751033851, 'min_child_weight': 1, 'gamma': 0.18663296039046817, 'reg_alpha': 0.0006856585265234698, 'reg_lambda': 0.6507282520032427, 'max_delta_step': 4}. Best is trial 0 with value: 0.4871630295250321.

Best trial: 2. Best value: 0.511553:   6%|▌         | 3/50 [00:36<07:25,  9.48s/it]

[I 2025-12-01 21:22:28,284] Trial 2 finished with value: 0.511553273427471 and parameters: {'max_depth': 4, 'learning_rate': 0.10534435296653519, 'n_estimators': 566, 'subsample': 0.6215559752789249, 'colsample_bytree': 0.9961372308320106, 'min_child_weight': 1, 'gamma': 2.5694953507534346, 'reg_alpha': 8.059801521303288e-08, 'reg_lambda': 0.0006786969908294812, 'max_delta_step': 6}. Best is trial 2 with value: 0.511553273427471.

Best trial: 2. Best value: 0.511553:   8%|▊         | 4/50 [00:56<10:22, 13.52s/it]

[I 2025-12-01 21:22:48,007] Trial 5 finished with value: 0.4974326059050064 and parameters: {'max_depth': 8, 'learning_rate': 0.15954559532240656, 'n_estimators': 563, 'subsample': 0.7191570317835534, 'colsample_bytree': 0.5091166044045592, 'min_child_weight': 3, 'gamma': 1.3260784609762277, 'reg_alpha': 7.581711823628732e-05, 'reg_lambda': 3.247758720636762e-08, 'max_delta_step': 1}. Best is trial 2 with value: 0.511553273427471.

Best trial: 2. Best value: 0.511553:  10%|█         | 5/50 [00:57<06:44,  8.98s/it]

[I 2025-12-01 21:22:48,942] Trial 3 finished with value: 0.4833119383825417 and parameters: {'max_depth': 4, 'learning_rate': 0.0593827366071953, 'n_estimators': 972, 'subsample': 0.7399921143112669, 'colsample_bytree': 0.8475370936649611, 'min_child_weight': 1, 'gamma': 1.3551288304256408, 'reg_alpha': 4.365361606456966e-08, 'reg_lambda': 0.00043061881187875906, 'max_delta_step': 2}. Best is trial 2 with value: 0.511553273427471.

Best trial: 2. Best value: 0.511553:  12%|█▏        | 6/50 [01:07<06:51,  9.36s/it]

[I 2025-12-01 21:22:59,040] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.012246385648346458, 'n_estimators': 220, 'subsample': 0.769833829473207, 'colsample_bytree': 0.631362485714006, 'min_child_weight': 10, 'gamma': 1.4170933159472838, 'reg_alpha': 2.3275028046919486e-05, 'reg_lambda': 2.56699410342028e-06, 'max_delta_step': 9}. Best is trial 2 with value: 0.511553273427471.

Best trial: 2. Best value: 0.511553:  14%|█▍        | 7/50 [01:17<06:52,  9.58s/it]

[I 2025-12-01 21:23:09,073] Trial 6 finished with value: 0.4871630295250321 and parameters: {'max_depth': 10, 'learning_rate': 0.0527830489363, 'n_estimators': 1014, 'subsample': 0.9855113059908505, 'colsample_bytree': 0.7424624275704522, 'min_child_weight': 8, 'gamma': 3.1798807123169426, 'reg_alpha': 8.95183482893746e-07, 'reg_lambda': 1.913780004760983e-08, 'max_delta_step': 7}. Best is trial 2 with value: 0.511553273427471.

Best trial: 2. Best value: 0.511553:  16%|█▌        | 8/50 [01:27<06:55,  9.90s/it]

[I 2025-12-01 21:23:19,661] Trial 9 finished with value: 0.48523748395378685 and parameters: {'max_depth': 8, 'learning_rate': 0.054548434599713286, 'n_estimators': 330, 'subsample': 0.8545337098256994, 'colsample_bytree': 0.652043471179525, 'min_child_weight': 3, 'gamma': 0.0676670849040456, 'reg_alpha': 0.003936591712720155, 'reg_lambda': 2.993589668502803e-07, 'max_delta_step': 9}. Best is trial 2 with value: 0.511553273427471.

Best trial: 2. Best value: 0.511553:  18%|█▊        | 9/50 [01:36<06:24,  9.37s/it]

[I 2025-12-01 21:23:27,855] Trial 8 finished with value: 0.48523748395378685 and parameters: {'max_depth': 10, 'learning_rate': 0.05791128508934496, 'n_estimators': 794, 'subsample': 0.9335355260371838, 'colsample_bytree': 0.5633732244988863, 'min_child_weight': 2, 'gamma': 0.7274730939849916, 'reg_alpha': 1.1736612718996182e-07, 'reg_lambda': 1.6897651121306356e-08, 'max_delta_step': 7}. Best is trial 2 with value: 0.511553273427471.

Best trial: 2. Best value: 0.511553:  20%|██        | 10/50 [01:40<05:16,  7.91s/it]

[I 2025-12-01 21:23:32,506] Trial 4 finished with value: 0.511553273427471 and parameters: {'max_depth': 8, 'learning_rate': 0.05108201975630281, 'n_estimators': 966, 'subsample': 0.7332012097565372, 'colsample_bytree': 0.9733733537320362, 'min_child_weight': 1, 'gamma': 4.1549786141590745, 'reg_alpha': 1.378927781728769e-08, 'reg_lambda': 1.5546691399049297, 'max_delta_step': 5}. Best is trial 2 with value: 0.511553273427471.

Best trial: 2. Best value: 0.511553:  22%|██▏       | 11/50 [01:44<04:12,  6.48s/it]

[I 2025-12-01 21:23:35,741] Trial 12 pruned.

Best trial: 2. Best value: 0.511553:  24%|██▍       | 12/50 [01:50<04:11,  6.61s/it]

[I 2025-12-01 21:23:42,632] Trial 14 pruned.

Best trial: 2. Best value: 0.511553:  26%|██▌       | 13/50 [02:01<04:46,  7.74s/it]

[I 2025-12-01 21:23:52,972] Trial 15 pruned.

Best trial: 2. Best value: 0.511553:  28%|██▊       | 14/50 [02:10<04:57,  8.26s/it]

[I 2025-12-01 21:24:02,435] Trial 16 pruned.

Best trial: 10. Best value: 0.523748:  30%|███       | 15/50 [02:19<04:50,  8.29s/it]

[I 2025-12-01 21:24:10,805] Trial 10 finished with value: 0.5237483953786906 and parameters: {'max_depth': 4, 'learning_rate': 0.1988562210853981, 'n_estimators': 1486, 'subsample': 0.5896672801019047, 'colsample_bytree': 0.7440450912771261, 'min_child_weight': 1, 'gamma': 0.7490498777943255, 'reg_alpha': 1.3050193582605877e-05, 'reg_lambda': 1.2942341899034723e-06, 'max_delta_step': 5}. Best is trial 10 with value: 0.5237483953786906.

Best trial: 10. Best value: 0.523748:  32%|███▏      | 16/50 [02:40<06:52, 12.12s/it]

[I 2025-12-01 21:24:31,806] Trial 11 finished with value: 0.511553273427471 and parameters: {'max_depth': 8, 'learning_rate': 0.03759115375309561, 'n_estimators': 1080, 'subsample': 0.5030254455463112, 'colsample_bytree': 0.8713563815674389, 'min_child_weight': 1, 'gamma': 4.241476766914286, 'reg_alpha': 2.5681505078121123e-08, 'reg_lambda': 0.02002358086326897, 'max_delta_step': 10}. Best is trial 10 with value: 0.5237483953786906.

Best trial: 13. Best value: 0.578306:  34%|███▍      | 17/50 [02:43<05:14,  9.54s/it]

[I 2025-12-01 21:24:35,346] Trial 13 finished with value: 0.5783055198973043 and parameters: {'max_depth': 5, 'learning_rate': 0.2624145176021885, 'n_estimators': 1478, 'subsample': 0.5392642517811217, 'colsample_bytree': 0.9911978669238384, 'min_child_weight': 6, 'gamma': 4.464380805270843, 'reg_alpha': 0.4766664419096171, 'reg_lambda': 0.010983659387900803, 'max_delta_step': 7}. Best is trial 13 with value: 0.5783055198973043.

Best trial: 13. Best value: 0.578306:  36%|███▌      | 18/50 [02:53<05:07,  9.60s/it]

[I 2025-12-01 21:24:45,094] Trial 17 finished with value: 0.48523748395378685 and parameters: {'max_depth': 5, 'learning_rate': 0.12486312176891537, 'n_estimators': 588, 'subsample': 0.806832893493042, 'colsample_bytree': 0.9908590617711601, 'min_child_weight': 1, 'gamma': 2.2741226186079637, 'reg_alpha': 3.1955867654668953e-06, 'reg_lambda': 0.0001460894337403117, 'max_delta_step': 7}. Best is trial 13 with value: 0.5783055198973043.

Best trial: 13. Best value: 0.578306:  38%|███▊      | 19/50 [02:53<03:30,  6.80s/it]

[I 2025-12-01 21:24:45,359] Trial 20 pruned.

Best trial: 13. Best value: 0.578306:  40%|████      | 20/50 [03:05<04:06,  8.21s/it]

[I 2025-12-01 21:24:56,864] Trial 21 pruned.

Best trial: 13. Best value: 0.578306:  42%|████▏     | 21/50 [03:09<03:27,  7.14s/it]

[I 2025-12-01 21:25:01,505] Trial 19 finished with value: 0.5539152759948652 and parameters: {'max_depth': 4, 'learning_rate': 0.23841081855605578, 'n_estimators': 602, 'subsample': 0.5037650263057893, 'colsample_bytree': 0.7066364870739767, 'min_child_weight': 4, 'gamma': 2.189629163379753, 'reg_alpha': 3.603943571113653e-06, 'reg_lambda': 0.00026727956912191397, 'max_delta_step': 7}. Best is trial 13 with value: 0.5783055198973043.

Best trial: 13. Best value: 0.578306:  44%|████▍     | 22/50 [03:15<03:08,  6.74s/it]

[I 2025-12-01 21:25:07,301] Trial 23 pruned.

Best trial: 13. Best value: 0.578306:  46%|████▌     | 23/50 [03:20<02:47,  6.21s/it]

[I 2025-12-01 21:25:12,270] Trial 24 pruned.

Best trial: 13. Best value: 0.578306:  48%|████▊     | 24/50 [03:25<02:31,  5.83s/it]

[I 2025-12-01 21:25:17,237] Trial 18 finished with value: 0.5378690629011553 and parameters: {'max_depth': 4, 'learning_rate': 0.2782308477038664, 'n_estimators': 1492, 'subsample': 0.5100002728072199, 'colsample_bytree': 0.8010127856566961, 'min_child_weight': 4, 'gamma': 2.2388022423470826, 'reg_alpha': 5.601309250194746e-06, 'reg_lambda': 9.196314676194364e-05, 'max_delta_step': 0}. Best is trial 13 with value: 0.5783055198973043.

Best trial: 13. Best value: 0.578306:  50%|█████     | 25/50 [03:26<01:51,  4.46s/it]

[I 2025-12-01 21:25:18,498] Trial 26 pruned.
[I 2025-12-01 21:25:18,511] Trial 25 pruned.

Best trial: 13. Best value: 0.578306:  54%|█████▍    | 27/50 [03:30<01:12,  3.15s/it]

[I 2025-12-01 21:25:21,735] Trial 27 pruned.

Best trial: 13. Best value: 0.578306:  56%|█████▌    | 28/50 [03:39<01:43,  4.68s/it]

[I 2025-12-01 21:25:31,079] Trial 30 pruned.

Best trial: 13. Best value: 0.578306:  58%|█████▊    | 29/50 [03:46<01:50,  5.28s/it]

[I 2025-12-01 21:25:38,022] Trial 31 pruned.

Best trial: 22. Best value: 0.604621:  60%|██████    | 30/50 [03:56<02:11,  6.56s/it]

[I 2025-12-01 21:25:48,023] Trial 22 finished with value: 0.6046213093709885 and parameters: {'max_depth': 4, 'learning_rate': 0.2362658824563471, 'n_estimators': 1296, 'subsample': 0.5582720092490074, 'colsample_bytree': 0.812521601691877, 'min_child_weight': 6, 'gamma': 4.914435392567851, 'reg_alpha': 0.028539129301396952, 'reg_lambda': 1.321513614199529e-06, 'max_delta_step': 8}. Best is trial 22 with value: 0.6046213093709885.

Best trial: 22. Best value: 0.604621:  62%|██████▏   | 31/50 [04:05<02:17,  7.24s/it]

[I 2025-12-01 21:25:56,966] Trial 33 pruned.

Best trial: 22. Best value: 0.604621:  64%|██████▍   | 32/50 [04:23<03:07, 10.44s/it]

[I 2025-12-01 21:26:15,459] Trial 28 finished with value: 0.5500641848523748 and parameters: {'max_depth': 6, 'learning_rate': 0.2757298473919123, 'n_estimators': 1141, 'subsample': 0.6306054543939895, 'colsample_bytree': 0.9240210479730938, 'min_child_weight': 5, 'gamma': 2.7082961711926616, 'reg_alpha': 0.00041214516515993504, 'reg_lambda': 0.00010378586084573729, 'max_delta_step': 0}. Best is trial 22 with value: 0.6046213093709885.
[I 2025-12-01 21:26:15,470] Trial 29 finished with value: 0.5641848523748395 and parameters: {'max_depth': 6, 'learning_rate': 0.26242108043857976, 'n_estimators': 1146, 'subsample': 0.6346104265909881, 'colsample_bytree': 0.9251283388533659, 'min_child_weight': 4, 'gamma': 2.6356244393479096, 'reg_alpha': 4.891093280340867e-07, 'reg_lambda': 6.578109489683918e-05, 'max_delta_step': 0}. Best is trial 22 with value: 0.6046213093709885.

Best trial: 22. Best value: 0.604621:  68%|██████▊   | 34/50 [04:30<01:56,  7.29s/it]

[I 2025-12-01 21:26:22,324] Trial 32 pruned.

Best trial: 22. Best value: 0.604621:  70%|███████   | 35/50 [04:34<01:38,  6.55s/it]

[I 2025-12-01 21:26:26,573] Trial 37 pruned.

Best trial: 22. Best value: 0.604621:  72%|███████▏  | 36/50 [04:35<01:09,  4.99s/it]

[I 2025-12-01 21:26:27,064] Trial 36 pruned.

Best trial: 22. Best value: 0.604621:  74%|███████▍  | 37/50 [04:44<01:20,  6.18s/it]

[I 2025-12-01 21:26:36,484] Trial 39 pruned.

Best trial: 22. Best value: 0.604621:  76%|███████▌  | 38/50 [04:48<01:04,  5.38s/it]

[I 2025-12-01 21:26:39,786] Trial 38 pruned.

Best trial: 22. Best value: 0.604621:  78%|███████▊  | 39/50 [04:52<00:57,  5.24s/it]

[I 2025-12-01 21:26:44,663] Trial 40 pruned.

Best trial: 22. Best value: 0.604621:  80%|████████  | 40/50 [04:56<00:47,  4.75s/it]

[I 2025-12-01 21:26:48,222] Trial 41 pruned.

Best trial: 22. Best value: 0.604621:  82%|████████▏ | 41/50 [05:02<00:44,  4.98s/it]

[I 2025-12-01 21:26:53,741] Trial 42 pruned.

Best trial: 22. Best value: 0.604621:  84%|████████▍ | 42/50 [05:11<00:49,  6.19s/it]

[I 2025-12-01 21:27:02,829] Trial 44 pruned.

Best trial: 22. Best value: 0.604621:  86%|████████▌ | 43/50 [05:12<00:32,  4.66s/it]

[I 2025-12-01 21:27:03,867] Trial 34 finished with value: 0.5500641848523748 and parameters: {'max_depth': 5, 'learning_rate': 0.23855610757401993, 'n_estimators': 1404, 'subsample': 0.5189755335796583, 'colsample_bytree': 0.8292590433518323, 'min_child_weight': 4, 'gamma': 4.515857238908872, 'reg_alpha': 0.10585723709766509, 'reg_lambda': 0.0009475063889023399, 'max_delta_step': 7}. Best is trial 22 with value: 0.6046213093709885.

Best trial: 22. Best value: 0.604621:  88%|████████▊ | 44/50 [05:21<00:36,  6.06s/it]

[I 2025-12-01 21:27:13,224] Trial 45 pruned.

Best trial: 22. Best value: 0.604621:  90%|█████████ | 45/50 [05:25<00:26,  5.34s/it]

[I 2025-12-01 21:27:16,890] Trial 46 pruned.

Best trial: 22. Best value: 0.604621:  92%|█████████▏| 46/50 [05:29<00:20,  5.15s/it]

[I 2025-12-01 21:27:21,591] Trial 43 finished with value: 0.6046213093709885 and parameters: {'max_depth': 4, 'learning_rate': 0.17030549991617416, 'n_estimators': 677, 'subsample': 0.7711332422166591, 'colsample_bytree': 0.8357945505426455, 'min_child_weight': 7, 'gamma': 1.4966934542702126, 'reg_alpha': 3.7335014544237385e-07, 'reg_lambda': 4.587681092686321e-06, 'max_delta_step': 8}. Best is trial 22 with value: 0.6046213093709885.

Best trial: 22. Best value: 0.604621:  94%|█████████▍| 47/50 [05:30<00:11,  3.94s/it]

[I 2025-12-01 21:27:22,694] Trial 47 pruned.

Best trial: 22. Best value: 0.604621:  96%|█████████▌| 48/50 [05:31<00:05,  2.96s/it]

[I 2025-12-01 21:27:23,370] Trial 35 finished with value: 0.5500641848523748 and parameters: {'max_depth': 5, 'learning_rate': 0.2270527442191344, 'n_estimators': 1387, 'subsample': 0.6086717294208037, 'colsample_bytree': 0.9447061438741954, 'min_child_weight': 3, 'gamma': 4.480976929258394, 'reg_alpha': 0.08294570242655748, 'reg_lambda': 0.0011871272364268849, 'max_delta_step': 7}. Best is trial 22 with value: 0.6046213093709885.

Best trial: 22. Best value: 0.604621:  98%|█████████▊| 49/50 [05:32<00:02,  2.32s/it]

[I 2025-12-01 21:27:24,176] Trial 48 pruned.

Best trial: 22. Best value: 0.604621: 100%|██████████| 50/50 [05:49<00:00,  6.98s/it]

[I 2025-12-01 21:27:40,813] Trial 49 finished with value: 0.4974326059050064 and parameters: {'max_depth': 4, 'learning_rate': 0.14071634987144158, 'n_estimators': 635, 'subsample': 0.8208376856995414, 'colsample_bytree': 0.7219574584335505, 'min_child_weight': 2, 'gamma': 1.4894147834237808, 'reg_alpha': 2.2104348117164024e-07, 'reg_lambda': 2.618469402018801e-05, 'max_delta_step': 8}. Best is trial 22 with value: 0.6046213093709885.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.722080                    0.75          0.80
1     9_1         loo       0.755921                    0.65          0.60
2    19_1         loo       0.560526                    0.60          0.56
3    17_1         loo       0.604621                    0.55          0.40

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.500000               1.0               0.5        50          60
1  0.288675               0.6               0.7        50          59
2  0.188982               0.6               0.6        50          59
3  0.094491               0.6               0.5        50          60

   test_size
0         15
1         15
2         15
3         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.722080                    0.75          0.80
1     9_1         loo       0.755921                    0.65          0.60
2    19_1         loo       0.560526                    0.60          0.56
3    17_1         loo       0.604621                    0.55          0.40

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.500000               1.0               0.5        50          60
1  0.288675               0.6               0.7        50          59
2  0.188982               0.6               0.6        50          59
3  0.094491               0.6               0.5        50          60

   test_size
0         15
1         15
2         15
3         15

In [1570]:

datasets = task_hf_compensated_freq_emb_lbl_ad_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir="xgb_ad_hc_{CV_STRATEGY}_tasks/xgb_results_handcrafted_frerq_emb_compensated_ad_hc_extended_{CV_STRATEGY}_tasks",
    split_param= "diagnosis_y",
)
print(summary)
## MCI-AD vs HC -> OPTUNA + XGB

[I 2025-12-01 21:27:44,155] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.613158:   2%|▏         | 1/50 [00:19<15:56, 19.53s/it]

[I 2025-12-01 21:28:03,675] Trial 3 finished with value: 0.6131578947368421 and parameters: {'max_depth': 7, 'learning_rate': 0.047241333458605914, 'n_estimators': 415, 'subsample': 0.6624038207407852, 'colsample_bytree': 0.5873300335181135, 'min_child_weight': 6, 'gamma': 4.606761965810629, 'reg_alpha': 9.775095620235482e-06, 'reg_lambda': 0.9511910021253253, 'max_delta_step': 7}. Best is trial 3 with value: 0.6131578947368421.

Best trial: 3. Best value: 0.613158:   4%|▍         | 2/50 [00:39<15:50, 19.81s/it]

[I 2025-12-01 21:28:23,677] Trial 4 finished with value: 0.5453947368421053 and parameters: {'max_depth': 10, 'learning_rate': 0.27517376161051926, 'n_estimators': 318, 'subsample': 0.7729138999883203, 'colsample_bytree': 0.7619048419126764, 'min_child_weight': 2, 'gamma': 4.86057178576615, 'reg_alpha': 7.471998553036454e-05, 'reg_lambda': 0.21733154067635074, 'max_delta_step': 6}. Best is trial 3 with value: 0.6131578947368421.

Best trial: 3. Best value: 0.613158:   6%|▌         | 3/50 [00:46<10:53, 13.91s/it]

[I 2025-12-01 21:28:30,561] Trial 2 finished with value: 0.325 and parameters: {'max_depth': 8, 'learning_rate': 0.22965834722028866, 'n_estimators': 1148, 'subsample': 0.8380416612989017, 'colsample_bytree': 0.859586785137136, 'min_child_weight': 10, 'gamma': 2.213305165431822, 'reg_alpha': 2.7580562587758e-07, 'reg_lambda': 1.2070806424971822e-07, 'max_delta_step': 6}. Best is trial 3 with value: 0.6131578947368421.

Best trial: 3. Best value: 0.613158:   8%|▊         | 4/50 [01:02<11:22, 14.83s/it]

[I 2025-12-01 21:28:46,813] Trial 0 finished with value: 0.5578947368421052 and parameters: {'max_depth': 8, 'learning_rate': 0.021049043563889036, 'n_estimators': 1075, 'subsample': 0.8938463318334219, 'colsample_bytree': 0.6748626444497643, 'min_child_weight': 4, 'gamma': 1.7717147197684269, 'reg_alpha': 7.286179982488425e-06, 'reg_lambda': 4.030218825661547, 'max_delta_step': 1}. Best is trial 3 with value: 0.6131578947368421.

Best trial: 3. Best value: 0.613158:  10%|█         | 5/50 [01:07<08:21, 11.15s/it]

[I 2025-12-01 21:28:51,436] Trial 1 finished with value: 0.49276315789473685 and parameters: {'max_depth': 4, 'learning_rate': 0.07379366502709857, 'n_estimators': 1227, 'subsample': 0.649373319258262, 'colsample_bytree': 0.7569739567020131, 'min_child_weight': 1, 'gamma': 0.7195641658899843, 'reg_alpha': 3.790761644229692e-08, 'reg_lambda': 0.7490371049083395, 'max_delta_step': 6}. Best is trial 3 with value: 0.6131578947368421.

Best trial: 3. Best value: 0.613158:  12%|█▏        | 6/50 [01:17<08:03, 11.00s/it]

[I 2025-12-01 21:29:02,132] Trial 5 finished with value: 0.5342105263157895 and parameters: {'max_depth': 9, 'learning_rate': 0.14276575501947514, 'n_estimators': 945, 'subsample': 0.5408999721106802, 'colsample_bytree': 0.6745326764638041, 'min_child_weight': 5, 'gamma': 0.8786043550060207, 'reg_alpha': 0.0017593605105350252, 'reg_lambda': 3.301253192232628e-07, 'max_delta_step': 0}. Best is trial 3 with value: 0.6131578947368421.

Best trial: 3. Best value: 0.613158:  14%|█▍        | 7/50 [01:30<08:20, 11.64s/it]

[I 2025-12-01 21:29:15,105] Trial 6 finished with value: 0.544078947368421 and parameters: {'max_depth': 9, 'learning_rate': 0.01946589462899213, 'n_estimators': 593, 'subsample': 0.540039303331722, 'colsample_bytree': 0.5479169509411869, 'min_child_weight': 2, 'gamma': 1.5649784052082172, 'reg_alpha': 2.8143457560128263e-08, 'reg_lambda': 4.825089532712534, 'max_delta_step': 2}. Best is trial 3 with value: 0.6131578947368421.

Best trial: 7. Best value: 0.626974:  16%|█▌        | 8/50 [01:35<06:36,  9.45s/it]

[I 2025-12-01 21:29:19,870] Trial 7 finished with value: 0.6269736842105263 and parameters: {'max_depth': 4, 'learning_rate': 0.06604813278842848, 'n_estimators': 754, 'subsample': 0.9772587939470353, 'colsample_bytree': 0.9906601700237752, 'min_child_weight': 9, 'gamma': 1.121553610477567, 'reg_alpha': 1.1698817293665096e-08, 'reg_lambda': 0.0008037254144698135, 'max_delta_step': 2}. Best is trial 7 with value: 0.6269736842105263.

Best trial: 7. Best value: 0.626974:  18%|█▊        | 9/50 [01:41<05:43,  8.37s/it]

[I 2025-12-01 21:29:25,858] Trial 8 finished with value: 0.425 and parameters: {'max_depth': 8, 'learning_rate': 0.020294245303785444, 'n_estimators': 851, 'subsample': 0.5618358689379919, 'colsample_bytree': 0.662716529516787, 'min_child_weight': 8, 'gamma': 0.5627791887240868, 'reg_alpha': 2.1880637055560755e-08, 'reg_lambda': 0.048880479645291165, 'max_delta_step': 3}. Best is trial 7 with value: 0.6269736842105263.

Best trial: 7. Best value: 0.626974:  20%|██        | 10/50 [01:48<05:12,  7.81s/it]

[I 2025-12-01 21:29:32,411] Trial 11 finished with value: 0.6006578947368422 and parameters: {'max_depth': 6, 'learning_rate': 0.14506575912464983, 'n_estimators': 243, 'subsample': 0.5946926418675682, 'colsample_bytree': 0.555599833767211, 'min_child_weight': 6, 'gamma': 4.946173189866199, 'reg_alpha': 5.432617240487779, 'reg_lambda': 3.240604308867016e-07, 'max_delta_step': 7}. Best is trial 7 with value: 0.6269736842105263.

Best trial: 7. Best value: 0.626974:  22%|██▏       | 11/50 [01:53<04:35,  7.08s/it]

[I 2025-12-01 21:29:37,824] Trial 10 pruned.

Best trial: 7. Best value: 0.626974:  24%|██▍       | 12/50 [02:09<06:14,  9.87s/it]

[I 2025-12-01 21:29:54,079] Trial 9 finished with value: 0.5980263157894736 and parameters: {'max_depth': 6, 'learning_rate': 0.05432199209125298, 'n_estimators': 874, 'subsample': 0.9885867084379929, 'colsample_bytree': 0.6639794301351544, 'min_child_weight': 3, 'gamma': 1.5188361690231371, 'reg_alpha': 2.0979261796418175e-08, 'reg_lambda': 2.1172115798551188, 'max_delta_step': 5}. Best is trial 7 with value: 0.6269736842105263.

Best trial: 7. Best value: 0.626974:  26%|██▌       | 13/50 [02:14<05:10,  8.40s/it]

[I 2025-12-01 21:29:59,090] Trial 15 pruned.

Best trial: 14. Best value: 0.638158:  28%|██▊       | 14/50 [02:19<04:16,  7.12s/it]

[I 2025-12-01 21:30:03,267] Trial 14 finished with value: 0.638157894736842 and parameters: {'max_depth': 3, 'learning_rate': 0.05398769538399931, 'n_estimators': 505, 'subsample': 0.9738152675279168, 'colsample_bytree': 0.9319242520308674, 'min_child_weight': 8, 'gamma': 3.5533868749119453, 'reg_alpha': 0.011832193321419753, 'reg_lambda': 0.00019535753436344207, 'max_delta_step': 10}. Best is trial 14 with value: 0.638157894736842.

Best trial: 14. Best value: 0.638158:  30%|███       | 15/50 [02:30<04:59,  8.55s/it]

[I 2025-12-01 21:30:15,140] Trial 17 pruned.

Best trial: 14. Best value: 0.638158:  32%|███▏      | 16/50 [02:37<04:34,  8.08s/it]

[I 2025-12-01 21:30:22,116] Trial 12 finished with value: 0.6269736842105263 and parameters: {'max_depth': 9, 'learning_rate': 0.016562022497472455, 'n_estimators': 1250, 'subsample': 0.8553007896247664, 'colsample_bytree': 0.941232727866798, 'min_child_weight': 9, 'gamma': 4.796639745033731, 'reg_alpha': 0.0018683128641189177, 'reg_lambda': 0.03928008878134075, 'max_delta_step': 6}. Best is trial 14 with value: 0.638157894736842.

Best trial: 13. Best value: 0.639474:  34%|███▍      | 17/50 [02:52<05:33, 10.11s/it]

[I 2025-12-01 21:30:36,945] Trial 13 finished with value: 0.6394736842105263 and parameters: {'max_depth': 3, 'learning_rate': 0.04685340481254726, 'n_estimators': 1456, 'subsample': 0.9920203443087655, 'colsample_bytree': 0.9413958088279243, 'min_child_weight': 9, 'gamma': 3.287241310533764, 'reg_alpha': 0.015163425310335703, 'reg_lambda': 0.00016469485192630698, 'max_delta_step': 9}. Best is trial 13 with value: 0.6394736842105263.

Best trial: 18. Best value: 0.650658:  36%|███▌      | 18/50 [03:03<05:31, 10.37s/it]

[I 2025-12-01 21:30:47,922] Trial 18 finished with value: 0.6506578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.03310783640907303, 'n_estimators': 646, 'subsample': 0.9206940547619996, 'colsample_bytree': 0.8433986087845482, 'min_child_weight': 8, 'gamma': 3.301328065631488, 'reg_alpha': 0.14277013348240009, 'reg_lambda': 0.0019378671032998878, 'max_delta_step': 4}. Best is trial 18 with value: 0.6506578947368421.

Best trial: 18. Best value: 0.650658:  38%|███▊      | 19/50 [03:11<05:00,  9.70s/it]

[I 2025-12-01 21:30:56,051] Trial 19 finished with value: 0.6506578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.033823430688379376, 'n_estimators': 655, 'subsample': 0.9051341431731402, 'colsample_bytree': 0.8257457714940157, 'min_child_weight': 7, 'gamma': 3.3586999873901777, 'reg_alpha': 0.4281640112480137, 'reg_lambda': 8.59297934555092e-06, 'max_delta_step': 4}. Best is trial 18 with value: 0.6506578947368421.

Best trial: 18. Best value: 0.650658:  40%|████      | 20/50 [03:23<05:07, 10.26s/it]

[I 2025-12-01 21:31:07,585] Trial 16 finished with value: 0.6243421052631579 and parameters: {'max_depth': 5, 'learning_rate': 0.010138170042726359, 'n_estimators': 1486, 'subsample': 0.7410816008249305, 'colsample_bytree': 0.5004107326693625, 'min_child_weight': 7, 'gamma': 3.4751444302882843, 'reg_alpha': 1.5746698451862716e-06, 'reg_lambda': 0.00037530200162374735, 'max_delta_step': 9}. Best is trial 18 with value: 0.6506578947368421.

Best trial: 18. Best value: 0.650658:  42%|████▏     | 21/50 [03:47<06:56, 14.37s/it]

[I 2025-12-01 21:31:31,568] Trial 21 finished with value: 0.6243421052631579 and parameters: {'max_depth': 5, 'learning_rate': 0.010213985370886886, 'n_estimators': 715, 'subsample': 0.9054936983362768, 'colsample_bytree': 0.8187282307312759, 'min_child_weight': 7, 'gamma': 2.8350824732079816, 'reg_alpha': 1.385924068599274, 'reg_lambda': 6.4405736147268364e-06, 'max_delta_step': 4}. Best is trial 18 with value: 0.6506578947368421.

Best trial: 18. Best value: 0.650658:  44%|████▍     | 22/50 [03:50<05:07, 10.98s/it]

[I 2025-12-01 21:31:34,642] Trial 22 finished with value: 0.6118421052631579 and parameters: {'max_depth': 5, 'learning_rate': 0.011049334916420853, 'n_estimators': 657, 'subsample': 0.9032121141392315, 'colsample_bytree': 0.833566223528723, 'min_child_weight': 7, 'gamma': 4.061073210294376, 'reg_alpha': 3.309008526812959, 'reg_lambda': 6.825476401685321e-06, 'max_delta_step': 4}. Best is trial 18 with value: 0.6506578947368421.

Best trial: 18. Best value: 0.650658:  46%|████▌     | 23/50 [03:54<04:02,  8.98s/it]

[I 2025-12-01 21:31:38,959] Trial 23 finished with value: 0.6243421052631579 and parameters: {'max_depth': 5, 'learning_rate': 0.03195902493777327, 'n_estimators': 630, 'subsample': 0.9152067112312738, 'colsample_bytree': 0.8214936657491226, 'min_child_weight': 7, 'gamma': 4.059004631093879, 'reg_alpha': 1.127778998715727, 'reg_lambda': 4.249183101082813e-06, 'max_delta_step': 4}. Best is trial 18 with value: 0.6506578947368421.

Best trial: 18. Best value: 0.650658:  48%|████▊     | 24/50 [03:58<03:14,  7.48s/it]

[I 2025-12-01 21:31:42,934] Trial 20 finished with value: 0.6243421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.03384911356310799, 'n_estimators': 1495, 'subsample': 0.9198673149694594, 'colsample_bytree': 0.8224507731783199, 'min_child_weight': 7, 'gamma': 3.380100597354724, 'reg_alpha': 0.17006281976298046, 'reg_lambda': 2.547822191975178e-06, 'max_delta_step': 9}. Best is trial 18 with value: 0.6506578947368421.

Best trial: 18. Best value: 0.650658:  50%|█████     | 25/50 [04:22<05:09, 12.38s/it]

[I 2025-12-01 21:32:06,739] Trial 24 finished with value: 0.6243421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.03181315909997669, 'n_estimators': 657, 'subsample': 0.9204594040988655, 'colsample_bytree': 0.8261350446592419, 'min_child_weight': 7, 'gamma': 4.262182529213291, 'reg_alpha': 0.32744289415213734, 'reg_lambda': 8.808787214550248e-06, 'max_delta_step': 4}. Best is trial 18 with value: 0.6506578947368421.

Best trial: 18. Best value: 0.650658:  52%|█████▏    | 26/50 [04:30<04:26, 11.09s/it]

[I 2025-12-01 21:32:14,842] Trial 28 pruned.

Best trial: 25. Best value: 0.651974:  54%|█████▍    | 27/50 [04:38<03:54, 10.20s/it]

[I 2025-12-01 21:32:22,967] Trial 25 finished with value: 0.6519736842105264 and parameters: {'max_depth': 3, 'learning_rate': 0.0333385022163895, 'n_estimators': 1031, 'subsample': 0.9338023554307151, 'colsample_bytree': 0.8798308727261404, 'min_child_weight': 9, 'gamma': 2.804498006203403, 'reg_alpha': 0.4175879576381184, 'reg_lambda': 0.0033671724510357264, 'max_delta_step': 8}. Best is trial 25 with value: 0.6519736842105264.

Best trial: 25. Best value: 0.651974:  56%|█████▌    | 28/50 [04:40<02:45,  7.53s/it]

[I 2025-12-01 21:32:24,223] Trial 26 finished with value: 0.6519736842105264 and parameters: {'max_depth': 3, 'learning_rate': 0.035312826897897893, 'n_estimators': 989, 'subsample': 0.8163399049068215, 'colsample_bytree': 0.8769165029222028, 'min_child_weight': 9, 'gamma': 2.642864759643339, 'reg_alpha': 0.18254086540222747, 'reg_lambda': 1.0165833566164456e-08, 'max_delta_step': 8}. Best is trial 25 with value: 0.6519736842105264.

Best trial: 25. Best value: 0.651974:  58%|█████▊    | 29/50 [04:42<02:08,  6.13s/it]

[I 2025-12-01 21:32:27,125] Trial 27 finished with value: 0.6394736842105263 and parameters: {'max_depth': 3, 'learning_rate': 0.03714074965976034, 'n_estimators': 935, 'subsample': 0.8338743594413173, 'colsample_bytree': 0.8811869496986726, 'min_child_weight': 9, 'gamma': 2.6649013919470415, 'reg_alpha': 0.17513059465631706, 'reg_lambda': 1.1056878328313996e-08, 'max_delta_step': 8}. Best is trial 25 with value: 0.6519736842105264.

Best trial: 25. Best value: 0.651974:  60%|██████    | 30/50 [04:46<01:48,  5.43s/it]

[I 2025-12-01 21:32:30,939] Trial 30 pruned.

Best trial: 25. Best value: 0.651974:  62%|██████▏   | 31/50 [04:48<01:21,  4.31s/it]

[I 2025-12-01 21:32:32,622] Trial 31 pruned.

Best trial: 25. Best value: 0.651974:  64%|██████▍   | 32/50 [04:51<01:10,  3.92s/it]

[I 2025-12-01 21:32:35,618] Trial 32 pruned.

Best trial: 25. Best value: 0.651974:  66%|██████▌   | 33/50 [04:53<00:56,  3.30s/it]

[I 2025-12-01 21:32:37,482] Trial 29 pruned.

Best trial: 25. Best value: 0.651974:  68%|██████▊   | 34/50 [04:58<00:59,  3.71s/it]

[I 2025-12-01 21:32:42,166] Trial 34 pruned.

Best trial: 25. Best value: 0.651974:  70%|███████   | 35/50 [05:11<01:37,  6.51s/it]

[I 2025-12-01 21:32:55,197] Trial 33 pruned.

Best trial: 25. Best value: 0.651974:  72%|███████▏  | 36/50 [05:46<03:32, 15.17s/it]

[I 2025-12-01 21:33:30,551] Trial 35 finished with value: 0.6394736842105263 and parameters: {'max_depth': 3, 'learning_rate': 0.040203961345504524, 'n_estimators': 1167, 'subsample': 0.8731528588942427, 'colsample_bytree': 0.7314073884001713, 'min_child_weight': 8, 'gamma': 0.16448288710466752, 'reg_alpha': 0.06639522136423934, 'reg_lambda': 4.6051373362837584e-08, 'max_delta_step': 5}. Best is trial 25 with value: 0.6519736842105264.

Best trial: 25. Best value: 0.651974:  74%|███████▍  | 37/50 [05:52<02:43, 12.58s/it]

[I 2025-12-01 21:33:37,115] Trial 37 finished with value: 0.6256578947368421 and parameters: {'max_depth': 4, 'learning_rate': 0.0708062778040813, 'n_estimators': 1180, 'subsample': 0.9501518938705604, 'colsample_bytree': 0.7208698496895017, 'min_child_weight': 8, 'gamma': 3.753966339557727, 'reg_alpha': 0.03176935285756337, 'reg_lambda': 4.880294744039144e-08, 'max_delta_step': 5}. Best is trial 25 with value: 0.6519736842105264.

Best trial: 25. Best value: 0.651974:  76%|███████▌  | 38/50 [05:54<01:50,  9.24s/it]

[I 2025-12-01 21:33:38,548] Trial 36 finished with value: 0.6256578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.01586356665570064, 'n_estimators': 1174, 'subsample': 0.871803397870704, 'colsample_bytree': 0.9032496619566425, 'min_child_weight': 8, 'gamma': 2.9489449216994315, 'reg_alpha': 0.05806508575173023, 'reg_lambda': 5.230303942220697e-08, 'max_delta_step': 5}. Best is trial 25 with value: 0.6519736842105264.

Best trial: 25. Best value: 0.651974:  78%|███████▊  | 39/50 [06:00<01:32,  8.40s/it]

[I 2025-12-01 21:33:44,994] Trial 39 pruned.

Best trial: 25. Best value: 0.651974:  80%|████████  | 40/50 [06:05<01:12,  7.29s/it]

[I 2025-12-01 21:33:49,694] Trial 42 pruned.

Best trial: 25. Best value: 0.651974:  82%|████████▏ | 41/50 [06:07<00:50,  5.66s/it]

[I 2025-12-01 21:33:51,561] Trial 38 finished with value: 0.638157894736842 and parameters: {'max_depth': 3, 'learning_rate': 0.040945624261201, 'n_estimators': 1200, 'subsample': 0.9442213617403296, 'colsample_bytree': 0.7182841170432586, 'min_child_weight': 8, 'gamma': 3.7180151908145587, 'reg_alpha': 0.0726741449438215, 'reg_lambda': 4.6870503396100585e-08, 'max_delta_step': 5}. Best is trial 25 with value: 0.6519736842105264.

Best trial: 25. Best value: 0.651974:  84%|████████▍ | 42/50 [06:21<01:04,  8.12s/it]

[I 2025-12-01 21:34:05,420] Trial 40 finished with value: 0.6243421052631579 and parameters: {'max_depth': 5, 'learning_rate': 0.04314745868093519, 'n_estimators': 489, 'subsample': 0.8814627568924257, 'colsample_bytree': 0.8562221180491587, 'min_child_weight': 6, 'gamma': 3.01019926516948, 'reg_alpha': 1.102990848055204, 'reg_lambda': 1.4835658666372474e-06, 'max_delta_step': 7}. Best is trial 25 with value: 0.6519736842105264.

Best trial: 25. Best value: 0.651974:  86%|████████▌ | 43/50 [06:28<00:54,  7.76s/it]

[I 2025-12-01 21:34:12,337] Trial 43 finished with value: 0.6118421052631579 and parameters: {'max_depth': 4, 'learning_rate': 0.040098651759031656, 'n_estimators': 361, 'subsample': 0.8304453665104956, 'colsample_bytree': 0.9704402366633172, 'min_child_weight': 6, 'gamma': 1.753274808565437, 'reg_alpha': 0.0002799065577554284, 'reg_lambda': 0.0006052020334551425, 'max_delta_step': 0}. Best is trial 25 with value: 0.6519736842105264.

Best trial: 25. Best value: 0.651974:  88%|████████▊ | 44/50 [06:35<00:45,  7.63s/it]

[I 2025-12-01 21:34:19,679] Trial 41 finished with value: 0.6243421052631579 and parameters: {'max_depth': 5, 'learning_rate': 0.04267767110178493, 'n_estimators': 818, 'subsample': 0.7420652880568411, 'colsample_bytree': 0.8572721423405574, 'min_child_weight': 6, 'gamma': 3.105399401540467, 'reg_alpha': 1.0894757997947369, 'reg_lambda': 8.234145957014474e-07, 'max_delta_step': 7}. Best is trial 25 with value: 0.6519736842105264.

Best trial: 44. Best value: 0.664474:  90%|█████████ | 45/50 [07:11<01:20, 16.03s/it]

[I 2025-12-01 21:34:55,304] Trial 44 finished with value: 0.6644736842105263 and parameters: {'max_depth': 3, 'learning_rate': 0.04608642440977391, 'n_estimators': 1399, 'subsample': 0.9984129724160121, 'colsample_bytree': 0.9534793500701807, 'min_child_weight': 9, 'gamma': 3.1501766459734513, 'reg_alpha': 0.008123706278382142, 'reg_lambda': 0.0007058905581700445, 'max_delta_step': 9}. Best is trial 44 with value: 0.6644736842105263.

Best trial: 44. Best value: 0.664474:  92%|█████████▏| 46/50 [07:24<01:00, 15.20s/it]

[I 2025-12-01 21:35:08,552] Trial 45 finished with value: 0.6519736842105264 and parameters: {'max_depth': 3, 'learning_rate': 0.08631919049216197, 'n_estimators': 1379, 'subsample': 0.986186841174791, 'colsample_bytree': 0.95534372507757, 'min_child_weight': 9, 'gamma': 3.11730670113526, 'reg_alpha': 0.005897285883752677, 'reg_lambda': 0.0011381883214254811, 'max_delta_step': 9}. Best is trial 44 with value: 0.6644736842105263.

Best trial: 44. Best value: 0.664474:  94%|█████████▍| 47/50 [07:32<00:39, 13.14s/it]

[I 2025-12-01 21:35:16,892] Trial 46 finished with value: 0.6394736842105263 and parameters: {'max_depth': 3, 'learning_rate': 0.028931837369617155, 'n_estimators': 1391, 'subsample': 0.9994147939107407, 'colsample_bytree': 0.9606997613126818, 'min_child_weight': 9, 'gamma': 3.1551645032870894, 'reg_alpha': 0.00696668093703756, 'reg_lambda': 0.01099469737428932, 'max_delta_step': 9}. Best is trial 44 with value: 0.6644736842105263.

Best trial: 44. Best value: 0.664474:  96%|█████████▌| 48/50 [07:35<00:20, 10.15s/it]

[I 2025-12-01 21:35:20,064] Trial 47 finished with value: 0.6131578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.05767108742810758, 'n_estimators': 1336, 'subsample': 0.9978808012462326, 'colsample_bytree': 0.9719694065932288, 'min_child_weight': 9, 'gamma': 2.5877048890109253, 'reg_alpha': 0.0067312873075771815, 'reg_lambda': 0.009291195319293441, 'max_delta_step': 9}. Best is trial 44 with value: 0.6644736842105263.

Best trial: 44. Best value: 0.664474:  98%|█████████▊| 49/50 [07:56<00:13, 13.34s/it]

[I 2025-12-01 21:35:40,862] Trial 48 finished with value: 0.6131578947368421 and parameters: {'max_depth': 10, 'learning_rate': 0.028503526400273753, 'n_estimators': 1362, 'subsample': 0.9965526838376785, 'colsample_bytree': 0.9720717897419722, 'min_child_weight': 9, 'gamma': 3.1330105873405962, 'reg_alpha': 0.0049111038526569156, 'reg_lambda': 0.01513880058865754, 'max_delta_step': 6}. Best is trial 44 with value: 0.6644736842105263.

Best trial: 44. Best value: 0.664474: 100%|██████████| 50/50 [08:02<00:00,  9.64s/it]

[I 2025-12-01 21:35:46,324] Trial 49 finished with value: 0.6519736842105264 and parameters: {'max_depth': 10, 'learning_rate': 0.08949214383617726, 'n_estimators': 1313, 'subsample': 0.99914387856775, 'colsample_bytree': 0.9844414992975723, 'min_child_weight': 9, 'gamma': 2.5125003006854287, 'reg_alpha': 0.00394679911451784, 'reg_lambda': 0.0097202773139266, 'max_delta_step': 9}. Best is trial 44 with value: 0.6644736842105263.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 21:35:49,762] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.553915:   2%|▏         | 1/50 [00:16<13:07, 16.08s/it]

[I 2025-12-01 21:36:05,830] Trial 2 finished with value: 0.5539152759948652 and parameters: {'max_depth': 8, 'learning_rate': 0.0483882227780534, 'n_estimators': 249, 'subsample': 0.5973010430106126, 'colsample_bytree': 0.888567582136162, 'min_child_weight': 7, 'gamma': 4.009738531235777, 'reg_alpha': 7.070867695988611e-07, 'reg_lambda': 2.3070742730573497e-06, 'max_delta_step': 0}. Best is trial 2 with value: 0.5539152759948652.

Best trial: 2. Best value: 0.553915:   4%|▍         | 2/50 [00:22<08:30, 10.63s/it]

[I 2025-12-01 21:36:12,649] Trial 3 finished with value: 0.5295250320924262 and parameters: {'max_depth': 9, 'learning_rate': 0.02384258778375289, 'n_estimators': 370, 'subsample': 0.7896468552813103, 'colsample_bytree': 0.9053487959670823, 'min_child_weight': 8, 'gamma': 2.023943142485666, 'reg_alpha': 0.0025034490031207945, 'reg_lambda': 0.006163527489743689, 'max_delta_step': 6}. Best is trial 2 with value: 0.5539152759948652.

Best trial: 2. Best value: 0.553915:   6%|▌         | 3/50 [00:34<08:46, 11.20s/it]

[I 2025-12-01 21:36:24,533] Trial 0 finished with value: 0.4749679075738126 and parameters: {'max_depth': 6, 'learning_rate': 0.2318722124834335, 'n_estimators': 659, 'subsample': 0.8726398730653535, 'colsample_bytree': 0.9528450695593342, 'min_child_weight': 6, 'gamma': 3.7904765721646134, 'reg_alpha': 0.00011776056880361618, 'reg_lambda': 1.1686628719199343, 'max_delta_step': 7}. Best is trial 2 with value: 0.5539152759948652.

Best trial: 2. Best value: 0.553915:   8%|▊         | 4/50 [00:45<08:26, 11.02s/it]

[I 2025-12-01 21:36:35,267] Trial 1 finished with value: 0.5154043645699615 and parameters: {'max_depth': 7, 'learning_rate': 0.037602627114342015, 'n_estimators': 944, 'subsample': 0.77997948057203, 'colsample_bytree': 0.7416976434461635, 'min_child_weight': 8, 'gamma': 1.6828989803314043, 'reg_alpha': 0.0003021694932732423, 'reg_lambda': 8.599291144449053e-08, 'max_delta_step': 10}. Best is trial 2 with value: 0.5539152759948652.

Best trial: 2. Best value: 0.553915:  10%|█         | 5/50 [00:46<05:38,  7.53s/it]

[I 2025-12-01 21:36:36,607] Trial 4 finished with value: 0.5051347881899871 and parameters: {'max_depth': 5, 'learning_rate': 0.028412834906012083, 'n_estimators': 628, 'subsample': 0.5157910207084815, 'colsample_bytree': 0.7714122455072927, 'min_child_weight': 6, 'gamma': 1.3761986773594255, 'reg_alpha': 6.388481230474041e-05, 'reg_lambda': 6.063462130764525e-08, 'max_delta_step': 3}. Best is trial 2 with value: 0.5539152759948652.

Best trial: 2. Best value: 0.553915:  12%|█▏        | 6/50 [00:53<05:23,  7.35s/it]

[I 2025-12-01 21:36:43,626] Trial 5 finished with value: 0.527599486521181 and parameters: {'max_depth': 5, 'learning_rate': 0.28783369021416905, 'n_estimators': 583, 'subsample': 0.9901765074628763, 'colsample_bytree': 0.849423102473432, 'min_child_weight': 6, 'gamma': 3.5029367899606356, 'reg_alpha': 9.09669121140458e-07, 'reg_lambda': 1.9842109264184431e-07, 'max_delta_step': 5}. Best is trial 2 with value: 0.5539152759948652.

Best trial: 2. Best value: 0.553915:  14%|█▍        | 7/50 [01:07<06:44,  9.41s/it]

[I 2025-12-01 21:36:57,254] Trial 7 finished with value: 0.3684210526315789 and parameters: {'max_depth': 9, 'learning_rate': 0.1969021362975228, 'n_estimators': 468, 'subsample': 0.5824488235869201, 'colsample_bytree': 0.8325846079988415, 'min_child_weight': 9, 'gamma': 4.523366531740126, 'reg_alpha': 1.6795870214648463, 'reg_lambda': 0.04676651850193009, 'max_delta_step': 3}. Best is trial 2 with value: 0.5539152759948652.

Best trial: 2. Best value: 0.553915:  16%|█▌        | 8/50 [01:14<05:59,  8.56s/it]

[I 2025-12-01 21:37:04,008] Trial 9 finished with value: 0.5539152759948652 and parameters: {'max_depth': 4, 'learning_rate': 0.02951124447193895, 'n_estimators': 306, 'subsample': 0.8651228635528636, 'colsample_bytree': 0.9395433583711406, 'min_child_weight': 7, 'gamma': 1.9380451623071782, 'reg_alpha': 5.619394819730165e-07, 'reg_lambda': 0.0030946156967821335, 'max_delta_step': 4}. Best is trial 2 with value: 0.5539152759948652.

Best trial: 2. Best value: 0.553915:  18%|█▊        | 9/50 [01:17<04:45,  6.95s/it]

[I 2025-12-01 21:37:07,424] Trial 6 finished with value: 0.4711168164313222 and parameters: {'max_depth': 5, 'learning_rate': 0.05421346139851204, 'n_estimators': 672, 'subsample': 0.5250522976303025, 'colsample_bytree': 0.7992686807853031, 'min_child_weight': 2, 'gamma': 2.013997219598227, 'reg_alpha': 8.713383604196659e-07, 'reg_lambda': 0.5701030391847498, 'max_delta_step': 1}. Best is trial 2 with value: 0.5539152759948652.

Best trial: 2. Best value: 0.553915:  20%|██        | 10/50 [01:31<06:03,  9.08s/it]

[I 2025-12-01 21:37:21,256] Trial 10 finished with value: 0.45892169448010267 and parameters: {'max_depth': 4, 'learning_rate': 0.03192210854264019, 'n_estimators': 285, 'subsample': 0.9224582584881762, 'colsample_bytree': 0.6669916315328548, 'min_child_weight': 3, 'gamma': 2.1161849753208104, 'reg_alpha': 0.0008496958763545875, 'reg_lambda': 1.0992976763601668e-05, 'max_delta_step': 0}. Best is trial 2 with value: 0.5539152759948652.

Best trial: 2. Best value: 0.553915:  22%|██▏       | 11/50 [01:32<04:17,  6.59s/it]

[I 2025-12-01 21:37:22,207] Trial 11 pruned.

Best trial: 2. Best value: 0.553915:  24%|██▍       | 12/50 [01:35<03:26,  5.43s/it]

[I 2025-12-01 21:37:24,966] Trial 8 pruned.

Best trial: 2. Best value: 0.553915:  26%|██▌       | 13/50 [01:39<03:12,  5.21s/it]

[I 2025-12-01 21:37:29,689] Trial 12 finished with value: 0.45378690629011553 and parameters: {'max_depth': 7, 'learning_rate': 0.01663877640899798, 'n_estimators': 480, 'subsample': 0.5332489445308488, 'colsample_bytree': 0.8668174298846082, 'min_child_weight': 7, 'gamma': 2.3430301169181167, 'reg_alpha': 0.13349935673541602, 'reg_lambda': 2.7510731434193212e-08, 'max_delta_step': 3}. Best is trial 2 with value: 0.5539152759948652.

Best trial: 2. Best value: 0.553915:  30%|███       | 15/50 [01:42<01:49,  3.14s/it]

[I 2025-12-01 21:37:32,295] Trial 16 pruned.
[I 2025-12-01 21:37:32,454] Trial 14 pruned.

Best trial: 2. Best value: 0.553915:  32%|███▏      | 16/50 [01:44<01:32,  2.73s/it]

[I 2025-12-01 21:37:34,224] Trial 13 pruned.

Best trial: 2. Best value: 0.553915:  34%|███▍      | 17/50 [01:52<02:19,  4.23s/it]

[I 2025-12-01 21:37:41,959] Trial 18 pruned.

Best trial: 2. Best value: 0.553915:  36%|███▌      | 18/50 [01:55<02:05,  3.94s/it]

[I 2025-12-01 21:37:45,208] Trial 17 pruned.

Best trial: 2. Best value: 0.553915:  38%|███▊      | 19/50 [01:55<01:29,  2.87s/it]

[I 2025-12-01 21:37:45,608] Trial 15 finished with value: 0.5154043645699615 and parameters: {'max_depth': 3, 'learning_rate': 0.010800732619022993, 'n_estimators': 200, 'subsample': 0.6693517528290818, 'colsample_bytree': 0.989375352662617, 'min_child_weight': 5, 'gamma': 0.3583344064999099, 'reg_alpha': 1.882237062031774e-08, 'reg_lambda': 0.00013774208163898192, 'max_delta_step': 1}. Best is trial 2 with value: 0.5539152759948652.

Best trial: 2. Best value: 0.553915:  40%|████      | 20/50 [01:57<01:11,  2.40s/it]

[I 2025-12-01 21:37:46,887] Trial 19 finished with value: 0.5417201540436457 and parameters: {'max_depth': 8, 'learning_rate': 0.07949713319213561, 'n_estimators': 201, 'subsample': 0.7082608065559606, 'colsample_bytree': 0.9185716803842598, 'min_child_weight': 8, 'gamma': 4.823407000066936, 'reg_alpha': 9.596003194136039e-06, 'reg_lambda': 2.4676172486754484e-06, 'max_delta_step': 5}. Best is trial 2 with value: 0.5539152759948652.

Best trial: 2. Best value: 0.553915:  42%|████▏     | 21/50 [02:07<02:15,  4.67s/it]

[I 2025-12-01 21:37:56,853] Trial 23 pruned.

Best trial: 21. Best value: 0.606547:  44%|████▍     | 22/50 [02:09<01:50,  3.93s/it]

[I 2025-12-01 21:37:59,075] Trial 21 finished with value: 0.6065468549422337 and parameters: {'max_depth': 8, 'learning_rate': 0.06369005636793396, 'n_estimators': 223, 'subsample': 0.9014044607006318, 'colsample_bytree': 0.8807695554506716, 'min_child_weight': 8, 'gamma': 2.7842815103916587, 'reg_alpha': 5.982397566542724e-06, 'reg_lambda': 0.0016720589484435892, 'max_delta_step': 0}. Best is trial 21 with value: 0.6065468549422337.

Best trial: 21. Best value: 0.606547:  46%|████▌     | 23/50 [02:10<01:22,  3.05s/it]

[I 2025-12-01 21:38:00,048] Trial 24 pruned.

Best trial: 21. Best value: 0.606547:  48%|████▊     | 24/50 [02:13<01:18,  3.00s/it]

[I 2025-12-01 21:38:02,935] Trial 25 pruned.

Best trial: 21. Best value: 0.606547:  50%|█████     | 25/50 [02:13<00:55,  2.22s/it]

[I 2025-12-01 21:38:03,341] Trial 26 pruned.

Best trial: 21. Best value: 0.606547:  52%|█████▏    | 26/50 [02:30<02:41,  6.73s/it]

[I 2025-12-01 21:38:20,579] Trial 20 finished with value: 0.5558408215661104 and parameters: {'max_depth': 8, 'learning_rate': 0.06506639768339811, 'n_estimators': 785, 'subsample': 0.723094150584165, 'colsample_bytree': 0.9221882920058282, 'min_child_weight': 8, 'gamma': 4.100235552212846, 'reg_alpha': 5.5745908547756035e-06, 'reg_lambda': 0.001296057089552182, 'max_delta_step': 5}. Best is trial 21 with value: 0.6065468549422337.

Best trial: 21. Best value: 0.606547:  54%|█████▍    | 27/50 [02:33<02:09,  5.63s/it]

[I 2025-12-01 21:38:23,645] Trial 27 finished with value: 0.5539152759948652 and parameters: {'max_depth': 9, 'learning_rate': 0.06104259262080324, 'n_estimators': 347, 'subsample': 0.8392592436052442, 'colsample_bytree': 0.8064312708510746, 'min_child_weight': 7, 'gamma': 4.157891064947362, 'reg_alpha': 2.760619669843306e-07, 'reg_lambda': 0.007435413022081246, 'max_delta_step': 2}. Best is trial 21 with value: 0.6065468549422337.

Best trial: 21. Best value: 0.606547:  56%|█████▌    | 28/50 [02:34<01:29,  4.07s/it]

[I 2025-12-01 21:38:24,096] Trial 22 finished with value: 0.5905006418485237 and parameters: {'max_depth': 8, 'learning_rate': 0.0632593234345349, 'n_estimators': 821, 'subsample': 0.9248116078221249, 'colsample_bytree': 0.5949157827903975, 'min_child_weight': 8, 'gamma': 2.777783726628688, 'reg_alpha': 6.9654624792420714e-06, 'reg_lambda': 0.0011368455903972535, 'max_delta_step': 5}. Best is trial 21 with value: 0.6065468549422337.

Best trial: 21. Best value: 0.606547:  58%|█████▊    | 29/50 [02:37<01:17,  3.70s/it]

[I 2025-12-01 21:38:26,936] Trial 29 pruned.

Best trial: 21. Best value: 0.606547:  60%|██████    | 30/50 [02:40<01:10,  3.54s/it]

[I 2025-12-01 21:38:30,101] Trial 30 pruned.

Best trial: 21. Best value: 0.606547:  62%|██████▏   | 31/50 [02:41<00:55,  2.93s/it]

[I 2025-12-01 21:38:31,597] Trial 31 pruned.

Best trial: 21. Best value: 0.606547:  64%|██████▍   | 32/50 [02:43<00:44,  2.46s/it]

[I 2025-12-01 21:38:32,958] Trial 28 finished with value: 0.5397946084724006 and parameters: {'max_depth': 4, 'learning_rate': 0.04561173288068272, 'n_estimators': 541, 'subsample': 0.8300511928354914, 'colsample_bytree': 0.9613492274498643, 'min_child_weight': 9, 'gamma': 4.241912991578325, 'reg_alpha': 2.7500601689810136e-05, 'reg_lambda': 0.014989307205122829, 'max_delta_step': 2}. Best is trial 21 with value: 0.6065468549422337.

Best trial: 21. Best value: 0.606547:  66%|██████▌   | 33/50 [03:18<03:27, 12.21s/it]

[I 2025-12-01 21:39:07,920] Trial 33 pruned.

Best trial: 21. Best value: 0.606547:  68%|██████▊   | 34/50 [03:29<03:13, 12.06s/it]

[I 2025-12-01 21:39:19,651] Trial 34 finished with value: 0.5661103979460848 and parameters: {'max_depth': 8, 'learning_rate': 0.07222957891278416, 'n_estimators': 926, 'subsample': 0.9091325870011601, 'colsample_bytree': 0.9654281259845147, 'min_child_weight': 8, 'gamma': 3.544471960278411, 'reg_alpha': 0.0002723712537384576, 'reg_lambda': 0.0003294398729067144, 'max_delta_step': 7}. Best is trial 21 with value: 0.6065468549422337.

Best trial: 21. Best value: 0.606547:  70%|███████   | 35/50 [03:30<02:07,  8.53s/it]

[I 2025-12-01 21:39:19,935] Trial 32 finished with value: 0.5397946084724006 and parameters: {'max_depth': 7, 'learning_rate': 0.20342736894798805, 'n_estimators': 1094, 'subsample': 0.8210041498444641, 'colsample_bytree': 0.6295492150160796, 'min_child_weight': 9, 'gamma': 3.5091900213202862, 'reg_alpha': 0.0020664460603113596, 'reg_lambda': 9.454565391845998, 'max_delta_step': 7}. Best is trial 21 with value: 0.6065468549422337.

Best trial: 35. Best value: 0.618742:  72%|███████▏  | 36/50 [03:30<01:25,  6.14s/it]

[I 2025-12-01 21:39:20,493] Trial 35 finished with value: 0.6187419768934532 and parameters: {'max_depth': 6, 'learning_rate': 0.06642260048067382, 'n_estimators': 914, 'subsample': 0.8980539211746384, 'colsample_bytree': 0.833098801231603, 'min_child_weight': 8, 'gamma': 3.5995545039785926, 'reg_alpha': 0.0002673964340832404, 'reg_lambda': 0.00039400898677332586, 'max_delta_step': 6}. Best is trial 35 with value: 0.6187419768934532.

Best trial: 35. Best value: 0.618742:  74%|███████▍  | 37/50 [04:10<03:30, 16.18s/it]

[I 2025-12-01 21:40:00,093] Trial 36 finished with value: 0.5924261874197689 and parameters: {'max_depth': 8, 'learning_rate': 0.07189595626485917, 'n_estimators': 1038, 'subsample': 0.9058002137843868, 'colsample_bytree': 0.8887173762390084, 'min_child_weight': 8, 'gamma': 3.6499587259894337, 'reg_alpha': 2.3103419515757532e-06, 'reg_lambda': 0.0005888268434504286, 'max_delta_step': 6}. Best is trial 35 with value: 0.6187419768934532.

Best trial: 35. Best value: 0.618742:  76%|███████▌  | 38/50 [04:14<02:31, 12.63s/it]

[I 2025-12-01 21:40:04,443] Trial 37 finished with value: 0.5558408215661104 and parameters: {'max_depth': 6, 'learning_rate': 0.07228837122113262, 'n_estimators': 884, 'subsample': 0.8942820868084569, 'colsample_bytree': 0.9591531294371551, 'min_child_weight': 8, 'gamma': 3.4184362493112666, 'reg_alpha': 0.0018980116595154462, 'reg_lambda': 0.0003435718551195764, 'max_delta_step': 6}. Best is trial 35 with value: 0.6187419768934532.

Best trial: 35. Best value: 0.618742:  78%|███████▊  | 39/50 [04:15<01:39,  9.09s/it]

[I 2025-12-01 21:40:05,260] Trial 39 finished with value: 0.5821566110397947 and parameters: {'max_depth': 6, 'learning_rate': 0.10142657546700572, 'n_estimators': 902, 'subsample': 0.8993781520532955, 'colsample_bytree': 0.7443228604928176, 'min_child_weight': 8, 'gamma': 2.4116894767631476, 'reg_alpha': 0.013991687145962823, 'reg_lambda': 0.0003747498040509379, 'max_delta_step': 6}. Best is trial 35 with value: 0.6187419768934532.

Best trial: 35. Best value: 0.618742:  80%|████████  | 40/50 [04:21<01:22,  8.25s/it]

[I 2025-12-01 21:40:11,544] Trial 38 finished with value: 0.5783055198973043 and parameters: {'max_depth': 6, 'learning_rate': 0.06921171772135648, 'n_estimators': 1026, 'subsample': 0.8880812534164939, 'colsample_bytree': 0.971035698305579, 'min_child_weight': 8, 'gamma': 3.7205767941698733, 'reg_alpha': 0.0004254342407820981, 'reg_lambda': 0.00031138026187733827, 'max_delta_step': 6}. Best is trial 35 with value: 0.6187419768934532.

Best trial: 35. Best value: 0.618742:  82%|████████▏ | 41/50 [04:25<01:02,  6.94s/it]

[I 2025-12-01 21:40:15,431] Trial 42 pruned.

Best trial: 35. Best value: 0.618742:  84%|████████▍ | 42/50 [04:30<00:51,  6.43s/it]

[I 2025-12-01 21:40:20,677] Trial 44 pruned.

Best trial: 35. Best value: 0.618742:  86%|████████▌ | 43/50 [04:36<00:42,  6.14s/it]

[I 2025-12-01 21:40:26,151] Trial 40 pruned.

Best trial: 35. Best value: 0.618742:  88%|████████▊ | 44/50 [04:39<00:31,  5.33s/it]

[I 2025-12-01 21:40:29,591] Trial 43 pruned.

Best trial: 35. Best value: 0.618742:  90%|█████████ | 45/50 [04:42<00:23,  4.68s/it]

[I 2025-12-01 21:40:32,748] Trial 46 pruned.

Best trial: 35. Best value: 0.618742:  92%|█████████▏| 46/50 [04:50<00:22,  5.51s/it]

[I 2025-12-01 21:40:40,194] Trial 47 pruned.

Best trial: 35. Best value: 0.618742:  94%|█████████▍| 47/50 [04:57<00:17,  5.84s/it]

[I 2025-12-01 21:40:46,808] Trial 49 pruned.

Best trial: 35. Best value: 0.618742:  96%|█████████▌| 48/50 [04:59<00:09,  4.90s/it]

[I 2025-12-01 21:40:49,519] Trial 45 pruned.

Best trial: 35. Best value: 0.618742:  98%|█████████▊| 49/50 [05:03<00:04,  4.54s/it]

[I 2025-12-01 21:40:53,207] Trial 41 finished with value: 0.527599486521181 and parameters: {'max_depth': 6, 'learning_rate': 0.09527475995213328, 'n_estimators': 1031, 'subsample': 0.9399347314467497, 'colsample_bytree': 0.7472771790911665, 'min_child_weight': 6, 'gamma': 2.9019328176692336, 'reg_alpha': 0.011652239960296747, 'reg_lambda': 4.002451687343001e-05, 'max_delta_step': 6}. Best is trial 35 with value: 0.6187419768934532.

Best trial: 35. Best value: 0.618742: 100%|██████████| 50/50 [05:20<00:00,  6.40s/it]

[I 2025-12-01 21:41:09,821] Trial 48 finished with value: 0.527599486521181 and parameters: {'max_depth': 7, 'learning_rate': 0.14552492228777897, 'n_estimators': 1193, 'subsample': 0.7937986758690685, 'colsample_bytree': 0.8523203765684245, 'min_child_weight': 8, 'gamma': 2.4753842186149515, 'reg_alpha': 0.3625305760680247, 'reg_lambda': 5.866163933791323e-05, 'max_delta_step': 6}. Best is trial 35 with value: 0.6187419768934532.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 21:41:13,252] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.35:   2%|▏         | 1/50 [00:29<24:06, 29.51s/it]

[I 2025-12-01 21:41:42,755] Trial 2 finished with value: 0.35 and parameters: {'max_depth': 3, 'learning_rate': 0.043261188523505766, 'n_estimators': 655, 'subsample': 0.5574794353288535, 'colsample_bytree': 0.6615393631831564, 'min_child_weight': 9, 'gamma': 4.129645249124826, 'reg_alpha': 4.766406148519281e-05, 'reg_lambda': 0.0004965612928357065, 'max_delta_step': 4}. Best is trial 2 with value: 0.35.

Best trial: 1. Best value: 0.559211:   4%|▍         | 2/50 [00:30<10:14, 12.80s/it]

[I 2025-12-01 21:41:43,845] Trial 1 finished with value: 0.5592105263157895 and parameters: {'max_depth': 7, 'learning_rate': 0.23339964087272036, 'n_estimators': 536, 'subsample': 0.8029031684887479, 'colsample_bytree': 0.6649389974773348, 'min_child_weight': 3, 'gamma': 3.3508131313974054, 'reg_alpha': 2.1961000801037622, 'reg_lambda': 0.0007544174999782992, 'max_delta_step': 6}. Best is trial 1 with value: 0.5592105263157895.

Best trial: 1. Best value: 0.559211:   6%|▌         | 3/50 [00:34<06:38,  8.49s/it]

[I 2025-12-01 21:41:47,213] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.019829202552967794, 'n_estimators': 740, 'subsample': 0.9147604507411407, 'colsample_bytree': 0.714916110159142, 'min_child_weight': 10, 'gamma': 3.158947060908277, 'reg_alpha': 0.011781913417868124, 'reg_lambda': 0.048505968163395696, 'max_delta_step': 0}. Best is trial 1 with value: 0.5592105263157895.
[I 2025-12-01 21:41:47,386] Trial 0 finished with value: 0.42894736842105263 and parameters: {'max_depth': 8, 'learning_rate': 0.10880704156512827, 'n_estimators': 624, 'subsample': 0.8094245810926365, 'colsample_bytree': 0.7424977657276716, 'min_child_weight': 5, 'gamma': 2.257090568339017, 'reg_alpha': 2.454597772263012, 'reg_lambda': 0.19003243001546377, 'max_delta_step': 6}. Best is trial 1 with value: 0.5592105263157895.

Best trial: 5. Best value: 0.560526:  10%|█         | 5/50 [00:55<08:18, 11.08s/it]

[I 2025-12-01 21:42:08,871] Trial 5 finished with value: 0.5605263157894737 and parameters: {'max_depth': 8, 'learning_rate': 0.07209795195691134, 'n_estimators': 587, 'subsample': 0.8667239092555118, 'colsample_bytree': 0.6321821840770051, 'min_child_weight': 7, 'gamma': 2.7062730706134763, 'reg_alpha': 2.2173499259517144e-05, 'reg_lambda': 0.0761370927312973, 'max_delta_step': 9}. Best is trial 5 with value: 0.5605263157894737.

Best trial: 5. Best value: 0.560526:  12%|█▏        | 6/50 [00:55<05:26,  7.42s/it]

[I 2025-12-01 21:42:09,199] Trial 4 finished with value: 0.40657894736842104 and parameters: {'max_depth': 7, 'learning_rate': 0.2850484844543432, 'n_estimators': 684, 'subsample': 0.6292651454579781, 'colsample_bytree': 0.5621899901767815, 'min_child_weight': 7, 'gamma': 4.193745808333146, 'reg_alpha': 2.739647672665497e-07, 'reg_lambda': 1.8426367098376236e-08, 'max_delta_step': 3}. Best is trial 5 with value: 0.5605263157894737.

Best trial: 5. Best value: 0.560526:  14%|█▍        | 7/50 [01:00<04:35,  6.40s/it]

[I 2025-12-01 21:42:13,508] Trial 7 finished with value: 0.49802631578947365 and parameters: {'max_depth': 3, 'learning_rate': 0.07720647282084472, 'n_estimators': 678, 'subsample': 0.7070387943432352, 'colsample_bytree': 0.7524994645145491, 'min_child_weight': 8, 'gamma': 2.839336575183853, 'reg_alpha': 1.0030824715319086e-05, 'reg_lambda': 3.3406816097332106e-05, 'max_delta_step': 8}. Best is trial 5 with value: 0.5605263157894737.

Best trial: 5. Best value: 0.560526:  16%|█▌        | 8/50 [01:13<05:58,  8.53s/it]

[I 2025-12-01 21:42:26,607] Trial 8 finished with value: 0.1125 and parameters: {'max_depth': 9, 'learning_rate': 0.012377073277583908, 'n_estimators': 418, 'subsample': 0.7737511122116605, 'colsample_bytree': 0.9709087936849492, 'min_child_weight': 9, 'gamma': 1.1998485982082103, 'reg_alpha': 2.4481855287608143, 'reg_lambda': 0.00016932957402713793, 'max_delta_step': 5}. Best is trial 5 with value: 0.5605263157894737.

Best trial: 5. Best value: 0.560526:  18%|█▊        | 9/50 [01:19<05:16,  7.71s/it]

[I 2025-12-01 21:42:32,515] Trial 6 finished with value: 0.44013157894736843 and parameters: {'max_depth': 8, 'learning_rate': 0.010647964939905762, 'n_estimators': 221, 'subsample': 0.7608351439252763, 'colsample_bytree': 0.8509689846055595, 'min_child_weight': 1, 'gamma': 2.34157004994457, 'reg_alpha': 1.3916114544364354e-08, 'reg_lambda': 8.431472756324568e-08, 'max_delta_step': 5}. Best is trial 5 with value: 0.5605263157894737.

Best trial: 5. Best value: 0.560526:  20%|██        | 10/50 [01:41<08:03, 12.10s/it]

[I 2025-12-01 21:42:54,431] Trial 11 finished with value: 0.3 and parameters: {'max_depth': 9, 'learning_rate': 0.015492324228971288, 'n_estimators': 633, 'subsample': 0.5423256783302967, 'colsample_bytree': 0.9665059037213961, 'min_child_weight': 9, 'gamma': 1.6140037963320464, 'reg_alpha': 3.825910506828435e-05, 'reg_lambda': 1.150879044735682e-07, 'max_delta_step': 8}. Best is trial 5 with value: 0.5605263157894737.

Best trial: 10. Best value: 0.575658:  22%|██▏       | 11/50 [01:57<08:40, 13.35s/it]

[I 2025-12-01 21:43:10,617] Trial 10 finished with value: 0.575657894736842 and parameters: {'max_depth': 7, 'learning_rate': 0.1613906751093009, 'n_estimators': 1460, 'subsample': 0.9965488774559623, 'colsample_bytree': 0.5175558067664947, 'min_child_weight': 8, 'gamma': 3.723677618342714, 'reg_alpha': 7.438444393707422e-05, 'reg_lambda': 0.14426941235067406, 'max_delta_step': 6}. Best is trial 10 with value: 0.575657894736842.

Best trial: 12. Best value: 0.586842:  24%|██▍       | 12/50 [02:18<09:53, 15.61s/it]

[I 2025-12-01 21:43:31,392] Trial 12 finished with value: 0.5868421052631578 and parameters: {'max_depth': 4, 'learning_rate': 0.1369410970603011, 'n_estimators': 1367, 'subsample': 0.8227376662856674, 'colsample_bytree': 0.7512384125041505, 'min_child_weight': 8, 'gamma': 3.1771274320423433, 'reg_alpha': 0.001253594091841592, 'reg_lambda': 0.4577566962242799, 'max_delta_step': 4}. Best is trial 12 with value: 0.5868421052631578.

Best trial: 12. Best value: 0.586842:  26%|██▌       | 13/50 [02:26<08:19, 13.50s/it]

[I 2025-12-01 21:43:40,051] Trial 9 finished with value: 0.5052631578947369 and parameters: {'max_depth': 3, 'learning_rate': 0.048674178000083834, 'n_estimators': 1433, 'subsample': 0.7100630206668019, 'colsample_bytree': 0.777547275533433, 'min_child_weight': 1, 'gamma': 1.8613362421880848, 'reg_alpha': 6.639403925196016e-08, 'reg_lambda': 0.026052829125226634, 'max_delta_step': 7}. Best is trial 12 with value: 0.5868421052631578.

Best trial: 12. Best value: 0.586842:  28%|██▊       | 14/50 [02:40<08:02, 13.41s/it]

[I 2025-12-01 21:43:53,262] Trial 16 pruned.

Best trial: 12. Best value: 0.586842:  30%|███       | 15/50 [02:40<05:36,  9.62s/it]

[I 2025-12-01 21:43:54,100] Trial 13 finished with value: 0.5467105263157894 and parameters: {'max_depth': 10, 'learning_rate': 0.036611212670375794, 'n_estimators': 1144, 'subsample': 0.9993384026975146, 'colsample_bytree': 0.5550848791344223, 'min_child_weight': 5, 'gamma': 0.29240045870424103, 'reg_alpha': 0.0022153381070671692, 'reg_lambda': 2.6685939608121885, 'max_delta_step': 10}. Best is trial 12 with value: 0.5868421052631578.

Best trial: 12. Best value: 0.586842:  32%|███▏      | 16/50 [02:50<05:32,  9.77s/it]

[I 2025-12-01 21:44:04,214] Trial 17 pruned.

Best trial: 12. Best value: 0.586842:  34%|███▍      | 17/50 [03:00<05:15,  9.57s/it]

[I 2025-12-01 21:44:13,310] Trial 14 finished with value: 0.5730263157894737 and parameters: {'max_depth': 5, 'learning_rate': 0.1392343061212204, 'n_estimators': 1438, 'subsample': 0.9814382035582288, 'colsample_bytree': 0.5018565169029201, 'min_child_weight': 6, 'gamma': 0.17261091389884342, 'reg_alpha': 0.002311179769307312, 'reg_lambda': 5.635514483528475, 'max_delta_step': 10}. Best is trial 12 with value: 0.5868421052631578.

Best trial: 12. Best value: 0.586842:  36%|███▌      | 18/50 [03:09<05:06,  9.58s/it]

[I 2025-12-01 21:44:22,918] Trial 20 pruned.

Best trial: 12. Best value: 0.586842:  38%|███▊      | 19/50 [03:17<04:39,  9.00s/it]

[I 2025-12-01 21:44:30,577] Trial 21 pruned.

Best trial: 12. Best value: 0.586842:  40%|████      | 20/50 [03:32<05:25, 10.84s/it]

[I 2025-12-01 21:44:45,709] Trial 15 finished with value: 0.4842105263157894 and parameters: {'max_depth': 5, 'learning_rate': 0.14969150870113798, 'n_estimators': 1483, 'subsample': 0.9872088618707513, 'colsample_bytree': 0.5002556012025955, 'min_child_weight': 5, 'gamma': 4.8971663408014265, 'reg_alpha': 0.012156876059036766, 'reg_lambda': 5.744464147048498, 'max_delta_step': 2}. Best is trial 12 with value: 0.5868421052631578.

Best trial: 18. Best value: 0.626974:  42%|████▏     | 21/50 [03:36<04:12,  8.69s/it]

[I 2025-12-01 21:44:49,382] Trial 18 finished with value: 0.6269736842105263 and parameters: {'max_depth': 5, 'learning_rate': 0.15769992791449636, 'n_estimators': 1168, 'subsample': 0.9077974401447232, 'colsample_bytree': 0.8828193023271952, 'min_child_weight': 7, 'gamma': 3.7839720329367688, 'reg_alpha': 0.0007136883756467834, 'reg_lambda': 0.8247373323532919, 'max_delta_step': 2}. Best is trial 18 with value: 0.6269736842105263.

Best trial: 18. Best value: 0.626974:  44%|████▍     | 22/50 [03:44<03:59,  8.57s/it]

[I 2025-12-01 21:44:57,654] Trial 23 pruned.

Best trial: 18. Best value: 0.626974:  46%|████▌     | 23/50 [03:49<03:25,  7.61s/it]

[I 2025-12-01 21:45:03,030] Trial 19 finished with value: 0.5605263157894737 and parameters: {'max_depth': 6, 'learning_rate': 0.1257468339061461, 'n_estimators': 1233, 'subsample': 0.8944938412947872, 'colsample_bytree': 0.8266476705961648, 'min_child_weight': 6, 'gamma': 4.699967904169943, 'reg_alpha': 0.11663194966878158, 'reg_lambda': 0.007719287737301028, 'max_delta_step': 1}. Best is trial 18 with value: 0.6269736842105263.

Best trial: 18. Best value: 0.626974:  48%|████▊     | 24/50 [03:55<02:59,  6.90s/it]

[I 2025-12-01 21:45:08,280] Trial 22 pruned.

Best trial: 25. Best value: 0.653289:  50%|█████     | 25/50 [04:32<06:39, 15.97s/it]

[I 2025-12-01 21:45:45,409] Trial 25 finished with value: 0.6532894736842105 and parameters: {'max_depth': 4, 'learning_rate': 0.1030280366525772, 'n_estimators': 1013, 'subsample': 0.9158737751710481, 'colsample_bytree': 0.918085553865117, 'min_child_weight': 8, 'gamma': 3.07995098304502, 'reg_alpha': 0.0002982459763271019, 'reg_lambda': 0.004790507761965354, 'max_delta_step': 3}. Best is trial 25 with value: 0.6532894736842105.

[I 2025-12-01 21:45:48,826] Trial 24 finished with value: 0.6394736842105263 and parameters: {'max_depth': 6, 'learning_rate': 0.10232938021926455, 'n_estimators': 1300, 'subsample': 0.9052426454745626, 'colsample_bytree': 0.9230817289852945, 'min_child_weight': 8, 'gamma': 3.7908102283612806, 'reg_alpha': 0.0002676881603953647, 'reg_lambda': 0.3580129265241062, 'max_delta_step': 1}. Best is trial 25 with value: 0.6532894736842105.

Best trial: 25. Best value: 0.653289:  54%|█████▍    | 27/50 [04:35<03:17,  8.60s/it]

[I 2025-12-01 21:45:49,009] Trial 26 finished with value: 0.6019736842105263 and parameters: {'max_depth': 4, 'learning_rate': 0.22174400758797752, 'n_estimators': 978, 'subsample': 0.8407135493435526, 'colsample_bytree': 0.9366678329523528, 'min_child_weight': 8, 'gamma': 3.006685983910136, 'reg_alpha': 0.00025350561214502874, 'reg_lambda': 0.3987204025531089, 'max_delta_step': 4}. Best is trial 25 with value: 0.6532894736842105.

Best trial: 25. Best value: 0.653289:  56%|█████▌    | 28/50 [04:42<02:59,  8.15s/it]

[I 2025-12-01 21:45:56,110] Trial 27 finished with value: 0.6157894736842104 and parameters: {'max_depth': 4, 'learning_rate': 0.2935940373333948, 'n_estimators': 1014, 'subsample': 0.9335732750430561, 'colsample_bytree': 0.9334721353877984, 'min_child_weight': 8, 'gamma': 3.226468204291611, 'reg_alpha': 0.00031049042168211177, 'reg_lambda': 0.0038439922519858468, 'max_delta_step': 4}. Best is trial 25 with value: 0.6532894736842105.

Best trial: 25. Best value: 0.653289:  58%|█████▊    | 29/50 [04:43<02:05,  5.98s/it]

[I 2025-12-01 21:45:57,030] Trial 29 pruned.

Best trial: 25. Best value: 0.653289:  60%|██████    | 30/50 [04:52<02:13,  6.66s/it]

[I 2025-12-01 21:46:05,293] Trial 31 pruned.

Best trial: 25. Best value: 0.653289:  62%|██████▏   | 31/50 [04:52<01:29,  4.72s/it]

[I 2025-12-01 21:46:05,491] Trial 32 pruned.

Best trial: 25. Best value: 0.653289:  64%|██████▍   | 32/50 [05:01<01:52,  6.23s/it]

[I 2025-12-01 21:46:15,245] Trial 33 pruned.

Best trial: 25. Best value: 0.653289:  66%|██████▌   | 33/50 [05:09<01:51,  6.54s/it]

[I 2025-12-01 21:46:22,498] Trial 35 pruned.

Best trial: 25. Best value: 0.653289:  68%|██████▊   | 34/50 [05:21<02:11,  8.21s/it]

[I 2025-12-01 21:46:34,595] Trial 28 finished with value: 0.6006578947368422 and parameters: {'max_depth': 4, 'learning_rate': 0.07117712758385533, 'n_estimators': 974, 'subsample': 0.8323037551987702, 'colsample_bytree': 0.9013874667888689, 'min_child_weight': 7, 'gamma': 2.970750419043124, 'reg_alpha': 0.0003957570297924903, 'reg_lambda': 0.9558141602663157, 'max_delta_step': 3}. Best is trial 25 with value: 0.6532894736842105.

Best trial: 25. Best value: 0.653289:  70%|███████   | 35/50 [05:27<01:53,  7.60s/it]

[I 2025-12-01 21:46:40,769] Trial 30 finished with value: 0.6144736842105263 and parameters: {'max_depth': 4, 'learning_rate': 0.07092255979782743, 'n_estimators': 1038, 'subsample': 0.9272094669333033, 'colsample_bytree': 0.9009414876066779, 'min_child_weight': 7, 'gamma': 4.173132703185528, 'reg_alpha': 1.8929784268853726e-06, 'reg_lambda': 0.005709283210444682, 'max_delta_step': 3}. Best is trial 25 with value: 0.6532894736842105.

Best trial: 25. Best value: 0.653289:  72%|███████▏  | 36/50 [05:36<01:51,  7.97s/it]

[I 2025-12-01 21:46:49,594] Trial 38 pruned.

Best trial: 25. Best value: 0.653289:  74%|███████▍  | 37/50 [05:38<01:20,  6.22s/it]

[I 2025-12-01 21:46:51,729] Trial 37 pruned.

Best trial: 25. Best value: 0.653289:  76%|███████▌  | 38/50 [05:41<01:04,  5.35s/it]

[I 2025-12-01 21:46:55,060] Trial 34 finished with value: 0.5355263157894736 and parameters: {'max_depth': 5, 'learning_rate': 0.293445615335005, 'n_estimators': 1043, 'subsample': 0.8528083236190714, 'colsample_bytree': 0.9424137348143343, 'min_child_weight': 9, 'gamma': 2.0529321781635854, 'reg_alpha': 0.0005396827538497888, 'reg_lambda': 0.0016279804960008123, 'max_delta_step': 3}. Best is trial 25 with value: 0.6532894736842105.

Best trial: 25. Best value: 0.653289:  78%|███████▊  | 39/50 [05:48<01:02,  5.68s/it]

[I 2025-12-01 21:47:01,515] Trial 41 pruned.

Best trial: 25. Best value: 0.653289:  80%|████████  | 40/50 [05:58<01:09,  6.94s/it]

[I 2025-12-01 21:47:11,377] Trial 42 pruned.

Best trial: 25. Best value: 0.653289:  82%|████████▏ | 41/50 [06:03<00:57,  6.36s/it]

[I 2025-12-01 21:47:16,405] Trial 36 finished with value: 0.6006578947368422 and parameters: {'max_depth': 3, 'learning_rate': 0.20532880129464295, 'n_estimators': 1099, 'subsample': 0.888284963738196, 'colsample_bytree': 0.9971371526422848, 'min_child_weight': 7, 'gamma': 2.038717038966399, 'reg_alpha': 0.00012072035333931631, 'reg_lambda': 0.00010580576518582981, 'max_delta_step': 3}. Best is trial 25 with value: 0.6532894736842105.

Best trial: 25. Best value: 0.653289:  84%|████████▍ | 42/50 [06:15<01:05,  8.13s/it]

[I 2025-12-01 21:47:28,649] Trial 39 finished with value: 0.5881578947368421 and parameters: {'max_depth': 5, 'learning_rate': 0.11276536210096462, 'n_estimators': 782, 'subsample': 0.9568181334263254, 'colsample_bytree': 0.9950290626070561, 'min_child_weight': 9, 'gamma': 3.3421503717811953, 'reg_alpha': 1.6134747142655648e-05, 'reg_lambda': 1.8099168396172177e-05, 'max_delta_step': 4}. Best is trial 25 with value: 0.6532894736842105.

Best trial: 25. Best value: 0.653289:  86%|████████▌ | 43/50 [06:17<00:44,  6.33s/it]

[I 2025-12-01 21:47:30,777] Trial 40 finished with value: 0.6394736842105263 and parameters: {'max_depth': 5, 'learning_rate': 0.2707610071807195, 'n_estimators': 790, 'subsample': 0.9511654211006283, 'colsample_bytree': 0.8024030260010113, 'min_child_weight': 8, 'gamma': 3.9342546386279573, 'reg_alpha': 1.1895883243058143e-05, 'reg_lambda': 0.08096955798801461, 'max_delta_step': 4}. Best is trial 25 with value: 0.6532894736842105.

Best trial: 25. Best value: 0.653289:  88%|████████▊ | 44/50 [06:24<00:39,  6.62s/it]

[I 2025-12-01 21:47:38,081] Trial 45 pruned.

Best trial: 25. Best value: 0.653289:  90%|█████████ | 45/50 [06:49<00:59, 11.88s/it]

[I 2025-12-01 21:48:02,250] Trial 44 finished with value: 0.6394736842105263 and parameters: {'max_depth': 4, 'learning_rate': 0.05298356237232762, 'n_estimators': 914, 'subsample': 0.9189875556785523, 'colsample_bytree': 0.8746525181244854, 'min_child_weight': 7, 'gamma': 4.043438768682071, 'reg_alpha': 3.7813372037788014e-07, 'reg_lambda': 0.0011307812799468634, 'max_delta_step': 4}. Best is trial 25 with value: 0.6532894736842105.

Best trial: 25. Best value: 0.653289:  92%|█████████▏| 46/50 [06:59<00:46, 11.61s/it]

[I 2025-12-01 21:48:13,207] Trial 43 finished with value: 0.6407894736842106 and parameters: {'max_depth': 3, 'learning_rate': 0.11832895375205668, 'n_estimators': 1360, 'subsample': 0.8014592564502732, 'colsample_bytree': 0.8734537489451061, 'min_child_weight': 8, 'gamma': 3.2334876383049225, 'reg_alpha': 4.0992955809829347e-07, 'reg_lambda': 3.426921361931792e-05, 'max_delta_step': 5}. Best is trial 25 with value: 0.6532894736842105.

Best trial: 25. Best value: 0.653289:  94%|█████████▍| 47/50 [07:00<00:25,  8.42s/it]

[I 2025-12-01 21:48:14,198] Trial 46 finished with value: 0.6394736842105263 and parameters: {'max_depth': 5, 'learning_rate': 0.24786233396010712, 'n_estimators': 934, 'subsample': 0.961382815920959, 'colsample_bytree': 0.8698950736772989, 'min_child_weight': 8, 'gamma': 3.992756835334077, 'reg_alpha': 6.321422270611237e-07, 'reg_lambda': 0.11663070075676729, 'max_delta_step': 5}. Best is trial 25 with value: 0.6532894736842105.

Best trial: 25. Best value: 0.653289:  96%|█████████▌| 48/50 [07:05<00:14,  7.17s/it]

[I 2025-12-01 21:48:18,440] Trial 47 finished with value: 0.6282894736842105 and parameters: {'max_depth': 5, 'learning_rate': 0.2525507201584866, 'n_estimators': 901, 'subsample': 0.9109197057321899, 'colsample_bytree': 0.815602868942404, 'min_child_weight': 8, 'gamma': 3.517638271787938, 'reg_alpha': 0.0066795803547900785, 'reg_lambda': 0.09591160287379992, 'max_delta_step': 6}. Best is trial 25 with value: 0.6532894736842105.

Best trial: 25. Best value: 0.653289:  98%|█████████▊| 49/50 [07:08<00:06,  6.03s/it]

[I 2025-12-01 21:48:21,823] Trial 48 finished with value: 0.5480263157894737 and parameters: {'max_depth': 5, 'learning_rate': 0.05029261139543471, 'n_estimators': 446, 'subsample': 0.7924901832977178, 'colsample_bytree': 0.8237004415836369, 'min_child_weight': 8, 'gamma': 3.551183604029669, 'reg_alpha': 1.3488869189648247e-07, 'reg_lambda': 0.11928931855710208, 'max_delta_step': 6}. Best is trial 25 with value: 0.6532894736842105.

Best trial: 25. Best value: 0.653289: 100%|██████████| 50/50 [07:33<00:00,  9.07s/it]

[I 2025-12-01 21:48:46,630] Trial 49 finished with value: 0.5368421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.04661191902149255, 'n_estimators': 1364, 'subsample': 0.7244618681471983, 'colsample_bytree': 0.8199078664511229, 'min_child_weight': 8, 'gamma': 3.5572626269986074, 'reg_alpha': 7.467579296308273e-08, 'reg_lambda': 4.826348718599693e-06, 'max_delta_step': 6}. Best is trial 25 with value: 0.6532894736842105.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 21:48:49,993] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.534018:   2%|▏         | 1/50 [00:27<22:08, 27.12s/it]

[I 2025-12-01 21:49:17,108] Trial 0 finished with value: 0.5340179717586649 and parameters: {'max_depth': 7, 'learning_rate': 0.0966492536813472, 'n_estimators': 380, 'subsample': 0.8769580099739699, 'colsample_bytree': 0.6034961620490995, 'min_child_weight': 2, 'gamma': 2.0344736785734323, 'reg_alpha': 1.7855369941678974, 'reg_lambda': 4.726706832732903e-07, 'max_delta_step': 3}. Best is trial 0 with value: 0.5340179717586649.

Best trial: 0. Best value: 0.534018:   4%|▍         | 2/50 [00:32<11:38, 14.55s/it]

[I 2025-12-01 21:49:22,864] Trial 3 finished with value: 0.42426187419768935 and parameters: {'max_depth': 7, 'learning_rate': 0.2912934628785164, 'n_estimators': 697, 'subsample': 0.933046617679079, 'colsample_bytree': 0.8423781343570234, 'min_child_weight': 7, 'gamma': 1.5216308641013865, 'reg_alpha': 4.3288114079400223e-07, 'reg_lambda': 0.06652325133110974, 'max_delta_step': 2}. Best is trial 0 with value: 0.5340179717586649.

Best trial: 2. Best value: 0.568036:   6%|▌         | 3/50 [01:00<16:13, 20.71s/it]

[I 2025-12-01 21:49:50,901] Trial 1 finished with value: 0.413992297817715 and parameters: {'max_depth': 7, 'learning_rate': 0.0337337468001065, 'n_estimators': 1383, 'subsample': 0.75842464095609, 'colsample_bytree': 0.5505418011096379, 'min_child_weight': 8, 'gamma': 3.07533409744382, 'reg_alpha': 4.577653227175535e-06, 'reg_lambda': 0.0006815893318730292, 'max_delta_step': 4}. Best is trial 0 with value: 0.5340179717586649.
[I 2025-12-01 21:49:50,916] Trial 2 finished with value: 0.5680359435173299 and parameters: {'max_depth': 7, 'learning_rate': 0.05166982443684424, 'n_estimators': 1433, 'subsample': 0.7913707267474104, 'colsample_bytree': 0.5006500986364952, 'min_child_weight': 9, 'gamma': 2.430599890446388, 'reg_alpha': 2.1540036266749142e-08, 'reg_lambda': 0.028699360264142014, 'max_delta_step': 9}. Best is trial 2 with value: 0.5680359435173299.

Best trial: 2. Best value: 0.568036:  10%|█         | 5/50 [01:15<09:51, 13.15s/it]

[I 2025-12-01 21:50:05,605] Trial 6 finished with value: 0.47304236200256744 and parameters: {'max_depth': 7, 'learning_rate': 0.024482523936486388, 'n_estimators': 287, 'subsample': 0.5552294108219424, 'colsample_bytree': 0.6631081641679327, 'min_child_weight': 6, 'gamma': 3.0214742327715727, 'reg_alpha': 1.3635569760833262e-08, 'reg_lambda': 0.0017164840705114564, 'max_delta_step': 0}. Best is trial 2 with value: 0.5680359435173299.

Best trial: 2. Best value: 0.568036:  12%|█▏        | 6/50 [01:22<08:19, 11.34s/it]

[I 2025-12-01 21:50:12,485] Trial 5 finished with value: 0.43645699614890887 and parameters: {'max_depth': 7, 'learning_rate': 0.023608222722382305, 'n_estimators': 1007, 'subsample': 0.8123426032687522, 'colsample_bytree': 0.7821377144260233, 'min_child_weight': 7, 'gamma': 4.936683234419926, 'reg_alpha': 0.05267791049823352, 'reg_lambda': 3.5030274419221635e-05, 'max_delta_step': 10}. Best is trial 2 with value: 0.5680359435173299.

Best trial: 2. Best value: 0.568036:  14%|█▍        | 7/50 [01:29<07:15, 10.13s/it]

[I 2025-12-01 21:50:19,651] Trial 4 finished with value: 0.5096277278562259 and parameters: {'max_depth': 9, 'learning_rate': 0.1936080557457181, 'n_estimators': 1062, 'subsample': 0.8244930079815798, 'colsample_bytree': 0.6281061378068209, 'min_child_weight': 1, 'gamma': 1.3560363990834812, 'reg_alpha': 3.229848973092638e-08, 'reg_lambda': 0.34439903369854963, 'max_delta_step': 5}. Best is trial 2 with value: 0.5680359435173299.

Best trial: 2. Best value: 0.568036:  16%|█▌        | 8/50 [01:39<07:05, 10.14s/it]

[I 2025-12-01 21:50:29,825] Trial 9 finished with value: 0.5096277278562259 and parameters: {'max_depth': 7, 'learning_rate': 0.1537858041828252, 'n_estimators': 273, 'subsample': 0.999262574548426, 'colsample_bytree': 0.5288446346095901, 'min_child_weight': 2, 'gamma': 2.865692876557065, 'reg_alpha': 0.005649267163744364, 'reg_lambda': 0.000700825292568348, 'max_delta_step': 10}. Best is trial 2 with value: 0.5680359435173299.

Best trial: 2. Best value: 0.568036:  18%|█▊        | 9/50 [01:45<06:04,  8.90s/it]

[I 2025-12-01 21:50:35,766] Trial 8 finished with value: 0.4056482670089859 and parameters: {'max_depth': 7, 'learning_rate': 0.010659044496688343, 'n_estimators': 704, 'subsample': 0.5660918563740074, 'colsample_bytree': 0.7283111673635361, 'min_child_weight': 7, 'gamma': 3.5516817081053835, 'reg_alpha': 0.08389136347679799, 'reg_lambda': 6.683835276816922e-08, 'max_delta_step': 8}. Best is trial 2 with value: 0.5680359435173299.

Best trial: 2. Best value: 0.568036:  20%|██        | 10/50 [02:14<09:52, 14.81s/it]

[I 2025-12-01 21:51:04,585] Trial 12 finished with value: 0.5359435173299101 and parameters: {'max_depth': 4, 'learning_rate': 0.08617833579793074, 'n_estimators': 642, 'subsample': 0.6221560499032535, 'colsample_bytree': 0.5473974887442423, 'min_child_weight': 3, 'gamma': 1.2357368177518213, 'reg_alpha': 3.8840893360423674e-07, 'reg_lambda': 0.0007125985712698379, 'max_delta_step': 0}. Best is trial 2 with value: 0.5680359435173299.

Best trial: 2. Best value: 0.568036:  22%|██▏       | 11/50 [02:15<06:56, 10.68s/it]

[I 2025-12-01 21:51:05,522] Trial 7 finished with value: 0.5622593068035944 and parameters: {'max_depth': 5, 'learning_rate': 0.02833789180370981, 'n_estimators': 1145, 'subsample': 0.9095691960608312, 'colsample_bytree': 0.6064850073784338, 'min_child_weight': 2, 'gamma': 2.540989878264996, 'reg_alpha': 1.8540366559011814, 'reg_lambda': 8.702943073388967, 'max_delta_step': 9}. Best is trial 2 with value: 0.5680359435173299.

Best trial: 2. Best value: 0.568036:  24%|██▍       | 12/50 [02:20<05:35,  8.84s/it]

[I 2025-12-01 21:51:10,025] Trial 10 pruned.

Best trial: 2. Best value: 0.568036:  26%|██▌       | 13/50 [02:24<04:41,  7.62s/it]

[I 2025-12-01 21:51:14,791] Trial 13 pruned.

Best trial: 2. Best value: 0.568036:  28%|██▊       | 14/50 [02:25<03:16,  5.47s/it]

[I 2025-12-01 21:51:15,230] Trial 14 pruned.

Best trial: 2. Best value: 0.568036:  30%|███       | 15/50 [02:27<02:40,  4.57s/it]

[I 2025-12-01 21:51:17,711] Trial 11 pruned.

Best trial: 2. Best value: 0.568036:  32%|███▏      | 16/50 [02:31<02:23,  4.22s/it]

[I 2025-12-01 21:51:21,112] Trial 15 pruned.

Best trial: 2. Best value: 0.568036:  34%|███▍      | 17/50 [02:45<03:56,  7.17s/it]

[I 2025-12-01 21:51:35,176] Trial 16 pruned.

Best trial: 2. Best value: 0.568036:  36%|███▌      | 18/50 [02:49<03:24,  6.40s/it]

[I 2025-12-01 21:51:39,782] Trial 18 pruned.

Best trial: 2. Best value: 0.568036:  38%|███▊      | 19/50 [02:56<03:19,  6.43s/it]

[I 2025-12-01 21:51:46,270] Trial 21 pruned.

Best trial: 17. Best value: 0.574454:  40%|████      | 20/50 [03:32<07:38, 15.28s/it]

[I 2025-12-01 21:52:22,217] Trial 17 finished with value: 0.5744544287548139 and parameters: {'max_depth': 9, 'learning_rate': 0.01419011453383882, 'n_estimators': 1174, 'subsample': 0.9291729535340115, 'colsample_bytree': 0.6000046680831883, 'min_child_weight': 4, 'gamma': 4.110037801356569, 'reg_alpha': 0.0022343342913749013, 'reg_lambda': 0.042975766998311425, 'max_delta_step': 9}. Best is trial 17 with value: 0.5744544287548139.

Best trial: 19. Best value: 0.602696:  42%|████▏     | 21/50 [03:36<05:50, 12.08s/it]

[I 2025-12-01 21:52:26,821] Trial 19 finished with value: 0.6026957637997432 and parameters: {'max_depth': 5, 'learning_rate': 0.01867325775180946, 'n_estimators': 1230, 'subsample': 0.9288223879646248, 'colsample_bytree': 0.5834248656831709, 'min_child_weight': 4, 'gamma': 3.9460235259304803, 'reg_alpha': 4.185378796935753, 'reg_lambda': 0.03398446210924044, 'max_delta_step': 9}. Best is trial 19 with value: 0.6026957637997432.

Best trial: 19. Best value: 0.602696:  44%|████▍     | 22/50 [03:41<04:40, 10.01s/it]

[I 2025-12-01 21:52:31,990] Trial 20 finished with value: 0.4974326059050064 and parameters: {'max_depth': 5, 'learning_rate': 0.017968133298741164, 'n_estimators': 916, 'subsample': 0.7975115027000118, 'colsample_bytree': 0.5785413564376456, 'min_child_weight': 4, 'gamma': 2.105666926079802, 'reg_alpha': 3.3636231823566476, 'reg_lambda': 0.013677572366426964, 'max_delta_step': 10}. Best is trial 19 with value: 0.6026957637997432.

Best trial: 19. Best value: 0.602696:  46%|████▌     | 23/50 [03:42<03:10,  7.06s/it]

[I 2025-12-01 21:52:32,193] Trial 22 finished with value: 0.4345314505776637 and parameters: {'max_depth': 6, 'learning_rate': 0.062055346694083004, 'n_estimators': 952, 'subsample': 0.8484377389464658, 'colsample_bytree': 0.8312083322259423, 'min_child_weight': 5, 'gamma': 1.8830690763761533, 'reg_alpha': 0.11944909049298143, 'reg_lambda': 0.37343837857377515, 'max_delta_step': 6}. Best is trial 19 with value: 0.6026957637997432.

Best trial: 19. Best value: 0.602696:  48%|████▊     | 24/50 [04:03<04:57, 11.45s/it]

[I 2025-12-01 21:52:53,860] Trial 25 pruned.

Best trial: 19. Best value: 0.602696:  50%|█████     | 25/50 [04:33<07:01, 16.86s/it]

[I 2025-12-01 21:53:23,343] Trial 23 finished with value: 0.4486521181001284 and parameters: {'max_depth': 8, 'learning_rate': 0.06929055349683469, 'n_estimators': 1305, 'subsample': 0.8543020372257204, 'colsample_bytree': 0.8655123586786972, 'min_child_weight': 5, 'gamma': 4.171738797506257, 'reg_alpha': 1.1442758563238812e-05, 'reg_lambda': 0.007149511980058022, 'max_delta_step': 6}. Best is trial 19 with value: 0.6026957637997432.

Best trial: 19. Best value: 0.602696:  52%|█████▏    | 26/50 [04:40<05:34, 13.95s/it]

[I 2025-12-01 21:53:30,498] Trial 24 finished with value: 0.5134788189987163 and parameters: {'max_depth': 6, 'learning_rate': 0.014523832686797735, 'n_estimators': 1300, 'subsample': 0.9925578871510983, 'colsample_bytree': 0.5726376936571562, 'min_child_weight': 5, 'gamma': 4.521792989629949, 'reg_alpha': 8.224628645730737e-06, 'reg_lambda': 0.007068461621992208, 'max_delta_step': 9}. Best is trial 19 with value: 0.6026957637997432.

Best trial: 19. Best value: 0.602696:  54%|█████▍    | 27/50 [04:46<04:25, 11.55s/it]

[I 2025-12-01 21:53:36,456] Trial 26 finished with value: 0.45057766367137353 and parameters: {'max_depth': 8, 'learning_rate': 0.013947129841500722, 'n_estimators': 1316, 'subsample': 0.9689965593024392, 'colsample_bytree': 0.5648767012896405, 'min_child_weight': 5, 'gamma': 4.644459189693843, 'reg_alpha': 1.120279203654245e-05, 'reg_lambda': 0.00759049601445041, 'max_delta_step': 9}. Best is trial 19 with value: 0.6026957637997432.

Best trial: 19. Best value: 0.602696:  56%|█████▌    | 28/50 [04:57<04:13, 11.52s/it]

[I 2025-12-01 21:53:47,894] Trial 30 pruned.

Best trial: 19. Best value: 0.602696:  58%|█████▊    | 29/50 [05:04<03:31, 10.09s/it]

[I 2025-12-01 21:53:54,672] Trial 31 pruned.

Best trial: 19. Best value: 0.602696:  60%|██████    | 30/50 [05:08<02:47,  8.36s/it]

[I 2025-12-01 21:53:58,991] Trial 32 pruned.

Best trial: 19. Best value: 0.602696:  62%|██████▏   | 31/50 [05:17<02:38,  8.33s/it]

[I 2025-12-01 21:54:07,247] Trial 27 finished with value: 0.5866495507060334 and parameters: {'max_depth': 10, 'learning_rate': 0.01423028128383083, 'n_estimators': 1334, 'subsample': 0.9551511147651955, 'colsample_bytree': 0.5617928335044969, 'min_child_weight': 3, 'gamma': 4.311069610778154, 'reg_alpha': 1.4959628311904716e-05, 'reg_lambda': 0.0069174214914565196, 'max_delta_step': 9}. Best is trial 19 with value: 0.6026957637997432.

Best trial: 19. Best value: 0.602696:  64%|██████▍   | 32/50 [05:36<03:29, 11.62s/it]

[I 2025-12-01 21:54:26,527] Trial 29 finished with value: 0.527599486521181 and parameters: {'max_depth': 10, 'learning_rate': 0.11541193808855918, 'n_estimators': 1122, 'subsample': 0.9464356849905943, 'colsample_bytree': 0.6406631665420668, 'min_child_weight': 3, 'gamma': 3.494002037093376, 'reg_alpha': 0.002021942379601718, 'reg_lambda': 0.16294441840677326, 'max_delta_step': 9}. Best is trial 19 with value: 0.6026957637997432.

Best trial: 28. Best value: 0.612965:  66%|██████▌   | 33/50 [05:47<03:15, 11.50s/it]

[I 2025-12-01 21:54:37,761] Trial 28 finished with value: 0.6129653401797176 and parameters: {'max_depth': 10, 'learning_rate': 0.013258948890058856, 'n_estimators': 1355, 'subsample': 0.9600648651497149, 'colsample_bytree': 0.5723660590551222, 'min_child_weight': 3, 'gamma': 4.959813407607726, 'reg_alpha': 0.00521204875097538, 'reg_lambda': 0.004370027017928907, 'max_delta_step': 9}. Best is trial 28 with value: 0.6129653401797176.

Best trial: 28. Best value: 0.612965:  68%|██████▊   | 34/50 [06:11<04:03, 15.24s/it]

[I 2025-12-01 21:55:01,716] Trial 33 finished with value: 0.5359435173299101 and parameters: {'max_depth': 3, 'learning_rate': 0.034838299464059246, 'n_estimators': 1366, 'subsample': 0.8712838718988115, 'colsample_bytree': 0.5433906274663824, 'min_child_weight': 4, 'gamma': 3.7745247503891433, 'reg_alpha': 0.0007076373359787844, 'reg_lambda': 0.12142362390407078, 'max_delta_step': 5}. Best is trial 28 with value: 0.6129653401797176.

Best trial: 28. Best value: 0.612965:  70%|███████   | 35/50 [06:38<04:41, 18.76s/it]

[I 2025-12-01 21:55:28,688] Trial 34 finished with value: 0.5481386392811296 and parameters: {'max_depth': 10, 'learning_rate': 0.010400930832608905, 'n_estimators': 1494, 'subsample': 0.9406375387365672, 'colsample_bytree': 0.5341288050707551, 'min_child_weight': 3, 'gamma': 3.848601038890572, 'reg_alpha': 1.9183930725240174e-07, 'reg_lambda': 0.002615388614500376, 'max_delta_step': 8}. Best is trial 28 with value: 0.6129653401797176.

Best trial: 28. Best value: 0.612965:  72%|███████▏  | 36/50 [06:46<03:37, 15.50s/it]

[I 2025-12-01 21:55:36,594] Trial 35 finished with value: 0.5481386392811296 and parameters: {'max_depth': 9, 'learning_rate': 0.012086521623182935, 'n_estimators': 1381, 'subsample': 0.8794600278474214, 'colsample_bytree': 0.5418953698363594, 'min_child_weight': 4, 'gamma': 4.9959666557652005, 'reg_alpha': 6.082849236235597e-07, 'reg_lambda': 0.0018009367298086217, 'max_delta_step': 8}. Best is trial 28 with value: 0.6129653401797176.

Best trial: 28. Best value: 0.612965:  74%|███████▍  | 37/50 [06:58<03:07, 14.39s/it]

[I 2025-12-01 21:55:48,397] Trial 36 finished with value: 0.5481386392811296 and parameters: {'max_depth': 10, 'learning_rate': 0.011796936805843905, 'n_estimators': 1383, 'subsample': 0.8837161029115799, 'colsample_bytree': 0.5436737350943692, 'min_child_weight': 4, 'gamma': 4.998671838354527, 'reg_alpha': 0.0006532556750801443, 'reg_lambda': 0.00202465752069373, 'max_delta_step': 8}. Best is trial 28 with value: 0.6129653401797176.

Best trial: 28. Best value: 0.612965:  76%|███████▌  | 38/50 [07:36<04:19, 21.65s/it]

[I 2025-12-01 21:56:26,987] Trial 37 finished with value: 0.5988446726572528 and parameters: {'max_depth': 10, 'learning_rate': 0.01002370775781739, 'n_estimators': 1380, 'subsample': 0.9582298554377352, 'colsample_bytree': 0.6008236220834975, 'min_child_weight': 2, 'gamma': 4.960594265042733, 'reg_alpha': 3.551667371372968e-05, 'reg_lambda': 0.0021043587471951297, 'max_delta_step': 8}. Best is trial 28 with value: 0.6129653401797176.

Best trial: 28. Best value: 0.612965:  78%|███████▊  | 39/50 [07:55<03:47, 20.66s/it]

[I 2025-12-01 21:56:45,328] Trial 39 finished with value: 0.5481386392811296 and parameters: {'max_depth': 10, 'learning_rate': 0.019167949073359142, 'n_estimators': 1198, 'subsample': 0.9666091521964011, 'colsample_bytree': 0.5799512759676625, 'min_child_weight': 2, 'gamma': 4.3724506941053844, 'reg_alpha': 4.01430522760407e-05, 'reg_lambda': 0.00019059269334812813, 'max_delta_step': 10}. Best is trial 28 with value: 0.6129653401797176.

Best trial: 28. Best value: 0.612965:  80%|████████  | 40/50 [08:01<02:44, 16.45s/it]

[I 2025-12-01 21:56:51,958] Trial 38 finished with value: 0.6110397946084724 and parameters: {'max_depth': 9, 'learning_rate': 0.012156749183284903, 'n_estimators': 1377, 'subsample': 0.9632993413850423, 'colsample_bytree': 0.6008314073769175, 'min_child_weight': 2, 'gamma': 4.855268343279892, 'reg_alpha': 2.7513673422177683e-06, 'reg_lambda': 0.0031413270290925415, 'max_delta_step': 10}. Best is trial 28 with value: 0.6129653401797176.

Best trial: 28. Best value: 0.612965:  82%|████████▏ | 41/50 [08:08<02:01, 13.52s/it]

[I 2025-12-01 21:56:58,652] Trial 40 finished with value: 0.5744544287548139 and parameters: {'max_depth': 9, 'learning_rate': 0.018125106948879838, 'n_estimators': 1188, 'subsample': 0.9776453724717871, 'colsample_bytree': 0.5905524655364981, 'min_child_weight': 2, 'gamma': 4.415377255002605, 'reg_alpha': 2.6707542620658452e-05, 'reg_lambda': 0.04451002846531633, 'max_delta_step': 10}. Best is trial 28 with value: 0.6129653401797176.

Best trial: 28. Best value: 0.612965:  84%|████████▍ | 42/50 [08:18<01:40, 12.51s/it]

[I 2025-12-01 21:57:08,763] Trial 43 pruned.

Best trial: 28. Best value: 0.612965:  86%|████████▌ | 43/50 [08:24<01:13, 10.46s/it]

[I 2025-12-01 21:57:14,459] Trial 44 pruned.

Best trial: 28. Best value: 0.612965:  88%|████████▊ | 44/50 [08:36<01:05, 10.89s/it]

[I 2025-12-01 21:57:26,358] Trial 46 pruned.

Best trial: 41. Best value: 0.663671:  90%|█████████ | 45/50 [08:53<01:04, 12.89s/it]

[I 2025-12-01 21:57:43,903] Trial 41 finished with value: 0.6636713735558408 and parameters: {'max_depth': 9, 'learning_rate': 0.01856120141320389, 'n_estimators': 1027, 'subsample': 0.9705171762552385, 'colsample_bytree': 0.778876512372213, 'min_child_weight': 1, 'gamma': 4.3532989914097495, 'reg_alpha': 1.594949760431522e-06, 'reg_lambda': 0.00017923833822607423, 'max_delta_step': 10}. Best is trial 41 with value: 0.6636713735558408.

Best trial: 41. Best value: 0.663671:  92%|█████████▏| 46/50 [09:07<00:51, 12.97s/it]

[I 2025-12-01 21:57:57,054] Trial 48 pruned.

Best trial: 41. Best value: 0.663671:  94%|█████████▍| 47/50 [09:09<00:29,  9.77s/it]

[I 2025-12-01 21:57:59,358] Trial 42 finished with value: 0.6514762516046213 and parameters: {'max_depth': 9, 'learning_rate': 0.016993839854315834, 'n_estimators': 1054, 'subsample': 0.9693685775917217, 'colsample_bytree': 0.6973793271676939, 'min_child_weight': 1, 'gamma': 4.6952590274297, 'reg_alpha': 3.041402064742926e-06, 'reg_lambda': 7.616865098951392e-06, 'max_delta_step': 4}. Best is trial 41 with value: 0.6636713735558408.

Best trial: 41. Best value: 0.663671:  96%|█████████▌| 48/50 [09:23<00:22, 11.22s/it]

[I 2025-12-01 21:58:13,973] Trial 45 finished with value: 0.5744544287548139 and parameters: {'max_depth': 10, 'learning_rate': 0.012306344801170826, 'n_estimators': 1038, 'subsample': 0.9596530693705849, 'colsample_bytree': 0.6240898385191793, 'min_child_weight': 2, 'gamma': 4.788376546527371, 'reg_alpha': 1.984459707430487e-06, 'reg_lambda': 0.0039735509442075725, 'max_delta_step': 10}. Best is trial 41 with value: 0.6636713735558408.

Best trial: 41. Best value: 0.663671:  98%|█████████▊| 49/50 [09:43<00:13, 13.75s/it]

[I 2025-12-01 21:58:33,622] Trial 47 finished with value: 0.6007702182284981 and parameters: {'max_depth': 10, 'learning_rate': 0.022249596826403494, 'n_estimators': 1342, 'subsample': 0.9493653460005389, 'colsample_bytree': 0.7684688685188229, 'min_child_weight': 3, 'gamma': 4.3658201370313385, 'reg_alpha': 0.01449706577067241, 'reg_lambda': 0.00011802339647866353, 'max_delta_step': 9}. Best is trial 41 with value: 0.6636713735558408.

Best trial: 41. Best value: 0.663671: 100%|██████████| 50/50 [10:03<00:00, 12.07s/it]

[I 2025-12-01 21:58:53,402] Trial 49 finished with value: 0.625160462130937 and parameters: {'max_depth': 8, 'learning_rate': 0.024522807130722808, 'n_estimators': 1243, 'subsample': 0.9817802962853714, 'colsample_bytree': 0.720768917241432, 'min_child_weight': 2, 'gamma': 4.366158321884432, 'reg_alpha': 7.334655336461638e-08, 'reg_lambda': 0.00021321852609811672, 'max_delta_step': 9}. Best is trial 41 with value: 0.6636713735558408.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    17_1         loo       0.663671                    0.85          0.92
1    15_1         loo       0.618742                    0.70          0.70
2     9_1         loo       0.664474                    0.50          0.73
3    19_1         loo       0.653289                    0.45          0.47

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.661438               1.0               0.7        50          60
1  0.377964               0.8               0.6        50          60
2  0.000000               0.6               0.4        50          59
3 -0.106600               0.2               0.7        50          59

   test_size
0         15
1         15
2         15
3         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    17_1         loo       0.663671                    0.85          0.92
1    15_1         loo       0.618742                    0.70          0.70
2     9_1         loo       0.664474                    0.50          0.73
3    19_1         loo       0.653289                    0.45          0.47

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.661438               1.0               0.7        50          60
1  0.377964               0.8               0.6        50          60
2  0.000000               0.6               0.4        50          59
3 -0.106600               0.2               0.7        50          59

   test_size
0         15
1         15
2         15
3         15

In [1571]:
datasets = task_freq_dfs_ad_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir="xgb_ad_hc_{CV_STRATEGY}_tasks/xgb_results_freq_ad_hc_extended_{CV_STRATEGY}_tasks",
    split_param="emb_",
)
print(summary)

[I 2025-12-01 21:58:59,958] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.534211:   2%|▏         | 1/50 [00:13<10:51, 13.29s/it]

[I 2025-12-01 21:59:13,245] Trial 0 finished with value: 0.5342105263157895 and parameters: {'max_depth': 3, 'learning_rate': 0.04935197840187953, 'n_estimators': 223, 'subsample': 0.5017739636536491, 'colsample_bytree': 0.925783296163591, 'min_child_weight': 5, 'gamma': 0.12729324970317202, 'reg_alpha': 0.19487521372493063, 'reg_lambda': 1.1462407005754032, 'max_delta_step': 10}. Best is trial 0 with value: 0.5342105263157895.

Best trial: 3. Best value: 0.574342:   4%|▍         | 2/50 [00:31<13:03, 16.33s/it]

[I 2025-12-01 21:59:31,702] Trial 3 finished with value: 0.5743421052631579 and parameters: {'max_depth': 8, 'learning_rate': 0.010040964033724406, 'n_estimators': 614, 'subsample': 0.7231391000424344, 'colsample_bytree': 0.9077057661109722, 'min_child_weight': 7, 'gamma': 0.8853649031663852, 'reg_alpha': 0.0008189353159710592, 'reg_lambda': 1.8722935304952196e-06, 'max_delta_step': 5}. Best is trial 3 with value: 0.5743421052631579.

Best trial: 3. Best value: 0.574342:   6%|▌         | 3/50 [01:04<18:34, 23.71s/it]

[I 2025-12-01 22:00:04,191] Trial 1 finished with value: 0.5328947368421053 and parameters: {'max_depth': 10, 'learning_rate': 0.05327911183739626, 'n_estimators': 1456, 'subsample': 0.7607961868026163, 'colsample_bytree': 0.7674105488679159, 'min_child_weight': 5, 'gamma': 4.469689592858948, 'reg_alpha': 0.001475927044375287, 'reg_lambda': 0.24812626730048762, 'max_delta_step': 7}. Best is trial 3 with value: 0.5743421052631579.

Best trial: 3. Best value: 0.574342:   8%|▊         | 4/50 [01:14<14:13, 18.55s/it]

[I 2025-12-01 22:00:14,838] Trial 4 finished with value: 0.4953947368421053 and parameters: {'max_depth': 6, 'learning_rate': 0.06426053010543807, 'n_estimators': 1344, 'subsample': 0.802030605887146, 'colsample_bytree': 0.7621111000177541, 'min_child_weight': 5, 'gamma': 3.8148335972572167, 'reg_alpha': 0.0007761613179004596, 'reg_lambda': 1.5277175507345107, 'max_delta_step': 7}. Best is trial 3 with value: 0.5743421052631579.

Best trial: 3. Best value: 0.574342:  10%|█         | 5/50 [01:17<09:40, 12.91s/it]

[I 2025-12-01 22:00:17,734] Trial 5 finished with value: 0.3375 and parameters: {'max_depth': 6, 'learning_rate': 0.020047306843615605, 'n_estimators': 1088, 'subsample': 0.704025873798573, 'colsample_bytree': 0.6972470075697235, 'min_child_weight': 9, 'gamma': 2.017428011659364, 'reg_alpha': 2.5782836124341093e-06, 'reg_lambda': 0.11345529947323423, 'max_delta_step': 0}. Best is trial 3 with value: 0.5743421052631579.

Best trial: 3. Best value: 0.574342:  12%|█▏        | 6/50 [01:38<11:17, 15.40s/it]

[I 2025-12-01 22:00:37,981] Trial 2 finished with value: 0.4552631578947368 and parameters: {'max_depth': 6, 'learning_rate': 0.015476225989098874, 'n_estimators': 1384, 'subsample': 0.6371728918448263, 'colsample_bytree': 0.8618230924702317, 'min_child_weight': 2, 'gamma': 0.47456893052971905, 'reg_alpha': 0.05137949588175857, 'reg_lambda': 1.7995412311899337e-05, 'max_delta_step': 0}. Best is trial 3 with value: 0.5743421052631579.

Best trial: 3. Best value: 0.574342:  14%|█▍        | 7/50 [01:55<11:34, 16.15s/it]

[I 2025-12-01 22:00:55,657] Trial 7 finished with value: 0.475 and parameters: {'max_depth': 8, 'learning_rate': 0.11799858270473851, 'n_estimators': 933, 'subsample': 0.6773206949260906, 'colsample_bytree': 0.6115496345706682, 'min_child_weight': 9, 'gamma': 2.1168827877588248, 'reg_alpha': 0.019861251242248273, 'reg_lambda': 7.173398252211533, 'max_delta_step': 6}. Best is trial 3 with value: 0.5743421052631579.

Best trial: 3. Best value: 0.574342:  16%|█▌        | 8/50 [02:08<10:27, 14.94s/it]

[I 2025-12-01 22:01:08,010] Trial 8 finished with value: 0.3 and parameters: {'max_depth': 4, 'learning_rate': 0.03147179169645192, 'n_estimators': 1127, 'subsample': 0.6592731467655011, 'colsample_bytree': 0.6340028834317812, 'min_child_weight': 9, 'gamma': 4.168656822628961, 'reg_alpha': 0.00737836716762209, 'reg_lambda': 0.006207312134410984, 'max_delta_step': 5}. Best is trial 3 with value: 0.5743421052631579.

Best trial: 3. Best value: 0.574342:  18%|█▊        | 9/50 [02:11<07:43, 11.30s/it]

[I 2025-12-01 22:01:11,297] Trial 6 finished with value: 0.5342105263157895 and parameters: {'max_depth': 8, 'learning_rate': 0.11016168204419752, 'n_estimators': 1485, 'subsample': 0.7576364518149874, 'colsample_bytree': 0.8114077253431637, 'min_child_weight': 7, 'gamma': 0.315993023346266, 'reg_alpha': 9.285710110372578e-05, 'reg_lambda': 2.689911642372732e-05, 'max_delta_step': 10}. Best is trial 3 with value: 0.5743421052631579.

Best trial: 3. Best value: 0.574342:  20%|██        | 10/50 [02:36<10:17, 15.43s/it]

[I 2025-12-01 22:01:35,978] Trial 10 finished with value: 0.506578947368421 and parameters: {'max_depth': 10, 'learning_rate': 0.12233432828010454, 'n_estimators': 812, 'subsample': 0.8512426659186276, 'colsample_bytree': 0.7532678331819161, 'min_child_weight': 5, 'gamma': 3.4364513447620944, 'reg_alpha': 4.56270739309681e-08, 'reg_lambda': 0.26533186529334, 'max_delta_step': 2}. Best is trial 3 with value: 0.5743421052631579.

Best trial: 3. Best value: 0.574342:  22%|██▏       | 11/50 [02:42<08:10, 12.57s/it]

[I 2025-12-01 22:01:42,050] Trial 13 pruned.

Best trial: 3. Best value: 0.574342:  24%|██▍       | 12/50 [02:44<05:59,  9.47s/it]

[I 2025-12-01 22:01:44,430] Trial 14 pruned.

Best trial: 3. Best value: 0.574342:  26%|██▌       | 13/50 [02:45<04:16,  6.94s/it]

[I 2025-12-01 22:01:45,566] Trial 12 pruned.

Best trial: 3. Best value: 0.574342:  28%|██▊       | 14/50 [02:47<03:17,  5.49s/it]

[I 2025-12-01 22:01:47,695] Trial 16 pruned.

Best trial: 3. Best value: 0.574342:  30%|███       | 15/50 [02:48<02:21,  4.04s/it]

[I 2025-12-01 22:01:48,369] Trial 15 pruned.

Best trial: 3. Best value: 0.574342:  32%|███▏      | 16/50 [02:49<01:44,  3.06s/it]

[I 2025-12-01 22:01:49,162] Trial 11 finished with value: 0.5480263157894737 and parameters: {'max_depth': 10, 'learning_rate': 0.1058067377718776, 'n_estimators': 788, 'subsample': 0.9112994648809379, 'colsample_bytree': 0.5586123700280499, 'min_child_weight': 4, 'gamma': 4.284142266630411, 'reg_alpha': 5.7051652443272096e-08, 'reg_lambda': 0.01726410584708462, 'max_delta_step': 0}. Best is trial 3 with value: 0.5743421052631579.

Best trial: 3. Best value: 0.574342:  34%|███▍      | 17/50 [02:50<01:23,  2.54s/it]

[I 2025-12-01 22:01:50,497] Trial 9 finished with value: 0.5342105263157895 and parameters: {'max_depth': 5, 'learning_rate': 0.07341926656134362, 'n_estimators': 1430, 'subsample': 0.7853760544863673, 'colsample_bytree': 0.8990427805752526, 'min_child_weight': 5, 'gamma': 4.175323127803834, 'reg_alpha': 2.2535678651535456e-06, 'reg_lambda': 0.11897394986575961, 'max_delta_step': 4}. Best is trial 3 with value: 0.5743421052631579.

Best trial: 3. Best value: 0.574342:  36%|███▌      | 18/50 [02:55<01:42,  3.20s/it]

[I 2025-12-01 22:01:55,217] Trial 17 pruned.

Best trial: 3. Best value: 0.574342:  38%|███▊      | 19/50 [02:56<01:17,  2.49s/it]

[I 2025-12-01 22:01:56,073] Trial 18 pruned.

Best trial: 3. Best value: 0.574342:  40%|████      | 20/50 [03:03<01:57,  3.91s/it]

[I 2025-12-01 22:02:03,276] Trial 22 pruned.

Best trial: 3. Best value: 0.574342:  42%|████▏     | 21/50 [03:06<01:44,  3.59s/it]

[I 2025-12-01 22:02:06,130] Trial 20 pruned.

Best trial: 3. Best value: 0.574342:  44%|████▍     | 22/50 [03:09<01:38,  3.54s/it]

[I 2025-12-01 22:02:09,537] Trial 23 pruned.

Best trial: 3. Best value: 0.574342:  46%|████▌     | 23/50 [03:10<01:11,  2.64s/it]

[I 2025-12-01 22:02:10,087] Trial 24 pruned.

Best trial: 3. Best value: 0.574342:  48%|████▊     | 24/50 [03:13<01:10,  2.72s/it]

[I 2025-12-01 22:02:12,984] Trial 21 pruned.

Best trial: 3. Best value: 0.574342:  50%|█████     | 25/50 [03:13<00:50,  2.01s/it]

[I 2025-12-01 22:02:13,344] Trial 25 pruned.

Best trial: 3. Best value: 0.574342:  52%|█████▏    | 26/50 [03:17<01:03,  2.67s/it]

[I 2025-12-01 22:02:17,514] Trial 26 pruned.

Best trial: 3. Best value: 0.574342:  54%|█████▍    | 27/50 [03:21<01:08,  2.97s/it]

[I 2025-12-01 22:02:21,218] Trial 27 pruned.

Best trial: 3. Best value: 0.574342:  56%|█████▌    | 28/50 [03:22<00:50,  2.31s/it]

[I 2025-12-01 22:02:21,995] Trial 19 finished with value: 0.5342105263157895 and parameters: {'max_depth': 9, 'learning_rate': 0.15656893905793473, 'n_estimators': 658, 'subsample': 0.8943051230882775, 'colsample_bytree': 0.5043326586285989, 'min_child_weight': 3, 'gamma': 4.99148058836469, 'reg_alpha': 1.0650524087417072e-08, 'reg_lambda': 0.0014637140936792777, 'max_delta_step': 2}. Best is trial 3 with value: 0.5743421052631579.

Best trial: 3. Best value: 0.574342:  58%|█████▊    | 29/50 [03:24<00:50,  2.43s/it]

[I 2025-12-01 22:02:24,690] Trial 31 pruned.

Best trial: 3. Best value: 0.574342:  60%|██████    | 30/50 [03:25<00:39,  1.96s/it]

[I 2025-12-01 22:02:25,548] Trial 30 pruned.

Best trial: 3. Best value: 0.574342:  62%|██████▏   | 31/50 [03:26<00:29,  1.54s/it]

[I 2025-12-01 22:02:26,109] Trial 29 pruned.

Best trial: 3. Best value: 0.574342:  64%|██████▍   | 32/50 [03:32<00:53,  2.97s/it]

[I 2025-12-01 22:02:32,439] Trial 32 pruned.
[I 2025-12-01 22:02:32,473] Trial 33 pruned.

Best trial: 3. Best value: 0.574342:  68%|██████▊   | 34/50 [03:36<00:40,  2.51s/it]

[I 2025-12-01 22:02:36,393] Trial 34 pruned.

Best trial: 3. Best value: 0.574342:  70%|███████   | 35/50 [03:41<00:45,  3.03s/it]

[I 2025-12-01 22:02:40,984] Trial 28 pruned.

Best trial: 3. Best value: 0.574342:  72%|███████▏  | 36/50 [03:51<01:08,  4.93s/it]

[I 2025-12-01 22:02:51,265] Trial 38 pruned.

Best trial: 3. Best value: 0.574342:  74%|███████▍  | 37/50 [03:52<00:50,  3.89s/it]

[I 2025-12-01 22:02:52,372] Trial 35 pruned.

Best trial: 3. Best value: 0.574342:  76%|███████▌  | 38/50 [03:57<00:51,  4.30s/it]

[I 2025-12-01 22:02:57,725] Trial 37 pruned.

Best trial: 3. Best value: 0.574342:  78%|███████▊  | 39/50 [03:59<00:39,  3.63s/it]

[I 2025-12-01 22:02:59,699] Trial 40 pruned.

Best trial: 3. Best value: 0.574342:  80%|████████  | 40/50 [04:01<00:29,  2.95s/it]

[I 2025-12-01 22:03:00,966] Trial 39 pruned.

Best trial: 3. Best value: 0.574342:  82%|████████▏ | 41/50 [04:04<00:29,  3.25s/it]

[I 2025-12-01 22:03:04,932] Trial 41 pruned.

Best trial: 3. Best value: 0.574342:  84%|████████▍ | 42/50 [04:05<00:20,  2.57s/it]

[I 2025-12-01 22:03:05,900] Trial 42 pruned.

Best trial: 3. Best value: 0.574342:  86%|████████▌ | 43/50 [04:20<00:43,  6.18s/it]

[I 2025-12-01 22:03:20,629] Trial 43 pruned.

Best trial: 3. Best value: 0.574342:  88%|████████▊ | 44/50 [04:30<00:43,  7.25s/it]

[I 2025-12-01 22:03:30,406] Trial 45 pruned.

Best trial: 3. Best value: 0.574342:  90%|█████████ | 45/50 [04:32<00:27,  5.58s/it]

[I 2025-12-01 22:03:32,052] Trial 46 pruned.

Best trial: 36. Best value: 0.600658:  92%|█████████▏| 46/50 [04:32<00:16,  4.17s/it]

[I 2025-12-01 22:03:32,920] Trial 36 finished with value: 0.6006578947368422 and parameters: {'max_depth': 6, 'learning_rate': 0.11407474091770513, 'n_estimators': 1266, 'subsample': 0.9453333506284753, 'colsample_bytree': 0.815177580790197, 'min_child_weight': 8, 'gamma': 0.2941773435442426, 'reg_alpha': 0.00014267547045160322, 'reg_lambda': 7.839455827412895e-06, 'max_delta_step': 10}. Best is trial 36 with value: 0.6006578947368422.

Best trial: 36. Best value: 0.600658:  94%|█████████▍| 47/50 [04:43<00:18,  6.12s/it]

[I 2025-12-01 22:03:43,605] Trial 47 pruned.

Best trial: 36. Best value: 0.600658:  96%|█████████▌| 48/50 [04:44<00:09,  4.59s/it]

[I 2025-12-01 22:03:44,632] Trial 49 pruned.

Best trial: 36. Best value: 0.600658:  98%|█████████▊| 49/50 [05:00<00:07,  7.98s/it]

[I 2025-12-01 22:04:00,534] Trial 44 finished with value: 0.5467105263157894 and parameters: {'max_depth': 6, 'learning_rate': 0.1331644892526731, 'n_estimators': 1413, 'subsample': 0.7815477728519594, 'colsample_bytree': 0.8975991574847174, 'min_child_weight': 5, 'gamma': 3.969284249870227, 'reg_alpha': 1.8856146094940279e-06, 'reg_lambda': 0.12267670623588024, 'max_delta_step': 5}. Best is trial 36 with value: 0.6006578947368422.

Best trial: 48. Best value: 0.664474: 100%|██████████| 50/50 [05:13<00:00,  6.28s/it]

[I 2025-12-01 22:04:13,731] Trial 48 finished with value: 0.6644736842105263 and parameters: {'max_depth': 3, 'learning_rate': 0.03497695895733737, 'n_estimators': 1484, 'subsample': 0.8815340270826834, 'colsample_bytree': 0.972274853524669, 'min_child_weight': 9, 'gamma': 4.05347320360234, 'reg_alpha': 1.321606558876863e-06, 'reg_lambda': 1.1182239790084327, 'max_delta_step': 3}. Best is trial 48 with value: 0.6644736842105263.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 22:04:16,998] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.442875:   2%|▏         | 1/50 [00:54<44:51, 54.93s/it]

[I 2025-12-01 22:05:11,917] Trial 1 finished with value: 0.4428754813863928 and parameters: {'max_depth': 9, 'learning_rate': 0.15199093894870355, 'n_estimators': 1284, 'subsample': 0.8374233774950595, 'colsample_bytree': 0.774957394167516, 'min_child_weight': 3, 'gamma': 1.7886578291679793, 'reg_alpha': 7.088745295367462e-07, 'reg_lambda': 0.022001011895898554, 'max_delta_step': 10}. Best is trial 1 with value: 0.4428754813863928.

Best trial: 0. Best value: 0.483312:   4%|▍         | 2/50 [00:57<19:30, 24.39s/it]

[I 2025-12-01 22:05:14,925] Trial 0 finished with value: 0.4833119383825417 and parameters: {'max_depth': 5, 'learning_rate': 0.018490213660220894, 'n_estimators': 1051, 'subsample': 0.6317347061836609, 'colsample_bytree': 0.7870737610091514, 'min_child_weight': 3, 'gamma': 3.384062378620362, 'reg_alpha': 8.696467498640344e-06, 'reg_lambda': 1.697925556037367e-05, 'max_delta_step': 10}. Best is trial 0 with value: 0.4833119383825417.

Best trial: 0. Best value: 0.483312:   6%|▌         | 3/50 [00:59<10:57, 14.00s/it]

[I 2025-12-01 22:05:16,557] Trial 2 finished with value: 0.41014120667522463 and parameters: {'max_depth': 10, 'learning_rate': 0.015063408776167487, 'n_estimators': 1121, 'subsample': 0.9294659610986777, 'colsample_bytree': 0.9154430445744999, 'min_child_weight': 7, 'gamma': 2.9108383824595436, 'reg_alpha': 9.367051596677817e-08, 'reg_lambda': 7.123471022629094e-07, 'max_delta_step': 1}. Best is trial 0 with value: 0.4833119383825417.

Best trial: 0. Best value: 0.483312:   8%|▊         | 4/50 [01:06<08:29, 11.08s/it]

[I 2025-12-01 22:05:23,171] Trial 3 finished with value: 0.4833119383825417 and parameters: {'max_depth': 9, 'learning_rate': 0.04160545446037674, 'n_estimators': 1306, 'subsample': 0.8350397795325379, 'colsample_bytree': 0.6580870826804949, 'min_child_weight': 3, 'gamma': 4.0377775774946905, 'reg_alpha': 0.14602421032227422, 'reg_lambda': 0.0004105498425939197, 'max_delta_step': 4}. Best is trial 0 with value: 0.4833119383825417.

Best trial: 0. Best value: 0.483312:  10%|█         | 5/50 [01:14<07:37, 10.17s/it]

[I 2025-12-01 22:05:31,717] Trial 6 finished with value: 0.2894736842105263 and parameters: {'max_depth': 10, 'learning_rate': 0.25161661184350353, 'n_estimators': 331, 'subsample': 0.7484569464153141, 'colsample_bytree': 0.621517691862676, 'min_child_weight': 10, 'gamma': 3.4021935961524, 'reg_alpha': 2.236512017536828, 'reg_lambda': 3.867620863572219e-07, 'max_delta_step': 8}. Best is trial 0 with value: 0.4833119383825417.

Best trial: 0. Best value: 0.483312:  12%|█▏        | 6/50 [01:35<10:08, 13.83s/it]

[I 2025-12-01 22:05:52,652] Trial 8 finished with value: 0.43838254172015406 and parameters: {'max_depth': 6, 'learning_rate': 0.02193453920924863, 'n_estimators': 336, 'subsample': 0.8085656952436111, 'colsample_bytree': 0.8429009806936436, 'min_child_weight': 8, 'gamma': 0.37785170283798797, 'reg_alpha': 1.5677355359385834, 'reg_lambda': 4.809992167964957e-07, 'max_delta_step': 7}. Best is trial 0 with value: 0.4833119383825417.

Best trial: 0. Best value: 0.483312:  14%|█▍        | 7/50 [01:47<09:20, 13.03s/it]

[I 2025-12-01 22:06:04,044] Trial 5 finished with value: 0.3838254172015404 and parameters: {'max_depth': 4, 'learning_rate': 0.03435222473521746, 'n_estimators': 902, 'subsample': 0.7781805348753819, 'colsample_bytree': 0.9538114778771121, 'min_child_weight': 6, 'gamma': 0.7025380447766283, 'reg_alpha': 0.02770195367761732, 'reg_lambda': 7.612702245731997e-06, 'max_delta_step': 3}. Best is trial 0 with value: 0.4833119383825417.

Best trial: 0. Best value: 0.483312:  16%|█▌        | 8/50 [01:50<06:56,  9.91s/it]

[I 2025-12-01 22:06:07,272] Trial 4 finished with value: 0.46277278562259305 and parameters: {'max_depth': 10, 'learning_rate': 0.03705503161633494, 'n_estimators': 1261, 'subsample': 0.9679199489752958, 'colsample_bytree': 0.5484254190345099, 'min_child_weight': 7, 'gamma': 4.301158473888348, 'reg_alpha': 0.12975121041127394, 'reg_lambda': 4.6278580024564504e-05, 'max_delta_step': 4}. Best is trial 0 with value: 0.4833119383825417.

Best trial: 7. Best value: 0.485237:  18%|█▊        | 9/50 [02:00<06:46,  9.93s/it]

[I 2025-12-01 22:06:17,228] Trial 7 finished with value: 0.48523748395378685 and parameters: {'max_depth': 5, 'learning_rate': 0.029768330825928082, 'n_estimators': 658, 'subsample': 0.8967721247745829, 'colsample_bytree': 0.9765514333187877, 'min_child_weight': 2, 'gamma': 4.06251090537302, 'reg_alpha': 1.4225367463220807e-06, 'reg_lambda': 0.027445096208339254, 'max_delta_step': 10}. Best is trial 7 with value: 0.48523748395378685.

Best trial: 7. Best value: 0.485237:  20%|██        | 10/50 [02:08<06:11,  9.29s/it]

[I 2025-12-01 22:06:25,094] Trial 9 finished with value: 0.4473684210526316 and parameters: {'max_depth': 4, 'learning_rate': 0.022610839164830716, 'n_estimators': 755, 'subsample': 0.5262729157786916, 'colsample_bytree': 0.7883729635481017, 'min_child_weight': 8, 'gamma': 0.8593033198276001, 'reg_alpha': 1.6964442991797198e-07, 'reg_lambda': 0.00011697656948971001, 'max_delta_step': 7}. Best is trial 7 with value: 0.48523748395378685.

Best trial: 7. Best value: 0.485237:  22%|██▏       | 11/50 [02:13<05:12,  8.00s/it]

[I 2025-12-01 22:06:30,179] Trial 12 pruned.

Best trial: 13. Best value: 0.523748:  24%|██▍       | 12/50 [02:50<10:43, 16.94s/it]

[I 2025-12-01 22:07:07,552] Trial 13 finished with value: 0.5237483953786906 and parameters: {'max_depth': 7, 'learning_rate': 0.08823899127261245, 'n_estimators': 620, 'subsample': 0.6782528071548897, 'colsample_bytree': 0.9667553799802113, 'min_child_weight': 1, 'gamma': 4.9826126426111745, 'reg_alpha': 0.00015881526589060443, 'reg_lambda': 1.9387206398980594, 'max_delta_step': 0}. Best is trial 13 with value: 0.5237483953786906.

Best trial: 13. Best value: 0.523748:  26%|██▌       | 13/50 [02:55<08:14, 13.37s/it]

[I 2025-12-01 22:07:12,713] Trial 11 finished with value: 0.5096277278562259 and parameters: {'max_depth': 9, 'learning_rate': 0.021713985433319625, 'n_estimators': 1363, 'subsample': 0.8014935587715821, 'colsample_bytree': 0.7938595445946024, 'min_child_weight': 4, 'gamma': 3.455212792572371, 'reg_alpha': 8.898602793299212e-08, 'reg_lambda': 0.003297517262155282, 'max_delta_step': 4}. Best is trial 13 with value: 0.5237483953786906.

Best trial: 13. Best value: 0.523748:  28%|██▊       | 14/50 [02:56<05:47,  9.65s/it]

[I 2025-12-01 22:07:13,781] Trial 10 finished with value: 0.5096277278562259 and parameters: {'max_depth': 8, 'learning_rate': 0.012300114606193983, 'n_estimators': 743, 'subsample': 0.5246851714579936, 'colsample_bytree': 0.5700519856681363, 'min_child_weight': 1, 'gamma': 1.4805606435122987, 'reg_alpha': 1.2400393663559814, 'reg_lambda': 1.3991155131209989e-08, 'max_delta_step': 7}. Best is trial 13 with value: 0.5237483953786906.

Best trial: 13. Best value: 0.523748:  30%|███       | 15/50 [02:57<04:02,  6.92s/it]

[I 2025-12-01 22:07:14,368] Trial 15 pruned.

Best trial: 13. Best value: 0.523748:  34%|███▍      | 17/50 [03:02<02:26,  4.42s/it]

[I 2025-12-01 22:07:19,117] Trial 17 pruned.
[I 2025-12-01 22:07:19,256] Trial 18 pruned.

Best trial: 13. Best value: 0.523748:  36%|███▌      | 18/50 [03:10<02:59,  5.60s/it]

[I 2025-12-01 22:07:27,583] Trial 20 pruned.

Best trial: 13. Best value: 0.523748:  38%|███▊      | 19/50 [03:13<02:32,  4.91s/it]

[I 2025-12-01 22:07:30,900] Trial 21 pruned.

Best trial: 13. Best value: 0.523748:  40%|████      | 20/50 [03:17<02:13,  4.43s/it]

[I 2025-12-01 22:07:34,219] Trial 14 finished with value: 0.5237483953786906 and parameters: {'max_depth': 7, 'learning_rate': 0.010142732730327456, 'n_estimators': 684, 'subsample': 0.6128759375004624, 'colsample_bytree': 0.9807776633385622, 'min_child_weight': 1, 'gamma': 4.939063837110656, 'reg_alpha': 5.293404968390205e-05, 'reg_lambda': 2.8046926604926328, 'max_delta_step': 10}. Best is trial 13 with value: 0.5237483953786906.

Best trial: 13. Best value: 0.523748:  42%|████▏     | 21/50 [03:28<03:08,  6.49s/it]

[I 2025-12-01 22:07:45,500] Trial 19 finished with value: 0.4871630295250321 and parameters: {'max_depth': 8, 'learning_rate': 0.011340953896328866, 'n_estimators': 439, 'subsample': 0.5664199153963845, 'colsample_bytree': 0.6767455449742272, 'min_child_weight': 5, 'gamma': 1.6628626075589223, 'reg_alpha': 0.001332222544013905, 'reg_lambda': 3.83907127399869e-08, 'max_delta_step': 6}. Best is trial 13 with value: 0.5237483953786906.

Best trial: 16. Best value: 0.564185:  44%|████▍     | 22/50 [03:36<03:16,  7.00s/it]

[I 2025-12-01 22:07:53,705] Trial 16 finished with value: 0.5641848523748395 and parameters: {'max_depth': 8, 'learning_rate': 0.123336667448917, 'n_estimators': 594, 'subsample': 0.693124948367054, 'colsample_bytree': 0.8763273864468076, 'min_child_weight': 1, 'gamma': 4.678812871585103, 'reg_alpha': 0.00029372776173471857, 'reg_lambda': 3.337241878884733, 'max_delta_step': 0}. Best is trial 16 with value: 0.5641848523748395.

Best trial: 16. Best value: 0.564185:  46%|████▌     | 23/50 [03:39<02:34,  5.73s/it]

[I 2025-12-01 22:07:56,475] Trial 23 finished with value: 0.42426187419768935 and parameters: {'max_depth': 6, 'learning_rate': 0.15650168825035624, 'n_estimators': 453, 'subsample': 0.6744734269427458, 'colsample_bytree': 0.8968704191632607, 'min_child_weight': 5, 'gamma': 4.362795813485609, 'reg_alpha': 1.377998902395324e-05, 'reg_lambda': 0.4744276210111939, 'max_delta_step': 5}. Best is trial 16 with value: 0.5641848523748395.

Best trial: 16. Best value: 0.564185:  48%|████▊     | 24/50 [03:44<02:25,  5.60s/it]

[I 2025-12-01 22:08:01,767] Trial 25 pruned.

Best trial: 16. Best value: 0.564185:  50%|█████     | 25/50 [03:52<02:33,  6.13s/it]

[I 2025-12-01 22:08:09,138] Trial 27 pruned.

Best trial: 16. Best value: 0.564185:  52%|█████▏    | 26/50 [03:59<02:38,  6.60s/it]

[I 2025-12-01 22:08:16,834] Trial 28 pruned.

Best trial: 16. Best value: 0.564185:  54%|█████▍    | 27/50 [04:10<03:02,  7.95s/it]

[I 2025-12-01 22:08:27,911] Trial 22 finished with value: 0.43645699614890887 and parameters: {'max_depth': 3, 'learning_rate': 0.15491635172413498, 'n_estimators': 1482, 'subsample': 0.6896326403765654, 'colsample_bytree': 0.6072571298217941, 'min_child_weight': 5, 'gamma': 1.1353120586753853, 'reg_alpha': 0.005102632431352581, 'reg_lambda': 0.4439547771480341, 'max_delta_step': 5}. Best is trial 16 with value: 0.5641848523748395.

Best trial: 16. Best value: 0.564185:  56%|█████▌    | 28/50 [04:18<02:53,  7.87s/it]

[I 2025-12-01 22:08:35,614] Trial 24 finished with value: 0.5237483953786906 and parameters: {'max_depth': 6, 'learning_rate': 0.013007663570062397, 'n_estimators': 784, 'subsample': 0.6756006633863446, 'colsample_bytree': 0.5901275083110143, 'min_child_weight': 2, 'gamma': 4.623057176159526, 'reg_alpha': 3.9787663926608356e-05, 'reg_lambda': 0.2884604866792948, 'max_delta_step': 9}. Best is trial 16 with value: 0.5641848523748395.

Best trial: 16. Best value: 0.564185:  58%|█████▊    | 29/50 [04:23<02:29,  7.12s/it]

[I 2025-12-01 22:08:40,985] Trial 31 pruned.

Best trial: 16. Best value: 0.564185:  60%|██████    | 30/50 [04:29<02:11,  6.59s/it]

[I 2025-12-01 22:08:46,350] Trial 26 finished with value: 0.5378690629011553 and parameters: {'max_depth': 6, 'learning_rate': 0.1419192508397569, 'n_estimators': 872, 'subsample': 0.695257492127686, 'colsample_bytree': 0.9225134737283234, 'min_child_weight': 2, 'gamma': 4.65336655002816, 'reg_alpha': 9.632609046529731e-05, 'reg_lambda': 0.6022779418439508, 'max_delta_step': 2}. Best is trial 16 with value: 0.5641848523748395.

Best trial: 16. Best value: 0.564185:  62%|██████▏   | 31/50 [04:30<01:31,  4.84s/it]

[I 2025-12-01 22:08:47,084] Trial 32 pruned.

Best trial: 16. Best value: 0.564185:  64%|██████▍   | 32/50 [04:31<01:06,  3.71s/it]

[I 2025-12-01 22:08:48,168] Trial 29 finished with value: 0.4608472400513479 and parameters: {'max_depth': 8, 'learning_rate': 0.1264881815086321, 'n_estimators': 668, 'subsample': 0.5918062653938627, 'colsample_bytree': 0.9513692527288568, 'min_child_weight': 4, 'gamma': 4.61516948800989, 'reg_alpha': 3.2795219068199475e-06, 'reg_lambda': 0.1016258500399777, 'max_delta_step': 3}. Best is trial 16 with value: 0.5641848523748395.

Best trial: 16. Best value: 0.564185:  66%|██████▌   | 33/50 [04:37<01:17,  4.53s/it]

[I 2025-12-01 22:08:54,624] Trial 33 pruned.

Best trial: 16. Best value: 0.564185:  68%|██████▊   | 34/50 [04:40<01:03,  3.97s/it]

[I 2025-12-01 22:08:57,289] Trial 35 pruned.

Best trial: 16. Best value: 0.564185:  70%|███████   | 35/50 [04:42<00:50,  3.34s/it]

[I 2025-12-01 22:08:59,155] Trial 34 pruned.

Best trial: 16. Best value: 0.564185:  72%|███████▏  | 36/50 [04:43<00:39,  2.83s/it]

[I 2025-12-01 22:09:00,789] Trial 30 finished with value: 0.4871630295250321 and parameters: {'max_depth': 8, 'learning_rate': 0.12378799647969871, 'n_estimators': 623, 'subsample': 0.5884367351445101, 'colsample_bytree': 0.9442458368542526, 'min_child_weight': 4, 'gamma': 4.553730690372937, 'reg_alpha': 2.2854708072448925e-06, 'reg_lambda': 9.661396918008819, 'max_delta_step': 2}. Best is trial 16 with value: 0.5641848523748395.

Best trial: 16. Best value: 0.564185:  74%|███████▍  | 37/50 [05:19<02:44, 12.68s/it]

[I 2025-12-01 22:09:36,460] Trial 36 finished with value: 0.5359435173299101 and parameters: {'max_depth': 9, 'learning_rate': 0.2024171529098729, 'n_estimators': 840, 'subsample': 0.7359030456801025, 'colsample_bytree': 0.9289600316031673, 'min_child_weight': 3, 'gamma': 4.291377760508529, 'reg_alpha': 0.00017467856968120666, 'reg_lambda': 1.5915000945632134, 'max_delta_step': 0}. Best is trial 16 with value: 0.5641848523748395.

Best trial: 16. Best value: 0.564185:  76%|███████▌  | 38/50 [05:26<02:12, 11.03s/it]

[I 2025-12-01 22:09:43,626] Trial 38 finished with value: 0.5096277278562259 and parameters: {'max_depth': 9, 'learning_rate': 0.05057057821098, 'n_estimators': 866, 'subsample': 0.7266184522042282, 'colsample_bytree': 0.9233497801770884, 'min_child_weight': 3, 'gamma': 3.0295497787764116, 'reg_alpha': 8.080351752471218e-05, 'reg_lambda': 0.005245906152765686, 'max_delta_step': 0}. Best is trial 16 with value: 0.5641848523748395.

Best trial: 16. Best value: 0.564185:  78%|███████▊  | 39/50 [05:27<01:26,  7.87s/it]

[I 2025-12-01 22:09:44,141] Trial 40 pruned.

Best trial: 16. Best value: 0.564185:  80%|████████  | 40/50 [05:33<01:13,  7.35s/it]

[I 2025-12-01 22:09:50,272] Trial 39 finished with value: 0.511553273427471 and parameters: {'max_depth': 9, 'learning_rate': 0.05135809906579069, 'n_estimators': 834, 'subsample': 0.741302631584631, 'colsample_bytree': 0.9112683740515811, 'min_child_weight': 2, 'gamma': 3.066246974722063, 'reg_alpha': 0.00011128506795726597, 'reg_lambda': 1.0941232307296938, 'max_delta_step': 0}. Best is trial 16 with value: 0.5641848523748395.

Best trial: 16. Best value: 0.564185:  82%|████████▏ | 41/50 [05:34<00:50,  5.61s/it]

[I 2025-12-01 22:09:51,821] Trial 41 pruned.

Best trial: 16. Best value: 0.564185:  84%|████████▍ | 42/50 [05:35<00:33,  4.24s/it]

[I 2025-12-01 22:09:52,864] Trial 42 pruned.

Best trial: 16. Best value: 0.564185:  86%|████████▌ | 43/50 [05:37<00:23,  3.33s/it]

[I 2025-12-01 22:09:54,083] Trial 37 finished with value: 0.4993581514762516 and parameters: {'max_depth': 9, 'learning_rate': 0.0498858102738632, 'n_estimators': 832, 'subsample': 0.7461291638870036, 'colsample_bytree': 0.9236759281378579, 'min_child_weight': 1, 'gamma': 3.0500867381865815, 'reg_alpha': 8.269563014176991e-05, 'reg_lambda': 0.0072356347601741505, 'max_delta_step': 0}. Best is trial 16 with value: 0.5641848523748395.

Best trial: 16. Best value: 0.564185:  88%|████████▊ | 44/50 [05:41<00:21,  3.53s/it]

[I 2025-12-01 22:09:58,061] Trial 43 pruned.

Best trial: 16. Best value: 0.564185:  90%|█████████ | 45/50 [05:43<00:15,  3.08s/it]

[I 2025-12-01 22:10:00,109] Trial 45 pruned.

Best trial: 16. Best value: 0.564185:  92%|█████████▏| 46/50 [06:18<00:51, 12.86s/it]

[I 2025-12-01 22:10:35,782] Trial 44 finished with value: 0.5134788189987163 and parameters: {'max_depth': 10, 'learning_rate': 0.10653667832742562, 'n_estimators': 708, 'subsample': 0.709870099570611, 'colsample_bytree': 0.9699603394572135, 'min_child_weight': 1, 'gamma': 4.822653745695092, 'reg_alpha': 0.0004975759232071716, 'reg_lambda': 4.32369190160836, 'max_delta_step': 1}. Best is trial 16 with value: 0.5641848523748395.

Best trial: 16. Best value: 0.564185:  94%|█████████▍| 47/50 [06:20<00:28,  9.65s/it]

[I 2025-12-01 22:10:37,896] Trial 46 finished with value: 0.5500641848523748 and parameters: {'max_depth': 7, 'learning_rate': 0.10989565175307245, 'n_estimators': 712, 'subsample': 0.6974143511373974, 'colsample_bytree': 0.9741888634582101, 'min_child_weight': 1, 'gamma': 4.780874726471861, 'reg_alpha': 1.757600433690307e-05, 'reg_lambda': 3.521105754539443, 'max_delta_step': 10}. Best is trial 16 with value: 0.5641848523748395.

Best trial: 16. Best value: 0.564185:  96%|█████████▌| 48/50 [06:25<00:16,  8.15s/it]

[I 2025-12-01 22:10:42,588] Trial 49 pruned.

Best trial: 16. Best value: 0.564185:  98%|█████████▊| 49/50 [06:32<00:07,  7.86s/it]

[I 2025-12-01 22:10:49,789] Trial 47 finished with value: 0.4871630295250321 and parameters: {'max_depth': 7, 'learning_rate': 0.016585049892452824, 'n_estimators': 706, 'subsample': 0.703101865317636, 'colsample_bytree': 0.978181671069153, 'min_child_weight': 1, 'gamma': 4.852465768677928, 'reg_alpha': 4.974162246736245e-07, 'reg_lambda': 3.7562358751035507, 'max_delta_step': 1}. Best is trial 16 with value: 0.5641848523748395.

Best trial: 16. Best value: 0.564185: 100%|██████████| 50/50 [06:43<00:00,  8.07s/it]

[I 2025-12-01 22:11:00,413] Trial 48 finished with value: 0.4993581514762516 and parameters: {'max_depth': 7, 'learning_rate': 0.24406845601741245, 'n_estimators': 1173, 'subsample': 0.6617052304341614, 'colsample_bytree': 0.9810446786605134, 'min_child_weight': 1, 'gamma': 4.9965839415856985, 'reg_alpha': 6.620058988211996e-07, 'reg_lambda': 0.16360459761637272, 'max_delta_step': 1}. Best is trial 16 with value: 0.5641848523748395.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 22:11:06,147] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.499358:   2%|▏         | 1/50 [00:29<24:02, 29.45s/it]

[I 2025-12-01 22:11:35,584] Trial 3 finished with value: 0.4993581514762516 and parameters: {'max_depth': 3, 'learning_rate': 0.06316817355368623, 'n_estimators': 687, 'subsample': 0.8508208532753148, 'colsample_bytree': 0.5716255565361218, 'min_child_weight': 5, 'gamma': 2.9724464578739607, 'reg_alpha': 0.002426185345283623, 'reg_lambda': 0.00017480336428330753, 'max_delta_step': 2}. Best is trial 3 with value: 0.4993581514762516.

Best trial: 3. Best value: 0.499358:   4%|▍         | 2/50 [00:35<12:26, 15.55s/it]

[I 2025-12-01 22:11:41,409] Trial 2 finished with value: 0.4768934531450577 and parameters: {'max_depth': 4, 'learning_rate': 0.018346480997581894, 'n_estimators': 919, 'subsample': 0.8183219597020027, 'colsample_bytree': 0.9061138143852787, 'min_child_weight': 9, 'gamma': 3.4021006267013405, 'reg_alpha': 0.00032192340195726695, 'reg_lambda': 4.36318112653858e-05, 'max_delta_step': 6}. Best is trial 3 with value: 0.4993581514762516.

Best trial: 5. Best value: 0.537869:   6%|▌         | 3/50 [00:57<14:32, 18.56s/it]

[I 2025-12-01 22:12:03,545] Trial 5 finished with value: 0.5378690629011553 and parameters: {'max_depth': 10, 'learning_rate': 0.020112713111370483, 'n_estimators': 435, 'subsample': 0.6606591974923406, 'colsample_bytree': 0.6194244429706206, 'min_child_weight': 6, 'gamma': 2.4675152510000578, 'reg_alpha': 0.039801552124356564, 'reg_lambda': 0.0012734797486081092, 'max_delta_step': 6}. Best is trial 5 with value: 0.5378690629011553.

Best trial: 5. Best value: 0.537869:   8%|▊         | 4/50 [00:58<08:53, 11.60s/it]

[I 2025-12-01 22:12:04,471] Trial 1 finished with value: 0.41014120667522463 and parameters: {'max_depth': 3, 'learning_rate': 0.015536949183662543, 'n_estimators': 1450, 'subsample': 0.8682089812364361, 'colsample_bytree': 0.986675313879328, 'min_child_weight': 9, 'gamma': 3.504530958276535, 'reg_alpha': 0.28143190070216045, 'reg_lambda': 0.03488054853656694, 'max_delta_step': 10}. Best is trial 5 with value: 0.5378690629011553.

Best trial: 6. Best value: 0.562259:  10%|█         | 5/50 [01:12<09:16, 12.37s/it]

[I 2025-12-01 22:12:18,220] Trial 6 finished with value: 0.5622593068035944 and parameters: {'max_depth': 4, 'learning_rate': 0.052719552290180466, 'n_estimators': 228, 'subsample': 0.7450102858857477, 'colsample_bytree': 0.6690594430534151, 'min_child_weight': 4, 'gamma': 1.6332238534476735, 'reg_alpha': 0.000699474880775811, 'reg_lambda': 6.017969567941159e-08, 'max_delta_step': 7}. Best is trial 6 with value: 0.5622593068035944.

Best trial: 6. Best value: 0.562259:  12%|█▏        | 6/50 [01:18<07:34, 10.34s/it]

[I 2025-12-01 22:12:24,605] Trial 7 finished with value: 0.21052631578947367 and parameters: {'max_depth': 7, 'learning_rate': 0.0453528695575749, 'n_estimators': 505, 'subsample': 0.6484694728362883, 'colsample_bytree': 0.9938722726547207, 'min_child_weight': 9, 'gamma': 0.41533672481546713, 'reg_alpha': 0.00023283732373316601, 'reg_lambda': 9.43404788619992, 'max_delta_step': 3}. Best is trial 6 with value: 0.5622593068035944.

Best trial: 6. Best value: 0.562259:  14%|█▍        | 7/50 [01:21<05:41,  7.95s/it]

[I 2025-12-01 22:12:27,629] Trial 4 finished with value: 0.4345314505776637 and parameters: {'max_depth': 4, 'learning_rate': 0.18814579246531937, 'n_estimators': 1452, 'subsample': 0.9689830865235338, 'colsample_bytree': 0.6700815154921115, 'min_child_weight': 8, 'gamma': 0.647244216540076, 'reg_alpha': 0.001688216466563923, 'reg_lambda': 5.103717437190306e-07, 'max_delta_step': 3}. Best is trial 6 with value: 0.5622593068035944.

Best trial: 6. Best value: 0.562259:  16%|█▌        | 8/50 [01:22<04:04,  5.83s/it]

[I 2025-12-01 22:12:28,919] Trial 0 finished with value: 0.5218228498074454 and parameters: {'max_depth': 8, 'learning_rate': 0.011902641483815589, 'n_estimators': 675, 'subsample': 0.9857258490528379, 'colsample_bytree': 0.8791689579896738, 'min_child_weight': 1, 'gamma': 1.3027273796324863, 'reg_alpha': 3.533348897796338e-05, 'reg_lambda': 1.6432989143544376, 'max_delta_step': 5}. Best is trial 6 with value: 0.5622593068035944.

Best trial: 6. Best value: 0.562259:  18%|█▊        | 9/50 [01:55<09:43, 14.23s/it]

[I 2025-12-01 22:13:01,620] Trial 8 finished with value: 0.4871630295250321 and parameters: {'max_depth': 7, 'learning_rate': 0.023955721619583, 'n_estimators': 921, 'subsample': 0.8667836883115736, 'colsample_bytree': 0.5838903757206677, 'min_child_weight': 7, 'gamma': 2.2868585086797237, 'reg_alpha': 0.10709214942768704, 'reg_lambda': 1.716108382962444e-05, 'max_delta_step': 9}. Best is trial 6 with value: 0.5622593068035944.

Best trial: 6. Best value: 0.562259:  20%|██        | 10/50 [01:59<07:24, 11.11s/it]

[I 2025-12-01 22:13:05,754] Trial 11 finished with value: 0.527599486521181 and parameters: {'max_depth': 5, 'learning_rate': 0.012763098486689786, 'n_estimators': 816, 'subsample': 0.6478731615057142, 'colsample_bytree': 0.5599708544494064, 'min_child_weight': 7, 'gamma': 0.5752210395041901, 'reg_alpha': 0.15120747627627792, 'reg_lambda': 0.00016938122812924807, 'max_delta_step': 4}. Best is trial 6 with value: 0.5622593068035944.

Best trial: 6. Best value: 0.562259:  22%|██▏       | 11/50 [02:03<05:48,  8.94s/it]

[I 2025-12-01 22:13:09,776] Trial 10 pruned.

Best trial: 6. Best value: 0.562259:  24%|██▍       | 12/50 [02:04<04:02,  6.38s/it]

[I 2025-12-01 22:13:10,283] Trial 12 pruned.

Best trial: 6. Best value: 0.562259:  26%|██▌       | 13/50 [02:06<03:07,  5.06s/it]

[I 2025-12-01 22:13:12,326] Trial 14 pruned.

Best trial: 6. Best value: 0.562259:  28%|██▊       | 14/50 [02:06<02:12,  3.69s/it]

[I 2025-12-01 22:13:12,835] Trial 15 pruned.

Best trial: 6. Best value: 0.562259:  30%|███       | 15/50 [02:10<02:09,  3.71s/it]

[I 2025-12-01 22:13:16,597] Trial 17 pruned.

Best trial: 6. Best value: 0.562259:  32%|███▏      | 16/50 [02:17<02:37,  4.62s/it]

[I 2025-12-01 22:13:23,330] Trial 13 finished with value: 0.511553273427471 and parameters: {'max_depth': 5, 'learning_rate': 0.14377166072346162, 'n_estimators': 293, 'subsample': 0.5459114625373183, 'colsample_bytree': 0.7572492684608587, 'min_child_weight': 3, 'gamma': 4.7453768486131995, 'reg_alpha': 2.0307667126799226e-08, 'reg_lambda': 1.2373835145480879e-08, 'max_delta_step': 8}. Best is trial 6 with value: 0.5622593068035944.

Best trial: 6. Best value: 0.562259:  34%|███▍      | 17/50 [02:19<02:07,  3.86s/it]

[I 2025-12-01 22:13:25,403] Trial 16 finished with value: 0.4993581514762516 and parameters: {'max_depth': 9, 'learning_rate': 0.12258255943069743, 'n_estimators': 208, 'subsample': 0.6783812861354588, 'colsample_bytree': 0.6741793296343513, 'min_child_weight': 4, 'gamma': 2.333970420119057, 'reg_alpha': 1.0693534518188309e-08, 'reg_lambda': 1.749163206266457e-08, 'max_delta_step': 0}. Best is trial 6 with value: 0.5622593068035944.

Best trial: 6. Best value: 0.562259:  36%|███▌      | 18/50 [02:28<02:52,  5.39s/it]

[I 2025-12-01 22:13:34,372] Trial 20 pruned.

Best trial: 6. Best value: 0.562259:  38%|███▊      | 19/50 [02:32<02:32,  4.93s/it]

[I 2025-12-01 22:13:38,234] Trial 18 finished with value: 0.511553273427471 and parameters: {'max_depth': 9, 'learning_rate': 0.07054411354040753, 'n_estimators': 386, 'subsample': 0.6957292891726239, 'colsample_bytree': 0.6302608137837654, 'min_child_weight': 4, 'gamma': 1.349592507087589, 'reg_alpha': 1.5417437311971244e-05, 'reg_lambda': 1.3785046802954612e-06, 'max_delta_step': 0}. Best is trial 6 with value: 0.5622593068035944.

Best trial: 9. Best value: 0.588575:  40%|████      | 20/50 [02:43<03:25,  6.85s/it]

[I 2025-12-01 22:13:49,557] Trial 9 finished with value: 0.5885750962772786 and parameters: {'max_depth': 8, 'learning_rate': 0.04375186298837513, 'n_estimators': 1454, 'subsample': 0.9817025076194323, 'colsample_bytree': 0.8064164902871549, 'min_child_weight': 4, 'gamma': 3.0513051563637945, 'reg_alpha': 0.0037936893360364663, 'reg_lambda': 0.003286398297296618, 'max_delta_step': 7}. Best is trial 9 with value: 0.5885750962772786.

Best trial: 9. Best value: 0.588575:  42%|████▏     | 21/50 [02:44<02:32,  5.25s/it]

[I 2025-12-01 22:13:51,072] Trial 19 pruned.

Best trial: 9. Best value: 0.588575:  44%|████▍     | 22/50 [02:48<02:09,  4.62s/it]

[I 2025-12-01 22:13:54,227] Trial 21 finished with value: 0.511553273427471 and parameters: {'max_depth': 6, 'learning_rate': 0.25153695466704934, 'n_estimators': 410, 'subsample': 0.7303442398457263, 'colsample_bytree': 0.5021577452436321, 'min_child_weight': 6, 'gamma': 1.6963174107131467, 'reg_alpha': 0.01788304178765884, 'reg_lambda': 0.0036763398406801087, 'max_delta_step': 10}. Best is trial 9 with value: 0.5885750962772786.

Best trial: 9. Best value: 0.588575:  46%|████▌     | 23/50 [02:56<02:34,  5.73s/it]

[I 2025-12-01 22:14:02,536] Trial 23 pruned.

Best trial: 9. Best value: 0.588575:  48%|████▊     | 24/50 [02:59<02:06,  4.87s/it]

[I 2025-12-01 22:14:05,393] Trial 25 pruned.

Best trial: 9. Best value: 0.588575:  50%|█████     | 25/50 [03:01<01:38,  3.96s/it]

[I 2025-12-01 22:14:07,239] Trial 22 finished with value: 0.5378690629011553 and parameters: {'max_depth': 6, 'learning_rate': 0.022034914163844854, 'n_estimators': 518, 'subsample': 0.7558401704363547, 'colsample_bytree': 0.5163716281756443, 'min_child_weight': 6, 'gamma': 0.06868439490623501, 'reg_alpha': 0.019826295027027634, 'reg_lambda': 0.002866319722534321, 'max_delta_step': 10}. Best is trial 9 with value: 0.5885750962772786.

Best trial: 9. Best value: 0.588575:  52%|█████▏    | 26/50 [03:27<04:13, 10.57s/it]

[I 2025-12-01 22:14:33,229] Trial 27 pruned.

Best trial: 9. Best value: 0.588575:  54%|█████▍    | 27/50 [03:34<03:41,  9.65s/it]

[I 2025-12-01 22:14:40,718] Trial 29 pruned.

Best trial: 9. Best value: 0.588575:  56%|█████▌    | 28/50 [03:35<02:35,  7.06s/it]

[I 2025-12-01 22:14:41,748] Trial 26 finished with value: 0.5500641848523748 and parameters: {'max_depth': 9, 'learning_rate': 0.01939654900763784, 'n_estimators': 581, 'subsample': 0.5987682998126004, 'colsample_bytree': 0.8573391265409427, 'min_child_weight': 3, 'gamma': 2.808515641517329, 'reg_alpha': 0.028745324702871132, 'reg_lambda': 0.0024367170731688817, 'max_delta_step': 7}. Best is trial 9 with value: 0.5885750962772786.

Best trial: 9. Best value: 0.588575:  58%|█████▊    | 29/50 [03:40<02:14,  6.41s/it]

[I 2025-12-01 22:14:46,626] Trial 30 pruned.

Best trial: 9. Best value: 0.588575:  60%|██████    | 30/50 [03:43<01:48,  5.42s/it]

[I 2025-12-01 22:14:49,735] Trial 31 pruned.

Best trial: 9. Best value: 0.588575:  62%|██████▏   | 31/50 [03:50<01:49,  5.76s/it]

[I 2025-12-01 22:14:56,305] Trial 24 finished with value: 0.5603337612323491 and parameters: {'max_depth': 9, 'learning_rate': 0.024326934555737235, 'n_estimators': 1105, 'subsample': 0.9279822163104631, 'colsample_bytree': 0.8240136858621915, 'min_child_weight': 3, 'gamma': 2.670633673805709, 'reg_alpha': 0.01984245104290747, 'reg_lambda': 0.0020883302797690463, 'max_delta_step': 7}. Best is trial 9 with value: 0.5885750962772786.

Best trial: 9. Best value: 0.588575:  64%|██████▍   | 32/50 [03:50<01:14,  4.13s/it]

[I 2025-12-01 22:14:56,613] Trial 33 pruned.

Best trial: 9. Best value: 0.588575:  66%|██████▌   | 33/50 [03:58<01:29,  5.28s/it]

[I 2025-12-01 22:15:04,597] Trial 28 finished with value: 0.5500641848523748 and parameters: {'max_depth': 9, 'learning_rate': 0.03816339337871698, 'n_estimators': 1353, 'subsample': 0.7909964356172161, 'colsample_bytree': 0.7165242878806591, 'min_child_weight': 5, 'gamma': 3.8130592958552065, 'reg_alpha': 0.00037839402386192377, 'reg_lambda': 1.601105874300265e-05, 'max_delta_step': 8}. Best is trial 9 with value: 0.5885750962772786.

Best trial: 9. Best value: 0.588575:  68%|██████▊   | 34/50 [04:40<04:21, 16.36s/it]

[I 2025-12-01 22:15:46,798] Trial 32 finished with value: 0.5744544287548139 and parameters: {'max_depth': 8, 'learning_rate': 0.04697373255926081, 'n_estimators': 1021, 'subsample': 0.9924913960570719, 'colsample_bytree': 0.9123234599739595, 'min_child_weight': 2, 'gamma': 3.1226127386795177, 'reg_alpha': 0.00016681494037066558, 'reg_lambda': 0.37485178023100213, 'max_delta_step': 8}. Best is trial 9 with value: 0.5885750962772786.

Best trial: 9. Best value: 0.588575:  70%|███████   | 35/50 [04:54<03:53, 15.55s/it]

[I 2025-12-01 22:16:00,452] Trial 34 finished with value: 0.5603337612323491 and parameters: {'max_depth': 9, 'learning_rate': 0.014337790224172921, 'n_estimators': 1031, 'subsample': 0.9220450542698828, 'colsample_bytree': 0.8597916768371481, 'min_child_weight': 3, 'gamma': 3.204802535501281, 'reg_alpha': 0.0002696244873454165, 'reg_lambda': 0.007822493612667545, 'max_delta_step': 7}. Best is trial 9 with value: 0.5885750962772786.

Best trial: 9. Best value: 0.588575:  72%|███████▏  | 36/50 [04:55<02:38, 11.30s/it]

[I 2025-12-01 22:16:01,838] Trial 35 finished with value: 0.5622593068035944 and parameters: {'max_depth': 9, 'learning_rate': 0.01357232068714002, 'n_estimators': 1052, 'subsample': 0.9994816745265563, 'colsample_bytree': 0.7774963300219815, 'min_child_weight': 3, 'gamma': 1.9681677625298986, 'reg_alpha': 9.39820471280223e-05, 'reg_lambda': 0.0003609786037587013, 'max_delta_step': 8}. Best is trial 9 with value: 0.5885750962772786.

Best trial: 9. Best value: 0.588575:  74%|███████▍  | 37/50 [04:58<01:52,  8.62s/it]

[I 2025-12-01 22:16:04,194] Trial 36 finished with value: 0.576379974326059 and parameters: {'max_depth': 8, 'learning_rate': 0.03029717551682061, 'n_estimators': 1039, 'subsample': 0.9761112554969539, 'colsample_bytree': 0.9074521671160904, 'min_child_weight': 3, 'gamma': 3.10063089273388, 'reg_alpha': 0.007397215438153396, 'reg_lambda': 0.013104654504665875, 'max_delta_step': 9}. Best is trial 9 with value: 0.5885750962772786.

Best trial: 9. Best value: 0.588575:  76%|███████▌  | 38/50 [05:04<01:36,  8.07s/it]

[I 2025-12-01 22:16:10,993] Trial 37 pruned.

Best trial: 9. Best value: 0.588575:  78%|███████▊  | 39/50 [05:18<01:47,  9.75s/it]

[I 2025-12-01 22:16:24,647] Trial 41 pruned.

Best trial: 9. Best value: 0.588575:  80%|████████  | 40/50 [05:21<01:16,  7.63s/it]

[I 2025-12-01 22:16:27,354] Trial 39 pruned.

Best trial: 9. Best value: 0.588575:  82%|████████▏ | 41/50 [05:21<00:49,  5.45s/it]

[I 2025-12-01 22:16:27,700] Trial 38 pruned.

Best trial: 9. Best value: 0.588575:  84%|████████▍ | 42/50 [05:28<00:46,  5.84s/it]

[I 2025-12-01 22:16:34,444] Trial 44 pruned.

Best trial: 9. Best value: 0.588575:  86%|████████▌ | 43/50 [05:29<00:30,  4.34s/it]

[I 2025-12-01 22:16:35,300] Trial 40 pruned.

Best trial: 9. Best value: 0.588575:  88%|████████▊ | 44/50 [05:43<00:44,  7.44s/it]

[I 2025-12-01 22:16:49,971] Trial 42 pruned.

Best trial: 9. Best value: 0.588575:  90%|█████████ | 45/50 [05:44<00:26,  5.38s/it]

[I 2025-12-01 22:16:50,532] Trial 46 pruned.

Best trial: 9. Best value: 0.588575:  92%|█████████▏| 46/50 [05:50<00:22,  5.71s/it]

[I 2025-12-01 22:16:57,017] Trial 48 pruned.

Best trial: 9. Best value: 0.588575:  94%|█████████▍| 47/50 [05:53<00:13,  4.64s/it]

[I 2025-12-01 22:16:59,150] Trial 47 pruned.

Best trial: 9. Best value: 0.588575:  96%|█████████▌| 48/50 [05:57<00:09,  4.68s/it]

[I 2025-12-01 22:17:03,940] Trial 43 finished with value: 0.5256739409499358 and parameters: {'max_depth': 8, 'learning_rate': 0.06543075732939586, 'n_estimators': 728, 'subsample': 0.8820042343200676, 'colsample_bytree': 0.966877604658469, 'min_child_weight': 4, 'gamma': 1.0148583064786645, 'reg_alpha': 0.004766655468824956, 'reg_lambda': 0.01291328688783509, 'max_delta_step': 6}. Best is trial 9 with value: 0.5885750962772786.

Best trial: 9. Best value: 0.588575:  98%|█████████▊| 49/50 [06:10<00:06,  6.99s/it]

[I 2025-12-01 22:17:16,318] Trial 45 finished with value: 0.5378690629011553 and parameters: {'max_depth': 8, 'learning_rate': 0.0628063376571011, 'n_estimators': 968, 'subsample': 0.8865016676181161, 'colsample_bytree': 0.9644241585815987, 'min_child_weight': 4, 'gamma': 2.341620388259121, 'reg_alpha': 0.0011509423898387347, 'reg_lambda': 6.518994149588043e-05, 'max_delta_step': 6}. Best is trial 9 with value: 0.5885750962772786.

Best trial: 9. Best value: 0.588575: 100%|██████████| 50/50 [06:41<00:00,  8.03s/it]

[I 2025-12-01 22:17:47,740] Trial 49 finished with value: 0.5622593068035944 and parameters: {'max_depth': 4, 'learning_rate': 0.010369447478496639, 'n_estimators': 969, 'subsample': 0.9482916046854175, 'colsample_bytree': 0.9751439986995022, 'min_child_weight': 4, 'gamma': 1.7191771428536722, 'reg_alpha': 2.4678045631517824e-05, 'reg_lambda': 0.0008180362621974214, 'max_delta_step': 4}. Best is trial 9 with value: 0.5885750962772786.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 22:17:52,804] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.480263:   2%|▏         | 1/50 [00:15<12:18, 15.08s/it]

[I 2025-12-01 22:18:07,878] Trial 0 finished with value: 0.48026315789473684 and parameters: {'max_depth': 4, 'learning_rate': 0.15792324843760494, 'n_estimators': 267, 'subsample': 0.8339784503664518, 'colsample_bytree': 0.5087958440574405, 'min_child_weight': 4, 'gamma': 2.246351581146206, 'reg_alpha': 2.9922370035489143e-07, 'reg_lambda': 3.317752427530751, 'max_delta_step': 9}. Best is trial 0 with value: 0.48026315789473684.

Best trial: 1. Best value: 0.639474:   4%|▍         | 2/50 [00:25<10:05, 12.61s/it]

[I 2025-12-01 22:18:18,753] Trial 1 finished with value: 0.6394736842105263 and parameters: {'max_depth': 3, 'learning_rate': 0.04355791993133569, 'n_estimators': 457, 'subsample': 0.8342741252582058, 'colsample_bytree': 0.7113876569519298, 'min_child_weight': 6, 'gamma': 0.5760307949372256, 'reg_alpha': 0.14341922617547748, 'reg_lambda': 0.0017751133708685445, 'max_delta_step': 9}. Best is trial 1 with value: 0.6394736842105263.

Best trial: 1. Best value: 0.639474:   8%|▊         | 4/50 [00:28<03:43,  4.86s/it]

[I 2025-12-01 22:18:21,159] Trial 2 finished with value: 0.375 and parameters: {'max_depth': 3, 'learning_rate': 0.13812031906606984, 'n_estimators': 628, 'subsample': 0.6672250104881574, 'colsample_bytree': 0.739904795010775, 'min_child_weight': 9, 'gamma': 0.40561310356246105, 'reg_alpha': 5.038815779363802e-07, 'reg_lambda': 0.00015715556035062953, 'max_delta_step': 5}. Best is trial 1 with value: 0.6394736842105263.
[I 2025-12-01 22:18:21,276] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.052313752179944197, 'n_estimators': 651, 'subsample': 0.8850713404057928, 'colsample_bytree': 0.5655941497396515, 'min_child_weight': 10, 'gamma': 0.43221448192210965, 'reg_alpha': 2.41441997427275e-07, 'reg_lambda': 0.0009272119148542414, 'max_delta_step': 4}. Best is trial 1 with value: 0.6394736842105263.

Best trial: 1. Best value: 0.639474:  10%|█         | 5/50 [00:37<04:38,  6.18s/it]

[I 2025-12-01 22:18:29,809] Trial 4 finished with value: 0.5868421052631578 and parameters: {'max_depth': 8, 'learning_rate': 0.029427761938357343, 'n_estimators': 343, 'subsample': 0.7548877225981345, 'colsample_bytree': 0.7067166369243063, 'min_child_weight': 6, 'gamma': 0.9221933646518798, 'reg_alpha': 2.768709013808935e-07, 'reg_lambda': 0.008025167705513047, 'max_delta_step': 4}. Best is trial 1 with value: 0.6394736842105263.

Best trial: 1. Best value: 0.639474:  12%|█▏        | 6/50 [00:54<07:19,  9.99s/it]

[I 2025-12-01 22:18:47,194] Trial 8 finished with value: 0.5190789473684211 and parameters: {'max_depth': 5, 'learning_rate': 0.1695671840697753, 'n_estimators': 342, 'subsample': 0.5880692766666928, 'colsample_bytree': 0.7095063441994321, 'min_child_weight': 3, 'gamma': 2.5101957090106035, 'reg_alpha': 0.8512836735205361, 'reg_lambda': 7.333388548667579e-05, 'max_delta_step': 7}. Best is trial 1 with value: 0.6394736842105263.

Best trial: 1. Best value: 0.639474:  14%|█▍        | 7/50 [00:59<06:07,  8.54s/it]

[I 2025-12-01 22:18:52,735] Trial 5 finished with value: 0.5703947368421052 and parameters: {'max_depth': 9, 'learning_rate': 0.10863120445766251, 'n_estimators': 754, 'subsample': 0.5090950908573761, 'colsample_bytree': 0.618750537711811, 'min_child_weight': 3, 'gamma': 1.2807424025426795, 'reg_alpha': 9.87711393593603e-05, 'reg_lambda': 1.604101104215747e-08, 'max_delta_step': 10}. Best is trial 1 with value: 0.6394736842105263.

Best trial: 1. Best value: 0.639474:  16%|█▌        | 8/50 [01:10<06:25,  9.18s/it]

[I 2025-12-01 22:19:03,305] Trial 7 finished with value: 0.5190789473684211 and parameters: {'max_depth': 6, 'learning_rate': 0.2299478696845225, 'n_estimators': 907, 'subsample': 0.852938898668455, 'colsample_bytree': 0.7671471791603222, 'min_child_weight': 2, 'gamma': 1.193035378572772, 'reg_alpha': 1.4577062648201446e-07, 'reg_lambda': 6.758076569131419e-05, 'max_delta_step': 3}. Best is trial 1 with value: 0.6394736842105263.

Best trial: 1. Best value: 0.639474:  18%|█▊        | 9/50 [01:18<05:59,  8.76s/it]

[I 2025-12-01 22:19:11,148] Trial 10 finished with value: 0.475 and parameters: {'max_depth': 6, 'learning_rate': 0.01811783363345379, 'n_estimators': 394, 'subsample': 0.5035229331290714, 'colsample_bytree': 0.9922669887965497, 'min_child_weight': 8, 'gamma': 4.439538493359124, 'reg_alpha': 0.946411358949221, 'reg_lambda': 0.0001222443756716697, 'max_delta_step': 9}. Best is trial 1 with value: 0.6394736842105263.

Best trial: 1. Best value: 0.639474:  20%|██        | 10/50 [01:30<06:29,  9.74s/it]

[I 2025-12-01 22:19:23,062] Trial 6 finished with value: 0.5842105263157895 and parameters: {'max_depth': 5, 'learning_rate': 0.032165098264068895, 'n_estimators': 1260, 'subsample': 0.5351286379832911, 'colsample_bytree': 0.9413466919445865, 'min_child_weight': 3, 'gamma': 3.2073651958102207, 'reg_alpha': 3.771468407855311e-07, 'reg_lambda': 1.5798146097239448e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.6394736842105263.

Best trial: 1. Best value: 0.639474:  22%|██▏       | 11/50 [01:36<05:38,  8.67s/it]

[I 2025-12-01 22:19:29,325] Trial 12 pruned.

Best trial: 1. Best value: 0.639474:  24%|██▍       | 12/50 [01:40<04:33,  7.19s/it]

[I 2025-12-01 22:19:33,113] Trial 11 pruned.

Best trial: 1. Best value: 0.639474:  26%|██▌       | 13/50 [01:41<03:16,  5.32s/it]

[I 2025-12-01 22:19:34,135] Trial 14 pruned.

Best trial: 1. Best value: 0.639474:  28%|██▊       | 14/50 [01:44<02:48,  4.69s/it]

[I 2025-12-01 22:19:37,377] Trial 9 finished with value: 0.5717105263157894 and parameters: {'max_depth': 8, 'learning_rate': 0.0329924524981429, 'n_estimators': 1067, 'subsample': 0.6058708977765074, 'colsample_bytree': 0.9010000075274929, 'min_child_weight': 4, 'gamma': 3.6676655024138722, 'reg_alpha': 6.12396712617149e-08, 'reg_lambda': 1.0852184863501712e-08, 'max_delta_step': 2}. Best is trial 1 with value: 0.6394736842105263.

Best trial: 1. Best value: 0.639474:  30%|███       | 15/50 [01:53<03:24,  5.85s/it]

[I 2025-12-01 22:19:45,917] Trial 15 finished with value: 0.5730263157894737 and parameters: {'max_depth': 8, 'learning_rate': 0.03865933279564465, 'n_estimators': 202, 'subsample': 0.7573298845164691, 'colsample_bytree': 0.6591149030886075, 'min_child_weight': 6, 'gamma': 1.3224092502888416, 'reg_alpha': 0.0007916744049525884, 'reg_lambda': 0.011092278608987708, 'max_delta_step': 0}. Best is trial 1 with value: 0.6394736842105263.

Best trial: 1. Best value: 0.639474:  32%|███▏      | 16/50 [01:54<02:37,  4.63s/it]

[I 2025-12-01 22:19:47,716] Trial 16 finished with value: 0.5743421052631579 and parameters: {'max_depth': 8, 'learning_rate': 0.037317951281827, 'n_estimators': 200, 'subsample': 0.7568257744057961, 'colsample_bytree': 0.8965075277666125, 'min_child_weight': 6, 'gamma': 0.05697029717503688, 'reg_alpha': 4.9796677067482763e-05, 'reg_lambda': 0.018358336947148543, 'max_delta_step': 1}. Best is trial 1 with value: 0.6394736842105263.

Best trial: 1. Best value: 0.639474:  34%|███▍      | 17/50 [01:56<02:00,  3.64s/it]

[I 2025-12-01 22:19:49,039] Trial 17 finished with value: 0.6243421052631579 and parameters: {'max_depth': 7, 'learning_rate': 0.07488819782755761, 'n_estimators': 202, 'subsample': 0.7409510451458842, 'colsample_bytree': 0.6733944598618462, 'min_child_weight': 6, 'gamma': 0.10900073551720157, 'reg_alpha': 5.449118681812464e-05, 'reg_lambda': 0.007396861848894583, 'max_delta_step': 6}. Best is trial 1 with value: 0.6394736842105263.

Best trial: 1. Best value: 0.639474:  36%|███▌      | 18/50 [02:00<02:01,  3.78s/it]

[I 2025-12-01 22:19:53,156] Trial 20 pruned.

Best trial: 1. Best value: 0.639474:  38%|███▊      | 19/50 [02:01<01:34,  3.03s/it]

[I 2025-12-01 22:19:54,446] Trial 13 pruned.

Best trial: 1. Best value: 0.639474:  40%|████      | 20/50 [02:05<01:34,  3.16s/it]

[I 2025-12-01 22:19:57,918] Trial 21 pruned.

Best trial: 1. Best value: 0.639474:  42%|████▏     | 21/50 [02:05<01:07,  2.34s/it]

[I 2025-12-01 22:19:58,341] Trial 22 pruned.

Best trial: 1. Best value: 0.639474:  44%|████▍     | 22/50 [02:10<01:23,  3.00s/it]

[I 2025-12-01 22:20:02,872] Trial 24 pruned.

Best trial: 1. Best value: 0.639474:  46%|████▌     | 23/50 [02:19<02:14,  4.96s/it]

[I 2025-12-01 22:20:12,422] Trial 19 finished with value: 0.6269736842105263 and parameters: {'max_depth': 7, 'learning_rate': 0.0746195418825615, 'n_estimators': 504, 'subsample': 0.9156433643880382, 'colsample_bytree': 0.7076788737199915, 'min_child_weight': 8, 'gamma': 1.9336640115492925, 'reg_alpha': 1.301560893847945e-05, 'reg_lambda': 0.7629046650049541, 'max_delta_step': 6}. Best is trial 1 with value: 0.6394736842105263.

Best trial: 1. Best value: 0.639474:  48%|████▊     | 24/50 [02:22<01:49,  4.23s/it]

[I 2025-12-01 22:20:14,936] Trial 18 finished with value: 0.6144736842105263 and parameters: {'max_depth': 7, 'learning_rate': 0.07457426977341007, 'n_estimators': 551, 'subsample': 0.75511428766734, 'colsample_bytree': 0.8546794891419923, 'min_child_weight': 7, 'gamma': 0.28171747389708646, 'reg_alpha': 0.0002639017434408227, 'reg_lambda': 5.483856170516731, 'max_delta_step': 6}. Best is trial 1 with value: 0.6394736842105263.

Best trial: 1. Best value: 0.639474:  50%|█████     | 25/50 [02:29<02:05,  5.02s/it]

[I 2025-12-01 22:20:21,807] Trial 27 pruned.

Best trial: 1. Best value: 0.639474:  52%|█████▏    | 26/50 [02:30<01:35,  4.00s/it]

[I 2025-12-01 22:20:23,414] Trial 26 pruned.

Best trial: 1. Best value: 0.639474:  54%|█████▍    | 27/50 [02:34<01:29,  3.89s/it]

[I 2025-12-01 22:20:27,051] Trial 29 pruned.

Best trial: 1. Best value: 0.639474:  56%|█████▌    | 28/50 [02:39<01:35,  4.33s/it]

[I 2025-12-01 22:20:32,397] Trial 30 pruned.

Best trial: 1. Best value: 0.639474:  58%|█████▊    | 29/50 [02:40<01:06,  3.17s/it]

[I 2025-12-01 22:20:32,868] Trial 28 pruned.

Best trial: 1. Best value: 0.639474:  60%|██████    | 30/50 [02:44<01:08,  3.41s/it]

[I 2025-12-01 22:20:36,849] Trial 31 pruned.

Best trial: 1. Best value: 0.639474:  62%|██████▏   | 31/50 [02:50<01:20,  4.21s/it]

[I 2025-12-01 22:20:42,919] Trial 32 pruned.

Best trial: 1. Best value: 0.639474:  64%|██████▍   | 32/50 [03:03<02:05,  6.97s/it]

[I 2025-12-01 22:20:56,334] Trial 33 finished with value: 0.5730263157894737 and parameters: {'max_depth': 9, 'learning_rate': 0.043351214921719096, 'n_estimators': 280, 'subsample': 0.8436291929532507, 'colsample_bytree': 0.6859954765814822, 'min_child_weight': 5, 'gamma': 1.5416869552227899, 'reg_alpha': 1.497003954859142e-06, 'reg_lambda': 2.4361847333784805, 'max_delta_step': 9}. Best is trial 1 with value: 0.6394736842105263.

Best trial: 1. Best value: 0.639474:  68%|██████▊   | 34/50 [03:08<01:11,  4.45s/it]

[I 2025-12-01 22:21:01,054] Trial 34 pruned.
[I 2025-12-01 22:21:01,190] Trial 35 pruned.

Best trial: 1. Best value: 0.639474:  70%|███████   | 35/50 [03:13<01:07,  4.53s/it]

[I 2025-12-01 22:21:05,918] Trial 36 pruned.

Best trial: 1. Best value: 0.639474:  72%|███████▏  | 36/50 [03:13<00:47,  3.38s/it]

[I 2025-12-01 22:21:06,628] Trial 37 pruned.

Best trial: 1. Best value: 0.639474:  74%|███████▍  | 37/50 [03:14<00:33,  2.56s/it]

[I 2025-12-01 22:21:07,271] Trial 23 finished with value: 0.5967105263157895 and parameters: {'max_depth': 4, 'learning_rate': 0.020881160826184672, 'n_estimators': 1425, 'subsample': 0.8085404514141927, 'colsample_bytree': 0.532199686932591, 'min_child_weight': 5, 'gamma': 0.7269110080772871, 'reg_alpha': 5.433903891964467e-06, 'reg_lambda': 0.001193889293946555, 'max_delta_step': 6}. Best is trial 1 with value: 0.6394736842105263.

Best trial: 1. Best value: 0.639474:  76%|███████▌  | 38/50 [03:17<00:31,  2.62s/it]

[I 2025-12-01 22:21:10,030] Trial 39 pruned.

Best trial: 1. Best value: 0.639474:  78%|███████▊  | 39/50 [03:18<00:24,  2.25s/it]

[I 2025-12-01 22:21:11,414] Trial 40 pruned.

Best trial: 25. Best value: 0.650658:  80%|████████  | 40/50 [03:22<00:25,  2.59s/it]

[I 2025-12-01 22:21:14,811] Trial 25 finished with value: 0.6506578947368421 and parameters: {'max_depth': 7, 'learning_rate': 0.02033631650552427, 'n_estimators': 1438, 'subsample': 0.782295748906238, 'colsample_bytree': 0.6525213565812483, 'min_child_weight': 5, 'gamma': 0.7569000281641467, 'reg_alpha': 8.843991676938778e-06, 'reg_lambda': 0.002627620625402962, 'max_delta_step': 6}. Best is trial 25 with value: 0.6506578947368421.

Best trial: 25. Best value: 0.650658:  82%|████████▏ | 41/50 [03:24<00:24,  2.69s/it]

[I 2025-12-01 22:21:17,725] Trial 42 pruned.

Best trial: 25. Best value: 0.650658:  84%|████████▍ | 42/50 [03:25<00:15,  1.98s/it]

[I 2025-12-01 22:21:18,044] Trial 41 pruned.

Best trial: 25. Best value: 0.650658:  86%|████████▌ | 43/50 [03:34<00:29,  4.24s/it]

[I 2025-12-01 22:21:27,568] Trial 43 pruned.

Best trial: 25. Best value: 0.650658:  88%|████████▊ | 44/50 [03:46<00:38,  6.49s/it]

[I 2025-12-01 22:21:39,290] Trial 38 finished with value: 0.5842105263157895 and parameters: {'max_depth': 6, 'learning_rate': 0.060691889507737705, 'n_estimators': 680, 'subsample': 0.6677871216755199, 'colsample_bytree': 0.6244849869632239, 'min_child_weight': 4, 'gamma': 0.8160641776216706, 'reg_alpha': 0.0016054289741273438, 'reg_lambda': 0.0003353380244964371, 'max_delta_step': 5}. Best is trial 25 with value: 0.6506578947368421.

Best trial: 25. Best value: 0.650658:  90%|█████████ | 45/50 [04:12<01:01, 12.26s/it]

[I 2025-12-01 22:22:05,028] Trial 44 finished with value: 0.6118421052631579 and parameters: {'max_depth': 7, 'learning_rate': 0.02750271936524778, 'n_estimators': 1011, 'subsample': 0.7688400340108628, 'colsample_bytree': 0.6269409979606261, 'min_child_weight': 6, 'gamma': 0.5869445005080531, 'reg_alpha': 0.0003104134569300776, 'reg_lambda': 0.0002879081927090259, 'max_delta_step': 7}. Best is trial 25 with value: 0.6506578947368421.

Best trial: 25. Best value: 0.650658:  92%|█████████▏| 46/50 [04:15<00:38,  9.50s/it]

[I 2025-12-01 22:22:08,086] Trial 48 pruned.

Best trial: 45. Best value: 0.703289:  94%|█████████▍| 47/50 [04:16<00:21,  7.01s/it]

[I 2025-12-01 22:22:09,277] Trial 45 finished with value: 0.7032894736842106 and parameters: {'max_depth': 7, 'learning_rate': 0.02660839822196817, 'n_estimators': 1076, 'subsample': 0.8307464051908025, 'colsample_bytree': 0.635470200725095, 'min_child_weight': 6, 'gamma': 0.5939363653377571, 'reg_alpha': 0.000172917727650947, 'reg_lambda': 0.00048474215289959937, 'max_delta_step': 7}. Best is trial 45 with value: 0.7032894736842106.

Best trial: 45. Best value: 0.703289:  96%|█████████▌| 48/50 [04:32<00:19,  9.71s/it]

[I 2025-12-01 22:22:25,282] Trial 46 finished with value: 0.6519736842105264 and parameters: {'max_depth': 7, 'learning_rate': 0.016185705046684803, 'n_estimators': 1211, 'subsample': 0.8338382177687031, 'colsample_bytree': 0.678538306923939, 'min_child_weight': 6, 'gamma': 0.6107169599208754, 'reg_alpha': 0.0002978034112187168, 'reg_lambda': 0.005079909039507218, 'max_delta_step': 7}. Best is trial 45 with value: 0.7032894736842106.

Best trial: 45. Best value: 0.703289:  98%|█████████▊| 49/50 [04:36<00:07,  7.88s/it]

[I 2025-12-01 22:22:28,893] Trial 47 finished with value: 0.7032894736842106 and parameters: {'max_depth': 7, 'learning_rate': 0.1346713460562998, 'n_estimators': 1351, 'subsample': 0.7757137101418503, 'colsample_bytree': 0.6853273413868924, 'min_child_weight': 6, 'gamma': 0.5300868035615315, 'reg_alpha': 0.0002898339051161899, 'reg_lambda': 0.0064153617206782615, 'max_delta_step': 7}. Best is trial 45 with value: 0.7032894736842106.

Best trial: 45. Best value: 0.703289: 100%|██████████| 50/50 [04:51<00:00,  5.83s/it]

[I 2025-12-01 22:22:44,501] Trial 49 finished with value: 0.5730263157894737 and parameters: {'max_depth': 7, 'learning_rate': 0.013159214809491364, 'n_estimators': 1227, 'subsample': 0.628846681551773, 'colsample_bytree': 0.6705910282631677, 'min_child_weight': 6, 'gamma': 0.2901892298980295, 'reg_alpha': 9.704144004183817e-08, 'reg_lambda': 0.0063503116558084605, 'max_delta_step': 7}. Best is trial 45 with value: 0.7032894736842106.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    17_1         loo       0.588575                    0.75          0.84
1     9_1         loo       0.664474                    0.70          0.81
2    19_1         loo       0.703289                    0.50          0.70
3    15_1         loo       0.564185                    0.40          0.64

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.472456               0.8               0.7        50          60
1  0.377964               0.8               0.6        50          59
2  0.000000               0.2               0.8        50          59
3 -0.277350               0.0               0.8        50          60

   test_size
0         15
1         15
2         15
3         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    17_1         loo       0.588575                    0.75          0.84
1     9_1         loo       0.664474                    0.70          0.81
2    19_1         loo       0.703289                    0.50          0.70
3    15_1         loo       0.564185                    0.40          0.64

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.472456               0.8               0.7        50          60
1  0.377964               0.8               0.6        50          59
2  0.000000               0.2               0.8        50          59
3 -0.277350               0.0               0.8        50          60

   test_size
0         15
1         15
2         15
3         15

In [1572]:
# Temporal embedings
datasets = task_temp_dfs_ad_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    #    scoring="balanced_accuracy",     # or "roc_auc"
    scoring="balanced_accuracy",      
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir="xgb_ad_hc_{CV_STRATEGY}_tasks/xgb_results_temp_ad_hc_extended{CV_STRATEGY}_tasks",
    split_param="emb_",
)
print(summary)

[I 2025-12-01 22:22:50,019] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.363816:   2%|▏         | 1/50 [00:26<21:16, 26.06s/it]

[I 2025-12-01 22:23:16,071] Trial 1 finished with value: 0.3638157894736842 and parameters: {'max_depth': 8, 'learning_rate': 0.2527132154971946, 'n_estimators': 583, 'subsample': 0.6790454922783177, 'colsample_bytree': 0.6289499653889971, 'min_child_weight': 7, 'gamma': 4.767694294571406, 'reg_alpha': 2.2257941580879526, 'reg_lambda': 8.498883720012785, 'max_delta_step': 6}. Best is trial 1 with value: 0.3638157894736842.

Best trial: 1. Best value: 0.363816:   4%|▍         | 2/50 [00:44<17:09, 21.44s/it]

[I 2025-12-01 22:23:34,282] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.11868768247816125, 'n_estimators': 402, 'subsample': 0.9553047379381732, 'colsample_bytree': 0.9800279966893344, 'min_child_weight': 10, 'gamma': 1.7205034905135053, 'reg_alpha': 0.3215792336188295, 'reg_lambda': 1.746241294299107e-08, 'max_delta_step': 4}. Best is trial 1 with value: 0.3638157894736842.

Best trial: 0. Best value: 0.378947:   6%|▌         | 3/50 [00:51<11:34, 14.78s/it]

[I 2025-12-01 22:23:41,135] Trial 0 finished with value: 0.3789473684210526 and parameters: {'max_depth': 3, 'learning_rate': 0.28846271057630524, 'n_estimators': 1228, 'subsample': 0.987064105984544, 'colsample_bytree': 0.7041841926568186, 'min_child_weight': 5, 'gamma': 0.6313178754352439, 'reg_alpha': 1.3230803659766593e-08, 'reg_lambda': 3.37100286783076e-07, 'max_delta_step': 2}. Best is trial 0 with value: 0.3789473684210526.

Best trial: 3. Best value: 0.405263:   8%|▊         | 4/50 [00:52<07:15,  9.47s/it]

[I 2025-12-01 22:23:42,439] Trial 3 finished with value: 0.4052631578947368 and parameters: {'max_depth': 10, 'learning_rate': 0.04091534891221664, 'n_estimators': 1098, 'subsample': 0.6370748737132013, 'colsample_bytree': 0.700838342795011, 'min_child_weight': 5, 'gamma': 3.481104932584911, 'reg_alpha': 3.9932986940489156e-08, 'reg_lambda': 8.995396234248402, 'max_delta_step': 8}. Best is trial 3 with value: 0.4052631578947368.

Best trial: 7. Best value: 0.419079:  10%|█         | 5/50 [01:08<08:49, 11.77s/it]

[I 2025-12-01 22:23:58,312] Trial 7 finished with value: 0.419078947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.12443734474358781, 'n_estimators': 272, 'subsample': 0.9952947734242659, 'colsample_bytree': 0.7512245799704856, 'min_child_weight': 2, 'gamma': 1.008533262001824, 'reg_alpha': 5.2038560521283565e-06, 'reg_lambda': 0.24712409312568875, 'max_delta_step': 5}. Best is trial 7 with value: 0.419078947368421.

Best trial: 7. Best value: 0.419079:  12%|█▏        | 6/50 [01:13<06:57,  9.50s/it]

[I 2025-12-01 22:24:03,391] Trial 2 finished with value: 0.41776315789473684 and parameters: {'max_depth': 7, 'learning_rate': 0.055345737256710124, 'n_estimators': 1300, 'subsample': 0.7699954594369968, 'colsample_bytree': 0.642360038735101, 'min_child_weight': 2, 'gamma': 3.4598894827581894, 'reg_alpha': 1.3617469938449957e-05, 'reg_lambda': 8.540006659019117, 'max_delta_step': 0}. Best is trial 7 with value: 0.419078947368421.

Best trial: 7. Best value: 0.419079:  14%|█▍        | 7/50 [01:21<06:24,  8.93s/it]

[I 2025-12-01 22:24:11,167] Trial 8 finished with value: 0.2125 and parameters: {'max_depth': 7, 'learning_rate': 0.01781122114899962, 'n_estimators': 276, 'subsample': 0.5885894267189533, 'colsample_bytree': 0.6638271014092014, 'min_child_weight': 8, 'gamma': 3.1952935635592956, 'reg_alpha': 2.815695529022493e-07, 'reg_lambda': 6.135305102259764e-08, 'max_delta_step': 9}. Best is trial 7 with value: 0.419078947368421.

Best trial: 7. Best value: 0.419079:  16%|█▌        | 8/50 [01:39<08:21, 11.94s/it]

[I 2025-12-01 22:24:29,562] Trial 6 finished with value: 0.3927631578947368 and parameters: {'max_depth': 5, 'learning_rate': 0.11582255539617936, 'n_estimators': 1024, 'subsample': 0.948464565362996, 'colsample_bytree': 0.7476933649838038, 'min_child_weight': 5, 'gamma': 4.313536283239024, 'reg_alpha': 0.21827732438607225, 'reg_lambda': 0.0006944049638072003, 'max_delta_step': 6}. Best is trial 7 with value: 0.419078947368421.

Best trial: 7. Best value: 0.419079:  18%|█▊        | 9/50 [01:48<07:28, 10.94s/it]

[I 2025-12-01 22:24:38,298] Trial 10 finished with value: 0.125 and parameters: {'max_depth': 9, 'learning_rate': 0.09039845854309671, 'n_estimators': 693, 'subsample': 0.740613826375216, 'colsample_bytree': 0.6243122870436801, 'min_child_weight': 9, 'gamma': 3.1705359161481637, 'reg_alpha': 0.2881073624093597, 'reg_lambda': 0.00033852475960641665, 'max_delta_step': 7}. Best is trial 7 with value: 0.419078947368421.

Best trial: 5. Best value: 0.430263:  20%|██        | 10/50 [02:02<07:58, 11.97s/it]

[I 2025-12-01 22:24:52,579] Trial 5 finished with value: 0.43026315789473685 and parameters: {'max_depth': 9, 'learning_rate': 0.018631491588651225, 'n_estimators': 1244, 'subsample': 0.5969281675296806, 'colsample_bytree': 0.9947303695237273, 'min_child_weight': 2, 'gamma': 4.480977713105234, 'reg_alpha': 0.0014744202226541715, 'reg_lambda': 0.07699320575793016, 'max_delta_step': 0}. Best is trial 5 with value: 0.43026315789473685.

Best trial: 5. Best value: 0.430263:  22%|██▏       | 11/50 [02:03<05:31,  8.50s/it]

[I 2025-12-01 22:24:53,209] Trial 11 pruned.

Best trial: 5. Best value: 0.430263:  24%|██▍       | 12/50 [02:05<04:12,  6.66s/it]

[I 2025-12-01 22:24:55,646] Trial 12 finished with value: 0.43026315789473685 and parameters: {'max_depth': 5, 'learning_rate': 0.16626285616293124, 'n_estimators': 367, 'subsample': 0.7569593542090108, 'colsample_bytree': 0.6897183418290522, 'min_child_weight': 3, 'gamma': 1.6743895074621118, 'reg_alpha': 0.0020942117669318938, 'reg_lambda': 3.632084330595565e-06, 'max_delta_step': 9}. Best is trial 5 with value: 0.43026315789473685.

Best trial: 5. Best value: 0.430263:  26%|██▌       | 13/50 [02:10<03:48,  6.16s/it]

[I 2025-12-01 22:25:00,675] Trial 9 finished with value: 0.41776315789473684 and parameters: {'max_depth': 10, 'learning_rate': 0.01670766326457568, 'n_estimators': 1175, 'subsample': 0.6191557838844122, 'colsample_bytree': 0.6683564741811341, 'min_child_weight': 4, 'gamma': 2.9797637095536023, 'reg_alpha': 1.9768369135577795e-08, 'reg_lambda': 4.5446196586670634e-07, 'max_delta_step': 8}. Best is trial 5 with value: 0.43026315789473685.

Best trial: 5. Best value: 0.430263:  28%|██▊       | 14/50 [02:38<07:33, 12.60s/it]

[I 2025-12-01 22:25:28,150] Trial 15 pruned.

Best trial: 5. Best value: 0.430263:  30%|███       | 15/50 [03:16<11:57, 20.51s/it]

[I 2025-12-01 22:26:06,974] Trial 16 finished with value: 0.43026315789473685 and parameters: {'max_depth': 5, 'learning_rate': 0.037233055257932066, 'n_estimators': 1472, 'subsample': 0.5151564475849922, 'colsample_bytree': 0.5267372413257025, 'min_child_weight': 1, 'gamma': 1.7678815119859659, 'reg_alpha': 0.002661391615443364, 'reg_lambda': 0.016639719405757255, 'max_delta_step': 10}. Best is trial 5 with value: 0.43026315789473685.

Best trial: 5. Best value: 0.430263:  32%|███▏      | 16/50 [03:27<09:54, 17.49s/it]

[I 2025-12-01 22:26:17,457] Trial 18 pruned.

Best trial: 5. Best value: 0.430263:  34%|███▍      | 17/50 [03:31<07:20, 13.33s/it]

[I 2025-12-01 22:26:21,124] Trial 17 pruned.

Best trial: 20. Best value: 0.455263:  36%|███▌      | 18/50 [03:59<09:30, 17.83s/it]

[I 2025-12-01 22:26:49,413] Trial 20 finished with value: 0.4552631578947368 and parameters: {'max_depth': 4, 'learning_rate': 0.06579043429757535, 'n_estimators': 540, 'subsample': 0.7359307319864176, 'colsample_bytree': 0.8386554187352326, 'min_child_weight': 3, 'gamma': 2.394266242404065, 'reg_alpha': 0.017639207920394712, 'reg_lambda': 0.00830474329643935, 'max_delta_step': 1}. Best is trial 20 with value: 0.4552631578947368.

Best trial: 20. Best value: 0.455263:  38%|███▊      | 19/50 [04:02<06:58, 13.50s/it]

[I 2025-12-01 22:26:52,826] Trial 13 finished with value: 0.42894736842105263 and parameters: {'max_depth': 5, 'learning_rate': 0.010540064696929422, 'n_estimators': 1457, 'subsample': 0.5040210677890724, 'colsample_bytree': 0.9870085697682482, 'min_child_weight': 1, 'gamma': 1.913133270511953, 'reg_alpha': 0.0033101302643917486, 'reg_lambda': 0.02377404123604049, 'max_delta_step': 0}. Best is trial 20 with value: 0.4552631578947368.

Best trial: 20. Best value: 0.455263:  40%|████      | 20/50 [04:13<06:18, 12.63s/it]

[I 2025-12-01 22:27:03,438] Trial 14 finished with value: 0.4552631578947368 and parameters: {'max_depth': 3, 'learning_rate': 0.01030175844101789, 'n_estimators': 1484, 'subsample': 0.503540288240757, 'colsample_bytree': 0.9830957120406154, 'min_child_weight': 1, 'gamma': 0.39628732437938197, 'reg_alpha': 0.0016355328444835628, 'reg_lambda': 0.028624137296257898, 'max_delta_step': 3}. Best is trial 20 with value: 0.4552631578947368.

Best trial: 20. Best value: 0.455263:  42%|████▏     | 21/50 [04:15<04:35,  9.52s/it]

[I 2025-12-01 22:27:05,700] Trial 19 pruned.

Best trial: 21. Best value: 0.470395:  44%|████▍     | 22/50 [04:24<04:22,  9.37s/it]

[I 2025-12-01 22:27:14,716] Trial 21 finished with value: 0.47039473684210525 and parameters: {'max_depth': 4, 'learning_rate': 0.06066864180076414, 'n_estimators': 484, 'subsample': 0.5591706498835206, 'colsample_bytree': 0.882048243941823, 'min_child_weight': 4, 'gamma': 4.975203693317382, 'reg_alpha': 0.012835417367671886, 'reg_lambda': 0.12478306026658584, 'max_delta_step': 0}. Best is trial 21 with value: 0.47039473684210525.

Best trial: 21. Best value: 0.470395:  46%|████▌     | 23/50 [04:29<03:38,  8.08s/it]

[I 2025-12-01 22:27:19,788] Trial 22 finished with value: 0.43157894736842106 and parameters: {'max_depth': 4, 'learning_rate': 0.06718398223345277, 'n_estimators': 523, 'subsample': 0.569791426055374, 'colsample_bytree': 0.8681723336367642, 'min_child_weight': 4, 'gamma': 4.999197501956418, 'reg_alpha': 0.03884267449486807, 'reg_lambda': 0.3563800005990058, 'max_delta_step': 1}. Best is trial 21 with value: 0.47039473684210525.

Best trial: 23. Best value: 0.506579:  48%|████▊     | 24/50 [04:45<04:33, 10.52s/it]

[I 2025-12-01 22:27:36,000] Trial 23 finished with value: 0.506578947368421 and parameters: {'max_depth': 4, 'learning_rate': 0.07157805886966823, 'n_estimators': 504, 'subsample': 0.70441756487761, 'colsample_bytree': 0.8605369057983705, 'min_child_weight': 4, 'gamma': 1.0742391624942689, 'reg_alpha': 0.02907426597853534, 'reg_lambda': 0.002106526456764838, 'max_delta_step': 2}. Best is trial 23 with value: 0.506578947368421.

Best trial: 23. Best value: 0.506579:  50%|█████     | 25/50 [04:59<04:43, 11.33s/it]

[I 2025-12-01 22:27:49,203] Trial 26 pruned.

Best trial: 23. Best value: 0.506579:  52%|█████▏    | 26/50 [05:01<03:25,  8.57s/it]

[I 2025-12-01 22:27:51,303] Trial 27 pruned.

Best trial: 23. Best value: 0.506579:  54%|█████▍    | 27/50 [05:06<02:55,  7.64s/it]

[I 2025-12-01 22:27:56,785] Trial 25 finished with value: 0.41776315789473684 and parameters: {'max_depth': 4, 'learning_rate': 0.07304081612925462, 'n_estimators': 500, 'subsample': 0.5556428654230255, 'colsample_bytree': 0.9039206566922466, 'min_child_weight': 4, 'gamma': 1.0418531252404768, 'reg_alpha': 0.03914203034921202, 'reg_lambda': 0.002087259878215635, 'max_delta_step': 2}. Best is trial 23 with value: 0.506578947368421.

Best trial: 23. Best value: 0.506579:  56%|█████▌    | 28/50 [05:08<02:08,  5.86s/it]

[I 2025-12-01 22:27:58,518] Trial 28 pruned.

Best trial: 23. Best value: 0.506579:  58%|█████▊    | 29/50 [05:10<01:37,  4.67s/it]

[I 2025-12-01 22:28:00,398] Trial 29 pruned.

Best trial: 23. Best value: 0.506579:  60%|██████    | 30/50 [05:38<03:52, 11.62s/it]

[I 2025-12-01 22:28:28,231] Trial 30 pruned.

Best trial: 23. Best value: 0.506579:  62%|██████▏   | 31/50 [05:38<02:38,  8.36s/it]

[I 2025-12-01 22:28:28,992] Trial 32 pruned.

Best trial: 23. Best value: 0.506579:  64%|██████▍   | 32/50 [05:39<01:48,  6.05s/it]

[I 2025-12-01 22:28:29,649] Trial 24 finished with value: 0.4164473684210527 and parameters: {'max_depth': 3, 'learning_rate': 0.024308406039216704, 'n_estimators': 942, 'subsample': 0.5653986805504249, 'colsample_bytree': 0.9051220522928802, 'min_child_weight': 2, 'gamma': 0.8704296996967968, 'reg_alpha': 0.02694446927523075, 'reg_lambda': 0.2812417568867722, 'max_delta_step': 2}. Best is trial 23 with value: 0.506578947368421.

Best trial: 23. Best value: 0.506579:  66%|██████▌   | 33/50 [05:45<01:42,  6.02s/it]

[I 2025-12-01 22:28:35,592] Trial 33 pruned.

Best trial: 23. Best value: 0.506579:  68%|██████▊   | 34/50 [05:48<01:21,  5.12s/it]

[I 2025-12-01 22:28:38,619] Trial 34 pruned.

Best trial: 23. Best value: 0.506579:  70%|███████   | 35/50 [05:51<01:08,  4.56s/it]

[I 2025-12-01 22:28:41,866] Trial 35 pruned.

Best trial: 23. Best value: 0.506579:  72%|███████▏  | 36/50 [05:58<01:14,  5.30s/it]

[I 2025-12-01 22:28:48,911] Trial 31 pruned.

Best trial: 23. Best value: 0.506579:  74%|███████▍  | 37/50 [06:25<02:32, 11.71s/it]

[I 2025-12-01 22:29:15,561] Trial 36 finished with value: 0.43026315789473685 and parameters: {'max_depth': 4, 'learning_rate': 0.051164000387522134, 'n_estimators': 583, 'subsample': 0.7249686489639685, 'colsample_bytree': 0.8337529064527253, 'min_child_weight': 4, 'gamma': 2.5054729621403804, 'reg_alpha': 0.01602128997129332, 'reg_lambda': 0.007806448038005854, 'max_delta_step': 1}. Best is trial 23 with value: 0.506578947368421.

Best trial: 23. Best value: 0.506579:  76%|███████▌  | 38/50 [06:26<01:42,  8.57s/it]

[I 2025-12-01 22:29:16,815] Trial 37 finished with value: 0.43157894736842106 and parameters: {'max_depth': 4, 'learning_rate': 0.05083105157361528, 'n_estimators': 587, 'subsample': 0.743411042709193, 'colsample_bytree': 0.8209031586075615, 'min_child_weight': 5, 'gamma': 2.7629526949576735, 'reg_alpha': 0.008029770981717702, 'reg_lambda': 0.0038207371573467713, 'max_delta_step': 1}. Best is trial 23 with value: 0.506578947368421.

Best trial: 23. Best value: 0.506579:  78%|███████▊  | 39/50 [06:30<01:18,  7.11s/it]

[I 2025-12-01 22:29:20,504] Trial 38 finished with value: 0.4565789473684211 and parameters: {'max_depth': 6, 'learning_rate': 0.05617139600601874, 'n_estimators': 578, 'subsample': 0.658967818231702, 'colsample_bytree': 0.8297327681604902, 'min_child_weight': 5, 'gamma': 1.4072189017204124, 'reg_alpha': 0.773385319853005, 'reg_lambda': 8.264844722986153e-05, 'max_delta_step': 1}. Best is trial 23 with value: 0.506578947368421.

Best trial: 23. Best value: 0.506579:  80%|████████  | 40/50 [06:33<00:58,  5.90s/it]

[I 2025-12-01 22:29:23,583] Trial 39 finished with value: 0.43026315789473685 and parameters: {'max_depth': 4, 'learning_rate': 0.05863641404018448, 'n_estimators': 592, 'subsample': 0.6422187517627382, 'colsample_bytree': 0.8316727307661208, 'min_child_weight': 5, 'gamma': 3.8485111663874623, 'reg_alpha': 0.8657516954872668, 'reg_lambda': 0.06917815364722339, 'max_delta_step': 1}. Best is trial 23 with value: 0.506578947368421.

Best trial: 23. Best value: 0.506579:  82%|████████▏ | 41/50 [06:57<01:41, 11.24s/it]

[I 2025-12-01 22:29:47,276] Trial 42 finished with value: 0.3927631578947368 and parameters: {'max_depth': 7, 'learning_rate': 0.11031719732260233, 'n_estimators': 459, 'subsample': 0.6218943429750681, 'colsample_bytree': 0.7534546735487355, 'min_child_weight': 7, 'gamma': 1.3127242520550002, 'reg_alpha': 0.8689645735050912, 'reg_lambda': 8.612486806863206e-05, 'max_delta_step': 0}. Best is trial 23 with value: 0.506578947368421.

Best trial: 23. Best value: 0.506579:  84%|████████▍ | 42/50 [07:10<01:35, 11.89s/it]

[I 2025-12-01 22:30:00,699] Trial 44 pruned.

Best trial: 23. Best value: 0.506579:  86%|████████▌ | 43/50 [07:23<01:24, 12.08s/it]

[I 2025-12-01 22:30:13,197] Trial 45 pruned.

Best trial: 41. Best value: 0.507895:  88%|████████▊ | 44/50 [07:35<01:13, 12.24s/it]

[I 2025-12-01 22:30:25,842] Trial 41 finished with value: 0.5078947368421052 and parameters: {'max_depth': 6, 'learning_rate': 0.29505922261087686, 'n_estimators': 1360, 'subsample': 0.6172245687335617, 'colsample_bytree': 0.7410036817759762, 'min_child_weight': 3, 'gamma': 1.3453369619281628, 'reg_alpha': 0.1832692699005932, 'reg_lambda': 0.059457519779910824, 'max_delta_step': 0}. Best is trial 41 with value: 0.5078947368421052.

Best trial: 41. Best value: 0.507895:  90%|█████████ | 45/50 [07:37<00:44,  8.97s/it]

[I 2025-12-01 22:30:27,173] Trial 40 finished with value: 0.444078947368421 and parameters: {'max_depth': 4, 'learning_rate': 0.05621652110241134, 'n_estimators': 1334, 'subsample': 0.6496519059165453, 'colsample_bytree': 0.7545858090495835, 'min_child_weight': 5, 'gamma': 1.3813679278960422, 'reg_alpha': 0.6986327836684223, 'reg_lambda': 0.044488495421626716, 'max_delta_step': 0}. Best is trial 41 with value: 0.5078947368421052.

Best trial: 41. Best value: 0.507895:  92%|█████████▏| 46/50 [07:40<00:29,  7.40s/it]

[I 2025-12-01 22:30:30,911] Trial 43 finished with value: 0.43157894736842106 and parameters: {'max_depth': 7, 'learning_rate': 0.11073758943770835, 'n_estimators': 1352, 'subsample': 0.6180691411411823, 'colsample_bytree': 0.7541210724172849, 'min_child_weight': 7, 'gamma': 1.3190642024873602, 'reg_alpha': 0.0844863057296858, 'reg_lambda': 0.00010187319524775855, 'max_delta_step': 0}. Best is trial 41 with value: 0.5078947368421052.

Best trial: 41. Best value: 0.507895:  94%|█████████▍| 47/50 [08:21<00:52, 17.42s/it]

[I 2025-12-01 22:31:11,718] Trial 46 finished with value: 0.44276315789473686 and parameters: {'max_depth': 5, 'learning_rate': 0.14402830613172457, 'n_estimators': 1064, 'subsample': 0.5941795056675787, 'colsample_bytree': 0.9558742014339618, 'min_child_weight': 5, 'gamma': 3.5158298456698525, 'reg_alpha': 0.1875636696710527, 'reg_lambda': 3.8045556271890963, 'max_delta_step': 5}. Best is trial 41 with value: 0.5078947368421052.

Best trial: 41. Best value: 0.507895:  96%|█████████▌| 48/50 [08:27<00:28, 14.03s/it]

[I 2025-12-01 22:31:17,832] Trial 49 pruned.

Best trial: 41. Best value: 0.507895:  98%|█████████▊| 49/50 [08:34<00:11, 11.68s/it]

[I 2025-12-01 22:31:24,026] Trial 47 finished with value: 0.43157894736842106 and parameters: {'max_depth': 7, 'learning_rate': 0.2517047883179431, 'n_estimators': 1357, 'subsample': 0.5945781657915126, 'colsample_bytree': 0.7741921652236062, 'min_child_weight': 5, 'gamma': 0.7292556896101777, 'reg_alpha': 0.08987769029675542, 'reg_lambda': 4.338632524992805, 'max_delta_step': 5}. Best is trial 41 with value: 0.5078947368421052.

Best trial: 41. Best value: 0.507895: 100%|██████████| 50/50 [08:40<00:00, 10.41s/it]

[I 2025-12-01 22:31:30,291] Trial 48 pruned.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 22:31:36,847] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.446727:   2%|▏         | 1/50 [00:58<48:06, 58.90s/it]

[I 2025-12-01 22:32:35,739] Trial 1 finished with value: 0.40821566110397944 and parameters: {'max_depth': 3, 'learning_rate': 0.0820094178312749, 'n_estimators': 1240, 'subsample': 0.677286361186413, 'colsample_bytree': 0.5793499811423571, 'min_child_weight': 3, 'gamma': 0.3959168619661052, 'reg_alpha': 1.533823668472704e-08, 'reg_lambda': 2.5604242006117384e-08, 'max_delta_step': 4}. Best is trial 1 with value: 0.40821566110397944.
[I 2025-12-01 22:32:35,771] Trial 0 finished with value: 0.4467265725288832 and parameters: {'max_depth': 9, 'learning_rate': 0.03945918111428521, 'n_estimators': 1076, 'subsample': 0.7848462960684549, 'colsample_bytree': 0.5645238514314996, 'min_child_weight': 3, 'gamma': 3.644518552816402, 'reg_alpha': 0.00021710548017261992, 'reg_lambda': 8.30273918314133e-06, 'max_delta_step': 9}. Best is trial 0 with value: 0.4467265725288832.

Best trial: 4. Best value: 0.483312:   6%|▌         | 3/50 [01:23<19:01, 24.29s/it]

[I 2025-12-01 22:33:00,089] Trial 4 finished with value: 0.4833119383825417 and parameters: {'max_depth': 10, 'learning_rate': 0.13698477861248587, 'n_estimators': 541, 'subsample': 0.6561810972452977, 'colsample_bytree': 0.5451830809439778, 'min_child_weight': 4, 'gamma': 0.9968990670796141, 'reg_alpha': 7.973335976816983e-07, 'reg_lambda': 1.0055061903853016e-07, 'max_delta_step': 10}. Best is trial 4 with value: 0.4833119383825417.

Best trial: 4. Best value: 0.483312:   8%|▊         | 4/50 [01:24<12:38, 16.48s/it]

[I 2025-12-01 22:33:01,816] Trial 3 finished with value: 0.4326059050064185 and parameters: {'max_depth': 6, 'learning_rate': 0.10825331787340982, 'n_estimators': 1445, 'subsample': 0.872543805205346, 'colsample_bytree': 0.6843969527698097, 'min_child_weight': 2, 'gamma': 1.621590076682653, 'reg_alpha': 1.987165933071436e-06, 'reg_lambda': 4.222174851608531, 'max_delta_step': 10}. Best is trial 4 with value: 0.4833119383825417.

Best trial: 4. Best value: 0.483312:  10%|█         | 5/50 [01:25<08:30, 11.35s/it]

[I 2025-12-01 22:33:02,787] Trial 2 finished with value: 0.3960205391527599 and parameters: {'max_depth': 6, 'learning_rate': 0.010388056600698846, 'n_estimators': 1389, 'subsample': 0.7687975640724922, 'colsample_bytree': 0.6002294694171089, 'min_child_weight': 3, 'gamma': 3.795206930537638, 'reg_alpha': 0.22008477041969565, 'reg_lambda': 0.0010788836130696466, 'max_delta_step': 9}. Best is trial 4 with value: 0.4833119383825417.

Best trial: 4. Best value: 0.483312:  12%|█▏        | 6/50 [01:47<10:47, 14.72s/it]

[I 2025-12-01 22:33:24,644] Trial 5 finished with value: 0.4711168164313222 and parameters: {'max_depth': 8, 'learning_rate': 0.0904117503548701, 'n_estimators': 951, 'subsample': 0.5902945025764091, 'colsample_bytree': 0.8418057826606757, 'min_child_weight': 2, 'gamma': 1.5118627480194713, 'reg_alpha': 1.3710428201594489e-05, 'reg_lambda': 0.513631621399847, 'max_delta_step': 7}. Best is trial 4 with value: 0.4833119383825417.

Best trial: 4. Best value: 0.483312:  14%|█▍        | 7/50 [01:59<09:52, 13.79s/it]

[I 2025-12-01 22:33:36,403] Trial 9 finished with value: 0.4159178433889602 and parameters: {'max_depth': 10, 'learning_rate': 0.16725512698293413, 'n_estimators': 202, 'subsample': 0.5488939074418497, 'colsample_bytree': 0.7403820323285744, 'min_child_weight': 7, 'gamma': 4.347045630159617, 'reg_alpha': 1.2978785540929874e-07, 'reg_lambda': 0.017240637286153025, 'max_delta_step': 1}. Best is trial 4 with value: 0.4833119383825417.

Best trial: 4. Best value: 0.483312:  16%|█▌        | 8/50 [02:19<11:04, 15.82s/it]

[I 2025-12-01 22:33:56,736] Trial 8 finished with value: 0.3613607188703466 and parameters: {'max_depth': 4, 'learning_rate': 0.0854715293534376, 'n_estimators': 1232, 'subsample': 0.7050723224077626, 'colsample_bytree': 0.7964038536672555, 'min_child_weight': 7, 'gamma': 1.8140283212892432, 'reg_alpha': 1.1496716996949688e-07, 'reg_lambda': 2.4809477646572247, 'max_delta_step': 8}. Best is trial 4 with value: 0.4833119383825417.

Best trial: 4. Best value: 0.483312:  18%|█▊        | 9/50 [02:21<07:45, 11.36s/it]

[I 2025-12-01 22:33:58,028] Trial 6 finished with value: 0.42426187419768935 and parameters: {'max_depth': 8, 'learning_rate': 0.015598510589936604, 'n_estimators': 1103, 'subsample': 0.9138407568043565, 'colsample_bytree': 0.7018503441369746, 'min_child_weight': 7, 'gamma': 4.65895034829283, 'reg_alpha': 0.7419309890399544, 'reg_lambda': 2.392413879928817e-07, 'max_delta_step': 5}. Best is trial 4 with value: 0.4833119383825417.

Best trial: 4. Best value: 0.483312:  20%|██        | 10/50 [02:41<09:28, 14.21s/it]

[I 2025-12-01 22:34:18,725] Trial 12 finished with value: 0.45699614890885754 and parameters: {'max_depth': 8, 'learning_rate': 0.1477979488788748, 'n_estimators': 390, 'subsample': 0.8707588410323384, 'colsample_bytree': 0.6656391887660875, 'min_child_weight': 6, 'gamma': 3.6427334179142474, 'reg_alpha': 1.8319278335104688e-05, 'reg_lambda': 3.991230701061918e-08, 'max_delta_step': 4}. Best is trial 4 with value: 0.4833119383825417.

Best trial: 4. Best value: 0.483312:  22%|██▏       | 11/50 [02:42<06:30, 10.00s/it]

[I 2025-12-01 22:34:19,066] Trial 7 finished with value: 0.3960205391527599 and parameters: {'max_depth': 3, 'learning_rate': 0.024930146760581466, 'n_estimators': 1485, 'subsample': 0.7832712614686572, 'colsample_bytree': 0.8525090362634098, 'min_child_weight': 6, 'gamma': 0.4529410439224363, 'reg_alpha': 3.1925571089027267e-07, 'reg_lambda': 0.6555848313565978, 'max_delta_step': 9}. Best is trial 4 with value: 0.4833119383825417.

Best trial: 10. Best value: 0.509628:  24%|██▍       | 12/50 [02:43<04:34,  7.22s/it]

[I 2025-12-01 22:34:19,857] Trial 10 finished with value: 0.5096277278562259 and parameters: {'max_depth': 8, 'learning_rate': 0.03412480207815179, 'n_estimators': 670, 'subsample': 0.8505144465118888, 'colsample_bytree': 0.9221431802880073, 'min_child_weight': 4, 'gamma': 1.5204272332871764, 'reg_alpha': 1.9308627522605155e-08, 'reg_lambda': 0.005121978958348972, 'max_delta_step': 7}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628:  26%|██▌       | 13/50 [02:48<04:11,  6.79s/it]

[I 2025-12-01 22:34:25,633] Trial 14 pruned.

Best trial: 10. Best value: 0.509628:  28%|██▊       | 14/50 [02:49<02:53,  4.83s/it]

[I 2025-12-01 22:34:25,925] Trial 15 pruned.

Best trial: 10. Best value: 0.509628:  30%|███       | 15/50 [02:52<02:34,  4.40s/it]

[I 2025-12-01 22:34:29,352] Trial 11 pruned.

Best trial: 10. Best value: 0.509628:  32%|███▏      | 16/50 [02:53<01:56,  3.42s/it]

[I 2025-12-01 22:34:30,486] Trial 13 pruned.

Best trial: 10. Best value: 0.509628:  34%|███▍      | 17/50 [02:59<02:16,  4.12s/it]

[I 2025-12-01 22:34:36,249] Trial 19 pruned.

Best trial: 10. Best value: 0.509628:  36%|███▌      | 18/50 [03:24<05:33, 10.42s/it]

[I 2025-12-01 22:35:01,344] Trial 18 finished with value: 0.4833119383825417 and parameters: {'max_depth': 7, 'learning_rate': 0.04806975852144117, 'n_estimators': 548, 'subsample': 0.6675589022357524, 'colsample_bytree': 0.5254655073262354, 'min_child_weight': 4, 'gamma': 2.525504137429583, 'reg_alpha': 1.2668472425936506e-08, 'reg_lambda': 0.028417624592445605, 'max_delta_step': 1}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628:  38%|███▊      | 19/50 [03:25<03:58,  7.68s/it]

[I 2025-12-01 22:35:02,640] Trial 17 finished with value: 0.4326059050064185 and parameters: {'max_depth': 7, 'learning_rate': 0.0433415908652635, 'n_estimators': 561, 'subsample': 0.645205699276115, 'colsample_bytree': 0.9012442876324416, 'min_child_weight': 4, 'gamma': 2.4329932905822074, 'reg_alpha': 2.119576620956692e-08, 'reg_lambda': 0.020613618974754878, 'max_delta_step': 0}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628:  40%|████      | 20/50 [03:29<03:11,  6.39s/it]

[I 2025-12-01 22:35:06,035] Trial 20 finished with value: 0.4326059050064185 and parameters: {'max_depth': 9, 'learning_rate': 0.028304624286900972, 'n_estimators': 485, 'subsample': 0.7214927477267895, 'colsample_bytree': 0.5026447128827138, 'min_child_weight': 5, 'gamma': 2.244318678593647, 'reg_alpha': 1.0980731493078094e-08, 'reg_lambda': 6.293181852848715e-07, 'max_delta_step': 2}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628:  42%|████▏     | 21/50 [03:30<02:23,  4.95s/it]

[I 2025-12-01 22:35:07,605] Trial 16 finished with value: 0.45892169448010267 and parameters: {'max_depth': 7, 'learning_rate': 0.04370269865003954, 'n_estimators': 717, 'subsample': 0.9843356707405461, 'colsample_bytree': 0.5029562509244573, 'min_child_weight': 4, 'gamma': 2.614095945926584, 'reg_alpha': 1.1040352555655608e-08, 'reg_lambda': 0.003177938695348167, 'max_delta_step': 6}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628:  44%|████▍     | 22/50 [03:35<02:17,  4.92s/it]

[I 2025-12-01 22:35:12,452] Trial 22 pruned.

Best trial: 10. Best value: 0.509628:  46%|████▌     | 23/50 [03:38<01:52,  4.16s/it]

[I 2025-12-01 22:35:14,833] Trial 21 pruned.

Best trial: 10. Best value: 0.509628:  48%|████▊     | 24/50 [03:40<01:35,  3.69s/it]

[I 2025-12-01 22:35:17,443] Trial 23 pruned.

Best trial: 10. Best value: 0.509628:  50%|█████     | 25/50 [03:44<01:30,  3.60s/it]

[I 2025-12-01 22:35:20,843] Trial 27 pruned.

Best trial: 10. Best value: 0.509628:  52%|█████▏    | 26/50 [03:54<02:18,  5.78s/it]

[I 2025-12-01 22:35:31,692] Trial 25 finished with value: 0.444801026957638 and parameters: {'max_depth': 8, 'learning_rate': 0.06270560935661376, 'n_estimators': 324, 'subsample': 0.6322461454070958, 'colsample_bytree': 0.5550124085310709, 'min_child_weight': 5, 'gamma': 3.0894410275018966, 'reg_alpha': 1.05961522857453e-06, 'reg_lambda': 7.48489102839427e-05, 'max_delta_step': 3}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628:  54%|█████▍    | 27/50 [03:56<01:41,  4.41s/it]

[I 2025-12-01 22:35:32,905] Trial 26 finished with value: 0.4345314505776637 and parameters: {'max_depth': 5, 'learning_rate': 0.06027296211762854, 'n_estimators': 291, 'subsample': 0.6401280058789092, 'colsample_bytree': 0.5484419574933399, 'min_child_weight': 5, 'gamma': 3.040310649678133, 'reg_alpha': 1.52824263112337e-07, 'reg_lambda': 0.00012825206546779756, 'max_delta_step': 2}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628:  56%|█████▌    | 28/50 [04:14<03:09,  8.60s/it]

[I 2025-12-01 22:35:51,273] Trial 28 finished with value: 0.42041078305519897 and parameters: {'max_depth': 8, 'learning_rate': 0.017840181520408283, 'n_estimators': 537, 'subsample': 0.6363020661867725, 'colsample_bytree': 0.6275546121000485, 'min_child_weight': 5, 'gamma': 2.9800694503678176, 'reg_alpha': 3.867388962995831e-07, 'reg_lambda': 0.00042481938984854933, 'max_delta_step': 2}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628:  58%|█████▊    | 29/50 [04:16<02:21,  6.73s/it]

[I 2025-12-01 22:35:53,663] Trial 24 finished with value: 0.4326059050064185 and parameters: {'max_depth': 9, 'learning_rate': 0.059551525813980405, 'n_estimators': 857, 'subsample': 0.5015519414849822, 'colsample_bytree': 0.5287690227332464, 'min_child_weight': 1, 'gamma': 1.0119824620580702, 'reg_alpha': 1.0638612658465176e-06, 'reg_lambda': 0.00014329702910542076, 'max_delta_step': 3}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628:  60%|██████    | 30/50 [04:24<02:21,  7.09s/it]

[I 2025-12-01 22:36:01,568] Trial 32 pruned.

Best trial: 10. Best value: 0.509628:  62%|██████▏   | 31/50 [04:27<01:48,  5.71s/it]

[I 2025-12-01 22:36:04,057] Trial 29 finished with value: 0.4993581514762516 and parameters: {'max_depth': 6, 'learning_rate': 0.03353800078840554, 'n_estimators': 518, 'subsample': 0.8295957560742825, 'colsample_bytree': 0.6371761178021154, 'min_child_weight': 4, 'gamma': 2.8570193736049307, 'reg_alpha': 5.490082204226787e-08, 'reg_lambda': 0.1367793854897151, 'max_delta_step': 8}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628:  64%|██████▍   | 32/50 [04:34<01:51,  6.22s/it]

[I 2025-12-01 22:36:11,483] Trial 30 finished with value: 0.4833119383825417 and parameters: {'max_depth': 6, 'learning_rate': 0.02064109087253046, 'n_estimators': 510, 'subsample': 0.8290129154206196, 'colsample_bytree': 0.620066125174454, 'min_child_weight': 4, 'gamma': 1.3162502860168426, 'reg_alpha': 4.98432576284909e-08, 'reg_lambda': 0.006417311785611649, 'max_delta_step': 8}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628:  66%|██████▌   | 33/50 [04:39<01:38,  5.77s/it]

[I 2025-12-01 22:36:16,199] Trial 35 pruned.

Best trial: 10. Best value: 0.509628:  68%|██████▊   | 34/50 [04:46<01:38,  6.14s/it]

[I 2025-12-01 22:36:23,197] Trial 36 pruned.

Best trial: 10. Best value: 0.509628:  70%|███████   | 35/50 [04:54<01:39,  6.64s/it]

[I 2025-12-01 22:36:31,021] Trial 31 finished with value: 0.4974326059050064 and parameters: {'max_depth': 6, 'learning_rate': 0.035070897109947055, 'n_estimators': 639, 'subsample': 0.8237529873368357, 'colsample_bytree': 0.6104399153651708, 'min_child_weight': 4, 'gamma': 1.3098441079180125, 'reg_alpha': 4.777649607429929e-08, 'reg_lambda': 0.005749076567508024, 'max_delta_step': 8}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628:  72%|███████▏  | 36/50 [04:55<01:10,  5.02s/it]

[I 2025-12-01 22:36:32,233] Trial 34 finished with value: 0.47304236200256744 and parameters: {'max_depth': 7, 'learning_rate': 0.034394846306847, 'n_estimators': 434, 'subsample': 0.8363883743515825, 'colsample_bytree': 0.6333900505078874, 'min_child_weight': 4, 'gamma': 3.532973156611468, 'reg_alpha': 4.7223460086046556e-08, 'reg_lambda': 0.01058609716570195, 'max_delta_step': 8}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628:  74%|███████▍  | 37/50 [05:02<01:13,  5.66s/it]

[I 2025-12-01 22:36:39,412] Trial 37 pruned.

Best trial: 10. Best value: 0.509628:  76%|███████▌  | 38/50 [05:05<00:57,  4.82s/it]

[I 2025-12-01 22:36:42,267] Trial 39 pruned.

Best trial: 10. Best value: 0.509628:  78%|███████▊  | 39/50 [05:10<00:52,  4.78s/it]

[I 2025-12-01 22:36:46,959] Trial 33 finished with value: 0.4486521181001284 and parameters: {'max_depth': 7, 'learning_rate': 0.20468737092680345, 'n_estimators': 939, 'subsample': 0.7364229440328616, 'colsample_bytree': 0.9966185108176705, 'min_child_weight': 4, 'gamma': 1.2924084780997582, 'reg_alpha': 5.867132836187043e-06, 'reg_lambda': 0.005532591505076427, 'max_delta_step': 8}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628:  80%|████████  | 40/50 [05:11<00:37,  3.77s/it]

[I 2025-12-01 22:36:48,361] Trial 40 pruned.

Best trial: 10. Best value: 0.509628:  82%|████████▏ | 41/50 [05:17<00:40,  4.48s/it]

[I 2025-12-01 22:36:54,498] Trial 41 pruned.

Best trial: 10. Best value: 0.509628:  84%|████████▍ | 42/50 [05:22<00:35,  4.45s/it]

[I 2025-12-01 22:36:58,881] Trial 43 pruned.

Best trial: 10. Best value: 0.509628:  86%|████████▌ | 43/50 [05:28<00:34,  4.93s/it]

[I 2025-12-01 22:37:04,936] Trial 45 pruned.

Best trial: 10. Best value: 0.509628:  88%|████████▊ | 44/50 [05:46<00:54,  9.06s/it]

[I 2025-12-01 22:37:23,633] Trial 44 finished with value: 0.42041078305519897 and parameters: {'max_depth': 6, 'learning_rate': 0.05014044690528323, 'n_estimators': 678, 'subsample': 0.7679478821058685, 'colsample_bytree': 0.5707425294467394, 'min_child_weight': 6, 'gamma': 4.102436931572315, 'reg_alpha': 6.54333303628327e-08, 'reg_lambda': 0.04857262729476208, 'max_delta_step': 7}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628:  90%|█████████ | 45/50 [05:53<00:41,  8.38s/it]

[I 2025-12-01 22:37:30,436] Trial 46 finished with value: 0.45892169448010267 and parameters: {'max_depth': 6, 'learning_rate': 0.04930543240130885, 'n_estimators': 513, 'subsample': 0.8575978637472251, 'colsample_bytree': 0.5288482913687872, 'min_child_weight': 6, 'gamma': 0.735028903627096, 'reg_alpha': 2.3848007902963712e-08, 'reg_lambda': 0.0015989587395460138, 'max_delta_step': 8}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628:  92%|█████████▏| 46/50 [06:07<00:39,  9.96s/it]

[I 2025-12-01 22:37:44,082] Trial 48 pruned.

Best trial: 10. Best value: 0.509628:  94%|█████████▍| 47/50 [06:11<00:24,  8.16s/it]

[I 2025-12-01 22:37:48,035] Trial 38 finished with value: 0.444801026957638 and parameters: {'max_depth': 5, 'learning_rate': 0.011978897697549019, 'n_estimators': 955, 'subsample': 0.8834556047220038, 'colsample_bytree': 0.6655194175758742, 'min_child_weight': 3, 'gamma': 0.679290936459235, 'reg_alpha': 0.00010566098380622888, 'reg_lambda': 0.0011013854464155606, 'max_delta_step': 9}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628:  96%|█████████▌| 48/50 [06:12<00:12,  6.02s/it]

[I 2025-12-01 22:37:49,071] Trial 47 finished with value: 0.46919127086007706 and parameters: {'max_depth': 8, 'learning_rate': 0.08045789697500179, 'n_estimators': 505, 'subsample': 0.6659371703987166, 'colsample_bytree': 0.5315477684747898, 'min_child_weight': 3, 'gamma': 1.5827887106904819, 'reg_alpha': 2.2265396251244367e-08, 'reg_lambda': 0.3939513497195543, 'max_delta_step': 10}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628:  98%|█████████▊| 49/50 [06:23<00:07,  7.45s/it]

[I 2025-12-01 22:37:59,870] Trial 49 finished with value: 0.4993581514762516 and parameters: {'max_depth': 8, 'learning_rate': 0.07659232135103869, 'n_estimators': 391, 'subsample': 0.9353919167714142, 'colsample_bytree': 0.6460319604824736, 'min_child_weight': 5, 'gamma': 2.750833693067394, 'reg_alpha': 0.08330131195500272, 'reg_lambda': 2.3423798080246993e-06, 'max_delta_step': 10}. Best is trial 10 with value: 0.5096277278562259.

Best trial: 10. Best value: 0.509628: 100%|██████████| 50/50 [06:27<00:00,  7.74s/it]

[I 2025-12-01 22:38:04,040] Trial 42 finished with value: 0.4711168164313222 and parameters: {'max_depth': 4, 'learning_rate': 0.02123170537773443, 'n_estimators': 1042, 'subsample': 0.7989812893769364, 'colsample_bytree': 0.722047598709136, 'min_child_weight': 2, 'gamma': 0.27977357883834664, 'reg_alpha': 4.295883110244729e-07, 'reg_lambda': 1.5877485697405582, 'max_delta_step': 6}. Best is trial 10 with value: 0.5096277278562259.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 22:38:09,523] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.56611:   2%|▏         | 1/50 [00:22<18:11, 22.28s/it]

[I 2025-12-01 22:38:31,794] Trial 1 finished with value: 0.5661103979460848 and parameters: {'max_depth': 10, 'learning_rate': 0.2385412089215862, 'n_estimators': 514, 'subsample': 0.6992784917590059, 'colsample_bytree': 0.9581885783314597, 'min_child_weight': 6, 'gamma': 2.849460157407539, 'reg_alpha': 4.42837202359042e-05, 'reg_lambda': 0.00033900580493157395, 'max_delta_step': 7}. Best is trial 1 with value: 0.5661103979460848.

Best trial: 1. Best value: 0.56611:   4%|▍         | 2/50 [00:36<14:05, 17.61s/it]

[I 2025-12-01 22:38:46,134] Trial 3 finished with value: 0.3684210526315789 and parameters: {'max_depth': 10, 'learning_rate': 0.2905900900686966, 'n_estimators': 887, 'subsample': 0.6703164501442436, 'colsample_bytree': 0.9337428081251049, 'min_child_weight': 9, 'gamma': 4.925567689467903, 'reg_alpha': 3.5739931119294948, 'reg_lambda': 1.3991832900634107e-07, 'max_delta_step': 2}. Best is trial 1 with value: 0.5661103979460848.

Best trial: 1. Best value: 0.56611:   6%|▌         | 3/50 [00:49<12:00, 15.33s/it]

[I 2025-12-01 22:38:58,750] Trial 0 finished with value: 0.4749679075738126 and parameters: {'max_depth': 3, 'learning_rate': 0.01518637634869182, 'n_estimators': 1079, 'subsample': 0.953219731160879, 'colsample_bytree': 0.750759027851762, 'min_child_weight': 8, 'gamma': 1.5484951743944675, 'reg_alpha': 1.1753399642057514e-05, 'reg_lambda': 0.015408538676110722, 'max_delta_step': 5}. Best is trial 1 with value: 0.5661103979460848.

Best trial: 1. Best value: 0.56611:   8%|▊         | 4/50 [00:53<08:29, 11.09s/it]

[I 2025-12-01 22:39:03,332] Trial 4 finished with value: 0.4871630295250321 and parameters: {'max_depth': 6, 'learning_rate': 0.12867140251392684, 'n_estimators': 653, 'subsample': 0.5992864827474103, 'colsample_bytree': 0.9768066312180427, 'min_child_weight': 3, 'gamma': 0.19329124193722846, 'reg_alpha': 0.003341158495891227, 'reg_lambda': 2.3481437961438878e-07, 'max_delta_step': 2}. Best is trial 1 with value: 0.5661103979460848.

Best trial: 1. Best value: 0.56611:  12%|█▏        | 6/50 [00:56<03:55,  5.36s/it]

[I 2025-12-01 22:39:05,980] Trial 2 finished with value: 0.511553273427471 and parameters: {'max_depth': 10, 'learning_rate': 0.03695086384058845, 'n_estimators': 978, 'subsample': 0.6618141938264028, 'colsample_bytree': 0.9385366541369755, 'min_child_weight': 2, 'gamma': 2.0559324110987527, 'reg_alpha': 0.43300434159843926, 'reg_lambda': 0.0003789043144229562, 'max_delta_step': 6}. Best is trial 1 with value: 0.5661103979460848.
[I 2025-12-01 22:39:06,140] Trial 5 finished with value: 0.5641848523748395 and parameters: {'max_depth': 4, 'learning_rate': 0.04728032947930671, 'n_estimators': 357, 'subsample': 0.6321092969838092, 'colsample_bytree': 0.5840691920348207, 'min_child_weight': 4, 'gamma': 3.282014735473166, 'reg_alpha': 0.019759720062012955, 'reg_lambda': 3.3390387227604914e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.5661103979460848.

Best trial: 7. Best value: 0.578306:  14%|█▍        | 7/50 [01:32<11:02, 15.40s/it]

[I 2025-12-01 22:39:42,212] Trial 7 finished with value: 0.5783055198973043 and parameters: {'max_depth': 8, 'learning_rate': 0.12217343376108261, 'n_estimators': 983, 'subsample': 0.5627850496663775, 'colsample_bytree': 0.7765630220195485, 'min_child_weight': 5, 'gamma': 0.1921017046618989, 'reg_alpha': 1.5550412520738928e-05, 'reg_lambda': 8.484739654158312e-05, 'max_delta_step': 9}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  16%|█▌        | 8/50 [01:33<07:28, 10.68s/it]

[I 2025-12-01 22:39:42,788] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.050081937793954104, 'n_estimators': 928, 'subsample': 0.7012223143752456, 'colsample_bytree': 0.9903034006074571, 'min_child_weight': 10, 'gamma': 3.927465327125606, 'reg_alpha': 0.08667214956406483, 'reg_lambda': 0.010023467561065568, 'max_delta_step': 3}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  18%|█▊        | 9/50 [01:39<06:22,  9.32s/it]

[I 2025-12-01 22:39:49,121] Trial 8 finished with value: 0.48523748395378685 and parameters: {'max_depth': 10, 'learning_rate': 0.07688462792090216, 'n_estimators': 947, 'subsample': 0.5927235393433916, 'colsample_bytree': 0.6220892572930996, 'min_child_weight': 1, 'gamma': 0.8795637103841497, 'reg_alpha': 3.1658689140401444e-06, 'reg_lambda': 6.565446678811072e-07, 'max_delta_step': 7}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  20%|██        | 10/50 [01:56<07:40, 11.52s/it]

[I 2025-12-01 22:40:05,552] Trial 10 finished with value: 0.18421052631578946 and parameters: {'max_depth': 4, 'learning_rate': 0.07036303198778152, 'n_estimators': 544, 'subsample': 0.5114645418396264, 'colsample_bytree': 0.8892727523980901, 'min_child_weight': 8, 'gamma': 1.633268309174527, 'reg_alpha': 0.00020101437692346662, 'reg_lambda': 0.29109836255910043, 'max_delta_step': 0}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  22%|██▏       | 11/50 [01:56<05:15,  8.10s/it]

[I 2025-12-01 22:40:05,881] Trial 11 pruned.

Best trial: 7. Best value: 0.578306:  24%|██▍       | 12/50 [01:59<04:08,  6.55s/it]

[I 2025-12-01 22:40:08,917] Trial 12 finished with value: 0.5012836970474968 and parameters: {'max_depth': 3, 'learning_rate': 0.10434685872746534, 'n_estimators': 405, 'subsample': 0.8157029435270619, 'colsample_bytree': 0.8593455807228081, 'min_child_weight': 6, 'gamma': 4.641090899401099, 'reg_alpha': 1.8050115008474987e-06, 'reg_lambda': 2.5967259003732315e-07, 'max_delta_step': 4}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  26%|██▌       | 13/50 [02:06<04:11,  6.79s/it]

[I 2025-12-01 22:40:16,256] Trial 6 finished with value: 0.5378690629011553 and parameters: {'max_depth': 6, 'learning_rate': 0.022631718095917127, 'n_estimators': 1050, 'subsample': 0.7364989552885369, 'colsample_bytree': 0.874333298948022, 'min_child_weight': 1, 'gamma': 4.271334990647998, 'reg_alpha': 0.02940619461597442, 'reg_lambda': 4.827892496629846e-08, 'max_delta_step': 0}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  28%|██▊       | 14/50 [02:07<02:54,  4.85s/it]

[I 2025-12-01 22:40:16,620] Trial 14 pruned.

Best trial: 7. Best value: 0.578306:  30%|███       | 15/50 [02:09<02:22,  4.06s/it]

[I 2025-12-01 22:40:18,847] Trial 15 pruned.

Best trial: 7. Best value: 0.578306:  32%|███▏      | 16/50 [02:11<01:57,  3.46s/it]

[I 2025-12-01 22:40:20,899] Trial 13 pruned.

Best trial: 7. Best value: 0.578306:  34%|███▍      | 17/50 [02:15<01:56,  3.54s/it]

[I 2025-12-01 22:40:24,623] Trial 18 pruned.

Best trial: 7. Best value: 0.578306:  36%|███▌      | 18/50 [02:17<01:45,  3.30s/it]

[I 2025-12-01 22:40:27,378] Trial 19 pruned.

Best trial: 7. Best value: 0.578306:  38%|███▊      | 19/50 [02:20<01:38,  3.17s/it]

[I 2025-12-01 22:40:30,261] Trial 17 pruned.

Best trial: 7. Best value: 0.578306:  40%|████      | 20/50 [02:26<02:01,  4.05s/it]

[I 2025-12-01 22:40:36,351] Trial 20 pruned.

Best trial: 7. Best value: 0.578306:  42%|████▏     | 21/50 [03:10<07:39, 15.83s/it]

[I 2025-12-01 22:41:19,655] Trial 16 finished with value: 0.5500641848523748 and parameters: {'max_depth': 8, 'learning_rate': 0.24688743199979055, 'n_estimators': 1362, 'subsample': 0.817185307192131, 'colsample_bytree': 0.7477664054913865, 'min_child_weight': 5, 'gamma': 2.8862636553236234, 'reg_alpha': 4.617380673879492e-05, 'reg_lambda': 3.4945849973430796e-05, 'max_delta_step': 10}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  44%|████▍     | 22/50 [03:11<05:19, 11.43s/it]

[I 2025-12-01 22:41:20,804] Trial 21 finished with value: 0.5378690629011553 and parameters: {'max_depth': 9, 'learning_rate': 0.1911640408957553, 'n_estimators': 1200, 'subsample': 0.5700439985597866, 'colsample_bytree': 0.5010437942605706, 'min_child_weight': 3, 'gamma': 3.25098483773659, 'reg_alpha': 0.0014612796021777877, 'reg_lambda': 7.115551428352047e-05, 'max_delta_step': 8}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  46%|████▌     | 23/50 [03:15<04:09,  9.23s/it]

[I 2025-12-01 22:41:24,898] Trial 22 finished with value: 0.5641848523748395 and parameters: {'max_depth': 9, 'learning_rate': 0.20167164721921663, 'n_estimators': 1141, 'subsample': 0.8913548281511328, 'colsample_bytree': 0.5019152989561713, 'min_child_weight': 3, 'gamma': 3.345353130841894, 'reg_alpha': 0.0016042580885386334, 'reg_lambda': 3.322176590248798e-06, 'max_delta_step': 8}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  48%|████▊     | 24/50 [03:25<04:07,  9.52s/it]

[I 2025-12-01 22:41:35,094] Trial 24 finished with value: 0.511553273427471 and parameters: {'max_depth': 5, 'learning_rate': 0.036017431896261304, 'n_estimators': 211, 'subsample': 0.6453007458259508, 'colsample_bytree': 0.5000682160727141, 'min_child_weight': 3, 'gamma': 3.4005818351241777, 'reg_alpha': 0.0021222052289396522, 'reg_lambda': 6.433544408070058e-06, 'max_delta_step': 6}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  50%|█████     | 25/50 [03:25<02:49,  6.77s/it]

[I 2025-12-01 22:41:35,458] Trial 23 finished with value: 0.511553273427471 and parameters: {'max_depth': 9, 'learning_rate': 0.10464652652034921, 'n_estimators': 1198, 'subsample': 0.8713922012703296, 'colsample_bytree': 0.8357490675183786, 'min_child_weight': 3, 'gamma': 2.1060026486748242, 'reg_alpha': 0.0017239444228188414, 'reg_lambda': 7.919513059207288e-06, 'max_delta_step': 6}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  52%|█████▏    | 26/50 [03:28<02:14,  5.62s/it]

[I 2025-12-01 22:41:38,386] Trial 25 finished with value: 0.5641848523748395 and parameters: {'max_depth': 5, 'learning_rate': 0.04087368886516704, 'n_estimators': 283, 'subsample': 0.6278952172555289, 'colsample_bytree': 0.5754453238928084, 'min_child_weight': 4, 'gamma': 3.5047805601733, 'reg_alpha': 0.002430840985278018, 'reg_lambda': 3.219100282540655e-06, 'max_delta_step': 6}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  54%|█████▍    | 27/50 [03:31<01:47,  4.68s/it]

[I 2025-12-01 22:41:40,859] Trial 28 pruned.

Best trial: 7. Best value: 0.578306:  56%|█████▌    | 28/50 [03:32<01:22,  3.76s/it]

[I 2025-12-01 22:41:42,484] Trial 26 finished with value: 0.5378690629011553 and parameters: {'max_depth': 5, 'learning_rate': 0.040416931121851525, 'n_estimators': 249, 'subsample': 0.6195715996370079, 'colsample_bytree': 0.5916293210580328, 'min_child_weight': 4, 'gamma': 2.307319011496216, 'reg_alpha': 0.01614352674275097, 'reg_lambda': 6.07454065654696e-06, 'max_delta_step': 6}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  58%|█████▊    | 29/50 [03:34<01:05,  3.10s/it]

[I 2025-12-01 22:41:44,038] Trial 27 pruned.

Best trial: 7. Best value: 0.578306:  60%|██████    | 30/50 [03:37<01:02,  3.15s/it]

[I 2025-12-01 22:41:47,313] Trial 29 pruned.

Best trial: 7. Best value: 0.578306:  62%|██████▏   | 31/50 [03:40<00:58,  3.08s/it]

[I 2025-12-01 22:41:50,240] Trial 31 pruned.

Best trial: 7. Best value: 0.578306:  64%|██████▍   | 32/50 [03:45<01:03,  3.52s/it]

[I 2025-12-01 22:41:54,781] Trial 33 pruned.

Best trial: 7. Best value: 0.578306:  66%|██████▌   | 33/50 [04:10<02:50, 10.05s/it]

[I 2025-12-01 22:42:20,063] Trial 30 finished with value: 0.5237483953786906 and parameters: {'max_depth': 4, 'learning_rate': 0.10776070898405811, 'n_estimators': 811, 'subsample': 0.7048264174990438, 'colsample_bytree': 0.7138914504194513, 'min_child_weight': 4, 'gamma': 2.356076213441244, 'reg_alpha': 0.15111968862938646, 'reg_lambda': 0.0019026881700729967, 'max_delta_step': 9}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  68%|██████▊   | 34/50 [04:13<02:04,  7.77s/it]

[I 2025-12-01 22:42:22,503] Trial 32 finished with value: 0.5134788189987163 and parameters: {'max_depth': 3, 'learning_rate': 0.0280103566423547, 'n_estimators': 785, 'subsample': 0.7173640284863123, 'colsample_bytree': 0.7230364310596847, 'min_child_weight': 7, 'gamma': 1.3592622909013945, 'reg_alpha': 5.76940182234633e-06, 'reg_lambda': 0.002642508833780405, 'max_delta_step': 9}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  70%|███████   | 35/50 [04:17<01:42,  6.82s/it]

[I 2025-12-01 22:42:27,115] Trial 34 pruned.

Best trial: 7. Best value: 0.578306:  72%|███████▏  | 36/50 [04:39<02:37, 11.28s/it]

[I 2025-12-01 22:42:48,797] Trial 35 finished with value: 0.5256739409499358 and parameters: {'max_depth': 10, 'learning_rate': 0.23009256100998907, 'n_estimators': 1155, 'subsample': 0.9566488595350899, 'colsample_bytree': 0.5358758382146451, 'min_child_weight': 2, 'gamma': 3.219136734058769, 'reg_alpha': 0.25989075797885947, 'reg_lambda': 0.1099281822449321, 'max_delta_step': 7}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  74%|███████▍  | 37/50 [04:50<02:28, 11.40s/it]

[I 2025-12-01 22:43:00,472] Trial 37 pruned.

Best trial: 7. Best value: 0.578306:  76%|███████▌  | 38/50 [04:58<02:04, 10.39s/it]

[I 2025-12-01 22:43:08,510] Trial 40 pruned.

Best trial: 7. Best value: 0.578306:  78%|███████▊  | 39/50 [05:08<01:50, 10.00s/it]

[I 2025-12-01 22:43:17,605] Trial 38 finished with value: 0.5134788189987163 and parameters: {'max_depth': 10, 'learning_rate': 0.21497786627684912, 'n_estimators': 1030, 'subsample': 0.7754970917814096, 'colsample_bytree': 0.9266755513881256, 'min_child_weight': 2, 'gamma': 3.6579426012215808, 'reg_alpha': 1.4957388066756274, 'reg_lambda': 0.00023348867421932304, 'max_delta_step': 7}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  80%|████████  | 40/50 [05:14<01:30,  9.01s/it]

[I 2025-12-01 22:43:24,293] Trial 39 finished with value: 0.5783055198973043 and parameters: {'max_depth': 9, 'learning_rate': 0.011021003976578387, 'n_estimators': 568, 'subsample': 0.9944299140062276, 'colsample_bytree': 0.9133111921436089, 'min_child_weight': 6, 'gamma': 3.836947013687014, 'reg_alpha': 0.0003139051023093601, 'reg_lambda': 1.0806818716063387e-06, 'max_delta_step': 2}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  82%|████████▏ | 41/50 [05:17<01:03,  7.04s/it]

[I 2025-12-01 22:43:26,754] Trial 42 pruned.

Best trial: 7. Best value: 0.578306:  84%|████████▍ | 42/50 [05:17<00:40,  5.06s/it]

[I 2025-12-01 22:43:27,173] Trial 41 pruned.

Best trial: 7. Best value: 0.578306:  86%|████████▌ | 43/50 [05:18<00:26,  3.82s/it]

[I 2025-12-01 22:43:28,105] Trial 36 finished with value: 0.4993581514762516 and parameters: {'max_depth': 10, 'learning_rate': 0.010051362221767812, 'n_estimators': 1096, 'subsample': 0.9923820531626051, 'colsample_bytree': 0.5328930100721105, 'min_child_weight': 2, 'gamma': 3.2839158837960665, 'reg_alpha': 2.6617940076343736, 'reg_lambda': 0.0002484783861881163, 'max_delta_step': 7}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  88%|████████▊ | 44/50 [05:23<00:24,  4.13s/it]

[I 2025-12-01 22:43:32,972] Trial 46 pruned.

Best trial: 7. Best value: 0.578306:  90%|█████████ | 45/50 [05:24<00:16,  3.27s/it]

[I 2025-12-01 22:43:34,223] Trial 43 pruned.

Best trial: 7. Best value: 0.578306:  92%|█████████▏| 46/50 [05:32<00:18,  4.54s/it]

[I 2025-12-01 22:43:41,736] Trial 48 pruned.

Best trial: 7. Best value: 0.578306:  94%|█████████▍| 47/50 [05:46<00:22,  7.38s/it]

[I 2025-12-01 22:43:55,742] Trial 45 finished with value: 0.5256739409499358 and parameters: {'max_depth': 9, 'learning_rate': 0.014291839316864336, 'n_estimators': 459, 'subsample': 0.8978820952254686, 'colsample_bytree': 0.9694642892389045, 'min_child_weight': 6, 'gamma': 4.619418368377807, 'reg_alpha': 6.663364659966804e-05, 'reg_lambda': 1.1315472131252953e-07, 'max_delta_step': 1}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 7. Best value: 0.578306:  96%|█████████▌| 48/50 [05:50<00:12,  6.45s/it]

[I 2025-12-01 22:44:00,007] Trial 49 pruned.

Best trial: 7. Best value: 0.578306:  98%|█████████▊| 49/50 [05:59<00:07,  7.08s/it]

[I 2025-12-01 22:44:08,555] Trial 44 finished with value: 0.4993581514762516 and parameters: {'max_depth': 9, 'learning_rate': 0.012603251366213077, 'n_estimators': 528, 'subsample': 0.9946011023783015, 'colsample_bytree': 0.9975863645619841, 'min_child_weight': 3, 'gamma': 4.636449047082664, 'reg_alpha': 0.007763114906097036, 'reg_lambda': 8.688428401393391e-08, 'max_delta_step': 1}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 47. Best value: 0.614891: 100%|██████████| 50/50 [06:04<00:00,  7.30s/it]

[I 2025-12-01 22:44:14,361] Trial 47 finished with value: 0.6148908857509627 and parameters: {'max_depth': 9, 'learning_rate': 0.015504435645222319, 'n_estimators': 893, 'subsample': 0.9940658028932758, 'colsample_bytree': 0.8902910617983292, 'min_child_weight': 5, 'gamma': 4.082563493332248, 'reg_alpha': 2.0395135301306495e-05, 'reg_lambda': 4.342199333799465e-07, 'max_delta_step': 1}. Best is trial 47 with value: 0.6148908857509627.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 22:44:19,070] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.507895:   2%|▏         | 1/50 [00:21<17:31, 21.47s/it]

[I 2025-12-01 22:44:40,530] Trial 3 finished with value: 0.5078947368421052 and parameters: {'max_depth': 3, 'learning_rate': 0.09461010463212749, 'n_estimators': 454, 'subsample': 0.9359352941721282, 'colsample_bytree': 0.5053180702500377, 'min_child_weight': 3, 'gamma': 2.2192002652021587, 'reg_alpha': 4.169511718676695, 'reg_lambda': 0.0035626016194346116, 'max_delta_step': 6}. Best is trial 3 with value: 0.5078947368421052.

Best trial: 0. Best value: 0.571711:   4%|▍         | 2/50 [00:41<16:17, 20.36s/it]

[I 2025-12-01 22:45:00,112] Trial 0 finished with value: 0.5717105263157894 and parameters: {'max_depth': 4, 'learning_rate': 0.017207669516303297, 'n_estimators': 712, 'subsample': 0.5361834156420879, 'colsample_bytree': 0.8588421286261437, 'min_child_weight': 3, 'gamma': 0.9856008735801347, 'reg_alpha': 7.592251317040856e-06, 'reg_lambda': 0.00021786961687298692, 'max_delta_step': 4}. Best is trial 0 with value: 0.5717105263157894.

Best trial: 0. Best value: 0.571711:   6%|▌         | 3/50 [00:56<14:09, 18.07s/it]

[I 2025-12-01 22:45:15,461] Trial 2 finished with value: 0.5328947368421053 and parameters: {'max_depth': 4, 'learning_rate': 0.027564209462184415, 'n_estimators': 859, 'subsample': 0.7302652514731918, 'colsample_bytree': 0.697581881407056, 'min_child_weight': 1, 'gamma': 3.4182617092940104, 'reg_alpha': 0.7828718192094227, 'reg_lambda': 0.013359560248086193, 'max_delta_step': 5}. Best is trial 0 with value: 0.5717105263157894.

Best trial: 0. Best value: 0.571711:   8%|▊         | 4/50 [00:58<09:04, 11.83s/it]

[I 2025-12-01 22:45:17,725] Trial 1 finished with value: 0.5717105263157894 and parameters: {'max_depth': 10, 'learning_rate': 0.1431025136258929, 'n_estimators': 1458, 'subsample': 0.8724182093387813, 'colsample_bytree': 0.5945063554376044, 'min_child_weight': 2, 'gamma': 1.5127657631341629, 'reg_alpha': 2.2496984849956595e-06, 'reg_lambda': 2.496544266244479e-06, 'max_delta_step': 10}. Best is trial 0 with value: 0.5717105263157894.

Best trial: 0. Best value: 0.571711:  10%|█         | 5/50 [01:17<10:45, 14.35s/it]

[I 2025-12-01 22:45:36,547] Trial 4 finished with value: 0.4151315789473684 and parameters: {'max_depth': 10, 'learning_rate': 0.010264338227712035, 'n_estimators': 1435, 'subsample': 0.6783965056829773, 'colsample_bytree': 0.7477185228443939, 'min_child_weight': 8, 'gamma': 2.798247111428223, 'reg_alpha': 3.829855302735474e-07, 'reg_lambda': 0.07703494409821858, 'max_delta_step': 1}. Best is trial 0 with value: 0.5717105263157894.

Best trial: 0. Best value: 0.571711:  12%|█▏        | 6/50 [01:34<11:06, 15.15s/it]

[I 2025-12-01 22:45:53,247] Trial 6 finished with value: 0.5717105263157894 and parameters: {'max_depth': 8, 'learning_rate': 0.07077634039734022, 'n_estimators': 760, 'subsample': 0.8322198042438331, 'colsample_bytree': 0.9362305703490417, 'min_child_weight': 5, 'gamma': 3.647972580650973, 'reg_alpha': 1.5056765918754616e-06, 'reg_lambda': 1.113463594229635e-06, 'max_delta_step': 0}. Best is trial 0 with value: 0.5717105263157894.
[I 2025-12-01 22:45:53,257] Trial 8 finished with value: 0.5717105263157894 and parameters: {'max_depth': 4, 'learning_rate': 0.15472872187585263, 'n_estimators': 360, 'subsample': 0.6099073999528916, 'colsample_bytree': 0.6234806741039776, 'min_child_weight': 6, 'gamma': 2.779067480497826, 'reg_alpha': 0.00013501063447505737, 'reg_lambda': 1.5944053712084994e-07, 'max_delta_step': 7}. Best is trial 0 with value: 0.5717105263157894.

Best trial: 0. Best value: 0.571711:  16%|█▌        | 8/50 [01:40<06:29,  9.28s/it]

[I 2025-12-01 22:45:59,732] Trial 5 finished with value: 0.5203947368421052 and parameters: {'max_depth': 4, 'learning_rate': 0.03838773934719671, 'n_estimators': 1238, 'subsample': 0.975961503458705, 'colsample_bytree': 0.5846525711149515, 'min_child_weight': 4, 'gamma': 2.7087899279299217, 'reg_alpha': 2.2856498471172145e-07, 'reg_lambda': 0.0005195859591627951, 'max_delta_step': 2}. Best is trial 0 with value: 0.5717105263157894.

Best trial: 0. Best value: 0.571711:  18%|█▊        | 9/50 [02:01<08:19, 12.18s/it]

[I 2025-12-01 22:46:20,148] Trial 10 finished with value: 0.5190789473684211 and parameters: {'max_depth': 4, 'learning_rate': 0.10932136167650884, 'n_estimators': 344, 'subsample': 0.7749852137371478, 'colsample_bytree': 0.9682423444964174, 'min_child_weight': 1, 'gamma': 0.5409359446485273, 'reg_alpha': 1.851375464177652e-08, 'reg_lambda': 0.25321817572690714, 'max_delta_step': 6}. Best is trial 0 with value: 0.5717105263157894.

Best trial: 0. Best value: 0.571711:  20%|██        | 10/50 [02:01<06:02,  9.07s/it]

[I 2025-12-01 22:46:20,837] Trial 7 finished with value: 0.5717105263157894 and parameters: {'max_depth': 9, 'learning_rate': 0.07785178804580023, 'n_estimators': 1446, 'subsample': 0.9261355329131373, 'colsample_bytree': 0.7032063320250962, 'min_child_weight': 6, 'gamma': 4.7639008516778745, 'reg_alpha': 5.692368152057117e-05, 'reg_lambda': 3.7305430013014024e-06, 'max_delta_step': 2}. Best is trial 0 with value: 0.5717105263157894.

Best trial: 0. Best value: 0.571711:  22%|██▏       | 11/50 [02:08<05:23,  8.28s/it]

[I 2025-12-01 22:46:27,105] Trial 11 pruned.

Best trial: 0. Best value: 0.571711:  24%|██▍       | 12/50 [02:08<03:53,  6.15s/it]

[I 2025-12-01 22:46:27,896] Trial 13 pruned.

Best trial: 0. Best value: 0.571711:  26%|██▌       | 13/50 [02:17<04:14,  6.87s/it]

[I 2025-12-01 22:46:36,554] Trial 9 finished with value: 0.531578947368421 and parameters: {'max_depth': 10, 'learning_rate': 0.04770281678376366, 'n_estimators': 814, 'subsample': 0.7006075367586746, 'colsample_bytree': 0.5827757661434326, 'min_child_weight': 2, 'gamma': 2.0194421656821415, 'reg_alpha': 0.0003475447472398353, 'reg_lambda': 0.12021299747631609, 'max_delta_step': 8}. Best is trial 0 with value: 0.5717105263157894.

Best trial: 12. Best value: 0.625658:  28%|██▊       | 14/50 [02:28<04:52,  8.12s/it]

[I 2025-12-01 22:46:47,669] Trial 12 finished with value: 0.6256578947368421 and parameters: {'max_depth': 9, 'learning_rate': 0.24648400453755984, 'n_estimators': 631, 'subsample': 0.6576598037740977, 'colsample_bytree': 0.8468037905299275, 'min_child_weight': 7, 'gamma': 4.625524040678993, 'reg_alpha': 1.5161501955955123e-06, 'reg_lambda': 1.5390158115939927e-05, 'max_delta_step': 1}. Best is trial 12 with value: 0.6256578947368421.

Best trial: 12. Best value: 0.625658:  30%|███       | 15/50 [02:33<04:06,  7.04s/it]

[I 2025-12-01 22:46:52,130] Trial 17 pruned.

Best trial: 12. Best value: 0.625658:  32%|███▏      | 16/50 [02:40<03:59,  7.04s/it]

[I 2025-12-01 22:46:59,183] Trial 18 pruned.

Best trial: 12. Best value: 0.625658:  34%|███▍      | 17/50 [02:43<03:18,  6.02s/it]

[I 2025-12-01 22:47:02,788] Trial 19 pruned.

Best trial: 12. Best value: 0.625658:  36%|███▌      | 18/50 [02:48<03:05,  5.79s/it]

[I 2025-12-01 22:47:08,051] Trial 20 pruned.

Best trial: 12. Best value: 0.625658:  38%|███▊      | 19/50 [03:09<05:16, 10.22s/it]

[I 2025-12-01 22:47:28,670] Trial 14 finished with value: 0.5967105263157895 and parameters: {'max_depth': 6, 'learning_rate': 0.012889547399859931, 'n_estimators': 1030, 'subsample': 0.5203199043159008, 'colsample_bytree': 0.8552477330096462, 'min_child_weight': 3, 'gamma': 0.7790426645415445, 'reg_alpha': 0.007150808075014666, 'reg_lambda': 7.948421935079871e-05, 'max_delta_step': 10}. Best is trial 12 with value: 0.6256578947368421.

Best trial: 12. Best value: 0.625658:  40%|████      | 20/50 [03:14<04:14,  8.48s/it]

[I 2025-12-01 22:47:33,081] Trial 15 finished with value: 0.5453947368421053 and parameters: {'max_depth': 6, 'learning_rate': 0.0195408745997605, 'n_estimators': 1150, 'subsample': 0.8459780470537712, 'colsample_bytree': 0.8492063582152393, 'min_child_weight': 3, 'gamma': 1.3137514043723493, 'reg_alpha': 8.981165194460993e-06, 'reg_lambda': 2.2785502262091356e-08, 'max_delta_step': 10}. Best is trial 12 with value: 0.6256578947368421.

Best trial: 12. Best value: 0.625658:  42%|████▏     | 21/50 [03:16<03:17,  6.79s/it]

[I 2025-12-01 22:47:35,917] Trial 21 finished with value: 0.5467105263157894 and parameters: {'max_depth': 8, 'learning_rate': 0.05443277321669453, 'n_estimators': 611, 'subsample': 0.5574642794922362, 'colsample_bytree': 0.7942115870337666, 'min_child_weight': 4, 'gamma': 1.9139258017638399, 'reg_alpha': 0.003973656053101545, 'reg_lambda': 1.8976843706156188e-07, 'max_delta_step': 9}. Best is trial 12 with value: 0.6256578947368421.

Best trial: 12. Best value: 0.625658:  44%|████▍     | 22/50 [03:22<02:56,  6.31s/it]

[I 2025-12-01 22:47:41,090] Trial 16 finished with value: 0.5703947368421052 and parameters: {'max_depth': 6, 'learning_rate': 0.020852825880841877, 'n_estimators': 1141, 'subsample': 0.8253995219862313, 'colsample_bytree': 0.855379265762058, 'min_child_weight': 3, 'gamma': 1.3133627127950807, 'reg_alpha': 8.118259544388149e-06, 'reg_lambda': 7.031293272422784e-05, 'max_delta_step': 10}. Best is trial 12 with value: 0.6256578947368421.
[I 2025-12-01 22:47:41,132] Trial 23 pruned.

Best trial: 12. Best value: 0.625658:  48%|████▊     | 24/50 [03:26<01:57,  4.50s/it]

[I 2025-12-01 22:47:45,876] Trial 24 pruned.

Best trial: 12. Best value: 0.625658:  50%|█████     | 25/50 [03:30<01:48,  4.36s/it]

[I 2025-12-01 22:47:49,787] Trial 26 pruned.

Best trial: 12. Best value: 0.625658:  52%|█████▏    | 26/50 [03:32<01:30,  3.75s/it]

[I 2025-12-01 22:47:51,840] Trial 27 pruned.

Best trial: 12. Best value: 0.625658:  54%|█████▍    | 27/50 [03:33<01:05,  2.84s/it]

[I 2025-12-01 22:47:52,235] Trial 25 pruned.

Best trial: 12. Best value: 0.625658:  56%|█████▌    | 28/50 [03:53<02:52,  7.85s/it]

[I 2025-12-01 22:48:12,990] Trial 22 finished with value: 0.5967105263157895 and parameters: {'max_depth': 8, 'learning_rate': 0.18604246023875584, 'n_estimators': 1012, 'subsample': 0.7795427118157967, 'colsample_bytree': 0.9945146115860313, 'min_child_weight': 5, 'gamma': 3.2274291966641324, 'reg_alpha': 0.011283585906919155, 'reg_lambda': 1.9379334348317157e-07, 'max_delta_step': 8}. Best is trial 12 with value: 0.6256578947368421.

Best trial: 12. Best value: 0.625658:  58%|█████▊    | 29/50 [04:02<02:49,  8.09s/it]

[I 2025-12-01 22:48:21,680] Trial 31 pruned.

Best trial: 12. Best value: 0.625658:  60%|██████    | 30/50 [04:06<02:19,  6.97s/it]

[I 2025-12-01 22:48:25,913] Trial 30 finished with value: 0.506578947368421 and parameters: {'max_depth': 9, 'learning_rate': 0.02543269804482581, 'n_estimators': 485, 'subsample': 0.6639604589730201, 'colsample_bytree': 0.7345703197912052, 'min_child_weight': 2, 'gamma': 1.888930454728548, 'reg_alpha': 2.3337348074739122e-07, 'reg_lambda': 0.00910739836557355, 'max_delta_step': 3}. Best is trial 12 with value: 0.6256578947368421.

Best trial: 12. Best value: 0.625658:  62%|██████▏   | 31/50 [04:10<01:56,  6.13s/it]

[I 2025-12-01 22:48:30,020] Trial 32 pruned.

Best trial: 12. Best value: 0.625658:  64%|██████▍   | 32/50 [04:11<01:21,  4.50s/it]

[I 2025-12-01 22:48:30,597] Trial 29 finished with value: 0.5967105263157895 and parameters: {'max_depth': 9, 'learning_rate': 0.040320911775603555, 'n_estimators': 690, 'subsample': 0.6563641202260021, 'colsample_bytree': 0.7426808652588649, 'min_child_weight': 2, 'gamma': 1.6874968510539818, 'reg_alpha': 1.4097839003474473e-07, 'reg_lambda': 0.01077748238712147, 'max_delta_step': 3}. Best is trial 12 with value: 0.6256578947368421.

Best trial: 12. Best value: 0.625658:  66%|██████▌   | 33/50 [04:12<00:59,  3.52s/it]

[I 2025-12-01 22:48:31,798] Trial 28 finished with value: 0.5592105263157895 and parameters: {'max_depth': 3, 'learning_rate': 0.026027909480224386, 'n_estimators': 665, 'subsample': 0.6168593237089893, 'colsample_bytree': 0.7898705646145248, 'min_child_weight': 2, 'gamma': 3.2813322522704658, 'reg_alpha': 1.830995897476034e-07, 'reg_lambda': 0.001135286972340747, 'max_delta_step': 3}. Best is trial 12 with value: 0.6256578947368421.

Best trial: 12. Best value: 0.625658:  68%|██████▊   | 34/50 [04:17<01:03,  3.96s/it]

[I 2025-12-01 22:48:36,798] Trial 35 pruned.

Best trial: 12. Best value: 0.625658:  70%|███████   | 35/50 [04:23<01:05,  4.39s/it]

[I 2025-12-01 22:48:42,191] Trial 36 pruned.

Best trial: 12. Best value: 0.625658:  72%|███████▏  | 36/50 [04:27<01:02,  4.48s/it]

[I 2025-12-01 22:48:46,875] Trial 37 pruned.

Best trial: 12. Best value: 0.625658:  74%|███████▍  | 37/50 [04:46<01:54,  8.78s/it]

[I 2025-12-01 22:49:05,737] Trial 34 finished with value: 0.5453947368421053 and parameters: {'max_depth': 7, 'learning_rate': 0.1199707526781314, 'n_estimators': 690, 'subsample': 0.6993772982743316, 'colsample_bytree': 0.8938486107125259, 'min_child_weight': 3, 'gamma': 4.405759880214578, 'reg_alpha': 6.352309957220242e-05, 'reg_lambda': 2.3582238144995744e-06, 'max_delta_step': 7}. Best is trial 12 with value: 0.6256578947368421.

Best trial: 12. Best value: 0.625658:  76%|███████▌  | 38/50 [04:54<01:41,  8.42s/it]

[I 2025-12-01 22:49:13,324] Trial 39 pruned.

Best trial: 12. Best value: 0.625658:  78%|███████▊  | 39/50 [04:57<01:15,  6.84s/it]

[I 2025-12-01 22:49:16,479] Trial 33 finished with value: 0.6230263157894737 and parameters: {'max_depth': 7, 'learning_rate': 0.13742100271708613, 'n_estimators': 1162, 'subsample': 0.7933380298950545, 'colsample_bytree': 0.8897356245851434, 'min_child_weight': 6, 'gamma': 4.3651443422906295, 'reg_alpha': 0.0030036824364563968, 'reg_lambda': 1.1128566077343593e-07, 'max_delta_step': 9}. Best is trial 12 with value: 0.6256578947368421.

Best trial: 12. Best value: 0.625658:  80%|████████  | 40/50 [05:03<01:05,  6.56s/it]

[I 2025-12-01 22:49:22,381] Trial 38 finished with value: 0.544078947368421 and parameters: {'max_depth': 10, 'learning_rate': 0.20088446828130893, 'n_estimators': 865, 'subsample': 0.7499989920098177, 'colsample_bytree': 0.8131856068287526, 'min_child_weight': 3, 'gamma': 2.397912038219856, 'reg_alpha': 0.13786113827434834, 'reg_lambda': 0.009056040798457534, 'max_delta_step': 1}. Best is trial 12 with value: 0.6256578947368421.

Best trial: 12. Best value: 0.625658:  82%|████████▏ | 41/50 [05:07<00:53,  5.99s/it]

[I 2025-12-01 22:49:27,022] Trial 42 pruned.

Best trial: 12. Best value: 0.625658:  84%|████████▍ | 42/50 [05:13<00:46,  5.79s/it]

[I 2025-12-01 22:49:32,344] Trial 43 pruned.

Best trial: 12. Best value: 0.625658:  86%|████████▌ | 43/50 [05:32<01:07,  9.68s/it]

[I 2025-12-01 22:49:51,111] Trial 40 finished with value: 0.5842105263157895 and parameters: {'max_depth': 10, 'learning_rate': 0.039227427521260703, 'n_estimators': 860, 'subsample': 0.802799331747901, 'colsample_bytree': 0.7272304877162875, 'min_child_weight': 4, 'gamma': 2.4180881634990357, 'reg_alpha': 0.2179367638563303, 'reg_lambda': 0.0003012372189167178, 'max_delta_step': 10}. Best is trial 12 with value: 0.6256578947368421.

Best trial: 12. Best value: 0.625658:  88%|████████▊ | 44/50 [05:36<00:48,  8.15s/it]

[I 2025-12-01 22:49:55,701] Trial 44 pruned.

Best trial: 12. Best value: 0.625658:  90%|█████████ | 45/50 [05:36<00:28,  5.79s/it]

[I 2025-12-01 22:49:55,979] Trial 46 pruned.

Best trial: 12. Best value: 0.625658:  92%|█████████▏| 46/50 [05:41<00:21,  5.37s/it]

[I 2025-12-01 22:50:00,362] Trial 47 pruned.

Best trial: 12. Best value: 0.625658:  94%|█████████▍| 47/50 [05:43<00:13,  4.34s/it]

[I 2025-12-01 22:50:02,297] Trial 48 pruned.

Best trial: 12. Best value: 0.625658:  96%|█████████▌| 48/50 [05:45<00:07,  3.73s/it]

[I 2025-12-01 22:50:04,608] Trial 49 pruned.

Best trial: 12. Best value: 0.625658:  98%|█████████▊| 49/50 [05:50<00:04,  4.08s/it]

[I 2025-12-01 22:50:09,515] Trial 41 finished with value: 0.5703947368421052 and parameters: {'max_depth': 8, 'learning_rate': 0.0629456193150885, 'n_estimators': 1228, 'subsample': 0.8047897916542809, 'colsample_bytree': 0.763861880107048, 'min_child_weight': 4, 'gamma': 2.3096287800990134, 'reg_alpha': 0.009092328143881478, 'reg_lambda': 0.0003278482557222231, 'max_delta_step': 1}. Best is trial 12 with value: 0.6256578947368421.

Best trial: 12. Best value: 0.625658: 100%|██████████| 50/50 [05:55<00:00,  7.10s/it]

[I 2025-12-01 22:50:14,116] Trial 45 finished with value: 0.5842105263157895 and parameters: {'max_depth': 9, 'learning_rate': 0.17099884534439935, 'n_estimators': 1074, 'subsample': 0.8052952575735376, 'colsample_bytree': 0.7692858617325085, 'min_child_weight': 4, 'gamma': 2.9988153612344095, 'reg_alpha': 7.355050883126846e-08, 'reg_lambda': 3.8787015256358434e-07, 'max_delta_step': 10}. Best is trial 12 with value: 0.6256578947368421.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    19_1         loo       0.625658                    0.50          0.48
1    15_1         loo       0.509628                    0.45          0.54
2    17_1         loo       0.614891                    0.45          0.48
3     9_1         loo       0.507895                    0.35          0.44

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.000000               0.2               0.8        50          59
1 -0.188982               0.0               0.9        50          60
2 -0.094491               0.4               0.5        50          60
3 -0.288675               0.2               0.5        50          59

   test_size
0         15
1         15
2         15
3         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    19_1         loo       0.625658                    0.50          0.48
1    15_1         loo       0.509628                    0.45          0.54
2    17_1         loo       0.614891                    0.45          0.48
3     9_1         loo       0.507895                    0.35          0.44

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.000000               0.2               0.8        50          59
1 -0.188982               0.0               0.9        50          60
2 -0.094491               0.4               0.5        50          60
3 -0.288675               0.2               0.5        50          59

   test_size
0         15
1         15
2         15
3         15

In [1573]:

# Combined embedings
datasets = task_comb_dfs_ad_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir="xgb_ad_hc_{CV_STRATEGY}_tasks/xgb_results_combined_ad_hc_extended_{CV_STRATEGY}_tasks",
    split_param="emb_",
)
print(summary)

[I 2025-12-01 22:50:17,955] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0:   2%|▏         | 1/50 [00:12<09:49, 12.03s/it]

[I 2025-12-01 22:50:29,983] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.0114516485911893, 'n_estimators': 205, 'subsample': 0.66152062952084, 'colsample_bytree': 0.6624538049835533, 'min_child_weight': 8, 'gamma': 4.035689963752129, 'reg_alpha': 6.687459677691822, 'reg_lambda': 0.030186011197959415, 'max_delta_step': 2}. Best is trial 3 with value: 0.0.

Best trial: 0. Best value: 0.520395:   4%|▍         | 2/50 [00:20<08:06, 10.14s/it]

[I 2025-12-01 22:50:38,796] Trial 0 finished with value: 0.5203947368421052 and parameters: {'max_depth': 10, 'learning_rate': 0.23174378097471296, 'n_estimators': 363, 'subsample': 0.9066408745585228, 'colsample_bytree': 0.7079308795796284, 'min_child_weight': 5, 'gamma': 0.5932155412243728, 'reg_alpha': 0.02627927831589757, 'reg_lambda': 5.686894130523644e-05, 'max_delta_step': 6}. Best is trial 0 with value: 0.5203947368421052.

Best trial: 0. Best value: 0.520395:   6%|▌         | 3/50 [00:29<07:34,  9.68s/it]

[I 2025-12-01 22:50:47,926] Trial 1 finished with value: 0.475 and parameters: {'max_depth': 8, 'learning_rate': 0.03008044061247381, 'n_estimators': 646, 'subsample': 0.6809772503795464, 'colsample_bytree': 0.6472882148096896, 'min_child_weight': 9, 'gamma': 2.1566884465475162, 'reg_alpha': 0.0016055506846208048, 'reg_lambda': 2.644695000396399e-08, 'max_delta_step': 9}. Best is trial 0 with value: 0.5203947368421052.

Best trial: 2. Best value: 0.585526:   8%|▊         | 4/50 [00:36<06:27,  8.42s/it]

[I 2025-12-01 22:50:54,430] Trial 2 finished with value: 0.5855263157894737 and parameters: {'max_depth': 6, 'learning_rate': 0.08972228222644839, 'n_estimators': 739, 'subsample': 0.7713897546878713, 'colsample_bytree': 0.8978018758762758, 'min_child_weight': 8, 'gamma': 4.357803246735416, 'reg_alpha': 0.14888237574008004, 'reg_lambda': 0.5151527668488889, 'max_delta_step': 8}. Best is trial 2 with value: 0.5855263157894737.

Best trial: 2. Best value: 0.585526:  10%|█         | 5/50 [00:48<07:15,  9.68s/it]

[I 2025-12-01 22:51:06,329] Trial 5 finished with value: 0.2 and parameters: {'max_depth': 7, 'learning_rate': 0.09550244110789465, 'n_estimators': 639, 'subsample': 0.6518570680873956, 'colsample_bytree': 0.5263668429411432, 'min_child_weight': 9, 'gamma': 3.5590837645536437, 'reg_alpha': 0.21510646213634207, 'reg_lambda': 2.5182923850284083e-07, 'max_delta_step': 10}. Best is trial 2 with value: 0.5855263157894737.

Best trial: 2. Best value: 0.585526:  12%|█▏        | 6/50 [00:54<06:11,  8.45s/it]

[I 2025-12-01 22:51:12,397] Trial 6 finished with value: 0.5592105263157895 and parameters: {'max_depth': 5, 'learning_rate': 0.03749894186685189, 'n_estimators': 446, 'subsample': 0.6554546060011436, 'colsample_bytree': 0.6625258260762583, 'min_child_weight': 6, 'gamma': 3.88411194838542, 'reg_alpha': 5.386688756730581e-06, 'reg_lambda': 0.0007357978972850834, 'max_delta_step': 0}. Best is trial 2 with value: 0.5855263157894737.

Best trial: 2. Best value: 0.585526:  14%|█▍        | 7/50 [01:00<05:26,  7.60s/it]

[I 2025-12-01 22:51:18,249] Trial 4 finished with value: 0.5078947368421052 and parameters: {'max_depth': 8, 'learning_rate': 0.02730191560873045, 'n_estimators': 879, 'subsample': 0.9410250201604498, 'colsample_bytree': 0.7948580613513547, 'min_child_weight': 7, 'gamma': 4.520814336352298, 'reg_alpha': 0.04416713379718462, 'reg_lambda': 7.778011232975727e-06, 'max_delta_step': 5}. Best is trial 2 with value: 0.5855263157894737.

Best trial: 8. Best value: 0.599342:  16%|█▌        | 8/50 [01:04<04:34,  6.54s/it]

[I 2025-12-01 22:51:22,513] Trial 8 finished with value: 0.5993421052631579 and parameters: {'max_depth': 9, 'learning_rate': 0.20937058252573462, 'n_estimators': 275, 'subsample': 0.5914321424016397, 'colsample_bytree': 0.9414713220606379, 'min_child_weight': 5, 'gamma': 2.1581193604539783, 'reg_alpha': 0.0013183955563257758, 'reg_lambda': 0.00011868310478579059, 'max_delta_step': 4}. Best is trial 8 with value: 0.5993421052631579.

Best trial: 8. Best value: 0.599342:  18%|█▊        | 9/50 [01:16<05:43,  8.37s/it]

[I 2025-12-01 22:51:34,904] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.018119795280718207, 'n_estimators': 452, 'subsample': 0.7749800689474232, 'colsample_bytree': 0.887211231586787, 'min_child_weight': 10, 'gamma': 3.876697240597351, 'reg_alpha': 0.0031041163602599543, 'reg_lambda': 2.0645629152909897e-08, 'max_delta_step': 10}. Best is trial 8 with value: 0.5993421052631579.

Best trial: 8. Best value: 0.599342:  20%|██        | 10/50 [01:22<04:57,  7.44s/it]

[I 2025-12-01 22:51:40,278] Trial 7 finished with value: 0.5230263157894737 and parameters: {'max_depth': 8, 'learning_rate': 0.287242879569038, 'n_estimators': 1008, 'subsample': 0.9651359057476804, 'colsample_bytree': 0.7470184041392292, 'min_child_weight': 7, 'gamma': 3.510181891568242, 'reg_alpha': 0.004301523367564073, 'reg_lambda': 1.5885447479391723e-06, 'max_delta_step': 5}. Best is trial 8 with value: 0.5993421052631579.

Best trial: 8. Best value: 0.599342:  22%|██▏       | 11/50 [01:25<04:00,  6.17s/it]

[I 2025-12-01 22:51:43,552] Trial 11 pruned.

Best trial: 8. Best value: 0.599342:  24%|██▍       | 12/50 [01:27<03:00,  4.75s/it]

[I 2025-12-01 22:51:45,061] Trial 10 pruned.

Best trial: 8. Best value: 0.599342:  26%|██▌       | 13/50 [01:34<03:28,  5.64s/it]

[I 2025-12-01 22:51:52,748] Trial 13 pruned.

Best trial: 8. Best value: 0.599342:  28%|██▊       | 14/50 [01:44<04:09,  6.92s/it]

[I 2025-12-01 22:52:02,638] Trial 15 pruned.

Best trial: 8. Best value: 0.599342:  30%|███       | 15/50 [02:53<14:54, 25.57s/it]

[I 2025-12-01 22:53:11,415] Trial 17 finished with value: 0.5730263157894737 and parameters: {'max_depth': 6, 'learning_rate': 0.06409264727259761, 'n_estimators': 1069, 'subsample': 0.838780045794936, 'colsample_bytree': 0.896843371321867, 'min_child_weight': 4, 'gamma': 4.891744512097828, 'reg_alpha': 1.2628426620198239, 'reg_lambda': 0.10575258307731888, 'max_delta_step': 8}. Best is trial 8 with value: 0.5993421052631579.

Best trial: 8. Best value: 0.599342:  32%|███▏      | 16/50 [02:56<10:37, 18.74s/it]

[I 2025-12-01 22:53:14,290] Trial 18 pruned.

Best trial: 8. Best value: 0.599342:  34%|███▍      | 17/50 [02:58<07:29, 13.61s/it]

[I 2025-12-01 22:53:15,971] Trial 16 finished with value: 0.5203947368421052 and parameters: {'max_depth': 6, 'learning_rate': 0.09151301417076979, 'n_estimators': 1154, 'subsample': 0.8314269221708741, 'colsample_bytree': 0.9445174263970484, 'min_child_weight': 4, 'gamma': 1.3495278232707588, 'reg_alpha': 3.257427011262288, 'reg_lambda': 9.203188691378259, 'max_delta_step': 7}. Best is trial 8 with value: 0.5993421052631579.

Best trial: 8. Best value: 0.599342:  36%|███▌      | 18/50 [03:00<05:24, 10.13s/it]

[I 2025-12-01 22:53:18,016] Trial 12 finished with value: 0.5203947368421052 and parameters: {'max_depth': 8, 'learning_rate': 0.01976364632707326, 'n_estimators': 856, 'subsample': 0.8208550031335552, 'colsample_bytree': 0.8953660121465314, 'min_child_weight': 1, 'gamma': 3.696124213259713, 'reg_alpha': 0.0001956345783536002, 'reg_lambda': 0.4448705623015578, 'max_delta_step': 10}. Best is trial 8 with value: 0.5993421052631579.

Best trial: 8. Best value: 0.599342:  38%|███▊      | 19/50 [03:06<04:43,  9.13s/it]

[I 2025-12-01 22:53:24,822] Trial 14 finished with value: 0.4953947368421053 and parameters: {'max_depth': 10, 'learning_rate': 0.10414404774743942, 'n_estimators': 1360, 'subsample': 0.5009799838408523, 'colsample_bytree': 0.9830042185901431, 'min_child_weight': 2, 'gamma': 1.8568270517539442, 'reg_alpha': 1.7819144778450126e-07, 'reg_lambda': 8.410977048457706, 'max_delta_step': 7}. Best is trial 8 with value: 0.5993421052631579.

Best trial: 8. Best value: 0.599342:  40%|████      | 20/50 [03:16<04:39,  9.33s/it]

[I 2025-12-01 22:53:34,594] Trial 22 pruned.

Best trial: 8. Best value: 0.599342:  42%|████▏     | 21/50 [03:24<04:19,  8.95s/it]

[I 2025-12-01 22:53:42,684] Trial 23 pruned.

Best trial: 8. Best value: 0.599342:  44%|████▍     | 22/50 [03:30<03:42,  7.93s/it]

[I 2025-12-01 22:53:48,223] Trial 21 finished with value: 0.5592105263157895 and parameters: {'max_depth': 5, 'learning_rate': 0.060852769610186985, 'n_estimators': 526, 'subsample': 0.7105082721132929, 'colsample_bytree': 0.8235115059338309, 'min_child_weight': 6, 'gamma': 0.6736138579244377, 'reg_alpha': 0.24259372797554782, 'reg_lambda': 0.005179417913617659, 'max_delta_step': 1}. Best is trial 8 with value: 0.5993421052631579.

Best trial: 8. Best value: 0.599342:  46%|████▌     | 23/50 [03:41<04:01,  8.94s/it]

[I 2025-12-01 22:53:59,507] Trial 20 finished with value: 0.5605263157894737 and parameters: {'max_depth': 5, 'learning_rate': 0.0625554822387924, 'n_estimators': 848, 'subsample': 0.726354137017071, 'colsample_bytree': 0.8346729091640123, 'min_child_weight': 6, 'gamma': 0.4648335877791845, 'reg_alpha': 0.1270679905881988, 'reg_lambda': 0.21577589821568666, 'max_delta_step': 1}. Best is trial 8 with value: 0.5993421052631579.

Best trial: 8. Best value: 0.599342:  48%|████▊     | 24/50 [03:58<04:57, 11.44s/it]

[I 2025-12-01 22:54:16,772] Trial 19 finished with value: 0.5203947368421052 and parameters: {'max_depth': 6, 'learning_rate': 0.06740909434680582, 'n_estimators': 1185, 'subsample': 0.7634412047857528, 'colsample_bytree': 0.9327819447265832, 'min_child_weight': 5, 'gamma': 0.993472541594, 'reg_alpha': 0.2866863120048995, 'reg_lambda': 0.023682501021572554, 'max_delta_step': 1}. Best is trial 8 with value: 0.5993421052631579.

Best trial: 8. Best value: 0.599342:  50%|█████     | 25/50 [04:35<07:53, 18.95s/it]

[I 2025-12-01 22:54:53,262] Trial 24 finished with value: 0.5855263157894737 and parameters: {'max_depth': 6, 'learning_rate': 0.060713014011312245, 'n_estimators': 1060, 'subsample': 0.8686950953097567, 'colsample_bytree': 0.931687169046436, 'min_child_weight': 4, 'gamma': 4.969525639401262, 'reg_alpha': 1.227728622127259, 'reg_lambda': 0.17263052129305795, 'max_delta_step': 8}. Best is trial 8 with value: 0.5993421052631579.

Best trial: 8. Best value: 0.599342:  52%|█████▏    | 26/50 [04:43<06:19, 15.80s/it]

[I 2025-12-01 22:55:01,714] Trial 25 finished with value: 0.5592105263157895 and parameters: {'max_depth': 6, 'learning_rate': 0.07013087707588672, 'n_estimators': 1153, 'subsample': 0.855660544342734, 'colsample_bytree': 0.9301583530791442, 'min_child_weight': 4, 'gamma': 4.9959080255157975, 'reg_alpha': 1.84253650646933, 'reg_lambda': 0.205666199717582, 'max_delta_step': 8}. Best is trial 8 with value: 0.5993421052631579.

Best trial: 26. Best value: 0.611842:  54%|█████▍    | 27/50 [04:49<04:57, 12.92s/it]

[I 2025-12-01 22:55:07,899] Trial 26 finished with value: 0.6118421052631579 and parameters: {'max_depth': 6, 'learning_rate': 0.1696056954212938, 'n_estimators': 1120, 'subsample': 0.8604826614014786, 'colsample_bytree': 0.9201937144919219, 'min_child_weight': 4, 'gamma': 4.737123508152324, 'reg_alpha': 2.514633332312211, 'reg_lambda': 0.14466304536452085, 'max_delta_step': 8}. Best is trial 26 with value: 0.6118421052631579.

Best trial: 26. Best value: 0.611842:  56%|█████▌    | 28/50 [04:57<04:08, 11.31s/it]

[I 2025-12-01 22:55:15,458] Trial 30 pruned.

Best trial: 26. Best value: 0.611842:  58%|█████▊    | 29/50 [05:05<03:38, 10.41s/it]

[I 2025-12-01 22:55:23,764] Trial 27 finished with value: 0.5855263157894737 and parameters: {'max_depth': 6, 'learning_rate': 0.14052840267766067, 'n_estimators': 1061, 'subsample': 0.8729482509061717, 'colsample_bytree': 0.945035839336174, 'min_child_weight': 4, 'gamma': 4.76847926660366, 'reg_alpha': 1.704573157363732, 'reg_lambda': 0.49728754790804497, 'max_delta_step': 8}. Best is trial 26 with value: 0.6118421052631579.

Best trial: 26. Best value: 0.611842:  60%|██████    | 30/50 [05:09<02:50,  8.51s/it]

[I 2025-12-01 22:55:27,837] Trial 31 pruned.

Best trial: 26. Best value: 0.611842:  62%|██████▏   | 31/50 [05:17<02:35,  8.17s/it]

[I 2025-12-01 22:55:35,215] Trial 33 pruned.

Best trial: 26. Best value: 0.611842:  64%|██████▍   | 32/50 [05:26<02:30,  8.37s/it]

[I 2025-12-01 22:55:44,063] Trial 34 pruned.

Best trial: 26. Best value: 0.611842:  66%|██████▌   | 33/50 [05:41<02:58, 10.51s/it]

[I 2025-12-01 22:55:59,571] Trial 35 pruned.

Best trial: 26. Best value: 0.611842:  68%|██████▊   | 34/50 [05:48<02:29,  9.33s/it]

[I 2025-12-01 22:56:06,135] Trial 29 finished with value: 0.5453947368421053 and parameters: {'max_depth': 7, 'learning_rate': 0.045742821593120715, 'n_estimators': 976, 'subsample': 0.8798575985844381, 'colsample_bytree': 0.95505857097671, 'min_child_weight': 5, 'gamma': 4.457132814980292, 'reg_alpha': 0.015003509894362107, 'reg_lambda': 1.169162887918341, 'max_delta_step': 6}. Best is trial 26 with value: 0.6118421052631579.

Best trial: 26. Best value: 0.611842:  70%|███████   | 35/50 [05:49<01:42,  6.85s/it]

[I 2025-12-01 22:56:07,208] Trial 28 pruned.

Best trial: 26. Best value: 0.611842:  72%|███████▏  | 36/50 [06:13<02:48, 12.00s/it]

[I 2025-12-01 22:56:31,224] Trial 37 pruned.

Best trial: 26. Best value: 0.611842:  74%|███████▍  | 37/50 [06:18<02:09,  9.99s/it]

[I 2025-12-01 22:56:36,531] Trial 39 pruned.

Best trial: 26. Best value: 0.611842:  76%|███████▌  | 38/50 [06:21<01:33,  7.83s/it]

[I 2025-12-01 22:56:39,312] Trial 32 finished with value: 0.5730263157894737 and parameters: {'max_depth': 9, 'learning_rate': 0.22370561677113948, 'n_estimators': 1263, 'subsample': 0.8948187408443252, 'colsample_bytree': 0.7805339011043703, 'min_child_weight': 3, 'gamma': 3.1529487543588695, 'reg_alpha': 0.02764608633833891, 'reg_lambda': 1.248899604064254e-05, 'max_delta_step': 6}. Best is trial 26 with value: 0.6118421052631579.

Best trial: 26. Best value: 0.611842:  78%|███████▊  | 39/50 [06:29<01:26,  7.84s/it]

[I 2025-12-01 22:56:47,188] Trial 41 pruned.

Best trial: 26. Best value: 0.611842:  80%|████████  | 40/50 [06:36<01:16,  7.65s/it]

[I 2025-12-01 22:56:54,389] Trial 36 finished with value: 0.5342105263157895 and parameters: {'max_depth': 7, 'learning_rate': 0.08323962732705165, 'n_estimators': 1070, 'subsample': 0.6927858047119754, 'colsample_bytree': 0.95823900756827, 'min_child_weight': 5, 'gamma': 2.1813018714720736, 'reg_alpha': 0.009440787430297649, 'reg_lambda': 0.0007790703843367563, 'max_delta_step': 9}. Best is trial 26 with value: 0.6118421052631579.

Best trial: 26. Best value: 0.611842:  82%|████████▏ | 41/50 [06:38<00:53,  5.91s/it]

[I 2025-12-01 22:56:56,239] Trial 40 finished with value: 0.5993421052631579 and parameters: {'max_depth': 8, 'learning_rate': 0.12868764461835297, 'n_estimators': 337, 'subsample': 0.929525980016563, 'colsample_bytree': 0.8646357872797902, 'min_child_weight': 7, 'gamma': 0.0850320194745966, 'reg_alpha': 0.06975738369581422, 'reg_lambda': 0.08172188663265054, 'max_delta_step': 4}. Best is trial 26 with value: 0.6118421052631579.

Best trial: 26. Best value: 0.611842:  84%|████████▍ | 42/50 [06:48<00:57,  7.21s/it]

[I 2025-12-01 22:57:06,491] Trial 44 pruned.

Best trial: 26. Best value: 0.611842:  86%|████████▌ | 43/50 [06:49<00:37,  5.41s/it]

[I 2025-12-01 22:57:07,701] Trial 38 finished with value: 0.5881578947368421 and parameters: {'max_depth': 6, 'learning_rate': 0.08251063243756324, 'n_estimators': 1266, 'subsample': 0.9247125704325724, 'colsample_bytree': 0.9138072623089152, 'min_child_weight': 8, 'gamma': 2.309651288157816, 'reg_alpha': 0.6074031782845816, 'reg_lambda': 0.0005189873543090989, 'max_delta_step': 9}. Best is trial 26 with value: 0.6118421052631579.

Best trial: 26. Best value: 0.611842:  88%|████████▊ | 44/50 [06:49<00:23,  3.86s/it]

[I 2025-12-01 22:57:07,939] Trial 42 pruned.

Best trial: 26. Best value: 0.611842:  90%|█████████ | 45/50 [06:53<00:18,  3.69s/it]

[I 2025-12-01 22:57:11,243] Trial 47 pruned.

Best trial: 48. Best value: 0.626974:  92%|█████████▏| 46/50 [07:07<00:27,  6.87s/it]

[I 2025-12-01 22:57:25,510] Trial 48 finished with value: 0.6269736842105263 and parameters: {'max_depth': 9, 'learning_rate': 0.12728503643201078, 'n_estimators': 210, 'subsample': 0.9622892607942591, 'colsample_bytree': 0.970865242130776, 'min_child_weight': 9, 'gamma': 0.15059747329665535, 'reg_alpha': 3.8609175107199816, 'reg_lambda': 0.008792676765324888, 'max_delta_step': 3}. Best is trial 48 with value: 0.6269736842105263.

Best trial: 45. Best value: 0.639474:  94%|█████████▍| 47/50 [07:11<00:18,  6.05s/it]

[I 2025-12-01 22:57:29,654] Trial 45 finished with value: 0.6394736842105263 and parameters: {'max_depth': 5, 'learning_rate': 0.12793431904223304, 'n_estimators': 421, 'subsample': 0.9986787142377722, 'colsample_bytree': 0.9124770843484101, 'min_child_weight': 8, 'gamma': 0.1429505194267522, 'reg_alpha': 0.004408134694510162, 'reg_lambda': 0.007703202212679573, 'max_delta_step': 3}. Best is trial 45 with value: 0.6394736842105263.

Best trial: 45. Best value: 0.639474:  96%|█████████▌| 48/50 [07:20<00:13,  6.90s/it]

[I 2025-12-01 22:57:38,539] Trial 43 finished with value: 0.5717105263157894 and parameters: {'max_depth': 5, 'learning_rate': 0.011878844423142779, 'n_estimators': 418, 'subsample': 0.936331991622432, 'colsample_bytree': 0.8583946117663149, 'min_child_weight': 6, 'gamma': 3.422377263266739, 'reg_alpha': 0.0010700329807793003, 'reg_lambda': 0.06915026991991545, 'max_delta_step': 5}. Best is trial 45 with value: 0.6394736842105263.

Best trial: 45. Best value: 0.639474:  98%|█████████▊| 49/50 [07:22<00:05,  5.41s/it]

[I 2025-12-01 22:57:40,463] Trial 49 finished with value: 0.6394736842105263 and parameters: {'max_depth': 9, 'learning_rate': 0.13628864228606724, 'n_estimators': 253, 'subsample': 0.9602539500334707, 'colsample_bytree': 0.9713000470716104, 'min_child_weight': 9, 'gamma': 0.061967406255307105, 'reg_alpha': 4.201186144092213, 'reg_lambda': 0.005932788900979774, 'max_delta_step': 3}. Best is trial 45 with value: 0.6394736842105263.

Best trial: 45. Best value: 0.639474: 100%|██████████| 50/50 [07:25<00:00,  8.91s/it]

[I 2025-12-01 22:57:43,234] Trial 46 finished with value: 0.6131578947368421 and parameters: {'max_depth': 5, 'learning_rate': 0.010216253096101097, 'n_estimators': 410, 'subsample': 0.9932728633193262, 'colsample_bytree': 0.8665024797170546, 'min_child_weight': 8, 'gamma': 0.18022990721446108, 'reg_alpha': 0.06009230327486122, 'reg_lambda': 3.600635242056275e-05, 'max_delta_step': 3}. Best is trial 45 with value: 0.6394736842105263.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 22:57:46,021] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.523748:   2%|▏         | 1/50 [00:22<18:43, 22.94s/it]

[I 2025-12-01 22:58:08,950] Trial 0 finished with value: 0.5237483953786906 and parameters: {'max_depth': 5, 'learning_rate': 0.030741633423394824, 'n_estimators': 328, 'subsample': 0.7754704707898661, 'colsample_bytree': 0.6878847470035307, 'min_child_weight': 7, 'gamma': 1.3036261738396977, 'reg_alpha': 0.0001266710906224185, 'reg_lambda': 0.4306124807538585, 'max_delta_step': 6}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:   4%|▍         | 2/50 [00:54<22:34, 28.22s/it]

[I 2025-12-01 22:58:40,872] Trial 2 finished with value: 0.4120667522464698 and parameters: {'max_depth': 8, 'learning_rate': 0.017323677832543974, 'n_estimators': 634, 'subsample': 0.639050238819452, 'colsample_bytree': 0.5316104458114191, 'min_child_weight': 2, 'gamma': 4.728095963530123, 'reg_alpha': 7.935986263900702e-05, 'reg_lambda': 0.0010544491768809622, 'max_delta_step': 2}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:   6%|▌         | 3/50 [01:02<14:53, 19.01s/it]

[I 2025-12-01 22:58:48,914] Trial 1 finished with value: 0.4345314505776637 and parameters: {'max_depth': 10, 'learning_rate': 0.07390089381750319, 'n_estimators': 681, 'subsample': 0.6838570457973342, 'colsample_bytree': 0.8450840140780427, 'min_child_weight': 1, 'gamma': 2.0278053922704005, 'reg_alpha': 1.7853457362104254e-07, 'reg_lambda': 1.5331405939743984e-05, 'max_delta_step': 10}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:   8%|▊         | 4/50 [01:55<24:37, 32.11s/it]

[I 2025-12-01 22:59:41,109] Trial 4 finished with value: 0.42041078305519897 and parameters: {'max_depth': 4, 'learning_rate': 0.04402283487852636, 'n_estimators': 1430, 'subsample': 0.9381520635782661, 'colsample_bytree': 0.6160976552237946, 'min_child_weight': 3, 'gamma': 3.6310315306948384, 'reg_alpha': 3.6658637703160164e-08, 'reg_lambda': 0.00412490800951903, 'max_delta_step': 3}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  10%|█         | 5/50 [02:10<19:38, 26.19s/it]

[I 2025-12-01 22:59:56,817] Trial 5 finished with value: 0.4608472400513479 and parameters: {'max_depth': 6, 'learning_rate': 0.01252491813596237, 'n_estimators': 1285, 'subsample': 0.8972095158871021, 'colsample_bytree': 0.5800592617922975, 'min_child_weight': 7, 'gamma': 0.4422785722640865, 'reg_alpha': 0.12764454330477523, 'reg_lambda': 1.0259919607673972e-07, 'max_delta_step': 2}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  12%|█▏        | 6/50 [02:11<12:58, 17.69s/it]

[I 2025-12-01 22:59:57,991] Trial 3 finished with value: 0.4608472400513479 and parameters: {'max_depth': 3, 'learning_rate': 0.13897577372126182, 'n_estimators': 1497, 'subsample': 0.9704104970482523, 'colsample_bytree': 0.8276644739655384, 'min_child_weight': 1, 'gamma': 3.6895072483618048, 'reg_alpha': 2.0544011004836004e-05, 'reg_lambda': 0.24041617098330983, 'max_delta_step': 2}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  14%|█▍        | 7/50 [02:18<09:59, 13.95s/it]

[I 2025-12-01 23:00:04,246] Trial 7 finished with value: 0.4608472400513479 and parameters: {'max_depth': 6, 'learning_rate': 0.0420243123963212, 'n_estimators': 338, 'subsample': 0.7626937838705153, 'colsample_bytree': 0.8484255855698022, 'min_child_weight': 7, 'gamma': 0.7083887852402754, 'reg_alpha': 0.06470846441312889, 'reg_lambda': 8.562990580670119e-07, 'max_delta_step': 1}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  16%|█▌        | 8/50 [02:58<15:33, 22.22s/it]

[I 2025-12-01 23:00:44,171] Trial 6 finished with value: 0.46277278562259305 and parameters: {'max_depth': 5, 'learning_rate': 0.09846967134197203, 'n_estimators': 1307, 'subsample': 0.6264602360561395, 'colsample_bytree': 0.893594324477947, 'min_child_weight': 1, 'gamma': 3.716267684756638, 'reg_alpha': 2.295013636819032, 'reg_lambda': 0.0008616463700923601, 'max_delta_step': 0}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  18%|█▊        | 9/50 [03:17<14:37, 21.40s/it]

[I 2025-12-01 23:01:03,759] Trial 10 finished with value: 0.40821566110397944 and parameters: {'max_depth': 5, 'learning_rate': 0.13541688979745833, 'n_estimators': 1196, 'subsample': 0.6248148004655242, 'colsample_bytree': 0.8483770240982904, 'min_child_weight': 4, 'gamma': 3.431781682135165, 'reg_alpha': 0.00018046155306428657, 'reg_lambda': 0.12678805624520414, 'max_delta_step': 3}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  20%|██        | 10/50 [03:34<13:24, 20.11s/it]

[I 2025-12-01 23:01:20,986] Trial 11 finished with value: 0.42233632862644416 and parameters: {'max_depth': 4, 'learning_rate': 0.06716679243083193, 'n_estimators': 535, 'subsample': 0.6323222059628816, 'colsample_bytree': 0.593915580348968, 'min_child_weight': 3, 'gamma': 3.4209949299876263, 'reg_alpha': 0.12774960459550766, 'reg_lambda': 0.020755076789888364, 'max_delta_step': 8}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  22%|██▏       | 11/50 [03:37<09:29, 14.60s/it]

[I 2025-12-01 23:01:23,080] Trial 13 pruned.

Best trial: 0. Best value: 0.523748:  24%|██▍       | 12/50 [03:55<09:55, 15.67s/it]

[I 2025-12-01 23:01:41,198] Trial 8 finished with value: 0.42041078305519897 and parameters: {'max_depth': 7, 'learning_rate': 0.01236822319095845, 'n_estimators': 798, 'subsample': 0.8897476669475384, 'colsample_bytree': 0.7196602803837049, 'min_child_weight': 2, 'gamma': 2.572485178602446, 'reg_alpha': 3.2421344002592036, 'reg_lambda': 0.32807619786826714, 'max_delta_step': 5}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  26%|██▌       | 13/50 [04:04<08:28, 13.74s/it]

[I 2025-12-01 23:01:50,497] Trial 9 finished with value: 0.39216944801026954 and parameters: {'max_depth': 9, 'learning_rate': 0.02879768977623224, 'n_estimators': 594, 'subsample': 0.5773218280647896, 'colsample_bytree': 0.8354436044653532, 'min_child_weight': 1, 'gamma': 0.032366091433000954, 'reg_alpha': 0.014570536823975255, 'reg_lambda': 1.1899385757619865, 'max_delta_step': 9}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  28%|██▊       | 14/50 [04:23<09:10, 15.28s/it]

[I 2025-12-01 23:02:09,348] Trial 12 finished with value: 0.4608472400513479 and parameters: {'max_depth': 6, 'learning_rate': 0.010106827988440651, 'n_estimators': 746, 'subsample': 0.5024391800160173, 'colsample_bytree': 0.5929627351700446, 'min_child_weight': 4, 'gamma': 0.7873000278768927, 'reg_alpha': 6.718196808387125e-05, 'reg_lambda': 2.2275925767176794e-06, 'max_delta_step': 8}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  30%|███       | 15/50 [04:48<10:34, 18.12s/it]

[I 2025-12-01 23:02:34,047] Trial 14 finished with value: 0.511553273427471 and parameters: {'max_depth': 7, 'learning_rate': 0.02457188757354544, 'n_estimators': 988, 'subsample': 0.790962619378053, 'colsample_bytree': 0.9764737831316987, 'min_child_weight': 6, 'gamma': 1.3720431122842212, 'reg_alpha': 0.004613868415678899, 'reg_lambda': 7.146732016649431e-05, 'max_delta_step': 5}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  32%|███▏      | 16/50 [05:07<10:32, 18.60s/it]

[I 2025-12-01 23:02:53,775] Trial 15 finished with value: 0.48523748395378685 and parameters: {'max_depth': 5, 'learning_rate': 0.02416324186528, 'n_estimators': 1010, 'subsample': 0.7906091944680876, 'colsample_bytree': 0.9911956247393557, 'min_child_weight': 6, 'gamma': 1.4199713058508263, 'reg_alpha': 0.003965863237713908, 'reg_lambda': 6.953168811171112e-05, 'max_delta_step': 6}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  34%|███▍      | 17/50 [05:16<08:40, 15.77s/it]

[I 2025-12-01 23:03:02,960] Trial 16 finished with value: 0.4993581514762516 and parameters: {'max_depth': 5, 'learning_rate': 0.024471038777542142, 'n_estimators': 1013, 'subsample': 0.799220820799045, 'colsample_bytree': 0.9755912627264764, 'min_child_weight': 6, 'gamma': 1.3879477955941242, 'reg_alpha': 0.004019748891104753, 'reg_lambda': 5.120503394511237e-05, 'max_delta_step': 6}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  36%|███▌      | 18/50 [05:22<06:46, 12.71s/it]

[I 2025-12-01 23:03:08,541] Trial 17 finished with value: 0.4974326059050064 and parameters: {'max_depth': 4, 'learning_rate': 0.024051128636706928, 'n_estimators': 999, 'subsample': 0.7838950685784041, 'colsample_bytree': 0.9446371820791145, 'min_child_weight': 7, 'gamma': 4.883283767036117, 'reg_alpha': 0.0022908100476740725, 'reg_lambda': 0.00010606989951067804, 'max_delta_step': 5}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  38%|███▊      | 19/50 [05:44<08:01, 15.55s/it]

[I 2025-12-01 23:03:30,700] Trial 21 finished with value: 0.42426187419768935 and parameters: {'max_depth': 7, 'learning_rate': 0.040055896361528696, 'n_estimators': 431, 'subsample': 0.8465754293206771, 'colsample_bytree': 0.6774521799067192, 'min_child_weight': 9, 'gamma': 2.3487425902262835, 'reg_alpha': 5.521877299974629e-06, 'reg_lambda': 0.008282199783091429, 'max_delta_step': 4}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  40%|████      | 20/50 [05:51<06:23, 12.80s/it]

[I 2025-12-01 23:03:37,090] Trial 18 finished with value: 0.48523748395378685 and parameters: {'max_depth': 7, 'learning_rate': 0.023106783499652127, 'n_estimators': 985, 'subsample': 0.7976400775662786, 'colsample_bytree': 0.9678456561541461, 'min_child_weight': 7, 'gamma': 1.4940432182302537, 'reg_alpha': 0.001883206649420965, 'reg_lambda': 6.319893241147243e-05, 'max_delta_step': 6}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  42%|████▏     | 21/50 [05:58<05:26, 11.25s/it]

[I 2025-12-01 23:03:44,720] Trial 23 pruned.

Best trial: 0. Best value: 0.523748:  44%|████▍     | 22/50 [06:01<04:05,  8.78s/it]

[I 2025-12-01 23:03:47,758] Trial 19 finished with value: 0.4749679075738126 and parameters: {'max_depth': 7, 'learning_rate': 0.025767405167057243, 'n_estimators': 1012, 'subsample': 0.8143633034648479, 'colsample_bytree': 0.9727459400304898, 'min_child_weight': 9, 'gamma': 1.2987839572667599, 'reg_alpha': 0.001934996313243431, 'reg_lambda': 6.8730739860525e-05, 'max_delta_step': 5}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  46%|████▌     | 23/50 [06:06<03:22,  7.49s/it]

[I 2025-12-01 23:03:52,217] Trial 20 finished with value: 0.4486521181001284 and parameters: {'max_depth': 7, 'learning_rate': 0.03074369498779643, 'n_estimators': 1004, 'subsample': 0.8456469278542089, 'colsample_bytree': 0.6661370826255275, 'min_child_weight': 9, 'gamma': 2.095118673691773, 'reg_alpha': 2.4982094248736204e-06, 'reg_lambda': 0.00975581669933478, 'max_delta_step': 4}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  48%|████▊     | 24/50 [06:31<05:32, 12.78s/it]

[I 2025-12-01 23:04:17,344] Trial 22 finished with value: 0.4749679075738126 and parameters: {'max_depth': 8, 'learning_rate': 0.017080429932787668, 'n_estimators': 905, 'subsample': 0.7114188031962829, 'colsample_bytree': 0.7805883215649305, 'min_child_weight': 8, 'gamma': 2.800466116267392, 'reg_alpha': 0.001339801309896548, 'reg_lambda': 4.394814291852717e-08, 'max_delta_step': 7}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  50%|█████     | 25/50 [07:12<08:51, 21.26s/it]

[I 2025-12-01 23:04:58,403] Trial 25 finished with value: 0.4608472400513479 and parameters: {'max_depth': 3, 'learning_rate': 0.03409338279276179, 'n_estimators': 1157, 'subsample': 0.7129393412320275, 'colsample_bytree': 0.9072767323609962, 'min_child_weight': 5, 'gamma': 2.506299050724298, 'reg_alpha': 0.01360860874139719, 'reg_lambda': 1.452677719959435e-07, 'max_delta_step': 7}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  52%|█████▏    | 26/50 [07:13<06:07, 15.32s/it]

[I 2025-12-01 23:04:59,844] Trial 24 finished with value: 0.48523748395378685 and parameters: {'max_depth': 3, 'learning_rate': 0.03195672150630006, 'n_estimators': 1158, 'subsample': 0.8345604698055469, 'colsample_bytree': 0.9230168177427013, 'min_child_weight': 5, 'gamma': 2.4604735621107863, 'reg_alpha': 5.5820690546528795e-06, 'reg_lambda': 3.268562923033478e-08, 'max_delta_step': 7}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  54%|█████▍    | 27/50 [07:34<06:31, 17.01s/it]

[I 2025-12-01 23:05:20,798] Trial 26 finished with value: 0.4974326059050064 and parameters: {'max_depth': 3, 'learning_rate': 0.01749163011441268, 'n_estimators': 1172, 'subsample': 0.7167782586160775, 'colsample_bytree': 0.9140652485736436, 'min_child_weight': 5, 'gamma': 0.2815595517186076, 'reg_alpha': 0.019730034240899152, 'reg_lambda': 1.4760000339849594e-08, 'max_delta_step': 7}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  56%|█████▌    | 28/50 [07:43<05:18, 14.46s/it]

[I 2025-12-01 23:05:29,298] Trial 27 finished with value: 0.4711168164313222 and parameters: {'max_depth': 3, 'learning_rate': 0.0351193959071629, 'n_estimators': 1132, 'subsample': 0.7485528842848463, 'colsample_bytree': 0.9148164142000162, 'min_child_weight': 5, 'gamma': 1.08977353363171, 'reg_alpha': 0.04690061399600166, 'reg_lambda': 1.0115575337840894e-05, 'max_delta_step': 7}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  58%|█████▊    | 29/50 [08:01<05:28, 15.67s/it]

[I 2025-12-01 23:05:47,785] Trial 29 finished with value: 0.47304236200256744 and parameters: {'max_depth': 5, 'learning_rate': 0.05435061845853668, 'n_estimators': 823, 'subsample': 0.7465424163121704, 'colsample_bytree': 0.8833095857918749, 'min_child_weight': 6, 'gamma': 0.24833768406902723, 'reg_alpha': 0.01569182131710915, 'reg_lambda': 1.0753380858166355e-05, 'max_delta_step': 4}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  60%|██████    | 30/50 [08:19<05:24, 16.21s/it]

[I 2025-12-01 23:06:05,263] Trial 28 finished with value: 0.47304236200256744 and parameters: {'max_depth': 5, 'learning_rate': 0.05523455398091048, 'n_estimators': 1120, 'subsample': 0.8441220479532451, 'colsample_bytree': 0.9235977694149727, 'min_child_weight': 6, 'gamma': 0.34246393311864587, 'reg_alpha': 0.41738531252775063, 'reg_lambda': 8.721468739142165e-06, 'max_delta_step': 7}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  62%|██████▏   | 31/50 [08:26<04:17, 13.56s/it]

[I 2025-12-01 23:06:12,636] Trial 30 finished with value: 0.47304236200256744 and parameters: {'max_depth': 5, 'learning_rate': 0.05029657534294864, 'n_estimators': 863, 'subsample': 0.8819742515040855, 'colsample_bytree': 0.6471927742279425, 'min_child_weight': 6, 'gamma': 1.1515278679953302, 'reg_alpha': 0.4551501001665745, 'reg_lambda': 1.5584399772719775e-05, 'max_delta_step': 4}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  64%|██████▍   | 32/50 [08:35<03:39, 12.19s/it]

[I 2025-12-01 23:06:21,630] Trial 31 finished with value: 0.47304236200256744 and parameters: {'max_depth': 5, 'learning_rate': 0.054890226360995026, 'n_estimators': 853, 'subsample': 0.8783559858847105, 'colsample_bytree': 0.7996545163502491, 'min_child_weight': 6, 'gamma': 1.7616074149058543, 'reg_alpha': 0.44987212570779866, 'reg_lambda': 0.00045304902682677937, 'max_delta_step': 4}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  66%|██████▌   | 33/50 [08:41<02:53, 10.18s/it]

[I 2025-12-01 23:06:27,133] Trial 32 finished with value: 0.511553273427471 and parameters: {'max_depth': 10, 'learning_rate': 0.0656098435574899, 'n_estimators': 698, 'subsample': 0.882144510226768, 'colsample_bytree': 0.7911055231171176, 'min_child_weight': 8, 'gamma': 1.8488499528542057, 'reg_alpha': 0.6284633178211343, 'reg_lambda': 0.00038363447077117524, 'max_delta_step': 10}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  68%|██████▊   | 34/50 [09:04<03:47, 14.24s/it]

[I 2025-12-01 23:06:50,831] Trial 33 finished with value: 0.511553273427471 and parameters: {'max_depth': 10, 'learning_rate': 0.020235200919238507, 'n_estimators': 700, 'subsample': 0.8915827443973091, 'colsample_bytree': 0.8096201439488511, 'min_child_weight': 8, 'gamma': 1.839943846904522, 'reg_alpha': 0.0002912926821757558, 'reg_lambda': 0.00024000860396768502, 'max_delta_step': 9}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  70%|███████   | 35/50 [09:05<02:34, 10.29s/it]

[I 2025-12-01 23:06:51,916] Trial 36 finished with value: 0.511553273427471 and parameters: {'max_depth': 10, 'learning_rate': 0.0805765949226777, 'n_estimators': 465, 'subsample': 0.919185276652136, 'colsample_bytree': 0.5202122867963925, 'min_child_weight': 8, 'gamma': 1.9430896817834407, 'reg_alpha': 5.4778301793406234e-05, 'reg_lambda': 0.0022563040854586868, 'max_delta_step': 10}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  72%|███████▏  | 36/50 [09:08<01:53,  8.11s/it]

[I 2025-12-01 23:06:54,949] Trial 34 finished with value: 0.4749679075738126 and parameters: {'max_depth': 4, 'learning_rate': 0.021459741368059605, 'n_estimators': 718, 'subsample': 0.7849892286121481, 'colsample_bytree': 0.9571458673488104, 'min_child_weight': 8, 'gamma': 1.8473126580730241, 'reg_alpha': 0.0004126194324594993, 'reg_lambda': 0.00024340859971875946, 'max_delta_step': 5}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  74%|███████▍  | 37/50 [09:19<01:55,  8.91s/it]

[I 2025-12-01 23:07:05,709] Trial 35 finished with value: 0.45057766367137353 and parameters: {'max_depth': 4, 'learning_rate': 0.021612290395687583, 'n_estimators': 769, 'subsample': 0.7652352967938201, 'colsample_bytree': 0.9996584551936771, 'min_child_weight': 8, 'gamma': 4.768887575086443, 'reg_alpha': 0.0003330974002763423, 'reg_lambda': 0.0001543371806151985, 'max_delta_step': 5}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  76%|███████▌  | 38/50 [09:24<01:32,  7.74s/it]

[I 2025-12-01 23:07:10,733] Trial 40 pruned.

Best trial: 0. Best value: 0.523748:  78%|███████▊  | 39/50 [09:40<01:53, 10.29s/it]

[I 2025-12-01 23:07:26,977] Trial 37 finished with value: 0.511553273427471 and parameters: {'max_depth': 10, 'learning_rate': 0.08106095036297771, 'n_estimators': 730, 'subsample': 0.9390383323308669, 'colsample_bytree': 0.5017611243098423, 'min_child_weight': 8, 'gamma': 1.868657131960272, 'reg_alpha': 3.621745337689149e-05, 'reg_lambda': 0.0018419928728551022, 'max_delta_step': 10}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  80%|████████  | 40/50 [09:42<01:16,  7.64s/it]

[I 2025-12-01 23:07:28,410] Trial 39 finished with value: 0.4467265725288832 and parameters: {'max_depth': 10, 'learning_rate': 0.11092205204043633, 'n_estimators': 599, 'subsample': 0.9981085089550572, 'colsample_bytree': 0.733860213604936, 'min_child_weight': 8, 'gamma': 3.019879844248992, 'reg_alpha': 1.7925016173612605e-05, 'reg_lambda': 0.04444819290522847, 'max_delta_step': 10}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  82%|████████▏ | 41/50 [09:51<01:11,  8.00s/it]

[I 2025-12-01 23:07:37,256] Trial 38 finished with value: 0.4608472400513479 and parameters: {'max_depth': 10, 'learning_rate': 0.018814785469363195, 'n_estimators': 663, 'subsample': 0.9523205920899996, 'colsample_bytree': 0.7406643084227684, 'min_child_weight': 8, 'gamma': 3.013121983288307, 'reg_alpha': 0.00037398077259700476, 'reg_lambda': 0.0002422456163250686, 'max_delta_step': 10}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  84%|████████▍ | 42/50 [10:00<01:06,  8.29s/it]

[I 2025-12-01 23:07:46,229] Trial 41 finished with value: 0.4608472400513479 and parameters: {'max_depth': 9, 'learning_rate': 0.013807975856176715, 'n_estimators': 283, 'subsample': 0.9507950702073055, 'colsample_bytree': 0.8724444912352365, 'min_child_weight': 7, 'gamma': 0.6511555657688644, 'reg_alpha': 3.040729135185085e-07, 'reg_lambda': 0.0014625812705691577, 'max_delta_step': 9}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  86%|████████▌ | 43/50 [10:09<00:59,  8.54s/it]

[I 2025-12-01 23:07:55,349] Trial 42 finished with value: 0.45892169448010267 and parameters: {'max_depth': 9, 'learning_rate': 0.01936600044325213, 'n_estimators': 200, 'subsample': 0.9972557918014089, 'colsample_bytree': 0.8139316030594096, 'min_child_weight': 7, 'gamma': 1.6355867657127245, 'reg_alpha': 3.3774555546906566e-07, 'reg_lambda': 0.0008200397582904425, 'max_delta_step': 9}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  88%|████████▊ | 44/50 [10:20<00:55,  9.22s/it]

[I 2025-12-01 23:08:06,142] Trial 44 finished with value: 0.4486521181001284 and parameters: {'max_depth': 9, 'learning_rate': 0.07171677943872584, 'n_estimators': 460, 'subsample': 0.9239612313016323, 'colsample_bytree': 0.5374444616813611, 'min_child_weight': 7, 'gamma': 1.612195604064907, 'reg_alpha': 2.872610337867413e-07, 'reg_lambda': 0.001975980394619458, 'max_delta_step': 9}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  90%|█████████ | 45/50 [10:24<00:39,  7.88s/it]

[I 2025-12-01 23:08:10,921] Trial 47 pruned.

Best trial: 0. Best value: 0.523748:  92%|█████████▏| 46/50 [10:26<00:23,  5.88s/it]

[I 2025-12-01 23:08:12,125] Trial 43 finished with value: 0.4486521181001284 and parameters: {'max_depth': 9, 'learning_rate': 0.014039981055087603, 'n_estimators': 356, 'subsample': 0.9415454495919956, 'colsample_bytree': 0.7961329169793439, 'min_child_weight': 7, 'gamma': 1.5836122274271154, 'reg_alpha': 2.8321639665443774e-07, 'reg_lambda': 0.0005998605949400302, 'max_delta_step': 9}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  94%|█████████▍| 47/50 [10:30<00:16,  5.35s/it]

[I 2025-12-01 23:08:16,246] Trial 45 finished with value: 0.4345314505776637 and parameters: {'max_depth': 9, 'learning_rate': 0.06452854217332285, 'n_estimators': 463, 'subsample': 0.9205544913709414, 'colsample_bytree': 0.5439183264635442, 'min_child_weight': 7, 'gamma': 1.5712396087679508, 'reg_alpha': 0.0001482773843127246, 'reg_lambda': 0.0040314611561912345, 'max_delta_step': 9}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  96%|█████████▌| 48/50 [10:36<00:11,  5.63s/it]

[I 2025-12-01 23:08:22,518] Trial 46 finished with value: 0.4486521181001284 and parameters: {'max_depth': 9, 'learning_rate': 0.0726210528125365, 'n_estimators': 461, 'subsample': 0.9196155576901471, 'colsample_bytree': 0.5597956531667383, 'min_child_weight': 7, 'gamma': 4.351543035605594, 'reg_alpha': 8.220053524392972e-05, 'reg_lambda': 1.1375459437880708, 'max_delta_step': 9}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748:  98%|█████████▊| 49/50 [10:42<00:05,  5.60s/it]

[I 2025-12-01 23:08:28,045] Trial 48 finished with value: 0.4871630295250321 and parameters: {'max_depth': 9, 'learning_rate': 0.06459146756154563, 'n_estimators': 331, 'subsample': 0.8686289802840615, 'colsample_bytree': 0.6276268359714461, 'min_child_weight': 8, 'gamma': 0.7824759640645738, 'reg_alpha': 3.3179001409364916e-05, 'reg_lambda': 1.3648172541420276, 'max_delta_step': 8}. Best is trial 0 with value: 0.5237483953786906.

Best trial: 0. Best value: 0.523748: 100%|██████████| 50/50 [10:44<00:00, 12.89s/it]

[I 2025-12-01 23:08:30,605] Trial 49 finished with value: 0.47304236200256744 and parameters: {'max_depth': 6, 'learning_rate': 0.08013100354390837, 'n_estimators': 401, 'subsample': 0.8698014958208111, 'colsample_bytree': 0.6409539129370765, 'min_child_weight': 8, 'gamma': 0.8606894215080666, 'reg_alpha': 1.5661109184231004e-05, 'reg_lambda': 0.0044175659173974315, 'max_delta_step': 8}. Best is trial 0 with value: 0.5237483953786906.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 23:08:36,872] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.527599:   2%|▏         | 1/50 [00:17<14:29, 17.75s/it]

[I 2025-12-01 23:08:54,617] Trial 1 finished with value: 0.527599486521181 and parameters: {'max_depth': 6, 'learning_rate': 0.07371628451125908, 'n_estimators': 240, 'subsample': 0.7241879912673045, 'colsample_bytree': 0.9312777125044289, 'min_child_weight': 6, 'gamma': 2.248989291752834, 'reg_alpha': 1.1589711339120959e-05, 'reg_lambda': 0.000346608280784593, 'max_delta_step': 8}. Best is trial 1 with value: 0.527599486521181.

Best trial: 2. Best value: 0.594352:   4%|▍         | 2/50 [00:46<19:10, 23.96s/it]

[I 2025-12-01 23:09:22,922] Trial 2 finished with value: 0.5943517329910142 and parameters: {'max_depth': 8, 'learning_rate': 0.0303672540036096, 'n_estimators': 973, 'subsample': 0.7330141657870692, 'colsample_bytree': 0.5097515209414268, 'min_child_weight': 7, 'gamma': 0.03847436770670509, 'reg_alpha': 0.09336332244784004, 'reg_lambda': 6.175825165048998e-06, 'max_delta_step': 0}. Best is trial 2 with value: 0.5943517329910142.

Best trial: 2. Best value: 0.594352:   6%|▌         | 3/50 [00:48<10:54, 13.93s/it]

[I 2025-12-01 23:09:24,921] Trial 0 finished with value: 0.41014120667522463 and parameters: {'max_depth': 6, 'learning_rate': 0.10644661003685867, 'n_estimators': 755, 'subsample': 0.8370056428583772, 'colsample_bytree': 0.5697376661386133, 'min_child_weight': 3, 'gamma': 4.957128346679019, 'reg_alpha': 1.5964480561329843e-06, 'reg_lambda': 2.4136123962910887e-07, 'max_delta_step': 4}. Best is trial 2 with value: 0.5943517329910142.

Best trial: 2. Best value: 0.594352:   8%|▊         | 4/50 [00:52<07:52, 10.27s/it]

[I 2025-12-01 23:09:29,576] Trial 3 finished with value: 0.2894736842105263 and parameters: {'max_depth': 7, 'learning_rate': 0.030382882523394075, 'n_estimators': 1247, 'subsample': 0.6935443797677001, 'colsample_bytree': 0.511794242971352, 'min_child_weight': 10, 'gamma': 0.32074090915277353, 'reg_alpha': 0.08639938463156636, 'reg_lambda': 1.7812632049967282e-06, 'max_delta_step': 10}. Best is trial 2 with value: 0.5943517329910142.

Best trial: 2. Best value: 0.594352:  10%|█         | 5/50 [00:57<06:09,  8.21s/it]

[I 2025-12-01 23:09:34,124] Trial 4 finished with value: 0.5012836970474968 and parameters: {'max_depth': 10, 'learning_rate': 0.07505883391237984, 'n_estimators': 615, 'subsample': 0.9096518552022446, 'colsample_bytree': 0.7450609635147928, 'min_child_weight': 4, 'gamma': 1.9485596568796888, 'reg_alpha': 9.522554016438807e-06, 'reg_lambda': 8.989425195417e-07, 'max_delta_step': 1}. Best is trial 2 with value: 0.5943517329910142.

Best trial: 2. Best value: 0.594352:  12%|█▏        | 6/50 [01:17<08:54, 12.15s/it]

[I 2025-12-01 23:09:53,936] Trial 8 finished with value: 0.5378690629011553 and parameters: {'max_depth': 9, 'learning_rate': 0.12768487957257257, 'n_estimators': 258, 'subsample': 0.845117951586, 'colsample_bytree': 0.9507049330000807, 'min_child_weight': 5, 'gamma': 1.028578547453069, 'reg_alpha': 2.5019463515043164e-08, 'reg_lambda': 1.875636812219273, 'max_delta_step': 10}. Best is trial 2 with value: 0.5943517329910142.

Best trial: 2. Best value: 0.594352:  14%|█▍        | 7/50 [01:29<08:47, 12.26s/it]

[I 2025-12-01 23:10:06,410] Trial 5 finished with value: 0.5378690629011553 and parameters: {'max_depth': 6, 'learning_rate': 0.0883016603351991, 'n_estimators': 594, 'subsample': 0.6299964830342186, 'colsample_bytree': 0.5116599963178902, 'min_child_weight': 1, 'gamma': 2.812621838291271, 'reg_alpha': 0.00028101066382899665, 'reg_lambda': 3.0482389655194504e-05, 'max_delta_step': 4}. Best is trial 2 with value: 0.5943517329910142.

Best trial: 2. Best value: 0.594352:  16%|█▌        | 8/50 [01:38<07:45, 11.09s/it]

[I 2025-12-01 23:10:15,006] Trial 7 finished with value: 0.576379974326059 and parameters: {'max_depth': 8, 'learning_rate': 0.042726384428802375, 'n_estimators': 772, 'subsample': 0.571902056252846, 'colsample_bytree': 0.6988495555881509, 'min_child_weight': 4, 'gamma': 4.603883633962848, 'reg_alpha': 1.7125389629432146, 'reg_lambda': 2.2821608546732886e-07, 'max_delta_step': 3}. Best is trial 2 with value: 0.5943517329910142.

Best trial: 6. Best value: 0.646983:  18%|█▊        | 9/50 [01:56<09:06, 13.34s/it]

[I 2025-12-01 23:10:33,279] Trial 6 finished with value: 0.6469833119383825 and parameters: {'max_depth': 10, 'learning_rate': 0.016196110408085898, 'n_estimators': 1438, 'subsample': 0.9392518943746169, 'colsample_bytree': 0.7619387993410756, 'min_child_weight': 9, 'gamma': 2.535840283887038, 'reg_alpha': 3.8253684739330025e-07, 'reg_lambda': 0.13998508319106479, 'max_delta_step': 6}. Best is trial 6 with value: 0.6469833119383825.

Best trial: 6. Best value: 0.646983:  20%|██        | 10/50 [02:16<10:11, 15.29s/it]

[I 2025-12-01 23:10:52,949] Trial 9 finished with value: 0.5378690629011553 and parameters: {'max_depth': 4, 'learning_rate': 0.10299241142239118, 'n_estimators': 677, 'subsample': 0.8464884247547007, 'colsample_bytree': 0.9190682781319217, 'min_child_weight': 2, 'gamma': 4.663958121762671, 'reg_alpha': 2.3019602993108086e-05, 'reg_lambda': 0.006117407900373313, 'max_delta_step': 2}. Best is trial 6 with value: 0.6469833119383825.

Best trial: 6. Best value: 0.646983:  22%|██▏       | 11/50 [02:18<07:25, 11.42s/it]

[I 2025-12-01 23:10:55,598] Trial 11 pruned.

Best trial: 6. Best value: 0.646983:  24%|██▍       | 12/50 [02:20<05:18,  8.37s/it]

[I 2025-12-01 23:10:56,992] Trial 10 pruned.

Best trial: 6. Best value: 0.646983:  26%|██▌       | 13/50 [02:28<05:04,  8.23s/it]

[I 2025-12-01 23:11:04,904] Trial 13 pruned.

Best trial: 6. Best value: 0.646983:  28%|██▊       | 14/50 [02:34<04:38,  7.74s/it]

[I 2025-12-01 23:11:11,494] Trial 15 pruned.

Best trial: 6. Best value: 0.646983:  30%|███       | 15/50 [02:51<06:02, 10.37s/it]

[I 2025-12-01 23:11:27,969] Trial 12 finished with value: 0.6206675224646983 and parameters: {'max_depth': 6, 'learning_rate': 0.13244084026599282, 'n_estimators': 1178, 'subsample': 0.6925008827221494, 'colsample_bytree': 0.8694662294855364, 'min_child_weight': 8, 'gamma': 1.3348881559577404, 'reg_alpha': 2.212313723666275e-08, 'reg_lambda': 0.0024496147656561033, 'max_delta_step': 2}. Best is trial 6 with value: 0.6469833119383825.

Best trial: 6. Best value: 0.646983:  32%|███▏      | 16/50 [03:16<08:21, 14.76s/it]

[I 2025-12-01 23:11:52,927] Trial 16 finished with value: 0.5680359435173299 and parameters: {'max_depth': 10, 'learning_rate': 0.24106091561338688, 'n_estimators': 1027, 'subsample': 0.9876600562439146, 'colsample_bytree': 0.8276467040953815, 'min_child_weight': 8, 'gamma': 3.8107804290948932, 'reg_alpha': 0.014002119624864324, 'reg_lambda': 0.0653786104132671, 'max_delta_step': 5}. Best is trial 6 with value: 0.6469833119383825.

Best trial: 6. Best value: 0.646983:  34%|███▍      | 17/50 [03:20<06:20, 11.54s/it]

[I 2025-12-01 23:11:56,971] Trial 17 finished with value: 0.6187419768934532 and parameters: {'max_depth': 8, 'learning_rate': 0.22212695819608305, 'n_estimators': 1005, 'subsample': 0.794708319336897, 'colsample_bytree': 0.6602668602478978, 'min_child_weight': 8, 'gamma': 1.6506058074122851, 'reg_alpha': 0.007982172653766694, 'reg_lambda': 0.009735665288470197, 'max_delta_step': 8}. Best is trial 6 with value: 0.6469833119383825.

Best trial: 6. Best value: 0.646983:  36%|███▌      | 18/50 [03:26<05:16,  9.88s/it]

[I 2025-12-01 23:12:02,988] Trial 19 pruned.

Best trial: 6. Best value: 0.646983:  38%|███▊      | 19/50 [03:30<04:12,  8.16s/it]

[I 2025-12-01 23:12:07,144] Trial 20 pruned.

Best trial: 6. Best value: 0.646983:  40%|████      | 20/50 [03:42<04:45,  9.51s/it]

[I 2025-12-01 23:12:19,789] Trial 14 finished with value: 0.5962772785622593 and parameters: {'max_depth': 10, 'learning_rate': 0.01127899888902853, 'n_estimators': 1478, 'subsample': 0.9976288066380756, 'colsample_bytree': 0.8318246215846464, 'min_child_weight': 8, 'gamma': 3.322837681895173, 'reg_alpha': 0.019471054060976024, 'reg_lambda': 0.11598689276377111, 'max_delta_step': 6}. Best is trial 6 with value: 0.6469833119383825.

Best trial: 6. Best value: 0.646983:  42%|████▏     | 21/50 [03:49<04:06,  8.49s/it]

[I 2025-12-01 23:12:25,917] Trial 18 finished with value: 0.5943517329910142 and parameters: {'max_depth': 5, 'learning_rate': 0.2899853535653739, 'n_estimators': 1259, 'subsample': 0.6405495051025173, 'colsample_bytree': 0.823976377403456, 'min_child_weight': 8, 'gamma': 1.7460481483571821, 'reg_alpha': 4.255130112729531e-07, 'reg_lambda': 0.021407382103515595, 'max_delta_step': 5}. Best is trial 6 with value: 0.6469833119383825.

Best trial: 6. Best value: 0.646983:  44%|████▍     | 22/50 [03:53<03:24,  7.29s/it]

[I 2025-12-01 23:12:30,399] Trial 23 pruned.

Best trial: 6. Best value: 0.646983:  46%|████▌     | 23/50 [04:21<06:05, 13.55s/it]

[I 2025-12-01 23:12:58,544] Trial 22 finished with value: 0.5905006418485237 and parameters: {'max_depth': 7, 'learning_rate': 0.15691844919846928, 'n_estimators': 1128, 'subsample': 0.9136170354069325, 'colsample_bytree': 0.7835137335889198, 'min_child_weight': 7, 'gamma': 2.6985989205422074, 'reg_alpha': 0.00019071856362326198, 'reg_lambda': 2.300721834470103e-08, 'max_delta_step': 4}. Best is trial 6 with value: 0.6469833119383825.

Best trial: 6. Best value: 0.646983:  48%|████▊     | 24/50 [04:31<05:22, 12.42s/it]

[I 2025-12-01 23:13:08,323] Trial 21 finished with value: 0.6065468549422337 and parameters: {'max_depth': 7, 'learning_rate': 0.01828103735562689, 'n_estimators': 1348, 'subsample': 0.6534171911384202, 'colsample_bytree': 0.7850881430526482, 'min_child_weight': 7, 'gamma': 2.4834219107152573, 'reg_alpha': 1.7120315860895572e-07, 'reg_lambda': 0.2875756235273303, 'max_delta_step': 2}. Best is trial 6 with value: 0.6469833119383825.

Best trial: 6. Best value: 0.646983:  50%|█████     | 25/50 [04:34<03:59,  9.57s/it]

[I 2025-12-01 23:13:11,241] Trial 24 finished with value: 0.5924261874197689 and parameters: {'max_depth': 8, 'learning_rate': 0.18732403937196873, 'n_estimators': 1044, 'subsample': 0.7917928811647974, 'colsample_bytree': 0.6578259687305809, 'min_child_weight': 7, 'gamma': 2.6543941629407986, 'reg_alpha': 0.0003366002218406771, 'reg_lambda': 0.0008061193988483236, 'max_delta_step': 8}. Best is trial 6 with value: 0.6469833119383825.

Best trial: 25. Best value: 0.697689:  52%|█████▏    | 26/50 [04:35<02:45,  6.89s/it]

[I 2025-12-01 23:13:11,886] Trial 25 finished with value: 0.6976893453145058 and parameters: {'max_depth': 8, 'learning_rate': 0.16596776161466498, 'n_estimators': 969, 'subsample': 0.7943773828693508, 'colsample_bytree': 0.6592086388637949, 'min_child_weight': 9, 'gamma': 2.225869436420453, 'reg_alpha': 0.001146019967066057, 'reg_lambda': 0.0007357230153259542, 'max_delta_step': 8}. Best is trial 25 with value: 0.6976893453145058.

Best trial: 25. Best value: 0.697689:  54%|█████▍    | 27/50 [04:41<02:36,  6.80s/it]

[I 2025-12-01 23:13:18,475] Trial 29 pruned.

Best trial: 25. Best value: 0.697689:  56%|█████▌    | 28/50 [04:47<02:24,  6.58s/it]

[I 2025-12-01 23:13:24,536] Trial 30 pruned.

Best trial: 25. Best value: 0.697689:  58%|█████▊    | 29/50 [05:03<03:15,  9.31s/it]

[I 2025-12-01 23:13:40,207] Trial 26 finished with value: 0.6489088575096278 and parameters: {'max_depth': 9, 'learning_rate': 0.16021521210802725, 'n_estimators': 980, 'subsample': 0.7808723326054499, 'colsample_bytree': 0.6666747584016259, 'min_child_weight': 9, 'gamma': 1.2991750598419434, 'reg_alpha': 0.002416755054308846, 'reg_lambda': 0.0008033369023661645, 'max_delta_step': 8}. Best is trial 25 with value: 0.6976893453145058.

Best trial: 25. Best value: 0.697689:  60%|██████    | 30/50 [05:11<02:59,  8.98s/it]

[I 2025-12-01 23:13:48,428] Trial 27 finished with value: 0.6206675224646983 and parameters: {'max_depth': 9, 'learning_rate': 0.20000434971725015, 'n_estimators': 949, 'subsample': 0.7851746161290449, 'colsample_bytree': 0.6657875468365863, 'min_child_weight': 9, 'gamma': 1.2022302986816427, 'reg_alpha': 0.00487191884837294, 'reg_lambda': 0.0008642606831027872, 'max_delta_step': 8}. Best is trial 25 with value: 0.6976893453145058.

Best trial: 25. Best value: 0.697689:  62%|██████▏   | 31/50 [05:14<02:16,  7.19s/it]

[I 2025-12-01 23:13:51,443] Trial 33 pruned.

Best trial: 25. Best value: 0.697689:  64%|██████▍   | 32/50 [05:14<01:32,  5.13s/it]

[I 2025-12-01 23:13:51,767] Trial 28 finished with value: 0.6084724005134787 and parameters: {'max_depth': 9, 'learning_rate': 0.13994507585993185, 'n_estimators': 938, 'subsample': 0.7895180839028033, 'colsample_bytree': 0.6501234103180273, 'min_child_weight': 9, 'gamma': 1.3031126153243509, 'reg_alpha': 0.0021194538197412778, 'reg_lambda': 0.0013487972301441495, 'max_delta_step': 7}. Best is trial 25 with value: 0.6976893453145058.

Best trial: 25. Best value: 0.697689:  66%|██████▌   | 33/50 [05:37<02:55, 10.35s/it]

[I 2025-12-01 23:14:14,279] Trial 32 finished with value: 0.6206675224646983 and parameters: {'max_depth': 9, 'learning_rate': 0.10697951102347127, 'n_estimators': 774, 'subsample': 0.8735068402972931, 'colsample_bytree': 0.6028633108001733, 'min_child_weight': 9, 'gamma': 0.6434499353355998, 'reg_alpha': 0.0012180382127943282, 'reg_lambda': 0.8216279756798446, 'max_delta_step': 9}. Best is trial 25 with value: 0.6976893453145058.

Best trial: 25. Best value: 0.697689:  68%|██████▊   | 34/50 [05:48<02:46, 10.43s/it]

[I 2025-12-01 23:14:24,902] Trial 36 pruned.

Best trial: 25. Best value: 0.697689:  70%|███████   | 35/50 [05:48<01:51,  7.44s/it]

[I 2025-12-01 23:14:25,374] Trial 31 finished with value: 0.6591784338896021 and parameters: {'max_depth': 9, 'learning_rate': 0.12216029695033521, 'n_estimators': 1389, 'subsample': 0.9432390498914233, 'colsample_bytree': 0.7743367486167456, 'min_child_weight': 9, 'gamma': 0.7257178911496212, 'reg_alpha': 3.8531543440312296e-05, 'reg_lambda': 1.78338467412351, 'max_delta_step': 7}. Best is trial 25 with value: 0.6976893453145058.

Best trial: 25. Best value: 0.697689:  72%|███████▏  | 36/50 [05:56<01:47,  7.68s/it]

[I 2025-12-01 23:14:33,624] Trial 37 pruned.

Best trial: 25. Best value: 0.697689:  74%|███████▍  | 37/50 [05:58<01:17,  5.96s/it]

[I 2025-12-01 23:14:35,576] Trial 38 pruned.

Best trial: 25. Best value: 0.697689:  76%|███████▌  | 38/50 [06:07<01:20,  6.74s/it]

[I 2025-12-01 23:14:44,132] Trial 39 pruned.

Best trial: 25. Best value: 0.697689:  78%|███████▊  | 39/50 [06:12<01:07,  6.16s/it]

[I 2025-12-01 23:14:48,948] Trial 35 finished with value: 0.6713735558408216 and parameters: {'max_depth': 8, 'learning_rate': 0.12741521767527328, 'n_estimators': 1366, 'subsample': 0.8802726861124722, 'colsample_bytree': 0.6077707923653557, 'min_child_weight': 9, 'gamma': 2.223163058122549, 'reg_alpha': 1.4022528646114576e-06, 'reg_lambda': 0.026611893407156646, 'max_delta_step': 9}. Best is trial 25 with value: 0.6976893453145058.

Best trial: 25. Best value: 0.697689:  80%|████████  | 40/50 [06:13<00:47,  4.79s/it]

[I 2025-12-01 23:14:50,539] Trial 34 finished with value: 0.6976893453145058 and parameters: {'max_depth': 8, 'learning_rate': 0.15935941196537354, 'n_estimators': 1412, 'subsample': 0.8176264746084144, 'colsample_bytree': 0.6131107649553097, 'min_child_weight': 9, 'gamma': 0.6275810004856466, 'reg_alpha': 3.8022412900530996e-05, 'reg_lambda': 0.002729730132163594, 'max_delta_step': 7}. Best is trial 25 with value: 0.6976893453145058.

Best trial: 25. Best value: 0.697689:  82%|████████▏ | 41/50 [06:16<00:36,  4.10s/it]

[I 2025-12-01 23:14:53,022] Trial 41 pruned.

Best trial: 25. Best value: 0.697689:  84%|████████▍ | 42/50 [06:18<00:28,  3.62s/it]

[I 2025-12-01 23:14:55,532] Trial 42 pruned.

Best trial: 25. Best value: 0.697689:  86%|████████▌ | 43/50 [06:22<00:26,  3.78s/it]

[I 2025-12-01 23:14:59,678] Trial 43 pruned.

Best trial: 25. Best value: 0.697689:  88%|████████▊ | 44/50 [06:59<01:21, 13.63s/it]

[I 2025-12-01 23:15:36,301] Trial 40 finished with value: 0.6450577663671373 and parameters: {'max_depth': 8, 'learning_rate': 0.07623371271880429, 'n_estimators': 1421, 'subsample': 0.8211998732229976, 'colsample_bytree': 0.5466316411129852, 'min_child_weight': 9, 'gamma': 0.04272371305791001, 'reg_alpha': 0.06401927254828389, 'reg_lambda': 6.803787201569881, 'max_delta_step': 9}. Best is trial 25 with value: 0.6976893453145058.

Best trial: 25. Best value: 0.697689:  90%|█████████ | 45/50 [07:07<00:59, 11.95s/it]

[I 2025-12-01 23:15:44,335] Trial 44 finished with value: 0.6732991014120667 and parameters: {'max_depth': 8, 'learning_rate': 0.16662820700519354, 'n_estimators': 1242, 'subsample': 0.8841855073284828, 'colsample_bytree': 0.5414896942024935, 'min_child_weight': 9, 'gamma': 0.482373368543658, 'reg_alpha': 4.536618413509343e-05, 'reg_lambda': 0.01620194342088153, 'max_delta_step': 8}. Best is trial 25 with value: 0.6976893453145058.

Best trial: 25. Best value: 0.697689:  92%|█████████▏| 46/50 [07:10<00:36,  9.19s/it]

[I 2025-12-01 23:15:47,080] Trial 45 finished with value: 0.6732991014120667 and parameters: {'max_depth': 7, 'learning_rate': 0.11644481473021144, 'n_estimators': 1226, 'subsample': 0.8793779088746227, 'colsample_bytree': 0.5483755145137035, 'min_child_weight': 9, 'gamma': 0.40424665819800265, 'reg_alpha': 7.23247017243369e-05, 'reg_lambda': 0.01979920376291281, 'max_delta_step': 8}. Best is trial 25 with value: 0.6976893453145058.

Best trial: 25. Best value: 0.697689:  94%|█████████▍| 47/50 [07:18<00:27,  9.04s/it]

[I 2025-12-01 23:15:55,772] Trial 46 finished with value: 0.6084724005134787 and parameters: {'max_depth': 7, 'learning_rate': 0.11895458111055855, 'n_estimators': 1307, 'subsample': 0.7568149313728262, 'colsample_bytree': 0.6881714212360912, 'min_child_weight': 9, 'gamma': 0.4187253707123593, 'reg_alpha': 6.156509233424768e-06, 'reg_lambda': 0.020078171347845283, 'max_delta_step': 8}. Best is trial 25 with value: 0.6976893453145058.
[I 2025-12-01 23:15:55,840] Trial 49 pruned.

Best trial: 25. Best value: 0.697689:  98%|█████████▊| 49/50 [07:46<00:11, 11.25s/it]

[I 2025-12-01 23:16:23,427] Trial 47 finished with value: 0.6854942233632862 and parameters: {'max_depth': 7, 'learning_rate': 0.11872240350325203, 'n_estimators': 1230, 'subsample': 0.7661714745859057, 'colsample_bytree': 0.634751428065626, 'min_child_weight': 8, 'gamma': 0.4757788854762246, 'reg_alpha': 6.157610726866161e-06, 'reg_lambda': 1.0706356213028931e-05, 'max_delta_step': 8}. Best is trial 25 with value: 0.6976893453145058.

Best trial: 25. Best value: 0.697689: 100%|██████████| 50/50 [07:51<00:00,  9.43s/it]

[I 2025-12-01 23:16:28,317] Trial 48 finished with value: 0.6591784338896021 and parameters: {'max_depth': 7, 'learning_rate': 0.12290314724637715, 'n_estimators': 1242, 'subsample': 0.8948798413528684, 'colsample_bytree': 0.5078428580351243, 'min_child_weight': 8, 'gamma': 0.36291882428908434, 'reg_alpha': 1.2676138466089587e-05, 'reg_lambda': 0.018681578631231953, 'max_delta_step': 7}. Best is trial 25 with value: 0.6976893453145058.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 23:16:31,890] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.532895:   2%|▏         | 1/50 [00:38<31:03, 38.02s/it]

[I 2025-12-01 23:17:09,900] Trial 1 finished with value: 0.5328947368421053 and parameters: {'max_depth': 9, 'learning_rate': 0.12274184070952937, 'n_estimators': 891, 'subsample': 0.566879175679441, 'colsample_bytree': 0.5720011569273177, 'min_child_weight': 6, 'gamma': 0.9891029452400613, 'reg_alpha': 1.568192637573632e-07, 'reg_lambda': 0.017107288960544465, 'max_delta_step': 0}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 1. Best value: 0.532895:   4%|▍         | 2/50 [00:38<12:50, 16.04s/it]

[I 2025-12-01 23:17:10,560] Trial 0 finished with value: 0.4967105263157895 and parameters: {'max_depth': 4, 'learning_rate': 0.16859626578517464, 'n_estimators': 889, 'subsample': 0.7930483548081373, 'colsample_bytree': 0.8272779735603222, 'min_child_weight': 8, 'gamma': 2.16766796724765, 'reg_alpha': 2.9110541587976173e-08, 'reg_lambda': 0.000169128740318991, 'max_delta_step': 10}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 1. Best value: 0.532895:   6%|▌         | 3/50 [00:53<12:08, 15.51s/it]

[I 2025-12-01 23:17:25,431] Trial 3 finished with value: 0.444078947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.18020459773546096, 'n_estimators': 1163, 'subsample': 0.6449423336753832, 'colsample_bytree': 0.8565695069152446, 'min_child_weight': 4, 'gamma': 2.86664377603223, 'reg_alpha': 0.08111710795097954, 'reg_lambda': 2.3024493171894495e-05, 'max_delta_step': 4}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 1. Best value: 0.532895:   8%|▊         | 4/50 [01:12<12:52, 16.79s/it]

[I 2025-12-01 23:17:44,190] Trial 2 finished with value: 0.4565789473684211 and parameters: {'max_depth': 5, 'learning_rate': 0.01927620693908688, 'n_estimators': 1163, 'subsample': 0.5262013764765656, 'colsample_bytree': 0.9183145463076866, 'min_child_weight': 4, 'gamma': 1.4830831788287357, 'reg_alpha': 1.0256999093882304e-07, 'reg_lambda': 0.0033361615334763597, 'max_delta_step': 9}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 1. Best value: 0.532895:  10%|█         | 5/50 [01:31<13:13, 17.63s/it]

[I 2025-12-01 23:18:03,298] Trial 4 finished with value: 0.4552631578947368 and parameters: {'max_depth': 5, 'learning_rate': 0.012853291370186745, 'n_estimators': 490, 'subsample': 0.8298494645447099, 'colsample_bytree': 0.9202219197730389, 'min_child_weight': 5, 'gamma': 2.508026109794877, 'reg_alpha': 0.0002781549983464263, 'reg_lambda': 2.6078347303877964e-07, 'max_delta_step': 0}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 1. Best value: 0.532895:  12%|█▏        | 6/50 [01:32<08:52, 12.10s/it]

[I 2025-12-01 23:18:04,681] Trial 5 finished with value: 0.05 and parameters: {'max_depth': 8, 'learning_rate': 0.23685016299948702, 'n_estimators': 1218, 'subsample': 0.9694806050291929, 'colsample_bytree': 0.880954916562662, 'min_child_weight': 10, 'gamma': 3.977160942624943, 'reg_alpha': 3.5998565486093406, 'reg_lambda': 3.499834807404601e-05, 'max_delta_step': 4}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 1. Best value: 0.532895:  14%|█▍        | 7/50 [01:54<10:52, 15.18s/it]

[I 2025-12-01 23:18:26,187] Trial 6 finished with value: 0.4677631578947368 and parameters: {'max_depth': 7, 'learning_rate': 0.025294945455992868, 'n_estimators': 1295, 'subsample': 0.584658176400872, 'colsample_bytree': 0.8930846798430407, 'min_child_weight': 7, 'gamma': 0.35036147463080813, 'reg_alpha': 2.578218449989811e-07, 'reg_lambda': 9.541942810355416e-08, 'max_delta_step': 6}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 1. Best value: 0.532895:  16%|█▌        | 8/50 [01:58<08:06, 11.59s/it]

[I 2025-12-01 23:18:30,101] Trial 7 finished with value: 0.5092105263157894 and parameters: {'max_depth': 9, 'learning_rate': 0.14904174618083355, 'n_estimators': 800, 'subsample': 0.7695120597000211, 'colsample_bytree': 0.745598580709206, 'min_child_weight': 4, 'gamma': 4.666659299880451, 'reg_alpha': 0.27893475598267836, 'reg_lambda': 1.2916123347683818e-08, 'max_delta_step': 0}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 1. Best value: 0.532895:  18%|█▊        | 9/50 [02:09<07:47, 11.41s/it]

[I 2025-12-01 23:18:41,118] Trial 9 finished with value: 0.4565789473684211 and parameters: {'max_depth': 9, 'learning_rate': 0.08008787717044225, 'n_estimators': 501, 'subsample': 0.7811701362430742, 'colsample_bytree': 0.7206339094801191, 'min_child_weight': 2, 'gamma': 1.5442043101706742, 'reg_alpha': 2.025426781601006e-08, 'reg_lambda': 1.1858396401011192e-05, 'max_delta_step': 5}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 1. Best value: 0.532895:  20%|██        | 10/50 [02:19<07:25, 11.14s/it]

[I 2025-12-01 23:18:51,642] Trial 11 finished with value: 0.25 and parameters: {'max_depth': 9, 'learning_rate': 0.03426258960786483, 'n_estimators': 294, 'subsample': 0.6103755498243318, 'colsample_bytree': 0.9390016420503902, 'min_child_weight': 4, 'gamma': 3.7277370766673195, 'reg_alpha': 8.369654015890022, 'reg_lambda': 4.305800843878734e-05, 'max_delta_step': 5}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 1. Best value: 0.532895:  22%|██▏       | 11/50 [02:21<05:26,  8.37s/it]

[I 2025-12-01 23:18:53,749] Trial 8 pruned.

Best trial: 1. Best value: 0.532895:  24%|██▍       | 12/50 [02:31<05:32,  8.74s/it]

[I 2025-12-01 23:19:03,325] Trial 10 finished with value: 0.46907894736842104 and parameters: {'max_depth': 8, 'learning_rate': 0.21142859181429743, 'n_estimators': 802, 'subsample': 0.9450297815182402, 'colsample_bytree': 0.5397414393100404, 'min_child_weight': 6, 'gamma': 4.0326723064313335, 'reg_alpha': 0.0014463773289882572, 'reg_lambda': 0.002444308249672165, 'max_delta_step': 1}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 1. Best value: 0.532895:  26%|██▌       | 13/50 [03:04<09:58, 16.19s/it]

[I 2025-12-01 23:19:36,644] Trial 12 finished with value: 0.5078947368421052 and parameters: {'max_depth': 10, 'learning_rate': 0.012074976959374031, 'n_estimators': 1058, 'subsample': 0.8352197015387586, 'colsample_bytree': 0.6701062555549897, 'min_child_weight': 8, 'gamma': 1.5165907427173035, 'reg_alpha': 0.10494921570619786, 'reg_lambda': 1.0531830358507983e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 1. Best value: 0.532895:  28%|██▊       | 14/50 [03:19<09:23, 15.67s/it]

[I 2025-12-01 23:19:51,105] Trial 14 finished with value: 0.444078947368421 and parameters: {'max_depth': 10, 'learning_rate': 0.08648212981109539, 'n_estimators': 856, 'subsample': 0.689261953967806, 'colsample_bytree': 0.5584318288912062, 'min_child_weight': 2, 'gamma': 4.8863253090492424, 'reg_alpha': 4.84719976143399e-05, 'reg_lambda': 0.8914984256237929, 'max_delta_step': 0}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 1. Best value: 0.532895:  30%|███       | 15/50 [03:24<07:21, 12.63s/it]

[I 2025-12-01 23:19:56,687] Trial 15 finished with value: 0.5078947368421052 and parameters: {'max_depth': 10, 'learning_rate': 0.0828728733080574, 'n_estimators': 859, 'subsample': 0.6931303663268316, 'colsample_bytree': 0.593239160107954, 'min_child_weight': 2, 'gamma': 0.18248193826487147, 'reg_alpha': 1.165333099978438e-05, 'reg_lambda': 1.1567868026317458, 'max_delta_step': 2}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 1. Best value: 0.532895:  32%|███▏      | 16/50 [03:29<05:50, 10.32s/it]

[I 2025-12-01 23:20:01,662] Trial 18 pruned.

Best trial: 1. Best value: 0.532895:  34%|███▍      | 17/50 [03:41<05:55, 10.78s/it]

[I 2025-12-01 23:20:13,504] Trial 19 pruned.

Best trial: 1. Best value: 0.532895:  36%|███▌      | 18/50 [03:46<04:44,  8.88s/it]

[I 2025-12-01 23:20:17,966] Trial 13 finished with value: 0.46907894736842104 and parameters: {'max_depth': 10, 'learning_rate': 0.0722028210488362, 'n_estimators': 913, 'subsample': 0.6745674644058635, 'colsample_bytree': 0.5298402122071857, 'min_child_weight': 1, 'gamma': 0.20933679947363004, 'reg_alpha': 2.5111272481831783e-05, 'reg_lambda': 4.78583556305975, 'max_delta_step': 2}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 1. Best value: 0.532895:  38%|███▊      | 19/50 [04:03<05:53, 11.41s/it]

[I 2025-12-01 23:20:35,283] Trial 16 finished with value: 0.44539473684210523 and parameters: {'max_depth': 10, 'learning_rate': 0.08912063711046353, 'n_estimators': 743, 'subsample': 0.6984935649088548, 'colsample_bytree': 0.5664934912466547, 'min_child_weight': 1, 'gamma': 4.938237837335475, 'reg_alpha': 2.5425145299494917e-05, 'reg_lambda': 1.0614802227029065, 'max_delta_step': 2}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 1. Best value: 0.532895:  40%|████      | 20/50 [04:04<04:08,  8.29s/it]

[I 2025-12-01 23:20:36,300] Trial 17 finished with value: 0.444078947368421 and parameters: {'max_depth': 9, 'learning_rate': 0.10703143751175663, 'n_estimators': 640, 'subsample': 0.704344238336688, 'colsample_bytree': 0.6157494295935569, 'min_child_weight': 1, 'gamma': 0.020432002921262793, 'reg_alpha': 3.3773541620847313e-06, 'reg_lambda': 1.0594166907680804e-08, 'max_delta_step': 2}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 1. Best value: 0.532895:  42%|████▏     | 21/50 [04:20<05:05, 10.52s/it]

[I 2025-12-01 23:20:52,015] Trial 20 finished with value: 0.481578947368421 and parameters: {'max_depth': 9, 'learning_rate': 0.05072339309468237, 'n_estimators': 628, 'subsample': 0.7321279484031524, 'colsample_bytree': 0.7932740838707408, 'min_child_weight': 5, 'gamma': 3.3186982987793003, 'reg_alpha': 0.6044788937774406, 'reg_lambda': 0.025712039636979545, 'max_delta_step': 3}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 1. Best value: 0.532895:  44%|████▍     | 22/50 [04:23<03:57,  8.47s/it]

[I 2025-12-01 23:20:55,718] Trial 21 finished with value: 0.481578947368421 and parameters: {'max_depth': 9, 'learning_rate': 0.04475521027723945, 'n_estimators': 628, 'subsample': 0.7285490462116976, 'colsample_bytree': 0.6788535974143979, 'min_child_weight': 5, 'gamma': 3.1772528544528376, 'reg_alpha': 0.4389948790013761, 'reg_lambda': 0.01141120764015874, 'max_delta_step': 7}. Best is trial 1 with value: 0.5328947368421053.

Best trial: 24. Best value: 0.548026:  46%|████▌     | 23/50 [05:08<08:39, 19.23s/it]

[I 2025-12-01 23:21:40,033] Trial 24 finished with value: 0.5480263157894737 and parameters: {'max_depth': 8, 'learning_rate': 0.04930553483731898, 'n_estimators': 1042, 'subsample': 0.8620993237667104, 'colsample_bytree': 0.6902596519422414, 'min_child_weight': 8, 'gamma': 1.3814399531150046, 'reg_alpha': 0.16383390425357838, 'reg_lambda': 8.721824613895763e-07, 'max_delta_step': 0}. Best is trial 24 with value: 0.5480263157894737.

Best trial: 24. Best value: 0.548026:  48%|████▊     | 24/50 [05:09<05:58, 13.80s/it]

[I 2025-12-01 23:21:41,167] Trial 25 finished with value: 0.5092105263157894 and parameters: {'max_depth': 8, 'learning_rate': 0.12914862552634662, 'n_estimators': 1029, 'subsample': 0.8680314645554416, 'colsample_bytree': 0.7006340581685726, 'min_child_weight': 8, 'gamma': 1.4079863620864694, 'reg_alpha': 0.007543605158361918, 'reg_lambda': 3.836578544945736e-07, 'max_delta_step': 0}. Best is trial 24 with value: 0.5480263157894737.

Best trial: 24. Best value: 0.548026:  50%|█████     | 25/50 [05:18<05:10, 12.40s/it]

[I 2025-12-01 23:21:50,313] Trial 22 finished with value: 0.481578947368421 and parameters: {'max_depth': 9, 'learning_rate': 0.04857775162081407, 'n_estimators': 1490, 'subsample': 0.7432959053072175, 'colsample_bytree': 0.7825742323703992, 'min_child_weight': 5, 'gamma': 3.056141129194228, 'reg_alpha': 0.33543666749321654, 'reg_lambda': 0.022992406099671108, 'max_delta_step': 3}. Best is trial 24 with value: 0.5480263157894737.

Best trial: 24. Best value: 0.548026:  52%|█████▏    | 26/50 [05:27<04:30, 11.28s/it]

[I 2025-12-01 23:21:58,979] Trial 23 finished with value: 0.4552631578947368 and parameters: {'max_depth': 6, 'learning_rate': 0.05112885145736519, 'n_estimators': 1471, 'subsample': 0.8898302598504672, 'colsample_bytree': 0.8063986233267111, 'min_child_weight': 5, 'gamma': 3.394184608206965, 'reg_alpha': 0.6843957715586961, 'reg_lambda': 0.013577570478647319, 'max_delta_step': 7}. Best is trial 24 with value: 0.5480263157894737.

Best trial: 24. Best value: 0.548026:  54%|█████▍    | 27/50 [06:03<07:14, 18.88s/it]

[I 2025-12-01 23:22:35,582] Trial 28 finished with value: 0.5105263157894737 and parameters: {'max_depth': 7, 'learning_rate': 0.0363996140963539, 'n_estimators': 1026, 'subsample': 0.9157442865737673, 'colsample_bytree': 0.6531040129781106, 'min_child_weight': 9, 'gamma': 0.8975593403719059, 'reg_alpha': 0.022199290081308148, 'reg_lambda': 0.0005063255562471733, 'max_delta_step': 1}. Best is trial 24 with value: 0.5480263157894737.

Best trial: 24. Best value: 0.548026:  56%|█████▌    | 28/50 [06:09<05:30, 15.03s/it]

[I 2025-12-01 23:22:41,618] Trial 29 finished with value: 0.5105263157894737 and parameters: {'max_depth': 7, 'learning_rate': 0.0336460542246959, 'n_estimators': 978, 'subsample': 0.934047970058475, 'colsample_bytree': 0.6509553284544319, 'min_child_weight': 9, 'gamma': 0.7866979352937971, 'reg_alpha': 0.010978011408488631, 'reg_lambda': 5.023514731254589e-08, 'max_delta_step': 1}. Best is trial 24 with value: 0.5480263157894737.

Best trial: 24. Best value: 0.548026:  58%|█████▊    | 29/50 [06:14<04:09, 11.88s/it]

[I 2025-12-01 23:22:46,156] Trial 26 finished with value: 0.5217105263157895 and parameters: {'max_depth': 8, 'learning_rate': 0.12143531412883529, 'n_estimators': 1449, 'subsample': 0.8914833362632646, 'colsample_bytree': 0.9966606258810162, 'min_child_weight': 8, 'gamma': 0.8612467773569419, 'reg_alpha': 0.005776514736966105, 'reg_lambda': 1.7629471747530845e-07, 'max_delta_step': 1}. Best is trial 24 with value: 0.5480263157894737.

Best trial: 24. Best value: 0.548026:  60%|██████    | 30/50 [06:20<03:23, 10.17s/it]

[I 2025-12-01 23:22:52,329] Trial 27 finished with value: 0.49407894736842106 and parameters: {'max_depth': 7, 'learning_rate': 0.057591416139992316, 'n_estimators': 1471, 'subsample': 0.9260738374959255, 'colsample_bytree': 0.9909504376274664, 'min_child_weight': 7, 'gamma': 0.7735690467999542, 'reg_alpha': 0.015326357273237445, 'reg_lambda': 5.5581746762872355e-08, 'max_delta_step': 1}. Best is trial 24 with value: 0.5480263157894737.

Best trial: 24. Best value: 0.548026:  62%|██████▏   | 31/50 [06:48<04:53, 15.45s/it]

[I 2025-12-01 23:23:20,102] Trial 30 finished with value: 0.5105263157894737 and parameters: {'max_depth': 7, 'learning_rate': 0.029477179146669426, 'n_estimators': 971, 'subsample': 0.9414094276092735, 'colsample_bytree': 0.6456787493948132, 'min_child_weight': 9, 'gamma': 0.7365872430417792, 'reg_alpha': 0.013956887371716823, 'reg_lambda': 0.000567228619459373, 'max_delta_step': 1}. Best is trial 24 with value: 0.5480263157894737.

Best trial: 31. Best value: 0.589474:  64%|██████▍   | 32/50 [07:00<04:19, 14.43s/it]

[I 2025-12-01 23:23:32,170] Trial 31 finished with value: 0.5894736842105264 and parameters: {'max_depth': 6, 'learning_rate': 0.06543473047684928, 'n_estimators': 1098, 'subsample': 0.9733579245320952, 'colsample_bytree': 0.9758626794811773, 'min_child_weight': 9, 'gamma': 0.9110335186396903, 'reg_alpha': 0.0009149134233879511, 'reg_lambda': 0.0006033950031600481, 'max_delta_step': 1}. Best is trial 31 with value: 0.5894736842105264.

Best trial: 31. Best value: 0.589474:  66%|██████▌   | 33/50 [07:14<04:02, 14.29s/it]

[I 2025-12-01 23:23:46,116] Trial 32 finished with value: 0.481578947368421 and parameters: {'max_depth': 8, 'learning_rate': 0.10943380271316697, 'n_estimators': 1277, 'subsample': 0.9945054439190242, 'colsample_bytree': 0.9816304002723771, 'min_child_weight': 7, 'gamma': 1.840460901521096, 'reg_alpha': 0.0003044699988417547, 'reg_lambda': 2.1488272963320123e-06, 'max_delta_step': 1}. Best is trial 31 with value: 0.5894736842105264.

Best trial: 31. Best value: 0.589474:  68%|██████▊   | 34/50 [07:26<03:40, 13.78s/it]

[I 2025-12-01 23:23:58,701] Trial 33 finished with value: 0.481578947368421 and parameters: {'max_depth': 8, 'learning_rate': 0.06746087425204829, 'n_estimators': 1362, 'subsample': 0.9994814474437216, 'colsample_bytree': 0.9794280824186963, 'min_child_weight': 7, 'gamma': 1.2321007280019494, 'reg_alpha': 0.0014145494388073951, 'reg_lambda': 0.00023516778342381488, 'max_delta_step': 10}. Best is trial 31 with value: 0.5894736842105264.

Best trial: 31. Best value: 0.589474:  70%|███████   | 35/50 [07:36<03:09, 12.63s/it]

[I 2025-12-01 23:24:08,644] Trial 34 finished with value: 0.5631578947368421 and parameters: {'max_depth': 8, 'learning_rate': 0.06599937267655506, 'n_estimators': 1108, 'subsample': 0.9981852469354527, 'colsample_bytree': 0.58810802414411, 'min_child_weight': 9, 'gamma': 1.0818073859035866, 'reg_alpha': 0.0012968534296290467, 'reg_lambda': 0.00024109889761562107, 'max_delta_step': 1}. Best is trial 31 with value: 0.5894736842105264.

Best trial: 31. Best value: 0.589474:  72%|███████▏  | 36/50 [07:44<02:37, 11.23s/it]

[I 2025-12-01 23:24:16,608] Trial 38 pruned.

Best trial: 31. Best value: 0.589474:  74%|███████▍  | 37/50 [07:56<02:28, 11.39s/it]

[I 2025-12-01 23:24:28,367] Trial 35 finished with value: 0.481578947368421 and parameters: {'max_depth': 5, 'learning_rate': 0.06459147098745383, 'n_estimators': 1121, 'subsample': 0.8595524621978884, 'colsample_bytree': 0.9939790460899782, 'min_child_weight': 7, 'gamma': 1.1998946480248598, 'reg_alpha': 0.0007803452454341514, 'reg_lambda': 0.00013047378225082253, 'max_delta_step': 10}. Best is trial 31 with value: 0.5894736842105264.

Best trial: 31. Best value: 0.589474:  76%|███████▌  | 38/50 [08:06<02:13, 11.12s/it]

[I 2025-12-01 23:24:38,859] Trial 36 finished with value: 0.5217105263157895 and parameters: {'max_depth': 5, 'learning_rate': 0.06262391526710273, 'n_estimators': 1123, 'subsample': 0.8656622953514016, 'colsample_bytree': 0.9556250748156159, 'min_child_weight': 8, 'gamma': 1.1670072289359708, 'reg_alpha': 0.0016889283405068349, 'reg_lambda': 0.003618433070513408, 'max_delta_step': 10}. Best is trial 31 with value: 0.5894736842105264.

Best trial: 31. Best value: 0.589474:  78%|███████▊  | 39/50 [08:18<02:03, 11.26s/it]

[I 2025-12-01 23:24:50,448] Trial 37 finished with value: 0.5092105263157894 and parameters: {'max_depth': 5, 'learning_rate': 0.15277890631490437, 'n_estimators': 1160, 'subsample': 0.8654075525749407, 'colsample_bytree': 0.9526979065388631, 'min_child_weight': 8, 'gamma': 1.9551775676440617, 'reg_alpha': 0.0016460908334286128, 'reg_lambda': 0.0017363025172012743, 'max_delta_step': 3}. Best is trial 31 with value: 0.5894736842105264.

Best trial: 39. Best value: 0.629605:  80%|████████  | 40/50 [08:37<02:14, 13.47s/it]

[I 2025-12-01 23:25:09,088] Trial 39 finished with value: 0.6296052631578948 and parameters: {'max_depth': 4, 'learning_rate': 0.041257931511362596, 'n_estimators': 1183, 'subsample': 0.9698204191344687, 'colsample_bytree': 0.8343260944928933, 'min_child_weight': 9, 'gamma': 0.5332650124728222, 'reg_alpha': 7.952010777695544e-07, 'reg_lambda': 0.0783423562631583, 'max_delta_step': 0}. Best is trial 39 with value: 0.6296052631578948.

Best trial: 39. Best value: 0.629605:  82%|████████▏ | 41/50 [08:50<02:00, 13.41s/it]

[I 2025-12-01 23:25:22,340] Trial 40 finished with value: 0.6157894736842104 and parameters: {'max_depth': 6, 'learning_rate': 0.01651824915519893, 'n_estimators': 1161, 'subsample': 0.9657387585487657, 'colsample_bytree': 0.8307908513080061, 'min_child_weight': 9, 'gamma': 0.47665196697277046, 'reg_alpha': 0.00010166376238229577, 'reg_lambda': 0.0010089618486755789, 'max_delta_step': 4}. Best is trial 39 with value: 0.6296052631578948.

Best trial: 39. Best value: 0.629605:  84%|████████▍ | 42/50 [08:58<01:33, 11.71s/it]

[I 2025-12-01 23:25:30,098] Trial 41 finished with value: 0.6019736842105263 and parameters: {'max_depth': 3, 'learning_rate': 0.17083115849385477, 'n_estimators': 1199, 'subsample': 0.9676836069373487, 'colsample_bytree': 0.8390084370112951, 'min_child_weight': 9, 'gamma': 0.4300443981393156, 'reg_alpha': 8.328593168816637e-07, 'reg_lambda': 0.11765289932258717, 'max_delta_step': 4}. Best is trial 39 with value: 0.6296052631578948.

Best trial: 39. Best value: 0.629605:  86%|████████▌ | 43/50 [09:11<01:24, 12.12s/it]

[I 2025-12-01 23:25:43,162] Trial 42 finished with value: 0.49802631578947365 and parameters: {'max_depth': 3, 'learning_rate': 0.19199211194737476, 'n_estimators': 1225, 'subsample': 0.9713468060442421, 'colsample_bytree': 0.8331134955783355, 'min_child_weight': 9, 'gamma': 0.4728736073183283, 'reg_alpha': 7.611549661607236e-07, 'reg_lambda': 0.15109470673608946, 'max_delta_step': 4}. Best is trial 39 with value: 0.6296052631578948.

Best trial: 39. Best value: 0.629605:  88%|████████▊ | 44/50 [09:20<01:07, 11.19s/it]

[I 2025-12-01 23:25:52,193] Trial 46 pruned.

Best trial: 39. Best value: 0.629605:  90%|█████████ | 45/50 [09:39<01:07, 13.48s/it]

[I 2025-12-01 23:26:11,009] Trial 43 finished with value: 0.5769736842105263 and parameters: {'max_depth': 3, 'learning_rate': 0.015096413361301329, 'n_estimators': 1236, 'subsample': 0.9709513406717734, 'colsample_bytree': 0.8407462716461466, 'min_child_weight': 9, 'gamma': 0.49793315774329505, 'reg_alpha': 0.00012196965219956707, 'reg_lambda': 0.08186286072901727, 'max_delta_step': 0}. Best is trial 39 with value: 0.6296052631578948.

Best trial: 39. Best value: 0.629605:  92%|█████████▏| 46/50 [09:49<00:49, 12.42s/it]

[I 2025-12-01 23:26:20,962] Trial 48 pruned.

Best trial: 39. Best value: 0.629605:  94%|█████████▍| 47/50 [09:51<00:28,  9.47s/it]

[I 2025-12-01 23:26:23,542] Trial 44 finished with value: 0.6032894736842105 and parameters: {'max_depth': 3, 'learning_rate': 0.014338726641851537, 'n_estimators': 1195, 'subsample': 0.9676929077224156, 'colsample_bytree': 0.8741874521015628, 'min_child_weight': 9, 'gamma': 0.5041343042502663, 'reg_alpha': 0.00011714639428683088, 'reg_lambda': 0.054048276092693526, 'max_delta_step': 4}. Best is trial 39 with value: 0.6296052631578948.

Best trial: 39. Best value: 0.629605:  96%|█████████▌| 48/50 [09:59<00:18,  9.01s/it]

[I 2025-12-01 23:26:31,495] Trial 45 finished with value: 0.6157894736842104 and parameters: {'max_depth': 3, 'learning_rate': 0.014986337738687327, 'n_estimators': 1229, 'subsample': 0.969433596402642, 'colsample_bytree': 0.8570591710676456, 'min_child_weight': 9, 'gamma': 0.4543926542337701, 'reg_alpha': 5.467946588418887e-07, 'reg_lambda': 0.133280415370312, 'max_delta_step': 4}. Best is trial 39 with value: 0.6296052631578948.

Best trial: 39. Best value: 0.629605:  98%|█████████▊| 49/50 [10:20<00:12, 12.69s/it]

[I 2025-12-01 23:26:52,756] Trial 47 finished with value: 0.6032894736842105 and parameters: {'max_depth': 4, 'learning_rate': 0.014967316990655156, 'n_estimators': 1359, 'subsample': 0.966304021145576, 'colsample_bytree': 0.9029065823838789, 'min_child_weight': 9, 'gamma': 0.5733176767985845, 'reg_alpha': 6.976509098048053e-08, 'reg_lambda': 0.17617862807089524, 'max_delta_step': 6}. Best is trial 39 with value: 0.6296052631578948.

Best trial: 39. Best value: 0.629605: 100%|██████████| 50/50 [10:38<00:00, 12.77s/it]

[I 2025-12-01 23:27:10,544] Trial 49 finished with value: 0.5894736842105264 and parameters: {'max_depth': 3, 'learning_rate': 0.016148796194321198, 'n_estimators': 1406, 'subsample': 0.954736349262867, 'colsample_bytree': 0.8496719060931835, 'min_child_weight': 9, 'gamma': 0.00015444741559189623, 'reg_alpha': 6.314902395587625e-08, 'reg_lambda': 0.06550573284057253, 'max_delta_step': 4}. Best is trial 39 with value: 0.6296052631578948.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.639474                    0.70          0.75
1    15_1         loo       0.523748                    0.70          0.76
2    17_1         loo       0.697689                    0.55          0.60
3    19_1         loo       0.629605                    0.50          0.68

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.377964               0.8               0.6        50          59
1  0.377964               0.8               0.6        50          60
2  0.106600               0.8               0.3        50          60
3  0.000000               0.4               0.6        50          59

   test_size
0         15
1         15
2         15
3         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.639474                    0.70          0.75
1    15_1         loo       0.523748                    0.70          0.76
2    17_1         loo       0.697689                    0.55          0.60
3    19_1         loo       0.629605                    0.50          0.68

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.377964               0.8               0.6        50          59
1  0.377964               0.8               0.6        50          60
2  0.106600               0.8               0.3        50          60
3  0.000000               0.4               0.6        50          59

   test_size
0         15
1         15
2         15
3         15

In [1574]:

datasets = task_hf_dfs_clean_ad_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir="xgb_ad_hc_{CV_STRATEGY}_tasks/xgb_results_handcrafted_ad_hc_extended_{CV_STRATEGY}_tasks",
    split_param="w.cz.fnusa",
)
print(summary)

[I 2025-12-01 23:27:14,573] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.487163:   2%|▏         | 1/50 [00:22<18:22, 22.49s/it]

[I 2025-12-01 23:27:37,046] Trial 1 finished with value: 0.4871630295250321 and parameters: {'max_depth': 10, 'learning_rate': 0.056582048240176167, 'n_estimators': 458, 'subsample': 0.7307765026528601, 'colsample_bytree': 0.6507444495356667, 'min_child_weight': 3, 'gamma': 4.164005864862684, 'reg_alpha': 0.009312887155481078, 'reg_lambda': 1.0319996732709499e-07, 'max_delta_step': 1}. Best is trial 1 with value: 0.4871630295250321.

Best trial: 0. Best value: 0.548139:   4%|▍         | 2/50 [00:31<11:27, 14.32s/it]

[I 2025-12-01 23:27:45,656] Trial 0 finished with value: 0.5481386392811296 and parameters: {'max_depth': 8, 'learning_rate': 0.07301539735665359, 'n_estimators': 644, 'subsample': 0.8388992796542476, 'colsample_bytree': 0.8178296221878583, 'min_child_weight': 4, 'gamma': 0.7631677155160405, 'reg_alpha': 3.493524078482015e-08, 'reg_lambda': 3.288207667279682, 'max_delta_step': 8}. Best is trial 0 with value: 0.5481386392811296.

Best trial: 0. Best value: 0.548139:   6%|▌         | 3/50 [00:31<06:14,  7.98s/it]

[I 2025-12-01 23:27:46,087] Trial 2 finished with value: 0.511553273427471 and parameters: {'max_depth': 3, 'learning_rate': 0.010295464557983134, 'n_estimators': 537, 'subsample': 0.9381779337080771, 'colsample_bytree': 0.9995415523623115, 'min_child_weight': 2, 'gamma': 2.5638859708888058, 'reg_alpha': 0.0020905887203668187, 'reg_lambda': 0.007274055174927826, 'max_delta_step': 7}. Best is trial 0 with value: 0.5481386392811296.

Best trial: 0. Best value: 0.548139:   8%|▊         | 4/50 [01:04<13:40, 17.83s/it]

[I 2025-12-01 23:28:19,013] Trial 3 finished with value: 0.4974326059050064 and parameters: {'max_depth': 10, 'learning_rate': 0.013499543886930516, 'n_estimators': 1202, 'subsample': 0.7205611915487273, 'colsample_bytree': 0.8141166605940653, 'min_child_weight': 2, 'gamma': 2.521121327878839, 'reg_alpha': 0.0682903153179829, 'reg_lambda': 7.965280137053393e-07, 'max_delta_step': 5}. Best is trial 0 with value: 0.5481386392811296.

Best trial: 0. Best value: 0.548139:  10%|█         | 5/50 [01:07<09:26, 12.59s/it]

[I 2025-12-01 23:28:22,312] Trial 4 finished with value: 0.34210526315789475 and parameters: {'max_depth': 8, 'learning_rate': 0.02354399130187155, 'n_estimators': 912, 'subsample': 0.6704167588398944, 'colsample_bytree': 0.6635438306041687, 'min_child_weight': 9, 'gamma': 2.419792417162165, 'reg_alpha': 1.260361075495325e-06, 'reg_lambda': 0.18907640091581032, 'max_delta_step': 1}. Best is trial 0 with value: 0.5481386392811296.

Best trial: 0. Best value: 0.548139:  12%|█▏        | 6/50 [01:09<06:27,  8.80s/it]

[I 2025-12-01 23:28:23,751] Trial 6 finished with value: 0.5436456996148908 and parameters: {'max_depth': 6, 'learning_rate': 0.020414142386215695, 'n_estimators': 729, 'subsample': 0.7803230651129694, 'colsample_bytree': 0.8384202382123092, 'min_child_weight': 9, 'gamma': 2.312841140750569, 'reg_alpha': 4.546486273712154e-05, 'reg_lambda': 1.969628523542718e-06, 'max_delta_step': 8}. Best is trial 0 with value: 0.5481386392811296.

Best trial: 7. Best value: 0.578306:  14%|█▍        | 7/50 [01:19<06:39,  9.30s/it]

[I 2025-12-01 23:28:34,092] Trial 7 finished with value: 0.5783055198973043 and parameters: {'max_depth': 10, 'learning_rate': 0.027982497660556303, 'n_estimators': 254, 'subsample': 0.7802887281787036, 'colsample_bytree': 0.7708410954799584, 'min_child_weight': 4, 'gamma': 3.1259761753676085, 'reg_alpha': 1.656170431977725, 'reg_lambda': 0.0017281929389070378, 'max_delta_step': 0}. Best is trial 7 with value: 0.5783055198973043.

Best trial: 5. Best value: 0.630937:  16%|█▌        | 8/50 [01:39<08:56, 12.78s/it]

[I 2025-12-01 23:28:54,323] Trial 5 finished with value: 0.6309370988446728 and parameters: {'max_depth': 9, 'learning_rate': 0.1378005737340078, 'n_estimators': 1367, 'subsample': 0.7054920497466688, 'colsample_bytree': 0.8729941626185465, 'min_child_weight': 8, 'gamma': 4.941882227521332, 'reg_alpha': 5.715908788713839e-07, 'reg_lambda': 4.1757999990118996e-07, 'max_delta_step': 4}. Best is trial 5 with value: 0.6309370988446728.

Best trial: 5. Best value: 0.630937:  18%|█▊        | 9/50 [01:51<08:34, 12.55s/it]

[I 2025-12-01 23:29:06,352] Trial 8 finished with value: 0.5417201540436457 and parameters: {'max_depth': 10, 'learning_rate': 0.03012271435516057, 'n_estimators': 842, 'subsample': 0.5340193895378569, 'colsample_bytree': 0.9271693231982892, 'min_child_weight': 6, 'gamma': 4.26430646246542, 'reg_alpha': 0.8003459063200111, 'reg_lambda': 0.196009819180576, 'max_delta_step': 9}. Best is trial 5 with value: 0.6309370988446728.

Best trial: 5. Best value: 0.630937:  20%|██        | 10/50 [02:06<08:44, 13.12s/it]

[I 2025-12-01 23:29:20,749] Trial 10 finished with value: 0.44993581514762515 and parameters: {'max_depth': 8, 'learning_rate': 0.04355703943867382, 'n_estimators': 915, 'subsample': 0.5165002638349436, 'colsample_bytree': 0.5133804835864897, 'min_child_weight': 7, 'gamma': 1.1997828989715897, 'reg_alpha': 0.01418901682993184, 'reg_lambda': 1.6889982716170061e-06, 'max_delta_step': 9}. Best is trial 5 with value: 0.6309370988446728.

Best trial: 5. Best value: 0.630937:  22%|██▏       | 11/50 [02:16<08:03, 12.39s/it]

[I 2025-12-01 23:29:31,476] Trial 9 finished with value: 0.5378690629011553 and parameters: {'max_depth': 4, 'learning_rate': 0.03761076047260404, 'n_estimators': 1279, 'subsample': 0.878586876563076, 'colsample_bytree': 0.7891551314185736, 'min_child_weight': 5, 'gamma': 1.9604128294410343, 'reg_alpha': 5.514398580149123e-05, 'reg_lambda': 1.1944265176697313, 'max_delta_step': 0}. Best is trial 5 with value: 0.6309370988446728.

Best trial: 5. Best value: 0.630937:  24%|██▍       | 12/50 [02:47<11:15, 17.78s/it]

[I 2025-12-01 23:30:01,608] Trial 12 finished with value: 0.511553273427471 and parameters: {'max_depth': 6, 'learning_rate': 0.14302401805293133, 'n_estimators': 1043, 'subsample': 0.721530113153454, 'colsample_bytree': 0.7154823630441943, 'min_child_weight': 1, 'gamma': 4.591520777725578, 'reg_alpha': 0.007584602346672174, 'reg_lambda': 0.0002322075108827972, 'max_delta_step': 6}. Best is trial 5 with value: 0.6309370988446728.

Best trial: 5. Best value: 0.630937:  26%|██▌       | 13/50 [02:49<08:02, 13.04s/it]

[I 2025-12-01 23:30:03,728] Trial 11 finished with value: 0.6309370988446728 and parameters: {'max_depth': 10, 'learning_rate': 0.02734551614336624, 'n_estimators': 1382, 'subsample': 0.9879598719945524, 'colsample_bytree': 0.5274458656431549, 'min_child_weight': 8, 'gamma': 4.716591826183953, 'reg_alpha': 0.35068113891062425, 'reg_lambda': 0.45925696417851536, 'max_delta_step': 3}. Best is trial 5 with value: 0.6309370988446728.

Best trial: 5. Best value: 0.630937:  28%|██▊       | 14/50 [02:49<05:31,  9.21s/it]

[I 2025-12-01 23:30:04,092] Trial 15 pruned.

Best trial: 5. Best value: 0.630937:  30%|███       | 15/50 [03:00<05:46,  9.89s/it]

[I 2025-12-01 23:30:15,563] Trial 16 pruned.

Best trial: 5. Best value: 0.630937:  32%|███▏      | 16/50 [03:01<04:04,  7.19s/it]

[I 2025-12-01 23:30:16,490] Trial 17 pruned.

Best trial: 5. Best value: 0.630937:  34%|███▍      | 17/50 [03:22<06:14, 11.34s/it]

[I 2025-12-01 23:30:37,482] Trial 13 pruned.

Best trial: 5. Best value: 0.630937:  36%|███▌      | 18/50 [03:34<06:00, 11.27s/it]

[I 2025-12-01 23:30:48,567] Trial 14 finished with value: 0.5494223363286265 and parameters: {'max_depth': 9, 'learning_rate': 0.1938751200148693, 'n_estimators': 1493, 'subsample': 0.6170136863786759, 'colsample_bytree': 0.6997120388193968, 'min_child_weight': 7, 'gamma': 4.974928435031565, 'reg_alpha': 8.767844319451953, 'reg_lambda': 0.00015794620940570914, 'max_delta_step': 4}. Best is trial 5 with value: 0.6309370988446728.

Best trial: 19. Best value: 0.671374:  38%|███▊      | 19/50 [04:02<08:32, 16.55s/it]

[I 2025-12-01 23:31:17,423] Trial 19 finished with value: 0.6713735558408216 and parameters: {'max_depth': 9, 'learning_rate': 0.08940669146776406, 'n_estimators': 1171, 'subsample': 0.8577771226364401, 'colsample_bytree': 0.6267630271733873, 'min_child_weight': 8, 'gamma': 3.750944746136021, 'reg_alpha': 3.3874668290438306e-06, 'reg_lambda': 0.01180789764516508, 'max_delta_step': 3}. Best is trial 19 with value: 0.6713735558408216.

Best trial: 19. Best value: 0.671374:  40%|████      | 20/50 [04:16<07:47, 15.59s/it]

[I 2025-12-01 23:31:30,780] Trial 18 finished with value: 0.5943517329910142 and parameters: {'max_depth': 7, 'learning_rate': 0.09345597423279553, 'n_estimators': 1472, 'subsample': 0.9730263239426571, 'colsample_bytree': 0.5771833299036853, 'min_child_weight': 8, 'gamma': 3.7058515610984237, 'reg_alpha': 1.3151258834809583e-06, 'reg_lambda': 2.502964922794097e-08, 'max_delta_step': 3}. Best is trial 19 with value: 0.6713735558408216.

Best trial: 19. Best value: 0.671374:  42%|████▏     | 21/50 [04:24<06:28, 13.40s/it]

[I 2025-12-01 23:31:39,083] Trial 20 finished with value: 0.6046213093709885 and parameters: {'max_depth': 9, 'learning_rate': 0.10219834267176461, 'n_estimators': 1182, 'subsample': 0.852772584765904, 'colsample_bytree': 0.5887026087301631, 'min_child_weight': 8, 'gamma': 3.6590348992937685, 'reg_alpha': 1.983806739838285e-06, 'reg_lambda': 0.015633023896535096, 'max_delta_step': 2}. Best is trial 19 with value: 0.6713735558408216.

Best trial: 19. Best value: 0.671374:  44%|████▍     | 22/50 [04:35<05:52, 12.57s/it]

[I 2025-12-01 23:31:49,722] Trial 24 pruned.

Best trial: 19. Best value: 0.671374:  46%|████▌     | 23/50 [04:35<03:59,  8.87s/it]

[I 2025-12-01 23:31:49,962] Trial 21 finished with value: 0.6046213093709885 and parameters: {'max_depth': 7, 'learning_rate': 0.08990505407436525, 'n_estimators': 1186, 'subsample': 0.8456079064897465, 'colsample_bytree': 0.5865865527387658, 'min_child_weight': 8, 'gamma': 3.72061040554859, 'reg_alpha': 5.845270286820564e-06, 'reg_lambda': 0.014146737946482751, 'max_delta_step': 2}. Best is trial 19 with value: 0.6713735558408216.

Best trial: 19. Best value: 0.671374:  48%|████▊     | 24/50 [04:44<03:50,  8.87s/it]

[I 2025-12-01 23:31:58,823] Trial 25 pruned.

Best trial: 19. Best value: 0.671374:  50%|█████     | 25/50 [04:47<02:56,  7.06s/it]

[I 2025-12-01 23:32:01,676] Trial 26 pruned.

Best trial: 19. Best value: 0.671374:  52%|█████▏    | 26/50 [05:00<03:35,  8.99s/it]

[I 2025-12-01 23:32:15,159] Trial 22 finished with value: 0.6309370988446728 and parameters: {'max_depth': 7, 'learning_rate': 0.09672116430212994, 'n_estimators': 1110, 'subsample': 0.8721388636057873, 'colsample_bytree': 0.5962048134148831, 'min_child_weight': 8, 'gamma': 3.68628202613887, 'reg_alpha': 1.655030158490604e-06, 'reg_lambda': 0.014184481255967588, 'max_delta_step': 2}. Best is trial 19 with value: 0.6713735558408216.

Best trial: 19. Best value: 0.671374:  54%|█████▍    | 27/50 [05:15<04:06, 10.73s/it]

[I 2025-12-01 23:32:29,961] Trial 23 finished with value: 0.5924261874197689 and parameters: {'max_depth': 8, 'learning_rate': 0.13923757327336023, 'n_estimators': 1139, 'subsample': 0.8569049180247926, 'colsample_bytree': 0.5888747541313231, 'min_child_weight': 8, 'gamma': 3.8508485628480846, 'reg_alpha': 1.4713091490552706e-05, 'reg_lambda': 1.7210297335520235e-05, 'max_delta_step': 2}. Best is trial 19 with value: 0.6713735558408216.

Best trial: 19. Best value: 0.671374:  56%|█████▌    | 28/50 [05:44<05:54, 16.13s/it]

[I 2025-12-01 23:32:58,668] Trial 28 finished with value: 0.641206675224647 and parameters: {'max_depth': 10, 'learning_rate': 0.144225567411388, 'n_estimators': 1088, 'subsample': 0.9319328531805761, 'colsample_bytree': 0.875903205752019, 'min_child_weight': 9, 'gamma': 0.11817326476581114, 'reg_alpha': 0.0007763697529353051, 'reg_lambda': 0.821155783286521, 'max_delta_step': 3}. Best is trial 19 with value: 0.6713735558408216.

Best trial: 27. Best value: 0.681643:  58%|█████▊    | 29/50 [05:50<04:40, 13.35s/it]

[I 2025-12-01 23:33:05,526] Trial 27 finished with value: 0.6816431322207959 and parameters: {'max_depth': 10, 'learning_rate': 0.04422751870627591, 'n_estimators': 1328, 'subsample': 0.9085436740210049, 'colsample_bytree': 0.5419881559206984, 'min_child_weight': 9, 'gamma': 3.000396883435668, 'reg_alpha': 0.0003064483923607972, 'reg_lambda': 2.00479140979562e-05, 'max_delta_step': 5}. Best is trial 27 with value: 0.6816431322207959.

Best trial: 27. Best value: 0.681643:  60%|██████    | 30/50 [05:52<03:17,  9.87s/it]

[I 2025-12-01 23:33:07,279] Trial 31 pruned.

Best trial: 27. Best value: 0.681643:  62%|██████▏   | 31/50 [06:10<03:49, 12.10s/it]

[I 2025-12-01 23:33:24,584] Trial 29 finished with value: 0.6675224646983312 and parameters: {'max_depth': 10, 'learning_rate': 0.14373394567603937, 'n_estimators': 1342, 'subsample': 0.9328923643865533, 'colsample_bytree': 0.7229822749224913, 'min_child_weight': 9, 'gamma': 4.45880485035635, 'reg_alpha': 0.0006890437955031022, 'reg_lambda': 6.5089158711736275, 'max_delta_step': 5}. Best is trial 27 with value: 0.6816431322207959.

Best trial: 27. Best value: 0.681643:  64%|██████▍   | 32/50 [06:25<03:54, 13.04s/it]

[I 2025-12-01 23:33:39,831] Trial 30 finished with value: 0.6694480102695763 and parameters: {'max_depth': 10, 'learning_rate': 0.044031056796312924, 'n_estimators': 1341, 'subsample': 0.9118367562267637, 'colsample_bytree': 0.545193352149044, 'min_child_weight': 7, 'gamma': 4.310434913720026, 'reg_alpha': 0.00038604796442289336, 'reg_lambda': 0.7699453060781734, 'max_delta_step': 5}. Best is trial 27 with value: 0.6816431322207959.

Best trial: 27. Best value: 0.681643:  66%|██████▌   | 33/50 [06:43<04:08, 14.59s/it]

[I 2025-12-01 23:33:58,028] Trial 32 finished with value: 0.6572528883183568 and parameters: {'max_depth': 10, 'learning_rate': 0.18033101582287114, 'n_estimators': 1029, 'subsample': 0.9177036058295237, 'colsample_bytree': 0.7118211088685218, 'min_child_weight': 9, 'gamma': 0.030484815982310454, 'reg_alpha': 0.0002635401191716602, 'reg_lambda': 2.9355178022725257, 'max_delta_step': 5}. Best is trial 27 with value: 0.6816431322207959.

Best trial: 27. Best value: 0.681643:  68%|██████▊   | 34/50 [06:57<03:52, 14.56s/it]

[I 2025-12-01 23:34:12,518] Trial 33 finished with value: 0.6816431322207959 and parameters: {'max_depth': 10, 'learning_rate': 0.04729843839249112, 'n_estimators': 1260, 'subsample': 0.9273617908245866, 'colsample_bytree': 0.7335568468802838, 'min_child_weight': 9, 'gamma': 1.643274740947165, 'reg_alpha': 0.0001490101294479978, 'reg_lambda': 0.0008747471003692104, 'max_delta_step': 10}. Best is trial 27 with value: 0.6816431322207959.

Best trial: 27. Best value: 0.681643:  70%|███████   | 35/50 [07:15<03:53, 15.53s/it]

[I 2025-12-01 23:34:30,319] Trial 34 finished with value: 0.6450577663671373 and parameters: {'max_depth': 10, 'learning_rate': 0.04191423203421523, 'n_estimators': 1262, 'subsample': 0.9269202053421252, 'colsample_bytree': 0.7282814380415163, 'min_child_weight': 9, 'gamma': 1.4170513620236422, 'reg_alpha': 0.00016902961399614663, 'reg_lambda': 4.203930916781191, 'max_delta_step': 5}. Best is trial 27 with value: 0.6816431322207959.

Best trial: 27. Best value: 0.681643:  72%|███████▏  | 36/50 [07:27<03:21, 14.42s/it]

[I 2025-12-01 23:34:42,136] Trial 35 finished with value: 0.6309370988446728 and parameters: {'max_depth': 10, 'learning_rate': 0.049582415331464506, 'n_estimators': 1214, 'subsample': 0.9154871422430857, 'colsample_bytree': 0.7142601456025345, 'min_child_weight': 7, 'gamma': 3.0626741039340675, 'reg_alpha': 0.00011774896240721472, 'reg_lambda': 6.668068462588629, 'max_delta_step': 7}. Best is trial 27 with value: 0.6816431322207959.

Best trial: 27. Best value: 0.681643:  74%|███████▍  | 37/50 [07:38<02:53, 13.31s/it]

[I 2025-12-01 23:34:52,883] Trial 39 pruned.

Best trial: 27. Best value: 0.681643:  76%|███████▌  | 38/50 [07:46<02:21, 11.76s/it]

[I 2025-12-01 23:35:01,017] Trial 40 pruned.

Best trial: 27. Best value: 0.681643:  78%|███████▊  | 39/50 [07:48<01:36,  8.81s/it]

[I 2025-12-01 23:35:02,933] Trial 36 finished with value: 0.6187419768934532 and parameters: {'max_depth': 10, 'learning_rate': 0.05104194404182198, 'n_estimators': 1280, 'subsample': 0.8969688136327997, 'colsample_bytree': 0.5480913851126058, 'min_child_weight': 7, 'gamma': 3.1233064987477537, 'reg_alpha': 0.00014389983766686264, 'reg_lambda': 9.93615477207727, 'max_delta_step': 7}. Best is trial 27 with value: 0.6816431322207959.

Best trial: 27. Best value: 0.681643:  80%|████████  | 40/50 [07:52<01:14,  7.41s/it]

[I 2025-12-01 23:35:07,095] Trial 37 pruned.

Best trial: 27. Best value: 0.681643:  82%|████████▏ | 41/50 [08:11<01:39, 11.03s/it]

[I 2025-12-01 23:35:26,548] Trial 41 pruned.

Best trial: 27. Best value: 0.681643:  84%|████████▍ | 42/50 [08:16<01:13,  9.17s/it]

[I 2025-12-01 23:35:31,372] Trial 38 finished with value: 0.6572528883183568 and parameters: {'max_depth': 9, 'learning_rate': 0.05230926001454755, 'n_estimators': 1209, 'subsample': 0.8941968773623976, 'colsample_bytree': 0.5476389396233767, 'min_child_weight': 7, 'gamma': 2.913211845426403, 'reg_alpha': 0.0031982924884476236, 'reg_lambda': 0.0010212465529407116, 'max_delta_step': 10}. Best is trial 27 with value: 0.6816431322207959.

Best trial: 27. Best value: 0.681643:  86%|████████▌ | 43/50 [08:29<01:11, 10.21s/it]

[I 2025-12-01 23:35:44,023] Trial 42 finished with value: 0.5622593068035944 and parameters: {'max_depth': 9, 'learning_rate': 0.03460791135203578, 'n_estimators': 752, 'subsample': 0.9592133056447715, 'colsample_bytree': 0.681585712604757, 'min_child_weight': 4, 'gamma': 2.1086092386188877, 'reg_alpha': 7.23699855626277e-06, 'reg_lambda': 0.0005526823772791572, 'max_delta_step': 8}. Best is trial 27 with value: 0.6816431322207959.

Best trial: 27. Best value: 0.681643:  88%|████████▊ | 44/50 [08:31<00:46,  7.79s/it]

[I 2025-12-01 23:35:46,163] Trial 43 finished with value: 0.5622593068035944 and parameters: {'max_depth': 9, 'learning_rate': 0.03551253959347761, 'n_estimators': 731, 'subsample': 0.9550337982979643, 'colsample_bytree': 0.682037984369775, 'min_child_weight': 4, 'gamma': 2.737327440389782, 'reg_alpha': 0.002115739566831505, 'reg_lambda': 1.0306118816784991e-05, 'max_delta_step': 8}. Best is trial 27 with value: 0.6816431322207959.

Best trial: 27. Best value: 0.681643:  90%|█████████ | 45/50 [09:19<01:39, 19.89s/it]

[I 2025-12-01 23:36:34,267] Trial 44 finished with value: 0.6572528883183568 and parameters: {'max_depth': 10, 'learning_rate': 0.03828762023662029, 'n_estimators': 1330, 'subsample': 0.9534126065105342, 'colsample_bytree': 0.677797418391551, 'min_child_weight': 9, 'gamma': 2.795612786600043, 'reg_alpha': 0.0010793898817978691, 'reg_lambda': 8.013161700932012e-06, 'max_delta_step': 6}. Best is trial 27 with value: 0.6816431322207959.

Best trial: 27. Best value: 0.681643:  92%|█████████▏| 46/50 [09:26<01:04, 16.10s/it]

[I 2025-12-01 23:36:41,528] Trial 45 finished with value: 0.6816431322207959 and parameters: {'max_depth': 10, 'learning_rate': 0.08341194939297852, 'n_estimators': 1350, 'subsample': 0.9542419599786769, 'colsample_bytree': 0.68276620630244, 'min_child_weight': 9, 'gamma': 4.073171961792438, 'reg_alpha': 0.0009640579195184544, 'reg_lambda': 1.2288751039595396e-05, 'max_delta_step': 6}. Best is trial 27 with value: 0.6816431322207959.

Best trial: 27. Best value: 0.681643:  94%|█████████▍| 47/50 [09:38<00:43, 14.64s/it]

[I 2025-12-01 23:36:52,775] Trial 46 finished with value: 0.6816431322207959 and parameters: {'max_depth': 3, 'learning_rate': 0.08263308730347574, 'n_estimators': 1338, 'subsample': 0.9544180596477759, 'colsample_bytree': 0.7725776420068218, 'min_child_weight': 9, 'gamma': 4.080982311632038, 'reg_alpha': 0.0008489441024117811, 'reg_lambda': 5.737683331460256e-06, 'max_delta_step': 6}. Best is trial 27 with value: 0.6816431322207959.

Best trial: 27. Best value: 0.681643:  96%|█████████▌| 48/50 [09:38<00:20, 10.40s/it]

[I 2025-12-01 23:36:53,272] Trial 49 pruned.

Best trial: 47. Best value: 0.695764:  98%|█████████▊| 49/50 [09:39<00:07,  7.65s/it]

[I 2025-12-01 23:36:54,525] Trial 47 finished with value: 0.6957637997432606 and parameters: {'max_depth': 3, 'learning_rate': 0.08255469575553977, 'n_estimators': 1360, 'subsample': 0.8292934835043091, 'colsample_bytree': 0.7523132520938582, 'min_child_weight': 9, 'gamma': 3.3764350654276347, 'reg_alpha': 0.0006920732819522329, 'reg_lambda': 0.20191463953841227, 'max_delta_step': 6}. Best is trial 47 with value: 0.6957637997432606.

Best trial: 47. Best value: 0.695764: 100%|██████████| 50/50 [09:50<00:00, 11.80s/it]

[I 2025-12-01 23:37:04,570] Trial 48 finished with value: 0.6611039794608472 and parameters: {'max_depth': 3, 'learning_rate': 0.0823029479538213, 'n_estimators': 1384, 'subsample': 0.7597698922826014, 'colsample_bytree': 0.7987594316379312, 'min_child_weight': 9, 'gamma': 3.381126179484672, 'reg_alpha': 0.020583743911273766, 'reg_lambda': 0.09750056015037875, 'max_delta_step': 5}. Best is trial 47 with value: 0.6957637997432606.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 23:37:07,752] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.604621:   2%|▏         | 1/50 [00:17<14:37, 17.91s/it]

[I 2025-12-01 23:37:25,653] Trial 2 finished with value: 0.6046213093709885 and parameters: {'max_depth': 3, 'learning_rate': 0.05621734560357569, 'n_estimators': 357, 'subsample': 0.8116301777483479, 'colsample_bytree': 0.5732068669409537, 'min_child_weight': 7, 'gamma': 1.479058128768766, 'reg_alpha': 4.565736206712403, 'reg_lambda': 4.52244160804742, 'max_delta_step': 8}. Best is trial 2 with value: 0.6046213093709885.

Best trial: 2. Best value: 0.604621:   4%|▍         | 2/50 [00:25<09:27, 11.83s/it]

[I 2025-12-01 23:37:33,222] Trial 1 finished with value: 0.5012836970474968 and parameters: {'max_depth': 5, 'learning_rate': 0.015428804286563265, 'n_estimators': 450, 'subsample': 0.5499486876092938, 'colsample_bytree': 0.8300391715199524, 'min_child_weight': 3, 'gamma': 1.7064612749259855, 'reg_alpha': 1.2839626164035272, 'reg_lambda': 6.074779350797082, 'max_delta_step': 3}. Best is trial 2 with value: 0.6046213093709885.

Best trial: 2. Best value: 0.604621:   6%|▌         | 3/50 [00:48<13:26, 17.15s/it]

[I 2025-12-01 23:37:56,709] Trial 0 finished with value: 0.45892169448010267 and parameters: {'max_depth': 8, 'learning_rate': 0.0699498063949746, 'n_estimators': 925, 'subsample': 0.8400633023156587, 'colsample_bytree': 0.9362410330878919, 'min_child_weight': 3, 'gamma': 3.172486208434508, 'reg_alpha': 0.002262157198846555, 'reg_lambda': 1.903944795419995e-06, 'max_delta_step': 1}. Best is trial 2 with value: 0.6046213093709885.

Best trial: 2. Best value: 0.604621:   8%|▊         | 4/50 [00:49<08:07, 10.60s/it]

[I 2025-12-01 23:37:57,261] Trial 4 finished with value: 0.46277278562259305 and parameters: {'max_depth': 6, 'learning_rate': 0.2350361788369215, 'n_estimators': 618, 'subsample': 0.818011786842761, 'colsample_bytree': 0.5186651886814001, 'min_child_weight': 5, 'gamma': 3.523756081743506, 'reg_alpha': 0.39796178168068846, 'reg_lambda': 6.431070742518921e-08, 'max_delta_step': 3}. Best is trial 2 with value: 0.6046213093709885.

Best trial: 2. Best value: 0.604621:  10%|█         | 5/50 [00:54<06:22,  8.49s/it]

[I 2025-12-01 23:38:02,016] Trial 3 finished with value: 0.14634146341463414 and parameters: {'max_depth': 5, 'learning_rate': 0.022272649430030027, 'n_estimators': 1120, 'subsample': 0.9383727901908347, 'colsample_bytree': 0.7170581192065685, 'min_child_weight': 10, 'gamma': 1.4688036186053233, 'reg_alpha': 0.3730561890738521, 'reg_lambda': 4.606205430442734e-08, 'max_delta_step': 1}. Best is trial 2 with value: 0.6046213093709885.

Best trial: 2. Best value: 0.604621:  12%|█▏        | 6/50 [00:59<05:20,  7.29s/it]

[I 2025-12-01 23:38:06,975] Trial 5 finished with value: 0.5012836970474968 and parameters: {'max_depth': 5, 'learning_rate': 0.07473255565718895, 'n_estimators': 652, 'subsample': 0.7868845292006875, 'colsample_bytree': 0.5044128643144987, 'min_child_weight': 2, 'gamma': 3.3986869863086353, 'reg_alpha': 9.03929537960481e-08, 'reg_lambda': 0.0005596641246057637, 'max_delta_step': 0}. Best is trial 2 with value: 0.6046213093709885.

Best trial: 2. Best value: 0.604621:  14%|█▍        | 7/50 [01:12<06:40,  9.32s/it]

[I 2025-12-01 23:38:20,463] Trial 9 finished with value: 0.4441591784338896 and parameters: {'max_depth': 3, 'learning_rate': 0.1435236914244245, 'n_estimators': 279, 'subsample': 0.5021129552491378, 'colsample_bytree': 0.7013199530454173, 'min_child_weight': 7, 'gamma': 1.333856860322871, 'reg_alpha': 0.0007421078957985313, 'reg_lambda': 7.975405283596917e-07, 'max_delta_step': 6}. Best is trial 2 with value: 0.6046213093709885.

Best trial: 2. Best value: 0.604621:  16%|█▌        | 8/50 [01:15<05:03,  7.22s/it]

[I 2025-12-01 23:38:23,211] Trial 6 finished with value: 0.5661103979460848 and parameters: {'max_depth': 3, 'learning_rate': 0.027061370129521884, 'n_estimators': 490, 'subsample': 0.9868620287746557, 'colsample_bytree': 0.6210063931326144, 'min_child_weight': 1, 'gamma': 1.211657217608364, 'reg_alpha': 0.22722419449068748, 'reg_lambda': 5.199532651538564e-07, 'max_delta_step': 8}. Best is trial 2 with value: 0.6046213093709885.

Best trial: 2. Best value: 0.604621:  18%|█▊        | 9/50 [01:19<04:14,  6.20s/it]

[I 2025-12-01 23:38:27,167] Trial 8 finished with value: 0.4467265725288832 and parameters: {'max_depth': 5, 'learning_rate': 0.021590636353707095, 'n_estimators': 370, 'subsample': 0.6062655022002794, 'colsample_bytree': 0.7684637298384048, 'min_child_weight': 1, 'gamma': 0.33985129082021004, 'reg_alpha': 0.764923650222611, 'reg_lambda': 0.0005792833059775707, 'max_delta_step': 3}. Best is trial 2 with value: 0.6046213093709885.

Best trial: 2. Best value: 0.604621:  20%|██        | 10/50 [01:31<05:25,  8.14s/it]

[I 2025-12-01 23:38:39,632] Trial 7 finished with value: 0.5397946084724006 and parameters: {'max_depth': 4, 'learning_rate': 0.012983780360563297, 'n_estimators': 897, 'subsample': 0.694906969966899, 'colsample_bytree': 0.7751457955153682, 'min_child_weight': 5, 'gamma': 3.5067143627783857, 'reg_alpha': 2.1336924365220713e-05, 'reg_lambda': 3.5307074783067547, 'max_delta_step': 4}. Best is trial 2 with value: 0.6046213093709885.

Best trial: 2. Best value: 0.604621:  22%|██▏       | 11/50 [01:34<04:14,  6.51s/it]

[I 2025-12-01 23:38:42,466] Trial 12 pruned.

Best trial: 2. Best value: 0.604621:  24%|██▍       | 12/50 [01:36<03:08,  4.95s/it]

[I 2025-12-01 23:38:43,852] Trial 10 pruned.

Best trial: 2. Best value: 0.604621:  26%|██▌       | 13/50 [01:37<02:20,  3.80s/it]

[I 2025-12-01 23:38:44,984] Trial 11 pruned.

Best trial: 2. Best value: 0.604621:  28%|██▊       | 14/50 [01:38<01:50,  3.08s/it]

[I 2025-12-01 23:38:46,395] Trial 15 pruned.

Best trial: 2. Best value: 0.604621:  30%|███       | 15/50 [01:46<02:40,  4.58s/it]

[I 2025-12-01 23:38:54,468] Trial 14 finished with value: 0.5378690629011553 and parameters: {'max_depth': 9, 'learning_rate': 0.037182412998196385, 'n_estimators': 208, 'subsample': 0.9935803948404552, 'colsample_bytree': 0.6226999151185038, 'min_child_weight': 7, 'gamma': 4.985573465856977, 'reg_alpha': 7.467316686713864, 'reg_lambda': 0.214004085833196, 'max_delta_step': 9}. Best is trial 2 with value: 0.6046213093709885.

Best trial: 16. Best value: 0.643132:  32%|███▏      | 16/50 [01:49<02:19,  4.12s/it]

[I 2025-12-01 23:38:57,507] Trial 16 finished with value: 0.6431322207958922 and parameters: {'max_depth': 10, 'learning_rate': 0.0381703563744337, 'n_estimators': 212, 'subsample': 0.9870529974051145, 'colsample_bytree': 0.620470940784013, 'min_child_weight': 7, 'gamma': 4.689850492359758, 'reg_alpha': 5.302083143348653, 'reg_lambda': 0.011716817758308042, 'max_delta_step': 10}. Best is trial 16 with value: 0.6431322207958922.

Best trial: 16. Best value: 0.643132:  34%|███▍      | 17/50 [02:07<04:32,  8.27s/it]

[I 2025-12-01 23:39:15,438] Trial 17 finished with value: 0.5802310654685494 and parameters: {'max_depth': 3, 'learning_rate': 0.03504183250094875, 'n_estimators': 523, 'subsample': 0.9002717126097575, 'colsample_bytree': 0.6424255825008526, 'min_child_weight': 7, 'gamma': 0.3433637640208431, 'reg_alpha': 0.04180358212535906, 'reg_lambda': 0.07089546062319457, 'max_delta_step': 9}. Best is trial 16 with value: 0.6431322207958922.

Best trial: 16. Best value: 0.643132:  36%|███▌      | 18/50 [02:11<03:45,  7.04s/it]

[I 2025-12-01 23:39:19,607] Trial 18 finished with value: 0.6206675224646983 and parameters: {'max_depth': 3, 'learning_rate': 0.09185797754814516, 'n_estimators': 469, 'subsample': 0.8872100777050675, 'colsample_bytree': 0.6316548639969896, 'min_child_weight': 8, 'gamma': 0.038139951600144606, 'reg_alpha': 0.032626098699723355, 'reg_lambda': 5.021259442137692e-05, 'max_delta_step': 8}. Best is trial 16 with value: 0.6431322207958922.

Best trial: 16. Best value: 0.643132:  38%|███▊      | 19/50 [02:13<02:47,  5.42s/it]

[I 2025-12-01 23:39:21,247] Trial 19 finished with value: 0.5680359435173299 and parameters: {'max_depth': 10, 'learning_rate': 0.1023819332411775, 'n_estimators': 442, 'subsample': 0.8740835043117615, 'colsample_bytree': 0.6904152993881679, 'min_child_weight': 8, 'gamma': 4.289072806662551, 'reg_alpha': 3.4091205879985365e-05, 'reg_lambda': 0.01967134580973918, 'max_delta_step': 10}. Best is trial 16 with value: 0.6431322207958922.

Best trial: 13. Best value: 0.695764:  40%|████      | 20/50 [02:39<05:47, 11.57s/it]

[I 2025-12-01 23:39:47,166] Trial 13 finished with value: 0.6957637997432606 and parameters: {'max_depth': 9, 'learning_rate': 0.04311191882210734, 'n_estimators': 1332, 'subsample': 0.6941633186596526, 'colsample_bytree': 0.6150216639412988, 'min_child_weight': 8, 'gamma': 4.78401840003167, 'reg_alpha': 4.427017565231036e-06, 'reg_lambda': 0.09500693167925814, 'max_delta_step': 10}. Best is trial 13 with value: 0.6957637997432606.

Best trial: 13. Best value: 0.695764:  42%|████▏     | 21/50 [02:51<05:43, 11.84s/it]

[I 2025-12-01 23:39:59,629] Trial 23 pruned.

Best trial: 20. Best value: 0.734275:  44%|████▍     | 22/50 [03:04<05:37, 12.07s/it]

[I 2025-12-01 23:40:12,221] Trial 20 finished with value: 0.7342747111681642 and parameters: {'max_depth': 10, 'learning_rate': 0.10113226245669904, 'n_estimators': 1094, 'subsample': 0.8782522669961688, 'colsample_bytree': 0.5526781705977762, 'min_child_weight': 9, 'gamma': 4.041740501486255, 'reg_alpha': 7.604004645047596e-05, 'reg_lambda': 0.004534946723187066, 'max_delta_step': 10}. Best is trial 20 with value: 0.7342747111681642.

Best trial: 20. Best value: 0.734275:  46%|████▌     | 23/50 [03:10<04:35, 10.21s/it]

[I 2025-12-01 23:40:18,088] Trial 21 finished with value: 0.6816431322207959 and parameters: {'max_depth': 10, 'learning_rate': 0.10883462953518497, 'n_estimators': 1140, 'subsample': 0.898216244835573, 'colsample_bytree': 0.6827704255157947, 'min_child_weight': 9, 'gamma': 4.238336556415336, 'reg_alpha': 3.365455790642003e-05, 'reg_lambda': 5.0296446928455135e-05, 'max_delta_step': 10}. Best is trial 20 with value: 0.7342747111681642.

Best trial: 20. Best value: 0.734275:  48%|████▊     | 24/50 [03:12<03:20,  7.72s/it]

[I 2025-12-01 23:40:20,015] Trial 22 finished with value: 0.6450577663671373 and parameters: {'max_depth': 7, 'learning_rate': 0.11296784426799678, 'n_estimators': 1140, 'subsample': 0.9292679543949562, 'colsample_bytree': 0.877272622037211, 'min_child_weight': 9, 'gamma': 2.6723017913226688, 'reg_alpha': 0.03178333880524967, 'reg_lambda': 1.540435341523186e-05, 'max_delta_step': 7}. Best is trial 20 with value: 0.7342747111681642.

Best trial: 20. Best value: 0.734275:  50%|█████     | 25/50 [03:56<07:46, 18.66s/it]

[I 2025-12-01 23:41:04,207] Trial 24 finished with value: 0.7220795892169447 and parameters: {'max_depth': 9, 'learning_rate': 0.07667824457359938, 'n_estimators': 1219, 'subsample': 0.757233553144441, 'colsample_bytree': 0.5682661856328697, 'min_child_weight': 9, 'gamma': 4.37957909249879, 'reg_alpha': 2.4226195790689364e-05, 'reg_lambda': 1.7671160685747786e-05, 'max_delta_step': 8}. Best is trial 20 with value: 0.7342747111681642.

Best trial: 20. Best value: 0.734275:  52%|█████▏    | 26/50 [04:07<06:30, 16.28s/it]

[I 2025-12-01 23:41:14,928] Trial 28 pruned.

Best trial: 20. Best value: 0.734275:  54%|█████▍    | 27/50 [04:09<04:37, 12.06s/it]

[I 2025-12-01 23:41:17,134] Trial 25 finished with value: 0.6854942233632862 and parameters: {'max_depth': 9, 'learning_rate': 0.13553995998796914, 'n_estimators': 1237, 'subsample': 0.7539417516051347, 'colsample_bytree': 0.5597229716576769, 'min_child_weight': 9, 'gamma': 4.277334509114955, 'reg_alpha': 8.398523374231015e-05, 'reg_lambda': 0.6498350170858022, 'max_delta_step': 9}. Best is trial 20 with value: 0.7342747111681642.

Best trial: 20. Best value: 0.734275:  56%|█████▌    | 28/50 [04:12<03:24,  9.31s/it]

[I 2025-12-01 23:41:20,028] Trial 26 finished with value: 0.7098844672657253 and parameters: {'max_depth': 9, 'learning_rate': 0.13906251405800218, 'n_estimators': 1207, 'subsample': 0.7731128291061226, 'colsample_bytree': 0.5594778730689146, 'min_child_weight': 9, 'gamma': 3.9776585388313355, 'reg_alpha': 3.3440261234314405e-05, 'reg_lambda': 2.8795560568374608e-05, 'max_delta_step': 9}. Best is trial 20 with value: 0.7342747111681642.

Best trial: 20. Best value: 0.734275:  58%|█████▊    | 29/50 [04:17<02:50,  8.13s/it]

[I 2025-12-01 23:41:25,402] Trial 27 finished with value: 0.7220795892169447 and parameters: {'max_depth': 9, 'learning_rate': 0.1910003120626987, 'n_estimators': 1272, 'subsample': 0.7555598892059108, 'colsample_bytree': 0.5563397595011569, 'min_child_weight': 9, 'gamma': 4.033324387743784, 'reg_alpha': 4.102356563096235e-05, 'reg_lambda': 0.5086378246677341, 'max_delta_step': 9}. Best is trial 20 with value: 0.7342747111681642.

Best trial: 20. Best value: 0.734275:  60%|██████    | 30/50 [04:30<03:08,  9.44s/it]

[I 2025-12-01 23:41:37,904] Trial 31 pruned.

Best trial: 20. Best value: 0.734275:  62%|██████▏   | 31/50 [04:35<02:33,  8.07s/it]

[I 2025-12-01 23:41:42,770] Trial 32 pruned.

Best trial: 20. Best value: 0.734275:  64%|██████▍   | 32/50 [04:47<02:51,  9.51s/it]

[I 2025-12-01 23:41:55,654] Trial 34 pruned.

Best trial: 20. Best value: 0.734275:  66%|██████▌   | 33/50 [05:00<02:58, 10.49s/it]

[I 2025-12-01 23:42:08,436] Trial 30 finished with value: 0.6450577663671373 and parameters: {'max_depth': 8, 'learning_rate': 0.2957771960334561, 'n_estimators': 996, 'subsample': 0.6475772901711613, 'colsample_bytree': 0.5209123518624462, 'min_child_weight': 8, 'gamma': 3.7811079639003786, 'reg_alpha': 1.434715914413409e-08, 'reg_lambda': 1.011880376164195e-05, 'max_delta_step': 7}. Best is trial 20 with value: 0.7342747111681642.

Best trial: 20. Best value: 0.734275:  68%|██████▊   | 34/50 [05:08<02:35,  9.74s/it]

[I 2025-12-01 23:42:16,428] Trial 35 pruned.

Best trial: 20. Best value: 0.734275:  70%|███████   | 35/50 [05:12<01:59,  7.97s/it]

[I 2025-12-01 23:42:20,252] Trial 29 finished with value: 0.634788189987163 and parameters: {'max_depth': 8, 'learning_rate': 0.18177480901037907, 'n_estimators': 1280, 'subsample': 0.6297287354560894, 'colsample_bytree': 0.5419997163833907, 'min_child_weight': 8, 'gamma': 3.9524170611907916, 'reg_alpha': 0.00016002847691165111, 'reg_lambda': 0.5119756600174329, 'max_delta_step': 7}. Best is trial 20 with value: 0.7342747111681642.

Best trial: 20. Best value: 0.734275:  72%|███████▏  | 36/50 [05:22<02:01,  8.64s/it]

[I 2025-12-01 23:42:30,476] Trial 33 finished with value: 0.5905006418485237 and parameters: {'max_depth': 8, 'learning_rate': 0.1880552429616964, 'n_estimators': 1007, 'subsample': 0.8311849285257158, 'colsample_bytree': 0.9464199742865342, 'min_child_weight': 6, 'gamma': 2.7480168187685017, 'reg_alpha': 5.148388664969704e-06, 'reg_lambda': 0.732040307783925, 'max_delta_step': 6}. Best is trial 20 with value: 0.7342747111681642.

Best trial: 20. Best value: 0.734275:  74%|███████▍  | 37/50 [06:05<04:03, 18.75s/it]

[I 2025-12-01 23:43:12,801] Trial 36 finished with value: 0.6469833119383825 and parameters: {'max_depth': 10, 'learning_rate': 0.07858121261583732, 'n_estimators': 1229, 'subsample': 0.8322344147675951, 'colsample_bytree': 0.976535307470236, 'min_child_weight': 9, 'gamma': 2.791043906079431, 'reg_alpha': 0.0043856881235415516, 'reg_lambda': 0.8664955418751621, 'max_delta_step': 9}. Best is trial 20 with value: 0.7342747111681642.

Best trial: 20. Best value: 0.734275:  76%|███████▌  | 38/50 [06:05<02:40, 13.39s/it]

[I 2025-12-01 23:43:13,694] Trial 37 finished with value: 0.6976893453145058 and parameters: {'max_depth': 9, 'learning_rate': 0.07922565891997647, 'n_estimators': 1081, 'subsample': 0.7802316631740033, 'colsample_bytree': 0.6718253919196171, 'min_child_weight': 9, 'gamma': 2.9388677391790177, 'reg_alpha': 1.2868116218562486e-05, 'reg_lambda': 0.002027917288816328, 'max_delta_step': 6}. Best is trial 20 with value: 0.7342747111681642.

Best trial: 20. Best value: 0.734275:  78%|███████▊  | 39/50 [06:12<02:06, 11.47s/it]

[I 2025-12-01 23:43:20,684] Trial 38 finished with value: 0.6469833119383825 and parameters: {'max_depth': 9, 'learning_rate': 0.08739803271426573, 'n_estimators': 1176, 'subsample': 0.7908674945084304, 'colsample_bytree': 0.6629704309391293, 'min_child_weight': 9, 'gamma': 3.015291515527667, 'reg_alpha': 1.0188120367219806e-05, 'reg_lambda': 0.002427452632804197, 'max_delta_step': 8}. Best is trial 20 with value: 0.7342747111681642.
[I 2025-12-01 23:43:20,706] Trial 41 pruned.

Best trial: 20. Best value: 0.734275:  82%|████████▏ | 41/50 [06:14<00:59,  6.62s/it]

[I 2025-12-01 23:43:22,592] Trial 40 pruned.

Best trial: 20. Best value: 0.734275:  84%|████████▍ | 42/50 [06:18<00:46,  5.86s/it]

[I 2025-12-01 23:43:26,139] Trial 39 finished with value: 0.6816431322207959 and parameters: {'max_depth': 9, 'learning_rate': 0.07966813020521842, 'n_estimators': 1084, 'subsample': 0.7871923017715413, 'colsample_bytree': 0.590977636263794, 'min_child_weight': 9, 'gamma': 3.1586840930399616, 'reg_alpha': 0.0035584021220261028, 'reg_lambda': 0.0020756269898622483, 'max_delta_step': 8}. Best is trial 20 with value: 0.7342747111681642.

Best trial: 20. Best value: 0.734275:  86%|████████▌ | 43/50 [06:20<00:34,  4.99s/it]

[I 2025-12-01 23:43:28,675] Trial 42 pruned.

Best trial: 20. Best value: 0.734275:  88%|████████▊ | 44/50 [06:21<00:22,  3.82s/it]

[I 2025-12-01 23:43:29,377] Trial 43 pruned.

Best trial: 20. Best value: 0.734275:  90%|█████████ | 45/50 [06:22<00:15,  3.13s/it]

[I 2025-12-01 23:43:30,729] Trial 44 pruned.

Best trial: 20. Best value: 0.734275:  92%|█████████▏| 46/50 [06:26<00:12,  3.21s/it]

[I 2025-12-01 23:43:34,122] Trial 45 pruned.

Best trial: 20. Best value: 0.734275:  94%|█████████▍| 47/50 [06:32<00:12,  4.15s/it]

[I 2025-12-01 23:43:40,580] Trial 46 pruned.

Best trial: 20. Best value: 0.734275:  96%|█████████▌| 48/50 [06:33<00:06,  3.18s/it]

[I 2025-12-01 23:43:41,433] Trial 47 pruned.

Best trial: 20. Best value: 0.734275:  98%|█████████▊| 49/50 [06:34<00:02,  2.37s/it]

[I 2025-12-01 23:43:41,851] Trial 48 pruned.

Best trial: 20. Best value: 0.734275: 100%|██████████| 50/50 [06:46<00:00,  8.13s/it]

[I 2025-12-01 23:43:54,433] Trial 49 finished with value: 0.6046213093709885 and parameters: {'max_depth': 10, 'learning_rate': 0.09336141131409613, 'n_estimators': 1369, 'subsample': 0.7658935987756189, 'colsample_bytree': 0.6017625807300891, 'min_child_weight': 8, 'gamma': 3.589433086257229, 'reg_alpha': 1.4503718447977153e-05, 'reg_lambda': 2.057048590329999, 'max_delta_step': 2}. Best is trial 20 with value: 0.7342747111681642.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 23:43:57,293] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.444801:   2%|▏         | 1/50 [00:19<16:06, 19.72s/it]

[I 2025-12-01 23:44:17,006] Trial 0 finished with value: 0.444801026957638 and parameters: {'max_depth': 6, 'learning_rate': 0.06578922110262365, 'n_estimators': 331, 'subsample': 0.5395959381607256, 'colsample_bytree': 0.8525459751755511, 'min_child_weight': 1, 'gamma': 2.440499459225136, 'reg_alpha': 0.0029099208094276424, 'reg_lambda': 3.687900976233065e-08, 'max_delta_step': 7}. Best is trial 0 with value: 0.444801026957638.

Best trial: 3. Best value: 0.474968:   4%|▍         | 2/50 [00:39<15:59, 19.98s/it]

[I 2025-12-01 23:44:37,177] Trial 3 finished with value: 0.4749679075738126 and parameters: {'max_depth': 9, 'learning_rate': 0.25478306851260635, 'n_estimators': 799, 'subsample': 0.8711790411595637, 'colsample_bytree': 0.9033768071023325, 'min_child_weight': 7, 'gamma': 2.604607311555676, 'reg_alpha': 0.10997522084568441, 'reg_lambda': 0.5087524801156365, 'max_delta_step': 8}. Best is trial 3 with value: 0.4749679075738126.

Best trial: 1. Best value: 0.505135:   6%|▌         | 3/50 [00:41<08:56, 11.42s/it]

[I 2025-12-01 23:44:38,393] Trial 1 finished with value: 0.5051347881899871 and parameters: {'max_depth': 5, 'learning_rate': 0.19590746589755736, 'n_estimators': 830, 'subsample': 0.5067972627559914, 'colsample_bytree': 0.77393366389625, 'min_child_weight': 7, 'gamma': 4.238928319728286, 'reg_alpha': 3.1126969765294795e-08, 'reg_lambda': 1.0027256978207032e-06, 'max_delta_step': 1}. Best is trial 1 with value: 0.5051347881899871.

Best trial: 2. Best value: 0.513479:   8%|▊         | 4/50 [00:43<06:00,  7.84s/it]

[I 2025-12-01 23:44:40,757] Trial 2 finished with value: 0.5134788189987163 and parameters: {'max_depth': 6, 'learning_rate': 0.012959774610128032, 'n_estimators': 826, 'subsample': 0.885549566392444, 'colsample_bytree': 0.7680503870556061, 'min_child_weight': 7, 'gamma': 1.9964920101822858, 'reg_alpha': 0.15179866953212115, 'reg_lambda': 0.06546583770190828, 'max_delta_step': 6}. Best is trial 2 with value: 0.5134788189987163.

Best trial: 6. Best value: 0.523748:  10%|█         | 5/50 [00:58<07:52, 10.50s/it]

[I 2025-12-01 23:44:55,969] Trial 6 finished with value: 0.5237483953786906 and parameters: {'max_depth': 6, 'learning_rate': 0.12099806308241115, 'n_estimators': 317, 'subsample': 0.9775276671117156, 'colsample_bytree': 0.7221561532211194, 'min_child_weight': 1, 'gamma': 1.3475899746647761, 'reg_alpha': 0.09446504815305137, 'reg_lambda': 4.017746074606284e-05, 'max_delta_step': 4}. Best is trial 6 with value: 0.5237483953786906.

Best trial: 6. Best value: 0.523748:  12%|█▏        | 6/50 [01:23<11:22, 15.52s/it]

[I 2025-12-01 23:45:21,230] Trial 5 finished with value: 0.4608472400513479 and parameters: {'max_depth': 7, 'learning_rate': 0.11900242677779363, 'n_estimators': 897, 'subsample': 0.8149929120958161, 'colsample_bytree': 0.9853027274665771, 'min_child_weight': 6, 'gamma': 2.6374425066246947, 'reg_alpha': 0.3106556156185091, 'reg_lambda': 1.5763540338109112, 'max_delta_step': 4}. Best is trial 6 with value: 0.5237483953786906.

Best trial: 6. Best value: 0.523748:  14%|█▍        | 7/50 [01:24<07:37, 10.65s/it]

[I 2025-12-01 23:45:21,844] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.013309120071187052, 'n_estimators': 521, 'subsample': 0.7575526411399518, 'colsample_bytree': 0.6473229285036317, 'min_child_weight': 10, 'gamma': 4.178871715989117, 'reg_alpha': 0.008728845822983632, 'reg_lambda': 0.008855243743034162, 'max_delta_step': 3}. Best is trial 6 with value: 0.5237483953786906.

Best trial: 6. Best value: 0.523748:  16%|█▌        | 8/50 [01:39<08:29, 12.14s/it]

[I 2025-12-01 23:45:37,192] Trial 4 finished with value: 0.42233632862644416 and parameters: {'max_depth': 8, 'learning_rate': 0.016409641720396703, 'n_estimators': 1485, 'subsample': 0.5097397967171298, 'colsample_bytree': 0.6765978455507231, 'min_child_weight': 1, 'gamma': 1.9168205480700355, 'reg_alpha': 1.0363088477424026e-07, 'reg_lambda': 4.224732244213896, 'max_delta_step': 1}. Best is trial 6 with value: 0.5237483953786906.

Best trial: 6. Best value: 0.523748:  18%|█▊        | 9/50 [01:54<08:45, 12.81s/it]

[I 2025-12-01 23:45:51,484] Trial 11 finished with value: 0.4326059050064185 and parameters: {'max_depth': 10, 'learning_rate': 0.0595864669434089, 'n_estimators': 243, 'subsample': 0.8345696967141898, 'colsample_bytree': 0.6684583628910604, 'min_child_weight': 2, 'gamma': 2.8237146333869263, 'reg_alpha': 0.0002758332150490496, 'reg_lambda': 0.00023915034856946527, 'max_delta_step': 9}. Best is trial 6 with value: 0.5237483953786906.

Best trial: 6. Best value: 0.523748:  20%|██        | 10/50 [01:59<07:01, 10.53s/it]

[I 2025-12-01 23:45:56,908] Trial 7 finished with value: 0.45892169448010267 and parameters: {'max_depth': 8, 'learning_rate': 0.019407064044035402, 'n_estimators': 1447, 'subsample': 0.879955034983877, 'colsample_bytree': 0.7361659467767947, 'min_child_weight': 2, 'gamma': 1.8239211386885117, 'reg_alpha': 3.2764440962702594e-06, 'reg_lambda': 1.6801431173175117e-05, 'max_delta_step': 4}. Best is trial 6 with value: 0.5237483953786906.

Best trial: 6. Best value: 0.523748:  22%|██▏       | 11/50 [02:01<05:01,  7.74s/it]

[I 2025-12-01 23:45:58,317] Trial 10 pruned.

Best trial: 6. Best value: 0.523748:  24%|██▍       | 12/50 [02:19<06:52, 10.86s/it]

[I 2025-12-01 23:46:16,326] Trial 13 pruned.

Best trial: 6. Best value: 0.523748:  26%|██▌       | 13/50 [02:19<04:47,  7.78s/it]

[I 2025-12-01 23:46:17,022] Trial 14 pruned.

Best trial: 6. Best value: 0.523748:  28%|██▊       | 14/50 [02:24<04:07,  6.88s/it]

[I 2025-12-01 23:46:21,804] Trial 15 pruned.

Best trial: 6. Best value: 0.523748:  30%|███       | 15/50 [02:25<03:00,  5.17s/it]

[I 2025-12-01 23:46:23,005] Trial 9 finished with value: 0.503209242618742 and parameters: {'max_depth': 6, 'learning_rate': 0.014035993226812657, 'n_estimators': 1257, 'subsample': 0.5855649126927358, 'colsample_bytree': 0.5520005282217764, 'min_child_weight': 7, 'gamma': 1.3288154715552185, 'reg_alpha': 1.7097933044487517e-08, 'reg_lambda': 5.0631511032524e-07, 'max_delta_step': 6}. Best is trial 6 with value: 0.5237483953786906.

Best trial: 6. Best value: 0.523748:  32%|███▏      | 16/50 [02:29<02:46,  4.88s/it]

[I 2025-12-01 23:46:27,228] Trial 18 pruned.

Best trial: 16. Best value: 0.553915:  34%|███▍      | 17/50 [02:49<05:05,  9.25s/it]

[I 2025-12-01 23:46:46,629] Trial 16 finished with value: 0.5539152759948652 and parameters: {'max_depth': 5, 'learning_rate': 0.10039187867401446, 'n_estimators': 570, 'subsample': 0.9269484018190327, 'colsample_bytree': 0.8227723736793287, 'min_child_weight': 8, 'gamma': 0.9984010631988791, 'reg_alpha': 0.07604818172922102, 'reg_lambda': 0.04527196357878064, 'max_delta_step': 6}. Best is trial 16 with value: 0.5539152759948652.

Best trial: 16. Best value: 0.553915:  36%|███▌      | 18/50 [02:52<04:01,  7.54s/it]

[I 2025-12-01 23:46:50,208] Trial 20 pruned.

Best trial: 16. Best value: 0.553915:  38%|███▊      | 19/50 [02:54<02:53,  5.61s/it]

[I 2025-12-01 23:46:51,300] Trial 17 finished with value: 0.527599486521181 and parameters: {'max_depth': 5, 'learning_rate': 0.010448494680509124, 'n_estimators': 541, 'subsample': 0.9170386960322381, 'colsample_bytree': 0.8062981166434559, 'min_child_weight': 8, 'gamma': 1.1921162058559929, 'reg_alpha': 0.07897759316266617, 'reg_lambda': 6.201417081786019e-05, 'max_delta_step': 2}. Best is trial 16 with value: 0.5539152759948652.

Best trial: 12. Best value: 0.578306:  40%|████      | 20/50 [02:56<02:18,  4.62s/it]

[I 2025-12-01 23:46:53,607] Trial 12 finished with value: 0.5783055198973043 and parameters: {'max_depth': 6, 'learning_rate': 0.043476502552630275, 'n_estimators': 1239, 'subsample': 0.9373547356520806, 'colsample_bytree': 0.525995156841616, 'min_child_weight': 7, 'gamma': 3.318961027119869, 'reg_alpha': 1.1926444003341998e-06, 'reg_lambda': 0.03902815257271572, 'max_delta_step': 8}. Best is trial 12 with value: 0.5783055198973043.

Best trial: 12. Best value: 0.578306:  42%|████▏     | 21/50 [02:59<02:04,  4.31s/it]

[I 2025-12-01 23:46:57,193] Trial 22 pruned.

Best trial: 12. Best value: 0.578306:  44%|████▍     | 22/50 [03:04<02:01,  4.33s/it]

[I 2025-12-01 23:47:01,575] Trial 21 pruned.

Best trial: 12. Best value: 0.578306:  46%|████▌     | 23/50 [03:05<01:35,  3.52s/it]

[I 2025-12-01 23:47:03,181] Trial 19 finished with value: 0.4486521181001284 and parameters: {'max_depth': 7, 'learning_rate': 0.010353964935318006, 'n_estimators': 619, 'subsample': 0.9210432766887003, 'colsample_bytree': 0.8947945393870563, 'min_child_weight': 5, 'gamma': 1.0640933232072136, 'reg_alpha': 0.00010189148912178724, 'reg_lambda': 0.09248458096754852, 'max_delta_step': 0}. Best is trial 12 with value: 0.5783055198973043.

Best trial: 12. Best value: 0.578306:  48%|████▊     | 24/50 [03:23<03:18,  7.62s/it]

[I 2025-12-01 23:47:20,390] Trial 26 pruned.

Best trial: 12. Best value: 0.578306:  50%|█████     | 25/50 [03:36<03:52,  9.30s/it]

[I 2025-12-01 23:47:33,595] Trial 24 finished with value: 0.5661103979460848 and parameters: {'max_depth': 5, 'learning_rate': 0.021989224746969262, 'n_estimators': 672, 'subsample': 0.9384542251814948, 'colsample_bytree': 0.8253018580976841, 'min_child_weight': 8, 'gamma': 4.8914809987608265, 'reg_alpha': 1.1316423062638046e-06, 'reg_lambda': 0.0004684704996802658, 'max_delta_step': 8}. Best is trial 12 with value: 0.5783055198973043.

Best trial: 12. Best value: 0.578306:  52%|█████▏    | 26/50 [03:46<03:46,  9.45s/it]

[I 2025-12-01 23:47:43,403] Trial 27 pruned.

Best trial: 12. Best value: 0.578306:  54%|█████▍    | 27/50 [03:50<03:01,  7.89s/it]

[I 2025-12-01 23:47:47,658] Trial 23 finished with value: 0.4871630295250321 and parameters: {'max_depth': 7, 'learning_rate': 0.025528996855323435, 'n_estimators': 1024, 'subsample': 0.7837514148967832, 'colsample_bytree': 0.6110101779289644, 'min_child_weight': 5, 'gamma': 3.5552433420399283, 'reg_alpha': 4.991227216427174e-07, 'reg_lambda': 0.15572659943549758, 'max_delta_step': 10}. Best is trial 12 with value: 0.5783055198973043.

Best trial: 12. Best value: 0.578306:  56%|█████▌    | 28/50 [04:12<04:29, 12.27s/it]

[I 2025-12-01 23:48:10,144] Trial 25 finished with value: 0.527599486521181 and parameters: {'max_depth': 7, 'learning_rate': 0.02295705193992822, 'n_estimators': 1321, 'subsample': 0.9176560475130099, 'colsample_bytree': 0.8366480604374623, 'min_child_weight': 8, 'gamma': 3.4554305039286692, 'reg_alpha': 1.915015916238406e-06, 'reg_lambda': 0.0011777963945773494, 'max_delta_step': 8}. Best is trial 12 with value: 0.5783055198973043.

Best trial: 28. Best value: 0.592426:  58%|█████▊    | 29/50 [04:14<03:11,  9.10s/it]

[I 2025-12-01 23:48:11,864] Trial 28 finished with value: 0.5924261874197689 and parameters: {'max_depth': 7, 'learning_rate': 0.04299734619596325, 'n_estimators': 739, 'subsample': 0.8643486068449078, 'colsample_bytree': 0.5942487998198177, 'min_child_weight': 9, 'gamma': 4.7531872430900775, 'reg_alpha': 6.432920724162231e-07, 'reg_lambda': 0.0008790841403491023, 'max_delta_step': 10}. Best is trial 28 with value: 0.5924261874197689.

Best trial: 28. Best value: 0.592426:  60%|██████    | 30/50 [04:21<02:47,  8.38s/it]

[I 2025-12-01 23:48:18,558] Trial 32 pruned.

Best trial: 28. Best value: 0.592426:  62%|██████▏   | 31/50 [04:25<02:16,  7.16s/it]

[I 2025-12-01 23:48:22,869] Trial 29 finished with value: 0.48908857509627723 and parameters: {'max_depth': 4, 'learning_rate': 0.020816476158709976, 'n_estimators': 727, 'subsample': 0.8610597451677692, 'colsample_bytree': 0.8487727662322615, 'min_child_weight': 6, 'gamma': 4.781826188289765, 'reg_alpha': 3.2986565550954457e-07, 'reg_lambda': 0.28475334703985977, 'max_delta_step': 7}. Best is trial 28 with value: 0.5924261874197689.

Best trial: 30. Best value: 0.618742:  66%|██████▌   | 33/50 [04:29<01:15,  4.42s/it]

[I 2025-12-01 23:48:27,037] Trial 30 finished with value: 0.6187419768934532 and parameters: {'max_depth': 4, 'learning_rate': 0.0795203412568577, 'n_estimators': 740, 'subsample': 0.8524578153215043, 'colsample_bytree': 0.8515149335296472, 'min_child_weight': 9, 'gamma': 4.994967859350454, 'reg_alpha': 1.3995787009557176e-05, 'reg_lambda': 0.017353592898816154, 'max_delta_step': 7}. Best is trial 30 with value: 0.6187419768934532.
[I 2025-12-01 23:48:27,157] Trial 34 pruned.

Best trial: 30. Best value: 0.618742:  70%|███████   | 35/50 [04:38<00:59,  3.96s/it]

[I 2025-12-01 23:48:35,534] Trial 35 pruned.
[I 2025-12-01 23:48:35,659] Trial 36 pruned.

Best trial: 30. Best value: 0.618742:  72%|███████▏  | 36/50 [04:44<01:05,  4.67s/it]

[I 2025-12-01 23:48:41,991] Trial 37 pruned.

Best trial: 30. Best value: 0.618742:  74%|███████▍  | 37/50 [04:50<01:06,  5.11s/it]

[I 2025-12-01 23:48:48,123] Trial 31 finished with value: 0.5154043645699615 and parameters: {'max_depth': 4, 'learning_rate': 0.0860176425747864, 'n_estimators': 699, 'subsample': 0.6814065746498542, 'colsample_bytree': 0.9389854395018351, 'min_child_weight': 6, 'gamma': 4.7850112561584055, 'reg_alpha': 1.4181859539416644e-05, 'reg_lambda': 0.02477229610555276, 'max_delta_step': 7}. Best is trial 30 with value: 0.6187419768934532.

Best trial: 30. Best value: 0.618742:  76%|███████▌  | 38/50 [05:12<02:01, 10.14s/it]

[I 2025-12-01 23:49:09,991] Trial 33 finished with value: 0.5134788189987163 and parameters: {'max_depth': 7, 'learning_rate': 0.041559813072085006, 'n_estimators': 964, 'subsample': 0.8420792965558399, 'colsample_bytree': 0.6244210186228764, 'min_child_weight': 6, 'gamma': 4.35038382608622, 'reg_alpha': 1.286494082174987e-07, 'reg_lambda': 1.1354419783546172e-05, 'max_delta_step': 7}. Best is trial 30 with value: 0.6187419768934532.

Best trial: 30. Best value: 0.618742:  78%|███████▊  | 39/50 [05:17<01:35,  8.64s/it]

[I 2025-12-01 23:49:15,146] Trial 38 finished with value: 0.5661103979460848 and parameters: {'max_depth': 6, 'learning_rate': 0.07530623616922567, 'n_estimators': 757, 'subsample': 0.8953829674239051, 'colsample_bytree': 0.773149957463213, 'min_child_weight': 7, 'gamma': 3.944890479137222, 'reg_alpha': 1.6649782308117996e-07, 'reg_lambda': 1.1003975271352432e-08, 'max_delta_step': 7}. Best is trial 30 with value: 0.6187419768934532.

Best trial: 30. Best value: 0.618742:  80%|████████  | 40/50 [05:24<01:21,  8.18s/it]

[I 2025-12-01 23:49:22,230] Trial 42 pruned.

Best trial: 30. Best value: 0.618742:  82%|████████▏ | 41/50 [05:28<01:00,  6.77s/it]

[I 2025-12-01 23:49:25,716] Trial 39 finished with value: 0.5012836970474968 and parameters: {'max_depth': 5, 'learning_rate': 0.06625173266235569, 'n_estimators': 828, 'subsample': 0.800978938659441, 'colsample_bytree': 0.7870324359176496, 'min_child_weight': 7, 'gamma': 3.801381078024196, 'reg_alpha': 5.888238277396096e-05, 'reg_lambda': 4.053805531628784e-08, 'max_delta_step': 7}. Best is trial 30 with value: 0.6187419768934532.

Best trial: 30. Best value: 0.618742:  84%|████████▍ | 42/50 [05:32<00:48,  6.06s/it]

[I 2025-12-01 23:49:30,122] Trial 43 pruned.

Best trial: 30. Best value: 0.618742:  86%|████████▌ | 43/50 [05:33<00:30,  4.40s/it]

[I 2025-12-01 23:49:30,665] Trial 40 finished with value: 0.5154043645699615 and parameters: {'max_depth': 5, 'learning_rate': 0.06014285377337968, 'n_estimators': 803, 'subsample': 0.7959225724521662, 'colsample_bytree': 0.7101426079609943, 'min_child_weight': 7, 'gamma': 3.888922079582633, 'reg_alpha': 5.540935969116432e-05, 'reg_lambda': 0.4885871359111144, 'max_delta_step': 5}. Best is trial 30 with value: 0.6187419768934532.

Best trial: 30. Best value: 0.618742:  88%|████████▊ | 44/50 [05:39<00:29,  4.97s/it]

[I 2025-12-01 23:49:36,949] Trial 45 pruned.
[I 2025-12-01 23:49:36,959] Trial 46 pruned.

Best trial: 30. Best value: 0.618742:  92%|█████████▏| 46/50 [05:48<00:18,  4.65s/it]

[I 2025-12-01 23:49:45,512] Trial 47 pruned.
[I 2025-12-01 23:49:45,520] Trial 48 pruned.

Best trial: 30. Best value: 0.618742:  96%|█████████▌| 48/50 [05:51<00:06,  3.36s/it]

[I 2025-12-01 23:49:48,300] Trial 49 pruned.

Best trial: 30. Best value: 0.618742:  98%|█████████▊| 49/50 [05:52<00:03,  3.01s/it]

[I 2025-12-01 23:49:50,080] Trial 41 finished with value: 0.527599486521181 and parameters: {'max_depth': 5, 'learning_rate': 0.06281122102331868, 'n_estimators': 819, 'subsample': 0.7967750910338549, 'colsample_bytree': 0.7872527969901162, 'min_child_weight': 7, 'gamma': 3.7942833742440545, 'reg_alpha': 5.37902918840034e-05, 'reg_lambda': 0.37702276523792416, 'max_delta_step': 5}. Best is trial 30 with value: 0.6187419768934532.

Best trial: 30. Best value: 0.618742: 100%|██████████| 50/50 [05:56<00:00,  7.12s/it]

[I 2025-12-01 23:49:53,350] Trial 44 finished with value: 0.5397946084724006 and parameters: {'max_depth': 6, 'learning_rate': 0.05633221720785295, 'n_estimators': 771, 'subsample': 0.8887546897518187, 'colsample_bytree': 0.7156271207429594, 'min_child_weight': 7, 'gamma': 2.9868275859859503, 'reg_alpha': 8.135716016707407e-07, 'reg_lambda': 1.0864151377991124e-08, 'max_delta_step': 8}. Best is trial 30 with value: 0.6187419768934532.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-01 23:49:56,167] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.562259:   2%|▏         | 1/50 [00:16<13:24, 16.41s/it]

[I 2025-12-01 23:50:12,571] Trial 1 finished with value: 0.5622593068035944 and parameters: {'max_depth': 9, 'learning_rate': 0.2942799833996056, 'n_estimators': 286, 'subsample': 0.9993319700474985, 'colsample_bytree': 0.995745197984423, 'min_child_weight': 3, 'gamma': 1.8880779196246706, 'reg_alpha': 0.0012878616143996119, 'reg_lambda': 0.0002857374540503917, 'max_delta_step': 4}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:   4%|▍         | 2/50 [00:21<07:52,  9.83s/it]

[I 2025-12-01 23:50:17,801] Trial 3 finished with value: 0.4807445442875481 and parameters: {'max_depth': 3, 'learning_rate': 0.01980609115826157, 'n_estimators': 401, 'subsample': 0.5873765551705179, 'colsample_bytree': 0.9822357699798894, 'min_child_weight': 7, 'gamma': 0.33900355551714445, 'reg_alpha': 2.905382360051955e-08, 'reg_lambda': 1.834211577813827e-07, 'max_delta_step': 7}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:   6%|▌         | 3/50 [00:34<08:46, 11.21s/it]

[I 2025-12-01 23:50:30,634] Trial 4 finished with value: 0.48523748395378685 and parameters: {'max_depth': 6, 'learning_rate': 0.06653243416706656, 'n_estimators': 313, 'subsample': 0.6241486437564667, 'colsample_bytree': 0.8270689859718522, 'min_child_weight': 2, 'gamma': 1.2206249659330204, 'reg_alpha': 2.340624981855024, 'reg_lambda': 0.010341816313933739, 'max_delta_step': 5}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:   8%|▊         | 4/50 [00:41<07:21,  9.59s/it]

[I 2025-12-01 23:50:37,765] Trial 5 finished with value: 0.4467265725288832 and parameters: {'max_depth': 10, 'learning_rate': 0.08127554298993585, 'n_estimators': 362, 'subsample': 0.7989212850254053, 'colsample_bytree': 0.9834715805720333, 'min_child_weight': 5, 'gamma': 0.5241815697667168, 'reg_alpha': 2.3770358629442503e-05, 'reg_lambda': 1.5020421091391721e-06, 'max_delta_step': 3}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:  10%|█         | 5/50 [00:42<04:51,  6.47s/it]

[I 2025-12-01 23:50:38,707] Trial 0 finished with value: 0.3876765083440308 and parameters: {'max_depth': 10, 'learning_rate': 0.012144999948414467, 'n_estimators': 798, 'subsample': 0.8382929717900918, 'colsample_bytree': 0.8719886696710841, 'min_child_weight': 6, 'gamma': 2.638906367561082, 'reg_alpha': 0.049551963053238765, 'reg_lambda': 2.7529084901326865e-05, 'max_delta_step': 10}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:  12%|█▏        | 6/50 [00:44<03:34,  4.87s/it]

[I 2025-12-01 23:50:40,462] Trial 2 finished with value: 0.5051347881899871 and parameters: {'max_depth': 9, 'learning_rate': 0.026943737304835323, 'n_estimators': 900, 'subsample': 0.676790124170257, 'colsample_bytree': 0.7829232024579029, 'min_child_weight': 8, 'gamma': 3.2248581325012053, 'reg_alpha': 0.00017678373233075563, 'reg_lambda': 0.013091320859531836, 'max_delta_step': 6}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:  14%|█▍        | 7/50 [00:56<05:19,  7.42s/it]

[I 2025-12-01 23:50:53,145] Trial 9 finished with value: 0.5096277278562259 and parameters: {'max_depth': 7, 'learning_rate': 0.04228293891233395, 'n_estimators': 203, 'subsample': 0.5832423398056938, 'colsample_bytree': 0.5210314160198222, 'min_child_weight': 1, 'gamma': 3.0547748389558214, 'reg_alpha': 0.10026771532388441, 'reg_lambda': 0.00011943421111910306, 'max_delta_step': 9}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:  16%|█▌        | 8/50 [01:29<10:52, 15.54s/it]

[I 2025-12-01 23:51:26,066] Trial 6 finished with value: 0.41014120667522463 and parameters: {'max_depth': 3, 'learning_rate': 0.06992179033380892, 'n_estimators': 1107, 'subsample': 0.7103138859964144, 'colsample_bytree': 0.5690615415748494, 'min_child_weight': 7, 'gamma': 3.981147040003223, 'reg_alpha': 3.657469593844543, 'reg_lambda': 0.011110054409764657, 'max_delta_step': 6}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:  18%|█▊        | 9/50 [01:35<08:33, 12.53s/it]

[I 2025-12-01 23:51:31,980] Trial 8 finished with value: 0.5096277278562259 and parameters: {'max_depth': 10, 'learning_rate': 0.05442967821887543, 'n_estimators': 1016, 'subsample': 0.9673207689415988, 'colsample_bytree': 0.8492159881009715, 'min_child_weight': 4, 'gamma': 0.23553316878685893, 'reg_alpha': 4.6803138885927226e-05, 'reg_lambda': 1.128534884286989, 'max_delta_step': 6}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:  20%|██        | 10/50 [01:50<08:49, 13.24s/it]

[I 2025-12-01 23:51:46,811] Trial 7 finished with value: 0.46277278562259305 and parameters: {'max_depth': 9, 'learning_rate': 0.026534580895696387, 'n_estimators': 1376, 'subsample': 0.6091793537772849, 'colsample_bytree': 0.8026344067144565, 'min_child_weight': 6, 'gamma': 4.394759346859233, 'reg_alpha': 0.25267873559310106, 'reg_lambda': 9.932430084158996e-07, 'max_delta_step': 4}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:  22%|██▏       | 11/50 [01:56<07:03, 10.87s/it]

[I 2025-12-01 23:51:52,296] Trial 13 pruned.

Best trial: 1. Best value: 0.562259:  24%|██▍       | 12/50 [02:07<07:03, 11.15s/it]

[I 2025-12-01 23:52:04,091] Trial 10 finished with value: 0.48908857509627723 and parameters: {'max_depth': 3, 'learning_rate': 0.21879356396110475, 'n_estimators': 1408, 'subsample': 0.7792994064856174, 'colsample_bytree': 0.912505668396743, 'min_child_weight': 3, 'gamma': 4.474290331676492, 'reg_alpha': 5.007821675967318e-05, 'reg_lambda': 0.3737865254617706, 'max_delta_step': 5}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:  26%|██▌       | 13/50 [02:14<06:01,  9.76s/it]

[I 2025-12-01 23:52:10,647] Trial 12 finished with value: 0.48523748395378685 and parameters: {'max_depth': 8, 'learning_rate': 0.10227895031657643, 'n_estimators': 764, 'subsample': 0.6376634380603479, 'colsample_bytree': 0.5475259322306393, 'min_child_weight': 4, 'gamma': 1.0721724195023636, 'reg_alpha': 0.009193408545285385, 'reg_lambda': 6.882820628380854e-07, 'max_delta_step': 9}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:  28%|██▊       | 14/50 [02:26<06:15, 10.44s/it]

[I 2025-12-01 23:52:22,668] Trial 11 finished with value: 0.5237483953786906 and parameters: {'max_depth': 5, 'learning_rate': 0.06916126552522725, 'n_estimators': 1103, 'subsample': 0.9833849379785466, 'colsample_bytree': 0.7423253850156866, 'min_child_weight': 3, 'gamma': 2.868713776665407, 'reg_alpha': 1.6445891611616912e-06, 'reg_lambda': 0.1889622418195231, 'max_delta_step': 6}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 14. Best value: 0.574454:  30%|███       | 15/50 [02:57<09:40, 16.58s/it]

[I 2025-12-01 23:52:53,490] Trial 14 finished with value: 0.5744544287548139 and parameters: {'max_depth': 8, 'learning_rate': 0.16126494929734245, 'n_estimators': 1176, 'subsample': 0.9910805046711011, 'colsample_bytree': 0.9011504847756483, 'min_child_weight': 3, 'gamma': 1.6057102944336759, 'reg_alpha': 5.099627061327975e-06, 'reg_lambda': 3.2818500170787894, 'max_delta_step': 1}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  32%|███▏      | 16/50 [03:01<07:13, 12.75s/it]

[I 2025-12-01 23:52:57,319] Trial 15 finished with value: 0.4486521181001284 and parameters: {'max_depth': 8, 'learning_rate': 0.1422969570918183, 'n_estimators': 1085, 'subsample': 0.9766832594783157, 'colsample_bytree': 0.6872917983760042, 'min_child_weight': 4, 'gamma': 1.6444068850093423, 'reg_alpha': 0.003346841665130739, 'reg_lambda': 8.613036849005322, 'max_delta_step': 0}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  34%|███▍      | 17/50 [03:10<06:23, 11.62s/it]

[I 2025-12-01 23:53:06,309] Trial 16 finished with value: 0.5500641848523748 and parameters: {'max_depth': 9, 'learning_rate': 0.1254861738209199, 'n_estimators': 1107, 'subsample': 0.9967408423725522, 'colsample_bytree': 0.7147882332595707, 'min_child_weight': 3, 'gamma': 1.89552045268058, 'reg_alpha': 1.4682232149093438e-06, 'reg_lambda': 9.33840296476961, 'max_delta_step': 0}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  36%|███▌      | 18/50 [03:26<06:59, 13.12s/it]

[I 2025-12-01 23:53:22,924] Trial 17 finished with value: 0.5622593068035944 and parameters: {'max_depth': 6, 'learning_rate': 0.14964745716219097, 'n_estimators': 1215, 'subsample': 0.8756984785721409, 'colsample_bytree': 0.7158011972348175, 'min_child_weight': 1, 'gamma': 2.0298284407043643, 'reg_alpha': 9.24887295384054e-07, 'reg_lambda': 0.0009676986258723141, 'max_delta_step': 0}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  38%|███▊      | 19/50 [03:28<04:58,  9.63s/it]

[I 2025-12-01 23:53:24,427] Trial 19 finished with value: 0.4608472400513479 and parameters: {'max_depth': 8, 'learning_rate': 0.15826854536624446, 'n_estimators': 524, 'subsample': 0.8783231150993206, 'colsample_bytree': 0.928616508034181, 'min_child_weight': 1, 'gamma': 2.11834761227938, 'reg_alpha': 8.623624223091861e-07, 'reg_lambda': 0.001040174283634998, 'max_delta_step': 0}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  40%|████      | 20/50 [03:32<03:58,  7.96s/it]

[I 2025-12-01 23:53:28,481] Trial 21 pruned.

Best trial: 14. Best value: 0.574454:  42%|████▏     | 21/50 [03:37<03:30,  7.24s/it]

[I 2025-12-01 23:53:34,063] Trial 20 finished with value: 0.5378690629011553 and parameters: {'max_depth': 8, 'learning_rate': 0.19250456016610573, 'n_estimators': 540, 'subsample': 0.8875904932182547, 'colsample_bytree': 0.9264277071080917, 'min_child_weight': 2, 'gamma': 2.255614104812046, 'reg_alpha': 1.2072079230832573e-06, 'reg_lambda': 0.0010421289606247182, 'max_delta_step': 2}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  44%|████▍     | 22/50 [03:38<02:27,  5.27s/it]

[I 2025-12-01 23:53:34,746] Trial 22 pruned.

Best trial: 14. Best value: 0.574454:  46%|████▌     | 23/50 [04:03<05:05, 11.31s/it]

[I 2025-12-01 23:54:00,124] Trial 18 finished with value: 0.5378690629011553 and parameters: {'max_depth': 8, 'learning_rate': 0.14537506872340264, 'n_estimators': 1269, 'subsample': 0.8788115892190582, 'colsample_bytree': 0.9140433124895285, 'min_child_weight': 1, 'gamma': 1.8846301662372174, 'reg_alpha': 0.0020188713212875723, 'reg_lambda': 9.313019150111044, 'max_delta_step': 0}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  48%|████▊     | 24/50 [04:38<07:53, 18.19s/it]

[I 2025-12-01 23:54:34,388] Trial 23 finished with value: 0.4871630295250321 and parameters: {'max_depth': 5, 'learning_rate': 0.20282786737999484, 'n_estimators': 1296, 'subsample': 0.9196667377539063, 'colsample_bytree': 0.9964022571344286, 'min_child_weight': 2, 'gamma': 2.3876820320377767, 'reg_alpha': 7.464527007923738e-06, 'reg_lambda': 0.05286454499346997, 'max_delta_step': 2}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  50%|█████     | 25/50 [04:40<05:33, 13.33s/it]

[I 2025-12-01 23:54:36,381] Trial 25 finished with value: 0.5359435173299101 and parameters: {'max_depth': 6, 'learning_rate': 0.20219969296627002, 'n_estimators': 1262, 'subsample': 0.9126287597598217, 'colsample_bytree': 0.613535865590631, 'min_child_weight': 2, 'gamma': 1.5651091018043108, 'reg_alpha': 1.7688496121098977e-07, 'reg_lambda': 0.00030701628277825683, 'max_delta_step': 1}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  52%|█████▏    | 26/50 [04:43<04:05, 10.21s/it]

[I 2025-12-01 23:54:39,313] Trial 24 finished with value: 0.5744544287548139 and parameters: {'max_depth': 5, 'learning_rate': 0.19993696667715027, 'n_estimators': 1272, 'subsample': 0.920349336088878, 'colsample_bytree': 0.6352131980640937, 'min_child_weight': 2, 'gamma': 3.535062807973933, 'reg_alpha': 1.4330376364224546e-07, 'reg_lambda': 0.00020224892321726306, 'max_delta_step': 1}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  54%|█████▍    | 27/50 [04:45<03:01,  7.91s/it]

[I 2025-12-01 23:54:41,840] Trial 27 pruned.

Best trial: 14. Best value: 0.574454:  56%|█████▌    | 28/50 [04:48<02:21,  6.42s/it]

[I 2025-12-01 23:54:44,801] Trial 28 pruned.

Best trial: 14. Best value: 0.574454:  58%|█████▊    | 29/50 [05:07<03:33, 10.16s/it]

[I 2025-12-01 23:55:03,698] Trial 26 finished with value: 0.5378690629011553 and parameters: {'max_depth': 6, 'learning_rate': 0.2229030559261957, 'n_estimators': 1245, 'subsample': 0.9308986885009531, 'colsample_bytree': 0.6295456399092301, 'min_child_weight': 2, 'gamma': 3.5534119711603536, 'reg_alpha': 1.5200798058477135e-07, 'reg_lambda': 0.0005128500325718321, 'max_delta_step': 1}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  60%|██████    | 30/50 [05:57<07:19, 21.98s/it]

[I 2025-12-01 23:55:53,229] Trial 29 finished with value: 0.511553273427471 and parameters: {'max_depth': 4, 'learning_rate': 0.10500259871455334, 'n_estimators': 1496, 'subsample': 0.9351285336287708, 'colsample_bytree': 0.6212302998078791, 'min_child_weight': 5, 'gamma': 3.513702734428525, 'reg_alpha': 1.093302624174272e-07, 'reg_lambda': 0.00010146306209663988, 'max_delta_step': 4}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  62%|██████▏   | 31/50 [05:59<05:04, 16.00s/it]

[I 2025-12-01 23:55:55,293] Trial 31 finished with value: 0.46277278562259305 and parameters: {'max_depth': 4, 'learning_rate': 0.2249527060821555, 'n_estimators': 1395, 'subsample': 0.8404632280709325, 'colsample_bytree': 0.9691417905264285, 'min_child_weight': 3, 'gamma': 4.893527842517379, 'reg_alpha': 9.114297086087996e-06, 'reg_lambda': 5.0547412282212834e-05, 'max_delta_step': 3}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  64%|██████▍   | 32/50 [05:59<03:24, 11.34s/it]

[I 2025-12-01 23:55:55,767] Trial 30 finished with value: 0.4871630295250321 and parameters: {'max_depth': 4, 'learning_rate': 0.09553066789665281, 'n_estimators': 1460, 'subsample': 0.8282074307725179, 'colsample_bytree': 0.9565783047006258, 'min_child_weight': 3, 'gamma': 3.468453716482357, 'reg_alpha': 6.9531882607147035e-06, 'reg_lambda': 5.229761452044279e-05, 'max_delta_step': 4}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  66%|██████▌   | 33/50 [06:23<04:16, 15.07s/it]

[I 2025-12-01 23:56:19,520] Trial 32 finished with value: 0.511553273427471 and parameters: {'max_depth': 4, 'learning_rate': 0.012799749158524764, 'n_estimators': 1438, 'subsample': 0.8398086095124122, 'colsample_bytree': 0.9530531433907713, 'min_child_weight': 3, 'gamma': 2.5143233434130727, 'reg_alpha': 9.732838681151941e-06, 'reg_lambda': 5.434420805276864e-05, 'max_delta_step': 3}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  68%|██████▊   | 34/50 [06:33<03:38, 13.64s/it]

[I 2025-12-01 23:56:29,843] Trial 36 pruned.

Best trial: 14. Best value: 0.574454:  70%|███████   | 35/50 [06:37<02:39, 10.63s/it]

[I 2025-12-01 23:56:33,446] Trial 33 finished with value: 0.4345314505776637 and parameters: {'max_depth': 4, 'learning_rate': 0.17513929410185622, 'n_estimators': 789, 'subsample': 0.8191397547193677, 'colsample_bytree': 0.9666530346768157, 'min_child_weight': 4, 'gamma': 4.927934376028148, 'reg_alpha': 6.711783464032904e-06, 'reg_lambda': 5.930967796661003e-06, 'max_delta_step': 3}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  72%|███████▏  | 36/50 [06:45<02:20, 10.02s/it]

[I 2025-12-01 23:56:42,038] Trial 38 pruned.

Best trial: 14. Best value: 0.574454:  74%|███████▍  | 37/50 [06:59<02:23, 11.03s/it]

[I 2025-12-01 23:56:55,414] Trial 35 finished with value: 0.5237483953786906 and parameters: {'max_depth': 9, 'learning_rate': 0.16339531725487913, 'n_estimators': 1169, 'subsample': 0.9932062543748672, 'colsample_bytree': 0.6924424865018619, 'min_child_weight': 4, 'gamma': 2.731923976198974, 'reg_alpha': 0.00014988340296436388, 'reg_lambda': 0.004307164724385023, 'max_delta_step': 1}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  76%|███████▌  | 38/50 [07:00<01:35,  7.98s/it]

[I 2025-12-01 23:56:56,288] Trial 34 finished with value: 0.5237483953786906 and parameters: {'max_depth': 4, 'learning_rate': 0.17208229655202376, 'n_estimators': 1198, 'subsample': 0.8358046985813458, 'colsample_bytree': 0.6783969157829717, 'min_child_weight': 3, 'gamma': 2.7381152931592982, 'reg_alpha': 0.00025476920150844693, 'reg_lambda': 4.262806423912561e-06, 'max_delta_step': 1}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  78%|███████▊  | 39/50 [07:10<01:35,  8.67s/it]

[I 2025-12-01 23:57:06,581] Trial 40 pruned.

Best trial: 14. Best value: 0.574454:  80%|████████  | 40/50 [07:14<01:13,  7.32s/it]

[I 2025-12-01 23:57:10,727] Trial 37 finished with value: 0.5237483953786906 and parameters: {'max_depth': 5, 'learning_rate': 0.2520832186547127, 'n_estimators': 797, 'subsample': 0.9594388407297123, 'colsample_bytree': 0.7796145234828444, 'min_child_weight': 4, 'gamma': 0.6203108582990824, 'reg_alpha': 0.00012347859709872889, 'reg_lambda': 0.003282347440324535, 'max_delta_step': 1}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  82%|████████▏ | 41/50 [07:27<01:22,  9.12s/it]

[I 2025-12-01 23:57:24,044] Trial 43 finished with value: 0.5359435173299101 and parameters: {'max_depth': 7, 'learning_rate': 0.04834328767001834, 'n_estimators': 209, 'subsample': 0.8959147044902644, 'colsample_bytree': 0.842052214520396, 'min_child_weight': 2, 'gamma': 2.1632403806452425, 'reg_alpha': 1.05584576451819, 'reg_lambda': 0.03433670909673996, 'max_delta_step': 7}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 14. Best value: 0.574454:  84%|████████▍ | 42/50 [07:43<01:29, 11.17s/it]

[I 2025-12-01 23:57:40,018] Trial 39 finished with value: 0.5096277278562259 and parameters: {'max_depth': 5, 'learning_rate': 0.12610606437103924, 'n_estimators': 1167, 'subsample': 0.9527399767151088, 'colsample_bytree': 0.7955771977598578, 'min_child_weight': 2, 'gamma': 0.71019296467613, 'reg_alpha': 0.009966591224447234, 'reg_lambda': 0.026047708122012656, 'max_delta_step': 7}. Best is trial 14 with value: 0.5744544287548139.

Best trial: 41. Best value: 0.58665:  86%|████████▌ | 43/50 [07:45<00:58,  8.34s/it]

[I 2025-12-01 23:57:41,752] Trial 41 finished with value: 0.5866495507060334 and parameters: {'max_depth': 5, 'learning_rate': 0.043519944019217126, 'n_estimators': 887, 'subsample': 0.951730735808178, 'colsample_bytree': 0.7974095593249222, 'min_child_weight': 2, 'gamma': 2.1755648465466266, 'reg_alpha': 3.485981796147566e-08, 'reg_lambda': 0.05088913965394236, 'max_delta_step': 7}. Best is trial 41 with value: 0.5866495507060334.

Best trial: 41. Best value: 0.58665:  88%|████████▊ | 44/50 [07:55<00:53,  8.87s/it]

[I 2025-12-01 23:57:51,851] Trial 42 finished with value: 0.5481386392811296 and parameters: {'max_depth': 7, 'learning_rate': 0.042063427852719944, 'n_estimators': 880, 'subsample': 0.8972048438374058, 'colsample_bytree': 0.8747609776473276, 'min_child_weight': 2, 'gamma': 1.4147026023840383, 'reg_alpha': 5.97347414591526e-07, 'reg_lambda': 0.02606980644525869, 'max_delta_step': 0}. Best is trial 41 with value: 0.5866495507060334.

Best trial: 41. Best value: 0.58665:  90%|█████████ | 45/50 [08:24<01:13, 14.71s/it]

[I 2025-12-01 23:58:20,186] Trial 44 finished with value: 0.4974326059050064 and parameters: {'max_depth': 9, 'learning_rate': 0.11970428982636545, 'n_estimators': 1133, 'subsample': 0.8633139719448998, 'colsample_bytree': 0.7339574252231775, 'min_child_weight': 2, 'gamma': 1.415552171089722, 'reg_alpha': 6.348887153292674e-07, 'reg_lambda': 2.6314376134751813, 'max_delta_step': 0}. Best is trial 41 with value: 0.5866495507060334.

Best trial: 41. Best value: 0.58665:  92%|█████████▏| 46/50 [08:30<00:49, 12.31s/it]

[I 2025-12-01 23:58:26,907] Trial 46 finished with value: 0.5378690629011553 and parameters: {'max_depth': 6, 'learning_rate': 0.037521840587404716, 'n_estimators': 871, 'subsample': 0.8559792041495647, 'colsample_bytree': 0.8194396967410612, 'min_child_weight': 1, 'gamma': 3.112595141456902, 'reg_alpha': 3.833271022616311e-07, 'reg_lambda': 1.8939398012275683, 'max_delta_step': 9}. Best is trial 41 with value: 0.5866495507060334.

Best trial: 41. Best value: 0.58665:  94%|█████████▍| 47/50 [08:35<00:30, 10.02s/it]

[I 2025-12-01 23:58:31,574] Trial 45 finished with value: 0.5237483953786906 and parameters: {'max_depth': 9, 'learning_rate': 0.12752844456136614, 'n_estimators': 1050, 'subsample': 0.9987095024190027, 'colsample_bytree': 0.7387374396251203, 'min_child_weight': 1, 'gamma': 1.9083589546291169, 'reg_alpha': 4.923326662747796e-07, 'reg_lambda': 2.5138030001342115, 'max_delta_step': 0}. Best is trial 41 with value: 0.5866495507060334.

Best trial: 41. Best value: 0.58665:  96%|█████████▌| 48/50 [08:44<00:19,  9.88s/it]

[I 2025-12-01 23:58:41,131] Trial 47 finished with value: 0.511553273427471 and parameters: {'max_depth': 6, 'learning_rate': 0.030804469198093733, 'n_estimators': 1038, 'subsample': 0.9767306655276936, 'colsample_bytree': 0.7295010764305125, 'min_child_weight': 1, 'gamma': 3.0509016401767877, 'reg_alpha': 3.744847536818147e-08, 'reg_lambda': 1.2011385313408054, 'max_delta_step': 8}. Best is trial 41 with value: 0.5866495507060334.

Best trial: 41. Best value: 0.58665:  98%|█████████▊| 49/50 [08:57<00:10, 10.79s/it]

[I 2025-12-01 23:58:54,030] Trial 48 finished with value: 0.5622593068035944 and parameters: {'max_depth': 6, 'learning_rate': 0.07815322638763988, 'n_estimators': 1041, 'subsample': 0.9735402788059412, 'colsample_bytree': 0.8191540306458046, 'min_child_weight': 1, 'gamma': 3.132622729580584, 'reg_alpha': 1.3539627319185906e-08, 'reg_lambda': 0.20041665644171971, 'max_delta_step': 8}. Best is trial 41 with value: 0.5866495507060334.

Best trial: 41. Best value: 0.58665: 100%|██████████| 50/50 [08:59<00:00, 10.80s/it]

[I 2025-12-01 23:58:56,073] Trial 49 finished with value: 0.48523748395378685 and parameters: {'max_depth': 6, 'learning_rate': 0.03045261322288313, 'n_estimators': 1043, 'subsample': 0.7848343850718101, 'colsample_bytree': 0.5692836793632692, 'min_child_weight': 1, 'gamma': 1.92214594507814, 'reg_alpha': 2.9644735978860705e-08, 'reg_lambda': 0.18633901119843616, 'max_delta_step': 8}. Best is trial 41 with value: 0.5866495507060334.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.734275                    0.75          0.80
1    17_1         loo       0.618742                    0.60          0.52
2     9_1         loo       0.695764                    0.60          0.62
3    19_1         loo       0.586650                    0.50          0.60

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.500000               1.0               0.5        50          60
1  0.200000               0.8               0.4        50          60
2  0.188982               0.6               0.6        50          60
3  0.000000               0.4               0.6        50          60

   test_size
0         15
1         15
2         15
3         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.734275                    0.75          0.80
1    17_1         loo       0.618742                    0.60          0.52
2     9_1         loo       0.695764                    0.60          0.62
3    19_1         loo       0.586650                    0.50          0.60

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.500000               1.0               0.5        50          60
1  0.200000               0.8               0.4        50          60
2  0.188982               0.6               0.6        50          60
3  0.000000               0.4               0.6        50          60

   test_size
0         15
1         15
2         15
3         15

## MCI-LBD vs MCI-AD -> OTPUNA + XBG

In [1575]:
datasets = task_hf_compensated_comb_emb_lbl_ad_lbd

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir="xgb_ad_lbd_{CV_STRATEGY}_tasks/xgb_results_handcrafted_combined_emb_compensated_ad_lbd_extended_{CV_STRATEGY}_tasks",
    split_param= "diagnosis_y",
)
print(summary)

[I 2025-12-01 23:59:00,864] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 42, Test size: 11
Using Leave-One-Out CV with 42 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.562929:   2%|▏         | 1/50 [00:30<24:42, 30.25s/it]

[I 2025-12-01 23:59:31,109] Trial 1 finished with value: 0.562929061784897 and parameters: {'max_depth': 4, 'learning_rate': 0.22653678111345438, 'n_estimators': 606, 'subsample': 0.8236377315119252, 'colsample_bytree': 0.8920924076919854, 'min_child_weight': 1, 'gamma': 2.180993007766209, 'reg_alpha': 0.9083023142418898, 'reg_lambda': 1.923802884431846, 'max_delta_step': 7}. Best is trial 1 with value: 0.562929061784897.

Best trial: 1. Best value: 0.562929:   4%|▍         | 2/50 [00:39<14:17, 17.86s/it]

[I 2025-12-01 23:59:40,301] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.011645261494993234, 'n_estimators': 1469, 'subsample': 0.6596438198569006, 'colsample_bytree': 0.5310666274945027, 'min_child_weight': 7, 'gamma': 0.8736538507018743, 'reg_alpha': 2.718450360982412e-05, 'reg_lambda': 9.387720558723648e-07, 'max_delta_step': 5}. Best is trial 1 with value: 0.562929061784897.

Best trial: 0. Best value: 0.610984:   6%|▌         | 3/50 [00:43<09:05, 11.61s/it]

[I 2025-12-01 23:59:44,474] Trial 3 finished with value: 0.10869565217391304 and parameters: {'max_depth': 6, 'learning_rate': 0.11593682844372553, 'n_estimators': 1444, 'subsample': 0.5150503111643943, 'colsample_bytree': 0.9626531435013655, 'min_child_weight': 6, 'gamma': 2.578286265203272, 'reg_alpha': 0.00526972375631247, 'reg_lambda': 4.961026578940045e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.562929061784897.
[I 2025-12-01 23:59:44,499] Trial 0 finished with value: 0.6109839816933638 and parameters: {'max_depth': 4, 'learning_rate': 0.02659588493111977, 'n_estimators': 1261, 'subsample': 0.7987503740071321, 'colsample_bytree': 0.5538133558027121, 'min_child_weight': 2, 'gamma': 1.6555526524776094, 'reg_alpha': 1.2404838959857005, 'reg_lambda': 0.03897985042768797, 'max_delta_step': 3}. Best is trial 0 with value: 0.6109839816933638.

Best trial: 0. Best value: 0.610984:  10%|█         | 5/50 [00:45<04:06,  5.47s/it]

[I 2025-12-01 23:59:46,007] Trial 4 finished with value: 0.13043478260869565 and parameters: {'max_depth': 10, 'learning_rate': 0.2605252493154839, 'n_estimators': 448, 'subsample': 0.5189971249049299, 'colsample_bytree': 0.7829196869497508, 'min_child_weight': 6, 'gamma': 2.5892352621582178, 'reg_alpha': 0.024786542895792563, 'reg_lambda': 3.333950610322144, 'max_delta_step': 8}. Best is trial 0 with value: 0.6109839816933638.

Best trial: 0. Best value: 0.610984:  12%|█▏        | 6/50 [01:13<08:46, 11.96s/it]

[I 2025-12-02 00:00:14,006] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.08099498892761477, 'n_estimators': 972, 'subsample': 0.9583882054799764, 'colsample_bytree': 0.5960292841673995, 'min_child_weight': 8, 'gamma': 0.16867289176986766, 'reg_alpha': 1.5185827424565583e-07, 'reg_lambda': 6.672993231261335e-05, 'max_delta_step': 8}. Best is trial 0 with value: 0.6109839816933638.

Best trial: 0. Best value: 0.610984:  14%|█▍        | 7/50 [01:18<07:11, 10.04s/it]

[I 2025-12-02 00:00:19,387] Trial 6 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.11226656897334825, 'n_estimators': 1112, 'subsample': 0.5283449408033958, 'colsample_bytree': 0.8228629125472174, 'min_child_weight': 10, 'gamma': 2.02232671288117, 'reg_alpha': 4.406542375309818e-06, 'reg_lambda': 2.8335885649615436e-07, 'max_delta_step': 8}. Best is trial 0 with value: 0.6109839816933638.

Best trial: 0. Best value: 0.610984:  16%|█▌        | 8/50 [01:19<05:15,  7.51s/it]

[I 2025-12-02 00:00:20,802] Trial 5 finished with value: 0.2631578947368421 and parameters: {'max_depth': 6, 'learning_rate': 0.04771227559303532, 'n_estimators': 1308, 'subsample': 0.6342580206180632, 'colsample_bytree': 0.7611472100763781, 'min_child_weight': 6, 'gamma': 0.16315997746615352, 'reg_alpha': 0.018136719555851086, 'reg_lambda': 1.8460330921965673, 'max_delta_step': 6}. Best is trial 0 with value: 0.6109839816933638.

Best trial: 0. Best value: 0.610984:  18%|█▊        | 9/50 [01:23<04:24,  6.45s/it]

[I 2025-12-02 00:00:24,750] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.04101140055090228, 'n_estimators': 1271, 'subsample': 0.8425297575870022, 'colsample_bytree': 0.7234698024046416, 'min_child_weight': 8, 'gamma': 4.645911817048029, 'reg_alpha': 1.3056528934343561e-05, 'reg_lambda': 3.0144358930475644e-05, 'max_delta_step': 3}. Best is trial 0 with value: 0.6109839816933638.

Best trial: 0. Best value: 0.610984:  20%|██        | 10/50 [01:31<04:29,  6.74s/it]

[I 2025-12-02 00:00:32,184] Trial 11 finished with value: 0.07894736842105263 and parameters: {'max_depth': 3, 'learning_rate': 0.015479950442779153, 'n_estimators': 320, 'subsample': 0.51730819611577, 'colsample_bytree': 0.9555327419882329, 'min_child_weight': 5, 'gamma': 3.9648872262629626, 'reg_alpha': 0.006186854423967927, 'reg_lambda': 0.11714385719776298, 'max_delta_step': 2}. Best is trial 0 with value: 0.6109839816933638.

Best trial: 0. Best value: 0.610984:  22%|██▏       | 11/50 [01:35<03:49,  5.89s/it]

[I 2025-12-02 00:00:36,049] Trial 9 pruned.

Best trial: 10. Best value: 0.663616:  24%|██▍       | 12/50 [01:39<03:27,  5.46s/it]

[I 2025-12-02 00:00:40,515] Trial 10 finished with value: 0.6636155606407322 and parameters: {'max_depth': 6, 'learning_rate': 0.04790433037733078, 'n_estimators': 627, 'subsample': 0.6153291445929854, 'colsample_bytree': 0.6068467624740422, 'min_child_weight': 2, 'gamma': 4.219270548900959, 'reg_alpha': 0.0016781430740290765, 'reg_lambda': 4.0004946896002726e-07, 'max_delta_step': 9}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  26%|██▌       | 13/50 [01:48<03:58,  6.45s/it]

[I 2025-12-02 00:00:49,292] Trial 14 pruned.

Best trial: 10. Best value: 0.663616:  28%|██▊       | 14/50 [01:58<04:26,  7.40s/it]

[I 2025-12-02 00:00:58,898] Trial 12 finished with value: 0.09610983981693363 and parameters: {'max_depth': 8, 'learning_rate': 0.22513833477481104, 'n_estimators': 1160, 'subsample': 0.5202107196480568, 'colsample_bytree': 0.7083919847386606, 'min_child_weight': 3, 'gamma': 3.3038444780527696, 'reg_alpha': 4.804833071985687, 'reg_lambda': 1.8391485374068033e-06, 'max_delta_step': 6}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  30%|███       | 15/50 [02:07<04:44,  8.12s/it]

[I 2025-12-02 00:01:08,725] Trial 13 finished with value: 0.47139588100686497 and parameters: {'max_depth': 4, 'learning_rate': 0.02496597616795288, 'n_estimators': 812, 'subsample': 0.9768186581810371, 'colsample_bytree': 0.6460878285998312, 'min_child_weight': 1, 'gamma': 1.2354418081063205, 'reg_alpha': 2.341552550609677, 'reg_lambda': 0.0069464403337141925, 'max_delta_step': 0}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  32%|███▏      | 16/50 [02:14<04:22,  7.73s/it]

[I 2025-12-02 00:01:15,544] Trial 15 finished with value: 0.5411899313501144 and parameters: {'max_depth': 4, 'learning_rate': 0.025558608127964535, 'n_estimators': 839, 'subsample': 0.8187719263968284, 'colsample_bytree': 0.6332521779791662, 'min_child_weight': 2, 'gamma': 1.2068886671327645, 'reg_alpha': 1.8574666098880248, 'reg_lambda': 0.004426631661585243, 'max_delta_step': 0}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  34%|███▍      | 17/50 [02:17<03:27,  6.30s/it]

[I 2025-12-02 00:01:18,493] Trial 16 finished with value: 0.5720823798627002 and parameters: {'max_depth': 5, 'learning_rate': 0.028697140060959924, 'n_estimators': 931, 'subsample': 0.7125406122685003, 'colsample_bytree': 0.5011282725292797, 'min_child_weight': 3, 'gamma': 3.37691068385534, 'reg_alpha': 0.5317208246286815, 'reg_lambda': 0.0032418868698126657, 'max_delta_step': 4}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  36%|███▌      | 18/50 [02:21<02:57,  5.54s/it]

[I 2025-12-02 00:01:22,272] Trial 20 pruned.

Best trial: 10. Best value: 0.663616:  38%|███▊      | 19/50 [02:29<03:13,  6.24s/it]

[I 2025-12-02 00:01:30,136] Trial 17 finished with value: 0.6418764302059496 and parameters: {'max_depth': 4, 'learning_rate': 0.023014231825563898, 'n_estimators': 981, 'subsample': 0.7651820356998308, 'colsample_bytree': 0.5029304028754666, 'min_child_weight': 3, 'gamma': 4.963023176500119, 'reg_alpha': 0.45382758528569245, 'reg_lambda': 1.178188380178481e-08, 'max_delta_step': 3}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  40%|████      | 20/50 [02:32<02:36,  5.20s/it]

[I 2025-12-02 00:01:32,928] Trial 22 pruned.

Best trial: 10. Best value: 0.663616:  42%|████▏     | 21/50 [02:32<01:47,  3.71s/it]

[I 2025-12-02 00:01:33,151] Trial 19 finished with value: 0.5022883295194508 and parameters: {'max_depth': 5, 'learning_rate': 0.034540263402459484, 'n_estimators': 535, 'subsample': 0.7521933079298958, 'colsample_bytree': 0.5141162866592421, 'min_child_weight': 4, 'gamma': 4.7100010119173445, 'reg_alpha': 0.00018425543576396783, 'reg_lambda': 4.224885609497221e-08, 'max_delta_step': 3}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  44%|████▍     | 22/50 [02:32<01:16,  2.72s/it]

[I 2025-12-02 00:01:33,567] Trial 21 finished with value: 0.6464530892448512 and parameters: {'max_depth': 5, 'learning_rate': 0.0661606334950384, 'n_estimators': 267, 'subsample': 0.7606040762772426, 'colsample_bytree': 0.679868469189764, 'min_child_weight': 3, 'gamma': 4.152778777472873, 'reg_alpha': 1.346545273453588e-08, 'reg_lambda': 1.3939725811358485e-08, 'max_delta_step': 2}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  46%|████▌     | 23/50 [02:40<01:56,  4.33s/it]

[I 2025-12-02 00:01:41,648] Trial 18 finished with value: 0.6418764302059496 and parameters: {'max_depth': 5, 'learning_rate': 0.025616424477789307, 'n_estimators': 989, 'subsample': 0.7515314746500162, 'colsample_bytree': 0.5125162927340621, 'min_child_weight': 3, 'gamma': 4.7674168102238506, 'reg_alpha': 0.15572403228469062, 'reg_lambda': 1.9011183289444197e-08, 'max_delta_step': 3}. Best is trial 10 with value: 0.6636155606407322.
[I 2025-12-02 00:01:41,738] Trial 25 finished with value: 0.5675057208237986 and parameters: {'max_depth': 7, 'learning_rate': 0.095018013907813, 'n_estimators': 216, 'subsample': 0.5866326486506533, 'colsample_bytree': 0.6112717397361402, 'min_child_weight': 3, 'gamma': 4.236089354973473, 'reg_alpha': 1.0139405530686205e-08, 'reg_lambda': 6.625668823968329e-08, 'max_delta_step': 1}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  50%|█████     | 25/50 [02:48<01:42,  4.10s/it]

[I 2025-12-02 00:01:49,311] Trial 26 finished with value: 0.5892448512585813 and parameters: {'max_depth': 7, 'learning_rate': 0.11826673705807506, 'n_estimators': 205, 'subsample': 0.575011686317916, 'colsample_bytree': 0.5838444539662236, 'min_child_weight': 2, 'gamma': 4.235011596441593, 'reg_alpha': 1.1079262180784321e-06, 'reg_lambda': 8.71731157751172e-08, 'max_delta_step': 1}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  52%|█████▏    | 26/50 [02:59<02:20,  5.86s/it]

[I 2025-12-02 00:02:00,530] Trial 27 finished with value: 0.5892448512585813 and parameters: {'max_depth': 3, 'learning_rate': 0.017712956552366554, 'n_estimators': 366, 'subsample': 0.8844197871159678, 'colsample_bytree': 0.6745436514098767, 'min_child_weight': 2, 'gamma': 3.171015907788468, 'reg_alpha': 6.890362359492143e-07, 'reg_lambda': 7.458418460915916e-06, 'max_delta_step': 5}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  54%|█████▍    | 27/50 [03:02<01:57,  5.12s/it]

[I 2025-12-02 00:02:03,540] Trial 23 finished with value: 0.5892448512585813 and parameters: {'max_depth': 8, 'learning_rate': 0.041100752704809104, 'n_estimators': 1026, 'subsample': 0.5951775341556351, 'colsample_bytree': 0.5974082740007582, 'min_child_weight': 3, 'gamma': 4.40670151747823, 'reg_alpha': 0.0004988495145724599, 'reg_lambda': 1.7415297036236132e-08, 'max_delta_step': 5}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  56%|█████▌    | 28/50 [03:03<01:24,  3.86s/it]

[I 2025-12-02 00:02:04,024] Trial 28 finished with value: 0.6247139588100686 and parameters: {'max_depth': 3, 'learning_rate': 0.14833578201875192, 'n_estimators': 423, 'subsample': 0.7139615493247539, 'colsample_bytree': 0.6754824989728314, 'min_child_weight': 2, 'gamma': 3.14118491400576, 'reg_alpha': 0.0013143335324488083, 'reg_lambda': 4.0913794829205124e-06, 'max_delta_step': 5}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  58%|█████▊    | 29/50 [03:04<01:05,  3.13s/it]

[I 2025-12-02 00:02:05,292] Trial 29 pruned.

Best trial: 10. Best value: 0.663616:  60%|██████    | 30/50 [03:08<01:05,  3.26s/it]

[I 2025-12-02 00:02:08,878] Trial 30 pruned.

Best trial: 10. Best value: 0.663616:  62%|██████▏   | 31/50 [03:08<00:46,  2.46s/it]

[I 2025-12-02 00:02:09,362] Trial 31 pruned.

Best trial: 10. Best value: 0.663616:  64%|██████▍   | 32/50 [03:10<00:41,  2.28s/it]

[I 2025-12-02 00:02:11,211] Trial 32 pruned.

Best trial: 10. Best value: 0.663616:  66%|██████▌   | 33/50 [03:11<00:33,  1.95s/it]

[I 2025-12-02 00:02:12,388] Trial 24 finished with value: 0.562929061784897 and parameters: {'max_depth': 3, 'learning_rate': 0.018558056063764518, 'n_estimators': 1051, 'subsample': 0.7600682923083502, 'colsample_bytree': 0.5713106777062801, 'min_child_weight': 2, 'gamma': 2.9644844441938525, 'reg_alpha': 0.08580771327825248, 'reg_lambda': 1.0117824758042665e-08, 'max_delta_step': 2}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  68%|██████▊   | 34/50 [03:13<00:33,  2.10s/it]

[I 2025-12-02 00:02:14,837] Trial 33 pruned.

Best trial: 10. Best value: 0.663616:  70%|███████   | 35/50 [03:32<01:46,  7.13s/it]

[I 2025-12-02 00:02:33,826] Trial 34 finished with value: 0.4977116704805492 and parameters: {'max_depth': 4, 'learning_rate': 0.020151779919926303, 'n_estimators': 917, 'subsample': 0.7691382647102778, 'colsample_bytree': 0.5021213717275481, 'min_child_weight': 4, 'gamma': 4.977772942972193, 'reg_alpha': 0.06099077206783912, 'reg_lambda': 1.2281861549324559e-08, 'max_delta_step': 2}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  72%|███████▏  | 36/50 [03:47<02:10,  9.34s/it]

[I 2025-12-02 00:02:48,383] Trial 35 finished with value: 0.5675057208237986 and parameters: {'max_depth': 5, 'learning_rate': 0.020753789811539556, 'n_estimators': 928, 'subsample': 0.7882853129551821, 'colsample_bytree': 0.5238643984669564, 'min_child_weight': 1, 'gamma': 4.636577334142139, 'reg_alpha': 0.09369988983697183, 'reg_lambda': 1.3305808634776053e-08, 'max_delta_step': 3}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  74%|███████▍  | 37/50 [03:49<01:32,  7.10s/it]

[I 2025-12-02 00:02:50,226] Trial 37 finished with value: 0.5675057208237986 and parameters: {'max_depth': 5, 'learning_rate': 0.020796428444912463, 'n_estimators': 902, 'subsample': 0.6658223361295008, 'colsample_bytree': 0.524642006184763, 'min_child_weight': 1, 'gamma': 4.489636295494156, 'reg_alpha': 0.19540586028574197, 'reg_lambda': 3.653835280349235e-08, 'max_delta_step': 3}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  76%|███████▌  | 38/50 [03:52<01:11,  5.93s/it]

[I 2025-12-02 00:02:53,408] Trial 36 finished with value: 0.5194508009153318 and parameters: {'max_depth': 5, 'learning_rate': 0.010225352621823211, 'n_estimators': 910, 'subsample': 0.789058065852233, 'colsample_bytree': 0.5239602158816952, 'min_child_weight': 1, 'gamma': 4.532124863991451, 'reg_alpha': 0.12929145883012272, 'reg_lambda': 3.924749789198326e-08, 'max_delta_step': 3}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  78%|███████▊  | 39/50 [03:57<01:03,  5.78s/it]

[I 2025-12-02 00:02:58,846] Trial 39 pruned.

Best trial: 10. Best value: 0.663616:  80%|████████  | 40/50 [04:25<02:03, 12.36s/it]

[I 2025-12-02 00:03:26,594] Trial 38 finished with value: 0.5194508009153318 and parameters: {'max_depth': 5, 'learning_rate': 0.01046592196525198, 'n_estimators': 1171, 'subsample': 0.6628137118588598, 'colsample_bytree': 0.6153145176151709, 'min_child_weight': 1, 'gamma': 4.551488142609696, 'reg_alpha': 0.0011367077739073731, 'reg_lambda': 8.374147643931426e-07, 'max_delta_step': 3}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  82%|████████▏ | 41/50 [04:28<01:24,  9.38s/it]

[I 2025-12-02 00:03:28,997] Trial 40 finished with value: 0.6155606407322655 and parameters: {'max_depth': 5, 'learning_rate': 0.013201612136227428, 'n_estimators': 1175, 'subsample': 0.8629966667190332, 'colsample_bytree': 0.614037475749143, 'min_child_weight': 3, 'gamma': 4.150544859076559, 'reg_alpha': 0.41216715722015806, 'reg_lambda': 7.824303435264284e-07, 'max_delta_step': 9}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  84%|████████▍ | 42/50 [04:33<01:04,  8.05s/it]

[I 2025-12-02 00:03:33,963] Trial 41 finished with value: 0.5892448512585813 and parameters: {'max_depth': 8, 'learning_rate': 0.013925283612008923, 'n_estimators': 1177, 'subsample': 0.847883563501721, 'colsample_bytree': 0.7309357900198377, 'min_child_weight': 3, 'gamma': 4.11208212000092, 'reg_alpha': 0.42882619025806357, 'reg_lambda': 8.215528697458779e-07, 'max_delta_step': 9}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  86%|████████▌ | 43/50 [04:37<00:48,  6.94s/it]

[I 2025-12-02 00:03:38,300] Trial 42 finished with value: 0.620137299771167 and parameters: {'max_depth': 4, 'learning_rate': 0.01291269555128514, 'n_estimators': 1186, 'subsample': 0.7343613541744269, 'colsample_bytree': 0.8046513254763091, 'min_child_weight': 3, 'gamma': 4.030226930889814, 'reg_alpha': 0.020723095772767423, 'reg_lambda': 5.299434540953914e-07, 'max_delta_step': 9}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  88%|████████▊ | 44/50 [04:43<00:39,  6.59s/it]

[I 2025-12-02 00:03:44,063] Trial 44 finished with value: 0.620137299771167 and parameters: {'max_depth': 3, 'learning_rate': 0.17579414626021123, 'n_estimators': 419, 'subsample': 0.7327385031620044, 'colsample_bytree': 0.7389251360889824, 'min_child_weight': 2, 'gamma': 2.8272557969259835, 'reg_alpha': 0.0016768164726175443, 'reg_lambda': 1.950745388012637e-06, 'max_delta_step': 7}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  90%|█████████ | 45/50 [04:48<00:31,  6.28s/it]

[I 2025-12-02 00:03:49,641] Trial 45 finished with value: 0.6418764302059496 and parameters: {'max_depth': 4, 'learning_rate': 0.15271084796387324, 'n_estimators': 429, 'subsample': 0.731195693106502, 'colsample_bytree': 0.8173267351029667, 'min_child_weight': 2, 'gamma': 2.2597008434959456, 'reg_alpha': 0.001879476808917776, 'reg_lambda': 8.935684146646028e-06, 'max_delta_step': 6}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  92%|█████████▏| 46/50 [04:50<00:19,  4.79s/it]

[I 2025-12-02 00:03:50,936] Trial 43 finished with value: 0.5938215102974829 and parameters: {'max_depth': 6, 'learning_rate': 0.014206239295129697, 'n_estimators': 556, 'subsample': 0.858446847114694, 'colsample_bytree': 0.8098963527094906, 'min_child_weight': 3, 'gamma': 4.106029163701486, 'reg_alpha': 0.4437349177191712, 'reg_lambda': 4.701432214685965e-07, 'max_delta_step': 9}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  94%|█████████▍| 47/50 [04:52<00:12,  4.18s/it]

[I 2025-12-02 00:03:53,691] Trial 46 finished with value: 0.5675057208237986 and parameters: {'max_depth': 3, 'learning_rate': 0.1690612021558985, 'n_estimators': 418, 'subsample': 0.7402062026611731, 'colsample_bytree': 0.6655820889695142, 'min_child_weight': 2, 'gamma': 2.1465341535874085, 'reg_alpha': 0.0017680673863573395, 'reg_lambda': 4.91245729217389e-06, 'max_delta_step': 6}. Best is trial 10 with value: 0.6636155606407322.

Best trial: 10. Best value: 0.663616:  96%|█████████▌| 48/50 [04:53<00:05,  2.99s/it]

[I 2025-12-02 00:03:53,906] Trial 49 pruned.

Best trial: 10. Best value: 0.663616:  98%|█████████▊| 49/50 [04:53<00:02,  2.20s/it]

[I 2025-12-02 00:03:54,278] Trial 48 pruned.

Best trial: 47. Best value: 0.71167: 100%|██████████| 50/50 [05:00<00:00,  6.00s/it]

[I 2025-12-02 00:04:01,092] Trial 47 finished with value: 0.7116704805491991 and parameters: {'max_depth': 4, 'learning_rate': 0.04228017619945086, 'n_estimators': 572, 'subsample': 0.6350020341001956, 'colsample_bytree': 0.6951066171585422, 'min_child_weight': 2, 'gamma': 3.415117158768018, 'reg_alpha': 0.0037244414331321324, 'reg_lambda': 4.652477392903502e-06, 'max_delta_step': 6}. Best is trial 47 with value: 0.7116704805491991.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 00:04:05,721] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 44, Test size: 12
Using Leave-One-Out CV with 44 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.36:   2%|▏         | 1/50 [00:19<16:15, 19.90s/it]

[I 2025-12-02 00:04:25,620] Trial 0 finished with value: 0.36 and parameters: {'max_depth': 10, 'learning_rate': 0.09075005499800365, 'n_estimators': 685, 'subsample': 0.5270039505465771, 'colsample_bytree': 0.585159473267032, 'min_child_weight': 5, 'gamma': 3.557767878955878, 'reg_alpha': 1.8788527310693117, 'reg_lambda': 1.1624937489146917e-07, 'max_delta_step': 2}. Best is trial 0 with value: 0.36.

Best trial: 0. Best value: 0.36:   4%|▍         | 2/50 [00:25<09:19, 11.65s/it]

[I 2025-12-02 00:04:31,497] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.043369877391145596, 'n_estimators': 835, 'subsample': 0.5551305287369124, 'colsample_bytree': 0.9266063233197147, 'min_child_weight': 7, 'gamma': 0.04323364727848, 'reg_alpha': 1.5886029461481933e-07, 'reg_lambda': 0.00011445939733526209, 'max_delta_step': 0}. Best is trial 0 with value: 0.36.

Best trial: 4. Best value: 0.42:   6%|▌         | 3/50 [00:36<08:53, 11.36s/it]

[I 2025-12-02 00:04:42,501] Trial 4 finished with value: 0.42 and parameters: {'max_depth': 9, 'learning_rate': 0.13313361737341534, 'n_estimators': 552, 'subsample': 0.5264405404178898, 'colsample_bytree': 0.659602103676113, 'min_child_weight': 6, 'gamma': 1.5982859556022333, 'reg_alpha': 5.866864027741359e-05, 'reg_lambda': 0.18452907612924263, 'max_delta_step': 6}. Best is trial 4 with value: 0.42.

Best trial: 4. Best value: 0.42:   8%|▊         | 4/50 [00:55<10:57, 14.30s/it]

[I 2025-12-02 00:05:01,316] Trial 1 finished with value: 0.38421052631578945 and parameters: {'max_depth': 6, 'learning_rate': 0.183648525605142, 'n_estimators': 1280, 'subsample': 0.9625593358900388, 'colsample_bytree': 0.529503771420565, 'min_child_weight': 1, 'gamma': 4.721498729305138, 'reg_alpha': 0.02247154200730902, 'reg_lambda': 1.898187064343276, 'max_delta_step': 1}. Best is trial 4 with value: 0.42.

Best trial: 2. Best value: 0.444211:  10%|█         | 5/50 [01:01<08:31, 11.38s/it]

[I 2025-12-02 00:05:07,509] Trial 2 finished with value: 0.4442105263157895 and parameters: {'max_depth': 8, 'learning_rate': 0.13998594525415267, 'n_estimators': 1238, 'subsample': 0.5410674359152383, 'colsample_bytree': 0.9020115974044953, 'min_child_weight': 1, 'gamma': 3.835259375741007, 'reg_alpha': 0.00396164836237141, 'reg_lambda': 1.1304508367537567, 'max_delta_step': 2}. Best is trial 2 with value: 0.4442105263157895.

Best trial: 2. Best value: 0.444211:  12%|█▏        | 6/50 [01:04<06:08,  8.39s/it]

[I 2025-12-02 00:05:10,088] Trial 6 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.15318183080031644, 'n_estimators': 930, 'subsample': 0.7934935047090528, 'colsample_bytree': 0.7813112739089878, 'min_child_weight': 8, 'gamma': 2.1440926488671725, 'reg_alpha': 6.541215179548892, 'reg_lambda': 2.3970743558601893e-07, 'max_delta_step': 5}. Best is trial 2 with value: 0.4442105263157895.
[I 2025-12-02 00:05:10,116] Trial 5 finished with value: 0.13157894736842105 and parameters: {'max_depth': 10, 'learning_rate': 0.0635883614697611, 'n_estimators': 1278, 'subsample': 0.677249629782325, 'colsample_bytree': 0.8228167274133172, 'min_child_weight': 5, 'gamma': 4.08219514628262, 'reg_alpha': 1.8313298957636536e-07, 'reg_lambda': 0.0012951489177494646, 'max_delta_step': 10}. Best is trial 2 with value: 0.4442105263157895.

Best trial: 7. Best value: 0.536842:  16%|█▌        | 8/50 [01:26<06:50,  9.78s/it]

[I 2025-12-02 00:05:32,511] Trial 7 finished with value: 0.5368421052631579 and parameters: {'max_depth': 9, 'learning_rate': 0.04585685644485223, 'n_estimators': 990, 'subsample': 0.6294638528108711, 'colsample_bytree': 0.5024353179741277, 'min_child_weight': 3, 'gamma': 2.2441441963585746, 'reg_alpha': 0.12240369518078724, 'reg_lambda': 1.3812744771902119e-05, 'max_delta_step': 5}. Best is trial 7 with value: 0.5368421052631579.

Best trial: 7. Best value: 0.536842:  18%|█▊        | 9/50 [01:27<05:06,  7.48s/it]

[I 2025-12-02 00:05:33,453] Trial 9 finished with value: 0.2 and parameters: {'max_depth': 6, 'learning_rate': 0.01374596635413831, 'n_estimators': 778, 'subsample': 0.7193242476718877, 'colsample_bytree': 0.5526000569012282, 'min_child_weight': 5, 'gamma': 1.540027150008536, 'reg_alpha': 1.0723625283189821e-07, 'reg_lambda': 0.00029540232777058487, 'max_delta_step': 7}. Best is trial 7 with value: 0.5368421052631579.

Best trial: 7. Best value: 0.536842:  20%|██        | 10/50 [01:39<05:47,  8.68s/it]

[I 2025-12-02 00:05:45,364] Trial 11 finished with value: 0.4631578947368421 and parameters: {'max_depth': 9, 'learning_rate': 0.2139602990605806, 'n_estimators': 255, 'subsample': 0.8035385484753634, 'colsample_bytree': 0.726569474098001, 'min_child_weight': 1, 'gamma': 4.706379134678645, 'reg_alpha': 4.192775877498231, 'reg_lambda': 0.15756222444675813, 'max_delta_step': 9}. Best is trial 7 with value: 0.5368421052631579.

Best trial: 7. Best value: 0.536842:  22%|██▏       | 11/50 [01:41<04:22,  6.73s/it]

[I 2025-12-02 00:05:47,060] Trial 8 pruned.

Best trial: 7. Best value: 0.536842:  24%|██▍       | 12/50 [01:48<04:16,  6.74s/it]

[I 2025-12-02 00:05:53,825] Trial 12 pruned.

Best trial: 7. Best value: 0.536842:  26%|██▌       | 13/50 [01:50<03:27,  5.61s/it]

[I 2025-12-02 00:05:56,649] Trial 13 pruned.

Best trial: 7. Best value: 0.536842:  28%|██▊       | 14/50 [01:57<03:27,  5.75s/it]

[I 2025-12-02 00:06:02,764] Trial 14 finished with value: 0.41789473684210526 and parameters: {'max_depth': 8, 'learning_rate': 0.030735249908198946, 'n_estimators': 221, 'subsample': 0.6540276882721936, 'colsample_bytree': 0.6469239934402173, 'min_child_weight': 2, 'gamma': 2.8924993299801622, 'reg_alpha': 0.38691198505648144, 'reg_lambda': 7.757147398688972e-06, 'max_delta_step': 4}. Best is trial 7 with value: 0.5368421052631579.

Best trial: 7. Best value: 0.536842:  30%|███       | 15/50 [02:01<03:12,  5.51s/it]

[I 2025-12-02 00:06:07,697] Trial 15 finished with value: 0.4642105263157895 and parameters: {'max_depth': 8, 'learning_rate': 0.02851420459290534, 'n_estimators': 225, 'subsample': 0.642311883215581, 'colsample_bytree': 0.6637298837020045, 'min_child_weight': 3, 'gamma': 3.062899653278525, 'reg_alpha': 0.537827326218229, 'reg_lambda': 0.015431557847200114, 'max_delta_step': 4}. Best is trial 7 with value: 0.5368421052631579.

Best trial: 16. Best value: 0.543158:  32%|███▏      | 16/50 [02:04<02:42,  4.77s/it]

[I 2025-12-02 00:06:10,692] Trial 16 finished with value: 0.5431578947368421 and parameters: {'max_depth': 8, 'learning_rate': 0.036295471434377, 'n_estimators': 210, 'subsample': 0.9082043607402289, 'colsample_bytree': 0.6491911319545298, 'min_child_weight': 3, 'gamma': 3.0263564731482773, 'reg_alpha': 0.5631736642337518, 'reg_lambda': 0.0064694260595112695, 'max_delta_step': 8}. Best is trial 16 with value: 0.5431578947368421.

Best trial: 16. Best value: 0.543158:  34%|███▍      | 17/50 [02:08<02:29,  4.52s/it]

[I 2025-12-02 00:06:14,621] Trial 10 finished with value: 0.4842105263157894 and parameters: {'max_depth': 3, 'learning_rate': 0.03039309018607923, 'n_estimators': 1455, 'subsample': 0.5996445794867148, 'colsample_bytree': 0.9642468782772613, 'min_child_weight': 2, 'gamma': 3.7925053415075745, 'reg_alpha': 2.2877277766429507, 'reg_lambda': 3.101597963716975e-06, 'max_delta_step': 7}. Best is trial 16 with value: 0.5431578947368421.

Best trial: 16. Best value: 0.543158:  36%|███▌      | 18/50 [02:35<05:52, 11.00s/it]

[I 2025-12-02 00:06:40,883] Trial 17 finished with value: 0.523157894736842 and parameters: {'max_depth': 8, 'learning_rate': 0.07636972478447913, 'n_estimators': 1046, 'subsample': 0.8851590658914745, 'colsample_bytree': 0.6984849479170152, 'min_child_weight': 3, 'gamma': 3.038395333784152, 'reg_alpha': 0.23183340919903714, 'reg_lambda': 0.009478761765384152, 'max_delta_step': 8}. Best is trial 16 with value: 0.5431578947368421.

Best trial: 16. Best value: 0.543158:  38%|███▊      | 19/50 [02:36<04:09,  8.04s/it]

[I 2025-12-02 00:06:41,960] Trial 18 finished with value: 0.4642105263157895 and parameters: {'max_depth': 7, 'learning_rate': 0.025162742500362628, 'n_estimators': 1041, 'subsample': 0.6027023586797399, 'colsample_bytree': 0.50114165882943, 'min_child_weight': 3, 'gamma': 2.9826457963069757, 'reg_alpha': 0.1752330405555233, 'reg_lambda': 0.007915202482691367, 'max_delta_step': 7}. Best is trial 16 with value: 0.5431578947368421.

Best trial: 16. Best value: 0.543158:  40%|████      | 20/50 [02:39<03:22,  6.75s/it]

[I 2025-12-02 00:06:45,693] Trial 19 finished with value: 0.49684210526315786 and parameters: {'max_depth': 7, 'learning_rate': 0.05210106868252728, 'n_estimators': 1033, 'subsample': 0.9192566941484726, 'colsample_bytree': 0.5058521428122197, 'min_child_weight': 3, 'gamma': 1.1623440943632122, 'reg_alpha': 0.00047803401132615015, 'reg_lambda': 1.0198932798421097e-08, 'max_delta_step': 8}. Best is trial 16 with value: 0.5431578947368421.

Best trial: 16. Best value: 0.543158:  42%|████▏     | 21/50 [02:43<02:45,  5.70s/it]

[I 2025-12-02 00:06:48,947] Trial 20 finished with value: 0.4568421052631579 and parameters: {'max_depth': 7, 'learning_rate': 0.0594417045066474, 'n_estimators': 990, 'subsample': 0.9398819496028993, 'colsample_bytree': 0.5991402053420118, 'min_child_weight': 3, 'gamma': 0.8812380459694151, 'reg_alpha': 0.001060611538762194, 'reg_lambda': 1.2905888835959938e-08, 'max_delta_step': 8}. Best is trial 16 with value: 0.5431578947368421.

Best trial: 21. Best value: 0.556842:  44%|████▍     | 22/50 [02:51<03:04,  6.59s/it]

[I 2025-12-02 00:06:57,612] Trial 21 finished with value: 0.5568421052631579 and parameters: {'max_depth': 7, 'learning_rate': 0.045597098625636025, 'n_estimators': 447, 'subsample': 0.93028783779667, 'colsample_bytree': 0.5948658486671083, 'min_child_weight': 4, 'gamma': 1.278069916920767, 'reg_alpha': 0.0009735888920226302, 'reg_lambda': 0.002387924793173004, 'max_delta_step': 6}. Best is trial 21 with value: 0.5568421052631579.

Best trial: 21. Best value: 0.556842:  46%|████▌     | 23/50 [02:52<02:10,  4.85s/it]

[I 2025-12-02 00:06:58,386] Trial 22 finished with value: 0.5305263157894737 and parameters: {'max_depth': 7, 'learning_rate': 0.05253241936191971, 'n_estimators': 440, 'subsample': 0.987581187105913, 'colsample_bytree': 0.5882412041781879, 'min_child_weight': 4, 'gamma': 0.7584730454811726, 'reg_alpha': 0.0010857047766557298, 'reg_lambda': 2.466029385942309e-08, 'max_delta_step': 5}. Best is trial 21 with value: 0.5568421052631579.

Best trial: 21. Best value: 0.556842:  48%|████▊     | 24/50 [02:58<02:17,  5.27s/it]

[I 2025-12-02 00:07:04,643] Trial 23 finished with value: 0.5105263157894737 and parameters: {'max_depth': 10, 'learning_rate': 0.01941426135517401, 'n_estimators': 457, 'subsample': 0.9888001087259218, 'colsample_bytree': 0.6016285118066342, 'min_child_weight': 4, 'gamma': 0.9523417814182191, 'reg_alpha': 0.001819304839445736, 'reg_lambda': 1.9485204038627256e-05, 'max_delta_step': 5}. Best is trial 21 with value: 0.5568421052631579.

Best trial: 24. Best value: 0.635789:  50%|█████     | 25/50 [03:00<01:41,  4.07s/it]

[I 2025-12-02 00:07:05,922] Trial 24 finished with value: 0.6357894736842105 and parameters: {'max_depth': 8, 'learning_rate': 0.0895607447246831, 'n_estimators': 473, 'subsample': 0.8779602760981357, 'colsample_bytree': 0.708513206396722, 'min_child_weight': 4, 'gamma': 2.5702990977655227, 'reg_alpha': 0.030235126874298277, 'reg_lambda': 0.008441277698104386, 'max_delta_step': 6}. Best is trial 24 with value: 0.6357894736842105.

Best trial: 24. Best value: 0.635789:  54%|█████▍    | 27/50 [03:07<01:20,  3.51s/it]

[I 2025-12-02 00:07:12,938] Trial 25 finished with value: 0.5631578947368421 and parameters: {'max_depth': 5, 'learning_rate': 0.0405423024465207, 'n_estimators': 416, 'subsample': 0.8678177777250664, 'colsample_bytree': 0.6036235504065699, 'min_child_weight': 4, 'gamma': 2.0251832402599375, 'reg_alpha': 0.027304589647760648, 'reg_lambda': 0.0014715289791073782, 'max_delta_step': 5}. Best is trial 24 with value: 0.6357894736842105.
[I 2025-12-02 00:07:13,073] Trial 26 finished with value: 0.5105263157894737 and parameters: {'max_depth': 5, 'learning_rate': 0.03940125987623316, 'n_estimators': 393, 'subsample': 0.863178163762898, 'colsample_bytree': 0.6103509297348083, 'min_child_weight': 4, 'gamma': 1.9762642616064743, 'reg_alpha': 0.024526447472981543, 'reg_lambda': 0.0021359988000475313, 'max_delta_step': 6}. Best is trial 24 with value: 0.6357894736842105.

Best trial: 24. Best value: 0.635789:  56%|█████▌    | 28/50 [03:10<01:17,  3.54s/it]

[I 2025-12-02 00:07:16,679] Trial 27 finished with value: 0.5368421052631579 and parameters: {'max_depth': 5, 'learning_rate': 0.03847566535438488, 'n_estimators': 313, 'subsample': 0.8690804014652513, 'colsample_bytree': 0.5537558771114296, 'min_child_weight': 4, 'gamma': 2.1448553988903534, 'reg_alpha': 0.01534922692044161, 'reg_lambda': 0.00139844962885876, 'max_delta_step': 6}. Best is trial 24 with value: 0.6357894736842105.

Best trial: 24. Best value: 0.635789:  58%|█████▊    | 29/50 [03:12<01:04,  3.05s/it]

[I 2025-12-02 00:07:18,589] Trial 30 pruned.

Best trial: 24. Best value: 0.635789:  60%|██████    | 30/50 [03:14<00:55,  2.76s/it]

[I 2025-12-02 00:07:20,684] Trial 28 finished with value: 0.5431578947368421 and parameters: {'max_depth': 5, 'learning_rate': 0.10920536160713648, 'n_estimators': 371, 'subsample': 0.8665063821081147, 'colsample_bytree': 0.8361454112788238, 'min_child_weight': 4, 'gamma': 1.8326254035013783, 'reg_alpha': 5.3230574326751295e-05, 'reg_lambda': 0.001806822845261675, 'max_delta_step': 6}. Best is trial 24 with value: 0.6357894736842105.

Best trial: 24. Best value: 0.635789:  62%|██████▏   | 31/50 [03:16<00:44,  2.36s/it]

[I 2025-12-02 00:07:22,097] Trial 31 pruned.

Best trial: 24. Best value: 0.635789:  64%|██████▍   | 32/50 [03:20<00:49,  2.75s/it]

[I 2025-12-02 00:07:25,749] Trial 33 pruned.

Best trial: 24. Best value: 0.635789:  66%|██████▌   | 33/50 [03:20<00:37,  2.21s/it]

[I 2025-12-02 00:07:26,702] Trial 34 pruned.

Best trial: 24. Best value: 0.635789:  68%|██████▊   | 34/50 [03:23<00:35,  2.22s/it]

[I 2025-12-02 00:07:28,962] Trial 29 finished with value: 0.16 and parameters: {'max_depth': 5, 'learning_rate': 0.10393765691283584, 'n_estimators': 387, 'subsample': 0.866078858631162, 'colsample_bytree': 0.8097083072038673, 'min_child_weight': 6, 'gamma': 1.758073252015058, 'reg_alpha': 2.1559530753854506e-05, 'reg_lambda': 0.00115237304701375, 'max_delta_step': 6}. Best is trial 24 with value: 0.6357894736842105.

Best trial: 24. Best value: 0.635789:  70%|███████   | 35/50 [03:27<00:43,  2.90s/it]

[I 2025-12-02 00:07:33,450] Trial 32 pruned.

Best trial: 24. Best value: 0.635789:  72%|███████▏  | 36/50 [03:29<00:34,  2.45s/it]

[I 2025-12-02 00:07:34,840] Trial 35 pruned.

Best trial: 24. Best value: 0.635789:  74%|███████▍  | 37/50 [03:29<00:25,  1.98s/it]

[I 2025-12-02 00:07:35,715] Trial 36 pruned.

Best trial: 24. Best value: 0.635789:  76%|███████▌  | 38/50 [03:31<00:21,  1.81s/it]

[I 2025-12-02 00:07:37,124] Trial 37 pruned.

Best trial: 24. Best value: 0.635789:  78%|███████▊  | 39/50 [03:34<00:23,  2.14s/it]

[I 2025-12-02 00:07:40,045] Trial 40 pruned.

Best trial: 24. Best value: 0.635789:  80%|████████  | 40/50 [03:35<00:19,  1.97s/it]

[I 2025-12-02 00:07:41,611] Trial 38 pruned.

Best trial: 24. Best value: 0.635789:  82%|████████▏ | 41/50 [03:36<00:15,  1.68s/it]

[I 2025-12-02 00:07:42,616] Trial 39 pruned.

Best trial: 24. Best value: 0.635789:  84%|████████▍ | 42/50 [03:37<00:10,  1.29s/it]

[I 2025-12-02 00:07:42,987] Trial 41 pruned.

Best trial: 24. Best value: 0.635789:  86%|████████▌ | 43/50 [03:38<00:08,  1.25s/it]

[I 2025-12-02 00:07:44,169] Trial 42 pruned.

Best trial: 24. Best value: 0.635789:  88%|████████▊ | 44/50 [03:40<00:08,  1.37s/it]

[I 2025-12-02 00:07:45,816] Trial 43 pruned.

Best trial: 24. Best value: 0.635789:  90%|█████████ | 45/50 [03:50<00:20,  4.11s/it]

[I 2025-12-02 00:07:56,306] Trial 44 finished with value: 0.4 and parameters: {'max_depth': 7, 'learning_rate': 0.12005324935567173, 'n_estimators': 395, 'subsample': 0.8162984297850414, 'colsample_bytree': 0.863863961414561, 'min_child_weight': 5, 'gamma': 1.2659962042026935, 'reg_alpha': 1.2566769800850577e-06, 'reg_lambda': 0.021804294055814757, 'max_delta_step': 6}. Best is trial 24 with value: 0.6357894736842105.

Best trial: 24. Best value: 0.635789:  92%|█████████▏| 46/50 [03:52<00:14,  3.50s/it]

[I 2025-12-02 00:07:58,404] Trial 46 finished with value: 0.5505263157894738 and parameters: {'max_depth': 9, 'learning_rate': 0.125531671506316, 'n_estimators': 383, 'subsample': 0.8899248152973774, 'colsample_bytree': 0.8867361226104871, 'min_child_weight': 4, 'gamma': 1.9384628292881319, 'reg_alpha': 2.2014611808441024e-06, 'reg_lambda': 0.032219992429089794, 'max_delta_step': 6}. Best is trial 24 with value: 0.6357894736842105.

Best trial: 24. Best value: 0.635789:  94%|█████████▍| 47/50 [03:54<00:08,  2.92s/it]

[I 2025-12-02 00:07:59,950] Trial 47 finished with value: 0.5305263157894737 and parameters: {'max_depth': 3, 'learning_rate': 0.12239261779925549, 'n_estimators': 379, 'subsample': 0.8861333795804307, 'colsample_bytree': 0.8600256449143678, 'min_child_weight': 4, 'gamma': 2.060910434908736, 'reg_alpha': 0.00012026308958400158, 'reg_lambda': 0.02271762660490802, 'max_delta_step': 6}. Best is trial 24 with value: 0.6357894736842105.

Best trial: 24. Best value: 0.635789:  96%|█████████▌| 48/50 [03:54<00:04,  2.17s/it]

[I 2025-12-02 00:08:00,368] Trial 45 finished with value: 0.5242105263157895 and parameters: {'max_depth': 9, 'learning_rate': 0.12945248150354532, 'n_estimators': 469, 'subsample': 0.893041251701976, 'colsample_bytree': 0.8679545260916913, 'min_child_weight': 4, 'gamma': 1.8407572437505053, 'reg_alpha': 0.00020949859517848798, 'reg_lambda': 5.08672879391607e-05, 'max_delta_step': 6}. Best is trial 24 with value: 0.6357894736842105.

Best trial: 24. Best value: 0.635789:  98%|█████████▊| 49/50 [04:00<00:03,  3.39s/it]

[I 2025-12-02 00:08:06,618] Trial 49 finished with value: 0.5431578947368421 and parameters: {'max_depth': 10, 'learning_rate': 0.17817565832453983, 'n_estimators': 266, 'subsample': 0.8961383246585393, 'colsample_bytree': 0.7428154220148313, 'min_child_weight': 4, 'gamma': 1.9842849597707788, 'reg_alpha': 0.0002449876952060688, 'reg_lambda': 0.0006440573723405159, 'max_delta_step': 7}. Best is trial 24 with value: 0.6357894736842105.

Best trial: 24. Best value: 0.635789: 100%|██████████| 50/50 [04:01<00:00,  4.84s/it]

[I 2025-12-02 00:08:07,547] Trial 48 finished with value: 0.5631578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.2841417366069606, 'n_estimators': 375, 'subsample': 0.8968677099689804, 'colsample_bytree': 0.7389169814835556, 'min_child_weight': 4, 'gamma': 1.8981536905646412, 'reg_alpha': 0.0002627268261451174, 'reg_lambda': 0.0024705360439483777, 'max_delta_step': 6}. Best is trial 24 with value: 0.6357894736842105.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 00:08:10,832] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 43, Test size: 11
Using Leave-One-Out CV with 43 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.413377:   2%|▏         | 1/50 [00:11<09:12, 11.27s/it]

[I 2025-12-02 00:08:22,091] Trial 1 finished with value: 0.4133771929824561 and parameters: {'max_depth': 7, 'learning_rate': 0.17754935976848463, 'n_estimators': 300, 'subsample': 0.5679793177179387, 'colsample_bytree': 0.9711301610369303, 'min_child_weight': 3, 'gamma': 4.356978856160728, 'reg_alpha': 0.00014342985262711416, 'reg_lambda': 0.02007083588468071, 'max_delta_step': 10}. Best is trial 1 with value: 0.4133771929824561.

Best trial: 1. Best value: 0.413377:   4%|▍         | 2/50 [00:26<10:49, 13.53s/it]

[I 2025-12-02 00:08:37,200] Trial 3 finished with value: 0.10416666666666667 and parameters: {'max_depth': 10, 'learning_rate': 0.26977832990671996, 'n_estimators': 830, 'subsample': 0.9431457032837876, 'colsample_bytree': 0.8136111920167746, 'min_child_weight': 5, 'gamma': 2.678571895296786, 'reg_alpha': 2.1746093825635823e-07, 'reg_lambda': 0.001450067234589226, 'max_delta_step': 0}. Best is trial 1 with value: 0.4133771929824561.

Best trial: 1. Best value: 0.413377:   6%|▌         | 3/50 [00:37<09:45, 12.46s/it]

[I 2025-12-02 00:08:48,386] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.09104626531057305, 'n_estimators': 1277, 'subsample': 0.6173576702125299, 'colsample_bytree': 0.5428911635407925, 'min_child_weight': 6, 'gamma': 3.576517908766506, 'reg_alpha': 0.0002496483265969337, 'reg_lambda': 0.000314854844002919, 'max_delta_step': 9}. Best is trial 1 with value: 0.4133771929824561.

Best trial: 1. Best value: 0.413377:   8%|▊         | 4/50 [00:38<05:55,  7.73s/it]

[I 2025-12-02 00:08:48,868] Trial 0 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.013327567005342439, 'n_estimators': 1214, 'subsample': 0.8120473642648072, 'colsample_bytree': 0.7929981483224856, 'min_child_weight': 6, 'gamma': 4.275330795689928, 'reg_alpha': 4.912729842575752e-06, 'reg_lambda': 0.018301532456025574, 'max_delta_step': 10}. Best is trial 1 with value: 0.4133771929824561.

Best trial: 1. Best value: 0.413377:  10%|█         | 5/50 [00:47<06:10,  8.24s/it]

[I 2025-12-02 00:08:58,013] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.18316137971572524, 'n_estimators': 1210, 'subsample': 0.6182910500927199, 'colsample_bytree': 0.5464326257351315, 'min_child_weight': 8, 'gamma': 1.268786384415358, 'reg_alpha': 0.00041612188102739035, 'reg_lambda': 1.6239938214934623e-06, 'max_delta_step': 6}. Best is trial 1 with value: 0.4133771929824561.

Best trial: 1. Best value: 0.413377:  12%|█▏        | 6/50 [00:48<04:19,  5.89s/it]

[I 2025-12-02 00:08:59,331] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.028695597947665023, 'n_estimators': 676, 'subsample': 0.5269424009993504, 'colsample_bytree': 0.8093725116416495, 'min_child_weight': 8, 'gamma': 1.444079706061625, 'reg_alpha': 6.528101061107806e-06, 'reg_lambda': 1.3408405629888257e-05, 'max_delta_step': 3}. Best is trial 1 with value: 0.4133771929824561.

Best trial: 1. Best value: 0.413377:  14%|█▍        | 7/50 [01:00<05:38,  7.88s/it]

[I 2025-12-02 00:09:11,322] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.2903651977918037, 'n_estimators': 370, 'subsample': 0.8434884364338149, 'colsample_bytree': 0.5580513484007654, 'min_child_weight': 10, 'gamma': 1.6021258972699353, 'reg_alpha': 0.9822079817760075, 'reg_lambda': 0.0006806545886274458, 'max_delta_step': 5}. Best is trial 1 with value: 0.4133771929824561.

Best trial: 1. Best value: 0.413377:  16%|█▌        | 8/50 [01:14<06:58,  9.96s/it]

[I 2025-12-02 00:09:25,720] Trial 8 finished with value: 0.26644736842105265 and parameters: {'max_depth': 3, 'learning_rate': 0.239055461068714, 'n_estimators': 630, 'subsample': 0.6444258010245227, 'colsample_bytree': 0.6316243490316744, 'min_child_weight': 1, 'gamma': 4.989815126565832, 'reg_alpha': 4.121011192352661, 'reg_lambda': 0.057469218853865967, 'max_delta_step': 8}. Best is trial 1 with value: 0.4133771929824561.

Best trial: 1. Best value: 0.413377:  18%|█▊        | 9/50 [01:15<04:50,  7.08s/it]

[I 2025-12-02 00:09:26,491] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.18870300808427853, 'n_estimators': 1272, 'subsample': 0.919235481332286, 'colsample_bytree': 0.5602613045659528, 'min_child_weight': 9, 'gamma': 0.7362841124574215, 'reg_alpha': 2.0440098273593486, 'reg_lambda': 1.7515255363398312e-07, 'max_delta_step': 1}. Best is trial 1 with value: 0.4133771929824561.

Best trial: 1. Best value: 0.413377:  20%|██        | 10/50 [01:18<03:55,  5.88s/it]

[I 2025-12-02 00:09:29,658] Trial 6 finished with value: 0.0625 and parameters: {'max_depth': 7, 'learning_rate': 0.03676774453754704, 'n_estimators': 1293, 'subsample': 0.6643718610571652, 'colsample_bytree': 0.8336911899560879, 'min_child_weight': 4, 'gamma': 4.551873983485181, 'reg_alpha': 0.00016216737842824909, 'reg_lambda': 8.826501280199881, 'max_delta_step': 2}. Best is trial 1 with value: 0.4133771929824561.

Best trial: 11. Best value: 0.460526:  22%|██▏       | 11/50 [01:25<03:53,  6.00s/it]

[I 2025-12-02 00:09:35,929] Trial 11 finished with value: 0.4605263157894737 and parameters: {'max_depth': 8, 'learning_rate': 0.14390977458965903, 'n_estimators': 273, 'subsample': 0.6588555877288085, 'colsample_bytree': 0.8112147104299345, 'min_child_weight': 3, 'gamma': 3.066014816457214, 'reg_alpha': 1.3236982207089282e-05, 'reg_lambda': 6.647857053896178e-07, 'max_delta_step': 9}. Best is trial 11 with value: 0.4605263157894737.

Best trial: 11. Best value: 0.460526:  24%|██▍       | 12/50 [01:34<04:24,  6.97s/it]

[I 2025-12-02 00:09:45,136] Trial 14 finished with value: 0.381578947368421 and parameters: {'max_depth': 5, 'learning_rate': 0.08883839298067031, 'n_estimators': 214, 'subsample': 0.5188880788122823, 'colsample_bytree': 0.9555924617838625, 'min_child_weight': 2, 'gamma': 3.208740267066344, 'reg_alpha': 0.005952854802320759, 'reg_lambda': 1.09946648843117e-08, 'max_delta_step': 7}. Best is trial 11 with value: 0.4605263157894737.

Best trial: 11. Best value: 0.460526:  26%|██▌       | 13/50 [01:36<03:22,  5.47s/it]

[I 2025-12-02 00:09:47,123] Trial 10 pruned.

Best trial: 11. Best value: 0.460526:  28%|██▊       | 14/50 [01:42<03:24,  5.68s/it]

[I 2025-12-02 00:09:53,324] Trial 12 finished with value: 0.42324561403508776 and parameters: {'max_depth': 3, 'learning_rate': 0.20850468720538157, 'n_estimators': 938, 'subsample': 0.5529334567232587, 'colsample_bytree': 0.5326852495554355, 'min_child_weight': 3, 'gamma': 3.4808321368683877, 'reg_alpha': 0.0027943449387421333, 'reg_lambda': 0.00019976223381273472, 'max_delta_step': 4}. Best is trial 11 with value: 0.4605263157894737.

Best trial: 11. Best value: 0.460526:  30%|███       | 15/50 [01:44<02:38,  4.53s/it]

[I 2025-12-02 00:09:55,183] Trial 13 finished with value: 0.32894736842105265 and parameters: {'max_depth': 5, 'learning_rate': 0.08823407425494624, 'n_estimators': 447, 'subsample': 0.5189712291859475, 'colsample_bytree': 0.9959988491110001, 'min_child_weight': 1, 'gamma': 3.157708288125609, 'reg_alpha': 0.007037895396884686, 'reg_lambda': 7.428727087062431, 'max_delta_step': 7}. Best is trial 11 with value: 0.4605263157894737.

Best trial: 11. Best value: 0.460526:  32%|███▏      | 16/50 [01:52<03:08,  5.53s/it]

[I 2025-12-02 00:10:03,039] Trial 16 finished with value: 0.34539473684210525 and parameters: {'max_depth': 6, 'learning_rate': 0.13407545563616335, 'n_estimators': 419, 'subsample': 0.7156608534800184, 'colsample_bytree': 0.9942650210710271, 'min_child_weight': 3, 'gamma': 3.739943552747295, 'reg_alpha': 1.0970422329496614e-08, 'reg_lambda': 1.724470399302678e-05, 'max_delta_step': 10}. Best is trial 11 with value: 0.4605263157894737.

Best trial: 11. Best value: 0.460526:  34%|███▍      | 17/50 [01:53<02:19,  4.23s/it]

[I 2025-12-02 00:10:04,245] Trial 15 finished with value: 0.3355263157894737 and parameters: {'max_depth': 6, 'learning_rate': 0.09850641496934531, 'n_estimators': 472, 'subsample': 0.7181172429787042, 'colsample_bytree': 0.9914122187115231, 'min_child_weight': 3, 'gamma': 3.9039301947163274, 'reg_alpha': 1.3315636960509931e-08, 'reg_lambda': 1.2220322568260067, 'max_delta_step': 9}. Best is trial 11 with value: 0.4605263157894737.

Best trial: 11. Best value: 0.460526:  36%|███▌      | 18/50 [02:00<02:40,  5.01s/it]

[I 2025-12-02 00:10:11,069] Trial 20 pruned.

Best trial: 11. Best value: 0.460526:  38%|███▊      | 19/50 [02:13<03:53,  7.52s/it]

[I 2025-12-02 00:10:24,447] Trial 17 finished with value: 0.3508771929824561 and parameters: {'max_depth': 5, 'learning_rate': 0.13856950449010963, 'n_estimators': 994, 'subsample': 0.7143378055577752, 'colsample_bytree': 0.6959998414048171, 'min_child_weight': 3, 'gamma': 2.260295102190886, 'reg_alpha': 3.637701508208176e-08, 'reg_lambda': 1.407433798289162e-05, 'max_delta_step': 3}. Best is trial 11 with value: 0.4605263157894737.

Best trial: 11. Best value: 0.460526:  40%|████      | 20/50 [02:14<02:42,  5.41s/it]

[I 2025-12-02 00:10:24,936] Trial 18 finished with value: 0.3925438596491228 and parameters: {'max_depth': 5, 'learning_rate': 0.13396731739039183, 'n_estimators': 952, 'subsample': 0.721703061327824, 'colsample_bytree': 0.6830046302365889, 'min_child_weight': 3, 'gamma': 2.1728102884455627, 'reg_alpha': 3.843140587829387e-08, 'reg_lambda': 2.0621037067735964e-05, 'max_delta_step': 4}. Best is trial 11 with value: 0.4605263157894737.

Best trial: 11. Best value: 0.460526:  42%|████▏     | 21/50 [02:24<03:19,  6.87s/it]

[I 2025-12-02 00:10:35,220] Trial 19 finished with value: 0.3508771929824561 and parameters: {'max_depth': 3, 'learning_rate': 0.047168105553333874, 'n_estimators': 1067, 'subsample': 0.7267355852437432, 'colsample_bytree': 0.7098071305215514, 'min_child_weight': 4, 'gamma': 2.2574162541563374, 'reg_alpha': 3.3549032115178664e-06, 'reg_lambda': 6.405964454901382e-07, 'max_delta_step': 4}. Best is trial 11 with value: 0.4605263157894737.

Best trial: 11. Best value: 0.460526:  44%|████▍     | 22/50 [02:29<03:01,  6.47s/it]

[I 2025-12-02 00:10:40,752] Trial 21 finished with value: 0.3969298245614035 and parameters: {'max_depth': 8, 'learning_rate': 0.13885770721606203, 'n_estimators': 955, 'subsample': 0.6801109619984694, 'colsample_bytree': 0.9005869250855401, 'min_child_weight': 4, 'gamma': 2.304671379038539, 'reg_alpha': 0.063925416238072, 'reg_lambda': 1.8789329811351242e-07, 'max_delta_step': 4}. Best is trial 11 with value: 0.4605263157894737.

Best trial: 11. Best value: 0.460526:  46%|████▌     | 23/50 [02:33<02:28,  5.49s/it]

[I 2025-12-02 00:10:43,957] Trial 24 finished with value: 0.3925438596491228 and parameters: {'max_depth': 8, 'learning_rate': 0.19002425076098645, 'n_estimators': 201, 'subsample': 0.5812234630493307, 'colsample_bytree': 0.8877525164175092, 'min_child_weight': 2, 'gamma': 3.029118654987693, 'reg_alpha': 6.986690057432559e-05, 'reg_lambda': 0.006552765697972437, 'max_delta_step': 8}. Best is trial 11 with value: 0.4605263157894737.

Best trial: 11. Best value: 0.460526:  48%|████▊     | 24/50 [02:37<02:10,  5.03s/it]

[I 2025-12-02 00:10:47,917] Trial 23 finished with value: 0.4583333333333333 and parameters: {'max_depth': 8, 'learning_rate': 0.05796105832557582, 'n_estimators': 722, 'subsample': 0.5840590957206113, 'colsample_bytree': 0.894845153374432, 'min_child_weight': 4, 'gamma': 0.01780787788874294, 'reg_alpha': 0.07154261217720422, 'reg_lambda': 4.252811773921556e-07, 'max_delta_step': 5}. Best is trial 11 with value: 0.4605263157894737.

Best trial: 11. Best value: 0.460526:  50%|█████     | 25/50 [02:38<01:39,  3.97s/it]

[I 2025-12-02 00:10:49,418] Trial 25 finished with value: 0.4024122807017544 and parameters: {'max_depth': 8, 'learning_rate': 0.1983239954130737, 'n_estimators': 200, 'subsample': 0.5845075747695424, 'colsample_bytree': 0.8905134506807537, 'min_child_weight': 2, 'gamma': 4.15621295862586, 'reg_alpha': 2.9550898683976045e-05, 'reg_lambda': 0.004003332823339657, 'max_delta_step': 8}. Best is trial 11 with value: 0.4605263157894737.

Best trial: 22. Best value: 0.5:  52%|█████▏    | 26/50 [02:40<01:21,  3.42s/it]

[I 2025-12-02 00:10:51,537] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.054193896507955475, 'n_estimators': 868, 'subsample': 0.584971992021627, 'colsample_bytree': 0.8925432784285602, 'min_child_weight': 4, 'gamma': 2.8255140100991833, 'reg_alpha': 0.13871414094114484, 'reg_lambda': 3.988436363261699e-07, 'max_delta_step': 5}. Best is trial 22 with value: 0.5.

Best trial: 22. Best value: 0.5:  54%|█████▍    | 27/50 [02:44<01:18,  3.42s/it]

[I 2025-12-02 00:10:54,955] Trial 28 pruned.

Best trial: 22. Best value: 0.5:  56%|█████▌    | 28/50 [02:46<01:05,  2.98s/it]

[I 2025-12-02 00:10:56,906] Trial 27 pruned.

Best trial: 22. Best value: 0.5:  58%|█████▊    | 29/50 [02:46<00:48,  2.32s/it]

[I 2025-12-02 00:10:57,709] Trial 29 pruned.

Best trial: 22. Best value: 0.5:  60%|██████    | 30/50 [02:49<00:45,  2.30s/it]

[I 2025-12-02 00:10:59,944] Trial 30 pruned.

Best trial: 22. Best value: 0.5:  62%|██████▏   | 31/50 [02:57<01:15,  3.97s/it]

[I 2025-12-02 00:11:07,829] Trial 31 pruned.

Best trial: 22. Best value: 0.5:  64%|██████▍   | 32/50 [02:57<00:55,  3.07s/it]

[I 2025-12-02 00:11:08,783] Trial 33 pruned.

Best trial: 22. Best value: 0.5:  66%|██████▌   | 33/50 [03:03<01:03,  3.76s/it]

[I 2025-12-02 00:11:14,148] Trial 26 finished with value: 0.49122807017543857 and parameters: {'max_depth': 7, 'learning_rate': 0.20420795528482802, 'n_estimators': 744, 'subsample': 0.568832677478705, 'colsample_bytree': 0.6132026937844155, 'min_child_weight': 1, 'gamma': 4.069864255410033, 'reg_alpha': 0.001769269562802714, 'reg_lambda': 0.00016729561282275945, 'max_delta_step': 6}. Best is trial 22 with value: 0.5.

Best trial: 22. Best value: 0.5:  68%|██████▊   | 34/50 [03:03<00:45,  2.82s/it]

[I 2025-12-02 00:11:14,780] Trial 34 pruned.

Best trial: 22. Best value: 0.5:  70%|███████   | 35/50 [03:04<00:31,  2.09s/it]

[I 2025-12-02 00:11:15,159] Trial 35 pruned.

Best trial: 22. Best value: 0.5:  72%|███████▏  | 36/50 [03:27<01:58,  8.45s/it]

[I 2025-12-02 00:11:38,469] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.041662578460127636, 'n_estimators': 868, 'subsample': 0.55282709374192, 'colsample_bytree': 0.7629927277569902, 'min_child_weight': 4, 'gamma': 4.121118405912754, 'reg_alpha': 0.001510925054240469, 'reg_lambda': 0.00011849644809860341, 'max_delta_step': 5}. Best is trial 22 with value: 0.5.

Best trial: 22. Best value: 0.5:  74%|███████▍  | 37/50 [03:30<01:29,  6.86s/it]

[I 2025-12-02 00:11:41,620] Trial 32 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.06516143160351894, 'n_estimators': 1484, 'subsample': 0.6766505586795537, 'colsample_bytree': 0.7671716285890435, 'min_child_weight': 6, 'gamma': 1.8405571537490342, 'reg_alpha': 0.0016797740079290257, 'reg_lambda': 2.7951565862802423e-06, 'max_delta_step': 5}. Best is trial 22 with value: 0.5.

Best trial: 22. Best value: 0.5:  76%|███████▌  | 38/50 [03:32<01:03,  5.31s/it]

[I 2025-12-02 00:11:43,317] Trial 37 finished with value: 0.42872807017543857 and parameters: {'max_depth': 6, 'learning_rate': 0.04096415623468322, 'n_estimators': 570, 'subsample': 0.5022739428796889, 'colsample_bytree': 0.9302224880043615, 'min_child_weight': 1, 'gamma': 4.137928497973219, 'reg_alpha': 0.0007691080089020289, 'reg_lambda': 0.00011871686938013865, 'max_delta_step': 9}. Best is trial 22 with value: 0.5.

Best trial: 22. Best value: 0.5:  78%|███████▊  | 39/50 [03:33<00:44,  4.07s/it]

[I 2025-12-02 00:11:44,488] Trial 38 finished with value: 0.4758771929824561 and parameters: {'max_depth': 6, 'learning_rate': 0.06531276166455063, 'n_estimators': 548, 'subsample': 0.6495470442264695, 'colsample_bytree': 0.9365496488041671, 'min_child_weight': 1, 'gamma': 4.008854724145132, 'reg_alpha': 6.183978739061749e-07, 'reg_lambda': 4.375823336379763e-06, 'max_delta_step': 9}. Best is trial 22 with value: 0.5.

Best trial: 22. Best value: 0.5:  80%|████████  | 40/50 [03:35<00:33,  3.31s/it]

[I 2025-12-02 00:11:46,016] Trial 40 pruned.

Best trial: 22. Best value: 0.5:  82%|████████▏ | 41/50 [03:42<00:40,  4.54s/it]

[I 2025-12-02 00:11:53,426] Trial 41 pruned.

Best trial: 22. Best value: 0.5:  84%|████████▍ | 42/50 [03:43<00:27,  3.44s/it]

[I 2025-12-02 00:11:54,302] Trial 43 pruned.

Best trial: 22. Best value: 0.5:  86%|████████▌ | 43/50 [03:43<00:17,  2.52s/it]

[I 2025-12-02 00:11:54,685] Trial 42 pruned.

Best trial: 22. Best value: 0.5:  88%|████████▊ | 44/50 [03:49<00:21,  3.52s/it]

[I 2025-12-02 00:12:00,530] Trial 46 pruned.

Best trial: 22. Best value: 0.5:  90%|█████████ | 45/50 [03:50<00:14,  2.84s/it]

[I 2025-12-02 00:12:01,789] Trial 45 pruned.

Best trial: 22. Best value: 0.5:  92%|█████████▏| 46/50 [03:51<00:08,  2.23s/it]

[I 2025-12-02 00:12:02,610] Trial 39 finished with value: 0.4758771929824561 and parameters: {'max_depth': 6, 'learning_rate': 0.11426651336476631, 'n_estimators': 529, 'subsample': 0.5000151979673816, 'colsample_bytree': 0.7451126863116746, 'min_child_weight': 1, 'gamma': 4.182921568505894, 'reg_alpha': 2.330095810560136e-05, 'reg_lambda': 4.4322535028326364e-05, 'max_delta_step': 10}. Best is trial 22 with value: 0.5.

Best trial: 22. Best value: 0.5:  94%|█████████▍| 47/50 [03:56<00:08,  2.87s/it]

[I 2025-12-02 00:12:06,969] Trial 47 pruned.

Best trial: 22. Best value: 0.5:  96%|█████████▌| 48/50 [03:56<00:04,  2.18s/it]

[I 2025-12-02 00:12:07,546] Trial 48 pruned.

Best trial: 22. Best value: 0.5:  98%|█████████▊| 49/50 [04:14<00:06,  6.95s/it]

[I 2025-12-02 00:12:25,603] Trial 49 finished with value: 0.3607456140350877 and parameters: {'max_depth': 7, 'learning_rate': 0.049960816985993715, 'n_estimators': 802, 'subsample': 0.6027356196728991, 'colsample_bytree': 0.7980710201115596, 'min_child_weight': 2, 'gamma': 4.678146798993014, 'reg_alpha': 0.00043286764646950713, 'reg_lambda': 0.0005577201649162004, 'max_delta_step': 6}. Best is trial 22 with value: 0.5.

Best trial: 22. Best value: 0.5: 100%|██████████| 50/50 [04:18<00:00,  5.16s/it]

[I 2025-12-02 00:12:29,056] Trial 44 finished with value: 0.481359649122807 and parameters: {'max_depth': 7, 'learning_rate': 0.06901392492864818, 'n_estimators': 1152, 'subsample': 0.6398289694958388, 'colsample_bytree': 0.508823762031127, 'min_child_weight': 1, 'gamma': 4.49330991138932, 'reg_alpha': 1.4753242700822882e-06, 'reg_lambda': 0.000643186687337262, 'max_delta_step': 2}. Best is trial 22 with value: 0.5.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
[I 2025-12-02 00:12:30,877] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 45, Test size: 12
Using Leave-One-Out CV with 45 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.173077:   2%|▏         | 1/50 [00:17<14:39, 17.94s/it]

[I 2025-12-02 00:12:48,809] Trial 3 finished with value: 0.17307692307692307 and parameters: {'max_depth': 3, 'learning_rate': 0.022379028789030343, 'n_estimators': 559, 'subsample': 0.6527244824306951, 'colsample_bytree': 0.8796216552989917, 'min_child_weight': 4, 'gamma': 3.9906601134027437, 'reg_alpha': 1.4112820028286238e-08, 'reg_lambda': 2.837393232662046e-08, 'max_delta_step': 2}. Best is trial 3 with value: 0.17307692307692307.

Best trial: 1. Best value: 0.288462:   4%|▍         | 2/50 [00:28<10:42, 13.39s/it]

[I 2025-12-02 00:12:59,007] Trial 1 finished with value: 0.28846153846153844 and parameters: {'max_depth': 10, 'learning_rate': 0.03964383561535089, 'n_estimators': 575, 'subsample': 0.8870711482887279, 'colsample_bytree': 0.9643986748539868, 'min_child_weight': 2, 'gamma': 3.6670311261124464, 'reg_alpha': 4.573824629123412, 'reg_lambda': 0.024168541425747755, 'max_delta_step': 10}. Best is trial 1 with value: 0.28846153846153844.

Best trial: 1. Best value: 0.288462:   6%|▌         | 3/50 [00:31<06:58,  8.91s/it]

[I 2025-12-02 00:13:02,592] Trial 0 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.10411346650741096, 'n_estimators': 1034, 'subsample': 0.6318538766389199, 'colsample_bytree': 0.8339674918811157, 'min_child_weight': 9, 'gamma': 2.100750833386197, 'reg_alpha': 0.7496341805747464, 'reg_lambda': 1.5106238070046833e-06, 'max_delta_step': 2}. Best is trial 1 with value: 0.28846153846153844.

Best trial: 1. Best value: 0.288462:   8%|▊         | 4/50 [00:43<07:36,  9.92s/it]

[I 2025-12-02 00:13:14,054] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.19756174069443702, 'n_estimators': 841, 'subsample': 0.8305172498896456, 'colsample_bytree': 0.5322008893651178, 'min_child_weight': 8, 'gamma': 1.6357958037157327, 'reg_alpha': 2.877634691266575e-05, 'reg_lambda': 0.00037056886137940427, 'max_delta_step': 2}. Best is trial 1 with value: 0.28846153846153844.

Best trial: 1. Best value: 0.288462:  10%|█         | 5/50 [00:51<07:03,  9.41s/it]

[I 2025-12-02 00:13:22,565] Trial 6 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.024007808438024154, 'n_estimators': 574, 'subsample': 0.9780495906098144, 'colsample_bytree': 0.8373053295045851, 'min_child_weight': 5, 'gamma': 4.279839554891652, 'reg_alpha': 2.5335524001112507e-05, 'reg_lambda': 0.013932266167742558, 'max_delta_step': 10}. Best is trial 1 with value: 0.28846153846153844.

Best trial: 1. Best value: 0.288462:  12%|█▏        | 6/50 [00:54<05:14,  7.15s/it]

[I 2025-12-02 00:13:25,335] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.19711569861025768, 'n_estimators': 287, 'subsample': 0.6614541937693356, 'colsample_bytree': 0.6833267806226695, 'min_child_weight': 10, 'gamma': 1.672513857175103, 'reg_alpha': 0.00020824274151234212, 'reg_lambda': 5.5758722250381095e-06, 'max_delta_step': 2}. Best is trial 1 with value: 0.28846153846153844.

Best trial: 5. Best value: 0.647773:  14%|█▍        | 7/50 [00:56<03:56,  5.49s/it]

[I 2025-12-02 00:13:27,417] Trial 5 finished with value: 0.6477732793522267 and parameters: {'max_depth': 8, 'learning_rate': 0.012725411948915733, 'n_estimators': 533, 'subsample': 0.8453051664930162, 'colsample_bytree': 0.9367571325149362, 'min_child_weight': 3, 'gamma': 3.576217817119352, 'reg_alpha': 2.884124694110314e-07, 'reg_lambda': 0.54813377227098, 'max_delta_step': 4}. Best is trial 5 with value: 0.6477732793522267.

Best trial: 5. Best value: 0.647773:  16%|█▌        | 8/50 [01:25<08:58, 12.83s/it]

[I 2025-12-02 00:13:55,949] Trial 2 finished with value: 0.5759109311740891 and parameters: {'max_depth': 9, 'learning_rate': 0.02048915263570584, 'n_estimators': 1459, 'subsample': 0.6619421134934573, 'colsample_bytree': 0.9464801142324952, 'min_child_weight': 1, 'gamma': 1.1783299060840107, 'reg_alpha': 0.9957333534030562, 'reg_lambda': 0.028501636253703652, 'max_delta_step': 5}. Best is trial 5 with value: 0.6477732793522267.

Best trial: 5. Best value: 0.647773:  18%|█▊        | 9/50 [01:27<06:32,  9.58s/it]

[I 2025-12-02 00:13:58,402] Trial 10 finished with value: 0.28846153846153844 and parameters: {'max_depth': 5, 'learning_rate': 0.08550717972631544, 'n_estimators': 1067, 'subsample': 0.7547610112869438, 'colsample_bytree': 0.5816601572650851, 'min_child_weight': 6, 'gamma': 1.787806009218707, 'reg_alpha': 0.0665274190673271, 'reg_lambda': 4.640504468308469, 'max_delta_step': 7}. Best is trial 5 with value: 0.6477732793522267.

Best trial: 5. Best value: 0.647773:  20%|██        | 10/50 [01:32<05:21,  8.04s/it]

[I 2025-12-02 00:14:02,991] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.07684008390351982, 'n_estimators': 1377, 'subsample': 0.9480309656638908, 'colsample_bytree': 0.500098633188105, 'min_child_weight': 5, 'gamma': 1.6430049070450836, 'reg_alpha': 2.2236817434245354e-06, 'reg_lambda': 1.3954489997264243e-06, 'max_delta_step': 5}. Best is trial 5 with value: 0.6477732793522267.

Best trial: 5. Best value: 0.647773:  22%|██▏       | 11/50 [01:34<04:07,  6.35s/it]

[I 2025-12-02 00:14:05,513] Trial 12 pruned.

Best trial: 5. Best value: 0.647773:  24%|██▍       | 12/50 [01:41<04:08,  6.54s/it]

[I 2025-12-02 00:14:12,495] Trial 9 finished with value: 0.597165991902834 and parameters: {'max_depth': 7, 'learning_rate': 0.020615099660813842, 'n_estimators': 1425, 'subsample': 0.9670404458437123, 'colsample_bytree': 0.7291646297986332, 'min_child_weight': 4, 'gamma': 1.702043343055157, 'reg_alpha': 5.407548025531646e-05, 'reg_lambda': 1.539988778586963e-05, 'max_delta_step': 9}. Best is trial 5 with value: 0.6477732793522267.

Best trial: 5. Best value: 0.647773:  26%|██▌       | 13/50 [01:41<02:52,  4.66s/it]

[I 2025-12-02 00:14:12,808] Trial 13 finished with value: 0.4423076923076923 and parameters: {'max_depth': 3, 'learning_rate': 0.010050161455211861, 'n_estimators': 214, 'subsample': 0.5018391993380809, 'colsample_bytree': 0.7174392396673991, 'min_child_weight': 3, 'gamma': 0.32388297084095496, 'reg_alpha': 1.295181098463177e-08, 'reg_lambda': 4.5208138878964945, 'max_delta_step': 0}. Best is trial 5 with value: 0.6477732793522267.

Best trial: 5. Best value: 0.647773:  28%|██▊       | 14/50 [01:46<02:42,  4.52s/it]

[I 2025-12-02 00:14:17,025] Trial 11 pruned.

Best trial: 5. Best value: 0.647773:  30%|███       | 15/50 [01:51<02:42,  4.65s/it]

[I 2025-12-02 00:14:21,970] Trial 16 pruned.

Best trial: 5. Best value: 0.647773:  34%|███▍      | 17/50 [02:21<04:47,  8.72s/it]

[I 2025-12-02 00:14:52,378] Trial 18 finished with value: 0.6022267206477733 and parameters: {'max_depth': 8, 'learning_rate': 0.014630567713503802, 'n_estimators': 769, 'subsample': 0.9303014155945647, 'colsample_bytree': 0.6620543523873581, 'min_child_weight': 3, 'gamma': 2.897200755586037, 'reg_alpha': 0.007978366486400285, 'reg_lambda': 2.78793119040451e-05, 'max_delta_step': 4}. Best is trial 5 with value: 0.6477732793522267.
[I 2025-12-02 00:14:52,540] Trial 17 finished with value: 0.6285425101214575 and parameters: {'max_depth': 7, 'learning_rate': 0.010192003577524117, 'n_estimators': 812, 'subsample': 0.8868362747091478, 'colsample_bytree': 0.775613586586033, 'min_child_weight': 3, 'gamma': 3.1642731011024363, 'reg_alpha': 1.0268046286419545e-06, 'reg_lambda': 0.00030787737655614056, 'max_delta_step': 7}. Best is trial 5 with value: 0.6477732793522267.

Best trial: 5. Best value: 0.647773:  36%|███▌      | 18/50 [02:32<05:00,  9.38s/it]

[I 2025-12-02 00:15:03,451] Trial 15 finished with value: 0.6477732793522267 and parameters: {'max_depth': 7, 'learning_rate': 0.010007351364512095, 'n_estimators': 1221, 'subsample': 0.8437398528758008, 'colsample_bytree': 0.7426346963931869, 'min_child_weight': 3, 'gamma': 0.014485003878876412, 'reg_alpha': 7.589067888575678e-07, 'reg_lambda': 0.6514368334009871, 'max_delta_step': 7}. Best is trial 5 with value: 0.6477732793522267.

Best trial: 5. Best value: 0.647773:  38%|███▊      | 19/50 [02:50<06:06, 11.82s/it]

[I 2025-12-02 00:15:20,936] Trial 20 finished with value: 0.47773279352226716 and parameters: {'max_depth': 6, 'learning_rate': 0.036490748201306586, 'n_estimators': 405, 'subsample': 0.7854677568262678, 'colsample_bytree': 0.993191767440329, 'min_child_weight': 1, 'gamma': 4.866289380580271, 'reg_alpha': 3.674504486445515e-07, 'reg_lambda': 0.002954216335157793, 'max_delta_step': 8}. Best is trial 5 with value: 0.6477732793522267.

Best trial: 5. Best value: 0.647773:  40%|████      | 20/50 [03:06<06:35, 13.18s/it]

[I 2025-12-02 00:15:37,300] Trial 21 finished with value: 0.47773279352226716 and parameters: {'max_depth': 6, 'learning_rate': 0.014974366972159339, 'n_estimators': 453, 'subsample': 0.7710493822214066, 'colsample_bytree': 0.9290076453626537, 'min_child_weight': 1, 'gamma': 4.9445279173212295, 'reg_alpha': 1.3957824225410357e-07, 'reg_lambda': 0.2594126165416993, 'max_delta_step': 4}. Best is trial 5 with value: 0.6477732793522267.

Best trial: 5. Best value: 0.647773:  42%|████▏     | 21/50 [03:07<04:39,  9.63s/it]

[I 2025-12-02 00:15:38,658] Trial 19 finished with value: 0.4848178137651822 and parameters: {'max_depth': 8, 'learning_rate': 0.013639642130173862, 'n_estimators': 752, 'subsample': 0.8947854957513823, 'colsample_bytree': 0.6416569234905813, 'min_child_weight': 1, 'gamma': 2.863265871670617, 'reg_alpha': 0.007081933200364416, 'reg_lambda': 1.1119961976337876e-08, 'max_delta_step': 4}. Best is trial 5 with value: 0.6477732793522267.

Best trial: 22. Best value: 0.667004:  44%|████▍     | 22/50 [03:41<07:55, 16.99s/it]

[I 2025-12-02 00:16:12,803] Trial 22 finished with value: 0.667004048582996 and parameters: {'max_depth': 8, 'learning_rate': 0.014876117894576206, 'n_estimators': 967, 'subsample': 0.712327429308318, 'colsample_bytree': 0.9134235086275361, 'min_child_weight': 2, 'gamma': 0.09800069587864926, 'reg_alpha': 0.0015466362661672565, 'reg_lambda': 0.48544580517529673, 'max_delta_step': 4}. Best is trial 22 with value: 0.667004048582996.

Best trial: 22. Best value: 0.667004:  46%|████▌     | 23/50 [03:50<06:31, 14.51s/it]

[I 2025-12-02 00:16:21,548] Trial 24 finished with value: 0.6214574898785425 and parameters: {'max_depth': 8, 'learning_rate': 0.013154734733246116, 'n_estimators': 1020, 'subsample': 0.8525848284704535, 'colsample_bytree': 0.7809614548283964, 'min_child_weight': 3, 'gamma': 3.480837764190198, 'reg_alpha': 4.166193846569134e-06, 'reg_lambda': 0.2492922982347049, 'max_delta_step': 6}. Best is trial 22 with value: 0.667004048582996.

Best trial: 22. Best value: 0.667004:  48%|████▊     | 24/50 [04:01<05:50, 13.48s/it]

[I 2025-12-02 00:16:32,624] Trial 23 finished with value: 0.6022267206477733 and parameters: {'max_depth': 8, 'learning_rate': 0.014240481244396091, 'n_estimators': 1000, 'subsample': 0.8294263355662217, 'colsample_bytree': 0.9049654006196103, 'min_child_weight': 2, 'gamma': 0.01884646198141078, 'reg_alpha': 0.002087972469373335, 'reg_lambda': 0.39267069978495867, 'max_delta_step': 4}. Best is trial 22 with value: 0.667004048582996.

Best trial: 22. Best value: 0.667004:  50%|█████     | 25/50 [04:19<06:07, 14.69s/it]

[I 2025-12-02 00:16:50,143] Trial 14 finished with value: 0.6214574898785425 and parameters: {'max_depth': 8, 'learning_rate': 0.010947724610106466, 'n_estimators': 1460, 'subsample': 0.7665644033080874, 'colsample_bytree': 0.9906706047429162, 'min_child_weight': 1, 'gamma': 0.06267787661847635, 'reg_alpha': 0.005232054145383671, 'reg_lambda': 3.991697596136013, 'max_delta_step': 5}. Best is trial 22 with value: 0.667004048582996.

Best trial: 22. Best value: 0.667004:  52%|█████▏    | 26/50 [04:32<05:39, 14.15s/it]

[I 2025-12-02 00:17:03,030] Trial 25 finished with value: 0.667004048582996 and parameters: {'max_depth': 9, 'learning_rate': 0.015949236803019132, 'n_estimators': 1008, 'subsample': 0.7037709476496978, 'colsample_bytree': 0.896988817858883, 'min_child_weight': 2, 'gamma': 0.25457479996464705, 'reg_alpha': 0.0017479116403169345, 'reg_lambda': 0.7159000279398801, 'max_delta_step': 6}. Best is trial 22 with value: 0.667004048582996.

Best trial: 22. Best value: 0.667004:  54%|█████▍    | 27/50 [04:40<04:46, 12.45s/it]

[I 2025-12-02 00:17:11,527] Trial 26 finished with value: 0.667004048582996 and parameters: {'max_depth': 9, 'learning_rate': 0.028304216848837233, 'n_estimators': 1192, 'subsample': 0.7038456165676105, 'colsample_bytree': 0.9173553958588379, 'min_child_weight': 2, 'gamma': 0.21055601568471483, 'reg_alpha': 0.0012468751565292383, 'reg_lambda': 1.0846315030852822, 'max_delta_step': 3}. Best is trial 22 with value: 0.667004048582996.

Best trial: 22. Best value: 0.667004:  56%|█████▌    | 28/50 [05:04<05:52, 16.00s/it]

[I 2025-12-02 00:17:35,799] Trial 27 finished with value: 0.667004048582996 and parameters: {'max_depth': 9, 'learning_rate': 0.027905043661406562, 'n_estimators': 1195, 'subsample': 0.715738670610501, 'colsample_bytree': 0.8532293776067938, 'min_child_weight': 2, 'gamma': 0.5007126417439718, 'reg_alpha': 0.0006430183070885837, 'reg_lambda': 9.074579385806947, 'max_delta_step': 6}. Best is trial 22 with value: 0.667004048582996.

Best trial: 22. Best value: 0.667004:  58%|█████▊    | 29/50 [05:06<04:07, 11.80s/it]

[I 2025-12-02 00:17:37,801] Trial 28 finished with value: 0.667004048582996 and parameters: {'max_depth': 9, 'learning_rate': 0.02812224516306556, 'n_estimators': 1205, 'subsample': 0.7104440791346689, 'colsample_bytree': 0.8219235362910738, 'min_child_weight': 2, 'gamma': 0.662407355292542, 'reg_alpha': 9.714251050942678e-08, 'reg_lambda': 1.0023881558432135, 'max_delta_step': 3}. Best is trial 22 with value: 0.667004048582996.

Best trial: 22. Best value: 0.667004:  60%|██████    | 30/50 [05:10<03:05,  9.26s/it]

[I 2025-12-02 00:17:41,122] Trial 29 finished with value: 0.667004048582996 and parameters: {'max_depth': 9, 'learning_rate': 0.027118515772727485, 'n_estimators': 908, 'subsample': 0.6915546904762504, 'colsample_bytree': 0.9076661701955019, 'min_child_weight': 2, 'gamma': 0.7129713980896519, 'reg_alpha': 0.00037672189993082875, 'reg_lambda': 0.05296585634461711, 'max_delta_step': 3}. Best is trial 22 with value: 0.667004048582996.

Best trial: 22. Best value: 0.667004:  62%|██████▏   | 31/50 [05:15<02:32,  8.01s/it]

[I 2025-12-02 00:17:46,233] Trial 32 pruned.

Best trial: 22. Best value: 0.667004:  64%|██████▍   | 32/50 [05:19<02:01,  6.75s/it]

[I 2025-12-02 00:17:50,024] Trial 30 finished with value: 0.6336032388663968 and parameters: {'max_depth': 9, 'learning_rate': 0.031886832812464044, 'n_estimators': 925, 'subsample': 0.7118527847310855, 'colsample_bytree': 0.8278977165374861, 'min_child_weight': 2, 'gamma': 0.6481985575916231, 'reg_alpha': 0.0005284247809707018, 'reg_lambda': 0.06665908146859202, 'max_delta_step': 3}. Best is trial 22 with value: 0.667004048582996.

Best trial: 22. Best value: 0.667004:  66%|██████▌   | 33/50 [05:20<01:27,  5.15s/it]

[I 2025-12-02 00:17:51,457] Trial 33 pruned.

Best trial: 22. Best value: 0.667004:  68%|██████▊   | 34/50 [05:29<01:40,  6.28s/it]

[I 2025-12-02 00:18:00,358] Trial 35 pruned.

Best trial: 22. Best value: 0.667004:  70%|███████   | 35/50 [05:43<02:09,  8.66s/it]

[I 2025-12-02 00:18:14,579] Trial 31 finished with value: 0.667004048582996 and parameters: {'max_depth': 10, 'learning_rate': 0.050045634597576855, 'n_estimators': 946, 'subsample': 0.7082150255401005, 'colsample_bytree': 0.9059281067208572, 'min_child_weight': 2, 'gamma': 0.7669314330313766, 'reg_alpha': 0.0691007019090634, 'reg_lambda': 0.0631584443618331, 'max_delta_step': 1}. Best is trial 22 with value: 0.667004048582996.

Best trial: 22. Best value: 0.667004:  72%|███████▏  | 36/50 [06:04<02:52, 12.30s/it]

[I 2025-12-02 00:18:35,358] Trial 38 pruned.

Best trial: 22. Best value: 0.667004:  74%|███████▍  | 37/50 [06:13<02:25, 11.20s/it]

[I 2025-12-02 00:18:44,008] Trial 34 finished with value: 0.667004048582996 and parameters: {'max_depth': 9, 'learning_rate': 0.03139918623363192, 'n_estimators': 1107, 'subsample': 0.7084882318823009, 'colsample_bytree': 0.8489078863316499, 'min_child_weight': 2, 'gamma': 0.45542045587660474, 'reg_alpha': 0.0008648094380239569, 'reg_lambda': 8.40782638624893, 'max_delta_step': 6}. Best is trial 22 with value: 0.667004048582996.

Best trial: 22. Best value: 0.667004:  76%|███████▌  | 38/50 [06:18<01:53,  9.48s/it]

[I 2025-12-02 00:18:49,487] Trial 40 pruned.

Best trial: 22. Best value: 0.667004:  78%|███████▊  | 39/50 [06:26<01:39,  9.02s/it]

[I 2025-12-02 00:18:57,428] Trial 41 pruned.

Best trial: 22. Best value: 0.667004:  80%|████████  | 40/50 [06:35<01:29,  8.95s/it]

[I 2025-12-02 00:19:06,200] Trial 36 finished with value: 0.6477732793522267 and parameters: {'max_depth': 9, 'learning_rate': 0.016651350032754253, 'n_estimators': 1142, 'subsample': 0.6941430288473743, 'colsample_bytree': 0.8579017502994708, 'min_child_weight': 2, 'gamma': 0.38871569078687296, 'reg_alpha': 0.0019473096754755832, 'reg_lambda': 9.294009382342473, 'max_delta_step': 6}. Best is trial 22 with value: 0.667004048582996.

Best trial: 22. Best value: 0.667004:  82%|████████▏ | 41/50 [06:39<01:06,  7.39s/it]

[I 2025-12-02 00:19:09,951] Trial 42 pruned.

Best trial: 22. Best value: 0.667004:  84%|████████▍ | 42/50 [06:53<01:15,  9.49s/it]

[I 2025-12-02 00:19:24,349] Trial 37 finished with value: 0.667004048582996 and parameters: {'max_depth': 9, 'learning_rate': 0.017967666385119707, 'n_estimators': 1298, 'subsample': 0.7253197920064999, 'colsample_bytree': 0.9608399908269633, 'min_child_weight': 2, 'gamma': 0.3363787791686883, 'reg_alpha': 0.001414200118772365, 'reg_lambda': 8.29794644952669, 'max_delta_step': 6}. Best is trial 22 with value: 0.667004048582996.

Best trial: 22. Best value: 0.667004:  86%|████████▌ | 43/50 [06:57<00:55,  7.89s/it]

[I 2025-12-02 00:19:28,507] Trial 39 finished with value: 0.6022267206477733 and parameters: {'max_depth': 9, 'learning_rate': 0.017979269216836843, 'n_estimators': 1128, 'subsample': 0.7260653162044514, 'colsample_bytree': 0.8626543581808417, 'min_child_weight': 2, 'gamma': 2.316171588107543, 'reg_alpha': 8.979965437745e-05, 'reg_lambda': 1.7643284908512278, 'max_delta_step': 6}. Best is trial 22 with value: 0.667004048582996.

Best trial: 43. Best value: 0.705466:  88%|████████▊ | 44/50 [07:18<01:10, 11.67s/it]

[I 2025-12-02 00:19:49,007] Trial 43 finished with value: 0.7054655870445343 and parameters: {'max_depth': 10, 'learning_rate': 0.0646626896129718, 'n_estimators': 1290, 'subsample': 0.7364478589022434, 'colsample_bytree': 0.925814900425232, 'min_child_weight': 3, 'gamma': 1.0639463054190417, 'reg_alpha': 1.189349750408475e-05, 'reg_lambda': 0.16127922456134566, 'max_delta_step': 3}. Best is trial 43 with value: 0.7054655870445343.

Best trial: 43. Best value: 0.705466:  90%|█████████ | 45/50 [07:23<00:49,  9.85s/it]

[I 2025-12-02 00:19:54,591] Trial 44 finished with value: 0.6740890688259109 and parameters: {'max_depth': 9, 'learning_rate': 0.02533401888653668, 'n_estimators': 1224, 'subsample': 0.7376858104837253, 'colsample_bytree': 0.9283930070331159, 'min_child_weight': 3, 'gamma': 0.9603355151162246, 'reg_alpha': 0.0001179075264884094, 'reg_lambda': 1.4334161369402325, 'max_delta_step': 3}. Best is trial 43 with value: 0.7054655870445343.

Best trial: 43. Best value: 0.705466:  92%|█████████▏| 46/50 [07:29<00:34,  8.53s/it]

[I 2025-12-02 00:20:00,044] Trial 47 pruned.

Best trial: 43. Best value: 0.705466:  94%|█████████▍| 47/50 [07:30<00:19,  6.42s/it]

[I 2025-12-02 00:20:01,561] Trial 45 finished with value: 0.667004048582996 and parameters: {'max_depth': 8, 'learning_rate': 0.025756758779336468, 'n_estimators': 1010, 'subsample': 0.6780146089575548, 'colsample_bytree': 0.8187663919801305, 'min_child_weight': 3, 'gamma': 1.0181854345373988, 'reg_alpha': 5.233429239845987e-05, 'reg_lambda': 1.7672190807551171, 'max_delta_step': 3}. Best is trial 43 with value: 0.7054655870445343.

Best trial: 43. Best value: 0.705466:  96%|█████████▌| 48/50 [07:34<00:11,  5.51s/it]

[I 2025-12-02 00:20:04,951] Trial 48 pruned.

Best trial: 43. Best value: 0.705466:  98%|█████████▊| 49/50 [07:38<00:05,  5.14s/it]

[I 2025-12-02 00:20:09,204] Trial 49 pruned.

Best trial: 43. Best value: 0.705466: 100%|██████████| 50/50 [07:39<00:00,  9.18s/it]

[I 2025-12-02 00:20:10,042] Trial 46 finished with value: 0.6214574898785425 and parameters: {'max_depth': 8, 'learning_rate': 0.0252347331104699, 'n_estimators': 1218, 'subsample': 0.6795385581506114, 'colsample_bytree': 0.8222969123560847, 'min_child_weight': 3, 'gamma': 0.9607064753985723, 'reg_alpha': 2.4358707320119213e-05, 'reg_lambda': 1.2050752818675137, 'max_delta_step': 3}. Best is trial 43 with value: 0.7054655870445343.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.711670                0.733333      0.800000
1    15_1         loo       0.635789                0.585714      0.514286
2    19_1         loo       0.500000                0.500000      0.500000
3    17_1         loo       0.705466                0.485714      0.514286

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.466667          0.666667               0.8        50          42
1  0.169031          0.571429               0.6        50          44
2  0.000000          1.000000               0.0        50          43
3 -0.028571          0.571429               0.4        50          45

   test_size
0         11
1         12
2         11
3         12
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.711670                0.733333      0.800000
1    15_1         loo       0.635789                0.585714      0.514286
2    19_1         loo       0.500000                0.500000      0.500000
3    17_1         loo       0.705466                0.485714      0.514286

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.466667          0.666667               0.8        50          42
1  0.169031          0.571429               0.6        50          44
2  0.000000          1.000000               0.0        50          43
3 -0.028571          0.571429               0.4        50          45

   test_size
0         11
1         12
2         11
3         12

In [ ]:

datasets = task_hf_compensated_temp_emb_lbl_ad_lbd

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_lbd_{CV_STRATEGY}_tasks/xgb_results_handcrafted_temporal_emb_compensated_ad_lbd_extended_{CV_STRATEGY}_tasks",
    split_param= "diagnosis_y",
)
print(summary)

[I 2025-12-02 00:20:15,657] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 42, Test size: 11
Using Leave-One-Out CV with 42 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.519451:   2%|▏         | 1/50 [00:11<09:30, 11.64s/it]

[I 2025-12-02 00:20:27,295] Trial 0 finished with value: 0.5194508009153318 and parameters: {'max_depth': 4, 'learning_rate': 0.02648501388677112, 'n_estimators': 300, 'subsample': 0.7749677704294118, 'colsample_bytree': 0.7103380243896111, 'min_child_weight': 2, 'gamma': 3.5556378268411355, 'reg_alpha': 2.0203476334495743e-07, 'reg_lambda': 0.012506584221013601, 'max_delta_step': 8}. Best is trial 0 with value: 0.5194508009153318.

Best trial: 2. Best value: 0.589245:   4%|▍         | 2/50 [00:17<06:25,  8.03s/it]

[I 2025-12-02 00:20:32,789] Trial 2 finished with value: 0.5892448512585813 and parameters: {'max_depth': 9, 'learning_rate': 0.020952371307882654, 'n_estimators': 352, 'subsample': 0.9457475583822019, 'colsample_bytree': 0.7700710591105144, 'min_child_weight': 1, 'gamma': 3.7755063256113504, 'reg_alpha': 3.216495673941447e-06, 'reg_lambda': 1.942931324311765e-08, 'max_delta_step': 7}. Best is trial 2 with value: 0.5892448512585813.

Best trial: 2. Best value: 0.589245:   6%|▌         | 3/50 [00:31<08:33, 10.92s/it]

[I 2025-12-02 00:20:47,152] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.15271466765559322, 'n_estimators': 1069, 'subsample': 0.5603859764593258, 'colsample_bytree': 0.7543113614647672, 'min_child_weight': 10, 'gamma': 4.2250056359658625, 'reg_alpha': 0.6422209793289494, 'reg_lambda': 9.895672835371352e-08, 'max_delta_step': 6}. Best is trial 2 with value: 0.5892448512585813.

Best trial: 2. Best value: 0.589245:   8%|▊         | 4/50 [00:37<06:55,  9.03s/it]

[I 2025-12-02 00:20:53,287] Trial 4 finished with value: 0.21052631578947367 and parameters: {'max_depth': 10, 'learning_rate': 0.21062911618121874, 'n_estimators': 834, 'subsample': 0.6416879171665512, 'colsample_bytree': 0.570389091261987, 'min_child_weight': 6, 'gamma': 4.107147208668783, 'reg_alpha': 3.8883071793650364e-07, 'reg_lambda': 0.002707536715792656, 'max_delta_step': 2}. Best is trial 2 with value: 0.5892448512585813.

Best trial: 2. Best value: 0.589245:  10%|█         | 5/50 [00:39<04:50,  6.46s/it]

[I 2025-12-02 00:20:55,181] Trial 3 finished with value: 0.448512585812357 and parameters: {'max_depth': 3, 'learning_rate': 0.13973166592513347, 'n_estimators': 1214, 'subsample': 0.8900739394130851, 'colsample_bytree': 0.9661424054134987, 'min_child_weight': 4, 'gamma': 4.214167180798894, 'reg_alpha': 0.6001400312008047, 'reg_lambda': 7.769991736837693, 'max_delta_step': 8}. Best is trial 2 with value: 0.5892448512585813.

Best trial: 2. Best value: 0.589245:  12%|█▏        | 6/50 [00:48<05:20,  7.30s/it]

[I 2025-12-02 00:21:04,104] Trial 5 finished with value: 0.47139588100686497 and parameters: {'max_depth': 10, 'learning_rate': 0.07384902849135948, 'n_estimators': 902, 'subsample': 0.9513410754921774, 'colsample_bytree': 0.5347079439527798, 'min_child_weight': 3, 'gamma': 4.174674119840917, 'reg_alpha': 7.046451413597308e-06, 'reg_lambda': 0.0021429909898783603, 'max_delta_step': 2}. Best is trial 2 with value: 0.5892448512585813.

Best trial: 2. Best value: 0.589245:  14%|█▍        | 7/50 [01:06<07:42, 10.76s/it]

[I 2025-12-02 00:21:21,999] Trial 9 finished with value: 0.39244851258581237 and parameters: {'max_depth': 3, 'learning_rate': 0.025219919317517256, 'n_estimators': 447, 'subsample': 0.937093760465981, 'colsample_bytree': 0.6815950755846079, 'min_child_weight': 2, 'gamma': 3.7708481189387233, 'reg_alpha': 3.5661341034887926, 'reg_lambda': 5.060245719100807e-06, 'max_delta_step': 3}. Best is trial 2 with value: 0.5892448512585813.

Best trial: 2. Best value: 0.589245:  16%|█▌        | 8/50 [01:07<05:19,  7.62s/it]

[I 2025-12-02 00:21:22,890] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.034705420274608365, 'n_estimators': 854, 'subsample': 0.5886327795227668, 'colsample_bytree': 0.9199427264225873, 'min_child_weight': 10, 'gamma': 4.87868952042997, 'reg_alpha': 3.022287676863739e-07, 'reg_lambda': 1.1368666003024221e-06, 'max_delta_step': 2}. Best is trial 2 with value: 0.5892448512585813.

Best trial: 2. Best value: 0.589245:  18%|█▊        | 9/50 [01:07<03:40,  5.37s/it]

[I 2025-12-02 00:21:23,313] Trial 6 finished with value: 0.02631578947368421 and parameters: {'max_depth': 6, 'learning_rate': 0.02920021316788921, 'n_estimators': 1122, 'subsample': 0.7233487059163068, 'colsample_bytree': 0.7217950715132047, 'min_child_weight': 6, 'gamma': 2.677525270834616, 'reg_alpha': 0.002047774668254623, 'reg_lambda': 0.6778592624811975, 'max_delta_step': 2}. Best is trial 2 with value: 0.5892448512585813.

Best trial: 2. Best value: 0.589245:  20%|██        | 10/50 [01:17<04:30,  6.76s/it]

[I 2025-12-02 00:21:33,179] Trial 12 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.26213498511225036, 'n_estimators': 286, 'subsample': 0.7805334662305805, 'colsample_bytree': 0.785865228596587, 'min_child_weight': 9, 'gamma': 2.633910081923541, 'reg_alpha': 7.36338508908553, 'reg_lambda': 0.014103504745715386, 'max_delta_step': 7}. Best is trial 2 with value: 0.5892448512585813.

Best trial: 2. Best value: 0.589245:  22%|██▏       | 11/50 [01:17<03:05,  4.76s/it]

[I 2025-12-02 00:21:33,420] Trial 10 pruned.
[I 2025-12-02 00:21:33,494] Trial 11 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.22802448867190517, 'n_estimators': 267, 'subsample': 0.6524823247761851, 'colsample_bytree': 0.5209320850126886, 'min_child_weight': 1, 'gamma': 2.4210796887942925, 'reg_alpha': 7.317713335297206, 'reg_lambda': 9.938153277256389e-05, 'max_delta_step': 5}. Best is trial 2 with value: 0.5892448512585813.

Best trial: 2. Best value: 0.589245:  26%|██▌       | 13/50 [01:20<01:57,  3.18s/it]

[I 2025-12-02 00:21:36,152] Trial 7 pruned.

Best trial: 2. Best value: 0.589245:  28%|██▊       | 14/50 [01:45<05:09,  8.60s/it]

[I 2025-12-02 00:22:01,015] Trial 16 finished with value: 0.545766590389016 and parameters: {'max_depth': 8, 'learning_rate': 0.010812302384373768, 'n_estimators': 553, 'subsample': 0.8359045788224709, 'colsample_bytree': 0.6346653047407383, 'min_child_weight': 1, 'gamma': 1.0500748767563794, 'reg_alpha': 1.0334420887891603e-08, 'reg_lambda': 0.08216377597753843, 'max_delta_step': 10}. Best is trial 2 with value: 0.5892448512585813.
[I 2025-12-02 00:22:01,101] Trial 14 finished with value: 0.5194508009153318 and parameters: {'max_depth': 8, 'learning_rate': 0.01022186406091993, 'n_estimators': 478, 'subsample': 0.8227888871585767, 'colsample_bytree': 0.848210736677467, 'min_child_weight': 1, 'gamma': 0.72665725899113, 'reg_alpha': 1.80880905489993e-08, 'reg_lambda': 8.017395358396355e-05, 'max_delta_step': 10}. Best is trial 2 with value: 0.5892448512585813.

Best trial: 2. Best value: 0.589245:  32%|███▏      | 16/50 [01:46<02:57,  5.23s/it]

[I 2025-12-02 00:22:02,064] Trial 15 finished with value: 0.5194508009153318 and parameters: {'max_depth': 5, 'learning_rate': 0.012153608726133934, 'n_estimators': 542, 'subsample': 0.8307692144720121, 'colsample_bytree': 0.8448696394559896, 'min_child_weight': 1, 'gamma': 0.47397642237629745, 'reg_alpha': 1.6261634677348845e-08, 'reg_lambda': 0.062183266352034694, 'max_delta_step': 10}. Best is trial 2 with value: 0.5892448512585813.

Best trial: 2. Best value: 0.589245:  34%|███▍      | 17/50 [01:48<02:31,  4.58s/it]

[I 2025-12-02 00:22:04,437] Trial 18 pruned.

Best trial: 2. Best value: 0.589245:  36%|███▌      | 18/50 [01:50<02:06,  3.97s/it]

[I 2025-12-02 00:22:06,534] Trial 19 pruned.

Best trial: 13. Best value: 0.606407:  38%|███▊      | 19/50 [01:56<02:13,  4.32s/it]

[I 2025-12-02 00:22:11,848] Trial 13 finished with value: 0.6064073226544622 and parameters: {'max_depth': 8, 'learning_rate': 0.06033244463669305, 'n_estimators': 1480, 'subsample': 0.9964233203804717, 'colsample_bytree': 0.8605071500180288, 'min_child_weight': 1, 'gamma': 0.2634176939634312, 'reg_alpha': 0.0007952324351851321, 'reg_lambda': 1.1490745433580664e-08, 'max_delta_step': 10}. Best is trial 13 with value: 0.6064073226544622.

Best trial: 13. Best value: 0.606407:  40%|████      | 20/50 [02:10<03:32,  7.09s/it]

[I 2025-12-02 00:22:26,379] Trial 21 finished with value: 0.4977116704805492 and parameters: {'max_depth': 9, 'learning_rate': 0.05235173209268174, 'n_estimators': 691, 'subsample': 0.900642772274573, 'colsample_bytree': 0.635692674371396, 'min_child_weight': 3, 'gamma': 1.777170412976172, 'reg_alpha': 1.575627496073261e-06, 'reg_lambda': 1.3022781904488224e-08, 'max_delta_step': 7}. Best is trial 13 with value: 0.6064073226544622.

Best trial: 13. Best value: 0.606407:  42%|████▏     | 21/50 [02:11<02:36,  5.39s/it]

[I 2025-12-02 00:22:27,379] Trial 20 finished with value: 0.5411899313501144 and parameters: {'max_depth': 9, 'learning_rate': 0.015876566633810377, 'n_estimators': 693, 'subsample': 0.8980709310456554, 'colsample_bytree': 0.6395436577407516, 'min_child_weight': 3, 'gamma': 1.454021204602422, 'reg_alpha': 0.0006023978204279028, 'reg_lambda': 7.77797326686618e-06, 'max_delta_step': 5}. Best is trial 13 with value: 0.6064073226544622.

Best trial: 13. Best value: 0.606407:  44%|████▍     | 22/50 [02:18<02:43,  5.85s/it]

[I 2025-12-02 00:22:34,398] Trial 23 pruned.
[I 2025-12-02 00:22:34,481] Trial 17 finished with value: 0.562929061784897 and parameters: {'max_depth': 8, 'learning_rate': 0.01001026376852642, 'n_estimators': 561, 'subsample': 0.9886999891693741, 'colsample_bytree': 0.6342195366089208, 'min_child_weight': 1, 'gamma': 0.24507507005202833, 'reg_alpha': 1.505415244756308e-08, 'reg_lambda': 1.777614676512209e-05, 'max_delta_step': 10}. Best is trial 13 with value: 0.6064073226544622.

Best trial: 13. Best value: 0.606407:  48%|████▊     | 24/50 [02:24<01:58,  4.54s/it]

[I 2025-12-02 00:22:40,259] Trial 24 finished with value: 0.6064073226544622 and parameters: {'max_depth': 9, 'learning_rate': 0.07486622231456173, 'n_estimators': 362, 'subsample': 0.9668897496196784, 'colsample_bytree': 0.8546924895774576, 'min_child_weight': 2, 'gamma': 0.13812207591478654, 'reg_alpha': 0.0057099966087134245, 'reg_lambda': 5.932260670139121e-07, 'max_delta_step': 9}. Best is trial 13 with value: 0.6064073226544622.

Best trial: 13. Best value: 0.606407:  50%|█████     | 25/50 [02:32<02:11,  5.27s/it]

[I 2025-12-02 00:22:47,820] Trial 25 finished with value: 0.4496567505720824 and parameters: {'max_depth': 8, 'learning_rate': 0.04428905869202817, 'n_estimators': 359, 'subsample': 0.5045505292569147, 'colsample_bytree': 0.8128169257947336, 'min_child_weight': 2, 'gamma': 0.8339350316100594, 'reg_alpha': 0.006675811261503575, 'reg_lambda': 2.416723482390258e-07, 'max_delta_step': 9}. Best is trial 13 with value: 0.6064073226544622.

Best trial: 13. Best value: 0.606407:  52%|█████▏    | 26/50 [02:33<01:43,  4.33s/it]

[I 2025-12-02 00:22:49,421] Trial 22 finished with value: 0.5194508009153318 and parameters: {'max_depth': 9, 'learning_rate': 0.06205756819160498, 'n_estimators': 1340, 'subsample': 0.9184770574699969, 'colsample_bytree': 0.8669875200086878, 'min_child_weight': 3, 'gamma': 1.7955964720515234, 'reg_alpha': 0.003988851177017467, 'reg_lambda': 2.00365928347431e-07, 'max_delta_step': 8}. Best is trial 13 with value: 0.6064073226544622.

Best trial: 13. Best value: 0.606407:  54%|█████▍    | 27/50 [02:35<01:22,  3.58s/it]

[I 2025-12-02 00:22:50,959] Trial 27 finished with value: 0.5583524027459954 and parameters: {'max_depth': 9, 'learning_rate': 0.05180718208502472, 'n_estimators': 201, 'subsample': 0.9354937338655882, 'colsample_bytree': 0.900091790131541, 'min_child_weight': 2, 'gamma': 0.05803227816991363, 'reg_alpha': 0.01381699254054468, 'reg_lambda': 3.486087074938003e-07, 'max_delta_step': 8}. Best is trial 13 with value: 0.6064073226544622.

Best trial: 13. Best value: 0.606407:  56%|█████▌    | 28/50 [02:35<00:58,  2.65s/it]

[I 2025-12-02 00:22:51,200] Trial 26 finished with value: 0.5755148741418764 and parameters: {'max_depth': 7, 'learning_rate': 0.04547183679550981, 'n_estimators': 407, 'subsample': 0.9953824393040995, 'colsample_bytree': 0.8907754301950745, 'min_child_weight': 2, 'gamma': 0.042540960120584226, 'reg_alpha': 0.006278764314860401, 'reg_lambda': 3.53890259756568e-07, 'max_delta_step': 8}. Best is trial 13 with value: 0.6064073226544622.

Best trial: 28. Best value: 0.659039:  58%|█████▊    | 29/50 [02:41<01:13,  3.50s/it]

[I 2025-12-02 00:22:56,852] Trial 28 finished with value: 0.6590389016018307 and parameters: {'max_depth': 9, 'learning_rate': 0.10562874242278408, 'n_estimators': 219, 'subsample': 0.9484695141377658, 'colsample_bytree': 0.9146921254433826, 'min_child_weight': 2, 'gamma': 0.017357237929046365, 'reg_alpha': 0.02256397731447275, 'reg_lambda': 5.0089107175290375e-08, 'max_delta_step': 8}. Best is trial 28 with value: 0.6590389016018307.

Best trial: 28. Best value: 0.659039:  60%|██████    | 30/50 [02:42<00:54,  2.74s/it]

[I 2025-12-02 00:22:57,725] Trial 31 pruned.

Best trial: 28. Best value: 0.659039:  62%|██████▏   | 31/50 [02:48<01:10,  3.69s/it]

[I 2025-12-02 00:23:03,719] Trial 32 pruned.

Best trial: 28. Best value: 0.659039:  64%|██████▍   | 32/50 [02:49<00:53,  2.97s/it]

[I 2025-12-02 00:23:04,941] Trial 29 finished with value: 0.5892448512585813 and parameters: {'max_depth': 7, 'learning_rate': 0.10317411826433692, 'n_estimators': 381, 'subsample': 0.9621496787490146, 'colsample_bytree': 0.9215442382233592, 'min_child_weight': 2, 'gamma': 2.948804450960833, 'reg_alpha': 0.038239433281745526, 'reg_lambda': 1.0674914409984461e-08, 'max_delta_step': 7}. Best is trial 28 with value: 0.6590389016018307.

Best trial: 28. Best value: 0.659039:  66%|██████▌   | 33/50 [02:50<00:43,  2.54s/it]

[I 2025-12-02 00:23:06,455] Trial 33 finished with value: 0.6155606407322655 and parameters: {'max_depth': 7, 'learning_rate': 0.09928844862629155, 'n_estimators': 200, 'subsample': 0.8695463922296729, 'colsample_bytree': 0.8177375041840991, 'min_child_weight': 2, 'gamma': 0.46556513931512633, 'reg_alpha': 0.0768084951121718, 'reg_lambda': 1.3583584601478637e-06, 'max_delta_step': 9}. Best is trial 28 with value: 0.6590389016018307.

Best trial: 28. Best value: 0.659039:  68%|██████▊   | 34/50 [02:59<01:08,  4.26s/it]

[I 2025-12-02 00:23:14,802] Trial 36 finished with value: 0.5892448512585813 and parameters: {'max_depth': 6, 'learning_rate': 0.12818678149611887, 'n_estimators': 201, 'subsample': 0.8697923473027399, 'colsample_bytree': 0.8117793090603682, 'min_child_weight': 2, 'gamma': 1.039286117069762, 'reg_alpha': 0.251766110645231, 'reg_lambda': 1.522669469240532e-06, 'max_delta_step': 9}. Best is trial 28 with value: 0.6590389016018307.

Best trial: 28. Best value: 0.659039:  70%|███████   | 35/50 [02:59<00:45,  3.06s/it]

[I 2025-12-02 00:23:15,023] Trial 35 finished with value: 0.562929061784897 and parameters: {'max_depth': 9, 'learning_rate': 0.1397214051494961, 'n_estimators': 215, 'subsample': 0.8617174851521459, 'colsample_bytree': 0.9988284183399907, 'min_child_weight': 1, 'gamma': 1.105900499540526, 'reg_alpha': 0.00015834814972269718, 'reg_lambda': 4.555604342217637e-08, 'max_delta_step': 6}. Best is trial 28 with value: 0.6590389016018307.

Best trial: 28. Best value: 0.659039:  72%|███████▏  | 36/50 [03:00<00:35,  2.51s/it]

[I 2025-12-02 00:23:16,255] Trial 34 finished with value: 0.6155606407322655 and parameters: {'max_depth': 9, 'learning_rate': 0.10182203008002215, 'n_estimators': 341, 'subsample': 0.8560403481188837, 'colsample_bytree': 0.811916046459825, 'min_child_weight': 2, 'gamma': 2.1230925162265395, 'reg_alpha': 0.07428466043501102, 'reg_lambda': 1.6062277123629415e-06, 'max_delta_step': 7}. Best is trial 28 with value: 0.6590389016018307.

Best trial: 28. Best value: 0.659039:  74%|███████▍  | 37/50 [03:02<00:31,  2.41s/it]

[I 2025-12-02 00:23:18,424] Trial 39 pruned.

Best trial: 28. Best value: 0.659039:  76%|███████▌  | 38/50 [03:09<00:45,  3.77s/it]

[I 2025-12-02 00:23:25,390] Trial 38 finished with value: 0.5194508009153318 and parameters: {'max_depth': 5, 'learning_rate': 0.17187805262435968, 'n_estimators': 293, 'subsample': 0.9213750177511246, 'colsample_bytree': 0.8190451925540251, 'min_child_weight': 3, 'gamma': 0.3736136936825468, 'reg_alpha': 0.14430843732993143, 'reg_lambda': 1.2670184452582805e-06, 'max_delta_step': 8}. Best is trial 28 with value: 0.6590389016018307.

Best trial: 28. Best value: 0.659039:  80%|████████  | 40/50 [03:10<00:20,  2.09s/it]

[I 2025-12-02 00:23:26,350] Trial 30 finished with value: 0.6327231121281465 and parameters: {'max_depth': 7, 'learning_rate': 0.09730039182992557, 'n_estimators': 974, 'subsample': 0.9655885903025427, 'colsample_bytree': 0.9099541046586033, 'min_child_weight': 2, 'gamma': 3.1529885599085277, 'reg_alpha': 8.724244617587462e-05, 'reg_lambda': 1.2737137654135974e-08, 'max_delta_step': 7}. Best is trial 28 with value: 0.6590389016018307.
[I 2025-12-02 00:23:26,462] Trial 37 finished with value: 0.5675057208237986 and parameters: {'max_depth': 5, 'learning_rate': 0.08002871143691846, 'n_estimators': 284, 'subsample': 0.9139729978771403, 'colsample_bytree': 0.9965391498069827, 'min_child_weight': 3, 'gamma': 0.3927032565747337, 'reg_alpha': 0.1557242854816791, 'reg_lambda': 6.750835034451896e-08, 'max_delta_step': 6}. Best is trial 28 with value: 0.6590389016018307.

Best trial: 28. Best value: 0.659039:  82%|████████▏ | 41/50 [03:18<00:34,  3.85s/it]

[I 2025-12-02 00:23:34,435] Trial 41 pruned.

Best trial: 28. Best value: 0.659039:  84%|████████▍ | 42/50 [03:19<00:23,  2.98s/it]

[I 2025-12-02 00:23:35,400] Trial 42 pruned.
[I 2025-12-02 00:23:35,458] Trial 43 pruned.

Best trial: 28. Best value: 0.659039:  88%|████████▊ | 44/50 [03:27<00:20,  3.42s/it]

[I 2025-12-02 00:23:43,252] Trial 40 finished with value: 0.5938215102974829 and parameters: {'max_depth': 5, 'learning_rate': 0.18507479029263968, 'n_estimators': 763, 'subsample': 0.9132610536230499, 'colsample_bytree': 0.8223058117903065, 'min_child_weight': 3, 'gamma': 0.4382681784408692, 'reg_alpha': 0.8658230399879138, 'reg_lambda': 1.933087832356123e-06, 'max_delta_step': 7}. Best is trial 28 with value: 0.6590389016018307.

Best trial: 28. Best value: 0.659039:  90%|█████████ | 45/50 [03:43<00:32,  6.52s/it]

[I 2025-12-02 00:23:59,192] Trial 44 finished with value: 0.49313501144164756 and parameters: {'max_depth': 6, 'learning_rate': 0.08567769443359427, 'n_estimators': 777, 'subsample': 0.8724253279210239, 'colsample_bytree': 0.8937105545513145, 'min_child_weight': 2, 'gamma': 3.177410797382426, 'reg_alpha': 0.0006675385491368718, 'reg_lambda': 2.803903363674357e-08, 'max_delta_step': 7}. Best is trial 28 with value: 0.6590389016018307.

Best trial: 28. Best value: 0.659039:  92%|█████████▏| 46/50 [03:46<00:21,  5.49s/it]

[I 2025-12-02 00:24:01,776] Trial 46 finished with value: 0.5366132723112128 and parameters: {'max_depth': 7, 'learning_rate': 0.0874870992387592, 'n_estimators': 804, 'subsample': 0.8826586682208774, 'colsample_bytree': 0.9526246889136875, 'min_child_weight': 1, 'gamma': 0.826365713573567, 'reg_alpha': 0.000864992659530618, 'reg_lambda': 1.0586339963028782e-07, 'max_delta_step': 8}. Best is trial 28 with value: 0.6590389016018307.

Best trial: 28. Best value: 0.659039:  94%|█████████▍| 47/50 [03:56<00:20,  6.95s/it]

[I 2025-12-02 00:24:12,640] Trial 45 finished with value: 0.5194508009153318 and parameters: {'max_depth': 6, 'learning_rate': 0.08708381066090821, 'n_estimators': 1206, 'subsample': 0.8760259862012065, 'colsample_bytree': 0.8299530099495436, 'min_child_weight': 2, 'gamma': 4.610515722761614, 'reg_alpha': 0.016492918134053163, 'reg_lambda': 3.0969538365970495e-08, 'max_delta_step': 7}. Best is trial 28 with value: 0.6590389016018307.

Best trial: 28. Best value: 0.659039:  96%|█████████▌| 48/50 [04:01<00:12,  6.37s/it]

[I 2025-12-02 00:24:17,519] Trial 47 finished with value: 0.47139588100686497 and parameters: {'max_depth': 7, 'learning_rate': 0.08294738318288848, 'n_estimators': 1022, 'subsample': 0.8861526591814919, 'colsample_bytree': 0.9505941307793395, 'min_child_weight': 1, 'gamma': 3.0356527296588185, 'reg_alpha': 0.0008117425830655045, 'reg_lambda': 2.9379855158448626e-08, 'max_delta_step': 8}. Best is trial 28 with value: 0.6590389016018307.

Best trial: 28. Best value: 0.659039:  98%|█████████▊| 49/50 [04:18<00:09,  9.40s/it]

[I 2025-12-02 00:24:34,498] Trial 49 finished with value: 0.5846681922196796 and parameters: {'max_depth': 7, 'learning_rate': 0.06400000282589573, 'n_estimators': 1299, 'subsample': 0.973052852580113, 'colsample_bytree': 0.8789700386848598, 'min_child_weight': 2, 'gamma': 3.8000821037409036, 'reg_alpha': 0.0160518021859794, 'reg_lambda': 2.559590950634171e-05, 'max_delta_step': 8}. Best is trial 28 with value: 0.6590389016018307.

Best trial: 28. Best value: 0.659039: 100%|██████████| 50/50 [04:20<00:00,  5.21s/it]

[I 2025-12-02 00:24:36,402] Trial 48 finished with value: 0.545766590389016 and parameters: {'max_depth': 7, 'learning_rate': 0.0633726623030265, 'n_estimators': 1329, 'subsample': 0.8822586726662365, 'colsample_bytree': 0.8741336301443638, 'min_child_weight': 1, 'gamma': 4.629590124387632, 'reg_alpha': 0.01763586906039825, 'reg_lambda': 3.8239583583646574e-05, 'max_delta_step': 8}. Best is trial 28 with value: 0.6590389016018307.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 00:24:40,726] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 44, Test size: 12
Using Leave-One-Out CV with 44 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.417895:   2%|▏         | 1/50 [00:13<10:56, 13.39s/it]

[I 2025-12-02 00:24:54,094] Trial 1 finished with value: 0.41789473684210526 and parameters: {'max_depth': 7, 'learning_rate': 0.10031339242644527, 'n_estimators': 357, 'subsample': 0.9293223767844376, 'colsample_bytree': 0.6547694470570428, 'min_child_weight': 3, 'gamma': 1.9750774562206541, 'reg_alpha': 1.9577509561248793e-08, 'reg_lambda': 0.0002581180247428937, 'max_delta_step': 10}. Best is trial 1 with value: 0.41789473684210526.

Best trial: 4. Best value: 0.464211:   4%|▍         | 2/50 [00:24<09:31, 11.91s/it]

[I 2025-12-02 00:25:04,982] Trial 4 finished with value: 0.4642105263157895 and parameters: {'max_depth': 8, 'learning_rate': 0.0913131083570077, 'n_estimators': 267, 'subsample': 0.5830762101637587, 'colsample_bytree': 0.9836812105344687, 'min_child_weight': 2, 'gamma': 4.387295227897583, 'reg_alpha': 0.053630533473967734, 'reg_lambda': 0.12044452222826929, 'max_delta_step': 3}. Best is trial 4 with value: 0.4642105263157895.

Best trial: 4. Best value: 0.464211:   6%|▌         | 3/50 [00:31<07:32,  9.62s/it]

[I 2025-12-02 00:25:11,877] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.01878344069934253, 'n_estimators': 989, 'subsample': 0.8140028590165009, 'colsample_bytree': 0.5209003166802886, 'min_child_weight': 5, 'gamma': 4.674087061837936, 'reg_alpha': 0.02139330522389323, 'reg_lambda': 0.2725392374911253, 'max_delta_step': 8}. Best is trial 4 with value: 0.4642105263157895.

Best trial: 4. Best value: 0.464211:   8%|▊         | 4/50 [00:38<06:43,  8.77s/it]

[I 2025-12-02 00:25:19,353] Trial 2 finished with value: 0.26 and parameters: {'max_depth': 5, 'learning_rate': 0.0897916166974055, 'n_estimators': 1161, 'subsample': 0.5599136423519308, 'colsample_bytree': 0.8317561986436541, 'min_child_weight': 5, 'gamma': 4.283070551288289, 'reg_alpha': 0.0006461820292786202, 'reg_lambda': 0.0060830692963373826, 'max_delta_step': 10}. Best is trial 4 with value: 0.4642105263157895.

Best trial: 4. Best value: 0.464211:  10%|█         | 5/50 [00:42<05:22,  7.18s/it]

[I 2025-12-02 00:25:23,697] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.11890027425161176, 'n_estimators': 540, 'subsample': 0.5071358464834674, 'colsample_bytree': 0.7654120891925293, 'min_child_weight': 10, 'gamma': 2.7580207674343233, 'reg_alpha': 1.0541807576364838e-06, 'reg_lambda': 1.8063863945964607e-05, 'max_delta_step': 6}. Best is trial 4 with value: 0.4642105263157895.

Best trial: 4. Best value: 0.464211:  12%|█▏        | 6/50 [00:49<05:07,  6.98s/it]

[I 2025-12-02 00:25:30,300] Trial 0 finished with value: 0.4378947368421053 and parameters: {'max_depth': 4, 'learning_rate': 0.03368013393336761, 'n_estimators': 1283, 'subsample': 0.8546716573734305, 'colsample_bytree': 0.9496650514374578, 'min_child_weight': 2, 'gamma': 0.5482857604346358, 'reg_alpha': 6.678427609356554e-08, 'reg_lambda': 0.18157205608505503, 'max_delta_step': 5}. Best is trial 4 with value: 0.4642105263157895.

Best trial: 4. Best value: 0.464211:  14%|█▍        | 7/50 [00:56<04:53,  6.83s/it]

[I 2025-12-02 00:25:36,812] Trial 8 finished with value: 0.34 and parameters: {'max_depth': 5, 'learning_rate': 0.1262770609553414, 'n_estimators': 381, 'subsample': 0.8486561298622379, 'colsample_bytree': 0.5176324561693173, 'min_child_weight': 7, 'gamma': 4.616939624153958, 'reg_alpha': 0.0018507117239288588, 'reg_lambda': 0.028073068288531993, 'max_delta_step': 8}. Best is trial 4 with value: 0.4642105263157895.

Best trial: 4. Best value: 0.464211:  16%|█▌        | 8/50 [00:58<03:43,  5.32s/it]

[I 2025-12-02 00:25:38,901] Trial 7 finished with value: 0.3684210526315789 and parameters: {'max_depth': 4, 'learning_rate': 0.14564223121662376, 'n_estimators': 562, 'subsample': 0.5716471183213607, 'colsample_bytree': 0.9897649244371332, 'min_child_weight': 7, 'gamma': 1.7628217634247583, 'reg_alpha': 1.0690057047906888e-05, 'reg_lambda': 0.00011912337489259791, 'max_delta_step': 10}. Best is trial 4 with value: 0.4642105263157895.

Best trial: 4. Best value: 0.464211:  18%|█▊        | 9/50 [01:13<05:43,  8.38s/it]

[I 2025-12-02 00:25:54,004] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.03568832743679968, 'n_estimators': 668, 'subsample': 0.8494631762838245, 'colsample_bytree': 0.9591014841713235, 'min_child_weight': 9, 'gamma': 4.138783213578268, 'reg_alpha': 2.3621449627012053e-07, 'reg_lambda': 8.686527911289023e-07, 'max_delta_step': 2}. Best is trial 4 with value: 0.4642105263157895.

Best trial: 4. Best value: 0.464211:  20%|██        | 10/50 [01:18<04:57,  7.44s/it]

[I 2025-12-02 00:25:59,325] Trial 6 finished with value: 0.39789473684210525 and parameters: {'max_depth': 8, 'learning_rate': 0.1373723450481347, 'n_estimators': 1421, 'subsample': 0.9941445457581907, 'colsample_bytree': 0.6680831727266426, 'min_child_weight': 3, 'gamma': 1.2507091200529712, 'reg_alpha': 8.648077058797846e-05, 'reg_lambda': 6.927206320705829e-07, 'max_delta_step': 9}. Best is trial 4 with value: 0.4642105263157895.

Best trial: 4. Best value: 0.464211:  22%|██▏       | 11/50 [01:19<03:31,  5.41s/it]

[I 2025-12-02 00:26:00,153] Trial 11 pruned.

Best trial: 4. Best value: 0.464211:  24%|██▍       | 12/50 [01:22<02:55,  4.63s/it]

[I 2025-12-02 00:26:02,999] Trial 10 pruned.

Best trial: 4. Best value: 0.464211:  26%|██▌       | 13/50 [01:25<02:31,  4.08s/it]

[I 2025-12-02 00:26:05,824] Trial 13 pruned.

Best trial: 12. Best value: 0.524211:  28%|██▊       | 14/50 [01:44<05:14,  8.73s/it]

[I 2025-12-02 00:26:25,287] Trial 12 finished with value: 0.5242105263157895 and parameters: {'max_depth': 3, 'learning_rate': 0.2611844913502031, 'n_estimators': 826, 'subsample': 0.941858387804626, 'colsample_bytree': 0.8944282685801781, 'min_child_weight': 1, 'gamma': 1.940536716277757, 'reg_alpha': 0.19754906905105943, 'reg_lambda': 0.9334579625572222, 'max_delta_step': 2}. Best is trial 12 with value: 0.5242105263157895.

Best trial: 17. Best value: 0.531579:  30%|███       | 15/50 [01:53<05:04,  8.71s/it]

[I 2025-12-02 00:26:33,964] Trial 17 finished with value: 0.531578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.07052455386586444, 'n_estimators': 200, 'subsample': 0.657260193872099, 'colsample_bytree': 0.9068454069461228, 'min_child_weight': 1, 'gamma': 3.6704615249117207, 'reg_alpha': 0.15198583536336066, 'reg_lambda': 7.280610201373821, 'max_delta_step': 4}. Best is trial 17 with value: 0.531578947368421.

Best trial: 17. Best value: 0.531579:  32%|███▏      | 16/50 [01:55<03:47,  6.68s/it]

[I 2025-12-02 00:26:35,919] Trial 18 pruned.

Best trial: 17. Best value: 0.531579:  34%|███▍      | 17/50 [02:07<04:31,  8.22s/it]

[I 2025-12-02 00:26:47,734] Trial 14 finished with value: 0.4063157894736842 and parameters: {'max_depth': 10, 'learning_rate': 0.04185591939403986, 'n_estimators': 1455, 'subsample': 0.6825345272451379, 'colsample_bytree': 0.8987874223325829, 'min_child_weight': 1, 'gamma': 3.1634393536750083, 'reg_alpha': 3.3096668037762083, 'reg_lambda': 5.669015843467611, 'max_delta_step': 3}. Best is trial 17 with value: 0.531578947368421.

Best trial: 15. Best value: 0.544211:  36%|███▌      | 18/50 [02:12<03:59,  7.48s/it]

[I 2025-12-02 00:26:53,490] Trial 15 finished with value: 0.5442105263157895 and parameters: {'max_depth': 10, 'learning_rate': 0.04260397075746864, 'n_estimators': 1431, 'subsample': 0.6838925025378586, 'colsample_bytree': 0.9078409123486035, 'min_child_weight': 1, 'gamma': 3.3905242465553895, 'reg_alpha': 0.23022478801271226, 'reg_lambda': 8.224994103543578, 'max_delta_step': 4}. Best is trial 15 with value: 0.5442105263157895.

Best trial: 15. Best value: 0.544211:  38%|███▊      | 19/50 [02:24<04:32,  8.78s/it]

[I 2025-12-02 00:27:05,293] Trial 16 finished with value: 0.4842105263157894 and parameters: {'max_depth': 3, 'learning_rate': 0.04356955103490159, 'n_estimators': 1455, 'subsample': 0.678275936978853, 'colsample_bytree': 0.9257339270164976, 'min_child_weight': 1, 'gamma': 0.020772059521199093, 'reg_alpha': 0.12601642845052746, 'reg_lambda': 4.8319272330938166, 'max_delta_step': 4}. Best is trial 15 with value: 0.5442105263157895.

Best trial: 15. Best value: 0.544211:  40%|████      | 20/50 [02:32<04:12,  8.42s/it]

[I 2025-12-02 00:27:12,884] Trial 22 pruned.

Best trial: 19. Best value: 0.550526:  42%|████▏     | 21/50 [02:32<02:55,  6.05s/it]

[I 2025-12-02 00:27:13,394] Trial 19 finished with value: 0.5505263157894738 and parameters: {'max_depth': 3, 'learning_rate': 0.060522837133238507, 'n_estimators': 1091, 'subsample': 0.653631393183183, 'colsample_bytree': 0.9002607208669378, 'min_child_weight': 1, 'gamma': 2.5012751300329596, 'reg_alpha': 0.00925268666498027, 'reg_lambda': 1.4829693533337737e-08, 'max_delta_step': 0}. Best is trial 19 with value: 0.5505263157894738.

Best trial: 19. Best value: 0.550526:  44%|████▍     | 22/50 [02:41<03:12,  6.88s/it]

[I 2025-12-02 00:27:22,227] Trial 23 pruned.

Best trial: 19. Best value: 0.550526:  46%|████▌     | 23/50 [02:42<02:16,  5.05s/it]

[I 2025-12-02 00:27:22,992] Trial 24 pruned.

Best trial: 19. Best value: 0.550526:  48%|████▊     | 24/50 [02:46<02:04,  4.80s/it]

[I 2025-12-02 00:27:27,210] Trial 21 finished with value: 0.4842105263157894 and parameters: {'max_depth': 9, 'learning_rate': 0.025503007443461293, 'n_estimators': 1107, 'subsample': 0.7486854045765404, 'colsample_bytree': 0.6966168500642439, 'min_child_weight': 3, 'gamma': 3.6192238683137337, 'reg_alpha': 0.004794674076274863, 'reg_lambda': 0.0036878702368148184, 'max_delta_step': 0}. Best is trial 19 with value: 0.5505263157894738.

Best trial: 19. Best value: 0.550526:  50%|█████     | 25/50 [02:49<01:47,  4.31s/it]

[I 2025-12-02 00:27:30,382] Trial 20 finished with value: 0.5505263157894738 and parameters: {'max_depth': 3, 'learning_rate': 0.06741676454073578, 'n_estimators': 1087, 'subsample': 0.751369313801817, 'colsample_bytree': 0.9111951427897772, 'min_child_weight': 1, 'gamma': 2.1397203014482686, 'reg_alpha': 0.013999655480320942, 'reg_lambda': 0.003340203576611729, 'max_delta_step': 0}. Best is trial 19 with value: 0.5505263157894738.

Best trial: 19. Best value: 0.550526:  52%|█████▏    | 26/50 [03:14<04:12, 10.51s/it]

[I 2025-12-02 00:27:55,341] Trial 25 finished with value: 0.41157894736842104 and parameters: {'max_depth': 4, 'learning_rate': 0.06728388209195998, 'n_estimators': 1031, 'subsample': 0.6277912356268599, 'colsample_bytree': 0.8479315857971823, 'min_child_weight': 2, 'gamma': 2.8068905347480437, 'reg_alpha': 8.687201731194782e-05, 'reg_lambda': 1.3311613946249086e-08, 'max_delta_step': 1}. Best is trial 19 with value: 0.5505263157894738.

Best trial: 19. Best value: 0.550526:  54%|█████▍    | 27/50 [03:19<03:23,  8.86s/it]

[I 2025-12-02 00:28:00,372] Trial 27 finished with value: 0.41157894736842104 and parameters: {'max_depth': 5, 'learning_rate': 0.06502116615870392, 'n_estimators': 975, 'subsample': 0.6310199582453015, 'colsample_bytree': 0.9223311101935235, 'min_child_weight': 2, 'gamma': 2.390569948144784, 'reg_alpha': 0.7677071215178215, 'reg_lambda': 2.7632911970581353e-08, 'max_delta_step': 5}. Best is trial 19 with value: 0.5505263157894738.

Best trial: 19. Best value: 0.550526:  56%|█████▌    | 28/50 [03:20<02:23,  6.54s/it]

[I 2025-12-02 00:28:01,505] Trial 26 finished with value: 0.5042105263157894 and parameters: {'max_depth': 5, 'learning_rate': 0.026050778899423036, 'n_estimators': 1015, 'subsample': 0.6499458432828216, 'colsample_bytree': 0.9344373765687903, 'min_child_weight': 2, 'gamma': 2.4069260403761015, 'reg_alpha': 1.3968778251755558, 'reg_lambda': 3.572519332089715e-08, 'max_delta_step': 5}. Best is trial 19 with value: 0.5505263157894738.

Best trial: 19. Best value: 0.550526:  58%|█████▊    | 29/50 [03:23<01:53,  5.41s/it]

[I 2025-12-02 00:28:04,259] Trial 28 finished with value: 0.41789473684210526 and parameters: {'max_depth': 5, 'learning_rate': 0.028871873760034104, 'n_estimators': 989, 'subsample': 0.6124771344501815, 'colsample_bytree': 0.7718399204273669, 'min_child_weight': 2, 'gamma': 2.2937520278346097, 'reg_alpha': 0.00011634024503531112, 'reg_lambda': 3.785018244815768e-08, 'max_delta_step': 1}. Best is trial 19 with value: 0.5505263157894738.

Best trial: 19. Best value: 0.550526:  60%|██████    | 30/50 [03:30<01:54,  5.73s/it]

[I 2025-12-02 00:28:10,729] Trial 30 pruned.

Best trial: 19. Best value: 0.550526:  62%|██████▏   | 31/50 [03:31<01:21,  4.31s/it]

[I 2025-12-02 00:28:11,745] Trial 31 pruned.

Best trial: 19. Best value: 0.550526:  64%|██████▍   | 32/50 [03:33<01:10,  3.91s/it]

[I 2025-12-02 00:28:14,715] Trial 32 pruned.

Best trial: 19. Best value: 0.550526:  66%|██████▌   | 33/50 [03:38<01:10,  4.15s/it]

[I 2025-12-02 00:28:19,426] Trial 33 pruned.

Best trial: 19. Best value: 0.550526:  68%|██████▊   | 34/50 [03:47<01:26,  5.41s/it]

[I 2025-12-02 00:28:27,772] Trial 36 pruned.

Best trial: 19. Best value: 0.550526:  70%|███████   | 35/50 [03:55<01:35,  6.39s/it]

[I 2025-12-02 00:28:36,452] Trial 29 finished with value: 0.4378947368421053 and parameters: {'max_depth': 5, 'learning_rate': 0.053196543557218666, 'n_estimators': 1330, 'subsample': 0.7236986622176345, 'colsample_bytree': 0.7766557936540693, 'min_child_weight': 2, 'gamma': 2.3488731721812304, 'reg_alpha': 0.5378540973443131, 'reg_lambda': 2.518468779345381e-06, 'max_delta_step': 1}. Best is trial 19 with value: 0.5505263157894738.

Best trial: 19. Best value: 0.550526:  72%|███████▏  | 36/50 [04:01<01:26,  6.21s/it]

[I 2025-12-02 00:28:42,254] Trial 38 pruned.

Best trial: 34. Best value: 0.576842:  74%|███████▍  | 37/50 [04:15<01:52,  8.63s/it]

[I 2025-12-02 00:28:56,521] Trial 34 finished with value: 0.5768421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.04879413188674697, 'n_estimators': 1190, 'subsample': 0.7968006868081613, 'colsample_bytree': 0.9560328784219918, 'min_child_weight': 1, 'gamma': 3.006798892464375, 'reg_alpha': 0.07197919385203982, 'reg_lambda': 0.752971139819541, 'max_delta_step': 4}. Best is trial 34 with value: 0.5768421052631579.

Best trial: 35. Best value: 0.623158:  76%|███████▌  | 38/50 [04:17<01:20,  6.68s/it]

[I 2025-12-02 00:28:58,640] Trial 35 finished with value: 0.6231578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.05477694744716876, 'n_estimators': 1191, 'subsample': 0.7860206451385354, 'colsample_bytree': 0.9568979641353121, 'min_child_weight': 1, 'gamma': 3.0577505490372134, 'reg_alpha': 0.1768067019523178, 'reg_lambda': 0.8650364146156694, 'max_delta_step': 4}. Best is trial 35 with value: 0.6231578947368421.

Best trial: 35. Best value: 0.623158:  78%|███████▊  | 39/50 [04:25<01:16,  6.93s/it]

[I 2025-12-02 00:29:06,145] Trial 41 pruned.

Best trial: 35. Best value: 0.623158:  80%|████████  | 40/50 [04:26<00:51,  5.12s/it]

[I 2025-12-02 00:29:07,039] Trial 37 finished with value: 0.5768421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.03801370609878929, 'n_estimators': 1201, 'subsample': 0.5308008380735805, 'colsample_bytree': 0.9054192981272116, 'min_child_weight': 1, 'gamma': 3.9637471671173534, 'reg_alpha': 0.0704140932896507, 'reg_lambda': 0.02930830748306573, 'max_delta_step': 6}. Best is trial 35 with value: 0.6231578947368421.

Best trial: 35. Best value: 0.623158:  82%|████████▏ | 41/50 [04:33<00:51,  5.77s/it]

[I 2025-12-02 00:29:14,343] Trial 42 pruned.

Best trial: 35. Best value: 0.623158:  84%|████████▍ | 42/50 [04:41<00:50,  6.37s/it]

[I 2025-12-02 00:29:22,110] Trial 39 finished with value: 0.4978947368421053 and parameters: {'max_depth': 3, 'learning_rate': 0.08071153404421363, 'n_estimators': 1193, 'subsample': 0.6040473498141857, 'colsample_bytree': 0.8563607991735602, 'min_child_weight': 1, 'gamma': 1.9953491972235942, 'reg_alpha': 0.01001871310238541, 'reg_lambda': 1.0110554132652168, 'max_delta_step': 3}. Best is trial 35 with value: 0.6231578947368421.

Best trial: 35. Best value: 0.623158:  86%|████████▌ | 43/50 [04:52<00:54,  7.72s/it]

[I 2025-12-02 00:29:32,990] Trial 43 finished with value: 0.5042105263157894 and parameters: {'max_depth': 4, 'learning_rate': 0.10372390838421662, 'n_estimators': 914, 'subsample': 0.5073534989208857, 'colsample_bytree': 0.969611933099644, 'min_child_weight': 3, 'gamma': 3.0326739437707966, 'reg_alpha': 0.0009636208862221056, 'reg_lambda': 1.3874285518999716, 'max_delta_step': 7}. Best is trial 35 with value: 0.6231578947368421.

Best trial: 35. Best value: 0.623158:  88%|████████▊ | 44/50 [04:59<00:45,  7.64s/it]

[I 2025-12-02 00:29:40,433] Trial 46 pruned.

Best trial: 35. Best value: 0.623158:  90%|█████████ | 45/50 [05:04<00:34,  6.91s/it]

[I 2025-12-02 00:29:45,644] Trial 40 finished with value: 0.5705263157894737 and parameters: {'max_depth': 7, 'learning_rate': 0.04338399480409082, 'n_estimators': 1154, 'subsample': 0.896743292163873, 'colsample_bytree': 0.9520616795785684, 'min_child_weight': 1, 'gamma': 2.9892792792547427, 'reg_alpha': 0.0012515727612223103, 'reg_lambda': 1.1583727067406502, 'max_delta_step': 3}. Best is trial 35 with value: 0.6231578947368421.

Best trial: 35. Best value: 0.623158:  92%|█████████▏| 46/50 [05:08<00:23,  5.94s/it]

[I 2025-12-02 00:29:49,322] Trial 45 finished with value: 0.5568421052631579 and parameters: {'max_depth': 4, 'learning_rate': 0.09938634234727782, 'n_estimators': 892, 'subsample': 0.5025543701791666, 'colsample_bytree': 0.9786177530497864, 'min_child_weight': 2, 'gamma': 3.006250939697627, 'reg_alpha': 0.001299506179837517, 'reg_lambda': 0.050974103129307606, 'max_delta_step': 7}. Best is trial 35 with value: 0.6231578947368421.

Best trial: 35. Best value: 0.623158:  94%|█████████▍| 47/50 [05:09<00:13,  4.45s/it]

[I 2025-12-02 00:29:50,286] Trial 47 pruned.

Best trial: 35. Best value: 0.623158:  96%|█████████▌| 48/50 [05:15<00:09,  4.81s/it]

[I 2025-12-02 00:29:55,924] Trial 44 finished with value: 0.5568421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.10459980694695467, 'n_estimators': 1210, 'subsample': 0.7948504440894326, 'colsample_bytree': 0.9753486709316443, 'min_child_weight': 2, 'gamma': 2.9931397632879655, 'reg_alpha': 0.01941273778039871, 'reg_lambda': 1.7681972527644465, 'max_delta_step': 7}. Best is trial 35 with value: 0.6231578947368421.

Best trial: 35. Best value: 0.623158:  98%|█████████▊| 49/50 [05:37<00:09, 10.00s/it]

[I 2025-12-02 00:30:18,042] Trial 48 finished with value: 0.5505263157894738 and parameters: {'max_depth': 7, 'learning_rate': 0.03562072423832649, 'n_estimators': 1254, 'subsample': 0.9283531709875004, 'colsample_bytree': 0.9907380323631071, 'min_child_weight': 2, 'gamma': 2.7376141023768286, 'reg_alpha': 8.57874579316591e-06, 'reg_lambda': 0.38175310906822735, 'max_delta_step': 5}. Best is trial 35 with value: 0.6231578947368421.

Best trial: 35. Best value: 0.623158: 100%|██████████| 50/50 [05:41<00:00,  6.83s/it]

[I 2025-12-02 00:30:22,469] Trial 49 finished with value: 0.5705263157894737 and parameters: {'max_depth': 7, 'learning_rate': 0.01372985169917014, 'n_estimators': 1274, 'subsample': 0.8891680796021865, 'colsample_bytree': 0.9834477402927413, 'min_child_weight': 2, 'gamma': 4.092553936212863, 'reg_alpha': 1.7832134776128888e-05, 'reg_lambda': 0.3039738694862081, 'max_delta_step': 7}. Best is trial 35 with value: 0.6231578947368421.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 00:30:26,977] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 43, Test size: 11
Using Leave-One-Out CV with 43 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.48136:   2%|▏         | 1/50 [00:10<08:47, 10.77s/it]

[I 2025-12-02 00:30:37,741] Trial 3 finished with value: 0.481359649122807 and parameters: {'max_depth': 10, 'learning_rate': 0.0986150214618699, 'n_estimators': 292, 'subsample': 0.757075531328063, 'colsample_bytree': 0.5742748543823692, 'min_child_weight': 2, 'gamma': 3.9759499563462475, 'reg_alpha': 0.004739741155665666, 'reg_lambda': 0.17174893753220433, 'max_delta_step': 2}. Best is trial 3 with value: 0.481359649122807.

Best trial: 3. Best value: 0.48136:   4%|▍         | 2/50 [00:17<06:50,  8.56s/it]

[I 2025-12-02 00:30:44,757] Trial 0 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.1657205178720904, 'n_estimators': 475, 'subsample': 0.7544598870737305, 'colsample_bytree': 0.5705524166081837, 'min_child_weight': 1, 'gamma': 1.8889929422948364, 'reg_alpha': 3.8783760091868267, 'reg_lambda': 0.1702829363624335, 'max_delta_step': 0}. Best is trial 3 with value: 0.481359649122807.

Best trial: 3. Best value: 0.48136:   6%|▌         | 3/50 [00:39<11:17, 14.42s/it]

[I 2025-12-02 00:31:06,141] Trial 2 finished with value: 0.3607456140350877 and parameters: {'max_depth': 7, 'learning_rate': 0.022483170262639525, 'n_estimators': 1112, 'subsample': 0.9030568140696855, 'colsample_bytree': 0.6383592459551473, 'min_child_weight': 3, 'gamma': 1.1424949883305402, 'reg_alpha': 4.73788161416802e-08, 'reg_lambda': 0.4553178284024672, 'max_delta_step': 10}. Best is trial 3 with value: 0.481359649122807.

Best trial: 3. Best value: 0.48136:   8%|▊         | 4/50 [00:47<09:08, 11.93s/it]

[I 2025-12-02 00:31:14,245] Trial 1 finished with value: 0.42324561403508776 and parameters: {'max_depth': 6, 'learning_rate': 0.14636576562992798, 'n_estimators': 1415, 'subsample': 0.668520585197804, 'colsample_bytree': 0.958923967565591, 'min_child_weight': 3, 'gamma': 1.6589612561415419, 'reg_alpha': 2.9158833416252976e-05, 'reg_lambda': 0.00012357258131504803, 'max_delta_step': 1}. Best is trial 3 with value: 0.481359649122807.

Best trial: 3. Best value: 0.48136:  10%|█         | 5/50 [00:47<05:54,  7.88s/it]

[I 2025-12-02 00:31:14,966] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.047692169032312104, 'n_estimators': 941, 'subsample': 0.554545716929582, 'colsample_bytree': 0.5057118579082087, 'min_child_weight': 6, 'gamma': 4.99059383238212, 'reg_alpha': 0.0200651790040744, 'reg_lambda': 1.1329937913352084e-05, 'max_delta_step': 3}. Best is trial 3 with value: 0.481359649122807.

Best trial: 3. Best value: 0.48136:  12%|█▏        | 6/50 [00:54<05:18,  7.25s/it]

[I 2025-12-02 00:31:20,970] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.07015844503513043, 'n_estimators': 1307, 'subsample': 0.5344154938473074, 'colsample_bytree': 0.7973224546238773, 'min_child_weight': 7, 'gamma': 3.949210681430389, 'reg_alpha': 0.051624201594113794, 'reg_lambda': 4.380859322205558, 'max_delta_step': 10}. Best is trial 3 with value: 0.481359649122807.

Best trial: 3. Best value: 0.48136:  14%|█▍        | 7/50 [00:59<04:45,  6.64s/it]

[I 2025-12-02 00:31:26,373] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.03076606007548407, 'n_estimators': 291, 'subsample': 0.6345772575585498, 'colsample_bytree': 0.805315632607758, 'min_child_weight': 10, 'gamma': 1.8261606599543483, 'reg_alpha': 2.3005427546118277e-06, 'reg_lambda': 2.625219377834316, 'max_delta_step': 8}. Best is trial 3 with value: 0.481359649122807.

Best trial: 3. Best value: 0.48136:  16%|█▌        | 8/50 [01:06<04:42,  6.72s/it]

[I 2025-12-02 00:31:33,272] Trial 6 finished with value: 0.10416666666666667 and parameters: {'max_depth': 4, 'learning_rate': 0.04673473985557268, 'n_estimators': 838, 'subsample': 0.6793074963050605, 'colsample_bytree': 0.519014389770103, 'min_child_weight': 4, 'gamma': 3.114652284240757, 'reg_alpha': 3.908108793348689e-05, 'reg_lambda': 2.1401630631028943, 'max_delta_step': 8}. Best is trial 3 with value: 0.481359649122807.

Best trial: 10. Best value: 0.622807:  18%|█▊        | 9/50 [01:12<04:23,  6.42s/it]

[I 2025-12-02 00:31:39,015] Trial 10 finished with value: 0.6228070175438596 and parameters: {'max_depth': 6, 'learning_rate': 0.012512220635303085, 'n_estimators': 255, 'subsample': 0.7842603627971328, 'colsample_bytree': 0.5809146286642859, 'min_child_weight': 1, 'gamma': 4.909048773112058, 'reg_alpha': 9.873561353643384e-07, 'reg_lambda': 0.05913552796080103, 'max_delta_step': 9}. Best is trial 10 with value: 0.6228070175438596.

Best trial: 10. Best value: 0.622807:  20%|██        | 10/50 [01:21<04:49,  7.24s/it]

[I 2025-12-02 00:31:48,110] Trial 12 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.19552952341535773, 'n_estimators': 228, 'subsample': 0.8117491599862895, 'colsample_bytree': 0.7441433941750799, 'min_child_weight': 10, 'gamma': 4.438792961838231, 'reg_alpha': 0.4763307553707598, 'reg_lambda': 0.14859967549312916, 'max_delta_step': 1}. Best is trial 10 with value: 0.6228070175438596.

Best trial: 10. Best value: 0.622807:  22%|██▏       | 11/50 [01:22<03:32,  5.44s/it]

[I 2025-12-02 00:31:49,474] Trial 9 pruned.

Best trial: 10. Best value: 0.622807:  24%|██▍       | 12/50 [01:25<02:59,  4.73s/it]

[I 2025-12-02 00:31:52,569] Trial 13 pruned.

Best trial: 10. Best value: 0.622807:  26%|██▌       | 13/50 [01:26<02:10,  3.54s/it]

[I 2025-12-02 00:31:53,370] Trial 11 pruned.

Best trial: 10. Best value: 0.622807:  28%|██▊       | 14/50 [01:27<01:39,  2.76s/it]

[I 2025-12-02 00:31:54,326] Trial 7 pruned.

Best trial: 14. Best value: 0.669956:  30%|███       | 15/50 [01:42<03:51,  6.60s/it]

[I 2025-12-02 00:32:09,831] Trial 14 finished with value: 0.6699561403508771 and parameters: {'max_depth': 6, 'learning_rate': 0.09409895144367184, 'n_estimators': 577, 'subsample': 0.9020771487362396, 'colsample_bytree': 0.6515941244119814, 'min_child_weight': 1, 'gamma': 3.676968453475819, 'reg_alpha': 0.0016141305305372958, 'reg_lambda': 0.011844672203496366, 'max_delta_step': 5}. Best is trial 14 with value: 0.6699561403508771.

Best trial: 14. Best value: 0.669956:  32%|███▏      | 16/50 [01:43<02:41,  4.76s/it]

[I 2025-12-02 00:32:10,327] Trial 17 finished with value: 0.5964912280701754 and parameters: {'max_depth': 7, 'learning_rate': 0.09911863809830798, 'n_estimators': 498, 'subsample': 0.8404028494691433, 'colsample_bytree': 0.6029157486815178, 'min_child_weight': 1, 'gamma': 3.806597806671512, 'reg_alpha': 0.0015455211548101888, 'reg_lambda': 0.006237727458997194, 'max_delta_step': 4}. Best is trial 14 with value: 0.6699561403508771.

Best trial: 14. Best value: 0.669956:  34%|███▍      | 17/50 [01:43<01:52,  3.41s/it]

[I 2025-12-02 00:32:10,590] Trial 15 finished with value: 0.5230263157894737 and parameters: {'max_depth': 7, 'learning_rate': 0.08768957327061025, 'n_estimators': 538, 'subsample': 0.848528905329036, 'colsample_bytree': 0.6154576599787449, 'min_child_weight': 1, 'gamma': 3.855389799954697, 'reg_alpha': 0.0025770996582551837, 'reg_lambda': 0.009277641155412391, 'max_delta_step': 4}. Best is trial 14 with value: 0.6699561403508771.
[I 2025-12-02 00:32:10,763] Trial 16 finished with value: 0.5811403508771931 and parameters: {'max_depth': 7, 'learning_rate': 0.0637701935026076, 'n_estimators': 521, 'subsample': 0.8522392970266841, 'colsample_bytree': 0.5864946533193276, 'min_child_weight': 1, 'gamma': 3.8673761098636374, 'reg_alpha': 0.0015825670555230265, 'reg_lambda': 0.007082616245006569, 'max_delta_step': 4}. Best is trial 14 with value: 0.6699561403508771.

Best trial: 14. Best value: 0.669956:  38%|███▊      | 19/50 [01:48<01:35,  3.08s/it]

[I 2025-12-02 00:32:15,352] Trial 19 pruned.

Best trial: 14. Best value: 0.669956:  40%|████      | 20/50 [01:48<01:08,  2.29s/it]

[I 2025-12-02 00:32:15,802] Trial 20 pruned.

Best trial: 14. Best value: 0.669956:  42%|████▏     | 21/50 [01:59<02:18,  4.76s/it]

[I 2025-12-02 00:32:26,313] Trial 21 pruned.

Best trial: 14. Best value: 0.669956:  44%|████▍     | 22/50 [02:01<01:52,  4.02s/it]

[I 2025-12-02 00:32:28,597] Trial 22 finished with value: 0.4451754385964912 and parameters: {'max_depth': 8, 'learning_rate': 0.02124787461269251, 'n_estimators': 371, 'subsample': 0.9171117492271927, 'colsample_bytree': 0.6998376541132204, 'min_child_weight': 3, 'gamma': 4.492927117094902, 'reg_alpha': 1.075806923108048e-06, 'reg_lambda': 0.0008275579047799813, 'max_delta_step': 8}. Best is trial 14 with value: 0.6699561403508771.

Best trial: 14. Best value: 0.669956:  46%|████▌     | 23/50 [02:01<01:18,  2.91s/it]

[I 2025-12-02 00:32:28,930] Trial 23 finished with value: 0.3925438596491228 and parameters: {'max_depth': 8, 'learning_rate': 0.029603542810457125, 'n_estimators': 375, 'subsample': 0.9167666221673936, 'colsample_bytree': 0.6718153713872816, 'min_child_weight': 3, 'gamma': 3.346453908846927, 'reg_alpha': 0.00023034737863408597, 'reg_lambda': 0.00054788171797709, 'max_delta_step': 8}. Best is trial 14 with value: 0.6699561403508771.

Best trial: 14. Best value: 0.669956:  48%|████▊     | 24/50 [02:05<01:21,  3.12s/it]

[I 2025-12-02 00:32:32,542] Trial 25 pruned.

Best trial: 18. Best value: 0.79057:  50%|█████     | 25/50 [02:08<01:14,  2.99s/it]

[I 2025-12-02 00:32:35,230] Trial 18 finished with value: 0.7905701754385965 and parameters: {'max_depth': 7, 'learning_rate': 0.024694877632393943, 'n_estimators': 565, 'subsample': 0.9784806348035731, 'colsample_bytree': 0.7134440096334675, 'min_child_weight': 1, 'gamma': 3.630788705517869, 'reg_alpha': 0.0006625324061440819, 'reg_lambda': 0.007009547835466342, 'max_delta_step': 5}. Best is trial 18 with value: 0.7905701754385965.

Best trial: 18. Best value: 0.79057:  52%|█████▏    | 26/50 [02:08<00:54,  2.26s/it]

[I 2025-12-02 00:32:35,767] Trial 27 pruned.

Best trial: 18. Best value: 0.79057:  54%|█████▍    | 27/50 [02:14<01:15,  3.27s/it]

[I 2025-12-02 00:32:41,392] Trial 24 finished with value: 0.4133771929824561 and parameters: {'max_depth': 8, 'learning_rate': 0.11124696737829559, 'n_estimators': 403, 'subsample': 0.9159143136365708, 'colsample_bytree': 0.6693132427547738, 'min_child_weight': 2, 'gamma': 4.4994719394782505, 'reg_alpha': 0.00012725899637436902, 'reg_lambda': 0.03647273392761899, 'max_delta_step': 4}. Best is trial 18 with value: 0.7905701754385965.

Best trial: 18. Best value: 0.79057:  56%|█████▌    | 28/50 [02:15<00:58,  2.67s/it]

[I 2025-12-02 00:32:42,672] Trial 26 finished with value: 0.481359649122807 and parameters: {'max_depth': 6, 'learning_rate': 0.11912615007289712, 'n_estimators': 413, 'subsample': 0.8098222011664646, 'colsample_bytree': 0.536908208844656, 'min_child_weight': 2, 'gamma': 2.322354984055992, 'reg_alpha': 0.0007007927492758689, 'reg_lambda': 0.02136500252996101, 'max_delta_step': 4}. Best is trial 18 with value: 0.7905701754385965.

Best trial: 18. Best value: 0.79057:  58%|█████▊    | 29/50 [02:22<01:20,  3.81s/it]

[I 2025-12-02 00:32:49,155] Trial 29 pruned.

Best trial: 18. Best value: 0.79057:  60%|██████    | 30/50 [02:25<01:12,  3.63s/it]

[I 2025-12-02 00:32:52,361] Trial 32 pruned.

Best trial: 18. Best value: 0.79057:  62%|██████▏   | 31/50 [02:26<00:55,  2.93s/it]

[I 2025-12-02 00:32:53,658] Trial 30 finished with value: 0.7171052631578947 and parameters: {'max_depth': 4, 'learning_rate': 0.01684739027539897, 'n_estimators': 201, 'subsample': 0.9555925836332103, 'colsample_bytree': 0.7772621867475957, 'min_child_weight': 1, 'gamma': 2.2978650018341855, 'reg_alpha': 9.771273784387822e-06, 'reg_lambda': 1.0283753644733677, 'max_delta_step': 7}. Best is trial 18 with value: 0.7905701754385965.

Best trial: 18. Best value: 0.79057:  64%|██████▍   | 32/50 [02:29<00:50,  2.82s/it]

[I 2025-12-02 00:32:56,219] Trial 33 pruned.

Best trial: 18. Best value: 0.79057:  66%|██████▌   | 33/50 [02:36<01:10,  4.13s/it]

[I 2025-12-02 00:33:03,390] Trial 28 finished with value: 0.42872807017543857 and parameters: {'max_depth': 6, 'learning_rate': 0.01656963638478361, 'n_estimators': 793, 'subsample': 0.9469169351908633, 'colsample_bytree': 0.7718138404488927, 'min_child_weight': 2, 'gamma': 2.255225094443804, 'reg_alpha': 0.034683710403237936, 'reg_lambda': 7.143701294221166e-07, 'max_delta_step': 5}. Best is trial 18 with value: 0.7905701754385965.

Best trial: 18. Best value: 0.79057:  68%|██████▊   | 34/50 [02:45<01:28,  5.54s/it]

[I 2025-12-02 00:33:12,230] Trial 35 finished with value: 0.5230263157894737 and parameters: {'max_depth': 3, 'learning_rate': 0.01707042785909935, 'n_estimators': 293, 'subsample': 0.8718920592895621, 'colsample_bytree': 0.834565604563588, 'min_child_weight': 1, 'gamma': 1.4060227696835454, 'reg_alpha': 1.6134265185920435e-05, 'reg_lambda': 0.18759794970655308, 'max_delta_step': 7}. Best is trial 18 with value: 0.7905701754385965.

Best trial: 18. Best value: 0.79057:  70%|███████   | 35/50 [02:45<00:59,  3.98s/it]

[I 2025-12-02 00:33:12,570] Trial 31 finished with value: 0.7335526315789473 and parameters: {'max_depth': 4, 'learning_rate': 0.016871514022076872, 'n_estimators': 797, 'subsample': 0.9469607761518679, 'colsample_bytree': 0.7814542117346054, 'min_child_weight': 1, 'gamma': 4.219635241207467, 'reg_alpha': 0.01790868087914085, 'reg_lambda': 0.8293141310295626, 'max_delta_step': 7}. Best is trial 18 with value: 0.7905701754385965.

Best trial: 18. Best value: 0.79057:  72%|███████▏  | 36/50 [02:51<01:03,  4.56s/it]

[I 2025-12-02 00:33:18,493] Trial 34 finished with value: 0.6491228070175439 and parameters: {'max_depth': 3, 'learning_rate': 0.01756748129048243, 'n_estimators': 611, 'subsample': 0.9521469830930339, 'colsample_bytree': 0.7713594910249889, 'min_child_weight': 1, 'gamma': 1.3320613564729287, 'reg_alpha': 7.320600730551679e-06, 'reg_lambda': 0.19868861542844538, 'max_delta_step': 9}. Best is trial 18 with value: 0.7905701754385965.

Best trial: 18. Best value: 0.79057:  74%|███████▍  | 37/50 [02:53<00:47,  3.65s/it]

[I 2025-12-02 00:33:19,999] Trial 38 pruned.

Best trial: 18. Best value: 0.79057:  76%|███████▌  | 38/50 [02:55<00:41,  3.42s/it]

[I 2025-12-02 00:33:22,904] Trial 36 finished with value: 0.5285087719298246 and parameters: {'max_depth': 4, 'learning_rate': 0.015384742421342445, 'n_estimators': 299, 'subsample': 0.8857832337823976, 'colsample_bytree': 0.8238953426795783, 'min_child_weight': 1, 'gamma': 1.0658843589534097, 'reg_alpha': 7.2910303893451636e-06, 'reg_lambda': 0.39637294757716723, 'max_delta_step': 7}. Best is trial 18 with value: 0.7905701754385965.

Best trial: 18. Best value: 0.79057:  78%|███████▊  | 39/50 [02:59<00:37,  3.45s/it]

[I 2025-12-02 00:33:26,405] Trial 39 pruned.

Best trial: 18. Best value: 0.79057:  80%|████████  | 40/50 [03:11<01:01,  6.13s/it]

[I 2025-12-02 00:33:38,783] Trial 42 pruned.

Best trial: 18. Best value: 0.79057:  82%|████████▏ | 41/50 [03:22<01:06,  7.35s/it]

[I 2025-12-02 00:33:48,991] Trial 43 pruned.

Best trial: 18. Best value: 0.79057:  84%|████████▍ | 42/50 [03:27<00:53,  6.67s/it]

[I 2025-12-02 00:33:54,075] Trial 40 finished with value: 0.3607456140350877 and parameters: {'max_depth': 5, 'learning_rate': 0.020719313456119465, 'n_estimators': 1059, 'subsample': 0.8918851956588563, 'colsample_bytree': 0.8223576028949409, 'min_child_weight': 3, 'gamma': 0.7652709283066419, 'reg_alpha': 0.007468680768299159, 'reg_lambda': 0.886373953022556, 'max_delta_step': 7}. Best is trial 18 with value: 0.7905701754385965.

Best trial: 18. Best value: 0.79057:  86%|████████▌ | 43/50 [03:27<00:34,  4.90s/it]

[I 2025-12-02 00:33:54,859] Trial 41 finished with value: 0.3925438596491228 and parameters: {'max_depth': 5, 'learning_rate': 0.03443902557702848, 'n_estimators': 1077, 'subsample': 0.9215806527758544, 'colsample_bytree': 0.6509008463299227, 'min_child_weight': 3, 'gamma': 4.181962177270124, 'reg_alpha': 0.010471412966942014, 'reg_lambda': 0.6738876238084471, 'max_delta_step': 5}. Best is trial 18 with value: 0.7905701754385965.

Best trial: 18. Best value: 0.79057:  88%|████████▊ | 44/50 [03:29<00:23,  3.96s/it]

[I 2025-12-02 00:33:56,599] Trial 37 finished with value: 0.5230263157894737 and parameters: {'max_depth': 4, 'learning_rate': 0.012664269970044193, 'n_estimators': 1073, 'subsample': 0.8919946777758271, 'colsample_bytree': 0.656795708687909, 'min_child_weight': 1, 'gamma': 1.0940879788885862, 'reg_alpha': 5.819650379901398e-06, 'reg_lambda': 0.3746597136766765, 'max_delta_step': 9}. Best is trial 18 with value: 0.7905701754385965.

Best trial: 18. Best value: 0.79057:  90%|█████████ | 45/50 [03:33<00:19,  3.84s/it]

[I 2025-12-02 00:34:00,167] Trial 45 pruned.

Best trial: 18. Best value: 0.79057:  92%|█████████▏| 46/50 [03:36<00:14,  3.56s/it]

[I 2025-12-02 00:34:03,067] Trial 46 pruned.

Best trial: 18. Best value: 0.79057:  94%|█████████▍| 47/50 [03:37<00:08,  2.84s/it]

[I 2025-12-02 00:34:04,225] Trial 47 pruned.

Best trial: 18. Best value: 0.79057:  96%|█████████▌| 48/50 [03:47<00:10,  5.18s/it]

[I 2025-12-02 00:34:14,881] Trial 44 finished with value: 0.5493421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.01818086403093552, 'n_estimators': 614, 'subsample': 0.936648809673094, 'colsample_bytree': 0.7638158364881579, 'min_child_weight': 1, 'gamma': 0.5438262093316016, 'reg_alpha': 8.705590388637773e-05, 'reg_lambda': 0.14754821004852867, 'max_delta_step': 9}. Best is trial 18 with value: 0.7905701754385965.

Best trial: 18. Best value: 0.79057:  98%|█████████▊| 49/50 [03:56<00:06,  6.35s/it]

[I 2025-12-02 00:34:23,964] Trial 48 finished with value: 0.37609649122807015 and parameters: {'max_depth': 3, 'learning_rate': 0.05365920653263736, 'n_estimators': 900, 'subsample': 0.9681226641277347, 'colsample_bytree': 0.7956899167922481, 'min_child_weight': 2, 'gamma': 0.13135662643357282, 'reg_alpha': 3.1494586019476635e-07, 'reg_lambda': 3.3914132876704897, 'max_delta_step': 8}. Best is trial 18 with value: 0.7905701754385965.

Best trial: 18. Best value: 0.79057: 100%|██████████| 50/50 [04:01<00:00,  4.82s/it]

[I 2025-12-02 00:34:28,083] Trial 49 finished with value: 0.481359649122807 and parameters: {'max_depth': 3, 'learning_rate': 0.018677883699263917, 'n_estimators': 865, 'subsample': 0.9317747620966902, 'colsample_bytree': 0.7949895440833472, 'min_child_weight': 2, 'gamma': 1.5626512037689966, 'reg_alpha': 8.261042084449022e-05, 'reg_lambda': 2.93503921094266, 'max_delta_step': 0}. Best is trial 18 with value: 0.7905701754385965.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 00:34:31,792] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 45, Test size: 12
Using Leave-One-Out CV with 45 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.458502:   2%|▏         | 1/50 [00:21<17:54, 21.93s/it]

[I 2025-12-02 00:34:53,712] Trial 3 finished with value: 0.458502024291498 and parameters: {'max_depth': 9, 'learning_rate': 0.06660962214714392, 'n_estimators': 652, 'subsample': 0.5492891021062374, 'colsample_bytree': 0.5934914040042552, 'min_child_weight': 3, 'gamma': 1.5556026330656199, 'reg_alpha': 1.1354690473820117e-06, 'reg_lambda': 1.1695327743917623e-08, 'max_delta_step': 0}. Best is trial 3 with value: 0.458502024291498.

Best trial: 3. Best value: 0.458502:   4%|▍         | 2/50 [00:37<14:33, 18.20s/it]

[I 2025-12-02 00:35:09,299] Trial 1 finished with value: 0.42004048582995945 and parameters: {'max_depth': 4, 'learning_rate': 0.13104106011383906, 'n_estimators': 1119, 'subsample': 0.9209645146607216, 'colsample_bytree': 0.6032576613038281, 'min_child_weight': 4, 'gamma': 4.16150599782933, 'reg_alpha': 2.267499368625779, 'reg_lambda': 0.08818888848886791, 'max_delta_step': 8}. Best is trial 3 with value: 0.458502024291498.

Best trial: 3. Best value: 0.458502:   6%|▌         | 3/50 [00:42<09:35, 12.25s/it]

[I 2025-12-02 00:35:14,462] Trial 2 finished with value: 0.18421052631578946 and parameters: {'max_depth': 6, 'learning_rate': 0.2462023706007191, 'n_estimators': 1266, 'subsample': 0.9008421073276909, 'colsample_bytree': 0.8960687002428642, 'min_child_weight': 7, 'gamma': 3.4235548804905624, 'reg_alpha': 0.21116620350951756, 'reg_lambda': 1.2748942839591776e-08, 'max_delta_step': 7}. Best is trial 3 with value: 0.458502024291498.

Best trial: 3. Best value: 0.458502:   8%|▊         | 4/50 [00:44<06:21,  8.28s/it]

[I 2025-12-02 00:35:16,670] Trial 0 finished with value: 0.44433198380566796 and parameters: {'max_depth': 5, 'learning_rate': 0.07691799612869313, 'n_estimators': 1108, 'subsample': 0.7722521455275808, 'colsample_bytree': 0.660226098833482, 'min_child_weight': 1, 'gamma': 1.7992425406375117, 'reg_alpha': 0.0048042552402296, 'reg_lambda': 7.472919877912136e-05, 'max_delta_step': 0}. Best is trial 3 with value: 0.458502024291498.

Best trial: 5. Best value: 0.518219:  10%|█         | 5/50 [01:01<08:27, 11.28s/it]

[I 2025-12-02 00:35:33,270] Trial 5 finished with value: 0.5182186234817814 and parameters: {'max_depth': 7, 'learning_rate': 0.0744580297970344, 'n_estimators': 537, 'subsample': 0.8703813274329859, 'colsample_bytree': 0.9912941121895289, 'min_child_weight': 2, 'gamma': 2.8247133107884004, 'reg_alpha': 2.4015631147748307e-08, 'reg_lambda': 0.01871793660779915, 'max_delta_step': 9}. Best is trial 5 with value: 0.5182186234817814.
[I 2025-12-02 00:35:33,344] Trial 4 finished with value: 0.4463562753036437 and parameters: {'max_depth': 10, 'learning_rate': 0.2177811465341459, 'n_estimators': 1231, 'subsample': 0.545095617982511, 'colsample_bytree': 0.6271945959751275, 'min_child_weight': 3, 'gamma': 0.4432561602751056, 'reg_alpha': 0.0003588846196604968, 'reg_lambda': 1.2061541191243824e-05, 'max_delta_step': 9}. Best is trial 5 with value: 0.5182186234817814.

Best trial: 5. Best value: 0.518219:  14%|█▍        | 7/50 [01:07<05:09,  7.21s/it]

[I 2025-12-02 00:35:39,780] Trial 6 finished with value: 0.42004048582995945 and parameters: {'max_depth': 7, 'learning_rate': 0.034891915573853606, 'n_estimators': 674, 'subsample': 0.6923687514054938, 'colsample_bytree': 0.7974623198474868, 'min_child_weight': 3, 'gamma': 2.135223831860646, 'reg_alpha': 1.4442218039668038, 'reg_lambda': 1.4289228244106922, 'max_delta_step': 3}. Best is trial 5 with value: 0.5182186234817814.

Best trial: 5. Best value: 0.518219:  16%|█▌        | 8/50 [01:08<03:48,  5.45s/it]

[I 2025-12-02 00:35:40,382] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.1205431445376783, 'n_estimators': 704, 'subsample': 0.7935532260323017, 'colsample_bytree': 0.9240425124235945, 'min_child_weight': 6, 'gamma': 2.594400543615958, 'reg_alpha': 1.5845203333172757e-07, 'reg_lambda': 4.347196266854137e-06, 'max_delta_step': 6}. Best is trial 5 with value: 0.5182186234817814.

Best trial: 5. Best value: 0.518219:  18%|█▊        | 9/50 [01:42<09:07, 13.35s/it]

[I 2025-12-02 00:36:14,507] Trial 11 finished with value: 0.1346153846153846 and parameters: {'max_depth': 3, 'learning_rate': 0.0659980407178625, 'n_estimators': 983, 'subsample': 0.6016631972615183, 'colsample_bytree': 0.554506291287008, 'min_child_weight': 5, 'gamma': 1.475192237770877, 'reg_alpha': 1.08273147225527, 'reg_lambda': 3.636973192406902e-08, 'max_delta_step': 10}. Best is trial 5 with value: 0.5182186234817814.

Best trial: 5. Best value: 0.518219:  20%|██        | 10/50 [01:49<07:40, 11.51s/it]

[I 2025-12-02 00:36:21,320] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.27761787094136636, 'n_estimators': 1344, 'subsample': 0.9623957669709093, 'colsample_bytree': 0.9896194056845138, 'min_child_weight': 6, 'gamma': 2.973805660457127, 'reg_alpha': 0.13490882229955523, 'reg_lambda': 3.733717793938112e-05, 'max_delta_step': 3}. Best is trial 5 with value: 0.5182186234817814.

Best trial: 5. Best value: 0.518219:  22%|██▏       | 11/50 [01:51<05:36,  8.63s/it]

[I 2025-12-02 00:36:22,824] Trial 12 pruned.

Best trial: 5. Best value: 0.518219:  24%|██▍       | 12/50 [01:52<04:05,  6.47s/it]

[I 2025-12-02 00:36:24,050] Trial 13 pruned.

Best trial: 5. Best value: 0.518219:  28%|██▊       | 14/50 [01:53<02:02,  3.39s/it]

[I 2025-12-02 00:36:24,651] Trial 10 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.0819814828120548, 'n_estimators': 1277, 'subsample': 0.9227731010417062, 'colsample_bytree': 0.7522792922879113, 'min_child_weight': 8, 'gamma': 4.032283150210228, 'reg_alpha': 3.77042157190248e-07, 'reg_lambda': 0.001157603710855833, 'max_delta_step': 7}. Best is trial 5 with value: 0.5182186234817814.
[I 2025-12-02 00:36:24,806] Trial 9 finished with value: 0.3076923076923077 and parameters: {'max_depth': 9, 'learning_rate': 0.1770814319159593, 'n_estimators': 1436, 'subsample': 0.6271734406061948, 'colsample_bytree': 0.9843305740523312, 'min_child_weight': 4, 'gamma': 4.484365640669075, 'reg_alpha': 4.1748523032848595e-08, 'reg_lambda': 0.046474194690812216, 'max_delta_step': 4}. Best is trial 5 with value: 0.5182186234817814.

Best trial: 5. Best value: 0.518219:  30%|███       | 15/50 [01:53<01:26,  2.47s/it]

[I 2025-12-02 00:36:25,106] Trial 14 pruned.

Best trial: 5. Best value: 0.518219:  32%|███▏      | 16/50 [02:09<03:42,  6.54s/it]

[I 2025-12-02 00:36:41,230] Trial 15 finished with value: 0.32186234817813764 and parameters: {'max_depth': 9, 'learning_rate': 0.032595752119586346, 'n_estimators': 437, 'subsample': 0.6717415234819304, 'colsample_bytree': 0.7309314777679742, 'min_child_weight': 1, 'gamma': 3.4828052349656433, 'reg_alpha': 1.968310579116425e-06, 'reg_lambda': 0.002533295877424567, 'max_delta_step': 0}. Best is trial 5 with value: 0.5182186234817814.

Best trial: 5. Best value: 0.518219:  34%|███▍      | 17/50 [02:10<02:38,  4.81s/it]

[I 2025-12-02 00:36:41,981] Trial 16 finished with value: 0.43218623481781376 and parameters: {'max_depth': 9, 'learning_rate': 0.03325985431580822, 'n_estimators': 404, 'subsample': 0.6771148482613868, 'colsample_bytree': 0.8605039965743793, 'min_child_weight': 1, 'gamma': 1.467383433300516, 'reg_alpha': 4.568287183191537e-06, 'reg_lambda': 5.339326434903372e-07, 'max_delta_step': 0}. Best is trial 5 with value: 0.5182186234817814.

Best trial: 5. Best value: 0.518219:  36%|███▌      | 18/50 [02:14<02:25,  4.55s/it]

[I 2025-12-02 00:36:45,917] Trial 17 finished with value: 0.451417004048583 and parameters: {'max_depth': 9, 'learning_rate': 0.02443092177640366, 'n_estimators': 443, 'subsample': 0.6836575312216301, 'colsample_bytree': 0.8690880210964653, 'min_child_weight': 1, 'gamma': 1.1056369769355503, 'reg_alpha': 3.991568080338854e-06, 'reg_lambda': 5.542819007940157e-07, 'max_delta_step': 0}. Best is trial 5 with value: 0.5182186234817814.

Best trial: 5. Best value: 0.518219:  38%|███▊      | 19/50 [02:16<01:57,  3.80s/it]

[I 2025-12-02 00:36:47,962] Trial 18 finished with value: 0.4251012145748988 and parameters: {'max_depth': 8, 'learning_rate': 0.036071996563317124, 'n_estimators': 595, 'subsample': 0.7105840365537522, 'colsample_bytree': 0.8372866463212795, 'min_child_weight': 1, 'gamma': 1.0441158715549042, 'reg_alpha': 1.84689832552889e-06, 'reg_lambda': 1.9271560962442883e-07, 'max_delta_step': 0}. Best is trial 5 with value: 0.5182186234817814.

Best trial: 5. Best value: 0.518219:  40%|████      | 20/50 [02:35<04:13,  8.46s/it]

[I 2025-12-02 00:37:07,318] Trial 20 finished with value: 0.47773279352226716 and parameters: {'max_depth': 8, 'learning_rate': 0.040722571049967654, 'n_estimators': 805, 'subsample': 0.5006471954007359, 'colsample_bytree': 0.5127551741199116, 'min_child_weight': 2, 'gamma': 0.04792214833113029, 'reg_alpha': 7.658179255020394e-06, 'reg_lambda': 6.52184320823535e-07, 'max_delta_step': 10}. Best is trial 5 with value: 0.5182186234817814.

Best trial: 19. Best value: 0.530364:  42%|████▏     | 21/50 [02:36<03:04,  6.35s/it]

[I 2025-12-02 00:37:08,747] Trial 19 finished with value: 0.5303643724696356 and parameters: {'max_depth': 8, 'learning_rate': 0.03989742141918795, 'n_estimators': 819, 'subsample': 0.9957703554620743, 'colsample_bytree': 0.5020866723644314, 'min_child_weight': 2, 'gamma': 0.9910595691376143, 'reg_alpha': 5.135961258308344e-06, 'reg_lambda': 5.181436015812729e-07, 'max_delta_step': 10}. Best is trial 19 with value: 0.5303643724696356.

Best trial: 19. Best value: 0.530364:  44%|████▍     | 22/50 [02:44<03:06,  6.67s/it]

[I 2025-12-02 00:37:16,153] Trial 22 finished with value: 0.47773279352226716 and parameters: {'max_depth': 10, 'learning_rate': 0.051694167330445, 'n_estimators': 846, 'subsample': 0.8468990603178659, 'colsample_bytree': 0.5069073350707517, 'min_child_weight': 2, 'gamma': 2.4129117825542026, 'reg_alpha': 3.815288633015991e-05, 'reg_lambda': 0.00022794761443409469, 'max_delta_step': 10}. Best is trial 19 with value: 0.5303643724696356.

Best trial: 21. Best value: 0.628543:  46%|████▌     | 23/50 [02:50<02:54,  6.45s/it]

[I 2025-12-02 00:37:22,079] Trial 21 finished with value: 0.6285425101214575 and parameters: {'max_depth': 8, 'learning_rate': 0.04999155499522891, 'n_estimators': 791, 'subsample': 0.9936833579537835, 'colsample_bytree': 0.6671292971520185, 'min_child_weight': 2, 'gamma': 0.15461922854969767, 'reg_alpha': 6.744145719136293e-05, 'reg_lambda': 9.33208761572429, 'max_delta_step': 2}. Best is trial 21 with value: 0.6285425101214575.

Best trial: 21. Best value: 0.628543:  48%|████▊     | 24/50 [03:03<03:39,  8.45s/it]

[I 2025-12-02 00:37:35,218] Trial 23 finished with value: 0.6214574898785425 and parameters: {'max_depth': 6, 'learning_rate': 0.04650596800564067, 'n_estimators': 852, 'subsample': 0.9943667181416223, 'colsample_bytree': 0.5058552904663821, 'min_child_weight': 2, 'gamma': 0.02982653584130668, 'reg_alpha': 4.042643955943922e-05, 'reg_lambda': 0.00015165433963939892, 'max_delta_step': 10}. Best is trial 21 with value: 0.6285425101214575.

Best trial: 21. Best value: 0.628543:  50%|█████     | 25/50 [03:05<02:44,  6.58s/it]

[I 2025-12-02 00:37:37,434] Trial 24 finished with value: 0.5566801619433198 and parameters: {'max_depth': 7, 'learning_rate': 0.0448789745811723, 'n_estimators': 856, 'subsample': 0.9952318478930647, 'colsample_bytree': 0.5044559381700536, 'min_child_weight': 2, 'gamma': 0.008074876871140238, 'reg_alpha': 4.542181809604554e-05, 'reg_lambda': 1.7973449139464152e-06, 'max_delta_step': 10}. Best is trial 21 with value: 0.6285425101214575.

Best trial: 21. Best value: 0.628543:  52%|█████▏    | 26/50 [03:14<02:52,  7.19s/it]

[I 2025-12-02 00:37:46,059] Trial 25 finished with value: 0.6214574898785425 and parameters: {'max_depth': 7, 'learning_rate': 0.045704023423651846, 'n_estimators': 818, 'subsample': 0.9954512974886066, 'colsample_bytree': 0.6884592968944943, 'min_child_weight': 2, 'gamma': 0.07210894527332992, 'reg_alpha': 4.932582351211735e-05, 'reg_lambda': 4.120297659265105e-06, 'max_delta_step': 9}. Best is trial 21 with value: 0.6285425101214575.

Best trial: 26. Best value: 0.640688:  54%|█████▍    | 27/50 [03:28<03:31,  9.22s/it]

[I 2025-12-02 00:37:59,999] Trial 26 finished with value: 0.6406882591093117 and parameters: {'max_depth': 7, 'learning_rate': 0.022196348807490496, 'n_estimators': 951, 'subsample': 0.9979436892801917, 'colsample_bytree': 0.6838879281703223, 'min_child_weight': 2, 'gamma': 0.0073957194960045936, 'reg_alpha': 0.00021100008049423712, 'reg_lambda': 0.301442288347103, 'max_delta_step': 8}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688:  56%|█████▌    | 28/50 [03:36<03:18,  9.01s/it]

[I 2025-12-02 00:38:08,529] Trial 27 finished with value: 0.45344129554655865 and parameters: {'max_depth': 6, 'learning_rate': 0.023661595063201847, 'n_estimators': 970, 'subsample': 0.9957186127499156, 'colsample_bytree': 0.6665415251501114, 'min_child_weight': 4, 'gamma': 0.11784602523858174, 'reg_alpha': 0.00011372104575066007, 'reg_lambda': 0.2721036136171616, 'max_delta_step': 8}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688:  58%|█████▊    | 29/50 [03:43<02:56,  8.41s/it]

[I 2025-12-02 00:38:15,538] Trial 31 pruned.

Best trial: 26. Best value: 0.640688:  60%|██████    | 30/50 [03:44<02:03,  6.15s/it]

[I 2025-12-02 00:38:16,416] Trial 28 finished with value: 0.4797570850202429 and parameters: {'max_depth': 6, 'learning_rate': 0.023935986184729544, 'n_estimators': 1018, 'subsample': 0.9997148576502697, 'colsample_bytree': 0.6908462544124914, 'min_child_weight': 4, 'gamma': 0.0012019675353340808, 'reg_alpha': 0.00035944351434847856, 'reg_lambda': 8.291657728091215, 'max_delta_step': 2}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688:  62%|██████▏   | 31/50 [03:48<01:45,  5.55s/it]

[I 2025-12-02 00:38:20,555] Trial 29 finished with value: 0.45344129554655865 and parameters: {'max_depth': 6, 'learning_rate': 0.02281851610181307, 'n_estimators': 993, 'subsample': 0.9506585566610812, 'colsample_bytree': 0.685941186377363, 'min_child_weight': 4, 'gamma': 0.4075244508096519, 'reg_alpha': 0.0011517485550506614, 'reg_lambda': 0.27623243773031514, 'max_delta_step': 8}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688:  64%|██████▍   | 32/50 [03:52<01:30,  5.02s/it]

[I 2025-12-02 00:38:24,358] Trial 32 pruned.

Best trial: 26. Best value: 0.640688:  66%|██████▌   | 33/50 [03:53<01:03,  3.71s/it]

[I 2025-12-02 00:38:25,009] Trial 33 pruned.

Best trial: 26. Best value: 0.640688:  68%|██████▊   | 34/50 [04:07<01:51,  6.96s/it]

[I 2025-12-02 00:38:39,559] Trial 30 finished with value: 0.45344129554655865 and parameters: {'max_depth': 6, 'learning_rate': 0.01969454297402291, 'n_estimators': 997, 'subsample': 0.9513475325663854, 'colsample_bytree': 0.6824271646752724, 'min_child_weight': 4, 'gamma': 0.554629519142986, 'reg_alpha': 0.0017726839349403382, 'reg_lambda': 8.79451653992134, 'max_delta_step': 8}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688:  70%|███████   | 35/50 [04:17<01:55,  7.73s/it]

[I 2025-12-02 00:38:49,069] Trial 34 finished with value: 0.4919028340080972 and parameters: {'max_depth': 5, 'learning_rate': 0.05682644982812715, 'n_estimators': 766, 'subsample': 0.9542644888290707, 'colsample_bytree': 0.6374216186474806, 'min_child_weight': 3, 'gamma': 0.6146934343861671, 'reg_alpha': 0.015281921462088207, 'reg_lambda': 0.00013743509007769158, 'max_delta_step': 9}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688:  72%|███████▏  | 36/50 [04:20<01:27,  6.23s/it]

[I 2025-12-02 00:38:51,808] Trial 35 finished with value: 0.4848178137651822 and parameters: {'max_depth': 7, 'learning_rate': 0.0964536304546757, 'n_estimators': 770, 'subsample': 0.9139664214151203, 'colsample_bytree': 0.598058609318566, 'min_child_weight': 3, 'gamma': 0.7308972489224971, 'reg_alpha': 0.007589096459080736, 'reg_lambda': 0.00013197770880920529, 'max_delta_step': 9}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688:  74%|███████▍  | 37/50 [04:20<00:59,  4.61s/it]

[I 2025-12-02 00:38:52,627] Trial 36 finished with value: 0.42004048582995945 and parameters: {'max_depth': 7, 'learning_rate': 0.05606920141694929, 'n_estimators': 755, 'subsample': 0.9035096653596061, 'colsample_bytree': 0.5849114381681392, 'min_child_weight': 3, 'gamma': 0.8037363723435871, 'reg_alpha': 2.155363388983018e-05, 'reg_lambda': 0.00011739649999270432, 'max_delta_step': 9}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688:  76%|███████▌  | 38/50 [04:33<01:25,  7.09s/it]

[I 2025-12-02 00:39:05,518] Trial 37 finished with value: 0.37449392712550605 and parameters: {'max_depth': 7, 'learning_rate': 0.05406938326170544, 'n_estimators': 738, 'subsample': 0.9055322470150443, 'colsample_bytree': 0.576903870889729, 'min_child_weight': 3, 'gamma': 0.763918662281772, 'reg_alpha': 1.4971283589550627e-05, 'reg_lambda': 7.822595303574512e-05, 'max_delta_step': 9}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688:  78%|███████▊  | 39/50 [04:50<01:49,  9.94s/it]

[I 2025-12-02 00:39:22,112] Trial 39 finished with value: 0.5425101214574899 and parameters: {'max_depth': 8, 'learning_rate': 0.05267610768854959, 'n_estimators': 892, 'subsample': 0.8847473534122569, 'colsample_bytree': 0.5746840199032708, 'min_child_weight': 2, 'gamma': 0.3022158860367664, 'reg_alpha': 1.8994825913408138e-05, 'reg_lambda': 3.247658122746467e-05, 'max_delta_step': 7}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688:  80%|████████  | 40/50 [04:50<01:10,  7.09s/it]

[I 2025-12-02 00:39:22,559] Trial 38 finished with value: 0.49696356275303644 and parameters: {'max_depth': 7, 'learning_rate': 0.02861169247212768, 'n_estimators': 927, 'subsample': 0.9066124149964286, 'colsample_bytree': 0.5550852236674211, 'min_child_weight': 2, 'gamma': 0.24473876192805483, 'reg_alpha': 1.8455335907918968e-05, 'reg_lambda': 3.3293804515390736e-05, 'max_delta_step': 7}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688:  82%|████████▏ | 41/50 [04:54<00:56,  6.23s/it]

[I 2025-12-02 00:39:26,783] Trial 40 finished with value: 0.5232793522267206 and parameters: {'max_depth': 8, 'learning_rate': 0.029534366365006354, 'n_estimators': 917, 'subsample': 0.88309264830547, 'colsample_bytree': 0.7206217315490299, 'min_child_weight': 2, 'gamma': 1.864062033677854, 'reg_alpha': 0.00010293585109171557, 'reg_lambda': 1.5375453673812182e-05, 'max_delta_step': 7}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688:  84%|████████▍ | 42/50 [05:07<01:03,  7.97s/it]

[I 2025-12-02 00:39:38,819] Trial 41 finished with value: 0.47773279352226716 and parameters: {'max_depth': 8, 'learning_rate': 0.030596408603044606, 'n_estimators': 916, 'subsample': 0.8740298516876421, 'colsample_bytree': 0.7982162689501764, 'min_child_weight': 2, 'gamma': 1.7298712687503217, 'reg_alpha': 9.807831087590938e-05, 'reg_lambda': 2.2269675055101302e-05, 'max_delta_step': 7}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688:  86%|████████▌ | 43/50 [05:12<00:51,  7.35s/it]

[I 2025-12-02 00:39:44,723] Trial 43 finished with value: 0.5566801619433198 and parameters: {'max_depth': 4, 'learning_rate': 0.16494887967616778, 'n_estimators': 608, 'subsample': 0.967375091123482, 'colsample_bytree': 0.7204162642072085, 'min_child_weight': 1, 'gamma': 1.7328390987038276, 'reg_alpha': 0.0001321944728024119, 'reg_lambda': 0.0006425487784085207, 'max_delta_step': 8}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688:  88%|████████▊ | 44/50 [05:18<00:40,  6.67s/it]

[I 2025-12-02 00:39:49,798] Trial 44 finished with value: 0.5303643724696356 and parameters: {'max_depth': 7, 'learning_rate': 0.04440763476809483, 'n_estimators': 647, 'subsample': 0.9775749795454601, 'colsample_bytree': 0.6185929953198595, 'min_child_weight': 1, 'gamma': 0.005379357097323151, 'reg_alpha': 9.21071791615299e-05, 'reg_lambda': 1.944794728121025e-06, 'max_delta_step': 10}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688:  90%|█████████ | 45/50 [05:29<00:40,  8.02s/it]

[I 2025-12-02 00:40:00,970] Trial 42 finished with value: 0.5111336032388664 and parameters: {'max_depth': 4, 'learning_rate': 0.029378666833967282, 'n_estimators': 908, 'subsample': 0.9697861090099706, 'colsample_bytree': 0.7213636619001086, 'min_child_weight': 1, 'gamma': 1.8291707612453638, 'reg_alpha': 0.00016897549706003205, 'reg_lambda': 0.0005804157907737689, 'max_delta_step': 1}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688:  92%|█████████▏| 46/50 [05:31<00:24,  6.19s/it]

[I 2025-12-02 00:40:02,890] Trial 45 finished with value: 0.5040485829959513 and parameters: {'max_depth': 7, 'learning_rate': 0.04506712348087814, 'n_estimators': 646, 'subsample': 0.9756349520669952, 'colsample_bytree': 0.6181697961662797, 'min_child_weight': 1, 'gamma': 0.24618736604043534, 'reg_alpha': 0.00048665032731690246, 'reg_lambda': 2.656878476774534e-06, 'max_delta_step': 10}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688:  94%|█████████▍| 47/50 [05:40<00:21,  7.10s/it]

[I 2025-12-02 00:40:12,111] Trial 49 pruned.

Best trial: 26. Best value: 0.640688:  96%|█████████▌| 48/50 [05:45<00:12,  6.50s/it]

[I 2025-12-02 00:40:17,200] Trial 47 finished with value: 0.5111336032388664 and parameters: {'max_depth': 6, 'learning_rate': 0.06965225477807885, 'n_estimators': 878, 'subsample': 0.933486461842893, 'colsample_bytree': 0.5376082721620228, 'min_child_weight': 3, 'gamma': 0.27078676373702093, 'reg_alpha': 0.0004973111537030006, 'reg_lambda': 5.139679224635512e-06, 'max_delta_step': 1}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688:  98%|█████████▊| 49/50 [05:48<00:05,  5.33s/it]

[I 2025-12-02 00:40:19,807] Trial 46 finished with value: 0.5495951417004048 and parameters: {'max_depth': 7, 'learning_rate': 0.04424734437599265, 'n_estimators': 1072, 'subsample': 0.9717716792259664, 'colsample_bytree': 0.5303785689370161, 'min_child_weight': 1, 'gamma': 0.23906628123790397, 'reg_alpha': 0.0005027256799045222, 'reg_lambda': 6.415263740168079e-06, 'max_delta_step': 10}. Best is trial 26 with value: 0.6406882591093117.

Best trial: 26. Best value: 0.640688: 100%|██████████| 50/50 [05:55<00:00,  7.11s/it]

[I 2025-12-02 00:40:27,529] Trial 48 finished with value: 0.4919028340080972 and parameters: {'max_depth': 6, 'learning_rate': 0.08405964728410191, 'n_estimators': 1201, 'subsample': 0.9286711935330761, 'colsample_bytree': 0.5255185048037131, 'min_child_weight': 3, 'gamma': 1.2496816815273564, 'reg_alpha': 0.0004292517956429175, 'reg_lambda': 4.112124283196688e-06, 'max_delta_step': 10}. Best is trial 26 with value: 0.6406882591093117.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.659039                0.650000      0.766667
1    19_1         loo       0.790570                0.550000      0.566667
2    15_1         loo       0.623158                0.485714      0.400000
3    17_1         loo       0.640688                0.242857      0.285714

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.310530          0.500000               0.8        50          42
1  0.100000          0.500000               0.6        50          43
2 -0.028571          0.571429               0.4        50          44
3 -0.507093          0.285714               0.2        50          45

   test_size
0         11
1         11
2         12
3         12
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.659039                0.650000      0.766667
1    19_1         loo       0.790570                0.550000      0.566667
2    15_1         loo       0.623158                0.485714      0.400000
3    17_1         loo       0.640688                0.242857      0.285714

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.310530          0.500000               0.8        50          42
1  0.100000          0.500000               0.6        50          43
2 -0.028571          0.571429               0.4        50          44
3 -0.507093          0.285714               0.2        50          45

   test_size
0         11
1         11
2         12
3         12

In [ ]:

datasets = task_hf_compensated_freq_emb_lbl_ad_lbd

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_lbd_{CV_STRATEGY}_tasks/xgb_results_handcrafted_frerq_emb_compensated_ad_lbd_extended_{CV_STRATEGY}_tasks",
    split_param= "diagnosis_y",
)
print(summary)
## MCI-AD vs HC -> OPTUNA + XGB

[I 2025-12-02 00:40:32,437] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 42, Test size: 11
Using Leave-One-Out CV with 42 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.641876:   2%|▏         | 1/50 [00:10<08:28, 10.37s/it]

[I 2025-12-02 00:40:42,799] Trial 3 finished with value: 0.6418764302059496 and parameters: {'max_depth': 10, 'learning_rate': 0.04788741829078676, 'n_estimators': 254, 'subsample': 0.643464596102097, 'colsample_bytree': 0.8148477779836287, 'min_child_weight': 3, 'gamma': 3.855829840445571, 'reg_alpha': 6.879224063807595e-06, 'reg_lambda': 0.0001118296509970077, 'max_delta_step': 5}. Best is trial 3 with value: 0.6418764302059496.
[I 2025-12-02 00:40:42,801] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.05509839088837269, 'n_estimators': 297, 'subsample': 0.683383846950161, 'colsample_bytree': 0.5426209733793848, 'min_child_weight': 9, 'gamma': 2.5932266941991045, 'reg_alpha': 7.045089683258602e-07, 'reg_lambda': 0.002281842857443521, 'max_delta_step': 8}. Best is trial 3 with value: 0.6418764302059496.

Best trial: 3. Best value: 0.641876:   6%|▌         | 3/50 [00:23<05:58,  7.63s/it]

[I 2025-12-02 00:40:56,153] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.05464313180644399, 'n_estimators': 718, 'subsample': 0.5119740787763886, 'colsample_bytree': 0.6421212253653655, 'min_child_weight': 7, 'gamma': 1.125623584131485, 'reg_alpha': 0.02059061338448788, 'reg_lambda': 0.0029702681786950066, 'max_delta_step': 5}. Best is trial 3 with value: 0.6418764302059496.

Best trial: 3. Best value: 0.641876:   8%|▊         | 4/50 [00:26<04:32,  5.92s/it]

[I 2025-12-02 00:40:58,822] Trial 0 finished with value: 0.3524027459954233 and parameters: {'max_depth': 9, 'learning_rate': 0.190369125818697, 'n_estimators': 797, 'subsample': 0.718038134521709, 'colsample_bytree': 0.667375345573432, 'min_child_weight': 6, 'gamma': 0.3452453977051495, 'reg_alpha': 1.2263972678173838e-07, 'reg_lambda': 0.0003521542948479468, 'max_delta_step': 4}. Best is trial 3 with value: 0.6418764302059496.

Best trial: 4. Best value: 0.659039:  10%|█         | 5/50 [00:29<03:37,  4.84s/it]

[I 2025-12-02 00:41:01,482] Trial 4 finished with value: 0.6590389016018307 and parameters: {'max_depth': 6, 'learning_rate': 0.04413357637103782, 'n_estimators': 415, 'subsample': 0.6337168219093838, 'colsample_bytree': 0.5676987981999682, 'min_child_weight': 1, 'gamma': 3.4830826097532226, 'reg_alpha': 1.5067361560450788e-07, 'reg_lambda': 2.9575875026066134, 'max_delta_step': 6}. Best is trial 4 with value: 0.6590389016018307.

Best trial: 4. Best value: 0.659039:  12%|█▏        | 6/50 [00:54<08:21, 11.40s/it]

[I 2025-12-02 00:41:26,777] Trial 6 finished with value: 0.2894736842105263 and parameters: {'max_depth': 8, 'learning_rate': 0.1882799639289996, 'n_estimators': 889, 'subsample': 0.5223316066386285, 'colsample_bytree': 0.7655929093338067, 'min_child_weight': 7, 'gamma': 3.1379067123766173, 'reg_alpha': 4.321007003985863e-05, 'reg_lambda': 0.00365696388801991, 'max_delta_step': 10}. Best is trial 4 with value: 0.6590389016018307.

Best trial: 4. Best value: 0.659039:  14%|█▍        | 7/50 [00:57<06:15,  8.74s/it]

[I 2025-12-02 00:41:29,712] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.06660964374469379, 'n_estimators': 1489, 'subsample': 0.9206969055199876, 'colsample_bytree': 0.5354795325785677, 'min_child_weight': 5, 'gamma': 1.3053346111692121, 'reg_alpha': 1.2967023935155881, 'reg_lambda': 4.273214818063348, 'max_delta_step': 4}. Best is trial 4 with value: 0.6590389016018307.
[I 2025-12-02 00:41:29,888] Trial 8 finished with value: 0.4473684210526316 and parameters: {'max_depth': 4, 'learning_rate': 0.13801971034076166, 'n_estimators': 868, 'subsample': 0.8140207433497868, 'colsample_bytree': 0.5662809518663333, 'min_child_weight': 6, 'gamma': 4.889453365806639, 'reg_alpha': 1.2428437458296294e-07, 'reg_lambda': 0.621701501053439, 'max_delta_step': 7}. Best is trial 4 with value: 0.6590389016018307.

Best trial: 4. Best value: 0.659039:  18%|█▊        | 9/50 [00:59<03:24,  4.99s/it]

[I 2025-12-02 00:41:32,405] Trial 7 finished with value: 0.18306636155606407 and parameters: {'max_depth': 8, 'learning_rate': 0.13143844507063773, 'n_estimators': 949, 'subsample': 0.6637077108790617, 'colsample_bytree': 0.9018260520989256, 'min_child_weight': 6, 'gamma': 1.0942075567451004, 'reg_alpha': 0.004547567536279821, 'reg_lambda': 7.904982450310756, 'max_delta_step': 7}. Best is trial 4 with value: 0.6590389016018307.

Best trial: 4. Best value: 0.659039:  20%|██        | 10/50 [01:04<03:19,  4.99s/it]

[I 2025-12-02 00:41:37,399] Trial 11 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.037541280671167104, 'n_estimators': 213, 'subsample': 0.8189640529246582, 'colsample_bytree': 0.5897314040162641, 'min_child_weight': 6, 'gamma': 3.3738784439258644, 'reg_alpha': 9.935426549982805e-06, 'reg_lambda': 1.5999304972924522e-07, 'max_delta_step': 9}. Best is trial 4 with value: 0.6590389016018307.

Best trial: 4. Best value: 0.659039:  22%|██▏       | 11/50 [01:14<04:07,  6.34s/it]

[I 2025-12-02 00:41:46,828] Trial 12 pruned.

Best trial: 4. Best value: 0.659039:  24%|██▍       | 12/50 [01:20<03:59,  6.30s/it]

[I 2025-12-02 00:41:53,044] Trial 9 finished with value: 0.6327231121281465 and parameters: {'max_depth': 3, 'learning_rate': 0.08046092540966591, 'n_estimators': 802, 'subsample': 0.8416923429624317, 'colsample_bytree': 0.591350478319941, 'min_child_weight': 1, 'gamma': 3.770107018067956, 'reg_alpha': 4.5462525624773984e-06, 'reg_lambda': 6.821843051041583e-08, 'max_delta_step': 8}. Best is trial 4 with value: 0.6590389016018307.

Best trial: 4. Best value: 0.659039:  26%|██▌       | 13/50 [01:26<03:47,  6.16s/it]

[I 2025-12-02 00:41:58,868] Trial 10 finished with value: 0.6590389016018307 and parameters: {'max_depth': 4, 'learning_rate': 0.013893615009693206, 'n_estimators': 550, 'subsample': 0.8875314294547777, 'colsample_bytree': 0.9898343975331001, 'min_child_weight': 1, 'gamma': 0.7355815344548461, 'reg_alpha': 8.746524020420926e-07, 'reg_lambda': 1.622121194596472e-05, 'max_delta_step': 8}. Best is trial 4 with value: 0.6590389016018307.

Best trial: 4. Best value: 0.659039:  28%|██▊       | 14/50 [01:29<03:09,  5.26s/it]

[I 2025-12-02 00:42:02,038] Trial 13 finished with value: 0.5194508009153318 and parameters: {'max_depth': 5, 'learning_rate': 0.011956551647028862, 'n_estimators': 547, 'subsample': 0.9831290491383397, 'colsample_bytree': 0.9629758155549932, 'min_child_weight': 1, 'gamma': 4.733251204633202, 'reg_alpha': 2.2349225284996235e-08, 'reg_lambda': 1.675161674110471e-06, 'max_delta_step': 0}. Best is trial 4 with value: 0.6590389016018307.

Best trial: 4. Best value: 0.659039:  30%|███       | 15/50 [01:33<02:47,  4.80s/it]

[I 2025-12-02 00:42:05,759] Trial 14 finished with value: 0.6590389016018307 and parameters: {'max_depth': 10, 'learning_rate': 0.013582285871538858, 'n_estimators': 445, 'subsample': 0.6072232112721302, 'colsample_bytree': 0.8563152651826044, 'min_child_weight': 1, 'gamma': 4.154055316928967, 'reg_alpha': 1.5505991338032562e-08, 'reg_lambda': 7.260163612098911e-07, 'max_delta_step': 1}. Best is trial 4 with value: 0.6590389016018307.

Best trial: 4. Best value: 0.659039:  32%|███▏      | 16/50 [01:40<03:03,  5.41s/it]

[I 2025-12-02 00:42:12,604] Trial 15 finished with value: 0.6590389016018307 and parameters: {'max_depth': 10, 'learning_rate': 0.015244607657549133, 'n_estimators': 477, 'subsample': 0.6205728503932159, 'colsample_bytree': 0.8385076596061902, 'min_child_weight': 1, 'gamma': 4.833238832709177, 'reg_alpha': 2.4815604782732322e-08, 'reg_lambda': 4.426280355781422e-06, 'max_delta_step': 0}. Best is trial 4 with value: 0.6590389016018307.

Best trial: 4. Best value: 0.659039:  34%|███▍      | 17/50 [01:44<02:47,  5.08s/it]

[I 2025-12-02 00:42:16,910] Trial 17 finished with value: 0.6372997711670481 and parameters: {'max_depth': 5, 'learning_rate': 0.01980208328400048, 'n_estimators': 490, 'subsample': 0.5964457078509852, 'colsample_bytree': 0.9938109169226571, 'min_child_weight': 3, 'gamma': 2.257594541119408, 'reg_alpha': 0.0002192914128248997, 'reg_lambda': 6.347741866526901e-06, 'max_delta_step': 2}. Best is trial 4 with value: 0.6590389016018307.

Best trial: 18. Best value: 0.663616:  36%|███▌      | 18/50 [01:49<02:38,  4.94s/it]

[I 2025-12-02 00:42:21,517] Trial 18 finished with value: 0.6636155606407322 and parameters: {'max_depth': 5, 'learning_rate': 0.02381400478739319, 'n_estimators': 552, 'subsample': 0.5812014182350493, 'colsample_bytree': 0.7371679005657186, 'min_child_weight': 3, 'gamma': 2.2433361856217746, 'reg_alpha': 0.0003743910818795417, 'reg_lambda': 1.123810852022797e-05, 'max_delta_step': 2}. Best is trial 18 with value: 0.6636155606407322.

Best trial: 18. Best value: 0.663616:  38%|███▊      | 19/50 [01:49<01:51,  3.61s/it]

[I 2025-12-02 00:42:22,018] Trial 20 pruned.

Best trial: 18. Best value: 0.663616:  40%|████      | 20/50 [01:52<01:41,  3.40s/it]

[I 2025-12-02 00:42:24,927] Trial 22 pruned.

Best trial: 16. Best value: 0.680778:  42%|████▏     | 21/50 [01:53<01:15,  2.60s/it]

[I 2025-12-02 00:42:25,687] Trial 16 finished with value: 0.6807780320366132 and parameters: {'max_depth': 5, 'learning_rate': 0.014423935436379877, 'n_estimators': 515, 'subsample': 0.6024739345388261, 'colsample_bytree': 0.9904043433907797, 'min_child_weight': 1, 'gamma': 1.9617162155381782, 'reg_alpha': 3.9937321187391265e-08, 'reg_lambda': 8.777827402450523e-06, 'max_delta_step': 1}. Best is trial 16 with value: 0.6807780320366132.

Best trial: 16. Best value: 0.680778:  44%|████▍     | 22/50 [01:58<01:37,  3.47s/it]

[I 2025-12-02 00:42:31,173] Trial 24 pruned.

Best trial: 19. Best value: 0.685355:  46%|████▌     | 23/50 [02:00<01:20,  2.97s/it]

[I 2025-12-02 00:42:32,984] Trial 19 finished with value: 0.6853546910755148 and parameters: {'max_depth': 5, 'learning_rate': 0.024381469890430527, 'n_estimators': 591, 'subsample': 0.7618428493333105, 'colsample_bytree': 0.9849330911590036, 'min_child_weight': 3, 'gamma': 2.0449442572542105, 'reg_alpha': 0.00034152220242395377, 'reg_lambda': 0.14587217815394973, 'max_delta_step': 3}. Best is trial 19 with value: 0.6853546910755148.

Best trial: 19. Best value: 0.685355:  48%|████▊     | 24/50 [02:08<01:59,  4.60s/it]

[I 2025-12-02 00:42:41,374] Trial 26 pruned.

Best trial: 19. Best value: 0.685355:  50%|█████     | 25/50 [02:13<01:56,  4.65s/it]

[I 2025-12-02 00:42:46,138] Trial 25 finished with value: 0.6155606407322655 and parameters: {'max_depth': 4, 'learning_rate': 0.02624247799076039, 'n_estimators': 378, 'subsample': 0.5585751709055582, 'colsample_bytree': 0.7917867473897736, 'min_child_weight': 2, 'gamma': 2.796405666903402, 'reg_alpha': 0.5865710991595545, 'reg_lambda': 3.6954572974979324e-05, 'max_delta_step': 2}. Best is trial 19 with value: 0.6853546910755148.

Best trial: 19. Best value: 0.685355:  52%|█████▏    | 26/50 [02:21<02:17,  5.74s/it]

[I 2025-12-02 00:42:54,410] Trial 21 finished with value: 0.6590389016018307 and parameters: {'max_depth': 7, 'learning_rate': 0.0277832927462318, 'n_estimators': 1097, 'subsample': 0.5735049660616962, 'colsample_bytree': 0.6947819266710303, 'min_child_weight': 3, 'gamma': 2.005752061510359, 'reg_alpha': 0.0015561075635372684, 'reg_lambda': 0.10007591936261664, 'max_delta_step': 3}. Best is trial 19 with value: 0.6853546910755148.

Best trial: 19. Best value: 0.685355:  54%|█████▍    | 27/50 [02:26<02:06,  5.52s/it]

[I 2025-12-02 00:42:59,419] Trial 23 finished with value: 0.6590389016018307 and parameters: {'max_depth': 6, 'learning_rate': 0.023221259425469903, 'n_estimators': 1054, 'subsample': 0.7568864022369645, 'colsample_bytree': 0.7310400315258045, 'min_child_weight': 2, 'gamma': 2.8829086222076614, 'reg_alpha': 0.40986059371137584, 'reg_lambda': 1.703682350364251e-08, 'max_delta_step': 2}. Best is trial 19 with value: 0.6853546910755148.

Best trial: 19. Best value: 0.685355:  56%|█████▌    | 28/50 [02:30<01:46,  4.82s/it]

[I 2025-12-02 00:43:02,613] Trial 27 finished with value: 0.6372997711670481 and parameters: {'max_depth': 5, 'learning_rate': 0.026085702153739135, 'n_estimators': 618, 'subsample': 0.5754048148064936, 'colsample_bytree': 0.9219140022479251, 'min_child_weight': 2, 'gamma': 1.6822227274504433, 'reg_alpha': 0.0010816230601839543, 'reg_lambda': 6.273119999773207e-05, 'max_delta_step': 1}. Best is trial 19 with value: 0.6853546910755148.

Best trial: 19. Best value: 0.685355:  58%|█████▊    | 29/50 [02:31<01:19,  3.79s/it]

[I 2025-12-02 00:43:04,012] Trial 30 pruned.

Best trial: 19. Best value: 0.685355:  60%|██████    | 30/50 [02:35<01:17,  3.89s/it]

[I 2025-12-02 00:43:08,114] Trial 31 pruned.

Best trial: 19. Best value: 0.685355:  62%|██████▏   | 31/50 [02:36<00:57,  3.05s/it]

[I 2025-12-02 00:43:09,213] Trial 32 pruned.

Best trial: 19. Best value: 0.685355:  64%|██████▍   | 32/50 [02:39<00:53,  2.99s/it]

[I 2025-12-02 00:43:12,046] Trial 28 finished with value: 0.6853546910755148 and parameters: {'max_depth': 5, 'learning_rate': 0.010037380310331488, 'n_estimators': 587, 'subsample': 0.7022480467897346, 'colsample_bytree': 0.9036015150732282, 'min_child_weight': 2, 'gamma': 1.7513260954996819, 'reg_alpha': 4.687732932141121e-05, 'reg_lambda': 0.023506698742812547, 'max_delta_step': 1}. Best is trial 19 with value: 0.6853546910755148.

Best trial: 19. Best value: 0.685355:  66%|██████▌   | 33/50 [02:40<00:40,  2.39s/it]

[I 2025-12-02 00:43:13,035] Trial 33 pruned.

Best trial: 19. Best value: 0.685355:  68%|██████▊   | 34/50 [02:44<00:44,  2.80s/it]

[I 2025-12-02 00:43:16,797] Trial 36 pruned.

Best trial: 19. Best value: 0.685355:  70%|███████   | 35/50 [02:48<00:49,  3.31s/it]

[I 2025-12-02 00:43:21,302] Trial 29 finished with value: 0.6372997711670481 and parameters: {'max_depth': 5, 'learning_rate': 0.010704942452058145, 'n_estimators': 647, 'subsample': 0.7143745637658435, 'colsample_bytree': 0.8975005648744739, 'min_child_weight': 2, 'gamma': 1.5547582259332042, 'reg_alpha': 4.008407048409812e-05, 'reg_lambda': 0.016593763198444626, 'max_delta_step': 1}. Best is trial 19 with value: 0.6853546910755148.

Best trial: 19. Best value: 0.685355:  72%|███████▏  | 36/50 [02:49<00:36,  2.63s/it]

[I 2025-12-02 00:43:22,347] Trial 34 finished with value: 0.6418764302059496 and parameters: {'max_depth': 6, 'learning_rate': 0.03767727884918688, 'n_estimators': 397, 'subsample': 0.6372175713401516, 'colsample_bytree': 0.6286986053390056, 'min_child_weight': 2, 'gamma': 3.391899124594143, 'reg_alpha': 1.4434453797573188e-07, 'reg_lambda': 1.1429477602835796, 'max_delta_step': 3}. Best is trial 19 with value: 0.6853546910755148.

Best trial: 19. Best value: 0.685355:  74%|███████▍  | 37/50 [02:51<00:31,  2.43s/it]

[I 2025-12-02 00:43:24,292] Trial 38 pruned.

Best trial: 19. Best value: 0.685355:  76%|███████▌  | 38/50 [03:00<00:50,  4.17s/it]

[I 2025-12-02 00:43:32,529] Trial 37 finished with value: 0.6853546910755148 and parameters: {'max_depth': 6, 'learning_rate': 0.012459955381150654, 'n_estimators': 347, 'subsample': 0.6713417553942935, 'colsample_bytree': 0.9992434270304121, 'min_child_weight': 2, 'gamma': 1.944680329736654, 'reg_alpha': 0.008219533220853793, 'reg_lambda': 0.3010855281311407, 'max_delta_step': 0}. Best is trial 19 with value: 0.6853546910755148.

Best trial: 19. Best value: 0.685355:  78%|███████▊  | 39/50 [03:01<00:36,  3.32s/it]

[I 2025-12-02 00:43:33,882] Trial 39 finished with value: 0.6853546910755148 and parameters: {'max_depth': 3, 'learning_rate': 0.012679949111267007, 'n_estimators': 311, 'subsample': 0.6662015184632675, 'colsample_bytree': 0.975600334074235, 'min_child_weight': 3, 'gamma': 1.9192821270638334, 'reg_alpha': 3.1615230670906084e-06, 'reg_lambda': 0.4829602009941384, 'max_delta_step': 0}. Best is trial 19 with value: 0.6853546910755148.

Best trial: 19. Best value: 0.685355:  80%|████████  | 40/50 [03:03<00:28,  2.82s/it]

[I 2025-12-02 00:43:35,520] Trial 40 finished with value: 0.6853546910755148 and parameters: {'max_depth': 3, 'learning_rate': 0.012735090564284065, 'n_estimators': 283, 'subsample': 0.7354224252428352, 'colsample_bytree': 0.8148837967323781, 'min_child_weight': 3, 'gamma': 0.9149432581819668, 'reg_alpha': 0.000652205535813981, 'reg_lambda': 0.00016988015040803728, 'max_delta_step': 0}. Best is trial 19 with value: 0.6853546910755148.

Best trial: 19. Best value: 0.685355:  82%|████████▏ | 41/50 [03:03<00:20,  2.24s/it]

[I 2025-12-02 00:43:36,397] Trial 42 pruned.

Best trial: 19. Best value: 0.685355:  84%|████████▍ | 42/50 [03:04<00:13,  1.68s/it]

[I 2025-12-02 00:43:36,796] Trial 35 finished with value: 0.6636155606407322 and parameters: {'max_depth': 5, 'learning_rate': 0.010716710360222854, 'n_estimators': 552, 'subsample': 0.7306758874925369, 'colsample_bytree': 0.9589625009313479, 'min_child_weight': 2, 'gamma': 0.9577184996600976, 'reg_alpha': 4.241420124205678e-05, 'reg_lambda': 0.025664337981102982, 'max_delta_step': 3}. Best is trial 19 with value: 0.6853546910755148.

Best trial: 19. Best value: 0.685355:  86%|████████▌ | 43/50 [03:05<00:10,  1.56s/it]

[I 2025-12-02 00:43:38,070] Trial 43 pruned.

Best trial: 19. Best value: 0.685355:  88%|████████▊ | 44/50 [03:06<00:08,  1.34s/it]

[I 2025-12-02 00:43:38,884] Trial 45 pruned.

Best trial: 19. Best value: 0.685355:  90%|█████████ | 45/50 [03:06<00:05,  1.00s/it]

[I 2025-12-02 00:43:39,102] Trial 44 pruned.

Best trial: 19. Best value: 0.685355:  94%|█████████▍| 47/50 [03:08<00:02,  1.02it/s]

[I 2025-12-02 00:43:41,258] Trial 47 pruned.
[I 2025-12-02 00:43:41,379] Trial 46 pruned.

Best trial: 19. Best value: 0.685355:  96%|█████████▌| 48/50 [03:09<00:01,  1.37it/s]

[I 2025-12-02 00:43:41,532] Trial 48 pruned.

Best trial: 19. Best value: 0.685355:  98%|█████████▊| 49/50 [03:13<00:01,  1.95s/it]

[I 2025-12-02 00:43:46,326] Trial 41 finished with value: 0.6590389016018307 and parameters: {'max_depth': 7, 'learning_rate': 0.012582628822889016, 'n_estimators': 288, 'subsample': 0.7300934229290114, 'colsample_bytree': 0.9696778594034808, 'min_child_weight': 2, 'gamma': 0.9961726757494384, 'reg_alpha': 0.010372840527084069, 'reg_lambda': 0.3094324623801759, 'max_delta_step': 0}. Best is trial 19 with value: 0.6853546910755148.

Best trial: 19. Best value: 0.685355: 100%|██████████| 50/50 [03:20<00:00,  4.00s/it]

[I 2025-12-02 00:43:52,476] Trial 49 finished with value: 0.6590389016018307 and parameters: {'max_depth': 4, 'learning_rate': 0.055061510087480135, 'n_estimators': 406, 'subsample': 0.8133992723527301, 'colsample_bytree': 0.9734490292472623, 'min_child_weight': 2, 'gamma': 0.5649444376516242, 'reg_alpha': 2.924301136759331e-06, 'reg_lambda': 6.174891111156133, 'max_delta_step': 1}. Best is trial 19 with value: 0.6853546910755148.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 00:43:57,014] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 44, Test size: 12
Using Leave-One-Out CV with 44 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.36:   2%|▏         | 1/50 [00:08<06:59,  8.57s/it]

[I 2025-12-02 00:44:05,570] Trial 1 finished with value: 0.36 and parameters: {'max_depth': 6, 'learning_rate': 0.0739237807053286, 'n_estimators': 212, 'subsample': 0.5664677821871974, 'colsample_bytree': 0.750306954172977, 'min_child_weight': 3, 'gamma': 2.192864932593773, 'reg_alpha': 1.966109942216667e-06, 'reg_lambda': 9.055671712380022, 'max_delta_step': 9}. Best is trial 1 with value: 0.36.

Best trial: 1. Best value: 0.36:   4%|▍         | 2/50 [00:17<06:59,  8.74s/it]

[I 2025-12-02 00:44:14,442] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.010610885471242908, 'n_estimators': 476, 'subsample': 0.8043881814078646, 'colsample_bytree': 0.5180706010294878, 'min_child_weight': 10, 'gamma': 2.2065758760250636, 'reg_alpha': 8.430438041952618e-08, 'reg_lambda': 0.3434599698611829, 'max_delta_step': 0}. Best is trial 1 with value: 0.36.

Best trial: 4. Best value: 0.46:   6%|▌         | 3/50 [00:21<05:18,  6.77s/it]

[I 2025-12-02 00:44:18,867] Trial 4 finished with value: 0.46 and parameters: {'max_depth': 3, 'learning_rate': 0.22517957033478966, 'n_estimators': 334, 'subsample': 0.5298329228850063, 'colsample_bytree': 0.8909216140440821, 'min_child_weight': 4, 'gamma': 3.967082264542575, 'reg_alpha': 0.00920167356628585, 'reg_lambda': 0.0039227466320309445, 'max_delta_step': 8}. Best is trial 4 with value: 0.46.

Best trial: 4. Best value: 0.46:   8%|▊         | 4/50 [00:23<03:37,  4.72s/it]

[I 2025-12-02 00:44:20,437] Trial 0 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.020956107755925792, 'n_estimators': 663, 'subsample': 0.7323662947974459, 'colsample_bytree': 0.5557131999743778, 'min_child_weight': 8, 'gamma': 3.7762303388849268, 'reg_alpha': 1.287805210191348e-06, 'reg_lambda': 1.7607135601450892, 'max_delta_step': 8}. Best is trial 4 with value: 0.46.

Best trial: 4. Best value: 0.46:  10%|█         | 5/50 [00:26<03:09,  4.21s/it]

[I 2025-12-02 00:44:23,750] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.02554768863630874, 'n_estimators': 747, 'subsample': 0.8311369366939441, 'colsample_bytree': 0.611342208100107, 'min_child_weight': 9, 'gamma': 2.504608424489664, 'reg_alpha': 0.24573279841912507, 'reg_lambda': 9.753628824532335, 'max_delta_step': 4}. Best is trial 4 with value: 0.46.

Best trial: 4. Best value: 0.46:  12%|█▏        | 6/50 [00:43<06:15,  8.53s/it]

[I 2025-12-02 00:44:40,668] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.018245613303303012, 'n_estimators': 740, 'subsample': 0.9255566704962217, 'colsample_bytree': 0.8306739510317203, 'min_child_weight': 7, 'gamma': 3.367925619167033, 'reg_alpha': 5.156830106254434, 'reg_lambda': 0.0006085300530653325, 'max_delta_step': 2}. Best is trial 4 with value: 0.46.

Best trial: 4. Best value: 0.46:  14%|█▍        | 7/50 [01:05<09:19, 13.01s/it]

[I 2025-12-02 00:45:02,888] Trial 6 finished with value: 0.43052631578947365 and parameters: {'max_depth': 7, 'learning_rate': 0.014579737686636526, 'n_estimators': 1097, 'subsample': 0.9378972701898685, 'colsample_bytree': 0.5945987382391059, 'min_child_weight': 3, 'gamma': 0.1350444745291779, 'reg_alpha': 1.6698043491853764e-08, 'reg_lambda': 0.00039866673968075284, 'max_delta_step': 8}. Best is trial 4 with value: 0.46.

Best trial: 4. Best value: 0.46:  16%|█▌        | 8/50 [01:11<07:32, 10.78s/it]

[I 2025-12-02 00:45:08,890] Trial 7 finished with value: 0.42 and parameters: {'max_depth': 6, 'learning_rate': 0.012326276742798185, 'n_estimators': 1477, 'subsample': 0.5834021416455734, 'colsample_bytree': 0.7305989787183447, 'min_child_weight': 5, 'gamma': 0.5544262044097997, 'reg_alpha': 0.0020381416372331276, 'reg_lambda': 0.03600427035406977, 'max_delta_step': 2}. Best is trial 4 with value: 0.46.

Best trial: 4. Best value: 0.46:  18%|█▊        | 9/50 [01:15<05:44,  8.40s/it]

[I 2025-12-02 00:45:12,081] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.042376519581812044, 'n_estimators': 1445, 'subsample': 0.9913111297269237, 'colsample_bytree': 0.8180228942669281, 'min_child_weight': 9, 'gamma': 3.2566857290207425, 'reg_alpha': 0.0028981164607271136, 'reg_lambda': 7.345657662047675e-06, 'max_delta_step': 1}. Best is trial 4 with value: 0.46.

Best trial: 4. Best value: 0.46:  20%|██        | 10/50 [01:23<05:36,  8.41s/it]

[I 2025-12-02 00:45:20,511] Trial 11 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.0908397343719728, 'n_estimators': 331, 'subsample': 0.9265011992639207, 'colsample_bytree': 0.5654390768239894, 'min_child_weight': 10, 'gamma': 4.698430969058543, 'reg_alpha': 0.20011160551215537, 'reg_lambda': 0.4840463211923466, 'max_delta_step': 7}. Best is trial 4 with value: 0.46.

Best trial: 4. Best value: 0.46:  22%|██▏       | 11/50 [01:27<04:33,  7.00s/it]

[I 2025-12-02 00:45:24,309] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.029225795222222486, 'n_estimators': 1238, 'subsample': 0.7238010260240202, 'colsample_bytree': 0.9873087735629102, 'min_child_weight': 9, 'gamma': 4.271500765671797, 'reg_alpha': 1.1201734822887626, 'reg_lambda': 7.1003534418033665, 'max_delta_step': 0}. Best is trial 4 with value: 0.46.

Best trial: 4. Best value: 0.46:  24%|██▍       | 12/50 [01:34<04:22,  6.92s/it]

[I 2025-12-02 00:45:31,038] Trial 10 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.16632316363652747, 'n_estimators': 662, 'subsample': 0.9140572732390997, 'colsample_bytree': 0.6613298935279927, 'min_child_weight': 1, 'gamma': 4.075417382576295, 'reg_alpha': 8.851425359699135, 'reg_lambda': 1.7589722253115556, 'max_delta_step': 0}. Best is trial 4 with value: 0.46.

Best trial: 4. Best value: 0.46:  26%|██▌       | 13/50 [01:49<05:54,  9.59s/it]

[I 2025-12-02 00:45:46,790] Trial 12 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.18949979044351517, 'n_estimators': 1085, 'subsample': 0.6784449456333999, 'colsample_bytree': 0.9388452906728044, 'min_child_weight': 9, 'gamma': 0.5632727861011594, 'reg_alpha': 0.0406502963101483, 'reg_lambda': 0.014969872561964064, 'max_delta_step': 3}. Best is trial 4 with value: 0.46.

Best trial: 14. Best value: 0.484211:  28%|██▊       | 14/50 [02:03<06:25, 10.71s/it]

[I 2025-12-02 00:46:00,069] Trial 14 finished with value: 0.4842105263157894 and parameters: {'max_depth': 3, 'learning_rate': 0.2806440482840971, 'n_estimators': 1063, 'subsample': 0.6487578081286102, 'colsample_bytree': 0.9910963356739676, 'min_child_weight': 1, 'gamma': 0.20480593782232637, 'reg_alpha': 3.407890234413276e-05, 'reg_lambda': 1.1012353025753004e-08, 'max_delta_step': 10}. Best is trial 14 with value: 0.4842105263157894.

Best trial: 13. Best value: 0.516842:  30%|███       | 15/50 [02:07<05:06,  8.75s/it]

[I 2025-12-02 00:46:04,269] Trial 13 finished with value: 0.5168421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.2797144846490951, 'n_estimators': 1094, 'subsample': 0.5005984577175197, 'colsample_bytree': 0.99780525760603, 'min_child_weight': 1, 'gamma': 4.98864515095627, 'reg_alpha': 9.683422623607607e-05, 'reg_lambda': 3.052747930261281e-08, 'max_delta_step': 6}. Best is trial 13 with value: 0.5168421052631579.

Best trial: 13. Best value: 0.516842:  32%|███▏      | 16/50 [02:08<03:35,  6.35s/it]

[I 2025-12-02 00:46:05,054] Trial 15 finished with value: 0.34 and parameters: {'max_depth': 3, 'learning_rate': 0.2464683430448246, 'n_estimators': 1039, 'subsample': 0.6477051930039636, 'colsample_bytree': 0.9602252093859822, 'min_child_weight': 4, 'gamma': 1.6444835838364489, 'reg_alpha': 4.1997759211176916e-05, 'reg_lambda': 2.3838585879162554e-08, 'max_delta_step': 10}. Best is trial 13 with value: 0.5168421052631579.

Best trial: 13. Best value: 0.516842:  34%|███▍      | 17/50 [02:23<05:02,  9.16s/it]

[I 2025-12-02 00:46:20,753] Trial 16 finished with value: 0.4189473684210526 and parameters: {'max_depth': 3, 'learning_rate': 0.29676078097244224, 'n_estimators': 1000, 'subsample': 0.5098301503010225, 'colsample_bytree': 0.8691790199297258, 'min_child_weight': 4, 'gamma': 1.2604384192811897, 'reg_alpha': 9.71122816360578e-05, 'reg_lambda': 3.2652211185710446e-07, 'max_delta_step': 6}. Best is trial 13 with value: 0.5168421052631579.

Best trial: 17. Best value: 0.596842:  36%|███▌      | 18/50 [02:36<05:23, 10.12s/it]

[I 2025-12-02 00:46:33,098] Trial 17 finished with value: 0.5968421052631578 and parameters: {'max_depth': 3, 'learning_rate': 0.28347197809443264, 'n_estimators': 973, 'subsample': 0.5120687096695142, 'colsample_bytree': 0.9013418396613325, 'min_child_weight': 1, 'gamma': 1.4755123946272066, 'reg_alpha': 3.232883891994014e-05, 'reg_lambda': 1.6902753433203686e-07, 'max_delta_step': 10}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  38%|███▊      | 19/50 [02:40<04:22,  8.46s/it]

[I 2025-12-02 00:46:37,711] Trial 19 finished with value: 0.5505263157894738 and parameters: {'max_depth': 4, 'learning_rate': 0.138593637622306, 'n_estimators': 940, 'subsample': 0.5000677678239831, 'colsample_bytree': 0.8837486242727346, 'min_child_weight': 1, 'gamma': 1.2744034997100149, 'reg_alpha': 0.0001168258489057049, 'reg_lambda': 4.326337553161495e-08, 'max_delta_step': 6}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  40%|████      | 20/50 [02:41<03:06,  6.22s/it]

[I 2025-12-02 00:46:38,696] Trial 18 finished with value: 0.41789473684210526 and parameters: {'max_depth': 3, 'learning_rate': 0.27799556852941343, 'n_estimators': 987, 'subsample': 0.6357018733680138, 'colsample_bytree': 0.9719195607734635, 'min_child_weight': 1, 'gamma': 1.3344059564224948, 'reg_alpha': 3.890699524958003e-05, 'reg_lambda': 1.990008935025753e-08, 'max_delta_step': 10}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  42%|████▏     | 21/50 [03:09<06:04, 12.57s/it]

[I 2025-12-02 00:47:06,062] Trial 22 finished with value: 0.48947368421052634 and parameters: {'max_depth': 4, 'learning_rate': 0.13452165288852636, 'n_estimators': 899, 'subsample': 0.5983600623726982, 'colsample_bytree': 0.9047966659496056, 'min_child_weight': 3, 'gamma': 1.3412679685959281, 'reg_alpha': 2.1949117870025136e-06, 'reg_lambda': 2.781892855683382e-06, 'max_delta_step': 4}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  44%|████▍     | 22/50 [03:16<05:08, 11.01s/it]

[I 2025-12-02 00:47:13,439] Trial 21 finished with value: 0.49684210526315786 and parameters: {'max_depth': 4, 'learning_rate': 0.12859785774928076, 'n_estimators': 1279, 'subsample': 0.5923177199319041, 'colsample_bytree': 0.9061267698583609, 'min_child_weight': 2, 'gamma': 1.3726719340718576, 'reg_alpha': 2.3937073044630736e-06, 'reg_lambda': 3.0629866976322123e-06, 'max_delta_step': 5}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  46%|████▌     | 23/50 [03:18<03:41,  8.20s/it]

[I 2025-12-02 00:47:15,102] Trial 20 finished with value: 0.4842105263157894 and parameters: {'max_depth': 4, 'learning_rate': 0.12535230905408273, 'n_estimators': 1288, 'subsample': 0.6297146708595585, 'colsample_bytree': 0.9250120921341736, 'min_child_weight': 1, 'gamma': 4.871254507183591, 'reg_alpha': 8.98621887774279e-06, 'reg_lambda': 6.551603098620042e-06, 'max_delta_step': 5}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  48%|████▊     | 24/50 [03:23<03:08,  7.24s/it]

[I 2025-12-02 00:47:20,080] Trial 23 finished with value: 0.4905263157894737 and parameters: {'max_depth': 4, 'learning_rate': 0.1052471043630801, 'n_estimators': 1291, 'subsample': 0.5872191402747443, 'colsample_bytree': 0.9110237612223623, 'min_child_weight': 2, 'gamma': 1.015087712335285, 'reg_alpha': 3.0392159957412167e-06, 'reg_lambda': 9.468877934094047e-06, 'max_delta_step': 5}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  50%|█████     | 25/50 [03:48<05:20, 12.81s/it]

[I 2025-12-02 00:47:45,887] Trial 26 finished with value: 0.5905263157894737 and parameters: {'max_depth': 4, 'learning_rate': 0.17040467027690742, 'n_estimators': 878, 'subsample': 0.5016699899791444, 'colsample_bytree': 0.8434308994158146, 'min_child_weight': 2, 'gamma': 2.573249766852264, 'reg_alpha': 0.0003209464021461158, 'reg_lambda': 2.819988884983173e-07, 'max_delta_step': 6}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  52%|█████▏    | 26/50 [03:52<03:59,  9.96s/it]

[I 2025-12-02 00:47:49,208] Trial 24 finished with value: 0.47789473684210526 and parameters: {'max_depth': 4, 'learning_rate': 0.11608131392907732, 'n_estimators': 1274, 'subsample': 0.5089374971101955, 'colsample_bytree': 0.8026362482410913, 'min_child_weight': 2, 'gamma': 4.952732421475818, 'reg_alpha': 0.0004511291849911426, 'reg_lambda': 2.990105244692109e-07, 'max_delta_step': 6}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  54%|█████▍    | 27/50 [03:53<02:51,  7.43s/it]

[I 2025-12-02 00:47:50,751] Trial 27 finished with value: 0.4842105263157894 and parameters: {'max_depth': 5, 'learning_rate': 0.18406119287796074, 'n_estimators': 887, 'subsample': 0.5242090237276711, 'colsample_bytree': 0.8362868236561248, 'min_child_weight': 2, 'gamma': 1.8337141821754825, 'reg_alpha': 0.00041818815996521225, 'reg_lambda': 3.9591981873600497e-07, 'max_delta_step': 7}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  56%|█████▌    | 28/50 [03:58<02:28,  6.77s/it]

[I 2025-12-02 00:47:55,963] Trial 25 finished with value: 0.4905263157894737 and parameters: {'max_depth': 4, 'learning_rate': 0.10847575615793417, 'n_estimators': 1236, 'subsample': 0.5043794242224398, 'colsample_bytree': 0.8262390944631648, 'min_child_weight': 2, 'gamma': 2.7514562720703992, 'reg_alpha': 0.000431007525046086, 'reg_lambda': 2.1707401818952795e-07, 'max_delta_step': 6}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  58%|█████▊    | 29/50 [03:59<01:41,  4.85s/it]

[I 2025-12-02 00:47:56,327] Trial 29 pruned.

Best trial: 17. Best value: 0.596842:  60%|██████    | 30/50 [04:00<01:14,  3.72s/it]

[I 2025-12-02 00:47:57,399] Trial 30 pruned.

Best trial: 17. Best value: 0.596842:  62%|██████▏   | 31/50 [04:04<01:12,  3.81s/it]

[I 2025-12-02 00:48:01,442] Trial 32 pruned.

Best trial: 17. Best value: 0.596842:  64%|██████▍   | 32/50 [04:05<00:54,  3.03s/it]

[I 2025-12-02 00:48:02,645] Trial 31 pruned.

Best trial: 17. Best value: 0.596842:  66%|██████▌   | 33/50 [04:11<01:05,  3.84s/it]

[I 2025-12-02 00:48:08,364] Trial 28 finished with value: 0.4905263157894737 and parameters: {'max_depth': 5, 'learning_rate': 0.062056706166192376, 'n_estimators': 551, 'subsample': 0.5389038777764052, 'colsample_bytree': 0.8385505989986465, 'min_child_weight': 2, 'gamma': 2.6620433140513553, 'reg_alpha': 0.0006338160412577296, 'reg_lambda': 3.11208098197868e-07, 'max_delta_step': 7}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  68%|██████▊   | 34/50 [04:16<01:08,  4.26s/it]

[I 2025-12-02 00:48:13,627] Trial 35 pruned.

Best trial: 17. Best value: 0.596842:  70%|███████   | 35/50 [04:22<01:12,  4.82s/it]

[I 2025-12-02 00:48:19,737] Trial 33 finished with value: 0.4831578947368421 and parameters: {'max_depth': 10, 'learning_rate': 0.17298309876169127, 'n_estimators': 623, 'subsample': 0.7037684820758059, 'colsample_bytree': 0.7831104948331725, 'min_child_weight': 3, 'gamma': 1.941183977928704, 'reg_alpha': 2.5159297379740865e-07, 'reg_lambda': 4.102643817247569e-05, 'max_delta_step': 9}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  72%|███████▏  | 36/50 [04:24<00:53,  3.82s/it]

[I 2025-12-02 00:48:21,241] Trial 37 pruned.

Best trial: 17. Best value: 0.596842:  74%|███████▍  | 37/50 [04:43<01:51,  8.60s/it]

[I 2025-12-02 00:48:40,973] Trial 34 finished with value: 0.5631578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.2086307424474233, 'n_estimators': 1164, 'subsample': 0.5031022598489645, 'colsample_bytree': 0.8730102108637643, 'min_child_weight': 1, 'gamma': 3.37334359896801, 'reg_alpha': 0.00010409205810845527, 'reg_lambda': 8.742976259844907e-08, 'max_delta_step': 6}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  76%|███████▌  | 38/50 [04:48<01:28,  7.36s/it]

[I 2025-12-02 00:48:45,434] Trial 36 finished with value: 0.4442105263157895 and parameters: {'max_depth': 3, 'learning_rate': 0.16156735499275746, 'n_estimators': 1122, 'subsample': 0.5662224376987701, 'colsample_bytree': 0.9513367380925621, 'min_child_weight': 1, 'gamma': 2.1323657197844965, 'reg_alpha': 1.0512105842916143e-05, 'reg_lambda': 4.63140827661837e-08, 'max_delta_step': 4}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  78%|███████▊  | 39/50 [04:49<01:01,  5.59s/it]

[I 2025-12-02 00:48:46,903] Trial 40 pruned.

Best trial: 17. Best value: 0.596842:  80%|████████  | 40/50 [04:54<00:51,  5.17s/it]

[I 2025-12-02 00:48:51,091] Trial 41 pruned.

Best trial: 17. Best value: 0.596842:  82%|████████▏ | 41/50 [04:58<00:45,  5.04s/it]

[I 2025-12-02 00:48:55,815] Trial 38 finished with value: 0.5568421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.21547429283310895, 'n_estimators': 960, 'subsample': 0.7753765119278925, 'colsample_bytree': 0.9480913776414412, 'min_child_weight': 1, 'gamma': 2.2021828534131687, 'reg_alpha': 0.014603749017906302, 'reg_lambda': 5.066827526585402e-08, 'max_delta_step': 6}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  84%|████████▍ | 42/50 [05:02<00:38,  4.77s/it]

[I 2025-12-02 00:48:59,966] Trial 39 finished with value: 0.39789473684210525 and parameters: {'max_depth': 3, 'learning_rate': 0.2255801227302624, 'n_estimators': 1160, 'subsample': 0.6127693323143361, 'colsample_bytree': 0.7204869139563665, 'min_child_weight': 1, 'gamma': 3.2892021457100697, 'reg_alpha': 0.007154573813914651, 'reg_lambda': 4.499953190251415e-08, 'max_delta_step': 8}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  86%|████████▌ | 43/50 [05:25<01:10, 10.05s/it]

[I 2025-12-02 00:49:22,319] Trial 42 pruned.

Best trial: 17. Best value: 0.596842:  88%|████████▊ | 44/50 [05:33<00:57,  9.51s/it]

[I 2025-12-02 00:49:30,568] Trial 44 finished with value: 0.5042105263157894 and parameters: {'max_depth': 3, 'learning_rate': 0.14851132840199555, 'n_estimators': 940, 'subsample': 0.8371160443309554, 'colsample_bytree': 0.9234544167462512, 'min_child_weight': 2, 'gamma': 2.3952908863842173, 'reg_alpha': 0.00014768881649113226, 'reg_lambda': 7.562856588131628e-08, 'max_delta_step': 8}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  90%|█████████ | 45/50 [05:35<00:36,  7.20s/it]

[I 2025-12-02 00:49:32,403] Trial 45 finished with value: 0.523157894736842 and parameters: {'max_depth': 3, 'learning_rate': 0.14261645597899233, 'n_estimators': 944, 'subsample': 0.8637497606515512, 'colsample_bytree': 0.8908839872985412, 'min_child_weight': 3, 'gamma': 2.331334787364763, 'reg_alpha': 0.042878291736483214, 'reg_lambda': 8.774758642142412e-08, 'max_delta_step': 5}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  92%|█████████▏| 46/50 [05:39<00:25,  6.33s/it]

[I 2025-12-02 00:49:36,689] Trial 43 finished with value: 0.5094736842105263 and parameters: {'max_depth': 3, 'learning_rate': 0.14475829788348443, 'n_estimators': 1413, 'subsample': 0.6148224288565305, 'colsample_bytree': 0.6896777789906707, 'min_child_weight': 3, 'gamma': 3.1150108576105717, 'reg_alpha': 0.026264830336213834, 'reg_lambda': 6.989946727686178e-08, 'max_delta_step': 8}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  94%|█████████▍| 47/50 [06:00<00:32, 10.72s/it]

[I 2025-12-02 00:49:57,646] Trial 47 finished with value: 0.5768421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.08869945557514707, 'n_estimators': 802, 'subsample': 0.7772018159693705, 'colsample_bytree': 0.8617409867281587, 'min_child_weight': 3, 'gamma': 1.5605198528772029, 'reg_alpha': 0.04177530735151201, 'reg_lambda': 7.583148327200745e-07, 'max_delta_step': 3}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  96%|█████████▌| 48/50 [06:05<00:18,  9.09s/it]

[I 2025-12-02 00:50:02,944] Trial 49 finished with value: 0.4842105263157894 and parameters: {'max_depth': 6, 'learning_rate': 0.08425979831830088, 'n_estimators': 797, 'subsample': 0.7911011219114729, 'colsample_bytree': 0.5053302841834915, 'min_child_weight': 1, 'gamma': 1.627029605406058, 'reg_alpha': 1.9178070411937215e-05, 'reg_lambda': 0.0023688452205799207, 'max_delta_step': 3}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842:  98%|█████████▊| 49/50 [06:07<00:06,  6.84s/it]

[I 2025-12-02 00:50:04,496] Trial 46 finished with value: 0.5305263157894737 and parameters: {'max_depth': 3, 'learning_rate': 0.08867442817243372, 'n_estimators': 1377, 'subsample': 0.8381393079256132, 'colsample_bytree': 0.9300570906791422, 'min_child_weight': 3, 'gamma': 2.4449347105564128, 'reg_alpha': 0.03519336449456336, 'reg_lambda': 1.2046748610569063e-08, 'max_delta_step': 3}. Best is trial 17 with value: 0.5968421052631578.

Best trial: 17. Best value: 0.596842: 100%|██████████| 50/50 [06:17<00:00,  7.56s/it]

[I 2025-12-02 00:50:14,780] Trial 48 finished with value: 0.45789473684210524 and parameters: {'max_depth': 4, 'learning_rate': 0.07923197902973007, 'n_estimators': 1371, 'subsample': 0.7573650683348753, 'colsample_bytree': 0.8503031890530751, 'min_child_weight': 1, 'gamma': 1.6182791423576266, 'reg_alpha': 0.03827320188846974, 'reg_lambda': 1.260001450941177e-08, 'max_delta_step': 3}. Best is trial 17 with value: 0.5968421052631578.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 00:50:18,930] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 43, Test size: 11
Using Leave-One-Out CV with 43 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.466009:   2%|▏         | 1/50 [00:13<10:42, 13.10s/it]

[I 2025-12-02 00:50:32,026] Trial 0 finished with value: 0.46600877192982454 and parameters: {'max_depth': 5, 'learning_rate': 0.15798968751754147, 'n_estimators': 368, 'subsample': 0.782235957058374, 'colsample_bytree': 0.8849082081239523, 'min_child_weight': 3, 'gamma': 2.3949264655530103, 'reg_alpha': 1.2827761890753921e-05, 'reg_lambda': 1.4764539097772232e-06, 'max_delta_step': 9}. Best is trial 0 with value: 0.46600877192982454.

Best trial: 0. Best value: 0.466009:   4%|▍         | 2/50 [00:17<06:33,  8.20s/it]

[I 2025-12-02 00:50:36,797] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.028206146548905298, 'n_estimators': 574, 'subsample': 0.7901927219885145, 'colsample_bytree': 0.6123505495328638, 'min_child_weight': 9, 'gamma': 2.7530256094313303, 'reg_alpha': 0.007421181503250676, 'reg_lambda': 7.29199262883376e-08, 'max_delta_step': 0}. Best is trial 0 with value: 0.46600877192982454.

Best trial: 0. Best value: 0.466009:   6%|▌         | 3/50 [00:22<05:02,  6.43s/it]

[I 2025-12-02 00:50:41,109] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.03395583721159012, 'n_estimators': 677, 'subsample': 0.6918387958301001, 'colsample_bytree': 0.8390292730959926, 'min_child_weight': 5, 'gamma': 2.489738680071098, 'reg_alpha': 3.308253771054837e-07, 'reg_lambda': 3.4229432039283655e-06, 'max_delta_step': 2}. Best is trial 0 with value: 0.46600877192982454.

Best trial: 5. Best value: 0.513158:   8%|▊         | 4/50 [00:33<06:21,  8.29s/it]

[I 2025-12-02 00:50:52,272] Trial 5 finished with value: 0.513157894736842 and parameters: {'max_depth': 10, 'learning_rate': 0.17635924596002484, 'n_estimators': 392, 'subsample': 0.9644612078941917, 'colsample_bytree': 0.5132880134604072, 'min_child_weight': 1, 'gamma': 1.5336105273652105, 'reg_alpha': 0.007466994017137697, 'reg_lambda': 0.47534107946639376, 'max_delta_step': 3}. Best is trial 5 with value: 0.513157894736842.

Best trial: 2. Best value: 0.554825:  10%|█         | 5/50 [00:47<07:47, 10.40s/it]

[I 2025-12-02 00:51:06,395] Trial 2 finished with value: 0.5548245614035088 and parameters: {'max_depth': 7, 'learning_rate': 0.12534632330272152, 'n_estimators': 1183, 'subsample': 0.7993663554821311, 'colsample_bytree': 0.781530326538448, 'min_child_weight': 1, 'gamma': 2.439554895415194, 'reg_alpha': 0.016002716201580353, 'reg_lambda': 1.8019785243938838e-06, 'max_delta_step': 6}. Best is trial 2 with value: 0.5548245614035088.

Best trial: 2. Best value: 0.554825:  14%|█▍        | 7/50 [00:52<04:09,  5.80s/it]

[I 2025-12-02 00:51:11,363] Trial 6 finished with value: 0.041666666666666664 and parameters: {'max_depth': 3, 'learning_rate': 0.16054865310753647, 'n_estimators': 964, 'subsample': 0.6150980510961129, 'colsample_bytree': 0.7727464010641065, 'min_child_weight': 7, 'gamma': 4.4263239731579365, 'reg_alpha': 0.0014402129997393872, 'reg_lambda': 2.337383425445276e-07, 'max_delta_step': 1}. Best is trial 2 with value: 0.5548245614035088.
[I 2025-12-02 00:51:11,492] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.20912832592440855, 'n_estimators': 1255, 'subsample': 0.7348592049930287, 'colsample_bytree': 0.8333410059749297, 'min_child_weight': 10, 'gamma': 2.168732790657075, 'reg_alpha': 0.0009019514802846647, 'reg_lambda': 0.0004326099931336371, 'max_delta_step': 5}. Best is trial 2 with value: 0.5548245614035088.

Best trial: 2. Best value: 0.554825:  16%|█▌        | 8/50 [01:06<05:56,  8.49s/it]

[I 2025-12-02 00:51:25,739] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.025948127311882594, 'n_estimators': 536, 'subsample': 0.8638731766187613, 'colsample_bytree': 0.8914542078932657, 'min_child_weight': 8, 'gamma': 4.438688306434426, 'reg_alpha': 0.00191641921569191, 'reg_lambda': 1.9838836835727718e-08, 'max_delta_step': 3}. Best is trial 2 with value: 0.5548245614035088.

Best trial: 2. Best value: 0.554825:  18%|█▊        | 9/50 [01:08<04:27,  6.51s/it]

[I 2025-12-02 00:51:27,910] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.0639871193053427, 'n_estimators': 1135, 'subsample': 0.5256403734281174, 'colsample_bytree': 0.582177680894816, 'min_child_weight': 9, 'gamma': 2.9628325798407005, 'reg_alpha': 0.003919753616159105, 'reg_lambda': 0.023069366134157124, 'max_delta_step': 5}. Best is trial 2 with value: 0.5548245614035088.

Best trial: 2. Best value: 0.554825:  20%|██        | 10/50 [01:21<05:31,  8.30s/it]

[I 2025-12-02 00:51:40,208] Trial 10 finished with value: 0.041666666666666664 and parameters: {'max_depth': 7, 'learning_rate': 0.015969479070058527, 'n_estimators': 898, 'subsample': 0.603704254262118, 'colsample_bytree': 0.6213707364101326, 'min_child_weight': 6, 'gamma': 3.0051293550361975, 'reg_alpha': 0.0009461619466002181, 'reg_lambda': 3.7375988028021996e-07, 'max_delta_step': 3}. Best is trial 2 with value: 0.5548245614035088.

Best trial: 2. Best value: 0.554825:  22%|██▏       | 11/50 [01:23<04:09,  6.39s/it]

[I 2025-12-02 00:51:42,264] Trial 12 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.013845687418655401, 'n_estimators': 448, 'subsample': 0.7909106632754506, 'colsample_bytree': 0.6863667501121432, 'min_child_weight': 9, 'gamma': 4.083522386882349, 'reg_alpha': 0.00016566936830671265, 'reg_lambda': 0.0003233592733624666, 'max_delta_step': 5}. Best is trial 2 with value: 0.5548245614035088.

Best trial: 2. Best value: 0.554825:  24%|██▍       | 12/50 [01:35<05:06,  8.07s/it]

[I 2025-12-02 00:51:54,183] Trial 11 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.026346123583795015, 'n_estimators': 911, 'subsample': 0.6967760761597525, 'colsample_bytree': 0.8453778175904036, 'min_child_weight': 9, 'gamma': 4.891707566252651, 'reg_alpha': 9.842644852267022e-08, 'reg_lambda': 5.440794609244533e-06, 'max_delta_step': 0}. Best is trial 2 with value: 0.5548245614035088.

Best trial: 2. Best value: 0.554825:  26%|██▌       | 13/50 [01:36<03:38,  5.90s/it]

[I 2025-12-02 00:51:55,092] Trial 9 finished with value: 0.4133771929824561 and parameters: {'max_depth': 10, 'learning_rate': 0.18737110754429598, 'n_estimators': 1304, 'subsample': 0.5882499461755536, 'colsample_bytree': 0.9800028029981172, 'min_child_weight': 2, 'gamma': 1.9488242101187825, 'reg_alpha': 0.0438432172391861, 'reg_lambda': 0.8235542119643697, 'max_delta_step': 2}. Best is trial 2 with value: 0.5548245614035088.

Best trial: 2. Best value: 0.554825:  28%|██▊       | 14/50 [01:43<03:42,  6.19s/it]

[I 2025-12-02 00:52:01,960] Trial 16 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.09102337306086013, 'n_estimators': 203, 'subsample': 0.9954785415046179, 'colsample_bytree': 0.5309796855099003, 'min_child_weight': 1, 'gamma': 0.6558843760788098, 'reg_alpha': 5.963482600505035, 'reg_lambda': 8.579349195113656, 'max_delta_step': 8}. Best is trial 2 with value: 0.5548245614035088.

Best trial: 14. Best value: 0.560307:  30%|███       | 15/50 [02:11<07:36, 13.04s/it]

[I 2025-12-02 00:52:30,878] Trial 14 finished with value: 0.5603070175438596 and parameters: {'max_depth': 7, 'learning_rate': 0.0830085332537386, 'n_estimators': 1496, 'subsample': 0.9969563198119779, 'colsample_bytree': 0.5027255875293736, 'min_child_weight': 1, 'gamma': 0.6116152168858433, 'reg_alpha': 2.062014441316308, 'reg_lambda': 7.153960762125108, 'max_delta_step': 8}. Best is trial 14 with value: 0.5603070175438596.

Best trial: 14. Best value: 0.560307:  32%|███▏      | 16/50 [02:18<06:20, 11.19s/it]

[I 2025-12-02 00:52:37,779] Trial 13 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.08236769708892393, 'n_estimators': 1443, 'subsample': 0.9999115899055533, 'colsample_bytree': 0.9705611582727476, 'min_child_weight': 1, 'gamma': 0.7630004193749935, 'reg_alpha': 7.386373750608828, 'reg_lambda': 9.410092457513281e-05, 'max_delta_step': 9}. Best is trial 14 with value: 0.5603070175438596.

Best trial: 14. Best value: 0.560307:  34%|███▍      | 17/50 [02:22<04:57,  9.02s/it]

[I 2025-12-02 00:52:41,745] Trial 17 finished with value: 0.3925438596491228 and parameters: {'max_depth': 6, 'learning_rate': 0.09859616387034958, 'n_estimators': 1445, 'subsample': 0.9776671136338776, 'colsample_bytree': 0.7222224877784946, 'min_child_weight': 4, 'gamma': 1.1645601815875806, 'reg_alpha': 0.2434946376561634, 'reg_lambda': 0.00955805632300314, 'max_delta_step': 7}. Best is trial 14 with value: 0.5603070175438596.

Best trial: 15. Best value: 0.628289:  36%|███▌      | 18/50 [02:24<03:40,  6.90s/it]

[I 2025-12-02 00:52:43,695] Trial 15 finished with value: 0.6282894736842105 and parameters: {'max_depth': 8, 'learning_rate': 0.08692067150466912, 'n_estimators': 1433, 'subsample': 0.993042836409495, 'colsample_bytree': 0.5125666966265678, 'min_child_weight': 1, 'gamma': 0.4335266668211699, 'reg_alpha': 0.5416865582823583, 'reg_lambda': 8.916021482401604, 'max_delta_step': 8}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  38%|███▊      | 19/50 [02:58<07:42, 14.91s/it]

[I 2025-12-02 00:53:17,278] Trial 20 finished with value: 0.38706140350877194 and parameters: {'max_depth': 5, 'learning_rate': 0.29744802655786745, 'n_estimators': 1100, 'subsample': 0.8927931242892267, 'colsample_bytree': 0.6831049240005757, 'min_child_weight': 3, 'gamma': 0.12410287793687091, 'reg_alpha': 0.3038598466019089, 'reg_lambda': 2.961159784434566e-05, 'max_delta_step': 7}. Best is trial 15 with value: 0.6282894736842105.
[I 2025-12-02 00:53:17,290] Trial 18 finished with value: 0.3399122807017544 and parameters: {'max_depth': 6, 'learning_rate': 0.09307922652440848, 'n_estimators': 1430, 'subsample': 0.8825577633252657, 'colsample_bytree': 0.715417602908718, 'min_child_weight': 4, 'gamma': 0.2607542186743741, 'reg_alpha': 1.2986361064264924, 'reg_lambda': 2.9342447648119447e-05, 'max_delta_step': 7}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  42%|████▏     | 21/50 [03:05<04:43,  9.76s/it]

[I 2025-12-02 00:53:24,789] Trial 19 finished with value: 0.3399122807017544 and parameters: {'max_depth': 6, 'learning_rate': 0.11397737269908725, 'n_estimators': 1483, 'subsample': 0.8920612106199629, 'colsample_bytree': 0.7004780247639895, 'min_child_weight': 4, 'gamma': 0.014060799326153894, 'reg_alpha': 0.27143633972417086, 'reg_lambda': 0.009428267565609782, 'max_delta_step': 7}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  44%|████▍     | 22/50 [03:06<03:27,  7.40s/it]

[I 2025-12-02 00:53:25,055] Trial 21 finished with value: 0.38706140350877194 and parameters: {'max_depth': 8, 'learning_rate': 0.0497571447301643, 'n_estimators': 1069, 'subsample': 0.9156524397487035, 'colsample_bytree': 0.5620196468531177, 'min_child_weight': 3, 'gamma': 0.002690624810981035, 'reg_alpha': 0.4512391074859331, 'reg_lambda': 7.4357887697593235, 'max_delta_step': 10}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  46%|████▌     | 23/50 [03:40<06:30, 14.46s/it]

[I 2025-12-02 00:53:59,430] Trial 22 finished with value: 0.3607456140350877 and parameters: {'max_depth': 8, 'learning_rate': 0.04812794501251505, 'n_estimators': 1317, 'subsample': 0.9194898694775233, 'colsample_bytree': 0.5522839227220124, 'min_child_weight': 3, 'gamma': 1.435136663129705, 'reg_alpha': 2.921360728368703e-05, 'reg_lambda': 7.026303821952356, 'max_delta_step': 10}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  48%|████▊     | 24/50 [03:45<05:10, 11.96s/it]

[I 2025-12-02 00:54:04,702] Trial 23 finished with value: 0.35526315789473684 and parameters: {'max_depth': 8, 'learning_rate': 0.054650680490934384, 'n_estimators': 1495, 'subsample': 0.9291263988031848, 'colsample_bytree': 0.5699819303199142, 'min_child_weight': 3, 'gamma': 1.4071410397315143, 'reg_alpha': 5.424376031711248e-05, 'reg_lambda': 4.9808479951598725, 'max_delta_step': 10}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  50%|█████     | 25/50 [03:48<03:56,  9.45s/it]

[I 2025-12-02 00:54:07,694] Trial 25 finished with value: 0.5339912280701754 and parameters: {'max_depth': 8, 'learning_rate': 0.05423948981990636, 'n_estimators': 1250, 'subsample': 0.9393880374655241, 'colsample_bytree': 0.7731461650030326, 'min_child_weight': 2, 'gamma': 1.3838370739767505, 'reg_alpha': 0.04245207792441979, 'reg_lambda': 0.24615027713500368, 'max_delta_step': 6}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  52%|█████▏    | 26/50 [03:49<02:49,  7.04s/it]

[I 2025-12-02 00:54:08,721] Trial 24 finished with value: 0.513157894736842 and parameters: {'max_depth': 8, 'learning_rate': 0.05933700106511536, 'n_estimators': 1281, 'subsample': 0.9187566622601374, 'colsample_bytree': 0.5593737864312296, 'min_child_weight': 2, 'gamma': 3.412797410541751, 'reg_alpha': 0.04095923205626279, 'reg_lambda': 6.350299993970437, 'max_delta_step': 10}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  54%|█████▍    | 27/50 [04:13<04:33, 11.91s/it]

[I 2025-12-02 00:54:32,555] Trial 28 finished with value: 0.4342105263157895 and parameters: {'max_depth': 7, 'learning_rate': 0.12457130867804161, 'n_estimators': 778, 'subsample': 0.8324886882644704, 'colsample_bytree': 0.6390000875501889, 'min_child_weight': 2, 'gamma': 0.6606913469090343, 'reg_alpha': 0.049341666253535005, 'reg_lambda': 0.055250372186146875, 'max_delta_step': 8}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  56%|█████▌    | 28/50 [04:18<03:33,  9.71s/it]

[I 2025-12-02 00:54:36,950] Trial 29 finished with value: 0.5701754385964912 and parameters: {'max_depth': 7, 'learning_rate': 0.12484390372255065, 'n_estimators': 770, 'subsample': 0.8389085002761579, 'colsample_bytree': 0.5023455999439846, 'min_child_weight': 1, 'gamma': 0.8748154605601253, 'reg_alpha': 2.566728425624437, 'reg_lambda': 0.07434999922515109, 'max_delta_step': 8}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  58%|█████▊    | 29/50 [04:20<02:38,  7.56s/it]

[I 2025-12-02 00:54:39,365] Trial 26 finished with value: 0.5021929824561404 and parameters: {'max_depth': 8, 'learning_rate': 0.06328117297784171, 'n_estimators': 1220, 'subsample': 0.8290339501474755, 'colsample_bytree': 0.5022227324716496, 'min_child_weight': 2, 'gamma': 3.5278842665341337, 'reg_alpha': 0.06462776971881876, 'reg_lambda': 0.20294717936805876, 'max_delta_step': 6}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  60%|██████    | 30/50 [04:24<02:11,  6.59s/it]

[I 2025-12-02 00:54:43,646] Trial 27 finished with value: 0.4967105263157895 and parameters: {'max_depth': 7, 'learning_rate': 0.1277669921185928, 'n_estimators': 1217, 'subsample': 0.8274183638792368, 'colsample_bytree': 0.7777673545482621, 'min_child_weight': 2, 'gamma': 0.7233029710356309, 'reg_alpha': 0.02655801375085228, 'reg_lambda': 0.2646443244648525, 'max_delta_step': 6}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  62%|██████▏   | 31/50 [04:32<02:09,  6.80s/it]

[I 2025-12-02 00:54:50,955] Trial 33 pruned.

Best trial: 15. Best value: 0.628289:  64%|██████▍   | 32/50 [04:44<02:35,  8.63s/it]

[I 2025-12-02 00:55:03,876] Trial 32 finished with value: 0.5285087719298246 and parameters: {'max_depth': 5, 'learning_rate': 0.25263066945874224, 'n_estimators': 711, 'subsample': 0.9583401612213961, 'colsample_bytree': 0.600501280073916, 'min_child_weight': 1, 'gamma': 1.0509585226606832, 'reg_alpha': 1.7993395720590768, 'reg_lambda': 0.0017253013832667539, 'max_delta_step': 9}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  66%|██████▌   | 33/50 [04:46<01:50,  6.48s/it]

[I 2025-12-02 00:55:05,332] Trial 31 finished with value: 0.48684210526315785 and parameters: {'max_depth': 5, 'learning_rate': 0.0706343374042042, 'n_estimators': 790, 'subsample': 0.9614309166339974, 'colsample_bytree': 0.5050788719252234, 'min_child_weight': 1, 'gamma': 0.9074452082764337, 'reg_alpha': 1.9335702042212186, 'reg_lambda': 0.0021645776315167803, 'max_delta_step': 8}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  68%|██████▊   | 34/50 [04:56<02:01,  7.59s/it]

[I 2025-12-02 00:55:15,502] Trial 36 pruned.

Best trial: 15. Best value: 0.628289:  70%|███████   | 35/50 [04:57<01:25,  5.70s/it]

[I 2025-12-02 00:55:16,791] Trial 34 finished with value: 0.5548245614035088 and parameters: {'max_depth': 7, 'learning_rate': 0.1414950889843354, 'n_estimators': 783, 'subsample': 0.757484159362292, 'colsample_bytree': 0.5028574460484195, 'min_child_weight': 1, 'gamma': 1.8059418336459392, 'reg_alpha': 1.156089251356148, 'reg_lambda': 0.0024884305148350576, 'max_delta_step': 8}. Best is trial 15 with value: 0.6282894736842105.
[I 2025-12-02 00:55:16,823] Trial 30 finished with value: 0.5285087719298246 and parameters: {'max_depth': 5, 'learning_rate': 0.07558566000475772, 'n_estimators': 1354, 'subsample': 0.8440093672659299, 'colsample_bytree': 0.5092942558758247, 'min_child_weight': 1, 'gamma': 1.838927462981135, 'reg_alpha': 2.1280255922956526, 'reg_lambda': 0.0014916688092143377, 'max_delta_step': 6}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  74%|███████▍  | 37/50 [05:06<01:06,  5.09s/it]

[I 2025-12-02 00:55:25,549] Trial 39 pruned.

Best trial: 15. Best value: 0.628289:  76%|███████▌  | 38/50 [05:11<00:59,  4.95s/it]

[I 2025-12-02 00:55:30,090] Trial 40 pruned.

Best trial: 15. Best value: 0.628289:  78%|███████▊  | 39/50 [05:18<01:01,  5.55s/it]

[I 2025-12-02 00:55:37,330] Trial 41 pruned.

Best trial: 15. Best value: 0.628289:  80%|████████  | 40/50 [05:32<01:18,  7.81s/it]

[I 2025-12-02 00:55:51,169] Trial 35 finished with value: 0.5964912280701754 and parameters: {'max_depth': 6, 'learning_rate': 0.07714255120440601, 'n_estimators': 1363, 'subsample': 0.7664007797309328, 'colsample_bytree': 0.5003421886304479, 'min_child_weight': 1, 'gamma': 1.935075251176573, 'reg_alpha': 1.0389255370472863e-08, 'reg_lambda': 1.753243930878454, 'max_delta_step': 8}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  82%|████████▏ | 41/50 [05:42<01:17,  8.57s/it]

[I 2025-12-02 00:56:01,709] Trial 43 pruned.

Best trial: 15. Best value: 0.628289:  84%|████████▍ | 42/50 [05:43<00:50,  6.36s/it]

[I 2025-12-02 00:56:02,529] Trial 37 finished with value: 0.5493421052631579 and parameters: {'max_depth': 9, 'learning_rate': 0.0408203224747658, 'n_estimators': 1366, 'subsample': 0.7162369103037008, 'colsample_bytree': 0.5394202107966756, 'min_child_weight': 1, 'gamma': 1.7334971491629654, 'reg_alpha': 1.2811030669411559e-06, 'reg_lambda': 0.0752743523479773, 'max_delta_step': 4}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  86%|████████▌ | 43/50 [05:45<00:35,  5.10s/it]

[I 2025-12-02 00:56:04,560] Trial 38 finished with value: 0.4133771929824561 and parameters: {'max_depth': 9, 'learning_rate': 0.04200808954604563, 'n_estimators': 1378, 'subsample': 0.7083883299880136, 'colsample_bytree': 0.8287173409382327, 'min_child_weight': 2, 'gamma': 0.45707259265418176, 'reg_alpha': 0.010332371454695751, 'reg_lambda': 1.8648519603915168, 'max_delta_step': 4}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  88%|████████▊ | 44/50 [05:59<00:45,  7.64s/it]

[I 2025-12-02 00:56:18,340] Trial 42 finished with value: 0.3717105263157895 and parameters: {'max_depth': 4, 'learning_rate': 0.07872509837598306, 'n_estimators': 1391, 'subsample': 0.725124232614167, 'colsample_bytree': 0.591859956372642, 'min_child_weight': 2, 'gamma': 0.43939767685007936, 'reg_alpha': 0.011185495489824128, 'reg_lambda': 0.049395419755554885, 'max_delta_step': 5}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  90%|█████████ | 45/50 [06:23<01:02, 12.44s/it]

[I 2025-12-02 00:56:42,236] Trial 46 finished with value: 0.5339912280701754 and parameters: {'max_depth': 6, 'learning_rate': 0.03335161094673398, 'n_estimators': 1172, 'subsample': 0.7342203064343233, 'colsample_bytree': 0.7480552200768082, 'min_child_weight': 1, 'gamma': 2.783677158257829, 'reg_alpha': 1.7252693933765446e-08, 'reg_lambda': 0.48264918326908973, 'max_delta_step': 8}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  92%|█████████▏| 46/50 [06:24<00:35,  8.96s/it]

[I 2025-12-02 00:56:42,944] Trial 44 finished with value: 0.5230263157894737 and parameters: {'max_depth': 6, 'learning_rate': 0.11031765453478104, 'n_estimators': 1407, 'subsample': 0.723245681409508, 'colsample_bytree': 0.5435627236470408, 'min_child_weight': 1, 'gamma': 2.7693402799487155, 'reg_alpha': 1.3570105321301814e-08, 'reg_lambda': 2.594626639765928, 'max_delta_step': 8}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  94%|█████████▍| 47/50 [06:32<00:26,  8.86s/it]

[I 2025-12-02 00:56:51,567] Trial 45 finished with value: 0.5021929824561404 and parameters: {'max_depth': 6, 'learning_rate': 0.03389584626999672, 'n_estimators': 1499, 'subsample': 0.8066610693602588, 'colsample_bytree': 0.748933510563349, 'min_child_weight': 1, 'gamma': 2.750821899874327, 'reg_alpha': 3.975210061246988e-08, 'reg_lambda': 2.712558558254765, 'max_delta_step': 8}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  96%|█████████▌| 48/50 [06:42<00:18,  9.14s/it]

[I 2025-12-02 00:57:01,370] Trial 47 finished with value: 0.5548245614035088 and parameters: {'max_depth': 6, 'learning_rate': 0.10462427867442928, 'n_estimators': 1500, 'subsample': 0.8020935896524011, 'colsample_bytree': 0.7471201770046764, 'min_child_weight': 1, 'gamma': 2.818384424804736, 'reg_alpha': 5.875064859191351e-06, 'reg_lambda': 0.5774334496849902, 'max_delta_step': 8}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289:  98%|█████████▊| 49/50 [06:47<00:07,  7.79s/it]

[I 2025-12-02 00:57:06,003] Trial 49 finished with value: 0.5603070175438596 and parameters: {'max_depth': 7, 'learning_rate': 0.19312450380599386, 'n_estimators': 873, 'subsample': 0.776613398170849, 'colsample_bytree': 0.9372488321350085, 'min_child_weight': 1, 'gamma': 2.2017666331469963, 'reg_alpha': 0.0027969996308278146, 'reg_lambda': 5.626120600515312e-07, 'max_delta_step': 7}. Best is trial 15 with value: 0.6282894736842105.

Best trial: 15. Best value: 0.628289: 100%|██████████| 50/50 [06:54<00:00,  8.28s/it]

[I 2025-12-02 00:57:13,061] Trial 48 finished with value: 0.5339912280701754 and parameters: {'max_depth': 7, 'learning_rate': 0.11120163617085153, 'n_estimators': 1306, 'subsample': 0.7730564318259688, 'colsample_bytree': 0.7962296252640053, 'min_child_weight': 1, 'gamma': 2.068160319843259, 'reg_alpha': 0.0005144213433631849, 'reg_lambda': 6.811547455556614e-07, 'max_delta_step': 7}. Best is trial 15 with value: 0.6282894736842105.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 00:57:19,408] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 45, Test size: 12
Using Leave-One-Out CV with 45 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0:   2%|▏         | 1/50 [00:13<11:01, 13.51s/it]

[I 2025-12-02 00:57:32,909] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.05807108280350026, 'n_estimators': 385, 'subsample': 0.6841617432024587, 'colsample_bytree': 0.7409284543114121, 'min_child_weight': 9, 'gamma': 0.6744079925456531, 'reg_alpha': 0.0403936885282295, 'reg_lambda': 2.0515465576098368e-05, 'max_delta_step': 3}. Best is trial 1 with value: 0.0.

Best trial: 3. Best value: 0.0384615:   4%|▍         | 2/50 [00:27<11:15, 14.07s/it]

[I 2025-12-02 00:57:47,374] Trial 3 finished with value: 0.038461538461538464 and parameters: {'max_depth': 6, 'learning_rate': 0.20130400755744843, 'n_estimators': 829, 'subsample': 0.6693221355461907, 'colsample_bytree': 0.8805307082887734, 'min_child_weight': 7, 'gamma': 0.19120609491160456, 'reg_alpha': 1.9496488315604416e-06, 'reg_lambda': 3.3555200849105603e-06, 'max_delta_step': 2}. Best is trial 3 with value: 0.038461538461538464.

Best trial: 0. Best value: 0.453441:   6%|▌         | 3/50 [00:29<06:21,  8.13s/it]

[I 2025-12-02 00:57:48,429] Trial 0 finished with value: 0.45344129554655865 and parameters: {'max_depth': 10, 'learning_rate': 0.07685025526588304, 'n_estimators': 644, 'subsample': 0.5016050998745809, 'colsample_bytree': 0.7971054937449913, 'min_child_weight': 1, 'gamma': 2.6484192114937177, 'reg_alpha': 2.895335296985857, 'reg_lambda': 3.402431108655866e-05, 'max_delta_step': 3}. Best is trial 0 with value: 0.45344129554655865.

Best trial: 0. Best value: 0.453441:   8%|▊         | 4/50 [00:44<08:20, 10.87s/it]

[I 2025-12-02 00:58:03,503] Trial 4 finished with value: 0.37449392712550605 and parameters: {'max_depth': 5, 'learning_rate': 0.047487557347559044, 'n_estimators': 915, 'subsample': 0.6943303585783374, 'colsample_bytree': 0.5569236321522791, 'min_child_weight': 4, 'gamma': 2.3550231826224395, 'reg_alpha': 0.021920362322178463, 'reg_lambda': 0.00015331499555941444, 'max_delta_step': 9}. Best is trial 0 with value: 0.45344129554655865.
[I 2025-12-02 00:58:03,509] Trial 6 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.012974863132002771, 'n_estimators': 388, 'subsample': 0.9332038665407962, 'colsample_bytree': 0.8463419904523461, 'min_child_weight': 5, 'gamma': 0.8034876738585345, 'reg_alpha': 0.23804940027607907, 'reg_lambda': 1.8368511663869704, 'max_delta_step': 5}. Best is trial 0 with value: 0.45344129554655865.

Best trial: 0. Best value: 0.453441:  12%|█▏        | 6/50 [00:48<04:31,  6.17s/it]

[I 2025-12-02 00:58:07,492] Trial 2 finished with value: 0.019230769230769232 and parameters: {'max_depth': 8, 'learning_rate': 0.1623588609892972, 'n_estimators': 1453, 'subsample': 0.5954208406127637, 'colsample_bytree': 0.7727573098109249, 'min_child_weight': 6, 'gamma': 0.46988591877596186, 'reg_alpha': 1.0607003171537158e-06, 'reg_lambda': 2.1181848380633146e-07, 'max_delta_step': 2}. Best is trial 0 with value: 0.45344129554655865.

Best trial: 7. Best value: 0.498988:  14%|█▍        | 7/50 [00:57<05:02,  7.04s/it]

[I 2025-12-02 00:58:16,836] Trial 7 finished with value: 0.4989878542510121 and parameters: {'max_depth': 3, 'learning_rate': 0.02702163632826843, 'n_estimators': 216, 'subsample': 0.7413234246739339, 'colsample_bytree': 0.6397296822725898, 'min_child_weight': 1, 'gamma': 0.4042146706321337, 'reg_alpha': 4.491215920631797e-07, 'reg_lambda': 0.10611409328182257, 'max_delta_step': 6}. Best is trial 7 with value: 0.4989878542510121.

Best trial: 7. Best value: 0.498988:  16%|█▌        | 8/50 [01:05<05:09,  7.38s/it]

[I 2025-12-02 00:58:25,088] Trial 9 finished with value: 0.48684210526315785 and parameters: {'max_depth': 10, 'learning_rate': 0.05883578669219194, 'n_estimators': 372, 'subsample': 0.7999269594053668, 'colsample_bytree': 0.9270591620190844, 'min_child_weight': 1, 'gamma': 1.4102013940036573, 'reg_alpha': 3.4775383821643854e-08, 'reg_lambda': 4.706374277938121e-07, 'max_delta_step': 3}. Best is trial 7 with value: 0.4989878542510121.

Best trial: 7. Best value: 0.498988:  18%|█▊        | 9/50 [01:12<04:55,  7.21s/it]

[I 2025-12-02 00:58:31,867] Trial 5 finished with value: 0.4564777327935223 and parameters: {'max_depth': 5, 'learning_rate': 0.19594544423125734, 'n_estimators': 1478, 'subsample': 0.64236865763176, 'colsample_bytree': 0.7466127710560363, 'min_child_weight': 6, 'gamma': 3.2943299648167153, 'reg_alpha': 0.0008154336279084817, 'reg_lambda': 0.13337434061688982, 'max_delta_step': 8}. Best is trial 7 with value: 0.4989878542510121.

Best trial: 7. Best value: 0.498988:  20%|██        | 10/50 [01:14<03:48,  5.70s/it]

[I 2025-12-02 00:58:33,880] Trial 10 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.06157929526888504, 'n_estimators': 544, 'subsample': 0.9135900752475838, 'colsample_bytree': 0.6271789134465617, 'min_child_weight': 8, 'gamma': 0.9289307263419772, 'reg_alpha': 0.019747296293036173, 'reg_lambda': 5.402473472920088e-06, 'max_delta_step': 6}. Best is trial 7 with value: 0.4989878542510121.

Best trial: 8. Best value: 0.525304:  22%|██▏       | 11/50 [01:15<02:44,  4.21s/it]

[I 2025-12-02 00:58:34,522] Trial 8 finished with value: 0.5253036437246963 and parameters: {'max_depth': 10, 'learning_rate': 0.015600897054264668, 'n_estimators': 621, 'subsample': 0.8992240882167095, 'colsample_bytree': 0.6403187622566378, 'min_child_weight': 1, 'gamma': 1.3813270907160131, 'reg_alpha': 2.940051509895704e-07, 'reg_lambda': 6.16472742171225e-08, 'max_delta_step': 7}. Best is trial 8 with value: 0.5253036437246963.

Best trial: 8. Best value: 0.525304:  24%|██▍       | 12/50 [01:21<03:03,  4.83s/it]

[I 2025-12-02 00:58:40,829] Trial 12 pruned.

Best trial: 8. Best value: 0.525304:  26%|██▌       | 13/50 [01:24<02:41,  4.37s/it]

[I 2025-12-02 00:58:44,097] Trial 14 finished with value: 0.4989878542510121 and parameters: {'max_depth': 4, 'learning_rate': 0.014285257687887434, 'n_estimators': 212, 'subsample': 0.8143003632555649, 'colsample_bytree': 0.6423148507100039, 'min_child_weight': 3, 'gamma': 4.89542100155072, 'reg_alpha': 1.1407860615241765e-08, 'reg_lambda': 0.01124319006108351, 'max_delta_step': 7}. Best is trial 8 with value: 0.5253036437246963.

Best trial: 8. Best value: 0.525304:  28%|██▊       | 14/50 [01:31<03:04,  5.13s/it]

[I 2025-12-02 00:58:51,022] Trial 15 finished with value: 0.5253036437246963 and parameters: {'max_depth': 3, 'learning_rate': 0.015061276328996887, 'n_estimators': 229, 'subsample': 0.8083898499807648, 'colsample_bytree': 0.5011408030387914, 'min_child_weight': 3, 'gamma': 4.214520225461156, 'reg_alpha': 2.9560681595942264e-06, 'reg_lambda': 0.007109364036461223, 'max_delta_step': 7}. Best is trial 8 with value: 0.5253036437246963.

Best trial: 11. Best value: 0.544534:  30%|███       | 15/50 [01:41<03:53,  6.67s/it]

[I 2025-12-02 00:59:01,307] Trial 11 finished with value: 0.5445344129554656 and parameters: {'max_depth': 10, 'learning_rate': 0.27605366074794513, 'n_estimators': 966, 'subsample': 0.8823030419178968, 'colsample_bytree': 0.8903724189263946, 'min_child_weight': 2, 'gamma': 2.9042083453909977, 'reg_alpha': 3.778838466807489e-06, 'reg_lambda': 0.015505956118034427, 'max_delta_step': 9}. Best is trial 11 with value: 0.5445344129554656.

Best trial: 13. Best value: 0.57085:  32%|███▏      | 16/50 [01:52<04:30,  7.97s/it]

[I 2025-12-02 00:59:12,331] Trial 13 finished with value: 0.5708502024291497 and parameters: {'max_depth': 3, 'learning_rate': 0.016766875365569825, 'n_estimators': 1119, 'subsample': 0.8172829538157171, 'colsample_bytree': 0.5022047615980989, 'min_child_weight': 3, 'gamma': 4.320462463352398, 'reg_alpha': 2.280020144606449e-05, 'reg_lambda': 0.03670141693573653, 'max_delta_step': 0}. Best is trial 13 with value: 0.5708502024291497.

Best trial: 13. Best value: 0.57085:  34%|███▍      | 17/50 [01:57<03:52,  7.04s/it]

[I 2025-12-02 00:59:17,192] Trial 16 finished with value: 0.5253036437246963 and parameters: {'max_depth': 3, 'learning_rate': 0.025313614107155585, 'n_estimators': 913, 'subsample': 0.8628465120562783, 'colsample_bytree': 0.5024595151726828, 'min_child_weight': 2, 'gamma': 1.5366639950937466, 'reg_alpha': 2.3718242862011298e-06, 'reg_lambda': 0.003715795695332368, 'max_delta_step': 10}. Best is trial 13 with value: 0.5708502024291497.

Best trial: 13. Best value: 0.57085:  36%|███▌      | 18/50 [02:02<03:25,  6.42s/it]

[I 2025-12-02 00:59:22,169] Trial 17 finished with value: 0.5516194331983806 and parameters: {'max_depth': 6, 'learning_rate': 0.022339455128671817, 'n_estimators': 889, 'subsample': 0.8708135783479739, 'colsample_bytree': 0.533927887724441, 'min_child_weight': 3, 'gamma': 4.647810420176654, 'reg_alpha': 1.2864709132414276e-05, 'reg_lambda': 0.0015359761205253292, 'max_delta_step': 10}. Best is trial 13 with value: 0.5708502024291497.

Best trial: 13. Best value: 0.57085:  38%|███▊      | 19/50 [02:10<03:32,  6.87s/it]

[I 2025-12-02 00:59:30,074] Trial 21 pruned.

Best trial: 13. Best value: 0.57085:  40%|████      | 20/50 [02:18<03:33,  7.12s/it]

[I 2025-12-02 00:59:37,802] Trial 22 pruned.

Best trial: 13. Best value: 0.57085:  42%|████▏     | 21/50 [02:19<02:37,  5.44s/it]

[I 2025-12-02 00:59:39,308] Trial 18 finished with value: 0.5637651821862348 and parameters: {'max_depth': 9, 'learning_rate': 0.024384487637244077, 'n_estimators': 1022, 'subsample': 0.8787219548542183, 'colsample_bytree': 0.9358798629605208, 'min_child_weight': 3, 'gamma': 1.8565212753572922, 'reg_alpha': 8.390640843205178e-06, 'reg_lambda': 0.0014963118348996296, 'max_delta_step': 10}. Best is trial 13 with value: 0.5708502024291497.

Best trial: 13. Best value: 0.57085:  44%|████▍     | 22/50 [02:34<03:45,  8.05s/it]

[I 2025-12-02 00:59:53,453] Trial 23 pruned.

Best trial: 19. Best value: 0.590081:  46%|████▌     | 23/50 [02:37<02:59,  6.64s/it]

[I 2025-12-02 00:59:56,797] Trial 19 finished with value: 0.590080971659919 and parameters: {'max_depth': 7, 'learning_rate': 0.12308332207586227, 'n_estimators': 1114, 'subsample': 0.992187068337214, 'colsample_bytree': 0.9735169006655451, 'min_child_weight': 3, 'gamma': 3.741015881008714, 'reg_alpha': 2.881039634215339e-05, 'reg_lambda': 8.388380588760608, 'max_delta_step': 0}. Best is trial 19 with value: 0.590080971659919.

Best trial: 19. Best value: 0.590081:  48%|████▊     | 24/50 [02:38<02:05,  4.84s/it]

[I 2025-12-02 00:59:57,448] Trial 20 finished with value: 0.5516194331983806 and parameters: {'max_depth': 7, 'learning_rate': 0.11647473184430446, 'n_estimators': 1123, 'subsample': 0.8633122179207887, 'colsample_bytree': 0.9854149765615916, 'min_child_weight': 3, 'gamma': 3.78872351062737, 'reg_alpha': 5.090294651863697e-05, 'reg_lambda': 1.5413035572416622, 'max_delta_step': 0}. Best is trial 19 with value: 0.590080971659919.

Best trial: 19. Best value: 0.590081:  50%|█████     | 25/50 [02:47<02:35,  6.23s/it]

[I 2025-12-02 01:00:06,912] Trial 24 finished with value: 0.590080971659919 and parameters: {'max_depth': 9, 'learning_rate': 0.02039543391506871, 'n_estimators': 761, 'subsample': 0.7526533229329498, 'colsample_bytree': 0.955759204016476, 'min_child_weight': 3, 'gamma': 4.007379412296743, 'reg_alpha': 5.4176121790435326e-05, 'reg_lambda': 0.0007573589016382963, 'max_delta_step': 10}. Best is trial 19 with value: 0.590080971659919.

Best trial: 19. Best value: 0.590081:  52%|█████▏    | 26/50 [02:56<02:51,  7.14s/it]

[I 2025-12-02 01:00:16,167] Trial 26 pruned.

Best trial: 19. Best value: 0.590081:  54%|█████▍    | 27/50 [03:10<03:26,  8.97s/it]

[I 2025-12-02 01:00:29,426] Trial 25 finished with value: 0.5253036437246963 and parameters: {'max_depth': 9, 'learning_rate': 0.019822734961339305, 'n_estimators': 1043, 'subsample': 0.8411001446022063, 'colsample_bytree': 0.9904386465648735, 'min_child_weight': 4, 'gamma': 1.9747310143910237, 'reg_alpha': 3.5826757190683044e-05, 'reg_lambda': 0.16678467230362734, 'max_delta_step': 10}. Best is trial 19 with value: 0.590080971659919.

Best trial: 19. Best value: 0.590081:  56%|█████▌    | 28/50 [03:19<03:18,  9.02s/it]

[I 2025-12-02 01:00:38,565] Trial 27 finished with value: 0.5253036437246963 and parameters: {'max_depth': 9, 'learning_rate': 0.0959229171600147, 'n_estimators': 1275, 'subsample': 0.9525829979940099, 'colsample_bytree': 0.986291024536918, 'min_child_weight': 4, 'gamma': 2.293265211351424, 'reg_alpha': 0.00013308365406168007, 'reg_lambda': 0.1742905109348896, 'max_delta_step': 1}. Best is trial 19 with value: 0.590080971659919.

Best trial: 19. Best value: 0.590081:  58%|█████▊    | 29/50 [03:29<03:18,  9.45s/it]

[I 2025-12-02 01:00:48,995] Trial 28 finished with value: 0.5060728744939271 and parameters: {'max_depth': 9, 'learning_rate': 0.09976252125697459, 'n_estimators': 1327, 'subsample': 0.9593524237519901, 'colsample_bytree': 0.9781223381354213, 'min_child_weight': 4, 'gamma': 3.4836574646910075, 'reg_alpha': 0.00014868141697834937, 'reg_lambda': 0.17691098226318938, 'max_delta_step': 1}. Best is trial 19 with value: 0.590080971659919.

Best trial: 19. Best value: 0.590081:  60%|██████    | 30/50 [03:40<03:16,  9.81s/it]

[I 2025-12-02 01:00:59,659] Trial 32 pruned.

Best trial: 19. Best value: 0.590081:  62%|██████▏   | 31/50 [03:43<02:27,  7.76s/it]

[I 2025-12-02 01:01:02,618] Trial 29 finished with value: 0.5445344129554656 and parameters: {'max_depth': 9, 'learning_rate': 0.037541483976555184, 'n_estimators': 1322, 'subsample': 0.780070750636608, 'colsample_bytree': 0.8193444099790159, 'min_child_weight': 2, 'gamma': 4.427090476273143, 'reg_alpha': 0.0034596286937145803, 'reg_lambda': 0.055904017535684254, 'max_delta_step': 1}. Best is trial 19 with value: 0.590080971659919.

Best trial: 19. Best value: 0.590081:  64%|██████▍   | 32/50 [03:44<01:46,  5.91s/it]

[I 2025-12-02 01:01:04,204] Trial 31 finished with value: 0.5060728744939271 and parameters: {'max_depth': 4, 'learning_rate': 0.03880836205600075, 'n_estimators': 720, 'subsample': 0.7661193673355742, 'colsample_bytree': 0.8221880595080194, 'min_child_weight': 2, 'gamma': 3.49016544401581, 'reg_alpha': 0.0015989258128091912, 'reg_lambda': 0.028425495996653886, 'max_delta_step': 2}. Best is trial 19 with value: 0.590080971659919.

Best trial: 19. Best value: 0.590081:  66%|██████▌   | 33/50 [03:49<01:32,  5.42s/it]

[I 2025-12-02 01:01:08,488] Trial 30 pruned.

Best trial: 19. Best value: 0.590081:  68%|██████▊   | 34/50 [03:51<01:11,  4.44s/it]

[I 2025-12-02 01:01:10,644] Trial 34 pruned.

Best trial: 19. Best value: 0.590081:  70%|███████   | 35/50 [03:53<00:54,  3.66s/it]

[I 2025-12-02 01:01:12,482] Trial 35 pruned.

Best trial: 19. Best value: 0.590081:  72%|███████▏  | 36/50 [03:57<00:53,  3.82s/it]

[I 2025-12-02 01:01:16,697] Trial 36 pruned.

Best trial: 19. Best value: 0.590081:  74%|███████▍  | 37/50 [04:02<00:53,  4.11s/it]

[I 2025-12-02 01:01:21,473] Trial 38 pruned.

Best trial: 19. Best value: 0.590081:  76%|███████▌  | 38/50 [04:05<00:48,  4.01s/it]

[I 2025-12-02 01:01:25,249] Trial 39 pruned.

Best trial: 19. Best value: 0.590081:  78%|███████▊  | 39/50 [04:08<00:39,  3.61s/it]

[I 2025-12-02 01:01:27,932] Trial 40 pruned.

Best trial: 19. Best value: 0.590081:  80%|████████  | 40/50 [04:11<00:33,  3.31s/it]

[I 2025-12-02 01:01:30,532] Trial 37 pruned.

Best trial: 19. Best value: 0.590081:  82%|████████▏ | 41/50 [04:11<00:21,  2.42s/it]

[I 2025-12-02 01:01:30,870] Trial 33 finished with value: 0.5445344129554656 and parameters: {'max_depth': 4, 'learning_rate': 0.07826378731229477, 'n_estimators': 671, 'subsample': 0.7852020415252948, 'colsample_bytree': 0.93246487196992, 'min_child_weight': 2, 'gamma': 3.173707649958415, 'reg_alpha': 0.0034263405007866187, 'reg_lambda': 8.88273038661268, 'max_delta_step': 2}. Best is trial 19 with value: 0.590080971659919.

Best trial: 19. Best value: 0.590081:  84%|████████▍ | 42/50 [04:18<00:30,  3.87s/it]

[I 2025-12-02 01:01:38,133] Trial 42 pruned.

Best trial: 19. Best value: 0.590081:  86%|████████▌ | 43/50 [04:20<00:23,  3.32s/it]

[I 2025-12-02 01:01:40,164] Trial 41 pruned.

Best trial: 19. Best value: 0.590081:  88%|████████▊ | 44/50 [04:41<00:51,  8.60s/it]

[I 2025-12-02 01:02:01,083] Trial 44 finished with value: 0.5637651821862348 and parameters: {'max_depth': 5, 'learning_rate': 0.023061295447141965, 'n_estimators': 879, 'subsample': 0.8664081159645702, 'colsample_bytree': 0.7754108313027614, 'min_child_weight': 3, 'gamma': 4.583586993060176, 'reg_alpha': 1.7086419648621946e-05, 'reg_lambda': 0.002640884137056924, 'max_delta_step': 10}. Best is trial 19 with value: 0.590080971659919.

Best trial: 19. Best value: 0.590081:  90%|█████████ | 45/50 [04:46<00:37,  7.41s/it]

[I 2025-12-02 01:02:05,724] Trial 46 finished with value: 0.48684210526315785 and parameters: {'max_depth': 5, 'learning_rate': 0.023357391394560206, 'n_estimators': 878, 'subsample': 0.8666448836902941, 'colsample_bytree': 0.5422262095018999, 'min_child_weight': 4, 'gamma': 4.537893146353446, 'reg_alpha': 1.3611160312778598e-05, 'reg_lambda': 0.0027817232155200964, 'max_delta_step': 10}. Best is trial 19 with value: 0.590080971659919.

Best trial: 45. Best value: 0.609312:  92%|█████████▏| 46/50 [04:53<00:29,  7.32s/it]

[I 2025-12-02 01:02:12,822] Trial 45 finished with value: 0.6093117408906883 and parameters: {'max_depth': 5, 'learning_rate': 0.024070245140189014, 'n_estimators': 915, 'subsample': 0.8658692248588186, 'colsample_bytree': 0.5490376257173248, 'min_child_weight': 1, 'gamma': 4.684494099664781, 'reg_alpha': 1.5392587750974485e-05, 'reg_lambda': 0.0016823455741672478, 'max_delta_step': 10}. Best is trial 45 with value: 0.6093117408906883.

Best trial: 45. Best value: 0.609312:  94%|█████████▍| 47/50 [04:57<00:19,  6.34s/it]

[I 2025-12-02 01:02:16,871] Trial 49 pruned.

Best trial: 45. Best value: 0.609312:  96%|█████████▌| 48/50 [04:59<00:09,  4.94s/it]

[I 2025-12-02 01:02:18,560] Trial 48 pruned.

Best trial: 45. Best value: 0.609312:  98%|█████████▊| 49/50 [05:02<00:04,  4.42s/it]

[I 2025-12-02 01:02:21,756] Trial 43 finished with value: 0.5182186234817814 and parameters: {'max_depth': 10, 'learning_rate': 0.1508879701923944, 'n_estimators': 1393, 'subsample': 0.6799253573703834, 'colsample_bytree': 0.7737610381883654, 'min_child_weight': 1, 'gamma': 4.092398618932336, 'reg_alpha': 0.0003725387679210161, 'reg_lambda': 1.6115892338515398, 'max_delta_step': 2}. Best is trial 45 with value: 0.6093117408906883.

Best trial: 45. Best value: 0.609312: 100%|██████████| 50/50 [05:09<00:00,  6.19s/it]

[I 2025-12-02 01:02:28,744] Trial 47 finished with value: 0.5253036437246963 and parameters: {'max_depth': 5, 'learning_rate': 0.04662071275416719, 'n_estimators': 866, 'subsample': 0.7528380441888771, 'colsample_bytree': 0.8569791545173097, 'min_child_weight': 1, 'gamma': 4.676273474371227, 'reg_alpha': 0.0003510099000790697, 'reg_lambda': 0.0031726151878740763, 'max_delta_step': 10}. Best is trial 45 with value: 0.6093117408906883.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.685355                0.716667      0.733333
1    19_1         loo       0.628289                0.650000      0.600000
2    17_1         loo       0.609312                0.485714      0.600000
3    15_1         loo       0.596842                0.442857      0.400000

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.448543          0.833333               0.6        50          42
1  0.310530          0.500000               0.8        50          43
2 -0.028571          0.571429               0.4        50          45
3 -0.119523          0.285714               0.6        50          44

   test_size
0         11
1         11
2         12
3         12
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.685355                0.716667      0.733333
1    19_1         loo       0.628289                0.650000      0.600000
2    17_1         loo       0.609312                0.485714      0.600000
3    15_1         loo       0.596842                0.442857      0.400000

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.448543          0.833333               0.6        50          42
1  0.310530          0.500000               0.8        50          43
2 -0.028571          0.571429               0.4        50          45
3 -0.119523          0.285714               0.6        50          44

   test_size
0         11
1         11
2         12
3         12

In [ ]:
datasets = task_freq_dfs_ad_lbd

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_lbd_{CV_STRATEGY}_tasks/xgb_results_freq_ad_lbd_extended_{CV_STRATEGY}_tasks",
    split_param="emb_",
)
print(summary)

[I 2025-12-02 01:02:33,691] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 42, Test size: 11
Using Leave-One-Out CV with 42 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0:   2%|▏         | 1/50 [00:16<13:16, 16.25s/it]

[I 2025-12-02 01:02:49,934] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.05766402043607894, 'n_estimators': 450, 'subsample': 0.8125510845328667, 'colsample_bytree': 0.9365767208760695, 'min_child_weight': 8, 'gamma': 4.703141635573937, 'reg_alpha': 0.054782821287875, 'reg_lambda': 0.7609338168817268, 'max_delta_step': 1}. Best is trial 2 with value: 0.0.

Best trial: 0. Best value: 0.615561:   4%|▍         | 2/50 [00:30<12:01, 15.04s/it]

[I 2025-12-02 01:03:04,120] Trial 0 finished with value: 0.6155606407322655 and parameters: {'max_depth': 5, 'learning_rate': 0.1443456904295352, 'n_estimators': 854, 'subsample': 0.7083335921843772, 'colsample_bytree': 0.7553732717194945, 'min_child_weight': 2, 'gamma': 2.747326076451913, 'reg_alpha': 0.02914020262694222, 'reg_lambda': 1.3962994664221452e-05, 'max_delta_step': 8}. Best is trial 0 with value: 0.6155606407322655.

Best trial: 0. Best value: 0.615561:   6%|▌         | 3/50 [00:31<06:52,  8.77s/it]

[I 2025-12-02 01:03:05,443] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.058369069015410315, 'n_estimators': 445, 'subsample': 0.5785402402844455, 'colsample_bytree': 0.682627307335286, 'min_child_weight': 7, 'gamma': 4.672706727602616, 'reg_alpha': 3.26824744837592e-05, 'reg_lambda': 0.004963060833591412, 'max_delta_step': 3}. Best is trial 0 with value: 0.6155606407322655.

Best trial: 0. Best value: 0.615561:   8%|▊         | 4/50 [00:42<07:14,  9.44s/it]

[I 2025-12-02 01:03:15,903] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.028113862802936526, 'n_estimators': 1312, 'subsample': 0.5048808976314556, 'colsample_bytree': 0.5470965306163698, 'min_child_weight': 7, 'gamma': 1.6996727400302036, 'reg_alpha': 0.004513098125658737, 'reg_lambda': 0.6285983329733138, 'max_delta_step': 7}. Best is trial 0 with value: 0.6155606407322655.
[I 2025-12-02 01:03:15,912] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.01231503098827712, 'n_estimators': 1287, 'subsample': 0.7074675393994427, 'colsample_bytree': 0.7293178557406625, 'min_child_weight': 10, 'gamma': 4.195321966226009, 'reg_alpha': 0.000377524789625201, 'reg_lambda': 0.00020529216172723014, 'max_delta_step': 2}. Best is trial 0 with value: 0.6155606407322655.

Best trial: 0. Best value: 0.615561:  12%|█▏        | 6/50 [00:50<04:57,  6.76s/it]

[I 2025-12-02 01:03:24,686] Trial 6 finished with value: 0.5503432494279177 and parameters: {'max_depth': 10, 'learning_rate': 0.020444427387714518, 'n_estimators': 522, 'subsample': 0.7137693362224496, 'colsample_bytree': 0.9395890967065219, 'min_child_weight': 3, 'gamma': 4.315796201797153, 'reg_alpha': 4.007809838066246, 'reg_lambda': 0.011683330424124031, 'max_delta_step': 7}. Best is trial 0 with value: 0.6155606407322655.

Best trial: 0. Best value: 0.615561:  14%|█▍        | 7/50 [00:59<05:17,  7.37s/it]

[I 2025-12-02 01:03:33,666] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.01211620375617931, 'n_estimators': 260, 'subsample': 0.9112678972563537, 'colsample_bytree': 0.7624151012264102, 'min_child_weight': 9, 'gamma': 3.068135542875363, 'reg_alpha': 0.10278441418176514, 'reg_lambda': 9.451717276578686e-08, 'max_delta_step': 7}. Best is trial 0 with value: 0.6155606407322655.

Best trial: 0. Best value: 0.615561:  16%|█▌        | 8/50 [01:12<06:09,  8.80s/it]

[I 2025-12-02 01:03:46,097] Trial 10 finished with value: 0.21052631578947367 and parameters: {'max_depth': 6, 'learning_rate': 0.1332731869281465, 'n_estimators': 350, 'subsample': 0.8610179934228597, 'colsample_bytree': 0.904591349848429, 'min_child_weight': 5, 'gamma': 1.398507336183341, 'reg_alpha': 0.0001905608809493552, 'reg_lambda': 1.5996436266055485, 'max_delta_step': 5}. Best is trial 0 with value: 0.6155606407322655.

Best trial: 0. Best value: 0.615561:  18%|█▊        | 9/50 [01:14<04:46,  7.00s/it]

[I 2025-12-02 01:03:48,624] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.1177172411028392, 'n_estimators': 1069, 'subsample': 0.8952897375981044, 'colsample_bytree': 0.510285328547435, 'min_child_weight': 7, 'gamma': 4.293061678111504, 'reg_alpha': 3.5605413651968756, 'reg_lambda': 2.9015092428102172e-05, 'max_delta_step': 7}. Best is trial 0 with value: 0.6155606407322655.

Best trial: 0. Best value: 0.615561:  20%|██        | 10/50 [01:17<03:52,  5.81s/it]

[I 2025-12-02 01:03:51,539] Trial 5 finished with value: 0.5503432494279177 and parameters: {'max_depth': 3, 'learning_rate': 0.02282316910796158, 'n_estimators': 1142, 'subsample': 0.8401070357210123, 'colsample_bytree': 0.8341862236280222, 'min_child_weight': 2, 'gamma': 3.501318661087645, 'reg_alpha': 0.06666862875723763, 'reg_lambda': 9.199003446392137, 'max_delta_step': 2}. Best is trial 0 with value: 0.6155606407322655.

Best trial: 0. Best value: 0.615561:  22%|██▏       | 11/50 [01:23<03:45,  5.78s/it]

[I 2025-12-02 01:03:57,239] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.01519778205744288, 'n_estimators': 1321, 'subsample': 0.8658630602513281, 'colsample_bytree': 0.5864516782505469, 'min_child_weight': 9, 'gamma': 4.188963467217567, 'reg_alpha': 2.4745827152928782e-06, 'reg_lambda': 0.0010827325160998893, 'max_delta_step': 9}. Best is trial 0 with value: 0.6155606407322655.

Best trial: 0. Best value: 0.615561:  24%|██▍       | 12/50 [01:29<03:43,  5.88s/it]

[I 2025-12-02 01:04:03,346] Trial 11 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.014100392480119666, 'n_estimators': 504, 'subsample': 0.5346926960346026, 'colsample_bytree': 0.8479843943818902, 'min_child_weight': 8, 'gamma': 4.2200117635478716, 'reg_alpha': 0.00010237862980331172, 'reg_lambda': 2.670898728490084e-08, 'max_delta_step': 0}. Best is trial 0 with value: 0.6155606407322655.

Best trial: 0. Best value: 0.615561:  26%|██▌       | 13/50 [01:42<04:58,  8.06s/it]

[I 2025-12-02 01:04:16,567] Trial 13 finished with value: 0.5411899313501144 and parameters: {'max_depth': 8, 'learning_rate': 0.29245262974503006, 'n_estimators': 782, 'subsample': 0.6477543432585412, 'colsample_bytree': 0.6377524879927895, 'min_child_weight': 1, 'gamma': 0.030816503563774855, 'reg_alpha': 8.664443735543868e-08, 'reg_lambda': 4.0767578303268707e-07, 'max_delta_step': 10}. Best is trial 0 with value: 0.6155606407322655.

Best trial: 0. Best value: 0.615561:  28%|██▊       | 14/50 [01:47<04:14,  7.06s/it]

[I 2025-12-02 01:04:21,288] Trial 12 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.014887995898638963, 'n_estimators': 1054, 'subsample': 0.6409013010222755, 'colsample_bytree': 0.8505620531112177, 'min_child_weight': 6, 'gamma': 3.231744395349327, 'reg_alpha': 0.09334517919017178, 'reg_lambda': 5.906089503628768, 'max_delta_step': 4}. Best is trial 0 with value: 0.6155606407322655.

Best trial: 0. Best value: 0.615561:  30%|███       | 15/50 [01:54<04:09,  7.14s/it]

[I 2025-12-02 01:04:28,605] Trial 14 finished with value: 0.545766590389016 and parameters: {'max_depth': 5, 'learning_rate': 0.28555863256638275, 'n_estimators': 820, 'subsample': 0.9742109614112182, 'colsample_bytree': 0.8247111569506703, 'min_child_weight': 1, 'gamma': 2.8510775064315954, 'reg_alpha': 1.4875065966985143e-08, 'reg_lambda': 9.890114488411414e-07, 'max_delta_step': 10}. Best is trial 0 with value: 0.6155606407322655.

Best trial: 0. Best value: 0.615561:  32%|███▏      | 16/50 [01:55<03:00,  5.30s/it]

[I 2025-12-02 01:04:29,594] Trial 15 finished with value: 0.5411899313501144 and parameters: {'max_depth': 5, 'learning_rate': 0.2583078165579665, 'n_estimators': 828, 'subsample': 0.6406357164798943, 'colsample_bytree': 0.8227170151224223, 'min_child_weight': 1, 'gamma': 2.7769776907625032, 'reg_alpha': 1.40193988683414e-08, 'reg_lambda': 3.2589862031812643e-06, 'max_delta_step': 10}. Best is trial 0 with value: 0.6155606407322655.

Best trial: 0. Best value: 0.615561:  34%|███▍      | 17/50 [02:16<05:27,  9.91s/it]

[I 2025-12-02 01:04:50,317] Trial 17 finished with value: 0.4977116704805492 and parameters: {'max_depth': 4, 'learning_rate': 0.032704955144609374, 'n_estimators': 787, 'subsample': 0.9779716477077792, 'colsample_bytree': 0.7855729792996481, 'min_child_weight': 1, 'gamma': 2.4828303438247237, 'reg_alpha': 0.00371227779247337, 'reg_lambda': 4.770954242244947e-06, 'max_delta_step': 5}. Best is trial 0 with value: 0.6155606407322655.

Best trial: 0. Best value: 0.615561:  36%|███▌      | 18/50 [02:18<03:56,  7.40s/it]

[I 2025-12-02 01:04:51,823] Trial 16 finished with value: 0.44508009153318073 and parameters: {'max_depth': 5, 'learning_rate': 0.03889622365615421, 'n_estimators': 923, 'subsample': 0.975962315188914, 'colsample_bytree': 0.7960117066554391, 'min_child_weight': 1, 'gamma': 2.719541949749975, 'reg_alpha': 0.07645671574234233, 'reg_lambda': 4.6603487764827054e-06, 'max_delta_step': 4}. Best is trial 0 with value: 0.6155606407322655.

Best trial: 0. Best value: 0.615561:  38%|███▊      | 19/50 [02:26<03:54,  7.58s/it]

[I 2025-12-02 01:04:59,821] Trial 18 finished with value: 0.6155606407322655 and parameters: {'max_depth': 4, 'learning_rate': 0.034800281456952256, 'n_estimators': 1071, 'subsample': 0.7580418587439793, 'colsample_bytree': 0.7767313042251831, 'min_child_weight': 3, 'gamma': 1.9298764822411574, 'reg_alpha': 0.006892144991704362, 'reg_lambda': 9.326388236095043e-06, 'max_delta_step': 5}. Best is trial 0 with value: 0.6155606407322655.

Best trial: 19. Best value: 0.659039:  40%|████      | 20/50 [02:43<05:18, 10.62s/it]

[I 2025-12-02 01:05:17,547] Trial 19 finished with value: 0.6590389016018307 and parameters: {'max_depth': 4, 'learning_rate': 0.03365083297337935, 'n_estimators': 1495, 'subsample': 0.7823227919953365, 'colsample_bytree': 0.9928722723569628, 'min_child_weight': 3, 'gamma': 1.98384982071491, 'reg_alpha': 0.0028517032568726366, 'reg_lambda': 0.05200621983044734, 'max_delta_step': 5}. Best is trial 19 with value: 0.6590389016018307.

Best trial: 19. Best value: 0.659039:  42%|████▏     | 21/50 [03:05<06:43, 13.92s/it]

[I 2025-12-02 01:05:39,164] Trial 20 finished with value: 0.6372997711670481 and parameters: {'max_depth': 4, 'learning_rate': 0.09467820266162623, 'n_estimators': 1500, 'subsample': 0.7592268133798789, 'colsample_bytree': 0.6947411530615475, 'min_child_weight': 3, 'gamma': 3.494436933290688, 'reg_alpha': 0.005333186190463148, 'reg_lambda': 0.05564182996167603, 'max_delta_step': 3}. Best is trial 19 with value: 0.6590389016018307.

Best trial: 19. Best value: 0.659039:  44%|████▍     | 22/50 [03:09<05:10, 11.10s/it]

[I 2025-12-02 01:05:43,669] Trial 21 finished with value: 0.6372997711670481 and parameters: {'max_depth': 4, 'learning_rate': 0.09574131735456338, 'n_estimators': 1478, 'subsample': 0.7766764385127272, 'colsample_bytree': 0.9984806812225111, 'min_child_weight': 3, 'gamma': 3.5843423326335877, 'reg_alpha': 0.664486223384327, 'reg_lambda': 0.03252225440404499, 'max_delta_step': 8}. Best is trial 19 with value: 0.6590389016018307.

Best trial: 19. Best value: 0.659039:  46%|████▌     | 23/50 [03:14<04:10,  9.27s/it]

[I 2025-12-02 01:05:48,685] Trial 22 finished with value: 0.6327231121281465 and parameters: {'max_depth': 4, 'learning_rate': 0.12178322388877826, 'n_estimators': 1485, 'subsample': 0.7778786900007401, 'colsample_bytree': 0.7096408519745243, 'min_child_weight': 4, 'gamma': 1.762305293976029, 'reg_alpha': 0.004041260996469403, 'reg_lambda': 6.167783732411837e-05, 'max_delta_step': 8}. Best is trial 19 with value: 0.6590389016018307.

Best trial: 19. Best value: 0.659039:  48%|████▊     | 24/50 [03:35<05:26, 12.57s/it]

[I 2025-12-02 01:06:08,963] Trial 23 finished with value: 0.6590389016018307 and parameters: {'max_depth': 6, 'learning_rate': 0.08714689027784338, 'n_estimators': 1494, 'subsample': 0.7749080976498222, 'colsample_bytree': 0.9988597429843389, 'min_child_weight': 4, 'gamma': 0.8716289150005185, 'reg_alpha': 5.536222383215203e-06, 'reg_lambda': 0.046778274962578616, 'max_delta_step': 8}. Best is trial 19 with value: 0.6590389016018307.

Best trial: 24. Best value: 0.685355:  50%|█████     | 25/50 [03:55<06:09, 14.78s/it]

[I 2025-12-02 01:06:28,898] Trial 24 finished with value: 0.6853546910755148 and parameters: {'max_depth': 4, 'learning_rate': 0.09506987076221657, 'n_estimators': 1455, 'subsample': 0.7750576070855384, 'colsample_bytree': 0.9889057117186872, 'min_child_weight': 4, 'gamma': 2.1794086656340306, 'reg_alpha': 0.0012649218476033094, 'reg_lambda': 0.08804834612727354, 'max_delta_step': 6}. Best is trial 24 with value: 0.6853546910755148.

Best trial: 24. Best value: 0.685355:  52%|█████▏    | 26/50 [04:00<04:44, 11.87s/it]

[I 2025-12-02 01:06:33,986] Trial 25 finished with value: 0.6853546910755148 and parameters: {'max_depth': 4, 'learning_rate': 0.09368442642912421, 'n_estimators': 1488, 'subsample': 0.7807892066027492, 'colsample_bytree': 0.9882431016486651, 'min_child_weight': 4, 'gamma': 3.506414791862401, 'reg_alpha': 1.0128748406601005, 'reg_lambda': 0.04068653973859534, 'max_delta_step': 6}. Best is trial 24 with value: 0.6853546910755148.

Best trial: 26. Best value: 0.707094:  54%|█████▍    | 27/50 [04:04<03:39,  9.55s/it]

[I 2025-12-02 01:06:38,105] Trial 26 finished with value: 0.7070938215102975 and parameters: {'max_depth': 3, 'learning_rate': 0.09088539713171993, 'n_estimators': 1466, 'subsample': 0.782331584028402, 'colsample_bytree': 0.999029219320596, 'min_child_weight': 4, 'gamma': 3.6069581565051627, 'reg_alpha': 1.0595556165185545, 'reg_lambda': 0.08290694233923782, 'max_delta_step': 6}. Best is trial 26 with value: 0.7070938215102975.

Best trial: 26. Best value: 0.707094:  56%|█████▌    | 28/50 [04:06<02:38,  7.22s/it]

[I 2025-12-02 01:06:39,911] Trial 28 pruned.

Best trial: 26. Best value: 0.707094:  58%|█████▊    | 29/50 [04:11<02:22,  6.78s/it]

[I 2025-12-02 01:06:45,649] Trial 29 pruned.

Best trial: 26. Best value: 0.707094:  60%|██████    | 30/50 [04:15<01:57,  5.87s/it]

[I 2025-12-02 01:06:49,401] Trial 30 pruned.

Best trial: 26. Best value: 0.707094:  62%|██████▏   | 31/50 [04:22<01:58,  6.25s/it]

[I 2025-12-02 01:06:56,523] Trial 27 finished with value: 0.6853546910755148 and parameters: {'max_depth': 6, 'learning_rate': 0.07844973755571269, 'n_estimators': 1396, 'subsample': 0.803286650848035, 'colsample_bytree': 0.9558222300991264, 'min_child_weight': 4, 'gamma': 0.7763319021592843, 'reg_alpha': 4.3456078678491465e-06, 'reg_lambda': 0.0900428375779486, 'max_delta_step': 6}. Best is trial 26 with value: 0.7070938215102975.

Best trial: 31. Best value: 0.71167:  64%|██████▍   | 32/50 [04:47<03:32, 11.81s/it]

[I 2025-12-02 01:07:21,314] Trial 31 finished with value: 0.7116704805491991 and parameters: {'max_depth': 3, 'learning_rate': 0.18770283653712966, 'n_estimators': 1208, 'subsample': 0.6844830703649354, 'colsample_bytree': 0.8999078737038861, 'min_child_weight': 4, 'gamma': 3.749466477242117, 'reg_alpha': 0.5263299786018956, 'reg_lambda': 0.0019279622408603534, 'max_delta_step': 6}. Best is trial 31 with value: 0.7116704805491991.

Best trial: 31. Best value: 0.71167:  66%|██████▌   | 33/50 [04:53<02:51, 10.09s/it]

[I 2025-12-02 01:07:27,378] Trial 32 finished with value: 0.6681922196796339 and parameters: {'max_depth': 3, 'learning_rate': 0.18490152686877673, 'n_estimators': 1212, 'subsample': 0.7103723415586355, 'colsample_bytree': 0.9429382967547971, 'min_child_weight': 4, 'gamma': 3.8347682719233664, 'reg_alpha': 0.6288530551241001, 'reg_lambda': 0.0014952633931760414, 'max_delta_step': 6}. Best is trial 31 with value: 0.7116704805491991.

Best trial: 31. Best value: 0.71167:  68%|██████▊   | 34/50 [04:57<02:10,  8.15s/it]

[I 2025-12-02 01:07:31,005] Trial 33 finished with value: 0.6464530892448512 and parameters: {'max_depth': 5, 'learning_rate': 0.20249764346839672, 'n_estimators': 1238, 'subsample': 0.7130389338743973, 'colsample_bytree': 0.9549008413541132, 'min_child_weight': 4, 'gamma': 3.8411698213200673, 'reg_alpha': 0.4929019721168485, 'reg_lambda': 0.010001107341911612, 'max_delta_step': 6}. Best is trial 31 with value: 0.7116704805491991.

Best trial: 31. Best value: 0.71167:  70%|███████   | 35/50 [05:03<01:54,  7.62s/it]

[I 2025-12-02 01:07:37,381] Trial 34 finished with value: 0.6899313501144164 and parameters: {'max_depth': 5, 'learning_rate': 0.16246462884950882, 'n_estimators': 1169, 'subsample': 0.7274423255781253, 'colsample_bytree': 0.9586068279651484, 'min_child_weight': 4, 'gamma': 0.010023090477276897, 'reg_alpha': 1.0397007261037728e-06, 'reg_lambda': 0.010025044216352199, 'max_delta_step': 6}. Best is trial 31 with value: 0.7116704805491991.
[I 2025-12-02 01:07:37,417] Trial 36 pruned.

Best trial: 31. Best value: 0.71167:  74%|███████▍  | 37/50 [05:07<01:05,  5.00s/it]

[I 2025-12-02 01:07:41,299] Trial 37 pruned.

Best trial: 31. Best value: 0.71167:  76%|███████▌  | 38/50 [05:11<00:57,  4.77s/it]

[I 2025-12-02 01:07:45,352] Trial 38 pruned.

Best trial: 31. Best value: 0.71167:  78%|███████▊  | 39/50 [05:15<00:49,  4.49s/it]

[I 2025-12-02 01:07:49,049] Trial 40 pruned.

Best trial: 31. Best value: 0.71167:  80%|████████  | 40/50 [05:16<00:36,  3.70s/it]

[I 2025-12-02 01:07:50,631] Trial 41 pruned.

Best trial: 31. Best value: 0.71167:  82%|████████▏ | 41/50 [05:25<00:45,  5.09s/it]

[I 2025-12-02 01:07:59,302] Trial 43 pruned.

Best trial: 31. Best value: 0.71167:  84%|████████▍ | 42/50 [05:28<00:34,  4.37s/it]

[I 2025-12-02 01:08:01,883] Trial 35 finished with value: 0.7116704805491991 and parameters: {'max_depth': 3, 'learning_rate': 0.17341593103053377, 'n_estimators': 1217, 'subsample': 0.7095961978274747, 'colsample_bytree': 0.9652070146882612, 'min_child_weight': 4, 'gamma': 3.7602892646408934, 'reg_alpha': 0.4770262339669362, 'reg_lambda': 0.01252333863794841, 'max_delta_step': 6}. Best is trial 31 with value: 0.7116704805491991.

Best trial: 31. Best value: 0.71167:  86%|████████▌ | 43/50 [05:37<00:39,  5.69s/it]

[I 2025-12-02 01:08:10,795] Trial 39 finished with value: 0.620137299771167 and parameters: {'max_depth': 3, 'learning_rate': 0.1483577899941405, 'n_estimators': 934, 'subsample': 0.6842968875229088, 'colsample_bytree': 0.8860696318149215, 'min_child_weight': 2, 'gamma': 4.846068287626573, 'reg_alpha': 1.382470983445158e-07, 'reg_lambda': 0.0002678922932797807, 'max_delta_step': 7}. Best is trial 31 with value: 0.7116704805491991.

Best trial: 31. Best value: 0.71167:  88%|████████▊ | 44/50 [05:56<00:57,  9.58s/it]

[I 2025-12-02 01:08:29,770] Trial 42 finished with value: 0.5675057208237986 and parameters: {'max_depth': 5, 'learning_rate': 0.11090399429981725, 'n_estimators': 1170, 'subsample': 0.6796933020634456, 'colsample_bytree': 0.9300961950811236, 'min_child_weight': 2, 'gamma': 2.3771558807620545, 'reg_alpha': 3.0148236554229465e-05, 'reg_lambda': 1.4769683095422534, 'max_delta_step': 7}. Best is trial 31 with value: 0.7116704805491991.

Best trial: 31. Best value: 0.71167:  90%|█████████ | 45/50 [06:06<00:49,  9.86s/it]

[I 2025-12-02 01:08:40,294] Trial 45 finished with value: 0.6155606407322655 and parameters: {'max_depth': 3, 'learning_rate': 0.11591126578673808, 'n_estimators': 1155, 'subsample': 0.7378467437540364, 'colsample_bytree': 0.9268475690454755, 'min_child_weight': 3, 'gamma': 3.1955959720569362, 'reg_alpha': 1.798472793239175, 'reg_lambda': 1.375719949537283, 'max_delta_step': 6}. Best is trial 31 with value: 0.7116704805491991.

Best trial: 31. Best value: 0.71167:  92%|█████████▏| 46/50 [06:12<00:34,  8.57s/it]

[I 2025-12-02 01:08:45,811] Trial 44 finished with value: 0.5983981693363845 and parameters: {'max_depth': 4, 'learning_rate': 0.10845599303726128, 'n_estimators': 1421, 'subsample': 0.7303937196103294, 'colsample_bytree': 0.9257156647949598, 'min_child_weight': 4, 'gamma': 3.545716107909607, 'reg_alpha': 2.0692057018099597, 'reg_lambda': 2.0237206262705407, 'max_delta_step': 6}. Best is trial 31 with value: 0.7116704805491991.

Best trial: 31. Best value: 0.71167:  94%|█████████▍| 47/50 [06:14<00:20,  6.86s/it]

[I 2025-12-02 01:08:48,642] Trial 46 finished with value: 0.6155606407322655 and parameters: {'max_depth': 3, 'learning_rate': 0.11671821309908469, 'n_estimators': 1132, 'subsample': 0.7378808734554588, 'colsample_bytree': 0.929352648815567, 'min_child_weight': 3, 'gamma': 3.2751638117297004, 'reg_alpha': 0.2086463229424415, 'reg_lambda': 0.880942408515999, 'max_delta_step': 6}. Best is trial 31 with value: 0.7116704805491991.

Best trial: 31. Best value: 0.71167:  96%|█████████▌| 48/50 [06:20<00:12,  6.50s/it]

[I 2025-12-02 01:08:54,284] Trial 49 pruned.

Best trial: 31. Best value: 0.71167:  98%|█████████▊| 49/50 [06:28<00:06,  6.94s/it]

[I 2025-12-02 01:09:02,268] Trial 47 finished with value: 0.6155606407322655 and parameters: {'max_depth': 3, 'learning_rate': 0.11090158228974666, 'n_estimators': 1315, 'subsample': 0.7453335508323629, 'colsample_bytree': 0.9704537128823176, 'min_child_weight': 3, 'gamma': 3.140805798906796, 'reg_alpha': 2.302769613494325, 'reg_lambda': 0.012794986390273903, 'max_delta_step': 6}. Best is trial 31 with value: 0.7116704805491991.

Best trial: 31. Best value: 0.71167: 100%|██████████| 50/50 [06:32<00:00,  7.84s/it]

[I 2025-12-02 01:09:05,830] Trial 48 finished with value: 0.620137299771167 and parameters: {'max_depth': 3, 'learning_rate': 0.22215923581993613, 'n_estimators': 1304, 'subsample': 0.7325942762314325, 'colsample_bytree': 0.9720784630007919, 'min_child_weight': 4, 'gamma': 1.435050865595128, 'reg_alpha': 0.21658840146185432, 'reg_lambda': 0.017426942719572278, 'max_delta_step': 5}. Best is trial 31 with value: 0.7116704805491991.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 01:09:10,233] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 44, Test size: 12
Using Leave-One-Out CV with 44 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0:   2%|▏         | 1/50 [00:08<07:17,  8.94s/it]

[I 2025-12-02 01:09:19,162] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.022393336955101213, 'n_estimators': 231, 'subsample': 0.507898117257338, 'colsample_bytree': 0.5916844092528196, 'min_child_weight': 8, 'gamma': 4.92408091375269, 'reg_alpha': 6.633244116643258e-05, 'reg_lambda': 3.249055156221154, 'max_delta_step': 1}. Best is trial 3 with value: 0.0.

Best trial: 1. Best value: 0.563158:   4%|▍         | 2/50 [00:35<15:35, 19.49s/it]

[I 2025-12-02 01:09:46,032] Trial 1 finished with value: 0.5631578947368421 and parameters: {'max_depth': 7, 'learning_rate': 0.2705129584490224, 'n_estimators': 1010, 'subsample': 0.8491293238104727, 'colsample_bytree': 0.6004434547695154, 'min_child_weight': 4, 'gamma': 1.2798376028183274, 'reg_alpha': 0.1450198360647567, 'reg_lambda': 0.0003666716318682925, 'max_delta_step': 0}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:   6%|▌         | 3/50 [00:36<08:26, 10.79s/it]

[I 2025-12-02 01:09:46,465] Trial 0 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.0315526015353602, 'n_estimators': 1012, 'subsample': 0.8474020676657767, 'colsample_bytree': 0.7100693284130463, 'min_child_weight': 7, 'gamma': 3.4142157474832096, 'reg_alpha': 0.40508131703332284, 'reg_lambda': 1.0511970705419937, 'max_delta_step': 5}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:   8%|▊         | 4/50 [00:50<09:25, 12.30s/it]

[I 2025-12-02 01:10:01,093] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.1280176618127203, 'n_estimators': 1484, 'subsample': 0.9559795459485358, 'colsample_bytree': 0.5709270468791816, 'min_child_weight': 9, 'gamma': 3.4763414660737597, 'reg_alpha': 0.9140496930766473, 'reg_lambda': 0.00015549161510664672, 'max_delta_step': 8}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  10%|█         | 5/50 [00:52<06:22,  8.50s/it]

[I 2025-12-02 01:10:02,846] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.053494338447878785, 'n_estimators': 1309, 'subsample': 0.9909966845444727, 'colsample_bytree': 0.5803278975369921, 'min_child_weight': 8, 'gamma': 1.2673767530395508, 'reg_alpha': 0.005687684316219996, 'reg_lambda': 1.2806151654907038e-07, 'max_delta_step': 3}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  12%|█▏        | 6/50 [00:58<05:37,  7.68s/it]

[I 2025-12-02 01:10:08,929] Trial 6 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.010795498574579832, 'n_estimators': 625, 'subsample': 0.8973731685714805, 'colsample_bytree': 0.9796320384591306, 'min_child_weight': 9, 'gamma': 1.0728855785046187, 'reg_alpha': 0.00031242158609937656, 'reg_lambda': 0.15676466356178492, 'max_delta_step': 2}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  14%|█▍        | 7/50 [01:16<07:48, 10.90s/it]

[I 2025-12-02 01:10:26,465] Trial 5 finished with value: 0.5168421052631579 and parameters: {'max_depth': 6, 'learning_rate': 0.018500873393421883, 'n_estimators': 1056, 'subsample': 0.9137482656673259, 'colsample_bytree': 0.7864568235919941, 'min_child_weight': 3, 'gamma': 4.8607585332565515, 'reg_alpha': 1.4458542289972791, 'reg_lambda': 3.526966844741317e-06, 'max_delta_step': 1}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  16%|█▌        | 8/50 [01:30<08:22, 11.97s/it]

[I 2025-12-02 01:10:40,719] Trial 8 finished with value: 0.4442105263157895 and parameters: {'max_depth': 3, 'learning_rate': 0.06810033629289938, 'n_estimators': 1177, 'subsample': 0.7819804238534687, 'colsample_bytree': 0.6393726946294177, 'min_child_weight': 3, 'gamma': 4.1510434741274995, 'reg_alpha': 6.02842274675311e-07, 'reg_lambda': 0.004596611272482019, 'max_delta_step': 9}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  18%|█▊        | 9/50 [01:30<05:41,  8.32s/it]

[I 2025-12-02 01:10:41,035] Trial 7 finished with value: 0.45789473684210524 and parameters: {'max_depth': 4, 'learning_rate': 0.019405313638242407, 'n_estimators': 1094, 'subsample': 0.6080538419254664, 'colsample_bytree': 0.6437210569868698, 'min_child_weight': 2, 'gamma': 1.087495925082046, 'reg_alpha': 9.982964533660163e-05, 'reg_lambda': 0.0033725871959452455, 'max_delta_step': 4}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  20%|██        | 10/50 [01:40<05:51,  8.79s/it]

[I 2025-12-02 01:10:50,861] Trial 10 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.10215935229103762, 'n_estimators': 761, 'subsample': 0.646073179324569, 'colsample_bytree': 0.7634559942948986, 'min_child_weight': 10, 'gamma': 2.8842638508731127, 'reg_alpha': 4.691083086026067e-05, 'reg_lambda': 0.015874953303826846, 'max_delta_step': 0}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  22%|██▏       | 11/50 [01:43<04:32,  7.00s/it]

[I 2025-12-02 01:10:53,794] Trial 9 finished with value: 0.4642105263157895 and parameters: {'max_depth': 6, 'learning_rate': 0.0943045089542867, 'n_estimators': 1176, 'subsample': 0.6791119095927207, 'colsample_bytree': 0.8318435875244624, 'min_child_weight': 2, 'gamma': 0.6763276012459907, 'reg_alpha': 2.498399806771199, 'reg_lambda': 0.6640074894718931, 'max_delta_step': 6}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  24%|██▍       | 12/50 [02:00<06:25, 10.15s/it]

[I 2025-12-02 01:11:11,163] Trial 13 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.2946188176600308, 'n_estimators': 529, 'subsample': 0.7250340077218309, 'colsample_bytree': 0.8620695523397722, 'min_child_weight': 5, 'gamma': 1.9483487428872563, 'reg_alpha': 0.015195435694234385, 'reg_lambda': 2.7457350100882067e-05, 'max_delta_step': 7}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  26%|██▌       | 13/50 [02:11<06:15, 10.16s/it]

[I 2025-12-02 01:11:21,333] Trial 12 finished with value: 0.12 and parameters: {'max_depth': 8, 'learning_rate': 0.05923147635161767, 'n_estimators': 1172, 'subsample': 0.7661639919277416, 'colsample_bytree': 0.636851267004264, 'min_child_weight': 7, 'gamma': 3.9509634883122855, 'reg_alpha': 0.0026574536779645054, 'reg_lambda': 1.5291471251822917e-08, 'max_delta_step': 3}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  28%|██▊       | 14/50 [02:12<04:26,  7.39s/it]

[I 2025-12-02 01:11:22,326] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.2496427807387034, 'n_estimators': 824, 'subsample': 0.8236184879404478, 'colsample_bytree': 0.5018746163228561, 'min_child_weight': 5, 'gamma': 2.0318159159375435, 'reg_alpha': 0.02686312446775734, 'reg_lambda': 5.990979494246359e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  30%|███       | 15/50 [02:19<04:20,  7.44s/it]

[I 2025-12-02 01:11:29,880] Trial 11 finished with value: 0.3368421052631579 and parameters: {'max_depth': 8, 'learning_rate': 0.2347203128833795, 'n_estimators': 1376, 'subsample': 0.5126484982935904, 'colsample_bytree': 0.9543047865469387, 'min_child_weight': 5, 'gamma': 0.18899826532654318, 'reg_alpha': 6.350932595652633e-08, 'reg_lambda': 2.3056496630373773e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  32%|███▏      | 16/50 [02:25<03:55,  6.92s/it]

[I 2025-12-02 01:11:35,580] Trial 16 pruned.

Best trial: 1. Best value: 0.563158:  34%|███▍      | 17/50 [02:27<03:05,  5.62s/it]

[I 2025-12-02 01:11:38,190] Trial 17 pruned.

Best trial: 1. Best value: 0.563158:  36%|███▌      | 18/50 [02:30<02:33,  4.79s/it]

[I 2025-12-02 01:11:41,033] Trial 15 finished with value: 0.4705263157894737 and parameters: {'max_depth': 5, 'learning_rate': 0.2808562279867179, 'n_estimators': 858, 'subsample': 0.8280250550769359, 'colsample_bytree': 0.7472323328560783, 'min_child_weight': 4, 'gamma': 0.09028144844574815, 'reg_alpha': 0.050465417329796924, 'reg_lambda': 1.7243461850976808e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  38%|███▊      | 19/50 [02:34<02:22,  4.60s/it]

[I 2025-12-02 01:11:45,201] Trial 18 pruned.

Best trial: 1. Best value: 0.563158:  40%|████      | 20/50 [02:48<03:38,  7.28s/it]

[I 2025-12-02 01:11:58,718] Trial 20 finished with value: 0.5294736842105263 and parameters: {'max_depth': 5, 'learning_rate': 0.032827240736088864, 'n_estimators': 662, 'subsample': 0.9304653093314774, 'colsample_bytree': 0.832524561823993, 'min_child_weight': 3, 'gamma': 4.876372115048845, 'reg_alpha': 0.13171664132685657, 'reg_lambda': 0.00025799440167538544, 'max_delta_step': 2}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  42%|████▏     | 21/50 [02:53<03:09,  6.53s/it]

[I 2025-12-02 01:12:03,507] Trial 21 finished with value: 0.4978947368421053 and parameters: {'max_depth': 6, 'learning_rate': 0.16116959609171638, 'n_estimators': 642, 'subsample': 0.9347964405880096, 'colsample_bytree': 0.8396933810641867, 'min_child_weight': 1, 'gamma': 2.5936868737959813, 'reg_alpha': 0.18939010645768223, 'reg_lambda': 0.00033816720780087287, 'max_delta_step': 2}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  44%|████▍     | 22/50 [02:56<02:38,  5.66s/it]

[I 2025-12-02 01:12:07,122] Trial 24 pruned.

Best trial: 1. Best value: 0.563158:  46%|████▌     | 23/50 [03:00<02:13,  4.93s/it]

[I 2025-12-02 01:12:10,349] Trial 22 finished with value: 0.4842105263157894 and parameters: {'max_depth': 7, 'learning_rate': 0.0352201673158961, 'n_estimators': 669, 'subsample': 0.9621224524844668, 'colsample_bytree': 0.841324721428439, 'min_child_weight': 1, 'gamma': 2.7419937603749323, 'reg_alpha': 0.451554289156697, 'reg_lambda': 7.15616604875159e-05, 'max_delta_step': 2}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  48%|████▊     | 24/50 [03:03<01:55,  4.44s/it]

[I 2025-12-02 01:12:13,657] Trial 19 finished with value: 0.43157894736842106 and parameters: {'max_depth': 5, 'learning_rate': 0.010787180300806208, 'n_estimators': 999, 'subsample': 0.9234127755559811, 'colsample_bytree': 0.7225082589533568, 'min_child_weight': 1, 'gamma': 4.711741886013833, 'reg_alpha': 0.1649447403021582, 'reg_lambda': 0.000550941419450004, 'max_delta_step': 2}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  50%|█████     | 25/50 [03:09<02:01,  4.85s/it]

[I 2025-12-02 01:12:19,474] Trial 23 finished with value: 0.5242105263157895 and parameters: {'max_depth': 4, 'learning_rate': 0.0351840206608693, 'n_estimators': 463, 'subsample': 0.9875712605007226, 'colsample_bytree': 0.9078875607691508, 'min_child_weight': 1, 'gamma': 2.6983514367697135, 'reg_alpha': 0.153558690769669, 'reg_lambda': 0.00020449255509142418, 'max_delta_step': 4}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  52%|█████▏    | 26/50 [03:12<01:42,  4.25s/it]

[I 2025-12-02 01:12:22,328] Trial 27 pruned.

Best trial: 1. Best value: 0.563158:  54%|█████▍    | 27/50 [03:15<01:32,  4.04s/it]

[I 2025-12-02 01:12:25,878] Trial 26 finished with value: 0.49684210526315786 and parameters: {'max_depth': 4, 'learning_rate': 0.01680931317783108, 'n_estimators': 427, 'subsample': 0.8752454559765908, 'colsample_bytree': 0.7905988659866435, 'min_child_weight': 3, 'gamma': 4.4497634480180475, 'reg_alpha': 0.002806292452174212, 'reg_lambda': 0.0005756980285118513, 'max_delta_step': 1}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  56%|█████▌    | 28/50 [03:20<01:36,  4.39s/it]

[I 2025-12-02 01:12:31,067] Trial 25 finished with value: 0.4242105263157895 and parameters: {'max_depth': 7, 'learning_rate': 0.017299334567397816, 'n_estimators': 729, 'subsample': 0.8718447153479815, 'colsample_bytree': 0.7994998675884498, 'min_child_weight': 3, 'gamma': 4.446578674563154, 'reg_alpha': 0.001274063934776064, 'reg_lambda': 0.0013346288130570195, 'max_delta_step': 1}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  58%|█████▊    | 29/50 [03:26<01:37,  4.62s/it]

[I 2025-12-02 01:12:36,240] Trial 30 finished with value: 0.5631578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.0463303058078604, 'n_estimators': 231, 'subsample': 0.9932539111101025, 'colsample_bytree': 0.9177623072009181, 'min_child_weight': 2, 'gamma': 1.457789581142293, 'reg_alpha': 2.8614287350973097e-06, 'reg_lambda': 2.3706072249009282e-05, 'max_delta_step': 4}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  60%|██████    | 30/50 [03:27<01:13,  3.68s/it]

[I 2025-12-02 01:12:37,706] Trial 28 finished with value: 0.5305263157894737 and parameters: {'max_depth': 4, 'learning_rate': 0.048861859224790714, 'n_estimators': 452, 'subsample': 0.9900648044648522, 'colsample_bytree': 0.9144390929756155, 'min_child_weight': 2, 'gamma': 3.387420941846598, 'reg_alpha': 0.001960697725805755, 'reg_lambda': 0.005389519379289243, 'max_delta_step': 4}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  64%|██████▍   | 32/50 [03:28<00:35,  1.96s/it]

[I 2025-12-02 01:12:38,283] Trial 29 finished with value: 0.5568421052631579 and parameters: {'max_depth': 4, 'learning_rate': 0.045629916296784395, 'n_estimators': 382, 'subsample': 0.9817140408500314, 'colsample_bytree': 0.9123120573389433, 'min_child_weight': 2, 'gamma': 1.6490516693420054, 'reg_alpha': 0.0007859063611548424, 'reg_lambda': 0.024367877899277628, 'max_delta_step': 4}. Best is trial 1 with value: 0.5631578947368421.
[I 2025-12-02 01:12:38,420] Trial 32 pruned.

Best trial: 1. Best value: 0.563158:  66%|██████▌   | 33/50 [03:36<01:04,  3.79s/it]

[I 2025-12-02 01:12:46,464] Trial 31 finished with value: 0.5242105263157895 and parameters: {'max_depth': 3, 'learning_rate': 0.025355571658768342, 'n_estimators': 346, 'subsample': 0.794355849429424, 'colsample_bytree': 0.901814426686681, 'min_child_weight': 2, 'gamma': 1.5940146693143356, 'reg_alpha': 5.973174123687492e-06, 'reg_lambda': 0.06655289640558529, 'max_delta_step': 4}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 1. Best value: 0.563158:  68%|██████▊   | 34/50 [03:37<00:47,  2.96s/it]

[I 2025-12-02 01:12:47,496] Trial 33 finished with value: 0.4442105263157895 and parameters: {'max_depth': 3, 'learning_rate': 0.0753194491535546, 'n_estimators': 251, 'subsample': 0.8171200710875777, 'colsample_bytree': 0.9340400778749115, 'min_child_weight': 2, 'gamma': 1.4740826727686818, 'reg_alpha': 1.505573219323674e-06, 'reg_lambda': 0.016442354151105208, 'max_delta_step': 6}. Best is trial 1 with value: 0.5631578947368421.

Best trial: 34. Best value: 0.576842:  70%|███████   | 35/50 [03:37<00:33,  2.26s/it]

[I 2025-12-02 01:12:48,118] Trial 34 finished with value: 0.5768421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.042149855885828404, 'n_estimators': 214, 'subsample': 0.9971158407310167, 'colsample_bytree': 0.9491111869138382, 'min_child_weight': 2, 'gamma': 1.569909912659952, 'reg_alpha': 1.426295789200522e-06, 'reg_lambda': 0.040563415553243484, 'max_delta_step': 5}. Best is trial 34 with value: 0.5768421052631579.

Best trial: 34. Best value: 0.576842:  72%|███████▏  | 36/50 [03:40<00:33,  2.42s/it]

[I 2025-12-02 01:12:50,927] Trial 38 pruned.

Best trial: 35. Best value: 0.603158:  74%|███████▍  | 37/50 [03:41<00:23,  1.83s/it]

[I 2025-12-02 01:12:51,369] Trial 35 finished with value: 0.6031578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.07280484000689136, 'n_estimators': 327, 'subsample': 0.9534968495369547, 'colsample_bytree': 0.9698115233440999, 'min_child_weight': 2, 'gamma': 1.678499796207678, 'reg_alpha': 1.341753344111847e-05, 'reg_lambda': 0.038717085901151575, 'max_delta_step': 6}. Best is trial 35 with value: 0.6031578947368421.

Best trial: 35. Best value: 0.603158:  76%|███████▌  | 38/50 [03:42<00:21,  1.82s/it]

[I 2025-12-02 01:12:53,164] Trial 39 pruned.

Best trial: 35. Best value: 0.603158:  78%|███████▊  | 39/50 [03:43<00:15,  1.41s/it]

[I 2025-12-02 01:12:53,615] Trial 40 pruned.

Best trial: 35. Best value: 0.603158:  80%|████████  | 40/50 [03:45<00:16,  1.61s/it]

[I 2025-12-02 01:12:55,684] Trial 41 pruned.

Best trial: 36. Best value: 0.609474:  82%|████████▏ | 41/50 [03:49<00:20,  2.24s/it]

[I 2025-12-02 01:12:59,389] Trial 36 finished with value: 0.6094736842105264 and parameters: {'max_depth': 3, 'learning_rate': 0.07658848448419439, 'n_estimators': 290, 'subsample': 0.9946946151419237, 'colsample_bytree': 0.9866164375113606, 'min_child_weight': 2, 'gamma': 3.064645849205827, 'reg_alpha': 0.0005430729378642948, 'reg_lambda': 0.008454845322317255, 'max_delta_step': 6}. Best is trial 36 with value: 0.6094736842105264.

Best trial: 36. Best value: 0.609474:  84%|████████▍ | 42/50 [03:51<00:17,  2.22s/it]

[I 2025-12-02 01:13:01,570] Trial 37 finished with value: 0.4705263157894737 and parameters: {'max_depth': 3, 'learning_rate': 0.04617982148777758, 'n_estimators': 307, 'subsample': 0.9946693393900103, 'colsample_bytree': 0.9925970936362982, 'min_child_weight': 2, 'gamma': 0.6623619815085235, 'reg_alpha': 0.00042960161083518305, 'reg_lambda': 0.014032824249427167, 'max_delta_step': 5}. Best is trial 36 with value: 0.6094736842105264.

Best trial: 36. Best value: 0.609474:  86%|████████▌ | 43/50 [03:52<00:12,  1.77s/it]

[I 2025-12-02 01:13:02,280] Trial 42 finished with value: 0.503157894736842 and parameters: {'max_depth': 9, 'learning_rate': 0.16866594713849703, 'n_estimators': 222, 'subsample': 0.8938367203256988, 'colsample_bytree': 0.9618283084477838, 'min_child_weight': 2, 'gamma': 0.9443068093465228, 'reg_alpha': 1.576526884079795e-06, 'reg_lambda': 0.05262881320320502, 'max_delta_step': 6}. Best is trial 36 with value: 0.6094736842105264.

Best trial: 36. Best value: 0.609474:  88%|████████▊ | 44/50 [03:53<00:10,  1.70s/it]

[I 2025-12-02 01:13:03,815] Trial 43 finished with value: 0.5105263157894737 and parameters: {'max_depth': 9, 'learning_rate': 0.07834272377312392, 'n_estimators': 212, 'subsample': 0.889010638152441, 'colsample_bytree': 0.5579717200412316, 'min_child_weight': 2, 'gamma': 1.219725118019313, 'reg_alpha': 1.2472523716832469e-06, 'reg_lambda': 7.043038976389599, 'max_delta_step': 6}. Best is trial 36 with value: 0.6094736842105264.

Best trial: 36. Best value: 0.609474:  90%|█████████ | 45/50 [03:58<00:13,  2.69s/it]

[I 2025-12-02 01:13:08,819] Trial 44 finished with value: 0.5505263157894738 and parameters: {'max_depth': 3, 'learning_rate': 0.07586653946187022, 'n_estimators': 202, 'subsample': 0.9377004975621743, 'colsample_bytree': 0.9609664042983401, 'min_child_weight': 2, 'gamma': 1.2332307733861816, 'reg_alpha': 1.5813001467920236e-06, 'reg_lambda': 6.418813583539773, 'max_delta_step': 6}. Best is trial 36 with value: 0.6094736842105264.

Best trial: 36. Best value: 0.609474:  92%|█████████▏| 46/50 [04:01<00:10,  2.67s/it]

[I 2025-12-02 01:13:11,444] Trial 45 finished with value: 0.5768421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.07993124998678981, 'n_estimators': 215, 'subsample': 0.9505895369487519, 'colsample_bytree': 0.9547058525910476, 'min_child_weight': 2, 'gamma': 1.1609762836219726, 'reg_alpha': 1.5938713878739686e-06, 'reg_lambda': 6.136626056581511, 'max_delta_step': 6}. Best is trial 36 with value: 0.6094736842105264.

Best trial: 36. Best value: 0.609474:  94%|█████████▍| 47/50 [04:15<00:18,  6.14s/it]

[I 2025-12-02 01:13:25,683] Trial 47 finished with value: 0.5042105263157894 and parameters: {'max_depth': 10, 'learning_rate': 0.05927070868975063, 'n_estimators': 569, 'subsample': 0.9485877412170195, 'colsample_bytree': 0.8738343884391905, 'min_child_weight': 1, 'gamma': 1.3064895437622674, 'reg_alpha': 0.0001109970451568771, 'reg_lambda': 0.006297416013010771, 'max_delta_step': 8}. Best is trial 36 with value: 0.6094736842105264.

Best trial: 36. Best value: 0.609474:  96%|█████████▌| 48/50 [04:16<00:08,  4.49s/it]

[I 2025-12-02 01:13:26,331] Trial 46 finished with value: 0.5505263157894738 and parameters: {'max_depth': 3, 'learning_rate': 0.07783729599244903, 'n_estimators': 574, 'subsample': 0.9469317599623971, 'colsample_bytree': 0.9498979063406149, 'min_child_weight': 1, 'gamma': 1.189585314199568, 'reg_alpha': 0.00015314525185561358, 'reg_lambda': 8.051170957264707, 'max_delta_step': 8}. Best is trial 36 with value: 0.6094736842105264.

Best trial: 36. Best value: 0.609474:  98%|█████████▊| 49/50 [04:18<00:03,  3.74s/it]

[I 2025-12-02 01:13:28,302] Trial 48 finished with value: 0.523157894736842 and parameters: {'max_depth': 4, 'learning_rate': 0.060100580557375445, 'n_estimators': 524, 'subsample': 0.7237138061951632, 'colsample_bytree': 0.877258539822254, 'min_child_weight': 1, 'gamma': 3.09590115802499, 'reg_alpha': 0.00012854695644680958, 'reg_lambda': 0.0011850562246508048, 'max_delta_step': 8}. Best is trial 36 with value: 0.6094736842105264.

Best trial: 36. Best value: 0.609474: 100%|██████████| 50/50 [04:23<00:00,  5.28s/it]

[I 2025-12-02 01:13:34,173] Trial 49 finished with value: 0.4442105263157895 and parameters: {'max_depth': 10, 'learning_rate': 0.09910813258230987, 'n_estimators': 1088, 'subsample': 0.7342775980270809, 'colsample_bytree': 0.879377995915154, 'min_child_weight': 3, 'gamma': 1.8153709314862874, 'reg_alpha': 0.00015686641116964022, 'reg_lambda': 1.566613781437904, 'max_delta_step': 8}. Best is trial 36 with value: 0.6094736842105264.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 01:13:37,794] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 45, Test size: 12
Using Leave-One-Out CV with 45 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.544534:   2%|▏         | 1/50 [00:20<16:53, 20.68s/it]

[I 2025-12-02 01:13:58,470] Trial 1 finished with value: 0.5445344129554656 and parameters: {'max_depth': 5, 'learning_rate': 0.09503691158162135, 'n_estimators': 628, 'subsample': 0.9350979706674309, 'colsample_bytree': 0.6001500493565106, 'min_child_weight': 4, 'gamma': 1.280049360901493, 'reg_alpha': 0.020211269325058123, 'reg_lambda': 0.0022365015451235133, 'max_delta_step': 10}. Best is trial 1 with value: 0.5445344129554656.

Best trial: 0. Best value: 0.563765:   4%|▍         | 2/50 [00:23<08:07, 10.16s/it]

[I 2025-12-02 01:14:01,254] Trial 0 finished with value: 0.5637651821862348 and parameters: {'max_depth': 7, 'learning_rate': 0.08452005931982454, 'n_estimators': 618, 'subsample': 0.507488422556635, 'colsample_bytree': 0.9834275073516675, 'min_child_weight': 2, 'gamma': 0.8096771147625653, 'reg_alpha': 0.00010361543726398589, 'reg_lambda': 1.1230480602386281, 'max_delta_step': 5}. Best is trial 0 with value: 0.5637651821862348.

Best trial: 0. Best value: 0.563765:   6%|▌         | 3/50 [00:37<09:28, 12.11s/it]

[I 2025-12-02 01:14:15,684] Trial 3 finished with value: 0.5060728744939271 and parameters: {'max_depth': 6, 'learning_rate': 0.21638349276769775, 'n_estimators': 1183, 'subsample': 0.725007721469312, 'colsample_bytree': 0.7792432417847259, 'min_child_weight': 4, 'gamma': 0.5851025701456636, 'reg_alpha': 1.7811036178855592e-05, 'reg_lambda': 0.0006902439052122406, 'max_delta_step': 2}. Best is trial 0 with value: 0.5637651821862348.

Best trial: 0. Best value: 0.563765:   8%|▊         | 4/50 [00:42<07:02,  9.18s/it]

[I 2025-12-02 01:14:20,392] Trial 2 finished with value: 0.5637651821862348 and parameters: {'max_depth': 3, 'learning_rate': 0.027259505698912057, 'n_estimators': 1207, 'subsample': 0.5578348396570537, 'colsample_bytree': 0.9530417688488013, 'min_child_weight': 2, 'gamma': 3.811622762905229, 'reg_alpha': 0.08245082764699606, 'reg_lambda': 5.389590454971265e-06, 'max_delta_step': 9}. Best is trial 0 with value: 0.5637651821862348.

Best trial: 0. Best value: 0.563765:  10%|█         | 5/50 [00:47<05:51,  7.81s/it]

[I 2025-12-02 01:14:25,774] Trial 5 finished with value: 0.5374493927125505 and parameters: {'max_depth': 9, 'learning_rate': 0.2308036766593832, 'n_estimators': 785, 'subsample': 0.7004701304414822, 'colsample_bytree': 0.7936596464837947, 'min_child_weight': 4, 'gamma': 0.05076737303373102, 'reg_alpha': 0.0006773434530006066, 'reg_lambda': 0.25058188220901956, 'max_delta_step': 7}. Best is trial 0 with value: 0.5637651821862348.

Best trial: 0. Best value: 0.563765:  12%|█▏        | 6/50 [00:53<05:14,  7.15s/it]

[I 2025-12-02 01:14:31,631] Trial 4 finished with value: 0.5637651821862348 and parameters: {'max_depth': 6, 'learning_rate': 0.01092161739689902, 'n_estimators': 672, 'subsample': 0.8548473599641602, 'colsample_bytree': 0.7313361239022875, 'min_child_weight': 2, 'gamma': 0.061641333980155255, 'reg_alpha': 4.218552237444146e-06, 'reg_lambda': 1.6674036931723933e-06, 'max_delta_step': 8}. Best is trial 0 with value: 0.5637651821862348.

Best trial: 0. Best value: 0.563765:  14%|█▍        | 7/50 [01:14<08:13, 11.47s/it]

[I 2025-12-02 01:14:51,996] Trial 7 finished with value: 0.07692307692307693 and parameters: {'max_depth': 4, 'learning_rate': 0.09860935699999976, 'n_estimators': 920, 'subsample': 0.8226349323689157, 'colsample_bytree': 0.6581446006028129, 'min_child_weight': 7, 'gamma': 1.936670351751012, 'reg_alpha': 1.5628604072419938, 'reg_lambda': 0.05470449992807235, 'max_delta_step': 2}. Best is trial 0 with value: 0.5637651821862348.

Best trial: 0. Best value: 0.563765:  16%|█▌        | 8/50 [01:23<07:28, 10.68s/it]

[I 2025-12-02 01:15:00,989] Trial 9 finished with value: 0.46153846153846156 and parameters: {'max_depth': 7, 'learning_rate': 0.18406356032879082, 'n_estimators': 847, 'subsample': 0.5599722364245632, 'colsample_bytree': 0.5259511706411222, 'min_child_weight': 4, 'gamma': 4.738356765590081, 'reg_alpha': 0.0006730245749708845, 'reg_lambda': 4.345787578727325e-07, 'max_delta_step': 3}. Best is trial 0 with value: 0.5637651821862348.
[I 2025-12-02 01:15:01,042] Trial 10 finished with value: 0.5323886639676113 and parameters: {'max_depth': 8, 'learning_rate': 0.2833020071257255, 'n_estimators': 209, 'subsample': 0.5493756405928774, 'colsample_bytree': 0.9671218103939768, 'min_child_weight': 2, 'gamma': 3.3456656278627417, 'reg_alpha': 0.0001248351182234889, 'reg_lambda': 0.10031834966529407, 'max_delta_step': 10}. Best is trial 0 with value: 0.5637651821862348.

Best trial: 0. Best value: 0.563765:  20%|██        | 10/50 [01:23<03:48,  5.72s/it]

[I 2025-12-02 01:15:01,512] Trial 8 finished with value: 0.5566801619433198 and parameters: {'max_depth': 9, 'learning_rate': 0.12124877919367205, 'n_estimators': 1025, 'subsample': 0.5391482774075653, 'colsample_bytree': 0.774274667599339, 'min_child_weight': 3, 'gamma': 4.001599359436304, 'reg_alpha': 3.758324692182387e-08, 'reg_lambda': 4.8020095307364984e-05, 'max_delta_step': 2}. Best is trial 0 with value: 0.5637651821862348.

Best trial: 0. Best value: 0.563765:  22%|██▏       | 11/50 [01:24<02:57,  4.56s/it]

[I 2025-12-02 01:15:02,666] Trial 6 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.010928863253056023, 'n_estimators': 1387, 'subsample': 0.8930334569405591, 'colsample_bytree': 0.8308290388038775, 'min_child_weight': 7, 'gamma': 1.441428579385049, 'reg_alpha': 4.062549960357356e-06, 'reg_lambda': 0.056636814486218684, 'max_delta_step': 7}. Best is trial 0 with value: 0.5637651821862348.

Best trial: 0. Best value: 0.563765:  24%|██▍       | 12/50 [01:25<02:16,  3.60s/it]

[I 2025-12-02 01:15:03,612] Trial 12 pruned.

Best trial: 0. Best value: 0.563765:  26%|██▌       | 13/50 [01:26<01:47,  2.90s/it]

[I 2025-12-02 01:15:04,689] Trial 13 pruned.

Best trial: 0. Best value: 0.563765:  28%|██▊       | 14/50 [01:32<02:14,  3.74s/it]

[I 2025-12-02 01:15:10,551] Trial 11 finished with value: 0.5516194331983806 and parameters: {'max_depth': 6, 'learning_rate': 0.017662934470009935, 'n_estimators': 265, 'subsample': 0.9943250434988065, 'colsample_bytree': 0.7889930855904064, 'min_child_weight': 4, 'gamma': 3.3792628421702195, 'reg_alpha': 4.457281390752428e-07, 'reg_lambda': 0.0001180998284908306, 'max_delta_step': 2}. Best is trial 0 with value: 0.5637651821862348.

Best trial: 0. Best value: 0.563765:  30%|███       | 15/50 [01:41<02:57,  5.06s/it]

[I 2025-12-02 01:15:18,894] Trial 15 pruned.

Best trial: 14. Best value: 0.57085:  32%|███▏      | 16/50 [01:44<02:32,  4.48s/it]

[I 2025-12-02 01:15:21,960] Trial 14 finished with value: 0.5708502024291497 and parameters: {'max_depth': 3, 'learning_rate': 0.028374391283892183, 'n_estimators': 455, 'subsample': 0.634929320929242, 'colsample_bytree': 0.9963218313366011, 'min_child_weight': 1, 'gamma': 2.867237732865379, 'reg_alpha': 0.36287476075561415, 'reg_lambda': 1.2529956356020802e-08, 'max_delta_step': 5}. Best is trial 14 with value: 0.5708502024291497.

Best trial: 14. Best value: 0.57085:  34%|███▍      | 17/50 [02:01<04:35,  8.35s/it]

[I 2025-12-02 01:15:39,619] Trial 19 pruned.

Best trial: 14. Best value: 0.57085:  36%|███▌      | 18/50 [02:06<03:50,  7.21s/it]

[I 2025-12-02 01:15:44,113] Trial 20 pruned.

Best trial: 14. Best value: 0.57085:  38%|███▊      | 19/50 [02:09<03:08,  6.07s/it]

[I 2025-12-02 01:15:47,486] Trial 21 pruned.

Best trial: 14. Best value: 0.57085:  40%|████      | 20/50 [02:14<02:46,  5.55s/it]

[I 2025-12-02 01:15:51,815] Trial 22 pruned.

Best trial: 14. Best value: 0.57085:  42%|████▏     | 21/50 [02:15<02:05,  4.33s/it]

[I 2025-12-02 01:15:53,268] Trial 16 finished with value: 0.5516194331983806 and parameters: {'max_depth': 3, 'learning_rate': 0.04942163461206712, 'n_estimators': 1405, 'subsample': 0.622074817274796, 'colsample_bytree': 0.9260187710973775, 'min_child_weight': 1, 'gamma': 3.1168115548367896, 'reg_alpha': 0.08364110865533513, 'reg_lambda': 2.3130634294782457e-08, 'max_delta_step': 4}. Best is trial 14 with value: 0.5708502024291497.

Best trial: 14. Best value: 0.57085:  44%|████▍     | 22/50 [02:23<02:29,  5.33s/it]

[I 2025-12-02 01:16:00,928] Trial 17 finished with value: 0.5516194331983806 and parameters: {'max_depth': 3, 'learning_rate': 0.05516837645396327, 'n_estimators': 1444, 'subsample': 0.6193777551512424, 'colsample_bytree': 0.9924680068845538, 'min_child_weight': 1, 'gamma': 2.8610756286360437, 'reg_alpha': 0.07112229531241834, 'reg_lambda': 1.3873913340979594e-08, 'max_delta_step': 4}. Best is trial 14 with value: 0.5708502024291497.

Best trial: 14. Best value: 0.57085:  46%|████▌     | 23/50 [02:24<01:54,  4.23s/it]

[I 2025-12-02 01:16:02,583] Trial 24 pruned.

Best trial: 18. Best value: 0.616397:  48%|████▊     | 24/50 [02:29<01:50,  4.26s/it]

[I 2025-12-02 01:16:06,934] Trial 18 finished with value: 0.6163967611336032 and parameters: {'max_depth': 3, 'learning_rate': 0.05609161776865764, 'n_estimators': 1448, 'subsample': 0.5090156480913205, 'colsample_bytree': 0.9890697134281698, 'min_child_weight': 1, 'gamma': 2.598127441866798, 'reg_alpha': 0.009794377231061724, 'reg_lambda': 8.858045412804994e-06, 'max_delta_step': 0}. Best is trial 18 with value: 0.6163967611336032.

Best trial: 18. Best value: 0.616397:  50%|█████     | 25/50 [02:31<01:34,  3.77s/it]

[I 2025-12-02 01:16:09,550] Trial 27 pruned.
[I 2025-12-02 01:16:09,563] Trial 26 pruned.

Best trial: 18. Best value: 0.616397:  54%|█████▍    | 27/50 [02:31<00:47,  2.08s/it]

[I 2025-12-02 01:16:09,745] Trial 25 pruned.

Best trial: 18. Best value: 0.616397:  56%|█████▌    | 28/50 [02:32<00:37,  1.69s/it]

[I 2025-12-02 01:16:10,272] Trial 23 finished with value: 0.5374493927125505 and parameters: {'max_depth': 8, 'learning_rate': 0.140311495530172, 'n_estimators': 356, 'subsample': 0.7794618037922814, 'colsample_bytree': 0.9268067663370395, 'min_child_weight': 1, 'gamma': 0.768726057641042, 'reg_alpha': 0.7477727471155934, 'reg_lambda': 1.0781673181922764, 'max_delta_step': 6}. Best is trial 18 with value: 0.6163967611336032.

Best trial: 18. Best value: 0.616397:  58%|█████▊    | 29/50 [02:37<00:54,  2.60s/it]

[I 2025-12-02 01:16:15,429] Trial 30 pruned.

Best trial: 18. Best value: 0.616397:  60%|██████    | 30/50 [02:38<00:40,  2.01s/it]

[I 2025-12-02 01:16:15,873] Trial 31 pruned.

Best trial: 18. Best value: 0.616397:  62%|██████▏   | 31/50 [02:41<00:45,  2.40s/it]

[I 2025-12-02 01:16:19,282] Trial 32 pruned.

Best trial: 18. Best value: 0.616397:  64%|██████▍   | 32/50 [02:51<01:22,  4.59s/it]

[I 2025-12-02 01:16:29,333] Trial 34 pruned.

Best trial: 18. Best value: 0.616397:  66%|██████▌   | 33/50 [02:58<01:30,  5.34s/it]

[I 2025-12-02 01:16:36,505] Trial 33 finished with value: 0.513157894736842 and parameters: {'max_depth': 7, 'learning_rate': 0.038727472903931, 'n_estimators': 593, 'subsample': 0.5815563248501427, 'colsample_bytree': 0.5167332240727885, 'min_child_weight': 1, 'gamma': 2.361696034017338, 'reg_alpha': 0.00016080473752489826, 'reg_lambda': 0.01309252593471063, 'max_delta_step': 3}. Best is trial 18 with value: 0.6163967611336032.

Best trial: 18. Best value: 0.616397:  68%|██████▊   | 34/50 [03:01<01:15,  4.69s/it]

[I 2025-12-02 01:16:39,640] Trial 35 pruned.
[I 2025-12-02 01:16:39,651] Trial 29 finished with value: 0.5253036437246963 and parameters: {'max_depth': 4, 'learning_rate': 0.07193959754196812, 'n_estimators': 734, 'subsample': 0.7830235015909601, 'colsample_bytree': 0.8426094068597674, 'min_child_weight': 1, 'gamma': 1.4457140901680672, 'reg_alpha': 0.583780250270876, 'reg_lambda': 0.00313346478452055, 'max_delta_step': 1}. Best is trial 18 with value: 0.6163967611336032.

Best trial: 18. Best value: 0.616397:  72%|███████▏  | 36/50 [03:10<01:02,  4.48s/it]

[I 2025-12-02 01:16:48,094] Trial 37 pruned.

Best trial: 18. Best value: 0.616397:  74%|███████▍  | 37/50 [03:11<00:46,  3.61s/it]

[I 2025-12-02 01:16:49,012] Trial 38 pruned.

Best trial: 18. Best value: 0.616397:  76%|███████▌  | 38/50 [03:14<00:43,  3.59s/it]

[I 2025-12-02 01:16:52,565] Trial 28 finished with value: 0.5253036437246963 and parameters: {'max_depth': 4, 'learning_rate': 0.07492606060810025, 'n_estimators': 1088, 'subsample': 0.7867752539575007, 'colsample_bytree': 0.8438434413234838, 'min_child_weight': 1, 'gamma': 1.4989260262711395, 'reg_alpha': 0.26601127442839995, 'reg_lambda': 0.0023726751852566432, 'max_delta_step': 1}. Best is trial 18 with value: 0.6163967611336032.

Best trial: 18. Best value: 0.616397:  78%|███████▊  | 39/50 [03:16<00:34,  3.16s/it]

[I 2025-12-02 01:16:54,580] Trial 40 pruned.

Best trial: 18. Best value: 0.616397:  80%|████████  | 40/50 [03:25<00:46,  4.69s/it]

[I 2025-12-02 01:17:03,232] Trial 41 pruned.

Best trial: 18. Best value: 0.616397:  82%|████████▏ | 41/50 [03:27<00:36,  4.02s/it]

[I 2025-12-02 01:17:05,560] Trial 42 pruned.

Best trial: 18. Best value: 0.616397:  84%|████████▍ | 42/50 [03:32<00:34,  4.37s/it]

[I 2025-12-02 01:17:10,782] Trial 43 pruned.

Best trial: 18. Best value: 0.616397:  86%|████████▌ | 43/50 [03:39<00:34,  4.90s/it]

[I 2025-12-02 01:17:16,971] Trial 45 pruned.

Best trial: 18. Best value: 0.616397:  88%|████████▊ | 44/50 [03:46<00:33,  5.53s/it]

[I 2025-12-02 01:17:24,002] Trial 36 finished with value: 0.5637651821862348 and parameters: {'max_depth': 3, 'learning_rate': 0.028822880765955697, 'n_estimators': 1285, 'subsample': 0.5381791340425723, 'colsample_bytree': 0.9724476990837753, 'min_child_weight': 2, 'gamma': 1.7142423388875823, 'reg_alpha': 0.03679064159605348, 'reg_lambda': 6.965775433227084e-07, 'max_delta_step': 9}. Best is trial 18 with value: 0.6163967611336032.

Best trial: 18. Best value: 0.616397:  90%|█████████ | 45/50 [03:51<00:27,  5.46s/it]

[I 2025-12-02 01:17:29,291] Trial 47 pruned.

Best trial: 18. Best value: 0.616397:  92%|█████████▏| 46/50 [03:55<00:19,  4.96s/it]

[I 2025-12-02 01:17:33,078] Trial 39 finished with value: 0.590080971659919 and parameters: {'max_depth': 3, 'learning_rate': 0.10281085186558453, 'n_estimators': 1287, 'subsample': 0.5366228945589707, 'colsample_bytree': 0.8762043569214424, 'min_child_weight': 2, 'gamma': 1.7954154317528772, 'reg_alpha': 3.1051613750713966e-05, 'reg_lambda': 8.760922867539122e-07, 'max_delta_step': 9}. Best is trial 18 with value: 0.6163967611336032.

Best trial: 18. Best value: 0.616397:  94%|█████████▍| 47/50 [03:56<00:11,  3.90s/it]

[I 2025-12-02 01:17:34,472] Trial 48 pruned.

Best trial: 18. Best value: 0.616397:  96%|█████████▌| 48/50 [03:57<00:06,  3.08s/it]

[I 2025-12-02 01:17:35,632] Trial 46 finished with value: 0.5637651821862348 and parameters: {'max_depth': 5, 'learning_rate': 0.014500193747390921, 'n_estimators': 489, 'subsample': 0.9478258015408194, 'colsample_bytree': 0.6715271109870568, 'min_child_weight': 4, 'gamma': 0.8587857434414792, 'reg_alpha': 1.7810873925102378e-06, 'reg_lambda': 4.408331513158119e-06, 'max_delta_step': 9}. Best is trial 18 with value: 0.6163967611336032.

Best trial: 18. Best value: 0.616397:  98%|█████████▊| 49/50 [03:59<00:02,  2.68s/it]

[I 2025-12-02 01:17:37,389] Trial 44 finished with value: 0.5637651821862348 and parameters: {'max_depth': 9, 'learning_rate': 0.010070571669147732, 'n_estimators': 932, 'subsample': 0.931164822477863, 'colsample_bytree': 0.68495494250321, 'min_child_weight': 4, 'gamma': 0.01076171664044856, 'reg_alpha': 2.73064021822175e-06, 'reg_lambda': 1.4612537086135618e-06, 'max_delta_step': 10}. Best is trial 18 with value: 0.6163967611336032.

Best trial: 18. Best value: 0.616397: 100%|██████████| 50/50 [04:02<00:00,  4.85s/it]

[I 2025-12-02 01:17:40,098] Trial 49 pruned.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 01:17:45,820] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 43, Test size: 11
Using Leave-One-Out CV with 43 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.371711:   2%|▏         | 1/50 [00:38<31:42, 38.82s/it]

[I 2025-12-02 01:18:24,614] Trial 1 finished with value: 0.3717105263157895 and parameters: {'max_depth': 9, 'learning_rate': 0.05517986262632772, 'n_estimators': 1152, 'subsample': 0.698534602790991, 'colsample_bytree': 0.8172809240512255, 'min_child_weight': 3, 'gamma': 2.3995597849598367, 'reg_alpha': 0.06761285340687112, 'reg_lambda': 3.3037378426100417e-06, 'max_delta_step': 2}. Best is trial 1 with value: 0.3717105263157895.

Best trial: 1. Best value: 0.371711:   4%|▍         | 2/50 [00:44<15:21, 19.19s/it]

[I 2025-12-02 01:18:30,091] Trial 0 finished with value: 0.020833333333333332 and parameters: {'max_depth': 8, 'learning_rate': 0.04811398498511389, 'n_estimators': 1347, 'subsample': 0.8569381082926486, 'colsample_bytree': 0.7976582626098797, 'min_child_weight': 7, 'gamma': 0.925495589108718, 'reg_alpha': 0.002079567933800458, 'reg_lambda': 1.3867557979080687e-08, 'max_delta_step': 1}. Best is trial 1 with value: 0.3717105263157895.
[I 2025-12-02 01:18:30,121] Trial 3 finished with value: 0.3508771929824561 and parameters: {'max_depth': 6, 'learning_rate': 0.017195219532195456, 'n_estimators': 1252, 'subsample': 0.7133996276460417, 'colsample_bytree': 0.5663577940786457, 'min_child_weight': 3, 'gamma': 0.10838025015049713, 'reg_alpha': 0.00046903212112863645, 'reg_lambda': 0.18516663417192725, 'max_delta_step': 2}. Best is trial 1 with value: 0.3717105263157895.

Best trial: 1. Best value: 0.371711:   8%|▊         | 4/50 [00:47<06:22,  8.31s/it]

[I 2025-12-02 01:18:33,769] Trial 2 finished with value: 0.36622807017543857 and parameters: {'max_depth': 6, 'learning_rate': 0.018869919351581624, 'n_estimators': 1378, 'subsample': 0.9306024684266812, 'colsample_bytree': 0.9654372666549498, 'min_child_weight': 4, 'gamma': 2.434808092169047, 'reg_alpha': 0.037705719947654204, 'reg_lambda': 3.3132146237560426e-05, 'max_delta_step': 8}. Best is trial 1 with value: 0.3717105263157895.

Best trial: 6. Best value: 0.387061:  10%|█         | 5/50 [01:04<08:07, 10.83s/it]

[I 2025-12-02 01:18:50,232] Trial 6 finished with value: 0.38706140350877194 and parameters: {'max_depth': 7, 'learning_rate': 0.05640756367594463, 'n_estimators': 500, 'subsample': 0.9046958132933702, 'colsample_bytree': 0.8781835933139147, 'min_child_weight': 3, 'gamma': 0.39892257784655993, 'reg_alpha': 0.45580441084591006, 'reg_lambda': 0.2931881594794185, 'max_delta_step': 8}. Best is trial 6 with value: 0.38706140350877194.

Best trial: 7. Best value: 0.407895:  12%|█▏        | 6/50 [01:08<06:23,  8.72s/it]

[I 2025-12-02 01:18:54,184] Trial 7 finished with value: 0.40789473684210525 and parameters: {'max_depth': 3, 'learning_rate': 0.16069072303197865, 'n_estimators': 535, 'subsample': 0.9312521993399555, 'colsample_bytree': 0.6908760677800034, 'min_child_weight': 2, 'gamma': 1.5972443930449969, 'reg_alpha': 1.0397408630505222e-05, 'reg_lambda': 7.934705907800189e-08, 'max_delta_step': 4}. Best is trial 7 with value: 0.40789473684210525.

Best trial: 7. Best value: 0.407895:  14%|█▍        | 7/50 [01:13<05:25,  7.56s/it]

[I 2025-12-02 01:18:59,099] Trial 4 finished with value: 0.3300438596491228 and parameters: {'max_depth': 9, 'learning_rate': 0.06096464285916049, 'n_estimators': 1011, 'subsample': 0.8462581754584347, 'colsample_bytree': 0.7518583692385064, 'min_child_weight': 3, 'gamma': 0.7988552210921218, 'reg_alpha': 1.3990531061869454e-05, 'reg_lambda': 8.220380240387183e-07, 'max_delta_step': 10}. Best is trial 7 with value: 0.40789473684210525.

Best trial: 7. Best value: 0.407895:  16%|█▌        | 8/50 [01:13<03:49,  5.46s/it]

[I 2025-12-02 01:18:59,718] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.06785996270284361, 'n_estimators': 216, 'subsample': 0.7791822509320989, 'colsample_bytree': 0.8769801924808163, 'min_child_weight': 6, 'gamma': 4.982461610746104, 'reg_alpha': 0.12349801698631195, 'reg_lambda': 9.781287040697785e-07, 'max_delta_step': 7}. Best is trial 7 with value: 0.40789473684210525.

Best trial: 7. Best value: 0.407895:  18%|█▊        | 9/50 [01:18<03:29,  5.11s/it]

[I 2025-12-02 01:19:04,037] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.04151564056255102, 'n_estimators': 1083, 'subsample': 0.8676340069697844, 'colsample_bytree': 0.6022210525379266, 'min_child_weight': 8, 'gamma': 3.060554688388901, 'reg_alpha': 0.0009315355312657851, 'reg_lambda': 8.358452284144926e-08, 'max_delta_step': 1}. Best is trial 7 with value: 0.40789473684210525.

Best trial: 7. Best value: 0.407895:  20%|██        | 10/50 [01:38<06:22,  9.57s/it]

[I 2025-12-02 01:19:23,943] Trial 12 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.014542556808439567, 'n_estimators': 531, 'subsample': 0.9530991077495617, 'colsample_bytree': 0.825108716196435, 'min_child_weight': 9, 'gamma': 4.731638980863169, 'reg_alpha': 5.368993518546756e-06, 'reg_lambda': 0.0005820934140928575, 'max_delta_step': 2}. Best is trial 7 with value: 0.40789473684210525.

Best trial: 7. Best value: 0.407895:  22%|██▏       | 11/50 [01:39<04:39,  7.17s/it]

[I 2025-12-02 01:19:25,512] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.11724630921677506, 'n_estimators': 895, 'subsample': 0.9124681039495008, 'colsample_bytree': 0.5223820272265669, 'min_child_weight': 10, 'gamma': 0.5929602254585703, 'reg_alpha': 2.0745815835556526e-06, 'reg_lambda': 0.0014364721150198268, 'max_delta_step': 4}. Best is trial 7 with value: 0.40789473684210525.

Best trial: 7. Best value: 0.407895:  24%|██▍       | 12/50 [01:43<03:55,  6.21s/it]

[I 2025-12-02 01:19:29,504] Trial 10 pruned.

Best trial: 7. Best value: 0.407895:  26%|██▌       | 13/50 [01:44<02:48,  4.55s/it]

[I 2025-12-02 01:19:30,195] Trial 11 pruned.

Best trial: 7. Best value: 0.407895:  28%|██▊       | 14/50 [01:44<02:00,  3.36s/it]

[I 2025-12-02 01:19:30,778] Trial 14 pruned.

Best trial: 7. Best value: 0.407895:  30%|███       | 15/50 [01:48<02:00,  3.44s/it]

[I 2025-12-02 01:19:34,415] Trial 15 pruned.

Best trial: 7. Best value: 0.407895:  32%|███▏      | 16/50 [01:49<01:26,  2.55s/it]

[I 2025-12-02 01:19:34,882] Trial 16 pruned.

Best trial: 7. Best value: 0.407895:  34%|███▍      | 17/50 [01:51<01:19,  2.40s/it]

[I 2025-12-02 01:19:36,933] Trial 18 pruned.

Best trial: 7. Best value: 0.407895:  36%|███▌      | 18/50 [01:52<01:07,  2.10s/it]

[I 2025-12-02 01:19:38,336] Trial 19 pruned.

Best trial: 13. Best value: 0.528509:  38%|███▊      | 19/50 [02:01<02:12,  4.28s/it]

[I 2025-12-02 01:19:47,691] Trial 13 finished with value: 0.5285087719298246 and parameters: {'max_depth': 3, 'learning_rate': 0.20354505404001788, 'n_estimators': 716, 'subsample': 0.5520993223631248, 'colsample_bytree': 0.6541110309934457, 'min_child_weight': 1, 'gamma': 1.4765629495510217, 'reg_alpha': 1.6683431487739477e-08, 'reg_lambda': 0.0023676439853625173, 'max_delta_step': 4}. Best is trial 13 with value: 0.5285087719298246.

Best trial: 13. Best value: 0.528509:  40%|████      | 20/50 [02:06<02:13,  4.46s/it]

[I 2025-12-02 01:19:52,569] Trial 22 pruned.

Best trial: 13. Best value: 0.528509:  42%|████▏     | 21/50 [02:08<01:46,  3.66s/it]

[I 2025-12-02 01:19:54,364] Trial 17 finished with value: 0.4396929824561403 and parameters: {'max_depth': 5, 'learning_rate': 0.17970120506474052, 'n_estimators': 590, 'subsample': 0.9870135763852951, 'colsample_bytree': 0.6863058817704171, 'min_child_weight': 1, 'gamma': 1.6471665594100295, 'reg_alpha': 5.298879547623147e-08, 'reg_lambda': 0.03010461198540572, 'max_delta_step': 7}. Best is trial 13 with value: 0.5285087719298246.

Best trial: 13. Best value: 0.528509:  44%|████▍     | 22/50 [02:12<01:47,  3.85s/it]

[I 2025-12-02 01:19:58,675] Trial 23 pruned.

Best trial: 13. Best value: 0.528509:  46%|████▌     | 23/50 [02:14<01:25,  3.18s/it]

[I 2025-12-02 01:20:00,274] Trial 24 pruned.

Best trial: 13. Best value: 0.528509:  48%|████▊     | 24/50 [02:14<01:01,  2.38s/it]

[I 2025-12-02 01:20:00,803] Trial 20 finished with value: 0.41885964912280704 and parameters: {'max_depth': 7, 'learning_rate': 0.1558122416273941, 'n_estimators': 714, 'subsample': 0.7868459476645682, 'colsample_bytree': 0.7394737929470625, 'min_child_weight': 2, 'gamma': 0.1561481846477344, 'reg_alpha': 1.0474008966838494e-07, 'reg_lambda': 0.12311681931779878, 'max_delta_step': 9}. Best is trial 13 with value: 0.5285087719298246.

Best trial: 13. Best value: 0.528509:  50%|█████     | 25/50 [02:18<01:06,  2.65s/it]

[I 2025-12-02 01:20:04,076] Trial 26 pruned.

Best trial: 13. Best value: 0.528509:  52%|█████▏    | 26/50 [02:18<00:47,  1.98s/it]

[I 2025-12-02 01:20:04,504] Trial 25 pruned.

Best trial: 13. Best value: 0.528509:  54%|█████▍    | 27/50 [02:21<00:50,  2.21s/it]

[I 2025-12-02 01:20:07,241] Trial 21 finished with value: 0.481359649122807 and parameters: {'max_depth': 7, 'learning_rate': 0.02635870221307507, 'n_estimators': 732, 'subsample': 0.7721998316060856, 'colsample_bytree': 0.737407114766238, 'min_child_weight': 2, 'gamma': 3.6278727312258443, 'reg_alpha': 9.996054107959309e-05, 'reg_lambda': 0.34226967978560185, 'max_delta_step': 4}. Best is trial 13 with value: 0.5285087719298246.

Best trial: 13. Best value: 0.528509:  56%|█████▌    | 28/50 [02:24<00:54,  2.47s/it]

[I 2025-12-02 01:20:10,310] Trial 28 pruned.

Best trial: 13. Best value: 0.528509:  58%|█████▊    | 29/50 [02:27<00:58,  2.77s/it]

[I 2025-12-02 01:20:13,783] Trial 30 pruned.

Best trial: 13. Best value: 0.528509:  60%|██████    | 30/50 [02:31<00:57,  2.85s/it]

[I 2025-12-02 01:20:16,826] Trial 31 pruned.

Best trial: 13. Best value: 0.528509:  62%|██████▏   | 31/50 [02:31<00:43,  2.27s/it]

[I 2025-12-02 01:20:17,730] Trial 27 finished with value: 0.47039473684210525 and parameters: {'max_depth': 8, 'learning_rate': 0.21562784751221845, 'n_estimators': 372, 'subsample': 0.6415863597194862, 'colsample_bytree': 0.7417317875641669, 'min_child_weight': 1, 'gamma': 2.8761873805600313, 'reg_alpha': 1.0393772425904561e-08, 'reg_lambda': 0.34827437390875393, 'max_delta_step': 9}. Best is trial 13 with value: 0.5285087719298246.

Best trial: 13. Best value: 0.528509:  64%|██████▍   | 32/50 [02:40<01:13,  4.06s/it]

[I 2025-12-02 01:20:25,983] Trial 32 pruned.

Best trial: 13. Best value: 0.528509:  66%|██████▌   | 33/50 [02:45<01:14,  4.36s/it]

[I 2025-12-02 01:20:31,020] Trial 29 finished with value: 0.38706140350877194 and parameters: {'max_depth': 7, 'learning_rate': 0.10706338197503502, 'n_estimators': 831, 'subsample': 0.7197147199580703, 'colsample_bytree': 0.7509404633775616, 'min_child_weight': 4, 'gamma': 1.9943857167629733, 'reg_alpha': 7.168646907051658e-07, 'reg_lambda': 0.059880460914053836, 'max_delta_step': 9}. Best is trial 13 with value: 0.5285087719298246.

Best trial: 34. Best value: 0.554825:  68%|██████▊   | 34/50 [02:53<01:26,  5.40s/it]

[I 2025-12-02 01:20:38,859] Trial 34 finished with value: 0.5548245614035088 and parameters: {'max_depth': 8, 'learning_rate': 0.21139185832268792, 'n_estimators': 636, 'subsample': 0.5558111788442293, 'colsample_bytree': 0.6905420593541449, 'min_child_weight': 1, 'gamma': 3.4269960193819666, 'reg_alpha': 2.809855849299671e-08, 'reg_lambda': 0.025235530548627462, 'max_delta_step': 0}. Best is trial 34 with value: 0.5548245614035088.

Best trial: 34. Best value: 0.554825:  70%|███████   | 35/50 [03:01<01:33,  6.23s/it]

[I 2025-12-02 01:20:47,019] Trial 35 finished with value: 0.5493421052631579 and parameters: {'max_depth': 8, 'learning_rate': 0.21054121207312, 'n_estimators': 636, 'subsample': 0.5571497040446406, 'colsample_bytree': 0.7029810206857644, 'min_child_weight': 1, 'gamma': 3.6433502984437314, 'reg_alpha': 3.485084935918722e-08, 'reg_lambda': 0.02304128092514482, 'max_delta_step': 9}. Best is trial 34 with value: 0.5548245614035088.

Best trial: 34. Best value: 0.554825:  72%|███████▏  | 36/50 [03:05<01:17,  5.57s/it]

[I 2025-12-02 01:20:51,054] Trial 37 finished with value: 0.48574561403508776 and parameters: {'max_depth': 8, 'learning_rate': 0.2318815887752422, 'n_estimators': 316, 'subsample': 0.5393179477106972, 'colsample_bytree': 0.7090943323853416, 'min_child_weight': 1, 'gamma': 3.690130841310825, 'reg_alpha': 0.005034202007625284, 'reg_lambda': 0.011076228258633978, 'max_delta_step': 0}. Best is trial 34 with value: 0.5548245614035088.

Best trial: 36. Best value: 0.596491:  76%|███████▌  | 38/50 [03:06<00:36,  3.04s/it]

[I 2025-12-02 01:20:52,352] Trial 36 finished with value: 0.5964912280701754 and parameters: {'max_depth': 8, 'learning_rate': 0.21049702540231816, 'n_estimators': 626, 'subsample': 0.5561529415356945, 'colsample_bytree': 0.7099153341108246, 'min_child_weight': 1, 'gamma': 3.5228524804978814, 'reg_alpha': 3.4279973626224575e-08, 'reg_lambda': 0.026444686407434845, 'max_delta_step': 5}. Best is trial 36 with value: 0.5964912280701754.
[I 2025-12-02 01:20:52,466] Trial 38 pruned.

Best trial: 36. Best value: 0.596491:  78%|███████▊  | 39/50 [03:10<00:35,  3.26s/it]

[I 2025-12-02 01:20:56,259] Trial 41 pruned.

Best trial: 36. Best value: 0.596491:  80%|████████  | 40/50 [03:11<00:26,  2.60s/it]

[I 2025-12-02 01:20:57,318] Trial 40 pruned.

Best trial: 36. Best value: 0.596491:  82%|████████▏ | 41/50 [03:15<00:26,  3.00s/it]

[I 2025-12-02 01:21:01,238] Trial 39 finished with value: 0.46600877192982454 and parameters: {'max_depth': 8, 'learning_rate': 0.23416024420072212, 'n_estimators': 289, 'subsample': 0.5370401951240718, 'colsample_bytree': 0.6397794596055274, 'min_child_weight': 3, 'gamma': 3.5326397989141456, 'reg_alpha': 0.008538687446700157, 'reg_lambda': 0.011223561722103086, 'max_delta_step': 0}. Best is trial 36 with value: 0.5964912280701754.

Best trial: 36. Best value: 0.596491:  84%|████████▍ | 42/50 [03:18<00:25,  3.15s/it]

[I 2025-12-02 01:21:04,727] Trial 43 pruned.

Best trial: 36. Best value: 0.596491:  86%|████████▌ | 43/50 [03:19<00:16,  2.30s/it]

[I 2025-12-02 01:21:05,056] Trial 42 pruned.

Best trial: 36. Best value: 0.596491:  88%|████████▊ | 44/50 [03:24<00:19,  3.20s/it]

[I 2025-12-02 01:21:10,361] Trial 44 pruned.

Best trial: 36. Best value: 0.596491:  90%|█████████ | 45/50 [03:28<00:16,  3.36s/it]

[I 2025-12-02 01:21:14,097] Trial 47 pruned.

Best trial: 36. Best value: 0.596491:  94%|█████████▍| 47/50 [03:30<00:06,  2.15s/it]

[I 2025-12-02 01:21:16,314] Trial 45 finished with value: 0.5701754385964912 and parameters: {'max_depth': 9, 'learning_rate': 0.2150730635112624, 'n_estimators': 308, 'subsample': 0.6013473382721946, 'colsample_bytree': 0.7153890269856749, 'min_child_weight': 1, 'gamma': 3.887100043146359, 'reg_alpha': 0.0017239944568232298, 'reg_lambda': 0.002278162130319529, 'max_delta_step': 2}. Best is trial 36 with value: 0.5964912280701754.
[I 2025-12-02 01:21:16,419] Trial 33 finished with value: 0.5285087719298246 and parameters: {'max_depth': 8, 'learning_rate': 0.01155327587667275, 'n_estimators': 1461, 'subsample': 0.811591185126401, 'colsample_bytree': 0.7075936683814791, 'min_child_weight': 1, 'gamma': 2.831082176389993, 'reg_alpha': 3.6242318623422804e-08, 'reg_lambda': 0.026651980941279227, 'max_delta_step': 5}. Best is trial 36 with value: 0.5964912280701754.

Best trial: 36. Best value: 0.596491:  96%|█████████▌| 48/50 [03:35<00:05,  2.82s/it]

[I 2025-12-02 01:21:20,827] Trial 46 finished with value: 0.5394736842105263 and parameters: {'max_depth': 8, 'learning_rate': 0.28623288938197955, 'n_estimators': 463, 'subsample': 0.6078809818152592, 'colsample_bytree': 0.7037662219063024, 'min_child_weight': 1, 'gamma': 3.9451064566287295, 'reg_alpha': 0.0005831168218484056, 'reg_lambda': 0.022597165950421175, 'max_delta_step': 2}. Best is trial 36 with value: 0.5964912280701754.

Best trial: 36. Best value: 0.596491:  98%|█████████▊| 49/50 [03:45<00:05,  5.06s/it]

[I 2025-12-02 01:21:31,097] Trial 49 finished with value: 0.5230263157894737 and parameters: {'max_depth': 10, 'learning_rate': 0.2870707565240647, 'n_estimators': 667, 'subsample': 0.609550138808012, 'colsample_bytree': 0.8027034552589916, 'min_child_weight': 1, 'gamma': 4.447717473563396, 'reg_alpha': 8.965856396840799e-08, 'reg_lambda': 0.0003264215784784723, 'max_delta_step': 2}. Best is trial 36 with value: 0.5964912280701754.

Best trial: 36. Best value: 0.596491: 100%|██████████| 50/50 [03:51<00:00,  4.63s/it]

[I 2025-12-02 01:21:37,247] Trial 48 finished with value: 0.5493421052631579 and parameters: {'max_depth': 6, 'learning_rate': 0.2941226008018342, 'n_estimators': 1070, 'subsample': 0.6127938225118442, 'colsample_bytree': 0.7739479982377749, 'min_child_weight': 1, 'gamma': 4.54909117388542, 'reg_alpha': 0.2602487393312263, 'reg_lambda': 1.1795020443927985e-05, 'max_delta_step': 0}. Best is trial 36 with value: 0.5964912280701754.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.711670                0.716667      0.700000
1    19_1         loo       0.596491                0.633333      0.700000
2    15_1         loo       0.609474                0.542857      0.428571
3    17_1         loo       0.616397                0.485714      0.485714

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.448543          0.833333               0.6        50          42
1  0.266667          0.666667               0.6        50          43
2  0.097590          0.285714               0.8        50          44
3 -0.028571          0.571429               0.4        50          45

   test_size
0         11
1         11
2         12
3         12
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.711670                0.716667      0.700000
1    19_1         loo       0.596491                0.633333      0.700000
2    15_1         loo       0.609474                0.542857      0.428571
3    17_1         loo       0.616397                0.485714      0.485714

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.448543          0.833333               0.6        50          42
1  0.266667          0.666667               0.6        50          43
2  0.097590          0.285714               0.8        50          44
3 -0.028571          0.571429               0.4        50          45

   test_size
0         11
1         11
2         12
3         12

In [ ]:

# Temporal embedings
datasets = task_temp_dfs_ad_lbd

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    #    scoring="balanced_accuracy",     # or "roc_auc"
    scoring="balanced_accuracy",      
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_lbd_{CV_STRATEGY}_tasks/xgb_results_temporal_ad_lbd_extended_{CV_STRATEGY}_tasks",
    split_param="emb_",
)
print(summary)

[I 2025-12-02 01:21:40,557] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 42, Test size: 11
Using Leave-One-Out CV with 42 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.379863:   2%|▏         | 1/50 [00:09<07:47,  9.54s/it]

[I 2025-12-02 01:21:50,085] Trial 0 finished with value: 0.37986270022883295 and parameters: {'max_depth': 9, 'learning_rate': 0.25889616070396065, 'n_estimators': 217, 'subsample': 0.9391443527841521, 'colsample_bytree': 0.5136830606882017, 'min_child_weight': 3, 'gamma': 2.5829820352617574, 'reg_alpha': 1.816517552080592, 'reg_lambda': 0.00827454827479826, 'max_delta_step': 9}. Best is trial 0 with value: 0.37986270022883295.

Best trial: 0. Best value: 0.379863:   4%|▍         | 2/50 [00:12<04:25,  5.54s/it]

[I 2025-12-02 01:21:52,820] Trial 3 finished with value: 0.021739130434782608 and parameters: {'max_depth': 7, 'learning_rate': 0.2360824104690861, 'n_estimators': 312, 'subsample': 0.8469264360510406, 'colsample_bytree': 0.5047821158444724, 'min_child_weight': 7, 'gamma': 1.3635488020754543, 'reg_alpha': 1.332645764600795e-07, 'reg_lambda': 2.094526500864473e-06, 'max_delta_step': 3}. Best is trial 0 with value: 0.37986270022883295.

Best trial: 0. Best value: 0.379863:   6%|▌         | 3/50 [00:23<06:30,  8.30s/it]

[I 2025-12-02 01:22:04,408] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.17413929218576588, 'n_estimators': 706, 'subsample': 0.6568155033814157, 'colsample_bytree': 0.7240718713174101, 'min_child_weight': 5, 'gamma': 2.087015491135606, 'reg_alpha': 7.72359103592002e-06, 'reg_lambda': 0.06708889745383481, 'max_delta_step': 9}. Best is trial 0 with value: 0.37986270022883295.

Best trial: 0. Best value: 0.379863:   8%|▊         | 4/50 [00:44<10:06, 13.18s/it]

[I 2025-12-02 01:22:25,081] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.019223454136083718, 'n_estimators': 1335, 'subsample': 0.9156784555647132, 'colsample_bytree': 0.7475195796026113, 'min_child_weight': 10, 'gamma': 1.512626864973431, 'reg_alpha': 6.407526978403091e-06, 'reg_lambda': 2.0521067874164183e-06, 'max_delta_step': 0}. Best is trial 0 with value: 0.37986270022883295.

Best trial: 0. Best value: 0.379863:  10%|█         | 5/50 [00:48<07:28,  9.96s/it]

[I 2025-12-02 01:22:29,337] Trial 4 finished with value: 0.3707093821510298 and parameters: {'max_depth': 6, 'learning_rate': 0.04399995135672805, 'n_estimators': 1034, 'subsample': 0.7983908833861425, 'colsample_bytree': 0.5274354096625291, 'min_child_weight': 1, 'gamma': 1.089587259547946, 'reg_alpha': 2.6160491219091342e-06, 'reg_lambda': 1.4433514361150483e-06, 'max_delta_step': 10}. Best is trial 0 with value: 0.37986270022883295.

Best trial: 0. Best value: 0.379863:  12%|█▏        | 6/50 [00:49<05:00,  6.83s/it]

[I 2025-12-02 01:22:30,070] Trial 5 finished with value: 0.37986270022883295 and parameters: {'max_depth': 7, 'learning_rate': 0.23264873573167894, 'n_estimators': 1187, 'subsample': 0.7001430892263061, 'colsample_bytree': 0.5505365862967893, 'min_child_weight': 3, 'gamma': 2.6291976857615817, 'reg_alpha': 0.0266458482052472, 'reg_lambda': 5.301235313160675e-06, 'max_delta_step': 0}. Best is trial 0 with value: 0.37986270022883295.

Best trial: 0. Best value: 0.379863:  14%|█▍        | 7/50 [01:08<07:40, 10.71s/it]

[I 2025-12-02 01:22:48,768] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.020248177943549984, 'n_estimators': 723, 'subsample': 0.9438468244266076, 'colsample_bytree': 0.5263478368935328, 'min_child_weight': 6, 'gamma': 2.094935928217056, 'reg_alpha': 7.190615061012183e-06, 'reg_lambda': 7.406324387016671e-08, 'max_delta_step': 2}. Best is trial 0 with value: 0.37986270022883295.

Best trial: 0. Best value: 0.379863:  16%|█▌        | 8/50 [01:12<06:02,  8.64s/it]

[I 2025-12-02 01:22:52,990] Trial 6 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.1871164346149577, 'n_estimators': 1468, 'subsample': 0.8327998730457262, 'colsample_bytree': 0.9953800869818761, 'min_child_weight': 10, 'gamma': 4.832394898583999, 'reg_alpha': 0.0716907601876959, 'reg_lambda': 0.03112459249383223, 'max_delta_step': 7}. Best is trial 0 with value: 0.37986270022883295.

Best trial: 0. Best value: 0.379863:  18%|█▊        | 9/50 [01:28<07:32, 11.04s/it]

[I 2025-12-02 01:23:09,291] Trial 8 finished with value: 0.07894736842105263 and parameters: {'max_depth': 9, 'learning_rate': 0.19029480238316082, 'n_estimators': 1173, 'subsample': 0.5059334088333716, 'colsample_bytree': 0.9206605641999255, 'min_child_weight': 7, 'gamma': 0.6770292189671534, 'reg_alpha': 0.01769502496944361, 'reg_lambda': 5.119777816329322e-06, 'max_delta_step': 4}. Best is trial 0 with value: 0.37986270022883295.

Best trial: 0. Best value: 0.379863:  20%|██        | 10/50 [01:29<05:16,  7.92s/it]

[I 2025-12-02 01:23:10,241] Trial 9 finished with value: 0.35812356979405036 and parameters: {'max_depth': 3, 'learning_rate': 0.018481146126494888, 'n_estimators': 1168, 'subsample': 0.5991844811079692, 'colsample_bytree': 0.7528730925295377, 'min_child_weight': 3, 'gamma': 4.209800315496127, 'reg_alpha': 0.5497029483628759, 'reg_lambda': 2.5917865034073655, 'max_delta_step': 8}. Best is trial 0 with value: 0.37986270022883295.

Best trial: 0. Best value: 0.379863:  22%|██▏       | 11/50 [01:30<03:41,  5.68s/it]

[I 2025-12-02 01:23:10,824] Trial 11 pruned.

Best trial: 0. Best value: 0.379863:  24%|██▍       | 12/50 [01:31<02:44,  4.33s/it]

[I 2025-12-02 01:23:12,066] Trial 10 pruned.

Best trial: 0. Best value: 0.379863:  26%|██▌       | 13/50 [01:34<02:26,  3.95s/it]

[I 2025-12-02 01:23:15,153] Trial 14 pruned.

Best trial: 0. Best value: 0.379863:  28%|██▊       | 14/50 [01:39<02:35,  4.32s/it]

[I 2025-12-02 01:23:20,313] Trial 13 finished with value: 0.20022883295194507 and parameters: {'max_depth': 10, 'learning_rate': 0.08676088054244062, 'n_estimators': 235, 'subsample': 0.9531570470405025, 'colsample_bytree': 0.6434208546885171, 'min_child_weight': 2, 'gamma': 3.4444334163632635, 'reg_alpha': 3.243519305975069, 'reg_lambda': 0.0009635010930695517, 'max_delta_step': 6}. Best is trial 0 with value: 0.37986270022883295.

Best trial: 0. Best value: 0.379863:  30%|███       | 15/50 [01:40<01:57,  3.35s/it]

[I 2025-12-02 01:23:21,428] Trial 15 finished with value: 0.3226544622425629 and parameters: {'max_depth': 9, 'learning_rate': 0.09845018734286777, 'n_estimators': 224, 'subsample': 0.7145999158944081, 'colsample_bytree': 0.6158127079607463, 'min_child_weight': 2, 'gamma': 3.1981156296008884, 'reg_alpha': 0.006260245729917681, 'reg_lambda': 0.001349915937163845, 'max_delta_step': 6}. Best is trial 0 with value: 0.37986270022883295.

Best trial: 0. Best value: 0.379863:  32%|███▏      | 16/50 [01:46<02:13,  3.94s/it]

[I 2025-12-02 01:23:26,730] Trial 12 pruned.

Best trial: 0. Best value: 0.379863:  34%|███▍      | 17/50 [01:51<02:20,  4.27s/it]

[I 2025-12-02 01:23:31,761] Trial 16 finished with value: 0.3318077803203661 and parameters: {'max_depth': 10, 'learning_rate': 0.1094537866666023, 'n_estimators': 466, 'subsample': 0.740461649071806, 'colsample_bytree': 0.6121071735741371, 'min_child_weight': 3, 'gamma': 3.0004198732774685, 'reg_alpha': 0.0020100426175985544, 'reg_lambda': 0.0009169978995666269, 'max_delta_step': 6}. Best is trial 0 with value: 0.37986270022883295.

Best trial: 0. Best value: 0.379863:  36%|███▌      | 18/50 [01:56<02:29,  4.68s/it]

[I 2025-12-02 01:23:37,386] Trial 17 finished with value: 0.3054919908466819 and parameters: {'max_depth': 8, 'learning_rate': 0.293065510305867, 'n_estimators': 479, 'subsample': 0.9991703914737556, 'colsample_bytree': 0.6031581401406354, 'min_child_weight': 4, 'gamma': 3.016125995598542, 'reg_alpha': 0.0051313844712873626, 'reg_lambda': 0.003096996155257647, 'max_delta_step': 2}. Best is trial 0 with value: 0.37986270022883295.

Best trial: 0. Best value: 0.379863:  38%|███▊      | 19/50 [02:00<02:17,  4.42s/it]

[I 2025-12-02 01:23:41,215] Trial 18 finished with value: 0.3318077803203661 and parameters: {'max_depth': 8, 'learning_rate': 0.01050724205954094, 'n_estimators': 526, 'subsample': 0.9953852637557842, 'colsample_bytree': 0.5815641588197882, 'min_child_weight': 4, 'gamma': 2.8183517019832682, 'reg_alpha': 0.0010278277337869531, 'reg_lambda': 1.719849563600363e-08, 'max_delta_step': 2}. Best is trial 0 with value: 0.37986270022883295.

Best trial: 0. Best value: 0.379863:  40%|████      | 20/50 [02:03<02:02,  4.07s/it]

[I 2025-12-02 01:23:44,463] Trial 19 finished with value: 0.36727688787185353 and parameters: {'max_depth': 8, 'learning_rate': 0.29187768585489865, 'n_estimators': 534, 'subsample': 0.8839708501362276, 'colsample_bytree': 0.5692718393414054, 'min_child_weight': 4, 'gamma': 2.731524106134907, 'reg_alpha': 0.0008076515544125589, 'reg_lambda': 4.3123199631222825e-08, 'max_delta_step': 2}. Best is trial 0 with value: 0.37986270022883295.

Best trial: 0. Best value: 0.379863:  42%|████▏     | 21/50 [02:08<02:00,  4.16s/it]

[I 2025-12-02 01:23:48,845] Trial 20 finished with value: 0.3100686498855835 and parameters: {'max_depth': 8, 'learning_rate': 0.29883639432939707, 'n_estimators': 515, 'subsample': 0.990981227949959, 'colsample_bytree': 0.5666400437048781, 'min_child_weight': 4, 'gamma': 2.5529779476652203, 'reg_alpha': 0.21067851073573104, 'reg_lambda': 3.554063787048506e-05, 'max_delta_step': 2}. Best is trial 0 with value: 0.37986270022883295.

Best trial: 0. Best value: 0.379863:  44%|████▍     | 22/50 [02:10<01:37,  3.47s/it]

[I 2025-12-02 01:23:50,693] Trial 22 pruned.

Best trial: 0. Best value: 0.379863:  46%|████▌     | 23/50 [02:16<02:00,  4.46s/it]

[I 2025-12-02 01:23:57,468] Trial 21 finished with value: 0.3100686498855835 and parameters: {'max_depth': 5, 'learning_rate': 0.010520743724167685, 'n_estimators': 543, 'subsample': 0.8746499182208899, 'colsample_bytree': 0.8335283559525639, 'min_child_weight': 4, 'gamma': 2.23055452134733, 'reg_alpha': 0.40489416365600434, 'reg_lambda': 3.475202762702471e-05, 'max_delta_step': 10}. Best is trial 0 with value: 0.37986270022883295.

Best trial: 23. Best value: 0.432494:  48%|████▊     | 24/50 [02:29<03:03,  7.04s/it]

[I 2025-12-02 01:24:10,526] Trial 23 finished with value: 0.43249427917620137 and parameters: {'max_depth': 5, 'learning_rate': 0.12997857110404787, 'n_estimators': 859, 'subsample': 0.802714313326563, 'colsample_bytree': 0.6856118970806404, 'min_child_weight': 3, 'gamma': 4.024457161930569, 'reg_alpha': 0.1738235209579987, 'reg_lambda': 4.43311069792985e-05, 'max_delta_step': 10}. Best is trial 23 with value: 0.43249427917620137.

Best trial: 23. Best value: 0.432494:  50%|█████     | 25/50 [02:40<03:23,  8.16s/it]

[I 2025-12-02 01:24:21,292] Trial 24 finished with value: 0.39702517162471396 and parameters: {'max_depth': 5, 'learning_rate': 0.04601667441413261, 'n_estimators': 966, 'subsample': 0.7986836552709581, 'colsample_bytree': 0.5165695484985989, 'min_child_weight': 1, 'gamma': 1.9443356428249974, 'reg_alpha': 0.6238485428659063, 'reg_lambda': 4.814777237219782e-05, 'max_delta_step': 10}. Best is trial 23 with value: 0.43249427917620137.

Best trial: 23. Best value: 0.432494:  52%|█████▏    | 26/50 [02:45<02:50,  7.10s/it]

[I 2025-12-02 01:24:25,924] Trial 25 finished with value: 0.40617848970251713 and parameters: {'max_depth': 5, 'learning_rate': 0.050403944315587944, 'n_estimators': 1016, 'subsample': 0.7909762780278052, 'colsample_bytree': 0.6775810715496898, 'min_child_weight': 1, 'gamma': 1.5187275926430401, 'reg_alpha': 0.00012406250110117545, 'reg_lambda': 2.2636520439665346e-07, 'max_delta_step': 10}. Best is trial 23 with value: 0.43249427917620137.

Best trial: 23. Best value: 0.432494:  54%|█████▍    | 27/50 [02:48<02:13,  5.78s/it]

[I 2025-12-02 01:24:28,636] Trial 28 pruned.

Best trial: 23. Best value: 0.432494:  56%|█████▌    | 28/50 [02:51<01:50,  5.04s/it]

[I 2025-12-02 01:24:31,929] Trial 26 finished with value: 0.41876430205949655 and parameters: {'max_depth': 5, 'learning_rate': 0.04710166126709231, 'n_estimators': 996, 'subsample': 0.8070657332869321, 'colsample_bytree': 0.6768335438397624, 'min_child_weight': 1, 'gamma': 1.379848856787055, 'reg_alpha': 7.521372220164823e-07, 'reg_lambda': 4.124934879710317e-07, 'max_delta_step': 9}. Best is trial 23 with value: 0.43249427917620137.

Best trial: 23. Best value: 0.432494:  58%|█████▊    | 29/50 [02:54<01:34,  4.52s/it]

[I 2025-12-02 01:24:35,234] Trial 27 finished with value: 0.33638443935926776 and parameters: {'max_depth': 5, 'learning_rate': 0.15152092930106284, 'n_estimators': 813, 'subsample': 0.7912974311080705, 'colsample_bytree': 0.6870994904887273, 'min_child_weight': 3, 'gamma': 3.828801373992225, 'reg_alpha': 1.7207694483005447, 'reg_lambda': 0.014956653463663679, 'max_delta_step': 8}. Best is trial 23 with value: 0.43249427917620137.

Best trial: 23. Best value: 0.432494:  60%|██████    | 30/50 [03:21<03:44, 11.22s/it]

[I 2025-12-02 01:25:02,094] Trial 29 finished with value: 0.40160183066361554 and parameters: {'max_depth': 4, 'learning_rate': 0.03578718592801204, 'n_estimators': 1033, 'subsample': 0.7887358285909456, 'colsample_bytree': 0.6844077254215717, 'min_child_weight': 1, 'gamma': 1.7273248303661881, 'reg_alpha': 9.26950792880574e-05, 'reg_lambda': 2.7831276348999207e-07, 'max_delta_step': 8}. Best is trial 23 with value: 0.43249427917620137.

Best trial: 23. Best value: 0.432494:  62%|██████▏   | 31/50 [03:23<02:42,  8.56s/it]

[I 2025-12-02 01:25:04,445] Trial 30 finished with value: 0.37528604118993136 and parameters: {'max_depth': 5, 'learning_rate': 0.03400842733423715, 'n_estimators': 1022, 'subsample': 0.7753330433054346, 'colsample_bytree': 0.6753579024347129, 'min_child_weight': 1, 'gamma': 1.771385443313807, 'reg_alpha': 0.00013512043472415944, 'reg_lambda': 1.5402280063574218e-07, 'max_delta_step': 9}. Best is trial 23 with value: 0.43249427917620137.

Best trial: 23. Best value: 0.432494:  64%|██████▍   | 32/50 [03:25<01:58,  6.57s/it]

[I 2025-12-02 01:25:06,359] Trial 31 finished with value: 0.3100686498855835 and parameters: {'max_depth': 4, 'learning_rate': 0.028869568875775464, 'n_estimators': 1081, 'subsample': 0.7768852352501591, 'colsample_bytree': 0.6885206836569945, 'min_child_weight': 2, 'gamma': 1.6385902633158511, 'reg_alpha': 0.000123059278958529, 'reg_lambda': 3.299556351890004e-07, 'max_delta_step': 9}. Best is trial 23 with value: 0.43249427917620137.

Best trial: 23. Best value: 0.432494:  66%|██████▌   | 33/50 [03:28<01:30,  5.33s/it]

[I 2025-12-02 01:25:08,795] Trial 32 finished with value: 0.2837528604118993 and parameters: {'max_depth': 4, 'learning_rate': 0.033110660274445036, 'n_estimators': 1074, 'subsample': 0.7669687495221804, 'colsample_bytree': 0.6808940917180154, 'min_child_weight': 2, 'gamma': 1.565213025933437, 'reg_alpha': 0.00017391536412982156, 'reg_lambda': 4.4109470436430665e-07, 'max_delta_step': 9}. Best is trial 23 with value: 0.43249427917620137.

Best trial: 23. Best value: 0.432494:  68%|██████▊   | 34/50 [03:53<03:03, 11.44s/it]

[I 2025-12-02 01:25:34,509] Trial 35 finished with value: 0.37528604118993136 and parameters: {'max_depth': 3, 'learning_rate': 0.07489355200494982, 'n_estimators': 891, 'subsample': 0.8482014103981597, 'colsample_bytree': 0.7912044458997423, 'min_child_weight': 2, 'gamma': 1.1937210792168493, 'reg_alpha': 7.123472408992416e-07, 'reg_lambda': 7.107208186298782e-07, 'max_delta_step': 8}. Best is trial 23 with value: 0.43249427917620137.

Best trial: 23. Best value: 0.432494:  70%|███████   | 35/50 [03:55<02:05,  8.34s/it]

[I 2025-12-02 01:25:35,601] Trial 33 finished with value: 0.3489702517162471 and parameters: {'max_depth': 4, 'learning_rate': 0.07511311690801696, 'n_estimators': 1062, 'subsample': 0.8397549197316865, 'colsample_bytree': 0.8008087624413565, 'min_child_weight': 2, 'gamma': 1.1331266046722255, 'reg_alpha': 2.4691139072796705e-07, 'reg_lambda': 2.9671581457045475e-07, 'max_delta_step': 9}. Best is trial 23 with value: 0.43249427917620137.

Best trial: 23. Best value: 0.432494:  72%|███████▏  | 36/50 [03:59<01:38,  7.07s/it]

[I 2025-12-02 01:25:39,701] Trial 34 finished with value: 0.3707093821510298 and parameters: {'max_depth': 4, 'learning_rate': 0.027769832979968257, 'n_estimators': 1064, 'subsample': 0.8477553630165179, 'colsample_bytree': 0.7114118250916539, 'min_child_weight': 2, 'gamma': 1.1323965517299521, 'reg_alpha': 5.626146112615764e-05, 'reg_lambda': 2.4513661850012515e-07, 'max_delta_step': 9}. Best is trial 23 with value: 0.43249427917620137.

Best trial: 23. Best value: 0.432494:  74%|███████▍  | 37/50 [04:00<01:09,  5.31s/it]

[I 2025-12-02 01:25:40,924] Trial 36 finished with value: 0.40160183066361554 and parameters: {'max_depth': 3, 'learning_rate': 0.0696072994487673, 'n_estimators': 881, 'subsample': 0.8342030590781712, 'colsample_bytree': 0.7949222249632418, 'min_child_weight': 1, 'gamma': 1.2142895676976937, 'reg_alpha': 3.452030306977358e-07, 'reg_lambda': 1.7582829655701457e-08, 'max_delta_step': 8}. Best is trial 23 with value: 0.43249427917620137.

Best trial: 23. Best value: 0.432494:  76%|███████▌  | 38/50 [04:09<01:18,  6.50s/it]

[I 2025-12-02 01:25:50,196] Trial 39 pruned.

Best trial: 23. Best value: 0.432494:  78%|███████▊  | 39/50 [04:19<01:21,  7.39s/it]

[I 2025-12-02 01:25:59,669] Trial 41 pruned.

Best trial: 23. Best value: 0.432494:  80%|████████  | 40/50 [04:28<01:20,  8.04s/it]

[I 2025-12-02 01:26:09,214] Trial 42 pruned.

Best trial: 23. Best value: 0.432494:  82%|████████▏ | 41/50 [04:36<01:11,  7.95s/it]

[I 2025-12-02 01:26:16,943] Trial 38 finished with value: 0.32723112128146453 and parameters: {'max_depth': 3, 'learning_rate': 0.04367453956490438, 'n_estimators': 1246, 'subsample': 0.6421389983476677, 'colsample_bytree': 0.7220050325418087, 'min_child_weight': 1, 'gamma': 0.8852273759518727, 'reg_alpha': 3.246240625561796e-05, 'reg_lambda': 7.905753804683054e-08, 'max_delta_step': 7}. Best is trial 23 with value: 0.43249427917620137.

Best trial: 23. Best value: 0.432494:  84%|████████▍ | 42/50 [04:37<00:46,  5.77s/it]

[I 2025-12-02 01:26:17,645] Trial 37 finished with value: 0.35354691075514877 and parameters: {'max_depth': 4, 'learning_rate': 0.04216215294246902, 'n_estimators': 1237, 'subsample': 0.8296728705140382, 'colsample_bytree': 0.7257841210948339, 'min_child_weight': 1, 'gamma': 0.9662032441048576, 'reg_alpha': 7.7727325481173e-07, 'reg_lambda': 1.3850547158215897e-08, 'max_delta_step': 10}. Best is trial 23 with value: 0.43249427917620137.

Best trial: 23. Best value: 0.432494:  86%|████████▌ | 43/50 [04:42<00:39,  5.64s/it]

[I 2025-12-02 01:26:22,978] Trial 40 finished with value: 0.37986270022883295 and parameters: {'max_depth': 6, 'learning_rate': 0.04297328318724105, 'n_estimators': 1265, 'subsample': 0.6758914450180733, 'colsample_bytree': 0.7315156184780145, 'min_child_weight': 1, 'gamma': 0.7946603972372882, 'reg_alpha': 1.274701717031158e-08, 'reg_lambda': 1.049860022325307e-05, 'max_delta_step': 7}. Best is trial 23 with value: 0.43249427917620137.

Best trial: 23. Best value: 0.432494:  88%|████████▊ | 44/50 [04:51<00:40,  6.71s/it]

[I 2025-12-02 01:26:32,172] Trial 43 finished with value: 0.36270022883295194 and parameters: {'max_depth': 7, 'learning_rate': 0.055060235977189176, 'n_estimators': 652, 'subsample': 0.6404943267639925, 'colsample_bytree': 0.7344656457839147, 'min_child_weight': 1, 'gamma': 4.316439431833168, 'reg_alpha': 0.000471043518534667, 'reg_lambda': 0.0001929843595051262, 'max_delta_step': 10}. Best is trial 23 with value: 0.43249427917620137.

Best trial: 23. Best value: 0.432494:  90%|█████████ | 45/50 [04:57<00:32,  6.58s/it]

[I 2025-12-02 01:26:38,453] Trial 47 pruned.

Best trial: 23. Best value: 0.432494:  92%|█████████▏| 46/50 [04:58<00:19,  4.78s/it]

[I 2025-12-02 01:26:39,044] Trial 44 finished with value: 0.40160183066361554 and parameters: {'max_depth': 4, 'learning_rate': 0.059544099892725647, 'n_estimators': 622, 'subsample': 0.8206570783205381, 'colsample_bytree': 0.7453088455131723, 'min_child_weight': 1, 'gamma': 1.4039670328823168, 'reg_alpha': 5.022408863224352e-08, 'reg_lambda': 1.1992519468183787e-08, 'max_delta_step': 10}. Best is trial 23 with value: 0.43249427917620137.

Best trial: 45. Best value: 0.44508:  94%|█████████▍| 47/50 [04:59<00:11,  3.70s/it]

[I 2025-12-02 01:26:40,213] Trial 45 finished with value: 0.44508009153318073 and parameters: {'max_depth': 3, 'learning_rate': 0.1280588000175127, 'n_estimators': 660, 'subsample': 0.8063082621541084, 'colsample_bytree': 0.8651471262589969, 'min_child_weight': 1, 'gamma': 1.5105595206459397, 'reg_alpha': 2.0804845625025625e-08, 'reg_lambda': 2.0713048746802712e-08, 'max_delta_step': 8}. Best is trial 45 with value: 0.44508009153318073.

Best trial: 45. Best value: 0.44508:  96%|█████████▌| 48/50 [05:03<00:07,  3.77s/it]

[I 2025-12-02 01:26:44,150] Trial 48 pruned.

Best trial: 45. Best value: 0.44508:  98%|█████████▊| 49/50 [05:04<00:03,  3.02s/it]

[I 2025-12-02 01:26:45,408] Trial 46 finished with value: 0.35354691075514877 and parameters: {'max_depth': 3, 'learning_rate': 0.05782319722442683, 'n_estimators': 640, 'subsample': 0.8157885795680828, 'colsample_bytree': 0.7699064173888867, 'min_child_weight': 1, 'gamma': 1.3780457929510548, 'reg_alpha': 1.5520080024225807e-07, 'reg_lambda': 2.592495679960406e-06, 'max_delta_step': 8}. Best is trial 45 with value: 0.44508009153318073.

Best trial: 45. Best value: 0.44508: 100%|██████████| 50/50 [05:11<00:00,  6.23s/it]

[I 2025-12-02 01:26:51,961] Trial 49 finished with value: 0.10869565217391304 and parameters: {'max_depth': 5, 'learning_rate': 0.0338537721908239, 'n_estimators': 847, 'subsample': 0.7641213050649496, 'colsample_bytree': 0.6581548121230635, 'min_child_weight': 6, 'gamma': 0.0735970106315822, 'reg_alpha': 1.784463519443373e-07, 'reg_lambda': 3.0197018676933863e-08, 'max_delta_step': 9}. Best is trial 45 with value: 0.44508009153318073.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 01:26:56,935] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 44, Test size: 12
Using Leave-One-Out CV with 44 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.576842:   2%|▏         | 1/50 [00:12<10:01, 12.29s/it]

[I 2025-12-02 01:27:09,214] Trial 2 finished with value: 0.5768421052631579 and parameters: {'max_depth': 5, 'learning_rate': 0.017111515729323904, 'n_estimators': 309, 'subsample': 0.6650444122082753, 'colsample_bytree': 0.7976762859209806, 'min_child_weight': 3, 'gamma': 4.353140131228455, 'reg_alpha': 0.00020676006078272004, 'reg_lambda': 0.5933090907676328, 'max_delta_step': 8}. Best is trial 2 with value: 0.5768421052631579.

Best trial: 2. Best value: 0.576842:   4%|▍         | 2/50 [00:21<08:36, 10.76s/it]

[I 2025-12-02 01:27:18,901] Trial 1 finished with value: 0.2 and parameters: {'max_depth': 9, 'learning_rate': 0.057987445150257624, 'n_estimators': 649, 'subsample': 0.6829200875745858, 'colsample_bytree': 0.5302895307657499, 'min_child_weight': 5, 'gamma': 1.1144300801005347, 'reg_alpha': 3.8747164891590604e-06, 'reg_lambda': 0.0016034275079427009, 'max_delta_step': 3}. Best is trial 2 with value: 0.5768421052631579.

Best trial: 0. Best value: 0.616842:   6%|▌         | 3/50 [00:36<09:36, 12.27s/it]

[I 2025-12-02 01:27:32,982] Trial 0 finished with value: 0.6168421052631579 and parameters: {'max_depth': 4, 'learning_rate': 0.08007555669208898, 'n_estimators': 862, 'subsample': 0.5392470635151336, 'colsample_bytree': 0.554160698470958, 'min_child_weight': 1, 'gamma': 1.3339391515764776, 'reg_alpha': 0.01942121158556396, 'reg_lambda': 5.356021955155558, 'max_delta_step': 0}. Best is trial 0 with value: 0.6168421052631579.

Best trial: 0. Best value: 0.616842:   8%|▊         | 4/50 [00:36<05:46,  7.54s/it]

[I 2025-12-02 01:27:33,263] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.013481333030013481, 'n_estimators': 405, 'subsample': 0.9211643471814666, 'colsample_bytree': 0.5864488550736501, 'min_child_weight': 10, 'gamma': 1.8771108423648974, 'reg_alpha': 4.08855849281851e-06, 'reg_lambda': 0.00011820296545017566, 'max_delta_step': 4}. Best is trial 0 with value: 0.6168421052631579.

Best trial: 0. Best value: 0.616842:  10%|█         | 5/50 [00:36<03:44,  4.98s/it]

[I 2025-12-02 01:27:33,719] Trial 4 finished with value: 0.5768421052631579 and parameters: {'max_depth': 8, 'learning_rate': 0.20306313053714656, 'n_estimators': 702, 'subsample': 0.6724456220871855, 'colsample_bytree': 0.6703875374191635, 'min_child_weight': 3, 'gamma': 0.40651118679400966, 'reg_alpha': 1.698070472133496e-05, 'reg_lambda': 0.03623574301844218, 'max_delta_step': 7}. Best is trial 0 with value: 0.6168421052631579.

Best trial: 0. Best value: 0.616842:  12%|█▏        | 6/50 [00:48<05:22,  7.34s/it]

[I 2025-12-02 01:27:45,624] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.07511259017207902, 'n_estimators': 1477, 'subsample': 0.8704567693359805, 'colsample_bytree': 0.570301344429798, 'min_child_weight': 8, 'gamma': 3.631430555496908, 'reg_alpha': 0.03265484412989263, 'reg_lambda': 0.03639826766966515, 'max_delta_step': 1}. Best is trial 0 with value: 0.6168421052631579.

Best trial: 0. Best value: 0.616842:  14%|█▍        | 7/50 [01:18<10:34, 14.77s/it]

[I 2025-12-02 01:28:15,684] Trial 8 finished with value: 0.5105263157894737 and parameters: {'max_depth': 8, 'learning_rate': 0.04983773488777013, 'n_estimators': 1115, 'subsample': 0.8333122881048904, 'colsample_bytree': 0.7200717442105469, 'min_child_weight': 2, 'gamma': 1.5981643554968472, 'reg_alpha': 0.00033986676599968315, 'reg_lambda': 0.016371229118130118, 'max_delta_step': 9}. Best is trial 0 with value: 0.6168421052631579.

Best trial: 0. Best value: 0.616842:  16%|█▌        | 8/50 [01:22<07:53, 11.27s/it]

[I 2025-12-02 01:28:19,469] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.08386748374660205, 'n_estimators': 1360, 'subsample': 0.9608995985551357, 'colsample_bytree': 0.7286800703594978, 'min_child_weight': 8, 'gamma': 0.38915318678742483, 'reg_alpha': 6.107417052011584e-05, 'reg_lambda': 0.0008869537798287547, 'max_delta_step': 0}. Best is trial 0 with value: 0.6168421052631579.

Best trial: 0. Best value: 0.616842:  18%|█▊        | 9/50 [01:26<06:07,  8.97s/it]

[I 2025-12-02 01:28:23,391] Trial 6 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.025081305585051936, 'n_estimators': 1486, 'subsample': 0.675869460757163, 'colsample_bytree': 0.6454329965303561, 'min_child_weight': 5, 'gamma': 3.6374260906487965, 'reg_alpha': 4.01199838673849, 'reg_lambda': 2.4090120161021087, 'max_delta_step': 5}. Best is trial 0 with value: 0.6168421052631579.

Best trial: 0. Best value: 0.616842:  20%|██        | 10/50 [01:28<04:38,  6.97s/it]

[I 2025-12-02 01:28:25,878] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.24152619052535776, 'n_estimators': 1172, 'subsample': 0.7092241443092706, 'colsample_bytree': 0.8309487009272969, 'min_child_weight': 10, 'gamma': 1.7340660257763008, 'reg_alpha': 0.000149424042382225, 'reg_lambda': 6.075906938392156e-07, 'max_delta_step': 10}. Best is trial 0 with value: 0.6168421052631579.

Best trial: 0. Best value: 0.616842:  22%|██▏       | 11/50 [01:52<07:53, 12.15s/it]

[I 2025-12-02 01:28:49,757] Trial 12 finished with value: 0.5905263157894737 and parameters: {'max_depth': 9, 'learning_rate': 0.021439609648979955, 'n_estimators': 652, 'subsample': 0.6200839171161897, 'colsample_bytree': 0.5474408013854279, 'min_child_weight': 1, 'gamma': 4.423056098772355, 'reg_alpha': 0.0007474197439053913, 'reg_lambda': 2.9573437855874022e-08, 'max_delta_step': 7}. Best is trial 0 with value: 0.6168421052631579.

Best trial: 0. Best value: 0.616842:  24%|██▍       | 12/50 [01:56<06:00,  9.48s/it]

[I 2025-12-02 01:28:53,152] Trial 10 finished with value: 0.5305263157894737 and parameters: {'max_depth': 8, 'learning_rate': 0.030478435930726626, 'n_estimators': 1101, 'subsample': 0.8046905821827877, 'colsample_bytree': 0.9220474737484279, 'min_child_weight': 4, 'gamma': 1.318315255955237, 'reg_alpha': 1.532290696373851e-06, 'reg_lambda': 1.3243457088699835, 'max_delta_step': 10}. Best is trial 0 with value: 0.6168421052631579.

Best trial: 0. Best value: 0.616842:  26%|██▌       | 13/50 [02:03<05:26,  8.82s/it]

[I 2025-12-02 01:29:00,436] Trial 13 finished with value: 0.4842105263157894 and parameters: {'max_depth': 3, 'learning_rate': 0.13633704146123937, 'n_estimators': 938, 'subsample': 0.5270655670441947, 'colsample_bytree': 0.9330121720917965, 'min_child_weight': 1, 'gamma': 2.755939798478, 'reg_alpha': 9.780202099947623e-08, 'reg_lambda': 1.2117198515467074e-08, 'max_delta_step': 2}. Best is trial 0 with value: 0.6168421052631579.

Best trial: 0. Best value: 0.616842:  28%|██▊       | 14/50 [02:06<04:15,  7.10s/it]

[I 2025-12-02 01:29:03,557] Trial 11 finished with value: 0.5368421052631579 and parameters: {'max_depth': 6, 'learning_rate': 0.1650133671887155, 'n_estimators': 1407, 'subsample': 0.7615047261916874, 'colsample_bytree': 0.621309176499975, 'min_child_weight': 3, 'gamma': 3.374484478759634, 'reg_alpha': 6.40756553827287e-08, 'reg_lambda': 3.3394717629221464e-08, 'max_delta_step': 1}. Best is trial 0 with value: 0.6168421052631579.

Best trial: 0. Best value: 0.616842:  30%|███       | 15/50 [02:09<03:22,  5.78s/it]

[I 2025-12-02 01:29:06,291] Trial 15 pruned.

Best trial: 0. Best value: 0.616842:  32%|███▏      | 16/50 [02:24<04:50,  8.55s/it]

[I 2025-12-02 01:29:21,257] Trial 16 finished with value: 0.5705263157894737 and parameters: {'max_depth': 5, 'learning_rate': 0.033494372394754744, 'n_estimators': 563, 'subsample': 0.5243103962055312, 'colsample_bytree': 0.5013913677546348, 'min_child_weight': 1, 'gamma': 4.921598775442181, 'reg_alpha': 0.01669596473706024, 'reg_lambda': 7.573819738260549e-06, 'max_delta_step': 6}. Best is trial 0 with value: 0.6168421052631579.

Best trial: 17. Best value: 0.623158:  34%|███▍      | 17/50 [02:27<03:49,  6.96s/it]

[I 2025-12-02 01:29:24,519] Trial 17 finished with value: 0.6231578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.03685403748077013, 'n_estimators': 586, 'subsample': 0.539941014529057, 'colsample_bytree': 0.506300250489498, 'min_child_weight': 1, 'gamma': 4.710905483044971, 'reg_alpha': 0.013844958268797282, 'reg_lambda': 1.572152340770466e-06, 'max_delta_step': 6}. Best is trial 17 with value: 0.6231578947368421.

Best trial: 17. Best value: 0.623158:  36%|███▌      | 18/50 [02:28<02:41,  5.06s/it]

[I 2025-12-02 01:29:25,148] Trial 19 pruned.

Best trial: 17. Best value: 0.623158:  38%|███▊      | 19/50 [02:28<01:51,  3.61s/it]

[I 2025-12-02 01:29:25,398] Trial 14 finished with value: 0.5705263157894737 and parameters: {'max_depth': 3, 'learning_rate': 0.03264498291851505, 'n_estimators': 886, 'subsample': 0.5035068412979038, 'colsample_bytree': 0.946738617931927, 'min_child_weight': 1, 'gamma': 2.741701185034137, 'reg_alpha': 0.03877150989985394, 'reg_lambda': 1.8333168897445933e-08, 'max_delta_step': 6}. Best is trial 17 with value: 0.6231578947368421.

Best trial: 17. Best value: 0.623158:  40%|████      | 20/50 [02:30<01:30,  3.02s/it]

[I 2025-12-02 01:29:27,029] Trial 18 finished with value: 0.5842105263157895 and parameters: {'max_depth': 5, 'learning_rate': 0.033855215971199, 'n_estimators': 560, 'subsample': 0.5873336300688241, 'colsample_bytree': 0.5039821697200818, 'min_child_weight': 1, 'gamma': 4.667906771228142, 'reg_alpha': 0.008720025158096771, 'reg_lambda': 1.1807394103757713e-05, 'max_delta_step': 6}. Best is trial 17 with value: 0.6231578947368421.

Best trial: 17. Best value: 0.623158:  42%|████▏     | 21/50 [02:30<01:05,  2.27s/it]

[I 2025-12-02 01:29:27,549] Trial 22 pruned.

Best trial: 17. Best value: 0.623158:  44%|████▍     | 22/50 [02:31<00:51,  1.83s/it]

[I 2025-12-02 01:29:28,346] Trial 20 pruned.

Best trial: 17. Best value: 0.623158:  46%|████▌     | 23/50 [02:34<01:00,  2.24s/it]

[I 2025-12-02 01:29:31,541] Trial 21 pruned.

Best trial: 17. Best value: 0.623158:  48%|████▊     | 24/50 [02:35<00:51,  1.98s/it]

[I 2025-12-02 01:29:32,929] Trial 23 pruned.

Best trial: 17. Best value: 0.623158:  50%|█████     | 25/50 [02:57<03:13,  7.74s/it]

[I 2025-12-02 01:29:54,113] Trial 26 finished with value: 0.45789473684210524 and parameters: {'max_depth': 7, 'learning_rate': 0.08462941316033809, 'n_estimators': 696, 'subsample': 0.5470605915146682, 'colsample_bytree': 0.567739453352583, 'min_child_weight': 2, 'gamma': 4.253010667117963, 'reg_alpha': 0.16803820246729004, 'reg_lambda': 4.174744560422148e-07, 'max_delta_step': 8}. Best is trial 17 with value: 0.6231578947368421.

Best trial: 17. Best value: 0.623158:  52%|█████▏    | 26/50 [02:59<02:24,  6.03s/it]

[I 2025-12-02 01:29:56,152] Trial 24 finished with value: 0.5505263157894738 and parameters: {'max_depth': 7, 'learning_rate': 0.01046936942341979, 'n_estimators': 769, 'subsample': 0.5693080675835588, 'colsample_bytree': 0.5585795078104078, 'min_child_weight': 2, 'gamma': 4.309707560753042, 'reg_alpha': 0.3468508597018166, 'reg_lambda': 1.452369673803337e-07, 'max_delta_step': 8}. Best is trial 17 with value: 0.6231578947368421.

Best trial: 17. Best value: 0.623158:  54%|█████▍    | 27/50 [02:59<01:41,  4.40s/it]

[I 2025-12-02 01:29:56,741] Trial 25 finished with value: 0.5305263157894737 and parameters: {'max_depth': 7, 'learning_rate': 0.010176508339075845, 'n_estimators': 748, 'subsample': 0.6211373309350922, 'colsample_bytree': 0.5559267586804354, 'min_child_weight': 2, 'gamma': 4.190020252603439, 'reg_alpha': 0.0013073861169544372, 'reg_lambda': 1.425855904478816e-07, 'max_delta_step': 8}. Best is trial 17 with value: 0.6231578947368421.

Best trial: 17. Best value: 0.623158:  56%|█████▌    | 28/50 [03:07<01:55,  5.25s/it]

[I 2025-12-02 01:30:03,974] Trial 29 pruned.

Best trial: 17. Best value: 0.623158:  58%|█████▊    | 29/50 [03:07<01:18,  3.76s/it]

[I 2025-12-02 01:30:04,255] Trial 30 pruned.

Best trial: 17. Best value: 0.623158:  60%|██████    | 30/50 [03:11<01:19,  3.96s/it]

[I 2025-12-02 01:30:08,693] Trial 27 finished with value: 0.5105263157894737 and parameters: {'max_depth': 7, 'learning_rate': 0.011478073661103209, 'n_estimators': 980, 'subsample': 0.638674717479261, 'colsample_bytree': 0.5455584600011553, 'min_child_weight': 2, 'gamma': 4.120456642852105, 'reg_alpha': 0.0011909043478524203, 'reg_lambda': 1.4505556832182172e-07, 'max_delta_step': 8}. Best is trial 17 with value: 0.6231578947368421.

Best trial: 17. Best value: 0.623158:  62%|██████▏   | 31/50 [03:12<00:54,  2.87s/it]

[I 2025-12-02 01:30:09,015] Trial 31 pruned.

Best trial: 17. Best value: 0.623158:  64%|██████▍   | 32/50 [03:12<00:37,  2.10s/it]

[I 2025-12-02 01:30:09,326] Trial 32 pruned.

Best trial: 17. Best value: 0.623158:  66%|██████▌   | 33/50 [03:16<00:45,  2.67s/it]

[I 2025-12-02 01:30:13,334] Trial 33 pruned.

Best trial: 17. Best value: 0.623158:  68%|██████▊   | 34/50 [03:28<01:26,  5.41s/it]

[I 2025-12-02 01:30:25,132] Trial 35 finished with value: 0.6168421052631579 and parameters: {'max_depth': 5, 'learning_rate': 0.017497475966769337, 'n_estimators': 404, 'subsample': 0.5520563690258252, 'colsample_bytree': 0.501099397377861, 'min_child_weight': 1, 'gamma': 4.518852084293012, 'reg_alpha': 0.00758554477050107, 'reg_lambda': 1.4490317177744754e-05, 'max_delta_step': 6}. Best is trial 17 with value: 0.6231578947368421.

Best trial: 17. Best value: 0.623158:  70%|███████   | 35/50 [03:31<01:09,  4.63s/it]

[I 2025-12-02 01:30:27,951] Trial 36 finished with value: 0.6168421052631579 and parameters: {'max_depth': 5, 'learning_rate': 0.014994260352257018, 'n_estimators': 358, 'subsample': 0.5510914574058451, 'colsample_bytree': 0.5066902735268151, 'min_child_weight': 1, 'gamma': 4.7134325564803445, 'reg_alpha': 0.006831781583327184, 'reg_lambda': 0.18762883045526546, 'max_delta_step': 7}. Best is trial 17 with value: 0.6231578947368421.

Best trial: 17. Best value: 0.623158:  72%|███████▏  | 36/50 [03:31<00:48,  3.45s/it]

[I 2025-12-02 01:30:28,630] Trial 37 pruned.

Best trial: 17. Best value: 0.623158:  74%|███████▍  | 37/50 [03:32<00:34,  2.69s/it]

[I 2025-12-02 01:30:29,544] Trial 28 finished with value: 0.5105263157894737 and parameters: {'max_depth': 6, 'learning_rate': 0.010819186682508237, 'n_estimators': 981, 'subsample': 0.632183430955153, 'colsample_bytree': 0.545205946633611, 'min_child_weight': 2, 'gamma': 4.078401622970751, 'reg_alpha': 0.0011847838576796823, 'reg_lambda': 1.823147214613013e-07, 'max_delta_step': 7}. Best is trial 17 with value: 0.6231578947368421.

Best trial: 17. Best value: 0.623158:  76%|███████▌  | 38/50 [03:33<00:26,  2.21s/it]

[I 2025-12-02 01:30:30,641] Trial 39 pruned.

Best trial: 17. Best value: 0.623158:  78%|███████▊  | 39/50 [03:34<00:19,  1.73s/it]

[I 2025-12-02 01:30:31,250] Trial 38 pruned.

Best trial: 17. Best value: 0.623158:  80%|████████  | 40/50 [03:34<00:13,  1.31s/it]

[I 2025-12-02 01:30:31,592] Trial 40 pruned.

Best trial: 17. Best value: 0.623158:  82%|████████▏ | 41/50 [03:35<00:09,  1.06s/it]

[I 2025-12-02 01:30:32,046] Trial 34 finished with value: 0.6168421052631579 and parameters: {'max_depth': 5, 'learning_rate': 0.02003033079568455, 'n_estimators': 617, 'subsample': 0.5486161772912627, 'colsample_bytree': 0.5096810434806383, 'min_child_weight': 1, 'gamma': 4.471938182808492, 'reg_alpha': 0.006628371279610409, 'reg_lambda': 1.561118170016784e-05, 'max_delta_step': 5}. Best is trial 17 with value: 0.6231578947368421.

Best trial: 17. Best value: 0.623158:  84%|████████▍ | 42/50 [03:37<00:10,  1.35s/it]

[I 2025-12-02 01:30:34,071] Trial 41 pruned.

Best trial: 17. Best value: 0.623158:  86%|████████▌ | 43/50 [03:39<00:12,  1.78s/it]

[I 2025-12-02 01:30:36,853] Trial 44 pruned.

Best trial: 17. Best value: 0.623158:  88%|████████▊ | 44/50 [03:41<00:09,  1.66s/it]

[I 2025-12-02 01:30:38,227] Trial 45 pruned.

Best trial: 17. Best value: 0.623158:  90%|█████████ | 45/50 [03:43<00:08,  1.74s/it]

[I 2025-12-02 01:30:40,163] Trial 46 pruned.

Best trial: 17. Best value: 0.623158:  92%|█████████▏| 46/50 [03:45<00:08,  2.02s/it]

[I 2025-12-02 01:30:42,834] Trial 48 pruned.

Best trial: 17. Best value: 0.623158:  94%|█████████▍| 47/50 [03:46<00:04,  1.65s/it]

[I 2025-12-02 01:30:43,627] Trial 47 pruned.

Best trial: 17. Best value: 0.623158:  96%|█████████▌| 48/50 [03:50<00:04,  2.34s/it]

[I 2025-12-02 01:30:47,588] Trial 42 finished with value: 0.5378947368421052 and parameters: {'max_depth': 4, 'learning_rate': 0.013147782992953626, 'n_estimators': 463, 'subsample': 0.5008421053867759, 'colsample_bytree': 0.5025836248858523, 'min_child_weight': 1, 'gamma': 3.048524900713608, 'reg_alpha': 6.266860708148234e-05, 'reg_lambda': 4.109423938386387, 'max_delta_step': 9}. Best is trial 17 with value: 0.6231578947368421.

Best trial: 17. Best value: 0.623158:  98%|█████████▊| 49/50 [03:51<00:01,  1.86s/it]

[I 2025-12-02 01:30:48,329] Trial 43 finished with value: 0.5905263157894737 and parameters: {'max_depth': 4, 'learning_rate': 0.06659645965544041, 'n_estimators': 472, 'subsample': 0.9227201920246713, 'colsample_bytree': 0.5793626259929103, 'min_child_weight': 1, 'gamma': 3.111370244126827, 'reg_alpha': 1.477718815344388, 'reg_lambda': 9.227534460461444, 'max_delta_step': 9}. Best is trial 17 with value: 0.6231578947368421.

Best trial: 17. Best value: 0.623158: 100%|██████████| 50/50 [03:56<00:00,  4.73s/it]

[I 2025-12-02 01:30:53,599] Trial 49 finished with value: 0.5968421052631578 and parameters: {'max_depth': 4, 'learning_rate': 0.047390635842453864, 'n_estimators': 426, 'subsample': 0.5696336394836599, 'colsample_bytree': 0.6993122990051421, 'min_child_weight': 1, 'gamma': 1.4024059109968843, 'reg_alpha': 0.16589939661776526, 'reg_lambda': 2.397689593385551e-05, 'max_delta_step': 4}. Best is trial 17 with value: 0.6231578947368421.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 01:30:58,398] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 45, Test size: 12
Using Leave-One-Out CV with 45 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0:   2%|▏         | 1/50 [00:20<17:02, 20.88s/it]

[I 2025-12-02 01:31:19,265] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.011975143812187606, 'n_estimators': 552, 'subsample': 0.8490623122718026, 'colsample_bytree': 0.7107818007431866, 'min_child_weight': 7, 'gamma': 4.346241361920381, 'reg_alpha': 0.0001608634411070829, 'reg_lambda': 0.0004213980734583544, 'max_delta_step': 4}. Best is trial 3 with value: 0.0.

Best trial: 1. Best value: 0.40587:   4%|▍         | 2/50 [00:25<09:07, 11.41s/it]

[I 2025-12-02 01:31:24,043] Trial 1 finished with value: 0.4058704453441295 and parameters: {'max_depth': 9, 'learning_rate': 0.09902613701810782, 'n_estimators': 620, 'subsample': 0.9479361971006033, 'colsample_bytree': 0.5568667534568321, 'min_child_weight': 3, 'gamma': 4.954449040781446, 'reg_alpha': 4.07776465469566e-06, 'reg_lambda': 0.00035981793185107294, 'max_delta_step': 3}. Best is trial 1 with value: 0.4058704453441295.

Best trial: 1. Best value: 0.40587:   6%|▌         | 3/50 [00:40<10:01, 12.80s/it]

[I 2025-12-02 01:31:38,491] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.05979845910527569, 'n_estimators': 368, 'subsample': 0.6185403405663329, 'colsample_bytree': 0.7705617139872261, 'min_child_weight': 9, 'gamma': 2.8836320954697827, 'reg_alpha': 1.403406333331196e-07, 'reg_lambda': 2.887134740935637e-05, 'max_delta_step': 2}. Best is trial 1 with value: 0.4058704453441295.

Best trial: 1. Best value: 0.40587:   8%|▊         | 4/50 [00:41<06:29,  8.47s/it]

[I 2025-12-02 01:31:40,333] Trial 0 finished with value: 0.34615384615384615 and parameters: {'max_depth': 10, 'learning_rate': 0.0358642391495235, 'n_estimators': 1178, 'subsample': 0.6914989845784464, 'colsample_bytree': 0.5353005047784296, 'min_child_weight': 5, 'gamma': 3.6747867093780706, 'reg_alpha': 0.05713067176390657, 'reg_lambda': 0.00019913523859738425, 'max_delta_step': 9}. Best is trial 1 with value: 0.4058704453441295.
[I 2025-12-02 01:31:40,360] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.1947756430305302, 'n_estimators': 1181, 'subsample': 0.6438873885744252, 'colsample_bytree': 0.5971949454583855, 'min_child_weight': 10, 'gamma': 2.4285825441069635, 'reg_alpha': 4.0838639505664603e-07, 'reg_lambda': 1.0133722186953254e-05, 'max_delta_step': 9}. Best is trial 1 with value: 0.4058704453441295.

Best trial: 4. Best value: 0.461538:  12%|█▏        | 6/50 [00:44<03:30,  4.77s/it]

[I 2025-12-02 01:31:43,330] Trial 4 finished with value: 0.46153846153846156 and parameters: {'max_depth': 6, 'learning_rate': 0.01981309634925681, 'n_estimators': 651, 'subsample': 0.6240082949036526, 'colsample_bytree': 0.6603999646770689, 'min_child_weight': 4, 'gamma': 4.610581994508012, 'reg_alpha': 6.313698740562e-06, 'reg_lambda': 0.06297007157656591, 'max_delta_step': 1}. Best is trial 4 with value: 0.46153846153846156.

Best trial: 4. Best value: 0.461538:  14%|█▍        | 7/50 [00:55<04:29,  6.27s/it]

[I 2025-12-02 01:31:53,566] Trial 8 finished with value: 0.3147773279352226 and parameters: {'max_depth': 6, 'learning_rate': 0.05664585203698164, 'n_estimators': 315, 'subsample': 0.5267184300650083, 'colsample_bytree': 0.970680817705282, 'min_child_weight': 3, 'gamma': 2.7833675495992747, 'reg_alpha': 7.143417591977355e-08, 'reg_lambda': 2.7849123247021628, 'max_delta_step': 4}. Best is trial 4 with value: 0.46153846153846156.

Best trial: 4. Best value: 0.461538:  16%|█▌        | 8/50 [01:08<05:45,  8.24s/it]

[I 2025-12-02 01:32:06,800] Trial 6 finished with value: 0.019230769230769232 and parameters: {'max_depth': 3, 'learning_rate': 0.045729710984474946, 'n_estimators': 773, 'subsample': 0.7307783062684582, 'colsample_bytree': 0.889758579931479, 'min_child_weight': 7, 'gamma': 2.54374897090347, 'reg_alpha': 4.919952077403948e-08, 'reg_lambda': 0.6093237452236032, 'max_delta_step': 8}. Best is trial 4 with value: 0.46153846153846156.

Best trial: 4. Best value: 0.461538:  18%|█▊        | 9/50 [01:12<04:46,  7.00s/it]

[I 2025-12-02 01:32:10,716] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.010267946277738124, 'n_estimators': 777, 'subsample': 0.9998740527871529, 'colsample_bytree': 0.6763269899804804, 'min_child_weight': 8, 'gamma': 1.9146110423701235, 'reg_alpha': 6.986655237117822e-06, 'reg_lambda': 1.0719584757997607, 'max_delta_step': 10}. Best is trial 4 with value: 0.46153846153846156.

Best trial: 4. Best value: 0.461538:  20%|██        | 10/50 [01:30<06:55, 10.38s/it]

[I 2025-12-02 01:32:29,367] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.06798333753540246, 'n_estimators': 1461, 'subsample': 0.9504633755241624, 'colsample_bytree': 0.8580689708719282, 'min_child_weight': 10, 'gamma': 3.339874517086857, 'reg_alpha': 1.1051452896028575e-07, 'reg_lambda': 4.616926292525576, 'max_delta_step': 5}. Best is trial 4 with value: 0.46153846153846156.

Best trial: 4. Best value: 0.461538:  22%|██▏       | 11/50 [01:35<05:42,  8.78s/it]

[I 2025-12-02 01:32:34,287] Trial 10 pruned.

Best trial: 4. Best value: 0.461538:  24%|██▍       | 12/50 [01:37<04:11,  6.61s/it]

[I 2025-12-02 01:32:35,710] Trial 12 pruned.

Best trial: 4. Best value: 0.461538:  26%|██▌       | 13/50 [01:39<03:18,  5.35s/it]

[I 2025-12-02 01:32:38,091] Trial 11 finished with value: 0.43218623481781376 and parameters: {'max_depth': 10, 'learning_rate': 0.01411727382683695, 'n_estimators': 674, 'subsample': 0.7001869075296518, 'colsample_bytree': 0.883332398318267, 'min_child_weight': 2, 'gamma': 2.018043497166358, 'reg_alpha': 4.005366702557789e-08, 'reg_lambda': 0.03731473098919295, 'max_delta_step': 8}. Best is trial 4 with value: 0.46153846153846156.

Best trial: 4. Best value: 0.461538:  28%|██▊       | 14/50 [01:51<04:16,  7.14s/it]

[I 2025-12-02 01:32:49,435] Trial 15 pruned.

Best trial: 4. Best value: 0.461538:  30%|███       | 15/50 [01:56<03:55,  6.74s/it]

[I 2025-12-02 01:32:55,227] Trial 14 finished with value: 0.39372469635627527 and parameters: {'max_depth': 7, 'learning_rate': 0.14755084017113954, 'n_estimators': 545, 'subsample': 0.8065583562721824, 'colsample_bytree': 0.5161738495248591, 'min_child_weight': 1, 'gamma': 4.8429900714679555, 'reg_alpha': 2.0923182848668714e-05, 'reg_lambda': 1.600229397007612e-07, 'max_delta_step': 0}. Best is trial 4 with value: 0.46153846153846156.

Best trial: 4. Best value: 0.461538:  32%|███▏      | 16/50 [02:03<03:50,  6.77s/it]

[I 2025-12-02 01:33:02,077] Trial 13 finished with value: 0.15384615384615385 and parameters: {'max_depth': 6, 'learning_rate': 0.021539256071118097, 'n_estimators': 1044, 'subsample': 0.5150899442439282, 'colsample_bytree': 0.7778655138786308, 'min_child_weight': 5, 'gamma': 0.5276530757796181, 'reg_alpha': 0.19121606641703787, 'reg_lambda': 7.725959523920711e-08, 'max_delta_step': 0}. Best is trial 4 with value: 0.46153846153846156.

Best trial: 4. Best value: 0.461538:  34%|███▍      | 17/50 [02:05<02:52,  5.24s/it]

[I 2025-12-02 01:33:03,729] Trial 16 pruned.

Best trial: 4. Best value: 0.461538:  36%|███▌      | 18/50 [02:20<04:26,  8.34s/it]

[I 2025-12-02 01:33:19,316] Trial 20 finished with value: 0.3674089068825911 and parameters: {'max_depth': 5, 'learning_rate': 0.017464036565174406, 'n_estimators': 415, 'subsample': 0.6091429803743744, 'colsample_bytree': 0.630080398066264, 'min_child_weight': 3, 'gamma': 1.4430289446568165, 'reg_alpha': 0.0016601950496837744, 'reg_lambda': 0.07580676905357069, 'max_delta_step': 6}. Best is trial 4 with value: 0.46153846153846156.

Best trial: 4. Best value: 0.461538:  38%|███▊      | 19/50 [02:24<03:34,  6.93s/it]

[I 2025-12-02 01:33:22,948] Trial 21 pruned.

Best trial: 4. Best value: 0.461538:  40%|████      | 20/50 [02:30<03:14,  6.49s/it]

[I 2025-12-02 01:33:28,424] Trial 18 finished with value: 0.32894736842105265 and parameters: {'max_depth': 5, 'learning_rate': 0.020983540801817056, 'n_estimators': 1003, 'subsample': 0.5469496035064125, 'colsample_bytree': 0.8092879896633367, 'min_child_weight': 3, 'gamma': 1.230281615323015, 'reg_alpha': 0.004627148295938358, 'reg_lambda': 0.049169746302624724, 'max_delta_step': 7}. Best is trial 4 with value: 0.46153846153846156.

Best trial: 17. Best value: 0.484818:  42%|████▏     | 21/50 [02:31<02:22,  4.93s/it]

[I 2025-12-02 01:33:29,698] Trial 17 finished with value: 0.4848178137651822 and parameters: {'max_depth': 5, 'learning_rate': 0.02103672761255657, 'n_estimators': 944, 'subsample': 0.5452382017179254, 'colsample_bytree': 0.8180588290690709, 'min_child_weight': 1, 'gamma': 0.9322574211818779, 'reg_alpha': 2.763987354257266e-06, 'reg_lambda': 0.05896732011252743, 'max_delta_step': 7}. Best is trial 17 with value: 0.4848178137651822.

Best trial: 17. Best value: 0.484818:  44%|████▍     | 22/50 [02:33<01:52,  4.02s/it]

[I 2025-12-02 01:33:31,594] Trial 19 finished with value: 0.3481781376518218 and parameters: {'max_depth': 5, 'learning_rate': 0.01996321737348474, 'n_estimators': 893, 'subsample': 0.5919921449267592, 'colsample_bytree': 0.6398853593625812, 'min_child_weight': 3, 'gamma': 1.5354800986791917, 'reg_alpha': 0.0029373173886403205, 'reg_lambda': 0.07644239884676733, 'max_delta_step': 7}. Best is trial 17 with value: 0.4848178137651822.

Best trial: 17. Best value: 0.484818:  46%|████▌     | 23/50 [02:51<03:48,  8.45s/it]

[I 2025-12-02 01:33:50,386] Trial 22 finished with value: 0.3603238866396761 and parameters: {'max_depth': 8, 'learning_rate': 0.01555199279189533, 'n_estimators': 697, 'subsample': 0.7661222164497445, 'colsample_bytree': 0.9947905109323828, 'min_child_weight': 2, 'gamma': 3.4370646734006343, 'reg_alpha': 1.0318843245736348e-06, 'reg_lambda': 0.005505070442145958, 'max_delta_step': 2}. Best is trial 17 with value: 0.4848178137651822.

Best trial: 17. Best value: 0.484818:  48%|████▊     | 24/50 [02:55<03:02,  7.01s/it]

[I 2025-12-02 01:33:54,027] Trial 24 finished with value: 0.37955465587044535 and parameters: {'max_depth': 4, 'learning_rate': 0.014948662679360193, 'n_estimators': 692, 'subsample': 0.5819409048676255, 'colsample_bytree': 0.978873137287914, 'min_child_weight': 2, 'gamma': 2.036547565655005, 'reg_alpha': 2.1263482629869135e-06, 'reg_lambda': 0.005517440304750285, 'max_delta_step': 6}. Best is trial 17 with value: 0.4848178137651822.

Best trial: 17. Best value: 0.484818:  50%|█████     | 25/50 [03:00<02:39,  6.39s/it]

[I 2025-12-02 01:33:58,975] Trial 25 finished with value: 0.451417004048583 and parameters: {'max_depth': 4, 'learning_rate': 0.013747583878107063, 'n_estimators': 690, 'subsample': 0.6659706970202353, 'colsample_bytree': 0.9559880358377545, 'min_child_weight': 2, 'gamma': 0.18588116016143186, 'reg_alpha': 1.0202120180347345e-06, 'reg_lambda': 0.0037283954804167873, 'max_delta_step': 6}. Best is trial 17 with value: 0.4848178137651822.

Best trial: 17. Best value: 0.484818:  52%|█████▏    | 26/50 [03:01<01:57,  4.90s/it]

[I 2025-12-02 01:34:00,386] Trial 23 finished with value: 0.37955465587044535 and parameters: {'max_depth': 8, 'learning_rate': 0.014345256327881792, 'n_estimators': 854, 'subsample': 0.7688784720696704, 'colsample_bytree': 0.9578564936836585, 'min_child_weight': 2, 'gamma': 2.0442851888434377, 'reg_alpha': 1.493049776017632e-06, 'reg_lambda': 0.003643846880023242, 'max_delta_step': 2}. Best is trial 17 with value: 0.4848178137651822.

Best trial: 17. Best value: 0.484818:  54%|█████▍    | 27/50 [03:03<01:26,  3.75s/it]

[I 2025-12-02 01:34:01,448] Trial 27 pruned.

Best trial: 17. Best value: 0.484818:  56%|█████▌    | 28/50 [03:04<01:08,  3.10s/it]

[I 2025-12-02 01:34:03,054] Trial 28 pruned.

Best trial: 17. Best value: 0.484818:  58%|█████▊    | 29/50 [03:12<01:32,  4.41s/it]

[I 2025-12-02 01:34:10,496] Trial 31 pruned.

Best trial: 17. Best value: 0.484818:  60%|██████    | 30/50 [03:17<01:33,  4.70s/it]

[I 2025-12-02 01:34:15,873] Trial 29 finished with value: 0.38461538461538464 and parameters: {'max_depth': 3, 'learning_rate': 0.03128949555397644, 'n_estimators': 448, 'subsample': 0.6513613423297467, 'colsample_bytree': 0.7135606553955881, 'min_child_weight': 4, 'gamma': 0.08790715054209804, 'reg_alpha': 2.4636124874171753e-05, 'reg_lambda': 0.0007690004772861191, 'max_delta_step': 5}. Best is trial 17 with value: 0.4848178137651822.

Best trial: 17. Best value: 0.484818:  62%|██████▏   | 31/50 [03:23<01:39,  5.24s/it]

[I 2025-12-02 01:34:22,390] Trial 26 finished with value: 0.43218623481781376 and parameters: {'max_depth': 4, 'learning_rate': 0.013647103490935087, 'n_estimators': 692, 'subsample': 0.6638137235977762, 'colsample_bytree': 0.9164818870047842, 'min_child_weight': 2, 'gamma': 0.1038592936378393, 'reg_alpha': 1.4532141847984341e-06, 'reg_lambda': 0.0023873633602290796, 'max_delta_step': 6}. Best is trial 17 with value: 0.4848178137651822.

Best trial: 17. Best value: 0.484818:  64%|██████▍   | 32/50 [03:37<02:17,  7.65s/it]

[I 2025-12-02 01:34:35,654] Trial 30 finished with value: 0.46153846153846156 and parameters: {'max_depth': 3, 'learning_rate': 0.02783199699450819, 'n_estimators': 1105, 'subsample': 0.5012165751277857, 'colsample_bytree': 0.7030089379794703, 'min_child_weight': 4, 'gamma': 0.018874390049546275, 'reg_alpha': 1.9956573503354453e-05, 'reg_lambda': 0.0010372745101409715, 'max_delta_step': 5}. Best is trial 17 with value: 0.4848178137651822.

Best trial: 17. Best value: 0.484818:  66%|██████▌   | 33/50 [03:44<02:08,  7.56s/it]

[I 2025-12-02 01:34:43,007] Trial 35 pruned.

Best trial: 32. Best value: 0.530364:  68%|██████▊   | 34/50 [03:50<01:53,  7.07s/it]

[I 2025-12-02 01:34:48,946] Trial 32 finished with value: 0.5303643724696356 and parameters: {'max_depth': 3, 'learning_rate': 0.038090453895758186, 'n_estimators': 1139, 'subsample': 0.503471395370268, 'colsample_bytree': 0.7007254351265128, 'min_child_weight': 1, 'gamma': 1.072085681535907, 'reg_alpha': 1.9715636192283882e-05, 'reg_lambda': 0.0010603453502324323, 'max_delta_step': 5}. Best is trial 32 with value: 0.5303643724696356.

Best trial: 32. Best value: 0.530364:  70%|███████   | 35/50 [04:03<02:12,  8.82s/it]

[I 2025-12-02 01:35:01,838] Trial 33 finished with value: 0.4392712550607287 and parameters: {'max_depth': 6, 'learning_rate': 0.025416839947972957, 'n_estimators': 1186, 'subsample': 0.7241380421176248, 'colsample_bytree': 0.8255727332001429, 'min_child_weight': 1, 'gamma': 1.2098490675273255, 'reg_alpha': 0.00020289525741861182, 'reg_lambda': 0.00010572033445059256, 'max_delta_step': 8}. Best is trial 32 with value: 0.5303643724696356.

Best trial: 32. Best value: 0.530364:  72%|███████▏  | 36/50 [04:07<01:43,  7.37s/it]

[I 2025-12-02 01:35:05,819] Trial 34 finished with value: 0.47773279352226716 and parameters: {'max_depth': 6, 'learning_rate': 0.02518806743120538, 'n_estimators': 1111, 'subsample': 0.7043441611287199, 'colsample_bytree': 0.8313829452029088, 'min_child_weight': 1, 'gamma': 0.888772149853119, 'reg_alpha': 2.8168961194433665e-07, 'reg_lambda': 0.022528453084209345, 'max_delta_step': 9}. Best is trial 32 with value: 0.5303643724696356.

Best trial: 32. Best value: 0.530364:  74%|███████▍  | 37/50 [04:12<01:26,  6.67s/it]

[I 2025-12-02 01:35:10,857] Trial 38 pruned.

Best trial: 32. Best value: 0.530364:  76%|███████▌  | 38/50 [04:16<01:10,  5.85s/it]

[I 2025-12-02 01:35:14,808] Trial 37 pruned.

Best trial: 32. Best value: 0.530364:  78%|███████▊  | 39/50 [04:25<01:15,  6.89s/it]

[I 2025-12-02 01:35:24,122] Trial 36 finished with value: 0.47773279352226716 and parameters: {'max_depth': 5, 'learning_rate': 0.025451232113285524, 'n_estimators': 1129, 'subsample': 0.614302930075402, 'colsample_bytree': 0.5909022467734933, 'min_child_weight': 1, 'gamma': 0.3358046244375056, 'reg_alpha': 0.00017147170795129272, 'reg_lambda': 3.3850756960658906e-06, 'max_delta_step': 8}. Best is trial 32 with value: 0.5303643724696356.

Best trial: 32. Best value: 0.530364:  80%|████████  | 40/50 [04:53<02:10, 13.03s/it]

[I 2025-12-02 01:35:51,466] Trial 39 finished with value: 0.451417004048583 and parameters: {'max_depth': 5, 'learning_rate': 0.03984644794974868, 'n_estimators': 1296, 'subsample': 0.6147367110089559, 'colsample_bytree': 0.5854846935279815, 'min_child_weight': 1, 'gamma': 1.1397660451590894, 'reg_alpha': 2.82648971942073e-07, 'reg_lambda': 0.01937998129018095, 'max_delta_step': 10}. Best is trial 32 with value: 0.5303643724696356.

Best trial: 32. Best value: 0.530364:  82%|████████▏ | 41/50 [05:00<01:42, 11.44s/it]

[I 2025-12-02 01:35:59,186] Trial 40 finished with value: 0.451417004048583 and parameters: {'max_depth': 5, 'learning_rate': 0.08549542774622461, 'n_estimators': 1348, 'subsample': 0.6027155188939969, 'colsample_bytree': 0.5869660014867419, 'min_child_weight': 1, 'gamma': 3.8924177645897062, 'reg_alpha': 3.035066352733335e-07, 'reg_lambda': 0.1853586560393698, 'max_delta_step': 10}. Best is trial 32 with value: 0.5303643724696356.

Best trial: 32. Best value: 0.530364:  84%|████████▍ | 42/50 [05:08<01:22, 10.31s/it]

[I 2025-12-02 01:36:06,873] Trial 41 finished with value: 0.458502024291498 and parameters: {'max_depth': 5, 'learning_rate': 0.043003649745299945, 'n_estimators': 1410, 'subsample': 0.6158255367062528, 'colsample_bytree': 0.6055373849120796, 'min_child_weight': 1, 'gamma': 3.871796403097516, 'reg_alpha': 4.014153347927225e-07, 'reg_lambda': 0.016477963235481438, 'max_delta_step': 10}. Best is trial 32 with value: 0.5303643724696356.
[I 2025-12-02 01:36:06,885] Trial 42 finished with value: 0.43218623481781376 and parameters: {'max_depth': 5, 'learning_rate': 0.0923953144081463, 'n_estimators': 1316, 'subsample': 0.5762740775990016, 'colsample_bytree': 0.6161978950480126, 'min_child_weight': 1, 'gamma': 0.7590348212370592, 'reg_alpha': 2.756683255095668e-07, 'reg_lambda': 1.994909552309262e-06, 'max_delta_step': 10}. Best is trial 32 with value: 0.5303643724696356.

Best trial: 32. Best value: 0.530364:  88%|████████▊ | 44/50 [05:15<00:43,  7.20s/it]

[I 2025-12-02 01:36:13,996] Trial 43 pruned.

Best trial: 32. Best value: 0.530364:  90%|█████████ | 45/50 [05:24<00:37,  7.57s/it]

[I 2025-12-02 01:36:22,699] Trial 47 pruned.

Best trial: 32. Best value: 0.530364:  92%|█████████▏| 46/50 [05:29<00:28,  7.08s/it]

[I 2025-12-02 01:36:28,389] Trial 48 pruned.

Best trial: 32. Best value: 0.530364:  94%|█████████▍| 47/50 [05:34<00:19,  6.44s/it]

[I 2025-12-02 01:36:33,106] Trial 45 pruned.

Best trial: 32. Best value: 0.530364:  96%|█████████▌| 48/50 [05:38<00:11,  5.76s/it]

[I 2025-12-02 01:36:37,134] Trial 44 finished with value: 0.4251012145748988 and parameters: {'max_depth': 6, 'learning_rate': 0.024457993577717437, 'n_estimators': 1072, 'subsample': 0.5785242029721045, 'colsample_bytree': 0.6207674515114895, 'min_child_weight': 2, 'gamma': 0.7834857324444469, 'reg_alpha': 0.0005730643898249938, 'reg_lambda': 3.5511882391037562e-06, 'max_delta_step': 9}. Best is trial 32 with value: 0.5303643724696356.

Best trial: 32. Best value: 0.530364:  98%|█████████▊| 49/50 [05:43<00:05,  5.54s/it]

[I 2025-12-02 01:36:42,111] Trial 46 finished with value: 0.5040485829959513 and parameters: {'max_depth': 6, 'learning_rate': 0.024804744334585502, 'n_estimators': 1068, 'subsample': 0.7242277767003495, 'colsample_bytree': 0.6628856546692988, 'min_child_weight': 2, 'gamma': 0.47647306690847974, 'reg_alpha': 8.711541622243349e-06, 'reg_lambda': 0.39530168034476487, 'max_delta_step': 9}. Best is trial 32 with value: 0.5303643724696356.

Best trial: 32. Best value: 0.530364: 100%|██████████| 50/50 [05:43<00:00,  6.88s/it]

[I 2025-12-02 01:36:42,328] Trial 49 pruned.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 01:36:47,689] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 43, Test size: 11
Using Leave-One-Out CV with 43 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.145833:   2%|▏         | 1/50 [00:20<16:36, 20.34s/it]

[I 2025-12-02 01:37:08,013] Trial 0 finished with value: 0.14583333333333334 and parameters: {'max_depth': 7, 'learning_rate': 0.25901218343869675, 'n_estimators': 629, 'subsample': 0.6047189072232414, 'colsample_bytree': 0.9214996364268242, 'min_child_weight': 6, 'gamma': 0.9588980395967139, 'reg_alpha': 2.7295852926014628e-08, 'reg_lambda': 1.1327331586070607e-08, 'max_delta_step': 8}. Best is trial 0 with value: 0.14583333333333334.

Best trial: 3. Best value: 0.444079:   4%|▍         | 2/50 [00:36<14:30, 18.14s/it]

[I 2025-12-02 01:37:24,627] Trial 3 finished with value: 0.444078947368421 and parameters: {'max_depth': 8, 'learning_rate': 0.04157948271931025, 'n_estimators': 1084, 'subsample': 0.7838597322192902, 'colsample_bytree': 0.7367860984569207, 'min_child_weight': 3, 'gamma': 0.31767920208141065, 'reg_alpha': 0.14699252751769265, 'reg_lambda': 2.6611270209533266e-08, 'max_delta_step': 5}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:   6%|▌         | 3/50 [00:39<08:44, 11.15s/it]

[I 2025-12-02 01:37:27,435] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.04989163529309282, 'n_estimators': 1287, 'subsample': 0.5094579543938659, 'colsample_bytree': 0.6414384718195799, 'min_child_weight': 5, 'gamma': 2.0615486769850895, 'reg_alpha': 0.00021405341425509815, 'reg_lambda': 4.077867613537668e-05, 'max_delta_step': 0}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:   8%|▊         | 4/50 [00:54<09:33, 12.47s/it]

[I 2025-12-02 01:37:41,942] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.24068488228183413, 'n_estimators': 1061, 'subsample': 0.5682450242050754, 'colsample_bytree': 0.9618152531737554, 'min_child_weight': 8, 'gamma': 0.3620672047775292, 'reg_alpha': 7.855667223250859e-07, 'reg_lambda': 0.02569493187746848, 'max_delta_step': 2}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  10%|█         | 5/50 [00:54<06:10,  8.23s/it]

[I 2025-12-02 01:37:42,651] Trial 2 finished with value: 0.3026315789473684 and parameters: {'max_depth': 5, 'learning_rate': 0.19826618204250973, 'n_estimators': 1444, 'subsample': 0.7088034430101179, 'colsample_bytree': 0.9969609139479992, 'min_child_weight': 1, 'gamma': 1.8997940953410248, 'reg_alpha': 0.005876359593951398, 'reg_lambda': 1.8626497614424638e-08, 'max_delta_step': 4}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  12%|█▏        | 6/50 [01:03<06:11,  8.44s/it]

[I 2025-12-02 01:37:51,505] Trial 6 finished with value: 0.35526315789473684 and parameters: {'max_depth': 7, 'learning_rate': 0.09192109776185953, 'n_estimators': 663, 'subsample': 0.952838789725265, 'colsample_bytree': 0.8629785701984263, 'min_child_weight': 2, 'gamma': 0.8884734361557206, 'reg_alpha': 0.020097420541908526, 'reg_lambda': 3.66243767472508e-08, 'max_delta_step': 8}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  14%|█▍        | 7/50 [01:06<04:44,  6.62s/it]

[I 2025-12-02 01:37:54,358] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.06714730379122962, 'n_estimators': 299, 'subsample': 0.9338158924318231, 'colsample_bytree': 0.9362497499964906, 'min_child_weight': 5, 'gamma': 3.069676431081378, 'reg_alpha': 0.28227137881365155, 'reg_lambda': 3.3630745655534614e-08, 'max_delta_step': 4}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  16%|█▌        | 8/50 [01:06<03:12,  4.59s/it]

[I 2025-12-02 01:37:54,618] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.0160196182595281, 'n_estimators': 332, 'subsample': 0.9364566000371908, 'colsample_bytree': 0.6053582350825653, 'min_child_weight': 9, 'gamma': 2.0469473059047436, 'reg_alpha': 5.7797971611892875e-08, 'reg_lambda': 0.0003684501304831891, 'max_delta_step': 10}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  18%|█▊        | 9/50 [01:15<03:55,  5.74s/it]

[I 2025-12-02 01:38:02,883] Trial 10 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.021726642435619045, 'n_estimators': 216, 'subsample': 0.524990361241003, 'colsample_bytree': 0.6476976764373823, 'min_child_weight': 8, 'gamma': 3.96076282507773, 'reg_alpha': 0.0707703377029407, 'reg_lambda': 3.725873588289967e-07, 'max_delta_step': 1}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  20%|██        | 10/50 [01:26<05:01,  7.55s/it]

[I 2025-12-02 01:38:14,478] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.03638777395333695, 'n_estimators': 1498, 'subsample': 0.9938044527941661, 'colsample_bytree': 0.9553332262534214, 'min_child_weight': 7, 'gamma': 0.3474923446808337, 'reg_alpha': 2.1849956537960022e-06, 'reg_lambda': 3.4028874538914223e-08, 'max_delta_step': 4}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  22%|██▏       | 11/50 [01:36<05:15,  8.10s/it]

[I 2025-12-02 01:38:23,838] Trial 9 finished with value: 0.020833333333333332 and parameters: {'max_depth': 6, 'learning_rate': 0.018192336098571887, 'n_estimators': 912, 'subsample': 0.6984331360435703, 'colsample_bytree': 0.954462959142792, 'min_child_weight': 5, 'gamma': 3.662623330102952, 'reg_alpha': 5.6859614802964414e-08, 'reg_lambda': 1.8563433556603303e-05, 'max_delta_step': 3}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  24%|██▍       | 12/50 [01:39<04:14,  6.69s/it]

[I 2025-12-02 01:38:27,270] Trial 12 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.03444230677723832, 'n_estimators': 719, 'subsample': 0.7029268584024986, 'colsample_bytree': 0.5257687806836149, 'min_child_weight': 8, 'gamma': 3.9973600665981044, 'reg_alpha': 0.003774809974181202, 'reg_lambda': 5.980380054021003e-06, 'max_delta_step': 0}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  26%|██▌       | 13/50 [01:46<04:07,  6.68s/it]

[I 2025-12-02 01:38:33,955] Trial 11 finished with value: 0.3399122807017544 and parameters: {'max_depth': 8, 'learning_rate': 0.04535482152623695, 'n_estimators': 1216, 'subsample': 0.71913579480659, 'colsample_bytree': 0.5770184219908809, 'min_child_weight': 4, 'gamma': 3.6662488487466183, 'reg_alpha': 8.251958337310704e-07, 'reg_lambda': 1.8967490148911556e-08, 'max_delta_step': 10}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  28%|██▊       | 14/50 [02:02<05:41,  9.48s/it]

[I 2025-12-02 01:38:49,910] Trial 13 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.010467650771483731, 'n_estimators': 1053, 'subsample': 0.8093859247373516, 'colsample_bytree': 0.7591500942371452, 'min_child_weight': 3, 'gamma': 4.47776048905697, 'reg_alpha': 4.657490672428121, 'reg_lambda': 4.8733703853875125, 'max_delta_step': 6}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  30%|███       | 15/50 [02:03<04:04,  6.99s/it]

[I 2025-12-02 01:38:51,116] Trial 14 finished with value: 0.33442982456140347 and parameters: {'max_depth': 9, 'learning_rate': 0.10723916352171026, 'n_estimators': 718, 'subsample': 0.8285336424823694, 'colsample_bytree': 0.7915451575768455, 'min_child_weight': 2, 'gamma': 1.0810137201387284, 'reg_alpha': 3.3857492481978118, 'reg_lambda': 1.7616577760750966e-06, 'max_delta_step': 7}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  32%|███▏      | 16/50 [02:06<03:13,  5.69s/it]

[I 2025-12-02 01:38:53,806] Trial 16 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.08411140944960274, 'n_estimators': 547, 'subsample': 0.8186070787014561, 'colsample_bytree': 0.8131747889228379, 'min_child_weight': 2, 'gamma': 1.1979460637615218, 'reg_alpha': 7.479145968353189, 'reg_lambda': 0.5932397815981622, 'max_delta_step': 7}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  34%|███▍      | 17/50 [02:16<03:58,  7.23s/it]

[I 2025-12-02 01:39:04,599] Trial 15 finished with value: 0.381578947368421 and parameters: {'max_depth': 9, 'learning_rate': 0.10148796995611223, 'n_estimators': 1096, 'subsample': 0.8332494763288586, 'colsample_bytree': 0.8135878169678348, 'min_child_weight': 2, 'gamma': 1.1668086592707616, 'reg_alpha': 0.5344904535127023, 'reg_lambda': 1.5578795978278583, 'max_delta_step': 7}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  36%|███▌      | 18/50 [02:21<03:29,  6.55s/it]

[I 2025-12-02 01:39:09,562] Trial 18 finished with value: 0.3497807017543859 and parameters: {'max_depth': 8, 'learning_rate': 0.09579653993609828, 'n_estimators': 480, 'subsample': 0.8378306136108216, 'colsample_bytree': 0.8394332741236955, 'min_child_weight': 1, 'gamma': 0.9906722343864619, 'reg_alpha': 0.0002507556273552208, 'reg_lambda': 0.0007670764105817637, 'max_delta_step': 7}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  38%|███▊      | 19/50 [02:22<02:32,  4.91s/it]

[I 2025-12-02 01:39:10,670] Trial 17 pruned.

Best trial: 3. Best value: 0.444079:  40%|████      | 20/50 [02:36<03:46,  7.54s/it]

[I 2025-12-02 01:39:24,324] Trial 19 finished with value: 0.41776315789473684 and parameters: {'max_depth': 8, 'learning_rate': 0.13220948580112707, 'n_estimators': 894, 'subsample': 0.9141464298397048, 'colsample_bytree': 0.8584234598187024, 'min_child_weight': 1, 'gamma': 0.08481531238040585, 'reg_alpha': 0.00020700299100848883, 'reg_lambda': 0.0012349133569980503, 'max_delta_step': 8}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  42%|████▏     | 21/50 [02:48<04:18,  8.91s/it]

[I 2025-12-02 01:39:36,422] Trial 20 finished with value: 0.3607456140350877 and parameters: {'max_depth': 9, 'learning_rate': 0.1052244812414578, 'n_estimators': 927, 'subsample': 0.868618130382989, 'colsample_bytree': 0.713306406706345, 'min_child_weight': 3, 'gamma': 0.0854123246686769, 'reg_alpha': 0.0003275869537139362, 'reg_lambda': 0.0035693951152481565, 'max_delta_step': 6}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  44%|████▍     | 22/50 [02:53<03:32,  7.59s/it]

[I 2025-12-02 01:39:40,929] Trial 22 finished with value: 0.41776315789473684 and parameters: {'max_depth': 9, 'learning_rate': 0.16061266485088563, 'n_estimators': 883, 'subsample': 0.771827769899309, 'colsample_bytree': 0.7051084989485473, 'min_child_weight': 3, 'gamma': 0.02207335653313719, 'reg_alpha': 0.3718660722078171, 'reg_lambda': 0.01008977034732399, 'max_delta_step': 5}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  46%|████▌     | 23/50 [02:53<02:27,  5.46s/it]

[I 2025-12-02 01:39:41,411] Trial 21 finished with value: 0.41776315789473684 and parameters: {'max_depth': 9, 'learning_rate': 0.16380622712863682, 'n_estimators': 913, 'subsample': 0.8775497651221896, 'colsample_bytree': 0.7093171247175984, 'min_child_weight': 3, 'gamma': 0.006369268805063222, 'reg_alpha': 0.4413209777226915, 'reg_lambda': 0.009745331937158864, 'max_delta_step': 5}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  48%|████▊     | 24/50 [03:09<03:39,  8.43s/it]

[I 2025-12-02 01:39:56,792] Trial 23 finished with value: 0.3969298245614035 and parameters: {'max_depth': 6, 'learning_rate': 0.1539401662148641, 'n_estimators': 929, 'subsample': 0.8840660855055555, 'colsample_bytree': 0.7088691911229533, 'min_child_weight': 3, 'gamma': 0.015252282168825279, 'reg_alpha': 1.8769207204509927e-05, 'reg_lambda': 0.01090443720223317, 'max_delta_step': 5}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  50%|█████     | 25/50 [03:20<03:54,  9.40s/it]

[I 2025-12-02 01:40:08,434] Trial 26 finished with value: 0.3497807017543859 and parameters: {'max_depth': 8, 'learning_rate': 0.14891923620202896, 'n_estimators': 787, 'subsample': 0.8978002976765919, 'colsample_bytree': 0.7041270895932985, 'min_child_weight': 4, 'gamma': 0.5618453686411597, 'reg_alpha': 2.5279562288786587e-05, 'reg_lambda': 0.10522481305995736, 'max_delta_step': 5}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  52%|█████▏    | 26/50 [03:25<03:12,  8.01s/it]

[I 2025-12-02 01:40:13,219] Trial 25 finished with value: 0.35526315789473684 and parameters: {'max_depth': 8, 'learning_rate': 0.1630653043104026, 'n_estimators': 925, 'subsample': 0.7667975234525066, 'colsample_bytree': 0.7157291496590164, 'min_child_weight': 3, 'gamma': 0.008281385302708666, 'reg_alpha': 3.595251095703287e-05, 'reg_lambda': 0.019959634336420094, 'max_delta_step': 5}. Best is trial 3 with value: 0.444078947368421.
[I 2025-12-02 01:40:13,228] Trial 24 finished with value: 0.42324561403508776 and parameters: {'max_depth': 8, 'learning_rate': 0.17891564846687202, 'n_estimators': 1073, 'subsample': 0.8851908990399239, 'colsample_bytree': 0.7038817563677955, 'min_child_weight': 3, 'gamma': 0.07071112616967747, 'reg_alpha': 0.3418082083482629, 'reg_lambda': 0.16862614010108393, 'max_delta_step': 9}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  56%|█████▌    | 28/50 [03:37<02:34,  7.02s/it]

[I 2025-12-02 01:40:24,961] Trial 27 finished with value: 0.3969298245614035 and parameters: {'max_depth': 8, 'learning_rate': 0.1659595974579422, 'n_estimators': 815, 'subsample': 0.8918512416312168, 'colsample_bytree': 0.8861213817177469, 'min_child_weight': 4, 'gamma': 0.4307604470641164, 'reg_alpha': 0.0014494994724279153, 'reg_lambda': 0.170871079452077, 'max_delta_step': 5}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  58%|█████▊    | 29/50 [03:48<02:49,  8.08s/it]

[I 2025-12-02 01:40:36,227] Trial 31 pruned.

Best trial: 3. Best value: 0.444079:  60%|██████    | 30/50 [03:58<02:53,  8.68s/it]

[I 2025-12-02 01:40:46,603] Trial 32 pruned.

Best trial: 3. Best value: 0.444079:  62%|██████▏   | 31/50 [04:01<02:13,  7.01s/it]

[I 2025-12-02 01:40:49,164] Trial 28 finished with value: 0.35526315789473684 and parameters: {'max_depth': 8, 'learning_rate': 0.02822849720648106, 'n_estimators': 1192, 'subsample': 0.7773439284375628, 'colsample_bytree': 0.889300642969652, 'min_child_weight': 4, 'gamma': 1.596761625789937, 'reg_alpha': 0.0019124579384103006, 'reg_lambda': 0.00015594076276796175, 'max_delta_step': 9}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  64%|██████▍   | 32/50 [04:05<01:50,  6.12s/it]

[I 2025-12-02 01:40:52,993] Trial 30 finished with value: 0.3135964912280702 and parameters: {'max_depth': 7, 'learning_rate': 0.06251474736397875, 'n_estimators': 1206, 'subsample': 0.6466706226915935, 'colsample_bytree': 0.7563959271932423, 'min_child_weight': 4, 'gamma': 1.5016884002546824, 'reg_alpha': 0.002053325265912451, 'reg_lambda': 8.202456087085016e-05, 'max_delta_step': 9}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  66%|██████▌   | 33/50 [04:07<01:23,  4.92s/it]

[I 2025-12-02 01:40:54,914] Trial 29 finished with value: 0.3969298245614035 and parameters: {'max_depth': 7, 'learning_rate': 0.02683978859226951, 'n_estimators': 1170, 'subsample': 0.9890768886855297, 'colsample_bytree': 0.8824014280021186, 'min_child_weight': 4, 'gamma': 1.6886493510311467, 'reg_alpha': 0.003995152684866065, 'reg_lambda': 9.963039251972666e-05, 'max_delta_step': 9}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  68%|██████▊   | 34/50 [04:07<00:59,  3.71s/it]

[I 2025-12-02 01:40:55,641] Trial 33 pruned.

Best trial: 3. Best value: 0.444079:  70%|███████   | 35/50 [04:36<02:43, 10.88s/it]

[I 2025-12-02 01:41:23,865] Trial 34 finished with value: 0.35526315789473684 and parameters: {'max_depth': 9, 'learning_rate': 0.2742008251456872, 'n_estimators': 1012, 'subsample': 0.9222425612130536, 'colsample_bytree': 0.7504511193484517, 'min_child_weight': 2, 'gamma': 0.654455195459599, 'reg_alpha': 0.8881548013598269, 'reg_lambda': 0.10452206224496915, 'max_delta_step': 8}. Best is trial 3 with value: 0.444078947368421.

Best trial: 3. Best value: 0.444079:  72%|███████▏  | 36/50 [04:39<02:02,  8.77s/it]

[I 2025-12-02 01:41:27,562] Trial 35 finished with value: 0.3969298245614035 and parameters: {'max_depth': 10, 'learning_rate': 0.2981338409360057, 'n_estimators': 991, 'subsample': 0.864613545544116, 'colsample_bytree': 0.65501835885614, 'min_child_weight': 2, 'gamma': 2.593379627648999, 'reg_alpha': 1.069346561655265, 'reg_lambda': 0.08730928686150177, 'max_delta_step': 8}. Best is trial 3 with value: 0.444078947368421.

Best trial: 36. Best value: 0.449561:  74%|███████▍  | 37/50 [04:41<01:26,  6.66s/it]

[I 2025-12-02 01:41:29,208] Trial 36 finished with value: 0.44956140350877194 and parameters: {'max_depth': 10, 'learning_rate': 0.27810749555558845, 'n_estimators': 1007, 'subsample': 0.85947172864537, 'colsample_bytree': 0.6174669815559544, 'min_child_weight': 2, 'gamma': 2.478039650367816, 'reg_alpha': 0.7731601023397128, 'reg_lambda': 0.05918031042123663, 'max_delta_step': 8}. Best is trial 36 with value: 0.44956140350877194.

Best trial: 36. Best value: 0.449561:  76%|███████▌  | 38/50 [04:43<01:02,  5.22s/it]

[I 2025-12-02 01:41:31,028] Trial 37 finished with value: 0.39144736842105265 and parameters: {'max_depth': 10, 'learning_rate': 0.1337076622118431, 'n_estimators': 1008, 'subsample': 0.9161571395116048, 'colsample_bytree': 0.6826874822204769, 'min_child_weight': 2, 'gamma': 0.6054545338704708, 'reg_alpha': 0.9373588699358003, 'reg_lambda': 0.07569896086462305, 'max_delta_step': 6}. Best is trial 36 with value: 0.44956140350877194.

Best trial: 36. Best value: 0.449561:  78%|███████▊  | 39/50 [04:51<01:08,  6.19s/it]

[I 2025-12-02 01:41:39,503] Trial 38 pruned.

Best trial: 36. Best value: 0.449561:  80%|████████  | 40/50 [05:01<01:13,  7.37s/it]

[I 2025-12-02 01:41:49,659] Trial 40 pruned.

Best trial: 36. Best value: 0.449561:  82%|████████▏ | 41/50 [05:03<00:49,  5.52s/it]

[I 2025-12-02 01:41:50,852] Trial 42 pruned.

Best trial: 36. Best value: 0.449561:  84%|████████▍ | 42/50 [05:21<01:13,  9.23s/it]

[I 2025-12-02 01:42:08,760] Trial 39 finished with value: 0.42872807017543857 and parameters: {'max_depth': 10, 'learning_rate': 0.20427035421261158, 'n_estimators': 1297, 'subsample': 0.9656805930893619, 'colsample_bytree': 0.6836443284164282, 'min_child_weight': 1, 'gamma': 0.2949392360467575, 'reg_alpha': 0.09305907773263919, 'reg_lambda': 0.0020376016835725354, 'max_delta_step': 3}. Best is trial 36 with value: 0.44956140350877194.

Best trial: 36. Best value: 0.449561:  86%|████████▌ | 43/50 [05:29<01:03,  9.05s/it]

[I 2025-12-02 01:42:17,392] Trial 44 finished with value: 0.39144736842105265 and parameters: {'max_depth': 9, 'learning_rate': 0.1285837245041686, 'n_estimators': 835, 'subsample': 0.7481677624195082, 'colsample_bytree': 0.5633549026646854, 'min_child_weight': 3, 'gamma': 0.8257703690901169, 'reg_alpha': 0.18104838549974864, 'reg_lambda': 0.005132381684419786, 'max_delta_step': 4}. Best is trial 36 with value: 0.44956140350877194.

Best trial: 36. Best value: 0.449561:  88%|████████▊ | 44/50 [05:36<00:50,  8.43s/it]

[I 2025-12-02 01:42:24,358] Trial 41 finished with value: 0.42434210526315785 and parameters: {'max_depth': 10, 'learning_rate': 0.20472070468202172, 'n_estimators': 1331, 'subsample': 0.9552641322849401, 'colsample_bytree': 0.6125466784162227, 'min_child_weight': 1, 'gamma': 4.902239393529024, 'reg_alpha': 0.09273261960787156, 'reg_lambda': 0.8818687609295915, 'max_delta_step': 10}. Best is trial 36 with value: 0.44956140350877194.

Best trial: 36. Best value: 0.449561:  90%|█████████ | 45/50 [05:45<00:42,  8.42s/it]

[I 2025-12-02 01:42:32,771] Trial 43 finished with value: 0.22916666666666666 and parameters: {'max_depth': 6, 'learning_rate': 0.046129786173947446, 'n_estimators': 1429, 'subsample': 0.7429253292481843, 'colsample_bytree': 0.6227859254462751, 'min_child_weight': 5, 'gamma': 4.918564825536847, 'reg_alpha': 0.015597227129935212, 'reg_lambda': 0.31598412107400714, 'max_delta_step': 3}. Best is trial 36 with value: 0.44956140350877194.

Best trial: 36. Best value: 0.449561:  92%|█████████▏| 46/50 [05:49<00:28,  7.11s/it]

[I 2025-12-02 01:42:36,830] Trial 47 pruned.

Best trial: 36. Best value: 0.449561:  94%|█████████▍| 47/50 [05:57<00:22,  7.63s/it]

[I 2025-12-02 01:42:45,666] Trial 49 pruned.

Best trial: 36. Best value: 0.449561:  96%|█████████▌| 48/50 [06:04<00:14,  7.20s/it]

[I 2025-12-02 01:42:51,874] Trial 48 pruned.

Best trial: 36. Best value: 0.449561:  98%|█████████▊| 49/50 [06:04<00:05,  5.27s/it]

[I 2025-12-02 01:42:52,641] Trial 45 finished with value: 0.3969298245614035 and parameters: {'max_depth': 3, 'learning_rate': 0.04546300815697965, 'n_estimators': 1428, 'subsample': 0.7320280665216896, 'colsample_bytree': 0.5604414960677981, 'min_child_weight': 2, 'gamma': 0.7812300224507114, 'reg_alpha': 0.23299036586491736, 'reg_lambda': 0.0006098131798249591, 'max_delta_step': 3}. Best is trial 36 with value: 0.44956140350877194.

Best trial: 36. Best value: 0.449561: 100%|██████████| 50/50 [06:12<00:00,  7.45s/it]

[I 2025-12-02 01:43:00,418] Trial 46 finished with value: 0.36622807017543857 and parameters: {'max_depth': 8, 'learning_rate': 0.04201273128459642, 'n_estimators': 1434, 'subsample': 0.9106115156178946, 'colsample_bytree': 0.6246919074785552, 'min_child_weight': 1, 'gamma': 4.9946008670166275, 'reg_alpha': 1.874334563920028, 'reg_lambda': 0.0004054574602221973, 'max_delta_step': 2}. Best is trial 36 with value: 0.44956140350877194.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.623158                0.485714      0.542857
1    17_1         loo       0.530364                0.485714      0.514286
2     9_1         loo       0.445080                0.450000      0.566667
3    19_1         loo       0.449561                0.183333      0.166667

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.028571          0.571429               0.4        50          44
1 -0.028571          0.571429               0.4        50          45
2 -0.100000          0.500000               0.4        50          42
3 -0.633333          0.166667               0.2        50          43

   test_size
0         12
1         12
2         11
3         11
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.623158                0.485714      0.542857
1    17_1         loo       0.530364                0.485714      0.514286
2     9_1         loo       0.445080                0.450000      0.566667
3    19_1         loo       0.449561                0.183333      0.166667

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.028571          0.571429               0.4        50          44
1 -0.028571          0.571429               0.4        50          45
2 -0.100000          0.500000               0.4        50          42
3 -0.633333          0.166667               0.2        50          43

   test_size
0         12
1         12
2         11
3         11

In [ ]:

# Combined embedings
datasets = task_comb_dfs_ad_lbd

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_lbd_{CV_STRATEGY}_tasks/xgb_results_combined_ad_lbd_extended_{CV_STRATEGY}_tasks",
    split_param="emb_",
)
print(summary)

[I 2025-12-02 01:43:04,593] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 42, Test size: 11
Using Leave-One-Out CV with 42 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0:   2%|▏         | 1/50 [00:15<13:03, 15.98s/it]

[I 2025-12-02 01:43:20,568] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.14347621744745825, 'n_estimators': 510, 'subsample': 0.7883089385444384, 'colsample_bytree': 0.8798649175530537, 'min_child_weight': 6, 'gamma': 0.9954820174631718, 'reg_alpha': 2.8793810024750396e-06, 'reg_lambda': 0.09985402416527304, 'max_delta_step': 6}. Best is trial 3 with value: 0.0.

Best trial: 3. Best value: 0:   4%|▍         | 2/50 [00:26<10:21, 12.94s/it]

[I 2025-12-02 01:43:31,380] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.014740132091675837, 'n_estimators': 873, 'subsample': 0.8127378072583313, 'colsample_bytree': 0.8702390909814705, 'min_child_weight': 5, 'gamma': 3.6338247039546925, 'reg_alpha': 0.0007772478218293647, 'reg_lambda': 1.024212535031905, 'max_delta_step': 2}. Best is trial 3 with value: 0.0.

Best trial: 0. Best value: 0.0789474:   6%|▌         | 3/50 [00:29<06:27,  8.24s/it]

[I 2025-12-02 01:43:34,033] Trial 0 finished with value: 0.07894736842105263 and parameters: {'max_depth': 3, 'learning_rate': 0.023686690804758475, 'n_estimators': 990, 'subsample': 0.6056951066364433, 'colsample_bytree': 0.7453339704954778, 'min_child_weight': 5, 'gamma': 3.7664748176622593, 'reg_alpha': 1.308627586772801e-05, 'reg_lambda': 0.02372551509584766, 'max_delta_step': 2}. Best is trial 0 with value: 0.07894736842105263.

Best trial: 2. Best value: 0.620137:   8%|▊         | 4/50 [00:29<03:53,  5.08s/it]

[I 2025-12-02 01:43:34,273] Trial 2 finished with value: 0.620137299771167 and parameters: {'max_depth': 8, 'learning_rate': 0.06423455849458792, 'n_estimators': 954, 'subsample': 0.7432631775238081, 'colsample_bytree': 0.7269468502100637, 'min_child_weight': 3, 'gamma': 1.9251304031167615, 'reg_alpha': 1.895287071464398e-06, 'reg_lambda': 0.003669440027278973, 'max_delta_step': 10}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  10%|█         | 5/50 [00:37<04:40,  6.24s/it]

[I 2025-12-02 01:43:42,568] Trial 6 finished with value: 0.4473684210526316 and parameters: {'max_depth': 8, 'learning_rate': 0.1077547761998685, 'n_estimators': 243, 'subsample': 0.5983281988208492, 'colsample_bytree': 0.9693212859126898, 'min_child_weight': 4, 'gamma': 3.284783979613798, 'reg_alpha': 5.740727115278652e-06, 'reg_lambda': 2.0093257063568212e-05, 'max_delta_step': 0}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  12%|█▏        | 6/50 [00:49<05:46,  7.89s/it]

[I 2025-12-02 01:43:53,650] Trial 7 finished with value: 0.5240274599542334 and parameters: {'max_depth': 3, 'learning_rate': 0.020010934733810812, 'n_estimators': 520, 'subsample': 0.7052746626164663, 'colsample_bytree': 0.5413700724564949, 'min_child_weight': 2, 'gamma': 3.344988084071852, 'reg_alpha': 1.753211401884094e-08, 'reg_lambda': 1.4832944222734904e-07, 'max_delta_step': 2}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  14%|█▍        | 7/50 [00:56<05:39,  7.89s/it]

[I 2025-12-02 01:44:01,541] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.058961024886564455, 'n_estimators': 1432, 'subsample': 0.8889681082820432, 'colsample_bytree': 0.9080798361967446, 'min_child_weight': 9, 'gamma': 1.6733051399045191, 'reg_alpha': 0.039400503653216436, 'reg_lambda': 3.578633649497593, 'max_delta_step': 7}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  16%|█▌        | 8/50 [01:00<04:31,  6.46s/it]

[I 2025-12-02 01:44:04,943] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.11339229738840048, 'n_estimators': 764, 'subsample': 0.5896257690667603, 'colsample_bytree': 0.8434284128603657, 'min_child_weight': 9, 'gamma': 0.26151080523243164, 'reg_alpha': 7.077692130135946, 'reg_lambda': 0.00034576451625648394, 'max_delta_step': 10}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  18%|█▊        | 9/50 [01:19<07:06, 10.41s/it]

[I 2025-12-02 01:44:24,042] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.03530099841012697, 'n_estimators': 1058, 'subsample': 0.9543035968964039, 'colsample_bytree': 0.9497364001719739, 'min_child_weight': 8, 'gamma': 3.6925387121151667, 'reg_alpha': 0.005641266395525785, 'reg_lambda': 2.7165409503166203e-06, 'max_delta_step': 4}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  20%|██        | 10/50 [01:19<04:51,  7.28s/it]

[I 2025-12-02 01:44:24,312] Trial 5 finished with value: 0.4759725400457666 and parameters: {'max_depth': 6, 'learning_rate': 0.04815717078951894, 'n_estimators': 1092, 'subsample': 0.8718668721043406, 'colsample_bytree': 0.8873596779341713, 'min_child_weight': 1, 'gamma': 2.1217290627797474, 'reg_alpha': 7.225082532215457e-05, 'reg_lambda': 0.0564202806083659, 'max_delta_step': 5}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  22%|██▏       | 11/50 [01:28<04:59,  7.67s/it]

[I 2025-12-02 01:44:32,876] Trial 11 pruned.

Best trial: 2. Best value: 0.620137:  24%|██▍       | 12/50 [01:33<04:25,  6.99s/it]

[I 2025-12-02 01:44:38,292] Trial 10 finished with value: 0.5720823798627002 and parameters: {'max_depth': 8, 'learning_rate': 0.044590879446044326, 'n_estimators': 1110, 'subsample': 0.7400351483070631, 'colsample_bytree': 0.5508750969257563, 'min_child_weight': 2, 'gamma': 0.7146771554574993, 'reg_alpha': 0.7126613281999798, 'reg_lambda': 5.14041154057616e-08, 'max_delta_step': 1}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  26%|██▌       | 13/50 [01:34<03:04,  4.98s/it]

[I 2025-12-02 01:44:38,646] Trial 12 pruned.

Best trial: 2. Best value: 0.620137:  28%|██▊       | 14/50 [01:48<04:42,  7.84s/it]

[I 2025-12-02 01:44:53,110] Trial 14 finished with value: 0.545766590389016 and parameters: {'max_depth': 8, 'learning_rate': 0.2655547806745806, 'n_estimators': 628, 'subsample': 0.6955510707425374, 'colsample_bytree': 0.5600121604160465, 'min_child_weight': 2, 'gamma': 4.974023608380937, 'reg_alpha': 4.2527631904286075e-08, 'reg_lambda': 1.1232522712978347e-08, 'max_delta_step': 10}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  30%|███       | 15/50 [01:51<03:47,  6.50s/it]

[I 2025-12-02 01:44:56,502] Trial 15 pruned.

Best trial: 2. Best value: 0.620137:  32%|███▏      | 16/50 [01:53<02:46,  4.89s/it]

[I 2025-12-02 01:44:57,643] Trial 16 pruned.

Best trial: 2. Best value: 0.620137:  34%|███▍      | 17/50 [01:58<02:47,  5.07s/it]

[I 2025-12-02 01:45:03,146] Trial 17 pruned.

Best trial: 2. Best value: 0.620137:  36%|███▌      | 18/50 [02:01<02:18,  4.33s/it]

[I 2025-12-02 01:45:05,756] Trial 13 finished with value: 0.5766590389016018 and parameters: {'max_depth': 10, 'learning_rate': 0.2836405660872863, 'n_estimators': 1396, 'subsample': 0.502588937720845, 'colsample_bytree': 0.6715358556591676, 'min_child_weight': 3, 'gamma': 2.5848754151292765, 'reg_alpha': 2.083417606325291e-08, 'reg_lambda': 0.0009390403844123453, 'max_delta_step': 10}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  38%|███▊      | 19/50 [02:10<02:58,  5.75s/it]

[I 2025-12-02 01:45:14,815] Trial 21 pruned.

Best trial: 2. Best value: 0.620137:  40%|████      | 20/50 [02:36<05:57, 11.91s/it]

[I 2025-12-02 01:45:41,076] Trial 18 finished with value: 0.5675057208237986 and parameters: {'max_depth': 9, 'learning_rate': 0.03472881082533511, 'n_estimators': 1284, 'subsample': 0.7388583460869733, 'colsample_bytree': 0.6330083788164782, 'min_child_weight': 1, 'gamma': 0.26716973477934697, 'reg_alpha': 0.15538987825478354, 'reg_lambda': 0.0012991316614291853, 'max_delta_step': 8}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  42%|████▏     | 21/50 [02:37<04:09,  8.59s/it]

[I 2025-12-02 01:45:41,925] Trial 19 finished with value: 0.545766590389016 and parameters: {'max_depth': 9, 'learning_rate': 0.034255073670281085, 'n_estimators': 1207, 'subsample': 0.7759240771644212, 'colsample_bytree': 0.6676683843380261, 'min_child_weight': 1, 'gamma': 0.025241425156381725, 'reg_alpha': 0.14068594151406796, 'reg_lambda': 1.6550286949199335e-05, 'max_delta_step': 4}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  44%|████▍     | 22/50 [02:41<03:27,  7.41s/it]

[I 2025-12-02 01:45:46,572] Trial 22 finished with value: 0.545766590389016 and parameters: {'max_depth': 10, 'learning_rate': 0.1773536996522161, 'n_estimators': 773, 'subsample': 0.9916388347237813, 'colsample_bytree': 0.6842776594410818, 'min_child_weight': 1, 'gamma': 2.6216721182713467, 'reg_alpha': 2.4419161860117026e-07, 'reg_lambda': 0.00528676268405221, 'max_delta_step': 9}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  46%|████▌     | 23/50 [02:45<02:47,  6.21s/it]

[I 2025-12-02 01:45:49,976] Trial 20 finished with value: 0.4977116704805492 and parameters: {'max_depth': 7, 'learning_rate': 0.010120544586345806, 'n_estimators': 781, 'subsample': 0.801832267703012, 'colsample_bytree': 0.69974629429825, 'min_child_weight': 1, 'gamma': 1.8910064606623984, 'reg_alpha': 0.14658564910794422, 'reg_lambda': 1.3825385414936625e-05, 'max_delta_step': 4}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  48%|████▊     | 24/50 [02:45<01:55,  4.46s/it]

[I 2025-12-02 01:45:50,352] Trial 24 pruned.

Best trial: 2. Best value: 0.620137:  50%|█████     | 25/50 [02:50<01:50,  4.40s/it]

[I 2025-12-02 01:45:54,630] Trial 25 pruned.

Best trial: 2. Best value: 0.620137:  52%|█████▏    | 26/50 [02:53<01:38,  4.10s/it]

[I 2025-12-02 01:45:58,014] Trial 27 pruned.

Best trial: 2. Best value: 0.620137:  54%|█████▍    | 27/50 [02:55<01:17,  3.39s/it]

[I 2025-12-02 01:45:59,750] Trial 26 pruned.

Best trial: 2. Best value: 0.620137:  56%|█████▌    | 28/50 [03:03<01:45,  4.80s/it]

[I 2025-12-02 01:46:07,844] Trial 28 pruned.

Best trial: 2. Best value: 0.620137:  58%|█████▊    | 29/50 [03:24<03:22,  9.63s/it]

[I 2025-12-02 01:46:28,753] Trial 23 finished with value: 0.528604118993135 and parameters: {'max_depth': 7, 'learning_rate': 0.17481566139433313, 'n_estimators': 1498, 'subsample': 0.9633642206229196, 'colsample_bytree': 0.8015638009455225, 'min_child_weight': 4, 'gamma': 4.473913864893708, 'reg_alpha': 3.0442179874713074e-07, 'reg_lambda': 0.008492937096801236, 'max_delta_step': 4}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  60%|██████    | 30/50 [03:37<03:35, 10.80s/it]

[I 2025-12-02 01:46:42,270] Trial 29 finished with value: 0.545766590389016 and parameters: {'max_depth': 10, 'learning_rate': 0.047911572130166905, 'n_estimators': 1445, 'subsample': 0.5037507021263833, 'colsample_bytree': 0.7690624978273889, 'min_child_weight': 3, 'gamma': 2.2114235937880546, 'reg_alpha': 0.0015047931014165886, 'reg_lambda': 0.36132532571413833, 'max_delta_step': 6}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  62%|██████▏   | 31/50 [03:40<02:40,  8.46s/it]

[I 2025-12-02 01:46:45,261] Trial 30 finished with value: 0.5720823798627002 and parameters: {'max_depth': 10, 'learning_rate': 0.044519366198004076, 'n_estimators': 1480, 'subsample': 0.8495078275009095, 'colsample_bytree': 0.6069689663810423, 'min_child_weight': 3, 'gamma': 2.1768530427890376, 'reg_alpha': 0.0018303426521503463, 'reg_lambda': 0.00019848357595241275, 'max_delta_step': 6}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  64%|██████▍   | 32/50 [03:45<02:10,  7.28s/it]

[I 2025-12-02 01:46:49,786] Trial 31 finished with value: 0.5720823798627002 and parameters: {'max_depth': 9, 'learning_rate': 0.1650475040256245, 'n_estimators': 1359, 'subsample': 0.8337099447098155, 'colsample_bytree': 0.6265390068975116, 'min_child_weight': 2, 'gamma': 2.322076838963645, 'reg_alpha': 1.1321053046367988e-08, 'reg_lambda': 0.3451264771809941, 'max_delta_step': 3}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  66%|██████▌   | 33/50 [03:52<02:02,  7.23s/it]

[I 2025-12-02 01:46:56,901] Trial 35 pruned.

Best trial: 2. Best value: 0.620137:  68%|██████▊   | 34/50 [03:58<01:49,  6.83s/it]

[I 2025-12-02 01:47:02,791] Trial 32 finished with value: 0.5194508009153318 and parameters: {'max_depth': 9, 'learning_rate': 0.025141108205930036, 'n_estimators': 987, 'subsample': 0.547440075513839, 'colsample_bytree': 0.7506911563809342, 'min_child_weight': 2, 'gamma': 2.4315457325102003, 'reg_alpha': 1.9527048793190887e-05, 'reg_lambda': 0.2768128667730057, 'max_delta_step': 3}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  70%|███████   | 35/50 [04:06<01:47,  7.16s/it]

[I 2025-12-02 01:47:10,738] Trial 37 pruned.

Best trial: 2. Best value: 0.620137:  72%|███████▏  | 36/50 [04:13<01:39,  7.10s/it]

[I 2025-12-02 01:47:17,680] Trial 33 finished with value: 0.5720823798627002 and parameters: {'max_depth': 9, 'learning_rate': 0.019622995823235567, 'n_estimators': 970, 'subsample': 0.5542099631787927, 'colsample_bytree': 0.7343374947557378, 'min_child_weight': 2, 'gamma': 1.3920206829319746, 'reg_alpha': 0.0001317083794623723, 'reg_lambda': 0.05604694641307872, 'max_delta_step': 3}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  74%|███████▍  | 37/50 [04:15<01:13,  5.66s/it]

[I 2025-12-02 01:47:19,985] Trial 38 pruned.

Best trial: 2. Best value: 0.620137:  76%|███████▌  | 38/50 [04:19<01:01,  5.15s/it]

[I 2025-12-02 01:47:23,947] Trial 39 pruned.

Best trial: 2. Best value: 0.620137:  78%|███████▊  | 39/50 [04:26<01:03,  5.81s/it]

[I 2025-12-02 01:47:31,298] Trial 34 finished with value: 0.620137299771167 and parameters: {'max_depth': 9, 'learning_rate': 0.021461142523036884, 'n_estimators': 1361, 'subsample': 0.74704991021396, 'colsample_bytree': 0.609821985299796, 'min_child_weight': 2, 'gamma': 1.348121885172318, 'reg_alpha': 3.699564667043557e-05, 'reg_lambda': 0.0004241475796295853, 'max_delta_step': 3}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  80%|████████  | 40/50 [04:28<00:44,  4.46s/it]

[I 2025-12-02 01:47:32,591] Trial 36 finished with value: 0.5675057208237986 and parameters: {'max_depth': 8, 'learning_rate': 0.023832825482288447, 'n_estimators': 895, 'subsample': 0.9172682555346551, 'colsample_bytree': 0.6020924002496942, 'min_child_weight': 2, 'gamma': 2.92047502089349, 'reg_alpha': 1.0244634159871533, 'reg_lambda': 8.403578423415246e-08, 'max_delta_step': 7}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  82%|████████▏ | 41/50 [04:36<00:49,  5.54s/it]

[I 2025-12-02 01:47:40,665] Trial 43 pruned.

Best trial: 2. Best value: 0.620137:  84%|████████▍ | 42/50 [04:39<00:38,  4.76s/it]

[I 2025-12-02 01:47:43,601] Trial 42 pruned.

Best trial: 2. Best value: 0.620137:  86%|████████▌ | 43/50 [04:53<00:52,  7.54s/it]

[I 2025-12-02 01:47:57,628] Trial 40 finished with value: 0.5720823798627002 and parameters: {'max_depth': 10, 'learning_rate': 0.0409027978181075, 'n_estimators': 1207, 'subsample': 0.8378507550406493, 'colsample_bytree': 0.6594814469159253, 'min_child_weight': 3, 'gamma': 1.9548779137575003, 'reg_alpha': 3.4222682513473847e-06, 'reg_lambda': 0.002618096476746471, 'max_delta_step': 9}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  88%|████████▊ | 44/50 [04:56<00:38,  6.37s/it]

[I 2025-12-02 01:48:01,264] Trial 41 finished with value: 0.5068649885583524 and parameters: {'max_depth': 10, 'learning_rate': 0.04059846373331878, 'n_estimators': 1196, 'subsample': 0.8286178364572254, 'colsample_bytree': 0.6632371918106679, 'min_child_weight': 3, 'gamma': 4.057297158362389, 'reg_alpha': 3.522950049127561e-06, 'reg_lambda': 3.1914306336320565e-06, 'max_delta_step': 1}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  90%|█████████ | 45/50 [05:22<01:00, 12.16s/it]

[I 2025-12-02 01:48:26,946] Trial 44 finished with value: 0.5675057208237986 and parameters: {'max_depth': 10, 'learning_rate': 0.04260691939405549, 'n_estimators': 1497, 'subsample': 0.7308988021092921, 'colsample_bytree': 0.6623888622707169, 'min_child_weight': 3, 'gamma': 2.068161453964984, 'reg_alpha': 0.019065846187107816, 'reg_lambda': 6.7404043977659275e-06, 'max_delta_step': 1}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  92%|█████████▏| 46/50 [05:23<00:35,  8.80s/it]

[I 2025-12-02 01:48:27,890] Trial 45 finished with value: 0.5720823798627002 and parameters: {'max_depth': 10, 'learning_rate': 0.015047832450968265, 'n_estimators': 1342, 'subsample': 0.8553893899941251, 'colsample_bytree': 0.567796031434878, 'min_child_weight': 3, 'gamma': 2.127629200803553, 'reg_alpha': 1.0171763689853465e-05, 'reg_lambda': 0.018469997141898856, 'max_delta_step': 9}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  94%|█████████▍| 47/50 [05:32<00:26,  8.79s/it]

[I 2025-12-02 01:48:36,659] Trial 46 finished with value: 0.5549199084668193 and parameters: {'max_depth': 10, 'learning_rate': 0.12577632311027906, 'n_estimators': 1348, 'subsample': 0.7837257080920758, 'colsample_bytree': 0.5627962529076772, 'min_child_weight': 3, 'gamma': 3.362140813573723, 'reg_alpha': 8.807583764728489e-06, 'reg_lambda': 7.0433160256881744e-06, 'max_delta_step': 2}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  96%|█████████▌| 48/50 [05:45<00:20, 10.21s/it]

[I 2025-12-02 01:48:50,194] Trial 47 finished with value: 0.528604118993135 and parameters: {'max_depth': 10, 'learning_rate': 0.09865997963331313, 'n_estimators': 1481, 'subsample': 0.768540895657409, 'colsample_bytree': 0.5638741279756192, 'min_child_weight': 1, 'gamma': 2.1509907077797776, 'reg_alpha': 0.0008057353787825845, 'reg_lambda': 0.0004964024891546051, 'max_delta_step': 2}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137:  98%|█████████▊| 49/50 [05:53<00:09,  9.54s/it]

[I 2025-12-02 01:48:58,164] Trial 48 finished with value: 0.47139588100686497 and parameters: {'max_depth': 9, 'learning_rate': 0.13325284410412597, 'n_estimators': 1043, 'subsample': 0.7826508109205317, 'colsample_bytree': 0.5643492743504204, 'min_child_weight': 1, 'gamma': 3.224570083697131, 'reg_alpha': 0.0003129243111508326, 'reg_lambda': 0.018757317000067865, 'max_delta_step': 2}. Best is trial 2 with value: 0.620137299771167.

Best trial: 2. Best value: 0.620137: 100%|██████████| 50/50 [05:54<00:00,  7.09s/it]

[I 2025-12-02 01:48:58,965] Trial 49 finished with value: 0.4977116704805492 and parameters: {'max_depth': 9, 'learning_rate': 0.12218550311380116, 'n_estimators': 1070, 'subsample': 0.7831311424036848, 'colsample_bytree': 0.5757659608884672, 'min_child_weight': 1, 'gamma': 3.2959873133392708, 'reg_alpha': 0.0007161718937391608, 'reg_lambda': 0.0005449296196626425, 'max_delta_step': 2}. Best is trial 2 with value: 0.620137299771167.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 01:49:04,707] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 44, Test size: 12
Using Leave-One-Out CV with 44 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.04:   2%|▏         | 1/50 [00:18<14:56, 18.30s/it]

[I 2025-12-02 01:49:22,995] Trial 3 finished with value: 0.04 and parameters: {'max_depth': 9, 'learning_rate': 0.04189371189672103, 'n_estimators': 565, 'subsample': 0.7882997440481347, 'colsample_bytree': 0.6924504704517407, 'min_child_weight': 6, 'gamma': 2.6481458184275866, 'reg_alpha': 0.000730246102008025, 'reg_lambda': 1.3483784012153177e-06, 'max_delta_step': 9}. Best is trial 3 with value: 0.04.

Best trial: 0. Best value: 0.470526:   4%|▍         | 2/50 [00:21<07:26,  9.30s/it]

[I 2025-12-02 01:49:25,998] Trial 0 finished with value: 0.4705263157894737 and parameters: {'max_depth': 10, 'learning_rate': 0.03459374899490229, 'n_estimators': 621, 'subsample': 0.541633860012035, 'colsample_bytree': 0.6062237540096034, 'min_child_weight': 3, 'gamma': 2.2595026206908786, 'reg_alpha': 0.0005887943478861547, 'reg_lambda': 0.0004347852973553714, 'max_delta_step': 3}. Best is trial 0 with value: 0.4705263157894737.

Best trial: 0. Best value: 0.470526:   6%|▌         | 3/50 [00:38<10:02, 12.83s/it]

[I 2025-12-02 01:49:43,023] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.04311151205818734, 'n_estimators': 590, 'subsample': 0.6766087776963289, 'colsample_bytree': 0.6736643044372213, 'min_child_weight': 6, 'gamma': 4.1635993748042575, 'reg_alpha': 0.00018259960860179345, 'reg_lambda': 0.0003974323831699556, 'max_delta_step': 5}. Best is trial 0 with value: 0.4705263157894737.

Best trial: 0. Best value: 0.470526:   8%|▊         | 4/50 [00:40<06:31,  8.50s/it]

[I 2025-12-02 01:49:44,897] Trial 2 finished with value: 0.18421052631578946 and parameters: {'max_depth': 9, 'learning_rate': 0.246009719492144, 'n_estimators': 1272, 'subsample': 0.883272441727104, 'colsample_bytree': 0.676641582584285, 'min_child_weight': 8, 'gamma': 4.80383144419879, 'reg_alpha': 0.5944809750401119, 'reg_lambda': 0.0021300220695508144, 'max_delta_step': 2}. Best is trial 0 with value: 0.4705263157894737.

Best trial: 0. Best value: 0.470526:  10%|█         | 5/50 [00:41<04:33,  6.08s/it]

[I 2025-12-02 01:49:46,660] Trial 1 finished with value: 0.45052631578947366 and parameters: {'max_depth': 5, 'learning_rate': 0.21288689874082808, 'n_estimators': 1263, 'subsample': 0.5659990449258683, 'colsample_bytree': 0.6046728977837569, 'min_child_weight': 1, 'gamma': 0.24672278978487783, 'reg_alpha': 4.794605728781262e-08, 'reg_lambda': 1.1255537397770677e-08, 'max_delta_step': 1}. Best is trial 0 with value: 0.4705263157894737.

Best trial: 0. Best value: 0.470526:  12%|█▏        | 6/50 [00:52<05:29,  7.48s/it]

[I 2025-12-02 01:49:56,889] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.2839160120758306, 'n_estimators': 947, 'subsample': 0.7198057011825234, 'colsample_bytree': 0.6275841339277115, 'min_child_weight': 10, 'gamma': 0.22382867771594372, 'reg_alpha': 1.4145746574886097e-06, 'reg_lambda': 0.034689418236741834, 'max_delta_step': 4}. Best is trial 0 with value: 0.4705263157894737.

Best trial: 0. Best value: 0.470526:  14%|█▍        | 7/50 [01:00<05:36,  7.83s/it]

[I 2025-12-02 01:50:05,416] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.010027419567722143, 'n_estimators': 218, 'subsample': 0.950997683839667, 'colsample_bytree': 0.6868169467009163, 'min_child_weight': 7, 'gamma': 2.532366151513161, 'reg_alpha': 0.0006400110434403915, 'reg_lambda': 0.00684206581489501, 'max_delta_step': 1}. Best is trial 0 with value: 0.4705263157894737.

Best trial: 6. Best value: 0.5:  16%|█▌        | 8/50 [01:10<05:53,  8.42s/it]

[I 2025-12-02 01:50:15,114] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.15605558573502168, 'n_estimators': 1034, 'subsample': 0.5780004968852397, 'colsample_bytree': 0.53070438620011, 'min_child_weight': 4, 'gamma': 0.31228925400893615, 'reg_alpha': 1.5149282203528687e-07, 'reg_lambda': 0.00013415589732513627, 'max_delta_step': 0}. Best is trial 6 with value: 0.5.

Best trial: 10. Best value: 0.576842:  18%|█▊        | 9/50 [01:13<04:41,  6.87s/it]

[I 2025-12-02 01:50:18,569] Trial 10 finished with value: 0.5768421052631579 and parameters: {'max_depth': 8, 'learning_rate': 0.14821386297018654, 'n_estimators': 243, 'subsample': 0.8463088867127131, 'colsample_bytree': 0.596543852633592, 'min_child_weight': 1, 'gamma': 1.6854619628705803, 'reg_alpha': 5.329216005414261e-07, 'reg_lambda': 0.0025538242102636937, 'max_delta_step': 1}. Best is trial 10 with value: 0.5768421052631579.

Best trial: 10. Best value: 0.576842:  20%|██        | 10/50 [01:14<03:21,  5.04s/it]

[I 2025-12-02 01:50:19,531] Trial 7 finished with value: 0.4242105263157895 and parameters: {'max_depth': 6, 'learning_rate': 0.012076761016834745, 'n_estimators': 746, 'subsample': 0.7338101350766938, 'colsample_bytree': 0.798071229270182, 'min_child_weight': 3, 'gamma': 0.6388061218696256, 'reg_alpha': 4.378936933542327e-07, 'reg_lambda': 0.016796643795501342, 'max_delta_step': 2}. Best is trial 10 with value: 0.5768421052631579.

Best trial: 10. Best value: 0.576842:  22%|██▏       | 11/50 [01:16<02:40,  4.11s/it]

[I 2025-12-02 01:50:21,519] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.19469207888067808, 'n_estimators': 1093, 'subsample': 0.5991114334655026, 'colsample_bytree': 0.7144503430568983, 'min_child_weight': 4, 'gamma': 1.97898936409317, 'reg_alpha': 0.007782699430703488, 'reg_lambda': 0.09194854211705145, 'max_delta_step': 1}. Best is trial 10 with value: 0.5768421052631579.

Best trial: 10. Best value: 0.576842:  24%|██▍       | 12/50 [01:19<02:18,  3.65s/it]

[I 2025-12-02 01:50:24,105] Trial 11 pruned.

Best trial: 10. Best value: 0.576842:  26%|██▌       | 13/50 [01:24<02:27,  4.00s/it]

[I 2025-12-02 01:50:28,909] Trial 12 pruned.

Best trial: 10. Best value: 0.576842:  28%|██▊       | 14/50 [01:30<02:50,  4.74s/it]

[I 2025-12-02 01:50:35,350] Trial 15 finished with value: 0.5168421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.10246403596469596, 'n_estimators': 222, 'subsample': 0.830612603775307, 'colsample_bytree': 0.5038253237629353, 'min_child_weight': 1, 'gamma': 1.1214488842365258, 'reg_alpha': 1.1341893931883524e-08, 'reg_lambda': 1.1559137922851026e-05, 'max_delta_step': 0}. Best is trial 10 with value: 0.5768421052631579.

Best trial: 10. Best value: 0.576842:  30%|███       | 15/50 [01:30<01:58,  3.39s/it]

[I 2025-12-02 01:50:35,626] Trial 14 finished with value: 0.5368421052631579 and parameters: {'max_depth': 7, 'learning_rate': 0.1069960394250383, 'n_estimators': 221, 'subsample': 0.8410336194876633, 'colsample_bytree': 0.5052356229597346, 'min_child_weight': 1, 'gamma': 1.2803884555308218, 'reg_alpha': 1.3634560604437644e-08, 'reg_lambda': 4.707293871202582, 'max_delta_step': 8}. Best is trial 10 with value: 0.5768421052631579.

Best trial: 10. Best value: 0.576842:  32%|███▏      | 16/50 [01:35<02:12,  3.88s/it]

[I 2025-12-02 01:50:40,657] Trial 18 pruned.

Best trial: 10. Best value: 0.576842:  34%|███▍      | 17/50 [01:36<01:39,  3.00s/it]

[I 2025-12-02 01:50:41,600] Trial 16 finished with value: 0.5368421052631579 and parameters: {'max_depth': 8, 'learning_rate': 0.10034380221921257, 'n_estimators': 262, 'subsample': 0.82294294121995, 'colsample_bytree': 0.505617837437705, 'min_child_weight': 1, 'gamma': 1.2360972717082817, 'reg_alpha': 1.4248094831656227e-08, 'reg_lambda': 1.2348741842830867e-05, 'max_delta_step': 0}. Best is trial 10 with value: 0.5768421052631579.

Best trial: 10. Best value: 0.576842:  36%|███▌      | 18/50 [01:40<01:44,  3.27s/it]

[I 2025-12-02 01:50:45,483] Trial 13 finished with value: 0.5368421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.10861162140412584, 'n_estimators': 362, 'subsample': 0.8491206386501433, 'colsample_bytree': 0.9515587819483864, 'min_child_weight': 1, 'gamma': 1.553943319327567, 'reg_alpha': 1.1103034670525318e-05, 'reg_lambda': 3.7849031000434006, 'max_delta_step': 8}. Best is trial 10 with value: 0.5768421052631579.

Best trial: 10. Best value: 0.576842:  38%|███▊      | 19/50 [01:41<01:13,  2.36s/it]

[I 2025-12-02 01:50:45,725] Trial 20 pruned.

Best trial: 10. Best value: 0.576842:  40%|████      | 20/50 [01:44<01:25,  2.84s/it]

[I 2025-12-02 01:50:49,684] Trial 21 pruned.

Best trial: 17. Best value: 0.583158:  42%|████▏     | 21/50 [01:47<01:17,  2.67s/it]

[I 2025-12-02 01:50:51,957] Trial 17 finished with value: 0.5831578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.0995165825102602, 'n_estimators': 284, 'subsample': 0.8676379017124646, 'colsample_bytree': 0.9180261537794555, 'min_child_weight': 1, 'gamma': 1.1654127163123715, 'reg_alpha': 1.2582639476678521e-08, 'reg_lambda': 7.209204741573172e-06, 'max_delta_step': 0}. Best is trial 17 with value: 0.5831578947368421.

Best trial: 17. Best value: 0.583158:  44%|████▍     | 22/50 [01:47<00:57,  2.06s/it]

[I 2025-12-02 01:50:52,611] Trial 23 pruned.

Best trial: 17. Best value: 0.583158:  46%|████▌     | 23/50 [01:49<00:50,  1.86s/it]

[I 2025-12-02 01:50:53,984] Trial 22 pruned.

Best trial: 17. Best value: 0.583158:  48%|████▊     | 24/50 [01:50<00:40,  1.55s/it]

[I 2025-12-02 01:50:54,826] Trial 19 pruned.

Best trial: 17. Best value: 0.583158:  50%|█████     | 25/50 [01:51<00:37,  1.49s/it]

[I 2025-12-02 01:50:56,177] Trial 24 pruned.

Best trial: 17. Best value: 0.583158:  52%|█████▏    | 26/50 [01:53<00:43,  1.80s/it]

[I 2025-12-02 01:50:58,696] Trial 25 pruned.

Best trial: 17. Best value: 0.583158:  54%|█████▍    | 27/50 [01:59<01:03,  2.77s/it]

[I 2025-12-02 01:51:03,732] Trial 28 pruned.
[I 2025-12-02 01:51:03,759] Trial 26 pruned.

Best trial: 17. Best value: 0.583158:  58%|█████▊    | 29/50 [02:00<00:39,  1.87s/it]

[I 2025-12-02 01:51:05,382] Trial 29 pruned.

Best trial: 17. Best value: 0.583158:  60%|██████    | 30/50 [02:01<00:32,  1.60s/it]

[I 2025-12-02 01:51:06,151] Trial 30 pruned.

Best trial: 17. Best value: 0.583158:  62%|██████▏   | 31/50 [02:03<00:33,  1.78s/it]

[I 2025-12-02 01:51:08,449] Trial 32 pruned.

Best trial: 17. Best value: 0.583158:  64%|██████▍   | 32/50 [02:04<00:27,  1.52s/it]

[I 2025-12-02 01:51:09,274] Trial 31 pruned.

Best trial: 17. Best value: 0.583158:  66%|██████▌   | 33/50 [02:07<00:31,  1.87s/it]

[I 2025-12-02 01:51:12,048] Trial 35 pruned.

Best trial: 17. Best value: 0.583158:  68%|██████▊   | 34/50 [02:11<00:40,  2.56s/it]

[I 2025-12-02 01:51:16,319] Trial 33 pruned.

Best trial: 17. Best value: 0.583158:  70%|███████   | 35/50 [02:12<00:32,  2.19s/it]

[I 2025-12-02 01:51:17,623] Trial 34 pruned.

Best trial: 17. Best value: 0.583158:  72%|███████▏  | 36/50 [02:15<00:30,  2.21s/it]

[I 2025-12-02 01:51:19,877] Trial 27 pruned.

Best trial: 17. Best value: 0.583158:  74%|███████▍  | 37/50 [02:19<00:37,  2.87s/it]

[I 2025-12-02 01:51:24,329] Trial 39 pruned.

Best trial: 17. Best value: 0.583158:  76%|███████▌  | 38/50 [02:22<00:36,  3.00s/it]

[I 2025-12-02 01:51:27,635] Trial 38 pruned.

Best trial: 17. Best value: 0.583158:  78%|███████▊  | 39/50 [02:25<00:30,  2.73s/it]

[I 2025-12-02 01:51:29,730] Trial 40 pruned.

Best trial: 17. Best value: 0.583158:  80%|████████  | 40/50 [02:26<00:23,  2.31s/it]

[I 2025-12-02 01:51:31,058] Trial 36 pruned.

Best trial: 17. Best value: 0.583158:  82%|████████▏ | 41/50 [02:29<00:22,  2.55s/it]

[I 2025-12-02 01:51:34,174] Trial 41 pruned.

Best trial: 17. Best value: 0.583158:  84%|████████▍ | 42/50 [02:31<00:19,  2.48s/it]

[I 2025-12-02 01:51:36,477] Trial 43 pruned.

Best trial: 17. Best value: 0.583158:  86%|████████▌ | 43/50 [02:33<00:16,  2.40s/it]

[I 2025-12-02 01:51:38,685] Trial 37 finished with value: 0.4705263157894737 and parameters: {'max_depth': 7, 'learning_rate': 0.1143201753911309, 'n_estimators': 498, 'subsample': 0.872041092228167, 'colsample_bytree': 0.5852998477814063, 'min_child_weight': 1, 'gamma': 0.4906482194963212, 'reg_alpha': 3.303452957444676e-08, 'reg_lambda': 4.601711747883319e-06, 'max_delta_step': 8}. Best is trial 17 with value: 0.5831578947368421.

Best trial: 17. Best value: 0.583158:  88%|████████▊ | 44/50 [02:37<00:16,  2.76s/it]

[I 2025-12-02 01:51:42,293] Trial 46 pruned.

Best trial: 17. Best value: 0.583158:  90%|█████████ | 45/50 [02:38<00:11,  2.33s/it]

[I 2025-12-02 01:51:43,620] Trial 45 pruned.

Best trial: 17. Best value: 0.583158:  92%|█████████▏| 46/50 [02:44<00:13,  3.31s/it]

[I 2025-12-02 01:51:49,209] Trial 44 finished with value: 0.4705263157894737 and parameters: {'max_depth': 8, 'learning_rate': 0.10349983869326536, 'n_estimators': 286, 'subsample': 0.8172736158829673, 'colsample_bytree': 0.5091954193835301, 'min_child_weight': 1, 'gamma': 0.0005655527750521028, 'reg_alpha': 1.4411605111497642e-08, 'reg_lambda': 0.0009470729444015963, 'max_delta_step': 0}. Best is trial 17 with value: 0.5831578947368421.

Best trial: 17. Best value: 0.583158:  94%|█████████▍| 47/50 [02:45<00:07,  2.57s/it]

[I 2025-12-02 01:51:50,045] Trial 48 pruned.

Best trial: 17. Best value: 0.583158:  96%|█████████▌| 48/50 [02:48<00:05,  2.85s/it]

[I 2025-12-02 01:51:53,554] Trial 42 finished with value: 0.49684210526315786 and parameters: {'max_depth': 5, 'learning_rate': 0.2836085952893579, 'n_estimators': 685, 'subsample': 0.7012511429474115, 'colsample_bytree': 0.5913452730005986, 'min_child_weight': 3, 'gamma': 1.895120870058662, 'reg_alpha': 3.8198225361384735e-05, 'reg_lambda': 3.037170912654439e-08, 'max_delta_step': 6}. Best is trial 17 with value: 0.5831578947368421.

Best trial: 17. Best value: 0.583158:  98%|█████████▊| 49/50 [02:50<00:02,  2.42s/it]

[I 2025-12-02 01:51:54,964] Trial 49 pruned.

Best trial: 17. Best value: 0.583158: 100%|██████████| 50/50 [03:03<00:00,  3.67s/it]

[I 2025-12-02 01:52:08,313] Trial 47 finished with value: 0.4705263157894737 and parameters: {'max_depth': 8, 'learning_rate': 0.09563391798605855, 'n_estimators': 899, 'subsample': 0.822171320474043, 'colsample_bytree': 0.5421059949219201, 'min_child_weight': 1, 'gamma': 1.0696895438887766, 'reg_alpha': 1.305994360640871e-07, 'reg_lambda': 0.000763095246121814, 'max_delta_step': 0}. Best is trial 17 with value: 0.5831578947368421.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 01:52:13,519] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 45, Test size: 12
Using Leave-One-Out CV with 45 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0:   2%|▏         | 1/50 [00:23<19:15, 23.59s/it]

[I 2025-12-02 01:52:37,094] Trial 0 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.07524376015374447, 'n_estimators': 735, 'subsample': 0.6695453878421738, 'colsample_bytree': 0.6989835664976922, 'min_child_weight': 7, 'gamma': 0.6554798832354403, 'reg_alpha': 3.2707906473539883e-05, 'reg_lambda': 2.734225441525977, 'max_delta_step': 0}. Best is trial 0 with value: 0.0.

Best trial: 0. Best value: 0:   4%|▍         | 2/50 [00:34<12:41, 15.87s/it]

[I 2025-12-02 01:52:47,563] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.034965878064535466, 'n_estimators': 1119, 'subsample': 0.6861081937963862, 'colsample_bytree': 0.566877817773767, 'min_child_weight': 7, 'gamma': 1.2419366146624145, 'reg_alpha': 5.2956541014356564e-05, 'reg_lambda': 0.7245759688681553, 'max_delta_step': 3}. Best is trial 0 with value: 0.0.

Best trial: 3. Best value: 0.563765:   6%|▌         | 3/50 [00:44<10:24, 13.29s/it]

[I 2025-12-02 01:52:57,784] Trial 3 finished with value: 0.5637651821862348 and parameters: {'max_depth': 8, 'learning_rate': 0.013542587717087898, 'n_estimators': 1280, 'subsample': 0.7814878445311624, 'colsample_bytree': 0.929578054905708, 'min_child_weight': 4, 'gamma': 0.7465201912922037, 'reg_alpha': 4.9069795461404015e-06, 'reg_lambda': 0.20324158168619286, 'max_delta_step': 5}. Best is trial 3 with value: 0.5637651821862348.

Best trial: 3. Best value: 0.563765:   8%|▊         | 4/50 [00:45<06:37,  8.65s/it]

[I 2025-12-02 01:52:59,319] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.18361524691887784, 'n_estimators': 1463, 'subsample': 0.9577618459669965, 'colsample_bytree': 0.7979672776907774, 'min_child_weight': 9, 'gamma': 4.487166024152263, 'reg_alpha': 6.999960083479841e-08, 'reg_lambda': 4.945711476614956e-05, 'max_delta_step': 3}. Best is trial 3 with value: 0.5637651821862348.

Best trial: 4. Best value: 0.609312:  10%|█         | 5/50 [00:50<05:23,  7.19s/it]

[I 2025-12-02 01:53:03,918] Trial 4 finished with value: 0.6093117408906883 and parameters: {'max_depth': 10, 'learning_rate': 0.06395141271197324, 'n_estimators': 812, 'subsample': 0.931672280981749, 'colsample_bytree': 0.7178772591915805, 'min_child_weight': 4, 'gamma': 0.4063538575801018, 'reg_alpha': 0.004772766363783533, 'reg_lambda': 0.0022537911028643045, 'max_delta_step': 0}. Best is trial 4 with value: 0.6093117408906883.

Best trial: 4. Best value: 0.609312:  12%|█▏        | 6/50 [01:05<07:13,  9.86s/it]

[I 2025-12-02 01:53:18,968] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.019676880133156424, 'n_estimators': 952, 'subsample': 0.9511764153369164, 'colsample_bytree': 0.8812785369468092, 'min_child_weight': 5, 'gamma': 0.12385668260840643, 'reg_alpha': 2.5323002314630947, 'reg_lambda': 9.525123246337507e-05, 'max_delta_step': 10}. Best is trial 4 with value: 0.6093117408906883.

Best trial: 4. Best value: 0.609312:  14%|█▍        | 7/50 [01:07<05:15,  7.34s/it]

[I 2025-12-02 01:53:21,122] Trial 7 finished with value: 0.28846153846153844 and parameters: {'max_depth': 5, 'learning_rate': 0.18817387327100585, 'n_estimators': 637, 'subsample': 0.8687013429907939, 'colsample_bytree': 0.9558045667335632, 'min_child_weight': 8, 'gamma': 3.5908580501809677, 'reg_alpha': 0.0010063519224067616, 'reg_lambda': 1.2128333464733332e-08, 'max_delta_step': 4}. Best is trial 4 with value: 0.6093117408906883.

Best trial: 4. Best value: 0.609312:  16%|█▌        | 8/50 [01:16<05:23,  7.71s/it]

[I 2025-12-02 01:53:29,608] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.012685873093722076, 'n_estimators': 265, 'subsample': 0.5503598594049957, 'colsample_bytree': 0.9089238314944262, 'min_child_weight': 7, 'gamma': 1.4061754485001825, 'reg_alpha': 0.0010529068845349903, 'reg_lambda': 0.5737880276351901, 'max_delta_step': 0}. Best is trial 4 with value: 0.6093117408906883.

Best trial: 4. Best value: 0.609312:  18%|█▊        | 9/50 [01:17<03:59,  5.84s/it]

[I 2025-12-02 01:53:31,333] Trial 6 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.017655426230168376, 'n_estimators': 1081, 'subsample': 0.85862791464555, 'colsample_bytree': 0.5485231355418967, 'min_child_weight': 9, 'gamma': 2.8322143371247934, 'reg_alpha': 2.2027540118394387e-05, 'reg_lambda': 7.942606022053327e-05, 'max_delta_step': 2}. Best is trial 4 with value: 0.6093117408906883.

Best trial: 4. Best value: 0.609312:  20%|██        | 10/50 [01:35<06:17,  9.43s/it]

[I 2025-12-02 01:53:48,804] Trial 8 finished with value: 0.5759109311740891 and parameters: {'max_depth': 4, 'learning_rate': 0.024471575620184025, 'n_estimators': 1256, 'subsample': 0.6796152556760249, 'colsample_bytree': 0.6987974155403306, 'min_child_weight': 2, 'gamma': 3.002481029447556, 'reg_alpha': 0.0014454208814282212, 'reg_lambda': 1.8834979193709394e-08, 'max_delta_step': 4}. Best is trial 4 with value: 0.6093117408906883.

Best trial: 4. Best value: 0.609312:  22%|██▏       | 11/50 [01:49<07:06, 10.93s/it]

[I 2025-12-02 01:54:03,149] Trial 10 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.23152281125807456, 'n_estimators': 1402, 'subsample': 0.8227891300256926, 'colsample_bytree': 0.7336374081161299, 'min_child_weight': 7, 'gamma': 2.5708690981168525, 'reg_alpha': 5.216045390481229e-07, 'reg_lambda': 0.005268168492697366, 'max_delta_step': 10}. Best is trial 4 with value: 0.6093117408906883.

Best trial: 4. Best value: 0.609312:  24%|██▍       | 12/50 [01:54<05:40,  8.97s/it]

[I 2025-12-02 01:54:07,619] Trial 11 finished with value: 0.5880566801619433 and parameters: {'max_depth': 10, 'learning_rate': 0.03725098940879199, 'n_estimators': 1016, 'subsample': 0.69021236125163, 'colsample_bytree': 0.8952127910716846, 'min_child_weight': 2, 'gamma': 2.9770786114349495, 'reg_alpha': 3.7678347797743554e-08, 'reg_lambda': 2.1306580461153755e-06, 'max_delta_step': 5}. Best is trial 4 with value: 0.6093117408906883.

Best trial: 4. Best value: 0.609312:  26%|██▌       | 13/50 [02:02<05:28,  8.88s/it]

[I 2025-12-02 01:54:16,315] Trial 13 finished with value: 0.4271255060728745 and parameters: {'max_depth': 10, 'learning_rate': 0.06462192896102636, 'n_estimators': 540, 'subsample': 0.9850545079009599, 'colsample_bytree': 0.6292457301483542, 'min_child_weight': 1, 'gamma': 1.9446378909843278, 'reg_alpha': 0.15650326229597605, 'reg_lambda': 0.007215815433745773, 'max_delta_step': 8}. Best is trial 4 with value: 0.6093117408906883.

Best trial: 14. Best value: 0.633603:  28%|██▊       | 14/50 [02:11<05:20,  8.91s/it]

[I 2025-12-02 01:54:25,270] Trial 14 finished with value: 0.6336032388663968 and parameters: {'max_depth': 10, 'learning_rate': 0.06215913615371202, 'n_estimators': 498, 'subsample': 0.5846377262122376, 'colsample_bytree': 0.660990970152491, 'min_child_weight': 1, 'gamma': 1.9104862374056726, 'reg_alpha': 0.0743899712890787, 'reg_lambda': 1.2925107644219025e-07, 'max_delta_step': 8}. Best is trial 14 with value: 0.6336032388663968.

Best trial: 14. Best value: 0.633603:  30%|███       | 15/50 [02:15<04:12,  7.20s/it]

[I 2025-12-02 01:54:28,526] Trial 17 pruned.

Best trial: 14. Best value: 0.633603:  32%|███▏      | 16/50 [02:18<03:22,  5.97s/it]

[I 2025-12-02 01:54:31,632] Trial 12 finished with value: 0.5111336032388664 and parameters: {'max_depth': 10, 'learning_rate': 0.018252516917021816, 'n_estimators': 1252, 'subsample': 0.7518491552827209, 'colsample_bytree': 0.6816751581805622, 'min_child_weight': 1, 'gamma': 1.7175375236869528, 'reg_alpha': 2.1593754948728536e-08, 'reg_lambda': 0.06975620435595918, 'max_delta_step': 0}. Best is trial 14 with value: 0.6336032388663968.

Best trial: 14. Best value: 0.633603:  34%|███▍      | 17/50 [02:21<02:55,  5.31s/it]

[I 2025-12-02 01:54:35,408] Trial 15 finished with value: 0.5759109311740891 and parameters: {'max_depth': 10, 'learning_rate': 0.07528918203613152, 'n_estimators': 568, 'subsample': 0.5647189842589453, 'colsample_bytree': 0.8191516839619128, 'min_child_weight': 1, 'gamma': 1.8513375886821042, 'reg_alpha': 0.6126619288451635, 'reg_lambda': 1.1590234924234861e-06, 'max_delta_step': 7}. Best is trial 14 with value: 0.6336032388663968.

Best trial: 14. Best value: 0.633603:  36%|███▌      | 18/50 [02:33<03:52,  7.25s/it]

[I 2025-12-02 01:54:47,174] Trial 16 finished with value: 0.5637651821862348 and parameters: {'max_depth': 10, 'learning_rate': 0.09651255744547242, 'n_estimators': 871, 'subsample': 0.5697885252498304, 'colsample_bytree': 0.7971677114911285, 'min_child_weight': 3, 'gamma': 3.9740150894304898, 'reg_alpha': 0.04558669273813763, 'reg_lambda': 1.4071139534823939e-06, 'max_delta_step': 7}. Best is trial 14 with value: 0.6336032388663968.

Best trial: 14. Best value: 0.633603:  38%|███▊      | 19/50 [02:37<03:12,  6.20s/it]

[I 2025-12-02 01:54:50,931] Trial 21 pruned.

Best trial: 14. Best value: 0.633603:  40%|████      | 20/50 [02:45<03:19,  6.64s/it]

[I 2025-12-02 01:54:58,585] Trial 22 pruned.

Best trial: 14. Best value: 0.633603:  42%|████▏     | 21/50 [02:46<02:24,  4.99s/it]

[I 2025-12-02 01:54:59,747] Trial 18 finished with value: 0.5495951417004048 and parameters: {'max_depth': 9, 'learning_rate': 0.10611814876322109, 'n_estimators': 809, 'subsample': 0.5912271858581856, 'colsample_bytree': 0.6417233301322423, 'min_child_weight': 3, 'gamma': 0.23460631530545556, 'reg_alpha': 0.04901702779230636, 'reg_lambda': 0.00915227631945807, 'max_delta_step': 7}. Best is trial 14 with value: 0.6336032388663968.

Best trial: 14. Best value: 0.633603:  44%|████▍     | 22/50 [02:48<01:52,  4.03s/it]

[I 2025-12-02 01:55:01,514] Trial 19 finished with value: 0.5688259109311741 and parameters: {'max_depth': 9, 'learning_rate': 0.09771750935831207, 'n_estimators': 746, 'subsample': 0.5897802600319416, 'colsample_bytree': 0.6338520947750579, 'min_child_weight': 3, 'gamma': 0.37700944609791986, 'reg_alpha': 0.023753535004633442, 'reg_lambda': 2.7281841648128303e-06, 'max_delta_step': 7}. Best is trial 14 with value: 0.6336032388663968.

Best trial: 14. Best value: 0.633603:  46%|████▌     | 23/50 [02:54<02:08,  4.76s/it]

[I 2025-12-02 01:55:07,982] Trial 20 finished with value: 0.6163967611336032 and parameters: {'max_depth': 9, 'learning_rate': 0.10283787391708876, 'n_estimators': 814, 'subsample': 0.6112783395492946, 'colsample_bytree': 0.6221727007758987, 'min_child_weight': 3, 'gamma': 0.36440371901850577, 'reg_alpha': 0.021100131090034162, 'reg_lambda': 0.0023056480803024942, 'max_delta_step': 8}. Best is trial 14 with value: 0.6336032388663968.

Best trial: 14. Best value: 0.633603:  48%|████▊     | 24/50 [03:13<03:55,  9.07s/it]

[I 2025-12-02 01:55:27,100] Trial 23 finished with value: 0.5495951417004048 and parameters: {'max_depth': 9, 'learning_rate': 0.05189074927807994, 'n_estimators': 678, 'subsample': 0.5042131223878019, 'colsample_bytree': 0.6206054637071687, 'min_child_weight': 3, 'gamma': 0.08122543259225679, 'reg_alpha': 0.013151070467965863, 'reg_lambda': 0.0009238881177560266, 'max_delta_step': 6}. Best is trial 14 with value: 0.6336032388663968.

Best trial: 14. Best value: 0.633603:  50%|█████     | 25/50 [03:23<03:51,  9.27s/it]

[I 2025-12-02 01:55:36,849] Trial 26 finished with value: 0.6214574898785425 and parameters: {'max_depth': 8, 'learning_rate': 0.05092968306438607, 'n_estimators': 658, 'subsample': 0.6228682615404004, 'colsample_bytree': 0.5736441787723572, 'min_child_weight': 2, 'gamma': 0.007540180003637431, 'reg_alpha': 0.004159097711340298, 'reg_lambda': 0.0003790315985907415, 'max_delta_step': 9}. Best is trial 14 with value: 0.6336032388663968.

Best trial: 14. Best value: 0.633603:  52%|█████▏    | 26/50 [03:31<03:36,  9.02s/it]

[I 2025-12-02 01:55:45,271] Trial 24 finished with value: 0.5566801619433198 and parameters: {'max_depth': 9, 'learning_rate': 0.0446428829616657, 'n_estimators': 993, 'subsample': 0.6495388014033143, 'colsample_bytree': 0.9995772849378859, 'min_child_weight': 2, 'gamma': 3.099562870866037, 'reg_alpha': 0.011168416314935299, 'reg_lambda': 1.2948403267095553e-05, 'max_delta_step': 5}. Best is trial 14 with value: 0.6336032388663968.

Best trial: 14. Best value: 0.633603:  54%|█████▍    | 27/50 [03:33<02:36,  6.80s/it]

[I 2025-12-02 01:55:46,886] Trial 25 finished with value: 0.5566801619433198 and parameters: {'max_depth': 8, 'learning_rate': 0.042907715908124186, 'n_estimators': 998, 'subsample': 0.6392061800879147, 'colsample_bytree': 0.989912908800181, 'min_child_weight': 2, 'gamma': 3.1888913630945543, 'reg_alpha': 0.0071900536291097635, 'reg_lambda': 1.6926293801280678e-05, 'max_delta_step': 5}. Best is trial 14 with value: 0.6336032388663968.

Best trial: 14. Best value: 0.633603:  56%|█████▌    | 28/50 [03:35<01:59,  5.45s/it]

[I 2025-12-02 01:55:49,190] Trial 27 finished with value: 0.5759109311740891 and parameters: {'max_depth': 8, 'learning_rate': 0.053584327626580844, 'n_estimators': 457, 'subsample': 0.629284140447712, 'colsample_bytree': 0.7457663933885867, 'min_child_weight': 2, 'gamma': 1.051373218429506, 'reg_alpha': 0.45641427896236625, 'reg_lambda': 0.0007665391296122759, 'max_delta_step': 9}. Best is trial 14 with value: 0.6336032388663968.

Best trial: 14. Best value: 0.633603:  58%|█████▊    | 29/50 [03:37<01:28,  4.22s/it]

[I 2025-12-02 01:55:50,562] Trial 29 pruned.

Best trial: 14. Best value: 0.633603:  60%|██████    | 30/50 [03:38<01:08,  3.45s/it]

[I 2025-12-02 01:55:52,187] Trial 30 pruned.

Best trial: 14. Best value: 0.633603:  62%|██████▏   | 31/50 [03:39<00:52,  2.74s/it]

[I 2025-12-02 01:55:53,298] Trial 31 pruned.

Best trial: 14. Best value: 0.633603:  64%|██████▍   | 32/50 [03:40<00:38,  2.14s/it]

[I 2025-12-02 01:55:54,025] Trial 33 pruned.

Best trial: 14. Best value: 0.633603:  66%|██████▌   | 33/50 [03:44<00:46,  2.76s/it]

[I 2025-12-02 01:55:58,240] Trial 28 finished with value: 0.5951417004048583 and parameters: {'max_depth': 8, 'learning_rate': 0.04797923611471372, 'n_estimators': 453, 'subsample': 0.6300412124557068, 'colsample_bytree': 0.5773642849611975, 'min_child_weight': 2, 'gamma': 1.121324580150921, 'reg_alpha': 0.00020537443310157108, 'reg_lambda': 0.00036836400277747783, 'max_delta_step': 9}. Best is trial 14 with value: 0.6336032388663968.

Best trial: 14. Best value: 0.633603:  68%|██████▊   | 34/50 [03:46<00:40,  2.51s/it]

[I 2025-12-02 01:56:00,157] Trial 34 pruned.

Best trial: 14. Best value: 0.633603:  70%|███████   | 35/50 [03:47<00:32,  2.14s/it]

[I 2025-12-02 01:56:01,425] Trial 35 pruned.

Best trial: 14. Best value: 0.633603:  72%|███████▏  | 36/50 [03:51<00:37,  2.66s/it]

[I 2025-12-02 01:56:05,299] Trial 36 pruned.

Best trial: 14. Best value: 0.633603:  74%|███████▍  | 37/50 [03:54<00:34,  2.67s/it]

[I 2025-12-02 01:56:07,990] Trial 37 pruned.

Best trial: 14. Best value: 0.633603:  76%|███████▌  | 38/50 [03:55<00:25,  2.13s/it]

[I 2025-12-02 01:56:08,862] Trial 38 pruned.

Best trial: 14. Best value: 0.633603:  78%|███████▊  | 39/50 [03:59<00:29,  2.67s/it]

[I 2025-12-02 01:56:12,787] Trial 39 pruned.

Best trial: 14. Best value: 0.633603:  80%|████████  | 40/50 [04:00<00:23,  2.30s/it]

[I 2025-12-02 01:56:14,246] Trial 40 pruned.

Best trial: 14. Best value: 0.633603:  82%|████████▏ | 41/50 [04:00<00:15,  1.68s/it]

[I 2025-12-02 01:56:14,469] Trial 41 pruned.

Best trial: 14. Best value: 0.633603:  84%|████████▍ | 42/50 [04:04<00:19,  2.38s/it]

[I 2025-12-02 01:56:18,497] Trial 42 pruned.

Best trial: 14. Best value: 0.633603:  86%|████████▌ | 43/50 [04:05<00:13,  1.86s/it]

[I 2025-12-02 01:56:19,122] Trial 32 finished with value: 0.5566801619433198 and parameters: {'max_depth': 7, 'learning_rate': 0.07788645773366099, 'n_estimators': 612, 'subsample': 0.727442171595951, 'colsample_bytree': 0.5379300900705225, 'min_child_weight': 1, 'gamma': 0.6722042644276947, 'reg_alpha': 0.00011929908529725629, 'reg_lambda': 0.056182273330533154, 'max_delta_step': 9}. Best is trial 14 with value: 0.6336032388663968.

Best trial: 14. Best value: 0.633603:  88%|████████▊ | 44/50 [04:08<00:13,  2.20s/it]

[I 2025-12-02 01:56:22,101] Trial 46 pruned.

Best trial: 14. Best value: 0.633603:  90%|█████████ | 45/50 [04:14<00:16,  3.38s/it]

[I 2025-12-02 01:56:28,256] Trial 43 finished with value: 0.5374493927125505 and parameters: {'max_depth': 8, 'learning_rate': 0.05938253781635812, 'n_estimators': 355, 'subsample': 0.7073818429735008, 'colsample_bytree': 0.5995952164651053, 'min_child_weight': 3, 'gamma': 1.3516926861902014, 'reg_alpha': 4.1703932432302355e-06, 'reg_lambda': 5.686045047598337e-05, 'max_delta_step': 6}. Best is trial 14 with value: 0.6336032388663968.

Best trial: 45. Best value: 0.640688:  92%|█████████▏| 46/50 [04:19<00:15,  3.87s/it]

[I 2025-12-02 01:56:33,273] Trial 45 finished with value: 0.6406882591093117 and parameters: {'max_depth': 8, 'learning_rate': 0.05055248519267739, 'n_estimators': 348, 'subsample': 0.5377407541543845, 'colsample_bytree': 0.5902017648708224, 'min_child_weight': 2, 'gamma': 1.1803782892426669, 'reg_alpha': 9.605652611067258e-06, 'reg_lambda': 0.00017629489844771972, 'max_delta_step': 6}. Best is trial 45 with value: 0.6406882591093117.

Best trial: 45. Best value: 0.640688:  94%|█████████▍| 47/50 [04:23<00:11,  3.88s/it]

[I 2025-12-02 01:56:37,163] Trial 44 finished with value: 0.6143724696356275 and parameters: {'max_depth': 8, 'learning_rate': 0.05076817397237188, 'n_estimators': 573, 'subsample': 0.7072585359826128, 'colsample_bytree': 0.6033389530931625, 'min_child_weight': 2, 'gamma': 1.2366994767440622, 'reg_alpha': 6.2533305500273735e-06, 'reg_lambda': 0.00017947532860594398, 'max_delta_step': 6}. Best is trial 45 with value: 0.6406882591093117.

Best trial: 45. Best value: 0.640688:  96%|█████████▌| 48/50 [04:25<00:06,  3.25s/it]

[I 2025-12-02 01:56:38,950] Trial 47 finished with value: 0.5951417004048583 and parameters: {'max_depth': 8, 'learning_rate': 0.033161334237450595, 'n_estimators': 374, 'subsample': 0.570603373749328, 'colsample_bytree': 0.5926002475707859, 'min_child_weight': 2, 'gamma': 1.548380062988617, 'reg_alpha': 0.0005833692867462228, 'reg_lambda': 0.00012502454628575494, 'max_delta_step': 4}. Best is trial 45 with value: 0.6406882591093117.

Best trial: 45. Best value: 0.640688:  98%|█████████▊| 49/50 [04:33<00:04,  4.64s/it]

[I 2025-12-02 01:56:46,838] Trial 48 finished with value: 0.6022267206477733 and parameters: {'max_depth': 10, 'learning_rate': 0.03640348161148473, 'n_estimators': 546, 'subsample': 0.5619031883573417, 'colsample_bytree': 0.5979179861084679, 'min_child_weight': 2, 'gamma': 0.4319339552232182, 'reg_alpha': 0.004334973642048035, 'reg_lambda': 0.00018676567434043075, 'max_delta_step': 3}. Best is trial 45 with value: 0.6406882591093117.

Best trial: 45. Best value: 0.640688: 100%|██████████| 50/50 [04:47<00:00,  5.74s/it]

[I 2025-12-02 01:57:00,568] Trial 49 finished with value: 0.6072874493927125 and parameters: {'max_depth': 10, 'learning_rate': 0.032582965687522204, 'n_estimators': 1078, 'subsample': 0.5626218231072755, 'colsample_bytree': 0.6514358015914858, 'min_child_weight': 2, 'gamma': 1.5272313184228306, 'reg_alpha': 0.0005334673765301852, 'reg_lambda': 1.2204972751260335, 'max_delta_step': 4}. Best is trial 45 with value: 0.6406882591093117.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 01:57:05,778] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 43, Test size: 11
Using Leave-One-Out CV with 43 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.125:   2%|▏         | 1/50 [00:24<20:24, 25.00s/it]

[I 2025-12-02 01:57:30,771] Trial 1 finished with value: 0.125 and parameters: {'max_depth': 8, 'learning_rate': 0.015460666074225122, 'n_estimators': 876, 'subsample': 0.744098876682933, 'colsample_bytree': 0.8007563849114658, 'min_child_weight': 5, 'gamma': 2.708553080967629, 'reg_alpha': 2.082229621234279e-08, 'reg_lambda': 0.37587012900670874, 'max_delta_step': 8}. Best is trial 1 with value: 0.125.

Best trial: 1. Best value: 0.125:   4%|▍         | 2/50 [00:34<12:39, 15.82s/it]

[I 2025-12-02 01:57:40,157] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.021451871394066298, 'n_estimators': 1225, 'subsample': 0.5410789951171446, 'colsample_bytree': 0.753408446231023, 'min_child_weight': 10, 'gamma': 4.020137225926643, 'reg_alpha': 3.631358058155297e-07, 'reg_lambda': 1.8468499514116465, 'max_delta_step': 5}. Best is trial 1 with value: 0.125.

Best trial: 1. Best value: 0.125:   6%|▌         | 3/50 [00:35<07:16,  9.28s/it]

[I 2025-12-02 01:57:41,665] Trial 0 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.011255328871725536, 'n_estimators': 1242, 'subsample': 0.8292931402285582, 'colsample_bytree': 0.8742013252141, 'min_child_weight': 8, 'gamma': 2.422346973335374, 'reg_alpha': 1.9724769418732586, 'reg_lambda': 0.04268729763174157, 'max_delta_step': 9}. Best is trial 1 with value: 0.125.

Best trial: 3. Best value: 0.156798:   8%|▊         | 4/50 [00:53<09:47, 12.76s/it]

[I 2025-12-02 01:57:59,759] Trial 3 finished with value: 0.1567982456140351 and parameters: {'max_depth': 7, 'learning_rate': 0.01634790419723072, 'n_estimators': 1312, 'subsample': 0.9503675101061309, 'colsample_bytree': 0.6430423113956578, 'min_child_weight': 2, 'gamma': 3.6092528816637874, 'reg_alpha': 4.295539144851814e-06, 'reg_lambda': 5.014053971299538, 'max_delta_step': 7}. Best is trial 3 with value: 0.1567982456140351.

Best trial: 3. Best value: 0.156798:  10%|█         | 5/50 [00:54<06:15,  8.34s/it]

[I 2025-12-02 01:58:00,267] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.013544382221402976, 'n_estimators': 1061, 'subsample': 0.8049216094711678, 'colsample_bytree': 0.5728127449598981, 'min_child_weight': 7, 'gamma': 2.9882245916308845, 'reg_alpha': 8.339151483814856, 'reg_lambda': 0.007539400188723813, 'max_delta_step': 8}. Best is trial 3 with value: 0.1567982456140351.

Best trial: 3. Best value: 0.156798:  12%|█▏        | 6/50 [00:55<04:23,  5.98s/it]

[I 2025-12-02 01:58:01,664] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.02673749330917966, 'n_estimators': 729, 'subsample': 0.7311707119547841, 'colsample_bytree': 0.7969645687388545, 'min_child_weight': 8, 'gamma': 0.13853364091411968, 'reg_alpha': 0.652441075242639, 'reg_lambda': 0.0016486609301673445, 'max_delta_step': 8}. Best is trial 3 with value: 0.1567982456140351.

Best trial: 3. Best value: 0.156798:  14%|█▍        | 7/50 [01:01<04:18,  6.00s/it]

[I 2025-12-02 01:58:07,716] Trial 6 finished with value: 0.020833333333333332 and parameters: {'max_depth': 7, 'learning_rate': 0.0320373463699307, 'n_estimators': 893, 'subsample': 0.8311143378357777, 'colsample_bytree': 0.796493249471925, 'min_child_weight': 6, 'gamma': 3.171581427037279, 'reg_alpha': 0.001715863847967354, 'reg_lambda': 0.0015331378544970419, 'max_delta_step': 1}. Best is trial 3 with value: 0.1567982456140351.

Best trial: 3. Best value: 0.156798:  16%|█▌        | 8/50 [01:17<06:16,  8.96s/it]

[I 2025-12-02 01:58:23,020] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.1408011352552335, 'n_estimators': 752, 'subsample': 0.7136804084423057, 'colsample_bytree': 0.861901307397275, 'min_child_weight': 8, 'gamma': 0.08959922984571489, 'reg_alpha': 6.997484244179921, 'reg_lambda': 0.20715902541540593, 'max_delta_step': 6}. Best is trial 3 with value: 0.1567982456140351.

Best trial: 10. Best value: 0.517544:  18%|█▊        | 9/50 [01:20<04:51,  7.12s/it]

[I 2025-12-02 01:58:26,070] Trial 10 finished with value: 0.5175438596491228 and parameters: {'max_depth': 3, 'learning_rate': 0.16446180750571054, 'n_estimators': 564, 'subsample': 0.5574728469720798, 'colsample_bytree': 0.5211184714578515, 'min_child_weight': 1, 'gamma': 0.729308421066367, 'reg_alpha': 0.14940365327697522, 'reg_lambda': 4.253880574216644e-08, 'max_delta_step': 3}. Best is trial 10 with value: 0.5175438596491228.

Best trial: 10. Best value: 0.517544:  20%|██        | 10/50 [01:28<04:56,  7.41s/it]

[I 2025-12-02 01:58:34,131] Trial 9 finished with value: 0.32456140350877194 and parameters: {'max_depth': 4, 'learning_rate': 0.049915547724061024, 'n_estimators': 777, 'subsample': 0.953590500557981, 'colsample_bytree': 0.82653821991583, 'min_child_weight': 3, 'gamma': 1.1322836411070103, 'reg_alpha': 3.43297372740048e-06, 'reg_lambda': 5.798290736793043, 'max_delta_step': 6}. Best is trial 10 with value: 0.5175438596491228.

Best trial: 10. Best value: 0.517544:  22%|██▏       | 11/50 [01:28<03:27,  5.33s/it]

[I 2025-12-02 01:58:34,760] Trial 12 pruned.

Best trial: 10. Best value: 0.517544:  24%|██▍       | 12/50 [01:30<02:33,  4.05s/it]

[I 2025-12-02 01:58:35,877] Trial 7 pruned.

Best trial: 10. Best value: 0.517544:  26%|██▌       | 13/50 [01:34<02:37,  4.27s/it]

[I 2025-12-02 01:58:40,644] Trial 11 pruned.

Best trial: 10. Best value: 0.517544:  28%|██▊       | 14/50 [01:40<02:48,  4.67s/it]

[I 2025-12-02 01:58:46,236] Trial 13 finished with value: 0.4024122807017544 and parameters: {'max_depth': 3, 'learning_rate': 0.27575260200484086, 'n_estimators': 296, 'subsample': 0.5087403393028621, 'colsample_bytree': 0.9987167320407944, 'min_child_weight': 1, 'gamma': 1.6681978074888404, 'reg_alpha': 0.011505434510597986, 'reg_lambda': 1.0113038791122005e-08, 'max_delta_step': 2}. Best is trial 10 with value: 0.5175438596491228.

Best trial: 10. Best value: 0.517544:  30%|███       | 15/50 [01:46<03:02,  5.22s/it]

[I 2025-12-02 01:58:52,745] Trial 14 finished with value: 0.40789473684210525 and parameters: {'max_depth': 3, 'learning_rate': 0.08169164898938934, 'n_estimators': 478, 'subsample': 0.506389408193231, 'colsample_bytree': 0.645198229760965, 'min_child_weight': 1, 'gamma': 1.441356825527796, 'reg_alpha': 7.508175111497575e-05, 'reg_lambda': 4.3655399018188286e-08, 'max_delta_step': 3}. Best is trial 10 with value: 0.5175438596491228.

Best trial: 10. Best value: 0.517544:  32%|███▏      | 16/50 [01:47<02:14,  3.95s/it]

[I 2025-12-02 01:58:53,754] Trial 15 finished with value: 0.44956140350877194 and parameters: {'max_depth': 3, 'learning_rate': 0.07326045404208853, 'n_estimators': 439, 'subsample': 0.51360432269312, 'colsample_bytree': 0.6753589738853664, 'min_child_weight': 1, 'gamma': 1.3874813919590947, 'reg_alpha': 3.312302633274577e-05, 'reg_lambda': 1.0067002078673052e-07, 'max_delta_step': 2}. Best is trial 10 with value: 0.5175438596491228.

Best trial: 10. Best value: 0.517544:  34%|███▍      | 17/50 [01:50<01:59,  3.62s/it]

[I 2025-12-02 01:58:56,604] Trial 17 finished with value: 0.41776315789473684 and parameters: {'max_depth': 3, 'learning_rate': 0.1362862540213868, 'n_estimators': 248, 'subsample': 0.5941641158256497, 'colsample_bytree': 0.5189647270256138, 'min_child_weight': 1, 'gamma': 1.6131841908196152, 'reg_alpha': 0.0001735005423368159, 'reg_lambda': 1.1365446743601805e-08, 'max_delta_step': 3}. Best is trial 10 with value: 0.5175438596491228.

Best trial: 10. Best value: 0.517544:  36%|███▌      | 18/50 [01:54<01:59,  3.74s/it]

[I 2025-12-02 01:59:00,623] Trial 16 finished with value: 0.44956140350877194 and parameters: {'max_depth': 3, 'learning_rate': 0.0752088599427958, 'n_estimators': 500, 'subsample': 0.6037502542434338, 'colsample_bytree': 0.5516900192918734, 'min_child_weight': 1, 'gamma': 1.3461973850338538, 'reg_alpha': 2.814720141838987e-05, 'reg_lambda': 6.68568247278762e-08, 'max_delta_step': 3}. Best is trial 10 with value: 0.5175438596491228.

Best trial: 10. Best value: 0.517544:  38%|███▊      | 19/50 [02:05<02:57,  5.71s/it]

[I 2025-12-02 01:59:10,924] Trial 18 finished with value: 0.40789473684210525 and parameters: {'max_depth': 5, 'learning_rate': 0.10884441778401763, 'n_estimators': 510, 'subsample': 0.6290332790796613, 'colsample_bytree': 0.5012108016648218, 'min_child_weight': 3, 'gamma': 1.1108338237596396, 'reg_alpha': 0.0001230791599428775, 'reg_lambda': 1.600628768597267e-08, 'max_delta_step': 3}. Best is trial 10 with value: 0.5175438596491228.

Best trial: 10. Best value: 0.517544:  40%|████      | 20/50 [02:06<02:14,  4.49s/it]

[I 2025-12-02 01:59:12,578] Trial 19 finished with value: 0.4133771929824561 and parameters: {'max_depth': 5, 'learning_rate': 0.10842476141230804, 'n_estimators': 537, 'subsample': 0.6064345872576873, 'colsample_bytree': 0.5143300521639881, 'min_child_weight': 3, 'gamma': 0.921386704589167, 'reg_alpha': 0.00029832896413249833, 'reg_lambda': 1.132982820606154e-06, 'max_delta_step': 0}. Best is trial 10 with value: 0.5175438596491228.

Best trial: 20. Best value: 0.533991:  42%|████▏     | 21/50 [02:10<02:04,  4.28s/it]

[I 2025-12-02 01:59:16,347] Trial 20 finished with value: 0.5339912280701754 and parameters: {'max_depth': 5, 'learning_rate': 0.08912352315788191, 'n_estimators': 551, 'subsample': 0.6231026713454237, 'colsample_bytree': 0.516706191405507, 'min_child_weight': 3, 'gamma': 0.8610219055963286, 'reg_alpha': 0.10275099682130728, 'reg_lambda': 5.830092646908458e-07, 'max_delta_step': 0}. Best is trial 20 with value: 0.5339912280701754.

Best trial: 20. Best value: 0.533991:  44%|████▍     | 22/50 [02:14<01:58,  4.25s/it]

[I 2025-12-02 01:59:20,536] Trial 21 finished with value: 0.4714912280701754 and parameters: {'max_depth': 5, 'learning_rate': 0.15049225748225398, 'n_estimators': 566, 'subsample': 0.6267300463771491, 'colsample_bytree': 0.6387259936945906, 'min_child_weight': 3, 'gamma': 0.605418065446792, 'reg_alpha': 0.061279670267070305, 'reg_lambda': 1.429708026024857e-06, 'max_delta_step': 0}. Best is trial 20 with value: 0.5339912280701754.

Best trial: 20. Best value: 0.533991:  46%|████▌     | 23/50 [02:15<01:24,  3.12s/it]

[I 2025-12-02 01:59:21,017] Trial 24 pruned.

Best trial: 20. Best value: 0.533991:  48%|████▊     | 24/50 [02:28<02:37,  6.05s/it]

[I 2025-12-02 01:59:33,890] Trial 22 finished with value: 0.3717105263157895 and parameters: {'max_depth': 5, 'learning_rate': 0.047215898373550176, 'n_estimators': 621, 'subsample': 0.6700517256335092, 'colsample_bytree': 0.6355081259701278, 'min_child_weight': 3, 'gamma': 0.7168030548015651, 'reg_alpha': 0.1764997535062871, 'reg_lambda': 1.0871986820005068e-06, 'max_delta_step': 0}. Best is trial 20 with value: 0.5339912280701754.

Best trial: 20. Best value: 0.533991:  50%|█████     | 25/50 [02:28<01:47,  4.31s/it]

[I 2025-12-02 01:59:34,146] Trial 23 finished with value: 0.48684210526315785 and parameters: {'max_depth': 9, 'learning_rate': 0.19082008285005495, 'n_estimators': 643, 'subsample': 0.6644596771221427, 'colsample_bytree': 0.654042158518801, 'min_child_weight': 4, 'gamma': 2.1466042186530405, 'reg_alpha': 0.06969232868258834, 'reg_lambda': 3.569432469365852e-06, 'max_delta_step': 0}. Best is trial 20 with value: 0.5339912280701754.

Best trial: 20. Best value: 0.533991:  52%|█████▏    | 26/50 [02:35<02:05,  5.21s/it]

[I 2025-12-02 01:59:41,475] Trial 25 finished with value: 0.45504385964912275 and parameters: {'max_depth': 6, 'learning_rate': 0.19198450132593506, 'n_estimators': 629, 'subsample': 0.6656060543369136, 'colsample_bytree': 0.5964069319315045, 'min_child_weight': 4, 'gamma': 0.6246263663683911, 'reg_alpha': 0.11080722507323405, 'reg_lambda': 4.884349216269266e-06, 'max_delta_step': 0}. Best is trial 20 with value: 0.5339912280701754.

Best trial: 20. Best value: 0.533991:  54%|█████▍    | 27/50 [02:36<01:27,  3.80s/it]

[I 2025-12-02 01:59:41,985] Trial 26 finished with value: 0.3541666666666667 and parameters: {'max_depth': 6, 'learning_rate': 0.18804922106940658, 'n_estimators': 625, 'subsample': 0.5682153542937834, 'colsample_bytree': 0.5794188712925639, 'min_child_weight': 4, 'gamma': 2.038185584323225, 'reg_alpha': 0.1289510232286239, 'reg_lambda': 1.5092670875491198e-05, 'max_delta_step': 1}. Best is trial 20 with value: 0.5339912280701754.

Best trial: 20. Best value: 0.533991:  56%|█████▌    | 28/50 [02:49<02:28,  6.74s/it]

[I 2025-12-02 01:59:55,585] Trial 27 finished with value: 0.4133771929824561 and parameters: {'max_depth': 6, 'learning_rate': 0.19679846016636504, 'n_estimators': 637, 'subsample': 0.5614265191148547, 'colsample_bytree': 0.5797135898639021, 'min_child_weight': 2, 'gamma': 2.119660276412511, 'reg_alpha': 0.0021245444207570415, 'reg_lambda': 4.913772948785123e-05, 'max_delta_step': 1}. Best is trial 20 with value: 0.5339912280701754.

Best trial: 20. Best value: 0.533991:  58%|█████▊    | 29/50 [02:57<02:28,  7.07s/it]

[I 2025-12-02 02:00:03,405] Trial 31 pruned.

Best trial: 20. Best value: 0.533991:  60%|██████    | 30/50 [03:00<01:57,  5.89s/it]

[I 2025-12-02 02:00:06,554] Trial 28 finished with value: 0.4583333333333333 and parameters: {'max_depth': 9, 'learning_rate': 0.19994481952092436, 'n_estimators': 1020, 'subsample': 0.5687887295914624, 'colsample_bytree': 0.564708702856767, 'min_child_weight': 4, 'gamma': 1.9786208217942853, 'reg_alpha': 0.0016787069118133012, 'reg_lambda': 2.2374953629718814e-05, 'max_delta_step': 1}. Best is trial 20 with value: 0.5339912280701754.

Best trial: 20. Best value: 0.533991:  62%|██████▏   | 31/50 [03:04<01:37,  5.13s/it]

[I 2025-12-02 02:00:09,920] Trial 33 pruned.

Best trial: 20. Best value: 0.533991:  64%|██████▍   | 32/50 [03:06<01:17,  4.29s/it]

[I 2025-12-02 02:00:12,225] Trial 32 pruned.

Best trial: 20. Best value: 0.533991:  66%|██████▌   | 33/50 [03:08<01:02,  3.67s/it]

[I 2025-12-02 02:00:14,448] Trial 30 finished with value: 0.45504385964912275 and parameters: {'max_depth': 10, 'learning_rate': 0.202738909080513, 'n_estimators': 969, 'subsample': 0.5633197117938735, 'colsample_bytree': 0.6829266576778175, 'min_child_weight': 2, 'gamma': 1.8237069710763762, 'reg_alpha': 0.0015322297087046546, 'reg_lambda': 2.1327542737839156e-07, 'max_delta_step': 2}. Best is trial 20 with value: 0.5339912280701754.

Best trial: 20. Best value: 0.533991:  68%|██████▊   | 34/50 [03:09<00:47,  2.94s/it]

[I 2025-12-02 02:00:15,692] Trial 29 finished with value: 0.36622807017543857 and parameters: {'max_depth': 10, 'learning_rate': 0.21268052167755766, 'n_estimators': 998, 'subsample': 0.5641946835463774, 'colsample_bytree': 0.6981343433057767, 'min_child_weight': 2, 'gamma': 2.0990828139740265, 'reg_alpha': 0.002726483277277179, 'reg_lambda': 1.4549067121348375e-05, 'max_delta_step': 1}. Best is trial 20 with value: 0.5339912280701754.

Best trial: 20. Best value: 0.533991:  70%|███████   | 35/50 [03:15<00:56,  3.78s/it]

[I 2025-12-02 02:00:21,441] Trial 37 pruned.

Best trial: 20. Best value: 0.533991:  72%|███████▏  | 36/50 [03:21<01:01,  4.39s/it]

[I 2025-12-02 02:00:27,242] Trial 38 pruned.

Best trial: 20. Best value: 0.533991:  74%|███████▍  | 37/50 [03:31<01:20,  6.16s/it]

[I 2025-12-02 02:00:37,541] Trial 35 finished with value: 0.40789473684210525 and parameters: {'max_depth': 4, 'learning_rate': 0.14662083265759168, 'n_estimators': 710, 'subsample': 0.6335670258917587, 'colsample_bytree': 0.6755725864554363, 'min_child_weight': 2, 'gamma': 0.4237308752133691, 'reg_alpha': 0.015151128375574053, 'reg_lambda': 4.067683108465434e-06, 'max_delta_step': 0}. Best is trial 20 with value: 0.5339912280701754.

Best trial: 20. Best value: 0.533991:  76%|███████▌  | 38/50 [03:42<01:29,  7.47s/it]

[I 2025-12-02 02:00:48,077] Trial 40 pruned.

Best trial: 20. Best value: 0.533991:  78%|███████▊  | 39/50 [03:47<01:14,  6.74s/it]

[I 2025-12-02 02:00:53,109] Trial 41 pruned.

Best trial: 20. Best value: 0.533991:  80%|████████  | 40/50 [03:52<01:02,  6.26s/it]

[I 2025-12-02 02:00:58,251] Trial 34 finished with value: 0.4133771929824561 and parameters: {'max_depth': 4, 'learning_rate': 0.14685109604019025, 'n_estimators': 1472, 'subsample': 0.6424298748367886, 'colsample_bytree': 0.6722573541970192, 'min_child_weight': 2, 'gamma': 0.45718689005604585, 'reg_alpha': 0.32129860732563326, 'reg_lambda': 5.173695304626435e-07, 'max_delta_step': 0}. Best is trial 20 with value: 0.5339912280701754.

Best trial: 20. Best value: 0.533991:  82%|████████▏ | 41/50 [03:56<00:50,  5.66s/it]

[I 2025-12-02 02:01:02,517] Trial 36 finished with value: 0.3980263157894737 and parameters: {'max_depth': 4, 'learning_rate': 0.14233746710540726, 'n_estimators': 1482, 'subsample': 0.639852463306413, 'colsample_bytree': 0.7437528336744702, 'min_child_weight': 3, 'gamma': 0.42610450431953756, 'reg_alpha': 0.019993674841108512, 'reg_lambda': 6.199666069995671e-06, 'max_delta_step': 0}. Best is trial 20 with value: 0.5339912280701754.

Best trial: 20. Best value: 0.533991:  84%|████████▍ | 42/50 [04:03<00:48,  6.12s/it]

[I 2025-12-02 02:01:09,705] Trial 44 pruned.

Best trial: 20. Best value: 0.533991:  86%|████████▌ | 43/50 [04:07<00:37,  5.41s/it]

[I 2025-12-02 02:01:13,449] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2939168654155914, 'n_estimators': 1459, 'subsample': 0.6366598173735465, 'colsample_bytree': 0.6070984132950791, 'min_child_weight': 5, 'gamma': 0.2761708940484049, 'reg_alpha': 2.9278798519009306e-08, 'reg_lambda': 0.0001900694539973982, 'max_delta_step': 0}. Best is trial 20 with value: 0.5339912280701754.

Best trial: 20. Best value: 0.533991:  88%|████████▊ | 44/50 [04:18<00:41,  6.97s/it]

[I 2025-12-02 02:01:24,053] Trial 42 finished with value: 0.36622807017543857 and parameters: {'max_depth': 4, 'learning_rate': 0.11448762757081046, 'n_estimators': 891, 'subsample': 0.5991922126575231, 'colsample_bytree': 0.605233359712154, 'min_child_weight': 3, 'gamma': 0.8255861055447902, 'reg_alpha': 0.029599904409216702, 'reg_lambda': 0.00042850961185746876, 'max_delta_step': 5}. Best is trial 20 with value: 0.5339912280701754.

Best trial: 20. Best value: 0.533991:  90%|█████████ | 45/50 [04:22<00:30,  6.16s/it]

[I 2025-12-02 02:01:28,316] Trial 43 finished with value: 0.45504385964912275 and parameters: {'max_depth': 5, 'learning_rate': 0.122743170585626, 'n_estimators': 876, 'subsample': 0.5932896477739519, 'colsample_bytree': 0.6120313651637439, 'min_child_weight': 3, 'gamma': 3.3817733116301825, 'reg_alpha': 1.242089239757799e-07, 'reg_lambda': 3.7522437298168527e-06, 'max_delta_step': 5}. Best is trial 20 with value: 0.5339912280701754.

Best trial: 20. Best value: 0.533991:  92%|█████████▏| 46/50 [04:26<00:22,  5.58s/it]

[I 2025-12-02 02:01:32,564] Trial 47 pruned.

Best trial: 20. Best value: 0.533991:  94%|█████████▍| 47/50 [04:27<00:12,  4.03s/it]

[I 2025-12-02 02:01:32,969] Trial 48 pruned.

Best trial: 20. Best value: 0.533991:  96%|█████████▌| 48/50 [04:30<00:07,  3.74s/it]

[I 2025-12-02 02:01:36,019] Trial 49 pruned.

Best trial: 20. Best value: 0.533991:  98%|█████████▊| 49/50 [04:35<00:04,  4.17s/it]

[I 2025-12-02 02:01:41,191] Trial 45 finished with value: 0.40789473684210525 and parameters: {'max_depth': 8, 'learning_rate': 0.23815301499106087, 'n_estimators': 1117, 'subsample': 0.5390533239846466, 'colsample_bytree': 0.60689576628508, 'min_child_weight': 5, 'gamma': 3.2259746552268225, 'reg_alpha': 1.4022465641783967e-08, 'reg_lambda': 0.0007597729623424639, 'max_delta_step': 1}. Best is trial 20 with value: 0.5339912280701754.

Best trial: 20. Best value: 0.533991: 100%|██████████| 50/50 [04:38<00:00,  5.57s/it]

[I 2025-12-02 02:01:44,075] Trial 46 finished with value: 0.3157894736842105 and parameters: {'max_depth': 5, 'learning_rate': 0.2379303139456245, 'n_estimators': 1184, 'subsample': 0.5392536916549072, 'colsample_bytree': 0.6076218652308772, 'min_child_weight': 7, 'gamma': 0.006055600153119567, 'reg_alpha': 3.921278508481707e-08, 'reg_lambda': 0.0005690593637345445, 'max_delta_step': 1}. Best is trial 20 with value: 0.5339912280701754.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.620137                0.816667      0.766667
1    15_1         loo       0.583158                0.585714      0.657143
2    17_1         loo       0.640688                0.585714      0.657143
3    19_1         loo       0.533991                0.466667      0.533333

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.633333          0.833333               0.8        50          42
1  0.169031          0.571429               0.6        50          44
2  0.169031          0.571429               0.6        50          45
3 -0.069007          0.333333               0.6        50          43

   test_size
0         11
1         12
2         12
3         11
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.620137                0.816667      0.766667
1    15_1         loo       0.583158                0.585714      0.657143
2    17_1         loo       0.640688                0.585714      0.657143
3    19_1         loo       0.533991                0.466667      0.533333

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.633333          0.833333               0.8        50          42
1  0.169031          0.571429               0.6        50          44
2  0.169031          0.571429               0.6        50          45
3 -0.069007          0.333333               0.6        50          43

   test_size
0         11
1         12
2         12
3         11

In [ ]:

datasets = task_hf_dfs_clean_ad_lbd

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_lbd_{CV_STRATEGY}_tasks/xgb_results_handcrafted_ad_lbd_extended_{CV_STRATEGY}_tasks",
    split_param="w.cz.fnusa",
)
print(summary)

[I 2025-12-02 02:01:48,826] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 45, Test size: 12
Using Leave-One-Out CV with 45 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0:   2%|▏         | 1/50 [00:18<15:18, 18.74s/it]

[I 2025-12-02 02:02:07,560] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.1684560749417041, 'n_estimators': 454, 'subsample': 0.9640896516370532, 'colsample_bytree': 0.9300051841335595, 'min_child_weight': 5, 'gamma': 2.158849305893835, 'reg_alpha': 0.024492663001685736, 'reg_lambda': 4.142962576890397, 'max_delta_step': 2}. Best is trial 2 with value: 0.0.

Best trial: 2. Best value: 0:   4%|▍         | 2/50 [00:37<14:47, 18.48s/it]

[I 2025-12-02 02:02:25,858] Trial 0 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.01685475318257995, 'n_estimators': 934, 'subsample': 0.5777162803526414, 'colsample_bytree': 0.9698828214611716, 'min_child_weight': 9, 'gamma': 1.1603539816061337, 'reg_alpha': 6.626342209786974, 'reg_lambda': 0.021659216115361694, 'max_delta_step': 5}. Best is trial 2 with value: 0.0.

Best trial: 3. Best value: 0.537449:   6%|▌         | 3/50 [00:41<09:19, 11.91s/it]

[I 2025-12-02 02:02:29,946] Trial 3 finished with value: 0.5374493927125505 and parameters: {'max_depth': 5, 'learning_rate': 0.026122038331818857, 'n_estimators': 1014, 'subsample': 0.9269909159555532, 'colsample_bytree': 0.8588421476252197, 'min_child_weight': 3, 'gamma': 3.623273998689136, 'reg_alpha': 0.05187024483999655, 'reg_lambda': 0.0028148471030009646, 'max_delta_step': 5}. Best is trial 3 with value: 0.5374493927125505.

Best trial: 3. Best value: 0.537449:   8%|▊         | 4/50 [00:45<06:53,  8.99s/it]

[I 2025-12-02 02:02:34,470] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.08981298043141811, 'n_estimators': 669, 'subsample': 0.5693059977151158, 'colsample_bytree': 0.8555659804340249, 'min_child_weight': 8, 'gamma': 1.518187311372864, 'reg_alpha': 0.00011247813587087266, 'reg_lambda': 0.04858455612055194, 'max_delta_step': 2}. Best is trial 3 with value: 0.5374493927125505.
[I 2025-12-02 02:02:34,492] Trial 1 finished with value: 0.21153846153846154 and parameters: {'max_depth': 3, 'learning_rate': 0.022158423687499665, 'n_estimators': 1187, 'subsample': 0.735149620625976, 'colsample_bytree': 0.7740964349105786, 'min_child_weight': 5, 'gamma': 0.7131670973645299, 'reg_alpha': 7.207501953242204e-06, 'reg_lambda': 4.69947321171075e-06, 'max_delta_step': 10}. Best is trial 3 with value: 0.5374493927125505.

Best trial: 3. Best value: 0.537449:  12%|█▏        | 6/50 [01:14<08:44, 11.91s/it]

[I 2025-12-02 02:03:03,460] Trial 6 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.011052418144767455, 'n_estimators': 852, 'subsample': 0.5376683493862424, 'colsample_bytree': 0.7445173172733144, 'min_child_weight': 8, 'gamma': 3.1667988105534928, 'reg_alpha': 4.7585146830891635e-05, 'reg_lambda': 0.05005742876151269, 'max_delta_step': 3}. Best is trial 3 with value: 0.5374493927125505.

Best trial: 3. Best value: 0.537449:  14%|█▍        | 7/50 [01:20<07:17, 10.18s/it]

[I 2025-12-02 02:03:09,064] Trial 8 finished with value: 0.5303643724696356 and parameters: {'max_depth': 7, 'learning_rate': 0.08408437954486421, 'n_estimators': 870, 'subsample': 0.5116118583938798, 'colsample_bytree': 0.8290222957917084, 'min_child_weight': 2, 'gamma': 2.8609010806924227, 'reg_alpha': 0.1786479148518275, 'reg_lambda': 1.0456532532672393e-05, 'max_delta_step': 0}. Best is trial 3 with value: 0.5374493927125505.

Best trial: 3. Best value: 0.537449:  16%|█▌        | 8/50 [01:27<06:34,  9.39s/it]

[I 2025-12-02 02:03:16,448] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.14043181272959918, 'n_estimators': 1296, 'subsample': 0.9050953265017858, 'colsample_bytree': 0.7801797664779416, 'min_child_weight': 8, 'gamma': 1.489545426016576, 'reg_alpha': 3.339438831521162e-06, 'reg_lambda': 0.0021556721387197943, 'max_delta_step': 6}. Best is trial 3 with value: 0.5374493927125505.

Best trial: 3. Best value: 0.537449:  18%|█▊        | 9/50 [01:42<07:26, 10.90s/it]

[I 2025-12-02 02:03:31,100] Trial 9 finished with value: 0.4726720647773279 and parameters: {'max_depth': 10, 'learning_rate': 0.060759797186779776, 'n_estimators': 686, 'subsample': 0.6491481790937654, 'colsample_bytree': 0.9684133138925224, 'min_child_weight': 3, 'gamma': 0.9568795491608789, 'reg_alpha': 1.700930923686297e-07, 'reg_lambda': 2.98196524385988e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.5374493927125505.

Best trial: 3. Best value: 0.537449:  20%|██        | 10/50 [01:44<05:30,  8.26s/it]

[I 2025-12-02 02:03:32,930] Trial 7 finished with value: 0.0840080971659919 and parameters: {'max_depth': 7, 'learning_rate': 0.059737468190885615, 'n_estimators': 1457, 'subsample': 0.7253261869372634, 'colsample_bytree': 0.7046712419198791, 'min_child_weight': 6, 'gamma': 3.277276655021785, 'reg_alpha': 0.0010060551278986108, 'reg_lambda': 0.02388828966122731, 'max_delta_step': 2}. Best is trial 3 with value: 0.5374493927125505.

Best trial: 3. Best value: 0.537449:  22%|██▏       | 11/50 [01:49<04:50,  7.46s/it]

[I 2025-12-02 02:03:38,442] Trial 13 pruned.

Best trial: 3. Best value: 0.537449:  24%|██▍       | 12/50 [01:50<03:31,  5.57s/it]

[I 2025-12-02 02:03:39,504] Trial 11 pruned.

Best trial: 3. Best value: 0.537449:  26%|██▌       | 13/50 [01:52<02:41,  4.36s/it]

[I 2025-12-02 02:03:41,017] Trial 10 finished with value: 0.5303643724696356 and parameters: {'max_depth': 8, 'learning_rate': 0.06372960036069249, 'n_estimators': 795, 'subsample': 0.6583686720472062, 'colsample_bytree': 0.885112577818932, 'min_child_weight': 3, 'gamma': 1.1020711618232715, 'reg_alpha': 0.47964714590793406, 'reg_lambda': 2.962479692588716, 'max_delta_step': 5}. Best is trial 3 with value: 0.5374493927125505.

Best trial: 3. Best value: 0.537449:  28%|██▊       | 14/50 [01:54<02:16,  3.80s/it]

[I 2025-12-02 02:03:43,473] Trial 12 pruned.

Best trial: 3. Best value: 0.537449:  30%|███       | 15/50 [02:28<07:28, 12.81s/it]

[I 2025-12-02 02:04:17,457] Trial 14 finished with value: 0.5111336032388664 and parameters: {'max_depth': 7, 'learning_rate': 0.03644580661007753, 'n_estimators': 1005, 'subsample': 0.8293079773704051, 'colsample_bytree': 0.8579776423794006, 'min_child_weight': 1, 'gamma': 4.19285704579382, 'reg_alpha': 0.06452631042077692, 'reg_lambda': 1.8999942905668633e-05, 'max_delta_step': 0}. Best is trial 3 with value: 0.5374493927125505.

Best trial: 16. Best value: 0.595142:  32%|███▏      | 16/50 [02:30<05:21,  9.46s/it]

[I 2025-12-02 02:04:19,086] Trial 16 finished with value: 0.5951417004048583 and parameters: {'max_depth': 5, 'learning_rate': 0.033716348225435615, 'n_estimators': 1009, 'subsample': 0.9968024613997565, 'colsample_bytree': 0.6461003196764322, 'min_child_weight': 1, 'gamma': 3.8130103132912057, 'reg_alpha': 0.014733384592876734, 'reg_lambda': 4.9257569177519514e-05, 'max_delta_step': 0}. Best is trial 16 with value: 0.5951417004048583.

Best trial: 16. Best value: 0.595142:  34%|███▍      | 17/50 [02:33<04:06,  7.46s/it]

[I 2025-12-02 02:04:21,846] Trial 15 finished with value: 0.5111336032388664 and parameters: {'max_depth': 5, 'learning_rate': 0.29486416114452546, 'n_estimators': 1075, 'subsample': 0.7999380112172105, 'colsample_bytree': 0.8727831725290855, 'min_child_weight': 1, 'gamma': 3.7136380471192516, 'reg_alpha': 0.06009694467347307, 'reg_lambda': 2.6729221686780337e-05, 'max_delta_step': 0}. Best is trial 16 with value: 0.5951417004048583.

Best trial: 16. Best value: 0.595142:  36%|███▌      | 18/50 [02:38<03:35,  6.73s/it]

[I 2025-12-02 02:04:26,875] Trial 17 finished with value: 0.5182186234817814 and parameters: {'max_depth': 5, 'learning_rate': 0.03550088436976296, 'n_estimators': 1097, 'subsample': 0.8150559772533588, 'colsample_bytree': 0.855816651693509, 'min_child_weight': 1, 'gamma': 3.9416868694099643, 'reg_alpha': 0.008845463807489174, 'reg_lambda': 0.00010936627906283901, 'max_delta_step': 0}. Best is trial 16 with value: 0.5951417004048583.

Best trial: 16. Best value: 0.595142:  38%|███▊      | 19/50 [02:40<02:44,  5.31s/it]

[I 2025-12-02 02:04:28,867] Trial 19 pruned.

Best trial: 16. Best value: 0.595142:  40%|████      | 20/50 [02:42<02:17,  4.59s/it]

[I 2025-12-02 02:04:31,780] Trial 20 pruned.

Best trial: 16. Best value: 0.595142:  42%|████▏     | 21/50 [03:00<04:08,  8.57s/it]

[I 2025-12-02 02:04:49,643] Trial 22 finished with value: 0.5566801619433198 and parameters: {'max_depth': 3, 'learning_rate': 0.014699057443948203, 'n_estimators': 515, 'subsample': 0.9421650657771664, 'colsample_bytree': 0.6040488859220292, 'min_child_weight': 4, 'gamma': 2.3664342322851515, 'reg_alpha': 1.0343258517210054, 'reg_lambda': 2.0883111812199882e-07, 'max_delta_step': 8}. Best is trial 16 with value: 0.5951417004048583.

Best trial: 16. Best value: 0.595142:  44%|████▍     | 22/50 [03:03<03:11,  6.85s/it]

[I 2025-12-02 02:04:52,461] Trial 23 finished with value: 0.5566801619433198 and parameters: {'max_depth': 4, 'learning_rate': 0.014468373237702564, 'n_estimators': 507, 'subsample': 0.9334322920458625, 'colsample_bytree': 0.6445956757710609, 'min_child_weight': 4, 'gamma': 2.343117630530429, 'reg_alpha': 0.9214696422323142, 'reg_lambda': 4.141961960378896e-07, 'max_delta_step': 10}. Best is trial 16 with value: 0.5951417004048583.

Best trial: 16. Best value: 0.595142:  46%|████▌     | 23/50 [03:06<02:32,  5.66s/it]

[I 2025-12-02 02:04:55,339] Trial 18 pruned.

Best trial: 16. Best value: 0.595142:  48%|████▊     | 24/50 [03:16<02:58,  6.87s/it]

[I 2025-12-02 02:05:05,051] Trial 24 finished with value: 0.5759109311740891 and parameters: {'max_depth': 4, 'learning_rate': 0.013625703167906915, 'n_estimators': 366, 'subsample': 0.9268080367806294, 'colsample_bytree': 0.6133201194721629, 'min_child_weight': 4, 'gamma': 2.429997484982251, 'reg_alpha': 0.6781754015426528, 'reg_lambda': 2.3457300457762491e-07, 'max_delta_step': 9}. Best is trial 16 with value: 0.5951417004048583.

Best trial: 16. Best value: 0.595142:  50%|█████     | 25/50 [03:19<02:21,  5.64s/it]

[I 2025-12-02 02:05:07,822] Trial 27 pruned.

Best trial: 16. Best value: 0.595142:  52%|█████▏    | 26/50 [03:22<01:56,  4.86s/it]

[I 2025-12-02 02:05:10,853] Trial 26 finished with value: 0.5566801619433198 and parameters: {'max_depth': 4, 'learning_rate': 0.014360345241694796, 'n_estimators': 351, 'subsample': 0.93903322127792, 'colsample_bytree': 0.5712321370737867, 'min_child_weight': 4, 'gamma': 2.1937352790598017, 'reg_alpha': 0.8095217191962552, 'reg_lambda': 6.330283099611593e-07, 'max_delta_step': 10}. Best is trial 16 with value: 0.5951417004048583.

Best trial: 16. Best value: 0.595142:  54%|█████▍    | 27/50 [03:22<01:21,  3.54s/it]

[I 2025-12-02 02:05:11,313] Trial 25 finished with value: 0.5566801619433198 and parameters: {'max_depth': 4, 'learning_rate': 0.01545207374166009, 'n_estimators': 440, 'subsample': 0.9471322162477432, 'colsample_bytree': 0.6195872145122897, 'min_child_weight': 4, 'gamma': 2.1700866090947293, 'reg_alpha': 1.1350851031422382, 'reg_lambda': 2.1179724195120927e-07, 'max_delta_step': 10}. Best is trial 16 with value: 0.5951417004048583.

Best trial: 16. Best value: 0.595142:  56%|█████▌    | 28/50 [03:26<01:22,  3.77s/it]

[I 2025-12-02 02:05:15,623] Trial 21 finished with value: 0.5566801619433198 and parameters: {'max_depth': 3, 'learning_rate': 0.03897641773706016, 'n_estimators': 1231, 'subsample': 0.9968624232965925, 'colsample_bytree': 0.5926630862720176, 'min_child_weight': 3, 'gamma': 2.405010938807191, 'reg_alpha': 0.0007683270238837362, 'reg_lambda': 6.855324563617882e-08, 'max_delta_step': 8}. Best is trial 16 with value: 0.5951417004048583.

Best trial: 16. Best value: 0.595142:  58%|█████▊    | 29/50 [03:36<01:55,  5.50s/it]

[I 2025-12-02 02:05:25,172] Trial 28 finished with value: 0.582995951417004 and parameters: {'max_depth': 4, 'learning_rate': 0.01218875925748402, 'n_estimators': 417, 'subsample': 0.9471556946247672, 'colsample_bytree': 0.5725561464987468, 'min_child_weight': 4, 'gamma': 0.2763859285179655, 'reg_alpha': 0.3562414662682072, 'reg_lambda': 4.856664279121679e-07, 'max_delta_step': 7}. Best is trial 16 with value: 0.5951417004048583.

Best trial: 16. Best value: 0.595142:  60%|██████    | 30/50 [03:38<01:30,  4.52s/it]

[I 2025-12-02 02:05:27,381] Trial 32 pruned.

Best trial: 16. Best value: 0.595142:  62%|██████▏   | 31/50 [03:43<01:29,  4.69s/it]

[I 2025-12-02 02:05:32,470] Trial 33 pruned.

Best trial: 29. Best value: 0.609312:  64%|██████▍   | 32/50 [03:44<01:04,  3.57s/it]

[I 2025-12-02 02:05:33,437] Trial 29 finished with value: 0.6093117408906883 and parameters: {'max_depth': 3, 'learning_rate': 0.02389544633267476, 'n_estimators': 563, 'subsample': 0.7847127795498352, 'colsample_bytree': 0.6827157511464979, 'min_child_weight': 4, 'gamma': 2.761972578576271, 'reg_alpha': 0.24294250669435533, 'reg_lambda': 5.997693479207751e-08, 'max_delta_step': 7}. Best is trial 29 with value: 0.6093117408906883.

Best trial: 29. Best value: 0.609312:  66%|██████▌   | 33/50 [03:47<00:57,  3.36s/it]

[I 2025-12-02 02:05:36,317] Trial 30 finished with value: 0.5566801619433198 and parameters: {'max_depth': 3, 'learning_rate': 0.010044726422212467, 'n_estimators': 571, 'subsample': 0.8922488556835584, 'colsample_bytree': 0.6892065687501605, 'min_child_weight': 2, 'gamma': 0.06942410824315548, 'reg_alpha': 0.21414823853125184, 'reg_lambda': 1.381247731623832e-06, 'max_delta_step': 7}. Best is trial 29 with value: 0.6093117408906883.

Best trial: 29. Best value: 0.609312:  68%|██████▊   | 34/50 [03:48<00:40,  2.53s/it]

[I 2025-12-02 02:05:36,888] Trial 31 pruned.

Best trial: 29. Best value: 0.609312:  70%|███████   | 35/50 [03:54<00:53,  3.58s/it]

[I 2025-12-02 02:05:42,933] Trial 34 pruned.

Best trial: 29. Best value: 0.609312:  72%|███████▏  | 36/50 [03:54<00:37,  2.65s/it]

[I 2025-12-02 02:05:43,402] Trial 36 pruned.

Best trial: 29. Best value: 0.609312:  74%|███████▍  | 37/50 [03:58<00:39,  3.01s/it]

[I 2025-12-02 02:05:47,273] Trial 39 pruned.

Best trial: 29. Best value: 0.609312:  76%|███████▌  | 38/50 [03:59<00:27,  2.29s/it]

[I 2025-12-02 02:05:47,865] Trial 35 pruned.

Best trial: 29. Best value: 0.609312:  78%|███████▊  | 39/50 [04:01<00:24,  2.25s/it]

[I 2025-12-02 02:05:50,014] Trial 40 pruned.

Best trial: 29. Best value: 0.609312:  80%|████████  | 40/50 [04:01<00:16,  1.69s/it]

[I 2025-12-02 02:05:50,398] Trial 38 pruned.

Best trial: 29. Best value: 0.609312:  82%|████████▏ | 41/50 [04:02<00:13,  1.54s/it]

[I 2025-12-02 02:05:51,599] Trial 37 pruned.

Best trial: 29. Best value: 0.609312:  84%|████████▍ | 42/50 [04:07<00:20,  2.56s/it]

[I 2025-12-02 02:05:56,521] Trial 41 pruned.

Best trial: 29. Best value: 0.609312:  86%|████████▌ | 43/50 [04:08<00:15,  2.16s/it]

[I 2025-12-02 02:05:57,744] Trial 42 pruned.

Best trial: 29. Best value: 0.609312:  88%|████████▊ | 44/50 [04:10<00:11,  1.97s/it]

[I 2025-12-02 02:05:59,295] Trial 43 pruned.

Best trial: 29. Best value: 0.609312:  90%|█████████ | 45/50 [04:32<00:40,  8.04s/it]

[I 2025-12-02 02:06:21,479] Trial 47 pruned.

Best trial: 29. Best value: 0.609312:  92%|█████████▏| 46/50 [04:33<00:23,  5.77s/it]

[I 2025-12-02 02:06:21,947] Trial 45 finished with value: 0.5303643724696356 and parameters: {'max_depth': 3, 'learning_rate': 0.012291425200337809, 'n_estimators': 620, 'subsample': 0.9731326176765441, 'colsample_bytree': 0.5840538786574458, 'min_child_weight': 4, 'gamma': 3.242291113286744, 'reg_alpha': 0.08603678952385677, 'reg_lambda': 7.962372752184996e-08, 'max_delta_step': 8}. Best is trial 29 with value: 0.6093117408906883.

Best trial: 29. Best value: 0.609312:  96%|█████████▌| 48/50 [04:39<00:08,  4.23s/it]

[I 2025-12-02 02:06:28,438] Trial 48 pruned.
[I 2025-12-02 02:06:28,567] Trial 44 finished with value: 0.5303643724696356 and parameters: {'max_depth': 3, 'learning_rate': 0.031129755580813056, 'n_estimators': 941, 'subsample': 0.9690474651327959, 'colsample_bytree': 0.5849443938730102, 'min_child_weight': 4, 'gamma': 3.256931393134984, 'reg_alpha': 2.7581538018533553, 'reg_lambda': 9.007665390230028e-08, 'max_delta_step': 1}. Best is trial 29 with value: 0.6093117408906883.

Best trial: 29. Best value: 0.609312:  98%|█████████▊| 49/50 [04:47<00:05,  5.36s/it]

[I 2025-12-02 02:06:36,584] Trial 46 finished with value: 0.5303643724696356 and parameters: {'max_depth': 3, 'learning_rate': 0.029989745490615886, 'n_estimators': 1350, 'subsample': 0.9198677385343078, 'colsample_bytree': 0.5848251828807368, 'min_child_weight': 4, 'gamma': 3.3223450766051505, 'reg_alpha': 0.08167204837282806, 'reg_lambda': 6.892077191683974e-08, 'max_delta_step': 1}. Best is trial 29 with value: 0.6093117408906883.

Best trial: 29. Best value: 0.609312: 100%|██████████| 50/50 [04:48<00:00,  5.77s/it]

[I 2025-12-02 02:06:37,224] Trial 49 finished with value: 0.5303643724696356 and parameters: {'max_depth': 3, 'learning_rate': 0.09473672700492579, 'n_estimators': 785, 'subsample': 0.9154656307916077, 'colsample_bytree': 0.539785633786408, 'min_child_weight': 3, 'gamma': 1.60498111276149, 'reg_alpha': 2.540652651682348e-05, 'reg_lambda': 4.869357717674458e-07, 'max_delta_step': 5}. Best is trial 29 with value: 0.6093117408906883.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 02:06:40,419] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 45, Test size: 12
Using Leave-One-Out CV with 45 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.427126:   2%|▏         | 1/50 [00:11<09:39, 11.83s/it]

[I 2025-12-02 02:06:52,240] Trial 1 finished with value: 0.4271255060728745 and parameters: {'max_depth': 7, 'learning_rate': 0.2762728269502877, 'n_estimators': 283, 'subsample': 0.5354559542581929, 'colsample_bytree': 0.6262068654458559, 'min_child_weight': 3, 'gamma': 3.7649308551532856, 'reg_alpha': 4.975780669140998e-05, 'reg_lambda': 5.403038201618531e-07, 'max_delta_step': 0}. Best is trial 1 with value: 0.4271255060728745.

Best trial: 1. Best value: 0.427126:   4%|▍         | 2/50 [00:32<13:28, 16.84s/it]

[I 2025-12-02 02:07:12,594] Trial 4 finished with value: 0.4149797570850202 and parameters: {'max_depth': 5, 'learning_rate': 0.06883401979158224, 'n_estimators': 507, 'subsample': 0.869816646876274, 'colsample_bytree': 0.9760569474634392, 'min_child_weight': 3, 'gamma': 1.9692278178364242, 'reg_alpha': 2.9657625698125063, 'reg_lambda': 4.0357401572102434e-05, 'max_delta_step': 1}. Best is trial 1 with value: 0.4271255060728745.

Best trial: 1. Best value: 0.427126:   6%|▌         | 3/50 [00:43<11:10, 14.27s/it]

[I 2025-12-02 02:07:23,801] Trial 5 finished with value: 0.40789473684210525 and parameters: {'max_depth': 5, 'learning_rate': 0.07870840871068961, 'n_estimators': 255, 'subsample': 0.7903195165197197, 'colsample_bytree': 0.7220549333958927, 'min_child_weight': 3, 'gamma': 3.6193278701112472, 'reg_alpha': 0.1558547479242593, 'reg_lambda': 0.5977739925679789, 'max_delta_step': 2}. Best is trial 1 with value: 0.4271255060728745.

Best trial: 1. Best value: 0.427126:   8%|▊         | 4/50 [00:45<07:06,  9.27s/it]

[I 2025-12-02 02:07:25,413] Trial 0 finished with value: 0.07692307692307693 and parameters: {'max_depth': 3, 'learning_rate': 0.013536006234758109, 'n_estimators': 1148, 'subsample': 0.5025879147635582, 'colsample_bytree': 0.8421349221396173, 'min_child_weight': 5, 'gamma': 1.9318963663180866, 'reg_alpha': 5.7627216153266165e-08, 'reg_lambda': 3.06901885972347e-05, 'max_delta_step': 10}. Best is trial 1 with value: 0.4271255060728745.

Best trial: 1. Best value: 0.427126:  10%|█         | 5/50 [00:45<04:42,  6.27s/it]

[I 2025-12-02 02:07:26,368] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.05033924555598047, 'n_estimators': 1190, 'subsample': 0.5176061796352294, 'colsample_bytree': 0.7234511249575484, 'min_child_weight': 9, 'gamma': 2.3181887641258188, 'reg_alpha': 4.251471591695191e-08, 'reg_lambda': 5.2798313121184763e-08, 'max_delta_step': 0}. Best is trial 1 with value: 0.4271255060728745.

Best trial: 1. Best value: 0.427126:  12%|█▏        | 6/50 [00:48<03:46,  5.15s/it]

[I 2025-12-02 02:07:29,332] Trial 3 finished with value: 0.38866396761133604 and parameters: {'max_depth': 8, 'learning_rate': 0.01577949952143693, 'n_estimators': 1239, 'subsample': 0.691041617884918, 'colsample_bytree': 0.8911042643767688, 'min_child_weight': 3, 'gamma': 1.9171241404385164, 'reg_alpha': 2.424171579410362, 'reg_lambda': 3.3486721448647176e-07, 'max_delta_step': 1}. Best is trial 1 with value: 0.4271255060728745.

Best trial: 1. Best value: 0.427126:  14%|█▍        | 7/50 [01:08<07:03,  9.85s/it]

[I 2025-12-02 02:07:48,870] Trial 6 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.11422537542886252, 'n_estimators': 639, 'subsample': 0.629727006782801, 'colsample_bytree': 0.7882676808544635, 'min_child_weight': 7, 'gamma': 2.5074407225756956, 'reg_alpha': 2.295427802392842, 'reg_lambda': 0.6306659614731562, 'max_delta_step': 5}. Best is trial 1 with value: 0.4271255060728745.

Best trial: 1. Best value: 0.427126:  16%|█▌        | 8/50 [01:16<06:29,  9.27s/it]

[I 2025-12-02 02:07:56,889] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.17242168097413332, 'n_estimators': 806, 'subsample': 0.5821820135306265, 'colsample_bytree': 0.5064622474492125, 'min_child_weight': 9, 'gamma': 2.1790587179077003, 'reg_alpha': 0.07847673555129508, 'reg_lambda': 4.18945564027014e-05, 'max_delta_step': 8}. Best is trial 1 with value: 0.4271255060728745.

Best trial: 1. Best value: 0.427126:  18%|█▊        | 9/50 [01:17<04:28,  6.54s/it]

[I 2025-12-02 02:07:57,425] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.020531724141198457, 'n_estimators': 709, 'subsample': 0.9390906191107442, 'colsample_bytree': 0.6132915616121104, 'min_child_weight': 7, 'gamma': 4.883030874639334, 'reg_alpha': 0.00048309320695045827, 'reg_lambda': 2.166402474458066e-06, 'max_delta_step': 8}. Best is trial 1 with value: 0.4271255060728745.

Best trial: 1. Best value: 0.427126:  20%|██        | 10/50 [01:30<05:45,  8.65s/it]

[I 2025-12-02 02:08:10,799] Trial 12 finished with value: 0.4271255060728745 and parameters: {'max_depth': 8, 'learning_rate': 0.013116082713036362, 'n_estimators': 307, 'subsample': 0.9354646510147648, 'colsample_bytree': 0.694367433196547, 'min_child_weight': 4, 'gamma': 2.356557192200221, 'reg_alpha': 0.45809379434066266, 'reg_lambda': 2.471107523906787e-05, 'max_delta_step': 3}. Best is trial 1 with value: 0.4271255060728745.

Best trial: 8. Best value: 0.498988:  22%|██▏       | 11/50 [01:37<05:14,  8.07s/it]

[I 2025-12-02 02:08:17,570] Trial 8 finished with value: 0.4989878542510121 and parameters: {'max_depth': 9, 'learning_rate': 0.12877614973266888, 'n_estimators': 1324, 'subsample': 0.7636118968146803, 'colsample_bytree': 0.8637607064738215, 'min_child_weight': 2, 'gamma': 3.376855247489103, 'reg_alpha': 3.7451216761697436e-05, 'reg_lambda': 0.09000587415421785, 'max_delta_step': 5}. Best is trial 8 with value: 0.4989878542510121.

Best trial: 8. Best value: 0.498988:  24%|██▍       | 12/50 [01:41<04:18,  6.81s/it]

[I 2025-12-02 02:08:21,487] Trial 11 pruned.

Best trial: 8. Best value: 0.498988:  26%|██▌       | 13/50 [01:49<04:29,  7.29s/it]

[I 2025-12-02 02:08:29,874] Trial 15 pruned.

Best trial: 8. Best value: 0.498988:  28%|██▊       | 14/50 [02:02<05:28,  9.13s/it]

[I 2025-12-02 02:08:43,263] Trial 10 finished with value: 0.38866396761133604 and parameters: {'max_depth': 4, 'learning_rate': 0.06033695668594885, 'n_estimators': 1405, 'subsample': 0.6979496641485419, 'colsample_bytree': 0.8246297050599883, 'min_child_weight': 4, 'gamma': 3.346967867858146, 'reg_alpha': 0.03132974227361113, 'reg_lambda': 0.0001515980229144527, 'max_delta_step': 6}. Best is trial 8 with value: 0.4989878542510121.

Best trial: 13. Best value: 0.647773:  30%|███       | 15/50 [02:07<04:29,  7.69s/it]

[I 2025-12-02 02:08:47,631] Trial 13 finished with value: 0.6477732793522267 and parameters: {'max_depth': 10, 'learning_rate': 0.2871022423078553, 'n_estimators': 944, 'subsample': 0.7586522358774087, 'colsample_bytree': 0.5717714513897423, 'min_child_weight': 1, 'gamma': 0.040731401281600466, 'reg_alpha': 8.969557340530957e-06, 'reg_lambda': 0.008717565937003395, 'max_delta_step': 4}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  32%|███▏      | 16/50 [02:11<03:46,  6.66s/it]

[I 2025-12-02 02:08:51,890] Trial 17 pruned.

Best trial: 13. Best value: 0.647773:  34%|███▍      | 17/50 [02:20<04:05,  7.44s/it]

[I 2025-12-02 02:09:01,131] Trial 19 pruned.

Best trial: 13. Best value: 0.647773:  36%|███▌      | 18/50 [02:30<04:23,  8.23s/it]

[I 2025-12-02 02:09:11,198] Trial 14 finished with value: 0.5445344129554656 and parameters: {'max_depth': 10, 'learning_rate': 0.2638624119700768, 'n_estimators': 1404, 'subsample': 0.7720793606467781, 'colsample_bytree': 0.5970368501971947, 'min_child_weight': 1, 'gamma': 0.214023580089854, 'reg_alpha': 2.263638232708908e-05, 'reg_lambda': 0.0035846575119508153, 'max_delta_step': 4}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  38%|███▊      | 19/50 [02:32<03:13,  6.24s/it]

[I 2025-12-02 02:09:12,805] Trial 20 pruned.

Best trial: 13. Best value: 0.647773:  40%|████      | 20/50 [02:45<04:06,  8.22s/it]

[I 2025-12-02 02:09:25,657] Trial 18 finished with value: 0.5708502024291497 and parameters: {'max_depth': 10, 'learning_rate': 0.15827864239143144, 'n_estimators': 972, 'subsample': 0.8103627549192828, 'colsample_bytree': 0.9301607397058135, 'min_child_weight': 1, 'gamma': 0.05062282668879411, 'reg_alpha': 1.4453746819468523e-06, 'reg_lambda': 0.006219217741810597, 'max_delta_step': 4}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  42%|████▏     | 21/50 [02:47<03:02,  6.30s/it]

[I 2025-12-02 02:09:27,467] Trial 16 finished with value: 0.5323886639676113 and parameters: {'max_depth': 10, 'learning_rate': 0.261597210309392, 'n_estimators': 1487, 'subsample': 0.6920439976519749, 'colsample_bytree': 0.9232880395365597, 'min_child_weight': 1, 'gamma': 0.20571362755832112, 'reg_alpha': 7.19869958749551e-05, 'reg_lambda': 0.0048289907901215064, 'max_delta_step': 6}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  44%|████▍     | 22/50 [02:52<02:49,  6.05s/it]

[I 2025-12-02 02:09:32,948] Trial 23 pruned.

Best trial: 13. Best value: 0.647773:  46%|████▌     | 23/50 [03:20<05:39, 12.56s/it]

[I 2025-12-02 02:10:00,698] Trial 25 pruned.

Best trial: 13. Best value: 0.647773:  48%|████▊     | 24/50 [03:20<03:51,  8.92s/it]

[I 2025-12-02 02:10:01,115] Trial 24 finished with value: 0.590080971659919 and parameters: {'max_depth': 10, 'learning_rate': 0.20848289147775334, 'n_estimators': 871, 'subsample': 0.8566601748343404, 'colsample_bytree': 0.5606747387996527, 'min_child_weight': 2, 'gamma': 0.8839889608683221, 'reg_alpha': 1.0259469567647654e-06, 'reg_lambda': 0.0007221227809982643, 'max_delta_step': 3}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  50%|█████     | 25/50 [03:29<03:39,  8.78s/it]

[I 2025-12-02 02:10:09,581] Trial 21 finished with value: 0.4726720647773279 and parameters: {'max_depth': 10, 'learning_rate': 0.03465871766315048, 'n_estimators': 1491, 'subsample': 0.855213647250803, 'colsample_bytree': 0.563664321004981, 'min_child_weight': 2, 'gamma': 0.8489238609982779, 'reg_alpha': 6.657018443461579e-07, 'reg_lambda': 0.0018010409643512571, 'max_delta_step': 3}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  52%|█████▏    | 26/50 [03:31<02:46,  6.95s/it]

[I 2025-12-02 02:10:12,239] Trial 22 finished with value: 0.45344129554655865 and parameters: {'max_depth': 10, 'learning_rate': 0.02703197075287691, 'n_estimators': 1499, 'subsample': 0.8751165573589974, 'colsample_bytree': 0.5596675529370221, 'min_child_weight': 2, 'gamma': 0.8784066808331489, 'reg_alpha': 4.109594734796437e-07, 'reg_lambda': 0.0009448959132052738, 'max_delta_step': 3}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  54%|█████▍    | 27/50 [03:55<04:34, 11.96s/it]

[I 2025-12-02 02:10:35,884] Trial 26 finished with value: 0.5587044534412955 and parameters: {'max_depth': 10, 'learning_rate': 0.10735970890805308, 'n_estimators': 881, 'subsample': 0.6377931457673771, 'colsample_bytree': 0.53686438331124, 'min_child_weight': 2, 'gamma': 0.6573207950890803, 'reg_alpha': 6.120665632255278e-06, 'reg_lambda': 0.0004756037389848155, 'max_delta_step': 4}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  56%|█████▌    | 28/50 [03:56<03:07,  8.54s/it]

[I 2025-12-02 02:10:36,459] Trial 27 finished with value: 0.6022267206477733 and parameters: {'max_depth': 9, 'learning_rate': 0.0967992868590827, 'n_estimators': 878, 'subsample': 0.8440716869368777, 'colsample_bytree': 0.5613256339547725, 'min_child_weight': 2, 'gamma': 0.662602455065198, 'reg_alpha': 2.6189930124471395e-07, 'reg_lambda': 0.0005500426395667712, 'max_delta_step': 2}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  58%|█████▊    | 29/50 [04:03<02:54,  8.33s/it]

[I 2025-12-02 02:10:44,300] Trial 28 finished with value: 0.5708502024291497 and parameters: {'max_depth': 9, 'learning_rate': 0.10231611054737294, 'n_estimators': 893, 'subsample': 0.9146446425786622, 'colsample_bytree': 0.5393807525600629, 'min_child_weight': 4, 'gamma': 1.3357350527319392, 'reg_alpha': 1.1485257397429016e-08, 'reg_lambda': 0.0005802763652204551, 'max_delta_step': 2}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  60%|██████    | 30/50 [04:06<02:11,  6.57s/it]

[I 2025-12-02 02:10:46,751] Trial 29 finished with value: 0.5253036437246963 and parameters: {'max_depth': 9, 'learning_rate': 0.09193618509384827, 'n_estimators': 878, 'subsample': 0.9160403803894362, 'colsample_bytree': 0.666247276098237, 'min_child_weight': 4, 'gamma': 1.424447430837564, 'reg_alpha': 1.1413262682826136e-08, 'reg_lambda': 0.0357141175264637, 'max_delta_step': 2}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  62%|██████▏   | 31/50 [04:10<01:50,  5.79s/it]

[I 2025-12-02 02:10:50,726] Trial 32 pruned.

Best trial: 13. Best value: 0.647773:  64%|██████▍   | 32/50 [04:12<01:27,  4.85s/it]

[I 2025-12-02 02:10:53,371] Trial 33 pruned.

Best trial: 13. Best value: 0.647773:  66%|██████▌   | 33/50 [04:14<01:07,  3.97s/it]

[I 2025-12-02 02:10:55,284] Trial 30 pruned.

Best trial: 13. Best value: 0.647773:  68%|██████▊   | 34/50 [04:24<01:30,  5.65s/it]

[I 2025-12-02 02:11:04,858] Trial 31 finished with value: 0.5253036437246963 and parameters: {'max_depth': 9, 'learning_rate': 0.09309463754645741, 'n_estimators': 711, 'subsample': 0.9212843042044783, 'colsample_bytree': 0.6537567205034183, 'min_child_weight': 4, 'gamma': 1.3722378746651647, 'reg_alpha': 1.070192311113533e-08, 'reg_lambda': 7.500201173177942e-06, 'max_delta_step': 2}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  70%|███████   | 35/50 [04:33<01:40,  6.71s/it]

[I 2025-12-02 02:11:14,039] Trial 37 pruned.

Best trial: 13. Best value: 0.647773:  72%|███████▏  | 36/50 [04:39<01:31,  6.52s/it]

[I 2025-12-02 02:11:20,128] Trial 34 finished with value: 0.582995951417004 and parameters: {'max_depth': 9, 'learning_rate': 0.2159053857007311, 'n_estimators': 746, 'subsample': 0.8364582129061588, 'colsample_bytree': 0.593009966877942, 'min_child_weight': 1, 'gamma': 0.46905302044936764, 'reg_alpha': 1.6805005472517565e-07, 'reg_lambda': 0.00019064367649301858, 'max_delta_step': 1}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  74%|███████▍  | 37/50 [04:55<02:00,  9.30s/it]

[I 2025-12-02 02:11:35,909] Trial 35 finished with value: 0.5566801619433198 and parameters: {'max_depth': 9, 'learning_rate': 0.14185730428575546, 'n_estimators': 1076, 'subsample': 0.8223978570959567, 'colsample_bytree': 0.9935754661083471, 'min_child_weight': 1, 'gamma': 0.5243185297428493, 'reg_alpha': 3.6460824570870766e-06, 'reg_lambda': 0.0001506068703829735, 'max_delta_step': 6}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  76%|███████▌  | 38/50 [04:58<01:30,  7.54s/it]

[I 2025-12-02 02:11:39,332] Trial 39 finished with value: 0.5182186234817814 and parameters: {'max_depth': 7, 'learning_rate': 0.20832860615842758, 'n_estimators': 479, 'subsample': 0.8923950740389212, 'colsample_bytree': 0.57805051280301, 'min_child_weight': 3, 'gamma': 1.7072662089652177, 'reg_alpha': 2.3724861641239037e-07, 'reg_lambda': 1.4883080732678946e-08, 'max_delta_step': 0}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  78%|███████▊  | 39/50 [04:59<00:58,  5.34s/it]

[I 2025-12-02 02:11:39,534] Trial 36 finished with value: 0.5516194331983806 and parameters: {'max_depth': 7, 'learning_rate': 0.20609767181643437, 'n_estimators': 1096, 'subsample': 0.8294674778941996, 'colsample_bytree': 0.9964308253907307, 'min_child_weight': 1, 'gamma': 0.5772240897900971, 'reg_alpha': 2.739911063293464e-06, 'reg_lambda': 0.00014680831485779758, 'max_delta_step': 6}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  80%|████████  | 40/50 [05:09<01:07,  6.73s/it]

[I 2025-12-02 02:11:49,525] Trial 41 pruned.

Best trial: 13. Best value: 0.647773:  82%|████████▏ | 41/50 [05:13<00:55,  6.15s/it]

[I 2025-12-02 02:11:54,314] Trial 42 pruned.

Best trial: 13. Best value: 0.647773:  84%|████████▍ | 42/50 [05:16<00:39,  4.94s/it]

[I 2025-12-02 02:11:56,431] Trial 40 finished with value: 0.5182186234817814 and parameters: {'max_depth': 7, 'learning_rate': 0.21236388269924772, 'n_estimators': 500, 'subsample': 0.8916637435592637, 'colsample_bytree': 0.5813898695474101, 'min_child_weight': 3, 'gamma': 1.7360072180775603, 'reg_alpha': 2.49109994480125e-07, 'reg_lambda': 1.053944770664817e-08, 'max_delta_step': 0}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  86%|████████▌ | 43/50 [05:21<00:35,  5.02s/it]

[I 2025-12-02 02:12:01,631] Trial 38 finished with value: 0.5708502024291497 and parameters: {'max_depth': 7, 'learning_rate': 0.1998394167450159, 'n_estimators': 1204, 'subsample': 0.798642427872742, 'colsample_bytree': 0.9978238204074903, 'min_child_weight': 3, 'gamma': 0.03550342046681798, 'reg_alpha': 1.959091616097421e-07, 'reg_lambda': 0.00011162390427514622, 'max_delta_step': 6}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  88%|████████▊ | 44/50 [05:28<00:33,  5.66s/it]

[I 2025-12-02 02:12:08,801] Trial 46 pruned.

Best trial: 13. Best value: 0.647773:  90%|█████████ | 45/50 [05:41<00:38,  7.78s/it]

[I 2025-12-02 02:12:21,518] Trial 43 finished with value: 0.5303643724696356 and parameters: {'max_depth': 8, 'learning_rate': 0.2510509477911836, 'n_estimators': 792, 'subsample': 0.7836339017129885, 'colsample_bytree': 0.701211340850403, 'min_child_weight': 3, 'gamma': 2.746966365436797, 'reg_alpha': 1.3476515408857125e-07, 'reg_lambda': 6.550622861360569e-05, 'max_delta_step': 1}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  92%|█████████▏| 46/50 [05:47<00:28,  7.25s/it]

[I 2025-12-02 02:12:27,522] Trial 45 finished with value: 0.5708502024291497 and parameters: {'max_depth': 10, 'learning_rate': 0.1787701036699375, 'n_estimators': 794, 'subsample': 0.7857565647172463, 'colsample_bytree': 0.6314706437840781, 'min_child_weight': 2, 'gamma': 0.05908000295748572, 'reg_alpha': 4.5216188385086946e-08, 'reg_lambda': 5.8011119766803975e-05, 'max_delta_step': 5}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  94%|█████████▍| 47/50 [05:49<00:17,  5.74s/it]

[I 2025-12-02 02:12:29,753] Trial 48 pruned.

Best trial: 13. Best value: 0.647773:  96%|█████████▌| 48/50 [05:51<00:09,  4.53s/it]

[I 2025-12-02 02:12:31,470] Trial 44 finished with value: 0.5445344129554656 and parameters: {'max_depth': 10, 'learning_rate': 0.17063327958009075, 'n_estimators': 942, 'subsample': 0.7873445787574419, 'colsample_bytree': 0.7342773912417356, 'min_child_weight': 2, 'gamma': 0.015186304117840076, 'reg_alpha': 3.3267032791502237e-07, 'reg_lambda': 0.015341175666868401, 'max_delta_step': 4}. Best is trial 13 with value: 0.6477732793522267.

Best trial: 13. Best value: 0.647773:  98%|█████████▊| 49/50 [05:51<00:03,  3.42s/it]

[I 2025-12-02 02:12:32,305] Trial 47 pruned.

Best trial: 13. Best value: 0.647773: 100%|██████████| 50/50 [05:52<00:00,  7.05s/it]

[I 2025-12-02 02:12:32,725] Trial 49 pruned.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 02:12:37,015] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 45, Test size: 12
Using Leave-One-Out CV with 45 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.41498:   2%|▏         | 1/50 [00:20<16:46, 20.55s/it]

[I 2025-12-02 02:12:57,542] Trial 0 finished with value: 0.4149797570850202 and parameters: {'max_depth': 10, 'learning_rate': 0.011932813678130585, 'n_estimators': 523, 'subsample': 0.7726014295828199, 'colsample_bytree': 0.9021762233216615, 'min_child_weight': 4, 'gamma': 2.854662018080738, 'reg_alpha': 1.4602157517270002, 'reg_lambda': 1.8040813853989628e-08, 'max_delta_step': 8}. Best is trial 0 with value: 0.4149797570850202.

Best trial: 4. Best value: 0.525304:   4%|▍         | 2/50 [00:41<16:49, 21.03s/it]

[I 2025-12-02 02:13:18,920] Trial 4 finished with value: 0.5253036437246963 and parameters: {'max_depth': 9, 'learning_rate': 0.1664664062943456, 'n_estimators': 558, 'subsample': 0.771324968982738, 'colsample_bytree': 0.542404252925176, 'min_child_weight': 4, 'gamma': 2.0478244513641153, 'reg_alpha': 0.000834051875566047, 'reg_lambda': 1.786101847446852e-06, 'max_delta_step': 2}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:   6%|▌         | 3/50 [00:50<11:54, 15.20s/it]

[I 2025-12-02 02:13:27,192] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.22669117012361092, 'n_estimators': 1264, 'subsample': 0.9467378887337248, 'colsample_bytree': 0.6968782105678724, 'min_child_weight': 5, 'gamma': 4.947637829515102, 'reg_alpha': 2.7560248440691962e-08, 'reg_lambda': 0.007408757776324038, 'max_delta_step': 9}. Best is trial 4 with value: 0.5253036437246963.
[I 2025-12-02 02:13:27,361] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.037512182988970924, 'n_estimators': 1254, 'subsample': 0.5124539220803057, 'colsample_bytree': 0.9481951661597987, 'min_child_weight': 8, 'gamma': 2.3466198839407326, 'reg_alpha': 0.0018460486240258326, 'reg_lambda': 6.245267339824831, 'max_delta_step': 4}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:   8%|▊         | 4/50 [00:50<07:06,  9.27s/it]

[I 2025-12-02 02:13:27,372] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.24258663224276142, 'n_estimators': 1289, 'subsample': 0.936759270923391, 'colsample_bytree': 0.9144364285558282, 'min_child_weight': 10, 'gamma': 4.927362583648056, 'reg_alpha': 5.033031056900891e-08, 'reg_lambda': 0.0962293400473307, 'max_delta_step': 7}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:  12%|█▏        | 6/50 [00:53<03:47,  5.17s/it]

[I 2025-12-02 02:13:30,421] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.02946129452580882, 'n_estimators': 263, 'subsample': 0.5875796598388972, 'colsample_bytree': 0.8186666540236094, 'min_child_weight': 5, 'gamma': 2.454696728540719, 'reg_alpha': 0.0040917569430958325, 'reg_lambda': 5.003566149993271e-05, 'max_delta_step': 2}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:  14%|█▍        | 7/50 [01:03<04:45,  6.65s/it]

[I 2025-12-02 02:13:40,983] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.26033746287500686, 'n_estimators': 328, 'subsample': 0.9586976231951526, 'colsample_bytree': 0.8597150993182234, 'min_child_weight': 5, 'gamma': 1.4004810808518275, 'reg_alpha': 7.77092846982981e-06, 'reg_lambda': 1.634786924136263e-08, 'max_delta_step': 9}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:  16%|█▌        | 8/50 [01:10<04:34,  6.53s/it]

[I 2025-12-02 02:13:47,232] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.08611580231752425, 'n_estimators': 411, 'subsample': 0.6547777924177314, 'colsample_bytree': 0.8128242628706013, 'min_child_weight': 5, 'gamma': 0.6699526673095796, 'reg_alpha': 7.365513732863373, 'reg_lambda': 8.393511469810223e-05, 'max_delta_step': 9}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:  18%|█▊        | 9/50 [01:14<04:00,  5.87s/it]

[I 2025-12-02 02:13:51,451] Trial 10 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.0747994614527602, 'n_estimators': 240, 'subsample': 0.5524564770158626, 'colsample_bytree': 0.9063125139573407, 'min_child_weight': 8, 'gamma': 4.451167314445177, 'reg_alpha': 0.042978210200526, 'reg_lambda': 4.930801295735832e-05, 'max_delta_step': 2}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:  20%|██        | 10/50 [01:32<06:12,  9.32s/it]

[I 2025-12-02 02:14:09,170] Trial 11 finished with value: 0.4463562753036437 and parameters: {'max_depth': 5, 'learning_rate': 0.20261965277737362, 'n_estimators': 557, 'subsample': 0.5891767218295385, 'colsample_bytree': 0.6989093059401306, 'min_child_weight': 3, 'gamma': 1.246378533115926, 'reg_alpha': 0.016943955488852126, 'reg_lambda': 1.0861457817718565e-05, 'max_delta_step': 0}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:  22%|██▏       | 11/50 [01:37<05:16,  8.11s/it]

[I 2025-12-02 02:14:14,376] Trial 8 finished with value: 0.4919028340080972 and parameters: {'max_depth': 5, 'learning_rate': 0.0533351787836453, 'n_estimators': 1189, 'subsample': 0.8624590554098481, 'colsample_bytree': 0.7082820119317006, 'min_child_weight': 1, 'gamma': 0.451206870750549, 'reg_alpha': 5.329927384277779e-08, 'reg_lambda': 0.004989331659723135, 'max_delta_step': 3}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:  24%|██▍       | 12/50 [01:37<03:42,  5.86s/it]

[I 2025-12-02 02:14:14,862] Trial 6 finished with value: 0.48684210526315785 and parameters: {'max_depth': 4, 'learning_rate': 0.010444874954175978, 'n_estimators': 1231, 'subsample': 0.7982540440709429, 'colsample_bytree': 0.8969971358772899, 'min_child_weight': 4, 'gamma': 1.3226490943302478, 'reg_alpha': 6.414429670229529e-08, 'reg_lambda': 0.013004023853185557, 'max_delta_step': 2}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:  26%|██▌       | 13/50 [02:01<06:47, 11.02s/it]

[I 2025-12-02 02:14:38,114] Trial 12 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.1773412036886996, 'n_estimators': 1215, 'subsample': 0.9608110474334113, 'colsample_bytree': 0.5823174762468422, 'min_child_weight': 5, 'gamma': 0.942491032828604, 'reg_alpha': 7.565651214398788e-06, 'reg_lambda': 0.6524872518196605, 'max_delta_step': 10}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:  28%|██▊       | 14/50 [02:05<05:21,  8.92s/it]

[I 2025-12-02 02:14:42,089] Trial 13 finished with value: 0.46558704453441296 and parameters: {'max_depth': 8, 'learning_rate': 0.1243392536491352, 'n_estimators': 842, 'subsample': 0.7993092952770487, 'colsample_bytree': 0.5145522642599447, 'min_child_weight': 1, 'gamma': 0.01530323625057628, 'reg_alpha': 2.0964410615852258e-05, 'reg_lambda': 1.1722298309839691e-06, 'max_delta_step': 5}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:  30%|███       | 15/50 [02:14<05:16,  9.03s/it]

[I 2025-12-02 02:14:51,376] Trial 14 finished with value: 0.4392712550607287 and parameters: {'max_depth': 8, 'learning_rate': 0.09875617440190233, 'n_estimators': 916, 'subsample': 0.8106578570325612, 'colsample_bytree': 0.5119500239968523, 'min_child_weight': 1, 'gamma': 0.05426989420865336, 'reg_alpha': 1.6475808468504963e-05, 'reg_lambda': 4.6900988581413895e-07, 'max_delta_step': 3}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:  32%|███▏      | 16/50 [02:15<03:44,  6.60s/it]

[I 2025-12-02 02:14:52,279] Trial 15 finished with value: 0.46558704453441296 and parameters: {'max_depth': 8, 'learning_rate': 0.11981381282726143, 'n_estimators': 915, 'subsample': 0.8202808159012048, 'colsample_bytree': 0.5246741011917921, 'min_child_weight': 1, 'gamma': 0.025644214860690295, 'reg_alpha': 2.7549257516763603e-05, 'reg_lambda': 7.920103966056454e-07, 'max_delta_step': 5}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:  34%|███▍      | 17/50 [02:37<06:08, 11.17s/it]

[I 2025-12-02 02:15:14,155] Trial 16 finished with value: 0.5182186234817814 and parameters: {'max_depth': 8, 'learning_rate': 0.09791178616193476, 'n_estimators': 908, 'subsample': 0.8565677641169654, 'colsample_bytree': 0.5110526242338803, 'min_child_weight': 1, 'gamma': 0.1412051389893909, 'reg_alpha': 2.1135200708496657e-05, 'reg_lambda': 1.4461518153776613e-06, 'max_delta_step': 5}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:  36%|███▌      | 18/50 [02:43<05:10,  9.71s/it]

[I 2025-12-02 02:15:20,448] Trial 17 finished with value: 0.4726720647773279 and parameters: {'max_depth': 8, 'learning_rate': 0.03997045724566588, 'n_estimators': 960, 'subsample': 0.8641559413069094, 'colsample_bytree': 0.6339491014404764, 'min_child_weight': 1, 'gamma': 3.5691307047676273, 'reg_alpha': 0.00012373808380946273, 'reg_lambda': 9.154152194271289e-07, 'max_delta_step': 0}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:  38%|███▊      | 19/50 [02:43<03:36,  6.97s/it]

[I 2025-12-02 02:15:21,008] Trial 19 finished with value: 0.4726720647773279 and parameters: {'max_depth': 7, 'learning_rate': 0.042255132163907805, 'n_estimators': 727, 'subsample': 0.878804227586906, 'colsample_bytree': 0.6039351776831372, 'min_child_weight': 3, 'gamma': 3.360974006750571, 'reg_alpha': 5.821755684171337e-07, 'reg_lambda': 0.001618104443541912, 'max_delta_step': 0}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:  40%|████      | 20/50 [02:51<03:35,  7.20s/it]

[I 2025-12-02 02:15:28,747] Trial 18 finished with value: 0.4989878542510121 and parameters: {'max_depth': 7, 'learning_rate': 0.04566640648764272, 'n_estimators': 944, 'subsample': 0.859891499607337, 'colsample_bytree': 0.6272792898394594, 'min_child_weight': 2, 'gamma': 3.367823864754249, 'reg_alpha': 0.00022368151761653662, 'reg_lambda': 0.0025286444695829286, 'max_delta_step': 0}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:  42%|████▏     | 21/50 [02:56<03:06,  6.44s/it]

[I 2025-12-02 02:15:33,412] Trial 22 pruned.

Best trial: 4. Best value: 0.525304:  44%|████▍     | 22/50 [02:57<02:15,  4.86s/it]

[I 2025-12-02 02:15:34,570] Trial 23 pruned.

Best trial: 4. Best value: 0.525304:  46%|████▌     | 23/50 [03:06<02:42,  6.03s/it]

[I 2025-12-02 02:15:43,351] Trial 20 finished with value: 0.4726720647773279 and parameters: {'max_depth': 9, 'learning_rate': 0.15145025526021294, 'n_estimators': 735, 'subsample': 0.7035207778657737, 'colsample_bytree': 0.6038352773676045, 'min_child_weight': 3, 'gamma': 3.495504490789347, 'reg_alpha': 0.00029098685329246357, 'reg_lambda': 1.2525897681586924e-07, 'max_delta_step': 0}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:  48%|████▊     | 24/50 [03:11<02:32,  5.88s/it]

[I 2025-12-02 02:15:48,876] Trial 21 finished with value: 0.4726720647773279 and parameters: {'max_depth': 9, 'learning_rate': 0.1431631573801399, 'n_estimators': 709, 'subsample': 0.7097038811024344, 'colsample_bytree': 0.5969765741507406, 'min_child_weight': 3, 'gamma': 1.8931056677534452, 'reg_alpha': 9.243695231989289e-07, 'reg_lambda': 1.1043735668601855e-07, 'max_delta_step': 7}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.525304:  50%|█████     | 25/50 [03:36<04:45, 11.41s/it]

[I 2025-12-02 02:16:13,187] Trial 24 finished with value: 0.5182186234817814 and parameters: {'max_depth': 7, 'learning_rate': 0.019956806035025136, 'n_estimators': 1026, 'subsample': 0.7350403362642574, 'colsample_bytree': 0.6384657244100367, 'min_child_weight': 3, 'gamma': 3.7912170098000297, 'reg_alpha': 9.139101699872391e-07, 'reg_lambda': 0.0006013493146717286, 'max_delta_step': 1}. Best is trial 4 with value: 0.5253036437246963.

Best trial: 25. Best value: 0.537449:  52%|█████▏    | 26/50 [03:37<03:24,  8.53s/it]

[I 2025-12-02 02:16:14,997] Trial 25 finished with value: 0.5374493927125505 and parameters: {'max_depth': 7, 'learning_rate': 0.021643697213479942, 'n_estimators': 1047, 'subsample': 0.8861694058645382, 'colsample_bytree': 0.6643001226427829, 'min_child_weight': 3, 'gamma': 3.77810601903692, 'reg_alpha': 0.0003222663900619924, 'reg_lambda': 5.926977915636551e-06, 'max_delta_step': 1}. Best is trial 25 with value: 0.5374493927125505.

Best trial: 25. Best value: 0.537449:  54%|█████▍    | 27/50 [03:48<03:29,  9.09s/it]

[I 2025-12-02 02:16:25,384] Trial 26 finished with value: 0.5182186234817814 and parameters: {'max_depth': 7, 'learning_rate': 0.0226044523149735, 'n_estimators': 1067, 'subsample': 0.9112870557538266, 'colsample_bytree': 0.6462519055287119, 'min_child_weight': 2, 'gamma': 4.213898375341983, 'reg_alpha': 0.047021866893937135, 'reg_lambda': 5.644278876475917e-06, 'max_delta_step': 1}. Best is trial 25 with value: 0.5374493927125505.

Best trial: 25. Best value: 0.537449:  56%|█████▌    | 28/50 [03:51<02:39,  7.23s/it]

[I 2025-12-02 02:16:28,295] Trial 27 finished with value: 0.5182186234817814 and parameters: {'max_depth': 7, 'learning_rate': 0.020150302219924886, 'n_estimators': 1007, 'subsample': 0.9113452609807613, 'colsample_bytree': 0.6482841452674126, 'min_child_weight': 2, 'gamma': 3.9541595800170812, 'reg_alpha': 0.08208983757484059, 'reg_lambda': 6.642547858725268e-06, 'max_delta_step': 1}. Best is trial 25 with value: 0.5374493927125505.

Best trial: 25. Best value: 0.537449:  58%|█████▊    | 29/50 [04:10<03:47, 10.82s/it]

[I 2025-12-02 02:16:47,493] Trial 31 pruned.

Best trial: 25. Best value: 0.537449:  60%|██████    | 30/50 [04:19<03:22, 10.14s/it]

[I 2025-12-02 02:16:56,028] Trial 28 finished with value: 0.5374493927125505 and parameters: {'max_depth': 7, 'learning_rate': 0.019257455845997414, 'n_estimators': 1068, 'subsample': 0.7523912576021747, 'colsample_bytree': 0.6527084761487644, 'min_child_weight': 2, 'gamma': 4.06352609687402, 'reg_alpha': 2.0247807429592202e-06, 'reg_lambda': 7.51852716286962e-06, 'max_delta_step': 1}. Best is trial 25 with value: 0.5374493927125505.

Best trial: 25. Best value: 0.537449:  62%|██████▏   | 31/50 [04:19<02:16,  7.19s/it]

[I 2025-12-02 02:16:56,335] Trial 30 finished with value: 0.4149797570850202 and parameters: {'max_depth': 6, 'learning_rate': 0.06744502292790143, 'n_estimators': 803, 'subsample': 0.9955798527756322, 'colsample_bytree': 0.7563400787518301, 'min_child_weight': 2, 'gamma': 2.884410782695271, 'reg_alpha': 0.0014939970301431499, 'reg_lambda': 2.857735470120895e-06, 'max_delta_step': 4}. Best is trial 25 with value: 0.5374493927125505.

Best trial: 25. Best value: 0.537449:  64%|██████▍   | 32/50 [04:20<01:38,  5.46s/it]

[I 2025-12-02 02:16:57,766] Trial 29 finished with value: 0.4989878542510121 and parameters: {'max_depth': 6, 'learning_rate': 0.07147672097063246, 'n_estimators': 1088, 'subsample': 0.9103707874837172, 'colsample_bytree': 0.75108870871162, 'min_child_weight': 2, 'gamma': 4.0919569098843525, 'reg_alpha': 0.06088893247054219, 'reg_lambda': 5.107672552068887e-06, 'max_delta_step': 4}. Best is trial 25 with value: 0.5374493927125505.

Best trial: 25. Best value: 0.537449:  66%|██████▌   | 33/50 [04:24<01:23,  4.89s/it]

[I 2025-12-02 02:17:01,337] Trial 34 pruned.

Best trial: 25. Best value: 0.537449:  68%|██████▊   | 34/50 [04:25<01:01,  3.86s/it]

[I 2025-12-02 02:17:02,792] Trial 35 pruned.

Best trial: 25. Best value: 0.537449:  70%|███████   | 35/50 [04:28<00:54,  3.65s/it]

[I 2025-12-02 02:17:05,949] Trial 33 pruned.

Best trial: 25. Best value: 0.537449:  72%|███████▏  | 36/50 [04:32<00:48,  3.50s/it]

[I 2025-12-02 02:17:09,094] Trial 32 finished with value: 0.4726720647773279 and parameters: {'max_depth': 10, 'learning_rate': 0.014248064474867912, 'n_estimators': 507, 'subsample': 0.7555182441633914, 'colsample_bytree': 0.5404427647711927, 'min_child_weight': 2, 'gamma': 2.848128778822472, 'reg_alpha': 0.40237059073690584, 'reg_lambda': 4.051669250195574e-06, 'max_delta_step': 3}. Best is trial 25 with value: 0.5374493927125505.

Best trial: 25. Best value: 0.537449:  74%|███████▍  | 37/50 [04:36<00:49,  3.77s/it]

[I 2025-12-02 02:17:13,504] Trial 36 pruned.

Best trial: 25. Best value: 0.537449:  76%|███████▌  | 38/50 [04:40<00:46,  3.87s/it]

[I 2025-12-02 02:17:17,598] Trial 38 pruned.

Best trial: 25. Best value: 0.537449:  78%|███████▊  | 39/50 [04:43<00:39,  3.63s/it]

[I 2025-12-02 02:17:20,658] Trial 40 pruned.

Best trial: 25. Best value: 0.537449:  80%|████████  | 40/50 [04:43<00:26,  2.63s/it]

[I 2025-12-02 02:17:20,968] Trial 39 pruned.

Best trial: 25. Best value: 0.537449:  82%|████████▏ | 41/50 [04:50<00:35,  3.93s/it]

[I 2025-12-02 02:17:27,921] Trial 41 pruned.

Best trial: 25. Best value: 0.537449:  84%|████████▍ | 42/50 [04:53<00:29,  3.67s/it]

[I 2025-12-02 02:17:30,990] Trial 43 pruned.
[I 2025-12-02 02:17:30,998] Trial 42 pruned.

Best trial: 25. Best value: 0.537449:  88%|████████▊ | 44/50 [05:00<00:21,  3.51s/it]

[I 2025-12-02 02:17:37,623] Trial 44 pruned.

Best trial: 25. Best value: 0.537449:  90%|█████████ | 45/50 [05:21<00:39,  7.85s/it]

[I 2025-12-02 02:17:58,651] Trial 37 finished with value: 0.4797570850202429 and parameters: {'max_depth': 10, 'learning_rate': 0.01538323501073665, 'n_estimators': 1435, 'subsample': 0.663870241480686, 'colsample_bytree': 0.6771089551364758, 'min_child_weight': 2, 'gamma': 3.069669080891315, 'reg_alpha': 3.3013969393575655e-06, 'reg_lambda': 2.3489527635964165e-07, 'max_delta_step': 1}. Best is trial 25 with value: 0.5374493927125505.

Best trial: 25. Best value: 0.537449:  92%|█████████▏| 46/50 [05:34<00:36,  9.06s/it]

[I 2025-12-02 02:18:11,108] Trial 46 finished with value: 0.5182186234817814 and parameters: {'max_depth': 7, 'learning_rate': 0.01901462508437587, 'n_estimators': 1020, 'subsample': 0.7333941565810068, 'colsample_bytree': 0.5019484088487689, 'min_child_weight': 2, 'gamma': 3.671023328916288, 'reg_alpha': 1.6893256654890094e-07, 'reg_lambda': 0.0006202618606380514, 'max_delta_step': 1}. Best is trial 25 with value: 0.5374493927125505.

Best trial: 25. Best value: 0.537449:  94%|█████████▍| 47/50 [05:34<00:20,  6.75s/it]

[I 2025-12-02 02:18:11,677] Trial 45 finished with value: 0.5182186234817814 and parameters: {'max_depth': 7, 'learning_rate': 0.021219874389111507, 'n_estimators': 1045, 'subsample': 0.7422104256082116, 'colsample_bytree': 0.5037174715893712, 'min_child_weight': 2, 'gamma': 3.8139788245202513, 'reg_alpha': 2.1735078938656509e-07, 'reg_lambda': 0.0009852951663636552, 'max_delta_step': 1}. Best is trial 25 with value: 0.5374493927125505.

Best trial: 25. Best value: 0.537449:  96%|█████████▌| 48/50 [05:38<00:11,  5.91s/it]

[I 2025-12-02 02:18:15,422] Trial 47 finished with value: 0.5182186234817814 and parameters: {'max_depth': 5, 'learning_rate': 0.01849979498696423, 'n_estimators': 1005, 'subsample': 0.7372682585501303, 'colsample_bytree': 0.50387466782625, 'min_child_weight': 2, 'gamma': 4.293990587701066, 'reg_alpha': 1.6419851968234163e-07, 'reg_lambda': 5.982336844386084e-05, 'max_delta_step': 1}. Best is trial 25 with value: 0.5374493927125505.

Best trial: 25. Best value: 0.537449:  98%|█████████▊| 49/50 [05:51<00:07,  7.98s/it]

[I 2025-12-02 02:18:28,581] Trial 48 finished with value: 0.5060728744939271 and parameters: {'max_depth': 5, 'learning_rate': 0.01841883946177681, 'n_estimators': 1274, 'subsample': 0.7354001388844023, 'colsample_bytree': 0.80041252822735, 'min_child_weight': 1, 'gamma': 3.742289203526815, 'reg_alpha': 1.6942262641570216e-07, 'reg_lambda': 8.361729730866138e-05, 'max_delta_step': 8}. Best is trial 25 with value: 0.5374493927125505.

Best trial: 25. Best value: 0.537449: 100%|██████████| 50/50 [05:54<00:00,  7.10s/it]

[I 2025-12-02 02:18:31,835] Trial 49 finished with value: 0.4726720647773279 and parameters: {'max_depth': 5, 'learning_rate': 0.214715332941179, 'n_estimators': 1292, 'subsample': 0.7866836502531825, 'colsample_bytree': 0.7957420628010722, 'min_child_weight': 1, 'gamma': 4.334608872521367, 'reg_alpha': 2.258368659580049e-07, 'reg_lambda': 7.234995842234106e-05, 'max_delta_step': 6}. Best is trial 25 with value: 0.5374493927125505.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 02:18:34,889] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 45, Test size: 12
Using Leave-One-Out CV with 45 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.336032:   2%|▏         | 1/50 [00:09<07:55,  9.70s/it]

[I 2025-12-02 02:18:44,584] Trial 3 finished with value: 0.3360323886639676 and parameters: {'max_depth': 10, 'learning_rate': 0.2744234837056176, 'n_estimators': 222, 'subsample': 0.7966737711110559, 'colsample_bytree': 0.8151462660031148, 'min_child_weight': 5, 'gamma': 2.304232078057341, 'reg_alpha': 7.816840152924653e-07, 'reg_lambda': 0.00028016605570708113, 'max_delta_step': 5}. Best is trial 3 with value: 0.3360323886639676.

Best trial: 3. Best value: 0.336032:   4%|▍         | 2/50 [00:24<09:55, 12.41s/it]

[I 2025-12-02 02:18:58,886] Trial 1 finished with value: 0.23076923076923078 and parameters: {'max_depth': 7, 'learning_rate': 0.013694498066093653, 'n_estimators': 612, 'subsample': 0.710497979841094, 'colsample_bytree': 0.6848092435461242, 'min_child_weight': 4, 'gamma': 1.3656602420844237, 'reg_alpha': 1.4837871056179938e-06, 'reg_lambda': 0.0014825670761422912, 'max_delta_step': 9}. Best is trial 3 with value: 0.3360323886639676.

Best trial: 0. Best value: 0.525304:   6%|▌         | 3/50 [00:27<06:35,  8.41s/it]

[I 2025-12-02 02:19:02,529] Trial 0 finished with value: 0.5253036437246963 and parameters: {'max_depth': 5, 'learning_rate': 0.0427887101775013, 'n_estimators': 678, 'subsample': 0.9725319559135289, 'colsample_bytree': 0.5579869259040308, 'min_child_weight': 1, 'gamma': 4.514992977500567, 'reg_alpha': 0.40516062184049506, 'reg_lambda': 4.6632959347291274e-05, 'max_delta_step': 5}. Best is trial 0 with value: 0.5253036437246963.

Best trial: 4. Best value: 0.537449:   8%|▊         | 4/50 [00:39<07:36,  9.93s/it]

[I 2025-12-02 02:19:14,796] Trial 4 finished with value: 0.5374493927125505 and parameters: {'max_depth': 7, 'learning_rate': 0.09770493778913698, 'n_estimators': 756, 'subsample': 0.942876573450016, 'colsample_bytree': 0.735061697059047, 'min_child_weight': 4, 'gamma': 1.2453401890925841, 'reg_alpha': 0.07421818047829919, 'reg_lambda': 0.034262677051109344, 'max_delta_step': 4}. Best is trial 4 with value: 0.5374493927125505.

Best trial: 4. Best value: 0.537449:  10%|█         | 5/50 [00:44<06:03,  8.07s/it]

[I 2025-12-02 02:19:19,573] Trial 2 finished with value: 0.5253036437246963 and parameters: {'max_depth': 4, 'learning_rate': 0.1771850484995815, 'n_estimators': 1164, 'subsample': 0.5088385915372116, 'colsample_bytree': 0.6605449955765631, 'min_child_weight': 3, 'gamma': 3.1061810703761097, 'reg_alpha': 1.862046960550196e-07, 'reg_lambda': 0.8479704066391618, 'max_delta_step': 7}. Best is trial 4 with value: 0.5374493927125505.

Best trial: 4. Best value: 0.537449:  12%|█▏        | 6/50 [00:56<06:53,  9.39s/it]

[I 2025-12-02 02:19:31,523] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.011312378593059676, 'n_estimators': 821, 'subsample': 0.5909800111508482, 'colsample_bytree': 0.822588233167557, 'min_child_weight': 6, 'gamma': 4.141599360460495, 'reg_alpha': 0.0005013518079761375, 'reg_lambda': 0.017146686116057117, 'max_delta_step': 2}. Best is trial 4 with value: 0.5374493927125505.

Best trial: 4. Best value: 0.537449:  14%|█▍        | 7/50 [01:07<07:05,  9.90s/it]

[I 2025-12-02 02:19:42,469] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.07477403703807456, 'n_estimators': 696, 'subsample': 0.8660449374015395, 'colsample_bytree': 0.8192324200091654, 'min_child_weight': 9, 'gamma': 2.5384757698641334, 'reg_alpha': 5.748164736949371e-05, 'reg_lambda': 0.4630571960849507, 'max_delta_step': 4}. Best is trial 4 with value: 0.5374493927125505.

Best trial: 4. Best value: 0.537449:  16%|█▌        | 8/50 [01:10<05:23,  7.70s/it]

[I 2025-12-02 02:19:45,472] Trial 6 finished with value: 0.40384615384615385 and parameters: {'max_depth': 10, 'learning_rate': 0.013418822749096525, 'n_estimators': 1104, 'subsample': 0.6955068395777398, 'colsample_bytree': 0.9126941474869834, 'min_child_weight': 5, 'gamma': 2.122121745793642, 'reg_alpha': 0.9629088894125372, 'reg_lambda': 0.00038300244737763924, 'max_delta_step': 2}. Best is trial 4 with value: 0.5374493927125505.

Best trial: 9. Best value: 0.621457:  18%|█▊        | 9/50 [01:12<04:04,  5.97s/it]

[I 2025-12-02 02:19:47,643] Trial 9 finished with value: 0.6214574898785425 and parameters: {'max_depth': 7, 'learning_rate': 0.03710586487368541, 'n_estimators': 381, 'subsample': 0.7502195928528717, 'colsample_bytree': 0.8875553732721089, 'min_child_weight': 2, 'gamma': 3.2719034058694034, 'reg_alpha': 1.9576322069038485e-05, 'reg_lambda': 2.1798587603391047e-07, 'max_delta_step': 6}. Best is trial 9 with value: 0.6214574898785425.

Best trial: 9. Best value: 0.621457:  20%|██        | 10/50 [01:32<06:52, 10.32s/it]

[I 2025-12-02 02:20:07,697] Trial 10 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.016785516448499644, 'n_estimators': 639, 'subsample': 0.7303735467295462, 'colsample_bytree': 0.7101666937869083, 'min_child_weight': 10, 'gamma': 1.4263094707351354, 'reg_alpha': 6.681655747054791e-08, 'reg_lambda': 5.885036201409401e-06, 'max_delta_step': 3}. Best is trial 9 with value: 0.6214574898785425.

Best trial: 9. Best value: 0.621457:  22%|██▏       | 11/50 [01:36<05:24,  8.31s/it]

[I 2025-12-02 02:20:11,458] Trial 8 finished with value: 0.5566801619433198 and parameters: {'max_depth': 4, 'learning_rate': 0.24529634046763296, 'n_estimators': 1354, 'subsample': 0.5924403089272587, 'colsample_bytree': 0.6857167919250688, 'min_child_weight': 3, 'gamma': 2.1310624655934336, 'reg_alpha': 6.471906107082107e-06, 'reg_lambda': 0.00018800569946088807, 'max_delta_step': 0}. Best is trial 9 with value: 0.6214574898785425.

Best trial: 9. Best value: 0.621457:  24%|██▍       | 12/50 [01:39<04:09,  6.57s/it]

[I 2025-12-02 02:20:14,048] Trial 11 finished with value: 0.3269230769230769 and parameters: {'max_depth': 9, 'learning_rate': 0.12297848134869212, 'n_estimators': 742, 'subsample': 0.8221823848424661, 'colsample_bytree': 0.6128699574373024, 'min_child_weight': 6, 'gamma': 2.936762241779895, 'reg_alpha': 1.901476187205184e-08, 'reg_lambda': 5.961687113113982, 'max_delta_step': 4}. Best is trial 9 with value: 0.6214574898785425.

Best trial: 13. Best value: 0.654858:  26%|██▌       | 13/50 [01:44<03:51,  6.25s/it]

[I 2025-12-02 02:20:19,564] Trial 13 finished with value: 0.6548582995951417 and parameters: {'max_depth': 8, 'learning_rate': 0.03098722673940563, 'n_estimators': 252, 'subsample': 0.6096324970764051, 'colsample_bytree': 0.997557765118842, 'min_child_weight': 1, 'gamma': 3.5913024326243557, 'reg_alpha': 0.0007639375025955018, 'reg_lambda': 1.3677602755639373e-08, 'max_delta_step': 10}. Best is trial 13 with value: 0.6548582995951417.

Best trial: 13. Best value: 0.654858:  28%|██▊       | 14/50 [01:46<02:58,  4.95s/it]

[I 2025-12-02 02:20:21,510] Trial 12 finished with value: 0.6022267206477733 and parameters: {'max_depth': 7, 'learning_rate': 0.11990063324082108, 'n_estimators': 840, 'subsample': 0.8646282243754293, 'colsample_bytree': 0.9182014156285208, 'min_child_weight': 1, 'gamma': 2.0213862261342346, 'reg_alpha': 0.19349203648191968, 'reg_lambda': 0.01740373748165033, 'max_delta_step': 5}. Best is trial 13 with value: 0.6548582995951417.

Best trial: 13. Best value: 0.654858:  30%|███       | 15/50 [01:49<02:28,  4.25s/it]

[I 2025-12-02 02:20:24,138] Trial 17 pruned.

Best trial: 13. Best value: 0.654858:  32%|███▏      | 16/50 [01:56<02:50,  5.01s/it]

[I 2025-12-02 02:20:30,904] Trial 16 finished with value: 0.6093117408906883 and parameters: {'max_depth': 9, 'learning_rate': 0.03398148714741056, 'n_estimators': 233, 'subsample': 0.63218057552467, 'colsample_bytree': 0.9976025770613139, 'min_child_weight': 1, 'gamma': 3.7752282170607727, 'reg_alpha': 0.0034385023628360355, 'reg_lambda': 1.1102715976351536e-08, 'max_delta_step': 10}. Best is trial 13 with value: 0.6548582995951417.

Best trial: 13. Best value: 0.654858:  34%|███▍      | 17/50 [01:59<02:34,  4.67s/it]

[I 2025-12-02 02:20:34,780] Trial 19 pruned.

Best trial: 13. Best value: 0.654858:  36%|███▌      | 18/50 [02:03<02:21,  4.42s/it]

[I 2025-12-02 02:20:38,618] Trial 20 pruned.

Best trial: 13. Best value: 0.654858:  38%|███▊      | 19/50 [02:06<02:04,  4.01s/it]

[I 2025-12-02 02:20:41,658] Trial 18 finished with value: 0.6548582995951417 and parameters: {'max_depth': 8, 'learning_rate': 0.029074023378525854, 'n_estimators': 399, 'subsample': 0.6540411666069098, 'colsample_bytree': 0.9864548251356609, 'min_child_weight': 1, 'gamma': 3.5390230534339477, 'reg_alpha': 0.0065859103743619, 'reg_lambda': 1.0606026319358979e-08, 'max_delta_step': 8}. Best is trial 13 with value: 0.6548582995951417.

Best trial: 13. Best value: 0.654858:  40%|████      | 20/50 [02:07<01:31,  3.06s/it]

[I 2025-12-02 02:20:42,527] Trial 21 pruned.

Best trial: 13. Best value: 0.654858:  42%|████▏     | 21/50 [02:11<01:37,  3.37s/it]

[I 2025-12-02 02:20:46,610] Trial 22 pruned.

Best trial: 13. Best value: 0.654858:  44%|████▍     | 22/50 [02:14<01:33,  3.34s/it]

[I 2025-12-02 02:20:49,880] Trial 24 pruned.

Best trial: 13. Best value: 0.654858:  46%|████▌     | 23/50 [02:16<01:15,  2.81s/it]

[I 2025-12-02 02:20:51,446] Trial 23 pruned.

Best trial: 13. Best value: 0.654858:  48%|████▊     | 24/50 [02:19<01:16,  2.95s/it]

[I 2025-12-02 02:20:54,735] Trial 26 pruned.

Best trial: 13. Best value: 0.654858:  50%|█████     | 25/50 [02:25<01:31,  3.66s/it]

[I 2025-12-02 02:21:00,044] Trial 27 pruned.

Best trial: 13. Best value: 0.654858:  52%|█████▏    | 26/50 [02:29<01:35,  4.00s/it]

[I 2025-12-02 02:21:04,833] Trial 25 finished with value: 0.6022267206477733 and parameters: {'max_depth': 7, 'learning_rate': 0.03402388028267948, 'n_estimators': 326, 'subsample': 0.6809409713569136, 'colsample_bytree': 0.9650388855105438, 'min_child_weight': 1, 'gamma': 4.234323823233162, 'reg_alpha': 0.00045253650322349387, 'reg_lambda': 2.4746744098179348e-08, 'max_delta_step': 6}. Best is trial 13 with value: 0.6548582995951417.

Best trial: 13. Best value: 0.654858:  54%|█████▍    | 27/50 [02:33<01:25,  3.73s/it]

[I 2025-12-02 02:21:07,947] Trial 14 finished with value: 0.6477732793522267 and parameters: {'max_depth': 3, 'learning_rate': 0.03188451306709331, 'n_estimators': 1490, 'subsample': 0.623351290529386, 'colsample_bytree': 0.9645392934345214, 'min_child_weight': 1, 'gamma': 0.16080478755246563, 'reg_alpha': 0.00013885635425174697, 'reg_lambda': 1.0118721435740314e-08, 'max_delta_step': 0}. Best is trial 13 with value: 0.6548582995951417.

Best trial: 13. Best value: 0.654858:  56%|█████▌    | 28/50 [02:34<01:07,  3.05s/it]

[I 2025-12-02 02:21:09,415] Trial 15 finished with value: 0.590080971659919 and parameters: {'max_depth': 3, 'learning_rate': 0.034187567183180584, 'n_estimators': 1474, 'subsample': 0.6062261780339713, 'colsample_bytree': 0.9925538035115824, 'min_child_weight': 1, 'gamma': 0.28137067664975834, 'reg_alpha': 0.00016937947789071015, 'reg_lambda': 1.0958050599231595e-08, 'max_delta_step': 0}. Best is trial 13 with value: 0.6548582995951417.

Best trial: 13. Best value: 0.654858:  58%|█████▊    | 29/50 [02:35<00:50,  2.39s/it]

[I 2025-12-02 02:21:10,254] Trial 29 pruned.

Best trial: 13. Best value: 0.654858:  60%|██████    | 30/50 [02:43<01:23,  4.18s/it]

[I 2025-12-02 02:21:18,613] Trial 32 pruned.

Best trial: 13. Best value: 0.654858:  62%|██████▏   | 31/50 [02:45<01:04,  3.39s/it]

[I 2025-12-02 02:21:20,176] Trial 31 pruned.

Best trial: 13. Best value: 0.654858:  64%|██████▍   | 32/50 [02:50<01:12,  4.02s/it]

[I 2025-12-02 02:21:25,650] Trial 28 pruned.

Best trial: 13. Best value: 0.654858:  66%|██████▌   | 33/50 [02:53<01:03,  3.74s/it]

[I 2025-12-02 02:21:28,736] Trial 35 pruned.

Best trial: 34. Best value: 0.681174:  68%|██████▊   | 34/50 [02:59<01:11,  4.45s/it]

[I 2025-12-02 02:21:34,845] Trial 34 finished with value: 0.6811740890688258 and parameters: {'max_depth': 6, 'learning_rate': 0.044006532531876315, 'n_estimators': 322, 'subsample': 0.693482508064284, 'colsample_bytree': 0.8761520449383716, 'min_child_weight': 1, 'gamma': 2.583648567428564, 'reg_alpha': 2.5766196082655836e-05, 'reg_lambda': 1.315256084062034e-07, 'max_delta_step': 6}. Best is trial 34 with value: 0.6811740890688258.

Best trial: 34. Best value: 0.681174:  70%|███████   | 35/50 [03:02<00:58,  3.89s/it]

[I 2025-12-02 02:21:37,415] Trial 37 pruned.

Best trial: 34. Best value: 0.681174:  72%|███████▏  | 36/50 [03:06<00:54,  3.92s/it]

[I 2025-12-02 02:21:41,415] Trial 36 pruned.

Best trial: 34. Best value: 0.681174:  74%|███████▍  | 37/50 [03:09<00:45,  3.51s/it]

[I 2025-12-02 02:21:43,955] Trial 39 pruned.

Best trial: 34. Best value: 0.681174:  76%|███████▌  | 38/50 [03:16<00:55,  4.64s/it]

[I 2025-12-02 02:21:51,249] Trial 33 pruned.

Best trial: 34. Best value: 0.681174:  78%|███████▊  | 39/50 [03:20<00:48,  4.41s/it]

[I 2025-12-02 02:21:55,110] Trial 40 pruned.

Best trial: 34. Best value: 0.681174:  82%|████████▏ | 41/50 [03:24<00:27,  3.05s/it]

[I 2025-12-02 02:21:59,169] Trial 38 pruned.
[I 2025-12-02 02:21:59,299] Trial 30 finished with value: 0.6093117408906883 and parameters: {'max_depth': 3, 'learning_rate': 0.06561775717811133, 'n_estimators': 1367, 'subsample': 0.5499066121189933, 'colsample_bytree': 0.853228150486112, 'min_child_weight': 1, 'gamma': 0.7418351645725054, 'reg_alpha': 0.0024141862083512135, 'reg_lambda': 8.398826174243744e-07, 'max_delta_step': 0}. Best is trial 34 with value: 0.6811740890688258.

Best trial: 34. Best value: 0.681174:  84%|████████▍ | 42/50 [03:25<00:20,  2.54s/it]

[I 2025-12-02 02:22:00,657] Trial 42 pruned.

Best trial: 34. Best value: 0.681174:  86%|████████▌ | 43/50 [03:29<00:21,  3.03s/it]

[I 2025-12-02 02:22:04,825] Trial 45 pruned.

Best trial: 34. Best value: 0.681174:  88%|████████▊ | 44/50 [03:38<00:27,  4.65s/it]

[I 2025-12-02 02:22:13,260] Trial 46 pruned.

Best trial: 34. Best value: 0.681174:  90%|█████████ | 45/50 [03:40<00:19,  3.91s/it]

[I 2025-12-02 02:22:15,438] Trial 44 finished with value: 0.6477732793522267 and parameters: {'max_depth': 7, 'learning_rate': 0.08052992750621539, 'n_estimators': 389, 'subsample': 0.7092930743992698, 'colsample_bytree': 0.8988632967304084, 'min_child_weight': 2, 'gamma': 3.8604465463743765, 'reg_alpha': 6.6777946391966476e-06, 'reg_lambda': 8.977789610276723e-08, 'max_delta_step': 6}. Best is trial 34 with value: 0.6811740890688258.

Best trial: 34. Best value: 0.681174:  92%|█████████▏| 46/50 [03:46<00:17,  4.45s/it]

[I 2025-12-02 02:22:21,135] Trial 48 pruned.

Best trial: 34. Best value: 0.681174:  94%|█████████▍| 47/50 [03:51<00:13,  4.55s/it]

[I 2025-12-02 02:22:25,938] Trial 47 finished with value: 0.6285425101214575 and parameters: {'max_depth': 7, 'learning_rate': 0.01976215778465509, 'n_estimators': 264, 'subsample': 0.756164689935078, 'colsample_bytree': 0.803712394646398, 'min_child_weight': 2, 'gamma': 2.6624576981079313, 'reg_alpha': 0.00023203747712164814, 'reg_lambda': 2.422503476061362e-08, 'max_delta_step': 7}. Best is trial 34 with value: 0.6811740890688258.

Best trial: 34. Best value: 0.681174:  96%|█████████▌| 48/50 [03:52<00:06,  3.49s/it]

[I 2025-12-02 02:22:26,945] Trial 49 pruned.

Best trial: 34. Best value: 0.681174:  98%|█████████▊| 49/50 [04:00<00:04,  4.96s/it]

[I 2025-12-02 02:22:35,341] Trial 41 finished with value: 0.6163967611336032 and parameters: {'max_depth': 4, 'learning_rate': 0.09065329053959607, 'n_estimators': 1498, 'subsample': 0.9833488271922527, 'colsample_bytree': 0.8985203537599432, 'min_child_weight': 3, 'gamma': 1.7016337760005942, 'reg_alpha': 0.06423578642081584, 'reg_lambda': 0.0029593772371933583, 'max_delta_step': 3}. Best is trial 34 with value: 0.6811740890688258.

Best trial: 34. Best value: 0.681174: 100%|██████████| 50/50 [04:02<00:00,  4.84s/it]

[I 2025-12-02 02:22:36,894] Trial 43 finished with value: 0.5637651821862348 and parameters: {'max_depth': 9, 'learning_rate': 0.0751312573315782, 'n_estimators': 1487, 'subsample': 0.9777818406943882, 'colsample_bytree': 0.9024340601270213, 'min_child_weight': 4, 'gamma': 1.0466537337642836, 'reg_alpha': 3.9586148079318e-06, 'reg_lambda': 1.1763134037197433e-07, 'max_delta_step': 3}. Best is trial 34 with value: 0.6811740890688258.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.609312                0.700000      0.828571
1    19_1         loo       0.681174                0.485714      0.657143
2    15_1         loo       0.647773                0.442857      0.400000
3    17_1         loo       0.537449                0.242857      0.171429

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.529150          1.000000               0.4        50          45
1 -0.028571          0.571429               0.4        50          45
2 -0.119523          0.285714               0.6        50          45
3 -0.507093          0.285714               0.2        50          45

   test_size
0         12
1         12
2         12
3         12
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.609312                0.700000      0.828571
1    19_1         loo       0.681174                0.485714      0.657143
2    15_1         loo       0.647773                0.442857      0.400000
3    17_1         loo       0.537449                0.242857      0.171429

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.529150          1.000000               0.4        50          45
1 -0.028571          0.571429               0.4        50          45
2 -0.119523          0.285714               0.6        50          45
3 -0.507093          0.285714               0.2        50          45

   test_size
0         12
1         12
2         12
3         12

## MCI-PD vs HC -> OPTUNA + XGB

In [ ]:
datasets = task_hf_compensated_comb_emb_lbl_pd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_pd_hc_{CV_STRATEGY}_tasks/xgb_results_handcrafted_comb_emb_pd_hc_extended_{CV_STRATEGY}_tasks",
    split_param= "diagnosis_y",
)
print(summary)

[I 2025-12-02 02:22:41,317] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.638158:   2%|▏         | 1/50 [00:38<31:15, 38.28s/it]

[I 2025-12-02 02:23:19,594] Trial 0 finished with value: 0.638157894736842 and parameters: {'max_depth': 4, 'learning_rate': 0.012519271770077901, 'n_estimators': 345, 'subsample': 0.687352496979583, 'colsample_bytree': 0.81733584991158, 'min_child_weight': 4, 'gamma': 2.3472270681550986, 'reg_alpha': 0.09665473279402156, 'reg_lambda': 0.04016594829220242, 'max_delta_step': 7}. Best is trial 0 with value: 0.638157894736842.

Best trial: 0. Best value: 0.638158:   4%|▍         | 2/50 [00:41<13:57, 17.45s/it]

[I 2025-12-02 02:23:22,452] Trial 1 finished with value: 0.638157894736842 and parameters: {'max_depth': 4, 'learning_rate': 0.026773059238484196, 'n_estimators': 608, 'subsample': 0.8986351823176701, 'colsample_bytree': 0.5575678634809274, 'min_child_weight': 4, 'gamma': 2.309822027915624, 'reg_alpha': 1.2790194574105617e-06, 'reg_lambda': 0.3688051012644705, 'max_delta_step': 9}. Best is trial 0 with value: 0.638157894736842.

Best trial: 2. Best value: 0.690789:   6%|▌         | 3/50 [00:47<09:36, 12.26s/it]

[I 2025-12-02 02:23:28,552] Trial 2 finished with value: 0.6907894736842105 and parameters: {'max_depth': 3, 'learning_rate': 0.08857323823532809, 'n_estimators': 954, 'subsample': 0.9153561381389081, 'colsample_bytree': 0.749636856990775, 'min_child_weight': 7, 'gamma': 0.5706886845858039, 'reg_alpha': 0.6855073646480324, 'reg_lambda': 0.10309018189748835, 'max_delta_step': 9}. Best is trial 2 with value: 0.6907894736842105.

Best trial: 2. Best value: 0.690789:   8%|▊         | 4/50 [01:06<11:26, 14.91s/it]

[I 2025-12-02 02:23:47,525] Trial 3 finished with value: 0.325 and parameters: {'max_depth': 6, 'learning_rate': 0.018318011842127755, 'n_estimators': 1412, 'subsample': 0.6130122776947732, 'colsample_bytree': 0.8173863817012226, 'min_child_weight': 8, 'gamma': 1.5340160887425784, 'reg_alpha': 0.0002962379936859109, 'reg_lambda': 0.018633942308291487, 'max_delta_step': 6}. Best is trial 2 with value: 0.6907894736842105.

Best trial: 2. Best value: 0.690789:  10%|█         | 5/50 [01:16<09:50, 13.13s/it]

[I 2025-12-02 02:23:57,488] Trial 5 finished with value: 0.325 and parameters: {'max_depth': 6, 'learning_rate': 0.011208740585417959, 'n_estimators': 697, 'subsample': 0.8027546861334004, 'colsample_bytree': 0.9517512597034876, 'min_child_weight': 9, 'gamma': 1.2622840808619062, 'reg_alpha': 0.001309746062703493, 'reg_lambda': 3.242861968192842, 'max_delta_step': 0}. Best is trial 2 with value: 0.6907894736842105.

Best trial: 2. Best value: 0.690789:  12%|█▏        | 6/50 [01:34<10:49, 14.77s/it]

[I 2025-12-02 02:24:15,447] Trial 8 finished with value: 0.45 and parameters: {'max_depth': 8, 'learning_rate': 0.010456472870499259, 'n_estimators': 393, 'subsample': 0.6747853977188863, 'colsample_bytree': 0.6005952658199456, 'min_child_weight': 9, 'gamma': 0.1299478218566391, 'reg_alpha': 0.00025974619663526167, 'reg_lambda': 1.929300153513727e-07, 'max_delta_step': 1}. Best is trial 2 with value: 0.6907894736842105.

Best trial: 7. Best value: 0.728289:  14%|█▍        | 7/50 [01:46<09:59, 13.93s/it]

[I 2025-12-02 02:24:27,652] Trial 7 finished with value: 0.7282894736842105 and parameters: {'max_depth': 6, 'learning_rate': 0.06246078062499146, 'n_estimators': 902, 'subsample': 0.5471754847245962, 'colsample_bytree': 0.533851583450353, 'min_child_weight': 5, 'gamma': 3.781457063573972, 'reg_alpha': 0.13751844483045506, 'reg_lambda': 1.985043529445631e-08, 'max_delta_step': 6}. Best is trial 7 with value: 0.7282894736842105.

Best trial: 7. Best value: 0.728289:  16%|█▌        | 8/50 [02:01<09:58, 14.26s/it]

[I 2025-12-02 02:24:42,620] Trial 10 finished with value: 0.6671052631578948 and parameters: {'max_depth': 8, 'learning_rate': 0.0627648465899564, 'n_estimators': 239, 'subsample': 0.8837490177896927, 'colsample_bytree': 0.886290385159922, 'min_child_weight': 9, 'gamma': 4.5929346824062804, 'reg_alpha': 0.0010548006860195483, 'reg_lambda': 0.030680712592787974, 'max_delta_step': 1}. Best is trial 7 with value: 0.7282894736842105.

Best trial: 7. Best value: 0.728289:  18%|█▊        | 9/50 [02:08<08:15, 12.08s/it]

[I 2025-12-02 02:24:49,897] Trial 9 finished with value: 0.3125 and parameters: {'max_depth': 3, 'learning_rate': 0.2795221456176417, 'n_estimators': 696, 'subsample': 0.5452319034564466, 'colsample_bytree': 0.9722163316108796, 'min_child_weight': 9, 'gamma': 2.7569651762913603, 'reg_alpha': 1.7882546996355487e-07, 'reg_lambda': 0.0015343184437338598, 'max_delta_step': 7}. Best is trial 7 with value: 0.7282894736842105.

Best trial: 7. Best value: 0.728289:  20%|██        | 10/50 [02:26<09:17, 13.94s/it]

[I 2025-12-02 02:25:07,994] Trial 4 finished with value: 0.6118421052631579 and parameters: {'max_depth': 5, 'learning_rate': 0.010829595841944931, 'n_estimators': 925, 'subsample': 0.6602887408505648, 'colsample_bytree': 0.9027585293334124, 'min_child_weight': 2, 'gamma': 2.6155987259718554, 'reg_alpha': 0.720026749914743, 'reg_lambda': 0.00866383565725228, 'max_delta_step': 2}. Best is trial 7 with value: 0.7282894736842105.

Best trial: 7. Best value: 0.728289:  22%|██▏       | 11/50 [02:29<06:47, 10.44s/it]

[I 2025-12-02 02:25:10,513] Trial 12 pruned.

Best trial: 7. Best value: 0.728289:  24%|██▍       | 12/50 [02:46<07:52, 12.42s/it]

[I 2025-12-02 02:25:27,467] Trial 6 finished with value: 0.6769736842105263 and parameters: {'max_depth': 5, 'learning_rate': 0.06639519440920402, 'n_estimators': 1477, 'subsample': 0.520842814079072, 'colsample_bytree': 0.8123091595148063, 'min_child_weight': 1, 'gamma': 4.0398291304332075, 'reg_alpha': 0.036884748907772366, 'reg_lambda': 0.6132801217118319, 'max_delta_step': 6}. Best is trial 7 with value: 0.7282894736842105.

Best trial: 7. Best value: 0.728289:  26%|██▌       | 13/50 [02:52<06:30, 10.55s/it]

[I 2025-12-02 02:25:33,707] Trial 11 finished with value: 0.6657894736842105 and parameters: {'max_depth': 5, 'learning_rate': 0.045472483645651596, 'n_estimators': 1027, 'subsample': 0.8635467435387327, 'colsample_bytree': 0.7171464695331863, 'min_child_weight': 8, 'gamma': 3.7351892164370213, 'reg_alpha': 6.8409325632281925, 'reg_lambda': 2.177993935066247e-06, 'max_delta_step': 7}. Best is trial 7 with value: 0.7282894736842105.

Best trial: 7. Best value: 0.728289:  28%|██▊       | 14/50 [03:03<06:25, 10.72s/it]

[I 2025-12-02 02:25:44,819] Trial 16 pruned.

Best trial: 14. Best value: 0.730921:  30%|███       | 15/50 [03:31<09:16, 15.89s/it]

[I 2025-12-02 02:26:12,687] Trial 14 finished with value: 0.7309210526315789 and parameters: {'max_depth': 10, 'learning_rate': 0.08641281264120791, 'n_estimators': 1058, 'subsample': 0.9750480102515677, 'colsample_bytree': 0.6537648871510632, 'min_child_weight': 6, 'gamma': 4.203064777558032, 'reg_alpha': 7.2854427171291665, 'reg_lambda': 1.8426664280111492e-08, 'max_delta_step': 4}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  32%|███▏      | 16/50 [03:39<07:44, 13.66s/it]

[I 2025-12-02 02:26:21,187] Trial 18 pruned.

Best trial: 14. Best value: 0.730921:  34%|███▍      | 17/50 [03:49<06:47, 12.36s/it]

[I 2025-12-02 02:26:30,503] Trial 13 finished with value: 0.6894736842105263 and parameters: {'max_depth': 10, 'learning_rate': 0.13606201729124145, 'n_estimators': 1252, 'subsample': 0.5221086055452065, 'colsample_bytree': 0.6590127220853779, 'min_child_weight': 1, 'gamma': 4.453106051349813, 'reg_alpha': 0.02107940361523117, 'reg_lambda': 7.816011811393484e-08, 'max_delta_step': 4}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  36%|███▌      | 18/50 [03:53<05:22, 10.08s/it]

[I 2025-12-02 02:26:35,287] Trial 19 pruned.

Best trial: 14. Best value: 0.730921:  38%|███▊      | 19/50 [03:57<04:10,  8.09s/it]

[I 2025-12-02 02:26:38,722] Trial 17 finished with value: 0.638157894736842 and parameters: {'max_depth': 8, 'learning_rate': 0.10719230818190616, 'n_estimators': 1194, 'subsample': 0.7962744731181179, 'colsample_bytree': 0.500156297066831, 'min_child_weight': 6, 'gamma': 1.149183262552772, 'reg_alpha': 0.008448438231925157, 'reg_lambda': 0.0002575532966212912, 'max_delta_step': 4}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  40%|████      | 20/50 [03:58<03:03,  6.13s/it]

[I 2025-12-02 02:26:40,278] Trial 15 finished with value: 0.7309210526315789 and parameters: {'max_depth': 10, 'learning_rate': 0.12128375165155389, 'n_estimators': 1125, 'subsample': 0.9714941757318658, 'colsample_bytree': 0.6931199054994137, 'min_child_weight': 6, 'gamma': 0.12857283929192248, 'reg_alpha': 8.513929589920997, 'reg_lambda': 1.991672079076248e-08, 'max_delta_step': 4}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  42%|████▏     | 21/50 [03:59<02:13,  4.59s/it]

[I 2025-12-02 02:26:41,280] Trial 20 pruned.

Best trial: 14. Best value: 0.730921:  44%|████▍     | 22/50 [04:10<02:55,  6.27s/it]

[I 2025-12-02 02:26:51,461] Trial 24 pruned.

Best trial: 14. Best value: 0.730921:  46%|████▌     | 23/50 [04:16<02:52,  6.39s/it]

[I 2025-12-02 02:26:58,153] Trial 25 pruned.

Best trial: 14. Best value: 0.730921:  48%|████▊     | 24/50 [04:26<03:13,  7.44s/it]

[I 2025-12-02 02:27:08,026] Trial 26 pruned.

Best trial: 14. Best value: 0.730921:  50%|█████     | 25/50 [04:30<02:39,  6.38s/it]

[I 2025-12-02 02:27:11,943] Trial 21 finished with value: 0.6394736842105263 and parameters: {'max_depth': 7, 'learning_rate': 0.0969881376511376, 'n_estimators': 814, 'subsample': 0.6180737854824224, 'colsample_bytree': 0.500063022500707, 'min_child_weight': 6, 'gamma': 3.2647306822987963, 'reg_alpha': 2.076657121546087e-05, 'reg_lambda': 1.6041150207569644e-06, 'max_delta_step': 5}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  52%|█████▏    | 26/50 [04:35<02:23,  5.98s/it]

[I 2025-12-02 02:27:16,987] Trial 22 finished with value: 0.6493421052631578 and parameters: {'max_depth': 7, 'learning_rate': 0.22380259955093976, 'n_estimators': 845, 'subsample': 0.5915519973957746, 'colsample_bytree': 0.570777025836689, 'min_child_weight': 5, 'gamma': 3.2661923837090936, 'reg_alpha': 3.102644400385377e-05, 'reg_lambda': 1.1738435671142184e-06, 'max_delta_step': 5}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  54%|█████▍    | 27/50 [04:47<03:00,  7.86s/it]

[I 2025-12-02 02:27:29,243] Trial 29 pruned.

Best trial: 14. Best value: 0.730921:  56%|█████▌    | 28/50 [04:48<02:04,  5.67s/it]

[I 2025-12-02 02:27:29,791] Trial 23 finished with value: 0.6532894736842105 and parameters: {'max_depth': 9, 'learning_rate': 0.2189750677740148, 'n_estimators': 1064, 'subsample': 0.9480678012523818, 'colsample_bytree': 0.6969933920686442, 'min_child_weight': 7, 'gamma': 3.236765364025075, 'reg_alpha': 1.6121003065823484e-05, 'reg_lambda': 1.9007153460872868e-06, 'max_delta_step': 2}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  58%|█████▊    | 29/50 [05:14<04:08, 11.84s/it]

[I 2025-12-02 02:27:56,035] Trial 27 finished with value: 0.6894736842105263 and parameters: {'max_depth': 9, 'learning_rate': 0.08069109663238605, 'n_estimators': 1019, 'subsample': 0.931698289752032, 'colsample_bytree': 0.5613230033841354, 'min_child_weight': 5, 'gamma': 3.979877697008763, 'reg_alpha': 0.9784228595547955, 'reg_lambda': 1.0580106024168497e-08, 'max_delta_step': 3}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  60%|██████    | 30/50 [05:18<03:10,  9.54s/it]

[I 2025-12-02 02:28:00,203] Trial 28 finished with value: 0.6506578947368421 and parameters: {'max_depth': 9, 'learning_rate': 0.18421326594251497, 'n_estimators': 1076, 'subsample': 0.9444493067380194, 'colsample_bytree': 0.5762495191939263, 'min_child_weight': 5, 'gamma': 3.979795681947298, 'reg_alpha': 1.2921427488433297, 'reg_lambda': 5.335299831559727e-08, 'max_delta_step': 3}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  62%|██████▏   | 31/50 [05:29<03:06,  9.79s/it]

[I 2025-12-02 02:28:10,581] Trial 30 finished with value: 0.638157894736842 and parameters: {'max_depth': 9, 'learning_rate': 0.12420916793694566, 'n_estimators': 942, 'subsample': 0.7320282163893056, 'colsample_bytree': 0.6425680921540677, 'min_child_weight': 6, 'gamma': 3.854109806609593, 'reg_alpha': 0.19001732560995413, 'reg_lambda': 1.7817128823506123e-07, 'max_delta_step': 8}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  64%|██████▍   | 32/50 [05:45<03:30, 11.68s/it]

[I 2025-12-02 02:28:26,678] Trial 31 finished with value: 0.7032894736842106 and parameters: {'max_depth': 10, 'learning_rate': 0.11271178020635594, 'n_estimators': 1316, 'subsample': 0.8363709300512235, 'colsample_bytree': 0.6406992474351373, 'min_child_weight': 6, 'gamma': 3.785266478330713, 'reg_alpha': 0.14901986623566987, 'reg_lambda': 1.4646231278472483e-07, 'max_delta_step': 8}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  66%|██████▌   | 33/50 [06:12<04:36, 16.24s/it]

[I 2025-12-02 02:28:53,561] Trial 34 finished with value: 0.6519736842105264 and parameters: {'max_depth': 3, 'learning_rate': 0.10068159447573562, 'n_estimators': 955, 'subsample': 0.9164383052479338, 'colsample_bytree': 0.7857836263342526, 'min_child_weight': 7, 'gamma': 0.5197452263555659, 'reg_alpha': 0.11279387935315442, 'reg_lambda': 0.00036982085672394074, 'max_delta_step': 8}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  68%|██████▊   | 34/50 [06:17<03:29, 13.08s/it]

[I 2025-12-02 02:28:59,254] Trial 33 finished with value: 0.638157894736842 and parameters: {'max_depth': 10, 'learning_rate': 0.1250749325945871, 'n_estimators': 1333, 'subsample': 0.7193017572879667, 'colsample_bytree': 0.6430799610809231, 'min_child_weight': 4, 'gamma': 2.1537542567140324, 'reg_alpha': 0.23259344005865668, 'reg_lambda': 8.440572883164555e-05, 'max_delta_step': 8}. Best is trial 14 with value: 0.7309210526315789.
[I 2025-12-02 02:28:59,268] Trial 32 finished with value: 0.6506578947368421 and parameters: {'max_depth': 10, 'learning_rate': 0.11522677256564881, 'n_estimators': 1349, 'subsample': 0.7229264746859367, 'colsample_bytree': 0.800356490008437, 'min_child_weight': 3, 'gamma': 2.061382268487454, 'reg_alpha': 0.171988505746964, 'reg_lambda': 1.9077695313898673e-07, 'max_delta_step': 6}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  72%|███████▏  | 36/50 [06:23<01:56,  8.32s/it]

[I 2025-12-02 02:29:04,770] Trial 36 pruned.

Best trial: 14. Best value: 0.730921:  74%|███████▍  | 37/50 [06:40<02:17, 10.60s/it]

[I 2025-12-02 02:29:22,299] Trial 37 finished with value: 0.6782894736842104 and parameters: {'max_depth': 4, 'learning_rate': 0.05953313015535696, 'n_estimators': 463, 'subsample': 0.842510180205702, 'colsample_bytree': 0.5348333008711537, 'min_child_weight': 8, 'gamma': 4.31792734843345, 'reg_alpha': 2.7110564097974867, 'reg_lambda': 3.7848348613847167e-08, 'max_delta_step': 9}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  76%|███████▌  | 38/50 [06:48<01:57,  9.76s/it]

[I 2025-12-02 02:29:29,707] Trial 35 finished with value: 0.638157894736842 and parameters: {'max_depth': 10, 'learning_rate': 0.05926376650900355, 'n_estimators': 1362, 'subsample': 0.8336760599131408, 'colsample_bytree': 0.629722838131566, 'min_child_weight': 4, 'gamma': 2.230607697989014, 'reg_alpha': 0.09464962905925019, 'reg_lambda': 3.3312678315192573e-07, 'max_delta_step': 8}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  78%|███████▊  | 39/50 [07:22<03:00, 16.37s/it]

[I 2025-12-02 02:30:03,746] Trial 38 finished with value: 0.7184210526315788 and parameters: {'max_depth': 4, 'learning_rate': 0.15989299008829183, 'n_estimators': 1478, 'subsample': 0.8435181986520817, 'colsample_bytree': 0.7378273708115962, 'min_child_weight': 8, 'gamma': 4.257208352777008, 'reg_alpha': 2.7692111804457213, 'reg_lambda': 4.2709684386652507e-07, 'max_delta_step': 9}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  80%|████████  | 40/50 [07:28<02:15, 13.56s/it]

[I 2025-12-02 02:30:10,067] Trial 39 finished with value: 0.6657894736842105 and parameters: {'max_depth': 10, 'learning_rate': 0.15693927726331627, 'n_estimators': 1489, 'subsample': 0.8942739263970945, 'colsample_bytree': 0.7323173865756757, 'min_child_weight': 6, 'gamma': 2.922738237758258, 'reg_alpha': 1.9853291619880569, 'reg_lambda': 1.9654282355906938e-08, 'max_delta_step': 7}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  82%|████████▏ | 41/50 [07:35<01:43, 11.48s/it]

[I 2025-12-02 02:30:16,363] Trial 42 pruned.

Best trial: 14. Best value: 0.730921:  84%|████████▍ | 42/50 [07:42<01:22, 10.32s/it]

[I 2025-12-02 02:30:23,850] Trial 43 pruned.

Best trial: 14. Best value: 0.730921:  86%|████████▌ | 43/50 [07:52<01:10, 10.10s/it]

[I 2025-12-02 02:30:33,408] Trial 40 finished with value: 0.6519736842105264 and parameters: {'max_depth': 6, 'learning_rate': 0.0251317440701341, 'n_estimators': 1417, 'subsample': 0.8912486328923375, 'colsample_bytree': 0.7660307140078378, 'min_child_weight': 6, 'gamma': 0.9880549227439963, 'reg_alpha': 1.544301349605648e-08, 'reg_lambda': 4.103840973941059e-07, 'max_delta_step': 7}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  88%|████████▊ | 44/50 [07:56<00:49,  8.29s/it]

[I 2025-12-02 02:30:37,358] Trial 41 finished with value: 0.6644736842105263 and parameters: {'max_depth': 6, 'learning_rate': 0.1614701876177419, 'n_estimators': 1494, 'subsample': 0.8847683277470981, 'colsample_bytree': 0.7667226901447809, 'min_child_weight': 6, 'gamma': 3.608559864216689, 'reg_alpha': 0.03748612719159608, 'reg_lambda': 6.663235992745439e-06, 'max_delta_step': 6}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  90%|█████████ | 45/50 [08:00<00:36,  7.24s/it]

[I 2025-12-02 02:30:42,125] Trial 46 pruned.

Best trial: 14. Best value: 0.730921:  92%|█████████▏| 46/50 [08:34<01:00, 15.06s/it]

[I 2025-12-02 02:31:15,637] Trial 45 finished with value: 0.6519736842105264 and parameters: {'max_depth': 5, 'learning_rate': 0.09112206416178155, 'n_estimators': 1129, 'subsample': 0.8063299600179047, 'colsample_bytree': 0.7664214452381296, 'min_child_weight': 6, 'gamma': 4.093802335204006, 'reg_alpha': 0.5000664321216082, 'reg_lambda': 8.609308845785986e-08, 'max_delta_step': 6}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  94%|█████████▍| 47/50 [08:34<00:32, 10.68s/it]

[I 2025-12-02 02:31:16,023] Trial 48 finished with value: 0.6519736842105264 and parameters: {'max_depth': 3, 'learning_rate': 0.07238886565678584, 'n_estimators': 743, 'subsample': 0.7594448964336726, 'colsample_bytree': 0.7268865072609755, 'min_child_weight': 7, 'gamma': 2.4838051351468646, 'reg_alpha': 0.35772110619978076, 'reg_lambda': 1.0964846685985214e-07, 'max_delta_step': 9}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  96%|█████████▌| 48/50 [08:36<00:16,  8.03s/it]

[I 2025-12-02 02:31:17,813] Trial 44 finished with value: 0.6769736842105263 and parameters: {'max_depth': 5, 'learning_rate': 0.07675111104793418, 'n_estimators': 1400, 'subsample': 0.7977719607328068, 'colsample_bytree': 0.5918184574030468, 'min_child_weight': 6, 'gamma': 3.6606169019115953, 'reg_alpha': 0.4548350078520435, 'reg_lambda': 7.73633367380134e-08, 'max_delta_step': 6}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921:  98%|█████████▊| 49/50 [08:43<00:07,  7.87s/it]

[I 2025-12-02 02:31:25,306] Trial 47 finished with value: 0.6519736842105264 and parameters: {'max_depth': 5, 'learning_rate': 0.072004717259677, 'n_estimators': 1145, 'subsample': 0.7680770214203995, 'colsample_bytree': 0.5990756484736768, 'min_child_weight': 7, 'gamma': 4.1736289538282945, 'reg_alpha': 0.48048097839372467, 'reg_lambda': 1.125103112344292e-07, 'max_delta_step': 9}. Best is trial 14 with value: 0.7309210526315789.

Best trial: 14. Best value: 0.730921: 100%|██████████| 50/50 [09:03<00:00, 10.88s/it]

[I 2025-12-02 02:31:45,106] Trial 49 finished with value: 0.7032894736842106 and parameters: {'max_depth': 3, 'learning_rate': 0.0730540772832029, 'n_estimators': 901, 'subsample': 0.693176240442021, 'colsample_bytree': 0.6829897899323661, 'min_child_weight': 7, 'gamma': 2.5739836178640934, 'reg_alpha': 0.02961476431418185, 'reg_lambda': 9.396899542211193e-08, 'max_delta_step': 9}. Best is trial 14 with value: 0.7309210526315789.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 02:31:48,405] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.61104:   2%|▏         | 1/50 [00:38<31:35, 38.68s/it]

[I 2025-12-02 02:32:27,081] Trial 1 finished with value: 0.6110397946084724 and parameters: {'max_depth': 7, 'learning_rate': 0.10119632928871387, 'n_estimators': 538, 'subsample': 0.7929438793730607, 'colsample_bytree': 0.5452651002425137, 'min_child_weight': 2, 'gamma': 0.3146119562717692, 'reg_alpha': 0.3106238201749384, 'reg_lambda': 0.4254648770031561, 'max_delta_step': 3}. Best is trial 1 with value: 0.6110397946084724.

Best trial: 3. Best value: 0.663671:   4%|▍         | 2/50 [00:43<15:11, 18.99s/it]

[I 2025-12-02 02:32:32,292] Trial 3 finished with value: 0.6636713735558408 and parameters: {'max_depth': 4, 'learning_rate': 0.015427466760229682, 'n_estimators': 468, 'subsample': 0.69527958300561, 'colsample_bytree': 0.5746854075677114, 'min_child_weight': 4, 'gamma': 4.400290695390327, 'reg_alpha': 0.007734091752677496, 'reg_lambda': 1.7018753690686101, 'max_delta_step': 10}. Best is trial 3 with value: 0.6636713735558408.

Best trial: 3. Best value: 0.663671:   6%|▌         | 3/50 [01:08<16:57, 21.65s/it]

[I 2025-12-02 02:32:57,105] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.07236050289461818, 'n_estimators': 1487, 'subsample': 0.7477375265634723, 'colsample_bytree': 0.655537039894282, 'min_child_weight': 10, 'gamma': 4.331999757083452, 'reg_alpha': 7.397828856243469, 'reg_lambda': 1.831148073593035e-05, 'max_delta_step': 8}. Best is trial 3 with value: 0.6636713735558408.

Best trial: 3. Best value: 0.663671:   8%|▊         | 4/50 [01:25<15:04, 19.67s/it]

[I 2025-12-02 02:33:13,727] Trial 4 finished with value: 0.42105263157894735 and parameters: {'max_depth': 9, 'learning_rate': 0.15630801215340512, 'n_estimators': 995, 'subsample': 0.7332650533033325, 'colsample_bytree': 0.6960128933666972, 'min_child_weight': 10, 'gamma': 1.1116957583594866, 'reg_alpha': 2.412817969755941e-05, 'reg_lambda': 1.3898070391232624e-08, 'max_delta_step': 2}. Best is trial 3 with value: 0.6636713735558408.

Best trial: 3. Best value: 0.663671:  10%|█         | 5/50 [01:27<10:06, 13.47s/it]

[I 2025-12-02 02:33:16,214] Trial 0 finished with value: 0.6495507060333761 and parameters: {'max_depth': 3, 'learning_rate': 0.034125686165029125, 'n_estimators': 1437, 'subsample': 0.7718953890712903, 'colsample_bytree': 0.7306441337260872, 'min_child_weight': 3, 'gamma': 1.263632478916158, 'reg_alpha': 3.106539053770041e-05, 'reg_lambda': 0.08650668274282772, 'max_delta_step': 3}. Best is trial 3 with value: 0.6636713735558408.

Best trial: 5. Best value: 0.689987:  12%|█▏        | 6/50 [01:29<06:57,  9.50s/it]

[I 2025-12-02 02:33:17,994] Trial 5 finished with value: 0.689987163029525 and parameters: {'max_depth': 7, 'learning_rate': 0.011202630641796687, 'n_estimators': 411, 'subsample': 0.9987160297122076, 'colsample_bytree': 0.6425712033709967, 'min_child_weight': 6, 'gamma': 0.7736159632864997, 'reg_alpha': 0.3382481544127228, 'reg_lambda': 0.026431633710606285, 'max_delta_step': 8}. Best is trial 5 with value: 0.689987163029525.

Best trial: 7. Best value: 0.691913:  14%|█▍        | 7/50 [01:46<08:28, 11.82s/it]

[I 2025-12-02 02:33:34,590] Trial 7 finished with value: 0.6919127086007703 and parameters: {'max_depth': 9, 'learning_rate': 0.01654598007929558, 'n_estimators': 273, 'subsample': 0.691423924482276, 'colsample_bytree': 0.5144902789682005, 'min_child_weight': 7, 'gamma': 3.1839812674716246, 'reg_alpha': 3.057510127719065e-05, 'reg_lambda': 1.368860929347125, 'max_delta_step': 1}. Best is trial 7 with value: 0.6919127086007703.

Best trial: 7. Best value: 0.691913:  16%|█▌        | 8/50 [01:49<06:18,  9.02s/it]

[I 2025-12-02 02:33:37,604] Trial 8 finished with value: 0.4024390243902439 and parameters: {'max_depth': 6, 'learning_rate': 0.07528368558749714, 'n_estimators': 347, 'subsample': 0.9504445680457232, 'colsample_bytree': 0.9849273149781144, 'min_child_weight': 10, 'gamma': 3.124046785346578, 'reg_alpha': 0.004265781927584027, 'reg_lambda': 1.5269573355440566e-07, 'max_delta_step': 4}. Best is trial 7 with value: 0.6919127086007703.

Best trial: 7. Best value: 0.691913:  18%|█▊        | 9/50 [03:04<20:23, 29.84s/it]

[I 2025-12-02 02:34:53,250] Trial 6 finished with value: 0.6373555840821565 and parameters: {'max_depth': 6, 'learning_rate': 0.013458871884390057, 'n_estimators': 1265, 'subsample': 0.9037227231125128, 'colsample_bytree': 0.518842229248315, 'min_child_weight': 2, 'gamma': 0.8449766288950644, 'reg_alpha': 0.000880758491498579, 'reg_lambda': 0.12832903391185985, 'max_delta_step': 7}. Best is trial 7 with value: 0.6919127086007703.

Best trial: 7. Best value: 0.691913:  20%|██        | 10/50 [03:14<15:43, 23.58s/it]

[I 2025-12-02 02:35:02,788] Trial 11 finished with value: 0.6232349165596919 and parameters: {'max_depth': 10, 'learning_rate': 0.02873892275955624, 'n_estimators': 427, 'subsample': 0.5182992557521001, 'colsample_bytree': 0.9202156756597619, 'min_child_weight': 1, 'gamma': 0.7074663793779701, 'reg_alpha': 2.785892585564259e-06, 'reg_lambda': 1.7680032837928328, 'max_delta_step': 0}. Best is trial 7 with value: 0.6919127086007703.

Best trial: 7. Best value: 0.691913:  22%|██▏       | 11/50 [03:16<11:01, 16.95s/it]

[I 2025-12-02 02:35:04,727] Trial 10 finished with value: 0.5847240051347882 and parameters: {'max_depth': 10, 'learning_rate': 0.08484988939096742, 'n_estimators': 1449, 'subsample': 0.9350642472759952, 'colsample_bytree': 0.8745933392523821, 'min_child_weight': 2, 'gamma': 0.9854976614344313, 'reg_alpha': 0.0004549269233777789, 'reg_lambda': 0.00037583371226427496, 'max_delta_step': 8}. Best is trial 7 with value: 0.6919127086007703.

Best trial: 7. Best value: 0.691913:  24%|██▍       | 12/50 [03:16<07:34, 11.96s/it]

[I 2025-12-02 02:35:05,238] Trial 12 pruned.

Best trial: 7. Best value: 0.691913:  26%|██▌       | 13/50 [03:19<05:38,  9.15s/it]

[I 2025-12-02 02:35:07,961] Trial 15 pruned.

Best trial: 7. Best value: 0.691913:  28%|██▊       | 14/50 [03:21<04:10,  6.97s/it]

[I 2025-12-02 02:35:09,850] Trial 13 pruned.

Best trial: 7. Best value: 0.691913:  30%|███       | 15/50 [03:30<04:22,  7.50s/it]

[I 2025-12-02 02:35:18,620] Trial 9 finished with value: 0.6617458279845956 and parameters: {'max_depth': 5, 'learning_rate': 0.019355015000353238, 'n_estimators': 1208, 'subsample': 0.7275454116605888, 'colsample_bytree': 0.5522816255469889, 'min_child_weight': 1, 'gamma': 3.0991575738786477, 'reg_alpha': 2.33602662699698, 'reg_lambda': 8.16519390009788e-07, 'max_delta_step': 2}. Best is trial 7 with value: 0.6919127086007703.

Best trial: 17. Best value: 0.728498:  32%|███▏      | 16/50 [03:44<05:19,  9.40s/it]

[I 2025-12-02 02:35:32,435] Trial 17 finished with value: 0.7284980744544287 and parameters: {'max_depth': 7, 'learning_rate': 0.0223136205756479, 'n_estimators': 233, 'subsample': 0.8287564672831091, 'colsample_bytree': 0.6026966645881036, 'min_child_weight': 6, 'gamma': 3.663371947978402, 'reg_alpha': 4.840779793195435e-07, 'reg_lambda': 0.01312400966764852, 'max_delta_step': 10}. Best is trial 17 with value: 0.7284980744544287.

Best trial: 17. Best value: 0.728498:  34%|███▍      | 17/50 [03:55<05:34, 10.13s/it]

[I 2025-12-02 02:35:44,264] Trial 18 finished with value: 0.7021822849807445 and parameters: {'max_depth': 8, 'learning_rate': 0.024211577566240348, 'n_estimators': 259, 'subsample': 0.8732204277697259, 'colsample_bytree': 0.6016299203331181, 'min_child_weight': 6, 'gamma': 2.1980005732210666, 'reg_alpha': 1.1934659749399242e-06, 'reg_lambda': 0.010529161783190173, 'max_delta_step': 10}. Best is trial 17 with value: 0.7284980744544287.

Best trial: 17. Best value: 0.728498:  36%|███▌      | 18/50 [03:59<04:25,  8.29s/it]

[I 2025-12-02 02:35:48,276] Trial 14 finished with value: 0.6919127086007703 and parameters: {'max_depth': 8, 'learning_rate': 0.011088656394525147, 'n_estimators': 738, 'subsample': 0.6165253436338222, 'colsample_bytree': 0.63422527790165, 'min_child_weight': 7, 'gamma': 2.4746341244804926, 'reg_alpha': 3.588466639063419e-08, 'reg_lambda': 0.0036876470282987597, 'max_delta_step': 6}. Best is trial 17 with value: 0.7284980744544287.

Best trial: 17. Best value: 0.728498:  38%|███▊      | 19/50 [04:06<04:02,  7.81s/it]

[I 2025-12-02 02:35:54,951] Trial 16 finished with value: 0.6636713735558408 and parameters: {'max_depth': 8, 'learning_rate': 0.022536452577492455, 'n_estimators': 693, 'subsample': 0.8421066939139872, 'colsample_bytree': 0.5782937385545186, 'min_child_weight': 6, 'gamma': 2.5032490182407985, 'reg_alpha': 8.661642900746687e-08, 'reg_lambda': 0.03797901571490208, 'max_delta_step': 10}. Best is trial 17 with value: 0.7284980744544287.

Best trial: 17. Best value: 0.728498:  40%|████      | 20/50 [04:12<03:36,  7.22s/it]

[I 2025-12-02 02:36:00,776] Trial 19 finished with value: 0.6636713735558408 and parameters: {'max_depth': 8, 'learning_rate': 0.02185704095470851, 'n_estimators': 220, 'subsample': 0.8445439843588182, 'colsample_bytree': 0.5961116405432958, 'min_child_weight': 5, 'gamma': 3.9279616927211434, 'reg_alpha': 5.842845952168874e-07, 'reg_lambda': 5.262546506347572, 'max_delta_step': 10}. Best is trial 17 with value: 0.7284980744544287.

Best trial: 17. Best value: 0.728498:  42%|████▏     | 21/50 [04:39<06:21, 13.16s/it]

[I 2025-12-02 02:36:27,806] Trial 20 finished with value: 0.7021822849807445 and parameters: {'max_depth': 8, 'learning_rate': 0.02623886276569267, 'n_estimators': 604, 'subsample': 0.8584577007208167, 'colsample_bytree': 0.5863370115752062, 'min_child_weight': 5, 'gamma': 3.863044088391243, 'reg_alpha': 3.7291885827533374e-07, 'reg_lambda': 2.8242671356601596e-05, 'max_delta_step': 10}. Best is trial 17 with value: 0.7284980744544287.

Best trial: 17. Best value: 0.728498:  44%|████▍     | 22/50 [04:43<04:52, 10.46s/it]

[I 2025-12-02 02:36:31,961] Trial 21 finished with value: 0.689987163029525 and parameters: {'max_depth': 8, 'learning_rate': 0.025570933460058322, 'n_estimators': 596, 'subsample': 0.8421079538145685, 'colsample_bytree': 0.5908076491733765, 'min_child_weight': 5, 'gamma': 3.82952762204748, 'reg_alpha': 4.611672886146875e-07, 'reg_lambda': 2.300519568049818e-05, 'max_delta_step': 10}. Best is trial 17 with value: 0.7284980744544287.

Best trial: 17. Best value: 0.728498:  46%|████▌     | 23/50 [04:45<03:36,  8.03s/it]

[I 2025-12-02 02:36:34,316] Trial 22 finished with value: 0.7021822849807445 and parameters: {'max_depth': 7, 'learning_rate': 0.04111788719444392, 'n_estimators': 545, 'subsample': 0.8454236674992855, 'colsample_bytree': 0.764552614092248, 'min_child_weight': 5, 'gamma': 3.8300692340849998, 'reg_alpha': 4.905768230471448e-07, 'reg_lambda': 3.692690706071415e-05, 'max_delta_step': 9}. Best is trial 17 with value: 0.7284980744544287.

Best trial: 17. Best value: 0.728498:  50%|█████     | 25/50 [04:54<02:23,  5.73s/it]

[I 2025-12-02 02:36:42,660] Trial 25 pruned.
[I 2025-12-02 02:36:42,803] Trial 23 finished with value: 0.689987163029525 and parameters: {'max_depth': 7, 'learning_rate': 0.03478043497469682, 'n_estimators': 601, 'subsample': 0.8583745321184233, 'colsample_bytree': 0.7407568381753653, 'min_child_weight': 5, 'gamma': 3.8036690557633666, 'reg_alpha': 7.007669071458205e-07, 'reg_lambda': 2.7165802414346548e-05, 'max_delta_step': 9}. Best is trial 17 with value: 0.7284980744544287.

Best trial: 17. Best value: 0.728498:  52%|█████▏    | 26/50 [05:14<03:59, 10.00s/it]

[I 2025-12-02 02:37:02,765] Trial 28 finished with value: 0.7060333761232349 and parameters: {'max_depth': 6, 'learning_rate': 0.058036187332454706, 'n_estimators': 362, 'subsample': 0.7890640031416379, 'colsample_bytree': 0.6140504645064926, 'min_child_weight': 8, 'gamma': 1.9528909397428937, 'reg_alpha': 6.293545085526668e-06, 'reg_lambda': 0.00018817999032402321, 'max_delta_step': 7}. Best is trial 17 with value: 0.7284980744544287.

Best trial: 17. Best value: 0.728498:  54%|█████▍    | 27/50 [05:16<02:52,  7.50s/it]

[I 2025-12-02 02:37:04,430] Trial 27 finished with value: 0.6919127086007703 and parameters: {'max_depth': 6, 'learning_rate': 0.032191080452936865, 'n_estimators': 358, 'subsample': 0.8074780709865784, 'colsample_bytree': 0.6134134105022911, 'min_child_weight': 8, 'gamma': 1.8363543069043153, 'reg_alpha': 4.610383761437132e-06, 'reg_lambda': 0.0002505246633679257, 'max_delta_step': 9}. Best is trial 17 with value: 0.7284980744544287.

Best trial: 17. Best value: 0.728498:  56%|█████▌    | 28/50 [05:18<02:10,  5.92s/it]

[I 2025-12-02 02:37:06,667] Trial 24 finished with value: 0.7021822849807445 and parameters: {'max_depth': 7, 'learning_rate': 0.03799175783445668, 'n_estimators': 551, 'subsample': 0.8463604084769285, 'colsample_bytree': 0.7008407235933315, 'min_child_weight': 5, 'gamma': 4.880578521632245, 'reg_alpha': 4.839250106198115e-07, 'reg_lambda': 5.962666290645848e-05, 'max_delta_step': 9}. Best is trial 17 with value: 0.7284980744544287.

Best trial: 17. Best value: 0.728498:  58%|█████▊    | 29/50 [05:34<03:11,  9.13s/it]

[I 2025-12-02 02:37:23,298] Trial 31 finished with value: 0.7021822849807445 and parameters: {'max_depth': 5, 'learning_rate': 0.05678371390273029, 'n_estimators': 284, 'subsample': 0.8005515178247388, 'colsample_bytree': 0.5050010447637149, 'min_child_weight': 8, 'gamma': 1.7383510875995394, 'reg_alpha': 0.00010889771584228188, 'reg_lambda': 0.01082128291836716, 'max_delta_step': 6}. Best is trial 17 with value: 0.7284980744544287.

Best trial: 29. Best value: 0.742619:  60%|██████    | 30/50 [05:35<02:10,  6.52s/it]

[I 2025-12-02 02:37:23,717] Trial 29 finished with value: 0.7426187419768935 and parameters: {'max_depth': 5, 'learning_rate': 0.054202294501254765, 'n_estimators': 323, 'subsample': 0.8052352038597558, 'colsample_bytree': 0.6849974499209193, 'min_child_weight': 8, 'gamma': 1.9435399596939338, 'reg_alpha': 6.568077142636096e-06, 'reg_lambda': 0.00032668243727334374, 'max_delta_step': 6}. Best is trial 29 with value: 0.7426187419768935.
[I 2025-12-02 02:37:23,746] Trial 30 finished with value: 0.6675224646983312 and parameters: {'max_depth': 5, 'learning_rate': 0.054781510146258025, 'n_estimators': 300, 'subsample': 0.7905792810449168, 'colsample_bytree': 0.700742850495205, 'min_child_weight': 8, 'gamma': 1.8787264225640279, 'reg_alpha': 9.862720955532823e-05, 'reg_lambda': 0.013294031642053101, 'max_delta_step': 6}. Best is trial 29 with value: 0.7426187419768935.

Best trial: 29. Best value: 0.742619:  64%|██████▍   | 32/50 [05:51<02:11,  7.32s/it]

[I 2025-12-02 02:37:40,244] Trial 32 finished with value: 0.7041078305519897 and parameters: {'max_depth': 5, 'learning_rate': 0.11257531323038857, 'n_estimators': 300, 'subsample': 0.7725159486740275, 'colsample_bytree': 0.6800439045885575, 'min_child_weight': 8, 'gamma': 1.5963475498032411, 'reg_alpha': 2.211071376461864e-05, 'reg_lambda': 0.00048365861009805203, 'max_delta_step': 7}. Best is trial 29 with value: 0.7426187419768935.

Best trial: 29. Best value: 0.742619:  66%|██████▌   | 33/50 [05:55<01:47,  6.33s/it]

[I 2025-12-02 02:37:43,554] Trial 33 finished with value: 0.641206675224647 and parameters: {'max_depth': 3, 'learning_rate': 0.10356409590934479, 'n_estimators': 362, 'subsample': 0.7675413044564371, 'colsample_bytree': 0.6838664918189621, 'min_child_weight': 8, 'gamma': 1.465408325888213, 'reg_alpha': 1.9196082898940486e-05, 'reg_lambda': 4.065207874908254e-06, 'max_delta_step': 5}. Best is trial 29 with value: 0.7426187419768935.

Best trial: 29. Best value: 0.742619:  70%|███████   | 35/50 [05:55<00:53,  3.57s/it]

[I 2025-12-02 02:37:44,297] Trial 35 pruned.
[I 2025-12-02 02:37:44,399] Trial 34 finished with value: 0.6758664955070603 and parameters: {'max_depth': 3, 'learning_rate': 0.12801373579524764, 'n_estimators': 385, 'subsample': 0.9042454784838247, 'colsample_bytree': 0.6708292355155784, 'min_child_weight': 9, 'gamma': 2.0911225189342644, 'reg_alpha': 9.227719689291687e-06, 'reg_lambda': 0.0007672429908915921, 'max_delta_step': 5}. Best is trial 29 with value: 0.7426187419768935.

Best trial: 29. Best value: 0.742619:  72%|███████▏  | 36/50 [05:56<00:38,  2.77s/it]

[I 2025-12-02 02:37:45,118] Trial 26 finished with value: 0.689987163029525 and parameters: {'max_depth': 6, 'learning_rate': 0.03632864471412887, 'n_estimators': 989, 'subsample': 0.8885236342988022, 'colsample_bytree': 0.6961477127080128, 'min_child_weight': 4, 'gamma': 4.982592343932998, 'reg_alpha': 4.618978732296899e-06, 'reg_lambda': 0.0001597565810150277, 'max_delta_step': 9}. Best is trial 29 with value: 0.7426187419768935.

Best trial: 29. Best value: 0.742619:  74%|███████▍  | 37/50 [05:59<00:36,  2.83s/it]

[I 2025-12-02 02:37:48,075] Trial 36 pruned.

Best trial: 29. Best value: 0.742619:  76%|███████▌  | 38/50 [05:59<00:24,  2.06s/it]

[I 2025-12-02 02:37:48,265] Trial 37 pruned.

Best trial: 29. Best value: 0.742619:  80%|████████  | 40/50 [06:00<00:12,  1.26s/it]

[I 2025-12-02 02:37:49,192] Trial 38 pruned.
[I 2025-12-02 02:37:49,346] Trial 39 pruned.

Best trial: 29. Best value: 0.742619:  82%|████████▏ | 41/50 [06:02<00:13,  1.47s/it]

[I 2025-12-02 02:37:51,297] Trial 42 pruned.

Best trial: 29. Best value: 0.742619:  84%|████████▍ | 42/50 [06:06<00:16,  2.10s/it]

[I 2025-12-02 02:37:54,899] Trial 44 pruned.

Best trial: 29. Best value: 0.742619:  88%|████████▊ | 44/50 [06:15<00:17,  2.93s/it]

[I 2025-12-02 02:38:03,694] Trial 41 finished with value: 0.7041078305519897 and parameters: {'max_depth': 4, 'learning_rate': 0.059782378733017526, 'n_estimators': 204, 'subsample': 0.7339786677159164, 'colsample_bytree': 0.542855201733303, 'min_child_weight': 7, 'gamma': 2.6730280055658735, 'reg_alpha': 0.00018278485996664094, 'reg_lambda': 0.0787567529308489, 'max_delta_step': 4}. Best is trial 29 with value: 0.7426187419768935.
[I 2025-12-02 02:38:03,858] Trial 43 finished with value: 0.7182284980744544 and parameters: {'max_depth': 4, 'learning_rate': 0.06167745469876073, 'n_estimators': 207, 'subsample': 0.6491177456809274, 'colsample_bytree': 0.5494259412398764, 'min_child_weight': 7, 'gamma': 2.8139785680422795, 'reg_alpha': 0.0019146377714625714, 'reg_lambda': 0.0020470104383997234, 'max_delta_step': 4}. Best is trial 29 with value: 0.7426187419768935.

Best trial: 29. Best value: 0.742619:  90%|█████████ | 45/50 [06:19<00:15,  3.18s/it]

[I 2025-12-02 02:38:07,646] Trial 47 pruned.

Best trial: 29. Best value: 0.742619:  92%|█████████▏| 46/50 [06:19<00:09,  2.44s/it]

[I 2025-12-02 02:38:08,339] Trial 40 finished with value: 0.6777920410783055 and parameters: {'max_depth': 4, 'learning_rate': 0.06632506033647817, 'n_estimators': 317, 'subsample': 0.7308320213425165, 'colsample_bytree': 0.5520829943348393, 'min_child_weight': 8, 'gamma': 0.0526967502720459, 'reg_alpha': 7.242243982119764e-08, 'reg_lambda': 0.0018488622551429623, 'max_delta_step': 7}. Best is trial 29 with value: 0.7426187419768935.

Best trial: 29. Best value: 0.742619:  94%|█████████▍| 47/50 [06:26<00:11,  3.69s/it]

[I 2025-12-02 02:38:14,944] Trial 45 finished with value: 0.7284980744544287 and parameters: {'max_depth': 4, 'learning_rate': 0.06732072178759603, 'n_estimators': 303, 'subsample': 0.8229346759402547, 'colsample_bytree': 0.5566252221685377, 'min_child_weight': 7, 'gamma': 2.773330185024447, 'reg_alpha': 0.00239494943124411, 'reg_lambda': 0.04866440332272044, 'max_delta_step': 8}. Best is trial 29 with value: 0.7426187419768935.

Best trial: 29. Best value: 0.742619:  96%|█████████▌| 48/50 [06:33<00:09,  4.53s/it]

[I 2025-12-02 02:38:21,437] Trial 46 finished with value: 0.7426187419768935 and parameters: {'max_depth': 4, 'learning_rate': 0.06199560178370877, 'n_estimators': 325, 'subsample': 0.6666131470867936, 'colsample_bytree': 0.557700426283014, 'min_child_weight': 7, 'gamma': 2.808315271879199, 'reg_alpha': 0.0029866266261599347, 'reg_lambda': 0.043348951759882126, 'max_delta_step': 4}. Best is trial 29 with value: 0.7426187419768935.

Best trial: 29. Best value: 0.742619:  98%|█████████▊| 49/50 [07:01<00:11, 11.83s/it]

[I 2025-12-02 02:38:50,334] Trial 48 finished with value: 0.6919127086007703 and parameters: {'max_depth': 6, 'learning_rate': 0.06656404467164478, 'n_estimators': 1214, 'subsample': 0.6439622687775145, 'colsample_bytree': 0.5607767593044785, 'min_child_weight': 7, 'gamma': 1.1637816319896888, 'reg_alpha': 0.00230295550187338, 'reg_lambda': 0.0006444550486060218, 'max_delta_step': 3}. Best is trial 29 with value: 0.7426187419768935.

Best trial: 29. Best value: 0.742619: 100%|██████████| 50/50 [07:04<00:00,  8.50s/it]

[I 2025-12-02 02:38:53,177] Trial 49 finished with value: 0.6797175866495507 and parameters: {'max_depth': 6, 'learning_rate': 0.11273917969110693, 'n_estimators': 1271, 'subsample': 0.6682190016235312, 'colsample_bytree': 0.6541067266481851, 'min_child_weight': 7, 'gamma': 1.1943775674257808, 'reg_alpha': 0.001111117474889845, 'reg_lambda': 0.0006504949574852797, 'max_delta_step': 3}. Best is trial 29 with value: 0.7426187419768935.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 02:38:56,952] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.872368:   2%|▏         | 1/50 [00:20<16:52, 20.67s/it]

[I 2025-12-02 02:39:17,612] Trial 1 finished with value: 0.8723684210526316 and parameters: {'max_depth': 3, 'learning_rate': 0.27948440476138153, 'n_estimators': 437, 'subsample': 0.6790892931389242, 'colsample_bytree': 0.7734061759273443, 'min_child_weight': 4, 'gamma': 3.8469538159245498, 'reg_alpha': 0.022482350495248944, 'reg_lambda': 0.00023130454242617886, 'max_delta_step': 6}. Best is trial 1 with value: 0.8723684210526316.

Best trial: 0. Best value: 0.898684:   4%|▍         | 2/50 [00:46<18:49, 23.54s/it]

[I 2025-12-02 02:39:43,164] Trial 0 finished with value: 0.8986842105263158 and parameters: {'max_depth': 5, 'learning_rate': 0.1728210809088788, 'n_estimators': 1019, 'subsample': 0.8662007813456974, 'colsample_bytree': 0.8752790373503989, 'min_child_weight': 6, 'gamma': 2.93067792030268, 'reg_alpha': 2.1466675975032766e-08, 'reg_lambda': 0.0002584712429102169, 'max_delta_step': 0}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:   6%|▌         | 3/50 [00:55<13:27, 17.18s/it]

[I 2025-12-02 02:39:52,784] Trial 2 finished with value: 0.8585526315789473 and parameters: {'max_depth': 9, 'learning_rate': 0.09443829343241929, 'n_estimators': 1279, 'subsample': 0.8481508573195946, 'colsample_bytree': 0.7732740414414174, 'min_child_weight': 9, 'gamma': 1.8317229560911068, 'reg_alpha': 5.807556436824412e-06, 'reg_lambda': 0.0005767508511568417, 'max_delta_step': 0}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:   8%|▊         | 4/50 [01:03<10:18, 13.45s/it]

[I 2025-12-02 02:40:00,518] Trial 3 finished with value: 0.8986842105263158 and parameters: {'max_depth': 9, 'learning_rate': 0.04203715592941841, 'n_estimators': 1390, 'subsample': 0.9787441176524776, 'colsample_bytree': 0.8184160232220332, 'min_child_weight': 6, 'gamma': 2.88883621896633, 'reg_alpha': 0.02381517873100611, 'reg_lambda': 0.0008275253906870578, 'max_delta_step': 6}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  10%|█         | 5/50 [01:21<11:15, 15.02s/it]

[I 2025-12-02 02:40:18,307] Trial 4 finished with value: 0.075 and parameters: {'max_depth': 4, 'learning_rate': 0.012010367527965752, 'n_estimators': 1421, 'subsample': 0.7198356614668402, 'colsample_bytree': 0.5766732706050832, 'min_child_weight': 9, 'gamma': 0.3611653558877148, 'reg_alpha': 5.390106464411579, 'reg_lambda': 0.001960725911541965, 'max_delta_step': 6}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  12%|█▏        | 6/50 [01:25<08:18, 11.33s/it]

[I 2025-12-02 02:40:22,481] Trial 6 finished with value: 0.8447368421052632 and parameters: {'max_depth': 8, 'learning_rate': 0.08968600758677062, 'n_estimators': 587, 'subsample': 0.7158108552375825, 'colsample_bytree': 0.8275620440941338, 'min_child_weight': 6, 'gamma': 2.412337906020068, 'reg_alpha': 0.0038401334352753994, 'reg_lambda': 8.852547056128403e-06, 'max_delta_step': 2}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  14%|█▍        | 7/50 [01:38<08:32, 11.92s/it]

[I 2025-12-02 02:40:35,629] Trial 5 finished with value: 0.8447368421052632 and parameters: {'max_depth': 8, 'learning_rate': 0.05951691944095739, 'n_estimators': 664, 'subsample': 0.7246585338198652, 'colsample_bytree': 0.93288235013434, 'min_child_weight': 1, 'gamma': 0.8383052462275725, 'reg_alpha': 4.06833737157439e-08, 'reg_lambda': 0.7963180870269182, 'max_delta_step': 2}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  16%|█▌        | 8/50 [02:08<12:15, 17.50s/it]

[I 2025-12-02 02:41:05,070] Trial 9 finished with value: 0.8585526315789473 and parameters: {'max_depth': 10, 'learning_rate': 0.055107246017538865, 'n_estimators': 556, 'subsample': 0.941588729734478, 'colsample_bytree': 0.5999062448475168, 'min_child_weight': 1, 'gamma': 1.6538563728478062, 'reg_alpha': 7.042858913894488e-07, 'reg_lambda': 3.160608524517992e-05, 'max_delta_step': 3}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  18%|█▊        | 9/50 [02:08<08:15, 12.09s/it]

[I 2025-12-02 02:41:05,277] Trial 8 finished with value: 0.8585526315789473 and parameters: {'max_depth': 10, 'learning_rate': 0.19968538904769362, 'n_estimators': 993, 'subsample': 0.790507214067955, 'colsample_bytree': 0.8625536038469502, 'min_child_weight': 9, 'gamma': 1.5496811081510393, 'reg_alpha': 0.13970742589053065, 'reg_lambda': 0.004084217014230145, 'max_delta_step': 9}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  20%|██        | 10/50 [02:21<08:12, 12.32s/it]

[I 2025-12-02 02:41:18,093] Trial 10 finished with value: 0.8723684210526316 and parameters: {'max_depth': 7, 'learning_rate': 0.13472551115775583, 'n_estimators': 861, 'subsample': 0.8963784879616192, 'colsample_bytree': 0.8661141803102836, 'min_child_weight': 5, 'gamma': 4.452582511361935, 'reg_alpha': 0.004891437411224392, 'reg_lambda': 5.34121395126013e-07, 'max_delta_step': 8}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  22%|██▏       | 11/50 [02:23<06:06,  9.39s/it]

[I 2025-12-02 02:41:20,852] Trial 12 pruned.

Best trial: 0. Best value: 0.898684:  24%|██▍       | 12/50 [02:24<04:16,  6.76s/it]

[I 2025-12-02 02:41:21,598] Trial 11 pruned.

Best trial: 0. Best value: 0.898684:  26%|██▌       | 13/50 [02:45<06:47, 11.03s/it]

[I 2025-12-02 02:41:42,435] Trial 7 finished with value: 0.8723684210526316 and parameters: {'max_depth': 6, 'learning_rate': 0.03036281660956507, 'n_estimators': 1354, 'subsample': 0.9570432487921059, 'colsample_bytree': 0.5240137678588372, 'min_child_weight': 1, 'gamma': 4.911472887141304, 'reg_alpha': 0.007969535518470492, 'reg_lambda': 0.7064784504293489, 'max_delta_step': 1}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  28%|██▊       | 14/50 [03:21<11:12, 18.67s/it]

[I 2025-12-02 02:42:18,779] Trial 13 finished with value: 0.8710526315789473 and parameters: {'max_depth': 5, 'learning_rate': 0.021997498827522288, 'n_estimators': 1069, 'subsample': 0.5369645183453334, 'colsample_bytree': 0.997071597962295, 'min_child_weight': 3, 'gamma': 3.6110624880654574, 'reg_alpha': 4.085598321285478e-05, 'reg_lambda': 0.6543713589010535, 'max_delta_step': 0}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  30%|███       | 15/50 [03:22<07:42, 13.22s/it]

[I 2025-12-02 02:42:19,339] Trial 14 finished with value: 0.8986842105263158 and parameters: {'max_depth': 5, 'learning_rate': 0.026268896963932458, 'n_estimators': 1172, 'subsample': 0.9766174967074065, 'colsample_bytree': 0.9792892604626647, 'min_child_weight': 6, 'gamma': 3.2541510530443176, 'reg_alpha': 4.567032712140641e-05, 'reg_lambda': 0.19131043514247958, 'max_delta_step': 0}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  32%|███▏      | 16/50 [03:25<05:41, 10.05s/it]

[I 2025-12-02 02:42:22,037] Trial 15 finished with value: 0.8986842105263158 and parameters: {'max_depth': 5, 'learning_rate': 0.02570028601667946, 'n_estimators': 1203, 'subsample': 0.9897183114668611, 'colsample_bytree': 0.9938629800860015, 'min_child_weight': 6, 'gamma': 3.345281610116647, 'reg_alpha': 0.0001304095142145895, 'reg_lambda': 0.0972722983466034, 'max_delta_step': 4}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  34%|███▍      | 17/50 [03:37<05:53, 10.72s/it]

[I 2025-12-02 02:42:34,329] Trial 19 finished with value: 0.8723684210526316 and parameters: {'max_depth': 7, 'learning_rate': 0.1291375071035871, 'n_estimators': 220, 'subsample': 0.8538712680181831, 'colsample_bytree': 0.6705694529315495, 'min_child_weight': 7, 'gamma': 2.534007571003023, 'reg_alpha': 2.4960212455133985e-08, 'reg_lambda': 2.0466385157577453e-08, 'max_delta_step': 10}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  36%|███▌      | 18/50 [03:40<04:26,  8.31s/it]

[I 2025-12-02 02:42:37,038] Trial 16 finished with value: 0.8986842105263158 and parameters: {'max_depth': 5, 'learning_rate': 0.020579028694551568, 'n_estimators': 1162, 'subsample': 0.9874873146954335, 'colsample_bytree': 0.6865824531755927, 'min_child_weight': 7, 'gamma': 3.1799394029067902, 'reg_alpha': 4.7015758188232415e-05, 'reg_lambda': 1.90273103584081e-08, 'max_delta_step': 4}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  38%|███▊      | 19/50 [04:15<08:27, 16.36s/it]

[I 2025-12-02 02:43:12,122] Trial 18 finished with value: 0.8585526315789473 and parameters: {'max_depth': 7, 'learning_rate': 0.1484801507514265, 'n_estimators': 1186, 'subsample': 0.8471230929263089, 'colsample_bytree': 0.6827917358804705, 'min_child_weight': 7, 'gamma': 2.797407777175129, 'reg_alpha': 1.0765317884331056e-08, 'reg_lambda': 0.01877432186207174, 'max_delta_step': 4}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  40%|████      | 20/50 [04:19<06:22, 12.75s/it]

[I 2025-12-02 02:43:16,465] Trial 17 finished with value: 0.8986842105263158 and parameters: {'max_depth': 5, 'learning_rate': 0.015458789592446457, 'n_estimators': 1193, 'subsample': 0.9882176163973577, 'colsample_bytree': 0.6911232617039316, 'min_child_weight': 7, 'gamma': 2.895046294993451, 'reg_alpha': 2.998261773692734e-08, 'reg_lambda': 3.236577369971131e-08, 'max_delta_step': 4}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  42%|████▏     | 21/50 [04:29<05:48, 12.01s/it]

[I 2025-12-02 02:43:26,764] Trial 20 finished with value: 0.8460526315789474 and parameters: {'max_depth': 8, 'learning_rate': 0.015692750859572932, 'n_estimators': 749, 'subsample': 0.9022959350605496, 'colsample_bytree': 0.6672141354396987, 'min_child_weight': 3, 'gamma': 2.5989023831732583, 'reg_alpha': 2.107335964793326e-06, 'reg_lambda': 0.013263449792213429, 'max_delta_step': 4}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  44%|████▍     | 22/50 [05:10<09:38, 20.65s/it]

[I 2025-12-02 02:44:07,570] Trial 21 finished with value: 0.8460526315789474 and parameters: {'max_depth': 9, 'learning_rate': 0.012828477449407403, 'n_estimators': 1498, 'subsample': 0.9024935311952759, 'colsample_bytree': 0.7106990875597254, 'min_child_weight': 3, 'gamma': 2.6049889244905144, 'reg_alpha': 5.29555175923345e-07, 'reg_lambda': 0.013162785895892815, 'max_delta_step': 7}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  46%|████▌     | 23/50 [05:33<09:34, 21.27s/it]

[I 2025-12-02 02:44:30,265] Trial 23 finished with value: 0.8460526315789474 and parameters: {'max_depth': 9, 'learning_rate': 0.08975937887200557, 'n_estimators': 1465, 'subsample': 0.9067090310691381, 'colsample_bytree': 0.923737840955269, 'min_child_weight': 3, 'gamma': 2.1678775757714694, 'reg_alpha': 4.197437599334186e-07, 'reg_lambda': 2.3999941025266836e-05, 'max_delta_step': 7}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  48%|████▊     | 24/50 [05:50<08:43, 20.14s/it]

[I 2025-12-02 02:44:47,764] Trial 24 finished with value: 0.8986842105263158 and parameters: {'max_depth': 4, 'learning_rate': 0.03946522276276631, 'n_estimators': 1500, 'subsample': 0.911396006440885, 'colsample_bytree': 0.9377886018852791, 'min_child_weight': 5, 'gamma': 3.9725053638010177, 'reg_alpha': 0.0005067042612150048, 'reg_lambda': 5.855818547929793, 'max_delta_step': 1}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  50%|█████     | 25/50 [06:05<07:42, 18.52s/it]

[I 2025-12-02 02:45:02,506] Trial 25 finished with value: 0.8986842105263158 and parameters: {'max_depth': 4, 'learning_rate': 0.039824507429983454, 'n_estimators': 1069, 'subsample': 0.7975067217827527, 'colsample_bytree': 0.9157088577959576, 'min_child_weight': 5, 'gamma': 4.22034068854046, 'reg_alpha': 0.0004708067030672529, 'reg_lambda': 4.5106072090012194e-05, 'max_delta_step': 1}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  52%|█████▏    | 26/50 [06:09<05:36, 14.02s/it]

[I 2025-12-02 02:45:06,034] Trial 22 finished with value: 0.8986842105263158 and parameters: {'max_depth': 9, 'learning_rate': 0.012512859476010102, 'n_estimators': 1491, 'subsample': 0.9080240885962034, 'colsample_bytree': 0.729755259173347, 'min_child_weight': 3, 'gamma': 2.131078433102113, 'reg_alpha': 7.430701777682225e-07, 'reg_lambda': 6.852969126098973, 'max_delta_step': 7}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  54%|█████▍    | 27/50 [06:26<05:49, 15.18s/it]

[I 2025-12-02 02:45:23,907] Trial 26 finished with value: 0.8986842105263158 and parameters: {'max_depth': 4, 'learning_rate': 0.04059386244994788, 'n_estimators': 1062, 'subsample': 0.7865787449317361, 'colsample_bytree': 0.9400722627656289, 'min_child_weight': 5, 'gamma': 3.8471700293407833, 'reg_alpha': 0.0005701595749975568, 'reg_lambda': 0.09694248531385607, 'max_delta_step': 1}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  56%|█████▌    | 28/50 [06:43<05:45, 15.73s/it]

[I 2025-12-02 02:45:40,916] Trial 27 finished with value: 0.8986842105263158 and parameters: {'max_depth': 4, 'learning_rate': 0.041907871749161094, 'n_estimators': 1054, 'subsample': 0.8072037748170222, 'colsample_bytree': 0.8354545918255897, 'min_child_weight': 5, 'gamma': 3.168556869849143, 'reg_alpha': 0.0005168421991026742, 'reg_lambda': 0.10512750788758357, 'max_delta_step': 1}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  58%|█████▊    | 29/50 [07:09<06:31, 18.64s/it]

[I 2025-12-02 02:46:06,352] Trial 28 finished with value: 0.8986842105263158 and parameters: {'max_depth': 6, 'learning_rate': 0.07370870657041662, 'n_estimators': 1293, 'subsample': 0.805301812176371, 'colsample_bytree': 0.972821429442484, 'min_child_weight': 6, 'gamma': 3.4120830729841787, 'reg_alpha': 0.48292106501582677, 'reg_lambda': 0.06277011779942458, 'max_delta_step': 0}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  60%|██████    | 30/50 [07:15<04:59, 14.99s/it]

[I 2025-12-02 02:46:12,843] Trial 29 finished with value: 0.8986842105263158 and parameters: {'max_depth': 6, 'learning_rate': 0.04072602924213913, 'n_estimators': 1354, 'subsample': 0.9509610941373595, 'colsample_bytree': 0.9602638415185407, 'min_child_weight': 6, 'gamma': 3.2958827919888956, 'reg_alpha': 0.42441890747432887, 'reg_lambda': 0.05109085410269958, 'max_delta_step': 0}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 0. Best value: 0.898684:  62%|██████▏   | 31/50 [07:32<04:54, 15.52s/it]

[I 2025-12-02 02:46:29,588] Trial 30 finished with value: 0.8986842105263158 and parameters: {'max_depth': 6, 'learning_rate': 0.068908604189153, 'n_estimators': 1347, 'subsample': 0.9489585353001465, 'colsample_bytree': 0.8181328066377922, 'min_child_weight': 6, 'gamma': 3.1675084848017994, 'reg_alpha': 0.5431751330020522, 'reg_lambda': 9.761369994918314e-05, 'max_delta_step': 0}. Best is trial 0 with value: 0.8986842105263158.

Best trial: 31. Best value: 0.911184:  64%|██████▍   | 32/50 [07:47<04:37, 15.43s/it]

[I 2025-12-02 02:46:44,812] Trial 31 finished with value: 0.9111842105263157 and parameters: {'max_depth': 6, 'learning_rate': 0.07182685766538466, 'n_estimators': 1326, 'subsample': 0.9597829395613183, 'colsample_bytree': 0.9702246828691053, 'min_child_weight': 8, 'gamma': 3.3920097672295086, 'reg_alpha': 0.5142423477095517, 'reg_lambda': 0.0012168732672524954, 'max_delta_step': 0}. Best is trial 31 with value: 0.9111842105263157.

Best trial: 31. Best value: 0.911184:  66%|██████▌   | 33/50 [07:52<03:28, 12.29s/it]

[I 2025-12-02 02:46:49,760] Trial 33 finished with value: 0.8197368421052631 and parameters: {'max_depth': 3, 'learning_rate': 0.2601647815972932, 'n_estimators': 782, 'subsample': 0.6548089229652142, 'colsample_bytree': 0.7900755884075392, 'min_child_weight': 4, 'gamma': 2.917866235587758, 'reg_alpha': 0.030413205647325643, 'reg_lambda': 0.00016195138872295942, 'max_delta_step': 5}. Best is trial 31 with value: 0.9111842105263157.

Best trial: 31. Best value: 0.911184:  68%|██████▊   | 34/50 [07:58<02:43, 10.21s/it]

[I 2025-12-02 02:46:55,139] Trial 35 pruned.

Best trial: 31. Best value: 0.911184:  70%|███████   | 35/50 [08:03<02:11,  8.76s/it]

[I 2025-12-02 02:47:00,492] Trial 36 pruned.

Best trial: 31. Best value: 0.911184:  72%|███████▏  | 36/50 [08:09<01:51,  7.97s/it]

[I 2025-12-02 02:47:06,642] Trial 37 pruned.

Best trial: 31. Best value: 0.911184:  74%|███████▍  | 37/50 [08:11<01:18,  6.06s/it]

[I 2025-12-02 02:47:08,240] Trial 32 finished with value: 0.8723684210526316 and parameters: {'max_depth': 6, 'learning_rate': 0.2857149697664583, 'n_estimators': 1316, 'subsample': 0.6442233339198156, 'colsample_bytree': 0.7860243327342366, 'min_child_weight': 4, 'gamma': 2.98030875914126, 'reg_alpha': 1.1495930209843805e-05, 'reg_lambda': 0.0001270219529488452, 'max_delta_step': 6}. Best is trial 31 with value: 0.9111842105263157.

Best trial: 31. Best value: 0.911184:  76%|███████▌  | 38/50 [08:42<02:43, 13.61s/it]

[I 2025-12-02 02:47:39,449] Trial 34 finished with value: 0.8723684210526316 and parameters: {'max_depth': 5, 'learning_rate': 0.02691737383952318, 'n_estimators': 1217, 'subsample': 0.9912248768034736, 'colsample_bytree': 0.9911271163899079, 'min_child_weight': 4, 'gamma': 3.562485343800092, 'reg_alpha': 3.3124707599474576e-05, 'reg_lambda': 0.0003902976440531377, 'max_delta_step': 6}. Best is trial 31 with value: 0.9111842105263157.

Best trial: 31. Best value: 0.911184:  78%|███████▊  | 39/50 [09:04<02:57, 16.10s/it]

[I 2025-12-02 02:48:01,377] Trial 40 finished with value: 0.8848684210526316 and parameters: {'max_depth': 8, 'learning_rate': 0.10339099906728969, 'n_estimators': 1109, 'subsample': 0.9339222520285759, 'colsample_bytree': 0.9680761050431939, 'min_child_weight': 8, 'gamma': 4.528110902200206, 'reg_alpha': 4.279495297130321, 'reg_lambda': 3.3739537697165053e-06, 'max_delta_step': 3}. Best is trial 31 with value: 0.9111842105263157.

Best trial: 31. Best value: 0.911184:  80%|████████  | 40/50 [09:07<02:02, 12.23s/it]

[I 2025-12-02 02:48:04,571] Trial 38 finished with value: 0.8986842105263158 and parameters: {'max_depth': 7, 'learning_rate': 0.10701490442420596, 'n_estimators': 1388, 'subsample': 0.9690352578192655, 'colsample_bytree': 0.7497381549097871, 'min_child_weight': 8, 'gamma': 2.0622756279436225, 'reg_alpha': 4.508926303296513, 'reg_lambda': 0.0043615820566480345, 'max_delta_step': 6}. Best is trial 31 with value: 0.9111842105263157.

Best trial: 31. Best value: 0.911184:  82%|████████▏ | 41/50 [09:11<01:27,  9.69s/it]

[I 2025-12-02 02:48:08,334] Trial 39 finished with value: 0.8848684210526316 and parameters: {'max_depth': 8, 'learning_rate': 0.02897387856528667, 'n_estimators': 1162, 'subsample': 0.936141764873662, 'colsample_bytree': 0.9541568442294722, 'min_child_weight': 8, 'gamma': 4.219969369421808, 'reg_alpha': 9.014611467405539, 'reg_lambda': 0.00393692253788645, 'max_delta_step': 3}. Best is trial 31 with value: 0.9111842105263157.

Best trial: 31. Best value: 0.911184:  84%|████████▍ | 42/50 [09:34<01:50, 13.85s/it]

[I 2025-12-02 02:48:31,893] Trial 41 finished with value: 0.8848684210526316 and parameters: {'max_depth': 8, 'learning_rate': 0.11008474765641574, 'n_estimators': 1143, 'subsample': 0.9351150924957905, 'colsample_bytree': 0.8494823457212535, 'min_child_weight': 8, 'gamma': 4.116927141984449, 'reg_alpha': 3.166409973494737, 'reg_lambda': 0.005688123679426599, 'max_delta_step': 3}. Best is trial 31 with value: 0.9111842105263157.

Best trial: 31. Best value: 0.911184:  86%|████████▌ | 43/50 [09:50<01:40, 14.35s/it]

[I 2025-12-02 02:48:47,423] Trial 42 finished with value: 0.8585526315789473 and parameters: {'max_depth': 8, 'learning_rate': 0.06960957828438012, 'n_estimators': 989, 'subsample': 0.879308829561676, 'colsample_bytree': 0.8539896435639104, 'min_child_weight': 8, 'gamma': 4.003774146639341, 'reg_alpha': 0.0015665152084346691, 'reg_lambda': 0.004260614386202611, 'max_delta_step': 2}. Best is trial 31 with value: 0.9111842105263157.

Best trial: 31. Best value: 0.911184:  88%|████████▊ | 44/50 [09:53<01:05, 10.90s/it]

[I 2025-12-02 02:48:50,264] Trial 43 finished with value: 0.8848684210526316 and parameters: {'max_depth': 10, 'learning_rate': 0.04960727923535093, 'n_estimators': 976, 'subsample': 0.9357238641963876, 'colsample_bytree': 0.8459351239680927, 'min_child_weight': 8, 'gamma': 4.088319283577847, 'reg_alpha': 0.0021914385030191944, 'reg_lambda': 0.004322923488632761, 'max_delta_step': 2}. Best is trial 31 with value: 0.9111842105263157.

Best trial: 31. Best value: 0.911184:  90%|█████████ | 45/50 [10:01<00:50, 10.05s/it]

[I 2025-12-02 02:48:58,331] Trial 44 finished with value: 0.8986842105263158 and parameters: {'max_depth': 5, 'learning_rate': 0.020814424356278966, 'n_estimators': 969, 'subsample': 0.9736144197280852, 'colsample_bytree': 0.8443713241943323, 'min_child_weight': 6, 'gamma': 3.422099988875733, 'reg_alpha': 0.010878747372018695, 'reg_lambda': 0.3049455430565927, 'max_delta_step': 2}. Best is trial 31 with value: 0.9111842105263157.

Best trial: 31. Best value: 0.911184:  92%|█████████▏| 46/50 [10:27<00:59, 14.83s/it]

[I 2025-12-02 02:49:24,322] Trial 45 finished with value: 0.8986842105263158 and parameters: {'max_depth': 5, 'learning_rate': 0.021788801898902685, 'n_estimators': 1004, 'subsample': 0.9649836942674678, 'colsample_bytree': 0.910230782220996, 'min_child_weight': 6, 'gamma': 2.3582565210519695, 'reg_alpha': 0.00223747642696069, 'reg_lambda': 0.22028063073002924, 'max_delta_step': 0}. Best is trial 31 with value: 0.9111842105263157.

Best trial: 31. Best value: 0.911184:  94%|█████████▍| 47/50 [10:53<00:54, 18.27s/it]

[I 2025-12-02 02:49:50,601] Trial 46 finished with value: 0.8986842105263158 and parameters: {'max_depth': 5, 'learning_rate': 0.023035325332596304, 'n_estimators': 1242, 'subsample': 0.9729835982488909, 'colsample_bytree': 0.9128994300900474, 'min_child_weight': 6, 'gamma': 2.358535929264929, 'reg_alpha': 0.00017975493890184908, 'reg_lambda': 1.8832829845183932, 'max_delta_step': 0}. Best is trial 31 with value: 0.9111842105263157.

Best trial: 31. Best value: 0.911184:  96%|█████████▌| 48/50 [10:55<00:26, 13.34s/it]

[I 2025-12-02 02:49:52,445] Trial 47 finished with value: 0.8986842105263158 and parameters: {'max_depth': 5, 'learning_rate': 0.02491319885270045, 'n_estimators': 1243, 'subsample': 0.9724964934724469, 'colsample_bytree': 0.9984425361265592, 'min_child_weight': 6, 'gamma': 2.3469296222208285, 'reg_alpha': 0.0001661035739254027, 'reg_lambda': 0.40248256406525745, 'max_delta_step': 0}. Best is trial 31 with value: 0.9111842105263157.

Best trial: 48. Best value: 0.925:  98%|█████████▊| 49/50 [11:01<00:10, 11.00s/it]

[I 2025-12-02 02:49:57,982] Trial 48 finished with value: 0.925 and parameters: {'max_depth': 5, 'learning_rate': 0.024404888092007134, 'n_estimators': 1250, 'subsample': 0.969130387273638, 'colsample_bytree': 0.9105117508738881, 'min_child_weight': 7, 'gamma': 2.3903317358675187, 'reg_alpha': 0.00010883063866273296, 'reg_lambda': 1.4311680831066975, 'max_delta_step': 0}. Best is trial 48 with value: 0.925.

Best trial: 48. Best value: 0.925: 100%|██████████| 50/50 [11:17<00:00, 13.56s/it]

[I 2025-12-02 02:50:14,913] Trial 49 finished with value: 0.925 and parameters: {'max_depth': 6, 'learning_rate': 0.04949959807386659, 'n_estimators': 1224, 'subsample': 0.9708818877905437, 'colsample_bytree': 0.9956842161523527, 'min_child_weight': 7, 'gamma': 2.803527025205295, 'reg_alpha': 1.7235989828790517e-07, 'reg_lambda': 1.279444798328333, 'max_delta_step': 8}. Best is trial 48 with value: 0.925.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 02:50:19,313] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.667522:   2%|▏         | 1/50 [00:51<42:03, 51.50s/it]

[I 2025-12-02 02:51:10,805] Trial 3 finished with value: 0.6675224646983312 and parameters: {'max_depth': 8, 'learning_rate': 0.022577155018903287, 'n_estimators': 1091, 'subsample': 0.8556490122575697, 'colsample_bytree': 0.649452971567738, 'min_child_weight': 8, 'gamma': 0.3829772803878184, 'reg_alpha': 2.2815036332236866e-06, 'reg_lambda': 2.0917753672572152e-05, 'max_delta_step': 3}. Best is trial 3 with value: 0.6675224646983312.

Best trial: 2. Best value: 0.744544:   4%|▍         | 2/50 [00:59<20:51, 26.07s/it]

[I 2025-12-02 02:51:19,068] Trial 2 finished with value: 0.7445442875481387 and parameters: {'max_depth': 10, 'learning_rate': 0.03416161842630699, 'n_estimators': 1214, 'subsample': 0.507595146492742, 'colsample_bytree': 0.8194503318250219, 'min_child_weight': 5, 'gamma': 3.525238165069781, 'reg_alpha': 2.6390612414453195e-05, 'reg_lambda': 2.5502328638863243e-06, 'max_delta_step': 2}. Best is trial 2 with value: 0.7445442875481387.

Best trial: 2. Best value: 0.744544:   6%|▌         | 3/50 [01:06<13:20, 17.02s/it]

[I 2025-12-02 02:51:25,328] Trial 1 finished with value: 0.6675224646983312 and parameters: {'max_depth': 3, 'learning_rate': 0.010729883354650737, 'n_estimators': 1269, 'subsample': 0.942694317925537, 'colsample_bytree': 0.7196685568357815, 'min_child_weight': 8, 'gamma': 1.7908444559397791, 'reg_alpha': 0.04077256744967161, 'reg_lambda': 3.2752761521967784e-08, 'max_delta_step': 7}. Best is trial 2 with value: 0.7445442875481387.

Best trial: 2. Best value: 0.744544:   8%|▊         | 4/50 [01:13<10:06, 13.18s/it]

[I 2025-12-02 02:51:32,612] Trial 4 finished with value: 0.15789473684210525 and parameters: {'max_depth': 3, 'learning_rate': 0.038101525860137465, 'n_estimators': 380, 'subsample': 0.674951972661378, 'colsample_bytree': 0.80037484775726, 'min_child_weight': 10, 'gamma': 3.642992877471406, 'reg_alpha': 0.0973470118986186, 'reg_lambda': 5.562592036079604e-08, 'max_delta_step': 2}. Best is trial 2 with value: 0.7445442875481387.

Best trial: 2. Best value: 0.744544:  10%|█         | 5/50 [01:22<08:55, 11.90s/it]

[I 2025-12-02 02:51:42,239] Trial 5 finished with value: 0.6797175866495507 and parameters: {'max_depth': 4, 'learning_rate': 0.08217193996113141, 'n_estimators': 405, 'subsample': 0.7593782571657886, 'colsample_bytree': 0.600873093978934, 'min_child_weight': 8, 'gamma': 0.2524695279959427, 'reg_alpha': 0.002748820388539322, 'reg_lambda': 2.3230896981871215e-07, 'max_delta_step': 9}. Best is trial 2 with value: 0.7445442875481387.

Best trial: 6. Best value: 0.74647:  12%|█▏        | 6/50 [01:28<07:04,  9.65s/it]

[I 2025-12-02 02:51:47,530] Trial 6 finished with value: 0.7464698331193838 and parameters: {'max_depth': 6, 'learning_rate': 0.12978889784852482, 'n_estimators': 349, 'subsample': 0.5790130276203767, 'colsample_bytree': 0.9489144023079767, 'min_child_weight': 7, 'gamma': 4.9609771684150585, 'reg_alpha': 0.26810282131620816, 'reg_lambda': 0.007558112014678705, 'max_delta_step': 1}. Best is trial 6 with value: 0.7464698331193838.

Best trial: 6. Best value: 0.74647:  14%|█▍        | 7/50 [02:01<12:26, 17.36s/it]

[I 2025-12-02 02:52:20,776] Trial 7 finished with value: 0.6797175866495507 and parameters: {'max_depth': 9, 'learning_rate': 0.24172995089450897, 'n_estimators': 554, 'subsample': 0.7328477914846886, 'colsample_bytree': 0.6807255025410823, 'min_child_weight': 1, 'gamma': 3.013979211958012, 'reg_alpha': 2.079452627050771e-06, 'reg_lambda': 5.179883828125873, 'max_delta_step': 10}. Best is trial 6 with value: 0.7464698331193838.

Best trial: 9. Best value: 0.77086:  16%|█▌        | 8/50 [02:05<09:11, 13.13s/it]

[I 2025-12-02 02:52:24,856] Trial 9 finished with value: 0.7708600770218228 and parameters: {'max_depth': 3, 'learning_rate': 0.15936801458838634, 'n_estimators': 726, 'subsample': 0.7377796503803788, 'colsample_bytree': 0.6673874270276543, 'min_child_weight': 4, 'gamma': 3.141510761490171, 'reg_alpha': 1.0166912669230739e-08, 'reg_lambda': 3.713797718527566, 'max_delta_step': 8}. Best is trial 9 with value: 0.7708600770218228.

Best trial: 9. Best value: 0.77086:  18%|█▊        | 9/50 [02:12<07:35, 11.12s/it]

[I 2025-12-02 02:52:31,542] Trial 8 finished with value: 0.730423620025674 and parameters: {'max_depth': 4, 'learning_rate': 0.284054761065128, 'n_estimators': 967, 'subsample': 0.9060485764588261, 'colsample_bytree': 0.8708912880018131, 'min_child_weight': 5, 'gamma': 1.1133399608624543, 'reg_alpha': 1.7385781911338178, 'reg_lambda': 1.2050368498660997, 'max_delta_step': 2}. Best is trial 9 with value: 0.7708600770218228.

Best trial: 9. Best value: 0.77086:  20%|██        | 10/50 [02:21<06:56, 10.41s/it]

[I 2025-12-02 02:52:40,352] Trial 10 finished with value: 0.6919127086007703 and parameters: {'max_depth': 3, 'learning_rate': 0.21689009113571742, 'n_estimators': 252, 'subsample': 0.7969350032722052, 'colsample_bytree': 0.9431940082939827, 'min_child_weight': 2, 'gamma': 0.9191698231274226, 'reg_alpha': 0.060698791968006455, 'reg_lambda': 1.0167940559441043e-06, 'max_delta_step': 6}. Best is trial 9 with value: 0.7708600770218228.

Best trial: 9. Best value: 0.77086:  22%|██▏       | 11/50 [02:32<06:54, 10.63s/it]

[I 2025-12-02 02:52:51,485] Trial 0 finished with value: 0.7426187419768935 and parameters: {'max_depth': 6, 'learning_rate': 0.010726852220878944, 'n_estimators': 1225, 'subsample': 0.7763763016617673, 'colsample_bytree': 0.6885549794843364, 'min_child_weight': 1, 'gamma': 3.7579854094960394, 'reg_alpha': 1.2638921740558068e-05, 'reg_lambda': 3.114879846987444e-08, 'max_delta_step': 1}. Best is trial 9 with value: 0.7708600770218228.

Best trial: 9. Best value: 0.77086:  24%|██▍       | 12/50 [02:42<06:45, 10.67s/it]

[I 2025-12-02 02:53:02,257] Trial 11 finished with value: 0.6534017971758665 and parameters: {'max_depth': 7, 'learning_rate': 0.04631299588067125, 'n_estimators': 328, 'subsample': 0.5169421542997295, 'colsample_bytree': 0.7176585677961054, 'min_child_weight': 1, 'gamma': 2.260265675529798, 'reg_alpha': 3.175795618885653e-08, 'reg_lambda': 1.4341885631344325e-05, 'max_delta_step': 2}. Best is trial 9 with value: 0.7708600770218228.

Best trial: 9. Best value: 0.77086:  26%|██▌       | 13/50 [02:51<06:15, 10.16s/it]

[I 2025-12-02 02:53:11,240] Trial 12 finished with value: 0.7323491655969192 and parameters: {'max_depth': 6, 'learning_rate': 0.05423171326551807, 'n_estimators': 766, 'subsample': 0.5121794810092297, 'colsample_bytree': 0.5127563434801815, 'min_child_weight': 5, 'gamma': 1.0376532761196748, 'reg_alpha': 2.072147550529336e-07, 'reg_lambda': 2.512127862969375e-08, 'max_delta_step': 10}. Best is trial 9 with value: 0.7708600770218228.

Best trial: 9. Best value: 0.77086:  28%|██▊       | 14/50 [03:01<06:04, 10.13s/it]

[I 2025-12-02 02:53:21,294] Trial 13 finished with value: 0.7060333761232349 and parameters: {'max_depth': 6, 'learning_rate': 0.09431211165198083, 'n_estimators': 779, 'subsample': 0.6559559136417085, 'colsample_bytree': 0.5287529196803421, 'min_child_weight': 3, 'gamma': 4.681519264452615, 'reg_alpha': 3.458593495011324e-08, 'reg_lambda': 0.009695342633575658, 'max_delta_step': 8}. Best is trial 9 with value: 0.7708600770218228.

Best trial: 9. Best value: 0.77086:  30%|███       | 15/50 [03:08<05:15,  9.01s/it]

[I 2025-12-02 02:53:27,718] Trial 14 finished with value: 0.7445442875481387 and parameters: {'max_depth': 6, 'learning_rate': 0.10579272346467376, 'n_estimators': 720, 'subsample': 0.6101214130889041, 'colsample_bytree': 0.5251460099948646, 'min_child_weight': 4, 'gamma': 4.886076749082914, 'reg_alpha': 1.8069210394896417e-08, 'reg_lambda': 0.01800871112876539, 'max_delta_step': 4}. Best is trial 9 with value: 0.7708600770218228.

Best trial: 9. Best value: 0.77086:  32%|███▏      | 16/50 [03:20<05:33,  9.80s/it]

[I 2025-12-02 02:53:39,358] Trial 15 finished with value: 0.7201540436456997 and parameters: {'max_depth': 6, 'learning_rate': 0.10271030806738932, 'n_estimators': 696, 'subsample': 0.6199784510140267, 'colsample_bytree': 0.5453894168836425, 'min_child_weight': 3, 'gamma': 4.692879700606268, 'reg_alpha': 1.1204540792625345e-08, 'reg_lambda': 0.011399838274095235, 'max_delta_step': 5}. Best is trial 9 with value: 0.7708600770218228.

Best trial: 9. Best value: 0.77086:  34%|███▍      | 17/50 [03:33<06:03, 11.00s/it]

[I 2025-12-02 02:53:53,143] Trial 17 finished with value: 0.7201540436456997 and parameters: {'max_depth': 5, 'learning_rate': 0.1347635043258078, 'n_estimators': 601, 'subsample': 0.6060852153532301, 'colsample_bytree': 0.9927259225569013, 'min_child_weight': 7, 'gamma': 4.835418496399987, 'reg_alpha': 6.9170283533987655, 'reg_lambda': 0.028473619369374478, 'max_delta_step': 5}. Best is trial 9 with value: 0.7708600770218228.

Best trial: 9. Best value: 0.77086:  36%|███▌      | 18/50 [03:43<05:35, 10.49s/it]

[I 2025-12-02 02:54:02,448] Trial 20 pruned.

Best trial: 9. Best value: 0.77086:  38%|███▊      | 19/50 [03:47<04:29,  8.70s/it]

[I 2025-12-02 02:54:06,981] Trial 19 finished with value: 0.7182284980744544 and parameters: {'max_depth': 5, 'learning_rate': 0.16955288959848105, 'n_estimators': 537, 'subsample': 0.5973157936126724, 'colsample_bytree': 0.9774732208876152, 'min_child_weight': 7, 'gamma': 4.172104130105058, 'reg_alpha': 0.000920689180209425, 'reg_lambda': 0.09664313521199835, 'max_delta_step': 0}. Best is trial 9 with value: 0.7708600770218228.

Best trial: 9. Best value: 0.77086:  40%|████      | 20/50 [03:48<03:11,  6.40s/it]

[I 2025-12-02 02:54:08,005] Trial 16 finished with value: 0.7567394094993581 and parameters: {'max_depth': 5, 'learning_rate': 0.10858325405378111, 'n_estimators': 683, 'subsample': 0.6207189803706917, 'colsample_bytree': 0.9820331742269217, 'min_child_weight': 3, 'gamma': 4.960346091963485, 'reg_alpha': 8.041409299966041, 'reg_lambda': 0.029020662111507597, 'max_delta_step': 5}. Best is trial 9 with value: 0.7708600770218228.

Best trial: 9. Best value: 0.77086:  42%|████▏     | 21/50 [03:54<03:03,  6.32s/it]

[I 2025-12-02 02:54:14,149] Trial 21 pruned.

Best trial: 9. Best value: 0.77086:  44%|████▍     | 22/50 [03:55<02:11,  4.71s/it]

[I 2025-12-02 02:54:15,093] Trial 22 pruned.

Best trial: 9. Best value: 0.77086:  46%|████▌     | 23/50 [04:21<04:59, 11.08s/it]

[I 2025-12-02 02:54:41,042] Trial 24 pruned.

Best trial: 9. Best value: 0.77086:  48%|████▊     | 24/50 [04:22<03:27,  7.97s/it]

[I 2025-12-02 02:54:41,772] Trial 18 finished with value: 0.6553273427471117 and parameters: {'max_depth': 5, 'learning_rate': 0.14139479327509738, 'n_estimators': 1488, 'subsample': 0.6189400748444066, 'colsample_bytree': 0.997602229139563, 'min_child_weight': 7, 'gamma': 4.24652127830417, 'reg_alpha': 6.910462149775835, 'reg_lambda': 0.11284137966919294, 'max_delta_step': 0}. Best is trial 9 with value: 0.7708600770218228.

Best trial: 9. Best value: 0.77086:  50%|█████     | 25/50 [04:45<05:14, 12.59s/it]

[I 2025-12-02 02:55:05,132] Trial 25 finished with value: 0.7445442875481387 and parameters: {'max_depth': 5, 'learning_rate': 0.06848990655634489, 'n_estimators': 886, 'subsample': 0.5670218339644306, 'colsample_bytree': 0.9095256606920612, 'min_child_weight': 3, 'gamma': 4.21611177591619, 'reg_alpha': 0.4556022199022924, 'reg_lambda': 0.0023469308146598965, 'max_delta_step': 4}. Best is trial 9 with value: 0.7708600770218228.

Best trial: 9. Best value: 0.77086:  52%|█████▏    | 26/50 [04:50<04:05, 10.22s/it]

[I 2025-12-02 02:55:09,819] Trial 28 pruned.

Best trial: 9. Best value: 0.77086:  54%|█████▍    | 27/50 [04:56<03:25,  8.92s/it]

[I 2025-12-02 02:55:15,716] Trial 29 pruned.

Best trial: 9. Best value: 0.77086:  56%|█████▌    | 28/50 [04:56<02:19,  6.32s/it]

[I 2025-12-02 02:55:15,975] Trial 26 finished with value: 0.7445442875481387 and parameters: {'max_depth': 7, 'learning_rate': 0.1263007867047155, 'n_estimators': 643, 'subsample': 0.569796492786718, 'colsample_bytree': 0.614280570766522, 'min_child_weight': 4, 'gamma': 3.337215618457787, 'reg_alpha': 0.359399837459526, 'reg_lambda': 7.74694663668972, 'max_delta_step': 8}. Best is trial 9 with value: 0.7708600770218228.

Best trial: 9. Best value: 0.77086:  58%|█████▊    | 29/50 [04:59<01:48,  5.19s/it]

[I 2025-12-02 02:55:18,509] Trial 31 pruned.

Best trial: 9. Best value: 0.77086:  60%|██████    | 30/50 [05:01<01:23,  4.19s/it]

[I 2025-12-02 02:55:20,366] Trial 27 finished with value: 0.7445442875481387 and parameters: {'max_depth': 3, 'learning_rate': 0.1222226520370458, 'n_estimators': 627, 'subsample': 0.5520204713102447, 'colsample_bytree': 0.9398155820613382, 'min_child_weight': 4, 'gamma': 2.210386588471426, 'reg_alpha': 0.3904754461771906, 'reg_lambda': 9.630428017888649, 'max_delta_step': 8}. Best is trial 9 with value: 0.7708600770218228.

Best trial: 9. Best value: 0.77086:  62%|██████▏   | 31/50 [05:04<01:15,  3.98s/it]

[I 2025-12-02 02:55:23,871] Trial 30 pruned.

Best trial: 9. Best value: 0.77086:  64%|██████▍   | 32/50 [05:10<01:23,  4.64s/it]

[I 2025-12-02 02:55:30,055] Trial 32 pruned.

Best trial: 9. Best value: 0.77086:  66%|██████▌   | 33/50 [05:12<01:03,  3.76s/it]

[I 2025-12-02 02:55:31,761] Trial 23 finished with value: 0.7567394094993581 and parameters: {'max_depth': 4, 'learning_rate': 0.07884030269123027, 'n_estimators': 1456, 'subsample': 0.8419650382470866, 'colsample_bytree': 0.7813844799273175, 'min_child_weight': 3, 'gamma': 2.847593034338337, 'reg_alpha': 0.006680280423366483, 'reg_lambda': 0.701333079014218, 'max_delta_step': 7}. Best is trial 9 with value: 0.7708600770218228.

Best trial: 9. Best value: 0.77086:  68%|██████▊   | 34/50 [05:14<00:52,  3.30s/it]

[I 2025-12-02 02:55:33,970] Trial 33 pruned.

Best trial: 9. Best value: 0.77086:  70%|███████   | 35/50 [05:22<01:09,  4.66s/it]

[I 2025-12-02 02:55:41,827] Trial 35 pruned.

Best trial: 9. Best value: 0.77086:  72%|███████▏  | 36/50 [05:27<01:04,  4.63s/it]

[I 2025-12-02 02:55:46,390] Trial 36 pruned.

Best trial: 9. Best value: 0.77086:  74%|███████▍  | 37/50 [05:33<01:06,  5.09s/it]

[I 2025-12-02 02:55:52,556] Trial 38 pruned.

Best trial: 9. Best value: 0.77086:  76%|███████▌  | 38/50 [05:38<01:02,  5.17s/it]

[I 2025-12-02 02:55:57,891] Trial 39 pruned.

Best trial: 9. Best value: 0.77086:  78%|███████▊  | 39/50 [05:44<00:58,  5.33s/it]

[I 2025-12-02 02:56:03,603] Trial 40 pruned.

Best trial: 9. Best value: 0.77086:  80%|████████  | 40/50 [06:01<01:27,  8.76s/it]

[I 2025-12-02 02:56:20,364] Trial 42 pruned.

Best trial: 9. Best value: 0.77086:  82%|████████▏ | 41/50 [06:04<01:05,  7.30s/it]

[I 2025-12-02 02:56:24,251] Trial 43 pruned.

Best trial: 9. Best value: 0.77086:  84%|████████▍ | 42/50 [06:13<01:01,  7.71s/it]

[I 2025-12-02 02:56:32,912] Trial 34 finished with value: 0.7586649550706033 and parameters: {'max_depth': 9, 'learning_rate': 0.031793179136432426, 'n_estimators': 1171, 'subsample': 0.5248385214187574, 'colsample_bytree': 0.8515761988889824, 'min_child_weight': 5, 'gamma': 3.8241396276884005, 'reg_alpha': 4.2273770487880345e-05, 'reg_lambda': 2.1444227037586616e-06, 'max_delta_step': 1}. Best is trial 9 with value: 0.7708600770218228.

Best trial: 37. Best value: 0.783055:  86%|████████▌ | 43/50 [06:45<01:45, 15.02s/it]

[I 2025-12-02 02:57:04,993] Trial 37 finished with value: 0.7830551989730423 and parameters: {'max_depth': 4, 'learning_rate': 0.012769246893732294, 'n_estimators': 1365, 'subsample': 0.8855497755198734, 'colsample_bytree': 0.734790614827665, 'min_child_weight': 5, 'gamma': 3.831243570029578, 'reg_alpha': 0.02572003690966299, 'reg_lambda': 0.06974077019345333, 'max_delta_step': 9}. Best is trial 37 with value: 0.7830551989730423.

Best trial: 37. Best value: 0.783055:  88%|████████▊ | 44/50 [07:10<01:47, 17.86s/it]

[I 2025-12-02 02:57:29,497] Trial 44 finished with value: 0.7708600770218228 and parameters: {'max_depth': 10, 'learning_rate': 0.028808264800170305, 'n_estimators': 1211, 'subsample': 0.5378542388240561, 'colsample_bytree': 0.8139315501433737, 'min_child_weight': 5, 'gamma': 2.590326639020517, 'reg_alpha': 3.094104713635437e-07, 'reg_lambda': 2.905972540404179e-06, 'max_delta_step': 3}. Best is trial 37 with value: 0.7830551989730423.

Best trial: 45. Best value: 0.797176:  90%|█████████ | 45/50 [07:23<01:22, 16.54s/it]

[I 2025-12-02 02:57:42,932] Trial 45 finished with value: 0.7971758664955071 and parameters: {'max_depth': 9, 'learning_rate': 0.031133452964654796, 'n_estimators': 1277, 'subsample': 0.5300732817254972, 'colsample_bytree': 0.7923726358823289, 'min_child_weight': 4, 'gamma': 2.5373434508436703, 'reg_alpha': 5.203784689878212e-07, 'reg_lambda': 1.3614478299585404e-06, 'max_delta_step': 3}. Best is trial 45 with value: 0.7971758664955071.

Best trial: 45. Best value: 0.797176:  92%|█████████▏| 46/50 [07:30<00:54, 13.67s/it]

[I 2025-12-02 02:57:49,913] Trial 41 finished with value: 0.7830551989730423 and parameters: {'max_depth': 5, 'learning_rate': 0.01487027828634206, 'n_estimators': 1143, 'subsample': 0.7351441392524332, 'colsample_bytree': 0.7004935082281893, 'min_child_weight': 3, 'gamma': 1.5481677314110431, 'reg_alpha': 1.6436859681914742, 'reg_lambda': 2.040982707214571, 'max_delta_step': 6}. Best is trial 45 with value: 0.7971758664955071.

Best trial: 45. Best value: 0.797176:  94%|█████████▍| 47/50 [08:02<00:57, 19.20s/it]

[I 2025-12-02 02:58:22,006] Trial 46 finished with value: 0.7830551989730423 and parameters: {'max_depth': 9, 'learning_rate': 0.02256478061990058, 'n_estimators': 1280, 'subsample': 0.939289589402401, 'colsample_bytree': 0.8061040346176327, 'min_child_weight': 5, 'gamma': 2.60347601598648, 'reg_alpha': 0.0023142993024871947, 'reg_lambda': 1.3166900768806878e-07, 'max_delta_step': 9}. Best is trial 45 with value: 0.7971758664955071.

Best trial: 45. Best value: 0.797176:  96%|█████████▌| 48/50 [08:20<00:37, 18.92s/it]

[I 2025-12-02 02:58:40,299] Trial 47 finished with value: 0.7708600770218228 and parameters: {'max_depth': 10, 'learning_rate': 0.01448399451271119, 'n_estimators': 1308, 'subsample': 0.5409218233278789, 'colsample_bytree': 0.8239593413944805, 'min_child_weight': 5, 'gamma': 2.4799175359877763, 'reg_alpha': 1.759520779663721e-07, 'reg_lambda': 8.328996707313574e-08, 'max_delta_step': 3}. Best is trial 45 with value: 0.7971758664955071.

Best trial: 45. Best value: 0.797176:  98%|█████████▊| 49/50 [08:28<00:15, 15.44s/it]

[I 2025-12-02 02:58:47,620] Trial 48 finished with value: 0.7586649550706033 and parameters: {'max_depth': 10, 'learning_rate': 0.016786623060608803, 'n_estimators': 1264, 'subsample': 0.530819839152471, 'colsample_bytree': 0.8150781376772682, 'min_child_weight': 5, 'gamma': 2.4569331438317765, 'reg_alpha': 3.9255269495434454e-07, 'reg_lambda': 4.952732797664915e-07, 'max_delta_step': 3}. Best is trial 45 with value: 0.7971758664955071.

Best trial: 45. Best value: 0.797176: 100%|██████████| 50/50 [08:48<00:00, 10.56s/it]

[I 2025-12-02 02:59:07,357] Trial 49 finished with value: 0.7952503209242618 and parameters: {'max_depth': 10, 'learning_rate': 0.014943729728462888, 'n_estimators': 1310, 'subsample': 0.9430784629048479, 'colsample_bytree': 0.8106659521502384, 'min_child_weight': 4, 'gamma': 2.452135010300031, 'reg_alpha': 1.2087663435595871e-07, 'reg_lambda': 3.497515000823501e-07, 'max_delta_step': 9}. Best is trial 45 with value: 0.7971758664955071.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.742619                    0.75          0.76
1    17_1         loo       0.797176                    0.55          0.66
2     9_1         loo       0.730921                    0.50          0.55
3    19_1         loo       0.925000                    0.45          0.59

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.533002               0.6               0.9        50          60
1  0.100000               0.4               0.7        50          60
2  0.000000               0.8               0.2        50          59
3 -0.094491               0.4               0.5        50          59

   test_size
0         15
1         15
2         15
3         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.742619                    0.75          0.76
1    17_1         loo       0.797176                    0.55          0.66
2     9_1         loo       0.730921                    0.50          0.55
3    19_1         loo       0.925000                    0.45          0.59

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.533002               0.6               0.9        50          60
1  0.100000               0.4               0.7        50          60
2  0.000000               0.8               0.2        50          59
3 -0.094491               0.4               0.5        50          59

   test_size
0         15
1         15
2         15
3         15

In [ ]:

datasets = task_hf_compensated_temp_emb_lbl_pd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_pd_hc_{CV_STRATEGY}_tasks/xgb_results_handcrafted_temp_emb_pd_hc_extended_{CV_STRATEGY}_tasks",
    split_param= "diagnosis_y",
)
print(summary)

[I 2025-12-02 02:59:13,623] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.475:   2%|▏         | 1/50 [00:16<13:13, 16.20s/it]

[I 2025-12-02 02:59:29,814] Trial 2 finished with value: 0.475 and parameters: {'max_depth': 8, 'learning_rate': 0.028441799768931054, 'n_estimators': 375, 'subsample': 0.6456923805931741, 'colsample_bytree': 0.9446870752732329, 'min_child_weight': 9, 'gamma': 2.3169775478820656, 'reg_alpha': 0.001291112079017021, 'reg_lambda': 2.7502060502702225e-08, 'max_delta_step': 9}. Best is trial 2 with value: 0.475.

Best trial: 1. Best value: 0.676974:   4%|▍         | 2/50 [00:29<11:27, 14.33s/it]

[I 2025-12-02 02:59:42,831] Trial 1 finished with value: 0.6769736842105263 and parameters: {'max_depth': 4, 'learning_rate': 0.011257548414258389, 'n_estimators': 641, 'subsample': 0.6061540649625761, 'colsample_bytree': 0.6437269786800974, 'min_child_weight': 6, 'gamma': 3.5618625507617567, 'reg_alpha': 1.6437721264267234e-08, 'reg_lambda': 0.03016286982264695, 'max_delta_step': 8}. Best is trial 1 with value: 0.6769736842105263.

Best trial: 1. Best value: 0.676974:   6%|▌         | 3/50 [00:32<07:15,  9.28s/it]

[I 2025-12-02 02:59:46,099] Trial 4 finished with value: 0.6256578947368421 and parameters: {'max_depth': 8, 'learning_rate': 0.21406591519491983, 'n_estimators': 370, 'subsample': 0.8106183854635398, 'colsample_bytree': 0.7802775221977623, 'min_child_weight': 7, 'gamma': 1.6455019248379643, 'reg_alpha': 0.4179184042818184, 'reg_lambda': 1.4345143947608979e-06, 'max_delta_step': 9}. Best is trial 1 with value: 0.6769736842105263.

Best trial: 1. Best value: 0.676974:   8%|▊         | 4/50 [00:36<05:22,  7.01s/it]

[I 2025-12-02 02:59:49,620] Trial 3 finished with value: 0.6631578947368422 and parameters: {'max_depth': 3, 'learning_rate': 0.02570391239844822, 'n_estimators': 779, 'subsample': 0.5700852418219459, 'colsample_bytree': 0.9260512328221222, 'min_child_weight': 5, 'gamma': 4.257365819444735, 'reg_alpha': 0.2318490815695742, 'reg_lambda': 3.9521171933786524e-07, 'max_delta_step': 5}. Best is trial 1 with value: 0.6769736842105263.

Best trial: 1. Best value: 0.676974:  10%|█         | 5/50 [00:46<06:12,  8.28s/it]

[I 2025-12-02 03:00:00,147] Trial 0 finished with value: 0.6368421052631579 and parameters: {'max_depth': 6, 'learning_rate': 0.03505877071670635, 'n_estimators': 913, 'subsample': 0.8505507995138213, 'colsample_bytree': 0.5808541353257655, 'min_child_weight': 2, 'gamma': 2.610051215138387, 'reg_alpha': 0.002871115987560094, 'reg_lambda': 4.9116425997998545e-08, 'max_delta_step': 6}. Best is trial 1 with value: 0.6769736842105263.

Best trial: 5. Best value: 0.715789:  12%|█▏        | 6/50 [00:55<06:19,  8.62s/it]

[I 2025-12-02 03:00:09,435] Trial 5 finished with value: 0.7157894736842105 and parameters: {'max_depth': 4, 'learning_rate': 0.18533849911561895, 'n_estimators': 738, 'subsample': 0.7807148734960799, 'colsample_bytree': 0.5595124947710721, 'min_child_weight': 6, 'gamma': 0.4526360828164133, 'reg_alpha': 0.7396104038350018, 'reg_lambda': 0.013137745208220055, 'max_delta_step': 5}. Best is trial 5 with value: 0.7157894736842105.

Best trial: 5. Best value: 0.715789:  14%|█▍        | 7/50 [00:58<04:41,  6.54s/it]

[I 2025-12-02 03:00:11,703] Trial 7 finished with value: 0.6769736842105263 and parameters: {'max_depth': 8, 'learning_rate': 0.07111060356105887, 'n_estimators': 440, 'subsample': 0.9164532597270507, 'colsample_bytree': 0.9179161694909397, 'min_child_weight': 3, 'gamma': 0.6646984040291076, 'reg_alpha': 3.4419086561470564e-06, 'reg_lambda': 0.0038729384060609976, 'max_delta_step': 8}. Best is trial 5 with value: 0.7157894736842105.

Best trial: 5. Best value: 0.715789:  16%|█▌        | 8/50 [01:10<05:57,  8.51s/it]

[I 2025-12-02 03:00:24,426] Trial 8 finished with value: 0.6394736842105263 and parameters: {'max_depth': 6, 'learning_rate': 0.05890326089513692, 'n_estimators': 650, 'subsample': 0.5423567617021363, 'colsample_bytree': 0.8450344260357524, 'min_child_weight': 7, 'gamma': 0.38377432753190777, 'reg_alpha': 4.175661615901626e-06, 'reg_lambda': 1.3162505306079047e-07, 'max_delta_step': 6}. Best is trial 5 with value: 0.7157894736842105.

Best trial: 5. Best value: 0.715789:  18%|█▊        | 9/50 [01:15<05:04,  7.43s/it]

[I 2025-12-02 03:00:29,480] Trial 10 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.010335881950325447, 'n_estimators': 477, 'subsample': 0.8782614451356019, 'colsample_bytree': 0.7828062469512483, 'min_child_weight': 10, 'gamma': 3.420120181790616, 'reg_alpha': 1.2949352428692235e-05, 'reg_lambda': 0.013346112396834626, 'max_delta_step': 8}. Best is trial 5 with value: 0.7157894736842105.

Best trial: 5. Best value: 0.715789:  20%|██        | 10/50 [01:21<04:39,  6.98s/it]

[I 2025-12-02 03:00:35,448] Trial 6 finished with value: 0.5717105263157894 and parameters: {'max_depth': 10, 'learning_rate': 0.0122728349822335, 'n_estimators': 495, 'subsample': 0.9614552810255022, 'colsample_bytree': 0.6448784546213167, 'min_child_weight': 1, 'gamma': 2.1260261382775614, 'reg_alpha': 0.006448386533330645, 'reg_lambda': 8.84137703861683e-05, 'max_delta_step': 10}. Best is trial 5 with value: 0.7157894736842105.

Best trial: 5. Best value: 0.715789:  22%|██▏       | 11/50 [01:27<04:18,  6.63s/it]

[I 2025-12-02 03:00:41,302] Trial 9 pruned.

Best trial: 5. Best value: 0.715789:  24%|██▍       | 12/50 [01:29<03:20,  5.27s/it]

[I 2025-12-02 03:00:43,449] Trial 11 finished with value: 0.6756578947368421 and parameters: {'max_depth': 4, 'learning_rate': 0.022305865713824143, 'n_estimators': 238, 'subsample': 0.6308538348883965, 'colsample_bytree': 0.5286538168820758, 'min_child_weight': 2, 'gamma': 1.9894291862481799, 'reg_alpha': 2.201530524978493e-05, 'reg_lambda': 0.043659040958930195, 'max_delta_step': 9}. Best is trial 5 with value: 0.7157894736842105.

Best trial: 5. Best value: 0.715789:  26%|██▌       | 13/50 [01:35<03:19,  5.39s/it]

[I 2025-12-02 03:00:49,129] Trial 14 pruned.

Best trial: 5. Best value: 0.715789:  28%|██▊       | 14/50 [01:57<06:16, 10.45s/it]

[I 2025-12-02 03:01:11,251] Trial 16 pruned.

Best trial: 5. Best value: 0.715789:  30%|███       | 15/50 [02:03<05:13,  8.96s/it]

[I 2025-12-02 03:01:16,758] Trial 12 finished with value: 0.7019736842105263 and parameters: {'max_depth': 7, 'learning_rate': 0.015560492210268369, 'n_estimators': 936, 'subsample': 0.6689380156988466, 'colsample_bytree': 0.6766352796124343, 'min_child_weight': 4, 'gamma': 3.8437751474758124, 'reg_alpha': 0.07227450730746995, 'reg_lambda': 0.0019987746266028695, 'max_delta_step': 10}. Best is trial 5 with value: 0.7157894736842105.

Best trial: 5. Best value: 0.715789:  32%|███▏      | 16/50 [02:14<05:25,  9.57s/it]

[I 2025-12-02 03:01:27,760] Trial 18 pruned.

Best trial: 15. Best value: 0.742105:  34%|███▍      | 17/50 [02:16<04:01,  7.33s/it]

[I 2025-12-02 03:01:29,868] Trial 15 finished with value: 0.7421052631578948 and parameters: {'max_depth': 4, 'learning_rate': 0.2574929404828638, 'n_estimators': 1042, 'subsample': 0.7335240664648845, 'colsample_bytree': 0.6201459937850669, 'min_child_weight': 5, 'gamma': 4.526367878957695, 'reg_alpha': 1.2679085817155522e-07, 'reg_lambda': 9.331655000204819, 'max_delta_step': 2}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  36%|███▌      | 18/50 [02:20<03:24,  6.40s/it]

[I 2025-12-02 03:01:34,122] Trial 13 finished with value: 0.6894736842105263 and parameters: {'max_depth': 4, 'learning_rate': 0.26431132915962374, 'n_estimators': 1375, 'subsample': 0.7218821154092144, 'colsample_bytree': 0.5574086374779106, 'min_child_weight': 4, 'gamma': 1.0019108619027983, 'reg_alpha': 3.88821618871298, 'reg_lambda': 0.8865420258605566, 'max_delta_step': 1}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  38%|███▊      | 19/50 [02:27<03:22,  6.53s/it]

[I 2025-12-02 03:01:40,951] Trial 17 finished with value: 0.6769736842105263 and parameters: {'max_depth': 5, 'learning_rate': 0.10901302500388152, 'n_estimators': 622, 'subsample': 0.6765267787075654, 'colsample_bytree': 0.7119949994829092, 'min_child_weight': 6, 'gamma': 1.0599232652223733, 'reg_alpha': 3.0712007909404013, 'reg_lambda': 0.6614687380210318, 'max_delta_step': 4}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  40%|████      | 20/50 [02:47<05:19, 10.65s/it]

[I 2025-12-02 03:02:01,211] Trial 21 pruned.

Best trial: 15. Best value: 0.742105:  42%|████▏     | 21/50 [03:08<06:35, 13.65s/it]

[I 2025-12-02 03:02:21,842] Trial 19 finished with value: 0.7032894736842106 and parameters: {'max_depth': 7, 'learning_rate': 0.0995192198388004, 'n_estimators': 1146, 'subsample': 0.7771749826216445, 'colsample_bytree': 0.5718972349452035, 'min_child_weight': 8, 'gamma': 1.285893515545844, 'reg_alpha': 7.250173459929093, 'reg_lambda': 0.9985511515198979, 'max_delta_step': 2}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  44%|████▍     | 22/50 [03:23<06:37, 14.20s/it]

[I 2025-12-02 03:02:37,320] Trial 20 finished with value: 0.6644736842105263 and parameters: {'max_depth': 3, 'learning_rate': 0.16776587384927347, 'n_estimators': 1480, 'subsample': 0.8064452392866198, 'colsample_bytree': 0.5803624832797943, 'min_child_weight': 9, 'gamma': 1.330858132924933, 'reg_alpha': 3.393715849187208e-07, 'reg_lambda': 5.726771285213556, 'max_delta_step': 0}. Best is trial 15 with value: 0.7421052631578948.
[I 2025-12-02 03:02:37,341] Trial 22 finished with value: 0.6921052631578948 and parameters: {'max_depth': 3, 'learning_rate': 0.1722107599574984, 'n_estimators': 1212, 'subsample': 0.8032784001601688, 'colsample_bytree': 0.5825517695382836, 'min_child_weight': 9, 'gamma': 4.898141538416645, 'reg_alpha': 3.5233175192594315e-07, 'reg_lambda': 7.963185778275212, 'max_delta_step': 0}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  48%|████▊     | 24/50 [03:29<03:55,  9.05s/it]

[I 2025-12-02 03:02:43,410] Trial 25 pruned.

Best trial: 15. Best value: 0.742105:  50%|█████     | 25/50 [03:56<05:34, 13.36s/it]

[I 2025-12-02 03:03:09,851] Trial 23 finished with value: 0.6769736842105263 and parameters: {'max_depth': 5, 'learning_rate': 0.19185455869125964, 'n_estimators': 1494, 'subsample': 0.8111819526798882, 'colsample_bytree': 0.6010705406066088, 'min_child_weight': 8, 'gamma': 4.42773603253738, 'reg_alpha': 2.921347844406646e-07, 'reg_lambda': 1.1233937325759966e-05, 'max_delta_step': 3}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  52%|█████▏    | 26/50 [04:00<04:24, 11.02s/it]

[I 2025-12-02 03:03:14,267] Trial 26 finished with value: 0.7032894736842106 and parameters: {'max_depth': 5, 'learning_rate': 0.08361004477486117, 'n_estimators': 776, 'subsample': 0.8467018816896063, 'colsample_bytree': 0.5015154980696896, 'min_child_weight': 8, 'gamma': 2.6596956307519304, 'reg_alpha': 0.813109232029542, 'reg_lambda': 0.2283046114012735, 'max_delta_step': 2}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  54%|█████▍    | 27/50 [04:16<04:43, 12.34s/it]

[I 2025-12-02 03:03:30,135] Trial 24 finished with value: 0.7171052631578947 and parameters: {'max_depth': 5, 'learning_rate': 0.1805343698412048, 'n_estimators': 1483, 'subsample': 0.8032391611211204, 'colsample_bytree': 0.5978912957700503, 'min_child_weight': 8, 'gamma': 1.437373999229244, 'reg_alpha': 2.250534297438824e-07, 'reg_lambda': 0.658180772415158, 'max_delta_step': 2}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  56%|█████▌    | 28/50 [04:18<03:24,  9.31s/it]

[I 2025-12-02 03:03:31,651] Trial 27 finished with value: 0.7157894736842105 and parameters: {'max_depth': 9, 'learning_rate': 0.21168348410109503, 'n_estimators': 1028, 'subsample': 0.7719340073160585, 'colsample_bytree': 0.6199456992837992, 'min_child_weight': 6, 'gamma': 2.79528946705301, 'reg_alpha': 0.0003863023647047668, 'reg_lambda': 0.15657516479867611, 'max_delta_step': 3}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  58%|█████▊    | 29/50 [04:25<03:02,  8.69s/it]

[I 2025-12-02 03:03:38,788] Trial 31 pruned.

Best trial: 15. Best value: 0.742105:  60%|██████    | 30/50 [04:32<02:45,  8.28s/it]

[I 2025-12-02 03:03:46,081] Trial 32 pruned.

Best trial: 15. Best value: 0.742105:  62%|██████▏   | 31/50 [04:45<03:02,  9.62s/it]

[I 2025-12-02 03:03:58,935] Trial 28 finished with value: 0.6894736842105263 and parameters: {'max_depth': 9, 'learning_rate': 0.07942457043849348, 'n_estimators': 1064, 'subsample': 0.7691423314351725, 'colsample_bytree': 0.5465356017606793, 'min_child_weight': 6, 'gamma': 2.7905526046336373, 'reg_alpha': 0.00034236059493158137, 'reg_lambda': 0.14068108190834666, 'max_delta_step': 2}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  64%|██████▍   | 32/50 [04:50<02:31,  8.43s/it]

[I 2025-12-02 03:04:04,504] Trial 29 finished with value: 0.7019736842105263 and parameters: {'max_depth': 9, 'learning_rate': 0.04962500292133583, 'n_estimators': 1073, 'subsample': 0.7649753184603009, 'colsample_bytree': 0.5488434254077936, 'min_child_weight': 6, 'gamma': 1.6013700228086918, 'reg_alpha': 0.00017323757931668956, 'reg_lambda': 2.392511551846138, 'max_delta_step': 3}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  66%|██████▌   | 33/50 [05:03<02:46,  9.78s/it]

[I 2025-12-02 03:04:17,512] Trial 30 finished with value: 0.6894736842105263 and parameters: {'max_depth': 6, 'learning_rate': 0.23480252996619735, 'n_estimators': 1020, 'subsample': 0.9737232450358624, 'colsample_bytree': 0.6353626928482267, 'min_child_weight': 6, 'gamma': 1.6297216799437515, 'reg_alpha': 0.00017582491530751412, 'reg_lambda': 0.07349501632689469, 'max_delta_step': 6}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  68%|██████▊   | 34/50 [05:12<02:32,  9.53s/it]

[I 2025-12-02 03:04:26,432] Trial 35 pruned.

Best trial: 15. Best value: 0.742105:  70%|███████   | 35/50 [05:17<02:01,  8.11s/it]

[I 2025-12-02 03:04:31,200] Trial 33 finished with value: 0.6519736842105264 and parameters: {'max_depth': 4, 'learning_rate': 0.1279759075191033, 'n_estimators': 951, 'subsample': 0.6910767130892737, 'colsample_bytree': 0.7668032835013939, 'min_child_weight': 7, 'gamma': 2.9752655750797645, 'reg_alpha': 9.144454081729543e-08, 'reg_lambda': 0.0005179233563132586, 'max_delta_step': 4}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  72%|███████▏  | 36/50 [05:29<02:11,  9.36s/it]

[I 2025-12-02 03:04:43,510] Trial 34 finished with value: 0.6269736842105263 and parameters: {'max_depth': 9, 'learning_rate': 0.21900477620381112, 'n_estimators': 969, 'subsample': 0.7319995626137527, 'colsample_bytree': 0.6111678941743659, 'min_child_weight': 6, 'gamma': 2.9601490275676756, 'reg_alpha': 7.37883035180905e-05, 'reg_lambda': 0.11669800483929618, 'max_delta_step': 4}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  74%|███████▍  | 37/50 [05:35<01:47,  8.23s/it]

[I 2025-12-02 03:04:49,097] Trial 36 finished with value: 0.7296052631578948 and parameters: {'max_depth': 4, 'learning_rate': 0.13586823773584633, 'n_estimators': 676, 'subsample': 0.6972626603129277, 'colsample_bytree': 0.6168424725614795, 'min_child_weight': 7, 'gamma': 3.0083167736373255, 'reg_alpha': 0.00188079411149166, 'reg_lambda': 0.01092515973231526, 'max_delta_step': 4}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  76%|███████▌  | 38/50 [05:41<01:29,  7.45s/it]

[I 2025-12-02 03:04:54,703] Trial 40 pruned.

Best trial: 15. Best value: 0.742105:  78%|███████▊  | 39/50 [05:45<01:10,  6.43s/it]

[I 2025-12-02 03:04:58,739] Trial 37 finished with value: 0.7032894736842106 and parameters: {'max_depth': 5, 'learning_rate': 0.1341938306578174, 'n_estimators': 674, 'subsample': 0.7399679324301973, 'colsample_bytree': 0.6113579685317295, 'min_child_weight': 5, 'gamma': 2.866399988318025, 'reg_alpha': 0.0025649667221302043, 'reg_lambda': 0.008102784837141797, 'max_delta_step': 1}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  80%|████████  | 40/50 [05:46<00:50,  5.06s/it]

[I 2025-12-02 03:05:00,602] Trial 41 pruned.

Best trial: 15. Best value: 0.742105:  82%|████████▏ | 41/50 [05:50<00:40,  4.52s/it]

[I 2025-12-02 03:05:03,884] Trial 38 finished with value: 0.7407894736842104 and parameters: {'max_depth': 5, 'learning_rate': 0.1911257613121277, 'n_estimators': 688, 'subsample': 0.736203604696643, 'colsample_bytree': 0.6013381590974517, 'min_child_weight': 5, 'gamma': 3.7832973639859873, 'reg_alpha': 0.0021122453025663726, 'reg_lambda': 0.014174916604630435, 'max_delta_step': 1}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  84%|████████▍ | 42/50 [05:51<00:28,  3.62s/it]

[I 2025-12-02 03:05:05,407] Trial 42 pruned.

Best trial: 15. Best value: 0.742105:  86%|████████▌ | 43/50 [05:52<00:18,  2.61s/it]

[I 2025-12-02 03:05:05,656] Trial 43 pruned.

Best trial: 15. Best value: 0.742105:  88%|████████▊ | 44/50 [06:02<00:30,  5.07s/it]

[I 2025-12-02 03:05:16,468] Trial 39 finished with value: 0.6894736842105263 and parameters: {'max_depth': 5, 'learning_rate': 0.17524044809072192, 'n_estimators': 692, 'subsample': 0.840192522882372, 'colsample_bytree': 0.6119915664033441, 'min_child_weight': 5, 'gamma': 2.248839465608591, 'reg_alpha': 0.004148444546383253, 'reg_lambda': 0.010819468195104081, 'max_delta_step': 1}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  90%|█████████ | 45/50 [06:08<00:26,  5.37s/it]

[I 2025-12-02 03:05:22,546] Trial 47 pruned.

Best trial: 15. Best value: 0.742105:  92%|█████████▏| 46/50 [06:14<00:21,  5.30s/it]

[I 2025-12-02 03:05:27,682] Trial 48 pruned.

Best trial: 15. Best value: 0.742105:  94%|█████████▍| 47/50 [06:16<00:13,  4.40s/it]

[I 2025-12-02 03:05:29,991] Trial 44 finished with value: 0.7032894736842106 and parameters: {'max_depth': 4, 'learning_rate': 0.2974321104046638, 'n_estimators': 528, 'subsample': 0.6626225553903154, 'colsample_bytree': 0.9732541621323442, 'min_child_weight': 4, 'gamma': 4.496836439464009, 'reg_alpha': 0.008137408610236669, 'reg_lambda': 0.020195783102064022, 'max_delta_step': 1}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  96%|█████████▌| 48/50 [06:18<00:07,  3.87s/it]

[I 2025-12-02 03:05:32,607] Trial 45 finished with value: 0.7144736842105264 and parameters: {'max_depth': 4, 'learning_rate': 0.24955310278520684, 'n_estimators': 561, 'subsample': 0.6683502381912908, 'colsample_bytree': 0.9713621893200034, 'min_child_weight': 4, 'gamma': 3.606263015049571, 'reg_alpha': 0.0009769168275387886, 'reg_lambda': 0.020666453454884465, 'max_delta_step': 1}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105:  98%|█████████▊| 49/50 [06:24<00:04,  4.30s/it]

[I 2025-12-02 03:05:37,910] Trial 46 finished with value: 0.7407894736842104 and parameters: {'max_depth': 4, 'learning_rate': 0.29846452812742447, 'n_estimators': 820, 'subsample': 0.8346809682430126, 'colsample_bytree': 0.6541609201602878, 'min_child_weight': 4, 'gamma': 3.6557172465997323, 'reg_alpha': 0.001165719772803294, 'reg_lambda': 0.0020883452320968523, 'max_delta_step': 1}. Best is trial 15 with value: 0.7421052631578948.

Best trial: 15. Best value: 0.742105: 100%|██████████| 50/50 [06:26<00:00,  7.73s/it]

[I 2025-12-02 03:05:40,248] Trial 49 finished with value: 0.6769736842105263 and parameters: {'max_depth': 4, 'learning_rate': 0.23236052617746877, 'n_estimators': 362, 'subsample': 0.7156973522518169, 'colsample_bytree': 0.6956736901861024, 'min_child_weight': 4, 'gamma': 3.51253192500364, 'reg_alpha': 0.09217959288471478, 'reg_lambda': 1.9362655292346236, 'max_delta_step': 3}. Best is trial 15 with value: 0.7421052631578948.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 03:05:43,108] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.677792:   2%|▏         | 1/50 [00:28<23:05, 28.28s/it]

[I 2025-12-02 03:06:11,378] Trial 1 finished with value: 0.6777920410783055 and parameters: {'max_depth': 6, 'learning_rate': 0.042883891884084736, 'n_estimators': 585, 'subsample': 0.6822584461054702, 'colsample_bytree': 0.8093802279398915, 'min_child_weight': 6, 'gamma': 4.259637811329343, 'reg_alpha': 0.04604404858168604, 'reg_lambda': 0.00013851321033112957, 'max_delta_step': 3}. Best is trial 1 with value: 0.6777920410783055.

Best trial: 1. Best value: 0.677792:   4%|▍         | 2/50 [00:44<17:02, 21.31s/it]

[I 2025-12-02 03:06:27,805] Trial 2 finished with value: 0.6636713735558408 and parameters: {'max_depth': 4, 'learning_rate': 0.10248928952836553, 'n_estimators': 764, 'subsample': 0.8584563078819808, 'colsample_bytree': 0.8874425037003832, 'min_child_weight': 2, 'gamma': 1.7560058647861876, 'reg_alpha': 0.011266711096017361, 'reg_lambda': 2.903834810900674e-07, 'max_delta_step': 3}. Best is trial 1 with value: 0.6777920410783055.

Best trial: 1. Best value: 0.677792:   6%|▌         | 3/50 [00:48<10:23, 13.26s/it]

[I 2025-12-02 03:06:31,484] Trial 4 finished with value: 0.641206675224647 and parameters: {'max_depth': 6, 'learning_rate': 0.10401641191543051, 'n_estimators': 419, 'subsample': 0.5200643425380413, 'colsample_bytree': 0.6995612622525245, 'min_child_weight': 6, 'gamma': 4.480910250674608, 'reg_alpha': 1.3341123274765707e-05, 'reg_lambda': 3.3960913185356527e-06, 'max_delta_step': 7}. Best is trial 1 with value: 0.6777920410783055.

Best trial: 1. Best value: 0.677792:   8%|▊         | 4/50 [00:52<07:18,  9.54s/it]

[I 2025-12-02 03:06:35,330] Trial 0 finished with value: 0.6392811296534018 and parameters: {'max_depth': 10, 'learning_rate': 0.14798370910617487, 'n_estimators': 1250, 'subsample': 0.5108602365569799, 'colsample_bytree': 0.5742016634928853, 'min_child_weight': 5, 'gamma': 2.754884845892999, 'reg_alpha': 5.896567217166757e-08, 'reg_lambda': 5.722734618372655e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.6777920410783055.

Best trial: 1. Best value: 0.677792:  10%|█         | 5/50 [00:56<05:48,  7.74s/it]

[I 2025-12-02 03:06:39,864] Trial 3 finished with value: 0.6777920410783055 and parameters: {'max_depth': 10, 'learning_rate': 0.06508448439345642, 'n_estimators': 1293, 'subsample': 0.7366238219291658, 'colsample_bytree': 0.7772437572619009, 'min_child_weight': 8, 'gamma': 4.495253539276046, 'reg_alpha': 3.1024362176028837e-07, 'reg_lambda': 0.16143524136439413, 'max_delta_step': 8}. Best is trial 1 with value: 0.6777920410783055.

Best trial: 1. Best value: 0.677792:  12%|█▏        | 6/50 [01:11<07:19,  9.98s/it]

[I 2025-12-02 03:06:54,212] Trial 6 finished with value: 0.6636713735558408 and parameters: {'max_depth': 8, 'learning_rate': 0.05892393556216338, 'n_estimators': 372, 'subsample': 0.540573586712036, 'colsample_bytree': 0.5645237956358575, 'min_child_weight': 2, 'gamma': 1.0485134560089282, 'reg_alpha': 1.9679592825247546e-06, 'reg_lambda': 2.2193820848483553e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.6777920410783055.

Best trial: 1. Best value: 0.677792:  14%|█▍        | 7/50 [01:30<09:15, 12.91s/it]

[I 2025-12-02 03:07:13,151] Trial 5 finished with value: 0.2631578947368421 and parameters: {'max_depth': 6, 'learning_rate': 0.136259026261064, 'n_estimators': 1029, 'subsample': 0.5388859371049245, 'colsample_bytree': 0.7628125113865322, 'min_child_weight': 10, 'gamma': 2.0576887922924842, 'reg_alpha': 3.184805531606993e-08, 'reg_lambda': 8.340342685043685e-05, 'max_delta_step': 9}. Best is trial 1 with value: 0.6777920410783055.

Best trial: 1. Best value: 0.677792:  16%|█▌        | 8/50 [01:34<07:13, 10.33s/it]

[I 2025-12-02 03:07:17,934] Trial 8 finished with value: 0.6495507060333761 and parameters: {'max_depth': 10, 'learning_rate': 0.11019848289471502, 'n_estimators': 774, 'subsample': 0.7422722698923456, 'colsample_bytree': 0.7148417046499967, 'min_child_weight': 3, 'gamma': 2.6079796010123135, 'reg_alpha': 8.48916132480291e-08, 'reg_lambda': 2.030404319938437e-08, 'max_delta_step': 5}. Best is trial 1 with value: 0.6777920410783055.

Best trial: 1. Best value: 0.677792:  18%|█▊        | 9/50 [01:44<06:52, 10.06s/it]

[I 2025-12-02 03:07:27,413] Trial 7 finished with value: 0.6777920410783055 and parameters: {'max_depth': 10, 'learning_rate': 0.11198590888212046, 'n_estimators': 1211, 'subsample': 0.8700256695407791, 'colsample_bytree': 0.5695084771298824, 'min_child_weight': 9, 'gamma': 4.61094081413477, 'reg_alpha': 9.172110567197903e-07, 'reg_lambda': 0.06319669123074088, 'max_delta_step': 3}. Best is trial 1 with value: 0.6777920410783055.

Best trial: 1. Best value: 0.677792:  20%|██        | 10/50 [02:01<08:10, 12.25s/it]

[I 2025-12-02 03:07:44,570] Trial 9 finished with value: 0.05263157894736842 and parameters: {'max_depth': 9, 'learning_rate': 0.03865283707468096, 'n_estimators': 1109, 'subsample': 0.777995568637478, 'colsample_bytree': 0.9181656680528631, 'min_child_weight': 10, 'gamma': 2.6942193541107335, 'reg_alpha': 1.9946282185779792e-08, 'reg_lambda': 5.8647308775904085e-08, 'max_delta_step': 7}. Best is trial 1 with value: 0.6777920410783055.

Best trial: 1. Best value: 0.677792:  22%|██▏       | 11/50 [02:03<05:50,  9.00s/it]

[I 2025-12-02 03:07:46,183] Trial 12 finished with value: 0.6636713735558408 and parameters: {'max_depth': 5, 'learning_rate': 0.14387603747716673, 'n_estimators': 355, 'subsample': 0.9162700563511608, 'colsample_bytree': 0.5926139826901238, 'min_child_weight': 4, 'gamma': 1.6205873552953394, 'reg_alpha': 0.7991748757011705, 'reg_lambda': 1.3714932293438175e-06, 'max_delta_step': 10}. Best is trial 1 with value: 0.6777920410783055.

Best trial: 1. Best value: 0.677792:  24%|██▍       | 12/50 [02:08<04:58,  7.86s/it]

[I 2025-12-02 03:07:51,432] Trial 11 finished with value: 0.641206675224647 and parameters: {'max_depth': 3, 'learning_rate': 0.13933410354802933, 'n_estimators': 785, 'subsample': 0.8729127678400166, 'colsample_bytree': 0.5681679526947245, 'min_child_weight': 7, 'gamma': 4.934790512434987, 'reg_alpha': 1.5404137508660137e-08, 'reg_lambda': 1.8459295890951778e-06, 'max_delta_step': 3}. Best is trial 1 with value: 0.6777920410783055.

Best trial: 1. Best value: 0.677792:  26%|██▌       | 13/50 [02:09<03:37,  5.89s/it]

[I 2025-12-02 03:07:52,803] Trial 10 finished with value: 0.6777920410783055 and parameters: {'max_depth': 3, 'learning_rate': 0.014017719001684303, 'n_estimators': 793, 'subsample': 0.6287215636042933, 'colsample_bytree': 0.9980598416317353, 'min_child_weight': 7, 'gamma': 3.792787876462353, 'reg_alpha': 0.026244558250843174, 'reg_lambda': 0.040927938730230276, 'max_delta_step': 0}. Best is trial 1 with value: 0.6777920410783055.

Best trial: 1. Best value: 0.677792:  28%|██▊       | 14/50 [02:42<08:22, 13.95s/it]

[I 2025-12-02 03:08:25,393] Trial 13 finished with value: 0.6148908857509627 and parameters: {'max_depth': 4, 'learning_rate': 0.010963470067528637, 'n_estimators': 577, 'subsample': 0.9980973363772452, 'colsample_bytree': 0.9850608019820744, 'min_child_weight': 6, 'gamma': 3.7072825497867075, 'reg_alpha': 3.970413965358636, 'reg_lambda': 9.304972452695415, 'max_delta_step': 3}. Best is trial 1 with value: 0.6777920410783055.

Best trial: 1. Best value: 0.677792:  30%|███       | 15/50 [03:05<09:44, 16.70s/it]

[I 2025-12-02 03:08:48,465] Trial 14 finished with value: 0.6777920410783055 and parameters: {'max_depth': 8, 'learning_rate': 0.013284537502386817, 'n_estimators': 1389, 'subsample': 0.6723207893584322, 'colsample_bytree': 0.8319817370199557, 'min_child_weight': 7, 'gamma': 3.782429611801426, 'reg_alpha': 0.005031295414794952, 'reg_lambda': 9.051464563533663, 'max_delta_step': 3}. Best is trial 1 with value: 0.6777920410783055.

Best trial: 1. Best value: 0.677792:  32%|███▏      | 16/50 [03:05<06:39, 11.76s/it]

[I 2025-12-02 03:08:48,747] Trial 15 finished with value: 0.5783055198973043 and parameters: {'max_depth': 8, 'learning_rate': 0.014560734767305098, 'n_estimators': 1405, 'subsample': 0.6662812593578393, 'colsample_bytree': 0.7913408289205315, 'min_child_weight': 8, 'gamma': 3.7782760028338283, 'reg_alpha': 0.002295708632154189, 'reg_lambda': 9.68407996154831, 'max_delta_step': 6}. Best is trial 1 with value: 0.6777920410783055.

Best trial: 1. Best value: 0.677792:  34%|███▍      | 17/50 [03:11<05:29,  9.99s/it]

[I 2025-12-02 03:08:54,613] Trial 16 finished with value: 0.641206675224647 and parameters: {'max_depth': 8, 'learning_rate': 0.030701007966409826, 'n_estimators': 1490, 'subsample': 0.684120742029492, 'colsample_bytree': 0.825658116729901, 'min_child_weight': 8, 'gamma': 3.7364911315945735, 'reg_alpha': 0.00036506898351456734, 'reg_lambda': 2.511921084646974, 'max_delta_step': 6}. Best is trial 1 with value: 0.6777920410783055.

Best trial: 1. Best value: 0.677792:  36%|███▌      | 18/50 [03:12<03:55,  7.37s/it]

[I 2025-12-02 03:08:55,892] Trial 18 pruned.

Best trial: 19. Best value: 0.689987:  38%|███▊      | 19/50 [03:36<06:23, 12.37s/it]

[I 2025-12-02 03:09:19,918] Trial 19 finished with value: 0.689987163029525 and parameters: {'max_depth': 7, 'learning_rate': 0.02962374703621799, 'n_estimators': 580, 'subsample': 0.7720605262634748, 'colsample_bytree': 0.6610362698308725, 'min_child_weight': 5, 'gamma': 0.40315344197625613, 'reg_alpha': 8.0540501428415e-05, 'reg_lambda': 0.0017973524777896621, 'max_delta_step': 5}. Best is trial 19 with value: 0.689987163029525.

Best trial: 19. Best value: 0.689987:  40%|████      | 20/50 [03:37<04:27,  8.92s/it]

[I 2025-12-02 03:09:20,800] Trial 21 finished with value: 0.6655969191270861 and parameters: {'max_depth': 7, 'learning_rate': 0.2776381657869762, 'n_estimators': 543, 'subsample': 0.7571154106664403, 'colsample_bytree': 0.6576022252956986, 'min_child_weight': 4, 'gamma': 0.27544007327048003, 'reg_alpha': 0.09208416437462481, 'reg_lambda': 0.00037092241386407846, 'max_delta_step': 9}. Best is trial 19 with value: 0.689987163029525.
[I 2025-12-02 03:09:20,829] Trial 20 finished with value: 0.689987163029525 and parameters: {'max_depth': 7, 'learning_rate': 0.060491352877666306, 'n_estimators': 520, 'subsample': 0.7602776293161584, 'colsample_bytree': 0.6639488504024292, 'min_child_weight': 5, 'gamma': 3.1524071156727818, 'reg_alpha': 4.748035823358955e-05, 'reg_lambda': 0.0023843156644003717, 'max_delta_step': 9}. Best is trial 19 with value: 0.689987163029525.

Best trial: 19. Best value: 0.689987:  44%|████▍     | 22/50 [03:43<02:49,  6.04s/it]

[I 2025-12-02 03:09:26,178] Trial 17 finished with value: 0.641206675224647 and parameters: {'max_depth': 8, 'learning_rate': 0.031833742760006126, 'n_estimators': 1420, 'subsample': 0.6735643082117994, 'colsample_bytree': 0.8076748014768378, 'min_child_weight': 8, 'gamma': 0.02515154716064627, 'reg_alpha': 0.0001405004686034728, 'reg_lambda': 0.004834292462508047, 'max_delta_step': 6}. Best is trial 19 with value: 0.689987163029525.

Best trial: 19. Best value: 0.689987:  46%|████▌     | 23/50 [03:52<03:06,  6.91s/it]

[I 2025-12-02 03:09:35,712] Trial 22 finished with value: 0.6777920410783055 and parameters: {'max_depth': 7, 'learning_rate': 0.022298093405013923, 'n_estimators': 201, 'subsample': 0.8128715173730714, 'colsample_bytree': 0.6500641079633438, 'min_child_weight': 5, 'gamma': 0.3183620687716669, 'reg_alpha': 0.06791196124474573, 'reg_lambda': 0.0002119188492672521, 'max_delta_step': 2}. Best is trial 19 with value: 0.689987163029525.

Best trial: 19. Best value: 0.689987:  48%|████▊     | 24/50 [03:53<02:21,  5.43s/it]

[I 2025-12-02 03:09:36,973] Trial 24 finished with value: 0.689987163029525 and parameters: {'max_depth': 6, 'learning_rate': 0.025207316294764418, 'n_estimators': 221, 'subsample': 0.8133836421003415, 'colsample_bytree': 0.6478186822412448, 'min_child_weight': 5, 'gamma': 0.27833591024002907, 'reg_alpha': 3.3468537420719694e-05, 'reg_lambda': 0.00047234904856132434, 'max_delta_step': 4}. Best is trial 19 with value: 0.689987163029525.

Best trial: 19. Best value: 0.689987:  50%|█████     | 25/50 [03:58<02:07,  5.12s/it]

[I 2025-12-02 03:09:41,250] Trial 25 finished with value: 0.6777920410783055 and parameters: {'max_depth': 6, 'learning_rate': 0.022288523319625272, 'n_estimators': 202, 'subsample': 0.7789091556156849, 'colsample_bytree': 0.651979617399712, 'min_child_weight': 5, 'gamma': 3.1824963662540604, 'reg_alpha': 1.2120460943597899e-05, 'reg_lambda': 0.00015159051207029993, 'max_delta_step': 4}. Best is trial 19 with value: 0.689987163029525.

Best trial: 19. Best value: 0.689987:  52%|█████▏    | 26/50 [04:11<02:59,  7.46s/it]

[I 2025-12-02 03:09:54,732] Trial 27 finished with value: 0.689987163029525 and parameters: {'max_depth': 5, 'learning_rate': 0.02253161690616818, 'n_estimators': 248, 'subsample': 0.7876313600443172, 'colsample_bytree': 0.5159786723389939, 'min_child_weight': 4, 'gamma': 0.8619367844918138, 'reg_alpha': 1.3667024863532077e-05, 'reg_lambda': 0.0012357166986455659, 'max_delta_step': 5}. Best is trial 19 with value: 0.689987163029525.

Best trial: 19. Best value: 0.689987:  54%|█████▍    | 27/50 [04:15<02:25,  6.34s/it]

[I 2025-12-02 03:09:58,280] Trial 23 finished with value: 0.5744544287548139 and parameters: {'max_depth': 5, 'learning_rate': 0.022995153842674972, 'n_estimators': 242, 'subsample': 0.8252328408582871, 'colsample_bytree': 0.6642414550711461, 'min_child_weight': 1, 'gamma': 0.24886626670761935, 'reg_alpha': 3.332476257952343e-05, 'reg_lambda': 0.0002412382645080595, 'max_delta_step': 4}. Best is trial 19 with value: 0.689987163029525.

Best trial: 26. Best value: 0.714377:  56%|█████▌    | 28/50 [04:17<01:56,  5.31s/it]

[I 2025-12-02 03:10:01,068] Trial 26 finished with value: 0.714377406931964 and parameters: {'max_depth': 6, 'learning_rate': 0.046451470673794966, 'n_estimators': 626, 'subsample': 0.595912707902245, 'colsample_bytree': 0.5070497663067001, 'min_child_weight': 4, 'gamma': 3.1490132614745345, 'reg_alpha': 1.7928338827942217e-05, 'reg_lambda': 4.052105340176837e-05, 'max_delta_step': 4}. Best is trial 26 with value: 0.714377406931964.

Best trial: 26. Best value: 0.714377:  58%|█████▊    | 29/50 [04:31<02:43,  7.79s/it]

[I 2025-12-02 03:10:14,845] Trial 28 finished with value: 0.6777920410783055 and parameters: {'max_depth': 5, 'learning_rate': 0.022819644138013077, 'n_estimators': 654, 'subsample': 0.8149723522746513, 'colsample_bytree': 0.5064672193268465, 'min_child_weight': 4, 'gamma': 0.9616174155209865, 'reg_alpha': 1.4483710317124821e-05, 'reg_lambda': 0.001519461796659801, 'max_delta_step': 5}. Best is trial 26 with value: 0.714377406931964.

Best trial: 26. Best value: 0.714377:  60%|██████    | 30/50 [04:43<03:00,  9.02s/it]

[I 2025-12-02 03:10:26,811] Trial 29 finished with value: 0.6636713735558408 and parameters: {'max_depth': 5, 'learning_rate': 0.06896422354427371, 'n_estimators': 494, 'subsample': 0.8259130324252648, 'colsample_bytree': 0.7037965821082317, 'min_child_weight': 1, 'gamma': 0.6643194858394419, 'reg_alpha': 0.0015568211821748068, 'reg_lambda': 2.7086246046785967e-05, 'max_delta_step': 4}. Best is trial 26 with value: 0.714377406931964.

Best trial: 26. Best value: 0.714377:  62%|██████▏   | 31/50 [04:46<02:18,  7.27s/it]

[I 2025-12-02 03:10:29,937] Trial 31 finished with value: 0.6777920410783055 and parameters: {'max_depth': 7, 'learning_rate': 0.07467149180143313, 'n_estimators': 669, 'subsample': 0.611591764411047, 'colsample_bytree': 0.5090325356030557, 'min_child_weight': 3, 'gamma': 2.2172445659032425, 'reg_alpha': 0.0009399918669938995, 'reg_lambda': 1.733924875133379e-05, 'max_delta_step': 1}. Best is trial 26 with value: 0.714377406931964.

Best trial: 26. Best value: 0.714377:  64%|██████▍   | 32/50 [04:51<01:58,  6.60s/it]

[I 2025-12-02 03:10:34,942] Trial 30 finished with value: 0.6514762516046213 and parameters: {'max_depth': 7, 'learning_rate': 0.047486931005789004, 'n_estimators': 648, 'subsample': 0.9309507245395875, 'colsample_bytree': 0.7157007053048654, 'min_child_weight': 3, 'gamma': 0.8021347877030207, 'reg_alpha': 0.0008359217668035986, 'reg_lambda': 2.2852575286556e-05, 'max_delta_step': 1}. Best is trial 26 with value: 0.714377406931964.

Best trial: 26. Best value: 0.714377:  66%|██████▌   | 33/50 [04:54<01:33,  5.53s/it]

[I 2025-12-02 03:10:37,948] Trial 32 finished with value: 0.689987163029525 and parameters: {'max_depth': 9, 'learning_rate': 0.07621352349089569, 'n_estimators': 477, 'subsample': 0.6024992638926324, 'colsample_bytree': 0.6086279631867849, 'min_child_weight': 3, 'gamma': 3.0335512620331153, 'reg_alpha': 0.0006528129787359552, 'reg_lambda': 2.2149888470977803e-05, 'max_delta_step': 1}. Best is trial 26 with value: 0.714377406931964.

Best trial: 34. Best value: 0.716303:  68%|██████▊   | 34/50 [05:09<02:11,  8.23s/it]

[I 2025-12-02 03:10:52,533] Trial 34 finished with value: 0.7163029525032092 and parameters: {'max_depth': 7, 'learning_rate': 0.046798689246802645, 'n_estimators': 445, 'subsample': 0.7150890114820457, 'colsample_bytree': 0.6126117726565098, 'min_child_weight': 5, 'gamma': 3.2357040278134126, 'reg_alpha': 2.2650874262136616e-06, 'reg_lambda': 0.011055184262076011, 'max_delta_step': 4}. Best is trial 34 with value: 0.7163029525032092.

Best trial: 34. Best value: 0.716303:  70%|███████   | 35/50 [05:14<01:50,  7.34s/it]

[I 2025-12-02 03:10:57,787] Trial 35 finished with value: 0.689987163029525 and parameters: {'max_depth': 6, 'learning_rate': 0.04955689560434372, 'n_estimators': 459, 'subsample': 0.7110595289020621, 'colsample_bytree': 0.641131469208247, 'min_child_weight': 5, 'gamma': 3.0436006585720254, 'reg_alpha': 2.7735821680763428e-06, 'reg_lambda': 0.01147563006767835, 'max_delta_step': 4}. Best is trial 34 with value: 0.7163029525032092.

Best trial: 34. Best value: 0.716303:  72%|███████▏  | 36/50 [05:17<01:24,  6.01s/it]

[I 2025-12-02 03:11:00,695] Trial 33 finished with value: 0.6392811296534018 and parameters: {'max_depth': 9, 'learning_rate': 0.046053086929934525, 'n_estimators': 669, 'subsample': 0.6134508017395807, 'colsample_bytree': 0.6106658083170139, 'min_child_weight': 3, 'gamma': 3.020962697734424, 'reg_alpha': 2.6470477929618906e-06, 'reg_lambda': 0.013347374146666681, 'max_delta_step': 2}. Best is trial 34 with value: 0.7163029525032092.

Best trial: 34. Best value: 0.716303:  74%|███████▍  | 37/50 [05:33<01:56,  8.98s/it]

[I 2025-12-02 03:11:16,620] Trial 38 finished with value: 0.6777920410783055 and parameters: {'max_depth': 7, 'learning_rate': 0.03963232942253975, 'n_estimators': 337, 'subsample': 0.7016107515809038, 'colsample_bytree': 0.6141361527671153, 'min_child_weight': 6, 'gamma': 3.3985302105914332, 'reg_alpha': 2.4583420957738085e-07, 'reg_lambda': 0.5512184775366057, 'max_delta_step': 7}. Best is trial 34 with value: 0.7163029525032092.

Best trial: 34. Best value: 0.716303:  76%|███████▌  | 38/50 [05:36<01:25,  7.16s/it]

[I 2025-12-02 03:11:19,535] Trial 36 finished with value: 0.6777920410783055 and parameters: {'max_depth': 6, 'learning_rate': 0.051706037374093204, 'n_estimators': 905, 'subsample': 0.7089235710578482, 'colsample_bytree': 0.6236579150493531, 'min_child_weight': 5, 'gamma': 1.5448528526677106, 'reg_alpha': 2.4428426792877753e-06, 'reg_lambda': 0.010317322939469839, 'max_delta_step': 4}. Best is trial 34 with value: 0.7163029525032092.

Best trial: 34. Best value: 0.716303:  78%|███████▊  | 39/50 [05:50<01:42,  9.29s/it]

[I 2025-12-02 03:11:33,775] Trial 37 finished with value: 0.689987163029525 and parameters: {'max_depth': 7, 'learning_rate': 0.05197963578189946, 'n_estimators': 882, 'subsample': 0.7136521750107064, 'colsample_bytree': 0.6243423699374433, 'min_child_weight': 6, 'gamma': 2.9952335478890935, 'reg_alpha': 2.3199001820856994e-06, 'reg_lambda': 0.01326622289130199, 'max_delta_step': 5}. Best is trial 34 with value: 0.7163029525032092.

Best trial: 34. Best value: 0.716303:  80%|████████  | 40/50 [05:57<01:26,  8.66s/it]

[I 2025-12-02 03:11:40,952] Trial 39 finished with value: 0.689987163029525 and parameters: {'max_depth': 7, 'learning_rate': 0.08475367369384075, 'n_estimators': 890, 'subsample': 0.7322377337367364, 'colsample_bytree': 0.5523547746269277, 'min_child_weight': 6, 'gamma': 2.237263918432523, 'reg_alpha': 2.778195245283803e-07, 'reg_lambda': 0.31257202929046846, 'max_delta_step': 7}. Best is trial 34 with value: 0.7163029525032092.

Best trial: 34. Best value: 0.716303:  82%|████████▏ | 41/50 [06:02<01:05,  7.31s/it]

[I 2025-12-02 03:11:45,137] Trial 43 pruned.

Best trial: 34. Best value: 0.716303:  84%|████████▍ | 42/50 [06:03<00:44,  5.57s/it]

[I 2025-12-02 03:11:46,645] Trial 41 finished with value: 0.6655969191270861 and parameters: {'max_depth': 7, 'learning_rate': 0.08835775740172205, 'n_estimators': 540, 'subsample': 0.5736403307944221, 'colsample_bytree': 0.5435037399174892, 'min_child_weight': 4, 'gamma': 2.3589103948398673, 'reg_alpha': 0.000111125456977824, 'reg_lambda': 0.0013012598297682365, 'max_delta_step': 8}. Best is trial 34 with value: 0.7163029525032092.

Best trial: 34. Best value: 0.716303:  86%|████████▌ | 43/50 [06:15<00:52,  7.52s/it]

[I 2025-12-02 03:11:58,698] Trial 40 finished with value: 0.7021822849807445 and parameters: {'max_depth': 6, 'learning_rate': 0.06024631867442372, 'n_estimators': 907, 'subsample': 0.5733366777845597, 'colsample_bytree': 0.5394658920547838, 'min_child_weight': 4, 'gamma': 2.30589795039027, 'reg_alpha': 0.00018116033843131632, 'reg_lambda': 0.0011414854759872121, 'max_delta_step': 8}. Best is trial 34 with value: 0.7163029525032092.

Best trial: 34. Best value: 0.716303:  88%|████████▊ | 44/50 [06:16<00:33,  5.62s/it]

[I 2025-12-02 03:11:59,881] Trial 42 finished with value: 0.6655969191270861 and parameters: {'max_depth': 8, 'learning_rate': 0.09342140449455888, 'n_estimators': 565, 'subsample': 0.5779917873682023, 'colsample_bytree': 0.5399772884908695, 'min_child_weight': 4, 'gamma': 2.3476635745728354, 'reg_alpha': 0.00012488446332311947, 'reg_lambda': 0.0019403871205939797, 'max_delta_step': 8}. Best is trial 34 with value: 0.7163029525032092.

Best trial: 34. Best value: 0.716303:  90%|█████████ | 45/50 [06:21<00:26,  5.25s/it]

[I 2025-12-02 03:12:04,262] Trial 44 finished with value: 0.6777920410783055 and parameters: {'max_depth': 6, 'learning_rate': 0.027451496236130055, 'n_estimators': 307, 'subsample': 0.8425209833561402, 'colsample_bytree': 0.6791613484122556, 'min_child_weight': 5, 'gamma': 3.3897664264677325, 'reg_alpha': 5.8157223415766355e-05, 'reg_lambda': 0.0005450499671501342, 'max_delta_step': 5}. Best is trial 34 with value: 0.7163029525032092.

Best trial: 34. Best value: 0.716303:  92%|█████████▏| 46/50 [06:21<00:15,  3.84s/it]

[I 2025-12-02 03:12:04,824] Trial 45 finished with value: 0.6777920410783055 and parameters: {'max_depth': 6, 'learning_rate': 0.028168971982592227, 'n_estimators': 315, 'subsample': 0.7576800489835914, 'colsample_bytree': 0.6793816539111808, 'min_child_weight': 5, 'gamma': 4.040884268862736, 'reg_alpha': 3.3048051471814007e-05, 'reg_lambda': 0.0005154267498674406, 'max_delta_step': 5}. Best is trial 34 with value: 0.7163029525032092.

Best trial: 34. Best value: 0.716303:  94%|█████████▍| 47/50 [06:30<00:16,  5.37s/it]

[I 2025-12-02 03:12:13,766] Trial 49 pruned.

Best trial: 34. Best value: 0.716303:  96%|█████████▌| 48/50 [06:43<00:15,  7.65s/it]

[I 2025-12-02 03:12:26,729] Trial 46 finished with value: 0.6636713735558408 and parameters: {'max_depth': 6, 'learning_rate': 0.06073638529122048, 'n_estimators': 707, 'subsample': 0.518373528099458, 'colsample_bytree': 0.6765085479212153, 'min_child_weight': 5, 'gamma': 1.9504932106122912, 'reg_alpha': 7.299170283901251e-06, 'reg_lambda': 0.05627777455287376, 'max_delta_step': 9}. Best is trial 34 with value: 0.7163029525032092.

Best trial: 34. Best value: 0.716303:  98%|█████████▊| 49/50 [06:50<00:07,  7.41s/it]

[I 2025-12-02 03:12:33,584] Trial 48 finished with value: 0.6148908857509627 and parameters: {'max_depth': 4, 'learning_rate': 0.06325491223563674, 'n_estimators': 737, 'subsample': 0.5242869502903835, 'colsample_bytree': 0.5863905056866066, 'min_child_weight': 2, 'gamma': 4.099088575269554, 'reg_alpha': 6.743235810849856e-06, 'reg_lambda': 0.08441192570998259, 'max_delta_step': 9}. Best is trial 34 with value: 0.7163029525032092.

Best trial: 34. Best value: 0.716303: 100%|██████████| 50/50 [06:56<00:00,  8.33s/it]

[I 2025-12-02 03:12:39,576] Trial 47 finished with value: 0.641206675224647 and parameters: {'max_depth': 6, 'learning_rate': 0.065288332557267, 'n_estimators': 1105, 'subsample': 0.5011627486769, 'colsample_bytree': 0.6796923238182206, 'min_child_weight': 2, 'gamma': 4.069990262644984, 'reg_alpha': 7.550595571182022e-06, 'reg_lambda': 0.07757773117454557, 'max_delta_step': 9}. Best is trial 34 with value: 0.7163029525032092.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 03:12:44,246] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.780921:   2%|▏         | 1/50 [00:20<16:56, 20.74s/it]

[I 2025-12-02 03:13:04,977] Trial 0 finished with value: 0.7809210526315788 and parameters: {'max_depth': 6, 'learning_rate': 0.013964082835961492, 'n_estimators': 467, 'subsample': 0.8863412072725745, 'colsample_bytree': 0.5469944224882693, 'min_child_weight': 9, 'gamma': 4.043085480386902, 'reg_alpha': 1.5988655862411782, 'reg_lambda': 2.280991147489889e-06, 'max_delta_step': 1}. Best is trial 0 with value: 0.7809210526315788.

Best trial: 0. Best value: 0.780921:   4%|▍         | 2/50 [00:32<12:10, 15.23s/it]

[I 2025-12-02 03:13:16,347] Trial 2 finished with value: 0.2125 and parameters: {'max_depth': 9, 'learning_rate': 0.03803049207617378, 'n_estimators': 746, 'subsample': 0.6110642025596908, 'colsample_bytree': 0.937753222523533, 'min_child_weight': 10, 'gamma': 3.8758070362010857, 'reg_alpha': 0.374511425737449, 'reg_lambda': 0.9593557879231001, 'max_delta_step': 5}. Best is trial 0 with value: 0.7809210526315788.

Best trial: 3. Best value: 0.844737:   6%|▌         | 3/50 [00:42<10:06, 12.91s/it]

[I 2025-12-02 03:13:26,504] Trial 3 finished with value: 0.8447368421052632 and parameters: {'max_depth': 5, 'learning_rate': 0.020930802654312682, 'n_estimators': 799, 'subsample': 0.9780379313557375, 'colsample_bytree': 0.8072384484143958, 'min_child_weight': 3, 'gamma': 1.882294934784543, 'reg_alpha': 0.00013932910815390255, 'reg_lambda': 0.000763971782033424, 'max_delta_step': 4}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:   8%|▊         | 4/50 [00:53<09:23, 12.24s/it]

[I 2025-12-02 03:13:37,717] Trial 4 finished with value: 0.7532894736842105 and parameters: {'max_depth': 3, 'learning_rate': 0.019737104308042132, 'n_estimators': 722, 'subsample': 0.5609635866448279, 'colsample_bytree': 0.9118783714296567, 'min_child_weight': 4, 'gamma': 4.8325061924301815, 'reg_alpha': 7.625934611933018e-05, 'reg_lambda': 4.5677860917184086e-08, 'max_delta_step': 9}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  10%|█         | 5/50 [00:54<06:07,  8.18s/it]

[I 2025-12-02 03:13:38,685] Trial 1 finished with value: 0.7407894736842104 and parameters: {'max_depth': 7, 'learning_rate': 0.044554484660687704, 'n_estimators': 1383, 'subsample': 0.5101050398532713, 'colsample_bytree': 0.6678835264083887, 'min_child_weight': 4, 'gamma': 3.499449293092214, 'reg_alpha': 0.03086665402029051, 'reg_lambda': 4.563565126924841e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  12%|█▏        | 6/50 [01:00<05:21,  7.31s/it]

[I 2025-12-02 03:13:44,307] Trial 6 finished with value: 0.7796052631578947 and parameters: {'max_depth': 6, 'learning_rate': 0.015127046532038993, 'n_estimators': 435, 'subsample': 0.8858530245013284, 'colsample_bytree': 0.62325930042303, 'min_child_weight': 9, 'gamma': 2.4667157392804473, 'reg_alpha': 5.715394265538936e-07, 'reg_lambda': 3.994281212620222e-06, 'max_delta_step': 8}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  14%|█▍        | 7/50 [01:09<05:45,  8.04s/it]

[I 2025-12-02 03:13:53,858] Trial 5 finished with value: 0.8447368421052632 and parameters: {'max_depth': 6, 'learning_rate': 0.013350305263950287, 'n_estimators': 448, 'subsample': 0.8054224240174476, 'colsample_bytree': 0.819472107179716, 'min_child_weight': 2, 'gamma': 0.8759791270082096, 'reg_alpha': 1.556883655218886e-05, 'reg_lambda': 1.3929878424031763e-05, 'max_delta_step': 3}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  16%|█▌        | 8/50 [01:25<07:19, 10.47s/it]

[I 2025-12-02 03:14:09,531] Trial 8 finished with value: 0.45394736842105265 and parameters: {'max_depth': 3, 'learning_rate': 0.2541857940414925, 'n_estimators': 829, 'subsample': 0.6298831255178903, 'colsample_bytree': 0.6023515509155657, 'min_child_weight': 10, 'gamma': 3.8178861731392293, 'reg_alpha': 0.8171922813716042, 'reg_lambda': 4.233142806191945, 'max_delta_step': 3}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  18%|█▊        | 9/50 [01:25<05:00,  7.33s/it]

[I 2025-12-02 03:14:09,970] Trial 7 finished with value: 0.23552631578947367 and parameters: {'max_depth': 10, 'learning_rate': 0.2112798449195982, 'n_estimators': 839, 'subsample': 0.5408744687755973, 'colsample_bytree': 0.7729079256252787, 'min_child_weight': 10, 'gamma': 1.3775411351905382, 'reg_alpha': 0.008528547523637759, 'reg_lambda': 9.243265862678941e-08, 'max_delta_step': 5}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  20%|██        | 10/50 [01:50<08:31, 12.78s/it]

[I 2025-12-02 03:14:34,941] Trial 9 finished with value: 0.8447368421052632 and parameters: {'max_depth': 8, 'learning_rate': 0.06171596771431227, 'n_estimators': 806, 'subsample': 0.7447391111017243, 'colsample_bytree': 0.7258877075985981, 'min_child_weight': 1, 'gamma': 4.255082119673176, 'reg_alpha': 6.7592938840791295, 'reg_lambda': 0.21095235967035555, 'max_delta_step': 7}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  22%|██▏       | 11/50 [01:54<06:31, 10.05s/it]

[I 2025-12-02 03:14:38,807] Trial 11 pruned.

Best trial: 3. Best value: 0.844737:  24%|██▍       | 12/50 [01:57<05:04,  8.01s/it]

[I 2025-12-02 03:14:42,138] Trial 10 pruned.

Best trial: 3. Best value: 0.844737:  26%|██▌       | 13/50 [02:12<06:09,  9.98s/it]

[I 2025-12-02 03:14:56,661] Trial 12 finished with value: 0.7796052631578947 and parameters: {'max_depth': 5, 'learning_rate': 0.21684597611131065, 'n_estimators': 1236, 'subsample': 0.9018908124075116, 'colsample_bytree': 0.7766540174402856, 'min_child_weight': 4, 'gamma': 1.6399143770094304, 'reg_alpha': 6.034116834734674e-08, 'reg_lambda': 0.030283593951349042, 'max_delta_step': 10}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  28%|██▊       | 14/50 [02:19<05:31,  9.21s/it]

[I 2025-12-02 03:15:04,076] Trial 14 finished with value: 0.8447368421052632 and parameters: {'max_depth': 5, 'learning_rate': 0.030575767671298836, 'n_estimators': 252, 'subsample': 0.7833842536485235, 'colsample_bytree': 0.8214581323623066, 'min_child_weight': 1, 'gamma': 0.25004131891597803, 'reg_alpha': 8.590841789745066e-06, 'reg_lambda': 0.006805489440689415, 'max_delta_step': 2}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 15. Best value: 0.857237:  30%|███       | 15/50 [02:24<04:37,  7.92s/it]

[I 2025-12-02 03:15:09,023] Trial 15 finished with value: 0.8572368421052632 and parameters: {'max_depth': 5, 'learning_rate': 0.02435260045500489, 'n_estimators': 263, 'subsample': 0.9847972877695798, 'colsample_bytree': 0.8353525417236167, 'min_child_weight': 1, 'gamma': 1.6056459574083521, 'reg_alpha': 1.247356361564722e-06, 'reg_lambda': 0.008107105282333445, 'max_delta_step': 0}. Best is trial 15 with value: 0.8572368421052632.

Best trial: 15. Best value: 0.857237:  32%|███▏      | 16/50 [02:35<04:54,  8.65s/it]

[I 2025-12-02 03:15:19,362] Trial 13 finished with value: 0.805921052631579 and parameters: {'max_depth': 4, 'learning_rate': 0.1070569178123102, 'n_estimators': 1182, 'subsample': 0.9826932705797501, 'colsample_bytree': 0.9935164128902985, 'min_child_weight': 6, 'gamma': 0.1521027658298637, 'reg_alpha': 1.2541002968546617e-08, 'reg_lambda': 0.007778114374043374, 'max_delta_step': 0}. Best is trial 15 with value: 0.8572368421052632.

Best trial: 15. Best value: 0.857237:  34%|███▍      | 17/50 [02:42<04:29,  8.17s/it]

[I 2025-12-02 03:15:26,418] Trial 16 finished with value: 0.8447368421052632 and parameters: {'max_depth': 5, 'learning_rate': 0.025206874347055406, 'n_estimators': 230, 'subsample': 0.7602593640579653, 'colsample_bytree': 0.8570400625022084, 'min_child_weight': 1, 'gamma': 0.010871953193587691, 'reg_alpha': 7.380341948695074e-06, 'reg_lambda': 0.0016373100609720585, 'max_delta_step': 0}. Best is trial 15 with value: 0.8572368421052632.

Best trial: 15. Best value: 0.857237:  36%|███▌      | 18/50 [03:05<06:47, 12.75s/it]

[I 2025-12-02 03:15:49,814] Trial 18 finished with value: 0.7796052631578947 and parameters: {'max_depth': 5, 'learning_rate': 0.08540384540304409, 'n_estimators': 1076, 'subsample': 0.9930934814116323, 'colsample_bytree': 0.9960564484624387, 'min_child_weight': 6, 'gamma': 2.134995909854675, 'reg_alpha': 1.153803739334361e-08, 'reg_lambda': 0.001845739214508145, 'max_delta_step': 0}. Best is trial 15 with value: 0.8572368421052632.

Best trial: 15. Best value: 0.857237:  38%|███▊      | 19/50 [03:23<07:25, 14.37s/it]

[I 2025-12-02 03:16:07,971] Trial 20 finished with value: 0.8322368421052632 and parameters: {'max_depth': 7, 'learning_rate': 0.08376089025519716, 'n_estimators': 1016, 'subsample': 0.9462067027086475, 'colsample_bytree': 0.7073270376461226, 'min_child_weight': 3, 'gamma': 2.157453026559917, 'reg_alpha': 0.0006434623387009618, 'reg_lambda': 0.00020686649974698234, 'max_delta_step': 1}. Best is trial 15 with value: 0.8572368421052632.

Best trial: 15. Best value: 0.857237:  40%|████      | 20/50 [03:26<05:23, 10.79s/it]

[I 2025-12-02 03:16:10,412] Trial 19 finished with value: 0.8572368421052632 and parameters: {'max_depth': 5, 'learning_rate': 0.02522800444231195, 'n_estimators': 1105, 'subsample': 0.9965618156739662, 'colsample_bytree': 0.8714014492502931, 'min_child_weight': 3, 'gamma': 2.135468915328898, 'reg_alpha': 0.0008006389134536906, 'reg_lambda': 0.0004953702617734712, 'max_delta_step': 0}. Best is trial 15 with value: 0.8572368421052632.

Best trial: 15. Best value: 0.857237:  42%|████▏     | 21/50 [03:31<04:21,  9.01s/it]

[I 2025-12-02 03:16:15,263] Trial 17 finished with value: 0.8572368421052632 and parameters: {'max_depth': 7, 'learning_rate': 0.010275941956338318, 'n_estimators': 1094, 'subsample': 0.9910353382016458, 'colsample_bytree': 0.9873444966997175, 'min_child_weight': 2, 'gamma': 1.2343000859271585, 'reg_alpha': 0.0010986434682538802, 'reg_lambda': 0.000273888281970724, 'max_delta_step': 0}. Best is trial 15 with value: 0.8572368421052632.

Best trial: 15. Best value: 0.857237:  44%|████▍     | 22/50 [03:43<04:40, 10.00s/it]

[I 2025-12-02 03:16:27,581] Trial 21 finished with value: 0.7921052631578948 and parameters: {'max_depth': 7, 'learning_rate': 0.01001777471440229, 'n_estimators': 572, 'subsample': 0.6948301703058198, 'colsample_bytree': 0.7045665195386632, 'min_child_weight': 3, 'gamma': 1.772437799117059, 'reg_alpha': 0.0007591986158639295, 'reg_lambda': 0.00010288377800313294, 'max_delta_step': 6}. Best is trial 15 with value: 0.8572368421052632.

Best trial: 15. Best value: 0.857237:  46%|████▌     | 23/50 [04:03<05:52, 13.04s/it]

[I 2025-12-02 03:16:47,724] Trial 22 finished with value: 0.7921052631578948 and parameters: {'max_depth': 4, 'learning_rate': 0.010476506832480505, 'n_estimators': 613, 'subsample': 0.7041807193693304, 'colsample_bytree': 0.8784788668023432, 'min_child_weight': 3, 'gamma': 1.4246582804315575, 'reg_alpha': 1.104270535785741e-06, 'reg_lambda': 0.04300795667448146, 'max_delta_step': 6}. Best is trial 15 with value: 0.8572368421052632.

Best trial: 15. Best value: 0.857237:  48%|████▊     | 24/50 [04:21<06:19, 14.60s/it]

[I 2025-12-02 03:17:05,937] Trial 23 finished with value: 0.7921052631578948 and parameters: {'max_depth': 4, 'learning_rate': 0.010153122514641715, 'n_estimators': 648, 'subsample': 0.6755412459744071, 'colsample_bytree': 0.8809406526214962, 'min_child_weight': 2, 'gamma': 1.1618793483478185, 'reg_alpha': 1.2203211992726348e-06, 'reg_lambda': 0.058050200728112664, 'max_delta_step': 1}. Best is trial 15 with value: 0.8572368421052632.

Best trial: 25. Best value: 0.883553:  50%|█████     | 25/50 [04:29<05:12, 12.52s/it]

[I 2025-12-02 03:17:13,610] Trial 25 finished with value: 0.8835526315789474 and parameters: {'max_depth': 8, 'learning_rate': 0.031294956409658896, 'n_estimators': 974, 'subsample': 0.9300189207385212, 'colsample_bytree': 0.8911563504882041, 'min_child_weight': 2, 'gamma': 0.918170322415659, 'reg_alpha': 3.292979805641504e-07, 'reg_lambda': 0.16183479734096426, 'max_delta_step': 1}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  52%|█████▏    | 26/50 [04:38<04:37, 11.55s/it]

[I 2025-12-02 03:17:22,894] Trial 24 finished with value: 0.8572368421052632 and parameters: {'max_depth': 8, 'learning_rate': 0.010469938026843349, 'n_estimators': 1005, 'subsample': 0.9177002389705584, 'colsample_bytree': 0.8680667248894676, 'min_child_weight': 2, 'gamma': 1.0819659725193362, 'reg_alpha': 0.000982475710503637, 'reg_lambda': 5.754537007940331e-05, 'max_delta_step': 1}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  54%|█████▍    | 27/50 [04:51<04:32, 11.85s/it]

[I 2025-12-02 03:17:35,433] Trial 26 finished with value: 0.8572368421052632 and parameters: {'max_depth': 8, 'learning_rate': 0.03060273851823609, 'n_estimators': 976, 'subsample': 0.919042423949396, 'colsample_bytree': 0.9398138996688301, 'min_child_weight': 2, 'gamma': 1.0866594742416391, 'reg_alpha': 0.002660996469617817, 'reg_lambda': 0.00011843345233932933, 'max_delta_step': 1}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  58%|█████▊    | 29/50 [05:15<03:47, 10.85s/it]

[I 2025-12-02 03:17:59,267] Trial 28 finished with value: 0.8572368421052632 and parameters: {'max_depth': 8, 'learning_rate': 0.03577529460274733, 'n_estimators': 959, 'subsample': 0.9270296927750745, 'colsample_bytree': 0.9651152225873098, 'min_child_weight': 2, 'gamma': 0.7791447532477872, 'reg_alpha': 3.1551856286278377e-07, 'reg_lambda': 0.5044454126957432, 'max_delta_step': 2}. Best is trial 25 with value: 0.8835526315789474.
[I 2025-12-02 03:17:59,402] Trial 27 finished with value: 0.8835526315789474 and parameters: {'max_depth': 8, 'learning_rate': 0.03178712570993041, 'n_estimators': 973, 'subsample': 0.9295029893991528, 'colsample_bytree': 0.9460319754644855, 'min_child_weight': 2, 'gamma': 2.875385440126589, 'reg_alpha': 0.04740666897158338, 'reg_lambda': 7.074519740252927e-05, 'max_delta_step': 2}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  60%|██████    | 30/50 [05:17<02:48,  8.43s/it]

[I 2025-12-02 03:18:02,191] Trial 29 finished with value: 0.7796052631578947 and parameters: {'max_depth': 8, 'learning_rate': 0.03292783151356038, 'n_estimators': 940, 'subsample': 0.8324128783663458, 'colsample_bytree': 0.9633312306634872, 'min_child_weight': 5, 'gamma': 0.7648408770550025, 'reg_alpha': 8.366804384920837e-08, 'reg_lambda': 0.23949291936498873, 'max_delta_step': 2}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  62%|██████▏   | 31/50 [05:41<04:08, 13.09s/it]

[I 2025-12-02 03:18:26,154] Trial 33 pruned.

Best trial: 25. Best value: 0.883553:  64%|██████▍   | 32/50 [05:48<03:21, 11.19s/it]

[I 2025-12-02 03:18:32,916] Trial 30 finished with value: 0.805921052631579 and parameters: {'max_depth': 9, 'learning_rate': 0.018605607746540753, 'n_estimators': 1317, 'subsample': 0.8531120633001344, 'colsample_bytree': 0.9715624587502871, 'min_child_weight': 5, 'gamma': 0.592453751269596, 'reg_alpha': 2.2077382127542208e-07, 'reg_lambda': 0.29112581488798145, 'max_delta_step': 2}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  66%|██████▌   | 33/50 [05:59<03:10, 11.19s/it]

[I 2025-12-02 03:18:44,093] Trial 32 finished with value: 0.7796052631578947 and parameters: {'max_depth': 9, 'learning_rate': 0.019821942712507517, 'n_estimators': 916, 'subsample': 0.8658018213721626, 'colsample_bytree': 0.9296904882680913, 'min_child_weight': 5, 'gamma': 3.142677907736919, 'reg_alpha': 0.15152753646609476, 'reg_lambda': 5.756041293291418, 'max_delta_step': 2}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  68%|██████▊   | 34/50 [06:11<03:02, 11.43s/it]

[I 2025-12-02 03:18:56,102] Trial 31 finished with value: 0.805921052631579 and parameters: {'max_depth': 9, 'learning_rate': 0.019256511836404706, 'n_estimators': 1295, 'subsample': 0.8553056252071748, 'colsample_bytree': 0.9556311927276822, 'min_child_weight': 5, 'gamma': 0.6987854643945667, 'reg_alpha': 1.1225293982133066e-07, 'reg_lambda': 3.2147792006576283, 'max_delta_step': 2}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  70%|███████   | 35/50 [06:38<04:01, 16.10s/it]

[I 2025-12-02 03:19:23,092] Trial 35 finished with value: 0.8835526315789474 and parameters: {'max_depth': 7, 'learning_rate': 0.04475144981521356, 'n_estimators': 913, 'subsample': 0.9546340087726094, 'colsample_bytree': 0.9236489978698537, 'min_child_weight': 1, 'gamma': 2.565653559864695, 'reg_alpha': 0.023499705816894333, 'reg_lambda': 1.872228639795653e-05, 'max_delta_step': 0}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  72%|███████▏  | 36/50 [06:43<02:58, 12.78s/it]

[I 2025-12-02 03:19:28,133] Trial 34 finished with value: 0.8835526315789474 and parameters: {'max_depth': 9, 'learning_rate': 0.06190647741133248, 'n_estimators': 1113, 'subsample': 0.9502679373628455, 'colsample_bytree': 0.9228371188051397, 'min_child_weight': 1, 'gamma': 2.7354623876007285, 'reg_alpha': 0.043062758401999905, 'reg_lambda': 2.470247368069565e-05, 'max_delta_step': 0}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  74%|███████▍  | 37/50 [07:01<03:06, 14.35s/it]

[I 2025-12-02 03:19:46,125] Trial 36 finished with value: 0.8835526315789474 and parameters: {'max_depth': 7, 'learning_rate': 0.04403105746454749, 'n_estimators': 1139, 'subsample': 0.9475164428054944, 'colsample_bytree': 0.905757113935255, 'min_child_weight': 1, 'gamma': 2.494203762256211, 'reg_alpha': 0.021982141516312927, 'reg_lambda': 2.493079261843152e-05, 'max_delta_step': 0}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  76%|███████▌  | 38/50 [07:06<02:16, 11.40s/it]

[I 2025-12-02 03:19:50,650] Trial 38 finished with value: 0.8835526315789474 and parameters: {'max_depth': 7, 'learning_rate': 0.04251675085424486, 'n_estimators': 348, 'subsample': 0.9450261331899251, 'colsample_bytree': 0.8452009161878515, 'min_child_weight': 1, 'gamma': 3.382571486597657, 'reg_alpha': 0.02669818233480807, 'reg_lambda': 1.7530125846644246e-05, 'max_delta_step': 1}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  78%|███████▊  | 39/50 [07:12<01:49,  9.93s/it]

[I 2025-12-02 03:19:57,138] Trial 37 finished with value: 0.8835526315789474 and parameters: {'max_depth': 7, 'learning_rate': 0.04456045560262464, 'n_estimators': 1095, 'subsample': 0.9493186076026936, 'colsample_bytree': 0.9070728689440293, 'min_child_weight': 1, 'gamma': 2.494523163774508, 'reg_alpha': 0.035451413358160495, 'reg_lambda': 3.594420092698857e-05, 'max_delta_step': 0}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  80%|████████  | 40/50 [07:34<02:12, 13.28s/it]

[I 2025-12-02 03:20:18,254] Trial 41 finished with value: 0.7796052631578947 and parameters: {'max_depth': 10, 'learning_rate': 0.06295438366484533, 'n_estimators': 699, 'subsample': 0.8212611296228616, 'colsample_bytree': 0.9188616111309555, 'min_child_weight': 4, 'gamma': 2.690380335709735, 'reg_alpha': 0.1486787922214545, 'reg_lambda': 1.535517260053747e-06, 'max_delta_step': 3}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  82%|████████▏ | 41/50 [07:41<01:43, 11.53s/it]

[I 2025-12-02 03:20:25,705] Trial 42 finished with value: 0.8322368421052632 and parameters: {'max_depth': 10, 'learning_rate': 0.0663365898049743, 'n_estimators': 702, 'subsample': 0.8913811531717547, 'colsample_bytree': 0.9288909016327771, 'min_child_weight': 4, 'gamma': 2.7876988762014108, 'reg_alpha': 1.8462512409411471, 'reg_lambda': 4.6153519741995774e-06, 'max_delta_step': 4}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  84%|████████▍ | 42/50 [07:46<01:15,  9.45s/it]

[I 2025-12-02 03:20:30,289] Trial 40 finished with value: 0.8835526315789474 and parameters: {'max_depth': 10, 'learning_rate': 0.05884022121454112, 'n_estimators': 727, 'subsample': 0.8926552326444579, 'colsample_bytree': 0.9249802038790608, 'min_child_weight': 1, 'gamma': 3.3615757032862104, 'reg_alpha': 0.03597759863961389, 'reg_lambda': 3.673368070055276e-07, 'max_delta_step': 4}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  86%|████████▌ | 43/50 [07:52<01:00,  8.61s/it]

[I 2025-12-02 03:20:36,930] Trial 39 finished with value: 0.8835526315789474 and parameters: {'max_depth': 10, 'learning_rate': 0.04342043686007578, 'n_estimators': 1158, 'subsample': 0.9455639781431406, 'colsample_bytree': 0.9039406361517773, 'min_child_weight': 1, 'gamma': 3.389687972430633, 'reg_alpha': 0.021352180995127187, 'reg_lambda': 1.035957410915188e-06, 'max_delta_step': 1}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  88%|████████▊ | 44/50 [08:16<01:19, 13.18s/it]

[I 2025-12-02 03:21:00,780] Trial 43 finished with value: 0.8572368421052632 and parameters: {'max_depth': 10, 'learning_rate': 0.0755180144807436, 'n_estimators': 876, 'subsample': 0.8938916390953107, 'colsample_bytree': 0.7689606594140191, 'min_child_weight': 2, 'gamma': 3.4743688928886747, 'reg_alpha': 3.196809262950705, 'reg_lambda': 3.730247570493728e-07, 'max_delta_step': 4}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  90%|█████████ | 45/50 [08:28<01:03, 12.74s/it]

[I 2025-12-02 03:21:12,501] Trial 45 finished with value: 0.8835526315789474 and parameters: {'max_depth': 6, 'learning_rate': 0.04817336936132922, 'n_estimators': 897, 'subsample': 0.9638771173954755, 'colsample_bytree': 0.9011289713637728, 'min_child_weight': 2, 'gamma': 2.328466923425765, 'reg_alpha': 0.013509200223684723, 'reg_lambda': 1.330100571625829e-05, 'max_delta_step': 1}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  92%|█████████▏| 46/50 [08:37<00:46, 11.66s/it]

[I 2025-12-02 03:21:21,625] Trial 44 finished with value: 0.8835526315789474 and parameters: {'max_depth': 6, 'learning_rate': 0.047548151840426454, 'n_estimators': 1168, 'subsample': 0.9604142023451622, 'colsample_bytree': 0.8949509706391229, 'min_child_weight': 2, 'gamma': 3.345679200077952, 'reg_alpha': 0.01731158639774681, 'reg_lambda': 5.067154965740785e-07, 'max_delta_step': 1}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  94%|█████████▍| 47/50 [08:40<00:26,  8.97s/it]

[I 2025-12-02 03:21:24,322] Trial 46 finished with value: 0.8835526315789474 and parameters: {'max_depth': 6, 'learning_rate': 0.07486807585310012, 'n_estimators': 1035, 'subsample': 0.9662011894403382, 'colsample_bytree': 0.7932449964871752, 'min_child_weight': 2, 'gamma': 3.7620373686173565, 'reg_alpha': 0.42043437292059693, 'reg_lambda': 1.191968397271696e-05, 'max_delta_step': 0}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  96%|█████████▌| 48/50 [09:10<00:30, 15.47s/it]

[I 2025-12-02 03:21:54,961] Trial 47 finished with value: 0.8835526315789474 and parameters: {'max_depth': 6, 'learning_rate': 0.1290938104865981, 'n_estimators': 1162, 'subsample': 0.9704889650687214, 'colsample_bytree': 0.887057547247669, 'min_child_weight': 2, 'gamma': 3.964719443558956, 'reg_alpha': 0.6958568716262685, 'reg_lambda': 8.15583763483272e-06, 'max_delta_step': 0}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553:  98%|█████████▊| 49/50 [09:16<00:12, 12.71s/it]

[I 2025-12-02 03:22:01,240] Trial 48 finished with value: 0.8835526315789474 and parameters: {'max_depth': 8, 'learning_rate': 0.13946268704885995, 'n_estimators': 1166, 'subsample': 0.926798591084622, 'colsample_bytree': 0.7923091688286402, 'min_child_weight': 2, 'gamma': 3.8224095244367664, 'reg_alpha': 0.47823703073822216, 'reg_lambda': 7.1854577661572385e-06, 'max_delta_step': 0}. Best is trial 25 with value: 0.8835526315789474.

Best trial: 25. Best value: 0.883553: 100%|██████████| 50/50 [09:18<00:00, 11.16s/it]

[I 2025-12-02 03:22:02,303] Trial 49 finished with value: 0.8572368421052632 and parameters: {'max_depth': 8, 'learning_rate': 0.09852215558199033, 'n_estimators': 1042, 'subsample': 0.9166203734010081, 'colsample_bytree': 0.9459620755034077, 'min_child_weight': 3, 'gamma': 3.789832472497427, 'reg_alpha': 0.4094341505080972, 'reg_lambda': 6.419435305302115e-06, 'max_delta_step': 0}. Best is trial 25 with value: 0.8835526315789474.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 03:22:07,426] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.704108:   2%|▏         | 1/50 [00:11<09:01, 11.05s/it]

[I 2025-12-02 03:22:18,467] Trial 3 finished with value: 0.7041078305519897 and parameters: {'max_depth': 10, 'learning_rate': 0.1502472998979024, 'n_estimators': 244, 'subsample': 0.8934894182228148, 'colsample_bytree': 0.686587451325942, 'min_child_weight': 8, 'gamma': 2.9331851149887056, 'reg_alpha': 1.0789078246243922, 'reg_lambda': 0.003043025949258081, 'max_delta_step': 8}. Best is trial 3 with value: 0.7041078305519897.

Best trial: 3. Best value: 0.704108:   4%|▍         | 2/50 [00:35<15:12, 19.00s/it]

[I 2025-12-02 03:22:43,037] Trial 0 finished with value: 0.2631578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.20274185941644438, 'n_estimators': 925, 'subsample': 0.5575012836526851, 'colsample_bytree': 0.5045291423828591, 'min_child_weight': 9, 'gamma': 3.7874562151695637, 'reg_alpha': 5.331905769109178e-06, 'reg_lambda': 0.0006754798702717675, 'max_delta_step': 4}. Best is trial 3 with value: 0.7041078305519897.

Best trial: 3. Best value: 0.704108:   6%|▌         | 3/50 [00:39<09:22, 11.97s/it]

[I 2025-12-02 03:22:46,629] Trial 1 finished with value: 0.6777920410783055 and parameters: {'max_depth': 3, 'learning_rate': 0.10066428159593568, 'n_estimators': 854, 'subsample': 0.5234559544251826, 'colsample_bytree': 0.5566888272700999, 'min_child_weight': 1, 'gamma': 0.828967702180125, 'reg_alpha': 7.828797543125417e-08, 'reg_lambda': 1.979699528199143e-06, 'max_delta_step': 1}. Best is trial 3 with value: 0.7041078305519897.

Best trial: 3. Best value: 0.704108:   8%|▊         | 4/50 [00:56<10:40, 13.91s/it]

[I 2025-12-02 03:23:03,533] Trial 5 finished with value: 0.2631578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.09464785071022662, 'n_estimators': 507, 'subsample': 0.5600064919191602, 'colsample_bytree': 0.5791099103139086, 'min_child_weight': 10, 'gamma': 1.9829973707346054, 'reg_alpha': 5.83207547975559e-06, 'reg_lambda': 1.3931020191921937, 'max_delta_step': 0}. Best is trial 3 with value: 0.7041078305519897.

Best trial: 4. Best value: 0.732349:  10%|█         | 5/50 [01:03<08:33, 11.41s/it]

[I 2025-12-02 03:23:10,505] Trial 4 finished with value: 0.7323491655969192 and parameters: {'max_depth': 7, 'learning_rate': 0.11125149259710418, 'n_estimators': 1286, 'subsample': 0.8258323164727084, 'colsample_bytree': 0.9673818276053208, 'min_child_weight': 8, 'gamma': 4.213831864731223, 'reg_alpha': 9.072079087535903e-06, 'reg_lambda': 2.0938438372324727e-06, 'max_delta_step': 0}. Best is trial 4 with value: 0.7323491655969192.

Best trial: 4. Best value: 0.732349:  12%|█▏        | 6/50 [01:19<09:42, 13.23s/it]

[I 2025-12-02 03:23:27,279] Trial 2 finished with value: 0.7041078305519897 and parameters: {'max_depth': 7, 'learning_rate': 0.012307799021554499, 'n_estimators': 1170, 'subsample': 0.7358384741853801, 'colsample_bytree': 0.8994261749242132, 'min_child_weight': 2, 'gamma': 0.9449908801646917, 'reg_alpha': 1.4473731511508423e-07, 'reg_lambda': 0.00011494142927661649, 'max_delta_step': 7}. Best is trial 4 with value: 0.7323491655969192.

Best trial: 4. Best value: 0.732349:  14%|█▍        | 7/50 [01:33<09:37, 13.44s/it]

[I 2025-12-02 03:23:41,140] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.05488651189202117, 'n_estimators': 285, 'subsample': 0.7102138701347278, 'colsample_bytree': 0.890042446262177, 'min_child_weight': 10, 'gamma': 3.130900236650385, 'reg_alpha': 8.418934863762569e-07, 'reg_lambda': 6.01932765012639e-05, 'max_delta_step': 3}. Best is trial 4 with value: 0.7323491655969192.

Best trial: 4. Best value: 0.732349:  16%|█▌        | 8/50 [01:35<06:51,  9.79s/it]

[I 2025-12-02 03:23:43,118] Trial 7 finished with value: 0.6572528883183568 and parameters: {'max_depth': 5, 'learning_rate': 0.0745534368479832, 'n_estimators': 1031, 'subsample': 0.7662160107189746, 'colsample_bytree': 0.6367179343064302, 'min_child_weight': 8, 'gamma': 1.224607702827104, 'reg_alpha': 1.289623550575034e-07, 'reg_lambda': 0.0003074776095626178, 'max_delta_step': 1}. Best is trial 4 with value: 0.7323491655969192.

Best trial: 4. Best value: 0.732349:  18%|█▊        | 9/50 [01:55<08:43, 12.78s/it]

[I 2025-12-02 03:24:02,465] Trial 6 finished with value: 0.6919127086007703 and parameters: {'max_depth': 8, 'learning_rate': 0.041253933912321024, 'n_estimators': 1256, 'subsample': 0.6008966031919004, 'colsample_bytree': 0.8045277980521719, 'min_child_weight': 1, 'gamma': 3.9412779331529517, 'reg_alpha': 1.8035008960802724e-05, 'reg_lambda': 0.39133521236274277, 'max_delta_step': 2}. Best is trial 4 with value: 0.7323491655969192.

Best trial: 4. Best value: 0.732349:  20%|██        | 10/50 [01:57<06:25,  9.64s/it]

[I 2025-12-02 03:24:05,086] Trial 8 finished with value: 0.3902439024390244 and parameters: {'max_depth': 10, 'learning_rate': 0.024850284900672624, 'n_estimators': 1477, 'subsample': 0.9462558235332386, 'colsample_bytree': 0.5576166652742521, 'min_child_weight': 10, 'gamma': 3.0351225790200265, 'reg_alpha': 2.575191791214983e-05, 'reg_lambda': 5.112521833958335e-06, 'max_delta_step': 2}. Best is trial 4 with value: 0.7323491655969192.

Best trial: 4. Best value: 0.732349:  22%|██▏       | 11/50 [02:33<11:22, 17.51s/it]

[I 2025-12-02 03:24:40,441] Trial 11 finished with value: 0.7060333761232349 and parameters: {'max_depth': 10, 'learning_rate': 0.10904568096623612, 'n_estimators': 1445, 'subsample': 0.5812159930660219, 'colsample_bytree': 0.7947381097517296, 'min_child_weight': 5, 'gamma': 2.9210456817518455, 'reg_alpha': 2.505892539245755e-08, 'reg_lambda': 0.004589903503409381, 'max_delta_step': 9}. Best is trial 4 with value: 0.7323491655969192.

Best trial: 4. Best value: 0.732349:  24%|██▍       | 12/50 [02:50<10:59, 17.35s/it]

[I 2025-12-02 03:24:57,422] Trial 10 finished with value: 0.7182284980744544 and parameters: {'max_depth': 3, 'learning_rate': 0.010483461840563278, 'n_estimators': 1210, 'subsample': 0.9528085350561133, 'colsample_bytree': 0.9698985805165267, 'min_child_weight': 5, 'gamma': 3.7133182672938805, 'reg_alpha': 0.5859102082442076, 'reg_lambda': 5.784873853066623, 'max_delta_step': 9}. Best is trial 4 with value: 0.7323491655969192.

Best trial: 4. Best value: 0.732349:  26%|██▌       | 13/50 [02:51<07:43, 12.53s/it]

[I 2025-12-02 03:24:58,847] Trial 12 finished with value: 0.6797175866495507 and parameters: {'max_depth': 8, 'learning_rate': 0.13925916553486475, 'n_estimators': 1368, 'subsample': 0.8377606418508694, 'colsample_bytree': 0.785118664818049, 'min_child_weight': 3, 'gamma': 0.6570074946732923, 'reg_alpha': 3.6078009305922317e-06, 'reg_lambda': 0.008076921718625322, 'max_delta_step': 3}. Best is trial 4 with value: 0.7323491655969192.

Best trial: 4. Best value: 0.732349:  28%|██▊       | 14/50 [02:58<06:36, 11.01s/it]

[I 2025-12-02 03:25:06,364] Trial 13 finished with value: 0.7041078305519897 and parameters: {'max_depth': 6, 'learning_rate': 0.2684443425833454, 'n_estimators': 1477, 'subsample': 0.8499222448167966, 'colsample_bytree': 0.9920168122336015, 'min_child_weight': 5, 'gamma': 4.662367560230831, 'reg_alpha': 0.009013576754857354, 'reg_lambda': 1.0754431853491605e-08, 'max_delta_step': 6}. Best is trial 4 with value: 0.7323491655969192.

Best trial: 4. Best value: 0.732349:  30%|███       | 15/50 [03:30<10:03, 17.24s/it]

[I 2025-12-02 03:25:38,032] Trial 17 finished with value: 0.6938382541720154 and parameters: {'max_depth': 5, 'learning_rate': 0.010273378033311895, 'n_estimators': 618, 'subsample': 0.9985635490582055, 'colsample_bytree': 0.9952451072409851, 'min_child_weight': 7, 'gamma': 4.677161555578268, 'reg_alpha': 0.005092188639281099, 'reg_lambda': 3.190468807708913e-08, 'max_delta_step': 10}. Best is trial 4 with value: 0.7323491655969192.

Best trial: 4. Best value: 0.732349:  32%|███▏      | 16/50 [03:31<06:56, 12.26s/it]

[I 2025-12-02 03:25:38,746] Trial 14 finished with value: 0.6919127086007703 and parameters: {'max_depth': 8, 'learning_rate': 0.2046555783100777, 'n_estimators': 1495, 'subsample': 0.8556927174645171, 'colsample_bytree': 0.9454015410544827, 'min_child_weight': 5, 'gamma': 4.593313323256345, 'reg_alpha': 0.0056523979850915855, 'reg_lambda': 8.084204178822139e-08, 'max_delta_step': 10}. Best is trial 4 with value: 0.7323491655969192.

Best trial: 4. Best value: 0.732349:  34%|███▍      | 17/50 [03:46<07:14, 13.18s/it]

[I 2025-12-02 03:25:54,055] Trial 16 finished with value: 0.7182284980744544 and parameters: {'max_depth': 5, 'learning_rate': 0.010028477267452861, 'n_estimators': 1129, 'subsample': 0.9987354943413745, 'colsample_bytree': 0.9909472892884501, 'min_child_weight': 6, 'gamma': 4.536648810870438, 'reg_alpha': 0.04837099066241551, 'reg_lambda': 1.2333733886184708e-08, 'max_delta_step': 6}. Best is trial 4 with value: 0.7323491655969192.

Best trial: 4. Best value: 0.732349:  36%|███▌      | 18/50 [03:55<06:19, 11.87s/it]

[I 2025-12-02 03:26:02,881] Trial 15 finished with value: 0.730423620025674 and parameters: {'max_depth': 5, 'learning_rate': 0.010611718141045853, 'n_estimators': 1178, 'subsample': 0.9998283526513765, 'colsample_bytree': 0.9941563120405567, 'min_child_weight': 5, 'gamma': 4.846394705609949, 'reg_alpha': 0.04968121598675497, 'reg_lambda': 1.2801206589407796e-08, 'max_delta_step': 6}. Best is trial 4 with value: 0.7323491655969192.

Best trial: 4. Best value: 0.732349:  38%|███▊      | 19/50 [04:24<08:44, 16.91s/it]

[I 2025-12-02 03:26:31,527] Trial 19 finished with value: 0.6392811296534018 and parameters: {'max_depth': 5, 'learning_rate': 0.01848492735332388, 'n_estimators': 1137, 'subsample': 0.9437123551225262, 'colsample_bytree': 0.8665315706812583, 'min_child_weight': 7, 'gamma': 3.7380474996155852, 'reg_alpha': 8.293526838337177, 'reg_lambda': 0.16322033638376834, 'max_delta_step': 5}. Best is trial 4 with value: 0.7323491655969192.

Best trial: 4. Best value: 0.732349:  40%|████      | 20/50 [04:25<06:08, 12.29s/it]

[I 2025-12-02 03:26:33,043] Trial 18 finished with value: 0.730423620025674 and parameters: {'max_depth': 5, 'learning_rate': 0.019479011035469344, 'n_estimators': 1125, 'subsample': 0.916973729982728, 'colsample_bytree': 0.9143473534179986, 'min_child_weight': 6, 'gamma': 3.9180205367445495, 'reg_alpha': 3.9084527449177813, 'reg_lambda': 6.848493538296931, 'max_delta_step': 5}. Best is trial 4 with value: 0.7323491655969192.

Best trial: 4. Best value: 0.732349:  42%|████▏     | 21/50 [04:35<05:34, 11.53s/it]

[I 2025-12-02 03:26:42,811] Trial 21 finished with value: 0.6514762516046213 and parameters: {'max_depth': 6, 'learning_rate': 0.022517030732524805, 'n_estimators': 731, 'subsample': 0.6720947105031662, 'colsample_bytree': 0.8761720185604073, 'min_child_weight': 3, 'gamma': 0.04178240428305635, 'reg_alpha': 0.00019740128081537387, 'reg_lambda': 5.112936163700614e-07, 'max_delta_step': 5}. Best is trial 4 with value: 0.7323491655969192.

Best trial: 4. Best value: 0.732349:  44%|████▍     | 22/50 [04:52<06:06, 13.10s/it]

[I 2025-12-02 03:26:59,585] Trial 20 finished with value: 0.7163029525032092 and parameters: {'max_depth': 6, 'learning_rate': 0.026774804073581522, 'n_estimators': 1287, 'subsample': 0.6603128171240824, 'colsample_bytree': 0.8626303594963286, 'min_child_weight': 4, 'gamma': 3.7064695770322413, 'reg_alpha': 4.888832563084772, 'reg_lambda': 7.129721108370381, 'max_delta_step': 8}. Best is trial 4 with value: 0.7323491655969192.

Best trial: 23. Best value: 0.768935:  46%|████▌     | 23/50 [04:57<04:52, 10.85s/it]

[I 2025-12-02 03:27:05,171] Trial 23 finished with value: 0.7689345314505777 and parameters: {'max_depth': 7, 'learning_rate': 0.0366822427221642, 'n_estimators': 700, 'subsample': 0.6709866707362931, 'colsample_bytree': 0.7200258144417421, 'min_child_weight': 4, 'gamma': 4.96683549372588, 'reg_alpha': 0.00035987956772194434, 'reg_lambda': 3.229716047484429e-07, 'max_delta_step': 0}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  48%|████▊     | 24/50 [05:02<03:54,  9.04s/it]

[I 2025-12-02 03:27:09,981] Trial 22 finished with value: 0.7182284980744544 and parameters: {'max_depth': 6, 'learning_rate': 0.03409308119857018, 'n_estimators': 739, 'subsample': 0.6478932742823812, 'colsample_bytree': 0.9203679253279091, 'min_child_weight': 3, 'gamma': 1.9018945335100104, 'reg_alpha': 0.0005397758715235705, 'reg_lambda': 3.889022786862811e-07, 'max_delta_step': 5}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  50%|█████     | 25/50 [05:35<06:42, 16.09s/it]

[I 2025-12-02 03:27:42,529] Trial 24 finished with value: 0.730423620025674 and parameters: {'max_depth': 4, 'learning_rate': 0.015981926267144387, 'n_estimators': 1317, 'subsample': 0.8059678102256889, 'colsample_bytree': 0.9296814663047764, 'min_child_weight': 6, 'gamma': 4.156722961204222, 'reg_alpha': 0.231508109984304, 'reg_lambda': 1.2587330824759018e-05, 'max_delta_step': 7}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  52%|█████▏    | 26/50 [05:37<04:47, 11.98s/it]

[I 2025-12-02 03:27:44,916] Trial 25 finished with value: 0.7060333761232349 and parameters: {'max_depth': 4, 'learning_rate': 0.016840312731960058, 'n_estimators': 992, 'subsample': 0.7930375871411925, 'colsample_bytree': 0.9321534913712166, 'min_child_weight': 7, 'gamma': 4.228909120017686, 'reg_alpha': 0.10657211950176658, 'reg_lambda': 2.443576559536632e-07, 'max_delta_step': 5}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  54%|█████▍    | 27/50 [05:41<03:41,  9.61s/it]

[I 2025-12-02 03:27:48,989] Trial 26 finished with value: 0.7041078305519897 and parameters: {'max_depth': 7, 'learning_rate': 0.04375629870131164, 'n_estimators': 958, 'subsample': 0.790099722516787, 'colsample_bytree': 0.7111135826960902, 'min_child_weight': 4, 'gamma': 4.904566649242963, 'reg_alpha': 0.00031488378328146255, 'reg_lambda': 2.1687924312930464e-07, 'max_delta_step': 0}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  56%|█████▌    | 28/50 [05:45<02:51,  7.80s/it]

[I 2025-12-02 03:27:52,564] Trial 30 pruned.

Best trial: 23. Best value: 0.768935:  58%|█████▊    | 29/50 [05:47<02:12,  6.31s/it]

[I 2025-12-02 03:27:55,418] Trial 27 finished with value: 0.6534017971758665 and parameters: {'max_depth': 7, 'learning_rate': 0.07149508707770254, 'n_estimators': 986, 'subsample': 0.7973537867429994, 'colsample_bytree': 0.7316371826696261, 'min_child_weight': 4, 'gamma': 4.9636907519211855, 'reg_alpha': 0.00024981330474246134, 'reg_lambda': 6.664697366890464e-06, 'max_delta_step': 0}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  60%|██████    | 30/50 [05:51<01:50,  5.50s/it]

[I 2025-12-02 03:27:59,032] Trial 31 pruned.

Best trial: 23. Best value: 0.768935:  62%|██████▏   | 31/50 [06:03<02:22,  7.48s/it]

[I 2025-12-02 03:28:11,110] Trial 29 finished with value: 0.7182284980744544 and parameters: {'max_depth': 7, 'learning_rate': 0.04867021748955073, 'n_estimators': 507, 'subsample': 0.6883072006432892, 'colsample_bytree': 0.7076706971924743, 'min_child_weight': 4, 'gamma': 4.932952958364003, 'reg_alpha': 0.0002819138783922077, 'reg_lambda': 2.2496714734033207e-06, 'max_delta_step': 0}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  64%|██████▍   | 32/50 [06:20<03:03, 10.22s/it]

[I 2025-12-02 03:28:27,722] Trial 28 finished with value: 0.6919127086007703 and parameters: {'max_depth': 7, 'learning_rate': 0.05845388586439469, 'n_estimators': 987, 'subsample': 0.7854448936605217, 'colsample_bytree': 0.7058829606891689, 'min_child_weight': 4, 'gamma': 4.945326969957771, 'reg_alpha': 0.0003573383609519019, 'reg_lambda': 1.0010503257443385e-07, 'max_delta_step': 0}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  66%|██████▌   | 33/50 [06:25<02:26,  8.59s/it]

[I 2025-12-02 03:28:32,512] Trial 32 finished with value: 0.7060333761232349 and parameters: {'max_depth': 9, 'learning_rate': 0.03098289592410571, 'n_estimators': 854, 'subsample': 0.8813322301538818, 'colsample_bytree': 0.6567304919319676, 'min_child_weight': 9, 'gamma': 3.3060003815058794, 'reg_alpha': 0.0013027899796690342, 'reg_lambda': 1.1951477520275229e-06, 'max_delta_step': 3}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  68%|██████▊   | 34/50 [06:39<02:44, 10.25s/it]

[I 2025-12-02 03:28:46,640] Trial 33 finished with value: 0.6655969191270861 and parameters: {'max_depth': 9, 'learning_rate': 0.032858403194185495, 'n_estimators': 878, 'subsample': 0.6990795450290651, 'colsample_bytree': 0.6688477572238536, 'min_child_weight': 2, 'gamma': 4.302522741843482, 'reg_alpha': 0.02188016421597709, 'reg_lambda': 4.223433554779213e-08, 'max_delta_step': 3}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  70%|███████   | 35/50 [06:50<02:40, 10.71s/it]

[I 2025-12-02 03:28:58,419] Trial 34 finished with value: 0.6675224646983312 and parameters: {'max_depth': 4, 'learning_rate': 0.0336062622187478, 'n_estimators': 1105, 'subsample': 0.8984753096749223, 'colsample_bytree': 0.959350221810924, 'min_child_weight': 7, 'gamma': 4.283675098055693, 'reg_alpha': 0.03957451547136863, 'reg_lambda': 0.055039509783575136, 'max_delta_step': 4}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  72%|███████▏  | 36/50 [07:05<02:45, 11.85s/it]

[I 2025-12-02 03:29:12,934] Trial 35 finished with value: 0.6919127086007703 and parameters: {'max_depth': 4, 'learning_rate': 0.033044364389253775, 'n_estimators': 1076, 'subsample': 0.9197540415546505, 'colsample_bytree': 0.6484067321282828, 'min_child_weight': 6, 'gamma': 4.299593915666273, 'reg_alpha': 0.034612985236377306, 'reg_lambda': 2.458293356895019e-08, 'max_delta_step': 4}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  74%|███████▍  | 37/50 [07:16<02:28, 11.45s/it]

[I 2025-12-02 03:29:23,434] Trial 36 finished with value: 0.6938382541720154 and parameters: {'max_depth': 4, 'learning_rate': 0.013485697774054495, 'n_estimators': 1067, 'subsample': 0.9150336251978419, 'colsample_bytree': 0.9543994520125991, 'min_child_weight': 6, 'gamma': 4.285235572001905, 'reg_alpha': 0.04019125930561843, 'reg_lambda': 3.5972140430266675e-08, 'max_delta_step': 4}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  76%|███████▌  | 38/50 [07:32<02:34, 12.86s/it]

[I 2025-12-02 03:29:39,600] Trial 37 finished with value: 0.7182284980744544 and parameters: {'max_depth': 4, 'learning_rate': 0.014985367112619665, 'n_estimators': 1077, 'subsample': 0.9136604351429862, 'colsample_bytree': 0.9602048443130848, 'min_child_weight': 6, 'gamma': 4.034210319104865, 'reg_alpha': 1.2071893715528135, 'reg_lambda': 0.08139793098688757, 'max_delta_step': 4}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  78%|███████▊  | 39/50 [07:40<02:07, 11.56s/it]

[I 2025-12-02 03:29:48,120] Trial 41 pruned.

Best trial: 23. Best value: 0.768935:  80%|████████  | 40/50 [08:01<02:23, 14.36s/it]

[I 2025-12-02 03:30:09,025] Trial 38 finished with value: 0.7060333761232349 and parameters: {'max_depth': 6, 'learning_rate': 0.01254668659037735, 'n_estimators': 1370, 'subsample': 0.9217754724366173, 'colsample_bytree': 0.909181521659795, 'min_child_weight': 6, 'gamma': 2.4100253988035654, 'reg_alpha': 1.782595421113326, 'reg_lambda': 9.235308905798583e-05, 'max_delta_step': 6}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  82%|████████▏ | 41/50 [08:03<01:34, 10.51s/it]

[I 2025-12-02 03:30:10,538] Trial 39 finished with value: 0.6919127086007703 and parameters: {'max_depth': 6, 'learning_rate': 0.014307058657136393, 'n_estimators': 1370, 'subsample': 0.9713917111212048, 'colsample_bytree': 0.6101268655948237, 'min_child_weight': 9, 'gamma': 2.5353098784225527, 'reg_alpha': 2.2426739009687724, 'reg_lambda': 6.683019828306793e-05, 'max_delta_step': 2}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  84%|████████▍ | 42/50 [08:15<01:28, 11.01s/it]

[I 2025-12-02 03:30:22,723] Trial 40 finished with value: 0.6919127086007703 and parameters: {'max_depth': 6, 'learning_rate': 0.02111110691618748, 'n_estimators': 1365, 'subsample': 0.9732750267650562, 'colsample_bytree': 0.8289612210114786, 'min_child_weight': 9, 'gamma': 2.4651508379375677, 'reg_alpha': 7.435175270896457e-07, 'reg_lambda': 6.140823626396378e-05, 'max_delta_step': 2}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  86%|████████▌ | 43/50 [08:29<01:23, 11.92s/it]

[I 2025-12-02 03:30:36,771] Trial 43 finished with value: 0.6694480102695763 and parameters: {'max_depth': 5, 'learning_rate': 0.09811224662693614, 'n_estimators': 588, 'subsample': 0.9727725184071018, 'colsample_bytree': 0.8276420454958865, 'min_child_weight': 8, 'gamma': 3.4783373278770275, 'reg_alpha': 3.5528498098617706e-07, 'reg_lambda': 0.0008127911038289936, 'max_delta_step': 1}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  88%|████████▊ | 44/50 [08:42<01:14, 12.36s/it]

[I 2025-12-02 03:30:50,156] Trial 42 finished with value: 0.730423620025674 and parameters: {'max_depth': 6, 'learning_rate': 0.012098799175486839, 'n_estimators': 1370, 'subsample': 0.7494483936268863, 'colsample_bytree': 0.905447468668138, 'min_child_weight': 8, 'gamma': 2.322700160154227, 'reg_alpha': 4.871836917516973e-07, 'reg_lambda': 0.0018681946963883195, 'max_delta_step': 6}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  90%|█████████ | 45/50 [08:55<01:02, 12.41s/it]

[I 2025-12-02 03:31:02,687] Trial 44 finished with value: 0.6797175866495507 and parameters: {'max_depth': 5, 'learning_rate': 0.020640917179688113, 'n_estimators': 1249, 'subsample': 0.750181924586521, 'colsample_bytree': 0.5160510397874677, 'min_child_weight': 8, 'gamma': 3.496501507392755, 'reg_alpha': 0.3356403242789991, 'reg_lambda': 1.1611285380161101e-05, 'max_delta_step': 7}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  92%|█████████▏| 46/50 [09:16<01:00, 15.00s/it]

[I 2025-12-02 03:31:23,728] Trial 45 finished with value: 0.7163029525032092 and parameters: {'max_depth': 5, 'learning_rate': 0.016463164951894173, 'n_estimators': 1283, 'subsample': 0.7481910000767754, 'colsample_bytree': 0.9005573708247885, 'min_child_weight': 5, 'gamma': 4.016887333820391, 'reg_alpha': 0.32861243051086375, 'reg_lambda': 0.0011586061247794129, 'max_delta_step': 7}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  94%|█████████▍| 47/50 [09:28<00:42, 14.30s/it]

[I 2025-12-02 03:31:36,377] Trial 46 finished with value: 0.730423620025674 and parameters: {'max_depth': 5, 'learning_rate': 0.015552715827694158, 'n_estimators': 1277, 'subsample': 0.7563601460576034, 'colsample_bytree': 0.8988871039496262, 'min_child_weight': 5, 'gamma': 3.9792194124058753, 'reg_alpha': 0.2950218380543621, 'reg_lambda': 1.5942660438168768e-05, 'max_delta_step': 7}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  96%|█████████▌| 48/50 [09:41<00:27, 13.70s/it]

[I 2025-12-02 03:31:48,695] Trial 47 finished with value: 0.730423620025674 and parameters: {'max_depth': 5, 'learning_rate': 0.0164871846974363, 'n_estimators': 1273, 'subsample': 0.8180436636784483, 'colsample_bytree': 0.9310012312018358, 'min_child_weight': 5, 'gamma': 3.9608390320859246, 'reg_alpha': 0.31750637107526963, 'reg_lambda': 1.4844030634308043e-05, 'max_delta_step': 7}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935:  98%|█████████▊| 49/50 [09:49<00:11, 11.92s/it]

[I 2025-12-02 03:31:56,450] Trial 48 finished with value: 0.730423620025674 and parameters: {'max_depth': 3, 'learning_rate': 0.01596912196817082, 'n_estimators': 1282, 'subsample': 0.8286243154405646, 'colsample_bytree': 0.9794911660339304, 'min_child_weight': 5, 'gamma': 3.932676814235803, 'reg_alpha': 0.1893219365589162, 'reg_lambda': 0.00031550218648486504, 'max_delta_step': 7}. Best is trial 23 with value: 0.7689345314505777.

Best trial: 23. Best value: 0.768935: 100%|██████████| 50/50 [09:55<00:00, 11.91s/it]

[I 2025-12-02 03:32:03,075] Trial 49 finished with value: 0.7182284980744544 and parameters: {'max_depth': 3, 'learning_rate': 0.026667260246849945, 'n_estimators': 1179, 'subsample': 0.8259803174737842, 'colsample_bytree': 0.7625400613505461, 'min_child_weight': 5, 'gamma': 4.545911809779234, 'reg_alpha': 1.349361311891087e-05, 'reg_lambda': 3.3138504077998104e-06, 'max_delta_step': 8}. Best is trial 23 with value: 0.7689345314505777.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.742105                    0.70          0.75
1    15_1         loo       0.716303                    0.65          0.62
2    19_1         loo       0.883553                    0.65          0.76
3    17_1         loo       0.768935                    0.55          0.56

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.377964               0.8               0.6        50          59
1  0.353553               0.4               0.9        50          60
2  0.288675               0.6               0.7        50          59
3  0.094491               0.6               0.5        50          60

   test_size
0         15
1         15
2         15
3         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0     9_1         loo       0.742105                    0.70          0.75
1    15_1         loo       0.716303                    0.65          0.62
2    19_1         loo       0.883553                    0.65          0.76
3    17_1         loo       0.768935                    0.55          0.56

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.377964               0.8               0.6        50          59
1  0.353553               0.4               0.9        50          60
2  0.288675               0.6               0.7        50          59
3  0.094491               0.6               0.5        50          60

   test_size
0         15
1         15
2         15
3         15

In [ ]:

datasets = task_hf_compensated_freq_emb_lbl_pd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_pd_hc_{CV_STRATEGY}_tasks/xgb_results_handcrafted_frerq_emb_pd_hc_extended_{CV_STRATEGY}_tasks",
    split_param= "diagnosis_y",
)
print(summary)
## MCI-AD vs HC -> OPTUNA + XGB

[I 2025-12-02 03:32:07,595] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.690789:   2%|▏         | 1/50 [00:13<11:03, 13.54s/it]

[I 2025-12-02 03:32:21,131] Trial 2 finished with value: 0.6907894736842105 and parameters: {'max_depth': 5, 'learning_rate': 0.01033992993423889, 'n_estimators': 256, 'subsample': 0.7520641855225206, 'colsample_bytree': 0.6421365838343964, 'min_child_weight': 8, 'gamma': 3.8717084039643583, 'reg_alpha': 4.865383428947908, 'reg_lambda': 3.215604325335426e-07, 'max_delta_step': 4}. Best is trial 2 with value: 0.6907894736842105.

Best trial: 2. Best value: 0.690789:   4%|▍         | 2/50 [00:18<06:49,  8.53s/it]

[I 2025-12-02 03:32:26,152] Trial 0 finished with value: 0.6782894736842104 and parameters: {'max_depth': 6, 'learning_rate': 0.12655031612886544, 'n_estimators': 370, 'subsample': 0.9874939172524136, 'colsample_bytree': 0.8025679420642531, 'min_child_weight': 6, 'gamma': 1.1723521965062178, 'reg_alpha': 0.17984063008556292, 'reg_lambda': 2.052380938771161e-07, 'max_delta_step': 8}. Best is trial 2 with value: 0.6907894736842105.

Best trial: 2. Best value: 0.690789:   6%|▌         | 3/50 [00:38<10:53, 13.90s/it]

[I 2025-12-02 03:32:46,445] Trial 1 finished with value: 0.6769736842105263 and parameters: {'max_depth': 8, 'learning_rate': 0.023663594382712483, 'n_estimators': 801, 'subsample': 0.743427304580116, 'colsample_bytree': 0.9244920465198592, 'min_child_weight': 6, 'gamma': 1.8570414273985931, 'reg_alpha': 0.003480755852023652, 'reg_lambda': 2.1427677164373305e-05, 'max_delta_step': 3}. Best is trial 2 with value: 0.6907894736842105.

Best trial: 3. Best value: 0.703289:   8%|▊         | 4/50 [00:47<08:55, 11.65s/it]

[I 2025-12-02 03:32:54,648] Trial 3 finished with value: 0.7032894736842106 and parameters: {'max_depth': 3, 'learning_rate': 0.0802708386599202, 'n_estimators': 1076, 'subsample': 0.9320868894300567, 'colsample_bytree': 0.9161595069741966, 'min_child_weight': 8, 'gamma': 2.929196730818901, 'reg_alpha': 0.1736225327448498, 'reg_lambda': 0.00047395402865167626, 'max_delta_step': 3}. Best is trial 3 with value: 0.7032894736842106.

Best trial: 3. Best value: 0.703289:  10%|█         | 5/50 [00:55<07:47, 10.38s/it]

[I 2025-12-02 03:33:02,769] Trial 4 finished with value: 0.6769736842105263 and parameters: {'max_depth': 5, 'learning_rate': 0.01117643132096277, 'n_estimators': 924, 'subsample': 0.7210893352122428, 'colsample_bytree': 0.9128897647041017, 'min_child_weight': 8, 'gamma': 3.0001262644782645, 'reg_alpha': 0.08626407529016872, 'reg_lambda': 5.210091525407859e-08, 'max_delta_step': 3}. Best is trial 3 with value: 0.7032894736842106.

Best trial: 6. Best value: 0.729605:  12%|█▏        | 6/50 [01:12<09:15, 12.63s/it]

[I 2025-12-02 03:33:19,765] Trial 6 finished with value: 0.7296052631578948 and parameters: {'max_depth': 5, 'learning_rate': 0.1672105542304254, 'n_estimators': 793, 'subsample': 0.8416159211963368, 'colsample_bytree': 0.5534838827413839, 'min_child_weight': 7, 'gamma': 3.4414889930408945, 'reg_alpha': 1.1337911825233231, 'reg_lambda': 0.0013433060921322435, 'max_delta_step': 3}. Best is trial 6 with value: 0.7296052631578948.

Best trial: 6. Best value: 0.729605:  14%|█▍        | 7/50 [01:17<07:13, 10.09s/it]

[I 2025-12-02 03:33:24,628] Trial 5 finished with value: 0.225 and parameters: {'max_depth': 9, 'learning_rate': 0.029759663475239787, 'n_estimators': 1368, 'subsample': 0.7380038289717459, 'colsample_bytree': 0.9209546969721565, 'min_child_weight': 9, 'gamma': 0.521473239470055, 'reg_alpha': 0.03009700967156725, 'reg_lambda': 7.372173774886602e-07, 'max_delta_step': 10}. Best is trial 6 with value: 0.7296052631578948.

Best trial: 6. Best value: 0.729605:  16%|█▌        | 8/50 [01:40<10:03, 14.36s/it]

[I 2025-12-02 03:33:48,133] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.12271318262483139, 'n_estimators': 637, 'subsample': 0.8671430539347299, 'colsample_bytree': 0.8438753613827608, 'min_child_weight': 10, 'gamma': 4.403568301379323, 'reg_alpha': 0.35230759505532594, 'reg_lambda': 0.013050346830579509, 'max_delta_step': 1}. Best is trial 6 with value: 0.7296052631578948.

Best trial: 8. Best value: 0.730921:  18%|█▊        | 9/50 [01:46<07:54, 11.58s/it]

[I 2025-12-02 03:33:53,611] Trial 8 finished with value: 0.7309210526315789 and parameters: {'max_depth': 6, 'learning_rate': 0.11642841168776547, 'n_estimators': 1249, 'subsample': 0.8148112510286293, 'colsample_bytree': 0.645899874601283, 'min_child_weight': 9, 'gamma': 4.877504055889876, 'reg_alpha': 3.8471799609314687, 'reg_lambda': 0.0008636080918216266, 'max_delta_step': 7}. Best is trial 8 with value: 0.7309210526315789.

Best trial: 8. Best value: 0.730921:  20%|██        | 10/50 [01:52<06:40, 10.02s/it]

[I 2025-12-02 03:34:00,113] Trial 10 finished with value: 0.6769736842105263 and parameters: {'max_depth': 3, 'learning_rate': 0.03916504205678341, 'n_estimators': 846, 'subsample': 0.7077642291027735, 'colsample_bytree': 0.5420705777865364, 'min_child_weight': 6, 'gamma': 4.720538559367478, 'reg_alpha': 0.002917837953932288, 'reg_lambda': 3.2071936878702295e-07, 'max_delta_step': 3}. Best is trial 8 with value: 0.7309210526315789.

Best trial: 8. Best value: 0.730921:  22%|██▏       | 11/50 [02:01<06:22,  9.82s/it]

[I 2025-12-02 03:34:09,486] Trial 13 pruned.

Best trial: 8. Best value: 0.730921:  24%|██▍       | 12/50 [02:02<04:22,  6.90s/it]

[I 2025-12-02 03:34:09,704] Trial 7 finished with value: 0.7019736842105263 and parameters: {'max_depth': 3, 'learning_rate': 0.03498826001655709, 'n_estimators': 1313, 'subsample': 0.98392460399625, 'colsample_bytree': 0.9482167241497543, 'min_child_weight': 4, 'gamma': 4.228395461119252, 'reg_alpha': 0.04348684985261578, 'reg_lambda': 6.511489386472488e-08, 'max_delta_step': 9}. Best is trial 8 with value: 0.7309210526315789.

Best trial: 8. Best value: 0.730921:  26%|██▌       | 13/50 [02:10<04:28,  7.25s/it]

[I 2025-12-02 03:34:17,757] Trial 12 finished with value: 0.7282894736842105 and parameters: {'max_depth': 9, 'learning_rate': 0.14777107045321286, 'n_estimators': 484, 'subsample': 0.6543391276185077, 'colsample_bytree': 0.9646537414006588, 'min_child_weight': 3, 'gamma': 4.452234407383128, 'reg_alpha': 0.1684056709708107, 'reg_lambda': 0.985779780051793, 'max_delta_step': 6}. Best is trial 8 with value: 0.7309210526315789.

Best trial: 8. Best value: 0.730921:  28%|██▊       | 14/50 [02:11<03:11,  5.32s/it]

[I 2025-12-02 03:34:18,631] Trial 15 pruned.

Best trial: 8. Best value: 0.730921:  30%|███       | 15/50 [02:11<02:14,  3.83s/it]

[I 2025-12-02 03:34:19,005] Trial 14 pruned.

Best trial: 8. Best value: 0.730921:  32%|███▏      | 16/50 [02:11<01:32,  2.73s/it]

[I 2025-12-02 03:34:19,194] Trial 11 finished with value: 0.7019736842105263 and parameters: {'max_depth': 9, 'learning_rate': 0.2335627273829179, 'n_estimators': 641, 'subsample': 0.9911930438147136, 'colsample_bytree': 0.7224586014224272, 'min_child_weight': 1, 'gamma': 0.5462688784173902, 'reg_alpha': 2.5469702226292892e-08, 'reg_lambda': 0.0007489209486244229, 'max_delta_step': 0}. Best is trial 8 with value: 0.7309210526315789.

Best trial: 8. Best value: 0.730921:  34%|███▍      | 17/50 [02:16<01:50,  3.34s/it]

[I 2025-12-02 03:34:23,944] Trial 18 pruned.

Best trial: 8. Best value: 0.730921:  36%|███▌      | 18/50 [02:19<01:41,  3.16s/it]

[I 2025-12-02 03:34:26,700] Trial 19 pruned.

Best trial: 8. Best value: 0.730921:  38%|███▊      | 19/50 [02:19<01:14,  2.42s/it]

[I 2025-12-02 03:34:27,380] Trial 17 pruned.

Best trial: 8. Best value: 0.730921:  40%|████      | 20/50 [02:24<01:37,  3.25s/it]

[I 2025-12-02 03:34:32,570] Trial 20 pruned.

Best trial: 8. Best value: 0.730921:  42%|████▏     | 21/50 [02:35<02:34,  5.32s/it]

[I 2025-12-02 03:34:42,711] Trial 23 pruned.

Best trial: 8. Best value: 0.730921:  44%|████▍     | 22/50 [03:02<05:37, 12.06s/it]

[I 2025-12-02 03:35:10,491] Trial 16 finished with value: 0.7019736842105263 and parameters: {'max_depth': 5, 'learning_rate': 0.2741975077204511, 'n_estimators': 1142, 'subsample': 0.5133834088519058, 'colsample_bytree': 0.5407663307047337, 'min_child_weight': 1, 'gamma': 3.5936924811823867, 'reg_alpha': 9.1718530789471e-06, 'reg_lambda': 0.00621913075205793, 'max_delta_step': 0}. Best is trial 8 with value: 0.7309210526315789.

Best trial: 24. Best value: 0.767105:  46%|████▌     | 23/50 [03:04<04:01,  8.93s/it]

[I 2025-12-02 03:35:12,110] Trial 24 finished with value: 0.7671052631578947 and parameters: {'max_depth': 7, 'learning_rate': 0.14225307764464465, 'n_estimators': 465, 'subsample': 0.6626502074910199, 'colsample_bytree': 0.988071535836558, 'min_child_weight': 3, 'gamma': 4.381035026851794, 'reg_alpha': 0.007115023564649217, 'reg_lambda': 9.165682594434852, 'max_delta_step': 7}. Best is trial 24 with value: 0.7671052631578947.

Best trial: 24. Best value: 0.767105:  48%|████▊     | 24/50 [03:08<03:16,  7.54s/it]

[I 2025-12-02 03:35:16,422] Trial 25 pruned.

Best trial: 24. Best value: 0.767105:  50%|█████     | 25/50 [03:10<02:26,  5.87s/it]

[I 2025-12-02 03:35:18,393] Trial 26 pruned.

Best trial: 24. Best value: 0.767105:  52%|█████▏    | 26/50 [03:12<01:48,  4.54s/it]

[I 2025-12-02 03:35:19,836] Trial 21 finished with value: 0.7282894736842105 and parameters: {'max_depth': 4, 'learning_rate': 0.16088212653317882, 'n_estimators': 1252, 'subsample': 0.80139376316932, 'colsample_bytree': 0.5834256098607264, 'min_child_weight': 7, 'gamma': 2.8700673673513073, 'reg_alpha': 0.0002131823333899612, 'reg_lambda': 0.18907748086766285, 'max_delta_step': 8}. Best is trial 24 with value: 0.7671052631578947.

Best trial: 24. Best value: 0.767105:  54%|█████▍    | 27/50 [03:13<01:23,  3.62s/it]

[I 2025-12-02 03:35:21,304] Trial 22 finished with value: 0.7269736842105263 and parameters: {'max_depth': 7, 'learning_rate': 0.16432207197602444, 'n_estimators': 1259, 'subsample': 0.8061565014703926, 'colsample_bytree': 0.7396894008288049, 'min_child_weight': 7, 'gamma': 3.059832768670465, 'reg_alpha': 0.0009505444833133786, 'reg_lambda': 0.04858172138167846, 'max_delta_step': 8}. Best is trial 24 with value: 0.7671052631578947.

Best trial: 24. Best value: 0.767105:  56%|█████▌    | 28/50 [03:14<01:00,  2.73s/it]

[I 2025-12-02 03:35:21,966] Trial 29 pruned.

Best trial: 24. Best value: 0.767105:  58%|█████▊    | 29/50 [03:16<00:54,  2.60s/it]

[I 2025-12-02 03:35:24,256] Trial 30 pruned.

Best trial: 24. Best value: 0.767105:  60%|██████    | 30/50 [03:24<01:24,  4.25s/it]

[I 2025-12-02 03:35:32,345] Trial 28 finished with value: 0.7032894736842106 and parameters: {'max_depth': 4, 'learning_rate': 0.1065161288319676, 'n_estimators': 245, 'subsample': 0.7854530296171032, 'colsample_bytree': 0.6728928434668763, 'min_child_weight': 5, 'gamma': 2.525859025475316, 'reg_alpha': 1.0915355725992217, 'reg_lambda': 2.729290839954598e-06, 'max_delta_step': 4}. Best is trial 24 with value: 0.7671052631578947.

Best trial: 24. Best value: 0.767105:  62%|██████▏   | 31/50 [03:38<02:13,  7.02s/it]

[I 2025-12-02 03:35:45,834] Trial 32 finished with value: 0.7407894736842104 and parameters: {'max_depth': 6, 'learning_rate': 0.1057816126628429, 'n_estimators': 449, 'subsample': 0.5913599804682405, 'colsample_bytree': 0.8106307313749949, 'min_child_weight': 5, 'gamma': 0.016478398121133164, 'reg_alpha': 0.027975961770259617, 'reg_lambda': 0.004337622653813177, 'max_delta_step': 9}. Best is trial 24 with value: 0.7671052631578947.

Best trial: 24. Best value: 0.767105:  64%|██████▍   | 32/50 [03:41<01:47,  5.96s/it]

[I 2025-12-02 03:35:49,323] Trial 34 pruned.

Best trial: 24. Best value: 0.767105:  66%|██████▌   | 33/50 [03:47<01:41,  5.98s/it]

[I 2025-12-02 03:35:55,343] Trial 33 finished with value: 0.7144736842105264 and parameters: {'max_depth': 6, 'learning_rate': 0.2034867326025869, 'n_estimators': 421, 'subsample': 0.8539683435942842, 'colsample_bytree': 0.8384281479406663, 'min_child_weight': 2, 'gamma': 1.5824701278539306, 'reg_alpha': 0.016256749541640535, 'reg_lambda': 1.2010048350671685e-08, 'max_delta_step': 10}. Best is trial 24 with value: 0.7671052631578947.

Best trial: 24. Best value: 0.767105:  68%|██████▊   | 34/50 [04:02<02:16,  8.52s/it]

[I 2025-12-02 03:36:09,798] Trial 35 finished with value: 0.6519736842105264 and parameters: {'max_depth': 6, 'learning_rate': 0.10352425866583237, 'n_estimators': 350, 'subsample': 0.6899996397390064, 'colsample_bytree': 0.8275935962451958, 'min_child_weight': 4, 'gamma': 1.753166725329605, 'reg_alpha': 0.024323056264579635, 'reg_lambda': 0.00013560208415369754, 'max_delta_step': 9}. Best is trial 24 with value: 0.7671052631578947.

Best trial: 24. Best value: 0.767105:  70%|███████   | 35/50 [04:13<02:21,  9.42s/it]

[I 2025-12-02 03:36:21,319] Trial 27 finished with value: 0.7282894736842105 and parameters: {'max_depth': 7, 'learning_rate': 0.1795097420813507, 'n_estimators': 1497, 'subsample': 0.7952970794713727, 'colsample_bytree': 0.8492070639069808, 'min_child_weight': 7, 'gamma': 2.644541563033048, 'reg_alpha': 0.8703518778132946, 'reg_lambda': 4.093922965587999e-06, 'max_delta_step': 8}. Best is trial 24 with value: 0.7671052631578947.

Best trial: 24. Best value: 0.767105:  72%|███████▏  | 36/50 [04:16<01:42,  7.31s/it]

[I 2025-12-02 03:36:23,695] Trial 36 finished with value: 0.7032894736842106 and parameters: {'max_depth': 6, 'learning_rate': 0.09846942131306594, 'n_estimators': 558, 'subsample': 0.6928784033903569, 'colsample_bytree': 0.9963612814905864, 'min_child_weight': 6, 'gamma': 1.6181838258805212, 'reg_alpha': 0.008907878464577936, 'reg_lambda': 0.002654476628099002, 'max_delta_step': 9}. Best is trial 24 with value: 0.7671052631578947.

Best trial: 24. Best value: 0.767105:  74%|███████▍  | 37/50 [04:19<01:18,  6.06s/it]

[I 2025-12-02 03:36:26,840] Trial 31 finished with value: 0.6644736842105263 and parameters: {'max_depth': 4, 'learning_rate': 0.11196946480994212, 'n_estimators': 1479, 'subsample': 0.9245255660295136, 'colsample_bytree': 0.8401331459855518, 'min_child_weight': 5, 'gamma': 2.305711004034106, 'reg_alpha': 0.030909949057802522, 'reg_lambda': 0.0016914885444020674, 'max_delta_step': 10}. Best is trial 24 with value: 0.7671052631578947.

Best trial: 24. Best value: 0.767105:  76%|███████▌  | 38/50 [04:40<02:07, 10.60s/it]

[I 2025-12-02 03:36:48,046] Trial 37 finished with value: 0.7282894736842105 and parameters: {'max_depth': 7, 'learning_rate': 0.05047567422054091, 'n_estimators': 784, 'subsample': 0.5742646796581747, 'colsample_bytree': 0.9898847931772178, 'min_child_weight': 6, 'gamma': 3.912529215435764, 'reg_alpha': 0.33905520111629134, 'reg_lambda': 0.0013064929198383728, 'max_delta_step': 9}. Best is trial 24 with value: 0.7671052631578947.

Best trial: 24. Best value: 0.767105:  78%|███████▊  | 39/50 [04:49<01:51, 10.10s/it]

[I 2025-12-02 03:36:56,958] Trial 38 finished with value: 0.7157894736842105 and parameters: {'max_depth': 6, 'learning_rate': 0.05193494678150825, 'n_estimators': 711, 'subsample': 0.5966687619448255, 'colsample_bytree': 0.9874906374248725, 'min_child_weight': 6, 'gamma': 1.2450378883448154, 'reg_alpha': 0.25188679592960084, 'reg_lambda': 0.0026918789149671636, 'max_delta_step': 9}. Best is trial 24 with value: 0.7671052631578947.

Best trial: 24. Best value: 0.767105:  80%|████████  | 40/50 [04:51<01:17,  7.80s/it]

[I 2025-12-02 03:36:59,387] Trial 39 finished with value: 0.7019736842105263 and parameters: {'max_depth': 4, 'learning_rate': 0.04790724083046373, 'n_estimators': 758, 'subsample': 0.5840840360789722, 'colsample_bytree': 0.5782391275253882, 'min_child_weight': 5, 'gamma': 1.1083960994533684, 'reg_alpha': 0.1092749604778957, 'reg_lambda': 8.158730730158616e-05, 'max_delta_step': 2}. Best is trial 24 with value: 0.7671052631578947.

Best trial: 24. Best value: 0.767105:  82%|████████▏ | 41/50 [04:52<00:50,  5.61s/it]

[I 2025-12-02 03:36:59,907] Trial 40 finished with value: 0.6782894736842104 and parameters: {'max_depth': 5, 'learning_rate': 0.04925050285039802, 'n_estimators': 739, 'subsample': 0.7586308280874476, 'colsample_bytree': 0.5082869679188811, 'min_child_weight': 8, 'gamma': 1.2312522079607355, 'reg_alpha': 0.11528091408451831, 'reg_lambda': 9.545049768426883e-05, 'max_delta_step': 2}. Best is trial 24 with value: 0.7671052631578947.

Best trial: 24. Best value: 0.767105:  84%|████████▍ | 42/50 [05:06<01:06,  8.28s/it]

[I 2025-12-02 03:37:14,420] Trial 41 finished with value: 0.7559210526315789 and parameters: {'max_depth': 5, 'learning_rate': 0.13008714839223043, 'n_estimators': 573, 'subsample': 0.7642197216259209, 'colsample_bytree': 0.568142794964693, 'min_child_weight': 8, 'gamma': 1.0998414967953003, 'reg_alpha': 0.11153993179500386, 'reg_lambda': 4.0888437892234136e-05, 'max_delta_step': 2}. Best is trial 24 with value: 0.7671052631578947.

Best trial: 24. Best value: 0.767105:  86%|████████▌ | 43/50 [05:11<00:49,  7.06s/it]

[I 2025-12-02 03:37:18,624] Trial 45 pruned.

Best trial: 24. Best value: 0.767105:  88%|████████▊ | 44/50 [05:17<00:42,  7.03s/it]

[I 2025-12-02 03:37:25,572] Trial 46 pruned.

Best trial: 24. Best value: 0.767105:  90%|█████████ | 45/50 [05:21<00:29,  5.86s/it]

[I 2025-12-02 03:37:28,705] Trial 47 pruned.

Best trial: 24. Best value: 0.767105:  92%|█████████▏| 46/50 [05:24<00:20,  5.15s/it]

[I 2025-12-02 03:37:32,206] Trial 44 finished with value: 0.6769736842105263 and parameters: {'max_depth': 9, 'learning_rate': 0.14025360225892605, 'n_estimators': 515, 'subsample': 0.658688300304517, 'colsample_bytree': 0.9651930977059996, 'min_child_weight': 3, 'gamma': 4.352902274353206, 'reg_alpha': 2.485892949035649, 'reg_lambda': 1.344028052950278, 'max_delta_step': 6}. Best is trial 24 with value: 0.7671052631578947.

Best trial: 24. Best value: 0.767105:  94%|█████████▍| 47/50 [05:27<00:13,  4.36s/it]

[I 2025-12-02 03:37:34,710] Trial 48 pruned.

Best trial: 24. Best value: 0.767105:  96%|█████████▌| 48/50 [05:28<00:06,  3.49s/it]

[I 2025-12-02 03:37:36,167] Trial 42 finished with value: 0.6907894736842105 and parameters: {'max_depth': 5, 'learning_rate': 0.017307252440532148, 'n_estimators': 890, 'subsample': 0.747344742111793, 'colsample_bytree': 0.5042234144174034, 'min_child_weight': 8, 'gamma': 3.310581180127792, 'reg_alpha': 0.09449637352127876, 'reg_lambda': 8.449588567086846e-05, 'max_delta_step': 2}. Best is trial 24 with value: 0.7671052631578947.

Best trial: 24. Best value: 0.767105:  98%|█████████▊| 49/50 [05:29<00:02,  2.65s/it]

[I 2025-12-02 03:37:36,882] Trial 43 finished with value: 0.6769736842105263 and parameters: {'max_depth': 5, 'learning_rate': 0.01296102114555926, 'n_estimators': 859, 'subsample': 0.7592256189725374, 'colsample_bytree': 0.5047382798458578, 'min_child_weight': 8, 'gamma': 3.306706870273889, 'reg_alpha': 0.0004883656156707705, 'reg_lambda': 0.9484820901939932, 'max_delta_step': 7}. Best is trial 24 with value: 0.7671052631578947.

Best trial: 24. Best value: 0.767105: 100%|██████████| 50/50 [05:37<00:00,  6.75s/it]

[I 2025-12-02 03:37:45,183] Trial 49 finished with value: 0.6631578947368422 and parameters: {'max_depth': 5, 'learning_rate': 0.12412855507518955, 'n_estimators': 307, 'subsample': 0.830973439222087, 'colsample_bytree': 0.8981123036754199, 'min_child_weight': 2, 'gamma': 0.8152607717461482, 'reg_alpha': 0.401826063863359, 'reg_lambda': 0.051070389862320174, 'max_delta_step': 1}. Best is trial 24 with value: 0.7671052631578947.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 03:37:48,870] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.740693:   2%|▏         | 1/50 [00:19<16:12, 19.85s/it]

[I 2025-12-02 03:38:08,715] Trial 2 finished with value: 0.7406931964056482 and parameters: {'max_depth': 5, 'learning_rate': 0.27940599772722163, 'n_estimators': 403, 'subsample': 0.8640548652524381, 'colsample_bytree': 0.7727750880126897, 'min_child_weight': 4, 'gamma': 0.3031027717867901, 'reg_alpha': 7.846570276239096e-07, 'reg_lambda': 0.015551785388701429, 'max_delta_step': 0}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:   4%|▍         | 2/50 [00:41<16:38, 20.80s/it]

[I 2025-12-02 03:38:30,174] Trial 0 finished with value: 0.6957637997432606 and parameters: {'max_depth': 6, 'learning_rate': 0.10869616446326932, 'n_estimators': 971, 'subsample': 0.6689331311016339, 'colsample_bytree': 0.6636766744414434, 'min_child_weight': 8, 'gamma': 0.505264832544986, 'reg_alpha': 0.00015266104976932043, 'reg_lambda': 0.025175915511131533, 'max_delta_step': 8}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:   6%|▌         | 3/50 [00:43<09:45, 12.46s/it]

[I 2025-12-02 03:38:32,709] Trial 3 finished with value: 0.6713735558408216 and parameters: {'max_depth': 9, 'learning_rate': 0.167667718294774, 'n_estimators': 1018, 'subsample': 0.6251283158320117, 'colsample_bytree': 0.7989692769937867, 'min_child_weight': 8, 'gamma': 0.08436027262853807, 'reg_alpha': 2.363333008175756e-06, 'reg_lambda': 4.983702942577566e-08, 'max_delta_step': 9}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:   8%|▊         | 4/50 [01:03<11:51, 15.46s/it]

[I 2025-12-02 03:38:52,776] Trial 5 finished with value: 0.7163029525032092 and parameters: {'max_depth': 10, 'learning_rate': 0.04549577216798032, 'n_estimators': 441, 'subsample': 0.8544301055138754, 'colsample_bytree': 0.821741891982268, 'min_child_weight': 6, 'gamma': 2.5945620635924733, 'reg_alpha': 1.2932885874766332e-07, 'reg_lambda': 0.00032383357818120765, 'max_delta_step': 5}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  10%|█         | 5/50 [01:07<08:22, 11.17s/it]

[I 2025-12-02 03:38:56,324] Trial 1 finished with value: 0.6373555840821565 and parameters: {'max_depth': 6, 'learning_rate': 0.1329112913692296, 'n_estimators': 1390, 'subsample': 0.6819851479365836, 'colsample_bytree': 0.8305784185147345, 'min_child_weight': 2, 'gamma': 2.9274018174786427, 'reg_alpha': 1.5919966844434312e-07, 'reg_lambda': 4.925341003944672e-07, 'max_delta_step': 6}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  12%|█▏        | 6/50 [01:25<09:50, 13.43s/it]

[I 2025-12-02 03:39:14,137] Trial 7 finished with value: 0.7021822849807445 and parameters: {'max_depth': 3, 'learning_rate': 0.10329635896190144, 'n_estimators': 444, 'subsample': 0.7653328420172114, 'colsample_bytree': 0.5228147400785446, 'min_child_weight': 4, 'gamma': 1.4729593328343482, 'reg_alpha': 5.992869968750406e-05, 'reg_lambda': 0.008556009304899167, 'max_delta_step': 7}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  14%|█▍        | 7/50 [01:25<06:36,  9.22s/it]

[I 2025-12-02 03:39:14,685] Trial 4 finished with value: 0.7163029525032092 and parameters: {'max_depth': 4, 'learning_rate': 0.015729965476813955, 'n_estimators': 1357, 'subsample': 0.7531299358770923, 'colsample_bytree': 0.911846277346908, 'min_child_weight': 6, 'gamma': 3.7166503898381897, 'reg_alpha': 0.001113294466178945, 'reg_lambda': 7.3973538048961755e-06, 'max_delta_step': 0}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  16%|█▌        | 8/50 [01:36<06:49,  9.74s/it]

[I 2025-12-02 03:39:25,563] Trial 6 finished with value: 0.7163029525032092 and parameters: {'max_depth': 8, 'learning_rate': 0.06927452995084915, 'n_estimators': 1226, 'subsample': 0.7035511993360699, 'colsample_bytree': 0.6902574123564292, 'min_child_weight': 5, 'gamma': 4.141568369031763, 'reg_alpha': 3.803752068350632e-08, 'reg_lambda': 1.0247915171217757e-07, 'max_delta_step': 5}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  18%|█▊        | 9/50 [01:53<08:04, 11.82s/it]

[I 2025-12-02 03:39:41,954] Trial 8 finished with value: 0.7284980744544287 and parameters: {'max_depth': 6, 'learning_rate': 0.07940740972865043, 'n_estimators': 958, 'subsample': 0.6683208768482087, 'colsample_bytree': 0.9176031902475603, 'min_child_weight': 5, 'gamma': 3.623386855866081, 'reg_alpha': 3.8519866433575344e-07, 'reg_lambda': 2.1583545626946086e-07, 'max_delta_step': 5}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  20%|██        | 10/50 [02:04<07:46, 11.67s/it]

[I 2025-12-02 03:39:53,293] Trial 9 finished with value: 0.7163029525032092 and parameters: {'max_depth': 6, 'learning_rate': 0.04456521298903143, 'n_estimators': 889, 'subsample': 0.9098284935581693, 'colsample_bytree': 0.6506445342150884, 'min_child_weight': 7, 'gamma': 1.9821868610766775, 'reg_alpha': 1.437355482902567e-05, 'reg_lambda': 0.00012619249487442054, 'max_delta_step': 9}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  22%|██▏       | 11/50 [02:07<05:51,  9.00s/it]

[I 2025-12-02 03:39:56,233] Trial 13 pruned.

Best trial: 2. Best value: 0.740693:  24%|██▍       | 12/50 [02:11<04:43,  7.47s/it]

[I 2025-12-02 03:40:00,208] Trial 10 finished with value: 0.7284980744544287 and parameters: {'max_depth': 4, 'learning_rate': 0.12141889187854223, 'n_estimators': 1108, 'subsample': 0.97518614686227, 'colsample_bytree': 0.5991264985115325, 'min_child_weight': 7, 'gamma': 0.2945329984594258, 'reg_alpha': 0.0003277114482693749, 'reg_lambda': 1.82428244080161e-06, 'max_delta_step': 7}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  26%|██▌       | 13/50 [02:12<03:28,  5.63s/it]

[I 2025-12-02 03:40:01,610] Trial 14 pruned.

Best trial: 2. Best value: 0.740693:  28%|██▊       | 14/50 [02:16<03:04,  5.12s/it]

[I 2025-12-02 03:40:05,538] Trial 15 pruned.

Best trial: 2. Best value: 0.740693:  30%|███       | 15/50 [02:25<03:40,  6.30s/it]

[I 2025-12-02 03:40:14,572] Trial 11 finished with value: 0.6655969191270861 and parameters: {'max_depth': 9, 'learning_rate': 0.09681089679832933, 'n_estimators': 1189, 'subsample': 0.5231785027655067, 'colsample_bytree': 0.7657368367359232, 'min_child_weight': 4, 'gamma': 3.5126303879558876, 'reg_alpha': 2.532636058264846e-08, 'reg_lambda': 0.1273731863738332, 'max_delta_step': 2}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  32%|███▏      | 16/50 [02:44<05:38,  9.96s/it]

[I 2025-12-02 03:40:33,020] Trial 17 finished with value: 0.6777920410783055 and parameters: {'max_depth': 5, 'learning_rate': 0.2292407791033229, 'n_estimators': 677, 'subsample': 0.560712462713806, 'colsample_bytree': 0.8974408587399901, 'min_child_weight': 3, 'gamma': 4.850660689493958, 'reg_alpha': 1.1504106299611193e-08, 'reg_lambda': 1.0509710198296185e-08, 'max_delta_step': 2}. Best is trial 2 with value: 0.7406931964056482.
[I 2025-12-02 03:40:33,067] Trial 16 finished with value: 0.6758664955070603 and parameters: {'max_depth': 5, 'learning_rate': 0.26092343817821173, 'n_estimators': 709, 'subsample': 0.8342461239516739, 'colsample_bytree': 0.9327918854217214, 'min_child_weight': 3, 'gamma': 3.3312024690399302, 'reg_alpha': 1.1987687410198602e-06, 'reg_lambda': 0.0005401381589685274, 'max_delta_step': 2}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  36%|███▌      | 18/50 [02:54<04:07,  7.72s/it]

[I 2025-12-02 03:40:43,261] Trial 18 finished with value: 0.6777920410783055 and parameters: {'max_depth': 5, 'learning_rate': 0.24171638303069748, 'n_estimators': 695, 'subsample': 0.5919535384777094, 'colsample_bytree': 0.8914865444397159, 'min_child_weight': 3, 'gamma': 4.988524521893679, 'reg_alpha': 1.3557414817343954e-06, 'reg_lambda': 0.0024567750879933795, 'max_delta_step': 2}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  38%|███▊      | 19/50 [02:59<03:38,  7.06s/it]

[I 2025-12-02 03:40:48,337] Trial 20 finished with value: 0.6777920410783055 and parameters: {'max_depth': 5, 'learning_rate': 0.031973913016054276, 'n_estimators': 249, 'subsample': 0.6077320326924953, 'colsample_bytree': 0.8647123929612828, 'min_child_weight': 5, 'gamma': 1.9871281537845105, 'reg_alpha': 0.005525067288637797, 'reg_lambda': 1.8488051776791103e-05, 'max_delta_step': 10}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  40%|████      | 20/50 [03:00<02:42,  5.42s/it]

[I 2025-12-02 03:40:49,138] Trial 12 finished with value: 0.6636713735558408 and parameters: {'max_depth': 4, 'learning_rate': 0.010071960953543463, 'n_estimators': 749, 'subsample': 0.9257781135060723, 'colsample_bytree': 0.8188371961101741, 'min_child_weight': 3, 'gamma': 0.5122430917091653, 'reg_alpha': 1.786161789309276e-08, 'reg_lambda': 1.8772630896028385e-07, 'max_delta_step': 10}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  42%|████▏     | 21/50 [03:04<02:27,  5.08s/it]

[I 2025-12-02 03:40:53,275] Trial 22 pruned.

Best trial: 2. Best value: 0.740693:  44%|████▍     | 22/50 [03:05<01:48,  3.87s/it]

[I 2025-12-02 03:40:54,057] Trial 23 pruned.

Best trial: 2. Best value: 0.740693:  46%|████▌     | 23/50 [03:06<01:22,  3.06s/it]

[I 2025-12-02 03:40:55,096] Trial 19 finished with value: 0.689987163029525 and parameters: {'max_depth': 5, 'learning_rate': 0.032787092360572714, 'n_estimators': 304, 'subsample': 0.8293451436503976, 'colsample_bytree': 0.8982651779864337, 'min_child_weight': 4, 'gamma': 2.049220883207843, 'reg_alpha': 4.3008356453696824e-06, 'reg_lambda': 0.0013423870467239188, 'max_delta_step': 4}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  48%|████▊     | 24/50 [03:09<01:21,  3.15s/it]

[I 2025-12-02 03:40:58,463] Trial 21 finished with value: 0.689987163029525 and parameters: {'max_depth': 3, 'learning_rate': 0.06127170399638768, 'n_estimators': 260, 'subsample': 0.7997289616278226, 'colsample_bytree': 0.7342765434446583, 'min_child_weight': 5, 'gamma': 2.0505320538008394, 'reg_alpha': 0.004282044504108807, 'reg_lambda': 1.7810692334415604e-05, 'max_delta_step': 10}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  50%|█████     | 25/50 [03:55<06:31, 15.65s/it]

[I 2025-12-02 03:41:44,303] Trial 24 finished with value: 0.6777920410783055 and parameters: {'max_depth': 4, 'learning_rate': 0.1703686167424662, 'n_estimators': 1089, 'subsample': 0.9910529379555604, 'colsample_bytree': 0.6100517567053513, 'min_child_weight': 7, 'gamma': 1.0176213195646366, 'reg_alpha': 1.3810070476764237e-05, 'reg_lambda': 3.5946276166976867e-06, 'max_delta_step': 7}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  52%|█████▏    | 26/50 [03:55<04:27, 11.13s/it]

[I 2025-12-02 03:41:44,633] Trial 25 finished with value: 0.689987163029525 and parameters: {'max_depth': 4, 'learning_rate': 0.16735307048242662, 'n_estimators': 1106, 'subsample': 0.9872506744179621, 'colsample_bytree': 0.5891897092374734, 'min_child_weight': 7, 'gamma': 0.00883244500164404, 'reg_alpha': 1.3153229105818302e-05, 'reg_lambda': 2.9082397832564167e-06, 'max_delta_step': 7}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  54%|█████▍    | 27/50 [03:57<03:10,  8.28s/it]

[I 2025-12-02 03:41:46,156] Trial 26 finished with value: 0.7163029525032092 and parameters: {'max_depth': 4, 'learning_rate': 0.17694325608606457, 'n_estimators': 1109, 'subsample': 0.9968821037954311, 'colsample_bytree': 0.6039489711664707, 'min_child_weight': 7, 'gamma': 0.8719799893648961, 'reg_alpha': 1.8559996911131177e-05, 'reg_lambda': 2.1539414056865782e-06, 'max_delta_step': 7}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  56%|█████▌    | 28/50 [04:02<02:44,  7.47s/it]

[I 2025-12-02 03:41:51,711] Trial 29 pruned.

Best trial: 2. Best value: 0.740693:  58%|█████▊    | 29/50 [04:04<01:57,  5.60s/it]

[I 2025-12-02 03:41:52,898] Trial 27 finished with value: 0.714377406931964 and parameters: {'max_depth': 4, 'learning_rate': 0.17158848367781612, 'n_estimators': 1180, 'subsample': 0.9854741742753599, 'colsample_bytree': 0.6001056565906024, 'min_child_weight': 7, 'gamma': 0.9618710194719247, 'reg_alpha': 2.7091740580247513e-05, 'reg_lambda': 2.8959417892111657e-06, 'max_delta_step': 6}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  60%|██████    | 30/50 [04:04<01:22,  4.11s/it]

[I 2025-12-02 03:41:53,526] Trial 30 pruned.

Best trial: 2. Best value: 0.740693:  62%|██████▏   | 31/50 [04:11<01:33,  4.90s/it]

[I 2025-12-02 03:42:00,268] Trial 32 pruned.

Best trial: 2. Best value: 0.740693:  64%|██████▍   | 32/50 [04:11<01:04,  3.59s/it]

[I 2025-12-02 03:42:00,796] Trial 33 pruned.

Best trial: 2. Best value: 0.740693:  66%|██████▌   | 33/50 [04:33<02:34,  9.11s/it]

[I 2025-12-02 03:42:22,810] Trial 28 finished with value: 0.7163029525032092 and parameters: {'max_depth': 7, 'learning_rate': 0.17490158728766927, 'n_estimators': 836, 'subsample': 0.9251210247908556, 'colsample_bytree': 0.584866812018577, 'min_child_weight': 7, 'gamma': 0.3529698060292156, 'reg_alpha': 3.0903222434967847e-07, 'reg_lambda': 2.2932152682202483e-06, 'max_delta_step': 6}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  68%|██████▊   | 34/50 [04:57<03:33, 13.36s/it]

[I 2025-12-02 03:42:46,116] Trial 31 finished with value: 0.7182284980744544 and parameters: {'max_depth': 6, 'learning_rate': 0.1399998761198336, 'n_estimators': 1277, 'subsample': 0.7239418215115587, 'colsample_bytree': 0.5030647775663114, 'min_child_weight': 6, 'gamma': 1.4068155856693032, 'reg_alpha': 0.0004036101219899761, 'reg_lambda': 3.292034375984309e-08, 'max_delta_step': 1}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  70%|███████   | 35/50 [05:06<03:00, 12.05s/it]

[I 2025-12-02 03:42:55,087] Trial 37 pruned.

Best trial: 2. Best value: 0.740693:  72%|███████▏  | 36/50 [05:16<02:41, 11.51s/it]

[I 2025-12-02 03:43:05,328] Trial 38 pruned.

Best trial: 2. Best value: 0.740693:  74%|███████▍  | 37/50 [05:24<02:16, 10.51s/it]

[I 2025-12-02 03:43:13,528] Trial 35 finished with value: 0.7163029525032092 and parameters: {'max_depth': 5, 'learning_rate': 0.010377490669255977, 'n_estimators': 1495, 'subsample': 0.6526634913863207, 'colsample_bytree': 0.8510327746168276, 'min_child_weight': 6, 'gamma': 3.037508873564876, 'reg_alpha': 0.0009320104638111644, 'reg_lambda': 2.4732614400790935e-07, 'max_delta_step': 0}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  76%|███████▌  | 38/50 [05:25<01:31,  7.60s/it]

[I 2025-12-02 03:43:14,330] Trial 34 finished with value: 0.7163029525032092 and parameters: {'max_depth': 5, 'learning_rate': 0.010807799036878651, 'n_estimators': 1392, 'subsample': 0.7500222327724302, 'colsample_bytree': 0.9347159841383605, 'min_child_weight': 6, 'gamma': 3.0528571552960786, 'reg_alpha': 0.0005667128590639018, 'reg_lambda': 0.01432284965542136, 'max_delta_step': 0}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  78%|███████▊  | 39/50 [05:44<02:02, 11.14s/it]

[I 2025-12-02 03:43:33,729] Trial 36 finished with value: 0.7163029525032092 and parameters: {'max_depth': 5, 'learning_rate': 0.010560796710405277, 'n_estimators': 1462, 'subsample': 0.6541907455807653, 'colsample_bytree': 0.7789470473232739, 'min_child_weight': 6, 'gamma': 3.112010488297936, 'reg_alpha': 0.0011669728733598324, 'reg_lambda': 2.037325503311121e-07, 'max_delta_step': 0}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  80%|████████  | 40/50 [06:10<02:35, 15.53s/it]

[I 2025-12-02 03:43:59,494] Trial 41 finished with value: 0.6919127086007703 and parameters: {'max_depth': 6, 'learning_rate': 0.0468134539279604, 'n_estimators': 1041, 'subsample': 0.7126208522663217, 'colsample_bytree': 0.5490370264629935, 'min_child_weight': 8, 'gamma': 2.4234601689784867, 'reg_alpha': 0.00010307740028726635, 'reg_lambda': 1.1148748102365088e-08, 'max_delta_step': 1}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  82%|████████▏ | 41/50 [06:12<01:42, 11.35s/it]

[I 2025-12-02 03:44:01,074] Trial 39 finished with value: 0.7021822849807445 and parameters: {'max_depth': 5, 'learning_rate': 0.13958946072601075, 'n_estimators': 1281, 'subsample': 0.7112097338515841, 'colsample_bytree': 0.5550484116707028, 'min_child_weight': 4, 'gamma': 2.4949453354539792, 'reg_alpha': 7.844851051866789e-05, 'reg_lambda': 1.0188292736728234e-08, 'max_delta_step': 0}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  84%|████████▍ | 42/50 [06:25<01:36, 12.05s/it]

[I 2025-12-02 03:44:14,782] Trial 40 finished with value: 0.7021822849807445 and parameters: {'max_depth': 6, 'learning_rate': 0.04892069726538916, 'n_estimators': 1285, 'subsample': 0.7164118493442287, 'colsample_bytree': 0.7015437100241155, 'min_child_weight': 4, 'gamma': 2.4516556796493543, 'reg_alpha': 7.148684117511195e-05, 'reg_lambda': 1.2741163708992872e-08, 'max_delta_step': 1}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  86%|████████▌ | 43/50 [06:47<01:43, 14.84s/it]

[I 2025-12-02 03:44:36,113] Trial 42 finished with value: 0.7284980744544287 and parameters: {'max_depth': 6, 'learning_rate': 0.04799262676280258, 'n_estimators': 1319, 'subsample': 0.7189427499140076, 'colsample_bytree': 0.7058525169461894, 'min_child_weight': 4, 'gamma': 2.536328991085925, 'reg_alpha': 5.036270332374614e-05, 'reg_lambda': 2.2451255550329775e-08, 'max_delta_step': 1}. Best is trial 2 with value: 0.7406931964056482.

Best trial: 2. Best value: 0.740693:  88%|████████▊ | 44/50 [06:51<01:10, 11.73s/it]

[I 2025-12-02 03:44:40,610] Trial 46 pruned.

Best trial: 44. Best value: 0.754814:  90%|█████████ | 45/50 [07:08<01:05, 13.13s/it]

[I 2025-12-02 03:44:57,006] Trial 44 finished with value: 0.754813863928113 and parameters: {'max_depth': 6, 'learning_rate': 0.10240519302498344, 'n_estimators': 1263, 'subsample': 0.7742705294923037, 'colsample_bytree': 0.6908729053067776, 'min_child_weight': 5, 'gamma': 3.7571198771012075, 'reg_alpha': 0.004457649020752392, 'reg_lambda': 8.059372302009573e-08, 'max_delta_step': 1}. Best is trial 44 with value: 0.754813863928113.

Best trial: 44. Best value: 0.754814:  92%|█████████▏| 46/50 [07:09<00:38,  9.74s/it]

[I 2025-12-02 03:44:58,826] Trial 43 finished with value: 0.7021822849807445 and parameters: {'max_depth': 8, 'learning_rate': 0.09437389525325579, 'n_estimators': 1313, 'subsample': 0.8774723780222029, 'colsample_bytree': 0.6333765058146745, 'min_child_weight': 4, 'gamma': 1.2868587574539103, 'reg_alpha': 7.18740857881008e-08, 'reg_lambda': 0.06313033671119644, 'max_delta_step': 1}. Best is trial 44 with value: 0.754813863928113.

Best trial: 44. Best value: 0.754814:  94%|█████████▍| 47/50 [07:20<00:29,  9.99s/it]

[I 2025-12-02 03:45:09,409] Trial 45 finished with value: 0.689987163029525 and parameters: {'max_depth': 4, 'learning_rate': 0.09474210772485273, 'n_estimators': 1203, 'subsample': 0.7726597723642075, 'colsample_bytree': 0.8030436039452767, 'min_child_weight': 5, 'gamma': 3.8671064484934816, 'reg_alpha': 7.956251574137945e-08, 'reg_lambda': 8.619009626572691e-08, 'max_delta_step': 1}. Best is trial 44 with value: 0.754813863928113.

Best trial: 44. Best value: 0.754814:  96%|█████████▌| 48/50 [07:36<00:23, 11.90s/it]

[I 2025-12-02 03:45:25,749] Trial 47 finished with value: 0.689987163029525 and parameters: {'max_depth': 8, 'learning_rate': 0.1040229980843059, 'n_estimators': 1190, 'subsample': 0.689844511827095, 'colsample_bytree': 0.6280909280176119, 'min_child_weight': 4, 'gamma': 0.7237865704003895, 'reg_alpha': 3.674958083663043e-07, 'reg_lambda': 9.372884991141466e-08, 'max_delta_step': 3}. Best is trial 44 with value: 0.754813863928113.

Best trial: 44. Best value: 0.754814:  98%|█████████▊| 49/50 [07:58<00:14, 14.73s/it]

[I 2025-12-02 03:45:47,108] Trial 49 finished with value: 0.6636713735558408 and parameters: {'max_depth': 10, 'learning_rate': 0.03800867998089321, 'n_estimators': 1157, 'subsample': 0.6883789826144739, 'colsample_bytree': 0.6942484998049788, 'min_child_weight': 2, 'gamma': 3.8497475232208274, 'reg_alpha': 7.423274544435292e-07, 'reg_lambda': 8.448756299281766e-08, 'max_delta_step': 3}. Best is trial 44 with value: 0.754813863928113.

Best trial: 44. Best value: 0.754814: 100%|██████████| 50/50 [08:01<00:00,  9.63s/it]

[I 2025-12-02 03:45:50,472] Trial 48 finished with value: 0.5988446726572528 and parameters: {'max_depth': 7, 'learning_rate': 0.036367896927691955, 'n_estimators': 1171, 'subsample': 0.8741894042553437, 'colsample_bytree': 0.6981688637062303, 'min_child_weight': 2, 'gamma': 3.8112893825568066, 'reg_alpha': 0.0427942687640326, 'reg_lambda': 8.920808316241314e-08, 'max_delta_step': 3}. Best is trial 44 with value: 0.754813863928113.
Training final model on full training set (LOO strategy)...

Evaluating on test set...

[I 2025-12-02 03:45:54,799] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.425:   2%|▏         | 1/50 [00:25<20:33, 25.18s/it]

[I 2025-12-02 03:46:19,971] Trial 2 finished with value: 0.425 and parameters: {'max_depth': 3, 'learning_rate': 0.019891605280635615, 'n_estimators': 623, 'subsample': 0.5046514862258724, 'colsample_bytree': 0.6841904384417565, 'min_child_weight': 7, 'gamma': 4.019389965470449, 'reg_alpha': 0.0003379649010079096, 'reg_lambda': 1.0978327238689794e-08, 'max_delta_step': 7}. Best is trial 2 with value: 0.425.

Best trial: 1. Best value: 0.792105:   4%|▍         | 2/50 [00:28<09:45, 12.19s/it]

[I 2025-12-02 03:46:23,074] Trial 1 finished with value: 0.7921052631578948 and parameters: {'max_depth': 6, 'learning_rate': 0.10977799823727621, 'n_estimators': 471, 'subsample': 0.7015352868256333, 'colsample_bytree': 0.8858008043281995, 'min_child_weight': 3, 'gamma': 2.943391785073998, 'reg_alpha': 5.7709028054970695, 'reg_lambda': 3.073080331610985e-05, 'max_delta_step': 10}. Best is trial 1 with value: 0.7921052631578948.

Best trial: 5. Best value: 0.858553:   8%|▊         | 4/50 [00:51<08:01, 10.48s/it]

[I 2025-12-02 03:46:46,249] Trial 5 finished with value: 0.8585526315789473 and parameters: {'max_depth': 3, 'learning_rate': 0.09706209936758223, 'n_estimators': 580, 'subsample': 0.9223281241452783, 'colsample_bytree': 0.9752943482954577, 'min_child_weight': 8, 'gamma': 1.8971570763063028, 'reg_alpha': 3.5333838920234473, 'reg_lambda': 1.343885818831794e-08, 'max_delta_step': 7}. Best is trial 5 with value: 0.8585526315789473.
[I 2025-12-02 03:46:46,411] Trial 3 finished with value: 0.8322368421052632 and parameters: {'max_depth': 8, 'learning_rate': 0.0423329365358299, 'n_estimators': 1361, 'subsample': 0.9032180389219222, 'colsample_bytree': 0.8056976256280062, 'min_child_weight': 9, 'gamma': 0.965096460920849, 'reg_alpha': 3.7214072307113936e-06, 'reg_lambda': 0.004334711574889562, 'max_delta_step': 4}. Best is trial 5 with value: 0.8585526315789473.

Best trial: 5. Best value: 0.858553:  10%|█         | 5/50 [01:01<07:44, 10.33s/it]

[I 2025-12-02 03:46:56,480] Trial 0 finished with value: 0.7532894736842105 and parameters: {'max_depth': 3, 'learning_rate': 0.013286411650979471, 'n_estimators': 1058, 'subsample': 0.8022385245199816, 'colsample_bytree': 0.8036858725153881, 'min_child_weight': 2, 'gamma': 0.8642003393778491, 'reg_alpha': 6.989813954388594e-08, 'reg_lambda': 0.0001599024724770634, 'max_delta_step': 7}. Best is trial 5 with value: 0.8585526315789473.

Best trial: 5. Best value: 0.858553:  12%|█▏        | 6/50 [01:13<08:03, 11.00s/it]

[I 2025-12-02 03:47:08,779] Trial 4 finished with value: 0.7921052631578948 and parameters: {'max_depth': 9, 'learning_rate': 0.01635294757383427, 'n_estimators': 1055, 'subsample': 0.8607329942290916, 'colsample_bytree': 0.937428100574575, 'min_child_weight': 4, 'gamma': 4.395874191075306, 'reg_alpha': 0.1773312779273188, 'reg_lambda': 2.5641649847493458e-05, 'max_delta_step': 6}. Best is trial 5 with value: 0.8585526315789473.

Best trial: 5. Best value: 0.858553:  14%|█▍        | 7/50 [01:33<09:48, 13.68s/it]

[I 2025-12-02 03:47:27,984] Trial 7 finished with value: 0.7921052631578948 and parameters: {'max_depth': 10, 'learning_rate': 0.13710913942811218, 'n_estimators': 1030, 'subsample': 0.7303141880556456, 'colsample_bytree': 0.8591461670090783, 'min_child_weight': 6, 'gamma': 1.506001903893333, 'reg_alpha': 8.906894188992349e-07, 'reg_lambda': 5.5786848854725164e-08, 'max_delta_step': 4}. Best is trial 5 with value: 0.8585526315789473.

Best trial: 5. Best value: 0.858553:  16%|█▌        | 8/50 [01:34<06:53,  9.84s/it]

[I 2025-12-02 03:47:29,581] Trial 6 finished with value: 0.7657894736842106 and parameters: {'max_depth': 3, 'learning_rate': 0.01696044152308863, 'n_estimators': 1088, 'subsample': 0.5895495837548147, 'colsample_bytree': 0.6360366322539879, 'min_child_weight': 6, 'gamma': 2.419801616114829, 'reg_alpha': 0.16930132694703395, 'reg_lambda': 0.12666702938109847, 'max_delta_step': 9}. Best is trial 5 with value: 0.8585526315789473.

Best trial: 5. Best value: 0.858553:  18%|█▊        | 9/50 [01:56<09:11, 13.46s/it]

[I 2025-12-02 03:47:51,003] Trial 9 finished with value: 0.805921052631579 and parameters: {'max_depth': 5, 'learning_rate': 0.027481246411616464, 'n_estimators': 1043, 'subsample': 0.9703698216109538, 'colsample_bytree': 0.819655900436476, 'min_child_weight': 9, 'gamma': 1.0982044778835904, 'reg_alpha': 1.6934611056120377e-08, 'reg_lambda': 6.425390651225144, 'max_delta_step': 5}. Best is trial 5 with value: 0.8585526315789473.

Best trial: 5. Best value: 0.858553:  20%|██        | 10/50 [02:06<08:14, 12.35s/it]

[I 2025-12-02 03:48:00,882] Trial 11 finished with value: 0.5815789473684211 and parameters: {'max_depth': 8, 'learning_rate': 0.015512175022899677, 'n_estimators': 794, 'subsample': 0.5405581916823001, 'colsample_bytree': 0.649052969799194, 'min_child_weight': 7, 'gamma': 3.663815451620957, 'reg_alpha': 6.820068945741252e-07, 'reg_lambda': 0.004714528320688678, 'max_delta_step': 3}. Best is trial 5 with value: 0.8585526315789473.

Best trial: 5. Best value: 0.858553:  22%|██▏       | 11/50 [02:07<05:55,  9.11s/it]

[I 2025-12-02 03:48:02,651] Trial 8 finished with value: 0.7934210526315789 and parameters: {'max_depth': 8, 'learning_rate': 0.03036794070367255, 'n_estimators': 1078, 'subsample': 0.7348954295540813, 'colsample_bytree': 0.5803800229745313, 'min_child_weight': 1, 'gamma': 2.7521537593652172, 'reg_alpha': 5.906077023881367, 'reg_lambda': 4.0872655419374736e-05, 'max_delta_step': 8}. Best is trial 5 with value: 0.8585526315789473.

Best trial: 5. Best value: 0.858553:  24%|██▍       | 12/50 [02:08<04:07,  6.52s/it]

[I 2025-12-02 03:48:03,245] Trial 13 pruned.

Best trial: 5. Best value: 0.858553:  26%|██▌       | 13/50 [02:15<04:10,  6.76s/it]

[I 2025-12-02 03:48:10,547] Trial 12 pruned.

Best trial: 5. Best value: 0.858553:  28%|██▊       | 14/50 [02:19<03:27,  5.76s/it]

[I 2025-12-02 03:48:13,986] Trial 14 pruned.

Best trial: 5. Best value: 0.858553:  30%|███       | 15/50 [02:23<03:06,  5.32s/it]

[I 2025-12-02 03:48:18,298] Trial 17 pruned.

Best trial: 5. Best value: 0.858553:  32%|███▏      | 16/50 [02:36<04:19,  7.62s/it]

[I 2025-12-02 03:48:31,268] Trial 10 finished with value: 0.7796052631578947 and parameters: {'max_depth': 8, 'learning_rate': 0.03436456634945352, 'n_estimators': 1449, 'subsample': 0.9520967295824918, 'colsample_bytree': 0.5095357420132116, 'min_child_weight': 3, 'gamma': 3.1021705607227816, 'reg_alpha': 2.0030884290501291e-07, 'reg_lambda': 0.02532737242579966, 'max_delta_step': 0}. Best is trial 5 with value: 0.8585526315789473.

Best trial: 5. Best value: 0.858553:  34%|███▍      | 17/50 [02:59<06:39, 12.11s/it]

[I 2025-12-02 03:48:53,807] Trial 18 finished with value: 0.8322368421052632 and parameters: {'max_depth': 7, 'learning_rate': 0.039516511674587945, 'n_estimators': 789, 'subsample': 0.9087354358398028, 'colsample_bytree': 0.9864302973123888, 'min_child_weight': 8, 'gamma': 0.20815146253753558, 'reg_alpha': 0.012301323864158506, 'reg_lambda': 0.03061970212042181, 'max_delta_step': 2}. Best is trial 5 with value: 0.8585526315789473.

Best trial: 5. Best value: 0.858553:  36%|███▌      | 18/50 [03:10<06:24, 12.00s/it]

[I 2025-12-02 03:49:05,561] Trial 15 finished with value: 0.8585526315789473 and parameters: {'max_depth': 7, 'learning_rate': 0.0685735545936485, 'n_estimators': 1421, 'subsample': 0.8895123312722983, 'colsample_bytree': 0.9949835635894823, 'min_child_weight': 9, 'gamma': 0.07424515882400584, 'reg_alpha': 1.4492717766614334e-05, 'reg_lambda': 0.013139546784103862, 'max_delta_step': 2}. Best is trial 5 with value: 0.8585526315789473.

Best trial: 5. Best value: 0.858553:  38%|███▊      | 19/50 [03:12<04:35,  8.88s/it]

[I 2025-12-02 03:49:07,152] Trial 19 finished with value: 0.8447368421052632 and parameters: {'max_depth': 7, 'learning_rate': 0.08277353577718322, 'n_estimators': 805, 'subsample': 0.8928964622008767, 'colsample_bytree': 0.9757977239510107, 'min_child_weight': 8, 'gamma': 0.3581876457149402, 'reg_alpha': 0.008535349937545521, 'reg_lambda': 2.0763620366921497e-06, 'max_delta_step': 2}. Best is trial 5 with value: 0.8585526315789473.

Best trial: 5. Best value: 0.858553:  40%|████      | 20/50 [03:19<04:13,  8.45s/it]

[I 2025-12-02 03:49:14,622] Trial 16 finished with value: 0.8322368421052632 and parameters: {'max_depth': 8, 'learning_rate': 0.05860903640417146, 'n_estimators': 1450, 'subsample': 0.9029377302921272, 'colsample_bytree': 0.9964526266935405, 'min_child_weight': 8, 'gamma': 1.6673743813658544, 'reg_alpha': 7.660496970016172e-05, 'reg_lambda': 0.005086173852982251, 'max_delta_step': 2}. Best is trial 5 with value: 0.8585526315789473.

Best trial: 5. Best value: 0.858553:  42%|████▏     | 21/50 [03:38<05:36, 11.61s/it]

[I 2025-12-02 03:49:33,607] Trial 21 finished with value: 0.8184210526315789 and parameters: {'max_depth': 4, 'learning_rate': 0.0920288492559074, 'n_estimators': 579, 'subsample': 0.8099028620491279, 'colsample_bytree': 0.902385131902823, 'min_child_weight': 5, 'gamma': 1.8759254340045424, 'reg_alpha': 2.5424318607894424e-05, 'reg_lambda': 1.0270503675973674e-06, 'max_delta_step': 2}. Best is trial 5 with value: 0.8585526315789473.

Best trial: 5. Best value: 0.858553:  44%|████▍     | 22/50 [03:47<05:02, 10.81s/it]

[I 2025-12-02 03:49:42,541] Trial 23 finished with value: 0.7657894736842106 and parameters: {'max_depth': 10, 'learning_rate': 0.28588700754580554, 'n_estimators': 611, 'subsample': 0.822512479548555, 'colsample_bytree': 0.9089658611440994, 'min_child_weight': 5, 'gamma': 4.874151001158067, 'reg_alpha': 1.0348516259872364e-05, 'reg_lambda': 2.720957755701642, 'max_delta_step': 8}. Best is trial 5 with value: 0.8585526315789473.

Best trial: 20. Best value: 0.871053:  46%|████▌     | 23/50 [03:55<04:26,  9.86s/it]

[I 2025-12-02 03:49:50,177] Trial 20 finished with value: 0.8710526315789473 and parameters: {'max_depth': 10, 'learning_rate': 0.09487646142190317, 'n_estimators': 1305, 'subsample': 0.8446260202632017, 'colsample_bytree': 0.7550727529036201, 'min_child_weight': 8, 'gamma': 1.7562557180676164, 'reg_alpha': 1.3731462698640335e-05, 'reg_lambda': 2.6980942981334123e-06, 'max_delta_step': 6}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053:  48%|████▊     | 24/50 [04:04<04:09,  9.59s/it]

[I 2025-12-02 03:49:59,132] Trial 26 pruned.

Best trial: 20. Best value: 0.871053:  50%|█████     | 25/50 [04:07<03:11,  7.68s/it]

[I 2025-12-02 03:50:02,344] Trial 22 finished with value: 0.7657894736842106 and parameters: {'max_depth': 4, 'learning_rate': 0.29693379171233525, 'n_estimators': 1234, 'subsample': 0.8325585088690985, 'colsample_bytree': 0.9047452347706167, 'min_child_weight': 5, 'gamma': 1.8336777695085835, 'reg_alpha': 5.384932909302107e-05, 'reg_lambda': 3.6056030261502703, 'max_delta_step': 7}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053:  52%|█████▏    | 26/50 [04:30<04:51, 12.13s/it]

[I 2025-12-02 03:50:24,887] Trial 25 finished with value: 0.8710526315789473 and parameters: {'max_depth': 7, 'learning_rate': 0.0750889667569781, 'n_estimators': 907, 'subsample': 0.8616514393854728, 'colsample_bytree': 0.9574786245303454, 'min_child_weight': 9, 'gamma': 0.06429529680006547, 'reg_alpha': 0.004498969066243735, 'reg_lambda': 3.8658217317835746e-06, 'max_delta_step': 1}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053:  54%|█████▍    | 27/50 [04:34<03:42,  9.69s/it]

[I 2025-12-02 03:50:28,879] Trial 24 finished with value: 0.8184210526315789 and parameters: {'max_depth': 7, 'learning_rate': 0.08431981106000644, 'n_estimators': 1243, 'subsample': 0.855554729559658, 'colsample_bytree': 0.9324674151131025, 'min_child_weight': 9, 'gamma': 0.07010299700097017, 'reg_alpha': 0.01276144433554353, 'reg_lambda': 4.683113260717244e-06, 'max_delta_step': 1}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053:  56%|█████▌    | 28/50 [05:01<05:28, 14.93s/it]

[I 2025-12-02 03:50:56,046] Trial 27 finished with value: 0.8184210526315789 and parameters: {'max_depth': 4, 'learning_rate': 0.12376186180445353, 'n_estimators': 1269, 'subsample': 0.6541226107692182, 'colsample_bytree': 0.9340900089127924, 'min_child_weight': 7, 'gamma': 3.3629820968124373, 'reg_alpha': 0.4235979578767037, 'reg_lambda': 0.0007194621151518295, 'max_delta_step': 6}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053:  58%|█████▊    | 29/50 [05:02<03:48, 10.87s/it]

[I 2025-12-02 03:50:57,428] Trial 28 finished with value: 0.8447368421052632 and parameters: {'max_depth': 9, 'learning_rate': 0.07908281144074812, 'n_estimators': 1253, 'subsample': 0.6719691151350148, 'colsample_bytree': 0.7711920568421835, 'min_child_weight': 7, 'gamma': 3.366273922101772, 'reg_alpha': 0.502387841626338, 'reg_lambda': 5.750176628155276e-06, 'max_delta_step': 6}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053:  60%|██████    | 30/50 [05:10<03:20, 10.02s/it]

[I 2025-12-02 03:51:05,452] Trial 29 finished with value: 0.8447368421052632 and parameters: {'max_depth': 9, 'learning_rate': 0.11394100087713285, 'n_estimators': 919, 'subsample': 0.7714035575501487, 'colsample_bytree': 0.8473860501227939, 'min_child_weight': 7, 'gamma': 3.2894117580523217, 'reg_alpha': 0.36876846972890487, 'reg_lambda': 7.057161706644624e-06, 'max_delta_step': 6}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053:  62%|██████▏   | 31/50 [05:14<02:36,  8.24s/it]

[I 2025-12-02 03:51:09,542] Trial 30 finished with value: 0.7796052631578947 and parameters: {'max_depth': 9, 'learning_rate': 0.13957800158177372, 'n_estimators': 931, 'subsample': 0.66957310603274, 'colsample_bytree': 0.8346894140902984, 'min_child_weight': 7, 'gamma': 3.4157581330010425, 'reg_alpha': 0.6039097556480271, 'reg_lambda': 1.1684166054767448e-07, 'max_delta_step': 6}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053:  64%|██████▍   | 32/50 [05:20<02:12,  7.37s/it]

[I 2025-12-02 03:51:14,897] Trial 34 pruned.

Best trial: 20. Best value: 0.871053:  66%|██████▌   | 33/50 [05:20<01:28,  5.23s/it]

[I 2025-12-02 03:51:15,111] Trial 32 finished with value: 0.805921052631579 and parameters: {'max_depth': 6, 'learning_rate': 0.010556736446694607, 'n_estimators': 240, 'subsample': 0.9490452831060799, 'colsample_bytree': 0.8439988639008534, 'min_child_weight': 6, 'gamma': 1.122032454466959, 'reg_alpha': 1.0342184839181205, 'reg_lambda': 0.00022775199121739036, 'max_delta_step': 8}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053:  68%|██████▊   | 34/50 [05:23<01:12,  4.50s/it]

[I 2025-12-02 03:51:17,923] Trial 35 pruned.

Best trial: 20. Best value: 0.871053:  70%|███████   | 35/50 [05:23<00:48,  3.21s/it]

[I 2025-12-02 03:51:18,109] Trial 36 pruned.

Best trial: 20. Best value: 0.871053:  72%|███████▏  | 36/50 [05:24<00:38,  2.72s/it]

[I 2025-12-02 03:51:19,692] Trial 33 finished with value: 0.805921052631579 and parameters: {'max_depth': 6, 'learning_rate': 0.18120249903275032, 'n_estimators': 291, 'subsample': 0.9469026551635881, 'colsample_bytree': 0.8491723682437816, 'min_child_weight': 6, 'gamma': 1.24076457938096, 'reg_alpha': 0.06833363345049942, 'reg_lambda': 0.00019484109760417346, 'max_delta_step': 8}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053:  74%|███████▍  | 37/50 [05:42<01:32,  7.14s/it]

[I 2025-12-02 03:51:37,153] Trial 31 finished with value: 0.8447368421052632 and parameters: {'max_depth': 9, 'learning_rate': 0.047476191405034424, 'n_estimators': 938, 'subsample': 0.779420103515619, 'colsample_bytree': 0.8472584997246877, 'min_child_weight': 7, 'gamma': 0.7548263713107461, 'reg_alpha': 0.7047360843251568, 'reg_lambda': 1.490784869671804e-07, 'max_delta_step': 8}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053:  76%|███████▌  | 38/50 [06:22<03:24, 17.05s/it]

[I 2025-12-02 03:52:17,327] Trial 37 finished with value: 0.8184210526315789 and parameters: {'max_depth': 3, 'learning_rate': 0.1034391174133042, 'n_estimators': 1346, 'subsample': 0.8621324379439904, 'colsample_bytree': 0.9610272565780158, 'min_child_weight': 8, 'gamma': 1.3908056448928414, 'reg_alpha': 0.001154259725523908, 'reg_lambda': 4.096543412740363e-05, 'max_delta_step': 10}. Best is trial 20 with value: 0.8710526315789473.
[I 2025-12-02 03:52:17,342] Trial 38 finished with value: 0.7934210526315789 and parameters: {'max_depth': 3, 'learning_rate': 0.07096755187840884, 'n_estimators': 1339, 'subsample': 0.8581489122489622, 'colsample_bytree': 0.9535281361119511, 'min_child_weight': 8, 'gamma': 1.4621519394946394, 'reg_alpha': 0.0015726091939860223, 'reg_lambda': 2.2285719455935854e-05, 'max_delta_step': 4}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053:  80%|████████  | 40/50 [06:23<01:33,  9.38s/it]

[I 2025-12-02 03:52:18,171] Trial 39 finished with value: 0.8184210526315789 and parameters: {'max_depth': 3, 'learning_rate': 0.10323812530904945, 'n_estimators': 1340, 'subsample': 0.8672868553209337, 'colsample_bytree': 0.7828222738474209, 'min_child_weight': 8, 'gamma': 0.48733654689794104, 'reg_alpha': 3.019691628021514, 'reg_lambda': 2.5011309552569506e-05, 'max_delta_step': 4}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053:  82%|████████▏ | 41/50 [06:32<01:24,  9.41s/it]

[I 2025-12-02 03:52:27,701] Trial 40 finished with value: 0.805921052631579 and parameters: {'max_depth': 10, 'learning_rate': 0.09589458745973076, 'n_estimators': 1141, 'subsample': 0.867265893522828, 'colsample_bytree': 0.6963408750859784, 'min_child_weight': 8, 'gamma': 0.028033432629159673, 'reg_alpha': 0.0017310035522191296, 'reg_lambda': 0.0008272218997898783, 'max_delta_step': 4}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053:  84%|████████▍ | 42/50 [06:48<01:27, 10.95s/it]

[I 2025-12-02 03:52:42,975] Trial 42 finished with value: 0.805921052631579 and parameters: {'max_depth': 10, 'learning_rate': 0.09675241401106441, 'n_estimators': 523, 'subsample': 0.8774341989558799, 'colsample_bytree': 0.7940159234078142, 'min_child_weight': 9, 'gamma': 0.4808661112460814, 'reg_alpha': 3.284328110228046, 'reg_lambda': 0.0006611275410992496, 'max_delta_step': 7}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053:  86%|████████▌ | 43/50 [07:06<01:29, 12.82s/it]

[I 2025-12-02 03:53:00,811] Trial 44 finished with value: 0.8184210526315789 and parameters: {'max_depth': 7, 'learning_rate': 0.07010180076884114, 'n_estimators': 708, 'subsample': 0.89951854031079, 'colsample_bytree': 0.8846459373243469, 'min_child_weight': 9, 'gamma': 0.31643941673668863, 'reg_alpha': 0.007414107215328011, 'reg_lambda': 1.660191143207111e-06, 'max_delta_step': 1}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053:  88%|████████▊ | 44/50 [07:14<01:09, 11.55s/it]

[I 2025-12-02 03:53:09,080] Trial 43 finished with value: 0.7921052631578948 and parameters: {'max_depth': 10, 'learning_rate': 0.07189709327409094, 'n_estimators': 1158, 'subsample': 0.7995381917607836, 'colsample_bytree': 0.6872069967162161, 'min_child_weight': 9, 'gamma': 2.081218276995591, 'reg_alpha': 1.7292637944570998e-07, 'reg_lambda': 3.629959746208153e-07, 'max_delta_step': 7}. Best is trial 20 with value: 0.8710526315789473.
[I 2025-12-02 03:53:09,161] Trial 41 finished with value: 0.8447368421052632 and parameters: {'max_depth': 5, 'learning_rate': 0.09957442072221145, 'n_estimators': 1166, 'subsample': 0.877659088946997, 'colsample_bytree': 0.7880393758634026, 'min_child_weight': 9, 'gamma': 0.07678356560751241, 'reg_alpha': 2.686533220942428e-07, 'reg_lambda': 0.0010697820310411434, 'max_delta_step': 7}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053:  92%|█████████▏| 46/50 [07:20<00:31,  7.86s/it]

[I 2025-12-02 03:53:15,572] Trial 48 pruned.

Best trial: 20. Best value: 0.871053:  94%|█████████▍| 47/50 [07:21<00:18,  6.12s/it]

[I 2025-12-02 03:53:16,198] Trial 45 finished with value: 0.8322368421052632 and parameters: {'max_depth': 7, 'learning_rate': 0.07121536138575443, 'n_estimators': 713, 'subsample': 0.9061957402110078, 'colsample_bytree': 0.979630737921025, 'min_child_weight': 9, 'gamma': 0.30394204696259947, 'reg_alpha': 0.004902331132016548, 'reg_lambda': 7.431041374534143e-07, 'max_delta_step': 1}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053:  96%|█████████▌| 48/50 [07:25<00:11,  5.67s/it]

[I 2025-12-02 03:53:20,572] Trial 49 pruned.

Best trial: 20. Best value: 0.871053:  98%|█████████▊| 49/50 [07:33<00:06,  6.19s/it]

[I 2025-12-02 03:53:28,168] Trial 46 finished with value: 0.8447368421052632 and parameters: {'max_depth': 6, 'learning_rate': 0.07760666753981502, 'n_estimators': 696, 'subsample': 0.9157660944681139, 'colsample_bytree': 0.9817654721084937, 'min_child_weight': 9, 'gamma': 0.02254585608184024, 'reg_alpha': 4.0421998718170816e-07, 'reg_lambda': 2.8700616351626978e-08, 'max_delta_step': 3}. Best is trial 20 with value: 0.8710526315789473.

Best trial: 20. Best value: 0.871053: 100%|██████████| 50/50 [07:37<00:00,  9.16s/it]

[I 2025-12-02 03:53:32,782] Trial 47 finished with value: 0.805921052631579 and parameters: {'max_depth': 8, 'learning_rate': 0.054943049611995344, 'n_estimators': 729, 'subsample': 0.9134853609574896, 'colsample_bytree': 0.9742050243725128, 'min_child_weight': 8, 'gamma': 0.9124047278765643, 'reg_alpha': 0.03776427165482615, 'reg_lambda': 3.560484857734907e-08, 'max_delta_step': 3}. Best is trial 20 with value: 0.8710526315789473.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 03:53:36,176] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.655327:   2%|▏         | 1/50 [00:14<11:40, 14.30s/it]

[I 2025-12-02 03:53:50,466] Trial 0 finished with value: 0.6553273427471117 and parameters: {'max_depth': 9, 'learning_rate': 0.2907318419137747, 'n_estimators': 297, 'subsample': 0.7829257908473688, 'colsample_bytree': 0.872598832109984, 'min_child_weight': 9, 'gamma': 0.6774394127827016, 'reg_alpha': 4.159187904653348, 'reg_lambda': 1.6886090224928316e-06, 'max_delta_step': 7}. Best is trial 0 with value: 0.6553273427471117.

Best trial: 1. Best value: 0.74647:   4%|▍         | 2/50 [00:15<05:17,  6.62s/it]

[I 2025-12-02 03:53:51,706] Trial 1 finished with value: 0.7464698331193838 and parameters: {'max_depth': 4, 'learning_rate': 0.23615491745804332, 'n_estimators': 330, 'subsample': 0.7471137996804277, 'colsample_bytree': 0.6261205317938157, 'min_child_weight': 8, 'gamma': 0.9505820610298449, 'reg_alpha': 7.6950391485022624, 'reg_lambda': 1.9742464688502177e-05, 'max_delta_step': 6}. Best is trial 1 with value: 0.7464698331193838.

Best trial: 1. Best value: 0.74647:   6%|▌         | 3/50 [00:27<07:03,  9.00s/it]

[I 2025-12-02 03:54:03,552] Trial 2 finished with value: 0.6553273427471117 and parameters: {'max_depth': 6, 'learning_rate': 0.06898344650886953, 'n_estimators': 609, 'subsample': 0.5563907200797107, 'colsample_bytree': 0.8630430422565954, 'min_child_weight': 7, 'gamma': 3.634479567054207, 'reg_alpha': 1.5132779063580032e-06, 'reg_lambda': 0.034797749237039204, 'max_delta_step': 5}. Best is trial 1 with value: 0.7464698331193838.

Best trial: 4. Best value: 0.783055:   8%|▊         | 4/50 [00:56<13:07, 17.12s/it]

[I 2025-12-02 03:54:33,107] Trial 4 finished with value: 0.7830551989730423 and parameters: {'max_depth': 8, 'learning_rate': 0.09567554011991944, 'n_estimators': 1011, 'subsample': 0.7368451004048605, 'colsample_bytree': 0.5912659346360203, 'min_child_weight': 7, 'gamma': 0.5744156482280771, 'reg_alpha': 0.0011205961654264147, 'reg_lambda': 9.65686497836926e-08, 'max_delta_step': 1}. Best is trial 4 with value: 0.7830551989730423.

Best trial: 3. Best value: 0.79525:  10%|█         | 5/50 [00:58<08:32, 11.39s/it]

[I 2025-12-02 03:54:34,333] Trial 3 finished with value: 0.7952503209242618 and parameters: {'max_depth': 7, 'learning_rate': 0.01525924075579262, 'n_estimators': 1004, 'subsample': 0.8835552907255524, 'colsample_bytree': 0.7963045022531878, 'min_child_weight': 4, 'gamma': 3.5654068619228023, 'reg_alpha': 0.45380105646764246, 'reg_lambda': 1.5312833710836272e-07, 'max_delta_step': 0}. Best is trial 3 with value: 0.7952503209242618.

Best trial: 3. Best value: 0.79525:  12%|█▏        | 6/50 [00:59<05:44,  7.83s/it]

[I 2025-12-02 03:54:35,265] Trial 6 finished with value: 0.7952503209242618 and parameters: {'max_depth': 6, 'learning_rate': 0.17989428164204607, 'n_estimators': 693, 'subsample': 0.9804010374320479, 'colsample_bytree': 0.8787219033970493, 'min_child_weight': 6, 'gamma': 4.458926477110881, 'reg_alpha': 5.175147733643764e-08, 'reg_lambda': 4.487892147269153e-06, 'max_delta_step': 7}. Best is trial 3 with value: 0.7952503209242618.

Best trial: 3. Best value: 0.79525:  14%|█▍        | 7/50 [01:11<06:43,  9.39s/it]

[I 2025-12-02 03:54:47,860] Trial 5 finished with value: 0.6675224646983312 and parameters: {'max_depth': 5, 'learning_rate': 0.10379034135371003, 'n_estimators': 1362, 'subsample': 0.7259469473087241, 'colsample_bytree': 0.5911616347824905, 'min_child_weight': 9, 'gamma': 2.52008915597923, 'reg_alpha': 6.221867564017151, 'reg_lambda': 8.132116703809408e-05, 'max_delta_step': 9}. Best is trial 3 with value: 0.7952503209242618.

Best trial: 3. Best value: 0.79525:  16%|█▌        | 8/50 [01:14<05:06,  7.30s/it]

[I 2025-12-02 03:54:50,683] Trial 9 finished with value: 0.39473684210526316 and parameters: {'max_depth': 4, 'learning_rate': 0.06406433719006584, 'n_estimators': 307, 'subsample': 0.5274794424319031, 'colsample_bytree': 0.8724019156342209, 'min_child_weight': 8, 'gamma': 0.015104174372435608, 'reg_alpha': 0.0014026438866228447, 'reg_lambda': 0.2291270531681897, 'max_delta_step': 10}. Best is trial 3 with value: 0.7952503209242618.

Best trial: 10. Best value: 0.821566:  18%|█▊        | 9/50 [01:33<07:26, 10.89s/it]

[I 2025-12-02 03:55:09,468] Trial 10 finished with value: 0.8215661103979461 and parameters: {'max_depth': 7, 'learning_rate': 0.17553400707414862, 'n_estimators': 431, 'subsample': 0.8757696343839407, 'colsample_bytree': 0.8726204252677985, 'min_child_weight': 5, 'gamma': 0.06152570037563754, 'reg_alpha': 3.330792791489026e-06, 'reg_lambda': 4.60073529015364e-07, 'max_delta_step': 2}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  20%|██        | 10/50 [01:44<07:20, 11.02s/it]

[I 2025-12-02 03:55:20,776] Trial 7 finished with value: 0.7952503209242618 and parameters: {'max_depth': 3, 'learning_rate': 0.19946230364947204, 'n_estimators': 983, 'subsample': 0.8627557375743121, 'colsample_bytree': 0.6448918696708972, 'min_child_weight': 2, 'gamma': 1.7635744948109338, 'reg_alpha': 1.413265853217805e-08, 'reg_lambda': 1.5118952423129817, 'max_delta_step': 2}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  22%|██▏       | 11/50 [01:45<05:04,  7.81s/it]

[I 2025-12-02 03:55:21,295] Trial 12 finished with value: 0.730423620025674 and parameters: {'max_depth': 10, 'learning_rate': 0.23037764551716097, 'n_estimators': 204, 'subsample': 0.96228222725794, 'colsample_bytree': 0.7823771993204783, 'min_child_weight': 3, 'gamma': 0.9111738872421038, 'reg_alpha': 7.730809902261613e-05, 'reg_lambda': 6.674732395147517e-06, 'max_delta_step': 8}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  24%|██▍       | 12/50 [01:50<04:24,  6.96s/it]

[I 2025-12-02 03:55:26,331] Trial 8 finished with value: 0.6816431322207959 and parameters: {'max_depth': 10, 'learning_rate': 0.011683833268069807, 'n_estimators': 1225, 'subsample': 0.6523732555681843, 'colsample_bytree': 0.7581965408901126, 'min_child_weight': 8, 'gamma': 4.2436273847090735, 'reg_alpha': 0.2646794213969858, 'reg_lambda': 3.167323612446351e-07, 'max_delta_step': 5}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  26%|██▌       | 13/50 [02:00<04:52,  7.92s/it]

[I 2025-12-02 03:55:36,443] Trial 11 finished with value: 0.7689345314505777 and parameters: {'max_depth': 9, 'learning_rate': 0.16208482892945364, 'n_estimators': 1059, 'subsample': 0.900814875497368, 'colsample_bytree': 0.7036589921229879, 'min_child_weight': 4, 'gamma': 4.954322350688768, 'reg_alpha': 0.5584380817403125, 'reg_lambda': 0.0001839432384810929, 'max_delta_step': 2}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  28%|██▊       | 14/50 [02:25<07:54, 13.17s/it]

[I 2025-12-02 03:56:01,747] Trial 15 finished with value: 0.7952503209242618 and parameters: {'max_depth': 8, 'learning_rate': 0.02145595182001266, 'n_estimators': 615, 'subsample': 0.8779204524256142, 'colsample_bytree': 0.9952581359954942, 'min_child_weight': 4, 'gamma': 3.2072176047774876, 'reg_alpha': 2.850882311546457e-06, 'reg_lambda': 1.3739298245790077e-08, 'max_delta_step': 0}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  30%|███       | 15/50 [02:34<06:53, 11.82s/it]

[I 2025-12-02 03:56:10,447] Trial 16 finished with value: 0.7952503209242618 and parameters: {'max_depth': 7, 'learning_rate': 0.021970944353733576, 'n_estimators': 602, 'subsample': 0.8575987402312011, 'colsample_bytree': 0.9981946948851202, 'min_child_weight': 4, 'gamma': 3.0177817101740025, 'reg_alpha': 1.499443321994888e-05, 'reg_lambda': 2.1489472424028518e-08, 'max_delta_step': 0}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  34%|███▍      | 17/50 [02:48<04:53,  8.89s/it]

[I 2025-12-02 03:56:25,044] Trial 14 finished with value: 0.7689345314505777 and parameters: {'max_depth': 8, 'learning_rate': 0.016167919927594872, 'n_estimators': 1320, 'subsample': 0.8718869652099132, 'colsample_bytree': 0.9983622928702259, 'min_child_weight': 4, 'gamma': 3.0889513342797312, 'reg_alpha': 0.06609288008542519, 'reg_lambda': 3.2340800710699964e-08, 'max_delta_step': 0}. Best is trial 10 with value: 0.8215661103979461.
[I 2025-12-02 03:56:25,157] Trial 13 finished with value: 0.7426187419768935 and parameters: {'max_depth': 10, 'learning_rate': 0.028552442078731366, 'n_estimators': 1476, 'subsample': 0.9813855140551265, 'colsample_bytree': 0.9659208938240169, 'min_child_weight': 4, 'gamma': 2.002197942871641, 'reg_alpha': 4.8827267512392114e-06, 'reg_lambda': 0.003355229709695185, 'max_delta_step': 3}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  36%|███▌      | 18/50 [03:20<08:17, 15.54s/it]

[I 2025-12-02 03:56:56,187] Trial 17 finished with value: 0.7952503209242618 and parameters: {'max_depth': 7, 'learning_rate': 0.02899038549811369, 'n_estimators': 766, 'subsample': 0.8231531790232134, 'colsample_bytree': 0.9683610807553132, 'min_child_weight': 1, 'gamma': 2.4397544568241774, 'reg_alpha': 0.018789535987197067, 'reg_lambda': 0.0029390150642489535, 'max_delta_step': 3}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  38%|███▊      | 19/50 [03:25<06:27, 12.49s/it]

[I 2025-12-02 03:57:01,589] Trial 18 finished with value: 0.7952503209242618 and parameters: {'max_depth': 7, 'learning_rate': 0.03538662573588357, 'n_estimators': 872, 'subsample': 0.8021680522430242, 'colsample_bytree': 0.8089050460072622, 'min_child_weight': 1, 'gamma': 1.5556975494350782, 'reg_alpha': 0.030171661037040876, 'reg_lambda': 0.0032505477308024605, 'max_delta_step': 3}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  40%|████      | 20/50 [03:37<06:06, 12.22s/it]

[I 2025-12-02 03:57:13,185] Trial 19 finished with value: 0.7952503209242618 and parameters: {'max_depth': 7, 'learning_rate': 0.03770544612277405, 'n_estimators': 813, 'subsample': 0.8053485761726097, 'colsample_bytree': 0.8066854923518525, 'min_child_weight': 1, 'gamma': 1.9419940799384667, 'reg_alpha': 0.0064005128151783655, 'reg_lambda': 0.0007725682482993176, 'max_delta_step': 3}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  42%|████▏     | 21/50 [03:40<04:41,  9.69s/it]

[I 2025-12-02 03:57:16,976] Trial 21 finished with value: 0.7952503209242618 and parameters: {'max_depth': 5, 'learning_rate': 0.03921935229440761, 'n_estimators': 492, 'subsample': 0.9283813819958144, 'colsample_bytree': 0.5027460779587483, 'min_child_weight': 6, 'gamma': 3.8066702100873075, 'reg_alpha': 2.450918453146717e-07, 'reg_lambda': 4.616282888855881e-07, 'max_delta_step': 3}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  44%|████▍     | 22/50 [03:41<03:18,  7.10s/it]

[I 2025-12-02 03:57:18,031] Trial 20 finished with value: 0.7952503209242618 and parameters: {'max_depth': 7, 'learning_rate': 0.03202454413683953, 'n_estimators': 852, 'subsample': 0.8124178795752952, 'colsample_bytree': 0.8084468596570435, 'min_child_weight': 1, 'gamma': 1.9015456209689252, 'reg_alpha': 0.010416558922945724, 'reg_lambda': 6.70498870602915e-07, 'max_delta_step': 4}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  46%|████▌     | 23/50 [03:46<02:52,  6.39s/it]

[I 2025-12-02 03:57:22,773] Trial 22 finished with value: 0.7952503209242618 and parameters: {'max_depth': 5, 'learning_rate': 0.0443481766077128, 'n_estimators': 467, 'subsample': 0.9359217991542899, 'colsample_bytree': 0.7065836961430215, 'min_child_weight': 6, 'gamma': 3.7299973012786456, 'reg_alpha': 2.3460206423553217e-07, 'reg_lambda': 4.7485345631303853e-07, 'max_delta_step': 2}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  48%|████▊     | 24/50 [03:53<02:49,  6.50s/it]

[I 2025-12-02 03:57:29,538] Trial 24 pruned.

Best trial: 10. Best value: 0.821566:  50%|█████     | 25/50 [04:04<03:17,  7.89s/it]

[I 2025-12-02 03:57:40,655] Trial 25 finished with value: 0.8093709884467266 and parameters: {'max_depth': 6, 'learning_rate': 0.14264709384000726, 'n_estimators': 474, 'subsample': 0.9922977042636392, 'colsample_bytree': 0.8964109768337047, 'min_child_weight': 6, 'gamma': 4.841132199749181, 'reg_alpha': 1.1428239469626777e-08, 'reg_lambda': 6.201267572777893e-06, 'max_delta_step': 7}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  52%|█████▏    | 26/50 [04:05<02:21,  5.91s/it]

[I 2025-12-02 03:57:41,946] Trial 23 finished with value: 0.7952503209242618 and parameters: {'max_depth': 6, 'learning_rate': 0.011465175275666373, 'n_estimators': 462, 'subsample': 0.9228824509878604, 'colsample_bytree': 0.6995810933904835, 'min_child_weight': 6, 'gamma': 3.8868655736986515, 'reg_alpha': 2.8545533881466225e-07, 'reg_lambda': 5.142626003597499e-07, 'max_delta_step': 1}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  54%|█████▍    | 27/50 [04:12<02:22,  6.21s/it]

[I 2025-12-02 03:57:48,878] Trial 26 pruned.

Best trial: 10. Best value: 0.821566:  56%|█████▌    | 28/50 [04:16<02:01,  5.52s/it]

[I 2025-12-02 03:57:52,787] Trial 30 pruned.

Best trial: 10. Best value: 0.821566:  58%|█████▊    | 29/50 [04:25<02:18,  6.62s/it]

[I 2025-12-02 03:58:01,951] Trial 28 finished with value: 0.7952503209242618 and parameters: {'max_depth': 6, 'learning_rate': 0.10507707910778769, 'n_estimators': 430, 'subsample': 0.9203797991880383, 'colsample_bytree': 0.9284641489934485, 'min_child_weight': 5, 'gamma': 4.156428847335722, 'reg_alpha': 7.874110179829219e-05, 'reg_lambda': 3.424413192426466e-05, 'max_delta_step': 1}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  60%|██████    | 30/50 [04:27<01:42,  5.14s/it]

[I 2025-12-02 03:58:03,642] Trial 27 finished with value: 0.8215661103979461 and parameters: {'max_depth': 6, 'learning_rate': 0.10631449486117543, 'n_estimators': 739, 'subsample': 0.9315294625130697, 'colsample_bytree': 0.9103442274675707, 'min_child_weight': 5, 'gamma': 4.22740062766926, 'reg_alpha': 1.964705211473003e-07, 'reg_lambda': 2.096114779515681e-05, 'max_delta_step': 1}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  62%|██████▏   | 31/50 [04:32<01:39,  5.21s/it]

[I 2025-12-02 03:58:09,033] Trial 33 pruned.

Best trial: 10. Best value: 0.821566:  64%|██████▍   | 32/50 [04:39<01:40,  5.58s/it]

[I 2025-12-02 03:58:15,480] Trial 32 finished with value: 0.7933247753530167 and parameters: {'max_depth': 9, 'learning_rate': 0.28923676879018667, 'n_estimators': 223, 'subsample': 0.7739518508127736, 'colsample_bytree': 0.8966753064426342, 'min_child_weight': 3, 'gamma': 2.7503584150054268, 'reg_alpha': 2.087377817497605e-05, 'reg_lambda': 1.1588668842478663e-07, 'max_delta_step': 6}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  66%|██████▌   | 33/50 [04:54<02:23,  8.42s/it]

[I 2025-12-02 03:58:30,530] Trial 29 finished with value: 0.7952503209242618 and parameters: {'max_depth': 8, 'learning_rate': 0.11893286815297927, 'n_estimators': 1095, 'subsample': 0.9530154832348052, 'colsample_bytree': 0.9291238753096506, 'min_child_weight': 5, 'gamma': 4.264333879818665, 'reg_alpha': 3.869573696721335e-05, 'reg_lambda': 3.8000241630350936e-05, 'max_delta_step': 1}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  68%|██████▊   | 34/50 [04:59<02:00,  7.55s/it]

[I 2025-12-02 03:58:36,025] Trial 31 finished with value: 0.7933247753530167 and parameters: {'max_depth': 9, 'learning_rate': 0.07335551264050154, 'n_estimators': 928, 'subsample': 0.6824436784975496, 'colsample_bytree': 0.9175336994278508, 'min_child_weight': 3, 'gamma': 2.5681480545334265, 'reg_alpha': 4.7741008555647025e-05, 'reg_lambda': 3.458471725829885e-05, 'max_delta_step': 6}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  70%|███████   | 35/50 [05:02<01:29,  5.95s/it]

[I 2025-12-02 03:58:38,241] Trial 35 pruned.

Best trial: 10. Best value: 0.821566:  72%|███████▏  | 36/50 [05:17<02:04,  8.89s/it]

[I 2025-12-02 03:58:54,014] Trial 37 finished with value: 0.7567394094993581 and parameters: {'max_depth': 7, 'learning_rate': 0.05581285423632963, 'n_estimators': 370, 'subsample': 0.8942061500620768, 'colsample_bytree': 0.8430103508860657, 'min_child_weight': 7, 'gamma': 3.5067873025238656, 'reg_alpha': 1.0371327212639742e-06, 'reg_lambda': 1.364766249471218e-06, 'max_delta_step': 0}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  74%|███████▍  | 37/50 [05:18<01:23,  6.39s/it]

[I 2025-12-02 03:58:54,547] Trial 34 finished with value: 0.8074454428754814 and parameters: {'max_depth': 7, 'learning_rate': 0.07759987535599001, 'n_estimators': 942, 'subsample': 0.8907324375988008, 'colsample_bytree': 0.8472176002217048, 'min_child_weight': 3, 'gamma': 3.35466580494193, 'reg_alpha': 1.1932698702175831e-06, 'reg_lambda': 2.209007845797319e-06, 'max_delta_step': 0}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  76%|███████▌  | 38/50 [05:29<01:34,  7.86s/it]

[I 2025-12-02 03:59:05,853] Trial 38 finished with value: 0.7689345314505777 and parameters: {'max_depth': 4, 'learning_rate': 0.08412464963765552, 'n_estimators': 597, 'subsample': 0.8537690987720317, 'colsample_bytree': 0.8321840852699776, 'min_child_weight': 7, 'gamma': 3.995996416531243, 'reg_alpha': 7.066520605278705e-08, 'reg_lambda': 1.6756446238956068e-06, 'max_delta_step': 4}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  78%|███████▊  | 39/50 [05:35<01:21,  7.40s/it]

[I 2025-12-02 03:59:12,164] Trial 36 finished with value: 0.7952503209242618 and parameters: {'max_depth': 4, 'learning_rate': 0.07976032260752025, 'n_estimators': 944, 'subsample': 0.8993546753448133, 'colsample_bytree': 0.8500398100527317, 'min_child_weight': 7, 'gamma': 3.512316593908471, 'reg_alpha': 7.548587112934235e-07, 'reg_lambda': 1.317235254596276e-06, 'max_delta_step': 4}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  80%|████████  | 40/50 [05:43<01:14,  7.45s/it]

[I 2025-12-02 03:59:19,728] Trial 39 finished with value: 0.7586649550706033 and parameters: {'max_depth': 4, 'learning_rate': 0.13244175669851874, 'n_estimators': 567, 'subsample': 0.8406302864305465, 'colsample_bytree': 0.9554266037217898, 'min_child_weight': 7, 'gamma': 4.545359964483078, 'reg_alpha': 5.265931577164818e-08, 'reg_lambda': 1.0910882612749855e-05, 'max_delta_step': 4}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  82%|████████▏ | 41/50 [05:45<00:52,  5.88s/it]

[I 2025-12-02 03:59:21,939] Trial 40 finished with value: 0.7567394094993581 and parameters: {'max_depth': 4, 'learning_rate': 0.09015405974333841, 'n_estimators': 598, 'subsample': 0.8345667810564079, 'colsample_bytree': 0.9516278821635392, 'min_child_weight': 7, 'gamma': 4.632978384453051, 'reg_alpha': 5.0647406773266854e-08, 'reg_lambda': 1.0770872771017777e-05, 'max_delta_step': 4}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  84%|████████▍ | 42/50 [05:59<01:05,  8.21s/it]

[I 2025-12-02 03:59:35,585] Trial 43 pruned.

Best trial: 10. Best value: 0.821566:  86%|████████▌ | 43/50 [06:03<00:47,  6.83s/it]

[I 2025-12-02 03:59:39,206] Trial 44 pruned.

Best trial: 10. Best value: 0.821566:  88%|████████▊ | 44/50 [06:07<00:37,  6.27s/it]

[I 2025-12-02 03:59:44,152] Trial 41 finished with value: 0.7689345314505777 and parameters: {'max_depth': 6, 'learning_rate': 0.12805527007402148, 'n_estimators': 692, 'subsample': 0.8327506889778926, 'colsample_bytree': 0.956164076534154, 'min_child_weight': 2, 'gamma': 4.511487126833356, 'reg_alpha': 4.5135929685642574e-08, 'reg_lambda': 1.3294570783195443e-05, 'max_delta_step': 2}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  90%|█████████ | 45/50 [06:14<00:32,  6.48s/it]

[I 2025-12-02 03:59:51,118] Trial 42 finished with value: 0.7952503209242618 and parameters: {'max_depth': 5, 'learning_rate': 0.1384222959741336, 'n_estimators': 719, 'subsample': 0.835244868663201, 'colsample_bytree': 0.879524006980773, 'min_child_weight': 2, 'gamma': 4.704843380415472, 'reg_alpha': 3.5508233839958324e-08, 'reg_lambda': 1.3423058509177326e-05, 'max_delta_step': 8}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  92%|█████████▏| 46/50 [06:32<00:39,  9.77s/it]

[I 2025-12-02 04:00:08,585] Trial 45 finished with value: 0.7689345314505777 and parameters: {'max_depth': 6, 'learning_rate': 0.05059906097375121, 'n_estimators': 706, 'subsample': 0.9570865999464513, 'colsample_bytree': 0.7604180900218572, 'min_child_weight': 5, 'gamma': 0.4597905313566155, 'reg_alpha': 4.625179334934366e-06, 'reg_lambda': 1.5986186464712763e-07, 'max_delta_step': 2}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566:  94%|█████████▍| 47/50 [06:43<00:30, 10.02s/it]

[I 2025-12-02 04:00:19,198] Trial 48 pruned.

Best trial: 10. Best value: 0.821566:  96%|█████████▌| 48/50 [06:54<00:20, 10.37s/it]

[I 2025-12-02 04:00:30,365] Trial 46 finished with value: 0.7952503209242618 and parameters: {'max_depth': 5, 'learning_rate': 0.12188711020031925, 'n_estimators': 1213, 'subsample': 0.9722910181481275, 'colsample_bytree': 0.7494915004523952, 'min_child_weight': 5, 'gamma': 4.049503451898675, 'reg_alpha': 8.859352789912832e-06, 'reg_lambda': 2.179120415506496e-07, 'max_delta_step': 1}. Best is trial 10 with value: 0.8215661103979461.

Best trial: 10. Best value: 0.821566: 100%|██████████| 50/50 [06:55<00:00,  8.31s/it]

[I 2025-12-02 04:00:31,402] Trial 47 finished with value: 0.8093709884467266 and parameters: {'max_depth': 5, 'learning_rate': 0.1621103050113729, 'n_estimators': 1157, 'subsample': 0.8828961299414537, 'colsample_bytree': 0.7534373843939414, 'min_child_weight': 5, 'gamma': 4.060745192102797, 'reg_alpha': 6.034181788326659e-06, 'reg_lambda': 1.9420323451917679e-07, 'max_delta_step': 1}. Best is trial 10 with value: 0.8215661103979461.
[I 2025-12-02 04:00:31,555] Trial 49 pruned.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.754814                    0.70          0.56
1    17_1         loo       0.821566                    0.70          0.66
2     9_1         loo       0.767105                    0.65          0.76
3    19_1         loo       0.871053                    0.65          0.72

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.400000               0.6               0.8        50          60
1  0.400000               0.6               0.8        50          60
2  0.288675               0.8               0.5        50          59
3  0.288675               0.6               0.7        50          59

   test_size
0         15
1         15
2         15
3         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.754814                    0.70          0.56
1    17_1         loo       0.821566                    0.70          0.66
2     9_1         loo       0.767105                    0.65          0.76
3    19_1         loo       0.871053                    0.65          0.72

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.400000               0.6               0.8        50          60
1  0.400000               0.6               0.8        50          60
2  0.288675               0.8               0.5        50          59
3  0.288675               0.6               0.7        50          59

   test_size
0         15
1         15
2         15
3         15

In [1585]:
datasets = task_freq_dfs_pd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir="xgb_pd_hc_{CV_STRATEGY}_tasks/xgb_results_freq_pd_hc_extended_{CV_STRATEGY}_tasks",
    split_param="emb_",
)
print(summary)

[I 2025-12-02 04:00:36,141] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.808553:   2%|▏         | 1/50 [00:14<11:44, 14.38s/it]

[I 2025-12-02 04:00:50,512] Trial 3 finished with value: 0.8085526315789473 and parameters: {'max_depth': 5, 'learning_rate': 0.01985972392487538, 'n_estimators': 275, 'subsample': 0.9963555183385562, 'colsample_bytree': 0.8872078559735119, 'min_child_weight': 9, 'gamma': 4.295008881855028, 'reg_alpha': 2.3902800318694782e-05, 'reg_lambda': 0.05220727998809623, 'max_delta_step': 5}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:   4%|▍         | 2/50 [00:15<05:29,  6.87s/it]

[I 2025-12-02 04:00:52,123] Trial 2 finished with value: 0.7671052631578947 and parameters: {'max_depth': 8, 'learning_rate': 0.296322477425458, 'n_estimators': 346, 'subsample': 0.8708864076437522, 'colsample_bytree': 0.6616396986617692, 'min_child_weight': 9, 'gamma': 1.3620642588661318, 'reg_alpha': 4.955003147750257e-07, 'reg_lambda': 0.4728153668898489, 'max_delta_step': 6}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:   6%|▌         | 3/50 [00:38<10:53, 13.89s/it]

[I 2025-12-02 04:01:14,381] Trial 5 finished with value: 0.2625 and parameters: {'max_depth': 3, 'learning_rate': 0.24603779397950604, 'n_estimators': 546, 'subsample': 0.5272098331587347, 'colsample_bytree': 0.9006392722721441, 'min_child_weight': 8, 'gamma': 2.374383218124989, 'reg_alpha': 5.138277770932546, 'reg_lambda': 0.007152607555868077, 'max_delta_step': 5}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:   8%|▊         | 4/50 [00:42<07:52, 10.27s/it]

[I 2025-12-02 04:01:19,081] Trial 0 finished with value: 0.7421052631578948 and parameters: {'max_depth': 9, 'learning_rate': 0.010180457793320937, 'n_estimators': 1023, 'subsample': 0.9044813320414935, 'colsample_bytree': 0.7507006110044911, 'min_child_weight': 9, 'gamma': 2.1820004727008744, 'reg_alpha': 0.014436971921354924, 'reg_lambda': 1.857782333256788e-08, 'max_delta_step': 9}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  10%|█         | 5/50 [00:49<06:49,  9.10s/it]

[I 2025-12-02 04:01:26,112] Trial 4 finished with value: 0.6368421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.030622225976277947, 'n_estimators': 513, 'subsample': 0.7481746481475786, 'colsample_bytree': 0.9462153175149415, 'min_child_weight': 2, 'gamma': 0.5734258202357734, 'reg_alpha': 9.541295272641336e-08, 'reg_lambda': 1.7777580137527135e-05, 'max_delta_step': 9}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  12%|█▏        | 6/50 [00:54<05:34,  7.59s/it]

[I 2025-12-02 04:01:30,786] Trial 1 finished with value: 0.743421052631579 and parameters: {'max_depth': 7, 'learning_rate': 0.06434743412328019, 'n_estimators': 1263, 'subsample': 0.6483564522069989, 'colsample_bytree': 0.6071954114558327, 'min_child_weight': 4, 'gamma': 3.814326666543079, 'reg_alpha': 7.80399266345583, 'reg_lambda': 3.799804936330153e-06, 'max_delta_step': 8}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  14%|█▍        | 7/50 [01:11<07:38, 10.67s/it]

[I 2025-12-02 04:01:47,794] Trial 8 finished with value: 0.7697368421052632 and parameters: {'max_depth': 9, 'learning_rate': 0.23350056536205444, 'n_estimators': 486, 'subsample': 0.7439396080293752, 'colsample_bytree': 0.9608638149473137, 'min_child_weight': 8, 'gamma': 2.5987418537681832, 'reg_alpha': 1.0971853500085864e-06, 'reg_lambda': 0.44171701336512514, 'max_delta_step': 3}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  16%|█▌        | 8/50 [01:31<09:27, 13.52s/it]

[I 2025-12-02 04:02:07,411] Trial 10 finished with value: 0.075 and parameters: {'max_depth': 3, 'learning_rate': 0.0433092947835144, 'n_estimators': 465, 'subsample': 0.6873556489930746, 'colsample_bytree': 0.7865039824647009, 'min_child_weight': 10, 'gamma': 0.9173817411547486, 'reg_alpha': 4.450557524030784e-07, 'reg_lambda': 3.278568921475729e-08, 'max_delta_step': 6}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  18%|█▊        | 9/50 [01:37<07:38, 11.18s/it]

[I 2025-12-02 04:02:13,443] Trial 6 finished with value: 0.475 and parameters: {'max_depth': 5, 'learning_rate': 0.0339722843009573, 'n_estimators': 1458, 'subsample': 0.5261386964623225, 'colsample_bytree': 0.9709373741788627, 'min_child_weight': 8, 'gamma': 0.007829319354681341, 'reg_alpha': 2.7113394737455987e-07, 'reg_lambda': 5.172995739217527e-07, 'max_delta_step': 10}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  20%|██        | 10/50 [01:52<08:11, 12.30s/it]

[I 2025-12-02 04:02:28,241] Trial 9 finished with value: 0.425 and parameters: {'max_depth': 8, 'learning_rate': 0.13100854355769842, 'n_estimators': 1455, 'subsample': 0.7079881113479537, 'colsample_bytree': 0.6532386655694026, 'min_child_weight': 9, 'gamma': 2.225527384399752, 'reg_alpha': 0.01790481157910164, 'reg_lambda': 9.236173635617978e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  22%|██▏       | 11/50 [02:04<08:03, 12.39s/it]

[I 2025-12-02 04:02:40,832] Trial 7 finished with value: 0.5703947368421052 and parameters: {'max_depth': 8, 'learning_rate': 0.14613117362680528, 'n_estimators': 1338, 'subsample': 0.8676210242856124, 'colsample_bytree': 0.7458038002819147, 'min_child_weight': 1, 'gamma': 4.796598590890202, 'reg_alpha': 9.205945357702999e-06, 'reg_lambda': 0.03542066770579117, 'max_delta_step': 3}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  24%|██▍       | 12/50 [02:05<05:38,  8.90s/it]

[I 2025-12-02 04:02:41,749] Trial 12 finished with value: 0.6131578947368421 and parameters: {'max_depth': 4, 'learning_rate': 0.13438948747296, 'n_estimators': 671, 'subsample': 0.7775524080225911, 'colsample_bytree': 0.5326088206374251, 'min_child_weight': 6, 'gamma': 1.5211895400855062, 'reg_alpha': 1.1256330099130885, 'reg_lambda': 0.006655453330700063, 'max_delta_step': 2}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  26%|██▌       | 13/50 [02:07<04:05,  6.62s/it]

[I 2025-12-02 04:02:43,139] Trial 11 finished with value: 0.6394736842105263 and parameters: {'max_depth': 6, 'learning_rate': 0.19934638461227258, 'n_estimators': 872, 'subsample': 0.7328407846696692, 'colsample_bytree': 0.5368889754962194, 'min_child_weight': 6, 'gamma': 3.718382621964885, 'reg_alpha': 1.5748994137874524e-07, 'reg_lambda': 0.04624970106050122, 'max_delta_step': 3}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  28%|██▊       | 14/50 [02:19<04:59,  8.31s/it]

[I 2025-12-02 04:02:55,360] Trial 14 finished with value: 0.7171052631578947 and parameters: {'max_depth': 10, 'learning_rate': 0.01370015992866212, 'n_estimators': 206, 'subsample': 0.97713794126926, 'colsample_bytree': 0.8940718968025874, 'min_child_weight': 6, 'gamma': 3.5088886902725536, 'reg_alpha': 5.9949637617310694e-05, 'reg_lambda': 4.706515458710094, 'max_delta_step': 0}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  30%|███       | 15/50 [02:22<03:58,  6.81s/it]

[I 2025-12-02 04:02:58,680] Trial 16 finished with value: 0.743421052631579 and parameters: {'max_depth': 10, 'learning_rate': 0.016453389341450065, 'n_estimators': 236, 'subsample': 0.9817884208793008, 'colsample_bytree': 0.8709826257409548, 'min_child_weight': 7, 'gamma': 3.418505452602393, 'reg_alpha': 8.3918723428366e-06, 'reg_lambda': 5.997384481912837, 'max_delta_step': 0}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  32%|███▏      | 16/50 [02:23<02:48,  4.96s/it]

[I 2025-12-02 04:02:59,355] Trial 15 finished with value: 0.7296052631578948 and parameters: {'max_depth': 10, 'learning_rate': 0.014629296946474277, 'n_estimators': 269, 'subsample': 0.9904400022284913, 'colsample_bytree': 0.8613899123933886, 'min_child_weight': 6, 'gamma': 3.5516122035871858, 'reg_alpha': 2.8561477844283503e-05, 'reg_lambda': 9.654124858323286, 'max_delta_step': 0}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  34%|███▍      | 17/50 [02:29<02:55,  5.33s/it]

[I 2025-12-02 04:03:05,549] Trial 18 pruned.

Best trial: 3. Best value: 0.808553:  36%|███▌      | 18/50 [02:29<02:01,  3.81s/it]

[I 2025-12-02 04:03:05,808] Trial 13 finished with value: 0.7171052631578947 and parameters: {'max_depth': 5, 'learning_rate': 0.01243083167034866, 'n_estimators': 822, 'subsample': 0.9946324713317305, 'colsample_bytree': 0.5055475084932046, 'min_child_weight': 6, 'gamma': 4.72275842968121, 'reg_alpha': 0.0001043225089330256, 'reg_lambda': 0.0025239098196754325, 'max_delta_step': 1}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  38%|███▊      | 19/50 [02:31<01:36,  3.11s/it]

[I 2025-12-02 04:03:07,299] Trial 17 finished with value: 0.7559210526315789 and parameters: {'max_depth': 6, 'learning_rate': 0.07110443320454382, 'n_estimators': 214, 'subsample': 0.6050540823676749, 'colsample_bytree': 0.8501602590397276, 'min_child_weight': 7, 'gamma': 4.822176612227503, 'reg_alpha': 8.262800777036475e-06, 'reg_lambda': 0.00037040811165124735, 'max_delta_step': 1}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  40%|████      | 20/50 [02:32<01:18,  2.60s/it]

[I 2025-12-02 04:03:08,710] Trial 20 pruned.

Best trial: 3. Best value: 0.808553:  42%|████▏     | 21/50 [02:32<00:54,  1.89s/it]

[I 2025-12-02 04:03:08,957] Trial 21 pruned.

Best trial: 3. Best value: 0.808553:  44%|████▍     | 22/50 [02:34<00:50,  1.79s/it]

[I 2025-12-02 04:03:10,505] Trial 22 pruned.

Best trial: 3. Best value: 0.808553:  46%|████▌     | 23/50 [02:39<01:11,  2.65s/it]

[I 2025-12-02 04:03:15,151] Trial 25 pruned.

Best trial: 3. Best value: 0.808553:  48%|████▊     | 24/50 [02:39<00:53,  2.06s/it]

[I 2025-12-02 04:03:15,855] Trial 23 pruned.

Best trial: 3. Best value: 0.808553:  50%|█████     | 25/50 [02:42<00:54,  2.18s/it]

[I 2025-12-02 04:03:18,291] Trial 26 pruned.

Best trial: 3. Best value: 0.808553:  52%|█████▏    | 26/50 [02:42<00:40,  1.70s/it]

[I 2025-12-02 04:03:18,892] Trial 27 pruned.

Best trial: 3. Best value: 0.808553:  54%|█████▍    | 27/50 [02:44<00:41,  1.79s/it]

[I 2025-12-02 04:03:20,873] Trial 28 pruned.

Best trial: 3. Best value: 0.808553:  56%|█████▌    | 28/50 [02:48<00:53,  2.44s/it]

[I 2025-12-02 04:03:24,835] Trial 29 pruned.

Best trial: 3. Best value: 0.808553:  58%|█████▊    | 29/50 [02:57<01:30,  4.31s/it]

[I 2025-12-02 04:03:33,509] Trial 19 finished with value: 0.7171052631578947 and parameters: {'max_depth': 6, 'learning_rate': 0.08086115780523707, 'n_estimators': 690, 'subsample': 0.5995135480317768, 'colsample_bytree': 0.8190334230607522, 'min_child_weight': 4, 'gamma': 4.806670481821631, 'reg_alpha': 0.0008008300000145648, 'reg_lambda': 0.0004284185956480756, 'max_delta_step': 2}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  60%|██████    | 30/50 [03:02<01:28,  4.42s/it]

[I 2025-12-02 04:03:38,197] Trial 24 finished with value: 0.7559210526315789 and parameters: {'max_depth': 8, 'learning_rate': 0.2793442029905388, 'n_estimators': 621, 'subsample': 0.9087978797804929, 'colsample_bytree': 0.6482071577655866, 'min_child_weight': 8, 'gamma': 1.685963301760488, 'reg_alpha': 1.5327912845150391e-06, 'reg_lambda': 0.6807745377035694, 'max_delta_step': 5}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  62%|██████▏   | 31/50 [03:08<01:34,  4.99s/it]

[I 2025-12-02 04:03:44,519] Trial 30 pruned.

Best trial: 3. Best value: 0.808553:  64%|██████▍   | 32/50 [03:11<01:19,  4.40s/it]

[I 2025-12-02 04:03:47,529] Trial 31 pruned.

Best trial: 3. Best value: 0.808553:  66%|██████▌   | 33/50 [03:15<01:13,  4.34s/it]

[I 2025-12-02 04:03:51,720] Trial 35 pruned.

Best trial: 3. Best value: 0.808553:  68%|██████▊   | 34/50 [03:24<01:30,  5.63s/it]

[I 2025-12-02 04:04:00,353] Trial 36 pruned.

Best trial: 3. Best value: 0.808553:  70%|███████   | 35/50 [03:31<01:33,  6.22s/it]

[I 2025-12-02 04:04:07,945] Trial 34 finished with value: 0.8085526315789473 and parameters: {'max_depth': 5, 'learning_rate': 0.04725851156306456, 'n_estimators': 467, 'subsample': 0.5761716411324622, 'colsample_bytree': 0.8331409470349909, 'min_child_weight': 7, 'gamma': 2.6049431301174844, 'reg_alpha': 1.158407316576338e-05, 'reg_lambda': 0.00012939338823914862, 'max_delta_step': 3}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  72%|███████▏  | 36/50 [03:36<01:18,  5.62s/it]

[I 2025-12-02 04:04:12,176] Trial 37 finished with value: 0.6907894736842105 and parameters: {'max_depth': 8, 'learning_rate': 0.11591753367719418, 'n_estimators': 208, 'subsample': 0.671331962461571, 'colsample_bytree': 0.7508130774223721, 'min_child_weight': 5, 'gamma': 1.2995225322276325, 'reg_alpha': 7.197987306914051e-06, 'reg_lambda': 0.0014813316959938392, 'max_delta_step': 1}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  74%|███████▍  | 37/50 [03:36<00:51,  4.00s/it]

[I 2025-12-02 04:04:12,395] Trial 38 pruned.

Best trial: 3. Best value: 0.808553:  76%|███████▌  | 38/50 [03:40<00:48,  4.08s/it]

[I 2025-12-02 04:04:16,668] Trial 39 pruned.

Best trial: 3. Best value: 0.808553:  78%|███████▊  | 39/50 [03:41<00:34,  3.14s/it]

[I 2025-12-02 04:04:17,611] Trial 32 finished with value: 0.7684210526315789 and parameters: {'max_depth': 4, 'learning_rate': 0.043789909980195184, 'n_estimators': 944, 'subsample': 0.9404456235106853, 'colsample_bytree': 0.7626128741512398, 'min_child_weight': 9, 'gamma': 2.68430560023681, 'reg_alpha': 5.6681451624464933e-08, 'reg_lambda': 1.553588323652866, 'max_delta_step': 3}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  80%|████████  | 40/50 [03:45<00:33,  3.37s/it]

[I 2025-12-02 04:04:21,515] Trial 33 finished with value: 0.7421052631578948 and parameters: {'max_depth': 4, 'learning_rate': 0.046492112616212895, 'n_estimators': 935, 'subsample': 0.9444519336899475, 'colsample_bytree': 0.7686341126948292, 'min_child_weight': 9, 'gamma': 2.5713947214077906, 'reg_alpha': 4.239118685293144e-08, 'reg_lambda': 6.483733067211285e-05, 'max_delta_step': 3}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 3. Best value: 0.808553:  82%|████████▏ | 41/50 [03:54<00:45,  5.04s/it]

[I 2025-12-02 04:04:30,464] Trial 43 pruned.

Best trial: 3. Best value: 0.808553:  84%|████████▍ | 42/50 [04:00<00:42,  5.31s/it]

[I 2025-12-02 04:04:36,406] Trial 40 finished with value: 0.7697368421052632 and parameters: {'max_depth': 5, 'learning_rate': 0.03331004597018993, 'n_estimators': 474, 'subsample': 0.8872227615944018, 'colsample_bytree': 0.9539423731874841, 'min_child_weight': 8, 'gamma': 2.0260737959809525, 'reg_alpha': 0.020344639921183343, 'reg_lambda': 1.2143017986676438e-06, 'max_delta_step': 3}. Best is trial 3 with value: 0.8085526315789473.

Best trial: 41. Best value: 0.821053:  86%|████████▌ | 43/50 [04:01<00:28,  4.11s/it]

[I 2025-12-02 04:04:37,709] Trial 41 finished with value: 0.8210526315789474 and parameters: {'max_depth': 5, 'learning_rate': 0.2394815511653686, 'n_estimators': 438, 'subsample': 0.9494660366993198, 'colsample_bytree': 0.9580922086667986, 'min_child_weight': 9, 'gamma': 3.1990836731980856, 'reg_alpha': 1.0487065571916082e-07, 'reg_lambda': 4.2512312013998217e-07, 'max_delta_step': 3}. Best is trial 41 with value: 0.8210526315789474.

Best trial: 41. Best value: 0.821053:  88%|████████▊ | 44/50 [04:15<00:42,  7.07s/it]

[I 2025-12-02 04:04:51,698] Trial 44 finished with value: 0.7822368421052632 and parameters: {'max_depth': 5, 'learning_rate': 0.038184825495682674, 'n_estimators': 444, 'subsample': 0.8840896149843237, 'colsample_bytree': 0.7204093419988291, 'min_child_weight': 8, 'gamma': 3.1895130297296483, 'reg_alpha': 1.6581484514863305e-07, 'reg_lambda': 1.591003572215661, 'max_delta_step': 2}. Best is trial 41 with value: 0.8210526315789474.

Best trial: 41. Best value: 0.821053:  90%|█████████ | 45/50 [04:21<00:34,  6.87s/it]

[I 2025-12-02 04:04:58,104] Trial 45 finished with value: 0.7822368421052632 and parameters: {'max_depth': 3, 'learning_rate': 0.03582326268497504, 'n_estimators': 441, 'subsample': 0.9581729665904226, 'colsample_bytree': 0.9516271763266775, 'min_child_weight': 8, 'gamma': 2.0597229689125616, 'reg_alpha': 0.47334074089519357, 'reg_lambda': 1.2479624059980444e-07, 'max_delta_step': 2}. Best is trial 41 with value: 0.8210526315789474.

Best trial: 41. Best value: 0.821053:  92%|█████████▏| 46/50 [04:22<00:20,  5.11s/it]

[I 2025-12-02 04:04:59,104] Trial 46 finished with value: 0.7822368421052632 and parameters: {'max_depth': 5, 'learning_rate': 0.032475313057202276, 'n_estimators': 436, 'subsample': 0.8846314719078328, 'colsample_bytree': 0.9656102344181705, 'min_child_weight': 8, 'gamma': 3.1853951463187133, 'reg_alpha': 0.17157172110727764, 'reg_lambda': 1.182145092682109e-07, 'max_delta_step': 2}. Best is trial 41 with value: 0.8210526315789474.

Best trial: 41. Best value: 0.821053:  94%|█████████▍| 47/50 [04:31<00:18,  6.09s/it]

[I 2025-12-02 04:05:07,462] Trial 42 finished with value: 0.7822368421052632 and parameters: {'max_depth': 5, 'learning_rate': 0.05489826094278514, 'n_estimators': 1115, 'subsample': 0.9558135388050997, 'colsample_bytree': 0.9572896340243773, 'min_child_weight': 8, 'gamma': 2.0503345867242135, 'reg_alpha': 6.494774317801988e-08, 'reg_lambda': 6.54958910307358e-07, 'max_delta_step': 3}. Best is trial 41 with value: 0.8210526315789474.

Best trial: 41. Best value: 0.821053:  96%|█████████▌| 48/50 [04:35<00:11,  5.51s/it]

[I 2025-12-02 04:05:11,630] Trial 47 finished with value: 0.7559210526315789 and parameters: {'max_depth': 3, 'learning_rate': 0.03707298156853636, 'n_estimators': 428, 'subsample': 0.9636184441163897, 'colsample_bytree': 0.7224298973737868, 'min_child_weight': 8, 'gamma': 3.169613295294094, 'reg_alpha': 1.6396659184923343e-07, 'reg_lambda': 9.741508042245414e-08, 'max_delta_step': 2}. Best is trial 41 with value: 0.8210526315789474.

Best trial: 41. Best value: 0.821053:  98%|█████████▊| 49/50 [04:37<00:04,  4.36s/it]

[I 2025-12-02 04:05:13,307] Trial 49 finished with value: 0.7171052631578947 and parameters: {'max_depth': 3, 'learning_rate': 0.039293434905247955, 'n_estimators': 281, 'subsample': 0.9639350793314689, 'colsample_bytree': 0.9187547585200744, 'min_child_weight': 7, 'gamma': 3.9666589825969796, 'reg_alpha': 1.6036716528733296e-07, 'reg_lambda': 2.9314978733986138e-08, 'max_delta_step': 2}. Best is trial 41 with value: 0.8210526315789474.

Best trial: 41. Best value: 0.821053: 100%|██████████| 50/50 [04:39<00:00,  5.59s/it]

[I 2025-12-02 04:05:15,450] Trial 48 finished with value: 0.7559210526315789 and parameters: {'max_depth': 3, 'learning_rate': 0.03687477437364878, 'n_estimators': 432, 'subsample': 0.9601676424696063, 'colsample_bytree': 0.7065640469426813, 'min_child_weight': 8, 'gamma': 3.207426337788295, 'reg_alpha': 0.23800900029513578, 'reg_lambda': 7.323656330012091e-08, 'max_delta_step': 2}. Best is trial 41 with value: 0.8210526315789474.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 04:05:17,842] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0:   2%|▏         | 1/50 [00:24<19:46, 24.22s/it]

[I 2025-12-02 04:05:42,067] Trial 0 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.15217865020469562, 'n_estimators': 518, 'subsample': 0.8103176700037831, 'colsample_bytree': 0.9867204403699852, 'min_child_weight': 10, 'gamma': 3.1634349697305755, 'reg_alpha': 0.2485735926767666, 'reg_lambda': 0.0003078200454572969, 'max_delta_step': 0}. Best is trial 0 with value: 0.0.

Best trial: 3. Best value: 0.421053:   4%|▍         | 2/50 [00:46<18:28, 23.10s/it]

[I 2025-12-02 04:06:04,390] Trial 3 finished with value: 0.42105263157894735 and parameters: {'max_depth': 7, 'learning_rate': 0.015606270521135099, 'n_estimators': 1113, 'subsample': 0.5065772793026659, 'colsample_bytree': 0.6292374708813565, 'min_child_weight': 7, 'gamma': 3.8537737425366347, 'reg_alpha': 9.507978128894831e-07, 'reg_lambda': 6.391587695783968e-08, 'max_delta_step': 10}. Best is trial 3 with value: 0.42105263157894735.

Best trial: 3. Best value: 0.421053:   6%|▌         | 3/50 [00:47<10:11, 13.01s/it]

[I 2025-12-02 04:06:05,393] Trial 2 finished with value: 0.31065468549422337 and parameters: {'max_depth': 4, 'learning_rate': 0.0730353808920403, 'n_estimators': 831, 'subsample': 0.8609448101903107, 'colsample_bytree': 0.5457779547856465, 'min_child_weight': 1, 'gamma': 1.265342696666586, 'reg_alpha': 5.981431487946231, 'reg_lambda': 2.2164646887607516e-05, 'max_delta_step': 0}. Best is trial 3 with value: 0.42105263157894735.

Best trial: 1. Best value: 0.51733:   8%|▊         | 4/50 [01:00<09:52, 12.88s/it]

[I 2025-12-02 04:06:18,064] Trial 1 finished with value: 0.5173299101412067 and parameters: {'max_depth': 10, 'learning_rate': 0.21256062512925658, 'n_estimators': 1461, 'subsample': 0.5440115850585145, 'colsample_bytree': 0.6306439375193593, 'min_child_weight': 7, 'gamma': 1.4246304166033346, 'reg_alpha': 0.0004705836583569018, 'reg_lambda': 0.35335196304155353, 'max_delta_step': 9}. Best is trial 1 with value: 0.5173299101412067.

Best trial: 1. Best value: 0.51733:  10%|█         | 5/50 [01:13<09:44, 12.99s/it]

[I 2025-12-02 04:06:31,244] Trial 7 finished with value: 0.17843388960205392 and parameters: {'max_depth': 8, 'learning_rate': 0.02988338764976084, 'n_estimators': 258, 'subsample': 0.6571176504383471, 'colsample_bytree': 0.5389771076343173, 'min_child_weight': 8, 'gamma': 2.7026964591402507, 'reg_alpha': 0.0006886233762004156, 'reg_lambda': 1.219119385938266, 'max_delta_step': 7}. Best is trial 1 with value: 0.5173299101412067.

Best trial: 4. Best value: 0.535944:  14%|█▍        | 7/50 [01:37<08:09, 11.39s/it]

[I 2025-12-02 04:06:55,589] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.01325062199600386, 'n_estimators': 1233, 'subsample': 0.5072671177003885, 'colsample_bytree': 0.6315097908564181, 'min_child_weight': 10, 'gamma': 4.808267612935684, 'reg_alpha': 0.0470673491570235, 'reg_lambda': 5.095594530762372e-06, 'max_delta_step': 9}. Best is trial 1 with value: 0.5173299101412067.
[I 2025-12-02 04:06:55,746] Trial 4 finished with value: 0.5359435173299101 and parameters: {'max_depth': 5, 'learning_rate': 0.2630963491132638, 'n_estimators': 1272, 'subsample': 0.9395997634964008, 'colsample_bytree': 0.7009940798868799, 'min_child_weight': 2, 'gamma': 3.805086576967642, 'reg_alpha': 0.02406410655211969, 'reg_lambda': 1.6210396857964435e-05, 'max_delta_step': 4}. Best is trial 4 with value: 0.5359435173299101.

Best trial: 4. Best value: 0.535944:  16%|█▌        | 8/50 [01:44<06:55,  9.90s/it]

[I 2025-12-02 04:07:02,463] Trial 6 finished with value: 0.2631578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.0736161203819989, 'n_estimators': 1383, 'subsample': 0.7553842912441512, 'colsample_bytree': 0.7509547789956366, 'min_child_weight': 10, 'gamma': 3.145402177670765, 'reg_alpha': 1.1683260417071923e-05, 'reg_lambda': 3.531104383306853, 'max_delta_step': 10}. Best is trial 4 with value: 0.5359435173299101.

Best trial: 4. Best value: 0.535944:  18%|█▊        | 9/50 [01:52<06:15,  9.15s/it]

[I 2025-12-02 04:07:09,970] Trial 10 finished with value: 0.5256739409499358 and parameters: {'max_depth': 4, 'learning_rate': 0.08039720065430243, 'n_estimators': 239, 'subsample': 0.8496082473361006, 'colsample_bytree': 0.6837850744439993, 'min_child_weight': 4, 'gamma': 3.2111017932895836, 'reg_alpha': 3.9038119583087156, 'reg_lambda': 1.723954651677138e-05, 'max_delta_step': 3}. Best is trial 4 with value: 0.5359435173299101.

Best trial: 4. Best value: 0.535944:  20%|██        | 10/50 [02:01<06:11,  9.28s/it]

[I 2025-12-02 04:07:19,531] Trial 9 finished with value: 0.42041078305519897 and parameters: {'max_depth': 8, 'learning_rate': 0.030201865171924025, 'n_estimators': 289, 'subsample': 0.9314448020965109, 'colsample_bytree': 0.828233822805228, 'min_child_weight': 2, 'gamma': 3.612763769866618, 'reg_alpha': 4.917164038339447e-05, 'reg_lambda': 0.3352766579824436, 'max_delta_step': 4}. Best is trial 4 with value: 0.5359435173299101.

Best trial: 4. Best value: 0.535944:  22%|██▏       | 11/50 [02:03<04:37,  7.12s/it]

[I 2025-12-02 04:07:21,765] Trial 11 finished with value: 0.39473684210526316 and parameters: {'max_depth': 6, 'learning_rate': 0.03256442354683158, 'n_estimators': 481, 'subsample': 0.5980246782463654, 'colsample_bytree': 0.6660836646081132, 'min_child_weight': 9, 'gamma': 4.087813849342999, 'reg_alpha': 8.896574302693954e-06, 'reg_lambda': 4.1516438368202625e-05, 'max_delta_step': 1}. Best is trial 4 with value: 0.5359435173299101.

Best trial: 4. Best value: 0.535944:  24%|██▍       | 12/50 [02:05<03:26,  5.43s/it]

[I 2025-12-02 04:07:23,308] Trial 8 pruned.

Best trial: 14. Best value: 0.562259:  26%|██▌       | 13/50 [02:42<09:19, 15.12s/it]

[I 2025-12-02 04:08:00,750] Trial 14 finished with value: 0.5622593068035944 and parameters: {'max_depth': 5, 'learning_rate': 0.2793726734188247, 'n_estimators': 899, 'subsample': 0.9014976341663236, 'colsample_bytree': 0.7839815221584935, 'min_child_weight': 4, 'gamma': 0.21694809129313608, 'reg_alpha': 0.05786666314960743, 'reg_lambda': 4.157865471193996e-07, 'max_delta_step': 3}. Best is trial 14 with value: 0.5622593068035944.

Best trial: 14. Best value: 0.562259:  28%|██▊       | 14/50 [02:43<06:24, 10.69s/it]

[I 2025-12-02 04:08:01,180] Trial 13 finished with value: 0.5500641848523748 and parameters: {'max_depth': 6, 'learning_rate': 0.23259491187535586, 'n_estimators': 948, 'subsample': 0.9978055031957054, 'colsample_bytree': 0.8687695108436946, 'min_child_weight': 4, 'gamma': 0.18078750305431557, 'reg_alpha': 0.02653643959899228, 'reg_lambda': 2.149895566485433e-08, 'max_delta_step': 6}. Best is trial 14 with value: 0.5622593068035944.

Best trial: 14. Best value: 0.562259:  30%|███       | 15/50 [02:44<04:38,  7.95s/it]

[I 2025-12-02 04:08:02,804] Trial 12 finished with value: 0.41014120667522463 and parameters: {'max_depth': 10, 'learning_rate': 0.24707415794654028, 'n_estimators': 1030, 'subsample': 0.5435168420056731, 'colsample_bytree': 0.6963141933043719, 'min_child_weight': 1, 'gamma': 3.4670331604829596, 'reg_alpha': 0.00017727689829751385, 'reg_lambda': 1.9302261909943194e-07, 'max_delta_step': 9}. Best is trial 14 with value: 0.5622593068035944.

Best trial: 14. Best value: 0.562259:  32%|███▏      | 16/50 [02:48<03:47,  6.70s/it]

[I 2025-12-02 04:08:06,580] Trial 15 finished with value: 0.5359435173299101 and parameters: {'max_depth': 6, 'learning_rate': 0.2730132526965674, 'n_estimators': 912, 'subsample': 0.9717983835291056, 'colsample_bytree': 0.7800448424769111, 'min_child_weight': 4, 'gamma': 2.2361681903904387, 'reg_alpha': 1.0908198980451922e-08, 'reg_lambda': 3.3466966135183335e-07, 'max_delta_step': 3}. Best is trial 14 with value: 0.5622593068035944.

Best trial: 14. Best value: 0.562259:  34%|███▍      | 17/50 [03:23<08:14, 14.99s/it]

[I 2025-12-02 04:08:40,869] Trial 16 finished with value: 0.5256739409499358 and parameters: {'max_depth': 6, 'learning_rate': 0.27860899686469615, 'n_estimators': 904, 'subsample': 0.9990070979740349, 'colsample_bytree': 0.8309397130261376, 'min_child_weight': 4, 'gamma': 0.07186723229901543, 'reg_alpha': 0.03394397627627225, 'reg_lambda': 4.554511487565238e-08, 'max_delta_step': 6}. Best is trial 14 with value: 0.5622593068035944.

Best trial: 14. Best value: 0.562259:  36%|███▌      | 18/50 [03:24<05:49, 10.91s/it]

[I 2025-12-02 04:08:42,262] Trial 19 finished with value: 0.4749679075738126 and parameters: {'max_depth': 7, 'learning_rate': 0.12866548189293328, 'n_estimators': 743, 'subsample': 0.9956227929812506, 'colsample_bytree': 0.8785608607251778, 'min_child_weight': 5, 'gamma': 0.05574140814250267, 'reg_alpha': 0.3286930499877239, 'reg_lambda': 1.5147750500598435e-08, 'max_delta_step': 6}. Best is trial 14 with value: 0.5622593068035944.

Best trial: 14. Best value: 0.562259:  38%|███▊      | 19/50 [03:26<04:11,  8.11s/it]

[I 2025-12-02 04:08:43,857] Trial 17 finished with value: 0.5359435173299101 and parameters: {'max_depth': 6, 'learning_rate': 0.13987326810789996, 'n_estimators': 909, 'subsample': 0.9947134868552834, 'colsample_bytree': 0.8731036464727834, 'min_child_weight': 4, 'gamma': 0.15397546842594417, 'reg_alpha': 0.28026564090698497, 'reg_lambda': 3.433474536632907e-08, 'max_delta_step': 6}. Best is trial 14 with value: 0.5622593068035944.

Best trial: 14. Best value: 0.562259:  40%|████      | 20/50 [03:26<02:54,  5.82s/it]

[I 2025-12-02 04:08:44,337] Trial 18 finished with value: 0.5256739409499358 and parameters: {'max_depth': 6, 'learning_rate': 0.13484182046842144, 'n_estimators': 870, 'subsample': 0.9702110108762493, 'colsample_bytree': 0.8686442452812047, 'min_child_weight': 4, 'gamma': 0.17968778828231619, 'reg_alpha': 0.42457980256112804, 'reg_lambda': 1.8128410523885107e-08, 'max_delta_step': 6}. Best is trial 14 with value: 0.5622593068035944.

Best trial: 14. Best value: 0.562259:  44%|████▍     | 22/50 [03:56<04:17,  9.21s/it]

[I 2025-12-02 04:09:14,406] Trial 21 finished with value: 0.5256739409499358 and parameters: {'max_depth': 8, 'learning_rate': 0.14410125758651487, 'n_estimators': 700, 'subsample': 0.8957199538616734, 'colsample_bytree': 0.9066252334162695, 'min_child_weight': 6, 'gamma': 0.6417455688215321, 'reg_alpha': 0.007175741629795556, 'reg_lambda': 0.008556623494154363, 'max_delta_step': 2}. Best is trial 14 with value: 0.5622593068035944.
[I 2025-12-02 04:09:14,558] Trial 23 finished with value: 0.511553273427471 and parameters: {'max_depth': 8, 'learning_rate': 0.1775870408116639, 'n_estimators': 669, 'subsample': 0.9060581795016317, 'colsample_bytree': 0.9315917942210952, 'min_child_weight': 6, 'gamma': 0.7828565013176585, 'reg_alpha': 0.0030744839181172014, 'reg_lambda': 0.009122990883367725, 'max_delta_step': 2}. Best is trial 14 with value: 0.5622593068035944.

Best trial: 22. Best value: 0.60077:  46%|████▌     | 23/50 [03:57<02:57,  6.57s/it]

[I 2025-12-02 04:09:14,973] Trial 22 finished with value: 0.6007702182284981 and parameters: {'max_depth': 8, 'learning_rate': 0.1857480399189593, 'n_estimators': 690, 'subsample': 0.9004661918958913, 'colsample_bytree': 0.9111820819188047, 'min_child_weight': 6, 'gamma': 0.6309295608005185, 'reg_alpha': 0.002659584265260135, 'reg_lambda': 0.00435212769818618, 'max_delta_step': 2}. Best is trial 22 with value: 0.6007702182284981.
[I 2025-12-02 04:09:15,072] Trial 20 finished with value: 0.511553273427471 and parameters: {'max_depth': 8, 'learning_rate': 0.13683941540927488, 'n_estimators': 690, 'subsample': 0.8981004522018463, 'colsample_bytree': 0.8994098323116133, 'min_child_weight': 5, 'gamma': 0.1354946883686985, 'reg_alpha': 1.0905015716676978, 'reg_lambda': 1.0211386950070785e-08, 'max_delta_step': 7}. Best is trial 22 with value: 0.6007702182284981.

Best trial: 22. Best value: 0.60077:  50%|█████     | 25/50 [04:06<02:23,  5.75s/it]

[I 2025-12-02 04:09:24,559] Trial 25 pruned.

Best trial: 22. Best value: 0.60077:  52%|█████▏    | 26/50 [04:12<02:19,  5.81s/it]

[I 2025-12-02 04:09:30,537] Trial 28 pruned.

Best trial: 22. Best value: 0.60077:  54%|█████▍    | 27/50 [04:21<02:29,  6.48s/it]

[I 2025-12-02 04:09:38,930] Trial 29 pruned.

Best trial: 22. Best value: 0.60077:  56%|█████▌    | 28/50 [04:26<02:18,  6.27s/it]

[I 2025-12-02 04:09:44,643] Trial 26 finished with value: 0.5237483953786906 and parameters: {'max_depth': 9, 'learning_rate': 0.09995064077227932, 'n_estimators': 556, 'subsample': 0.8211986082324301, 'colsample_bytree': 0.811859516232881, 'min_child_weight': 3, 'gamma': 0.7730927318114038, 'reg_alpha': 0.009078848871536666, 'reg_lambda': 8.153882402902184e-07, 'max_delta_step': 4}. Best is trial 22 with value: 0.6007702182284981.

Best trial: 22. Best value: 0.60077:  58%|█████▊    | 29/50 [04:40<02:57,  8.47s/it]

[I 2025-12-02 04:09:58,761] Trial 30 finished with value: 0.5134788189987163 and parameters: {'max_depth': 9, 'learning_rate': 0.20592245719854788, 'n_estimators': 420, 'subsample': 0.8754185114221111, 'colsample_bytree': 0.796226979425837, 'min_child_weight': 7, 'gamma': 1.8358691853028009, 'reg_alpha': 0.00012065019131072662, 'reg_lambda': 1.234381860290688e-06, 'max_delta_step': 3}. Best is trial 22 with value: 0.6007702182284981.

Best trial: 22. Best value: 0.60077:  60%|██████    | 30/50 [04:47<02:35,  7.80s/it]

[I 2025-12-02 04:10:04,878] Trial 27 finished with value: 0.4974326059050064 and parameters: {'max_depth': 9, 'learning_rate': 0.10555239202144148, 'n_estimators': 1058, 'subsample': 0.8140134576368204, 'colsample_bytree': 0.8128089832913494, 'min_child_weight': 3, 'gamma': 0.7604948744257497, 'reg_alpha': 0.012607990898110336, 'reg_lambda': 1.9094302879372743e-06, 'max_delta_step': 4}. Best is trial 22 with value: 0.6007702182284981.

Best trial: 22. Best value: 0.60077:  62%|██████▏   | 31/50 [04:47<01:50,  5.80s/it]

[I 2025-12-02 04:10:05,778] Trial 24 finished with value: 0.4993581514762516 and parameters: {'max_depth': 5, 'learning_rate': 0.1874167140460417, 'n_estimators': 1080, 'subsample': 0.924850365937087, 'colsample_bytree': 0.7847839356366473, 'min_child_weight': 2, 'gamma': 0.7132073121117483, 'reg_alpha': 0.011499547246325998, 'reg_lambda': 1.2832110251620812e-06, 'max_delta_step': 5}. Best is trial 22 with value: 0.6007702182284981.

Best trial: 22. Best value: 0.60077:  64%|██████▍   | 32/50 [05:03<02:35,  8.65s/it]

[I 2025-12-02 04:10:21,326] Trial 31 finished with value: 0.5641848523748395 and parameters: {'max_depth': 5, 'learning_rate': 0.20439268888273943, 'n_estimators': 798, 'subsample': 0.8833945097981896, 'colsample_bytree': 0.9395756095093977, 'min_child_weight': 7, 'gamma': 1.8185152214996536, 'reg_alpha': 0.0006512513882687661, 'reg_lambda': 0.08152255019168919, 'max_delta_step': 1}. Best is trial 22 with value: 0.6007702182284981.

Best trial: 22. Best value: 0.60077:  66%|██████▌   | 33/50 [05:18<02:56, 10.39s/it]

[I 2025-12-02 04:10:35,875] Trial 32 finished with value: 0.5378690629011553 and parameters: {'max_depth': 5, 'learning_rate': 0.17294950396338973, 'n_estimators': 796, 'subsample': 0.7739690975929535, 'colsample_bytree': 0.9564002591359887, 'min_child_weight': 6, 'gamma': 0.4469288698344268, 'reg_alpha': 0.10802994083062464, 'reg_lambda': 0.0005134509189423801, 'max_delta_step': 0}. Best is trial 22 with value: 0.6007702182284981.

Best trial: 22. Best value: 0.60077:  68%|██████▊   | 34/50 [05:25<02:31,  9.48s/it]

[I 2025-12-02 04:10:43,206] Trial 33 finished with value: 0.4871630295250321 and parameters: {'max_depth': 5, 'learning_rate': 0.17419129412164772, 'n_estimators': 803, 'subsample': 0.7800259043732735, 'colsample_bytree': 0.9569473084599138, 'min_child_weight': 5, 'gamma': 1.6497232628660479, 'reg_alpha': 0.09117751828889545, 'reg_lambda': 0.001652639235218934, 'max_delta_step': 0}. Best is trial 22 with value: 0.6007702182284981.

Best trial: 22. Best value: 0.60077:  70%|███████   | 35/50 [05:39<02:45, 11.02s/it]

[I 2025-12-02 04:10:57,846] Trial 35 finished with value: 0.5134788189987163 and parameters: {'max_depth': 5, 'learning_rate': 0.22884649012565936, 'n_estimators': 793, 'subsample': 0.7798106972892734, 'colsample_bytree': 0.9496525400292907, 'min_child_weight': 6, 'gamma': 1.6999387295353856, 'reg_alpha': 0.0008231191237699452, 'reg_lambda': 0.09729739020646908, 'max_delta_step': 0}. Best is trial 22 with value: 0.6007702182284981.

Best trial: 22. Best value: 0.60077:  72%|███████▏  | 36/50 [05:47<02:18,  9.88s/it]

[I 2025-12-02 04:11:05,059] Trial 34 finished with value: 0.5397946084724006 and parameters: {'max_depth': 5, 'learning_rate': 0.2439613429564293, 'n_estimators': 1215, 'subsample': 0.9470581506460208, 'colsample_bytree': 0.7211877149548548, 'min_child_weight': 5, 'gamma': 4.742004487133352, 'reg_alpha': 0.07625556891369387, 'reg_lambda': 0.0013195745243112442, 'max_delta_step': 1}. Best is trial 22 with value: 0.6007702182284981.

Best trial: 37. Best value: 0.616816:  74%|███████▍  | 37/50 [05:53<01:56,  8.94s/it]

[I 2025-12-02 04:11:11,786] Trial 37 finished with value: 0.616816431322208 and parameters: {'max_depth': 3, 'learning_rate': 0.21754733152797115, 'n_estimators': 617, 'subsample': 0.7130976783439782, 'colsample_bytree': 0.849091956196305, 'min_child_weight': 7, 'gamma': 1.1070033785104574, 'reg_alpha': 0.0006852366437545177, 'reg_lambda': 0.069365935441996, 'max_delta_step': 1}. Best is trial 37 with value: 0.616816431322208.

Best trial: 37. Best value: 0.616816:  76%|███████▌  | 38/50 [06:01<01:43,  8.66s/it]

[I 2025-12-02 04:11:19,801] Trial 36 finished with value: 0.46277278562259305 and parameters: {'max_depth': 3, 'learning_rate': 0.22993554749762918, 'n_estimators': 948, 'subsample': 0.9564778038926701, 'colsample_bytree': 0.8488393456366592, 'min_child_weight': 5, 'gamma': 1.6231470643968784, 'reg_alpha': 0.0009909206359674941, 'reg_lambda': 0.08569744489856794, 'max_delta_step': 1}. Best is trial 37 with value: 0.616816431322208.

Best trial: 37. Best value: 0.616816:  78%|███████▊  | 39/50 [06:20<02:08, 11.69s/it]

[I 2025-12-02 04:11:38,588] Trial 39 finished with value: 0.5134788189987163 and parameters: {'max_depth': 3, 'learning_rate': 0.04996582618954241, 'n_estimators': 626, 'subsample': 0.8702346222812254, 'colsample_bytree': 0.9121875304712017, 'min_child_weight': 8, 'gamma': 1.0365970842405752, 'reg_alpha': 1.4032309605097035, 'reg_lambda': 0.051459011665763894, 'max_delta_step': 1}. Best is trial 37 with value: 0.616816431322208.

Best trial: 37. Best value: 0.616816:  80%|████████  | 40/50 [06:23<01:30,  9.03s/it]

[I 2025-12-02 04:11:41,386] Trial 40 finished with value: 0.5314505776636713 and parameters: {'max_depth': 3, 'learning_rate': 0.299245619216637, 'n_estimators': 645, 'subsample': 0.7086695334766266, 'colsample_bytree': 0.9227500803401922, 'min_child_weight': 8, 'gamma': 1.201443814009783, 'reg_alpha': 5.627562505085343e-05, 'reg_lambda': 0.03152149697832953, 'max_delta_step': 1}. Best is trial 37 with value: 0.616816431322208.

Best trial: 37. Best value: 0.616816:  82%|████████▏ | 41/50 [06:25<01:02,  6.98s/it]

[I 2025-12-02 04:11:43,572] Trial 38 finished with value: 0.5905006418485237 and parameters: {'max_depth': 7, 'learning_rate': 0.05672474192532716, 'n_estimators': 959, 'subsample': 0.9588539856701925, 'colsample_bytree': 0.8527326161422284, 'min_child_weight': 8, 'gamma': 1.1708774588103883, 'reg_alpha': 0.0015080518727493542, 'reg_lambda': 0.14106933582562523, 'max_delta_step': 1}. Best is trial 37 with value: 0.616816431322208.

Best trial: 37. Best value: 0.616816:  84%|████████▍ | 42/50 [06:29<00:47,  5.98s/it]

[I 2025-12-02 04:11:47,234] Trial 41 finished with value: 0.46662387676508343 and parameters: {'max_depth': 3, 'learning_rate': 0.2973357775662474, 'n_estimators': 608, 'subsample': 0.7283588602054026, 'colsample_bytree': 0.5024882275896865, 'min_child_weight': 8, 'gamma': 0.9997378968251818, 'reg_alpha': 3.165151399962319e-05, 'reg_lambda': 0.06196678038773346, 'max_delta_step': 1}. Best is trial 37 with value: 0.616816431322208.

Best trial: 37. Best value: 0.616816:  86%|████████▌ | 43/50 [06:38<00:47,  6.81s/it]

[I 2025-12-02 04:11:55,970] Trial 45 pruned.

Best trial: 37. Best value: 0.616816:  88%|████████▊ | 44/50 [06:41<00:34,  5.73s/it]

[I 2025-12-02 04:11:59,181] Trial 42 finished with value: 0.5500641848523748 and parameters: {'max_depth': 4, 'learning_rate': 0.27239331691072005, 'n_estimators': 414, 'subsample': 0.7274731278249023, 'colsample_bytree': 0.9937451165190214, 'min_child_weight': 7, 'gamma': 1.1547735715819005, 'reg_alpha': 3.9450635809965105e-05, 'reg_lambda': 5.054753479906986, 'max_delta_step': 2}. Best is trial 37 with value: 0.616816431322208.
[I 2025-12-02 04:11:59,189] Trial 46 pruned.

Best trial: 37. Best value: 0.616816:  92%|█████████▏| 46/50 [06:45<00:16,  4.06s/it]

[I 2025-12-02 04:12:03,421] Trial 43 finished with value: 0.4768934531450577 and parameters: {'max_depth': 4, 'learning_rate': 0.022920929246467263, 'n_estimators': 360, 'subsample': 0.6995871545390367, 'colsample_bytree': 0.9968008210722008, 'min_child_weight': 7, 'gamma': 2.7464892177112654, 'reg_alpha': 6.934505892841807e-06, 'reg_lambda': 5.91436512955756, 'max_delta_step': 2}. Best is trial 37 with value: 0.616816431322208.

Best trial: 37. Best value: 0.616816:  94%|█████████▍| 47/50 [06:51<00:13,  4.41s/it]

[I 2025-12-02 04:12:08,872] Trial 49 pruned.

Best trial: 37. Best value: 0.616816:  96%|█████████▌| 48/50 [07:02<00:12,  6.25s/it]

[I 2025-12-02 04:12:20,307] Trial 44 finished with value: 0.4768934531450577 and parameters: {'max_depth': 7, 'learning_rate': 0.019320669173584104, 'n_estimators': 746, 'subsample': 0.6956057477533814, 'colsample_bytree': 0.9990574540001537, 'min_child_weight': 7, 'gamma': 0.46735711176146744, 'reg_alpha': 0.00029136266429152834, 'reg_lambda': 0.4594502770909223, 'max_delta_step': 2}. Best is trial 37 with value: 0.616816431322208.

Best trial: 37. Best value: 0.616816:  98%|█████████▊| 49/50 [07:07<00:05,  5.83s/it]

[I 2025-12-02 04:12:25,010] Trial 47 finished with value: 0.503209242618742 and parameters: {'max_depth': 7, 'learning_rate': 0.060778749759118324, 'n_estimators': 740, 'subsample': 0.9184731487878894, 'colsample_bytree': 0.8438412216867103, 'min_child_weight': 9, 'gamma': 2.5019817843028918, 'reg_alpha': 0.0011958573472364172, 'reg_lambda': 0.42605132327775724, 'max_delta_step': 3}. Best is trial 37 with value: 0.616816431322208.

Best trial: 37. Best value: 0.616816: 100%|██████████| 50/50 [07:07<00:00,  8.55s/it]

[I 2025-12-02 04:12:25,597] Trial 48 finished with value: 0.5173299101412067 and parameters: {'max_depth': 7, 'learning_rate': 0.037411757252230796, 'n_estimators': 744, 'subsample': 0.90745817298887, 'colsample_bytree': 0.8501230956263749, 'min_child_weight': 9, 'gamma': 2.6281322305192423, 'reg_alpha': 0.001238310215949594, 'reg_lambda': 0.3593413224168987, 'max_delta_step': 3}. Best is trial 37 with value: 0.616816431322208.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 04:12:29,002] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.641207:   2%|▏         | 1/50 [00:23<19:09, 23.46s/it]

[I 2025-12-02 04:12:52,453] Trial 3 finished with value: 0.641206675224647 and parameters: {'max_depth': 5, 'learning_rate': 0.21031403756821698, 'n_estimators': 468, 'subsample': 0.8750473101745695, 'colsample_bytree': 0.714345666614137, 'min_child_weight': 4, 'gamma': 2.913929343578837, 'reg_alpha': 0.0006771508271389666, 'reg_lambda': 2.3094074387918626e-08, 'max_delta_step': 7}. Best is trial 3 with value: 0.641206675224647.

Best trial: 0. Best value: 0.691913:   4%|▍         | 2/50 [00:47<18:48, 23.52s/it]

[I 2025-12-02 04:13:16,007] Trial 0 finished with value: 0.6919127086007703 and parameters: {'max_depth': 3, 'learning_rate': 0.05114641706893776, 'n_estimators': 1082, 'subsample': 0.829852765945609, 'colsample_bytree': 0.5590783168751319, 'min_child_weight': 8, 'gamma': 1.4291945052284944, 'reg_alpha': 3.110856759224555e-05, 'reg_lambda': 0.002426202574626245, 'max_delta_step': 1}. Best is trial 0 with value: 0.6919127086007703.

Best trial: 1. Best value: 0.706033:   6%|▌         | 3/50 [00:48<10:33, 13.48s/it]

[I 2025-12-02 04:13:17,549] Trial 1 finished with value: 0.7060333761232349 and parameters: {'max_depth': 4, 'learning_rate': 0.06010093502472821, 'n_estimators': 1134, 'subsample': 0.9895068568687417, 'colsample_bytree': 0.5684857319449071, 'min_child_weight': 9, 'gamma': 3.9298200916948502, 'reg_alpha': 0.00046696933488519273, 'reg_lambda': 1.8248007876105394e-07, 'max_delta_step': 10}. Best is trial 1 with value: 0.7060333761232349.

Best trial: 1. Best value: 0.706033:   8%|▊         | 4/50 [00:51<07:16,  9.48s/it]

[I 2025-12-02 04:13:20,906] Trial 2 finished with value: 0.6758664955070603 and parameters: {'max_depth': 3, 'learning_rate': 0.2527321499177084, 'n_estimators': 1059, 'subsample': 0.7859485592975638, 'colsample_bytree': 0.5955157671059074, 'min_child_weight': 1, 'gamma': 0.0812320257600535, 'reg_alpha': 0.7212074777745503, 'reg_lambda': 6.4225519591562615e-06, 'max_delta_step': 4}. Best is trial 1 with value: 0.7060333761232349.

Best trial: 7. Best value: 0.784981:  10%|█         | 5/50 [01:03<07:40, 10.24s/it]

[I 2025-12-02 04:13:32,476] Trial 7 finished with value: 0.7849807445442876 and parameters: {'max_depth': 3, 'learning_rate': 0.04329665232072533, 'n_estimators': 221, 'subsample': 0.8293281048036224, 'colsample_bytree': 0.9619763582740729, 'min_child_weight': 9, 'gamma': 0.9284096785097151, 'reg_alpha': 2.2331092673998382e-05, 'reg_lambda': 0.00028067754925262457, 'max_delta_step': 2}. Best is trial 7 with value: 0.7849807445442876.

Best trial: 7. Best value: 0.784981:  12%|█▏        | 6/50 [01:10<06:42,  9.15s/it]

[I 2025-12-02 04:13:39,522] Trial 4 finished with value: 0.7201540436456997 and parameters: {'max_depth': 3, 'learning_rate': 0.014750911287308556, 'n_estimators': 954, 'subsample': 0.6431544138734654, 'colsample_bytree': 0.713662144562168, 'min_child_weight': 5, 'gamma': 2.943262242336224, 'reg_alpha': 8.655172118411646e-07, 'reg_lambda': 9.307714608894191e-08, 'max_delta_step': 3}. Best is trial 7 with value: 0.7849807445442876.

Best trial: 7. Best value: 0.784981:  14%|█▍        | 7/50 [01:32<09:31, 13.29s/it]

[I 2025-12-02 04:14:01,339] Trial 5 finished with value: 0.7060333761232349 and parameters: {'max_depth': 9, 'learning_rate': 0.012434192734399146, 'n_estimators': 989, 'subsample': 0.9965811799154398, 'colsample_bytree': 0.8270028452212366, 'min_child_weight': 8, 'gamma': 0.9153048185231083, 'reg_alpha': 0.8003114514613223, 'reg_lambda': 2.088301510406504e-06, 'max_delta_step': 5}. Best is trial 7 with value: 0.7849807445442876.

Best trial: 7. Best value: 0.784981:  16%|█▌        | 8/50 [01:33<06:32,  9.34s/it]

[I 2025-12-02 04:14:02,228] Trial 6 finished with value: 0.7060333761232349 and parameters: {'max_depth': 3, 'learning_rate': 0.04429440803427265, 'n_estimators': 931, 'subsample': 0.855164437523356, 'colsample_bytree': 0.7274645301560955, 'min_child_weight': 5, 'gamma': 2.910931472347161, 'reg_alpha': 0.014890314477092204, 'reg_lambda': 8.900678316607708, 'max_delta_step': 1}. Best is trial 7 with value: 0.7849807445442876.

Best trial: 7. Best value: 0.784981:  18%|█▊        | 9/50 [01:42<06:20,  9.28s/it]

[I 2025-12-02 04:14:11,371] Trial 9 finished with value: 0.7323491655969192 and parameters: {'max_depth': 9, 'learning_rate': 0.025550875397899755, 'n_estimators': 615, 'subsample': 0.8040714652823546, 'colsample_bytree': 0.9517595216138002, 'min_child_weight': 5, 'gamma': 1.8519876651182698, 'reg_alpha': 0.0007582066883591675, 'reg_lambda': 1.1455184027859506e-08, 'max_delta_step': 7}. Best is trial 7 with value: 0.7849807445442876.

Best trial: 7. Best value: 0.784981:  20%|██        | 10/50 [01:45<04:55,  7.38s/it]

[I 2025-12-02 04:14:14,484] Trial 8 finished with value: 0.7464698331193838 and parameters: {'max_depth': 6, 'learning_rate': 0.0785078455827747, 'n_estimators': 996, 'subsample': 0.828736635379915, 'colsample_bytree': 0.8906539086505303, 'min_child_weight': 9, 'gamma': 1.0764481599364661, 'reg_alpha': 1.2895946658169774e-07, 'reg_lambda': 1.8084914065591913e-06, 'max_delta_step': 3}. Best is trial 7 with value: 0.7849807445442876.

Best trial: 7. Best value: 0.784981:  22%|██▏       | 11/50 [01:47<03:39,  5.63s/it]

[I 2025-12-02 04:14:16,165] Trial 13 pruned.

Best trial: 7. Best value: 0.784981:  24%|██▍       | 12/50 [01:48<02:44,  4.33s/it]

[I 2025-12-02 04:14:17,534] Trial 12 pruned.

Best trial: 7. Best value: 0.784981:  26%|██▌       | 13/50 [01:56<03:25,  5.55s/it]

[I 2025-12-02 04:14:25,862] Trial 14 pruned.

Best trial: 7. Best value: 0.784981:  28%|██▊       | 14/50 [01:58<02:39,  4.42s/it]

[I 2025-12-02 04:14:27,690] Trial 15 pruned.

Best trial: 7. Best value: 0.784981:  30%|███       | 15/50 [02:01<02:22,  4.06s/it]

[I 2025-12-02 04:14:30,905] Trial 10 finished with value: 0.7182284980744544 and parameters: {'max_depth': 10, 'learning_rate': 0.01761010045127721, 'n_estimators': 532, 'subsample': 0.7127596401326057, 'colsample_bytree': 0.5230493501974341, 'min_child_weight': 4, 'gamma': 2.9283883246064146, 'reg_alpha': 0.00010416325218461186, 'reg_lambda': 1.3595907044331237e-07, 'max_delta_step': 4}. Best is trial 7 with value: 0.7849807445442876.

Best trial: 7. Best value: 0.784981:  32%|███▏      | 16/50 [02:02<01:43,  3.04s/it]

[I 2025-12-02 04:14:31,590] Trial 16 pruned.

Best trial: 7. Best value: 0.784981:  34%|███▍      | 17/50 [02:04<01:28,  2.69s/it]

[I 2025-12-02 04:14:33,450] Trial 17 pruned.

Best trial: 7. Best value: 0.784981:  36%|███▌      | 18/50 [02:06<01:21,  2.56s/it]

[I 2025-12-02 04:14:35,708] Trial 20 pruned.

Best trial: 7. Best value: 0.784981:  38%|███▊      | 19/50 [02:07<01:03,  2.06s/it]

[I 2025-12-02 04:14:36,608] Trial 18 pruned.

Best trial: 7. Best value: 0.784981:  40%|████      | 20/50 [02:14<01:49,  3.65s/it]

[I 2025-12-02 04:14:43,961] Trial 19 finished with value: 0.7445442875481387 and parameters: {'max_depth': 5, 'learning_rate': 0.16261667927637427, 'n_estimators': 242, 'subsample': 0.60508128641268, 'colsample_bytree': 0.8158068978206465, 'min_child_weight': 7, 'gamma': 4.978596774264472, 'reg_alpha': 1.1392285995191572e-06, 'reg_lambda': 4.756772596779412e-06, 'max_delta_step': 0}. Best is trial 7 with value: 0.7849807445442876.

Best trial: 7. Best value: 0.784981:  42%|████▏     | 21/50 [02:15<01:22,  2.83s/it]

[I 2025-12-02 04:14:44,887] Trial 21 pruned.

Best trial: 7. Best value: 0.784981:  44%|████▍     | 22/50 [02:16<00:58,  2.08s/it]

[I 2025-12-02 04:14:45,209] Trial 11 finished with value: 0.7323491655969192 and parameters: {'max_depth': 4, 'learning_rate': 0.13597315595287138, 'n_estimators': 843, 'subsample': 0.9982805713011556, 'colsample_bytree': 0.69715733416297, 'min_child_weight': 5, 'gamma': 2.6195650444159435, 'reg_alpha': 9.779314107892453, 'reg_lambda': 8.258605489504173e-06, 'max_delta_step': 2}. Best is trial 7 with value: 0.7849807445442876.

Best trial: 7. Best value: 0.784981:  48%|████▊     | 24/50 [02:19<00:45,  1.73s/it]

[I 2025-12-02 04:14:48,455] Trial 25 pruned.
[I 2025-12-02 04:14:48,568] Trial 24 pruned.

Best trial: 7. Best value: 0.784981:  50%|█████     | 25/50 [02:24<01:10,  2.83s/it]

[I 2025-12-02 04:14:53,970] Trial 23 pruned.

Best trial: 7. Best value: 0.784981:  52%|█████▏    | 26/50 [02:28<01:13,  3.06s/it]

[I 2025-12-02 04:14:57,568] Trial 28 pruned.

Best trial: 7. Best value: 0.784981:  54%|█████▍    | 27/50 [02:31<01:09,  3.01s/it]

[I 2025-12-02 04:15:00,468] Trial 29 pruned.

Best trial: 7. Best value: 0.784981:  56%|█████▌    | 28/50 [02:36<01:16,  3.49s/it]

[I 2025-12-02 04:15:05,083] Trial 27 finished with value: 0.7849807445442876 and parameters: {'max_depth': 6, 'learning_rate': 0.07292018928232331, 'n_estimators': 318, 'subsample': 0.7782501871615634, 'colsample_bytree': 0.767000860687622, 'min_child_weight': 9, 'gamma': 3.9911399968043777, 'reg_alpha': 1.458762661971917e-06, 'reg_lambda': 0.0006005405938512724, 'max_delta_step': 4}. Best is trial 7 with value: 0.7849807445442876.

Best trial: 7. Best value: 0.784981:  58%|█████▊    | 29/50 [02:36<00:53,  2.56s/it]

[I 2025-12-02 04:15:05,449] Trial 22 pruned.

Best trial: 7. Best value: 0.784981:  60%|██████    | 30/50 [02:37<00:40,  2.04s/it]

[I 2025-12-02 04:15:06,297] Trial 26 finished with value: 0.7644415917843389 and parameters: {'max_depth': 6, 'learning_rate': 0.07650497180561922, 'n_estimators': 350, 'subsample': 0.7754690250205369, 'colsample_bytree': 0.7801208545334486, 'min_child_weight': 9, 'gamma': 3.6041523489594818, 'reg_alpha': 2.2032846273254436e-06, 'reg_lambda': 0.0006757049932151006, 'max_delta_step': 1}. Best is trial 7 with value: 0.7849807445442876.

Best trial: 7. Best value: 0.784981:  62%|██████▏   | 31/50 [02:38<00:34,  1.80s/it]

[I 2025-12-02 04:15:07,544] Trial 30 pruned.

Best trial: 7. Best value: 0.784981:  64%|██████▍   | 32/50 [02:41<00:39,  2.18s/it]

[I 2025-12-02 04:15:10,605] Trial 33 pruned.

Best trial: 7. Best value: 0.784981:  66%|██████▌   | 33/50 [02:55<01:38,  5.81s/it]

[I 2025-12-02 04:15:24,893] Trial 31 pruned.

Best trial: 7. Best value: 0.784981:  68%|██████▊   | 34/50 [02:59<01:22,  5.16s/it]

[I 2025-12-02 04:15:28,520] Trial 34 finished with value: 0.7098844672657253 and parameters: {'max_depth': 8, 'learning_rate': 0.050010143587997276, 'n_estimators': 418, 'subsample': 0.7574043615807381, 'colsample_bytree': 0.6880833472410375, 'min_child_weight': 9, 'gamma': 3.5558126102161154, 'reg_alpha': 1.13841187667729e-07, 'reg_lambda': 0.004946023056144867, 'max_delta_step': 3}. Best is trial 7 with value: 0.7849807445442876.

Best trial: 7. Best value: 0.784981:  70%|███████   | 35/50 [03:05<01:19,  5.30s/it]

[I 2025-12-02 04:15:34,154] Trial 37 pruned.

Best trial: 7. Best value: 0.784981:  72%|███████▏  | 36/50 [03:09<01:10,  5.03s/it]

[I 2025-12-02 04:15:38,554] Trial 36 pruned.

Best trial: 7. Best value: 0.784981:  74%|███████▍  | 37/50 [03:10<00:48,  3.76s/it]

[I 2025-12-02 04:15:39,351] Trial 35 finished with value: 0.7708600770218228 and parameters: {'max_depth': 8, 'learning_rate': 0.08155201816118957, 'n_estimators': 584, 'subsample': 0.8222087586682703, 'colsample_bytree': 0.7863184370570236, 'min_child_weight': 9, 'gamma': 4.483874672031609, 'reg_alpha': 6.241336179622609e-08, 'reg_lambda': 0.00035297221621270064, 'max_delta_step': 3}. Best is trial 7 with value: 0.7849807445442876.

Best trial: 7. Best value: 0.784981:  76%|███████▌  | 38/50 [03:13<00:41,  3.47s/it]

[I 2025-12-02 04:15:42,133] Trial 40 pruned.

Best trial: 7. Best value: 0.784981:  78%|███████▊  | 39/50 [03:15<00:34,  3.18s/it]

[I 2025-12-02 04:15:44,647] Trial 41 pruned.

Best trial: 7. Best value: 0.784981:  80%|████████  | 40/50 [03:17<00:26,  2.63s/it]

[I 2025-12-02 04:15:45,997] Trial 32 finished with value: 0.7708600770218228 and parameters: {'max_depth': 8, 'learning_rate': 0.038569558576667155, 'n_estimators': 831, 'subsample': 0.8271187020274517, 'colsample_bytree': 0.7764224065687061, 'min_child_weight': 9, 'gamma': 1.5835916226481657, 'reg_alpha': 4.952263984396892e-05, 'reg_lambda': 0.0064124887491527225, 'max_delta_step': 6}. Best is trial 7 with value: 0.7849807445442876.

Best trial: 7. Best value: 0.784981:  82%|████████▏ | 41/50 [03:17<00:19,  2.12s/it]

[I 2025-12-02 04:15:46,937] Trial 39 pruned.

Best trial: 7. Best value: 0.784981:  84%|████████▍ | 42/50 [03:21<00:20,  2.62s/it]

[I 2025-12-02 04:15:50,711] Trial 42 pruned.

Best trial: 7. Best value: 0.784981:  86%|████████▌ | 43/50 [03:22<00:14,  2.12s/it]

[I 2025-12-02 04:15:51,649] Trial 44 pruned.

Best trial: 7. Best value: 0.784981:  88%|████████▊ | 44/50 [03:26<00:16,  2.70s/it]

[I 2025-12-02 04:15:55,707] Trial 45 pruned.

Best trial: 7. Best value: 0.784981:  90%|█████████ | 45/50 [03:41<00:31,  6.33s/it]

[I 2025-12-02 04:16:10,513] Trial 43 finished with value: 0.7445442875481387 and parameters: {'max_depth': 9, 'learning_rate': 0.022125686433157724, 'n_estimators': 452, 'subsample': 0.9672105024947776, 'colsample_bytree': 0.8596389462882108, 'min_child_weight': 8, 'gamma': 4.525106280521418, 'reg_alpha': 0.0007995838047712763, 'reg_lambda': 1.8122258913433957, 'max_delta_step': 7}. Best is trial 7 with value: 0.7849807445442876.

Best trial: 7. Best value: 0.784981:  92%|█████████▏| 46/50 [03:48<00:26,  6.65s/it]

[I 2025-12-02 04:16:17,923] Trial 48 pruned.

Best trial: 7. Best value: 0.784981:  94%|█████████▍| 47/50 [03:51<00:16,  5.52s/it]

[I 2025-12-02 04:16:20,784] Trial 47 finished with value: 0.7708600770218228 and parameters: {'max_depth': 3, 'learning_rate': 0.03384466602708495, 'n_estimators': 499, 'subsample': 0.8831190689165098, 'colsample_bytree': 0.7398749551243071, 'min_child_weight': 9, 'gamma': 2.439812113950807, 'reg_alpha': 2.1327908438738826e-05, 'reg_lambda': 0.00022020308676764128, 'max_delta_step': 7}. Best is trial 7 with value: 0.7849807445442876.

Best trial: 7. Best value: 0.784981:  96%|█████████▌| 48/50 [03:52<00:08,  4.19s/it]

[I 2025-12-02 04:16:21,887] Trial 49 pruned.

Best trial: 7. Best value: 0.784981:  98%|█████████▊| 49/50 [03:54<00:03,  3.35s/it]

[I 2025-12-02 04:16:23,262] Trial 38 finished with value: 0.7201540436456997 and parameters: {'max_depth': 6, 'learning_rate': 0.07240565363460034, 'n_estimators': 1082, 'subsample': 0.9509918659903784, 'colsample_bytree': 0.8650425469192138, 'min_child_weight': 8, 'gamma': 4.320997430367216, 'reg_alpha': 0.00027039334862579453, 'reg_lambda': 0.5391167339115881, 'max_delta_step': 2}. Best is trial 7 with value: 0.7849807445442876.

Best trial: 7. Best value: 0.784981: 100%|██████████| 50/50 [03:58<00:00,  4.78s/it]

[I 2025-12-02 04:16:27,839] Trial 46 finished with value: 0.7445442875481387 and parameters: {'max_depth': 8, 'learning_rate': 0.033680032256704344, 'n_estimators': 907, 'subsample': 0.8839902957479682, 'colsample_bytree': 0.7409687105597577, 'min_child_weight': 9, 'gamma': 3.7839720979356333, 'reg_alpha': 2.4505831555298544e-05, 'reg_lambda': 3.172319361315801e-05, 'max_delta_step': 7}. Best is trial 7 with value: 0.7849807445442876.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 04:16:30,423] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.793421:   2%|▏         | 1/50 [00:30<24:46, 30.33s/it]

[I 2025-12-02 04:17:00,751] Trial 2 finished with value: 0.7934210526315789 and parameters: {'max_depth': 9, 'learning_rate': 0.021709308891965054, 'n_estimators': 564, 'subsample': 0.6922835679200812, 'colsample_bytree': 0.89505417478155, 'min_child_weight': 4, 'gamma': 1.4140113213406291, 'reg_alpha': 0.0006301480974737032, 'reg_lambda': 2.5976667995754074e-08, 'max_delta_step': 4}. Best is trial 2 with value: 0.7934210526315789.

Best trial: 2. Best value: 0.793421:   4%|▍         | 2/50 [00:43<15:58, 19.96s/it]

[I 2025-12-02 04:17:13,452] Trial 1 finished with value: 0.7671052631578947 and parameters: {'max_depth': 5, 'learning_rate': 0.07432385092337279, 'n_estimators': 971, 'subsample': 0.6983433707447526, 'colsample_bytree': 0.7323628759489953, 'min_child_weight': 8, 'gamma': 2.3774449875141483, 'reg_alpha': 0.0003431371548916878, 'reg_lambda': 0.019088035935963886, 'max_delta_step': 7}. Best is trial 2 with value: 0.7934210526315789.

Best trial: 3. Best value: 0.844737:   6%|▌         | 3/50 [00:43<08:43, 11.14s/it]

[I 2025-12-02 04:17:14,096] Trial 3 finished with value: 0.8447368421052632 and parameters: {'max_depth': 10, 'learning_rate': 0.12535063830863022, 'n_estimators': 969, 'subsample': 0.5000230381163904, 'colsample_bytree': 0.7711304153204772, 'min_child_weight': 6, 'gamma': 0.9584893747723744, 'reg_alpha': 8.936594291860834, 'reg_lambda': 0.06698102746205212, 'max_delta_step': 3}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:   8%|▊         | 4/50 [00:50<07:06,  9.27s/it]

[I 2025-12-02 04:17:20,508] Trial 0 finished with value: 0.8184210526315789 and parameters: {'max_depth': 5, 'learning_rate': 0.08656665257714477, 'n_estimators': 1167, 'subsample': 0.8305160685570483, 'colsample_bytree': 0.550465211053063, 'min_child_weight': 8, 'gamma': 1.5985693229601932, 'reg_alpha': 9.92551363977928e-05, 'reg_lambda': 2.908629822307115, 'max_delta_step': 3}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  10%|█         | 5/50 [01:04<08:17, 11.05s/it]

[I 2025-12-02 04:17:34,689] Trial 5 finished with value: 0.7809210526315788 and parameters: {'max_depth': 6, 'learning_rate': 0.2680484050222662, 'n_estimators': 415, 'subsample': 0.904300083963615, 'colsample_bytree': 0.5870043954726945, 'min_child_weight': 2, 'gamma': 1.4657840902553292, 'reg_alpha': 1.355677055405429e-07, 'reg_lambda': 0.16216001010753678, 'max_delta_step': 5}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  12%|█▏        | 6/50 [01:10<06:59,  9.53s/it]

[I 2025-12-02 04:17:41,294] Trial 6 finished with value: 0.075 and parameters: {'max_depth': 4, 'learning_rate': 0.16547750154274032, 'n_estimators': 583, 'subsample': 0.5203227795561433, 'colsample_bytree': 0.8688409052224979, 'min_child_weight': 8, 'gamma': 0.4987921736744333, 'reg_alpha': 7.722339685508849, 'reg_lambda': 1.0399237940087427e-07, 'max_delta_step': 7}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  14%|█▍        | 7/50 [01:29<09:01, 12.60s/it]

[I 2025-12-02 04:18:00,205] Trial 4 finished with value: 0.8447368421052632 and parameters: {'max_depth': 3, 'learning_rate': 0.06587793821462656, 'n_estimators': 1439, 'subsample': 0.6932794358274412, 'colsample_bytree': 0.5438203398430925, 'min_child_weight': 7, 'gamma': 2.603514829328886, 'reg_alpha': 0.00019311739423508276, 'reg_lambda': 0.03926684392042168, 'max_delta_step': 6}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  16%|█▌        | 8/50 [01:30<06:16,  8.97s/it]

[I 2025-12-02 04:18:01,404] Trial 7 finished with value: 0.805921052631579 and parameters: {'max_depth': 4, 'learning_rate': 0.24329753186908795, 'n_estimators': 871, 'subsample': 0.842826020660673, 'colsample_bytree': 0.5204515224348215, 'min_child_weight': 2, 'gamma': 3.898451320434899, 'reg_alpha': 4.5207223714047215e-05, 'reg_lambda': 1.3324613584087608, 'max_delta_step': 9}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  18%|█▊        | 9/50 [01:35<05:16,  7.72s/it]

[I 2025-12-02 04:18:06,380] Trial 8 finished with value: 0.8197368421052631 and parameters: {'max_depth': 10, 'learning_rate': 0.05705269614406466, 'n_estimators': 755, 'subsample': 0.9536140020055763, 'colsample_bytree': 0.947757842565246, 'min_child_weight': 6, 'gamma': 3.0480304201620223, 'reg_alpha': 0.0004403128508719136, 'reg_lambda': 0.00027400495467958896, 'max_delta_step': 10}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  20%|██        | 10/50 [01:44<05:24,  8.12s/it]

[I 2025-12-02 04:18:15,385] Trial 11 finished with value: 0.8447368421052632 and parameters: {'max_depth': 6, 'learning_rate': 0.17865816266233728, 'n_estimators': 264, 'subsample': 0.5864425296083875, 'colsample_bytree': 0.6817492111886805, 'min_child_weight': 2, 'gamma': 0.610063649555081, 'reg_alpha': 7.272598841170132, 'reg_lambda': 5.4247597466369575e-05, 'max_delta_step': 0}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  22%|██▏       | 11/50 [01:48<04:25,  6.81s/it]

[I 2025-12-02 04:18:19,239] Trial 9 finished with value: 0.8197368421052631 and parameters: {'max_depth': 4, 'learning_rate': 0.010031659367154668, 'n_estimators': 635, 'subsample': 0.9391611323029658, 'colsample_bytree': 0.6956198193838574, 'min_child_weight': 3, 'gamma': 4.421966360648794, 'reg_alpha': 0.00023046757229804808, 'reg_lambda': 0.052933751253158204, 'max_delta_step': 9}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  24%|██▍       | 12/50 [01:52<03:38,  5.76s/it]

[I 2025-12-02 04:18:22,586] Trial 13 pruned.

Best trial: 3. Best value: 0.844737:  26%|██▌       | 13/50 [01:54<02:57,  4.81s/it]

[I 2025-12-02 04:18:25,202] Trial 12 finished with value: 0.8447368421052632 and parameters: {'max_depth': 8, 'learning_rate': 0.06629024112135486, 'n_estimators': 470, 'subsample': 0.8357883107418422, 'colsample_bytree': 0.7184394513819867, 'min_child_weight': 8, 'gamma': 3.783104063319897, 'reg_alpha': 1.5504731324154504e-05, 'reg_lambda': 4.081553682490066, 'max_delta_step': 5}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  28%|██▊       | 14/50 [01:59<02:46,  4.63s/it]

[I 2025-12-02 04:18:29,420] Trial 10 finished with value: 0.8322368421052632 and parameters: {'max_depth': 3, 'learning_rate': 0.018639563102431405, 'n_estimators': 221, 'subsample': 0.9458799282104835, 'colsample_bytree': 0.7945705179775782, 'min_child_weight': 1, 'gamma': 0.16232119243086707, 'reg_alpha': 0.001898211809069239, 'reg_lambda': 0.018703151987033203, 'max_delta_step': 7}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  30%|███       | 15/50 [02:55<11:48, 20.24s/it]

[I 2025-12-02 04:19:25,819] Trial 14 finished with value: 0.8447368421052632 and parameters: {'max_depth': 8, 'learning_rate': 0.031175463179973828, 'n_estimators': 1456, 'subsample': 0.5843590344509152, 'colsample_bytree': 0.7883826664034966, 'min_child_weight': 6, 'gamma': 2.8499268795120676, 'reg_alpha': 0.07685986540703199, 'reg_lambda': 0.0026953008183155675, 'max_delta_step': 2}. Best is trial 3 with value: 0.8447368421052632.
[I 2025-12-02 04:19:25,827] Trial 15 finished with value: 0.8184210526315789 and parameters: {'max_depth': 8, 'learning_rate': 0.10564040249090677, 'n_estimators': 1427, 'subsample': 0.610762016844332, 'colsample_bytree': 0.6347957466337244, 'min_child_weight': 6, 'gamma': 2.8118790243866925, 'reg_alpha': 0.029297914327437266, 'reg_lambda': 0.005703917430968212, 'max_delta_step': 3}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  34%|███▍      | 17/50 [03:00<06:33, 11.94s/it]

[I 2025-12-02 04:19:30,431] Trial 16 finished with value: 0.8197368421052631 and parameters: {'max_depth': 3, 'learning_rate': 0.11703309840845072, 'n_estimators': 1479, 'subsample': 0.621295077986642, 'colsample_bytree': 0.6211307113179204, 'min_child_weight': 6, 'gamma': 2.5568695792672194, 'reg_alpha': 0.04391219604035401, 'reg_lambda': 0.00455330743676835, 'max_delta_step': 2}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  36%|███▌      | 18/50 [03:05<05:27, 10.24s/it]

[I 2025-12-02 04:19:35,531] Trial 17 finished with value: 0.8184210526315789 and parameters: {'max_depth': 10, 'learning_rate': 0.1180093715780287, 'n_estimators': 1470, 'subsample': 0.6159344709582633, 'colsample_bytree': 0.6310112148895853, 'min_child_weight': 6, 'gamma': 2.473158903293505, 'reg_alpha': 0.03562448431498784, 'reg_lambda': 0.0015842887081362175, 'max_delta_step': 2}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  38%|███▊      | 19/50 [03:43<09:08, 17.69s/it]

[I 2025-12-02 04:20:14,208] Trial 19 finished with value: 0.805921052631579 and parameters: {'max_depth': 10, 'learning_rate': 0.03874543536740648, 'n_estimators': 1094, 'subsample': 0.7421457575166726, 'colsample_bytree': 0.6270906209817232, 'min_child_weight': 5, 'gamma': 2.1514951967993396, 'reg_alpha': 1.2954062048568433e-06, 'reg_lambda': 0.27965095815802055, 'max_delta_step': 6}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  40%|████      | 20/50 [03:48<07:02, 14.07s/it]

[I 2025-12-02 04:20:18,627] Trial 18 finished with value: 0.805921052631579 and parameters: {'max_depth': 10, 'learning_rate': 0.04083979296203225, 'n_estimators': 1182, 'subsample': 0.7073012835037109, 'colsample_bytree': 0.6161372438094134, 'min_child_weight': 4, 'gamma': 2.04256061754536, 'reg_alpha': 1.2639373067641543e-06, 'reg_lambda': 0.19112145377048562, 'max_delta_step': 6}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  42%|████▏     | 21/50 [03:53<05:39, 11.72s/it]

[I 2025-12-02 04:20:24,306] Trial 22 pruned.

Best trial: 3. Best value: 0.844737:  44%|████▍     | 22/50 [03:55<04:04,  8.74s/it]

[I 2025-12-02 04:20:25,585] Trial 20 finished with value: 0.7934210526315789 and parameters: {'max_depth': 10, 'learning_rate': 0.040832647089350374, 'n_estimators': 1178, 'subsample': 0.7384836628377274, 'colsample_bytree': 0.85561111441075, 'min_child_weight': 4, 'gamma': 2.0661192228640752, 'reg_alpha': 8.142650919984015e-07, 'reg_lambda': 0.33705370243803845, 'max_delta_step': 6}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  46%|████▌     | 23/50 [03:55<02:51,  6.36s/it]

[I 2025-12-02 04:20:26,122] Trial 24 pruned.

Best trial: 3. Best value: 0.844737:  48%|████▊     | 24/50 [03:57<02:08,  4.93s/it]

[I 2025-12-02 04:20:27,609] Trial 25 pruned.

Best trial: 3. Best value: 0.844737:  50%|█████     | 25/50 [03:58<01:37,  3.88s/it]

[I 2025-12-02 04:20:28,973] Trial 23 pruned.

Best trial: 3. Best value: 0.844737:  52%|█████▏    | 26/50 [04:02<01:35,  3.97s/it]

[I 2025-12-02 04:20:33,144] Trial 21 finished with value: 0.7934210526315789 and parameters: {'max_depth': 7, 'learning_rate': 0.03967187650594934, 'n_estimators': 1226, 'subsample': 0.7581920177106858, 'colsample_bytree': 0.859960423018808, 'min_child_weight': 4, 'gamma': 1.9231300190717229, 'reg_alpha': 6.266696977847538e-07, 'reg_lambda': 0.29441992767498354, 'max_delta_step': 6}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 3. Best value: 0.844737:  54%|█████▍    | 27/50 [04:03<01:10,  3.09s/it]

[I 2025-12-02 04:20:34,147] Trial 26 pruned.

Best trial: 3. Best value: 0.844737:  56%|█████▌    | 28/50 [04:06<01:07,  3.07s/it]

[I 2025-12-02 04:20:37,162] Trial 28 pruned.

Best trial: 3. Best value: 0.844737:  58%|█████▊    | 29/50 [04:13<01:28,  4.21s/it]

[I 2025-12-02 04:20:44,056] Trial 31 pruned.

Best trial: 3. Best value: 0.844737:  60%|██████    | 30/50 [04:13<01:00,  3.03s/it]

[I 2025-12-02 04:20:44,314] Trial 27 pruned.

Best trial: 3. Best value: 0.844737:  62%|██████▏   | 31/50 [04:16<00:55,  2.91s/it]

[I 2025-12-02 04:20:46,955] Trial 32 pruned.

Best trial: 3. Best value: 0.844737:  64%|██████▍   | 32/50 [04:17<00:39,  2.19s/it]

[I 2025-12-02 04:20:47,473] Trial 33 pruned.

Best trial: 3. Best value: 0.844737:  66%|██████▌   | 33/50 [04:18<00:33,  1.98s/it]

[I 2025-12-02 04:20:48,953] Trial 30 pruned.

Best trial: 3. Best value: 0.844737:  68%|██████▊   | 34/50 [04:19<00:26,  1.65s/it]

[I 2025-12-02 04:20:49,831] Trial 29 pruned.

Best trial: 3. Best value: 0.844737:  70%|███████   | 35/50 [04:23<00:37,  2.47s/it]

[I 2025-12-02 04:20:54,231] Trial 34 pruned.

Best trial: 3. Best value: 0.844737:  72%|███████▏  | 36/50 [04:25<00:29,  2.11s/it]

[I 2025-12-02 04:20:55,482] Trial 35 pruned.

Best trial: 3. Best value: 0.844737:  74%|███████▍  | 37/50 [04:27<00:28,  2.16s/it]

[I 2025-12-02 04:20:57,754] Trial 36 pruned.

Best trial: 3. Best value: 0.844737:  76%|███████▌  | 38/50 [04:29<00:27,  2.28s/it]

[I 2025-12-02 04:21:00,325] Trial 39 pruned.

Best trial: 3. Best value: 0.844737:  78%|███████▊  | 39/50 [04:31<00:22,  2.06s/it]

[I 2025-12-02 04:21:01,876] Trial 40 pruned.

Best trial: 3. Best value: 0.844737:  80%|████████  | 40/50 [04:41<00:44,  4.45s/it]

[I 2025-12-02 04:21:11,886] Trial 37 finished with value: 0.8447368421052632 and parameters: {'max_depth': 9, 'learning_rate': 0.07224233565474333, 'n_estimators': 465, 'subsample': 0.82024091227745, 'colsample_bytree': 0.7212376541129366, 'min_child_weight': 8, 'gamma': 3.8982743049373125, 'reg_alpha': 2.5653031639011862e-05, 'reg_lambda': 2.748988474068855, 'max_delta_step': 8}. Best is trial 3 with value: 0.8447368421052632.

Best trial: 38. Best value: 0.871053:  82%|████████▏ | 41/50 [04:47<00:43,  4.81s/it]

[I 2025-12-02 04:21:17,531] Trial 38 finished with value: 0.8710526315789473 and parameters: {'max_depth': 8, 'learning_rate': 0.07130737527979421, 'n_estimators': 504, 'subsample': 0.8439584164670841, 'colsample_bytree': 0.7092274968101892, 'min_child_weight': 8, 'gamma': 4.282798203820613, 'reg_alpha': 1.009948542434122e-05, 'reg_lambda': 2.71292021017368, 'max_delta_step': 4}. Best is trial 38 with value: 0.8710526315789473.

Best trial: 38. Best value: 0.871053:  84%|████████▍ | 42/50 [04:49<00:32,  4.06s/it]

[I 2025-12-02 04:21:19,838] Trial 41 finished with value: 0.8197368421052631 and parameters: {'max_depth': 8, 'learning_rate': 0.07591115928583554, 'n_estimators': 328, 'subsample': 0.8447071674192805, 'colsample_bytree': 0.9938517835719264, 'min_child_weight': 3, 'gamma': 1.6914402360284737, 'reg_alpha': 0.008191574498120852, 'reg_lambda': 1.3759907358914405, 'max_delta_step': 7}. Best is trial 38 with value: 0.8710526315789473.

Best trial: 38. Best value: 0.871053:  86%|████████▌ | 43/50 [05:16<01:16, 10.93s/it]

[I 2025-12-02 04:21:46,808] Trial 44 finished with value: 0.8710526315789473 and parameters: {'max_depth': 8, 'learning_rate': 0.2936450289332269, 'n_estimators': 631, 'subsample': 0.8710892029995677, 'colsample_bytree': 0.9113423129210461, 'min_child_weight': 7, 'gamma': 4.600002170944427, 'reg_alpha': 9.945822810131379e-05, 'reg_lambda': 0.8021328023918184, 'max_delta_step': 7}. Best is trial 38 with value: 0.8710526315789473.

Best trial: 38. Best value: 0.871053:  88%|████████▊ | 44/50 [05:16<00:46,  7.72s/it]

[I 2025-12-02 04:21:47,048] Trial 45 finished with value: 0.8447368421052632 and parameters: {'max_depth': 6, 'learning_rate': 0.05482879998079114, 'n_estimators': 603, 'subsample': 0.8747641024939335, 'colsample_bytree': 0.6611481365181612, 'min_child_weight': 7, 'gamma': 4.629546570088234, 'reg_alpha': 0.00014313314045574348, 'reg_lambda': 0.08288210161679367, 'max_delta_step': 5}. Best is trial 38 with value: 0.8710526315789473.

Best trial: 38. Best value: 0.871053:  90%|█████████ | 45/50 [05:21<00:33,  6.73s/it]

[I 2025-12-02 04:21:51,474] Trial 42 finished with value: 0.7934210526315789 and parameters: {'max_depth': 3, 'learning_rate': 0.05358810066021643, 'n_estimators': 1061, 'subsample': 0.5054428173794437, 'colsample_bytree': 0.9591498508688305, 'min_child_weight': 3, 'gamma': 1.2507062090071754, 'reg_alpha': 0.00018554844334273476, 'reg_lambda': 0.06440226433796727, 'max_delta_step': 8}. Best is trial 38 with value: 0.8710526315789473.

Best trial: 38. Best value: 0.871053:  92%|█████████▏| 46/50 [05:31<00:31,  7.84s/it]

[I 2025-12-02 04:22:01,902] Trial 43 finished with value: 0.805921052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.05527799154571409, 'n_estimators': 1092, 'subsample': 0.5077649605197316, 'colsample_bytree': 0.9160945267361351, 'min_child_weight': 3, 'gamma': 0.5722487354067978, 'reg_alpha': 0.00012121708909028161, 'reg_lambda': 0.0867190683529943, 'max_delta_step': 8}. Best is trial 38 with value: 0.8710526315789473.

Best trial: 38. Best value: 0.871053:  94%|█████████▍| 47/50 [05:45<00:28,  9.63s/it]

[I 2025-12-02 04:22:15,691] Trial 46 finished with value: 0.8460526315789474 and parameters: {'max_depth': 6, 'learning_rate': 0.2755231184602713, 'n_estimators': 626, 'subsample': 0.8981274629623076, 'colsample_bytree': 0.9296708951815922, 'min_child_weight': 7, 'gamma': 4.537341776441944, 'reg_alpha': 0.0001392811658100127, 'reg_lambda': 0.06221381291951178, 'max_delta_step': 7}. Best is trial 38 with value: 0.8710526315789473.

Best trial: 38. Best value: 0.871053:  96%|█████████▌| 48/50 [05:49<00:16,  8.09s/it]

[I 2025-12-02 04:22:20,198] Trial 47 finished with value: 0.8322368421052632 and parameters: {'max_depth': 3, 'learning_rate': 0.19491041309911422, 'n_estimators': 642, 'subsample': 0.969910531961768, 'colsample_bytree': 0.9566462214469211, 'min_child_weight': 2, 'gamma': 1.138284187037623, 'reg_alpha': 0.0009417800157159772, 'reg_lambda': 0.6751804714188144, 'max_delta_step': 7}. Best is trial 38 with value: 0.8710526315789473.

Best trial: 38. Best value: 0.871053:  98%|█████████▊| 49/50 [05:50<00:05,  5.97s/it]

[I 2025-12-02 04:22:21,210] Trial 48 finished with value: 0.8197368421052631 and parameters: {'max_depth': 6, 'learning_rate': 0.2838822172937823, 'n_estimators': 704, 'subsample': 0.9297622436142511, 'colsample_bytree': 0.8932204088345089, 'min_child_weight': 7, 'gamma': 4.434740236870844, 'reg_alpha': 0.0009940370264368225, 'reg_lambda': 0.012047783430973213, 'max_delta_step': 9}. Best is trial 38 with value: 0.8710526315789473.

Best trial: 38. Best value: 0.871053: 100%|██████████| 50/50 [05:54<00:00,  7.09s/it]

[I 2025-12-02 04:22:25,000] Trial 49 finished with value: 0.8322368421052632 and parameters: {'max_depth': 4, 'learning_rate': 0.2849142023590782, 'n_estimators': 694, 'subsample': 0.9907666032331275, 'colsample_bytree': 0.536187930820703, 'min_child_weight': 7, 'gamma': 4.361532279485389, 'reg_alpha': 0.0007724798091501087, 'reg_lambda': 0.012407056835234161, 'max_delta_step': 7}. Best is trial 38 with value: 0.8710526315789473.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    17_1         loo       0.784981                    0.75          0.77
1    19_1         loo       0.871053                    0.70          0.61
2    15_1         loo       0.616816                    0.45          0.58
3     9_1         loo       0.821053                    0.45          0.46

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.533002               0.6               0.9        50          60
1  0.400000               0.6               0.8        50          59
2 -0.094491               0.4               0.5        50          60
3 -0.100000               0.6               0.3        50          59

   test_size
0         15
1         15
2         15
3         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    17_1         loo       0.784981                    0.75          0.77
1    19_1         loo       0.871053                    0.70          0.61
2    15_1         loo       0.616816                    0.45          0.58
3     9_1         loo       0.821053                    0.45          0.46

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.533002               0.6               0.9        50          60
1  0.400000               0.6               0.8        50          59
2 -0.094491               0.4               0.5        50          60
3 -0.100000               0.6               0.3        50          59

   test_size
0         15
1         15
2         15
3         15

In [ ]:

# Temporal embedings
datasets = task_temp_dfs_pd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    #    scoring="balanced_accuracy",     # or "roc_auc"
    scoring="balanced_accuracy",      
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_pd_hc_{CV_STRATEGY}_tasks/xgb_results_temporal_pd_hc_extended_{CV_STRATEGY}_tasks",
    split_param="emb_",
)
print(summary)

[I 2025-12-02 04:22:28,166] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.1375:   2%|▏         | 1/50 [00:24<20:22, 24.95s/it]

[I 2025-12-02 04:22:53,112] Trial 1 finished with value: 0.1375 and parameters: {'max_depth': 8, 'learning_rate': 0.05502339677961636, 'n_estimators': 521, 'subsample': 0.7740519856607999, 'colsample_bytree': 0.8094190292386626, 'min_child_weight': 10, 'gamma': 2.282094767801264, 'reg_alpha': 0.0028621000801513953, 'reg_lambda': 0.0019464995471946166, 'max_delta_step': 3}. Best is trial 1 with value: 0.1375.

Best trial: 2. Best value: 0.475:   4%|▍         | 2/50 [00:34<12:48, 16.01s/it]

[I 2025-12-02 04:23:02,864] Trial 2 finished with value: 0.475 and parameters: {'max_depth': 4, 'learning_rate': 0.026933117176107312, 'n_estimators': 754, 'subsample': 0.5373772162132111, 'colsample_bytree': 0.7769703322256254, 'min_child_weight': 8, 'gamma': 3.896090475066539, 'reg_alpha': 0.0003456478656791948, 'reg_lambda': 3.40748659338687e-05, 'max_delta_step': 8}. Best is trial 2 with value: 0.475.

Best trial: 4. Best value: 0.598026:   6%|▌         | 3/50 [00:46<11:08, 14.23s/it]

[I 2025-12-02 04:23:14,975] Trial 4 finished with value: 0.5980263157894736 and parameters: {'max_depth': 4, 'learning_rate': 0.05137921095404776, 'n_estimators': 396, 'subsample': 0.6707941802340134, 'colsample_bytree': 0.7492930426273627, 'min_child_weight': 6, 'gamma': 0.02176104349118635, 'reg_alpha': 0.0008073586157778023, 'reg_lambda': 6.469286094664708e-08, 'max_delta_step': 8}. Best is trial 4 with value: 0.5980263157894736.

Best trial: 3. Best value: 0.638158:   8%|▊         | 4/50 [00:49<07:18,  9.53s/it]

[I 2025-12-02 04:23:17,292] Trial 3 finished with value: 0.638157894736842 and parameters: {'max_depth': 6, 'learning_rate': 0.1277081564771843, 'n_estimators': 1119, 'subsample': 0.8225444446021153, 'colsample_bytree': 0.5219340763978122, 'min_child_weight': 8, 'gamma': 2.058566640478536, 'reg_alpha': 1.7049738083692982e-06, 'reg_lambda': 0.04725001330709087, 'max_delta_step': 6}. Best is trial 3 with value: 0.638157894736842.

Best trial: 3. Best value: 0.638158:  10%|█         | 5/50 [01:01<07:55, 10.56s/it]

[I 2025-12-02 04:23:29,673] Trial 0 finished with value: 0.5480263157894737 and parameters: {'max_depth': 6, 'learning_rate': 0.11510470999461123, 'n_estimators': 1224, 'subsample': 0.922340643456655, 'colsample_bytree': 0.5564963267642304, 'min_child_weight': 4, 'gamma': 3.995819256896354, 'reg_alpha': 7.456725000567211, 'reg_lambda': 2.785783141033999e-08, 'max_delta_step': 1}. Best is trial 3 with value: 0.638157894736842.

Best trial: 3. Best value: 0.638158:  12%|█▏        | 6/50 [01:30<12:26, 16.97s/it]

[I 2025-12-02 04:23:59,102] Trial 5 finished with value: 0.0875 and parameters: {'max_depth': 9, 'learning_rate': 0.08482748384504424, 'n_estimators': 1402, 'subsample': 0.5291409498045629, 'colsample_bytree': 0.9028757653357744, 'min_child_weight': 9, 'gamma': 3.0603873158182244, 'reg_alpha': 0.049286528948232905, 'reg_lambda': 9.36801808953821, 'max_delta_step': 1}. Best is trial 3 with value: 0.638157894736842.

Best trial: 3. Best value: 0.638158:  14%|█▍        | 7/50 [01:33<08:47, 12.28s/it]

[I 2025-12-02 04:24:01,713] Trial 7 finished with value: 0.5203947368421052 and parameters: {'max_depth': 6, 'learning_rate': 0.03236830594163263, 'n_estimators': 1139, 'subsample': 0.6464456193049521, 'colsample_bytree': 0.7781675374061185, 'min_child_weight': 8, 'gamma': 0.6329384165402857, 'reg_alpha': 0.00017522713208878386, 'reg_lambda': 0.014470075849021288, 'max_delta_step': 4}. Best is trial 3 with value: 0.638157894736842.

Best trial: 3. Best value: 0.638158:  16%|█▌        | 8/50 [01:47<09:02, 12.93s/it]

[I 2025-12-02 04:24:16,024] Trial 9 finished with value: 0.5855263157894737 and parameters: {'max_depth': 10, 'learning_rate': 0.038518952558907804, 'n_estimators': 373, 'subsample': 0.5881002525294385, 'colsample_bytree': 0.5505191042204902, 'min_child_weight': 5, 'gamma': 4.868169589991561, 'reg_alpha': 0.002402977266577341, 'reg_lambda': 0.00025517437812704616, 'max_delta_step': 5}. Best is trial 3 with value: 0.638157894736842.

Best trial: 3. Best value: 0.638158:  18%|█▊        | 9/50 [01:51<06:46,  9.92s/it]

[I 2025-12-02 04:24:19,326] Trial 8 finished with value: 0.6144736842105263 and parameters: {'max_depth': 9, 'learning_rate': 0.050666082047231636, 'n_estimators': 1280, 'subsample': 0.9178488395086306, 'colsample_bytree': 0.7434300446535678, 'min_child_weight': 8, 'gamma': 1.310384211599624, 'reg_alpha': 5.945456214401221e-06, 'reg_lambda': 1.1311270430009648e-06, 'max_delta_step': 7}. Best is trial 3 with value: 0.638157894736842.

Best trial: 3. Best value: 0.638158:  20%|██        | 10/50 [02:08<08:02, 12.07s/it]

[I 2025-12-02 04:24:36,216] Trial 6 finished with value: 0.5717105263157894 and parameters: {'max_depth': 5, 'learning_rate': 0.01564905961591161, 'n_estimators': 1172, 'subsample': 0.6226178545371683, 'colsample_bytree': 0.7377197513509248, 'min_child_weight': 1, 'gamma': 0.5318699230282836, 'reg_alpha': 0.0621072891607128, 'reg_lambda': 0.024731620505049155, 'max_delta_step': 0}. Best is trial 3 with value: 0.638157894736842.

Best trial: 3. Best value: 0.638158:  22%|██▏       | 11/50 [02:14<06:47, 10.45s/it]

[I 2025-12-02 04:24:42,979] Trial 10 finished with value: 0.5993421052631579 and parameters: {'max_depth': 10, 'learning_rate': 0.030635446218862633, 'n_estimators': 990, 'subsample': 0.951508859736406, 'colsample_bytree': 0.9704834357261763, 'min_child_weight': 7, 'gamma': 4.028737120230657, 'reg_alpha': 7.915785407071992e-05, 'reg_lambda': 0.024883246195821655, 'max_delta_step': 4}. Best is trial 3 with value: 0.638157894736842.

Best trial: 3. Best value: 0.638158:  24%|██▍       | 12/50 [02:17<05:08,  8.13s/it]

[I 2025-12-02 04:24:45,809] Trial 12 finished with value: 0.5717105263157894 and parameters: {'max_depth': 10, 'learning_rate': 0.27032290634865297, 'n_estimators': 694, 'subsample': 0.8176942794578483, 'colsample_bytree': 0.8001213568780525, 'min_child_weight': 4, 'gamma': 1.8764544157261132, 'reg_alpha': 8.180031297934607e-08, 'reg_lambda': 0.18608491110426037, 'max_delta_step': 3}. Best is trial 3 with value: 0.638157894736842.

Best trial: 3. Best value: 0.638158:  26%|██▌       | 13/50 [02:27<05:18,  8.60s/it]

[I 2025-12-02 04:24:55,492] Trial 15 pruned.

Best trial: 3. Best value: 0.638158:  28%|██▊       | 14/50 [02:34<04:54,  8.19s/it]

[I 2025-12-02 04:25:02,742] Trial 14 pruned.

Best trial: 3. Best value: 0.638158:  30%|███       | 15/50 [02:40<04:25,  7.59s/it]

[I 2025-12-02 04:25:08,952] Trial 17 pruned.

Best trial: 3. Best value: 0.638158:  32%|███▏      | 16/50 [02:46<03:59,  7.06s/it]

[I 2025-12-02 04:25:14,765] Trial 16 pruned.

Best trial: 3. Best value: 0.638158:  34%|███▍      | 17/50 [02:52<03:41,  6.72s/it]

[I 2025-12-02 04:25:20,712] Trial 13 finished with value: 0.6105263157894737 and parameters: {'max_depth': 3, 'learning_rate': 0.295241705376521, 'n_estimators': 898, 'subsample': 0.8299001293106423, 'colsample_bytree': 0.6184343650760998, 'min_child_weight': 2, 'gamma': 1.9795995549562324, 'reg_alpha': 1.9290382338839806e-08, 'reg_lambda': 2.5133665841472657, 'max_delta_step': 10}. Best is trial 3 with value: 0.638157894736842.

Best trial: 3. Best value: 0.638158:  36%|███▌      | 18/50 [02:54<02:46,  5.21s/it]

[I 2025-12-02 04:25:22,382] Trial 11 finished with value: 0.5328947368421053 and parameters: {'max_depth': 3, 'learning_rate': 0.011670278664475611, 'n_estimators': 1130, 'subsample': 0.7866843637569749, 'colsample_bytree': 0.6721494107609847, 'min_child_weight': 3, 'gamma': 0.6859657801840985, 'reg_alpha': 0.005502377403696462, 'reg_lambda': 0.0030114442338852842, 'max_delta_step': 3}. Best is trial 3 with value: 0.638157894736842.

Best trial: 3. Best value: 0.638158:  38%|███▊      | 19/50 [03:01<02:58,  5.77s/it]

[I 2025-12-02 04:25:29,467] Trial 20 pruned.

Best trial: 3. Best value: 0.638158:  40%|████      | 20/50 [03:09<03:11,  6.39s/it]

[I 2025-12-02 04:25:37,290] Trial 22 pruned.

Best trial: 3. Best value: 0.638158:  42%|████▏     | 21/50 [03:17<03:25,  7.08s/it]

[I 2025-12-02 04:25:45,980] Trial 23 pruned.

Best trial: 18. Best value: 0.667105:  44%|████▍     | 22/50 [03:29<03:57,  8.50s/it]

[I 2025-12-02 04:25:57,788] Trial 18 finished with value: 0.6671052631578948 and parameters: {'max_depth': 3, 'learning_rate': 0.1473233442146696, 'n_estimators': 1287, 'subsample': 0.7059722988517642, 'colsample_bytree': 0.672475738793775, 'min_child_weight': 8, 'gamma': 2.9503174604650355, 'reg_alpha': 3.645178241240455e-06, 'reg_lambda': 2.364354494494698, 'max_delta_step': 7}. Best is trial 18 with value: 0.6671052631578948.

Best trial: 18. Best value: 0.667105:  46%|████▌     | 23/50 [03:39<03:58,  8.83s/it]

[I 2025-12-02 04:26:07,388] Trial 25 pruned.

Best trial: 18. Best value: 0.667105:  48%|████▊     | 24/50 [03:46<03:39,  8.45s/it]

[I 2025-12-02 04:26:14,944] Trial 21 finished with value: 0.6407894736842106 and parameters: {'max_depth': 5, 'learning_rate': 0.07280693528552679, 'n_estimators': 1316, 'subsample': 0.7186028173653874, 'colsample_bytree': 0.8737949760274851, 'min_child_weight': 8, 'gamma': 2.895344302008994, 'reg_alpha': 1.9735476464840066e-05, 'reg_lambda': 0.5096838246462432, 'max_delta_step': 6}. Best is trial 18 with value: 0.6671052631578948.

Best trial: 18. Best value: 0.667105:  50%|█████     | 25/50 [03:47<02:31,  6.07s/it]

[I 2025-12-02 04:26:15,482] Trial 26 pruned.

Best trial: 18. Best value: 0.667105:  52%|█████▏    | 26/50 [03:49<01:55,  4.80s/it]

[I 2025-12-02 04:26:17,309] Trial 28 pruned.

Best trial: 18. Best value: 0.667105:  54%|█████▍    | 27/50 [04:01<02:41,  7.02s/it]

[I 2025-12-02 04:26:29,518] Trial 24 finished with value: 0.6368421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.185579181319411, 'n_estimators': 780, 'subsample': 0.8610889201118156, 'colsample_bytree': 0.5737792016031413, 'min_child_weight': 1, 'gamma': 2.481967235052941, 'reg_alpha': 5.412421281899094e-07, 'reg_lambda': 4.143907220319564, 'max_delta_step': 9}. Best is trial 18 with value: 0.6671052631578948.

Best trial: 18. Best value: 0.667105:  56%|█████▌    | 28/50 [04:07<02:26,  6.67s/it]

[I 2025-12-02 04:26:35,379] Trial 19 finished with value: 0.5980263157894736 and parameters: {'max_depth': 3, 'learning_rate': 0.06588825502122694, 'n_estimators': 1291, 'subsample': 0.7406890254784038, 'colsample_bytree': 0.8893392816034411, 'min_child_weight': 1, 'gamma': 2.913791326087863, 'reg_alpha': 1.0408871673586196e-05, 'reg_lambda': 0.9112359355786355, 'max_delta_step': 6}. Best is trial 18 with value: 0.6671052631578948.

Best trial: 18. Best value: 0.667105:  58%|█████▊    | 29/50 [04:08<01:44,  4.98s/it]

[I 2025-12-02 04:26:36,420] Trial 30 pruned.

Best trial: 18. Best value: 0.667105:  60%|██████    | 30/50 [04:31<03:26, 10.35s/it]

[I 2025-12-02 04:26:59,279] Trial 27 finished with value: 0.5480263157894737 and parameters: {'max_depth': 4, 'learning_rate': 0.11545537447529264, 'n_estimators': 1064, 'subsample': 0.6873235247961138, 'colsample_bytree': 0.8610876120849794, 'min_child_weight': 7, 'gamma': 2.377293061815448, 'reg_alpha': 2.6956561732621837e-05, 'reg_lambda': 0.11051908725236785, 'max_delta_step': 5}. Best is trial 18 with value: 0.6671052631578948.

Best trial: 18. Best value: 0.667105:  62%|██████▏   | 31/50 [04:33<02:33,  8.08s/it]

[I 2025-12-02 04:27:02,086] Trial 29 finished with value: 0.5743421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.07395862494984069, 'n_estimators': 1060, 'subsample': 0.7585952016967048, 'colsample_bytree': 0.8361170344485729, 'min_child_weight': 7, 'gamma': 3.6441516553579225, 'reg_alpha': 9.102598378022028e-07, 'reg_lambda': 6.263160095460568, 'max_delta_step': 6}. Best is trial 18 with value: 0.6671052631578948.

Best trial: 18. Best value: 0.667105:  64%|██████▍   | 32/50 [04:53<03:26, 11.45s/it]

[I 2025-12-02 04:27:21,399] Trial 31 finished with value: 0.6519736842105264 and parameters: {'max_depth': 5, 'learning_rate': 0.09849881476434845, 'n_estimators': 1051, 'subsample': 0.7773391077936012, 'colsample_bytree': 0.841999116186178, 'min_child_weight': 7, 'gamma': 3.4013397149350686, 'reg_alpha': 3.856919839689936e-05, 'reg_lambda': 0.06604712997158445, 'max_delta_step': 5}. Best is trial 18 with value: 0.6671052631578948.

Best trial: 18. Best value: 0.667105:  66%|██████▌   | 33/50 [04:56<02:32,  8.99s/it]

[I 2025-12-02 04:27:24,630] Trial 32 finished with value: 0.5855263157894737 and parameters: {'max_depth': 4, 'learning_rate': 0.10965175669268873, 'n_estimators': 1038, 'subsample': 0.7815362018828879, 'colsample_bytree': 0.8609432346679132, 'min_child_weight': 5, 'gamma': 3.8797217765310057, 'reg_alpha': 1.7793630478147364, 'reg_lambda': 0.068699434688526, 'max_delta_step': 5}. Best is trial 18 with value: 0.6671052631578948.

Best trial: 18. Best value: 0.667105:  68%|██████▊   | 34/50 [05:02<02:08,  8.04s/it]

[I 2025-12-02 04:27:30,461] Trial 35 pruned.

Best trial: 18. Best value: 0.667105:  70%|███████   | 35/50 [05:07<01:47,  7.13s/it]

[I 2025-12-02 04:27:35,481] Trial 36 pruned.

Best trial: 18. Best value: 0.667105:  72%|███████▏  | 36/50 [05:08<01:16,  5.48s/it]

[I 2025-12-02 04:27:37,085] Trial 34 finished with value: 0.5467105263157894 and parameters: {'max_depth': 4, 'learning_rate': 0.20264585994683287, 'n_estimators': 786, 'subsample': 0.8058106201517975, 'colsample_bytree': 0.5548173433232938, 'min_child_weight': 5, 'gamma': 2.5554802063636277, 'reg_alpha': 4.6603203568096337e-07, 'reg_lambda': 4.488532431710967, 'max_delta_step': 9}. Best is trial 18 with value: 0.6671052631578948.

Best trial: 18. Best value: 0.667105:  74%|███████▍  | 37/50 [05:12<01:04,  4.96s/it]

[I 2025-12-02 04:27:40,833] Trial 37 pruned.

Best trial: 18. Best value: 0.667105:  76%|███████▌  | 38/50 [05:18<01:03,  5.32s/it]

[I 2025-12-02 04:27:47,010] Trial 39 pruned.

Best trial: 18. Best value: 0.667105:  78%|███████▊  | 39/50 [05:22<00:52,  4.77s/it]

[I 2025-12-02 04:27:50,490] Trial 40 pruned.

Best trial: 18. Best value: 0.667105:  80%|████████  | 40/50 [05:27<00:48,  4.90s/it]

[I 2025-12-02 04:27:55,682] Trial 41 pruned.

Best trial: 18. Best value: 0.667105:  82%|████████▏ | 41/50 [05:31<00:40,  4.52s/it]

[I 2025-12-02 04:27:59,334] Trial 42 pruned.

Best trial: 18. Best value: 0.667105:  84%|████████▍ | 42/50 [05:34<00:34,  4.29s/it]

[I 2025-12-02 04:28:03,095] Trial 33 finished with value: 0.5993421052631579 and parameters: {'max_depth': 6, 'learning_rate': 0.09929261061453919, 'n_estimators': 1185, 'subsample': 0.7904134592636202, 'colsample_bytree': 0.9965770103851886, 'min_child_weight': 5, 'gamma': 3.8702052548056765, 'reg_alpha': 5.009089145207868, 'reg_lambda': 0.0029138215636476746, 'max_delta_step': 7}. Best is trial 18 with value: 0.6671052631578948.

Best trial: 18. Best value: 0.667105:  86%|████████▌ | 43/50 [05:36<00:23,  3.40s/it]

[I 2025-12-02 04:28:04,413] Trial 43 pruned.

Best trial: 18. Best value: 0.667105:  88%|████████▊ | 44/50 [06:02<01:01, 10.17s/it]

[I 2025-12-02 04:28:30,386] Trial 44 finished with value: 0.6105263157894737 and parameters: {'max_depth': 3, 'learning_rate': 0.17643413096392624, 'n_estimators': 665, 'subsample': 0.858742224586808, 'colsample_bytree': 0.535470117406441, 'min_child_weight': 3, 'gamma': 2.4524045255403784, 'reg_alpha': 7.978063674117107e-08, 'reg_lambda': 1.6965657202156752, 'max_delta_step': 9}. Best is trial 18 with value: 0.6671052631578948.

Best trial: 18. Best value: 0.667105:  90%|█████████ | 45/50 [06:06<00:41,  8.31s/it]

[I 2025-12-02 04:28:34,359] Trial 38 finished with value: 0.569078947368421 and parameters: {'max_depth': 5, 'learning_rate': 0.21767453021630423, 'n_estimators': 1385, 'subsample': 0.5916891105606648, 'colsample_bytree': 0.793153357805303, 'min_child_weight': 8, 'gamma': 3.208581028994024, 'reg_alpha': 0.0003251229398654162, 'reg_lambda': 0.009188672885059377, 'max_delta_step': 7}. Best is trial 18 with value: 0.6671052631578948.

Best trial: 18. Best value: 0.667105:  92%|█████████▏| 46/50 [06:14<00:32,  8.24s/it]

[I 2025-12-02 04:28:42,430] Trial 46 finished with value: 0.5730263157894737 and parameters: {'max_depth': 3, 'learning_rate': 0.17654780064024955, 'n_estimators': 791, 'subsample': 0.9125810651657045, 'colsample_bytree': 0.5945531258665779, 'min_child_weight': 3, 'gamma': 2.3422307104620024, 'reg_alpha': 7.327314068061538e-08, 'reg_lambda': 1.5846308532166453, 'max_delta_step': 9}. Best is trial 18 with value: 0.6671052631578948.

Best trial: 18. Best value: 0.667105:  94%|█████████▍| 47/50 [06:15<00:18,  6.10s/it]

[I 2025-12-02 04:28:43,539] Trial 45 finished with value: 0.5855263157894737 and parameters: {'max_depth': 3, 'learning_rate': 0.23108005083127975, 'n_estimators': 819, 'subsample': 0.8405001497804335, 'colsample_bytree': 0.5909464912854367, 'min_child_weight': 2, 'gamma': 2.419567274490891, 'reg_alpha': 7.83231776154217e-08, 'reg_lambda': 1.4619827088229798, 'max_delta_step': 9}. Best is trial 18 with value: 0.6671052631578948.

Best trial: 18. Best value: 0.667105:  96%|█████████▌| 48/50 [06:30<00:17,  8.96s/it]

[I 2025-12-02 04:28:59,154] Trial 47 finished with value: 0.5881578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.2498279843565785, 'n_estimators': 824, 'subsample': 0.9152609638959441, 'colsample_bytree': 0.5926263450428183, 'min_child_weight': 8, 'gamma': 2.7696821879946403, 'reg_alpha': 2.604922585984049e-07, 'reg_lambda': 6.216085008147941, 'max_delta_step': 8}. Best is trial 18 with value: 0.6671052631578948.

Best trial: 18. Best value: 0.667105:  98%|█████████▊| 49/50 [06:32<00:06,  6.71s/it]

[I 2025-12-02 04:29:00,624] Trial 48 finished with value: 0.5730263157894737 and parameters: {'max_depth': 4, 'learning_rate': 0.23687618996779305, 'n_estimators': 551, 'subsample': 0.9118492753864939, 'colsample_bytree': 0.5864844742862443, 'min_child_weight': 2, 'gamma': 2.76636117121262, 'reg_alpha': 2.1389243465894053e-07, 'reg_lambda': 9.499459310378986, 'max_delta_step': 9}. Best is trial 18 with value: 0.6671052631578948.

Best trial: 18. Best value: 0.667105: 100%|██████████| 50/50 [06:36<00:00,  7.92s/it]

[I 2025-12-02 04:29:04,251] Trial 49 finished with value: 0.5855263157894737 and parameters: {'max_depth': 4, 'learning_rate': 0.24547019101620984, 'n_estimators': 596, 'subsample': 0.8389732472816058, 'colsample_bytree': 0.5734952214734687, 'min_child_weight': 4, 'gamma': 2.701097848024335, 'reg_alpha': 4.687242525344609e-06, 'reg_lambda': 9.71022341393287, 'max_delta_step': 8}. Best is trial 18 with value: 0.6671052631578948.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 04:29:07,347] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.562259:   2%|▏         | 1/50 [00:19<15:45, 19.29s/it]

[I 2025-12-02 04:29:26,634] Trial 3 finished with value: 0.5622593068035944 and parameters: {'max_depth': 6, 'learning_rate': 0.17807902750403898, 'n_estimators': 425, 'subsample': 0.5910121177726847, 'colsample_bytree': 0.627110770920011, 'min_child_weight': 6, 'gamma': 0.7191694922740482, 'reg_alpha': 1.2337543025070296e-05, 'reg_lambda': 4.988692999846133e-05, 'max_delta_step': 0}. Best is trial 3 with value: 0.5622593068035944.

Best trial: 2. Best value: 0.57638:   4%|▍         | 2/50 [00:30<11:37, 14.52s/it]

[I 2025-12-02 04:29:37,817] Trial 2 finished with value: 0.576379974326059 and parameters: {'max_depth': 9, 'learning_rate': 0.026915800318611436, 'n_estimators': 673, 'subsample': 0.7370130567585211, 'colsample_bytree': 0.5243248307462907, 'min_child_weight': 7, 'gamma': 4.883617269640889, 'reg_alpha': 0.004875971970902593, 'reg_lambda': 2.6492661736700717e-08, 'max_delta_step': 7}. Best is trial 2 with value: 0.576379974326059.

Best trial: 2. Best value: 0.57638:   6%|▌         | 3/50 [00:35<07:57, 10.16s/it]

[I 2025-12-02 04:29:42,793] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.014205326027896047, 'n_estimators': 833, 'subsample': 0.7363338972446211, 'colsample_bytree': 0.7829456464963234, 'min_child_weight': 10, 'gamma': 2.7254318669182127, 'reg_alpha': 0.011482756268754505, 'reg_lambda': 2.318775174357761e-07, 'max_delta_step': 1}. Best is trial 2 with value: 0.576379974326059.

Best trial: 2. Best value: 0.57638:   8%|▊         | 4/50 [00:45<07:51, 10.24s/it]

[I 2025-12-02 04:29:53,152] Trial 5 finished with value: 0.5397946084724006 and parameters: {'max_depth': 3, 'learning_rate': 0.02377019398807095, 'n_estimators': 295, 'subsample': 0.5706882857243234, 'colsample_bytree': 0.835514975198963, 'min_child_weight': 6, 'gamma': 0.9189815468487395, 'reg_alpha': 9.269897609013645e-08, 'reg_lambda': 4.45010486074257e-05, 'max_delta_step': 6}. Best is trial 2 with value: 0.576379974326059.

Best trial: 2. Best value: 0.57638:  10%|█         | 5/50 [00:55<07:33, 10.08s/it]

[I 2025-12-02 04:30:02,949] Trial 6 finished with value: 0.5661103979460848 and parameters: {'max_depth': 9, 'learning_rate': 0.22938887078054251, 'n_estimators': 456, 'subsample': 0.6911803993843675, 'colsample_bytree': 0.6437506676156033, 'min_child_weight': 6, 'gamma': 2.299157432902843, 'reg_alpha': 0.010542534972025815, 'reg_lambda': 0.15889238553678328, 'max_delta_step': 3}. Best is trial 2 with value: 0.576379974326059.

Best trial: 4. Best value: 0.614891:  12%|█▏        | 6/50 [00:58<05:38,  7.69s/it]

[I 2025-12-02 04:30:05,991] Trial 4 finished with value: 0.6148908857509627 and parameters: {'max_depth': 6, 'learning_rate': 0.2409616988716518, 'n_estimators': 935, 'subsample': 0.5740617828600894, 'colsample_bytree': 0.6020896856959073, 'min_child_weight': 2, 'gamma': 0.8940818450555815, 'reg_alpha': 5.9610024334660535e-05, 'reg_lambda': 0.0007906138109279682, 'max_delta_step': 6}. Best is trial 4 with value: 0.6148908857509627.

Best trial: 4. Best value: 0.614891:  14%|█▍        | 7/50 [01:11<06:40,  9.31s/it]

[I 2025-12-02 04:30:18,638] Trial 0 finished with value: 0.5622593068035944 and parameters: {'max_depth': 9, 'learning_rate': 0.014190956705892172, 'n_estimators': 1228, 'subsample': 0.8974783668128625, 'colsample_bytree': 0.9758884668980349, 'min_child_weight': 5, 'gamma': 4.02320979189514, 'reg_alpha': 0.03863641130353495, 'reg_lambda': 3.1353732767382224e-06, 'max_delta_step': 0}. Best is trial 4 with value: 0.6148908857509627.

Best trial: 4. Best value: 0.614891:  16%|█▌        | 8/50 [01:19<06:15,  8.94s/it]

[I 2025-12-02 04:30:26,800] Trial 9 finished with value: 0.5500641848523748 and parameters: {'max_depth': 7, 'learning_rate': 0.03510683472664577, 'n_estimators': 464, 'subsample': 0.7023120735999442, 'colsample_bytree': 0.994419060137389, 'min_child_weight': 7, 'gamma': 1.3128103622606817, 'reg_alpha': 0.0003349146827619924, 'reg_lambda': 4.838210223426339, 'max_delta_step': 4}. Best is trial 4 with value: 0.6148908857509627.

Best trial: 4. Best value: 0.614891:  18%|█▊        | 9/50 [01:25<05:28,  8.02s/it]

[I 2025-12-02 04:30:32,780] Trial 8 finished with value: 0.5641848523748395 and parameters: {'max_depth': 9, 'learning_rate': 0.012960812687581431, 'n_estimators': 459, 'subsample': 0.8802948244142881, 'colsample_bytree': 0.7719331748369711, 'min_child_weight': 5, 'gamma': 3.174960581921173, 'reg_alpha': 5.232156777804233e-05, 'reg_lambda': 6.567243998560349, 'max_delta_step': 9}. Best is trial 4 with value: 0.6148908857509627.

Best trial: 4. Best value: 0.614891:  20%|██        | 10/50 [01:35<05:45,  8.65s/it]

[I 2025-12-02 04:30:42,837] Trial 11 finished with value: 0.5378690629011553 and parameters: {'max_depth': 10, 'learning_rate': 0.08001658401686337, 'n_estimators': 335, 'subsample': 0.9836643121164732, 'colsample_bytree': 0.5354968568240659, 'min_child_weight': 6, 'gamma': 1.3425375079767088, 'reg_alpha': 2.833883677827485e-08, 'reg_lambda': 0.011573712808191843, 'max_delta_step': 0}. Best is trial 4 with value: 0.6148908857509627.

Best trial: 4. Best value: 0.614891:  22%|██▏       | 11/50 [01:36<04:04,  6.26s/it]

[I 2025-12-02 04:30:43,694] Trial 7 finished with value: 0.5641848523748395 and parameters: {'max_depth': 4, 'learning_rate': 0.029607207131999116, 'n_estimators': 1090, 'subsample': 0.6316074089756147, 'colsample_bytree': 0.6985859258591685, 'min_child_weight': 4, 'gamma': 3.1464880135559947, 'reg_alpha': 4.961398275274853, 'reg_lambda': 0.21765571727057417, 'max_delta_step': 4}. Best is trial 4 with value: 0.6148908857509627.

Best trial: 4. Best value: 0.614891:  24%|██▍       | 12/50 [01:57<06:55, 10.93s/it]

[I 2025-12-02 04:31:05,299] Trial 10 finished with value: 0.5500641848523748 and parameters: {'max_depth': 10, 'learning_rate': 0.011973970808743883, 'n_estimators': 958, 'subsample': 0.8606783190346695, 'colsample_bytree': 0.9025130976012854, 'min_child_weight': 7, 'gamma': 1.9222830184900692, 'reg_alpha': 0.1318792609230643, 'reg_lambda': 0.005831297106544097, 'max_delta_step': 1}. Best is trial 4 with value: 0.6148908857509627.

Best trial: 4. Best value: 0.614891:  26%|██▌       | 13/50 [02:13<07:37, 12.37s/it]

[I 2025-12-02 04:31:20,989] Trial 14 finished with value: 0.6007702182284981 and parameters: {'max_depth': 6, 'learning_rate': 0.08405632710948348, 'n_estimators': 803, 'subsample': 0.5103829125433168, 'colsample_bytree': 0.5068860820781659, 'min_child_weight': 1, 'gamma': 4.977424256755353, 'reg_alpha': 3.488781669973997e-06, 'reg_lambda': 1.640739254779076e-08, 'max_delta_step': 7}. Best is trial 4 with value: 0.6148908857509627.

Best trial: 4. Best value: 0.614891:  28%|██▊       | 14/50 [02:27<07:39, 12.77s/it]

[I 2025-12-02 04:31:34,680] Trial 13 finished with value: 0.6007702182284981 and parameters: {'max_depth': 5, 'learning_rate': 0.09283846810984671, 'n_estimators': 1228, 'subsample': 0.5049730248184255, 'colsample_bytree': 0.652323426492131, 'min_child_weight': 1, 'gamma': 0.13979976586148624, 'reg_alpha': 1.6738276132203697e-06, 'reg_lambda': 0.0019390673838364095, 'max_delta_step': 9}. Best is trial 4 with value: 0.6148908857509627.

Best trial: 4. Best value: 0.614891:  30%|███       | 15/50 [02:27<05:14,  8.99s/it]

[I 2025-12-02 04:31:34,923] Trial 12 finished with value: 0.5237483953786906 and parameters: {'max_depth': 9, 'learning_rate': 0.023927688530819016, 'n_estimators': 1174, 'subsample': 0.9380411654274976, 'colsample_bytree': 0.9629459363427003, 'min_child_weight': 4, 'gamma': 0.5585087711358477, 'reg_alpha': 0.006207429798230482, 'reg_lambda': 3.3819197484012136e-08, 'max_delta_step': 3}. Best is trial 4 with value: 0.6148908857509627.

Best trial: 15. Best value: 0.665597:  32%|███▏      | 16/50 [02:34<04:45,  8.39s/it]

[I 2025-12-02 04:31:41,893] Trial 15 finished with value: 0.6655969191270861 and parameters: {'max_depth': 6, 'learning_rate': 0.08453119595258318, 'n_estimators': 740, 'subsample': 0.5336129035371813, 'colsample_bytree': 0.5099864286739696, 'min_child_weight': 1, 'gamma': 4.466246007498065, 'reg_alpha': 3.733335757521703e-06, 'reg_lambda': 3.981884085415447e-08, 'max_delta_step': 7}. Best is trial 15 with value: 0.6655969191270861.

Best trial: 15. Best value: 0.665597:  34%|███▍      | 17/50 [03:25<11:41, 21.25s/it]

[I 2025-12-02 04:32:33,063] Trial 16 finished with value: 0.6392811296534018 and parameters: {'max_depth': 5, 'learning_rate': 0.10714229158442463, 'n_estimators': 1429, 'subsample': 0.50596203452764, 'colsample_bytree': 0.581259167194623, 'min_child_weight': 1, 'gamma': 4.954143852285985, 'reg_alpha': 1.4512306611846366e-06, 'reg_lambda': 0.0007449743198718711, 'max_delta_step': 8}. Best is trial 15 with value: 0.6655969191270861.

Best trial: 15. Best value: 0.665597:  36%|███▌      | 18/50 [03:33<09:10, 17.21s/it]

[I 2025-12-02 04:32:40,860] Trial 17 finished with value: 0.6148908857509627 and parameters: {'max_depth': 5, 'learning_rate': 0.14127200722815886, 'n_estimators': 1480, 'subsample': 0.5485296760636501, 'colsample_bytree': 0.6259542184172775, 'min_child_weight': 1, 'gamma': 0.022544883131603632, 'reg_alpha': 5.193790456305119e-07, 'reg_lambda': 0.001145739149419748, 'max_delta_step': 10}. Best is trial 15 with value: 0.6655969191270861.
[I 2025-12-02 04:32:40,875] Trial 18 finished with value: 0.5885750962772786 and parameters: {'max_depth': 5, 'learning_rate': 0.12982186019349773, 'n_estimators': 1478, 'subsample': 0.5269516275342424, 'colsample_bytree': 0.60911444400593, 'min_child_weight': 1, 'gamma': 0.03704577896619039, 'reg_alpha': 2.908510335542419e-07, 'reg_lambda': 0.00042804968389736583, 'max_delta_step': 10}. Best is trial 15 with value: 0.6655969191270861.

Best trial: 15. Best value: 0.665597:  40%|████      | 20/50 [03:41<05:35, 11.20s/it]

[I 2025-12-02 04:32:49,256] Trial 19 finished with value: 0.6514762516046213 and parameters: {'max_depth': 5, 'learning_rate': 0.14798900489803854, 'n_estimators': 1492, 'subsample': 0.630252374532927, 'colsample_bytree': 0.5854892898525941, 'min_child_weight': 2, 'gamma': 4.015320498331677, 'reg_alpha': 4.838370410291112e-07, 'reg_lambda': 2.325395190041232e-06, 'max_delta_step': 10}. Best is trial 15 with value: 0.6655969191270861.

Best trial: 15. Best value: 0.665597:  42%|████▏     | 21/50 [04:05<06:55, 14.33s/it]

[I 2025-12-02 04:33:13,068] Trial 21 finished with value: 0.6007702182284981 and parameters: {'max_depth': 3, 'learning_rate': 0.05214477154430392, 'n_estimators': 679, 'subsample': 0.6355519808065295, 'colsample_bytree': 0.5604951848381763, 'min_child_weight': 3, 'gamma': 4.143229152397242, 'reg_alpha': 1.6776638706252087e-08, 'reg_lambda': 1.7841048725916687e-06, 'max_delta_step': 8}. Best is trial 15 with value: 0.6655969191270861.

Best trial: 15. Best value: 0.665597:  44%|████▍     | 22/50 [04:05<04:58, 10.64s/it]

[I 2025-12-02 04:33:13,322] Trial 22 finished with value: 0.5622593068035944 and parameters: {'max_depth': 3, 'learning_rate': 0.051019171355724785, 'n_estimators': 678, 'subsample': 0.6280229639754328, 'colsample_bytree': 0.5729003036216961, 'min_child_weight': 3, 'gamma': 4.246744524222859, 'reg_alpha': 0.0005313784869159644, 'reg_lambda': 1.7349345004324416e-06, 'max_delta_step': 8}. Best is trial 15 with value: 0.6655969191270861.

Best trial: 15. Best value: 0.665597:  46%|████▌     | 23/50 [04:15<04:40, 10.38s/it]

[I 2025-12-02 04:33:23,001] Trial 23 finished with value: 0.6270860077021823 and parameters: {'max_depth': 3, 'learning_rate': 0.05117222924658681, 'n_estimators': 706, 'subsample': 0.6347367669183027, 'colsample_bytree': 0.700252180019142, 'min_child_weight': 3, 'gamma': 4.071964543682829, 'reg_alpha': 1.8055443926265952e-08, 'reg_lambda': 1.2273935149872375e-06, 'max_delta_step': 8}. Best is trial 15 with value: 0.6655969191270861.

Best trial: 15. Best value: 0.665597:  48%|████▊     | 24/50 [04:31<05:10, 11.92s/it]

[I 2025-12-02 04:33:38,894] Trial 20 finished with value: 0.5237483953786906 and parameters: {'max_depth': 4, 'learning_rate': 0.13020069601198406, 'n_estimators': 1489, 'subsample': 0.8135387250059476, 'colsample_bytree': 0.5790680093207758, 'min_child_weight': 3, 'gamma': 4.154474485979367, 'reg_alpha': 3.7579168709671474e-07, 'reg_lambda': 4.31470378878674e-06, 'max_delta_step': 10}. Best is trial 15 with value: 0.6655969191270861.

Best trial: 15. Best value: 0.665597:  50%|█████     | 25/50 [05:04<07:29, 18.00s/it]

[I 2025-12-02 04:34:12,080] Trial 25 finished with value: 0.6655969191270861 and parameters: {'max_depth': 4, 'learning_rate': 0.10803975269563083, 'n_estimators': 1348, 'subsample': 0.6012258983408896, 'colsample_bytree': 0.7062607868027173, 'min_child_weight': 2, 'gamma': 4.488712560209046, 'reg_alpha': 8.4053647845022e-06, 'reg_lambda': 1.643970309642847e-05, 'max_delta_step': 9}. Best is trial 15 with value: 0.6655969191270861.

Best trial: 15. Best value: 0.665597:  52%|█████▏    | 26/50 [05:06<05:20, 13.35s/it]

[I 2025-12-02 04:34:14,053] Trial 24 finished with value: 0.6007702182284981 and parameters: {'max_depth': 4, 'learning_rate': 0.05773865147525248, 'n_estimators': 1347, 'subsample': 0.6274862729480025, 'colsample_bytree': 0.7012542854010366, 'min_child_weight': 2, 'gamma': 4.20869879689536, 'reg_alpha': 4.059741048380855e-06, 'reg_lambda': 1.4714485929440098e-06, 'max_delta_step': 8}. Best is trial 15 with value: 0.6655969191270861.

Best trial: 15. Best value: 0.665597:  54%|█████▍    | 27/50 [05:14<04:30, 11.75s/it]

[I 2025-12-02 04:34:21,917] Trial 26 finished with value: 0.576379974326059 and parameters: {'max_depth': 7, 'learning_rate': 0.10986717404296567, 'n_estimators': 1332, 'subsample': 0.7900063658204662, 'colsample_bytree': 0.5695833596590001, 'min_child_weight': 2, 'gamma': 4.54378608485167, 'reg_alpha': 7.480902216675413e-06, 'reg_lambda': 2.457712197820728e-05, 'max_delta_step': 9}. Best is trial 15 with value: 0.6655969191270861.

Best trial: 15. Best value: 0.665597:  56%|█████▌    | 28/50 [05:21<03:47, 10.32s/it]

[I 2025-12-02 04:34:28,835] Trial 30 pruned.

Best trial: 15. Best value: 0.665597:  58%|█████▊    | 29/50 [05:31<03:32, 10.11s/it]

[I 2025-12-02 04:34:38,453] Trial 31 pruned.

Best trial: 27. Best value: 0.667522:  60%|██████    | 30/50 [05:31<02:25,  7.29s/it]

[I 2025-12-02 04:34:39,066] Trial 27 finished with value: 0.6675224646983312 and parameters: {'max_depth': 7, 'learning_rate': 0.06860152309254819, 'n_estimators': 1348, 'subsample': 0.587515832812426, 'colsample_bytree': 0.6838960473286241, 'min_child_weight': 2, 'gamma': 4.626380685886039, 'reg_alpha': 4.548488257090244e-06, 'reg_lambda': 3.342659096190946e-05, 'max_delta_step': 9}. Best is trial 27 with value: 0.6675224646983312.

Best trial: 27. Best value: 0.667522:  62%|██████▏   | 31/50 [06:08<05:03, 15.96s/it]

[I 2025-12-02 04:35:15,424] Trial 28 finished with value: 0.6007702182284981 and parameters: {'max_depth': 4, 'learning_rate': 0.07052258420632998, 'n_estimators': 1340, 'subsample': 0.6771455975942323, 'colsample_bytree': 0.698245819763615, 'min_child_weight': 2, 'gamma': 3.524858837954749, 'reg_alpha': 1.9475588673406952e-05, 'reg_lambda': 1.9987357062698772e-07, 'max_delta_step': 9}. Best is trial 27 with value: 0.6675224646983312.

Best trial: 27. Best value: 0.667522:  64%|██████▍   | 32/50 [06:10<03:32, 11.80s/it]

[I 2025-12-02 04:35:17,466] Trial 29 finished with value: 0.5783055198973043 and parameters: {'max_depth': 7, 'learning_rate': 0.2971283283509018, 'n_estimators': 1363, 'subsample': 0.6728634036790632, 'colsample_bytree': 0.8262603384860541, 'min_child_weight': 2, 'gamma': 4.576920973766021, 'reg_alpha': 3.891584886195181e-05, 'reg_lambda': 3.7142272934761215e-05, 'max_delta_step': 9}. Best is trial 27 with value: 0.6675224646983312.

Best trial: 27. Best value: 0.667522:  66%|██████▌   | 33/50 [06:24<03:31, 12.46s/it]

[I 2025-12-02 04:35:31,471] Trial 33 finished with value: 0.5622593068035944 and parameters: {'max_depth': 8, 'learning_rate': 0.0713682154785998, 'n_estimators': 1180, 'subsample': 0.6715436616930834, 'colsample_bytree': 0.8212800342883979, 'min_child_weight': 4, 'gamma': 4.575597426324962, 'reg_alpha': 0.0012051045399985247, 'reg_lambda': 1.378741170145436e-05, 'max_delta_step': 9}. Best is trial 27 with value: 0.6675224646983312.

Best trial: 27. Best value: 0.667522:  68%|██████▊   | 34/50 [06:27<02:33,  9.62s/it]

[I 2025-12-02 04:35:34,431] Trial 32 finished with value: 0.6148908857509627 and parameters: {'max_depth': 6, 'learning_rate': 0.06248260998972353, 'n_estimators': 1247, 'subsample': 0.6704229767313256, 'colsample_bytree': 0.8270078522664895, 'min_child_weight': 4, 'gamma': 3.731959789856515, 'reg_alpha': 1.5477950920365912e-05, 'reg_lambda': 3.0793951592062516e-07, 'max_delta_step': 9}. Best is trial 27 with value: 0.6675224646983312.

Best trial: 27. Best value: 0.667522:  70%|███████   | 35/50 [06:28<01:49,  7.27s/it]

[I 2025-12-02 04:35:36,210] Trial 36 pruned.

Best trial: 27. Best value: 0.667522:  72%|███████▏  | 36/50 [07:05<03:43, 15.98s/it]

[I 2025-12-02 04:36:12,557] Trial 34 finished with value: 0.527599486521181 and parameters: {'max_depth': 8, 'learning_rate': 0.06713376382364879, 'n_estimators': 1233, 'subsample': 0.6022501980524195, 'colsample_bytree': 0.7548956912746829, 'min_child_weight': 4, 'gamma': 4.562024580309472, 'reg_alpha': 0.00019275118151064358, 'reg_lambda': 7.621309334865486e-06, 'max_delta_step': 10}. Best is trial 27 with value: 0.6675224646983312.
[I 2025-12-02 04:36:12,558] Trial 35 finished with value: 0.6026957637997432 and parameters: {'max_depth': 8, 'learning_rate': 0.06957296163569253, 'n_estimators': 1202, 'subsample': 0.553168080660656, 'colsample_bytree': 0.7338846718049512, 'min_child_weight': 4, 'gamma': 4.5753809808072, 'reg_alpha': 1.151760296540726e-06, 'reg_lambda': 9.119225203510644e-06, 'max_delta_step': 10}. Best is trial 27 with value: 0.6675224646983312.

Best trial: 27. Best value: 0.667522:  76%|███████▌  | 38/50 [07:05<01:45,  8.78s/it]

[I 2025-12-02 04:36:13,302] Trial 38 finished with value: 0.6553273427471117 and parameters: {'max_depth': 8, 'learning_rate': 0.16775530690303175, 'n_estimators': 802, 'subsample': 0.6013370148369082, 'colsample_bytree': 0.5368173874544985, 'min_child_weight': 3, 'gamma': 4.663106714147914, 'reg_alpha': 0.00014783238146392748, 'reg_lambda': 8.21663940829889e-06, 'max_delta_step': 7}. Best is trial 27 with value: 0.6675224646983312.

Best trial: 27. Best value: 0.667522:  78%|███████▊  | 39/50 [07:06<01:14,  6.78s/it]

[I 2025-12-02 04:36:13,997] Trial 37 finished with value: 0.6129653401797176 and parameters: {'max_depth': 8, 'learning_rate': 0.039443051226166835, 'n_estimators': 798, 'subsample': 0.5511778125142094, 'colsample_bytree': 0.5377519781329556, 'min_child_weight': 3, 'gamma': 4.600761789269827, 'reg_alpha': 0.0001334495951832439, 'reg_lambda': 0.0001464182385762894, 'max_delta_step': 10}. Best is trial 27 with value: 0.6675224646983312.

Best trial: 27. Best value: 0.667522:  80%|████████  | 40/50 [07:11<01:02,  6.26s/it]

[I 2025-12-02 04:36:18,805] Trial 40 pruned.

Best trial: 27. Best value: 0.667522:  82%|████████▏ | 41/50 [07:11<00:41,  4.66s/it]

[I 2025-12-02 04:36:19,179] Trial 42 pruned.

Best trial: 27. Best value: 0.667522:  84%|████████▍ | 42/50 [07:13<00:31,  3.92s/it]

[I 2025-12-02 04:36:21,208] Trial 39 pruned.

Best trial: 27. Best value: 0.667522:  86%|████████▌ | 43/50 [07:20<00:32,  4.69s/it]

[I 2025-12-02 04:36:27,800] Trial 44 pruned.

Best trial: 27. Best value: 0.667522:  88%|████████▊ | 44/50 [07:28<00:34,  5.68s/it]

[I 2025-12-02 04:36:35,906] Trial 46 pruned.

Best trial: 27. Best value: 0.667522:  90%|█████████ | 45/50 [07:43<00:42,  8.45s/it]

[I 2025-12-02 04:36:51,056] Trial 41 finished with value: 0.5725288831835686 and parameters: {'max_depth': 8, 'learning_rate': 0.2016825073709787, 'n_estimators': 800, 'subsample': 0.7170960178238546, 'colsample_bytree': 0.5383529911393892, 'min_child_weight': 3, 'gamma': 3.142200722217003, 'reg_alpha': 0.00015880577963268882, 'reg_lambda': 0.00021232958965468769, 'max_delta_step': 6}. Best is trial 27 with value: 0.6675224646983312.

Best trial: 27. Best value: 0.667522:  92%|█████████▏| 46/50 [07:53<00:35,  8.87s/it]

[I 2025-12-02 04:37:00,920] Trial 43 finished with value: 0.5641848523748395 and parameters: {'max_depth': 7, 'learning_rate': 0.213623213001381, 'n_estimators': 941, 'subsample': 0.7292769288831332, 'colsample_bytree': 0.5120083580648195, 'min_child_weight': 5, 'gamma': 2.827032845031458, 'reg_alpha': 0.001593580947245273, 'reg_lambda': 6.121320591526943e-08, 'max_delta_step': 5}. Best is trial 27 with value: 0.6675224646983312.

Best trial: 27. Best value: 0.667522:  94%|█████████▍| 47/50 [08:00<00:24,  8.23s/it]

[I 2025-12-02 04:37:07,650] Trial 45 finished with value: 0.6514762516046213 and parameters: {'max_depth': 6, 'learning_rate': 0.10970909264772197, 'n_estimators': 932, 'subsample': 0.5711505092227042, 'colsample_bytree': 0.6709014406823196, 'min_child_weight': 2, 'gamma': 2.6987731411128553, 'reg_alpha': 3.4716517555210686e-06, 'reg_lambda': 6.288753121563192e-07, 'max_delta_step': 5}. Best is trial 27 with value: 0.6675224646983312.

Best trial: 27. Best value: 0.667522:  96%|█████████▌| 48/50 [08:01<00:12,  6.25s/it]

[I 2025-12-02 04:37:09,198] Trial 47 finished with value: 0.5256739409499358 and parameters: {'max_depth': 7, 'learning_rate': 0.20958989217480578, 'n_estimators': 751, 'subsample': 0.6504615719334566, 'colsample_bytree': 0.6257507587961408, 'min_child_weight': 5, 'gamma': 2.759343044904092, 'reg_alpha': 9.812686814973973e-05, 'reg_lambda': 5.902334416089772e-07, 'max_delta_step': 8}. Best is trial 27 with value: 0.6675224646983312.

Best trial: 27. Best value: 0.667522:  98%|█████████▊| 49/50 [08:07<00:05,  5.99s/it]

[I 2025-12-02 04:37:14,598] Trial 48 finished with value: 0.5256739409499358 and parameters: {'max_depth': 7, 'learning_rate': 0.09203407671668805, 'n_estimators': 592, 'subsample': 0.6533689325880381, 'colsample_bytree': 0.7857613669975356, 'min_child_weight': 5, 'gamma': 2.586423464894348, 'reg_alpha': 2.9533938130524126e-06, 'reg_lambda': 4.3926660224407164e-07, 'max_delta_step': 5}. Best is trial 27 with value: 0.6675224646983312.

Best trial: 27. Best value: 0.667522: 100%|██████████| 50/50 [08:29<00:00, 10.20s/it]

[I 2025-12-02 04:37:37,301] Trial 49 finished with value: 0.6026957637997432 and parameters: {'max_depth': 9, 'learning_rate': 0.01549414588838844, 'n_estimators': 725, 'subsample': 0.6479277077797279, 'colsample_bytree': 0.6395385562368499, 'min_child_weight': 1, 'gamma': 4.795809487627039, 'reg_alpha': 0.033804686221351035, 'reg_lambda': 6.02844643559418e-07, 'max_delta_step': 8}. Best is trial 27 with value: 0.6675224646983312.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 04:37:42,568] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.629012:   2%|▏         | 1/50 [00:21<17:40, 21.65s/it]

[I 2025-12-02 04:38:04,212] Trial 3 finished with value: 0.6290115532734275 and parameters: {'max_depth': 4, 'learning_rate': 0.11601203654670332, 'n_estimators': 402, 'subsample': 0.9762561955662181, 'colsample_bytree': 0.7391586634257565, 'min_child_weight': 3, 'gamma': 0.7908879669851893, 'reg_alpha': 1.2550437425844862e-07, 'reg_lambda': 0.00016054030314600247, 'max_delta_step': 6}. Best is trial 3 with value: 0.6290115532734275.

Best trial: 3. Best value: 0.629012:   4%|▍         | 2/50 [00:27<09:51, 12.32s/it]

[I 2025-12-02 04:38:09,994] Trial 0 finished with value: 0.6026957637997432 and parameters: {'max_depth': 4, 'learning_rate': 0.19108633930798596, 'n_estimators': 577, 'subsample': 0.8040950473723008, 'colsample_bytree': 0.8619859818300514, 'min_child_weight': 5, 'gamma': 0.32221686080155076, 'reg_alpha': 0.33014946999246786, 'reg_lambda': 3.060405864442874e-07, 'max_delta_step': 1}. Best is trial 3 with value: 0.6290115532734275.

Best trial: 3. Best value: 0.629012:   6%|▌         | 3/50 [00:35<07:58, 10.17s/it]

[I 2025-12-02 04:38:17,617] Trial 2 finished with value: 0.6007702182284981 and parameters: {'max_depth': 7, 'learning_rate': 0.1187089767247425, 'n_estimators': 761, 'subsample': 0.5502139375126602, 'colsample_bytree': 0.5432653027135166, 'min_child_weight': 3, 'gamma': 1.2959664407815241, 'reg_alpha': 1.1192620898118496e-08, 'reg_lambda': 6.154671647689457e-07, 'max_delta_step': 2}. Best is trial 3 with value: 0.6290115532734275.

Best trial: 3. Best value: 0.629012:   8%|▊         | 4/50 [00:40<06:16,  8.19s/it]

[I 2025-12-02 04:38:22,774] Trial 1 finished with value: 0.6206675224646983 and parameters: {'max_depth': 5, 'learning_rate': 0.015835057345116185, 'n_estimators': 854, 'subsample': 0.8887068408157368, 'colsample_bytree': 0.6340267880228538, 'min_child_weight': 8, 'gamma': 1.102999521223773, 'reg_alpha': 2.0670772862508482e-05, 'reg_lambda': 1.3733424562628739e-05, 'max_delta_step': 1}. Best is trial 3 with value: 0.6290115532734275.

Best trial: 3. Best value: 0.629012:  10%|█         | 5/50 [01:09<11:47, 15.73s/it]

[I 2025-12-02 04:38:51,860] Trial 6 finished with value: 0.6084724005134787 and parameters: {'max_depth': 8, 'learning_rate': 0.042995795956748746, 'n_estimators': 739, 'subsample': 0.9904313849551458, 'colsample_bytree': 0.6055780576168803, 'min_child_weight': 8, 'gamma': 1.4087971113568858, 'reg_alpha': 0.001399517514084523, 'reg_lambda': 0.5731952528814567, 'max_delta_step': 4}. Best is trial 3 with value: 0.6290115532734275.

Best trial: 4. Best value: 0.693838:  12%|█▏        | 6/50 [01:20<10:26, 14.25s/it]

[I 2025-12-02 04:39:03,241] Trial 4 finished with value: 0.6938382541720154 and parameters: {'max_depth': 9, 'learning_rate': 0.14288998609917059, 'n_estimators': 1236, 'subsample': 0.6556470633536776, 'colsample_bytree': 0.5490078421883575, 'min_child_weight': 2, 'gamma': 4.979677483208662, 'reg_alpha': 3.873643182343827e-08, 'reg_lambda': 0.006079380960612393, 'max_delta_step': 8}. Best is trial 4 with value: 0.6938382541720154.

Best trial: 5. Best value: 0.695764:  14%|█▍        | 7/50 [01:26<08:07, 11.34s/it]

[I 2025-12-02 04:39:08,599] Trial 5 finished with value: 0.6957637997432606 and parameters: {'max_depth': 7, 'learning_rate': 0.1758321421188279, 'n_estimators': 1185, 'subsample': 0.8355465761166734, 'colsample_bytree': 0.5181582360988615, 'min_child_weight': 2, 'gamma': 1.164581410275396, 'reg_alpha': 1.0653879499835304, 'reg_lambda': 0.016327401586574843, 'max_delta_step': 0}. Best is trial 5 with value: 0.6957637997432606.

Best trial: 5. Best value: 0.695764:  16%|█▌        | 8/50 [01:28<05:52,  8.39s/it]

[I 2025-12-02 04:39:10,647] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.0238878634135788, 'n_estimators': 1069, 'subsample': 0.5025307717945695, 'colsample_bytree': 0.8055549403397468, 'min_child_weight': 8, 'gamma': 2.8835861220113386, 'reg_alpha': 0.001410449552529873, 'reg_lambda': 2.750514589629072e-08, 'max_delta_step': 2}. Best is trial 5 with value: 0.6957637997432606.

Best trial: 5. Best value: 0.695764:  18%|█▊        | 9/50 [01:39<06:19,  9.26s/it]

[I 2025-12-02 04:39:21,836] Trial 8 finished with value: 0.5353016688061617 and parameters: {'max_depth': 4, 'learning_rate': 0.02170909053485671, 'n_estimators': 670, 'subsample': 0.7504044279502435, 'colsample_bytree': 0.8366790437932571, 'min_child_weight': 9, 'gamma': 3.835682783348778, 'reg_alpha': 0.30111981487945744, 'reg_lambda': 0.00160446703943167, 'max_delta_step': 9}. Best is trial 5 with value: 0.6957637997432606.

Best trial: 5. Best value: 0.695764:  20%|██        | 10/50 [01:41<04:40,  7.02s/it]

[I 2025-12-02 04:39:23,849] Trial 9 finished with value: 0.6572528883183568 and parameters: {'max_depth': 7, 'learning_rate': 0.045044690854624876, 'n_estimators': 366, 'subsample': 0.7817472934208292, 'colsample_bytree': 0.7455304143473706, 'min_child_weight': 4, 'gamma': 3.8282034012204007, 'reg_alpha': 2.669808747270128e-05, 'reg_lambda': 0.23987031489517782, 'max_delta_step': 10}. Best is trial 5 with value: 0.6957637997432606.

Best trial: 5. Best value: 0.695764:  22%|██▏       | 11/50 [01:41<03:15,  5.01s/it]

[I 2025-12-02 04:39:24,311] Trial 11 pruned.

Best trial: 5. Best value: 0.695764:  24%|██▍       | 12/50 [01:42<02:26,  3.85s/it]

[I 2025-12-02 04:39:25,501] Trial 12 pruned.

Best trial: 5. Best value: 0.695764:  26%|██▌       | 13/50 [01:56<04:10,  6.76s/it]

[I 2025-12-02 04:39:38,966] Trial 10 finished with value: 0.6431322207958922 and parameters: {'max_depth': 9, 'learning_rate': 0.010275462185605563, 'n_estimators': 541, 'subsample': 0.559871902857958, 'colsample_bytree': 0.6763207060293822, 'min_child_weight': 4, 'gamma': 0.5344906415797607, 'reg_alpha': 6.722131166757199e-06, 'reg_lambda': 0.03752683390938914, 'max_delta_step': 2}. Best is trial 5 with value: 0.6957637997432606.

Best trial: 5. Best value: 0.695764:  28%|██▊       | 14/50 [02:05<04:33,  7.60s/it]

[I 2025-12-02 04:39:48,493] Trial 16 pruned.

Best trial: 5. Best value: 0.695764:  30%|███       | 15/50 [02:08<03:35,  6.15s/it]

[I 2025-12-02 04:39:51,289] Trial 13 pruned.

Best trial: 5. Best value: 0.695764:  32%|███▏      | 16/50 [02:18<04:04,  7.19s/it]

[I 2025-12-02 04:40:00,894] Trial 18 pruned.

Best trial: 5. Best value: 0.695764:  34%|███▍      | 17/50 [02:39<06:15, 11.38s/it]

[I 2025-12-02 04:40:22,010] Trial 14 finished with value: 0.6797175866495507 and parameters: {'max_depth': 10, 'learning_rate': 0.2540838224320846, 'n_estimators': 1449, 'subsample': 0.6388960087823222, 'colsample_bytree': 0.5050081421982815, 'min_child_weight': 1, 'gamma': 2.085534955925516, 'reg_alpha': 1.049817661864212e-06, 'reg_lambda': 0.005386324943775567, 'max_delta_step': 7}. Best is trial 5 with value: 0.6957637997432606.

Best trial: 5. Best value: 0.695764:  36%|███▌      | 18/50 [02:56<06:56, 13.01s/it]

[I 2025-12-02 04:40:38,815] Trial 15 finished with value: 0.6450577663671373 and parameters: {'max_depth': 10, 'learning_rate': 0.29472814362659394, 'n_estimators': 1437, 'subsample': 0.6703476804887453, 'colsample_bytree': 0.6391625475319445, 'min_child_weight': 1, 'gamma': 2.2316016392912137, 'reg_alpha': 6.749164839845514, 'reg_lambda': 9.829679838336922, 'max_delta_step': 7}. Best is trial 5 with value: 0.6957637997432606.

Best trial: 5. Best value: 0.695764:  38%|███▊      | 19/50 [03:07<06:29, 12.57s/it]

[I 2025-12-02 04:40:50,350] Trial 19 finished with value: 0.6694480102695763 and parameters: {'max_depth': 6, 'learning_rate': 0.15505034521652195, 'n_estimators': 1235, 'subsample': 0.8570745200834138, 'colsample_bytree': 0.6486637054360769, 'min_child_weight': 6, 'gamma': 4.814392880078134, 'reg_alpha': 0.009368720497269169, 'reg_lambda': 0.005365556123464163, 'max_delta_step': 6}. Best is trial 5 with value: 0.6957637997432606.

Best trial: 17. Best value: 0.720154:  40%|████      | 20/50 [03:16<05:42, 11.43s/it]

[I 2025-12-02 04:40:59,142] Trial 17 finished with value: 0.7201540436456997 and parameters: {'max_depth': 6, 'learning_rate': 0.22343820736203274, 'n_estimators': 1340, 'subsample': 0.6970727325295512, 'colsample_bytree': 0.9327256065254579, 'min_child_weight': 1, 'gamma': 2.1355661990579824, 'reg_alpha': 0.022172688886613903, 'reg_lambda': 0.0001784857700838525, 'max_delta_step': 8}. Best is trial 17 with value: 0.7201540436456997.

Best trial: 17. Best value: 0.720154:  42%|████▏     | 21/50 [03:32<06:07, 12.67s/it]

[I 2025-12-02 04:41:14,688] Trial 20 finished with value: 0.5924261874197689 and parameters: {'max_depth': 6, 'learning_rate': 0.06294774803209222, 'n_estimators': 1226, 'subsample': 0.8743274016852771, 'colsample_bytree': 0.6735196894538241, 'min_child_weight': 6, 'gamma': 4.212213098772513, 'reg_alpha': 0.016901014084594667, 'reg_lambda': 2.809979549305426e-05, 'max_delta_step': 10}. Best is trial 17 with value: 0.7201540436456997.

Best trial: 17. Best value: 0.720154:  44%|████▍     | 22/50 [03:52<07:00, 15.01s/it]

[I 2025-12-02 04:41:35,153] Trial 21 finished with value: 0.5924261874197689 and parameters: {'max_depth': 6, 'learning_rate': 0.061083267127557135, 'n_estimators': 1234, 'subsample': 0.8808876657452891, 'colsample_bytree': 0.6969272024589535, 'min_child_weight': 5, 'gamma': 4.998221213718282, 'reg_alpha': 0.023635110565895512, 'reg_lambda': 1.9739465586896204e-05, 'max_delta_step': 5}. Best is trial 17 with value: 0.7201540436456997.

Best trial: 17. Best value: 0.720154:  46%|████▌     | 23/50 [04:04<06:16, 13.94s/it]

[I 2025-12-02 04:41:46,594] Trial 22 finished with value: 0.6431322207958922 and parameters: {'max_depth': 3, 'learning_rate': 0.06488872369538486, 'n_estimators': 1185, 'subsample': 0.916301797664807, 'colsample_bytree': 0.5672607241346919, 'min_child_weight': 3, 'gamma': 4.205536946682729, 'reg_alpha': 0.011661168634634737, 'reg_lambda': 0.0005769647925453136, 'max_delta_step': 10}. Best is trial 17 with value: 0.7201540436456997.

Best trial: 17. Best value: 0.720154:  48%|████▊     | 24/50 [04:05<04:24, 10.18s/it]

[I 2025-12-02 04:41:48,006] Trial 23 finished with value: 0.6290115532734275 and parameters: {'max_depth': 3, 'learning_rate': 0.08128540744288566, 'n_estimators': 1088, 'subsample': 0.9185021643164836, 'colsample_bytree': 0.9603990029914022, 'min_child_weight': 6, 'gamma': 1.706254952606498, 'reg_alpha': 0.023427354849335166, 'reg_lambda': 1.6093896129792103e-05, 'max_delta_step': 10}. Best is trial 17 with value: 0.7201540436456997.

Best trial: 17. Best value: 0.720154:  50%|█████     | 25/50 [04:12<03:51,  9.27s/it]

[I 2025-12-02 04:41:55,142] Trial 26 pruned.

Best trial: 17. Best value: 0.720154:  52%|█████▏    | 26/50 [04:27<04:26, 11.09s/it]

[I 2025-12-02 04:42:10,502] Trial 24 finished with value: 0.7201540436456997 and parameters: {'max_depth': 5, 'learning_rate': 0.1339969285739618, 'n_estimators': 1088, 'subsample': 0.9293022638688403, 'colsample_bytree': 0.9642412539042388, 'min_child_weight': 2, 'gamma': 1.853320106725528, 'reg_alpha': 0.03396423248890321, 'reg_lambda': 0.0007121362144008978, 'max_delta_step': 9}. Best is trial 17 with value: 0.7201540436456997.

Best trial: 17. Best value: 0.720154:  54%|█████▍    | 27/50 [04:32<03:26,  9.00s/it]

[I 2025-12-02 04:42:14,614] Trial 28 pruned.

Best trial: 17. Best value: 0.720154:  56%|█████▌    | 28/50 [04:41<03:19,  9.08s/it]

[I 2025-12-02 04:42:23,877] Trial 25 finished with value: 0.6938382541720154 and parameters: {'max_depth': 3, 'learning_rate': 0.1799238304727282, 'n_estimators': 1091, 'subsample': 0.7255886394142627, 'colsample_bytree': 0.981765383271787, 'min_child_weight': 2, 'gamma': 1.772427750582838, 'reg_alpha': 0.0006427633146870623, 'reg_lambda': 0.0010744065866989325, 'max_delta_step': 9}. Best is trial 17 with value: 0.7201540436456997.

Best trial: 17. Best value: 0.720154:  58%|█████▊    | 29/50 [04:55<03:44, 10.70s/it]

[I 2025-12-02 04:42:38,347] Trial 31 pruned.

Best trial: 17. Best value: 0.720154:  60%|██████    | 30/50 [05:06<03:33, 10.66s/it]

[I 2025-12-02 04:42:48,918] Trial 32 pruned.

Best trial: 17. Best value: 0.720154:  62%|██████▏   | 31/50 [05:07<02:30,  7.93s/it]

[I 2025-12-02 04:42:50,471] Trial 27 finished with value: 0.641206675224647 and parameters: {'max_depth': 7, 'learning_rate': 0.13217577509390724, 'n_estimators': 1325, 'subsample': 0.7181898404323092, 'colsample_bytree': 0.902903118303018, 'min_child_weight': 2, 'gamma': 0.04040703347514274, 'reg_alpha': 0.9922961777407956, 'reg_lambda': 0.06548970586362263, 'max_delta_step': 8}. Best is trial 17 with value: 0.7201540436456997.

Best trial: 17. Best value: 0.720154:  64%|██████▍   | 32/50 [05:13<02:10,  7.26s/it]

[I 2025-12-02 04:42:56,190] Trial 30 finished with value: 0.6431322207958922 and parameters: {'max_depth': 5, 'learning_rate': 0.09836201044208749, 'n_estimators': 878, 'subsample': 0.9606960760523057, 'colsample_bytree': 0.9132513527822033, 'min_child_weight': 4, 'gamma': 1.812564113248418, 'reg_alpha': 0.21829848263446988, 'reg_lambda': 2.4298491142486182e-06, 'max_delta_step': 9}. Best is trial 17 with value: 0.7201540436456997.

Best trial: 17. Best value: 0.720154:  66%|██████▌   | 33/50 [05:28<02:44,  9.66s/it]

[I 2025-12-02 04:43:11,422] Trial 29 finished with value: 0.6938382541720154 and parameters: {'max_depth': 5, 'learning_rate': 0.11721692795801579, 'n_estimators': 1353, 'subsample': 0.9281147064116124, 'colsample_bytree': 0.9003212665430114, 'min_child_weight': 2, 'gamma': 0.031437139710926765, 'reg_alpha': 0.0010929436513296604, 'reg_lambda': 2.858153242406073e-06, 'max_delta_step': 9}. Best is trial 17 with value: 0.7201540436456997.

Best trial: 17. Best value: 0.720154:  68%|██████▊   | 34/50 [06:00<04:19, 16.19s/it]

[I 2025-12-02 04:43:42,877] Trial 33 finished with value: 0.6290115532734275 and parameters: {'max_depth': 7, 'learning_rate': 0.19575749937105835, 'n_estimators': 1342, 'subsample': 0.7744428590187135, 'colsample_bytree': 0.7915035540976078, 'min_child_weight': 5, 'gamma': 0.7218762744854446, 'reg_alpha': 0.862649501995876, 'reg_lambda': 0.05104051915203888, 'max_delta_step': 3}. Best is trial 17 with value: 0.7201540436456997.

Best trial: 17. Best value: 0.720154:  70%|███████   | 35/50 [06:06<03:17, 13.13s/it]

[I 2025-12-02 04:43:48,870] Trial 34 finished with value: 0.6816431322207959 and parameters: {'max_depth': 9, 'learning_rate': 0.15561397221035037, 'n_estimators': 1152, 'subsample': 0.7725330850391556, 'colsample_bytree': 0.788095698857688, 'min_child_weight': 1, 'gamma': 1.8912764501353752, 'reg_alpha': 0.06091491634994247, 'reg_lambda': 0.008466776475591258, 'max_delta_step': 6}. Best is trial 17 with value: 0.7201540436456997.

Best trial: 17. Best value: 0.720154:  72%|███████▏  | 36/50 [06:07<02:15,  9.66s/it]

[I 2025-12-02 04:43:50,399] Trial 37 pruned.

Best trial: 17. Best value: 0.720154:  74%|███████▍  | 37/50 [06:13<01:49,  8.39s/it]

[I 2025-12-02 04:43:55,838] Trial 38 pruned.

Best trial: 36. Best value: 0.732349:  76%|███████▌  | 38/50 [06:19<01:31,  7.63s/it]

[I 2025-12-02 04:44:01,699] Trial 36 finished with value: 0.7323491655969192 and parameters: {'max_depth': 9, 'learning_rate': 0.15131751768913107, 'n_estimators': 1128, 'subsample': 0.7691574047247947, 'colsample_bytree': 0.7857386930376407, 'min_child_weight': 1, 'gamma': 0.8785596017628619, 'reg_alpha': 0.004812126780703971, 'reg_lambda': 0.0034622023879759003, 'max_delta_step': 6}. Best is trial 36 with value: 0.7323491655969192.

Best trial: 36. Best value: 0.732349:  78%|███████▊  | 39/50 [06:23<01:12,  6.55s/it]

[I 2025-12-02 04:44:05,716] Trial 35 finished with value: 0.7079589216944802 and parameters: {'max_depth': 8, 'learning_rate': 0.14939065468661983, 'n_estimators': 1345, 'subsample': 0.7611629663693303, 'colsample_bytree': 0.7803680899056701, 'min_child_weight': 1, 'gamma': 3.3300245585825023, 'reg_alpha': 0.003713492460670202, 'reg_lambda': 0.011656328720744898, 'max_delta_step': 6}. Best is trial 36 with value: 0.7323491655969192.

Best trial: 36. Best value: 0.732349:  80%|████████  | 40/50 [06:56<02:26, 14.61s/it]

[I 2025-12-02 04:44:39,137] Trial 39 finished with value: 0.7201540436456997 and parameters: {'max_depth': 4, 'learning_rate': 0.047702212083930814, 'n_estimators': 1007, 'subsample': 0.8503499192933038, 'colsample_bytree': 0.603313694388461, 'min_child_weight': 1, 'gamma': 1.5046082707372004, 'reg_alpha': 1.7273532657848897e-06, 'reg_lambda': 0.0024742509728610178, 'max_delta_step': 1}. Best is trial 36 with value: 0.7323491655969192.

Best trial: 36. Best value: 0.732349:  82%|████████▏ | 41/50 [07:03<01:51, 12.37s/it]

[I 2025-12-02 04:44:46,284] Trial 40 finished with value: 0.7323491655969192 and parameters: {'max_depth': 8, 'learning_rate': 0.045809747617387375, 'n_estimators': 989, 'subsample': 0.8362669711371785, 'colsample_bytree': 0.8640029698623616, 'min_child_weight': 1, 'gamma': 1.5046969673202386, 'reg_alpha': 0.000150280127182094, 'reg_lambda': 0.00281047050301681, 'max_delta_step': 7}. Best is trial 36 with value: 0.7323491655969192.

Best trial: 36. Best value: 0.732349:  84%|████████▍ | 42/50 [07:04<01:12,  9.03s/it]

[I 2025-12-02 04:44:47,517] Trial 42 finished with value: 0.7201540436456997 and parameters: {'max_depth': 8, 'learning_rate': 0.04721787271310568, 'n_estimators': 813, 'subsample': 0.7519835939626016, 'colsample_bytree': 0.8566944224085846, 'min_child_weight': 1, 'gamma': 3.440797432755667, 'reg_alpha': 0.000175653750802002, 'reg_lambda': 0.001732925343264928, 'max_delta_step': 6}. Best is trial 36 with value: 0.7323491655969192.

Best trial: 36. Best value: 0.732349:  86%|████████▌ | 43/50 [07:10<00:54,  7.86s/it]

[I 2025-12-02 04:44:52,636] Trial 41 finished with value: 0.7079589216944802 and parameters: {'max_depth': 8, 'learning_rate': 0.03328630041932417, 'n_estimators': 768, 'subsample': 0.8240001240809292, 'colsample_bytree': 0.8444422781176097, 'min_child_weight': 1, 'gamma': 0.8199005828069015, 'reg_alpha': 0.00018652671084356455, 'reg_lambda': 1.4934396908537089, 'max_delta_step': 6}. Best is trial 36 with value: 0.7323491655969192.

Best trial: 36. Best value: 0.732349:  88%|████████▊ | 44/50 [07:14<00:41,  6.91s/it]

[I 2025-12-02 04:44:57,340] Trial 45 pruned.

Best trial: 36. Best value: 0.732349:  90%|█████████ | 45/50 [07:42<01:05, 13.04s/it]

[I 2025-12-02 04:45:24,696] Trial 43 finished with value: 0.7323491655969192 and parameters: {'max_depth': 4, 'learning_rate': 0.046892930810280835, 'n_estimators': 824, 'subsample': 0.8529088468332706, 'colsample_bytree': 0.8679164225520203, 'min_child_weight': 1, 'gamma': 2.48619578798071, 'reg_alpha': 0.0002613934931302784, 'reg_lambda': 0.0025980959586109835, 'max_delta_step': 3}. Best is trial 36 with value: 0.7323491655969192.

Best trial: 36. Best value: 0.732349:  92%|█████████▏| 46/50 [07:50<00:46, 11.64s/it]

[I 2025-12-02 04:45:33,057] Trial 44 finished with value: 0.7323491655969192 and parameters: {'max_depth': 4, 'learning_rate': 0.03384870403369808, 'n_estimators': 798, 'subsample': 0.8475037806957936, 'colsample_bytree': 0.8643719467183081, 'min_child_weight': 1, 'gamma': 1.4478401186550807, 'reg_alpha': 2.364410624001666e-06, 'reg_lambda': 0.001913451962058231, 'max_delta_step': 7}. Best is trial 36 with value: 0.7323491655969192.

Best trial: 36. Best value: 0.732349:  94%|█████████▍| 47/50 [07:56<00:30, 10.09s/it]

[I 2025-12-02 04:45:39,534] Trial 46 finished with value: 0.6816431322207959 and parameters: {'max_depth': 4, 'learning_rate': 0.02792437609757691, 'n_estimators': 994, 'subsample': 0.8529918025369755, 'colsample_bytree': 0.7246433399450817, 'min_child_weight': 2, 'gamma': 1.5546931357963034, 'reg_alpha': 1.182647050144899e-06, 'reg_lambda': 0.0022562698999644935, 'max_delta_step': 7}. Best is trial 36 with value: 0.7323491655969192.

Best trial: 36. Best value: 0.732349:  96%|█████████▌| 48/50 [07:59<00:15,  7.85s/it]

[I 2025-12-02 04:45:42,156] Trial 47 finished with value: 0.6816431322207959 and parameters: {'max_depth': 4, 'learning_rate': 0.03649842947118049, 'n_estimators': 940, 'subsample': 0.7859090424178644, 'colsample_bytree': 0.8712692904445559, 'min_child_weight': 2, 'gamma': 2.4872347742296896, 'reg_alpha': 1.046353992325733e-06, 'reg_lambda': 0.0003973367637573213, 'max_delta_step': 7}. Best is trial 36 with value: 0.7323491655969192.

Best trial: 36. Best value: 0.732349:  98%|█████████▊| 49/50 [08:00<00:05,  5.78s/it]

[I 2025-12-02 04:45:43,119] Trial 48 finished with value: 0.7201540436456997 and parameters: {'max_depth': 6, 'learning_rate': 0.03190715086063129, 'n_estimators': 229, 'subsample': 0.7920134621478652, 'colsample_bytree': 0.8726758913979634, 'min_child_weight': 2, 'gamma': 2.7155597757580816, 'reg_alpha': 7.277984974273018e-05, 'reg_lambda': 0.0005732772261780801, 'max_delta_step': 3}. Best is trial 36 with value: 0.7323491655969192.

Best trial: 36. Best value: 0.732349: 100%|██████████| 50/50 [08:04<00:00,  9.69s/it]

[I 2025-12-02 04:45:46,865] Trial 49 finished with value: 0.6694480102695763 and parameters: {'max_depth': 3, 'learning_rate': 0.03634874520637641, 'n_estimators': 220, 'subsample': 0.8046098196076269, 'colsample_bytree': 0.8727627967920539, 'min_child_weight': 3, 'gamma': 2.5516080023881984, 'reg_alpha': 4.303912532554963e-05, 'reg_lambda': 0.0034485526377463173, 'max_delta_step': 3}. Best is trial 36 with value: 0.7323491655969192.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 04:45:51,710] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.704605:   2%|▏         | 1/50 [00:15<12:35, 15.42s/it]

[I 2025-12-02 04:46:07,121] Trial 2 finished with value: 0.7046052631578947 and parameters: {'max_depth': 3, 'learning_rate': 0.1285160893049804, 'n_estimators': 278, 'subsample': 0.9473235177722819, 'colsample_bytree': 0.5349996867978167, 'min_child_weight': 9, 'gamma': 4.300192056872715, 'reg_alpha': 1.2154686426104851e-05, 'reg_lambda': 0.0015465720722895656, 'max_delta_step': 6}. Best is trial 2 with value: 0.7046052631578947.

Best trial: 2. Best value: 0.704605:   4%|▍         | 2/50 [00:25<10:00, 12.52s/it]

[I 2025-12-02 04:46:17,607] Trial 1 finished with value: 0.35131578947368425 and parameters: {'max_depth': 9, 'learning_rate': 0.039316929776289734, 'n_estimators': 540, 'subsample': 0.6331084905351098, 'colsample_bytree': 0.8305997985587887, 'min_child_weight': 8, 'gamma': 3.9757904462005205, 'reg_alpha': 1.4972716854179495, 'reg_lambda': 0.00033767607299387616, 'max_delta_step': 9}. Best is trial 2 with value: 0.7046052631578947.

Best trial: 2. Best value: 0.704605:   6%|▌         | 3/50 [00:43<11:33, 14.75s/it]

[I 2025-12-02 04:46:35,017] Trial 0 finished with value: 0.3375 and parameters: {'max_depth': 6, 'learning_rate': 0.016947140981858316, 'n_estimators': 1009, 'subsample': 0.6185038467710926, 'colsample_bytree': 0.618443483097729, 'min_child_weight': 8, 'gamma': 2.591121873849552, 'reg_alpha': 1.610370133103925e-06, 'reg_lambda': 0.677154423779128, 'max_delta_step': 10}. Best is trial 2 with value: 0.7046052631578947.

Best trial: 4. Best value: 0.717105:   8%|▊         | 4/50 [00:59<11:46, 15.36s/it]

[I 2025-12-02 04:46:51,308] Trial 4 finished with value: 0.7171052631578947 and parameters: {'max_depth': 10, 'learning_rate': 0.011358914302037521, 'n_estimators': 931, 'subsample': 0.9190640447315315, 'colsample_bytree': 0.9476238891662565, 'min_child_weight': 9, 'gamma': 2.8259528409245127, 'reg_alpha': 0.6061252041490222, 'reg_lambda': 1.3414815954217931e-08, 'max_delta_step': 8}. Best is trial 4 with value: 0.7171052631578947.

Best trial: 4. Best value: 0.717105:  10%|█         | 5/50 [01:04<08:42, 11.60s/it]

[I 2025-12-02 04:46:56,245] Trial 3 finished with value: 0.5730263157894737 and parameters: {'max_depth': 3, 'learning_rate': 0.05351599470196301, 'n_estimators': 1429, 'subsample': 0.9420223446006042, 'colsample_bytree': 0.9178966518715738, 'min_child_weight': 7, 'gamma': 0.6312613893192465, 'reg_alpha': 9.143077364919536e-07, 'reg_lambda': 1.5263510932084487e-07, 'max_delta_step': 4}. Best is trial 4 with value: 0.7171052631578947.

Best trial: 4. Best value: 0.717105:  12%|█▏        | 6/50 [01:04<05:43,  7.80s/it]

[I 2025-12-02 04:46:56,652] Trial 5 finished with value: 0.6105263157894737 and parameters: {'max_depth': 9, 'learning_rate': 0.05509734648644628, 'n_estimators': 796, 'subsample': 0.667903625437956, 'colsample_bytree': 0.9226376935795522, 'min_child_weight': 4, 'gamma': 3.2360230213474814, 'reg_alpha': 1.4538464475176498e-05, 'reg_lambda': 0.00032487598432582134, 'max_delta_step': 4}. Best is trial 4 with value: 0.7171052631578947.

Best trial: 4. Best value: 0.717105:  14%|█▍        | 7/50 [01:20<07:18, 10.20s/it]

[I 2025-12-02 04:47:11,822] Trial 6 finished with value: 0.05 and parameters: {'max_depth': 4, 'learning_rate': 0.1860629413219777, 'n_estimators': 870, 'subsample': 0.6663291643842215, 'colsample_bytree': 0.7403641081808673, 'min_child_weight': 10, 'gamma': 2.6858122022829978, 'reg_alpha': 0.6309589757470103, 'reg_lambda': 2.4475165179325476e-08, 'max_delta_step': 5}. Best is trial 4 with value: 0.7171052631578947.

Best trial: 4. Best value: 0.717105:  16%|█▌        | 8/50 [01:26<06:13,  8.89s/it]

[I 2025-12-02 04:47:17,899] Trial 9 finished with value: 0.5453947368421053 and parameters: {'max_depth': 3, 'learning_rate': 0.06332716952654806, 'n_estimators': 381, 'subsample': 0.6980227250942918, 'colsample_bytree': 0.8519190958107352, 'min_child_weight': 3, 'gamma': 2.8222368000017557, 'reg_alpha': 1.48103176268742e-08, 'reg_lambda': 0.0017583877117931877, 'max_delta_step': 5}. Best is trial 4 with value: 0.7171052631578947.

Best trial: 4. Best value: 0.717105:  18%|█▊        | 9/50 [01:33<05:39,  8.27s/it]

[I 2025-12-02 04:47:24,821] Trial 7 finished with value: 0.475 and parameters: {'max_depth': 4, 'learning_rate': 0.09303414722645176, 'n_estimators': 785, 'subsample': 0.690070920700359, 'colsample_bytree': 0.8953962605886078, 'min_child_weight': 9, 'gamma': 1.4719683125515721, 'reg_alpha': 0.03153141090948663, 'reg_lambda': 0.5564729417893313, 'max_delta_step': 5}. Best is trial 4 with value: 0.7171052631578947.

Best trial: 4. Best value: 0.717105:  20%|██        | 10/50 [01:35<04:18,  6.46s/it]

[I 2025-12-02 04:47:27,226] Trial 8 finished with value: 0.5203947368421052 and parameters: {'max_depth': 5, 'learning_rate': 0.17269480854575617, 'n_estimators': 627, 'subsample': 0.9650665956451698, 'colsample_bytree': 0.7045482795505255, 'min_child_weight': 3, 'gamma': 2.4878183630352564, 'reg_alpha': 1.7400729190237762e-05, 'reg_lambda': 4.083249218667208e-07, 'max_delta_step': 3}. Best is trial 4 with value: 0.7171052631578947.

Best trial: 4. Best value: 0.717105:  22%|██▏       | 11/50 [01:37<03:20,  5.15s/it]

[I 2025-12-02 04:47:29,388] Trial 10 pruned.

Best trial: 4. Best value: 0.717105:  24%|██▍       | 12/50 [01:39<02:31,  4.00s/it]

[I 2025-12-02 04:47:30,758] Trial 11 pruned.

Best trial: 4. Best value: 0.717105:  26%|██▌       | 13/50 [01:51<04:07,  6.70s/it]

[I 2025-12-02 04:47:43,675] Trial 15 finished with value: 0.5730263157894737 and parameters: {'max_depth': 7, 'learning_rate': 0.010101984746557574, 'n_estimators': 202, 'subsample': 0.8561564112100847, 'colsample_bytree': 0.6045706955494354, 'min_child_weight': 6, 'gamma': 4.936690800664058, 'reg_alpha': 0.0024333202797897167, 'reg_lambda': 6.448008365770243e-06, 'max_delta_step': 0}. Best is trial 4 with value: 0.7171052631578947.

Best trial: 4. Best value: 0.717105:  28%|██▊       | 14/50 [02:00<04:22,  7.28s/it]

[I 2025-12-02 04:47:52,296] Trial 12 pruned.

Best trial: 4. Best value: 0.717105:  30%|███       | 15/50 [02:02<03:16,  5.61s/it]

[I 2025-12-02 04:47:54,022] Trial 16 pruned.

Best trial: 4. Best value: 0.717105:  32%|███▏      | 16/50 [02:28<06:38, 11.71s/it]

[I 2025-12-02 04:48:19,902] Trial 14 finished with value: 0.5730263157894737 and parameters: {'max_depth': 7, 'learning_rate': 0.011483818727433214, 'n_estimators': 1193, 'subsample': 0.8460127670808105, 'colsample_bytree': 0.5118990692484781, 'min_child_weight': 6, 'gamma': 4.971362249102893, 'reg_alpha': 0.003383446487139676, 'reg_lambda': 4.139488622534925e-06, 'max_delta_step': 7}. Best is trial 4 with value: 0.7171052631578947.

Best trial: 4. Best value: 0.717105:  34%|███▍      | 17/50 [02:38<06:14, 11.34s/it]

[I 2025-12-02 04:48:30,400] Trial 13 finished with value: 0.5730263157894737 and parameters: {'max_depth': 10, 'learning_rate': 0.010144809686126102, 'n_estimators': 1232, 'subsample': 0.8437533803732769, 'colsample_bytree': 0.9740963260622005, 'min_child_weight': 6, 'gamma': 1.4937614851165217, 'reg_alpha': 0.0032438627658380906, 'reg_lambda': 5.652178711324256e-06, 'max_delta_step': 0}. Best is trial 4 with value: 0.7171052631578947.

Best trial: 4. Best value: 0.717105:  36%|███▌      | 18/50 [02:42<04:52,  9.16s/it]

[I 2025-12-02 04:48:34,463] Trial 20 pruned.

Best trial: 4. Best value: 0.717105:  38%|███▊      | 19/50 [02:44<03:35,  6.96s/it]

[I 2025-12-02 04:48:36,304] Trial 21 pruned.

Best trial: 4. Best value: 0.717105:  40%|████      | 20/50 [02:50<03:21,  6.73s/it]

[I 2025-12-02 04:48:42,495] Trial 19 finished with value: 0.7046052631578947 and parameters: {'max_depth': 10, 'learning_rate': 0.2648912606708438, 'n_estimators': 447, 'subsample': 0.7686943356418516, 'colsample_bytree': 0.9905499055764588, 'min_child_weight': 8, 'gamma': 0.18678678343588917, 'reg_alpha': 6.849417251782975, 'reg_lambda': 1.5832054843897144e-05, 'max_delta_step': 7}. Best is trial 4 with value: 0.7171052631578947.

Best trial: 4. Best value: 0.717105:  42%|████▏     | 21/50 [02:52<02:32,  5.27s/it]

[I 2025-12-02 04:48:44,381] Trial 17 finished with value: 0.5592105263157895 and parameters: {'max_depth': 10, 'learning_rate': 0.031236723631313863, 'n_estimators': 1149, 'subsample': 0.8819595226727885, 'colsample_bytree': 0.5349687498548196, 'min_child_weight': 6, 'gamma': 4.837267196626074, 'reg_alpha': 8.611884990199824, 'reg_lambda': 0.005231964797660402, 'max_delta_step': 7}. Best is trial 4 with value: 0.7171052631578947.

Best trial: 4. Best value: 0.717105:  44%|████▍     | 22/50 [02:53<01:54,  4.09s/it]

[I 2025-12-02 04:48:45,696] Trial 18 finished with value: 0.5993421052631579 and parameters: {'max_depth': 10, 'learning_rate': 0.1068800508696241, 'n_estimators': 1236, 'subsample': 0.779484635210945, 'colsample_bytree': 0.5143859180075883, 'min_child_weight': 6, 'gamma': 4.92533030966705, 'reg_alpha': 6.0562608906601864e-05, 'reg_lambda': 8.622250561844647e-06, 'max_delta_step': 7}. Best is trial 4 with value: 0.7171052631578947.

Best trial: 4. Best value: 0.717105:  46%|████▌     | 23/50 [02:59<01:58,  4.38s/it]

[I 2025-12-02 04:48:50,767] Trial 23 pruned.

Best trial: 22. Best value: 0.729605:  48%|████▊     | 24/50 [03:03<01:57,  4.52s/it]

[I 2025-12-02 04:48:55,598] Trial 22 finished with value: 0.7296052631578948 and parameters: {'max_depth': 5, 'learning_rate': 0.025926590974310038, 'n_estimators': 353, 'subsample': 0.9014827424395779, 'colsample_bytree': 0.9954686706434108, 'min_child_weight': 9, 'gamma': 4.178718531934162, 'reg_alpha': 3.73627178918554e-08, 'reg_lambda': 3.410530022916413e-05, 'max_delta_step': 7}. Best is trial 22 with value: 0.7296052631578948.

Best trial: 22. Best value: 0.729605:  52%|█████▏    | 26/50 [03:10<01:27,  3.65s/it]

[I 2025-12-02 04:49:02,273] Trial 25 finished with value: 0.638157894736842 and parameters: {'max_depth': 8, 'learning_rate': 0.28281023707757513, 'n_estimators': 326, 'subsample': 0.9104926666747784, 'colsample_bytree': 0.9875610980239026, 'min_child_weight': 9, 'gamma': 0.14689628968215063, 'reg_alpha': 0.04016049416936384, 'reg_lambda': 8.23898580591781e-05, 'max_delta_step': 8}. Best is trial 22 with value: 0.7296052631578948.
[I 2025-12-02 04:49:02,391] Trial 24 finished with value: 0.638157894736842 and parameters: {'max_depth': 8, 'learning_rate': 0.27970062090150655, 'n_estimators': 352, 'subsample': 0.9202557445793138, 'colsample_bytree': 0.995004781441438, 'min_child_weight': 9, 'gamma': 0.10281612538127094, 'reg_alpha': 0.08054297624457506, 'reg_lambda': 2.2510540304545634e-05, 'max_delta_step': 8}. Best is trial 22 with value: 0.7296052631578948.

Best trial: 22. Best value: 0.729605:  54%|█████▍    | 27/50 [03:17<01:43,  4.49s/it]

[I 2025-12-02 04:49:08,835] Trial 26 finished with value: 0.5993421052631579 and parameters: {'max_depth': 8, 'learning_rate': 0.2739787658673646, 'n_estimators': 370, 'subsample': 0.9271124736124724, 'colsample_bytree': 0.9923995253402151, 'min_child_weight': 9, 'gamma': 0.09710891125654504, 'reg_alpha': 0.08459927883144414, 'reg_lambda': 3.055479603740551e-05, 'max_delta_step': 6}. Best is trial 22 with value: 0.7296052631578948.

Best trial: 22. Best value: 0.729605:  56%|█████▌    | 28/50 [03:20<01:33,  4.24s/it]

[I 2025-12-02 04:49:12,498] Trial 27 finished with value: 0.7296052631578948 and parameters: {'max_depth': 4, 'learning_rate': 0.021227081044829975, 'n_estimators': 326, 'subsample': 0.9236728898690586, 'colsample_bytree': 0.9582391072928651, 'min_child_weight': 9, 'gamma': 3.4977965438293617, 'reg_alpha': 1.8074714446366175e-07, 'reg_lambda': 3.4091244291044e-07, 'max_delta_step': 6}. Best is trial 22 with value: 0.7296052631578948.

Best trial: 22. Best value: 0.729605:  58%|█████▊    | 29/50 [03:21<01:08,  3.29s/it]

[I 2025-12-02 04:49:13,556] Trial 30 pruned.

Best trial: 22. Best value: 0.729605:  60%|██████    | 30/50 [03:29<01:29,  4.46s/it]

[I 2025-12-02 04:49:20,751] Trial 32 pruned.

Best trial: 22. Best value: 0.729605:  62%|██████▏   | 31/50 [03:33<01:27,  4.58s/it]

[I 2025-12-02 04:49:25,624] Trial 29 pruned.

Best trial: 22. Best value: 0.729605:  64%|██████▍   | 32/50 [03:35<01:07,  3.75s/it]

[I 2025-12-02 04:49:27,417] Trial 33 pruned.

Best trial: 22. Best value: 0.729605:  66%|██████▌   | 33/50 [03:36<00:48,  2.85s/it]

[I 2025-12-02 04:49:28,168] Trial 34 pruned.

Best trial: 22. Best value: 0.729605:  68%|██████▊   | 34/50 [03:42<01:02,  3.89s/it]

[I 2025-12-02 04:49:34,504] Trial 35 pruned.

Best trial: 22. Best value: 0.729605:  70%|███████   | 35/50 [03:48<01:07,  4.51s/it]

[I 2025-12-02 04:49:40,464] Trial 36 pruned.

Best trial: 22. Best value: 0.729605:  72%|███████▏  | 36/50 [03:52<00:58,  4.18s/it]

[I 2025-12-02 04:49:43,870] Trial 31 finished with value: 0.6256578947368421 and parameters: {'max_depth': 5, 'learning_rate': 0.021238403223383887, 'n_estimators': 614, 'subsample': 0.8135597876939427, 'colsample_bytree': 0.9370369244099586, 'min_child_weight': 7, 'gamma': 3.432527738995342, 'reg_alpha': 1.1357996615237334e-07, 'reg_lambda': 7.062187221464745e-07, 'max_delta_step': 9}. Best is trial 22 with value: 0.7296052631578948.

Best trial: 22. Best value: 0.729605:  74%|███████▍  | 37/50 [03:57<01:00,  4.64s/it]

[I 2025-12-02 04:49:49,592] Trial 28 finished with value: 0.5730263157894737 and parameters: {'max_depth': 4, 'learning_rate': 0.021466943214900558, 'n_estimators': 981, 'subsample': 0.9383368780700849, 'colsample_bytree': 0.9514137573230903, 'min_child_weight': 7, 'gamma': 3.513879004084419, 'reg_alpha': 3.2176817455932036e-07, 'reg_lambda': 1.0478679806111583e-06, 'max_delta_step': 6}. Best is trial 22 with value: 0.7296052631578948.

Best trial: 22. Best value: 0.729605:  76%|███████▌  | 38/50 [04:06<01:09,  5.77s/it]

[I 2025-12-02 04:49:57,988] Trial 37 finished with value: 0.6118421052631579 and parameters: {'max_depth': 5, 'learning_rate': 0.02337157859791712, 'n_estimators': 455, 'subsample': 0.8809377219008988, 'colsample_bytree': 0.6540464476453318, 'min_child_weight': 8, 'gamma': 3.858725003796053, 'reg_alpha': 1.1081109065206413e-06, 'reg_lambda': 0.0009417668564833755, 'max_delta_step': 4}. Best is trial 22 with value: 0.7296052631578948.

Best trial: 22. Best value: 0.729605:  78%|███████▊  | 39/50 [04:19<01:28,  8.07s/it]

[I 2025-12-02 04:50:11,414] Trial 38 finished with value: 0.5993421052631579 and parameters: {'max_depth': 5, 'learning_rate': 0.023665787429413745, 'n_estimators': 664, 'subsample': 0.880362269274249, 'colsample_bytree': 0.6502752326177605, 'min_child_weight': 9, 'gamma': 3.5638561115097365, 'reg_alpha': 0.00013996812030928627, 'reg_lambda': 0.0008986273156749093, 'max_delta_step': 4}. Best is trial 22 with value: 0.7296052631578948.

Best trial: 22. Best value: 0.729605:  80%|████████  | 40/50 [04:25<01:12,  7.24s/it]

[I 2025-12-02 04:50:16,735] Trial 39 finished with value: 0.6769736842105263 and parameters: {'max_depth': 4, 'learning_rate': 0.07160558036363934, 'n_estimators': 730, 'subsample': 0.883828866594501, 'colsample_bytree': 0.6674569455802782, 'min_child_weight': 9, 'gamma': 3.6825753120152833, 'reg_alpha': 7.607863334093012e-07, 'reg_lambda': 1.9792699681664927e-07, 'max_delta_step': 5}. Best is trial 22 with value: 0.7296052631578948.

Best trial: 22. Best value: 0.729605:  82%|████████▏ | 41/50 [04:26<00:48,  5.38s/it]

[I 2025-12-02 04:50:17,766] Trial 42 pruned.

Best trial: 22. Best value: 0.729605:  84%|████████▍ | 42/50 [04:29<00:38,  4.85s/it]

[I 2025-12-02 04:50:21,387] Trial 43 pruned.

Best trial: 22. Best value: 0.729605:  86%|████████▌ | 43/50 [04:30<00:25,  3.70s/it]

[I 2025-12-02 04:50:22,403] Trial 40 finished with value: 0.6769736842105263 and parameters: {'max_depth': 4, 'learning_rate': 0.0770622363563352, 'n_estimators': 701, 'subsample': 0.8823542414024067, 'colsample_bytree': 0.6490559595303742, 'min_child_weight': 9, 'gamma': 3.95065579360406, 'reg_alpha': 1.2495692277664053e-08, 'reg_lambda': 0.0008809560019917811, 'max_delta_step': 5}. Best is trial 22 with value: 0.7296052631578948.

Best trial: 22. Best value: 0.729605:  88%|████████▊ | 44/50 [04:33<00:20,  3.34s/it]

[I 2025-12-02 04:50:24,895] Trial 46 pruned.

Best trial: 22. Best value: 0.729605:  90%|█████████ | 45/50 [04:37<00:17,  3.50s/it]

[I 2025-12-02 04:50:28,760] Trial 47 pruned.

Best trial: 22. Best value: 0.729605:  92%|█████████▏| 46/50 [04:40<00:14,  3.55s/it]

[I 2025-12-02 04:50:32,438] Trial 48 pruned.

Best trial: 22. Best value: 0.729605:  94%|█████████▍| 47/50 [04:43<00:09,  3.18s/it]

[I 2025-12-02 04:50:34,755] Trial 41 finished with value: 0.7171052631578947 and parameters: {'max_depth': 4, 'learning_rate': 0.014676534603095105, 'n_estimators': 733, 'subsample': 0.9006656383225877, 'colsample_bytree': 0.911249956291626, 'min_child_weight': 9, 'gamma': 3.0845303351385684, 'reg_alpha': 1.0469093857211778e-08, 'reg_lambda': 1.3044558649952165e-07, 'max_delta_step': 5}. Best is trial 22 with value: 0.7296052631578948.

Best trial: 22. Best value: 0.729605:  96%|█████████▌| 48/50 [04:46<00:06,  3.28s/it]

[I 2025-12-02 04:50:38,280] Trial 44 finished with value: 0.6519736842105264 and parameters: {'max_depth': 9, 'learning_rate': 0.22347320623672837, 'n_estimators': 416, 'subsample': 0.7399925394182161, 'colsample_bytree': 0.966963129445763, 'min_child_weight': 8, 'gamma': 0.8563605473804672, 'reg_alpha': 1.5643302297600912, 'reg_lambda': 0.00016027756935681155, 'max_delta_step': 8}. Best is trial 22 with value: 0.7296052631578948.

Best trial: 22. Best value: 0.729605:  98%|█████████▊| 49/50 [04:48<00:02,  2.79s/it]

[I 2025-12-02 04:50:39,903] Trial 45 finished with value: 0.55 and parameters: {'max_depth': 9, 'learning_rate': 0.2239152858575462, 'n_estimators': 409, 'subsample': 0.5928301495071522, 'colsample_bytree': 0.9764037701531211, 'min_child_weight': 8, 'gamma': 4.018985680197871, 'reg_alpha': 0.5632195237280442, 'reg_lambda': 0.00012065753595563528, 'max_delta_step': 7}. Best is trial 22 with value: 0.7296052631578948.

Best trial: 22. Best value: 0.729605: 100%|██████████| 50/50 [05:01<00:00,  6.03s/it]

[I 2025-12-02 04:50:53,153] Trial 49 finished with value: 0.6118421052631579 and parameters: {'max_depth': 10, 'learning_rate': 0.050111393005083514, 'n_estimators': 864, 'subsample': 0.854719860792875, 'colsample_bytree': 0.7270003507088962, 'min_child_weight': 8, 'gamma': 2.7030994356820486, 'reg_alpha': 1.845772540497819, 'reg_lambda': 0.036339632619347174, 'max_delta_step': 7}. Best is trial 22 with value: 0.7296052631578948.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    19_1         loo       0.729605                    0.75          0.84
1    17_1         loo       0.732349                    0.55          0.50
2     9_1         loo       0.667105                    0.50          0.63
3    15_1         loo       0.667522                    0.35          0.66

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.533002               0.6               0.9        50          59
1  0.100000               0.4               0.7        50          60
2  0.000000               0.4               0.6        50          59
3 -0.353553               0.0               0.7        50          60

   test_size
0         15
1         15
2         15
3         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    19_1         loo       0.729605                    0.75          0.84
1    17_1         loo       0.732349                    0.55          0.50
2     9_1         loo       0.667105                    0.50          0.63
3    15_1         loo       0.667522                    0.35          0.66

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.533002               0.6               0.9        50          59
1  0.100000               0.4               0.7        50          60
2  0.000000               0.4               0.6        50          59
3 -0.353553               0.0               0.7        50          60

   test_size
0         15
1         15
2         15
3         15

In [ ]:

# Combined embedings
datasets = task_comb_dfs_pd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_pd_hc_{CV_STRATEGY}_tasks/xgb_results_combined_pd_hc_extended_{CV_STRATEGY}_tasks",
    split_param="emb_",
)
print(summary)

[I 2025-12-02 04:50:56,290] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.475:   2%|▏         | 1/50 [00:17<14:00, 17.16s/it]

[I 2025-12-02 04:51:13,437] Trial 2 finished with value: 0.475 and parameters: {'max_depth': 5, 'learning_rate': 0.01934357570791956, 'n_estimators': 306, 'subsample': 0.5491757198742266, 'colsample_bytree': 0.9649986917114111, 'min_child_weight': 8, 'gamma': 4.581983184052204, 'reg_alpha': 2.338132796364119e-05, 'reg_lambda': 0.42604285889562343, 'max_delta_step': 4}. Best is trial 2 with value: 0.475.

Best trial: 0. Best value: 0.638158:   4%|▍         | 2/50 [00:40<16:24, 20.50s/it]

[I 2025-12-02 04:51:36,285] Trial 0 finished with value: 0.638157894736842 and parameters: {'max_depth': 3, 'learning_rate': 0.018329771339531183, 'n_estimators': 791, 'subsample': 0.9732462578457707, 'colsample_bytree': 0.5242651397041943, 'min_child_weight': 8, 'gamma': 3.766472644078224, 'reg_alpha': 0.11872889945293714, 'reg_lambda': 0.005017453958277477, 'max_delta_step': 5}. Best is trial 0 with value: 0.638157894736842.

Best trial: 3. Best value: 0.650658:   6%|▌         | 3/50 [00:56<14:46, 18.86s/it]

[I 2025-12-02 04:51:53,182] Trial 3 finished with value: 0.6506578947368421 and parameters: {'max_depth': 6, 'learning_rate': 0.014452171880401384, 'n_estimators': 643, 'subsample': 0.5069117764476923, 'colsample_bytree': 0.5069911974420687, 'min_child_weight': 3, 'gamma': 0.8192336186551835, 'reg_alpha': 1.0830768080580914e-08, 'reg_lambda': 3.560039881268862, 'max_delta_step': 8}. Best is trial 3 with value: 0.6506578947368421.

Best trial: 3. Best value: 0.650658:   8%|▊         | 4/50 [01:28<18:18, 23.87s/it]

[I 2025-12-02 04:52:24,752] Trial 5 finished with value: 0.5480263157894737 and parameters: {'max_depth': 5, 'learning_rate': 0.1457845045233345, 'n_estimators': 1134, 'subsample': 0.5176938796126846, 'colsample_bytree': 0.5261968663459207, 'min_child_weight': 4, 'gamma': 0.01832471328302998, 'reg_alpha': 6.506053182265424e-08, 'reg_lambda': 0.003843851072315568, 'max_delta_step': 2}. Best is trial 3 with value: 0.6506578947368421.

Best trial: 1. Best value: 0.690789:  10%|█         | 5/50 [01:29<11:46, 15.71s/it]

[I 2025-12-02 04:52:25,979] Trial 1 finished with value: 0.6907894736842105 and parameters: {'max_depth': 8, 'learning_rate': 0.03805591276879173, 'n_estimators': 992, 'subsample': 0.8430270899417617, 'colsample_bytree': 0.6526167453223575, 'min_child_weight': 1, 'gamma': 2.579460329521503, 'reg_alpha': 3.1356317646307548, 'reg_lambda': 3.224551442269622e-05, 'max_delta_step': 8}. Best is trial 1 with value: 0.6907894736842105.

Best trial: 1. Best value: 0.690789:  12%|█▏        | 6/50 [01:32<08:19, 11.35s/it]

[I 2025-12-02 04:52:28,869] Trial 4 finished with value: 0.6256578947368421 and parameters: {'max_depth': 8, 'learning_rate': 0.16113518996006324, 'n_estimators': 1440, 'subsample': 0.5943219499286818, 'colsample_bytree': 0.9623004766222863, 'min_child_weight': 2, 'gamma': 0.002542041753375579, 'reg_alpha': 5.583823188254157e-07, 'reg_lambda': 0.008555414685033593, 'max_delta_step': 10}. Best is trial 1 with value: 0.6907894736842105.

Best trial: 1. Best value: 0.690789:  14%|█▍        | 7/50 [02:21<17:00, 23.72s/it]

[I 2025-12-02 04:53:18,067] Trial 7 finished with value: 0.6118421052631579 and parameters: {'max_depth': 8, 'learning_rate': 0.0932128618459318, 'n_estimators': 1310, 'subsample': 0.6419379201823388, 'colsample_bytree': 0.7034505450641988, 'min_child_weight': 8, 'gamma': 4.2991622775381275, 'reg_alpha': 0.00020092954604139805, 'reg_lambda': 1.57649257779698e-08, 'max_delta_step': 6}. Best is trial 1 with value: 0.6907894736842105.

Best trial: 1. Best value: 0.690789:  16%|█▌        | 8/50 [02:27<12:30, 17.88s/it]

[I 2025-12-02 04:53:23,424] Trial 9 finished with value: 0.5868421052631578 and parameters: {'max_depth': 7, 'learning_rate': 0.027558531060581197, 'n_estimators': 1198, 'subsample': 0.8710174754864799, 'colsample_bytree': 0.5494105666523336, 'min_child_weight': 6, 'gamma': 1.3078864818177716, 'reg_alpha': 1.3409757693265417e-07, 'reg_lambda': 1.7656162204477453e-07, 'max_delta_step': 10}. Best is trial 1 with value: 0.6907894736842105.

Best trial: 10. Best value: 0.703289:  18%|█▊        | 9/50 [02:35<10:11, 14.91s/it]

[I 2025-12-02 04:53:31,818] Trial 10 finished with value: 0.7032894736842106 and parameters: {'max_depth': 3, 'learning_rate': 0.05601029790640082, 'n_estimators': 210, 'subsample': 0.9864968462258856, 'colsample_bytree': 0.584900687108448, 'min_child_weight': 8, 'gamma': 3.1013950958694037, 'reg_alpha': 1.164279610899594, 'reg_lambda': 0.00037592494841041046, 'max_delta_step': 1}. Best is trial 10 with value: 0.7032894736842106.

Best trial: 10. Best value: 0.703289:  20%|██        | 10/50 [02:35<06:55, 10.39s/it]

[I 2025-12-02 04:53:32,091] Trial 6 finished with value: 0.6519736842105264 and parameters: {'max_depth': 7, 'learning_rate': 0.026786825991523436, 'n_estimators': 1060, 'subsample': 0.7472638696313052, 'colsample_bytree': 0.746825679002968, 'min_child_weight': 1, 'gamma': 3.9839644506407352, 'reg_alpha': 6.447960785065801e-05, 'reg_lambda': 0.9993068088050213, 'max_delta_step': 4}. Best is trial 10 with value: 0.7032894736842106.

Best trial: 10. Best value: 0.703289:  22%|██▏       | 11/50 [02:37<04:56,  7.61s/it]

[I 2025-12-02 04:53:33,409] Trial 11 pruned.

Best trial: 10. Best value: 0.703289:  24%|██▍       | 12/50 [02:38<03:31,  5.57s/it]

[I 2025-12-02 04:53:34,295] Trial 13 pruned.

Best trial: 10. Best value: 0.703289:  26%|██▌       | 13/50 [02:39<02:37,  4.27s/it]

[I 2025-12-02 04:53:35,572] Trial 14 pruned.

Best trial: 10. Best value: 0.703289:  28%|██▊       | 14/50 [02:46<03:01,  5.04s/it]

[I 2025-12-02 04:53:42,410] Trial 12 pruned.

Best trial: 10. Best value: 0.703289:  30%|███       | 15/50 [02:48<02:25,  4.14s/it]

[I 2025-12-02 04:53:44,470] Trial 16 pruned.

Best trial: 10. Best value: 0.703289:  32%|███▏      | 16/50 [03:14<06:05, 10.76s/it]

[I 2025-12-02 04:54:10,591] Trial 18 finished with value: 0.638157894736842 and parameters: {'max_depth': 9, 'learning_rate': 0.27512543223949676, 'n_estimators': 554, 'subsample': 0.8804237889953069, 'colsample_bytree': 0.6050037655077439, 'min_child_weight': 5, 'gamma': 2.1033291400346363, 'reg_alpha': 0.21140181751569226, 'reg_lambda': 0.0003477997784608179, 'max_delta_step': 8}. Best is trial 10 with value: 0.7032894736842106.

Best trial: 10. Best value: 0.703289:  34%|███▍      | 17/50 [03:18<04:53,  8.89s/it]

[I 2025-12-02 04:54:15,122] Trial 19 pruned.

Best trial: 15. Best value: 0.730921:  36%|███▌      | 18/50 [03:29<04:57,  9.29s/it]

[I 2025-12-02 04:54:25,357] Trial 15 finished with value: 0.7309210526315789 and parameters: {'max_depth': 10, 'learning_rate': 0.04249319463731565, 'n_estimators': 936, 'subsample': 0.8785635481339433, 'colsample_bytree': 0.6262962020783295, 'min_child_weight': 6, 'gamma': 2.9326946755021397, 'reg_alpha': 6.8739785549265555, 'reg_lambda': 2.762725670302687e-05, 'max_delta_step': 7}. Best is trial 15 with value: 0.7309210526315789.

Best trial: 15. Best value: 0.730921:  38%|███▊      | 19/50 [03:36<04:26,  8.58s/it]

[I 2025-12-02 04:54:32,292] Trial 8 finished with value: 0.6243421052631579 and parameters: {'max_depth': 3, 'learning_rate': 0.011240738437835776, 'n_estimators': 1083, 'subsample': 0.7510005117978027, 'colsample_bytree': 0.8660127573399266, 'min_child_weight': 2, 'gamma': 1.6076481287663809, 'reg_alpha': 0.010226947946658797, 'reg_lambda': 0.2461288513038702, 'max_delta_step': 1}. Best is trial 15 with value: 0.7309210526315789.

Best trial: 17. Best value: 0.783553:  40%|████      | 20/50 [03:39<03:31,  7.06s/it]

[I 2025-12-02 04:54:35,786] Trial 17 finished with value: 0.7835526315789474 and parameters: {'max_depth': 3, 'learning_rate': 0.043765436549717464, 'n_estimators': 946, 'subsample': 0.8788368348931116, 'colsample_bytree': 0.6317028849685027, 'min_child_weight': 6, 'gamma': 2.198034914039787, 'reg_alpha': 8.830654276311831, 'reg_lambda': 0.0003429330089402229, 'max_delta_step': 7}. Best is trial 17 with value: 0.7835526315789474.

Best trial: 17. Best value: 0.783553:  42%|████▏     | 21/50 [03:46<03:24,  7.07s/it]

[I 2025-12-02 04:54:42,884] Trial 23 pruned.

Best trial: 17. Best value: 0.783553:  44%|████▍     | 22/50 [03:53<03:13,  6.93s/it]

[I 2025-12-02 04:54:49,484] Trial 24 pruned.

Best trial: 17. Best value: 0.783553:  46%|████▌     | 23/50 [04:09<04:20,  9.66s/it]

[I 2025-12-02 04:55:05,517] Trial 21 finished with value: 0.6256578947368421 and parameters: {'max_depth': 4, 'learning_rate': 0.08704738435125428, 'n_estimators': 839, 'subsample': 0.9372877249351059, 'colsample_bytree': 0.8056394100121589, 'min_child_weight': 7, 'gamma': 3.187430133639185, 'reg_alpha': 0.5847666065256045, 'reg_lambda': 0.00042664735330283517, 'max_delta_step': 4}. Best is trial 17 with value: 0.7835526315789474.

Best trial: 17. Best value: 0.783553:  48%|████▊     | 24/50 [04:14<03:39,  8.45s/it]

[I 2025-12-02 04:55:11,139] Trial 26 pruned.

Best trial: 17. Best value: 0.783553:  50%|█████     | 25/50 [04:15<02:33,  6.12s/it]

[I 2025-12-02 04:55:11,826] Trial 22 finished with value: 0.6256578947368421 and parameters: {'max_depth': 5, 'learning_rate': 0.09255859764531228, 'n_estimators': 836, 'subsample': 0.9313924257245059, 'colsample_bytree': 0.7669175233445829, 'min_child_weight': 7, 'gamma': 3.3613411427776976, 'reg_alpha': 0.5126711580441614, 'reg_lambda': 0.0005042686212334079, 'max_delta_step': 4}. Best is trial 17 with value: 0.7835526315789474.

Best trial: 17. Best value: 0.783553:  52%|█████▏    | 26/50 [04:18<02:05,  5.23s/it]

[I 2025-12-02 04:55:14,982] Trial 27 pruned.

Best trial: 17. Best value: 0.783553:  54%|█████▍    | 27/50 [04:19<01:30,  3.92s/it]

[I 2025-12-02 04:55:15,834] Trial 28 pruned.

Best trial: 17. Best value: 0.783553:  56%|█████▌    | 28/50 [04:29<02:08,  5.86s/it]

[I 2025-12-02 04:55:26,226] Trial 30 pruned.

Best trial: 17. Best value: 0.783553:  58%|█████▊    | 29/50 [04:32<01:43,  4.93s/it]

[I 2025-12-02 04:55:28,981] Trial 25 finished with value: 0.7835526315789474 and parameters: {'max_depth': 4, 'learning_rate': 0.08245433085166605, 'n_estimators': 754, 'subsample': 0.9402121992314304, 'colsample_bytree': 0.6901795953387135, 'min_child_weight': 7, 'gamma': 4.97626513076377, 'reg_alpha': 7.849418034178848, 'reg_lambda': 0.000940220413972428, 'max_delta_step': 6}. Best is trial 17 with value: 0.7835526315789474.

Best trial: 17. Best value: 0.783553:  60%|██████    | 30/50 [04:34<01:21,  4.07s/it]

[I 2025-12-02 04:55:31,059] Trial 20 finished with value: 0.6519736842105264 and parameters: {'max_depth': 4, 'learning_rate': 0.08746643044272107, 'n_estimators': 844, 'subsample': 0.922671513207346, 'colsample_bytree': 0.762750627553781, 'min_child_weight': 1, 'gamma': 4.969378093228496, 'reg_alpha': 0.9359144245559902, 'reg_lambda': 0.00023201069082358356, 'max_delta_step': 8}. Best is trial 17 with value: 0.7835526315789474.

Best trial: 17. Best value: 0.783553:  62%|██████▏   | 31/50 [04:39<01:23,  4.37s/it]

[I 2025-12-02 04:55:36,138] Trial 32 pruned.

Best trial: 17. Best value: 0.783553:  64%|██████▍   | 32/50 [04:41<01:03,  3.54s/it]

[I 2025-12-02 04:55:37,739] Trial 33 pruned.

Best trial: 17. Best value: 0.783553:  66%|██████▌   | 33/50 [05:06<02:52, 10.12s/it]

[I 2025-12-02 04:56:03,206] Trial 31 finished with value: 0.7421052631578948 and parameters: {'max_depth': 6, 'learning_rate': 0.0785148754830165, 'n_estimators': 725, 'subsample': 0.9594304771441797, 'colsample_bytree': 0.6486043966064726, 'min_child_weight': 9, 'gamma': 4.943032720656947, 'reg_alpha': 2.5010193352283827, 'reg_lambda': 2.342940666256032e-06, 'max_delta_step': 3}. Best is trial 17 with value: 0.7835526315789474.

Best trial: 17. Best value: 0.783553:  68%|██████▊   | 34/50 [05:19<02:54, 10.91s/it]

[I 2025-12-02 04:56:15,964] Trial 29 finished with value: 0.6256578947368421 and parameters: {'max_depth': 9, 'learning_rate': 0.034793001685082495, 'n_estimators': 969, 'subsample': 0.8949712749927872, 'colsample_bytree': 0.6950483818825374, 'min_child_weight': 5, 'gamma': 4.734404818222282, 'reg_alpha': 2.4200420005396923, 'reg_lambda': 0.057518119196674856, 'max_delta_step': 6}. Best is trial 17 with value: 0.7835526315789474.

Best trial: 17. Best value: 0.783553:  70%|███████   | 35/50 [05:25<02:22,  9.47s/it]

[I 2025-12-02 04:56:22,071] Trial 35 finished with value: 0.7684210526315789 and parameters: {'max_depth': 3, 'learning_rate': 0.06943454101607843, 'n_estimators': 957, 'subsample': 0.9727717698554912, 'colsample_bytree': 0.62573432021562, 'min_child_weight': 9, 'gamma': 3.89875862251645, 'reg_alpha': 2.658117513705943, 'reg_lambda': 0.0016141356838739198, 'max_delta_step': 6}. Best is trial 17 with value: 0.7835526315789474.

Best trial: 34. Best value: 0.794737:  72%|███████▏  | 36/50 [05:34<02:08,  9.21s/it]

[I 2025-12-02 04:56:30,672] Trial 34 finished with value: 0.7947368421052632 and parameters: {'max_depth': 3, 'learning_rate': 0.07202705254348755, 'n_estimators': 1191, 'subsample': 0.9674510814785449, 'colsample_bytree': 0.6423824701187235, 'min_child_weight': 9, 'gamma': 3.9390880220818882, 'reg_alpha': 2.5385132265022574, 'reg_lambda': 0.001404599471859067, 'max_delta_step': 6}. Best is trial 34 with value: 0.7947368421052632.

Best trial: 34. Best value: 0.794737:  74%|███████▍  | 37/50 [05:45<02:05,  9.63s/it]

[I 2025-12-02 04:56:41,301] Trial 37 finished with value: 0.7296052631578948 and parameters: {'max_depth': 5, 'learning_rate': 0.04510368794902415, 'n_estimators': 536, 'subsample': 0.9610780013552298, 'colsample_bytree': 0.6510605118097307, 'min_child_weight': 9, 'gamma': 4.284959314902375, 'reg_alpha': 4.601913220296819, 'reg_lambda': 2.2853719968998336e-07, 'max_delta_step': 7}. Best is trial 34 with value: 0.7947368421052632.

Best trial: 36. Best value: 0.808553:  76%|███████▌  | 38/50 [05:49<01:37,  8.12s/it]

[I 2025-12-02 04:56:45,878] Trial 36 finished with value: 0.8085526315789473 and parameters: {'max_depth': 7, 'learning_rate': 0.06737475800671477, 'n_estimators': 941, 'subsample': 0.9614413758656852, 'colsample_bytree': 0.6567576655572331, 'min_child_weight': 9, 'gamma': 4.276741504830838, 'reg_alpha': 3.679061059966359, 'reg_lambda': 6.605988590693275e-07, 'max_delta_step': 3}. Best is trial 36 with value: 0.8085526315789473.

Best trial: 36. Best value: 0.808553:  78%|███████▊  | 39/50 [05:53<01:16,  6.96s/it]

[I 2025-12-02 04:56:50,129] Trial 38 finished with value: 0.8085526315789473 and parameters: {'max_depth': 3, 'learning_rate': 0.06564904717515511, 'n_estimators': 575, 'subsample': 0.9613677776466748, 'colsample_bytree': 0.6617783341236128, 'min_child_weight': 9, 'gamma': 4.384871775900994, 'reg_alpha': 2.473202607968582, 'reg_lambda': 0.0014061653643818116, 'max_delta_step': 3}. Best is trial 36 with value: 0.8085526315789473.

Best trial: 36. Best value: 0.808553:  80%|████████  | 40/50 [06:02<01:15,  7.51s/it]

[I 2025-12-02 04:56:58,943] Trial 42 pruned.

Best trial: 36. Best value: 0.808553:  82%|████████▏ | 41/50 [06:10<01:08,  7.63s/it]

[I 2025-12-02 04:57:06,829] Trial 43 pruned.

Best trial: 36. Best value: 0.808553:  84%|████████▍ | 42/50 [06:27<01:22, 10.30s/it]

[I 2025-12-02 04:57:23,357] Trial 39 finished with value: 0.8085526315789473 and parameters: {'max_depth': 3, 'learning_rate': 0.07207806285192903, 'n_estimators': 1182, 'subsample': 0.9600479093536497, 'colsample_bytree': 0.6654693073572563, 'min_child_weight': 9, 'gamma': 4.34785598289092, 'reg_alpha': 9.654765462858414, 'reg_lambda': 0.001634540234582507, 'max_delta_step': 9}. Best is trial 36 with value: 0.8085526315789473.

Best trial: 36. Best value: 0.808553:  86%|████████▌ | 43/50 [06:35<01:08,  9.84s/it]

[I 2025-12-02 04:57:32,123] Trial 40 finished with value: 0.7296052631578948 and parameters: {'max_depth': 3, 'learning_rate': 0.06958582751604382, 'n_estimators': 1179, 'subsample': 0.962280047306449, 'colsample_bytree': 0.5227707296933911, 'min_child_weight': 9, 'gamma': 3.8634651476481108, 'reg_alpha': 0.1313270994037723, 'reg_lambda': 0.001942455948904032, 'max_delta_step': 8}. Best is trial 36 with value: 0.8085526315789473.

Best trial: 36. Best value: 0.808553:  90%|█████████ | 45/50 [06:37<00:25,  5.16s/it]

[I 2025-12-02 04:57:33,571] Trial 45 pruned.
[I 2025-12-02 04:57:33,694] Trial 44 finished with value: 0.7559210526315789 and parameters: {'max_depth': 4, 'learning_rate': 0.06555415017009272, 'n_estimators': 593, 'subsample': 0.9561592453552311, 'colsample_bytree': 0.6594904818512611, 'min_child_weight': 8, 'gamma': 4.512945621402965, 'reg_alpha': 0.3622667639111889, 'reg_lambda': 0.016654850244261134, 'max_delta_step': 5}. Best is trial 36 with value: 0.8085526315789473.

Best trial: 36. Best value: 0.808553:  92%|█████████▏| 46/50 [06:41<00:19,  4.92s/it]

[I 2025-12-02 04:57:38,063] Trial 41 finished with value: 0.638157894736842 and parameters: {'max_depth': 7, 'learning_rate': 0.1915587210639981, 'n_estimators': 1192, 'subsample': 0.9568182002560609, 'colsample_bytree': 0.7299730990363901, 'min_child_weight': 8, 'gamma': 4.487245599543857, 'reg_alpha': 2.505021866012471e-06, 'reg_lambda': 0.00966398600493764, 'max_delta_step': 3}. Best is trial 36 with value: 0.8085526315789473.

Best trial: 36. Best value: 0.808553:  94%|█████████▍| 47/50 [06:46<00:14,  4.90s/it]

[I 2025-12-02 04:57:42,898] Trial 48 pruned.
[I 2025-12-02 04:57:42,931] Trial 47 pruned.

Best trial: 36. Best value: 0.808553:  98%|█████████▊| 49/50 [06:48<00:03,  3.12s/it]

[I 2025-12-02 04:57:45,009] Trial 49 pruned.

Best trial: 36. Best value: 0.808553: 100%|██████████| 50/50 [07:19<00:00,  8.78s/it]

[I 2025-12-02 04:58:15,424] Trial 46 finished with value: 0.6769736842105263 and parameters: {'max_depth': 3, 'learning_rate': 0.06263326967804188, 'n_estimators': 1390, 'subsample': 0.9515601472081928, 'colsample_bytree': 0.6638829050353132, 'min_child_weight': 8, 'gamma': 4.1029852178876824, 'reg_alpha': 0.4396233660300205, 'reg_lambda': 0.016112720074049094, 'max_delta_step': 9}. Best is trial 36 with value: 0.8085526315789473.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 04:58:18,968] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.501284:   2%|▏         | 1/50 [00:17<14:39, 17.94s/it]

[I 2025-12-02 04:58:36,900] Trial 0 finished with value: 0.5012836970474968 and parameters: {'max_depth': 10, 'learning_rate': 0.09458870856800633, 'n_estimators': 364, 'subsample': 0.6677228757421704, 'colsample_bytree': 0.8643278154242733, 'min_child_weight': 8, 'gamma': 3.3308481050695833, 'reg_alpha': 2.228307088197103e-08, 'reg_lambda': 0.10944268310680182, 'max_delta_step': 5}. Best is trial 0 with value: 0.5012836970474968.

Best trial: 0. Best value: 0.501284:   4%|▍         | 2/50 [00:21<07:30,  9.38s/it]

[I 2025-12-02 04:58:40,280] Trial 2 finished with value: 0.18421052631578946 and parameters: {'max_depth': 4, 'learning_rate': 0.10818333999915575, 'n_estimators': 441, 'subsample': 0.5806862032231257, 'colsample_bytree': 0.9791108642109152, 'min_child_weight': 9, 'gamma': 2.6221453115864346, 'reg_alpha': 0.7718901341169092, 'reg_lambda': 8.54534551439712e-08, 'max_delta_step': 5}. Best is trial 0 with value: 0.5012836970474968.

Best trial: 0. Best value: 0.501284:   6%|▌         | 3/50 [00:47<13:16, 16.95s/it]

[I 2025-12-02 04:59:06,253] Trial 4 finished with value: 0.4473684210526316 and parameters: {'max_depth': 9, 'learning_rate': 0.024302004927304784, 'n_estimators': 688, 'subsample': 0.5232882972385781, 'colsample_bytree': 0.5939949405307487, 'min_child_weight': 10, 'gamma': 2.532807292041923, 'reg_alpha': 0.002707356165896303, 'reg_lambda': 1.0818099741481268e-05, 'max_delta_step': 7}. Best is trial 0 with value: 0.5012836970474968.

Best trial: 0. Best value: 0.501284:   8%|▊         | 4/50 [00:52<09:27, 12.34s/it]

[I 2025-12-02 04:59:11,522] Trial 3 finished with value: 0.18421052631578946 and parameters: {'max_depth': 3, 'learning_rate': 0.19368454470317237, 'n_estimators': 1214, 'subsample': 0.5185037676892899, 'colsample_bytree': 0.7465113085864825, 'min_child_weight': 10, 'gamma': 2.3905483942147736, 'reg_alpha': 7.397558462902035e-05, 'reg_lambda': 1.9263115225097877e-07, 'max_delta_step': 3}. Best is trial 0 with value: 0.5012836970474968.

Best trial: 0. Best value: 0.501284:  10%|█         | 5/50 [01:27<15:19, 20.44s/it]

[I 2025-12-02 04:59:46,322] Trial 5 finished with value: 0.4608472400513479 and parameters: {'max_depth': 3, 'learning_rate': 0.05546172761910843, 'n_estimators': 1052, 'subsample': 0.927921298014364, 'colsample_bytree': 0.6172237648745447, 'min_child_weight': 4, 'gamma': 3.263329580562944, 'reg_alpha': 4.098409606341804, 'reg_lambda': 4.25753959617046e-06, 'max_delta_step': 3}. Best is trial 0 with value: 0.5012836970474968.

Best trial: 0. Best value: 0.501284:  12%|█▏        | 6/50 [01:33<11:32, 15.75s/it]

[I 2025-12-02 04:59:52,959] Trial 1 finished with value: 0.3838254172015404 and parameters: {'max_depth': 6, 'learning_rate': 0.07831486402651751, 'n_estimators': 1082, 'subsample': 0.98852714337196, 'colsample_bytree': 0.7748963844010996, 'min_child_weight': 1, 'gamma': 4.830904065076586, 'reg_alpha': 6.383209378660875e-07, 'reg_lambda': 0.25926093764551167, 'max_delta_step': 8}. Best is trial 0 with value: 0.5012836970474968.

Best trial: 0. Best value: 0.501284:  14%|█▍        | 7/50 [01:43<09:53, 13.80s/it]

[I 2025-12-02 05:00:02,747] Trial 7 finished with value: 0.2349165596919127 and parameters: {'max_depth': 5, 'learning_rate': 0.13410466781844793, 'n_estimators': 1199, 'subsample': 0.5714982840106106, 'colsample_bytree': 0.7398604474742825, 'min_child_weight': 9, 'gamma': 4.7673619214146505, 'reg_alpha': 0.0800033124647757, 'reg_lambda': 0.00083631966603157, 'max_delta_step': 0}. Best is trial 0 with value: 0.5012836970474968.

Best trial: 0. Best value: 0.501284:  16%|█▌        | 8/50 [01:52<08:37, 12.33s/it]

[I 2025-12-02 05:00:11,939] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.04105003009285088, 'n_estimators': 1478, 'subsample': 0.5835893022232936, 'colsample_bytree': 0.8384889634121137, 'min_child_weight': 8, 'gamma': 2.479919071418381, 'reg_alpha': 9.955281572419605e-06, 'reg_lambda': 2.4254430951539857e-05, 'max_delta_step': 1}. Best is trial 0 with value: 0.5012836970474968.

Best trial: 0. Best value: 0.501284:  18%|█▊        | 9/50 [01:56<06:36,  9.67s/it]

[I 2025-12-02 05:00:15,765] Trial 9 finished with value: 0.4993581514762516 and parameters: {'max_depth': 10, 'learning_rate': 0.02296012456117532, 'n_estimators': 259, 'subsample': 0.7900634585863118, 'colsample_bytree': 0.7179797636756815, 'min_child_weight': 7, 'gamma': 1.8484652208329218, 'reg_alpha': 0.03167863904131034, 'reg_lambda': 3.9233342396727395, 'max_delta_step': 8}. Best is trial 0 with value: 0.5012836970474968.

Best trial: 0. Best value: 0.501284:  20%|██        | 10/50 [02:30<11:20, 17.00s/it]

[I 2025-12-02 05:00:49,182] Trial 8 finished with value: 0.35365853658536583 and parameters: {'max_depth': 10, 'learning_rate': 0.11083491284638451, 'n_estimators': 1361, 'subsample': 0.8588460198875998, 'colsample_bytree': 0.9684851880575347, 'min_child_weight': 10, 'gamma': 4.940738324950279, 'reg_alpha': 0.015509141560851094, 'reg_lambda': 4.818712472893291e-06, 'max_delta_step': 0}. Best is trial 0 with value: 0.5012836970474968.

Best trial: 0. Best value: 0.501284:  22%|██▏       | 11/50 [02:31<07:53, 12.13s/it]

[I 2025-12-02 05:00:50,273] Trial 11 pruned.

Best trial: 10. Best value: 0.529525:  24%|██▍       | 12/50 [02:31<05:28,  8.64s/it]

[I 2025-12-02 05:00:50,915] Trial 10 finished with value: 0.5295250320924262 and parameters: {'max_depth': 6, 'learning_rate': 0.18482223190316568, 'n_estimators': 1085, 'subsample': 0.7761965491831977, 'colsample_bytree': 0.6991645860506611, 'min_child_weight': 9, 'gamma': 0.4327619061016458, 'reg_alpha': 2.509962199305819e-06, 'reg_lambda': 5.219898082409295e-07, 'max_delta_step': 9}. Best is trial 10 with value: 0.5295250320924262.

Best trial: 10. Best value: 0.529525:  26%|██▌       | 13/50 [02:46<06:26, 10.44s/it]

[I 2025-12-02 05:01:05,495] Trial 12 pruned.

Best trial: 10. Best value: 0.529525:  28%|██▊       | 14/50 [03:18<10:11, 16.99s/it]

[I 2025-12-02 05:01:37,613] Trial 14 finished with value: 0.5012836970474968 and parameters: {'max_depth': 7, 'learning_rate': 0.011616322727363782, 'n_estimators': 665, 'subsample': 0.6842542133866549, 'colsample_bytree': 0.873925883890955, 'min_child_weight': 7, 'gamma': 0.34659053969704523, 'reg_alpha': 9.288229432591334e-06, 'reg_lambda': 0.0352383718906856, 'max_delta_step': 3}. Best is trial 10 with value: 0.5295250320924262.

Best trial: 10. Best value: 0.529525:  30%|███       | 15/50 [03:23<07:42, 13.22s/it]

[I 2025-12-02 05:01:42,119] Trial 16 finished with value: 0.4608472400513479 and parameters: {'max_depth': 8, 'learning_rate': 0.2941709733167641, 'n_estimators': 736, 'subsample': 0.7009499292570431, 'colsample_bytree': 0.6528253280059872, 'min_child_weight': 6, 'gamma': 0.24801325939092797, 'reg_alpha': 1.0937759376227042e-08, 'reg_lambda': 0.06061213334309951, 'max_delta_step': 10}. Best is trial 10 with value: 0.5295250320924262.

Best trial: 10. Best value: 0.529525:  32%|███▏      | 16/50 [03:34<07:11, 12.70s/it]

[I 2025-12-02 05:01:53,591] Trial 15 finished with value: 0.5237483953786906 and parameters: {'max_depth': 8, 'learning_rate': 0.012813099049410448, 'n_estimators': 724, 'subsample': 0.7103245447260238, 'colsample_bytree': 0.8702174695821026, 'min_child_weight': 6, 'gamma': 0.1066214858608151, 'reg_alpha': 1.931905731629602e-08, 'reg_lambda': 0.030130558248209097, 'max_delta_step': 10}. Best is trial 10 with value: 0.5295250320924262.

Best trial: 10. Best value: 0.529525:  34%|███▍      | 17/50 [03:38<05:34, 10.13s/it]

[I 2025-12-02 05:01:57,761] Trial 18 finished with value: 0.42041078305519897 and parameters: {'max_depth': 7, 'learning_rate': 0.17214445082301466, 'n_estimators': 215, 'subsample': 0.6672997029374834, 'colsample_bytree': 0.5031835388913022, 'min_child_weight': 4, 'gamma': 1.1610421554160049, 'reg_alpha': 1.377816270858139e-08, 'reg_lambda': 0.00037940002005604006, 'max_delta_step': 10}. Best is trial 10 with value: 0.5295250320924262.

Best trial: 10. Best value: 0.529525:  36%|███▌      | 18/50 [03:45<04:47,  8.98s/it]

[I 2025-12-02 05:02:04,070] Trial 13 finished with value: 0.4974326059050064 and parameters: {'max_depth': 8, 'learning_rate': 0.012663796643523009, 'n_estimators': 740, 'subsample': 0.7045677261147649, 'colsample_bytree': 0.8905714646625589, 'min_child_weight': 5, 'gamma': 0.07127464762370295, 'reg_alpha': 2.3794938251130832e-08, 'reg_lambda': 0.013841753799669376, 'max_delta_step': 10}. Best is trial 10 with value: 0.5295250320924262.

Best trial: 10. Best value: 0.529525:  38%|███▊      | 19/50 [03:55<04:53,  9.48s/it]

[I 2025-12-02 05:02:14,700] Trial 17 finished with value: 0.5154043645699615 and parameters: {'max_depth': 8, 'learning_rate': 0.2936755540857749, 'n_estimators': 761, 'subsample': 0.6985752200610472, 'colsample_bytree': 0.5013226930317913, 'min_child_weight': 6, 'gamma': 0.12820890749724834, 'reg_alpha': 6.422456816745584e-08, 'reg_lambda': 0.0003523403935522649, 'max_delta_step': 10}. Best is trial 10 with value: 0.5295250320924262.

Best trial: 10. Best value: 0.529525:  40%|████      | 20/50 [04:00<04:00,  8.01s/it]

[I 2025-12-02 05:02:19,302] Trial 21 pruned.

Best trial: 10. Best value: 0.529525:  42%|████▏     | 21/50 [04:01<02:48,  5.81s/it]

[I 2025-12-02 05:02:19,973] Trial 20 pruned.

Best trial: 10. Best value: 0.529525:  44%|████▍     | 22/50 [04:09<03:07,  6.70s/it]

[I 2025-12-02 05:02:28,745] Trial 22 pruned.

Best trial: 10. Best value: 0.529525:  46%|████▌     | 23/50 [04:10<02:13,  4.95s/it]

[I 2025-12-02 05:02:29,605] Trial 23 pruned.

Best trial: 10. Best value: 0.529525:  48%|████▊     | 24/50 [04:28<03:46,  8.72s/it]

[I 2025-12-02 05:02:47,114] Trial 24 finished with value: 0.4486521181001284 and parameters: {'max_depth': 7, 'learning_rate': 0.20437190419499496, 'n_estimators': 528, 'subsample': 0.8437114008497519, 'colsample_bytree': 0.5509198217761826, 'min_child_weight': 6, 'gamma': 0.8518032006119349, 'reg_alpha': 1.788063846402805e-07, 'reg_lambda': 8.949725091061747e-05, 'max_delta_step': 9}. Best is trial 10 with value: 0.5295250320924262.

Best trial: 10. Best value: 0.529525:  50%|█████     | 25/50 [04:37<03:45,  9.01s/it]

[I 2025-12-02 05:02:56,813] Trial 25 finished with value: 0.5237483953786906 and parameters: {'max_depth': 7, 'learning_rate': 0.21128678328899322, 'n_estimators': 560, 'subsample': 0.855915443558102, 'colsample_bytree': 0.5002285646361946, 'min_child_weight': 6, 'gamma': 0.548086895140107, 'reg_alpha': 3.4554843739140313e-06, 'reg_lambda': 4.453252551750473e-05, 'max_delta_step': 9}. Best is trial 10 with value: 0.5295250320924262.

Best trial: 10. Best value: 0.529525:  52%|█████▏    | 26/50 [04:42<03:03,  7.63s/it]

[I 2025-12-02 05:03:01,229] Trial 19 finished with value: 0.48523748395378685 and parameters: {'max_depth': 7, 'learning_rate': 0.02299242047761322, 'n_estimators': 891, 'subsample': 0.7510525767505118, 'colsample_bytree': 0.5069854744462021, 'min_child_weight': 4, 'gamma': 0.9892469833507347, 'reg_alpha': 0.00027302535535570296, 'reg_lambda': 1.6373891686086864e-08, 'max_delta_step': 10}. Best is trial 10 with value: 0.5295250320924262.

Best trial: 10. Best value: 0.529525:  54%|█████▍    | 27/50 [04:47<02:36,  6.79s/it]

[I 2025-12-02 05:03:06,069] Trial 28 pruned.

Best trial: 10. Best value: 0.529525:  56%|█████▌    | 28/50 [04:50<02:06,  5.74s/it]

[I 2025-12-02 05:03:09,333] Trial 29 pruned.

Best trial: 10. Best value: 0.529525:  58%|█████▊    | 29/50 [04:50<01:26,  4.12s/it]

[I 2025-12-02 05:03:09,691] Trial 26 finished with value: 0.46277278562259305 and parameters: {'max_depth': 9, 'learning_rate': 0.1753058875386334, 'n_estimators': 797, 'subsample': 0.6235643807571566, 'colsample_bytree': 0.5083546462407207, 'min_child_weight': 6, 'gamma': 0.5215499299553554, 'reg_alpha': 3.6848145118060646e-06, 'reg_lambda': 7.2470917699845e-05, 'max_delta_step': 9}. Best is trial 10 with value: 0.5295250320924262.

Best trial: 10. Best value: 0.529525:  60%|██████    | 30/50 [04:57<01:37,  4.86s/it]

[I 2025-12-02 05:03:16,275] Trial 31 pruned.

Best trial: 10. Best value: 0.529525:  62%|██████▏   | 31/50 [04:58<01:08,  3.63s/it]

[I 2025-12-02 05:03:17,026] Trial 32 pruned.

Best trial: 10. Best value: 0.529525:  64%|██████▍   | 32/50 [05:14<02:14,  7.47s/it]

[I 2025-12-02 05:03:33,445] Trial 33 finished with value: 0.48908857509627723 and parameters: {'max_depth': 4, 'learning_rate': 0.09341852158092015, 'n_estimators': 353, 'subsample': 0.8154705975608574, 'colsample_bytree': 0.5752911060787984, 'min_child_weight': 9, 'gamma': 4.1553269886215105, 'reg_alpha': 2.5686243918101145e-05, 'reg_lambda': 0.7872299114818271, 'max_delta_step': 4}. Best is trial 10 with value: 0.5295250320924262.

Best trial: 10. Best value: 0.529525:  66%|██████▌   | 33/50 [05:19<01:54,  6.76s/it]

[I 2025-12-02 05:03:38,542] Trial 27 finished with value: 0.4833119383825417 and parameters: {'max_depth': 9, 'learning_rate': 0.039176987078750704, 'n_estimators': 818, 'subsample': 0.6371699425610172, 'colsample_bytree': 0.6708672791603947, 'min_child_weight': 5, 'gamma': 1.5347694870361515, 'reg_alpha': 4.877262862404012e-06, 'reg_lambda': 0.002523700764362255, 'max_delta_step': 9}. Best is trial 10 with value: 0.5295250320924262.

Best trial: 30. Best value: 0.629012:  68%|██████▊   | 34/50 [05:26<01:48,  6.79s/it]

[I 2025-12-02 05:03:45,428] Trial 30 finished with value: 0.6290115532734275 and parameters: {'max_depth': 9, 'learning_rate': 0.14287634833794918, 'n_estimators': 798, 'subsample': 0.8999391831761219, 'colsample_bytree': 0.5794384663845864, 'min_child_weight': 7, 'gamma': 0.5243754862077183, 'reg_alpha': 3.4524382560085093e-06, 'reg_lambda': 0.003066195757047222, 'max_delta_step': 7}. Best is trial 30 with value: 0.6290115532734275.

Best trial: 30. Best value: 0.629012:  70%|███████   | 35/50 [05:34<01:49,  7.28s/it]

[I 2025-12-02 05:03:53,859] Trial 37 pruned.

Best trial: 30. Best value: 0.629012:  72%|███████▏  | 36/50 [05:42<01:42,  7.30s/it]

[I 2025-12-02 05:04:01,205] Trial 34 finished with value: 0.521181001283697 and parameters: {'max_depth': 8, 'learning_rate': 0.2263600201493153, 'n_estimators': 994, 'subsample': 0.7244580008718232, 'colsample_bytree': 0.5573000465892125, 'min_child_weight': 9, 'gamma': 0.004451105016671106, 'reg_alpha': 8.087196906696e-08, 'reg_lambda': 0.31312547270205343, 'max_delta_step': 8}. Best is trial 30 with value: 0.6290115532734275.

Best trial: 30. Best value: 0.629012:  74%|███████▍  | 37/50 [05:42<01:09,  5.31s/it]

[I 2025-12-02 05:04:01,875] Trial 38 pruned.

Best trial: 30. Best value: 0.629012:  76%|███████▌  | 38/50 [05:59<01:44,  8.73s/it]

[I 2025-12-02 05:04:18,587] Trial 35 finished with value: 0.5783055198973043 and parameters: {'max_depth': 8, 'learning_rate': 0.25944310132002457, 'n_estimators': 1016, 'subsample': 0.7340426811987463, 'colsample_bytree': 0.5449677025698487, 'min_child_weight': 6, 'gamma': 0.24486890102920145, 'reg_alpha': 5.123518273649614e-08, 'reg_lambda': 8.58697599061989e-05, 'max_delta_step': 8}. Best is trial 30 with value: 0.6290115532734275.

Best trial: 30. Best value: 0.629012:  78%|███████▊  | 39/50 [06:04<01:23,  7.61s/it]

[I 2025-12-02 05:04:23,583] Trial 36 finished with value: 0.5378690629011553 and parameters: {'max_depth': 8, 'learning_rate': 0.23677703296265168, 'n_estimators': 1014, 'subsample': 0.7128331361841563, 'colsample_bytree': 0.5435795896245016, 'min_child_weight': 6, 'gamma': 0.007683893053751084, 'reg_alpha': 6.223594978401807e-08, 'reg_lambda': 0.3487378118676594, 'max_delta_step': 8}. Best is trial 30 with value: 0.6290115532734275.

Best trial: 30. Best value: 0.629012:  80%|████████  | 40/50 [06:15<01:25,  8.53s/it]

[I 2025-12-02 05:04:34,264] Trial 39 finished with value: 0.4871630295250321 and parameters: {'max_depth': 7, 'learning_rate': 0.13428578021639845, 'n_estimators': 660, 'subsample': 0.8908431710170834, 'colsample_bytree': 0.6486158016716896, 'min_child_weight': 7, 'gamma': 2.9493192274154243, 'reg_alpha': 6.857522110115217e-07, 'reg_lambda': 5.37570395066069e-05, 'max_delta_step': 6}. Best is trial 30 with value: 0.6290115532734275.

Best trial: 30. Best value: 0.629012:  82%|████████▏ | 41/50 [06:16<00:57,  6.34s/it]

[I 2025-12-02 05:04:35,497] Trial 40 finished with value: 0.5378690629011553 and parameters: {'max_depth': 7, 'learning_rate': 0.0742439984933919, 'n_estimators': 673, 'subsample': 0.8826635684754316, 'colsample_bytree': 0.5994314124431338, 'min_child_weight': 8, 'gamma': 3.033798060754102, 'reg_alpha': 3.37220719418875e-07, 'reg_lambda': 9.55300062239556e-08, 'max_delta_step': 6}. Best is trial 30 with value: 0.6290115532734275.

Best trial: 30. Best value: 0.629012:  84%|████████▍ | 42/50 [06:32<01:13,  9.24s/it]

[I 2025-12-02 05:04:51,502] Trial 43 pruned.

Best trial: 30. Best value: 0.629012:  86%|████████▌ | 43/50 [06:53<01:28, 12.64s/it]

[I 2025-12-02 05:05:12,064] Trial 41 finished with value: 0.5012836970474968 and parameters: {'max_depth': 9, 'learning_rate': 0.1532516094680559, 'n_estimators': 1099, 'subsample': 0.7778400192931939, 'colsample_bytree': 0.6124977460524029, 'min_child_weight': 8, 'gamma': 3.6109177826905094, 'reg_alpha': 3.02410157917834e-07, 'reg_lambda': 0.017075028774522653, 'max_delta_step': 6}. Best is trial 30 with value: 0.6290115532734275.

Best trial: 30. Best value: 0.629012:  88%|████████▊ | 44/50 [07:02<01:09, 11.54s/it]

[I 2025-12-02 05:05:21,050] Trial 42 finished with value: 0.5012836970474968 and parameters: {'max_depth': 9, 'learning_rate': 0.15670414522697115, 'n_estimators': 1136, 'subsample': 0.7802369842855091, 'colsample_bytree': 0.6069494971793451, 'min_child_weight': 8, 'gamma': 3.127671796365046, 'reg_alpha': 2.8444516437672935e-07, 'reg_lambda': 1.4412862272536122, 'max_delta_step': 6}. Best is trial 30 with value: 0.6290115532734275.

Best trial: 30. Best value: 0.629012:  90%|█████████ | 45/50 [07:04<00:44,  8.86s/it]

[I 2025-12-02 05:05:23,667] Trial 46 pruned.

Best trial: 30. Best value: 0.629012:  92%|█████████▏| 46/50 [07:10<00:31,  7.81s/it]

[I 2025-12-02 05:05:29,009] Trial 47 pruned.

Best trial: 30. Best value: 0.629012:  94%|█████████▍| 47/50 [07:12<00:18,  6.15s/it]

[I 2025-12-02 05:05:31,285] Trial 48 pruned.

Best trial: 30. Best value: 0.629012:  96%|█████████▌| 48/50 [07:13<00:09,  4.55s/it]

[I 2025-12-02 05:05:32,119] Trial 44 finished with value: 0.4871630295250321 and parameters: {'max_depth': 9, 'learning_rate': 0.16465951624160807, 'n_estimators': 1131, 'subsample': 0.785266601042192, 'colsample_bytree': 0.6018736213069985, 'min_child_weight': 8, 'gamma': 3.656235134178618, 'reg_alpha': 1.949463127323685e-07, 'reg_lambda': 2.0829213102227836e-07, 'max_delta_step': 7}. Best is trial 30 with value: 0.6290115532734275.

Best trial: 30. Best value: 0.629012:  98%|█████████▊| 49/50 [07:23<00:06,  6.19s/it]

[I 2025-12-02 05:05:42,113] Trial 45 finished with value: 0.5500641848523748 and parameters: {'max_depth': 9, 'learning_rate': 0.1009590449107354, 'n_estimators': 1069, 'subsample': 0.8928716919473825, 'colsample_bytree': 0.5775856296216582, 'min_child_weight': 8, 'gamma': 2.7762529771591, 'reg_alpha': 9.9800808330569e-07, 'reg_lambda': 5.360163374933288e-07, 'max_delta_step': 5}. Best is trial 30 with value: 0.6290115532734275.

Best trial: 30. Best value: 0.629012: 100%|██████████| 50/50 [07:42<00:00,  9.24s/it]

[I 2025-12-02 05:06:01,025] Trial 49 finished with value: 0.5481386392811296 and parameters: {'max_depth': 8, 'learning_rate': 0.08326425122043636, 'n_estimators': 951, 'subsample': 0.7346466062652728, 'colsample_bytree': 0.5850166005286087, 'min_child_weight': 7, 'gamma': 2.179633444264187, 'reg_alpha': 7.16859241312489e-08, 'reg_lambda': 1.1513119454828089e-05, 'max_delta_step': 7}. Best is trial 30 with value: 0.6290115532734275.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 05:06:04,944] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.580231:   2%|▏         | 1/50 [00:18<15:15, 18.69s/it]

[I 2025-12-02 05:06:23,627] Trial 2 finished with value: 0.5802310654685494 and parameters: {'max_depth': 6, 'learning_rate': 0.2279189766460958, 'n_estimators': 372, 'subsample': 0.7228926395678975, 'colsample_bytree': 0.892344995761474, 'min_child_weight': 8, 'gamma': 1.9170814263849216, 'reg_alpha': 5.927165376455106e-07, 'reg_lambda': 0.4932161084645771, 'max_delta_step': 9}. Best is trial 2 with value: 0.5802310654685494.

Best trial: 0. Best value: 0.629012:   4%|▍         | 2/50 [00:50<21:14, 26.56s/it]

[I 2025-12-02 05:06:55,689] Trial 0 finished with value: 0.6290115532734275 and parameters: {'max_depth': 10, 'learning_rate': 0.1733276635120159, 'n_estimators': 1212, 'subsample': 0.6255327728788276, 'colsample_bytree': 0.5337672344042168, 'min_child_weight': 6, 'gamma': 3.690134229514717, 'reg_alpha': 3.8017100309246357e-06, 'reg_lambda': 4.854248390469921e-06, 'max_delta_step': 6}. Best is trial 0 with value: 0.6290115532734275.
[I 2025-12-02 05:06:55,717] Trial 1 finished with value: 0.2894736842105263 and parameters: {'max_depth': 5, 'learning_rate': 0.29885283301954546, 'n_estimators': 1216, 'subsample': 0.5929957024958072, 'colsample_bytree': 0.6111655166378965, 'min_child_weight': 10, 'gamma': 1.9081955345358943, 'reg_alpha': 3.4085105665579906e-07, 'reg_lambda': 8.479683406754256e-08, 'max_delta_step': 5}. Best is trial 0 with value: 0.6290115532734275.

Best trial: 0. Best value: 0.629012:   8%|▊         | 4/50 [00:53<08:08, 10.62s/it]

[I 2025-12-02 05:06:57,958] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.028083397393010093, 'n_estimators': 1206, 'subsample': 0.8231216984805507, 'colsample_bytree': 0.8461878081740977, 'min_child_weight': 10, 'gamma': 3.8059567973015724, 'reg_alpha': 2.9160557137855557e-07, 'reg_lambda': 1.4428318325660868e-05, 'max_delta_step': 2}. Best is trial 0 with value: 0.6290115532734275.

Best trial: 0. Best value: 0.629012:  10%|█         | 5/50 [01:11<09:52, 13.18s/it]

[I 2025-12-02 05:07:16,854] Trial 6 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.14917744135585, 'n_estimators': 427, 'subsample': 0.7602645857849274, 'colsample_bytree': 0.8559876504944465, 'min_child_weight': 10, 'gamma': 1.9529774273091027, 'reg_alpha': 9.625684853544328, 'reg_lambda': 1.0358936965285523e-06, 'max_delta_step': 5}. Best is trial 0 with value: 0.6290115532734275.

Best trial: 0. Best value: 0.629012:  12%|█▏        | 6/50 [01:14<07:20, 10.01s/it]

[I 2025-12-02 05:07:19,702] Trial 4 finished with value: 0.6046213093709885 and parameters: {'max_depth': 5, 'learning_rate': 0.2290710579204935, 'n_estimators': 1187, 'subsample': 0.9485173626772385, 'colsample_bytree': 0.9567294341653937, 'min_child_weight': 8, 'gamma': 3.377792824999208, 'reg_alpha': 4.224374183687896, 'reg_lambda': 0.0009100432024818514, 'max_delta_step': 6}. Best is trial 0 with value: 0.6290115532734275.

Best trial: 0. Best value: 0.629012:  14%|█▍        | 7/50 [01:25<07:24, 10.35s/it]

[I 2025-12-02 05:07:30,819] Trial 5 finished with value: 0.6148908857509627 and parameters: {'max_depth': 8, 'learning_rate': 0.012686557251692999, 'n_estimators': 310, 'subsample': 0.836480846046465, 'colsample_bytree': 0.5124321021464769, 'min_child_weight': 4, 'gamma': 1.5904571349864844, 'reg_alpha': 0.10636437570564213, 'reg_lambda': 4.511475331604046e-08, 'max_delta_step': 2}. Best is trial 0 with value: 0.6290115532734275.

Best trial: 0. Best value: 0.629012:  16%|█▌        | 8/50 [01:26<05:06,  7.29s/it]

[I 2025-12-02 05:07:31,077] Trial 9 finished with value: 0.04878048780487805 and parameters: {'max_depth': 7, 'learning_rate': 0.07669751142353666, 'n_estimators': 207, 'subsample': 0.6818649404154313, 'colsample_bytree': 0.7418272826569324, 'min_child_weight': 10, 'gamma': 0.201304021041262, 'reg_alpha': 2.5440787537121513e-07, 'reg_lambda': 3.5139092963278, 'max_delta_step': 2}. Best is trial 0 with value: 0.6290115532734275.

Best trial: 0. Best value: 0.629012:  18%|█▊        | 9/50 [01:52<08:52, 12.98s/it]

[I 2025-12-02 05:07:57,215] Trial 7 finished with value: 0.6290115532734275 and parameters: {'max_depth': 4, 'learning_rate': 0.14162161493924694, 'n_estimators': 1348, 'subsample': 0.8853535579235432, 'colsample_bytree': 0.7101759942309063, 'min_child_weight': 9, 'gamma': 0.1197169037733925, 'reg_alpha': 1.0250725275119367e-06, 'reg_lambda': 0.000761314176154858, 'max_delta_step': 7}. Best is trial 0 with value: 0.6290115532734275.

Best trial: 0. Best value: 0.629012:  20%|██        | 10/50 [02:02<08:07, 12.20s/it]

[I 2025-12-02 05:08:07,588] Trial 8 finished with value: 0.15853658536585366 and parameters: {'max_depth': 9, 'learning_rate': 0.1415165612520354, 'n_estimators': 1171, 'subsample': 0.9044596795860924, 'colsample_bytree': 0.6829837972991539, 'min_child_weight': 10, 'gamma': 4.40814060560296, 'reg_alpha': 2.2381809711116794, 'reg_lambda': 0.40883784098269965, 'max_delta_step': 4}. Best is trial 0 with value: 0.6290115532734275.

Best trial: 0. Best value: 0.629012:  22%|██▏       | 11/50 [02:03<05:40,  8.72s/it]

[I 2025-12-02 05:08:08,229] Trial 10 finished with value: 0.616816431322208 and parameters: {'max_depth': 7, 'learning_rate': 0.08546508278494602, 'n_estimators': 753, 'subsample': 0.9884517622465958, 'colsample_bytree': 0.9421639148847778, 'min_child_weight': 7, 'gamma': 1.111401222904373, 'reg_alpha': 0.0004416124701378591, 'reg_lambda': 3.427812098076577e-06, 'max_delta_step': 2}. Best is trial 0 with value: 0.6290115532734275.

Best trial: 11. Best value: 0.639281:  24%|██▍       | 12/50 [02:20<07:10, 11.32s/it]

[I 2025-12-02 05:08:25,584] Trial 11 finished with value: 0.6392811296534018 and parameters: {'max_depth': 9, 'learning_rate': 0.06295958317167838, 'n_estimators': 347, 'subsample': 0.7947201971072131, 'colsample_bytree': 0.9092756605297021, 'min_child_weight': 1, 'gamma': 0.706303146714079, 'reg_alpha': 6.31001560995641e-07, 'reg_lambda': 3.735965528306971, 'max_delta_step': 8}. Best is trial 11 with value: 0.6392811296534018.

Best trial: 12. Best value: 0.667522:  26%|██▌       | 13/50 [02:31<06:54, 11.19s/it]

[I 2025-12-02 05:08:36,486] Trial 12 finished with value: 0.6675224646983312 and parameters: {'max_depth': 3, 'learning_rate': 0.013031142579150104, 'n_estimators': 625, 'subsample': 0.6864154008453891, 'colsample_bytree': 0.7739679228895676, 'min_child_weight': 6, 'gamma': 4.968930586457356, 'reg_alpha': 0.009967473528351829, 'reg_lambda': 0.013907898789363611, 'max_delta_step': 5}. Best is trial 12 with value: 0.6675224646983312.

Best trial: 12. Best value: 0.667522:  28%|██▊       | 14/50 [02:46<07:22, 12.28s/it]

[I 2025-12-02 05:08:51,296] Trial 13 finished with value: 0.6553273427471117 and parameters: {'max_depth': 3, 'learning_rate': 0.060282032875714646, 'n_estimators': 818, 'subsample': 0.5004256135912735, 'colsample_bytree': 0.5025520667021555, 'min_child_weight': 2, 'gamma': 4.8611929176722946, 'reg_alpha': 0.0001330113426959961, 'reg_lambda': 4.4799077858478564e-05, 'max_delta_step': 10}. Best is trial 12 with value: 0.6675224646983312.

Best trial: 12. Best value: 0.667522:  30%|███       | 15/50 [03:16<10:22, 17.77s/it]

[I 2025-12-02 05:09:21,880] Trial 14 finished with value: 0.6553273427471117 and parameters: {'max_depth': 3, 'learning_rate': 0.04084101640919936, 'n_estimators': 1484, 'subsample': 0.5066226089604654, 'colsample_bytree': 0.5321973454477383, 'min_child_weight': 2, 'gamma': 3.160374402189688, 'reg_alpha': 4.7076952057238663e-05, 'reg_lambda': 0.00879624799110326, 'max_delta_step': 8}. Best is trial 12 with value: 0.6675224646983312.

Best trial: 12. Best value: 0.667522:  32%|███▏      | 16/50 [03:22<08:02, 14.19s/it]

[I 2025-12-02 05:09:27,710] Trial 15 finished with value: 0.641206675224647 and parameters: {'max_depth': 10, 'learning_rate': 0.03650667582794466, 'n_estimators': 856, 'subsample': 0.5195254496596223, 'colsample_bytree': 0.5291644089253832, 'min_child_weight': 1, 'gamma': 3.164959359045725, 'reg_alpha': 5.391163484063358e-05, 'reg_lambda': 0.013009491845671774, 'max_delta_step': 10}. Best is trial 12 with value: 0.6675224646983312.

Best trial: 12. Best value: 0.667522:  34%|███▍      | 17/50 [03:28<06:28, 11.77s/it]

[I 2025-12-02 05:09:33,835] Trial 17 finished with value: 0.6553273427471117 and parameters: {'max_depth': 3, 'learning_rate': 0.030976561947455142, 'n_estimators': 738, 'subsample': 0.5195007598052328, 'colsample_bytree': 0.8030815817837852, 'min_child_weight': 4, 'gamma': 4.691276576652395, 'reg_alpha': 0.0010469594665836902, 'reg_lambda': 0.012711533180906509, 'max_delta_step': 10}. Best is trial 12 with value: 0.6675224646983312.

Best trial: 12. Best value: 0.667522:  36%|███▌      | 18/50 [03:34<05:17,  9.92s/it]

[I 2025-12-02 05:09:39,451] Trial 16 finished with value: 0.641206675224647 and parameters: {'max_depth': 3, 'learning_rate': 0.032634979723037576, 'n_estimators': 644, 'subsample': 0.5116350186372176, 'colsample_bytree': 0.7819795108993827, 'min_child_weight': 1, 'gamma': 4.842706343611262, 'reg_alpha': 0.0005091640711447343, 'reg_lambda': 0.27191139054834956, 'max_delta_step': 10}. Best is trial 12 with value: 0.6675224646983312.

Best trial: 18. Best value: 0.681643:  38%|███▊      | 19/50 [04:10<09:05, 17.61s/it]

[I 2025-12-02 05:10:14,975] Trial 18 finished with value: 0.6816431322207959 and parameters: {'max_depth': 3, 'learning_rate': 0.010991947789436653, 'n_estimators': 690, 'subsample': 0.502907250074368, 'colsample_bytree': 0.8004131329840869, 'min_child_weight': 4, 'gamma': 4.91766294518346, 'reg_alpha': 0.003703891146769642, 'reg_lambda': 0.03401498114988628, 'max_delta_step': 10}. Best is trial 18 with value: 0.6816431322207959.

Best trial: 18. Best value: 0.681643:  40%|████      | 20/50 [04:16<07:12, 14.40s/it]

[I 2025-12-02 05:10:21,911] Trial 20 finished with value: 0.6675224646983312 and parameters: {'max_depth': 4, 'learning_rate': 0.010490329868328433, 'n_estimators': 573, 'subsample': 0.5989021390278351, 'colsample_bytree': 0.6471024733323202, 'min_child_weight': 4, 'gamma': 4.998533839312745, 'reg_alpha': 0.007127179205591113, 'reg_lambda': 6.813472396840055e-05, 'max_delta_step': 4}. Best is trial 18 with value: 0.6816431322207959.

Best trial: 18. Best value: 0.681643:  42%|████▏     | 21/50 [04:28<06:29, 13.43s/it]

[I 2025-12-02 05:10:33,070] Trial 19 finished with value: 0.6290115532734275 and parameters: {'max_depth': 3, 'learning_rate': 0.01145392954178902, 'n_estimators': 651, 'subsample': 0.5889953112278326, 'colsample_bytree': 0.8129036696635208, 'min_child_weight': 3, 'gamma': 4.918694534120947, 'reg_alpha': 0.0038469354326306883, 'reg_lambda': 5.785381187240627e-05, 'max_delta_step': 0}. Best is trial 18 with value: 0.6816431322207959.

Best trial: 18. Best value: 0.681643:  44%|████▍     | 22/50 [04:36<05:35, 11.97s/it]

[I 2025-12-02 05:10:41,634] Trial 21 finished with value: 0.6797175866495507 and parameters: {'max_depth': 4, 'learning_rate': 0.016037094832020923, 'n_estimators': 989, 'subsample': 0.6079788020256272, 'colsample_bytree': 0.6148919571447056, 'min_child_weight': 4, 'gamma': 4.242137748273837, 'reg_alpha': 0.011079685722933065, 'reg_lambda': 7.160683086422552e-05, 'max_delta_step': 4}. Best is trial 18 with value: 0.6816431322207959.

Best trial: 18. Best value: 0.681643:  46%|████▌     | 23/50 [04:56<06:24, 14.26s/it]

[I 2025-12-02 05:11:01,226] Trial 22 finished with value: 0.6431322207958922 and parameters: {'max_depth': 4, 'learning_rate': 0.011299621822472615, 'n_estimators': 553, 'subsample': 0.5940324061106013, 'colsample_bytree': 0.9988012535746554, 'min_child_weight': 5, 'gamma': 4.189939123714685, 'reg_alpha': 0.01453768711552175, 'reg_lambda': 0.00015968958854676633, 'max_delta_step': 0}. Best is trial 18 with value: 0.6816431322207959.

Best trial: 18. Best value: 0.681643:  48%|████▊     | 24/50 [05:05<05:30, 12.70s/it]

[I 2025-12-02 05:11:10,296] Trial 24 finished with value: 0.6675224646983312 and parameters: {'max_depth': 4, 'learning_rate': 0.017768206060152614, 'n_estimators': 538, 'subsample': 0.6487850469924739, 'colsample_bytree': 0.6485176787888924, 'min_child_weight': 5, 'gamma': 4.061366263151115, 'reg_alpha': 0.02244951860494253, 'reg_lambda': 0.003933698128309942, 'max_delta_step': 4}. Best is trial 18 with value: 0.6816431322207959.

Best trial: 18. Best value: 0.681643:  50%|█████     | 25/50 [05:14<04:53, 11.72s/it]

[I 2025-12-02 05:11:19,734] Trial 27 pruned.

Best trial: 18. Best value: 0.681643:  52%|█████▏    | 26/50 [05:23<04:19, 10.83s/it]

[I 2025-12-02 05:11:28,490] Trial 23 finished with value: 0.6553273427471117 and parameters: {'max_depth': 4, 'learning_rate': 0.01706268888984132, 'n_estimators': 991, 'subsample': 0.6577701251533703, 'colsample_bytree': 0.9917800302824267, 'min_child_weight': 5, 'gamma': 4.161845984969209, 'reg_alpha': 1.6751397599689182e-08, 'reg_lambda': 0.03153373549223291, 'max_delta_step': 4}. Best is trial 18 with value: 0.6816431322207959.

Best trial: 18. Best value: 0.681643:  54%|█████▍    | 27/50 [05:31<03:51, 10.07s/it]

[I 2025-12-02 05:11:36,784] Trial 25 finished with value: 0.6816431322207959 and parameters: {'max_depth': 4, 'learning_rate': 0.0179816578062671, 'n_estimators': 968, 'subsample': 0.6655293445539945, 'colsample_bytree': 0.611919060553982, 'min_child_weight': 5, 'gamma': 4.112080104293817, 'reg_alpha': 0.06219886932826049, 'reg_lambda': 0.0023727284529814407, 'max_delta_step': 4}. Best is trial 18 with value: 0.6816431322207959.

Best trial: 18. Best value: 0.681643:  56%|█████▌    | 28/50 [05:46<04:09, 11.35s/it]

[I 2025-12-02 05:11:51,121] Trial 26 finished with value: 0.6797175866495507 and parameters: {'max_depth': 5, 'learning_rate': 0.01954405145319459, 'n_estimators': 935, 'subsample': 0.6522254503485153, 'colsample_bytree': 0.6088091317166867, 'min_child_weight': 6, 'gamma': 4.225348478786951, 'reg_alpha': 0.11725531916203924, 'reg_lambda': 0.0033895147263797447, 'max_delta_step': 4}. Best is trial 18 with value: 0.6816431322207959.

Best trial: 18. Best value: 0.681643:  58%|█████▊    | 29/50 [05:54<03:38, 10.38s/it]

[I 2025-12-02 05:11:59,250] Trial 30 pruned.

Best trial: 18. Best value: 0.681643:  60%|██████    | 30/50 [06:22<05:15, 15.78s/it]

[I 2025-12-02 05:12:27,633] Trial 28 finished with value: 0.6675224646983312 and parameters: {'max_depth': 6, 'learning_rate': 0.016784879355668667, 'n_estimators': 951, 'subsample': 0.5586888600790018, 'colsample_bytree': 0.7269709170467644, 'min_child_weight': 3, 'gamma': 4.422371815872293, 'reg_alpha': 0.17824036612578628, 'reg_lambda': 0.049821540019299074, 'max_delta_step': 3}. Best is trial 18 with value: 0.6816431322207959.

Best trial: 18. Best value: 0.681643:  62%|██████▏   | 31/50 [06:24<03:38, 11.49s/it]

[I 2025-12-02 05:12:29,120] Trial 29 finished with value: 0.6675224646983312 and parameters: {'max_depth': 6, 'learning_rate': 0.02151817723900522, 'n_estimators': 978, 'subsample': 0.5635368829551873, 'colsample_bytree': 0.5789210624465201, 'min_child_weight': 3, 'gamma': 4.422914582747854, 'reg_alpha': 0.21962048727702158, 'reg_lambda': 0.0019190546571569533, 'max_delta_step': 3}. Best is trial 18 with value: 0.6816431322207959.

Best trial: 18. Best value: 0.681643:  64%|██████▍   | 32/50 [06:31<03:05, 10.32s/it]

[I 2025-12-02 05:12:36,712] Trial 33 pruned.

Best trial: 18. Best value: 0.681643:  66%|██████▌   | 33/50 [06:32<02:08,  7.54s/it]

[I 2025-12-02 05:12:37,761] Trial 34 pruned.

Best trial: 18. Best value: 0.681643:  68%|██████▊   | 34/50 [06:46<02:28,  9.28s/it]

[I 2025-12-02 05:12:51,112] Trial 31 finished with value: 0.6797175866495507 and parameters: {'max_depth': 6, 'learning_rate': 0.026379766770675238, 'n_estimators': 1024, 'subsample': 0.5719438815272088, 'colsample_bytree': 0.5712082283696053, 'min_child_weight': 3, 'gamma': 2.758033346155664, 'reg_alpha': 0.001953046345495692, 'reg_lambda': 0.0005613346589358285, 'max_delta_step': 3}. Best is trial 18 with value: 0.6816431322207959.

Best trial: 18. Best value: 0.681643:  70%|███████   | 35/50 [07:09<03:23, 13.54s/it]

[I 2025-12-02 05:13:14,589] Trial 32 finished with value: 0.641206675224647 and parameters: {'max_depth': 6, 'learning_rate': 0.014600552208338917, 'n_estimators': 1098, 'subsample': 0.5636235582026115, 'colsample_bytree': 0.5675608649347488, 'min_child_weight': 3, 'gamma': 3.724596982107082, 'reg_alpha': 0.6662641183934918, 'reg_lambda': 6.16272367313455e-07, 'max_delta_step': 6}. Best is trial 18 with value: 0.6816431322207959.

Best trial: 18. Best value: 0.681643:  72%|███████▏  | 36/50 [07:23<03:12, 13.77s/it]

[I 2025-12-02 05:13:28,883] Trial 35 finished with value: 0.6553273427471117 and parameters: {'max_depth': 5, 'learning_rate': 0.015730451250833735, 'n_estimators': 861, 'subsample': 0.6250027151865397, 'colsample_bytree': 0.6461435437205898, 'min_child_weight': 5, 'gamma': 3.8357253801521125, 'reg_alpha': 0.0367612239016693, 'reg_lambda': 0.0002599191683429581, 'max_delta_step': 1}. Best is trial 18 with value: 0.6816431322207959.

Best trial: 18. Best value: 0.681643:  74%|███████▍  | 37/50 [07:27<02:19, 10.76s/it]

[I 2025-12-02 05:13:32,633] Trial 36 finished with value: 0.6816431322207959 and parameters: {'max_depth': 5, 'learning_rate': 0.014482253966870286, 'n_estimators': 902, 'subsample': 0.6294868024339504, 'colsample_bytree': 0.6336632181683328, 'min_child_weight': 5, 'gamma': 2.649171793402436, 'reg_alpha': 0.002631719518223618, 'reg_lambda': 0.0034153249720994656, 'max_delta_step': 5}. Best is trial 18 with value: 0.6816431322207959.

Best trial: 18. Best value: 0.681643:  76%|███████▌  | 38/50 [07:32<01:48,  9.06s/it]

[I 2025-12-02 05:13:37,730] Trial 39 pruned.

Best trial: 18. Best value: 0.681643:  78%|███████▊  | 39/50 [07:39<01:32,  8.43s/it]

[I 2025-12-02 05:13:44,682] Trial 37 finished with value: 0.6553273427471117 and parameters: {'max_depth': 5, 'learning_rate': 0.014570263341933506, 'n_estimators': 843, 'subsample': 0.6266613481061835, 'colsample_bytree': 0.6286483119761357, 'min_child_weight': 5, 'gamma': 4.066237207522974, 'reg_alpha': 0.7548995390664898, 'reg_lambda': 0.004314798819953112, 'max_delta_step': 1}. Best is trial 18 with value: 0.6816431322207959.

Best trial: 38. Best value: 0.732349:  80%|████████  | 40/50 [07:56<01:48, 10.88s/it]

[I 2025-12-02 05:14:01,292] Trial 38 finished with value: 0.7323491655969192 and parameters: {'max_depth': 5, 'learning_rate': 0.04355708623275443, 'n_estimators': 892, 'subsample': 0.6169158652197596, 'colsample_bytree': 0.6269946775854048, 'min_child_weight': 5, 'gamma': 3.994018770870782, 'reg_alpha': 0.03681153734395601, 'reg_lambda': 0.002127939749490448, 'max_delta_step': 5}. Best is trial 38 with value: 0.7323491655969192.

Best trial: 38. Best value: 0.732349:  82%|████████▏ | 41/50 [08:01<01:23,  9.31s/it]

[I 2025-12-02 05:14:06,917] Trial 43 pruned.

Best trial: 38. Best value: 0.732349:  84%|████████▍ | 42/50 [08:56<03:02, 22.80s/it]

[I 2025-12-02 05:15:01,193] Trial 40 finished with value: 0.6797175866495507 and parameters: {'max_depth': 4, 'learning_rate': 0.012461988735831783, 'n_estimators': 1300, 'subsample': 0.7202472479420058, 'colsample_bytree': 0.6832332208160542, 'min_child_weight': 4, 'gamma': 2.2465167117570854, 'reg_alpha': 0.003148322352056518, 'reg_lambda': 1.2475567356217015e-05, 'max_delta_step': 7}. Best is trial 38 with value: 0.7323491655969192.

Best trial: 38. Best value: 0.732349:  86%|████████▌ | 43/50 [08:57<01:53, 16.27s/it]

[I 2025-12-02 05:15:02,230] Trial 41 finished with value: 0.6797175866495507 and parameters: {'max_depth': 4, 'learning_rate': 0.013277251518230426, 'n_estimators': 1300, 'subsample': 0.6265540270833254, 'colsample_bytree': 0.6887577448921561, 'min_child_weight': 4, 'gamma': 2.4681394748086527, 'reg_alpha': 0.002577758914432913, 'reg_lambda': 1.3523673098983583e-05, 'max_delta_step': 7}. Best is trial 38 with value: 0.7323491655969192.

Best trial: 38. Best value: 0.732349:  88%|████████▊ | 44/50 [09:07<01:26, 14.49s/it]

[I 2025-12-02 05:15:12,559] Trial 45 pruned.

Best trial: 38. Best value: 0.732349:  90%|█████████ | 45/50 [09:10<00:55, 11.13s/it]

[I 2025-12-02 05:15:15,845] Trial 42 finished with value: 0.6534017971758665 and parameters: {'max_depth': 4, 'learning_rate': 0.012440015095619754, 'n_estimators': 1313, 'subsample': 0.7539626536773858, 'colsample_bytree': 0.6781296962371104, 'min_child_weight': 4, 'gamma': 2.257772031805014, 'reg_alpha': 0.0025501230457652822, 'reg_lambda': 0.08312529478674607, 'max_delta_step': 7}. Best is trial 38 with value: 0.7323491655969192.

Best trial: 38. Best value: 0.732349:  92%|█████████▏| 46/50 [09:24<00:47, 11.97s/it]

[I 2025-12-02 05:15:29,772] Trial 44 finished with value: 0.6675224646983312 and parameters: {'max_depth': 4, 'learning_rate': 0.010388238042470842, 'n_estimators': 1278, 'subsample': 0.6092293497664527, 'colsample_bytree': 0.6929149524683825, 'min_child_weight': 4, 'gamma': 4.68428321279533, 'reg_alpha': 0.004441080721099613, 'reg_lambda': 7.582598780555892e-06, 'max_delta_step': 5}. Best is trial 38 with value: 0.7323491655969192.

Best trial: 38. Best value: 0.732349:  94%|█████████▍| 47/50 [09:30<00:30, 10.18s/it]

[I 2025-12-02 05:15:35,788] Trial 49 pruned.

Best trial: 38. Best value: 0.732349:  96%|█████████▌| 48/50 [09:50<00:26, 13.07s/it]

[I 2025-12-02 05:15:55,602] Trial 48 finished with value: 0.6675224646983312 and parameters: {'max_depth': 3, 'learning_rate': 0.027593225128286075, 'n_estimators': 690, 'subsample': 0.6627845200053686, 'colsample_bytree': 0.8467444655909329, 'min_child_weight': 5, 'gamma': 1.5598360111666283, 'reg_alpha': 0.00915939158269731, 'reg_lambda': 0.0015236747562372727, 'max_delta_step': 5}. Best is trial 38 with value: 0.7323491655969192.

Best trial: 38. Best value: 0.732349:  98%|█████████▊| 49/50 [09:52<00:09,  9.69s/it]

[I 2025-12-02 05:15:57,391] Trial 46 finished with value: 0.6675224646983312 and parameters: {'max_depth': 4, 'learning_rate': 0.010307495578722521, 'n_estimators': 716, 'subsample': 0.7595249818842891, 'colsample_bytree': 0.8323820673811827, 'min_child_weight': 5, 'gamma': 4.625802335486821, 'reg_alpha': 0.05701474061363137, 'reg_lambda': 0.09099585113606659, 'max_delta_step': 5}. Best is trial 38 with value: 0.7323491655969192.

Best trial: 38. Best value: 0.732349: 100%|██████████| 50/50 [09:59<00:00, 12.00s/it]

[I 2025-12-02 05:16:04,728] Trial 47 finished with value: 0.6938382541720154 and parameters: {'max_depth': 3, 'learning_rate': 0.04643820895116344, 'n_estimators': 1130, 'subsample': 0.5391522779914929, 'colsample_bytree': 0.8284060054912841, 'min_child_weight': 5, 'gamma': 1.5649176243658462, 'reg_alpha': 0.013954045470693269, 'reg_lambda': 0.0015024510677049264, 'max_delta_step': 5}. Best is trial 38 with value: 0.7323491655969192.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 05:16:11,372] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 59, Test size: 15
Using Leave-One-Out CV with 59 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.898684:   2%|▏         | 1/50 [00:43<35:53, 43.95s/it]

[I 2025-12-02 05:16:55,316] Trial 2 finished with value: 0.8986842105263158 and parameters: {'max_depth': 6, 'learning_rate': 0.2099937316782063, 'n_estimators': 1063, 'subsample': 0.6272982231429829, 'colsample_bytree': 0.5773689265765496, 'min_child_weight': 5, 'gamma': 3.4034967135006844, 'reg_alpha': 6.316191002558452e-06, 'reg_lambda': 3.895760763974248e-06, 'max_delta_step': 0}. Best is trial 2 with value: 0.8986842105263158.

Best trial: 2. Best value: 0.898684:   4%|▍         | 2/50 [00:44<14:44, 18.43s/it]

[I 2025-12-02 05:16:55,874] Trial 3 finished with value: 0.8460526315789474 and parameters: {'max_depth': 9, 'learning_rate': 0.15232675039241955, 'n_estimators': 809, 'subsample': 0.7273507366691853, 'colsample_bytree': 0.8626925604854315, 'min_child_weight': 2, 'gamma': 4.665699217139946, 'reg_alpha': 6.557631477285909e-07, 'reg_lambda': 0.020235628399016273, 'max_delta_step': 5}. Best is trial 2 with value: 0.8986842105263158.

Best trial: 2. Best value: 0.898684:   6%|▌         | 3/50 [01:00<13:39, 17.43s/it]

[I 2025-12-02 05:17:12,120] Trial 0 finished with value: 0.475 and parameters: {'max_depth': 8, 'learning_rate': 0.09799567318477072, 'n_estimators': 1435, 'subsample': 0.5240110802244633, 'colsample_bytree': 0.6970659022784127, 'min_child_weight': 9, 'gamma': 3.2832208169617028, 'reg_alpha': 0.9613289405531501, 'reg_lambda': 0.00020278206078543895, 'max_delta_step': 2}. Best is trial 2 with value: 0.8986842105263158.

Best trial: 2. Best value: 0.898684:   8%|▊         | 4/50 [01:19<13:48, 18.00s/it]

[I 2025-12-02 05:17:30,997] Trial 1 finished with value: 0.8986842105263158 and parameters: {'max_depth': 7, 'learning_rate': 0.016000178539457847, 'n_estimators': 1400, 'subsample': 0.948734375639247, 'colsample_bytree': 0.9251707298172083, 'min_child_weight': 4, 'gamma': 3.4191327832542107, 'reg_alpha': 0.3279066125414946, 'reg_lambda': 0.37885653676177444, 'max_delta_step': 2}. Best is trial 2 with value: 0.8986842105263158.

Best trial: 2. Best value: 0.898684:  10%|█         | 5/50 [01:22<09:28, 12.63s/it]

[I 2025-12-02 05:17:34,116] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.01228618845752128, 'n_estimators': 808, 'subsample': 0.6178370560322735, 'colsample_bytree': 0.9553877028763983, 'min_child_weight': 10, 'gamma': 2.6023917204830846, 'reg_alpha': 5.242163828091451, 'reg_lambda': 1.0841308644547731e-06, 'max_delta_step': 6}. Best is trial 2 with value: 0.8986842105263158.

Best trial: 2. Best value: 0.898684:  12%|█▏        | 6/50 [02:13<18:52, 25.74s/it]

[I 2025-12-02 05:18:25,304] Trial 7 finished with value: 0.0625 and parameters: {'max_depth': 5, 'learning_rate': 0.03572151746653403, 'n_estimators': 1261, 'subsample': 0.7045508644374316, 'colsample_bytree': 0.7673866551852933, 'min_child_weight': 10, 'gamma': 1.2284592649637682, 'reg_alpha': 1.950139420340377, 'reg_lambda': 1.2968132712521452e-05, 'max_delta_step': 1}. Best is trial 2 with value: 0.8986842105263158.

Best trial: 2. Best value: 0.898684:  14%|█▍        | 7/50 [02:16<13:03, 18.22s/it]

[I 2025-12-02 05:18:28,046] Trial 8 finished with value: 0.8585526315789473 and parameters: {'max_depth': 3, 'learning_rate': 0.025838002550172073, 'n_estimators': 560, 'subsample': 0.5350376242890207, 'colsample_bytree': 0.9902485079325705, 'min_child_weight': 1, 'gamma': 3.448222668860174, 'reg_alpha': 3.4509353569783854e-05, 'reg_lambda': 2.874895197073597e-07, 'max_delta_step': 4}. Best is trial 2 with value: 0.8986842105263158.

Best trial: 2. Best value: 0.898684:  16%|█▌        | 8/50 [02:19<09:17, 13.28s/it]

[I 2025-12-02 05:18:30,742] Trial 6 finished with value: 0.8723684210526316 and parameters: {'max_depth': 4, 'learning_rate': 0.1084529171356037, 'n_estimators': 1426, 'subsample': 0.9443554013835054, 'colsample_bytree': 0.6238608759311787, 'min_child_weight': 2, 'gamma': 3.482679113335851, 'reg_alpha': 0.00032180701454545844, 'reg_lambda': 0.004920630087913566, 'max_delta_step': 4}. Best is trial 2 with value: 0.8986842105263158.

Best trial: 2. Best value: 0.898684:  18%|█▊        | 9/50 [02:20<06:32,  9.59s/it]

[I 2025-12-02 05:18:32,201] Trial 4 finished with value: 0.8723684210526316 and parameters: {'max_depth': 3, 'learning_rate': 0.013713595350565027, 'n_estimators': 1163, 'subsample': 0.8949613396094641, 'colsample_bytree': 0.570473194761868, 'min_child_weight': 1, 'gamma': 0.008059145609289331, 'reg_alpha': 0.10292867487541851, 'reg_lambda': 0.003867122540662909, 'max_delta_step': 4}. Best is trial 2 with value: 0.8986842105263158.

Best trial: 9. Best value: 0.911184:  20%|██        | 10/50 [02:37<07:48, 11.72s/it]

[I 2025-12-02 05:18:48,697] Trial 9 finished with value: 0.9111842105263157 and parameters: {'max_depth': 10, 'learning_rate': 0.043618133063101125, 'n_estimators': 336, 'subsample': 0.8958936016719848, 'colsample_bytree': 0.9749701451897459, 'min_child_weight': 4, 'gamma': 1.9085306092147036, 'reg_alpha': 0.06119385953114923, 'reg_lambda': 5.953443970344154e-07, 'max_delta_step': 3}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  22%|██▏       | 11/50 [02:50<07:49, 12.03s/it]

[I 2025-12-02 05:19:01,423] Trial 12 finished with value: 0.8447368421052632 and parameters: {'max_depth': 10, 'learning_rate': 0.23225282612398065, 'n_estimators': 650, 'subsample': 0.5648048104887529, 'colsample_bytree': 0.6384416808046193, 'min_child_weight': 4, 'gamma': 1.1929359394786947, 'reg_alpha': 0.00012655398668055435, 'reg_lambda': 0.5550865635667739, 'max_delta_step': 3}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  24%|██▍       | 12/50 [02:51<05:32,  8.75s/it]

[I 2025-12-02 05:19:02,661] Trial 13 finished with value: 0.8585526315789473 and parameters: {'max_depth': 10, 'learning_rate': 0.05249661094614761, 'n_estimators': 245, 'subsample': 0.8323003520610974, 'colsample_bytree': 0.8201641192631495, 'min_child_weight': 7, 'gamma': 1.5810436715332195, 'reg_alpha': 0.0074717375598696975, 'reg_lambda': 1.5773336554932854e-08, 'max_delta_step': 10}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  26%|██▌       | 13/50 [03:11<07:29, 12.14s/it]

[I 2025-12-02 05:19:22,621] Trial 14 finished with value: 0.8848684210526316 and parameters: {'max_depth': 8, 'learning_rate': 0.05435065280270494, 'n_estimators': 406, 'subsample': 0.8524817127427529, 'colsample_bytree': 0.8831945800285164, 'min_child_weight': 7, 'gamma': 1.9411810220553962, 'reg_alpha': 0.010715871193971379, 'reg_lambda': 1.076269963653363e-08, 'max_delta_step': 9}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  28%|██▊       | 14/50 [03:12<05:13,  8.71s/it]

[I 2025-12-02 05:19:23,405] Trial 15 finished with value: 0.8986842105263158 and parameters: {'max_depth': 8, 'learning_rate': 0.022377773418978283, 'n_estimators': 203, 'subsample': 0.9892024770399274, 'colsample_bytree': 0.9041636841679178, 'min_child_weight': 4, 'gamma': 4.66273535008655, 'reg_alpha': 0.008962856585222502, 'reg_lambda': 2.535305099433766, 'max_delta_step': 7}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  30%|███       | 15/50 [03:15<04:12,  7.21s/it]

[I 2025-12-02 05:19:27,152] Trial 11 finished with value: 0.8585526315789473 and parameters: {'max_depth': 9, 'learning_rate': 0.04729411768775396, 'n_estimators': 1313, 'subsample': 0.5890138723965381, 'colsample_bytree': 0.5767620883748499, 'min_child_weight': 5, 'gamma': 2.979454817107457, 'reg_alpha': 0.006979308025660173, 'reg_lambda': 1.75192463229478e-08, 'max_delta_step': 3}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  32%|███▏      | 16/50 [03:17<03:05,  5.45s/it]

[I 2025-12-02 05:19:28,519] Trial 10 finished with value: 0.8848684210526316 and parameters: {'max_depth': 7, 'learning_rate': 0.01985764331091748, 'n_estimators': 876, 'subsample': 0.8344587145330453, 'colsample_bytree': 0.9724486044867233, 'min_child_weight': 3, 'gamma': 0.328616504906003, 'reg_alpha': 0.030561953402482175, 'reg_lambda': 0.00043423606373198416, 'max_delta_step': 8}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  34%|███▍      | 17/50 [04:06<10:12, 18.57s/it]

[I 2025-12-02 05:20:17,603] Trial 19 finished with value: 0.9111842105263157 and parameters: {'max_depth': 7, 'learning_rate': 0.010330186045636224, 'n_estimators': 1002, 'subsample': 0.9132723288564816, 'colsample_bytree': 0.7803931945795782, 'min_child_weight': 7, 'gamma': 4.022523480614844, 'reg_alpha': 0.35211858206083035, 'reg_lambda': 0.1652914396236496, 'max_delta_step': 0}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  36%|███▌      | 18/50 [04:07<07:04, 13.27s/it]

[I 2025-12-02 05:20:18,512] Trial 17 finished with value: 0.8848684210526316 and parameters: {'max_depth': 7, 'learning_rate': 0.019181407176527297, 'n_estimators': 995, 'subsample': 0.8012271241257993, 'colsample_bytree': 0.9447894200739129, 'min_child_weight': 4, 'gamma': 2.4867326256800064, 'reg_alpha': 0.13046549272898245, 'reg_lambda': 0.0002680922722368523, 'max_delta_step': 2}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  38%|███▊      | 19/50 [04:16<06:16, 12.15s/it]

[I 2025-12-02 05:20:28,046] Trial 16 finished with value: 0.8986842105263158 and parameters: {'max_depth': 8, 'learning_rate': 0.02189555865808096, 'n_estimators': 971, 'subsample': 0.9942139536730894, 'colsample_bytree': 0.922923792804204, 'min_child_weight': 4, 'gamma': 4.522476634575319, 'reg_alpha': 1.7456145758165795e-08, 'reg_lambda': 2.995165539322949, 'max_delta_step': 7}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  40%|████      | 20/50 [04:17<04:25,  8.86s/it]

[I 2025-12-02 05:20:29,250] Trial 18 finished with value: 0.8848684210526316 and parameters: {'max_depth': 7, 'learning_rate': 0.019385705326480242, 'n_estimators': 962, 'subsample': 0.8054895687688903, 'colsample_bytree': 0.9436107305810069, 'min_child_weight': 3, 'gamma': 4.163941223451865, 'reg_alpha': 0.19415534671357682, 'reg_lambda': 7.362832576435347e-05, 'max_delta_step': 1}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  42%|████▏     | 21/50 [04:27<04:22,  9.05s/it]

[I 2025-12-02 05:20:38,738] Trial 21 finished with value: 0.8848684210526316 and parameters: {'max_depth': 5, 'learning_rate': 0.08326760825332438, 'n_estimators': 421, 'subsample': 0.8985713803207254, 'colsample_bytree': 0.7461136401932016, 'min_child_weight': 7, 'gamma': 4.2873181175499075, 'reg_alpha': 2.514198437300922e-08, 'reg_lambda': 0.07784973154194996, 'max_delta_step': 0}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  44%|████▍     | 22/50 [04:34<04:01,  8.62s/it]

[I 2025-12-02 05:20:46,351] Trial 24 pruned.

Best trial: 9. Best value: 0.911184:  46%|████▌     | 23/50 [04:46<04:18,  9.59s/it]

[I 2025-12-02 05:20:58,213] Trial 23 finished with value: 0.8848684210526316 and parameters: {'max_depth': 5, 'learning_rate': 0.08176970369486146, 'n_estimators': 618, 'subsample': 0.9010922076335226, 'colsample_bytree': 0.7767391277796564, 'min_child_weight': 7, 'gamma': 4.060120023146993, 'reg_alpha': 0.000633597686132604, 'reg_lambda': 2.331990676389775e-07, 'max_delta_step': 0}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  48%|████▊     | 24/50 [04:47<02:56,  6.80s/it]

[I 2025-12-02 05:20:58,507] Trial 22 finished with value: 0.8848684210526316 and parameters: {'max_depth': 5, 'learning_rate': 0.07655307032877687, 'n_estimators': 639, 'subsample': 0.7721232699688583, 'colsample_bytree': 0.7691172759037376, 'min_child_weight': 7, 'gamma': 4.035151789770038, 'reg_alpha': 0.0012900370648827278, 'reg_lambda': 0.04790117286011461, 'max_delta_step': 0}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  50%|█████     | 25/50 [04:50<02:27,  5.89s/it]

[I 2025-12-02 05:21:02,262] Trial 20 finished with value: 0.8848684210526316 and parameters: {'max_depth': 5, 'learning_rate': 0.0316192616940244, 'n_estimators': 988, 'subsample': 0.7743768454626654, 'colsample_bytree': 0.740010697762494, 'min_child_weight': 7, 'gamma': 4.01947628966226, 'reg_alpha': 1.486738850243808e-08, 'reg_lambda': 0.00012560572871985232, 'max_delta_step': 0}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  52%|█████▏    | 26/50 [04:59<02:38,  6.60s/it]

[I 2025-12-02 05:21:10,536] Trial 27 pruned.

Best trial: 9. Best value: 0.911184:  54%|█████▍    | 27/50 [05:00<01:53,  4.92s/it]

[I 2025-12-02 05:21:11,527] Trial 26 pruned.

Best trial: 9. Best value: 0.911184:  56%|█████▌    | 28/50 [05:05<01:54,  5.19s/it]

[I 2025-12-02 05:21:17,344] Trial 28 pruned.

Best trial: 9. Best value: 0.911184:  58%|█████▊    | 29/50 [05:28<03:38, 10.40s/it]

[I 2025-12-02 05:21:39,911] Trial 25 finished with value: 0.8848684210526316 and parameters: {'max_depth': 5, 'learning_rate': 0.03424694780384719, 'n_estimators': 1129, 'subsample': 0.9533741707594343, 'colsample_bytree': 0.8363318743559581, 'min_child_weight': 8, 'gamma': 2.313226108830426, 'reg_alpha': 0.0009683804855905553, 'reg_lambda': 7.8385674157968666, 'max_delta_step': 2}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  60%|██████    | 30/50 [05:57<05:17, 15.86s/it]

[I 2025-12-02 05:22:08,512] Trial 29 finished with value: 0.8585526315789473 and parameters: {'max_depth': 10, 'learning_rate': 0.014613785395431548, 'n_estimators': 1308, 'subsample': 0.8659494593139364, 'colsample_bytree': 0.5039297903155723, 'min_child_weight': 8, 'gamma': 2.808978138504096, 'reg_alpha': 0.06960445677179226, 'reg_lambda': 6.891890120779745, 'max_delta_step': 3}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  62%|██████▏   | 31/50 [05:57<03:35, 11.33s/it]

[I 2025-12-02 05:22:09,265] Trial 30 finished with value: 0.8585526315789473 and parameters: {'max_depth': 9, 'learning_rate': 0.014921489264468745, 'n_estimators': 1345, 'subsample': 0.8595208831547361, 'colsample_bytree': 0.5207619596331022, 'min_child_weight': 8, 'gamma': 2.9015189690467635, 'reg_alpha': 0.03527324077917519, 'reg_lambda': 0.002299268289072587, 'max_delta_step': 3}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  64%|██████▍   | 32/50 [06:04<03:00, 10.01s/it]

[I 2025-12-02 05:22:16,196] Trial 31 finished with value: 0.8848684210526316 and parameters: {'max_depth': 10, 'learning_rate': 0.010007009823445653, 'n_estimators': 1349, 'subsample': 0.8843706801268004, 'colsample_bytree': 0.7037329112280937, 'min_child_weight': 9, 'gamma': 2.7741179307083668, 'reg_alpha': 0.04772008043823699, 'reg_lambda': 0.001915994901514696, 'max_delta_step': 3}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  66%|██████▌   | 33/50 [06:37<04:47, 16.88s/it]

[I 2025-12-02 05:22:49,118] Trial 32 finished with value: 0.8848684210526316 and parameters: {'max_depth': 9, 'learning_rate': 0.010267123672343753, 'n_estimators': 1488, 'subsample': 0.8744259508494907, 'colsample_bytree': 0.9039542906379753, 'min_child_weight': 8, 'gamma': 3.0667427445799618, 'reg_alpha': 0.5046275406033084, 'reg_lambda': 0.0016573689005483913, 'max_delta_step': 3}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  68%|██████▊   | 34/50 [06:48<04:00, 15.02s/it]

[I 2025-12-02 05:22:59,793] Trial 35 finished with value: 0.8585526315789473 and parameters: {'max_depth': 7, 'learning_rate': 0.2427364706904906, 'n_estimators': 1055, 'subsample': 0.6904920314136951, 'colsample_bytree': 0.6674118395194576, 'min_child_weight': 5, 'gamma': 4.998496807992568, 'reg_alpha': 5.336587251991963e-06, 'reg_lambda': 4.0424778164264225e-06, 'max_delta_step': 1}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  70%|███████   | 35/50 [06:58<03:23, 13.54s/it]

[I 2025-12-02 05:23:09,882] Trial 34 finished with value: 0.8335526315789473 and parameters: {'max_depth': 7, 'learning_rate': 0.25654695848441095, 'n_estimators': 1452, 'subsample': 0.6683486386415737, 'colsample_bytree': 0.7072671556367152, 'min_child_weight': 5, 'gamma': 3.592584132815847, 'reg_alpha': 6.593702521407628e-07, 'reg_lambda': 4.054380545645717e-06, 'max_delta_step': 1}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  72%|███████▏  | 36/50 [07:07<02:49, 12.13s/it]

[I 2025-12-02 05:23:18,733] Trial 38 pruned.

Best trial: 9. Best value: 0.911184:  74%|███████▍  | 37/50 [07:10<02:03,  9.51s/it]

[I 2025-12-02 05:23:22,127] Trial 33 finished with value: 0.9111842105263157 and parameters: {'max_depth': 9, 'learning_rate': 0.010188445685833908, 'n_estimators': 1468, 'subsample': 0.88093155758193, 'colsample_bytree': 0.7004415256041718, 'min_child_weight': 5, 'gamma': 3.1143706610578885, 'reg_alpha': 0.3667496333980131, 'reg_lambda': 0.001623450373714258, 'max_delta_step': 5}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  76%|███████▌  | 38/50 [07:13<01:28,  7.35s/it]

[I 2025-12-02 05:23:24,410] Trial 36 finished with value: 0.8585526315789473 and parameters: {'max_depth': 7, 'learning_rate': 0.18081898428707738, 'n_estimators': 752, 'subsample': 0.6543276368849597, 'colsample_bytree': 0.6345203927588827, 'min_child_weight': 5, 'gamma': 3.392330755793285, 'reg_alpha': 5.312701910453752e-06, 'reg_lambda': 1.2159164466099131e-05, 'max_delta_step': 1}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  78%|███████▊  | 39/50 [07:22<01:28,  8.02s/it]

[I 2025-12-02 05:23:34,014] Trial 41 pruned.

Best trial: 9. Best value: 0.911184:  80%|████████  | 40/50 [07:23<00:59,  5.91s/it]

[I 2025-12-02 05:23:34,985] Trial 37 finished with value: 0.8585526315789473 and parameters: {'max_depth': 4, 'learning_rate': 0.17737197684345798, 'n_estimators': 756, 'subsample': 0.6668458405116426, 'colsample_bytree': 0.5736436656040931, 'min_child_weight': 5, 'gamma': 3.6811847663284705, 'reg_alpha': 1.2054486487654006e-06, 'reg_lambda': 1.7135677296921667e-05, 'max_delta_step': 5}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  82%|████████▏ | 41/50 [07:29<00:53,  5.95s/it]

[I 2025-12-02 05:23:41,044] Trial 40 pruned.

Best trial: 9. Best value: 0.911184:  84%|████████▍ | 42/50 [07:37<00:52,  6.59s/it]

[I 2025-12-02 05:23:49,118] Trial 44 pruned.
[I 2025-12-02 05:23:49,179] Trial 42 pruned.

Best trial: 9. Best value: 0.911184:  88%|████████▊ | 44/50 [07:38<00:22,  3.67s/it]

[I 2025-12-02 05:23:49,641] Trial 43 pruned.

Best trial: 9. Best value: 0.911184:  90%|█████████ | 45/50 [07:42<00:18,  3.70s/it]

[I 2025-12-02 05:23:53,429] Trial 39 finished with value: 0.8322368421052632 and parameters: {'max_depth': 6, 'learning_rate': 0.12344343031726637, 'n_estimators': 743, 'subsample': 0.502266905706093, 'colsample_bytree': 0.5679125811066751, 'min_child_weight': 2, 'gamma': 3.296960912770961, 'reg_alpha': 5.253874918090566e-06, 'reg_lambda': 0.01776900568374433, 'max_delta_step': 4}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  92%|█████████▏| 46/50 [08:24<00:54, 13.74s/it]

[I 2025-12-02 05:24:35,507] Trial 47 finished with value: 0.8585526315789473 and parameters: {'max_depth': 10, 'learning_rate': 0.13624924242900022, 'n_estimators': 1076, 'subsample': 0.726482242878668, 'colsample_bytree': 0.6089072548597743, 'min_child_weight': 4, 'gamma': 0.978782359424148, 'reg_alpha': 2.735729296433928, 'reg_lambda': 1.5656711750024217e-06, 'max_delta_step': 5}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  94%|█████████▍| 47/50 [08:29<00:34, 11.36s/it]

[I 2025-12-02 05:24:40,496] Trial 45 finished with value: 0.8460526315789474 and parameters: {'max_depth': 6, 'learning_rate': 0.12697594769692194, 'n_estimators': 1229, 'subsample': 0.7366000249393694, 'colsample_bytree': 0.6093528764982465, 'min_child_weight': 4, 'gamma': 2.651718418805308, 'reg_alpha': 2.7632650640775082e-05, 'reg_lambda': 0.03339724230327977, 'max_delta_step': 4}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184:  96%|█████████▌| 48/50 [08:29<00:16,  8.38s/it]

[I 2025-12-02 05:24:41,227] Trial 49 pruned.

Best trial: 9. Best value: 0.911184:  98%|█████████▊| 49/50 [08:30<00:06,  6.20s/it]

[I 2025-12-02 05:24:41,970] Trial 48 finished with value: 0.8848684210526316 and parameters: {'max_depth': 10, 'learning_rate': 0.04310859393200398, 'n_estimators': 1078, 'subsample': 0.8337204450764237, 'colsample_bytree': 0.7219637114694988, 'min_child_weight': 5, 'gamma': 0.8241010456628959, 'reg_alpha': 7.625998375370692e-05, 'reg_lambda': 0.0005362722289727335, 'max_delta_step': 5}. Best is trial 9 with value: 0.9111842105263157.

Best trial: 9. Best value: 0.911184: 100%|██████████| 50/50 [08:31<00:00, 10.22s/it]

[I 2025-12-02 05:24:42,607] Trial 46 finished with value: 0.8848684210526316 and parameters: {'max_depth': 10, 'learning_rate': 0.04293681548898676, 'n_estimators': 1240, 'subsample': 0.7228048746406993, 'colsample_bytree': 0.5901617002087661, 'min_child_weight': 4, 'gamma': 0.9130214356748461, 'reg_alpha': 0.0035115099424923826, 'reg_lambda': 5.8378983295151126e-08, 'max_delta_step': 4}. Best is trial 9 with value: 0.9111842105263157.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.629012                    0.70          0.88
1     9_1         loo       0.808553                    0.60          0.42
2    17_1         loo       0.732349                    0.55          0.64
3    19_1         loo       0.911184                    0.50          0.55

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0       0.4               0.6               0.8        50          60
1       0.2               0.8               0.4        50          59
2       0.1               0.4               0.7        50          60
3       0.0               0.4               0.6        50          59

   test_size
0         15
1         15
2         15
3         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.629012                    0.70          0.88
1     9_1         loo       0.808553                    0.60          0.42
2    17_1         loo       0.732349                    0.55          0.64
3    19_1         loo       0.911184                    0.50          0.55

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0       0.4               0.6               0.8        50          60
1       0.2               0.8               0.4        50          59
2       0.1               0.4               0.7        50          60
3       0.0               0.4               0.6        50          59

   test_size
0         15
1         15
2         15
3         15

In [1588]:

datasets = task_hf_dfs_clean_pd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir="xgb_pd_hc_{CV_STRATEGY}_tasks/xgb_results_handcrafted_pd_hc_extended_{CV_STRATEGY}_tasks",
    split_param="w.cz.fnusa",
)
print(summary)

[I 2025-12-02 05:24:46,641] A new study created in memory with name: 9_1_balanced_accuracy

============================================================
Processing dataset: 9_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.718228:   2%|▏         | 1/50 [00:14<12:12, 14.96s/it]

[I 2025-12-02 05:25:01,590] Trial 3 finished with value: 0.7182284980744544 and parameters: {'max_depth': 9, 'learning_rate': 0.061790681605381835, 'n_estimators': 274, 'subsample': 0.7841488224775135, 'colsample_bytree': 0.5593510086945653, 'min_child_weight': 6, 'gamma': 3.4925851626856863, 'reg_alpha': 1.2889325163694634e-08, 'reg_lambda': 6.845708887180277e-06, 'max_delta_step': 10}. Best is trial 3 with value: 0.7182284980744544.

Best trial: 4. Best value: 0.742619:   4%|▍         | 2/50 [00:27<10:48, 13.51s/it]

[I 2025-12-02 05:25:14,087] Trial 4 finished with value: 0.7426187419768935 and parameters: {'max_depth': 8, 'learning_rate': 0.1458580008535006, 'n_estimators': 215, 'subsample': 0.6673458815568647, 'colsample_bytree': 0.9104289770549836, 'min_child_weight': 7, 'gamma': 3.6821869721111664, 'reg_alpha': 1.3166518883637837, 'reg_lambda': 7.588489746699607e-08, 'max_delta_step': 8}. Best is trial 4 with value: 0.7426187419768935.

Best trial: 4. Best value: 0.742619:   6%|▌         | 3/50 [00:33<07:56, 10.13s/it]

[I 2025-12-02 05:25:20,191] Trial 0 finished with value: 0.7182284980744544 and parameters: {'max_depth': 10, 'learning_rate': 0.0220599234372462, 'n_estimators': 616, 'subsample': 0.8075695504688893, 'colsample_bytree': 0.986487370280236, 'min_child_weight': 6, 'gamma': 2.643204165082078, 'reg_alpha': 2.1016226308452097, 'reg_lambda': 0.0002964574246147719, 'max_delta_step': 5}. Best is trial 4 with value: 0.7426187419768935.

Best trial: 4. Best value: 0.742619:   8%|▊         | 4/50 [00:48<09:05, 11.86s/it]

[I 2025-12-02 05:25:34,695] Trial 2 finished with value: 0.7426187419768935 and parameters: {'max_depth': 9, 'learning_rate': 0.012047964018237014, 'n_estimators': 904, 'subsample': 0.6771971254394614, 'colsample_bytree': 0.5706365912992165, 'min_child_weight': 5, 'gamma': 4.123893247200808, 'reg_alpha': 1.2632238122723933, 'reg_lambda': 9.447661594438143e-07, 'max_delta_step': 6}. Best is trial 4 with value: 0.7426187419768935.

Best trial: 5. Best value: 0.756739:  10%|█         | 5/50 [00:50<06:22,  8.49s/it]

[I 2025-12-02 05:25:37,224] Trial 5 finished with value: 0.7567394094993581 and parameters: {'max_depth': 6, 'learning_rate': 0.18117035258003483, 'n_estimators': 420, 'subsample': 0.9091775515528728, 'colsample_bytree': 0.7942942367804544, 'min_child_weight': 9, 'gamma': 0.761682337684218, 'reg_alpha': 0.00022530450170495607, 'reg_lambda': 0.0056003851013405066, 'max_delta_step': 8}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 5. Best value: 0.756739:  12%|█▏        | 6/50 [00:52<04:35,  6.25s/it]

[I 2025-12-02 05:25:39,119] Trial 1 finished with value: 0.7445442875481387 and parameters: {'max_depth': 4, 'learning_rate': 0.10123192654648402, 'n_estimators': 1003, 'subsample': 0.8584611703163776, 'colsample_bytree': 0.8348104478503537, 'min_child_weight': 9, 'gamma': 3.489164531675639, 'reg_alpha': 3.9533035848353e-08, 'reg_lambda': 3.209180799880138e-08, 'max_delta_step': 8}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 5. Best value: 0.756739:  14%|█▍        | 7/50 [01:13<07:56, 11.07s/it]

[I 2025-12-02 05:26:00,122] Trial 8 finished with value: 0.754813863928113 and parameters: {'max_depth': 10, 'learning_rate': 0.1095111595735959, 'n_estimators': 442, 'subsample': 0.5656571143242577, 'colsample_bytree': 0.8311589335489336, 'min_child_weight': 5, 'gamma': 0.003566635243820726, 'reg_alpha': 5.6342943858236045e-05, 'reg_lambda': 7.702466392955523, 'max_delta_step': 3}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 5. Best value: 0.756739:  16%|█▌        | 8/50 [01:24<07:44, 11.06s/it]

[I 2025-12-02 05:26:11,169] Trial 9 finished with value: 0.7041078305519897 and parameters: {'max_depth': 5, 'learning_rate': 0.02038710886207663, 'n_estimators': 593, 'subsample': 0.8933984966539686, 'colsample_bytree': 0.942971882669691, 'min_child_weight': 4, 'gamma': 4.360365009394293, 'reg_alpha': 6.926980805787247e-08, 'reg_lambda': 4.441265432605014, 'max_delta_step': 9}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 5. Best value: 0.756739:  18%|█▊        | 9/50 [01:27<05:55,  8.68s/it]

[I 2025-12-02 05:26:14,593] Trial 6 finished with value: 0.7041078305519897 and parameters: {'max_depth': 8, 'learning_rate': 0.01711791732804668, 'n_estimators': 1048, 'subsample': 0.9229735302914854, 'colsample_bytree': 0.5585930959554, 'min_child_weight': 4, 'gamma': 4.406508881851579, 'reg_alpha': 0.00015176877863159517, 'reg_lambda': 2.9576015284286287e-05, 'max_delta_step': 5}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 5. Best value: 0.756739:  20%|██        | 10/50 [01:42<06:58, 10.47s/it]

[I 2025-12-02 05:26:29,071] Trial 11 finished with value: 0.7445442875481387 and parameters: {'max_depth': 6, 'learning_rate': 0.27627553030708457, 'n_estimators': 322, 'subsample': 0.5485194150959669, 'colsample_bytree': 0.9562410656559404, 'min_child_weight': 3, 'gamma': 3.3715358812633505, 'reg_alpha': 0.09689380331979795, 'reg_lambda': 3.0956305924629125e-06, 'max_delta_step': 4}. Best is trial 5 with value: 0.7567394094993581.
[I 2025-12-02 05:26:29,164] Trial 12 pruned.

Best trial: 5. Best value: 0.756739:  24%|██▍       | 12/50 [01:54<05:14,  8.29s/it]

[I 2025-12-02 05:26:40,702] Trial 13 pruned.

Best trial: 5. Best value: 0.756739:  26%|██▌       | 13/50 [02:01<05:01,  8.15s/it]

[I 2025-12-02 05:26:48,460] Trial 7 finished with value: 0.730423620025674 and parameters: {'max_depth': 4, 'learning_rate': 0.011556642545747108, 'n_estimators': 1488, 'subsample': 0.8652158607977576, 'colsample_bytree': 0.5103004992774847, 'min_child_weight': 8, 'gamma': 3.957548814853995, 'reg_alpha': 7.460531438210715e-05, 'reg_lambda': 0.0017264864483995397, 'max_delta_step': 6}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 5. Best value: 0.756739:  28%|██▊       | 14/50 [02:10<05:00,  8.34s/it]

[I 2025-12-02 05:26:57,330] Trial 10 finished with value: 0.730423620025674 and parameters: {'max_depth': 5, 'learning_rate': 0.022178731048676757, 'n_estimators': 1074, 'subsample': 0.5281734598636061, 'colsample_bytree': 0.8891756229383542, 'min_child_weight': 3, 'gamma': 3.0230781262948274, 'reg_alpha': 1.2520772507172776e-08, 'reg_lambda': 5.743260678622874, 'max_delta_step': 0}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 5. Best value: 0.756739:  30%|███       | 15/50 [02:19<04:57,  8.50s/it]

[I 2025-12-02 05:27:06,247] Trial 15 finished with value: 0.689987163029525 and parameters: {'max_depth': 7, 'learning_rate': 0.13672169942648074, 'n_estimators': 470, 'subsample': 0.5116212107790686, 'colsample_bytree': 0.8154540021822738, 'min_child_weight': 1, 'gamma': 0.10654187452185648, 'reg_alpha': 7.157852742343252e-06, 'reg_lambda': 0.07747932000819766, 'max_delta_step': 3}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 5. Best value: 0.756739:  32%|███▏      | 16/50 [02:27<04:42,  8.30s/it]

[I 2025-12-02 05:27:14,052] Trial 16 finished with value: 0.7284980744544287 and parameters: {'max_depth': 7, 'learning_rate': 0.1496465452176993, 'n_estimators': 443, 'subsample': 0.5481936621334932, 'colsample_bytree': 0.8102037389254575, 'min_child_weight': 1, 'gamma': 0.06162435993053472, 'reg_alpha': 3.2035340503098137e-06, 'reg_lambda': 4.6244121320270715, 'max_delta_step': 3}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 5. Best value: 0.756739:  34%|███▍      | 17/50 [02:36<04:40,  8.51s/it]

[I 2025-12-02 05:27:23,067] Trial 17 finished with value: 0.754813863928113 and parameters: {'max_depth': 7, 'learning_rate': 0.15585541524753685, 'n_estimators': 475, 'subsample': 0.5853361404570647, 'colsample_bytree': 0.7943652624959558, 'min_child_weight': 1, 'gamma': 0.12383214436165661, 'reg_alpha': 1.431745228463379e-06, 'reg_lambda': 0.0940394701107555, 'max_delta_step': 3}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 5. Best value: 0.756739:  36%|███▌      | 18/50 [02:52<05:43, 10.72s/it]

[I 2025-12-02 05:27:39,200] Trial 14 finished with value: 0.7041078305519897 and parameters: {'max_depth': 7, 'learning_rate': 0.205634001816146, 'n_estimators': 1345, 'subsample': 0.5030794974462773, 'colsample_bytree': 0.7451695304764584, 'min_child_weight': 1, 'gamma': 0.023810022223961537, 'reg_alpha': 0.002798904690637619, 'reg_lambda': 0.28351396784777677, 'max_delta_step': 2}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 5. Best value: 0.756739:  38%|███▊      | 19/50 [02:58<04:49,  9.35s/it]

[I 2025-12-02 05:27:45,224] Trial 18 finished with value: 0.7163029525032092 and parameters: {'max_depth': 7, 'learning_rate': 0.04396556743020694, 'n_estimators': 736, 'subsample': 0.6094967492833201, 'colsample_bytree': 0.7863269498471693, 'min_child_weight': 7, 'gamma': 1.3680764153273475, 'reg_alpha': 1.4309539408980541e-06, 'reg_lambda': 0.1391645915636597, 'max_delta_step': 3}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 5. Best value: 0.756739:  40%|████      | 20/50 [03:06<04:24,  8.80s/it]

[I 2025-12-02 05:27:52,742] Trial 22 pruned.

Best trial: 5. Best value: 0.756739:  42%|████▏     | 21/50 [03:08<03:18,  6.86s/it]

[I 2025-12-02 05:27:54,978] Trial 19 finished with value: 0.7426187419768935 and parameters: {'max_depth': 10, 'learning_rate': 0.03371801571849578, 'n_estimators': 760, 'subsample': 0.6198112214036586, 'colsample_bytree': 0.6834351145110311, 'min_child_weight': 7, 'gamma': 1.3967315961787206, 'reg_alpha': 0.002300335941328621, 'reg_lambda': 0.16352259005377925, 'max_delta_step': 7}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 5. Best value: 0.756739:  44%|████▍     | 22/50 [03:17<03:28,  7.46s/it]

[I 2025-12-02 05:28:03,844] Trial 20 finished with value: 0.7445442875481387 and parameters: {'max_depth': 10, 'learning_rate': 0.04213045131375576, 'n_estimators': 742, 'subsample': 0.9965012703795937, 'colsample_bytree': 0.6630621450879226, 'min_child_weight': 7, 'gamma': 1.3401436036200471, 'reg_alpha': 0.003393001932076243, 'reg_lambda': 0.004917041563308336, 'max_delta_step': 7}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 5. Best value: 0.756739:  46%|████▌     | 23/50 [03:26<03:32,  7.88s/it]

[I 2025-12-02 05:28:12,712] Trial 23 finished with value: 0.7182284980744544 and parameters: {'max_depth': 6, 'learning_rate': 0.09130174296685617, 'n_estimators': 350, 'subsample': 0.7236376716017836, 'colsample_bytree': 0.6648519301395546, 'min_child_weight': 7, 'gamma': 1.260446159716727, 'reg_alpha': 0.03403209730102394, 'reg_lambda': 0.008279622881977445, 'max_delta_step': 10}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 5. Best value: 0.756739:  48%|████▊     | 24/50 [03:31<03:09,  7.28s/it]

[I 2025-12-02 05:28:18,597] Trial 24 finished with value: 0.6655969191270861 and parameters: {'max_depth': 6, 'learning_rate': 0.09663722806511008, 'n_estimators': 415, 'subsample': 0.7396750675178999, 'colsample_bytree': 0.8630400816726362, 'min_child_weight': 2, 'gamma': 0.6776780585576367, 'reg_alpha': 3.3514974171506865e-07, 'reg_lambda': 0.016692134532458054, 'max_delta_step': 4}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 5. Best value: 0.756739:  50%|█████     | 25/50 [03:32<02:14,  5.37s/it]

[I 2025-12-02 05:28:19,488] Trial 21 finished with value: 0.7182284980744544 and parameters: {'max_depth': 10, 'learning_rate': 0.04197473832289071, 'n_estimators': 733, 'subsample': 0.747053982088568, 'colsample_bytree': 0.6538903847014189, 'min_child_weight': 7, 'gamma': 1.467325336493785, 'reg_alpha': 0.0019633556285396734, 'reg_lambda': 0.0015215972606685481, 'max_delta_step': 8}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 5. Best value: 0.756739:  52%|█████▏    | 26/50 [03:39<02:18,  5.77s/it]

[I 2025-12-02 05:28:26,181] Trial 25 finished with value: 0.7284980744544287 and parameters: {'max_depth': 6, 'learning_rate': 0.10180953995483041, 'n_estimators': 400, 'subsample': 0.7309847347083814, 'colsample_bytree': 0.8634479787697751, 'min_child_weight': 2, 'gamma': 0.812493651440332, 'reg_alpha': 2.319712183762718e-07, 'reg_lambda': 0.02107125515623692, 'max_delta_step': 4}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 5. Best value: 0.756739:  54%|█████▍    | 27/50 [03:44<02:08,  5.58s/it]

[I 2025-12-02 05:28:31,334] Trial 28 finished with value: 0.7060333761232349 and parameters: {'max_depth': 8, 'learning_rate': 0.1932505525993402, 'n_estimators': 201, 'subsample': 0.603419520799084, 'colsample_bytree': 0.7796050070119346, 'min_child_weight': 5, 'gamma': 0.5941319392943565, 'reg_alpha': 2.3006424817074482e-05, 'reg_lambda': 0.9127941468635423, 'max_delta_step': 2}. Best is trial 5 with value: 0.7567394094993581.

Best trial: 26. Best value: 0.78113:  56%|█████▌    | 28/50 [03:51<02:11,  5.99s/it]

[I 2025-12-02 05:28:38,272] Trial 26 finished with value: 0.7811296534017972 and parameters: {'max_depth': 8, 'learning_rate': 0.18285676688100355, 'n_estimators': 446, 'subsample': 0.6038803256077254, 'colsample_bytree': 0.8602596463633904, 'min_child_weight': 2, 'gamma': 0.6841525110553721, 'reg_alpha': 9.504750431453167e-07, 'reg_lambda': 0.8669023544111493, 'max_delta_step': 4}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  58%|█████▊    | 29/50 [04:05<02:56,  8.38s/it]

[I 2025-12-02 05:28:52,243] Trial 27 finished with value: 0.7426187419768935 and parameters: {'max_depth': 8, 'learning_rate': 0.19165112699266632, 'n_estimators': 626, 'subsample': 0.601920293839827, 'colsample_bytree': 0.7658527477375114, 'min_child_weight': 5, 'gamma': 0.6582894287721897, 'reg_alpha': 2.110165757355645e-05, 'reg_lambda': 0.7194402872644852, 'max_delta_step': 2}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  60%|██████    | 30/50 [04:10<02:25,  7.30s/it]

[I 2025-12-02 05:28:57,003] Trial 29 finished with value: 0.7182284980744544 and parameters: {'max_depth': 8, 'learning_rate': 0.18227906324645485, 'n_estimators': 551, 'subsample': 0.5940882018727686, 'colsample_bytree': 0.7745316162502772, 'min_child_weight': 5, 'gamma': 1.8801783777873458, 'reg_alpha': 2.7524752381577216e-05, 'reg_lambda': 0.9564381476037884, 'max_delta_step': 2}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  62%|██████▏   | 31/50 [04:15<02:06,  6.66s/it]

[I 2025-12-02 05:29:02,190] Trial 30 finished with value: 0.7567394094993581 and parameters: {'max_depth': 9, 'learning_rate': 0.18840673336152255, 'n_estimators': 555, 'subsample': 0.5888136703007788, 'colsample_bytree': 0.7582463583566051, 'min_child_weight': 4, 'gamma': 4.950922741065539, 'reg_alpha': 9.347003754137254e-07, 'reg_lambda': 0.7830611667498321, 'max_delta_step': 2}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  64%|██████▍   | 32/50 [04:22<01:59,  6.63s/it]

[I 2025-12-02 05:29:08,744] Trial 31 finished with value: 0.7811296534017972 and parameters: {'max_depth': 9, 'learning_rate': 0.20561207733725906, 'n_estimators': 568, 'subsample': 0.6437983469391908, 'colsample_bytree': 0.8538388934700475, 'min_child_weight': 4, 'gamma': 2.0959948606607566, 'reg_alpha': 0.00048181121380973393, 'reg_lambda': 0.5724880405374297, 'max_delta_step': 6}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  66%|██████▌   | 33/50 [04:40<02:50, 10.06s/it]

[I 2025-12-02 05:29:26,798] Trial 32 finished with value: 0.7163029525032092 and parameters: {'max_depth': 9, 'learning_rate': 0.06870086587802411, 'n_estimators': 623, 'subsample': 0.8024756315045196, 'colsample_bytree': 0.847219627991394, 'min_child_weight': 4, 'gamma': 2.3505424404357327, 'reg_alpha': 0.0002377388816980176, 'reg_lambda': 0.00022102156014382635, 'max_delta_step': 6}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  68%|██████▊   | 34/50 [04:50<02:41, 10.07s/it]

[I 2025-12-02 05:29:36,897] Trial 34 finished with value: 0.689987163029525 and parameters: {'max_depth': 9, 'learning_rate': 0.2945959259083308, 'n_estimators': 633, 'subsample': 0.6507324209644146, 'colsample_bytree': 0.8741501295434854, 'min_child_weight': 4, 'gamma': 4.888242267984755, 'reg_alpha': 0.00040624194898921577, 'reg_lambda': 0.00016577016981209094, 'max_delta_step': 4}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  70%|███████   | 35/50 [04:56<02:14,  8.96s/it]

[I 2025-12-02 05:29:43,257] Trial 35 finished with value: 0.754813863928113 and parameters: {'max_depth': 9, 'learning_rate': 0.23991153313065663, 'n_estimators': 627, 'subsample': 0.630072905533865, 'colsample_bytree': 0.8672550136117241, 'min_child_weight': 3, 'gamma': 4.779590027944757, 'reg_alpha': 0.00042493498427080355, 'reg_lambda': 0.00014886370572895528, 'max_delta_step': 6}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  72%|███████▏  | 36/50 [05:12<02:35, 11.13s/it]

[I 2025-12-02 05:29:59,463] Trial 33 finished with value: 0.7163029525032092 and parameters: {'max_depth': 9, 'learning_rate': 0.0711986645158692, 'n_estimators': 1201, 'subsample': 0.8054523613488841, 'colsample_bytree': 0.8545813273332095, 'min_child_weight': 4, 'gamma': 2.2807032009073804, 'reg_alpha': 0.00025487352448288775, 'reg_lambda': 8.03018316142179e-05, 'max_delta_step': 6}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  74%|███████▍  | 37/50 [05:26<02:35, 11.97s/it]

[I 2025-12-02 05:30:13,406] Trial 36 finished with value: 0.7426187419768935 and parameters: {'max_depth': 9, 'learning_rate': 0.24132610969604104, 'n_estimators': 880, 'subsample': 0.6419734161171884, 'colsample_bytree': 0.8976241261684439, 'min_child_weight': 3, 'gamma': 4.87193707414385, 'reg_alpha': 0.018440960167750615, 'reg_lambda': 1.1414268022779714, 'max_delta_step': 5}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  76%|███████▌  | 38/50 [05:38<02:24, 12.01s/it]

[I 2025-12-02 05:30:25,516] Trial 37 finished with value: 0.730423620025674 and parameters: {'max_depth': 9, 'learning_rate': 0.23300382133567443, 'n_estimators': 922, 'subsample': 0.6426165220209202, 'colsample_bytree': 0.9914808977977407, 'min_child_weight': 3, 'gamma': 2.291389211724119, 'reg_alpha': 0.03771500763752181, 'reg_lambda': 1.398857642505633, 'max_delta_step': 6}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  78%|███████▊  | 39/50 [05:43<01:46,  9.71s/it]

[I 2025-12-02 05:30:29,838] Trial 38 finished with value: 0.6919127086007703 and parameters: {'max_depth': 9, 'learning_rate': 0.12348001131339793, 'n_estimators': 870, 'subsample': 0.6945075132405067, 'colsample_bytree': 0.9877510408160879, 'min_child_weight': 2, 'gamma': 2.1433764978866696, 'reg_alpha': 0.046129331115545014, 'reg_lambda': 1.28063349440959, 'max_delta_step': 9}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  80%|████████  | 40/50 [05:44<01:11,  7.19s/it]

[I 2025-12-02 05:30:31,132] Trial 40 finished with value: 0.689987163029525 and parameters: {'max_depth': 8, 'learning_rate': 0.12532372067998998, 'n_estimators': 307, 'subsample': 0.6994203126685773, 'colsample_bytree': 0.9986320088047085, 'min_child_weight': 2, 'gamma': 0.9716189882233676, 'reg_alpha': 0.3251505455999832, 'reg_lambda': 0.0008207474642346309, 'max_delta_step': 8}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  82%|████████▏ | 41/50 [05:56<01:18,  8.76s/it]

[I 2025-12-02 05:30:43,589] Trial 39 finished with value: 0.689987163029525 and parameters: {'max_depth': 8, 'learning_rate': 0.12231940401420677, 'n_estimators': 830, 'subsample': 0.6974956539193445, 'colsample_bytree': 0.9278028519242343, 'min_child_weight': 2, 'gamma': 0.9251002399007412, 'reg_alpha': 0.03160012844205033, 'reg_lambda': 1.2860798498438573, 'max_delta_step': 5}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  84%|████████▍ | 42/50 [05:57<00:50,  6.26s/it]

[I 2025-12-02 05:30:44,000] Trial 41 finished with value: 0.730423620025674 and parameters: {'max_depth': 8, 'learning_rate': 0.121734026323288, 'n_estimators': 324, 'subsample': 0.7051495018138172, 'colsample_bytree': 0.9241862758363741, 'min_child_weight': 6, 'gamma': 1.0233943932932767, 'reg_alpha': 0.28308622671226574, 'reg_lambda': 0.2835686297765209, 'max_delta_step': 9}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  86%|████████▌ | 43/50 [05:59<00:34,  4.98s/it]

[I 2025-12-02 05:30:46,007] Trial 42 finished with value: 0.754813863928113 and parameters: {'max_depth': 8, 'learning_rate': 0.16813824881787812, 'n_estimators': 281, 'subsample': 0.8511108137004344, 'colsample_bytree': 0.9201251959862569, 'min_child_weight': 6, 'gamma': 1.0143132105827406, 'reg_alpha': 6.49483443780678e-08, 'reg_lambda': 0.02794096614259782, 'max_delta_step': 5}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  88%|████████▊ | 44/50 [06:12<00:45,  7.53s/it]

[I 2025-12-02 05:30:59,482] Trial 43 finished with value: 0.730423620025674 and parameters: {'max_depth': 5, 'learning_rate': 0.1625694487744716, 'n_estimators': 522, 'subsample': 0.8491838092437839, 'colsample_bytree': 0.925616288471393, 'min_child_weight': 6, 'gamma': 2.880443352839734, 'reg_alpha': 6.157639322233799e-08, 'reg_lambda': 0.026714529477738162, 'max_delta_step': 5}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  90%|█████████ | 45/50 [06:24<00:43,  8.75s/it]

[I 2025-12-02 05:31:11,063] Trial 44 finished with value: 0.730423620025674 and parameters: {'max_depth': 10, 'learning_rate': 0.16648787253089412, 'n_estimators': 511, 'subsample': 0.5618491812446298, 'colsample_bytree': 0.8173291954505392, 'min_child_weight': 6, 'gamma': 0.38152312783558373, 'reg_alpha': 6.296918656535182e-08, 'reg_lambda': 5.468466739213151, 'max_delta_step': 1}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  92%|█████████▏| 46/50 [06:25<00:26,  6.54s/it]

[I 2025-12-02 05:31:12,442] Trial 45 finished with value: 0.730423620025674 and parameters: {'max_depth': 10, 'learning_rate': 0.1845885357446317, 'n_estimators': 522, 'subsample': 0.568158331054632, 'colsample_bytree': 0.8235489948733467, 'min_child_weight': 6, 'gamma': 0.36668315407550245, 'reg_alpha': 7.531809745427952e-05, 'reg_lambda': 9.359336734075303, 'max_delta_step': 1}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  94%|█████████▍| 47/50 [06:28<00:15,  5.27s/it]

[I 2025-12-02 05:31:14,776] Trial 48 pruned.

Best trial: 26. Best value: 0.78113:  96%|█████████▌| 48/50 [06:28<00:07,  3.81s/it]

[I 2025-12-02 05:31:15,163] Trial 46 finished with value: 0.7426187419768935 and parameters: {'max_depth': 5, 'learning_rate': 0.21281652671751158, 'n_estimators': 522, 'subsample': 0.5669257984560662, 'colsample_bytree': 0.8293034216340192, 'min_child_weight': 5, 'gamma': 0.3607921416846964, 'reg_alpha': 2.941218804356666e-07, 'reg_lambda': 9.5608935578861, 'max_delta_step': 1}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113:  98%|█████████▊| 49/50 [06:30<00:03,  3.26s/it]

[I 2025-12-02 05:31:17,134] Trial 47 finished with value: 0.730423620025674 and parameters: {'max_depth': 10, 'learning_rate': 0.21766384317186332, 'n_estimators': 369, 'subsample': 0.5714450296126429, 'colsample_bytree': 0.8211163139045214, 'min_child_weight': 5, 'gamma': 0.3486096749875924, 'reg_alpha': 7.101752770798233e-05, 'reg_lambda': 4.381680577652213, 'max_delta_step': 1}. Best is trial 26 with value: 0.7811296534017972.

Best trial: 26. Best value: 0.78113: 100%|██████████| 50/50 [06:33<00:00,  7.88s/it]

[I 2025-12-02 05:31:20,449] Trial 49 finished with value: 0.7201540436456997 and parameters: {'max_depth': 5, 'learning_rate': 0.22196910944297696, 'n_estimators': 394, 'subsample': 0.7708345633330032, 'colsample_bytree': 0.7528734915604367, 'min_child_weight': 8, 'gamma': 3.1592596494092122, 'reg_alpha': 2.5152094894063815e-07, 'reg_lambda': 0.30746033933301953, 'max_delta_step': 0}. Best is trial 26 with value: 0.7811296534017972.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 05:31:24,517] A new study created in memory with name: 15_1_balanced_accuracy

============================================================
Processing dataset: 15_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.342105:   2%|▏         | 1/50 [00:21<17:12, 21.07s/it]

[I 2025-12-02 05:31:45,583] Trial 1 finished with value: 0.34210526315789475 and parameters: {'max_depth': 4, 'learning_rate': 0.02242874697108731, 'n_estimators': 398, 'subsample': 0.6945124672753882, 'colsample_bytree': 0.736131672332601, 'min_child_weight': 10, 'gamma': 4.99255084291331, 'reg_alpha': 1.5932273101375045e-07, 'reg_lambda': 0.0004763874993358401, 'max_delta_step': 6}. Best is trial 1 with value: 0.34210526315789475.

Best trial: 1. Best value: 0.342105:   4%|▍         | 2/50 [00:52<21:54, 27.39s/it]

[I 2025-12-02 05:32:17,395] Trial 0 finished with value: 0.2894736842105263 and parameters: {'max_depth': 5, 'learning_rate': 0.030393065179799218, 'n_estimators': 1082, 'subsample': 0.6577962534238901, 'colsample_bytree': 0.5715992159314851, 'min_child_weight': 10, 'gamma': 2.004550219224608, 'reg_alpha': 0.01295908670074731, 'reg_lambda': 0.020696964093986317, 'max_delta_step': 4}. Best is trial 1 with value: 0.34210526315789475.

Best trial: 3. Best value: 0.754814:   6%|▌         | 3/50 [01:10<18:06, 23.12s/it]

[I 2025-12-02 05:32:35,431] Trial 3 finished with value: 0.754813863928113 and parameters: {'max_depth': 10, 'learning_rate': 0.019288367286120295, 'n_estimators': 1362, 'subsample': 0.9274809583736362, 'colsample_bytree': 0.7610956036538489, 'min_child_weight': 4, 'gamma': 3.1024907266602435, 'reg_alpha': 7.861521944857013e-07, 'reg_lambda': 0.6553074701253053, 'max_delta_step': 6}. Best is trial 3 with value: 0.754813863928113.

Best trial: 3. Best value: 0.754814:   8%|▊         | 4/50 [01:12<11:18, 14.75s/it]

[I 2025-12-02 05:32:37,348] Trial 2 finished with value: 0.730423620025674 and parameters: {'max_depth': 6, 'learning_rate': 0.21001092259136556, 'n_estimators': 1395, 'subsample': 0.8792386699185031, 'colsample_bytree': 0.7775311016854853, 'min_child_weight': 1, 'gamma': 1.2822070550471416, 'reg_alpha': 2.8596909669371153e-06, 'reg_lambda': 5.652263077326736e-08, 'max_delta_step': 1}. Best is trial 3 with value: 0.754813863928113.

Best trial: 3. Best value: 0.754814:  10%|█         | 5/50 [01:31<12:13, 16.29s/it]

[I 2025-12-02 05:32:56,381] Trial 4 finished with value: 0.30808729139922975 and parameters: {'max_depth': 10, 'learning_rate': 0.13952445732512117, 'n_estimators': 1396, 'subsample': 0.6945190035502811, 'colsample_bytree': 0.8057071576902619, 'min_child_weight': 10, 'gamma': 4.666491676568219, 'reg_alpha': 1.7080285561968454e-07, 'reg_lambda': 0.00010685415776788441, 'max_delta_step': 3}. Best is trial 3 with value: 0.754813863928113.

Best trial: 3. Best value: 0.754814:  12%|█▏        | 6/50 [01:57<14:09, 19.32s/it]

[I 2025-12-02 05:33:21,570] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.013207948152241675, 'n_estimators': 856, 'subsample': 0.8267409733579187, 'colsample_bytree': 0.7773821929494164, 'min_child_weight': 10, 'gamma': 0.21085323984127602, 'reg_alpha': 0.00011123645489462505, 'reg_lambda': 3.719102808260626e-05, 'max_delta_step': 5}. Best is trial 3 with value: 0.754813863928113.

Best trial: 3. Best value: 0.754814:  14%|█▍        | 7/50 [01:59<09:55, 13.86s/it]

[I 2025-12-02 05:33:24,189] Trial 6 finished with value: 0.7163029525032092 and parameters: {'max_depth': 5, 'learning_rate': 0.1180679182584595, 'n_estimators': 955, 'subsample': 0.5246477273555874, 'colsample_bytree': 0.5702121034393883, 'min_child_weight': 4, 'gamma': 4.208279911620922, 'reg_alpha': 5.172165516783066e-06, 'reg_lambda': 8.90865802905569e-06, 'max_delta_step': 5}. Best is trial 3 with value: 0.754813863928113.

Best trial: 3. Best value: 0.754814:  16%|█▌        | 8/50 [02:00<06:41,  9.57s/it]

[I 2025-12-02 05:33:24,576] Trial 5 finished with value: 0.6919127086007703 and parameters: {'max_depth': 10, 'learning_rate': 0.14311189156648613, 'n_estimators': 1331, 'subsample': 0.8477767741692157, 'colsample_bytree': 0.6411042019826663, 'min_child_weight': 9, 'gamma': 0.2144984912725012, 'reg_alpha': 0.002837381656158495, 'reg_lambda': 0.04368738936690213, 'max_delta_step': 3}. Best is trial 3 with value: 0.754813863928113.

Best trial: 3. Best value: 0.754814:  18%|█▊        | 9/50 [02:21<09:04, 13.28s/it]

[I 2025-12-02 05:33:46,028] Trial 8 finished with value: 0.754813863928113 and parameters: {'max_depth': 3, 'learning_rate': 0.02087672626205204, 'n_estimators': 914, 'subsample': 0.8369211639632609, 'colsample_bytree': 0.7446967443793401, 'min_child_weight': 3, 'gamma': 2.1044912994532474, 'reg_alpha': 0.00760361827341003, 'reg_lambda': 0.013249115932186896, 'max_delta_step': 9}. Best is trial 3 with value: 0.754813863928113.

Best trial: 3. Best value: 0.754814:  20%|██        | 10/50 [02:35<09:00, 13.52s/it]

[I 2025-12-02 05:34:00,088] Trial 9 finished with value: 0.6675224646983312 and parameters: {'max_depth': 8, 'learning_rate': 0.07575165432886062, 'n_estimators': 737, 'subsample': 0.6857081289438856, 'colsample_bytree': 0.6559464833394466, 'min_child_weight': 4, 'gamma': 2.0788643003311886, 'reg_alpha': 8.137918725819018, 'reg_lambda': 0.11581462179363221, 'max_delta_step': 9}. Best is trial 3 with value: 0.754813863928113.

Best trial: 3. Best value: 0.754814:  22%|██▏       | 11/50 [02:38<06:42, 10.33s/it]

[I 2025-12-02 05:34:03,176] Trial 11 finished with value: 0.754813863928113 and parameters: {'max_depth': 5, 'learning_rate': 0.02212324090322127, 'n_estimators': 710, 'subsample': 0.7437697508385558, 'colsample_bytree': 0.7723111019446671, 'min_child_weight': 4, 'gamma': 0.7824126227638295, 'reg_alpha': 0.09387591835776207, 'reg_lambda': 0.14182782122602342, 'max_delta_step': 6}. Best is trial 3 with value: 0.754813863928113.

Best trial: 3. Best value: 0.754814:  24%|██▍       | 12/50 [02:38<04:36,  7.27s/it]

[I 2025-12-02 05:34:03,456] Trial 12 pruned.

Best trial: 3. Best value: 0.754814:  26%|██▌       | 13/50 [02:44<04:11,  6.79s/it]

[I 2025-12-02 05:34:09,153] Trial 10 finished with value: 0.7163029525032092 and parameters: {'max_depth': 10, 'learning_rate': 0.016537247696068305, 'n_estimators': 912, 'subsample': 0.9901985427254465, 'colsample_bytree': 0.7522374166306145, 'min_child_weight': 9, 'gamma': 1.6683120288288522, 'reg_alpha': 2.156452212899022, 'reg_lambda': 0.10998129343109125, 'max_delta_step': 2}. Best is trial 3 with value: 0.754813863928113.

Best trial: 3. Best value: 0.754814:  28%|██▊       | 14/50 [02:59<05:35,  9.31s/it]

[I 2025-12-02 05:34:24,289] Trial 13 finished with value: 0.730423620025674 and parameters: {'max_depth': 8, 'learning_rate': 0.04327900345555882, 'n_estimators': 533, 'subsample': 0.9948681119983722, 'colsample_bytree': 0.9622764307925875, 'min_child_weight': 6, 'gamma': 3.506283290839037, 'reg_alpha': 1.309601187135331e-08, 'reg_lambda': 8.997149889940918, 'max_delta_step': 7}. Best is trial 3 with value: 0.754813863928113.

Best trial: 3. Best value: 0.754814:  30%|███       | 15/50 [03:03<04:29,  7.69s/it]

[I 2025-12-02 05:34:28,229] Trial 15 finished with value: 0.7041078305519897 and parameters: {'max_depth': 3, 'learning_rate': 0.011166062953094805, 'n_estimators': 435, 'subsample': 0.9855545977800553, 'colsample_bytree': 0.9408010405168212, 'min_child_weight': 1, 'gamma': 3.2428229641176958, 'reg_alpha': 2.124420607611065e-08, 'reg_lambda': 9.658715074292294, 'max_delta_step': 10}. Best is trial 3 with value: 0.754813863928113.

Best trial: 3. Best value: 0.754814:  32%|███▏      | 16/50 [03:04<03:09,  5.57s/it]

[I 2025-12-02 05:34:28,853] Trial 14 finished with value: 0.7182284980744544 and parameters: {'max_depth': 7, 'learning_rate': 0.011909106940975437, 'n_estimators': 447, 'subsample': 0.9415687487580053, 'colsample_bytree': 0.9547081633007511, 'min_child_weight': 1, 'gamma': 3.379108803017313, 'reg_alpha': 4.386535020701135e-05, 'reg_lambda': 4.141406424130256, 'max_delta_step': 10}. Best is trial 3 with value: 0.754813863928113.

Best trial: 3. Best value: 0.754814:  34%|███▍      | 17/50 [03:08<02:50,  5.18s/it]

[I 2025-12-02 05:34:33,126] Trial 16 finished with value: 0.7182284980744544 and parameters: {'max_depth': 3, 'learning_rate': 0.03804010723388378, 'n_estimators': 475, 'subsample': 0.9135899242339517, 'colsample_bytree': 0.9476178571884837, 'min_child_weight': 1, 'gamma': 3.2947753538578652, 'reg_alpha': 2.2674121425080653e-08, 'reg_lambda': 4.227695344361753, 'max_delta_step': 10}. Best is trial 3 with value: 0.754813863928113.

Best trial: 3. Best value: 0.754814:  36%|███▌      | 18/50 [03:15<03:06,  5.83s/it]

[I 2025-12-02 05:34:40,478] Trial 19 finished with value: 0.754813863928113 and parameters: {'max_depth': 3, 'learning_rate': 0.048083573260204085, 'n_estimators': 205, 'subsample': 0.8006047643194129, 'colsample_bytree': 0.8624862601445272, 'min_child_weight': 6, 'gamma': 2.6948898591354147, 'reg_alpha': 0.0025877961200458438, 'reg_lambda': 0.0024072053266231616, 'max_delta_step': 8}. Best is trial 3 with value: 0.754813863928113.

Best trial: 3. Best value: 0.754814:  38%|███▊      | 19/50 [03:20<02:50,  5.50s/it]

[I 2025-12-02 05:34:45,191] Trial 20 finished with value: 0.7426187419768935 and parameters: {'max_depth': 7, 'learning_rate': 0.064679077713629, 'n_estimators': 212, 'subsample': 0.8017536952033119, 'colsample_bytree': 0.8609788225537915, 'min_child_weight': 6, 'gamma': 2.829128222488422, 'reg_alpha': 0.002212617162605706, 'reg_lambda': 0.0023438209383710227, 'max_delta_step': 8}. Best is trial 3 with value: 0.754813863928113.

Best trial: 3. Best value: 0.754814:  40%|████      | 20/50 [03:26<02:45,  5.51s/it]

[I 2025-12-02 05:34:50,742] Trial 21 pruned.

Best trial: 18. Best value: 0.767009:  42%|████▏     | 21/50 [04:00<06:53, 14.26s/it]

[I 2025-12-02 05:35:25,401] Trial 18 finished with value: 0.7670089858793325 and parameters: {'max_depth': 7, 'learning_rate': 0.046614920307034874, 'n_estimators': 1192, 'subsample': 0.8964441662009643, 'colsample_bytree': 0.884570681309756, 'min_child_weight': 6, 'gamma': 2.929942921486452, 'reg_alpha': 1.0871673897030311e-05, 'reg_lambda': 0.003406961418333172, 'max_delta_step': 8}. Best is trial 18 with value: 0.7670089858793325.

Best trial: 18. Best value: 0.767009:  44%|████▍     | 22/50 [04:06<05:23, 11.54s/it]

[I 2025-12-02 05:35:30,596] Trial 17 finished with value: 0.7182284980744544 and parameters: {'max_depth': 3, 'learning_rate': 0.010390063362265382, 'n_estimators': 1194, 'subsample': 0.9098655242070957, 'colsample_bytree': 0.8701348878707368, 'min_child_weight': 1, 'gamma': 3.1064743245033455, 'reg_alpha': 1.2533960547501275e-05, 'reg_lambda': 8.504502802139942, 'max_delta_step': 10}. Best is trial 18 with value: 0.7670089858793325.

Best trial: 18. Best value: 0.767009:  46%|████▌     | 23/50 [04:21<05:40, 12.62s/it]

[I 2025-12-02 05:35:45,740] Trial 22 finished with value: 0.7163029525032092 and parameters: {'max_depth': 6, 'learning_rate': 0.02224685997002369, 'n_estimators': 1200, 'subsample': 0.8956402925881346, 'colsample_bytree': 0.6941696171911348, 'min_child_weight': 3, 'gamma': 4.031587874009448, 'reg_alpha': 0.40619325031081727, 'reg_lambda': 2.5440273420695397e-06, 'max_delta_step': 0}. Best is trial 18 with value: 0.7670089858793325.

Best trial: 18. Best value: 0.767009:  48%|████▊     | 24/50 [04:22<04:01,  9.29s/it]

[I 2025-12-02 05:35:47,263] Trial 23 finished with value: 0.689987163029525 and parameters: {'max_depth': 6, 'learning_rate': 0.022039700213525235, 'n_estimators': 1143, 'subsample': 0.894478880724517, 'colsample_bytree': 0.520010529785638, 'min_child_weight': 3, 'gamma': 3.9313196235955186, 'reg_alpha': 1.0459978809734625e-05, 'reg_lambda': 0.35763835370358615, 'max_delta_step': 8}. Best is trial 18 with value: 0.7670089858793325.

Best trial: 18. Best value: 0.767009:  50%|█████     | 25/50 [05:05<08:00, 19.24s/it]

[I 2025-12-02 05:36:29,705] Trial 24 finished with value: 0.7426187419768935 and parameters: {'max_depth': 6, 'learning_rate': 0.02594508935122101, 'n_estimators': 1244, 'subsample': 0.8904520740501596, 'colsample_bytree': 0.8591858493948755, 'min_child_weight': 3, 'gamma': 3.9688325910130127, 'reg_alpha': 1.0189835168060257e-05, 'reg_lambda': 0.5892378224952547, 'max_delta_step': 8}. Best is trial 18 with value: 0.7670089858793325.

Best trial: 18. Best value: 0.767009:  52%|█████▏    | 26/50 [05:15<06:34, 16.45s/it]

[I 2025-12-02 05:36:39,651] Trial 26 finished with value: 0.7670089858793325 and parameters: {'max_depth': 8, 'learning_rate': 0.01643266232586861, 'n_estimators': 1105, 'subsample': 0.8565591018502706, 'colsample_bytree': 0.5081285850712476, 'min_child_weight': 7, 'gamma': 3.8653015353503357, 'reg_alpha': 9.794299899189233e-07, 'reg_lambda': 0.011430479588066748, 'max_delta_step': 8}. Best is trial 18 with value: 0.7670089858793325.

Best trial: 18. Best value: 0.767009:  54%|█████▍    | 27/50 [05:21<05:06, 13.32s/it]

[I 2025-12-02 05:36:45,661] Trial 25 finished with value: 0.7426187419768935 and parameters: {'max_depth': 6, 'learning_rate': 0.026329471625366876, 'n_estimators': 1476, 'subsample': 0.8628845741652235, 'colsample_bytree': 0.7092020721404807, 'min_child_weight': 3, 'gamma': 3.932340712858387, 'reg_alpha': 7.768658926169894e-07, 'reg_lambda': 0.5943230045602506, 'max_delta_step': 8}. Best is trial 18 with value: 0.7670089858793325.

Best trial: 18. Best value: 0.767009:  56%|█████▌    | 28/50 [05:36<05:08, 14.00s/it]

[I 2025-12-02 05:37:01,255] Trial 27 finished with value: 0.754813863928113 and parameters: {'max_depth': 8, 'learning_rate': 0.0324330662085857, 'n_estimators': 1498, 'subsample': 0.8547334247116537, 'colsample_bytree': 0.8378971883124795, 'min_child_weight': 7, 'gamma': 1.5677305418843202, 'reg_alpha': 7.166407525863033e-07, 'reg_lambda': 0.011627073548225056, 'max_delta_step': 7}. Best is trial 18 with value: 0.7670089858793325.

Best trial: 18. Best value: 0.767009:  58%|█████▊    | 29/50 [06:08<06:44, 19.26s/it]

[I 2025-12-02 05:37:32,773] Trial 29 finished with value: 0.7670089858793325 and parameters: {'max_depth': 8, 'learning_rate': 0.016068817165270234, 'n_estimators': 1029, 'subsample': 0.9504739217603599, 'colsample_bytree': 0.9115707052938875, 'min_child_weight': 7, 'gamma': 4.431015659859561, 'reg_alpha': 7.440131789003486e-07, 'reg_lambda': 0.007209018936862175, 'max_delta_step': 6}. Best is trial 18 with value: 0.7670089858793325.

Best trial: 18. Best value: 0.767009:  60%|██████    | 30/50 [06:16<05:16, 15.81s/it]

[I 2025-12-02 05:37:40,554] Trial 30 finished with value: 0.754813863928113 and parameters: {'max_depth': 8, 'learning_rate': 0.015671756492873817, 'n_estimators': 1046, 'subsample': 0.9453700634363951, 'colsample_bytree': 0.8957513005735406, 'min_child_weight': 7, 'gamma': 4.479283575655024, 'reg_alpha': 8.303342564015812e-07, 'reg_lambda': 0.0083653225386203, 'max_delta_step': 6}. Best is trial 18 with value: 0.7670089858793325.

Best trial: 18. Best value: 0.767009:  62%|██████▏   | 31/50 [06:19<03:52, 12.23s/it]

[I 2025-12-02 05:37:44,407] Trial 28 finished with value: 0.7284980744544287 and parameters: {'max_depth': 8, 'learning_rate': 0.033049056261068244, 'n_estimators': 1460, 'subsample': 0.8550834380225136, 'colsample_bytree': 0.8222851065668717, 'min_child_weight': 7, 'gamma': 1.6722335776141404, 'reg_alpha': 6.83752395651689e-07, 'reg_lambda': 0.008265505838095759, 'max_delta_step': 6}. Best is trial 18 with value: 0.7670089858793325.

Best trial: 18. Best value: 0.767009:  64%|██████▍   | 32/50 [06:22<02:48,  9.35s/it]

[I 2025-12-02 05:37:47,060] Trial 33 pruned.

Best trial: 18. Best value: 0.767009:  66%|██████▌   | 33/50 [06:34<02:50, 10.03s/it]

[I 2025-12-02 05:37:58,665] Trial 31 finished with value: 0.7670089858793325 and parameters: {'max_depth': 9, 'learning_rate': 0.015436569852192902, 'n_estimators': 1086, 'subsample': 0.9274229300151869, 'colsample_bytree': 0.9982324586404041, 'min_child_weight': 7, 'gamma': 3.6914377073760423, 'reg_alpha': 7.739268368818049e-07, 'reg_lambda': 0.000613753680243664, 'max_delta_step': 6}. Best is trial 18 with value: 0.7670089858793325.

Best trial: 18. Best value: 0.767009:  68%|██████▊   | 34/50 [06:43<02:36,  9.79s/it]

[I 2025-12-02 05:38:07,902] Trial 36 pruned.

Best trial: 18. Best value: 0.767009:  70%|███████   | 35/50 [07:04<03:15, 13.06s/it]

[I 2025-12-02 05:38:28,594] Trial 32 finished with value: 0.7670089858793325 and parameters: {'max_depth': 9, 'learning_rate': 0.01572477026503812, 'n_estimators': 1066, 'subsample': 0.9458472435419143, 'colsample_bytree': 0.9014674159316889, 'min_child_weight': 7, 'gamma': 4.456789668876561, 'reg_alpha': 1.0307615995267791e-07, 'reg_lambda': 0.00038224480935831865, 'max_delta_step': 5}. Best is trial 18 with value: 0.7670089858793325.

Best trial: 18. Best value: 0.767009:  72%|███████▏  | 36/50 [07:16<02:58, 12.76s/it]

[I 2025-12-02 05:38:40,642] Trial 34 finished with value: 0.7163029525032092 and parameters: {'max_depth': 9, 'learning_rate': 0.016460341538149896, 'n_estimators': 1097, 'subsample': 0.9395153662442293, 'colsample_bytree': 0.908129273492275, 'min_child_weight': 8, 'gamma': 3.5342461148425572, 'reg_alpha': 1.198758605571624e-07, 'reg_lambda': 0.0008335936240256061, 'max_delta_step': 4}. Best is trial 18 with value: 0.7670089858793325.

Best trial: 35. Best value: 0.779204:  74%|███████▍  | 37/50 [07:21<02:15, 10.45s/it]

[I 2025-12-02 05:38:45,700] Trial 35 finished with value: 0.779204107830552 and parameters: {'max_depth': 9, 'learning_rate': 0.017118832291197282, 'n_estimators': 1129, 'subsample': 0.9337662696474209, 'colsample_bytree': 0.9128945667423066, 'min_child_weight': 5, 'gamma': 3.655360329493656, 'reg_alpha': 1.1034367142120682e-07, 'reg_lambda': 0.0007062185803181534, 'max_delta_step': 4}. Best is trial 35 with value: 0.779204107830552.

Best trial: 35. Best value: 0.779204:  76%|███████▌  | 38/50 [07:33<02:12, 11.02s/it]

[I 2025-12-02 05:38:58,057] Trial 37 finished with value: 0.7670089858793325 and parameters: {'max_depth': 7, 'learning_rate': 0.013846368397373509, 'n_estimators': 957, 'subsample': 0.6024659290651444, 'colsample_bytree': 0.9132562990514165, 'min_child_weight': 5, 'gamma': 4.392825097990801, 'reg_alpha': 2.4841569718332066e-06, 'reg_lambda': 0.00012254008740137902, 'max_delta_step': 7}. Best is trial 35 with value: 0.779204107830552.

Best trial: 35. Best value: 0.779204:  78%|███████▊  | 39/50 [07:54<02:34, 14.09s/it]

[I 2025-12-02 05:39:19,300] Trial 38 finished with value: 0.754813863928113 and parameters: {'max_depth': 7, 'learning_rate': 0.01808630584447696, 'n_estimators': 974, 'subsample': 0.5642545899281441, 'colsample_bytree': 0.9865846749644589, 'min_child_weight': 5, 'gamma': 4.332957217494512, 'reg_alpha': 2.5102532888414094e-06, 'reg_lambda': 0.028373993825276576, 'max_delta_step': 7}. Best is trial 35 with value: 0.779204107830552.

Best trial: 39. Best value: 0.80552:  80%|████████  | 40/50 [08:08<02:20, 14.07s/it]

[I 2025-12-02 05:39:33,315] Trial 39 finished with value: 0.8055198973042362 and parameters: {'max_depth': 7, 'learning_rate': 0.028054200384745386, 'n_estimators': 984, 'subsample': 0.5758567153757903, 'colsample_bytree': 0.9992211795269433, 'min_child_weight': 5, 'gamma': 4.7051012387374165, 'reg_alpha': 2.647459049493821e-06, 'reg_lambda': 8.22786232511721e-05, 'max_delta_step': 7}. Best is trial 39 with value: 0.8055198973042362.

Best trial: 39. Best value: 0.80552:  82%|████████▏ | 41/50 [08:12<01:38, 10.98s/it]

[I 2025-12-02 05:39:37,096] Trial 40 finished with value: 0.7670089858793325 and parameters: {'max_depth': 7, 'learning_rate': 0.027859482879243412, 'n_estimators': 991, 'subsample': 0.75349719101493, 'colsample_bytree': 0.797022620238936, 'min_child_weight': 5, 'gamma': 4.293042848704136, 'reg_alpha': 2.4836180994624088e-06, 'reg_lambda': 9.063073102345284e-05, 'max_delta_step': 3}. Best is trial 39 with value: 0.8055198973042362.

Best trial: 39. Best value: 0.80552:  84%|████████▍ | 42/50 [08:40<02:08, 16.02s/it]

[I 2025-12-02 05:40:04,879] Trial 41 finished with value: 0.754813863928113 and parameters: {'max_depth': 8, 'learning_rate': 0.026358460441547958, 'n_estimators': 1313, 'subsample': 0.750131043197238, 'colsample_bytree': 0.5243446476339595, 'min_child_weight': 5, 'gamma': 4.764619056306462, 'reg_alpha': 4.4512843080820715e-05, 'reg_lambda': 0.026709704769283017, 'max_delta_step': 4}. Best is trial 39 with value: 0.8055198973042362.

Best trial: 39. Best value: 0.80552:  86%|████████▌ | 43/50 [08:56<01:51, 15.94s/it]

[I 2025-12-02 05:40:20,630] Trial 44 finished with value: 0.754813863928113 and parameters: {'max_depth': 8, 'learning_rate': 0.05496838776499289, 'n_estimators': 826, 'subsample': 0.5997254488403025, 'colsample_bytree': 0.9708039546310395, 'min_child_weight': 6, 'gamma': 4.817691971500076, 'reg_alpha': 2.7215895851113505e-07, 'reg_lambda': 9.974354488113164e-06, 'max_delta_step': 9}. Best is trial 39 with value: 0.8055198973042362.

Best trial: 39. Best value: 0.80552:  88%|████████▊ | 44/50 [09:01<01:16, 12.81s/it]

[I 2025-12-02 05:40:26,125] Trial 42 finished with value: 0.7670089858793325 and parameters: {'max_depth': 8, 'learning_rate': 0.027580064788756752, 'n_estimators': 1307, 'subsample': 0.9664677270858877, 'colsample_bytree': 0.5170160026253328, 'min_child_weight': 5, 'gamma': 4.899036757009719, 'reg_alpha': 2.86088277151463e-05, 'reg_lambda': 3.188486939979781e-05, 'max_delta_step': 3}. Best is trial 39 with value: 0.8055198973042362.

Best trial: 39. Best value: 0.80552:  90%|█████████ | 45/50 [09:17<01:08, 13.68s/it]

[I 2025-12-02 05:40:41,833] Trial 43 finished with value: 0.7284980744544287 and parameters: {'max_depth': 5, 'learning_rate': 0.026198532259161824, 'n_estimators': 1328, 'subsample': 0.6214195628745036, 'colsample_bytree': 0.8040780279616304, 'min_child_weight': 5, 'gamma': 4.886015487143474, 'reg_alpha': 3.5894429481048556e-05, 'reg_lambda': 5.310253757654866e-06, 'max_delta_step': 3}. Best is trial 39 with value: 0.8055198973042362.

Best trial: 39. Best value: 0.80552:  92%|█████████▏| 46/50 [09:25<00:48, 12.13s/it]

[I 2025-12-02 05:40:50,369] Trial 45 finished with value: 0.7163029525032092 and parameters: {'max_depth': 8, 'learning_rate': 0.01880453013922962, 'n_estimators': 859, 'subsample': 0.6348006205145118, 'colsample_bytree': 0.9712274959270805, 'min_child_weight': 6, 'gamma': 4.688865927180623, 'reg_alpha': 3.271665420630632e-07, 'reg_lambda': 1.1993508713755445e-05, 'max_delta_step': 9}. Best is trial 39 with value: 0.8055198973042362.

Best trial: 39. Best value: 0.80552:  94%|█████████▍| 47/50 [09:44<00:42, 14.15s/it]

[I 2025-12-02 05:41:09,231] Trial 47 finished with value: 0.7689345314505777 and parameters: {'max_depth': 10, 'learning_rate': 0.035324235912908904, 'n_estimators': 839, 'subsample': 0.6527335713123422, 'colsample_bytree': 0.6036310179500208, 'min_child_weight': 6, 'gamma': 4.588942308950923, 'reg_alpha': 0.0005395763475590415, 'reg_lambda': 0.00447038782558015, 'max_delta_step': 5}. Best is trial 39 with value: 0.8055198973042362.

Best trial: 39. Best value: 0.80552:  96%|█████████▌| 48/50 [09:53<00:24, 12.41s/it]

[I 2025-12-02 05:41:17,580] Trial 46 finished with value: 0.754813863928113 and parameters: {'max_depth': 8, 'learning_rate': 0.03848335080351852, 'n_estimators': 1152, 'subsample': 0.6505074803633546, 'colsample_bytree': 0.9332752494330231, 'min_child_weight': 6, 'gamma': 2.977670165712882, 'reg_alpha': 0.00041305474070778373, 'reg_lambda': 3.544964173839087e-05, 'max_delta_step': 5}. Best is trial 39 with value: 0.8055198973042362.

Best trial: 39. Best value: 0.80552:  98%|█████████▊| 49/50 [10:03<00:11, 11.69s/it]

[I 2025-12-02 05:41:27,595] Trial 48 finished with value: 0.754813863928113 and parameters: {'max_depth': 10, 'learning_rate': 0.036555513167389336, 'n_estimators': 1176, 'subsample': 0.8753977566803735, 'colsample_bytree': 0.830805173586538, 'min_child_weight': 4, 'gamma': 4.136107329042073, 'reg_alpha': 0.0002269489536067427, 'reg_lambda': 0.005775187274005258, 'max_delta_step': 5}. Best is trial 39 with value: 0.8055198973042362.

Best trial: 39. Best value: 0.80552: 100%|██████████| 50/50 [10:05<00:00, 12.11s/it]

[I 2025-12-02 05:41:29,901] Trial 49 finished with value: 0.754813863928113 and parameters: {'max_depth': 10, 'learning_rate': 0.03945794099265416, 'n_estimators': 1161, 'subsample': 0.82934209169868, 'colsample_bytree': 0.9238677103722815, 'min_child_weight': 4, 'gamma': 2.9442160878062253, 'reg_alpha': 4.5992731339427454e-08, 'reg_lambda': 0.004811883625648731, 'max_delta_step': 5}. Best is trial 39 with value: 0.8055198973042362.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 05:41:33,216] A new study created in memory with name: 17_1_balanced_accuracy

============================================================
Processing dataset: 17_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.665597:   2%|▏         | 1/50 [00:22<18:02, 22.09s/it]

[I 2025-12-02 05:41:55,301] Trial 2 finished with value: 0.6655969191270861 and parameters: {'max_depth': 6, 'learning_rate': 0.04652944177673169, 'n_estimators': 406, 'subsample': 0.6298955921168743, 'colsample_bytree': 0.7488379714110879, 'min_child_weight': 3, 'gamma': 4.995366262371571, 'reg_alpha': 0.4561652158278161, 'reg_lambda': 7.527194625622305e-05, 'max_delta_step': 1}. Best is trial 2 with value: 0.6655969191270861.

Best trial: 2. Best value: 0.665597:   4%|▍         | 2/50 [00:23<08:08, 10.17s/it]

[I 2025-12-02 05:41:57,126] Trial 0 finished with value: 0.4473684210526316 and parameters: {'max_depth': 6, 'learning_rate': 0.12652546222312122, 'n_estimators': 464, 'subsample': 0.5589127895227934, 'colsample_bytree': 0.8359285408018096, 'min_child_weight': 8, 'gamma': 0.20307141988070765, 'reg_alpha': 0.0028462892572494168, 'reg_lambda': 0.4494064785600036, 'max_delta_step': 8}. Best is trial 2 with value: 0.6655969191270861.

Best trial: 3. Best value: 0.704108:   6%|▌         | 3/50 [00:27<05:38,  7.20s/it]

[I 2025-12-02 05:42:00,781] Trial 3 finished with value: 0.7041078305519897 and parameters: {'max_depth': 10, 'learning_rate': 0.06467144790491916, 'n_estimators': 502, 'subsample': 0.5343667526828988, 'colsample_bytree': 0.8195899050077391, 'min_child_weight': 2, 'gamma': 4.802714324356493, 'reg_alpha': 0.004198191951201625, 'reg_lambda': 6.389867959651712, 'max_delta_step': 10}. Best is trial 3 with value: 0.7041078305519897.

Best trial: 3. Best value: 0.704108:   8%|▊         | 4/50 [00:42<08:00, 10.44s/it]

[I 2025-12-02 05:42:16,197] Trial 5 finished with value: 0.6777920410783055 and parameters: {'max_depth': 10, 'learning_rate': 0.03464113791423043, 'n_estimators': 342, 'subsample': 0.9929148845986852, 'colsample_bytree': 0.9367527937032529, 'min_child_weight': 7, 'gamma': 1.7275446248229747, 'reg_alpha': 1.3205682411322299e-06, 'reg_lambda': 0.09351893295583226, 'max_delta_step': 10}. Best is trial 3 with value: 0.7041078305519897.

Best trial: 1. Best value: 0.742619:  10%|█         | 5/50 [00:44<05:25,  7.23s/it]

[I 2025-12-02 05:42:17,728] Trial 1 finished with value: 0.7426187419768935 and parameters: {'max_depth': 7, 'learning_rate': 0.01428195676471085, 'n_estimators': 858, 'subsample': 0.7367913662914812, 'colsample_bytree': 0.6693111869792343, 'min_child_weight': 6, 'gamma': 1.6301911142958296, 'reg_alpha': 1.8193081258339223e-05, 'reg_lambda': 0.2466397586837311, 'max_delta_step': 8}. Best is trial 1 with value: 0.7426187419768935.

Best trial: 1. Best value: 0.742619:  12%|█▏        | 6/50 [00:49<04:44,  6.47s/it]

[I 2025-12-02 05:42:22,722] Trial 4 finished with value: 0.6777920410783055 and parameters: {'max_depth': 4, 'learning_rate': 0.06746113663067382, 'n_estimators': 513, 'subsample': 0.7380462272085231, 'colsample_bytree': 0.9298556083451881, 'min_child_weight': 4, 'gamma': 1.4349229452240653, 'reg_alpha': 0.0005529394348734808, 'reg_lambda': 0.11618984831316011, 'max_delta_step': 8}. Best is trial 1 with value: 0.7426187419768935.

Best trial: 6. Best value: 0.77086:  14%|█▍        | 7/50 [00:51<03:30,  4.89s/it]

[I 2025-12-02 05:42:24,367] Trial 6 finished with value: 0.7708600770218228 and parameters: {'max_depth': 8, 'learning_rate': 0.014738473303045651, 'n_estimators': 437, 'subsample': 0.8766170037356994, 'colsample_bytree': 0.9478947361540024, 'min_child_weight': 9, 'gamma': 1.8202897756837704, 'reg_alpha': 0.0002632443122678536, 'reg_lambda': 1.6094336030229903, 'max_delta_step': 10}. Best is trial 6 with value: 0.7708600770218228.

Best trial: 6. Best value: 0.77086:  16%|█▌        | 8/50 [01:04<05:13,  7.47s/it]

[I 2025-12-02 05:42:37,368] Trial 9 finished with value: 0.6919127086007703 and parameters: {'max_depth': 9, 'learning_rate': 0.1166741969385516, 'n_estimators': 261, 'subsample': 0.9812036063767724, 'colsample_bytree': 0.8099506320131808, 'min_child_weight': 6, 'gamma': 0.46799083249860596, 'reg_alpha': 8.734821813888432e-08, 'reg_lambda': 0.20477579696757797, 'max_delta_step': 6}. Best is trial 6 with value: 0.7708600770218228.

Best trial: 6. Best value: 0.77086:  18%|█▊        | 9/50 [01:14<05:41,  8.33s/it]

[I 2025-12-02 05:42:47,569] Trial 7 finished with value: 0.7284980744544287 and parameters: {'max_depth': 9, 'learning_rate': 0.024227451414416946, 'n_estimators': 567, 'subsample': 0.9318808365604039, 'colsample_bytree': 0.6663054050112097, 'min_child_weight': 2, 'gamma': 4.704998605592705, 'reg_alpha': 0.019361771809856, 'reg_lambda': 1.4648303365691673e-06, 'max_delta_step': 5}. Best is trial 6 with value: 0.7708600770218228.

Best trial: 6. Best value: 0.77086:  20%|██        | 10/50 [01:26<06:14,  9.36s/it]

[I 2025-12-02 05:42:59,258] Trial 11 finished with value: 0.7163029525032092 and parameters: {'max_depth': 9, 'learning_rate': 0.026994381906108866, 'n_estimators': 403, 'subsample': 0.9425565780376522, 'colsample_bytree': 0.7954094840608179, 'min_child_weight': 3, 'gamma': 4.349442887963436, 'reg_alpha': 2.197045108945082, 'reg_lambda': 3.2113329344554845e-08, 'max_delta_step': 9}. Best is trial 6 with value: 0.7708600770218228.

Best trial: 6. Best value: 0.77086:  22%|██▏       | 11/50 [01:27<04:32,  7.00s/it]

[I 2025-12-02 05:43:00,887] Trial 8 pruned.

Best trial: 6. Best value: 0.77086:  24%|██▍       | 12/50 [01:32<03:57,  6.25s/it]

[I 2025-12-02 05:43:05,429] Trial 10 finished with value: 0.7163029525032092 and parameters: {'max_depth': 8, 'learning_rate': 0.020835072160660773, 'n_estimators': 746, 'subsample': 0.7351754992289647, 'colsample_bytree': 0.8652020411521699, 'min_child_weight': 2, 'gamma': 3.3554397084893783, 'reg_alpha': 0.4682778655030365, 'reg_lambda': 0.0019148778389369999, 'max_delta_step': 9}. Best is trial 6 with value: 0.7708600770218228.

Best trial: 6. Best value: 0.77086:  26%|██▌       | 13/50 [01:35<03:19,  5.38s/it]

[I 2025-12-02 05:43:08,805] Trial 14 pruned.

Best trial: 6. Best value: 0.77086:  28%|██▊       | 14/50 [01:37<02:37,  4.38s/it]

[I 2025-12-02 05:43:10,881] Trial 13 pruned.

Best trial: 6. Best value: 0.77086:  30%|███       | 15/50 [01:41<02:26,  4.20s/it]

[I 2025-12-02 05:43:14,643] Trial 15 pruned.

Best trial: 6. Best value: 0.77086:  32%|███▏      | 16/50 [02:28<09:43, 17.17s/it]

[I 2025-12-02 05:44:01,953] Trial 12 finished with value: 0.6919127086007703 and parameters: {'max_depth': 6, 'learning_rate': 0.02961009329323146, 'n_estimators': 1438, 'subsample': 0.6967637671297144, 'colsample_bytree': 0.6900236751360309, 'min_child_weight': 5, 'gamma': 2.61378713561831, 'reg_alpha': 2.7675528364656248e-08, 'reg_lambda': 0.0055514463448104534, 'max_delta_step': 7}. Best is trial 6 with value: 0.7708600770218228.

Best trial: 16. Best value: 0.783055:  34%|███▍      | 17/50 [02:32<07:16, 13.22s/it]

[I 2025-12-02 05:44:05,997] Trial 16 finished with value: 0.7830551989730423 and parameters: {'max_depth': 7, 'learning_rate': 0.010363906727352658, 'n_estimators': 1076, 'subsample': 0.8371402036976288, 'colsample_bytree': 0.6543811050012232, 'min_child_weight': 8, 'gamma': 2.0546114620650218, 'reg_alpha': 5.8680226172934406e-05, 'reg_lambda': 6.754023025291479, 'max_delta_step': 4}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  36%|███▌      | 18/50 [02:33<05:03,  9.48s/it]

[I 2025-12-02 05:44:06,763] Trial 17 finished with value: 0.7830551989730423 and parameters: {'max_depth': 7, 'learning_rate': 0.015327521345395634, 'n_estimators': 1058, 'subsample': 0.828791609936173, 'colsample_bytree': 0.6597168119626259, 'min_child_weight': 8, 'gamma': 1.924243587504718, 'reg_alpha': 1.9579795760025418e-07, 'reg_lambda': 3.4377530855418947, 'max_delta_step': 7}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  38%|███▊      | 19/50 [02:41<04:37,  8.94s/it]

[I 2025-12-02 05:44:14,459] Trial 18 finished with value: 0.7830551989730423 and parameters: {'max_depth': 5, 'learning_rate': 0.01844215516050748, 'n_estimators': 1154, 'subsample': 0.8810881568028225, 'colsample_bytree': 0.681056893880853, 'min_child_weight': 8, 'gamma': 1.954746032114376, 'reg_alpha': 1.2520807736215069e-08, 'reg_lambda': 2.3097082512255147, 'max_delta_step': 8}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  40%|████      | 20/50 [03:28<10:13, 20.45s/it]

[I 2025-12-02 05:45:01,722] Trial 19 finished with value: 0.7830551989730423 and parameters: {'max_depth': 8, 'learning_rate': 0.01682169548831838, 'n_estimators': 1130, 'subsample': 0.845137281795231, 'colsample_bytree': 0.9929384412851628, 'min_child_weight': 8, 'gamma': 1.741425000308776, 'reg_alpha': 9.115363166383126e-07, 'reg_lambda': 8.106790346793664, 'max_delta_step': 4}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  42%|████▏     | 21/50 [03:32<07:32, 15.59s/it]

[I 2025-12-02 05:45:05,977] Trial 21 finished with value: 0.7830551989730423 and parameters: {'max_depth': 5, 'learning_rate': 0.020210697445305174, 'n_estimators': 1137, 'subsample': 0.7883347845693527, 'colsample_bytree': 0.6106916250077894, 'min_child_weight': 8, 'gamma': 3.699211741239222, 'reg_alpha': 3.5403349706462304e-07, 'reg_lambda': 8.639703652007025, 'max_delta_step': 4}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  44%|████▍     | 22/50 [03:36<05:33, 11.92s/it]

[I 2025-12-02 05:45:09,340] Trial 20 finished with value: 0.7567394094993581 and parameters: {'max_depth': 5, 'learning_rate': 0.017294990340581233, 'n_estimators': 1202, 'subsample': 0.8785295501463243, 'colsample_bytree': 0.9984878366005439, 'min_child_weight': 8, 'gamma': 2.029899951590853, 'reg_alpha': 7.542747630942994e-07, 'reg_lambda': 2.7219460009301044, 'max_delta_step': 4}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  46%|████▌     | 23/50 [03:40<04:24,  9.78s/it]

[I 2025-12-02 05:45:14,141] Trial 22 finished with value: 0.7567394094993581 and parameters: {'max_depth': 3, 'learning_rate': 0.04105938302840245, 'n_estimators': 1134, 'subsample': 0.7913646927649555, 'colsample_bytree': 0.6060281542627712, 'min_child_weight': 8, 'gamma': 3.717351968697634, 'reg_alpha': 4.316894176826631e-07, 'reg_lambda': 0.024604440018787224, 'max_delta_step': 4}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  48%|████▊     | 24/50 [04:25<08:42, 20.11s/it]

[I 2025-12-02 05:45:58,330] Trial 25 finished with value: 0.6919127086007703 and parameters: {'max_depth': 3, 'learning_rate': 0.03988608359728809, 'n_estimators': 948, 'subsample': 0.8931951047913369, 'colsample_bytree': 0.7203758742604688, 'min_child_weight': 7, 'gamma': 1.1342048688761583, 'reg_alpha': 2.850544618493801e-08, 'reg_lambda': 0.04358739334415742, 'max_delta_step': 2}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  50%|█████     | 25/50 [04:31<06:40, 16.00s/it]

[I 2025-12-02 05:46:04,754] Trial 26 finished with value: 0.7041078305519897 and parameters: {'max_depth': 5, 'learning_rate': 0.013738615497842582, 'n_estimators': 990, 'subsample': 0.9055204663693965, 'colsample_bytree': 0.7304798770345994, 'min_child_weight': 7, 'gamma': 1.0788894805997726, 'reg_alpha': 1.19674264927435e-08, 'reg_lambda': 1.3039924084582049, 'max_delta_step': 7}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  52%|█████▏    | 26/50 [04:32<04:33, 11.41s/it]

[I 2025-12-02 05:46:05,439] Trial 23 finished with value: 0.730423620025674 and parameters: {'max_depth': 5, 'learning_rate': 0.03771009019652675, 'n_estimators': 1245, 'subsample': 0.7823176502945014, 'colsample_bytree': 0.5991300699181596, 'min_child_weight': 7, 'gamma': 3.5185000518219196, 'reg_alpha': 2.753785983447186e-07, 'reg_lambda': 0.019776794495444408, 'max_delta_step': 3}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  54%|█████▍    | 27/50 [04:36<03:34,  9.33s/it]

[I 2025-12-02 05:46:09,924] Trial 24 finished with value: 0.6655969191270861 and parameters: {'max_depth': 3, 'learning_rate': 0.0399651077401689, 'n_estimators': 1249, 'subsample': 0.9134498289102118, 'colsample_bytree': 0.7167040228477786, 'min_child_weight': 7, 'gamma': 2.141092447946863, 'reg_alpha': 1.886015454198671e-08, 'reg_lambda': 0.03037283886336096, 'max_delta_step': 3}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  56%|█████▌    | 28/50 [04:38<02:33,  6.96s/it]

[I 2025-12-02 05:46:11,364] Trial 29 pruned.

Best trial: 16. Best value: 0.783055:  58%|█████▊    | 29/50 [04:43<02:15,  6.47s/it]

[I 2025-12-02 05:46:16,693] Trial 30 pruned.

Best trial: 16. Best value: 0.783055:  60%|██████    | 30/50 [05:10<04:10, 12.52s/it]

[I 2025-12-02 05:46:43,341] Trial 28 finished with value: 0.7586649550706033 and parameters: {'max_depth': 6, 'learning_rate': 0.020853604571591324, 'n_estimators': 724, 'subsample': 0.7823188585447008, 'colsample_bytree': 0.6298951224422994, 'min_child_weight': 9, 'gamma': 2.185528052687067, 'reg_alpha': 8.428946279232267e-08, 'reg_lambda': 0.6429442914192132, 'max_delta_step': 7}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  62%|██████▏   | 31/50 [05:18<03:36, 11.40s/it]

[I 2025-12-02 05:46:52,101] Trial 31 finished with value: 0.7830551989730423 and parameters: {'max_depth': 6, 'learning_rate': 0.019897403832449662, 'n_estimators': 774, 'subsample': 0.9555675794305799, 'colsample_bytree': 0.7771773935243724, 'min_child_weight': 9, 'gamma': 2.262122121437827, 'reg_alpha': 1.2370535613733737e-07, 'reg_lambda': 1.3195513137030642e-08, 'max_delta_step': 0}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  64%|██████▍   | 32/50 [05:32<03:39, 12.19s/it]

[I 2025-12-02 05:47:06,145] Trial 27 finished with value: 0.6919127086007703 and parameters: {'max_depth': 5, 'learning_rate': 0.01327576345344246, 'n_estimators': 1307, 'subsample': 0.9158916540913081, 'colsample_bytree': 0.6227865286314603, 'min_child_weight': 7, 'gamma': 2.2076503526319584, 'reg_alpha': 9.238570008033777e-08, 'reg_lambda': 0.795414478452856, 'max_delta_step': 7}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  66%|██████▌   | 33/50 [05:37<02:48,  9.91s/it]

[I 2025-12-02 05:47:10,736] Trial 32 finished with value: 0.6777920410783055 and parameters: {'max_depth': 6, 'learning_rate': 0.11593465958529588, 'n_estimators': 1040, 'subsample': 0.9572270750584106, 'colsample_bytree': 0.5584814121714098, 'min_child_weight': 5, 'gamma': 0.11708327502087168, 'reg_alpha': 9.915361494999878e-08, 'reg_lambda': 1.163383505573811e-08, 'max_delta_step': 0}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  68%|██████▊   | 34/50 [06:04<04:01, 15.07s/it]

[I 2025-12-02 05:47:37,841] Trial 33 finished with value: 0.6777920410783055 and parameters: {'max_depth': 6, 'learning_rate': 0.09255314391696666, 'n_estimators': 1051, 'subsample': 0.9683105287791399, 'colsample_bytree': 0.5619657321684157, 'min_child_weight': 5, 'gamma': 0.05913240336321324, 'reg_alpha': 0.00011225144205556268, 'reg_lambda': 0.00014947359114033756, 'max_delta_step': 0}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  70%|███████   | 35/50 [06:13<03:17, 13.16s/it]

[I 2025-12-02 05:47:46,552] Trial 34 finished with value: 0.7830551989730423 and parameters: {'max_depth': 8, 'learning_rate': 0.016122588948626896, 'n_estimators': 1051, 'subsample': 0.8370175821799031, 'colsample_bytree': 0.6898591504251095, 'min_child_weight': 8, 'gamma': 1.367486824932381, 'reg_alpha': 0.00010362527891933038, 'reg_lambda': 9.181528807054628, 'max_delta_step': 5}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  72%|███████▏  | 36/50 [06:29<03:18, 14.15s/it]

[I 2025-12-02 05:48:03,013] Trial 35 finished with value: 0.7830551989730423 and parameters: {'max_depth': 8, 'learning_rate': 0.016448631867857718, 'n_estimators': 1084, 'subsample': 0.8471426525114815, 'colsample_bytree': 0.6918836818081772, 'min_child_weight': 8, 'gamma': 1.484208422492345, 'reg_alpha': 0.00014073461375854735, 'reg_lambda': 5.17456244078111, 'max_delta_step': 5}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  74%|███████▍  | 37/50 [06:35<02:30, 11.60s/it]

[I 2025-12-02 05:48:08,658] Trial 36 finished with value: 0.7830551989730423 and parameters: {'max_depth': 8, 'learning_rate': 0.016400913613695455, 'n_estimators': 1110, 'subsample': 0.8525912156786076, 'colsample_bytree': 0.7640632118723696, 'min_child_weight': 8, 'gamma': 1.3302818274155084, 'reg_alpha': 6.487954389324061e-05, 'reg_lambda': 7.774414848772483, 'max_delta_step': 5}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  76%|███████▌  | 38/50 [07:01<03:09, 15.82s/it]

[I 2025-12-02 05:48:34,318] Trial 38 finished with value: 0.6777920410783055 and parameters: {'max_depth': 8, 'learning_rate': 0.016580558826585805, 'n_estimators': 900, 'subsample': 0.8695272049115443, 'colsample_bytree': 0.8780253528875686, 'min_child_weight': 6, 'gamma': 1.5374452534083118, 'reg_alpha': 2.084139403686537e-06, 'reg_lambda': 3.343243154432885, 'max_delta_step': 8}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  78%|███████▊  | 39/50 [07:04<02:13, 12.16s/it]

[I 2025-12-02 05:48:37,948] Trial 37 finished with value: 0.6777920410783055 and parameters: {'max_depth': 8, 'learning_rate': 0.01592060496247723, 'n_estimators': 1145, 'subsample': 0.8549254442585493, 'colsample_bytree': 0.6935841589519659, 'min_child_weight': 6, 'gamma': 1.437819156498763, 'reg_alpha': 2.5437044333916e-06, 'reg_lambda': 4.618203127881952, 'max_delta_step': 5}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  80%|████████  | 40/50 [07:14<01:53, 11.40s/it]

[I 2025-12-02 05:48:47,564] Trial 39 finished with value: 0.6777920410783055 and parameters: {'max_depth': 7, 'learning_rate': 0.029077594761992172, 'n_estimators': 854, 'subsample': 0.8619416197618652, 'colsample_bytree': 0.7626956387125281, 'min_child_weight': 6, 'gamma': 1.7601981060134873, 'reg_alpha': 0.0014999715216432944, 'reg_lambda': 2.598030372790913, 'max_delta_step': 8}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  82%|████████▏ | 41/50 [07:24<01:39, 11.03s/it]

[I 2025-12-02 05:48:57,726] Trial 40 finished with value: 0.7163029525032092 and parameters: {'max_depth': 7, 'learning_rate': 0.059353093104694186, 'n_estimators': 932, 'subsample': 0.7548959040895952, 'colsample_bytree': 0.8830364898968116, 'min_child_weight': 6, 'gamma': 1.844637171596593, 'reg_alpha': 0.0014069417138451354, 'reg_lambda': 0.2423789862012798, 'max_delta_step': 8}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  84%|████████▍ | 42/50 [08:02<02:32, 19.10s/it]

[I 2025-12-02 05:49:35,669] Trial 41 finished with value: 0.7182284980744544 and parameters: {'max_depth': 7, 'learning_rate': 0.05280042550798336, 'n_estimators': 1188, 'subsample': 0.805445614576382, 'colsample_bytree': 0.6657175313066761, 'min_child_weight': 6, 'gamma': 1.752014775051986, 'reg_alpha': 0.0028589844395823074, 'reg_lambda': 0.2901959509149441, 'max_delta_step': 9}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  86%|████████▌ | 43/50 [08:04<01:38, 14.04s/it]

[I 2025-12-02 05:49:37,887] Trial 43 finished with value: 0.7586649550706033 and parameters: {'max_depth': 9, 'learning_rate': 0.05636680040113433, 'n_estimators': 960, 'subsample': 0.8044020069482403, 'colsample_bytree': 0.6561789198950702, 'min_child_weight': 9, 'gamma': 0.683731632704095, 'reg_alpha': 0.007135161704588977, 'reg_lambda': 0.1617533819225229, 'max_delta_step': 9}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  88%|████████▊ | 44/50 [08:15<01:19, 13.22s/it]

[I 2025-12-02 05:49:49,185] Trial 42 finished with value: 0.7445442875481387 and parameters: {'max_depth': 7, 'learning_rate': 0.05419487175494361, 'n_estimators': 1362, 'subsample': 0.7539907265278675, 'colsample_bytree': 0.6629085619320951, 'min_child_weight': 9, 'gamma': 1.848130776386085, 'reg_alpha': 0.0021201562738472207, 'reg_lambda': 0.1887574463088111, 'max_delta_step': 9}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  90%|█████████ | 45/50 [08:26<01:01, 12.36s/it]

[I 2025-12-02 05:49:59,536] Trial 44 finished with value: 0.7830551989730423 and parameters: {'max_depth': 4, 'learning_rate': 0.012353300263002253, 'n_estimators': 1208, 'subsample': 0.802869851736645, 'colsample_bytree': 0.6572787071089781, 'min_child_weight': 8, 'gamma': 2.8936552275341647, 'reg_alpha': 0.02119223690046014, 'reg_lambda': 0.13442525486188434, 'max_delta_step': 4}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  92%|█████████▏| 46/50 [08:26<00:35,  8.78s/it]

[I 2025-12-02 05:49:59,983] Trial 47 pruned.

Best trial: 16. Best value: 0.783055:  94%|█████████▍| 47/50 [09:13<01:00, 20.03s/it]

[I 2025-12-02 05:50:46,248] Trial 45 finished with value: 0.7182284980744544 and parameters: {'max_depth': 4, 'learning_rate': 0.023480501614371825, 'n_estimators': 1336, 'subsample': 0.7556503661309228, 'colsample_bytree': 0.5972456264702628, 'min_child_weight': 9, 'gamma': 0.7296377208635649, 'reg_alpha': 3.141142195188989e-07, 'reg_lambda': 9.550836261229787, 'max_delta_step': 4}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  96%|█████████▌| 48/50 [09:14<00:29, 14.51s/it]

[I 2025-12-02 05:50:47,886] Trial 46 finished with value: 0.7830551989730423 and parameters: {'max_depth': 5, 'learning_rate': 0.02449247214262306, 'n_estimators': 1328, 'subsample': 0.7678667853426311, 'colsample_bytree': 0.5848986778825668, 'min_child_weight': 8, 'gamma': 2.485585893582765, 'reg_alpha': 2.8424116128398504e-07, 'reg_lambda': 9.63436132435814, 'max_delta_step': 4}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055:  98%|█████████▊| 49/50 [09:18<00:11, 11.37s/it]

[I 2025-12-02 05:50:51,944] Trial 49 finished with value: 0.7689345314505777 and parameters: {'max_depth': 4, 'learning_rate': 0.024116411395806045, 'n_estimators': 1140, 'subsample': 0.7202715489009401, 'colsample_bytree': 0.7389865431245911, 'min_child_weight': 7, 'gamma': 2.4190491088654653, 'reg_alpha': 7.22254344709633e-06, 'reg_lambda': 1.6404988291189286, 'max_delta_step': 6}. Best is trial 16 with value: 0.7830551989730423.

Best trial: 16. Best value: 0.783055: 100%|██████████| 50/50 [09:20<00:00, 11.21s/it]

[I 2025-12-02 05:50:53,582] Trial 48 finished with value: 0.7445442875481387 and parameters: {'max_depth': 5, 'learning_rate': 0.02559714827650951, 'n_estimators': 1306, 'subsample': 0.7655252802558112, 'colsample_bytree': 0.5933480378317503, 'min_child_weight': 7, 'gamma': 4.041858723120227, 'reg_alpha': 2.6676137452750427e-07, 'reg_lambda': 3.150519788799201e-06, 'max_delta_step': 2}. Best is trial 16 with value: 0.7830551989730423.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

[I 2025-12-02 05:50:56,827] A new study created in memory with name: 19_1_balanced_accuracy

============================================================
Processing dataset: 19_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.833761:   2%|▏         | 1/50 [00:20<16:22, 20.04s/it]

[I 2025-12-02 05:51:16,863] Trial 2 finished with value: 0.8337612323491657 and parameters: {'max_depth': 9, 'learning_rate': 0.04722725975121312, 'n_estimators': 363, 'subsample': 0.7797113000704837, 'colsample_bytree': 0.6987175084138553, 'min_child_weight': 3, 'gamma': 1.9380667995169099, 'reg_alpha': 1.998098135146886e-05, 'reg_lambda': 0.17966532922990006, 'max_delta_step': 2}. Best is trial 2 with value: 0.8337612323491657.

Best trial: 2. Best value: 0.833761:   4%|▍         | 2/50 [00:36<14:18, 17.89s/it]

[I 2025-12-02 05:51:33,252] Trial 0 finished with value: 0.7830551989730423 and parameters: {'max_depth': 4, 'learning_rate': 0.02827446527668181, 'n_estimators': 722, 'subsample': 0.7030629929733441, 'colsample_bytree': 0.9978076932147931, 'min_child_weight': 6, 'gamma': 1.3325213633921296, 'reg_alpha': 4.958656786640249e-06, 'reg_lambda': 0.0002129622955973995, 'max_delta_step': 2}. Best is trial 2 with value: 0.8337612323491657.

Best trial: 2. Best value: 0.833761:   6%|▌         | 3/50 [00:42<09:39, 12.34s/it]

[I 2025-12-02 05:51:38,977] Trial 4 finished with value: 0.8093709884467266 and parameters: {'max_depth': 4, 'learning_rate': 0.022908908485297367, 'n_estimators': 404, 'subsample': 0.6557070888478752, 'colsample_bytree': 0.8535344709352332, 'min_child_weight': 5, 'gamma': 2.8834015858177366, 'reg_alpha': 9.268638157665059e-08, 'reg_lambda': 0.00021299357016703408, 'max_delta_step': 6}. Best is trial 2 with value: 0.8337612323491657.

Best trial: 3. Best value: 0.882542:   8%|▊         | 4/50 [00:58<10:38, 13.88s/it]

[I 2025-12-02 05:51:55,216] Trial 3 finished with value: 0.8825417201540436 and parameters: {'max_depth': 5, 'learning_rate': 0.11920136978512155, 'n_estimators': 1114, 'subsample': 0.8172504343360869, 'colsample_bytree': 0.6218994694441918, 'min_child_weight': 1, 'gamma': 3.117764314018499, 'reg_alpha': 0.06738122616125793, 'reg_lambda': 7.366019953622109e-06, 'max_delta_step': 9}. Best is trial 3 with value: 0.8825417201540436.

Best trial: 3. Best value: 0.882542:  10%|█         | 5/50 [01:04<08:14, 10.98s/it]

[I 2025-12-02 05:52:01,065] Trial 1 finished with value: 0.8459563543003852 and parameters: {'max_depth': 3, 'learning_rate': 0.25646420970869654, 'n_estimators': 1284, 'subsample': 0.7724999711490805, 'colsample_bytree': 0.9124075733711068, 'min_child_weight': 1, 'gamma': 0.2766756803541248, 'reg_alpha': 1.6880180652755383e-08, 'reg_lambda': 1.805692264912872, 'max_delta_step': 1}. Best is trial 3 with value: 0.8825417201540436.

Best trial: 3. Best value: 0.882542:  12%|█▏        | 6/50 [01:27<11:05, 15.12s/it]

[I 2025-12-02 05:52:24,209] Trial 8 finished with value: 0.8478818998716302 and parameters: {'max_depth': 3, 'learning_rate': 0.1468554916377817, 'n_estimators': 425, 'subsample': 0.6543056267952791, 'colsample_bytree': 0.8265300612966251, 'min_child_weight': 8, 'gamma': 0.6915836054989982, 'reg_alpha': 0.4540129657161317, 'reg_lambda': 1.422979029733111e-07, 'max_delta_step': 5}. Best is trial 3 with value: 0.8825417201540436.

Best trial: 3. Best value: 0.882542:  14%|█▍        | 7/50 [01:36<09:19, 13.02s/it]

[I 2025-12-02 05:52:32,914] Trial 7 finished with value: 0.7464698331193838 and parameters: {'max_depth': 3, 'learning_rate': 0.26176752834911504, 'n_estimators': 711, 'subsample': 0.608923370379292, 'colsample_bytree': 0.8419369366144795, 'min_child_weight': 8, 'gamma': 3.222935047529419, 'reg_alpha': 0.03838106422628395, 'reg_lambda': 0.0039838144561824, 'max_delta_step': 3}. Best is trial 3 with value: 0.8825417201540436.

Best trial: 3. Best value: 0.882542:  16%|█▌        | 8/50 [01:40<07:06, 10.16s/it]

[I 2025-12-02 05:52:36,952] Trial 6 finished with value: 0.8215661103979461 and parameters: {'max_depth': 7, 'learning_rate': 0.2604874545108562, 'n_estimators': 1129, 'subsample': 0.5170424673856142, 'colsample_bytree': 0.5258186976252764, 'min_child_weight': 5, 'gamma': 2.627129219763003, 'reg_alpha': 0.0001526436194941414, 'reg_lambda': 0.0012108130974134144, 'max_delta_step': 0}. Best is trial 3 with value: 0.8825417201540436.

Best trial: 3. Best value: 0.882542:  18%|█▊        | 9/50 [01:44<05:40,  8.31s/it]

[I 2025-12-02 05:52:41,191] Trial 5 finished with value: 0.8215661103979461 and parameters: {'max_depth': 7, 'learning_rate': 0.10628429970629577, 'n_estimators': 1356, 'subsample': 0.8652915653554115, 'colsample_bytree': 0.8053958616766073, 'min_child_weight': 6, 'gamma': 0.2833370984724576, 'reg_alpha': 0.017455219315982123, 'reg_lambda': 0.005328502326085605, 'max_delta_step': 2}. Best is trial 3 with value: 0.8825417201540436.

Best trial: 3. Best value: 0.882542:  20%|██        | 10/50 [01:58<06:48, 10.22s/it]

[I 2025-12-02 05:52:55,702] Trial 9 finished with value: 0.8356867779204107 and parameters: {'max_depth': 5, 'learning_rate': 0.2933193675949114, 'n_estimators': 603, 'subsample': 0.7713415316715306, 'colsample_bytree': 0.9118504313659102, 'min_child_weight': 8, 'gamma': 2.014946327691538, 'reg_alpha': 0.030367070761810003, 'reg_lambda': 5.19064965652115, 'max_delta_step': 10}. Best is trial 3 with value: 0.8825417201540436.

Best trial: 3. Best value: 0.882542:  22%|██▏       | 11/50 [02:02<05:23,  8.29s/it]

[I 2025-12-02 05:52:59,607] Trial 10 finished with value: 0.8337612323491657 and parameters: {'max_depth': 3, 'learning_rate': 0.0198678871371171, 'n_estimators': 497, 'subsample': 0.911373023891816, 'colsample_bytree': 0.5668239592731691, 'min_child_weight': 5, 'gamma': 3.3670146118093873, 'reg_alpha': 1.2847414458440508e-08, 'reg_lambda': 3.3148729313630643, 'max_delta_step': 8}. Best is trial 3 with value: 0.8825417201540436.

Best trial: 3. Best value: 0.882542:  24%|██▍       | 12/50 [02:03<03:41,  5.84s/it]

[I 2025-12-02 05:52:59,849] Trial 12 pruned.

Best trial: 3. Best value: 0.882542:  26%|██▌       | 13/50 [02:05<02:58,  4.83s/it]

[I 2025-12-02 05:53:02,360] Trial 15 pruned.

Best trial: 3. Best value: 0.882542:  28%|██▊       | 14/50 [02:07<02:25,  4.04s/it]

[I 2025-12-02 05:53:04,557] Trial 13 pruned.

Best trial: 3. Best value: 0.882542:  30%|███       | 15/50 [02:11<02:14,  3.83s/it]

[I 2025-12-02 05:53:07,923] Trial 14 pruned.

Best trial: 3. Best value: 0.882542:  32%|███▏      | 16/50 [02:13<01:56,  3.43s/it]

[I 2025-12-02 05:53:10,418] Trial 16 pruned.

Best trial: 3. Best value: 0.882542:  34%|███▍      | 17/50 [02:31<04:13,  7.67s/it]

[I 2025-12-02 05:53:27,958] Trial 11 finished with value: 0.8459563543003852 and parameters: {'max_depth': 5, 'learning_rate': 0.03172141838990263, 'n_estimators': 946, 'subsample': 0.5944771653210705, 'colsample_bytree': 0.7956934953537375, 'min_child_weight': 1, 'gamma': 1.3345834496400477, 'reg_alpha': 0.3896399591291709, 'reg_lambda': 1.7906912134495612, 'max_delta_step': 2}. Best is trial 3 with value: 0.8825417201540436.

Best trial: 3. Best value: 0.882542:  36%|███▌      | 18/50 [02:54<06:37, 12.41s/it]

[I 2025-12-02 05:53:51,390] Trial 17 finished with value: 0.8478818998716302 and parameters: {'max_depth': 5, 'learning_rate': 0.15796091021871275, 'n_estimators': 905, 'subsample': 0.6914483030934069, 'colsample_bytree': 0.7374785737451014, 'min_child_weight': 8, 'gamma': 3.9907652900417476, 'reg_alpha': 0.2126795186319832, 'reg_lambda': 1.2886067568344015e-08, 'max_delta_step': 6}. Best is trial 3 with value: 0.8825417201540436.

Best trial: 3. Best value: 0.882542:  38%|███▊      | 19/50 [02:54<04:31,  8.74s/it]

[I 2025-12-02 05:53:51,595] Trial 18 finished with value: 0.8318356867779204 and parameters: {'max_depth': 6, 'learning_rate': 0.048393010668958854, 'n_estimators': 837, 'subsample': 0.6941585343119973, 'colsample_bytree': 0.7569743926280603, 'min_child_weight': 3, 'gamma': 0.7570372008041186, 'reg_alpha': 0.3473265434420808, 'reg_lambda': 7.113549556055814e-06, 'max_delta_step': 7}. Best is trial 3 with value: 0.8825417201540436.

Best trial: 19. Best value: 0.884467:  40%|████      | 20/50 [02:57<03:26,  6.89s/it]

[I 2025-12-02 05:53:54,157] Trial 19 finished with value: 0.8844672657252888 and parameters: {'max_depth': 6, 'learning_rate': 0.17950546661599753, 'n_estimators': 842, 'subsample': 0.7061045750600107, 'colsample_bytree': 0.7659908755570008, 'min_child_weight': 3, 'gamma': 3.729080981375724, 'reg_alpha': 0.21120620586995803, 'reg_lambda': 9.123475212057758e-06, 'max_delta_step': 8}. Best is trial 19 with value: 0.8844672657252888.

Best trial: 19. Best value: 0.884467:  42%|████▏     | 21/50 [03:47<09:40, 20.01s/it]

[I 2025-12-02 05:54:44,767] Trial 20 finished with value: 0.8459563543003852 and parameters: {'max_depth': 6, 'learning_rate': 0.01186502091140416, 'n_estimators': 1457, 'subsample': 0.7196977526787662, 'colsample_bytree': 0.7519428554768569, 'min_child_weight': 3, 'gamma': 3.706172612356232, 'reg_alpha': 0.0013572437116981051, 'reg_lambda': 4.292339948681562e-06, 'max_delta_step': 8}. Best is trial 19 with value: 0.8844672657252888.

Best trial: 19. Best value: 0.884467:  44%|████▍     | 22/50 [03:58<07:58, 17.11s/it]

[I 2025-12-02 05:54:55,102] Trial 23 finished with value: 0.8703465982028241 and parameters: {'max_depth': 8, 'learning_rate': 0.18386152995620642, 'n_estimators': 1231, 'subsample': 0.9172846287242058, 'colsample_bytree': 0.6016677455492719, 'min_child_weight': 3, 'gamma': 3.74492331779713, 'reg_alpha': 0.0016608567329785874, 'reg_lambda': 1.250627755380522e-05, 'max_delta_step': 9}. Best is trial 19 with value: 0.8844672657252888.

Best trial: 19. Best value: 0.884467:  46%|████▌     | 23/50 [04:12<07:18, 16.23s/it]

[I 2025-12-02 05:55:09,285] Trial 21 finished with value: 0.8581514762516047 and parameters: {'max_depth': 6, 'learning_rate': 0.1605026481281089, 'n_estimators': 1483, 'subsample': 0.8263637289892943, 'colsample_bytree': 0.7622603312789609, 'min_child_weight': 3, 'gamma': 0.8068107926520419, 'reg_alpha': 0.00046700163622905635, 'reg_lambda': 8.571359473479354e-06, 'max_delta_step': 8}. Best is trial 19 with value: 0.8844672657252888.
[I 2025-12-02 05:55:09,334] Trial 22 finished with value: 0.8459563543003852 and parameters: {'max_depth': 4, 'learning_rate': 0.011003877887122163, 'n_estimators': 1456, 'subsample': 0.8449131703632093, 'colsample_bytree': 0.5993345845976379, 'min_child_weight': 3, 'gamma': 2.270228293311658, 'reg_alpha': 0.0013785539877812431, 'reg_lambda': 1.41087353028794e-05, 'max_delta_step': 8}. Best is trial 19 with value: 0.8844672657252888.

Best trial: 19. Best value: 0.884467:  50%|█████     | 25/50 [04:23<04:39, 11.18s/it]

[I 2025-12-02 05:55:19,866] Trial 26 pruned.

Best trial: 24. Best value: 0.896662:  52%|█████▏    | 26/50 [04:48<05:50, 14.60s/it]

[I 2025-12-02 05:55:44,822] Trial 24 finished with value: 0.8966623876765083 and parameters: {'max_depth': 8, 'learning_rate': 0.17460047740867957, 'n_estimators': 1178, 'subsample': 0.8386497672800821, 'colsample_bytree': 0.626496807326995, 'min_child_weight': 2, 'gamma': 2.200328073360271, 'reg_alpha': 0.0024464804831830305, 'reg_lambda': 9.645280116184068e-06, 'max_delta_step': 9}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  54%|█████▍    | 27/50 [04:59<05:17, 13.83s/it]

[I 2025-12-02 05:55:56,463] Trial 25 finished with value: 0.8703465982028241 and parameters: {'max_depth': 8, 'learning_rate': 0.184342010487455, 'n_estimators': 1195, 'subsample': 0.9397214566135783, 'colsample_bytree': 0.5008723206533039, 'min_child_weight': 2, 'gamma': 3.364842837587008, 'reg_alpha': 0.0005568159312467922, 'reg_lambda': 1.842894517743609e-05, 'max_delta_step': 9}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  56%|█████▌    | 28/50 [05:11<04:51, 13.25s/it]

[I 2025-12-02 05:56:08,197] Trial 27 finished with value: 0.8703465982028241 and parameters: {'max_depth': 8, 'learning_rate': 0.19438896157909902, 'n_estimators': 1159, 'subsample': 0.9382350854553343, 'colsample_bytree': 0.5005814418249651, 'min_child_weight': 2, 'gamma': 3.2222732520759267, 'reg_alpha': 0.00372630514502228, 'reg_lambda': 6.25394033514158e-05, 'max_delta_step': 9}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  58%|█████▊    | 29/50 [05:26<04:48, 13.72s/it]

[I 2025-12-02 05:56:23,118] Trial 28 finished with value: 0.8703465982028241 and parameters: {'max_depth': 8, 'learning_rate': 0.07886610091612534, 'n_estimators': 1253, 'subsample': 0.896065564492022, 'colsample_bytree': 0.5244297147058898, 'min_child_weight': 2, 'gamma': 3.18344176417144, 'reg_alpha': 2.649141905190005e-05, 'reg_lambda': 1.7222308193232272e-06, 'max_delta_step': 9}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  60%|██████    | 30/50 [05:30<03:39, 10.97s/it]

[I 2025-12-02 05:56:27,216] Trial 29 finished with value: 0.8703465982028241 and parameters: {'max_depth': 8, 'learning_rate': 0.07557393562796345, 'n_estimators': 818, 'subsample': 0.8165471036252075, 'colsample_bytree': 0.5007574782487271, 'min_child_weight': 2, 'gamma': 2.9356053694333974, 'reg_alpha': 0.0800042235825274, 'reg_lambda': 1.4842468604030442e-06, 'max_delta_step': 9}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  62%|██████▏   | 31/50 [05:41<03:30, 11.10s/it]

[I 2025-12-02 05:56:38,623] Trial 30 finished with value: 0.8459563543003852 and parameters: {'max_depth': 9, 'learning_rate': 0.07155988090598314, 'n_estimators': 803, 'subsample': 0.8070868214926992, 'colsample_bytree': 0.7096285088500676, 'min_child_weight': 2, 'gamma': 2.954489507284528, 'reg_alpha': 0.08147971408947077, 'reg_lambda': 1.4496058791845408e-06, 'max_delta_step': 10}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  64%|██████▍   | 32/50 [05:54<03:28, 11.59s/it]

[I 2025-12-02 05:56:51,412] Trial 31 finished with value: 0.8196405648267009 and parameters: {'max_depth': 9, 'learning_rate': 0.06872443401678395, 'n_estimators': 813, 'subsample': 0.7982243006318693, 'colsample_bytree': 0.7139803125000712, 'min_child_weight': 4, 'gamma': 2.7894563776508994, 'reg_alpha': 0.08673733136399148, 'reg_lambda': 1.3906536451177898e-06, 'max_delta_step': 10}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  66%|██████▌   | 33/50 [06:08<03:31, 12.42s/it]

[I 2025-12-02 05:57:05,803] Trial 32 finished with value: 0.7952503209242618 and parameters: {'max_depth': 9, 'learning_rate': 0.13044565916596598, 'n_estimators': 799, 'subsample': 0.807041065279237, 'colsample_bytree': 0.7110423054345454, 'min_child_weight': 4, 'gamma': 2.5844676228632575, 'reg_alpha': 0.08529737501020561, 'reg_lambda': 0.00010172510487085052, 'max_delta_step': 7}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  68%|██████▊   | 34/50 [06:26<03:42, 13.90s/it]

[I 2025-12-02 05:57:23,222] Trial 33 finished with value: 0.8196405648267009 and parameters: {'max_depth': 9, 'learning_rate': 0.1306409844381765, 'n_estimators': 1061, 'subsample': 0.8020961689975116, 'colsample_bytree': 0.6951927048813925, 'min_child_weight': 4, 'gamma': 1.7433941871947813, 'reg_alpha': 1.2466692874047594, 'reg_lambda': 0.00011630733841812878, 'max_delta_step': 7}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  70%|███████   | 35/50 [06:37<03:16, 13.12s/it]

[I 2025-12-02 05:57:34,484] Trial 37 pruned.

Best trial: 24. Best value: 0.896662:  72%|███████▏  | 36/50 [06:37<02:09,  9.27s/it]

[I 2025-12-02 05:57:34,700] Trial 34 finished with value: 0.8337612323491657 and parameters: {'max_depth': 9, 'learning_rate': 0.13789347253228468, 'n_estimators': 1064, 'subsample': 0.7365533165276281, 'colsample_bytree': 0.5689320929084364, 'min_child_weight': 4, 'gamma': 3.738651475543936, 'reg_alpha': 8.124693057275827e-05, 'reg_lambda': 8.577807041253095e-05, 'max_delta_step': 7}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  74%|███████▍  | 37/50 [06:49<02:09,  9.99s/it]

[I 2025-12-02 05:57:46,384] Trial 39 pruned.

Best trial: 24. Best value: 0.896662:  76%|███████▌  | 38/50 [06:51<01:29,  7.50s/it]

[I 2025-12-02 05:57:48,034] Trial 35 finished with value: 0.7971758664955071 and parameters: {'max_depth': 7, 'learning_rate': 0.20947192534687967, 'n_estimators': 1069, 'subsample': 0.7272636542364547, 'colsample_bytree': 0.6348059410798063, 'min_child_weight': 4, 'gamma': 3.9439206986889404, 'reg_alpha': 8.229048447624607e-05, 'reg_lambda': 0.00010058993559655915, 'max_delta_step': 7}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  78%|███████▊  | 39/50 [07:00<01:28,  8.00s/it]

[I 2025-12-02 05:57:57,217] Trial 40 pruned.

Best trial: 24. Best value: 0.896662:  80%|████████  | 40/50 [07:19<01:51, 11.19s/it]

[I 2025-12-02 05:58:15,874] Trial 36 finished with value: 0.8478818998716302 and parameters: {'max_depth': 7, 'learning_rate': 0.2091306437069005, 'n_estimators': 1353, 'subsample': 0.7348523403125021, 'colsample_bytree': 0.5782696010379077, 'min_child_weight': 4, 'gamma': 3.671841127736246, 'reg_alpha': 7.38011318443061e-05, 'reg_lambda': 0.0007522649564672959, 'max_delta_step': 7}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  82%|████████▏ | 41/50 [07:33<01:49, 12.18s/it]

[I 2025-12-02 05:58:30,368] Trial 38 finished with value: 0.8337612323491657 and parameters: {'max_depth': 10, 'learning_rate': 0.09206597629018887, 'n_estimators': 1073, 'subsample': 0.8740946822566859, 'colsample_bytree': 0.6402680478189154, 'min_child_weight': 4, 'gamma': 2.2745972010542927, 'reg_alpha': 0.003992809444219384, 'reg_lambda': 0.0007815295259690148, 'max_delta_step': 9}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  84%|████████▍ | 42/50 [07:37<01:18,  9.86s/it]

[I 2025-12-02 05:58:34,814] Trial 42 finished with value: 0.8337612323491657 and parameters: {'max_depth': 4, 'learning_rate': 0.29946140853632, 'n_estimators': 702, 'subsample': 0.7712309076345804, 'colsample_bytree': 0.8978842526647395, 'min_child_weight': 3, 'gamma': 3.4808906973788845, 'reg_alpha': 9.795020649465083e-07, 'reg_lambda': 1.934487552001196e-08, 'max_delta_step': 4}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  86%|████████▌ | 43/50 [07:53<01:21, 11.58s/it]

[I 2025-12-02 05:58:50,397] Trial 43 finished with value: 0.8703465982028241 and parameters: {'max_depth': 4, 'learning_rate': 0.2813896597069991, 'n_estimators': 648, 'subsample': 0.8647510392097697, 'colsample_bytree': 0.9625707870769766, 'min_child_weight': 3, 'gamma': 1.7903901481218547, 'reg_alpha': 0.0009742700771576871, 'reg_lambda': 3.263228338291057e-08, 'max_delta_step': 4}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  88%|████████▊ | 44/50 [07:57<00:55,  9.27s/it]

[I 2025-12-02 05:58:54,268] Trial 41 finished with value: 0.8337612323491657 and parameters: {'max_depth': 10, 'learning_rate': 0.09304752832913014, 'n_estimators': 1244, 'subsample': 0.7776574124902146, 'colsample_bytree': 0.6669060634916778, 'min_child_weight': 1, 'gamma': 4.271843775034585, 'reg_alpha': 0.0013490847774832696, 'reg_lambda': 0.0005363957377632157, 'max_delta_step': 4}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  90%|█████████ | 45/50 [08:37<01:33, 18.61s/it]

[I 2025-12-02 05:59:34,676] Trial 44 finished with value: 0.8703465982028241 and parameters: {'max_depth': 8, 'learning_rate': 0.18812573873700497, 'n_estimators': 1210, 'subsample': 0.9135610445879868, 'colsample_bytree': 0.5404456522346046, 'min_child_weight': 2, 'gamma': 3.4613137286870463, 'reg_alpha': 0.0008726974654699873, 'reg_lambda': 2.1310533484058017e-05, 'max_delta_step': 9}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  92%|█████████▏| 46/50 [08:44<00:59, 14.99s/it]

[I 2025-12-02 05:59:41,217] Trial 45 finished with value: 0.8825417201540436 and parameters: {'max_depth': 8, 'learning_rate': 0.1677546965602341, 'n_estimators': 1281, 'subsample': 0.9111538449817863, 'colsample_bytree': 0.5467558261028621, 'min_child_weight': 2, 'gamma': 3.4755588539261586, 'reg_alpha': 0.0004561700752378725, 'reg_lambda': 2.275897611947971e-05, 'max_delta_step': 9}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  94%|█████████▍| 47/50 [08:55<00:41, 13.77s/it]

[I 2025-12-02 05:59:52,134] Trial 49 pruned.

Best trial: 24. Best value: 0.896662:  96%|█████████▌| 48/50 [08:58<00:21, 10.55s/it]

[I 2025-12-02 05:59:55,159] Trial 46 finished with value: 0.8703465982028241 and parameters: {'max_depth': 8, 'learning_rate': 0.1752139831767764, 'n_estimators': 1208, 'subsample': 0.9169003835417747, 'colsample_bytree': 0.5396063846334668, 'min_child_weight': 2, 'gamma': 3.4494442266390983, 'reg_alpha': 0.00031838308375076727, 'reg_lambda': 2.439394427649514e-05, 'max_delta_step': 9}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662:  98%|█████████▊| 49/50 [08:59<00:07,  7.69s/it]

[I 2025-12-02 05:59:56,186] Trial 47 finished with value: 0.8825417201540436 and parameters: {'max_depth': 8, 'learning_rate': 0.1839629910616462, 'n_estimators': 1212, 'subsample': 0.9157969737942712, 'colsample_bytree': 0.5377300582478658, 'min_child_weight': 2, 'gamma': 3.537753261053652, 'reg_alpha': 5.649177094346669e-06, 'reg_lambda': 2.1377991204885147e-05, 'max_delta_step': 9}. Best is trial 24 with value: 0.8966623876765083.

Best trial: 24. Best value: 0.896662: 100%|██████████| 50/50 [09:04<00:00, 10.89s/it]

[I 2025-12-02 06:00:01,361] Trial 48 finished with value: 0.8825417201540436 and parameters: {'max_depth': 7, 'learning_rate': 0.16092324716867779, 'n_estimators': 905, 'subsample': 0.9565797599729841, 'colsample_bytree': 0.5417365721111878, 'min_child_weight': 2, 'gamma': 3.0908379683474942, 'reg_alpha': 0.022501255210101018, 'reg_lambda': 2.7117932566126618e-05, 'max_delta_step': 8}. Best is trial 24 with value: 0.8966623876765083.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.805520                    0.65          0.56
1     9_1         loo       0.781130                    0.60          0.70
2    17_1         loo       0.783055                    0.50          0.56
3    19_1         loo       0.896662                    0.45          0.56

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.288675               0.6               0.7        50          60
1  0.188982               0.6               0.6        50          60
2  0.000000               0.6               0.4        50          60
3 -0.094491               0.4               0.5        50          60

   test_size
0         15
1         15
2         15
3         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    15_1         loo       0.805520                    0.65          0.56
1     9_1         loo       0.781130                    0.60          0.70
2    17_1         loo       0.783055                    0.50          0.56
3    19_1         loo       0.896662                    0.45          0.56

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.288675               0.6               0.7        50          60
1  0.188982               0.6               0.6        50          60
2  0.000000               0.6               0.4        50          60
3 -0.094491               0.4               0.5        50          60

   test_size
0         15
1         15
2         15
3         15

# MCI-LBD vs HC - 9_1 - Long Sentence

In [1589]:
#task_9_1_comb_emb_hf_lbd_hc = {"9_1": task_hf_compensated_comb_emb_lbl_lbd_hc.get("9_1")}
#task_9_1_temp_emb_hf_lbd_hc = {"9_1": task_hf_compensated_temp_emb_lbl_lbd_hc.get("9_1")}
#task_9_1_freq_emb_hf_lbd_hc = {"9_1": task_hf_compensated_freq_emb_lbl_lbd_hc.get("9_1")}
#
#task_9_1_comb_emb_lbd_hc = {"9_1": task_comb_dfs_lbd_hc.get("9_1")}
#task_9_1_temp_emb_lbd_hc = {"9_1": task_temp_dfs_lbd_hc.get("9_1")}
#task_9_1_freq_emb_lbd_hc = {"9_1": task_freq_dfs_lbd_hc.get("9_1")}
#
#task_9_1_hf_lbd_hc = {"9_1": task_hf_dfs_clean_lbd_hc.get("9_1")}

In [1590]:
#print(
#task_9_1_comb_emb_hf_lbd_hc.get('9_1').shape, 
#task_9_1_temp_emb_hf_lbd_hc.get('9_1').shape,
#task_9_1_freq_emb_hf_lbd_hc.get('9_1').shape,
#
#task_9_1_comb_emb_lbd_hc.get('9_1').shape,
#task_9_1_temp_emb_lbd_hc.get('9_1').shape,
#ttask_9_1_freq_emb_lbd_hc.get('9_1')ask_9_1_freq_emb_lbd_hc.get('9_1').shape,
#
#task_9_1_hf_lbd_hc.get('9_1').shape,
#)

In [1591]:
#task_9_1_hf_lbd_hc.get('9_1')

In [1592]:
#task_9_1_freq_emb_lbd_hc.get('9_1')

In [1593]:

#print(
#task_9_1_comb_emb_hf_ad_hc.get('9_1').shape, 
#task_9_1_temp_emb_hf_ad_hc.get('9_1').shape,
#task_9_1_freq_emb_hf_ad_hc.get('9_1').shape,
#
#task_9_1_comb_emb_ad_hc.get('9_1').shape,
#task_9_1_temp_emb_ad_hc.get('9_1').shape,
#task_9_1_freq_emb_ad_hc.get('9_1').shape,
#
#task_9_1_hf_ad_hc.get('9_1').shape,

In [1594]:

#print(
    #task_9_1_comb_emb_hf_ad_lbd.get('9_1').shape, 
    #task_9_1_temp_emb_hf_ad_lbd.get('9_1').shape,
    #task_9_1_freq_emb_hf_ad_lbd.get('9_1').shape,
#
    #task_9_1_comb_emb_ad_lbd.get('9_1').shape,
    #task_9_1_temp_emb_ad_lbd.get('9_1').shape,
    #task_9_1_freq_emb_ad_lbd.get('9_1').shape,
#
    #task_9_1_hf_ad_lbd.get('9_1').shape,
#)

In [1595]:
#import pandas as pd
#import umap
#import matplotlib.pyplot as plt
#
#def plot_umap(df, label_col="diagnosis", subject_col="subject"):
    ## pick feature columns (exclude subject, diagnosis, and anything non-numeric)
    #feature_cols = df.select_dtypes(include=["float", "int"]).columns.tolist()
    #feature_cols = [c for c in feature_cols if c not in [label_col]]  # keep features only
#
    #X = df[feature_cols].values
    #y = df[label_col].values  # labels [0,1]

    # Initialize UMAP
    #reducer = umap.UMAP(
        #n_neighbors=15,
        #min_dist=0.1,
        #metric='euclidean',
        #random_state=42
    #)
#
    #embedding = reducer.fit_transform(X)
#
    ## Plot
    #plt.figure(figsize=(8,6))
    #scatter = plt.scatter(
        #embedding[:, 0], embedding[:, 1],
        #c=y,
        #cmap='coolwarm',
        #alpha=0.8,
        #s=70
    #)
#
    #cbar = plt.colorbar(scatter)
    #cbar.set_label("Diagnosis (0=Control, 1=Patient)")
#
    #plt.title("UMAP projection of subjects")
    #plt.xlabel("UMAP-1")
    #plt.ylabel("UMAP-2")
    #plt.grid(True)
    #plt.show()
#
#

In [1596]:
#plot_umap(task_9_1_comb_emb_hf_lbd_hc.get('9_1'), label_col = 'diagnosis_y')
#plot_umap(task_9_1_temp_emb_hf_lbd_hc.get('9_1'), label_col = 'diagnosis_y')
#plot_umap(task_9_1_freq_emb_hf_lbd_hc.get('9_1'), label_col = 'diagnosis_y')

#plot_umap(task_9_1_comb_emb_lbd_hc.get('9_1'), label_col = 'diagnosis')
#plot_umap(task_9_1_temp_emb_lbd_hc.get('9_1'), label_col = 'diagnosis')
#plot_umap(task_9_1_freq_emb_lbd_hc.get('9_1'), label_col = 'diagnosis')

#plot_umap(task_9_1_hf_lbd_hc.get('9_1'), label_col = 'diagnosis')

In [1597]:
#print(task_9_1_comb_emb_hf_lbd_hc)

In [1598]:
#task_9_1_comb_emb_hf_lbd_hc

In [1599]:
#datasets = task_9_1_comb_emb_hf_lbd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials = 50,
    #cv_strategy="loo",
    #output_dir="xgb_lbd_hc_loo_9_1/xgb_results_handcrafted_combined_emb_loo_9_1_lbd_hc",
    #split_param= "diagnosis_y",
#)
#print(summary)
#

In [1600]:

#datasets = task_9_1_temp_emb_hf_lbd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_lbd_hc_loo_9_1/xgb_results_handcrafted_temporal_emb_loo_9_1_lbd_hc",
    #split_param= "diagnosis_y",
#)
#print(summary)
#

In [1601]:

#datasets = task_9_1_freq_emb_hf_lbd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_lbd_hc_loo_9_1/xgb_results_handcrafted_frerq_emb_loo_9_1_lbd_hc",
    #split_param= "diagnosis_y",
#)
#print(summary)
### MCI-AD vs HC -> OPTUNA + XGB

In [1602]:
#task_9_1_freq_emb_hf_lbd_hc.get("9_1")

In [1603]:
#datasets = task_9_1_comb_emb_lbd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_lbd_hc_loo_9_1/xgb_results_comb_loo_9_1_lbd_hc",
    #split_param="emb_",
#)
#print(summary)
#

In [1604]:
#
## Temporal embedings
#datasets = task_9_1_temp_emb_lbd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    ##    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="balanced_accuracy",      
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_lbd_hc_loo_9_1/xgb_results_temp_loo_9_1_lbd_hc",
    #split_param="emb_",
#)
#print(summary)
#

In [1605]:

# Combined embedings
#datasets = task_9_1_freq_emb_lbd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_lbd_hc_loo_9_1/xgb_results_freq_loo_9_1_lbd_hc",
    #split_param="emb_",
#)
#print(summary)
#
#

In [1606]:

#datasets = task_9_1_hf_lbd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_lbd_hc_loo_9_1/xgb_results_handcrafted_loo_9_1_lbd_hc",
    #split_param="w.cz.fnusa",
#)
#print(summary)

# MCI-AD vs HC - 9_1 - Long Sentence

In [1607]:
#task_9_1_comb_emb_hf_ad_hc = {"9_1": task_hf_compensated_comb_emb_lbl_ad_hc.get("9_1")}
#task_9_1_temp_emb_hf_ad_hc = {"9_1": task_hf_compensated_temp_emb_lbl_ad_hc.get("9_1")}
#task_9_1_freq_emb_hf_ad_hc = {"9_1": task_hf_compensated_freq_emb_lbl_ad_hc.get("9_1")}
#
#task_9_1_comb_emb_ad_hc = {"9_1": task_comb_dfs_ad_hc.get("9_1")}
#task_9_1_temp_emb_ad_hc = {"9_1": task_temp_dfs_ad_hc.get("9_1")}
#task_9_1_freq_emb_ad_hc = {"9_1": task_freq_dfs_ad_hc.get("9_1")}
#
#task_9_1_hf_lbd_hc = {"9_1": task_hf_dfs_clean_ad_hc.get("9_1")}

In [1608]:
#task_9_1_hf_ad_hc.get("9_1")

In [1609]:
#task_9_1_comb_emb_hf_ad_hc

In [1610]:
#datasets = task_9_1_comb_emb_hf_ad_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy ="loo",
    #output_dir="xgb_ad_hc_loo_9_1/xgb_results_handcrafted_combined_emb_loo_9_1_ad_hc",
    #split_param= "diagnosis_y",
#)
#print(summary)
#

In [1611]:

#datasets = task_9_1_temp_emb_hf_ad_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_hc_loo_9_1/xgb_results_handcrafted_temporal_emb_loo_9_1_ad_hc",
    #split_param= "diagnosis_y",
#)
#print(summary)
#

In [1612]:

#datasets = task_9_1_freq_emb_hf_ad_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_hc_loo_9_1/xgb_results_handcrafted_frerq_emb_loo_9_1_ad_hc",
    #split_param= "diagnosis_y",
#)
#print(summary)
### MCI-AD vs HC -> OPTUNA + XGB

In [1613]:
#datasets = task_9_1_comb_emb_ad_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_hc_loo_9_1/xgb_results_comb_loo_9_1_ad_hc",
    #split_param="emb_",
#)
#print(summary)
#

In [1614]:

## Temporal embedings
#datasets = task_9_1_temp_emb_ad_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    ##    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="balanced_accuracy",      
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_hc_loo_9_1/xgb_results_temp_loo_9_1_ad_hc",
    #split_param="emb_",
#)
#print(summary)
#

In [1615]:

## Combined embedings
#datasets = task_9_1_freq_emb_ad_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_hc_loo_9_1/xgb_results_freq_loo_9_1_ad_hc",
    #split_param="emb_",
#)
#print(summary)
#
##

In [1616]:
#task_9_1_hf_ad_hc.get('9_1')

In [1617]:

## Combined embedings
#datasets = task_9_1_hf_ad_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_hc_loo_9_1/xgb_results_hc_loo_9_1_ad_hc",
    #split_param="emb_",
#)
#print(summary)
#
#

# MCI-LBD vs MCI-AD - 9_1 - Long Sentence

In [1618]:
#task_9_1_comb_emb_hf_ad_lbd = {"9_1": task_hf_compensated_comb_emb_lbl_ad_lbd.get("9_1")}
#task_9_1_temp_emb_hf_ad_lbd = {"9_1": task_hf_compensated_temp_emb_lbl_ad_lbd.get("9_1")}
#task_9_1_freq_emb_hf_ad_lbd = {"9_1": task_hf_compensated_freq_emb_lbl_ad_lbd.get("9_1")}
#
#task_9_1_comb_emb_ad_lbd = {"9_1": task_comb_dfs_ad_lbd.get("9_1")}
#task_9_1_temp_emb_ad_lbd = {"9_1": task_temp_dfs_ad_lbd.get("9_1")}
#task_9_1_freq_emb_ad_lbd = {"9_1": task_freq_dfs_ad_lbd.get("9_1")}
#
#task_9_1_hf_ad_lbd = {"9_1": task_hf_dfs_clean_ad_lbd.get("9_1")}

In [1619]:
#task_9_1_freq_emb_ad_lbd.get('9_1')

In [1620]:
#datasets = task_9_1_comb_emb_hf_ad_lbd
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy ="loo",
    #output_dir="xgb_ad_lbd_loo_9_1/xgb_results_handcrafted_combined_emb_loo_9_1_ad_lbd",
    #split_param= "diagnosis_y",
#)
#print(summary)
#

In [1621]:

#datasets = task_9_1_temp_emb_hf_ad_lbd
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_lbd_loo_9_1/xgb_results_handcrafted_temporal_emb_loo_9_1_ad_lbd",
    #split_param= "diagnosis_y",
#)
#print(summary)
#

In [1622]:
#task_9_1_freq_emb_hf_ad_lbd.get('9_1')

In [1623]:

#datasets = task_9_1_freq_emb_hf_ad_lbd
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_lbd_loo_9_1/xgb_results_handcrafted_frerq_emb_loo_9_1_ad_lbd",
    #split_param= "diagnosis_y",
#)
#print(summary)
### MCI-AD vs HC -> OPTUNA + XGB

In [1624]:
#datasets = task_9_1_comb_emb_ad_lbd
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_lbd_loo_9_1/xgb_results_comb_loo_9_1_ad_lbd",
    #split_param="emb_",
#)
#print(summary)
#

In [1625]:
#task_9_1_temp_emb_ad_lbd.get('9_1')et

In [1626]:

# Temporal embedings
#datasets = task_9_1_temp_emb_ad_lbd
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    ##    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="balanced_accuracy",      
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_lbd_loo_9_1/xgb_results_temp_loo_9_1_ad_lbd",
    #split_param="emb_",
#)
#print(summary)
#

In [1627]:

# Combined embedings
#datasets = task_9_1_freq_emb_ad_lbd
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_lbd_loo_9_1/xgb_results_freq_loo_9_1_ad_lbd",
    #split_param="emb_",
#)
#print(summary)
#
#

In [1628]:
#task_9_1_hf_ad_hc.get('9_1')

In [1629]:

# Handcrafted features
#datasets = task_9_1_hf_ad_lbd
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_lbd_loo_9_1/xgb_results_hc_loo_9_1_ad_lbd",
    #split_param="emb_",
#)
#print(summary)
#
#

# PD vs HC - 9_1 - Long Sentence

In [1630]:
#task_9_1_comb_emb_hf_pd_hc = {"9_1": task_hf_compensated_comb_emb_lbl_pd_hc.get("9_1")}
#task_9_1_temp_emb_hf_pd_hc = {"9_1": task_hf_compensated_temp_emb_lbl_pd_hc.get("9_1")}
#task_9_1_freq_emb_hf_pd_hc = {"9_1": task_hf_compensated_freq_emb_lbl_pd_hc.get("9_1")}
#
#task_9_1_comb_emb_pd_hc = {"9_1": task_comb_dfs_pd_hc.get("9_1")}
#task_9_1_temp_emb_pd_hc = {"9_1": task_temp_dfs_pd_hc.get("9_1")}
#task_9_1_freq_emb_pd_hc = {"9_1": task_freq_dfs_pd_hc.get("9_1")}
#
#task_9_1_hf_pd_hc = {"9_1": task_hf_dfs_clean_pd_hc.get("9_1")}

In [1631]:
#task_9_1_hf_pd_hc.get('9_1')

In [1632]:
#datasets = task_9_1_comb_emb_hf_pd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy ="loo",
    #output_dir="xgb_pd_hc_loo_9_1/xgb_results_handcrafted_combined_emb_loo_9_1_pd_hc",
    #split_param= "diagnosis_y",
#)
#print(summary)
#

In [1633]:

#datasets = task_9_1_temp_emb_hf_pd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_pd_hc_loo_9_1/xgb_results_handcrafted_temporal_emb_loo_9_1_pd_hc",
    #split_param= "diagnosis_y",
#)
#print(summary)
#

In [1634]:
#task_9_1_freq_emb_hf_pd_hc.get('9_1')

In [1635]:
#
#datpd_hc = task_9_1_freq_emb_hf_pd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_pd_hc_loo_9_1/xgb_results_handcrafted_frerq_emb_loo_9_1_pd_hc",
    #split_param= "diagnosis_y",
#)
#print(summary)
### MCI-AD vs HC -> OPTUNA + XGB

In [1636]:
#datasets = task_9_1_comb_emb_pd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_pd_hc_loo_9_1/xgb_results_comb_loo_9_1_pd_hc",
    #split_param="emb_",
#)
#print(summary)
#

In [1637]:
#task_9_1_temp_emb_pd_hc.get('9_1')

In [1638]:
#
## Temporal embedings
#datasets = task_9_1_temp_emb_pd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    ##    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="balanced_accuracy",      
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_pd_hc_loo_9_1/xgb_results_temp_loo_9_1_pd_hc",
    #split_param="emb_",
#)
#print(summary)

In [1639]:

## Combined embedings
#datasets = task_9_1_freq_emb_pd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_pd_hc_loo_9_1/xgb_results_freq_loo_9_1_pd_hc",
    #split_param="emb_",
#)
#print(summary)
#
#

In [1640]:
#task_9_1_hf_pd_hc.get('9_1')

In [1641]:

# Handcrafted features
#datasets = task_9_1_hf_pd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_pd_hc_loo_9_1/xgb_results_hc_loo_9_1_pd_hc",
    #split_param="emb_",
#)
#print(summary)
#
#