In [67]:
import pathlib as Path
import numpy as np
import pandas as pd

## Create dataframe from embeddings

In [68]:
#-----Frequency Embeddings dataframe creation-----
def create_embeddings_dataframe(root_path):
    emb_root = Path.Path(root_path)
    emb_files = emb_root.rglob("embeddings_samples.npz")
    
    all_data = []
    
    for emb_file in emb_files:
        emb = np.load(emb_file)
        X = emb['X']
        y = emb['y']
        subjects = emb['subs']
        
        for i in range(X.shape[0]):
            data_point = {
                'embedding': X[i],
                'label': y[i],
                'subject': subjects[i],
                'file_path': str(emb_file)
            }
            all_data.append(data_point)
    
    df = pd.DataFrame(all_data)
    return df

## Clean embedding DF

In [69]:
def df_cleaning(df, emb_size=384):
        # --- Expand embedding column into 381 separate columns ---
    embedding_df = pd.DataFrame(df["embedding"].tolist(),
                                columns=[f"emb_{i}" for i in range(emb_size)])

    # --- Concatenate back to the original DataFrame (optional) ---
    df_expanded = pd.concat([df.drop(columns=["embedding"]), embedding_df], axis=1)
    return df_expanded

## Frequency/ Temporal/ Combined DF

In [70]:
#-----Frequency Embeddings dataframe creation-----
freq_emb= create_embeddings_dataframe("C://dev//dolphin_initial_testing//DOLPHIN//out_prelbd_task_wise//frequency_emb_stored//")
#-----Temporal Embeddings dataframe creation-----
temp_emb= create_embeddings_dataframe("C://dev//dolphin_initial_testing//DOLPHIN//out_prelbd_task_wise//temporal_emb_stored//")
#-----Combined Embeddings dataframe creation-----
comb_emb= create_embeddings_dataframe("C://dev//dolphin_initial_testing//DOLPHIN//out_prelbd_task_wise//emb_stored//")

freq_emb_df= df_cleaning(freq_emb, emb_size=384)
temp_emb_df= df_cleaning(temp_emb, emb_size=384)
comb_emb_df= df_cleaning(comb_emb, emb_size=768)

In [71]:
freq_emb_df.sample(5)

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_374,emb_375,emb_376,emb_377,emb_378,emb_379,emb_380,emb_381,emb_382,emb_383
239,1,pre-LBD-48#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.026829,-0.037561,0.012212,-0.047020,0.024748,-0.035392,0.046189,...,0.022111,0.126247,-0.033947,0.023330,-0.005869,0.110748,0.002101,0.030808,0.025347,0.048743
993,1,pre-LBD-72#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.007746,-0.119414,-0.096543,0.007971,-0.034161,-0.039081,0.060631,...,0.026341,0.095504,0.020670,-0.031900,0.056306,0.029541,0.099522,-0.012130,0.021537,-0.048232
913,1,pre-LBD-103#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.006091,-0.122542,-0.097042,0.007439,-0.035012,-0.037619,0.061736,...,0.024269,0.096376,0.021212,-0.031216,0.056705,0.028116,0.097500,-0.013545,0.020749,-0.046550
124,1,pre-LBD-79#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.003713,0.040947,-0.102968,0.045758,0.034926,-0.030015,0.006690,...,0.078143,0.062993,0.058206,-0.027473,-0.028143,0.006273,0.008161,-0.037082,-0.032695,-0.039703
231,1,pre-LBD-4#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.023560,-0.033300,0.005409,-0.053382,0.022268,-0.039408,0.042200,...,0.022690,0.127628,-0.041221,0.026466,-0.001108,0.113712,0.000516,0.033044,0.026210,0.045985

In [72]:
temp_emb_df.sample(5)

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_374,emb_375,emb_376,emb_377,emb_378,emb_379,emb_380,emb_381,emb_382,emb_383
1374,1,pre-LBD-15#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.072782,0.034710,-0.039587,-0.020371,0.089312,0.032138,-0.004606,...,-0.043482,0.046901,-0.001693,0.079785,0.018602,0.035085,-0.006108,0.062380,0.021124,-0.017660
782,1,pre-LBD-116#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.028852,-0.028504,-0.002088,0.079480,0.029286,-0.024515,-0.038351,...,-0.004113,0.002134,-0.070211,0.040174,-0.061012,-0.057692,0.043160,0.010722,0.062937,-0.042202
837,1,pre-LBD-61#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.034455,-0.009454,0.000486,0.088870,0.024815,-0.022061,-0.050019,...,-0.000842,0.008465,-0.069420,0.032619,-0.061646,-0.058760,0.051590,0.007967,0.065390,-0.045500
1210,1,pre-LBD-106#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.013444,0.000117,-0.004020,-0.012621,0.032116,0.033671,-0.023083,...,0.039705,0.034761,0.042621,-0.040136,0.007026,0.067041,0.021651,0.018673,0.025703,0.021640
1808,1,pre-LBD-12#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.013239,-0.040882,0.024400,-0.055079,-0.014620,0.010625,-0.064201,...,0.019777,-0.073483,0.026999,0.080754,-0.003973,-0.008127,0.048084,0.059806,0.063131,0.162505

In [73]:
comb_emb_df.sample(5)

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_758,emb_759,emb_760,emb_761,emb_762,emb_763,emb_764,emb_765,emb_766,emb_767
515,1,pre-LBD-30#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.054891,0.023616,0.029865,0.013956,-0.061379,0.063497,-0.005428,...,-0.037852,-0.038421,0.000336,0.006482,0.031445,0.033240,0.020176,-0.021619,-0.034384,-0.029052
1435,1,pre-LBD-74#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.005197,0.033889,0.046267,-0.018016,0.000173,-0.047002,0.024773,...,-0.001178,0.036760,0.023915,0.030995,0.018438,0.028437,-0.036605,-0.027379,0.004752,-0.055482
1031,0,HC-18#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.053051,-0.016040,0.003169,0.015450,-0.100921,0.042919,0.012869,...,0.030790,-0.055749,0.038751,0.018162,-0.040069,0.013775,-0.051406,0.002137,0.020295,0.014173
346,1,pre-LBD-119#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.039520,-0.009753,0.006910,0.039528,0.045146,-0.018873,-0.061653,...,0.000499,-0.002708,-0.047119,0.059782,-0.001132,-0.049402,-0.008109,-0.004787,0.003716,0.037838
51,1,pre-LBD-118#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.004838,-0.084137,0.003182,-0.020603,-0.020748,0.046657,-0.065704,...,0.030596,-0.017201,-0.024265,0.016454,-0.006532,0.011949,-0.076281,0.000632,-0.019008,0.003844

# Metadata data labeling
    - 0 -> HC
    - 1 -> unknown
    - 2 -> MCI-AD
    - 3 -> MCI- LBD

In [120]:
#metadata_path = Path("C://dev//dolphin_initial_testing//DOLPHIN//data-raw//LBD_CZ_002_metadata//preDLB_shared(PSY_RAW)")

df_metadata = pd.read_csv('C://dev//dolphin_initial_testing//DOLPHIN//data-raw//LBD_CZ_002_metadata//preDLB_shared(PSY_RAW).csv')

ParserError: Error tokenizing data. C error: Expected 44 fields in line 14, saw 47

In [74]:
def task_wise_df_creation(df, task_name):
    task_df = df[df['file_path'].str.contains(task_name)].reset_index(drop=True)
    return task_df

In [75]:
task_list = ['1_1', '3_1', '3_2', '3_3', '3_4', '3_5', '9_1', '10_1', '15_1', '16_1', '17_1', '18_1', '19_1']

task_freq_dfs = {task: task_wise_df_creation(freq_emb_df, task) for task in task_list}
task_temp_dfs = {task: task_wise_df_creation(freq_emb_df, task) for task in task_list}
task_comb_dfs = {task: task_wise_df_creation(freq_emb_df, task) for task in task_list}

In [76]:
task_freq_dfs.get("3_1").sample(15)

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_374,emb_375,emb_376,emb_377,emb_378,emb_379,emb_380,emb_381,emb_382,emb_383
93,1,pre-LBD-49#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.025570,0.081931,-0.013505,0.009018,-0.116183,-0.026485,-0.033332,...,0.039413,-0.041263,0.020840,-0.004276,-0.049099,0.034478,-0.065123,-0.015089,0.002810,-0.059363
136,1,pre-LBD-9#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.018721,0.081927,-0.010418,0.001998,-0.117634,-0.025292,-0.031785,...,0.036665,-0.038815,0.019437,-0.002878,-0.046651,0.036924,-0.064980,-0.014711,-0.004201,-0.063378
123,1,pre-LBD-78#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.019524,0.081369,-0.007641,0.009783,-0.114131,-0.033370,-0.031553,...,0.032844,-0.030420,0.023112,-0.001709,-0.052515,0.039440,-0.059261,-0.020329,-0.002682,-0.059311
24,0,HC-31#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.020676,0.081833,-0.008087,0.010638,-0.116799,-0.030684,-0.032455,...,0.034569,-0.035206,0.021831,-0.004647,-0.050852,0.039896,-0.061662,-0.019066,-0.000568,-0.057273
91,1,pre-LBD-47#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.020102,0.080821,-0.009853,0.009671,-0.114418,-0.031540,-0.032411,...,0.031674,-0.029105,0.023281,-0.000472,-0.049428,0.041171,-0.063274,-0.017340,-0.000682,-0.059505
38,1,pre-LBD-103#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.020236,0.081759,-0.008424,0.009276,-0.115209,-0.030145,-0.032695,...,0.032214,-0.032790,0.021979,-0.002656,-0.051434,0.039761,-0.061657,-0.019571,-0.002411,-0.058873
133,1,pre-LBD-87#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.020353,0.081825,-0.010217,0.008826,-0.113884,-0.028939,-0.033813,...,0.033737,-0.032606,0.020480,-0.002645,-0.051493,0.040450,-0.062977,-0.018187,0.000387,-0.059231
54,1,pre-LBD-120#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.020379,0.082506,-0.009032,0.013731,-0.116217,-0.033883,-0.034782,...,0.032991,-0.036044,0.023143,-0.004842,-0.050248,0.042101,-0.061835,-0.019287,-0.000293,-0.053892
121,1,pre-LBD-76#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.019539,0.079011,-0.015013,0.007018,-0.111438,-0.030025,-0.033130,...,0.031044,-0.027128,0.022969,0.004412,-0.047450,0.036385,-0.064244,-0.015139,-0.002766,-0.063278
100,1,pre-LBD-55#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.020786,0.080664,-0.010544,0.010554,-0.111780,-0.029734,-0.034320,...,0.034555,-0.032969,0.020447,-0.000964,-0.052547,0.038277,-0.061269,-0.018033,-0.000678,-0.059951
145,1,pre-LBD-98#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.023650,0.082128,-0.013285,0.008044,-0.113671,-0.024967,-0.032775,...,0.036425,-0.033664,0.020819,-0.001577,-0.049763,0.038362,-0.064215,-0.015112,0.000056,-0.060256
61,1,pre-LBD-18#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.021553,0.081026,-0.009876,0.007957,-0.115876,-0.031374,-0.031656,...,0.034516,-0.034468,0.021693,-0.003879,-0.051767,0.038641,-0.060882,-0.018528,-0.002593,-0.058147
138,1,pre-LBD-91#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.020727,0.081019,-0.010819,0.009694,-0.114165,-0.028424,-0.031667,...,0.037299,-0.035691,0.022536,-0.000615,-0.050098,0.040154,-0.064722,-0.018412,0.000068,-0.061039
57,1,pre-LBD-14#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.015944,0.080661,-0.006830,0.010052,-0.115370,-0.033410,-0.033333,...,0.029632,-0.032336,0.021827,-0.003415,-0.049775,0.042920,-0.060795,-0.020692,-0.004642,-0.056170
112,1,pre-LBD-67#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.021381,0.079730,-0.010148,0.008695,-0.109966,-0.030376,-0.033927,...,0.035821,-0.033162,0.019941,-0.000692,-0.050567,0.040126,-0.064558,-0.018815,0.001659,-0.062460

In [77]:
def x_y_split(df):
    embedding_cols = [c for c in df.columns if c.startswith("emb_")]
    X = df[embedding_cols].values
    y = df["label"].values
    
    return X, y

In [78]:
df_3_1 = task_freq_dfs.get("3_1")
X, y = x_y_split(df_3_1)
X.shape
y.shape

(147,)

# OPTUNA + XGBoost

In [79]:
import xgboost as xgb
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

# Defining the objective function
def objective(trial):
    param = {
        'max_depth': trial.suggest_int('max_depth', 3, 10),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1),
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000),
        'subsample': trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'gamma': trial.suggest_float('gamma', 0, 5),
    }
    
    # initializing the XGBoost model
    model = xgb.XGBClassifier(**param, 
                              tree_method = 'hist',  # Using GPU for training 
                              device =  'cuda')       # If you have multiple GPUs, you can specify the GPU ID
                              
    # if you try in the computer without GPU, just remove the last 2 params (tree_method & device)
    X, y = x_y_split(df_3_1)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
    score = cross_val_score(model, X_train, y_train, cv=10).mean()   # calculating score using cross-validation
    return score

In [80]:
import optuna

# Create and run the optimization process with 100 trials
study = optuna.create_study(study_name="preLBD_task", direction='maximize') 
study.optimize(objective, n_trials=100, show_progress_bar=True, n_jobs=-1)   

# Retrieve the best parameter values
best_params = study.best_params
print(f"\nBest parameters: {best_params}")

[I 2025-11-10 13:33:01,060] A new study created in memory with name: preLBD_task
Best trial: 1. Best value: 0.794545:   1%|          | 1/100 [00:12<19:55, 12.08s/it]

[I 2025-11-10 13:33:13,135] Trial 1 finished with value: 0.7945454545454546 and parameters: {'max_depth': 10, 'learning_rate': 0.05237129638271615, 'n_estimators': 216, 'subsample': 0.6609299165445001, 'colsample_bytree': 0.7539932157774187, 'min_child_weight': 3, 'gamma': 4.244764194118254}. Best is trial 1 with value: 0.7945454545454546.

Best trial: 1. Best value: 0.794545:   2%|▏         | 2/100 [00:17<13:45,  8.43s/it]

[I 2025-11-10 13:33:19,006] Trial 2 finished with value: 0.7845454545454545 and parameters: {'max_depth': 6, 'learning_rate': 0.08330962292419715, 'n_estimators': 353, 'subsample': 0.7105026869160295, 'colsample_bytree': 0.698523897844277, 'min_child_weight': 4, 'gamma': 3.9284379489163044}. Best is trial 1 with value: 0.7945454545454546.

Best trial: 1. Best value: 0.794545:   3%|▎         | 3/100 [00:21<10:10,  6.29s/it]

[I 2025-11-10 13:33:22,761] Trial 0 finished with value: 0.7836363636363636 and parameters: {'max_depth': 6, 'learning_rate': 0.08546960605971507, 'n_estimators': 430, 'subsample': 0.712627499774434, 'colsample_bytree': 0.5407879243843869, 'min_child_weight': 1, 'gamma': 2.9614262347277003}. Best is trial 1 with value: 0.7945454545454546.

Best trial: 4. Best value: 0.813636:   4%|▍         | 4/100 [00:27<09:54,  6.20s/it]

[I 2025-11-10 13:33:28,814] Trial 4 finished with value: 0.8136363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.05228730955979085, 'n_estimators': 308, 'subsample': 0.6228271253198983, 'colsample_bytree': 0.5784089158769181, 'min_child_weight': 7, 'gamma': 2.210183195251947}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:   5%|▌         | 5/100 [00:28<06:38,  4.20s/it]

[I 2025-11-10 13:33:29,465] Trial 3 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.0756515455591825, 'n_estimators': 584, 'subsample': 0.7229446659829755, 'colsample_bytree': 0.522262183950764, 'min_child_weight': 5, 'gamma': 4.066417279740292}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:   6%|▌         | 6/100 [00:39<10:26,  6.67s/it]

[I 2025-11-10 13:33:40,928] Trial 8 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.011723638693323336, 'n_estimators': 240, 'subsample': 0.6782894174646137, 'colsample_bytree': 0.7343264194026204, 'min_child_weight': 8, 'gamma': 2.30917502468806}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:   7%|▋         | 7/100 [00:40<07:14,  4.68s/it]

[I 2025-11-10 13:33:41,501] Trial 6 finished with value: 0.8036363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.020898620712195965, 'n_estimators': 336, 'subsample': 0.550544009472763, 'colsample_bytree': 0.9287784371711888, 'min_child_weight': 3, 'gamma': 2.5562167175107913}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:   8%|▊         | 8/100 [00:45<07:12,  4.70s/it]

[I 2025-11-10 13:33:46,259] Trial 7 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.028622082658130557, 'n_estimators': 331, 'subsample': 0.9305007400284548, 'colsample_bytree': 0.8863711983116018, 'min_child_weight': 8, 'gamma': 0.8255400945505864}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:   9%|▉         | 9/100 [00:55<09:47,  6.46s/it]

[I 2025-11-10 13:33:56,585] Trial 5 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.0898087767011117, 'n_estimators': 791, 'subsample': 0.976483228988857, 'colsample_bytree': 0.5637677273111834, 'min_child_weight': 7, 'gamma': 0.5242008661909131}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  10%|█         | 10/100 [01:05<11:14,  7.49s/it]

[I 2025-11-10 13:34:06,379] Trial 9 finished with value: 0.8136363636363637 and parameters: {'max_depth': 10, 'learning_rate': 0.052261062628710296, 'n_estimators': 497, 'subsample': 0.6458532727468136, 'colsample_bytree': 0.6981825527436862, 'min_child_weight': 9, 'gamma': 3.6199785148376495}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  11%|█         | 11/100 [01:11<10:32,  7.11s/it]

[I 2025-11-10 13:34:12,617] Trial 12 finished with value: 0.8036363636363637 and parameters: {'max_depth': 10, 'learning_rate': 0.05109745621845674, 'n_estimators': 288, 'subsample': 0.7833290895930591, 'colsample_bytree': 0.7829955293931206, 'min_child_weight': 4, 'gamma': 4.5623229119228625}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  12%|█▏        | 12/100 [01:23<12:36,  8.59s/it]

[I 2025-11-10 13:34:24,615] Trial 11 finished with value: 0.7654545454545454 and parameters: {'max_depth': 10, 'learning_rate': 0.09177959577206304, 'n_estimators': 639, 'subsample': 0.5705642773030586, 'colsample_bytree': 0.7828406094751386, 'min_child_weight': 2, 'gamma': 1.7903735107888596}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  13%|█▎        | 13/100 [01:31<12:13,  8.44s/it]

[I 2025-11-10 13:34:32,685] Trial 10 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.06425481260004799, 'n_estimators': 972, 'subsample': 0.5631642421043068, 'colsample_bytree': 0.715535124655048, 'min_child_weight': 9, 'gamma': 1.034120930919638}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  14%|█▍        | 14/100 [01:38<11:13,  7.83s/it]

[I 2025-11-10 13:34:39,111] Trial 16 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.07101694195022339, 'n_estimators': 111, 'subsample': 0.8033027425244043, 'colsample_bytree': 0.6160668589832518, 'min_child_weight': 6, 'gamma': 3.1459659514125655}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  15%|█▌        | 15/100 [01:45<10:50,  7.66s/it]

[I 2025-11-10 13:34:46,371] Trial 13 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.06988847706117483, 'n_estimators': 718, 'subsample': 0.8238103704150324, 'colsample_bytree': 0.9975705080683676, 'min_child_weight': 5, 'gamma': 4.990469557713311}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  16%|█▌        | 16/100 [01:47<08:15,  5.90s/it]

[I 2025-11-10 13:34:48,205] Trial 14 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.06988954258874792, 'n_estimators': 632, 'subsample': 0.827093711089057, 'colsample_bytree': 0.6026747734238133, 'min_child_weight': 6, 'gamma': 1.504949245271201}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  17%|█▋        | 17/100 [02:01<11:32,  8.34s/it]

[I 2025-11-10 13:35:02,219] Trial 15 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.06760310741973428, 'n_estimators': 662, 'subsample': 0.8070911174577968, 'colsample_bytree': 0.5063147760498117, 'min_child_weight': 6, 'gamma': 1.4841546500015204}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  18%|█▊        | 18/100 [02:14<13:26,  9.84s/it]

[I 2025-11-10 13:35:15,547] Trial 19 finished with value: 0.8136363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.03911597992120319, 'n_estimators': 512, 'subsample': 0.6034485722513626, 'colsample_bytree': 0.5004820443373257, 'min_child_weight': 7, 'gamma': 0.12781529365741484}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  19%|█▉        | 19/100 [02:15<09:32,  7.06s/it]

[I 2025-11-10 13:35:16,142] Trial 17 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.03906815627226556, 'n_estimators': 673, 'subsample': 0.8419472939809087, 'colsample_bytree': 0.5102161332374261, 'min_child_weight': 6, 'gamma': 1.6417262615728623}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  20%|██        | 20/100 [02:15<06:50,  5.13s/it]

[I 2025-11-10 13:35:16,768] Trial 18 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.03848445986009868, 'n_estimators': 552, 'subsample': 0.8834775206541126, 'colsample_bytree': 0.501108109934402, 'min_child_weight': 6, 'gamma': 1.5542066863978157}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  21%|██        | 21/100 [02:27<09:33,  7.26s/it]

[I 2025-11-10 13:35:28,996] Trial 20 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.037734833123093524, 'n_estimators': 503, 'subsample': 0.6068153463245102, 'colsample_bytree': 0.6374222180175388, 'min_child_weight': 10, 'gamma': 0.11903693706406449}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  22%|██▏       | 22/100 [02:57<18:16, 14.06s/it]

[I 2025-11-10 13:35:58,907] Trial 21 finished with value: 0.8036363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.09896720888128702, 'n_estimators': 847, 'subsample': 0.8818474524616634, 'colsample_bytree': 0.6529328526105461, 'min_child_weight': 5, 'gamma': 3.3833121563515576}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  23%|██▎       | 23/100 [03:00<13:29, 10.52s/it]

[I 2025-11-10 13:36:01,165] Trial 22 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.08003815686929404, 'n_estimators': 875, 'subsample': 0.744997154739556, 'colsample_bytree': 0.6368520583544002, 'min_child_weight': 5, 'gamma': 3.523835027365089}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  24%|██▍       | 24/100 [03:02<10:23,  8.20s/it]

[I 2025-11-10 13:36:03,962] Trial 23 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.0791735939230716, 'n_estimators': 936, 'subsample': 0.7433026036888485, 'colsample_bytree': 0.6342819869058608, 'min_child_weight': 10, 'gamma': 3.4563440330028996}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  25%|██▌       | 25/100 [03:11<10:25,  8.34s/it]

[I 2025-11-10 13:36:12,635] Trial 24 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.09816371572601243, 'n_estimators': 806, 'subsample': 0.9783386266961146, 'colsample_bytree': 0.5770521272434807, 'min_child_weight': 7, 'gamma': 0.6874545194294908}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  26%|██▌       | 26/100 [03:17<09:31,  7.72s/it]

[I 2025-11-10 13:36:18,891] Trial 28 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.061887962073832, 'n_estimators': 119, 'subsample': 0.5204232926101491, 'colsample_bytree': 0.5606918164174698, 'min_child_weight': 7, 'gamma': 2.213470875130741}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  27%|██▋       | 27/100 [03:35<12:52, 10.59s/it]

[I 2025-11-10 13:36:36,174] Trial 25 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.08405552483272889, 'n_estimators': 788, 'subsample': 0.74478000199568, 'colsample_bytree': 0.5765792887809272, 'min_child_weight': 7, 'gamma': 2.4465431374367688}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  28%|██▊       | 28/100 [03:39<10:36,  8.84s/it]

[I 2025-11-10 13:36:40,925] Trial 26 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.06023521591000129, 'n_estimators': 832, 'subsample': 0.7489643750195216, 'colsample_bytree': 0.5687966849108632, 'min_child_weight': 7, 'gamma': 2.5107447413636814}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  29%|██▉       | 29/100 [03:40<07:40,  6.49s/it]

[I 2025-11-10 13:36:41,937] Trial 27 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.06008892881506145, 'n_estimators': 788, 'subsample': 0.9917871974593147, 'colsample_bytree': 0.5650436830028742, 'min_child_weight': 7, 'gamma': 0.6665804660493793}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  30%|███       | 30/100 [03:57<11:00,  9.43s/it]

[I 2025-11-10 13:36:58,235] Trial 29 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.05829396498581228, 'n_estimators': 735, 'subsample': 0.9890056671809847, 'colsample_bytree': 0.5771297577759193, 'min_child_weight': 8, 'gamma': 2.8768180172622966}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  31%|███       | 31/100 [04:03<09:37,  8.38s/it]

[I 2025-11-10 13:37:04,147] Trial 32 finished with value: 0.8136363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.0896364810871704, 'n_estimators': 427, 'subsample': 0.6999354120608552, 'colsample_bytree': 0.5403210161717591, 'min_child_weight': 8, 'gamma': 2.8985123221362112}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  32%|███▏      | 32/100 [04:12<09:47,  8.64s/it]

[I 2025-11-10 13:37:13,410] Trial 30 finished with value: 0.8136363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.058782558807777614, 'n_estimators': 733, 'subsample': 0.9813910980278043, 'colsample_bytree': 0.5518262541930552, 'min_child_weight': 8, 'gamma': 2.834235873559731}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  33%|███▎      | 33/100 [04:18<08:47,  7.87s/it]

[I 2025-11-10 13:37:19,487] Trial 31 finished with value: 0.8136363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.09125071620886299, 'n_estimators': 749, 'subsample': 0.9903999732297672, 'colsample_bytree': 0.5369788625688923, 'min_child_weight': 8, 'gamma': 2.9282650499970675}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  34%|███▍      | 34/100 [04:20<06:54,  6.27s/it]

[I 2025-11-10 13:37:22,034] Trial 33 finished with value: 0.7936363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.07589600766606511, 'n_estimators': 429, 'subsample': 0.6974780528312411, 'colsample_bytree': 0.5306064378314775, 'min_child_weight': 4, 'gamma': 1.9541752988753351}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  35%|███▌      | 35/100 [04:25<06:05,  5.62s/it]

[I 2025-11-10 13:37:26,132] Trial 34 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.028780872550744907, 'n_estimators': 431, 'subsample': 0.9448116900119327, 'colsample_bytree': 0.8729078346237812, 'min_child_weight': 9, 'gamma': 1.0739347343373207}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  36%|███▌      | 36/100 [04:29<05:36,  5.26s/it]

[I 2025-11-10 13:37:30,546] Trial 36 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.02857950194944766, 'n_estimators': 208, 'subsample': 0.9360065872657607, 'colsample_bytree': 0.8291017939921507, 'min_child_weight': 9, 'gamma': 1.0138052765834669}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  37%|███▋      | 37/100 [04:32<04:56,  4.71s/it]

[I 2025-11-10 13:37:33,974] Trial 35 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.047858033406170016, 'n_estimators': 393, 'subsample': 0.9100683313581609, 'colsample_bytree': 0.8946152054079782, 'min_child_weight': 9, 'gamma': 1.0273662135198296}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  38%|███▊      | 38/100 [04:38<05:10,  5.01s/it]

[I 2025-11-10 13:37:39,672] Trial 38 finished with value: 0.8036363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.017861282216206194, 'n_estimators': 208, 'subsample': 0.9475230404463513, 'colsample_bytree': 0.8652979427241091, 'min_child_weight': 5, 'gamma': 0.39823747414785343}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  39%|███▉      | 39/100 [04:39<03:49,  3.76s/it]

[I 2025-11-10 13:37:40,529] Trial 37 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.04598320097682586, 'n_estimators': 349, 'subsample': 0.9245089456287874, 'colsample_bytree': 0.8587324377230929, 'min_child_weight': 9, 'gamma': 1.047613156108537}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  40%|████      | 40/100 [04:56<07:35,  7.60s/it]

[I 2025-11-10 13:37:57,081] Trial 39 finished with value: 0.8136363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.015099408791776014, 'n_estimators': 349, 'subsample': 0.6430774686479555, 'colsample_bytree': 0.9210532905249693, 'min_child_weight': 1, 'gamma': 0.512870044009174}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  41%|████      | 41/100 [05:06<08:13,  8.36s/it]

[I 2025-11-10 13:38:07,217] Trial 40 finished with value: 0.8036363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.0162981025565058, 'n_estimators': 578, 'subsample': 0.6472821278630827, 'colsample_bytree': 0.6793019278491079, 'min_child_weight': 3, 'gamma': 4.044016051818408}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  42%|████▏     | 42/100 [05:10<06:59,  7.23s/it]

[I 2025-11-10 13:38:11,804] Trial 41 finished with value: 0.7936363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.04600107518376329, 'n_estimators': 580, 'subsample': 0.6428565838413226, 'colsample_bytree': 0.9709823628158101, 'min_child_weight': 3, 'gamma': 4.054293269493958}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  43%|████▎     | 43/100 [05:12<05:13,  5.51s/it]

[I 2025-11-10 13:38:13,296] Trial 43 finished with value: 0.7936363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.0872376935566078, 'n_estimators': 280, 'subsample': 0.8613925962373125, 'colsample_bytree': 0.6795615516174235, 'min_child_weight': 4, 'gamma': 4.0636122599776865}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  44%|████▍     | 44/100 [05:13<04:03,  4.35s/it]

[I 2025-11-10 13:38:14,942] Trial 42 finished with value: 0.8036363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.012149310693935947, 'n_estimators': 566, 'subsample': 0.6347304484666022, 'colsample_bytree': 0.9720614980033867, 'min_child_weight': 1, 'gamma': 4.147641757743193}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  45%|████▌     | 45/100 [05:22<05:03,  5.52s/it]

[I 2025-11-10 13:38:23,191] Trial 44 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.02324364010385834, 'n_estimators': 274, 'subsample': 0.6754713481100204, 'colsample_bytree': 0.7363662395542526, 'min_child_weight': 8, 'gamma': 2.218707355517785}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  46%|████▌     | 46/100 [05:25<04:24,  4.89s/it]

[I 2025-11-10 13:38:26,622] Trial 45 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.010698406414745534, 'n_estimators': 256, 'subsample': 0.6755775760082519, 'colsample_bytree': 0.7478546489626212, 'min_child_weight': 8, 'gamma': 2.0465999572448643}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  47%|████▋     | 47/100 [05:28<03:46,  4.28s/it]

[I 2025-11-10 13:38:29,476] Trial 46 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.024548976125953515, 'n_estimators': 275, 'subsample': 0.6711541400608251, 'colsample_bytree': 0.7424784313756093, 'min_child_weight': 8, 'gamma': 4.73754425249699}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  48%|████▊     | 48/100 [05:30<03:03,  3.54s/it]

[I 2025-11-10 13:38:31,274] Trial 47 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.024133490586098337, 'n_estimators': 274, 'subsample': 0.6769508869683408, 'colsample_bytree': 0.7337457812075856, 'min_child_weight': 8, 'gamma': 2.2001293364828527}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  49%|████▉     | 49/100 [05:31<02:25,  2.86s/it]

[I 2025-11-10 13:38:32,550] Trial 48 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.026905616823687088, 'n_estimators': 161, 'subsample': 0.7808676729858322, 'colsample_bytree': 0.7896917128230285, 'min_child_weight': 6, 'gamma': 4.507525875988849}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  50%|█████     | 50/100 [05:36<02:52,  3.45s/it]

[I 2025-11-10 13:38:37,388] Trial 50 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.07508028700492608, 'n_estimators': 149, 'subsample': 0.7227105613222629, 'colsample_bytree': 0.7842229177073908, 'min_child_weight': 6, 'gamma': 1.270902109635943}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  51%|█████     | 51/100 [05:41<03:19,  4.06s/it]

[I 2025-11-10 13:38:42,877] Trial 49 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.024803573795446742, 'n_estimators': 311, 'subsample': 0.7219039522321108, 'colsample_bytree': 0.7820829592958106, 'min_child_weight': 6, 'gamma': 4.643500643278033}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  52%|█████▏    | 52/100 [05:46<03:22,  4.23s/it]

[I 2025-11-10 13:38:47,494] Trial 51 finished with value: 0.8136363636363637 and parameters: {'max_depth': 9, 'learning_rate': 0.03445035952455888, 'n_estimators': 317, 'subsample': 0.6172000920729331, 'colsample_bytree': 0.7800021513415887, 'min_child_weight': 6, 'gamma': 1.215740346241985}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  53%|█████▎    | 53/100 [05:47<02:31,  3.23s/it]

[I 2025-11-10 13:38:48,390] Trial 52 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.034600552319567185, 'n_estimators': 316, 'subsample': 0.6114903789990772, 'colsample_bytree': 0.6044606843008214, 'min_child_weight': 6, 'gamma': 1.2571723207126015}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  54%|█████▍    | 54/100 [05:51<02:48,  3.65s/it]

[I 2025-11-10 13:38:53,036] Trial 53 finished with value: 0.8136363636363637 and parameters: {'max_depth': 9, 'learning_rate': 0.031528338893243295, 'n_estimators': 315, 'subsample': 0.6107178403636543, 'colsample_bytree': 0.6077648951846906, 'min_child_weight': 7, 'gamma': 3.1280525609145964}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  55%|█████▌    | 55/100 [06:01<04:00,  5.35s/it]

[I 2025-11-10 13:39:02,361] Trial 54 finished with value: 0.8136363636363637 and parameters: {'max_depth': 9, 'learning_rate': 0.032034009657328694, 'n_estimators': 401, 'subsample': 0.601686539849879, 'colsample_bytree': 0.6090570538936324, 'min_child_weight': 10, 'gamma': 3.7826544441497285}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  56%|█████▌    | 56/100 [06:10<04:50,  6.60s/it]

[I 2025-11-10 13:39:11,880] Trial 56 finished with value: 0.8136363636363637 and parameters: {'max_depth': 9, 'learning_rate': 0.0543319524184569, 'n_estimators': 491, 'subsample': 0.5647821206616721, 'colsample_bytree': 0.689118074287827, 'min_child_weight': 10, 'gamma': 3.24068576796542}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  57%|█████▋    | 57/100 [06:11<03:21,  4.68s/it]

[I 2025-11-10 13:39:12,085] Trial 55 finished with value: 0.8136363636363637 and parameters: {'max_depth': 9, 'learning_rate': 0.06598367259382512, 'n_estimators': 482, 'subsample': 0.5763042269845358, 'colsample_bytree': 0.6003144920540812, 'min_child_weight': 9, 'gamma': 3.8391352017330154}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  58%|█████▊    | 58/100 [06:15<03:19,  4.75s/it]

[I 2025-11-10 13:39:16,994] Trial 57 finished with value: 0.8136363636363637 and parameters: {'max_depth': 9, 'learning_rate': 0.05419796424759923, 'n_estimators': 490, 'subsample': 0.5799960292661321, 'colsample_bytree': 0.715016653084461, 'min_child_weight': 10, 'gamma': 3.6935830311678814}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  59%|█████▉    | 59/100 [06:24<04:03,  5.93s/it]

[I 2025-11-10 13:39:25,668] Trial 58 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.06555124212471375, 'n_estimators': 478, 'subsample': 0.5663665732752099, 'colsample_bytree': 0.6911688528390909, 'min_child_weight': 9, 'gamma': 3.6420543282342344}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  60%|██████    | 60/100 [06:40<05:57,  8.94s/it]

[I 2025-11-10 13:39:41,621] Trial 59 finished with value: 0.8136363636363637 and parameters: {'max_depth': 10, 'learning_rate': 0.09541032339089585, 'n_estimators': 614, 'subsample': 0.7737993983892526, 'colsample_bytree': 0.709304781147005, 'min_child_weight': 9, 'gamma': 3.7989345247803237}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  61%|██████    | 61/100 [06:46<05:14,  8.07s/it]

[I 2025-11-10 13:39:47,675] Trial 61 finished with value: 0.8136363636363637 and parameters: {'max_depth': 10, 'learning_rate': 0.051468010547828486, 'n_estimators': 624, 'subsample': 0.7957395278925081, 'colsample_bytree': 0.6606833043316298, 'min_child_weight': 7, 'gamma': 1.731126394823403}. Best is trial 4 with value: 0.8136363636363637.
[I 2025-11-10 13:39:47,677] Trial 60 finished with value: 0.8136363636363637 and parameters: {'max_depth': 10, 'learning_rate': 0.049523882459627765, 'n_estimators': 686, 'subsample': 0.7836890047890145, 'colsample_bytree': 0.7043038504407517, 'min_child_weight': 7, 'gamma': 3.6858899771223768}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  63%|██████▎   | 63/100 [06:55<03:56,  6.40s/it]

[I 2025-11-10 13:39:56,582] Trial 62 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.0950360005431514, 'n_estimators': 632, 'subsample': 0.9620034448835857, 'colsample_bytree': 0.5212743935361428, 'min_child_weight': 7, 'gamma': 2.661175854639188}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  64%|██████▍   | 64/100 [07:26<07:26, 12.39s/it]

[I 2025-11-10 13:40:27,150] Trial 63 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.04333465471969946, 'n_estimators': 934, 'subsample': 0.9688971457077467, 'colsample_bytree': 0.5221666819957761, 'min_child_weight': 5, 'gamma': 4.368589578915669}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 4. Best value: 0.813636:  65%|██████▌   | 65/100 [07:34<06:33, 11.23s/it]

[I 2025-11-10 13:40:35,100] Trial 64 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.07176403221988455, 'n_estimators': 961, 'subsample': 0.5152852647027791, 'colsample_bytree': 0.5203887526735262, 'min_child_weight': 5, 'gamma': 2.668277856506055}. Best is trial 4 with value: 0.8136363636363637.

Best trial: 65. Best value: 0.823636:  66%|██████▌   | 66/100 [07:40<05:33,  9.80s/it]

[I 2025-11-10 13:40:41,080] Trial 65 finished with value: 0.8236363636363638 and parameters: {'max_depth': 5, 'learning_rate': 0.08001257951806276, 'n_estimators': 998, 'subsample': 0.7017966259166858, 'colsample_bytree': 0.8107701969894145, 'min_child_weight': 5, 'gamma': 2.667370889853929}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  67%|██████▋   | 67/100 [07:42<04:14,  7.72s/it]

[I 2025-11-10 13:40:43,434] Trial 66 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.042014912744446936, 'n_estimators': 959, 'subsample': 0.5310290403260794, 'colsample_bytree': 0.7662933081836284, 'min_child_weight': 5, 'gamma': 0.29770526238425}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  68%|██████▊   | 68/100 [07:55<05:00,  9.38s/it]

[I 2025-11-10 13:40:56,967] Trial 70 finished with value: 0.7936363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.08068928092712355, 'n_estimators': 237, 'subsample': 0.7038850388739296, 'colsample_bytree': 0.8119305312419037, 'min_child_weight': 4, 'gamma': 0.7953416687005204}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  69%|██████▉   | 69/100 [08:08<05:22, 10.40s/it]

[I 2025-11-10 13:41:09,883] Trial 67 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.08164035213932821, 'n_estimators': 873, 'subsample': 0.5226389629563558, 'colsample_bytree': 0.8086782630392862, 'min_child_weight': 8, 'gamma': 0.7547097213343048}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  70%|███████   | 70/100 [08:17<05:01, 10.04s/it]

[I 2025-11-10 13:41:19,031] Trial 68 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.0835109855077596, 'n_estimators': 892, 'subsample': 0.5336592301829232, 'colsample_bytree': 0.8274281284794538, 'min_child_weight': 8, 'gamma': 0.7777255963607783}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  71%|███████   | 71/100 [08:27<04:48,  9.94s/it]

[I 2025-11-10 13:41:28,732] Trial 69 finished with value: 0.8036363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.08407326577365341, 'n_estimators': 877, 'subsample': 0.6889403063993729, 'colsample_bytree': 0.8230776475717678, 'min_child_weight': 4, 'gamma': 0.8564048722256367}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  72%|███████▏  | 72/100 [08:37<04:37,  9.90s/it]

[I 2025-11-10 13:41:38,535] Trial 73 finished with value: 0.7936363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.07748946287770372, 'n_estimators': 383, 'subsample': 0.6909042236146286, 'colsample_bytree': 0.5870470793480158, 'min_child_weight': 4, 'gamma': 2.42521501766473}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  73%|███████▎  | 73/100 [08:43<03:56,  8.76s/it]

[I 2025-11-10 13:41:44,614] Trial 71 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.0855640249436848, 'n_estimators': 995, 'subsample': 0.761819361265675, 'colsample_bytree': 0.8335901991364265, 'min_child_weight': 8, 'gamma': 2.4168379771278063}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  74%|███████▍  | 74/100 [08:55<04:13,  9.75s/it]

[I 2025-11-10 13:41:56,676] Trial 72 finished with value: 0.8136363636363637 and parameters: {'max_depth': 4, 'learning_rate': 0.08632452950158045, 'n_estimators': 995, 'subsample': 0.7315278316597038, 'colsample_bytree': 0.5903561641602021, 'min_child_weight': 8, 'gamma': 2.34614483591164}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  75%|███████▌  | 75/100 [09:08<04:28, 10.76s/it]

[I 2025-11-10 13:42:09,812] Trial 76 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.07250750015560423, 'n_estimators': 522, 'subsample': 0.7297425227139328, 'colsample_bytree': 0.5462634016320622, 'min_child_weight': 9, 'gamma': 1.9188049378969172}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  76%|███████▌  | 76/100 [09:18<04:12, 10.52s/it]

[I 2025-11-10 13:42:19,759] Trial 74 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.06332725819591804, 'n_estimators': 988, 'subsample': 0.6610568053142014, 'colsample_bytree': 0.5872928586718725, 'min_child_weight': 9, 'gamma': 0.032628344529039066}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  77%|███████▋  | 77/100 [09:22<03:13,  8.39s/it]

[I 2025-11-10 13:42:23,182] Trial 77 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.062140870973859806, 'n_estimators': 522, 'subsample': 0.6582262796186323, 'colsample_bytree': 0.7214251866068306, 'min_child_weight': 9, 'gamma': 0.26076416454488077}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  78%|███████▊  | 78/100 [09:27<02:41,  7.35s/it]

[I 2025-11-10 13:42:28,095] Trial 75 finished with value: 0.8136363636363637 and parameters: {'max_depth': 5, 'learning_rate': 0.06366845048602891, 'n_estimators': 990, 'subsample': 0.7294817530236208, 'colsample_bytree': 0.5512592863059715, 'min_child_weight': 9, 'gamma': 1.481343006563347}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  79%|███████▉  | 79/100 [09:36<02:46,  7.92s/it]

[I 2025-11-10 13:42:37,338] Trial 81 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.020485446576397042, 'n_estimators': 180, 'subsample': 0.7137838495879578, 'colsample_bytree': 0.8926421529900531, 'min_child_weight': 7, 'gamma': 3.3124829061004224}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  80%|████████  | 80/100 [09:50<03:14,  9.73s/it]

[I 2025-11-10 13:42:51,315] Trial 78 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.06351149152408592, 'n_estimators': 822, 'subsample': 0.6576111551840773, 'colsample_bytree': 0.6279361004311806, 'min_child_weight': 9, 'gamma': 1.4902283337574302}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  81%|████████  | 81/100 [09:59<02:59,  9.47s/it]

[I 2025-11-10 13:43:00,173] Trial 80 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.06931613201872797, 'n_estimators': 757, 'subsample': 0.6309952206377424, 'colsample_bytree': 0.6446194792524996, 'min_child_weight': 7, 'gamma': 0.5378289913892484}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  82%|████████▏ | 82/100 [10:07<02:45,  9.20s/it]

[I 2025-11-10 13:43:08,760] Trial 79 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.05686750570492534, 'n_estimators': 920, 'subsample': 0.5000066279148162, 'colsample_bytree': 0.6256523865243385, 'min_child_weight': 7, 'gamma': 1.4353595255777138}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  83%|████████▎ | 83/100 [10:14<02:22,  8.37s/it]

[I 2025-11-10 13:43:15,188] Trial 82 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.05767878599510934, 'n_estimators': 774, 'subsample': 0.625878846996287, 'colsample_bytree': 0.7616043955963373, 'min_child_weight': 5, 'gamma': 1.3964388267231427}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  84%|████████▍ | 84/100 [10:26<02:34,  9.68s/it]

[I 2025-11-10 13:43:27,903] Trial 83 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.05677835448458094, 'n_estimators': 770, 'subsample': 0.6300761314669379, 'colsample_bytree': 0.6565613559306183, 'min_child_weight': 5, 'gamma': 0.528335075607653}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  85%|████████▌ | 85/100 [10:31<02:04,  8.31s/it]

[I 2025-11-10 13:43:33,023] Trial 85 finished with value: 0.8036363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.06849601960199957, 'n_estimators': 453, 'subsample': 0.846885407266223, 'colsample_bytree': 0.948695188061978, 'min_child_weight': 5, 'gamma': 4.882974069365169}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  86%|████████▌ | 86/100 [10:32<01:22,  5.90s/it]

[I 2025-11-10 13:43:33,284] Trial 84 finished with value: 0.8136363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.0576175994153275, 'n_estimators': 700, 'subsample': 0.8248190506471488, 'colsample_bytree': 0.9623585547563784, 'min_child_weight': 6, 'gamma': 4.817552476119154}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  87%|████████▋ | 87/100 [10:46<01:50,  8.48s/it]

[I 2025-11-10 13:43:47,779] Trial 86 finished with value: 0.8136363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.07433681328989329, 'n_estimators': 678, 'subsample': 0.8944665601651816, 'colsample_bytree': 0.9411671970864536, 'min_child_weight': 5, 'gamma': 4.963701431154417}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  88%|████████▊ | 88/100 [11:00<01:59,  9.93s/it]

[I 2025-11-10 13:44:01,118] Trial 87 finished with value: 0.8136363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.07524876353611702, 'n_estimators': 694, 'subsample': 0.826399331749387, 'colsample_bytree': 0.996237430082452, 'min_child_weight': 5, 'gamma': 4.872705182676401}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  89%|████████▉ | 89/100 [11:06<01:36,  8.77s/it]

[I 2025-11-10 13:44:07,164] Trial 89 finished with value: 0.7845454545454545 and parameters: {'max_depth': 6, 'learning_rate': 0.07417672338095418, 'n_estimators': 710, 'subsample': 0.9107852769379753, 'colsample_bytree': 0.9049902492902011, 'min_child_weight': 4, 'gamma': 4.4018641903195235}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  90%|█████████ | 90/100 [11:09<01:12,  7.22s/it]

[I 2025-11-10 13:44:10,787] Trial 88 finished with value: 0.8136363636363637 and parameters: {'max_depth': 7, 'learning_rate': 0.07324452030514073, 'n_estimators': 710, 'subsample': 0.9061105884927549, 'colsample_bytree': 0.9260410939820967, 'min_child_weight': 6, 'gamma': 4.259425202746808}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  91%|█████████ | 91/100 [11:20<01:14,  8.33s/it]

[I 2025-11-10 13:44:21,682] Trial 90 finished with value: 0.8136363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.0888017686965733, 'n_estimators': 714, 'subsample': 0.5966272503476178, 'colsample_bytree': 0.9111043422903858, 'min_child_weight': 10, 'gamma': 3.03400357044024}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  92%|█████████▏| 92/100 [11:22<00:52,  6.54s/it]

[I 2025-11-10 13:44:24,045] Trial 93 finished with value: 0.8136363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.08929855312926444, 'n_estimators': 240, 'subsample': 0.5954401997191388, 'colsample_bytree': 0.7302438513924584, 'min_child_weight': 10, 'gamma': 3.006979214047333}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  93%|█████████▎| 93/100 [11:24<00:35,  5.11s/it]

[I 2025-11-10 13:44:25,826] Trial 92 finished with value: 0.8136363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.08859543516482382, 'n_estimators': 377, 'subsample': 0.5921633922206863, 'colsample_bytree': 0.5005025252801152, 'min_child_weight': 6, 'gamma': 3.061074565458107}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  94%|█████████▍| 94/100 [11:32<00:35,  6.00s/it]

[I 2025-11-10 13:44:33,884] Trial 91 finished with value: 0.8136363636363637 and parameters: {'max_depth': 6, 'learning_rate': 0.06701483944094813, 'n_estimators': 653, 'subsample': 0.9288625252571733, 'colsample_bytree': 0.9054477005330187, 'min_child_weight': 6, 'gamma': 4.449347831924835}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  95%|█████████▌| 95/100 [11:47<00:43,  8.75s/it]

[I 2025-11-10 13:44:49,051] Trial 94 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.07822525723702405, 'n_estimators': 550, 'subsample': 0.5880431808934299, 'colsample_bytree': 0.5606937641491855, 'min_child_weight': 6, 'gamma': 0.9141734545021115}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  96%|█████████▌| 96/100 [11:54<00:32,  8.20s/it]

[I 2025-11-10 13:44:55,972] Trial 95 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.0772443124352036, 'n_estimators': 601, 'subsample': 0.874855680410721, 'colsample_bytree': 0.6687412757392796, 'min_child_weight': 6, 'gamma': 1.802577727141083}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  97%|█████████▋| 97/100 [11:56<00:18,  6.24s/it]

[I 2025-11-10 13:44:57,657] Trial 96 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.06994067756447428, 'n_estimators': 657, 'subsample': 0.7563376441956012, 'colsample_bytree': 0.5584606326785528, 'min_child_weight': 6, 'gamma': 1.670687567138181}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  98%|█████████▊| 98/100 [12:00<00:10,  5.49s/it]

[I 2025-11-10 13:45:01,383] Trial 97 finished with value: 0.8136363636363637 and parameters: {'max_depth': 8, 'learning_rate': 0.07783264632541503, 'n_estimators': 604, 'subsample': 0.5528024399990554, 'colsample_bytree': 0.5651168356090639, 'min_child_weight': 8, 'gamma': 0.9279264988703535}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636:  99%|█████████▉| 99/100 [12:07<00:05,  5.99s/it]

[I 2025-11-10 13:45:08,541] Trial 98 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.07044292745655996, 'n_estimators': 602, 'subsample': 0.8669882446669668, 'colsample_bytree': 0.6650198517560678, 'min_child_weight': 8, 'gamma': 1.6224998403790343}. Best is trial 65 with value: 0.8236363636363638.

Best trial: 65. Best value: 0.823636: 100%|██████████| 100/100 [12:13<00:00,  7.34s/it]

[I 2025-11-10 13:45:14,718] Trial 99 finished with value: 0.8136363636363637 and parameters: {'max_depth': 3, 'learning_rate': 0.0693070056729431, 'n_estimators': 855, 'subsample': 0.9975020518277293, 'colsample_bytree': 0.573228964957697, 'min_child_weight': 8, 'gamma': 1.1153908844214375}. Best is trial 65 with value: 0.8236363636363638.

Best parameters: {'max_depth': 5, 'learning_rate': 0.08001257951806276, 'n_estimators': 998, 'subsample': 0.7017966259166858, 'colsample_bytree': 0.8107701969894145, 'min_child_weight': 5, 'gamma': 2.667370889853929}

In [81]:
import sys, pkgutil
print("Python:", sys.executable)
print("plotly installed?", pkgutil.find_loader("plotly") is not None)

Python: c:\Users\tenNovy\miniconda3\envs\dolphin\python.exe
plotly installed? True

In [82]:
import sys
!{sys.executable} -m pip install -U "optuna[visualization]" plotly kaleido
# (Conda option) conda install -c conda-forge python-kaleido plotly

Requirement already satisfied: plotly in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (6.4.0)
Requirement already satisfied: kaleido in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (1.2.0)
Requirement already satisfied: optuna[visualization] in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (4.6.0)
Requirement already satisfied: alembic>=1.5.0 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from optuna[visualization]) (1.17.1)
Requirement already satisfied: colorlog in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from optuna[visualization]) (6.10.1)
Requirement already satisfied: numpy in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from optuna[visualization]) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from optuna[visualization]) (25.0)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from optuna[visualization]) (2.0.44)
Requirement already satisfied: tqdm in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from optuna[visualization]) (4.67.1)
Requirement already satisfied: PyYAML in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from optuna[visualization]) (6.0.3)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from plotly) (2.10.2)
Requirement already satisfied: choreographer>=1.1.1 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from kaleido) (1.2.1)
Requirement already satisfied: logistro>=1.0.8 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from kaleido) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from kaleido) (3.11.4)
Requirement already satisfied: pytest-timeout>=2.4.0 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from kaleido) (2.4.0)
Requirement already satisfied: Mako in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from alembic>=1.5.0->optuna[visualization]) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from alembic>=1.5.0->optuna[visualization]) (4.12.2)
Requirement already satisfied: simplejson>=3.19.3 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from choreographer>=1.1.1->kaleido) (3.20.2)
Requirement already satisfied: pytest>=7.0.0 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from pytest-timeout>=2.4.0->kaleido) (9.0.0)
Requirement already satisfied: greenlet>=1 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from sqlalchemy>=1.4.2->optuna[visualization]) (3.2.4)
Requirement already satisfied: colorama in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from colorlog->optuna[visualization]) (0.4.6)
Requirement already satisfied: iniconfig>=1.0.1 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido) (2.19.2)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\tennovy\miniconda3\envs\dolphin\lib\site-packages (from Mako->alembic>=1.5.0->optuna[visualization]) (3.0.3)

WARNING: optuna 4.6.0 does not provide the extra 'visualization'

In [83]:
import plotly.io as pio
pio.renderers.default = "notebook_connected"  # or "vscode", "browser"

In [86]:
from plotly.io import show
import optuna.visualization as vis

fig = vis.plot_optimization_history(study)
show(fig)

In [ ]:

from plotly.io import show
import optuna.visualization as vis

fig = vis.plot_optimization_history(study)
show(fig)

In [ ]:

fig = vis.plot_contour(study, params = ["","max_depth"])
show(fig)

[W 2025-11-10 13:51:09,763] The length of params must be greater than 1.

In [88]:

from sklearn.metrics import accuracy_score, classification_report

X, y = x_y_split(df_3_1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# Train the model with the best parameters
best_model = xgb.XGBClassifier(**best_params)
best_model.fit(X_train, y_train)

# Predict the test data
y_pred = best_model.predict(X_test)

# Calculate the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

# Generate a classification report
cr = classification_report(y_test, y_pred)
print(f"\nReport:\n{cr}")

Accuracy: 0.6888888888888889

Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        14
           1       0.69      1.00      0.82        31

    accuracy                           0.69        45
   macro avg       0.34      0.50      0.41        45
weighted avg       0.47      0.69      0.56        45

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

In [103]:
import os, json
import numpy as np
import pandas as pd
import optuna, xgboost as xgb
from typing import Dict, Tuple
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.metrics import (
    balanced_accuracy_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    RocCurveDisplay,
    ConfusionMatrixDisplay,
)

# def x_y_split(df): ...  # your splitter (must return X, y)

def _pick_device():
    try:
        _ = xgb.core.get_cuda_compute_capabilities()
        return {"tree_method": "hist", "device": "cuda"}
    except Exception:
        return {"tree_method": "hist", "device": "cpu"}

def _ensure_dir(path: str):
    os.makedirs(path, exist_ok=True)

def _save_json(d: dict, path: str):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(d, f, indent=2, ensure_ascii=False)

def make_xgb_objective(X, y, scoring: str = "balanced_accuracy", n_splits: int = 5, random_state: int = 42):
    if scoring == "balanced_accuracy":
        from sklearn.metrics import balanced_accuracy_score as metric_fn
        needs_proba = False
        eval_metric = "logloss"
    elif scoring == "roc_auc":
        from sklearn.metrics import roc_auc_score as metric_fn
        needs_proba = True
        eval_metric = "auc"
    else:
        raise ValueError("scoring must be 'balanced_accuracy' or 'roc_auc'")

    folds = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    device_kwargs = _pick_device()

    pos_ratio = float(np.mean(y))
    scale_pos_weight = ((1.0 - pos_ratio) / pos_ratio) if 0 < pos_ratio < 1 else 1.0

    def objective(trial: optuna.Trial) -> float:
        params = {
            "max_depth": trial.suggest_int("max_depth", 3, 10),
            "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
            "n_estimators": trial.suggest_int("n_estimators", 200, 1500),
            "subsample": trial.suggest_float("subsample", 0.5, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
            "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
            "gamma": trial.suggest_float("gamma", 0.0, 5.0),
            "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
            "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
            "max_delta_step": trial.suggest_int("max_delta_step", 0, 10),
            "objective": "binary:logistic",
            "eval_metric": eval_metric,
            "n_jobs": 1,  # keep each trial single-threaded
            "scale_pos_weight": scale_pos_weight,
            **device_kwargs,
        }

        scores = []
        for tr_idx, va_idx in folds.split(X, y):
            if hasattr(X, "iloc"):
                X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
                y_tr, y_va = y.iloc[tr_idx], y.iloc[va_idx]
            else:
                X_tr, X_va = X[tr_idx], X[va_idx]
                y_tr, y_va = y[tr_idx], y[va_idx]

            model = xgb.XGBClassifier(**params)
            model.fit(
                X_tr, y_tr,
                eval_set=[(X_va, y_va)],
                #early_stopping_rounds=50,
                verbose=False,
            )

            if needs_proba:
                y_score = model.predict_proba(X_va)[:, 1]
                score = metric_fn(y_va, y_score)
            else:
                y_pred = model.predict(X_va)
                score = metric_fn(y_va, y_pred)
            scores.append(score)

            trial.report(np.mean(scores), len(scores))
            if trial.should_prune():
                raise optuna.TrialPruned()

        return float(np.mean(scores))

    return objective

def _evaluate_and_save(name: str, model, X_test, y_test, out_dir: str):
    """Compute metrics, plot ROC + confusion matrix, and save everything."""
    _ensure_dir(out_dir)

    # Predictions
    y_proba = None
    try:
        y_proba = model.predict_proba(X_test)[:, 1]
    except Exception:
        pass
    y_pred = model.predict(X_test)

    # Metrics
    metrics = {}
    metrics["balanced_accuracy"] = float(balanced_accuracy_score(y_test, y_pred))
    # ROC-AUC if both classes present and proba available
    try:
        if y_proba is not None and len(np.unique(y_test)) == 2:
            metrics["roc_auc"] = float(roc_auc_score(y_test, y_proba))
        else:
            metrics["roc_auc"] = None
    except Exception:
        metrics["roc_auc"] = None

    # Classification report (as dict)
    try:
        metrics["classification_report"] = classification_report(y_test, y_pred, output_dict=True)
    except Exception:
        metrics["classification_report"] = None

    # Confusion matrix plot
    try:
        cm = confusion_matrix(y_test, y_pred)
        disp = ConfusionMatrixDisplay(cm)
        import matplotlib.pyplot as plt
        plt.figure()
        disp.plot(values_format="d")
        plt.title(f"Confusion Matrix — {name}")
        plt.savefig(os.path.join(out_dir, "confusion_matrix.png"), dpi=200, bbox_inches="tight")
        plt.close()
    except Exception:
        pass

    # ROC curve plot
    try:
        if y_proba is not None and len(np.unique(y_test)) == 2:
            import matplotlib.pyplot as plt
            plt.figure()
            RocCurveDisplay.from_predictions(y_test, y_proba)
            plt.title(f"ROC Curve — {name}")
            plt.savefig(os.path.join(out_dir, "roc_curve.png"), dpi=200, bbox_inches="tight")
            plt.close()
    except Exception:
        pass

    # Save metrics JSON
    _save_json(metrics, os.path.join(out_dir, "metrics.json"))
    return metrics

def optimize_many(
    dfs: Dict[str, pd.DataFrame],
    x_y_split_fn,
    scoring: str = "balanced_accuracy",
    n_trials: int = 100,
    n_splits: int = 5,
    random_state: int = 42,
    n_jobs_trials: int = -1,
    output_dir: str = "xgb_results",
    test_size: float = 0.20,
) -> Tuple[pd.DataFrame, Dict[str, xgb.XGBClassifier], Dict[str, optuna.Study]]:
    """
    Runs Optuna per dataset, evaluates on a held-out test set,
    and saves plots + metrics in output_dir/<dataset_name>/
    """
    results = []
    best_models: Dict[str, xgb.XGBClassifier] = {}
    studies: Dict[str, optuna.Study] = {}

    _ensure_dir(output_dir)

    for name, df in dfs.items():
        X, y = x_y_split_fn(df)

        # To numpy for fast indexing, but keep DataFrame support
        X_arr = X.values if hasattr(X, "values") else X
        y_arr = y.values if hasattr(y, "values") else y

        # Hold-out test split (kept untouched for final evaluation)
        X_train, X_test, y_train, y_test = train_test_split(
            X_arr, y_arr, test_size=test_size, random_state=random_state, stratify=y_arr
        )

        # Build objective on TRAIN ONLY
        objective = make_xgb_objective(X_train, y_train, scoring=scoring, n_splits=n_splits, random_state=random_state)

        study = optuna.create_study(
            study_name=f"{name}_{scoring}",
            direction="maximize",
            sampler=optuna.samplers.TPESampler(seed=random_state),
            pruner=optuna.pruners.MedianPruner(n_startup_trials=10),
        )
        study.optimize(objective, n_trials=n_trials, show_progress_bar=True, n_jobs=n_jobs_trials)
        studies[name] = study

        # Train final model on TRAIN using best params (with small VA split for early stopping)
        device_kwargs = _pick_device()
        pos_ratio = float(np.mean(y_train))
        spw = ((1.0 - pos_ratio) / pos_ratio) if 0 < pos_ratio < 1 else 1.0

        best_params = {
            **study.best_params,
            "objective": "binary:logistic",
            "eval_metric": "auc" if scoring == "roc_auc" else "logloss",
            "n_jobs": 0,
            "scale_pos_weight": spw,
            **device_kwargs,
        }
        final_model = xgb.XGBClassifier(**best_params)

        # Early stopping split inside TRAIN
        X_tr, X_va, y_tr, y_va = train_test_split(
            X_train, y_train, test_size=0.15, random_state=random_state, stratify=y_train
        )
        final_model.fit(
            X_tr, y_tr,
            eval_set=[(X_va, y_va)],
            #early_stopping_rounds=50,
            verbose=False,
        )

        # Save per-dataset artifacts
        ds_out = os.path.join(output_dir, name)
        _ensure_dir(ds_out)

        # Evaluate on TEST and save plots/metrics
        metrics = _evaluate_and_save(name, final_model, X_test, y_test, ds_out)

        # Save best params + study summary
        _save_json({"best_params": study.best_params, "best_value": study.best_value}, os.path.join(ds_out, "best.json"))

        # Optional: save model
        try:
            import joblib
            joblib.dump(final_model, os.path.join(ds_out, "model.joblib"))
        except Exception:
            pass

        best_models[name] = final_model
        results.append({
            "dataset": name,
            "cv_best_value": study.best_value,
            "test_balanced_accuracy": metrics.get("balanced_accuracy"),
            "test_roc_auc": metrics.get("roc_auc"),
            "n_trials": len(study.trials),
        })

    summary_df = pd.DataFrame(results).sort_values(by="test_balanced_accuracy", ascending=False).reset_index(drop=True)
    # Save a global summary too
    summary_df.to_csv(os.path.join(output_dir, "summary.csv"), index=False)
    return summary_df, best_models, studies

In [108]:
datasets = task_freq_dfs

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    #    scoring="balanced_accuracy",     # or "roc_auc"
    scoring="roc_auc",    
    n_trials=200,
    n_splits=5,
    output_dir="xgb_results_freq",
)
print(summary)

[I 2025-11-10 17:19:44,788] A new study created in memory with name: 1_1_roc_auc
Best trial: 2. Best value: 0.5:   1%|          | 2/200 [00:02<02:59,  1.10it/s]

[I 2025-11-10 17:19:46,823] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.07816402654628794, 'n_estimators': 302, 'subsample': 0.9305866600928967, 'colsample_bytree': 0.7476299925454323, 'min_child_weight': 9, 'gamma': 4.96495822320594, 'reg_alpha': 0.019055026833003037, 'reg_lambda': 1.3866222154916543, 'max_delta_step': 10}. Best is trial 2 with value: 0.5.
[I 2025-11-10 17:19:46,931] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.15035332672088908, 'n_estimators': 298, 'subsample': 0.6189913828630448, 'colsample_bytree': 0.9054412308622102, 'min_child_weight': 6, 'gamma': 1.4344530953210315, 'reg_alpha': 1.5621882627585145e-07, 'reg_lambda': 2.025153869580495e-05, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▏         | 3/200 [00:03<03:12,  1.02it/s]

[I 2025-11-10 17:19:47,993] Trial 3 finished with value: 0.3721052631578948 and parameters: {'max_depth': 5, 'learning_rate': 0.03111705586678764, 'n_estimators': 477, 'subsample': 0.5980682618684164, 'colsample_bytree': 0.689598633661928, 'min_child_weight': 3, 'gamma': 1.0089727485237976, 'reg_alpha': 0.06537767098335145, 'reg_lambda': 0.015787969145791916, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.
[I 2025-11-10 17:19:48,081] Trial 1 finished with value: 0.47247563352826505 and parameters: {'max_depth': 7, 'learning_rate': 0.10781833311261461, 'n_estimators': 620, 'subsample': 0.835874124272041, 'colsample_bytree': 0.674981409085678, 'min_child_weight': 4, 'gamma': 3.861814318283826, 'reg_alpha': 8.749654415097207e-05, 'reg_lambda': 6.922404249870502e-06, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▎         | 5/200 [00:03<01:48,  1.79it/s]

[I 2025-11-10 17:19:48,473] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.15069347697609742, 'n_estimators': 309, 'subsample': 0.5210142717863371, 'colsample_bytree': 0.7736586689895056, 'min_child_weight': 6, 'gamma': 2.579828095221556, 'reg_alpha': 0.0004675325913990989, 'reg_lambda': 0.42026956306474633, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 4. Best value: 0.53:   3%|▎         | 6/200 [00:05<02:45,  1.17it/s]

[I 2025-11-10 17:19:50,059] Trial 4 finished with value: 0.53 and parameters: {'max_depth': 3, 'learning_rate': 0.06101238778431767, 'n_estimators': 621, 'subsample': 0.8549356274484927, 'colsample_bytree': 0.9989480167292866, 'min_child_weight': 5, 'gamma': 2.2204045235210836, 'reg_alpha': 0.5419169554653852, 'reg_lambda': 0.00042148432599688597, 'max_delta_step': 6}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:   4%|▎         | 7/200 [00:08<04:44,  1.47s/it]

[I 2025-11-10 17:19:53,029] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.07853527612162985, 'n_estimators': 877, 'subsample': 0.8588029451096881, 'colsample_bytree': 0.9384324162217685, 'min_child_weight': 9, 'gamma': 1.2420553616363446, 'reg_alpha': 0.08329274911192905, 'reg_lambda': 0.00038518723625358993, 'max_delta_step': 7}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:   4%|▍         | 8/200 [00:08<03:57,  1.24s/it]

[I 2025-11-10 17:19:53,705] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.013798016901488805, 'n_estimators': 1172, 'subsample': 0.5147944672054869, 'colsample_bytree': 0.6727158402477098, 'min_child_weight': 7, 'gamma': 1.0347886491731022, 'reg_alpha': 0.010707398321689822, 'reg_lambda': 3.3822202115510993e-06, 'max_delta_step': 4}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:   4%|▍         | 9/200 [00:10<04:08,  1.30s/it]

[I 2025-11-10 17:19:55,161] Trial 9 finished with value: 0.3877777777777778 and parameters: {'max_depth': 5, 'learning_rate': 0.020382631195650255, 'n_estimators': 626, 'subsample': 0.9254791835645968, 'colsample_bytree': 0.5153508673309353, 'min_child_weight': 2, 'gamma': 3.9920255557786217, 'reg_alpha': 0.0001661859602610948, 'reg_lambda': 0.12557436864006494, 'max_delta_step': 3}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:   5%|▌         | 10/200 [00:11<03:54,  1.24s/it]

[I 2025-11-10 17:19:56,240] Trial 6 finished with value: 0.42522417153996106 and parameters: {'max_depth': 8, 'learning_rate': 0.11787903086162217, 'n_estimators': 1204, 'subsample': 0.9917698024548729, 'colsample_bytree': 0.6288576181989444, 'min_child_weight': 2, 'gamma': 2.047326444044158, 'reg_alpha': 0.021775734555190156, 'reg_lambda': 4.908556275458567e-07, 'max_delta_step': 6}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:   6%|▌         | 11/200 [00:11<03:05,  1.02it/s]

[I 2025-11-10 17:19:56,629] Trial 12 pruned.

Best trial: 4. Best value: 0.53:   6%|▌         | 12/200 [00:13<03:40,  1.17s/it]

[I 2025-11-10 17:19:58,254] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.07198528116640814, 'n_estimators': 858, 'subsample': 0.62000107921915, 'colsample_bytree': 0.7554698777336885, 'min_child_weight': 8, 'gamma': 3.2814103184702144, 'reg_alpha': 3.5866524174730624e-05, 'reg_lambda': 7.324008664249095, 'max_delta_step': 7}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:   6%|▋         | 13/200 [00:14<03:46,  1.21s/it]

[I 2025-11-10 17:19:59,546] Trial 15 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.23454686118693235, 'n_estimators': 205, 'subsample': 0.7410618157775182, 'colsample_bytree': 0.9955099694874021, 'min_child_weight': 5, 'gamma': 0.1529513889923988, 'reg_alpha': 3.645298683872395e-08, 'reg_lambda': 0.00040104943126450924, 'max_delta_step': 10}. Best is trial 4 with value: 0.53.
[I 2025-11-10 17:19:59,579] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.08622659979614189, 'n_estimators': 1212, 'subsample': 0.6974659021984738, 'colsample_bytree': 0.7763136025835301, 'min_child_weight': 7, 'gamma': 1.5629692162491442, 'reg_alpha': 1.7948656246962015e-08, 'reg_lambda': 6.10261057504594e-06, 'max_delta_step': 4}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:   8%|▊         | 15/200 [00:16<03:14,  1.05s/it]

[I 2025-11-10 17:20:01,280] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.21546187229031577, 'n_estimators': 907, 'subsample': 0.6975916856028604, 'colsample_bytree': 0.997516795300266, 'min_child_weight': 7, 'gamma': 0.0033480320402317076, 'reg_alpha': 1.1560892986423366e-08, 'reg_lambda': 0.00016096046399332044, 'max_delta_step': 0}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:   8%|▊         | 16/200 [00:17<03:15,  1.07s/it]

[I 2025-11-10 17:20:02,384] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.29591884604914587, 'n_estimators': 436, 'subsample': 0.7407694438031016, 'colsample_bytree': 0.875646954512959, 'min_child_weight': 7, 'gamma': 2.048660048158494, 'reg_alpha': 1.171699694754173e-08, 'reg_lambda': 1.7903205960379065e-08, 'max_delta_step': 0}. Best is trial 4 with value: 0.53.
[I 2025-11-10 17:20:02,470] Trial 17 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.29562066107451246, 'n_estimators': 444, 'subsample': 0.792498264728524, 'colsample_bytree': 0.8713286842400364, 'min_child_weight': 4, 'gamma': 2.447758660485442, 'reg_alpha': 5.033107175527492, 'reg_lambda': 1.1831565445603483e-08, 'max_delta_step': 0}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:   9%|▉         | 18/200 [00:18<02:36,  1.16it/s]

[I 2025-11-10 17:20:03,521] Trial 19 pruned.

Best trial: 4. Best value: 0.53:  10%|▉         | 19/200 [00:19<02:41,  1.12it/s]

[I 2025-11-10 17:20:04,519] Trial 13 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.29340055882472793, 'n_estimators': 1450, 'subsample': 0.7372393008812453, 'colsample_bytree': 0.9896607665043754, 'min_child_weight': 4, 'gamma': 0.009786233652059995, 'reg_alpha': 5.798775400903053, 'reg_lambda': 1.1374581823020635e-08, 'max_delta_step': 0}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  10%|█         | 20/200 [00:19<02:10,  1.38it/s]

[I 2025-11-10 17:20:04,729] Trial 21 pruned.

Best trial: 4. Best value: 0.53:  10%|█         | 21/200 [00:21<02:41,  1.11it/s]

[I 2025-11-10 17:20:06,136] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.04718929343622044, 'n_estimators': 737, 'subsample': 0.6156342635894093, 'colsample_bytree': 0.8478267113459057, 'min_child_weight': 10, 'gamma': 3.251735964061356, 'reg_alpha': 1.9029461047931697e-06, 'reg_lambda': 0.014325974001452146, 'max_delta_step': 9}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  11%|█         | 22/200 [00:23<03:35,  1.21s/it]

[I 2025-11-10 17:20:08,185] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.043505360907989045, 'n_estimators': 716, 'subsample': 0.6196491173700156, 'colsample_bytree': 0.8250641115476001, 'min_child_weight': 10, 'gamma': 1.6695362657679897, 'reg_alpha': 7.547496150478301e-07, 'reg_lambda': 3.42163512749868e-05, 'max_delta_step': 9}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  12%|█▏        | 24/200 [00:23<02:05,  1.40it/s]

[I 2025-11-10 17:20:08,446] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.15802453125683688, 'n_estimators': 287, 'subsample': 0.9485084194445734, 'colsample_bytree': 0.8079534994152602, 'min_child_weight': 10, 'gamma': 4.766518663924252, 'reg_alpha': 0.4542745712605946, 'reg_lambda': 0.0017925952091178935, 'max_delta_step': 10}. Best is trial 4 with value: 0.53.
[I 2025-11-10 17:20:08,569] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.1458541956895037, 'n_estimators': 722, 'subsample': 0.6651322312259371, 'colsample_bytree': 0.9223108546906179, 'min_child_weight': 10, 'gamma': 3.5308507763120596, 'reg_alpha': 2.511487442522934e-06, 'reg_lambda': 0.0034939222700154583, 'max_delta_step': 5}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  12%|█▎        | 25/200 [00:24<02:10,  1.34it/s]

[I 2025-11-10 17:20:09,402] Trial 18 finished with value: 0.4917543859649123 and parameters: {'max_depth': 10, 'learning_rate': 0.04923861037198026, 'n_estimators': 1436, 'subsample': 0.8040868649192099, 'colsample_bytree': 0.8864065960357548, 'min_child_weight': 4, 'gamma': 2.441349918264512, 'reg_alpha': 4.096641323377368, 'reg_lambda': 0.006253898682432785, 'max_delta_step': 9}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  13%|█▎        | 26/200 [00:25<01:58,  1.46it/s]

[I 2025-11-10 17:20:09,936] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.15211052216379534, 'n_estimators': 287, 'subsample': 0.989309701786293, 'colsample_bytree': 0.9360070694039297, 'min_child_weight': 6, 'gamma': 4.857343623458082, 'reg_alpha': 0.39104001948921263, 'reg_lambda': 0.001598636760924842, 'max_delta_step': 10}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  14%|█▎        | 27/200 [00:25<01:46,  1.62it/s]

[I 2025-11-10 17:20:10,387] Trial 27 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.06524188890951164, 'n_estimators': 337, 'subsample': 0.9039273816071515, 'colsample_bytree': 0.7157277991364678, 'min_child_weight': 6, 'gamma': 4.413818545611667, 'reg_alpha': 0.002644852403964785, 'reg_lambda': 1.8570541492643376e-07, 'max_delta_step': 10}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  14%|█▍        | 28/200 [00:25<01:27,  1.96it/s]

[I 2025-11-10 17:20:10,619] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.11628598380962407, 'n_estimators': 375, 'subsample': 0.9161840002938293, 'colsample_bytree': 0.9431043484128191, 'min_child_weight': 6, 'gamma': 4.906435143506389, 'reg_alpha': 0.0033712219516288822, 'reg_lambda': 3.8618170714800676e-07, 'max_delta_step': 10}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  14%|█▍        | 29/200 [00:26<01:56,  1.47it/s]

[I 2025-11-10 17:20:11,722] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.09812721317014006, 'n_estimators': 205, 'subsample': 0.5653749172449836, 'colsample_bytree': 0.6061431704071929, 'min_child_weight': 8, 'gamma': 0.3992548270729783, 'reg_alpha': 1.7561007317022652e-05, 'reg_lambda': 0.09540030060978376, 'max_delta_step': 8}. Best is trial 4 with value: 0.53.
[I 2025-11-10 17:20:11,735] Trial 28 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.09964112485511817, 'n_estimators': 404, 'subsample': 0.9070907508541187, 'colsample_bytree': 0.9521346512736174, 'min_child_weight': 6, 'gamma': 4.752859436773845, 'reg_alpha': 0.003497592768161894, 'reg_lambda': 3.9919211245306077e-07, 'max_delta_step': 10}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  16%|█▌        | 31/200 [00:27<01:38,  1.72it/s]

[I 2025-11-10 17:20:12,661] Trial 29 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.09795593129759401, 'n_estimators': 516, 'subsample': 0.9299623706823308, 'colsample_bytree': 0.7246239278932861, 'min_child_weight': 8, 'gamma': 0.4484581560626201, 'reg_alpha': 0.003246791113338105, 'reg_lambda': 7.164638222506442e-07, 'max_delta_step': 8}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  16%|█▌        | 32/200 [00:28<01:27,  1.92it/s]

[I 2025-11-10 17:20:12,992] Trial 30 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.09468024382295268, 'n_estimators': 491, 'subsample': 0.9534528769878592, 'colsample_bytree': 0.6182571100147181, 'min_child_weight': 8, 'gamma': 0.5652276603900387, 'reg_alpha': 0.0013641182244505657, 'reg_lambda': 0.421074616005289, 'max_delta_step': 8}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  16%|█▋        | 33/200 [00:29<02:02,  1.36it/s]

[I 2025-11-10 17:20:14,333] Trial 33 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.034191865658519414, 'n_estimators': 521, 'subsample': 0.8427018126264505, 'colsample_bytree': 0.7105972691651792, 'min_child_weight': 8, 'gamma': 2.8615556078769435, 'reg_alpha': 0.5336643743489923, 'reg_lambda': 1.8479368247720315e-05, 'max_delta_step': 8}. Best is trial 4 with value: 0.53.
[I 2025-11-10 17:20:14,429] Trial 32 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03145999529232173, 'n_estimators': 526, 'subsample': 0.8400908161114308, 'colsample_bytree': 0.7230082649711619, 'min_child_weight': 8, 'gamma': 4.007419230240416, 'reg_alpha': 0.47892222290725284, 'reg_lambda': 1.015789340942324, 'max_delta_step': 8}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  18%|█▊        | 35/200 [00:30<01:28,  1.86it/s]

[I 2025-11-10 17:20:14,857] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.19756250456991967, 'n_estimators': 310, 'subsample': 0.5025883393057109, 'colsample_bytree': 0.7639128613714117, 'min_child_weight': 5, 'gamma': 2.9448659330900875, 'reg_alpha': 0.11058656270791428, 'reg_lambda': 1.0364873834865997, 'max_delta_step': 2}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  18%|█▊        | 36/200 [00:30<01:26,  1.89it/s]

[I 2025-11-10 17:20:15,388] Trial 38 pruned.

Best trial: 4. Best value: 0.53:  18%|█▊        | 37/200 [00:31<01:31,  1.79it/s]

[I 2025-11-10 17:20:16,032] Trial 39 pruned.

Best trial: 4. Best value: 0.53:  19%|█▉        | 38/200 [00:31<01:17,  2.09it/s]

[I 2025-11-10 17:20:16,286] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.18558487091759143, 'n_estimators': 521, 'subsample': 0.5010646255932438, 'colsample_bytree': 0.7789913053988077, 'min_child_weight': 5, 'gamma': 2.7607231627210664, 'reg_alpha': 0.0008777927851376543, 'reg_lambda': 1.363868287211911, 'max_delta_step': 2}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  20%|█▉        | 39/200 [00:33<02:02,  1.31it/s]

[I 2025-11-10 17:20:17,798] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.19441673058682823, 'n_estimators': 311, 'subsample': 0.5205541931568942, 'colsample_bytree': 0.7856887318330276, 'min_child_weight': 5, 'gamma': 4.148638906454615, 'reg_alpha': 0.06020883791741879, 'reg_lambda': 1.4002903206883113, 'max_delta_step': 2}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  20%|██        | 40/200 [00:33<01:44,  1.52it/s]

[I 2025-11-10 17:20:18,186] Trial 37 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.19650233926625835, 'n_estimators': 299, 'subsample': 0.5064178982950972, 'colsample_bytree': 0.7809541825539176, 'min_child_weight': 5, 'gamma': 1.3069483440005565, 'reg_alpha': 0.04400203198671776, 'reg_lambda': 0.10239149665863029, 'max_delta_step': 2}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  20%|██        | 41/200 [00:35<02:47,  1.05s/it]

[I 2025-11-10 17:20:20,215] Trial 40 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06386481418771964, 'n_estimators': 608, 'subsample': 0.6595803975361414, 'colsample_bytree': 0.5092399680243425, 'min_child_weight': 9, 'gamma': 1.0072647158780446, 'reg_alpha': 0.016616340735842755, 'reg_lambda': 1.9803443323399052e-06, 'max_delta_step': 6}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  21%|██        | 42/200 [00:35<02:06,  1.24it/s]

[I 2025-11-10 17:20:20,418] Trial 41 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.01009201453690694, 'n_estimators': 628, 'subsample': 0.6616789534283901, 'colsample_bytree': 0.5813956705749377, 'min_child_weight': 7, 'gamma': 1.087915775660885, 'reg_alpha': 0.019706320532741718, 'reg_lambda': 3.002351426130069e-06, 'max_delta_step': 6}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  22%|██▏       | 43/200 [00:36<02:18,  1.13it/s]

[I 2025-11-10 17:20:21,492] Trial 43 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.011571285326076562, 'n_estimators': 621, 'subsample': 0.6581316630586805, 'colsample_bytree': 0.5168893312175127, 'min_child_weight': 9, 'gamma': 1.011846482442968, 'reg_alpha': 3.2538800109687075e-05, 'reg_lambda': 2.791241971283149e-06, 'max_delta_step': 6}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  22%|██▏       | 44/200 [00:37<01:51,  1.40it/s]

[I 2025-11-10 17:20:21,798] Trial 42 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.07156875754928484, 'n_estimators': 623, 'subsample': 0.6617733801547819, 'colsample_bytree': 0.9725115259434745, 'min_child_weight': 9, 'gamma': 1.1012563881641655, 'reg_alpha': 0.00010230084688177676, 'reg_lambda': 2.046041450094659e-06, 'max_delta_step': 6}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  22%|██▎       | 45/200 [00:41<04:29,  1.74s/it]

[I 2025-11-10 17:20:25,967] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.017555284078952214, 'n_estimators': 980, 'subsample': 0.5379121427292961, 'colsample_bytree': 0.6646803121966203, 'min_child_weight': 7, 'gamma': 2.224898935548775, 'reg_alpha': 0.00012613215577452055, 'reg_lambda': 1.3881157309200806e-05, 'max_delta_step': 4}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  23%|██▎       | 46/200 [00:41<03:17,  1.29s/it]

[I 2025-11-10 17:20:26,178] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.01896260552280264, 'n_estimators': 1233, 'subsample': 0.5430270117877978, 'colsample_bytree': 0.6705422633729626, 'min_child_weight': 7, 'gamma': 0.7193209684832309, 'reg_alpha': 9.345185894516715e-05, 'reg_lambda': 5.131984264353263e-06, 'max_delta_step': 4}. Best is trial 4 with value: 0.53.
[I 2025-11-10 17:20:26,198] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.018105520336650194, 'n_estimators': 1138, 'subsample': 0.5452125776496138, 'colsample_bytree': 0.6501697686975104, 'min_child_weight': 9, 'gamma': 1.7349439954037857, 'reg_alpha': 0.00012208924869463244, 'reg_lambda': 1.2543975955637867e-05, 'max_delta_step': 4}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  24%|██▍       | 48/200 [00:42<02:07,  1.19it/s]

[I 2025-11-10 17:20:26,822] Trial 47 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.01696586273713843, 'n_estimators': 1058, 'subsample': 0.5454707751397412, 'colsample_bytree': 0.6683439821577343, 'min_child_weight': 7, 'gamma': 1.839655016102233, 'reg_alpha': 6.736037016309799e-08, 'reg_lambda': 1.0882828817188709e-05, 'max_delta_step': 4}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  24%|██▍       | 49/200 [00:45<03:45,  1.50s/it]

[I 2025-11-10 17:20:30,320] Trial 50 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.08228206034538559, 'n_estimators': 789, 'subsample': 0.8666906567852211, 'colsample_bytree': 0.9008328706356782, 'min_child_weight': 6, 'gamma': 3.492859724620991, 'reg_alpha': 0.006733178030702109, 'reg_lambda': 7.831409373252758, 'max_delta_step': 3}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  25%|██▌       | 50/200 [00:45<03:02,  1.22s/it]

[I 2025-11-10 17:20:30,741] Trial 51 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.24784413013057352, 'n_estimators': 806, 'subsample': 0.8734540387713884, 'colsample_bytree': 0.8989194813095226, 'min_child_weight': 6, 'gamma': 1.4609208007646122, 'reg_alpha': 0.010369007797634496, 'reg_lambda': 0.00015599718712500508, 'max_delta_step': 1}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  26%|██▌       | 51/200 [00:46<02:33,  1.03s/it]

[I 2025-11-10 17:20:31,274] Trial 49 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.08115051519255011, 'n_estimators': 1027, 'subsample': 0.8688165784544535, 'colsample_bytree': 0.9079563322343591, 'min_child_weight': 6, 'gamma': 1.5943328274868038, 'reg_alpha': 0.007671796895963665, 'reg_lambda': 7.143767430778767, 'max_delta_step': 3}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  26%|██▌       | 52/200 [00:46<02:09,  1.15it/s]

[I 2025-11-10 17:20:31,738] Trial 48 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.08181200498354525, 'n_estimators': 1176, 'subsample': 0.8828607198215133, 'colsample_bytree': 0.7390186260906707, 'min_child_weight': 6, 'gamma': 0.7276865549524245, 'reg_alpha': 0.008089493809521597, 'reg_lambda': 0.00019904790550447885, 'max_delta_step': 3}. Best is trial 4 with value: 0.53.

Best trial: 4. Best value: 0.53:  26%|██▋       | 53/200 [00:47<01:50,  1.33it/s]

[I 2025-11-10 17:20:32,194] Trial 53 pruned.

Best trial: 52. Best value: 0.556491:  27%|██▋       | 54/200 [00:47<01:37,  1.50it/s]

[I 2025-11-10 17:20:32,641] Trial 52 finished with value: 0.5564912280701754 and parameters: {'max_depth': 10, 'learning_rate': 0.24975961724865708, 'n_estimators': 429, 'subsample': 0.5914934958386409, 'colsample_bytree': 0.7436487244440564, 'min_child_weight': 4, 'gamma': 1.5633687454023124, 'reg_alpha': 0.14199241772743976, 'reg_lambda': 0.00016506583797585303, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  28%|██▊       | 55/200 [00:48<01:36,  1.50it/s]

[I 2025-11-10 17:20:33,304] Trial 57 pruned.

Best trial: 52. Best value: 0.556491:  28%|██▊       | 56/200 [00:49<02:03,  1.17it/s]

[I 2025-11-10 17:20:34,625] Trial 58 finished with value: 0.5442690058479532 and parameters: {'max_depth': 10, 'learning_rate': 0.023935047873054883, 'n_estimators': 254, 'subsample': 0.5938934825375007, 'colsample_bytree': 0.6885158027839017, 'min_child_weight': 4, 'gamma': 1.9294926578364755, 'reg_alpha': 1.9161989064009617, 'reg_lambda': 5.863559735396661e-05, 'max_delta_step': 5}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  28%|██▊       | 57/200 [00:51<02:34,  1.08s/it]

[I 2025-11-10 17:20:36,240] Trial 59 finished with value: 0.5442690058479532 and parameters: {'max_depth': 10, 'learning_rate': 0.25287132572610665, 'n_estimators': 229, 'subsample': 0.5916414675092905, 'colsample_bytree': 0.6950794654415262, 'min_child_weight': 4, 'gamma': 1.9175372207742405, 'reg_alpha': 2.2493547906587614, 'reg_lambda': 7.313969344653826e-05, 'max_delta_step': 5}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  29%|██▉       | 58/200 [00:52<02:20,  1.01it/s]

[I 2025-11-10 17:20:37,022] Trial 60 pruned.

Best trial: 52. Best value: 0.556491:  30%|██▉       | 59/200 [00:52<01:52,  1.26it/s]

[I 2025-11-10 17:20:37,352] Trial 61 pruned.

Best trial: 52. Best value: 0.556491:  30%|███       | 60/200 [00:53<02:01,  1.16it/s]

[I 2025-11-10 17:20:38,383] Trial 54 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.03839874307500568, 'n_estimators': 1357, 'subsample': 0.8202762867243372, 'colsample_bytree': 0.9748045101323385, 'min_child_weight': 9, 'gamma': 1.2622583806275882, 'reg_alpha': 0.153595222027851, 'reg_lambda': 0.00016971615312721546, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  30%|███       | 61/200 [00:53<01:35,  1.45it/s]

[I 2025-11-10 17:20:38,654] Trial 55 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.12784794048619177, 'n_estimators': 1338, 'subsample': 0.7704892725066319, 'colsample_bytree': 0.9762183275885472, 'min_child_weight': 9, 'gamma': 2.2587994648508376, 'reg_alpha': 0.2264458714359344, 'reg_lambda': 0.0004919761195482915, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  31%|███       | 62/200 [00:54<01:40,  1.38it/s]

[I 2025-11-10 17:20:39,472] Trial 62 finished with value: 0.4925146198830409 and parameters: {'max_depth': 10, 'learning_rate': 0.22501596161158788, 'n_estimators': 388, 'subsample': 0.6344577552476185, 'colsample_bytree': 0.7579588870062044, 'min_child_weight': 4, 'gamma': 1.9181765487134523, 'reg_alpha': 2.2582707529328356, 'reg_lambda': 0.0006347301234907631, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  32%|███▏      | 63/200 [00:54<01:18,  1.74it/s]

[I 2025-11-10 17:20:39,686] Trial 56 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.037913603956247495, 'n_estimators': 1356, 'subsample': 0.7144039986606031, 'colsample_bytree': 0.9737491154353108, 'min_child_weight': 9, 'gamma': 1.2274833226013289, 'reg_alpha': 0.13511004329810897, 'reg_lambda': 0.0008140186441162076, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  32%|███▎      | 65/200 [00:55<01:09,  1.93it/s]

[I 2025-11-10 17:20:40,583] Trial 63 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.024847148826171818, 'n_estimators': 381, 'subsample': 0.6383609153799983, 'colsample_bytree': 0.8361506402966865, 'min_child_weight': 4, 'gamma': 1.8469531278990239, 'reg_alpha': 7.283395261393881, 'reg_lambda': 0.0005913889261674238, 'max_delta_step': 9}. Best is trial 52 with value: 0.5564912280701754.
[I 2025-11-10 17:20:40,751] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.056022073017526354, 'n_estimators': 376, 'subsample': 0.5956656402967513, 'colsample_bytree': 0.8311682370234772, 'min_child_weight': 4, 'gamma': 1.8597796527590411, 'reg_alpha': 4.011760826411884, 'reg_lambda': 2.835110278982591e-05, 'max_delta_step': 5}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  33%|███▎      | 66/200 [00:56<00:56,  2.36it/s]

[I 2025-11-10 17:20:40,950] Trial 65 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.2692290695967386, 'n_estimators': 240, 'subsample': 0.6017505673315344, 'colsample_bytree': 0.8278901156439337, 'min_child_weight': 4, 'gamma': 2.5974479441620466, 'reg_alpha': 8.503706677359268, 'reg_lambda': 2.4659544036561307e-05, 'max_delta_step': 9}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  34%|███▎      | 67/200 [00:56<00:50,  2.62it/s]

[I 2025-11-10 17:20:41,232] Trial 66 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05534703730376061, 'n_estimators': 249, 'subsample': 0.6068886268340982, 'colsample_bytree': 0.8347798794884607, 'min_child_weight': 4, 'gamma': 2.605887894720829, 'reg_alpha': 6.057898966076198, 'reg_lambda': 0.37093986962892084, 'max_delta_step': 9}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  34%|███▍      | 68/200 [00:56<00:50,  2.62it/s]

[I 2025-11-10 17:20:41,617] Trial 69 pruned.

Best trial: 52. Best value: 0.556491:  34%|███▍      | 69/200 [00:57<00:45,  2.87it/s]

[I 2025-11-10 17:20:41,886] Trial 70 pruned.

Best trial: 52. Best value: 0.556491:  36%|███▌      | 71/200 [00:57<00:35,  3.60it/s]

[I 2025-11-10 17:20:42,192] Trial 67 finished with value: 0.4973099415204678 and parameters: {'max_depth': 10, 'learning_rate': 0.054348552733749854, 'n_estimators': 249, 'subsample': 0.5985320801313849, 'colsample_bytree': 0.7320711256121007, 'min_child_weight': 4, 'gamma': 2.596434696576078, 'reg_alpha': 1.347778730168772, 'reg_lambda': 2.6049348173433793e-05, 'max_delta_step': 5}. Best is trial 52 with value: 0.5564912280701754.
[I 2025-11-10 17:20:42,335] Trial 72 pruned.

Best trial: 52. Best value: 0.556491:  36%|███▌      | 72/200 [00:57<00:33,  3.80it/s]

[I 2025-11-10 17:20:42,558] Trial 68 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.25930522905386977, 'n_estimators': 246, 'subsample': 0.608765375289895, 'colsample_bytree': 0.735890322460153, 'min_child_weight': 5, 'gamma': 2.5464909431698253, 'reg_alpha': 0.9446607323367251, 'reg_lambda': 0.2783796687634299, 'max_delta_step': 9}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  36%|███▋      | 73/200 [00:58<01:09,  1.82it/s]

[I 2025-11-10 17:20:43,778] Trial 71 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.15138020679262118, 'n_estimators': 337, 'subsample': 0.5261214163167769, 'colsample_bytree': 0.8028941679651324, 'min_child_weight': 5, 'gamma': 1.6617797363315159, 'reg_alpha': 0.00026568732327967654, 'reg_lambda': 7.205270404341964e-05, 'max_delta_step': 10}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  37%|███▋      | 74/200 [00:59<01:09,  1.80it/s]

[I 2025-11-10 17:20:44,353] Trial 76 pruned.
[I 2025-11-10 17:20:44,435] Trial 73 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1372118066648399, 'n_estimators': 343, 'subsample': 0.5237573674465803, 'colsample_bytree': 0.7113284950476505, 'min_child_weight': 5, 'gamma': 1.5112868909521562, 'reg_alpha': 0.3039050745274341, 'reg_lambda': 0.0016788281331638968, 'max_delta_step': 6}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  38%|███▊      | 77/200 [00:59<00:36,  3.41it/s]

[I 2025-11-10 17:20:44,543] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.01357080791017424, 'n_estimators': 342, 'subsample': 0.5215887302031051, 'colsample_bytree': 0.6828144450563028, 'min_child_weight': 5, 'gamma': 1.6103931095645205, 'reg_alpha': 0.03907621429192625, 'reg_lambda': 0.03033058997913396, 'max_delta_step': 6}. Best is trial 52 with value: 0.5564912280701754.
[I 2025-11-10 17:20:44,681] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.14357859869158157, 'n_estimators': 350, 'subsample': 0.527602957099196, 'colsample_bytree': 0.636781852383895, 'min_child_weight': 5, 'gamma': 1.6111895998168717, 'reg_alpha': 0.0348360434762759, 'reg_lambda': 3.7210836426257528, 'max_delta_step': 6}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  39%|███▉      | 78/200 [01:01<01:09,  1.76it/s]

[I 2025-11-10 17:20:46,028] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.013399862516025216, 'n_estimators': 290, 'subsample': 0.6816249806783943, 'colsample_bytree': 0.6851069973721478, 'min_child_weight': 6, 'gamma': 4.3306681061894805, 'reg_alpha': 1.1654604907878891e-07, 'reg_lambda': 1.067975982603952e-06, 'max_delta_step': 6}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  40%|███▉      | 79/200 [01:02<01:27,  1.39it/s]

[I 2025-11-10 17:20:47,153] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.014850990800191309, 'n_estimators': 416, 'subsample': 0.5800890871313964, 'colsample_bytree': 0.6853941727108919, 'min_child_weight': 7, 'gamma': 1.7025071839232, 'reg_alpha': 0.03885053475382949, 'reg_lambda': 0.041247787304409346, 'max_delta_step': 5}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  40%|████      | 80/200 [01:02<01:13,  1.64it/s]

[I 2025-11-10 17:20:47,484] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.06911577010390886, 'n_estimators': 564, 'subsample': 0.6778395945429716, 'colsample_bytree': 0.6335207268840108, 'min_child_weight': 6, 'gamma': 4.633578036585193, 'reg_alpha': 2.6798078442756554e-07, 'reg_lambda': 7.932425235414495e-06, 'max_delta_step': 5}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  40%|████      | 81/200 [01:03<01:08,  1.74it/s]

[I 2025-11-10 17:20:47,973] Trial 80 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.07007830061782232, 'n_estimators': 566, 'subsample': 0.6870781218497203, 'colsample_bytree': 0.5906006863163098, 'min_child_weight': 7, 'gamma': 3.6672759705048663, 'reg_alpha': 2.64169491458489, 'reg_lambda': 1.143026823242673e-06, 'max_delta_step': 5}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  41%|████      | 82/200 [01:03<01:09,  1.71it/s]

[I 2025-11-10 17:20:48,582] Trial 81 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.0693483379826054, 'n_estimators': 428, 'subsample': 0.5722497009947932, 'colsample_bytree': 0.575562169528981, 'min_child_weight': 7, 'gamma': 0.8869829682874394, 'reg_alpha': 0.002172957120117178, 'reg_lambda': 6.293167729542951e-06, 'max_delta_step': 4}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  42%|████▏     | 83/200 [01:04<01:08,  1.70it/s]

[I 2025-11-10 17:20:49,170] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.28271156451417234, 'n_estimators': 276, 'subsample': 0.5558029079485125, 'colsample_bytree': 0.9567728644867454, 'min_child_weight': 7, 'gamma': 2.401437748388437, 'reg_alpha': 0.0021024685935355477, 'reg_lambda': 0.0036766126393811605, 'max_delta_step': 4}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  42%|████▏     | 84/200 [01:05<01:09,  1.67it/s]

[I 2025-11-10 17:20:49,793] Trial 82 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2961138007482106, 'n_estimators': 487, 'subsample': 0.5711831715793562, 'colsample_bytree': 0.5909053283304039, 'min_child_weight': 6, 'gamma': 0.814164418242955, 'reg_alpha': 0.08386921590668868, 'reg_lambda': 5.84952282297643e-06, 'max_delta_step': 4}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  42%|████▎     | 85/200 [01:08<02:30,  1.31s/it]

[I 2025-11-10 17:20:52,803] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04577122641966277, 'n_estimators': 908, 'subsample': 0.5569557548446273, 'colsample_bytree': 0.9591148063811533, 'min_child_weight': 8, 'gamma': 2.407556795597911, 'reg_alpha': 0.0894404948263609, 'reg_lambda': 0.004379792912938871, 'max_delta_step': 8}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  43%|████▎     | 86/200 [01:08<02:03,  1.08s/it]

[I 2025-11-10 17:20:53,354] Trial 87 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10512243598778093, 'n_estimators': 699, 'subsample': 0.9374371112834402, 'colsample_bytree': 0.9386772438740708, 'min_child_weight': 10, 'gamma': 1.3605510531954668, 'reg_alpha': 4.434328787264378e-06, 'reg_lambda': 0.00025938556844253073, 'max_delta_step': 1}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  44%|████▎     | 87/200 [01:09<01:41,  1.11it/s]

[I 2025-11-10 17:20:53,819] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08882623884262658, 'n_estimators': 943, 'subsample': 0.9322789114205816, 'colsample_bytree': 0.9544283834599636, 'min_child_weight': 10, 'gamma': 1.177269959821773, 'reg_alpha': 4.738512609361813e-06, 'reg_lambda': 0.00029036780552181584, 'max_delta_step': 8}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  44%|████▍     | 88/200 [01:09<01:22,  1.35it/s]

[I 2025-11-10 17:20:54,187] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.10763842446425866, 'n_estimators': 908, 'subsample': 0.8536384446269931, 'colsample_bytree': 0.9246805489863393, 'min_child_weight': 8, 'gamma': 1.3465472426858454, 'reg_alpha': 0.06516435500578505, 'reg_lambda': 0.00011225031073870037, 'max_delta_step': 8}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  44%|████▍     | 89/200 [01:10<01:26,  1.28it/s]

[I 2025-11-10 17:20:55,059] Trial 91 pruned.
[I 2025-11-10 17:20:55,124] Trial 90 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.17646682625344476, 'n_estimators': 207, 'subsample': 0.8980150231255266, 'colsample_bytree': 0.719951852181242, 'min_child_weight': 8, 'gamma': 0.5796194657715341, 'reg_alpha': 0.004480591994780241, 'reg_lambda': 0.00012822494534408017, 'max_delta_step': 3}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  46%|████▌     | 91/200 [01:11<01:14,  1.45it/s]

[I 2025-11-10 17:20:56,217] Trial 92 pruned.

Best trial: 52. Best value: 0.556491:  46%|████▌     | 92/200 [01:11<01:06,  1.63it/s]

[I 2025-11-10 17:20:56,601] Trial 88 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.08998238856798418, 'n_estimators': 673, 'subsample': 0.9381594458787844, 'colsample_bytree': 0.9999018620423358, 'min_child_weight': 10, 'gamma': 1.3245774717601682, 'reg_alpha': 5.87455876916558e-06, 'reg_lambda': 0.00023343610738731386, 'max_delta_step': 1}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  46%|████▋     | 93/200 [01:12<00:57,  1.87it/s]

[I 2025-11-10 17:20:56,914] Trial 93 pruned.

Best trial: 52. Best value: 0.556491:  47%|████▋     | 94/200 [01:14<01:35,  1.11it/s]

[I 2025-11-10 17:20:58,792] Trial 89 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.09092562448270451, 'n_estimators': 896, 'subsample': 0.8259949115614771, 'colsample_bytree': 0.924540109884266, 'min_child_weight': 10, 'gamma': 0.25730359618248855, 'reg_alpha': 0.013695091075025619, 'reg_lambda': 0.000933328651594695, 'max_delta_step': 8}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  48%|████▊     | 95/200 [01:18<03:22,  1.93s/it]

[I 2025-11-10 17:21:03,385] Trial 97 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.06338360856755025, 'n_estimators': 835, 'subsample': 0.6231047829753169, 'colsample_bytree': 0.8828422784993921, 'min_child_weight': 6, 'gamma': 2.1318424983417015, 'reg_alpha': 3.1478712739532735e-08, 'reg_lambda': 2.0525842594426368e-07, 'max_delta_step': 4}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  48%|████▊     | 96/200 [01:18<02:32,  1.47s/it]

[I 2025-11-10 17:21:03,696] Trial 96 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.06220180878402501, 'n_estimators': 1239, 'subsample': 0.7807513715513368, 'colsample_bytree': 0.7740314053474588, 'min_child_weight': 6, 'gamma': 2.006669272527821, 'reg_alpha': 6.578749153456182e-08, 'reg_lambda': 1.8066495440089937e-05, 'max_delta_step': 4}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  48%|████▊     | 97/200 [01:19<01:53,  1.10s/it]

[I 2025-11-10 17:21:03,900] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.049465832444735285, 'n_estimators': 1235, 'subsample': 0.8209496129901186, 'colsample_bytree': 0.9914661298124755, 'min_child_weight': 6, 'gamma': 1.1316839990461376, 'reg_alpha': 2.51028748206084e-08, 'reg_lambda': 3.362479020316096e-06, 'max_delta_step': 4}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  49%|████▉     | 98/200 [01:20<01:46,  1.04s/it]

[I 2025-11-10 17:21:04,803] Trial 95 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.06319767189194574, 'n_estimators': 1497, 'subsample': 0.818097072955248, 'colsample_bytree': 0.7734115080802444, 'min_child_weight': 6, 'gamma': 0.24655865143016475, 'reg_alpha': 5.043509799809986e-05, 'reg_lambda': 1.8289033484927552e-05, 'max_delta_step': 4}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  50%|████▉     | 99/200 [01:20<01:24,  1.20it/s]

[I 2025-11-10 17:21:05,128] Trial 99 pruned.

Best trial: 52. Best value: 0.556491:  50%|█████     | 100/200 [01:21<01:33,  1.07it/s]

[I 2025-11-10 17:21:06,288] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.23865130511024718, 'n_estimators': 220, 'subsample': 0.8034161919668097, 'colsample_bytree': 0.6982268845159574, 'min_child_weight': 7, 'gamma': 1.514121699735883, 'reg_alpha': 0.46703211939729056, 'reg_lambda': 1.0367763316820646e-05, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  50%|█████     | 101/200 [01:23<01:51,  1.13s/it]

[I 2025-11-10 17:21:07,874] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07729460807261154, 'n_estimators': 305, 'subsample': 0.6524154934834439, 'colsample_bytree': 0.644378729352848, 'min_child_weight': 9, 'gamma': 1.949853513871403, 'reg_alpha': 3.782844046601818, 'reg_lambda': 0.00033558077642037014, 'max_delta_step': 10}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  51%|█████     | 102/200 [01:24<01:58,  1.21s/it]

[I 2025-11-10 17:21:09,292] Trial 98 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.06250031622539455, 'n_estimators': 1185, 'subsample': 0.7656938787859062, 'colsample_bytree': 0.7712758323729221, 'min_child_weight': 9, 'gamma': 1.4887846856628482, 'reg_alpha': 1.0521842014266205e-06, 'reg_lambda': 0.011564375618345005, 'max_delta_step': 5}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  52%|█████▏    | 103/200 [01:25<01:37,  1.00s/it]

[I 2025-11-10 17:21:09,799] Trial 100 finished with value: 0.4590155945419103 and parameters: {'max_depth': 8, 'learning_rate': 0.23029709837497683, 'n_estimators': 1156, 'subsample': 0.6488617676548651, 'colsample_bytree': 0.8580301264223393, 'min_child_weight': 4, 'gamma': 1.5279195668679002, 'reg_alpha': 1.0303018995965474e-08, 'reg_lambda': 9.023110237423897e-05, 'max_delta_step': 5}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  52%|█████▏    | 104/200 [01:25<01:34,  1.01it/s]

[I 2025-11-10 17:21:10,760] Trial 101 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.07838052337875577, 'n_estimators': 1158, 'subsample': 0.5118932508537637, 'colsample_bytree': 0.7902551435217552, 'min_child_weight': 9, 'gamma': 1.747461853361557, 'reg_alpha': 0.2032070867507991, 'reg_lambda': 0.00036664575896776924, 'max_delta_step': 5}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  52%|█████▎    | 105/200 [01:27<01:45,  1.11s/it]

[I 2025-11-10 17:21:12,148] Trial 104 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0763644402582459, 'n_estimators': 871, 'subsample': 0.6503173809092179, 'colsample_bytree': 0.7927242134939142, 'min_child_weight': 8, 'gamma': 2.294545433240285, 'reg_alpha': 3.6780405348301576e-07, 'reg_lambda': 2.8258431223520333, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  53%|█████▎    | 106/200 [01:28<01:52,  1.20s/it]

[I 2025-11-10 17:21:13,541] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07503019696682345, 'n_estimators': 856, 'subsample': 0.5891182833916211, 'colsample_bytree': 0.7936503687240765, 'min_child_weight': 8, 'gamma': 3.8799080558645573, 'reg_alpha': 2.86231326276779e-07, 'reg_lambda': 0.5832683573267295, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  54%|█████▎    | 107/200 [01:30<02:00,  1.30s/it]

[I 2025-11-10 17:21:15,073] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.07385914424393146, 'n_estimators': 1074, 'subsample': 0.9614876203711287, 'colsample_bytree': 0.7555127804327585, 'min_child_weight': 8, 'gamma': 3.4856092102840144, 'reg_alpha': 2.2434014517339998e-07, 'reg_lambda': 0.6208164225495434, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  54%|█████▍    | 108/200 [01:31<01:48,  1.18s/it]

[I 2025-11-10 17:21:15,988] Trial 107 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07275060944216907, 'n_estimators': 1070, 'subsample': 0.5910592158456354, 'colsample_bytree': 0.814735639735698, 'min_child_weight': 8, 'gamma': 3.7662141511996032, 'reg_alpha': 4.569711541231013e-07, 'reg_lambda': 2.691954404270045, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  55%|█████▍    | 109/200 [01:32<01:41,  1.12s/it]

[I 2025-11-10 17:21:16,965] Trial 110 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.12099302800568189, 'n_estimators': 290, 'subsample': 0.6266029568160546, 'colsample_bytree': 0.8090860592720874, 'min_child_weight': 7, 'gamma': 2.786964154836615, 'reg_alpha': 0.00021565789158655696, 'reg_lambda': 4.934954806637491, 'max_delta_step': 6}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  55%|█████▌    | 110/200 [01:32<01:26,  1.04it/s]

[I 2025-11-10 17:21:17,568] Trial 111 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.11994930299690348, 'n_estimators': 273, 'subsample': 0.619080465823727, 'colsample_bytree': 0.6202067188103579, 'min_child_weight': 7, 'gamma': 3.3117058994450446, 'reg_alpha': 1.2025779705496487, 'reg_lambda': 5.569669622254739, 'max_delta_step': 0}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  56%|█████▌    | 111/200 [01:32<01:04,  1.37it/s]

[I 2025-11-10 17:21:17,752] Trial 108 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.12159273090793088, 'n_estimators': 974, 'subsample': 0.6176372661926781, 'colsample_bytree': 0.7589209325380986, 'min_child_weight': 8, 'gamma': 2.704907650414149, 'reg_alpha': 0.9329911145354042, 'reg_lambda': 0.6788059757343188, 'max_delta_step': 0}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  56%|█████▌    | 112/200 [01:34<01:22,  1.06it/s]

[I 2025-11-10 17:21:19,178] Trial 109 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.2115261895999103, 'n_estimators': 1084, 'subsample': 0.6192966776461792, 'colsample_bytree': 0.8145513639900828, 'min_child_weight': 7, 'gamma': 2.179370025525974, 'reg_alpha': 0.8972112092521058, 'reg_lambda': 1.8153982212055262, 'max_delta_step': 0}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  56%|█████▋    | 113/200 [01:37<02:06,  1.45s/it]

[I 2025-11-10 17:21:21,833] Trial 112 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.08422323357093504, 'n_estimators': 963, 'subsample': 0.5325241102571828, 'colsample_bytree': 0.731886126886763, 'min_child_weight': 7, 'gamma': 3.281283037823509, 'reg_alpha': 1.0362623171995542, 'reg_lambda': 1.5376578118658928, 'max_delta_step': 0}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  57%|█████▋    | 114/200 [01:38<02:03,  1.44s/it]

[I 2025-11-10 17:21:23,229] Trial 116 pruned.

Best trial: 52. Best value: 0.556491:  57%|█████▊    | 115/200 [01:39<01:40,  1.18s/it]

[I 2025-11-10 17:21:23,799] Trial 113 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.052375245493099735, 'n_estimators': 1269, 'subsample': 0.537062844250814, 'colsample_bytree': 0.6750908027026351, 'min_child_weight': 5, 'gamma': 2.1995030957775583, 'reg_alpha': 0.0268801838711998, 'reg_lambda': 4.476320041061519e-06, 'max_delta_step': 6}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  58%|█████▊    | 116/200 [01:39<01:32,  1.10s/it]

[I 2025-11-10 17:21:24,733] Trial 114 finished with value: 0.4628167641325536 and parameters: {'max_depth': 3, 'learning_rate': 0.05195408657811238, 'n_estimators': 1276, 'subsample': 0.7327913691230514, 'colsample_bytree': 0.9846982104922617, 'min_child_weight': 4, 'gamma': 2.1414204273514055, 'reg_alpha': 3.1342184459313644, 'reg_lambda': 1.7126616375089673e-08, 'max_delta_step': 10}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  58%|█████▊    | 117/200 [01:42<01:56,  1.40s/it]

[I 2025-11-10 17:21:26,829] Trial 115 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.27668501555392544, 'n_estimators': 1445, 'subsample': 0.74484817539163, 'colsample_bytree': 0.911923786639732, 'min_child_weight': 5, 'gamma': 1.882864618084624, 'reg_alpha': 3.0849170299628965, 'reg_lambda': 8.642923800452053, 'max_delta_step': 3}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  59%|█████▉    | 118/200 [01:45<02:51,  2.09s/it]

[I 2025-11-10 17:21:30,500] Trial 117 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.020885483034042796, 'n_estimators': 1401, 'subsample': 0.5813592975619879, 'colsample_bytree': 0.9669126554468647, 'min_child_weight': 5, 'gamma': 2.961697800257205, 'reg_alpha': 0.02046916581514612, 'reg_lambda': 4.036132617303399e-06, 'max_delta_step': 6}. Best is trial 52 with value: 0.5564912280701754.
[I 2025-11-10 17:21:30,577] Trial 118 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2728350850549447, 'n_estimators': 1386, 'subsample': 0.7037860862935417, 'colsample_bytree': 0.7084523869655043, 'min_child_weight': 4, 'gamma': 1.3875911938670276, 'reg_alpha': 5.203382453975276, 'reg_lambda': 8.963160245115487, 'max_delta_step': 10}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  60%|██████    | 120/200 [01:46<01:51,  1.39s/it]

[I 2025-11-10 17:21:31,667] Trial 122 pruned.

Best trial: 52. Best value: 0.556491:  60%|██████    | 121/200 [01:47<01:32,  1.17s/it]

[I 2025-11-10 17:21:32,190] Trial 119 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04191417193886967, 'n_estimators': 1401, 'subsample': 0.7144008702755983, 'colsample_bytree': 0.9651990285542927, 'min_child_weight': 5, 'gamma': 1.2413322108039913, 'reg_alpha': 0.35983871439289844, 'reg_lambda': 5.147484255290686e-08, 'max_delta_step': 3}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  61%|██████    | 122/200 [01:48<01:37,  1.25s/it]

[I 2025-11-10 17:21:33,660] Trial 123 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.10048934257554608, 'n_estimators': 383, 'subsample': 0.6714029861983544, 'colsample_bytree': 0.7431663968367922, 'min_child_weight': 9, 'gamma': 1.2187695670814995, 'reg_alpha': 9.322750427681433, 'reg_lambda': 5.889566029140016e-05, 'max_delta_step': 2}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  62%|██████▏   | 123/200 [01:49<01:16,  1.01it/s]

[I 2025-11-10 17:21:33,943] Trial 120 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05891907171583891, 'n_estimators': 1384, 'subsample': 0.6727770571040349, 'colsample_bytree': 0.9679903393414129, 'min_child_weight': 4, 'gamma': 1.206358563388182, 'reg_alpha': 5.704484817167129, 'reg_lambda': 0.23326547085868615, 'max_delta_step': 6}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  62%|██████▏   | 124/200 [01:49<01:10,  1.08it/s]

[I 2025-11-10 17:21:34,714] Trial 121 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.0585479801448566, 'n_estimators': 781, 'subsample': 0.7047277452219413, 'colsample_bytree': 0.7481801062466858, 'min_child_weight': 4, 'gamma': 1.233557181230137, 'reg_alpha': 5.956413388591271, 'reg_lambda': 0.2308445459078392, 'max_delta_step': 9}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  62%|██████▎   | 125/200 [01:51<01:27,  1.17s/it]

[I 2025-11-10 17:21:36,486] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.16704397914335903, 'n_estimators': 804, 'subsample': 0.6077243700714832, 'colsample_bytree': 0.9942475358748157, 'min_child_weight': 9, 'gamma': 0.09054907395796258, 'reg_alpha': 1.491430661792732e-08, 'reg_lambda': 5.183409874900379e-05, 'max_delta_step': 1}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  63%|██████▎   | 126/200 [01:53<01:33,  1.26s/it]

[I 2025-11-10 17:21:37,970] Trial 126 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.21240121849825325, 'n_estimators': 796, 'subsample': 0.6949514153392641, 'colsample_bytree': 0.9319383091081554, 'min_child_weight': 7, 'gamma': 0.12645494480350708, 'reg_alpha': 4.518915115430098e-08, 'reg_lambda': 0.00018726112651995845, 'max_delta_step': 0}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  64%|██████▎   | 127/200 [01:53<01:09,  1.06it/s]

[I 2025-11-10 17:21:38,161] Trial 127 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.16121928218468293, 'n_estimators': 651, 'subsample': 0.6409656167295918, 'colsample_bytree': 0.9946637772213425, 'min_child_weight': 6, 'gamma': 0.040202633967099756, 'reg_alpha': 5.555361822865073e-08, 'reg_lambda': 0.00016085721658401421, 'max_delta_step': 2}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  64%|██████▍   | 128/200 [01:53<00:56,  1.28it/s]

[I 2025-11-10 17:21:38,543] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.24045065728883017, 'n_estimators': 835, 'subsample': 0.6066727096316064, 'colsample_bytree': 0.9987385560513837, 'min_child_weight': 7, 'gamma': 0.1373938525124717, 'reg_alpha': 1.6727357248983958e-08, 'reg_lambda': 0.00019129145982758417, 'max_delta_step': 0}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  64%|██████▍   | 129/200 [01:54<00:49,  1.44it/s]

[I 2025-11-10 17:21:39,038] Trial 130 pruned.

Best trial: 52. Best value: 0.556491:  65%|██████▌   | 130/200 [01:54<00:44,  1.57it/s]

[I 2025-11-10 17:21:39,522] Trial 129 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2564382617153457, 'n_estimators': 230, 'subsample': 0.7922550116234022, 'colsample_bytree': 0.6594656427595784, 'min_child_weight': 6, 'gamma': 0.2721296311590218, 'reg_alpha': 1.0751970476946638e-07, 'reg_lambda': 1.7468117694656114e-06, 'max_delta_step': 1}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  66%|██████▌   | 131/200 [01:55<00:49,  1.39it/s]

[I 2025-11-10 17:21:40,442] Trial 131 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.25044939793520005, 'n_estimators': 236, 'subsample': 0.6914819666972358, 'colsample_bytree': 0.7297940463358483, 'min_child_weight': 6, 'gamma': 0.2616034181913401, 'reg_alpha': 9.59506135769093e-08, 'reg_lambda': 6.970010587838651e-07, 'max_delta_step': 1}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  66%|██████▌   | 132/200 [01:55<00:38,  1.78it/s]

[I 2025-11-10 17:21:40,639] Trial 133 pruned.

Best trial: 52. Best value: 0.556491:  66%|██████▋   | 133/200 [01:57<00:51,  1.29it/s]

[I 2025-11-10 17:21:41,910] Trial 128 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.2503334936441554, 'n_estimators': 837, 'subsample': 0.6896677956766023, 'colsample_bytree': 0.9977977239177898, 'min_child_weight': 6, 'gamma': 0.37435927799980395, 'reg_alpha': 1.7499394836707094, 'reg_lambda': 0.00017230722435373737, 'max_delta_step': 1}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  67%|██████▋   | 134/200 [01:57<00:40,  1.63it/s]

[I 2025-11-10 17:21:42,140] Trial 135 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01150218378192908, 'n_estimators': 261, 'subsample': 0.5508135324502846, 'colsample_bytree': 0.6942204248395807, 'min_child_weight': 5, 'gamma': 1.7045043368945836, 'reg_alpha': 3.419750602522629e-08, 'reg_lambda': 0.0003744642599013885, 'max_delta_step': 10}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  68%|██████▊   | 135/200 [01:57<00:34,  1.91it/s]

[I 2025-11-10 17:21:42,458] Trial 134 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.29488084948894944, 'n_estimators': 318, 'subsample': 0.5530078931563925, 'colsample_bytree': 0.975193263121379, 'min_child_weight': 5, 'gamma': 2.0487798733354294, 'reg_alpha': 3.4130019680339806e-08, 'reg_lambda': 0.0023516481230046807, 'max_delta_step': 10}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  68%|██████▊   | 136/200 [01:58<00:43,  1.46it/s]

[I 2025-11-10 17:21:43,525] Trial 138 pruned.

Best trial: 52. Best value: 0.556491:  68%|██████▊   | 137/200 [01:59<00:37,  1.68it/s]

[I 2025-11-10 17:21:43,916] Trial 139 pruned.

Best trial: 52. Best value: 0.556491:  69%|██████▉   | 138/200 [01:59<00:30,  2.00it/s]

[I 2025-11-10 17:21:44,179] Trial 136 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2964765281138105, 'n_estimators': 265, 'subsample': 0.5564347098411697, 'colsample_bytree': 0.947689677432916, 'min_child_weight': 4, 'gamma': 4.5984700709303405, 'reg_alpha': 3.062100652219218e-08, 'reg_lambda': 0.0004244177679681931, 'max_delta_step': 10}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  70%|██████▉   | 139/200 [01:59<00:27,  2.22it/s]

[I 2025-11-10 17:21:44,525] Trial 132 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.25266141184709917, 'n_estimators': 930, 'subsample': 0.552673608314583, 'colsample_bytree': 0.8942569556531594, 'min_child_weight': 6, 'gamma': 0.4207069606136932, 'reg_alpha': 9.872653459645937e-08, 'reg_lambda': 1.6634075894182178e-06, 'max_delta_step': 8}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  70%|███████   | 140/200 [02:01<00:44,  1.34it/s]

[I 2025-11-10 17:21:45,969] Trial 140 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.19646242703000183, 'n_estimators': 361, 'subsample': 0.9829465555592292, 'colsample_bytree': 0.8669154092227651, 'min_child_weight': 8, 'gamma': 4.580201056827656, 'reg_alpha': 0.00507626698684763, 'reg_lambda': 0.0004995942348613917, 'max_delta_step': 8}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  70%|███████   | 141/200 [02:02<00:57,  1.02it/s]

[I 2025-11-10 17:21:47,470] Trial 137 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.2947680113893587, 'n_estimators': 884, 'subsample': 0.7228558289083776, 'colsample_bytree': 0.8922300556873491, 'min_child_weight': 5, 'gamma': 4.4430859703157495, 'reg_alpha': 1.2872540038184764e-08, 'reg_lambda': 0.000497720597002017, 'max_delta_step': 10}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  71%|███████   | 142/200 [02:03<00:52,  1.10it/s]

[I 2025-11-10 17:21:48,230] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.19540822272268765, 'n_estimators': 760, 'subsample': 0.7613578784777285, 'colsample_bytree': 0.535244640665702, 'min_child_weight': 8, 'gamma': 1.6084716577698874, 'reg_alpha': 0.00587770643977506, 'reg_lambda': 3.2623459359054046e-05, 'max_delta_step': 9}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  72%|███████▏  | 143/200 [02:04<00:53,  1.06it/s]

[I 2025-11-10 17:21:49,248] Trial 142 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.19830883283557674, 'n_estimators': 888, 'subsample': 0.7172248226810053, 'colsample_bytree': 0.7666068477273514, 'min_child_weight': 8, 'gamma': 0.17031250579835971, 'reg_alpha': 0.005113738326322625, 'reg_lambda': 1.4827987120238301e-05, 'max_delta_step': 5}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  72%|███████▏  | 144/200 [02:05<00:53,  1.05it/s]

[I 2025-11-10 17:21:50,233] Trial 144 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2687673271952611, 'n_estimators': 533, 'subsample': 0.7638062046640436, 'colsample_bytree': 0.8770868702937222, 'min_child_weight': 7, 'gamma': 2.469404622377088, 'reg_alpha': 2.1131882903332536e-08, 'reg_lambda': 1.4029970723533356e-05, 'max_delta_step': 0}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  72%|███████▎  | 145/200 [02:05<00:40,  1.37it/s]

[I 2025-11-10 17:21:50,432] Trial 143 finished with value: 0.5040350877192983 and parameters: {'max_depth': 10, 'learning_rate': 0.09406263619012974, 'n_estimators': 880, 'subsample': 0.8832842416247519, 'colsample_bytree': 0.7111278428915252, 'min_child_weight': 5, 'gamma': 4.141357957698949, 'reg_alpha': 1.0337464964988008e-08, 'reg_lambda': 0.050030535450541126, 'max_delta_step': 9}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  73%|███████▎  | 146/200 [02:06<00:44,  1.21it/s]

[I 2025-11-10 17:21:51,494] Trial 145 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.0858261951659835, 'n_estimators': 547, 'subsample': 0.9182534604346163, 'colsample_bytree': 0.7660895749643559, 'min_child_weight': 7, 'gamma': 0.005709670957981676, 'reg_alpha': 1.080773288721713e-08, 'reg_lambda': 2.4828011452766903e-08, 'max_delta_step': 0}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  74%|███████▎  | 147/200 [02:07<00:38,  1.39it/s]

[I 2025-11-10 17:21:51,968] Trial 146 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.27459988172627176, 'n_estimators': 450, 'subsample': 0.7752841743243395, 'colsample_bytree': 0.918342241266, 'min_child_weight': 7, 'gamma': 2.447914116672769, 'reg_alpha': 2.3157738796646118e-08, 'reg_lambda': 2.9765854105734828e-08, 'max_delta_step': 0}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  74%|███████▍  | 148/200 [02:08<00:39,  1.30it/s]

[I 2025-11-10 17:21:52,837] Trial 147 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.08452386493797996, 'n_estimators': 410, 'subsample': 0.9200028049046534, 'colsample_bytree': 0.915841686467469, 'min_child_weight': 7, 'gamma': 2.0320098429541695, 'reg_alpha': 1.117671788555215e-08, 'reg_lambda': 9.342938360570493e-06, 'max_delta_step': 0}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  74%|███████▍  | 149/200 [02:08<00:38,  1.32it/s]

[I 2025-11-10 17:21:53,576] Trial 150 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.0984504748641122, 'n_estimators': 282, 'subsample': 0.8834354317299734, 'colsample_bytree': 0.7100289187032305, 'min_child_weight': 5, 'gamma': 4.231361803204752, 'reg_alpha': 0.5437921402251682, 'reg_lambda': 0.0761779380300185, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  75%|███████▌  | 150/200 [02:09<00:30,  1.65it/s]

[I 2025-11-10 17:21:53,829] Trial 149 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.09271285369050755, 'n_estimators': 411, 'subsample': 0.8775114394335364, 'colsample_bytree': 0.7066723791572959, 'min_child_weight': 5, 'gamma': 4.328693287152771, 'reg_alpha': 0.06272646362492502, 'reg_lambda': 0.041380816099225434, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  76%|███████▌  | 151/200 [02:10<00:35,  1.38it/s]

[I 2025-11-10 17:21:54,816] Trial 151 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.09228020269005788, 'n_estimators': 295, 'subsample': 0.8880984152235142, 'colsample_bytree': 0.7069535319554503, 'min_child_weight': 5, 'gamma': 4.244030721097829, 'reg_alpha': 1.4252223423987985e-05, 'reg_lambda': 0.010599442863836846, 'max_delta_step': 9}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  76%|███████▌  | 152/200 [02:11<00:38,  1.25it/s]

[I 2025-11-10 17:21:55,809] Trial 148 finished with value: 0.451812865497076 and parameters: {'max_depth': 10, 'learning_rate': 0.08524199089763199, 'n_estimators': 999, 'subsample': 0.9156632522348764, 'colsample_bytree': 0.7054556011192622, 'min_child_weight': 5, 'gamma': 4.02089332924994, 'reg_alpha': 0.5603584895685053, 'reg_lambda': 8.335745156818928e-06, 'max_delta_step': 9}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  76%|███████▋  | 153/200 [02:11<00:29,  1.62it/s]

[I 2025-11-10 17:21:55,999] Trial 153 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.09454818656304795, 'n_estimators': 297, 'subsample': 0.8735828917497552, 'colsample_bytree': 0.7055014358650891, 'min_child_weight': 5, 'gamma': 4.102576516926672, 'reg_alpha': 0.5642499330306667, 'reg_lambda': 0.043189877958219616, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  77%|███████▋  | 154/200 [02:12<00:31,  1.46it/s]

[I 2025-11-10 17:21:56,836] Trial 154 finished with value: 0.5040350877192983 and parameters: {'max_depth': 10, 'learning_rate': 0.09741316249418161, 'n_estimators': 289, 'subsample': 0.8904710282382039, 'colsample_bytree': 0.7069154919722964, 'min_child_weight': 5, 'gamma': 4.2126324047429025, 'reg_alpha': 2.4226920868995266e-05, 'reg_lambda': 0.07223138744487953, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  78%|███████▊  | 155/200 [02:12<00:33,  1.34it/s]

[I 2025-11-10 17:21:57,730] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09588347582674597, 'n_estimators': 293, 'subsample': 0.8609170720815331, 'colsample_bytree': 0.7163900639249111, 'min_child_weight': 5, 'gamma': 4.1965987248906975, 'reg_alpha': 1.3155873379147834e-05, 'reg_lambda': 0.06803165676711194, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  78%|███████▊  | 156/200 [02:13<00:27,  1.60it/s]

[I 2025-11-10 17:21:58,078] Trial 156 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.09359384670091155, 'n_estimators': 294, 'subsample': 0.8855636088678054, 'colsample_bytree': 0.7147649899988392, 'min_child_weight': 5, 'gamma': 4.2399377488390595, 'reg_alpha': 1.3126826358751803e-05, 'reg_lambda': 0.06594429492996774, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  78%|███████▊  | 157/200 [02:14<00:28,  1.53it/s]

[I 2025-11-10 17:21:58,799] Trial 157 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.11095792377550512, 'n_estimators': 294, 'subsample': 0.8833476869174366, 'colsample_bytree': 0.7147496207757396, 'min_child_weight': 5, 'gamma': 4.170428209146998, 'reg_alpha': 1.6202229581952487e-06, 'reg_lambda': 0.055739682136728516, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  79%|███████▉  | 158/200 [02:14<00:23,  1.75it/s]

[I 2025-11-10 17:21:59,167] Trial 152 finished with value: 0.5040350877192983 and parameters: {'max_depth': 10, 'learning_rate': 0.09551581143343602, 'n_estimators': 1019, 'subsample': 0.887896378225849, 'colsample_bytree': 0.7075120807953149, 'min_child_weight': 5, 'gamma': 4.213871350894224, 'reg_alpha': 0.7091543153769714, 'reg_lambda': 0.09236411828381846, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  80%|███████▉  | 159/200 [02:14<00:22,  1.83it/s]

[I 2025-11-10 17:21:59,656] Trial 158 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.10907907017359574, 'n_estimators': 308, 'subsample': 0.8841597938067735, 'colsample_bytree': 0.6971333766165431, 'min_child_weight': 5, 'gamma': 4.124807978998876, 'reg_alpha': 2.6172824144920883e-06, 'reg_lambda': 0.01871176842856067, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  80%|████████  | 160/200 [02:15<00:18,  2.11it/s]

[I 2025-11-10 17:21:59,959] Trial 159 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.11131086428946566, 'n_estimators': 306, 'subsample': 0.8876252562482855, 'colsample_bytree': 0.6917067384394773, 'min_child_weight': 5, 'gamma': 4.283955130026155, 'reg_alpha': 2.855717726005161e-05, 'reg_lambda': 0.021130389789120137, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  80%|████████  | 161/200 [02:15<00:22,  1.77it/s]

[I 2025-11-10 17:22:00,738] Trial 160 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.10971129281218775, 'n_estimators': 311, 'subsample': 0.8862925813528453, 'colsample_bytree': 0.6905633786387612, 'min_child_weight': 5, 'gamma': 4.203613060925873, 'reg_alpha': 2.38247335959894e-06, 'reg_lambda': 0.060317150576377425, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  81%|████████  | 162/200 [02:16<00:19,  1.96it/s]

[I 2025-11-10 17:22:01,127] Trial 161 finished with value: 0.5040350877192983 and parameters: {'max_depth': 10, 'learning_rate': 0.10967688993676043, 'n_estimators': 311, 'subsample': 0.8936056142972378, 'colsample_bytree': 0.6924225820027701, 'min_child_weight': 5, 'gamma': 4.20347249674368, 'reg_alpha': 2.5092229495168643e-06, 'reg_lambda': 0.058854530760076545, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  82%|████████▏ | 163/200 [02:16<00:17,  2.16it/s]

[I 2025-11-10 17:22:01,476] Trial 162 finished with value: 0.5040350877192983 and parameters: {'max_depth': 10, 'learning_rate': 0.11107255164458214, 'n_estimators': 281, 'subsample': 0.8947552291528853, 'colsample_bytree': 0.6901762388347822, 'min_child_weight': 5, 'gamma': 4.1529894468459325, 'reg_alpha': 1.8372377362270885e-06, 'reg_lambda': 0.02002588839235149, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  82%|████████▏ | 164/200 [02:17<00:17,  2.02it/s]

[I 2025-11-10 17:22:02,044] Trial 163 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.10943108273548803, 'n_estimators': 309, 'subsample': 0.8881785105575762, 'colsample_bytree': 0.696395923723709, 'min_child_weight': 5, 'gamma': 4.156020261460279, 'reg_alpha': 2.470554123009393e-05, 'reg_lambda': 0.019435707036172596, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  82%|████████▎ | 165/200 [02:17<00:19,  1.81it/s]

[I 2025-11-10 17:22:02,725] Trial 164 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.11253481453169464, 'n_estimators': 281, 'subsample': 0.888074722126105, 'colsample_bytree': 0.6894247713173766, 'min_child_weight': 5, 'gamma': 4.168203458068355, 'reg_alpha': 1.425855182150823e-06, 'reg_lambda': 0.055474992654696076, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  83%|████████▎ | 166/200 [02:18<00:17,  1.90it/s]

[I 2025-11-10 17:22:03,188] Trial 165 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.11162028754543289, 'n_estimators': 312, 'subsample': 0.8816084202556775, 'colsample_bytree': 0.6912426145946524, 'min_child_weight': 5, 'gamma': 4.216773964201651, 'reg_alpha': 1.995742107223877e-06, 'reg_lambda': 0.06163466934007605, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  84%|████████▎ | 167/200 [02:18<00:15,  2.18it/s]

[I 2025-11-10 17:22:03,495] Trial 166 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.10008105432254384, 'n_estimators': 276, 'subsample': 0.8811387471164164, 'colsample_bytree': 0.7037061460106555, 'min_child_weight': 5, 'gamma': 4.348645720653192, 'reg_alpha': 1.2200399599807045e-06, 'reg_lambda': 0.021117047412736737, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  84%|████████▍ | 168/200 [02:19<00:13,  2.30it/s]

[I 2025-11-10 17:22:03,870] Trial 167 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.10322037570863814, 'n_estimators': 283, 'subsample': 0.8741366702596611, 'colsample_bytree': 0.712489979358679, 'min_child_weight': 5, 'gamma': 4.3206901745982185, 'reg_alpha': 9.898824397347123e-07, 'reg_lambda': 0.042832931783113974, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  84%|████████▍ | 169/200 [02:20<00:18,  1.71it/s]

[I 2025-11-10 17:22:04,815] Trial 169 finished with value: 0.4984795321637427 and parameters: {'max_depth': 10, 'learning_rate': 0.10008639377946908, 'n_estimators': 261, 'subsample': 0.8976593426321042, 'colsample_bytree': 0.7096303136218808, 'min_child_weight': 5, 'gamma': 4.042999445245015, 'reg_alpha': 6.884120731163207e-06, 'reg_lambda': 0.008034852056096302, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  85%|████████▌ | 170/200 [02:20<00:14,  2.14it/s]

[I 2025-11-10 17:22:05,007] Trial 168 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.10270764594761306, 'n_estimators': 361, 'subsample': 0.8775633169654204, 'colsample_bytree': 0.7115029867401941, 'min_child_weight': 5, 'gamma': 4.361769415466541, 'reg_alpha': 8.574021155032409e-06, 'reg_lambda': 0.00962814291313763, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  86%|████████▌ | 171/200 [02:21<00:16,  1.76it/s]

[I 2025-11-10 17:22:05,806] Trial 170 finished with value: 0.4962573099415204 and parameters: {'max_depth': 10, 'learning_rate': 0.1319330579623979, 'n_estimators': 361, 'subsample': 0.897829462638304, 'colsample_bytree': 0.7172535164075199, 'min_child_weight': 5, 'gamma': 4.063623592781158, 'reg_alpha': 6.288063304473561e-06, 'reg_lambda': 0.00896209251816753, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  86%|████████▌ | 172/200 [02:21<00:14,  1.87it/s]

[I 2025-11-10 17:22:06,263] Trial 171 finished with value: 0.4984795321637427 and parameters: {'max_depth': 10, 'learning_rate': 0.0932990016360716, 'n_estimators': 356, 'subsample': 0.8984763882715668, 'colsample_bytree': 0.6778299276962435, 'min_child_weight': 5, 'gamma': 4.040653614474472, 'reg_alpha': 9.161061420353921e-06, 'reg_lambda': 0.13535788803876017, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  86%|████████▋ | 173/200 [02:22<00:16,  1.61it/s]

[I 2025-11-10 17:22:07,073] Trial 172 finished with value: 0.4984795321637427 and parameters: {'max_depth': 10, 'learning_rate': 0.09201150701657664, 'n_estimators': 355, 'subsample': 0.8977531149757999, 'colsample_bytree': 0.7232915733689339, 'min_child_weight': 5, 'gamma': 3.913763778261269, 'reg_alpha': 8.239626104676324e-06, 'reg_lambda': 0.144896878422164, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  87%|████████▋ | 174/200 [02:22<00:14,  1.77it/s]

[I 2025-11-10 17:22:07,523] Trial 173 finished with value: 0.4984795321637427 and parameters: {'max_depth': 10, 'learning_rate': 0.09209963447382018, 'n_estimators': 338, 'subsample': 0.89986614400832, 'colsample_bytree': 0.7232362401865607, 'min_child_weight': 5, 'gamma': 3.9208416915282465, 'reg_alpha': 2.0878434292973704e-05, 'reg_lambda': 0.1191707567044348, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  88%|████████▊ | 175/200 [02:23<00:12,  1.94it/s]

[I 2025-11-10 17:22:07,931] Trial 174 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09322629837578751, 'n_estimators': 338, 'subsample': 0.8654912770899343, 'colsample_bytree': 0.6776693299517247, 'min_child_weight': 5, 'gamma': 3.885560506704574, 'reg_alpha': 6.681844596351344e-05, 'reg_lambda': 0.1378331920643953, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  88%|████████▊ | 176/200 [02:23<00:11,  2.08it/s]

[I 2025-11-10 17:22:08,325] Trial 175 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09306521054215151, 'n_estimators': 326, 'subsample': 0.8449366414607502, 'colsample_bytree': 0.7251349477957364, 'min_child_weight': 5, 'gamma': 3.890278346659409, 'reg_alpha': 4.107218915065051e-06, 'reg_lambda': 0.03196011705316247, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  88%|████████▊ | 177/200 [02:24<00:12,  1.83it/s]

[I 2025-11-10 17:22:09,020] Trial 176 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.11717768596426588, 'n_estimators': 323, 'subsample': 0.8649147325929097, 'colsample_bytree': 0.6706093070141389, 'min_child_weight': 5, 'gamma': 4.474775026914239, 'reg_alpha': 2.393722573409151e-06, 'reg_lambda': 0.028106640148377722, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  90%|████████▉ | 179/200 [02:25<00:09,  2.21it/s]

[I 2025-11-10 17:22:09,715] Trial 178 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.11915942754393191, 'n_estimators': 247, 'subsample': 0.8451866010427378, 'colsample_bytree': 0.6663725269900422, 'min_child_weight': 5, 'gamma': 4.494358270194214, 'reg_alpha': 3.2572839146198994e-06, 'reg_lambda': 0.03686576101497023, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.
[I 2025-11-10 17:22:09,842] Trial 177 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.116756752070824, 'n_estimators': 325, 'subsample': 0.8612144126851953, 'colsample_bytree': 0.6704370103650505, 'min_child_weight': 5, 'gamma': 4.456776140688958, 'reg_alpha': 2.666145665957098e-06, 'reg_lambda': 0.027178399881156723, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  90%|█████████ | 181/200 [02:26<00:08,  2.20it/s]

[I 2025-11-10 17:22:10,751] Trial 179 finished with value: 0.5040350877192983 and parameters: {'max_depth': 10, 'learning_rate': 0.1175987161202643, 'n_estimators': 392, 'subsample': 0.9105309432139311, 'colsample_bytree': 0.6658840928535146, 'min_child_weight': 5, 'gamma': 4.47203386951322, 'reg_alpha': 2.829784104890926e-06, 'reg_lambda': 0.016096192849085523, 'max_delta_step': 8}. Best is trial 52 with value: 0.5564912280701754.
[I 2025-11-10 17:22:10,896] Trial 180 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.14241750510551646, 'n_estimators': 246, 'subsample': 0.88535986373874, 'colsample_bytree': 0.7020842213939371, 'min_child_weight': 5, 'gamma': 4.297315790582014, 'reg_alpha': 3.1496349299520623e-06, 'reg_lambda': 0.01409402792775213, 'max_delta_step': 6}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  91%|█████████ | 182/200 [02:26<00:07,  2.39it/s]

[I 2025-11-10 17:22:11,221] Trial 183 pruned.

Best trial: 52. Best value: 0.556491:  92%|█████████▏| 183/200 [02:27<00:07,  2.13it/s]

[I 2025-11-10 17:22:11,822] Trial 182 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.10661538264604556, 'n_estimators': 290, 'subsample': 0.8844318292926302, 'colsample_bytree': 0.6993777742261671, 'min_child_weight': 5, 'gamma': 4.290421095354599, 'reg_alpha': 7.654597817979834e-07, 'reg_lambda': 0.08809391790261549, 'max_delta_step': 8}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  92%|█████████▏| 184/200 [02:27<00:07,  2.17it/s]

[I 2025-11-10 17:22:12,265] Trial 181 finished with value: 0.4962573099415204 and parameters: {'max_depth': 10, 'learning_rate': 0.10968518400763458, 'n_estimators': 394, 'subsample': 0.9106635432984606, 'colsample_bytree': 0.6999207674065498, 'min_child_weight': 5, 'gamma': 4.260626345735833, 'reg_alpha': 7.77397516067162e-07, 'reg_lambda': 0.016345860673924694, 'max_delta_step': 8}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  92%|█████████▎| 185/200 [02:28<00:07,  2.02it/s]

[I 2025-11-10 17:22:12,828] Trial 184 finished with value: 0.5007017543859649 and parameters: {'max_depth': 10, 'learning_rate': 0.10716220135341564, 'n_estimators': 297, 'subsample': 0.9071832240598587, 'colsample_bytree': 0.6868333361579112, 'min_child_weight': 5, 'gamma': 4.2358048923999085, 'reg_alpha': 0.30255574230864896, 'reg_lambda': 0.018509978224267185, 'max_delta_step': 8}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  93%|█████████▎| 186/200 [02:28<00:08,  1.74it/s]

[I 2025-11-10 17:22:13,598] Trial 185 finished with value: 0.5040350877192983 and parameters: {'max_depth': 10, 'learning_rate': 0.12823326301119528, 'n_estimators': 407, 'subsample': 0.9099791100171497, 'colsample_bytree': 0.6887783218639741, 'min_child_weight': 5, 'gamma': 4.229540595812023, 'reg_alpha': 1.2758857510454238e-05, 'reg_lambda': 0.07707165460419003, 'max_delta_step': 8}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  94%|█████████▎| 187/200 [02:29<00:07,  1.77it/s]

[I 2025-11-10 17:22:14,129] Trial 186 finished with value: 0.4962573099415204 and parameters: {'max_depth': 10, 'learning_rate': 0.12832957359010047, 'n_estimators': 397, 'subsample': 0.9107872467943561, 'colsample_bytree': 0.685838966446994, 'min_child_weight': 5, 'gamma': 4.128375737232664, 'reg_alpha': 1.7156532502820361e-06, 'reg_lambda': 0.07033779868750555, 'max_delta_step': 8}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  94%|█████████▍| 188/200 [02:29<00:06,  1.79it/s]

[I 2025-11-10 17:22:14,686] Trial 187 finished with value: 0.4955555555555556 and parameters: {'max_depth': 10, 'learning_rate': 0.1298112757182248, 'n_estimators': 405, 'subsample': 0.890826113803679, 'colsample_bytree': 0.6824210224452444, 'min_child_weight': 5, 'gamma': 4.762736590766268, 'reg_alpha': 1.3826637013644495e-05, 'reg_lambda': 0.07853390096144837, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  94%|█████████▍| 189/200 [02:30<00:06,  1.78it/s]

[I 2025-11-10 17:22:15,247] Trial 188 finished with value: 0.5040350877192983 and parameters: {'max_depth': 10, 'learning_rate': 0.12913867792025574, 'n_estimators': 392, 'subsample': 0.8911161707352278, 'colsample_bytree': 0.6847672931800306, 'min_child_weight': 5, 'gamma': 4.155549349498918, 'reg_alpha': 1.5697587451558373e-06, 'reg_lambda': 0.0815209039163826, 'max_delta_step': 6}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  95%|█████████▌| 190/200 [02:30<00:05,  1.97it/s]

[I 2025-11-10 17:22:15,624] Trial 191 pruned.

Best trial: 52. Best value: 0.556491:  96%|█████████▌| 191/200 [02:31<00:04,  1.98it/s]

[I 2025-11-10 17:22:16,131] Trial 192 pruned.

Best trial: 52. Best value: 0.556491:  96%|█████████▌| 192/200 [02:31<00:04,  1.97it/s]

[I 2025-11-10 17:22:16,648] Trial 189 finished with value: 0.48088693957115003 and parameters: {'max_depth': 10, 'learning_rate': 0.12788665605249566, 'n_estimators': 485, 'subsample': 0.9241528497704183, 'colsample_bytree': 0.6529312340862228, 'min_child_weight': 5, 'gamma': 4.128618783328768, 'reg_alpha': 1.552970940046254e-05, 'reg_lambda': 0.042797981988129105, 'max_delta_step': 6}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  96%|█████████▋| 193/200 [02:32<00:04,  1.69it/s]

[I 2025-11-10 17:22:17,434] Trial 190 finished with value: 0.4803313840155946 and parameters: {'max_depth': 10, 'learning_rate': 0.09784962926834147, 'n_estimators': 502, 'subsample': 0.9265150984924897, 'colsample_bytree': 0.7399705968761406, 'min_child_weight': 5, 'gamma': 4.685772654138408, 'reg_alpha': 1.3293825575545592e-05, 'reg_lambda': 0.0051306083741669, 'max_delta_step': 6}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  97%|█████████▋| 194/200 [02:33<00:03,  1.54it/s]

[I 2025-11-10 17:22:18,217] Trial 193 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.13733549535812772, 'n_estimators': 432, 'subsample': 0.8774732020345556, 'colsample_bytree': 0.7342124750308543, 'min_child_weight': 5, 'gamma': 3.797808368288303, 'reg_alpha': 1.757813997963358e-05, 'reg_lambda': 0.05444462745728034, 'max_delta_step': 6}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  98%|█████████▊| 195/200 [02:33<00:02,  1.67it/s]

[I 2025-11-10 17:22:18,688] Trial 194 finished with value: 0.5040350877192983 and parameters: {'max_depth': 10, 'learning_rate': 0.13767887089489098, 'n_estimators': 430, 'subsample': 0.8932265591594596, 'colsample_bytree': 0.7313182075607828, 'min_child_weight': 5, 'gamma': 4.388487051464763, 'reg_alpha': 2.4385825498585773e-05, 'reg_lambda': 0.0063339949157130235, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  98%|█████████▊| 197/200 [02:34<00:01,  2.35it/s]

[I 2025-11-10 17:22:19,069] Trial 196 finished with value: 0.5040350877192983 and parameters: {'max_depth': 10, 'learning_rate': 0.0858599914651007, 'n_estimators': 265, 'subsample': 0.8932334064595875, 'colsample_bytree': 0.7108494786006152, 'min_child_weight': 5, 'gamma': 4.535102782529041, 'reg_alpha': 2.733224155178008e-05, 'reg_lambda': 0.15809663027156576, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.
[I 2025-11-10 17:22:19,249] Trial 195 finished with value: 0.5040350877192983 and parameters: {'max_depth': 10, 'learning_rate': 0.12321653794196329, 'n_estimators': 418, 'subsample': 0.8930619499062779, 'colsample_bytree': 0.7376784338767047, 'min_child_weight': 5, 'gamma': 4.391735697186725, 'reg_alpha': 3.768724918755353e-05, 'reg_lambda': 0.15602986369394176, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491:  99%|█████████▉| 198/200 [02:35<00:01,  1.42it/s]

[I 2025-11-10 17:22:20,602] Trial 197 finished with value: 0.5029239766081871 and parameters: {'max_depth': 10, 'learning_rate': 0.1504479158128293, 'n_estimators': 447, 'subsample': 0.8949748235076259, 'colsample_bytree': 0.7115133174922984, 'min_child_weight': 5, 'gamma': 4.376332234272339, 'reg_alpha': 2.3979654544535992e-05, 'reg_lambda': 0.09882650387616283, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

Best trial: 52. Best value: 0.556491: 100%|██████████| 200/200 [02:36<00:00,  1.28it/s]

[I 2025-11-10 17:22:21,044] Trial 199 finished with value: 0.5040350877192983 and parameters: {'max_depth': 10, 'learning_rate': 0.08143824611113339, 'n_estimators': 431, 'subsample': 0.9037169153606024, 'colsample_bytree': 0.7143144019472268, 'min_child_weight': 5, 'gamma': 4.561832626451323, 'reg_alpha': 3.318298875470268e-05, 'reg_lambda': 0.1829163681566484, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.
[I 2025-11-10 17:22:21,061] Trial 198 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.08951115688379936, 'n_estimators': 436, 'subsample': 0.8527773587467468, 'colsample_bytree': 0.713832951299312, 'min_child_weight': 5, 'gamma': 4.52871794003799, 'reg_alpha': 0.44292952075999614, 'reg_lambda': 0.15915885569716087, 'max_delta_step': 7}. Best is trial 52 with value: 0.5564912280701754.

[I 2025-11-10 17:22:21,954] A new study created in memory with name: 3_1_roc_auc
Best trial: 3. Best value: 0.5:   0%|          | 1/200 [00:02<08:00,  2.42s/it]

[I 2025-11-10 17:22:24,364] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.03650645349212289, 'n_estimators': 375, 'subsample': 0.7885444281981425, 'colsample_bytree': 0.8747509361695738, 'min_child_weight': 9, 'gamma': 2.0814484971713805, 'reg_alpha': 1.2544715821065882, 'reg_lambda': 0.004888117870890536, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   1%|          | 2/200 [00:03<04:43,  1.43s/it]

[I 2025-11-10 17:22:25,108] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.294690309040005, 'n_estimators': 564, 'subsample': 0.5220568787351507, 'colsample_bytree': 0.7829926984894116, 'min_child_weight': 9, 'gamma': 0.23689448559276294, 'reg_alpha': 5.088616223923688e-05, 'reg_lambda': 0.3201492618696152, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   2%|▏         | 3/200 [00:06<07:03,  2.15s/it]

[I 2025-11-10 17:22:28,116] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.20594376145627902, 'n_estimators': 731, 'subsample': 0.8430383669629573, 'colsample_bytree': 0.9116689768811995, 'min_child_weight': 7, 'gamma': 3.956279850433033, 'reg_alpha': 7.469605763015612e-07, 'reg_lambda': 4.92312575453127e-05, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   2%|▎         | 5/200 [00:06<03:10,  1.02it/s]

[I 2025-11-10 17:22:28,491] Trial 0 finished with value: 0.4750292397660819 and parameters: {'max_depth': 7, 'learning_rate': 0.16741473737501117, 'n_estimators': 1387, 'subsample': 0.8704822769115368, 'colsample_bytree': 0.5559762727018518, 'min_child_weight': 5, 'gamma': 0.39799106321428745, 'reg_alpha': 0.16721763248845456, 'reg_lambda': 0.004373158592774474, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:22:28,625] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.044216133566204456, 'n_estimators': 1450, 'subsample': 0.6384138704272864, 'colsample_bytree': 0.6024987170450253, 'min_child_weight': 8, 'gamma': 2.383462283650039, 'reg_alpha': 7.58261034295122e-05, 'reg_lambda': 1.0217161452578645e-08, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   3%|▎         | 6/200 [00:08<03:52,  1.20s/it]

[I 2025-11-10 17:22:30,264] Trial 5 finished with value: 0.4828460038986354 and parameters: {'max_depth': 9, 'learning_rate': 0.018656264017665715, 'n_estimators': 731, 'subsample': 0.896142383874516, 'colsample_bytree': 0.5522140701896683, 'min_child_weight': 3, 'gamma': 1.352241380175816, 'reg_alpha': 0.10918424521896618, 'reg_lambda': 0.0006161123196892693, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   4%|▎         | 7/200 [00:08<02:55,  1.10it/s]

[I 2025-11-10 17:22:30,580] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.054964815329825244, 'n_estimators': 370, 'subsample': 0.5200809207884655, 'colsample_bytree': 0.7294818646823998, 'min_child_weight': 6, 'gamma': 3.0620163121772355, 'reg_alpha': 2.4539113482325026e-07, 'reg_lambda': 0.008908491520575162, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   4%|▍         | 9/200 [00:12<04:03,  1.27s/it]

[I 2025-11-10 17:22:34,217] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.10981670447796074, 'n_estimators': 1184, 'subsample': 0.5720386789388403, 'colsample_bytree': 0.534508003443054, 'min_child_weight': 4, 'gamma': 2.783162675102315, 'reg_alpha': 3.57349700392655, 'reg_lambda': 8.499390638276342e-08, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:22:34,382] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.01680733204704047, 'n_estimators': 668, 'subsample': 0.7068521277401063, 'colsample_bytree': 0.6369406729102802, 'min_child_weight': 7, 'gamma': 1.7076668230324925, 'reg_alpha': 0.0005047523381333264, 'reg_lambda': 8.77458483875157, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   5%|▌         | 10/200 [00:12<03:06,  1.02it/s]

[I 2025-11-10 17:22:34,715] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.018574920454732056, 'n_estimators': 1306, 'subsample': 0.9405744294212816, 'colsample_bytree': 0.8431387032152002, 'min_child_weight': 8, 'gamma': 0.6741588801980397, 'reg_alpha': 2.381681351287245, 'reg_lambda': 0.06728396664904653, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   6%|▌         | 11/200 [00:13<03:04,  1.02it/s]

[I 2025-11-10 17:22:35,667] Trial 12 pruned.

Best trial: 3. Best value: 0.5:   6%|▌         | 12/200 [00:14<02:29,  1.26it/s]

[I 2025-11-10 17:22:36,057] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.013907567467820391, 'n_estimators': 337, 'subsample': 0.6943951162572151, 'colsample_bytree': 0.9010474310882877, 'min_child_weight': 5, 'gamma': 4.430380949249698, 'reg_alpha': 0.08813768748268451, 'reg_lambda': 0.0007966029367276532, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   6%|▋         | 13/200 [00:14<01:59,  1.56it/s]

[I 2025-11-10 17:22:36,335] Trial 13 pruned.

Best trial: 3. Best value: 0.5:   7%|▋         | 14/200 [00:15<02:06,  1.47it/s]

[I 2025-11-10 17:22:37,115] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.06730169214825385, 'n_estimators': 1296, 'subsample': 0.5556085349308488, 'colsample_bytree': 0.6761684032062889, 'min_child_weight': 7, 'gamma': 0.49195398162382387, 'reg_alpha': 0.17501887062713553, 'reg_lambda': 0.003264775859561912, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   8%|▊         | 15/200 [00:18<04:33,  1.48s/it]

[I 2025-11-10 17:22:40,432] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.07973542311742898, 'n_estimators': 988, 'subsample': 0.6242411311505572, 'colsample_bytree': 0.7357485258416923, 'min_child_weight': 10, 'gamma': 4.999053551424913, 'reg_alpha': 0.0003217880650955469, 'reg_lambda': 1.128712652330998e-08, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   8%|▊         | 16/200 [00:19<03:55,  1.28s/it]

[I 2025-11-10 17:22:41,264] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.28725089932002357, 'n_estimators': 971, 'subsample': 0.6059600096365451, 'colsample_bytree': 0.9971837261731081, 'min_child_weight': 10, 'gamma': 1.0339767548152201, 'reg_alpha': 1.0415201191879205e-05, 'reg_lambda': 3.0312496113473546e-06, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   8%|▊         | 17/200 [00:20<03:26,  1.13s/it]

[I 2025-11-10 17:22:42,040] Trial 17 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.10626394785635909, 'n_estimators': 936, 'subsample': 0.6304006628824019, 'colsample_bytree': 0.9909090264180069, 'min_child_weight': 10, 'gamma': 1.1465586459528683, 'reg_alpha': 8.660821792943815e-06, 'reg_lambda': 2.373966290839535e-06, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   9%|▉         | 18/200 [00:21<03:31,  1.16s/it]

[I 2025-11-10 17:22:43,270] Trial 18 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.27330679982124995, 'n_estimators': 542, 'subsample': 0.6157708868435806, 'colsample_bytree': 0.8204627690938955, 'min_child_weight': 10, 'gamma': 1.1518660352814023, 'reg_alpha': 9.750171349135542e-06, 'reg_lambda': 5.59106823157422e-06, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  10%|▉         | 19/200 [00:21<02:43,  1.11it/s]

[I 2025-11-10 17:22:43,580] Trial 15 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.07981553980341284, 'n_estimators': 1500, 'subsample': 0.5882802012018997, 'colsample_bytree': 0.7618389647455643, 'min_child_weight': 10, 'gamma': 1.013527443403395, 'reg_alpha': 0.0002668001117839531, 'reg_lambda': 1.220134279655189e-08, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  10%|█         | 20/200 [00:23<03:16,  1.09s/it]

[I 2025-11-10 17:22:45,109] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.035647308383642586, 'n_estimators': 607, 'subsample': 0.5233177132939897, 'colsample_bytree': 0.794900226983747, 'min_child_weight': 9, 'gamma': 2.32458786722742, 'reg_alpha': 1.0990956915025683e-08, 'reg_lambda': 2.192255941561497, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  10%|█         | 21/200 [00:23<02:44,  1.09it/s]

[I 2025-11-10 17:22:45,627] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03935766302000579, 'n_estimators': 539, 'subsample': 0.5180646206655993, 'colsample_bytree': 0.8103479118149082, 'min_child_weight': 8, 'gamma': 2.3406338031101415, 'reg_alpha': 1.9985852340533718e-08, 'reg_lambda': 1.4123355484646578, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  11%|█         | 22/200 [00:25<03:05,  1.04s/it]

[I 2025-11-10 17:22:46,967] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.02625845847539824, 'n_estimators': 232, 'subsample': 0.7854903047023152, 'colsample_bytree': 0.872394392384521, 'min_child_weight': 8, 'gamma': 1.8935967467173924, 'reg_alpha': 0.003871906360880443, 'reg_lambda': 0.14590680434382697, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  12%|█▏        | 23/200 [00:25<02:26,  1.21it/s]

[I 2025-11-10 17:22:47,291] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03501215331941262, 'n_estimators': 528, 'subsample': 0.5014476119296608, 'colsample_bytree': 0.6200408364474034, 'min_child_weight': 8, 'gamma': 2.3665018164123315, 'reg_alpha': 1.971201069037561e-08, 'reg_lambda': 0.9277942869968538, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  12%|█▏        | 24/200 [00:26<02:26,  1.20it/s]

[I 2025-11-10 17:22:48,121] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02624939753445407, 'n_estimators': 501, 'subsample': 0.6755268734860072, 'colsample_bytree': 0.6151835984488546, 'min_child_weight': 8, 'gamma': 0.12948614611891962, 'reg_alpha': 0.007200822587963858, 'reg_lambda': 0.26326947397101663, 'max_delta_step': 0}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  12%|█▎        | 25/200 [00:27<02:39,  1.10it/s]

[I 2025-11-10 17:22:49,230] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.04408968793645669, 'n_estimators': 395, 'subsample': 0.808253641871928, 'colsample_bytree': 0.5931629301267279, 'min_child_weight': 9, 'gamma': 3.548990116978582, 'reg_alpha': 0.003992024778622101, 'reg_lambda': 0.12911722068839881, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  13%|█▎        | 26/200 [00:27<02:15,  1.28it/s]

[I 2025-11-10 17:22:49,705] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.010960320740850673, 'n_estimators': 400, 'subsample': 0.8143868086773121, 'colsample_bytree': 0.9368299914858527, 'min_child_weight': 9, 'gamma': 3.6179089668026405, 'reg_alpha': 0.009508096577002243, 'reg_lambda': 0.06420335185391428, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  14%|█▎        | 27/200 [00:28<01:55,  1.49it/s]

[I 2025-11-10 17:22:50,113] Trial 27 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.01034305277407692, 'n_estimators': 371, 'subsample': 0.9891521594086946, 'colsample_bytree': 0.9318510397542354, 'min_child_weight': 9, 'gamma': 3.6134442280560934, 'reg_alpha': 0.004172761171517582, 'reg_lambda': 5.3441630839381464e-05, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  14%|█▍        | 28/200 [00:29<02:29,  1.15it/s]

[I 2025-11-10 17:22:51,444] Trial 29 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.12828858686606956, 'n_estimators': 276, 'subsample': 0.9964922761827341, 'colsample_bytree': 0.6917856465116122, 'min_child_weight': 6, 'gamma': 1.819145197562813, 'reg_alpha': 7.616820696126933e-07, 'reg_lambda': 6.94484339691785e-05, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  14%|█▍        | 29/200 [00:30<02:22,  1.20it/s]

[I 2025-11-10 17:22:52,190] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03885754496105839, 'n_estimators': 1481, 'subsample': 0.5149866463632014, 'colsample_bytree': 0.7900686464384636, 'min_child_weight': 8, 'gamma': 2.1666530855757338, 'reg_alpha': 1.931726357535858e-08, 'reg_lambda': 2.145931706910299, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  15%|█▌        | 30/200 [00:32<03:21,  1.19s/it]

[I 2025-11-10 17:22:54,205] Trial 28 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.15143604447543513, 'n_estimators': 837, 'subsample': 0.998094770830119, 'colsample_bytree': 0.9355260232028492, 'min_child_weight': 9, 'gamma': 1.745222483150062, 'reg_alpha': 1.1012327997371186e-06, 'reg_lambda': 9.149024219786905e-05, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  16%|█▌        | 31/200 [00:32<02:35,  1.09it/s]

[I 2025-11-10 17:22:54,502] Trial 30 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.13052191939798632, 'n_estimators': 836, 'subsample': 0.7268722990812705, 'colsample_bytree': 0.7020383604687792, 'min_child_weight': 6, 'gamma': 1.8573075394962604, 'reg_alpha': 5.52586573728322e-05, 'reg_lambda': 0.02890934286263844, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  16%|█▌        | 32/200 [00:33<02:59,  1.07s/it]

[I 2025-11-10 17:22:55,906] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.046607432141958186, 'n_estimators': 841, 'subsample': 0.7392060851632268, 'colsample_bytree': 0.7732461658316023, 'min_child_weight': 9, 'gamma': 2.684141482149833, 'reg_alpha': 6.095770366697365e-05, 'reg_lambda': 0.02557981529699891, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  16%|█▋        | 33/200 [00:35<03:02,  1.10s/it]

[I 2025-11-10 17:22:57,074] Trial 32 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.16937876190410034, 'n_estimators': 886, 'subsample': 0.7494596855132478, 'colsample_bytree': 0.846462172443324, 'min_child_weight': 7, 'gamma': 2.6651095648019814, 'reg_alpha': 5.661739084926431e-05, 'reg_lambda': 0.012800987954589334, 'max_delta_step': 1}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  17%|█▋        | 34/200 [00:36<03:06,  1.12s/it]

[I 2025-11-10 17:22:58,264] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.21497197418389463, 'n_estimators': 750, 'subsample': 0.8579853641573344, 'colsample_bytree': 0.8634433136289362, 'min_child_weight': 7, 'gamma': 4.043021444373439, 'reg_alpha': 1.716371902620862e-06, 'reg_lambda': 1.8088889674881635e-07, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  18%|█▊        | 35/200 [00:37<03:15,  1.18s/it]

[I 2025-11-10 17:22:59,583] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.19849078621801725, 'n_estimators': 713, 'subsample': 0.8859750852022952, 'colsample_bytree': 0.8799778881030075, 'min_child_weight': 7, 'gamma': 4.182630931057585, 'reg_alpha': 1.9989863796630457e-07, 'reg_lambda': 4.170333381074379e-07, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  18%|█▊        | 36/200 [00:37<02:28,  1.10it/s]

[I 2025-11-10 17:22:59,840] Trial 33 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.025106220111133826, 'n_estimators': 1100, 'subsample': 0.7335635087113785, 'colsample_bytree': 0.7096122056043529, 'min_child_weight': 7, 'gamma': 2.7719269872485093, 'reg_alpha': 6.626765882471852e-05, 'reg_lambda': 0.01524580537571437, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  18%|█▊        | 37/200 [00:39<02:43,  1.00s/it]

[I 2025-11-10 17:23:01,066] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.19680734851287152, 'n_estimators': 749, 'subsample': 0.8598582833377627, 'colsample_bytree': 0.877206325326573, 'min_child_weight': 7, 'gamma': 3.9449572523527885, 'reg_alpha': 1.182379411739664e-06, 'reg_lambda': 3.123280580811296e-07, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  20%|█▉        | 39/200 [00:40<02:02,  1.31it/s]

[I 2025-11-10 17:23:02,180] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.23361625778682596, 'n_estimators': 448, 'subsample': 0.8421638930749697, 'colsample_bytree': 0.5123443257630638, 'min_child_weight': 6, 'gamma': 3.0310846231604236, 'reg_alpha': 0.5624356978829427, 'reg_lambda': 0.0009136060457988781, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:23:02,314] Trial 37 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2252290300144215, 'n_estimators': 647, 'subsample': 0.8416383956134234, 'colsample_bytree': 0.8945089702144893, 'min_child_weight': 7, 'gamma': 0.0815910821699575, 'reg_alpha': 1.1105188261626564e-07, 'reg_lambda': 5.352545210517335e-07, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  20%|██        | 40/200 [00:40<01:43,  1.54it/s]

[I 2025-11-10 17:23:02,693] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.24130697244952543, 'n_estimators': 446, 'subsample': 0.8504537145418077, 'colsample_bytree': 0.9102832767650872, 'min_child_weight': 6, 'gamma': 0.007622703360690597, 'reg_alpha': 8.224603979938983, 'reg_lambda': 0.0008659480868641285, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  20%|██        | 41/200 [00:41<01:29,  1.77it/s]

[I 2025-11-10 17:23:03,064] Trial 41 pruned.
[I 2025-11-10 17:23:03,090] Trial 42 pruned.

Best trial: 3. Best value: 0.5:  22%|██▏       | 43/200 [00:41<01:12,  2.15it/s]

[I 2025-11-10 17:23:03,765] Trial 40 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.29676564297717195, 'n_estimators': 440, 'subsample': 0.9143748645234528, 'colsample_bytree': 0.5753684622987891, 'min_child_weight': 6, 'gamma': 3.1816712398796554, 'reg_alpha': 0.0010086597832614365, 'reg_lambda': 0.000531087083388662, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  22%|██▏       | 44/200 [00:44<02:21,  1.10it/s]

[I 2025-11-10 17:23:06,007] Trial 43 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.021877276070956117, 'n_estimators': 609, 'subsample': 0.5569232820467744, 'colsample_bytree': 0.579714852926252, 'min_child_weight': 5, 'gamma': 0.7363900104988235, 'reg_alpha': 0.0010377562031532999, 'reg_lambda': 0.00022621879695996664, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  23%|██▎       | 46/200 [00:48<03:13,  1.26s/it]

[I 2025-11-10 17:23:09,850] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.017498882963239898, 'n_estimators': 1353, 'subsample': 0.9379960050372542, 'colsample_bytree': 0.8262597401173734, 'min_child_weight': 8, 'gamma': 1.4241666375711244, 'reg_alpha': 1.3437730328242345, 'reg_lambda': 0.0002694304935965434, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:23:09,989] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.014158048300530055, 'n_estimators': 1387, 'subsample': 0.9427417896904919, 'colsample_bytree': 0.8278282939665093, 'min_child_weight': 8, 'gamma': 0.5331508590425375, 'reg_alpha': 0.9028375308980147, 'reg_lambda': 0.0028616716228091255, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  24%|██▎       | 47/200 [00:48<02:43,  1.07s/it]

[I 2025-11-10 17:23:10,579] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.019305244657489114, 'n_estimators': 1322, 'subsample': 0.5543822097219464, 'colsample_bytree': 0.8347168271859817, 'min_child_weight': 8, 'gamma': 1.5553057953800917, 'reg_alpha': 1.0529893856155346, 'reg_lambda': 0.00456585735870681, 'max_delta_step': 1}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  24%|██▍       | 48/200 [00:49<02:30,  1.01it/s]

[I 2025-11-10 17:23:11,363] Trial 49 pruned.

Best trial: 3. Best value: 0.5:  25%|██▌       | 50/200 [00:50<01:51,  1.35it/s]

[I 2025-11-10 17:23:12,379] Trial 50 pruned.
[I 2025-11-10 17:23:12,509] Trial 47 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.01669949371155065, 'n_estimators': 1365, 'subsample': 0.774184618932261, 'colsample_bytree': 0.8339614965499813, 'min_child_weight': 8, 'gamma': 1.462917068572282, 'reg_alpha': 0.2870636374289188, 'reg_lambda': 0.0040675126347421665, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  26%|██▌       | 51/200 [00:51<01:52,  1.33it/s]

[I 2025-11-10 17:23:13,283] Trial 51 pruned.

Best trial: 3. Best value: 0.5:  26%|██▌       | 52/200 [00:54<03:26,  1.39s/it]

[I 2025-11-10 17:23:16,184] Trial 48 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.054834968102674145, 'n_estimators': 1257, 'subsample': 0.6504695963175083, 'colsample_bytree': 0.8315271006819303, 'min_child_weight': 8, 'gamma': 0.38034521450826486, 'reg_alpha': 0.04651811451042522, 'reg_lambda': 0.002847493906429031, 'max_delta_step': 1}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  26%|██▋       | 53/200 [00:56<03:42,  1.51s/it]

[I 2025-11-10 17:23:17,987] Trial 52 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03083589005911615, 'n_estimators': 1124, 'subsample': 0.7766414847373151, 'colsample_bytree': 0.7988391641178442, 'min_child_weight': 10, 'gamma': 2.111824230455551, 'reg_alpha': 0.35563288547489946, 'reg_lambda': 8.653382826899422, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  27%|██▋       | 54/200 [00:57<03:53,  1.60s/it]

[I 2025-11-10 17:23:19,787] Trial 53 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04990592938610051, 'n_estimators': 1432, 'subsample': 0.7055563882000072, 'colsample_bytree': 0.7982531126643465, 'min_child_weight': 10, 'gamma': 0.3149842533075651, 'reg_alpha': 4.192571588692393e-06, 'reg_lambda': 8.664353209001051, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  28%|██▊       | 55/200 [00:58<02:58,  1.23s/it]

[I 2025-11-10 17:23:20,167] Trial 56 pruned.

Best trial: 3. Best value: 0.5:  28%|██▊       | 56/200 [00:58<02:18,  1.04it/s]

[I 2025-11-10 17:23:20,500] Trial 54 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.030879830239326465, 'n_estimators': 1466, 'subsample': 0.5815852857159259, 'colsample_bytree': 0.6503670532366106, 'min_child_weight': 10, 'gamma': 2.033905981826993, 'reg_alpha': 3.1153959703227243, 'reg_lambda': 3.648356358514847e-08, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  28%|██▊       | 57/200 [00:59<02:34,  1.08s/it]

[I 2025-11-10 17:23:21,856] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07152836415669514, 'n_estimators': 320, 'subsample': 0.5964269311797459, 'colsample_bytree': 0.6455097309497827, 'min_child_weight': 9, 'gamma': 3.3325336017709657, 'reg_alpha': 1.3685923415505165e-07, 'reg_lambda': 3.09685151108585e-08, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  29%|██▉       | 58/200 [01:00<02:02,  1.16it/s]

[I 2025-11-10 17:23:22,203] Trial 58 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03153632169648763, 'n_estimators': 318, 'subsample': 0.5296557706664786, 'colsample_bytree': 0.8614575427110108, 'min_child_weight': 9, 'gamma': 3.3681973566951777, 'reg_alpha': 2.0194575674459232e-07, 'reg_lambda': 0.0921925065957843, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  30%|██▉       | 59/200 [01:00<01:35,  1.48it/s]

[I 2025-11-10 17:23:22,433] Trial 59 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.012270683220504638, 'n_estimators': 339, 'subsample': 0.5482136763225831, 'colsample_bytree': 0.722411336806929, 'min_child_weight': 9, 'gamma': 2.5252094655140866, 'reg_alpha': 0.0001784002483999317, 'reg_lambda': 0.0596357509228608, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  30%|███       | 60/200 [01:00<01:16,  1.84it/s]

[I 2025-11-10 17:23:22,666] Trial 61 pruned.

Best trial: 3. Best value: 0.5:  30%|███       | 61/200 [01:01<01:04,  2.15it/s]

[I 2025-11-10 17:23:22,957] Trial 62 pruned.

Best trial: 3. Best value: 0.5:  31%|███       | 62/200 [01:01<01:14,  1.86it/s]

[I 2025-11-10 17:23:23,666] Trial 55 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02919130203260934, 'n_estimators': 1450, 'subsample': 0.584582701514601, 'colsample_bytree': 0.7265402028659993, 'min_child_weight': 10, 'gamma': 2.9827656262231534, 'reg_alpha': 8.655868895165084e-08, 'reg_lambda': 8.221472743555786, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  32%|███▏      | 63/200 [01:02<01:06,  2.07it/s]

[I 2025-11-10 17:23:24,021] Trial 60 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.012442423764966775, 'n_estimators': 284, 'subsample': 0.544712213420093, 'colsample_bytree': 0.7231269216382982, 'min_child_weight': 9, 'gamma': 2.520187091089066, 'reg_alpha': 0.0001770287597495735, 'reg_lambda': 0.1534346453596084, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  32%|███▏      | 64/200 [01:03<01:51,  1.22it/s]

[I 2025-11-10 17:23:25,635] Trial 63 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03535020394387528, 'n_estimators': 500, 'subsample': 0.6761478802372201, 'colsample_bytree': 0.7600871558419398, 'min_child_weight': 8, 'gamma': 3.813100764843102, 'reg_alpha': 2.1779410087408245e-05, 'reg_lambda': 0.013959279093196619, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  32%|███▎      | 65/200 [01:04<02:07,  1.06it/s]

[I 2025-11-10 17:23:26,864] Trial 65 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10993711352540161, 'n_estimators': 557, 'subsample': 0.5043192298361799, 'colsample_bytree': 0.5010925484988157, 'min_child_weight': 6, 'gamma': 3.8099964052544055, 'reg_alpha': 1.4324740785854815e-05, 'reg_lambda': 7.648187909049899e-08, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  33%|███▎      | 66/200 [01:07<03:14,  1.45s/it]

[I 2025-11-10 17:23:29,499] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.11709652336441538, 'n_estimators': 1175, 'subsample': 0.5355418381177389, 'colsample_bytree': 0.5471656416553212, 'min_child_weight': 3, 'gamma': 2.9449347993822674, 'reg_alpha': 7.593514544958437, 'reg_lambda': 2.1657617113601523e-08, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  34%|███▎      | 67/200 [01:07<02:32,  1.15s/it]

[I 2025-11-10 17:23:29,946] Trial 66 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.12043888720706586, 'n_estimators': 1058, 'subsample': 0.5657480226642893, 'colsample_bytree': 0.5217309887913523, 'min_child_weight': 3, 'gamma': 2.8440958462893455, 'reg_alpha': 6.280949471021039, 'reg_lambda': 8.84764353498858e-08, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  34%|███▍      | 68/200 [01:09<02:50,  1.29s/it]

[I 2025-11-10 17:23:31,572] Trial 67 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.11075528363027687, 'n_estimators': 1158, 'subsample': 0.5700899501750305, 'colsample_bytree': 0.5367775928099627, 'min_child_weight': 7, 'gamma': 2.1973945482911086, 'reg_alpha': 6.733419589298995, 'reg_lambda': 1.4060261873904335e-08, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  34%|███▍      | 69/200 [01:11<02:55,  1.34s/it]

[I 2025-11-10 17:23:33,028] Trial 68 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2576379699738454, 'n_estimators': 1181, 'subsample': 0.5683410746352757, 'colsample_bytree': 0.5297009987397684, 'min_child_weight': 7, 'gamma': 2.9083896333045898, 'reg_alpha': 3.6879567883019493, 'reg_lambda': 1.2447970830900742e-08, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  35%|███▌      | 70/200 [01:11<02:18,  1.06s/it]

[I 2025-11-10 17:23:33,449] Trial 70 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.26761041014116965, 'n_estimators': 704, 'subsample': 0.6189456773028895, 'colsample_bytree': 0.680357545621269, 'min_child_weight': 7, 'gamma': 4.752950724636475, 'reg_alpha': 2.261310396675112, 'reg_lambda': 1.3623330144981104e-08, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  36%|███▌      | 71/200 [01:13<02:34,  1.20s/it]

[I 2025-11-10 17:23:34,952] Trial 69 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.26311519397198685, 'n_estimators': 1048, 'subsample': 0.5649515454955295, 'colsample_bytree': 0.5251439972567171, 'min_child_weight': 7, 'gamma': 1.164267266699368, 'reg_alpha': 1.9873391327806904, 'reg_lambda': 8.049455911609875e-08, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  36%|███▌      | 72/200 [01:13<02:09,  1.01s/it]

[I 2025-11-10 17:23:35,540] Trial 71 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.26280374980827925, 'n_estimators': 717, 'subsample': 0.8296545945169824, 'colsample_bytree': 0.6203643119769271, 'min_child_weight': 7, 'gamma': 1.1888150814394614, 'reg_alpha': 2.1506976526253054, 'reg_lambda': 1.1852521576313246, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  36%|███▋      | 73/200 [01:15<02:33,  1.21s/it]

[I 2025-11-10 17:23:37,189] Trial 72 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.16150516598841905, 'n_estimators': 803, 'subsample': 0.7968050297629702, 'colsample_bytree': 0.6824732864511406, 'min_child_weight': 7, 'gamma': 0.21193950611130075, 'reg_alpha': 3.1434662366639326e-07, 'reg_lambda': 0.008180396467648612, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  37%|███▋      | 74/200 [01:16<02:50,  1.35s/it]

[I 2025-11-10 17:23:38,872] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.1558216520120905, 'n_estimators': 689, 'subsample': 0.709713752334127, 'colsample_bytree': 0.6138373920890776, 'min_child_weight': 6, 'gamma': 1.9762697167668761, 'reg_alpha': 5.278925660216962e-07, 'reg_lambda': 0.3349920618910665, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  38%|███▊      | 75/200 [01:17<02:21,  1.13s/it]

[I 2025-11-10 17:23:39,498] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.18122142733904653, 'n_estimators': 790, 'subsample': 0.7087870779337507, 'colsample_bytree': 0.5567225768526972, 'min_child_weight': 8, 'gamma': 1.6260660867605279, 'reg_alpha': 6.183644391933136e-07, 'reg_lambda': 2.343676950822511, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  38%|███▊      | 76/200 [01:19<02:36,  1.26s/it]

[I 2025-11-10 17:23:41,061] Trial 73 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.17319326633392795, 'n_estimators': 1406, 'subsample': 0.8257706599942974, 'colsample_bytree': 0.8877466385780249, 'min_child_weight': 9, 'gamma': 1.149725367955568, 'reg_alpha': 6.126255165541209e-07, 'reg_lambda': 0.008510555414354307, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  38%|███▊      | 77/200 [01:20<02:22,  1.16s/it]

[I 2025-11-10 17:23:41,995] Trial 76 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02164122828457763, 'n_estimators': 898, 'subsample': 0.7095514031192265, 'colsample_bytree': 0.5624416919904679, 'min_child_weight': 8, 'gamma': 2.6736829114759546, 'reg_alpha': 2.824441460893983e-06, 'reg_lambda': 0.27007359129616215, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  39%|███▉      | 78/200 [01:21<02:35,  1.27s/it]

[I 2025-11-10 17:23:43,529] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.021577567321250206, 'n_estimators': 882, 'subsample': 0.7556459780966127, 'colsample_bytree': 0.5691379133130924, 'min_child_weight': 8, 'gamma': 2.7408770939061173, 'reg_alpha': 1.9968658243862885e-06, 'reg_lambda': 0.1987256808397641, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  40%|███▉      | 79/200 [01:22<02:20,  1.16s/it]

[I 2025-11-10 17:23:44,430] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.02081741906567131, 'n_estimators': 949, 'subsample': 0.8789211645220514, 'colsample_bytree': 0.9215351302651481, 'min_child_weight': 8, 'gamma': 1.7162141738194427, 'reg_alpha': 2.818751051165329e-06, 'reg_lambda': 2.53862837266259, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  40%|████      | 80/200 [01:22<01:50,  1.08it/s]

[I 2025-11-10 17:23:44,782] Trial 80 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.014944895909907769, 'n_estimators': 498, 'subsample': 0.6315315835075441, 'colsample_bytree': 0.9186258499452628, 'min_child_weight': 6, 'gamma': 2.215636525658739, 'reg_alpha': 0.15102848920676734, 'reg_lambda': 3.6324761963609316, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  40%|████      | 81/200 [01:24<01:59,  1.00s/it]

[I 2025-11-10 17:23:45,978] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.0950243683788504, 'n_estimators': 934, 'subsample': 0.8724300824859474, 'colsample_bytree': 0.9200183789981601, 'min_child_weight': 8, 'gamma': 2.2555027571632897, 'reg_alpha': 9.394975448555584e-05, 'reg_lambda': 4.104931321366857, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  41%|████      | 82/200 [01:24<01:42,  1.15it/s]

[I 2025-11-10 17:23:46,537] Trial 81 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06324212075670417, 'n_estimators': 567, 'subsample': 0.8798801267397471, 'colsample_bytree': 0.601800203864425, 'min_child_weight': 6, 'gamma': 2.3650296604639913, 'reg_alpha': 0.0005514033602728582, 'reg_lambda': 2.9735647356423507, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  42%|████▏     | 83/200 [01:26<02:03,  1.06s/it]

[I 2025-11-10 17:23:48,024] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.14026124635963916, 'n_estimators': 656, 'subsample': 0.5157874717283616, 'colsample_bytree': 0.8527635290004395, 'min_child_weight': 5, 'gamma': 0.9443476778874897, 'reg_alpha': 0.000600930667206088, 'reg_lambda': 0.6910106774676481, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  42%|████▏     | 84/200 [01:28<02:58,  1.54s/it]

[I 2025-11-10 17:23:50,687] Trial 82 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.014207439726819628, 'n_estimators': 1274, 'subsample': 0.5099312663548751, 'colsample_bytree': 0.808839513061278, 'min_child_weight': 9, 'gamma': 2.193999684715818, 'reg_alpha': 0.18709038370328357, 'reg_lambda': 0.0014543359817853294, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  42%|████▎     | 85/200 [01:29<02:42,  1.42s/it]

[I 2025-11-10 17:23:51,818] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.13645047502669091, 'n_estimators': 1284, 'subsample': 0.5185984617038062, 'colsample_bytree': 0.6605423515352835, 'min_child_weight': 6, 'gamma': 0.8437792206286898, 'reg_alpha': 0.5719232795395126, 'reg_lambda': 0.02360794203128674, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  43%|████▎     | 86/200 [01:30<02:17,  1.21s/it]

[I 2025-11-10 17:23:52,540] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.13632240948372434, 'n_estimators': 1312, 'subsample': 0.5159636151121351, 'colsample_bytree': 0.6335932709546803, 'min_child_weight': 5, 'gamma': 0.9148244804734567, 'reg_alpha': 0.6774289881407374, 'reg_lambda': 0.001873119632898673, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  44%|████▎     | 87/200 [01:32<02:31,  1.34s/it]

[I 2025-11-10 17:23:54,177] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.043957894826856844, 'n_estimators': 1322, 'subsample': 0.537651392497137, 'colsample_bytree': 0.6606289326955578, 'min_child_weight': 7, 'gamma': 0.8036205683697265, 'reg_alpha': 0.641183225187273, 'reg_lambda': 0.026313444076886187, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  44%|████▍     | 88/200 [01:32<01:52,  1.00s/it]

[I 2025-11-10 17:23:54,406] Trial 89 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.06620695904303543, 'n_estimators': 378, 'subsample': 0.6065183540912938, 'colsample_bytree': 0.6967754722843714, 'min_child_weight': 9, 'gamma': 0.46865187800259706, 'reg_alpha': 0.0021410225027669867, 'reg_lambda': 0.038686688854259625, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  44%|████▍     | 89/200 [01:34<02:39,  1.43s/it]

[I 2025-11-10 17:23:56,839] Trial 87 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.06662005304012926, 'n_estimators': 1294, 'subsample': 0.5335681428486297, 'colsample_bytree': 0.6481958837307139, 'min_child_weight': 7, 'gamma': 0.8258159080135512, 'reg_alpha': 0.966153315644108, 'reg_lambda': 0.00012061259258894919, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:23:56,846] Trial 90 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.06823409779727532, 'n_estimators': 424, 'subsample': 0.662676425368405, 'colsample_bytree': 0.7017714180038209, 'min_child_weight': 7, 'gamma': 0.5517548763093536, 'reg_alpha': 0.0022002051534490957, 'reg_lambda': 0.00011968677036356396, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  46%|████▌     | 91/200 [01:36<02:10,  1.20s/it]

[I 2025-11-10 17:23:58,702] Trial 88 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.07013816805289518, 'n_estimators': 1494, 'subsample': 0.534210601911601, 'colsample_bytree': 0.6411731468827601, 'min_child_weight': 7, 'gamma': 0.5121211978287423, 'reg_alpha': 0.6200468829198176, 'reg_lambda': 0.0015604350536342867, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  46%|████▌     | 92/200 [01:38<02:24,  1.33s/it]

[I 2025-11-10 17:24:00,409] Trial 93 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.05095977741801368, 'n_estimators': 765, 'subsample': 0.9060563140320779, 'colsample_bytree': 0.7764496797611417, 'min_child_weight': 8, 'gamma': 0.1794002912937691, 'reg_alpha': 4.531949012615377, 'reg_lambda': 0.00047661441953539925, 'max_delta_step': 1}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  46%|████▋     | 93/200 [01:38<01:59,  1.11s/it]

[I 2025-11-10 17:24:00,929] Trial 92 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.04915953128635893, 'n_estimators': 778, 'subsample': 0.8974910019265703, 'colsample_bytree': 0.7760902920299438, 'min_child_weight': 8, 'gamma': 0.19674150431070053, 'reg_alpha': 0.007975817585017897, 'reg_lambda': 1.6763220280982224e-06, 'max_delta_step': 1}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  47%|████▋     | 94/200 [01:39<01:38,  1.08it/s]

[I 2025-11-10 17:24:01,350] Trial 96 pruned.

Best trial: 3. Best value: 0.5:  48%|████▊     | 95/200 [01:39<01:18,  1.33it/s]

[I 2025-11-10 17:24:01,662] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.05088091323707499, 'n_estimators': 475, 'subsample': 0.686742475847846, 'colsample_bytree': 0.9031212032514783, 'min_child_weight': 5, 'gamma': 4.413423884401008, 'reg_alpha': 0.011178637409893367, 'reg_lambda': 0.0005157362762881253, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  48%|████▊     | 96/200 [01:40<01:05,  1.60it/s]

[I 2025-11-10 17:24:01,966] Trial 91 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.024250960160488912, 'n_estimators': 1489, 'subsample': 0.6675887988861257, 'colsample_bytree': 0.7103022201548984, 'min_child_weight': 7, 'gamma': 0.2513263300861821, 'reg_alpha': 0.008971136440715687, 'reg_lambda': 0.07288990929337863, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  48%|████▊     | 97/200 [01:40<00:57,  1.78it/s]

[I 2025-11-10 17:24:02,370] Trial 98 pruned.
[I 2025-11-10 17:24:02,374] Trial 95 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.016043013120414052, 'n_estimators': 257, 'subsample': 0.6962447828994908, 'colsample_bytree': 0.9544367878566932, 'min_child_weight': 5, 'gamma': 4.408713911190746, 'reg_alpha': 0.014199283892083307, 'reg_lambda': 0.004773358871271445, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  50%|████▉     | 99/200 [01:40<00:41,  2.44it/s]

[I 2025-11-10 17:24:02,818] Trial 101 pruned.

Best trial: 3. Best value: 0.5:  50%|█████     | 100/200 [01:41<00:45,  2.21it/s]

[I 2025-11-10 17:24:03,410] Trial 97 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.023967203247177597, 'n_estimators': 349, 'subsample': 0.6919837740043365, 'colsample_bytree': 0.8888717884594807, 'min_child_weight': 5, 'gamma': 4.625035972834811, 'reg_alpha': 5.476032964349521e-08, 'reg_lambda': 0.0006753241712083836, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 99. Best value: 0.544639:  50%|█████     | 101/200 [01:41<00:45,  2.20it/s]

[I 2025-11-10 17:24:03,870] Trial 99 finished with value: 0.5446393762183236 and parameters: {'max_depth': 7, 'learning_rate': 0.01183895661283495, 'n_estimators': 365, 'subsample': 0.636824260500448, 'colsample_bytree': 0.5865106540986583, 'min_child_weight': 4, 'gamma': 4.567589502679374, 'reg_alpha': 0.3216151548889177, 'reg_lambda': 0.000891672968065705, 'max_delta_step': 9}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  51%|█████     | 102/200 [01:42<00:46,  2.13it/s]

[I 2025-11-10 17:24:04,377] Trial 104 pruned.
[I 2025-11-10 17:24:04,377] Trial 100 pruned.

Best trial: 99. Best value: 0.544639:  52%|█████▏    | 104/200 [01:43<00:38,  2.49it/s]

[I 2025-11-10 17:24:05,015] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.08342799634582089, 'n_estimators': 415, 'subsample': 0.7530117731470045, 'colsample_bytree': 0.6804558076617927, 'min_child_weight': 6, 'gamma': 4.934173425921317, 'reg_alpha': 0.0001223335169330943, 'reg_lambda': 0.014920670391448147, 'max_delta_step': 6}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  52%|█████▎    | 105/200 [01:43<00:40,  2.33it/s]

[I 2025-11-10 17:24:05,531] Trial 107 pruned.

Best trial: 99. Best value: 0.544639:  54%|█████▎    | 107/200 [01:46<01:07,  1.38it/s]

[I 2025-11-10 17:24:07,992] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.01050800768697161, 'n_estimators': 675, 'subsample': 0.5542565429136674, 'colsample_bytree': 0.625487445149292, 'min_child_weight': 4, 'gamma': 3.5332294379061597, 'reg_alpha': 1.5162377528085584, 'reg_lambda': 0.00022817201803422451, 'max_delta_step': 8}. Best is trial 99 with value: 0.5446393762183236.
[I 2025-11-10 17:24:08,108] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.013417101339495094, 'n_estimators': 674, 'subsample': 0.5008900402271622, 'colsample_bytree': 0.8789462001256912, 'min_child_weight': 4, 'gamma': 3.483599809395482, 'reg_alpha': 1.4431998088348605, 'reg_lambda': 0.018067869836771985, 'max_delta_step': 8}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  54%|█████▍    | 108/200 [01:46<00:57,  1.59it/s]

[I 2025-11-10 17:24:08,486] Trial 108 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.013112506904959506, 'n_estimators': 524, 'subsample': 0.7254830795312565, 'colsample_bytree': 0.8992890945270872, 'min_child_weight': 9, 'gamma': 4.1034942343690375, 'reg_alpha': 3.582794765946255e-05, 'reg_lambda': 4.417944044949948e-06, 'max_delta_step': 8}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  55%|█████▍    | 109/200 [01:47<01:17,  1.17it/s]

[I 2025-11-10 17:24:09,914] Trial 109 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.013383487288482968, 'n_estimators': 379, 'subsample': 0.7266193819669529, 'colsample_bytree': 0.8756904923065992, 'min_child_weight': 9, 'gamma': 2.6000409687227166, 'reg_alpha': 0.11816396936761746, 'reg_lambda': 0.0010781897300134952, 'max_delta_step': 10}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  55%|█████▌    | 110/200 [01:48<01:17,  1.17it/s]

[I 2025-11-10 17:24:10,769] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.011219218266683212, 'n_estimators': 1418, 'subsample': 0.7661817314561341, 'colsample_bytree': 0.879719758858656, 'min_child_weight': 6, 'gamma': 1.2925943423913604, 'reg_alpha': 9.230508315815826e-05, 'reg_lambda': 2.3288970263325323e-07, 'max_delta_step': 6}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  56%|█████▌    | 111/200 [01:49<01:02,  1.43it/s]

[I 2025-11-10 17:24:11,095] Trial 110 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04243463006371543, 'n_estimators': 622, 'subsample': 0.5743769974697578, 'colsample_bytree': 0.578929060435132, 'min_child_weight': 9, 'gamma': 2.5392052411901993, 'reg_alpha': 3.677540563631314e-05, 'reg_lambda': 0.0010257462163422305, 'max_delta_step': 10}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  56%|█████▌    | 112/200 [01:53<02:24,  1.64s/it]

[I 2025-11-10 17:24:15,001] Trial 111 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03712437785255501, 'n_estimators': 1396, 'subsample': 0.8017632951089491, 'colsample_bytree': 0.8182255838580416, 'min_child_weight': 6, 'gamma': 2.509608218528671, 'reg_alpha': 0.0002962797180811197, 'reg_lambda': 1.6905617203057754e-07, 'max_delta_step': 10}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  56%|█████▋    | 113/200 [01:53<02:02,  1.40s/it]

[I 2025-11-10 17:24:15,844] Trial 114 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.09764859242311458, 'n_estimators': 1013, 'subsample': 0.6150478225121502, 'colsample_bytree': 0.7399026557913686, 'min_child_weight': 10, 'gamma': 4.748531769616672, 'reg_alpha': 0.0003941341196916738, 'reg_lambda': 5.1556677700115846e-08, 'max_delta_step': 9}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  57%|█████▋    | 114/200 [01:54<01:37,  1.14s/it]

[I 2025-11-10 17:24:16,347] Trial 115 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.10282145581908814, 'n_estimators': 251, 'subsample': 0.6140401343352835, 'colsample_bytree': 0.7410021608845286, 'min_child_weight': 10, 'gamma': 4.745143347110988, 'reg_alpha': 1.4384145214817396e-05, 'reg_lambda': 1.9131838850891487e-08, 'max_delta_step': 9}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  57%|█████▊    | 115/200 [01:54<01:17,  1.10it/s]

[I 2025-11-10 17:24:16,709] Trial 112 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01143894989150079, 'n_estimators': 1406, 'subsample': 0.79935661812551, 'colsample_bytree': 0.8163038676345279, 'min_child_weight': 6, 'gamma': 0.6376667183238867, 'reg_alpha': 0.2662488379838029, 'reg_lambda': 8.207443930831075e-07, 'max_delta_step': 9}. Best is trial 99 with value: 0.5446393762183236.
[I 2025-11-10 17:24:16,721] Trial 113 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.017650965020183224, 'n_estimators': 1221, 'subsample': 0.6638668452485731, 'colsample_bytree': 0.8152839150398188, 'min_child_weight': 10, 'gamma': 3.8796142283228736, 'reg_alpha': 0.0003283953130182279, 'reg_lambda': 8.298306131039463e-07, 'max_delta_step': 9}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  58%|█████▊    | 117/200 [01:59<02:04,  1.50s/it]

[I 2025-11-10 17:24:21,111] Trial 116 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.07433101126603375, 'n_estimators': 1115, 'subsample': 0.6408803399619513, 'colsample_bytree': 0.7895504087176388, 'min_child_weight': 10, 'gamma': 4.838875228134409, 'reg_alpha': 0.3833006549947761, 'reg_lambda': 5.498059900593385e-07, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  59%|█████▉    | 118/200 [01:59<01:44,  1.28s/it]

[I 2025-11-10 17:24:21,704] Trial 118 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.0774553787550763, 'n_estimators': 1093, 'subsample': 0.6370260781739826, 'colsample_bytree': 0.6027656069287001, 'min_child_weight': 8, 'gamma': 4.613085291289672, 'reg_alpha': 0.0001809581120522787, 'reg_lambda': 2.9142358615548407e-08, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.
[I 2025-11-10 17:24:21,709] Trial 117 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.07544937046557228, 'n_estimators': 1105, 'subsample': 0.6620294758761419, 'colsample_bytree': 0.7528914759385807, 'min_child_weight': 10, 'gamma': 4.556967581428086, 'reg_alpha': 0.00017506930836922032, 'reg_lambda': 8.184205360942125e-07, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  60%|██████    | 120/200 [02:00<01:05,  1.22it/s]

[I 2025-11-10 17:24:22,043] Trial 119 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.07663225301252895, 'n_estimators': 1105, 'subsample': 0.6367695524113545, 'colsample_bytree': 0.789862688365788, 'min_child_weight': 8, 'gamma': 1.928862463073798, 'reg_alpha': 2.9188208391032724, 'reg_lambda': 2.5268616224832005e-08, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  60%|██████    | 121/200 [02:03<01:46,  1.34s/it]

[I 2025-11-10 17:24:25,159] Trial 120 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.0811060832143998, 'n_estimators': 819, 'subsample': 0.5951377255267075, 'colsample_bytree': 0.729908713129785, 'min_child_weight': 8, 'gamma': 3.1114246166538964, 'reg_alpha': 1.1113499956631601e-08, 'reg_lambda': 3.0580580660516854e-08, 'max_delta_step': 4}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  61%|██████    | 122/200 [02:03<01:26,  1.11s/it]

[I 2025-11-10 17:24:25,563] Trial 122 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2942724420411277, 'n_estimators': 737, 'subsample': 0.5574146436564392, 'colsample_bytree': 0.7282357262794785, 'min_child_weight': 8, 'gamma': 1.9356241582434626, 'reg_alpha': 2.4643759736777184, 'reg_lambda': 0.009493077557708734, 'max_delta_step': 4}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  62%|██████▏   | 124/200 [02:04<00:53,  1.42it/s]

[I 2025-11-10 17:24:25,952] Trial 121 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05556879385535079, 'n_estimators': 816, 'subsample': 0.6267687639366504, 'colsample_bytree': 0.9841676486519035, 'min_child_weight': 8, 'gamma': 1.8327401901204035, 'reg_alpha': 2.588724283665494, 'reg_lambda': 0.00889855129094785, 'max_delta_step': 4}. Best is trial 99 with value: 0.5446393762183236.
[I 2025-11-10 17:24:26,060] Trial 123 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05406897090119806, 'n_estimators': 823, 'subsample': 0.622991602610129, 'colsample_bytree': 0.5471290261506004, 'min_child_weight': 7, 'gamma': 2.804411927498484, 'reg_alpha': 4.628402479751026, 'reg_lambda': 4.766424698863771e-08, 'max_delta_step': 4}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  62%|██████▎   | 125/200 [02:08<02:11,  1.75s/it]

[I 2025-11-10 17:24:30,509] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.08839530172553789, 'n_estimators': 1145, 'subsample': 0.5459406747249075, 'colsample_bytree': 0.7659964910892482, 'min_child_weight': 10, 'gamma': 2.075567433627853, 'reg_alpha': 0.0013830087428982518, 'reg_lambda': 1.1135279018446081e-08, 'max_delta_step': 8}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  63%|██████▎   | 126/200 [02:10<02:08,  1.74s/it]

[I 2025-11-10 17:24:32,210] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05443524631451396, 'n_estimators': 1430, 'subsample': 0.6242907222751368, 'colsample_bytree': 0.8469572434586322, 'min_child_weight': 10, 'gamma': 1.7868061672917308, 'reg_alpha': 0.0019872637515605668, 'reg_lambda': 5.2304007455080497e-08, 'max_delta_step': 5}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  64%|██████▎   | 127/200 [02:10<01:40,  1.38s/it]

[I 2025-11-10 17:24:32,723] Trial 127 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.027846295413556033, 'n_estimators': 1431, 'subsample': 0.5837223234138691, 'colsample_bytree': 0.7671185391741893, 'min_child_weight': 9, 'gamma': 2.404756229522142, 'reg_alpha': 0.001635741735289496, 'reg_lambda': 1.3366179225366032e-08, 'max_delta_step': 8}. Best is trial 99 with value: 0.5446393762183236.
[I 2025-11-10 17:24:32,765] Trial 126 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.0864472983100556, 'n_estimators': 1449, 'subsample': 0.5875270840842468, 'colsample_bytree': 0.8427050583071445, 'min_child_weight': 10, 'gamma': 0.37971698428731, 'reg_alpha': 1.1486773484529952e-06, 'reg_lambda': 1.2917382782090859e-08, 'max_delta_step': 8}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  64%|██████▍   | 129/200 [02:12<01:14,  1.04s/it]

[I 2025-11-10 17:24:33,990] Trial 129 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.24486728454500575, 'n_estimators': 315, 'subsample': 0.5772768833024781, 'colsample_bytree': 0.9321916310427037, 'min_child_weight': 9, 'gamma': 4.273599815826367, 'reg_alpha': 3.4262368860941365e-07, 'reg_lambda': 1.7395909597899745e-08, 'max_delta_step': 3}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  65%|██████▌   | 130/200 [02:12<01:01,  1.14it/s]

[I 2025-11-10 17:24:34,346] Trial 131 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04678296541944716, 'n_estimators': 295, 'subsample': 0.604679018521159, 'colsample_bytree': 0.911687469516487, 'min_child_weight': 9, 'gamma': 4.282871003540576, 'reg_alpha': 0.004605588468159152, 'reg_lambda': 1.4765092363319296e-07, 'max_delta_step': 6}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  66%|██████▌   | 131/200 [02:14<01:25,  1.24s/it]

[I 2025-11-10 17:24:36,644] Trial 128 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.19548867487937688, 'n_estimators': 1247, 'subsample': 0.5884011624991969, 'colsample_bytree': 0.8410872010423083, 'min_child_weight': 10, 'gamma': 0.35465693653734864, 'reg_alpha': 3.1678321181955457e-07, 'reg_lambda': 1.755352651291134e-08, 'max_delta_step': 5}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  66%|██████▌   | 132/200 [02:16<01:41,  1.49s/it]

[I 2025-11-10 17:24:38,797] Trial 130 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.18860703194083658, 'n_estimators': 1194, 'subsample': 0.5902352238615044, 'colsample_bytree': 0.7150777707633765, 'min_child_weight': 9, 'gamma': 4.272278696190502, 'reg_alpha': 0.0006803150012080948, 'reg_lambda': 0.002036698946588484, 'max_delta_step': 0}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  66%|██████▋   | 133/200 [02:18<01:42,  1.53s/it]

[I 2025-11-10 17:24:40,448] Trial 132 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.06191233302256591, 'n_estimators': 1374, 'subsample': 0.525677883130578, 'colsample_bytree': 0.6368550814529401, 'min_child_weight': 4, 'gamma': 1.0601891082572488, 'reg_alpha': 7.040172969760304e-06, 'reg_lambda': 0.047963535030562485, 'max_delta_step': 10}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  67%|██████▋   | 134/200 [02:19<01:22,  1.25s/it]

[I 2025-11-10 17:24:40,968] Trial 133 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1938758524398556, 'n_estimators': 1341, 'subsample': 0.7888981411626226, 'colsample_bytree': 0.6656471483749631, 'min_child_weight': 5, 'gamma': 0.6778772500841972, 'reg_alpha': 5.345590489556298e-05, 'reg_lambda': 0.0022225264875801133, 'max_delta_step': 3}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  68%|██████▊   | 135/200 [02:21<01:44,  1.61s/it]

[I 2025-11-10 17:24:43,469] Trial 134 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.29760701660177685, 'n_estimators': 1348, 'subsample': 0.6483463622909409, 'colsample_bytree': 0.9691514368338116, 'min_child_weight': 10, 'gamma': 0.6485569179975585, 'reg_alpha': 2.155294172845756e-05, 'reg_lambda': 0.10783480883818997, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  68%|██████▊   | 136/200 [02:21<01:18,  1.23s/it]

[I 2025-11-10 17:24:43,767] Trial 135 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.06252031737742181, 'n_estimators': 947, 'subsample': 0.654202395644699, 'colsample_bytree': 0.9735794388511363, 'min_child_weight': 10, 'gamma': 1.4769130784636926, 'reg_alpha': 9.275063864200232e-06, 'reg_lambda': 0.11812537193414431, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  68%|██████▊   | 137/200 [02:23<01:19,  1.26s/it]

[I 2025-11-10 17:24:45,111] Trial 136 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2935528205824277, 'n_estimators': 921, 'subsample': 0.6504764960467687, 'colsample_bytree': 0.9791073576943065, 'min_child_weight': 10, 'gamma': 1.010192976298412, 'reg_alpha': 1.4214467539933894e-05, 'reg_lambda': 1.1875399469804914e-05, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  69%|██████▉   | 138/200 [02:23<01:07,  1.08s/it]

[I 2025-11-10 17:24:45,767] Trial 139 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.015082687162102811, 'n_estimators': 399, 'subsample': 0.681031810713379, 'colsample_bytree': 0.9419061872902756, 'min_child_weight': 7, 'gamma': 4.418219538859501, 'reg_alpha': 5.216868877173603e-05, 'reg_lambda': 1.3242682913899119e-05, 'max_delta_step': 6}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  70%|██████▉   | 139/200 [02:25<01:25,  1.39s/it]

[I 2025-11-10 17:24:47,894] Trial 137 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.29726780951178317, 'n_estimators': 1471, 'subsample': 0.6091042530581661, 'colsample_bytree': 0.9868351690185081, 'min_child_weight': 10, 'gamma': 3.644922866325588, 'reg_alpha': 1.1804448109955749e-05, 'reg_lambda': 5.317483566256872e-05, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  70%|███████   | 140/200 [02:26<01:08,  1.14s/it]

[I 2025-11-10 17:24:48,464] Trial 138 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03306096480381953, 'n_estimators': 1011, 'subsample': 0.6089076279352389, 'colsample_bytree': 0.9415963371805709, 'min_child_weight': 7, 'gamma': 1.5029928868597797, 'reg_alpha': 0.03818671805654054, 'reg_lambda': 1.5687424342664864, 'max_delta_step': 6}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  70%|███████   | 141/200 [02:27<00:59,  1.01s/it]

[I 2025-11-10 17:24:49,146] Trial 142 pruned.

Best trial: 99. Best value: 0.544639:  71%|███████   | 142/200 [02:27<00:48,  1.21it/s]

[I 2025-11-10 17:24:49,552] Trial 143 pruned.

Best trial: 99. Best value: 0.544639:  72%|███████▏  | 143/200 [02:27<00:36,  1.55it/s]

[I 2025-11-10 17:24:49,765] Trial 140 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.0152504638544902, 'n_estimators': 970, 'subsample': 0.853152499312602, 'colsample_bytree': 0.6884668898118541, 'min_child_weight': 7, 'gamma': 4.011807294433299, 'reg_alpha': 0.038997486118379485, 'reg_lambda': 4.778785493182441e-05, 'max_delta_step': 9}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  72%|███████▏  | 144/200 [02:28<00:43,  1.29it/s]

[I 2025-11-10 17:24:50,861] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.04043440351558343, 'n_estimators': 973, 'subsample': 0.6117575545868326, 'colsample_bytree': 0.9974346768407054, 'min_child_weight': 4, 'gamma': 4.024567538755702, 'reg_alpha': 9.036209646170528, 'reg_lambda': 5.6059366825825615e-05, 'max_delta_step': 9}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  72%|███████▎  | 145/200 [02:32<01:18,  1.43s/it]

[I 2025-11-10 17:24:53,793] Trial 145 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2721649966525097, 'n_estimators': 852, 'subsample': 0.8525942112892223, 'colsample_bytree': 0.9985279178117915, 'min_child_weight': 9, 'gamma': 1.0891406355950517, 'reg_alpha': 1.6021447091697287e-07, 'reg_lambda': 4.866529327552186, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.
[I 2025-11-10 17:24:53,975] Trial 144 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.23784118796557588, 'n_estimators': 958, 'subsample': 0.860760465165076, 'colsample_bytree': 0.995304863618761, 'min_child_weight': 10, 'gamma': 1.0353821652358572, 'reg_alpha': 3.417213707853699e-06, 'reg_lambda': 5.259055967622543e-06, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  74%|███████▎  | 147/200 [02:32<00:46,  1.15it/s]

[I 2025-11-10 17:24:54,418] Trial 146 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2099377783246271, 'n_estimators': 976, 'subsample': 0.5572404125205059, 'colsample_bytree': 0.9973364802698127, 'min_child_weight': 10, 'gamma': 4.988531788762888, 'reg_alpha': 0.00022415339830774832, 'reg_lambda': 1.1409417796819587e-07, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  74%|███████▍  | 148/200 [02:32<00:38,  1.34it/s]

[I 2025-11-10 17:24:54,875] Trial 147 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.10476897924670327, 'n_estimators': 856, 'subsample': 0.5692347838204682, 'colsample_bytree': 0.6683986276827442, 'min_child_weight': 9, 'gamma': 1.066199986711066, 'reg_alpha': 3.232497085813176e-06, 'reg_lambda': 9.903885001326881e-08, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  74%|███████▍  | 149/200 [02:33<00:33,  1.50it/s]

[I 2025-11-10 17:24:55,353] Trial 151 pruned.

Best trial: 99. Best value: 0.544639:  75%|███████▌  | 150/200 [02:36<01:07,  1.36s/it]

[I 2025-11-10 17:24:58,317] Trial 148 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2266012853943828, 'n_estimators': 894, 'subsample': 0.8292745985730103, 'colsample_bytree': 0.566974255874866, 'min_child_weight': 10, 'gamma': 1.6772249427264394, 'reg_alpha': 1.6641811154016314e-06, 'reg_lambda': 2.7209593184343647e-06, 'max_delta_step': 8}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  76%|███████▌  | 151/200 [02:36<00:51,  1.05s/it]

[I 2025-11-10 17:24:58,663] Trial 150 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10492206542275671, 'n_estimators': 872, 'subsample': 0.5638773584112171, 'colsample_bytree': 0.6704157776091288, 'min_child_weight': 5, 'gamma': 1.247175116232665, 'reg_alpha': 9.727643444618992e-08, 'reg_lambda': 1.8970070338221772e-06, 'max_delta_step': 8}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  76%|███████▌  | 152/200 [02:37<00:49,  1.03s/it]

[I 2025-11-10 17:24:59,642] Trial 152 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.1498740418986616, 'n_estimators': 896, 'subsample': 0.8304176085233623, 'colsample_bytree': 0.6262354303939307, 'min_child_weight': 10, 'gamma': 1.6350661728434395, 'reg_alpha': 1.0962359379187285, 'reg_lambda': 0.0006802345016795867, 'max_delta_step': 8}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  76%|███████▋  | 153/200 [02:39<01:02,  1.34s/it]

[I 2025-11-10 17:25:01,702] Trial 154 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07091337525006652, 'n_estimators': 592, 'subsample': 0.601487171768454, 'colsample_bytree': 0.8020376962784754, 'min_child_weight': 10, 'gamma': 0.5621878143628105, 'reg_alpha': 2.4155010776586974e-05, 'reg_lambda': 0.7409405013892251, 'max_delta_step': 6}. Best is trial 99 with value: 0.5446393762183236.
[I 2025-11-10 17:25:01,773] Trial 149 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.21358059599278, 'n_estimators': 1500, 'subsample': 0.5595303677589084, 'colsample_bytree': 0.958281659187017, 'min_child_weight': 10, 'gamma': 1.6389734035460628, 'reg_alpha': 5.647061081142239e-06, 'reg_lambda': 1.8432810735520915e-06, 'max_delta_step': 8}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  78%|███████▊  | 155/200 [02:40<00:40,  1.12it/s]

[I 2025-11-10 17:25:02,456] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.09292204805548575, 'n_estimators': 536, 'subsample': 0.600427885716441, 'colsample_bytree': 0.7848677600756055, 'min_child_weight': 10, 'gamma': 0.9091507128516007, 'reg_alpha': 4.692289408779423e-06, 'reg_lambda': 0.8285891353952856, 'max_delta_step': 6}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  78%|███████▊  | 156/200 [02:42<00:46,  1.05s/it]

[I 2025-11-10 17:25:03,960] Trial 156 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.12316972949779459, 'n_estimators': 450, 'subsample': 0.7434705916056621, 'colsample_bytree': 0.782048249392001, 'min_child_weight': 10, 'gamma': 1.357876742309014, 'reg_alpha': 7.672951990099525e-05, 'reg_lambda': 3.792965088560038e-07, 'max_delta_step': 3}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  78%|███████▊  | 157/200 [02:42<00:39,  1.08it/s]

[I 2025-11-10 17:25:04,532] Trial 157 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1207320557917268, 'n_estimators': 555, 'subsample': 0.7423352463967626, 'colsample_bytree': 0.7827553471738541, 'min_child_weight': 10, 'gamma': 1.3538061335210132, 'reg_alpha': 6.795154919503003e-05, 'reg_lambda': 3.8640953063227803e-07, 'max_delta_step': 3}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  79%|███████▉  | 158/200 [02:43<00:37,  1.11it/s]

[I 2025-11-10 17:25:05,374] Trial 153 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.0711438708239613, 'n_estimators': 1499, 'subsample': 0.5390024945108141, 'colsample_bytree': 0.5126930783739528, 'min_child_weight': 6, 'gamma': 1.3821554741807667, 'reg_alpha': 4.821812952820684e-06, 'reg_lambda': 0.0003849430657962387, 'max_delta_step': 3}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  80%|███████▉  | 159/200 [02:43<00:31,  1.30it/s]

[I 2025-11-10 17:25:05,800] Trial 158 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.27510204861284826, 'n_estimators': 647, 'subsample': 0.6304613041600834, 'colsample_bytree': 0.8237529252203204, 'min_child_weight': 9, 'gamma': 4.851258274693173, 'reg_alpha': 0.46212368230578277, 'reg_lambda': 3.5182989445039143e-07, 'max_delta_step': 3}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  80%|████████  | 161/200 [02:45<00:26,  1.45it/s]

[I 2025-11-10 17:25:07,081] Trial 161 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.274286700558247, 'n_estimators': 331, 'subsample': 0.6257822549909418, 'colsample_bytree': 0.8264346784598707, 'min_child_weight': 7, 'gamma': 3.7237181643101054, 'reg_alpha': 8.384378229064333e-07, 'reg_lambda': 7.659052134008942e-06, 'max_delta_step': 10}. Best is trial 99 with value: 0.5446393762183236.
[I 2025-11-10 17:25:07,205] Trial 160 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.26436347219055406, 'n_estimators': 502, 'subsample': 0.6292753826458931, 'colsample_bytree': 0.7516044738226006, 'min_child_weight': 9, 'gamma': 2.3255351674911493, 'reg_alpha': 0.45754646176762687, 'reg_lambda': 6.190913230831067e-06, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  81%|████████  | 162/200 [02:45<00:20,  1.84it/s]

[I 2025-11-10 17:25:07,399] Trial 159 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.27657366307683223, 'n_estimators': 631, 'subsample': 0.6308168790902059, 'colsample_bytree': 0.8561107843133283, 'min_child_weight': 9, 'gamma': 1.1919957949513, 'reg_alpha': 3.136063884885975e-05, 'reg_lambda': 7.2830922309567455e-06, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  82%|████████▏ | 163/200 [02:45<00:16,  2.21it/s]

[I 2025-11-10 17:25:07,652] Trial 162 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.2718797142057897, 'n_estimators': 321, 'subsample': 0.7674859805933277, 'colsample_bytree': 0.7482213823540333, 'min_child_weight': 7, 'gamma': 1.2273930687543966, 'reg_alpha': 0.00044559232107868244, 'reg_lambda': 7.438260401589199e-06, 'max_delta_step': 10}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  82%|████████▏ | 164/200 [02:47<00:28,  1.25it/s]

[I 2025-11-10 17:25:09,270] Trial 163 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.045734025992876966, 'n_estimators': 368, 'subsample': 0.6733572918481978, 'colsample_bytree': 0.7520245937532279, 'min_child_weight': 7, 'gamma': 0.1072316807872421, 'reg_alpha': 0.8569988066692016, 'reg_lambda': 0.0013927650658612943, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  83%|████████▎ | 166/200 [02:48<00:22,  1.50it/s]

[I 2025-11-10 17:25:10,416] Trial 165 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03355880635912687, 'n_estimators': 601, 'subsample': 0.5117738770601028, 'colsample_bytree': 0.8085198491148039, 'min_child_weight': 9, 'gamma': 2.3051359168821164, 'reg_alpha': 1.7575290435541046e-08, 'reg_lambda': 6.434685216688342, 'max_delta_step': 6}. Best is trial 99 with value: 0.5446393762183236.
[I 2025-11-10 17:25:10,532] Trial 164 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03265431346299219, 'n_estimators': 611, 'subsample': 0.5434958393940909, 'colsample_bytree': 0.8672397272607594, 'min_child_weight': 9, 'gamma': 2.1086635815610033, 'reg_alpha': 3.673251677645012e-08, 'reg_lambda': 9.676213179103124, 'max_delta_step': 6}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  84%|████████▎ | 167/200 [02:48<00:16,  1.99it/s]

[I 2025-11-10 17:25:10,647] Trial 166 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04559856115490472, 'n_estimators': 606, 'subsample': 0.5236846402554449, 'colsample_bytree': 0.803704262926351, 'min_child_weight': 9, 'gamma': 2.059733591485865, 'reg_alpha': 2.9028788599068863e-08, 'reg_lambda': 9.557774590726465, 'max_delta_step': 6}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  84%|████████▍ | 168/200 [02:50<00:25,  1.26it/s]

[I 2025-11-10 17:25:12,123] Trial 167 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03332769411134579, 'n_estimators': 582, 'subsample': 0.5212882468324542, 'colsample_bytree': 0.6520287447053303, 'min_child_weight': 9, 'gamma': 0.287615261394194, 'reg_alpha': 2.3435942206897022e-08, 'reg_lambda': 1.6011791002199904, 'max_delta_step': 6}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  84%|████████▍ | 169/200 [02:51<00:32,  1.03s/it]

[I 2025-11-10 17:25:13,718] Trial 170 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.08179590318947588, 'n_estimators': 572, 'subsample': 0.5296972276467069, 'colsample_bytree': 0.7952215425884963, 'min_child_weight': 8, 'gamma': 2.4550001289287957, 'reg_alpha': 4.824548960905333, 'reg_lambda': 0.003018622666905629, 'max_delta_step': 1}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  85%|████████▌ | 170/200 [02:52<00:24,  1.22it/s]

[I 2025-11-10 17:25:14,045] Trial 168 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03677055514018383, 'n_estimators': 710, 'subsample': 0.5220244665943053, 'colsample_bytree': 0.799784436391148, 'min_child_weight': 9, 'gamma': 2.1448514173814313, 'reg_alpha': 0.11604611623879742, 'reg_lambda': 1.003105462597047e-08, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.
[I 2025-11-10 17:25:14,062] Trial 169 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03707045847513744, 'n_estimators': 704, 'subsample': 0.5208122263782102, 'colsample_bytree': 0.799957296423458, 'min_child_weight': 8, 'gamma': 2.4168852301525603, 'reg_alpha': 4.725252892881209, 'reg_lambda': 0.00015279996990609404, 'max_delta_step': 5}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  86%|████████▌ | 172/200 [02:54<00:29,  1.05s/it]

[I 2025-11-10 17:25:16,672] Trial 174 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.039805026260800964, 'n_estimators': 524, 'subsample': 0.6170000227567989, 'colsample_bytree': 0.76717788521761, 'min_child_weight': 10, 'gamma': 2.7343715004627125, 'reg_alpha': 5.500905276065727e-08, 'reg_lambda': 1.6618845432111442, 'max_delta_step': 5}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  86%|████████▋ | 173/200 [02:55<00:26,  1.01it/s]

[I 2025-11-10 17:25:17,486] Trial 173 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.014292494212819673, 'n_estimators': 674, 'subsample': 0.576593377258707, 'colsample_bytree': 0.7713297069341679, 'min_child_weight': 6, 'gamma': 2.6961817512590223, 'reg_alpha': 0.20005723770359807, 'reg_lambda': 0.00012740967170270654, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  87%|████████▋ | 174/200 [02:56<00:27,  1.05s/it]

[I 2025-11-10 17:25:18,684] Trial 171 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.020004077181116173, 'n_estimators': 1312, 'subsample': 0.6417569685554358, 'colsample_bytree': 0.7649123075501997, 'min_child_weight': 8, 'gamma': 2.715730466169407, 'reg_alpha': 0.000887088806181393, 'reg_lambda': 0.00018296747209410583, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  88%|████████▊ | 175/200 [02:57<00:26,  1.06s/it]

[I 2025-11-10 17:25:19,807] Trial 175 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.028427233534264497, 'n_estimators': 664, 'subsample': 0.576619489686855, 'colsample_bytree': 0.6142795043688075, 'min_child_weight': 8, 'gamma': 2.205367955440854, 'reg_alpha': 1.1071360151160998e-08, 'reg_lambda': 0.2031742157535388, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.
[I 2025-11-10 17:25:19,857] Trial 176 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.05875071952994037, 'n_estimators': 482, 'subsample': 0.5129368388828606, 'colsample_bytree': 0.5874506115772186, 'min_child_weight': 8, 'gamma': 0.9007094049991616, 'reg_alpha': 8.597194977648877e-06, 'reg_lambda': 0.47600583845847527, 'max_delta_step': 5}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  88%|████████▊ | 177/200 [02:58<00:15,  1.53it/s]

[I 2025-11-10 17:25:20,047] Trial 172 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.03972378529391648, 'n_estimators': 1279, 'subsample': 0.6428541341984753, 'colsample_bytree': 0.7612299618373408, 'min_child_weight': 6, 'gamma': 2.8811898528555635, 'reg_alpha': 8.491757378026166e-06, 'reg_lambda': 0.00015305499880853752, 'max_delta_step': 7}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  90%|████████▉ | 179/200 [02:59<00:12,  1.65it/s]

[I 2025-11-10 17:25:21,146] Trial 177 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.058886927534956966, 'n_estimators': 477, 'subsample': 0.7175416554265609, 'colsample_bytree': 0.7362620483208541, 'min_child_weight': 8, 'gamma': 2.246560099946235, 'reg_alpha': 1.6266378082922947e-08, 'reg_lambda': 0.39259230224709646, 'max_delta_step': 5}. Best is trial 99 with value: 0.5446393762183236.
[I 2025-11-10 17:25:21,303] Trial 180 pruned.

Best trial: 99. Best value: 0.544639:  90%|█████████ | 180/200 [03:00<00:14,  1.40it/s]

[I 2025-11-10 17:25:22,326] Trial 178 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.016538273766787567, 'n_estimators': 477, 'subsample': 0.5002332741387938, 'colsample_bytree': 0.733890563140356, 'min_child_weight': 8, 'gamma': 2.275593669239724, 'reg_alpha': 0.00028112848416773483, 'reg_lambda': 0.4706283410433336, 'max_delta_step': 5}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  90%|█████████ | 181/200 [03:00<00:10,  1.74it/s]

[I 2025-11-10 17:25:22,526] Trial 181 pruned.

Best trial: 99. Best value: 0.544639:  91%|█████████ | 182/200 [03:02<00:15,  1.18it/s]

[I 2025-11-10 17:25:24,077] Trial 182 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01663485986249888, 'n_estimators': 545, 'subsample': 0.5019042321957984, 'colsample_bytree': 0.9231414131092692, 'min_child_weight': 10, 'gamma': 4.507182602323182, 'reg_alpha': 0.00029097976203192586, 'reg_lambda': 4.390551549994937, 'max_delta_step': 4}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  92%|█████████▏| 183/200 [03:02<00:12,  1.38it/s]

[I 2025-11-10 17:25:24,501] Trial 183 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.06651997576796301, 'n_estimators': 396, 'subsample': 0.5460234630250367, 'colsample_bytree': 0.838459415048023, 'min_child_weight': 10, 'gamma': 2.5435933024518147, 'reg_alpha': 2.0246019060753886e-05, 'reg_lambda': 1.8179727087381554e-05, 'max_delta_step': 10}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  92%|█████████▏| 184/200 [03:03<00:12,  1.32it/s]

[I 2025-11-10 17:25:25,342] Trial 184 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.04269742045896776, 'n_estimators': 548, 'subsample': 0.5488689887590297, 'colsample_bytree': 0.8326875046159623, 'min_child_weight': 8, 'gamma': 1.9610579220118198, 'reg_alpha': 1.4662389457588467e-08, 'reg_lambda': 2.562463465347293, 'max_delta_step': 4}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  92%|█████████▎| 185/200 [03:04<00:12,  1.23it/s]

[I 2025-11-10 17:25:26,278] Trial 179 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01190865641772836, 'n_estimators': 1273, 'subsample': 0.508044903047793, 'colsample_bytree': 0.8327907930227016, 'min_child_weight': 8, 'gamma': 2.5366994646700114, 'reg_alpha': 1.499319821743343e-08, 'reg_lambda': 3.013269786859904, 'max_delta_step': 2}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  93%|█████████▎| 186/200 [03:09<00:27,  1.95s/it]

[I 2025-11-10 17:25:30,956] Trial 185 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.041723468784186146, 'n_estimators': 1442, 'subsample': 0.53291461784853, 'colsample_bytree': 0.7067621410961598, 'min_child_weight': 8, 'gamma': 1.999248734425862, 'reg_alpha': 5.275280226320462e-08, 'reg_lambda': 1.115936501200868, 'max_delta_step': 5}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  94%|█████████▎| 187/200 [03:09<00:20,  1.58s/it]

[I 2025-11-10 17:25:31,632] Trial 186 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.04409848376486559, 'n_estimators': 1460, 'subsample': 0.5325635681250322, 'colsample_bytree': 0.8126832354453672, 'min_child_weight': 8, 'gamma': 2.4191806529681648, 'reg_alpha': 1.5379708640411617e-08, 'reg_lambda': 1.9955389687332352, 'max_delta_step': 5}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  94%|█████████▍| 189/200 [03:10<00:09,  1.13it/s]

[I 2025-11-10 17:25:32,007] Trial 190 pruned.
[I 2025-11-10 17:25:32,107] Trial 187 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03506457023485051, 'n_estimators': 1460, 'subsample': 0.5304389255692594, 'colsample_bytree': 0.5334086982505583, 'min_child_weight': 7, 'gamma': 0.7325129229423952, 'reg_alpha': 4.1819077307257886e-08, 'reg_lambda': 1.355091994114297, 'max_delta_step': 8}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  95%|█████████▌| 190/200 [03:10<00:07,  1.29it/s]

[I 2025-11-10 17:25:32,640] Trial 189 pruned.

Best trial: 99. Best value: 0.544639:  96%|█████████▌| 191/200 [03:11<00:07,  1.27it/s]

[I 2025-11-10 17:25:33,438] Trial 188 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.013083673300965947, 'n_estimators': 1469, 'subsample': 0.5357537482116402, 'colsample_bytree': 0.8162457476088198, 'min_child_weight': 4, 'gamma': 3.4272925925189446, 'reg_alpha': 5.728028754869824e-08, 'reg_lambda': 0.973876626917394, 'max_delta_step': 5}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  96%|█████████▌| 192/200 [03:11<00:05,  1.55it/s]

[I 2025-11-10 17:25:33,759] Trial 192 pruned.

Best trial: 99. Best value: 0.544639:  96%|█████████▋| 193/200 [03:12<00:05,  1.30it/s]

[I 2025-11-10 17:25:34,829] Trial 193 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.04931285091537698, 'n_estimators': 428, 'subsample': 0.6230002681646744, 'colsample_bytree': 0.6035762406474396, 'min_child_weight': 10, 'gamma': 0.9895062056322341, 'reg_alpha': 4.798099469680874e-05, 'reg_lambda': 0.006393529764709006, 'max_delta_step': 10}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  97%|█████████▋| 194/200 [03:14<00:05,  1.00it/s]

[I 2025-11-10 17:25:36,348] Trial 195 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.17200976097941126, 'n_estimators': 515, 'subsample': 0.51523448762248, 'colsample_bytree': 0.9075960613271952, 'min_child_weight': 8, 'gamma': 3.029899767611369, 'reg_alpha': 1.8813197160354167, 'reg_lambda': 0.0011081960500536816, 'max_delta_step': 3}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  98%|█████████▊| 195/200 [03:14<00:04,  1.18it/s]

[I 2025-11-10 17:25:36,857] Trial 191 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03003844403971849, 'n_estimators': 990, 'subsample': 0.591621281276141, 'colsample_bytree': 0.7172115394732698, 'min_child_weight': 7, 'gamma': 0.9888311491020629, 'reg_alpha': 4.568221251100998e-05, 'reg_lambda': 0.005738213501600489, 'max_delta_step': 8}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  98%|█████████▊| 196/200 [03:15<00:02,  1.45it/s]

[I 2025-11-10 17:25:37,173] Trial 194 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.04963297210135641, 'n_estimators': 757, 'subsample': 0.5178790993603167, 'colsample_bytree': 0.6191061861437828, 'min_child_weight': 8, 'gamma': 2.1440480631620114, 'reg_alpha': 2.2812125449759888e-07, 'reg_lambda': 0.000723185024501421, 'max_delta_step': 4}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  98%|█████████▊| 197/200 [03:19<00:04,  1.66s/it]

[I 2025-11-10 17:25:41,100] Trial 197 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03520570460764015, 'n_estimators': 995, 'subsample': 0.5093154021266132, 'colsample_bytree': 0.634360381020403, 'min_child_weight': 7, 'gamma': 2.1559636687893815, 'reg_alpha': 4.5749751925888473e-07, 'reg_lambda': 0.0004473689453332736, 'max_delta_step': 4}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639:  99%|█████████▉| 198/200 [03:19<00:02,  1.24s/it]

[I 2025-11-10 17:25:41,357] Trial 196 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.0366267572668176, 'n_estimators': 1398, 'subsample': 0.5047286093209704, 'colsample_bytree': 0.5956463054913725, 'min_child_weight': 8, 'gamma': 2.351778173565513, 'reg_alpha': 1.7131037834076457, 'reg_lambda': 0.0008365554662243259, 'max_delta_step': 3}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639: 100%|█████████▉| 199/200 [03:20<00:01,  1.07s/it]

[I 2025-11-10 17:25:42,025] Trial 199 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.035229944550537184, 'n_estimators': 1232, 'subsample': 0.5120038687093944, 'colsample_bytree': 0.5923297295533559, 'min_child_weight': 9, 'gamma': 2.381336221385816, 'reg_alpha': 0.0005740046508625478, 'reg_lambda': 0.6272489661423545, 'max_delta_step': 5}. Best is trial 99 with value: 0.5446393762183236.

Best trial: 99. Best value: 0.544639: 100%|██████████| 200/200 [03:20<00:00,  1.00s/it]

[I 2025-11-10 17:25:42,282] Trial 198 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03511635918756581, 'n_estimators': 1390, 'subsample': 0.5065448118892961, 'colsample_bytree': 0.6153800227341283, 'min_child_weight': 8, 'gamma': 2.366789024704531, 'reg_alpha': 2.103759331132501e-07, 'reg_lambda': 2.07033906214492e-08, 'max_delta_step': 4}. Best is trial 99 with value: 0.5446393762183236.

[I 2025-11-10 17:25:43,014] A new study created in memory with name: 3_2_roc_auc
Best trial: 2. Best value: 0.384444:   0%|          | 1/200 [00:02<08:20,  2.51s/it]

[I 2025-11-10 17:25:45,518] Trial 2 finished with value: 0.3844444444444445 and parameters: {'max_depth': 5, 'learning_rate': 0.12743983339663612, 'n_estimators': 410, 'subsample': 0.7425178819174229, 'colsample_bytree': 0.6163788526398043, 'min_child_weight': 3, 'gamma': 3.0136405386476204, 'reg_alpha': 3.8337841900236296e-05, 'reg_lambda': 0.002317297431167289, 'max_delta_step': 3}. Best is trial 2 with value: 0.3844444444444445.

Best trial: 2. Best value: 0.384444:   1%|          | 2/200 [00:02<03:53,  1.18s/it]

[I 2025-11-10 17:25:45,761] Trial 0 finished with value: 0.32473684210526316 and parameters: {'max_depth': 10, 'learning_rate': 0.10580624203762115, 'n_estimators': 342, 'subsample': 0.8568113588830952, 'colsample_bytree': 0.6303580920044012, 'min_child_weight': 1, 'gamma': 1.3212822177524468, 'reg_alpha': 0.015430706193124264, 'reg_lambda': 0.01324222640071874, 'max_delta_step': 7}. Best is trial 2 with value: 0.3844444444444445.

Best trial: 3. Best value: 0.5:   2%|▏         | 3/200 [00:03<03:44,  1.14s/it]

[I 2025-11-10 17:25:46,860] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.023215343256948042, 'n_estimators': 797, 'subsample': 0.9113885910703656, 'colsample_bytree': 0.9034074178417439, 'min_child_weight': 6, 'gamma': 4.837127657488899, 'reg_alpha': 3.4571998380233728e-06, 'reg_lambda': 0.037312678799544544, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   2%|▏         | 4/200 [00:06<05:37,  1.72s/it]

[I 2025-11-10 17:25:49,479] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.010358311865947059, 'n_estimators': 535, 'subsample': 0.8013717247014025, 'colsample_bytree': 0.8314565141026166, 'min_child_weight': 6, 'gamma': 4.432444360665408, 'reg_alpha': 0.0006636266809257279, 'reg_lambda': 0.08650122128282804, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   2%|▎         | 5/200 [00:07<04:33,  1.40s/it]

[I 2025-11-10 17:25:50,304] Trial 1 finished with value: 0.42060428849902537 and parameters: {'max_depth': 10, 'learning_rate': 0.08614723675463103, 'n_estimators': 1325, 'subsample': 0.8799130659403449, 'colsample_bytree': 0.7707186058608666, 'min_child_weight': 2, 'gamma': 0.4236521073373184, 'reg_alpha': 3.1871044003233097e-06, 'reg_lambda': 0.038937214110874016, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   3%|▎         | 6/200 [00:08<04:29,  1.39s/it]

[I 2025-11-10 17:25:51,672] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.022249638676956673, 'n_estimators': 1433, 'subsample': 0.7450404518475542, 'colsample_bytree': 0.581104276568096, 'min_child_weight': 5, 'gamma': 4.982145929650085, 'reg_alpha': 5.266603585875359e-06, 'reg_lambda': 3.3787668313837095e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   4%|▎         | 7/200 [00:09<03:28,  1.08s/it]

[I 2025-11-10 17:25:52,123] Trial 5 finished with value: 0.4272319688109162 and parameters: {'max_depth': 8, 'learning_rate': 0.22824475244541995, 'n_estimators': 1430, 'subsample': 0.6603644633563186, 'colsample_bytree': 0.7921881148041903, 'min_child_weight': 4, 'gamma': 3.9796948152105225, 'reg_alpha': 2.8904304382874456e-08, 'reg_lambda': 1.755636636596071e-06, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   4%|▍         | 8/200 [00:10<03:54,  1.22s/it]

[I 2025-11-10 17:25:53,639] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04006572480181784, 'n_estimators': 1031, 'subsample': 0.9175310939261502, 'colsample_bytree': 0.5804710449564123, 'min_child_weight': 7, 'gamma': 4.544159008710848, 'reg_alpha': 3.6483960462708303, 'reg_lambda': 4.267848425181968e-08, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   4%|▍         | 9/200 [00:11<03:36,  1.13s/it]

[I 2025-11-10 17:25:54,579] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.035567737761064165, 'n_estimators': 453, 'subsample': 0.8177184704130815, 'colsample_bytree': 0.9002996836550077, 'min_child_weight': 5, 'gamma': 3.5994991551124, 'reg_alpha': 0.006490856388710851, 'reg_lambda': 0.0001501886718699648, 'max_delta_step': 0}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   5%|▌         | 10/200 [00:13<03:55,  1.24s/it]

[I 2025-11-10 17:25:56,068] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.16631549946231358, 'n_estimators': 525, 'subsample': 0.6357902597533074, 'colsample_bytree': 0.5929539417817458, 'min_child_weight': 5, 'gamma': 2.745774232919162, 'reg_alpha': 3.2988648980572372e-06, 'reg_lambda': 1.759803944957435, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   6%|▌         | 11/200 [00:13<03:18,  1.05s/it]

[I 2025-11-10 17:25:56,681] Trial 8 pruned.
[I 2025-11-10 17:25:56,722] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.011083770254779619, 'n_estimators': 1098, 'subsample': 0.5796687088399062, 'colsample_bytree': 0.9757536309249748, 'min_child_weight': 9, 'gamma': 4.124067566529014, 'reg_alpha': 1.037123453081972e-06, 'reg_lambda': 9.858221164940556e-05, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   6%|▋         | 13/200 [00:16<04:03,  1.30s/it]

[I 2025-11-10 17:25:59,848] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.14038097745021028, 'n_estimators': 1111, 'subsample': 0.7278647567574137, 'colsample_bytree': 0.9725699081715805, 'min_child_weight': 5, 'gamma': 0.8573433043095091, 'reg_alpha': 2.0070444787299002e-05, 'reg_lambda': 0.0005305278592969653, 'max_delta_step': 1}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   7%|▋         | 14/200 [00:17<03:18,  1.07s/it]

[I 2025-11-10 17:26:00,214] Trial 15 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02115637426424243, 'n_estimators': 768, 'subsample': 0.9921814976772654, 'colsample_bytree': 0.5001158077701477, 'min_child_weight': 8, 'gamma': 4.841718088090601, 'reg_alpha': 1.3888278914892419e-08, 'reg_lambda': 8.619040880098957e-07, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   8%|▊         | 15/200 [00:17<02:53,  1.06it/s]

[I 2025-11-10 17:26:00,809] Trial 13 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.014146512098053664, 'n_estimators': 946, 'subsample': 0.9977574477848961, 'colsample_bytree': 0.9923252688170967, 'min_child_weight': 10, 'gamma': 1.817760100043881, 'reg_alpha': 1.1522218246482279e-08, 'reg_lambda': 7.038809439997147, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   8%|▊         | 16/200 [00:18<02:17,  1.34it/s]

[I 2025-11-10 17:26:01,040] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.015163406928608876, 'n_estimators': 865, 'subsample': 0.508844217612272, 'colsample_bytree': 0.9598202358045996, 'min_child_weight': 10, 'gamma': 4.867702534132725, 'reg_alpha': 5.3204861462722443e-08, 'reg_lambda': 3.353249161077417e-06, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   8%|▊         | 17/200 [00:20<03:43,  1.22s/it]

[I 2025-11-10 17:26:03,477] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.022814905098879772, 'n_estimators': 771, 'subsample': 0.962286858610178, 'colsample_bytree': 0.6947709276466691, 'min_child_weight': 8, 'gamma': 4.960191041353411, 'reg_alpha': 1.325860634829208e-08, 'reg_lambda': 1.6019908129387927e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   9%|▉         | 18/200 [00:21<03:06,  1.03s/it]

[I 2025-11-10 17:26:04,022] Trial 17 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.019820665147621028, 'n_estimators': 765, 'subsample': 0.5012048328848854, 'colsample_bytree': 0.6882163727293532, 'min_child_weight': 7, 'gamma': 1.8810503688160374, 'reg_alpha': 5.33494203275062e-07, 'reg_lambda': 2.9421550473364664, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  10%|▉         | 19/200 [00:21<02:36,  1.15it/s]

[I 2025-11-10 17:26:04,494] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.026389924483870817, 'n_estimators': 706, 'subsample': 0.9161163433169117, 'colsample_bytree': 0.6994170438439831, 'min_child_weight': 7, 'gamma': 3.3297783103638485, 'reg_alpha': 4.117425301008767e-07, 'reg_lambda': 1.9601678993103857e-08, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  10%|█         | 20/200 [00:21<02:02,  1.47it/s]

[I 2025-11-10 17:26:04,712] Trial 18 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.023202002258950253, 'n_estimators': 755, 'subsample': 0.6787159701966303, 'colsample_bytree': 0.8576162749577259, 'min_child_weight': 7, 'gamma': 3.4445512684322264, 'reg_alpha': 1.8992021510002602e-07, 'reg_lambda': 5.26515366463046e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:26:04,798] Trial 21 pruned.

Best trial: 3. Best value: 0.5:  12%|█▏        | 23/200 [00:23<01:33,  1.90it/s]

[I 2025-11-10 17:26:05,941] Trial 23 pruned.
[I 2025-11-10 17:26:06,096] Trial 22 pruned.

Best trial: 3. Best value: 0.5:  12%|█▎        | 25/200 [00:23<01:02,  2.78it/s]

[I 2025-11-10 17:26:06,239] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.01217161475527028, 'n_estimators': 279, 'subsample': 0.7969124973719388, 'colsample_bytree': 0.8362232145765043, 'min_child_weight': 6, 'gamma': 4.262244170664833, 'reg_alpha': 0.0019888642226984716, 'reg_lambda': 0.27844415875533435, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:26:06,421] Trial 25 pruned.

Best trial: 3. Best value: 0.5:  13%|█▎        | 26/200 [00:23<01:03,  2.73it/s]

[I 2025-11-10 17:26:06,802] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.05372871438532446, 'n_estimators': 657, 'subsample': 0.6880502452779632, 'colsample_bytree': 0.870285455400837, 'min_child_weight': 7, 'gamma': 3.3380648175842746, 'reg_alpha': 4.687366948493608e-07, 'reg_lambda': 1.010723899205565e-07, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  14%|█▎        | 27/200 [00:24<01:25,  2.02it/s]

[I 2025-11-10 17:26:07,622] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.010353055406475528, 'n_estimators': 256, 'subsample': 0.827126406286104, 'colsample_bytree': 0.9218721146218558, 'min_child_weight': 6, 'gamma': 4.45875598227944, 'reg_alpha': 0.004184364325382636, 'reg_lambda': 0.0542947889658046, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  14%|█▍        | 28/200 [00:26<02:20,  1.22it/s]

[I 2025-11-10 17:26:09,232] Trial 27 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03374379173762205, 'n_estimators': 545, 'subsample': 0.7877142115769101, 'colsample_bytree': 0.9113194991598133, 'min_child_weight': 6, 'gamma': 4.493886175506594, 'reg_alpha': 9.706574012817564e-06, 'reg_lambda': 0.023588600681546775, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  14%|█▍        | 29/200 [00:26<01:52,  1.52it/s]

[I 2025-11-10 17:26:09,510] Trial 28 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.033716309379106454, 'n_estimators': 546, 'subsample': 0.8805398457408158, 'colsample_bytree': 0.9245961636933671, 'min_child_weight': 6, 'gamma': 4.390249491336542, 'reg_alpha': 1.2375939250021584e-05, 'reg_lambda': 0.0026758338689802006, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:26:09,526] Trial 29 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.033145917174367934, 'n_estimators': 548, 'subsample': 0.8658721392820611, 'colsample_bytree': 0.9126087722262486, 'min_child_weight': 6, 'gamma': 4.547574976187795, 'reg_alpha': 1.362421978994222e-05, 'reg_lambda': 0.004734175101990229, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  16%|█▌        | 31/200 [00:27<01:31,  1.86it/s]

[I 2025-11-10 17:26:10,293] Trial 31 pruned.

Best trial: 3. Best value: 0.5:  16%|█▌        | 32/200 [00:27<01:17,  2.16it/s]

[I 2025-11-10 17:26:10,514] Trial 32 pruned.
[I 2025-11-10 17:26:10,528] Trial 33 pruned.

Best trial: 3. Best value: 0.5:  17%|█▋        | 34/200 [00:27<00:57,  2.91it/s]

[I 2025-11-10 17:26:10,876] Trial 30 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03257868995263372, 'n_estimators': 601, 'subsample': 0.9108612981595522, 'colsample_bytree': 0.9181274670633273, 'min_child_weight': 6, 'gamma': 4.61300959793, 'reg_alpha': 1.0896190704552688e-05, 'reg_lambda': 0.005026302822387451, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  18%|█▊        | 35/200 [00:31<03:06,  1.13s/it]

[I 2025-11-10 17:26:14,672] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.039470695875933444, 'n_estimators': 972, 'subsample': 0.9237212013292629, 'colsample_bytree': 0.5516454576244043, 'min_child_weight': 8, 'gamma': 4.704766515954037, 'reg_alpha': 1.5108921437968235, 'reg_lambda': 1.8126776613071644e-05, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  18%|█▊        | 36/200 [00:32<02:41,  1.01it/s]

[I 2025-11-10 17:26:15,211] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04273237701639913, 'n_estimators': 1011, 'subsample': 0.91395920399714, 'colsample_bytree': 0.6509440296783939, 'min_child_weight': 8, 'gamma': 4.700395661202718, 'reg_alpha': 7.835285446637657, 'reg_lambda': 1.703758087928714e-07, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  18%|█▊        | 37/200 [00:32<02:21,  1.16it/s]

[I 2025-11-10 17:26:15,741] Trial 37 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04673574656106212, 'n_estimators': 1045, 'subsample': 0.9416098870491503, 'colsample_bytree': 0.6439290934460404, 'min_child_weight': 5, 'gamma': 4.792389997132788, 'reg_alpha': 9.538827449045675, 'reg_lambda': 3.213826715865734e-07, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  19%|█▉        | 38/200 [00:33<02:18,  1.17it/s]

[I 2025-11-10 17:26:16,555] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.044965085183504706, 'n_estimators': 1283, 'subsample': 0.9235664846058501, 'colsample_bytree': 0.6555966478687113, 'min_child_weight': 8, 'gamma': 4.717058719434232, 'reg_alpha': 4.746576590786707, 'reg_lambda': 3.4075507188877775e-07, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  20%|█▉        | 39/200 [00:34<02:04,  1.29it/s]

[I 2025-11-10 17:26:17,124] Trial 41 pruned.

Best trial: 3. Best value: 0.5:  20%|██        | 40/200 [00:35<02:29,  1.07it/s]

[I 2025-11-10 17:26:18,455] Trial 42 pruned.

Best trial: 3. Best value: 0.5:  20%|██        | 41/200 [00:37<03:29,  1.31s/it]

[I 2025-11-10 17:26:20,712] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04418522719882565, 'n_estimators': 1327, 'subsample': 0.7292121084708187, 'colsample_bytree': 0.64689751019707, 'min_child_weight': 5, 'gamma': 2.927485599353136, 'reg_alpha': 1.2718283026239348, 'reg_lambda': 9.098203437083055e-08, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  21%|██        | 42/200 [00:38<02:52,  1.09s/it]

[I 2025-11-10 17:26:21,252] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04583559949887366, 'n_estimators': 1274, 'subsample': 0.7376071555284951, 'colsample_bytree': 0.6114484824428232, 'min_child_weight': 5, 'gamma': 4.970184055558402, 'reg_alpha': 2.3139411550797646e-06, 'reg_lambda': 0.0007236902378736524, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  22%|██▏       | 43/200 [00:38<02:30,  1.04it/s]

[I 2025-11-10 17:26:21,903] Trial 40 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.0843672590609104, 'n_estimators': 1300, 'subsample': 0.7501661346494312, 'colsample_bytree': 0.7614904538195413, 'min_child_weight': 9, 'gamma': 3.006725078474002, 'reg_alpha': 1.9841599520644084e-06, 'reg_lambda': 4.918960604591505e-08, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  22%|██▏       | 44/200 [00:41<03:31,  1.36s/it]

[I 2025-11-10 17:26:24,201] Trial 43 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.29659222749660197, 'n_estimators': 1220, 'subsample': 0.7563918915948477, 'colsample_bytree': 0.829070355238086, 'min_child_weight': 9, 'gamma': 4.998204061075488, 'reg_alpha': 4.08403387755998e-05, 'reg_lambda': 0.06557830208504628, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  22%|██▎       | 45/200 [00:43<03:54,  1.51s/it]

[I 2025-11-10 17:26:26,090] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.013100932237594315, 'n_estimators': 1134, 'subsample': 0.5926954601152786, 'colsample_bytree': 0.9460832641606405, 'min_child_weight': 9, 'gamma': 4.2468261438163255, 'reg_alpha': 2.148631422049439e-06, 'reg_lambda': 5.958328303607019e-05, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  23%|██▎       | 46/200 [00:43<03:17,  1.28s/it]

[I 2025-11-10 17:26:26,821] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.013442771658194146, 'n_estimators': 1122, 'subsample': 0.5742544484796599, 'colsample_bytree': 0.9476193983689436, 'min_child_weight': 10, 'gamma': 4.14347712619606, 'reg_alpha': 4.285287331444254e-05, 'reg_lambda': 9.041380558477912e-05, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  24%|██▎       | 47/200 [00:44<02:59,  1.17s/it]

[I 2025-11-10 17:26:27,738] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.013296281950195546, 'n_estimators': 1120, 'subsample': 0.5750334691901713, 'colsample_bytree': 0.9938992151462447, 'min_child_weight': 9, 'gamma': 4.141919019199987, 'reg_alpha': 6.97126115112361e-08, 'reg_lambda': 0.06821150964445394, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  24%|██▍       | 48/200 [00:46<03:34,  1.41s/it]

[I 2025-11-10 17:26:29,711] Trial 47 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.013808111450281641, 'n_estimators': 1105, 'subsample': 0.5777077218722557, 'colsample_bytree': 0.9506990917674567, 'min_child_weight': 9, 'gamma': 0.06081406253275645, 'reg_alpha': 1.8354550245998515e-07, 'reg_lambda': 9.510020616719303e-05, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  24%|██▍       | 49/200 [00:47<03:09,  1.25s/it]

[I 2025-11-10 17:26:30,598] Trial 49 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.01000796333386235, 'n_estimators': 826, 'subsample': 0.9640655323384741, 'colsample_bytree': 0.9888268179877773, 'min_child_weight': 7, 'gamma': 0.03791367186982342, 'reg_alpha': 8.4920464109996e-08, 'reg_lambda': 0.00026377353999923524, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  25%|██▌       | 50/200 [00:48<02:35,  1.04s/it]

[I 2025-11-10 17:26:31,131] Trial 48 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.0100062057128466, 'n_estimators': 1059, 'subsample': 0.5823984140325563, 'colsample_bytree': 0.5782494826302413, 'min_child_weight': 7, 'gamma': 4.0229595217647836, 'reg_alpha': 7.692283986356901e-08, 'reg_lambda': 0.00012944865675956603, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  26%|██▌       | 51/200 [00:48<01:58,  1.26it/s]

[I 2025-11-10 17:26:31,357] Trial 50 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.010042941700235893, 'n_estimators': 839, 'subsample': 0.9668384937118139, 'colsample_bytree': 0.5822233307098004, 'min_child_weight': 7, 'gamma': 3.7364137812112137, 'reg_alpha': 1.6997997953049445e-07, 'reg_lambda': 0.009642521615932603, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  26%|██▌       | 52/200 [00:49<02:18,  1.07it/s]

[I 2025-11-10 17:26:32,612] Trial 52 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.01900671077593924, 'n_estimators': 440, 'subsample': 0.9712115873009549, 'colsample_bytree': 0.5754156141107267, 'min_child_weight': 7, 'gamma': 1.366132581040477, 'reg_alpha': 6.019816766660773e-07, 'reg_lambda': 0.011265581800263377, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  26%|██▋       | 53/200 [00:50<02:11,  1.12it/s]

[I 2025-11-10 17:26:33,410] Trial 53 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.019405898648697267, 'n_estimators': 457, 'subsample': 0.5366085182003508, 'colsample_bytree': 0.8886399005565588, 'min_child_weight': 7, 'gamma': 3.7847006445774123, 'reg_alpha': 4.723734061065768e-06, 'reg_lambda': 1.306164076123153, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  28%|██▊       | 55/200 [00:50<01:16,  1.89it/s]

[I 2025-11-10 17:26:33,603] Trial 54 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.026677153119097078, 'n_estimators': 446, 'subsample': 0.836761435501519, 'colsample_bytree': 0.8867540091301656, 'min_child_weight': 5, 'gamma': 1.2608000610509031, 'reg_alpha': 0.00790699925728976, 'reg_lambda': 1.0125371632172029, 'max_delta_step': 0}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:26:33,777] Trial 51 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.026998526440230458, 'n_estimators': 821, 'subsample': 0.9684842098350568, 'colsample_bytree': 0.8870391736213659, 'min_child_weight': 7, 'gamma': 1.472216873868439, 'reg_alpha': 4.660535318676399e-06, 'reg_lambda': 0.010910426089560258, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  28%|██▊       | 56/200 [00:51<01:24,  1.70it/s]

[I 2025-11-10 17:26:34,500] Trial 55 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.024021805774013034, 'n_estimators': 360, 'subsample': 0.8394233013200338, 'colsample_bytree': 0.8841862243062903, 'min_child_weight': 5, 'gamma': 3.545403209281166, 'reg_alpha': 0.0007483809452520743, 'reg_lambda': 1.213523680514339e-06, 'max_delta_step': 0}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  28%|██▊       | 57/200 [00:52<01:29,  1.60it/s]

[I 2025-11-10 17:26:35,216] Trial 56 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.025830931018162834, 'n_estimators': 349, 'subsample': 0.8328005823413568, 'colsample_bytree': 0.8845428553058535, 'min_child_weight': 5, 'gamma': 4.385159330090507, 'reg_alpha': 0.008459650084029057, 'reg_lambda': 2.073748919054412e-06, 'max_delta_step': 0}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  29%|██▉       | 58/200 [00:52<01:31,  1.54it/s]

[I 2025-11-10 17:26:35,895] Trial 58 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.02286733925517945, 'n_estimators': 385, 'subsample': 0.7103747259591964, 'colsample_bytree': 0.8376473611984707, 'min_child_weight': 6, 'gamma': 2.4805487370134833, 'reg_alpha': 0.0005479113394470456, 'reg_lambda': 1.598677814577051e-06, 'max_delta_step': 1}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  30%|██▉       | 59/200 [00:54<01:58,  1.19it/s]

[I 2025-11-10 17:26:37,205] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.02417320547583714, 'n_estimators': 703, 'subsample': 0.8140175328599926, 'colsample_bytree': 0.8461086321951925, 'min_child_weight': 6, 'gamma': 4.4060636708557395, 'reg_alpha': 0.0007939269329535939, 'reg_lambda': 3.774067986389625e-05, 'max_delta_step': 1}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  30%|███       | 60/200 [00:54<01:33,  1.50it/s]

[I 2025-11-10 17:26:37,473] Trial 62 pruned.

Best trial: 3. Best value: 0.5:  30%|███       | 61/200 [00:54<01:21,  1.71it/s]

[I 2025-11-10 17:26:37,857] Trial 59 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03802878978484621, 'n_estimators': 668, 'subsample': 0.8064436239552105, 'colsample_bytree': 0.8477141191344421, 'min_child_weight': 6, 'gamma': 4.3579539520560555, 'reg_alpha': 9.050659132985326e-05, 'reg_lambda': 3.7951070272112734e-06, 'max_delta_step': 0}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  31%|███       | 62/200 [00:55<01:27,  1.58it/s]

[I 2025-11-10 17:26:38,599] Trial 60 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.029983677198960508, 'n_estimators': 679, 'subsample': 0.8158257318814803, 'colsample_bytree': 0.8475136594460104, 'min_child_weight': 6, 'gamma': 3.1981813525019542, 'reg_alpha': 0.0003831505050636325, 'reg_lambda': 3.064445080942608e-05, 'max_delta_step': 1}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  32%|███▏      | 63/200 [00:56<01:36,  1.43it/s]

[I 2025-11-10 17:26:39,471] Trial 61 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03852367121007166, 'n_estimators': 698, 'subsample': 0.8002984826686553, 'colsample_bytree': 0.9764484453770921, 'min_child_weight': 6, 'gamma': 3.3019350225120516, 'reg_alpha': 0.00012210011579940564, 'reg_lambda': 3.581734098288534e-05, 'max_delta_step': 1}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  32%|███▏      | 64/200 [00:57<01:47,  1.26it/s]

[I 2025-11-10 17:26:40,470] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.12571775666236137, 'n_estimators': 597, 'subsample': 0.6293439506949745, 'colsample_bytree': 0.5202885842460476, 'min_child_weight': 5, 'gamma': 2.1972995231328607, 'reg_alpha': 2.9688892140673766e-05, 'reg_lambda': 6.2949499434929015, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  32%|███▎      | 65/200 [00:57<01:36,  1.39it/s]

[I 2025-11-10 17:26:41,006] Trial 67 pruned.

Best trial: 3. Best value: 0.5:  33%|███▎      | 66/200 [00:58<01:45,  1.27it/s]

[I 2025-11-10 17:26:41,969] Trial 66 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.14687770034419015, 'n_estimators': 497, 'subsample': 0.6159707012821412, 'colsample_bytree': 0.5225196872445452, 'min_child_weight': 5, 'gamma': 4.829315220254056, 'reg_alpha': 1.0099180531195701e-06, 'reg_lambda': 5.572679568855677, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  34%|███▎      | 67/200 [01:00<02:17,  1.03s/it]

[I 2025-11-10 17:26:43,573] Trial 68 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.15956591688804617, 'n_estimators': 491, 'subsample': 0.6056615571747199, 'colsample_bytree': 0.6259390702258985, 'min_child_weight': 10, 'gamma': 4.5615922231380885, 'reg_alpha': 2.6221290970471926e-08, 'reg_lambda': 0.11960536246107709, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  34%|███▍      | 68/200 [01:01<02:04,  1.06it/s]

[I 2025-11-10 17:26:44,304] Trial 63 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03897330863358808, 'n_estimators': 1386, 'subsample': 0.8927244829400964, 'colsample_bytree': 0.8060051496110562, 'min_child_weight': 6, 'gamma': 4.52431032753494, 'reg_alpha': 7.336721552244042e-05, 'reg_lambda': 0.00026450043306822557, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  34%|███▍      | 69/200 [01:02<01:54,  1.15it/s]

[I 2025-11-10 17:26:45,021] Trial 70 pruned.

Best trial: 3. Best value: 0.5:  35%|███▌      | 70/200 [01:02<01:32,  1.40it/s]

[I 2025-11-10 17:26:45,350] Trial 71 pruned.

Best trial: 3. Best value: 0.5:  36%|███▌      | 71/200 [01:02<01:23,  1.54it/s]

[I 2025-11-10 17:26:45,848] Trial 65 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.10659319567628456, 'n_estimators': 1452, 'subsample': 0.6228501956991352, 'colsample_bytree': 0.9724931957972084, 'min_child_weight': 5, 'gamma': 4.842007675181833, 'reg_alpha': 1.001631851873067e-06, 'reg_lambda': 5.926911200614982, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  36%|███▌      | 72/200 [01:03<01:06,  1.91it/s]

[I 2025-11-10 17:26:46,064] Trial 72 pruned.

Best trial: 3. Best value: 0.5:  36%|███▋      | 73/200 [01:03<01:18,  1.62it/s]

[I 2025-11-10 17:26:46,908] Trial 74 pruned.

Best trial: 3. Best value: 0.5:  38%|███▊      | 75/200 [01:05<01:29,  1.40it/s]

[I 2025-11-10 17:26:48,632] Trial 73 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.06422832857300698, 'n_estimators': 610, 'subsample': 0.5549395662346231, 'colsample_bytree': 0.723390535503279, 'min_child_weight': 4, 'gamma': 4.642477668071094, 'reg_alpha': 5.155908497654271e-06, 'reg_lambda': 0.6787832597083365, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:26:48,801] Trial 69 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.011430377371093309, 'n_estimators': 1372, 'subsample': 0.5527781648195488, 'colsample_bytree': 0.5985391604270711, 'min_child_weight': 10, 'gamma': 4.560356054646916, 'reg_alpha': 0.24587255584135587, 'reg_lambda': 0.0016047368184834692, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  38%|███▊      | 76/200 [01:09<03:15,  1.58s/it]

[I 2025-11-10 17:26:52,398] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.2279223411999485, 'n_estimators': 1204, 'subsample': 0.7149687120445257, 'colsample_bytree': 0.9638727659110796, 'min_child_weight': 5, 'gamma': 0.772230321364173, 'reg_alpha': 1.965742814452295e-05, 'reg_lambda': 0.9032978471226786, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  38%|███▊      | 77/200 [01:10<02:57,  1.44s/it]

[I 2025-11-10 17:26:53,526] Trial 76 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.011755488886104008, 'n_estimators': 1219, 'subsample': 0.6931129318599594, 'colsample_bytree': 0.9017804303094986, 'min_child_weight': 5, 'gamma': 1.9863315252000706, 'reg_alpha': 2.083638185114623e-05, 'reg_lambda': 0.0005120300274838532, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  39%|███▉      | 78/200 [01:11<02:54,  1.43s/it]

[I 2025-11-10 17:26:54,921] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.011555395365506534, 'n_estimators': 1178, 'subsample': 0.6856677965355295, 'colsample_bytree': 0.932491536973531, 'min_child_weight': 5, 'gamma': 1.9207991853703215, 'reg_alpha': 1.5770580106371607e-05, 'reg_lambda': 2.4513530640824492, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  40%|███▉      | 79/200 [01:12<02:08,  1.06s/it]

[I 2025-11-10 17:26:55,132] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.21948095734610368, 'n_estimators': 1209, 'subsample': 0.6900605376039699, 'colsample_bytree': 0.958374150840543, 'min_child_weight': 5, 'gamma': 4.2073802766408015, 'reg_alpha': 1.7285856469081086e-05, 'reg_lambda': 2.051138471135114, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  40%|████      | 80/200 [01:13<02:22,  1.19s/it]

[I 2025-11-10 17:26:56,610] Trial 81 pruned.

Best trial: 3. Best value: 0.5:  40%|████      | 81/200 [01:15<02:39,  1.34s/it]

[I 2025-11-10 17:26:58,295] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.011943967460457042, 'n_estimators': 1177, 'subsample': 0.7849186445146782, 'colsample_bytree': 0.5515715409827272, 'min_child_weight': 6, 'gamma': 3.9973745496923954, 'reg_alpha': 2.2190676504828955e-05, 'reg_lambda': 5.031808622895231e-07, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  41%|████      | 82/200 [01:15<02:07,  1.08s/it]

[I 2025-11-10 17:26:58,764] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.051263284965186985, 'n_estimators': 312, 'subsample': 0.7654105916523732, 'colsample_bytree': 0.9997869431910161, 'min_child_weight': 8, 'gamma': 4.736650041480675, 'reg_alpha': 0.04202051307047168, 'reg_lambda': 8.910613238207196e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  42%|████▏     | 83/200 [01:17<02:15,  1.16s/it]

[I 2025-11-10 17:27:00,129] Trial 80 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.02067430581122924, 'n_estimators': 1175, 'subsample': 0.9452048206617902, 'colsample_bytree': 0.9356250957373389, 'min_child_weight': 6, 'gamma': 4.005217638320498, 'reg_alpha': 0.0028113752004098676, 'reg_lambda': 1.0372285248230905e-08, 'max_delta_step': 1}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:27:00,167] Trial 82 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.021263203300930036, 'n_estimators': 1009, 'subsample': 0.7673989922842954, 'colsample_bytree': 0.5455504069285477, 'min_child_weight': 8, 'gamma': 3.9658108946119848, 'reg_alpha': 0.0020570527293976887, 'reg_lambda': 0.21253433474651565, 'max_delta_step': 1}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  43%|████▎     | 86/200 [01:20<02:09,  1.14s/it]

[I 2025-11-10 17:27:03,748] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.01688130405614239, 'n_estimators': 1005, 'subsample': 0.9867024772278279, 'colsample_bytree': 0.9027553004130126, 'min_child_weight': 8, 'gamma': 2.1963175144379576, 'reg_alpha': 2.9649843379469104e-07, 'reg_lambda': 8.864409463173508e-06, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:27:03,904] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.015618808582333188, 'n_estimators': 1011, 'subsample': 0.9942675725341881, 'colsample_bytree': 0.9404434835650255, 'min_child_weight': 10, 'gamma': 0.6127762696773927, 'reg_alpha': 8.379542145935354e-06, 'reg_lambda': 0.0052182927381875036, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  44%|████▎     | 87/200 [01:21<01:48,  1.05it/s]

[I 2025-11-10 17:27:04,354] Trial 87 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.017805224609656358, 'n_estimators': 794, 'subsample': 0.9820174210600882, 'colsample_bytree': 0.9823981712643567, 'min_child_weight': 10, 'gamma': 1.690203690855622, 'reg_alpha': 3.446772434581862e-07, 'reg_lambda': 0.005141428229447039, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  44%|████▍     | 88/200 [01:24<02:39,  1.43s/it]

[I 2025-11-10 17:27:07,033] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.01763442800810412, 'n_estimators': 1071, 'subsample': 0.9799203877505642, 'colsample_bytree': 0.9060883507095103, 'min_child_weight': 10, 'gamma': 1.6353617600674464, 'reg_alpha': 2.92766116752086e-06, 'reg_lambda': 0.005214674386722586, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  45%|████▌     | 90/200 [01:27<02:48,  1.53s/it]

[I 2025-11-10 17:27:10,774] Trial 88 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.014980416822315578, 'n_estimators': 1087, 'subsample': 0.993892102035951, 'colsample_bytree': 0.9810825799298218, 'min_child_weight': 10, 'gamma': 0.5471730753281623, 'reg_alpha': 5.628867471402042e-05, 'reg_lambda': 9.037877294630597, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:27:10,944] Trial 89 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.03495810139459809, 'n_estimators': 1079, 'subsample': 0.8971255382097838, 'colsample_bytree': 0.9895310485003714, 'min_child_weight': 9, 'gamma': 0.20640985279043644, 'reg_alpha': 1.4322716850429012e-08, 'reg_lambda': 2.3741543283517384e-08, 'max_delta_step': 0}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  46%|████▌     | 91/200 [01:28<02:09,  1.19s/it]

[I 2025-11-10 17:27:11,296] Trial 90 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.28325719615445755, 'n_estimators': 1091, 'subsample': 0.9397496722017993, 'colsample_bytree': 0.8664703026660147, 'min_child_weight': 9, 'gamma': 2.450618034770184, 'reg_alpha': 1.3984429522791388e-08, 'reg_lambda': 0.11094874974063154, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  46%|████▌     | 92/200 [01:28<01:49,  1.01s/it]

[I 2025-11-10 17:27:11,877] Trial 91 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.27912466637062117, 'n_estimators': 922, 'subsample': 0.9499782723248343, 'colsample_bytree': 0.7781045597014418, 'min_child_weight': 9, 'gamma': 1.0349186524534832, 'reg_alpha': 1.3118535456661577e-08, 'reg_lambda': 9.812962935163492, 'max_delta_step': 0}. Best is trial 3 with value: 0.5.

[I 2025-11-10 17:27:16,308] Trial 93 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.010841450209674228, 'n_estimators': 871, 'subsample': 0.95265862839295, 'colsample_bytree': 0.7508178534561226, 'min_child_weight': 6, 'gamma': 4.940532559038029, 'reg_alpha': 1.3699417609383919e-06, 'reg_lambda': 0.39543514647339273, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  47%|████▋     | 94/200 [01:33<02:36,  1.48s/it]

[I 2025-11-10 17:27:16,478] Trial 92 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.035016031081698575, 'n_estimators': 915, 'subsample': 0.6420944906341076, 'colsample_bytree': 0.8683221186856668, 'min_child_weight': 9, 'gamma': 2.3728733540776346, 'reg_alpha': 2.7758626830687545e-08, 'reg_lambda': 0.00012684733231472123, 'max_delta_step': 0}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  48%|████▊     | 95/200 [01:34<02:05,  1.19s/it]

[I 2025-11-10 17:27:17,018] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.01278380834561137, 'n_estimators': 888, 'subsample': 0.5104021941137323, 'colsample_bytree': 0.9599759393659612, 'min_child_weight': 9, 'gamma': 4.957330610142286, 'reg_alpha': 4.542019037849551e-08, 'reg_lambda': 0.00045087361480605743, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  48%|████▊     | 96/200 [01:34<01:40,  1.03it/s]

[I 2025-11-10 17:27:17,460] Trial 95 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.012465579347505874, 'n_estimators': 848, 'subsample': 0.6456942105907353, 'colsample_bytree': 0.958871726552127, 'min_child_weight': 6, 'gamma': 4.975266478231456, 'reg_alpha': 2.477373663990639e-08, 'reg_lambda': 0.00015722626741372647, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  48%|████▊     | 97/200 [01:37<02:32,  1.48s/it]

[I 2025-11-10 17:27:20,136] Trial 98 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.014022185388173408, 'n_estimators': 574, 'subsample': 0.7493015217276884, 'colsample_bytree': 0.9214695174473484, 'min_child_weight': 10, 'gamma': 4.315770125376438, 'reg_alpha': 1.4213776780963406e-07, 'reg_lambda': 1.6927966718363081e-07, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  49%|████▉     | 98/200 [01:37<01:54,  1.13s/it]

[I 2025-11-10 17:27:20,432] Trial 99 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.014097469956508015, 'n_estimators': 570, 'subsample': 0.8756804184127689, 'colsample_bytree': 0.9199250812620927, 'min_child_weight': 10, 'gamma': 4.335412039124797, 'reg_alpha': 0.6564520778797097, 'reg_lambda': 2.0421261378665825e-05, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  50%|████▉     | 99/200 [01:38<01:36,  1.04it/s]

[I 2025-11-10 17:27:21,005] Trial 97 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.030552530336125427, 'n_estimators': 866, 'subsample': 0.5022950391630813, 'colsample_bytree': 0.9591516874107987, 'min_child_weight': 10, 'gamma': 4.886897817165583, 'reg_alpha': 3.8084392375240524e-08, 'reg_lambda': 2.9896939419480652e-06, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:27:21,024] Trial 96 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.013472126260319395, 'n_estimators': 870, 'subsample': 0.5176272031591979, 'colsample_bytree': 0.9599825028814153, 'min_child_weight': 10, 'gamma': 2.7581532839236176, 'reg_alpha': 3.77032836775441e-08, 'reg_lambda': 0.00014358885065033567, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  50%|█████     | 101/200 [01:38<01:09,  1.43it/s]

[I 2025-11-10 17:27:21,796] Trial 101 pruned.

Best trial: 3. Best value: 0.5:  51%|█████     | 102/200 [01:42<02:24,  1.47s/it]

[I 2025-11-10 17:27:25,609] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.010721511790140942, 'n_estimators': 734, 'subsample': 0.8573250629044313, 'colsample_bytree': 0.6668417564265702, 'min_child_weight': 7, 'gamma': 4.733824766225769, 'reg_alpha': 3.323395579598561e-06, 'reg_lambda': 3.785984976148259, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  52%|█████▏    | 103/200 [01:43<02:00,  1.24s/it]

[I 2025-11-10 17:27:26,194] Trial 104 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1634827751991565, 'n_estimators': 743, 'subsample': 0.8534804478487774, 'colsample_bytree': 0.5285056980925006, 'min_child_weight': 7, 'gamma': 4.736292021079388, 'reg_alpha': 4.484192043118875, 'reg_lambda': 1.266051643156041e-06, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  52%|█████▏    | 104/200 [01:43<01:46,  1.11s/it]

[I 2025-11-10 17:27:26,955] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.17090545744894517, 'n_estimators': 982, 'subsample': 0.5234629430783801, 'colsample_bytree': 0.9693056656352718, 'min_child_weight': 7, 'gamma': 4.455559804068815, 'reg_alpha': 2.763135883209956, 'reg_lambda': 5.927292823007582e-05, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  52%|█████▎    | 105/200 [01:44<01:25,  1.12it/s]

[I 2025-11-10 17:27:27,302] Trial 100 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1724007467838913, 'n_estimators': 1256, 'subsample': 0.8517646256284409, 'colsample_bytree': 0.6679442646096725, 'min_child_weight': 7, 'gamma': 4.43670740250829, 'reg_alpha': 1.307226235262348, 'reg_lambda': 3.6251896961468946, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  53%|█████▎    | 106/200 [01:46<02:04,  1.32s/it]

[I 2025-11-10 17:27:29,688] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.021653444853757815, 'n_estimators': 782, 'subsample': 0.589031069333796, 'colsample_bytree': 0.5007653291264257, 'min_child_weight': 8, 'gamma': 4.426435647989128, 'reg_alpha': 1.0842294413760715e-08, 'reg_lambda': 8.322071204960854e-07, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  54%|█████▍    | 108/200 [01:47<01:21,  1.13it/s]

[I 2025-11-10 17:27:30,511] Trial 107 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.022568981739016107, 'n_estimators': 798, 'subsample': 0.9319126508370236, 'colsample_bytree': 0.5029238976425223, 'min_child_weight': 8, 'gamma': 4.505622466874604, 'reg_alpha': 5.309858362985477e-07, 'reg_lambda': 6.755994544772189e-07, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:27:30,680] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.18623990714480404, 'n_estimators': 1148, 'subsample': 0.8490689410170816, 'colsample_bytree': 0.5087812975332573, 'min_child_weight': 8, 'gamma': 4.773752268270975, 'reg_alpha': 4.287050857381179, 'reg_lambda': 7.754334982802251e-07, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  54%|█████▍    | 108/200 [01:47<01:21,  1.13it/s]

[I 2025-11-10 17:27:30,702] Trial 108 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.0252063461061679, 'n_estimators': 780, 'subsample': 0.702801545256631, 'colsample_bytree': 0.6187731358710965, 'min_child_weight': 5, 'gamma': 4.624517191196351, 'reg_alpha': 0.0002419293512410393, 'reg_lambda': 7.129262952423996e-07, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  55%|█████▌    | 110/200 [01:49<01:21,  1.11it/s]

[I 2025-11-10 17:27:32,523] Trial 111 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.018356646526066677, 'n_estimators': 414, 'subsample': 0.5622490729715353, 'colsample_bytree': 0.6155424626493292, 'min_child_weight': 5, 'gamma': 3.663333238315558, 'reg_alpha': 6.183380963047261e-08, 'reg_lambda': 1.570669133481838, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  56%|█████▌    | 112/200 [01:50<01:00,  1.47it/s]

[I 2025-11-10 17:27:33,308] Trial 110 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.12541521033884606, 'n_estimators': 651, 'subsample': 0.6650624417418088, 'colsample_bytree': 0.6331862566303594, 'min_child_weight': 5, 'gamma': 4.6508994985098235, 'reg_alpha': 0.006580598004633165, 'reg_lambda': 1.8469608615104712e-07, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:27:33,458] Trial 112 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.01812995797651284, 'n_estimators': 630, 'subsample': 0.7257663157890214, 'colsample_bytree': 0.5646424797127433, 'min_child_weight': 6, 'gamma': 1.114803119770761, 'reg_alpha': 1.8966146687823757e-08, 'reg_lambda': 2.3563036293311112e-07, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  56%|█████▋    | 113/200 [01:51<01:11,  1.22it/s]

[I 2025-11-10 17:27:34,658] Trial 109 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.024408715940618986, 'n_estimators': 1151, 'subsample': 0.727429803146718, 'colsample_bytree': 0.620463268434313, 'min_child_weight': 5, 'gamma': 4.588760018466425, 'reg_alpha': 1.3696666612866826e-06, 'reg_lambda': 8.093062535480886e-07, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  57%|█████▋    | 114/200 [01:52<01:03,  1.36it/s]

[I 2025-11-10 17:27:35,176] Trial 113 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.11710481400667413, 'n_estimators': 527, 'subsample': 0.670730773431213, 'colsample_bytree': 0.9425762518077297, 'min_child_weight': 6, 'gamma': 2.9396149564425436, 'reg_alpha': 1.1982828018288144e-05, 'reg_lambda': 2.7812352007697297e-08, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  57%|█████▊    | 115/200 [01:52<00:57,  1.47it/s]

[I 2025-11-10 17:27:35,706] Trial 114 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.028295730746768867, 'n_estimators': 530, 'subsample': 0.9998028979643812, 'colsample_bytree': 0.574579079108357, 'min_child_weight': 8, 'gamma': 4.87127065449328, 'reg_alpha': 2.3227430684541156e-08, 'reg_lambda': 2.1662580774363895e-06, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  58%|█████▊    | 116/200 [01:54<01:14,  1.12it/s]

[I 2025-11-10 17:27:37,117] Trial 115 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.14392770547326475, 'n_estimators': 814, 'subsample': 0.9030997407250766, 'colsample_bytree': 0.6945471662741894, 'min_child_weight': 9, 'gamma': 4.823525741186659, 'reg_alpha': 1.5549285458614065e-06, 'reg_lambda': 2.6469254525771094e-06, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  58%|█████▊    | 117/200 [01:54<01:09,  1.19it/s]

[I 2025-11-10 17:27:37,836] Trial 118 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.14351891110758955, 'n_estimators': 469, 'subsample': 0.9758010208860686, 'colsample_bytree': 0.5936620339692436, 'min_child_weight': 9, 'gamma': 4.865973426651149, 'reg_alpha': 0.016552418740016887, 'reg_lambda': 4.993786902483895e-08, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  59%|█████▉    | 118/200 [01:55<01:11,  1.14it/s]

[I 2025-11-10 17:27:38,792] Trial 120 pruned.
[I 2025-11-10 17:27:38,820] Trial 116 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.027675864008087286, 'n_estimators': 952, 'subsample': 0.9580030732320316, 'colsample_bytree': 0.5877649446371547, 'min_child_weight': 9, 'gamma': 4.85728362269919, 'reg_alpha': 9.973058562833339e-06, 'reg_lambda': 2.531388978886715e-06, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  60%|██████    | 120/200 [01:56<00:45,  1.75it/s]

[I 2025-11-10 17:27:39,214] Trial 117 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.015990133106285897, 'n_estimators': 815, 'subsample': 0.9589554268156056, 'colsample_bytree': 0.9987374544538847, 'min_child_weight': 9, 'gamma': 4.857835862967995, 'reg_alpha': 2.397439391965912e-07, 'reg_lambda': 2.8970272196606176e-06, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  60%|██████    | 121/200 [01:58<01:11,  1.11it/s]

[I 2025-11-10 17:27:41,115] Trial 119 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.016045074724026644, 'n_estimators': 946, 'subsample': 0.9634866934014976, 'colsample_bytree': 0.5319049651816464, 'min_child_weight': 7, 'gamma': 4.142141049411215, 'reg_alpha': 2.2150568250746864e-07, 'reg_lambda': 8.495128088500436e-08, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  61%|██████    | 122/200 [01:58<01:08,  1.14it/s]

[I 2025-11-10 17:27:41,929] Trial 122 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.019814673676871536, 'n_estimators': 708, 'subsample': 0.9254022103641366, 'colsample_bytree': 0.8009531282793811, 'min_child_weight': 7, 'gamma': 3.415209203444333, 'reg_alpha': 2.524803878135256e-07, 'reg_lambda': 5.495376678931377e-06, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  62%|██████▏   | 123/200 [01:59<01:03,  1.21it/s]

[I 2025-11-10 17:27:42,613] Trial 121 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.019931525303740562, 'n_estimators': 830, 'subsample': 0.7937371922206024, 'colsample_bytree': 0.9997806341979706, 'min_child_weight': 7, 'gamma': 4.99175292305184, 'reg_alpha': 0.0011458188191665697, 'reg_lambda': 4.688550699035033e-06, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  62%|██████▏   | 124/200 [02:00<01:09,  1.10it/s]

[I 2025-11-10 17:27:43,754] Trial 123 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.042086652490494474, 'n_estimators': 1029, 'subsample': 0.9354657450141789, 'colsample_bytree': 0.7990040003806022, 'min_child_weight': 7, 'gamma': 4.09785223255097, 'reg_alpha': 1.0383112329458594e-08, 'reg_lambda': 5.651507859057661e-06, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  62%|██████▎   | 125/200 [02:01<01:01,  1.21it/s]

[I 2025-11-10 17:27:44,359] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.019660929983652854, 'n_estimators': 718, 'subsample': 0.5377399532918096, 'colsample_bytree': 0.7946422955504859, 'min_child_weight': 8, 'gamma': 4.993945590472629, 'reg_alpha': 2.824644588313824e-06, 'reg_lambda': 5.370779317849805e-06, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  63%|██████▎   | 126/200 [02:02<01:17,  1.04s/it]

[I 2025-11-10 17:27:45,930] Trial 126 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.021772039318991538, 'n_estimators': 761, 'subsample': 0.5296892890163889, 'colsample_bytree': 0.7383850196987957, 'min_child_weight': 6, 'gamma': 1.6640717333822437, 'reg_alpha': 1.0279737378379927e-07, 'reg_lambda': 0.04138485909292854, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  64%|██████▎   | 127/200 [02:03<01:02,  1.18it/s]

[I 2025-11-10 17:27:46,320] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.0486926074888363, 'n_estimators': 985, 'subsample': 0.7459493461639224, 'colsample_bytree': 0.7326686548271497, 'min_child_weight': 6, 'gamma': 1.8555809848649294, 'reg_alpha': 7.824808862272598e-07, 'reg_lambda': 0.4980121745999561, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  64%|██████▍   | 128/200 [02:04<01:00,  1.20it/s]

[I 2025-11-10 17:27:47,119] Trial 127 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.02210394990883368, 'n_estimators': 761, 'subsample': 0.529075751460285, 'colsample_bytree': 0.6950518395424288, 'min_child_weight': 6, 'gamma': 2.1201162836880423, 'reg_alpha': 2.757836210433939e-06, 'reg_lambda': 0.045051736413214055, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  64%|██████▍   | 129/200 [02:05<01:04,  1.09it/s]

[I 2025-11-10 17:27:48,226] Trial 128 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.058287678720335655, 'n_estimators': 902, 'subsample': 0.7412112912261561, 'colsample_bytree': 0.7261233624918857, 'min_child_weight': 6, 'gamma': 2.0469246292834207, 'reg_alpha': 0.08353222851314682, 'reg_lambda': 3.4818664735674063, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  65%|██████▌   | 130/200 [02:05<00:54,  1.29it/s]

[I 2025-11-10 17:27:48,679] Trial 132 pruned.

Best trial: 3. Best value: 0.5:  66%|██████▌   | 131/200 [02:06<00:49,  1.39it/s]

[I 2025-11-10 17:27:49,251] Trial 131 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.08536137899365194, 'n_estimators': 481, 'subsample': 0.503208648305491, 'colsample_bytree': 0.604094609807797, 'min_child_weight': 4, 'gamma': 4.6911050071893365, 'reg_alpha': 0.07893364539406866, 'reg_lambda': 2.913690220100155, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  66%|██████▌   | 132/200 [02:06<00:46,  1.47it/s]

[I 2025-11-10 17:27:49,844] Trial 129 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.04796499107630946, 'n_estimators': 907, 'subsample': 0.608114031261529, 'colsample_bytree': 0.7104090374556323, 'min_child_weight': 5, 'gamma': 1.4851867045728553, 'reg_alpha': 5.798686958006668e-08, 'reg_lambda': 0.016630070395515163, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  66%|██████▋   | 133/200 [02:07<00:51,  1.30it/s]

[I 2025-11-10 17:27:50,823] Trial 133 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.023662511385593644, 'n_estimators': 438, 'subsample': 0.8206459771464107, 'colsample_bytree': 0.9865298001214946, 'min_child_weight': 5, 'gamma': 1.3745876794510161, 'reg_alpha': 4.075591248559953e-07, 'reg_lambda': 0.001781816484638784, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  68%|██████▊   | 135/200 [02:09<00:46,  1.40it/s]

[I 2025-11-10 17:27:52,174] Trial 130 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.06381354334289246, 'n_estimators': 1335, 'subsample': 0.6055955935229242, 'colsample_bytree': 0.8191320853175966, 'min_child_weight': 5, 'gamma': 1.3839543404675072, 'reg_alpha': 0.09112080425060944, 'reg_lambda': 0.01592545428684685, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:27:52,348] Trial 134 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.022908455522623963, 'n_estimators': 692, 'subsample': 0.6803090555874705, 'colsample_bytree': 0.8507439908738967, 'min_child_weight': 8, 'gamma': 1.4176669039686849, 'reg_alpha': 1.7869117106210596e-08, 'reg_lambda': 2.037857149765136e-05, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  68%|██████▊   | 136/200 [02:09<00:41,  1.54it/s]

[I 2025-11-10 17:27:52,859] Trial 135 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.0234811454342703, 'n_estimators': 680, 'subsample': 0.6772692198594256, 'colsample_bytree': 0.8233253330203909, 'min_child_weight': 8, 'gamma': 3.881410033263831, 'reg_alpha': 8.722057854315597e-07, 'reg_lambda': 1.6823162194543035e-05, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  68%|██████▊   | 137/200 [02:10<00:49,  1.29it/s]

[I 2025-11-10 17:27:53,929] Trial 136 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.032423352750656415, 'n_estimators': 685, 'subsample': 0.9908453694792515, 'colsample_bytree': 0.7622473157678303, 'min_child_weight': 8, 'gamma': 2.3217592928669895, 'reg_alpha': 9.331187909045342e-07, 'reg_lambda': 1.4614388656608487e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  69%|██████▉   | 138/200 [02:12<01:00,  1.02it/s]

[I 2025-11-10 17:27:55,380] Trial 137 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03268812745392379, 'n_estimators': 685, 'subsample': 0.9893796048544055, 'colsample_bytree': 0.8610940933810995, 'min_child_weight': 8, 'gamma': 3.077966526990765, 'reg_alpha': 1.8103912408071843e-08, 'reg_lambda': 5.792632038220639, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  70%|██████▉   | 139/200 [02:13<00:57,  1.06it/s]

[I 2025-11-10 17:27:56,220] Trial 138 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.02595347548921752, 'n_estimators': 842, 'subsample': 0.7567554725237849, 'colsample_bytree': 0.892829731740732, 'min_child_weight': 7, 'gamma': 3.7816117286919964, 'reg_alpha': 4.230940794942198e-06, 'reg_lambda': 1.3233512927837587, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  70%|███████   | 140/200 [02:13<00:47,  1.25it/s]

[I 2025-11-10 17:27:56,702] Trial 139 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.026706623259177657, 'n_estimators': 845, 'subsample': 0.7005525599420223, 'colsample_bytree': 0.8597352998478897, 'min_child_weight': 7, 'gamma': 3.0903077119160125, 'reg_alpha': 6.563658603382382e-06, 'reg_lambda': 1.3653148769075721e-06, 'max_delta_step': 1}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  70%|███████   | 141/200 [02:14<00:51,  1.14it/s]

[I 2025-11-10 17:27:57,758] Trial 140 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.012809605013171275, 'n_estimators': 850, 'subsample': 0.7749008343981657, 'colsample_bytree': 0.8550696352138202, 'min_child_weight': 7, 'gamma': 3.6494960344332696, 'reg_alpha': 4.438045216179074e-06, 'reg_lambda': 0.08029984823185037, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  71%|███████   | 142/200 [02:16<01:00,  1.04s/it]

[I 2025-11-10 17:27:59,168] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.02611305752229331, 'n_estimators': 847, 'subsample': 0.6328502194616202, 'colsample_bytree': 0.8930060555173902, 'min_child_weight': 7, 'gamma': 3.6577410393241965, 'reg_alpha': 0.0004930301254954104, 'reg_lambda': 0.09012865595282285, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  72%|███████▏  | 144/200 [02:16<00:36,  1.53it/s]

[I 2025-11-10 17:27:59,676] Trial 143 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.012147396261116335, 'n_estimators': 644, 'subsample': 0.9721503049723648, 'colsample_bytree': 0.9488043403378873, 'min_child_weight': 10, 'gamma': 3.625463747188638, 'reg_alpha': 0.0004238164185859125, 'reg_lambda': 0.0031713961913061115, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:27:59,803] Trial 142 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.011364467718661998, 'n_estimators': 759, 'subsample': 0.6556183876329589, 'colsample_bytree': 0.8753268783027829, 'min_child_weight': 10, 'gamma': 3.3127246792828515, 'reg_alpha': 2.005228126754176e-06, 'reg_lambda': 0.0003920053593088465, 'max_delta_step': 1}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  72%|███████▎  | 145/200 [02:17<00:35,  1.55it/s]

[I 2025-11-10 17:28:00,430] Trial 146 pruned.

Best trial: 3. Best value: 0.5:  74%|███████▎  | 147/200 [02:18<00:27,  1.95it/s]

[I 2025-11-10 17:28:01,170] Trial 144 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03656814456223354, 'n_estimators': 760, 'subsample': 0.9174968557810012, 'colsample_bytree': 0.6920270672268899, 'min_child_weight': 7, 'gamma': 3.2802750428257523, 'reg_alpha': 5.029599739691664e-07, 'reg_lambda': 1.4306236213919931e-08, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:28:01,305] Trial 147 pruned.

Best trial: 3. Best value: 0.5:  74%|███████▍  | 148/200 [02:19<00:39,  1.32it/s]

[I 2025-11-10 17:28:02,620] Trial 145 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.01862637794721595, 'n_estimators': 746, 'subsample': 0.9173681890321881, 'colsample_bytree': 0.6911079460088762, 'min_child_weight': 10, 'gamma': 1.8090361027931126, 'reg_alpha': 4.168877023894875e-07, 'reg_lambda': 1.6330651247551434e-08, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  74%|███████▍  | 149/200 [02:20<00:46,  1.09it/s]

[I 2025-11-10 17:28:03,932] Trial 148 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0282741634682464, 'n_estimators': 798, 'subsample': 0.9988898431049836, 'colsample_bytree': 0.6604005185898204, 'min_child_weight': 6, 'gamma': 4.498349246188748, 'reg_alpha': 5.908677308829721e-07, 'reg_lambda': 8.605945754015888e-06, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  75%|███████▌  | 150/200 [02:21<00:46,  1.07it/s]

[I 2025-11-10 17:28:04,886] Trial 150 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.04099583007526124, 'n_estimators': 797, 'subsample': 0.5666673851432035, 'colsample_bytree': 0.7146560682298427, 'min_child_weight': 6, 'gamma': 3.502618408195118, 'reg_alpha': 3.525737436444299e-08, 'reg_lambda': 4.346265118406809e-07, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  76%|███████▌  | 151/200 [02:22<00:48,  1.02it/s]

[I 2025-11-10 17:28:05,986] Trial 151 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.014502693375626173, 'n_estimators': 790, 'subsample': 0.5530076069718172, 'colsample_bytree': 0.5642599229626536, 'min_child_weight': 6, 'gamma': 3.490824465732739, 'reg_alpha': 1.313187691099255e-07, 'reg_lambda': 4.391477224935028e-08, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  76%|███████▌  | 152/200 [02:23<00:42,  1.12it/s]

[I 2025-11-10 17:28:06,668] Trial 152 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.2023508489112964, 'n_estimators': 573, 'subsample': 0.8848221394880321, 'colsample_bytree': 0.9744261438777588, 'min_child_weight': 7, 'gamma': 3.418863054190297, 'reg_alpha': 3.959806089564663e-08, 'reg_lambda': 4.1324475003278344e-07, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  76%|███████▋  | 153/200 [02:23<00:32,  1.43it/s]

[I 2025-11-10 17:28:06,924] Trial 153 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.20194230761609838, 'n_estimators': 397, 'subsample': 0.8057782301355206, 'colsample_bytree': 0.9783889881120256, 'min_child_weight': 7, 'gamma': 4.737336955126432, 'reg_alpha': 1.39707415369007e-07, 'reg_lambda': 3.8219766100973354e-08, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  77%|███████▋  | 154/200 [02:24<00:29,  1.54it/s]

[I 2025-11-10 17:28:07,447] Trial 149 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01710454261699845, 'n_estimators': 1433, 'subsample': 0.8924732700939972, 'colsample_bytree': 0.6546594947113116, 'min_child_weight': 6, 'gamma': 3.5001968951620612, 'reg_alpha': 9.293493004854198e-08, 'reg_lambda': 3.9685409985634334e-08, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  78%|███████▊  | 155/200 [02:25<00:37,  1.20it/s]

[I 2025-11-10 17:28:08,721] Trial 154 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.09812271085014139, 'n_estimators': 562, 'subsample': 0.7078013827703568, 'colsample_bytree': 0.8804088881403933, 'min_child_weight': 7, 'gamma': 3.402710746068098, 'reg_alpha': 6.676858377364566e-07, 'reg_lambda': 9.578947355640716e-08, 'max_delta_step': 0}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  78%|███████▊  | 156/200 [02:27<00:46,  1.06s/it]

[I 2025-11-10 17:28:10,298] Trial 156 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.020907109572636084, 'n_estimators': 728, 'subsample': 0.7566883965537218, 'colsample_bytree': 0.8365022137741035, 'min_child_weight': 7, 'gamma': 2.8685207267531196, 'reg_alpha': 1.8075537768669567e-06, 'reg_lambda': 1.1834745315895556e-07, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  78%|███████▊  | 157/200 [02:27<00:36,  1.19it/s]

[I 2025-11-10 17:28:10,645] Trial 157 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07367722240312063, 'n_estimators': 716, 'subsample': 0.7160473740342962, 'colsample_bytree': 0.8422992661900597, 'min_child_weight': 7, 'gamma': 4.56599144278781, 'reg_alpha': 1.5263558920539143e-06, 'reg_lambda': 9.672743660019296e-08, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  79%|███████▉  | 158/200 [02:28<00:36,  1.15it/s]

[I 2025-11-10 17:28:11,574] Trial 158 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0702069644848662, 'n_estimators': 611, 'subsample': 0.7371338992140508, 'colsample_bytree': 0.8350441981858605, 'min_child_weight': 5, 'gamma': 2.9548175285225082, 'reg_alpha': 1.1778736835550202e-06, 'reg_lambda': 7.680628554484266e-08, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  80%|███████▉  | 159/200 [02:30<00:42,  1.04s/it]

[I 2025-11-10 17:28:13,000] Trial 159 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.024835693058373885, 'n_estimators': 591, 'subsample': 0.5113721409700797, 'colsample_bytree': 0.6790971720465355, 'min_child_weight': 5, 'gamma': 3.2162652732908454, 'reg_alpha': 1.3375682699249084e-06, 'reg_lambda': 0.6011098476444212, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:28:13,091] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.021064516236168264, 'n_estimators': 1449, 'subsample': 0.7368752696445799, 'colsample_bytree': 0.6806796497248504, 'min_child_weight': 7, 'gamma': 2.843709467746513, 'reg_alpha': 1.3284181456682094e-06, 'reg_lambda': 7.925149629633653e-08, 'max_delta_step': 0}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  80%|████████  | 161/200 [02:30<00:27,  1.42it/s]

[I 2025-11-10 17:28:13,637] Trial 160 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.02471999272936881, 'n_estimators': 617, 'subsample': 0.9039312029357103, 'colsample_bytree': 0.9136645143097748, 'min_child_weight': 5, 'gamma': 4.243911225959016, 'reg_alpha': 1.7144667396772854e-07, 'reg_lambda': 2.0373839511261647, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  81%|████████  | 162/200 [02:31<00:30,  1.23it/s]

[I 2025-11-10 17:28:14,774] Trial 161 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.04404153621067844, 'n_estimators': 664, 'subsample': 0.9414128126257887, 'colsample_bytree': 0.9289592836115589, 'min_child_weight': 8, 'gamma': 4.269637436797238, 'reg_alpha': 1.7970164168989674e-07, 'reg_lambda': 0.00023132419813088747, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  82%|████████▏ | 163/200 [02:32<00:26,  1.42it/s]

[I 2025-11-10 17:28:15,171] Trial 164 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.010201452752427823, 'n_estimators': 309, 'subsample': 0.6916106233329515, 'colsample_bytree': 0.8732268721734768, 'min_child_weight': 6, 'gamma': 4.392051687190202, 'reg_alpha': 0.001022596806739445, 'reg_lambda': 0.2698410538489826, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  82%|████████▏ | 164/200 [02:32<00:21,  1.71it/s]

[I 2025-11-10 17:28:15,437] Trial 163 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.053464789445133235, 'n_estimators': 513, 'subsample': 0.9456906987062587, 'colsample_bytree': 0.5344919730909354, 'min_child_weight': 9, 'gamma': 4.651668095936262, 'reg_alpha': 2.716326151377056e-07, 'reg_lambda': 1.9811351386334417, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  82%|████████▎ | 165/200 [02:32<00:16,  2.11it/s]

[I 2025-11-10 17:28:15,626] Trial 162 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03048244145720574, 'n_estimators': 515, 'subsample': 0.6222382761585672, 'colsample_bytree': 0.9162728002472256, 'min_child_weight': 8, 'gamma': 1.2016910098500189, 'reg_alpha': 2.549118946911148e-08, 'reg_lambda': 0.00022278913517837092, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  84%|████████▎ | 167/200 [02:33<00:15,  2.12it/s]

[I 2025-11-10 17:28:16,577] Trial 167 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.011207657220837832, 'n_estimators': 223, 'subsample': 0.8300695835650937, 'colsample_bytree': 0.8142211701935255, 'min_child_weight': 6, 'gamma': 4.7814840587667815, 'reg_alpha': 0.0020528299335334007, 'reg_lambda': 0.12704897345312913, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:28:16,698] Trial 165 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.010586617445434226, 'n_estimators': 370, 'subsample': 0.8436891558142955, 'colsample_bytree': 0.8730167868584325, 'min_child_weight': 6, 'gamma': 4.674467428068566, 'reg_alpha': 3.1093166093140196e-07, 'reg_lambda': 0.26079563590470023, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  84%|████████▍ | 168/200 [02:33<00:12,  2.63it/s]

[I 2025-11-10 17:28:16,863] Trial 168 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.013508054706941856, 'n_estimators': 230, 'subsample': 0.9790643064727313, 'colsample_bytree': 0.8164927695356562, 'min_child_weight': 6, 'gamma': 4.794857669583402, 'reg_alpha': 0.002063371258756488, 'reg_lambda': 0.17149222320303686, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  85%|████████▌ | 170/200 [02:35<00:14,  2.02it/s]

[I 2025-11-10 17:28:18,138] Trial 170 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.012583002135178246, 'n_estimators': 297, 'subsample': 0.7867853008062001, 'colsample_bytree': 0.8296227830242722, 'min_child_weight': 5, 'gamma': 4.946426289666034, 'reg_alpha': 0.004189611273399666, 'reg_lambda': 0.16095599917257156, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:28:18,279] Trial 171 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.012112609253132584, 'n_estimators': 270, 'subsample': 0.7808730001372994, 'colsample_bytree': 0.9654933646257765, 'min_child_weight': 7, 'gamma': 4.923133906156286, 'reg_alpha': 0.0047167922384134114, 'reg_lambda': 2.644816295731184e-07, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  86%|████████▌ | 171/200 [02:35<00:11,  2.60it/s]

[I 2025-11-10 17:28:18,406] Trial 169 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.013214229861605382, 'n_estimators': 362, 'subsample': 0.7977396689262567, 'colsample_bytree': 0.57919784339195, 'min_child_weight': 6, 'gamma': 3.8594219019340077, 'reg_alpha': 0.005846563908998594, 'reg_lambda': 1.0060502263124436e-08, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  86%|████████▌ | 172/200 [02:37<00:21,  1.28it/s]

[I 2025-11-10 17:28:20,118] Trial 166 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.05280827030432404, 'n_estimators': 1060, 'subsample': 0.8315816510896886, 'colsample_bytree': 0.8110633465312846, 'min_child_weight': 6, 'gamma': 4.776282249742572, 'reg_alpha': 3.2400998335555843e-07, 'reg_lambda': 0.14189379875040622, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  86%|████████▋ | 173/200 [02:38<00:24,  1.12it/s]

[I 2025-11-10 17:28:21,272] Trial 175 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.010144972988611979, 'n_estimators': 200, 'subsample': 0.8177385701640014, 'colsample_bytree': 0.8970955273924978, 'min_child_weight': 5, 'gamma': 4.1200597815138185, 'reg_alpha': 0.0007906959990174945, 'reg_lambda': 0.03047477547836096, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  87%|████████▋ | 174/200 [02:39<00:22,  1.16it/s]

[I 2025-11-10 17:28:22,064] Trial 174 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.010208186175945311, 'n_estimators': 813, 'subsample': 0.8167283338569652, 'colsample_bytree': 0.8981971830065357, 'min_child_weight': 5, 'gamma': 0.9626977337831178, 'reg_alpha': 1.0142376361986706e-08, 'reg_lambda': 9.348000040301254e-05, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  88%|████████▊ | 175/200 [02:39<00:17,  1.44it/s]

[I 2025-11-10 17:28:22,366] Trial 173 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.015165319006210804, 'n_estimators': 880, 'subsample': 0.7994723031042349, 'colsample_bytree': 0.8975824791501615, 'min_child_weight': 5, 'gamma': 3.8643069162662345, 'reg_alpha': 3.610008552596642e-05, 'reg_lambda': 3.1056604248435645e-05, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  88%|████████▊ | 176/200 [02:39<00:14,  1.64it/s]

[I 2025-11-10 17:28:22,781] Trial 172 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.022863486412784007, 'n_estimators': 1048, 'subsample': 0.8035208313108985, 'colsample_bytree': 0.5174498119471774, 'min_child_weight': 7, 'gamma': 3.777610669729313, 'reg_alpha': 3.542129718822399e-05, 'reg_lambda': 1.0187844157406516e-08, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  88%|████████▊ | 177/200 [02:40<00:14,  1.54it/s]

[I 2025-11-10 17:28:23,513] Trial 177 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.022626425809957974, 'n_estimators': 265, 'subsample': 0.7242462401954008, 'colsample_bytree': 0.7846883995003993, 'min_child_weight': 7, 'gamma': 4.551005278942285, 'reg_alpha': 0.0012260301031271862, 'reg_lambda': 4.5051952654878615, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  89%|████████▉ | 178/200 [02:40<00:13,  1.67it/s]

[I 2025-11-10 17:28:23,991] Trial 178 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.011546485723643238, 'n_estimators': 274, 'subsample': 0.7688510961933551, 'colsample_bytree': 0.9877103621598428, 'min_child_weight': 6, 'gamma': 4.472195150712521, 'reg_alpha': 0.0014631358818638905, 'reg_lambda': 0.05729571125409407, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  90%|████████▉ | 179/200 [02:41<00:14,  1.44it/s]

[I 2025-11-10 17:28:24,921] Trial 179 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.011912416008487192, 'n_estimators': 423, 'subsample': 0.6568893596733707, 'colsample_bytree': 0.558020380883593, 'min_child_weight': 6, 'gamma': 4.469263705358035, 'reg_alpha': 0.6984910211172642, 'reg_lambda': 5.614669847833588, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  90%|█████████ | 180/200 [02:42<00:14,  1.36it/s]

[I 2025-11-10 17:28:25,747] Trial 181 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05940286731614948, 'n_estimators': 328, 'subsample': 0.9294790363912818, 'colsample_bytree': 0.9097677055441643, 'min_child_weight': 10, 'gamma': 0.7901946878583268, 'reg_alpha': 0.013711682272252184, 'reg_lambda': 8.591974878020116, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  90%|█████████ | 181/200 [02:43<00:16,  1.15it/s]

[I 2025-11-10 17:28:26,935] Trial 180 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.01132682112754143, 'n_estimators': 546, 'subsample': 0.8632839297660071, 'colsample_bytree': 0.9529044589732713, 'min_child_weight': 9, 'gamma': 4.354146356660968, 'reg_alpha': 0.000291715311350904, 'reg_lambda': 0.05061490056867307, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  91%|█████████ | 182/200 [02:44<00:13,  1.35it/s]

[I 2025-11-10 17:28:27,378] Trial 176 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.011346997727281108, 'n_estimators': 1038, 'subsample': 0.802711383989778, 'colsample_bytree': 0.9493376971122925, 'min_child_weight': 7, 'gamma': 4.454640353990396, 'reg_alpha': 0.002964195060569059, 'reg_lambda': 4.151456375061366e-05, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  92%|█████████▏| 183/200 [02:44<00:10,  1.67it/s]

[I 2025-11-10 17:28:27,638] Trial 182 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01993190361083979, 'n_estimators': 331, 'subsample': 0.983541183918969, 'colsample_bytree': 0.9102650344127328, 'min_child_weight': 10, 'gamma': 4.343221999718226, 'reg_alpha': 0.010704819974263263, 'reg_lambda': 0.007798453096100264, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  92%|█████████▏| 184/200 [02:47<00:19,  1.19s/it]

[I 2025-11-10 17:28:30,215] Trial 183 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.1509980230711954, 'n_estimators': 729, 'subsample': 0.9832368390107119, 'colsample_bytree': 0.9494134742749689, 'min_child_weight': 9, 'gamma': 4.006396967778629, 'reg_alpha': 0.0002563205125331593, 'reg_lambda': 1.8035357085110028e-06, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  92%|█████████▎| 185/200 [02:47<00:15,  1.00s/it]

[I 2025-11-10 17:28:30,766] Trial 184 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.04056319994065864, 'n_estimators': 732, 'subsample': 0.541992042800381, 'colsample_bytree': 0.9381717433280985, 'min_child_weight': 6, 'gamma': 4.06163765845738, 'reg_alpha': 1.1719574708125647e-05, 'reg_lambda': 3.5613492942963607e-06, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.
[I 2025-11-10 17:28:30,787] Trial 185 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03190632213490619, 'n_estimators': 731, 'subsample': 0.5907392405668273, 'colsample_bytree': 0.7068837668973019, 'min_child_weight': 6, 'gamma': 4.319405253057874, 'reg_alpha': 8.934986896309641e-06, 'reg_lambda': 0.028729088060655328, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  94%|█████████▎| 187/200 [02:48<00:07,  1.65it/s]

[I 2025-11-10 17:28:31,061] Trial 186 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03241163928232594, 'n_estimators': 727, 'subsample': 0.7881419147581014, 'colsample_bytree': 0.7107604604232425, 'min_child_weight': 6, 'gamma': 2.7267905768522938, 'reg_alpha': 1.3702882564841654e-05, 'reg_lambda': 0.02406300666116696, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  94%|█████████▍| 188/200 [02:51<00:14,  1.20s/it]

[I 2025-11-10 17:28:34,068] Trial 190 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.02870978017085964, 'n_estimators': 459, 'subsample': 0.7545675614956044, 'colsample_bytree': 0.9294303102696271, 'min_child_weight': 5, 'gamma': 1.5706151819492038, 'reg_alpha': 0.02975131813899051, 'reg_lambda': 0.07259628977448329, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  94%|█████████▍| 189/200 [02:52<00:13,  1.19s/it]

[I 2025-11-10 17:28:35,217] Trial 188 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03507948849823018, 'n_estimators': 781, 'subsample': 0.7586840816501315, 'colsample_bytree': 0.9218976733150968, 'min_child_weight': 6, 'gamma': 4.996150007104437, 'reg_alpha': 9.267766274854012e-06, 'reg_lambda': 0.030542057371689305, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  95%|█████████▌| 190/200 [02:52<00:10,  1.03s/it]

[I 2025-11-10 17:28:35,835] Trial 187 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03937617704090017, 'n_estimators': 991, 'subsample': 0.78670121190476, 'colsample_bytree': 0.9295714492903563, 'min_child_weight': 6, 'gamma': 4.597014456766831, 'reg_alpha': 7.567582330102056e-06, 'reg_lambda': 3.847973756160324e-06, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  96%|█████████▌| 191/200 [02:53<00:09,  1.06s/it]

[I 2025-11-10 17:28:36,973] Trial 189 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.028106443875707685, 'n_estimators': 974, 'subsample': 0.8126943449437317, 'colsample_bytree': 0.9248934067036628, 'min_child_weight': 6, 'gamma': 2.725722077605114, 'reg_alpha': 7.161481028112673e-06, 'reg_lambda': 0.014199514978984881, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  96%|█████████▌| 192/200 [02:54<00:07,  1.06it/s]

[I 2025-11-10 17:28:37,613] Trial 194 pruned.

Best trial: 3. Best value: 0.5:  96%|█████████▋| 193/200 [02:55<00:06,  1.07it/s]

[I 2025-11-10 17:28:38,529] Trial 191 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03912432201016271, 'n_estimators': 772, 'subsample': 0.5152113921033494, 'colsample_bytree': 0.9669912343625195, 'min_child_weight': 6, 'gamma': 4.623691624096644, 'reg_alpha': 4.0668861303263985e-06, 'reg_lambda': 0.0005505929772005637, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  97%|█████████▋| 194/200 [02:57<00:07,  1.20s/it]

[I 2025-11-10 17:28:40,379] Trial 195 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03441826198772058, 'n_estimators': 536, 'subsample': 0.8790727579631779, 'colsample_bytree': 0.7505693188504827, 'min_child_weight': 7, 'gamma': 4.685889164582488, 'reg_alpha': 2.2744333156559165e-05, 'reg_lambda': 0.007685497292161749, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  98%|█████████▊| 195/200 [02:57<00:05,  1.02s/it]

[I 2025-11-10 17:28:40,954] Trial 192 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03756459920039702, 'n_estimators': 988, 'subsample': 0.5104368344152046, 'colsample_bytree': 0.879626823896614, 'min_child_weight': 8, 'gamma': 4.593703203279489, 'reg_alpha': 2.5520559792216103e-06, 'reg_lambda': 1.1264746395248528, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  98%|█████████▊| 196/200 [02:58<00:03,  1.20it/s]

[I 2025-11-10 17:28:41,346] Trial 196 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.03383965162961959, 'n_estimators': 507, 'subsample': 0.5042415766461523, 'colsample_bytree': 0.8841334477061853, 'min_child_weight': 7, 'gamma': 4.880342162167285, 'reg_alpha': 1.6707875534281632e-08, 'reg_lambda': 1.1119128920610432e-06, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  98%|█████████▊| 197/200 [02:59<00:02,  1.19it/s]

[I 2025-11-10 17:28:42,209] Trial 193 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.02431882130704742, 'n_estimators': 1133, 'subsample': 0.5030838219090438, 'colsample_bytree': 0.8851571021698881, 'min_child_weight': 7, 'gamma': 4.208129312761004, 'reg_alpha': 4.2807012765505286e-06, 'reg_lambda': 8.548780654948603e-06, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  99%|█████████▉| 198/200 [02:59<00:01,  1.38it/s]

[I 2025-11-10 17:28:42,665] Trial 197 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.02583957229894454, 'n_estimators': 509, 'subsample': 0.5006411199501286, 'colsample_bytree': 0.8863932904762671, 'min_child_weight': 7, 'gamma': 4.855579846110088, 'reg_alpha': 4.843140233754643e-06, 'reg_lambda': 1.0342309134113357e-06, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5: 100%|█████████▉| 199/200 [03:00<00:00,  1.59it/s]

[I 2025-11-10 17:28:43,067] Trial 198 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.024314848336849836, 'n_estimators': 558, 'subsample': 0.8988041396162579, 'colsample_bytree': 0.8504263105283063, 'min_child_weight': 7, 'gamma': 4.8453704426901245, 'reg_alpha': 4.3015413988307266e-06, 'reg_lambda': 0.002265512824159855, 'max_delta_step': 1}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5: 100%|██████████| 200/200 [03:00<00:00,  1.11it/s]

[I 2025-11-10 17:28:43,534] Trial 199 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.04415475743097179, 'n_estimators': 638, 'subsample': 0.7719171862142795, 'colsample_bytree': 0.9881607000782724, 'min_child_weight': 5, 'gamma': 4.208121268987068, 'reg_alpha': 6.234944008787488e-05, 'reg_lambda': 0.3905021695816639, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

[I 2025-11-10 17:28:44,536] A new study created in memory with name: 3_3_roc_auc
Best trial: 3. Best value: 0.5:   0%|          | 1/200 [00:02<07:26,  2.24s/it]

[I 2025-11-10 17:28:46,770] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07860500007050508, 'n_estimators': 579, 'subsample': 0.8915661124534906, 'colsample_bytree': 0.5986461577365467, 'min_child_weight': 7, 'gamma': 3.6334739589922274, 'reg_alpha': 0.0018578737487268176, 'reg_lambda': 0.6778871709460825, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   1%|          | 2/200 [00:03<04:40,  1.42s/it]

[I 2025-11-10 17:28:47,621] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04751701793958915, 'n_estimators': 792, 'subsample': 0.7932797413555153, 'colsample_bytree': 0.7300050734586639, 'min_child_weight': 9, 'gamma': 0.7713022547496357, 'reg_alpha': 0.4033026116116864, 'reg_lambda': 0.05851275551943679, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 1. Best value: 0.583762:   2%|▏         | 3/200 [00:03<02:51,  1.15it/s]

[I 2025-11-10 17:28:47,829] Trial 1 finished with value: 0.5837621832358674 and parameters: {'max_depth': 9, 'learning_rate': 0.2047671554846333, 'n_estimators': 733, 'subsample': 0.9044950282986294, 'colsample_bytree': 0.9479715251819882, 'min_child_weight': 4, 'gamma': 2.6252908778006443, 'reg_alpha': 0.0004403862917657113, 'reg_lambda': 2.7089075368662386e-05, 'max_delta_step': 1}. Best is trial 1 with value: 0.5837621832358674.

Best trial: 1. Best value: 0.583762:   2%|▏         | 4/200 [00:04<03:01,  1.08it/s]

[I 2025-11-10 17:28:48,859] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2834726688656704, 'n_estimators': 278, 'subsample': 0.5399580238409838, 'colsample_bytree': 0.8339587239041055, 'min_child_weight': 5, 'gamma': 1.939242333281395, 'reg_alpha': 0.1393972896505029, 'reg_lambda': 0.07509475817296772, 'max_delta_step': 10}. Best is trial 1 with value: 0.5837621832358674.

Best trial: 1. Best value: 0.583762:   2%|▎         | 5/200 [00:06<04:38,  1.43s/it]

[I 2025-11-10 17:28:51,161] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.019939515772787443, 'n_estimators': 1164, 'subsample': 0.9496193500060763, 'colsample_bytree': 0.6376976760193478, 'min_child_weight': 6, 'gamma': 1.4549173071693677, 'reg_alpha': 3.529617117659815e-06, 'reg_lambda': 1.6067824201310398e-07, 'max_delta_step': 2}. Best is trial 1 with value: 0.5837621832358674.

Best trial: 1. Best value: 0.583762:   3%|▎         | 6/200 [00:07<03:52,  1.20s/it]

[I 2025-11-10 17:28:51,922] Trial 0 finished with value: 0.4937426900584795 and parameters: {'max_depth': 9, 'learning_rate': 0.02095971347053385, 'n_estimators': 1345, 'subsample': 0.9215982189288032, 'colsample_bytree': 0.6582768811331905, 'min_child_weight': 2, 'gamma': 4.010831915542916, 'reg_alpha': 2.9801324814079697e-06, 'reg_lambda': 1.4123862874621415e-05, 'max_delta_step': 2}. Best is trial 1 with value: 0.5837621832358674.

Best trial: 6. Best value: 0.617076:   4%|▎         | 7/200 [00:08<03:13,  1.00s/it]

[I 2025-11-10 17:28:52,528] Trial 6 finished with value: 0.6170760233918129 and parameters: {'max_depth': 9, 'learning_rate': 0.09175895873055558, 'n_estimators': 1194, 'subsample': 0.9780885467098581, 'colsample_bytree': 0.7719319138637278, 'min_child_weight': 5, 'gamma': 0.6507091858699732, 'reg_alpha': 0.002903088788165892, 'reg_lambda': 9.808193905726843e-07, 'max_delta_step': 3}. Best is trial 6 with value: 0.6170760233918129.
[I 2025-11-10 17:28:52,553] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.06856100022407141, 'n_estimators': 958, 'subsample': 0.9697943511683031, 'colsample_bytree': 0.8246609501271451, 'min_child_weight': 6, 'gamma': 1.039262706327238, 'reg_alpha': 1.9976085689773824, 'reg_lambda': 3.551294757691021e-08, 'max_delta_step': 5}. Best is trial 6 with value: 0.6170760233918129.

Best trial: 6. Best value: 0.617076:   4%|▍         | 9/200 [00:10<03:34,  1.13s/it]

[I 2025-11-10 17:28:55,028] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.23177974508721635, 'n_estimators': 647, 'subsample': 0.5553204422010398, 'colsample_bytree': 0.5870629259938251, 'min_child_weight': 5, 'gamma': 1.6666598368306258, 'reg_alpha': 0.22591593675200036, 'reg_lambda': 0.00014954447078260974, 'max_delta_step': 1}. Best is trial 6 with value: 0.6170760233918129.

Best trial: 6. Best value: 0.617076:   5%|▌         | 10/200 [00:12<03:54,  1.23s/it]

[I 2025-11-10 17:28:56,574] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.25889027123825326, 'n_estimators': 1242, 'subsample': 0.9804897029832121, 'colsample_bytree': 0.6415990494686832, 'min_child_weight': 10, 'gamma': 4.050301283610288, 'reg_alpha': 0.001530576039299367, 'reg_lambda': 0.0001535522642476118, 'max_delta_step': 2}. Best is trial 6 with value: 0.6170760233918129.

Best trial: 6. Best value: 0.617076:   6%|▌         | 11/200 [00:12<03:26,  1.09s/it]

[I 2025-11-10 17:28:57,293] Trial 12 finished with value: 0.5728849902534112 and parameters: {'max_depth': 3, 'learning_rate': 0.0800748989748908, 'n_estimators': 487, 'subsample': 0.854319018616378, 'colsample_bytree': 0.5367662719923038, 'min_child_weight': 3, 'gamma': 4.783336932980249, 'reg_alpha': 2.209295675510518e-08, 'reg_lambda': 0.02849119601266065, 'max_delta_step': 1}. Best is trial 6 with value: 0.6170760233918129.

Best trial: 6. Best value: 0.617076:   6%|▌         | 12/200 [00:13<02:54,  1.08it/s]

[I 2025-11-10 17:28:57,784] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.02201231928522778, 'n_estimators': 1335, 'subsample': 0.5683071997019659, 'colsample_bytree': 0.7051180469215452, 'min_child_weight': 9, 'gamma': 2.6742994399414126, 'reg_alpha': 1.3768486706735412e-08, 'reg_lambda': 6.540231542332907e-05, 'max_delta_step': 9}. Best is trial 6 with value: 0.6170760233918129.

Best trial: 6. Best value: 0.617076:   6%|▋         | 13/200 [00:14<03:34,  1.15s/it]

[I 2025-11-10 17:28:59,484] Trial 8 finished with value: 0.5357699805068226 and parameters: {'max_depth': 8, 'learning_rate': 0.21697463074293924, 'n_estimators': 1390, 'subsample': 0.8899695829019159, 'colsample_bytree': 0.7213058033627774, 'min_child_weight': 1, 'gamma': 4.855749960382393, 'reg_alpha': 0.0066090460953482436, 'reg_lambda': 1.3027246399903843e-06, 'max_delta_step': 6}. Best is trial 6 with value: 0.6170760233918129.

Best trial: 6. Best value: 0.617076:   7%|▋         | 14/200 [00:16<04:20,  1.40s/it]

[I 2025-11-10 17:29:01,522] Trial 14 finished with value: 0.5548732943469785 and parameters: {'max_depth': 10, 'learning_rate': 0.1365517034775241, 'n_estimators': 987, 'subsample': 0.6780859363590245, 'colsample_bytree': 0.9713435675964149, 'min_child_weight': 3, 'gamma': 2.6785612173664624, 'reg_alpha': 6.46154648566748e-05, 'reg_lambda': 1.8635786400148924e-06, 'max_delta_step': 5}. Best is trial 6 with value: 0.6170760233918129.

Best trial: 6. Best value: 0.617076:   8%|▊         | 15/200 [00:17<03:45,  1.22s/it]

[I 2025-11-10 17:29:02,300] Trial 15 finished with value: 0.5652631578947369 and parameters: {'max_depth': 10, 'learning_rate': 0.14776425864669268, 'n_estimators': 1024, 'subsample': 0.6965366085504852, 'colsample_bytree': 0.9840664115682326, 'min_child_weight': 3, 'gamma': 0.00014506873552821986, 'reg_alpha': 7.981283035210301e-05, 'reg_lambda': 1.2136076557232597e-06, 'max_delta_step': 5}. Best is trial 6 with value: 0.6170760233918129.

Best trial: 6. Best value: 0.617076:   8%|▊         | 16/200 [00:18<03:32,  1.16s/it]

[I 2025-11-10 17:29:03,300] Trial 13 finished with value: 0.512046783625731 and parameters: {'max_depth': 6, 'learning_rate': 0.12748579002880517, 'n_estimators': 1429, 'subsample': 0.6880350157649762, 'colsample_bytree': 0.9971187192483101, 'min_child_weight': 1, 'gamma': 0.26243655278007827, 'reg_alpha': 3.2050476744225943e-07, 'reg_lambda': 5.681039371215364e-07, 'max_delta_step': 6}. Best is trial 6 with value: 0.6170760233918129.

Best trial: 6. Best value: 0.617076:   8%|▊         | 17/200 [00:19<02:55,  1.04it/s]

[I 2025-11-10 17:29:03,800] Trial 16 finished with value: 0.5942690058479533 and parameters: {'max_depth': 10, 'learning_rate': 0.1325064157715275, 'n_estimators': 1022, 'subsample': 0.6841223477532645, 'colsample_bytree': 0.9924943018017165, 'min_child_weight': 4, 'gamma': 0.3252419830235742, 'reg_alpha': 6.34382941209037e-05, 'reg_lambda': 2.5097210033105493e-06, 'max_delta_step': 5}. Best is trial 6 with value: 0.6170760233918129.

Best trial: 6. Best value: 0.617076:   9%|▉         | 18/200 [00:21<03:54,  1.29s/it]

[I 2025-11-10 17:29:05,863] Trial 18 finished with value: 0.5882066276803118 and parameters: {'max_depth': 6, 'learning_rate': 0.0440265039943239, 'n_estimators': 797, 'subsample': 0.8044397539481808, 'colsample_bytree': 0.8960376319525877, 'min_child_weight': 4, 'gamma': 3.294254012288157, 'reg_alpha': 0.012821106583019612, 'reg_lambda': 0.003955430509736116, 'max_delta_step': 0}. Best is trial 6 with value: 0.6170760233918129.

Best trial: 6. Best value: 0.617076:  10%|▉         | 19/200 [00:21<03:08,  1.04s/it]

[I 2025-11-10 17:29:06,330] Trial 17 finished with value: 0.5551267056530215 and parameters: {'max_depth': 6, 'learning_rate': 0.13994500189465547, 'n_estimators': 1128, 'subsample': 0.8124094111654355, 'colsample_bytree': 0.9942395882228529, 'min_child_weight': 4, 'gamma': 0.42696138265786043, 'reg_alpha': 4.89828035877763e-05, 'reg_lambda': 0.0034296257994012483, 'max_delta_step': 0}. Best is trial 6 with value: 0.6170760233918129.

Best trial: 6. Best value: 0.617076:  10%|█         | 20/200 [00:22<02:40,  1.12it/s]

[I 2025-11-10 17:29:06,873] Trial 21 pruned.

Best trial: 6. Best value: 0.617076:  10%|█         | 21/200 [00:22<02:07,  1.40it/s]

[I 2025-11-10 17:29:07,156] Trial 22 pruned.
[I 2025-11-10 17:29:07,174] Trial 19 finished with value: 0.5973489278752437 and parameters: {'max_depth': 8, 'learning_rate': 0.010057566346872155, 'n_estimators': 784, 'subsample': 0.8148558520742455, 'colsample_bytree': 0.8762208794842239, 'min_child_weight': 4, 'gamma': 3.119860358633208, 'reg_alpha': 0.019936951737439923, 'reg_lambda': 0.001150925372259683, 'max_delta_step': 0}. Best is trial 6 with value: 0.6170760233918129.

Best trial: 6. Best value: 0.617076:  12%|█▏        | 23/200 [00:23<01:24,  2.10it/s]

[I 2025-11-10 17:29:07,548] Trial 20 pruned.

Best trial: 6. Best value: 0.617076:  12%|█▏        | 24/200 [00:23<01:15,  2.33it/s]

[I 2025-11-10 17:29:07,836] Trial 23 pruned.

Best trial: 6. Best value: 0.617076:  12%|█▎        | 25/200 [00:23<01:05,  2.67it/s]

[I 2025-11-10 17:29:08,059] Trial 25 pruned.

Best trial: 6. Best value: 0.617076:  13%|█▎        | 26/200 [00:24<01:19,  2.20it/s]

[I 2025-11-10 17:29:08,731] Trial 26 pruned.

Best trial: 6. Best value: 0.617076:  14%|█▎        | 27/200 [00:24<01:07,  2.57it/s]

[I 2025-11-10 17:29:08,951] Trial 27 pruned.

Best trial: 6. Best value: 0.617076:  14%|█▍        | 28/200 [00:25<01:59,  1.44it/s]

[I 2025-11-10 17:29:10,403] Trial 30 pruned.

Best trial: 6. Best value: 0.617076:  15%|█▌        | 30/200 [00:26<01:26,  1.97it/s]

[I 2025-11-10 17:29:10,997] Trial 24 finished with value: 0.6158674463937622 and parameters: {'max_depth': 5, 'learning_rate': 0.04167841411397891, 'n_estimators': 857, 'subsample': 0.7652371311755342, 'colsample_bytree': 0.9052544928870874, 'min_child_weight': 4, 'gamma': 3.3279507717077883, 'reg_alpha': 0.022800328499776323, 'reg_lambda': 0.0008400990054090582, 'max_delta_step': 7}. Best is trial 6 with value: 0.6170760233918129.
[I 2025-11-10 17:29:11,137] Trial 28 finished with value: 0.5575828460038986 and parameters: {'max_depth': 10, 'learning_rate': 0.09853678450695806, 'n_estimators': 531, 'subsample': 0.8403065081931371, 'colsample_bytree': 0.7650910440338943, 'min_child_weight': 2, 'gamma': 3.1271951418901884, 'reg_alpha': 0.000667353765895203, 'reg_lambda': 0.0004262150861107959, 'max_delta_step': 3}. Best is trial 6 with value: 0.6170760233918129.

Best trial: 6. Best value: 0.617076:  16%|█▌        | 31/200 [00:27<01:22,  2.04it/s]

[I 2025-11-10 17:29:11,572] Trial 32 pruned.

Best trial: 6. Best value: 0.617076:  16%|█▌        | 32/200 [00:28<02:19,  1.20it/s]

[I 2025-11-10 17:29:13,222] Trial 31 finished with value: 0.588421052631579 and parameters: {'max_depth': 7, 'learning_rate': 0.10188012720016723, 'n_estimators': 695, 'subsample': 0.6483699749069176, 'colsample_bytree': 0.7730745321424454, 'min_child_weight': 4, 'gamma': 1.324248467899642, 'reg_alpha': 0.0017026750763030926, 'reg_lambda': 8.546082744383882e-06, 'max_delta_step': 3}. Best is trial 6 with value: 0.6170760233918129.

Best trial: 6. Best value: 0.617076:  16%|█▋        | 33/200 [00:29<01:54,  1.45it/s]

[I 2025-11-10 17:29:13,562] Trial 33 finished with value: 0.5854191033138401 and parameters: {'max_depth': 5, 'learning_rate': 0.015701533131934314, 'n_estimators': 391, 'subsample': 0.9364028491110926, 'colsample_bytree': 0.9403094303674654, 'min_child_weight': 3, 'gamma': 3.8968410222359866, 'reg_alpha': 0.003483956299701426, 'reg_lambda': 3.389233908738654, 'max_delta_step': 8}. Best is trial 6 with value: 0.6170760233918129.

Best trial: 34. Best value: 0.625653:  18%|█▊        | 35/200 [00:29<01:27,  1.88it/s]

[I 2025-11-10 17:29:14,286] Trial 36 pruned.
[I 2025-11-10 17:29:14,433] Trial 34 finished with value: 0.6256530214424951 and parameters: {'max_depth': 5, 'learning_rate': 0.015190156687649501, 'n_estimators': 669, 'subsample': 0.6513169223607421, 'colsample_bytree': 0.9393310969497978, 'min_child_weight': 4, 'gamma': 3.5595775217595405, 'reg_alpha': 0.9355278482586143, 'reg_lambda': 1.3100586274854542e-05, 'max_delta_step': 6}. Best is trial 34 with value: 0.6256530214424951.

Best trial: 34. Best value: 0.625653:  18%|█▊        | 36/200 [00:30<01:29,  1.83it/s]

[I 2025-11-10 17:29:15,010] Trial 38 pruned.

Best trial: 34. Best value: 0.625653:  18%|█▊        | 37/200 [00:30<01:14,  2.18it/s]

[I 2025-11-10 17:29:15,264] Trial 37 pruned.

Best trial: 34. Best value: 0.625653:  19%|█▉        | 38/200 [00:31<01:09,  2.32it/s]

[I 2025-11-10 17:29:15,635] Trial 39 pruned.

Best trial: 34. Best value: 0.625653:  20%|██        | 40/200 [00:32<01:17,  2.06it/s]

[I 2025-11-10 17:29:16,692] Trial 29 finished with value: 0.6219200779727094 and parameters: {'max_depth': 10, 'learning_rate': 0.05863849671300915, 'n_estimators': 1497, 'subsample': 0.6403364325248173, 'colsample_bytree': 0.7856652087009294, 'min_child_weight': 2, 'gamma': 3.114222958829842, 'reg_alpha': 0.00102906363890134, 'reg_lambda': 6.576279372561294, 'max_delta_step': 3}. Best is trial 34 with value: 0.6256530214424951.
[I 2025-11-10 17:29:16,870] Trial 35 finished with value: 0.5715594541910332 and parameters: {'max_depth': 5, 'learning_rate': 0.16657456194451295, 'n_estimators': 824, 'subsample': 0.5042805133866686, 'colsample_bytree': 0.9484396687891067, 'min_child_weight': 3, 'gamma': 3.490869632101542, 'reg_alpha': 0.00016717400445741737, 'reg_lambda': 2.921592159388849e-05, 'max_delta_step': 6}. Best is trial 34 with value: 0.6256530214424951.

Best trial: 34. Best value: 0.625653:  20%|██        | 41/200 [00:33<02:07,  1.25it/s]

[I 2025-11-10 17:29:18,412] Trial 42 pruned.

Best trial: 34. Best value: 0.625653:  22%|██▏       | 43/200 [00:34<01:28,  1.78it/s]

[I 2025-11-10 17:29:19,005] Trial 44 pruned.
[I 2025-11-10 17:29:19,153] Trial 40 finished with value: 0.5907992202729044 and parameters: {'max_depth': 4, 'learning_rate': 0.025274735196903864, 'n_estimators': 754, 'subsample': 0.7752820901356621, 'colsample_bytree': 0.9285194426980108, 'min_child_weight': 3, 'gamma': 4.396833899354456, 'reg_alpha': 0.05371197971717436, 'reg_lambda': 0.17304083227588726, 'max_delta_step': 6}. Best is trial 34 with value: 0.6256530214424951.

Best trial: 34. Best value: 0.625653:  22%|██▎       | 45/200 [00:35<01:01,  2.51it/s]

[I 2025-11-10 17:29:19,557] Trial 45 pruned.
[I 2025-11-10 17:29:19,682] Trial 46 pruned.

Best trial: 34. Best value: 0.625653:  24%|██▎       | 47/200 [00:35<00:39,  3.84it/s]

[I 2025-11-10 17:29:19,844] Trial 41 finished with value: 0.5883430799220273 and parameters: {'max_depth': 4, 'learning_rate': 0.010040036025281246, 'n_estimators': 752, 'subsample': 0.7737087203075271, 'colsample_bytree': 0.9303233747254712, 'min_child_weight': 3, 'gamma': 4.428337060272243, 'reg_alpha': 0.10385378440384625, 'reg_lambda': 3.6217985458310334e-07, 'max_delta_step': 6}. Best is trial 34 with value: 0.6256530214424951.
[I 2025-11-10 17:29:19,949] Trial 47 pruned.

Best trial: 34. Best value: 0.625653:  24%|██▍       | 48/200 [00:35<00:34,  4.36it/s]

[I 2025-11-10 17:29:20,106] Trial 49 pruned.

Best trial: 34. Best value: 0.625653:  24%|██▍       | 49/200 [00:36<00:52,  2.89it/s]

[I 2025-11-10 17:29:20,720] Trial 48 pruned.

Best trial: 34. Best value: 0.625653:  25%|██▌       | 50/200 [00:36<00:57,  2.61it/s]

[I 2025-11-10 17:29:21,198] Trial 50 pruned.

Best trial: 34. Best value: 0.625653:  26%|██▌       | 51/200 [00:37<01:14,  1.99it/s]

[I 2025-11-10 17:29:21,972] Trial 52 pruned.

Best trial: 34. Best value: 0.625653:  26%|██▌       | 52/200 [00:37<01:08,  2.17it/s]

[I 2025-11-10 17:29:22,333] Trial 53 pruned.

Best trial: 34. Best value: 0.625653:  26%|██▋       | 53/200 [00:38<01:14,  1.96it/s]

[I 2025-11-10 17:29:22,948] Trial 54 pruned.

Best trial: 34. Best value: 0.625653:  27%|██▋       | 54/200 [00:38<01:06,  2.21it/s]

[I 2025-11-10 17:29:23,279] Trial 55 pruned.

Best trial: 34. Best value: 0.625653:  28%|██▊       | 55/200 [00:39<01:09,  2.08it/s]

[I 2025-11-10 17:29:23,820] Trial 51 finished with value: 0.6116569200779727 and parameters: {'max_depth': 6, 'learning_rate': 0.055626690480225775, 'n_estimators': 872, 'subsample': 0.663062708284207, 'colsample_bytree': 0.6970935836803642, 'min_child_weight': 4, 'gamma': 2.8220683196214926, 'reg_alpha': 0.0056157421408371076, 'reg_lambda': 0.04454575255881678, 'max_delta_step': 1}. Best is trial 34 with value: 0.6256530214424951.

Best trial: 34. Best value: 0.625653:  28%|██▊       | 56/200 [00:39<00:56,  2.56it/s]

[I 2025-11-10 17:29:24,009] Trial 56 pruned.

Best trial: 34. Best value: 0.625653:  28%|██▊       | 57/200 [00:40<01:09,  2.05it/s]

[I 2025-11-10 17:29:24,717] Trial 59 pruned.

Best trial: 34. Best value: 0.625653:  29%|██▉       | 58/200 [00:40<00:59,  2.39it/s]

[I 2025-11-10 17:29:24,981] Trial 43 finished with value: 0.5983430799220273 and parameters: {'max_depth': 4, 'learning_rate': 0.044554877071369264, 'n_estimators': 1289, 'subsample': 0.5790227235492559, 'colsample_bytree': 0.7375454686369188, 'min_child_weight': 1, 'gamma': 4.428615144932701, 'reg_alpha': 0.14946259718296828, 'reg_lambda': 0.17893248948964885, 'max_delta_step': 4}. Best is trial 34 with value: 0.6256530214424951.

Best trial: 34. Best value: 0.625653:  30%|██▉       | 59/200 [00:41<01:23,  1.69it/s]

[I 2025-11-10 17:29:25,976] Trial 60 pruned.

Best trial: 34. Best value: 0.625653:  30%|███       | 60/200 [00:41<01:19,  1.77it/s]

[I 2025-11-10 17:29:26,475] Trial 61 pruned.

Best trial: 34. Best value: 0.625653:  30%|███       | 61/200 [00:42<01:28,  1.57it/s]

[I 2025-11-10 17:29:27,289] Trial 62 pruned.

Best trial: 34. Best value: 0.625653:  31%|███       | 62/200 [00:44<02:03,  1.11it/s]

[I 2025-11-10 17:29:28,791] Trial 57 finished with value: 0.5589668615984406 and parameters: {'max_depth': 10, 'learning_rate': 0.01347376574462001, 'n_estimators': 1172, 'subsample': 0.6750609159368295, 'colsample_bytree': 0.7493738265385694, 'min_child_weight': 3, 'gamma': 3.1354350592716473, 'reg_alpha': 0.0046463171645805814, 'reg_lambda': 9.504508855927258e-07, 'max_delta_step': 5}. Best is trial 34 with value: 0.6256530214424951.

Best trial: 34. Best value: 0.625653:  32%|███▏      | 63/200 [00:45<02:11,  1.04it/s]

[I 2025-11-10 17:29:29,906] Trial 65 pruned.

Best trial: 34. Best value: 0.625653:  32%|███▏      | 64/200 [00:46<02:06,  1.07it/s]

[I 2025-11-10 17:29:30,754] Trial 58 finished with value: 0.5648732943469785 and parameters: {'max_depth': 5, 'learning_rate': 0.012819753914349852, 'n_estimators': 1387, 'subsample': 0.8269355015075147, 'colsample_bytree': 0.6771333327776812, 'min_child_weight': 3, 'gamma': 3.4705842964194993, 'reg_alpha': 0.0053109828494097835, 'reg_lambda': 0.10302101975450186, 'max_delta_step': 2}. Best is trial 34 with value: 0.6256530214424951.

Best trial: 34. Best value: 0.625653:  32%|███▎      | 65/200 [00:47<02:04,  1.09it/s]

[I 2025-11-10 17:29:31,651] Trial 67 pruned.

Best trial: 34. Best value: 0.625653:  33%|███▎      | 66/200 [00:49<02:59,  1.34s/it]

[I 2025-11-10 17:29:33,982] Trial 63 finished with value: 0.5598050682261209 and parameters: {'max_depth': 5, 'learning_rate': 0.049111435331906254, 'n_estimators': 1350, 'subsample': 0.5438583286394975, 'colsample_bytree': 0.6245662925329852, 'min_child_weight': 1, 'gamma': 4.588699346858605, 'reg_alpha': 0.5002761176017835, 'reg_lambda': 0.8151839488273744, 'max_delta_step': 3}. Best is trial 34 with value: 0.6256530214424951.

Best trial: 34. Best value: 0.625653:  34%|███▎      | 67/200 [00:49<02:17,  1.03s/it]

[I 2025-11-10 17:29:34,287] Trial 64 finished with value: 0.5793372319688109 and parameters: {'max_depth': 6, 'learning_rate': 0.04673288103880452, 'n_estimators': 1367, 'subsample': 0.6381305904201164, 'colsample_bytree': 0.7511716454356299, 'min_child_weight': 2, 'gamma': 3.5120108532025194, 'reg_alpha': 0.023071738894062437, 'reg_lambda': 0.35949026748889795, 'max_delta_step': 3}. Best is trial 34 with value: 0.6256530214424951.

Best trial: 34. Best value: 0.625653:  34%|███▍      | 68/200 [00:50<02:22,  1.08s/it]

[I 2025-11-10 17:29:35,487] Trial 70 pruned.

Best trial: 34. Best value: 0.625653:  34%|███▍      | 69/200 [00:52<02:20,  1.07s/it]

[I 2025-11-10 17:29:36,543] Trial 71 pruned.
[I 2025-11-10 17:29:36,573] Trial 66 finished with value: 0.5481091617933722 and parameters: {'max_depth': 5, 'learning_rate': 0.09026281583636048, 'n_estimators': 1432, 'subsample': 0.6378020421245884, 'colsample_bytree': 0.6455289007495469, 'min_child_weight': 2, 'gamma': 2.6641923013854436, 'reg_alpha': 0.0003199032253055692, 'reg_lambda': 0.3053212616066735, 'max_delta_step': 3}. Best is trial 34 with value: 0.6256530214424951.

Best trial: 34. Best value: 0.625653:  36%|███▌      | 71/200 [00:52<01:28,  1.46it/s]

[I 2025-11-10 17:29:37,005] Trial 68 finished with value: 0.590916179337232 and parameters: {'max_depth': 5, 'learning_rate': 0.0509065538672965, 'n_estimators': 1321, 'subsample': 0.6397312452381645, 'colsample_bytree': 0.64803989831517, 'min_child_weight': 4, 'gamma': 2.9597943122484516, 'reg_alpha': 0.40578526436752127, 'reg_lambda': 0.0003763906528970051, 'max_delta_step': 3}. Best is trial 34 with value: 0.6256530214424951.

Best trial: 34. Best value: 0.625653:  36%|███▌      | 72/200 [00:52<01:15,  1.69it/s]

[I 2025-11-10 17:29:37,313] Trial 72 pruned.
[I 2025-11-10 17:29:37,408] Trial 73 pruned.

Best trial: 34. Best value: 0.625653:  37%|███▋      | 74/200 [00:53<00:58,  2.14it/s]

[I 2025-11-10 17:29:37,892] Trial 74 pruned.

Best trial: 34. Best value: 0.625653:  38%|███▊      | 75/200 [00:53<01:00,  2.08it/s]

[I 2025-11-10 17:29:38,428] Trial 75 pruned.

Best trial: 34. Best value: 0.625653:  38%|███▊      | 76/200 [00:54<00:57,  2.14it/s]

[I 2025-11-10 17:29:38,852] Trial 77 pruned.

Best trial: 34. Best value: 0.625653:  38%|███▊      | 77/200 [00:54<01:03,  1.95it/s]

[I 2025-11-10 17:29:39,492] Trial 78 pruned.

Best trial: 34. Best value: 0.625653:  39%|███▉      | 78/200 [00:55<01:09,  1.75it/s]

[I 2025-11-10 17:29:40,231] Trial 80 pruned.

Best trial: 34. Best value: 0.625653:  40%|███▉      | 79/200 [00:56<01:00,  2.00it/s]

[I 2025-11-10 17:29:40,540] Trial 69 finished with value: 0.5803313840155945 and parameters: {'max_depth': 6, 'learning_rate': 0.06715164687970593, 'n_estimators': 1448, 'subsample': 0.632044051460471, 'colsample_bytree': 0.7320400866260336, 'min_child_weight': 4, 'gamma': 1.8810520738770813, 'reg_alpha': 0.012622355902961638, 'reg_lambda': 0.0005496307503674772, 'max_delta_step': 0}. Best is trial 34 with value: 0.6256530214424951.

Best trial: 34. Best value: 0.625653:  40%|████      | 80/200 [00:56<01:04,  1.86it/s]

[I 2025-11-10 17:29:41,170] Trial 81 pruned.

Best trial: 34. Best value: 0.625653:  40%|████      | 81/200 [00:57<01:05,  1.80it/s]

[I 2025-11-10 17:29:41,762] Trial 83 pruned.

Best trial: 34. Best value: 0.625653:  41%|████      | 82/200 [00:57<01:00,  1.94it/s]

[I 2025-11-10 17:29:42,179] Trial 76 finished with value: 0.5595711500974658 and parameters: {'max_depth': 10, 'learning_rate': 0.1539751774527606, 'n_estimators': 980, 'subsample': 0.7518458898881726, 'colsample_bytree': 0.9977702158237814, 'min_child_weight': 4, 'gamma': 0.8010000699000064, 'reg_alpha': 7.688978828746132e-05, 'reg_lambda': 0.0017146740277218322, 'max_delta_step': 4}. Best is trial 34 with value: 0.6256530214424951.

Best trial: 34. Best value: 0.625653:  42%|████▏     | 83/200 [00:59<01:45,  1.11it/s]

[I 2025-11-10 17:29:44,018] Trial 79 finished with value: 0.5982261208576999 and parameters: {'max_depth': 4, 'learning_rate': 0.019003515814270844, 'n_estimators': 1177, 'subsample': 0.6945394346537302, 'colsample_bytree': 0.7307926023640041, 'min_child_weight': 4, 'gamma': 3.0368904786851805, 'reg_alpha': 0.22470228641405648, 'reg_lambda': 0.007155128034235542, 'max_delta_step': 5}. Best is trial 34 with value: 0.6256530214424951.

Best trial: 34. Best value: 0.625653:  42%|████▏     | 84/200 [00:59<01:30,  1.28it/s]

[I 2025-11-10 17:29:44,504] Trial 82 finished with value: 0.5622807017543858 and parameters: {'max_depth': 9, 'learning_rate': 0.011608356749799832, 'n_estimators': 642, 'subsample': 0.6864731543597509, 'colsample_bytree': 0.9582040755140352, 'min_child_weight': 3, 'gamma': 3.0265687640016887, 'reg_alpha': 1.5078812770778263, 'reg_lambda': 0.0018308216238614714, 'max_delta_step': 6}. Best is trial 34 with value: 0.6256530214424951.

Best trial: 34. Best value: 0.625653:  42%|████▎     | 85/200 [01:00<01:37,  1.19it/s]

[I 2025-11-10 17:29:45,495] Trial 87 pruned.

Best trial: 84. Best value: 0.647076:  43%|████▎     | 86/200 [01:02<02:06,  1.11s/it]

[I 2025-11-10 17:29:47,223] Trial 84 finished with value: 0.6470760233918129 and parameters: {'max_depth': 5, 'learning_rate': 0.052642013365733833, 'n_estimators': 1296, 'subsample': 0.5991665828197229, 'colsample_bytree': 0.7941128672365816, 'min_child_weight': 4, 'gamma': 2.9278751107890546, 'reg_alpha': 0.05402474925678516, 'reg_lambda': 0.00021306793434402413, 'max_delta_step': 4}. Best is trial 84 with value: 0.6470760233918129.

Best trial: 84. Best value: 0.647076:  44%|████▎     | 87/200 [01:03<01:43,  1.09it/s]

[I 2025-11-10 17:29:47,700] Trial 85 finished with value: 0.5803118908382066 and parameters: {'max_depth': 5, 'learning_rate': 0.054129999528340154, 'n_estimators': 1260, 'subsample': 0.5986317112843969, 'colsample_bytree': 0.7887801149723599, 'min_child_weight': 3, 'gamma': 2.9966038547872134, 'reg_alpha': 0.46600573884610713, 'reg_lambda': 0.00021803378654211222, 'max_delta_step': 3}. Best is trial 84 with value: 0.6470760233918129.

Best trial: 84. Best value: 0.647076:  44%|████▍     | 88/200 [01:03<01:34,  1.19it/s]

[I 2025-11-10 17:29:48,348] Trial 90 pruned.

Best trial: 84. Best value: 0.647076:  44%|████▍     | 89/200 [01:04<01:12,  1.53it/s]

[I 2025-11-10 17:29:48,569] Trial 89 pruned.

Best trial: 84. Best value: 0.647076:  45%|████▌     | 90/200 [01:04<01:04,  1.71it/s]

[I 2025-11-10 17:29:49,005] Trial 92 pruned.

Best trial: 84. Best value: 0.647076:  46%|████▌     | 91/200 [01:05<01:11,  1.53it/s]

[I 2025-11-10 17:29:49,807] Trial 86 finished with value: 0.5797270955165692 and parameters: {'max_depth': 4, 'learning_rate': 0.017002117825582433, 'n_estimators': 1098, 'subsample': 0.6865343743632799, 'colsample_bytree': 0.7896482083079628, 'min_child_weight': 3, 'gamma': 2.8346126171494705, 'reg_alpha': 0.0913390153860324, 'reg_lambda': 0.04055498734164203, 'max_delta_step': 6}. Best is trial 84 with value: 0.6470760233918129.

Best trial: 84. Best value: 0.647076:  46%|████▌     | 92/200 [01:05<01:03,  1.71it/s]

[I 2025-11-10 17:29:50,227] Trial 93 pruned.

Best trial: 84. Best value: 0.647076:  47%|████▋     | 94/200 [01:06<00:49,  2.15it/s]

[I 2025-11-10 17:29:50,851] Trial 88 finished with value: 0.602280701754386 and parameters: {'max_depth': 3, 'learning_rate': 0.0311661489104555, 'n_estimators': 1201, 'subsample': 0.5971609074246315, 'colsample_bytree': 0.8680006098973166, 'min_child_weight': 4, 'gamma': 2.801579898938823, 'reg_alpha': 0.08923606769512318, 'reg_lambda': 0.0002222798871219529, 'max_delta_step': 5}. Best is trial 84 with value: 0.6470760233918129.
[I 2025-11-10 17:29:51,005] Trial 95 pruned.

Best trial: 84. Best value: 0.647076:  48%|████▊     | 95/200 [01:07<01:02,  1.67it/s]

[I 2025-11-10 17:29:51,925] Trial 96 pruned.

Best trial: 84. Best value: 0.647076:  48%|████▊     | 96/200 [01:07<00:54,  1.91it/s]

[I 2025-11-10 17:29:52,276] Trial 97 pruned.

Best trial: 84. Best value: 0.647076:  48%|████▊     | 97/200 [01:09<01:28,  1.16it/s]

[I 2025-11-10 17:29:53,918] Trial 91 finished with value: 0.6310038986354776 and parameters: {'max_depth': 4, 'learning_rate': 0.03246350263952888, 'n_estimators': 1282, 'subsample': 0.9383304115710911, 'colsample_bytree': 0.7925608172990884, 'min_child_weight': 5, 'gamma': 2.845508948346454, 'reg_alpha': 0.14846658722038958, 'reg_lambda': 0.04644135406000223, 'max_delta_step': 4}. Best is trial 84 with value: 0.6470760233918129.

Best trial: 84. Best value: 0.647076:  49%|████▉     | 98/200 [01:10<01:40,  1.01it/s]

[I 2025-11-10 17:29:55,197] Trial 94 finished with value: 0.6226705653021443 and parameters: {'max_depth': 5, 'learning_rate': 0.1816969010642027, 'n_estimators': 1201, 'subsample': 0.899144298118486, 'colsample_bytree': 0.8128616221245896, 'min_child_weight': 4, 'gamma': 3.3462025454993776, 'reg_alpha': 0.04838344155220508, 'reg_lambda': 2.7681081900666866e-06, 'max_delta_step': 5}. Best is trial 84 with value: 0.6470760233918129.

Best trial: 84. Best value: 0.647076:  50%|████▉     | 99/200 [01:11<01:43,  1.03s/it]

[I 2025-11-10 17:29:56,315] Trial 101 pruned.

Best trial: 84. Best value: 0.647076:  50%|█████     | 100/200 [01:12<01:42,  1.03s/it]

[I 2025-11-10 17:29:57,353] Trial 98 finished with value: 0.621803118908382 and parameters: {'max_depth': 3, 'learning_rate': 0.043183233515052544, 'n_estimators': 1163, 'subsample': 0.9389608084827612, 'colsample_bytree': 0.8949857831421704, 'min_child_weight': 5, 'gamma': 2.601526220684192, 'reg_alpha': 0.1731474771518769, 'reg_lambda': 0.0003229167533026337, 'max_delta_step': 4}. Best is trial 84 with value: 0.6470760233918129.

Best trial: 84. Best value: 0.647076:  50%|█████     | 101/200 [01:13<01:35,  1.04it/s]

[I 2025-11-10 17:29:58,158] Trial 99 finished with value: 0.6286549707602338 and parameters: {'max_depth': 4, 'learning_rate': 0.044430603436290336, 'n_estimators': 1319, 'subsample': 0.9274581119476927, 'colsample_bytree': 0.7623465511726144, 'min_child_weight': 5, 'gamma': 2.5781093137264195, 'reg_alpha': 5.037766510939311e-08, 'reg_lambda': 0.16642376382395832, 'max_delta_step': 6}. Best is trial 84 with value: 0.6470760233918129.

Best trial: 84. Best value: 0.647076:  51%|█████     | 102/200 [01:15<02:03,  1.26s/it]

[I 2025-11-10 17:30:00,121] Trial 100 finished with value: 0.6277485380116958 and parameters: {'max_depth': 3, 'learning_rate': 0.04239270491310067, 'n_estimators': 1162, 'subsample': 0.9430655614967626, 'colsample_bytree': 0.724877347244368, 'min_child_weight': 5, 'gamma': 2.7181834768470843, 'reg_alpha': 0.174961847884582, 'reg_lambda': 0.5700584236695009, 'max_delta_step': 4}. Best is trial 84 with value: 0.6470760233918129.

Best trial: 84. Best value: 0.647076:  52%|█████▏    | 103/200 [01:16<01:54,  1.18s/it]

[I 2025-11-10 17:30:01,104] Trial 105 pruned.

Best trial: 84. Best value: 0.647076:  52%|█████▏    | 104/200 [01:18<02:05,  1.31s/it]

[I 2025-11-10 17:30:02,710] Trial 102 finished with value: 0.6233528265107212 and parameters: {'max_depth': 5, 'learning_rate': 0.0426219309723582, 'n_estimators': 1137, 'subsample': 0.9292564554028745, 'colsample_bytree': 0.8100635547618376, 'min_child_weight': 5, 'gamma': 2.709184609276793, 'reg_alpha': 0.05906254667476794, 'reg_lambda': 0.1615644549343691, 'max_delta_step': 4}. Best is trial 84 with value: 0.6470760233918129.

Best trial: 84. Best value: 0.647076:  52%|█████▎    | 105/200 [01:19<01:52,  1.19s/it]

[I 2025-11-10 17:30:03,625] Trial 103 finished with value: 0.6217251461988305 and parameters: {'max_depth': 3, 'learning_rate': 0.042046716595303485, 'n_estimators': 1126, 'subsample': 0.9332681299475784, 'colsample_bytree': 0.8485241835428416, 'min_child_weight': 5, 'gamma': 2.054542058543002, 'reg_alpha': 0.03196492427581037, 'reg_lambda': 8.14743940382709e-05, 'max_delta_step': 4}. Best is trial 84 with value: 0.6470760233918129.

Best trial: 84. Best value: 0.647076:  53%|█████▎    | 106/200 [01:19<01:34,  1.01s/it]

[I 2025-11-10 17:30:04,200] Trial 104 finished with value: 0.6297660818713451 and parameters: {'max_depth': 3, 'learning_rate': 0.04353882137213396, 'n_estimators': 1150, 'subsample': 0.9318310427515611, 'colsample_bytree': 0.8081815434231852, 'min_child_weight': 5, 'gamma': 2.7209200383066627, 'reg_alpha': 0.06063887191605331, 'reg_lambda': 0.0002948935049181745, 'max_delta_step': 6}. Best is trial 84 with value: 0.6470760233918129.

Best trial: 84. Best value: 0.647076:  54%|█████▎    | 107/200 [01:20<01:22,  1.13it/s]

[I 2025-11-10 17:30:04,809] Trial 108 pruned.

Best trial: 84. Best value: 0.647076:  54%|█████▍    | 108/200 [01:21<01:24,  1.09it/s]

[I 2025-11-10 17:30:05,805] Trial 110 pruned.

Best trial: 84. Best value: 0.647076:  55%|█████▍    | 109/200 [01:22<01:24,  1.07it/s]

[I 2025-11-10 17:30:06,764] Trial 106 finished with value: 0.6215497076023391 and parameters: {'max_depth': 3, 'learning_rate': 0.056810576266971585, 'n_estimators': 1256, 'subsample': 0.9264125998400645, 'colsample_bytree': 0.7630991771312301, 'min_child_weight': 5, 'gamma': 2.6001364074690505, 'reg_alpha': 0.0010358635539640918, 'reg_lambda': 5.000687420188177e-06, 'max_delta_step': 4}. Best is trial 84 with value: 0.6470760233918129.

Best trial: 107. Best value: 0.648051:  55%|█████▌    | 110/200 [01:23<01:26,  1.04it/s]

[I 2025-11-10 17:30:07,794] Trial 107 finished with value: 0.6480506822612087 and parameters: {'max_depth': 5, 'learning_rate': 0.2994308800057562, 'n_estimators': 1144, 'subsample': 0.9348080009461258, 'colsample_bytree': 0.8150005963467464, 'min_child_weight': 5, 'gamma': 2.681234938442508, 'reg_alpha': 0.06109788152221002, 'reg_lambda': 0.1605667564882204, 'max_delta_step': 3}. Best is trial 107 with value: 0.6480506822612087.

Best trial: 109. Best value: 0.673684:  56%|█████▌    | 111/200 [01:24<01:37,  1.10s/it]

[I 2025-11-10 17:30:09,229] Trial 109 finished with value: 0.6736842105263158 and parameters: {'max_depth': 3, 'learning_rate': 0.2948387283717553, 'n_estimators': 1144, 'subsample': 0.9280793307761669, 'colsample_bytree': 0.8091529718493007, 'min_child_weight': 5, 'gamma': 2.1719880475459252, 'reg_alpha': 0.06286666280233282, 'reg_lambda': 4.475354391821432, 'max_delta_step': 4}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  56%|█████▌    | 112/200 [01:26<01:48,  1.24s/it]

[I 2025-11-10 17:30:10,777] Trial 111 finished with value: 0.6423099415204678 and parameters: {'max_depth': 3, 'learning_rate': 0.2983113040762226, 'n_estimators': 1153, 'subsample': 0.9473592326674162, 'colsample_bytree': 0.7982640814319918, 'min_child_weight': 5, 'gamma': 2.4172618568506956, 'reg_alpha': 0.9812259013580754, 'reg_lambda': 0.46078614563772907, 'max_delta_step': 3}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  56%|█████▋    | 113/200 [01:26<01:33,  1.08s/it]

[I 2025-11-10 17:30:11,477] Trial 112 finished with value: 0.630204678362573 and parameters: {'max_depth': 3, 'learning_rate': 0.03291981241507488, 'n_estimators': 1068, 'subsample': 0.9445900207383866, 'colsample_bytree': 0.7982211021027353, 'min_child_weight': 5, 'gamma': 2.430843268120979, 'reg_alpha': 5.448284403051028e-08, 'reg_lambda': 0.6225379962573473, 'max_delta_step': 6}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  57%|█████▋    | 114/200 [01:27<01:12,  1.19it/s]

[I 2025-11-10 17:30:11,783] Trial 115 pruned.

Best trial: 109. Best value: 0.673684:  57%|█████▊    | 115/200 [01:27<01:07,  1.25it/s]

[I 2025-11-10 17:30:12,471] Trial 116 pruned.

Best trial: 109. Best value: 0.673684:  58%|█████▊    | 116/200 [01:28<00:56,  1.50it/s]

[I 2025-11-10 17:30:12,829] Trial 117 pruned.
[I 2025-11-10 17:30:12,870] Trial 113 finished with value: 0.6258771929824561 and parameters: {'max_depth': 5, 'learning_rate': 0.03316275466300445, 'n_estimators': 1150, 'subsample': 0.9441067889560262, 'colsample_bytree': 0.8004602532242102, 'min_child_weight': 5, 'gamma': 2.9104358605583824, 'reg_alpha': 0.15399820753875018, 'reg_lambda': 0.1574677204817669, 'max_delta_step': 3}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  59%|█████▉    | 118/200 [01:29<00:43,  1.87it/s]

[I 2025-11-10 17:30:13,588] Trial 118 pruned.

Best trial: 109. Best value: 0.673684:  60%|█████▉    | 119/200 [01:29<00:38,  2.12it/s]

[I 2025-11-10 17:30:13,873] Trial 120 pruned.
[I 2025-11-10 17:30:13,885] Trial 119 pruned.

Best trial: 109. Best value: 0.673684:  60%|██████    | 121/200 [01:29<00:25,  3.08it/s]

[I 2025-11-10 17:30:14,103] Trial 114 finished with value: 0.6211988304093568 and parameters: {'max_depth': 3, 'learning_rate': 0.297333059206276, 'n_estimators': 1063, 'subsample': 0.9486657683850973, 'colsample_bytree': 0.7986858246043672, 'min_child_weight': 5, 'gamma': 2.3180639921148267, 'reg_alpha': 0.9830714823698563, 'reg_lambda': 0.5185368724733496, 'max_delta_step': 3}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  61%|██████    | 122/200 [01:30<00:29,  2.67it/s]

[I 2025-11-10 17:30:14,641] Trial 121 pruned.

Best trial: 109. Best value: 0.673684:  62%|██████▏   | 123/200 [01:30<00:27,  2.84it/s]

[I 2025-11-10 17:30:14,939] Trial 122 pruned.

Best trial: 109. Best value: 0.673684:  62%|██████▏   | 124/200 [01:32<01:03,  1.19it/s]

[I 2025-11-10 17:30:17,168] Trial 125 pruned.

Best trial: 109. Best value: 0.673684:  62%|██████▎   | 125/200 [01:35<01:39,  1.33s/it]

[I 2025-11-10 17:30:19,815] Trial 123 finished with value: 0.6605750487329436 and parameters: {'max_depth': 3, 'learning_rate': 0.22524673341310264, 'n_estimators': 1010, 'subsample': 0.9705845954385707, 'colsample_bytree': 0.8377768625044032, 'min_child_weight': 5, 'gamma': 2.157987129730765, 'reg_alpha': 1.7696627225490547, 'reg_lambda': 0.062164639375908284, 'max_delta_step': 3}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  63%|██████▎   | 126/200 [01:36<01:32,  1.25s/it]

[I 2025-11-10 17:30:20,844] Trial 124 finished with value: 0.6370077972709551 and parameters: {'max_depth': 5, 'learning_rate': 0.03499358153799, 'n_estimators': 1230, 'subsample': 0.9636784488539566, 'colsample_bytree': 0.8089988421836554, 'min_child_weight': 5, 'gamma': 2.914451834608731, 'reg_alpha': 0.33314196587184347, 'reg_lambda': 0.07466061432226535, 'max_delta_step': 3}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  64%|██████▎   | 127/200 [01:36<01:16,  1.05s/it]

[I 2025-11-10 17:30:21,386] Trial 126 finished with value: 0.6549512670565301 and parameters: {'max_depth': 5, 'learning_rate': 0.22096681446627817, 'n_estimators': 1228, 'subsample': 0.9692026160970433, 'colsample_bytree': 0.8082424762731023, 'min_child_weight': 5, 'gamma': 2.922426047451823, 'reg_alpha': 0.14577274628826528, 'reg_lambda': 0.07217578581540005, 'max_delta_step': 4}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  64%|██████▍   | 128/200 [01:38<01:18,  1.09s/it]

[I 2025-11-10 17:30:22,575] Trial 127 finished with value: 0.6244054580896686 and parameters: {'max_depth': 5, 'learning_rate': 0.038228374164225344, 'n_estimators': 1307, 'subsample': 0.9185923136218376, 'colsample_bytree': 0.8235529858044078, 'min_child_weight': 5, 'gamma': 2.697321962717855, 'reg_alpha': 0.06076556538154814, 'reg_lambda': 0.07225347724666277, 'max_delta_step': 4}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  64%|██████▍   | 129/200 [01:39<01:34,  1.33s/it]

[I 2025-11-10 17:30:24,511] Trial 128 finished with value: 0.6574269005847954 and parameters: {'max_depth': 3, 'learning_rate': 0.22361700326498116, 'n_estimators': 1107, 'subsample': 0.9645518625344456, 'colsample_bytree': 0.8280978473859371, 'min_child_weight': 5, 'gamma': 2.9272162632250405, 'reg_alpha': 1.2776741484570746, 'reg_lambda': 0.073578915983904, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  65%|██████▌   | 130/200 [01:40<01:25,  1.22s/it]

[I 2025-11-10 17:30:25,441] Trial 129 finished with value: 0.6558284600389863 and parameters: {'max_depth': 3, 'learning_rate': 0.20468657155668496, 'n_estimators': 1108, 'subsample': 0.9654368459144538, 'colsample_bytree': 0.8245207128931968, 'min_child_weight': 5, 'gamma': 2.933977277775308, 'reg_alpha': 0.5314084971010933, 'reg_lambda': 0.059555728694063184, 'max_delta_step': 3}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  66%|██████▌   | 131/200 [01:41<01:03,  1.09it/s]

[I 2025-11-10 17:30:25,656] Trial 132 pruned.

Best trial: 109. Best value: 0.673684:  66%|██████▌   | 132/200 [01:41<01:00,  1.13it/s]

[I 2025-11-10 17:30:26,453] Trial 133 pruned.

Best trial: 109. Best value: 0.673684:  66%|██████▋   | 133/200 [01:42<00:47,  1.40it/s]

[I 2025-11-10 17:30:26,776] Trial 130 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.1927335721301829, 'n_estimators': 1266, 'subsample': 0.9717646652147663, 'colsample_bytree': 0.8217406417616336, 'min_child_weight': 5, 'gamma': 2.9168627820484203, 'reg_alpha': 2.658620018252568, 'reg_lambda': 0.07209917140554799, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  67%|██████▋   | 134/200 [01:43<00:56,  1.16it/s]

[I 2025-11-10 17:30:27,979] Trial 131 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.20775178869965136, 'n_estimators': 1266, 'subsample': 0.9640129509483919, 'colsample_bytree': 0.8331018570931117, 'min_child_weight': 5, 'gamma': 2.8990667762934015, 'reg_alpha': 2.0508146183328253, 'reg_lambda': 0.0780268128634368, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  68%|██████▊   | 135/200 [01:44<00:59,  1.09it/s]

[I 2025-11-10 17:30:29,033] Trial 137 pruned.

Best trial: 109. Best value: 0.673684:  68%|██████▊   | 136/200 [01:45<00:59,  1.08it/s]

[I 2025-11-10 17:30:29,987] Trial 138 pruned.

Best trial: 109. Best value: 0.673684:  68%|██████▊   | 137/200 [01:46<00:53,  1.19it/s]

[I 2025-11-10 17:30:30,623] Trial 134 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.21448861305830827, 'n_estimators': 1105, 'subsample': 0.9829527588975276, 'colsample_bytree': 0.8438596210771497, 'min_child_weight': 5, 'gamma': 2.8656537570028657, 'reg_alpha': 1.8207277620783058, 'reg_lambda': 0.021259099417249135, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  69%|██████▉   | 138/200 [01:47<00:57,  1.07it/s]

[I 2025-11-10 17:30:31,766] Trial 135 finished with value: 0.6617543859649123 and parameters: {'max_depth': 3, 'learning_rate': 0.23439962306029938, 'n_estimators': 1227, 'subsample': 0.986333364058578, 'colsample_bytree': 0.7882161487104692, 'min_child_weight': 5, 'gamma': 2.5385706664843135, 'reg_alpha': 1.827513797416111, 'reg_lambda': 0.2690616152489123, 'max_delta_step': 3}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  70%|██████▉   | 139/200 [01:48<00:55,  1.11it/s]

[I 2025-11-10 17:30:32,601] Trial 136 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.202316344788466, 'n_estimators': 1341, 'subsample': 0.9879171128969443, 'colsample_bytree': 0.8262869083556706, 'min_child_weight': 5, 'gamma': 2.549835444312728, 'reg_alpha': 1.921049933104808, 'reg_lambda': 0.015110376229454433, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  70%|███████   | 140/200 [01:49<00:59,  1.01it/s]

[I 2025-11-10 17:30:33,793] Trial 142 pruned.

Best trial: 109. Best value: 0.673684:  70%|███████   | 141/200 [01:50<00:59,  1.02s/it]

[I 2025-11-10 17:30:34,863] Trial 143 pruned.

Best trial: 109. Best value: 0.673684:  71%|███████   | 142/200 [01:51<00:58,  1.01s/it]

[I 2025-11-10 17:30:35,884] Trial 139 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.2021969129110897, 'n_estimators': 1339, 'subsample': 0.9846123174175311, 'colsample_bytree': 0.8202310970034955, 'min_child_weight': 5, 'gamma': 3.085079167436754, 'reg_alpha': 1.9089574275704742, 'reg_lambda': 0.015167249863160403, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  72%|███████▏  | 143/200 [01:51<00:47,  1.19it/s]

[I 2025-11-10 17:30:36,298] Trial 140 finished with value: 0.6617543859649123 and parameters: {'max_depth': 3, 'learning_rate': 0.20538507979561774, 'n_estimators': 1279, 'subsample': 0.9846466261564807, 'colsample_bytree': 0.8453891231901866, 'min_child_weight': 5, 'gamma': 2.5082490897359397, 'reg_alpha': 2.1371784216169, 'reg_lambda': 0.031796089660581575, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  72%|███████▏  | 144/200 [01:52<00:51,  1.09it/s]

[I 2025-11-10 17:30:37,404] Trial 141 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.22537277420351748, 'n_estimators': 1270, 'subsample': 0.9836392626062314, 'colsample_bytree': 0.844169541915777, 'min_child_weight': 5, 'gamma': 2.8462665031437466, 'reg_alpha': 2.0492908917963226, 'reg_lambda': 0.01577274126262989, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  72%|███████▎  | 145/200 [01:55<01:23,  1.52s/it]

[I 2025-11-10 17:30:40,330] Trial 144 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.25945463136630126, 'n_estimators': 1280, 'subsample': 0.9598865865947118, 'colsample_bytree': 0.8594813116497436, 'min_child_weight': 5, 'gamma': 2.8783684351838965, 'reg_alpha': 2.0720479221382733, 'reg_lambda': 0.0576169851583533, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  73%|███████▎  | 146/200 [01:57<01:17,  1.43s/it]

[I 2025-11-10 17:30:41,549] Trial 145 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.16484013629017796, 'n_estimators': 1337, 'subsample': 0.9622932261016729, 'colsample_bytree': 0.8562716140162574, 'min_child_weight': 5, 'gamma': 3.2324169321965934, 'reg_alpha': 1.9172410082758822, 'reg_lambda': 0.06896688766656614, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  74%|███████▎  | 147/200 [01:57<01:02,  1.19s/it]

[I 2025-11-10 17:30:42,165] Trial 146 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.26156689014600765, 'n_estimators': 1351, 'subsample': 0.9777201583513692, 'colsample_bytree': 0.8544894663785976, 'min_child_weight': 5, 'gamma': 3.1860859038809393, 'reg_alpha': 2.317175013926123, 'reg_lambda': 0.011632710936743798, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  74%|███████▍  | 148/200 [01:58<00:57,  1.11s/it]

[I 2025-11-10 17:30:43,102] Trial 147 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.21232704503620872, 'n_estimators': 1336, 'subsample': 0.9869243988102542, 'colsample_bytree': 0.8601371065923491, 'min_child_weight': 5, 'gamma': 3.2401412153702043, 'reg_alpha': 1.8174856615347112, 'reg_lambda': 0.012009866691452441, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  74%|███████▍  | 149/200 [02:01<01:27,  1.72s/it]

[I 2025-11-10 17:30:46,257] Trial 148 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.2564089478460948, 'n_estimators': 1402, 'subsample': 0.9885043982088954, 'colsample_bytree': 0.8790863339811434, 'min_child_weight': 5, 'gamma': 3.1373119439964667, 'reg_alpha': 1.9983684989988026, 'reg_lambda': 0.018862149062651903, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  75%|███████▌  | 150/200 [02:02<01:17,  1.56s/it]

[I 2025-11-10 17:30:47,414] Trial 152 pruned.
[I 2025-11-10 17:30:47,421] Trial 149 finished with value: 0.6662573099415205 and parameters: {'max_depth': 3, 'learning_rate': 0.16747437390218978, 'n_estimators': 1392, 'subsample': 0.9744176501964448, 'colsample_bytree': 0.8795814622967938, 'min_child_weight': 5, 'gamma': 3.2193378123263185, 'reg_alpha': 1.6558996540508484, 'reg_lambda': 0.01226110013227952, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  76%|███████▌  | 152/200 [02:03<00:46,  1.03it/s]

[I 2025-11-10 17:30:47,978] Trial 150 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.17037681777456057, 'n_estimators': 1335, 'subsample': 0.9865306695149113, 'colsample_bytree': 0.8786649877334316, 'min_child_weight': 5, 'gamma': 3.242748487785879, 'reg_alpha': 1.90489027137025, 'reg_lambda': 0.012026311439548671, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  76%|███████▋  | 153/200 [02:04<00:46,  1.02it/s]

[I 2025-11-10 17:30:49,002] Trial 151 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.25588413975406704, 'n_estimators': 1397, 'subsample': 0.9865163319979865, 'colsample_bytree': 0.8770900100123445, 'min_child_weight': 5, 'gamma': 3.201307261271145, 'reg_alpha': 1.7425743882641331, 'reg_lambda': 0.016050721320023616, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  77%|███████▋  | 154/200 [02:04<00:36,  1.26it/s]

[I 2025-11-10 17:30:49,257] Trial 155 pruned.

Best trial: 109. Best value: 0.673684:  78%|███████▊  | 155/200 [02:05<00:38,  1.18it/s]

[I 2025-11-10 17:30:50,267] Trial 156 pruned.

Best trial: 109. Best value: 0.673684:  78%|███████▊  | 156/200 [02:06<00:30,  1.44it/s]

[I 2025-11-10 17:30:50,552] Trial 157 pruned.

Best trial: 109. Best value: 0.673684:  78%|███████▊  | 157/200 [02:07<00:33,  1.28it/s]

[I 2025-11-10 17:30:51,554] Trial 158 pruned.

Best trial: 109. Best value: 0.673684:  79%|███████▉  | 158/200 [02:07<00:25,  1.62it/s]

[I 2025-11-10 17:30:51,779] Trial 159 pruned.

Best trial: 109. Best value: 0.673684:  80%|███████▉  | 159/200 [02:08<00:33,  1.22it/s]

[I 2025-11-10 17:30:53,080] Trial 161 pruned.

Best trial: 109. Best value: 0.673684:  80%|████████  | 160/200 [02:08<00:27,  1.45it/s]

[I 2025-11-10 17:30:53,469] Trial 153 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.16456131197752027, 'n_estimators': 1341, 'subsample': 0.9786322203530105, 'colsample_bytree': 0.870425917132424, 'min_child_weight': 5, 'gamma': 3.446096656026234, 'reg_alpha': 2.152704213339118, 'reg_lambda': 0.011734083255201038, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  80%|████████  | 161/200 [02:09<00:22,  1.76it/s]

[I 2025-11-10 17:30:53,742] Trial 154 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.1699452422765447, 'n_estimators': 1386, 'subsample': 0.9784995266055514, 'colsample_bytree': 0.8648704816980578, 'min_child_weight': 5, 'gamma': 3.4606830637115893, 'reg_alpha': 2.259488806075732, 'reg_lambda': 0.013393640107781138, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  81%|████████  | 162/200 [02:09<00:22,  1.69it/s]

[I 2025-11-10 17:30:54,389] Trial 162 pruned.

Best trial: 109. Best value: 0.673684:  82%|████████▏ | 163/200 [02:10<00:19,  1.87it/s]

[I 2025-11-10 17:30:54,782] Trial 163 pruned.

Best trial: 109. Best value: 0.673684:  82%|████████▏ | 164/200 [02:10<00:16,  2.22it/s]

[I 2025-11-10 17:30:55,041] Trial 164 pruned.

Best trial: 109. Best value: 0.673684:  82%|████████▎ | 165/200 [02:11<00:22,  1.57it/s]

[I 2025-11-10 17:30:56,122] Trial 166 pruned.

Best trial: 109. Best value: 0.673684:  83%|████████▎ | 166/200 [02:13<00:31,  1.09it/s]

[I 2025-11-10 17:30:57,676] Trial 160 finished with value: 0.6692397660818714 and parameters: {'max_depth': 3, 'learning_rate': 0.27438693007753645, 'n_estimators': 1330, 'subsample': 0.9877491430237324, 'colsample_bytree': 0.8893435958457576, 'min_child_weight': 5, 'gamma': 3.1260809730124564, 'reg_alpha': 1.1654436231982332, 'reg_lambda': 0.00989485009298161, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  84%|████████▎ | 167/200 [02:16<00:51,  1.56s/it]

[I 2025-11-10 17:31:00,751] Trial 165 finished with value: 0.6639766081871346 and parameters: {'max_depth': 3, 'learning_rate': 0.1625960619006836, 'n_estimators': 1418, 'subsample': 0.9725774691835093, 'colsample_bytree': 0.8722135098117344, 'min_child_weight': 5, 'gamma': 3.743079601164845, 'reg_alpha': 0.6917954010735298, 'reg_lambda': 0.018452854775322627, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  84%|████████▍ | 168/200 [02:16<00:40,  1.27s/it]

[I 2025-11-10 17:31:01,348] Trial 167 finished with value: 0.6584795321637428 and parameters: {'max_depth': 3, 'learning_rate': 0.16599378876003662, 'n_estimators': 1424, 'subsample': 0.9770817620161572, 'colsample_bytree': 0.8585552137548639, 'min_child_weight': 5, 'gamma': 3.7338684894427847, 'reg_alpha': 0.643916867220838, 'reg_lambda': 0.018054021432330442, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  84%|████████▍ | 169/200 [02:17<00:34,  1.12s/it]

[I 2025-11-10 17:31:02,119] Trial 168 finished with value: 0.6648538011695907 and parameters: {'max_depth': 3, 'learning_rate': 0.16406898770240358, 'n_estimators': 1370, 'subsample': 0.9747890013027127, 'colsample_bytree': 0.8647037383567564, 'min_child_weight': 5, 'gamma': 3.4313293448328674, 'reg_alpha': 0.7206206642066992, 'reg_lambda': 0.00924681524525875, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  85%|████████▌ | 170/200 [02:18<00:27,  1.07it/s]

[I 2025-11-10 17:31:02,607] Trial 171 pruned.

Best trial: 109. Best value: 0.673684:  86%|████████▌ | 171/200 [02:18<00:24,  1.17it/s]

[I 2025-11-10 17:31:03,274] Trial 172 pruned.

Best trial: 109. Best value: 0.673684:  86%|████████▌ | 172/200 [02:19<00:20,  1.34it/s]

[I 2025-11-10 17:31:03,771] Trial 169 finished with value: 0.6725730994152047 and parameters: {'max_depth': 3, 'learning_rate': 0.2640567369840695, 'n_estimators': 1371, 'subsample': 0.9919524560208458, 'colsample_bytree': 0.8666120619799041, 'min_child_weight': 5, 'gamma': 3.031192175177419, 'reg_alpha': 0.653641253332992, 'reg_lambda': 0.02548288543492343, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  86%|████████▋ | 173/200 [02:22<00:39,  1.45s/it]

[I 2025-11-10 17:31:06,863] Trial 170 finished with value: 0.6328654970760235 and parameters: {'max_depth': 3, 'learning_rate': 0.27495962782107525, 'n_estimators': 1379, 'subsample': 0.9907125836263244, 'colsample_bytree': 0.856714351244494, 'min_child_weight': 5, 'gamma': 3.4768614416122614, 'reg_alpha': 2.6049865238043255, 'reg_lambda': 0.008477568441494327, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  87%|████████▋ | 174/200 [02:23<00:35,  1.38s/it]

[I 2025-11-10 17:31:08,082] Trial 173 finished with value: 0.6617543859649123 and parameters: {'max_depth': 3, 'learning_rate': 0.21001040376179028, 'n_estimators': 1307, 'subsample': 0.9989240083443017, 'colsample_bytree': 0.8909711780633193, 'min_child_weight': 5, 'gamma': 3.0606144357422393, 'reg_alpha': 1.1291119269171315, 'reg_lambda': 0.005586197832379877, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  88%|████████▊ | 175/200 [02:24<00:34,  1.36s/it]

[I 2025-11-10 17:31:09,404] Trial 175 finished with value: 0.6639766081871346 and parameters: {'max_depth': 3, 'learning_rate': 0.25550105587513966, 'n_estimators': 1325, 'subsample': 0.9991644198683693, 'colsample_bytree': 0.8494389159916196, 'min_child_weight': 5, 'gamma': 3.0893888430107332, 'reg_alpha': 1.2707742687023336, 'reg_lambda': 0.027734525399364964, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.
[I 2025-11-10 17:31:09,447] Trial 174 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.20534208023145975, 'n_estimators': 1458, 'subsample': 0.999751051053092, 'colsample_bytree': 0.8838951446650783, 'min_child_weight': 5, 'gamma': 3.236141780436847, 'reg_alpha': 1.577141968467253, 'reg_lambda': 0.012639509049255692, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  88%|████████▊ | 177/200 [02:26<00:23,  1.03s/it]

[I 2025-11-10 17:31:10,702] Trial 179 pruned.
[I 2025-11-10 17:31:10,744] Trial 178 pruned.

Best trial: 109. Best value: 0.673684:  90%|████████▉ | 179/200 [02:28<00:21,  1.05s/it]

[I 2025-11-10 17:31:12,832] Trial 176 finished with value: 0.6595321637426901 and parameters: {'max_depth': 3, 'learning_rate': 0.21156382761143955, 'n_estimators': 1323, 'subsample': 0.9974538570408312, 'colsample_bytree': 0.8852821319822185, 'min_child_weight': 5, 'gamma': 3.091452584186885, 'reg_alpha': 1.170720015972481, 'reg_lambda': 0.027049995703296418, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  90%|█████████ | 181/200 [02:29<00:15,  1.21it/s]

[I 2025-11-10 17:31:13,903] Trial 177 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.25107414242418025, 'n_estimators': 1336, 'subsample': 0.9608876704290013, 'colsample_bytree': 0.8432033365302113, 'min_child_weight': 5, 'gamma': 3.2642113693440566, 'reg_alpha': 1.503585615636613, 'reg_lambda': 0.03004436359174767, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.
[I 2025-11-10 17:31:14,015] Trial 182 pruned.

Best trial: 109. Best value: 0.673684:  91%|█████████ | 182/200 [02:31<00:21,  1.22s/it]

[I 2025-11-10 17:31:16,366] Trial 180 finished with value: 0.6639766081871346 and parameters: {'max_depth': 3, 'learning_rate': 0.24824917458660728, 'n_estimators': 1269, 'subsample': 0.984956469813491, 'colsample_bytree': 0.8693010355266634, 'min_child_weight': 5, 'gamma': 3.16163741062332, 'reg_alpha': 0.9521257867552965, 'reg_lambda': 0.023070934450466977, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.
[I 2025-11-10 17:31:16,380] Trial 181 finished with value: 0.6574269005847954 and parameters: {'max_depth': 3, 'learning_rate': 0.22148748500691462, 'n_estimators': 1274, 'subsample': 0.9654663394220184, 'colsample_bytree': 0.9072326228066573, 'min_child_weight': 5, 'gamma': 3.180228440532135, 'reg_alpha': 1.0747312416785928, 'reg_lambda': 0.023366655357191853, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  92%|█████████▏| 184/200 [02:34<00:21,  1.33s/it]

[I 2025-11-10 17:31:19,341] Trial 183 finished with value: 0.6659649122807018 and parameters: {'max_depth': 3, 'learning_rate': 0.23381106599708057, 'n_estimators': 1270, 'subsample': 0.9835801023799048, 'colsample_bytree': 0.8648458368868838, 'min_child_weight': 5, 'gamma': 2.7817543397574633, 'reg_alpha': 0.43386786647775505, 'reg_lambda': 0.01470872555443142, 'max_delta_step': 1}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  92%|█████████▎| 185/200 [02:35<00:18,  1.25s/it]

[I 2025-11-10 17:31:20,325] Trial 184 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.21074292064405084, 'n_estimators': 1465, 'subsample': 0.9863680280450946, 'colsample_bytree': 0.8642823779552481, 'min_child_weight': 5, 'gamma': 3.164175996088297, 'reg_alpha': 1.825591400554669, 'reg_lambda': 0.014154144001302183, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  93%|█████████▎| 186/200 [02:36<00:17,  1.23s/it]

[I 2025-11-10 17:31:21,511] Trial 188 pruned.

Best trial: 109. Best value: 0.673684:  94%|█████████▍| 188/200 [02:38<00:10,  1.13it/s]

[I 2025-11-10 17:31:22,489] Trial 185 finished with value: 0.6662573099415205 and parameters: {'max_depth': 3, 'learning_rate': 0.20368376118480952, 'n_estimators': 1454, 'subsample': 0.9729962584002642, 'colsample_bytree': 0.8831065731823122, 'min_child_weight': 5, 'gamma': 3.021210781188039, 'reg_alpha': 2.0274273864766, 'reg_lambda': 0.01399171492102964, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.
[I 2025-11-10 17:31:22,621] Trial 186 finished with value: 0.6662573099415205 and parameters: {'max_depth': 3, 'learning_rate': 0.20075307469330478, 'n_estimators': 1481, 'subsample': 0.9731643606617109, 'colsample_bytree': 0.8837869577102937, 'min_child_weight': 5, 'gamma': 3.0037805636004116, 'reg_alpha': 1.8441771631567665, 'reg_lambda': 0.015258303084211819, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  94%|█████████▍| 189/200 [02:39<00:10,  1.04it/s]

[I 2025-11-10 17:31:23,763] Trial 191 pruned.

Best trial: 109. Best value: 0.673684:  95%|█████████▌| 190/200 [02:40<00:10,  1.07s/it]

[I 2025-11-10 17:31:25,129] Trial 192 pruned.

Best trial: 109. Best value: 0.673684:  96%|█████████▌| 191/200 [02:41<00:08,  1.10it/s]

[I 2025-11-10 17:31:25,633] Trial 187 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.1983988356693847, 'n_estimators': 1456, 'subsample': 0.9720651575110268, 'colsample_bytree': 0.8816556504464106, 'min_child_weight': 5, 'gamma': 3.0421661502710613, 'reg_alpha': 1.9362849055009352, 'reg_lambda': 0.00503973131809202, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  96%|█████████▌| 192/200 [02:41<00:07,  1.12it/s]

[I 2025-11-10 17:31:26,483] Trial 193 pruned.

Best trial: 109. Best value: 0.673684:  96%|█████████▋| 193/200 [02:42<00:05,  1.35it/s]

[I 2025-11-10 17:31:26,875] Trial 194 pruned.

Best trial: 109. Best value: 0.673684:  97%|█████████▋| 194/200 [02:43<00:04,  1.31it/s]

[I 2025-11-10 17:31:27,679] Trial 189 finished with value: 0.6328654970760235 and parameters: {'max_depth': 3, 'learning_rate': 0.27978831440871166, 'n_estimators': 1364, 'subsample': 0.9732676291348317, 'colsample_bytree': 0.8515590705579954, 'min_child_weight': 5, 'gamma': 3.0051846180017217, 'reg_alpha': 2.7742596128287134, 'reg_lambda': 0.007520665930386311, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.
[I 2025-11-10 17:31:27,746] Trial 195 pruned.

Best trial: 109. Best value: 0.673684:  98%|█████████▊| 196/200 [02:44<00:02,  1.59it/s]

[I 2025-11-10 17:31:28,627] Trial 190 finished with value: 0.6328654970760235 and parameters: {'max_depth': 3, 'learning_rate': 0.2806601964749887, 'n_estimators': 1364, 'subsample': 0.9528710979233124, 'colsample_bytree': 0.8504114655137877, 'min_child_weight': 5, 'gamma': 3.259597508304581, 'reg_alpha': 2.64263215525447, 'reg_lambda': 0.007248375325073268, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684:  98%|█████████▊| 197/200 [02:44<00:01,  1.76it/s]

[I 2025-11-10 17:31:29,003] Trial 197 pruned.

Best trial: 109. Best value: 0.673684:  99%|█████████▉| 198/200 [02:47<00:02,  1.15s/it]

[I 2025-11-10 17:31:31,815] Trial 196 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.22370756359867228, 'n_estimators': 1346, 'subsample': 0.9630554707527545, 'colsample_bytree': 0.8445881218543827, 'min_child_weight': 5, 'gamma': 3.395651792564892, 'reg_alpha': 1.4180049927089302, 'reg_lambda': 0.04212150572654474, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684: 100%|█████████▉| 199/200 [02:47<00:00,  1.01it/s]

[I 2025-11-10 17:31:32,365] Trial 198 finished with value: 0.6639766081871346 and parameters: {'max_depth': 3, 'learning_rate': 0.2539813644576374, 'n_estimators': 1394, 'subsample': 0.9851010777461447, 'colsample_bytree': 0.8363117536651942, 'min_child_weight': 5, 'gamma': 3.5133000248572497, 'reg_alpha': 0.5006392802655234, 'reg_lambda': 0.02603744971433236, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

Best trial: 109. Best value: 0.673684: 100%|██████████| 200/200 [02:48<00:00,  1.19it/s]

[I 2025-11-10 17:31:32,628] Trial 199 finished with value: 0.6639766081871346 and parameters: {'max_depth': 3, 'learning_rate': 0.18253294252550692, 'n_estimators': 1299, 'subsample': 0.9833800149514299, 'colsample_bytree': 0.8723936866036692, 'min_child_weight': 5, 'gamma': 3.153901824723929, 'reg_alpha': 1.4386492519493728, 'reg_lambda': 0.028545101133853275, 'max_delta_step': 2}. Best is trial 109 with value: 0.6736842105263158.

[I 2025-11-10 17:31:33,715] A new study created in memory with name: 3_4_roc_auc
Best trial: 3. Best value: 0.547544:   0%|          | 1/200 [00:03<11:09,  3.37s/it]

[I 2025-11-10 17:31:37,076] Trial 3 finished with value: 0.5475438596491229 and parameters: {'max_depth': 3, 'learning_rate': 0.010458428270683627, 'n_estimators': 604, 'subsample': 0.8478861310116526, 'colsample_bytree': 0.6971293514189791, 'min_child_weight': 3, 'gamma': 4.9473386500865, 'reg_alpha': 8.722097989210224e-06, 'reg_lambda': 0.0012612042542969092, 'max_delta_step': 5}. Best is trial 3 with value: 0.5475438596491229.

Best trial: 3. Best value: 0.547544:   1%|          | 2/200 [00:04<06:27,  1.95s/it]

[I 2025-11-10 17:31:38,049] Trial 1 finished with value: 0.4818713450292397 and parameters: {'max_depth': 4, 'learning_rate': 0.06039373767748547, 'n_estimators': 1071, 'subsample': 0.7715693878836766, 'colsample_bytree': 0.5238081998908457, 'min_child_weight': 4, 'gamma': 3.8407172368888656, 'reg_alpha': 0.05161784441216862, 'reg_lambda': 0.1135456697493989, 'max_delta_step': 1}. Best is trial 3 with value: 0.5475438596491229.

Best trial: 3. Best value: 0.547544:   2%|▏         | 3/200 [00:05<05:27,  1.66s/it]

[I 2025-11-10 17:31:39,356] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.028942666396223858, 'n_estimators': 1412, 'subsample': 0.5725232894249739, 'colsample_bytree': 0.5367560032731518, 'min_child_weight': 9, 'gamma': 0.2155826534700206, 'reg_alpha': 0.8376774309801265, 'reg_lambda': 5.472698141795787e-08, 'max_delta_step': 0}. Best is trial 3 with value: 0.5475438596491229.

Best trial: 3. Best value: 0.547544:   2%|▏         | 4/200 [00:06<03:46,  1.16s/it]

[I 2025-11-10 17:31:39,734] Trial 0 finished with value: 0.5280409356725146 and parameters: {'max_depth': 6, 'learning_rate': 0.1181784389315391, 'n_estimators': 1367, 'subsample': 0.918993845784389, 'colsample_bytree': 0.5867591762428337, 'min_child_weight': 4, 'gamma': 3.8655801911363197, 'reg_alpha': 1.8798256163753038e-07, 'reg_lambda': 0.6196102531186247, 'max_delta_step': 9}. Best is trial 3 with value: 0.5475438596491229.

Best trial: 3. Best value: 0.547544:   2%|▎         | 5/200 [00:10<07:24,  2.28s/it]

[I 2025-11-10 17:31:44,008] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.02256261071947754, 'n_estimators': 1393, 'subsample': 0.6357235670805271, 'colsample_bytree': 0.86905190066679, 'min_child_weight': 6, 'gamma': 0.7567665323324707, 'reg_alpha': 1.5617030050390054e-07, 'reg_lambda': 0.012039778581378325, 'max_delta_step': 6}. Best is trial 3 with value: 0.5475438596491229.

Best trial: 3. Best value: 0.547544:   3%|▎         | 6/200 [00:11<05:58,  1.85s/it]

[I 2025-11-10 17:31:45,027] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.032912648025035796, 'n_estimators': 1121, 'subsample': 0.7519322529150607, 'colsample_bytree': 0.8497068197474495, 'min_child_weight': 5, 'gamma': 0.5502671853936875, 'reg_alpha': 0.29049513050997877, 'reg_lambda': 2.1541939026674413e-08, 'max_delta_step': 2}. Best is trial 3 with value: 0.5475438596491229.

Best trial: 3. Best value: 0.547544:   4%|▎         | 7/200 [00:11<04:16,  1.33s/it]

[I 2025-11-10 17:31:45,284] Trial 5 finished with value: 0.5471539961013645 and parameters: {'max_depth': 7, 'learning_rate': 0.1631406163075046, 'n_estimators': 1316, 'subsample': 0.9616216967746392, 'colsample_bytree': 0.9529934281277603, 'min_child_weight': 3, 'gamma': 1.2779927448749862, 'reg_alpha': 0.0003430895000403863, 'reg_lambda': 6.90139623125655e-06, 'max_delta_step': 10}. Best is trial 3 with value: 0.5475438596491229.

Best trial: 3. Best value: 0.547544:   4%|▍         | 8/200 [00:12<03:20,  1.04s/it]

[I 2025-11-10 17:31:45,716] Trial 7 finished with value: 0.5094152046783625 and parameters: {'max_depth': 10, 'learning_rate': 0.13719278775843474, 'n_estimators': 1197, 'subsample': 0.6198253323484232, 'colsample_bytree': 0.7347011027397017, 'min_child_weight': 3, 'gamma': 3.158369045613602, 'reg_alpha': 2.5467099006739495e-07, 'reg_lambda': 2.7735505085108973e-08, 'max_delta_step': 10}. Best is trial 3 with value: 0.5475438596491229.

Best trial: 3. Best value: 0.547544:   4%|▍         | 9/200 [00:13<03:55,  1.23s/it]

[I 2025-11-10 17:31:47,358] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.18154338743200574, 'n_estimators': 398, 'subsample': 0.971069575061419, 'colsample_bytree': 0.5898362769239962, 'min_child_weight': 1, 'gamma': 4.810282442335979, 'reg_alpha': 5.7754613693848444, 'reg_lambda': 5.412470278138692, 'max_delta_step': 0}. Best is trial 3 with value: 0.5475438596491229.

Best trial: 3. Best value: 0.547544:   5%|▌         | 10/200 [00:14<03:04,  1.03it/s]

[I 2025-11-10 17:31:47,741] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.039020644385592364, 'n_estimators': 605, 'subsample': 0.9317083477998531, 'colsample_bytree': 0.6701336389360477, 'min_child_weight': 7, 'gamma': 2.629493585876779, 'reg_alpha': 1.6012727212935696, 'reg_lambda': 8.712430075516261e-05, 'max_delta_step': 10}. Best is trial 3 with value: 0.5475438596491229.

Best trial: 3. Best value: 0.547544:   6%|▌         | 11/200 [00:15<03:31,  1.12s/it]

[I 2025-11-10 17:31:49,203] Trial 12 finished with value: 0.4917056530214425 and parameters: {'max_depth': 4, 'learning_rate': 0.2572431595551209, 'n_estimators': 406, 'subsample': 0.6556019858892252, 'colsample_bytree': 0.9228013750722852, 'min_child_weight': 4, 'gamma': 4.231391257349641, 'reg_alpha': 4.3231511573891864e-05, 'reg_lambda': 1.2611811385335029e-05, 'max_delta_step': 1}. Best is trial 3 with value: 0.5475438596491229.

Best trial: 3. Best value: 0.547544:   6%|▌         | 12/200 [00:15<02:38,  1.19it/s]

[I 2025-11-10 17:31:49,421] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.03835196057446209, 'n_estimators': 1355, 'subsample': 0.5064089072620583, 'colsample_bytree': 0.6183533476196645, 'min_child_weight': 10, 'gamma': 1.2972575546436937, 'reg_alpha': 1.4573960058661789e-08, 'reg_lambda': 1.2909395912872607e-07, 'max_delta_step': 0}. Best is trial 3 with value: 0.5475438596491229.

Best trial: 13. Best value: 0.565673:   6%|▋         | 13/200 [00:16<02:22,  1.31it/s]

[I 2025-11-10 17:31:49,992] Trial 13 finished with value: 0.5656725146198831 and parameters: {'max_depth': 7, 'learning_rate': 0.012736924248209457, 'n_estimators': 202, 'subsample': 0.8434777251471874, 'colsample_bytree': 0.7185968541524299, 'min_child_weight': 1, 'gamma': 4.774619820915038, 'reg_alpha': 3.768198700689088e-05, 'reg_lambda': 0.0018174627651308276, 'max_delta_step': 4}. Best is trial 13 with value: 0.5656725146198831.

Best trial: 13. Best value: 0.565673:   7%|▋         | 14/200 [00:18<03:34,  1.15s/it]

[I 2025-11-10 17:31:52,042] Trial 16 finished with value: 0.5485185185185185 and parameters: {'max_depth': 7, 'learning_rate': 0.010353317364661834, 'n_estimators': 208, 'subsample': 0.817483661378113, 'colsample_bytree': 0.7553008214303972, 'min_child_weight': 1, 'gamma': 4.766733749346975, 'reg_alpha': 5.9634268373641356e-05, 'reg_lambda': 0.0004191277648195817, 'max_delta_step': 4}. Best is trial 13 with value: 0.5656725146198831.

Best trial: 13. Best value: 0.565673:   8%|▊         | 15/200 [00:18<02:59,  1.03it/s]

[I 2025-11-10 17:31:52,585] Trial 11 finished with value: 0.5336939571150097 and parameters: {'max_depth': 7, 'learning_rate': 0.184763012339013, 'n_estimators': 1208, 'subsample': 0.6807773468301731, 'colsample_bytree': 0.6216844986695209, 'min_child_weight': 1, 'gamma': 3.8446281497570207, 'reg_alpha': 5.43956435668973e-07, 'reg_lambda': 5.747354555670788, 'max_delta_step': 2}. Best is trial 13 with value: 0.5656725146198831.

Best trial: 13. Best value: 0.565673:   8%|▊         | 16/200 [00:21<04:02,  1.32s/it]

[I 2025-11-10 17:31:54,727] Trial 17 finished with value: 0.555906432748538 and parameters: {'max_depth': 7, 'learning_rate': 0.010291352949539574, 'n_estimators': 202, 'subsample': 0.8611018327557092, 'colsample_bytree': 0.7945711741706509, 'min_child_weight': 1, 'gamma': 2.9765704011282486, 'reg_alpha': 0.0013080460369035323, 'reg_lambda': 0.0012791838940104938, 'max_delta_step': 4}. Best is trial 13 with value: 0.5656725146198831.

Best trial: 13. Best value: 0.565673:   8%|▊         | 17/200 [00:22<04:11,  1.38s/it]

[I 2025-11-10 17:31:56,226] Trial 18 finished with value: 0.5625730994152047 and parameters: {'max_depth': 8, 'learning_rate': 0.010177713945598582, 'n_estimators': 346, 'subsample': 0.8267039272787399, 'colsample_bytree': 0.79817729925469, 'min_child_weight': 1, 'gamma': 3.0134029408910425, 'reg_alpha': 0.001944918364482576, 'reg_lambda': 0.0020508800571489906, 'max_delta_step': 5}. Best is trial 13 with value: 0.5656725146198831.

Best trial: 14. Best value: 0.572827:   9%|▉         | 18/200 [00:22<03:05,  1.02s/it]

[I 2025-11-10 17:31:56,421] Trial 14 finished with value: 0.5728265107212476 and parameters: {'max_depth': 8, 'learning_rate': 0.01103670874601987, 'n_estimators': 764, 'subsample': 0.8468682995175164, 'colsample_bytree': 0.8028195836646883, 'min_child_weight': 1, 'gamma': 1.5015843884611253, 'reg_alpha': 0.00010257866353220045, 'reg_lambda': 5.1793742006970305e-06, 'max_delta_step': 5}. Best is trial 14 with value: 0.5728265107212476.

Best trial: 19. Best value: 0.589415:  10%|▉         | 19/200 [00:23<02:31,  1.19it/s]

[I 2025-11-10 17:31:56,838] Trial 19 finished with value: 0.5894152046783625 and parameters: {'max_depth': 8, 'learning_rate': 0.01601475168461537, 'n_estimators': 235, 'subsample': 0.8504788403873935, 'colsample_bytree': 0.8016646320269775, 'min_child_weight': 2, 'gamma': 2.707782145806875, 'reg_alpha': 0.0026538157153926456, 'reg_lambda': 0.0034831992161809865, 'max_delta_step': 7}. Best is trial 19 with value: 0.5894152046783625.

Best trial: 19. Best value: 0.589415:  10%|█         | 20/200 [00:23<02:14,  1.34it/s]

[I 2025-11-10 17:31:57,371] Trial 15 finished with value: 0.5687329434697856 and parameters: {'max_depth': 7, 'learning_rate': 0.011507916614499042, 'n_estimators': 793, 'subsample': 0.8568419114682737, 'colsample_bytree': 0.9722461849974507, 'min_child_weight': 1, 'gamma': 1.7451661201107673, 'reg_alpha': 0.00021467078033616312, 'reg_lambda': 0.0008345815700339141, 'max_delta_step': 5}. Best is trial 19 with value: 0.5894152046783625.

Best trial: 19. Best value: 0.589415:  10%|█         | 21/200 [00:27<05:15,  1.76s/it]

[I 2025-11-10 17:32:01,507] Trial 20 finished with value: 0.5438011695906433 and parameters: {'max_depth': 8, 'learning_rate': 0.015409536649304908, 'n_estimators': 867, 'subsample': 0.7174558900187346, 'colsample_bytree': 0.8032276286339227, 'min_child_weight': 2, 'gamma': 2.026732165588607, 'reg_alpha': 0.010624839883363052, 'reg_lambda': 0.008997881541922983, 'max_delta_step': 7}. Best is trial 19 with value: 0.5894152046783625.

Best trial: 19. Best value: 0.589415:  11%|█         | 22/200 [00:28<04:37,  1.56s/it]

[I 2025-11-10 17:32:02,591] Trial 23 finished with value: 0.5394736842105263 and parameters: {'max_depth': 9, 'learning_rate': 0.018887869279092487, 'n_estimators': 885, 'subsample': 0.7114933689467928, 'colsample_bytree': 0.8670451556670228, 'min_child_weight': 2, 'gamma': 2.0419174547533174, 'reg_alpha': 0.012085180519290518, 'reg_lambda': 1.0154056712858696e-06, 'max_delta_step': 8}. Best is trial 19 with value: 0.5894152046783625.
[I 2025-11-10 17:32:02,652] Trial 22 finished with value: 0.5801559454191033 and parameters: {'max_depth': 9, 'learning_rate': 0.01817700180316563, 'n_estimators': 882, 'subsample': 0.8937588002142962, 'colsample_bytree': 0.890235978521593, 'min_child_weight': 2, 'gamma': 1.6874925809569254, 'reg_alpha': 0.04156897614603233, 'reg_lambda': 2.9081721045004957e-06, 'max_delta_step': 7}. Best is trial 19 with value: 0.5894152046783625.

Best trial: 19. Best value: 0.589415:  12%|█▏        | 24/200 [00:29<02:35,  1.13it/s]

[I 2025-11-10 17:32:02,784] Trial 21 finished with value: 0.5822417153996101 and parameters: {'max_depth': 9, 'learning_rate': 0.017138134280812733, 'n_estimators': 894, 'subsample': 0.8960054797455811, 'colsample_bytree': 0.9992432899674435, 'min_child_weight': 2, 'gamma': 1.973940333761799, 'reg_alpha': 0.007325511627560416, 'reg_lambda': 1.0388181428855612e-06, 'max_delta_step': 7}. Best is trial 19 with value: 0.5894152046783625.

Best trial: 24. Best value: 0.590643:  12%|█▎        | 25/200 [00:33<05:04,  1.74s/it]

[I 2025-11-10 17:32:07,109] Trial 24 finished with value: 0.5906432748538012 and parameters: {'max_depth': 9, 'learning_rate': 0.018216532107078978, 'n_estimators': 838, 'subsample': 0.8879532271523485, 'colsample_bytree': 0.9918116499022498, 'min_child_weight': 2, 'gamma': 1.9143586722517727, 'reg_alpha': 0.012123563180421465, 'reg_lambda': 7.745557042194137e-07, 'max_delta_step': 8}. Best is trial 24 with value: 0.5906432748538012.

Best trial: 24. Best value: 0.590643:  13%|█▎        | 26/200 [00:33<04:01,  1.39s/it]

[I 2025-11-10 17:32:07,504] Trial 26 finished with value: 0.5853411306042885 and parameters: {'max_depth': 9, 'learning_rate': 0.017915238672190557, 'n_estimators': 716, 'subsample': 0.9026227472170338, 'colsample_bytree': 0.8362433104856539, 'min_child_weight': 2, 'gamma': 1.5163483543112708, 'reg_alpha': 0.05127288989004067, 'reg_lambda': 5.47367165460991e-05, 'max_delta_step': 7}. Best is trial 24 with value: 0.5906432748538012.
[I 2025-11-10 17:32:07,535] Trial 25 finished with value: 0.583840155945419 and parameters: {'max_depth': 6, 'learning_rate': 0.017057256346719965, 'n_estimators': 676, 'subsample': 0.8962672595304737, 'colsample_bytree': 0.9858992776562643, 'min_child_weight': 2, 'gamma': 1.90166870613442, 'reg_alpha': 3.1392870703181126e-06, 'reg_lambda': 5.544298977646246e-05, 'max_delta_step': 7}. Best is trial 24 with value: 0.5906432748538012.

Best trial: 24. Best value: 0.590643:  14%|█▍        | 29/200 [00:34<02:02,  1.39it/s]

[I 2025-11-10 17:32:08,029] Trial 28 pruned.
[I 2025-11-10 17:32:08,137] Trial 29 pruned.

Best trial: 24. Best value: 0.590643:  16%|█▌        | 31/200 [00:34<01:22,  2.05it/s]

[I 2025-11-10 17:32:08,410] Trial 27 finished with value: 0.5718323586744639 and parameters: {'max_depth': 9, 'learning_rate': 0.05679066523082573, 'n_estimators': 979, 'subsample': 0.9012381328482338, 'colsample_bytree': 0.9232042152304694, 'min_child_weight': 2, 'gamma': 2.38349360464052, 'reg_alpha': 0.060298190606856095, 'reg_lambda': 4.846879752382311e-05, 'max_delta_step': 7}. Best is trial 24 with value: 0.5906432748538012.
[I 2025-11-10 17:32:08,567] Trial 30 pruned.

Best trial: 24. Best value: 0.590643:  16%|█▋        | 33/200 [00:34<00:51,  3.27it/s]

[I 2025-11-10 17:32:08,647] Trial 31 pruned.
[I 2025-11-10 17:32:08,687] Trial 32 pruned.

Best trial: 24. Best value: 0.590643:  17%|█▋        | 34/200 [00:35<00:51,  3.24it/s]

[I 2025-11-10 17:32:09,009] Trial 33 pruned.

Best trial: 24. Best value: 0.590643:  18%|█▊        | 35/200 [00:35<00:56,  2.94it/s]

[I 2025-11-10 17:32:09,444] Trial 34 pruned.

Best trial: 24. Best value: 0.590643:  18%|█▊        | 36/200 [00:35<00:49,  3.31it/s]

[I 2025-11-10 17:32:09,646] Trial 36 pruned.

Best trial: 24. Best value: 0.590643:  18%|█▊        | 37/200 [00:36<01:03,  2.58it/s]

[I 2025-11-10 17:32:10,254] Trial 39 pruned.
[I 2025-11-10 17:32:10,287] Trial 38 pruned.

Best trial: 24. Best value: 0.590643:  20%|█▉        | 39/200 [00:36<00:49,  3.24it/s]

[I 2025-11-10 17:32:10,664] Trial 40 pruned.

Best trial: 24. Best value: 0.590643:  20%|██        | 40/200 [00:38<01:46,  1.51it/s]

[I 2025-11-10 17:32:12,463] Trial 41 finished with value: 0.5553411306042884 and parameters: {'max_depth': 8, 'learning_rate': 0.03133134961234884, 'n_estimators': 318, 'subsample': 0.9512896507411742, 'colsample_bytree': 0.8881508320560597, 'min_child_weight': 3, 'gamma': 2.7348141377349164, 'reg_alpha': 0.7101508477154823, 'reg_lambda': 0.00029068259392141206, 'max_delta_step': 7}. Best is trial 24 with value: 0.5906432748538012.

Best trial: 24. Best value: 0.590643:  20%|██        | 41/200 [00:39<02:05,  1.27it/s]

[I 2025-11-10 17:32:13,626] Trial 37 finished with value: 0.5293762183235868 and parameters: {'max_depth': 6, 'learning_rate': 0.01503593896536836, 'n_estimators': 736, 'subsample': 0.8936773052915898, 'colsample_bytree': 0.9548857628030709, 'min_child_weight': 3, 'gamma': 3.5709664089133986, 'reg_alpha': 2.0641428905019943e-06, 'reg_lambda': 0.011550107988144901, 'max_delta_step': 6}. Best is trial 24 with value: 0.5906432748538012.

Best trial: 24. Best value: 0.590643:  21%|██        | 42/200 [00:40<02:04,  1.27it/s]

[I 2025-11-10 17:32:14,412] Trial 35 finished with value: 0.5646783625730993 and parameters: {'max_depth': 6, 'learning_rate': 0.014707566979431218, 'n_estimators': 744, 'subsample': 0.9450229073573169, 'colsample_bytree': 0.9624546449180247, 'min_child_weight': 3, 'gamma': 0.9652370239134764, 'reg_alpha': 2.708214225699549e-06, 'reg_lambda': 0.07276380088781267, 'max_delta_step': 9}. Best is trial 24 with value: 0.5906432748538012.
[I 2025-11-10 17:32:14,586] Trial 42 finished with value: 0.5446978557504872 and parameters: {'max_depth': 8, 'learning_rate': 0.02043009062819433, 'n_estimators': 798, 'subsample': 0.9185325909373844, 'colsample_bytree': 0.5057777759556071, 'min_child_weight': 3, 'gamma': 2.7605117200919707, 'reg_alpha': 0.4973176091596554, 'reg_lambda': 0.00022699921992247468, 'max_delta_step': 7}. Best is trial 24 with value: 0.5906432748538012.

Best trial: 24. Best value: 0.590643:  22%|██▏       | 44/200 [00:45<04:33,  1.75s/it]

[I 2025-11-10 17:32:19,223] Trial 44 finished with value: 0.5753216374269006 and parameters: {'max_depth': 9, 'learning_rate': 0.01913397933010346, 'n_estimators': 815, 'subsample': 0.9056092509446021, 'colsample_bytree': 0.9849596691251301, 'min_child_weight': 2, 'gamma': 2.0090662636685894, 'reg_alpha': 0.006770393599227319, 'reg_lambda': 1.4663824587976737e-06, 'max_delta_step': 7}. Best is trial 24 with value: 0.5906432748538012.

Best trial: 24. Best value: 0.590643:  22%|██▎       | 45/200 [00:46<04:05,  1.59s/it]

[I 2025-11-10 17:32:20,386] Trial 47 pruned.

Best trial: 24. Best value: 0.590643:  23%|██▎       | 46/200 [00:46<03:03,  1.19s/it]

[I 2025-11-10 17:32:20,615] Trial 45 finished with value: 0.5719883040935673 and parameters: {'max_depth': 9, 'learning_rate': 0.01957620903895676, 'n_estimators': 929, 'subsample': 0.9050904377737582, 'colsample_bytree': 0.9990183787949507, 'min_child_weight': 2, 'gamma': 2.0718349049712597, 'reg_alpha': 0.00796010566103109, 'reg_lambda': 2.102787932657138e-06, 'max_delta_step': 7}. Best is trial 24 with value: 0.5906432748538012.

Best trial: 24. Best value: 0.590643:  24%|██▎       | 47/200 [00:47<02:17,  1.11it/s]

[I 2025-11-10 17:32:20,824] Trial 43 finished with value: 0.5815204678362573 and parameters: {'max_depth': 6, 'learning_rate': 0.02007947714099118, 'n_estimators': 1481, 'subsample': 0.9170057520891398, 'colsample_bytree': 0.6864967784780478, 'min_child_weight': 2, 'gamma': 1.3944296360259332, 'reg_alpha': 0.7390962952896898, 'reg_lambda': 0.00024284282351835174, 'max_delta_step': 9}. Best is trial 24 with value: 0.5906432748538012.
[I 2025-11-10 17:32:20,863] Trial 46 finished with value: 0.5791617933723197 and parameters: {'max_depth': 9, 'learning_rate': 0.01755361848426051, 'n_estimators': 927, 'subsample': 0.9140645627688115, 'colsample_bytree': 0.9994706051336084, 'min_child_weight': 2, 'gamma': 2.1423986547043987, 'reg_alpha': 0.005016914825222661, 'reg_lambda': 1.6398167670416663e-06, 'max_delta_step': 7}. Best is trial 24 with value: 0.5906432748538012.

Best trial: 24. Best value: 0.590643:  24%|██▍       | 49/200 [00:48<01:46,  1.42it/s]

[I 2025-11-10 17:32:21,767] Trial 51 pruned.
[I 2025-11-10 17:32:21,781] Trial 50 pruned.

Best trial: 24. Best value: 0.590643:  26%|██▌       | 51/200 [00:49<01:39,  1.49it/s]

[I 2025-11-10 17:32:22,995] Trial 52 pruned.

Best trial: 24. Best value: 0.590643:  26%|██▌       | 52/200 [00:49<01:27,  1.69it/s]

[I 2025-11-10 17:32:23,315] Trial 53 pruned.

Best trial: 24. Best value: 0.590643:  26%|██▋       | 53/200 [00:53<03:10,  1.30s/it]

[I 2025-11-10 17:32:26,862] Trial 49 finished with value: 0.5723976608187135 and parameters: {'max_depth': 9, 'learning_rate': 0.028124001941801174, 'n_estimators': 1089, 'subsample': 0.8713041567071571, 'colsample_bytree': 0.667893374794457, 'min_child_weight': 2, 'gamma': 1.451670059479525, 'reg_alpha': 1.8870251775082654, 'reg_lambda': 5.087940645498729e-08, 'max_delta_step': 10}. Best is trial 24 with value: 0.5906432748538012.
[I 2025-11-10 17:32:26,900] Trial 48 finished with value: 0.5751072124756336 and parameters: {'max_depth': 9, 'learning_rate': 0.01817331909454981, 'n_estimators': 1087, 'subsample': 0.8714315301451526, 'colsample_bytree': 0.6764644426557823, 'min_child_weight': 2, 'gamma': 1.3362813043286537, 'reg_alpha': 0.020714615270866873, 'reg_lambda': 6.415645640562063e-08, 'max_delta_step': 10}. Best is trial 24 with value: 0.5906432748538012.

Best trial: 24. Best value: 0.590643:  28%|██▊       | 55/200 [00:54<02:24,  1.01it/s]

[I 2025-11-10 17:32:27,959] Trial 57 pruned.

Best trial: 24. Best value: 0.590643:  28%|██▊       | 56/200 [00:55<02:26,  1.02s/it]

[I 2025-11-10 17:32:29,071] Trial 58 pruned.

Best trial: 24. Best value: 0.590643:  28%|██▊       | 57/200 [00:57<03:16,  1.38s/it]

[I 2025-11-10 17:32:31,556] Trial 54 finished with value: 0.5716179337231969 and parameters: {'max_depth': 7, 'learning_rate': 0.01327063763734787, 'n_estimators': 1428, 'subsample': 0.963865379539326, 'colsample_bytree': 0.6548351343444784, 'min_child_weight': 2, 'gamma': 1.3370598179065323, 'reg_alpha': 1.9668790393831195, 'reg_lambda': 0.0036510921356418457, 'max_delta_step': 8}. Best is trial 24 with value: 0.5906432748538012.

Best trial: 24. Best value: 0.590643:  29%|██▉       | 58/200 [00:58<02:40,  1.13s/it]

[I 2025-11-10 17:32:31,976] Trial 55 finished with value: 0.5858284600389864 and parameters: {'max_depth': 6, 'learning_rate': 0.013275516552694527, 'n_estimators': 1427, 'subsample': 0.9265288070547776, 'colsample_bytree': 0.677192823235494, 'min_child_weight': 2, 'gamma': 1.2379620046395705, 'reg_alpha': 0.02116624046144518, 'reg_lambda': 0.0040660356405813995, 'max_delta_step': 8}. Best is trial 24 with value: 0.5906432748538012.

Best trial: 24. Best value: 0.590643:  30%|██▉       | 59/200 [00:59<02:25,  1.03s/it]

[I 2025-11-10 17:32:32,742] Trial 60 pruned.

Best trial: 24. Best value: 0.590643:  30%|███       | 61/200 [00:59<01:30,  1.54it/s]

[I 2025-11-10 17:32:33,187] Trial 62 pruned.
[I 2025-11-10 17:32:33,287] Trial 61 pruned.

Best trial: 24. Best value: 0.590643:  31%|███       | 62/200 [01:00<01:28,  1.56it/s]

[I 2025-11-10 17:32:33,902] Trial 59 finished with value: 0.5816179337231968 and parameters: {'max_depth': 5, 'learning_rate': 0.015776363629919004, 'n_estimators': 607, 'subsample': 0.8401541813981326, 'colsample_bytree': 0.5521464004071, 'min_child_weight': 2, 'gamma': 0.634902038171246, 'reg_alpha': 1.9627389500862036, 'reg_lambda': 0.0006012879853116596, 'max_delta_step': 9}. Best is trial 24 with value: 0.5906432748538012.

Best trial: 24. Best value: 0.590643:  32%|███▏      | 63/200 [01:00<01:22,  1.66it/s]

[I 2025-11-10 17:32:34,418] Trial 63 pruned.

Best trial: 24. Best value: 0.590643:  32%|███▏      | 64/200 [01:01<01:23,  1.62it/s]

[I 2025-11-10 17:32:35,061] Trial 65 pruned.

Best trial: 56. Best value: 0.592865:  32%|███▎      | 65/200 [01:01<01:06,  2.03it/s]

[I 2025-11-10 17:32:35,265] Trial 56 finished with value: 0.5928654970760234 and parameters: {'max_depth': 6, 'learning_rate': 0.021963462995609157, 'n_estimators': 1412, 'subsample': 0.9691300274328096, 'colsample_bytree': 0.7118348368987156, 'min_child_weight': 2, 'gamma': 1.3424986429739847, 'reg_alpha': 0.022382604756777436, 'reg_lambda': 0.0038709871944059933, 'max_delta_step': 8}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  33%|███▎      | 66/200 [01:03<01:52,  1.19it/s]

[I 2025-11-10 17:32:36,934] Trial 68 pruned.

Best trial: 56. Best value: 0.592865:  34%|███▎      | 67/200 [01:05<02:40,  1.20s/it]

[I 2025-11-10 17:32:38,990] Trial 67 finished with value: 0.5622417153996102 and parameters: {'max_depth': 3, 'learning_rate': 0.021642882803561938, 'n_estimators': 646, 'subsample': 0.8517547836676718, 'colsample_bytree': 0.5352145287273361, 'min_child_weight': 2, 'gamma': 1.1674391676372573, 'reg_alpha': 0.00013154812190920774, 'reg_lambda': 0.027583770122670385, 'max_delta_step': 8}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  34%|███▍      | 68/200 [01:05<02:06,  1.04it/s]

[I 2025-11-10 17:32:39,365] Trial 66 finished with value: 0.569785575048733 and parameters: {'max_depth': 3, 'learning_rate': 0.02103799183521719, 'n_estimators': 836, 'subsample': 0.8884648512637009, 'colsample_bytree': 0.5399704436874756, 'min_child_weight': 2, 'gamma': 1.0840769944283266, 'reg_alpha': 0.051698912778351876, 'reg_lambda': 0.023619464126718493, 'max_delta_step': 3}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  34%|███▍      | 69/200 [01:06<01:48,  1.21it/s]

[I 2025-11-10 17:32:39,898] Trial 71 pruned.

Best trial: 56. Best value: 0.592865:  35%|███▌      | 70/200 [01:07<01:48,  1.20it/s]

[I 2025-11-10 17:32:40,734] Trial 64 finished with value: 0.5775828460038985 and parameters: {'max_depth': 6, 'learning_rate': 0.022233005778999705, 'n_estimators': 1351, 'subsample': 0.8920426571725528, 'colsample_bytree': 0.6060066788239498, 'min_child_weight': 2, 'gamma': 1.6632519278009663, 'reg_alpha': 0.05398616977172855, 'reg_lambda': 0.027187498765172676, 'max_delta_step': 8}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  36%|███▌      | 71/200 [01:07<01:27,  1.47it/s]

[I 2025-11-10 17:32:41,059] Trial 70 pruned.

Best trial: 56. Best value: 0.592865:  36%|███▋      | 73/200 [01:07<00:54,  2.32it/s]

[I 2025-11-10 17:32:41,351] Trial 72 pruned.
[I 2025-11-10 17:32:41,476] Trial 73 pruned.

Best trial: 56. Best value: 0.592865:  37%|███▋      | 74/200 [01:08<01:00,  2.09it/s]

[I 2025-11-10 17:32:42,063] Trial 75 pruned.

Best trial: 56. Best value: 0.592865:  38%|███▊      | 75/200 [01:08<00:54,  2.28it/s]

[I 2025-11-10 17:32:42,410] Trial 76 pruned.

Best trial: 56. Best value: 0.592865:  38%|███▊      | 76/200 [01:09<00:56,  2.18it/s]

[I 2025-11-10 17:32:42,913] Trial 77 pruned.

Best trial: 56. Best value: 0.592865:  38%|███▊      | 77/200 [01:09<00:57,  2.15it/s]

[I 2025-11-10 17:32:43,394] Trial 78 pruned.

Best trial: 56. Best value: 0.592865:  39%|███▉      | 78/200 [01:10<00:52,  2.31it/s]

[I 2025-11-10 17:32:43,747] Trial 79 pruned.

Best trial: 56. Best value: 0.592865:  40%|███▉      | 79/200 [01:10<00:53,  2.27it/s]

[I 2025-11-10 17:32:44,205] Trial 69 finished with value: 0.5821247563352826 and parameters: {'max_depth': 6, 'learning_rate': 0.021588684217392747, 'n_estimators': 1156, 'subsample': 0.9796624515903493, 'colsample_bytree': 0.7270782603494653, 'min_child_weight': 2, 'gamma': 1.1159364949004524, 'reg_alpha': 0.0001348112114965034, 'reg_lambda': 0.004517842955521921, 'max_delta_step': 3}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  40%|████      | 80/200 [01:11<01:18,  1.54it/s]

[I 2025-11-10 17:32:45,349] Trial 74 finished with value: 0.5748343079922027 and parameters: {'max_depth': 5, 'learning_rate': 0.016059949363295474, 'n_estimators': 574, 'subsample': 0.8095938359703755, 'colsample_bytree': 0.767946276607858, 'min_child_weight': 2, 'gamma': 2.2426514813854617, 'reg_alpha': 0.0007462716470964446, 'reg_lambda': 0.001411734555418871, 'max_delta_step': 7}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  40%|████      | 81/200 [01:12<01:25,  1.39it/s]

[I 2025-11-10 17:32:46,235] Trial 82 pruned.

Best trial: 56. Best value: 0.592865:  41%|████      | 82/200 [01:13<01:21,  1.44it/s]

[I 2025-11-10 17:32:46,866] Trial 80 finished with value: 0.5695126705653021 and parameters: {'max_depth': 7, 'learning_rate': 0.018110992543839566, 'n_estimators': 675, 'subsample': 0.857620017890694, 'colsample_bytree': 0.7700233118449293, 'min_child_weight': 3, 'gamma': 2.6033306456192693, 'reg_alpha': 3.9411693482221777, 'reg_lambda': 3.8795347184912865e-06, 'max_delta_step': 8}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  42%|████▏     | 83/200 [01:13<01:06,  1.76it/s]

[I 2025-11-10 17:32:47,142] Trial 83 pruned.

Best trial: 56. Best value: 0.592865:  42%|████▏     | 84/200 [01:13<00:55,  2.09it/s]

[I 2025-11-10 17:32:47,410] Trial 84 pruned.

Best trial: 56. Best value: 0.592865:  42%|████▎     | 85/200 [01:14<00:55,  2.08it/s]

[I 2025-11-10 17:32:47,897] Trial 85 pruned.

Best trial: 56. Best value: 0.592865:  43%|████▎     | 86/200 [01:14<00:57,  1.99it/s]

[I 2025-11-10 17:32:48,454] Trial 86 pruned.

Best trial: 56. Best value: 0.592865:  44%|████▎     | 87/200 [01:14<00:46,  2.45it/s]

[I 2025-11-10 17:32:48,637] Trial 81 finished with value: 0.580896686159844 and parameters: {'max_depth': 7, 'learning_rate': 0.01879986155572324, 'n_estimators': 666, 'subsample': 0.8571364643074922, 'colsample_bytree': 0.7715157851785264, 'min_child_weight': 2, 'gamma': 1.0870418229063366, 'reg_alpha': 3.587959082826315e-07, 'reg_lambda': 3.760974431538439e-06, 'max_delta_step': 8}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  44%|████▍     | 88/200 [01:15<00:48,  2.29it/s]

[I 2025-11-10 17:32:49,140] Trial 88 pruned.

Best trial: 56. Best value: 0.592865:  44%|████▍     | 89/200 [01:16<01:09,  1.59it/s]

[I 2025-11-10 17:32:50,221] Trial 90 pruned.

Best trial: 56. Best value: 0.592865:  45%|████▌     | 90/200 [01:17<01:11,  1.55it/s]

[I 2025-11-10 17:32:50,905] Trial 91 pruned.

Best trial: 56. Best value: 0.592865:  46%|████▌     | 91/200 [01:18<01:26,  1.25it/s]

[I 2025-11-10 17:32:52,053] Trial 92 pruned.

Best trial: 56. Best value: 0.592865:  46%|████▌     | 92/200 [01:18<01:14,  1.45it/s]

[I 2025-11-10 17:32:52,493] Trial 93 pruned.

Best trial: 56. Best value: 0.592865:  46%|████▋     | 93/200 [01:19<01:26,  1.24it/s]

[I 2025-11-10 17:32:53,567] Trial 95 pruned.

Best trial: 56. Best value: 0.592865:  47%|████▋     | 94/200 [01:20<01:26,  1.23it/s]

[I 2025-11-10 17:32:54,412] Trial 87 finished with value: 0.5910331384015595 and parameters: {'max_depth': 9, 'learning_rate': 0.014615465385010554, 'n_estimators': 973, 'subsample': 0.8989597698813574, 'colsample_bytree': 0.6982549296829363, 'min_child_weight': 2, 'gamma': 0.9417278074795732, 'reg_alpha': 0.006473000307992418, 'reg_lambda': 0.0008962329325936911, 'max_delta_step': 1}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  48%|████▊     | 95/200 [01:21<01:40,  1.05it/s]

[I 2025-11-10 17:32:55,681] Trial 89 finished with value: 0.5794152046783625 and parameters: {'max_depth': 9, 'learning_rate': 0.019340314438444545, 'n_estimators': 1192, 'subsample': 0.9414304019015798, 'colsample_bytree': 0.6982622118945284, 'min_child_weight': 2, 'gamma': 0.9683285631902875, 'reg_alpha': 0.006641778976808918, 'reg_lambda': 0.002325870239904514, 'max_delta_step': 3}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  48%|████▊     | 96/200 [01:23<01:52,  1.08s/it]

[I 2025-11-10 17:32:57,061] Trial 98 pruned.

Best trial: 56. Best value: 0.592865:  48%|████▊     | 97/200 [01:24<01:56,  1.13s/it]

[I 2025-11-10 17:32:58,329] Trial 99 pruned.

Best trial: 56. Best value: 0.592865:  49%|████▉     | 98/200 [01:25<02:02,  1.20s/it]

[I 2025-11-10 17:32:59,692] Trial 100 pruned.

Best trial: 56. Best value: 0.592865:  50%|████▉     | 99/200 [01:26<01:48,  1.07s/it]

[I 2025-11-10 17:33:00,445] Trial 94 finished with value: 0.566588693957115 and parameters: {'max_depth': 6, 'learning_rate': 0.020802218443910746, 'n_estimators': 1456, 'subsample': 0.8807998982456369, 'colsample_bytree': 0.6844211758808062, 'min_child_weight': 2, 'gamma': 1.4253124755185225, 'reg_alpha': 0.09676664290289759, 'reg_lambda': 0.00027157228069741787, 'max_delta_step': 9}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  50%|█████     | 100/200 [01:27<01:36,  1.04it/s]

[I 2025-11-10 17:33:01,148] Trial 102 pruned.

Best trial: 56. Best value: 0.592865:  50%|█████     | 101/200 [01:27<01:12,  1.37it/s]

[I 2025-11-10 17:33:01,346] Trial 97 finished with value: 0.5703898635477582 and parameters: {'max_depth': 9, 'learning_rate': 0.01756595523992666, 'n_estimators': 968, 'subsample': 0.8373361724917572, 'colsample_bytree': 0.6853963406633894, 'min_child_weight': 2, 'gamma': 0.4623242884799075, 'reg_alpha': 0.0908083457893412, 'reg_lambda': 0.00035285772890689967, 'max_delta_step': 0}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  51%|█████     | 102/200 [01:28<01:09,  1.40it/s]

[I 2025-11-10 17:33:02,018] Trial 104 pruned.

Best trial: 56. Best value: 0.592865:  52%|█████▏    | 104/200 [01:28<00:48,  2.00it/s]

[I 2025-11-10 17:33:02,512] Trial 103 pruned.
[I 2025-11-10 17:33:02,676] Trial 96 finished with value: 0.5770565302144249 and parameters: {'max_depth': 6, 'learning_rate': 0.017290942267416003, 'n_estimators': 1476, 'subsample': 0.8334738437954723, 'colsample_bytree': 0.6910252249683217, 'min_child_weight': 2, 'gamma': 1.364682425433363, 'reg_alpha': 0.24846943488424775, 'reg_lambda': 0.0002885086840097378, 'max_delta_step': 8}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  52%|█████▎    | 105/200 [01:29<01:02,  1.52it/s]

[I 2025-11-10 17:33:03,689] Trial 105 pruned.

Best trial: 56. Best value: 0.592865:  53%|█████▎    | 106/200 [01:30<01:04,  1.45it/s]

[I 2025-11-10 17:33:04,462] Trial 106 pruned.

Best trial: 56. Best value: 0.592865:  54%|█████▍    | 108/200 [01:31<00:52,  1.76it/s]

[I 2025-11-10 17:33:05,321] Trial 108 pruned.
[I 2025-11-10 17:33:05,490] Trial 109 pruned.

Best trial: 56. Best value: 0.592865:  55%|█████▍    | 109/200 [01:32<01:09,  1.31it/s]

[I 2025-11-10 17:33:06,701] Trial 110 pruned.

Best trial: 56. Best value: 0.592865:  55%|█████▌    | 110/200 [01:34<01:39,  1.11s/it]

[I 2025-11-10 17:33:08,619] Trial 101 finished with value: 0.5826315789473684 and parameters: {'max_depth': 4, 'learning_rate': 0.010187614736542273, 'n_estimators': 891, 'subsample': 0.9003363597558921, 'colsample_bytree': 0.8380498101038523, 'min_child_weight': 2, 'gamma': 0.49795648058338915, 'reg_alpha': 0.0017083086235447297, 'reg_lambda': 0.00031366736020376954, 'max_delta_step': 7}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  56%|█████▌    | 111/200 [01:37<02:13,  1.50s/it]

[I 2025-11-10 17:33:11,024] Trial 107 finished with value: 0.5759649122807018 and parameters: {'max_depth': 7, 'learning_rate': 0.02157759826809326, 'n_estimators': 1387, 'subsample': 0.9167953601601605, 'colsample_bytree': 0.8357559877343782, 'min_child_weight': 2, 'gamma': 0.7180388405564744, 'reg_alpha': 3.305798812295225e-05, 'reg_lambda': 0.0012550557685941468, 'max_delta_step': 7}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  56%|█████▌    | 112/200 [01:38<02:03,  1.40s/it]

[I 2025-11-10 17:33:12,203] Trial 111 finished with value: 0.5805068226120859 and parameters: {'max_depth': 7, 'learning_rate': 0.02386380263258947, 'n_estimators': 1056, 'subsample': 0.8894991308705981, 'colsample_bytree': 0.760217421308321, 'min_child_weight': 2, 'gamma': 0.1808228540279333, 'reg_alpha': 2.6012679191344843e-05, 'reg_lambda': 0.0018717100646224905, 'max_delta_step': 7}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  56%|█████▋    | 113/200 [01:39<01:53,  1.31s/it]

[I 2025-11-10 17:33:13,296] Trial 114 pruned.

Best trial: 56. Best value: 0.592865:  57%|█████▋    | 114/200 [01:41<02:00,  1.40s/it]

[I 2025-11-10 17:33:14,892] Trial 116 pruned.

Best trial: 56. Best value: 0.592865:  57%|█████▊    | 115/200 [01:43<02:25,  1.71s/it]

[I 2025-11-10 17:33:17,344] Trial 112 finished with value: 0.5491617933723197 and parameters: {'max_depth': 5, 'learning_rate': 0.011634254746451512, 'n_estimators': 1496, 'subsample': 0.8849050452712073, 'colsample_bytree': 0.6047014259393519, 'min_child_weight': 1, 'gamma': 0.8140852412604994, 'reg_alpha': 2.8777731907372264, 'reg_lambda': 1.0825704044743876e-05, 'max_delta_step': 8}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  58%|█████▊    | 117/200 [01:46<02:00,  1.46s/it]

[I 2025-11-10 17:33:20,112] Trial 113 finished with value: 0.5633528265107213 and parameters: {'max_depth': 4, 'learning_rate': 0.010061193992937544, 'n_estimators': 953, 'subsample': 0.6590076219556205, 'colsample_bytree': 0.9377296823380427, 'min_child_weight': 1, 'gamma': 0.15269967921854943, 'reg_alpha': 2.438694438536474e-05, 'reg_lambda': 0.04644509173502122, 'max_delta_step': 6}. Best is trial 56 with value: 0.5928654970760234.
[I 2025-11-10 17:33:20,236] Trial 118 finished with value: 0.5823781676413256 and parameters: {'max_depth': 3, 'learning_rate': 0.01634552881832408, 'n_estimators': 244, 'subsample': 0.8498072347542213, 'colsample_bytree': 0.7233920761922041, 'min_child_weight': 2, 'gamma': 1.5131890136910169, 'reg_alpha': 0.5812866730530738, 'reg_lambda': 0.042247012281719, 'max_delta_step': 7}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  59%|█████▉    | 118/200 [01:47<01:41,  1.24s/it]

[I 2025-11-10 17:33:20,983] Trial 117 finished with value: 0.5805263157894736 and parameters: {'max_depth': 4, 'learning_rate': 0.016123950396020072, 'n_estimators': 615, 'subsample': 0.8983165567855894, 'colsample_bytree': 0.8583499813703946, 'min_child_weight': 2, 'gamma': 0.585290188012141, 'reg_alpha': 0.001835617647992493, 'reg_lambda': 1.0295261405727873e-05, 'max_delta_step': 8}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  60%|█████▉    | 119/200 [01:48<01:34,  1.17s/it]

[I 2025-11-10 17:33:21,990] Trial 121 pruned.

Best trial: 56. Best value: 0.592865:  60%|██████    | 120/200 [01:49<01:33,  1.17s/it]

[I 2025-11-10 17:33:23,158] Trial 119 finished with value: 0.5839766081871345 and parameters: {'max_depth': 9, 'learning_rate': 0.01634969703330014, 'n_estimators': 239, 'subsample': 0.8959467253135476, 'colsample_bytree': 0.8629950051383807, 'min_child_weight': 2, 'gamma': 0.4509114532726557, 'reg_alpha': 0.0019250652285647217, 'reg_lambda': 0.0006462047452015461, 'max_delta_step': 9}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  60%|██████    | 121/200 [01:49<01:09,  1.13it/s]

[I 2025-11-10 17:33:23,373] Trial 115 finished with value: 0.5900389863547758 and parameters: {'max_depth': 4, 'learning_rate': 0.010619105711429861, 'n_estimators': 1495, 'subsample': 0.9338649806584839, 'colsample_bytree': 0.8578676081977663, 'min_child_weight': 2, 'gamma': 0.7760186341652254, 'reg_alpha': 6.4354436223542015e-06, 'reg_lambda': 0.046579583882556105, 'max_delta_step': 6}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  61%|██████    | 122/200 [01:49<00:53,  1.46it/s]

[I 2025-11-10 17:33:23,584] Trial 120 finished with value: 0.5906432748538012 and parameters: {'max_depth': 3, 'learning_rate': 0.013441609121267477, 'n_estimators': 272, 'subsample': 0.8617123814477768, 'colsample_bytree': 0.8630145208676192, 'min_child_weight': 2, 'gamma': 0.545370337153207, 'reg_alpha': 0.01803353840763226, 'reg_lambda': 0.0006732858391220646, 'max_delta_step': 7}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  62%|██████▏   | 123/200 [01:50<00:42,  1.79it/s]

[I 2025-11-10 17:33:23,850] Trial 125 pruned.

Best trial: 56. Best value: 0.592865:  62%|██████▏   | 124/200 [01:50<00:47,  1.59it/s]

[I 2025-11-10 17:33:24,640] Trial 126 pruned.

Best trial: 56. Best value: 0.592865:  62%|██████▎   | 125/200 [01:51<00:43,  1.73it/s]

[I 2025-11-10 17:33:25,101] Trial 122 finished with value: 0.5748538011695906 and parameters: {'max_depth': 3, 'learning_rate': 0.01314366052093123, 'n_estimators': 250, 'subsample': 0.854141874482642, 'colsample_bytree': 0.9002452142542807, 'min_child_weight': 2, 'gamma': 1.51900936596506, 'reg_alpha': 6.862849261933371e-06, 'reg_lambda': 1.2176016336713769, 'max_delta_step': 7}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  63%|██████▎   | 126/200 [01:52<00:57,  1.28it/s]

[I 2025-11-10 17:33:26,352] Trial 123 finished with value: 0.5883040935672514 and parameters: {'max_depth': 3, 'learning_rate': 0.013272363376240553, 'n_estimators': 244, 'subsample': 0.906801650713196, 'colsample_bytree': 0.8252048274075129, 'min_child_weight': 2, 'gamma': 0.48521530024945664, 'reg_alpha': 0.0010803957856383086, 'reg_lambda': 0.009461305736903316, 'max_delta_step': 7}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  64%|██████▎   | 127/200 [01:53<00:48,  1.50it/s]

[I 2025-11-10 17:33:26,761] Trial 124 finished with value: 0.5911306042884991 and parameters: {'max_depth': 3, 'learning_rate': 0.010746789603805039, 'n_estimators': 316, 'subsample': 0.9269558971471351, 'colsample_bytree': 0.7911916895848128, 'min_child_weight': 2, 'gamma': 2.103244066965586, 'reg_alpha': 1.021423447273472e-05, 'reg_lambda': 0.09631531079311695, 'max_delta_step': 7}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  64%|██████▍   | 128/200 [01:53<00:45,  1.59it/s]

[I 2025-11-10 17:33:27,302] Trial 129 pruned.

Best trial: 56. Best value: 0.592865:  64%|██████▍   | 129/200 [01:54<00:43,  1.65it/s]

[I 2025-11-10 17:33:27,859] Trial 131 pruned.

Best trial: 56. Best value: 0.592865:  65%|██████▌   | 130/200 [01:54<00:44,  1.57it/s]

[I 2025-11-10 17:33:28,559] Trial 128 finished with value: 0.5726315789473684 and parameters: {'max_depth': 3, 'learning_rate': 0.010844388534107154, 'n_estimators': 302, 'subsample': 0.8748221459974613, 'colsample_bytree': 0.822312445807077, 'min_child_weight': 2, 'gamma': 1.763947720090293, 'reg_alpha': 0.02885747996810633, 'reg_lambda': 0.045000883506209406, 'max_delta_step': 7}. Best is trial 56 with value: 0.5928654970760234.
[I 2025-11-10 17:33:28,647] Trial 132 pruned.

Best trial: 56. Best value: 0.592865:  66%|██████▌   | 132/200 [01:55<00:26,  2.53it/s]

[I 2025-11-10 17:33:28,790] Trial 127 finished with value: 0.5778167641325537 and parameters: {'max_depth': 3, 'learning_rate': 0.010685031232505162, 'n_estimators': 319, 'subsample': 0.8753279622992856, 'colsample_bytree': 0.9000654168396395, 'min_child_weight': 2, 'gamma': 0.4774165562310479, 'reg_alpha': 0.026777663506882307, 'reg_lambda': 0.0186469582522744, 'max_delta_step': 7}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  66%|██████▋   | 133/200 [01:56<00:35,  1.88it/s]

[I 2025-11-10 17:33:29,729] Trial 133 pruned.

Best trial: 56. Best value: 0.592865:  67%|██████▋   | 134/200 [01:56<00:40,  1.63it/s]

[I 2025-11-10 17:33:30,571] Trial 130 finished with value: 0.5840935672514619 and parameters: {'max_depth': 3, 'learning_rate': 0.011403682710590266, 'n_estimators': 298, 'subsample': 0.9310105345102406, 'colsample_bytree': 0.7963519702713703, 'min_child_weight': 2, 'gamma': 0.4248780577393517, 'reg_alpha': 2.6274593700184217e-06, 'reg_lambda': 0.010243740995814316, 'max_delta_step': 6}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  68%|██████▊   | 135/200 [01:58<00:50,  1.28it/s]

[I 2025-11-10 17:33:31,796] Trial 135 finished with value: 0.5828849902534115 and parameters: {'max_depth': 3, 'learning_rate': 0.014084892351228421, 'n_estimators': 237, 'subsample': 0.9002247265720237, 'colsample_bytree': 0.8541403580366372, 'min_child_weight': 2, 'gamma': 0.7091444696567515, 'reg_alpha': 0.00041296129018512077, 'reg_lambda': 0.1164558300495504, 'max_delta_step': 7}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  68%|██████▊   | 136/200 [01:58<00:49,  1.29it/s]

[I 2025-11-10 17:33:32,559] Trial 134 finished with value: 0.5902923976608186 and parameters: {'max_depth': 3, 'learning_rate': 0.014235746433567772, 'n_estimators': 359, 'subsample': 0.8988248377471015, 'colsample_bytree': 0.7881530294301652, 'min_child_weight': 2, 'gamma': 0.7603355512126124, 'reg_alpha': 0.00043452351429258446, 'reg_lambda': 0.019802852717241505, 'max_delta_step': 7}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  68%|██████▊   | 137/200 [01:59<00:38,  1.64it/s]

[I 2025-11-10 17:33:32,757] Trial 136 finished with value: 0.588440545808967 and parameters: {'max_depth': 3, 'learning_rate': 0.012229707029397538, 'n_estimators': 229, 'subsample': 0.9011348211392033, 'colsample_bytree': 0.8388628565044969, 'min_child_weight': 2, 'gamma': 0.8674710467253903, 'reg_alpha': 0.0005744886830189752, 'reg_lambda': 0.15019690426032714, 'max_delta_step': 7}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  69%|██████▉   | 138/200 [01:59<00:34,  1.79it/s]

[I 2025-11-10 17:33:33,187] Trial 139 pruned.

Best trial: 56. Best value: 0.592865:  70%|██████▉   | 139/200 [01:59<00:30,  1.99it/s]

[I 2025-11-10 17:33:33,559] Trial 140 pruned.

Best trial: 56. Best value: 0.592865:  70%|███████   | 140/200 [02:00<00:29,  2.01it/s]

[I 2025-11-10 17:33:34,041] Trial 137 finished with value: 0.5918908382066277 and parameters: {'max_depth': 3, 'learning_rate': 0.011533043697484454, 'n_estimators': 270, 'subsample': 0.9051127889106964, 'colsample_bytree': 0.7887419294906405, 'min_child_weight': 2, 'gamma': 0.3863896015397867, 'reg_alpha': 7.259294211239883e-07, 'reg_lambda': 0.007926454577468937, 'max_delta_step': 5}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  70%|███████   | 141/200 [02:01<00:44,  1.34it/s]

[I 2025-11-10 17:33:35,385] Trial 138 finished with value: 0.5908966861598441 and parameters: {'max_depth': 3, 'learning_rate': 0.01239464752431871, 'n_estimators': 274, 'subsample': 0.9315631872575554, 'colsample_bytree': 0.7849199608454412, 'min_child_weight': 2, 'gamma': 0.6396080436927882, 'reg_alpha': 0.00041755482783953753, 'reg_lambda': 0.13335305306812728, 'max_delta_step': 5}. Best is trial 56 with value: 0.5928654970760234.

Best trial: 56. Best value: 0.592865:  71%|███████   | 142/200 [02:02<00:43,  1.33it/s]

[I 2025-11-10 17:33:36,149] Trial 144 pruned.

Best trial: 142. Best value: 0.600292:  72%|███████▏  | 143/200 [02:03<00:47,  1.21it/s]

[I 2025-11-10 17:33:37,151] Trial 142 finished with value: 0.6002923976608188 and parameters: {'max_depth': 3, 'learning_rate': 0.011458203816290384, 'n_estimators': 276, 'subsample': 0.8922776265820194, 'colsample_bytree': 0.8011685205801988, 'min_child_weight': 2, 'gamma': 0.6152311844020093, 'reg_alpha': 0.0004375147239426621, 'reg_lambda': 0.7337665992070395, 'max_delta_step': 6}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  72%|███████▏  | 144/200 [02:03<00:40,  1.40it/s]

[I 2025-11-10 17:33:37,606] Trial 141 finished with value: 0.5923976608187135 and parameters: {'max_depth': 3, 'learning_rate': 0.011590127762920092, 'n_estimators': 342, 'subsample': 0.9075563430885465, 'colsample_bytree': 0.7786629838231751, 'min_child_weight': 2, 'gamma': 0.38239028779994744, 'reg_alpha': 0.0006274444278612322, 'reg_lambda': 0.802574035214449, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  72%|███████▎  | 145/200 [02:04<00:36,  1.50it/s]

[I 2025-11-10 17:33:38,164] Trial 143 finished with value: 0.5894346978557505 and parameters: {'max_depth': 3, 'learning_rate': 0.011467332085945935, 'n_estimators': 327, 'subsample': 0.8864054137560704, 'colsample_bytree': 0.8037332256265202, 'min_child_weight': 2, 'gamma': 0.6275907738565937, 'reg_alpha': 4.859482597244626e-06, 'reg_lambda': 0.6236026810047486, 'max_delta_step': 6}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  73%|███████▎  | 146/200 [02:06<00:59,  1.11s/it]

[I 2025-11-10 17:33:40,301] Trial 145 finished with value: 0.5794152046783625 and parameters: {'max_depth': 3, 'learning_rate': 0.011468444682801764, 'n_estimators': 336, 'subsample': 0.9488310877916817, 'colsample_bytree': 0.7777426126164422, 'min_child_weight': 2, 'gamma': 0.6001571724616547, 'reg_alpha': 1.4213955137704924e-07, 'reg_lambda': 0.07261961292497504, 'max_delta_step': 4}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  74%|███████▎  | 147/200 [02:06<00:46,  1.15it/s]

[I 2025-11-10 17:33:40,619] Trial 147 finished with value: 0.5699025341130604 and parameters: {'max_depth': 3, 'learning_rate': 0.012869227373187244, 'n_estimators': 216, 'subsample': 0.9470791100855536, 'colsample_bytree': 0.7794148047955272, 'min_child_weight': 2, 'gamma': 0.642491361433146, 'reg_alpha': 0.0002548916410461128, 'reg_lambda': 3.6128437746120814, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  74%|███████▍  | 148/200 [02:07<00:41,  1.25it/s]

[I 2025-11-10 17:33:41,263] Trial 146 finished with value: 0.5858479532163743 and parameters: {'max_depth': 3, 'learning_rate': 0.012678306328857159, 'n_estimators': 331, 'subsample': 0.8831520024587408, 'colsample_bytree': 0.8127941200468042, 'min_child_weight': 2, 'gamma': 0.6488253063169015, 'reg_alpha': 0.00020583322603024188, 'reg_lambda': 0.5676397814452099, 'max_delta_step': 6}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  74%|███████▍  | 149/200 [02:08<00:46,  1.10it/s]

[I 2025-11-10 17:33:42,421] Trial 148 finished with value: 0.5814035087719298 and parameters: {'max_depth': 3, 'learning_rate': 0.01171179904316375, 'n_estimators': 344, 'subsample': 0.8869074359509129, 'colsample_bytree': 0.776741928243882, 'min_child_weight': 2, 'gamma': 0.6433999995664115, 'reg_alpha': 0.0002090950551427495, 'reg_lambda': 1.134680201203836, 'max_delta_step': 4}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  75%|███████▌  | 150/200 [02:11<01:09,  1.39s/it]

[I 2025-11-10 17:33:44,944] Trial 149 finished with value: 0.5938791423001949 and parameters: {'max_depth': 3, 'learning_rate': 0.012908896575637952, 'n_estimators': 384, 'subsample': 0.8855181985333945, 'colsample_bytree': 0.7814073630850131, 'min_child_weight': 2, 'gamma': 0.6426241650740983, 'reg_alpha': 0.0001889492227873057, 'reg_lambda': 1.1387991307671168, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  76%|███████▌  | 151/200 [02:11<00:58,  1.19s/it]

[I 2025-11-10 17:33:45,665] Trial 150 finished with value: 0.5902923976608186 and parameters: {'max_depth': 3, 'learning_rate': 0.012032609341974285, 'n_estimators': 434, 'subsample': 0.887540891180358, 'colsample_bytree': 0.7648774892408398, 'min_child_weight': 2, 'gamma': 0.7541366510288543, 'reg_alpha': 0.00047952320625825633, 'reg_lambda': 1.270112466504834, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  76%|███████▌  | 152/200 [02:12<00:46,  1.03it/s]

[I 2025-11-10 17:33:46,124] Trial 151 finished with value: 0.5739961013645225 and parameters: {'max_depth': 3, 'learning_rate': 0.010686386721039203, 'n_estimators': 384, 'subsample': 0.8842297718636788, 'colsample_bytree': 0.7580674925502497, 'min_child_weight': 2, 'gamma': 0.27211989694863986, 'reg_alpha': 0.00048318160099453285, 'reg_lambda': 1.7873150717767115, 'max_delta_step': 6}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  76%|███████▋  | 153/200 [02:12<00:34,  1.35it/s]

[I 2025-11-10 17:33:46,329] Trial 153 pruned.

Best trial: 142. Best value: 0.600292:  77%|███████▋  | 154/200 [02:13<00:36,  1.25it/s]

[I 2025-11-10 17:33:47,264] Trial 152 finished with value: 0.5851072124756336 and parameters: {'max_depth': 3, 'learning_rate': 0.010758339782951593, 'n_estimators': 382, 'subsample': 0.8644526202070223, 'colsample_bytree': 0.8064451608731201, 'min_child_weight': 2, 'gamma': 0.2577015368702089, 'reg_alpha': 0.0004961686371850755, 'reg_lambda': 1.6127377078477054, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  78%|███████▊  | 156/200 [02:17<00:51,  1.17s/it]

[I 2025-11-10 17:33:50,812] Trial 155 finished with value: 0.5923976608187134 and parameters: {'max_depth': 3, 'learning_rate': 0.014774104979090022, 'n_estimators': 428, 'subsample': 0.8634792058368281, 'colsample_bytree': 0.7648093275303425, 'min_child_weight': 2, 'gamma': 0.7728129852684327, 'reg_alpha': 0.0001147877972423026, 'reg_lambda': 2.8440484505538337, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.
[I 2025-11-10 17:33:50,917] Trial 154 finished with value: 0.5916569200779727 and parameters: {'max_depth': 3, 'learning_rate': 0.010450468670081396, 'n_estimators': 449, 'subsample': 0.8631642425103667, 'colsample_bytree': 0.7617577181904774, 'min_child_weight': 2, 'gamma': 0.7671864958814861, 'reg_alpha': 0.0005229949156915623, 'reg_lambda': 1.8670994163890828, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  78%|███████▊  | 157/200 [02:17<00:43,  1.02s/it]

[I 2025-11-10 17:33:51,582] Trial 156 finished with value: 0.5958479532163743 and parameters: {'max_depth': 3, 'learning_rate': 0.014361228490979922, 'n_estimators': 447, 'subsample': 0.8686705205186903, 'colsample_bytree': 0.785499177628508, 'min_child_weight': 2, 'gamma': 0.012826012903476958, 'reg_alpha': 0.0006557843106211057, 'reg_lambda': 2.5915090038377357, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  79%|███████▉  | 158/200 [02:18<00:33,  1.27it/s]

[I 2025-11-10 17:33:51,839] Trial 157 finished with value: 0.5853411306042885 and parameters: {'max_depth': 3, 'learning_rate': 0.014612989304684191, 'n_estimators': 431, 'subsample': 0.8908394625722682, 'colsample_bytree': 0.7668790529464273, 'min_child_weight': 2, 'gamma': 0.005202630942590769, 'reg_alpha': 0.0003104153823537324, 'reg_lambda': 0.1973734164405322, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  80%|███████▉  | 159/200 [02:18<00:33,  1.23it/s]

[I 2025-11-10 17:33:52,699] Trial 161 pruned.

Best trial: 142. Best value: 0.600292:  80%|████████  | 160/200 [02:19<00:29,  1.34it/s]

[I 2025-11-10 17:33:53,298] Trial 162 pruned.

Best trial: 142. Best value: 0.600292:  80%|████████  | 161/200 [02:20<00:32,  1.19it/s]

[I 2025-11-10 17:33:54,351] Trial 163 pruned.

Best trial: 142. Best value: 0.600292:  81%|████████  | 162/200 [02:22<00:41,  1.09s/it]

[I 2025-11-10 17:33:56,023] Trial 159 finished with value: 0.5890643274853801 and parameters: {'max_depth': 3, 'learning_rate': 0.014545831504156786, 'n_estimators': 439, 'subsample': 0.8742408623930257, 'colsample_bytree': 0.7445849823326658, 'min_child_weight': 2, 'gamma': 0.5468896544276685, 'reg_alpha': 0.00011461130574636695, 'reg_lambda': 2.3935613766640538, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  82%|████████▏ | 163/200 [02:22<00:31,  1.18it/s]

[I 2025-11-10 17:33:56,311] Trial 158 finished with value: 0.597953216374269 and parameters: {'max_depth': 3, 'learning_rate': 0.01480512297135565, 'n_estimators': 447, 'subsample': 0.8734487214878524, 'colsample_bytree': 0.763946004331868, 'min_child_weight': 2, 'gamma': 0.03988667312177274, 'reg_alpha': 0.00010737442900227815, 'reg_lambda': 2.5946719805181697, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  82%|████████▏ | 164/200 [02:23<00:34,  1.06it/s]

[I 2025-11-10 17:33:57,485] Trial 160 finished with value: 0.5986939571150097 and parameters: {'max_depth': 3, 'learning_rate': 0.010005981727729134, 'n_estimators': 453, 'subsample': 0.8703271435557252, 'colsample_bytree': 0.7427507225887674, 'min_child_weight': 2, 'gamma': 0.00731839161186143, 'reg_alpha': 0.00031404040933075855, 'reg_lambda': 2.8990936998892884, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  82%|████████▎ | 165/200 [02:26<00:47,  1.36s/it]

[I 2025-11-10 17:33:59,817] Trial 164 finished with value: 0.5883040935672514 and parameters: {'max_depth': 3, 'learning_rate': 0.011870104746103002, 'n_estimators': 457, 'subsample': 0.8733829278385143, 'colsample_bytree': 0.7651644853808873, 'min_child_weight': 2, 'gamma': 0.5599518355224882, 'reg_alpha': 0.0007433485887466857, 'reg_lambda': 0.6912121239254991, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  84%|████████▎ | 167/200 [02:28<00:36,  1.11s/it]

[I 2025-11-10 17:34:01,731] Trial 165 finished with value: 0.5942495126705652 and parameters: {'max_depth': 3, 'learning_rate': 0.011480630882811139, 'n_estimators': 468, 'subsample': 0.8910453699609463, 'colsample_bytree': 0.7660172775600786, 'min_child_weight': 2, 'gamma': 0.5553746400325136, 'reg_alpha': 0.00031558300831413706, 'reg_lambda': 0.9512812311546726, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.
[I 2025-11-10 17:34:01,871] Trial 166 finished with value: 0.5906627680311891 and parameters: {'max_depth': 3, 'learning_rate': 0.011982349595804796, 'n_estimators': 408, 'subsample': 0.8589333920725853, 'colsample_bytree': 0.7670728405708181, 'min_child_weight': 2, 'gamma': 0.11875415230743314, 'reg_alpha': 0.000739814341385197, 'reg_lambda': 5.526876574435865, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  84%|████████▍ | 169/200 [02:29<00:27,  1.11it/s]

[I 2025-11-10 17:34:03,390] Trial 170 pruned.
[I 2025-11-10 17:34:03,518] Trial 167 finished with value: 0.5906627680311891 and parameters: {'max_depth': 3, 'learning_rate': 0.012047987217749087, 'n_estimators': 463, 'subsample': 0.8625780104520598, 'colsample_bytree': 0.7636824730242062, 'min_child_weight': 2, 'gamma': 0.10257890874621822, 'reg_alpha': 0.00027973993958253405, 'reg_lambda': 5.9915657037837535, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  85%|████████▌ | 170/200 [02:31<00:37,  1.26s/it]

[I 2025-11-10 17:34:05,629] Trial 168 finished with value: 0.5907797270955165 and parameters: {'max_depth': 3, 'learning_rate': 0.012721399217541786, 'n_estimators': 473, 'subsample': 0.8576336775829834, 'colsample_bytree': 0.7761816069862446, 'min_child_weight': 2, 'gamma': 0.08981164169829614, 'reg_alpha': 0.00035791602738294374, 'reg_lambda': 4.9996813258680515, 'max_delta_step': 4}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  86%|████████▌ | 171/200 [02:33<00:38,  1.33s/it]

[I 2025-11-10 17:34:07,113] Trial 169 finished with value: 0.5901559454191033 and parameters: {'max_depth': 3, 'learning_rate': 0.010054607081316651, 'n_estimators': 408, 'subsample': 0.8593742112924642, 'colsample_bytree': 0.7837261776480464, 'min_child_weight': 2, 'gamma': 0.0777229289090814, 'reg_alpha': 0.00018317786107748563, 'reg_lambda': 6.613568113458125, 'max_delta_step': 4}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  86%|████████▌ | 172/200 [02:35<00:47,  1.69s/it]

[I 2025-11-10 17:34:09,636] Trial 171 finished with value: 0.5923976608187134 and parameters: {'max_depth': 3, 'learning_rate': 0.010159786692634377, 'n_estimators': 501, 'subsample': 0.8448026019853146, 'colsample_bytree': 0.7794865937086595, 'min_child_weight': 2, 'gamma': 0.02558536894398418, 'reg_alpha': 0.00030209836082465704, 'reg_lambda': 5.403669765745874, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  86%|████████▋ | 173/200 [02:36<00:37,  1.37s/it]

[I 2025-11-10 17:34:10,271] Trial 172 finished with value: 0.5864522417153997 and parameters: {'max_depth': 3, 'learning_rate': 0.010151776971075211, 'n_estimators': 545, 'subsample': 0.8695554381586106, 'colsample_bytree': 0.7789926536713858, 'min_child_weight': 2, 'gamma': 0.15560249224143322, 'reg_alpha': 0.00023352124321885566, 'reg_lambda': 5.256672607102296, 'max_delta_step': 4}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  87%|████████▋ | 174/200 [02:38<00:37,  1.44s/it]

[I 2025-11-10 17:34:11,868] Trial 173 finished with value: 0.5864717348927876 and parameters: {'max_depth': 3, 'learning_rate': 0.010013433597180701, 'n_estimators': 499, 'subsample': 0.841750358152384, 'colsample_bytree': 0.7837112343360776, 'min_child_weight': 2, 'gamma': 0.035892961134345334, 'reg_alpha': 0.0002833394214245872, 'reg_lambda': 4.808496252584098, 'max_delta_step': 4}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  88%|████████▊ | 175/200 [02:39<00:35,  1.43s/it]

[I 2025-11-10 17:34:13,274] Trial 174 finished with value: 0.590916179337232 and parameters: {'max_depth': 3, 'learning_rate': 0.012744813590868351, 'n_estimators': 528, 'subsample': 0.841963564175529, 'colsample_bytree': 0.7726201733696559, 'min_child_weight': 2, 'gamma': 0.2393983169812724, 'reg_alpha': 0.0003084505163613331, 'reg_lambda': 4.036225688240082, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  88%|████████▊ | 176/200 [02:42<00:43,  1.82s/it]

[I 2025-11-10 17:34:16,008] Trial 175 finished with value: 0.5951072124756336 and parameters: {'max_depth': 3, 'learning_rate': 0.010043874079870735, 'n_estimators': 517, 'subsample': 0.8472728318634705, 'colsample_bytree': 0.7784979700816564, 'min_child_weight': 2, 'gamma': 0.017204801489619517, 'reg_alpha': 0.0003546362053938457, 'reg_lambda': 4.792343303662162, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  88%|████████▊ | 177/200 [02:42<00:32,  1.43s/it]

[I 2025-11-10 17:34:16,529] Trial 176 finished with value: 0.590916179337232 and parameters: {'max_depth': 3, 'learning_rate': 0.011303668747423914, 'n_estimators': 521, 'subsample': 0.8476151945332949, 'colsample_bytree': 0.7733834754638331, 'min_child_weight': 2, 'gamma': 0.0008936916513571508, 'reg_alpha': 0.00032159009848937623, 'reg_lambda': 4.547260399142444, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  89%|████████▉ | 178/200 [02:43<00:28,  1.29s/it]

[I 2025-11-10 17:34:17,501] Trial 177 finished with value: 0.5886744639376218 and parameters: {'max_depth': 3, 'learning_rate': 0.011133824766014206, 'n_estimators': 478, 'subsample': 0.8267252642719002, 'colsample_bytree': 0.7719494388230679, 'min_child_weight': 2, 'gamma': 0.1923666911523335, 'reg_alpha': 0.0003038574007410981, 'reg_lambda': 3.9732429019265108, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  90%|████████▉ | 179/200 [02:45<00:27,  1.32s/it]

[I 2025-11-10 17:34:18,888] Trial 178 finished with value: 0.5891812865497077 and parameters: {'max_depth': 3, 'learning_rate': 0.011042096880871818, 'n_estimators': 486, 'subsample': 0.849333495754514, 'colsample_bytree': 0.7726775633624549, 'min_child_weight': 2, 'gamma': 0.2022678587692082, 'reg_alpha': 9.39054537436803e-05, 'reg_lambda': 2.307504739727175, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  90%|█████████ | 180/200 [02:46<00:23,  1.18s/it]

[I 2025-11-10 17:34:19,749] Trial 182 pruned.

Best trial: 142. Best value: 0.600292:  90%|█████████ | 181/200 [02:48<00:28,  1.51s/it]

[I 2025-11-10 17:34:22,039] Trial 179 finished with value: 0.5890643274853801 and parameters: {'max_depth': 3, 'learning_rate': 0.01116715225452593, 'n_estimators': 535, 'subsample': 0.8482252218673889, 'colsample_bytree': 0.7742663883502658, 'min_child_weight': 2, 'gamma': 0.21521146820452308, 'reg_alpha': 9.447694009822505e-05, 'reg_lambda': 2.1196527633500617, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  91%|█████████ | 182/200 [02:48<00:20,  1.15s/it]

[I 2025-11-10 17:34:22,344] Trial 180 finished with value: 0.5805263157894737 and parameters: {'max_depth': 3, 'learning_rate': 0.011033379576486028, 'n_estimators': 530, 'subsample': 0.8253621613072168, 'colsample_bytree': 0.7509649094530693, 'min_child_weight': 2, 'gamma': 0.22312543376364566, 'reg_alpha': 9.591477686026639e-05, 'reg_lambda': 2.1404058585198165, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  92%|█████████▏| 183/200 [02:49<00:19,  1.14s/it]

[I 2025-11-10 17:34:23,451] Trial 181 finished with value: 0.592027290448343 and parameters: {'max_depth': 3, 'learning_rate': 0.010997816850103799, 'n_estimators': 525, 'subsample': 0.8473358223830675, 'colsample_bytree': 0.752724020834896, 'min_child_weight': 2, 'gamma': 0.337313263778688, 'reg_alpha': 0.00014596994695625942, 'reg_lambda': 2.250941653881089, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  92%|█████████▏| 184/200 [02:51<00:23,  1.46s/it]

[I 2025-11-10 17:34:25,662] Trial 183 finished with value: 0.57682261208577 and parameters: {'max_depth': 4, 'learning_rate': 0.011337836952985117, 'n_estimators': 528, 'subsample': 0.8171527841493735, 'colsample_bytree': 0.794642445013192, 'min_child_weight': 2, 'gamma': 0.31447943352109425, 'reg_alpha': 0.000705860366753435, 'reg_lambda': 2.0377617153673286, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  92%|█████████▎| 185/200 [02:52<00:19,  1.32s/it]

[I 2025-11-10 17:34:26,659] Trial 187 pruned.

Best trial: 142. Best value: 0.600292:  93%|█████████▎| 186/200 [02:53<00:15,  1.08s/it]

[I 2025-11-10 17:34:27,178] Trial 188 pruned.

Best trial: 142. Best value: 0.600292:  94%|█████████▍| 188/200 [02:54<00:09,  1.30it/s]

[I 2025-11-10 17:34:28,088] Trial 185 finished with value: 0.5936257309941521 and parameters: {'max_depth': 3, 'learning_rate': 0.012149124302458219, 'n_estimators': 449, 'subsample': 0.8502586046180072, 'colsample_bytree': 0.7898535746526887, 'min_child_weight': 2, 'gamma': 0.32398475911717184, 'reg_alpha': 0.0007283884681125421, 'reg_lambda': 3.1849834370793118, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.
[I 2025-11-10 17:34:28,250] Trial 184 finished with value: 0.5785575048732944 and parameters: {'max_depth': 3, 'learning_rate': 0.012828919499769952, 'n_estimators': 511, 'subsample': 0.826333490299761, 'colsample_bytree': 0.7936870655327993, 'min_child_weight': 2, 'gamma': 0.3482273687090558, 'reg_alpha': 0.0003873235705782477, 'reg_lambda': 3.2717655015825757, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  94%|█████████▍| 189/200 [02:55<00:10,  1.04it/s]

[I 2025-11-10 17:34:29,655] Trial 186 finished with value: 0.5701559454191034 and parameters: {'max_depth': 3, 'learning_rate': 0.012558868273022467, 'n_estimators': 509, 'subsample': 0.8155128741296692, 'colsample_bytree': 0.7975989443846283, 'min_child_weight': 2, 'gamma': 0.37211453882004025, 'reg_alpha': 4.909461899805966e-05, 'reg_lambda': 3.2604415139102803, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  95%|█████████▌| 190/200 [02:56<00:07,  1.31it/s]

[I 2025-11-10 17:34:29,958] Trial 191 pruned.

Best trial: 142. Best value: 0.600292:  96%|█████████▌| 191/200 [02:57<00:07,  1.28it/s]

[I 2025-11-10 17:34:30,773] Trial 193 pruned.

Best trial: 142. Best value: 0.600292:  96%|█████████▌| 192/200 [02:57<00:05,  1.42it/s]

[I 2025-11-10 17:34:31,305] Trial 192 pruned.

Best trial: 142. Best value: 0.600292:  96%|█████████▋| 193/200 [02:59<00:06,  1.00it/s]

[I 2025-11-10 17:34:32,990] Trial 189 finished with value: 0.5920272904483431 and parameters: {'max_depth': 3, 'learning_rate': 0.01009376224225853, 'n_estimators': 456, 'subsample': 0.8474929844875518, 'colsample_bytree': 0.73624677768528, 'min_child_weight': 2, 'gamma': 0.001822055248851595, 'reg_alpha': 0.00035603615922269075, 'reg_lambda': 3.716500130028761, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  97%|█████████▋| 194/200 [02:59<00:05,  1.10it/s]

[I 2025-11-10 17:34:33,685] Trial 190 finished with value: 0.5886939571150098 and parameters: {'max_depth': 3, 'learning_rate': 0.010032450145762208, 'n_estimators': 445, 'subsample': 0.8452871624110592, 'colsample_bytree': 0.7363294697045097, 'min_child_weight': 2, 'gamma': 0.0031244179322575324, 'reg_alpha': 0.0013534923803097748, 'reg_lambda': 3.286141787731303, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  98%|█████████▊| 195/200 [03:00<00:04,  1.09it/s]

[I 2025-11-10 17:34:34,619] Trial 197 pruned.

Best trial: 142. Best value: 0.600292:  98%|█████████▊| 196/200 [03:01<00:03,  1.05it/s]

[I 2025-11-10 17:34:35,673] Trial 195 finished with value: 0.5859649122807018 and parameters: {'max_depth': 3, 'learning_rate': 0.013313048811853264, 'n_estimators': 372, 'subsample': 0.86756058943537, 'colsample_bytree': 0.7803170855226075, 'min_child_weight': 2, 'gamma': 0.43380397866072073, 'reg_alpha': 0.0006096013892967812, 'reg_lambda': 0.7627014607601372, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  98%|█████████▊| 197/200 [03:02<00:02,  1.29it/s]

[I 2025-11-10 17:34:36,034] Trial 194 finished with value: 0.5794152046783625 and parameters: {'max_depth': 3, 'learning_rate': 0.01189218829432625, 'n_estimators': 451, 'subsample': 0.8747222226677329, 'colsample_bytree': 0.7835504656702066, 'min_child_weight': 2, 'gamma': 0.4498816861515789, 'reg_alpha': 0.0005179741834568835, 'reg_lambda': 0.9294440341293847, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292:  99%|█████████▉| 198/200 [03:03<00:01,  1.30it/s]

[I 2025-11-10 17:34:36,773] Trial 199 pruned.

Best trial: 142. Best value: 0.600292: 100%|█████████▉| 199/200 [03:03<00:00,  1.45it/s]

[I 2025-11-10 17:34:37,279] Trial 196 finished with value: 0.5867056530214425 and parameters: {'max_depth': 3, 'learning_rate': 0.010605594083240156, 'n_estimators': 376, 'subsample': 0.8699487773112115, 'colsample_bytree': 0.7319069192928418, 'min_child_weight': 2, 'gamma': 0.16106643103053103, 'reg_alpha': 0.00023254057606650303, 'reg_lambda': 0.4222858215940258, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

Best trial: 142. Best value: 0.600292: 100%|██████████| 200/200 [03:05<00:00,  1.08it/s]

[I 2025-11-10 17:34:39,024] Trial 198 finished with value: 0.5914035087719298 and parameters: {'max_depth': 3, 'learning_rate': 0.011552797608177501, 'n_estimators': 492, 'subsample': 0.8699015348466335, 'colsample_bytree': 0.7831133947243879, 'min_child_weight': 2, 'gamma': 0.15656425164539103, 'reg_alpha': 0.0005372753485987766, 'reg_lambda': 0.9678195814905428, 'max_delta_step': 5}. Best is trial 142 with value: 0.6002923976608188.

[I 2025-11-10 17:34:39,899] A new study created in memory with name: 3_5_roc_auc
Best trial: 1. Best value: 0.5:   0%|          | 1/200 [00:01<05:28,  1.65s/it]

[I 2025-11-10 17:34:41,541] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.019341427864249878, 'n_estimators': 386, 'subsample': 0.5872921787286652, 'colsample_bytree': 0.5858350059146715, 'min_child_weight': 9, 'gamma': 2.2408414231620495, 'reg_alpha': 0.0002468324208434696, 'reg_lambda': 0.013433831009032561, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   1%|          | 2/200 [00:03<05:03,  1.53s/it]

[I 2025-11-10 17:34:42,991] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.04957346667804598, 'n_estimators': 759, 'subsample': 0.5299199498510628, 'colsample_bytree': 0.5032109822889306, 'min_child_weight': 4, 'gamma': 2.1440561381521617, 'reg_alpha': 0.05893842881245984, 'reg_lambda': 4.6540961535911417e-08, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   2%|▏         | 3/200 [00:03<03:20,  1.02s/it]

[I 2025-11-10 17:34:43,397] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.14221311746234636, 'n_estimators': 857, 'subsample': 0.5266394335936396, 'colsample_bytree': 0.6776034009398104, 'min_child_weight': 7, 'gamma': 4.941555642168879, 'reg_alpha': 0.008566620194402793, 'reg_lambda': 0.0032438602844758256, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   2%|▏         | 4/200 [00:05<04:17,  1.31s/it]

[I 2025-11-10 17:34:45,165] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.041946011838337224, 'n_estimators': 508, 'subsample': 0.6236627624111148, 'colsample_bytree': 0.8201785530688057, 'min_child_weight': 10, 'gamma': 0.04919380098637183, 'reg_alpha': 0.03787197055202294, 'reg_lambda': 0.013230236089134683, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   3%|▎         | 6/200 [00:06<02:44,  1.18it/s]

[I 2025-11-10 17:34:46,258] Trial 3 finished with value: 0.4989083820662768 and parameters: {'max_depth': 6, 'learning_rate': 0.10840977677034166, 'n_estimators': 1248, 'subsample': 0.9059869623345729, 'colsample_bytree': 0.6615997534440909, 'min_child_weight': 3, 'gamma': 4.168126317345693, 'reg_alpha': 4.758662617096619e-07, 'reg_lambda': 0.00014127231393954023, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:34:46,364] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.17153392744105314, 'n_estimators': 736, 'subsample': 0.6469195807661304, 'colsample_bytree': 0.5906432883413857, 'min_child_weight': 6, 'gamma': 2.768174197459896, 'reg_alpha': 0.0007547528794032322, 'reg_lambda': 7.828662764488311e-08, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   4%|▎         | 7/200 [00:07<02:33,  1.25it/s]

[I 2025-11-10 17:34:47,051] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01686101595541413, 'n_estimators': 1398, 'subsample': 0.634919355807944, 'colsample_bytree': 0.5479373934071373, 'min_child_weight': 9, 'gamma': 1.7764272093431548, 'reg_alpha': 2.1286815456366243e-05, 'reg_lambda': 4.907316236628362e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   4%|▍         | 8/200 [00:10<05:08,  1.60s/it]

[I 2025-11-10 17:34:50,385] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03025057053966242, 'n_estimators': 1331, 'subsample': 0.8913331837703634, 'colsample_bytree': 0.6433555884809115, 'min_child_weight': 10, 'gamma': 2.16040348733749, 'reg_alpha': 0.009765705846298134, 'reg_lambda': 4.6741349380212643e-07, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 10. Best value: 0.554815:   4%|▍         | 9/200 [00:10<03:48,  1.19s/it]

[I 2025-11-10 17:34:50,678] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.12545281458067906, 'n_estimators': 1093, 'subsample': 0.5888241121284181, 'colsample_bytree': 0.6800117149272759, 'min_child_weight': 5, 'gamma': 0.692269321814214, 'reg_alpha': 0.000827816438118801, 'reg_lambda': 0.00042633285024147984, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:34:50,714] Trial 10 finished with value: 0.5548148148148148 and parameters: {'max_depth': 6, 'learning_rate': 0.01539784869292604, 'n_estimators': 550, 'subsample': 0.5070671789652765, 'colsample_bytree': 0.9466645736221733, 'min_child_weight': 2, 'gamma': 2.3542846227306247, 'reg_alpha': 0.0048017197119416535, 'reg_lambda': 3.125681174128578e-06, 'max_delta_step': 5}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:   6%|▌         | 11/200 [00:12<03:05,  1.02it/s]

[I 2025-11-10 17:34:52,160] Trial 9 finished with value: 0.5308284600389863 and parameters: {'max_depth': 4, 'learning_rate': 0.13608584115039848, 'n_estimators': 1435, 'subsample': 0.7349610333006227, 'colsample_bytree': 0.7102211720552423, 'min_child_weight': 4, 'gamma': 1.2790142292420774, 'reg_alpha': 0.576793803046281, 'reg_lambda': 4.529808021307719e-06, 'max_delta_step': 3}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:   6%|▌         | 12/200 [00:12<02:52,  1.09it/s]

[I 2025-11-10 17:34:52,891] Trial 14 pruned.

Best trial: 10. Best value: 0.554815:   6%|▋         | 13/200 [00:13<02:24,  1.29it/s]

[I 2025-11-10 17:34:53,261] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09810980986970133, 'n_estimators': 767, 'subsample': 0.6898930866403474, 'colsample_bytree': 0.5159986912034338, 'min_child_weight': 8, 'gamma': 2.9623504949338693, 'reg_alpha': 0.5541187382177265, 'reg_lambda': 0.00010571577788923897, 'max_delta_step': 5}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:   7%|▋         | 14/200 [00:14<02:27,  1.26it/s]

[I 2025-11-10 17:34:54,108] Trial 15 pruned.

Best trial: 10. Best value: 0.554815:   8%|▊         | 16/200 [00:14<01:38,  1.87it/s]

[I 2025-11-10 17:34:54,572] Trial 13 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.011769091024891556, 'n_estimators': 570, 'subsample': 0.756355273529453, 'colsample_bytree': 0.9947251057173884, 'min_child_weight': 1, 'gamma': 3.4112174581593626, 'reg_alpha': 8.635633559038292, 'reg_lambda': 8.122333543583935, 'max_delta_step': 10}. Best is trial 10 with value: 0.5548148148148148.
[I 2025-11-10 17:34:54,690] Trial 17 pruned.

Best trial: 10. Best value: 0.554815:   8%|▊         | 17/200 [00:15<01:22,  2.21it/s]

[I 2025-11-10 17:34:54,946] Trial 18 pruned.

Best trial: 10. Best value: 0.554815:   9%|▉         | 18/200 [00:15<01:47,  1.69it/s]

[I 2025-11-10 17:34:55,867] Trial 20 pruned.

Best trial: 10. Best value: 0.554815:  10%|▉         | 19/200 [00:16<01:53,  1.59it/s]

[I 2025-11-10 17:34:56,585] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.054658563637379295, 'n_estimators': 1485, 'subsample': 0.818142759684954, 'colsample_bytree': 0.8390400156544054, 'min_child_weight': 6, 'gamma': 3.5595157542722493, 'reg_alpha': 1.161615737330205e-05, 'reg_lambda': 1.374195801025665, 'max_delta_step': 8}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  10%|█         | 20/200 [00:17<02:06,  1.43it/s]

[I 2025-11-10 17:34:57,461] Trial 22 pruned.
[I 2025-11-10 17:34:57,503] Trial 21 pruned.

Best trial: 10. Best value: 0.554815:  11%|█         | 22/200 [00:18<01:35,  1.86it/s]

[I 2025-11-10 17:34:58,142] Trial 23 pruned.

Best trial: 10. Best value: 0.554815:  12%|█▏        | 23/200 [00:19<01:57,  1.51it/s]

[I 2025-11-10 17:34:59,185] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07506040564000269, 'n_estimators': 1046, 'subsample': 0.7831198122629022, 'colsample_bytree': 0.8294349134298108, 'min_child_weight': 2, 'gamma': 3.297262997747791, 'reg_alpha': 6.840948290152623, 'reg_lambda': 3.3608482324840214e-06, 'max_delta_step': 10}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  12%|█▏        | 24/200 [00:21<02:58,  1.01s/it]

[I 2025-11-10 17:35:01,199] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.16540252224970425, 'n_estimators': 895, 'subsample': 0.5192207718522966, 'colsample_bytree': 0.7243065071782812, 'min_child_weight': 7, 'gamma': 4.7348599311847375, 'reg_alpha': 0.006123673159095592, 'reg_lambda': 0.004194374808010261, 'max_delta_step': 6}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  12%|█▎        | 25/200 [00:21<02:35,  1.13it/s]

[I 2025-11-10 17:35:01,743] Trial 19 finished with value: 0.5173489278752437 and parameters: {'max_depth': 5, 'learning_rate': 0.07595713496685992, 'n_estimators': 1497, 'subsample': 0.8296070646105269, 'colsample_bytree': 0.9019405303039737, 'min_child_weight': 3, 'gamma': 0.6038579083632125, 'reg_alpha': 0.2471659954542703, 'reg_lambda': 1.707476466994652e-05, 'max_delta_step': 7}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  13%|█▎        | 26/200 [00:22<02:17,  1.26it/s]

[I 2025-11-10 17:35:02,287] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.16909984623333052, 'n_estimators': 962, 'subsample': 0.5199485407744151, 'colsample_bytree': 0.7260444543156171, 'min_child_weight': 8, 'gamma': 4.912701467285889, 'reg_alpha': 0.003595673505147641, 'reg_lambda': 0.003453298854052848, 'max_delta_step': 8}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  14%|█▎        | 27/200 [00:23<02:13,  1.30it/s]

[I 2025-11-10 17:35:03,004] Trial 28 pruned.
[I 2025-11-10 17:35:03,085] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1699475678119939, 'n_estimators': 899, 'subsample': 0.5072711650993208, 'colsample_bytree': 0.7009036333007539, 'min_child_weight': 7, 'gamma': 4.706317899363088, 'reg_alpha': 0.003805154797794853, 'reg_lambda': 0.0025569607700347227, 'max_delta_step': 8}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  14%|█▍        | 29/200 [00:23<01:32,  1.85it/s]

[I 2025-11-10 17:35:03,517] Trial 29 pruned.

Best trial: 10. Best value: 0.554815:  15%|█▌        | 30/200 [00:24<01:42,  1.65it/s]

[I 2025-11-10 17:35:04,328] Trial 31 pruned.
[I 2025-11-10 17:35:04,426] Trial 30 pruned.

Best trial: 10. Best value: 0.554815:  16%|█▌        | 32/200 [00:25<01:25,  1.97it/s]

[I 2025-11-10 17:35:05,056] Trial 32 pruned.

Best trial: 10. Best value: 0.554815:  16%|█▋        | 33/200 [00:25<01:36,  1.73it/s]

[I 2025-11-10 17:35:05,878] Trial 33 pruned.

Best trial: 10. Best value: 0.554815:  17%|█▋        | 34/200 [00:26<01:26,  1.92it/s]

[I 2025-11-10 17:35:06,217] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.12092268538474375, 'n_estimators': 399, 'subsample': 0.5585798800184625, 'colsample_bytree': 0.6352560182165843, 'min_child_weight': 5, 'gamma': 1.0896139669008578, 'reg_alpha': 0.0002980354236365261, 'reg_lambda': 0.13492018728919017, 'max_delta_step': 9}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  18%|█▊        | 36/200 [00:26<01:01,  2.65it/s]

[I 2025-11-10 17:35:06,475] Trial 27 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.16418454098513433, 'n_estimators': 1190, 'subsample': 0.5003613814283475, 'colsample_bytree': 0.7701652369604045, 'min_child_weight': 7, 'gamma': 4.642264848426745, 'reg_alpha': 0.00011248825212958479, 'reg_lambda': 0.0009897836380816096, 'max_delta_step': 9}. Best is trial 10 with value: 0.5548148148148148.
[I 2025-11-10 17:35:06,652] Trial 37 pruned.

Best trial: 10. Best value: 0.554815:  18%|█▊        | 37/200 [00:27<01:02,  2.59it/s]

[I 2025-11-10 17:35:07,058] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.14109235308890428, 'n_estimators': 423, 'subsample': 0.5721475964850832, 'colsample_bytree': 0.6452651096159018, 'min_child_weight': 5, 'gamma': 1.0650661328304398, 'reg_alpha': 0.00013588485954641916, 'reg_lambda': 0.02634737462569502, 'max_delta_step': 9}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  19%|█▉        | 38/200 [00:28<01:28,  1.83it/s]

[I 2025-11-10 17:35:08,008] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.13345636068454678, 'n_estimators': 437, 'subsample': 0.5636010062900736, 'colsample_bytree': 0.6078099287046659, 'min_child_weight': 5, 'gamma': 2.5597735468459812, 'reg_alpha': 0.0010730089910575866, 'reg_lambda': 0.03163272776594283, 'max_delta_step': 9}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  20%|█▉        | 39/200 [00:28<01:31,  1.77it/s]

[I 2025-11-10 17:35:08,621] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.13445826685203288, 'n_estimators': 470, 'subsample': 0.5618928546786756, 'colsample_bytree': 0.6021052427776283, 'min_child_weight': 4, 'gamma': 4.1849216735239345, 'reg_alpha': 0.12588150558939212, 'reg_lambda': 0.00011010884093913787, 'max_delta_step': 5}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  20%|██        | 40/200 [00:29<01:45,  1.52it/s]

[I 2025-11-10 17:35:09,500] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.12511703747813527, 'n_estimators': 636, 'subsample': 0.5586095340699575, 'colsample_bytree': 0.6879200288083892, 'min_child_weight': 6, 'gamma': 2.387677628289793, 'reg_alpha': 0.0016101277531253707, 'reg_lambda': 0.03780844554254154, 'max_delta_step': 5}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  20%|██        | 41/200 [00:30<02:07,  1.24it/s]

[I 2025-11-10 17:35:10,656] Trial 40 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.2984198981067986, 'n_estimators': 782, 'subsample': 0.6076177805589861, 'colsample_bytree': 0.7970732185815823, 'min_child_weight': 6, 'gamma': 4.068674890029705, 'reg_alpha': 0.015212671547069552, 'reg_lambda': 9.320734928795269e-08, 'max_delta_step': 4}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  21%|██        | 42/200 [00:31<01:44,  1.51it/s]

[I 2025-11-10 17:35:10,975] Trial 41 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.09604028599392588, 'n_estimators': 656, 'subsample': 0.611335828616298, 'colsample_bytree': 0.679447050410214, 'min_child_weight': 6, 'gamma': 2.1342120400471734, 'reg_alpha': 0.018311229069429318, 'reg_lambda': 0.00014445804536037223, 'max_delta_step': 5}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  22%|██▏       | 43/200 [00:31<01:39,  1.57it/s]

[I 2025-11-10 17:35:11,553] Trial 42 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.06503482499385553, 'n_estimators': 638, 'subsample': 0.5993106752345163, 'colsample_bytree': 0.6908330813176792, 'min_child_weight': 6, 'gamma': 1.9677631684407229, 'reg_alpha': 1.1435855499922605, 'reg_lambda': 1.0398495301766975e-07, 'max_delta_step': 4}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  22%|██▏       | 44/200 [00:32<01:36,  1.62it/s]

[I 2025-11-10 17:35:12,128] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.014085151602438502, 'n_estimators': 312, 'subsample': 0.6535244288593423, 'colsample_bytree': 0.5567028405966576, 'min_child_weight': 9, 'gamma': 2.0775892858103937, 'reg_alpha': 4.0269100608492225e-06, 'reg_lambda': 0.22947029918395986, 'max_delta_step': 3}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  22%|██▎       | 45/200 [00:32<01:26,  1.80it/s]

[I 2025-11-10 17:35:12,541] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.014030463938000774, 'n_estimators': 334, 'subsample': 0.6539545899898582, 'colsample_bytree': 0.5504743647582273, 'min_child_weight': 9, 'gamma': 2.8667616475202475, 'reg_alpha': 0.9999127586565107, 'reg_lambda': 1.072871744328874e-05, 'max_delta_step': 4}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  23%|██▎       | 46/200 [00:33<01:21,  1.89it/s]

[I 2025-11-10 17:35:13,002] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.02340421123137817, 'n_estimators': 319, 'subsample': 0.5400094438290697, 'colsample_bytree': 0.5226552693917436, 'min_child_weight': 9, 'gamma': 2.871920266740047, 'reg_alpha': 5.979372070936276e-06, 'reg_lambda': 9.836060920088107e-06, 'max_delta_step': 6}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  24%|██▎       | 47/200 [00:36<03:15,  1.28s/it]

[I 2025-11-10 17:35:16,044] Trial 43 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.09154326993870543, 'n_estimators': 1495, 'subsample': 0.6245724225764484, 'colsample_bytree': 0.7891460524875331, 'min_child_weight': 8, 'gamma': 1.8587575819879176, 'reg_alpha': 2.1255027029900826, 'reg_lambda': 1.084748194867245e-07, 'max_delta_step': 4}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  24%|██▍       | 49/200 [00:38<02:47,  1.11s/it]

[I 2025-11-10 17:35:18,144] Trial 47 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.025319732736681838, 'n_estimators': 1456, 'subsample': 0.5359082829039258, 'colsample_bytree': 0.5401133724767456, 'min_child_weight': 10, 'gamma': 2.904063052237506, 'reg_alpha': 0.00040261339945522006, 'reg_lambda': 8.479899892917192e-06, 'max_delta_step': 6}. Best is trial 10 with value: 0.5548148148148148.
[I 2025-11-10 17:35:18,292] Trial 48 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.023979264190912442, 'n_estimators': 1426, 'subsample': 0.5388540641920639, 'colsample_bytree': 0.5024754807848929, 'min_child_weight': 10, 'gamma': 2.3350782162914485, 'reg_alpha': 0.0003157666180595886, 'reg_lambda': 0.009059999945266106, 'max_delta_step': 6}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  25%|██▌       | 50/200 [00:38<02:16,  1.10it/s]

[I 2025-11-10 17:35:18,728] Trial 52 pruned.

Best trial: 10. Best value: 0.554815:  26%|██▌       | 51/200 [00:39<01:42,  1.45it/s]

[I 2025-11-10 17:35:18,907] Trial 49 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.015031945352558359, 'n_estimators': 1433, 'subsample': 0.7944674853234277, 'colsample_bytree': 0.6598511657016712, 'min_child_weight': 10, 'gamma': 0.8097613832928725, 'reg_alpha': 0.00029752349421366625, 'reg_lambda': 0.01010564730937241, 'max_delta_step': 7}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  26%|██▌       | 52/200 [00:40<01:57,  1.26it/s]

[I 2025-11-10 17:35:19,932] Trial 53 pruned.

Best trial: 10. Best value: 0.554815:  26%|██▋       | 53/200 [00:40<01:44,  1.40it/s]

[I 2025-11-10 17:35:20,466] Trial 51 pruned.

Best trial: 10. Best value: 0.554815:  27%|██▋       | 54/200 [00:40<01:29,  1.62it/s]

[I 2025-11-10 17:35:20,855] Trial 55 pruned.

Best trial: 10. Best value: 0.554815:  28%|██▊       | 55/200 [00:41<01:27,  1.66it/s]

[I 2025-11-10 17:35:21,420] Trial 56 pruned.

Best trial: 10. Best value: 0.554815:  28%|██▊       | 56/200 [00:41<01:10,  2.05it/s]

[I 2025-11-10 17:35:21,639] Trial 57 pruned.

Best trial: 10. Best value: 0.554815:  28%|██▊       | 57/200 [00:41<00:58,  2.45it/s]

[I 2025-11-10 17:35:21,863] Trial 54 finished with value: 0.507485380116959 and parameters: {'max_depth': 10, 'learning_rate': 0.20548394749333077, 'n_estimators': 541, 'subsample': 0.849788386217873, 'colsample_bytree': 0.9357179894853808, 'min_child_weight': 2, 'gamma': 0.10161528754185967, 'reg_alpha': 0.01825762234024322, 'reg_lambda': 6.907008955103551e-07, 'max_delta_step': 3}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  29%|██▉       | 58/200 [00:42<00:48,  2.90it/s]

[I 2025-11-10 17:35:22,059] Trial 50 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.05571507544916931, 'n_estimators': 1437, 'subsample': 0.7938892475315416, 'colsample_bytree': 0.662945816620166, 'min_child_weight': 10, 'gamma': 0.11875945809334287, 'reg_alpha': 0.00045321799428903756, 'reg_lambda': 0.008572775511396761, 'max_delta_step': 7}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  30%|██▉       | 59/200 [00:42<00:44,  3.17it/s]

[I 2025-11-10 17:35:22,308] Trial 58 pruned.

Best trial: 10. Best value: 0.554815:  30%|███       | 60/200 [00:43<01:35,  1.47it/s]

[I 2025-11-10 17:35:23,843] Trial 59 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.19866867596982982, 'n_estimators': 484, 'subsample': 0.5020102089558274, 'colsample_bytree': 0.7346626694842181, 'min_child_weight': 4, 'gamma': 2.2609709031491767, 'reg_alpha': 4.127867453039226e-05, 'reg_lambda': 5.1882848524942694e-05, 'max_delta_step': 0}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  30%|███       | 61/200 [00:44<01:32,  1.51it/s]

[I 2025-11-10 17:35:24,463] Trial 60 finished with value: 0.5241520467836257 and parameters: {'max_depth': 8, 'learning_rate': 0.19285191903046, 'n_estimators': 474, 'subsample': 0.8466094930780533, 'colsample_bytree': 0.9301028155280872, 'min_child_weight': 2, 'gamma': 0.4660842776618485, 'reg_alpha': 0.07687608894746223, 'reg_lambda': 6.461580379853094e-05, 'max_delta_step': 0}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  31%|███       | 62/200 [00:44<01:14,  1.85it/s]

[I 2025-11-10 17:35:24,714] Trial 61 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.2028284038310517, 'n_estimators': 584, 'subsample': 0.9082254970107926, 'colsample_bytree': 0.9536552083413559, 'min_child_weight': 8, 'gamma': 0.5153046307381649, 'reg_alpha': 0.0043344577507561976, 'reg_lambda': 2.3785033634508573e-07, 'max_delta_step': 0}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  32%|███▏      | 64/200 [00:45<00:50,  2.70it/s]

[I 2025-11-10 17:35:25,034] Trial 62 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.11156426563073962, 'n_estimators': 589, 'subsample': 0.7717099611648259, 'colsample_bytree': 0.9572996431069435, 'min_child_weight': 8, 'gamma': 1.2563959535628892, 'reg_alpha': 0.006936597677057229, 'reg_lambda': 0.0015221519433593611, 'max_delta_step': 5}. Best is trial 10 with value: 0.5548148148148148.
[I 2025-11-10 17:35:25,162] Trial 64 pruned.

Best trial: 10. Best value: 0.554815:  32%|███▎      | 65/200 [00:45<00:46,  2.88it/s]

[I 2025-11-10 17:35:25,458] Trial 65 pruned.

Best trial: 10. Best value: 0.554815:  33%|███▎      | 66/200 [00:45<00:40,  3.27it/s]

[I 2025-11-10 17:35:25,665] Trial 66 pruned.
[I 2025-11-10 17:35:25,672] Trial 67 pruned.

Best trial: 10. Best value: 0.554815:  34%|███▍      | 68/200 [00:45<00:27,  4.80it/s]

[I 2025-11-10 17:35:25,856] Trial 68 pruned.

Best trial: 10. Best value: 0.554815:  34%|███▍      | 69/200 [00:46<00:45,  2.86it/s]

[I 2025-11-10 17:35:26,632] Trial 63 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.012050705829345925, 'n_estimators': 578, 'subsample': 0.848469334259953, 'colsample_bytree': 0.9200724631613065, 'min_child_weight': 7, 'gamma': 0.43889628026075034, 'reg_alpha': 0.08388044945623138, 'reg_lambda': 2.045943165385777e-07, 'max_delta_step': 4}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  35%|███▌      | 70/200 [00:47<00:43,  2.97it/s]

[I 2025-11-10 17:35:26,932] Trial 69 pruned.
[I 2025-11-10 17:35:26,981] Trial 70 pruned.

Best trial: 10. Best value: 0.554815:  36%|███▋      | 73/200 [00:48<00:42,  2.98it/s]

[I 2025-11-10 17:35:27,866] Trial 72 pruned.
[I 2025-11-10 17:35:28,019] Trial 73 pruned.

Best trial: 10. Best value: 0.554815:  37%|███▋      | 74/200 [00:48<00:35,  3.55it/s]

[I 2025-11-10 17:35:28,137] Trial 74 pruned.

Best trial: 10. Best value: 0.554815:  38%|███▊      | 75/200 [00:48<00:35,  3.50it/s]

[I 2025-11-10 17:35:28,433] Trial 71 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.08723993872256042, 'n_estimators': 530, 'subsample': 0.8939425825879396, 'colsample_bytree': 0.967826201760308, 'min_child_weight': 7, 'gamma': 0.9150456244701761, 'reg_alpha': 0.002059346454279448, 'reg_lambda': 5.0066074588808984e-05, 'max_delta_step': 8}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  38%|███▊      | 76/200 [00:49<00:47,  2.61it/s]

[I 2025-11-10 17:35:29,077] Trial 76 pruned.

Best trial: 10. Best value: 0.554815:  38%|███▊      | 77/200 [00:49<00:42,  2.89it/s]

[I 2025-11-10 17:35:29,327] Trial 78 pruned.

Best trial: 10. Best value: 0.554815:  39%|███▉      | 78/200 [00:49<00:45,  2.70it/s]

[I 2025-11-10 17:35:29,762] Trial 77 pruned.

Best trial: 10. Best value: 0.554815:  40%|███▉      | 79/200 [00:50<00:47,  2.53it/s]

[I 2025-11-10 17:35:30,214] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.018237517773792924, 'n_estimators': 461, 'subsample': 0.6862014663646401, 'colsample_bytree': 0.9867719080874637, 'min_child_weight': 4, 'gamma': 3.5715780739188876, 'reg_alpha': 5.455204562423619, 'reg_lambda': 7.192326833124074e-05, 'max_delta_step': 3}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  40%|████      | 80/200 [00:51<01:10,  1.71it/s]

[I 2025-11-10 17:35:31,253] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.17980068495907822, 'n_estimators': 460, 'subsample': 0.6818056802838156, 'colsample_bytree': 0.7506555280609406, 'min_child_weight': 5, 'gamma': 2.6439821207035408, 'reg_alpha': 4.191015834249872, 'reg_lambda': 0.08895518409316842, 'max_delta_step': 2}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  41%|████      | 82/200 [00:51<00:43,  2.69it/s]

[I 2025-11-10 17:35:31,463] Trial 80 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.18145641634551019, 'n_estimators': 458, 'subsample': 0.5470290263788968, 'colsample_bytree': 0.9520221709837021, 'min_child_weight': 5, 'gamma': 3.4999073846560558, 'reg_alpha': 0.7174500539203794, 'reg_lambda': 0.41961769270104987, 'max_delta_step': 6}. Best is trial 10 with value: 0.5548148148148148.
[I 2025-11-10 17:35:31,596] Trial 82 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.176037150934552, 'n_estimators': 270, 'subsample': 0.5467110886236146, 'colsample_bytree': 0.8863101944603258, 'min_child_weight': 5, 'gamma': 1.4706470549174253, 'reg_alpha': 0.008177462917332148, 'reg_lambda': 1.1050389001673095e-08, 'max_delta_step': 6}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  42%|████▏     | 83/200 [00:52<00:43,  2.71it/s]

[I 2025-11-10 17:35:31,958] Trial 81 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.18740571556039223, 'n_estimators': 449, 'subsample': 0.5502430453730195, 'colsample_bytree': 0.8882047266724119, 'min_child_weight': 5, 'gamma': 1.4344228132870636, 'reg_alpha': 0.0007065460354722731, 'reg_lambda': 3.1218656425098525e-07, 'max_delta_step': 6}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  42%|████▏     | 84/200 [00:54<02:02,  1.05s/it]

[I 2025-11-10 17:35:34,625] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.047849680087451295, 'n_estimators': 682, 'subsample': 0.5521450201678477, 'colsample_bytree': 0.888529022886758, 'min_child_weight': 5, 'gamma': 1.4534813662873791, 'reg_alpha': 0.029183681514277155, 'reg_lambda': 1.0523060525776022e-08, 'max_delta_step': 6}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  42%|████▎     | 85/200 [00:57<03:04,  1.60s/it]

[I 2025-11-10 17:35:37,510] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.016759508578701777, 'n_estimators': 1367, 'subsample': 0.6380793163971638, 'colsample_bytree': 0.5203609011311073, 'min_child_weight': 9, 'gamma': 1.821857503199741, 'reg_alpha': 0.0010394597969250721, 'reg_lambda': 1.2306251404118726e-06, 'max_delta_step': 0}. Best is trial 10 with value: 0.5548148148148148.
[I 2025-11-10 17:35:37,526] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01670406179353669, 'n_estimators': 1404, 'subsample': 0.8623568466147014, 'colsample_bytree': 0.5285623054179083, 'min_child_weight': 8, 'gamma': 1.8216991889502574, 'reg_alpha': 1.6616667195650824e-05, 'reg_lambda': 1.0351663145234531e-08, 'max_delta_step': 0}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  44%|████▎     | 87/200 [00:57<01:45,  1.07it/s]

[I 2025-11-10 17:35:37,813] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01697996810831415, 'n_estimators': 1371, 'subsample': 0.6286031365587808, 'colsample_bytree': 0.5168506779880382, 'min_child_weight': 9, 'gamma': 1.7944524127692123, 'reg_alpha': 3.3120755885097964e-05, 'reg_lambda': 1.3177267044184411e-05, 'max_delta_step': 0}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  44%|████▍     | 88/200 [00:58<01:36,  1.16it/s]

[I 2025-11-10 17:35:38,458] Trial 87 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.030438923343079804, 'n_estimators': 855, 'subsample': 0.633520141289712, 'colsample_bytree': 0.5306362928752033, 'min_child_weight': 9, 'gamma': 1.7517531862929663, 'reg_alpha': 3.5305503850885556e-05, 'reg_lambda': 5.7540943690424235e-06, 'max_delta_step': 0}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  44%|████▍     | 89/200 [00:59<01:28,  1.25it/s]

[I 2025-11-10 17:35:39,085] Trial 91 pruned.

Best trial: 10. Best value: 0.554815:  45%|████▌     | 90/200 [01:00<01:46,  1.04it/s]

[I 2025-11-10 17:35:40,494] Trial 92 pruned.

Best trial: 10. Best value: 0.554815:  46%|████▌     | 91/200 [01:01<01:29,  1.22it/s]

[I 2025-11-10 17:35:40,935] Trial 93 pruned.

Best trial: 10. Best value: 0.554815:  46%|████▌     | 92/200 [01:01<01:13,  1.47it/s]

[I 2025-11-10 17:35:41,271] Trial 89 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.02858501387858738, 'n_estimators': 836, 'subsample': 0.5132737569739653, 'colsample_bytree': 0.5646293273368026, 'min_child_weight': 9, 'gamma': 2.4384761570384565, 'reg_alpha': 3.62794504259661e-05, 'reg_lambda': 2.2315360690806164e-05, 'max_delta_step': 5}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  46%|████▋     | 93/200 [01:03<01:55,  1.08s/it]

[I 2025-11-10 17:35:43,337] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.026766368647762575, 'n_estimators': 498, 'subsample': 0.6155828770439686, 'colsample_bytree': 0.9078415777259804, 'min_child_weight': 10, 'gamma': 0.055362608923958834, 'reg_alpha': 0.13182656096013987, 'reg_lambda': 0.04398711085348635, 'max_delta_step': 5}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  47%|████▋     | 94/200 [01:04<01:43,  1.03it/s]

[I 2025-11-10 17:35:44,052] Trial 88 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.021356973020358615, 'n_estimators': 1476, 'subsample': 0.8720041576321984, 'colsample_bytree': 0.538798345056126, 'min_child_weight': 9, 'gamma': 2.028497922704609, 'reg_alpha': 2.114628522261384e-05, 'reg_lambda': 1.283739814516628e-05, 'max_delta_step': 5}. Best is trial 10 with value: 0.5548148148148148.
[I 2025-11-10 17:35:44,090] Trial 90 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.030171113848862254, 'n_estimators': 1466, 'subsample': 0.5777850189618157, 'colsample_bytree': 0.5598710680829069, 'min_child_weight': 9, 'gamma': 1.9864986314551993, 'reg_alpha': 8.150313939739662e-05, 'reg_lambda': 5.7702312727130766e-06, 'max_delta_step': 5}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  48%|████▊     | 96/200 [01:08<02:27,  1.42s/it]

[I 2025-11-10 17:35:47,935] Trial 95 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.06177367715116588, 'n_estimators': 1497, 'subsample': 0.6163460849748525, 'colsample_bytree': 0.9070521893650816, 'min_child_weight': 10, 'gamma': 0.1579808874103202, 'reg_alpha': 0.1890400257808739, 'reg_lambda': 0.01617664506724859, 'max_delta_step': 4}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  48%|████▊     | 97/200 [01:08<02:01,  1.18s/it]

[I 2025-11-10 17:35:48,411] Trial 96 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.037744265195365875, 'n_estimators': 1147, 'subsample': 0.6671520926954958, 'colsample_bytree': 0.8169279831975884, 'min_child_weight': 9, 'gamma': 0.21226181113455939, 'reg_alpha': 0.21349274588497813, 'reg_lambda': 0.0199819406615192, 'max_delta_step': 4}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  49%|████▉     | 98/200 [01:09<01:56,  1.14s/it]

[I 2025-11-10 17:35:49,425] Trial 98 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.06337679846061134, 'n_estimators': 1228, 'subsample': 0.6690757348595086, 'colsample_bytree': 0.8044110802068817, 'min_child_weight': 10, 'gamma': 0.2043179687480458, 'reg_alpha': 0.053781348757280086, 'reg_lambda': 6.189729906975507, 'max_delta_step': 4}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  50%|████▉     | 99/200 [01:10<01:36,  1.05it/s]

[I 2025-11-10 17:35:49,866] Trial 97 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.034519753312491755, 'n_estimators': 1331, 'subsample': 0.6707221886683321, 'colsample_bytree': 0.8268087398874754, 'min_child_weight': 10, 'gamma': 2.1784857914912203, 'reg_alpha': 0.0001596505135535363, 'reg_lambda': 0.020294443435767674, 'max_delta_step': 4}. Best is trial 10 with value: 0.5548148148148148.
[I 2025-11-10 17:35:49,906] Trial 99 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.23076196977258828, 'n_estimators': 412, 'subsample': 0.6673927417025609, 'colsample_bytree': 0.9436894078915229, 'min_child_weight': 8, 'gamma': 1.1784451715933915, 'reg_alpha': 0.000150633345493343, 'reg_lambda': 5.907854023272491e-08, 'max_delta_step': 3}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  50%|█████     | 101/200 [01:12<01:38,  1.01it/s]

[I 2025-11-10 17:35:51,956] Trial 101 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.04918941265896488, 'n_estimators': 549, 'subsample': 0.8362396568911895, 'colsample_bytree': 0.7846948237190216, 'min_child_weight': 8, 'gamma': 2.1601345959484632, 'reg_alpha': 0.0025592731660880226, 'reg_lambda': 5.101746797902143e-08, 'max_delta_step': 3}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  51%|█████     | 102/200 [01:12<01:25,  1.15it/s]

[I 2025-11-10 17:35:52,423] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.07907163254893003, 'n_estimators': 546, 'subsample': 0.837294010268123, 'colsample_bytree': 0.873759682693837, 'min_child_weight': 7, 'gamma': 4.25834410073636, 'reg_alpha': 0.002513497742953337, 'reg_lambda': 0.0005692242753553604, 'max_delta_step': 1}. Best is trial 10 with value: 0.5548148148148148.
[I 2025-11-10 17:35:52,520] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.23180630549826498, 'n_estimators': 552, 'subsample': 0.8323594890784833, 'colsample_bytree': 0.785007544296054, 'min_child_weight': 7, 'gamma': 1.2005185755092258, 'reg_alpha': 0.024440062977162287, 'reg_lambda': 0.0005496733238615584, 'max_delta_step': 3}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  52%|█████▏    | 104/200 [01:14<01:32,  1.03it/s]

[I 2025-11-10 17:35:54,653] Trial 100 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.22276023299165845, 'n_estimators': 1324, 'subsample': 0.5270850953408922, 'colsample_bytree': 0.9404912161288025, 'min_child_weight': 10, 'gamma': 1.112523445830778, 'reg_alpha': 0.0001844873749655697, 'reg_lambda': 0.00043264498901066724, 'max_delta_step': 3}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  52%|█████▎    | 105/200 [01:15<01:19,  1.20it/s]

[I 2025-11-10 17:35:55,032] Trial 104 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1377823322196501, 'n_estimators': 680, 'subsample': 0.6484043969358662, 'colsample_bytree': 0.6536444261520655, 'min_child_weight': 6, 'gamma': 4.233661350779499, 'reg_alpha': 0.00628842976383005, 'reg_lambda': 2.4754807155288714e-08, 'max_delta_step': 3}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  53%|█████▎    | 106/200 [01:15<01:09,  1.35it/s]

[I 2025-11-10 17:35:55,487] Trial 107 pruned.
[I 2025-11-10 17:35:55,670] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.13247007611677405, 'n_estimators': 724, 'subsample': 0.647144969483446, 'colsample_bytree': 0.5973872776374672, 'min_child_weight': 6, 'gamma': 0.011236373909866093, 'reg_alpha': 0.02264983620704286, 'reg_lambda': 2.2705205399058126e-08, 'max_delta_step': 3}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  54%|█████▍    | 108/200 [01:16<00:47,  1.93it/s]

[I 2025-11-10 17:35:55,971] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.13030151823751548, 'n_estimators': 770, 'subsample': 0.5943223024973001, 'colsample_bytree': 0.6066743170928219, 'min_child_weight': 6, 'gamma': 0.01010739385570808, 'reg_alpha': 0.011152564750440179, 'reg_lambda': 1.5727210139919967e-07, 'max_delta_step': 4}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  55%|█████▍    | 109/200 [01:16<00:39,  2.30it/s]

[I 2025-11-10 17:35:56,190] Trial 110 pruned.

Best trial: 10. Best value: 0.554815:  55%|█████▌    | 110/200 [01:16<00:41,  2.15it/s]

[I 2025-11-10 17:35:56,729] Trial 111 pruned.

Best trial: 10. Best value: 0.554815:  56%|█████▌    | 111/200 [01:17<00:36,  2.41it/s]

[I 2025-11-10 17:35:57,019] Trial 112 pruned.

Best trial: 10. Best value: 0.554815:  56%|█████▌    | 112/200 [01:17<00:36,  2.39it/s]

[I 2025-11-10 17:35:57,444] Trial 108 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.1632468732158941, 'n_estimators': 494, 'subsample': 0.5899414135465394, 'colsample_bytree': 0.6804830071788427, 'min_child_weight': 6, 'gamma': 0.725840912011861, 'reg_alpha': 0.0005961565644817665, 'reg_lambda': 1.7146674347507257e-07, 'max_delta_step': 4}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  56%|█████▋    | 113/200 [01:18<00:40,  2.15it/s]

[I 2025-11-10 17:35:58,023] Trial 113 pruned.

Best trial: 10. Best value: 0.554815:  57%|█████▋    | 114/200 [01:18<00:41,  2.09it/s]

[I 2025-11-10 17:35:58,539] Trial 116 pruned.

Best trial: 10. Best value: 0.554815:  57%|█████▊    | 115/200 [01:19<00:43,  1.96it/s]

[I 2025-11-10 17:35:59,123] Trial 109 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.011268272851267655, 'n_estimators': 757, 'subsample': 0.5937127986802102, 'colsample_bytree': 0.5922511195147602, 'min_child_weight': 6, 'gamma': 0.019244427951150223, 'reg_alpha': 0.016823135487408866, 'reg_lambda': 0.003318686338174178, 'max_delta_step': 4}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  58%|█████▊    | 116/200 [01:19<00:38,  2.19it/s]

[I 2025-11-10 17:35:59,451] Trial 115 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.04048378212740299, 'n_estimators': 427, 'subsample': 0.9241110951694236, 'colsample_bytree': 0.5697685580163362, 'min_child_weight': 10, 'gamma': 1.9326857281922156, 'reg_alpha': 0.009616997910785402, 'reg_lambda': 9.877803759976394e-07, 'max_delta_step': 7}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  58%|█████▊    | 117/200 [01:23<01:57,  1.42s/it]

[I 2025-11-10 17:36:03,130] Trial 114 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.04347645279231311, 'n_estimators': 1408, 'subsample': 0.9665195714545554, 'colsample_bytree': 0.6405602997245172, 'min_child_weight': 10, 'gamma': 2.5236902075698833, 'reg_alpha': 0.017550292358936435, 'reg_lambda': 2.1933169610995317e-06, 'max_delta_step': 7}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  60%|█████▉    | 119/200 [01:24<01:26,  1.07s/it]

[I 2025-11-10 17:36:04,662] Trial 117 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.21082926014255307, 'n_estimators': 1424, 'subsample': 0.9591856567586428, 'colsample_bytree': 0.62311121061386, 'min_child_weight': 10, 'gamma': 2.3629034054455738, 'reg_alpha': 0.05492877599934607, 'reg_lambda': 0.0025572247069987467, 'max_delta_step': 9}. Best is trial 10 with value: 0.5548148148148148.
[I 2025-11-10 17:36:04,834] Trial 120 pruned.

Best trial: 10. Best value: 0.554815:  60%|██████    | 120/200 [01:25<01:04,  1.24it/s]

[I 2025-11-10 17:36:05,021] Trial 119 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.033282207954159475, 'n_estimators': 1279, 'subsample': 0.9474838039889817, 'colsample_bytree': 0.7052444724908505, 'min_child_weight': 10, 'gamma': 2.5520535581884762, 'reg_alpha': 0.001289925082520262, 'reg_lambda': 3.669185445894579e-07, 'max_delta_step': 5}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  61%|██████    | 122/200 [01:25<00:39,  1.98it/s]

[I 2025-11-10 17:36:05,337] Trial 122 pruned.
[I 2025-11-10 17:36:05,482] Trial 118 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04266667490389116, 'n_estimators': 1426, 'subsample': 0.9183271444860911, 'colsample_bytree': 0.6434508105563733, 'min_child_weight': 10, 'gamma': 2.3170020818570047, 'reg_alpha': 0.0014911558538864853, 'reg_lambda': 3.249657790459503e-07, 'max_delta_step': 5}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  62%|██████▏   | 123/200 [01:25<00:33,  2.31it/s]

[I 2025-11-10 17:36:05,746] Trial 121 pruned.

Best trial: 10. Best value: 0.554815:  62%|██████▏   | 124/200 [01:28<01:26,  1.14s/it]

[I 2025-11-10 17:36:08,543] Trial 126 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.015469872668760407, 'n_estimators': 647, 'subsample': 0.5616528399929291, 'colsample_bytree': 0.6684933593895964, 'min_child_weight': 5, 'gamma': 0.3662511672971639, 'reg_alpha': 0.03614636611343376, 'reg_lambda': 9.947381480233456e-06, 'max_delta_step': 8}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  62%|██████▎   | 125/200 [01:29<01:09,  1.09it/s]

[I 2025-11-10 17:36:08,945] Trial 123 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.10462621864655738, 'n_estimators': 869, 'subsample': 0.5330797843740998, 'colsample_bytree': 0.7155817540055436, 'min_child_weight': 4, 'gamma': 1.5755623557179346, 'reg_alpha': 0.03282057382391279, 'reg_lambda': 0.0001508577618088244, 'max_delta_step': 8}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  64%|██████▎   | 127/200 [01:29<00:40,  1.81it/s]

[I 2025-11-10 17:36:09,258] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.10272799361857061, 'n_estimators': 859, 'subsample': 0.5644885465274598, 'colsample_bytree': 0.7143908147371189, 'min_child_weight': 5, 'gamma': 0.3956175685378054, 'reg_alpha': 0.004176668136935717, 'reg_lambda': 8.507764550206167e-08, 'max_delta_step': 8}. Best is trial 10 with value: 0.5548148148148148.
[I 2025-11-10 17:36:09,377] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.015168689022584452, 'n_estimators': 850, 'subsample': 0.5347743059349078, 'colsample_bytree': 0.6699162710977143, 'min_child_weight': 4, 'gamma': 0.3574899702402156, 'reg_alpha': 0.03363809350997618, 'reg_lambda': 0.0014117766513363176, 'max_delta_step': 8}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  64%|██████▍   | 128/200 [01:30<00:46,  1.55it/s]

[I 2025-11-10 17:36:10,235] Trial 130 pruned.

Best trial: 10. Best value: 0.554815:  64%|██████▍   | 129/200 [01:32<01:19,  1.12s/it]

[I 2025-11-10 17:36:12,464] Trial 127 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.19572867483611625, 'n_estimators': 859, 'subsample': 0.502926306687032, 'colsample_bytree': 0.7231558585613002, 'min_child_weight': 4, 'gamma': 0.8318156999325957, 'reg_alpha': 0.004815612308236827, 'reg_lambda': 0.0011744251089514256, 'max_delta_step': 8}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  65%|██████▌   | 130/200 [01:32<01:03,  1.10it/s]

[I 2025-11-10 17:36:12,890] Trial 129 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1921450600477539, 'n_estimators': 813, 'subsample': 0.5057654654707247, 'colsample_bytree': 0.653911266464775, 'min_child_weight': 7, 'gamma': 0.5952787506354289, 'reg_alpha': 0.11394232139657799, 'reg_lambda': 0.0008374061256664017, 'max_delta_step': 9}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  66%|██████▌   | 131/200 [01:34<01:23,  1.21s/it]

[I 2025-11-10 17:36:14,780] Trial 128 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.19403737686256006, 'n_estimators': 1347, 'subsample': 0.5077209510754261, 'colsample_bytree': 0.6510405450907063, 'min_child_weight': 7, 'gamma': 4.502962262796161, 'reg_alpha': 0.45544085670778334, 'reg_lambda': 9.197175120869074e-08, 'max_delta_step': 9}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  66%|██████▌   | 132/200 [01:35<01:01,  1.10it/s]

[I 2025-11-10 17:36:14,994] Trial 131 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.013579897313275871, 'n_estimators': 1009, 'subsample': 0.5033904858500261, 'colsample_bytree': 0.9580455428685127, 'min_child_weight': 9, 'gamma': 0.5073557661877486, 'reg_alpha': 0.00022979013686385473, 'reg_lambda': 1.3878756665423168e-06, 'max_delta_step': 1}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  66%|██████▋   | 133/200 [01:36<01:20,  1.20s/it]

[I 2025-11-10 17:36:16,886] Trial 132 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.05770452332530546, 'n_estimators': 1002, 'subsample': 0.582946160958637, 'colsample_bytree': 0.6548033414587011, 'min_child_weight': 9, 'gamma': 0.5523889077535764, 'reg_alpha': 0.00023344001767398339, 'reg_lambda': 3.363735150060558e-05, 'max_delta_step': 0}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  67%|██████▋   | 134/200 [01:38<01:18,  1.19s/it]

[I 2025-11-10 17:36:18,038] Trial 133 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.059697257827567116, 'n_estimators': 1113, 'subsample': 0.6179407055365395, 'colsample_bytree': 0.954591898085059, 'min_child_weight': 8, 'gamma': 1.0089226877893167, 'reg_alpha': 0.06841119157411316, 'reg_lambda': 3.424398484448754e-05, 'max_delta_step': 1}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  68%|██████▊   | 135/200 [01:38<01:01,  1.06it/s]

[I 2025-11-10 17:36:18,406] Trial 135 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.08398001561201573, 'n_estimators': 781, 'subsample': 0.9894984687370842, 'colsample_bytree': 0.5070304454126926, 'min_child_weight': 8, 'gamma': 2.185403595010046, 'reg_alpha': 0.9743802737731827, 'reg_lambda': 3.943296429717721e-05, 'max_delta_step': 6}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  68%|██████▊   | 136/200 [01:39<01:04,  1.01s/it]

[I 2025-11-10 17:36:19,589] Trial 134 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.11556624087814171, 'n_estimators': 1120, 'subsample': 0.6207724935091217, 'colsample_bytree': 0.5019513731523304, 'min_child_weight': 9, 'gamma': 2.703242968797522, 'reg_alpha': 0.24275035153892283, 'reg_lambda': 3.117757262704107e-05, 'max_delta_step': 6}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  68%|██████▊   | 137/200 [01:40<00:52,  1.20it/s]

[I 2025-11-10 17:36:20,010] Trial 136 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09321603755302402, 'n_estimators': 702, 'subsample': 0.6226605104803765, 'colsample_bytree': 0.500057947468279, 'min_child_weight': 8, 'gamma': 2.9378596930149694, 'reg_alpha': 0.21428294506740647, 'reg_lambda': 0.00010729275283884307, 'max_delta_step': 6}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  69%|██████▉   | 138/200 [01:41<00:57,  1.07it/s]

[I 2025-11-10 17:36:21,172] Trial 137 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09342321216299872, 'n_estimators': 715, 'subsample': 0.710499270492039, 'colsample_bytree': 0.7402455926401857, 'min_child_weight': 8, 'gamma': 2.877400891251736, 'reg_alpha': 3.5197034255741583e-07, 'reg_lambda': 8.692286052852297e-05, 'max_delta_step': 6}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  70%|██████▉   | 139/200 [01:41<00:45,  1.33it/s]

[I 2025-11-10 17:36:21,496] Trial 138 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.1162879153313587, 'n_estimators': 714, 'subsample': 0.7257131325760386, 'colsample_bytree': 0.5117501111791629, 'min_child_weight': 7, 'gamma': 0.21295112493407095, 'reg_alpha': 0.24711073731102592, 'reg_lambda': 8.426700853041296e-05, 'max_delta_step': 6}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  70%|███████   | 141/200 [01:41<00:26,  2.25it/s]

[I 2025-11-10 17:36:21,700] Trial 140 pruned.
[I 2025-11-10 17:36:21,815] Trial 139 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.018404610234455186, 'n_estimators': 507, 'subsample': 0.717033911024706, 'colsample_bytree': 0.5149653320502776, 'min_child_weight': 7, 'gamma': 2.796429606158654, 'reg_alpha': 0.1297270608390401, 'reg_lambda': 0.0003417781346096322, 'max_delta_step': 5}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  71%|███████   | 142/200 [01:42<00:22,  2.63it/s]

[I 2025-11-10 17:36:22,044] Trial 141 pruned.

Best trial: 10. Best value: 0.554815:  72%|███████▏  | 143/200 [01:42<00:20,  2.82it/s]

[I 2025-11-10 17:36:22,343] Trial 142 pruned.

Best trial: 10. Best value: 0.554815:  72%|███████▏  | 144/200 [01:43<00:28,  1.93it/s]

[I 2025-11-10 17:36:23,237] Trial 143 pruned.

Best trial: 10. Best value: 0.554815:  72%|███████▎  | 145/200 [01:48<01:42,  1.86s/it]

[I 2025-11-10 17:36:28,223] Trial 144 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.05260414743412237, 'n_estimators': 1480, 'subsample': 0.8193066103333091, 'colsample_bytree': 0.8566109540576914, 'min_child_weight': 6, 'gamma': 3.4114450847036655, 'reg_alpha': 1.482295708023609e-05, 'reg_lambda': 2.2283026859044153, 'max_delta_step': 8}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  73%|███████▎  | 146/200 [01:48<01:13,  1.36s/it]

[I 2025-11-10 17:36:28,423] Trial 145 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.07135234978221017, 'n_estimators': 1464, 'subsample': 0.8153021853435302, 'colsample_bytree': 0.9142470379043968, 'min_child_weight': 6, 'gamma': 3.131827558253416, 'reg_alpha': 0.006433707236393299, 'reg_lambda': 2.1328988936799553, 'max_delta_step': 8}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  74%|███████▎  | 147/200 [01:48<00:57,  1.08s/it]

[I 2025-11-10 17:36:28,846] Trial 146 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.06964642518159776, 'n_estimators': 1494, 'subsample': 0.8137069706585088, 'colsample_bytree': 0.8539636147986429, 'min_child_weight': 6, 'gamma': 3.6752777353095327, 'reg_alpha': 1.226739546907777e-05, 'reg_lambda': 3.2354865981129545e-06, 'max_delta_step': 8}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  74%|███████▍  | 148/200 [01:49<00:51,  1.00it/s]

[I 2025-11-10 17:36:29,636] Trial 147 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1469108331897063, 'n_estimators': 1495, 'subsample': 0.8278043353164457, 'colsample_bytree': 0.8491527836656745, 'min_child_weight': 6, 'gamma': 3.745407419515892, 'reg_alpha': 6.703739254320106e-05, 'reg_lambda': 2.6893758346384478, 'max_delta_step': 8}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  74%|███████▍  | 149/200 [01:52<01:14,  1.46s/it]

[I 2025-11-10 17:36:32,202] Trial 151 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1740128343989536, 'n_estimators': 568, 'subsample': 0.6062421223400052, 'colsample_bytree': 0.8985072038343688, 'min_child_weight': 5, 'gamma': 2.4310221977118607, 'reg_alpha': 1.5801233959999294e-06, 'reg_lambda': 7.985812225844075e-06, 'max_delta_step': 7}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  75%|███████▌  | 150/200 [01:54<01:16,  1.54s/it]

[I 2025-11-10 17:36:33,911] Trial 149 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.14785576896366062, 'n_estimators': 1305, 'subsample': 0.8004076708345934, 'colsample_bytree': 0.8371307840951534, 'min_child_weight': 5, 'gamma': 3.7976413720581337, 'reg_alpha': 3.4940847286747543e-06, 'reg_lambda': 0.3723979998704445, 'max_delta_step': 7}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  76%|███████▌  | 151/200 [01:54<01:00,  1.23s/it]

[I 2025-11-10 17:36:34,436] Trial 148 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.15536222307750683, 'n_estimators': 1453, 'subsample': 0.8064462173368288, 'colsample_bytree': 0.9009069002545299, 'min_child_weight': 6, 'gamma': 3.9400655547627523, 'reg_alpha': 2.21664693643023e-06, 'reg_lambda': 0.3305410788444401, 'max_delta_step': 7}. Best is trial 10 with value: 0.5548148148148148.
[I 2025-11-10 17:36:34,480] Trial 150 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1459133075070538, 'n_estimators': 1449, 'subsample': 0.6576206764346109, 'colsample_bytree': 0.5452205223764371, 'min_child_weight': 5, 'gamma': 2.4206410371227696, 'reg_alpha': 1.4265755359258344e-06, 'reg_lambda': 6.442654099105404e-06, 'max_delta_step': 7}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  76%|███████▋  | 153/200 [01:55<00:39,  1.19it/s]

[I 2025-11-10 17:36:35,213] Trial 155 pruned.
[I 2025-11-10 17:36:35,257] Trial 154 pruned.

Best trial: 10. Best value: 0.554815:  78%|███████▊  | 155/200 [01:55<00:24,  1.83it/s]

[I 2025-11-10 17:36:35,401] Trial 153 pruned.

Best trial: 10. Best value: 0.554815:  79%|███████▉  | 158/200 [01:56<00:16,  2.56it/s]

[I 2025-11-10 17:36:36,111] Trial 157 pruned.
[I 2025-11-10 17:36:36,129] Trial 156 pruned.
[I 2025-11-10 17:36:36,285] Trial 158 pruned.

Best trial: 10. Best value: 0.554815:  80%|███████▉  | 159/200 [01:56<00:16,  2.49it/s]

[I 2025-11-10 17:36:36,728] Trial 159 pruned.

Best trial: 10. Best value: 0.554815:  80%|████████  | 160/200 [01:57<00:17,  2.32it/s]

[I 2025-11-10 17:36:37,255] Trial 160 pruned.

Best trial: 10. Best value: 0.554815:  80%|████████  | 161/200 [01:58<00:20,  1.91it/s]

[I 2025-11-10 17:36:38,046] Trial 152 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.04819705719098433, 'n_estimators': 1387, 'subsample': 0.6589893981425068, 'colsample_bytree': 0.8403828231317074, 'min_child_weight': 5, 'gamma': 1.9115617473723325, 'reg_alpha': 0.015195261113779154, 'reg_lambda': 5.38506991731149e-07, 'max_delta_step': 2}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  81%|████████  | 162/200 [02:00<00:41,  1.09s/it]

[I 2025-11-10 17:36:40,692] Trial 163 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.12419074440119607, 'n_estimators': 891, 'subsample': 0.5167633326456873, 'colsample_bytree': 0.7678930799517028, 'min_child_weight': 10, 'gamma': 3.0502641535029706, 'reg_alpha': 0.024568402802655404, 'reg_lambda': 0.0002090910586383958, 'max_delta_step': 9}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  82%|████████▏ | 163/200 [02:01<00:31,  1.18it/s]

[I 2025-11-10 17:36:40,902] Trial 162 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.12711374596609043, 'n_estimators': 1081, 'subsample': 0.6312556520500952, 'colsample_bytree': 0.7612018987919449, 'min_child_weight': 9, 'gamma': 2.065081163959221, 'reg_alpha': 8.68933795348109, 'reg_lambda': 0.00018524483568632916, 'max_delta_step': 4}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  82%|████████▏ | 164/200 [02:01<00:27,  1.33it/s]

[I 2025-11-10 17:36:41,417] Trial 164 finished with value: 0.5088888888888888 and parameters: {'max_depth': 3, 'learning_rate': 0.019216223499154274, 'n_estimators': 572, 'subsample': 0.7711859483567124, 'colsample_bytree': 0.9630065273595123, 'min_child_weight': 2, 'gamma': 3.091479122903149, 'reg_alpha': 5.402713571657562, 'reg_lambda': 4.395214697831424e-06, 'max_delta_step': 10}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  82%|████████▎ | 165/200 [02:01<00:21,  1.63it/s]

[I 2025-11-10 17:36:41,682] Trial 166 pruned.

Best trial: 10. Best value: 0.554815:  83%|████████▎ | 166/200 [02:03<00:28,  1.19it/s]

[I 2025-11-10 17:36:43,090] Trial 161 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.04723127978677826, 'n_estimators': 1174, 'subsample': 0.6410556414311319, 'colsample_bytree': 0.7734900206560034, 'min_child_weight': 1, 'gamma': 2.0872544733743204, 'reg_alpha': 6.0584683678458555, 'reg_lambda': 0.00018386672586625337, 'max_delta_step': 10}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  84%|████████▎ | 167/200 [02:03<00:27,  1.22it/s]

[I 2025-11-10 17:36:43,854] Trial 169 pruned.

Best trial: 10. Best value: 0.554815:  84%|████████▍ | 169/200 [02:05<00:19,  1.56it/s]

[I 2025-11-10 17:36:44,804] Trial 167 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01852360195192842, 'n_estimators': 582, 'subsample': 0.7455230515567465, 'colsample_bytree': 0.9979828633448152, 'min_child_weight': 2, 'gamma': 3.5498587622023936, 'reg_alpha': 6.883316531111246, 'reg_lambda': 4.734560609768917e-06, 'max_delta_step': 4}. Best is trial 10 with value: 0.5548148148148148.
[I 2025-11-10 17:36:44,934] Trial 168 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.019200084285654142, 'n_estimators': 564, 'subsample': 0.7567309789340235, 'colsample_bytree': 0.96579233340651, 'min_child_weight': 2, 'gamma': 3.5526986315395868, 'reg_alpha': 7.232894710258714, 'reg_lambda': 3.6496259545846624e-08, 'max_delta_step': 10}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  85%|████████▌ | 170/200 [02:05<00:16,  1.83it/s]

[I 2025-11-10 17:36:45,253] Trial 171 pruned.

Best trial: 10. Best value: 0.554815:  86%|████████▌ | 171/200 [02:06<00:17,  1.61it/s]

[I 2025-11-10 17:36:46,054] Trial 173 pruned.

Best trial: 10. Best value: 0.554815:  86%|████████▋ | 173/200 [02:06<00:12,  2.20it/s]

[I 2025-11-10 17:36:46,538] Trial 172 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.025723811698395733, 'n_estimators': 339, 'subsample': 0.7664520999747555, 'colsample_bytree': 0.8145193526120333, 'min_child_weight': 7, 'gamma': 0.6691650136613394, 'reg_alpha': 0.08270516769796547, 'reg_lambda': 0.002131691792584036, 'max_delta_step': 3}. Best is trial 10 with value: 0.5548148148148148.
[I 2025-11-10 17:36:46,696] Trial 165 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.05364057586630445, 'n_estimators': 1054, 'subsample': 0.7445444711917438, 'colsample_bytree': 0.8169461864874807, 'min_child_weight': 2, 'gamma': 0.0881175038879224, 'reg_alpha': 7.256781188400076, 'reg_lambda': 2.1119405444599077e-06, 'max_delta_step': 10}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  87%|████████▋ | 174/200 [02:07<00:12,  2.10it/s]

[I 2025-11-10 17:36:47,221] Trial 174 pruned.

Best trial: 10. Best value: 0.554815:  88%|████████▊ | 175/200 [02:07<00:12,  2.03it/s]

[I 2025-11-10 17:36:47,749] Trial 176 pruned.

Best trial: 10. Best value: 0.554815:  88%|████████▊ | 176/200 [02:08<00:12,  1.93it/s]

[I 2025-11-10 17:36:48,336] Trial 178 pruned.

Best trial: 10. Best value: 0.554815:  88%|████████▊ | 177/200 [02:09<00:14,  1.55it/s]

[I 2025-11-10 17:36:49,279] Trial 175 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.054209107177695524, 'n_estimators': 476, 'subsample': 0.542962105397435, 'colsample_bytree': 0.9290059183745822, 'min_child_weight': 2, 'gamma': 3.321389849856055, 'reg_alpha': 8.58791775633121, 'reg_lambda': 2.7192502655974774e-06, 'max_delta_step': 10}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  89%|████████▉ | 178/200 [02:09<00:11,  1.90it/s]

[I 2025-11-10 17:36:49,524] Trial 177 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08561968464648954, 'n_estimators': 479, 'subsample': 0.776522279609519, 'colsample_bytree': 0.9258184864571561, 'min_child_weight': 9, 'gamma': 1.334261681442523, 'reg_alpha': 2.2524999546497204, 'reg_lambda': 8.967061908144536e-06, 'max_delta_step': 9}. Best is trial 10 with value: 0.5548148148148148.
[I 2025-11-10 17:36:49,546] Trial 170 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.019400845456471312, 'n_estimators': 1251, 'subsample': 0.7541646816213856, 'colsample_bytree': 0.9753607474252801, 'min_child_weight': 4, 'gamma': 0.11427343637207771, 'reg_alpha': 8.561426366357255, 'reg_lambda': 4.7462847144136104e-06, 'max_delta_step': 10}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  90%|█████████ | 180/200 [02:12<00:20,  1.02s/it]

[I 2025-11-10 17:36:52,700] Trial 180 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.16881136925594603, 'n_estimators': 781, 'subsample': 0.8777961729395152, 'colsample_bytree': 0.6257563763337648, 'min_child_weight': 10, 'gamma': 3.114194073817957, 'reg_alpha': 2.7087947402025545, 'reg_lambda': 2.0087647738982706e-08, 'max_delta_step': 4}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  90%|█████████ | 181/200 [02:13<00:16,  1.18it/s]

[I 2025-11-10 17:36:53,034] Trial 182 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10487035325716951, 'n_estimators': 788, 'subsample': 0.8778527145395962, 'colsample_bytree': 0.6947560148101679, 'min_child_weight': 8, 'gamma': 2.5422684121713655, 'reg_alpha': 2.6449325969813987e-05, 'reg_lambda': 1.789391061568337e-08, 'max_delta_step': 4}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  91%|█████████ | 182/200 [02:15<00:20,  1.12s/it]

[I 2025-11-10 17:36:54,927] Trial 179 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09667334866538232, 'n_estimators': 1411, 'subsample': 0.878267001005799, 'colsample_bytree': 0.9235641782027321, 'min_child_weight': 10, 'gamma': 4.574202804113545, 'reg_alpha': 3.0069806152976466, 'reg_lambda': 0.02694358129829447, 'max_delta_step': 0}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  92%|█████████▏| 183/200 [02:15<00:15,  1.13it/s]

[I 2025-11-10 17:36:55,192] Trial 181 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10099880550638178, 'n_estimators': 1257, 'subsample': 0.8721011779466473, 'colsample_bytree': 0.82717664643472, 'min_child_weight': 10, 'gamma': 0.4531518717311086, 'reg_alpha': 2.9316837984915427, 'reg_lambda': 5.940092121559092e-08, 'max_delta_step': 0}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  92%|█████████▏| 184/200 [02:16<00:17,  1.07s/it]

[I 2025-11-10 17:36:56,717] Trial 184 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1371899080168262, 'n_estimators': 836, 'subsample': 0.570350351600319, 'colsample_bytree': 0.7301474177197387, 'min_child_weight': 7, 'gamma': 4.883830205511062, 'reg_alpha': 0.003307490789876723, 'reg_lambda': 6.387188451557334e-08, 'max_delta_step': 6}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  92%|█████████▎| 185/200 [02:18<00:19,  1.32s/it]

[I 2025-11-10 17:36:58,689] Trial 185 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.21092802516805817, 'n_estimators': 819, 'subsample': 0.8287087152397296, 'colsample_bytree': 0.7386379299086483, 'min_child_weight': 7, 'gamma': 4.813480779707911, 'reg_alpha': 0.002692808898842537, 'reg_lambda': 0.004152004625316944, 'max_delta_step': 7}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  93%|█████████▎| 186/200 [02:19<00:14,  1.00s/it]

[I 2025-11-10 17:36:58,910] Trial 183 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.10877460055339631, 'n_estimators': 1414, 'subsample': 0.8213239039214498, 'colsample_bytree': 0.7275884162346821, 'min_child_weight': 8, 'gamma': 2.5530366378120553, 'reg_alpha': 0.0027625622163846863, 'reg_lambda': 4.287230252774386e-08, 'max_delta_step': 0}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  94%|█████████▎| 187/200 [02:19<00:10,  1.27it/s]

[I 2025-11-10 17:36:59,174] Trial 186 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.21697630597677456, 'n_estimators': 888, 'subsample': 0.5686248338614557, 'colsample_bytree': 0.7273929942960848, 'min_child_weight': 7, 'gamma': 4.85962420321493, 'reg_alpha': 0.0460041706950665, 'reg_lambda': 0.009739261288041829, 'max_delta_step': 7}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  94%|█████████▍| 188/200 [02:20<00:11,  1.01it/s]

[I 2025-11-10 17:37:00,645] Trial 187 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.17879050485208994, 'n_estimators': 897, 'subsample': 0.8224386362743014, 'colsample_bytree': 0.6832701522354941, 'min_child_weight': 7, 'gamma': 4.747818108341039, 'reg_alpha': 0.009029112586884819, 'reg_lambda': 3.660242746671596e-06, 'max_delta_step': 5}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  94%|█████████▍| 189/200 [02:22<00:11,  1.08s/it]

[I 2025-11-10 17:37:01,927] Trial 189 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.17901534734389335, 'n_estimators': 684, 'subsample': 0.5572034822778033, 'colsample_bytree': 0.6772849897804216, 'min_child_weight': 6, 'gamma': 4.363472363755382, 'reg_alpha': 0.00847542878101637, 'reg_lambda': 0.010567533896946745, 'max_delta_step': 6}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  95%|█████████▌| 190/200 [02:22<00:09,  1.00it/s]

[I 2025-11-10 17:37:02,736] Trial 188 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.17912412704947137, 'n_estimators': 900, 'subsample': 0.5228797503210055, 'colsample_bytree': 0.6774800711160611, 'min_child_weight': 6, 'gamma': 3.0015544406472063, 'reg_alpha': 0.0009856423436600916, 'reg_lambda': 0.0008202458660778892, 'max_delta_step': 6}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  96%|█████████▌| 191/200 [02:24<00:10,  1.14s/it]

[I 2025-11-10 17:37:04,203] Trial 190 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.015837782607292846, 'n_estimators': 1155, 'subsample': 0.5181550248258231, 'colsample_bytree': 0.675354331728145, 'min_child_weight': 6, 'gamma': 1.691643243455164, 'reg_alpha': 0.008856851465638783, 'reg_lambda': 1.1200891733245702e-05, 'max_delta_step': 6}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  96%|█████████▌| 192/200 [02:24<00:07,  1.08it/s]

[I 2025-11-10 17:37:04,637] Trial 192 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.011189767070907136, 'n_estimators': 604, 'subsample': 0.5190271875167733, 'colsample_bytree': 0.6341858315256308, 'min_child_weight': 6, 'gamma': 2.9345275074972035, 'reg_alpha': 0.0018463817829459334, 'reg_lambda': 1.310779199806041e-07, 'max_delta_step': 5}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  96%|█████████▋| 193/200 [02:27<00:09,  1.35s/it]

[I 2025-11-10 17:37:06,978] Trial 194 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.15227696489892356, 'n_estimators': 602, 'subsample': 0.542542495506921, 'colsample_bytree': 0.7512554468195118, 'min_child_weight': 8, 'gamma': 4.654383081505687, 'reg_alpha': 0.0049488121879381125, 'reg_lambda': 4.212828726167457, 'max_delta_step': 8}. Best is trial 10 with value: 0.5548148148148148.
[I 2025-11-10 17:37:07,153] Trial 191 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01564598085448682, 'n_estimators': 1468, 'subsample': 0.515187629346487, 'colsample_bytree': 0.7143773194053952, 'min_child_weight': 6, 'gamma': 4.644107269841882, 'reg_alpha': 0.0009077997716856665, 'reg_lambda': 0.0007350406645555595, 'max_delta_step': 6}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  98%|█████████▊| 195/200 [02:28<00:05,  1.16s/it]

[I 2025-11-10 17:37:08,694] Trial 193 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.015814260975396073, 'n_estimators': 1357, 'subsample': 0.6784022571941157, 'colsample_bytree': 0.5195998541075347, 'min_child_weight': 9, 'gamma': 4.981985173156355, 'reg_alpha': 0.00010929433971214875, 'reg_lambda': 9.685064424002614e-06, 'max_delta_step': 5}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  98%|█████████▊| 196/200 [02:29<00:03,  1.11it/s]

[I 2025-11-10 17:37:09,001] Trial 195 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.2046982383078051, 'n_estimators': 953, 'subsample': 0.545969615402417, 'colsample_bytree': 0.7548891167948591, 'min_child_weight': 8, 'gamma': 4.984470268084598, 'reg_alpha': 0.0049535130617607125, 'reg_lambda': 0.005407736490384315, 'max_delta_step': 8}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815:  98%|█████████▊| 197/200 [02:29<00:02,  1.12it/s]

[I 2025-11-10 17:37:09,869] Trial 198 pruned.

Best trial: 10. Best value: 0.554815: 100%|█████████▉| 199/200 [02:31<00:00,  1.45it/s]

[I 2025-11-10 17:37:10,816] Trial 196 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1587276441550188, 'n_estimators': 952, 'subsample': 0.5375810484682133, 'colsample_bytree': 0.7155522216118343, 'min_child_weight': 8, 'gamma': 4.8762632790998675, 'reg_alpha': 0.00010470885448320284, 'reg_lambda': 0.0028813469572945226, 'max_delta_step': 8}. Best is trial 10 with value: 0.5548148148148148.
[I 2025-11-10 17:37:10,993] Trial 197 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.16299702431832724, 'n_estimators': 1002, 'subsample': 0.5346145804891298, 'colsample_bytree': 0.7194596207048185, 'min_child_weight': 9, 'gamma': 4.920500517434949, 'reg_alpha': 1.291491408703478e-08, 'reg_lambda': 0.00327614847645529, 'max_delta_step': 8}. Best is trial 10 with value: 0.5548148148148148.

Best trial: 10. Best value: 0.554815: 100%|██████████| 200/200 [02:31<00:00,  1.32it/s]

[I 2025-11-10 17:37:11,808] Trial 199 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.16965167895101027, 'n_estimators': 974, 'subsample': 0.531327664036579, 'colsample_bytree': 0.6981645666072126, 'min_child_weight': 8, 'gamma': 2.230200373134738, 'reg_alpha': 0.023201627877747218, 'reg_lambda': 0.002634778705997478, 'max_delta_step': 8}. Best is trial 10 with value: 0.5548148148148148.

[I 2025-11-10 17:37:12,828] A new study created in memory with name: 9_1_roc_auc
Best trial: 2. Best value: 0.511367:   0%|          | 1/200 [00:04<14:44,  4.44s/it]

[I 2025-11-10 17:37:17,266] Trial 2 finished with value: 0.5113674560733383 and parameters: {'max_depth': 9, 'learning_rate': 0.03479780946823029, 'n_estimators': 309, 'subsample': 0.9967749465271176, 'colsample_bytree': 0.7857764665398677, 'min_child_weight': 2, 'gamma': 2.054942902365953, 'reg_alpha': 0.04111804513105583, 'reg_lambda': 0.04246813082963235, 'max_delta_step': 8}. Best is trial 2 with value: 0.5113674560733383.

Best trial: 1. Best value: 0.512032:   1%|          | 2/200 [00:09<16:28,  4.99s/it]

[I 2025-11-10 17:37:22,642] Trial 1 finished with value: 0.5120320855614973 and parameters: {'max_depth': 5, 'learning_rate': 0.020705163575918815, 'n_estimators': 876, 'subsample': 0.8589488569777497, 'colsample_bytree': 0.7120400650741474, 'min_child_weight': 3, 'gamma': 2.2092345475415294, 'reg_alpha': 6.228005780041737e-08, 'reg_lambda': 3.2084867847050607e-06, 'max_delta_step': 3}. Best is trial 1 with value: 0.5120320855614973.

Best trial: 1. Best value: 0.512032:   2%|▏         | 3/200 [00:12<12:12,  3.72s/it]

[I 2025-11-10 17:37:24,846] Trial 3 finished with value: 0.5084889228418641 and parameters: {'max_depth': 9, 'learning_rate': 0.12338318106357381, 'n_estimators': 1103, 'subsample': 0.9525762333855313, 'colsample_bytree': 0.780131355097488, 'min_child_weight': 1, 'gamma': 3.8340439204113785, 'reg_alpha': 1.2848681798881014e-07, 'reg_lambda': 0.09264317965753341, 'max_delta_step': 1}. Best is trial 1 with value: 0.5120320855614973.

Best trial: 0. Best value: 0.5405:   2%|▏         | 4/200 [00:12<07:37,  2.34s/it]

[I 2025-11-10 17:37:25,058] Trial 0 finished with value: 0.5404996180290297 and parameters: {'max_depth': 8, 'learning_rate': 0.011667720743109336, 'n_estimators': 1473, 'subsample': 0.7119992016927564, 'colsample_bytree': 0.818606382263428, 'min_child_weight': 5, 'gamma': 4.223815816597127, 'reg_alpha': 0.17992202417021175, 'reg_lambda': 2.1177889404794615e-05, 'max_delta_step': 0}. Best is trial 0 with value: 0.5404996180290297.

Best trial: 0. Best value: 0.5405:   2%|▎         | 5/200 [00:12<05:30,  1.70s/it]

[I 2025-11-10 17:37:25,620] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.027554019709729018, 'n_estimators': 479, 'subsample': 0.5935054923314449, 'colsample_bytree': 0.6632322377737442, 'min_child_weight': 6, 'gamma': 1.2855431292344073, 'reg_alpha': 4.247233315307554, 'reg_lambda': 4.324483371374495e-05, 'max_delta_step': 0}. Best is trial 0 with value: 0.5404996180290297.

Best trial: 0. Best value: 0.5405:   3%|▎         | 6/200 [00:14<05:21,  1.66s/it]

[I 2025-11-10 17:37:27,207] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07172476973305918, 'n_estimators': 351, 'subsample': 0.6861143513344843, 'colsample_bytree': 0.6895686254481443, 'min_child_weight': 8, 'gamma': 3.6114242479762932, 'reg_alpha': 7.058927372991395e-08, 'reg_lambda': 0.00022374233429814657, 'max_delta_step': 8}. Best is trial 0 with value: 0.5404996180290297.

Best trial: 0. Best value: 0.5405:   4%|▎         | 7/200 [00:15<05:07,  1.59s/it]

[I 2025-11-10 17:37:28,660] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.043483601418985836, 'n_estimators': 420, 'subsample': 0.5968130414080461, 'colsample_bytree': 0.6769771131737334, 'min_child_weight': 10, 'gamma': 3.7012551441034387, 'reg_alpha': 5.246411250079086e-05, 'reg_lambda': 1.3354032472569295e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5404996180290297.
[I 2025-11-10 17:37:28,711] Trial 4 finished with value: 0.5156577540106951 and parameters: {'max_depth': 4, 'learning_rate': 0.022492633675812803, 'n_estimators': 623, 'subsample': 0.9996917974109176, 'colsample_bytree': 0.8643129358703909, 'min_child_weight': 5, 'gamma': 0.16089805605900065, 'reg_alpha': 0.17335057376568033, 'reg_lambda': 0.031383523253861206, 'max_delta_step': 6}. Best is trial 0 with value: 0.5404996180290297.

Best trial: 0. Best value: 0.5405:   4%|▍         | 9/200 [00:21<07:13,  2.27s/it]

[I 2025-11-10 17:37:34,659] Trial 9 finished with value: 0.5090771581359818 and parameters: {'max_depth': 3, 'learning_rate': 0.02195222616892095, 'n_estimators': 386, 'subsample': 0.9631984674629581, 'colsample_bytree': 0.5047811046990145, 'min_child_weight': 4, 'gamma': 0.23589131555174003, 'reg_alpha': 6.927498054703026e-05, 'reg_lambda': 0.08581890404855372, 'max_delta_step': 7}. Best is trial 0 with value: 0.5404996180290297.

Best trial: 7. Best value: 0.596672:   5%|▌         | 10/200 [00:22<05:34,  1.76s/it]

[I 2025-11-10 17:37:34,932] Trial 7 finished with value: 0.596672268907563 and parameters: {'max_depth': 3, 'learning_rate': 0.07681327489791473, 'n_estimators': 1457, 'subsample': 0.6852458735489184, 'colsample_bytree': 0.6064796098009828, 'min_child_weight': 7, 'gamma': 3.195279485190941, 'reg_alpha': 1.6640932603029964e-06, 'reg_lambda': 0.007642707716610215, 'max_delta_step': 2}. Best is trial 7 with value: 0.596672268907563.

Best trial: 7. Best value: 0.596672:   6%|▌         | 11/200 [00:23<05:01,  1.60s/it]

[I 2025-11-10 17:37:36,088] Trial 11 finished with value: 0.5501604278074865 and parameters: {'max_depth': 3, 'learning_rate': 0.050210279074251275, 'n_estimators': 888, 'subsample': 0.9686488919126351, 'colsample_bytree': 0.7287183077763608, 'min_child_weight': 7, 'gamma': 4.57644664218765, 'reg_alpha': 4.844216058234894e-06, 'reg_lambda': 0.00021026825757143228, 'max_delta_step': 2}. Best is trial 7 with value: 0.596672268907563.

Best trial: 7. Best value: 0.596672:   6%|▌         | 12/200 [00:23<04:11,  1.34s/it]

[I 2025-11-10 17:37:36,751] Trial 10 pruned.

Best trial: 7. Best value: 0.596672:   6%|▋         | 13/200 [00:24<03:09,  1.02s/it]

[I 2025-11-10 17:37:36,951] Trial 13 pruned.

Best trial: 7. Best value: 0.596672:   7%|▋         | 14/200 [00:25<03:16,  1.06s/it]

[I 2025-11-10 17:37:38,117] Trial 14 pruned.

Best trial: 7. Best value: 0.596672:   8%|▊         | 15/200 [00:31<08:01,  2.61s/it]

[I 2025-11-10 17:37:44,479] Trial 16 finished with value: 0.5903720397249808 and parameters: {'max_depth': 7, 'learning_rate': 0.08219071958442985, 'n_estimators': 1084, 'subsample': 0.8297339367110649, 'colsample_bytree': 0.5806023695998128, 'min_child_weight': 7, 'gamma': 3.012486876784481, 'reg_alpha': 2.772183738485825e-06, 'reg_lambda': 0.004358996010065178, 'max_delta_step': 3}. Best is trial 7 with value: 0.596672268907563.
[I 2025-11-10 17:37:44,498] Trial 12 finished with value: 0.584192513368984 and parameters: {'max_depth': 8, 'learning_rate': 0.23050386359548505, 'n_estimators': 1128, 'subsample': 0.6656416638922313, 'colsample_bytree': 0.8030962303192972, 'min_child_weight': 1, 'gamma': 0.1596472238538471, 'reg_alpha': 0.015157089180887201, 'reg_lambda': 2.365496208987457e-08, 'max_delta_step': 9}. Best is trial 7 with value: 0.596672268907563.

Best trial: 7. Best value: 0.596672:   8%|▊         | 17/200 [00:32<04:57,  1.63s/it]

[I 2025-11-10 17:37:45,383] Trial 17 finished with value: 0.5783292589763177 and parameters: {'max_depth': 4, 'learning_rate': 0.07870286925920093, 'n_estimators': 1058, 'subsample': 0.8179383988340692, 'colsample_bytree': 0.60069360251189, 'min_child_weight': 7, 'gamma': 2.887694346689252, 'reg_alpha': 0.001959015138813059, 'reg_lambda': 0.0013575397121637018, 'max_delta_step': 10}. Best is trial 7 with value: 0.596672268907563.

Best trial: 7. Best value: 0.596672:   9%|▉         | 18/200 [00:33<04:04,  1.34s/it]

[I 2025-11-10 17:37:45,853] Trial 15 finished with value: 0.5929243697478992 and parameters: {'max_depth': 6, 'learning_rate': 0.08789023519251375, 'n_estimators': 1120, 'subsample': 0.8262418604953397, 'colsample_bytree': 0.9758085846595499, 'min_child_weight': 7, 'gamma': 4.910688855005509, 'reg_alpha': 4.083482729891757e-06, 'reg_lambda': 0.0044636566035866215, 'max_delta_step': 3}. Best is trial 7 with value: 0.596672268907563.

Best trial: 7. Best value: 0.596672:  10%|▉         | 19/200 [00:33<03:42,  1.23s/it]

[I 2025-11-10 17:37:46,756] Trial 20 pruned.

Best trial: 7. Best value: 0.596672:  10%|█         | 20/200 [00:34<03:17,  1.10s/it]

[I 2025-11-10 17:37:47,493] Trial 21 pruned.

Best trial: 7. Best value: 0.596672:  10%|█         | 21/200 [00:36<03:28,  1.16s/it]

[I 2025-11-10 17:37:48,830] Trial 23 pruned.

Best trial: 7. Best value: 0.596672:  11%|█         | 22/200 [00:39<05:39,  1.91s/it]

[I 2025-11-10 17:37:52,612] Trial 19 finished with value: 0.569318563789152 and parameters: {'max_depth': 7, 'learning_rate': 0.09223098172896868, 'n_estimators': 1128, 'subsample': 0.799262201946183, 'colsample_bytree': 0.6022141695230698, 'min_child_weight': 6, 'gamma': 2.9990947549052023, 'reg_alpha': 0.0005986674009559037, 'reg_lambda': 0.0027783328467926843, 'max_delta_step': 4}. Best is trial 7 with value: 0.596672268907563.
[I 2025-11-10 17:37:52,686] Trial 18 finished with value: 0.5693582887700535 and parameters: {'max_depth': 7, 'learning_rate': 0.0772778278008245, 'n_estimators': 1176, 'subsample': 0.7951389203830062, 'colsample_bytree': 0.5064000970469362, 'min_child_weight': 6, 'gamma': 2.920625089111762, 'reg_alpha': 0.0020417980114231732, 'reg_lambda': 0.0025151130460016277, 'max_delta_step': 10}. Best is trial 7 with value: 0.596672268907563.

Best trial: 7. Best value: 0.596672:  12%|█▏        | 24/200 [00:40<03:38,  1.24s/it]

[I 2025-11-10 17:37:53,463] Trial 22 finished with value: 0.5822383498854087 and parameters: {'max_depth': 6, 'learning_rate': 0.14729302010853793, 'n_estimators': 705, 'subsample': 0.910577838677691, 'colsample_bytree': 0.972803703529159, 'min_child_weight': 6, 'gamma': 1.5249139866683947, 'reg_alpha': 1.0700756784151226e-08, 'reg_lambda': 8.547844699289024e-07, 'max_delta_step': 5}. Best is trial 7 with value: 0.596672268907563.

Best trial: 7. Best value: 0.596672:  12%|█▎        | 25/200 [00:41<03:37,  1.24s/it]

[I 2025-11-10 17:37:54,710] Trial 27 pruned.

Best trial: 24. Best value: 0.60269:  13%|█▎        | 26/200 [00:42<03:25,  1.18s/it]

[I 2025-11-10 17:37:55,697] Trial 24 finished with value: 0.6026898395721926 and parameters: {'max_depth': 7, 'learning_rate': 0.07404641851370607, 'n_estimators': 994, 'subsample': 0.9077617573357728, 'colsample_bytree': 0.6284052556414349, 'min_child_weight': 8, 'gamma': 2.989794647381848, 'reg_alpha': 1.180308946322751e-06, 'reg_lambda': 0.0046132480129009255, 'max_delta_step': 2}. Best is trial 24 with value: 0.6026898395721926.

Best trial: 24. Best value: 0.60269:  14%|█▎        | 27/200 [00:43<02:41,  1.07it/s]

[I 2025-11-10 17:37:55,961] Trial 28 pruned.

Best trial: 24. Best value: 0.60269:  14%|█▍        | 28/200 [00:44<02:44,  1.04it/s]

[I 2025-11-10 17:37:56,988] Trial 29 pruned.

Best trial: 24. Best value: 0.60269:  14%|█▍        | 29/200 [00:44<02:37,  1.08it/s]

[I 2025-11-10 17:37:57,816] Trial 30 pruned.

Best trial: 24. Best value: 0.60269:  15%|█▌        | 30/200 [00:45<02:04,  1.37it/s]

[I 2025-11-10 17:37:58,080] Trial 31 pruned.

Best trial: 25. Best value: 0.609416:  16%|█▌        | 31/200 [00:46<02:25,  1.16it/s]

[I 2025-11-10 17:37:59,257] Trial 25 finished with value: 0.6094155844155844 and parameters: {'max_depth': 7, 'learning_rate': 0.06140342113984659, 'n_estimators': 934, 'subsample': 0.9153903520160694, 'colsample_bytree': 0.5640059303085292, 'min_child_weight': 8, 'gamma': 2.5829915173239995, 'reg_alpha': 8.36891635149626e-07, 'reg_lambda': 0.01002256915762233, 'max_delta_step': 2}. Best is trial 25 with value: 0.6094155844155844.

Best trial: 25. Best value: 0.609416:  16%|█▌        | 32/200 [00:46<01:55,  1.45it/s]

[I 2025-11-10 17:37:59,538] Trial 26 finished with value: 0.5904690603514132 and parameters: {'max_depth': 6, 'learning_rate': 0.06165522242525879, 'n_estimators': 966, 'subsample': 0.8776125133362652, 'colsample_bytree': 0.6440996767673723, 'min_child_weight': 8, 'gamma': 3.3599261414813744, 'reg_alpha': 9.705008436576998e-07, 'reg_lambda': 0.02007137158071839, 'max_delta_step': 2}. Best is trial 25 with value: 0.6094155844155844.
[I 2025-11-10 17:37:59,562] Trial 32 pruned.

Best trial: 25. Best value: 0.609416:  17%|█▋        | 34/200 [00:48<01:51,  1.49it/s]

[I 2025-11-10 17:38:00,832] Trial 33 pruned.

Best trial: 25. Best value: 0.609416:  18%|█▊        | 35/200 [00:48<01:40,  1.64it/s]

[I 2025-11-10 17:38:01,263] Trial 35 pruned.

Best trial: 25. Best value: 0.609416:  18%|█▊        | 36/200 [00:51<03:27,  1.26s/it]

[I 2025-11-10 17:38:04,379] Trial 36 finished with value: 0.5974079449961802 and parameters: {'max_depth': 7, 'learning_rate': 0.15915448272257582, 'n_estimators': 579, 'subsample': 0.9368101937594832, 'colsample_bytree': 0.7561451023444412, 'min_child_weight': 7, 'gamma': 1.9944697757037335, 'reg_alpha': 1.6918026892857618e-07, 'reg_lambda': 0.16081092276377804, 'max_delta_step': 3}. Best is trial 25 with value: 0.6094155844155844.

Best trial: 25. Best value: 0.609416:  18%|█▊        | 37/200 [00:52<03:19,  1.23s/it]

[I 2025-11-10 17:38:05,506] Trial 39 pruned.

Best trial: 25. Best value: 0.609416:  19%|█▉        | 38/200 [00:53<03:05,  1.15s/it]

[I 2025-11-10 17:38:06,452] Trial 38 finished with value: 0.5805805958747134 and parameters: {'max_depth': 7, 'learning_rate': 0.03191428468192968, 'n_estimators': 556, 'subsample': 0.9318163933433019, 'colsample_bytree': 0.7027100491646979, 'min_child_weight': 7, 'gamma': 2.0213414115590203, 'reg_alpha': 3.8894531805359116e-08, 'reg_lambda': 0.0009702071028290788, 'max_delta_step': 2}. Best is trial 25 with value: 0.6094155844155844.

Best trial: 25. Best value: 0.609416:  20%|█▉        | 39/200 [00:55<03:44,  1.39s/it]

[I 2025-11-10 17:38:08,460] Trial 41 finished with value: 0.5717119938884644 and parameters: {'max_depth': 7, 'learning_rate': 0.015289603827355152, 'n_estimators': 230, 'subsample': 0.9809243053368222, 'colsample_bytree': 0.5354434466226629, 'min_child_weight': 8, 'gamma': 2.6678565308843103, 'reg_alpha': 1.567844828061295e-07, 'reg_lambda': 0.18721781177156147, 'max_delta_step': 4}. Best is trial 25 with value: 0.6094155844155844.

Best trial: 25. Best value: 0.609416:  20%|██        | 40/200 [00:56<03:02,  1.14s/it]

[I 2025-11-10 17:38:08,972] Trial 34 finished with value: 0.5970129870129871 and parameters: {'max_depth': 8, 'learning_rate': 0.09860793711776901, 'n_estimators': 1425, 'subsample': 0.7234615632647998, 'colsample_bytree': 0.8370280780898876, 'min_child_weight': 7, 'gamma': 2.5418665565763834, 'reg_alpha': 1.8697594294532924e-07, 'reg_lambda': 0.27350812947164416, 'max_delta_step': 0}. Best is trial 25 with value: 0.6094155844155844.

Best trial: 25. Best value: 0.609416:  20%|██        | 41/200 [00:56<02:26,  1.08it/s]

[I 2025-11-10 17:38:09,381] Trial 42 pruned.

Best trial: 25. Best value: 0.609416:  21%|██        | 42/200 [00:57<02:14,  1.17it/s]

[I 2025-11-10 17:38:10,062] Trial 43 pruned.

Best trial: 25. Best value: 0.609416:  22%|██▏       | 43/200 [00:57<02:08,  1.22it/s]

[I 2025-11-10 17:38:10,792] Trial 40 finished with value: 0.5600542398777693 and parameters: {'max_depth': 7, 'learning_rate': 0.029244934133086792, 'n_estimators': 541, 'subsample': 0.9843346399409476, 'colsample_bytree': 0.7717704978255303, 'min_child_weight': 7, 'gamma': 2.040717479046658, 'reg_alpha': 3.59125469496115e-08, 'reg_lambda': 0.18470205550368315, 'max_delta_step': 4}. Best is trial 25 with value: 0.6094155844155844.
[I 2025-11-10 17:38:10,815] Trial 45 pruned.

Best trial: 25. Best value: 0.609416:  22%|██▎       | 45/200 [00:58<01:32,  1.68it/s]

[I 2025-11-10 17:38:11,462] Trial 44 pruned.

Best trial: 25. Best value: 0.609416:  23%|██▎       | 46/200 [00:58<01:18,  1.96it/s]

[I 2025-11-10 17:38:11,706] Trial 37 finished with value: 0.5721130634071809 and parameters: {'max_depth': 7, 'learning_rate': 0.0298337288739503, 'n_estimators': 1211, 'subsample': 0.9524387703624903, 'colsample_bytree': 0.7463726420046468, 'min_child_weight': 7, 'gamma': 2.0721359872078393, 'reg_alpha': 1.2561236230593675e-07, 'reg_lambda': 0.10214980824703798, 'max_delta_step': 2}. Best is trial 25 with value: 0.6094155844155844.

Best trial: 25. Best value: 0.609416:  24%|██▎       | 47/200 [00:59<01:35,  1.60it/s]

[I 2025-11-10 17:38:12,665] Trial 46 pruned.

Best trial: 25. Best value: 0.609416:  24%|██▍       | 48/200 [01:00<01:46,  1.43it/s]

[I 2025-11-10 17:38:13,563] Trial 47 pruned.
[I 2025-11-10 17:38:13,653] Trial 48 pruned.

Best trial: 25. Best value: 0.609416:  25%|██▌       | 50/200 [01:01<01:08,  2.19it/s]

[I 2025-11-10 17:38:13,849] Trial 49 pruned.

Best trial: 25. Best value: 0.609416:  26%|██▌       | 51/200 [01:01<01:16,  1.95it/s]

[I 2025-11-10 17:38:14,547] Trial 53 pruned.

Best trial: 25. Best value: 0.609416:  26%|██▌       | 52/200 [01:02<01:20,  1.84it/s]

[I 2025-11-10 17:38:15,169] Trial 52 pruned.

Best trial: 25. Best value: 0.609416:  26%|██▋       | 53/200 [01:02<01:08,  2.15it/s]

[I 2025-11-10 17:38:15,427] Trial 50 pruned.

Best trial: 25. Best value: 0.609416:  27%|██▋       | 54/200 [01:04<02:03,  1.18it/s]

[I 2025-11-10 17:38:17,284] Trial 56 pruned.

Best trial: 25. Best value: 0.609416:  28%|██▊       | 55/200 [01:09<04:36,  1.91s/it]

[I 2025-11-10 17:38:21,876] Trial 54 finished with value: 0.5972467532467532 and parameters: {'max_depth': 4, 'learning_rate': 0.08543715389204055, 'n_estimators': 886, 'subsample': 0.8336760225182513, 'colsample_bytree': 0.907955692205732, 'min_child_weight': 7, 'gamma': 2.7371178044664126, 'reg_alpha': 4.79073063749882e-06, 'reg_lambda': 0.0008782618953207627, 'max_delta_step': 3}. Best is trial 25 with value: 0.6094155844155844.

Best trial: 25. Best value: 0.609416:  28%|██▊       | 56/200 [01:09<03:48,  1.59s/it]

[I 2025-11-10 17:38:22,678] Trial 55 finished with value: 0.5928464476699771 and parameters: {'max_depth': 5, 'learning_rate': 0.08751395645099072, 'n_estimators': 916, 'subsample': 0.8380471320479927, 'colsample_bytree': 0.9029026035405295, 'min_child_weight': 7, 'gamma': 3.743217766055717, 'reg_alpha': 4.409048720285448e-06, 'reg_lambda': 0.0008206927786162033, 'max_delta_step': 3}. Best is trial 25 with value: 0.6094155844155844.

Best trial: 25. Best value: 0.609416:  28%|██▊       | 57/200 [01:10<02:54,  1.22s/it]

[I 2025-11-10 17:38:23,006] Trial 51 finished with value: 0.57161115355233 and parameters: {'max_depth': 4, 'learning_rate': 0.18774617206451455, 'n_estimators': 1315, 'subsample': 0.7003929186797371, 'colsample_bytree': 0.6770021245206832, 'min_child_weight': 6, 'gamma': 3.9388224939870256, 'reg_alpha': 1.5621472248590894e-06, 'reg_lambda': 0.012324278326044782, 'max_delta_step': 6}. Best is trial 25 with value: 0.6094155844155844.

Best trial: 25. Best value: 0.609416:  29%|██▉       | 58/200 [01:10<02:30,  1.06s/it]

[I 2025-11-10 17:38:23,668] Trial 57 finished with value: 0.5895179526355998 and parameters: {'max_depth': 3, 'learning_rate': 0.08495534022653776, 'n_estimators': 929, 'subsample': 0.7803687193039317, 'colsample_bytree': 0.5804850827864299, 'min_child_weight': 7, 'gamma': 3.620877992905133, 'reg_alpha': 3.200956863448294e-06, 'reg_lambda': 0.004285862486916375, 'max_delta_step': 3}. Best is trial 25 with value: 0.6094155844155844.

Best trial: 25. Best value: 0.609416:  30%|██▉       | 59/200 [01:11<02:30,  1.06s/it]

[I 2025-11-10 17:38:24,750] Trial 59 pruned.

Best trial: 25. Best value: 0.609416:  30%|███       | 60/200 [01:12<02:18,  1.01it/s]

[I 2025-11-10 17:38:25,569] Trial 61 pruned.

Best trial: 25. Best value: 0.609416:  30%|███       | 61/200 [01:14<02:41,  1.16s/it]

[I 2025-11-10 17:38:27,139] Trial 63 pruned.

Best trial: 58. Best value: 0.628451:  31%|███       | 62/200 [01:14<02:18,  1.00s/it]

[I 2025-11-10 17:38:27,758] Trial 58 finished with value: 0.6284514896867839 and parameters: {'max_depth': 3, 'learning_rate': 0.08031126440579035, 'n_estimators': 843, 'subsample': 0.7463172035529626, 'colsample_bytree': 0.5822816847734136, 'min_child_weight': 7, 'gamma': 3.1692127486270976, 'reg_alpha': 3.583010361925493e-06, 'reg_lambda': 0.0005301520290153509, 'max_delta_step': 4}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  32%|███▏      | 63/200 [01:17<03:40,  1.61s/it]

[I 2025-11-10 17:38:30,803] Trial 60 finished with value: 0.5965637891520243 and parameters: {'max_depth': 3, 'learning_rate': 0.07504355150613122, 'n_estimators': 1038, 'subsample': 0.8887996065941713, 'colsample_bytree': 0.5832009536155476, 'min_child_weight': 7, 'gamma': 3.1492572698765144, 'reg_alpha': 3.6748106402613345e-05, 'reg_lambda': 0.00012445992335599485, 'max_delta_step': 3}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  32%|███▏      | 64/200 [01:19<03:46,  1.66s/it]

[I 2025-11-10 17:38:32,592] Trial 66 pruned.

Best trial: 58. Best value: 0.628451:  32%|███▎      | 65/200 [01:20<03:22,  1.50s/it]

[I 2025-11-10 17:38:33,707] Trial 62 finished with value: 0.586109243697479 and parameters: {'max_depth': 3, 'learning_rate': 0.10045517465587456, 'n_estimators': 1040, 'subsample': 0.8886305872871298, 'colsample_bytree': 0.8324745074027541, 'min_child_weight': 7, 'gamma': 2.821061834644876, 'reg_alpha': 0.30477968152710877, 'reg_lambda': 0.0016225346134450497, 'max_delta_step': 2}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  33%|███▎      | 66/200 [01:21<02:56,  1.32s/it]

[I 2025-11-10 17:38:34,595] Trial 68 pruned.

Best trial: 58. Best value: 0.628451:  34%|███▎      | 67/200 [01:22<02:48,  1.27s/it]

[I 2025-11-10 17:38:35,745] Trial 69 pruned.

Best trial: 58. Best value: 0.628451:  34%|███▍      | 68/200 [01:23<02:35,  1.18s/it]

[I 2025-11-10 17:38:36,712] Trial 64 finished with value: 0.5777119938884645 and parameters: {'max_depth': 7, 'learning_rate': 0.0811148116991537, 'n_estimators': 1023, 'subsample': 0.9210851145366561, 'colsample_bytree': 0.9489930886250421, 'min_child_weight': 7, 'gamma': 2.786638671917719, 'reg_alpha': 6.20261853267814e-07, 'reg_lambda': 0.0019119059073707538, 'max_delta_step': 4}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  34%|███▍      | 69/200 [01:24<02:04,  1.06it/s]

[I 2025-11-10 17:38:37,124] Trial 70 pruned.

Best trial: 58. Best value: 0.628451:  35%|███▌      | 70/200 [01:25<02:00,  1.08it/s]

[I 2025-11-10 17:38:38,007] Trial 67 finished with value: 0.5976608097784568 and parameters: {'max_depth': 4, 'learning_rate': 0.06396526025359561, 'n_estimators': 729, 'subsample': 0.8047931427200944, 'colsample_bytree': 0.5588942976018304, 'min_child_weight': 7, 'gamma': 2.8161438428731134, 'reg_alpha': 0.00013989116191120854, 'reg_lambda': 0.00043790621066365514, 'max_delta_step': 4}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  36%|███▌      | 71/200 [01:25<01:41,  1.27it/s]

[I 2025-11-10 17:38:38,462] Trial 72 pruned.

Best trial: 58. Best value: 0.628451:  36%|███▌      | 72/200 [01:26<01:33,  1.37it/s]

[I 2025-11-10 17:38:39,068] Trial 73 pruned.

Best trial: 58. Best value: 0.628451:  36%|███▋      | 73/200 [01:26<01:27,  1.46it/s]

[I 2025-11-10 17:38:39,649] Trial 74 pruned.
[I 2025-11-10 17:38:39,686] Trial 65 finished with value: 0.6086447669977082 and parameters: {'max_depth': 3, 'learning_rate': 0.045508215965888506, 'n_estimators': 1484, 'subsample': 0.7951993155795929, 'colsample_bytree': 0.8358345934310313, 'min_child_weight': 7, 'gamma': 2.848280595412546, 'reg_alpha': 6.128514995515741e-07, 'reg_lambda': 0.0018437465048835424, 'max_delta_step': 4}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  38%|███▊      | 75/200 [01:29<02:03,  1.01it/s]

[I 2025-11-10 17:38:42,337] Trial 71 finished with value: 0.5660870893812071 and parameters: {'max_depth': 4, 'learning_rate': 0.05665873669103448, 'n_estimators': 652, 'subsample': 0.8099033670663237, 'colsample_bytree': 0.5903268680552797, 'min_child_weight': 6, 'gamma': 2.9671962782754404, 'reg_alpha': 0.00010866896438330308, 'reg_lambda': 0.03165988933065603, 'max_delta_step': 5}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  38%|███▊      | 76/200 [01:31<02:33,  1.24s/it]

[I 2025-11-10 17:38:44,334] Trial 75 finished with value: 0.5896493506493506 and parameters: {'max_depth': 4, 'learning_rate': 0.09021902540117877, 'n_estimators': 761, 'subsample': 0.812322064212444, 'colsample_bytree': 0.5555268123864398, 'min_child_weight': 8, 'gamma': 2.5330930089638626, 'reg_alpha': 0.00934819452697305, 'reg_lambda': 0.00040159789845402413, 'max_delta_step': 4}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  38%|███▊      | 77/200 [01:32<02:21,  1.15s/it]

[I 2025-11-10 17:38:45,228] Trial 76 finished with value: 0.6008640183346066 and parameters: {'max_depth': 4, 'learning_rate': 0.09151041662934987, 'n_estimators': 748, 'subsample': 0.7952566622787876, 'colsample_bytree': 0.5661699822184691, 'min_child_weight': 7, 'gamma': 3.226558909041141, 'reg_alpha': 2.3279639048548404e-06, 'reg_lambda': 0.00010642115170471402, 'max_delta_step': 4}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  39%|███▉      | 78/200 [01:33<02:21,  1.16s/it]

[I 2025-11-10 17:38:46,412] Trial 80 pruned.

Best trial: 58. Best value: 0.628451:  40%|███▉      | 79/200 [01:34<02:10,  1.08s/it]

[I 2025-11-10 17:38:47,285] Trial 81 pruned.

Best trial: 58. Best value: 0.628451:  40%|████      | 80/200 [01:34<01:41,  1.18it/s]

[I 2025-11-10 17:38:47,543] Trial 77 finished with value: 0.610435446906035 and parameters: {'max_depth': 4, 'learning_rate': 0.037511985353691914, 'n_estimators': 902, 'subsample': 0.8126695047559146, 'colsample_bytree': 0.723614667750694, 'min_child_weight': 7, 'gamma': 2.514874279226438, 'reg_alpha': 0.0287070569254256, 'reg_lambda': 0.00010057767779463678, 'max_delta_step': 4}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  40%|████      | 81/200 [01:35<01:46,  1.12it/s]

[I 2025-11-10 17:38:48,549] Trial 82 pruned.

Best trial: 58. Best value: 0.628451:  41%|████      | 82/200 [01:39<03:09,  1.61s/it]

[I 2025-11-10 17:38:51,881] Trial 79 finished with value: 0.6053491214667683 and parameters: {'max_depth': 5, 'learning_rate': 0.04582755323982093, 'n_estimators': 896, 'subsample': 0.7852246276544973, 'colsample_bytree': 0.7886595599232744, 'min_child_weight': 7, 'gamma': 3.215545243157284, 'reg_alpha': 2.429371411902418e-06, 'reg_lambda': 8.11869214067501e-05, 'max_delta_step': 4}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  42%|████▏     | 83/200 [01:40<03:00,  1.54s/it]

[I 2025-11-10 17:38:53,277] Trial 85 pruned.

Best trial: 58. Best value: 0.628451:  42%|████▏     | 84/200 [01:42<03:03,  1.58s/it]

[I 2025-11-10 17:38:54,949] Trial 78 finished with value: 0.5971016042780748 and parameters: {'max_depth': 4, 'learning_rate': 0.025183182644718215, 'n_estimators': 1495, 'subsample': 0.779027286244912, 'colsample_bytree': 0.8377462550136585, 'min_child_weight': 7, 'gamma': 2.5455822650322677, 'reg_alpha': 2.4742521533986172e-06, 'reg_lambda': 0.00011013636967439148, 'max_delta_step': 4}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  42%|████▎     | 85/200 [01:43<02:42,  1.41s/it]

[I 2025-11-10 17:38:55,969] Trial 87 pruned.

Best trial: 58. Best value: 0.628451:  44%|████▎     | 87/200 [01:43<01:28,  1.28it/s]

[I 2025-11-10 17:38:56,203] Trial 84 finished with value: 0.5931680672268907 and parameters: {'max_depth': 4, 'learning_rate': 0.04408624648793224, 'n_estimators': 953, 'subsample': 0.8285214329915536, 'colsample_bytree': 0.7218488814583646, 'min_child_weight': 7, 'gamma': 3.5384939640804323, 'reg_alpha': 0.03661558453723631, 'reg_lambda': 0.000216218828909601, 'max_delta_step': 3}. Best is trial 58 with value: 0.6284514896867839.
[I 2025-11-10 17:38:56,329] Trial 83 finished with value: 0.6261634835752483 and parameters: {'max_depth': 3, 'learning_rate': 0.045444474575010226, 'n_estimators': 1081, 'subsample': 0.9521872805224871, 'colsample_bytree': 0.65728786962305, 'min_child_weight': 8, 'gamma': 1.4870121821083313, 'reg_alpha': 1.5970292136492785, 'reg_lambda': 3.868635211067003e-05, 'max_delta_step': 4}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  44%|████▍     | 89/200 [01:44<01:17,  1.43it/s]

[I 2025-11-10 17:38:57,652] Trial 88 pruned.
[I 2025-11-10 17:38:57,776] Trial 90 pruned.

Best trial: 58. Best value: 0.628451:  45%|████▌     | 90/200 [01:45<01:13,  1.50it/s]

[I 2025-11-10 17:38:58,371] Trial 89 pruned.

Best trial: 58. Best value: 0.628451:  46%|████▌     | 91/200 [01:46<01:15,  1.45it/s]

[I 2025-11-10 17:38:59,116] Trial 91 pruned.
[I 2025-11-10 17:38:59,290] Trial 92 pruned.

Best trial: 58. Best value: 0.628451:  46%|████▋     | 93/200 [01:46<00:51,  2.09it/s]

[I 2025-11-10 17:38:59,634] Trial 93 pruned.

Best trial: 58. Best value: 0.628451:  47%|████▋     | 94/200 [01:47<00:46,  2.27it/s]

[I 2025-11-10 17:38:59,988] Trial 86 finished with value: 0.5829831932773109 and parameters: {'max_depth': 5, 'learning_rate': 0.032653015091698455, 'n_estimators': 677, 'subsample': 0.824243291285247, 'colsample_bytree': 0.7990985192894674, 'min_child_weight': 6, 'gamma': 2.9994387684095867, 'reg_alpha': 0.0009856673875006836, 'reg_lambda': 7.968869603964264e-05, 'max_delta_step': 4}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  48%|████▊     | 95/200 [01:47<00:56,  1.87it/s]

[I 2025-11-10 17:39:00,742] Trial 95 pruned.
[I 2025-11-10 17:39:00,818] Trial 94 pruned.

Best trial: 58. Best value: 0.628451:  48%|████▊     | 97/200 [01:49<01:00,  1.71it/s]

[I 2025-11-10 17:39:02,020] Trial 98 pruned.

Best trial: 58. Best value: 0.628451:  49%|████▉     | 98/200 [01:50<01:15,  1.35it/s]

[I 2025-11-10 17:39:03,248] Trial 100 pruned.

Best trial: 58. Best value: 0.628451:  50%|████▉     | 99/200 [01:52<01:55,  1.14s/it]

[I 2025-11-10 17:39:05,519] Trial 96 finished with value: 0.6133300229182582 and parameters: {'max_depth': 7, 'learning_rate': 0.04147278579483979, 'n_estimators': 616, 'subsample': 0.983135665652766, 'colsample_bytree': 0.7868874738670809, 'min_child_weight': 8, 'gamma': 1.8610731824910807, 'reg_alpha': 0.05198179514599167, 'reg_lambda': 1.4834526572796889e-05, 'max_delta_step': 4}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  50%|█████     | 100/200 [01:54<02:01,  1.22s/it]

[I 2025-11-10 17:39:06,931] Trial 102 pruned.

Best trial: 58. Best value: 0.628451:  50%|█████     | 101/200 [01:54<01:32,  1.07it/s]

[I 2025-11-10 17:39:07,130] Trial 97 finished with value: 0.6281077158135983 and parameters: {'max_depth': 7, 'learning_rate': 0.04906720790545876, 'n_estimators': 858, 'subsample': 0.9275956167448898, 'colsample_bytree': 0.6129816723261617, 'min_child_weight': 8, 'gamma': 1.8575612482673507, 'reg_alpha': 0.019743829174548748, 'reg_lambda': 1.0104441838852413e-05, 'max_delta_step': 4}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  51%|█████     | 102/200 [01:54<01:15,  1.29it/s]

[I 2025-11-10 17:39:07,514] Trial 99 finished with value: 0.6031550802139037 and parameters: {'max_depth': 4, 'learning_rate': 0.04899965768548049, 'n_estimators': 858, 'subsample': 0.7573876840562725, 'colsample_bytree': 0.6131203895093437, 'min_child_weight': 7, 'gamma': 2.40486197822867, 'reg_alpha': 0.10894893472971304, 'reg_lambda': 0.00029488321411703835, 'max_delta_step': 3}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  52%|█████▏    | 103/200 [01:55<01:17,  1.25it/s]

[I 2025-11-10 17:39:08,380] Trial 104 pruned.
[I 2025-11-10 17:39:08,389] Trial 103 pruned.

Best trial: 58. Best value: 0.628451:  52%|█████▎    | 105/200 [01:55<00:50,  1.87it/s]

[I 2025-11-10 17:39:08,807] Trial 105 pruned.

Best trial: 58. Best value: 0.628451:  53%|█████▎    | 106/200 [01:57<01:07,  1.40it/s]

[I 2025-11-10 17:39:10,078] Trial 106 pruned.

Best trial: 58. Best value: 0.628451:  54%|█████▎    | 107/200 [01:57<00:56,  1.63it/s]

[I 2025-11-10 17:39:10,396] Trial 108 pruned.

Best trial: 58. Best value: 0.628451:  54%|█████▍    | 108/200 [01:58<01:01,  1.49it/s]

[I 2025-11-10 17:39:11,226] Trial 101 finished with value: 0.5889625668449198 and parameters: {'max_depth': 4, 'learning_rate': 0.05341159150498766, 'n_estimators': 865, 'subsample': 0.9018685666764776, 'colsample_bytree': 0.6276505730872809, 'min_child_weight': 7, 'gamma': 2.1629255005100227, 'reg_alpha': 0.8472886458569885, 'reg_lambda': 0.0006397101336346462, 'max_delta_step': 3}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  55%|█████▍    | 109/200 [02:04<03:07,  2.06s/it]

[I 2025-11-10 17:39:16,893] Trial 107 finished with value: 0.6254644766997709 and parameters: {'max_depth': 7, 'learning_rate': 0.04218208635446414, 'n_estimators': 1003, 'subsample': 0.8988148296141998, 'colsample_bytree': 0.6500663439929488, 'min_child_weight': 8, 'gamma': 1.6960425124509455, 'reg_alpha': 0.02084166990587463, 'reg_lambda': 6.514463273697927e-06, 'max_delta_step': 3}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  55%|█████▌    | 110/200 [02:05<02:55,  1.95s/it]

[I 2025-11-10 17:39:18,574] Trial 109 finished with value: 0.6243857906799082 and parameters: {'max_depth': 6, 'learning_rate': 0.030157420140771406, 'n_estimators': 925, 'subsample': 0.9435346503688767, 'colsample_bytree': 0.6499714613231861, 'min_child_weight': 8, 'gamma': 1.6051165675768049, 'reg_alpha': 0.2465130677735592, 'reg_lambda': 1.7314890244223883e-05, 'max_delta_step': 2}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 58. Best value: 0.628451:  56%|█████▌    | 111/200 [02:06<02:22,  1.60s/it]

[I 2025-11-10 17:39:19,296] Trial 111 finished with value: 0.6284041252864782 and parameters: {'max_depth': 7, 'learning_rate': 0.07296810448631212, 'n_estimators': 1007, 'subsample': 0.9411545508342992, 'colsample_bytree': 0.6013953114032038, 'min_child_weight': 8, 'gamma': 2.311941074979769, 'reg_alpha': 0.07759839712646845, 'reg_lambda': 0.0012005216189605488, 'max_delta_step': 4}. Best is trial 58 with value: 0.6284514896867839.

Best trial: 110. Best value: 0.644498:  56%|█████▌    | 112/200 [02:06<01:50,  1.26s/it]

[I 2025-11-10 17:39:19,736] Trial 110 finished with value: 0.644498090145149 and parameters: {'max_depth': 3, 'learning_rate': 0.05037301892192511, 'n_estimators': 1001, 'subsample': 0.946488452045993, 'colsample_bytree': 0.851033375985424, 'min_child_weight': 8, 'gamma': 1.4989396527026135, 'reg_alpha': 0.17830626502930197, 'reg_lambda': 0.0011847406577777829, 'max_delta_step': 4}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  56%|█████▋    | 113/200 [02:12<03:28,  2.39s/it]

[I 2025-11-10 17:39:24,837] Trial 112 finished with value: 0.6263743315508021 and parameters: {'max_depth': 7, 'learning_rate': 0.04989075813214821, 'n_estimators': 1001, 'subsample': 0.874305408531152, 'colsample_bytree': 0.6048141077590418, 'min_child_weight': 8, 'gamma': 1.6226398851727408, 'reg_alpha': 0.21453061749384525, 'reg_lambda': 1.0908307529161317e-07, 'max_delta_step': 2}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  57%|█████▋    | 114/200 [02:14<03:34,  2.50s/it]

[I 2025-11-10 17:39:27,580] Trial 113 finished with value: 0.6361298701298701 and parameters: {'max_depth': 6, 'learning_rate': 0.027679735186390525, 'n_estimators': 1011, 'subsample': 0.9857384469870416, 'colsample_bytree': 0.6521629821807489, 'min_child_weight': 8, 'gamma': 1.457003617179875, 'reg_alpha': 0.20982914068836303, 'reg_lambda': 1.7396465265010405e-05, 'max_delta_step': 2}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  57%|█████▊    | 115/200 [02:15<02:57,  2.09s/it]

[I 2025-11-10 17:39:28,722] Trial 114 finished with value: 0.6318823529411765 and parameters: {'max_depth': 7, 'learning_rate': 0.04576530979583001, 'n_estimators': 1135, 'subsample': 0.9416822424328238, 'colsample_bytree': 0.6523669554088197, 'min_child_weight': 8, 'gamma': 1.5902116392449406, 'reg_alpha': 0.21357665256107117, 'reg_lambda': 1.9435924621582488e-05, 'max_delta_step': 4}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  58%|█████▊    | 116/200 [02:17<02:34,  1.84s/it]

[I 2025-11-10 17:39:29,966] Trial 115 finished with value: 0.6314438502673797 and parameters: {'max_depth': 7, 'learning_rate': 0.04594526049271167, 'n_estimators': 1148, 'subsample': 0.9401342444073716, 'colsample_bytree': 0.8610519241802465, 'min_child_weight': 8, 'gamma': 1.595162295357539, 'reg_alpha': 0.2709791007363062, 'reg_lambda': 1.8340091208126352e-05, 'max_delta_step': 4}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  58%|█████▊    | 117/200 [02:19<02:41,  1.95s/it]

[I 2025-11-10 17:39:32,173] Trial 119 pruned.

Best trial: 110. Best value: 0.644498:  59%|█████▉    | 118/200 [02:21<02:36,  1.91s/it]

[I 2025-11-10 17:39:34,004] Trial 120 pruned.

Best trial: 110. Best value: 0.644498:  60%|█████▉    | 119/200 [02:21<01:56,  1.44s/it]

[I 2025-11-10 17:39:34,323] Trial 116 finished with value: 0.6370939648586706 and parameters: {'max_depth': 7, 'learning_rate': 0.058801561246604205, 'n_estimators': 1131, 'subsample': 0.9428305503887361, 'colsample_bytree': 0.8671202152433021, 'min_child_weight': 8, 'gamma': 1.568201380948548, 'reg_alpha': 0.24375355377620064, 'reg_lambda': 9.216223514063158e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  60%|██████    | 120/200 [02:24<02:33,  1.92s/it]

[I 2025-11-10 17:39:37,377] Trial 117 finished with value: 0.6278640183346065 and parameters: {'max_depth': 7, 'learning_rate': 0.01813436772900978, 'n_estimators': 1140, 'subsample': 0.9879226021114325, 'colsample_bytree': 0.6537024251388737, 'min_child_weight': 8, 'gamma': 1.5870789154156053, 'reg_alpha': 0.26684391647526345, 'reg_lambda': 1.4032879778598264e-07, 'max_delta_step': 2}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  60%|██████    | 121/200 [02:25<02:09,  1.64s/it]

[I 2025-11-10 17:39:38,346] Trial 118 finished with value: 0.6290603514132925 and parameters: {'max_depth': 7, 'learning_rate': 0.01926709684458715, 'n_estimators': 1133, 'subsample': 0.9873428912839438, 'colsample_bytree': 0.6514114723218174, 'min_child_weight': 8, 'gamma': 1.5690384090449219, 'reg_alpha': 0.22574217622724033, 'reg_lambda': 5.8884637502604146e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  61%|██████    | 122/200 [02:26<01:54,  1.47s/it]

[I 2025-11-10 17:39:39,439] Trial 123 pruned.

Best trial: 110. Best value: 0.644498:  62%|██████▏   | 123/200 [02:31<03:15,  2.54s/it]

[I 2025-11-10 17:39:44,466] Trial 121 finished with value: 0.6256065699006875 and parameters: {'max_depth': 6, 'learning_rate': 0.022732042059005024, 'n_estimators': 1200, 'subsample': 0.9876932398842914, 'colsample_bytree': 0.8501286239076845, 'min_child_weight': 8, 'gamma': 1.7476781733943954, 'reg_alpha': 0.07954993864977188, 'reg_lambda': 3.6229934491939017e-07, 'max_delta_step': 5}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  62%|██████▏   | 124/200 [02:32<02:38,  2.09s/it]

[I 2025-11-10 17:39:45,510] Trial 122 finished with value: 0.6337708174178761 and parameters: {'max_depth': 6, 'learning_rate': 0.022588310873454375, 'n_estimators': 1194, 'subsample': 0.9565477391784123, 'colsample_bytree': 0.8938085624723806, 'min_child_weight': 8, 'gamma': 1.3578699328833244, 'reg_alpha': 0.17700354293679793, 'reg_lambda': 1.1192743151393058e-07, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  62%|██████▎   | 125/200 [02:34<02:39,  2.13s/it]

[I 2025-11-10 17:39:47,739] Trial 127 pruned.

Best trial: 110. Best value: 0.644498:  63%|██████▎   | 126/200 [02:36<02:18,  1.87s/it]

[I 2025-11-10 17:39:48,995] Trial 124 finished with value: 0.6306898395721925 and parameters: {'max_depth': 7, 'learning_rate': 0.015368813055230812, 'n_estimators': 1181, 'subsample': 0.9583382016424911, 'colsample_bytree': 0.6392144894128503, 'min_child_weight': 8, 'gamma': 1.3379946656668475, 'reg_alpha': 0.07856430472025806, 'reg_lambda': 7.4433976288143e-08, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  64%|██████▎   | 127/200 [02:36<01:39,  1.37s/it]

[I 2025-11-10 17:39:49,197] Trial 125 finished with value: 0.6245538579067991 and parameters: {'max_depth': 7, 'learning_rate': 0.021629109195768388, 'n_estimators': 1204, 'subsample': 0.9886979570864312, 'colsample_bytree': 0.6376142991469871, 'min_child_weight': 8, 'gamma': 1.7329308462096544, 'reg_alpha': 0.17817983507631693, 'reg_lambda': 1.6033286254822147e-07, 'max_delta_step': 2}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  64%|██████▍   | 128/200 [02:39<02:06,  1.76s/it]

[I 2025-11-10 17:39:51,870] Trial 130 pruned.

Best trial: 110. Best value: 0.644498:  64%|██████▍   | 129/200 [02:41<02:12,  1.87s/it]

[I 2025-11-10 17:39:53,995] Trial 131 pruned.

Best trial: 110. Best value: 0.644498:  65%|██████▌   | 130/200 [02:43<02:30,  2.16s/it]

[I 2025-11-10 17:39:56,816] Trial 126 finished with value: 0.6314048892284185 and parameters: {'max_depth': 6, 'learning_rate': 0.018019614010685057, 'n_estimators': 1222, 'subsample': 0.9917855786599846, 'colsample_bytree': 0.8956923385459394, 'min_child_weight': 8, 'gamma': 1.1687132772245827, 'reg_alpha': 0.08236427336726615, 'reg_lambda': 1.9033612585263127e-07, 'max_delta_step': 2}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  66%|██████▌   | 131/200 [02:44<02:02,  1.77s/it]

[I 2025-11-10 17:39:57,678] Trial 128 finished with value: 0.6210244461420933 and parameters: {'max_depth': 7, 'learning_rate': 0.01796352245124341, 'n_estimators': 1148, 'subsample': 0.9982031326310935, 'colsample_bytree': 0.6365701023469901, 'min_child_weight': 8, 'gamma': 1.4811686736133478, 'reg_alpha': 0.33805246496023195, 'reg_lambda': 9.926842888005067e-08, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  66%|██████▌   | 132/200 [02:48<02:36,  2.31s/it]

[I 2025-11-10 17:40:01,243] Trial 129 finished with value: 0.6389862490450726 and parameters: {'max_depth': 7, 'learning_rate': 0.01648585240531519, 'n_estimators': 1173, 'subsample': 0.9977378183520702, 'colsample_bytree': 0.876195431991873, 'min_child_weight': 8, 'gamma': 1.0519018378910143, 'reg_alpha': 0.31579584043572806, 'reg_lambda': 1.9262855424162884e-08, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  66%|██████▋   | 133/200 [02:52<03:18,  2.96s/it]

[I 2025-11-10 17:40:05,716] Trial 132 finished with value: 0.6301650114591293 and parameters: {'max_depth': 8, 'learning_rate': 0.019248409163256593, 'n_estimators': 1181, 'subsample': 0.9661296061795425, 'colsample_bytree': 0.895174215697465, 'min_child_weight': 8, 'gamma': 1.2742924281867163, 'reg_alpha': 0.7540366218928308, 'reg_lambda': 1.0022171967240156e-08, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  67%|██████▋   | 134/200 [02:55<03:08,  2.85s/it]

[I 2025-11-10 17:40:08,330] Trial 133 finished with value: 0.6204530175706646 and parameters: {'max_depth': 6, 'learning_rate': 0.019359585348664, 'n_estimators': 1193, 'subsample': 0.9976515352819402, 'colsample_bytree': 0.9193479591589917, 'min_child_weight': 8, 'gamma': 1.2392293180172973, 'reg_alpha': 1.1371365253136656, 'reg_lambda': 5.542638086220761e-07, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  68%|██████▊   | 135/200 [02:56<02:34,  2.37s/it]

[I 2025-11-10 17:40:09,575] Trial 134 finished with value: 0.6339312452253628 and parameters: {'max_depth': 6, 'learning_rate': 0.02016662631526433, 'n_estimators': 1177, 'subsample': 0.9784294856643405, 'colsample_bytree': 0.9191475702026602, 'min_child_weight': 8, 'gamma': 1.2248240754367123, 'reg_alpha': 0.18427570879565125, 'reg_lambda': 4.5055050356983553e-07, 'max_delta_step': 2}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  68%|██████▊   | 136/200 [02:59<02:44,  2.58s/it]

[I 2025-11-10 17:40:12,626] Trial 138 pruned.

Best trial: 110. Best value: 0.644498:  68%|██████▊   | 137/200 [03:01<02:27,  2.35s/it]

[I 2025-11-10 17:40:14,437] Trial 135 finished with value: 0.6330458365164248 and parameters: {'max_depth': 6, 'learning_rate': 0.019962388142870997, 'n_estimators': 1194, 'subsample': 0.9802487221179514, 'colsample_bytree': 0.8955569879269917, 'min_child_weight': 8, 'gamma': 0.9704794709020966, 'reg_alpha': 0.7225711152606454, 'reg_lambda': 4.029336545781471e-07, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  69%|██████▉   | 138/200 [03:08<03:50,  3.72s/it]

[I 2025-11-10 17:40:21,348] Trial 136 finished with value: 0.6315508021390375 and parameters: {'max_depth': 8, 'learning_rate': 0.019437901177020114, 'n_estimators': 1179, 'subsample': 0.9726943324378083, 'colsample_bytree': 0.9187544215435957, 'min_child_weight': 8, 'gamma': 0.9149650487055103, 'reg_alpha': 0.699348101954718, 'reg_lambda': 2.444748083663049e-08, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  70%|██████▉   | 139/200 [03:10<03:10,  3.13s/it]

[I 2025-11-10 17:40:23,100] Trial 137 finished with value: 0.6310588235294118 and parameters: {'max_depth': 8, 'learning_rate': 0.015538031831069318, 'n_estimators': 1174, 'subsample': 0.9766513265421174, 'colsample_bytree': 0.896277828893761, 'min_child_weight': 8, 'gamma': 0.9788532258185055, 'reg_alpha': 0.5621441410945528, 'reg_lambda': 1.1808355757072415e-08, 'max_delta_step': 0}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  70%|███████   | 140/200 [03:15<03:50,  3.84s/it]

[I 2025-11-10 17:40:28,611] Trial 139 finished with value: 0.6318693659281894 and parameters: {'max_depth': 6, 'learning_rate': 0.01634009421784496, 'n_estimators': 1268, 'subsample': 0.9840229712206052, 'colsample_bytree': 0.9283318176210115, 'min_child_weight': 8, 'gamma': 1.0454784655735334, 'reg_alpha': 0.6386514813186923, 'reg_lambda': 1.2095587548971793e-08, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  70%|███████   | 141/200 [03:15<02:42,  2.75s/it]

[I 2025-11-10 17:40:28,819] Trial 140 finished with value: 0.6366249045072573 and parameters: {'max_depth': 6, 'learning_rate': 0.02018862958569555, 'n_estimators': 1180, 'subsample': 0.9764706627544358, 'colsample_bytree': 0.8681513847080053, 'min_child_weight': 8, 'gamma': 1.033307552621329, 'reg_alpha': 0.6891430889661625, 'reg_lambda': 1.1974758193013856e-08, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  72%|███████▏  | 143/200 [03:18<01:45,  1.85s/it]

[I 2025-11-10 17:40:31,049] Trial 143 pruned.
[I 2025-11-10 17:40:31,171] Trial 144 pruned.

Best trial: 110. Best value: 0.644498:  72%|███████▏  | 144/200 [03:21<02:08,  2.30s/it]

[I 2025-11-10 17:40:34,512] Trial 141 finished with value: 0.6312513368983957 and parameters: {'max_depth': 8, 'learning_rate': 0.023257039552974645, 'n_estimators': 1254, 'subsample': 0.9777554822699418, 'colsample_bytree': 0.9222921722241166, 'min_child_weight': 8, 'gamma': 0.9908260801331389, 'reg_alpha': 0.5830917511958841, 'reg_lambda': 1.1594528595925096e-08, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  72%|███████▎  | 145/200 [03:23<01:58,  2.16s/it]

[I 2025-11-10 17:40:36,339] Trial 142 finished with value: 0.6342773109243698 and parameters: {'max_depth': 8, 'learning_rate': 0.016160589301169835, 'n_estimators': 1261, 'subsample': 0.9654717271603832, 'colsample_bytree': 0.9212033243903766, 'min_child_weight': 8, 'gamma': 0.869441225420678, 'reg_alpha': 0.5009516139268971, 'reg_lambda': 1.1726887394227441e-08, 'max_delta_step': 0}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  73%|███████▎  | 146/200 [03:33<03:59,  4.44s/it]

[I 2025-11-10 17:40:46,096] Trial 145 finished with value: 0.631362872421696 and parameters: {'max_depth': 6, 'learning_rate': 0.013256696511239903, 'n_estimators': 1235, 'subsample': 0.9668189697201564, 'colsample_bytree': 0.9143165858902447, 'min_child_weight': 8, 'gamma': 0.998983196328866, 'reg_alpha': 1.3780990003380533, 'reg_lambda': 2.707203747663259e-08, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  74%|███████▎  | 147/200 [03:33<02:50,  3.22s/it]

[I 2025-11-10 17:40:46,461] Trial 146 finished with value: 0.62209243697479 and parameters: {'max_depth': 6, 'learning_rate': 0.01307886674259047, 'n_estimators': 1229, 'subsample': 0.9573211286473552, 'colsample_bytree': 0.8657705677724086, 'min_child_weight': 8, 'gamma': 0.7220361641856041, 'reg_alpha': 2.175747074187314, 'reg_lambda': 1.1090328393096472e-08, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  74%|███████▍  | 148/200 [03:37<03:02,  3.51s/it]

[I 2025-11-10 17:40:50,653] Trial 147 finished with value: 0.6318640183346066 and parameters: {'max_depth': 9, 'learning_rate': 0.021089441326855776, 'n_estimators': 1345, 'subsample': 0.9652833233313427, 'colsample_bytree': 0.9566479836590341, 'min_child_weight': 8, 'gamma': 0.6795681328096921, 'reg_alpha': 1.6581933092473726, 'reg_lambda': 1.1113291391112093e-08, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  74%|███████▍  | 149/200 [03:38<02:15,  2.66s/it]

[I 2025-11-10 17:40:51,328] Trial 148 finished with value: 0.634563025210084 and parameters: {'max_depth': 9, 'learning_rate': 0.021094551275618018, 'n_estimators': 1249, 'subsample': 0.9644384979357061, 'colsample_bytree': 0.8689901862970042, 'min_child_weight': 8, 'gamma': 0.7025894273655608, 'reg_alpha': 1.330323360389717, 'reg_lambda': 2.9716002963010336e-08, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  75%|███████▌  | 150/200 [03:42<02:31,  3.04s/it]

[I 2025-11-10 17:40:55,246] Trial 152 pruned.

Best trial: 110. Best value: 0.644498:  76%|███████▌  | 151/200 [03:44<02:15,  2.77s/it]

[I 2025-11-10 17:40:57,384] Trial 153 pruned.

Best trial: 110. Best value: 0.644498:  76%|███████▌  | 152/200 [03:47<02:21,  2.95s/it]

[I 2025-11-10 17:41:00,777] Trial 154 pruned.

Best trial: 110. Best value: 0.644498:  77%|███████▋  | 154/200 [03:50<01:29,  1.95s/it]

[I 2025-11-10 17:41:02,997] Trial 155 pruned.
[I 2025-11-10 17:41:03,113] Trial 149 finished with value: 0.6231100076394194 and parameters: {'max_depth': 6, 'learning_rate': 0.013480139678418896, 'n_estimators': 1353, 'subsample': 0.9985643238935341, 'colsample_bytree': 0.9638602713403552, 'min_child_weight': 8, 'gamma': 0.6871458450563278, 'reg_alpha': 1.7002869159471852, 'reg_lambda': 3.120797368543714e-08, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  78%|███████▊  | 155/200 [03:50<01:08,  1.51s/it]

[I 2025-11-10 17:41:03,608] Trial 150 finished with value: 0.6306478227654697 and parameters: {'max_depth': 6, 'learning_rate': 0.013488412912305866, 'n_estimators': 1215, 'subsample': 0.9676778761155532, 'colsample_bytree': 0.9594295166425818, 'min_child_weight': 8, 'gamma': 0.7206004872062266, 'reg_alpha': 1.336230399829127, 'reg_lambda': 4.011819176395859e-08, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  78%|███████▊  | 156/200 [03:51<01:02,  1.42s/it]

[I 2025-11-10 17:41:04,796] Trial 151 finished with value: 0.6135485103132161 and parameters: {'max_depth': 9, 'learning_rate': 0.020949619607209622, 'n_estimators': 1375, 'subsample': 0.9963550491881066, 'colsample_bytree': 0.933947087047872, 'min_child_weight': 8, 'gamma': 0.6764123500573413, 'reg_alpha': 1.053535428908061, 'reg_lambda': 2.610200696441676e-07, 'max_delta_step': 0}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  78%|███████▊  | 157/200 [03:53<01:01,  1.43s/it]

[I 2025-11-10 17:41:06,260] Trial 157 pruned.
[I 2025-11-10 17:41:06,269] Trial 158 pruned.

Best trial: 110. Best value: 0.644498:  80%|███████▉  | 159/200 [03:53<00:33,  1.22it/s]

[I 2025-11-10 17:41:06,481] Trial 156 pruned.

Best trial: 110. Best value: 0.644498:  80%|████████  | 160/200 [03:55<00:38,  1.05it/s]

[I 2025-11-10 17:41:07,841] Trial 159 pruned.

Best trial: 110. Best value: 0.644498:  80%|████████  | 161/200 [03:56<00:38,  1.02it/s]

[I 2025-11-10 17:41:08,889] Trial 161 pruned.

Best trial: 110. Best value: 0.644498:  81%|████████  | 162/200 [03:57<00:39,  1.03s/it]

[I 2025-11-10 17:41:10,042] Trial 160 pruned.

Best trial: 110. Best value: 0.644498:  82%|████████▏ | 163/200 [03:58<00:40,  1.09s/it]

[I 2025-11-10 17:41:11,301] Trial 164 pruned.

Best trial: 110. Best value: 0.644498:  82%|████████▏ | 164/200 [04:00<00:44,  1.23s/it]

[I 2025-11-10 17:41:12,892] Trial 165 pruned.

Best trial: 110. Best value: 0.644498:  82%|████████▎ | 165/200 [04:00<00:38,  1.10s/it]

[I 2025-11-10 17:41:13,662] Trial 163 pruned.

Best trial: 110. Best value: 0.644498:  83%|████████▎ | 166/200 [04:04<01:07,  2.00s/it]

[I 2025-11-10 17:41:17,821] Trial 162 finished with value: 0.6364553093964858 and parameters: {'max_depth': 6, 'learning_rate': 0.02705711849686467, 'n_estimators': 1067, 'subsample': 0.9822031817022078, 'colsample_bytree': 0.8517931325536763, 'min_child_weight': 8, 'gamma': 1.150402245792177, 'reg_alpha': 0.16777174474867204, 'reg_lambda': 1.6410998937770237e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  84%|████████▎ | 167/200 [04:07<01:06,  2.00s/it]

[I 2025-11-10 17:41:19,837] Trial 169 pruned.

Best trial: 110. Best value: 0.644498:  84%|████████▍ | 168/200 [04:09<01:06,  2.08s/it]

[I 2025-11-10 17:41:22,092] Trial 170 pruned.

Best trial: 110. Best value: 0.644498:  84%|████████▍ | 169/200 [04:10<01:00,  1.94s/it]

[I 2025-11-10 17:41:23,710] Trial 166 finished with value: 0.6339533995416348 and parameters: {'max_depth': 6, 'learning_rate': 0.024187013794447102, 'n_estimators': 1094, 'subsample': 0.9709512426829419, 'colsample_bytree': 0.9930599224852377, 'min_child_weight': 8, 'gamma': 1.170123352567381, 'reg_alpha': 0.749181484962314, 'reg_lambda': 2.2762202505733075e-08, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  85%|████████▌ | 170/200 [04:12<00:50,  1.70s/it]

[I 2025-11-10 17:41:24,839] Trial 167 finished with value: 0.6170343773873185 and parameters: {'max_depth': 6, 'learning_rate': 0.015087490677247663, 'n_estimators': 1059, 'subsample': 0.9826393940667806, 'colsample_bytree': 0.9165131276089435, 'min_child_weight': 8, 'gamma': 1.342137516989503, 'reg_alpha': 1.5405268631592357, 'reg_lambda': 1.0203318249118135e-07, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  86%|████████▌ | 171/200 [04:12<00:42,  1.46s/it]

[I 2025-11-10 17:41:25,724] Trial 171 pruned.

Best trial: 110. Best value: 0.644498:  86%|████████▌ | 172/200 [04:13<00:37,  1.35s/it]

[I 2025-11-10 17:41:26,817] Trial 168 finished with value: 0.6326508785332314 and parameters: {'max_depth': 6, 'learning_rate': 0.014757999954326051, 'n_estimators': 1065, 'subsample': 0.9747724766286386, 'colsample_bytree': 0.9167070915864176, 'min_child_weight': 8, 'gamma': 1.1679895195226973, 'reg_alpha': 1.0994951521930625, 'reg_lambda': 1.0268632496952819e-07, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  86%|████████▋ | 173/200 [04:15<00:36,  1.34s/it]

[I 2025-11-10 17:41:28,142] Trial 173 pruned.

Best trial: 110. Best value: 0.644498:  87%|████████▋ | 174/200 [04:22<01:18,  3.01s/it]

[I 2025-11-10 17:41:35,067] Trial 172 finished with value: 0.6342818945760123 and parameters: {'max_depth': 6, 'learning_rate': 0.027231641155915136, 'n_estimators': 1060, 'subsample': 0.9205114133374404, 'colsample_bytree': 0.9747697106303701, 'min_child_weight': 8, 'gamma': 1.297805743690384, 'reg_alpha': 0.734391771607028, 'reg_lambda': 2.5278039064030138e-08, 'max_delta_step': 7}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  88%|████████▊ | 175/200 [04:23<01:05,  2.63s/it]

[I 2025-11-10 17:41:36,811] Trial 174 finished with value: 0.6386035141329259 and parameters: {'max_depth': 6, 'learning_rate': 0.027140002739047136, 'n_estimators': 1096, 'subsample': 0.9743992987030236, 'colsample_bytree': 0.8985076158659007, 'min_child_weight': 8, 'gamma': 1.208054281618118, 'reg_alpha': 0.20609795228032388, 'reg_lambda': 2.5249650262591968e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  88%|████████▊ | 176/200 [04:25<00:55,  2.32s/it]

[I 2025-11-10 17:41:38,393] Trial 175 finished with value: 0.6387020626432391 and parameters: {'max_depth': 6, 'learning_rate': 0.028720371205144497, 'n_estimators': 1084, 'subsample': 0.9731672425744765, 'colsample_bytree': 0.9417048919291959, 'min_child_weight': 8, 'gamma': 0.9138046816176909, 'reg_alpha': 1.0704238288449421, 'reg_lambda': 2.5367391011270932e-08, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  88%|████████▊ | 177/200 [04:27<00:51,  2.23s/it]

[I 2025-11-10 17:41:40,405] Trial 179 pruned.

Best trial: 110. Best value: 0.644498:  89%|████████▉ | 178/200 [04:27<00:35,  1.62s/it]

[I 2025-11-10 17:41:40,605] Trial 176 finished with value: 0.6354484339190221 and parameters: {'max_depth': 6, 'learning_rate': 0.016082097815134953, 'n_estimators': 1123, 'subsample': 0.9743781569460089, 'colsample_bytree': 0.9414224241290289, 'min_child_weight': 8, 'gamma': 1.1950474740335106, 'reg_alpha': 0.4595238640883706, 'reg_lambda': 1.0035645201157585e-08, 'max_delta_step': 1}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  90%|████████▉ | 179/200 [04:30<00:40,  1.95s/it]

[I 2025-11-10 17:41:43,317] Trial 180 pruned.

Best trial: 110. Best value: 0.644498:  90%|█████████ | 180/200 [04:32<00:41,  2.08s/it]

[I 2025-11-10 17:41:45,692] Trial 177 finished with value: 0.6315569136745607 and parameters: {'max_depth': 6, 'learning_rate': 0.026941173479095196, 'n_estimators': 1087, 'subsample': 0.9718630015482114, 'colsample_bytree': 0.9793271895922455, 'min_child_weight': 8, 'gamma': 1.2359455813370492, 'reg_alpha': 1.1359572408376426, 'reg_lambda': 1.656258483504408e-08, 'max_delta_step': 7}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  91%|█████████ | 182/200 [04:34<00:25,  1.41s/it]

[I 2025-11-10 17:41:47,369] Trial 178 finished with value: 0.6358059587471352 and parameters: {'max_depth': 6, 'learning_rate': 0.027643697112290908, 'n_estimators': 1088, 'subsample': 0.9752396690501274, 'colsample_bytree': 0.9703759733866589, 'min_child_weight': 8, 'gamma': 1.2139625265821663, 'reg_alpha': 1.0795589071993883, 'reg_lambda': 1.0153306280839168e-08, 'max_delta_step': 7}. Best is trial 110 with value: 0.644498090145149.
[I 2025-11-10 17:41:47,521] Trial 183 pruned.

Best trial: 110. Best value: 0.644498:  92%|█████████▏| 183/200 [04:36<00:28,  1.67s/it]

[I 2025-11-10 17:41:49,782] Trial 185 pruned.

Best trial: 110. Best value: 0.644498:  92%|█████████▏| 184/200 [04:38<00:24,  1.54s/it]

[I 2025-11-10 17:41:51,017] Trial 181 finished with value: 0.6331810542398777 and parameters: {'max_depth': 6, 'learning_rate': 0.02806155991876586, 'n_estimators': 1071, 'subsample': 0.9736732213008814, 'colsample_bytree': 0.9816933812448969, 'min_child_weight': 8, 'gamma': 1.1659413239007725, 'reg_alpha': 1.1118202141635212, 'reg_lambda': 1.7329343874902547e-08, 'max_delta_step': 7}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  92%|█████████▎| 185/200 [04:40<00:25,  1.68s/it]

[I 2025-11-10 17:41:53,029] Trial 187 pruned.

Best trial: 110. Best value: 0.644498:  93%|█████████▎| 186/200 [04:41<00:21,  1.51s/it]

[I 2025-11-10 17:41:54,129] Trial 182 finished with value: 0.6364446142093201 and parameters: {'max_depth': 6, 'learning_rate': 0.027311060997175222, 'n_estimators': 1122, 'subsample': 0.9581682050824185, 'colsample_bytree': 0.9655849520042228, 'min_child_weight': 8, 'gamma': 1.339131485624755, 'reg_alpha': 0.3995480922492857, 'reg_lambda': 9.134715134354211e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  94%|█████████▎| 187/200 [04:44<00:24,  1.88s/it]

[I 2025-11-10 17:41:56,879] Trial 188 pruned.

Best trial: 110. Best value: 0.644498:  94%|█████████▍| 188/200 [04:45<00:20,  1.69s/it]

[I 2025-11-10 17:41:58,144] Trial 184 finished with value: 0.6349809014514897 and parameters: {'max_depth': 6, 'learning_rate': 0.03028378257305239, 'n_estimators': 1097, 'subsample': 0.9584324816328512, 'colsample_bytree': 0.9701779486161071, 'min_child_weight': 8, 'gamma': 1.3394317155961253, 'reg_alpha': 0.43457617345555494, 'reg_lambda': 3.2539495310453014e-08, 'max_delta_step': 8}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  94%|█████████▍| 189/200 [04:47<00:20,  1.85s/it]

[I 2025-11-10 17:42:00,369] Trial 191 pruned.

Best trial: 110. Best value: 0.644498:  95%|█████████▌| 190/200 [04:47<00:13,  1.39s/it]

[I 2025-11-10 17:42:00,665] Trial 186 finished with value: 0.6329404125286479 and parameters: {'max_depth': 5, 'learning_rate': 0.028428834375485487, 'n_estimators': 1083, 'subsample': 0.9736708803344654, 'colsample_bytree': 0.9704494818843504, 'min_child_weight': 8, 'gamma': 1.4928900452963663, 'reg_alpha': 0.2346009470832186, 'reg_lambda': 1.0299447145717575e-08, 'max_delta_step': 7}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  96%|█████████▌| 191/200 [04:49<00:12,  1.36s/it]

[I 2025-11-10 17:42:01,957] Trial 192 pruned.

Best trial: 110. Best value: 0.644498:  96%|█████████▌| 192/200 [04:49<00:09,  1.15s/it]

[I 2025-11-10 17:42:02,632] Trial 193 pruned.

Best trial: 110. Best value: 0.644498:  96%|█████████▋| 193/200 [04:51<00:09,  1.35s/it]

[I 2025-11-10 17:42:04,433] Trial 194 pruned.

Best trial: 110. Best value: 0.644498:  97%|█████████▋| 194/200 [04:52<00:06,  1.17s/it]

[I 2025-11-10 17:42:05,171] Trial 195 pruned.

Best trial: 110. Best value: 0.644498:  98%|█████████▊| 195/200 [04:52<00:04,  1.06it/s]

[I 2025-11-10 17:42:05,592] Trial 189 finished with value: 0.6387020626432391 and parameters: {'max_depth': 6, 'learning_rate': 0.02562448714150872, 'n_estimators': 1087, 'subsample': 0.9606728640112764, 'colsample_bytree': 0.9790471284680936, 'min_child_weight': 8, 'gamma': 1.3213978742565045, 'reg_alpha': 0.2960138467354165, 'reg_lambda': 2.033352355410873e-08, 'max_delta_step': 6}. Best is trial 110 with value: 0.644498090145149.

Best trial: 110. Best value: 0.644498:  98%|█████████▊| 196/200 [04:54<00:04,  1.15s/it]

[I 2025-11-10 17:42:07,225] Trial 196 pruned.

Best trial: 110. Best value: 0.644498:  99%|█████████▉| 198/200 [04:55<00:01,  1.41it/s]

[I 2025-11-10 17:42:07,741] Trial 190 finished with value: 0.6244896867838043 and parameters: {'max_depth': 6, 'learning_rate': 0.027663010184619415, 'n_estimators': 1028, 'subsample': 0.9995282572452309, 'colsample_bytree': 0.9749927784701251, 'min_child_weight': 8, 'gamma': 1.3198520738187947, 'reg_alpha': 0.299526574885808, 'reg_lambda': 1.796937955924473e-08, 'max_delta_step': 8}. Best is trial 110 with value: 0.644498090145149.
[I 2025-11-10 17:42:07,862] Trial 197 pruned.

Best trial: 110. Best value: 0.644498: 100%|█████████▉| 199/200 [04:56<00:00,  1.19it/s]

[I 2025-11-10 17:42:09,024] Trial 199 pruned.

Best trial: 110. Best value: 0.644498: 100%|██████████| 200/200 [05:00<00:00,  1.50s/it]

[I 2025-11-10 17:42:13,273] Trial 198 finished with value: 0.6266485867074103 and parameters: {'max_depth': 6, 'learning_rate': 0.022652384092305668, 'n_estimators': 1046, 'subsample': 0.9997183591022619, 'colsample_bytree': 0.9659189932263506, 'min_child_weight': 8, 'gamma': 1.274173047142714, 'reg_alpha': 0.15076636803460372, 'reg_lambda': 1.4388360718320339e-08, 'max_delta_step': 6}. Best is trial 110 with value: 0.644498090145149.

[I 2025-11-10 17:42:14,680] A new study created in memory with name: 10_1_roc_auc
Best trial: 0. Best value: 0.5:   0%|          | 1/200 [00:02<07:03,  2.13s/it]

[I 2025-11-10 17:42:16,803] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.015639249054973266, 'n_estimators': 498, 'subsample': 0.5011043609117957, 'colsample_bytree': 0.5815740309062639, 'min_child_weight': 5, 'gamma': 1.0833733442128257, 'reg_alpha': 4.661679755174864e-07, 'reg_lambda': 0.06781188791732955, 'max_delta_step': 2}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   1%|          | 2/200 [00:02<03:20,  1.01s/it]

[I 2025-11-10 17:42:17,036] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.014807625482436174, 'n_estimators': 555, 'subsample': 0.5364165567595984, 'colsample_bytree': 0.53290180407769, 'min_child_weight': 9, 'gamma': 3.3906930805008155, 'reg_alpha': 0.6538120633377932, 'reg_lambda': 0.0013782743672057628, 'max_delta_step': 0}. Best is trial 0 with value: 0.5.
[I 2025-11-10 17:42:17,104] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.020698263298872956, 'n_estimators': 529, 'subsample': 0.5180810846638928, 'colsample_bytree': 0.8401407930308735, 'min_child_weight': 5, 'gamma': 2.4677530879635774, 'reg_alpha': 0.5321095662175013, 'reg_lambda': 2.0639071125594213, 'max_delta_step': 1}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   2%|▏         | 4/200 [00:04<03:33,  1.09s/it]

[I 2025-11-10 17:42:19,299] Trial 2 finished with value: 0.46662768031189084 and parameters: {'max_depth': 5, 'learning_rate': 0.10492934569868674, 'n_estimators': 1041, 'subsample': 0.6878011990883837, 'colsample_bytree': 0.7358265146794536, 'min_child_weight': 3, 'gamma': 0.8822710030378972, 'reg_alpha': 2.6498757668639142e-05, 'reg_lambda': 0.010199199380697936, 'max_delta_step': 10}. Best is trial 0 with value: 0.5.

Best trial: 4. Best value: 0.527446:   2%|▎         | 5/200 [00:05<03:37,  1.12s/it]

[I 2025-11-10 17:42:20,485] Trial 4 finished with value: 0.5274463937621832 and parameters: {'max_depth': 8, 'learning_rate': 0.029119937689283264, 'n_estimators': 826, 'subsample': 0.7494977588381062, 'colsample_bytree': 0.6947938528644502, 'min_child_weight': 4, 'gamma': 0.158036415533494, 'reg_alpha': 0.41283362243403526, 'reg_lambda': 5.9386384858324886e-05, 'max_delta_step': 2}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:   3%|▎         | 6/200 [00:06<03:05,  1.04it/s]

[I 2025-11-10 17:42:21,078] Trial 5 finished with value: 0.46565302144249515 and parameters: {'max_depth': 5, 'learning_rate': 0.05085454822265603, 'n_estimators': 558, 'subsample': 0.9619506891020921, 'colsample_bytree': 0.7528783930790894, 'min_child_weight': 1, 'gamma': 1.3093889272617871, 'reg_alpha': 1.6821073748252318e-06, 'reg_lambda': 0.002212133688620616, 'max_delta_step': 0}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:   4%|▎         | 7/200 [00:07<03:27,  1.07s/it]

[I 2025-11-10 17:42:22,423] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.018048412637028548, 'n_estimators': 1460, 'subsample': 0.8800072192198445, 'colsample_bytree': 0.5947542399361374, 'min_child_weight': 6, 'gamma': 4.465212161580884, 'reg_alpha': 0.001831362560653045, 'reg_lambda': 0.0006013473374942601, 'max_delta_step': 0}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:   4%|▍         | 8/200 [00:09<03:55,  1.23s/it]

[I 2025-11-10 17:42:24,000] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.09345376272009728, 'n_estimators': 774, 'subsample': 0.7872401818758106, 'colsample_bytree': 0.5849480142322132, 'min_child_weight': 8, 'gamma': 2.6047359435523694, 'reg_alpha': 2.5721152401163007e-08, 'reg_lambda': 0.0027862720973004258, 'max_delta_step': 10}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:   4%|▍         | 9/200 [00:10<03:28,  1.09s/it]

[I 2025-11-10 17:42:24,781] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.21242904397268136, 'n_estimators': 1339, 'subsample': 0.7638147295975906, 'colsample_bytree': 0.9313903574132459, 'min_child_weight': 5, 'gamma': 1.4913145171054238, 'reg_alpha': 0.08344339456864189, 'reg_lambda': 2.3401437386019768, 'max_delta_step': 7}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:   5%|▌         | 10/200 [00:10<02:36,  1.21it/s]

[I 2025-11-10 17:42:24,983] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.20797816171076475, 'n_estimators': 692, 'subsample': 0.55715402788979, 'colsample_bytree': 0.6234593531476366, 'min_child_weight': 7, 'gamma': 1.0067122521913912, 'reg_alpha': 8.072109982668897e-07, 'reg_lambda': 1.3463261357175341e-08, 'max_delta_step': 8}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:   6%|▌         | 11/200 [00:10<02:10,  1.45it/s]

[I 2025-11-10 17:42:25,361] Trial 8 pruned.
[I 2025-11-10 17:42:25,450] Trial 13 pruned.

Best trial: 4. Best value: 0.527446:   6%|▋         | 13/200 [00:10<01:17,  2.41it/s]

[I 2025-11-10 17:42:25,556] Trial 11 pruned.

Best trial: 4. Best value: 0.527446:   7%|▋         | 14/200 [00:11<01:13,  2.53it/s]

[I 2025-11-10 17:42:25,895] Trial 14 pruned.

Best trial: 4. Best value: 0.527446:   8%|▊         | 15/200 [00:11<01:11,  2.60it/s]

[I 2025-11-10 17:42:26,244] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06987003110984406, 'n_estimators': 313, 'subsample': 0.9191879081305674, 'colsample_bytree': 0.6284411736547033, 'min_child_weight': 8, 'gamma': 4.6712715716206095, 'reg_alpha': 7.830914285301895, 'reg_lambda': 7.720110293839034e-07, 'max_delta_step': 9}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:   8%|▊         | 16/200 [00:11<01:07,  2.71it/s]

[I 2025-11-10 17:42:26,572] Trial 16 pruned.

Best trial: 4. Best value: 0.527446:   8%|▊         | 17/200 [00:12<00:58,  3.13it/s]

[I 2025-11-10 17:42:26,765] Trial 15 finished with value: 0.5042202729044835 and parameters: {'max_depth': 9, 'learning_rate': 0.02907680925986038, 'n_estimators': 250, 'subsample': 0.6325252782307533, 'colsample_bytree': 0.6602568461641944, 'min_child_weight': 4, 'gamma': 0.27209565929359614, 'reg_alpha': 0.015122714467887665, 'reg_lambda': 5.11932114389173e-06, 'max_delta_step': 3}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:   9%|▉         | 18/200 [00:12<01:17,  2.35it/s]

[I 2025-11-10 17:42:27,449] Trial 18 pruned.

Best trial: 4. Best value: 0.527446:  10%|▉         | 19/200 [00:13<01:19,  2.28it/s]

[I 2025-11-10 17:42:27,926] Trial 20 pruned.

Best trial: 4. Best value: 0.527446:  10%|█         | 20/200 [00:15<02:56,  1.02it/s]

[I 2025-11-10 17:42:30,214] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.010056176521157862, 'n_estimators': 905, 'subsample': 0.8375303077040929, 'colsample_bytree': 0.5190781747578436, 'min_child_weight': 6, 'gamma': 1.870969335040008, 'reg_alpha': 4.8028497786781936e-05, 'reg_lambda': 0.17845197958447961, 'max_delta_step': 5}. Best is trial 4 with value: 0.5274463937621832.
[I 2025-11-10 17:42:30,251] Trial 17 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.033092251512436055, 'n_estimators': 1064, 'subsample': 0.6044685185596725, 'colsample_bytree': 0.529468893032384, 'min_child_weight': 4, 'gamma': 1.9107861851254975, 'reg_alpha': 9.615755599822505, 'reg_lambda': 0.11522979913771239, 'max_delta_step': 5}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  11%|█         | 22/200 [00:17<02:41,  1.10it/s]

[I 2025-11-10 17:42:31,851] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.026768939849936238, 'n_estimators': 931, 'subsample': 0.7233666489263728, 'colsample_bytree': 0.8522475455698653, 'min_child_weight': 10, 'gamma': 0.4710615632423341, 'reg_alpha': 6.148414726447568, 'reg_lambda': 1.273911309982418e-07, 'max_delta_step': 5}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  12%|█▏        | 23/200 [00:17<02:13,  1.32it/s]

[I 2025-11-10 17:42:32,149] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.022612759421327174, 'n_estimators': 446, 'subsample': 0.7188780543906306, 'colsample_bytree': 0.6746916644825371, 'min_child_weight': 5, 'gamma': 0.48981227228670604, 'reg_alpha': 0.038988939460822505, 'reg_lambda': 1.1283043271079789e-07, 'max_delta_step': 2}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  12%|█▏        | 24/200 [00:18<02:11,  1.34it/s]

[I 2025-11-10 17:42:32,866] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.05065025787043502, 'n_estimators': 1254, 'subsample': 0.6003353962055543, 'colsample_bytree': 0.7805048028393595, 'min_child_weight': 6, 'gamma': 0.5398934410806502, 'reg_alpha': 0.05687664198971123, 'reg_lambda': 1.5735212931180575e-07, 'max_delta_step': 5}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  12%|█▎        | 25/200 [00:18<01:48,  1.62it/s]

[I 2025-11-10 17:42:33,140] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.014626946848834041, 'n_estimators': 204, 'subsample': 0.5824997384056155, 'colsample_bytree': 0.5802793054154876, 'min_child_weight': 6, 'gamma': 0.5533151479080978, 'reg_alpha': 0.3929127783086142, 'reg_lambda': 0.00011160440357682496, 'max_delta_step': 2}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  14%|█▍        | 28/200 [00:19<01:06,  2.60it/s]

[I 2025-11-10 17:42:33,755] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.023089977898897815, 'n_estimators': 809, 'subsample': 0.7253229867813418, 'colsample_bytree': 0.7922120482762105, 'min_child_weight': 10, 'gamma': 0.5373041870277887, 'reg_alpha': 7.509903205515571, 'reg_lambda': 9.970587741295539e-08, 'max_delta_step': 2}. Best is trial 4 with value: 0.5274463937621832.
[I 2025-11-10 17:42:33,837] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.014634533286134553, 'n_estimators': 437, 'subsample': 0.5923812958875527, 'colsample_bytree': 0.6697980437823167, 'min_child_weight': 5, 'gamma': 0.48245677446441704, 'reg_alpha': 0.02760012859943829, 'reg_lambda': 0.00011770095910438452, 'max_delta_step': 2}. Best is trial 4 with value: 0.5274463937621832.
[I 2025-11-10 17:42:33,937] Trial 27 pruned.

Best trial: 4. Best value: 0.527446:  14%|█▍        | 29/200 [00:19<00:55,  3.10it/s]

[I 2025-11-10 17:42:34,064] Trial 28 pruned.

Best trial: 4. Best value: 0.527446:  15%|█▌        | 30/200 [00:19<01:06,  2.56it/s]

[I 2025-11-10 17:42:34,655] Trial 30 pruned.

Best trial: 4. Best value: 0.527446:  16%|█▌        | 31/200 [00:20<00:57,  2.96it/s]

[I 2025-11-10 17:42:34,849] Trial 29 pruned.

Best trial: 4. Best value: 0.527446:  16%|█▌        | 32/200 [00:22<02:06,  1.33it/s]

[I 2025-11-10 17:42:36,690] Trial 32 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06571365682625849, 'n_estimators': 572, 'subsample': 0.5041304230183251, 'colsample_bytree': 0.7090482531558078, 'min_child_weight': 7, 'gamma': 3.5047430684471625, 'reg_alpha': 0.00552749347409948, 'reg_lambda': 0.013278639412249323, 'max_delta_step': 4}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  16%|█▋        | 33/200 [00:22<01:39,  1.67it/s]

[I 2025-11-10 17:42:36,892] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.0395665665480317, 'n_estimators': 657, 'subsample': 0.5075680663232484, 'colsample_bytree': 0.6289282531330058, 'min_child_weight': 7, 'gamma': 1.471156602141289, 'reg_alpha': 0.0002904394517540402, 'reg_lambda': 0.021111591589475356, 'max_delta_step': 3}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  17%|█▋        | 34/200 [00:22<01:24,  1.97it/s]

[I 2025-11-10 17:42:37,178] Trial 33 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.061619130475165616, 'n_estimators': 555, 'subsample': 0.5376118864271197, 'colsample_bytree': 0.5511551174144498, 'min_child_weight': 7, 'gamma': 3.3576088443460885, 'reg_alpha': 0.007170921362082911, 'reg_lambda': 1.9298301480393537e-05, 'max_delta_step': 4}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  18%|█▊        | 35/200 [00:22<01:12,  2.27it/s]

[I 2025-11-10 17:42:37,458] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.017535530756471424, 'n_estimators': 584, 'subsample': 0.6267676480873766, 'colsample_bytree': 0.5459192962834027, 'min_child_weight': 8, 'gamma': 3.808697528332633, 'reg_alpha': 1.1901075558820928, 'reg_lambda': 0.0007597168163895931, 'max_delta_step': 1}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  18%|█▊        | 36/200 [00:23<01:14,  2.21it/s]

[I 2025-11-10 17:42:37,938] Trial 38 pruned.

Best trial: 4. Best value: 0.527446:  18%|█▊        | 37/200 [00:24<01:41,  1.61it/s]

[I 2025-11-10 17:42:38,966] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.017715194316621743, 'n_estimators': 474, 'subsample': 0.5544771323094828, 'colsample_bytree': 0.5511946840217617, 'min_child_weight': 9, 'gamma': 3.214495594073586, 'reg_alpha': 0.9439561956978905, 'reg_lambda': 0.0007157144685131797, 'max_delta_step': 1}. Best is trial 4 with value: 0.5274463937621832.
[I 2025-11-10 17:42:39,050] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.017578745381624922, 'n_estimators': 531, 'subsample': 0.5550125182370457, 'colsample_bytree': 0.559004154732931, 'min_child_weight': 9, 'gamma': 3.337140930763564, 'reg_alpha': 1.4461593116262612, 'reg_lambda': 0.0005486064832503673, 'max_delta_step': 1}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  20%|██        | 40/200 [00:24<00:56,  2.82it/s]

[I 2025-11-10 17:42:39,367] Trial 37 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.017100640698925678, 'n_estimators': 501, 'subsample': 0.6281298593986905, 'colsample_bytree': 0.5469871502030482, 'min_child_weight': 9, 'gamma': 3.7865735745656237, 'reg_alpha': 1.6754001515831989, 'reg_lambda': 0.0008187627122159091, 'max_delta_step': 0}. Best is trial 4 with value: 0.5274463937621832.
[I 2025-11-10 17:42:39,493] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2954686470899832, 'n_estimators': 342, 'subsample': 0.6918779888493599, 'colsample_bytree': 0.5545290612623033, 'min_child_weight': 9, 'gamma': 4.120836826432107, 'reg_alpha': 2.476576794221592e-06, 'reg_lambda': 0.0005966964192112442, 'max_delta_step': 1}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  20%|██        | 41/200 [00:25<01:24,  1.87it/s]

[I 2025-11-10 17:42:40,535] Trial 40 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.012278806594684156, 'n_estimators': 317, 'subsample': 0.68235622187443, 'colsample_bytree': 0.5999942803312079, 'min_child_weight': 5, 'gamma': 3.9097424621889942, 'reg_alpha': 1.9514601512577583e-06, 'reg_lambda': 0.3519815876632061, 'max_delta_step': 0}. Best is trial 4 with value: 0.5274463937621832.
[I 2025-11-10 17:42:40,626] Trial 41 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.012292109838848556, 'n_estimators': 332, 'subsample': 0.6851700194566508, 'colsample_bytree': 0.6008329839630958, 'min_child_weight': 5, 'gamma': 4.029524506699664, 'reg_alpha': 1.7857110553946338e-06, 'reg_lambda': 0.43784656034662833, 'max_delta_step': 0}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  22%|██▏       | 43/200 [00:26<00:56,  2.79it/s]

[I 2025-11-10 17:42:40,783] Trial 43 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.012200985988592582, 'n_estimators': 265, 'subsample': 0.7585910633682136, 'colsample_bytree': 0.5980591233080523, 'min_child_weight': 5, 'gamma': 0.8287442057674088, 'reg_alpha': 0.16730220535071824, 'reg_lambda': 0.004582341996859065, 'max_delta_step': 1}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  22%|██▏       | 44/200 [00:26<00:50,  3.12it/s]

[I 2025-11-10 17:42:40,980] Trial 42 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.16006186287141602, 'n_estimators': 330, 'subsample': 0.6808346810442549, 'colsample_bytree': 0.6009231317860491, 'min_child_weight': 5, 'gamma': 0.843063147062818, 'reg_alpha': 5.012317391315222e-06, 'reg_lambda': 0.6283154237917802, 'max_delta_step': 0}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  22%|██▎       | 45/200 [00:27<01:30,  1.71it/s]

[I 2025-11-10 17:42:42,360] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.025950450448345087, 'n_estimators': 384, 'subsample': 0.5287625452335117, 'colsample_bytree': 0.8941451768583897, 'min_child_weight': 5, 'gamma': 2.735363595162299, 'reg_alpha': 0.33006978315894836, 'reg_lambda': 0.8527058711476141, 'max_delta_step': 1}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  23%|██▎       | 46/200 [00:29<02:11,  1.17it/s]

[I 2025-11-10 17:42:43,964] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.02263324371288985, 'n_estimators': 764, 'subsample': 0.5269336580964533, 'colsample_bytree': 0.8657329241083561, 'min_child_weight': 4, 'gamma': 2.9753911948554714, 'reg_alpha': 0.19589842819099457, 'reg_lambda': 1.2521363833195671, 'max_delta_step': 1}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  24%|██▎       | 47/200 [00:29<01:45,  1.44it/s]

[I 2025-11-10 17:42:44,228] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.021791904460789494, 'n_estimators': 782, 'subsample': 0.5286673459648484, 'colsample_bytree': 0.910930509696978, 'min_child_weight': 4, 'gamma': 2.9788682118899827, 'reg_alpha': 1.0042228576661206e-08, 'reg_lambda': 1.5603923183035477, 'max_delta_step': 1}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  24%|██▍       | 48/200 [00:30<02:00,  1.26it/s]

[I 2025-11-10 17:42:45,264] Trial 49 pruned.
[I 2025-11-10 17:42:45,278] Trial 50 pruned.

Best trial: 4. Best value: 0.527446:  25%|██▌       | 50/200 [00:31<01:21,  1.85it/s]

[I 2025-11-10 17:42:45,728] Trial 48 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.020518994567417518, 'n_estimators': 761, 'subsample': 0.5296748151163803, 'colsample_bytree': 0.8344765890957807, 'min_child_weight': 3, 'gamma': 3.0158890829447857, 'reg_alpha': 3.9541643416565266e-07, 'reg_lambda': 6.740018374001766, 'max_delta_step': 6}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  26%|██▌       | 51/200 [00:31<01:10,  2.11it/s]

[I 2025-11-10 17:42:45,989] Trial 51 pruned.

Best trial: 4. Best value: 0.527446:  26%|██▌       | 52/200 [00:31<01:05,  2.24it/s]

[I 2025-11-10 17:42:46,357] Trial 52 pruned.

Best trial: 4. Best value: 0.527446:  26%|██▋       | 53/200 [00:32<01:30,  1.63it/s]

[I 2025-11-10 17:42:47,421] Trial 47 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.021727803057313512, 'n_estimators': 1485, 'subsample': 0.530996462459359, 'colsample_bytree': 0.8977760494625332, 'min_child_weight': 4, 'gamma': 2.8074867147547486, 'reg_alpha': 0.16993910055227446, 'reg_lambda': 6.70614817531218, 'max_delta_step': 1}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  28%|██▊       | 55/200 [00:34<01:48,  1.33it/s]

[I 2025-11-10 17:42:49,350] Trial 53 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.07568636346668732, 'n_estimators': 870, 'subsample': 0.991772694499649, 'colsample_bytree': 0.7047899957034373, 'min_child_weight': 6, 'gamma': 4.987111698312571, 'reg_alpha': 3.272767309143492, 'reg_lambda': 3.3877067928912746e-06, 'max_delta_step': 2}. Best is trial 4 with value: 0.5274463937621832.
[I 2025-11-10 17:42:49,529] Trial 54 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03129034059392821, 'n_estimators': 874, 'subsample': 0.9895397633779639, 'colsample_bytree': 0.7104863878922728, 'min_child_weight': 6, 'gamma': 4.60807637411772, 'reg_alpha': 0.000759862180838421, 'reg_lambda': 1.7167383948169665e-05, 'max_delta_step': 0}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  28%|██▊       | 56/200 [00:35<01:31,  1.57it/s]

[I 2025-11-10 17:42:49,886] Trial 55 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03108474918921804, 'n_estimators': 847, 'subsample': 0.9827183906018804, 'colsample_bytree': 0.6578845696482217, 'min_child_weight': 6, 'gamma': 4.35772260751666, 'reg_alpha': 2.6622435982700754, 'reg_lambda': 2.522398131804824e-05, 'max_delta_step': 0}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  28%|██▊       | 57/200 [00:36<01:30,  1.58it/s]

[I 2025-11-10 17:42:50,517] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03148698441208877, 'n_estimators': 260, 'subsample': 0.8708290885193583, 'colsample_bytree': 0.5153219995768216, 'min_child_weight': 6, 'gamma': 4.38413086674754, 'reg_alpha': 0.0008720743665112411, 'reg_lambda': 1.5037983983411536e-05, 'max_delta_step': 0}. Best is trial 4 with value: 0.5274463937621832.
[I 2025-11-10 17:42:50,703] Trial 59 pruned.

Best trial: 4. Best value: 0.527446:  30%|██▉       | 59/200 [00:36<01:02,  2.25it/s]

[I 2025-11-10 17:42:51,008] Trial 56 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.08599385905545175, 'n_estimators': 857, 'subsample': 0.9168696647038336, 'colsample_bytree': 0.6560218210406973, 'min_child_weight': 6, 'gamma': 4.813113763972246, 'reg_alpha': 0.001969578840398219, 'reg_lambda': 9.955642080965338e-06, 'max_delta_step': 0}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  30%|███       | 60/200 [00:36<00:56,  2.47it/s]

[I 2025-11-10 17:42:51,320] Trial 58 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.024511779429200107, 'n_estimators': 406, 'subsample': 0.8898627995423005, 'colsample_bytree': 0.6580707882645277, 'min_child_weight': 6, 'gamma': 4.408939343295895, 'reg_alpha': 0.0018929089358004044, 'reg_lambda': 0.0015235236563664008, 'max_delta_step': 0}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  30%|███       | 61/200 [00:37<01:16,  1.82it/s]

[I 2025-11-10 17:42:52,206] Trial 60 pruned.

Best trial: 4. Best value: 0.527446:  31%|███       | 62/200 [00:38<01:43,  1.33it/s]

[I 2025-11-10 17:42:53,439] Trial 64 pruned.

Best trial: 4. Best value: 0.527446:  32%|███▏      | 63/200 [00:41<02:44,  1.20s/it]

[I 2025-11-10 17:42:55,697] Trial 62 finished with value: 0.5212280701754386 and parameters: {'max_depth': 8, 'learning_rate': 0.03627038688752917, 'n_estimators': 1120, 'subsample': 0.5757555532324675, 'colsample_bytree': 0.6175841733660777, 'min_child_weight': 4, 'gamma': 0.025578786701858203, 'reg_alpha': 0.00011824050441398579, 'reg_lambda': 0.00024293058396746307, 'max_delta_step': 10}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  32%|███▏      | 64/200 [00:41<02:06,  1.07it/s]

[I 2025-11-10 17:42:56,000] Trial 61 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.024466566570480464, 'n_estimators': 1317, 'subsample': 0.6559978251937598, 'colsample_bytree': 0.5010242840717376, 'min_child_weight': 8, 'gamma': 2.131898028407599, 'reg_alpha': 7.002682751173582e-05, 'reg_lambda': 0.0018929873032709748, 'max_delta_step': 9}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  32%|███▎      | 65/200 [00:41<01:50,  1.22it/s]

[I 2025-11-10 17:42:56,546] Trial 63 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.046612158118487325, 'n_estimators': 1307, 'subsample': 0.5717082800642652, 'colsample_bytree': 0.5031960600962154, 'min_child_weight': 8, 'gamma': 1.0507251794116599, 'reg_alpha': 0.0001135413548622385, 'reg_lambda': 0.05883589188914751, 'max_delta_step': 2}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  33%|███▎      | 66/200 [00:42<01:56,  1.15it/s]

[I 2025-11-10 17:42:57,541] Trial 68 pruned.

Best trial: 4. Best value: 0.527446:  34%|███▎      | 67/200 [00:44<02:36,  1.18s/it]

[I 2025-11-10 17:42:59,443] Trial 65 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03695147647342532, 'n_estimators': 1378, 'subsample': 0.7901514181481493, 'colsample_bytree': 0.738937889941008, 'min_child_weight': 5, 'gamma': 1.6418828617249233, 'reg_alpha': 0.00010936056401911814, 'reg_lambda': 0.05515060172330418, 'max_delta_step': 9}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  34%|███▍      | 68/200 [00:45<02:14,  1.02s/it]

[I 2025-11-10 17:43:00,093] Trial 67 finished with value: 0.5212280701754386 and parameters: {'max_depth': 9, 'learning_rate': 0.03632956533986739, 'n_estimators': 979, 'subsample': 0.5773130645989377, 'colsample_bytree': 0.6148029435521813, 'min_child_weight': 4, 'gamma': 0.3579346913360794, 'reg_alpha': 0.6055028241428108, 'reg_lambda': 0.044399176784015004, 'max_delta_step': 10}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  34%|███▍      | 69/200 [00:45<01:51,  1.17it/s]

[I 2025-11-10 17:43:00,548] Trial 70 pruned.

Best trial: 4. Best value: 0.527446:  35%|███▌      | 70/200 [00:46<01:42,  1.27it/s]

[I 2025-11-10 17:43:01,182] Trial 66 finished with value: 0.5264912280701755 and parameters: {'max_depth': 9, 'learning_rate': 0.04199851130326715, 'n_estimators': 1202, 'subsample': 0.7829382329978304, 'colsample_bytree': 0.5003539207098128, 'min_child_weight': 4, 'gamma': 0.30577895319312454, 'reg_alpha': 8.453802517740675e-05, 'reg_lambda': 0.07477604721608397, 'max_delta_step': 8}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 4. Best value: 0.527446:  36%|███▌      | 71/200 [00:47<02:06,  1.02it/s]

[I 2025-11-10 17:43:02,612] Trial 69 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.03472177329169889, 'n_estimators': 1174, 'subsample': 0.58997490977717, 'colsample_bytree': 0.7331168571807205, 'min_child_weight': 5, 'gamma': 0.33204861000241426, 'reg_alpha': 1.343658894981126e-05, 'reg_lambda': 0.00018315899855133667, 'max_delta_step': 8}. Best is trial 4 with value: 0.5274463937621832.

Best trial: 71. Best value: 0.545789:  36%|███▋      | 73/200 [00:50<02:04,  1.02it/s]

[I 2025-11-10 17:43:04,831] Trial 72 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.034963999145581036, 'n_estimators': 1008, 'subsample': 0.5859111320490841, 'colsample_bytree': 0.5761742157467511, 'min_child_weight': 5, 'gamma': 0.3671877036068574, 'reg_alpha': 1.587708600524229e-05, 'reg_lambda': 0.19807339507074298, 'max_delta_step': 9}. Best is trial 4 with value: 0.5274463937621832.
[I 2025-11-10 17:43:04,953] Trial 71 finished with value: 0.5457894736842105 and parameters: {'max_depth': 10, 'learning_rate': 0.043754051866691866, 'n_estimators': 1122, 'subsample': 0.5869598824303929, 'colsample_bytree': 0.6153929644444714, 'min_child_weight': 4, 'gamma': 0.662840632402719, 'reg_alpha': 0.4168596503219593, 'reg_lambda': 0.005252138578954055, 'max_delta_step': 10}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  37%|███▋      | 74/200 [00:51<02:03,  1.02it/s]

[I 2025-11-10 17:43:05,926] Trial 76 pruned.

Best trial: 71. Best value: 0.545789:  38%|███▊      | 75/200 [00:51<01:46,  1.18it/s]

[I 2025-11-10 17:43:06,474] Trial 73 finished with value: 0.5181871345029239 and parameters: {'max_depth': 10, 'learning_rate': 0.05113716259242552, 'n_estimators': 1241, 'subsample': 0.5896386861555521, 'colsample_bytree': 0.5704340539443374, 'min_child_weight': 4, 'gamma': 0.3846971854470256, 'reg_alpha': 2.0928944390267397e-05, 'reg_lambda': 0.1705562180841361, 'max_delta_step': 10}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  38%|███▊      | 76/200 [00:52<01:46,  1.17it/s]

[I 2025-11-10 17:43:07,344] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.04282276485542811, 'n_estimators': 1104, 'subsample': 0.5454594989796997, 'colsample_bytree': 0.5745033342962927, 'min_child_weight': 4, 'gamma': 0.3686069436496478, 'reg_alpha': 2.0433416708765885e-05, 'reg_lambda': 0.2246133204358762, 'max_delta_step': 10}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  38%|███▊      | 77/200 [00:53<01:27,  1.40it/s]

[I 2025-11-10 17:43:07,723] Trial 78 pruned.

Best trial: 71. Best value: 0.545789:  39%|███▉      | 78/200 [00:53<01:31,  1.33it/s]

[I 2025-11-10 17:43:08,572] Trial 79 pruned.

Best trial: 71. Best value: 0.545789:  40%|███▉      | 79/200 [00:54<01:16,  1.58it/s]

[I 2025-11-10 17:43:08,920] Trial 80 pruned.

Best trial: 71. Best value: 0.545789:  40%|████      | 80/200 [00:54<01:18,  1.52it/s]

[I 2025-11-10 17:43:09,632] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05217092000228309, 'n_estimators': 1112, 'subsample': 0.5466638204120849, 'colsample_bytree': 0.6159633050995298, 'min_child_weight': 4, 'gamma': 0.14551344447269415, 'reg_alpha': 0.57633802258625, 'reg_lambda': 0.008962061037956085, 'max_delta_step': 9}. Best is trial 71 with value: 0.5457894736842105.
[I 2025-11-10 17:43:09,648] Trial 81 pruned.

Best trial: 71. Best value: 0.545789:  41%|████      | 82/200 [00:55<00:48,  2.41it/s]

[I 2025-11-10 17:43:09,898] Trial 82 pruned.

Best trial: 71. Best value: 0.545789:  42%|████▏     | 83/200 [00:56<00:59,  1.97it/s]

[I 2025-11-10 17:43:10,687] Trial 83 pruned.

Best trial: 71. Best value: 0.545789:  42%|████▏     | 84/200 [00:56<01:04,  1.80it/s]

[I 2025-11-10 17:43:11,379] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.053415099490430634, 'n_estimators': 1256, 'subsample': 0.5433890199327319, 'colsample_bytree': 0.5674259323668731, 'min_child_weight': 4, 'gamma': 0.6332148525607407, 'reg_alpha': 0.09840235249992411, 'reg_lambda': 0.026808302878493527, 'max_delta_step': 10}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  42%|████▎     | 85/200 [00:58<01:54,  1.00it/s]

[I 2025-11-10 17:43:13,558] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.044319851749970746, 'n_estimators': 954, 'subsample': 0.5646413223689831, 'colsample_bytree': 0.5327989933837743, 'min_child_weight': 4, 'gamma': 0.44935749760507976, 'reg_alpha': 0.28804600910943023, 'reg_lambda': 0.08240714778694912, 'max_delta_step': 8}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  43%|████▎     | 86/200 [01:00<02:04,  1.10s/it]

[I 2025-11-10 17:43:14,909] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06212838027760007, 'n_estimators': 1249, 'subsample': 0.5698199071099243, 'colsample_bytree': 0.5241755875010695, 'min_child_weight': 5, 'gamma': 0.4430194884585712, 'reg_alpha': 0.3438241598026876, 'reg_lambda': 0.07283494785070185, 'max_delta_step': 10}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  44%|████▎     | 87/200 [01:00<01:50,  1.02it/s]

[I 2025-11-10 17:43:15,591] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.06002619672002609, 'n_estimators': 1215, 'subsample': 0.5661518208927018, 'colsample_bytree': 0.5334719934803096, 'min_child_weight': 5, 'gamma': 0.47981168319402856, 'reg_alpha': 0.3345404205159924, 'reg_lambda': 0.0030762474246876417, 'max_delta_step': 10}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  44%|████▍     | 88/200 [01:01<01:44,  1.08it/s]

[I 2025-11-10 17:43:16,405] Trial 87 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05943036914739144, 'n_estimators': 1212, 'subsample': 0.5595050766065145, 'colsample_bytree': 0.5364550648910194, 'min_child_weight': 5, 'gamma': 0.46549390465114804, 'reg_alpha': 0.2637907323841314, 'reg_lambda': 0.0015003900431767073, 'max_delta_step': 8}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  44%|████▍     | 89/200 [01:01<01:21,  1.36it/s]

[I 2025-11-10 17:43:16,675] Trial 90 pruned.

Best trial: 71. Best value: 0.545789:  45%|████▌     | 90/200 [01:02<01:23,  1.31it/s]

[I 2025-11-10 17:43:17,497] Trial 91 pruned.

Best trial: 71. Best value: 0.545789:  46%|████▌     | 91/200 [01:03<01:05,  1.65it/s]

[I 2025-11-10 17:43:17,729] Trial 92 pruned.

Best trial: 71. Best value: 0.545789:  46%|████▌     | 92/200 [01:03<01:00,  1.79it/s]

[I 2025-11-10 17:43:18,178] Trial 89 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.041628275465613554, 'n_estimators': 736, 'subsample': 0.5164816217065137, 'colsample_bytree': 0.5849851447878378, 'min_child_weight': 5, 'gamma': 0.25304555205699103, 'reg_alpha': 2.008742022459405, 'reg_lambda': 7.207844962250176e-05, 'max_delta_step': 6}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  46%|████▋     | 93/200 [01:04<00:59,  1.78it/s]

[I 2025-11-10 17:43:18,742] Trial 88 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.061797778751933354, 'n_estimators': 1207, 'subsample': 0.580018812719689, 'colsample_bytree': 0.5343709373466373, 'min_child_weight': 5, 'gamma': 0.9139057446126232, 'reg_alpha': 2.168348595744537, 'reg_lambda': 0.0012942049323691452, 'max_delta_step': 6}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  47%|████▋     | 94/200 [01:05<01:33,  1.13it/s]

[I 2025-11-10 17:43:20,382] Trial 95 finished with value: 0.5256725146198831 and parameters: {'max_depth': 3, 'learning_rate': 0.013869487355532083, 'n_estimators': 500, 'subsample': 0.5790817404793237, 'colsample_bytree': 0.5134552849828135, 'min_child_weight': 4, 'gamma': 0.9317352860278832, 'reg_alpha': 0.10765207382761471, 'reg_lambda': 4.197389027642653e-07, 'max_delta_step': 3}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  48%|████▊     | 95/200 [01:06<01:16,  1.37it/s]

[I 2025-11-10 17:43:20,763] Trial 93 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.033451549260347796, 'n_estimators': 715, 'subsample': 0.6139188953708523, 'colsample_bytree': 0.6419699007532158, 'min_child_weight': 10, 'gamma': 0.8716436201208478, 'reg_alpha': 1.0705246079852293, 'reg_lambda': 0.015151584419416117, 'max_delta_step': 4}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  49%|████▉     | 98/200 [01:06<00:36,  2.80it/s]

[I 2025-11-10 17:43:21,002] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.013935411646308588, 'n_estimators': 728, 'subsample': 0.582465916547501, 'colsample_bytree': 0.5160183381683489, 'min_child_weight': 5, 'gamma': 0.919579388833833, 'reg_alpha': 1.069959293678135, 'reg_lambda': 0.2960924816866797, 'max_delta_step': 4}. Best is trial 71 with value: 0.5457894736842105.
[I 2025-11-10 17:43:21,012] Trial 97 pruned.
[I 2025-11-10 17:43:21,180] Trial 96 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.012848786275177918, 'n_estimators': 533, 'subsample': 0.5041770763175137, 'colsample_bytree': 0.5148209511342379, 'min_child_weight': 10, 'gamma': 0.8194556708905698, 'reg_alpha': 1.0865004455338567, 'reg_lambda': 0.33520190468446764, 'max_delta_step': 3}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  50%|████▉     | 99/200 [01:06<00:32,  3.08it/s]

[I 2025-11-10 17:43:21,408] Trial 98 pruned.

Best trial: 71. Best value: 0.545789:  50%|█████     | 100/200 [01:08<01:20,  1.24it/s]

[I 2025-11-10 17:43:23,583] Trial 99 finished with value: 0.5240350877192982 and parameters: {'max_depth': 9, 'learning_rate': 0.016581435805553997, 'n_estimators': 585, 'subsample': 0.6012305768766156, 'colsample_bytree': 0.6068553227578694, 'min_child_weight': 4, 'gamma': 0.746402925278737, 'reg_alpha': 0.045294680652421246, 'reg_lambda': 2.296460415343886e-07, 'max_delta_step': 3}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  50%|█████     | 101/200 [01:09<01:11,  1.38it/s]

[I 2025-11-10 17:43:24,083] Trial 103 pruned.

Best trial: 71. Best value: 0.545789:  51%|█████     | 102/200 [01:10<01:12,  1.35it/s]

[I 2025-11-10 17:43:24,863] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.07401456580754395, 'n_estimators': 806, 'subsample': 0.5917629444108552, 'colsample_bytree': 0.6943543252444945, 'min_child_weight': 4, 'gamma': 0.37573414172818037, 'reg_alpha': 4.935136998749754, 'reg_lambda': 2.2451220958773367e-07, 'max_delta_step': 9}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  52%|█████▏    | 104/200 [01:11<01:00,  1.60it/s]

[I 2025-11-10 17:43:25,877] Trial 100 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.03886541700303194, 'n_estimators': 1143, 'subsample': 0.538779961910419, 'colsample_bytree': 0.6054377039499668, 'min_child_weight': 4, 'gamma': 0.7842859225152636, 'reg_alpha': 0.10983502607258823, 'reg_lambda': 3.701683611336841e-07, 'max_delta_step': 3}. Best is trial 71 with value: 0.5457894736842105.
[I 2025-11-10 17:43:26,032] Trial 101 finished with value: 0.4496491228070175 and parameters: {'max_depth': 8, 'learning_rate': 0.011100985809484194, 'n_estimators': 1139, 'subsample': 0.5966883633662006, 'colsample_bytree': 0.6063835394310624, 'min_child_weight': 4, 'gamma': 0.585965968815135, 'reg_alpha': 0.0645482361688196, 'reg_lambda': 2.9268171500964503e-07, 'max_delta_step': 3}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  52%|█████▏    | 104/200 [01:11<01:00,  1.60it/s]

[I 2025-11-10 17:43:26,111] Trial 104 finished with value: 0.4100877192982456 and parameters: {'max_depth': 8, 'learning_rate': 0.01631466688798743, 'n_estimators': 427, 'subsample': 0.6440075124200078, 'colsample_bytree': 0.5478602320444068, 'min_child_weight': 4, 'gamma': 0.33689607670602406, 'reg_alpha': 0.13928129042110154, 'reg_lambda': 2.938114036641999e-08, 'max_delta_step': 2}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  53%|█████▎    | 106/200 [01:12<00:49,  1.92it/s]

[I 2025-11-10 17:43:26,821] Trial 108 pruned.

Best trial: 71. Best value: 0.545789:  54%|█████▎    | 107/200 [01:12<00:41,  2.23it/s]

[I 2025-11-10 17:43:27,043] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.01643331592685998, 'n_estimators': 452, 'subsample': 0.5385165090395958, 'colsample_bytree': 0.547749709531472, 'min_child_weight': 4, 'gamma': 1.1297373635367958, 'reg_alpha': 0.10846733003577634, 'reg_lambda': 0.00047847335103196894, 'max_delta_step': 2}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  54%|█████▍    | 108/200 [01:13<00:54,  1.69it/s]

[I 2025-11-10 17:43:28,043] Trial 106 finished with value: 0.534561403508772 and parameters: {'max_depth': 9, 'learning_rate': 0.019006630986386237, 'n_estimators': 445, 'subsample': 0.5778926978076395, 'colsample_bytree': 0.5439129002782365, 'min_child_weight': 4, 'gamma': 0.5821897699508958, 'reg_alpha': 0.005141623319398949, 'reg_lambda': 2.773672559087042e-08, 'max_delta_step': 2}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  55%|█████▍    | 109/200 [01:13<00:43,  2.07it/s]

[I 2025-11-10 17:43:28,236] Trial 107 finished with value: 0.5451461988304093 and parameters: {'max_depth': 9, 'learning_rate': 0.016375501176263265, 'n_estimators': 454, 'subsample': 0.6213904454946243, 'colsample_bytree': 0.5643331006551315, 'min_child_weight': 4, 'gamma': 0.06943078861433427, 'reg_alpha': 0.009950466441764227, 'reg_lambda': 5.2580904924526266e-08, 'max_delta_step': 2}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 71. Best value: 0.545789:  55%|█████▌    | 110/200 [01:13<00:37,  2.37it/s]

[I 2025-11-10 17:43:28,497] Trial 111 pruned.

Best trial: 71. Best value: 0.545789:  56%|█████▌    | 111/200 [01:14<00:51,  1.72it/s]

[I 2025-11-10 17:43:29,482] Trial 112 finished with value: 0.5195906432748537 and parameters: {'max_depth': 9, 'learning_rate': 0.018978944386626402, 'n_estimators': 237, 'subsample': 0.6220649187520332, 'colsample_bytree': 0.7215589457693866, 'min_child_weight': 4, 'gamma': 0.07956832546430895, 'reg_alpha': 0.0033275916032646877, 'reg_lambda': 6.915096143610255e-08, 'max_delta_step': 3}. Best is trial 71 with value: 0.5457894736842105.

Best trial: 110. Best value: 0.569591:  56%|█████▌    | 112/200 [01:15<00:41,  2.12it/s]

[I 2025-11-10 17:43:29,685] Trial 110 finished with value: 0.5695906432748539 and parameters: {'max_depth': 9, 'learning_rate': 0.03357386575505361, 'n_estimators': 558, 'subsample': 0.6200485635520706, 'colsample_bytree': 0.6680490785970741, 'min_child_weight': 4, 'gamma': 0.055199498172343986, 'reg_alpha': 0.03240425035570631, 'reg_lambda': 8.422834765579069e-08, 'max_delta_step': 4}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  57%|█████▋    | 114/200 [01:15<00:28,  3.02it/s]

[I 2025-11-10 17:43:29,943] Trial 109 finished with value: 0.551812865497076 and parameters: {'max_depth': 9, 'learning_rate': 0.023712467020242742, 'n_estimators': 628, 'subsample': 0.6207182555689111, 'colsample_bytree': 0.6682794623204271, 'min_child_weight': 4, 'gamma': 1.3392829352793851, 'reg_alpha': 9.667598434896817e-06, 'reg_lambda': 0.5597829133133805, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.
[I 2025-11-10 17:43:30,087] Trial 113 pruned.

Best trial: 110. Best value: 0.569591:  57%|█████▊    | 115/200 [01:15<00:27,  3.05it/s]

[I 2025-11-10 17:43:30,407] Trial 117 pruned.

Best trial: 110. Best value: 0.569591:  58%|█████▊    | 116/200 [01:16<00:25,  3.31it/s]

[I 2025-11-10 17:43:30,648] Trial 116 pruned.
[I 2025-11-10 17:43:30,749] Trial 114 finished with value: 0.5173684210526315 and parameters: {'max_depth': 9, 'learning_rate': 0.018568678421778624, 'n_estimators': 204, 'subsample': 0.6081388151464883, 'colsample_bytree': 0.5790668541821209, 'min_child_weight': 4, 'gamma': 0.06614904348906389, 'reg_alpha': 0.003368380838130643, 'reg_lambda': 7.141388544401921e-08, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  59%|█████▉    | 118/200 [01:16<00:28,  2.88it/s]

[I 2025-11-10 17:43:31,450] Trial 120 pruned.

Best trial: 110. Best value: 0.569591:  60%|█████▉    | 119/200 [01:17<00:31,  2.54it/s]

[I 2025-11-10 17:43:31,987] Trial 121 pruned.

Best trial: 110. Best value: 0.569591:  60%|██████    | 120/200 [01:17<00:36,  2.20it/s]

[I 2025-11-10 17:43:32,615] Trial 115 finished with value: 0.5240350877192982 and parameters: {'max_depth': 9, 'learning_rate': 0.03771830271991661, 'n_estimators': 604, 'subsample': 0.6061716100709816, 'colsample_bytree': 0.7280893476668037, 'min_child_weight': 4, 'gamma': 0.006298149639061057, 'reg_alpha': 0.0056559328550997495, 'reg_lambda': 1.5206907649660124e-08, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  60%|██████    | 121/200 [01:18<00:36,  2.18it/s]

[I 2025-11-10 17:43:33,081] Trial 119 finished with value: 0.5240350877192982 and parameters: {'max_depth': 9, 'learning_rate': 0.02377532332067533, 'n_estimators': 508, 'subsample': 0.6041964392891431, 'colsample_bytree': 0.7623951173073473, 'min_child_weight': 4, 'gamma': 0.09572987083153008, 'reg_alpha': 0.0305614828680478, 'reg_lambda': 8.070467912794504e-08, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  61%|██████    | 122/200 [01:18<00:30,  2.54it/s]

[I 2025-11-10 17:43:33,307] Trial 118 finished with value: 0.500263157894737 and parameters: {'max_depth': 9, 'learning_rate': 0.018090975563726013, 'n_estimators': 605, 'subsample': 0.64822072198585, 'colsample_bytree': 0.6795910880241026, 'min_child_weight': 4, 'gamma': 0.08800279835490106, 'reg_alpha': 0.029366883693454374, 'reg_lambda': 2.7896582457253046e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  62%|██████▏   | 123/200 [01:20<00:56,  1.35it/s]

[I 2025-11-10 17:43:34,910] Trial 122 finished with value: 0.5229239766081871 and parameters: {'max_depth': 8, 'learning_rate': 0.02967478409421346, 'n_estimators': 662, 'subsample': 0.6050793172190757, 'colsample_bytree': 0.6727870064981308, 'min_child_weight': 4, 'gamma': 1.0172077842610778, 'reg_alpha': 0.011730881568834596, 'reg_lambda': 2.0814207303642144e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  62%|██████▏   | 124/200 [01:20<00:46,  1.65it/s]

[I 2025-11-10 17:43:35,190] Trial 123 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.02938891873733987, 'n_estimators': 579, 'subsample': 0.6044033564851365, 'colsample_bytree': 0.6942947338044485, 'min_child_weight': 5, 'gamma': 0.9916821993034055, 'reg_alpha': 0.036047242377290026, 'reg_lambda': 1.0067064480224453e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  63%|██████▎   | 126/200 [01:21<00:35,  2.07it/s]

[I 2025-11-10 17:43:35,847] Trial 125 finished with value: 0.5240350877192982 and parameters: {'max_depth': 9, 'learning_rate': 0.02782578157851727, 'n_estimators': 563, 'subsample': 0.6062322317256023, 'colsample_bytree': 0.7808165928428228, 'min_child_weight': 4, 'gamma': 0.2972559524764648, 'reg_alpha': 0.014361446384534241, 'reg_lambda': 2.6605125672701396e-08, 'max_delta_step': 4}. Best is trial 110 with value: 0.5695906432748539.
[I 2025-11-10 17:43:35,999] Trial 127 pruned.

Best trial: 110. Best value: 0.569591:  63%|██████▎   | 126/200 [01:21<00:35,  2.07it/s]

[I 2025-11-10 17:43:36,067] Trial 124 finished with value: 0.5451461988304093 and parameters: {'max_depth': 8, 'learning_rate': 0.029807131081298247, 'n_estimators': 657, 'subsample': 0.6026353503247047, 'colsample_bytree': 0.6720521070354617, 'min_child_weight': 4, 'gamma': 0.2609993244438427, 'reg_alpha': 0.03761805026939862, 'reg_lambda': 2.2031303274632448e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  64%|██████▍   | 128/200 [01:21<00:28,  2.56it/s]

[I 2025-11-10 17:43:36,557] Trial 128 pruned.

Best trial: 110. Best value: 0.569591:  64%|██████▍   | 129/200 [01:23<00:44,  1.60it/s]

[I 2025-11-10 17:43:37,896] Trial 126 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.02140518184674356, 'n_estimators': 654, 'subsample': 0.6272995237795294, 'colsample_bytree': 0.7500418660713692, 'min_child_weight': 5, 'gamma': 1.370759406845271, 'reg_alpha': 0.012748786957965141, 'reg_lambda': 2.789040266042475e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  66%|██████▌   | 131/200 [01:23<00:33,  2.07it/s]

[I 2025-11-10 17:43:38,442] Trial 132 pruned.
[I 2025-11-10 17:43:38,607] Trial 129 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.023310492768882092, 'n_estimators': 561, 'subsample': 0.6196625395391016, 'colsample_bytree': 0.7754990435693228, 'min_child_weight': 5, 'gamma': 1.4056828513110515, 'reg_alpha': 0.010014054380533767, 'reg_lambda': 1.9971726756936594e-08, 'max_delta_step': 5}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  66%|██████▌   | 131/200 [01:23<00:33,  2.07it/s]

[I 2025-11-10 17:43:38,663] Trial 130 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.02098591911179974, 'n_estimators': 554, 'subsample': 0.6346938470314332, 'colsample_bytree': 0.7446350883028504, 'min_child_weight': 5, 'gamma': 1.3529556920029648, 'reg_alpha': 0.008380636637255693, 'reg_lambda': 3.289755433409347e-08, 'max_delta_step': 5}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  66%|██████▋   | 133/200 [01:24<00:26,  2.51it/s]

[I 2025-11-10 17:43:39,184] Trial 131 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.02168404337608638, 'n_estimators': 549, 'subsample': 0.6369033268428952, 'colsample_bytree': 0.8027999782979751, 'min_child_weight': 5, 'gamma': 0.5031246513514555, 'reg_alpha': 0.008606397347457268, 'reg_lambda': 6.675652322365479e-07, 'max_delta_step': 4}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  67%|██████▋   | 134/200 [01:25<00:41,  1.60it/s]

[I 2025-11-10 17:43:40,535] Trial 133 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.023565945585102797, 'n_estimators': 423, 'subsample': 0.5551955071063293, 'colsample_bytree': 0.8092225211454478, 'min_child_weight': 4, 'gamma': 0.19442613598995587, 'reg_alpha': 0.07513501738812352, 'reg_lambda': 5.427846176538449e-07, 'max_delta_step': 5}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  68%|██████▊   | 136/200 [01:26<00:35,  1.80it/s]

[I 2025-11-10 17:43:41,519] Trial 135 finished with value: 0.5240350877192982 and parameters: {'max_depth': 8, 'learning_rate': 0.026192974899252163, 'n_estimators': 632, 'subsample': 0.6017580639654619, 'colsample_bytree': 0.6703883088575967, 'min_child_weight': 4, 'gamma': 0.16025456805720611, 'reg_alpha': 0.06562570557629092, 'reg_lambda': 7.780841789096098e-08, 'max_delta_step': 4}. Best is trial 110 with value: 0.5695906432748539.
[I 2025-11-10 17:43:41,632] Trial 134 finished with value: 0.4790058479532163 and parameters: {'max_depth': 8, 'learning_rate': 0.026793520589266994, 'n_estimators': 637, 'subsample': 0.5949330303013043, 'colsample_bytree': 0.7977802893927064, 'min_child_weight': 4, 'gamma': 0.17730617725416298, 'reg_alpha': 0.04141492331268396, 'reg_lambda': 9.344270633623301e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  68%|██████▊   | 137/200 [01:27<00:33,  1.89it/s]

[I 2025-11-10 17:43:42,088] Trial 136 finished with value: 0.5240350877192982 and parameters: {'max_depth': 8, 'learning_rate': 0.030913593391252204, 'n_estimators': 626, 'subsample': 0.605721968661285, 'colsample_bytree': 0.6897648090375994, 'min_child_weight': 4, 'gamma': 0.17930720271551137, 'reg_alpha': 0.04819438649900539, 'reg_lambda': 8.418451720575774e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  69%|██████▉   | 138/200 [01:28<00:46,  1.34it/s]

[I 2025-11-10 17:43:43,379] Trial 137 finished with value: 0.47900584795321643 and parameters: {'max_depth': 8, 'learning_rate': 0.02565638451282626, 'n_estimators': 628, 'subsample': 0.5948787393590235, 'colsample_bytree': 0.7210025347077335, 'min_child_weight': 4, 'gamma': 0.30989630560403053, 'reg_alpha': 0.04823530528918034, 'reg_lambda': 9.053825995221897e-08, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  70%|██████▉   | 139/200 [01:29<00:43,  1.41it/s]

[I 2025-11-10 17:43:43,994] Trial 139 finished with value: 0.5212280701754386 and parameters: {'max_depth': 7, 'learning_rate': 0.025059134271998455, 'n_estimators': 519, 'subsample': 0.5844911931459854, 'colsample_bytree': 0.7230439132313649, 'min_child_weight': 4, 'gamma': 0.29797945757995636, 'reg_alpha': 0.02167674213447525, 'reg_lambda': 1.4038188494504434e-08, 'max_delta_step': 4}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  70%|███████   | 141/200 [01:29<00:28,  2.08it/s]

[I 2025-11-10 17:43:44,394] Trial 140 finished with value: 0.5234502923976609 and parameters: {'max_depth': 7, 'learning_rate': 0.025650008213567305, 'n_estimators': 501, 'subsample': 0.5852633875957561, 'colsample_bytree': 0.7644721747955425, 'min_child_weight': 4, 'gamma': 0.3652399209112135, 'reg_alpha': 0.022912102775602516, 'reg_lambda': 4.6291526259642786e-08, 'max_delta_step': 4}. Best is trial 110 with value: 0.5695906432748539.
[I 2025-11-10 17:43:44,550] Trial 138 finished with value: 0.5212280701754386 and parameters: {'max_depth': 8, 'learning_rate': 0.03279733283360757, 'n_estimators': 622, 'subsample': 0.5898476989107979, 'colsample_bytree': 0.6466630141121612, 'min_child_weight': 4, 'gamma': 0.2803729058368744, 'reg_alpha': 0.05113531553305292, 'reg_lambda': 8.487715209830518e-08, 'max_delta_step': 4}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  71%|███████   | 142/200 [01:30<00:22,  2.60it/s]

[I 2025-11-10 17:43:44,706] Trial 142 pruned.

Best trial: 110. Best value: 0.569591:  72%|███████▏  | 143/200 [01:30<00:20,  2.72it/s]

[I 2025-11-10 17:43:45,030] Trial 143 pruned.

Best trial: 110. Best value: 0.569591:  72%|███████▏  | 144/200 [01:31<00:25,  2.18it/s]

[I 2025-11-10 17:43:45,709] Trial 141 finished with value: 0.5234502923976609 and parameters: {'max_depth': 7, 'learning_rate': 0.014649143436291569, 'n_estimators': 471, 'subsample': 0.5857897185613398, 'colsample_bytree': 0.7652307003375985, 'min_child_weight': 4, 'gamma': 0.3566730580940114, 'reg_alpha': 0.01854208581807808, 'reg_lambda': 4.377188334711032e-08, 'max_delta_step': 4}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  73%|███████▎  | 146/200 [01:33<00:36,  1.47it/s]

[I 2025-11-10 17:43:47,627] Trial 144 finished with value: 0.492046783625731 and parameters: {'max_depth': 9, 'learning_rate': 0.030403205327119116, 'n_estimators': 695, 'subsample': 0.6119956154325126, 'colsample_bytree': 0.6988205120495656, 'min_child_weight': 4, 'gamma': 0.1180025627183261, 'reg_alpha': 0.1648571762091888, 'reg_lambda': 1.6335485184008244e-07, 'max_delta_step': 1}. Best is trial 110 with value: 0.5695906432748539.
[I 2025-11-10 17:43:47,800] Trial 145 finished with value: 0.5142690058479532 and parameters: {'max_depth': 9, 'learning_rate': 0.0147055538043378, 'n_estimators': 693, 'subsample': 0.6027425606336071, 'colsample_bytree': 0.7004113517996862, 'min_child_weight': 4, 'gamma': 0.12473386330264692, 'reg_alpha': 0.16739159333088974, 'reg_lambda': 2.0363000674032596e-07, 'max_delta_step': 1}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  74%|███████▎  | 147/200 [01:33<00:28,  1.83it/s]

[I 2025-11-10 17:43:48,033] Trial 146 finished with value: 0.5142690058479532 and parameters: {'max_depth': 8, 'learning_rate': 0.030423535355229406, 'n_estimators': 684, 'subsample': 0.6030804712132926, 'colsample_bytree': 0.6884770324713212, 'min_child_weight': 4, 'gamma': 0.12573589693353898, 'reg_alpha': 0.0685555595986767, 'reg_lambda': 2.4547472188262597e-07, 'max_delta_step': 1}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  74%|███████▍  | 148/200 [01:34<00:32,  1.60it/s]

[I 2025-11-10 17:43:48,841] Trial 147 finished with value: 0.5142690058479532 and parameters: {'max_depth': 8, 'learning_rate': 0.030253090187134273, 'n_estimators': 695, 'subsample': 0.6026659758241287, 'colsample_bytree': 0.7007159441540747, 'min_child_weight': 4, 'gamma': 0.600362760478254, 'reg_alpha': 0.19116299949993762, 'reg_lambda': 3.015715690553251e-07, 'max_delta_step': 1}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  74%|███████▍  | 149/200 [01:35<00:47,  1.08it/s]

[I 2025-11-10 17:43:50,474] Trial 149 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.017039640465476884, 'n_estimators': 584, 'subsample': 0.5637384352706105, 'colsample_bytree': 0.6671593102162569, 'min_child_weight': 4, 'gamma': 0.5853273428103729, 'reg_alpha': 0.082078081341338, 'reg_lambda': 1.3292411650818635e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  76%|███████▌  | 151/200 [01:36<00:27,  1.81it/s]

[I 2025-11-10 17:43:50,735] Trial 150 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.03804321723867395, 'n_estimators': 594, 'subsample': 0.5730728309727812, 'colsample_bytree': 0.6694404499008184, 'min_child_weight': 4, 'gamma': 0.5630665415562589, 'reg_alpha': 0.035946848785267264, 'reg_lambda': 1.375920574788158e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.
[I 2025-11-10 17:43:50,875] Trial 148 finished with value: 0.5142690058479532 and parameters: {'max_depth': 8, 'learning_rate': 0.03680780635582216, 'n_estimators': 679, 'subsample': 0.6018749438154423, 'colsample_bytree': 0.691422643019401, 'min_child_weight': 4, 'gamma': 0.6236396973577372, 'reg_alpha': 0.06499056265329019, 'reg_lambda': 1.4839014109391103e-08, 'max_delta_step': 1}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  76%|███████▌  | 152/200 [01:36<00:26,  1.78it/s]

[I 2025-11-10 17:43:51,458] Trial 154 pruned.

Best trial: 110. Best value: 0.569591:  76%|███████▋  | 153/200 [01:37<00:21,  2.17it/s]

[I 2025-11-10 17:43:51,685] Trial 151 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.017277720796843084, 'n_estimators': 593, 'subsample': 0.5637728230852469, 'colsample_bytree': 0.6620224206023716, 'min_child_weight': 4, 'gamma': 0.0005320245547069946, 'reg_alpha': 0.03778312022425177, 'reg_lambda': 1.574081093196699e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  77%|███████▋  | 154/200 [01:38<00:31,  1.44it/s]

[I 2025-11-10 17:43:52,923] Trial 153 finished with value: 0.4625438596491228 and parameters: {'max_depth': 9, 'learning_rate': 0.03495838978349605, 'n_estimators': 448, 'subsample': 0.6503669440665056, 'colsample_bytree': 0.5068817320884879, 'min_child_weight': 4, 'gamma': 0.7367533397452686, 'reg_alpha': 0.032567945654915, 'reg_lambda': 0.6994496122102218, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  78%|███████▊  | 155/200 [01:38<00:27,  1.62it/s]

[I 2025-11-10 17:43:53,356] Trial 152 finished with value: 0.5378947368421053 and parameters: {'max_depth': 9, 'learning_rate': 0.03810088859076538, 'n_estimators': 602, 'subsample': 0.5747190170681841, 'colsample_bytree': 0.5050074071388961, 'min_child_weight': 4, 'gamma': 0.7092576107964813, 'reg_alpha': 0.03821463399529854, 'reg_lambda': 6.67052998540407e-08, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  78%|███████▊  | 157/200 [01:39<00:19,  2.18it/s]

[I 2025-11-10 17:43:53,894] Trial 155 finished with value: 0.524561403508772 and parameters: {'max_depth': 6, 'learning_rate': 0.026985186775738197, 'n_estimators': 506, 'subsample': 0.5893164699677959, 'colsample_bytree': 0.7621025597308625, 'min_child_weight': 4, 'gamma': 0.007899429526467439, 'reg_alpha': 0.0011745978234225603, 'reg_lambda': 4.106290705782791e-08, 'max_delta_step': 4}. Best is trial 110 with value: 0.5695906432748539.
[I 2025-11-10 17:43:54,043] Trial 156 finished with value: 0.5234502923976608 and parameters: {'max_depth': 6, 'learning_rate': 0.027738420967361465, 'n_estimators': 491, 'subsample': 0.5778651735439441, 'colsample_bytree': 0.6841710307404927, 'min_child_weight': 4, 'gamma': 0.2192982884985407, 'reg_alpha': 0.10803632738900772, 'reg_lambda': 4.372058183207313e-08, 'max_delta_step': 4}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  79%|███████▉  | 158/200 [01:39<00:20,  2.06it/s]

[I 2025-11-10 17:43:54,588] Trial 159 pruned.
[I 2025-11-10 17:43:54,614] Trial 160 pruned.

Best trial: 110. Best value: 0.569591:  80%|████████  | 160/200 [01:40<00:16,  2.43it/s]

[I 2025-11-10 17:43:55,238] Trial 161 pruned.

Best trial: 110. Best value: 0.569591:  80%|████████  | 161/200 [01:40<00:15,  2.45it/s]

[I 2025-11-10 17:43:55,639] Trial 157 finished with value: 0.5378947368421053 and parameters: {'max_depth': 6, 'learning_rate': 0.027152288306952852, 'n_estimators': 531, 'subsample': 0.5758518692961935, 'colsample_bytree': 0.7822422969779401, 'min_child_weight': 4, 'gamma': 0.24613907530707274, 'reg_alpha': 0.0013415481959934113, 'reg_lambda': 3.925383872820388e-08, 'max_delta_step': 4}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  81%|████████  | 162/200 [01:41<00:18,  2.02it/s]

[I 2025-11-10 17:43:56,378] Trial 158 finished with value: 0.5378947368421053 and parameters: {'max_depth': 9, 'learning_rate': 0.043046589729345754, 'n_estimators': 637, 'subsample': 0.57412028014337, 'colsample_bytree': 0.5386870191424764, 'min_child_weight': 4, 'gamma': 0.21281420785668437, 'reg_alpha': 0.11089996848733602, 'reg_lambda': 6.34326227377218e-08, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  82%|████████▏ | 163/200 [01:42<00:22,  1.62it/s]

[I 2025-11-10 17:43:57,327] Trial 162 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.045394275081975376, 'n_estimators': 565, 'subsample': 0.5920329161406884, 'colsample_bytree': 0.780054426526244, 'min_child_weight': 5, 'gamma': 2.3460096433598068, 'reg_alpha': 0.00040037754619109294, 'reg_lambda': 1.1355196768086926e-06, 'max_delta_step': 4}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  82%|████████▏ | 164/200 [01:43<00:21,  1.64it/s]

[I 2025-11-10 17:43:57,920] Trial 163 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.04545737107651234, 'n_estimators': 571, 'subsample': 0.5924876641585285, 'colsample_bytree': 0.7859191630685267, 'min_child_weight': 5, 'gamma': 0.7286953916429022, 'reg_alpha': 0.2566247891082253, 'reg_lambda': 6.066306268805597e-08, 'max_delta_step': 4}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  82%|████████▎ | 165/200 [01:43<00:18,  1.87it/s]

[I 2025-11-10 17:43:58,262] Trial 164 finished with value: 0.524561403508772 and parameters: {'max_depth': 5, 'learning_rate': 0.04448198057260898, 'n_estimators': 567, 'subsample': 0.5924226214541005, 'colsample_bytree': 0.7817524147189255, 'min_child_weight': 4, 'gamma': 0.276570837059821, 'reg_alpha': 0.0011107215176762771, 'reg_lambda': 2.524085827003925e-08, 'max_delta_step': 4}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  83%|████████▎ | 166/200 [01:44<00:21,  1.61it/s]

[I 2025-11-10 17:43:59,098] Trial 165 finished with value: 0.5278947368421053 and parameters: {'max_depth': 6, 'learning_rate': 0.04676326332640372, 'n_estimators': 572, 'subsample': 0.5898514669954884, 'colsample_bytree': 0.781928766627309, 'min_child_weight': 4, 'gamma': 2.3445569584976385, 'reg_alpha': 0.0010655177317668804, 'reg_lambda': 2.6709987823016312e-08, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  84%|████████▎ | 167/200 [01:44<00:16,  2.01it/s]

[I 2025-11-10 17:43:59,291] Trial 166 finished with value: 0.5256725146198831 and parameters: {'max_depth': 6, 'learning_rate': 0.04735076293604785, 'n_estimators': 406, 'subsample': 0.5794973528286963, 'colsample_bytree': 0.5205130644946216, 'min_child_weight': 4, 'gamma': 0.7025807091172325, 'reg_alpha': 0.006053622877333586, 'reg_lambda': 5.8638374256546056e-08, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  84%|████████▍ | 168/200 [01:45<00:19,  1.68it/s]

[I 2025-11-10 17:44:00,118] Trial 167 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.038705532127538037, 'n_estimators': 473, 'subsample': 0.5501465466837975, 'colsample_bytree': 0.5011403999841652, 'min_child_weight': 4, 'gamma': 0.3279668953679932, 'reg_alpha': 3.342583886746314e-06, 'reg_lambda': 2.4768787200871054e-08, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  84%|████████▍ | 169/200 [01:45<00:16,  1.89it/s]

[I 2025-11-10 17:44:00,498] Trial 168 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04821373347705619, 'n_estimators': 474, 'subsample': 0.5513498264761371, 'colsample_bytree': 0.5233832322851592, 'min_child_weight': 4, 'gamma': 0.8994196508290326, 'reg_alpha': 0.001301728124683729, 'reg_lambda': 1.0393795725590678e-08, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  85%|████████▌ | 170/200 [01:46<00:17,  1.71it/s]

[I 2025-11-10 17:44:01,213] Trial 170 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04902753648786423, 'n_estimators': 402, 'subsample': 0.5675996477662183, 'colsample_bytree': 0.5257037892041877, 'min_child_weight': 4, 'gamma': 0.88794909713913, 'reg_alpha': 0.0012531964316605476, 'reg_lambda': 2.8993469426386682e-08, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  86%|████████▌ | 171/200 [01:47<00:18,  1.59it/s]

[I 2025-11-10 17:44:01,948] Trial 169 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04945195368144944, 'n_estimators': 608, 'subsample': 0.5692015158899659, 'colsample_bytree': 0.5565065538856525, 'min_child_weight': 4, 'gamma': 0.9020836808139604, 'reg_alpha': 0.0011122622001041122, 'reg_lambda': 1.045754724132357e-08, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.
[I 2025-11-10 17:44:02,022] Trial 171 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04835428257823233, 'n_estimators': 384, 'subsample': 0.5691000657866624, 'colsample_bytree': 0.5270002895502663, 'min_child_weight': 4, 'gamma': 0.8377874844117044, 'reg_alpha': 0.0011814833705151091, 'reg_lambda': 6.576071146811967e-08, 'max_delta_step': 7}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  86%|████████▋ | 173/200 [01:47<00:12,  2.15it/s]

[I 2025-11-10 17:44:02,495] Trial 175 pruned.
[I 2025-11-10 17:44:02,507] Trial 172 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04405092644115603, 'n_estimators': 405, 'subsample': 0.5718967016992829, 'colsample_bytree': 0.5175970952222138, 'min_child_weight': 4, 'gamma': 0.5118811440805868, 'reg_alpha': 0.001333197449771717, 'reg_lambda': 5.340776868044921e-06, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  88%|████████▊ | 175/200 [01:48<00:11,  2.11it/s]

[I 2025-11-10 17:44:03,468] Trial 173 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.043473241588446045, 'n_estimators': 420, 'subsample': 0.5780989445492052, 'colsample_bytree': 0.8120886922994541, 'min_child_weight': 4, 'gamma': 1.7733969083833427, 'reg_alpha': 0.002313615661933033, 'reg_lambda': 4.028898859553586, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  88%|████████▊ | 176/200 [01:49<00:12,  1.98it/s]

[I 2025-11-10 17:44:04,090] Trial 174 finished with value: 0.5256725146198831 and parameters: {'max_depth': 6, 'learning_rate': 0.04387693010068401, 'n_estimators': 424, 'subsample': 0.57884533787507, 'colsample_bytree': 0.5131443672023182, 'min_child_weight': 4, 'gamma': 1.8431234865630257, 'reg_alpha': 0.004140699429582131, 'reg_lambda': 1.960996672638503e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  88%|████████▊ | 177/200 [01:50<00:13,  1.67it/s]

[I 2025-11-10 17:44:04,984] Trial 176 finished with value: 0.5256725146198831 and parameters: {'max_depth': 5, 'learning_rate': 0.043697308433350145, 'n_estimators': 527, 'subsample': 0.5800909005623478, 'colsample_bytree': 0.5555049206684277, 'min_child_weight': 4, 'gamma': 1.8570847694260413, 'reg_alpha': 0.0023568178100309366, 'reg_lambda': 2.197638500170925e-08, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  89%|████████▉ | 178/200 [01:50<00:12,  1.75it/s]

[I 2025-11-10 17:44:05,472] Trial 177 finished with value: 0.5256725146198831 and parameters: {'max_depth': 5, 'learning_rate': 0.039872951511988164, 'n_estimators': 595, 'subsample': 0.5839387869101992, 'colsample_bytree': 0.8243694061060169, 'min_child_weight': 4, 'gamma': 0.704693466834865, 'reg_alpha': 0.0025439360595901, 'reg_lambda': 1.8575375521668107e-08, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  90%|████████▉ | 179/200 [01:51<00:11,  1.77it/s]

[I 2025-11-10 17:44:06,020] Trial 181 pruned.

Best trial: 110. Best value: 0.569591:  90%|█████████ | 180/200 [01:51<00:09,  2.12it/s]

[I 2025-11-10 17:44:06,248] Trial 179 finished with value: 0.5256725146198831 and parameters: {'max_depth': 5, 'learning_rate': 0.041145257518673276, 'n_estimators': 446, 'subsample': 0.5809312227713332, 'colsample_bytree': 0.5048027724736905, 'min_child_weight': 4, 'gamma': 0.4216086445018169, 'reg_alpha': 0.0004387614387161128, 'reg_lambda': 1.9680564344490658e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  90%|█████████ | 181/200 [01:51<00:08,  2.35it/s]

[I 2025-11-10 17:44:06,556] Trial 178 finished with value: 0.5201169590643275 and parameters: {'max_depth': 6, 'learning_rate': 0.04150130879771643, 'n_estimators': 662, 'subsample': 0.5853646707740326, 'colsample_bytree': 0.5396613780127494, 'min_child_weight': 4, 'gamma': 0.7693946564286992, 'reg_alpha': 0.0005551163641123346, 'reg_lambda': 1.9098169667422897e-08, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  91%|█████████ | 182/200 [01:52<00:09,  1.96it/s]

[I 2025-11-10 17:44:07,273] Trial 180 finished with value: 0.5378947368421053 and parameters: {'max_depth': 5, 'learning_rate': 0.04044977219412793, 'n_estimators': 451, 'subsample': 0.5807469219552894, 'colsample_bytree': 0.8220666193581565, 'min_child_weight': 4, 'gamma': 2.2279614067764966, 'reg_alpha': 0.0005513610327452821, 'reg_lambda': 4.110128787866154e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  92%|█████████▏| 183/200 [01:53<00:08,  1.92it/s]

[I 2025-11-10 17:44:07,822] Trial 182 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03463876049390529, 'n_estimators': 350, 'subsample': 0.7571960211792551, 'colsample_bytree': 0.8598914855430676, 'min_child_weight': 5, 'gamma': 2.0647759117651314, 'reg_alpha': 0.003279442313912543, 'reg_lambda': 3.662748778692814e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  92%|█████████▏| 184/200 [01:54<00:09,  1.64it/s]

[I 2025-11-10 17:44:08,641] Trial 184 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.034811447239979205, 'n_estimators': 456, 'subsample': 0.5590963761093671, 'colsample_bytree': 0.8706652878874069, 'min_child_weight': 4, 'gamma': 1.9778755710327591, 'reg_alpha': 0.0026419888329598943, 'reg_lambda': 3.870878576979564e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.
[I 2025-11-10 17:44:08,721] Trial 183 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03978005007949754, 'n_estimators': 524, 'subsample': 0.5598069955379922, 'colsample_bytree': 0.8734682790217758, 'min_child_weight': 5, 'gamma': 1.106430977293773, 'reg_alpha': 0.0019975439402439886, 'reg_lambda': 2.211217443670078e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  93%|█████████▎| 186/200 [01:54<00:05,  2.42it/s]

[I 2025-11-10 17:44:09,000] Trial 185 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03938676402047133, 'n_estimators': 341, 'subsample': 0.5601738291563301, 'colsample_bytree': 0.8341910157730464, 'min_child_weight': 4, 'gamma': 2.1512889871641963, 'reg_alpha': 0.00023634785317734974, 'reg_lambda': 3.7952412845222176e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  94%|█████████▎| 187/200 [01:55<00:07,  1.72it/s]

[I 2025-11-10 17:44:10,093] Trial 186 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03887018718178786, 'n_estimators': 467, 'subsample': 0.5542730849105656, 'colsample_bytree': 0.8270345464522704, 'min_child_weight': 4, 'gamma': 2.4040912627590934, 'reg_alpha': 0.0022814469755867823, 'reg_lambda': 2.2685549114349528e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  94%|█████████▍| 188/200 [01:55<00:06,  1.74it/s]

[I 2025-11-10 17:44:10,650] Trial 188 finished with value: 0.5378947368421053 and parameters: {'max_depth': 5, 'learning_rate': 0.04612559674865013, 'n_estimators': 383, 'subsample': 0.5791690259469152, 'colsample_bytree': 0.8260958977962866, 'min_child_weight': 4, 'gamma': 2.300914700787268, 'reg_alpha': 1.1456877080924095e-05, 'reg_lambda': 5.711207987302651e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  94%|█████████▍| 189/200 [01:56<00:05,  1.85it/s]

[I 2025-11-10 17:44:11,100] Trial 191 pruned.

Best trial: 110. Best value: 0.569591:  95%|█████████▌| 190/200 [01:57<00:06,  1.60it/s]

[I 2025-11-10 17:44:11,940] Trial 190 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.046839975613937, 'n_estimators': 397, 'subsample': 0.5688787456470671, 'colsample_bytree': 0.507472132926011, 'min_child_weight': 4, 'gamma': 1.8682118358659294, 'reg_alpha': 0.00037148726736857356, 'reg_lambda': 6.001033977219332e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  96%|█████████▌| 192/200 [01:58<00:03,  2.06it/s]

[I 2025-11-10 17:44:12,612] Trial 187 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.039408208379634414, 'n_estimators': 819, 'subsample': 0.5594223832292889, 'colsample_bytree': 0.8306334252090317, 'min_child_weight': 4, 'gamma': 2.2499080443736563, 'reg_alpha': 1.1029321182666103e-05, 'reg_lambda': 5.8028034105739516e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.
[I 2025-11-10 17:44:12,730] Trial 189 finished with value: 0.5390058479532164 and parameters: {'max_depth': 5, 'learning_rate': 0.045212297541537244, 'n_estimators': 822, 'subsample': 0.5815729893813629, 'colsample_bytree': 0.5046794442969909, 'min_child_weight': 4, 'gamma': 2.2283204722796834, 'reg_alpha': 9.668182729991636e-06, 'reg_lambda': 5.416743542662357e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  96%|█████████▋| 193/200 [01:58<00:03,  1.81it/s]

[I 2025-11-10 17:44:13,438] Trial 192 finished with value: 0.5234502923976608 and parameters: {'max_depth': 4, 'learning_rate': 0.04696247500868615, 'n_estimators': 486, 'subsample': 0.5781581137260902, 'colsample_bytree': 0.5514194756816824, 'min_child_weight': 4, 'gamma': 1.9681877364130829, 'reg_alpha': 0.007491764468573215, 'reg_lambda': 2.998198993334315e-05, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  97%|█████████▋| 194/200 [01:59<00:04,  1.36it/s]

[I 2025-11-10 17:44:14,615] Trial 193 finished with value: 0.4922222222222222 and parameters: {'max_depth': 5, 'learning_rate': 0.053464401001558276, 'n_estimators': 539, 'subsample': 0.5805408901297219, 'colsample_bytree': 0.8201636859376592, 'min_child_weight': 4, 'gamma': 2.641826058318585, 'reg_alpha': 0.43909158573421064, 'reg_lambda': 1.4841981325315206, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.
[I 2025-11-10 17:44:14,619] Trial 194 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.05091363461681937, 'n_estimators': 435, 'subsample': 0.5824358545571902, 'colsample_bytree': 0.5001610588735591, 'min_child_weight': 4, 'gamma': 2.537096961258222, 'reg_alpha': 6.790899502377406e-05, 'reg_lambda': 1.1765814844050215, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  98%|█████████▊| 196/200 [02:01<00:03,  1.27it/s]

[I 2025-11-10 17:44:16,322] Trial 198 finished with value: 0.5323391812865498 and parameters: {'max_depth': 5, 'learning_rate': 0.04275902111272044, 'n_estimators': 374, 'subsample': 0.58957369070947, 'colsample_bytree': 0.5308413569644077, 'min_child_weight': 4, 'gamma': 2.2391167465207453, 'reg_alpha': 3.6808328801385486e-06, 'reg_lambda': 5.964368219330198e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  98%|█████████▊| 197/200 [02:02<00:02,  1.41it/s]

[I 2025-11-10 17:44:16,780] Trial 195 finished with value: 0.5390058479532164 and parameters: {'max_depth': 5, 'learning_rate': 0.05320218482458915, 'n_estimators': 841, 'subsample': 0.5797275657582409, 'colsample_bytree': 0.8213609315587445, 'min_child_weight': 4, 'gamma': 2.3937881173932665, 'reg_alpha': 3.336844141054649e-05, 'reg_lambda': 5.153255706475672e-08, 'max_delta_step': 3}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591:  99%|█████████▉| 198/200 [02:02<00:01,  1.73it/s]

[I 2025-11-10 17:44:16,994] Trial 196 finished with value: 0.5390058479532164 and parameters: {'max_depth': 5, 'learning_rate': 0.04342706891963363, 'n_estimators': 839, 'subsample': 0.5841774957325009, 'colsample_bytree': 0.5300017775046413, 'min_child_weight': 4, 'gamma': 2.6048571462470824, 'reg_alpha': 1.9084007963745486e-05, 'reg_lambda': 5.6782874168331876e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

Best trial: 110. Best value: 0.569591: 100%|██████████| 200/200 [02:02<00:00,  1.63it/s]

[I 2025-11-10 17:44:17,503] Trial 199 finished with value: 0.5201169590643275 and parameters: {'max_depth': 6, 'learning_rate': 0.036521838615651774, 'n_estimators': 365, 'subsample': 0.5932618130030777, 'colsample_bytree': 0.5283026168721363, 'min_child_weight': 4, 'gamma': 1.6122092026740122, 'reg_alpha': 3.1593726142294466e-06, 'reg_lambda': 1.1544965081482905e-07, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.
[I 2025-11-10 17:44:17,643] Trial 197 finished with value: 0.5367836257309941 and parameters: {'max_depth': 5, 'learning_rate': 0.044242068722625275, 'n_estimators': 835, 'subsample': 0.5930414240205288, 'colsample_bytree': 0.5298853197773677, 'min_child_weight': 4, 'gamma': 2.1456375084909545, 'reg_alpha': 4.439750712640093e-06, 'reg_lambda': 5.576583602478646e-08, 'max_delta_step': 2}. Best is trial 110 with value: 0.5695906432748539.

[I 2025-11-10 17:44:18,410] A new study created in memory with name: 15_1_roc_auc
Best trial: 1. Best value: 0.5:   0%|          | 1/200 [00:01<03:46,  1.14s/it]

[I 2025-11-10 17:44:19,543] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2362560445524807, 'n_estimators': 237, 'subsample': 0.5337447302039451, 'colsample_bytree': 0.674245167334932, 'min_child_weight': 5, 'gamma': 0.5185164011158383, 'reg_alpha': 9.576261132635736e-08, 'reg_lambda': 9.874001387051434, 'max_delta_step': 2}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:44:19,616] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.02013723485864951, 'n_estimators': 255, 'subsample': 0.5154347412690277, 'colsample_bytree': 0.6234457822384469, 'min_child_weight': 4, 'gamma': 0.4674678648727104, 'reg_alpha': 0.3135828967975511, 'reg_lambda': 0.2445273306504287, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 2. Best value: 0.505068:   2%|▏         | 3/200 [00:02<02:07,  1.54it/s]

[I 2025-11-10 17:44:20,491] Trial 2 finished with value: 0.5050682261208577 and parameters: {'max_depth': 7, 'learning_rate': 0.022336961644656064, 'n_estimators': 336, 'subsample': 0.7574624232421681, 'colsample_bytree': 0.8666207154645773, 'min_child_weight': 3, 'gamma': 4.6160779310633195, 'reg_alpha': 0.20150753442727165, 'reg_lambda': 0.00030565445372033613, 'max_delta_step': 7}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:   2%|▏         | 4/200 [00:03<02:24,  1.35it/s]

[I 2025-11-10 17:44:21,411] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.14246015667336698, 'n_estimators': 729, 'subsample': 0.7245075889812091, 'colsample_bytree': 0.8612963410881804, 'min_child_weight': 4, 'gamma': 1.651542864247778, 'reg_alpha': 4.998957169379631, 'reg_lambda': 3.8659885420941215e-06, 'max_delta_step': 1}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:   2%|▎         | 5/200 [00:05<03:47,  1.17s/it]

[I 2025-11-10 17:44:23,434] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.06490403634148877, 'n_estimators': 559, 'subsample': 0.6200645505946599, 'colsample_bytree': 0.7218065176621398, 'min_child_weight': 6, 'gamma': 0.29058239953947185, 'reg_alpha': 0.3058647364868952, 'reg_lambda': 0.04375878874508891, 'max_delta_step': 1}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:   3%|▎         | 6/200 [00:06<04:35,  1.42s/it]

[I 2025-11-10 17:44:25,394] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.011387710230066938, 'n_estimators': 572, 'subsample': 0.6606128409705565, 'colsample_bytree': 0.5673335489528546, 'min_child_weight': 7, 'gamma': 4.77054501106631, 'reg_alpha': 0.11920282715084608, 'reg_lambda': 4.173547907501549e-08, 'max_delta_step': 4}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:   4%|▎         | 7/200 [00:07<03:59,  1.24s/it]

[I 2025-11-10 17:44:26,247] Trial 4 finished with value: 0.4133333333333333 and parameters: {'max_depth': 4, 'learning_rate': 0.15348096916350384, 'n_estimators': 1485, 'subsample': 0.7847903947831869, 'colsample_bytree': 0.6036116235715563, 'min_child_weight': 2, 'gamma': 0.6813285992612156, 'reg_alpha': 2.4268123890066217e-08, 'reg_lambda': 3.3403750168071125, 'max_delta_step': 5}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:   4%|▍         | 8/200 [00:08<03:19,  1.04s/it]

[I 2025-11-10 17:44:26,837] Trial 6 finished with value: 0.4894736842105264 and parameters: {'max_depth': 10, 'learning_rate': 0.04420555270917424, 'n_estimators': 999, 'subsample': 0.9777331757029823, 'colsample_bytree': 0.6982267671606257, 'min_child_weight': 1, 'gamma': 3.6120734232462057, 'reg_alpha': 0.00011253186005125176, 'reg_lambda': 0.0032380901775747816, 'max_delta_step': 9}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:   5%|▌         | 10/200 [00:09<02:00,  1.57it/s]

[I 2025-11-10 17:44:27,298] Trial 5 finished with value: 0.44947368421052636 and parameters: {'max_depth': 7, 'learning_rate': 0.023410518078975925, 'n_estimators': 1349, 'subsample': 0.7842156280520246, 'colsample_bytree': 0.5524864920789097, 'min_child_weight': 1, 'gamma': 3.852481593048503, 'reg_alpha': 1.0832743831639844e-05, 'reg_lambda': 0.0005423469527288763, 'max_delta_step': 5}. Best is trial 2 with value: 0.5050682261208577.
[I 2025-11-10 17:44:27,416] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.12487329800126072, 'n_estimators': 251, 'subsample': 0.6866347803508908, 'colsample_bytree': 0.5241058632058013, 'min_child_weight': 8, 'gamma': 3.5797327546228557, 'reg_alpha': 0.029984380051626684, 'reg_lambda': 0.19534360995899264, 'max_delta_step': 4}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:   6%|▌         | 11/200 [00:09<02:09,  1.46it/s]

[I 2025-11-10 17:44:28,215] Trial 12 pruned.

Best trial: 2. Best value: 0.505068:   6%|▌         | 12/200 [00:11<03:03,  1.02it/s]

[I 2025-11-10 17:44:29,870] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.18028200894416463, 'n_estimators': 919, 'subsample': 0.6167687547067116, 'colsample_bytree': 0.5918024433803977, 'min_child_weight': 2, 'gamma': 1.3049302180024984, 'reg_alpha': 9.981685467899966, 'reg_lambda': 2.876324775668716e-05, 'max_delta_step': 5}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:   6%|▋         | 13/200 [00:12<03:01,  1.03it/s]

[I 2025-11-10 17:44:30,811] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09955846605248925, 'n_estimators': 614, 'subsample': 0.8825126627260598, 'colsample_bytree': 0.8812272562685755, 'min_child_weight': 10, 'gamma': 1.8106327099610011, 'reg_alpha': 8.162162159979232, 'reg_lambda': 2.614178988901851e-06, 'max_delta_step': 8}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:   7%|▋         | 14/200 [00:12<02:31,  1.23it/s]

[I 2025-11-10 17:44:31,273] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.19836601747728186, 'n_estimators': 1138, 'subsample': 0.5035894379802104, 'colsample_bytree': 0.6009725990280446, 'min_child_weight': 10, 'gamma': 3.0956430936608497, 'reg_alpha': 0.001094550595469496, 'reg_lambda': 0.04924075467120353, 'max_delta_step': 4}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:   8%|▊         | 15/200 [00:13<02:01,  1.53it/s]

[I 2025-11-10 17:44:31,559] Trial 16 pruned.

Best trial: 2. Best value: 0.505068:   8%|▊         | 17/200 [00:13<01:48,  1.68it/s]

[I 2025-11-10 17:44:32,009] Trial 17 pruned.
[I 2025-11-10 17:44:32,013] Trial 18 pruned.
[I 2025-11-10 17:44:32,025] Trial 13 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.042691671821156275, 'n_estimators': 1040, 'subsample': 0.8984460274145093, 'colsample_bytree': 0.9969788956134827, 'min_child_weight': 10, 'gamma': 4.98148162621356, 'reg_alpha': 0.001969224570905255, 'reg_lambda': 5.112462269883353e-06, 'max_delta_step': 9}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  10%|▉         | 19/200 [00:14<01:18,  2.32it/s]

[I 2025-11-10 17:44:32,923] Trial 15 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09560299939098771, 'n_estimators': 620, 'subsample': 0.8819190211691905, 'colsample_bytree': 0.8756269890447078, 'min_child_weight': 4, 'gamma': 1.8470250293497583, 'reg_alpha': 8.444606690456133, 'reg_lambda': 2.776759101993866e-06, 'max_delta_step': 8}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  10%|█         | 20/200 [00:15<01:35,  1.89it/s]

[I 2025-11-10 17:44:33,812] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.08712730674207703, 'n_estimators': 406, 'subsample': 0.7353169935637712, 'colsample_bytree': 0.78118216846792, 'min_child_weight': 6, 'gamma': 4.229790997264794, 'reg_alpha': 0.033104172493877454, 'reg_lambda': 4.067360662861408e-08, 'max_delta_step': 2}. Best is trial 2 with value: 0.5050682261208577.
[I 2025-11-10 17:44:33,848] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.08803815374975969, 'n_estimators': 412, 'subsample': 0.7419510865865809, 'colsample_bytree': 0.7962480669238291, 'min_child_weight': 6, 'gamma': 1.173699700841665, 'reg_alpha': 0.02087631864198049, 'reg_lambda': 1.8904261947086804e-08, 'max_delta_step': 2}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  11%|█         | 22/200 [00:15<01:08,  2.60it/s]

[I 2025-11-10 17:44:34,109] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.06798212257973761, 'n_estimators': 452, 'subsample': 0.7238895487704018, 'colsample_bytree': 0.7936442414325408, 'min_child_weight': 5, 'gamma': 1.1092920361456706, 'reg_alpha': 0.02511232345138376, 'reg_lambda': 6.581563398878073e-08, 'max_delta_step': 2}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  12%|█▏        | 23/200 [00:16<01:04,  2.73it/s]

[I 2025-11-10 17:44:34,406] Trial 25 pruned.
[I 2025-11-10 17:44:34,416] Trial 23 pruned.

Best trial: 2. Best value: 0.505068:  12%|█▎        | 25/200 [00:16<00:56,  3.09it/s]

[I 2025-11-10 17:44:34,912] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.0169144539409936, 'n_estimators': 426, 'subsample': 0.7391025451245424, 'colsample_bytree': 0.8040239745753409, 'min_child_weight': 6, 'gamma': 1.3485260045116845, 'reg_alpha': 0.03530196901673976, 'reg_lambda': 6.009782777983263e-08, 'max_delta_step': 2}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  13%|█▎        | 26/200 [00:16<00:51,  3.40it/s]

[I 2025-11-10 17:44:35,100] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.29516630021731916, 'n_estimators': 235, 'subsample': 0.5636450416303515, 'colsample_bytree': 0.9505205445652203, 'min_child_weight': 5, 'gamma': 1.101976079436933, 'reg_alpha': 6.457427297017232e-08, 'reg_lambda': 0.0019456721291800261, 'max_delta_step': 2}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  14%|█▎        | 27/200 [00:17<01:10,  2.45it/s]

[I 2025-11-10 17:44:35,882] Trial 29 pruned.

Best trial: 2. Best value: 0.505068:  14%|█▍        | 28/200 [00:19<02:18,  1.25it/s]

[I 2025-11-10 17:44:37,870] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.016321947158042215, 'n_estimators': 798, 'subsample': 0.5785101456940881, 'colsample_bytree': 0.6777463111286008, 'min_child_weight': 5, 'gamma': 2.6667899210688164, 'reg_alpha': 7.169208817604728e-07, 'reg_lambda': 6.0940825901349266e-05, 'max_delta_step': 6}. Best is trial 2 with value: 0.5050682261208577.
[I 2025-11-10 17:44:37,888] Trial 27 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.1348106362736798, 'n_estimators': 794, 'subsample': 0.5783271763386235, 'colsample_bytree': 0.7133552910425153, 'min_child_weight': 8, 'gamma': 2.7384920112778093, 'reg_alpha': 1.6564762503855166e-07, 'reg_lambda': 9.958036119065978e-05, 'max_delta_step': 6}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  16%|█▌        | 31/200 [00:20<01:17,  2.19it/s]

[I 2025-11-10 17:44:38,300] Trial 32 pruned.
[I 2025-11-10 17:44:38,416] Trial 28 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2150237937032348, 'n_estimators': 799, 'subsample': 0.5895754000911398, 'colsample_bytree': 0.6496953322671883, 'min_child_weight': 5, 'gamma': 2.763958119938364, 'reg_alpha': 4.22894955645724e-07, 'reg_lambda': 9.582790327201502e-05, 'max_delta_step': 6}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  16%|█▌        | 32/200 [00:21<01:41,  1.66it/s]

[I 2025-11-10 17:44:39,469] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.21486802913717298, 'n_estimators': 336, 'subsample': 0.7993795222236296, 'colsample_bytree': 0.7462986589886116, 'min_child_weight': 8, 'gamma': 0.7426714005850591, 'reg_alpha': 0.00010875311634199209, 'reg_lambda': 2.654739515958879e-07, 'max_delta_step': 1}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  17%|█▋        | 34/200 [00:21<01:11,  2.31it/s]

[I 2025-11-10 17:44:39,867] Trial 33 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.11578935805287495, 'n_estimators': 317, 'subsample': 0.7900256256289082, 'colsample_bytree': 0.8410390188248518, 'min_child_weight': 7, 'gamma': 4.274660002867949, 'reg_alpha': 0.9334556207266966, 'reg_lambda': 0.011505140303825653, 'max_delta_step': 1}. Best is trial 2 with value: 0.5050682261208577.
[I 2025-11-10 17:44:39,989] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01924118463525174, 'n_estimators': 336, 'subsample': 0.5028879903370774, 'colsample_bytree': 0.6374318750129632, 'min_child_weight': 4, 'gamma': 0.7589584949464974, 'reg_alpha': 0.5786657389829865, 'reg_lambda': 5.748824662386872, 'max_delta_step': 1}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  18%|█▊        | 35/200 [00:22<01:10,  2.35it/s]

[I 2025-11-10 17:44:40,394] Trial 36 pruned.
[I 2025-11-10 17:44:40,477] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.01982834825123411, 'n_estimators': 202, 'subsample': 0.506922602598183, 'colsample_bytree': 0.6596706179135026, 'min_child_weight': 4, 'gamma': 0.5716846092416956, 'reg_alpha': 0.7524310092457648, 'reg_lambda': 1.775121712050945, 'max_delta_step': 0}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  18%|█▊        | 37/200 [00:22<00:47,  3.43it/s]

[I 2025-11-10 17:44:40,641] Trial 37 pruned.

Best trial: 2. Best value: 0.505068:  19%|█▉        | 38/200 [00:22<00:50,  3.20it/s]

[I 2025-11-10 17:44:41,018] Trial 30 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.22978286781842383, 'n_estimators': 1192, 'subsample': 0.7878110344522405, 'colsample_bytree': 0.6700950500818263, 'min_child_weight': 8, 'gamma': 2.651419919152841, 'reg_alpha': 4.4556620592637075e-07, 'reg_lambda': 4.295344173284223e-07, 'max_delta_step': 1}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  20%|██        | 40/200 [00:23<00:41,  3.86it/s]

[I 2025-11-10 17:44:41,325] Trial 39 pruned.
[I 2025-11-10 17:44:41,443] Trial 38 pruned.

Best trial: 2. Best value: 0.505068:  20%|██        | 41/200 [00:23<01:00,  2.63it/s]

[I 2025-11-10 17:44:42,143] Trial 40 pruned.

Best trial: 2. Best value: 0.505068:  21%|██        | 42/200 [00:24<01:08,  2.30it/s]

[I 2025-11-10 17:44:42,718] Trial 42 pruned.
[I 2025-11-10 17:44:42,748] Trial 43 pruned.

Best trial: 2. Best value: 0.505068:  22%|██▏       | 44/200 [00:24<00:54,  2.88it/s]

[I 2025-11-10 17:44:43,195] Trial 41 pruned.

Best trial: 2. Best value: 0.505068:  23%|██▎       | 46/200 [00:26<01:25,  1.81it/s]

[I 2025-11-10 17:44:45,036] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03965226332230769, 'n_estimators': 532, 'subsample': 0.7613255609647739, 'colsample_bytree': 0.7092956615843847, 'min_child_weight': 7, 'gamma': 0.37965710136909875, 'reg_alpha': 0.21346389631672497, 'reg_lambda': 0.01624462324471085, 'max_delta_step': 1}. Best is trial 2 with value: 0.5050682261208577.
[I 2025-11-10 17:44:45,140] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04422536568187992, 'n_estimators': 708, 'subsample': 0.6090575981818824, 'colsample_bytree': 0.7231859382754929, 'min_child_weight': 7, 'gamma': 0.3344489574049958, 'reg_alpha': 0.1294627196397129, 'reg_lambda': 0.022613676460361467, 'max_delta_step': 1}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  24%|██▎       | 47/200 [00:28<01:59,  1.28it/s]

[I 2025-11-10 17:44:46,547] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.04051735969678061, 'n_estimators': 919, 'subsample': 0.6146189749578509, 'colsample_bytree': 0.7203714041731488, 'min_child_weight': 7, 'gamma': 3.34042076567683, 'reg_alpha': 2.980504659709885, 'reg_lambda': 0.010895281272013814, 'max_delta_step': 1}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  24%|██▍       | 48/200 [00:28<01:44,  1.45it/s]

[I 2025-11-10 17:44:46,988] Trial 47 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.066830339994374, 'n_estimators': 916, 'subsample': 0.7604311803482465, 'colsample_bytree': 0.7169686469299035, 'min_child_weight': 7, 'gamma': 0.36692742935748923, 'reg_alpha': 0.18443088943757158, 'reg_lambda': 0.04666699952904136, 'max_delta_step': 1}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  24%|██▍       | 49/200 [00:29<01:48,  1.39it/s]

[I 2025-11-10 17:44:47,793] Trial 49 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.17794474514562253, 'n_estimators': 654, 'subsample': 0.7032574402020113, 'colsample_bytree': 0.6166943824165971, 'min_child_weight': 5, 'gamma': 0.9228054663860368, 'reg_alpha': 0.00038778510271494763, 'reg_lambda': 0.10857191354383568, 'max_delta_step': 4}. Best is trial 2 with value: 0.5050682261208577.
[I 2025-11-10 17:44:47,815] Trial 48 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.05823238751558001, 'n_estimators': 656, 'subsample': 0.6150286717913315, 'colsample_bytree': 0.622735343877884, 'min_child_weight': 5, 'gamma': 0.9276027697115401, 'reg_alpha': 0.2943325226827003, 'reg_lambda': 0.08217960464401934, 'max_delta_step': 4}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  26%|██▌       | 51/200 [00:30<01:51,  1.33it/s]

[I 2025-11-10 17:44:49,366] Trial 50 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.17526650224163626, 'n_estimators': 683, 'subsample': 0.7593726176529425, 'colsample_bytree': 0.615062681026509, 'min_child_weight': 5, 'gamma': 0.9263889186966441, 'reg_alpha': 0.01094766397330439, 'reg_lambda': 0.08287939020861702, 'max_delta_step': 5}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  26%|██▌       | 52/200 [00:31<01:35,  1.55it/s]

[I 2025-11-10 17:44:49,682] Trial 51 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.05428110116081861, 'n_estimators': 632, 'subsample': 0.529598847185202, 'colsample_bytree': 0.6013724737892536, 'min_child_weight': 5, 'gamma': 0.9332081990508451, 'reg_alpha': 0.011944081832142817, 'reg_lambda': 0.09749318699283185, 'max_delta_step': 4}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  27%|██▋       | 54/200 [00:31<01:11,  2.04it/s]

[I 2025-11-10 17:44:50,269] Trial 52 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.05615335700600285, 'n_estimators': 578, 'subsample': 0.641682918106849, 'colsample_bytree': 0.5961015493841695, 'min_child_weight': 6, 'gamma': 1.4755101801285446, 'reg_alpha': 0.00845806518389038, 'reg_lambda': 0.004638332364188834, 'max_delta_step': 5}. Best is trial 2 with value: 0.5050682261208577.
[I 2025-11-10 17:44:50,376] Trial 53 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.010136678026661454, 'n_estimators': 598, 'subsample': 0.5249907582822793, 'colsample_bytree': 0.5006739871129355, 'min_child_weight': 6, 'gamma': 1.484496967764398, 'reg_alpha': 4.593730945834772, 'reg_lambda': 9.698838170774224e-06, 'max_delta_step': 9}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  28%|██▊       | 57/200 [00:33<01:09,  2.06it/s]

[I 2025-11-10 17:44:52,026] Trial 56 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.010432925838923442, 'n_estimators': 374, 'subsample': 0.7198005005842962, 'colsample_bytree': 0.5089159213708289, 'min_child_weight': 6, 'gamma': 4.761160547544119, 'reg_alpha': 0.06598658501620555, 'reg_lambda': 6.03411970064027e-06, 'max_delta_step': 7}. Best is trial 2 with value: 0.5050682261208577.
[I 2025-11-10 17:44:52,090] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.01037482672898966, 'n_estimators': 369, 'subsample': 0.7100262708280499, 'colsample_bytree': 0.5350853823312156, 'min_child_weight': 9, 'gamma': 4.739548292871517, 'reg_alpha': 0.062308986180432006, 'reg_lambda': 1.1472451289725466e-08, 'max_delta_step': 2}. Best is trial 2 with value: 0.5050682261208577.
[I 2025-11-10 17:44:52,179] Trial 54 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.014894804032155515, 'n_estimators': 610, 'subsample': 0.5338719139602501, 'colsample_bytree': 0.5314230093685048, 'min_child_weight': 6, 'gamma': 4.6004732236059676, 'reg_alpha': 0.07146537813498283, 'reg_lambda': 8.155475316066155e-06, 'max_delta_step': 7}. Best is trial 2 with value: 0.5050682261208577.

Best trial: 2. Best value: 0.505068:  30%|██▉       | 59/200 [00:34<00:47,  3.00it/s]

[I 2025-11-10 17:44:52,290] Trial 55 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.010974970626626156, 'n_estimators': 556, 'subsample': 0.6431712861548854, 'colsample_bytree': 0.5016764879924585, 'min_child_weight': 6, 'gamma': 4.622320205207661, 'reg_alpha': 0.07191842547951773, 'reg_lambda': 1.45967374989038e-05, 'max_delta_step': 8}. Best is trial 2 with value: 0.5050682261208577.
[I 2025-11-10 17:44:52,442] Trial 58 pruned.

Best trial: 59. Best value: 0.556491:  30%|███       | 60/200 [00:35<01:13,  1.91it/s]

[I 2025-11-10 17:44:53,486] Trial 59 finished with value: 0.5564912280701755 and parameters: {'max_depth': 7, 'learning_rate': 0.015448054460487963, 'n_estimators': 286, 'subsample': 0.5926927985761863, 'colsample_bytree': 0.7727668665360636, 'min_child_weight': 4, 'gamma': 2.254971308268118, 'reg_alpha': 0.4223697664107285, 'reg_lambda': 1.1822687221892077e-05, 'max_delta_step': 8}. Best is trial 59 with value: 0.5564912280701755.

Best trial: 59. Best value: 0.556491:  30%|███       | 61/200 [00:35<01:24,  1.64it/s]

[I 2025-11-10 17:44:54,325] Trial 60 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.02284437507706974, 'n_estimators': 455, 'subsample': 0.5919444714096006, 'colsample_bytree': 0.8947987388873543, 'min_child_weight': 4, 'gamma': 3.899599968612595, 'reg_alpha': 0.002668862947622035, 'reg_lambda': 3.062840669540856, 'max_delta_step': 0}. Best is trial 59 with value: 0.5564912280701755.

Best trial: 59. Best value: 0.556491:  31%|███       | 62/200 [00:36<01:15,  1.83it/s]

[I 2025-11-10 17:44:54,705] Trial 61 finished with value: 0.5133625730994152 and parameters: {'max_depth': 7, 'learning_rate': 0.022883692823625845, 'n_estimators': 492, 'subsample': 0.6796180829164853, 'colsample_bytree': 0.8954557931608141, 'min_child_weight': 4, 'gamma': 2.1495273146575915, 'reg_alpha': 0.0027196178095454772, 'reg_lambda': 3.7413946663657636, 'max_delta_step': 10}. Best is trial 59 with value: 0.5564912280701755.

Best trial: 59. Best value: 0.556491:  32%|███▏      | 64/200 [00:37<01:08,  2.00it/s]

[I 2025-11-10 17:44:55,636] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.034459460209889235, 'n_estimators': 269, 'subsample': 0.5695180101994809, 'colsample_bytree': 0.8409268128006738, 'min_child_weight': 4, 'gamma': 2.210783252590983, 'reg_alpha': 6.251755594869835, 'reg_lambda': 0.00022080237328668144, 'max_delta_step': 8}. Best is trial 59 with value: 0.5564912280701755.
[I 2025-11-10 17:44:55,756] Trial 63 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.022236932279101465, 'n_estimators': 482, 'subsample': 0.5657254883117371, 'colsample_bytree': 0.7716416995374278, 'min_child_weight': 4, 'gamma': 2.2326502172466305, 'reg_alpha': 0.00278063563823565, 'reg_lambda': 1.4245538804133882e-06, 'max_delta_step': 10}. Best is trial 59 with value: 0.5564912280701755.
[I 2025-11-10 17:44:55,783] Trial 62 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.024198659332811703, 'n_estimators': 742, 'subsample': 0.5623044159427829, 'colsample_bytree': 0.7679886806006379, 'min_child_weight': 4, 'gamma': 3.9827010538752186, 'reg_alpha': 6.189198294280512, 'reg_lambda': 1.402218490747119e-06, 'max_delta_step': 8}. Best is trial 59 with value: 0.5564912280701755.

Best trial: 59. Best value: 0.556491:  34%|███▎      | 67/200 [00:37<00:41,  3.21it/s]

[I 2025-11-10 17:44:56,150] Trial 65 finished with value: 0.5031578947368421 and parameters: {'max_depth': 7, 'learning_rate': 0.023386052849321784, 'n_estimators': 274, 'subsample': 0.573453350902522, 'colsample_bytree': 0.7786019250221472, 'min_child_weight': 4, 'gamma': 2.3303522592699157, 'reg_alpha': 2.206787165327083e-05, 'reg_lambda': 0.49738384813417524, 'max_delta_step': 10}. Best is trial 59 with value: 0.5564912280701755.
[I 2025-11-10 17:44:56,305] Trial 66 pruned.

Best trial: 59. Best value: 0.556491:  34%|███▍      | 69/200 [00:38<00:27,  4.74it/s]

[I 2025-11-10 17:44:56,332] Trial 67 pruned.
[I 2025-11-10 17:44:56,440] Trial 68 pruned.

Best trial: 59. Best value: 0.556491:  36%|███▌      | 72/200 [00:38<00:19,  6.51it/s]

[I 2025-11-10 17:44:56,676] Trial 70 pruned.
[I 2025-11-10 17:44:56,769] Trial 72 pruned.
[I 2025-11-10 17:44:56,779] Trial 71 pruned.

Best trial: 59. Best value: 0.556491:  36%|███▌      | 72/200 [00:38<00:19,  6.51it/s]

[I 2025-11-10 17:44:56,977] Trial 69 pruned.

Best trial: 59. Best value: 0.556491:  37%|███▋      | 74/200 [00:38<00:21,  5.83it/s]

[I 2025-11-10 17:44:57,194] Trial 73 pruned.

Best trial: 59. Best value: 0.556491:  38%|███▊      | 76/200 [00:39<00:37,  3.32it/s]

[I 2025-11-10 17:44:58,275] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.14455979273630312, 'n_estimators': 298, 'subsample': 0.544565650145017, 'colsample_bytree': 0.9248012453318809, 'min_child_weight': 5, 'gamma': 2.4767980136799106, 'reg_alpha': 1.0034676547720167, 'reg_lambda': 1.5893491165534748, 'max_delta_step': 7}. Best is trial 59 with value: 0.5564912280701755.
[I 2025-11-10 17:44:58,384] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.2670151417105899, 'n_estimators': 307, 'subsample': 0.5420833297842956, 'colsample_bytree': 0.9588608136749699, 'min_child_weight': 5, 'gamma': 2.4632983986397443, 'reg_alpha': 0.3253976429036267, 'reg_lambda': 1.423885742967606, 'max_delta_step': 7}. Best is trial 59 with value: 0.5564912280701755.

Best trial: 59. Best value: 0.556491:  38%|███▊      | 77/200 [00:40<00:33,  3.71it/s]

[I 2025-11-10 17:44:58,557] Trial 76 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.15649302567902473, 'n_estimators': 312, 'subsample': 0.6335718572614548, 'colsample_bytree': 0.9289741427447125, 'min_child_weight': 5, 'gamma': 0.4899574830855258, 'reg_alpha': 0.3098417970411296, 'reg_lambda': 2.0009481937544815, 'max_delta_step': 7}. Best is trial 59 with value: 0.5564912280701755.

Best trial: 59. Best value: 0.556491:  40%|███▉      | 79/200 [00:40<00:27,  4.33it/s]

[I 2025-11-10 17:44:58,797] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.07823812394329023, 'n_estimators': 310, 'subsample': 0.5493089563198615, 'colsample_bytree': 0.9215446871739286, 'min_child_weight': 5, 'gamma': 2.089647547725143, 'reg_alpha': 0.4982287210086925, 'reg_lambda': 1.708129198458843, 'max_delta_step': 7}. Best is trial 59 with value: 0.5564912280701755.
[I 2025-11-10 17:44:58,945] Trial 79 pruned.

Best trial: 59. Best value: 0.556491:  40%|████      | 80/200 [00:40<00:34,  3.51it/s]

[I 2025-11-10 17:44:59,369] Trial 81 pruned.

Best trial: 59. Best value: 0.556491:  40%|████      | 81/200 [00:41<00:34,  3.42it/s]

[I 2025-11-10 17:44:59,677] Trial 83 pruned.

Best trial: 59. Best value: 0.556491:  41%|████      | 82/200 [00:41<00:39,  2.96it/s]

[I 2025-11-10 17:45:00,129] Trial 82 finished with value: 0.554074074074074 and parameters: {'max_depth': 6, 'learning_rate': 0.027933344807262644, 'n_estimators': 228, 'subsample': 0.6294222268975816, 'colsample_bytree': 0.7013436532942107, 'min_child_weight': 4, 'gamma': 0.1547308165052645, 'reg_alpha': 0.00024144181662673478, 'reg_lambda': 0.0009520095420261787, 'max_delta_step': 0}. Best is trial 59 with value: 0.5564912280701755.

Best trial: 59. Best value: 0.556491:  42%|████▏     | 83/200 [00:42<00:40,  2.90it/s]

[I 2025-11-10 17:45:00,494] Trial 85 pruned.

Best trial: 59. Best value: 0.556491:  42%|████▏     | 84/200 [00:42<00:40,  2.87it/s]

[I 2025-11-10 17:45:00,849] Trial 80 finished with value: 0.5164912280701754 and parameters: {'max_depth': 5, 'learning_rate': 0.02561314846754257, 'n_estimators': 450, 'subsample': 0.5782087584939789, 'colsample_bytree': 0.6950083679780297, 'min_child_weight': 4, 'gamma': 1.2061874480827117, 'reg_alpha': 0.03538970405755598, 'reg_lambda': 0.15757586621225722, 'max_delta_step': 0}. Best is trial 59 with value: 0.5564912280701755.

Best trial: 59. Best value: 0.556491:  42%|████▎     | 85/200 [00:43<00:54,  2.11it/s]

[I 2025-11-10 17:45:01,620] Trial 86 finished with value: 0.5014814814814815 and parameters: {'max_depth': 6, 'learning_rate': 0.029397906349739863, 'n_estimators': 231, 'subsample': 0.6249816134129484, 'colsample_bytree': 0.5809675922848802, 'min_child_weight': 4, 'gamma': 0.48774981679001783, 'reg_alpha': 0.0002865874287078208, 'reg_lambda': 0.003901110078788732, 'max_delta_step': 1}. Best is trial 59 with value: 0.5564912280701755.

Best trial: 59. Best value: 0.556491:  43%|████▎     | 86/200 [00:43<00:54,  2.08it/s]

[I 2025-11-10 17:45:02,116] Trial 87 finished with value: 0.5031578947368421 and parameters: {'max_depth': 5, 'learning_rate': 0.030737857185109033, 'n_estimators': 264, 'subsample': 0.5773305734708667, 'colsample_bytree': 0.7594477565022105, 'min_child_weight': 4, 'gamma': 1.6195239825711847, 'reg_alpha': 0.00024038832887891815, 'reg_lambda': 0.003707860814057098, 'max_delta_step': 0}. Best is trial 59 with value: 0.5564912280701755.

Best trial: 59. Best value: 0.556491:  44%|████▍     | 88/200 [00:44<00:37,  2.98it/s]

[I 2025-11-10 17:45:02,349] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.014310447710956638, 'n_estimators': 862, 'subsample': 0.5555218456781328, 'colsample_bytree': 0.7368323770026214, 'min_child_weight': 5, 'gamma': 1.8225696040164505, 'reg_alpha': 2.978619064411547e-06, 'reg_lambda': 3.1494650946665745e-05, 'max_delta_step': 8}. Best is trial 59 with value: 0.5564912280701755.
[I 2025-11-10 17:45:02,520] Trial 89 pruned.

Best trial: 59. Best value: 0.556491:  44%|████▍     | 89/200 [00:44<00:31,  3.47it/s]

[I 2025-11-10 17:45:02,696] Trial 90 pruned.

Best trial: 59. Best value: 0.556491:  45%|████▌     | 90/200 [00:44<00:34,  3.20it/s]

[I 2025-11-10 17:45:03,066] Trial 88 finished with value: 0.5376023391812866 and parameters: {'max_depth': 4, 'learning_rate': 0.028701293428164812, 'n_estimators': 271, 'subsample': 0.5807563977938152, 'colsample_bytree': 0.7575797317607218, 'min_child_weight': 4, 'gamma': 1.4939097425716699, 'reg_alpha': 0.0001620928306216671, 'reg_lambda': 0.0033375091659040043, 'max_delta_step': 0}. Best is trial 59 with value: 0.5564912280701755.

Best trial: 59. Best value: 0.556491:  46%|████▌     | 91/200 [00:45<00:36,  3.01it/s]

[I 2025-11-10 17:45:03,443] Trial 93 pruned.

Best trial: 59. Best value: 0.556491:  46%|████▌     | 92/200 [00:45<00:34,  3.13it/s]

[I 2025-11-10 17:45:03,732] Trial 91 finished with value: 0.5164912280701754 and parameters: {'max_depth': 4, 'learning_rate': 0.02750576009719791, 'n_estimators': 224, 'subsample': 0.5778057393440964, 'colsample_bytree': 0.756350066239648, 'min_child_weight': 4, 'gamma': 1.5484515075874143, 'reg_alpha': 0.00021235767466714215, 'reg_lambda': 0.00018278690711097197, 'max_delta_step': 0}. Best is trial 59 with value: 0.5564912280701755.

Best trial: 59. Best value: 0.556491:  46%|████▋     | 93/200 [00:45<00:35,  3.01it/s]

[I 2025-11-10 17:45:04,096] Trial 84 finished with value: 0.4715497076023391 and parameters: {'max_depth': 8, 'learning_rate': 0.027912637989391524, 'n_estimators': 869, 'subsample': 0.6934578036212053, 'colsample_bytree': 0.8805281575545287, 'min_child_weight': 4, 'gamma': 4.314738684619322, 'reg_alpha': 0.028072856737257037, 'reg_lambda': 0.0008276223871835077, 'max_delta_step': 6}. Best is trial 59 with value: 0.5564912280701755.

Best trial: 94. Best value: 0.586491:  48%|████▊     | 95/200 [00:46<00:43,  2.44it/s]

[I 2025-11-10 17:45:05,089] Trial 94 finished with value: 0.5864912280701755 and parameters: {'max_depth': 5, 'learning_rate': 0.02448790640493022, 'n_estimators': 341, 'subsample': 0.5857807451881571, 'colsample_bytree': 0.6927053190100542, 'min_child_weight': 4, 'gamma': 1.1666319215804606, 'reg_alpha': 1.578457186697526e-05, 'reg_lambda': 0.0008731992786769591, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.
[I 2025-11-10 17:45:05,218] Trial 96 finished with value: 0.5031578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.036764203732803896, 'n_estimators': 230, 'subsample': 0.5774264107382241, 'colsample_bytree': 0.6981017830353005, 'min_child_weight': 4, 'gamma': 1.3804980654734775, 'reg_alpha': 1.5786932476346576e-05, 'reg_lambda': 0.025864402991614556, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  48%|████▊     | 96/200 [00:47<00:35,  2.90it/s]

[I 2025-11-10 17:45:05,410] Trial 95 finished with value: 0.5376023391812866 and parameters: {'max_depth': 4, 'learning_rate': 0.036638267766618125, 'n_estimators': 344, 'subsample': 0.5826844992995673, 'colsample_bytree': 0.7019995438550618, 'min_child_weight': 4, 'gamma': 1.1729282264506709, 'reg_alpha': 8.400653677652855e-05, 'reg_lambda': 0.0009737564857546855, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  48%|████▊     | 97/200 [00:47<00:34,  3.01it/s]

[I 2025-11-10 17:45:05,712] Trial 98 pruned.

Best trial: 94. Best value: 0.586491:  49%|████▉     | 98/200 [00:47<00:35,  2.83it/s]

[I 2025-11-10 17:45:06,114] Trial 99 pruned.

Best trial: 94. Best value: 0.586491:  50%|████▉     | 99/200 [00:48<00:35,  2.82it/s]

[I 2025-11-10 17:45:06,474] Trial 100 pruned.
[I 2025-11-10 17:45:06,570] Trial 101 pruned.

Best trial: 94. Best value: 0.586491:  50%|█████     | 101/200 [00:48<00:34,  2.87it/s]

[I 2025-11-10 17:45:07,154] Trial 97 finished with value: 0.5031578947368421 and parameters: {'max_depth': 3, 'learning_rate': 0.02546386332986205, 'n_estimators': 405, 'subsample': 0.5769314559768404, 'colsample_bytree': 0.6906938065589596, 'min_child_weight': 4, 'gamma': 1.3444275762332272, 'reg_alpha': 7.534728041101782e-05, 'reg_lambda': 0.00017645651667217175, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  51%|█████     | 102/200 [00:49<00:44,  2.19it/s]

[I 2025-11-10 17:45:07,940] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.050368173071191104, 'n_estimators': 284, 'subsample': 0.5844522990228305, 'colsample_bytree': 0.7307699997699767, 'min_child_weight': 5, 'gamma': 2.284421646604252, 'reg_alpha': 2.4147792658543784e-05, 'reg_lambda': 0.0009251818989976876, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  52%|█████▏    | 104/200 [00:50<00:37,  2.59it/s]

[I 2025-11-10 17:45:08,426] Trial 92 finished with value: 0.5231578947368422 and parameters: {'max_depth': 5, 'learning_rate': 0.026533467221116054, 'n_estimators': 1174, 'subsample': 0.5769500658557022, 'colsample_bytree': 0.8865229866128667, 'min_child_weight': 4, 'gamma': 1.9618665920649128, 'reg_alpha': 0.004005038244940347, 'reg_lambda': 0.008425987776903924, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.
[I 2025-11-10 17:45:08,604] Trial 104 finished with value: 0.5376023391812866 and parameters: {'max_depth': 5, 'learning_rate': 0.04734230077926889, 'n_estimators': 290, 'subsample': 0.5829130162644742, 'colsample_bytree': 0.7897582404730605, 'min_child_weight': 4, 'gamma': 1.54171096311347, 'reg_alpha': 0.00014443451669709113, 'reg_lambda': 6.331039453484067e-05, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  52%|█████▎    | 105/200 [00:51<00:56,  1.68it/s]

[I 2025-11-10 17:45:09,731] Trial 107 pruned.

Best trial: 94. Best value: 0.586491:  53%|█████▎    | 106/200 [00:51<00:52,  1.80it/s]

[I 2025-11-10 17:45:10,191] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03787260927836276, 'n_estimators': 490, 'subsample': 0.569975691911778, 'colsample_bytree': 0.7970696020568977, 'min_child_weight': 4, 'gamma': 1.5403799858759977, 'reg_alpha': 0.00015469682449729619, 'reg_lambda': 0.0013790699205591392, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.
[I 2025-11-10 17:45:10,210] Trial 108 pruned.

Best trial: 94. Best value: 0.586491:  54%|█████▍    | 108/200 [00:53<00:54,  1.68it/s]

[I 2025-11-10 17:45:11,476] Trial 102 finished with value: 0.5186549707602339 and parameters: {'max_depth': 4, 'learning_rate': 0.04467999461062547, 'n_estimators': 1132, 'subsample': 0.6023995027223418, 'colsample_bytree': 0.70721501544027, 'min_child_weight': 4, 'gamma': 1.2343416172542356, 'reg_alpha': 0.00013936488565607097, 'reg_lambda': 0.0005618010862629553, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  55%|█████▍    | 109/200 [00:54<01:22,  1.11it/s]

[I 2025-11-10 17:45:13,344] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03274404335886739, 'n_estimators': 1194, 'subsample': 0.5581316009055923, 'colsample_bytree': 0.6592274865150838, 'min_child_weight': 4, 'gamma': 2.096330725087076, 'reg_alpha': 0.004260388099662126, 'reg_lambda': 5.952218467691499e-05, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  55%|█████▌    | 110/200 [00:55<01:24,  1.07it/s]

[I 2025-11-10 17:45:14,381] Trial 110 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.044073925991540135, 'n_estimators': 1032, 'subsample': 0.5973152638703335, 'colsample_bytree': 0.6471287879415432, 'min_child_weight': 5, 'gamma': 1.238365655465456, 'reg_alpha': 0.004066270499125527, 'reg_lambda': 0.00035675502961813194, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  56%|█████▌    | 111/200 [00:56<01:08,  1.29it/s]

[I 2025-11-10 17:45:14,710] Trial 109 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.04482826859401032, 'n_estimators': 1055, 'subsample': 0.5955030000931217, 'colsample_bytree': 0.8949811880101706, 'min_child_weight': 5, 'gamma': 1.9131731564065784, 'reg_alpha': 0.017080574429553446, 'reg_lambda': 0.0007107034941332495, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  56%|█████▌    | 112/200 [00:57<01:16,  1.16it/s]

[I 2025-11-10 17:45:15,814] Trial 114 pruned.

Best trial: 94. Best value: 0.586491:  56%|█████▋    | 113/200 [00:57<01:01,  1.43it/s]

[I 2025-11-10 17:45:16,100] Trial 111 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04550453764884446, 'n_estimators': 1129, 'subsample': 0.5952621409995353, 'colsample_bytree': 0.7108216688903357, 'min_child_weight': 5, 'gamma': 1.2824219766048826, 'reg_alpha': 0.004500227575178578, 'reg_lambda': 0.0003325291492998928, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  57%|█████▋    | 114/200 [00:58<00:52,  1.63it/s]

[I 2025-11-10 17:45:16,495] Trial 116 pruned.

Best trial: 94. Best value: 0.586491:  57%|█████▊    | 115/200 [00:58<00:49,  1.73it/s]

[I 2025-11-10 17:45:16,986] Trial 115 pruned.

Best trial: 94. Best value: 0.586491:  58%|█████▊    | 116/200 [00:59<00:55,  1.50it/s]

[I 2025-11-10 17:45:17,859] Trial 118 pruned.

Best trial: 94. Best value: 0.586491:  58%|█████▊    | 117/200 [00:59<00:44,  1.85it/s]

[I 2025-11-10 17:45:18,106] Trial 119 pruned.
[I 2025-11-10 17:45:18,142] Trial 112 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04588343213288608, 'n_estimators': 1124, 'subsample': 0.5957956100527995, 'colsample_bytree': 0.707560558177254, 'min_child_weight': 5, 'gamma': 1.9509692114688486, 'reg_alpha': 0.0009643290606907038, 'reg_lambda': 0.002275764775040391, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  60%|█████▉    | 119/200 [01:00<00:47,  1.71it/s]

[I 2025-11-10 17:45:19,376] Trial 113 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.048220110891377885, 'n_estimators': 1148, 'subsample': 0.5870490393620095, 'colsample_bytree': 0.7084183245924267, 'min_child_weight': 5, 'gamma': 1.9478392759190064, 'reg_alpha': 0.0013269500948064545, 'reg_lambda': 0.0006882339033359438, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  60%|██████    | 121/200 [01:02<00:54,  1.45it/s]

[I 2025-11-10 17:45:21,157] Trial 122 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.021676275164421034, 'n_estimators': 387, 'subsample': 0.5689090206326193, 'colsample_bytree': 0.8511236123992014, 'min_child_weight': 4, 'gamma': 1.494025768444672, 'reg_alpha': 0.04277165912754621, 'reg_lambda': 0.0005259351992316203, 'max_delta_step': 6}. Best is trial 94 with value: 0.5864912280701755.
[I 2025-11-10 17:45:21,312] Trial 117 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.027259478285714223, 'n_estimators': 1134, 'subsample': 0.5663348820935306, 'colsample_bytree': 0.6715323291475734, 'min_child_weight': 4, 'gamma': 0.8396108967463412, 'reg_alpha': 0.00040514481296263284, 'reg_lambda': 0.0001271531136405026, 'max_delta_step': 5}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  61%|██████    | 122/200 [01:03<00:46,  1.67it/s]

[I 2025-11-10 17:45:21,669] Trial 123 pruned.

Best trial: 94. Best value: 0.586491:  62%|██████▏   | 123/200 [01:04<00:53,  1.43it/s]

[I 2025-11-10 17:45:22,625] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.023221315390793276, 'n_estimators': 283, 'subsample': 0.5505270915125473, 'colsample_bytree': 0.832553031805471, 'min_child_weight': 4, 'gamma': 1.7427173212734006, 'reg_alpha': 2.6242152115343498e-05, 'reg_lambda': 0.000307802795408864, 'max_delta_step': 10}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  62%|██████▎   | 125/200 [01:04<00:34,  2.17it/s]

[I 2025-11-10 17:45:22,970] Trial 126 pruned.
[I 2025-11-10 17:45:23,093] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01626245003475486, 'n_estimators': 280, 'subsample': 0.5490075108796135, 'colsample_bytree': 0.8347426523117225, 'min_child_weight': 4, 'gamma': 1.720759410506033, 'reg_alpha': 2.5391488416572043e-05, 'reg_lambda': 0.00027290930458495806, 'max_delta_step': 10}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  63%|██████▎   | 126/200 [01:05<00:36,  2.01it/s]

[I 2025-11-10 17:45:23,678] Trial 120 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03255239628565019, 'n_estimators': 1273, 'subsample': 0.5696231423722804, 'colsample_bytree': 0.7859842110730074, 'min_child_weight': 4, 'gamma': 0.8378945916129885, 'reg_alpha': 9.40009230975397e-05, 'reg_lambda': 0.0006806720629032947, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  64%|██████▎   | 127/200 [01:05<00:29,  2.47it/s]

[I 2025-11-10 17:45:23,862] Trial 121 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.06121097344463537, 'n_estimators': 1312, 'subsample': 0.5648383986893267, 'colsample_bytree': 0.762874417690712, 'min_child_weight': 4, 'gamma': 2.5842687861073985, 'reg_alpha': 0.10918555705997816, 'reg_lambda': 0.0005340243279956877, 'max_delta_step': 6}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  64%|██████▍   | 128/200 [01:05<00:28,  2.54it/s]

[I 2025-11-10 17:45:24,229] Trial 130 pruned.

Best trial: 94. Best value: 0.586491:  64%|██████▍   | 129/200 [01:06<00:28,  2.49it/s]

[I 2025-11-10 17:45:24,648] Trial 131 pruned.

Best trial: 94. Best value: 0.586491:  65%|██████▌   | 130/200 [01:06<00:26,  2.65it/s]

[I 2025-11-10 17:45:24,970] Trial 129 pruned.
[I 2025-11-10 17:45:25,065] Trial 132 pruned.

Best trial: 94. Best value: 0.586491:  66%|██████▌   | 132/200 [01:07<00:34,  1.97it/s]

[I 2025-11-10 17:45:26,291] Trial 134 finished with value: 0.5164912280701754 and parameters: {'max_depth': 5, 'learning_rate': 0.026283018553224492, 'n_estimators': 264, 'subsample': 0.5784378406132917, 'colsample_bytree': 0.7781584776631395, 'min_child_weight': 4, 'gamma': 1.573913636599488, 'reg_alpha': 0.00019629284905291948, 'reg_lambda': 0.005015491512141303, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  66%|██████▋   | 133/200 [01:08<00:30,  2.20it/s]

[I 2025-11-10 17:45:26,582] Trial 135 pruned.

Best trial: 94. Best value: 0.586491:  67%|██████▋   | 134/200 [01:09<00:46,  1.41it/s]

[I 2025-11-10 17:45:28,009] Trial 136 finished with value: 0.5031578947368421 and parameters: {'max_depth': 5, 'learning_rate': 0.023995537999541093, 'n_estimators': 305, 'subsample': 0.5768031701941536, 'colsample_bytree': 0.886905912341224, 'min_child_weight': 4, 'gamma': 1.4984577712047888, 'reg_alpha': 0.0004607435940279833, 'reg_lambda': 0.004856418090649225, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  68%|██████▊   | 135/200 [01:10<00:41,  1.56it/s]

[I 2025-11-10 17:45:28,469] Trial 137 pruned.

Best trial: 94. Best value: 0.586491:  68%|██████▊   | 136/200 [01:10<00:34,  1.87it/s]

[I 2025-11-10 17:45:28,735] Trial 127 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03198143956857434, 'n_estimators': 1233, 'subsample': 0.5357607972196374, 'colsample_bytree': 0.9398080427125349, 'min_child_weight': 4, 'gamma': 1.7003605718260824, 'reg_alpha': 4.33697496716296e-05, 'reg_lambda': 3.1855109785290966e-06, 'max_delta_step': 9}. Best is trial 94 with value: 0.5864912280701755.
[I 2025-11-10 17:45:28,826] Trial 128 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.031945355165436215, 'n_estimators': 1246, 'subsample': 0.5710534122972626, 'colsample_bytree': 0.9047980776883086, 'min_child_weight': 4, 'gamma': 2.2816084507971297, 'reg_alpha': 4.897102918452409e-05, 'reg_lambda': 4.363190926088033, 'max_delta_step': 9}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  69%|██████▉   | 138/200 [01:11<00:30,  2.05it/s]

[I 2025-11-10 17:45:29,589] Trial 138 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.021925618710465507, 'n_estimators': 205, 'subsample': 0.5801117545410936, 'colsample_bytree': 0.7770951082265632, 'min_child_weight': 4, 'gamma': 4.990702093036383, 'reg_alpha': 0.00024230613573306608, 'reg_lambda': 4.464627729682515, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  70%|██████▉   | 139/200 [01:11<00:29,  2.03it/s]

[I 2025-11-10 17:45:30,091] Trial 140 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.021072345197453945, 'n_estimators': 251, 'subsample': 0.5803521618051241, 'colsample_bytree': 0.777443841574033, 'min_child_weight': 5, 'gamma': 1.8928315868736303, 'reg_alpha': 1.1874684169197887e-05, 'reg_lambda': 0.0032027211711596233, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.
[I 2025-11-10 17:45:30,095] Trial 139 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.020392526695352593, 'n_estimators': 260, 'subsample': 0.585746049655326, 'colsample_bytree': 0.7384386943326054, 'min_child_weight': 5, 'gamma': 1.8401974951706297, 'reg_alpha': 0.0002789990849370713, 'reg_lambda': 0.05991552460661764, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  70%|███████   | 141/200 [01:12<00:23,  2.55it/s]

[I 2025-11-10 17:45:30,582] Trial 143 pruned.

Best trial: 94. Best value: 0.586491:  71%|███████   | 142/200 [01:12<00:22,  2.56it/s]

[I 2025-11-10 17:45:30,974] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.052349798513818956, 'n_estimators': 261, 'subsample': 0.5568675862768654, 'colsample_bytree': 0.687859275071342, 'min_child_weight': 5, 'gamma': 1.298272183249459, 'reg_alpha': 1.2142912617559485e-05, 'reg_lambda': 0.002651467033632399, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  72%|███████▏  | 143/200 [01:12<00:22,  2.58it/s]

[I 2025-11-10 17:45:31,348] Trial 145 pruned.

Best trial: 94. Best value: 0.586491:  72%|███████▏  | 144/200 [01:13<00:20,  2.71it/s]

[I 2025-11-10 17:45:31,664] Trial 142 pruned.

Best trial: 94. Best value: 0.586491:  72%|███████▎  | 145/200 [01:13<00:18,  2.99it/s]

[I 2025-11-10 17:45:31,908] Trial 133 finished with value: 0.49000000000000005 and parameters: {'max_depth': 5, 'learning_rate': 0.026702148889369427, 'n_estimators': 1484, 'subsample': 0.5774562265455297, 'colsample_bytree': 0.7476551312694184, 'min_child_weight': 4, 'gamma': 1.4415896939402313, 'reg_alpha': 1.2673606207067048e-05, 'reg_lambda': 4.031298974879766, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  73%|███████▎  | 146/200 [01:13<00:17,  3.11it/s]

[I 2025-11-10 17:45:32,193] Trial 144 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.0346659288357556, 'n_estimators': 297, 'subsample': 0.5580959661062658, 'colsample_bytree': 0.7924606328520047, 'min_child_weight': 4, 'gamma': 1.582493010909108, 'reg_alpha': 0.002129730417942859, 'reg_lambda': 0.0024968591266707287, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  74%|███████▎  | 147/200 [01:14<00:18,  2.91it/s]

[I 2025-11-10 17:45:32,595] Trial 146 finished with value: 0.5031578947368421 and parameters: {'max_depth': 5, 'learning_rate': 0.03439437298000783, 'n_estimators': 229, 'subsample': 0.575814018410329, 'colsample_bytree': 0.7920966368478455, 'min_child_weight': 4, 'gamma': 1.4436553234531813, 'reg_alpha': 8.000773214208048e-05, 'reg_lambda': 0.0014507214167562082, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  74%|███████▍  | 148/200 [01:14<00:17,  3.00it/s]

[I 2025-11-10 17:45:32,904] Trial 147 finished with value: 0.5031578947368421 and parameters: {'max_depth': 6, 'learning_rate': 0.029621074075395843, 'n_estimators': 226, 'subsample': 0.5751931074512605, 'colsample_bytree': 0.7197077725898143, 'min_child_weight': 4, 'gamma': 1.4098512217874668, 'reg_alpha': 9.662632665215371e-05, 'reg_lambda': 0.011595904390238752, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  74%|███████▍  | 149/200 [01:15<00:25,  2.02it/s]

[I 2025-11-10 17:45:33,785] Trial 148 finished with value: 0.5864912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.024135608940617222, 'n_estimators': 384, 'subsample': 0.5911523048217481, 'colsample_bytree': 0.7913099471379189, 'min_child_weight': 4, 'gamma': 1.1186036354922528, 'reg_alpha': 0.01727047541125453, 'reg_lambda': 0.011386315504320786, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  75%|███████▌  | 150/200 [01:15<00:21,  2.30it/s]

[I 2025-11-10 17:45:34,076] Trial 149 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.037943764789514764, 'n_estimators': 387, 'subsample': 0.5898459109164588, 'colsample_bytree': 0.7241163075778144, 'min_child_weight': 4, 'gamma': 2.1239402215142746, 'reg_alpha': 0.00033946324467541136, 'reg_lambda': 0.0011983008437766742, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  76%|███████▌  | 151/200 [01:16<00:20,  2.44it/s]

[I 2025-11-10 17:45:34,427] Trial 150 finished with value: 0.5464912280701755 and parameters: {'max_depth': 5, 'learning_rate': 0.02971518136561115, 'n_estimators': 379, 'subsample': 0.5941999680461448, 'colsample_bytree': 0.7179156682642819, 'min_child_weight': 4, 'gamma': 2.040282417557414, 'reg_alpha': 0.0003415357781363711, 'reg_lambda': 0.009017494999306359, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  76%|███████▌  | 152/200 [01:16<00:19,  2.53it/s]

[I 2025-11-10 17:45:34,791] Trial 151 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.025183366714672844, 'n_estimators': 384, 'subsample': 0.5906777519391584, 'colsample_bytree': 0.7649883537540588, 'min_child_weight': 4, 'gamma': 2.133813481646758, 'reg_alpha': 0.0006812354036672877, 'reg_lambda': 0.00011045242445738915, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  76%|███████▋  | 153/200 [01:17<00:25,  1.81it/s]

[I 2025-11-10 17:45:35,713] Trial 152 finished with value: 0.5864912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.02438320119048127, 'n_estimators': 389, 'subsample': 0.5919536587566232, 'colsample_bytree': 0.8054621851531861, 'min_child_weight': 4, 'gamma': 1.1483697828387727, 'reg_alpha': 0.015246786947213984, 'reg_lambda': 0.018817213211295883, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  77%|███████▋  | 154/200 [01:17<00:23,  1.92it/s]

[I 2025-11-10 17:45:36,158] Trial 153 finished with value: 0.495 and parameters: {'max_depth': 6, 'learning_rate': 0.03802941611384296, 'n_estimators': 439, 'subsample': 0.62702769722528, 'colsample_bytree': 0.7300559588278007, 'min_child_weight': 4, 'gamma': 1.0911565986623963, 'reg_alpha': 0.17717715666645678, 'reg_lambda': 0.016292031587462615, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  78%|███████▊  | 155/200 [01:18<00:20,  2.16it/s]

[I 2025-11-10 17:45:36,489] Trial 154 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.03880365579164437, 'n_estimators': 439, 'subsample': 0.5950153972324619, 'colsample_bytree': 0.6941808089279193, 'min_child_weight': 4, 'gamma': 2.139039126749678, 'reg_alpha': 0.011697464227428194, 'reg_lambda': 0.020491670404612437, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  78%|███████▊  | 156/200 [01:18<00:17,  2.58it/s]

[I 2025-11-10 17:45:36,699] Trial 155 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.038224905655964536, 'n_estimators': 387, 'subsample': 0.5937470396725082, 'colsample_bytree': 0.7314317002859851, 'min_child_weight': 4, 'gamma': 2.116574724129206, 'reg_alpha': 0.014999828115169889, 'reg_lambda': 0.03212094482683827, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  78%|███████▊  | 157/200 [01:19<00:22,  1.88it/s]

[I 2025-11-10 17:45:37,569] Trial 156 finished with value: 0.5864912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.04186131228572658, 'n_estimators': 391, 'subsample': 0.5875514342453975, 'colsample_bytree': 0.7188947913352925, 'min_child_weight': 4, 'gamma': 1.127817808092761, 'reg_alpha': 0.017234925309987978, 'reg_lambda': 0.014346161791131079, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  80%|███████▉  | 159/200 [01:19<00:15,  2.63it/s]

[I 2025-11-10 17:45:37,985] Trial 160 pruned.
[I 2025-11-10 17:45:38,091] Trial 157 finished with value: 0.5864912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.04260988247353422, 'n_estimators': 375, 'subsample': 0.5939840579223766, 'colsample_bytree': 0.8062483784416759, 'min_child_weight': 4, 'gamma': 1.170980832786758, 'reg_alpha': 0.0006663913743967447, 'reg_lambda': 0.00833006748549991, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  80%|████████  | 160/200 [01:19<00:14,  2.81it/s]

[I 2025-11-10 17:45:38,391] Trial 158 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.038937584706993086, 'n_estimators': 393, 'subsample': 0.5940696554058046, 'colsample_bytree': 0.6981483646911989, 'min_child_weight': 4, 'gamma': 2.0342944145468493, 'reg_alpha': 0.014064102466536008, 'reg_lambda': 0.022247711409359345, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  80%|████████  | 161/200 [01:20<00:12,  3.05it/s]

[I 2025-11-10 17:45:38,652] Trial 159 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.04190047218938826, 'n_estimators': 387, 'subsample': 0.5949126326485819, 'colsample_bytree': 0.7038489567796135, 'min_child_weight': 4, 'gamma': 2.003959832172882, 'reg_alpha': 0.014860128377099947, 'reg_lambda': 0.03201235597134371, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  81%|████████  | 162/200 [01:21<00:23,  1.63it/s]

[I 2025-11-10 17:45:39,927] Trial 162 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.041257817836684314, 'n_estimators': 378, 'subsample': 0.5945228744653175, 'colsample_bytree': 0.7344540949527443, 'min_child_weight': 4, 'gamma': 2.156221650817615, 'reg_alpha': 0.01017207147989472, 'reg_lambda': 0.017771009534295924, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.
[I 2025-11-10 17:45:39,954] Trial 161 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.04151735142363335, 'n_estimators': 381, 'subsample': 0.5939862789493993, 'colsample_bytree': 0.702141373367151, 'min_child_weight': 4, 'gamma': 2.1410517208959585, 'reg_alpha': 0.009071737354614338, 'reg_lambda': 0.00958865910618218, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  82%|████████▏ | 164/200 [01:22<00:16,  2.24it/s]

[I 2025-11-10 17:45:40,431] Trial 164 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.04117044214102365, 'n_estimators': 362, 'subsample': 0.5891393725812173, 'colsample_bytree': 0.6772640007790789, 'min_child_weight': 4, 'gamma': 2.1160634833655787, 'reg_alpha': 0.009268696816957599, 'reg_lambda': 0.04111843803466969, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.
[I 2025-11-10 17:45:40,604] Trial 163 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.03839371924741418, 'n_estimators': 426, 'subsample': 0.5928117477742753, 'colsample_bytree': 0.8227385970854136, 'min_child_weight': 4, 'gamma': 2.17028060136694, 'reg_alpha': 0.018482649646504753, 'reg_lambda': 0.044678514935572164, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  84%|████████▎ | 167/200 [01:23<00:14,  2.23it/s]

[I 2025-11-10 17:45:41,741] Trial 165 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.04227320189249177, 'n_estimators': 374, 'subsample': 0.5949514989127269, 'colsample_bytree': 0.6995674214805849, 'min_child_weight': 4, 'gamma': 2.174174258603132, 'reg_alpha': 0.011125965955811345, 'reg_lambda': 0.05184900529450674, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.
[I 2025-11-10 17:45:41,842] Trial 166 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.04226087882055133, 'n_estimators': 372, 'subsample': 0.5953324065898259, 'colsample_bytree': 0.7377956091690528, 'min_child_weight': 4, 'gamma': 2.0611598617574547, 'reg_alpha': 0.011150946542271858, 'reg_lambda': 0.02031388563187127, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  84%|████████▍ | 168/200 [01:23<00:13,  2.37it/s]

[I 2025-11-10 17:45:42,194] Trial 169 pruned.
[I 2025-11-10 17:45:42,372] Trial 170 pruned.

Best trial: 94. Best value: 0.586491:  84%|████████▍ | 169/200 [01:24<00:10,  2.85it/s]

[I 2025-11-10 17:45:42,460] Trial 167 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.04229083810726451, 'n_estimators': 381, 'subsample': 0.5933799994555254, 'colsample_bytree': 0.6808359681858513, 'min_child_weight': 4, 'gamma': 2.3518252504339925, 'reg_alpha': 0.010241353268636658, 'reg_lambda': 0.047813819485422106, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  86%|████████▌ | 171/200 [01:24<00:07,  3.67it/s]

[I 2025-11-10 17:45:42,723] Trial 168 finished with value: 0.5409356725146199 and parameters: {'max_depth': 6, 'learning_rate': 0.04257329114246709, 'n_estimators': 427, 'subsample': 0.5978234629269245, 'colsample_bytree': 0.7212637664700421, 'min_child_weight': 4, 'gamma': 2.170958073691934, 'reg_alpha': 0.02413129661637046, 'reg_lambda': 0.019880854816398313, 'max_delta_step': 2}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  86%|████████▌ | 172/200 [01:24<00:08,  3.27it/s]

[I 2025-11-10 17:45:43,137] Trial 174 pruned.

Best trial: 94. Best value: 0.586491:  87%|████████▋ | 174/200 [01:26<00:11,  2.36it/s]

[I 2025-11-10 17:45:44,306] Trial 171 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03838898011552976, 'n_estimators': 427, 'subsample': 0.6072975247974729, 'colsample_bytree': 0.8228936449608659, 'min_child_weight': 5, 'gamma': 2.397442302819306, 'reg_alpha': 0.023934504812848298, 'reg_lambda': 0.032522654882506045, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.
[I 2025-11-10 17:45:44,444] Trial 172 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05003735230209104, 'n_estimators': 424, 'subsample': 0.6057282074310949, 'colsample_bytree': 0.8042526676114298, 'min_child_weight': 5, 'gamma': 2.356366623802143, 'reg_alpha': 0.0497368402286577, 'reg_lambda': 0.0336862607305432, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  87%|████████▋ | 174/200 [01:26<00:11,  2.36it/s]

[I 2025-11-10 17:45:44,504] Trial 173 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.039261239128309866, 'n_estimators': 423, 'subsample': 0.6410380177230605, 'colsample_bytree': 0.803838806556921, 'min_child_weight': 5, 'gamma': 2.5102598150187014, 'reg_alpha': 0.04694639395922182, 'reg_lambda': 0.02832735441162176, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  88%|████████▊ | 176/200 [01:26<00:09,  2.44it/s]

[I 2025-11-10 17:45:45,227] Trial 175 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.04933733478864532, 'n_estimators': 444, 'subsample': 0.5898485243281539, 'colsample_bytree': 0.8056170853957481, 'min_child_weight': 4, 'gamma': 2.3768929532188623, 'reg_alpha': 0.006522405354823251, 'reg_lambda': 0.029387514812959113, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  89%|████████▉ | 178/200 [01:27<00:09,  2.34it/s]

[I 2025-11-10 17:45:46,107] Trial 177 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.046243144520755605, 'n_estimators': 358, 'subsample': 0.5900568983112662, 'colsample_bytree': 0.6598219118679025, 'min_child_weight': 4, 'gamma': 2.0067812712767346, 'reg_alpha': 0.007747068589032753, 'reg_lambda': 0.06772151795755713, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.
[I 2025-11-10 17:45:46,259] Trial 178 finished with value: 0.5209356725146199 and parameters: {'max_depth': 6, 'learning_rate': 0.036033595919796844, 'n_estimators': 367, 'subsample': 0.5909666892783244, 'colsample_bytree': 0.6633065567436564, 'min_child_weight': 4, 'gamma': 1.8765261819287056, 'reg_alpha': 0.006650932924885539, 'reg_lambda': 0.012957921760432768, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  90%|████████▉ | 179/200 [01:28<00:08,  2.34it/s]

[I 2025-11-10 17:45:46,687] Trial 181 pruned.

Best trial: 94. Best value: 0.586491:  90%|█████████ | 180/200 [01:28<00:07,  2.73it/s]

[I 2025-11-10 17:45:46,890] Trial 176 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.04916070966516672, 'n_estimators': 510, 'subsample': 0.5900374851345606, 'colsample_bytree': 0.8100500299227577, 'min_child_weight': 4, 'gamma': 1.9682127365399142, 'reg_alpha': 0.005764103413526787, 'reg_lambda': 0.08574831311259126, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  90%|█████████ | 181/200 [01:29<00:09,  2.05it/s]

[I 2025-11-10 17:45:47,690] Trial 179 finished with value: 0.490925925925926 and parameters: {'max_depth': 6, 'learning_rate': 0.03348284019043059, 'n_estimators': 524, 'subsample': 0.6276892836784639, 'colsample_bytree': 0.6676850901503624, 'min_child_weight': 4, 'gamma': 2.0218166278059497, 'reg_alpha': 0.007304694879864216, 'reg_lambda': 0.06260127452366902, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  91%|█████████ | 182/200 [01:29<00:08,  2.19it/s]

[I 2025-11-10 17:45:48,066] Trial 180 finished with value: 0.495 and parameters: {'max_depth': 6, 'learning_rate': 0.03561486017728317, 'n_estimators': 396, 'subsample': 0.6253299162058996, 'colsample_bytree': 0.7078045844135618, 'min_child_weight': 4, 'gamma': 1.8648410775176005, 'reg_alpha': 0.016241244394039803, 'reg_lambda': 0.012357525181011512, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  92%|█████████▏| 184/200 [01:30<00:05,  2.97it/s]

[I 2025-11-10 17:45:48,390] Trial 182 finished with value: 0.4611111111111111 and parameters: {'max_depth': 6, 'learning_rate': 0.04404080112335115, 'n_estimators': 341, 'subsample': 0.6226304880870608, 'colsample_bytree': 0.7084812415578723, 'min_child_weight': 4, 'gamma': 2.230277530236723, 'reg_alpha': 0.005464282388071289, 'reg_lambda': 0.01531391329670887, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.
[I 2025-11-10 17:45:48,530] Trial 183 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.042790512968010404, 'n_estimators': 338, 'subsample': 0.6160883290750667, 'colsample_bytree': 0.7072344853436348, 'min_child_weight': 9, 'gamma': 2.1914351073302516, 'reg_alpha': 0.01948923496542904, 'reg_lambda': 0.015139448862445186, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  92%|█████████▎| 185/200 [01:31<00:08,  1.79it/s]

[I 2025-11-10 17:45:49,621] Trial 184 finished with value: 0.5409356725146199 and parameters: {'max_depth': 6, 'learning_rate': 0.04372395683924905, 'n_estimators': 394, 'subsample': 0.5974512153506023, 'colsample_bytree': 0.6960136607410535, 'min_child_weight': 4, 'gamma': 2.1335179161201805, 'reg_alpha': 0.013577220225483414, 'reg_lambda': 0.046068329827899365, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  93%|█████████▎| 186/200 [01:31<00:06,  2.20it/s]

[I 2025-11-10 17:45:49,823] Trial 185 finished with value: 0.512046783625731 and parameters: {'max_depth': 6, 'learning_rate': 0.04245361088378008, 'n_estimators': 356, 'subsample': 0.5988135025860348, 'colsample_bytree': 0.6965335037510798, 'min_child_weight': 4, 'gamma': 2.245105615003455, 'reg_alpha': 0.010584538246006652, 'reg_lambda': 0.04605113958889614, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  94%|█████████▍| 188/200 [01:31<00:04,  2.86it/s]

[I 2025-11-10 17:45:50,256] Trial 186 finished with value: 0.512046783625731 and parameters: {'max_depth': 6, 'learning_rate': 0.04250680750092032, 'n_estimators': 379, 'subsample': 0.5979029857265171, 'colsample_bytree': 0.6985295873500678, 'min_child_weight': 4, 'gamma': 2.2091559102150438, 'reg_alpha': 0.012587881933521282, 'reg_lambda': 0.05051754501743414, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.
[I 2025-11-10 17:45:50,380] Trial 187 finished with value: 0.5076023391812866 and parameters: {'max_depth': 6, 'learning_rate': 0.011782260181168026, 'n_estimators': 377, 'subsample': 0.5998885202938318, 'colsample_bytree': 0.6950121723256194, 'min_child_weight': 4, 'gamma': 2.135795541119075, 'reg_alpha': 0.0032047234081880637, 'reg_lambda': 0.05658187470462903, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  94%|█████████▍| 189/200 [01:33<00:07,  1.44it/s]

[I 2025-11-10 17:45:51,877] Trial 188 finished with value: 0.512046783625731 and parameters: {'max_depth': 6, 'learning_rate': 0.0410386496106555, 'n_estimators': 461, 'subsample': 0.6005225382018929, 'colsample_bytree': 0.6927588188913841, 'min_child_weight': 4, 'gamma': 2.1467466625341047, 'reg_alpha': 0.009711155985288242, 'reg_lambda': 0.008579087977085264, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  95%|█████████▌| 190/200 [01:33<00:05,  1.80it/s]

[I 2025-11-10 17:45:52,117] Trial 189 finished with value: 0.512046783625731 and parameters: {'max_depth': 6, 'learning_rate': 0.04037017025435547, 'n_estimators': 466, 'subsample': 0.6001039203001555, 'colsample_bytree': 0.7289276498916301, 'min_child_weight': 4, 'gamma': 2.713937487601348, 'reg_alpha': 0.003485474014922629, 'reg_lambda': 0.008385105721814624, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  96%|█████████▌| 192/200 [01:34<00:03,  2.56it/s]

[I 2025-11-10 17:45:52,422] Trial 190 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05885301018645503, 'n_estimators': 448, 'subsample': 0.5656685214038458, 'colsample_bytree': 0.732183676973458, 'min_child_weight': 4, 'gamma': 2.110712613023791, 'reg_alpha': 0.0028148728777047183, 'reg_lambda': 0.008024333625032451, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.
[I 2025-11-10 17:45:52,599] Trial 191 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.040051430885394756, 'n_estimators': 469, 'subsample': 0.5640790882093241, 'colsample_bytree': 0.725775777929802, 'min_child_weight': 4, 'gamma': 2.0945159080956914, 'reg_alpha': 0.028478241470549, 'reg_lambda': 0.10664074708834156, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  96%|█████████▋| 193/200 [01:35<00:03,  1.84it/s]

[I 2025-11-10 17:45:53,502] Trial 192 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.037567576428245535, 'n_estimators': 325, 'subsample': 0.5869079532206829, 'colsample_bytree': 0.7309845404544135, 'min_child_weight': 4, 'gamma': 2.055966937626162, 'reg_alpha': 0.03267145972379153, 'reg_lambda': 0.023012661944649338, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  97%|█████████▋| 194/200 [01:35<00:02,  2.21it/s]

[I 2025-11-10 17:45:53,739] Trial 193 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04641807892111144, 'n_estimators': 326, 'subsample': 0.5642283414461148, 'colsample_bytree': 0.6757553585823499, 'min_child_weight': 4, 'gamma': 2.0542709606311, 'reg_alpha': 0.03684455937452095, 'reg_lambda': 0.020790549557008927, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  98%|█████████▊| 196/200 [01:35<00:01,  2.89it/s]

[I 2025-11-10 17:45:54,111] Trial 197 pruned.
[I 2025-11-10 17:45:54,269] Trial 194 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.04741622530343616, 'n_estimators': 369, 'subsample': 0.5873157430895547, 'colsample_bytree': 0.7440881530293741, 'min_child_weight': 4, 'gamma': 2.0706679629912186, 'reg_alpha': 0.03272163791638489, 'reg_lambda': 0.021603688287630957, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  98%|█████████▊| 197/200 [01:36<00:00,  3.47it/s]

[I 2025-11-10 17:45:54,419] Trial 195 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.0457733901403297, 'n_estimators': 365, 'subsample': 0.5882043807790573, 'colsample_bytree': 0.7421354519511626, 'min_child_weight': 4, 'gamma': 2.0374261066548316, 'reg_alpha': 0.00950325795392941, 'reg_lambda': 0.02294756066777252, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491:  99%|█████████▉| 198/200 [01:36<00:00,  2.56it/s]

[I 2025-11-10 17:45:55,051] Trial 196 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.046922026956520514, 'n_estimators': 366, 'subsample': 0.5873296184951247, 'colsample_bytree': 0.7140828475278801, 'min_child_weight': 4, 'gamma': 2.2978335819883076, 'reg_alpha': 0.010321549276810352, 'reg_lambda': 0.019830863144632286, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.

Best trial: 94. Best value: 0.586491: 100%|██████████| 200/200 [01:37<00:00,  2.06it/s]

[I 2025-11-10 17:45:55,430] Trial 198 finished with value: 0.5464912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.04520418934319972, 'n_estimators': 377, 'subsample': 0.5892019844623446, 'colsample_bytree': 0.7134753124783106, 'min_child_weight': 4, 'gamma': 2.4895096724713808, 'reg_alpha': 0.0007279100538348345, 'reg_lambda': 0.0237632081401301, 'max_delta_step': 0}. Best is trial 94 with value: 0.5864912280701755.
[I 2025-11-10 17:45:55,559] Trial 199 finished with value: 0.5864912280701755 and parameters: {'max_depth': 6, 'learning_rate': 0.041225835448460244, 'n_estimators': 409, 'subsample': 0.589359668349248, 'colsample_bytree': 0.714171006943661, 'min_child_weight': 4, 'gamma': 1.9176224716022263, 'reg_alpha': 0.010089679185975335, 'reg_lambda': 0.031052157490792525, 'max_delta_step': 1}. Best is trial 94 with value: 0.5864912280701755.

[I 2025-11-10 17:45:56,241] A new study created in memory with name: 16_1_roc_auc
Best trial: 0. Best value: 0.610429:   0%|          | 1/200 [00:01<04:08,  1.25s/it]

[I 2025-11-10 17:45:57,485] Trial 0 finished with value: 0.6104288499025342 and parameters: {'max_depth': 9, 'learning_rate': 0.21878939295449554, 'n_estimators': 272, 'subsample': 0.7413144084408156, 'colsample_bytree': 0.5665004921159088, 'min_child_weight': 4, 'gamma': 3.6336914961885154, 'reg_alpha': 1.654998153704493e-08, 'reg_lambda': 7.667409078962278e-06, 'max_delta_step': 9}. Best is trial 0 with value: 0.6104288499025342.

Best trial: 0. Best value: 0.610429:   1%|          | 2/200 [00:01<02:13,  1.48it/s]

[I 2025-11-10 17:45:57,756] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.01709282748056088, 'n_estimators': 325, 'subsample': 0.8005224161829956, 'colsample_bytree': 0.8758412823558401, 'min_child_weight': 10, 'gamma': 3.7484313804962417, 'reg_alpha': 0.0001777281112122638, 'reg_lambda': 0.057096843237896926, 'max_delta_step': 4}. Best is trial 0 with value: 0.6104288499025342.

Best trial: 0. Best value: 0.610429:   2%|▏         | 3/200 [00:02<02:49,  1.16it/s]

[I 2025-11-10 17:45:58,840] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.18108591044638087, 'n_estimators': 622, 'subsample': 0.7391711696434207, 'colsample_bytree': 0.6225184182967222, 'min_child_weight': 8, 'gamma': 3.3117249928719303, 'reg_alpha': 1.019745216315154, 'reg_lambda': 3.7442843282284895e-05, 'max_delta_step': 9}. Best is trial 0 with value: 0.6104288499025342.

Best trial: 5. Best value: 0.630205:   3%|▎         | 6/200 [00:05<02:19,  1.39it/s]

[I 2025-11-10 17:46:01,182] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.19157962677121368, 'n_estimators': 890, 'subsample': 0.8472901893933822, 'colsample_bytree': 0.8840166987316092, 'min_child_weight': 10, 'gamma': 2.934533878287164, 'reg_alpha': 0.03177482080781149, 'reg_lambda': 9.972847783854223e-05, 'max_delta_step': 9}. Best is trial 0 with value: 0.6104288499025342.
[I 2025-11-10 17:46:01,197] Trial 1 finished with value: 0.5636842105263158 and parameters: {'max_depth': 8, 'learning_rate': 0.01589021994415832, 'n_estimators': 1253, 'subsample': 0.8748368970840044, 'colsample_bytree': 0.5486068276548817, 'min_child_weight': 5, 'gamma': 2.130452590004893, 'reg_alpha': 0.0006650294469779849, 'reg_lambda': 5.689829411043348e-08, 'max_delta_step': 9}. Best is trial 0 with value: 0.6104288499025342.
[I 2025-11-10 17:46:01,337] Trial 5 finished with value: 0.6302046783625732 and parameters: {'max_depth': 3, 'learning_rate': 0.24994209693061142, 'n_estimators': 912, 'subsample': 0.6840967212064853, 'colsample_bytree': 0.6789604841390506, 'min_child_weight': 4, 'gamma': 2.9323045403211516, 'reg_alpha': 0.00044371157632643873, 'reg_lambda': 0.6742402112772286, 'max_delta_step': 10}. Best is trial 5 with value: 0.6302046783625732.

Best trial: 5. Best value: 0.630205:   4%|▎         | 7/200 [00:06<03:08,  1.03it/s]

[I 2025-11-10 17:46:02,982] Trial 9 finished with value: 0.6012280701754384 and parameters: {'max_depth': 9, 'learning_rate': 0.025870364996654106, 'n_estimators': 405, 'subsample': 0.5115037932799784, 'colsample_bytree': 0.5497546310467929, 'min_child_weight': 3, 'gamma': 4.86988414300186, 'reg_alpha': 0.00042765008186971474, 'reg_lambda': 0.004715480903895574, 'max_delta_step': 4}. Best is trial 5 with value: 0.6302046783625732.

Best trial: 5. Best value: 0.630205:   4%|▍         | 8/200 [00:08<03:32,  1.10s/it]

[I 2025-11-10 17:46:04,421] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.058356511545328726, 'n_estimators': 862, 'subsample': 0.9111371515395983, 'colsample_bytree': 0.6709363095621655, 'min_child_weight': 8, 'gamma': 1.0328065556048376, 'reg_alpha': 3.310277601953742e-06, 'reg_lambda': 2.185084585809917e-08, 'max_delta_step': 4}. Best is trial 5 with value: 0.6302046783625732.

Best trial: 5. Best value: 0.630205:   4%|▍         | 9/200 [00:09<03:57,  1.24s/it]

[I 2025-11-10 17:46:05,996] Trial 7 finished with value: 0.6293567251461988 and parameters: {'max_depth': 8, 'learning_rate': 0.01880472960684083, 'n_estimators': 1267, 'subsample': 0.6181621426533144, 'colsample_bytree': 0.8280074983933776, 'min_child_weight': 4, 'gamma': 0.6205099488114751, 'reg_alpha': 2.9050965471820934e-05, 'reg_lambda': 1.0142759247850393, 'max_delta_step': 6}. Best is trial 5 with value: 0.6302046783625732.

Best trial: 5. Best value: 0.630205:   5%|▌         | 10/200 [00:10<03:18,  1.04s/it]

[I 2025-11-10 17:46:06,561] Trial 6 finished with value: 0.5193177387914231 and parameters: {'max_depth': 3, 'learning_rate': 0.054487572715476204, 'n_estimators': 1333, 'subsample': 0.9784811016308543, 'colsample_bytree': 0.6474292290191858, 'min_child_weight': 1, 'gamma': 2.8092881249700685, 'reg_alpha': 0.0003393125292680087, 'reg_lambda': 0.00970326666084246, 'max_delta_step': 7}. Best is trial 5 with value: 0.6302046783625732.

Best trial: 5. Best value: 0.630205:   6%|▌         | 11/200 [00:10<02:35,  1.22it/s]

[I 2025-11-10 17:46:06,846] Trial 12 pruned.

Best trial: 5. Best value: 0.630205:   6%|▌         | 12/200 [00:11<02:15,  1.38it/s]

[I 2025-11-10 17:46:07,335] Trial 11 pruned.

Best trial: 5. Best value: 0.630205:   6%|▋         | 13/200 [00:12<02:36,  1.19it/s]

[I 2025-11-10 17:46:08,444] Trial 10 finished with value: 0.5350682261208577 and parameters: {'max_depth': 9, 'learning_rate': 0.0270632017443345, 'n_estimators': 636, 'subsample': 0.977665973836248, 'colsample_bytree': 0.7971357787859952, 'min_child_weight': 1, 'gamma': 0.41753289229192414, 'reg_alpha': 0.00039322264157601154, 'reg_lambda': 0.00048296627951829727, 'max_delta_step': 10}. Best is trial 5 with value: 0.6302046783625732.

Best trial: 5. Best value: 0.630205:   7%|▋         | 14/200 [00:12<02:24,  1.29it/s]

[I 2025-11-10 17:46:09,076] Trial 15 pruned.

Best trial: 5. Best value: 0.630205:   8%|▊         | 15/200 [00:16<05:24,  1.75s/it]

[I 2025-11-10 17:46:13,121] Trial 17 finished with value: 0.580458089668616 and parameters: {'max_depth': 5, 'learning_rate': 0.01035159087472233, 'n_estimators': 1031, 'subsample': 0.6375595921499455, 'colsample_bytree': 0.9797482058705529, 'min_child_weight': 4, 'gamma': 1.7869485433694796, 'reg_alpha': 0.0691306304290204, 'reg_lambda': 5.608722992417949, 'max_delta_step': 1}. Best is trial 5 with value: 0.6302046783625732.
[I 2025-11-10 17:46:13,127] Trial 16 finished with value: 0.6275438596491227 and parameters: {'max_depth': 4, 'learning_rate': 0.011050759962424654, 'n_estimators': 1066, 'subsample': 0.6258800605813378, 'colsample_bytree': 0.7715659055347243, 'min_child_weight': 3, 'gamma': 1.8713320680253394, 'reg_alpha': 1.3663719829215667e-06, 'reg_lambda': 9.152967632954221, 'max_delta_step': 6}. Best is trial 5 with value: 0.6302046783625732.

Best trial: 5. Best value: 0.630205:   8%|▊         | 17/200 [00:17<03:13,  1.06s/it]

[I 2025-11-10 17:46:13,604] Trial 13 finished with value: 0.561364522417154 and parameters: {'max_depth': 4, 'learning_rate': 0.07964179815997192, 'n_estimators': 1010, 'subsample': 0.6420314015052815, 'colsample_bytree': 0.9811704684420423, 'min_child_weight': 1, 'gamma': 1.6383847951046029, 'reg_alpha': 2.5098075423105775e-07, 'reg_lambda': 6.8006350080671965, 'max_delta_step': 0}. Best is trial 5 with value: 0.6302046783625732.

Best trial: 5. Best value: 0.630205:   9%|▉         | 18/200 [00:18<02:57,  1.03it/s]

[I 2025-11-10 17:46:14,327] Trial 19 pruned.
[I 2025-11-10 17:46:14,342] Trial 18 pruned.

Best trial: 5. Best value: 0.630205:  11%|█         | 22/200 [00:18<01:20,  2.21it/s]

[I 2025-11-10 17:46:14,800] Trial 14 finished with value: 0.5658089668615984 and parameters: {'max_depth': 5, 'learning_rate': 0.01080447755692382, 'n_estimators': 1035, 'subsample': 0.612734979333009, 'colsample_bytree': 0.7619782754087066, 'min_child_weight': 2, 'gamma': 0.3549712737414672, 'reg_alpha': 3.681601724148853e-06, 'reg_lambda': 8.485564091043285, 'max_delta_step': 6}. Best is trial 5 with value: 0.6302046783625732.
[I 2025-11-10 17:46:14,821] Trial 20 pruned.
[I 2025-11-10 17:46:14,972] Trial 21 pruned.

Best trial: 5. Best value: 0.630205:  12%|█▏        | 23/200 [00:18<01:10,  2.52it/s]

[I 2025-11-10 17:46:15,157] Trial 22 pruned.

Best trial: 5. Best value: 0.630205:  12%|█▏        | 24/200 [00:19<01:06,  2.67it/s]

[I 2025-11-10 17:46:15,463] Trial 23 pruned.

Best trial: 5. Best value: 0.630205:  12%|█▎        | 25/200 [00:19<01:01,  2.85it/s]

[I 2025-11-10 17:46:15,739] Trial 24 pruned.

Best trial: 5. Best value: 0.630205:  13%|█▎        | 26/200 [00:20<01:14,  2.33it/s]

[I 2025-11-10 17:46:16,390] Trial 25 pruned.

Best trial: 5. Best value: 0.630205:  14%|█▎        | 27/200 [00:20<01:16,  2.26it/s]

[I 2025-11-10 17:46:16,865] Trial 28 pruned.

Best trial: 5. Best value: 0.630205:  14%|█▍        | 28/200 [00:20<01:10,  2.42it/s]

[I 2025-11-10 17:46:17,202] Trial 29 pruned.

Best trial: 5. Best value: 0.630205:  14%|█▍        | 29/200 [00:21<01:18,  2.19it/s]

[I 2025-11-10 17:46:17,773] Trial 30 pruned.

Best trial: 5. Best value: 0.630205:  15%|█▌        | 30/200 [00:24<03:40,  1.29s/it]

[I 2025-11-10 17:46:21,122] Trial 26 finished with value: 0.6270760233918129 and parameters: {'max_depth': 4, 'learning_rate': 0.016554629545151005, 'n_estimators': 1295, 'subsample': 0.6850147719761309, 'colsample_bytree': 0.9328097082923051, 'min_child_weight': 4, 'gamma': 1.6989902359122167, 'reg_alpha': 2.25044142985269e-07, 'reg_lambda': 1.837037607450989, 'max_delta_step': 6}. Best is trial 5 with value: 0.6302046783625732.
[I 2025-11-10 17:46:21,140] Trial 27 finished with value: 0.612729044834308 and parameters: {'max_depth': 4, 'learning_rate': 0.01631163364514617, 'n_estimators': 1280, 'subsample': 0.6627761198550707, 'colsample_bytree': 0.9241927588845592, 'min_child_weight': 4, 'gamma': 1.686440775484507, 'reg_alpha': 1.1559745691238388e-07, 'reg_lambda': 1.384163717879419, 'max_delta_step': 5}. Best is trial 5 with value: 0.6302046783625732.

Best trial: 31. Best value: 0.639942:  16%|█▋        | 33/200 [00:26<02:02,  1.36it/s]

[I 2025-11-10 17:46:22,134] Trial 33 pruned.
[I 2025-11-10 17:46:22,240] Trial 31 finished with value: 0.6399415204678363 and parameters: {'max_depth': 5, 'learning_rate': 0.012505767756270306, 'n_estimators': 1174, 'subsample': 0.6199188654947126, 'colsample_bytree': 0.8091732949030993, 'min_child_weight': 4, 'gamma': 4.521551186099533, 'reg_alpha': 0.0024047316350382427, 'reg_lambda': 0.05099455877855913, 'max_delta_step': 10}. Best is trial 31 with value: 0.6399415204678363.
[I 2025-11-10 17:46:22,270] Trial 34 pruned.

Best trial: 31. Best value: 0.639942:  18%|█▊        | 35/200 [00:26<01:24,  1.95it/s]

[I 2025-11-10 17:46:22,629] Trial 32 finished with value: 0.6326315789473684 and parameters: {'max_depth': 7, 'learning_rate': 0.012745923744113355, 'n_estimators': 1163, 'subsample': 0.6048835983496995, 'colsample_bytree': 0.5957544997069912, 'min_child_weight': 4, 'gamma': 4.157040731925842, 'reg_alpha': 2.050503191281387e-08, 'reg_lambda': 9.675868088102576e-07, 'max_delta_step': 10}. Best is trial 31 with value: 0.6399415204678363.

Best trial: 31. Best value: 0.639942:  18%|█▊        | 36/200 [00:26<01:21,  2.01it/s]

[I 2025-11-10 17:46:23,072] Trial 37 pruned.

Best trial: 31. Best value: 0.639942:  18%|█▊        | 37/200 [00:27<01:10,  2.33it/s]

[I 2025-11-10 17:46:23,295] Trial 36 pruned.

Best trial: 31. Best value: 0.639942:  19%|█▉        | 38/200 [00:27<01:05,  2.46it/s]

[I 2025-11-10 17:46:23,637] Trial 38 pruned.

Best trial: 31. Best value: 0.639942:  20%|█▉        | 39/200 [00:27<01:07,  2.37it/s]

[I 2025-11-10 17:46:24,098] Trial 39 pruned.

Best trial: 31. Best value: 0.639942:  20%|██        | 40/200 [00:28<01:00,  2.65it/s]

[I 2025-11-10 17:46:24,358] Trial 40 pruned.

Best trial: 31. Best value: 0.639942:  20%|██        | 41/200 [00:28<01:02,  2.56it/s]

[I 2025-11-10 17:46:24,785] Trial 41 pruned.

Best trial: 31. Best value: 0.639942:  21%|██        | 42/200 [00:29<01:13,  2.15it/s]

[I 2025-11-10 17:46:25,430] Trial 42 pruned.

Best trial: 31. Best value: 0.639942:  22%|██▏       | 43/200 [00:31<02:27,  1.06it/s]

[I 2025-11-10 17:46:27,530] Trial 35 finished with value: 0.6310526315789474 and parameters: {'max_depth': 5, 'learning_rate': 0.012469069026981241, 'n_estimators': 1180, 'subsample': 0.6143957355281489, 'colsample_bytree': 0.9286781894158602, 'min_child_weight': 4, 'gamma': 2.0624888103089956, 'reg_alpha': 0.0021935280376152813, 'reg_lambda': 2.91058659734172, 'max_delta_step': 6}. Best is trial 31 with value: 0.6399415204678363.

Best trial: 31. Best value: 0.639942:  22%|██▏       | 44/200 [00:32<02:30,  1.03it/s]

[I 2025-11-10 17:46:28,557] Trial 46 pruned.

Best trial: 31. Best value: 0.639942:  23%|██▎       | 46/200 [00:33<01:52,  1.37it/s]

[I 2025-11-10 17:46:29,602] Trial 44 finished with value: 0.5863157894736842 and parameters: {'max_depth': 7, 'learning_rate': 0.010679113560612082, 'n_estimators': 1071, 'subsample': 0.6252363375237807, 'colsample_bytree': 0.6903049015995093, 'min_child_weight': 3, 'gamma': 4.032241705025097, 'reg_alpha': 0.00010342654112064258, 'reg_lambda': 1.894446062924686e-05, 'max_delta_step': 9}. Best is trial 31 with value: 0.6399415204678363.
[I 2025-11-10 17:46:29,718] Trial 47 pruned.

Best trial: 31. Best value: 0.639942:  24%|██▍       | 49/200 [00:34<01:05,  2.30it/s]

[I 2025-11-10 17:46:30,491] Trial 45 finished with value: 0.5882846003898635 and parameters: {'max_depth': 7, 'learning_rate': 0.011476084771512659, 'n_estimators': 1107, 'subsample': 0.6244043035127673, 'colsample_bytree': 0.6841493461839814, 'min_child_weight': 3, 'gamma': 4.421324442274029, 'reg_alpha': 1.0674830840388464e-08, 'reg_lambda': 1.1472624004899178e-08, 'max_delta_step': 9}. Best is trial 31 with value: 0.6399415204678363.
[I 2025-11-10 17:46:30,499] Trial 48 pruned.
[I 2025-11-10 17:46:30,639] Trial 49 pruned.

Best trial: 31. Best value: 0.639942:  26%|██▌       | 52/200 [00:35<00:55,  2.67it/s]

[I 2025-11-10 17:46:31,685] Trial 43 finished with value: 0.5792982456140352 and parameters: {'max_depth': 6, 'learning_rate': 0.03574854569591888, 'n_estimators': 1388, 'subsample': 0.7379448353914692, 'colsample_bytree': 0.6825453847545233, 'min_child_weight': 2, 'gamma': 4.203095035015201, 'reg_alpha': 3.354629356500267, 'reg_lambda': 1.9771331773085263e-05, 'max_delta_step': 9}. Best is trial 31 with value: 0.6399415204678363.
[I 2025-11-10 17:46:31,731] Trial 50 pruned.
[I 2025-11-10 17:46:31,837] Trial 51 pruned.

Best trial: 31. Best value: 0.639942:  26%|██▋       | 53/200 [00:35<00:46,  3.15it/s]

[I 2025-11-10 17:46:31,961] Trial 52 pruned.

Best trial: 31. Best value: 0.639942:  27%|██▋       | 54/200 [00:36<00:55,  2.64it/s]

[I 2025-11-10 17:46:32,525] Trial 53 pruned.
[I 2025-11-10 17:46:32,541] Trial 54 pruned.

Best trial: 31. Best value: 0.639942:  28%|██▊       | 57/200 [00:36<00:35,  4.04it/s]

[I 2025-11-10 17:46:32,816] Trial 56 pruned.
[I 2025-11-10 17:46:32,945] Trial 55 pruned.

Best trial: 31. Best value: 0.639942:  30%|██▉       | 59/200 [00:37<00:39,  3.55it/s]

[I 2025-11-10 17:46:33,540] Trial 58 pruned.
[I 2025-11-10 17:46:33,676] Trial 57 finished with value: 0.5990545808966862 and parameters: {'max_depth': 3, 'learning_rate': 0.018301294544934437, 'n_estimators': 213, 'subsample': 0.6326782622672398, 'colsample_bytree': 0.7697263044028332, 'min_child_weight': 4, 'gamma': 2.077247417504535, 'reg_alpha': 0.0002528358888220858, 'reg_lambda': 4.112751367418462, 'max_delta_step': 7}. Best is trial 31 with value: 0.6399415204678363.

Best trial: 31. Best value: 0.639942:  30%|███       | 60/200 [00:37<00:36,  3.78it/s]

[I 2025-11-10 17:46:33,897] Trial 59 pruned.
[I 2025-11-10 17:46:33,915] Trial 60 pruned.

Best trial: 31. Best value: 0.639942:  31%|███       | 62/200 [00:38<00:46,  2.99it/s]

[I 2025-11-10 17:46:34,745] Trial 61 pruned.

Best trial: 31. Best value: 0.639942:  32%|███▏      | 63/200 [00:38<00:42,  3.25it/s]

[I 2025-11-10 17:46:34,968] Trial 62 pruned.

Best trial: 31. Best value: 0.639942:  32%|███▏      | 64/200 [00:39<00:43,  3.15it/s]

[I 2025-11-10 17:46:35,311] Trial 63 pruned.

Best trial: 31. Best value: 0.639942:  32%|███▎      | 65/200 [00:39<00:38,  3.50it/s]

[I 2025-11-10 17:46:35,510] Trial 64 pruned.

Best trial: 31. Best value: 0.639942:  34%|███▎      | 67/200 [00:44<02:39,  1.20s/it]

[I 2025-11-10 17:46:40,651] Trial 66 finished with value: 0.6263157894736842 and parameters: {'max_depth': 4, 'learning_rate': 0.0150470462519555, 'n_estimators': 1333, 'subsample': 0.6173324544954216, 'colsample_bytree': 0.9924156145437072, 'min_child_weight': 4, 'gamma': 1.3889005853123062, 'reg_alpha': 3.1136422182881995e-07, 'reg_lambda': 8.54181593247277, 'max_delta_step': 6}. Best is trial 31 with value: 0.6399415204678363.
[I 2025-11-10 17:46:40,784] Trial 68 finished with value: 0.6060233918128655 and parameters: {'max_depth': 4, 'learning_rate': 0.015772774845417677, 'n_estimators': 1238, 'subsample': 0.6158583783164286, 'colsample_bytree': 0.9508314518382428, 'min_child_weight': 4, 'gamma': 1.2330480398496015, 'reg_alpha': 4.580548761701424e-07, 'reg_lambda': 1.7239690376655241, 'max_delta_step': 6}. Best is trial 31 with value: 0.6399415204678363.
[I 2025-11-10 17:46:40,813] Trial 65 finished with value: 0.621150097465887 and parameters: {'max_depth': 4, 'learning_rate': 0.011520281450405666, 'n_estimators': 1324, 'subsample': 0.6871654991089859, 'colsample_bytree': 0.9557333292271674, 'min_child_weight': 4, 'gamma': 1.2717476539009547, 'reg_alpha': 3.2252060411597774e-07, 'reg_lambda': 9.423642094684627, 'max_delta_step': 6}. Best is trial 31 with value: 0.6399415204678363.

Best trial: 31. Best value: 0.639942:  34%|███▍      | 69/200 [00:45<01:46,  1.23it/s]

[I 2025-11-10 17:46:41,456] Trial 67 finished with value: 0.6230019493177388 and parameters: {'max_depth': 4, 'learning_rate': 0.014731366477163303, 'n_estimators': 1333, 'subsample': 0.6808113664084393, 'colsample_bytree': 0.9572232304784288, 'min_child_weight': 4, 'gamma': 1.2965748108218964, 'reg_alpha': 5.392023600612806e-08, 'reg_lambda': 1.8431277907530432, 'max_delta_step': 6}. Best is trial 31 with value: 0.6399415204678363.

Best trial: 31. Best value: 0.639942:  36%|███▌      | 71/200 [00:45<01:33,  1.38it/s]

[I 2025-11-10 17:46:41,891] Trial 71 pruned.
[I 2025-11-10 17:46:41,917] Trial 70 pruned.
[I 2025-11-10 17:46:41,925] Trial 69 pruned.

Best trial: 31. Best value: 0.639942:  36%|███▋      | 73/200 [00:46<01:00,  2.08it/s]

[I 2025-11-10 17:46:42,629] Trial 72 pruned.

Best trial: 31. Best value: 0.639942:  37%|███▋      | 74/200 [00:46<00:56,  2.24it/s]

[I 2025-11-10 17:46:42,933] Trial 73 pruned.

Best trial: 31. Best value: 0.639942:  38%|███▊      | 75/200 [00:46<00:48,  2.55it/s]

[I 2025-11-10 17:46:43,129] Trial 74 pruned.

Best trial: 31. Best value: 0.639942:  38%|███▊      | 76/200 [00:47<00:52,  2.34it/s]

[I 2025-11-10 17:46:43,669] Trial 75 pruned.

Best trial: 31. Best value: 0.639942:  38%|███▊      | 77/200 [00:48<00:55,  2.21it/s]

[I 2025-11-10 17:46:44,196] Trial 76 pruned.
[I 2025-11-10 17:46:44,240] Trial 78 pruned.

Best trial: 31. Best value: 0.639942:  40%|███▉      | 79/200 [00:48<00:46,  2.59it/s]

[I 2025-11-10 17:46:44,788] Trial 77 pruned.

Best trial: 31. Best value: 0.639942:  40%|████      | 80/200 [00:49<00:57,  2.09it/s]

[I 2025-11-10 17:46:45,570] Trial 80 pruned.

Best trial: 31. Best value: 0.639942:  40%|████      | 81/200 [00:49<00:53,  2.24it/s]

[I 2025-11-10 17:46:45,922] Trial 82 pruned.

Best trial: 31. Best value: 0.639942:  41%|████      | 82/200 [00:50<00:49,  2.40it/s]

[I 2025-11-10 17:46:46,257] Trial 81 pruned.

Best trial: 31. Best value: 0.639942:  42%|████▏     | 83/200 [00:50<00:45,  2.55it/s]

[I 2025-11-10 17:46:46,582] Trial 83 pruned.

Best trial: 31. Best value: 0.639942:  42%|████▏     | 84/200 [00:51<01:12,  1.59it/s]

[I 2025-11-10 17:46:47,822] Trial 79 finished with value: 0.5763157894736841 and parameters: {'max_depth': 5, 'learning_rate': 0.010113011989938317, 'n_estimators': 956, 'subsample': 0.5946114000228151, 'colsample_bytree': 0.9732549609337287, 'min_child_weight': 4, 'gamma': 1.5466998149342392, 'reg_alpha': 2.110729842331134e-07, 'reg_lambda': 2.822010202350877, 'max_delta_step': 6}. Best is trial 31 with value: 0.6399415204678363.

Best trial: 31. Best value: 0.639942:  42%|████▎     | 85/200 [00:52<01:28,  1.29it/s]

[I 2025-11-10 17:46:48,953] Trial 87 pruned.

Best trial: 31. Best value: 0.639942:  43%|████▎     | 86/200 [00:55<02:43,  1.43s/it]

[I 2025-11-10 17:46:52,000] Trial 84 finished with value: 0.6190448343079922 and parameters: {'max_depth': 4, 'learning_rate': 0.015163641385449721, 'n_estimators': 1355, 'subsample': 0.6766893436561815, 'colsample_bytree': 0.9757077005320309, 'min_child_weight': 4, 'gamma': 1.680774319295097, 'reg_alpha': 6.270289651409972e-08, 'reg_lambda': 9.383666747674263e-05, 'max_delta_step': 6}. Best is trial 31 with value: 0.6399415204678363.
[I 2025-11-10 17:46:52,034] Trial 85 finished with value: 0.6053411306042885 and parameters: {'max_depth': 4, 'learning_rate': 0.015247449284092735, 'n_estimators': 1346, 'subsample': 0.6817293775113532, 'colsample_bytree': 0.847261787791599, 'min_child_weight': 4, 'gamma': 2.361450095782913, 'reg_alpha': 1.5754946750635847e-08, 'reg_lambda': 7.073618237294004e-05, 'max_delta_step': 6}. Best is trial 31 with value: 0.6399415204678363.

Best trial: 31. Best value: 0.639942:  44%|████▍     | 88/200 [00:56<01:44,  1.07it/s]

[I 2025-11-10 17:46:52,680] Trial 86 finished with value: 0.6352241715399609 and parameters: {'max_depth': 4, 'learning_rate': 0.014587804855826742, 'n_estimators': 1350, 'subsample': 0.6832686807723531, 'colsample_bytree': 0.8842871879231764, 'min_child_weight': 4, 'gamma': 3.819824617551001, 'reg_alpha': 1.7481047498703844e-08, 'reg_lambda': 0.4619994170865557, 'max_delta_step': 6}. Best is trial 31 with value: 0.6399415204678363.

Best trial: 31. Best value: 0.639942:  45%|████▌     | 90/200 [00:57<01:10,  1.57it/s]

[I 2025-11-10 17:46:53,134] Trial 90 pruned.
[I 2025-11-10 17:46:53,256] Trial 89 pruned.

Best trial: 31. Best value: 0.639942:  46%|████▌     | 91/200 [00:57<01:04,  1.68it/s]

[I 2025-11-10 17:46:53,726] Trial 91 pruned.

Best trial: 31. Best value: 0.639942:  46%|████▌     | 92/200 [00:57<00:59,  1.81it/s]

[I 2025-11-10 17:46:54,174] Trial 92 pruned.

Best trial: 31. Best value: 0.639942:  46%|████▋     | 93/200 [00:58<00:55,  1.93it/s]

[I 2025-11-10 17:46:54,606] Trial 93 pruned.

Best trial: 31. Best value: 0.639942:  47%|████▋     | 94/200 [00:58<00:50,  2.11it/s]

[I 2025-11-10 17:46:54,965] Trial 94 pruned.
[I 2025-11-10 17:46:54,973] Trial 88 finished with value: 0.6305458089668617 and parameters: {'max_depth': 4, 'learning_rate': 0.012300720601781069, 'n_estimators': 1306, 'subsample': 0.6738967083542731, 'colsample_bytree': 0.8848450621288007, 'min_child_weight': 4, 'gamma': 2.364037448900548, 'reg_alpha': 4.5596324877104256e-08, 'reg_lambda': 0.5380038202080935, 'max_delta_step': 6}. Best is trial 31 with value: 0.6399415204678363.

Best trial: 31. Best value: 0.639942:  48%|████▊     | 96/200 [00:59<00:40,  2.57it/s]

[I 2025-11-10 17:46:55,545] Trial 95 pruned.

Best trial: 31. Best value: 0.639942:  48%|████▊     | 97/200 [00:59<00:41,  2.48it/s]

[I 2025-11-10 17:46:55,992] Trial 96 pruned.
[I 2025-11-10 17:46:56,162] Trial 98 pruned.

Best trial: 31. Best value: 0.639942:  50%|████▉     | 99/200 [01:00<00:28,  3.55it/s]

[I 2025-11-10 17:46:56,279] Trial 97 pruned.

Best trial: 31. Best value: 0.639942:  50%|█████     | 100/200 [01:00<00:39,  2.50it/s]

[I 2025-11-10 17:46:56,986] Trial 99 pruned.

Best trial: 31. Best value: 0.639942:  50%|█████     | 101/200 [01:01<00:41,  2.41it/s]

[I 2025-11-10 17:46:57,442] Trial 100 pruned.
[I 2025-11-10 17:46:57,464] Trial 101 pruned.

Best trial: 31. Best value: 0.639942:  52%|█████▏    | 103/200 [01:01<00:27,  3.48it/s]

[I 2025-11-10 17:46:57,701] Trial 102 pruned.

Best trial: 31. Best value: 0.639942:  52%|█████▏    | 104/200 [01:02<00:35,  2.74it/s]

[I 2025-11-10 17:46:58,306] Trial 103 pruned.

Best trial: 31. Best value: 0.639942:  52%|█████▎    | 105/200 [01:02<00:35,  2.68it/s]

[I 2025-11-10 17:46:58,702] Trial 104 pruned.
[I 2025-11-10 17:46:58,785] Trial 105 pruned.

Best trial: 31. Best value: 0.639942:  54%|█████▎    | 107/200 [01:03<00:38,  2.39it/s]

[I 2025-11-10 17:46:59,662] Trial 107 pruned.

Best trial: 31. Best value: 0.639942:  54%|█████▍    | 108/200 [01:03<00:33,  2.73it/s]

[I 2025-11-10 17:46:59,858] Trial 109 pruned.

Best trial: 31. Best value: 0.639942:  55%|█████▍    | 109/200 [01:03<00:30,  2.96it/s]

[I 2025-11-10 17:47:00,111] Trial 108 pruned.

Best trial: 31. Best value: 0.639942:  55%|█████▌    | 110/200 [01:04<00:27,  3.25it/s]

[I 2025-11-10 17:47:00,333] Trial 111 pruned.

Best trial: 31. Best value: 0.639942:  56%|█████▌    | 112/200 [01:04<00:23,  3.82it/s]

[I 2025-11-10 17:47:00,640] Trial 112 pruned.
[I 2025-11-10 17:47:00,786] Trial 110 pruned.

Best trial: 31. Best value: 0.639942:  56%|█████▋    | 113/200 [01:05<00:40,  2.16it/s]

[I 2025-11-10 17:47:01,746] Trial 113 pruned.

Best trial: 31. Best value: 0.639942:  57%|█████▋    | 114/200 [01:05<00:32,  2.61it/s]

[I 2025-11-10 17:47:01,936] Trial 114 pruned.

Best trial: 31. Best value: 0.639942:  57%|█████▊    | 115/200 [01:05<00:29,  2.83it/s]

[I 2025-11-10 17:47:02,215] Trial 115 pruned.

Best trial: 31. Best value: 0.639942:  58%|█████▊    | 117/200 [01:06<00:33,  2.50it/s]

[I 2025-11-10 17:47:03,069] Trial 116 pruned.
[I 2025-11-10 17:47:03,233] Trial 117 pruned.

Best trial: 31. Best value: 0.639942:  60%|█████▉    | 119/200 [01:07<00:19,  4.13it/s]

[I 2025-11-10 17:47:03,271] Trial 118 pruned.
[I 2025-11-10 17:47:03,337] Trial 106 finished with value: 0.5747368421052632 and parameters: {'max_depth': 4, 'learning_rate': 0.014049846986280659, 'n_estimators': 1220, 'subsample': 0.5854126060360629, 'colsample_bytree': 0.9193542393760543, 'min_child_weight': 4, 'gamma': 2.6779006540736554, 'reg_alpha': 5.5177040716894347e-08, 'reg_lambda': 1.9423353317533205, 'max_delta_step': 6}. Best is trial 31 with value: 0.6399415204678363.

Best trial: 31. Best value: 0.639942:  60%|██████    | 120/200 [01:08<00:33,  2.39it/s]

[I 2025-11-10 17:47:04,302] Trial 119 pruned.
[I 2025-11-10 17:47:04,354] Trial 120 pruned.

Best trial: 31. Best value: 0.639942:  61%|██████    | 122/200 [01:08<00:22,  3.49it/s]

[I 2025-11-10 17:47:04,499] Trial 121 pruned.

Best trial: 31. Best value: 0.639942:  62%|██████▏   | 123/200 [01:08<00:24,  3.10it/s]

[I 2025-11-10 17:47:04,940] Trial 122 pruned.

Best trial: 31. Best value: 0.639942:  62%|██████▏   | 124/200 [01:09<00:29,  2.62it/s]

[I 2025-11-10 17:47:05,505] Trial 123 pruned.

Best trial: 31. Best value: 0.639942:  62%|██████▎   | 125/200 [01:09<00:32,  2.34it/s]

[I 2025-11-10 17:47:06,065] Trial 124 pruned.
[I 2025-11-10 17:47:06,143] Trial 125 pruned.

Best trial: 31. Best value: 0.639942:  64%|██████▎   | 127/200 [01:11<00:36,  2.00it/s]

[I 2025-11-10 17:47:07,259] Trial 128 pruned.
[I 2025-11-10 17:47:07,346] Trial 129 pruned.

Best trial: 31. Best value: 0.639942:  64%|██████▍   | 129/200 [01:12<00:38,  1.82it/s]

[I 2025-11-10 17:47:08,520] Trial 131 pruned.

Best trial: 31. Best value: 0.639942:  65%|██████▌   | 130/200 [01:12<00:33,  2.06it/s]

[I 2025-11-10 17:47:08,767] Trial 130 pruned.

Best trial: 31. Best value: 0.639942:  66%|██████▌   | 131/200 [01:13<00:40,  1.70it/s]

[I 2025-11-10 17:47:09,695] Trial 132 pruned.

Best trial: 31. Best value: 0.639942:  66%|██████▌   | 132/200 [01:13<00:35,  1.90it/s]

[I 2025-11-10 17:47:10,038] Trial 133 pruned.

Best trial: 31. Best value: 0.639942:  66%|██████▋   | 133/200 [01:14<00:46,  1.44it/s]

[I 2025-11-10 17:47:11,197] Trial 135 pruned.

Best trial: 31. Best value: 0.639942:  67%|██████▋   | 134/200 [01:15<00:37,  1.74it/s]

[I 2025-11-10 17:47:11,451] Trial 126 finished with value: 0.6037426900584795 and parameters: {'max_depth': 4, 'learning_rate': 0.015185059210689763, 'n_estimators': 1441, 'subsample': 0.678696563203647, 'colsample_bytree': 0.6008098208924713, 'min_child_weight': 4, 'gamma': 1.4853507689479502, 'reg_alpha': 1.1343391968012065e-06, 'reg_lambda': 1.6580775837930636e-06, 'max_delta_step': 6}. Best is trial 31 with value: 0.6399415204678363.

Best trial: 31. Best value: 0.639942:  68%|██████▊   | 135/200 [01:15<00:35,  1.83it/s]

[I 2025-11-10 17:47:11,932] Trial 127 finished with value: 0.6183235867446394 and parameters: {'max_depth': 4, 'learning_rate': 0.014960564764255791, 'n_estimators': 1350, 'subsample': 0.678628795241626, 'colsample_bytree': 0.9295083809559826, 'min_child_weight': 4, 'gamma': 1.9237483346088116, 'reg_alpha': 6.464902510162898e-08, 'reg_lambda': 0.00013327679552860134, 'max_delta_step': 6}. Best is trial 31 with value: 0.6399415204678363.
[I 2025-11-10 17:47:11,956] Trial 136 pruned.

Best trial: 31. Best value: 0.639942:  68%|██████▊   | 137/200 [01:16<00:31,  2.00it/s]

[I 2025-11-10 17:47:12,816] Trial 137 pruned.

Best trial: 31. Best value: 0.639942:  69%|██████▉   | 138/200 [01:17<00:30,  2.07it/s]

[I 2025-11-10 17:47:13,249] Trial 139 pruned.

Best trial: 31. Best value: 0.639942:  70%|██████▉   | 139/200 [01:17<00:28,  2.11it/s]

[I 2025-11-10 17:47:13,690] Trial 140 pruned.

Best trial: 31. Best value: 0.639942:  70%|███████   | 140/200 [01:18<00:30,  1.97it/s]

[I 2025-11-10 17:47:14,289] Trial 141 pruned.

Best trial: 31. Best value: 0.639942:  70%|███████   | 141/200 [01:18<00:34,  1.69it/s]

[I 2025-11-10 17:47:15,099] Trial 142 pruned.

Best trial: 134. Best value: 0.640409:  71%|███████   | 142/200 [01:19<00:27,  2.08it/s]

[I 2025-11-10 17:47:15,303] Trial 143 pruned.
[I 2025-11-10 17:47:15,323] Trial 134 finished with value: 0.6404093567251462 and parameters: {'max_depth': 4, 'learning_rate': 0.016519888262393645, 'n_estimators': 1338, 'subsample': 0.6499812588981926, 'colsample_bytree': 0.6023104498834648, 'min_child_weight': 4, 'gamma': 3.525895674364148, 'reg_alpha': 1.2648466164277897e-07, 'reg_lambda': 0.8322733804439549, 'max_delta_step': 5}. Best is trial 134 with value: 0.6404093567251462.

Best trial: 134. Best value: 0.640409:  72%|███████▎  | 145/200 [01:20<00:23,  2.33it/s]

[I 2025-11-10 17:47:16,433] Trial 144 pruned.
[I 2025-11-10 17:47:16,580] Trial 145 pruned.

Best trial: 134. Best value: 0.640409:  73%|███████▎  | 146/200 [01:21<00:35,  1.54it/s]

[I 2025-11-10 17:47:17,877] Trial 148 pruned.

Best trial: 134. Best value: 0.640409:  74%|███████▎  | 147/200 [01:22<00:38,  1.39it/s]

[I 2025-11-10 17:47:18,784] Trial 138 finished with value: 0.6141130604288498 and parameters: {'max_depth': 4, 'learning_rate': 0.011268878151845362, 'n_estimators': 1394, 'subsample': 0.6853836995394692, 'colsample_bytree': 0.9649993975293956, 'min_child_weight': 4, 'gamma': 1.8107624000895337, 'reg_alpha': 1.6339189492367552e-08, 'reg_lambda': 2.5399789077401995e-08, 'max_delta_step': 6}. Best is trial 134 with value: 0.6404093567251462.

Best trial: 134. Best value: 0.640409:  74%|███████▍  | 148/200 [01:23<00:43,  1.19it/s]

[I 2025-11-10 17:47:19,940] Trial 150 pruned.

Best trial: 134. Best value: 0.640409:  74%|███████▍  | 149/200 [01:24<00:46,  1.10it/s]

[I 2025-11-10 17:47:21,018] Trial 146 finished with value: 0.6115204678362572 and parameters: {'max_depth': 4, 'learning_rate': 0.012297977316726105, 'n_estimators': 1356, 'subsample': 0.6684486777634646, 'colsample_bytree': 0.5915193611686428, 'min_child_weight': 4, 'gamma': 3.623283364857801, 'reg_alpha': 1.1386139673570416e-07, 'reg_lambda': 0.4999100298840683, 'max_delta_step': 5}. Best is trial 134 with value: 0.6404093567251462.

Best trial: 134. Best value: 0.640409:  75%|███████▌  | 150/200 [01:24<00:35,  1.41it/s]

[I 2025-11-10 17:47:21,230] Trial 151 pruned.

Best trial: 147. Best value: 0.645322:  76%|███████▌  | 152/200 [01:26<00:29,  1.65it/s]

[I 2025-11-10 17:47:22,276] Trial 147 finished with value: 0.6453216374269005 and parameters: {'max_depth': 4, 'learning_rate': 0.01745677502524491, 'n_estimators': 1373, 'subsample': 0.620067286562381, 'colsample_bytree': 0.5682432720093084, 'min_child_weight': 4, 'gamma': 3.556111426052709, 'reg_alpha': 1.0915632476261694e-07, 'reg_lambda': 4.554310829993292e-05, 'max_delta_step': 6}. Best is trial 147 with value: 0.6453216374269005.
[I 2025-11-10 17:47:22,402] Trial 153 pruned.

Best trial: 147. Best value: 0.645322:  76%|███████▋  | 153/200 [01:26<00:23,  1.98it/s]

[I 2025-11-10 17:47:22,668] Trial 152 pruned.

Best trial: 149. Best value: 0.654211:  77%|███████▋  | 154/200 [01:27<00:28,  1.59it/s]

[I 2025-11-10 17:47:23,582] Trial 149 finished with value: 0.6542105263157894 and parameters: {'max_depth': 4, 'learning_rate': 0.010751639189354345, 'n_estimators': 1352, 'subsample': 0.6191931018421805, 'colsample_bytree': 0.5923328756587336, 'min_child_weight': 4, 'gamma': 3.7087376422954517, 'reg_alpha': 0.004781964475252221, 'reg_lambda': 0.4168498520785886, 'max_delta_step': 6}. Best is trial 149 with value: 0.6542105263157894.

Best trial: 149. Best value: 0.654211:  78%|███████▊  | 155/200 [01:27<00:22,  1.97it/s]

[I 2025-11-10 17:47:23,810] Trial 154 pruned.

Best trial: 149. Best value: 0.654211:  78%|███████▊  | 156/200 [01:30<00:56,  1.28s/it]

[I 2025-11-10 17:47:26,905] Trial 156 finished with value: 0.633157894736842 and parameters: {'max_depth': 4, 'learning_rate': 0.07273796024093795, 'n_estimators': 978, 'subsample': 0.611897584506228, 'colsample_bytree': 0.5664793460324408, 'min_child_weight': 4, 'gamma': 3.5019009303532482, 'reg_alpha': 1.9440597112652576e-07, 'reg_lambda': 0.00011319916258913467, 'max_delta_step': 6}. Best is trial 149 with value: 0.6542105263157894.

Best trial: 149. Best value: 0.654211:  79%|███████▉  | 158/200 [01:31<00:34,  1.21it/s]

[I 2025-11-10 17:47:27,653] Trial 155 finished with value: 0.6300584795321638 and parameters: {'max_depth': 4, 'learning_rate': 0.019212836092921657, 'n_estimators': 1231, 'subsample': 0.6256254319303618, 'colsample_bytree': 0.5342943004933166, 'min_child_weight': 4, 'gamma': 4.142181088238051, 'reg_alpha': 3.258911795974449e-08, 'reg_lambda': 5.4872974301891145e-05, 'max_delta_step': 6}. Best is trial 149 with value: 0.6542105263157894.
[I 2025-11-10 17:47:27,784] Trial 159 pruned.

Best trial: 149. Best value: 0.654211:  80%|███████▉  | 159/200 [01:32<00:33,  1.22it/s]

[I 2025-11-10 17:47:28,590] Trial 160 pruned.

Best trial: 149. Best value: 0.654211:  80%|████████  | 160/200 [01:33<00:31,  1.29it/s]

[I 2025-11-10 17:47:29,269] Trial 158 finished with value: 0.651578947368421 and parameters: {'max_depth': 4, 'learning_rate': 0.0735019881469415, 'n_estimators': 1240, 'subsample': 0.6197940620559449, 'colsample_bytree': 0.5670493552132406, 'min_child_weight': 4, 'gamma': 4.083940436131723, 'reg_alpha': 0.003977433761360836, 'reg_lambda': 0.003280023318956104, 'max_delta_step': 6}. Best is trial 149 with value: 0.6542105263157894.

Best trial: 149. Best value: 0.654211:  80%|████████  | 161/200 [01:33<00:23,  1.67it/s]

[I 2025-11-10 17:47:29,451] Trial 157 finished with value: 0.6394152046783625 and parameters: {'max_depth': 4, 'learning_rate': 0.01343925055630563, 'n_estimators': 1319, 'subsample': 0.6243965254282604, 'colsample_bytree': 0.5855731791870175, 'min_child_weight': 4, 'gamma': 3.852418684060415, 'reg_alpha': 0.0043062043459927615, 'reg_lambda': 4.806165702815592e-05, 'max_delta_step': 6}. Best is trial 149 with value: 0.6542105263157894.

Best trial: 149. Best value: 0.654211:  81%|████████  | 162/200 [01:34<00:25,  1.48it/s]

[I 2025-11-10 17:47:30,310] Trial 164 pruned.

Best trial: 149. Best value: 0.654211:  82%|████████▏ | 163/200 [01:34<00:27,  1.35it/s]

[I 2025-11-10 17:47:31,193] Trial 165 pruned.

Best trial: 149. Best value: 0.654211:  82%|████████▏ | 164/200 [01:35<00:27,  1.32it/s]

[I 2025-11-10 17:47:32,000] Trial 161 finished with value: 0.5811695906432748 and parameters: {'max_depth': 5, 'learning_rate': 0.03287598660999248, 'n_estimators': 972, 'subsample': 0.5963920262713538, 'colsample_bytree': 0.5320935903929094, 'min_child_weight': 4, 'gamma': 4.076098048786999, 'reg_alpha': 0.0001912051632451823, 'reg_lambda': 0.06785351833852321, 'max_delta_step': 7}. Best is trial 149 with value: 0.6542105263157894.

Best trial: 149. Best value: 0.654211:  82%|████████▎ | 165/200 [01:36<00:26,  1.33it/s]

[I 2025-11-10 17:47:32,743] Trial 162 finished with value: 0.5811695906432748 and parameters: {'max_depth': 5, 'learning_rate': 0.0895554129621921, 'n_estimators': 954, 'subsample': 0.5968006922804302, 'colsample_bytree': 0.5259549281805508, 'min_child_weight': 4, 'gamma': 3.8844103204751725, 'reg_alpha': 0.014977357392411485, 'reg_lambda': 4.303584928006513e-05, 'max_delta_step': 2}. Best is trial 149 with value: 0.6542105263157894.

Best trial: 149. Best value: 0.654211:  83%|████████▎ | 166/200 [01:38<00:36,  1.08s/it]

[I 2025-11-10 17:47:34,582] Trial 163 finished with value: 0.5789473684210527 and parameters: {'max_depth': 3, 'learning_rate': 0.057993207916177465, 'n_estimators': 1237, 'subsample': 0.5967814605693232, 'colsample_bytree': 0.5253426736708992, 'min_child_weight': 4, 'gamma': 3.8299549170775626, 'reg_alpha': 0.0023040816207241617, 'reg_lambda': 4.602917151294801e-05, 'max_delta_step': 6}. Best is trial 149 with value: 0.6542105263157894.

Best trial: 149. Best value: 0.654211:  84%|████████▎ | 167/200 [01:39<00:32,  1.03it/s]

[I 2025-11-10 17:47:35,308] Trial 166 finished with value: 0.6496783625730995 and parameters: {'max_depth': 4, 'learning_rate': 0.053670345889066946, 'n_estimators': 982, 'subsample': 0.6278378055882547, 'colsample_bytree': 0.5330145735997179, 'min_child_weight': 4, 'gamma': 4.0511502172292655, 'reg_alpha': 0.009677689151468778, 'reg_lambda': 1.3956931331839289e-05, 'max_delta_step': 6}. Best is trial 149 with value: 0.6542105263157894.

Best trial: 149. Best value: 0.654211:  84%|████████▍ | 168/200 [01:39<00:30,  1.05it/s]

[I 2025-11-10 17:47:36,211] Trial 170 pruned.

Best trial: 149. Best value: 0.654211:  84%|████████▍ | 169/200 [01:41<00:31,  1.02s/it]

[I 2025-11-10 17:47:37,382] Trial 167 finished with value: 0.6386549707602339 and parameters: {'max_depth': 4, 'learning_rate': 0.05910879783994032, 'n_estimators': 1244, 'subsample': 0.6214420674770508, 'colsample_bytree': 0.5570490975961168, 'min_child_weight': 4, 'gamma': 3.8277158025086777, 'reg_alpha': 0.002984783329831222, 'reg_lambda': 0.0001874429275005625, 'max_delta_step': 6}. Best is trial 149 with value: 0.6542105263157894.

Best trial: 149. Best value: 0.654211:  85%|████████▌ | 170/200 [01:41<00:27,  1.11it/s]

[I 2025-11-10 17:47:38,007] Trial 168 finished with value: 0.6492105263157895 and parameters: {'max_depth': 4, 'learning_rate': 0.05921355139480887, 'n_estimators': 1243, 'subsample': 0.6288192380058476, 'colsample_bytree': 0.5005541988341937, 'min_child_weight': 4, 'gamma': 3.310840547524612, 'reg_alpha': 0.0016326516118113428, 'reg_lambda': 2.656081320361082e-05, 'max_delta_step': 6}. Best is trial 149 with value: 0.6542105263157894.

Best trial: 171. Best value: 0.670936:  86%|████████▌ | 171/200 [01:43<00:36,  1.28s/it]

[I 2025-11-10 17:47:40,157] Trial 169 finished with value: 0.6495711500974658 and parameters: {'max_depth': 4, 'learning_rate': 0.021288025079607257, 'n_estimators': 1252, 'subsample': 0.6273773958404173, 'colsample_bytree': 0.572295589805668, 'min_child_weight': 4, 'gamma': 3.3265816230476637, 'reg_alpha': 0.009665553377910821, 'reg_lambda': 0.008636350506210515, 'max_delta_step': 6}. Best is trial 149 with value: 0.6542105263157894.
[I 2025-11-10 17:47:40,185] Trial 171 finished with value: 0.6709356725146198 and parameters: {'max_depth': 4, 'learning_rate': 0.03887399425645028, 'n_estimators': 883, 'subsample': 0.6367440846506451, 'colsample_bytree': 0.5758666321828269, 'min_child_weight': 4, 'gamma': 3.9908318616841143, 'reg_alpha': 0.006815199577274377, 'reg_lambda': 2.445406394176777e-05, 'max_delta_step': 6}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  86%|████████▋ | 173/200 [01:45<00:26,  1.03it/s]

[I 2025-11-10 17:47:41,404] Trial 172 finished with value: 0.6382163742690058 and parameters: {'max_depth': 4, 'learning_rate': 0.049001263101897244, 'n_estimators': 889, 'subsample': 0.6431326450541611, 'colsample_bytree': 0.5002898492495044, 'min_child_weight': 4, 'gamma': 4.253370777730908, 'reg_alpha': 0.003936154612898529, 'reg_lambda': 0.00016634166008904286, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  87%|████████▋ | 174/200 [01:47<00:31,  1.19s/it]

[I 2025-11-10 17:47:43,259] Trial 173 finished with value: 0.5992690058479533 and parameters: {'max_depth': 4, 'learning_rate': 0.08011697226035261, 'n_estimators': 1200, 'subsample': 0.6389387670346334, 'colsample_bytree': 0.5391001083753977, 'min_child_weight': 4, 'gamma': 3.6753962517722663, 'reg_alpha': 0.003750078703704994, 'reg_lambda': 0.00016848058512145326, 'max_delta_step': 6}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  88%|████████▊ | 175/200 [01:47<00:26,  1.06s/it]

[I 2025-11-10 17:47:43,951] Trial 175 finished with value: 0.6180799220272906 and parameters: {'max_depth': 4, 'learning_rate': 0.054771740529881124, 'n_estimators': 860, 'subsample': 0.6396772269634816, 'colsample_bytree': 0.5113959768441744, 'min_child_weight': 4, 'gamma': 3.705076966524875, 'reg_alpha': 0.00375700881224122, 'reg_lambda': 1.7816825568889835e-05, 'max_delta_step': 6}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  88%|████████▊ | 176/200 [01:48<00:26,  1.12s/it]

[I 2025-11-10 17:47:45,218] Trial 176 finished with value: 0.6523391812865497 and parameters: {'max_depth': 4, 'learning_rate': 0.050731430596437393, 'n_estimators': 882, 'subsample': 0.6351899443497873, 'colsample_bytree': 0.5096740943582125, 'min_child_weight': 4, 'gamma': 3.6846223906217026, 'reg_alpha': 0.03918196780798382, 'reg_lambda': 1.604898227952701e-05, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  88%|████████▊ | 177/200 [01:49<00:20,  1.14it/s]

[I 2025-11-10 17:47:45,469] Trial 174 finished with value: 0.6025243664717349 and parameters: {'max_depth': 4, 'learning_rate': 0.05639316273082697, 'n_estimators': 1204, 'subsample': 0.6383784900777151, 'colsample_bytree': 0.5142280083421534, 'min_child_weight': 4, 'gamma': 4.03072496100569, 'reg_alpha': 0.003443967010285597, 'reg_lambda': 0.00018192515986145916, 'max_delta_step': 6}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  89%|████████▉ | 178/200 [01:49<00:17,  1.27it/s]

[I 2025-11-10 17:47:46,038] Trial 179 pruned.

Best trial: 171. Best value: 0.670936:  90%|████████▉ | 179/200 [01:50<00:18,  1.11it/s]

[I 2025-11-10 17:47:47,201] Trial 177 finished with value: 0.6393469785575049 and parameters: {'max_depth': 4, 'learning_rate': 0.04873681223918429, 'n_estimators': 890, 'subsample': 0.6425057365721688, 'colsample_bytree': 0.5130094541351689, 'min_child_weight': 4, 'gamma': 3.9864030017307615, 'reg_alpha': 0.0015598445545369584, 'reg_lambda': 1.2849905399131485e-05, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  90%|█████████ | 180/200 [01:51<00:14,  1.34it/s]

[I 2025-11-10 17:47:47,580] Trial 178 finished with value: 0.6280116959064327 and parameters: {'max_depth': 4, 'learning_rate': 0.046654853679566614, 'n_estimators': 815, 'subsample': 0.6101929976177528, 'colsample_bytree': 0.5051903581941091, 'min_child_weight': 4, 'gamma': 4.252636202346601, 'reg_alpha': 0.03318293892172086, 'reg_lambda': 0.034868463759689584, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  90%|█████████ | 181/200 [01:53<00:19,  1.03s/it]

[I 2025-11-10 17:47:49,308] Trial 180 finished with value: 0.6280116959064327 and parameters: {'max_depth': 4, 'learning_rate': 0.04856916999847873, 'n_estimators': 909, 'subsample': 0.6099315543310068, 'colsample_bytree': 0.503738394004349, 'min_child_weight': 4, 'gamma': 4.259079574789037, 'reg_alpha': 0.036881709906686315, 'reg_lambda': 0.032582367334870105, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  91%|█████████ | 182/200 [01:53<00:15,  1.18it/s]

[I 2025-11-10 17:47:49,712] Trial 181 finished with value: 0.6441520467836258 and parameters: {'max_depth': 4, 'learning_rate': 0.03958507236821331, 'n_estimators': 888, 'subsample': 0.626921168150563, 'colsample_bytree': 0.5015434786726305, 'min_child_weight': 4, 'gamma': 4.224094883045585, 'reg_alpha': 0.03807654468098437, 'reg_lambda': 2.277425765522102e-05, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  92%|█████████▏| 183/200 [01:54<00:15,  1.08it/s]

[I 2025-11-10 17:47:50,820] Trial 183 finished with value: 0.6378362573099414 and parameters: {'max_depth': 4, 'learning_rate': 0.0402764693406442, 'n_estimators': 755, 'subsample': 0.6255106942972962, 'colsample_bytree': 0.5520048306049774, 'min_child_weight': 4, 'gamma': 3.5877470125945594, 'reg_alpha': 0.0074743546705445365, 'reg_lambda': 2.8834356286355377e-05, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  92%|█████████▏| 184/200 [01:54<00:11,  1.39it/s]

[I 2025-11-10 17:47:51,060] Trial 182 finished with value: 0.6341520467836259 and parameters: {'max_depth': 4, 'learning_rate': 0.04035371832054391, 'n_estimators': 909, 'subsample': 0.6218305004096318, 'colsample_bytree': 0.5023154835301649, 'min_child_weight': 4, 'gamma': 4.304899595193544, 'reg_alpha': 0.038226650349879196, 'reg_lambda': 0.009543790634441527, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  92%|█████████▎| 185/200 [01:56<00:16,  1.13s/it]

[I 2025-11-10 17:47:53,152] Trial 184 finished with value: 0.6510526315789474 and parameters: {'max_depth': 4, 'learning_rate': 0.06269776483407336, 'n_estimators': 865, 'subsample': 0.6257089064296404, 'colsample_bytree': 0.5529093471848099, 'min_child_weight': 4, 'gamma': 3.577468004200232, 'reg_alpha': 0.008102384936066907, 'reg_lambda': 2.7444864943030376e-05, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  93%|█████████▎| 186/200 [01:57<00:13,  1.06it/s]

[I 2025-11-10 17:47:53,640] Trial 185 finished with value: 0.6300584795321637 and parameters: {'max_depth': 4, 'learning_rate': 0.04206719697332705, 'n_estimators': 881, 'subsample': 0.6263607768587088, 'colsample_bytree': 0.5508797610528794, 'min_child_weight': 4, 'gamma': 3.570952668322211, 'reg_alpha': 0.0015479493836255335, 'reg_lambda': 1.3852921585191255e-05, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  94%|█████████▎| 187/200 [01:58<00:12,  1.03it/s]

[I 2025-11-10 17:47:54,696] Trial 186 finished with value: 0.6568713450292398 and parameters: {'max_depth': 4, 'learning_rate': 0.039844598781465845, 'n_estimators': 872, 'subsample': 0.6291545073014315, 'colsample_bytree': 0.5493289128398541, 'min_child_weight': 4, 'gamma': 3.6090260319482774, 'reg_alpha': 0.018671783410160778, 'reg_lambda': 2.9618300590549274e-05, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  94%|█████████▍| 188/200 [01:58<00:09,  1.28it/s]

[I 2025-11-10 17:47:55,040] Trial 187 finished with value: 0.659093567251462 and parameters: {'max_depth': 4, 'learning_rate': 0.04098106509437997, 'n_estimators': 892, 'subsample': 0.6294132337010478, 'colsample_bytree': 0.5475721109263575, 'min_child_weight': 4, 'gamma': 3.5404480194017247, 'reg_alpha': 0.02003910251371647, 'reg_lambda': 2.8437737689963886e-05, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  94%|█████████▍| 189/200 [01:59<00:07,  1.48it/s]

[I 2025-11-10 17:47:55,456] Trial 190 pruned.

Best trial: 171. Best value: 0.670936:  95%|█████████▌| 190/200 [02:00<00:09,  1.01it/s]

[I 2025-11-10 17:47:57,184] Trial 188 finished with value: 0.6475730994152047 and parameters: {'max_depth': 4, 'learning_rate': 0.040684475006147705, 'n_estimators': 879, 'subsample': 0.6283944991332425, 'colsample_bytree': 0.546762191217206, 'min_child_weight': 4, 'gamma': 3.9260974690616677, 'reg_alpha': 0.05748999965385667, 'reg_lambda': 2.6481591723310317e-05, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  96%|█████████▌| 191/200 [02:01<00:07,  1.28it/s]

[I 2025-11-10 17:47:57,475] Trial 189 finished with value: 0.6260136452241716 and parameters: {'max_depth': 4, 'learning_rate': 0.038732765053580566, 'n_estimators': 855, 'subsample': 0.648629306421479, 'colsample_bytree': 0.501410018534192, 'min_child_weight': 4, 'gamma': 3.373316343263043, 'reg_alpha': 0.02109992205092071, 'reg_lambda': 2.6079795050149125e-05, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  96%|█████████▌| 192/200 [02:02<00:06,  1.24it/s]

[I 2025-11-10 17:47:58,343] Trial 191 finished with value: 0.6195808966861599 and parameters: {'max_depth': 4, 'learning_rate': 0.04380549348027375, 'n_estimators': 729, 'subsample': 0.6451394963190858, 'colsample_bytree': 0.5519446400416099, 'min_child_weight': 4, 'gamma': 3.3674710232636365, 'reg_alpha': 0.01851152093487865, 'reg_lambda': 6.59625641561711e-06, 'max_delta_step': 4}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  96%|█████████▋| 193/200 [02:02<00:05,  1.31it/s]

[I 2025-11-10 17:47:59,002] Trial 194 pruned.

Best trial: 171. Best value: 0.670936:  97%|█████████▋| 194/200 [02:03<00:03,  1.65it/s]

[I 2025-11-10 17:47:59,243] Trial 192 finished with value: 0.6358771929824562 and parameters: {'max_depth': 4, 'learning_rate': 0.037157970881134, 'n_estimators': 836, 'subsample': 0.6329995566324695, 'colsample_bytree': 0.589040034823389, 'min_child_weight': 4, 'gamma': 3.65810995932659, 'reg_alpha': 0.007483790467354004, 'reg_lambda': 6.843804335487927e-06, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  98%|█████████▊| 195/200 [02:04<00:04,  1.09it/s]

[I 2025-11-10 17:48:00,882] Trial 193 finished with value: 0.6523391812865497 and parameters: {'max_depth': 4, 'learning_rate': 0.05138682768870623, 'n_estimators': 839, 'subsample': 0.636839992534221, 'colsample_bytree': 0.5171409370360807, 'min_child_weight': 4, 'gamma': 3.3539149407956543, 'reg_alpha': 0.06306306781961157, 'reg_lambda': 1.588261348040113e-05, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  98%|█████████▊| 196/200 [02:05<00:04,  1.04s/it]

[I 2025-11-10 17:48:02,222] Trial 195 finished with value: 0.6348245614035088 and parameters: {'max_depth': 4, 'learning_rate': 0.03562457345839729, 'n_estimators': 881, 'subsample': 0.6326227239068035, 'colsample_bytree': 0.5877908267030688, 'min_child_weight': 4, 'gamma': 3.617047097758232, 'reg_alpha': 0.11103808319362815, 'reg_lambda': 2.17292320775489e-05, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  98%|█████████▊| 197/200 [02:06<00:02,  1.20it/s]

[I 2025-11-10 17:48:02,555] Trial 196 finished with value: 0.6364327485380118 and parameters: {'max_depth': 4, 'learning_rate': 0.03789103649802217, 'n_estimators': 833, 'subsample': 0.6319519738572239, 'colsample_bytree': 0.5162739104919688, 'min_child_weight': 4, 'gamma': 3.9575712070582596, 'reg_alpha': 0.006712239351700617, 'reg_lambda': 1.9948464858776245e-05, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936:  99%|█████████▉| 198/200 [02:06<00:01,  1.44it/s]

[I 2025-11-10 17:48:02,931] Trial 197 finished with value: 0.6443859649122807 and parameters: {'max_depth': 4, 'learning_rate': 0.03421812339017091, 'n_estimators': 892, 'subsample': 0.6231712539446814, 'colsample_bytree': 0.5140463328948872, 'min_child_weight': 4, 'gamma': 3.8982526263308857, 'reg_alpha': 0.07460435206189303, 'reg_lambda': 1.8028440181463183e-05, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936: 100%|█████████▉| 199/200 [02:07<00:00,  1.38it/s]

[I 2025-11-10 17:48:03,734] Trial 198 finished with value: 0.6590058479532164 and parameters: {'max_depth': 4, 'learning_rate': 0.06549751552355854, 'n_estimators': 836, 'subsample': 0.6348494132368508, 'colsample_bytree': 0.5188762573210532, 'min_child_weight': 4, 'gamma': 3.9925601436365343, 'reg_alpha': 0.07143712311020921, 'reg_lambda': 1.4334978945425696e-05, 'max_delta_step': 5}. Best is trial 171 with value: 0.6709356725146198.

Best trial: 171. Best value: 0.670936: 100%|██████████| 200/200 [02:08<00:00,  1.56it/s]

[I 2025-11-10 17:48:04,353] Trial 199 finished with value: 0.6525633528265107 and parameters: {'max_depth': 4, 'learning_rate': 0.0644485940841911, 'n_estimators': 836, 'subsample': 0.6442268353605162, 'colsample_bytree': 0.5158453411768655, 'min_child_weight': 4, 'gamma': 3.9597178140527607, 'reg_alpha': 0.011428300608327615, 'reg_lambda': 1.421950823407646e-05, 'max_delta_step': 4}. Best is trial 171 with value: 0.6709356725146198.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\utils\_plotting.py:28: RuntimeWarning:

More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.

[I 2025-11-10 17:48:05,245] A new study created in memory with name: 17_1_roc_auc
Best trial: 1. Best value: 0.5:   0%|          | 1/200 [00:03<11:06,  3.35s/it]

[I 2025-11-10 17:48:08,587] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.15835974117853632, 'n_estimators': 807, 'subsample': 0.5006712047030337, 'colsample_bytree': 0.980694553349378, 'min_child_weight': 10, 'gamma': 0.20164497817485083, 'reg_alpha': 0.0018983470117390105, 'reg_lambda': 0.00035745325513386313, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 3. Best value: 0.523996:   2%|▏         | 3/200 [00:05<04:54,  1.50s/it]

[I 2025-11-10 17:48:10,704] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.283699500638096, 'n_estimators': 1483, 'subsample': 0.9946179249132749, 'colsample_bytree': 0.6007189479836863, 'min_child_weight': 7, 'gamma': 0.3665359792012435, 'reg_alpha': 3.343863890686714, 'reg_lambda': 0.2813306193075634, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:48:10,859] Trial 3 finished with value: 0.5239961013645223 and parameters: {'max_depth': 7, 'learning_rate': 0.039886629679947536, 'n_estimators': 1309, 'subsample': 0.8922329740949186, 'colsample_bytree': 0.9477029071288434, 'min_child_weight': 4, 'gamma': 1.496449088630842, 'reg_alpha': 1.4953723187439616e-06, 'reg_lambda': 0.0008419864053047681, 'max_delta_step': 3}. Best is trial 3 with value: 0.5239961013645223.

Best trial: 2. Best value: 0.548012:   2%|▏         | 4/200 [00:06<03:55,  1.20s/it]

[I 2025-11-10 17:48:11,612] Trial 2 finished with value: 0.5480116959064327 and parameters: {'max_depth': 9, 'learning_rate': 0.060100996111405965, 'n_estimators': 1024, 'subsample': 0.8559798988070875, 'colsample_bytree': 0.7463193507437025, 'min_child_weight': 1, 'gamma': 2.9168860867416373, 'reg_alpha': 0.007177969348514125, 'reg_lambda': 0.004015585260075374, 'max_delta_step': 6}. Best is trial 2 with value: 0.5480116959064327.

Best trial: 4. Best value: 0.550409:   2%|▎         | 5/200 [00:07<03:15,  1.00s/it]

[I 2025-11-10 17:48:12,257] Trial 4 finished with value: 0.5504093567251462 and parameters: {'max_depth': 6, 'learning_rate': 0.05448198648816968, 'n_estimators': 863, 'subsample': 0.5496969550351247, 'colsample_bytree': 0.523664054158477, 'min_child_weight': 2, 'gamma': 4.982565236292971, 'reg_alpha': 0.7836127883499793, 'reg_lambda': 6.614975994610709e-08, 'max_delta_step': 4}. Best is trial 4 with value: 0.5504093567251462.

Best trial: 4. Best value: 0.550409:   3%|▎         | 6/200 [00:08<04:05,  1.27s/it]

[I 2025-11-10 17:48:14,045] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.0428926668959425, 'n_estimators': 840, 'subsample': 0.6781281628894511, 'colsample_bytree': 0.8375212613960938, 'min_child_weight': 5, 'gamma': 1.0030129824278622, 'reg_alpha': 0.012270447387020137, 'reg_lambda': 1.9365044215818852e-08, 'max_delta_step': 2}. Best is trial 4 with value: 0.5504093567251462.

Best trial: 4. Best value: 0.550409:   4%|▎         | 7/200 [00:09<03:26,  1.07s/it]

[I 2025-11-10 17:48:14,713] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.2884095110632765, 'n_estimators': 624, 'subsample': 0.9037167126995849, 'colsample_bytree': 0.6640394523391812, 'min_child_weight': 6, 'gamma': 4.7560067358419325, 'reg_alpha': 4.7676056944708484e-07, 'reg_lambda': 9.087005267722693e-06, 'max_delta_step': 9}. Best is trial 4 with value: 0.5504093567251462.

Best trial: 4. Best value: 0.550409:   4%|▍         | 8/200 [00:09<02:43,  1.17it/s]

[I 2025-11-10 17:48:15,093] Trial 6 finished with value: 0.5267641325536062 and parameters: {'max_depth': 4, 'learning_rate': 0.02102662311451099, 'n_estimators': 437, 'subsample': 0.6591518010575588, 'colsample_bytree': 0.7268724116139353, 'min_child_weight': 1, 'gamma': 0.8114491650136113, 'reg_alpha': 0.012887231068733001, 'reg_lambda': 6.8694098757620046e-06, 'max_delta_step': 6}. Best is trial 4 with value: 0.5504093567251462.

Best trial: 4. Best value: 0.550409:   4%|▍         | 9/200 [00:10<02:26,  1.31it/s]

[I 2025-11-10 17:48:15,671] Trial 7 finished with value: 0.5089083820662766 and parameters: {'max_depth': 8, 'learning_rate': 0.030767923589904756, 'n_estimators': 892, 'subsample': 0.9340516802776442, 'colsample_bytree': 0.8137541367626425, 'min_child_weight': 4, 'gamma': 0.2206278682741658, 'reg_alpha': 6.371310460464239e-07, 'reg_lambda': 0.002169944938213939, 'max_delta_step': 7}. Best is trial 4 with value: 0.5504093567251462.

Best trial: 4. Best value: 0.550409:   6%|▌         | 11/200 [00:11<02:12,  1.42it/s]

[I 2025-11-10 17:48:17,061] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.018204194533759356, 'n_estimators': 336, 'subsample': 0.5779635357838728, 'colsample_bytree': 0.891336441424412, 'min_child_weight': 10, 'gamma': 2.8860332977916303, 'reg_alpha': 0.001286113361120507, 'reg_lambda': 4.634100365927177e-06, 'max_delta_step': 8}. Best is trial 4 with value: 0.5504093567251462.
[I 2025-11-10 17:48:17,185] Trial 9 pruned.

Best trial: 10. Best value: 0.584172:   6%|▌         | 12/200 [00:12<01:43,  1.81it/s]

[I 2025-11-10 17:48:17,388] Trial 10 finished with value: 0.5841715399610136 and parameters: {'max_depth': 8, 'learning_rate': 0.06706832244925959, 'n_estimators': 540, 'subsample': 0.9830522739463294, 'colsample_bytree': 0.8271297409819316, 'min_child_weight': 4, 'gamma': 4.4780654980959085, 'reg_alpha': 0.5298553019699299, 'reg_lambda': 2.150924072336994e-07, 'max_delta_step': 8}. Best is trial 10 with value: 0.5841715399610136.

Best trial: 10. Best value: 0.584172:   6%|▋         | 13/200 [00:12<01:25,  2.19it/s]

[I 2025-11-10 17:48:17,624] Trial 11 pruned.

Best trial: 10. Best value: 0.584172:   7%|▋         | 14/200 [00:12<01:16,  2.44it/s]

[I 2025-11-10 17:48:17,927] Trial 15 pruned.

Best trial: 10. Best value: 0.584172:   8%|▊         | 15/200 [00:12<01:06,  2.80it/s]

[I 2025-11-10 17:48:18,161] Trial 17 pruned.

Best trial: 10. Best value: 0.584172:   8%|▊         | 16/200 [00:13<01:20,  2.28it/s]

[I 2025-11-10 17:48:18,787] Trial 16 pruned.

Best trial: 10. Best value: 0.584172:   9%|▉         | 18/200 [00:14<01:01,  2.98it/s]

[I 2025-11-10 17:48:19,213] Trial 18 pruned.
[I 2025-11-10 17:48:19,319] Trial 13 pruned.

Best trial: 10. Best value: 0.584172:  10%|▉         | 19/200 [00:14<01:13,  2.45it/s]

[I 2025-11-10 17:48:19,899] Trial 19 pruned.

Best trial: 10. Best value: 0.584172:  10%|█         | 20/200 [00:15<01:39,  1.80it/s]

[I 2025-11-10 17:48:20,794] Trial 22 pruned.

Best trial: 10. Best value: 0.584172:  10%|█         | 21/200 [00:16<01:57,  1.52it/s]

[I 2025-11-10 17:48:21,692] Trial 20 pruned.

Best trial: 10. Best value: 0.584172:  11%|█         | 22/200 [00:17<01:59,  1.49it/s]

[I 2025-11-10 17:48:22,390] Trial 23 pruned.

Best trial: 10. Best value: 0.584172:  12%|█▏        | 24/200 [00:18<01:35,  1.85it/s]

[I 2025-11-10 17:48:23,205] Trial 14 finished with value: 0.5556530214424951 and parameters: {'max_depth': 10, 'learning_rate': 0.08300035624091745, 'n_estimators': 1138, 'subsample': 0.8087271099126291, 'colsample_bytree': 0.5167135487335943, 'min_child_weight': 1, 'gamma': 3.4895173314719297, 'reg_alpha': 1.454686696306819, 'reg_lambda': 0.21961728955900342, 'max_delta_step': 4}. Best is trial 10 with value: 0.5841715399610136.
[I 2025-11-10 17:48:23,344] Trial 21 finished with value: 0.5408187134502923 and parameters: {'max_depth': 8, 'learning_rate': 0.06332210217853661, 'n_estimators': 752, 'subsample': 0.9954365439997086, 'colsample_bytree': 0.8237959970987339, 'min_child_weight': 3, 'gamma': 4.306668040912051, 'reg_alpha': 0.2946630020128287, 'reg_lambda': 3.6426572062578846e-05, 'max_delta_step': 1}. Best is trial 10 with value: 0.5841715399610136.

Best trial: 10. Best value: 0.584172:  12%|█▎        | 25/200 [00:22<04:55,  1.69s/it]

[I 2025-11-10 17:48:27,716] Trial 24 finished with value: 0.5527875243664717 and parameters: {'max_depth': 10, 'learning_rate': 0.05849169528260546, 'n_estimators': 1015, 'subsample': 0.8579293953608542, 'colsample_bytree': 0.7406762149957165, 'min_child_weight': 1, 'gamma': 2.8302578693821268, 'reg_alpha': 0.040663066125507505, 'reg_lambda': 0.02401965669974395, 'max_delta_step': 6}. Best is trial 10 with value: 0.5841715399610136.

Best trial: 26. Best value: 0.599591:  13%|█▎        | 26/200 [00:22<03:37,  1.25s/it]

[I 2025-11-10 17:48:27,941] Trial 27 finished with value: 0.5794541910331384 and parameters: {'max_depth': 10, 'learning_rate': 0.027922966491654815, 'n_estimators': 940, 'subsample': 0.5629789904238043, 'colsample_bytree': 0.5832368423926007, 'min_child_weight': 1, 'gamma': 3.293670950740733, 'reg_alpha': 1.951828423331652, 'reg_lambda': 0.030795035422594732, 'max_delta_step': 3}. Best is trial 10 with value: 0.5841715399610136.
[I 2025-11-10 17:48:28,020] Trial 26 finished with value: 0.5995906432748538 and parameters: {'max_depth': 10, 'learning_rate': 0.0652639466603065, 'n_estimators': 930, 'subsample': 0.8342469295820364, 'colsample_bytree': 0.5690953587709459, 'min_child_weight': 1, 'gamma': 3.4602100063608328, 'reg_alpha': 0.9294641238784982, 'reg_lambda': 4.775742462721341, 'max_delta_step': 3}. Best is trial 26 with value: 0.5995906432748538.

Best trial: 26. Best value: 0.599591:  14%|█▍        | 28/200 [00:22<02:05,  1.37it/s]

[I 2025-11-10 17:48:28,184] Trial 25 finished with value: 0.5493567251461987 and parameters: {'max_depth': 10, 'learning_rate': 0.05889912671040678, 'n_estimators': 968, 'subsample': 0.8470057009659215, 'colsample_bytree': 0.738717600119601, 'min_child_weight': 1, 'gamma': 3.150749103753399, 'reg_alpha': 0.015159851867592462, 'reg_lambda': 0.01690226668516883, 'max_delta_step': 6}. Best is trial 26 with value: 0.5995906432748538.

Best trial: 26. Best value: 0.599591:  14%|█▍        | 29/200 [00:23<01:52,  1.53it/s]

[I 2025-11-10 17:48:28,614] Trial 31 pruned.

Best trial: 26. Best value: 0.599591:  15%|█▌        | 30/200 [00:23<01:31,  1.86it/s]

[I 2025-11-10 17:48:28,812] Trial 30 pruned.

Best trial: 26. Best value: 0.599591:  16%|█▌        | 32/200 [00:24<01:23,  2.00it/s]

[I 2025-11-10 17:48:29,706] Trial 32 pruned.
[I 2025-11-10 17:48:29,863] Trial 33 pruned.

Best trial: 29. Best value: 0.634854:  16%|█▋        | 33/200 [00:28<04:24,  1.58s/it]

[I 2025-11-10 17:48:34,152] Trial 29 finished with value: 0.6348538011695906 and parameters: {'max_depth': 10, 'learning_rate': 0.028882217701560683, 'n_estimators': 1238, 'subsample': 0.7212370099196546, 'colsample_bytree': 0.5741036368831475, 'min_child_weight': 1, 'gamma': 3.375019293767489, 'reg_alpha': 2.0314441985682326, 'reg_lambda': 8.407356626498643, 'max_delta_step': 3}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  17%|█▋        | 34/200 [00:29<03:39,  1.32s/it]

[I 2025-11-10 17:48:34,841] Trial 28 finished with value: 0.5665692007797272 and parameters: {'max_depth': 10, 'learning_rate': 0.029383301095376783, 'n_estimators': 1263, 'subsample': 0.8518447077934614, 'colsample_bytree': 0.59105565221748, 'min_child_weight': 1, 'gamma': 3.196260023388609, 'reg_alpha': 0.040644961926353404, 'reg_lambda': 1.8830811778831182, 'max_delta_step': 7}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  18%|█▊        | 35/200 [00:30<02:58,  1.08s/it]

[I 2025-11-10 17:48:35,338] Trial 34 finished with value: 0.5922222222222222 and parameters: {'max_depth': 10, 'learning_rate': 0.07396675912852947, 'n_estimators': 1132, 'subsample': 0.8263686886382243, 'colsample_bytree': 0.5700325422718637, 'min_child_weight': 1, 'gamma': 3.520192770898845, 'reg_alpha': 1.7403551170651397, 'reg_lambda': 0.3503886283309721, 'max_delta_step': 3}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  18%|█▊        | 37/200 [00:30<01:43,  1.57it/s]

[I 2025-11-10 17:48:35,660] Trial 37 pruned.
[I 2025-11-10 17:48:35,770] Trial 35 finished with value: 0.5875243664717349 and parameters: {'max_depth': 10, 'learning_rate': 0.11325991949962597, 'n_estimators': 1144, 'subsample': 0.8193928201512625, 'colsample_bytree': 0.5900198447545386, 'min_child_weight': 1, 'gamma': 4.229778592962398, 'reg_alpha': 0.6791536312886661, 'reg_lambda': 0.10849832671262817, 'max_delta_step': 3}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  19%|█▉        | 38/200 [00:31<02:12,  1.22it/s]

[I 2025-11-10 17:48:37,025] Trial 38 pruned.

Best trial: 29. Best value: 0.634854:  20%|█▉        | 39/200 [00:32<02:30,  1.07it/s]

[I 2025-11-10 17:48:38,233] Trial 36 finished with value: 0.5367446393762183 and parameters: {'max_depth': 10, 'learning_rate': 0.04358295972073994, 'n_estimators': 779, 'subsample': 0.5440661729620623, 'colsample_bytree': 0.583135664541521, 'min_child_weight': 2, 'gamma': 1.8464624587854888, 'reg_alpha': 0.048012909433779095, 'reg_lambda': 0.09736040864395852, 'max_delta_step': 3}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  20%|██        | 40/200 [00:34<02:52,  1.08s/it]

[I 2025-11-10 17:48:39,644] Trial 42 pruned.

Best trial: 29. Best value: 0.634854:  20%|██        | 41/200 [00:37<04:10,  1.57s/it]

[I 2025-11-10 17:48:42,381] Trial 39 finished with value: 0.5313450292397661 and parameters: {'max_depth': 9, 'learning_rate': 0.12621833868004884, 'n_estimators': 1089, 'subsample': 0.8910527280538192, 'colsample_bytree': 0.6231136236479978, 'min_child_weight': 2, 'gamma': 4.266219466937867, 'reg_alpha': 0.003526164149267443, 'reg_lambda': 0.822389065026375, 'max_delta_step': 2}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  21%|██        | 42/200 [00:37<03:22,  1.28s/it]

[I 2025-11-10 17:48:42,975] Trial 41 finished with value: 0.46713450292397657 and parameters: {'max_depth': 9, 'learning_rate': 0.22764215619771155, 'n_estimators': 1105, 'subsample': 0.8193994987491019, 'colsample_bytree': 0.6166058684165959, 'min_child_weight': 2, 'gamma': 1.905141123019338, 'reg_alpha': 0.06543799980042893, 'reg_lambda': 0.9752023584555698, 'max_delta_step': 2}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  22%|██▏       | 43/200 [00:38<02:33,  1.02it/s]

[I 2025-11-10 17:48:43,247] Trial 40 finished with value: 0.49181286549707603 and parameters: {'max_depth': 9, 'learning_rate': 0.18637938789355818, 'n_estimators': 1379, 'subsample': 0.822468799093584, 'colsample_bytree': 0.6170319854999498, 'min_child_weight': 2, 'gamma': 1.927208390946254, 'reg_alpha': 0.00274218314364189, 'reg_lambda': 0.7930436515188669, 'max_delta_step': 2}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  22%|██▏       | 44/200 [00:39<03:04,  1.18s/it]

[I 2025-11-10 17:48:44,902] Trial 45 pruned.

Best trial: 29. Best value: 0.634854:  22%|██▎       | 45/200 [00:40<02:31,  1.03it/s]

[I 2025-11-10 17:48:45,396] Trial 43 finished with value: 0.6169005847953216 and parameters: {'max_depth': 9, 'learning_rate': 0.19353954124044295, 'n_estimators': 1231, 'subsample': 0.7646934882978872, 'colsample_bytree': 0.6119791281568754, 'min_child_weight': 3, 'gamma': 3.048523351625365, 'reg_alpha': 0.17095237646624836, 'reg_lambda': 9.33080454014865, 'max_delta_step': 5}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  23%|██▎       | 46/200 [00:40<01:56,  1.33it/s]

[I 2025-11-10 17:48:45,630] Trial 44 pruned.

Best trial: 29. Best value: 0.634854:  24%|██▎       | 47/200 [00:41<02:16,  1.12it/s]

[I 2025-11-10 17:48:46,840] Trial 48 pruned.

Best trial: 29. Best value: 0.634854:  24%|██▍       | 48/200 [00:43<02:59,  1.18s/it]

[I 2025-11-10 17:48:48,690] Trial 46 finished with value: 0.5465107212475633 and parameters: {'max_depth': 10, 'learning_rate': 0.06902730509056659, 'n_estimators': 1223, 'subsample': 0.7769208770744501, 'colsample_bytree': 0.7772206689687731, 'min_child_weight': 3, 'gamma': 3.698691453872184, 'reg_alpha': 0.7061644920455538, 'reg_lambda': 0.0005811048564758949, 'max_delta_step': 5}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  24%|██▍       | 49/200 [00:45<03:41,  1.47s/it]

[I 2025-11-10 17:48:50,839] Trial 49 finished with value: 0.5440545808966861 and parameters: {'max_depth': 10, 'learning_rate': 0.044689245089207096, 'n_estimators': 1208, 'subsample': 0.6692826040740923, 'colsample_bytree': 0.6840498668297379, 'min_child_weight': 3, 'gamma': 2.601253054771749, 'reg_alpha': 0.1441771127483508, 'reg_lambda': 6.531882855091935, 'max_delta_step': 3}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  25%|██▌       | 50/200 [00:46<03:18,  1.32s/it]

[I 2025-11-10 17:48:51,828] Trial 50 finished with value: 0.5667836257309942 and parameters: {'max_depth': 10, 'learning_rate': 0.10229914160784584, 'n_estimators': 1214, 'subsample': 0.7388626018875305, 'colsample_bytree': 0.5352919168883781, 'min_child_weight': 3, 'gamma': 2.942934132587824, 'reg_alpha': 2.9149202738178204, 'reg_lambda': 0.006120367596332988, 'max_delta_step': 4}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  26%|██▌       | 51/200 [00:47<02:36,  1.05s/it]

[I 2025-11-10 17:48:52,228] Trial 51 finished with value: 0.5234307992202728 and parameters: {'max_depth': 10, 'learning_rate': 0.10956182963472443, 'n_estimators': 874, 'subsample': 0.7386980843988076, 'colsample_bytree': 0.5421644187269068, 'min_child_weight': 3, 'gamma': 3.029337116354388, 'reg_alpha': 0.014118419876318775, 'reg_lambda': 0.004578611020530083, 'max_delta_step': 4}. Best is trial 29 with value: 0.6348538011695906.
[I 2025-11-10 17:48:52,282] Trial 47 finished with value: 0.5563937621832359 and parameters: {'max_depth': 7, 'learning_rate': 0.04563050755629593, 'n_estimators': 1236, 'subsample': 0.6631338846906776, 'colsample_bytree': 0.6734252268172181, 'min_child_weight': 1, 'gamma': 4.582433678684083, 'reg_alpha': 0.2819344894470137, 'reg_lambda': 0.003322221541856683, 'max_delta_step': 3}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  26%|██▋       | 53/200 [00:47<01:54,  1.29it/s]

[I 2025-11-10 17:48:53,152] Trial 54 pruned.
[I 2025-11-10 17:48:53,158] Trial 55 pruned.

Best trial: 29. Best value: 0.634854:  28%|██▊       | 55/200 [00:49<01:41,  1.43it/s]

[I 2025-11-10 17:48:54,323] Trial 56 pruned.

Best trial: 29. Best value: 0.634854:  28%|██▊       | 56/200 [00:49<01:26,  1.67it/s]

[I 2025-11-10 17:48:54,562] Trial 57 pruned.

Best trial: 29. Best value: 0.634854:  28%|██▊       | 57/200 [00:49<01:23,  1.72it/s]

[I 2025-11-10 17:48:55,087] Trial 58 pruned.

Best trial: 29. Best value: 0.634854:  29%|██▉       | 58/200 [00:50<01:09,  2.03it/s]

[I 2025-11-10 17:48:55,318] Trial 59 pruned.

Best trial: 29. Best value: 0.634854:  30%|██▉       | 59/200 [00:50<01:00,  2.35it/s]

[I 2025-11-10 17:48:55,564] Trial 52 finished with value: 0.6297660818713451 and parameters: {'max_depth': 10, 'learning_rate': 0.10371913434415037, 'n_estimators': 855, 'subsample': 0.7447581302610013, 'colsample_bytree': 0.5254605839661542, 'min_child_weight': 1, 'gamma': 3.1252753490505745, 'reg_alpha': 3.7435778148209296, 'reg_lambda': 0.0037634718656440478, 'max_delta_step': 4}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  30%|███       | 60/200 [00:51<01:19,  1.77it/s]

[I 2025-11-10 17:48:56,498] Trial 62 pruned.

Best trial: 29. Best value: 0.634854:  30%|███       | 61/200 [00:51<01:14,  1.87it/s]

[I 2025-11-10 17:48:56,952] Trial 60 pruned.

Best trial: 29. Best value: 0.634854:  31%|███       | 62/200 [00:52<01:33,  1.47it/s]

[I 2025-11-10 17:48:57,981] Trial 53 finished with value: 0.5288888888888889 and parameters: {'max_depth': 9, 'learning_rate': 0.1720234382915307, 'n_estimators': 1057, 'subsample': 0.8365824055594042, 'colsample_bytree': 0.6347617033617917, 'min_child_weight': 1, 'gamma': 3.1049981028333247, 'reg_alpha': 0.021149952801891206, 'reg_lambda': 0.2830532396329272, 'max_delta_step': 4}. Best is trial 29 with value: 0.6348538011695906.
[I 2025-11-10 17:48:57,987] Trial 63 pruned.

Best trial: 29. Best value: 0.634854:  32%|███▎      | 65/200 [00:53<00:54,  2.46it/s]

[I 2025-11-10 17:48:58,501] Trial 64 pruned.
[I 2025-11-10 17:48:58,656] Trial 65 pruned.

Best trial: 29. Best value: 0.634854:  33%|███▎      | 66/200 [00:53<00:45,  2.92it/s]

[I 2025-11-10 17:48:58,814] Trial 67 pruned.
[I 2025-11-10 17:48:58,847] Trial 66 pruned.

Best trial: 29. Best value: 0.634854:  34%|███▍      | 68/200 [00:54<00:46,  2.85it/s]

[I 2025-11-10 17:48:59,535] Trial 68 pruned.

Best trial: 29. Best value: 0.634854:  34%|███▍      | 69/200 [00:54<00:44,  2.94it/s]

[I 2025-11-10 17:48:59,843] Trial 70 pruned.

Best trial: 29. Best value: 0.634854:  35%|███▌      | 70/200 [00:55<01:06,  1.96it/s]

[I 2025-11-10 17:49:00,865] Trial 61 finished with value: 0.5878752436647173 and parameters: {'max_depth': 4, 'learning_rate': 0.06442527119227097, 'n_estimators': 988, 'subsample': 0.698381325447979, 'colsample_bytree': 0.5258347380704053, 'min_child_weight': 1, 'gamma': 3.8489971680900616, 'reg_alpha': 0.023166039477441554, 'reg_lambda': 1.8895469426026406, 'max_delta_step': 1}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  36%|███▌      | 71/200 [00:55<00:58,  2.20it/s]

[I 2025-11-10 17:49:01,163] Trial 71 pruned.

Best trial: 29. Best value: 0.634854:  36%|███▌      | 72/200 [00:57<01:51,  1.15it/s]

[I 2025-11-10 17:49:03,147] Trial 69 finished with value: 0.5877582846003898 and parameters: {'max_depth': 8, 'learning_rate': 0.052106842663831685, 'n_estimators': 921, 'subsample': 0.716564236433792, 'colsample_bytree': 0.601469718859174, 'min_child_weight': 2, 'gamma': 3.8054103816902303, 'reg_alpha': 3.437684154355687, 'reg_lambda': 0.0017515721238414628, 'max_delta_step': 6}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  36%|███▋      | 73/200 [00:59<02:30,  1.18s/it]

[I 2025-11-10 17:49:05,130] Trial 75 pruned.

Best trial: 29. Best value: 0.634854:  37%|███▋      | 74/200 [01:00<02:18,  1.10s/it]

[I 2025-11-10 17:49:06,003] Trial 76 pruned.

Best trial: 29. Best value: 0.634854:  38%|███▊      | 75/200 [01:01<02:07,  1.02s/it]

[I 2025-11-10 17:49:06,846] Trial 73 finished with value: 0.6059941520467836 and parameters: {'max_depth': 4, 'learning_rate': 0.020667101553691943, 'n_estimators': 1164, 'subsample': 0.6951347161436477, 'colsample_bytree': 0.5570320494503076, 'min_child_weight': 1, 'gamma': 4.0646433051749264, 'reg_alpha': 1.2256127555147833, 'reg_lambda': 4.417922978133185, 'max_delta_step': 6}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  38%|███▊      | 76/200 [01:01<01:36,  1.29it/s]

[I 2025-11-10 17:49:07,030] Trial 72 finished with value: 0.5712085769980506 and parameters: {'max_depth': 9, 'learning_rate': 0.02276024535658593, 'n_estimators': 1278, 'subsample': 0.7440207061738447, 'colsample_bytree': 0.6003519626759765, 'min_child_weight': 1, 'gamma': 3.400752365088089, 'reg_alpha': 0.9925544307707385, 'reg_lambda': 2.029928337291769, 'max_delta_step': 6}. Best is trial 29 with value: 0.6348538011695906.
[I 2025-11-10 17:49:07,059] Trial 74 finished with value: 0.5925341130604289 and parameters: {'max_depth': 3, 'learning_rate': 0.06440858783509057, 'n_estimators': 1163, 'subsample': 0.7388229441013775, 'colsample_bytree': 0.5523247182655746, 'min_child_weight': 1, 'gamma': 4.118875017617576, 'reg_alpha': 0.0005494527378018624, 'reg_lambda': 3.630800325310597, 'max_delta_step': 4}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  39%|███▉      | 78/200 [01:02<00:57,  2.12it/s]

[I 2025-11-10 17:49:07,244] Trial 77 pruned.

Best trial: 29. Best value: 0.634854:  40%|███▉      | 79/200 [01:03<01:14,  1.63it/s]

[I 2025-11-10 17:49:08,295] Trial 80 pruned.

Best trial: 29. Best value: 0.634854:  40%|████      | 80/200 [01:04<01:31,  1.31it/s]

[I 2025-11-10 17:49:09,475] Trial 79 pruned.

Best trial: 29. Best value: 0.634854:  40%|████      | 81/200 [01:04<01:23,  1.42it/s]

[I 2025-11-10 17:49:10,028] Trial 82 pruned.

Best trial: 29. Best value: 0.634854:  41%|████      | 82/200 [01:05<01:23,  1.42it/s]

[I 2025-11-10 17:49:10,728] Trial 83 pruned.

Best trial: 29. Best value: 0.634854:  42%|████▏     | 83/200 [01:05<01:08,  1.72it/s]

[I 2025-11-10 17:49:11,009] Trial 84 pruned.

Best trial: 29. Best value: 0.634854:  42%|████▏     | 84/200 [01:06<01:20,  1.44it/s]

[I 2025-11-10 17:49:11,981] Trial 85 pruned.

Best trial: 29. Best value: 0.634854:  42%|████▎     | 85/200 [01:07<01:12,  1.59it/s]

[I 2025-11-10 17:49:12,455] Trial 78 finished with value: 0.5718518518518518 and parameters: {'max_depth': 5, 'learning_rate': 0.01813525440486149, 'n_estimators': 941, 'subsample': 0.6332102109194544, 'colsample_bytree': 0.5582685239856173, 'min_child_weight': 1, 'gamma': 3.7619281568143768, 'reg_alpha': 0.000993922723906538, 'reg_lambda': 0.0009131167290023421, 'max_delta_step': 6}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  43%|████▎     | 86/200 [01:08<01:23,  1.36it/s]

[I 2025-11-10 17:49:13,446] Trial 81 finished with value: 0.5855555555555555 and parameters: {'max_depth': 4, 'learning_rate': 0.01773040982127287, 'n_estimators': 1099, 'subsample': 0.7607185444963072, 'colsample_bytree': 0.554411206133708, 'min_child_weight': 1, 'gamma': 3.2435549602775833, 'reg_alpha': 0.00013999343763265403, 'reg_lambda': 3.6618155795906806, 'max_delta_step': 0}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  44%|████▎     | 87/200 [01:08<01:23,  1.35it/s]

[I 2025-11-10 17:49:14,194] Trial 88 pruned.

Best trial: 29. Best value: 0.634854:  44%|████▍     | 88/200 [01:09<01:08,  1.63it/s]

[I 2025-11-10 17:49:14,503] Trial 89 pruned.

Best trial: 29. Best value: 0.634854:  44%|████▍     | 89/200 [01:09<01:05,  1.70it/s]

[I 2025-11-10 17:49:15,032] Trial 90 pruned.

Best trial: 29. Best value: 0.634854:  45%|████▌     | 90/200 [01:10<00:52,  2.10it/s]

[I 2025-11-10 17:49:15,246] Trial 91 pruned.

Best trial: 29. Best value: 0.634854:  46%|████▌     | 91/200 [01:10<00:44,  2.46it/s]

[I 2025-11-10 17:49:15,490] Trial 86 finished with value: 0.5840545808966862 and parameters: {'max_depth': 6, 'learning_rate': 0.05783666558176377, 'n_estimators': 809, 'subsample': 0.7285613976346618, 'colsample_bytree': 0.57664117849529, 'min_child_weight': 1, 'gamma': 3.5581274735595345, 'reg_alpha': 2.4606072874549456, 'reg_lambda': 1.224217114828646, 'max_delta_step': 5}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  46%|████▌     | 92/200 [01:10<00:48,  2.23it/s]

[I 2025-11-10 17:49:16,038] Trial 92 pruned.

Best trial: 29. Best value: 0.634854:  46%|████▋     | 93/200 [01:11<00:56,  1.89it/s]

[I 2025-11-10 17:49:16,751] Trial 94 pruned.

Best trial: 29. Best value: 0.634854:  47%|████▋     | 94/200 [01:11<00:51,  2.05it/s]

[I 2025-11-10 17:49:17,146] Trial 87 finished with value: 0.557504873294347 and parameters: {'max_depth': 6, 'learning_rate': 0.014087275495193981, 'n_estimators': 812, 'subsample': 0.7244441379148933, 'colsample_bytree': 0.5727855083042164, 'min_child_weight': 1, 'gamma': 3.8253720829576814, 'reg_alpha': 9.398323649166196e-05, 'reg_lambda': 1.208685593087306, 'max_delta_step': 6}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  48%|████▊     | 95/200 [01:12<01:00,  1.74it/s]

[I 2025-11-10 17:49:17,919] Trial 96 pruned.

Best trial: 29. Best value: 0.634854:  48%|████▊     | 96/200 [01:13<01:02,  1.66it/s]

[I 2025-11-10 17:49:18,592] Trial 95 pruned.

Best trial: 29. Best value: 0.634854:  48%|████▊     | 97/200 [01:13<00:56,  1.84it/s]

[I 2025-11-10 17:49:19,001] Trial 98 pruned.

Best trial: 29. Best value: 0.634854:  49%|████▉     | 98/200 [01:14<00:50,  2.01it/s]

[I 2025-11-10 17:49:19,387] Trial 97 pruned.

Best trial: 29. Best value: 0.634854:  50%|████▉     | 99/200 [01:14<00:45,  2.23it/s]

[I 2025-11-10 17:49:19,716] Trial 99 pruned.

Best trial: 29. Best value: 0.634854:  50%|█████     | 100/200 [01:14<00:39,  2.50it/s]

[I 2025-11-10 17:49:20,006] Trial 93 finished with value: 0.5860233918128654 and parameters: {'max_depth': 6, 'learning_rate': 0.020646931891593365, 'n_estimators': 906, 'subsample': 0.714095370761338, 'colsample_bytree': 0.5422335644319866, 'min_child_weight': 2, 'gamma': 3.6360086348086273, 'reg_alpha': 0.17817912350104614, 'reg_lambda': 4.381404770082672, 'max_delta_step': 4}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  50%|█████     | 101/200 [01:15<00:42,  2.33it/s]

[I 2025-11-10 17:49:20,507] Trial 100 pruned.

Best trial: 29. Best value: 0.634854:  51%|█████     | 102/200 [01:15<00:42,  2.29it/s]

[I 2025-11-10 17:49:20,959] Trial 101 pruned.

Best trial: 29. Best value: 0.634854:  52%|█████▏    | 103/200 [01:19<02:13,  1.38s/it]

[I 2025-11-10 17:49:24,543] Trial 104 finished with value: 0.6256237816764132 and parameters: {'max_depth': 5, 'learning_rate': 0.024380501315411317, 'n_estimators': 762, 'subsample': 0.748463028667105, 'colsample_bytree': 0.5887131297342604, 'min_child_weight': 1, 'gamma': 4.020282183714686, 'reg_alpha': 0.06552921108070703, 'reg_lambda': 6.250822418563563, 'max_delta_step': 3}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  52%|█████▏    | 104/200 [01:19<01:47,  1.12s/it]

[I 2025-11-10 17:49:25,048] Trial 105 finished with value: 0.5940740740740741 and parameters: {'max_depth': 5, 'learning_rate': 0.023077997958307846, 'n_estimators': 753, 'subsample': 0.7150006312029576, 'colsample_bytree': 0.5867455809081642, 'min_child_weight': 1, 'gamma': 3.489425080761136, 'reg_alpha': 0.007643230552035496, 'reg_lambda': 5.683718921414421, 'max_delta_step': 4}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  52%|█████▎    | 105/200 [01:20<01:48,  1.14s/it]

[I 2025-11-10 17:49:26,242] Trial 106 pruned.

Best trial: 29. Best value: 0.634854:  54%|█████▍    | 108/200 [01:21<00:48,  1.91it/s]

[I 2025-11-10 17:49:26,581] Trial 103 finished with value: 0.5483820662768031 and parameters: {'max_depth': 9, 'learning_rate': 0.05105596243314254, 'n_estimators': 1280, 'subsample': 0.6696358482601382, 'colsample_bytree': 0.5832613240143986, 'min_child_weight': 1, 'gamma': 2.797716102927147, 'reg_alpha': 0.054543332576974024, 'reg_lambda': 0.10327794999634338, 'max_delta_step': 7}. Best is trial 29 with value: 0.6348538011695906.
[I 2025-11-10 17:49:26,601] Trial 107 pruned.
[I 2025-11-10 17:49:26,747] Trial 102 finished with value: 0.5508576998050682 and parameters: {'max_depth': 9, 'learning_rate': 0.06820288761935608, 'n_estimators': 1239, 'subsample': 0.7669565853059843, 'colsample_bytree': 0.6294484741830275, 'min_child_weight': 1, 'gamma': 4.007689529682576, 'reg_alpha': 0.19331663271858943, 'reg_lambda': 0.0031097306732926744, 'max_delta_step': 1}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  55%|█████▍    | 109/200 [01:22<00:52,  1.73it/s]

[I 2025-11-10 17:49:27,499] Trial 109 pruned.

Best trial: 29. Best value: 0.634854:  55%|█████▌    | 110/200 [01:22<00:53,  1.69it/s]

[I 2025-11-10 17:49:28,130] Trial 108 pruned.

Best trial: 29. Best value: 0.634854:  56%|█████▌    | 111/200 [01:23<00:58,  1.52it/s]

[I 2025-11-10 17:49:28,967] Trial 113 pruned.

Best trial: 29. Best value: 0.634854:  56%|█████▌    | 112/200 [01:25<01:15,  1.17it/s]

[I 2025-11-10 17:49:30,324] Trial 114 pruned.

Best trial: 29. Best value: 0.634854:  56%|█████▋    | 113/200 [01:25<00:59,  1.46it/s]

[I 2025-11-10 17:49:30,585] Trial 110 finished with value: 0.5641910331384016 and parameters: {'max_depth': 3, 'learning_rate': 0.023045488286219426, 'n_estimators': 622, 'subsample': 0.7782970700941212, 'colsample_bytree': 0.5659838330857225, 'min_child_weight': 1, 'gamma': 3.009904030679901, 'reg_alpha': 0.09237204564508954, 'reg_lambda': 1.9888148685716585, 'max_delta_step': 4}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  57%|█████▋    | 114/200 [01:25<00:56,  1.51it/s]

[I 2025-11-10 17:49:31,184] Trial 111 finished with value: 0.551345029239766 and parameters: {'max_depth': 4, 'learning_rate': 0.022791938250624873, 'n_estimators': 721, 'subsample': 0.77893763840608, 'colsample_bytree': 0.56459620248822, 'min_child_weight': 1, 'gamma': 2.971530000466447, 'reg_alpha': 0.02475171863770591, 'reg_lambda': 1.948394490338257, 'max_delta_step': 4}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  57%|█████▊    | 115/200 [01:26<00:51,  1.66it/s]

[I 2025-11-10 17:49:31,641] Trial 112 finished with value: 0.5393567251461987 and parameters: {'max_depth': 3, 'learning_rate': 0.015951673778800503, 'n_estimators': 595, 'subsample': 0.6965786659342924, 'colsample_bytree': 0.6484180708201245, 'min_child_weight': 1, 'gamma': 3.3361638574549404, 'reg_alpha': 0.004188345702971457, 'reg_lambda': 0.7538518035854468, 'max_delta_step': 4}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  58%|█████▊    | 116/200 [01:27<00:55,  1.51it/s]

[I 2025-11-10 17:49:32,447] Trial 118 pruned.

Best trial: 29. Best value: 0.634854:  58%|█████▊    | 117/200 [01:27<00:52,  1.57it/s]

[I 2025-11-10 17:49:33,028] Trial 117 pruned.

Best trial: 29. Best value: 0.634854:  59%|█████▉    | 118/200 [01:28<00:54,  1.49it/s]

[I 2025-11-10 17:49:33,774] Trial 119 pruned.

Best trial: 29. Best value: 0.634854:  60%|█████▉    | 119/200 [01:30<01:21,  1.01s/it]

[I 2025-11-10 17:49:35,576] Trial 120 pruned.

Best trial: 29. Best value: 0.634854:  60%|██████    | 120/200 [01:30<01:02,  1.28it/s]

[I 2025-11-10 17:49:35,825] Trial 115 finished with value: 0.572729044834308 and parameters: {'max_depth': 5, 'learning_rate': 0.011437726739052507, 'n_estimators': 789, 'subsample': 0.8006159273968859, 'colsample_bytree': 0.596059776817936, 'min_child_weight': 1, 'gamma': 3.311055890369245, 'reg_alpha': 0.871121482149259, 'reg_lambda': 0.7819050224751732, 'max_delta_step': 3}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  60%|██████    | 121/200 [01:31<00:58,  1.34it/s]

[I 2025-11-10 17:49:36,480] Trial 122 pruned.

Best trial: 29. Best value: 0.634854:  61%|██████    | 122/200 [01:31<00:57,  1.36it/s]

[I 2025-11-10 17:49:37,197] Trial 116 finished with value: 0.559980506822612 and parameters: {'max_depth': 4, 'learning_rate': 0.016249399875483257, 'n_estimators': 1068, 'subsample': 0.7360530279626047, 'colsample_bytree': 0.5872208299442544, 'min_child_weight': 1, 'gamma': 3.89725126595349, 'reg_alpha': 0.845209613413735, 'reg_lambda': 0.00033909593345279334, 'max_delta_step': 3}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  62%|██████▏   | 123/200 [01:32<00:45,  1.70it/s]

[I 2025-11-10 17:49:37,441] Trial 124 pruned.

Best trial: 29. Best value: 0.634854:  62%|██████▏   | 124/200 [01:33<00:49,  1.52it/s]

[I 2025-11-10 17:49:38,261] Trial 123 pruned.
[I 2025-11-10 17:49:38,299] Trial 126 pruned.

Best trial: 29. Best value: 0.634854:  63%|██████▎   | 126/200 [01:33<00:40,  1.85it/s]

[I 2025-11-10 17:49:39,069] Trial 125 pruned.

Best trial: 29. Best value: 0.634854:  64%|██████▎   | 127/200 [01:34<00:33,  2.17it/s]

[I 2025-11-10 17:49:39,283] Trial 127 pruned.

Best trial: 29. Best value: 0.634854:  64%|██████▍   | 129/200 [01:34<00:30,  2.31it/s]

[I 2025-11-10 17:49:40,023] Trial 130 pruned.
[I 2025-11-10 17:49:40,187] Trial 129 pruned.

Best trial: 29. Best value: 0.634854:  65%|██████▌   | 130/200 [01:35<00:30,  2.30it/s]

[I 2025-11-10 17:49:40,630] Trial 128 pruned.

Best trial: 29. Best value: 0.634854:  66%|██████▌   | 131/200 [01:36<00:50,  1.38it/s]

[I 2025-11-10 17:49:42,084] Trial 121 finished with value: 0.5755555555555556 and parameters: {'max_depth': 5, 'learning_rate': 0.010713865146911842, 'n_estimators': 1328, 'subsample': 0.8723835944757377, 'colsample_bytree': 0.5541292926895197, 'min_child_weight': 1, 'gamma': 3.67722159720533, 'reg_alpha': 1.7483706883392098, 'reg_lambda': 0.000221440657191243, 'max_delta_step': 5}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  66%|██████▌   | 132/200 [01:37<00:38,  1.75it/s]

[I 2025-11-10 17:49:42,272] Trial 132 pruned.

Best trial: 29. Best value: 0.634854:  66%|██████▋   | 133/200 [01:37<00:32,  2.07it/s]

[I 2025-11-10 17:49:42,543] Trial 133 pruned.
[I 2025-11-10 17:49:42,600] Trial 131 pruned.

Best trial: 29. Best value: 0.634854:  68%|██████▊   | 135/200 [01:38<00:34,  1.87it/s]

[I 2025-11-10 17:49:43,740] Trial 137 pruned.

Best trial: 29. Best value: 0.634854:  68%|██████▊   | 136/200 [01:39<00:42,  1.50it/s]

[I 2025-11-10 17:49:44,804] Trial 135 pruned.

Best trial: 29. Best value: 0.634854:  68%|██████▊   | 137/200 [01:39<00:35,  1.77it/s]

[I 2025-11-10 17:49:45,078] Trial 136 pruned.

Best trial: 29. Best value: 0.634854:  69%|██████▉   | 138/200 [01:40<00:41,  1.50it/s]

[I 2025-11-10 17:49:46,022] Trial 138 pruned.

Best trial: 29. Best value: 0.634854:  70%|██████▉   | 139/200 [01:41<00:41,  1.48it/s]

[I 2025-11-10 17:49:46,725] Trial 141 pruned.

Best trial: 29. Best value: 0.634854:  70%|███████   | 140/200 [01:42<00:41,  1.43it/s]

[I 2025-11-10 17:49:47,482] Trial 139 pruned.

Best trial: 29. Best value: 0.634854:  71%|███████   | 142/200 [01:42<00:28,  2.04it/s]

[I 2025-11-10 17:49:47,959] Trial 142 pruned.
[I 2025-11-10 17:49:48,100] Trial 134 finished with value: 0.6246101364522416 and parameters: {'max_depth': 4, 'learning_rate': 0.018447913506319365, 'n_estimators': 1105, 'subsample': 0.689167674963391, 'colsample_bytree': 0.5429432819756108, 'min_child_weight': 1, 'gamma': 3.9649095023430547, 'reg_alpha': 0.0001569243578614687, 'reg_lambda': 6.06858912175443, 'max_delta_step': 0}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  72%|███████▏  | 143/200 [01:43<00:27,  2.07it/s]

[I 2025-11-10 17:49:48,564] Trial 144 pruned.

Best trial: 29. Best value: 0.634854:  72%|███████▏  | 144/200 [01:43<00:22,  2.54it/s]

[I 2025-11-10 17:49:48,748] Trial 143 pruned.

Best trial: 29. Best value: 0.634854:  72%|███████▎  | 145/200 [01:44<00:25,  2.16it/s]

[I 2025-11-10 17:49:49,373] Trial 145 pruned.

Best trial: 29. Best value: 0.634854:  73%|███████▎  | 146/200 [01:44<00:25,  2.08it/s]

[I 2025-11-10 17:49:49,898] Trial 147 pruned.

Best trial: 29. Best value: 0.634854:  74%|███████▎  | 147/200 [01:45<00:36,  1.46it/s]

[I 2025-11-10 17:49:51,053] Trial 149 pruned.

Best trial: 29. Best value: 0.634854:  74%|███████▍  | 148/200 [01:46<00:29,  1.76it/s]

[I 2025-11-10 17:49:51,349] Trial 140 finished with value: 0.5455360623781677 and parameters: {'max_depth': 10, 'learning_rate': 0.13912370999770007, 'n_estimators': 1094, 'subsample': 0.7335901607625769, 'colsample_bytree': 0.6146977705307519, 'min_child_weight': 1, 'gamma': 4.00814059422294, 'reg_alpha': 6.215345182643734e-06, 'reg_lambda': 0.5395394562971744, 'max_delta_step': 1}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  74%|███████▍  | 149/200 [01:46<00:30,  1.66it/s]

[I 2025-11-10 17:49:52,030] Trial 151 pruned.

Best trial: 29. Best value: 0.634854:  75%|███████▌  | 150/200 [01:48<00:41,  1.20it/s]

[I 2025-11-10 17:49:53,400] Trial 152 pruned.

Best trial: 29. Best value: 0.634854:  76%|███████▌  | 152/200 [01:49<00:35,  1.34it/s]

[I 2025-11-10 17:49:54,843] Trial 146 finished with value: 0.5522222222222222 and parameters: {'max_depth': 4, 'learning_rate': 0.019306975356795982, 'n_estimators': 1105, 'subsample': 0.6752071725493916, 'colsample_bytree': 0.5523873468171931, 'min_child_weight': 1, 'gamma': 3.9860208365897254, 'reg_alpha': 0.00025729600773362934, 'reg_lambda': 0.0005272725310737085, 'max_delta_step': 0}. Best is trial 29 with value: 0.6348538011695906.
[I 2025-11-10 17:49:54,965] Trial 148 finished with value: 0.6243957115009746 and parameters: {'max_depth': 4, 'learning_rate': 0.021893511042036372, 'n_estimators': 1038, 'subsample': 0.6941588488535236, 'colsample_bytree': 0.5372837911078789, 'min_child_weight': 1, 'gamma': 4.18769094169712, 'reg_alpha': 0.00045775632862050914, 'reg_lambda': 5.318657121585141, 'max_delta_step': 0}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  76%|███████▋  | 153/200 [01:50<00:31,  1.50it/s]

[I 2025-11-10 17:49:55,446] Trial 154 pruned.

Best trial: 29. Best value: 0.634854:  78%|███████▊  | 155/200 [01:50<00:22,  2.03it/s]

[I 2025-11-10 17:49:56,041] Trial 150 finished with value: 0.5443079922027291 and parameters: {'max_depth': 4, 'learning_rate': 0.02161872341829443, 'n_estimators': 683, 'subsample': 0.735210283741049, 'colsample_bytree': 0.7110426741162251, 'min_child_weight': 1, 'gamma': 3.0990430009327343, 'reg_alpha': 0.0001805653361423978, 'reg_lambda': 0.6674198267125961, 'max_delta_step': 3}. Best is trial 29 with value: 0.6348538011695906.
[I 2025-11-10 17:49:56,180] Trial 155 pruned.

Best trial: 29. Best value: 0.634854:  78%|███████▊  | 156/200 [01:51<00:18,  2.42it/s]

[I 2025-11-10 17:49:56,408] Trial 153 pruned.

Best trial: 29. Best value: 0.634854:  78%|███████▊  | 157/200 [01:51<00:16,  2.67it/s]

[I 2025-11-10 17:49:56,691] Trial 156 pruned.

Best trial: 29. Best value: 0.634854:  79%|███████▉  | 158/200 [01:52<00:19,  2.20it/s]

[I 2025-11-10 17:49:57,333] Trial 158 pruned.

Best trial: 29. Best value: 0.634854:  80%|████████  | 160/200 [01:52<00:13,  3.04it/s]

[I 2025-11-10 17:49:57,631] Trial 159 pruned.
[I 2025-11-10 17:49:57,772] Trial 160 pruned.

Best trial: 29. Best value: 0.634854:  80%|████████  | 161/200 [01:53<00:16,  2.33it/s]

[I 2025-11-10 17:49:58,439] Trial 157 pruned.
[I 2025-11-10 17:49:58,518] Trial 161 pruned.

Best trial: 29. Best value: 0.634854:  82%|████████▏ | 163/200 [01:53<00:10,  3.48it/s]

[I 2025-11-10 17:49:58,684] Trial 162 pruned.

Best trial: 29. Best value: 0.634854:  82%|████████▏ | 164/200 [01:53<00:09,  3.71it/s]

[I 2025-11-10 17:49:58,900] Trial 164 pruned.
[I 2025-11-10 17:49:58,925] Trial 163 pruned.

Best trial: 29. Best value: 0.634854:  83%|████████▎ | 166/200 [01:53<00:07,  4.71it/s]

[I 2025-11-10 17:49:59,161] Trial 166 pruned.

Best trial: 29. Best value: 0.634854:  84%|████████▎ | 167/200 [01:54<00:08,  3.81it/s]

[I 2025-11-10 17:49:59,592] Trial 165 pruned.

Best trial: 29. Best value: 0.634854:  84%|████████▍ | 169/200 [01:55<00:08,  3.49it/s]

[I 2025-11-10 17:50:00,164] Trial 167 pruned.
[I 2025-11-10 17:50:00,304] Trial 170 pruned.

Best trial: 29. Best value: 0.634854:  86%|████████▌ | 171/200 [01:55<00:06,  4.65it/s]

[I 2025-11-10 17:50:00,449] Trial 168 pruned.
[I 2025-11-10 17:50:00,579] Trial 169 pruned.

Best trial: 29. Best value: 0.634854:  86%|████████▌ | 172/200 [01:56<00:10,  2.65it/s]

[I 2025-11-10 17:50:01,362] Trial 174 pruned.

Best trial: 29. Best value: 0.634854:  87%|████████▋ | 174/200 [01:56<00:07,  3.60it/s]

[I 2025-11-10 17:50:01,610] Trial 171 pruned.
[I 2025-11-10 17:50:01,739] Trial 172 pruned.

Best trial: 29. Best value: 0.634854:  88%|████████▊ | 175/200 [01:57<00:10,  2.28it/s]

[I 2025-11-10 17:50:02,553] Trial 175 pruned.
[I 2025-11-10 17:50:02,554] Trial 173 pruned.

Best trial: 29. Best value: 0.634854:  88%|████████▊ | 177/200 [01:57<00:06,  3.31it/s]

[I 2025-11-10 17:50:02,841] Trial 176 pruned.

Best trial: 29. Best value: 0.634854:  90%|████████▉ | 179/200 [01:58<00:07,  2.88it/s]

[I 2025-11-10 17:50:03,613] Trial 179 pruned.
[I 2025-11-10 17:50:03,756] Trial 177 pruned.

Best trial: 29. Best value: 0.634854:  90%|█████████ | 180/200 [01:59<00:08,  2.38it/s]

[I 2025-11-10 17:50:04,374] Trial 178 pruned.

Best trial: 29. Best value: 0.634854:  90%|█████████ | 181/200 [01:59<00:10,  1.90it/s]

[I 2025-11-10 17:50:05,178] Trial 182 pruned.

Best trial: 29. Best value: 0.634854:  91%|█████████ | 182/200 [02:00<00:07,  2.30it/s]

[I 2025-11-10 17:50:05,380] Trial 181 pruned.
[I 2025-11-10 17:50:05,409] Trial 180 finished with value: 0.552943469785575 and parameters: {'max_depth': 7, 'learning_rate': 0.061228426818245855, 'n_estimators': 425, 'subsample': 0.7551695381779552, 'colsample_bytree': 0.5430146104564625, 'min_child_weight': 1, 'gamma': 4.844644212875848, 'reg_alpha': 0.8440471814758974, 'reg_lambda': 0.0021955091689074015, 'max_delta_step': 5}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  92%|█████████▏| 184/200 [02:00<00:04,  3.40it/s]

[I 2025-11-10 17:50:05,625] Trial 183 pruned.

Best trial: 29. Best value: 0.634854:  92%|█████████▎| 185/200 [02:01<00:05,  2.53it/s]

[I 2025-11-10 17:50:06,334] Trial 184 pruned.

Best trial: 29. Best value: 0.634854:  93%|█████████▎| 186/200 [02:01<00:04,  2.81it/s]

[I 2025-11-10 17:50:06,576] Trial 186 pruned.
[I 2025-11-10 17:50:06,600] Trial 185 pruned.

Best trial: 29. Best value: 0.634854:  94%|█████████▍| 188/200 [02:01<00:03,  3.62it/s]

[I 2025-11-10 17:50:06,914] Trial 187 pruned.

Best trial: 29. Best value: 0.634854:  94%|█████████▍| 189/200 [02:02<00:04,  2.40it/s]

[I 2025-11-10 17:50:07,795] Trial 188 pruned.

Best trial: 29. Best value: 0.634854:  95%|█████████▌| 190/200 [02:03<00:06,  1.54it/s]

[I 2025-11-10 17:50:09,152] Trial 192 pruned.

Best trial: 29. Best value: 0.634854:  96%|█████████▌| 191/200 [02:04<00:06,  1.35it/s]

[I 2025-11-10 17:50:10,152] Trial 193 pruned.

Best trial: 29. Best value: 0.634854:  96%|█████████▌| 192/200 [02:06<00:06,  1.15it/s]

[I 2025-11-10 17:50:11,364] Trial 194 pruned.

Best trial: 29. Best value: 0.634854:  96%|█████████▋| 193/200 [02:06<00:06,  1.15it/s]

[I 2025-11-10 17:50:12,217] Trial 191 finished with value: 0.5445029239766082 and parameters: {'max_depth': 10, 'learning_rate': 0.18272888334088866, 'n_estimators': 1167, 'subsample': 0.6037229761552753, 'colsample_bytree': 0.5808966625906055, 'min_child_weight': 2, 'gamma': 4.287179078464265, 'reg_alpha': 0.015058762273638983, 'reg_lambda': 6.882056983464303, 'max_delta_step': 4}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  97%|█████████▋| 194/200 [02:07<00:04,  1.47it/s]

[I 2025-11-10 17:50:12,428] Trial 195 pruned.

Best trial: 29. Best value: 0.634854:  98%|█████████▊| 195/200 [02:07<00:03,  1.57it/s]

[I 2025-11-10 17:50:12,962] Trial 190 finished with value: 0.5704873294346978 and parameters: {'max_depth': 10, 'learning_rate': 0.023481375041396923, 'n_estimators': 1024, 'subsample': 0.8288274292731144, 'colsample_bytree': 0.5766112899777004, 'min_child_weight': 1, 'gamma': 3.490132371347452, 'reg_alpha': 0.14453933267125235, 'reg_lambda': 0.40139413128448415, 'max_delta_step': 4}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  98%|█████████▊| 196/200 [02:08<00:02,  1.51it/s]

[I 2025-11-10 17:50:13,690] Trial 189 finished with value: 0.576803118908382 and parameters: {'max_depth': 10, 'learning_rate': 0.030115017516175402, 'n_estimators': 1195, 'subsample': 0.8278851024130454, 'colsample_bytree': 0.5772542422113092, 'min_child_weight': 1, 'gamma': 4.261123031122546, 'reg_alpha': 0.17803342845239578, 'reg_lambda': 0.2998557783010392, 'max_delta_step': 3}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854:  99%|█████████▉| 198/200 [02:10<00:01,  1.18it/s]

[I 2025-11-10 17:50:15,983] Trial 199 pruned.
[I 2025-11-10 17:50:16,138] Trial 196 pruned.

Best trial: 29. Best value: 0.634854: 100%|█████████▉| 199/200 [02:13<00:01,  1.46s/it]

[I 2025-11-10 17:50:19,045] Trial 197 finished with value: 0.5635672514619883 and parameters: {'max_depth': 5, 'learning_rate': 0.02334486647083389, 'n_estimators': 1113, 'subsample': 0.8681836319956068, 'colsample_bytree': 0.5495702839081404, 'min_child_weight': 1, 'gamma': 3.8361949183699924, 'reg_alpha': 1.0806683616831019, 'reg_lambda': 0.0011588665775150771, 'max_delta_step': 5}. Best is trial 29 with value: 0.6348538011695906.

Best trial: 29. Best value: 0.634854: 100%|██████████| 200/200 [02:15<00:00,  1.48it/s]

[I 2025-11-10 17:50:20,276] Trial 198 finished with value: 0.5633333333333332 and parameters: {'max_depth': 5, 'learning_rate': 0.017594505700182606, 'n_estimators': 1337, 'subsample': 0.866004494678384, 'colsample_bytree': 0.5509653081891946, 'min_child_weight': 1, 'gamma': 3.7958283366176993, 'reg_alpha': 0.0001242986431173566, 'reg_lambda': 0.0685599608754002, 'max_delta_step': 7}. Best is trial 29 with value: 0.6348538011695906.

C:\Users\tenNovy\AppData\Local\Temp\ipykernel_11656\1094786132.py:137: RuntimeWarning:

More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.

[I 2025-11-10 17:50:21,834] A new study created in memory with name: 18_1_roc_auc
Best trial: 1. Best value: 0.5:   0%|          | 1/200 [00:02<07:45,  2.34s/it]

[I 2025-11-10 17:50:24,174] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.13362756165174705, 'n_estimators': 562, 'subsample': 0.9250182163798123, 'colsample_bytree': 0.9902565165727223, 'min_child_weight': 7, 'gamma': 3.9575656641392913, 'reg_alpha': 0.0020682637787719743, 'reg_lambda': 6.513632409770989e-05, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   1%|          | 2/200 [00:03<05:34,  1.69s/it]

[I 2025-11-10 17:50:25,409] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.07433324549090593, 'n_estimators': 936, 'subsample': 0.8616495825233367, 'colsample_bytree': 0.8503703589159, 'min_child_weight': 6, 'gamma': 1.5375540456964014, 'reg_alpha': 0.005619393228860804, 'reg_lambda': 0.030806891891655794, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   2%|▏         | 3/200 [00:04<04:21,  1.33s/it]

[I 2025-11-10 17:50:26,309] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.015756706064893947, 'n_estimators': 1137, 'subsample': 0.5204395775644062, 'colsample_bytree': 0.9817135158644682, 'min_child_weight': 10, 'gamma': 4.97562018584356, 'reg_alpha': 0.9742667396857649, 'reg_lambda': 1.1148562546071787e-05, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 2. Best value: 0.672261:   2%|▏         | 4/200 [00:04<03:17,  1.01s/it]

[I 2025-11-10 17:50:26,818] Trial 2 finished with value: 0.672261208576998 and parameters: {'max_depth': 6, 'learning_rate': 0.020923384162521385, 'n_estimators': 713, 'subsample': 0.6409560642863583, 'colsample_bytree': 0.8027955069417135, 'min_child_weight': 1, 'gamma': 3.122652857367132, 'reg_alpha': 0.00011572123034556304, 'reg_lambda': 0.0018330503572023358, 'max_delta_step': 9}. Best is trial 2 with value: 0.672261208576998.

Best trial: 2. Best value: 0.672261:   2%|▎         | 5/200 [00:06<03:27,  1.06s/it]

[I 2025-11-10 17:50:27,982] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.09161600770509015, 'n_estimators': 932, 'subsample': 0.9376031952892673, 'colsample_bytree': 0.8728110398153455, 'min_child_weight': 9, 'gamma': 4.72554542375946, 'reg_alpha': 0.0006416332285131064, 'reg_lambda': 9.605569161975501e-05, 'max_delta_step': 3}. Best is trial 2 with value: 0.672261208576998.

Best trial: 2. Best value: 0.672261:   3%|▎         | 6/200 [00:06<02:56,  1.10it/s]

[I 2025-11-10 17:50:28,591] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02058540680868768, 'n_estimators': 836, 'subsample': 0.759620730507548, 'colsample_bytree': 0.5264474654194272, 'min_child_weight': 7, 'gamma': 1.2150443899043823, 'reg_alpha': 0.08856364805185846, 'reg_lambda': 0.03848561787742895, 'max_delta_step': 2}. Best is trial 2 with value: 0.672261208576998.

Best trial: 2. Best value: 0.672261:   4%|▎         | 7/200 [00:09<04:40,  1.45s/it]

[I 2025-11-10 17:50:31,160] Trial 6 finished with value: 0.5998830409356726 and parameters: {'max_depth': 10, 'learning_rate': 0.04373417420423136, 'n_estimators': 1254, 'subsample': 0.9870684607319107, 'colsample_bytree': 0.5021229976978749, 'min_child_weight': 5, 'gamma': 0.47029633024635753, 'reg_alpha': 0.000325373518176417, 'reg_lambda': 1.964510466520971e-06, 'max_delta_step': 7}. Best is trial 2 with value: 0.672261208576998.

Best trial: 2. Best value: 0.672261:   4%|▍         | 9/200 [00:09<02:26,  1.30it/s]

[I 2025-11-10 17:50:31,358] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.030194409932691225, 'n_estimators': 1179, 'subsample': 0.7121255374949597, 'colsample_bytree': 0.6063235385418817, 'min_child_weight': 10, 'gamma': 3.879810980055179, 'reg_alpha': 2.994109271405892e-06, 'reg_lambda': 0.0003394652107054123, 'max_delta_step': 6}. Best is trial 2 with value: 0.672261208576998.
[I 2025-11-10 17:50:31,502] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09996651930341574, 'n_estimators': 745, 'subsample': 0.9892212498118818, 'colsample_bytree': 0.6333798973166229, 'min_child_weight': 7, 'gamma': 4.8980400826636075, 'reg_alpha': 2.843771394956174e-06, 'reg_lambda': 4.0179834095974147e-08, 'max_delta_step': 8}. Best is trial 2 with value: 0.672261208576998.

Best trial: 2. Best value: 0.672261:   5%|▌         | 10/200 [00:12<03:58,  1.25s/it]

[I 2025-11-10 17:50:33,843] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.16914317182970087, 'n_estimators': 1486, 'subsample': 0.5557358023072083, 'colsample_bytree': 0.7101835277898996, 'min_child_weight': 10, 'gamma': 1.6019107917717084, 'reg_alpha': 2.0268025619251278e-05, 'reg_lambda': 0.002587899278468256, 'max_delta_step': 10}. Best is trial 2 with value: 0.672261208576998.
[I 2025-11-10 17:50:33,915] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.013854968762116775, 'n_estimators': 667, 'subsample': 0.652609608187795, 'colsample_bytree': 0.8022958918356523, 'min_child_weight': 10, 'gamma': 4.137154990408243, 'reg_alpha': 1.1107654244295303e-05, 'reg_lambda': 1.1101468621602406e-06, 'max_delta_step': 10}. Best is trial 2 with value: 0.672261208576998.

Best trial: 2. Best value: 0.672261:   6%|▌         | 12/200 [00:12<02:26,  1.28it/s]

[I 2025-11-10 17:50:34,330] Trial 13 pruned.

Best trial: 2. Best value: 0.672261:   6%|▋         | 13/200 [00:12<02:02,  1.53it/s]

[I 2025-11-10 17:50:34,601] Trial 14 pruned.

Best trial: 2. Best value: 0.672261:   7%|▋         | 14/200 [00:13<02:25,  1.28it/s]

[I 2025-11-10 17:50:35,740] Trial 16 pruned.

Best trial: 2. Best value: 0.672261:   8%|▊         | 16/200 [00:14<01:35,  1.92it/s]

[I 2025-11-10 17:50:36,092] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03859595709874061, 'n_estimators': 1178, 'subsample': 0.7220322344701249, 'colsample_bytree': 0.552786455629036, 'min_child_weight': 8, 'gamma': 2.323134424789799, 'reg_alpha': 0.002810114875579205, 'reg_lambda': 0.00016504947796126864, 'max_delta_step': 4}. Best is trial 2 with value: 0.672261208576998.
[I 2025-11-10 17:50:36,245] Trial 17 pruned.

Best trial: 2. Best value: 0.672261:   8%|▊         | 17/200 [00:14<01:26,  2.13it/s]

[I 2025-11-10 17:50:36,589] Trial 18 pruned.

Best trial: 2. Best value: 0.672261:   9%|▉         | 18/200 [00:15<01:34,  1.93it/s]

[I 2025-11-10 17:50:37,223] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.01841976771970835, 'n_estimators': 1434, 'subsample': 0.8493047417776619, 'colsample_bytree': 0.7881926071050295, 'min_child_weight': 6, 'gamma': 4.740377236360855, 'reg_alpha': 0.006540686758480386, 'reg_lambda': 6.608855576093516e-05, 'max_delta_step': 4}. Best is trial 2 with value: 0.672261208576998.

Best trial: 2. Best value: 0.672261:  10%|▉         | 19/200 [00:15<01:25,  2.11it/s]

[I 2025-11-10 17:50:37,595] Trial 19 pruned.

Best trial: 2. Best value: 0.672261:  10%|█         | 20/200 [00:16<01:30,  1.98it/s]

[I 2025-11-10 17:50:38,166] Trial 21 pruned.

Best trial: 2. Best value: 0.672261:  10%|█         | 21/200 [00:16<01:18,  2.28it/s]

[I 2025-11-10 17:50:38,454] Trial 22 pruned.

Best trial: 2. Best value: 0.672261:  11%|█         | 22/200 [00:17<01:54,  1.56it/s]

[I 2025-11-10 17:50:39,573] Trial 24 pruned.

Best trial: 2. Best value: 0.672261:  12%|█▏        | 23/200 [00:18<02:00,  1.47it/s]

[I 2025-11-10 17:50:40,344] Trial 25 pruned.

Best trial: 15. Best value: 0.674776:  12%|█▏        | 24/200 [00:20<02:52,  1.02it/s]

[I 2025-11-10 17:50:42,021] Trial 15 finished with value: 0.6747758284600389 and parameters: {'max_depth': 8, 'learning_rate': 0.040592022223309314, 'n_estimators': 1464, 'subsample': 0.7756540956759804, 'colsample_bytree': 0.5042438930144886, 'min_child_weight': 1, 'gamma': 0.13567302037209528, 'reg_alpha': 0.00020281782604544713, 'reg_lambda': 4.946731331700003e-07, 'max_delta_step': 5}. Best is trial 15 with value: 0.6747758284600389.

Best trial: 15. Best value: 0.674776:  12%|█▎        | 25/200 [00:21<02:49,  1.03it/s]

[I 2025-11-10 17:50:42,975] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.04928812127092026, 'n_estimators': 641, 'subsample': 0.910917115589702, 'colsample_bytree': 0.7553367863101705, 'min_child_weight': 6, 'gamma': 1.8816756968612762, 'reg_alpha': 0.021117533655562466, 'reg_lambda': 0.0034985300672278757, 'max_delta_step': 6}. Best is trial 15 with value: 0.6747758284600389.
[I 2025-11-10 17:50:43,001] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.27476587467159747, 'n_estimators': 1469, 'subsample': 0.5906225902666069, 'colsample_bytree': 0.9072098071805565, 'min_child_weight': 3, 'gamma': 3.125379648175597, 'reg_alpha': 6.170226246781002, 'reg_lambda': 1.7138603528225444e-08, 'max_delta_step': 9}. Best is trial 15 with value: 0.6747758284600389.

Best trial: 15. Best value: 0.674776:  14%|█▎        | 27/200 [00:21<01:42,  1.69it/s]

[I 2025-11-10 17:50:43,265] Trial 27 pruned.

Best trial: 15. Best value: 0.674776:  14%|█▍        | 28/200 [00:21<01:33,  1.85it/s]

[I 2025-11-10 17:50:43,658] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.030430683279556087, 'n_estimators': 1306, 'subsample': 0.6702816271742891, 'colsample_bytree': 0.9218375511701319, 'min_child_weight': 5, 'gamma': 2.115773582869229, 'reg_alpha': 6.879123429044574, 'reg_lambda': 0.002423084429315454, 'max_delta_step': 6}. Best is trial 15 with value: 0.6747758284600389.

Best trial: 15. Best value: 0.674776:  14%|█▍        | 29/200 [00:22<01:40,  1.71it/s]

[I 2025-11-10 17:50:44,369] Trial 28 pruned.

Best trial: 15. Best value: 0.674776:  15%|█▌        | 30/200 [00:23<01:42,  1.65it/s]

[I 2025-11-10 17:50:45,019] Trial 29 pruned.

Best trial: 15. Best value: 0.674776:  16%|█▌        | 31/200 [00:23<01:41,  1.67it/s]

[I 2025-11-10 17:50:45,608] Trial 31 pruned.

Best trial: 15. Best value: 0.674776:  16%|█▌        | 32/200 [00:24<01:53,  1.48it/s]

[I 2025-11-10 17:50:46,470] Trial 32 pruned.

Best trial: 15. Best value: 0.674776:  16%|█▋        | 33/200 [00:27<03:52,  1.39s/it]

[I 2025-11-10 17:50:49,619] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.13399103811254814, 'n_estimators': 1053, 'subsample': 0.7842713887734094, 'colsample_bytree': 0.8338432669342081, 'min_child_weight': 8, 'gamma': 1.28766474401277, 'reg_alpha': 0.002096173009584749, 'reg_lambda': 0.0005480240166865692, 'max_delta_step': 4}. Best is trial 15 with value: 0.6747758284600389.

Best trial: 15. Best value: 0.674776:  17%|█▋        | 34/200 [00:28<03:16,  1.19s/it]

[I 2025-11-10 17:50:50,312] Trial 36 pruned.

Best trial: 15. Best value: 0.674776:  18%|█▊        | 36/200 [00:28<01:51,  1.47it/s]

[I 2025-11-10 17:50:50,515] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07209849582852096, 'n_estimators': 1041, 'subsample': 0.862753015001424, 'colsample_bytree': 0.8404499400728042, 'min_child_weight': 8, 'gamma': 1.2364374384007086, 'reg_alpha': 0.0020024099132010813, 'reg_lambda': 0.01782335452892857, 'max_delta_step': 7}. Best is trial 15 with value: 0.6747758284600389.
[I 2025-11-10 17:50:50,683] Trial 30 finished with value: 0.6635282651072125 and parameters: {'max_depth': 7, 'learning_rate': 0.03237239536523015, 'n_estimators': 1322, 'subsample': 0.7966799533083514, 'colsample_bytree': 0.5008201344318611, 'min_child_weight': 1, 'gamma': 0.6549968640795552, 'reg_alpha': 1.5531037282116587e-05, 'reg_lambda': 1.9461861208447375e-07, 'max_delta_step': 2}. Best is trial 15 with value: 0.6747758284600389.

Best trial: 33. Best value: 0.688596:  18%|█▊        | 37/200 [00:30<02:17,  1.19it/s]

[I 2025-11-10 17:50:51,910] Trial 33 finished with value: 0.6885964912280701 and parameters: {'max_depth': 7, 'learning_rate': 0.024924604949742007, 'n_estimators': 1060, 'subsample': 0.8044270095799954, 'colsample_bytree': 0.6328547322600396, 'min_child_weight': 1, 'gamma': 1.2008934280528305, 'reg_alpha': 2.09673616090544e-05, 'reg_lambda': 2.167826599836453e-05, 'max_delta_step': 4}. Best is trial 33 with value: 0.6885964912280701.

Best trial: 33. Best value: 0.688596:  19%|█▉        | 38/200 [00:32<03:15,  1.21s/it]

[I 2025-11-10 17:50:53,975] Trial 37 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.06606367749872757, 'n_estimators': 928, 'subsample': 0.853761362818311, 'colsample_bytree': 0.8403655862899743, 'min_child_weight': 6, 'gamma': 0.04270137606609352, 'reg_alpha': 0.021798299577066017, 'reg_lambda': 0.04210529776872364, 'max_delta_step': 7}. Best is trial 33 with value: 0.6885964912280701.

Best trial: 33. Best value: 0.688596:  20%|█▉        | 39/200 [00:32<02:27,  1.09it/s]

[I 2025-11-10 17:50:54,214] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.11823705707156736, 'n_estimators': 917, 'subsample': 0.7339146588631219, 'colsample_bytree': 0.9900387053991182, 'min_child_weight': 6, 'gamma': 0.1002046219525714, 'reg_alpha': 0.17366543684868288, 'reg_lambda': 0.0007748730036499379, 'max_delta_step': 7}. Best is trial 33 with value: 0.6885964912280701.

Best trial: 33. Best value: 0.688596:  20%|██        | 40/200 [00:33<02:39,  1.00it/s]

[I 2025-11-10 17:50:55,400] Trial 41 pruned.

Best trial: 33. Best value: 0.688596:  20%|██        | 41/200 [00:34<02:34,  1.03it/s]

[I 2025-11-10 17:50:56,300] Trial 43 pruned.

Best trial: 33. Best value: 0.688596:  21%|██        | 42/200 [00:37<04:09,  1.58s/it]

[I 2025-11-10 17:50:59,300] Trial 39 finished with value: 0.6592202729044835 and parameters: {'max_depth': 6, 'learning_rate': 0.017504059074642052, 'n_estimators': 1121, 'subsample': 0.7383492555640147, 'colsample_bytree': 0.6347060435794667, 'min_child_weight': 1, 'gamma': 0.12762915080688964, 'reg_alpha': 1.949331854954694e-06, 'reg_lambda': 4.9911703014107226e-08, 'max_delta_step': 0}. Best is trial 33 with value: 0.6885964912280701.

Best trial: 33. Best value: 0.688596:  22%|██▏       | 43/200 [00:38<03:40,  1.41s/it]

[I 2025-11-10 17:51:00,305] Trial 40 finished with value: 0.6524366471734893 and parameters: {'max_depth': 6, 'learning_rate': 0.01841782966620997, 'n_estimators': 960, 'subsample': 0.7405607516909898, 'colsample_bytree': 0.634602156334957, 'min_child_weight': 1, 'gamma': 0.09152103368388745, 'reg_alpha': 1.4740719785301118e-06, 'reg_lambda': 1.6250376417999e-07, 'max_delta_step': 1}. Best is trial 33 with value: 0.6885964912280701.

Best trial: 33. Best value: 0.688596:  22%|██▏       | 44/200 [00:39<03:22,  1.30s/it]

[I 2025-11-10 17:51:01,354] Trial 42 finished with value: 0.6726705653021443 and parameters: {'max_depth': 7, 'learning_rate': 0.01738515387087042, 'n_estimators': 1143, 'subsample': 0.8198525199411572, 'colsample_bytree': 0.6229878877153089, 'min_child_weight': 1, 'gamma': 3.8146630884679196, 'reg_alpha': 2.2834675073627425e-06, 'reg_lambda': 7.994533023454946e-08, 'max_delta_step': 0}. Best is trial 33 with value: 0.6885964912280701.

Best trial: 33. Best value: 0.688596:  22%|██▎       | 45/200 [00:39<02:43,  1.05s/it]

[I 2025-11-10 17:51:01,831] Trial 46 pruned.

Best trial: 33. Best value: 0.688596:  23%|██▎       | 46/200 [00:40<02:39,  1.03s/it]

[I 2025-11-10 17:51:02,823] Trial 47 pruned.

Best trial: 33. Best value: 0.688596:  24%|██▎       | 47/200 [00:41<02:18,  1.10it/s]

[I 2025-11-10 17:51:03,434] Trial 48 pruned.

Best trial: 33. Best value: 0.688596:  24%|██▍       | 48/200 [00:41<01:49,  1.38it/s]

[I 2025-11-10 17:51:03,724] Trial 44 finished with value: 0.6726900584795321 and parameters: {'max_depth': 7, 'learning_rate': 0.025946175732478902, 'n_estimators': 1254, 'subsample': 0.7579862004587652, 'colsample_bytree': 0.611351125463899, 'min_child_weight': 1, 'gamma': 0.49036420351528454, 'reg_alpha': 5.9114468219965434e-05, 'reg_lambda': 1.858706267093047e-06, 'max_delta_step': 3}. Best is trial 33 with value: 0.6885964912280701.

Best trial: 33. Best value: 0.688596:  24%|██▍       | 49/200 [00:42<01:37,  1.54it/s]

[I 2025-11-10 17:51:04,197] Trial 49 pruned.

Best trial: 33. Best value: 0.688596:  25%|██▌       | 50/200 [00:43<01:44,  1.44it/s]

[I 2025-11-10 17:51:04,999] Trial 51 pruned.

Best trial: 33. Best value: 0.688596:  26%|██▌       | 51/200 [00:43<01:20,  1.84it/s]

[I 2025-11-10 17:51:05,194] Trial 52 pruned.

Best trial: 33. Best value: 0.688596:  26%|██▌       | 52/200 [00:43<01:14,  1.98it/s]

[I 2025-11-10 17:51:05,608] Trial 53 pruned.

Best trial: 33. Best value: 0.688596:  26%|██▋       | 53/200 [00:44<01:37,  1.50it/s]

[I 2025-11-10 17:51:06,649] Trial 54 pruned.

Best trial: 45. Best value: 0.693411:  28%|██▊       | 55/200 [00:45<01:06,  2.18it/s]

[I 2025-11-10 17:51:07,067] Trial 45 finished with value: 0.693411306042885 and parameters: {'max_depth': 6, 'learning_rate': 0.020566169239255912, 'n_estimators': 1133, 'subsample': 0.7682264927262229, 'colsample_bytree': 0.5788798737625482, 'min_child_weight': 1, 'gamma': 1.029519618930116, 'reg_alpha': 4.0421430255692495e-05, 'reg_lambda': 6.159402680792036e-08, 'max_delta_step': 1}. Best is trial 45 with value: 0.693411306042885.
[I 2025-11-10 17:51:07,219] Trial 55 pruned.

Best trial: 45. Best value: 0.693411:  28%|██▊       | 56/200 [00:46<01:27,  1.65it/s]

[I 2025-11-10 17:51:08,165] Trial 57 pruned.

Best trial: 45. Best value: 0.693411:  28%|██▊       | 57/200 [00:46<01:13,  1.96it/s]

[I 2025-11-10 17:51:08,457] Trial 58 pruned.

Best trial: 45. Best value: 0.693411:  29%|██▉       | 58/200 [00:47<01:21,  1.73it/s]

[I 2025-11-10 17:51:09,185] Trial 59 pruned.

Best trial: 45. Best value: 0.693411:  30%|██▉       | 59/200 [00:48<01:52,  1.25it/s]

[I 2025-11-10 17:51:10,496] Trial 61 pruned.

Best trial: 45. Best value: 0.693411:  30%|███       | 60/200 [00:49<01:34,  1.48it/s]

[I 2025-11-10 17:51:10,896] Trial 50 finished with value: 0.6801949317738792 and parameters: {'max_depth': 7, 'learning_rate': 0.02642364192351124, 'n_estimators': 1194, 'subsample': 0.8733784776425898, 'colsample_bytree': 0.6006484078237073, 'min_child_weight': 1, 'gamma': 3.4704846585936937, 'reg_alpha': 6.648672049067413e-06, 'reg_lambda': 1.3593148643188888e-06, 'max_delta_step': 3}. Best is trial 45 with value: 0.693411306042885.

Best trial: 45. Best value: 0.693411:  30%|███       | 61/200 [00:50<01:45,  1.32it/s]

[I 2025-11-10 17:51:11,839] Trial 62 pruned.

Best trial: 45. Best value: 0.693411:  31%|███       | 62/200 [00:51<01:54,  1.20it/s]

[I 2025-11-10 17:51:12,848] Trial 56 finished with value: 0.6739181286549707 and parameters: {'max_depth': 7, 'learning_rate': 0.0195249486520231, 'n_estimators': 707, 'subsample': 0.7682910956537754, 'colsample_bytree': 0.6627641398943268, 'min_child_weight': 1, 'gamma': 0.5288174036258566, 'reg_alpha': 4.91369966692822e-06, 'reg_lambda': 2.8640332740527675e-07, 'max_delta_step': 2}. Best is trial 45 with value: 0.693411306042885.

Best trial: 45. Best value: 0.693411:  32%|███▏      | 63/200 [00:54<03:52,  1.69s/it]

[I 2025-11-10 17:51:16,549] Trial 60 finished with value: 0.6732748538011697 and parameters: {'max_depth': 4, 'learning_rate': 0.015444476096128472, 'n_estimators': 1168, 'subsample': 0.8357795699958898, 'colsample_bytree': 0.5377451254226412, 'min_child_weight': 1, 'gamma': 0.3731167313890552, 'reg_alpha': 5.525282271435119e-08, 'reg_lambda': 2.787750133422159e-08, 'max_delta_step': 5}. Best is trial 45 with value: 0.693411306042885.

Best trial: 63. Best value: 0.695283:  32%|███▏      | 64/200 [00:55<03:30,  1.55s/it]

[I 2025-11-10 17:51:17,753] Trial 63 finished with value: 0.6952826510721248 and parameters: {'max_depth': 8, 'learning_rate': 0.019746820625318316, 'n_estimators': 1174, 'subsample': 0.9133997751855655, 'colsample_bytree': 0.564654264161602, 'min_child_weight': 1, 'gamma': 3.885465461520967, 'reg_alpha': 1.0022235063579489e-07, 'reg_lambda': 1.0211436040164994e-07, 'max_delta_step': 3}. Best is trial 63 with value: 0.6952826510721248.

Best trial: 63. Best value: 0.695283:  32%|███▎      | 65/200 [00:56<02:34,  1.15s/it]

[I 2025-11-10 17:51:17,963] Trial 66 pruned.

Best trial: 64. Best value: 0.695653:  33%|███▎      | 66/200 [00:57<02:23,  1.07s/it]

[I 2025-11-10 17:51:18,867] Trial 64 finished with value: 0.6956530214424951 and parameters: {'max_depth': 7, 'learning_rate': 0.019752270292637403, 'n_estimators': 1161, 'subsample': 0.8877271943498032, 'colsample_bytree': 0.5638126599480783, 'min_child_weight': 1, 'gamma': 3.072122173280337, 'reg_alpha': 8.043939823196583e-05, 'reg_lambda': 2.755000927676597e-06, 'max_delta_step': 3}. Best is trial 64 with value: 0.6956530214424951.

Best trial: 64. Best value: 0.695653:  34%|███▎      | 67/200 [00:57<01:50,  1.20it/s]

[I 2025-11-10 17:51:19,143] Trial 68 pruned.
[I 2025-11-10 17:51:19,169] Trial 67 pruned.

Best trial: 64. Best value: 0.695653:  34%|███▍      | 69/200 [00:58<01:23,  1.57it/s]

[I 2025-11-10 17:51:19,963] Trial 70 pruned.

Best trial: 64. Best value: 0.695653:  35%|███▌      | 70/200 [00:58<01:09,  1.87it/s]

[I 2025-11-10 17:51:20,183] Trial 69 pruned.
[I 2025-11-10 17:51:20,258] Trial 71 pruned.

Best trial: 64. Best value: 0.695653:  36%|███▌      | 72/200 [00:59<01:03,  2.01it/s]

[I 2025-11-10 17:51:21,077] Trial 72 pruned.
[I 2025-11-10 17:51:21,109] Trial 65 finished with value: 0.6747563352826511 and parameters: {'max_depth': 7, 'learning_rate': 0.0195955712442233, 'n_estimators': 1179, 'subsample': 0.902854285271844, 'colsample_bytree': 0.6138610478738051, 'min_child_weight': 1, 'gamma': 0.34029826555316767, 'reg_alpha': 7.980208671379501e-07, 'reg_lambda': 8.816131807136612e-08, 'max_delta_step': 3}. Best is trial 64 with value: 0.6956530214424951.

Best trial: 64. Best value: 0.695653:  37%|███▋      | 74/200 [00:59<00:55,  2.28it/s]

[I 2025-11-10 17:51:21,754] Trial 74 pruned.

Best trial: 64. Best value: 0.695653:  38%|███▊      | 75/200 [01:01<01:18,  1.59it/s]

[I 2025-11-10 17:51:23,107] Trial 73 finished with value: 0.6228460038986354 and parameters: {'max_depth': 7, 'learning_rate': 0.02919281588374915, 'n_estimators': 565, 'subsample': 0.96312330572711, 'colsample_bytree': 0.5782443554962897, 'min_child_weight': 3, 'gamma': 4.558743334759662, 'reg_alpha': 0.00018479520772312852, 'reg_lambda': 4.944525190943924e-07, 'max_delta_step': 2}. Best is trial 64 with value: 0.6956530214424951.

Best trial: 64. Best value: 0.695653:  38%|███▊      | 76/200 [01:03<01:54,  1.08it/s]

[I 2025-11-10 17:51:25,017] Trial 77 finished with value: 0.6714424951267055 and parameters: {'max_depth': 7, 'learning_rate': 0.01234561024638331, 'n_estimators': 343, 'subsample': 0.8715803327564577, 'colsample_bytree': 0.5777670158560917, 'min_child_weight': 1, 'gamma': 2.5219090003313216, 'reg_alpha': 1.0561208281343005e-05, 'reg_lambda': 9.842734938858515e-07, 'max_delta_step': 2}. Best is trial 64 with value: 0.6956530214424951.

Best trial: 64. Best value: 0.695653:  38%|███▊      | 77/200 [01:03<01:34,  1.30it/s]

[I 2025-11-10 17:51:25,319] Trial 78 finished with value: 0.6739181286549708 and parameters: {'max_depth': 7, 'learning_rate': 0.04490765627869334, 'n_estimators': 325, 'subsample': 0.8666074485400359, 'colsample_bytree': 0.5161596644530351, 'min_child_weight': 1, 'gamma': 2.4245669145632154, 'reg_alpha': 8.315115135872323e-06, 'reg_lambda': 1.357121885558534e-07, 'max_delta_step': 2}. Best is trial 64 with value: 0.6956530214424951.
[I 2025-11-10 17:51:25,335] Trial 75 finished with value: 0.6751461988304094 and parameters: {'max_depth': 7, 'learning_rate': 0.016622528279787843, 'n_estimators': 310, 'subsample': 0.8650627288961852, 'colsample_bytree': 0.5375936259788088, 'min_child_weight': 1, 'gamma': 0.26646485983049345, 'reg_alpha': 1.6969420806201808e-07, 'reg_lambda': 9.507954428202994e-08, 'max_delta_step': 5}. Best is trial 64 with value: 0.6956530214424951.

Best trial: 64. Best value: 0.695653:  40%|███▉      | 79/200 [01:05<01:40,  1.21it/s]

[I 2025-11-10 17:51:27,127] Trial 80 pruned.

Best trial: 64. Best value: 0.695653:  40%|████      | 80/200 [01:06<02:01,  1.01s/it]

[I 2025-11-10 17:51:28,756] Trial 82 pruned.

Best trial: 64. Best value: 0.695653:  40%|████      | 81/200 [01:07<01:47,  1.11it/s]

[I 2025-11-10 17:51:29,335] Trial 76 finished with value: 0.6825341130604288 and parameters: {'max_depth': 7, 'learning_rate': 0.01580840606445907, 'n_estimators': 1301, 'subsample': 0.8883085661678479, 'colsample_bytree': 0.6512755651093666, 'min_child_weight': 1, 'gamma': 3.6186214955983393, 'reg_alpha': 0.00016961528602362673, 'reg_lambda': 1.017689370490883e-07, 'max_delta_step': 2}. Best is trial 64 with value: 0.6956530214424951.

Best trial: 64. Best value: 0.695653:  41%|████      | 82/200 [01:08<01:43,  1.14it/s]

[I 2025-11-10 17:51:30,131] Trial 83 pruned.

Best trial: 64. Best value: 0.695653:  42%|████▏     | 83/200 [01:09<02:02,  1.05s/it]

[I 2025-11-10 17:51:31,640] Trial 85 pruned.

Best trial: 64. Best value: 0.695653:  42%|████▏     | 84/200 [01:10<01:52,  1.03it/s]

[I 2025-11-10 17:51:32,397] Trial 79 finished with value: 0.6780896686159844 and parameters: {'max_depth': 6, 'learning_rate': 0.044491193166047875, 'n_estimators': 1297, 'subsample': 0.8940250201385463, 'colsample_bytree': 0.6515707942372961, 'min_child_weight': 1, 'gamma': 1.856108330535681, 'reg_alpha': 3.1436074482468082e-06, 'reg_lambda': 1.373737188086727e-07, 'max_delta_step': 2}. Best is trial 64 with value: 0.6956530214424951.

Best trial: 64. Best value: 0.695653:  42%|████▎     | 85/200 [01:11<01:38,  1.17it/s]

[I 2025-11-10 17:51:32,975] Trial 81 finished with value: 0.6936452241715398 and parameters: {'max_depth': 9, 'learning_rate': 0.017243447219191133, 'n_estimators': 1299, 'subsample': 0.9023710479246106, 'colsample_bytree': 0.5461820073631927, 'min_child_weight': 1, 'gamma': 1.7054128537732551, 'reg_alpha': 3.150861100890307e-08, 'reg_lambda': 1.342776047891469e-08, 'max_delta_step': 6}. Best is trial 64 with value: 0.6956530214424951.

Best trial: 64. Best value: 0.695653:  43%|████▎     | 86/200 [01:12<01:38,  1.16it/s]

[I 2025-11-10 17:51:33,860] Trial 87 pruned.

Best trial: 64. Best value: 0.695653:  44%|████▎     | 87/200 [01:13<01:55,  1.02s/it]

[I 2025-11-10 17:51:35,258] Trial 89 pruned.

Best trial: 64. Best value: 0.695653:  44%|████▍     | 88/200 [01:14<02:10,  1.17s/it]

[I 2025-11-10 17:51:36,773] Trial 84 finished with value: 0.6871345029239766 and parameters: {'max_depth': 7, 'learning_rate': 0.01658747897535537, 'n_estimators': 1289, 'subsample': 0.938267773049823, 'colsample_bytree': 0.6463920739682391, 'min_child_weight': 1, 'gamma': 4.030075819919853, 'reg_alpha': 6.526782657062752e-05, 'reg_lambda': 1.1227983966473466e-08, 'max_delta_step': 4}. Best is trial 64 with value: 0.6956530214424951.

Best trial: 64. Best value: 0.695653:  44%|████▍     | 89/200 [01:16<02:26,  1.32s/it]

[I 2025-11-10 17:51:38,452] Trial 91 pruned.

Best trial: 64. Best value: 0.695653:  45%|████▌     | 90/200 [01:17<01:54,  1.05s/it]

[I 2025-11-10 17:51:38,853] Trial 86 finished with value: 0.680448343079922 and parameters: {'max_depth': 7, 'learning_rate': 0.01872809170293262, 'n_estimators': 1240, 'subsample': 0.9230582710404068, 'colsample_bytree': 0.6130649660380421, 'min_child_weight': 1, 'gamma': 3.9452499223223385, 'reg_alpha': 0.0005746723957406808, 'reg_lambda': 5.357574253264799e-08, 'max_delta_step': 3}. Best is trial 64 with value: 0.6956530214424951.

Best trial: 64. Best value: 0.695653:  46%|████▌     | 91/200 [01:18<01:53,  1.04s/it]

[I 2025-11-10 17:51:39,873] Trial 92 pruned.

Best trial: 64. Best value: 0.695653:  46%|████▌     | 92/200 [01:18<01:29,  1.21it/s]

[I 2025-11-10 17:51:40,197] Trial 93 pruned.

Best trial: 88. Best value: 0.704016:  46%|████▋     | 93/200 [01:20<02:02,  1.15s/it]

[I 2025-11-10 17:51:42,109] Trial 88 finished with value: 0.7040155945419102 and parameters: {'max_depth': 6, 'learning_rate': 0.016148695828429708, 'n_estimators': 1231, 'subsample': 0.931818830174879, 'colsample_bytree': 0.9598593074695687, 'min_child_weight': 1, 'gamma': 3.995094802491473, 'reg_alpha': 3.915593032601393e-08, 'reg_lambda': 1.021297723079599e-08, 'max_delta_step': 1}. Best is trial 88 with value: 0.7040155945419102.

Best trial: 88. Best value: 0.704016:  47%|████▋     | 94/200 [01:21<02:15,  1.28s/it]

[I 2025-11-10 17:51:43,680] Trial 90 finished with value: 0.6989668615984406 and parameters: {'max_depth': 6, 'learning_rate': 0.014711171914118611, 'n_estimators': 1357, 'subsample': 0.8913744356705512, 'colsample_bytree': 0.6079731060137683, 'min_child_weight': 1, 'gamma': 1.3733129407065765, 'reg_alpha': 1.499142701400837e-07, 'reg_lambda': 1.7349301368286357e-08, 'max_delta_step': 6}. Best is trial 88 with value: 0.7040155945419102.

Best trial: 88. Best value: 0.704016:  48%|████▊     | 95/200 [01:23<02:35,  1.48s/it]

[I 2025-11-10 17:51:45,629] Trial 94 pruned.

Best trial: 88. Best value: 0.704016:  48%|████▊     | 96/200 [01:25<02:35,  1.50s/it]

[I 2025-11-10 17:51:47,170] Trial 98 pruned.

Best trial: 88. Best value: 0.704016:  48%|████▊     | 97/200 [01:25<01:57,  1.14s/it]

[I 2025-11-10 17:51:47,465] Trial 95 finished with value: 0.6851267056530215 and parameters: {'max_depth': 7, 'learning_rate': 0.01438884309127952, 'n_estimators': 1231, 'subsample': 0.9469202222336023, 'colsample_bytree': 0.6501897725792776, 'min_child_weight': 1, 'gamma': 3.838838303774911, 'reg_alpha': 2.5272441861166916e-05, 'reg_lambda': 4.8459558553507626e-08, 'max_delta_step': 2}. Best is trial 88 with value: 0.7040155945419102.

Best trial: 88. Best value: 0.704016:  49%|████▉     | 98/200 [01:26<01:39,  1.03it/s]

[I 2025-11-10 17:51:48,046] Trial 99 pruned.

Best trial: 88. Best value: 0.704016:  50%|████▉     | 99/200 [01:26<01:18,  1.29it/s]

[I 2025-11-10 17:51:48,362] Trial 100 pruned.

Best trial: 88. Best value: 0.704016:  50%|█████     | 100/200 [01:27<01:21,  1.23it/s]

[I 2025-11-10 17:51:49,260] Trial 101 pruned.
[I 2025-11-10 17:51:49,308] Trial 102 pruned.

Best trial: 88. Best value: 0.704016:  51%|█████     | 102/200 [01:27<00:48,  2.04it/s]

[I 2025-11-10 17:51:49,490] Trial 96 pruned.

Best trial: 88. Best value: 0.704016:  52%|█████▏    | 103/200 [01:29<01:07,  1.44it/s]

[I 2025-11-10 17:51:50,801] Trial 97 pruned.
[I 2025-11-10 17:51:50,899] Trial 103 pruned.

Best trial: 88. Best value: 0.704016:  52%|█████▎    | 105/200 [01:33<02:03,  1.30s/it]

[I 2025-11-10 17:51:55,113] Trial 104 pruned.

Best trial: 88. Best value: 0.704016:  53%|█████▎    | 106/200 [01:33<01:38,  1.05s/it]

[I 2025-11-10 17:51:55,317] Trial 105 pruned.

Best trial: 88. Best value: 0.704016:  54%|█████▎    | 107/200 [01:34<01:40,  1.08s/it]

[I 2025-11-10 17:51:56,501] Trial 106 pruned.
[I 2025-11-10 17:51:56,593] Trial 108 pruned.

Best trial: 88. Best value: 0.704016:  55%|█████▍    | 109/200 [01:36<01:23,  1.10it/s]

[I 2025-11-10 17:51:57,841] Trial 107 finished with value: 0.6984990253411306 and parameters: {'max_depth': 7, 'learning_rate': 0.021811463823608476, 'n_estimators': 1141, 'subsample': 0.9317087643204899, 'colsample_bytree': 0.6124326623060317, 'min_child_weight': 1, 'gamma': 1.092814123292732, 'reg_alpha': 0.00014729685356079365, 'reg_lambda': 5.625612711029173e-05, 'max_delta_step': 8}. Best is trial 88 with value: 0.7040155945419102.

Best trial: 88. Best value: 0.704016:  55%|█████▌    | 110/200 [01:36<01:07,  1.34it/s]

[I 2025-11-10 17:51:58,021] Trial 111 pruned.

Best trial: 88. Best value: 0.704016:  56%|█████▌    | 111/200 [01:36<00:56,  1.57it/s]

[I 2025-11-10 17:51:58,328] Trial 110 pruned.

Best trial: 88. Best value: 0.704016:  56%|█████▌    | 112/200 [01:37<01:01,  1.42it/s]

[I 2025-11-10 17:51:59,213] Trial 112 pruned.

Best trial: 88. Best value: 0.704016:  56%|█████▋    | 113/200 [01:38<01:19,  1.09it/s]

[I 2025-11-10 17:52:00,701] Trial 109 pruned.

Best trial: 114. Best value: 0.705029:  57%|█████▋    | 114/200 [01:44<03:01,  2.11s/it]

[I 2025-11-10 17:52:05,897] Trial 113 finished with value: 0.7010721247563353 and parameters: {'max_depth': 8, 'learning_rate': 0.023701080117457553, 'n_estimators': 1340, 'subsample': 0.9024346397779104, 'colsample_bytree': 0.5696922607086543, 'min_child_weight': 1, 'gamma': 1.0251534310763688, 'reg_alpha': 0.00012812962358809579, 'reg_lambda': 8.289706854689791e-05, 'max_delta_step': 9}. Best is trial 88 with value: 0.7040155945419102.
[I 2025-11-10 17:52:05,933] Trial 114 finished with value: 0.7050292397660818 and parameters: {'max_depth': 8, 'learning_rate': 0.016692477998247173, 'n_estimators': 1135, 'subsample': 0.9036015320127034, 'colsample_bytree': 0.6298035709875689, 'min_child_weight': 1, 'gamma': 1.0699571219206074, 'reg_alpha': 0.00013579360369142348, 'reg_lambda': 6.18874008548109e-05, 'max_delta_step': 8}. Best is trial 114 with value: 0.7050292397660818.

Best trial: 115. Best value: 0.70538:  58%|█████▊    | 116/200 [01:45<02:01,  1.45s/it]

[I 2025-11-10 17:52:07,140] Trial 115 finished with value: 0.7053801169590643 and parameters: {'max_depth': 7, 'learning_rate': 0.01881029601997886, 'n_estimators': 1330, 'subsample': 0.9148548022702199, 'colsample_bytree': 0.5703853612524692, 'min_child_weight': 1, 'gamma': 1.572591896046709, 'reg_alpha': 0.008084478689575647, 'reg_lambda': 5.274763707340991e-05, 'max_delta_step': 8}. Best is trial 115 with value: 0.7053801169590643.

Best trial: 115. Best value: 0.70538:  58%|█████▊    | 117/200 [01:46<02:03,  1.49s/it]

[I 2025-11-10 17:52:08,764] Trial 116 finished with value: 0.7029239766081872 and parameters: {'max_depth': 7, 'learning_rate': 0.023733378209268102, 'n_estimators': 1336, 'subsample': 0.9033296794366481, 'colsample_bytree': 0.6312623580532778, 'min_child_weight': 1, 'gamma': 0.9477487847066146, 'reg_alpha': 0.003475055005341823, 'reg_lambda': 8.14327698484775e-05, 'max_delta_step': 4}. Best is trial 115 with value: 0.7053801169590643.

Best trial: 115. Best value: 0.70538:  59%|█████▉    | 118/200 [01:50<02:42,  1.98s/it]

[I 2025-11-10 17:52:12,182] Trial 117 finished with value: 0.6797270955165692 and parameters: {'max_depth': 8, 'learning_rate': 0.18271817124743592, 'n_estimators': 1321, 'subsample': 0.9147260757657593, 'colsample_bytree': 0.5685340971087699, 'min_child_weight': 1, 'gamma': 0.9604093018915526, 'reg_alpha': 1.575456233328715e-05, 'reg_lambda': 7.434126150832064e-05, 'max_delta_step': 8}. Best is trial 115 with value: 0.7053801169590643.

Best trial: 115. Best value: 0.70538:  60%|█████▉    | 119/200 [01:50<02:03,  1.53s/it]

[I 2025-11-10 17:52:12,451] Trial 118 finished with value: 0.695009746588694 and parameters: {'max_depth': 8, 'learning_rate': 0.023849690300821198, 'n_estimators': 1073, 'subsample': 0.9016077351733354, 'colsample_bytree': 0.5690598101041611, 'min_child_weight': 1, 'gamma': 1.002936627647672, 'reg_alpha': 0.00011904708575388911, 'reg_lambda': 0.00027958878558904563, 'max_delta_step': 9}. Best is trial 115 with value: 0.7053801169590643.

Best trial: 115. Best value: 0.70538:  60%|██████    | 120/200 [01:51<01:57,  1.46s/it]

[I 2025-11-10 17:52:13,753] Trial 121 pruned.

Best trial: 115. Best value: 0.70538:  60%|██████    | 121/200 [01:52<01:28,  1.12s/it]

[I 2025-11-10 17:52:14,002] Trial 122 pruned.

Best trial: 115. Best value: 0.70538:  61%|██████    | 122/200 [01:53<01:35,  1.22s/it]

[I 2025-11-10 17:52:15,472] Trial 119 finished with value: 0.6981091617933723 and parameters: {'max_depth': 8, 'learning_rate': 0.024726851512315483, 'n_estimators': 1431, 'subsample': 0.9073207788095443, 'colsample_bytree': 0.567906362956931, 'min_child_weight': 1, 'gamma': 1.582384282113861, 'reg_alpha': 0.007857342650591154, 'reg_lambda': 9.475358050153246e-05, 'max_delta_step': 9}. Best is trial 115 with value: 0.7053801169590643.

Best trial: 115. Best value: 0.70538:  62%|██████▏   | 123/200 [01:54<01:34,  1.22s/it]

[I 2025-11-10 17:52:16,704] Trial 120 finished with value: 0.7010721247563353 and parameters: {'max_depth': 8, 'learning_rate': 0.02396098299027333, 'n_estimators': 1352, 'subsample': 0.9030722520479753, 'colsample_bytree': 0.5691148978763858, 'min_child_weight': 1, 'gamma': 1.5460901695016822, 'reg_alpha': 0.011652623712040107, 'reg_lambda': 6.482509290325126e-05, 'max_delta_step': 9}. Best is trial 115 with value: 0.7053801169590643.

Best trial: 124. Best value: 0.707115:  62%|██████▏   | 124/200 [01:58<02:23,  1.89s/it]

[I 2025-11-10 17:52:20,195] Trial 124 finished with value: 0.7071150097465887 and parameters: {'max_depth': 9, 'learning_rate': 0.022692041234362068, 'n_estimators': 1057, 'subsample': 0.8560852513636384, 'colsample_bytree': 0.5614515033696862, 'min_child_weight': 1, 'gamma': 1.56272817716863, 'reg_alpha': 0.004972419002844856, 'reg_lambda': 3.9206466669230904e-05, 'max_delta_step': 8}. Best is trial 124 with value: 0.7071150097465887.

Best trial: 124. Best value: 0.707115:  62%|██████▎   | 125/200 [02:00<02:22,  1.91s/it]

[I 2025-11-10 17:52:22,139] Trial 123 finished with value: 0.6978557504873294 and parameters: {'max_depth': 8, 'learning_rate': 0.022716477010933746, 'n_estimators': 1402, 'subsample': 0.9023768001957172, 'colsample_bytree': 0.5863558968059176, 'min_child_weight': 1, 'gamma': 1.5567369071280392, 'reg_alpha': 0.05017949729320288, 'reg_lambda': 0.0005046153094569973, 'max_delta_step': 9}. Best is trial 124 with value: 0.7071150097465887.

Best trial: 124. Best value: 0.707115:  63%|██████▎   | 126/200 [02:01<02:10,  1.76s/it]

[I 2025-11-10 17:52:23,546] Trial 125 finished with value: 0.6965107212475632 and parameters: {'max_depth': 8, 'learning_rate': 0.02343025276330663, 'n_estimators': 1406, 'subsample': 0.9042263799761443, 'colsample_bytree': 0.5974503088734493, 'min_child_weight': 1, 'gamma': 1.5744430736969353, 'reg_alpha': 0.004273827974631889, 'reg_lambda': 0.00015215115688749285, 'max_delta_step': 9}. Best is trial 124 with value: 0.7071150097465887.

Best trial: 126. Best value: 0.724425:  64%|██████▎   | 127/200 [02:02<01:52,  1.54s/it]

[I 2025-11-10 17:52:24,560] Trial 126 finished with value: 0.7244249512670565 and parameters: {'max_depth': 8, 'learning_rate': 0.022490526840207033, 'n_estimators': 1391, 'subsample': 0.9054328469652269, 'colsample_bytree': 0.5600527287536106, 'min_child_weight': 1, 'gamma': 1.5696032155855681, 'reg_alpha': 0.008543111121201288, 'reg_lambda': 3.322998466664506e-05, 'max_delta_step': 9}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  64%|██████▍   | 128/200 [02:06<02:32,  2.11s/it]

[I 2025-11-10 17:52:28,033] Trial 127 finished with value: 0.7203313840155945 and parameters: {'max_depth': 8, 'learning_rate': 0.02281342084155238, 'n_estimators': 1395, 'subsample': 0.9097427744411289, 'colsample_bytree': 0.560054994432714, 'min_child_weight': 1, 'gamma': 1.606469947853804, 'reg_alpha': 0.0037385143821491483, 'reg_lambda': 3.1611105933563204e-05, 'max_delta_step': 9}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  64%|██████▍   | 129/200 [02:08<02:24,  2.03s/it]

[I 2025-11-10 17:52:29,881] Trial 128 finished with value: 0.6984795321637426 and parameters: {'max_depth': 8, 'learning_rate': 0.022409526378908064, 'n_estimators': 1388, 'subsample': 0.8598459064746494, 'colsample_bytree': 0.5612244934479373, 'min_child_weight': 1, 'gamma': 1.6069025633441159, 'reg_alpha': 0.007426702791593742, 'reg_lambda': 4.5448892291468167e-05, 'max_delta_step': 8}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  65%|██████▌   | 130/200 [02:09<02:09,  1.85s/it]

[I 2025-11-10 17:52:31,298] Trial 129 finished with value: 0.6956335282651073 and parameters: {'max_depth': 9, 'learning_rate': 0.028008032707178623, 'n_estimators': 1407, 'subsample': 0.8672977872664007, 'colsample_bytree': 0.5945386328943212, 'min_child_weight': 1, 'gamma': 1.5583001036358488, 'reg_alpha': 0.0045464992043500576, 'reg_lambda': 4.6838315124175114e-05, 'max_delta_step': 8}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  66%|██████▌   | 131/200 [02:11<02:01,  1.77s/it]

[I 2025-11-10 17:52:32,867] Trial 130 finished with value: 0.687485380116959 and parameters: {'max_depth': 8, 'learning_rate': 0.022703421661221655, 'n_estimators': 1499, 'subsample': 0.8614114348295854, 'colsample_bytree': 0.5979804694595658, 'min_child_weight': 1, 'gamma': 1.5517445833245058, 'reg_alpha': 0.005568151115146843, 'reg_lambda': 4.4412597189209306e-05, 'max_delta_step': 8}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  66%|██████▌   | 132/200 [02:13<02:18,  2.03s/it]

[I 2025-11-10 17:52:35,519] Trial 131 finished with value: 0.6853801169590643 and parameters: {'max_depth': 9, 'learning_rate': 0.02801915056771638, 'n_estimators': 1361, 'subsample': 0.851193719454546, 'colsample_bytree': 0.5875387657777916, 'min_child_weight': 1, 'gamma': 1.96028441904689, 'reg_alpha': 0.010422899960072802, 'reg_lambda': 3.900320382234202e-05, 'max_delta_step': 8}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  66%|██████▋   | 133/200 [02:15<02:19,  2.08s/it]

[I 2025-11-10 17:52:37,705] Trial 132 finished with value: 0.6788499025341131 and parameters: {'max_depth': 9, 'learning_rate': 0.027606081234974468, 'n_estimators': 1478, 'subsample': 0.8463665791605051, 'colsample_bytree': 0.5267261130896637, 'min_child_weight': 1, 'gamma': 1.4809427409445237, 'reg_alpha': 0.008106207796400868, 'reg_lambda': 4.5867361926339504e-05, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  67%|██████▋   | 134/200 [02:16<01:52,  1.71s/it]

[I 2025-11-10 17:52:38,546] Trial 135 pruned.

Best trial: 126. Best value: 0.724425:  68%|██████▊   | 135/200 [02:17<01:27,  1.35s/it]

[I 2025-11-10 17:52:39,061] Trial 133 finished with value: 0.7011890838206628 and parameters: {'max_depth': 9, 'learning_rate': 0.031932823463861504, 'n_estimators': 1480, 'subsample': 0.8469303724319326, 'colsample_bytree': 0.5338025741998731, 'min_child_weight': 1, 'gamma': 1.4530594203414808, 'reg_alpha': 0.009304804860311069, 'reg_lambda': 1.1719018902246495e-05, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  68%|██████▊   | 136/200 [02:18<01:24,  1.31s/it]

[I 2025-11-10 17:52:40,288] Trial 134 finished with value: 0.696140350877193 and parameters: {'max_depth': 8, 'learning_rate': 0.026474922795107367, 'n_estimators': 1344, 'subsample': 0.8780112269281866, 'colsample_bytree': 0.5575712502349125, 'min_child_weight': 1, 'gamma': 1.4100406268623737, 'reg_alpha': 0.01070052592041114, 'reg_lambda': 1.3119254505759623e-05, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  68%|██████▊   | 137/200 [02:19<01:11,  1.14s/it]

[I 2025-11-10 17:52:41,013] Trial 138 pruned.

Best trial: 126. Best value: 0.724425:  69%|██████▉   | 138/200 [02:20<01:14,  1.21s/it]

[I 2025-11-10 17:52:42,385] Trial 140 pruned.

Best trial: 126. Best value: 0.724425:  70%|██████▉   | 139/200 [02:22<01:19,  1.30s/it]

[I 2025-11-10 17:52:43,892] Trial 141 pruned.

Best trial: 126. Best value: 0.724425:  70%|███████   | 140/200 [02:23<01:17,  1.28s/it]

[I 2025-11-10 17:52:45,144] Trial 137 pruned.

Best trial: 126. Best value: 0.724425:  70%|███████   | 141/200 [02:23<01:00,  1.03s/it]

[I 2025-11-10 17:52:45,587] Trial 142 pruned.
[I 2025-11-10 17:52:45,607] Trial 136 finished with value: 0.6935477582846004 and parameters: {'max_depth': 8, 'learning_rate': 0.03130786910795741, 'n_estimators': 1342, 'subsample': 0.8736252496632586, 'colsample_bytree': 0.5558420270304626, 'min_child_weight': 1, 'gamma': 1.4347695652281212, 'reg_alpha': 0.06531450295783724, 'reg_lambda': 9.76618932999125e-05, 'max_delta_step': 9}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  72%|███████▏  | 143/200 [02:25<00:54,  1.05it/s]

[I 2025-11-10 17:52:47,290] Trial 144 pruned.
[I 2025-11-10 17:52:47,332] Trial 145 pruned.

Best trial: 126. Best value: 0.724425:  72%|███████▎  | 145/200 [02:26<00:47,  1.16it/s]

[I 2025-11-10 17:52:48,758] Trial 139 finished with value: 0.707738791423002 and parameters: {'max_depth': 9, 'learning_rate': 0.020937196993491336, 'n_estimators': 1442, 'subsample': 0.9151769542671864, 'colsample_bytree': 0.5421627971697035, 'min_child_weight': 1, 'gamma': 1.2744307552017393, 'reg_alpha': 0.0029714726419747613, 'reg_lambda': 1.3178815595497385e-05, 'max_delta_step': 9}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  73%|███████▎  | 146/200 [02:27<00:38,  1.39it/s]

[I 2025-11-10 17:52:48,967] Trial 146 pruned.

Best trial: 126. Best value: 0.724425:  74%|███████▎  | 147/200 [02:29<01:00,  1.15s/it]

[I 2025-11-10 17:52:51,463] Trial 143 pruned.

Best trial: 126. Best value: 0.724425:  74%|███████▍  | 148/200 [02:30<00:52,  1.01s/it]

[I 2025-11-10 17:52:52,067] Trial 148 pruned.

Best trial: 126. Best value: 0.724425:  74%|███████▍  | 149/200 [02:30<00:42,  1.19it/s]

[I 2025-11-10 17:52:52,447] Trial 149 pruned.

Best trial: 126. Best value: 0.724425:  76%|███████▌  | 151/200 [02:31<00:35,  1.39it/s]

[I 2025-11-10 17:52:53,674] Trial 151 pruned.
[I 2025-11-10 17:52:53,830] Trial 152 pruned.

Best trial: 126. Best value: 0.724425:  76%|███████▌  | 152/200 [02:33<00:45,  1.06it/s]

[I 2025-11-10 17:52:55,319] Trial 153 pruned.

Best trial: 126. Best value: 0.724425:  76%|███████▋  | 153/200 [02:33<00:35,  1.31it/s]

[I 2025-11-10 17:52:55,634] Trial 147 finished with value: 0.6897076023391813 and parameters: {'max_depth': 8, 'learning_rate': 0.024637171851049657, 'n_estimators': 1369, 'subsample': 0.8583578123597174, 'colsample_bytree': 0.5825705586133255, 'min_child_weight': 1, 'gamma': 1.2004922688870943, 'reg_alpha': 0.015793767701456032, 'reg_lambda': 0.0004618235002395664, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  77%|███████▋  | 154/200 [02:37<01:18,  1.70s/it]

[I 2025-11-10 17:52:59,606] Trial 150 finished with value: 0.7124366471734892 and parameters: {'max_depth': 9, 'learning_rate': 0.017951444008594365, 'n_estimators': 1326, 'subsample': 0.9101657861669278, 'colsample_bytree': 0.530627302995649, 'min_child_weight': 1, 'gamma': 1.1295145781214435, 'reg_alpha': 0.022832520567710034, 'reg_lambda': 6.303231005135421e-05, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  78%|███████▊  | 155/200 [02:40<01:32,  2.06s/it]

[I 2025-11-10 17:53:02,511] Trial 154 finished with value: 0.7140350877192982 and parameters: {'max_depth': 8, 'learning_rate': 0.017817769748152426, 'n_estimators': 1500, 'subsample': 0.899372371435085, 'colsample_bytree': 0.563143140306828, 'min_child_weight': 1, 'gamma': 1.558280740355612, 'reg_alpha': 0.025523854514302818, 'reg_lambda': 0.0005029002491513325, 'max_delta_step': 9}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  78%|███████▊  | 156/200 [02:42<01:21,  1.85s/it]

[I 2025-11-10 17:53:03,858] Trial 155 finished with value: 0.704541910331384 and parameters: {'max_depth': 8, 'learning_rate': 0.022499437072456396, 'n_estimators': 1487, 'subsample': 0.8971628028277631, 'colsample_bytree': 0.587454449501964, 'min_child_weight': 1, 'gamma': 1.5853624340494459, 'reg_alpha': 0.023889592535037474, 'reg_lambda': 0.0004659931926553525, 'max_delta_step': 9}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  78%|███████▊  | 157/200 [02:42<01:04,  1.50s/it]

[I 2025-11-10 17:53:04,526] Trial 156 finished with value: 0.7021832358674465 and parameters: {'max_depth': 8, 'learning_rate': 0.02251711380193426, 'n_estimators': 1483, 'subsample': 0.899463288075307, 'colsample_bytree': 0.6246015811389345, 'min_child_weight': 1, 'gamma': 1.6100427140996172, 'reg_alpha': 0.04463904196344645, 'reg_lambda': 8.796032239815726e-06, 'max_delta_step': 9}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  79%|███████▉  | 158/200 [02:44<01:07,  1.61s/it]

[I 2025-11-10 17:53:06,413] Trial 160 pruned.

Best trial: 126. Best value: 0.724425:  80%|███████▉  | 159/200 [02:46<01:07,  1.66s/it]

[I 2025-11-10 17:53:08,177] Trial 157 finished with value: 0.6939181286549707 and parameters: {'max_depth': 9, 'learning_rate': 0.01859881993803411, 'n_estimators': 1499, 'subsample': 0.9454446648915081, 'colsample_bytree': 0.538511143388495, 'min_child_weight': 1, 'gamma': 1.373764191315896, 'reg_alpha': 0.0020752636385486787, 'reg_lambda': 2.507484257961681e-05, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  80%|████████  | 160/200 [02:49<01:27,  2.20s/it]

[I 2025-11-10 17:53:11,633] Trial 158 finished with value: 0.7072514619883041 and parameters: {'max_depth': 9, 'learning_rate': 0.017147381095469504, 'n_estimators': 1492, 'subsample': 0.8873285581888396, 'colsample_bytree': 0.5432406540080329, 'min_child_weight': 1, 'gamma': 0.893969819398141, 'reg_alpha': 0.03349862892960738, 'reg_lambda': 8.762891356361546e-06, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.
[I 2025-11-10 17:53:11,689] Trial 162 pruned.

Best trial: 126. Best value: 0.724425:  81%|████████  | 162/200 [02:50<00:55,  1.45s/it]

[I 2025-11-10 17:53:12,779] Trial 163 pruned.
[I 2025-11-10 17:53:12,805] Trial 164 pruned.

Best trial: 126. Best value: 0.724425:  82%|████████▏ | 164/200 [02:51<00:35,  1.03it/s]

[I 2025-11-10 17:53:13,278] Trial 159 finished with value: 0.7046588693957114 and parameters: {'max_depth': 9, 'learning_rate': 0.018211149751232798, 'n_estimators': 1480, 'subsample': 0.893594232042642, 'colsample_bytree': 0.6237305175910307, 'min_child_weight': 1, 'gamma': 1.3954748967211545, 'reg_alpha': 0.020335590760622156, 'reg_lambda': 9.652270266285927e-06, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  82%|████████▎ | 165/200 [02:51<00:29,  1.20it/s]

[I 2025-11-10 17:53:13,627] Trial 161 pruned.

Best trial: 126. Best value: 0.724425:  83%|████████▎ | 166/200 [02:53<00:32,  1.03it/s]

[I 2025-11-10 17:53:15,023] Trial 167 pruned.

Best trial: 126. Best value: 0.724425:  84%|████████▎ | 167/200 [02:53<00:26,  1.23it/s]

[I 2025-11-10 17:53:15,385] Trial 168 pruned.

Best trial: 126. Best value: 0.724425:  84%|████████▍ | 168/200 [02:54<00:28,  1.14it/s]

[I 2025-11-10 17:53:16,443] Trial 165 pruned.
[I 2025-11-10 17:53:16,481] Trial 170 pruned.

Best trial: 126. Best value: 0.724425:  85%|████████▌ | 170/200 [02:54<00:17,  1.75it/s]

[I 2025-11-10 17:53:16,786] Trial 169 pruned.

Best trial: 126. Best value: 0.724425:  86%|████████▌ | 171/200 [02:56<00:22,  1.28it/s]

[I 2025-11-10 17:53:18,235] Trial 171 pruned.

Best trial: 126. Best value: 0.724425:  86%|████████▌ | 172/200 [02:58<00:28,  1.01s/it]

[I 2025-11-10 17:53:19,921] Trial 166 pruned.

Best trial: 126. Best value: 0.724425:  86%|████████▋ | 173/200 [02:58<00:23,  1.17it/s]

[I 2025-11-10 17:53:20,354] Trial 173 pruned.

Best trial: 126. Best value: 0.724425:  87%|████████▋ | 174/200 [03:03<00:52,  2.01s/it]

[I 2025-11-10 17:53:25,403] Trial 172 finished with value: 0.7030409356725146 and parameters: {'max_depth': 8, 'learning_rate': 0.017709052437268974, 'n_estimators': 1415, 'subsample': 0.9032955030990114, 'colsample_bytree': 0.6294908549252947, 'min_child_weight': 1, 'gamma': 1.4850868406657907, 'reg_alpha': 0.03063218293212298, 'reg_lambda': 1.4069381474121311e-05, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  88%|████████▊ | 175/200 [03:05<00:47,  1.89s/it]

[I 2025-11-10 17:53:27,005] Trial 174 finished with value: 0.6940350877192982 and parameters: {'max_depth': 8, 'learning_rate': 0.015484331125891074, 'n_estimators': 1402, 'subsample': 0.8957884278906775, 'colsample_bytree': 0.6027820632723687, 'min_child_weight': 1, 'gamma': 1.4326080499667777, 'reg_alpha': 0.0219968604348858, 'reg_lambda': 0.00025838994673911027, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  88%|████████▊ | 176/200 [03:07<00:45,  1.91s/it]

[I 2025-11-10 17:53:28,956] Trial 175 finished with value: 0.7004678362573099 and parameters: {'max_depth': 8, 'learning_rate': 0.013244780542519966, 'n_estimators': 1412, 'subsample': 0.8987358659666903, 'colsample_bytree': 0.6005066018346974, 'min_child_weight': 1, 'gamma': 1.3634310819026032, 'reg_alpha': 0.011214323837869682, 'reg_lambda': 0.0003540321679210951, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  88%|████████▊ | 177/200 [03:07<00:35,  1.52s/it]

[I 2025-11-10 17:53:29,534] Trial 176 finished with value: 0.7043079922027291 and parameters: {'max_depth': 8, 'learning_rate': 0.01338797210939815, 'n_estimators': 1412, 'subsample': 0.896602149208829, 'colsample_bytree': 0.6023655162596983, 'min_child_weight': 1, 'gamma': 1.306286964739063, 'reg_alpha': 0.012478822654194126, 'reg_lambda': 0.0003518111682993049, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  89%|████████▉ | 178/200 [03:08<00:31,  1.44s/it]

[I 2025-11-10 17:53:30,785] Trial 179 pruned.

Best trial: 126. Best value: 0.724425:  90%|████████▉ | 179/200 [03:12<00:40,  1.93s/it]

[I 2025-11-10 17:53:33,871] Trial 177 finished with value: 0.6983625730994152 and parameters: {'max_depth': 8, 'learning_rate': 0.019248096671722118, 'n_estimators': 1418, 'subsample': 0.8980047533207879, 'colsample_bytree': 0.5690693328605901, 'min_child_weight': 1, 'gamma': 1.2812776342774603, 'reg_alpha': 0.012068153993640274, 'reg_lambda': 3.2222403529741974e-05, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  90%|█████████ | 180/200 [03:12<00:32,  1.63s/it]

[I 2025-11-10 17:53:34,784] Trial 181 pruned.

Best trial: 126. Best value: 0.724425:  90%|█████████ | 181/200 [03:13<00:24,  1.30s/it]

[I 2025-11-10 17:53:35,329] Trial 178 finished with value: 0.7055360623781677 and parameters: {'max_depth': 8, 'learning_rate': 0.021285762590603195, 'n_estimators': 1423, 'subsample': 0.9272883733474845, 'colsample_bytree': 0.5671855144529132, 'min_child_weight': 1, 'gamma': 1.2725736416080382, 'reg_alpha': 0.012026094498813526, 'reg_lambda': 3.658998303910132e-05, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  91%|█████████ | 182/200 [03:14<00:19,  1.08s/it]

[I 2025-11-10 17:53:35,880] Trial 182 pruned.

Best trial: 126. Best value: 0.724425:  92%|█████████▏| 183/200 [03:14<00:15,  1.07it/s]

[I 2025-11-10 17:53:36,467] Trial 183 pruned.

Best trial: 126. Best value: 0.724425:  92%|█████████▏| 184/200 [03:16<00:19,  1.21s/it]

[I 2025-11-10 17:53:38,334] Trial 180 finished with value: 0.7076218323586744 and parameters: {'max_depth': 8, 'learning_rate': 0.019271087761035338, 'n_estimators': 1469, 'subsample': 0.9263042206426159, 'colsample_bytree': 0.5852075677665437, 'min_child_weight': 1, 'gamma': 1.2525438795272894, 'reg_alpha': 0.03435609049328331, 'reg_lambda': 1.7215825206290104e-05, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  92%|█████████▎| 185/200 [03:21<00:36,  2.41s/it]

[I 2025-11-10 17:53:43,558] Trial 184 finished with value: 0.7161598440545809 and parameters: {'max_depth': 8, 'learning_rate': 0.02115567993612059, 'n_estimators': 1386, 'subsample': 0.9372187048706749, 'colsample_bytree': 0.5921047390715934, 'min_child_weight': 1, 'gamma': 1.0354813066933266, 'reg_alpha': 0.06977073035851712, 'reg_lambda': 1.6632883223314787e-05, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  93%|█████████▎| 186/200 [03:22<00:28,  2.02s/it]

[I 2025-11-10 17:53:44,660] Trial 186 finished with value: 0.6987329434697855 and parameters: {'max_depth': 8, 'learning_rate': 0.021486126721880907, 'n_estimators': 1453, 'subsample': 0.9427277001787424, 'colsample_bytree': 0.5901677030002437, 'min_child_weight': 1, 'gamma': 1.1468487535789307, 'reg_alpha': 0.021102882327645744, 'reg_lambda': 2.3344592439685704e-05, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  94%|█████████▎| 187/200 [03:24<00:25,  1.93s/it]

[I 2025-11-10 17:53:46,388] Trial 185 finished with value: 0.7149122807017545 and parameters: {'max_depth': 8, 'learning_rate': 0.020798466649096074, 'n_estimators': 1388, 'subsample': 0.9399730889706801, 'colsample_bytree': 0.9994718312421473, 'min_child_weight': 1, 'gamma': 1.158171511134554, 'reg_alpha': 0.005765085880289485, 'reg_lambda': 1.636424487111756e-05, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  94%|█████████▍| 188/200 [03:24<00:17,  1.43s/it]

[I 2025-11-10 17:53:46,640] Trial 187 finished with value: 0.7052826510721247 and parameters: {'max_depth': 8, 'learning_rate': 0.021548870769855923, 'n_estimators': 1457, 'subsample': 0.9318134602888772, 'colsample_bytree': 0.5891345715396008, 'min_child_weight': 1, 'gamma': 1.2140611493558564, 'reg_alpha': 0.06162777944849371, 'reg_lambda': 1.6829791919242995e-05, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 126. Best value: 0.724425:  94%|█████████▍| 189/200 [03:26<00:15,  1.41s/it]

[I 2025-11-10 17:53:48,004] Trial 189 pruned.

Best trial: 126. Best value: 0.724425:  95%|█████████▌| 190/200 [03:29<00:20,  2.09s/it]

[I 2025-11-10 17:53:51,687] Trial 188 finished with value: 0.7053996101364522 and parameters: {'max_depth': 8, 'learning_rate': 0.02069754562436933, 'n_estimators': 1388, 'subsample': 0.9372534643758318, 'colsample_bytree': 0.5924216154524324, 'min_child_weight': 1, 'gamma': 1.1523030668824605, 'reg_alpha': 0.07269531314661468, 'reg_lambda': 0.0007558640779506936, 'max_delta_step': 10}. Best is trial 126 with value: 0.7244249512670565.

Best trial: 190. Best value: 0.725302:  96%|█████████▌| 192/200 [03:35<00:17,  2.19s/it]

[I 2025-11-10 17:53:57,046] Trial 191 finished with value: 0.7252826510721248 and parameters: {'max_depth': 8, 'learning_rate': 0.020028180107509185, 'n_estimators': 1385, 'subsample': 0.9352585110337795, 'colsample_bytree': 0.9945096492762532, 'min_child_weight': 1, 'gamma': 1.1741574980937934, 'reg_alpha': 0.22852138056281307, 'reg_lambda': 1.6710676238917752e-05, 'max_delta_step': 10}. Best is trial 191 with value: 0.7252826510721248.
[I 2025-11-10 17:53:57,191] Trial 190 finished with value: 0.7253021442495127 and parameters: {'max_depth': 8, 'learning_rate': 0.018696205538268805, 'n_estimators': 1400, 'subsample': 0.9394631793487966, 'colsample_bytree': 0.995070568826729, 'min_child_weight': 1, 'gamma': 0.8908834611271914, 'reg_alpha': 0.06749794174672308, 'reg_lambda': 1.7816142462518646e-05, 'max_delta_step': 10}. Best is trial 190 with value: 0.7253021442495127.

Best trial: 190. Best value: 0.725302:  96%|█████████▋| 193/200 [03:36<00:13,  1.90s/it]

[I 2025-11-10 17:53:58,395] Trial 192 finished with value: 0.7165302144249512 and parameters: {'max_depth': 8, 'learning_rate': 0.019079479172453236, 'n_estimators': 1387, 'subsample': 0.9357978500776833, 'colsample_bytree': 0.9792551170970017, 'min_child_weight': 1, 'gamma': 1.1631944317554581, 'reg_alpha': 0.07320872784033161, 'reg_lambda': 0.0010541110412488376, 'max_delta_step': 10}. Best is trial 190 with value: 0.7253021442495127.

Best trial: 190. Best value: 0.725302:  97%|█████████▋| 194/200 [03:37<00:09,  1.63s/it]

[I 2025-11-10 17:53:59,419] Trial 196 pruned.

Best trial: 190. Best value: 0.725302:  98%|█████████▊| 195/200 [03:40<00:09,  1.94s/it]

[I 2025-11-10 17:54:02,062] Trial 193 finished with value: 0.717524366471735 and parameters: {'max_depth': 8, 'learning_rate': 0.01921993468144002, 'n_estimators': 1383, 'subsample': 0.9528568751534211, 'colsample_bytree': 0.9829820566867413, 'min_child_weight': 1, 'gamma': 1.1547180502677072, 'reg_alpha': 0.0653592907869266, 'reg_lambda': 0.0007868478775678066, 'max_delta_step': 10}. Best is trial 190 with value: 0.7253021442495127.

Best trial: 190. Best value: 0.725302:  98%|█████████▊| 196/200 [03:41<00:07,  1.76s/it]

[I 2025-11-10 17:54:03,411] Trial 197 pruned.

Best trial: 190. Best value: 0.725302:  98%|█████████▊| 197/200 [03:43<00:05,  1.89s/it]

[I 2025-11-10 17:54:05,611] Trial 195 pruned.

Best trial: 190. Best value: 0.725302:  99%|█████████▉| 198/200 [03:45<00:03,  1.77s/it]

[I 2025-11-10 17:54:07,084] Trial 194 finished with value: 0.7204873294346978 and parameters: {'max_depth': 8, 'learning_rate': 0.019186305605276406, 'n_estimators': 1379, 'subsample': 0.9377364653830843, 'colsample_bytree': 0.9769509280334172, 'min_child_weight': 1, 'gamma': 1.1587582562935324, 'reg_alpha': 0.2046684528361084, 'reg_lambda': 0.0007960382697308236, 'max_delta_step': 10}. Best is trial 190 with value: 0.7253021442495127.

Best trial: 190. Best value: 0.725302: 100%|█████████▉| 199/200 [03:49<00:02,  2.45s/it]

[I 2025-11-10 17:54:11,144] Trial 198 finished with value: 0.7167836257309942 and parameters: {'max_depth': 8, 'learning_rate': 0.01890640138925632, 'n_estimators': 1387, 'subsample': 0.9646055092647277, 'colsample_bytree': 0.9977864072903714, 'min_child_weight': 1, 'gamma': 1.124881738018073, 'reg_alpha': 0.06716327098461963, 'reg_lambda': 0.002047400870601733, 'max_delta_step': 10}. Best is trial 190 with value: 0.7253021442495127.

Best trial: 190. Best value: 0.725302: 100%|██████████| 200/200 [03:50<00:00,  1.15s/it]

[I 2025-11-10 17:54:12,158] Trial 199 finished with value: 0.7193567251461987 and parameters: {'max_depth': 8, 'learning_rate': 0.01925088600636776, 'n_estimators': 1397, 'subsample': 0.9533289543540572, 'colsample_bytree': 0.9957523036928795, 'min_child_weight': 1, 'gamma': 1.129303495032643, 'reg_alpha': 0.304854251849846, 'reg_lambda': 0.0007567175980499947, 'max_delta_step': 10}. Best is trial 190 with value: 0.7253021442495127.

[I 2025-11-10 17:54:13,882] A new study created in memory with name: 19_1_roc_auc
Best trial: 2. Best value: 0.5:   0%|          | 1/200 [00:03<10:49,  3.26s/it]

[I 2025-11-10 17:54:17,143] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.017299423472554032, 'n_estimators': 811, 'subsample': 0.8419791758219989, 'colsample_bytree': 0.5280019086989538, 'min_child_weight': 7, 'gamma': 1.038323369626869, 'reg_alpha': 0.001115489894441784, 'reg_lambda': 2.0141602065887597e-08, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   1%|          | 2/200 [00:03<05:13,  1.58s/it]

[I 2025-11-10 17:54:17,541] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.04272006180682628, 'n_estimators': 848, 'subsample': 0.7876474102121479, 'colsample_bytree': 0.906067113598961, 'min_child_weight': 10, 'gamma': 4.318680865079888, 'reg_alpha': 0.008261917135263912, 'reg_lambda': 8.775051453902833e-06, 'max_delta_step': 10}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▏         | 3/200 [00:03<03:12,  1.02it/s]

[I 2025-11-10 17:54:17,806] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05507875339711192, 'n_estimators': 888, 'subsample': 0.964929062055754, 'colsample_bytree': 0.9813466741267491, 'min_child_weight': 8, 'gamma': 1.6515268547467588, 'reg_alpha': 4.4273692882700916e-05, 'reg_lambda': 7.385746190152135e-07, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▏         | 4/200 [00:05<03:19,  1.02s/it]

[I 2025-11-10 17:54:18,889] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.015474939125906728, 'n_estimators': 1319, 'subsample': 0.8486001751899158, 'colsample_bytree': 0.5407841720594564, 'min_child_weight': 8, 'gamma': 4.593584983371387, 'reg_alpha': 2.8049987975251494, 'reg_lambda': 2.0222087196772294e-06, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▎         | 5/200 [00:06<03:20,  1.03s/it]

[I 2025-11-10 17:54:19,933] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1834800634141465, 'n_estimators': 675, 'subsample': 0.5850239978714233, 'colsample_bytree': 0.6441977433044187, 'min_child_weight': 9, 'gamma': 0.7786711745192743, 'reg_alpha': 0.022960504825677394, 'reg_lambda': 0.0018241348471920566, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   3%|▎         | 6/200 [00:07<03:38,  1.13s/it]

[I 2025-11-10 17:54:21,257] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07297540854249239, 'n_estimators': 667, 'subsample': 0.5534703176979212, 'colsample_bytree': 0.7966911127805996, 'min_child_weight': 10, 'gamma': 0.8044345666735342, 'reg_alpha': 0.0023856694492037805, 'reg_lambda': 0.5431411454863144, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 4. Best value: 0.568693:   4%|▎         | 7/200 [00:07<03:01,  1.06it/s]

[I 2025-11-10 17:54:21,815] Trial 4 finished with value: 0.5686928104575164 and parameters: {'max_depth': 5, 'learning_rate': 0.18138076618268006, 'n_estimators': 786, 'subsample': 0.6303762513578204, 'colsample_bytree': 0.9075363884610699, 'min_child_weight': 1, 'gamma': 3.1558410073464582, 'reg_alpha': 2.6646796521000387e-05, 'reg_lambda': 3.689955220758544e-08, 'max_delta_step': 5}. Best is trial 4 with value: 0.5686928104575164.

Best trial: 8. Best value: 0.600261:   4%|▍         | 8/200 [00:10<04:40,  1.46s/it]

[I 2025-11-10 17:54:24,386] Trial 8 finished with value: 0.6002614379084967 and parameters: {'max_depth': 8, 'learning_rate': 0.2655722399503707, 'n_estimators': 1227, 'subsample': 0.6885065953653011, 'colsample_bytree': 0.647613908678164, 'min_child_weight': 2, 'gamma': 0.44749897814977235, 'reg_alpha': 9.087741095150377e-05, 'reg_lambda': 0.0607285939287824, 'max_delta_step': 1}. Best is trial 8 with value: 0.6002614379084967.

Best trial: 8. Best value: 0.600261:   4%|▍         | 9/200 [00:11<03:46,  1.19s/it]

[I 2025-11-10 17:54:24,965] Trial 9 finished with value: 0.531764705882353 and parameters: {'max_depth': 6, 'learning_rate': 0.15974204149602728, 'n_estimators': 853, 'subsample': 0.7463207649840218, 'colsample_bytree': 0.5543665236188243, 'min_child_weight': 2, 'gamma': 3.9815713915491457, 'reg_alpha': 2.5964209382739664e-07, 'reg_lambda': 3.884603731379012, 'max_delta_step': 1}. Best is trial 8 with value: 0.6002614379084967.

Best trial: 8. Best value: 0.600261:   5%|▌         | 10/200 [00:11<03:02,  1.04it/s]

[I 2025-11-10 17:54:25,428] Trial 6 finished with value: 0.5219607843137255 and parameters: {'max_depth': 10, 'learning_rate': 0.029618236799024818, 'n_estimators': 1181, 'subsample': 0.5711508609684388, 'colsample_bytree': 0.9832179077677574, 'min_child_weight': 1, 'gamma': 4.9489930476986785, 'reg_alpha': 0.4676327057705321, 'reg_lambda': 7.529373526676489e-07, 'max_delta_step': 0}. Best is trial 8 with value: 0.6002614379084967.

Best trial: 13. Best value: 0.671634:   6%|▌         | 11/200 [00:13<03:40,  1.17s/it]

[I 2025-11-10 17:54:27,062] Trial 13 finished with value: 0.6716339869281046 and parameters: {'max_depth': 8, 'learning_rate': 0.2995585689274498, 'n_estimators': 406, 'subsample': 0.6705288943871941, 'colsample_bytree': 0.7038723715113726, 'min_child_weight': 4, 'gamma': 0.02241454769235962, 'reg_alpha': 6.566319949480202e-08, 'reg_lambda': 0.02515815080872977, 'max_delta_step': 8}. Best is trial 13 with value: 0.6716339869281046.

Best trial: 13. Best value: 0.671634:   6%|▌         | 12/200 [00:13<03:16,  1.04s/it]

[I 2025-11-10 17:54:27,821] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.011527307001196394, 'n_estimators': 773, 'subsample': 0.5292935775841884, 'colsample_bytree': 0.6935271394811093, 'min_child_weight': 7, 'gamma': 4.786436864038775, 'reg_alpha': 1.6897074255843363e-08, 'reg_lambda': 9.93341220450753e-07, 'max_delta_step': 6}. Best is trial 13 with value: 0.6716339869281046.

Best trial: 13. Best value: 0.671634:   6%|▋         | 13/200 [00:14<02:31,  1.23it/s]

[I 2025-11-10 17:54:28,100] Trial 14 finished with value: 0.6042483660130719 and parameters: {'max_depth': 8, 'learning_rate': 0.24706211040262463, 'n_estimators': 226, 'subsample': 0.6914321148575628, 'colsample_bytree': 0.6944884945201167, 'min_child_weight': 4, 'gamma': 0.040822788321390524, 'reg_alpha': 1.2678627269425137e-08, 'reg_lambda': 0.008875282366371544, 'max_delta_step': 8}. Best is trial 13 with value: 0.6716339869281046.

Best trial: 13. Best value: 0.671634:   7%|▋         | 14/200 [00:14<02:27,  1.26it/s]

[I 2025-11-10 17:54:28,855] Trial 15 finished with value: 0.633202614379085 and parameters: {'max_depth': 8, 'learning_rate': 0.2967119790306609, 'n_estimators': 223, 'subsample': 0.6837940058799021, 'colsample_bytree': 0.7603476327153464, 'min_child_weight': 4, 'gamma': 0.24001222369967623, 'reg_alpha': 1.4031716542737344e-06, 'reg_lambda': 0.007648759389847164, 'max_delta_step': 8}. Best is trial 13 with value: 0.6716339869281046.

Best trial: 13. Best value: 0.671634:   8%|▊         | 15/200 [00:15<01:57,  1.57it/s]

[I 2025-11-10 17:54:29,123] Trial 16 finished with value: 0.6302614379084968 and parameters: {'max_depth': 8, 'learning_rate': 0.09955669760382532, 'n_estimators': 201, 'subsample': 0.6890901904953102, 'colsample_bytree': 0.7718004963184063, 'min_child_weight': 4, 'gamma': 0.10674731185058581, 'reg_alpha': 6.12880511776252e-07, 'reg_lambda': 0.002680570006327031, 'max_delta_step': 9}. Best is trial 13 with value: 0.6716339869281046.

Best trial: 13. Best value: 0.671634:   8%|▊         | 16/200 [00:15<01:44,  1.77it/s]

[I 2025-11-10 17:54:29,528] Trial 18 pruned.

Best trial: 13. Best value: 0.671634:   8%|▊         | 17/200 [00:15<01:27,  2.10it/s]

[I 2025-11-10 17:54:29,794] Trial 10 finished with value: 0.5211764705882354 and parameters: {'max_depth': 10, 'learning_rate': 0.013157683457293698, 'n_estimators': 1413, 'subsample': 0.821454914872782, 'colsample_bytree': 0.6682355558901449, 'min_child_weight': 2, 'gamma': 3.554945688280845, 'reg_alpha': 0.5681573495799064, 'reg_lambda': 0.07557055369351445, 'max_delta_step': 5}. Best is trial 13 with value: 0.6716339869281046.
[I 2025-11-10 17:54:29,851] Trial 11 pruned.

Best trial: 13. Best value: 0.671634:  10%|▉         | 19/200 [00:16<01:04,  2.82it/s]

[I 2025-11-10 17:54:30,221] Trial 17 finished with value: 0.6479738562091504 and parameters: {'max_depth': 7, 'learning_rate': 0.10851422276740269, 'n_estimators': 286, 'subsample': 0.655387587511162, 'colsample_bytree': 0.808090453102344, 'min_child_weight': 4, 'gamma': 1.8629716551208453, 'reg_alpha': 7.240291004196105e-07, 'reg_lambda': 0.00010729296195300517, 'max_delta_step': 8}. Best is trial 13 with value: 0.6716339869281046.

Best trial: 13. Best value: 0.671634:  10%|█         | 20/200 [00:17<01:44,  1.73it/s]

[I 2025-11-10 17:54:31,478] Trial 19 finished with value: 0.6227450980392156 and parameters: {'max_depth': 7, 'learning_rate': 0.2707411846794903, 'n_estimators': 434, 'subsample': 0.7657994155315663, 'colsample_bytree': 0.7260917320829973, 'min_child_weight': 4, 'gamma': 1.5955570788175961, 'reg_alpha': 5.731063667670258e-06, 'reg_lambda': 0.14061879268750552, 'max_delta_step': 8}. Best is trial 13 with value: 0.6716339869281046.

Best trial: 13. Best value: 0.671634:  11%|█         | 22/200 [00:18<01:10,  2.51it/s]

[I 2025-11-10 17:54:31,760] Trial 20 finished with value: 0.6316339869281046 and parameters: {'max_depth': 7, 'learning_rate': 0.2894556770480703, 'n_estimators': 431, 'subsample': 0.9237360337696097, 'colsample_bytree': 0.7363193181960345, 'min_child_weight': 4, 'gamma': 1.5209314587965728, 'reg_alpha': 5.245143569691492e-06, 'reg_lambda': 8.781890363029538e-05, 'max_delta_step': 8}. Best is trial 13 with value: 0.6716339869281046.
[I 2025-11-10 17:54:31,886] Trial 21 finished with value: 0.6247058823529412 and parameters: {'max_depth': 7, 'learning_rate': 0.1281922804973111, 'n_estimators': 443, 'subsample': 0.7471561579574821, 'colsample_bytree': 0.5973726253380978, 'min_child_weight': 4, 'gamma': 1.4408244211883343, 'reg_alpha': 2.5050436991561962e-06, 'reg_lambda': 0.00024589191978182783, 'max_delta_step': 8}. Best is trial 13 with value: 0.6716339869281046.
[I 2025-11-10 17:54:31,937] Trial 23 pruned.

Best trial: 22. Best value: 0.685033:  13%|█▎        | 26/200 [00:18<00:33,  5.14it/s]

[I 2025-11-10 17:54:32,151] Trial 24 pruned.
[I 2025-11-10 17:54:32,237] Trial 22 finished with value: 0.685032679738562 and parameters: {'max_depth': 7, 'learning_rate': 0.12102937219796595, 'n_estimators': 437, 'subsample': 0.8978505304731825, 'colsample_bytree': 0.8482494338456368, 'min_child_weight': 5, 'gamma': 2.482807294555277, 'reg_alpha': 1.0301350072048564e-07, 'reg_lambda': 7.147234051262262e-05, 'max_delta_step': 10}. Best is trial 22 with value: 0.685032679738562.
[I 2025-11-10 17:54:32,245] Trial 25 pruned.

Best trial: 22. Best value: 0.685033:  14%|█▎        | 27/200 [00:18<00:44,  3.90it/s]

[I 2025-11-10 17:54:32,740] Trial 27 pruned.

Best trial: 22. Best value: 0.685033:  14%|█▍        | 28/200 [00:19<01:02,  2.76it/s]

[I 2025-11-10 17:54:33,447] Trial 26 finished with value: 0.6018300653594771 and parameters: {'max_depth': 9, 'learning_rate': 0.19592319881142523, 'n_estimators': 304, 'subsample': 0.6236032127629817, 'colsample_bytree': 0.7920449271239716, 'min_child_weight': 3, 'gamma': 2.248240874111282, 'reg_alpha': 1.0944590112599455e-07, 'reg_lambda': 0.01128256704567709, 'max_delta_step': 7}. Best is trial 22 with value: 0.685032679738562.

Best trial: 22. Best value: 0.685033:  14%|█▍        | 29/200 [00:19<00:56,  3.05it/s]

[I 2025-11-10 17:54:33,672] Trial 30 pruned.

Best trial: 22. Best value: 0.685033:  15%|█▌        | 30/200 [00:20<00:54,  3.14it/s]

[I 2025-11-10 17:54:33,964] Trial 31 pruned.

Best trial: 22. Best value: 0.685033:  16%|█▌        | 31/200 [00:20<01:01,  2.76it/s]

[I 2025-11-10 17:54:34,439] Trial 33 pruned.

Best trial: 22. Best value: 0.685033:  16%|█▌        | 32/200 [00:20<00:57,  2.90it/s]

[I 2025-11-10 17:54:34,740] Trial 34 pruned.

Best trial: 22. Best value: 0.685033:  16%|█▋        | 33/200 [00:21<00:56,  2.95it/s]

[I 2025-11-10 17:54:35,067] Trial 35 pruned.

Best trial: 22. Best value: 0.685033:  18%|█▊        | 36/200 [00:21<00:36,  4.56it/s]

[I 2025-11-10 17:54:35,463] Trial 28 finished with value: 0.5448366013071896 and parameters: {'max_depth': 6, 'learning_rate': 0.08077542608101713, 'n_estimators': 575, 'subsample': 0.8990450257491034, 'colsample_bytree': 0.8983060309679693, 'min_child_weight': 3, 'gamma': 2.832874890022471, 'reg_alpha': 3.563003837498772e-08, 'reg_lambda': 1.2344810392863776e-05, 'max_delta_step': 9}. Best is trial 22 with value: 0.685032679738562.
[I 2025-11-10 17:54:35,556] Trial 29 finished with value: 0.5004575163398692 and parameters: {'max_depth': 6, 'learning_rate': 0.08334316347355118, 'n_estimators': 546, 'subsample': 0.9971185215410014, 'colsample_bytree': 0.8979488171653701, 'min_child_weight': 3, 'gamma': 2.9816593794041926, 'reg_alpha': 2.0623659898173445e-08, 'reg_lambda': 1.6828275009726186e-05, 'max_delta_step': 9}. Best is trial 22 with value: 0.685032679738562.
[I 2025-11-10 17:54:35,566] Trial 36 pruned.

Best trial: 22. Best value: 0.685033:  18%|█▊        | 37/200 [00:22<00:39,  4.09it/s]

[I 2025-11-10 17:54:35,894] Trial 37 pruned.
[I 2025-11-10 17:54:35,980] Trial 38 pruned.

Best trial: 22. Best value: 0.685033:  20%|█▉        | 39/200 [00:22<00:36,  4.42it/s]

[I 2025-11-10 17:54:36,293] Trial 32 finished with value: 0.6770588235294117 and parameters: {'max_depth': 6, 'learning_rate': 0.1433794201489213, 'n_estimators': 546, 'subsample': 0.9967964893733892, 'colsample_bytree': 0.8850222919887193, 'min_child_weight': 5, 'gamma': 3.022008595295789, 'reg_alpha': 0.00019889670507395219, 'reg_lambda': 9.804147904724158e-06, 'max_delta_step': 9}. Best is trial 22 with value: 0.685032679738562.

Best trial: 22. Best value: 0.685033:  20%|██        | 40/200 [00:22<00:46,  3.41it/s]

[I 2025-11-10 17:54:36,818] Trial 41 pruned.

Best trial: 22. Best value: 0.685033:  20%|██        | 41/200 [00:23<00:52,  3.05it/s]

[I 2025-11-10 17:54:37,253] Trial 39 finished with value: 0.6026143790849673 and parameters: {'max_depth': 7, 'learning_rate': 0.14924723312434204, 'n_estimators': 355, 'subsample': 0.8647439298636918, 'colsample_bytree': 0.7548566379838674, 'min_child_weight': 5, 'gamma': 0.1776779610687605, 'reg_alpha': 1.3528436593360775e-06, 'reg_lambda': 0.0005010649834370967, 'max_delta_step': 8}. Best is trial 22 with value: 0.685032679738562.
[I 2025-11-10 17:54:37,299] Trial 40 finished with value: 0.6767320261437909 and parameters: {'max_depth': 7, 'learning_rate': 0.15390275006494716, 'n_estimators': 263, 'subsample': 0.8645299532337705, 'colsample_bytree': 0.9583922798892252, 'min_child_weight': 5, 'gamma': 0.29365790245525164, 'reg_alpha': 0.0002836805563387349, 'reg_lambda': 1.1295123480191529e-07, 'max_delta_step': 8}. Best is trial 22 with value: 0.685032679738562.

Best trial: 22. Best value: 0.685033:  22%|██▏       | 43/200 [00:23<00:37,  4.18it/s]

[I 2025-11-10 17:54:37,477] Trial 43 pruned.

Best trial: 22. Best value: 0.685033:  22%|██▎       | 45/200 [00:24<00:36,  4.19it/s]

[I 2025-11-10 17:54:37,790] Trial 45 pruned.
[I 2025-11-10 17:54:37,974] Trial 46 pruned.

Best trial: 22. Best value: 0.685033:  23%|██▎       | 46/200 [00:24<00:41,  3.75it/s]

[I 2025-11-10 17:54:38,323] Trial 48 pruned.

Best trial: 22. Best value: 0.685033:  24%|██▎       | 47/200 [00:24<00:37,  4.04it/s]

[I 2025-11-10 17:54:38,519] Trial 47 pruned.

Best trial: 22. Best value: 0.685033:  24%|██▍       | 49/200 [00:25<00:35,  4.27it/s]

[I 2025-11-10 17:54:38,901] Trial 44 finished with value: 0.5618954248366013 and parameters: {'max_depth': 5, 'learning_rate': 0.21901609168470373, 'n_estimators': 265, 'subsample': 0.9744927222950012, 'colsample_bytree': 0.9464365184321436, 'min_child_weight': 4, 'gamma': 3.3345417302791263, 'reg_alpha': 0.02870117382002607, 'reg_lambda': 3.8375931642012555e-06, 'max_delta_step': 10}. Best is trial 22 with value: 0.685032679738562.
[I 2025-11-10 17:54:39,006] Trial 49 pruned.

Best trial: 22. Best value: 0.685033:  25%|██▌       | 50/200 [00:25<00:46,  3.21it/s]

[I 2025-11-10 17:54:39,505] Trial 52 pruned.
[I 2025-11-10 17:54:39,601] Trial 42 finished with value: 0.6796078431372549 and parameters: {'max_depth': 5, 'learning_rate': 0.15727575893836412, 'n_estimators': 695, 'subsample': 0.9523872632763875, 'colsample_bytree': 0.9494337930024128, 'min_child_weight': 5, 'gamma': 3.3632236972866085, 'reg_alpha': 0.0006350050570167798, 'reg_lambda': 9.171551204096168e-08, 'max_delta_step': 10}. Best is trial 22 with value: 0.685032679738562.

Best trial: 22. Best value: 0.685033:  26%|██▌       | 52/200 [00:25<00:35,  4.13it/s]

[I 2025-11-10 17:54:39,825] Trial 53 pruned.

Best trial: 22. Best value: 0.685033:  26%|██▋       | 53/200 [00:27<01:29,  1.65it/s]

[I 2025-11-10 17:54:41,561] Trial 50 finished with value: 0.6116993464052287 and parameters: {'max_depth': 4, 'learning_rate': 0.16934061410696774, 'n_estimators': 627, 'subsample': 0.9363076037002366, 'colsample_bytree': 0.9201293792830789, 'min_child_weight': 4, 'gamma': 4.405588853786084, 'reg_alpha': 0.007789148526525518, 'reg_lambda': 3.784535741152901e-06, 'max_delta_step': 8}. Best is trial 22 with value: 0.685032679738562.
[I 2025-11-10 17:54:41,581] Trial 51 finished with value: 0.6652287581699347 and parameters: {'max_depth': 4, 'learning_rate': 0.17162005682807338, 'n_estimators': 615, 'subsample': 0.9361825800377159, 'colsample_bytree': 0.8717903600698481, 'min_child_weight': 5, 'gamma': 0.8299729528058069, 'reg_alpha': 1.7851200593370662e-05, 'reg_lambda': 9.58858524917298e-07, 'max_delta_step': 8}. Best is trial 22 with value: 0.685032679738562.

Best trial: 22. Best value: 0.685033:  28%|██▊       | 56/200 [00:28<01:06,  2.17it/s]

[I 2025-11-10 17:54:42,466] Trial 55 finished with value: 0.6797385620915033 and parameters: {'max_depth': 4, 'learning_rate': 0.1665551156110371, 'n_estimators': 614, 'subsample': 0.9315302139396311, 'colsample_bytree': 0.9183513480893772, 'min_child_weight': 5, 'gamma': 3.1713844504026087, 'reg_alpha': 0.0016552260733969997, 'reg_lambda': 5.170893151222287e-07, 'max_delta_step': 8}. Best is trial 22 with value: 0.685032679738562.
[I 2025-11-10 17:54:42,643] Trial 54 finished with value: 0.6704575163398692 and parameters: {'max_depth': 4, 'learning_rate': 0.12639891614299031, 'n_estimators': 699, 'subsample': 0.9279266072043618, 'colsample_bytree': 0.9232240005109638, 'min_child_weight': 5, 'gamma': 2.6766284015136343, 'reg_alpha': 0.0020703170477031738, 'reg_lambda': 5.0449587536897225, 'max_delta_step': 9}. Best is trial 22 with value: 0.685032679738562.

Best trial: 22. Best value: 0.685033:  28%|██▊       | 57/200 [00:29<01:14,  1.91it/s]

[I 2025-11-10 17:54:43,356] Trial 59 pruned.

Best trial: 22. Best value: 0.685033:  30%|██▉       | 59/200 [00:31<01:22,  1.71it/s]

[I 2025-11-10 17:54:44,746] Trial 57 finished with value: 0.656797385620915 and parameters: {'max_depth': 4, 'learning_rate': 0.12111926703062577, 'n_estimators': 704, 'subsample': 0.8823860610759892, 'colsample_bytree': 0.8765070901342016, 'min_child_weight': 5, 'gamma': 0.8490942880653736, 'reg_alpha': 0.0002712913682069435, 'reg_lambda': 3.7572284550473304e-07, 'max_delta_step': 9}. Best is trial 22 with value: 0.685032679738562.
[I 2025-11-10 17:54:44,899] Trial 56 finished with value: 0.6462745098039215 and parameters: {'max_depth': 6, 'learning_rate': 0.12275029005703114, 'n_estimators': 737, 'subsample': 0.9786743504120302, 'colsample_bytree': 0.8724882140258492, 'min_child_weight': 5, 'gamma': 3.0999463132762224, 'reg_alpha': 0.00024288549750726214, 'reg_lambda': 3.6971353483580305e-08, 'max_delta_step': 9}. Best is trial 22 with value: 0.685032679738562.

Best trial: 22. Best value: 0.685033:  30%|███       | 60/200 [00:31<01:23,  1.68it/s]

[I 2025-11-10 17:54:45,525] Trial 61 pruned.

Best trial: 22. Best value: 0.685033:  30%|███       | 61/200 [00:31<01:12,  1.93it/s]

[I 2025-11-10 17:54:45,844] Trial 58 finished with value: 0.6601960784313725 and parameters: {'max_depth': 3, 'learning_rate': 0.1258812755069475, 'n_estimators': 730, 'subsample': 0.9138794517052964, 'colsample_bytree': 0.9934382817177041, 'min_child_weight': 5, 'gamma': 4.164117151886492, 'reg_alpha': 0.12940755792650752, 'reg_lambda': 3.4855032063175643e-07, 'max_delta_step': 9}. Best is trial 22 with value: 0.685032679738562.

Best trial: 22. Best value: 0.685033:  31%|███       | 62/200 [00:33<01:51,  1.24it/s]

[I 2025-11-10 17:54:47,365] Trial 60 finished with value: 0.6591503267973856 and parameters: {'max_depth': 5, 'learning_rate': 0.09429490974836462, 'n_estimators': 901, 'subsample': 0.9717856622197927, 'colsample_bytree': 0.9685191181349136, 'min_child_weight': 5, 'gamma': 3.5786569371021684, 'reg_alpha': 0.0002180788706725697, 'reg_lambda': 3.332791161012767e-07, 'max_delta_step': 10}. Best is trial 22 with value: 0.685032679738562.

Best trial: 22. Best value: 0.685033:  32%|███▏      | 64/200 [00:34<01:11,  1.89it/s]

[I 2025-11-10 17:54:47,730] Trial 63 finished with value: 0.5985620915032679 and parameters: {'max_depth': 5, 'learning_rate': 0.15216444159972692, 'n_estimators': 484, 'subsample': 0.9480603673509511, 'colsample_bytree': 0.6637938715351801, 'min_child_weight': 4, 'gamma': 3.574588613559878, 'reg_alpha': 0.0010140640736795187, 'reg_lambda': 4.554833310066041e-08, 'max_delta_step': 10}. Best is trial 22 with value: 0.685032679738562.
[I 2025-11-10 17:54:47,896] Trial 65 pruned.

Best trial: 22. Best value: 0.685033:  32%|███▎      | 65/200 [00:34<01:04,  2.11it/s]

[I 2025-11-10 17:54:48,240] Trial 64 finished with value: 0.6201307189542483 and parameters: {'max_depth': 4, 'learning_rate': 0.1845573463353488, 'n_estimators': 467, 'subsample': 0.9589658642968936, 'colsample_bytree': 0.9160819782499827, 'min_child_weight': 4, 'gamma': 3.5887249267718597, 'reg_alpha': 0.0015068649409664724, 'reg_lambda': 2.700772064951467, 'max_delta_step': 10}. Best is trial 22 with value: 0.685032679738562.
[I 2025-11-10 17:54:48,246] Trial 66 pruned.

Best trial: 22. Best value: 0.685033:  34%|███▎      | 67/200 [00:34<00:44,  2.99it/s]

[I 2025-11-10 17:54:48,585] Trial 67 pruned.

Best trial: 22. Best value: 0.685033:  34%|███▍      | 69/200 [00:35<00:33,  3.92it/s]

[I 2025-11-10 17:54:48,809] Trial 68 pruned.
[I 2025-11-10 17:54:48,916] Trial 69 pruned.

Best trial: 22. Best value: 0.685033:  36%|███▌      | 71/200 [00:35<00:28,  4.56it/s]

[I 2025-11-10 17:54:49,107] Trial 70 pruned.
[I 2025-11-10 17:54:49,275] Trial 62 finished with value: 0.59359477124183 and parameters: {'max_depth': 5, 'learning_rate': 0.09388831637427672, 'n_estimators': 837, 'subsample': 0.9557876707670949, 'colsample_bytree': 0.9700720117898995, 'min_child_weight': 4, 'gamma': 3.637126295298138, 'reg_alpha': 0.00103552239832982, 'reg_lambda': 1.7406942972711527e-06, 'max_delta_step': 10}. Best is trial 22 with value: 0.685032679738562.

Best trial: 22. Best value: 0.685033:  36%|███▋      | 73/200 [00:35<00:29,  4.29it/s]

[I 2025-11-10 17:54:49,650] Trial 71 pruned.
[I 2025-11-10 17:54:49,812] Trial 72 pruned.

Best trial: 22. Best value: 0.685033:  37%|███▋      | 74/200 [00:37<01:35,  1.32it/s]

[I 2025-11-10 17:54:51,835] Trial 74 finished with value: 0.6550980392156862 and parameters: {'max_depth': 4, 'learning_rate': 0.14103974962009072, 'n_estimators': 591, 'subsample': 0.9350027400004156, 'colsample_bytree': 0.8504556466928843, 'min_child_weight': 5, 'gamma': 0.27583963357181174, 'reg_alpha': 3.217936471792834e-05, 'reg_lambda': 9.563746784810246e-07, 'max_delta_step': 8}. Best is trial 22 with value: 0.685032679738562.

Best trial: 75. Best value: 0.693268:  38%|███▊      | 76/200 [00:38<01:06,  1.85it/s]

[I 2025-11-10 17:54:52,388] Trial 75 finished with value: 0.6932679738562091 and parameters: {'max_depth': 4, 'learning_rate': 0.1673318893138467, 'n_estimators': 623, 'subsample': 0.937744600466336, 'colsample_bytree': 0.8852513882826262, 'min_child_weight': 5, 'gamma': 2.925971391120378, 'reg_alpha': 5.3942759856638236e-08, 'reg_lambda': 1.0058752040092922e-06, 'max_delta_step': 7}. Best is trial 75 with value: 0.6932679738562091.
[I 2025-11-10 17:54:52,554] Trial 76 finished with value: 0.672875816993464 and parameters: {'max_depth': 4, 'learning_rate': 0.16180106974256647, 'n_estimators': 617, 'subsample': 0.9283378435093591, 'colsample_bytree': 0.8560356391794907, 'min_child_weight': 5, 'gamma': 0.3581882083547878, 'reg_alpha': 0.0005325986422739632, 'reg_lambda': 8.240688374403358e-07, 'max_delta_step': 8}. Best is trial 75 with value: 0.6932679738562091.

Best trial: 75. Best value: 0.693268:  38%|███▊      | 77/200 [00:38<00:53,  2.29it/s]

[I 2025-11-10 17:54:52,746] Trial 73 finished with value: 0.6763398692810457 and parameters: {'max_depth': 6, 'learning_rate': 0.1437768248075758, 'n_estimators': 801, 'subsample': 0.9325444172652072, 'colsample_bytree': 0.8899897554006039, 'min_child_weight': 5, 'gamma': 2.915417497732933, 'reg_alpha': 4.656683927319918e-06, 'reg_lambda': 0.0002282506448395773, 'max_delta_step': 8}. Best is trial 75 with value: 0.6932679738562091.

Best trial: 75. Best value: 0.693268:  39%|███▉      | 78/200 [00:39<00:47,  2.58it/s]

[I 2025-11-10 17:54:53,017] Trial 79 pruned.

Best trial: 75. Best value: 0.693268:  40%|███▉      | 79/200 [00:39<01:01,  1.96it/s]

[I 2025-11-10 17:54:53,815] Trial 81 pruned.

Best trial: 75. Best value: 0.693268:  40%|████      | 80/200 [00:40<01:00,  1.97it/s]

[I 2025-11-10 17:54:54,319] Trial 78 finished with value: 0.6824183006535949 and parameters: {'max_depth': 8, 'learning_rate': 0.11640901062327566, 'n_estimators': 400, 'subsample': 0.875897248577177, 'colsample_bytree': 0.8906469278078997, 'min_child_weight': 5, 'gamma': 2.0935459791547633, 'reg_alpha': 2.426024686259377e-07, 'reg_lambda': 0.00020543655217482407, 'max_delta_step': 7}. Best is trial 75 with value: 0.6932679738562091.

Best trial: 75. Best value: 0.693268:  41%|████      | 82/200 [00:41<00:47,  2.50it/s]

[I 2025-11-10 17:54:54,894] Trial 77 finished with value: 0.679673202614379 and parameters: {'max_depth': 3, 'learning_rate': 0.16263581970931273, 'n_estimators': 673, 'subsample': 0.9253952524179241, 'colsample_bytree': 0.8822479605621266, 'min_child_weight': 5, 'gamma': 0.01950527164867604, 'reg_alpha': 5.582815390610158e-08, 'reg_lambda': 1.7972418056688304e-07, 'max_delta_step': 8}. Best is trial 75 with value: 0.6932679738562091.
[I 2025-11-10 17:54:54,994] Trial 83 pruned.

Best trial: 75. Best value: 0.693268:  42%|████▏     | 83/200 [00:42<01:06,  1.75it/s]

[I 2025-11-10 17:54:55,962] Trial 85 pruned.

Best trial: 75. Best value: 0.693268:  42%|████▏     | 84/200 [00:42<01:18,  1.49it/s]

[I 2025-11-10 17:54:56,874] Trial 80 finished with value: 0.6866666666666666 and parameters: {'max_depth': 6, 'learning_rate': 0.16646440704566615, 'n_estimators': 912, 'subsample': 0.9976535050170214, 'colsample_bytree': 0.8569293271963119, 'min_child_weight': 5, 'gamma': 2.7584756549264426, 'reg_alpha': 1.8019919196711643e-07, 'reg_lambda': 0.00022285874783840168, 'max_delta_step': 7}. Best is trial 75 with value: 0.6932679738562091.

Best trial: 75. Best value: 0.693268:  42%|████▎     | 85/200 [00:43<01:04,  1.78it/s]

[I 2025-11-10 17:54:57,176] Trial 82 finished with value: 0.6756209150326796 and parameters: {'max_depth': 3, 'learning_rate': 0.11767227396977607, 'n_estimators': 761, 'subsample': 0.8783287149790033, 'colsample_bytree': 0.8584527783164871, 'min_child_weight': 5, 'gamma': 3.0013628411081896, 'reg_alpha': 5.41389074882944e-05, 'reg_lambda': 5.682900067143575e-07, 'max_delta_step': 6}. Best is trial 75 with value: 0.6932679738562091.

Best trial: 75. Best value: 0.693268:  43%|████▎     | 86/200 [00:43<00:56,  2.03it/s]

[I 2025-11-10 17:54:57,513] Trial 88 pruned.

Best trial: 75. Best value: 0.693268:  44%|████▎     | 87/200 [00:43<00:47,  2.37it/s]

[I 2025-11-10 17:54:57,765] Trial 87 pruned.
[I 2025-11-10 17:54:57,785] Trial 84 finished with value: 0.6758823529411764 and parameters: {'max_depth': 3, 'learning_rate': 0.14715083586736105, 'n_estimators': 664, 'subsample': 0.871086840806772, 'colsample_bytree': 0.9086904598915192, 'min_child_weight': 5, 'gamma': 2.999046138510391, 'reg_alpha': 1.0005599923523214e-08, 'reg_lambda': 3.241215902963998e-05, 'max_delta_step': 6}. Best is trial 75 with value: 0.6932679738562091.

Best trial: 75. Best value: 0.693268:  44%|████▍     | 89/200 [00:44<00:34,  3.25it/s]

[I 2025-11-10 17:54:58,118] Trial 89 pruned.

Best trial: 75. Best value: 0.693268:  46%|████▌     | 91/200 [00:45<00:35,  3.04it/s]

[I 2025-11-10 17:54:58,810] Trial 91 pruned.
[I 2025-11-10 17:54:58,927] Trial 90 pruned.

Best trial: 75. Best value: 0.693268:  46%|████▌     | 92/200 [00:45<00:33,  3.21it/s]

[I 2025-11-10 17:54:59,193] Trial 92 pruned.

Best trial: 75. Best value: 0.693268:  46%|████▋     | 93/200 [00:45<00:33,  3.19it/s]

[I 2025-11-10 17:54:59,514] Trial 86 finished with value: 0.6777777777777778 and parameters: {'max_depth': 3, 'learning_rate': 0.14249473726319126, 'n_estimators': 760, 'subsample': 0.8811601732804858, 'colsample_bytree': 0.8860687714039802, 'min_child_weight': 5, 'gamma': 0.007271547243882967, 'reg_alpha': 1.566606032749805e-08, 'reg_lambda': 5.624715677692024e-05, 'max_delta_step': 8}. Best is trial 75 with value: 0.6932679738562091.

Best trial: 75. Best value: 0.693268:  47%|████▋     | 94/200 [00:46<00:38,  2.73it/s]

[I 2025-11-10 17:55:00,011] Trial 93 pruned.

Best trial: 75. Best value: 0.693268:  48%|████▊     | 95/200 [00:46<00:48,  2.19it/s]

[I 2025-11-10 17:55:00,690] Trial 97 pruned.

Best trial: 75. Best value: 0.693268:  48%|████▊     | 97/200 [00:48<01:08,  1.50it/s]

[I 2025-11-10 17:55:02,658] Trial 96 finished with value: 0.6632679738562091 and parameters: {'max_depth': 3, 'learning_rate': 0.13319538776379075, 'n_estimators': 752, 'subsample': 0.8969750919735557, 'colsample_bytree': 0.8419606356370012, 'min_child_weight': 5, 'gamma': 0.18051087713260017, 'reg_alpha': 3.007451938324845e-08, 'reg_lambda': 1.954841483287051e-07, 'max_delta_step': 8}. Best is trial 75 with value: 0.6932679738562091.
[I 2025-11-10 17:55:02,762] Trial 95 finished with value: 0.6813725490196079 and parameters: {'max_depth': 6, 'learning_rate': 0.13546394121997252, 'n_estimators': 801, 'subsample': 0.9025823866593157, 'colsample_bytree': 0.8599605303991227, 'min_child_weight': 5, 'gamma': 2.823860954199919, 'reg_alpha': 2.9261324610929187e-08, 'reg_lambda': 0.000650107716435708, 'max_delta_step': 8}. Best is trial 75 with value: 0.6932679738562091.

Best trial: 75. Best value: 0.693268:  50%|████▉     | 99/200 [00:49<00:46,  2.17it/s]

[I 2025-11-10 17:55:03,159] Trial 98 finished with value: 0.6744444444444444 and parameters: {'max_depth': 3, 'learning_rate': 0.042156499063667405, 'n_estimators': 571, 'subsample': 0.8917900238033607, 'colsample_bytree': 0.8398738106660526, 'min_child_weight': 5, 'gamma': 2.7471909223790476, 'reg_alpha': 2.6624263254653317e-08, 'reg_lambda': 6.790726672318287e-06, 'max_delta_step': 9}. Best is trial 75 with value: 0.6932679738562091.
[I 2025-11-10 17:55:03,329] Trial 99 pruned.

Best trial: 75. Best value: 0.693268:  50%|█████     | 100/200 [00:49<00:44,  2.23it/s]

[I 2025-11-10 17:55:03,746] Trial 101 pruned.

Best trial: 75. Best value: 0.693268:  50%|█████     | 101/200 [00:50<00:41,  2.36it/s]

[I 2025-11-10 17:55:04,106] Trial 102 pruned.
[I 2025-11-10 17:55:04,115] Trial 100 pruned.

Best trial: 75. Best value: 0.693268:  52%|█████▏    | 103/200 [00:50<00:32,  3.03it/s]

[I 2025-11-10 17:55:04,551] Trial 103 pruned.

Best trial: 75. Best value: 0.693268:  52%|█████▏    | 104/200 [00:50<00:30,  3.17it/s]

[I 2025-11-10 17:55:04,824] Trial 94 finished with value: 0.6784313725490196 and parameters: {'max_depth': 6, 'learning_rate': 0.1335057797857495, 'n_estimators': 1334, 'subsample': 0.9049653908686754, 'colsample_bytree': 0.8438763726728538, 'min_child_weight': 5, 'gamma': 2.7999949278549563, 'reg_alpha': 5.821541849338598e-07, 'reg_lambda': 0.0005369909453184392, 'max_delta_step': 8}. Best is trial 75 with value: 0.6932679738562091.
[I 2025-11-10 17:55:04,842] Trial 105 pruned.

Best trial: 75. Best value: 0.693268:  53%|█████▎    | 106/200 [00:53<01:04,  1.45it/s]

[I 2025-11-10 17:55:07,252] Trial 104 finished with value: 0.66 and parameters: {'max_depth': 8, 'learning_rate': 0.13148008798336314, 'n_estimators': 700, 'subsample': 0.8601370196105128, 'colsample_bytree': 0.9304262954275268, 'min_child_weight': 5, 'gamma': 3.1043729151252806, 'reg_alpha': 1.0919633206514457e-07, 'reg_lambda': 0.00462763248227076, 'max_delta_step': 8}. Best is trial 75 with value: 0.6932679738562091.

Best trial: 75. Best value: 0.693268:  54%|█████▍    | 108/200 [00:56<01:55,  1.25s/it]

[I 2025-11-10 17:55:10,416] Trial 107 finished with value: 0.6790849673202614 and parameters: {'max_depth': 5, 'learning_rate': 0.13402924995945498, 'n_estimators': 1342, 'subsample': 0.8800439281704519, 'colsample_bytree': 0.832598201191778, 'min_child_weight': 5, 'gamma': 2.5413843369328077, 'reg_alpha': 9.612205513963268e-07, 'reg_lambda': 0.0013921749198338197, 'max_delta_step': 8}. Best is trial 75 with value: 0.6932679738562091.
[I 2025-11-10 17:55:10,434] Trial 106 finished with value: 0.6539215686274511 and parameters: {'max_depth': 7, 'learning_rate': 0.13646285771225322, 'n_estimators': 1374, 'subsample': 0.8549115728949713, 'colsample_bytree': 0.9346333130587112, 'min_child_weight': 5, 'gamma': 3.1092391851643595, 'reg_alpha': 0.00016657649099500695, 'reg_lambda': 8.155302433939493e-05, 'max_delta_step': 8}. Best is trial 75 with value: 0.6932679738562091.
[I 2025-11-10 17:55:10,436] Trial 108 finished with value: 0.6503921568627451 and parameters: {'max_depth': 6, 'learning_rate': 0.14579903448227893, 'n_estimators': 1333, 'subsample': 0.9219792349795759, 'colsample_bytree': 0.8299445503615284, 'min_child_weight': 5, 'gamma': 2.350564825032563, 'reg_alpha': 1.184663534567581e-06, 'reg_lambda': 8.198090921738958e-05, 'max_delta_step': 7}. Best is trial 75 with value: 0.6932679738562091.

Best trial: 75. Best value: 0.693268:  55%|█████▌    | 110/200 [00:57<01:14,  1.21it/s]

[I 2025-11-10 17:55:11,586] Trial 112 pruned.

Best trial: 75. Best value: 0.693268:  56%|█████▌    | 111/200 [00:59<01:33,  1.05s/it]

[I 2025-11-10 17:55:13,602] Trial 109 finished with value: 0.62718954248366 and parameters: {'max_depth': 6, 'learning_rate': 0.1492956172424611, 'n_estimators': 1420, 'subsample': 0.9213630170856091, 'colsample_bytree': 0.8065209743976136, 'min_child_weight': 4, 'gamma': 2.6112931391384793, 'reg_alpha': 8.962954965786244e-07, 'reg_lambda': 9.738744606411488e-05, 'max_delta_step': 7}. Best is trial 75 with value: 0.6932679738562091.

Best trial: 75. Best value: 0.693268:  56%|█████▌    | 112/200 [01:00<01:34,  1.07s/it]

[I 2025-11-10 17:55:14,740] Trial 114 pruned.

Best trial: 110. Best value: 0.697712:  56%|█████▋    | 113/200 [01:02<01:40,  1.15s/it]

[I 2025-11-10 17:55:16,161] Trial 110 finished with value: 0.6977124183006537 and parameters: {'max_depth': 4, 'learning_rate': 0.20878566805360635, 'n_estimators': 1359, 'subsample': 0.8824878476330258, 'colsample_bytree': 0.8099051600031637, 'min_child_weight': 5, 'gamma': 2.3396785988546136, 'reg_alpha': 8.893771376803957e-07, 'reg_lambda': 0.002415198630323374, 'max_delta_step': 7}. Best is trial 110 with value: 0.6977124183006537.

Best trial: 110. Best value: 0.697712:  57%|█████▋    | 114/200 [01:02<01:22,  1.05it/s]

[I 2025-11-10 17:55:16,533] Trial 111 finished with value: 0.6461437908496732 and parameters: {'max_depth': 4, 'learning_rate': 0.2340782510246182, 'n_estimators': 1446, 'subsample': 0.8795259097032112, 'colsample_bytree': 0.8086064070809498, 'min_child_weight': 4, 'gamma': 2.5562115973226747, 'reg_alpha': 4.800450089430138e-07, 'reg_lambda': 0.0032083743352244046, 'max_delta_step': 7}. Best is trial 110 with value: 0.6977124183006537.

Best trial: 110. Best value: 0.697712:  57%|█████▊    | 115/200 [01:03<01:09,  1.23it/s]

[I 2025-11-10 17:55:16,940] Trial 113 finished with value: 0.6832026143790848 and parameters: {'max_depth': 5, 'learning_rate': 0.11993437802001587, 'n_estimators': 1283, 'subsample': 0.8868969085385401, 'colsample_bytree': 0.8141598895511089, 'min_child_weight': 5, 'gamma': 2.174407121693421, 'reg_alpha': 6.62526033258813e-07, 'reg_lambda': 0.0020139549921594944, 'max_delta_step': 4}. Best is trial 110 with value: 0.6977124183006537.

Best trial: 110. Best value: 0.697712:  58%|█████▊    | 116/200 [01:03<00:54,  1.54it/s]

[I 2025-11-10 17:55:17,156] Trial 115 finished with value: 0.6607843137254902 and parameters: {'max_depth': 5, 'learning_rate': 0.17861157478321704, 'n_estimators': 512, 'subsample': 0.9452949438431715, 'colsample_bytree': 0.8501106612722785, 'min_child_weight': 5, 'gamma': 2.689907609656005, 'reg_alpha': 4.517609472909697e-07, 'reg_lambda': 0.00017974538192542318, 'max_delta_step': 9}. Best is trial 110 with value: 0.6977124183006537.

Best trial: 110. Best value: 0.697712:  58%|█████▊    | 117/200 [01:03<00:44,  1.88it/s]

[I 2025-11-10 17:55:17,387] Trial 116 pruned.

Best trial: 110. Best value: 0.697712:  59%|█████▉    | 118/200 [01:08<02:31,  1.84s/it]

[I 2025-11-10 17:55:22,497] Trial 118 finished with value: 0.6390196078431373 and parameters: {'max_depth': 5, 'learning_rate': 0.015335443481697844, 'n_estimators': 1286, 'subsample': 0.9406782502037524, 'colsample_bytree': 0.8308563418756361, 'min_child_weight': 5, 'gamma': 2.047262707435236, 'reg_alpha': 3.077590787884613e-07, 'reg_lambda': 0.003957833662147123, 'max_delta_step': 4}. Best is trial 110 with value: 0.6977124183006537.
[I 2025-11-10 17:55:22,521] Trial 119 finished with value: 0.6803921568627451 and parameters: {'max_depth': 5, 'learning_rate': 0.2741788727577116, 'n_estimators': 1288, 'subsample': 0.9254166856944932, 'colsample_bytree': 0.8220691494265661, 'min_child_weight': 5, 'gamma': 2.2252653583300663, 'reg_alpha': 7.835216412165221e-07, 'reg_lambda': 0.00030667662617156623, 'max_delta_step': 6}. Best is trial 110 with value: 0.6977124183006537.

Best trial: 110. Best value: 0.697712:  60%|██████    | 120/200 [01:09<01:28,  1.11s/it]

[I 2025-11-10 17:55:22,922] Trial 117 finished with value: 0.6307843137254903 and parameters: {'max_depth': 4, 'learning_rate': 0.015323219174419221, 'n_estimators': 1497, 'subsample': 0.9425201316515548, 'colsample_bytree': 0.8508018325032974, 'min_child_weight': 5, 'gamma': 2.1574473159010137, 'reg_alpha': 1.3524717814449355e-07, 'reg_lambda': 0.00018307080057669575, 'max_delta_step': 8}. Best is trial 110 with value: 0.6977124183006537.

Best trial: 110. Best value: 0.697712:  60%|██████    | 121/200 [01:09<01:16,  1.04it/s]

[I 2025-11-10 17:55:23,432] Trial 120 finished with value: 0.6709150326797385 and parameters: {'max_depth': 5, 'learning_rate': 0.15977479515620324, 'n_estimators': 1474, 'subsample': 0.9244437484325279, 'colsample_bytree': 0.7699869731792095, 'min_child_weight': 5, 'gamma': 1.765933106651677, 'reg_alpha': 1.5465188537942599e-06, 'reg_lambda': 0.016341979285255746, 'max_delta_step': 4}. Best is trial 110 with value: 0.6977124183006537.

Best trial: 110. Best value: 0.697712:  62%|██████▏   | 123/200 [01:10<00:48,  1.59it/s]

[I 2025-11-10 17:55:23,808] Trial 121 pruned.
[I 2025-11-10 17:55:23,937] Trial 122 pruned.

Best trial: 110. Best value: 0.697712:  62%|██████▏   | 124/200 [01:10<00:41,  1.83it/s]

[I 2025-11-10 17:55:24,270] Trial 123 pruned.

Best trial: 110. Best value: 0.697712:  62%|██████▎   | 125/200 [01:10<00:40,  1.87it/s]

[I 2025-11-10 17:55:24,780] Trial 124 pruned.

Best trial: 110. Best value: 0.697712:  63%|██████▎   | 126/200 [01:15<02:09,  1.75s/it]

[I 2025-11-10 17:55:29,524] Trial 125 finished with value: 0.6947712418300654 and parameters: {'max_depth': 5, 'learning_rate': 0.2543164453821486, 'n_estimators': 1319, 'subsample': 0.889207426768762, 'colsample_bytree': 0.7959508804348925, 'min_child_weight': 5, 'gamma': 2.3013126172328353, 'reg_alpha': 4.463657324659734e-08, 'reg_lambda': 0.000374990422860536, 'max_delta_step': 6}. Best is trial 110 with value: 0.6977124183006537.

Best trial: 110. Best value: 0.697712:  64%|██████▎   | 127/200 [01:15<01:35,  1.31s/it]

[I 2025-11-10 17:55:29,754] Trial 126 finished with value: 0.6694771241830064 and parameters: {'max_depth': 5, 'learning_rate': 0.20437164633361254, 'n_estimators': 1335, 'subsample': 0.8970233275305831, 'colsample_bytree': 0.8577505248014939, 'min_child_weight': 5, 'gamma': 2.898020348598988, 'reg_alpha': 3.331837864422453e-06, 'reg_lambda': 0.0003189827354854529, 'max_delta_step': 2}. Best is trial 110 with value: 0.6977124183006537.

Best trial: 110. Best value: 0.697712:  64%|██████▍   | 128/200 [01:16<01:11,  1.01it/s]

[I 2025-11-10 17:55:29,973] Trial 127 finished with value: 0.687124183006536 and parameters: {'max_depth': 5, 'learning_rate': 0.20360255918949996, 'n_estimators': 1339, 'subsample': 0.8908534951941445, 'colsample_bytree': 0.797234762852915, 'min_child_weight': 5, 'gamma': 4.979647205662046, 'reg_alpha': 7.342539735245092e-07, 'reg_lambda': 0.00034346587893350204, 'max_delta_step': 6}. Best is trial 110 with value: 0.6977124183006537.

Best trial: 128. Best value: 0.707255:  64%|██████▍   | 129/200 [01:16<00:58,  1.21it/s]

[I 2025-11-10 17:55:30,412] Trial 128 finished with value: 0.7072549019607844 and parameters: {'max_depth': 5, 'learning_rate': 0.19177718585125783, 'n_estimators': 1305, 'subsample': 0.9579210962906906, 'colsample_bytree': 0.7987897111202562, 'min_child_weight': 5, 'gamma': 2.46973091214376, 'reg_alpha': 2.9770943619210615e-06, 'reg_lambda': 0.00034065874368669066, 'max_delta_step': 6}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  65%|██████▌   | 130/200 [01:16<00:50,  1.40it/s]

[I 2025-11-10 17:55:30,869] Trial 130 pruned.

Best trial: 128. Best value: 0.707255:  66%|██████▌   | 131/200 [01:18<00:59,  1.16it/s]

[I 2025-11-10 17:55:32,077] Trial 133 pruned.

Best trial: 128. Best value: 0.707255:  66%|██████▌   | 132/200 [01:21<01:36,  1.42s/it]

[I 2025-11-10 17:55:34,791] Trial 131 finished with value: 0.6233333333333334 and parameters: {'max_depth': 4, 'learning_rate': 0.2211766923922158, 'n_estimators': 1215, 'subsample': 0.8649425871415919, 'colsample_bytree': 0.7342304641892913, 'min_child_weight': 5, 'gamma': 4.7487208327065344, 'reg_alpha': 7.084105168611967e-08, 'reg_lambda': 0.0003804095765492444, 'max_delta_step': 6}. Best is trial 128 with value: 0.7072549019607844.
[I 2025-11-10 17:55:34,971] Trial 129 finished with value: 0.6840522875816993 and parameters: {'max_depth': 5, 'learning_rate': 0.21933069084772153, 'n_estimators': 1266, 'subsample': 0.9553744596138357, 'colsample_bytree': 0.7973182654706188, 'min_child_weight': 5, 'gamma': 2.5350745365882257, 'reg_alpha': 4.4438749385347575e-08, 'reg_lambda': 0.0023288506597569703, 'max_delta_step': 6}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  67%|██████▋   | 134/200 [01:21<01:02,  1.05it/s]

[I 2025-11-10 17:55:35,697] Trial 132 finished with value: 0.6864052287581699 and parameters: {'max_depth': 4, 'learning_rate': 0.22374031425899535, 'n_estimators': 1259, 'subsample': 0.956804007341194, 'colsample_bytree': 0.8006920919903426, 'min_child_weight': 5, 'gamma': 2.2327032954739585, 'reg_alpha': 3.0821348617098247e-07, 'reg_lambda': 0.0007845251121533519, 'max_delta_step': 6}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  68%|██████▊   | 135/200 [01:23<01:20,  1.24s/it]

[I 2025-11-10 17:55:37,619] Trial 134 finished with value: 0.6805882352941176 and parameters: {'max_depth': 5, 'learning_rate': 0.19134909421512977, 'n_estimators': 1311, 'subsample': 0.9527156775180196, 'colsample_bytree': 0.785958533167507, 'min_child_weight': 5, 'gamma': 4.666921790051024, 'reg_alpha': 1.5088035603793522e-07, 'reg_lambda': 0.00031290610056949837, 'max_delta_step': 6}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  68%|██████▊   | 137/200 [01:26<01:12,  1.15s/it]

[I 2025-11-10 17:55:40,045] Trial 136 finished with value: 0.6791503267973857 and parameters: {'max_depth': 5, 'learning_rate': 0.19312058732117077, 'n_estimators': 1167, 'subsample': 0.9559173639698048, 'colsample_bytree': 0.794747373336845, 'min_child_weight': 5, 'gamma': 2.458286949691822, 'reg_alpha': 2.821103416587275e-07, 'reg_lambda': 0.0001409034575556664, 'max_delta_step': 6}. Best is trial 128 with value: 0.7072549019607844.
[I 2025-11-10 17:55:40,155] Trial 135 finished with value: 0.6885620915032681 and parameters: {'max_depth': 5, 'learning_rate': 0.19165643382379127, 'n_estimators': 1258, 'subsample': 0.9538689757791678, 'colsample_bytree': 0.7714679990590128, 'min_child_weight': 5, 'gamma': 2.4540238262059204, 'reg_alpha': 1.4640303013276042e-07, 'reg_lambda': 0.00013056934727703756, 'max_delta_step': 5}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  69%|██████▉   | 138/200 [01:26<01:01,  1.01it/s]

[I 2025-11-10 17:55:40,784] Trial 137 finished with value: 0.6873856209150329 and parameters: {'max_depth': 4, 'learning_rate': 0.1903866158550069, 'n_estimators': 1170, 'subsample': 0.9553108532244206, 'colsample_bytree': 0.7641856839182278, 'min_child_weight': 5, 'gamma': 2.373949192787123, 'reg_alpha': 2.4312756277643156e-07, 'reg_lambda': 0.0006612874143530541, 'max_delta_step': 5}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  70%|██████▉   | 139/200 [01:27<00:51,  1.19it/s]

[I 2025-11-10 17:55:41,263] Trial 139 pruned.

Best trial: 128. Best value: 0.707255:  70%|███████   | 140/200 [01:28<00:49,  1.21it/s]

[I 2025-11-10 17:55:42,056] Trial 141 pruned.

Best trial: 128. Best value: 0.707255:  70%|███████   | 141/200 [01:28<00:43,  1.37it/s]

[I 2025-11-10 17:55:42,562] Trial 142 pruned.

Best trial: 128. Best value: 0.707255:  71%|███████   | 142/200 [01:29<00:38,  1.50it/s]

[I 2025-11-10 17:55:43,075] Trial 143 pruned.

Best trial: 128. Best value: 0.707255:  72%|███████▏  | 143/200 [01:29<00:31,  1.83it/s]

[I 2025-11-10 17:55:43,342] Trial 138 finished with value: 0.6909803921568627 and parameters: {'max_depth': 5, 'learning_rate': 0.22379300202542082, 'n_estimators': 1272, 'subsample': 0.9540617463209259, 'colsample_bytree': 0.7712051291867734, 'min_child_weight': 5, 'gamma': 4.9966831610413465, 'reg_alpha': 2.83468228124051e-07, 'reg_lambda': 0.000307823015691393, 'max_delta_step': 6}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  72%|███████▏  | 144/200 [01:29<00:29,  1.92it/s]

[I 2025-11-10 17:55:43,805] Trial 144 pruned.

Best trial: 128. Best value: 0.707255:  72%|███████▎  | 145/200 [01:30<00:36,  1.49it/s]

[I 2025-11-10 17:55:44,831] Trial 147 pruned.

Best trial: 128. Best value: 0.707255:  73%|███████▎  | 146/200 [01:31<00:37,  1.46it/s]

[I 2025-11-10 17:55:45,550] Trial 140 finished with value: 0.6937254901960784 and parameters: {'max_depth': 5, 'learning_rate': 0.22388210458206992, 'n_estimators': 1250, 'subsample': 0.9844675357533355, 'colsample_bytree': 0.7463374427926468, 'min_child_weight': 5, 'gamma': 2.3241682562081887, 'reg_alpha': 1.430899054846861e-07, 'reg_lambda': 0.006066286183506416, 'max_delta_step': 5}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  74%|███████▎  | 147/200 [01:32<00:43,  1.22it/s]

[I 2025-11-10 17:55:46,683] Trial 149 pruned.

Best trial: 128. Best value: 0.707255:  74%|███████▍  | 148/200 [01:33<00:45,  1.15it/s]

[I 2025-11-10 17:55:47,670] Trial 150 pruned.

Best trial: 128. Best value: 0.707255:  74%|███████▍  | 149/200 [01:34<00:43,  1.16it/s]

[I 2025-11-10 17:55:48,513] Trial 146 finished with value: 0.6956862745098039 and parameters: {'max_depth': 5, 'learning_rate': 0.20317107731041195, 'n_estimators': 1241, 'subsample': 0.9577167634310575, 'colsample_bytree': 0.7514189262996093, 'min_child_weight': 5, 'gamma': 4.914610989610944, 'reg_alpha': 4.434337628555134e-08, 'reg_lambda': 0.002858626553370309, 'max_delta_step': 6}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  75%|███████▌  | 150/200 [01:34<00:33,  1.48it/s]

[I 2025-11-10 17:55:48,752] Trial 145 finished with value: 0.6932679738562093 and parameters: {'max_depth': 5, 'learning_rate': 0.20136558125653783, 'n_estimators': 1310, 'subsample': 0.9528175517172415, 'colsample_bytree': 0.7844918774244537, 'min_child_weight': 5, 'gamma': 2.4873249532960413, 'reg_alpha': 1.4623639109163642e-07, 'reg_lambda': 0.0019443077871556477, 'max_delta_step': 6}. Best is trial 128 with value: 0.7072549019607844.
[I 2025-11-10 17:55:48,774] Trial 151 pruned.

Best trial: 128. Best value: 0.707255:  76%|███████▌  | 152/200 [01:35<00:27,  1.73it/s]

[I 2025-11-10 17:55:49,684] Trial 152 pruned.

Best trial: 128. Best value: 0.707255:  76%|███████▋  | 153/200 [01:36<00:23,  2.01it/s]

[I 2025-11-10 17:55:49,938] Trial 153 pruned.

Best trial: 128. Best value: 0.707255:  78%|███████▊  | 155/200 [01:37<00:21,  2.12it/s]

[I 2025-11-10 17:55:50,787] Trial 148 finished with value: 0.7025490196078431 and parameters: {'max_depth': 5, 'learning_rate': 0.2481175354396637, 'n_estimators': 1354, 'subsample': 0.9564497212218597, 'colsample_bytree': 0.7759246513210503, 'min_child_weight': 5, 'gamma': 4.858399423194365, 'reg_alpha': 4.5788861334595067e-08, 'reg_lambda': 0.00016272453583584943, 'max_delta_step': 5}. Best is trial 128 with value: 0.7072549019607844.
[I 2025-11-10 17:55:50,944] Trial 155 pruned.

Best trial: 128. Best value: 0.707255:  78%|███████▊  | 156/200 [01:40<00:54,  1.24s/it]

[I 2025-11-10 17:55:54,147] Trial 154 finished with value: 0.6768627450980392 and parameters: {'max_depth': 5, 'learning_rate': 0.23303883070619802, 'n_estimators': 1243, 'subsample': 0.9529832609705396, 'colsample_bytree': 0.7591076580897708, 'min_child_weight': 5, 'gamma': 4.4743198162107225, 'reg_alpha': 8.218969197496906e-08, 'reg_lambda': 0.038867973881369214, 'max_delta_step': 3}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  78%|███████▊  | 157/200 [01:41<00:55,  1.29s/it]

[I 2025-11-10 17:55:55,572] Trial 156 finished with value: 0.6691503267973855 and parameters: {'max_depth': 5, 'learning_rate': 0.2394915838267053, 'n_estimators': 1280, 'subsample': 0.9503383448474563, 'colsample_bytree': 0.8017884719338114, 'min_child_weight': 5, 'gamma': 2.4383272749849163, 'reg_alpha': 7.892461572833231e-08, 'reg_lambda': 0.0018139128961168149, 'max_delta_step': 6}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  79%|███████▉  | 158/200 [01:42<00:50,  1.20s/it]

[I 2025-11-10 17:55:56,536] Trial 157 finished with value: 0.6768627450980392 and parameters: {'max_depth': 5, 'learning_rate': 0.2326933558390979, 'n_estimators': 1347, 'subsample': 0.9510415349631478, 'colsample_bytree': 0.7451793699153508, 'min_child_weight': 5, 'gamma': 4.59684505627258, 'reg_alpha': 7.825448608224356e-08, 'reg_lambda': 0.00012912873696509927, 'max_delta_step': 6}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  80%|███████▉  | 159/200 [01:42<00:37,  1.10it/s]

[I 2025-11-10 17:55:56,743] Trial 158 finished with value: 0.6652941176470588 and parameters: {'max_depth': 4, 'learning_rate': 0.2147269361930104, 'n_estimators': 1356, 'subsample': 0.9487393393154246, 'colsample_bytree': 0.7486995459434377, 'min_child_weight': 5, 'gamma': 4.5758392570660575, 'reg_alpha': 6.579228357418305e-08, 'reg_lambda': 0.010727377372181005, 'max_delta_step': 6}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  80%|████████  | 160/200 [01:46<01:03,  1.59s/it]

[I 2025-11-10 17:55:59,950] Trial 159 finished with value: 0.6780392156862745 and parameters: {'max_depth': 4, 'learning_rate': 0.21677434682345456, 'n_estimators': 1400, 'subsample': 0.9419322985852173, 'colsample_bytree': 0.7484449210007806, 'min_child_weight': 5, 'gamma': 4.879145599446684, 'reg_alpha': 5.539228165454765e-08, 'reg_lambda': 0.011397514758178632, 'max_delta_step': 6}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  80%|████████  | 161/200 [01:47<00:57,  1.48s/it]

[I 2025-11-10 17:56:01,179] Trial 163 pruned.

Best trial: 128. Best value: 0.707255:  81%|████████  | 162/200 [01:47<00:44,  1.17s/it]

[I 2025-11-10 17:56:01,626] Trial 160 finished with value: 0.6813725490196078 and parameters: {'max_depth': 4, 'learning_rate': 0.29923807733590513, 'n_estimators': 1408, 'subsample': 0.9407696487878302, 'colsample_bytree': 0.7482015032340951, 'min_child_weight': 5, 'gamma': 4.842761480883193, 'reg_alpha': 1.476861566553113e-07, 'reg_lambda': 0.00012577867580449394, 'max_delta_step': 6}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  82%|████████▏ | 164/200 [01:48<00:27,  1.32it/s]

[I 2025-11-10 17:56:02,268] Trial 162 finished with value: 0.666470588235294 and parameters: {'max_depth': 4, 'learning_rate': 0.18029578143474326, 'n_estimators': 1318, 'subsample': 0.9375503865339446, 'colsample_bytree': 0.7850894381776466, 'min_child_weight': 5, 'gamma': 4.814221501188058, 'reg_alpha': 1.5517780153233523e-07, 'reg_lambda': 0.000892956676790263, 'max_delta_step': 5}. Best is trial 128 with value: 0.7072549019607844.
[I 2025-11-10 17:56:02,431] Trial 164 pruned.

Best trial: 128. Best value: 0.707255:  82%|████████▎ | 165/200 [01:48<00:21,  1.65it/s]

[I 2025-11-10 17:56:02,677] Trial 161 finished with value: 0.6862745098039216 and parameters: {'max_depth': 4, 'learning_rate': 0.21754194843064825, 'n_estimators': 1405, 'subsample': 0.9398361698996623, 'colsample_bytree': 0.7910264088843137, 'min_child_weight': 5, 'gamma': 4.883114150200764, 'reg_alpha': 1.555586998699845e-07, 'reg_lambda': 0.0009528406717785996, 'max_delta_step': 5}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  83%|████████▎ | 166/200 [01:49<00:17,  1.99it/s]

[I 2025-11-10 17:56:02,940] Trial 165 pruned.

Best trial: 128. Best value: 0.707255:  84%|████████▎ | 167/200 [01:50<00:23,  1.40it/s]

[I 2025-11-10 17:56:04,147] Trial 168 pruned.

Best trial: 128. Best value: 0.707255:  84%|████████▍ | 168/200 [01:54<00:52,  1.63s/it]

[I 2025-11-10 17:56:07,911] Trial 167 finished with value: 0.6662745098039216 and parameters: {'max_depth': 5, 'learning_rate': 0.2553919454060922, 'n_estimators': 1269, 'subsample': 0.9962148349328573, 'colsample_bytree': 0.7732263479550446, 'min_child_weight': 5, 'gamma': 4.995043498936923, 'reg_alpha': 1.932233382906385e-08, 'reg_lambda': 0.0026798028064712177, 'max_delta_step': 5}. Best is trial 128 with value: 0.7072549019607844.
[I 2025-11-10 17:56:07,955] Trial 166 finished with value: 0.6658823529411764 and parameters: {'max_depth': 5, 'learning_rate': 0.2591351307341896, 'n_estimators': 1304, 'subsample': 0.9977181321620946, 'colsample_bytree': 0.7761011177836091, 'min_child_weight': 5, 'gamma': 2.478185140329349, 'reg_alpha': 6.94890812517178e-07, 'reg_lambda': 0.004146081281579824, 'max_delta_step': 4}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  85%|████████▌ | 170/200 [01:54<00:32,  1.10s/it]

[I 2025-11-10 17:56:08,862] Trial 169 finished with value: 0.6658823529411764 and parameters: {'max_depth': 4, 'learning_rate': 0.25754420703101605, 'n_estimators': 1393, 'subsample': 0.9945980556535134, 'colsample_bytree': 0.7682710075618163, 'min_child_weight': 5, 'gamma': 2.339537684054362, 'reg_alpha': 1.984783367804351e-08, 'reg_lambda': 0.0002976040054139551, 'max_delta_step': 5}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  86%|████████▌ | 171/200 [01:55<00:25,  1.13it/s]

[I 2025-11-10 17:56:09,112] Trial 171 pruned.
[I 2025-11-10 17:56:09,134] Trial 172 pruned.

Best trial: 128. Best value: 0.707255:  86%|████████▋ | 173/200 [01:55<00:16,  1.67it/s]

[I 2025-11-10 17:56:09,494] Trial 170 finished with value: 0.652156862745098 and parameters: {'max_depth': 4, 'learning_rate': 0.20270904980082655, 'n_estimators': 1168, 'subsample': 0.9778213971940719, 'colsample_bytree': 0.8039077254778957, 'min_child_weight': 5, 'gamma': 4.983916710661597, 'reg_alpha': 3.618894365575285e-07, 'reg_lambda': 0.0011952247662286699, 'max_delta_step': 5}. Best is trial 128 with value: 0.7072549019607844.

Best trial: 128. Best value: 0.707255:  87%|████████▋ | 174/200 [01:56<00:17,  1.51it/s]

[I 2025-11-10 17:56:10,375] Trial 174 pruned.

Best trial: 128. Best value: 0.707255:  88%|████████▊ | 175/200 [01:56<00:13,  1.81it/s]

[I 2025-11-10 17:56:10,596] Trial 176 pruned.

Best trial: 128. Best value: 0.707255:  88%|████████▊ | 176/200 [01:57<00:14,  1.61it/s]

[I 2025-11-10 17:56:11,406] Trial 177 pruned.

Best trial: 173. Best value: 0.707712:  88%|████████▊ | 177/200 [01:59<00:25,  1.09s/it]

[I 2025-11-10 17:56:13,761] Trial 173 finished with value: 0.7077124183006536 and parameters: {'max_depth': 4, 'learning_rate': 0.20747947860940574, 'n_estimators': 1128, 'subsample': 0.9752748447311507, 'colsample_bytree': 0.8032599444670095, 'min_child_weight': 5, 'gamma': 4.73367741632811, 'reg_alpha': 1.2238026800126656e-07, 'reg_lambda': 7.586324069685729e-05, 'max_delta_step': 6}. Best is trial 173 with value: 0.7077124183006536.

Best trial: 173. Best value: 0.707712:  89%|████████▉ | 178/200 [02:00<00:20,  1.06it/s]

[I 2025-11-10 17:56:14,327] Trial 175 finished with value: 0.6862745098039216 and parameters: {'max_depth': 5, 'learning_rate': 0.22224396887774833, 'n_estimators': 1208, 'subsample': 0.9313203466792905, 'colsample_bytree': 0.7926660218773615, 'min_child_weight': 5, 'gamma': 4.716022384073322, 'reg_alpha': 3.9834017954671537e-07, 'reg_lambda': 0.0016253234369008965, 'max_delta_step': 5}. Best is trial 173 with value: 0.7077124183006536.

Best trial: 173. Best value: 0.707712:  90%|████████▉ | 179/200 [02:02<00:23,  1.12s/it]

[I 2025-11-10 17:56:15,894] Trial 178 finished with value: 0.6644444444444445 and parameters: {'max_depth': 5, 'learning_rate': 0.21572822216065402, 'n_estimators': 1266, 'subsample': 0.9332880938015068, 'colsample_bytree': 0.7844734861253906, 'min_child_weight': 5, 'gamma': 2.2286816397608997, 'reg_alpha': 1.0810376099407538e-07, 'reg_lambda': 0.006432847796299942, 'max_delta_step': 5}. Best is trial 173 with value: 0.7077124183006536.

Best trial: 173. Best value: 0.707712:  90%|█████████ | 180/200 [02:02<00:20,  1.01s/it]

[I 2025-11-10 17:56:16,645] Trial 179 finished with value: 0.6650326797385622 and parameters: {'max_depth': 5, 'learning_rate': 0.2113911952025093, 'n_estimators': 1259, 'subsample': 0.9342861486386441, 'colsample_bytree': 0.8117678098541039, 'min_child_weight': 5, 'gamma': 1.9507131801153468, 'reg_alpha': 3.77997736265469e-08, 'reg_lambda': 7.371673144888362e-05, 'max_delta_step': 5}. Best is trial 173 with value: 0.7077124183006536.

Best trial: 173. Best value: 0.707712:  90%|█████████ | 181/200 [02:03<00:15,  1.23it/s]

[I 2025-11-10 17:56:16,970] Trial 182 pruned.

Best trial: 173. Best value: 0.707712:  91%|█████████ | 182/200 [02:05<00:22,  1.22s/it]

[I 2025-11-10 17:56:19,177] Trial 181 finished with value: 0.6766666666666667 and parameters: {'max_depth': 4, 'learning_rate': 0.19111573358454106, 'n_estimators': 1135, 'subsample': 0.9353737794139162, 'colsample_bytree': 0.7357658159538661, 'min_child_weight': 5, 'gamma': 4.1875674243050245, 'reg_alpha': 2.4911432587723587e-06, 'reg_lambda': 7.12397795329966e-05, 'max_delta_step': 5}. Best is trial 173 with value: 0.7077124183006536.

Best trial: 173. Best value: 0.707712:  92%|█████████▏| 183/200 [02:05<00:16,  1.04it/s]

[I 2025-11-10 17:56:19,503] Trial 180 finished with value: 0.6907843137254901 and parameters: {'max_depth': 4, 'learning_rate': 0.21192367199098217, 'n_estimators': 1330, 'subsample': 0.9335194096537853, 'colsample_bytree': 0.7627331103727003, 'min_child_weight': 5, 'gamma': 4.208675984140486, 'reg_alpha': 4.832752561795899e-08, 'reg_lambda': 7.502014474409765e-05, 'max_delta_step': 5}. Best is trial 173 with value: 0.7077124183006536.

Best trial: 173. Best value: 0.707712:  92%|█████████▏| 184/200 [02:06<00:14,  1.09it/s]

[I 2025-11-10 17:56:20,320] Trial 185 pruned.

Best trial: 173. Best value: 0.707712:  92%|█████████▎| 185/200 [02:07<00:14,  1.04it/s]

[I 2025-11-10 17:56:21,394] Trial 183 finished with value: 0.693529411764706 and parameters: {'max_depth': 4, 'learning_rate': 0.1927156418517283, 'n_estimators': 1124, 'subsample': 0.956396702405458, 'colsample_bytree': 0.732856469878264, 'min_child_weight': 5, 'gamma': 4.619185573489709, 'reg_alpha': 2.089582832224511e-07, 'reg_lambda': 1.9730614918751547e-05, 'max_delta_step': 5}. Best is trial 173 with value: 0.7077124183006536.

Best trial: 173. Best value: 0.707712:  93%|█████████▎| 186/200 [02:08<00:12,  1.14it/s]

[I 2025-11-10 17:56:22,064] Trial 184 finished with value: 0.6956862745098039 and parameters: {'max_depth': 4, 'learning_rate': 0.19482375714355152, 'n_estimators': 1181, 'subsample': 0.9583908330680291, 'colsample_bytree': 0.735416960495165, 'min_child_weight': 5, 'gamma': 4.890785913606896, 'reg_alpha': 5.20474343870167e-08, 'reg_lambda': 0.00016395563540119493, 'max_delta_step': 6}. Best is trial 173 with value: 0.7077124183006536.

Best trial: 173. Best value: 0.707712:  94%|█████████▎| 187/200 [02:10<00:15,  1.20s/it]

[I 2025-11-10 17:56:24,022] Trial 186 finished with value: 0.6862745098039216 and parameters: {'max_depth': 4, 'learning_rate': 0.23229620990833685, 'n_estimators': 1031, 'subsample': 0.9197640120613784, 'colsample_bytree': 0.7583195916229647, 'min_child_weight': 5, 'gamma': 4.8947112800226735, 'reg_alpha': 6.143297375489527e-08, 'reg_lambda': 0.00011979660108919638, 'max_delta_step': 5}. Best is trial 173 with value: 0.7077124183006536.

Best trial: 173. Best value: 0.707712:  94%|█████████▍| 188/200 [02:12<00:17,  1.43s/it]

[I 2025-11-10 17:56:26,003] Trial 188 finished with value: 0.6745098039215686 and parameters: {'max_depth': 4, 'learning_rate': 0.2377530749550456, 'n_estimators': 1090, 'subsample': 0.9177252454194137, 'colsample_bytree': 0.7275140449153198, 'min_child_weight': 5, 'gamma': 4.794472049758882, 'reg_alpha': 2.0265523887732682e-07, 'reg_lambda': 0.0002630348525068262, 'max_delta_step': 5}. Best is trial 173 with value: 0.7077124183006536.
[I 2025-11-10 17:56:26,024] Trial 187 finished with value: 0.6637254901960784 and parameters: {'max_depth': 4, 'learning_rate': 0.23977807218853844, 'n_estimators': 1327, 'subsample': 0.9162381038474862, 'colsample_bytree': 0.7653699344273975, 'min_child_weight': 5, 'gamma': 3.9950851978977076, 'reg_alpha': 2.0660800585532867e-07, 'reg_lambda': 2.3320997412625383e-05, 'max_delta_step': 5}. Best is trial 173 with value: 0.7077124183006536.

Best trial: 173. Best value: 0.707712:  95%|█████████▌| 190/200 [02:13<00:10,  1.02s/it]

[I 2025-11-10 17:56:27,079] Trial 192 pruned.

Best trial: 173. Best value: 0.707712:  96%|█████████▌| 191/200 [02:13<00:08,  1.05it/s]

[I 2025-11-10 17:56:27,835] Trial 189 finished with value: 0.6284313725490197 and parameters: {'max_depth': 4, 'learning_rate': 0.1972082448233893, 'n_estimators': 1328, 'subsample': 0.9489737915224612, 'colsample_bytree': 0.6821481979213169, 'min_child_weight': 5, 'gamma': 4.878756006096822, 'reg_alpha': 2.7998101968175215e-08, 'reg_lambda': 0.00011372522102869011, 'max_delta_step': 7}. Best is trial 173 with value: 0.7077124183006536.

Best trial: 173. Best value: 0.707712:  96%|█████████▌| 192/200 [02:14<00:06,  1.21it/s]

[I 2025-11-10 17:56:28,308] Trial 193 pruned.

Best trial: 173. Best value: 0.707712:  97%|█████████▋| 194/200 [02:15<00:03,  1.71it/s]

[I 2025-11-10 17:56:28,871] Trial 194 pruned.
[I 2025-11-10 17:56:29,018] Trial 190 finished with value: 0.6711764705882353 and parameters: {'max_depth': 4, 'learning_rate': 0.19715580175228994, 'n_estimators': 1099, 'subsample': 0.953801702165915, 'colsample_bytree': 0.7248807760752104, 'min_child_weight': 5, 'gamma': 4.805755706899962, 'reg_alpha': 2.300135960736878e-07, 'reg_lambda': 1.985072456034631e-05, 'max_delta_step': 7}. Best is trial 173 with value: 0.7077124183006536.

Best trial: 173. Best value: 0.707712:  98%|█████████▊| 195/200 [02:15<00:02,  1.85it/s]

[I 2025-11-10 17:56:29,444] Trial 195 pruned.

Best trial: 173. Best value: 0.707712:  98%|█████████▊| 196/200 [02:16<00:02,  1.78it/s]

[I 2025-11-10 17:56:30,054] Trial 196 pruned.

Best trial: 173. Best value: 0.707712:  98%|█████████▊| 197/200 [02:17<00:02,  1.10it/s]

[I 2025-11-10 17:56:31,807] Trial 191 finished with value: 0.6801960784313724 and parameters: {'max_depth': 4, 'learning_rate': 0.20051267557654137, 'n_estimators': 1354, 'subsample': 0.9467953748056057, 'colsample_bytree': 0.7406950060493341, 'min_child_weight': 5, 'gamma': 4.907240179622157, 'reg_alpha': 2.8811332727130714e-08, 'reg_lambda': 2.5879420728316458e-05, 'max_delta_step': 7}. Best is trial 173 with value: 0.7077124183006536.

Best trial: 173. Best value: 0.707712:  99%|█████████▉| 198/200 [02:19<00:02,  1.15s/it]

[I 2025-11-10 17:56:33,546] Trial 197 finished with value: 0.672156862745098 and parameters: {'max_depth': 4, 'learning_rate': 0.207249143304173, 'n_estimators': 1231, 'subsample': 0.9432656867176341, 'colsample_bytree': 0.7559932641110969, 'min_child_weight': 5, 'gamma': 4.687757174597072, 'reg_alpha': 5.863262045304183e-08, 'reg_lambda': 0.00034994652183006263, 'max_delta_step': 5}. Best is trial 173 with value: 0.7077124183006536.

Best trial: 173. Best value: 0.707712: 100%|█████████▉| 199/200 [02:19<00:00,  1.12it/s]

[I 2025-11-10 17:56:33,822] Trial 198 finished with value: 0.6884313725490195 and parameters: {'max_depth': 4, 'learning_rate': 0.2059432164208519, 'n_estimators': 1224, 'subsample': 0.9872754287731188, 'colsample_bytree': 0.754705397069612, 'min_child_weight': 5, 'gamma': 4.765886979698906, 'reg_alpha': 9.771526906643513e-08, 'reg_lambda': 0.0006869616082280586, 'max_delta_step': 5}. Best is trial 173 with value: 0.7077124183006536.

Best trial: 173. Best value: 0.707712: 100%|██████████| 200/200 [02:20<00:00,  1.43it/s]

[I 2025-11-10 17:56:34,122] Trial 199 finished with value: 0.6662745098039216 and parameters: {'max_depth': 4, 'learning_rate': 0.2239956375921115, 'n_estimators': 1226, 'subsample': 0.986626912651818, 'colsample_bytree': 0.7560609749833294, 'min_child_weight': 5, 'gamma': 4.991724551164467, 'reg_alpha': 9.027819736031063e-08, 'reg_lambda': 0.0006882183135322757, 'max_delta_step': 5}. Best is trial 173 with value: 0.7077124183006536.
   dataset  cv_best_value  test_balanced_accuracy  test_roc_auc  n_trials
0      3_3       0.673684                0.798137      0.922360       200
1     17_1       0.634854                0.711180      0.751553       200
2      3_5       0.554815                0.677019      0.571429       200
3     16_1       0.670936                0.670807      0.667702       200
4      1_1       0.556491                0.583851      0.639752       200
5     10_1       0.569591                0.568323      0.571429       200
6      9_1       0.644498                0.517483      0.490385       200
7      3_2       0.500000                0.500000      0.500000       200
8      3_1       0.544639                0.490683      0.385093       200
9     18_1       0.725302                0.456522      0.745342       200
10     3_4       0.600292                0.447205      0.540373       200
11    19_1       0.707712                0.439394      0.393939       200
12    15_1       0.586491                0.381988      0.388199       200

In [109]:
# Temporal embedings
datasets = task_temp_dfs

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    #    scoring="balanced_accuracy",     # or "roc_auc"
    scoring="roc_auc",      
    n_trials=200,
    n_splits=5,
    output_dir="xgb_results_temporal",
)
print(summary)

[I 2025-11-10 17:56:35,213] A new study created in memory with name: 1_1_roc_auc
Best trial: 3. Best value: 0.438012:   0%|          | 1/200 [00:01<04:49,  1.45s/it]

[I 2025-11-10 17:56:36,662] Trial 3 finished with value: 0.43801169590643274 and parameters: {'max_depth': 3, 'learning_rate': 0.2468799800537976, 'n_estimators': 346, 'subsample': 0.7236209851799751, 'colsample_bytree': 0.530495800784516, 'min_child_weight': 4, 'gamma': 2.6487938550995347, 'reg_alpha': 1.5166999550245424, 'reg_lambda': 0.0007484408538775205, 'max_delta_step': 5}. Best is trial 3 with value: 0.43801169590643274.

Best trial: 1. Best value: 0.5:   2%|▏         | 3/200 [00:02<02:41,  1.22it/s]

[I 2025-11-10 17:56:38,061] Trial 2 finished with value: 0.4637037037037037 and parameters: {'max_depth': 6, 'learning_rate': 0.01658494818160015, 'n_estimators': 638, 'subsample': 0.919876806371303, 'colsample_bytree': 0.6975657104655764, 'min_child_weight': 4, 'gamma': 2.5935315759528725, 'reg_alpha': 3.553953996286355, 'reg_lambda': 3.2601173097224945, 'max_delta_step': 3}. Best is trial 2 with value: 0.4637037037037037.
[I 2025-11-10 17:56:38,161] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.07218997743381521, 'n_estimators': 740, 'subsample': 0.6055239817038996, 'colsample_bytree': 0.7292310973977456, 'min_child_weight': 6, 'gamma': 4.73826348851479, 'reg_alpha': 0.0330423640312014, 'reg_lambda': 4.604028376484331, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   2%|▏         | 4/200 [00:03<02:38,  1.24it/s]

[I 2025-11-10 17:56:38,956] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02472272094016048, 'n_estimators': 586, 'subsample': 0.7719432734939531, 'colsample_bytree': 0.8569547914627349, 'min_child_weight': 8, 'gamma': 4.002857950542536, 'reg_alpha': 5.314057264999984e-06, 'reg_lambda': 4.046506005598322e-06, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   2%|▎         | 5/200 [00:06<04:42,  1.45s/it]

[I 2025-11-10 17:56:41,539] Trial 0 finished with value: 0.36674463937621826 and parameters: {'max_depth': 6, 'learning_rate': 0.0468313813669455, 'n_estimators': 1296, 'subsample': 0.7697278452451046, 'colsample_bytree': 0.917751375657843, 'min_child_weight': 3, 'gamma': 3.1695717072440144, 'reg_alpha': 0.00046718102048012703, 'reg_lambda': 0.0019355038878963741, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   3%|▎         | 6/200 [00:06<03:23,  1.05s/it]

[I 2025-11-10 17:56:41,813] Trial 5 finished with value: 0.4147173489278752 and parameters: {'max_depth': 3, 'learning_rate': 0.05566675955839332, 'n_estimators': 659, 'subsample': 0.9461861969867289, 'colsample_bytree': 0.7484995850216096, 'min_child_weight': 2, 'gamma': 3.6535449194431373, 'reg_alpha': 3.2349224975283753e-06, 'reg_lambda': 1.1411705027351013e-08, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   4%|▎         | 7/200 [00:07<03:16,  1.02s/it]

[I 2025-11-10 17:56:42,762] Trial 6 finished with value: 0.4452436647173489 and parameters: {'max_depth': 9, 'learning_rate': 0.06983142925565847, 'n_estimators': 719, 'subsample': 0.8385660168599001, 'colsample_bytree': 0.7825493788232181, 'min_child_weight': 1, 'gamma': 1.6598213073608103, 'reg_alpha': 9.101298958424455e-05, 'reg_lambda': 1.3151658994386212e-05, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   4%|▍         | 8/200 [00:08<03:06,  1.03it/s]

[I 2025-11-10 17:56:43,628] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08840125575893394, 'n_estimators': 1223, 'subsample': 0.6736799395277506, 'colsample_bytree': 0.9228226056806896, 'min_child_weight': 5, 'gamma': 1.842785956716314, 'reg_alpha': 3.827999558100573e-05, 'reg_lambda': 6.904276843784417e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   4%|▍         | 9/200 [00:09<03:02,  1.05it/s]

[I 2025-11-10 17:56:44,553] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2733982392884836, 'n_estimators': 746, 'subsample': 0.621082775957523, 'colsample_bytree': 0.6104411476839369, 'min_child_weight': 10, 'gamma': 1.048886825784, 'reg_alpha': 0.007049725622762431, 'reg_lambda': 0.004673955731626035, 'max_delta_step': 1}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   5%|▌         | 10/200 [00:10<03:18,  1.05s/it]

[I 2025-11-10 17:56:45,807] Trial 10 finished with value: 0.36693957115009745 and parameters: {'max_depth': 7, 'learning_rate': 0.03402706357188254, 'n_estimators': 483, 'subsample': 0.7850068894413548, 'colsample_bytree': 0.8033749094990914, 'min_child_weight': 3, 'gamma': 1.0182119179248594, 'reg_alpha': 2.4766021336172925e-07, 'reg_lambda': 0.0008515963395403671, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   6%|▌         | 11/200 [00:11<02:54,  1.09it/s]

[I 2025-11-10 17:56:46,443] Trial 12 pruned.

Best trial: 1. Best value: 0.5:   6%|▌         | 12/200 [00:11<02:23,  1.31it/s]

[I 2025-11-10 17:56:46,851] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.26055512690268395, 'n_estimators': 838, 'subsample': 0.7383175050272435, 'colsample_bytree': 0.6949329478151797, 'min_child_weight': 5, 'gamma': 2.547858678624812, 'reg_alpha': 0.013054147480326829, 'reg_lambda': 8.868488777708854e-08, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   6%|▋         | 13/200 [00:13<03:09,  1.01s/it]

[I 2025-11-10 17:56:48,428] Trial 8 finished with value: 0.4396881091617934 and parameters: {'max_depth': 8, 'learning_rate': 0.21028715360323463, 'n_estimators': 1158, 'subsample': 0.514796070667475, 'colsample_bytree': 0.9314763914004505, 'min_child_weight': 1, 'gamma': 3.883875416046087, 'reg_alpha': 6.1452169423249e-07, 'reg_lambda': 1.5063522716599746e-05, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   7%|▋         | 14/200 [00:14<03:29,  1.13s/it]

[I 2025-11-10 17:56:49,824] Trial 13 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.1500021587836282, 'n_estimators': 1024, 'subsample': 0.5210144806597843, 'colsample_bytree': 0.6590055719303997, 'min_child_weight': 7, 'gamma': 4.907133136031223, 'reg_alpha': 0.035524318094235806, 'reg_lambda': 5.425291848011361, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   8%|▊         | 15/200 [00:15<03:00,  1.02it/s]

[I 2025-11-10 17:56:50,448] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.13835216600546194, 'n_estimators': 948, 'subsample': 0.540919871026697, 'colsample_bytree': 0.8629298580207663, 'min_child_weight': 8, 'gamma': 4.977533599779764, 'reg_alpha': 2.2031508924267956e-08, 'reg_lambda': 2.8149075228341642, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   8%|▊         | 16/200 [00:15<02:30,  1.23it/s]

[I 2025-11-10 17:56:50,895] Trial 17 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.026624548221017886, 'n_estimators': 223, 'subsample': 0.6190097159469868, 'colsample_bytree': 0.8429495247307911, 'min_child_weight': 8, 'gamma': 4.906344721384264, 'reg_alpha': 3.915451720014375e-08, 'reg_lambda': 0.06543858061564946, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   8%|▊         | 17/200 [00:16<02:04,  1.47it/s]

[I 2025-11-10 17:56:51,259] Trial 15 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03102936351438272, 'n_estimators': 1028, 'subsample': 0.5125691566225086, 'colsample_bytree': 0.8581614608633631, 'min_child_weight': 8, 'gamma': 4.96435465625784, 'reg_alpha': 1.5606039259154386e-08, 'reg_lambda': 2.175524585335419, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   9%|▉         | 18/200 [00:17<02:48,  1.08it/s]

[I 2025-11-10 17:56:52,762] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.026153184993229057, 'n_estimators': 996, 'subsample': 0.5695407236584205, 'colsample_bytree': 0.8620289431259004, 'min_child_weight': 8, 'gamma': 4.958175262346486, 'reg_alpha': 1.5426521620823272e-08, 'reg_lambda': 1.4049006048370745, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  10%|▉         | 19/200 [00:17<02:14,  1.35it/s]

[I 2025-11-10 17:56:53,069] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.024713997953788036, 'n_estimators': 468, 'subsample': 0.8669834246862237, 'colsample_bytree': 0.9996357051194041, 'min_child_weight': 7, 'gamma': 0.12575211699774247, 'reg_alpha': 0.22955921123993445, 'reg_lambda': 0.07438488620871381, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  10%|█         | 20/200 [00:19<03:19,  1.11s/it]

[I 2025-11-10 17:56:55,037] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.010646379479682883, 'n_estimators': 505, 'subsample': 0.8361294590845559, 'colsample_bytree': 0.9965805601961268, 'min_child_weight': 10, 'gamma': 3.9416483898301506, 'reg_alpha': 0.3829883025872526, 'reg_lambda': 0.0612536464483055, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  10%|█         | 21/200 [00:20<02:38,  1.13it/s]

[I 2025-11-10 17:56:55,402] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09083770137813109, 'n_estimators': 537, 'subsample': 0.992514526790979, 'colsample_bytree': 0.751829134910303, 'min_child_weight': 10, 'gamma': 4.1017356907263425, 'reg_alpha': 4.431669171336184e-06, 'reg_lambda': 7.791510355419564e-05, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  11%|█         | 22/200 [00:21<03:14,  1.09s/it]

[I 2025-11-10 17:56:56,985] Trial 18 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.027108692642308578, 'n_estimators': 1498, 'subsample': 0.6016041686475408, 'colsample_bytree': 0.8621143378808395, 'min_child_weight': 7, 'gamma': 4.222564669970034, 'reg_alpha': 0.18086374032717206, 'reg_lambda': 0.006377293357551117, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  12%|█▏        | 23/200 [00:22<02:33,  1.15it/s]

[I 2025-11-10 17:56:57,327] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.08865599853573101, 'n_estimators': 524, 'subsample': 0.6661104647859887, 'colsample_bytree': 0.61150007352955, 'min_child_weight': 6, 'gamma': 4.370861008362418, 'reg_alpha': 7.596614547266743e-06, 'reg_lambda': 0.000104441702936051, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  12%|█▏        | 24/200 [00:22<02:16,  1.29it/s]

[I 2025-11-10 17:56:57,889] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.011464032716277894, 'n_estimators': 1491, 'subsample': 0.8547606435194925, 'colsample_bytree': 0.9801971269620229, 'min_child_weight': 10, 'gamma': 4.167986478091006, 'reg_alpha': 0.23192897145770894, 'reg_lambda': 0.06253457336585343, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  12%|█▎        | 25/200 [00:25<04:08,  1.42s/it]

[I 2025-11-10 17:57:00,804] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.11627744742780341, 'n_estimators': 812, 'subsample': 0.6650961279115006, 'colsample_bytree': 0.929787251672623, 'min_child_weight': 6, 'gamma': 1.829328522437499, 'reg_alpha': 5.9655068811809e-05, 'reg_lambda': 5.904394001874864e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  14%|█▎        | 27/200 [00:26<02:37,  1.10it/s]

[I 2025-11-10 17:57:01,600] Trial 27 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.042967696300612035, 'n_estimators': 859, 'subsample': 0.6903598693750186, 'colsample_bytree': 0.921710281887844, 'min_child_weight': 6, 'gamma': 2.0601732288513146, 'reg_alpha': 6.407405455074007e-05, 'reg_lambda': 6.567785026603124e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:57:01,767] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09834257920239473, 'n_estimators': 1461, 'subsample': 0.6838699000974101, 'colsample_bytree': 0.9460973756335476, 'min_child_weight': 6, 'gamma': 1.8337282322711879, 'reg_alpha': 5.2308054359078634e-05, 'reg_lambda': 8.417422476321383e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  14%|█▍        | 28/200 [00:27<02:57,  1.03s/it]

[I 2025-11-10 17:57:03,081] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10057077803417538, 'n_estimators': 1400, 'subsample': 0.6493075813487145, 'colsample_bytree': 0.9352088037962774, 'min_child_weight': 6, 'gamma': 1.9902524456913921, 'reg_alpha': 2.713059227770398e-05, 'reg_lambda': 1.991169992093825e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  14%|█▍        | 29/200 [00:31<04:46,  1.68s/it]

[I 2025-11-10 17:57:06,257] Trial 28 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04605877708573203, 'n_estimators': 1271, 'subsample': 0.6884769524090093, 'colsample_bytree': 0.813774444358637, 'min_child_weight': 5, 'gamma': 1.9947885678457213, 'reg_alpha': 0.0024053653654625183, 'reg_lambda': 4.0747356172327284e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  16%|█▌        | 31/200 [00:32<02:56,  1.04s/it]

[I 2025-11-10 17:57:07,096] Trial 30 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.07026702586276148, 'n_estimators': 1244, 'subsample': 0.7937506015015798, 'colsample_bytree': 0.8110809548871188, 'min_child_weight': 5, 'gamma': 3.5266186728219067, 'reg_alpha': 0.002487181825235255, 'reg_lambda': 6.72224032800826e-08, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:57:07,251] Trial 29 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.0673530787577711, 'n_estimators': 1326, 'subsample': 0.6945978304550875, 'colsample_bytree': 0.7806483448324812, 'min_child_weight': 5, 'gamma': 3.3267941339278186, 'reg_alpha': 0.0017903106010213699, 'reg_lambda': 1.4343482462972856e-07, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  16%|█▌        | 32/200 [00:32<02:39,  1.05it/s]

[I 2025-11-10 17:57:07,986] Trial 32 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.0668554883009269, 'n_estimators': 375, 'subsample': 0.7942136017437489, 'colsample_bytree': 0.7507438548826211, 'min_child_weight': 9, 'gamma': 3.286344062210795, 'reg_alpha': 0.0003591616859338062, 'reg_lambda': 3.492369041222233e-08, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  16%|█▋        | 33/200 [00:33<02:02,  1.36it/s]

[I 2025-11-10 17:57:08,211] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.06222791011776131, 'n_estimators': 1174, 'subsample': 0.7970873978842186, 'colsample_bytree': 0.8123546498641023, 'min_child_weight': 5, 'gamma': 3.2503608474157506, 'reg_alpha': 0.0027009405914375224, 'reg_lambda': 1.0172770067209962e-08, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  17%|█▋        | 34/200 [00:33<02:05,  1.32it/s]

[I 2025-11-10 17:57:09,022] Trial 33 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.06160139704049451, 'n_estimators': 385, 'subsample': 0.7175050177349392, 'colsample_bytree': 0.8992281079164187, 'min_child_weight': 9, 'gamma': 2.8954998419214397, 'reg_alpha': 0.00038586416565397516, 'reg_lambda': 4.48341410073295e-06, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  18%|█▊        | 35/200 [00:34<01:58,  1.39it/s]

[I 2025-11-10 17:57:09,661] Trial 37 pruned.

Best trial: 1. Best value: 0.5:  18%|█▊        | 36/200 [00:35<02:02,  1.34it/s]

[I 2025-11-10 17:57:10,462] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1906677494855577, 'n_estimators': 718, 'subsample': 0.619813041436969, 'colsample_bytree': 0.5896932780095152, 'min_child_weight': 9, 'gamma': 0.6566021491412743, 'reg_alpha': 0.00045670787093368275, 'reg_lambda': 0.4728943369374726, 'max_delta_step': 2}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  18%|█▊        | 37/200 [00:35<01:56,  1.39it/s]

[I 2025-11-10 17:57:11,116] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.019221630649022745, 'n_estimators': 711, 'subsample': 0.6147701275681935, 'colsample_bytree': 0.540056050507889, 'min_child_weight': 9, 'gamma': 0.7131826685509268, 'reg_alpha': 0.017077924685373648, 'reg_lambda': 0.0039029653582077655, 'max_delta_step': 2}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  19%|█▉        | 38/200 [00:36<01:33,  1.74it/s]

[I 2025-11-10 17:57:11,360] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1832024486951807, 'n_estimators': 713, 'subsample': 0.618409083487617, 'colsample_bytree': 0.5622202582756942, 'min_child_weight': 9, 'gamma': 0.6383734186637917, 'reg_alpha': 0.01940518975208624, 'reg_lambda': 0.00720330176022004, 'max_delta_step': 2}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  20%|█▉        | 39/200 [00:36<01:25,  1.88it/s]

[I 2025-11-10 17:57:11,785] Trial 40 pruned.

Best trial: 1. Best value: 0.5:  20%|██        | 40/200 [00:36<01:12,  2.21it/s]

[I 2025-11-10 17:57:12,052] Trial 41 pruned.

Best trial: 1. Best value: 0.5:  20%|██        | 41/200 [00:37<01:07,  2.35it/s]

[I 2025-11-10 17:57:12,421] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1481390634714637, 'n_estimators': 604, 'subsample': 0.5754085951003941, 'colsample_bytree': 0.5954044312678973, 'min_child_weight': 9, 'gamma': 4.536546672164774, 'reg_alpha': 0.039983679431615224, 'reg_lambda': 0.006092468233000179, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  21%|██        | 42/200 [00:37<01:09,  2.28it/s]

[I 2025-11-10 17:57:12,892] Trial 43 pruned.

Best trial: 1. Best value: 0.5:  22%|██▏       | 43/200 [00:38<01:09,  2.27it/s]

[I 2025-11-10 17:57:13,328] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03985027513745167, 'n_estimators': 613, 'subsample': 0.5713488123068727, 'colsample_bytree': 0.5908630193495704, 'min_child_weight': 3, 'gamma': 4.558428457695871, 'reg_alpha': 6.578549020426886, 'reg_lambda': 0.0063066999575016325, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  22%|██▏       | 44/200 [00:38<01:03,  2.46it/s]

[I 2025-11-10 17:57:13,659] Trial 45 pruned.

Best trial: 1. Best value: 0.5:  22%|██▎       | 45/200 [00:38<01:05,  2.37it/s]

[I 2025-11-10 17:57:14,116] Trial 46 pruned.

Best trial: 1. Best value: 0.5:  23%|██▎       | 46/200 [00:39<01:12,  2.13it/s]

[I 2025-11-10 17:57:14,699] Trial 42 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.2922847855478735, 'n_estimators': 623, 'subsample': 0.5642861548304048, 'colsample_bytree': 0.6317893043801492, 'min_child_weight': 4, 'gamma': 4.46644721071341, 'reg_alpha': 4.0437982497036605e-07, 'reg_lambda': 0.00036896668327800815, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  24%|██▎       | 47/200 [00:41<02:02,  1.25it/s]

[I 2025-11-10 17:57:16,267] Trial 44 finished with value: 0.37729044834307984 and parameters: {'max_depth': 9, 'learning_rate': 0.2938850754474442, 'n_estimators': 848, 'subsample': 0.7301162064715115, 'colsample_bytree': 0.6887376788828199, 'min_child_weight': 4, 'gamma': 2.686041673367889, 'reg_alpha': 1.4173387168281958e-05, 'reg_lambda': 2.7434331813252884e-06, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  24%|██▍       | 48/200 [00:42<02:28,  1.02it/s]

[I 2025-11-10 17:57:17,658] Trial 47 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.29494313464573535, 'n_estimators': 922, 'subsample': 0.7424728929135679, 'colsample_bytree': 0.6409775585634702, 'min_child_weight': 7, 'gamma': 2.4551990842861837, 'reg_alpha': 0.006902978696165396, 'reg_lambda': 9.57330859627167e-06, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  24%|██▍       | 49/200 [00:42<02:03,  1.22it/s]

[I 2025-11-10 17:57:18,099] Trial 48 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.0523731548897255, 'n_estimators': 931, 'subsample': 0.6500114627750592, 'colsample_bytree': 0.6536804561741758, 'min_child_weight': 7, 'gamma': 2.9680593937777413, 'reg_alpha': 0.008198703792210627, 'reg_lambda': 1.5675182212418322e-05, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  25%|██▌       | 50/200 [00:44<02:21,  1.06it/s]

[I 2025-11-10 17:57:19,334] Trial 49 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.12934762255292429, 'n_estimators': 1082, 'subsample': 0.7198692057359528, 'colsample_bytree': 0.6675283515328391, 'min_child_weight': 7, 'gamma': 2.8961304775291747, 'reg_alpha': 2.1636771744156053e-06, 'reg_lambda': 2.2766373632874574e-05, 'max_delta_step': 1}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  26%|██▌       | 51/200 [00:44<02:14,  1.11it/s]

[I 2025-11-10 17:57:20,150] Trial 53 pruned.

Best trial: 1. Best value: 0.5:  26%|██▌       | 52/200 [00:45<01:42,  1.44it/s]

[I 2025-11-10 17:57:20,350] Trial 50 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.16740974351631543, 'n_estimators': 938, 'subsample': 0.6500153974462434, 'colsample_bytree': 0.6617625762707966, 'min_child_weight': 7, 'gamma': 3.6691923835567284, 'reg_alpha': 0.006776664399730046, 'reg_lambda': 1.922214655803619e-05, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  26%|██▋       | 53/200 [00:46<02:02,  1.20it/s]

[I 2025-11-10 17:57:21,505] Trial 52 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.13146196254835177, 'n_estimators': 774, 'subsample': 0.7104602380964854, 'colsample_bytree': 0.7719316765756941, 'min_child_weight': 8, 'gamma': 1.0985770946209223, 'reg_alpha': 1.6814936417032546e-06, 'reg_lambda': 3.1266558853589534e-08, 'max_delta_step': 1}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  27%|██▋       | 54/200 [00:46<01:50,  1.32it/s]

[I 2025-11-10 17:57:22,105] Trial 51 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.08183026029173228, 'n_estimators': 987, 'subsample': 0.8188582144213072, 'colsample_bytree': 0.7314774332022105, 'min_child_weight': 8, 'gamma': 1.3326048763256426, 'reg_alpha': 0.0001694400723605573, 'reg_lambda': 2.94342345378221e-08, 'max_delta_step': 1}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  28%|██▊       | 55/200 [00:49<03:04,  1.27s/it]

[I 2025-11-10 17:57:24,564] Trial 54 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07697281409373674, 'n_estimators': 1012, 'subsample': 0.5133981906108892, 'colsample_bytree': 0.6794497520628371, 'min_child_weight': 8, 'gamma': 4.74803760061542, 'reg_alpha': 0.0001402440876035412, 'reg_lambda': 5.544871511629537, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  28%|██▊       | 56/200 [00:49<02:33,  1.07s/it]

[I 2025-11-10 17:57:25,156] Trial 55 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.21775895739749845, 'n_estimators': 1044, 'subsample': 0.5446887522266352, 'colsample_bytree': 0.9619605921100246, 'min_child_weight': 8, 'gamma': 4.775910808341356, 'reg_alpha': 0.7269302346411716, 'reg_lambda': 8.30981841329398, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  28%|██▊       | 57/200 [00:50<02:22,  1.00it/s]

[I 2025-11-10 17:57:25,987] Trial 56 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.08279390857893539, 'n_estimators': 1021, 'subsample': 0.5324470565175572, 'colsample_bytree': 0.7305505156965979, 'min_child_weight': 8, 'gamma': 4.804485811650549, 'reg_alpha': 0.0009645908274776199, 'reg_lambda': 6.288714164523046, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  29%|██▉       | 58/200 [00:51<02:10,  1.09it/s]

[I 2025-11-10 17:57:26,725] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.23554868124954284, 'n_estimators': 1078, 'subsample': 0.5325849556422317, 'colsample_bytree': 0.6214056472433591, 'min_child_weight': 6, 'gamma': 4.778461824638083, 'reg_alpha': 0.8360250621649589, 'reg_lambda': 9.439930922110138, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  30%|██▉       | 59/200 [00:53<02:34,  1.09s/it]

[I 2025-11-10 17:57:28,224] Trial 59 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.11161532412425185, 'n_estimators': 673, 'subsample': 0.5366376237200544, 'colsample_bytree': 0.840491991363384, 'min_child_weight': 6, 'gamma': 0.06610529455634762, 'reg_alpha': 0.0011461998014503751, 'reg_lambda': 0.020935550889173843, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  30%|███       | 60/200 [00:54<02:27,  1.05s/it]

[I 2025-11-10 17:57:29,178] Trial 61 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10686562034706988, 'n_estimators': 545, 'subsample': 0.7687847555919511, 'colsample_bytree': 0.8379211566212923, 'min_child_weight': 5, 'gamma': 3.9185475195015913, 'reg_alpha': 1.2483116323989767e-07, 'reg_lambda': 1.1199080265464834, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:57:29,276] Trial 58 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.23301132940583405, 'n_estimators': 1073, 'subsample': 0.5321668394761925, 'colsample_bytree': 0.6240021670785446, 'min_child_weight': 6, 'gamma': 0.18942951403306463, 'reg_alpha': 1.262059566553557e-07, 'reg_lambda': 8.448710311751288, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  31%|███       | 62/200 [00:55<02:16,  1.01it/s]

[I 2025-11-10 17:57:31,024] Trial 60 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10417903360887316, 'n_estimators': 1123, 'subsample': 0.8834679398119002, 'colsample_bytree': 0.8345617397842292, 'min_child_weight': 6, 'gamma': 3.9982185842848357, 'reg_alpha': 8.497712427510041e-08, 'reg_lambda': 0.02199194358002706, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  32%|███▏      | 63/200 [00:58<03:06,  1.36s/it]

[I 2025-11-10 17:57:33,503] Trial 62 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.15380220068077816, 'n_estimators': 1224, 'subsample': 0.6007977454347126, 'colsample_bytree': 0.8816578143910525, 'min_child_weight': 5, 'gamma': 3.977197457944254, 'reg_alpha': 0.10960333200890754, 'reg_lambda': 0.0012959366486786415, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  32%|███▏      | 64/200 [00:59<02:49,  1.24s/it]

[I 2025-11-10 17:57:34,418] Trial 63 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.15268381030101394, 'n_estimators': 1202, 'subsample': 0.5929540910675614, 'colsample_bytree': 0.8826177389302605, 'min_child_weight': 10, 'gamma': 4.303898048205163, 'reg_alpha': 0.06764991381952455, 'reg_lambda': 0.16648600469808023, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:57:34,452] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.1580237350704247, 'n_estimators': 1198, 'subsample': 0.5021013676473559, 'colsample_bytree': 0.8830135519621933, 'min_child_weight': 10, 'gamma': 4.313572928982187, 'reg_alpha': 0.04250413962644561, 'reg_lambda': 3.135346460773153, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  33%|███▎      | 66/200 [01:01<02:32,  1.14s/it]

[I 2025-11-10 17:57:36,417] Trial 65 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.15081891835385333, 'n_estimators': 1223, 'subsample': 0.5966996322321891, 'colsample_bytree': 0.88471176465745, 'min_child_weight': 10, 'gamma': 4.972634552992488, 'reg_alpha': 0.040103462575705594, 'reg_lambda': 0.2258185311485, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:57:36,498] Trial 68 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.013620999213778762, 'n_estimators': 445, 'subsample': 0.5516139161662699, 'colsample_bytree': 0.7929172030233373, 'min_child_weight': 7, 'gamma': 4.970569526622217, 'reg_alpha': 0.4189592319835477, 'reg_lambda': 0.9982175822290901, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  34%|███▍      | 68/200 [01:02<01:59,  1.10it/s]

[I 2025-11-10 17:57:37,464] Trial 69 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.015392680863534923, 'n_estimators': 203, 'subsample': 0.670383947833254, 'colsample_bytree': 0.7923691831510776, 'min_child_weight': 7, 'gamma': 2.1683292121185196, 'reg_alpha': 3.673990346674562e-08, 'reg_lambda': 1.6363900225099794, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  34%|███▍      | 69/200 [01:04<02:24,  1.10s/it]

[I 2025-11-10 17:57:39,281] Trial 66 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.13041059272489178, 'n_estimators': 1333, 'subsample': 0.5934083400807267, 'colsample_bytree': 0.7678581749127547, 'min_child_weight': 10, 'gamma': 4.347583611603296, 'reg_alpha': 0.049234223865006935, 'reg_lambda': 1.9656517012714123, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  35%|███▌      | 70/200 [01:04<02:17,  1.06s/it]

[I 2025-11-10 17:57:40,198] Trial 67 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.01262410964505554, 'n_estimators': 1336, 'subsample': 0.501411990389685, 'colsample_bytree': 0.7946659294106876, 'min_child_weight': 7, 'gamma': 4.981020413083951, 'reg_alpha': 1.8280191623873128e-08, 'reg_lambda': 2.9175332311780497, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  36%|███▌      | 71/200 [01:05<01:50,  1.17it/s]

[I 2025-11-10 17:57:40,448] Trial 71 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.12654165146825222, 'n_estimators': 666, 'subsample': 0.6996323190744592, 'colsample_bytree': 0.9100708650016309, 'min_child_weight': 5, 'gamma': 3.6861485847846276, 'reg_alpha': 0.0001824442845615344, 'reg_lambda': 2.3120671573793827e-07, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  36%|███▌      | 72/200 [01:07<02:32,  1.19s/it]

[I 2025-11-10 17:57:42,587] Trial 70 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05209684405948064, 'n_estimators': 1378, 'subsample': 0.6367308901475294, 'colsample_bytree': 0.9053828150990068, 'min_child_weight': 7, 'gamma': 2.1402431884986903, 'reg_alpha': 1.5775913788096025e-08, 'reg_lambda': 2.484196504693935, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  36%|███▋      | 73/200 [01:07<02:10,  1.03s/it]

[I 2025-11-10 17:57:43,184] Trial 73 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01989367796485202, 'n_estimators': 665, 'subsample': 0.7044425652766229, 'colsample_bytree': 0.8566568307914888, 'min_child_weight': 5, 'gamma': 3.7523657973698077, 'reg_alpha': 0.010996001792596072, 'reg_lambda': 1.1800325022467366e-06, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  37%|███▋      | 74/200 [01:08<01:47,  1.17it/s]

[I 2025-11-10 17:57:43,593] Trial 72 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02189957156977534, 'n_estimators': 966, 'subsample': 0.6389429006903583, 'colsample_bytree': 0.907546694507142, 'min_child_weight': 5, 'gamma': 3.6805946694569114, 'reg_alpha': 0.011418135312079233, 'reg_lambda': 1.9395982721967318e-07, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  38%|███▊      | 75/200 [01:09<01:56,  1.07it/s]

[I 2025-11-10 17:57:44,711] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.022206629496417166, 'n_estimators': 966, 'subsample': 0.6374426718860776, 'colsample_bytree': 0.8618826853412062, 'min_child_weight': 8, 'gamma': 4.649579817380957, 'reg_alpha': 1.0602372469151704e-08, 'reg_lambda': 9.75142725472905e-07, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  38%|███▊      | 76/200 [01:11<02:22,  1.15s/it]

[I 2025-11-10 17:57:46,391] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.026022986317548708, 'n_estimators': 853, 'subsample': 0.5177581577905217, 'colsample_bytree': 0.8596032509718455, 'min_child_weight': 9, 'gamma': 4.653146281484541, 'reg_alpha': 1.081186417594179e-08, 'reg_lambda': 1.2453943114077403e-06, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  38%|███▊      | 77/200 [01:11<02:01,  1.01it/s]

[I 2025-11-10 17:57:47,002] Trial 76 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.022176263764845196, 'n_estimators': 852, 'subsample': 0.518053877958485, 'colsample_bytree': 0.942484288096544, 'min_child_weight': 8, 'gamma': 4.6407043696204315, 'reg_alpha': 2.240241717723375e-05, 'reg_lambda': 1.1170115890533847e-07, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  39%|███▉      | 78/200 [01:12<01:41,  1.20it/s]

[I 2025-11-10 17:57:47,449] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.031887055450475564, 'n_estimators': 840, 'subsample': 0.5201397469437908, 'colsample_bytree': 0.9552095019575393, 'min_child_weight': 8, 'gamma': 4.633517157729776, 'reg_alpha': 0.0043670534651051056, 'reg_lambda': 0.7607572323068755, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  40%|███▉      | 79/200 [01:13<01:50,  1.10it/s]

[I 2025-11-10 17:57:48,546] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.02991262682604813, 'n_estimators': 890, 'subsample': 0.5211260023656406, 'colsample_bytree': 0.6973558129078087, 'min_child_weight': 9, 'gamma': 4.44916724624655, 'reg_alpha': 7.075051767779538e-06, 'reg_lambda': 0.6602616062699637, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  40%|████      | 80/200 [01:15<02:19,  1.16s/it]

[I 2025-11-10 17:57:50,298] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.028467212496069733, 'n_estimators': 835, 'subsample': 0.5571863218210041, 'colsample_bytree': 0.9656325092807965, 'min_child_weight': 8, 'gamma': 3.497887862170857, 'reg_alpha': 0.004507995014182732, 'reg_lambda': 0.41434519206949066, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  40%|████      | 81/200 [01:15<02:00,  1.01s/it]

[I 2025-11-10 17:57:50,954] Trial 80 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03255375301665703, 'n_estimators': 892, 'subsample': 0.5562810712670531, 'colsample_bytree': 0.6989457526126497, 'min_child_weight': 9, 'gamma': 1.7420075942796758, 'reg_alpha': 4.1518071898087495e-08, 'reg_lambda': 0.383798759225373, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:57:50,962] Trial 82 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.18996416210102257, 'n_estimators': 569, 'subsample': 0.5809793680435814, 'colsample_bytree': 0.5692748618164347, 'min_child_weight': 6, 'gamma': 1.7512068179222715, 'reg_alpha': 0.0008147586192778348, 'reg_lambda': 0.00014138153761137016, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  42%|████▏     | 83/200 [01:16<01:19,  1.47it/s]

[I 2025-11-10 17:57:51,543] Trial 81 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.0953467275010137, 'n_estimators': 884, 'subsample': 0.5535712443529687, 'colsample_bytree': 0.985070211049874, 'min_child_weight': 9, 'gamma': 1.8640203325762408, 'reg_alpha': 6.530381002574675e-06, 'reg_lambda': 0.4143399412922385, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  42%|████▏     | 84/200 [01:18<02:02,  1.06s/it]

[I 2025-11-10 17:57:53,745] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.19924793213952233, 'n_estimators': 747, 'subsample': 0.676441306688828, 'colsample_bytree': 0.822754625990007, 'min_child_weight': 6, 'gamma': 1.7751369187913002, 'reg_alpha': 0.02328612833386625, 'reg_lambda': 4.028348564320808, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  42%|████▎     | 85/200 [01:19<01:47,  1.06it/s]

[I 2025-11-10 17:57:54,352] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09104014312332304, 'n_estimators': 744, 'subsample': 0.7825651857412794, 'colsample_bytree': 0.8278238111490998, 'min_child_weight': 7, 'gamma': 4.880042707941162, 'reg_alpha': 2.7195869690769294e-08, 'reg_lambda': 5.008471984241232, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  43%|████▎     | 86/200 [01:19<01:32,  1.23it/s]

[I 2025-11-10 17:57:54,819] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2034245636045826, 'n_estimators': 756, 'subsample': 0.6097661316207048, 'colsample_bytree': 0.6790384793818673, 'min_child_weight': 7, 'gamma': 4.124804302698585, 'reg_alpha': 2.77903173876144e-07, 'reg_lambda': 4.497257596901398, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  44%|████▎     | 87/200 [01:20<01:44,  1.08it/s]

[I 2025-11-10 17:57:56,033] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.26228783355650864, 'n_estimators': 1149, 'subsample': 0.6725411950283436, 'colsample_bytree': 0.8265489951784171, 'min_child_weight': 7, 'gamma': 4.908308828346108, 'reg_alpha': 2.733367238791533e-07, 'reg_lambda': 4.9798361852860875, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  44%|████▍     | 88/200 [01:23<02:39,  1.42s/it]

[I 2025-11-10 17:57:58,705] Trial 87 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.05566761335817255, 'n_estimators': 1133, 'subsample': 0.9914045949641255, 'colsample_bytree': 0.8256087484001624, 'min_child_weight': 8, 'gamma': 4.878267502481188, 'reg_alpha': 2.9058827602547783e-08, 'reg_lambda': 1.2661131577451596, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  44%|████▍     | 89/200 [01:24<02:16,  1.23s/it]

[I 2025-11-10 17:57:59,469] Trial 88 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.05789914229957382, 'n_estimators': 1157, 'subsample': 0.6104879361651279, 'colsample_bytree': 0.9266324697727966, 'min_child_weight': 8, 'gamma': 0.858208961183403, 'reg_alpha': 4.2621583771682736e-07, 'reg_lambda': 0.1229841440402359, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  45%|████▌     | 90/200 [01:24<01:44,  1.05it/s]

[I 2025-11-10 17:57:59,745] Trial 89 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.04518093278674125, 'n_estimators': 1135, 'subsample': 0.542660682728973, 'colsample_bytree': 0.919766281645145, 'min_child_weight': 8, 'gamma': 4.846791464130319, 'reg_alpha': 5.773591745901448e-08, 'reg_lambda': 0.12501704233493566, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  46%|████▌     | 91/200 [01:25<01:50,  1.01s/it]

[I 2025-11-10 17:58:00,898] Trial 90 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.05953232651035208, 'n_estimators': 1104, 'subsample': 0.6227132740819766, 'colsample_bytree': 0.9236223873161288, 'min_child_weight': 8, 'gamma': 0.8481065977469473, 'reg_alpha': 7.233574306086677e-07, 'reg_lambda': 1.6329188667054864, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  46%|████▌     | 92/200 [01:28<02:34,  1.43s/it]

[I 2025-11-10 17:58:03,333] Trial 91 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.024199129216735848, 'n_estimators': 1034, 'subsample': 0.5778469216566415, 'colsample_bytree': 0.9240759988876779, 'min_child_weight': 8, 'gamma': 0.4738593481539487, 'reg_alpha': 1.126152103561994e-06, 'reg_lambda': 0.1116337681063236, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  47%|████▋     | 94/200 [01:28<01:35,  1.11it/s]

[I 2025-11-10 17:58:04,084] Trial 92 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.03908179209513695, 'n_estimators': 1034, 'subsample': 0.5815857129515183, 'colsample_bytree': 0.8488245883293625, 'min_child_weight': 6, 'gamma': 2.6372215800546233, 'reg_alpha': 5.485522729724645e-08, 'reg_lambda': 6.468715991921522e-06, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:58:04,203] Trial 93 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.07525792534753163, 'n_estimators': 1039, 'subsample': 0.5789643158679103, 'colsample_bytree': 0.6449129218781404, 'min_child_weight': 6, 'gamma': 4.461471826775465, 'reg_alpha': 0.1480022712158578, 'reg_lambda': 4.0961994588374187e-07, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  48%|████▊     | 95/200 [01:29<01:23,  1.25it/s]

[I 2025-11-10 17:58:04,765] Trial 95 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.019007690930307804, 'n_estimators': 280, 'subsample': 0.5662315915324877, 'colsample_bytree': 0.8451835541837426, 'min_child_weight': 9, 'gamma': 4.481659900575164, 'reg_alpha': 7.198253051353935e-08, 'reg_lambda': 0.03086294709001823, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  48%|████▊     | 97/200 [01:30<00:55,  1.85it/s]

[I 2025-11-10 17:58:05,246] Trial 97 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.024038889986397537, 'n_estimators': 200, 'subsample': 0.5631154142106845, 'colsample_bytree': 0.7586004478827088, 'min_child_weight': 9, 'gamma': 3.079434294797296, 'reg_alpha': 1.4093857538054796e-07, 'reg_lambda': 0.0356404044399657, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:58:05,404] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03736079115685668, 'n_estimators': 997, 'subsample': 0.5749404821217479, 'colsample_bytree': 0.8501646877532347, 'min_child_weight': 9, 'gamma': 4.752267240651467, 'reg_alpha': 7.938891659681264e-08, 'reg_lambda': 0.03850575979773241, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  49%|████▉     | 98/200 [01:33<02:04,  1.22s/it]

[I 2025-11-10 17:58:08,212] Trial 98 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02652138877106297, 'n_estimators': 808, 'subsample': 0.6593628583119799, 'colsample_bytree': 0.8691159747293925, 'min_child_weight': 5, 'gamma': 3.109166480333948, 'reg_alpha': 1.6422274862251266e-07, 'reg_lambda': 0.03749296048349498, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  50%|████▉     | 99/200 [01:33<01:32,  1.09it/s]

[I 2025-11-10 17:58:08,432] Trial 96 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.018562633888454385, 'n_estimators': 992, 'subsample': 0.56708092947502, 'colsample_bytree': 0.8711842560068321, 'min_child_weight': 9, 'gamma': 4.461292501244506, 'reg_alpha': 9.358564105107173e-08, 'reg_lambda': 0.0023474337222963654, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  50%|█████     | 101/200 [01:34<01:08,  1.45it/s]

[I 2025-11-10 17:58:09,368] Trial 100 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.026544570664491132, 'n_estimators': 915, 'subsample': 0.7673365987492922, 'colsample_bytree': 0.8717078416214288, 'min_child_weight': 5, 'gamma': 1.5542849074598566, 'reg_alpha': 4.7200807023501156e-05, 'reg_lambda': 9.137115506354862e-08, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:58:09,515] Trial 99 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.035290400843899596, 'n_estimators': 993, 'subsample': 0.7337788969972151, 'colsample_bytree': 0.8750148928371392, 'min_child_weight': 5, 'gamma': 1.5512716560286177, 'reg_alpha': 0.024185699238491887, 'reg_lambda': 0.003044931581062101, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  51%|█████     | 102/200 [01:35<01:17,  1.26it/s]

[I 2025-11-10 17:58:10,540] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.14080327575653198, 'n_estimators': 448, 'subsample': 0.7631931681871728, 'colsample_bytree': 0.7215899141865048, 'min_child_weight': 5, 'gamma': 1.5610162204838138, 'reg_alpha': 1.9626941548151607e-08, 'reg_lambda': 0.012041864742017827, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  52%|█████▏    | 103/200 [01:37<01:44,  1.08s/it]

[I 2025-11-10 17:58:12,296] Trial 101 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.017542068000586098, 'n_estimators': 922, 'subsample': 0.7594956021200026, 'colsample_bytree': 0.60937039314949, 'min_child_weight': 5, 'gamma': 1.5250250846324873, 'reg_alpha': 0.02427901691900177, 'reg_lambda': 0.2262494853187979, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  52%|█████▎    | 105/200 [01:38<01:21,  1.17it/s]

[I 2025-11-10 17:58:13,640] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.017233458440147117, 'n_estimators': 953, 'subsample': 0.6571728373414814, 'colsample_bytree': 0.7251417451281338, 'min_child_weight': 8, 'gamma': 4.989463439359871, 'reg_alpha': 1.8953249134920805e-08, 'reg_lambda': 1.7862866628950974e-08, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:58:13,793] Trial 104 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.028946210552101743, 'n_estimators': 960, 'subsample': 0.6050872918851015, 'colsample_bytree': 0.721059372363884, 'min_child_weight': 7, 'gamma': 1.2862536473911736, 'reg_alpha': 0.21694133858232317, 'reg_lambda': 0.000162057333369405, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  54%|█████▎    | 107/200 [01:41<01:37,  1.05s/it]

[I 2025-11-10 17:58:16,552] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.029927217229371573, 'n_estimators': 1445, 'subsample': 0.6276017542051823, 'colsample_bytree': 0.6048904181769827, 'min_child_weight': 7, 'gamma': 4.18361557016624, 'reg_alpha': 0.18445738676773532, 'reg_lambda': 3.433320059470542e-05, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:58:16,718] Trial 107 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.06608787451616259, 'n_estimators': 688, 'subsample': 0.6089679624550021, 'colsample_bytree': 0.8908492941464992, 'min_child_weight': 7, 'gamma': 4.75522181816752, 'reg_alpha': 2.0651369563096265, 'reg_lambda': 0.0013289248222235132, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  54%|█████▍    | 108/200 [01:43<02:00,  1.31s/it]

[I 2025-11-10 17:58:18,631] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02945371385634175, 'n_estimators': 1447, 'subsample': 0.6052111935294279, 'colsample_bytree': 0.8943228939304533, 'min_child_weight': 7, 'gamma': 4.180068962293939, 'reg_alpha': 0.21816483601618217, 'reg_lambda': 0.0007753491587984181, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  55%|█████▍    | 109/200 [01:44<01:58,  1.30s/it]

[I 2025-11-10 17:58:19,905] Trial 108 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.11666736966714195, 'n_estimators': 1438, 'subsample': 0.6288582430570232, 'colsample_bytree': 0.8970589890521962, 'min_child_weight': 7, 'gamma': 4.69265451057135, 'reg_alpha': 0.10979453548752816, 'reg_lambda': 0.0009428221142360544, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:58:20,005] Trial 111 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.11738441008662791, 'n_estimators': 308, 'subsample': 0.8078573165459546, 'colsample_bytree': 0.7456002102226722, 'min_child_weight': 8, 'gamma': 4.559594847316486, 'reg_alpha': 0.0751061471351741, 'reg_lambda': 0.009692318419532319, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  56%|█████▌    | 111/200 [01:46<01:44,  1.17s/it]

[I 2025-11-10 17:58:21,955] Trial 110 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.020471783406883697, 'n_estimators': 1253, 'subsample': 0.7803516218883624, 'colsample_bytree': 0.7424506090883346, 'min_child_weight': 8, 'gamma': 4.5766205266646045, 'reg_alpha': 0.42082473123675723, 'reg_lambda': 0.00926334068168203, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  56%|█████▌    | 112/200 [01:47<01:23,  1.05it/s]

[I 2025-11-10 17:58:22,219] Trial 109 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.17179340514727848, 'n_estimators': 1296, 'subsample': 0.5914500288260239, 'colsample_bytree': 0.8930792693722789, 'min_child_weight': 7, 'gamma': 4.2513754316398344, 'reg_alpha': 0.359987079525914, 'reg_lambda': 0.0010781737122922488, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  56%|█████▋    | 113/200 [01:49<01:53,  1.30s/it]

[I 2025-11-10 17:58:24,533] Trial 114 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.024216279105861025, 'n_estimators': 490, 'subsample': 0.8550063711053958, 'colsample_bytree': 0.9997419351268397, 'min_child_weight': 6, 'gamma': 0.3144994304790505, 'reg_alpha': 0.000280390608202604, 'reg_lambda': 0.0726275634583972, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  57%|█████▋    | 114/200 [01:49<01:31,  1.06s/it]

[I 2025-11-10 17:58:24,943] Trial 115 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.024070199257535424, 'n_estimators': 503, 'subsample': 0.8590631706968338, 'colsample_bytree': 0.9897510500372487, 'min_child_weight': 6, 'gamma': 0.39027607850955726, 'reg_alpha': 9.532459832987786e-05, 'reg_lambda': 0.06235737567973295, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  57%|█████▊    | 115/200 [01:50<01:16,  1.11it/s]

[I 2025-11-10 17:58:25,422] Trial 117 pruned.

Best trial: 1. Best value: 0.5:  58%|█████▊    | 117/200 [01:50<00:44,  1.85it/s]

[I 2025-11-10 17:58:25,597] Trial 113 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.02086706642543099, 'n_estimators': 1257, 'subsample': 0.5894356376893759, 'colsample_bytree': 0.6676883834405779, 'min_child_weight': 6, 'gamma': 3.7980885896148533, 'reg_alpha': 0.41114866885590656, 'reg_lambda': 9.54420933909267, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:58:25,767] Trial 112 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02115934232035639, 'n_estimators': 1288, 'subsample': 0.5903397343332476, 'colsample_bytree': 0.7428396994673075, 'min_child_weight': 8, 'gamma': 4.562301026001739, 'reg_alpha': 0.06652665978942067, 'reg_lambda': 2.769746208448466, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  59%|█████▉    | 118/200 [01:51<00:55,  1.48it/s]

[I 2025-11-10 17:58:26,766] Trial 116 finished with value: 0.47099415204678363 and parameters: {'max_depth': 4, 'learning_rate': 0.03259120974530361, 'n_estimators': 371, 'subsample': 0.9124878722078447, 'colsample_bytree': 0.9760718490880768, 'min_child_weight': 4, 'gamma': 3.409586940340688, 'reg_alpha': 0.0018374308718002211, 'reg_lambda': 2.3684428844288155, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  60%|█████▉    | 119/200 [01:52<00:50,  1.61it/s]

[I 2025-11-10 17:58:27,259] Trial 118 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.2560725620718191, 'n_estimators': 363, 'subsample': 0.9118424936784923, 'colsample_bytree': 0.9711836025465427, 'min_child_weight': 8, 'gamma': 4.834904777849292, 'reg_alpha': 3.527958759693516e-06, 'reg_lambda': 0.017428687303219052, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  60%|██████    | 120/200 [01:52<00:42,  1.90it/s]

[I 2025-11-10 17:58:27,558] Trial 120 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.2738447044389624, 'n_estimators': 377, 'subsample': 0.9109871191113241, 'colsample_bytree': 0.8554009980415861, 'min_child_weight': 8, 'gamma': 3.468449817563683, 'reg_alpha': 2.987258250298576e-06, 'reg_lambda': 0.005519445692892144, 'max_delta_step': 2}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  60%|██████    | 121/200 [01:53<00:56,  1.40it/s]

[I 2025-11-10 17:58:28,713] Trial 123 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.05061502569573765, 'n_estimators': 244, 'subsample': 0.8259316464270009, 'colsample_bytree': 0.7790182737788224, 'min_child_weight': 7, 'gamma': 2.7224278373345574, 'reg_alpha': 3.314393357719989e-05, 'reg_lambda': 0.6332162564576773, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:58:28,800] Trial 119 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.2649832480415487, 'n_estimators': 646, 'subsample': 0.9051310787996659, 'colsample_bytree': 0.9767230437672302, 'min_child_weight': 8, 'gamma': 3.3987643665692544, 'reg_alpha': 0.0019592394113401752, 'reg_lambda': 0.9100852167877992, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  62%|██████▏   | 123/200 [01:54<00:40,  1.92it/s]

[I 2025-11-10 17:58:29,306] Trial 122 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.027554131231763326, 'n_estimators': 402, 'subsample': 0.6832990889851834, 'colsample_bytree': 0.9401253556264665, 'min_child_weight': 7, 'gamma': 4.996525270201604, 'reg_alpha': 1.0315968763868845e-08, 'reg_lambda': 0.26561520755714624, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  62%|██████▏   | 124/200 [01:58<01:47,  1.41s/it]

[I 2025-11-10 17:58:33,432] Trial 121 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.2693531143428895, 'n_estimators': 1500, 'subsample': 0.6850999705140678, 'colsample_bytree': 0.9426402839404915, 'min_child_weight': 8, 'gamma': 4.89771772123038, 'reg_alpha': 3.7432747383845033e-06, 'reg_lambda': 1.0174904260610134, 'max_delta_step': 2}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  62%|██████▎   | 125/200 [01:59<01:51,  1.49s/it]

[I 2025-11-10 17:58:35,134] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.010848971328554769, 'n_estimators': 1487, 'subsample': 0.6846323205939777, 'colsample_bytree': 0.9406224800776872, 'min_child_weight': 10, 'gamma': 4.052908022715529, 'reg_alpha': 1.0319306077159121e-08, 'reg_lambda': 1.3082197254402348, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:58:35,140] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01141588440628063, 'n_estimators': 1492, 'subsample': 0.8367057213403644, 'colsample_bytree': 0.9360464148566139, 'min_child_weight': 10, 'gamma': 4.043335998212582, 'reg_alpha': 0.011836557203826672, 'reg_lambda': 1.4016888307773137, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  64%|██████▎   | 127/200 [02:00<01:12,  1.01it/s]

[I 2025-11-10 17:58:35,792] Trial 126 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.014136335951177205, 'n_estimators': 1490, 'subsample': 0.8867491324107952, 'colsample_bytree': 0.9560418338569273, 'min_child_weight': 9, 'gamma': 2.2856787621582875, 'reg_alpha': 0.013816465430300122, 'reg_lambda': 1.8187408790959688e-06, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  64%|██████▍   | 128/200 [02:04<02:01,  1.68s/it]

[I 2025-11-10 17:58:39,733] Trial 127 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.010513765311881392, 'n_estimators': 1496, 'subsample': 0.5281480990954903, 'colsample_bytree': 0.8149258491614628, 'min_child_weight': 10, 'gamma': 4.7063948997226115, 'reg_alpha': 0.6894181766499702, 'reg_lambda': 1.6341683098877247, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  64%|██████▍   | 129/200 [02:05<01:52,  1.59s/it]

[I 2025-11-10 17:58:41,039] Trial 128 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07001465582553808, 'n_estimators': 1395, 'subsample': 0.5265570060662507, 'colsample_bytree': 0.838336782539587, 'min_child_weight': 10, 'gamma': 3.872970020480036, 'reg_alpha': 0.031125750506440553, 'reg_lambda': 6.810270465820001e-07, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  65%|██████▌   | 130/200 [02:06<01:28,  1.27s/it]

[I 2025-11-10 17:58:41,403] Trial 129 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.015356332952817771, 'n_estimators': 1414, 'subsample': 0.5409184985372473, 'colsample_bytree': 0.9552421897661159, 'min_child_weight': 10, 'gamma': 4.359767996138215, 'reg_alpha': 0.03290259579971233, 'reg_lambda': 2.023007454021418e-06, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  66%|██████▌   | 131/200 [02:06<01:06,  1.03it/s]

[I 2025-11-10 17:58:41,583] Trial 130 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04144539385027124, 'n_estimators': 1418, 'subsample': 0.5065183874911539, 'colsample_bytree': 0.5782056324041881, 'min_child_weight': 10, 'gamma': 4.8250599679991515, 'reg_alpha': 0.6797812297877699, 'reg_lambda': 0.0004610413931261661, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  66%|██████▌   | 132/200 [02:07<01:08,  1.00s/it]

[I 2025-11-10 17:58:42,677] Trial 133 pruned.

Best trial: 1. Best value: 0.5:  66%|██████▋   | 133/200 [02:08<01:07,  1.01s/it]

[I 2025-11-10 17:58:43,714] Trial 132 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07626902345831295, 'n_estimators': 562, 'subsample': 0.5063595006613665, 'colsample_bytree': 0.9879560710701323, 'min_child_weight': 10, 'gamma': 4.383054877624607, 'reg_alpha': 3.539864656404137e-08, 'reg_lambda': 7.056144988985493, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  67%|██████▋   | 134/200 [02:09<00:58,  1.13it/s]

[I 2025-11-10 17:58:44,283] Trial 134 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.011220068601884335, 'n_estimators': 573, 'subsample': 0.873072070945165, 'colsample_bytree': 0.9965339328978704, 'min_child_weight': 10, 'gamma': 4.233465330099709, 'reg_alpha': 0.26167368502218086, 'reg_lambda': 0.0669861131663437, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  68%|██████▊   | 136/200 [02:10<00:52,  1.21it/s]

[I 2025-11-10 17:58:45,935] Trial 131 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0833240290956175, 'n_estimators': 1409, 'subsample': 0.510036592620096, 'colsample_bytree': 0.6834124447064152, 'min_child_weight': 10, 'gamma': 4.808652799336636, 'reg_alpha': 1.3966612113682156e-05, 'reg_lambda': 3.083847469704021e-07, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:58:46,072] Trial 135 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.012037161558682145, 'n_estimators': 698, 'subsample': 0.8713740741017978, 'colsample_bytree': 0.9827104817654388, 'min_child_weight': 10, 'gamma': 0.5799126675504482, 'reg_alpha': 1.2479311526633903, 'reg_lambda': 0.07145134538406754, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  69%|██████▉   | 138/200 [02:11<00:34,  1.81it/s]

[I 2025-11-10 17:58:46,579] Trial 136 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.0866838438210286, 'n_estimators': 585, 'subsample': 0.8776004783400353, 'colsample_bytree': 0.9997692859420143, 'min_child_weight': 9, 'gamma': 1.9430224017014794, 'reg_alpha': 0.2599267104657356, 'reg_lambda': 0.05759967901912878, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:58:46,717] Trial 137 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.012533637867071675, 'n_estimators': 532, 'subsample': 0.8920399150872731, 'colsample_bytree': 0.5321327024128684, 'min_child_weight': 9, 'gamma': 3.9152731827703544, 'reg_alpha': 1.0987524109073197, 'reg_lambda': 6.101497489375618e-08, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  70%|██████▉   | 139/200 [02:13<00:56,  1.09it/s]

[I 2025-11-10 17:58:48,493] Trial 140 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.012899981321827361, 'n_estimators': 414, 'subsample': 0.9367278289498624, 'colsample_bytree': 0.6967546425067744, 'min_child_weight': 9, 'gamma': 3.9176871529959882, 'reg_alpha': 0.1229157888205628, 'reg_lambda': 0.018564125318887445, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  70%|███████   | 140/200 [02:13<00:49,  1.20it/s]

[I 2025-11-10 17:58:49,115] Trial 138 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.010102502323066732, 'n_estimators': 693, 'subsample': 0.9375645317109161, 'colsample_bytree': 0.5447141735485024, 'min_child_weight': 9, 'gamma': 3.5756915614141715, 'reg_alpha': 0.11557015094073948, 'reg_lambda': 3.7283863276539995, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  70%|███████   | 141/200 [02:14<00:48,  1.23it/s]

[I 2025-11-10 17:58:49,895] Trial 139 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.02539576486922197, 'n_estimators': 789, 'subsample': 0.9338965528936854, 'colsample_bytree': 0.8666450051033073, 'min_child_weight': 9, 'gamma': 1.3271931241388806, 'reg_alpha': 0.11097051829280348, 'reg_lambda': 3.821450550264037, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  71%|███████   | 142/200 [02:16<00:58,  1.01s/it]

[I 2025-11-10 17:58:51,369] Trial 142 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.02242570987112851, 'n_estimators': 630, 'subsample': 0.798917690371007, 'colsample_bytree': 0.6294595219024856, 'min_child_weight': 6, 'gamma': 1.3272486909018342, 'reg_alpha': 2.8836382004248264, 'reg_lambda': 0.29036608653792645, 'max_delta_step': 1}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  72%|███████▏  | 143/200 [02:17<00:55,  1.03it/s]

[I 2025-11-10 17:58:52,235] Trial 144 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09750347937515313, 'n_estimators': 521, 'subsample': 0.644556844991404, 'colsample_bytree': 0.6340787497945303, 'min_child_weight': 5, 'gamma': 4.12516518624395, 'reg_alpha': 2.1942231872580424, 'reg_lambda': 0.00031021100369054935, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  72%|███████▏  | 144/200 [02:17<00:47,  1.17it/s]

[I 2025-11-10 17:58:52,836] Trial 143 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.025756338396800926, 'n_estimators': 792, 'subsample': 0.8387481553482738, 'colsample_bytree': 0.8610650929622268, 'min_child_weight': 8, 'gamma': 4.960947140795034, 'reg_alpha': 1.8684647351940946, 'reg_lambda': 0.3400495824321687, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  72%|███████▎  | 145/200 [02:17<00:38,  1.41it/s]

[I 2025-11-10 17:58:53,193] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.025491096584543873, 'n_estimators': 1365, 'subsample': 0.6462568373956429, 'colsample_bytree': 0.8626872219806591, 'min_child_weight': 6, 'gamma': 0.9590184075001649, 'reg_alpha': 0.14701314481898292, 'reg_lambda': 0.00023969740727344238, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  73%|███████▎  | 146/200 [02:19<00:51,  1.05it/s]

[I 2025-11-10 17:58:54,710] Trial 145 finished with value: 0.47074074074074074 and parameters: {'max_depth': 4, 'learning_rate': 0.0987094344952243, 'n_estimators': 726, 'subsample': 0.9738589515603693, 'colsample_bytree': 0.6500343233193501, 'min_child_weight': 5, 'gamma': 4.927913621524439, 'reg_alpha': 1.7223993812535023e-08, 'reg_lambda': 9.56637556324176e-06, 'max_delta_step': 1}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  74%|███████▎  | 147/200 [02:20<00:47,  1.12it/s]

[I 2025-11-10 17:58:55,469] Trial 148 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.06396157421777915, 'n_estimators': 469, 'subsample': 0.9844555452925218, 'colsample_bytree': 0.9650485735948112, 'min_child_weight': 10, 'gamma': 4.70108977690176, 'reg_alpha': 2.1976041425132163e-08, 'reg_lambda': 6.116341365667574e-05, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  74%|███████▍  | 148/200 [02:21<00:54,  1.04s/it]

[I 2025-11-10 17:58:56,858] Trial 149 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.0316090048806515, 'n_estimators': 477, 'subsample': 0.9575222522557525, 'colsample_bytree': 0.7589816768006556, 'min_child_weight': 10, 'gamma': 0.1469357777262744, 'reg_alpha': 0.007647391827236009, 'reg_lambda': 0.14809619566555468, 'max_delta_step': 1}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  74%|███████▍  | 149/200 [02:21<00:41,  1.24it/s]

[I 2025-11-10 17:58:57,108] Trial 146 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.10362089763914901, 'n_estimators': 1095, 'subsample': 0.958109301398011, 'colsample_bytree': 0.6472491163353681, 'min_child_weight': 10, 'gamma': 2.4974799967239134, 'reg_alpha': 1.7238544116393123e-08, 'reg_lambda': 0.029539738462772903, 'max_delta_step': 1}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  75%|███████▌  | 150/200 [02:23<00:53,  1.06s/it]

[I 2025-11-10 17:58:58,779] Trial 147 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.10284331020080865, 'n_estimators': 1351, 'subsample': 0.9592209854189306, 'colsample_bytree': 0.7587137851686, 'min_child_weight': 10, 'gamma': 4.70897756793606, 'reg_alpha': 0.048436050874170765, 'reg_lambda': 1.0599599888207202e-05, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  76%|███████▌  | 151/200 [02:24<00:44,  1.10it/s]

[I 2025-11-10 17:58:59,328] Trial 150 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.21494297526524128, 'n_estimators': 874, 'subsample': 0.7091721957227373, 'colsample_bytree': 0.7103674929066954, 'min_child_weight': 7, 'gamma': 4.039291095468805, 'reg_alpha': 0.05337197592941726, 'reg_lambda': 0.1539335340742308, 'max_delta_step': 1}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  76%|███████▌  | 152/200 [02:25<00:49,  1.04s/it]

[I 2025-11-10 17:59:00,664] Trial 151 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.10891552284737292, 'n_estimators': 883, 'subsample': 0.7461735454740733, 'colsample_bytree': 0.6685073792209424, 'min_child_weight': 7, 'gamma': 3.807780442874647, 'reg_alpha': 8.673994194147887e-06, 'reg_lambda': 0.015229392856302192, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  77%|███████▋  | 154/200 [02:26<00:33,  1.36it/s]

[I 2025-11-10 17:59:01,563] Trial 152 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.14079097944976104, 'n_estimators': 1016, 'subsample': 0.5483363712257364, 'colsample_bytree': 0.714266506550326, 'min_child_weight': 8, 'gamma': 4.782837929976871, 'reg_alpha': 0.059367436150421546, 'reg_lambda': 0.013658856846613986, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:59:01,700] Trial 154 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.0723016020371463, 'n_estimators': 517, 'subsample': 0.622333055477406, 'colsample_bytree': 0.5929425883655028, 'min_child_weight': 6, 'gamma': 4.287288043601718, 'reg_alpha': 6.239402770052288e-06, 'reg_lambda': 9.967603863465153e-05, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  78%|███████▊  | 155/200 [02:27<00:34,  1.31it/s]

[I 2025-11-10 17:59:02,521] Trial 153 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.13636462532447213, 'n_estimators': 827, 'subsample': 0.6187861795449512, 'colsample_bytree': 0.6730063415609713, 'min_child_weight': 8, 'gamma': 2.7758255210361544, 'reg_alpha': 2.3324750568083477e-05, 'reg_lambda': 0.0020505001337866725, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  78%|███████▊  | 156/200 [02:27<00:31,  1.41it/s]

[I 2025-11-10 17:59:03,103] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.08798470309833427, 'n_estimators': 521, 'subsample': 0.6324971109868779, 'colsample_bytree': 0.5940855722011433, 'min_child_weight': 6, 'gamma': 4.310020420879545, 'reg_alpha': 1.1884493842914133e-06, 'reg_lambda': 3.8775121404701044e-05, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  78%|███████▊  | 157/200 [02:28<00:30,  1.43it/s]

[I 2025-11-10 17:59:03,789] Trial 157 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.29704856392270385, 'n_estimators': 423, 'subsample': 0.8291046127544042, 'colsample_bytree': 0.8780040742869317, 'min_child_weight': 5, 'gamma': 4.515896160730674, 'reg_alpha': 2.2917170271833353e-05, 'reg_lambda': 5.788660226927535, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  79%|███████▉  | 158/200 [02:29<00:31,  1.35it/s]

[I 2025-11-10 17:59:04,625] Trial 156 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.2980177804167017, 'n_estimators': 608, 'subsample': 0.6218742202032123, 'colsample_bytree': 0.8777576942969798, 'min_child_weight': 6, 'gamma': 4.313358649344569, 'reg_alpha': 2.5773000935213596e-05, 'reg_lambda': 5.865451659103786, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  80%|███████▉  | 159/200 [02:30<00:29,  1.39it/s]

[I 2025-11-10 17:59:05,300] Trial 158 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.09106227349886745, 'n_estimators': 594, 'subsample': 0.6968224100651559, 'colsample_bytree': 0.6076884880510337, 'min_child_weight': 5, 'gamma': 4.568630173826356, 'reg_alpha': 1.1618821105717565e-06, 'reg_lambda': 2.232742258540333e-05, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  80%|████████  | 160/200 [02:30<00:26,  1.49it/s]

[I 2025-11-10 17:59:05,861] Trial 159 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.08121109184282643, 'n_estimators': 599, 'subsample': 0.7155212735158506, 'colsample_bytree': 0.6103957877115537, 'min_child_weight': 5, 'gamma': 4.513784732525256, 'reg_alpha': 8.864087731383049e-05, 'reg_lambda': 4.151972948449552e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  80%|████████  | 161/200 [02:31<00:27,  1.41it/s]

[I 2025-11-10 17:59:06,651] Trial 160 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.12161953966002377, 'n_estimators': 611, 'subsample': 0.7333865930168588, 'colsample_bytree': 0.6091886821516104, 'min_child_weight': 7, 'gamma': 4.133924962947398, 'reg_alpha': 0.31682178585651327, 'reg_lambda': 2.5385732434475187e-05, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  81%|████████  | 162/200 [02:32<00:32,  1.15it/s]

[I 2025-11-10 17:59:07,886] Trial 162 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.08269231570185254, 'n_estimators': 556, 'subsample': 0.6633931496701494, 'colsample_bytree': 0.8484452850851592, 'min_child_weight': 7, 'gamma': 4.111040952040031, 'reg_alpha': 2.3005938528528683e-06, 'reg_lambda': 4.043168347144467e-06, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  82%|████████▏ | 163/200 [02:34<00:39,  1.07s/it]

[I 2025-11-10 17:59:09,417] Trial 161 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.0811653817527746, 'n_estimators': 1056, 'subsample': 0.736233082786751, 'colsample_bytree': 0.8452864616641087, 'min_child_weight': 7, 'gamma': 4.1473075987898556, 'reg_alpha': 1.0607691435522939e-05, 'reg_lambda': 8.184048533997358e-05, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  82%|████████▏ | 164/200 [02:35<00:39,  1.10s/it]

[I 2025-11-10 17:59:10,583] Trial 163 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.12330786079515996, 'n_estimators': 1058, 'subsample': 0.65834019758755, 'colsample_bytree': 0.9088800145287557, 'min_child_weight': 7, 'gamma': 4.870380126435217, 'reg_alpha': 0.4057496870975743, 'reg_lambda': 1.4474895265285162e-08, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  82%|████████▎ | 165/200 [02:37<00:47,  1.36s/it]

[I 2025-11-10 17:59:12,566] Trial 165 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.022750263045457575, 'n_estimators': 1062, 'subsample': 0.6571140290751789, 'colsample_bytree': 0.9119126422230833, 'min_child_weight': 6, 'gamma': 4.899207747711091, 'reg_alpha': 4.597072622881178e-06, 'reg_lambda': 6.735005202749032e-07, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  83%|████████▎ | 166/200 [02:37<00:38,  1.14s/it]

[I 2025-11-10 17:59:13,188] Trial 164 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.027940210479494663, 'n_estimators': 1462, 'subsample': 0.6651806257532011, 'colsample_bytree': 0.8452154080850909, 'min_child_weight': 6, 'gamma': 2.1659073147933827, 'reg_alpha': 5.258149617807934e-06, 'reg_lambda': 1.7542072038997517e-07, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  84%|████████▎ | 167/200 [02:40<00:51,  1.57s/it]

[I 2025-11-10 17:59:15,757] Trial 166 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.02759016323534931, 'n_estimators': 1455, 'subsample': 0.6687759695702167, 'colsample_bytree': 0.9057354986331345, 'min_child_weight': 6, 'gamma': 4.865313134704279, 'reg_alpha': 4.5242768049422007e-05, 'reg_lambda': 1.5542119993642902e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  84%|████████▍ | 168/200 [02:41<00:46,  1.45s/it]

[I 2025-11-10 17:59:16,940] Trial 167 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09315238493945845, 'n_estimators': 1452, 'subsample': 0.6736718670690043, 'colsample_bytree': 0.9788136635632959, 'min_child_weight': 6, 'gamma': 0.8160915775819665, 'reg_alpha': 4.3097880744996815e-05, 'reg_lambda': 6.42198381537952e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  84%|████████▍ | 169/200 [02:42<00:34,  1.11s/it]

[I 2025-11-10 17:59:17,236] Trial 169 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.24641591175805974, 'n_estimators': 918, 'subsample': 0.7746672147490905, 'colsample_bytree': 0.8317781705227317, 'min_child_weight': 8, 'gamma': 3.257370026095473, 'reg_alpha': 5.746158226387386e-05, 'reg_lambda': 3.428147402040068e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  85%|████████▌ | 170/200 [02:43<00:39,  1.32s/it]

[I 2025-11-10 17:59:19,056] Trial 168 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.16129239685261992, 'n_estimators': 1459, 'subsample': 0.6007761607373684, 'colsample_bytree': 0.9739745058520609, 'min_child_weight': 6, 'gamma': 2.1716954405338713, 'reg_alpha': 4.001708019801873e-05, 'reg_lambda': 0.0990620407082614, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  86%|████████▌ | 171/200 [02:44<00:36,  1.24s/it]

[I 2025-11-10 17:59:20,126] Trial 170 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.11087313967436657, 'n_estimators': 944, 'subsample': 0.787664344644406, 'colsample_bytree': 0.9797684815728257, 'min_child_weight': 8, 'gamma': 2.0401920597536747, 'reg_alpha': 0.0002846346072420397, 'reg_lambda': 0.0001626838776363581, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  86%|████████▋ | 173/200 [02:46<00:23,  1.14it/s]

[I 2025-11-10 17:59:21,264] Trial 171 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.11365877511584553, 'n_estimators': 944, 'subsample': 0.7231253778628858, 'colsample_bytree': 0.9910400165785133, 'min_child_weight': 8, 'gamma': 1.8940894311840932, 'reg_alpha': 0.0003256778312251294, 'reg_lambda': 0.10190361107039228, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:59:21,368] Trial 172 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.15890637814878097, 'n_estimators': 967, 'subsample': 0.6008055151001901, 'colsample_bytree': 0.5085408651583443, 'min_child_weight': 8, 'gamma': 4.986548073640312, 'reg_alpha': 0.00020164395292613757, 'reg_lambda': 0.00015225586803696602, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  87%|████████▋ | 174/200 [02:48<00:33,  1.30s/it]

[I 2025-11-10 17:59:23,632] Trial 173 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.17876621749121674, 'n_estimators': 968, 'subsample': 0.7531879781532159, 'colsample_bytree': 0.9885383175204264, 'min_child_weight': 8, 'gamma': 4.429787648582407, 'reg_alpha': 4.8036929601868925e-08, 'reg_lambda': 0.0001399813446536004, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  88%|████████▊ | 175/200 [02:49<00:30,  1.23s/it]

[I 2025-11-10 17:59:24,694] Trial 174 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09483817996102405, 'n_estimators': 975, 'subsample': 0.6420153733727112, 'colsample_bytree': 0.9494754980847847, 'min_child_weight': 6, 'gamma': 1.6154765516016674, 'reg_alpha': 1.453558687585149e-05, 'reg_lambda': 8.781858063903397e-08, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  88%|████████▊ | 176/200 [02:52<00:40,  1.67s/it]

[I 2025-11-10 17:59:27,409] Trial 175 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.1000001217323236, 'n_estimators': 1385, 'subsample': 0.63716757120961, 'colsample_bytree': 0.9545634089551238, 'min_child_weight': 5, 'gamma': 2.344396862775815, 'reg_alpha': 8.314729987193528e-05, 'reg_lambda': 6.846913085694776e-08, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  88%|████████▊ | 177/200 [02:52<00:28,  1.25s/it]

[I 2025-11-10 17:59:27,671] Trial 176 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.0979122125693219, 'n_estimators': 1473, 'subsample': 0.6363810232402899, 'colsample_bytree': 0.6941984950218104, 'min_child_weight': 6, 'gamma': 4.410128596668731, 'reg_alpha': 1.0449029713806435e-05, 'reg_lambda': 1.1175082563668376e-07, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  89%|████████▉ | 178/200 [02:53<00:28,  1.31s/it]

[I 2025-11-10 17:59:29,125] Trial 180 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.04846672207939361, 'n_estimators': 305, 'subsample': 0.6111983996967923, 'colsample_bytree': 0.886855479485275, 'min_child_weight': 10, 'gamma': 3.983571490989209, 'reg_alpha': 0.0006764979309858597, 'reg_lambda': 3.159400890863231e-08, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  90%|████████▉ | 179/200 [02:54<00:23,  1.11s/it]

[I 2025-11-10 17:59:29,756] Trial 179 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07347980164818893, 'n_estimators': 494, 'subsample': 0.8957022370173836, 'colsample_bytree': 0.9300457115603878, 'min_child_weight': 6, 'gamma': 1.6819837940299518, 'reg_alpha': 0.018999372965544846, 'reg_lambda': 1.2230198932269632e-06, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  90%|█████████ | 180/200 [02:54<00:18,  1.11it/s]

[I 2025-11-10 17:59:30,190] Trial 177 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09937257546561537, 'n_estimators': 1474, 'subsample': 0.6515416330438563, 'colsample_bytree': 0.9506125980604151, 'min_child_weight': 6, 'gamma': 1.7009961699934892, 'reg_alpha': 0.00013427253980848782, 'reg_lambda': 8.314764758895531e-08, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  90%|█████████ | 181/200 [02:55<00:17,  1.10it/s]

[I 2025-11-10 17:59:31,118] Trial 178 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07585153863913151, 'n_estimators': 1472, 'subsample': 0.6926894734892496, 'colsample_bytree': 0.8874876117418525, 'min_child_weight': 5, 'gamma': 2.3992280637549825, 'reg_alpha': 1.6254897581435766e-05, 'reg_lambda': 1.0564847203985781e-06, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  91%|█████████ | 182/200 [02:59<00:29,  1.65s/it]

[I 2025-11-10 17:59:34,504] Trial 184 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.08748157882272897, 'n_estimators': 777, 'subsample': 0.5320248247408036, 'colsample_bytree': 0.9182528803050669, 'min_child_weight': 6, 'gamma': 1.8374557405793257, 'reg_alpha': 0.003698851745740806, 'reg_lambda': 0.04103210524575602, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  92%|█████████▏| 184/200 [03:00<00:17,  1.07s/it]

[I 2025-11-10 17:59:35,568] Trial 181 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07402006587910212, 'n_estimators': 1423, 'subsample': 0.5408291024982941, 'colsample_bytree': 0.9271631810965697, 'min_child_weight': 6, 'gamma': 4.80674576349812, 'reg_alpha': 0.019737697195624754, 'reg_lambda': 1.9613822338401412, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:59:35,678] Trial 182 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03070255290050287, 'n_estimators': 1425, 'subsample': 0.6931132524277668, 'colsample_bytree': 0.6598629405431028, 'min_child_weight': 10, 'gamma': 1.990481750060253, 'reg_alpha': 1.54762555919768e-05, 'reg_lambda': 3.173006908375288, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  92%|█████████▎| 185/200 [03:00<00:13,  1.14it/s]

[I 2025-11-10 17:59:36,127] Trial 183 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.030752981768378543, 'n_estimators': 1417, 'subsample': 0.5371017894794377, 'colsample_bytree': 0.6201074914117048, 'min_child_weight': 7, 'gamma': 1.8020864093155573, 'reg_alpha': 0.0033508209400704334, 'reg_lambda': 2.522555962980588e-07, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  93%|█████████▎| 186/200 [03:01<00:10,  1.28it/s]

[I 2025-11-10 17:59:36,682] Trial 188 pruned.

Best trial: 1. Best value: 0.5:  94%|█████████▎| 187/200 [03:02<00:12,  1.01it/s]

[I 2025-11-10 17:59:38,163] Trial 185 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1267981935690899, 'n_estimators': 836, 'subsample': 0.6757202235887619, 'colsample_bytree': 0.6209135587747447, 'min_child_weight': 7, 'gamma': 2.006304134755437, 'reg_alpha': 1.4254830737089121e-08, 'reg_lambda': 4.951460284332525e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  94%|█████████▍| 188/200 [03:03<00:11,  1.03it/s]

[I 2025-11-10 17:59:39,084] Trial 187 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.12663114281758414, 'n_estimators': 737, 'subsample': 0.8159193814473789, 'colsample_bytree': 0.8571027212878778, 'min_child_weight': 7, 'gamma': 1.4707193073828861, 'reg_alpha': 0.18295573648863506, 'reg_lambda': 3.154922477491819e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  94%|█████████▍| 189/200 [03:04<00:08,  1.23it/s]

[I 2025-11-10 17:59:39,536] Trial 186 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03386605300738058, 'n_estimators': 813, 'subsample': 0.8054920844529172, 'colsample_bytree': 0.9605715782693314, 'min_child_weight': 7, 'gamma': 2.0538338491316734, 'reg_alpha': 0.5628869731793521, 'reg_lambda': 3.978019377144192e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  95%|█████████▌| 190/200 [03:05<00:08,  1.16it/s]

[I 2025-11-10 17:59:40,512] Trial 189 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.10789387830620797, 'n_estimators': 815, 'subsample': 0.6743956352989814, 'colsample_bytree': 0.9636308681986602, 'min_child_weight': 7, 'gamma': 4.681594828984379, 'reg_alpha': 0.5307239592115234, 'reg_lambda': 4.85141685688152e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  96%|█████████▌| 191/200 [03:06<00:08,  1.10it/s]

[I 2025-11-10 17:59:41,528] Trial 190 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03472420350273138, 'n_estimators': 731, 'subsample': 0.5178476868251044, 'colsample_bytree': 0.8147298610366678, 'min_child_weight': 5, 'gamma': 4.6534099727420175, 'reg_alpha': 2.768300656817555e-08, 'reg_lambda': 4.6416422263132665e-07, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  96%|█████████▋| 193/200 [03:07<00:05,  1.31it/s]

[I 2025-11-10 17:59:42,880] Trial 191 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03463679525171063, 'n_estimators': 816, 'subsample': 0.5216224475973052, 'colsample_bytree': 0.9344644301625472, 'min_child_weight': 5, 'gamma': 4.637668564893583, 'reg_alpha': 0.5425585565176311, 'reg_lambda': 0.0035251005511994114, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:59:42,994] Trial 192 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.02347498908356115, 'n_estimators': 771, 'subsample': 0.5221720596966313, 'colsample_bytree': 0.7333216274859736, 'min_child_weight': 5, 'gamma': 4.998436810613193, 'reg_alpha': 2.6032774956846295e-08, 'reg_lambda': 9.019789288967434, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  97%|█████████▋| 194/200 [03:08<00:04,  1.43it/s]

[I 2025-11-10 17:59:43,549] Trial 193 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.14675011506403582, 'n_estimators': 659, 'subsample': 0.6503806025043172, 'colsample_bytree': 0.814849608656139, 'min_child_weight': 5, 'gamma': 2.8713654346424766, 'reg_alpha': 3.323147646702006e-05, 'reg_lambda': 9.267173534306364, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  98%|█████████▊| 195/200 [03:10<00:05,  1.07s/it]

[I 2025-11-10 17:59:45,493] Trial 194 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.053785814919980995, 'n_estimators': 870, 'subsample': 0.6826131901212777, 'colsample_bytree': 0.9318666398247653, 'min_child_weight': 6, 'gamma': 1.8408792724061536, 'reg_alpha': 3.164116601636678e-05, 'reg_lambda': 7.392783729979959e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  98%|█████████▊| 196/200 [03:11<00:04,  1.15s/it]

[I 2025-11-10 17:59:46,830] Trial 195 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.037742769503726493, 'n_estimators': 851, 'subsample': 0.6537254881558819, 'colsample_bytree': 0.9995919024026451, 'min_child_weight': 6, 'gamma': 1.9016737647945101, 'reg_alpha': 7.02700015789665e-05, 'reg_lambda': 7.084595462912592e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.
[I 2025-11-10 17:59:46,895] Trial 196 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.027126945049047457, 'n_estimators': 868, 'subsample': 0.651272886471114, 'colsample_bytree': 0.9172156040789019, 'min_child_weight': 6, 'gamma': 2.279345966808461, 'reg_alpha': 6.596292768444584e-05, 'reg_lambda': 2.0231898788583064e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  99%|█████████▉| 198/200 [03:12<00:01,  1.41it/s]

[I 2025-11-10 17:59:47,216] Trial 197 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.05666265179111684, 'n_estimators': 854, 'subsample': 0.69808513057532, 'colsample_bytree': 0.9183077122687207, 'min_child_weight': 6, 'gamma': 1.838895689415486, 'reg_alpha': 8.365951670693992e-05, 'reg_lambda': 7.161754724663835e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5: 100%|█████████▉| 199/200 [03:13<00:00,  1.07it/s]

[I 2025-11-10 17:59:48,836] Trial 198 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09031768299582199, 'n_estimators': 1018, 'subsample': 0.7006594619176785, 'colsample_bytree': 0.9988486438781834, 'min_child_weight': 6, 'gamma': 2.2000378430674474, 'reg_alpha': 0.00010119992368486154, 'reg_lambda': 1.8451404221512906e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5: 100%|██████████| 200/200 [03:14<00:00,  1.03it/s]

[I 2025-11-10 17:59:49,919] Trial 199 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.027154943062859784, 'n_estimators': 1208, 'subsample': 0.5866579866228269, 'colsample_bytree': 0.9463236362471461, 'min_child_weight': 6, 'gamma': 2.5832212322391785, 'reg_alpha': 0.0001249669897799527, 'reg_lambda': 2.029951756164078e-07, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

[I 2025-11-10 17:59:50,740] A new study created in memory with name: 3_1_roc_auc
Best trial: 0. Best value: 0.5:   0%|          | 1/200 [00:02<08:04,  2.44s/it]

[I 2025-11-10 17:59:53,167] Trial 1 finished with value: 0.46456140350877195 and parameters: {'max_depth': 7, 'learning_rate': 0.019765106775260655, 'n_estimators': 357, 'subsample': 0.7795597357676146, 'colsample_bytree': 0.7039802393437353, 'min_child_weight': 3, 'gamma': 1.6400278483732817, 'reg_alpha': 1.5146860348033134e-08, 'reg_lambda': 0.00022692148309029118, 'max_delta_step': 8}. Best is trial 1 with value: 0.46456140350877195.
[I 2025-11-10 17:59:53,175] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.053541784568084, 'n_estimators': 562, 'subsample': 0.6488462067235486, 'colsample_bytree': 0.9610962528490588, 'min_child_weight': 6, 'gamma': 1.8092953843809767, 'reg_alpha': 1.4683427013161001, 'reg_lambda': 1.4138529250419023, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   2%|▏         | 3/200 [00:03<03:33,  1.08s/it]

[I 2025-11-10 17:59:54,392] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.10566868472741076, 'n_estimators': 291, 'subsample': 0.7856363904395207, 'colsample_bytree': 0.7636480150558704, 'min_child_weight': 8, 'gamma': 2.898947457534814, 'reg_alpha': 6.629957137122974, 'reg_lambda': 0.258625481297477, 'max_delta_step': 0}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   2%|▎         | 5/200 [00:05<04:18,  1.33s/it]

[I 2025-11-10 17:59:56,178] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.019241938267669897, 'n_estimators': 1397, 'subsample': 0.6625447729458782, 'colsample_bytree': 0.6162527553773653, 'min_child_weight': 7, 'gamma': 2.3528852036390497, 'reg_alpha': 1.6060809665320167e-05, 'reg_lambda': 2.0043030735470128e-08, 'max_delta_step': 0}. Best is trial 0 with value: 0.5.
[I 2025-11-10 17:59:56,200] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.18389962204444035, 'n_estimators': 753, 'subsample': 0.7737098963829259, 'colsample_bytree': 0.842125645485623, 'min_child_weight': 6, 'gamma': 2.870120467937205, 'reg_alpha': 0.34312000250979346, 'reg_lambda': 5.845645053408537, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.
[I 2025-11-10 17:59:56,238] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.05780628151696756, 'n_estimators': 1381, 'subsample': 0.6768981503604654, 'colsample_bytree': 0.7299456462379695, 'min_child_weight': 5, 'gamma': 1.6687317258609884, 'reg_alpha': 3.77745133927325e-05, 'reg_lambda': 0.0013502053094630987, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   4%|▎         | 7/200 [00:07<03:10,  1.01it/s]

[I 2025-11-10 17:59:58,461] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.027193492861066603, 'n_estimators': 968, 'subsample': 0.5445383978014968, 'colsample_bytree': 0.9682848206166171, 'min_child_weight': 9, 'gamma': 1.3437481520728594, 'reg_alpha': 0.007647949747687826, 'reg_lambda': 6.566495569448033e-05, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 10. Best value: 0.518733:   4%|▍         | 9/200 [00:10<03:37,  1.14s/it]

[I 2025-11-10 18:00:01,534] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.019744814119894257, 'n_estimators': 1319, 'subsample': 0.7226041843526277, 'colsample_bytree': 0.6577066718909425, 'min_child_weight': 9, 'gamma': 2.1230993833013017, 'reg_alpha': 6.847214501644859e-05, 'reg_lambda': 0.00019658744830958853, 'max_delta_step': 1}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:00:01,678] Trial 10 finished with value: 0.5187329434697855 and parameters: {'max_depth': 9, 'learning_rate': 0.26176984029985134, 'n_estimators': 744, 'subsample': 0.7016475423434874, 'colsample_bytree': 0.8797023847076112, 'min_child_weight': 3, 'gamma': 1.8225507829013292, 'reg_alpha': 3.297381310873147e-08, 'reg_lambda': 0.005067125047912673, 'max_delta_step': 10}. Best is trial 10 with value: 0.5187329434697855.

Best trial: 10. Best value: 0.518733:   4%|▍         | 9/200 [00:11<03:37,  1.14s/it]

[I 2025-11-10 18:00:01,755] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.18452107336538096, 'n_estimators': 1405, 'subsample': 0.7570749292188144, 'colsample_bytree': 0.5662660686194698, 'min_child_weight': 8, 'gamma': 2.330848485736273, 'reg_alpha': 5.384643855324219e-07, 'reg_lambda': 1.0087173576569234e-05, 'max_delta_step': 0}. Best is trial 10 with value: 0.5187329434697855.

Best trial: 10. Best value: 0.518733:   6%|▌         | 12/200 [00:11<02:03,  1.52it/s]

[I 2025-11-10 18:00:02,338] Trial 12 pruned.
[I 2025-11-10 18:00:02,468] Trial 11 pruned.

Best trial: 9. Best value: 0.530712:   6%|▋         | 13/200 [00:11<01:40,  1.86it/s]

[I 2025-11-10 18:00:02,640] Trial 9 finished with value: 0.5307115009746589 and parameters: {'max_depth': 3, 'learning_rate': 0.011721385622149938, 'n_estimators': 1391, 'subsample': 0.7596677917956023, 'colsample_bytree': 0.876676684093882, 'min_child_weight': 4, 'gamma': 3.87397914970195, 'reg_alpha': 8.239053903548079e-08, 'reg_lambda': 2.811034075179593e-07, 'max_delta_step': 10}. Best is trial 9 with value: 0.5307115009746589.
[I 2025-11-10 18:00:02,735] Trial 13 pruned.

Best trial: 9. Best value: 0.530712:   8%|▊         | 15/200 [00:12<01:10,  2.61it/s]

[I 2025-11-10 18:00:02,965] Trial 15 pruned.

Best trial: 9. Best value: 0.530712:   8%|▊         | 16/200 [00:12<01:09,  2.66it/s]

[I 2025-11-10 18:00:03,314] Trial 14 pruned.

Best trial: 9. Best value: 0.530712:   8%|▊         | 17/200 [00:13<01:16,  2.38it/s]

[I 2025-11-10 18:00:03,874] Trial 17 pruned.

Best trial: 9. Best value: 0.530712:  10%|▉         | 19/200 [00:13<01:02,  2.90it/s]

[I 2025-11-10 18:00:04,292] Trial 18 pruned.
[I 2025-11-10 18:00:04,430] Trial 19 pruned.

Best trial: 9. Best value: 0.530712:  10%|█         | 20/200 [00:13<00:51,  3.50it/s]

[I 2025-11-10 18:00:04,565] Trial 16 pruned.

Best trial: 9. Best value: 0.530712:  10%|█         | 21/200 [00:14<00:54,  3.30it/s]

[I 2025-11-10 18:00:04,911] Trial 20 pruned.
[I 2025-11-10 18:00:05,092] Trial 21 pruned.

Best trial: 22. Best value: 0.533158:  12%|█▏        | 23/200 [00:17<02:53,  1.02it/s]

[I 2025-11-10 18:00:07,804] Trial 22 finished with value: 0.5331578947368422 and parameters: {'max_depth': 8, 'learning_rate': 0.12211451640112837, 'n_estimators': 772, 'subsample': 0.5854975713512577, 'colsample_bytree': 0.7934291503816193, 'min_child_weight': 4, 'gamma': 3.4332117216741924, 'reg_alpha': 0.0003005492505279723, 'reg_lambda': 2.6201634398654533e-06, 'max_delta_step': 6}. Best is trial 22 with value: 0.5331578947368422.
[I 2025-11-10 18:00:07,808] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03597484546102207, 'n_estimators': 654, 'subsample': 0.5935497739638054, 'colsample_bytree': 0.9310300130481899, 'min_child_weight': 6, 'gamma': 0.9261304508856987, 'reg_alpha': 1.2548885930980775, 'reg_lambda': 9.215032600299917, 'max_delta_step': 2}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  12%|█▎        | 25/200 [00:17<01:44,  1.67it/s]

[I 2025-11-10 18:00:08,081] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.039042375263113695, 'n_estimators': 666, 'subsample': 0.6315606034611996, 'colsample_bytree': 0.9313148016577779, 'min_child_weight': 6, 'gamma': 0.880584885992159, 'reg_alpha': 0.0006672794610348137, 'reg_lambda': 5.801815823003707, 'max_delta_step': 3}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  13%|█▎        | 26/200 [00:17<01:30,  1.92it/s]

[I 2025-11-10 18:00:08,368] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.12589576800771338, 'n_estimators': 861, 'subsample': 0.5473457632014989, 'colsample_bytree': 0.796622830530958, 'min_child_weight': 4, 'gamma': 3.537528290604441, 'reg_alpha': 0.000540469475064093, 'reg_lambda': 2.64850556181495e-06, 'max_delta_step': 7}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  14%|█▎        | 27/200 [00:18<01:26,  2.01it/s]

[I 2025-11-10 18:00:08,797] Trial 26 pruned.
[I 2025-11-10 18:00:08,825] Trial 27 pruned.

Best trial: 22. Best value: 0.533158:  14%|█▍        | 29/200 [00:18<00:56,  3.05it/s]

[I 2025-11-10 18:00:08,996] Trial 28 pruned.

Best trial: 22. Best value: 0.533158:  15%|█▌        | 30/200 [00:19<01:36,  1.76it/s]

[I 2025-11-10 18:00:10,354] Trial 30 pruned.

Best trial: 22. Best value: 0.533158:  16%|█▌        | 31/200 [00:20<01:31,  1.86it/s]

[I 2025-11-10 18:00:10,806] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.0831915056707512, 'n_estimators': 437, 'subsample': 0.8192195738729361, 'colsample_bytree': 0.824112847657484, 'min_child_weight': 5, 'gamma': 4.978964538258216, 'reg_alpha': 1.1131709416414268e-07, 'reg_lambda': 1.0345436105953767e-08, 'max_delta_step': 5}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  16%|█▌        | 32/200 [00:20<01:18,  2.15it/s]

[I 2025-11-10 18:00:11,062] Trial 32 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.0759176091223005, 'n_estimators': 451, 'subsample': 0.7047214840503567, 'colsample_bytree': 0.8274801649240362, 'min_child_weight': 5, 'gamma': 3.899217212655418, 'reg_alpha': 8.753151644778271e-08, 'reg_lambda': 1.197587586459877e-08, 'max_delta_step': 5}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  16%|█▋        | 33/200 [00:20<01:21,  2.05it/s]

[I 2025-11-10 18:00:11,610] Trial 35 pruned.

Best trial: 22. Best value: 0.533158:  17%|█▋        | 34/200 [00:21<01:34,  1.75it/s]

[I 2025-11-10 18:00:12,392] Trial 33 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07230946651055009, 'n_estimators': 448, 'subsample': 0.8167486625192426, 'colsample_bytree': 0.7387873326578924, 'min_child_weight': 5, 'gamma': 3.8261982753341894, 'reg_alpha': 1.5578486581096708e-07, 'reg_lambda': 0.0021822178540582666, 'max_delta_step': 5}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  18%|█▊        | 35/200 [00:21<01:17,  2.12it/s]

[I 2025-11-10 18:00:12,618] Trial 29 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.27460629654446317, 'n_estimators': 915, 'subsample': 0.5099957771982311, 'colsample_bytree': 0.9132350884080229, 'min_child_weight': 5, 'gamma': 2.8787815532995173, 'reg_alpha': 9.215252962353302e-08, 'reg_lambda': 1.0233018673089536e-08, 'max_delta_step': 9}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  18%|█▊        | 36/200 [00:22<01:43,  1.58it/s]

[I 2025-11-10 18:00:13,644] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.04627722394343462, 'n_estimators': 219, 'subsample': 0.611143662186117, 'colsample_bytree': 0.6984412222263917, 'min_child_weight': 7, 'gamma': 1.8159345594918115, 'reg_alpha': 4.426671613539263e-06, 'reg_lambda': 1.774981080508272, 'max_delta_step': 4}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  18%|█▊        | 37/200 [00:23<01:41,  1.61it/s]

[I 2025-11-10 18:00:14,239] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.015981268622575987, 'n_estimators': 723, 'subsample': 0.6218905926371209, 'colsample_bytree': 0.8975005789445337, 'min_child_weight': 7, 'gamma': 1.5053473407336786, 'reg_alpha': 0.0025144018435497052, 'reg_lambda': 0.9460400939167302, 'max_delta_step': 4}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  19%|█▉        | 38/200 [00:24<01:48,  1.49it/s]

[I 2025-11-10 18:00:15,006] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.037297220309875936, 'n_estimators': 738, 'subsample': 0.617580965965867, 'colsample_bytree': 0.908152643175584, 'min_child_weight': 7, 'gamma': 1.7827087993564426, 'reg_alpha': 0.08924591305035207, 'reg_lambda': 0.85783978559898, 'max_delta_step': 4}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  20%|█▉        | 39/200 [00:25<02:36,  1.03it/s]

[I 2025-11-10 18:00:16,713] Trial 41 pruned.

Best trial: 22. Best value: 0.533158:  20%|██        | 40/200 [00:26<02:11,  1.21it/s]

[I 2025-11-10 18:00:17,193] Trial 37 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.04303646182138801, 'n_estimators': 758, 'subsample': 0.6131286086702227, 'colsample_bytree': 0.9033190166248181, 'min_child_weight': 7, 'gamma': 1.7024354295222357, 'reg_alpha': 3.772154872359478e-06, 'reg_lambda': 1.2368993116504596, 'max_delta_step': 4}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  20%|██        | 41/200 [00:27<02:23,  1.11it/s]

[I 2025-11-10 18:00:18,269] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1533420659299675, 'n_estimators': 735, 'subsample': 0.6582858409462501, 'colsample_bytree': 0.9564005264567708, 'min_child_weight': 7, 'gamma': 2.6865054208338788, 'reg_alpha': 0.11538767238727086, 'reg_lambda': 0.6173149828319391, 'max_delta_step': 2}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  21%|██        | 42/200 [00:28<02:09,  1.22it/s]

[I 2025-11-10 18:00:18,906] Trial 40 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.14699686952589822, 'n_estimators': 742, 'subsample': 0.6725887694995124, 'colsample_bytree': 0.9522600197111659, 'min_child_weight': 6, 'gamma': 1.89487059393969, 'reg_alpha': 0.20039953633346938, 'reg_lambda': 0.01190289906784862, 'max_delta_step': 2}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  22%|██▏       | 43/200 [00:29<02:12,  1.18it/s]

[I 2025-11-10 18:00:19,803] Trial 43 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.03077274888741153, 'n_estimators': 590, 'subsample': 0.731443369462839, 'colsample_bytree': 0.7738158032104299, 'min_child_weight': 8, 'gamma': 2.6577414359658382, 'reg_alpha': 8.596995885121338, 'reg_lambda': 0.010611605956922699, 'max_delta_step': 6}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  22%|██▏       | 44/200 [00:30<02:46,  1.07s/it]

[I 2025-11-10 18:00:21,405] Trial 42 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.20267612979896982, 'n_estimators': 1044, 'subsample': 0.5794015633732709, 'colsample_bytree': 0.9582510003676172, 'min_child_weight': 10, 'gamma': 2.5763708650674353, 'reg_alpha': 1.5776850995982934, 'reg_lambda': 0.008359676054217976, 'max_delta_step': 7}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  22%|██▎       | 45/200 [00:31<02:55,  1.13s/it]

[I 2025-11-10 18:00:22,675] Trial 47 pruned.

Best trial: 22. Best value: 0.533158:  24%|██▎       | 47/200 [00:33<02:06,  1.21it/s]

[I 2025-11-10 18:00:23,799] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.027297774169167118, 'n_estimators': 1314, 'subsample': 0.6865305232743879, 'colsample_bytree': 0.703502921957302, 'min_child_weight': 6, 'gamma': 1.1412186760730694, 'reg_alpha': 4.5249715777237625e-05, 'reg_lambda': 0.009040489674250205, 'max_delta_step': 3}. Best is trial 22 with value: 0.5331578947368422.
[I 2025-11-10 18:00:23,913] Trial 48 pruned.

Best trial: 22. Best value: 0.533158:  24%|██▍       | 48/200 [00:34<02:18,  1.10it/s]

[I 2025-11-10 18:00:25,018] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.029317790345563914, 'n_estimators': 1454, 'subsample': 0.7355275906013227, 'colsample_bytree': 0.6964966652590031, 'min_child_weight': 10, 'gamma': 1.1973848313251862, 'reg_alpha': 7.394566105435856e-05, 'reg_lambda': 3.7512155046447086e-05, 'max_delta_step': 1}. Best is trial 22 with value: 0.5331578947368422.
[I 2025-11-10 18:00:25,064] Trial 49 pruned.

Best trial: 22. Best value: 0.533158:  25%|██▌       | 50/200 [00:34<01:25,  1.75it/s]

[I 2025-11-10 18:00:25,374] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05892496647347666, 'n_estimators': 1307, 'subsample': 0.7816988966785424, 'colsample_bytree': 0.75912632811827, 'min_child_weight': 10, 'gamma': 1.1654588415645946, 'reg_alpha': 2.8733776237127863e-05, 'reg_lambda': 3.574955140159136e-05, 'max_delta_step': 1}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  26%|██▌       | 52/200 [00:38<02:44,  1.11s/it]

[I 2025-11-10 18:00:29,526] Trial 52 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.10418354684368089, 'n_estimators': 1043, 'subsample': 0.5700668944025853, 'colsample_bytree': 0.8343179538894747, 'min_child_weight': 5, 'gamma': 0.6049263362371697, 'reg_alpha': 0.012046009663131012, 'reg_lambda': 0.2055769802169717, 'max_delta_step': 10}. Best is trial 22 with value: 0.5331578947368422.
[I 2025-11-10 18:00:29,655] Trial 53 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.1012135083757957, 'n_estimators': 1060, 'subsample': 0.5556983312411722, 'colsample_bytree': 0.5980649113366054, 'min_child_weight': 5, 'gamma': 2.3206379738521408, 'reg_alpha': 0.0069406071425366965, 'reg_lambda': 4.8620062858027734e-08, 'max_delta_step': 10}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  26%|██▋       | 53/200 [00:39<02:18,  1.06it/s]

[I 2025-11-10 18:00:30,150] Trial 50 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.10498147021328365, 'n_estimators': 1473, 'subsample': 0.7382558098671497, 'colsample_bytree': 0.7643319259224246, 'min_child_weight': 5, 'gamma': 2.378773289430671, 'reg_alpha': 0.015931038248214662, 'reg_lambda': 0.09715646841214255, 'max_delta_step': 1}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  27%|██▋       | 54/200 [00:39<01:49,  1.33it/s]

[I 2025-11-10 18:00:30,398] Trial 51 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.0912781386191879, 'n_estimators': 1226, 'subsample': 0.5577791448491884, 'colsample_bytree': 0.8547460794905468, 'min_child_weight': 5, 'gamma': 2.3533039905981803, 'reg_alpha': 1.8187302819917295e-05, 'reg_lambda': 0.07774963613951744, 'max_delta_step': 6}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  28%|██▊       | 55/200 [00:43<04:09,  1.72s/it]

[I 2025-11-10 18:00:34,538] Trial 55 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.015644763846868234, 'n_estimators': 1236, 'subsample': 0.6396995287686644, 'colsample_bytree': 0.6247412436513751, 'min_child_weight': 8, 'gamma': 1.5507069047489368, 'reg_alpha': 1.5400713190119962e-05, 'reg_lambda': 0.0010437084647710166, 'max_delta_step': 0}. Best is trial 22 with value: 0.5331578947368422.
[I 2025-11-10 18:00:34,577] Trial 54 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.014244659301359278, 'n_estimators': 1217, 'subsample': 0.6424884541445623, 'colsample_bytree': 0.6155334746181217, 'min_child_weight': 6, 'gamma': 2.320877899728478, 'reg_alpha': 1.4047133729406636e-05, 'reg_lambda': 7.21396483902887e-08, 'max_delta_step': 0}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  28%|██▊       | 57/200 [00:44<02:36,  1.09s/it]

[I 2025-11-10 18:00:35,189] Trial 56 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.015786041384872718, 'n_estimators': 1268, 'subsample': 0.6428068991316287, 'colsample_bytree': 0.5062460062579026, 'min_child_weight': 8, 'gamma': 4.6313015558131765, 'reg_alpha': 0.00015326133695153663, 'reg_lambda': 9.425682344801215e-08, 'max_delta_step': 0}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  29%|██▉       | 58/200 [00:45<02:17,  1.03it/s]

[I 2025-11-10 18:00:35,774] Trial 59 pruned.

Best trial: 22. Best value: 0.533158:  30%|██▉       | 59/200 [00:45<01:52,  1.25it/s]

[I 2025-11-10 18:00:36,077] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.014846523677389372, 'n_estimators': 1420, 'subsample': 0.6478685157312142, 'colsample_bytree': 0.5109941162403921, 'min_child_weight': 8, 'gamma': 4.543024368482769, 'reg_alpha': 1.0000217918523212e-05, 'reg_lambda': 9.805329776254513e-07, 'max_delta_step': 0}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  30%|███       | 60/200 [00:45<01:40,  1.39it/s]

[I 2025-11-10 18:00:36,585] Trial 60 pruned.

Best trial: 22. Best value: 0.533158:  30%|███       | 61/200 [00:46<01:22,  1.69it/s]

[I 2025-11-10 18:00:36,850] Trial 62 pruned.
[I 2025-11-10 18:00:36,887] Trial 61 pruned.

Best trial: 22. Best value: 0.533158:  32%|███▏      | 63/200 [00:46<01:02,  2.19it/s]

[I 2025-11-10 18:00:37,422] Trial 63 pruned.

Best trial: 22. Best value: 0.533158:  32%|███▏      | 64/200 [00:49<02:28,  1.09s/it]

[I 2025-11-10 18:00:40,510] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.2348579667385722, 'n_estimators': 842, 'subsample': 0.7650379111616736, 'colsample_bytree': 0.844503639961118, 'min_child_weight': 6, 'gamma': 2.8502167156757756, 'reg_alpha': 2.917101276556891, 'reg_lambda': 3.6871040231288177, 'max_delta_step': 6}. Best is trial 22 with value: 0.5331578947368422.
[I 2025-11-10 18:00:40,533] Trial 65 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2296838876189201, 'n_estimators': 835, 'subsample': 0.7674956836880558, 'colsample_bytree': 0.8723647037479914, 'min_child_weight': 6, 'gamma': 2.7790945349288965, 'reg_alpha': 0.00020616851946692998, 'reg_lambda': 4.387134191893941, 'max_delta_step': 8}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  33%|███▎      | 66/200 [00:50<01:34,  1.42it/s]

[I 2025-11-10 18:00:40,794] Trial 58 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.01324921698692114, 'n_estimators': 1377, 'subsample': 0.7601148698868203, 'colsample_bytree': 0.9940187982172627, 'min_child_weight': 6, 'gamma': 1.9553295633291, 'reg_alpha': 0.00016949111380599178, 'reg_lambda': 7.536286049560728e-08, 'max_delta_step': 0}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  34%|███▎      | 67/200 [00:50<01:22,  1.62it/s]

[I 2025-11-10 18:00:41,110] Trial 68 pruned.

Best trial: 22. Best value: 0.533158:  34%|███▍      | 68/200 [00:50<01:20,  1.64it/s]

[I 2025-11-10 18:00:41,702] Trial 66 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.21155959862973517, 'n_estimators': 978, 'subsample': 0.8149715919055116, 'colsample_bytree': 0.8532981980891058, 'min_child_weight': 6, 'gamma': 3.744621744196788, 'reg_alpha': 3.107387682699682, 'reg_lambda': 4.623888695463402, 'max_delta_step': 6}. Best is trial 22 with value: 0.5331578947368422.
[I 2025-11-10 18:00:41,721] Trial 69 pruned.

Best trial: 22. Best value: 0.533158:  35%|███▌      | 70/200 [00:53<01:58,  1.10it/s]

[I 2025-11-10 18:00:44,393] Trial 72 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.02121145242671372, 'n_estimators': 609, 'subsample': 0.6858143045577214, 'colsample_bytree': 0.8174842736137707, 'min_child_weight': 7, 'gamma': 3.987421549840761, 'reg_alpha': 0.7419136743954147, 'reg_lambda': 0.0038445602872098856, 'max_delta_step': 8}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  36%|███▌      | 71/200 [00:54<01:41,  1.27it/s]

[I 2025-11-10 18:00:44,761] Trial 71 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1711870772055512, 'n_estimators': 683, 'subsample': 0.6662854038168301, 'colsample_bytree': 0.8935331364077981, 'min_child_weight': 7, 'gamma': 1.6770343409430224, 'reg_alpha': 0.0009192644784848221, 'reg_lambda': 3.3192577666441954e-07, 'max_delta_step': 9}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  36%|███▌      | 72/200 [00:54<01:22,  1.54it/s]

[I 2025-11-10 18:00:44,974] Trial 67 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.16974893842848898, 'n_estimators': 977, 'subsample': 0.7997621658016556, 'colsample_bytree': 0.868038983719505, 'min_child_weight': 6, 'gamma': 3.63775383204984, 'reg_alpha': 0.5416743591903628, 'reg_lambda': 9.927245307423343e-06, 'max_delta_step': 8}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  36%|███▋      | 73/200 [00:54<01:07,  1.89it/s]

[I 2025-11-10 18:00:45,168] Trial 73 pruned.

Best trial: 22. Best value: 0.533158:  37%|███▋      | 74/200 [00:54<00:56,  2.24it/s]

[I 2025-11-10 18:00:45,389] Trial 70 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.18695958896582088, 'n_estimators': 947, 'subsample': 0.6820433412982865, 'colsample_bytree': 0.8907683050729496, 'min_child_weight': 7, 'gamma': 3.646818080948275, 'reg_alpha': 0.00144575054381008, 'reg_lambda': 3.683482174826502e-07, 'max_delta_step': 8}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  38%|███▊      | 75/200 [00:55<01:03,  1.96it/s]

[I 2025-11-10 18:00:46,059] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.12571337494622312, 'n_estimators': 200, 'subsample': 0.592782531710266, 'colsample_bytree': 0.7899822237910367, 'min_child_weight': 8, 'gamma': 2.968484165797911, 'reg_alpha': 7.6212341893350075, 'reg_lambda': 0.28098619579040035, 'max_delta_step': 10}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  38%|███▊      | 77/200 [00:55<00:47,  2.58it/s]

[I 2025-11-10 18:00:46,521] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.12122040597424188, 'n_estimators': 345, 'subsample': 0.791804514381087, 'colsample_bytree': 0.747912875308241, 'min_child_weight': 9, 'gamma': 3.473327631146451, 'reg_alpha': 9.579262499820294, 'reg_lambda': 2.27315321976558, 'max_delta_step': 2}. Best is trial 22 with value: 0.5331578947368422.
[I 2025-11-10 18:00:46,645] Trial 76 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.11837905335922758, 'n_estimators': 286, 'subsample': 0.8389214195006209, 'colsample_bytree': 0.7437352734851513, 'min_child_weight': 9, 'gamma': 3.0121864030828753, 'reg_alpha': 4.1931316502049425, 'reg_lambda': 0.5165226472384062, 'max_delta_step': 2}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  39%|███▉      | 78/200 [00:56<00:54,  2.24it/s]

[I 2025-11-10 18:00:47,232] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.11380895636481103, 'n_estimators': 373, 'subsample': 0.826870364951857, 'colsample_bytree': 0.7393721277914295, 'min_child_weight': 9, 'gamma': 3.260253648728508, 'reg_alpha': 5.702036456199839, 'reg_lambda': 0.5001385404836457, 'max_delta_step': 2}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  40%|███▉      | 79/200 [00:56<00:55,  2.18it/s]

[I 2025-11-10 18:00:47,721] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06760746659588861, 'n_estimators': 333, 'subsample': 0.8386178355573142, 'colsample_bytree': 0.7490398583276904, 'min_child_weight': 5, 'gamma': 2.1120089889667772, 'reg_alpha': 4.2973326202620414e-08, 'reg_lambda': 2.023219960294795, 'max_delta_step': 2}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  40%|████      | 80/200 [00:57<00:46,  2.58it/s]

[I 2025-11-10 18:00:47,941] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.2590894398581368, 'n_estimators': 275, 'subsample': 0.8410788977588841, 'colsample_bytree': 0.7228011973990881, 'min_child_weight': 9, 'gamma': 3.2569257407984833, 'reg_alpha': 4.071764205889866, 'reg_lambda': 0.4626373147616465, 'max_delta_step': 4}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  40%|████      | 81/200 [00:57<00:55,  2.13it/s]

[I 2025-11-10 18:00:48,599] Trial 80 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.06494374879883781, 'n_estimators': 411, 'subsample': 0.8353939355469127, 'colsample_bytree': 0.8118414957537371, 'min_child_weight': 5, 'gamma': 2.1324215981509114, 'reg_alpha': 1.2592506173413203, 'reg_lambda': 0.032696206408509135, 'max_delta_step': 3}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  41%|████      | 82/200 [00:58<00:58,  2.01it/s]

[I 2025-11-10 18:00:49,167] Trial 81 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.017958243031701213, 'n_estimators': 409, 'subsample': 0.7234228473678233, 'colsample_bytree': 0.7197005158260316, 'min_child_weight': 5, 'gamma': 2.1049967761855166, 'reg_alpha': 1.5428973574679026, 'reg_lambda': 0.03779497884449279, 'max_delta_step': 3}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  42%|████▏     | 84/200 [00:59<00:50,  2.28it/s]

[I 2025-11-10 18:00:49,854] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.032893790669930846, 'n_estimators': 419, 'subsample': 0.8692121908602238, 'colsample_bytree': 0.8055220128442937, 'min_child_weight': 7, 'gamma': 1.8268764199326686, 'reg_alpha': 1.374223365355683e-08, 'reg_lambda': 0.02040542947997745, 'max_delta_step': 3}. Best is trial 22 with value: 0.5331578947368422.
[I 2025-11-10 18:00:50,021] Trial 82 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01787429197322626, 'n_estimators': 496, 'subsample': 0.7241589312498322, 'colsample_bytree': 0.8036213630329704, 'min_child_weight': 7, 'gamma': 4.140232002235829, 'reg_alpha': 1.1100266724152932e-08, 'reg_lambda': 0.02655033810676296, 'max_delta_step': 4}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  42%|████▎     | 85/200 [01:00<01:23,  1.38it/s]

[I 2025-11-10 18:00:51,407] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03451339521586011, 'n_estimators': 613, 'subsample': 0.5429414678919775, 'colsample_bytree': 0.9456794839104544, 'min_child_weight': 8, 'gamma': 1.3076691807775074, 'reg_alpha': 0.20444359719294544, 'reg_lambda': 0.0012317774660204927, 'max_delta_step': 10}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  43%|████▎     | 86/200 [01:01<01:23,  1.37it/s]

[I 2025-11-10 18:00:52,163] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08112997219335201, 'n_estimators': 485, 'subsample': 0.7464827121357579, 'colsample_bytree': 0.9783128681821487, 'min_child_weight': 8, 'gamma': 1.3438003422156342, 'reg_alpha': 0.003919751083816509, 'reg_lambda': 9.278981030212337, 'max_delta_step': 10}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  44%|████▎     | 87/200 [01:01<01:14,  1.52it/s]

[I 2025-11-10 18:00:52,647] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07703456366708906, 'n_estimators': 767, 'subsample': 0.5438188538889033, 'colsample_bytree': 0.6832509885042581, 'min_child_weight': 7, 'gamma': 1.3572715976820218, 'reg_alpha': 0.17770395623941393, 'reg_lambda': 1.938488814805815e-06, 'max_delta_step': 10}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  44%|████▍     | 88/200 [01:02<01:01,  1.83it/s]

[I 2025-11-10 18:00:52,933] Trial 89 pruned.

Best trial: 22. Best value: 0.533158:  45%|████▌     | 90/200 [01:02<00:49,  2.24it/s]

[I 2025-11-10 18:00:53,573] Trial 87 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08504169166268132, 'n_estimators': 767, 'subsample': 0.744071936448075, 'colsample_bytree': 0.9444295326396079, 'min_child_weight': 8, 'gamma': 1.37730716819912, 'reg_alpha': 0.143918791282318, 'reg_lambda': 0.0010088154443558728, 'max_delta_step': 10}. Best is trial 22 with value: 0.5331578947368422.
[I 2025-11-10 18:00:53,721] Trial 91 pruned.

Best trial: 22. Best value: 0.533158:  45%|████▌     | 90/200 [01:03<00:49,  2.24it/s]

[I 2025-11-10 18:00:53,749] Trial 90 pruned.

Best trial: 22. Best value: 0.533158:  46%|████▌     | 92/200 [01:04<00:52,  2.04it/s]

[I 2025-11-10 18:00:54,804] Trial 93 pruned.

Best trial: 22. Best value: 0.533158:  46%|████▋     | 93/200 [01:04<00:48,  2.22it/s]

[I 2025-11-10 18:00:55,137] Trial 88 finished with value: 0.5178460038986354 and parameters: {'max_depth': 4, 'learning_rate': 0.08397063509147577, 'n_estimators': 780, 'subsample': 0.6274420134405313, 'colsample_bytree': 0.9725330293056108, 'min_child_weight': 4, 'gamma': 2.4751119570585782, 'reg_alpha': 0.004779723629950885, 'reg_lambda': 1.9183868438967736e-06, 'max_delta_step': 7}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  47%|████▋     | 94/200 [01:05<01:09,  1.53it/s]

[I 2025-11-10 18:00:56,366] Trial 96 pruned.

Best trial: 22. Best value: 0.533158:  48%|████▊     | 95/200 [01:08<02:17,  1.31s/it]

[I 2025-11-10 18:00:59,418] Trial 97 finished with value: 0.5242690058479533 and parameters: {'max_depth': 3, 'learning_rate': 0.27901860348798724, 'n_estimators': 710, 'subsample': 0.5812651550876542, 'colsample_bytree': 0.9592078872157944, 'min_child_weight': 4, 'gamma': 2.7335302809688766, 'reg_alpha': 0.0747817137657197, 'reg_lambda': 4.5694101697888156e-07, 'max_delta_step': 1}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  48%|████▊     | 96/200 [01:09<01:51,  1.07s/it]

[I 2025-11-10 18:00:59,892] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.01102480705281983, 'n_estimators': 1415, 'subsample': 0.7790135954869442, 'colsample_bytree': 0.9690301562358754, 'min_child_weight': 9, 'gamma': 2.480181769031746, 'reg_alpha': 7.32940781510438e-07, 'reg_lambda': 7.543408398010061e-05, 'max_delta_step': 0}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  48%|████▊     | 97/200 [01:09<01:27,  1.18it/s]

[I 2025-11-10 18:01:00,171] Trial 92 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.026226609154041004, 'n_estimators': 1497, 'subsample': 0.5316547965146508, 'colsample_bytree': 0.9706177940961097, 'min_child_weight': 4, 'gamma': 0.9311041061679874, 'reg_alpha': 3.912563139334611e-05, 'reg_lambda': 2.070171604377294e-08, 'max_delta_step': 9}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 22. Best value: 0.533158:  49%|████▉     | 98/200 [01:09<01:13,  1.38it/s]

[I 2025-11-10 18:01:00,597] Trial 99 pruned.

Best trial: 22. Best value: 0.533158:  50%|████▉     | 99/200 [01:10<01:00,  1.66it/s]

[I 2025-11-10 18:01:00,900] Trial 100 pruned.
[I 2025-11-10 18:01:00,952] Trial 95 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.21565014424318227, 'n_estimators': 1410, 'subsample': 0.7772821585223478, 'colsample_bytree': 0.9694677483170232, 'min_child_weight': 9, 'gamma': 2.6715348730556587, 'reg_alpha': 5.3616822648066733e-08, 'reg_lambda': 0.00015358120338720778, 'max_delta_step': 0}. Best is trial 22 with value: 0.5331578947368422.

Best trial: 98. Best value: 0.555029:  50%|█████     | 101/200 [01:11<01:12,  1.36it/s]

[I 2025-11-10 18:01:02,691] Trial 98 finished with value: 0.5550292397660819 and parameters: {'max_depth': 3, 'learning_rate': 0.2716192557988118, 'n_estimators': 708, 'subsample': 0.6255192300134413, 'colsample_bytree': 0.9328085139777262, 'min_child_weight': 4, 'gamma': 2.7456677751058245, 'reg_alpha': 0.8073745563286824, 'reg_lambda': 5.046050342529329e-07, 'max_delta_step': 0}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  51%|█████     | 102/200 [01:12<01:13,  1.33it/s]

[I 2025-11-10 18:01:03,501] Trial 101 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.11013583464733635, 'n_estimators': 644, 'subsample': 0.6012178247953227, 'colsample_bytree': 0.7777926639441077, 'min_child_weight': 5, 'gamma': 2.7668162589169842, 'reg_alpha': 0.26252601148701626, 'reg_lambda': 5.507209860079612e-06, 'max_delta_step': 1}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  52%|█████▏    | 103/200 [01:13<01:02,  1.56it/s]

[I 2025-11-10 18:01:03,815] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1079642695813815, 'n_estimators': 633, 'subsample': 0.6231074143139828, 'colsample_bytree': 0.9316751804952799, 'min_child_weight': 5, 'gamma': 2.248922139898603, 'reg_alpha': 0.2979241962981684, 'reg_lambda': 1.504899001590082, 'max_delta_step': 1}. Best is trial 98 with value: 0.5550292397660819.
[I 2025-11-10 18:01:03,911] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.260511270186942, 'n_estimators': 639, 'subsample': 0.625137045978067, 'colsample_bytree': 0.9366260198477934, 'min_child_weight': 5, 'gamma': 2.253020365267898, 'reg_alpha': 2.3239105939252744, 'reg_lambda': 5.096286039314646e-06, 'max_delta_step': 1}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  53%|█████▎    | 106/200 [01:14<00:41,  2.27it/s]

[I 2025-11-10 18:01:04,621] Trial 106 pruned.
[I 2025-11-10 18:01:04,740] Trial 107 pruned.

Best trial: 98. Best value: 0.555029:  54%|█████▎    | 107/200 [01:14<00:47,  1.96it/s]

[I 2025-11-10 18:01:05,456] Trial 108 pruned.

Best trial: 98. Best value: 0.555029:  54%|█████▍    | 108/200 [01:14<00:40,  2.30it/s]

[I 2025-11-10 18:01:05,677] Trial 104 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.25919664028609085, 'n_estimators': 628, 'subsample': 0.6011952183395252, 'colsample_bytree': 0.9328696340326362, 'min_child_weight': 5, 'gamma': 2.215839750848089, 'reg_alpha': 0.41818062099165715, 'reg_lambda': 1.4449672433445842e-06, 'max_delta_step': 1}. Best is trial 98 with value: 0.5550292397660819.
[I 2025-11-10 18:01:05,685] Trial 109 pruned.

Best trial: 98. Best value: 0.555029:  55%|█████▌    | 110/200 [01:15<00:33,  2.66it/s]

[I 2025-11-10 18:01:06,279] Trial 110 pruned.

Best trial: 98. Best value: 0.555029:  56%|█████▌    | 111/200 [01:15<00:29,  2.97it/s]

[I 2025-11-10 18:01:06,486] Trial 112 pruned.

Best trial: 98. Best value: 0.555029:  56%|█████▌    | 112/200 [01:16<00:29,  2.99it/s]

[I 2025-11-10 18:01:06,810] Trial 105 finished with value: 0.5263742690058479 and parameters: {'max_depth': 5, 'learning_rate': 0.27250352801706057, 'n_estimators': 635, 'subsample': 0.619290488497366, 'colsample_bytree': 0.8827402091503341, 'min_child_weight': 4, 'gamma': 2.230492873122138, 'reg_alpha': 0.3932032741682023, 'reg_lambda': 1.3525338838421038e-06, 'max_delta_step': 1}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  56%|█████▋    | 113/200 [01:18<01:13,  1.18it/s]

[I 2025-11-10 18:01:09,084] Trial 111 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.22741365772118047, 'n_estimators': 736, 'subsample': 0.6506882498192779, 'colsample_bytree': 0.951695042246858, 'min_child_weight': 6, 'gamma': 3.487751169964661, 'reg_alpha': 0.0006162568884544219, 'reg_lambda': 4.050439975967684e-08, 'max_delta_step': 0}. Best is trial 98 with value: 0.5550292397660819.
[I 2025-11-10 18:01:09,123] Trial 114 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04060689715222751, 'n_estimators': 578, 'subsample': 0.6517098112017375, 'colsample_bytree': 0.9585170739560381, 'min_child_weight': 6, 'gamma': 1.7633977664871485, 'reg_alpha': 0.004695455194390467, 'reg_lambda': 3.0089808761665644, 'max_delta_step': 7}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  57%|█████▊    | 115/200 [01:20<01:28,  1.04s/it]

[I 2025-11-10 18:01:11,668] Trial 116 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.29582519251628264, 'n_estimators': 580, 'subsample': 0.5629560668953177, 'colsample_bytree': 0.8365229202991152, 'min_child_weight': 4, 'gamma': 1.7686169354413894, 'reg_alpha': 0.0001110442250454555, 'reg_lambda': 3.1489218419225734e-06, 'max_delta_step': 1}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  58%|█████▊    | 116/200 [01:21<01:16,  1.09it/s]

[I 2025-11-10 18:01:12,178] Trial 117 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.0908539349539431, 'n_estimators': 671, 'subsample': 0.5660368873932691, 'colsample_bytree': 0.8248415624890962, 'min_child_weight': 4, 'gamma': 3.053893089925919, 'reg_alpha': 0.05805767396923895, 'reg_lambda': 1.2035671392823221e-07, 'max_delta_step': 1}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  58%|█████▊    | 117/200 [01:22<01:11,  1.16it/s]

[I 2025-11-10 18:01:12,877] Trial 113 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.20182608336452285, 'n_estimators': 1451, 'subsample': 0.5886665247493135, 'colsample_bytree': 0.9576871554836636, 'min_child_weight': 6, 'gamma': 1.9261330412601794, 'reg_alpha': 0.0063585549052832795, 'reg_lambda': 0.0004999599198472006, 'max_delta_step': 6}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  59%|█████▉    | 118/200 [01:22<01:01,  1.34it/s]

[I 2025-11-10 18:01:13,305] Trial 115 finished with value: 0.49558479532163735 and parameters: {'max_depth': 4, 'learning_rate': 0.29639061614651224, 'n_estimators': 1447, 'subsample': 0.7915244321992403, 'colsample_bytree': 0.8532859903803297, 'min_child_weight': 4, 'gamma': 1.8391132471758151, 'reg_alpha': 0.0001364754137628893, 'reg_lambda': 1.1257226569467062e-07, 'max_delta_step': 1}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  60%|█████▉    | 119/200 [01:23<00:55,  1.47it/s]

[I 2025-11-10 18:01:13,820] Trial 120 pruned.

Best trial: 98. Best value: 0.555029:  60%|██████    | 120/200 [01:23<00:57,  1.40it/s]

[I 2025-11-10 18:01:14,617] Trial 118 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.24330500498273863, 'n_estimators': 663, 'subsample': 0.5847851673151012, 'colsample_bytree': 0.8794843957488019, 'min_child_weight': 4, 'gamma': 3.0533641140771204, 'reg_alpha': 7.325901969574034e-06, 'reg_lambda': 6.818483608758419, 'max_delta_step': 1}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  60%|██████    | 121/200 [01:24<00:57,  1.36it/s]

[I 2025-11-10 18:01:15,390] Trial 123 pruned.

Best trial: 98. Best value: 0.555029:  61%|██████    | 122/200 [01:26<01:22,  1.06s/it]

[I 2025-11-10 18:01:17,237] Trial 122 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.24892971079282933, 'n_estimators': 799, 'subsample': 0.695302956173626, 'colsample_bytree': 0.8799892671040958, 'min_child_weight': 5, 'gamma': 2.850537615067769, 'reg_alpha': 0.44889777608065295, 'reg_lambda': 5.183851960314642e-07, 'max_delta_step': 4}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  62%|██████▏   | 123/200 [01:26<01:08,  1.13it/s]

[I 2025-11-10 18:01:17,722] Trial 119 finished with value: 0.5209941520467837 and parameters: {'max_depth': 5, 'learning_rate': 0.24426065024529384, 'n_estimators': 1270, 'subsample': 0.5878348305495927, 'colsample_bytree': 0.8771399089035459, 'min_child_weight': 4, 'gamma': 2.8031902479029855, 'reg_alpha': 0.0018627578473063375, 'reg_lambda': 4.929889207797818e-07, 'max_delta_step': 4}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  62%|██████▏   | 124/200 [01:27<01:03,  1.20it/s]

[I 2025-11-10 18:01:18,435] Trial 121 finished with value: 0.5484600389863548 and parameters: {'max_depth': 5, 'learning_rate': 0.1602247768815026, 'n_estimators': 787, 'subsample': 0.6391550731620833, 'colsample_bytree': 0.8807302971524028, 'min_child_weight': 1, 'gamma': 2.8098253990137363, 'reg_alpha': 1.0757230368608013, 'reg_lambda': 4.955563133111129e-07, 'max_delta_step': 4}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  62%|██████▎   | 125/200 [01:28<00:54,  1.38it/s]

[I 2025-11-10 18:01:18,890] Trial 126 pruned.

Best trial: 98. Best value: 0.555029:  63%|██████▎   | 126/200 [01:28<00:49,  1.48it/s]

[I 2025-11-10 18:01:19,452] Trial 128 pruned.

Best trial: 98. Best value: 0.555029:  64%|██████▎   | 127/200 [01:29<00:57,  1.28it/s]

[I 2025-11-10 18:01:20,487] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01728426729944047, 'n_estimators': 1186, 'subsample': 0.6976874823119691, 'colsample_bytree': 0.91268851443371, 'min_child_weight': 5, 'gamma': 1.6310151358475156, 'reg_alpha': 0.015167701791644455, 'reg_lambda': 8.617277830701281e-07, 'max_delta_step': 8}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  64%|██████▍   | 128/200 [01:30<00:48,  1.48it/s]

[I 2025-11-10 18:01:20,910] Trial 129 pruned.

Best trial: 98. Best value: 0.555029:  64%|██████▍   | 129/200 [01:30<00:50,  1.41it/s]

[I 2025-11-10 18:01:21,707] Trial 130 pruned.

Best trial: 98. Best value: 0.555029:  65%|██████▌   | 130/200 [01:31<00:48,  1.43it/s]

[I 2025-11-10 18:01:22,373] Trial 127 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.20933247019297127, 'n_estimators': 838, 'subsample': 0.5726736985733974, 'colsample_bytree': 0.9112569410785747, 'min_child_weight': 4, 'gamma': 3.8185965569085134, 'reg_alpha': 1.1673722510269806, 'reg_lambda': 9.56898700991718e-07, 'max_delta_step': 4}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  66%|██████▌   | 132/200 [01:32<00:31,  2.19it/s]

[I 2025-11-10 18:01:22,706] Trial 132 pruned.
[I 2025-11-10 18:01:22,858] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07088428560929626, 'n_estimators': 1289, 'subsample': 0.5156294731555664, 'colsample_bytree': 0.7555318621282737, 'min_child_weight': 10, 'gamma': 1.531957970522923, 'reg_alpha': 0.012057591855098835, 'reg_lambda': 8.58018737876954e-07, 'max_delta_step': 8}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  66%|██████▋   | 133/200 [01:32<00:38,  1.75it/s]

[I 2025-11-10 18:01:23,692] Trial 133 pruned.

Best trial: 98. Best value: 0.555029:  67%|██████▋   | 134/200 [01:33<00:40,  1.64it/s]

[I 2025-11-10 18:01:24,393] Trial 131 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.15337217254781849, 'n_estimators': 757, 'subsample': 0.5730179287378566, 'colsample_bytree': 0.8743503903003107, 'min_child_weight': 4, 'gamma': 2.4081588001562317, 'reg_alpha': 1.2168099624803688, 'reg_lambda': 2.894554973968231e-07, 'max_delta_step': 3}. Best is trial 98 with value: 0.5550292397660819.
[I 2025-11-10 18:01:24,409] Trial 136 pruned.

Best trial: 98. Best value: 0.555029:  68%|██████▊   | 136/200 [01:35<00:46,  1.38it/s]

[I 2025-11-10 18:01:26,102] Trial 134 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.012205712248317945, 'n_estimators': 748, 'subsample': 0.6144594015012326, 'colsample_bytree': 0.7905093166735377, 'min_child_weight': 4, 'gamma': 2.782504151243149, 'reg_alpha': 5.861125297312134, 'reg_lambda': 8.173892168342275e-06, 'max_delta_step': 5}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  68%|██████▊   | 137/200 [01:35<00:38,  1.62it/s]

[I 2025-11-10 18:01:26,399] Trial 135 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.24491051065594352, 'n_estimators': 753, 'subsample': 0.6149390119943436, 'colsample_bytree': 0.8504628199502362, 'min_child_weight': 4, 'gamma': 2.773264830268267, 'reg_alpha': 4.995097624540696, 'reg_lambda': 7.173330364074157e-08, 'max_delta_step': 5}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  69%|██████▉   | 138/200 [01:37<00:52,  1.19it/s]

[I 2025-11-10 18:01:27,880] Trial 138 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.29828039288827407, 'n_estimators': 776, 'subsample': 0.7935030178683423, 'colsample_bytree': 0.5952953187154238, 'min_child_weight': 6, 'gamma': 3.1829632243203734, 'reg_alpha': 2.0084214634953166, 'reg_lambda': 0.8128465777575311, 'max_delta_step': 5}. Best is trial 98 with value: 0.5550292397660819.
[I 2025-11-10 18:01:27,898] Trial 137 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.2711489196949126, 'n_estimators': 754, 'subsample': 0.5969759232189005, 'colsample_bytree': 0.7883697854325072, 'min_child_weight': 6, 'gamma': 3.1991796562897368, 'reg_alpha': 2.212510009235505e-05, 'reg_lambda': 6.223862073024963e-08, 'max_delta_step': 5}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  70%|███████   | 140/200 [01:38<00:46,  1.28it/s]

[I 2025-11-10 18:01:29,281] Trial 142 pruned.

Best trial: 98. Best value: 0.555029:  70%|███████   | 141/200 [01:38<00:38,  1.53it/s]

[I 2025-11-10 18:01:29,516] Trial 139 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.02230077234973479, 'n_estimators': 716, 'subsample': 0.6813459136013975, 'colsample_bytree': 0.8440988892138663, 'min_child_weight': 6, 'gamma': 2.610861327346474, 'reg_alpha': 2.145185026886453e-05, 'reg_lambda': 0.0022620485500999825, 'max_delta_step': 2}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  71%|███████   | 142/200 [01:39<00:44,  1.29it/s]

[I 2025-11-10 18:01:30,645] Trial 140 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.13578844117521716, 'n_estimators': 914, 'subsample': 0.7928145571190865, 'colsample_bytree': 0.8190248749729971, 'min_child_weight': 5, 'gamma': 3.1800956643101315, 'reg_alpha': 2.8517689593953577, 'reg_lambda': 1.7113545540551774e-06, 'max_delta_step': 2}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  72%|███████▏  | 143/200 [01:42<01:13,  1.29s/it]

[I 2025-11-10 18:01:33,376] Trial 143 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10149089244240411, 'n_estimators': 926, 'subsample': 0.5537290057066875, 'colsample_bytree': 0.7718969354391846, 'min_child_weight': 5, 'gamma': 2.6090409378110295, 'reg_alpha': 5.466684895621928e-05, 'reg_lambda': 0.0018828043797420777, 'max_delta_step': 6}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  72%|███████▏  | 144/200 [01:42<00:56,  1.01s/it]

[I 2025-11-10 18:01:33,652] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.1691328883993087, 'n_estimators': 1333, 'subsample': 0.7127329991747458, 'colsample_bytree': 0.7306621355443996, 'min_child_weight': 5, 'gamma': 2.6317971747778497, 'reg_alpha': 2.102344769565232e-05, 'reg_lambda': 0.0062045445378409, 'max_delta_step': 2}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  72%|███████▎  | 145/200 [01:43<00:52,  1.04it/s]

[I 2025-11-10 18:01:34,486] Trial 144 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.10041043345793685, 'n_estimators': 1094, 'subsample': 0.5027522538367074, 'colsample_bytree': 0.9714029148403752, 'min_child_weight': 7, 'gamma': 2.1745991904839226, 'reg_alpha': 5.466091972277043e-05, 'reg_lambda': 0.005363568540662269, 'max_delta_step': 6}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  73%|███████▎  | 146/200 [01:44<00:45,  1.19it/s]

[I 2025-11-10 18:01:35,022] Trial 147 pruned.

Best trial: 98. Best value: 0.555029:  74%|███████▎  | 147/200 [01:44<00:34,  1.54it/s]

[I 2025-11-10 18:01:35,207] Trial 145 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01026265960761809, 'n_estimators': 1001, 'subsample': 0.7528370645979824, 'colsample_bytree': 0.9656525870722519, 'min_child_weight': 7, 'gamma': 2.1896034714979056, 'reg_alpha': 0.005075105920180111, 'reg_lambda': 1.370063047257383e-05, 'max_delta_step': 6}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  74%|███████▍  | 148/200 [01:45<00:33,  1.57it/s]

[I 2025-11-10 18:01:35,819] Trial 150 pruned.

Best trial: 98. Best value: 0.555029:  74%|███████▍  | 149/200 [01:45<00:34,  1.49it/s]

[I 2025-11-10 18:01:36,564] Trial 149 pruned.

Best trial: 98. Best value: 0.555029:  75%|███████▌  | 150/200 [01:48<01:06,  1.34s/it]

[I 2025-11-10 18:01:39,486] Trial 146 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.0196375035598276, 'n_estimators': 1362, 'subsample': 0.505246607199721, 'colsample_bytree': 0.9624809966059659, 'min_child_weight': 7, 'gamma': 2.1845601072181635, 'reg_alpha': 0.005886192125313951, 'reg_lambda': 1.1192477273451167, 'max_delta_step': 7}. Best is trial 98 with value: 0.5550292397660819.
[I 2025-11-10 18:01:39,501] Trial 152 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.020041771269817214, 'n_estimators': 669, 'subsample': 0.5429714378293926, 'colsample_bytree': 0.9383620028456632, 'min_child_weight': 8, 'gamma': 3.328706647526657, 'reg_alpha': 0.03318890429708038, 'reg_lambda': 1.1710246674166664, 'max_delta_step': 10}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  76%|███████▌  | 152/200 [01:49<00:48,  1.01s/it]

[I 2025-11-10 18:01:40,725] Trial 148 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.030188455541123548, 'n_estimators': 1397, 'subsample': 0.5309002367525509, 'colsample_bytree': 0.9447497988795224, 'min_child_weight': 8, 'gamma': 2.868847838822288, 'reg_alpha': 0.03378338733624364, 'reg_lambda': 3.7879524403045857e-06, 'max_delta_step': 10}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  76%|███████▋  | 153/200 [01:51<00:54,  1.16s/it]

[I 2025-11-10 18:01:42,341] Trial 151 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.027778676406771886, 'n_estimators': 1471, 'subsample': 0.5362407324391215, 'colsample_bytree': 0.8888218069091837, 'min_child_weight': 8, 'gamma': 3.307938439709668, 'reg_alpha': 0.020579171617283128, 'reg_lambda': 4.441277862134812e-06, 'max_delta_step': 9}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  77%|███████▋  | 154/200 [01:52<00:52,  1.14s/it]

[I 2025-11-10 18:01:43,441] Trial 153 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.048346132567205685, 'n_estimators': 829, 'subsample': 0.5415223318125318, 'colsample_bytree': 0.8863574321668278, 'min_child_weight': 4, 'gamma': 1.2211845579859897, 'reg_alpha': 0.0005162859611939925, 'reg_lambda': 4.0411601590826835e-06, 'max_delta_step': 0}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  78%|███████▊  | 155/200 [01:54<01:02,  1.38s/it]

[I 2025-11-10 18:01:45,473] Trial 154 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.08782417928003904, 'n_estimators': 1391, 'subsample': 0.7300167137385954, 'colsample_bytree': 0.5424095750463718, 'min_child_weight': 8, 'gamma': 2.8823482444418698, 'reg_alpha': 7.688667654918311e-08, 'reg_lambda': 3.3811909124222806e-06, 'max_delta_step': 0}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  78%|███████▊  | 156/200 [01:55<00:49,  1.13s/it]

[I 2025-11-10 18:01:45,950] Trial 156 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.18820082835649196, 'n_estimators': 824, 'subsample': 0.7305603297888789, 'colsample_bytree': 0.5720976027556581, 'min_child_weight': 9, 'gamma': 4.024700376652345, 'reg_alpha': 7.07273142681634e-08, 'reg_lambda': 6.177612191191598e-07, 'max_delta_step': 0}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  78%|███████▊  | 157/200 [01:56<00:46,  1.08s/it]

[I 2025-11-10 18:01:46,918] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.18849681437400867, 'n_estimators': 1444, 'subsample': 0.7489375744255005, 'colsample_bytree': 0.5612261514124863, 'min_child_weight': 9, 'gamma': 3.9992564042086864, 'reg_alpha': 6.014775730490809e-08, 'reg_lambda': 4.093898718445153e-06, 'max_delta_step': 0}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  79%|███████▉  | 158/200 [01:56<00:41,  1.01it/s]

[I 2025-11-10 18:01:47,677] Trial 160 pruned.

Best trial: 98. Best value: 0.555029:  80%|███████▉  | 159/200 [01:58<00:42,  1.04s/it]

[I 2025-11-10 18:01:48,839] Trial 161 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.08049341724800432, 'n_estimators': 245, 'subsample': 0.7732423300210702, 'colsample_bytree': 0.5842698008786233, 'min_child_weight': 5, 'gamma': 2.4697847078330515, 'reg_alpha': 3.5569825111929515e-08, 'reg_lambda': 1.560460793996625e-08, 'max_delta_step': 0}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  80%|████████  | 160/200 [01:58<00:39,  1.00it/s]

[I 2025-11-10 18:01:49,732] Trial 157 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1936655659690049, 'n_estimators': 1423, 'subsample': 0.7716017875441173, 'colsample_bytree': 0.5916909979634508, 'min_child_weight': 9, 'gamma': 2.4959792538653005, 'reg_alpha': 4.575666038239173e-08, 'reg_lambda': 3.396347090773573e-05, 'max_delta_step': 0}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  80%|████████  | 161/200 [02:00<00:42,  1.08s/it]

[I 2025-11-10 18:01:51,001] Trial 158 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1816365064509722, 'n_estimators': 1244, 'subsample': 0.7731046469662026, 'colsample_bytree': 0.5676178409465125, 'min_child_weight': 9, 'gamma': 3.9492969235703614, 'reg_alpha': 4.819307298106225e-08, 'reg_lambda': 1.2515539917744053e-06, 'max_delta_step': 0}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  82%|████████▏ | 163/200 [02:01<00:29,  1.25it/s]

[I 2025-11-10 18:01:52,108] Trial 159 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.25448933188576517, 'n_estimators': 1431, 'subsample': 0.7717368640975951, 'colsample_bytree': 0.5295000990619501, 'min_child_weight': 10, 'gamma': 2.29294682738658, 'reg_alpha': 4.214407738832153e-07, 'reg_lambda': 1.4995819295348577e-06, 'max_delta_step': 0}. Best is trial 98 with value: 0.5550292397660819.
[I 2025-11-10 18:01:52,245] Trial 162 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.03714681482246804, 'n_estimators': 707, 'subsample': 0.6398250713678733, 'colsample_bytree': 0.9764931918166857, 'min_child_weight': 10, 'gamma': 2.3388170962745294, 'reg_alpha': 5.264039309875393e-07, 'reg_lambda': 5.959467297586044, 'max_delta_step': 0}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  82%|████████▏ | 164/200 [02:03<00:41,  1.16s/it]

[I 2025-11-10 18:01:54,254] Trial 164 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.014781952818731311, 'n_estimators': 719, 'subsample': 0.9999230015707156, 'colsample_bytree': 0.6376815517525402, 'min_child_weight': 9, 'gamma': 2.2856179176713685, 'reg_alpha': 0.00025400975315202054, 'reg_lambda': 0.00015655455780410444, 'max_delta_step': 1}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  82%|████████▎ | 165/200 [02:04<00:40,  1.16s/it]

[I 2025-11-10 18:01:55,393] Trial 165 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.016457038815865098, 'n_estimators': 723, 'subsample': 0.7405365444854682, 'colsample_bytree': 0.8690050733894483, 'min_child_weight': 9, 'gamma': 1.6571260053767323, 'reg_alpha': 1.6907208256651182e-06, 'reg_lambda': 0.013913714766473882, 'max_delta_step': 1}. Best is trial 98 with value: 0.5550292397660819.
[I 2025-11-10 18:01:55,461] Trial 163 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.14317366348062435, 'n_estimators': 1247, 'subsample': 0.6341350331235097, 'colsample_bytree': 0.8721234934264391, 'min_child_weight': 6, 'gamma': 2.364283989522523, 'reg_alpha': 1.8497287395357594e-06, 'reg_lambda': 1.2938693159156142e-06, 'max_delta_step': 4}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  84%|████████▎ | 167/200 [02:04<00:22,  1.45it/s]

[I 2025-11-10 18:01:55,688] Trial 167 pruned.

Best trial: 98. Best value: 0.555029:  84%|████████▍ | 169/200 [02:06<00:18,  1.65it/s]

[I 2025-11-10 18:01:56,747] Trial 169 pruned.
[I 2025-11-10 18:01:56,852] Trial 168 pruned.

Best trial: 98. Best value: 0.555029:  85%|████████▌ | 170/200 [02:06<00:14,  2.01it/s]

[I 2025-11-10 18:01:57,061] Trial 170 pruned.

Best trial: 98. Best value: 0.555029:  86%|████████▌ | 172/200 [02:07<00:13,  2.08it/s]

[I 2025-11-10 18:01:58,006] Trial 166 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02534172332757085, 'n_estimators': 1312, 'subsample': 0.7414413127492888, 'colsample_bytree': 0.6162440613583223, 'min_child_weight': 9, 'gamma': 2.077886549802141, 'reg_alpha': 8.996741248308451e-05, 'reg_lambda': 0.00023407799048704196, 'max_delta_step': 1}. Best is trial 98 with value: 0.5550292397660819.
[I 2025-11-10 18:01:58,126] Trial 171 pruned.

Best trial: 98. Best value: 0.555029:  86%|████████▋ | 173/200 [02:09<00:22,  1.19it/s]

[I 2025-11-10 18:01:59,856] Trial 175 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.12761483625760078, 'n_estimators': 372, 'subsample': 0.5534784689399714, 'colsample_bytree': 0.7095632425241338, 'min_child_weight': 4, 'gamma': 3.0088209987930066, 'reg_alpha': 0.0004034585446437212, 'reg_lambda': 2.43330781431607, 'max_delta_step': 8}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  87%|████████▋ | 174/200 [02:09<00:17,  1.46it/s]

[I 2025-11-10 18:02:00,170] Trial 173 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03247301547742895, 'n_estimators': 649, 'subsample': 0.7852489505271131, 'colsample_bytree': 0.8294612022229378, 'min_child_weight': 8, 'gamma': 4.15571767981797, 'reg_alpha': 2.2247515923286204e-08, 'reg_lambda': 2.973769082524291, 'max_delta_step': 10}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  88%|████████▊ | 175/200 [02:11<00:24,  1.01it/s]

[I 2025-11-10 18:02:01,875] Trial 174 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.12448551308161956, 'n_estimators': 859, 'subsample': 0.5539728741631875, 'colsample_bytree': 0.8269298732049736, 'min_child_weight': 4, 'gamma': 3.02797170639942, 'reg_alpha': 2.022035542598228e-08, 'reg_lambda': 5.060066223493675e-07, 'max_delta_step': 10}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  88%|████████▊ | 176/200 [02:11<00:22,  1.07it/s]

[I 2025-11-10 18:02:02,676] Trial 172 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.09476134846305603, 'n_estimators': 1313, 'subsample': 0.6872842263156764, 'colsample_bytree': 0.6157918751340744, 'min_child_weight': 7, 'gamma': 0.02984367939682553, 'reg_alpha': 1.8718885515282094e-08, 'reg_lambda': 0.32309055341803644, 'max_delta_step': 7}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  88%|████████▊ | 177/200 [02:13<00:22,  1.02it/s]

[I 2025-11-10 18:02:03,766] Trial 176 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.12356419761478052, 'n_estimators': 867, 'subsample': 0.5628813314320198, 'colsample_bytree': 0.7975964691928296, 'min_child_weight': 4, 'gamma': 3.50033222726405, 'reg_alpha': 0.3537038151916013, 'reg_lambda': 1.0435985807593776e-05, 'max_delta_step': 8}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  89%|████████▉ | 178/200 [02:13<00:16,  1.30it/s]

[I 2025-11-10 18:02:04,045] Trial 177 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.27755399148058246, 'n_estimators': 851, 'subsample': 0.6554442434785872, 'colsample_bytree': 0.8077297843338684, 'min_child_weight': 5, 'gamma': 0.1082764077699081, 'reg_alpha': 0.5257814269027838, 'reg_lambda': 2.1087932066965272e-06, 'max_delta_step': 7}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  90%|████████▉ | 179/200 [02:13<00:14,  1.41it/s]

[I 2025-11-10 18:02:04,603] Trial 180 pruned.

Best trial: 98. Best value: 0.555029:  90%|█████████ | 181/200 [02:14<00:10,  1.83it/s]

[I 2025-11-10 18:02:05,397] Trial 182 pruned.
[I 2025-11-10 18:02:05,502] Trial 178 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.11130835481834746, 'n_estimators': 776, 'subsample': 0.6519782519519907, 'colsample_bytree': 0.8128049686973421, 'min_child_weight': 6, 'gamma': 3.523702497841406, 'reg_alpha': 0.0008006137592081876, 'reg_lambda': 8.63964774438985e-06, 'max_delta_step': 7}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  91%|█████████ | 182/200 [02:15<00:11,  1.62it/s]

[I 2025-11-10 18:02:06,285] Trial 179 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.2733555911813899, 'n_estimators': 774, 'subsample': 0.6545242826476867, 'colsample_bytree': 0.8043141406393408, 'min_child_weight': 6, 'gamma': 3.575511487197918, 'reg_alpha': 0.33368305314263297, 'reg_lambda': 2.5520606268409273e-06, 'max_delta_step': 6}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  92%|█████████▏| 183/200 [02:16<00:13,  1.23it/s]

[I 2025-11-10 18:02:07,564] Trial 181 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.2646150642766804, 'n_estimators': 791, 'subsample': 0.5792758041139798, 'colsample_bytree': 0.7751277234728489, 'min_child_weight': 6, 'gamma': 2.55113698922131, 'reg_alpha': 3.0703371375285803e-06, 'reg_lambda': 1.7277768918288026e-07, 'max_delta_step': 4}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  92%|█████████▏| 184/200 [02:17<00:13,  1.14it/s]

[I 2025-11-10 18:02:08,579] Trial 184 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03562134229520629, 'n_estimators': 676, 'subsample': 0.5890296479864294, 'colsample_bytree': 0.9527065797607026, 'min_child_weight': 6, 'gamma': 0.48263337844197096, 'reg_alpha': 1.740550410633184, 'reg_lambda': 7.144657991813411, 'max_delta_step': 0}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  92%|█████████▎| 185/200 [02:18<00:11,  1.36it/s]

[I 2025-11-10 18:02:08,994] Trial 183 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.021497999809525156, 'n_estimators': 774, 'subsample': 0.6037244616391306, 'colsample_bytree': 0.8647762741744818, 'min_child_weight': 6, 'gamma': 2.6834253782180677, 'reg_alpha': 0.2181856617549745, 'reg_lambda': 7.608614083191943e-07, 'max_delta_step': 2}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  93%|█████████▎| 186/200 [02:18<00:09,  1.50it/s]

[I 2025-11-10 18:02:09,494] Trial 185 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.021288824827908323, 'n_estimators': 689, 'subsample': 0.6050691322946052, 'colsample_bytree': 0.9306814917906588, 'min_child_weight': 6, 'gamma': 0.7673012555479551, 'reg_alpha': 1.5360136882872006, 'reg_lambda': 4.595577728573783, 'max_delta_step': 2}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  94%|█████████▎| 187/200 [02:19<00:10,  1.27it/s]

[I 2025-11-10 18:02:10,558] Trial 188 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.24453999650154729, 'n_estimators': 303, 'subsample': 0.5968262025210039, 'colsample_bytree': 0.9339268668879096, 'min_child_weight': 7, 'gamma': 3.7299283687568665, 'reg_alpha': 0.15628932630336534, 'reg_lambda': 8.142131024840298, 'max_delta_step': 1}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  94%|█████████▍| 188/200 [02:20<00:07,  1.61it/s]

[I 2025-11-10 18:02:10,792] Trial 186 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02095782078655751, 'n_estimators': 668, 'subsample': 0.6013257005829631, 'colsample_bytree': 0.929569193410385, 'min_child_weight': 6, 'gamma': 0.7422202700040543, 'reg_alpha': 0.18721078164250352, 'reg_lambda': 7.868311576268199e-07, 'max_delta_step': 3}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  94%|█████████▍| 189/200 [02:20<00:07,  1.52it/s]

[I 2025-11-10 18:02:11,539] Trial 187 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02126022094529007, 'n_estimators': 604, 'subsample': 0.5983360805176609, 'colsample_bytree': 0.9254974513915719, 'min_child_weight': 7, 'gamma': 0.681476722318245, 'reg_alpha': 0.17850046450144258, 'reg_lambda': 8.584100581405924, 'max_delta_step': 2}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  95%|█████████▌| 190/200 [02:21<00:05,  1.90it/s]

[I 2025-11-10 18:02:11,756] Trial 189 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02746149833372775, 'n_estimators': 470, 'subsample': 0.592567548019927, 'colsample_bytree': 0.7516211792124966, 'min_child_weight': 5, 'gamma': 3.7384695034480813, 'reg_alpha': 0.1475124098625418, 'reg_lambda': 4.6014592398371165e-07, 'max_delta_step': 3}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 98. Best value: 0.555029:  96%|█████████▌| 191/200 [02:21<00:05,  1.55it/s]

[I 2025-11-10 18:02:12,678] Trial 193 pruned.

Best trial: 98. Best value: 0.555029:  96%|█████████▌| 192/200 [02:22<00:05,  1.43it/s]

[I 2025-11-10 18:02:13,496] Trial 190 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04041759863674984, 'n_estimators': 599, 'subsample': 0.674514417468295, 'colsample_bytree': 0.8974526858246507, 'min_child_weight': 5, 'gamma': 0.7863553861289432, 'reg_alpha': 0.9361187614208865, 'reg_lambda': 5.122886800865212e-07, 'max_delta_step': 3}. Best is trial 98 with value: 0.5550292397660819.

Best trial: 191. Best value: 0.561754:  96%|█████████▋| 193/200 [02:22<00:03,  1.81it/s]

[I 2025-11-10 18:02:13,706] Trial 191 finished with value: 0.5617543859649123 and parameters: {'max_depth': 3, 'learning_rate': 0.04291161786174988, 'n_estimators': 595, 'subsample': 0.6238381913263398, 'colsample_bytree': 0.8989047279984088, 'min_child_weight': 4, 'gamma': 1.049036477639335, 'reg_alpha': 3.0231789791843853, 'reg_lambda': 5.185244816092302e-07, 'max_delta_step': 3}. Best is trial 191 with value: 0.5617543859649123.

Best trial: 191. Best value: 0.561754:  97%|█████████▋| 194/200 [02:24<00:04,  1.29it/s]

[I 2025-11-10 18:02:15,013] Trial 192 finished with value: 0.5375438596491228 and parameters: {'max_depth': 3, 'learning_rate': 0.14515982796997629, 'n_estimators': 728, 'subsample': 0.6217267439445787, 'colsample_bytree': 0.8983530638814545, 'min_child_weight': 4, 'gamma': 1.0330275136098055, 'reg_alpha': 0.08173200960130593, 'reg_lambda': 4.274371344476526e-07, 'max_delta_step': 9}. Best is trial 191 with value: 0.5617543859649123.

Best trial: 191. Best value: 0.561754:  98%|█████████▊| 195/200 [02:24<00:03,  1.33it/s]

[I 2025-11-10 18:02:15,708] Trial 194 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03909733518536438, 'n_estimators': 647, 'subsample': 0.6719321761084295, 'colsample_bytree': 0.9030786889137272, 'min_child_weight': 6, 'gamma': 0.950402423580128, 'reg_alpha': 0.0004952037656812163, 'reg_lambda': 4.19931527375689, 'max_delta_step': 3}. Best is trial 191 with value: 0.5617543859649123.

Best trial: 191. Best value: 0.561754:  98%|█████████▊| 196/200 [02:25<00:02,  1.54it/s]

[I 2025-11-10 18:02:16,112] Trial 197 pruned.

Best trial: 191. Best value: 0.561754:  99%|█████████▉| 198/200 [02:25<00:00,  2.23it/s]

[I 2025-11-10 18:02:16,574] Trial 195 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05349768005005397, 'n_estimators': 635, 'subsample': 0.6193882790690883, 'colsample_bytree': 0.9074247662934983, 'min_child_weight': 6, 'gamma': 1.0857599174056611, 'reg_alpha': 0.0005759692854268564, 'reg_lambda': 5.1626307599725285, 'max_delta_step': 3}. Best is trial 191 with value: 0.5617543859649123.
[I 2025-11-10 18:02:16,686] Trial 196 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.053882877587088734, 'n_estimators': 631, 'subsample': 0.6401434656057104, 'colsample_bytree': 0.9049101774334218, 'min_child_weight': 4, 'gamma': 0.9091072299852557, 'reg_alpha': 7.070122726615839, 'reg_lambda': 6.280947464191364e-06, 'max_delta_step': 3}. Best is trial 191 with value: 0.5617543859649123.

Best trial: 191. Best value: 0.561754: 100%|██████████| 200/200 [02:27<00:00,  1.36it/s]

[I 2025-11-10 18:02:18,204] Trial 198 finished with value: 0.5142105263157895 and parameters: {'max_depth': 3, 'learning_rate': 0.13452694095086684, 'n_estimators': 813, 'subsample': 0.6217707257529964, 'colsample_bytree': 0.8915057028356951, 'min_child_weight': 4, 'gamma': 1.0602494385775836, 'reg_alpha': 3.977866738826079e-05, 'reg_lambda': 1.7641711603569035e-07, 'max_delta_step': 9}. Best is trial 191 with value: 0.5617543859649123.
[I 2025-11-10 18:02:18,254] Trial 199 finished with value: 0.4886549707602339 and parameters: {'max_depth': 3, 'learning_rate': 0.1630458608775426, 'n_estimators': 742, 'subsample': 0.6195727433339405, 'colsample_bytree': 0.8883259510925358, 'min_child_weight': 4, 'gamma': 1.0928931096737182, 'reg_alpha': 2.979946097068948, 'reg_lambda': 2.5161852130157296e-07, 'max_delta_step': 8}. Best is trial 191 with value: 0.5617543859649123.

[I 2025-11-10 18:02:19,085] A new study created in memory with name: 3_2_roc_auc
Best trial: 2. Best value: 0.5:   0%|          | 1/200 [00:02<09:49,  2.96s/it]

[I 2025-11-10 18:02:22,044] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03472763579691188, 'n_estimators': 710, 'subsample': 0.6818565483337348, 'colsample_bytree': 0.642822570939019, 'min_child_weight': 5, 'gamma': 3.933694113955657, 'reg_alpha': 0.0542153241035089, 'reg_lambda': 0.04244632761991144, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▏         | 3/200 [00:03<02:51,  1.15it/s]

[I 2025-11-10 18:02:22,458] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09607830991921532, 'n_estimators': 795, 'subsample': 0.9784824691086154, 'colsample_bytree': 0.6742037042904585, 'min_child_weight': 10, 'gamma': 1.1561233801516075, 'reg_alpha': 4.0669286306195565e-08, 'reg_lambda': 2.9409715219917216, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:02:22,616] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04555406278612703, 'n_estimators': 821, 'subsample': 0.6928042612737777, 'colsample_bytree': 0.747740149398852, 'min_child_weight': 5, 'gamma': 3.6184406295643705, 'reg_alpha': 0.03905862495498157, 'reg_lambda': 0.0005589976393460056, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▏         | 4/200 [00:04<03:03,  1.07it/s]

[I 2025-11-10 18:02:23,658] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.012863280362550892, 'n_estimators': 363, 'subsample': 0.7895431785571527, 'colsample_bytree': 0.906235299106563, 'min_child_weight': 10, 'gamma': 3.290302467389003, 'reg_alpha': 1.4175887011474567e-07, 'reg_lambda': 4.164261737911637e-07, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▎         | 5/200 [00:06<03:54,  1.20s/it]

[I 2025-11-10 18:02:25,329] Trial 0 finished with value: 0.38988304093567244 and parameters: {'max_depth': 6, 'learning_rate': 0.11178952927972453, 'n_estimators': 1435, 'subsample': 0.6408505426549826, 'colsample_bytree': 0.5663297240224605, 'min_child_weight': 2, 'gamma': 1.1221874898213846, 'reg_alpha': 0.011748214642915169, 'reg_lambda': 2.2563015892160913e-06, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   3%|▎         | 6/200 [00:07<04:02,  1.25s/it]

[I 2025-11-10 18:02:26,680] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.18884723826723498, 'n_estimators': 756, 'subsample': 0.6677371775908033, 'colsample_bytree': 0.6460100307893126, 'min_child_weight': 8, 'gamma': 4.020847261609807, 'reg_alpha': 1.4011863044076442e-06, 'reg_lambda': 0.0008492831523458914, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   4%|▎         | 7/200 [00:08<03:10,  1.01it/s]

[I 2025-11-10 18:02:27,120] Trial 6 finished with value: 0.41458089668615977 and parameters: {'max_depth': 9, 'learning_rate': 0.24996039888226498, 'n_estimators': 1096, 'subsample': 0.6432493515738651, 'colsample_bytree': 0.732998371607561, 'min_child_weight': 4, 'gamma': 0.28573469223261483, 'reg_alpha': 0.026063365256276227, 'reg_lambda': 1.7981995188321293e-06, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   4%|▍         | 8/200 [00:08<03:04,  1.04it/s]

[I 2025-11-10 18:02:28,030] Trial 5 finished with value: 0.3808187134502924 and parameters: {'max_depth': 4, 'learning_rate': 0.14298060106159738, 'n_estimators': 1202, 'subsample': 0.6620824697732961, 'colsample_bytree': 0.5304761379783324, 'min_child_weight': 2, 'gamma': 2.3105760541959777, 'reg_alpha': 1.772518283974124, 'reg_lambda': 1.4823376340725625e-06, 'max_delta_step': 10}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   4%|▍         | 9/200 [00:11<04:47,  1.50s/it]

[I 2025-11-10 18:02:30,725] Trial 8 finished with value: 0.40107212475633525 and parameters: {'max_depth': 10, 'learning_rate': 0.011267861961018748, 'n_estimators': 1143, 'subsample': 0.9494003529863616, 'colsample_bytree': 0.8426551292694117, 'min_child_weight': 5, 'gamma': 0.4347607242261742, 'reg_alpha': 0.03461114897462864, 'reg_lambda': 0.006892564079558797, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   5%|▌         | 10/200 [00:12<04:09,  1.31s/it]

[I 2025-11-10 18:02:31,610] Trial 10 finished with value: 0.4338401559454191 and parameters: {'max_depth': 4, 'learning_rate': 0.20847668250667445, 'n_estimators': 932, 'subsample': 0.8721530581575662, 'colsample_bytree': 0.7725366806954016, 'min_child_weight': 3, 'gamma': 2.1455498151327252, 'reg_alpha': 2.9503071777377976e-08, 'reg_lambda': 0.37250938939804673, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   6%|▌         | 12/200 [00:12<02:18,  1.36it/s]

[I 2025-11-10 18:02:31,919] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.15029593868022376, 'n_estimators': 1229, 'subsample': 0.8690265831878402, 'colsample_bytree': 0.9496185638461635, 'min_child_weight': 8, 'gamma': 4.969702043604351, 'reg_alpha': 1.1038081506491113e-07, 'reg_lambda': 1.3808189065352325e-05, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:02:32,038] Trial 11 pruned.

Best trial: 2. Best value: 0.5:   6%|▋         | 13/200 [00:13<02:00,  1.55it/s]

[I 2025-11-10 18:02:32,481] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.13206097874849074, 'n_estimators': 393, 'subsample': 0.7433511264639849, 'colsample_bytree': 0.6559417428822198, 'min_child_weight': 7, 'gamma': 4.631222015629064, 'reg_alpha': 1.0082349649268962e-06, 'reg_lambda': 0.00012152287094690575, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   7%|▋         | 14/200 [00:14<02:30,  1.24it/s]

[I 2025-11-10 18:02:33,667] Trial 13 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.034844290230779375, 'n_estimators': 411, 'subsample': 0.5189587827294494, 'colsample_bytree': 0.996512385866231, 'min_child_weight': 7, 'gamma': 4.9420214621019465, 'reg_alpha': 6.233597428658186e-05, 'reg_lambda': 8.011392813136661e-05, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   8%|▊         | 15/200 [00:15<02:16,  1.36it/s]

[I 2025-11-10 18:02:34,232] Trial 15 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.02923805938541516, 'n_estimators': 495, 'subsample': 0.5052242505495088, 'colsample_bytree': 0.6466043470331856, 'min_child_weight': 7, 'gamma': 3.231753732481081, 'reg_alpha': 0.00023145635068935099, 'reg_lambda': 0.051244092235716986, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:02:34,257] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.033078345984962815, 'n_estimators': 517, 'subsample': 0.5333434252124747, 'colsample_bytree': 0.6322935018400757, 'min_child_weight': 6, 'gamma': 3.7278767273318927, 'reg_alpha': 0.00010836607031342624, 'reg_lambda': 0.02096365956413664, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   8%|▊         | 17/200 [00:16<01:49,  1.67it/s]

[I 2025-11-10 18:02:35,101] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.029863812811352256, 'n_estimators': 583, 'subsample': 0.5092353818304712, 'colsample_bytree': 0.7438665368469423, 'min_child_weight': 6, 'gamma': 3.38806769384055, 'reg_alpha': 0.00019276268892679983, 'reg_lambda': 0.031618351279911, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   9%|▉         | 18/200 [00:17<02:24,  1.26it/s]

[I 2025-11-10 18:02:36,490] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.058828877455640034, 'n_estimators': 213, 'subsample': 0.7516518014279573, 'colsample_bytree': 0.8056256071226743, 'min_child_weight': 1, 'gamma': 2.8223125283292076, 'reg_alpha': 6.313383092579027, 'reg_lambda': 1.2760851230790038e-08, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  10%|▉         | 19/200 [00:17<01:55,  1.57it/s]

[I 2025-11-10 18:02:36,683] Trial 18 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.05600309708198641, 'n_estimators': 606, 'subsample': 0.7436170495136531, 'colsample_bytree': 0.7460031041160434, 'min_child_weight': 5, 'gamma': 3.602067550186249, 'reg_alpha': 8.232420010614758, 'reg_lambda': 0.00315056408789321, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:02:36,760] Trial 17 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03503943822913451, 'n_estimators': 724, 'subsample': 0.7407885637487676, 'colsample_bytree': 0.742288968669777, 'min_child_weight': 6, 'gamma': 3.1753442946434567, 'reg_alpha': 0.000676392969481286, 'reg_lambda': 0.03535651870093922, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  11%|█         | 22/200 [00:18<01:19,  2.25it/s]

[I 2025-11-10 18:02:37,552] Trial 22 pruned.
[I 2025-11-10 18:02:37,654] Trial 23 pruned.

Best trial: 2. Best value: 0.5:  12%|█▏        | 23/200 [00:19<01:30,  1.95it/s]

[I 2025-11-10 18:02:38,364] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.06970256487340677, 'n_estimators': 654, 'subsample': 0.7421945380091941, 'colsample_bytree': 0.7419040838048814, 'min_child_weight': 1, 'gamma': 2.9937100910303625, 'reg_alpha': 6.073332924895956, 'reg_lambda': 0.003294856691979433, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  12%|█▏        | 24/200 [00:20<01:57,  1.50it/s]

[I 2025-11-10 18:02:39,464] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.06175587484073052, 'n_estimators': 672, 'subsample': 0.7177789040112561, 'colsample_bytree': 0.585135207923909, 'min_child_weight': 5, 'gamma': 2.7397031930991997, 'reg_alpha': 0.003532062761192998, 'reg_lambda': 8.683702056719119, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  12%|█▎        | 25/200 [00:21<02:32,  1.15it/s]

[I 2025-11-10 18:02:40,883] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0880246830882618, 'n_estimators': 786, 'subsample': 0.9713646072643387, 'colsample_bytree': 0.5894874505902816, 'min_child_weight': 9, 'gamma': 1.3901175230376948, 'reg_alpha': 0.4076510833618232, 'reg_lambda': 1.5811042342864288, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  13%|█▎        | 26/200 [00:22<02:01,  1.43it/s]

[I 2025-11-10 18:02:41,138] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.08050464757612741, 'n_estimators': 777, 'subsample': 0.9762076631516182, 'colsample_bytree': 0.7040078728420208, 'min_child_weight': 10, 'gamma': 1.4741959928701904, 'reg_alpha': 1.015995277675996e-05, 'reg_lambda': 0.3918823786575326, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  14%|█▎        | 27/200 [00:22<02:07,  1.36it/s]

[I 2025-11-10 18:02:41,966] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07538386570560415, 'n_estimators': 814, 'subsample': 0.9583314013428204, 'colsample_bytree': 0.6920553792477594, 'min_child_weight': 10, 'gamma': 1.688224151718817, 'reg_alpha': 1.0707282060901636e-05, 'reg_lambda': 0.5769214813839092, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:02:41,975] Trial 29 pruned.

Best trial: 2. Best value: 0.5:  15%|█▌        | 30/200 [00:24<01:28,  1.91it/s]

[I 2025-11-10 18:02:43,014] Trial 30 pruned.
[I 2025-11-10 18:02:43,174] Trial 27 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.08891019552216409, 'n_estimators': 821, 'subsample': 0.9932064236023364, 'colsample_bytree': 0.6865356613628099, 'min_child_weight': 9, 'gamma': 1.8689059390831853, 'reg_alpha': 8.708355960113472e-06, 'reg_lambda': 0.4765792459418483, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  16%|█▌        | 31/200 [00:25<02:12,  1.28it/s]

[I 2025-11-10 18:02:44,709] Trial 28 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.0432011152765738, 'n_estimators': 861, 'subsample': 0.5821732484829405, 'colsample_bytree': 0.6961670982454793, 'min_child_weight': 10, 'gamma': 1.5319993431043213, 'reg_alpha': 1.626148889107172e-05, 'reg_lambda': 0.25994807512341184, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  16%|█▌        | 32/200 [00:26<02:29,  1.12it/s]

[I 2025-11-10 18:02:45,890] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.020588203509235747, 'n_estimators': 243, 'subsample': 0.7001599111987656, 'colsample_bytree': 0.9107720883240032, 'min_child_weight': 9, 'gamma': 3.636211983243163, 'reg_alpha': 1.454126151422097e-07, 'reg_lambda': 1.2756581314964733e-05, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  16%|█▋        | 33/200 [00:27<02:21,  1.18it/s]

[I 2025-11-10 18:02:46,629] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.022379010017954736, 'n_estimators': 1040, 'subsample': 0.7062464859745384, 'colsample_bytree': 0.7922609582176487, 'min_child_weight': 9, 'gamma': 0.8982520347881573, 'reg_alpha': 0.0018789878757280532, 'reg_lambda': 0.0003702742491024496, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  17%|█▋        | 34/200 [00:29<03:25,  1.24s/it]

[I 2025-11-10 18:02:48,840] Trial 33 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02417950959346216, 'n_estimators': 1319, 'subsample': 0.6945445679423591, 'colsample_bytree': 0.5590310441489681, 'min_child_weight': 8, 'gamma': 1.0491367547606931, 'reg_alpha': 0.002748729709203354, 'reg_lambda': 2.001170261453669e-05, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  18%|█▊        | 35/200 [00:30<02:45,  1.00s/it]

[I 2025-11-10 18:02:49,272] Trial 32 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.020322271163041278, 'n_estimators': 1499, 'subsample': 0.6930249769192777, 'colsample_bytree': 0.5495699225444656, 'min_child_weight': 8, 'gamma': 0.9781047729457955, 'reg_alpha': 0.004383974332943477, 'reg_lambda': 4.393096501012433e-05, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  18%|█▊        | 36/200 [00:31<02:45,  1.01s/it]

[I 2025-11-10 18:02:50,296] Trial 37 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.011049530907917892, 'n_estimators': 313, 'subsample': 0.7902124618421816, 'colsample_bytree': 0.880743617282712, 'min_child_weight': 5, 'gamma': 2.405200955300173, 'reg_alpha': 1.1245354901451958e-08, 'reg_lambda': 2.531792960484837e-07, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  18%|█▊        | 37/200 [00:31<02:28,  1.10it/s]

[I 2025-11-10 18:02:50,973] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.010544062308759584, 'n_estimators': 377, 'subsample': 0.797045398252388, 'colsample_bytree': 0.8926806986753828, 'min_child_weight': 5, 'gamma': 2.403271095532233, 'reg_alpha': 1.4670009883536823e-08, 'reg_lambda': 3.273388462516353e-07, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  19%|█▉        | 38/200 [00:33<03:00,  1.11s/it]

[I 2025-11-10 18:02:52,560] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.011191167756677875, 'n_estimators': 1499, 'subsample': 0.8019092480184675, 'colsample_bytree': 0.887452563891619, 'min_child_weight': 8, 'gamma': 1.042416985805075, 'reg_alpha': 1.0567415470372772e-08, 'reg_lambda': 2.347384758482666e-07, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  20%|█▉        | 39/200 [00:33<02:19,  1.15it/s]

[I 2025-11-10 18:02:52,847] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01075362833193593, 'n_estimators': 1399, 'subsample': 0.788997679687138, 'colsample_bytree': 0.8829264170704577, 'min_child_weight': 8, 'gamma': 2.485657825630104, 'reg_alpha': 2.2991356453500664e-08, 'reg_lambda': 4.0514681931238173e-07, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  21%|██        | 42/200 [00:34<01:10,  2.25it/s]

[I 2025-11-10 18:02:53,414] Trial 41 pruned.
[I 2025-11-10 18:02:53,448] Trial 40 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.11009367298958739, 'n_estimators': 512, 'subsample': 0.6297426527920295, 'colsample_bytree': 0.6222535745673694, 'min_child_weight': 10, 'gamma': 4.112487947040031, 'reg_alpha': 2.1959942610950322e-07, 'reg_lambda': 2.3714428063151716e-06, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:02:53,522] Trial 42 pruned.

Best trial: 2. Best value: 0.5:  22%|██▏       | 43/200 [00:34<00:57,  2.75it/s]

[I 2025-11-10 18:02:53,641] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.015756840008805603, 'n_estimators': 709, 'subsample': 0.6269168596371743, 'colsample_bytree': 0.6346275956659342, 'min_child_weight': 10, 'gamma': 3.994769346894998, 'reg_alpha': 6.634785906373687e-07, 'reg_lambda': 3.648625612700428e-06, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  22%|██▏       | 44/200 [00:37<02:33,  1.02it/s]

[I 2025-11-10 18:02:56,369] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.290716979413777, 'n_estimators': 716, 'subsample': 0.9086696859927545, 'colsample_bytree': 0.6658055962650379, 'min_child_weight': 7, 'gamma': 4.497258158630335, 'reg_alpha': 7.68110849307754e-08, 'reg_lambda': 0.001036309425389944, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:02:56,375] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.2470061400599669, 'n_estimators': 717, 'subsample': 0.6661524687526862, 'colsample_bytree': 0.6627609532952741, 'min_child_weight': 7, 'gamma': 0.09694297234619365, 'reg_alpha': 1.6903998743274675e-06, 'reg_lambda': 0.0008483643282299522, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  23%|██▎       | 46/200 [00:37<01:39,  1.56it/s]

[I 2025-11-10 18:02:56,752] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.17782140190045376, 'n_estimators': 741, 'subsample': 0.6710740189379185, 'colsample_bytree': 0.6648503867229826, 'min_child_weight': 7, 'gamma': 4.482794956212825, 'reg_alpha': 5.360906774576204e-08, 'reg_lambda': 0.001261686658687331, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  24%|██▎       | 47/200 [00:38<01:50,  1.38it/s]

[I 2025-11-10 18:02:57,736] Trial 43 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10964821724491164, 'n_estimators': 1055, 'subsample': 0.6585591366194447, 'colsample_bytree': 0.6156520780134465, 'min_child_weight': 10, 'gamma': 4.42063304030262, 'reg_alpha': 0.015375933294169765, 'reg_lambda': 1.097259962045809e-08, 'max_delta_step': 10}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  24%|██▍       | 48/200 [00:41<02:59,  1.18s/it]

[I 2025-11-10 18:03:00,278] Trial 50 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1365500989241087, 'n_estimators': 601, 'subsample': 0.5533331759312179, 'colsample_bytree': 0.9898843581947786, 'min_child_weight': 6, 'gamma': 3.7707217972332288, 'reg_alpha': 3.3645005237275365e-06, 'reg_lambda': 0.009173338232588082, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  24%|██▍       | 49/200 [00:41<02:20,  1.07it/s]

[I 2025-11-10 18:03:00,519] Trial 47 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.16943494705760848, 'n_estimators': 1047, 'subsample': 0.8526376872173299, 'colsample_bytree': 0.7183014200778594, 'min_child_weight': 6, 'gamma': 3.8038753824263294, 'reg_alpha': 0.016738831755505227, 'reg_lambda': 0.011270379171971127, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  25%|██▌       | 50/200 [00:41<01:49,  1.37it/s]

[I 2025-11-10 18:03:00,703] Trial 48 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.16941461689610374, 'n_estimators': 1087, 'subsample': 0.6764369605687806, 'colsample_bytree': 0.7248647302971125, 'min_child_weight': 6, 'gamma': 3.460054264773593, 'reg_alpha': 0.02176772930263554, 'reg_lambda': 0.006227749250961849, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  26%|██▌       | 51/200 [00:41<01:32,  1.61it/s]

[I 2025-11-10 18:03:01,046] Trial 49 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.13916912525712713, 'n_estimators': 1084, 'subsample': 0.8448083964736807, 'colsample_bytree': 0.7195616077328406, 'min_child_weight': 6, 'gamma': 3.815817942269272, 'reg_alpha': 0.0267879592168983, 'reg_lambda': 0.00013772478222571946, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  26%|██▌       | 52/200 [00:44<03:06,  1.26s/it]

[I 2025-11-10 18:03:03,903] Trial 51 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.19948158342846303, 'n_estimators': 934, 'subsample': 0.8431747714431259, 'colsample_bytree': 0.7111038561859306, 'min_child_weight': 9, 'gamma': 3.2986101813978497, 'reg_alpha': 0.046927278862091665, 'reg_lambda': 0.07703541964889912, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  26%|██▋       | 53/200 [00:45<02:32,  1.04s/it]

[I 2025-11-10 18:03:04,390] Trial 52 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.02783896299281527, 'n_estimators': 962, 'subsample': 0.7691471273703318, 'colsample_bytree': 0.844942557313611, 'min_child_weight': 9, 'gamma': 4.717605036839424, 'reg_alpha': 3.7426566294523356e-05, 'reg_lambda': 0.000173980194313651, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  27%|██▋       | 54/200 [00:45<01:55,  1.27it/s]

[I 2025-11-10 18:03:04,581] Trial 53 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.02778277409353182, 'n_estimators': 945, 'subsample': 0.8503737612349719, 'colsample_bytree': 0.9429144296995724, 'min_child_weight': 9, 'gamma': 3.1208966276379053, 'reg_alpha': 1.488437672533696, 'reg_lambda': 0.07100111341822313, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  28%|██▊       | 55/200 [00:45<01:39,  1.45it/s]

[I 2025-11-10 18:03:05,036] Trial 55 pruned.

Best trial: 2. Best value: 0.5:  28%|██▊       | 56/200 [00:46<01:19,  1.82it/s]

[I 2025-11-10 18:03:05,252] Trial 57 pruned.

Best trial: 2. Best value: 0.5:  28%|██▊       | 57/200 [00:46<01:11,  2.00it/s]

[I 2025-11-10 18:03:05,636] Trial 56 pruned.

Best trial: 2. Best value: 0.5:  29%|██▉       | 58/200 [00:46<00:58,  2.44it/s]

[I 2025-11-10 18:03:05,833] Trial 58 pruned.

Best trial: 2. Best value: 0.5:  30%|██▉       | 59/200 [00:46<00:48,  2.91it/s]

[I 2025-11-10 18:03:06,020] Trial 59 pruned.

Best trial: 2. Best value: 0.5:  30%|███       | 60/200 [00:47<00:53,  2.61it/s]

[I 2025-11-10 18:03:06,498] Trial 54 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.21171932200641874, 'n_estimators': 1246, 'subsample': 0.8939723643514098, 'colsample_bytree': 0.9600034290950299, 'min_child_weight': 9, 'gamma': 4.959605912875034, 'reg_alpha': 1.951577607709622e-07, 'reg_lambda': 5.1887254453701216e-08, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  31%|███       | 62/200 [00:47<00:39,  3.52it/s]

[I 2025-11-10 18:03:06,795] Trial 60 pruned.
[I 2025-11-10 18:03:06,908] Trial 62 pruned.

Best trial: 2. Best value: 0.5:  32%|███▏      | 64/200 [00:49<01:10,  1.92it/s]

[I 2025-11-10 18:03:08,540] Trial 65 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.12356299332177795, 'n_estimators': 364, 'subsample': 0.7627045957866928, 'colsample_bytree': 0.6058356673201403, 'min_child_weight': 8, 'gamma': 4.551510113358152, 'reg_alpha': 3.2668365977301774e-06, 'reg_lambda': 0.00021887629903520777, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:03:08,663] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.13042178004299682, 'n_estimators': 410, 'subsample': 0.7667095273451424, 'colsample_bytree': 0.5983442254371001, 'min_child_weight': 7, 'gamma': 3.494394586683743, 'reg_alpha': 2.218483692247944e-06, 'reg_lambda': 0.0018678647150282325, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  32%|███▎      | 65/200 [00:50<01:43,  1.30it/s]

[I 2025-11-10 18:03:10,015] Trial 67 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09362613962239472, 'n_estimators': 290, 'subsample': 0.8179588441009304, 'colsample_bytree': 0.6472045396982511, 'min_child_weight': 8, 'gamma': 4.65061769383386, 'reg_alpha': 0.00741787424856103, 'reg_lambda': 1.683815258931152, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  33%|███▎      | 66/200 [00:51<01:32,  1.44it/s]

[I 2025-11-10 18:03:10,534] Trial 66 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.09331754107913828, 'n_estimators': 431, 'subsample': 0.8721993625400545, 'colsample_bytree': 0.646886528775908, 'min_child_weight': 7, 'gamma': 3.4829669535015917, 'reg_alpha': 0.006329834711973348, 'reg_lambda': 0.0029303255014555855, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  34%|███▎      | 67/200 [00:52<01:36,  1.37it/s]

[I 2025-11-10 18:03:11,340] Trial 61 finished with value: 0.4792202729044834 and parameters: {'max_depth': 8, 'learning_rate': 0.06609484162532533, 'n_estimators': 1151, 'subsample': 0.7636295000318287, 'colsample_bytree': 0.758821806286942, 'min_child_weight': 4, 'gamma': 3.522827823508736, 'reg_alpha': 0.00040149510131498904, 'reg_lambda': 0.0024867138775027105, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  34%|███▍      | 68/200 [00:52<01:29,  1.48it/s]

[I 2025-11-10 18:03:11,894] Trial 63 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.06528760793969521, 'n_estimators': 1172, 'subsample': 0.726439245727024, 'colsample_bytree': 0.7573820015262506, 'min_child_weight': 8, 'gamma': 3.4584045484822714, 'reg_alpha': 2.0096061934591847e-06, 'reg_lambda': 0.0032383631760504166, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  34%|███▍      | 69/200 [00:53<01:12,  1.80it/s]

[I 2025-11-10 18:03:12,168] Trial 68 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01300973258634601, 'n_estimators': 455, 'subsample': 0.7315691028047717, 'colsample_bytree': 0.6855803216442808, 'min_child_weight': 7, 'gamma': 3.990576910386937, 'reg_alpha': 0.32686617274267193, 'reg_lambda': 7.878344466693123e-05, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  35%|███▌      | 70/200 [00:55<02:17,  1.06s/it]

[I 2025-11-10 18:03:14,409] Trial 69 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.15276812254924746, 'n_estimators': 895, 'subsample': 0.730236265564445, 'colsample_bytree': 0.6794007251869667, 'min_child_weight': 8, 'gamma': 3.973618368033292, 'reg_alpha': 1.4226678222659354e-06, 'reg_lambda': 8.349580587819759e-05, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  36%|███▌      | 71/200 [00:55<01:42,  1.25it/s]

[I 2025-11-10 18:03:14,595] Trial 72 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.15227097528921724, 'n_estimators': 553, 'subsample': 0.6844890264745676, 'colsample_bytree': 0.5729395149623986, 'min_child_weight': 10, 'gamma': 4.7443601953289685, 'reg_alpha': 9.221781679832206e-08, 'reg_lambda': 3.5062847343489643, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  36%|███▌      | 72/200 [00:55<01:26,  1.48it/s]

[I 2025-11-10 18:03:14,989] Trial 70 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.15620555875234857, 'n_estimators': 817, 'subsample': 0.7355279626011093, 'colsample_bytree': 0.6889610988587007, 'min_child_weight': 8, 'gamma': 0.6079986550169614, 'reg_alpha': 0.654424187310389, 'reg_lambda': 4.696198283326846, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  36%|███▋      | 73/200 [00:56<01:26,  1.47it/s]

[I 2025-11-10 18:03:15,670] Trial 71 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04950297071336746, 'n_estimators': 828, 'subsample': 0.6873529122370893, 'colsample_bytree': 0.6870254217538001, 'min_child_weight': 10, 'gamma': 3.9684299537746104, 'reg_alpha': 0.4662639863348001, 'reg_lambda': 6.381087543604027e-05, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  37%|███▋      | 74/200 [00:57<01:36,  1.31it/s]

[I 2025-11-10 18:03:16,633] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03257617335874016, 'n_estimators': 333, 'subsample': 0.9998523132330526, 'colsample_bytree': 0.990170353756569, 'min_child_weight': 6, 'gamma': 4.626354367239654, 'reg_alpha': 0.00014292441908268325, 'reg_lambda': 0.0005196460264714013, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  38%|███▊      | 75/200 [00:58<01:30,  1.38it/s]

[I 2025-11-10 18:03:17,260] Trial 76 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03219416599418212, 'n_estimators': 324, 'subsample': 0.5348702082926626, 'colsample_bytree': 0.9469116815471068, 'min_child_weight': 6, 'gamma': 4.593945657897424, 'reg_alpha': 5.940636454345786e-06, 'reg_lambda': 0.15228568755160396, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  38%|███▊      | 76/200 [00:58<01:20,  1.53it/s]

[I 2025-11-10 18:03:17,748] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03829061220422171, 'n_estimators': 206, 'subsample': 0.5913880038644124, 'colsample_bytree': 0.9471814557312901, 'min_child_weight': 7, 'gamma': 4.3978094921768545, 'reg_alpha': 2.2128762238025447e-05, 'reg_lambda': 2.5960311285534945e-05, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  38%|███▊      | 77/200 [00:59<01:10,  1.74it/s]

[I 2025-11-10 18:03:18,142] Trial 73 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.055907094899716535, 'n_estimators': 829, 'subsample': 0.688083151343461, 'colsample_bytree': 0.5708481816497792, 'min_child_weight': 10, 'gamma': 4.671539000476759, 'reg_alpha': 2.2798002951626704e-08, 'reg_lambda': 0.00046616282236360896, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  39%|███▉      | 78/200 [00:59<00:57,  2.11it/s]

[I 2025-11-10 18:03:18,382] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07460872793291563, 'n_estimators': 209, 'subsample': 0.603800119195099, 'colsample_bytree': 0.6333264096773193, 'min_child_weight': 7, 'gamma': 1.2375696901417002, 'reg_alpha': 4.014640681124219e-05, 'reg_lambda': 0.023910188619038715, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  40%|███▉      | 79/200 [00:59<00:53,  2.26it/s]

[I 2025-11-10 18:03:18,749] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.05159739119836682, 'n_estimators': 837, 'subsample': 0.547934767789008, 'colsample_bytree': 0.9994694838536138, 'min_child_weight': 6, 'gamma': 0.587436983398068, 'reg_alpha': 7.85302775300459e-05, 'reg_lambda': 0.0005435982979106818, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  40%|████      | 80/200 [01:00<01:10,  1.71it/s]

[I 2025-11-10 18:03:19,668] Trial 81 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.024761383291958455, 'n_estimators': 253, 'subsample': 0.7099143309955792, 'colsample_bytree': 0.904723067475638, 'min_child_weight': 9, 'gamma': 4.815351929859476, 'reg_alpha': 4.1289209128387965e-07, 'reg_lambda': 0.8573877286526059, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  40%|████      | 81/200 [01:01<01:13,  1.61it/s]

[I 2025-11-10 18:03:20,363] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.025297676481506052, 'n_estimators': 538, 'subsample': 0.7104360333152488, 'colsample_bytree': 0.8659654341349654, 'min_child_weight': 5, 'gamma': 3.654942818594633, 'reg_alpha': 5.9858365846898534e-05, 'reg_lambda': 0.0003509567703530774, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  41%|████      | 82/200 [01:01<01:13,  1.61it/s]

[I 2025-11-10 18:03:20,995] Trial 80 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.024549928285505805, 'n_estimators': 631, 'subsample': 0.704795715629674, 'colsample_bytree': 0.6260272841324015, 'min_child_weight': 9, 'gamma': 2.249036599169206, 'reg_alpha': 5.3606798874625036e-05, 'reg_lambda': 0.0002343538209010368, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  42%|████▏     | 83/200 [01:02<01:17,  1.51it/s]

[I 2025-11-10 18:03:21,747] Trial 82 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.18559569222104902, 'n_estimators': 630, 'subsample': 0.709284418199223, 'colsample_bytree': 0.9099852347098129, 'min_child_weight': 9, 'gamma': 2.190715375315322, 'reg_alpha': 6.814366404079004e-07, 'reg_lambda': 0.0002607038296130866, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  42%|████▏     | 84/200 [01:03<01:29,  1.30it/s]

[I 2025-11-10 18:03:22,773] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.18943537542062486, 'n_estimators': 384, 'subsample': 0.5209469839776385, 'colsample_bytree': 0.6513701323303378, 'min_child_weight': 6, 'gamma': 2.7165094474518865, 'reg_alpha': 0.07469691309283684, 'reg_lambda': 0.02370168514605318, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  42%|████▎     | 85/200 [01:04<01:15,  1.53it/s]

[I 2025-11-10 18:03:23,153] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.18961150458680928, 'n_estimators': 759, 'subsample': 0.6503615331704766, 'colsample_bytree': 0.6560308695372488, 'min_child_weight': 5, 'gamma': 4.141240546605836, 'reg_alpha': 9.665511117094638e-07, 'reg_lambda': 7.245548365708011e-06, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:03:23,235] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04014378393959113, 'n_estimators': 629, 'subsample': 0.522411807725379, 'colsample_bytree': 0.6250988891878279, 'min_child_weight': 6, 'gamma': 3.322185509565457, 'reg_alpha': 0.0009132429301916651, 'reg_lambda': 0.019503045602938893, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  44%|████▎     | 87/200 [01:06<01:31,  1.23it/s]

[I 2025-11-10 18:03:25,150] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03837814216674605, 'n_estimators': 759, 'subsample': 0.5025692127301078, 'colsample_bytree': 0.6553172402402853, 'min_child_weight': 6, 'gamma': 3.2572071146244617, 'reg_alpha': 0.000486746378303096, 'reg_lambda': 0.017345422551272943, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  44%|████▍     | 88/200 [01:06<01:13,  1.52it/s]

[I 2025-11-10 18:03:25,334] Trial 88 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03605515895290559, 'n_estimators': 471, 'subsample': 0.5681348300236609, 'colsample_bytree': 0.6108422249684528, 'min_child_weight': 7, 'gamma': 3.309206973098967, 'reg_alpha': 0.0016767844461197132, 'reg_lambda': 2.5697372163620107e-05, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:03:25,420] Trial 89 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03490283278929621, 'n_estimators': 469, 'subsample': 0.5801911314394861, 'colsample_bytree': 0.7345460739993636, 'min_child_weight': 7, 'gamma': 3.778277947287446, 'reg_alpha': 1.0705049684485384e-07, 'reg_lambda': 0.0001170231088006004, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  45%|████▌     | 90/200 [01:07<01:04,  1.70it/s]

[I 2025-11-10 18:03:26,318] Trial 87 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03812915225050196, 'n_estimators': 783, 'subsample': 0.5064807322416535, 'colsample_bytree': 0.6103593977962061, 'min_child_weight': 7, 'gamma': 3.29462081549269, 'reg_alpha': 0.0015056962900433792, 'reg_lambda': 0.0051821102436061745, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  46%|████▌     | 91/200 [01:09<01:38,  1.11it/s]

[I 2025-11-10 18:03:28,272] Trial 90 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.0457399412863155, 'n_estimators': 686, 'subsample': 0.5721114982425333, 'colsample_bytree': 0.6722986850254811, 'min_child_weight': 7, 'gamma': 3.761449286269101, 'reg_alpha': 0.0001715055342431447, 'reg_lambda': 0.005084689454107067, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  46%|████▌     | 92/200 [01:09<01:26,  1.24it/s]

[I 2025-11-10 18:03:28,786] Trial 93 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.11752743482576929, 'n_estimators': 546, 'subsample': 0.7482750375083399, 'colsample_bytree': 0.7040668089292369, 'min_child_weight': 5, 'gamma': 3.683023157180393, 'reg_alpha': 0.00020834406321036802, 'reg_lambda': 0.8906677608925755, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  46%|████▋     | 93/200 [01:10<01:20,  1.33it/s]

[I 2025-11-10 18:03:29,381] Trial 92 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.04558218333563445, 'n_estimators': 895, 'subsample': 0.7535691141915994, 'colsample_bytree': 0.704614043233165, 'min_child_weight': 8, 'gamma': 4.364610426627452, 'reg_alpha': 0.20730675035234047, 'reg_lambda': 0.12517554897598554, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  47%|████▋     | 94/200 [01:10<01:10,  1.50it/s]

[I 2025-11-10 18:03:29,825] Trial 91 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.04447211944379141, 'n_estimators': 995, 'subsample': 0.9743463570596818, 'colsample_bytree': 0.6715024840609948, 'min_child_weight': 7, 'gamma': 3.7092491394720835, 'reg_alpha': 2.3613854101523386e-08, 'reg_lambda': 0.0053565173929531985, 'max_delta_step': 10}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  48%|████▊     | 95/200 [01:11<01:15,  1.38it/s]

[I 2025-11-10 18:03:30,687] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.029113040338357845, 'n_estimators': 526, 'subsample': 0.7501464730263818, 'colsample_bytree': 0.7008204333671355, 'min_child_weight': 8, 'gamma': 3.0648812640169476, 'reg_alpha': 0.00012030359412335887, 'reg_lambda': 0.07308649471685662, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  48%|████▊     | 97/200 [01:12<00:51,  2.00it/s]

[I 2025-11-10 18:03:31,136] Trial 95 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.018898766202699313, 'n_estimators': 519, 'subsample': 0.614191435465068, 'colsample_bytree': 0.6392396142128028, 'min_child_weight': 8, 'gamma': 3.130465750941484, 'reg_alpha': 9.926590794930528e-05, 'reg_lambda': 0.04285536314723465, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:03:31,278] Trial 96 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.030923756600897998, 'n_estimators': 403, 'subsample': 0.5231109374855677, 'colsample_bytree': 0.6379504143824376, 'min_child_weight': 10, 'gamma': 4.801284806829693, 'reg_alpha': 1.808402346486197e-05, 'reg_lambda': 0.04216457121989566, 'max_delta_step': 10}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  49%|████▉     | 98/200 [01:12<00:51,  1.98it/s]

[I 2025-11-10 18:03:31,801] Trial 97 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.029509354979934076, 'n_estimators': 420, 'subsample': 0.8260290418729512, 'colsample_bytree': 0.638274012386886, 'min_child_weight': 10, 'gamma': 3.0473187863422533, 'reg_alpha': 0.00010853474994687573, 'reg_lambda': 0.05261765100181434, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  50%|████▉     | 99/200 [01:13<00:59,  1.70it/s]

[I 2025-11-10 18:03:32,585] Trial 98 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.01887647402615898, 'n_estimators': 401, 'subsample': 0.5189775721269635, 'colsample_bytree': 0.5888929946308844, 'min_child_weight': 10, 'gamma': 4.854013907388129, 'reg_alpha': 0.00025260530175396886, 'reg_lambda': 0.04962722639522878, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  50%|█████     | 100/200 [01:13<00:48,  2.07it/s]

[I 2025-11-10 18:03:32,822] Trial 99 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03137609024205946, 'n_estimators': 353, 'subsample': 0.5327294926687436, 'colsample_bytree': 0.6414979655106634, 'min_child_weight': 5, 'gamma': 2.62333624962453, 'reg_alpha': 8.254888370431237e-06, 'reg_lambda': 0.2709976239606442, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  50%|█████     | 101/200 [01:13<00:39,  2.49it/s]

[I 2025-11-10 18:03:33,028] Trial 102 pruned.

Best trial: 2. Best value: 0.5:  51%|█████     | 102/200 [01:14<00:33,  2.92it/s]

[I 2025-11-10 18:03:33,235] Trial 101 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03363048642398903, 'n_estimators': 280, 'subsample': 0.7841893873990764, 'colsample_bytree': 0.5437230602348677, 'min_child_weight': 5, 'gamma': 4.987499756037088, 'reg_alpha': 0.0002755688542235488, 'reg_lambda': 0.0009410507680875879, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  52%|█████▏    | 103/200 [01:15<01:10,  1.38it/s]

[I 2025-11-10 18:03:34,860] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.02282675495463382, 'n_estimators': 446, 'subsample': 0.7781731823089214, 'colsample_bytree': 0.5338571187304659, 'min_child_weight': 6, 'gamma': 3.866513326784649, 'reg_alpha': 2.879564056012463e-07, 'reg_lambda': 0.0013937257228469008, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  52%|█████▏    | 104/200 [01:16<01:12,  1.32it/s]

[I 2025-11-10 18:03:35,693] Trial 104 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.02243051673243163, 'n_estimators': 581, 'subsample': 0.5468176369528273, 'colsample_bytree': 0.7908011741860886, 'min_child_weight': 6, 'gamma': 1.7965833714623365, 'reg_alpha': 0.00034447985136626456, 'reg_lambda': 0.0010562304967562186, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  52%|█████▎    | 105/200 [01:17<01:08,  1.38it/s]

[I 2025-11-10 18:03:36,345] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.021144985308444487, 'n_estimators': 697, 'subsample': 0.550475545755039, 'colsample_bytree': 0.7427093941627586, 'min_child_weight': 6, 'gamma': 1.6999035334528116, 'reg_alpha': 0.04922239469857088, 'reg_lambda': 0.01004215514117516, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  53%|█████▎    | 106/200 [01:18<01:25,  1.10it/s]

[I 2025-11-10 18:03:37,668] Trial 100 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.022320949670593022, 'n_estimators': 1365, 'subsample': 0.7784368708429952, 'colsample_bytree': 0.925964998121046, 'min_child_weight': 5, 'gamma': 2.924490218095336, 'reg_alpha': 3.633500282519275e-07, 'reg_lambda': 0.2795283282368122, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  54%|█████▎    | 107/200 [01:18<01:07,  1.38it/s]

[I 2025-11-10 18:03:37,981] Trial 107 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.026618633474004477, 'n_estimators': 494, 'subsample': 0.636686223539753, 'colsample_bytree': 0.7412344764758275, 'min_child_weight': 7, 'gamma': 4.082253461242429, 'reg_alpha': 0.03796290823827359, 'reg_lambda': 0.009276222888748827, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  54%|█████▍    | 108/200 [01:19<01:05,  1.41it/s]

[I 2025-11-10 18:03:38,644] Trial 108 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.02715690893651777, 'n_estimators': 494, 'subsample': 0.9619070618286898, 'colsample_bytree': 0.8084961763014017, 'min_child_weight': 7, 'gamma': 3.5543124499747805, 'reg_alpha': 2.7112393313944487e-05, 'reg_lambda': 5.359205204515255e-06, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:03:38,821] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.027214304571992726, 'n_estimators': 856, 'subsample': 0.5537933509004677, 'colsample_bytree': 0.7921611456718685, 'min_child_weight': 6, 'gamma': 2.878414413327834, 'reg_alpha': 0.03783806536037681, 'reg_lambda': 0.012308728125163232, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  55%|█████▌    | 110/200 [01:21<01:33,  1.04s/it]

[I 2025-11-10 18:03:41,004] Trial 109 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.24961947783142144, 'n_estimators': 735, 'subsample': 0.511214994336507, 'colsample_bytree': 0.8201845056933617, 'min_child_weight': 7, 'gamma': 3.5715758933222963, 'reg_alpha': 2.5425489004793236e-05, 'reg_lambda': 0.14121744800101796, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  56%|█████▌    | 111/200 [01:22<01:15,  1.18it/s]

[I 2025-11-10 18:03:41,411] Trial 112 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2650377650147898, 'n_estimators': 565, 'subsample': 0.6575140175229173, 'colsample_bytree': 0.8308138585940977, 'min_child_weight': 8, 'gamma': 3.387438693271095, 'reg_alpha': 1.5498564108292294e-08, 'reg_lambda': 3.940771500316755e-05, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  56%|█████▋    | 113/200 [01:22<00:48,  1.80it/s]

[I 2025-11-10 18:03:41,846] Trial 110 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.04204960385457983, 'n_estimators': 868, 'subsample': 0.5091526234811883, 'colsample_bytree': 0.598468118505049, 'min_child_weight': 7, 'gamma': 3.5704885160437714, 'reg_alpha': 0.0005414110714391149, 'reg_lambda': 4.3899404109590084e-05, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:03:42,008] Trial 111 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.012305649732428372, 'n_estimators': 736, 'subsample': 0.6743076518527373, 'colsample_bytree': 0.5800631802385798, 'min_child_weight': 6, 'gamma': 3.380489287457744, 'reg_alpha': 1.3270868510949007e-07, 'reg_lambda': 6.045564236802418e-05, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  57%|█████▋    | 114/200 [01:23<00:54,  1.57it/s]

[I 2025-11-10 18:03:42,839] Trial 116 pruned.

Best trial: 2. Best value: 0.5:  57%|█████▊    | 115/200 [01:23<00:43,  1.93it/s]

[I 2025-11-10 18:03:43,073] Trial 113 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.011888753362178652, 'n_estimators': 434, 'subsample': 0.5336336988508411, 'colsample_bytree': 0.5985807773159116, 'min_child_weight': 8, 'gamma': 4.4818423288225056, 'reg_alpha': 0.000535727932064576, 'reg_lambda': 4.471257253711265e-05, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  58%|█████▊    | 116/200 [01:25<01:14,  1.13it/s]

[I 2025-11-10 18:03:44,807] Trial 114 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.041161711289103356, 'n_estimators': 733, 'subsample': 0.5359446551153085, 'colsample_bytree': 0.7204572343502548, 'min_child_weight': 6, 'gamma': 3.383798016456522, 'reg_alpha': 0.0006423363232589246, 'reg_lambda': 0.02836671942299337, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  58%|█████▊    | 117/200 [01:26<01:08,  1.22it/s]

[I 2025-11-10 18:03:45,490] Trial 115 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03565640584186329, 'n_estimators': 800, 'subsample': 0.5362531703436593, 'colsample_bytree': 0.7710984385249771, 'min_child_weight': 6, 'gamma': 3.142544743210896, 'reg_alpha': 0.000637735239924925, 'reg_lambda': 0.029101360929454798, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  59%|█████▉    | 118/200 [01:26<01:00,  1.36it/s]

[I 2025-11-10 18:03:46,021] Trial 118 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.041213366535586146, 'n_estimators': 666, 'subsample': 0.7395183322731312, 'colsample_bytree': 0.7286329540539863, 'min_child_weight': 6, 'gamma': 3.9119289810327396, 'reg_alpha': 3.7917405342837394e-08, 'reg_lambda': 0.028715155070310062, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  60%|█████▉    | 119/200 [01:27<00:52,  1.54it/s]

[I 2025-11-10 18:03:46,471] Trial 117 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.08270575246885462, 'n_estimators': 793, 'subsample': 0.5383585739968559, 'colsample_bytree': 0.7302597503463676, 'min_child_weight': 6, 'gamma': 3.8781980939374527, 'reg_alpha': 0.011271195857094692, 'reg_lambda': 0.03438674905187443, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  60%|██████    | 120/200 [01:27<00:48,  1.64it/s]

[I 2025-11-10 18:03:46,985] Trial 121 pruned.

Best trial: 2. Best value: 0.5:  60%|██████    | 121/200 [01:28<00:52,  1.50it/s]

[I 2025-11-10 18:03:47,784] Trial 119 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03629420790618459, 'n_estimators': 649, 'subsample': 0.8302774429593994, 'colsample_bytree': 0.9598552553380858, 'min_child_weight': 9, 'gamma': 3.8414921966214366, 'reg_alpha': 0.010014062778488292, 'reg_lambda': 0.1120208368828277, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  61%|██████    | 122/200 [01:29<00:43,  1.79it/s]

[I 2025-11-10 18:03:48,093] Trial 120 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05209347737713316, 'n_estimators': 613, 'subsample': 0.7386231037440619, 'colsample_bytree': 0.6619296595385642, 'min_child_weight': 9, 'gamma': 3.876601864600394, 'reg_alpha': 0.01055034416404948, 'reg_lambda': 0.001828458972683982, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  62%|██████▏   | 123/200 [01:29<00:43,  1.79it/s]

[I 2025-11-10 18:03:48,655] Trial 123 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.16769094614997132, 'n_estimators': 385, 'subsample': 0.6951205175757332, 'colsample_bytree': 0.6200406397585467, 'min_child_weight': 9, 'gamma': 2.782293374969397, 'reg_alpha': 3.098539697740312, 'reg_lambda': 1.768577055304341e-07, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  62%|██████▏   | 124/200 [01:31<01:06,  1.15it/s]

[I 2025-11-10 18:03:50,251] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1614883396230528, 'n_estimators': 589, 'subsample': 0.6985289524539118, 'colsample_bytree': 0.751533210299244, 'min_child_weight': 5, 'gamma': 4.04257156153968, 'reg_alpha': 7.915959942291057, 'reg_lambda': 1.5935395941531558e-05, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  62%|██████▎   | 125/200 [01:31<01:00,  1.23it/s]

[I 2025-11-10 18:03:50,928] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.16476730254321137, 'n_estimators': 682, 'subsample': 0.9854334926537813, 'colsample_bytree': 0.7442433146118941, 'min_child_weight': 5, 'gamma': 3.6346411934887817, 'reg_alpha': 2.8577249312325907, 'reg_lambda': 0.00032821464308187113, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  63%|██████▎   | 126/200 [01:32<00:46,  1.60it/s]

[I 2025-11-10 18:03:51,116] Trial 122 finished with value: 0.47333333333333333 and parameters: {'max_depth': 5, 'learning_rate': 0.1429340059718977, 'n_estimators': 602, 'subsample': 0.9426221569058344, 'colsample_bytree': 0.9612237413099364, 'min_child_weight': 1, 'gamma': 4.056903835937589, 'reg_alpha': 4.806458705955066e-06, 'reg_lambda': 6.403451735049788, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  64%|██████▎   | 127/200 [01:32<00:42,  1.71it/s]

[I 2025-11-10 18:03:51,606] Trial 126 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.13476048877541627, 'n_estimators': 706, 'subsample': 0.7981517930207762, 'colsample_bytree': 0.7514003812558255, 'min_child_weight': 5, 'gamma': 2.028778044125511, 'reg_alpha': 1.0947881974004954, 'reg_lambda': 0.003762582015704359, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  64%|██████▍   | 128/200 [01:33<00:45,  1.60it/s]

[I 2025-11-10 18:03:52,330] Trial 130 pruned.

Best trial: 2. Best value: 0.5:  64%|██████▍   | 129/200 [01:34<00:47,  1.49it/s]

[I 2025-11-10 18:03:53,097] Trial 128 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.05923641017125875, 'n_estimators': 460, 'subsample': 0.5013654507552154, 'colsample_bytree': 0.6714143170869685, 'min_child_weight': 5, 'gamma': 1.981445929436957, 'reg_alpha': 1.0676869867801277, 'reg_lambda': 0.0038532593096967543, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  65%|██████▌   | 130/200 [01:34<00:42,  1.64it/s]

[I 2025-11-10 18:03:53,574] Trial 127 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.14233223257668814, 'n_estimators': 684, 'subsample': 0.7228361757520445, 'colsample_bytree': 0.9370614797389113, 'min_child_weight': 5, 'gamma': 3.175065383357066, 'reg_alpha': 0.0037796125587895306, 'reg_lambda': 0.0006145687553460747, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  66%|██████▌   | 131/200 [01:35<00:46,  1.48it/s]

[I 2025-11-10 18:03:54,404] Trial 129 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.05897421864039237, 'n_estimators': 707, 'subsample': 0.7230524887660519, 'colsample_bytree': 0.6770213192346692, 'min_child_weight': 5, 'gamma': 3.410914468004176, 'reg_alpha': 0.0037737139763272514, 'reg_lambda': 0.016332692059391505, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  66%|██████▌   | 132/200 [01:35<00:39,  1.72it/s]

[I 2025-11-10 18:03:54,762] Trial 131 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.05576937134785562, 'n_estimators': 475, 'subsample': 0.7196920564839844, 'colsample_bytree': 0.9848055199655339, 'min_child_weight': 5, 'gamma': 3.1945566311857183, 'reg_alpha': 7.234483324759183e-08, 'reg_lambda': 0.016011201894023205, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  66%|██████▋   | 133/200 [01:35<00:33,  2.01it/s]

[I 2025-11-10 18:03:55,062] Trial 133 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.033659413478397404, 'n_estimators': 311, 'subsample': 0.6660692749269084, 'colsample_bytree': 0.715154395777722, 'min_child_weight': 7, 'gamma': 0.32533948780568933, 'reg_alpha': 6.34052962260892e-08, 'reg_lambda': 0.015648015431711685, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  67%|██████▋   | 134/200 [01:36<00:26,  2.45it/s]

[I 2025-11-10 18:03:55,264] Trial 134 pruned.

Best trial: 2. Best value: 0.5:  68%|██████▊   | 135/200 [01:36<00:22,  2.86it/s]

[I 2025-11-10 18:03:55,476] Trial 135 pruned.
[I 2025-11-10 18:03:55,570] Trial 132 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.014260105259049768, 'n_estimators': 501, 'subsample': 0.6805511111082139, 'colsample_bytree': 0.7813958872251701, 'min_child_weight': 10, 'gamma': 4.898393382673034, 'reg_alpha': 1.147722353054698e-06, 'reg_lambda': 0.00011269433855187255, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  68%|██████▊   | 137/200 [01:38<00:42,  1.49it/s]

[I 2025-11-10 18:03:57,575] Trial 138 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.06798188200934185, 'n_estimators': 514, 'subsample': 0.7599402668876155, 'colsample_bytree': 0.62747894578038, 'min_child_weight': 10, 'gamma': 3.668798381540595, 'reg_alpha': 1.6413634698588202e-07, 'reg_lambda': 0.0006204163031656323, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  69%|██████▉   | 138/200 [01:39<00:41,  1.51it/s]

[I 2025-11-10 18:03:58,211] Trial 139 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.030156587585629273, 'n_estimators': 647, 'subsample': 0.7646811775151016, 'colsample_bytree': 0.6297367317851756, 'min_child_weight': 6, 'gamma': 4.711589766546427, 'reg_alpha': 5.255108738426965, 'reg_lambda': 0.007260918876946123, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  70%|██████▉   | 139/200 [01:39<00:35,  1.71it/s]

[I 2025-11-10 18:03:58,570] Trial 136 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.12330996367932452, 'n_estimators': 639, 'subsample': 0.7699630210386601, 'colsample_bytree': 0.6299864545945153, 'min_child_weight': 2, 'gamma': 3.0663367359232665, 'reg_alpha': 5.6043841475175915, 'reg_lambda': 0.0007505130835941586, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  70%|███████   | 140/200 [01:41<00:54,  1.11it/s]

[I 2025-11-10 18:04:00,316] Trial 140 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.02959075697316567, 'n_estimators': 647, 'subsample': 0.5653095658737717, 'colsample_bytree': 0.7655976470704903, 'min_child_weight': 7, 'gamma': 3.4509276136121416, 'reg_alpha': 4.946087422514705, 'reg_lambda': 0.0968914212453688, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  70%|███████   | 141/200 [01:41<00:41,  1.41it/s]

[I 2025-11-10 18:04:00,529] Trial 137 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10302978326698263, 'n_estimators': 911, 'subsample': 0.7637866302032137, 'colsample_bytree': 0.7608182118056259, 'min_child_weight': 2, 'gamma': 4.88559707860092, 'reg_alpha': 4.9537381157052565, 'reg_lambda': 0.07648546233324417, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  72%|███████▏  | 143/200 [01:42<00:35,  1.62it/s]

[I 2025-11-10 18:04:01,630] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.12077018650967711, 'n_estimators': 776, 'subsample': 0.7736349495274507, 'colsample_bytree': 0.7635538367088777, 'min_child_weight': 4, 'gamma': 3.2822130573283625, 'reg_alpha': 5.047536631156162, 'reg_lambda': 0.07343200582553874, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:04:01,756] Trial 142 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.0471991971704432, 'n_estimators': 721, 'subsample': 0.9211994207733292, 'colsample_bytree': 0.766694946004056, 'min_child_weight': 8, 'gamma': 3.51282855405336, 'reg_alpha': 6.472248069230479e-05, 'reg_lambda': 0.08578015334705139, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  72%|███████▏  | 144/200 [01:43<00:31,  1.80it/s]

[I 2025-11-10 18:04:02,153] Trial 145 pruned.
[I 2025-11-10 18:04:02,190] Trial 146 pruned.

Best trial: 2. Best value: 0.5:  73%|███████▎  | 146/200 [01:44<00:38,  1.41it/s]

[I 2025-11-10 18:04:03,941] Trial 144 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.045293092375478516, 'n_estimators': 776, 'subsample': 0.7308432348825812, 'colsample_bytree': 0.8616054454057924, 'min_child_weight': 8, 'gamma': 3.2763681538434755, 'reg_alpha': 8.228731194959913e-05, 'reg_lambda': 0.002500791030907474, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  74%|███████▎  | 147/200 [01:45<00:30,  1.71it/s]

[I 2025-11-10 18:04:04,139] Trial 143 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.08013966315602584, 'n_estimators': 917, 'subsample': 0.5165905081336938, 'colsample_bytree': 0.6471300979022888, 'min_child_weight': 8, 'gamma': 3.2587037947393864, 'reg_alpha': 7.380162505388061e-05, 'reg_lambda': 0.002722206254058993, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  74%|███████▍  | 148/200 [01:45<00:25,  2.00it/s]

[I 2025-11-10 18:04:04,398] Trial 149 pruned.

Best trial: 2. Best value: 0.5:  74%|███████▍  | 149/200 [01:45<00:22,  2.29it/s]

[I 2025-11-10 18:04:04,669] Trial 148 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07701837273372511, 'n_estimators': 368, 'subsample': 0.7123116032658212, 'colsample_bytree': 0.8929110861367417, 'min_child_weight': 1, 'gamma': 2.404573494117796, 'reg_alpha': 9.216883052313387, 'reg_lambda': 9.141573059361565e-08, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  75%|███████▌  | 150/200 [01:46<00:34,  1.43it/s]

[I 2025-11-10 18:04:06,037] Trial 151 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03356847557685892, 'n_estimators': 379, 'subsample': 0.7125044712761093, 'colsample_bytree': 0.8976994114105601, 'min_child_weight': 7, 'gamma': 1.2163428217413341, 'reg_alpha': 8.739443858213455, 'reg_lambda': 8.629550112857024e-08, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  76%|███████▌  | 151/200 [01:47<00:32,  1.52it/s]

[I 2025-11-10 18:04:06,591] Trial 150 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03329403058594336, 'n_estimators': 371, 'subsample': 0.743680208452871, 'colsample_bytree': 0.8752221721219787, 'min_child_weight': 1, 'gamma': 1.3724362900315672, 'reg_alpha': 9.078115541640415, 'reg_lambda': 4.066560948216693e-08, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  76%|███████▌  | 152/200 [01:48<00:37,  1.28it/s]

[I 2025-11-10 18:04:07,678] Trial 147 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08089206635615845, 'n_estimators': 839, 'subsample': 0.7315002005563448, 'colsample_bytree': 0.8970621573173437, 'min_child_weight': 1, 'gamma': 1.4361834439767274, 'reg_alpha': 9.639732708387891, 'reg_lambda': 4.741537899551054e-07, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  76%|███████▋  | 153/200 [01:48<00:30,  1.52it/s]

[I 2025-11-10 18:04:08,042] Trial 152 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.032350549011043374, 'n_estimators': 841, 'subsample': 0.6431295854655458, 'colsample_bytree': 0.7094454086965694, 'min_child_weight': 6, 'gamma': 2.8422390202195045, 'reg_alpha': 5.630878109289079e-07, 'reg_lambda': 0.20592890802868383, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  77%|███████▋  | 154/200 [01:49<00:27,  1.68it/s]

[I 2025-11-10 18:04:08,488] Trial 153 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.061852947980680154, 'n_estimators': 540, 'subsample': 0.7346391309392564, 'colsample_bytree': 0.6956337658674546, 'min_child_weight': 6, 'gamma': 2.8972394260600964, 'reg_alpha': 0.1547161975248362, 'reg_lambda': 0.00037762415394826973, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  78%|███████▊  | 155/200 [01:50<00:31,  1.45it/s]

[I 2025-11-10 18:04:09,404] Trial 154 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.06066032378142829, 'n_estimators': 674, 'subsample': 0.6923900261858585, 'colsample_bytree': 0.5066166269656565, 'min_child_weight': 6, 'gamma': 2.8449693718560525, 'reg_alpha': 0.001398688243663688, 'reg_lambda': 7.136385224667866, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  78%|███████▊  | 156/200 [01:52<00:46,  1.06s/it]

[I 2025-11-10 18:04:11,327] Trial 157 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05972834222100165, 'n_estimators': 674, 'subsample': 0.6923753473250261, 'colsample_bytree': 0.5540515006890453, 'min_child_weight': 5, 'gamma': 2.771620148792903, 'reg_alpha': 0.022466587677873098, 'reg_lambda': 7.326419605546738, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  78%|███████▊  | 157/200 [01:53<00:49,  1.14s/it]

[I 2025-11-10 18:04:12,677] Trial 159 pruned.

Best trial: 2. Best value: 0.5:  79%|███████▉  | 158/200 [01:54<00:47,  1.12s/it]

[I 2025-11-10 18:04:13,745] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.20545898165460377, 'n_estimators': 1436, 'subsample': 0.7030432660635696, 'colsample_bytree': 0.6949000632369173, 'min_child_weight': 6, 'gamma': 2.6785391571908868, 'reg_alpha': 0.0010444394838820081, 'reg_lambda': 8.924756400078389, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  80%|███████▉  | 159/200 [01:54<00:36,  1.14it/s]

[I 2025-11-10 18:04:14,057] Trial 156 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05875604008048188, 'n_estimators': 1472, 'subsample': 0.6911603251797804, 'colsample_bytree': 0.5648389540587978, 'min_child_weight': 6, 'gamma': 2.6976692100528323, 'reg_alpha': 0.12801936761806382, 'reg_lambda': 7.609997287362936, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  80%|████████  | 160/200 [01:55<00:32,  1.23it/s]

[I 2025-11-10 18:04:14,707] Trial 160 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.03765277399619553, 'n_estimators': 417, 'subsample': 0.7507755835518354, 'colsample_bytree': 0.8008569484759651, 'min_child_weight': 7, 'gamma': 4.986050225600539, 'reg_alpha': 1.0983573740841706e-07, 'reg_lambda': 3.033143302878758, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  80%|████████  | 161/200 [01:56<00:29,  1.34it/s]

[I 2025-11-10 18:04:15,297] Trial 158 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.038517603711891314, 'n_estimators': 1440, 'subsample': 0.6994222015742452, 'colsample_bytree': 0.6593354783604356, 'min_child_weight': 5, 'gamma': 2.7243608405812108, 'reg_alpha': 0.02273530794460253, 'reg_lambda': 9.82174595939627, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  81%|████████  | 162/200 [01:56<00:25,  1.49it/s]

[I 2025-11-10 18:04:15,787] Trial 161 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.03834631120782982, 'n_estimators': 423, 'subsample': 0.5018032444943631, 'colsample_bytree': 0.7489051449949763, 'min_child_weight': 7, 'gamma': 3.068862192434478, 'reg_alpha': 1.3274724849375531e-05, 'reg_lambda': 3.2221356679085207, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  82%|████████▏ | 163/200 [01:58<00:35,  1.04it/s]

[I 2025-11-10 18:04:17,424] Trial 162 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.054620368485998404, 'n_estimators': 745, 'subsample': 0.7471607612872924, 'colsample_bytree': 0.8039289544535779, 'min_child_weight': 7, 'gamma': 3.0830585798987094, 'reg_alpha': 0.2997657107423742, 'reg_lambda': 0.00026710082851831156, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  82%|████████▏ | 164/200 [01:58<00:30,  1.19it/s]

[I 2025-11-10 18:04:17,996] Trial 163 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05369661135452906, 'n_estimators': 731, 'subsample': 0.7196220274959467, 'colsample_bytree': 0.750118025441642, 'min_child_weight': 10, 'gamma': 2.5111280029799707, 'reg_alpha': 0.006445703114497045, 'reg_lambda': 0.00020321255611692321, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  82%|████████▎ | 165/200 [01:59<00:26,  1.34it/s]

[I 2025-11-10 18:04:18,514] Trial 164 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05387304352600946, 'n_estimators': 736, 'subsample': 0.9644231420072465, 'colsample_bytree': 0.5849893314407355, 'min_child_weight': 9, 'gamma': 3.5884981826233386, 'reg_alpha': 0.27229677013619846, 'reg_lambda': 1.3641431578725203, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  83%|████████▎ | 166/200 [02:01<00:42,  1.25s/it]

[I 2025-11-10 18:04:20,946] Trial 166 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05032105649918256, 'n_estimators': 815, 'subsample': 0.9764201019990513, 'colsample_bytree': 0.5900410055587287, 'min_child_weight': 9, 'gamma': 3.570149345416669, 'reg_alpha': 3.4133660369851494e-08, 'reg_lambda': 2.5257150510721484e-06, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  84%|████████▎ | 167/200 [02:02<00:31,  1.03it/s]

[I 2025-11-10 18:04:21,251] Trial 165 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.06657834292391165, 'n_estimators': 1290, 'subsample': 0.9854899202165853, 'colsample_bytree': 0.6114299877958322, 'min_child_weight': 10, 'gamma': 0.972284885302332, 'reg_alpha': 0.23991702990764513, 'reg_lambda': 0.00019108393323284022, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  84%|████████▍ | 168/200 [02:02<00:25,  1.27it/s]

[I 2025-11-10 18:04:21,616] Trial 167 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.01013570113649834, 'n_estimators': 808, 'subsample': 0.9653572734129952, 'colsample_bytree': 0.618895382731014, 'min_child_weight': 9, 'gamma': 1.1770790551776549, 'reg_alpha': 0.061894043483482764, 'reg_lambda': 1.8807622747118857, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  84%|████████▍ | 169/200 [02:03<00:21,  1.43it/s]

[I 2025-11-10 18:04:22,108] Trial 168 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.06871893049455749, 'n_estimators': 818, 'subsample': 0.9673780301223628, 'colsample_bytree': 0.6393555012941764, 'min_child_weight': 9, 'gamma': 0.9830339285586236, 'reg_alpha': 0.09703289701682717, 'reg_lambda': 1.8732926278443946e-06, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  85%|████████▌ | 170/200 [02:04<00:28,  1.05it/s]

[I 2025-11-10 18:04:23,667] Trial 169 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.06718895604553964, 'n_estimators': 608, 'subsample': 0.9930404732956963, 'colsample_bytree': 0.61386545896916, 'min_child_weight': 10, 'gamma': 4.517988628632851, 'reg_alpha': 0.6667332854378064, 'reg_lambda': 4.035170741956363, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  86%|████████▌ | 171/200 [02:04<00:22,  1.30it/s]

[I 2025-11-10 18:04:23,998] Trial 170 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.08683784313819413, 'n_estimators': 584, 'subsample': 0.7831128454810662, 'colsample_bytree': 0.7280386547165669, 'min_child_weight': 8, 'gamma': 1.0580350064935287, 'reg_alpha': 1.706928519530478, 'reg_lambda': 0.9022398954961572, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  86%|████████▌ | 172/200 [02:05<00:22,  1.23it/s]

[I 2025-11-10 18:04:24,908] Trial 172 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.17771160607977318, 'n_estimators': 613, 'subsample': 0.9542648995385695, 'colsample_bytree': 0.7238554459036051, 'min_child_weight': 10, 'gamma': 4.737208717548262, 'reg_alpha': 0.6200836841036595, 'reg_lambda': 3.8539265094264725, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  86%|████████▋ | 173/200 [02:06<00:17,  1.52it/s]

[I 2025-11-10 18:04:25,202] Trial 171 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.02590927937021032, 'n_estimators': 705, 'subsample': 0.6780393523171488, 'colsample_bytree': 0.9945196925303417, 'min_child_weight': 8, 'gamma': 1.0582387094047994, 'reg_alpha': 0.08380323150058419, 'reg_lambda': 1.613350153956174e-08, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  87%|████████▋ | 174/200 [02:08<00:28,  1.11s/it]

[I 2025-11-10 18:04:27,371] Trial 174 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.08490846381742001, 'n_estimators': 773, 'subsample': 0.9787549965055824, 'colsample_bytree': 0.7224385744046776, 'min_child_weight': 10, 'gamma': 1.3850251611436317, 'reg_alpha': 1.6878074153926815e-08, 'reg_lambda': 0.35591390090633007, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  88%|████████▊ | 175/200 [02:09<00:25,  1.00s/it]

[I 2025-11-10 18:04:28,127] Trial 175 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07274599845060786, 'n_estimators': 771, 'subsample': 0.9474023775861635, 'colsample_bytree': 0.68461606124598, 'min_child_weight': 10, 'gamma': 3.3957821526617336, 'reg_alpha': 3.0959075279552505e-06, 'reg_lambda': 0.04970232660488564, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  88%|████████▊ | 176/200 [02:09<00:20,  1.17it/s]

[I 2025-11-10 18:04:28,627] Trial 176 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09521176633897795, 'n_estimators': 787, 'subsample': 0.9816664859225784, 'colsample_bytree': 0.7367825843262533, 'min_child_weight': 10, 'gamma': 3.3954431660471744, 'reg_alpha': 2.2816569751325242e-06, 'reg_lambda': 1.246671877392545, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  88%|████████▊ | 177/200 [02:09<00:15,  1.49it/s]

[I 2025-11-10 18:04:28,882] Trial 173 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.09897745810797429, 'n_estimators': 1204, 'subsample': 0.6790609500117057, 'colsample_bytree': 0.7237582091023959, 'min_child_weight': 8, 'gamma': 3.37181719071143, 'reg_alpha': 1.287750098249861, 'reg_lambda': 0.0013058758825718205, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  89%|████████▉ | 178/200 [02:10<00:12,  1.70it/s]

[I 2025-11-10 18:04:29,273] Trial 180 pruned.

Best trial: 2. Best value: 0.5:  90%|████████▉ | 179/200 [02:12<00:20,  1.04it/s]

[I 2025-11-10 18:04:31,101] Trial 177 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.028455762065151595, 'n_estimators': 872, 'subsample': 0.739988090814338, 'colsample_bytree': 0.6875818111647006, 'min_child_weight': 10, 'gamma': 1.5576212331307289, 'reg_alpha': 3.54241760247019, 'reg_lambda': 0.0013570296235009022, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  90%|█████████ | 180/200 [02:13<00:20,  1.03s/it]

[I 2025-11-10 18:04:32,290] Trial 181 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.06386787504399723, 'n_estimators': 703, 'subsample': 0.5123055827369887, 'colsample_bytree': 0.6661201344188579, 'min_child_weight': 4, 'gamma': 3.7518350984094466, 'reg_alpha': 3.6537513832245985, 'reg_lambda': 0.007485737258813804, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  90%|█████████ | 181/200 [02:13<00:17,  1.10it/s]

[I 2025-11-10 18:04:32,928] Trial 178 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.14975855718271924, 'n_estimators': 1112, 'subsample': 0.5295143904136685, 'colsample_bytree': 0.7366490361133239, 'min_child_weight': 10, 'gamma': 3.757381361195358, 'reg_alpha': 3.495344549689169e-07, 'reg_lambda': 0.0012124573274016057, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  91%|█████████ | 182/200 [02:14<00:13,  1.34it/s]

[I 2025-11-10 18:04:33,285] Trial 182 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10949315579379179, 'n_estimators': 448, 'subsample': 0.5111652151796604, 'colsample_bytree': 0.9182727107666127, 'min_child_weight': 4, 'gamma': 3.7579756768497545, 'reg_alpha': 0.0001332487000675665, 'reg_lambda': 0.010974050709697673, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  92%|█████████▏| 183/200 [02:14<00:10,  1.58it/s]

[I 2025-11-10 18:04:33,657] Trial 179 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.11390515533812336, 'n_estimators': 1108, 'subsample': 0.5257151503685129, 'colsample_bytree': 0.6720697228176227, 'min_child_weight': 5, 'gamma': 3.8013878932070755, 'reg_alpha': 0.00038898253505942717, 'reg_lambda': 0.0014094577155924866, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  92%|█████████▏| 184/200 [02:16<00:16,  1.05s/it]

[I 2025-11-10 18:04:35,686] Trial 183 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.11438516743610176, 'n_estimators': 757, 'subsample': 0.8132797281440516, 'colsample_bytree': 0.6030117545008069, 'min_child_weight': 5, 'gamma': 3.222831132695736, 'reg_alpha': 7.94029422594562e-07, 'reg_lambda': 0.013193301443162688, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  92%|█████████▎| 185/200 [02:17<00:14,  1.07it/s]

[I 2025-11-10 18:04:36,348] Trial 184 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07623912681977077, 'n_estimators': 762, 'subsample': 0.9273846069383748, 'colsample_bytree': 0.6459488934111078, 'min_child_weight': 10, 'gamma': 1.290963024755814, 'reg_alpha': 0.00011835653137398975, 'reg_lambda': 0.45970178754460306, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  93%|█████████▎| 186/200 [02:18<00:12,  1.12it/s]

[I 2025-11-10 18:04:37,143] Trial 185 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.030935375903613435, 'n_estimators': 853, 'subsample': 0.9574057518738186, 'colsample_bytree': 0.6452860697314773, 'min_child_weight': 10, 'gamma': 1.6003047989029124, 'reg_alpha': 5.481166525536182e-06, 'reg_lambda': 0.03821309964615544, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  94%|█████████▎| 187/200 [02:18<00:09,  1.34it/s]

[I 2025-11-10 18:04:37,553] Trial 186 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0780012599808141, 'n_estimators': 859, 'subsample': 0.9561924817249555, 'colsample_bytree': 0.6480872871661303, 'min_child_weight': 10, 'gamma': 1.8285886220664942, 'reg_alpha': 1.1242477912145413e-05, 'reg_lambda': 0.6993822229907409, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  94%|█████████▍| 188/200 [02:20<00:13,  1.12s/it]

[I 2025-11-10 18:04:39,537] Trial 187 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07905549246798331, 'n_estimators': 859, 'subsample': 0.9542339359804015, 'colsample_bytree': 0.5752844782207323, 'min_child_weight': 10, 'gamma': 1.62274268113566, 'reg_alpha': 3.23594047861367e-05, 'reg_lambda': 0.5666120131480813, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  94%|█████████▍| 189/200 [02:21<00:10,  1.03it/s]

[I 2025-11-10 18:04:40,171] Trial 188 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0787693922497438, 'n_estimators': 860, 'subsample': 0.6585221365858557, 'colsample_bytree': 0.7048770660992101, 'min_child_weight': 9, 'gamma': 1.7291309832672377, 'reg_alpha': 1.3355809386201382e-05, 'reg_lambda': 0.5262771002242741, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  95%|█████████▌| 190/200 [02:21<00:08,  1.18it/s]

[I 2025-11-10 18:04:40,732] Trial 189 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0423394969328353, 'n_estimators': 791, 'subsample': 0.723515722232069, 'colsample_bytree': 0.7093764300908646, 'min_child_weight': 9, 'gamma': 1.461430599420737, 'reg_alpha': 9.755856869593703e-06, 'reg_lambda': 0.7748004475981188, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  96%|█████████▌| 191/200 [02:23<00:10,  1.17s/it]

[I 2025-11-10 18:04:42,651] Trial 192 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.042897691297552436, 'n_estimators': 530, 'subsample': 0.7249660389042991, 'colsample_bytree': 0.9314135523436332, 'min_child_weight': 7, 'gamma': 1.4084105755352598, 'reg_alpha': 0.0002676181998418478, 'reg_lambda': 1.7040520433324721e-07, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  96%|█████████▌| 192/200 [02:23<00:07,  1.06it/s]

[I 2025-11-10 18:04:43,061] Trial 191 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03535028455227542, 'n_estimators': 797, 'subsample': 0.6576109176744898, 'colsample_bytree': 0.7122266263695695, 'min_child_weight': 9, 'gamma': 1.4186170181047464, 'reg_alpha': 0.00022067438366094757, 'reg_lambda': 1.1202074217803673, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  96%|█████████▋| 193/200 [02:24<00:05,  1.18it/s]

[I 2025-11-10 18:04:43,681] Trial 190 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.035819971654883424, 'n_estimators': 1381, 'subsample': 0.6543281658707049, 'colsample_bytree': 0.7072468319931583, 'min_child_weight': 9, 'gamma': 1.3037416861844324, 'reg_alpha': 2.350596290320793e-05, 'reg_lambda': 0.316735912240692, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  97%|█████████▋| 194/200 [02:27<00:08,  1.36s/it]

[I 2025-11-10 18:04:46,238] Trial 194 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08707294531273024, 'n_estimators': 826, 'subsample': 0.9747173252578638, 'colsample_bytree': 0.6648095688979073, 'min_child_weight': 9, 'gamma': 1.8706588456500237, 'reg_alpha': 1.4875074388735483e-06, 'reg_lambda': 1.1287761439924449, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  98%|█████████▊| 195/200 [02:27<00:05,  1.06s/it]

[I 2025-11-10 18:04:46,602] Trial 196 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.08948259491832958, 'n_estimators': 656, 'subsample': 0.9894015301289264, 'colsample_bytree': 0.678575134735861, 'min_child_weight': 6, 'gamma': 2.957636389274469, 'reg_alpha': 4.533228905060369e-06, 'reg_lambda': 0.02262964634318579, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:04:46,628] Trial 195 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09049400742814344, 'n_estimators': 816, 'subsample': 0.9900050556179654, 'colsample_bytree': 0.6774745915609128, 'min_child_weight': 6, 'gamma': 1.843509753351152, 'reg_alpha': 3.4498689455787286e-06, 'reg_lambda': 0.32280384167852744, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  98%|█████████▊| 197/200 [02:28<00:02,  1.44it/s]

[I 2025-11-10 18:04:47,124] Trial 193 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03453510032974185, 'n_estimators': 1377, 'subsample': 0.988890767162484, 'colsample_bytree': 0.9366548557925041, 'min_child_weight': 7, 'gamma': 3.488111879572702, 'reg_alpha': 5.184582150017315e-05, 'reg_lambda': 0.02157103716075573, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  99%|█████████▉| 198/200 [02:28<00:01,  1.41it/s]

[I 2025-11-10 18:04:47,892] Trial 198 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.09860843833725685, 'n_estimators': 345, 'subsample': 0.970449199737768, 'colsample_bytree': 0.685176944428275, 'min_child_weight': 7, 'gamma': 3.926039723777998, 'reg_alpha': 5.878361752865643e-08, 'reg_lambda': 0.06035297985971333, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5: 100%|█████████▉| 199/200 [02:29<00:00,  1.45it/s]

[I 2025-11-10 18:04:48,531] Trial 197 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.014790589693914856, 'n_estimators': 679, 'subsample': 0.9923471979727156, 'colsample_bytree': 0.6739082914189953, 'min_child_weight': 6, 'gamma': 1.7126437844833575, 'reg_alpha': 5.092458514516219e-08, 'reg_lambda': 0.026101965214381805, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5: 100%|██████████| 200/200 [02:29<00:00,  1.34it/s]

[I 2025-11-10 18:04:48,726] Trial 199 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.07224718222149427, 'n_estimators': 691, 'subsample': 0.8577832407416164, 'colsample_bytree': 0.6935516106267423, 'min_child_weight': 7, 'gamma': 1.6907342105752943, 'reg_alpha': 5.25900204195491e-08, 'reg_lambda': 1.9239443819771196, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

[I 2025-11-10 18:04:49,725] A new study created in memory with name: 3_3_roc_auc
Best trial: 2. Best value: 0.5:   0%|          | 1/200 [00:04<13:50,  4.17s/it]

[I 2025-11-10 18:04:53,890] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.04335257201041846, 'n_estimators': 958, 'subsample': 0.6858539721239113, 'colsample_bytree': 0.9197544377682547, 'min_child_weight': 7, 'gamma': 0.347176589910711, 'reg_alpha': 0.23822562890886978, 'reg_lambda': 6.586648810592716e-05, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:04:53,963] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.02283146178288841, 'n_estimators': 1066, 'subsample': 0.7989579457072677, 'colsample_bytree': 0.5482212029539366, 'min_child_weight': 5, 'gamma': 1.2076231693396315, 'reg_alpha': 3.496700831907736e-06, 'reg_lambda': 3.4174558929502132, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 0. Best value: 0.517895:   2%|▏         | 3/200 [00:05<04:37,  1.41s/it]

[I 2025-11-10 18:04:54,767] Trial 0 finished with value: 0.5178947368421053 and parameters: {'max_depth': 6, 'learning_rate': 0.19116624513891853, 'n_estimators': 1071, 'subsample': 0.8820599828378326, 'colsample_bytree': 0.8374309692912214, 'min_child_weight': 2, 'gamma': 0.4715474306020717, 'reg_alpha': 0.020886182965166852, 'reg_lambda': 0.02634503420972897, 'max_delta_step': 3}. Best is trial 0 with value: 0.5178947368421053.

Best trial: 0. Best value: 0.517895:   2%|▏         | 4/200 [00:05<03:17,  1.01s/it]

[I 2025-11-10 18:04:55,032] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.027743763316429, 'n_estimators': 1372, 'subsample': 0.6241273986219342, 'colsample_bytree': 0.5100568476680063, 'min_child_weight': 8, 'gamma': 1.7729333868818753, 'reg_alpha': 1.8434148012727852e-07, 'reg_lambda': 0.021072626953271244, 'max_delta_step': 7}. Best is trial 0 with value: 0.5178947368421053.

Best trial: 0. Best value: 0.517895:   2%|▎         | 5/200 [00:06<03:25,  1.05s/it]

[I 2025-11-10 18:04:56,168] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.023810211924642798, 'n_estimators': 359, 'subsample': 0.9950520320879808, 'colsample_bytree': 0.5147034330721091, 'min_child_weight': 7, 'gamma': 2.50768234619535, 'reg_alpha': 0.3814390176161791, 'reg_lambda': 1.0694617986536198e-05, 'max_delta_step': 4}. Best is trial 0 with value: 0.5178947368421053.

Best trial: 0. Best value: 0.517895:   3%|▎         | 6/200 [00:07<03:24,  1.05s/it]

[I 2025-11-10 18:04:57,225] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.12797903112145068, 'n_estimators': 866, 'subsample': 0.5120368906316073, 'colsample_bytree': 0.6202888685543851, 'min_child_weight': 7, 'gamma': 4.610340312953413, 'reg_alpha': 0.012397951839047681, 'reg_lambda': 0.0003581464309832495, 'max_delta_step': 2}. Best is trial 0 with value: 0.5178947368421053.

Best trial: 4. Best value: 0.539357:   4%|▎         | 7/200 [00:09<03:56,  1.23s/it]

[I 2025-11-10 18:04:58,833] Trial 4 finished with value: 0.5393567251461988 and parameters: {'max_depth': 5, 'learning_rate': 0.11384267656732754, 'n_estimators': 870, 'subsample': 0.6172020163434082, 'colsample_bytree': 0.7444473791786548, 'min_child_weight': 1, 'gamma': 2.944606392252886, 'reg_alpha': 0.0003012295478489349, 'reg_lambda': 0.001998925671386849, 'max_delta_step': 0}. Best is trial 4 with value: 0.5393567251461988.

Best trial: 4. Best value: 0.539357:   4%|▍         | 8/200 [00:11<05:27,  1.71s/it]

[I 2025-11-10 18:05:01,605] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.012571021703521649, 'n_estimators': 700, 'subsample': 0.758319704599447, 'colsample_bytree': 0.7679239741523227, 'min_child_weight': 5, 'gamma': 3.656817669241401, 'reg_alpha': 8.147869635883666e-05, 'reg_lambda': 0.09477789594076516, 'max_delta_step': 6}. Best is trial 4 with value: 0.5393567251461988.

Best trial: 7. Best value: 0.59807:   4%|▍         | 9/200 [00:12<04:17,  1.35s/it]

[I 2025-11-10 18:05:02,144] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.05057710992046362, 'n_estimators': 1250, 'subsample': 0.8559024056780468, 'colsample_bytree': 0.8765601208655305, 'min_child_weight': 7, 'gamma': 2.105095611430421, 'reg_alpha': 2.1138504610009214e-05, 'reg_lambda': 0.03946717763982064, 'max_delta_step': 8}. Best is trial 4 with value: 0.5393567251461988.
[I 2025-11-10 18:05:02,174] Trial 7 finished with value: 0.5980701754385964 and parameters: {'max_depth': 3, 'learning_rate': 0.020203938150782804, 'n_estimators': 1272, 'subsample': 0.5683278903873585, 'colsample_bytree': 0.6670665686102738, 'min_child_weight': 1, 'gamma': 4.673704476154641, 'reg_alpha': 0.002014849811221654, 'reg_lambda': 1.09410326763745e-08, 'max_delta_step': 7}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:   6%|▌         | 11/200 [00:12<02:29,  1.26it/s]

[I 2025-11-10 18:05:02,458] Trial 8 finished with value: 0.5104873294346979 and parameters: {'max_depth': 10, 'learning_rate': 0.27199330157569535, 'n_estimators': 1218, 'subsample': 0.9429079300532305, 'colsample_bytree': 0.9226076502105472, 'min_child_weight': 2, 'gamma': 1.4367495830334864, 'reg_alpha': 2.259546020735625e-05, 'reg_lambda': 0.019819440745799916, 'max_delta_step': 9}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:   6%|▌         | 12/200 [00:14<03:25,  1.09s/it]

[I 2025-11-10 18:05:04,460] Trial 12 finished with value: 0.525204678362573 and parameters: {'max_depth': 3, 'learning_rate': 0.06946345982498013, 'n_estimators': 451, 'subsample': 0.5367143169697667, 'colsample_bytree': 0.7252358295022504, 'min_child_weight': 2, 'gamma': 3.427883014668995, 'reg_alpha': 0.008366354197673963, 'reg_lambda': 0.003217414820969473, 'max_delta_step': 5}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:   6%|▋         | 13/200 [00:16<03:51,  1.24s/it]

[I 2025-11-10 18:05:06,095] Trial 14 finished with value: 0.5458674463937621 and parameters: {'max_depth': 8, 'learning_rate': 0.09853709374269264, 'n_estimators': 642, 'subsample': 0.5466057926700602, 'colsample_bytree': 0.6794384982495321, 'min_child_weight': 1, 'gamma': 4.998646790916169, 'reg_alpha': 0.0013003202733891082, 'reg_lambda': 2.8897429755695193e-08, 'max_delta_step': 0}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:   7%|▋         | 14/200 [00:17<03:51,  1.24s/it]

[I 2025-11-10 18:05:07,356] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.048101891230365804, 'n_estimators': 1450, 'subsample': 0.5256482777322457, 'colsample_bytree': 0.7364266246467337, 'min_child_weight': 9, 'gamma': 2.807571697044697, 'reg_alpha': 2.5733797301771316e-07, 'reg_lambda': 4.462921177315985e-08, 'max_delta_step': 5}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:   8%|▊         | 16/200 [00:18<02:40,  1.15it/s]

[I 2025-11-10 18:05:08,342] Trial 13 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.01345224392876749, 'n_estimators': 1494, 'subsample': 0.5075287982861736, 'colsample_bytree': 0.9961603049964893, 'min_child_weight': 10, 'gamma': 4.966128782152918, 'reg_alpha': 1.0848194782868527e-08, 'reg_lambda': 1.1391083249505399e-08, 'max_delta_step': 10}. Best is trial 7 with value: 0.5980701754385964.
[I 2025-11-10 18:05:08,464] Trial 15 finished with value: 0.532943469785575 and parameters: {'max_depth': 8, 'learning_rate': 0.10050601220493334, 'n_estimators': 666, 'subsample': 0.6127131378273446, 'colsample_bytree': 0.674427414181051, 'min_child_weight': 1, 'gamma': 4.698754081697391, 'reg_alpha': 0.0009629543851803955, 'reg_lambda': 2.3668150198963568e-08, 'max_delta_step': 0}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:   8%|▊         | 17/200 [00:18<02:04,  1.47it/s]

[I 2025-11-10 18:05:08,671] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.011265450881707502, 'n_estimators': 597, 'subsample': 0.5968545905860277, 'colsample_bytree': 0.6471200396844944, 'min_child_weight': 4, 'gamma': 4.922172509560861, 'reg_alpha': 5.841043210524962, 'reg_lambda': 1.1706098972278247e-08, 'max_delta_step': 10}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:   9%|▉         | 18/200 [00:20<02:58,  1.02it/s]

[I 2025-11-10 18:05:10,379] Trial 17 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.010194996313517602, 'n_estimators': 681, 'subsample': 0.6154535216487745, 'colsample_bytree': 0.6370063285028286, 'min_child_weight': 4, 'gamma': 4.9632145451861165, 'reg_alpha': 9.936307677492868, 'reg_lambda': 1.3167543689089047e-08, 'max_delta_step': 10}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:  10%|█         | 21/200 [00:21<01:32,  1.94it/s]

[I 2025-11-10 18:05:11,070] Trial 20 finished with value: 0.582261208576998 and parameters: {'max_depth': 7, 'learning_rate': 0.07519222217644828, 'n_estimators': 493, 'subsample': 0.6787588618540332, 'colsample_bytree': 0.5963549994664932, 'min_child_weight': 3, 'gamma': 4.054959025253514, 'reg_alpha': 0.0008913138466874344, 'reg_lambda': 1.3352474634390465e-06, 'max_delta_step': 2}. Best is trial 7 with value: 0.5980701754385964.
[I 2025-11-10 18:05:11,086] Trial 18 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.09575275344373058, 'n_estimators': 626, 'subsample': 0.6170508621601077, 'colsample_bytree': 0.6372320718834313, 'min_child_weight': 4, 'gamma': 4.217364581456928, 'reg_alpha': 3.386256847085561, 'reg_lambda': 4.970383817131957e-07, 'max_delta_step': 0}. Best is trial 7 with value: 0.5980701754385964.
[I 2025-11-10 18:05:11,202] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.08153959496239334, 'n_estimators': 596, 'subsample': 0.6804396161637754, 'colsample_bytree': 0.6043507753036433, 'min_child_weight': 4, 'gamma': 4.034800423037392, 'reg_alpha': 7.141050631814407, 'reg_lambda': 4.687648285821119e-07, 'max_delta_step': 2}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:  11%|█         | 22/200 [00:21<01:30,  1.97it/s]

[I 2025-11-10 18:05:11,692] Trial 21 finished with value: 0.5404873294346978 and parameters: {'max_depth': 7, 'learning_rate': 0.07174981825592744, 'n_estimators': 233, 'subsample': 0.6681397814269271, 'colsample_bytree': 0.5805733426338114, 'min_child_weight': 3, 'gamma': 4.038151291572335, 'reg_alpha': 0.0017887356323140883, 'reg_lambda': 1.1406389207126604e-06, 'max_delta_step': 2}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:  12%|█▏        | 23/200 [00:22<01:35,  1.85it/s]

[I 2025-11-10 18:05:12,324] Trial 24 finished with value: 0.5716374269005848 and parameters: {'max_depth': 7, 'learning_rate': 0.0323542489013284, 'n_estimators': 200, 'subsample': 0.6944167610079433, 'colsample_bytree': 0.5746840020058116, 'min_child_weight': 3, 'gamma': 4.161524735272556, 'reg_alpha': 0.0005831595967514879, 'reg_lambda': 4.0873383538007874e-07, 'max_delta_step': 1}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:  12%|█▏        | 24/200 [00:22<01:23,  2.11it/s]

[I 2025-11-10 18:05:12,621] Trial 23 finished with value: 0.5807992202729044 and parameters: {'max_depth': 7, 'learning_rate': 0.029388574548909724, 'n_estimators': 267, 'subsample': 0.7122614192715389, 'colsample_bytree': 0.5776595711630413, 'min_child_weight': 3, 'gamma': 3.9941935299931193, 'reg_alpha': 0.1321340901422606, 'reg_lambda': 9.572551816533507e-07, 'max_delta_step': 2}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:  13%|█▎        | 26/200 [00:23<01:18,  2.21it/s]

[I 2025-11-10 18:05:13,500] Trial 22 finished with value: 0.5536062378167641 and parameters: {'max_depth': 7, 'learning_rate': 0.036940281072610846, 'n_estimators': 489, 'subsample': 0.6792334874264678, 'colsample_bytree': 0.5799855265158644, 'min_child_weight': 3, 'gamma': 4.069023926391662, 'reg_alpha': 0.12597315736888529, 'reg_lambda': 6.206417045310519e-07, 'max_delta_step': 2}. Best is trial 7 with value: 0.5980701754385964.
[I 2025-11-10 18:05:13,614] Trial 26 finished with value: 0.5568031189083821 and parameters: {'max_depth': 7, 'learning_rate': 0.033259130014065726, 'n_estimators': 217, 'subsample': 0.7301557796951358, 'colsample_bytree': 0.5658585666409222, 'min_child_weight': 3, 'gamma': 3.3700461369001595, 'reg_alpha': 0.08521919287578908, 'reg_lambda': 4.049563465622252e-06, 'max_delta_step': 1}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:  14%|█▎        | 27/200 [00:24<01:22,  2.09it/s]

[I 2025-11-10 18:05:14,151] Trial 29 pruned.

Best trial: 7. Best value: 0.59807:  14%|█▍        | 28/200 [00:24<01:21,  2.11it/s]

[I 2025-11-10 18:05:14,613] Trial 30 pruned.
[I 2025-11-10 18:05:14,630] Trial 27 finished with value: 0.5720272904483431 and parameters: {'max_depth': 7, 'learning_rate': 0.019003693141652032, 'n_estimators': 346, 'subsample': 0.7339239717725156, 'colsample_bytree': 0.6900813241589768, 'min_child_weight': 3, 'gamma': 3.530520509810522, 'reg_alpha': 0.0962433692859777, 'reg_lambda': 4.394150640603042e-06, 'max_delta_step': 3}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:  15%|█▌        | 30/200 [00:25<01:02,  2.73it/s]

[I 2025-11-10 18:05:15,094] Trial 31 pruned.

Best trial: 7. Best value: 0.59807:  16%|█▌        | 31/200 [00:25<00:55,  3.04it/s]

[I 2025-11-10 18:05:15,301] Trial 25 finished with value: 0.5536062378167641 and parameters: {'max_depth': 7, 'learning_rate': 0.03304491092042615, 'n_estimators': 477, 'subsample': 0.5645455180224591, 'colsample_bytree': 0.6862916575104708, 'min_child_weight': 1, 'gamma': 3.4929662314839516, 'reg_alpha': 0.0833196437166344, 'reg_lambda': 1.122851307698436e-07, 'max_delta_step': 1}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:  16%|█▌        | 32/200 [00:26<01:09,  2.40it/s]

[I 2025-11-10 18:05:15,973] Trial 28 finished with value: 0.5365497076023391 and parameters: {'max_depth': 4, 'learning_rate': 0.01998959044561199, 'n_estimators': 337, 'subsample': 0.7392714113266661, 'colsample_bytree': 0.6966661875761023, 'min_child_weight': 2, 'gamma': 3.2924832337387198, 'reg_alpha': 0.07306249947384902, 'reg_lambda': 6.969925060766439e-06, 'max_delta_step': 7}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:  16%|█▋        | 33/200 [00:27<01:30,  1.84it/s]

[I 2025-11-10 18:05:16,856] Trial 35 pruned.

Best trial: 7. Best value: 0.59807:  17%|█▋        | 34/200 [00:27<01:18,  2.10it/s]

[I 2025-11-10 18:05:17,156] Trial 34 finished with value: 0.543840155945419 and parameters: {'max_depth': 9, 'learning_rate': 0.15380995628732724, 'n_estimators': 309, 'subsample': 0.7240787409362913, 'colsample_bytree': 0.8008574487275366, 'min_child_weight': 2, 'gamma': 3.705839053464719, 'reg_alpha': 0.02421858317576185, 'reg_lambda': 4.483346978495422e-06, 'max_delta_step': 3}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:  18%|█▊        | 35/200 [00:28<01:53,  1.46it/s]

[I 2025-11-10 18:05:18,369] Trial 36 finished with value: 0.5461988304093567 and parameters: {'max_depth': 9, 'learning_rate': 0.024653953857450662, 'n_estimators': 286, 'subsample': 0.6518393430978943, 'colsample_bytree': 0.6080545227025314, 'min_child_weight': 3, 'gamma': 4.4092677752860805, 'reg_alpha': 0.0033843945734617345, 'reg_lambda': 0.00028208400299636785, 'max_delta_step': 4}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:  19%|█▉        | 38/200 [00:29<01:06,  2.43it/s]

[I 2025-11-10 18:05:19,115] Trial 32 finished with value: 0.5490448343079922 and parameters: {'max_depth': 6, 'learning_rate': 0.16415978798322678, 'n_estimators': 759, 'subsample': 0.8376927488134616, 'colsample_bytree': 0.8131512185155262, 'min_child_weight': 2, 'gamma': 2.929363812446773, 'reg_alpha': 0.051344419218349605, 'reg_lambda': 9.624825507579716e-05, 'max_delta_step': 4}. Best is trial 7 with value: 0.5980701754385964.
[I 2025-11-10 18:05:19,204] Trial 38 pruned.
[I 2025-11-10 18:05:19,229] Trial 33 finished with value: 0.5373294346978558 and parameters: {'max_depth': 9, 'learning_rate': 0.06060574691192399, 'n_estimators': 782, 'subsample': 0.578342782788691, 'colsample_bytree': 0.8120287207890713, 'min_child_weight': 2, 'gamma': 0.8655065641655937, 'reg_alpha': 0.0001437728193136013, 'reg_lambda': 5.4776860244655016e-05, 'max_delta_step': 4}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:  20%|█▉        | 39/200 [00:29<01:06,  2.43it/s]

[I 2025-11-10 18:05:19,650] Trial 41 pruned.

Best trial: 7. Best value: 0.59807:  20%|██        | 40/200 [00:30<01:07,  2.38it/s]

[I 2025-11-10 18:05:20,092] Trial 39 pruned.

Best trial: 7. Best value: 0.59807:  20%|██        | 41/200 [00:30<00:58,  2.73it/s]

[I 2025-11-10 18:05:20,315] Trial 40 pruned.

Best trial: 7. Best value: 0.59807:  21%|██        | 42/200 [00:31<01:39,  1.58it/s]

[I 2025-11-10 18:05:21,637] Trial 44 finished with value: 0.551150097465887 and parameters: {'max_depth': 6, 'learning_rate': 0.026784893264337854, 'n_estimators': 206, 'subsample': 0.6491829640754744, 'colsample_bytree': 0.5023747390849423, 'min_child_weight': 3, 'gamma': 0.1456463479036536, 'reg_alpha': 0.0004702160405435468, 'reg_lambda': 1.6784080974655123e-06, 'max_delta_step': 1}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:  22%|██▏       | 43/200 [00:32<01:24,  1.86it/s]

[I 2025-11-10 18:05:21,936] Trial 37 finished with value: 0.5808966861598439 and parameters: {'max_depth': 6, 'learning_rate': 0.022705345053461803, 'n_estimators': 977, 'subsample': 0.6580370208082819, 'colsample_bytree': 0.6140932796296291, 'min_child_weight': 3, 'gamma': 4.384591629023475, 'reg_alpha': 1.1197353735471292, 'reg_lambda': 5.299314083059598e-05, 'max_delta_step': 4}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:  22%|██▏       | 44/200 [00:33<02:17,  1.14it/s]

[I 2025-11-10 18:05:23,651] Trial 45 finished with value: 0.5656920077972709 and parameters: {'max_depth': 6, 'learning_rate': 0.031851114618880044, 'n_estimators': 409, 'subsample': 0.6463272725006836, 'colsample_bytree': 0.5734324689131158, 'min_child_weight': 3, 'gamma': 4.650055080262533, 'reg_alpha': 1.2776021017061587e-05, 'reg_lambda': 2.387601688782809e-07, 'max_delta_step': 1}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 7. Best value: 0.59807:  22%|██▎       | 45/200 [00:35<02:30,  1.03it/s]

[I 2025-11-10 18:05:24,850] Trial 42 finished with value: 0.5799025341130604 and parameters: {'max_depth': 6, 'learning_rate': 0.0225487370755759, 'n_estimators': 1214, 'subsample': 0.6480229997323863, 'colsample_bytree': 0.5022990629045768, 'min_child_weight': 4, 'gamma': 0.03297886857285448, 'reg_alpha': 0.9869658263828683, 'reg_lambda': 1.8883054602495417e-07, 'max_delta_step': 8}. Best is trial 7 with value: 0.5980701754385964.

Best trial: 43. Best value: 0.600936:  23%|██▎       | 46/200 [00:35<02:20,  1.09it/s]

[I 2025-11-10 18:05:25,631] Trial 43 finished with value: 0.60093567251462 and parameters: {'max_depth': 10, 'learning_rate': 0.02183872009920273, 'n_estimators': 1254, 'subsample': 0.648241640398849, 'colsample_bytree': 0.7229804054366717, 'min_child_weight': 4, 'gamma': 2.1614698937875128, 'reg_alpha': 1.667371264628297, 'reg_lambda': 1.7026079721279765e-07, 'max_delta_step': 8}. Best is trial 43 with value: 0.60093567251462.

Best trial: 46. Best value: 0.658811:  24%|██▎       | 47/200 [00:37<02:36,  1.02s/it]

[I 2025-11-10 18:05:26,899] Trial 46 finished with value: 0.6588109161793373 and parameters: {'max_depth': 5, 'learning_rate': 0.020609048277589487, 'n_estimators': 1151, 'subsample': 0.649184054937723, 'colsample_bytree': 0.7152598998825737, 'min_child_weight': 4, 'gamma': 4.708766501776637, 'reg_alpha': 0.23175759261245987, 'reg_lambda': 1.333904609108763e-05, 'max_delta_step': 2}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  24%|██▍       | 48/200 [00:37<02:12,  1.15it/s]

[I 2025-11-10 18:05:27,417] Trial 49 pruned.

Best trial: 46. Best value: 0.658811:  24%|██▍       | 49/200 [00:40<03:21,  1.33s/it]

[I 2025-11-10 18:05:29,837] Trial 47 finished with value: 0.6043859649122807 and parameters: {'max_depth': 5, 'learning_rate': 0.021178894632997405, 'n_estimators': 1303, 'subsample': 0.8959880111920574, 'colsample_bytree': 0.7175221604153144, 'min_child_weight': 4, 'gamma': 3.8958268184815554, 'reg_alpha': 0.27269078499390664, 'reg_lambda': 0.00037099983070257536, 'max_delta_step': 2}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  25%|██▌       | 50/200 [00:40<02:39,  1.06s/it]

[I 2025-11-10 18:05:30,266] Trial 48 finished with value: 0.5787426900584796 and parameters: {'max_depth': 5, 'learning_rate': 0.0226900829270949, 'n_estimators': 1328, 'subsample': 0.6422090275262697, 'colsample_bytree': 0.5302873515912591, 'min_child_weight': 4, 'gamma': 2.191499064409627, 'reg_alpha': 0.28544829607070565, 'reg_lambda': 1.2928866427941997e-05, 'max_delta_step': 8}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  26%|██▌       | 51/200 [00:42<03:13,  1.30s/it]

[I 2025-11-10 18:05:32,115] Trial 51 finished with value: 0.5116959064327485 and parameters: {'max_depth': 5, 'learning_rate': 0.022724354344246467, 'n_estimators': 1136, 'subsample': 0.5868325430105967, 'colsample_bytree': 0.75870922001332, 'min_child_weight': 4, 'gamma': 1.5276551405365657, 'reg_alpha': 0.266244511134429, 'reg_lambda': 0.00023981173808462463, 'max_delta_step': 9}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  26%|██▌       | 52/200 [00:42<02:32,  1.03s/it]

[I 2025-11-10 18:05:32,516] Trial 50 finished with value: 0.5916959064327485 and parameters: {'max_depth': 10, 'learning_rate': 0.021794471439259677, 'n_estimators': 1331, 'subsample': 0.589137454680806, 'colsample_bytree': 0.722129588242636, 'min_child_weight': 4, 'gamma': 1.9439334708161453, 'reg_alpha': 2.2342148132890647, 'reg_lambda': 1.4445327651796718e-05, 'max_delta_step': 8}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  26%|██▋       | 53/200 [00:44<02:39,  1.08s/it]

[I 2025-11-10 18:05:33,727] Trial 55 pruned.

Best trial: 46. Best value: 0.658811:  27%|██▋       | 54/200 [00:45<03:03,  1.26s/it]

[I 2025-11-10 18:05:35,396] Trial 53 finished with value: 0.5378167641325536 and parameters: {'max_depth': 3, 'learning_rate': 0.04679676017496385, 'n_estimators': 1098, 'subsample': 0.9002862470883142, 'colsample_bytree': 0.7643457765107149, 'min_child_weight': 4, 'gamma': 1.6578135605031532, 'reg_alpha': 1.9775839699036682e-06, 'reg_lambda': 0.009928348716253298, 'max_delta_step': 9}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  28%|██▊       | 55/200 [00:46<02:22,  1.01it/s]

[I 2025-11-10 18:05:35,745] Trial 52 finished with value: 0.6370760233918128 and parameters: {'max_depth': 5, 'learning_rate': 0.04346104616782599, 'n_estimators': 1377, 'subsample': 0.5983015622803188, 'colsample_bytree': 0.7654802403361401, 'min_child_weight': 4, 'gamma': 1.453437330746147, 'reg_alpha': 5.650876768234678e-07, 'reg_lambda': 0.0018609409096838816, 'max_delta_step': 9}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  28%|██▊       | 56/200 [00:46<02:12,  1.08it/s]

[I 2025-11-10 18:05:36,521] Trial 57 pruned.

Best trial: 46. Best value: 0.658811:  28%|██▊       | 57/200 [00:47<01:50,  1.29it/s]

[I 2025-11-10 18:05:36,952] Trial 58 pruned.

Best trial: 46. Best value: 0.658811:  29%|██▉       | 58/200 [00:48<01:50,  1.29it/s]

[I 2025-11-10 18:05:37,734] Trial 59 pruned.

Best trial: 46. Best value: 0.658811:  30%|██▉       | 59/200 [00:48<01:53,  1.25it/s]

[I 2025-11-10 18:05:38,597] Trial 54 finished with value: 0.6517153996101366 and parameters: {'max_depth': 3, 'learning_rate': 0.012508176782991815, 'n_estimators': 1414, 'subsample': 0.8836516620418019, 'colsample_bytree': 0.7153417721126809, 'min_child_weight': 4, 'gamma': 4.631485005825357, 'reg_alpha': 1.7944245525633753, 'reg_lambda': 0.0011641451853684718, 'max_delta_step': 9}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  30%|███       | 60/200 [00:50<02:08,  1.09it/s]

[I 2025-11-10 18:05:39,781] Trial 62 pruned.

Best trial: 46. Best value: 0.658811:  30%|███       | 61/200 [00:51<02:13,  1.05it/s]

[I 2025-11-10 18:05:40,829] Trial 56 finished with value: 0.5514035087719298 and parameters: {'max_depth': 3, 'learning_rate': 0.012394971743094665, 'n_estimators': 1373, 'subsample': 0.889811034697912, 'colsample_bytree': 0.747893731290368, 'min_child_weight': 4, 'gamma': 1.6199831166051288, 'reg_alpha': 4.436186721992897e-05, 'reg_lambda': 0.623331652590512, 'max_delta_step': 9}. Best is trial 46 with value: 0.6588109161793373.
[I 2025-11-10 18:05:40,854] Trial 63 pruned.

Best trial: 46. Best value: 0.658811:  32%|███▏      | 63/200 [00:54<03:05,  1.36s/it]

[I 2025-11-10 18:05:44,471] Trial 60 finished with value: 0.573391812865497 and parameters: {'max_depth': 4, 'learning_rate': 0.02036754497234095, 'n_estimators': 1489, 'subsample': 0.964480775365386, 'colsample_bytree': 0.857470888528684, 'min_child_weight': 4, 'gamma': 1.8519775147545348, 'reg_alpha': 1.3299162491737114e-08, 'reg_lambda': 0.005292119790942544, 'max_delta_step': 8}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  32%|███▏      | 64/200 [00:55<02:31,  1.11s/it]

[I 2025-11-10 18:05:44,849] Trial 61 finished with value: 0.5764035087719298 and parameters: {'max_depth': 3, 'learning_rate': 0.03842364307999015, 'n_estimators': 1482, 'subsample': 0.9694867792205069, 'colsample_bytree': 0.7850976749625155, 'min_child_weight': 4, 'gamma': 2.623786764842363, 'reg_alpha': 3.146812106595034e-05, 'reg_lambda': 0.005415618855266753, 'max_delta_step': 9}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  32%|███▎      | 65/200 [00:55<02:20,  1.04s/it]

[I 2025-11-10 18:05:45,676] Trial 66 pruned.

Best trial: 46. Best value: 0.658811:  33%|███▎      | 66/200 [00:56<01:56,  1.15it/s]

[I 2025-11-10 18:05:46,091] Trial 67 pruned.

Best trial: 46. Best value: 0.658811:  34%|███▎      | 67/200 [00:56<01:35,  1.39it/s]

[I 2025-11-10 18:05:46,430] Trial 64 finished with value: 0.6161890838206627 and parameters: {'max_depth': 3, 'learning_rate': 0.020883217106804564, 'n_estimators': 1228, 'subsample': 0.8488115543751946, 'colsample_bytree': 0.7803275937222252, 'min_child_weight': 4, 'gamma': 4.808096265011428, 'reg_alpha': 6.438903150145298e-07, 'reg_lambda': 0.00014094147734064572, 'max_delta_step': 10}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  34%|███▍      | 68/200 [00:57<01:23,  1.58it/s]

[I 2025-11-10 18:05:46,848] Trial 68 pruned.

Best trial: 46. Best value: 0.658811:  34%|███▍      | 69/200 [00:57<01:23,  1.57it/s]

[I 2025-11-10 18:05:47,490] Trial 65 finished with value: 0.5778167641325536 and parameters: {'max_depth': 4, 'learning_rate': 0.019944735818999023, 'n_estimators': 1433, 'subsample': 0.9596551763957367, 'colsample_bytree': 0.7145563412540956, 'min_child_weight': 4, 'gamma': 2.6486672187567226, 'reg_alpha': 6.78596175114016e-07, 'reg_lambda': 0.00012598061159470187, 'max_delta_step': 10}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  35%|███▌      | 70/200 [00:58<01:13,  1.76it/s]

[I 2025-11-10 18:05:47,894] Trial 71 pruned.

Best trial: 46. Best value: 0.658811:  36%|███▌      | 71/200 [01:01<03:05,  1.44s/it]

[I 2025-11-10 18:05:51,421] Trial 70 finished with value: 0.6101656920077972 and parameters: {'max_depth': 3, 'learning_rate': 0.020053789838308793, 'n_estimators': 1156, 'subsample': 0.8588602993758327, 'colsample_bytree': 0.6665790708794576, 'min_child_weight': 4, 'gamma': 4.7763203611973255, 'reg_alpha': 1.3860135826383074e-06, 'reg_lambda': 0.00041664807555441937, 'max_delta_step': 10}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  36%|███▌      | 72/200 [01:02<02:31,  1.18s/it]

[I 2025-11-10 18:05:51,993] Trial 69 finished with value: 0.6475243664717348 and parameters: {'max_depth': 10, 'learning_rate': 0.020538372476076837, 'n_estimators': 1319, 'subsample': 0.9165108940016408, 'colsample_bytree': 0.66616152228165, 'min_child_weight': 4, 'gamma': 4.808851920768949, 'reg_alpha': 5.966578966065208e-08, 'reg_lambda': 0.00042820847346108465, 'max_delta_step': 8}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  36%|███▋      | 73/200 [01:03<02:33,  1.21s/it]

[I 2025-11-10 18:05:53,254] Trial 72 finished with value: 0.5931384015594541 and parameters: {'max_depth': 3, 'learning_rate': 0.02921266033958417, 'n_estimators': 1171, 'subsample': 0.8590877077399096, 'colsample_bytree': 0.6718856565615792, 'min_child_weight': 3, 'gamma': 4.80605953329896, 'reg_alpha': 7.723652482592404e-06, 'reg_lambda': 0.0005298516265374384, 'max_delta_step': 5}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  37%|███▋      | 74/200 [01:04<02:32,  1.21s/it]

[I 2025-11-10 18:05:54,471] Trial 73 finished with value: 0.6007992202729044 and parameters: {'max_depth': 3, 'learning_rate': 0.013433814702020852, 'n_estimators': 1263, 'subsample': 0.8445108379641256, 'colsample_bytree': 0.7358883190038844, 'min_child_weight': 3, 'gamma': 4.841042429806533, 'reg_alpha': 6.591113900950981e-06, 'reg_lambda': 0.0004632776738661552, 'max_delta_step': 9}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  38%|███▊      | 75/200 [01:06<03:06,  1.49s/it]

[I 2025-11-10 18:05:56,613] Trial 74 finished with value: 0.6394931773879142 and parameters: {'max_depth': 3, 'learning_rate': 0.025448156281972695, 'n_estimators': 1143, 'subsample': 0.9174426626923826, 'colsample_bytree': 0.665232238180736, 'min_child_weight': 4, 'gamma': 4.802942654755658, 'reg_alpha': 7.4405970541449825e-06, 'reg_lambda': 0.00046570609198543346, 'max_delta_step': 9}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  38%|███▊      | 76/200 [01:07<02:29,  1.21s/it]

[I 2025-11-10 18:05:57,158] Trial 75 finished with value: 0.6357017543859649 and parameters: {'max_depth': 3, 'learning_rate': 0.025387429587469115, 'n_estimators': 1143, 'subsample': 0.9168242412313632, 'colsample_bytree': 0.6325699280028264, 'min_child_weight': 4, 'gamma': 4.810556737660431, 'reg_alpha': 5.796412557314177e-08, 'reg_lambda': 0.0017604463722747843, 'max_delta_step': 9}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  38%|███▊      | 77/200 [01:08<02:40,  1.31s/it]

[I 2025-11-10 18:05:58,707] Trial 76 finished with value: 0.6441033138401558 and parameters: {'max_depth': 3, 'learning_rate': 0.015226653241693588, 'n_estimators': 1245, 'subsample': 0.9155596323483687, 'colsample_bytree': 0.634179643296974, 'min_child_weight': 4, 'gamma': 4.806573183701075, 'reg_alpha': 6.619845592094446e-08, 'reg_lambda': 0.0020077413446450178, 'max_delta_step': 9}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  39%|███▉      | 78/200 [01:09<02:00,  1.01it/s]

[I 2025-11-10 18:05:58,939] Trial 77 finished with value: 0.604083820662768 and parameters: {'max_depth': 5, 'learning_rate': 0.025735930394174156, 'n_estimators': 1032, 'subsample': 0.9102299130443737, 'colsample_bytree': 0.6291526190347102, 'min_child_weight': 4, 'gamma': 4.236203162000001, 'reg_alpha': 4.496007024120515e-07, 'reg_lambda': 0.0016632639039291454, 'max_delta_step': 10}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  40%|███▉      | 79/200 [01:11<02:56,  1.46s/it]

[I 2025-11-10 18:06:01,489] Trial 78 finished with value: 0.6022124756335282 and parameters: {'max_depth': 3, 'learning_rate': 0.025756100343624088, 'n_estimators': 1034, 'subsample': 0.9183724705319504, 'colsample_bytree': 0.6318602521061163, 'min_child_weight': 4, 'gamma': 4.203677116955006, 'reg_alpha': 6.827514914335344e-08, 'reg_lambda': 0.002481365861462495, 'max_delta_step': 9}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 46. Best value: 0.658811:  40%|████      | 80/200 [01:12<02:22,  1.19s/it]

[I 2025-11-10 18:06:02,048] Trial 79 finished with value: 0.5998732943469787 and parameters: {'max_depth': 3, 'learning_rate': 0.035321612801532044, 'n_estimators': 1021, 'subsample': 0.9173211547889689, 'colsample_bytree': 0.6482547483200592, 'min_child_weight': 4, 'gamma': 4.252864819352421, 'reg_alpha': 7.838807459045968e-08, 'reg_lambda': 0.0014896799976786615, 'max_delta_step': 9}. Best is trial 46 with value: 0.6588109161793373.

Best trial: 80. Best value: 0.677018:  40%|████      | 81/200 [01:12<01:59,  1.00s/it]

[I 2025-11-10 18:06:02,614] Trial 80 finished with value: 0.6770175438596491 and parameters: {'max_depth': 3, 'learning_rate': 0.2287131153942463, 'n_estimators': 919, 'subsample': 0.9203668491952359, 'colsample_bytree': 0.6383101543246537, 'min_child_weight': 5, 'gamma': 4.221536319280711, 'reg_alpha': 5.067286806337312e-08, 'reg_lambda': 0.001661791741439493, 'max_delta_step': 9}. Best is trial 80 with value: 0.6770175438596491.

Best trial: 80. Best value: 0.677018:  41%|████      | 82/200 [01:13<01:59,  1.01s/it]

[I 2025-11-10 18:06:03,658] Trial 81 finished with value: 0.646608187134503 and parameters: {'max_depth': 3, 'learning_rate': 0.035540221141962654, 'n_estimators': 1105, 'subsample': 0.9365603797118192, 'colsample_bytree': 0.6469470006399226, 'min_child_weight': 5, 'gamma': 4.502734034043382, 'reg_alpha': 8.424417782529783e-08, 'reg_lambda': 0.010047411980907117, 'max_delta_step': 9}. Best is trial 80 with value: 0.6770175438596491.

Best trial: 80. Best value: 0.677018:  42%|████▏     | 83/200 [01:16<02:46,  1.43s/it]

[I 2025-11-10 18:06:06,046] Trial 83 finished with value: 0.6454970760233919 and parameters: {'max_depth': 4, 'learning_rate': 0.017639271800176843, 'n_estimators': 923, 'subsample': 0.9409938982818289, 'colsample_bytree': 0.6910298213274334, 'min_child_weight': 5, 'gamma': 4.57655409089957, 'reg_alpha': 3.379575483734995e-08, 'reg_lambda': 0.018689744502807623, 'max_delta_step': 9}. Best is trial 80 with value: 0.6770175438596491.
[I 2025-11-10 18:06:06,069] Trial 84 finished with value: 0.6328654970760235 and parameters: {'max_depth': 3, 'learning_rate': 0.1969993225562566, 'n_estimators': 852, 'subsample': 0.9408041133203796, 'colsample_bytree': 0.5943989299033783, 'min_child_weight': 5, 'gamma': 4.5251173247522605, 'reg_alpha': 3.311008914116381e-08, 'reg_lambda': 0.00356252192954752, 'max_delta_step': 9}. Best is trial 80 with value: 0.6770175438596491.

Best trial: 80. Best value: 0.677018:  43%|████▎     | 86/200 [01:17<01:25,  1.33it/s]

[I 2025-11-10 18:06:06,841] Trial 82 finished with value: 0.6518713450292398 and parameters: {'max_depth': 3, 'learning_rate': 0.015386617175574805, 'n_estimators': 1216, 'subsample': 0.9406613800337286, 'colsample_bytree': 0.5922321078530445, 'min_child_weight': 5, 'gamma': 4.605474872476932, 'reg_alpha': 8.92124651183816e-08, 'reg_lambda': 0.013842502543419049, 'max_delta_step': 9}. Best is trial 80 with value: 0.6770175438596491.
[I 2025-11-10 18:06:06,990] Trial 86 pruned.

Best trial: 80. Best value: 0.677018:  44%|████▎     | 87/200 [01:17<01:08,  1.65it/s]

[I 2025-11-10 18:06:07,184] Trial 87 pruned.

Best trial: 80. Best value: 0.677018:  44%|████▍     | 89/200 [01:18<00:50,  2.19it/s]

[I 2025-11-10 18:06:07,694] Trial 85 finished with value: 0.6717543859649124 and parameters: {'max_depth': 3, 'learning_rate': 0.2487428593475423, 'n_estimators': 908, 'subsample': 0.9426040509679133, 'colsample_bytree': 0.5895764276827462, 'min_child_weight': 5, 'gamma': 4.538954825837518, 'reg_alpha': 3.833837850847098e-08, 'reg_lambda': 0.016062507736704104, 'max_delta_step': 9}. Best is trial 80 with value: 0.6770175438596491.
[I 2025-11-10 18:06:07,836] Trial 88 pruned.

Best trial: 80. Best value: 0.677018:  46%|████▌     | 91/200 [01:21<01:42,  1.06it/s]

[I 2025-11-10 18:06:11,142] Trial 90 finished with value: 0.6706432748538013 and parameters: {'max_depth': 3, 'learning_rate': 0.23673201995527815, 'n_estimators': 916, 'subsample': 0.9833087872078858, 'colsample_bytree': 0.6207353280108536, 'min_child_weight': 5, 'gamma': 4.632031349870921, 'reg_alpha': 1.0962648847281194e-07, 'reg_lambda': 0.013610015784586772, 'max_delta_step': 8}. Best is trial 80 with value: 0.6770175438596491.
[I 2025-11-10 18:06:11,288] Trial 92 finished with value: 0.6706432748538013 and parameters: {'max_depth': 3, 'learning_rate': 0.25349941207016174, 'n_estimators': 798, 'subsample': 0.9825281312462496, 'colsample_bytree': 0.6201468742805075, 'min_child_weight': 5, 'gamma': 4.3792811978288055, 'reg_alpha': 1.1735116190128527e-08, 'reg_lambda': 0.05870445388395325, 'max_delta_step': 8}. Best is trial 80 with value: 0.6770175438596491.

Best trial: 80. Best value: 0.677018:  46%|████▌     | 92/200 [01:22<01:28,  1.22it/s]

[I 2025-11-10 18:06:11,796] Trial 91 finished with value: 0.6706432748538013 and parameters: {'max_depth': 4, 'learning_rate': 0.011289440343328391, 'n_estimators': 935, 'subsample': 0.953437268738038, 'colsample_bytree': 0.5569000272821306, 'min_child_weight': 5, 'gamma': 4.964488783803491, 'reg_alpha': 1.0739197494787059e-07, 'reg_lambda': 0.07249814017518111, 'max_delta_step': 8}. Best is trial 80 with value: 0.6770175438596491.

Best trial: 80. Best value: 0.677018:  46%|████▋     | 93/200 [01:22<01:08,  1.56it/s]

[I 2025-11-10 18:06:12,021] Trial 89 finished with value: 0.6661988304093568 and parameters: {'max_depth': 4, 'learning_rate': 0.015346307741261354, 'n_estimators': 1110, 'subsample': 0.9522249045824267, 'colsample_bytree': 0.6858892793700316, 'min_child_weight': 5, 'gamma': 4.97655826165408, 'reg_alpha': 1.1852096472792305e-07, 'reg_lambda': 0.029201750333861742, 'max_delta_step': 8}. Best is trial 80 with value: 0.6770175438596491.

Best trial: 80. Best value: 0.677018:  47%|████▋     | 94/200 [01:25<02:17,  1.30s/it]

[I 2025-11-10 18:06:14,882] Trial 93 finished with value: 0.6706432748538013 and parameters: {'max_depth': 4, 'learning_rate': 0.23765666643744143, 'n_estimators': 806, 'subsample': 0.9872028428583568, 'colsample_bytree': 0.6210075404397759, 'min_child_weight': 5, 'gamma': 4.349660247659794, 'reg_alpha': 1.4523058334325316e-08, 'reg_lambda': 0.14035530848147323, 'max_delta_step': 7}. Best is trial 80 with value: 0.6770175438596491.
[I 2025-11-10 18:06:14,915] Trial 94 finished with value: 0.6728654970760235 and parameters: {'max_depth': 3, 'learning_rate': 0.24664741797045453, 'n_estimators': 813, 'subsample': 0.9536029809938551, 'colsample_bytree': 0.554601222063815, 'min_child_weight': 5, 'gamma': 4.326745327701578, 'reg_alpha': 1.1210745631841213e-08, 'reg_lambda': 0.05196216680062831, 'max_delta_step': 7}. Best is trial 80 with value: 0.6770175438596491.

Best trial: 80. Best value: 0.677018:  48%|████▊     | 96/200 [01:25<01:25,  1.22it/s]

[I 2025-11-10 18:06:15,385] Trial 95 finished with value: 0.6706432748538013 and parameters: {'max_depth': 3, 'learning_rate': 0.22688409549225075, 'n_estimators': 781, 'subsample': 0.9852859238949431, 'colsample_bytree': 0.6181213437258475, 'min_child_weight': 5, 'gamma': 4.355906686877318, 'reg_alpha': 2.8648201490745907e-07, 'reg_lambda': 0.11258686890225111, 'max_delta_step': 7}. Best is trial 80 with value: 0.6770175438596491.

Best trial: 80. Best value: 0.677018:  48%|████▊     | 97/200 [01:26<01:12,  1.42it/s]

[I 2025-11-10 18:06:15,727] Trial 96 finished with value: 0.6706432748538014 and parameters: {'max_depth': 4, 'learning_rate': 0.23141308700880434, 'n_estimators': 819, 'subsample': 0.9803905021405797, 'colsample_bytree': 0.5564988858570279, 'min_child_weight': 5, 'gamma': 4.660761780201622, 'reg_alpha': 1.2040244837768303e-08, 'reg_lambda': 0.1026520433612276, 'max_delta_step': 7}. Best is trial 80 with value: 0.6770175438596491.

Best trial: 80. Best value: 0.677018:  49%|████▉     | 98/200 [01:26<01:04,  1.58it/s]

[I 2025-11-10 18:06:16,168] Trial 99 pruned.

Best trial: 80. Best value: 0.677018:  50%|████▉     | 99/200 [01:28<01:44,  1.04s/it]

[I 2025-11-10 18:06:18,292] Trial 97 finished with value: 0.6706432748538013 and parameters: {'max_depth': 4, 'learning_rate': 0.24677931283502716, 'n_estimators': 763, 'subsample': 0.9829336140559184, 'colsample_bytree': 0.6223888091774263, 'min_child_weight': 5, 'gamma': 4.375579985280935, 'reg_alpha': 1.7579897288209498e-08, 'reg_lambda': 0.11300489702278074, 'max_delta_step': 7}. Best is trial 80 with value: 0.6770175438596491.

Best trial: 80. Best value: 0.677018:  50%|█████     | 100/200 [01:28<01:20,  1.23it/s]

[I 2025-11-10 18:06:18,513] Trial 98 finished with value: 0.6706432748538013 and parameters: {'max_depth': 4, 'learning_rate': 0.2419197559564632, 'n_estimators': 789, 'subsample': 0.9893077415073408, 'colsample_bytree': 0.5493658662246965, 'min_child_weight': 5, 'gamma': 4.337832245850249, 'reg_alpha': 1.0191019164152065e-08, 'reg_lambda': 0.15839090312240542, 'max_delta_step': 7}. Best is trial 80 with value: 0.6770175438596491.

Best trial: 80. Best value: 0.677018:  50%|█████     | 101/200 [01:29<01:10,  1.41it/s]

[I 2025-11-10 18:06:18,974] Trial 102 pruned.

Best trial: 80. Best value: 0.677018:  51%|█████     | 102/200 [01:29<00:56,  1.74it/s]

[I 2025-11-10 18:06:19,213] Trial 103 pruned.
[I 2025-11-10 18:06:19,295] Trial 100 finished with value: 0.6706432748538013 and parameters: {'max_depth': 4, 'learning_rate': 0.24948244233559524, 'n_estimators': 806, 'subsample': 0.9853210348667757, 'colsample_bytree': 0.5566763514959487, 'min_child_weight': 5, 'gamma': 4.3426997871381, 'reg_alpha': 1.402994625528348e-08, 'reg_lambda': 0.15385442837705132, 'max_delta_step': 7}. Best is trial 80 with value: 0.6770175438596491.

Best trial: 80. Best value: 0.677018:  52%|█████▏    | 104/200 [01:29<00:35,  2.67it/s]

[I 2025-11-10 18:06:19,480] Trial 101 finished with value: 0.6706432748538014 and parameters: {'max_depth': 4, 'learning_rate': 0.23993908848764695, 'n_estimators': 732, 'subsample': 0.9992950283665498, 'colsample_bytree': 0.5217062386322119, 'min_child_weight': 5, 'gamma': 4.367325218328755, 'reg_alpha': 1.9487970536703934e-08, 'reg_lambda': 0.09143461472586005, 'max_delta_step': 7}. Best is trial 80 with value: 0.6770175438596491.

Best trial: 80. Best value: 0.677018:  52%|█████▎    | 105/200 [01:32<01:34,  1.01it/s]

[I 2025-11-10 18:06:22,386] Trial 104 finished with value: 0.6595321637426901 and parameters: {'max_depth': 4, 'learning_rate': 0.2058913513006629, 'n_estimators': 815, 'subsample': 0.9984784622779319, 'colsample_bytree': 0.5171902865384836, 'min_child_weight': 5, 'gamma': 4.082475321525488, 'reg_alpha': 2.4549316705132653e-08, 'reg_lambda': 0.30154977241310404, 'max_delta_step': 7}. Best is trial 80 with value: 0.6770175438596491.

Best trial: 105. Best value: 0.683977:  53%|█████▎    | 106/200 [01:33<01:19,  1.19it/s]

[I 2025-11-10 18:06:22,793] Trial 105 finished with value: 0.6839766081871345 and parameters: {'max_depth': 4, 'learning_rate': 0.29913639229314665, 'n_estimators': 812, 'subsample': 0.9828469832446997, 'colsample_bytree': 0.6164739523294258, 'min_child_weight': 5, 'gamma': 4.1143501142112076, 'reg_alpha': 1.0332682688531725e-08, 'reg_lambda': 0.23859143979722142, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  54%|█████▍    | 108/200 [01:33<00:49,  1.85it/s]

[I 2025-11-10 18:06:23,034] Trial 107 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.2963326329850317, 'n_estimators': 831, 'subsample': 0.960539377884662, 'colsample_bytree': 0.6153448428201664, 'min_child_weight': 5, 'gamma': 4.132690299058192, 'reg_alpha': 3.452365504850571e-08, 'reg_lambda': 0.31719169395590247, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.
[I 2025-11-10 18:06:23,218] Trial 106 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.22073958690474355, 'n_estimators': 876, 'subsample': 0.9982989487721117, 'colsample_bytree': 0.6201941912205062, 'min_child_weight': 5, 'gamma': 4.120301680121784, 'reg_alpha': 2.8549477052373635e-08, 'reg_lambda': 0.397467915270735, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  55%|█████▍    | 109/200 [01:33<00:38,  2.39it/s]

[I 2025-11-10 18:06:23,328] Trial 108 pruned.

Best trial: 105. Best value: 0.683977:  55%|█████▌    | 110/200 [01:34<00:37,  2.39it/s]

[I 2025-11-10 18:06:23,749] Trial 109 pruned.

Best trial: 105. Best value: 0.683977:  56%|█████▌    | 111/200 [01:34<00:32,  2.72it/s]

[I 2025-11-10 18:06:23,989] Trial 110 pruned.

Best trial: 105. Best value: 0.683977:  56%|█████▌    | 112/200 [01:34<00:28,  3.12it/s]

[I 2025-11-10 18:06:24,201] Trial 111 pruned.

Best trial: 105. Best value: 0.683977:  56%|█████▋    | 113/200 [01:36<01:24,  1.03it/s]

[I 2025-11-10 18:06:26,701] Trial 113 finished with value: 0.6692397660818714 and parameters: {'max_depth': 3, 'learning_rate': 0.18422525367148412, 'n_estimators': 645, 'subsample': 0.970282469950032, 'colsample_bytree': 0.5657593955247568, 'min_child_weight': 5, 'gamma': 3.702293013347638, 'reg_alpha': 4.637453462136651e-08, 'reg_lambda': 0.044606357148017875, 'max_delta_step': 8}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  57%|█████▊    | 115/200 [01:37<00:56,  1.51it/s]

[I 2025-11-10 18:06:27,351] Trial 112 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.17503501435651517, 'n_estimators': 893, 'subsample': 0.9705824403277714, 'colsample_bytree': 0.5739258911579597, 'min_child_weight': 5, 'gamma': 4.431063815988594, 'reg_alpha': 4.697173035536042e-08, 'reg_lambda': 0.06968510359214183, 'max_delta_step': 6}. Best is trial 105 with value: 0.6839766081871345.
[I 2025-11-10 18:06:27,519] Trial 114 finished with value: 0.6662573099415205 and parameters: {'max_depth': 4, 'learning_rate': 0.17803141472685874, 'n_estimators': 762, 'subsample': 0.9749751211865691, 'colsample_bytree': 0.6014352806521114, 'min_child_weight': 5, 'gamma': 4.43963752751716, 'reg_alpha': 1.0005460752725583e-08, 'reg_lambda': 0.0707578034159234, 'max_delta_step': 8}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  58%|█████▊    | 116/200 [01:37<00:42,  1.99it/s]

[I 2025-11-10 18:06:27,653] Trial 115 finished with value: 0.6706432748538013 and parameters: {'max_depth': 4, 'learning_rate': 0.26749019478239655, 'n_estimators': 758, 'subsample': 0.9804136180701242, 'colsample_bytree': 0.5824072384673125, 'min_child_weight': 5, 'gamma': 4.466493117039701, 'reg_alpha': 1.6573395934016116e-08, 'reg_lambda': 0.046416197294361645, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  58%|█████▊    | 117/200 [01:40<01:32,  1.12s/it]

[I 2025-11-10 18:06:30,204] Trial 116 finished with value: 0.6653801169590644 and parameters: {'max_depth': 4, 'learning_rate': 0.2709791075959574, 'n_estimators': 764, 'subsample': 0.9758495820696315, 'colsample_bytree': 0.5830318806517655, 'min_child_weight': 5, 'gamma': 4.437389897538674, 'reg_alpha': 1.6479247975419797e-08, 'reg_lambda': 0.08577256390679382, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  60%|█████▉    | 119/200 [01:41<00:56,  1.44it/s]

[I 2025-11-10 18:06:30,672] Trial 118 finished with value: 0.6706432748538014 and parameters: {'max_depth': 4, 'learning_rate': 0.2660116820762695, 'n_estimators': 694, 'subsample': 0.9815872065206801, 'colsample_bytree': 0.5422686038537997, 'min_child_weight': 5, 'gamma': 4.2520154735305775, 'reg_alpha': 1.9673857955753307e-08, 'reg_lambda': 0.22445263064799675, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.
[I 2025-11-10 18:06:30,829] Trial 117 finished with value: 0.667309941520468 and parameters: {'max_depth': 4, 'learning_rate': 0.2692863450290033, 'n_estimators': 762, 'subsample': 0.9304148560941014, 'colsample_bytree': 0.6039574813302444, 'min_child_weight': 5, 'gamma': 4.433062135941394, 'reg_alpha': 1.537413368910674e-08, 'reg_lambda': 0.22272373460081452, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  60%|██████    | 120/200 [01:41<00:53,  1.48it/s]

[I 2025-11-10 18:06:31,456] Trial 119 finished with value: 0.6559064327485381 and parameters: {'max_depth': 4, 'learning_rate': 0.14191555743148576, 'n_estimators': 839, 'subsample': 0.9293084455900333, 'colsample_bytree': 0.6051557387574413, 'min_child_weight': 5, 'gamma': 3.7975412277992224, 'reg_alpha': 2.0416607950259904e-08, 'reg_lambda': 0.1962544943204849, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  60%|██████    | 121/200 [01:43<01:23,  1.06s/it]

[I 2025-11-10 18:06:33,406] Trial 120 finished with value: 0.667309941520468 and parameters: {'max_depth': 4, 'learning_rate': 0.14103361928459893, 'n_estimators': 688, 'subsample': 0.9871754998055389, 'colsample_bytree': 0.5296213753857362, 'min_child_weight': 5, 'gamma': 4.700989949776351, 'reg_alpha': 2.4274847391102615e-08, 'reg_lambda': 0.19051159306404222, 'max_delta_step': 5}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  61%|██████    | 122/200 [01:44<01:12,  1.08it/s]

[I 2025-11-10 18:06:34,035] Trial 122 finished with value: 0.667309941520468 and parameters: {'max_depth': 5, 'learning_rate': 0.14601779085387795, 'n_estimators': 690, 'subsample': 0.9668581744381304, 'colsample_bytree': 0.5412773843979273, 'min_child_weight': 5, 'gamma': 4.263509143785291, 'reg_alpha': 2.3750333697550725e-08, 'reg_lambda': 0.019638308010734167, 'max_delta_step': 5}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  62%|██████▏   | 123/200 [01:44<00:54,  1.41it/s]

[I 2025-11-10 18:06:34,223] Trial 123 finished with value: 0.667309941520468 and parameters: {'max_depth': 5, 'learning_rate': 0.22425862241022632, 'n_estimators': 602, 'subsample': 0.96449030351841, 'colsample_bytree': 0.5406239904336372, 'min_child_weight': 5, 'gamma': 4.239132291705155, 'reg_alpha': 3.892432293404441e-08, 'reg_lambda': 0.018634508344485542, 'max_delta_step': 5}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  62%|██████▏   | 124/200 [01:44<00:45,  1.66it/s]

[I 2025-11-10 18:06:34,586] Trial 121 finished with value: 0.6595321637426901 and parameters: {'max_depth': 4, 'learning_rate': 0.13790562012392082, 'n_estimators': 837, 'subsample': 0.9324112723296349, 'colsample_bytree': 0.5316854167152548, 'min_child_weight': 5, 'gamma': 4.27082487833375, 'reg_alpha': 1.5738679792706047e-07, 'reg_lambda': 0.2687828081779157, 'max_delta_step': 8}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  62%|██████▎   | 125/200 [01:46<01:03,  1.18it/s]

[I 2025-11-10 18:06:36,006] Trial 124 finished with value: 0.667309941520468 and parameters: {'max_depth': 5, 'learning_rate': 0.2265549986004714, 'n_estimators': 551, 'subsample': 0.9667867058891255, 'colsample_bytree': 0.5432063245948272, 'min_child_weight': 5, 'gamma': 4.255910939279772, 'reg_alpha': 1.4436081518020443e-07, 'reg_lambda': 0.023674817633923925, 'max_delta_step': 8}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  63%|██████▎   | 126/200 [01:47<01:12,  1.02it/s]

[I 2025-11-10 18:06:37,283] Trial 125 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.2210298214772388, 'n_estimators': 732, 'subsample': 0.9827833140851356, 'colsample_bytree': 0.5309622991822407, 'min_child_weight': 5, 'gamma': 4.585692476606416, 'reg_alpha': 1.839323096947928e-07, 'reg_lambda': 0.12078937380597582, 'max_delta_step': 8}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  64%|██████▎   | 127/200 [01:48<01:03,  1.15it/s]

[I 2025-11-10 18:06:37,902] Trial 127 finished with value: 0.6706432748538013 and parameters: {'max_depth': 3, 'learning_rate': 0.2298105172580468, 'n_estimators': 723, 'subsample': 0.9925884983146435, 'colsample_bytree': 0.6247235581861567, 'min_child_weight': 5, 'gamma': 4.59755849750572, 'reg_alpha': 1.308885611039178e-08, 'reg_lambda': 0.10400439665349076, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  64%|██████▍   | 128/200 [01:48<00:49,  1.46it/s]

[I 2025-11-10 18:06:38,157] Trial 129 pruned.

Best trial: 105. Best value: 0.683977:  65%|██████▌   | 130/200 [01:49<00:35,  1.98it/s]

[I 2025-11-10 18:06:38,773] Trial 130 pruned.
[I 2025-11-10 18:06:38,903] Trial 126 finished with value: 0.667309941520468 and parameters: {'max_depth': 4, 'learning_rate': 0.22607747084056923, 'n_estimators': 945, 'subsample': 0.9497831379195667, 'colsample_bytree': 0.9997168737880009, 'min_child_weight': 5, 'gamma': 4.579927881156125, 'reg_alpha': 1.7263033892973416e-07, 'reg_lambda': 0.10589721296921638, 'max_delta_step': 8}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  66%|██████▌   | 131/200 [01:50<00:51,  1.33it/s]

[I 2025-11-10 18:06:40,228] Trial 128 finished with value: 0.6420467836257311 and parameters: {'max_depth': 3, 'learning_rate': 0.19376906491394288, 'n_estimators': 953, 'subsample': 0.984160663071259, 'colsample_bytree': 0.5099944337404645, 'min_child_weight': 5, 'gamma': 4.603569859364083, 'reg_alpha': 1.0110464120295864e-08, 'reg_lambda': 0.11990285047280683, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  66%|██████▌   | 132/200 [01:52<01:16,  1.13s/it]

[I 2025-11-10 18:06:42,253] Trial 131 finished with value: 0.667309941520468 and parameters: {'max_depth': 4, 'learning_rate': 0.20619188392919843, 'n_estimators': 948, 'subsample': 0.9835344876669052, 'colsample_bytree': 0.6427239062969617, 'min_child_weight': 5, 'gamma': 4.921379838431928, 'reg_alpha': 3.4491980999899077e-08, 'reg_lambda': 0.04094277520703507, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

[I 2025-11-10 18:06:42,792] Trial 132 finished with value: 0.6487426900584795 and parameters: {'max_depth': 3, 'learning_rate': 0.19891263501439027, 'n_estimators': 928, 'subsample': 0.9833427031195592, 'colsample_bytree': 0.6387573152175676, 'min_child_weight': 5, 'gamma': 3.1233342278504135, 'reg_alpha': 3.994717926376428e-08, 'reg_lambda': 0.007030851403869409, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  67%|██████▋   | 134/200 [01:53<00:47,  1.39it/s]

[I 2025-11-10 18:06:42,970] Trial 133 finished with value: 0.665906432748538 and parameters: {'max_depth': 3, 'learning_rate': 0.19676132222813247, 'n_estimators': 921, 'subsample': 0.9837862423356667, 'colsample_bytree': 0.6485703356446614, 'min_child_weight': 5, 'gamma': 3.236606160539022, 'reg_alpha': 4.114339434922343e-08, 'reg_lambda': 0.007327202611974922, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  68%|██████▊   | 135/200 [01:54<00:49,  1.32it/s]

[I 2025-11-10 18:06:43,814] Trial 134 finished with value: 0.6706432748538013 and parameters: {'max_depth': 4, 'learning_rate': 0.24225300315877502, 'n_estimators': 817, 'subsample': 0.9900349049720972, 'colsample_bytree': 0.5588009363393247, 'min_child_weight': 5, 'gamma': 4.353671412098051, 'reg_alpha': 2.8005074854755236e-08, 'reg_lambda': 0.05443545246275085, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  68%|██████▊   | 136/200 [01:55<01:09,  1.08s/it]

[I 2025-11-10 18:06:45,656] Trial 135 finished with value: 0.6595321637426901 and parameters: {'max_depth': 4, 'learning_rate': 0.2938904754856732, 'n_estimators': 793, 'subsample': 0.9923582255431482, 'colsample_bytree': 0.552565798004486, 'min_child_weight': 5, 'gamma': 4.378511472700955, 'reg_alpha': 2.2685111427080398e-08, 'reg_lambda': 0.0598929468291648, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  68%|██████▊   | 137/200 [01:56<01:00,  1.04it/s]

[I 2025-11-10 18:06:46,330] Trial 136 finished with value: 0.6595321637426901 and parameters: {'max_depth': 4, 'learning_rate': 0.29055674125100345, 'n_estimators': 800, 'subsample': 0.9938392909858215, 'colsample_bytree': 0.553400268629816, 'min_child_weight': 5, 'gamma': 4.3477029670225456, 'reg_alpha': 2.407487606799902e-08, 'reg_lambda': 0.0694429053453968, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  69%|██████▉   | 138/200 [01:57<00:51,  1.21it/s]

[I 2025-11-10 18:06:46,854] Trial 137 finished with value: 0.667309941520468 and parameters: {'max_depth': 4, 'learning_rate': 0.28432416128620086, 'n_estimators': 781, 'subsample': 0.9999035048966847, 'colsample_bytree': 0.936131411651583, 'min_child_weight': 5, 'gamma': 4.3460392018403935, 'reg_alpha': 2.1443910641325117e-08, 'reg_lambda': 0.047132160188901095, 'max_delta_step': 6}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  70%|██████▉   | 139/200 [01:57<00:41,  1.48it/s]

[I 2025-11-10 18:06:47,167] Trial 140 pruned.

Best trial: 105. Best value: 0.683977:  70%|███████   | 140/200 [01:57<00:31,  1.88it/s]

[I 2025-11-10 18:06:47,371] Trial 138 finished with value: 0.6706432748538013 and parameters: {'max_depth': 4, 'learning_rate': 0.28739423633410577, 'n_estimators': 778, 'subsample': 0.9940869766134166, 'colsample_bytree': 0.5497345853608405, 'min_child_weight': 5, 'gamma': 4.16159734542248, 'reg_alpha': 2.054291166534257e-08, 'reg_lambda': 0.526028217881555, 'max_delta_step': 8}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  70%|███████   | 141/200 [01:58<00:28,  2.05it/s]

[I 2025-11-10 18:06:47,753] Trial 141 pruned.

Best trial: 105. Best value: 0.683977:  71%|███████   | 142/200 [01:58<00:28,  2.02it/s]

[I 2025-11-10 18:06:48,263] Trial 143 pruned.

Best trial: 105. Best value: 0.683977:  72%|███████▏  | 143/200 [01:59<00:29,  1.93it/s]

[I 2025-11-10 18:06:48,832] Trial 139 finished with value: 0.6706432748538013 and parameters: {'max_depth': 4, 'learning_rate': 0.23984353005283854, 'n_estimators': 660, 'subsample': 0.9982650033889091, 'colsample_bytree': 0.5902803429776853, 'min_child_weight': 5, 'gamma': 4.132863703237729, 'reg_alpha': 1.3063372876043543e-08, 'reg_lambda': 0.4223111383607651, 'max_delta_step': 6}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  72%|███████▏  | 144/200 [02:00<00:44,  1.26it/s]

[I 2025-11-10 18:06:50,267] Trial 142 finished with value: 0.6587134502923977 and parameters: {'max_depth': 3, 'learning_rate': 0.2584332064868544, 'n_estimators': 653, 'subsample': 0.9740370504231641, 'colsample_bytree': 0.5210547687722348, 'min_child_weight': 5, 'gamma': 4.153859543447544, 'reg_alpha': 6.13532476227644e-08, 'reg_lambda': 0.1828636653651789, 'max_delta_step': 8}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  72%|███████▎  | 145/200 [02:01<00:40,  1.36it/s]

[I 2025-11-10 18:06:50,873] Trial 144 finished with value: 0.6587134502923977 and parameters: {'max_depth': 4, 'learning_rate': 0.25914273852544445, 'n_estimators': 664, 'subsample': 0.975050071438839, 'colsample_bytree': 0.5219572396397669, 'min_child_weight': 5, 'gamma': 4.14658570695913, 'reg_alpha': 6.070610915634075e-08, 'reg_lambda': 0.14388365269108724, 'max_delta_step': 8}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  73%|███████▎  | 146/200 [02:02<00:41,  1.29it/s]

[I 2025-11-10 18:06:51,741] Trial 145 finished with value: 0.6620467836257311 and parameters: {'max_depth': 4, 'learning_rate': 0.2097841979097199, 'n_estimators': 740, 'subsample': 0.9772479062647083, 'colsample_bytree': 0.5218712496707207, 'min_child_weight': 5, 'gamma': 4.5092531301674565, 'reg_alpha': 6.565775011400232e-08, 'reg_lambda': 0.24373642064121326, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  74%|███████▎  | 147/200 [02:02<00:36,  1.45it/s]

[I 2025-11-10 18:06:52,220] Trial 146 finished with value: 0.6620467836257311 and parameters: {'max_depth': 4, 'learning_rate': 0.21254268063603216, 'n_estimators': 740, 'subsample': 0.9770088086861447, 'colsample_bytree': 0.5192150696562968, 'min_child_weight': 5, 'gamma': 4.4994352853955375, 'reg_alpha': 6.978027509581754e-08, 'reg_lambda': 0.14597619799163472, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  74%|███████▍  | 148/200 [02:03<00:46,  1.12it/s]

[I 2025-11-10 18:06:53,585] Trial 147 finished with value: 0.667309941520468 and parameters: {'max_depth': 4, 'learning_rate': 0.21395120789821903, 'n_estimators': 707, 'subsample': 0.9772274844830239, 'colsample_bytree': 0.5631215202375234, 'min_child_weight': 5, 'gamma': 4.493972573425255, 'reg_alpha': 8.221530594784148e-08, 'reg_lambda': 0.3090423245509786, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  74%|███████▍  | 149/200 [02:04<00:47,  1.08it/s]

[I 2025-11-10 18:06:54,607] Trial 148 finished with value: 0.6328654970760235 and parameters: {'max_depth': 4, 'learning_rate': 0.08781736857136238, 'n_estimators': 826, 'subsample': 0.9773543777599043, 'colsample_bytree': 0.5612380126110486, 'min_child_weight': 5, 'gamma': 4.4645877481855125, 'reg_alpha': 8.053526019520039e-08, 'reg_lambda': 1.8704156626266948, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  75%|███████▌  | 150/200 [02:05<00:38,  1.32it/s]

[I 2025-11-10 18:06:54,973] Trial 149 finished with value: 0.667309941520468 and parameters: {'max_depth': 4, 'learning_rate': 0.21296667287266335, 'n_estimators': 705, 'subsample': 0.955273642147532, 'colsample_bytree': 0.5609376034152419, 'min_child_weight': 5, 'gamma': 4.2873996623464645, 'reg_alpha': 1.0678149427870183e-07, 'reg_lambda': 0.0864536740023507, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  76%|███████▌  | 151/200 [02:05<00:32,  1.50it/s]

[I 2025-11-10 18:06:55,410] Trial 150 finished with value: 0.6342690058479533 and parameters: {'max_depth': 4, 'learning_rate': 0.27551698839809613, 'n_estimators': 704, 'subsample': 0.9040636669180734, 'colsample_bytree': 0.607184833045971, 'min_child_weight': 5, 'gamma': 4.3176155182843745, 'reg_alpha': 1.0686113178360636e-07, 'reg_lambda': 0.030359011737199865, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  76%|███████▌  | 152/200 [02:07<00:47,  1.00it/s]

[I 2025-11-10 18:06:57,186] Trial 151 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.18616974673862494, 'n_estimators': 818, 'subsample': 0.95496420355633, 'colsample_bytree': 0.615201519320575, 'min_child_weight': 5, 'gamma': 4.330517701821114, 'reg_alpha': 1.5705832687086724e-08, 'reg_lambda': 0.02467256278206286, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  76%|███████▋  | 153/200 [02:08<00:45,  1.04it/s]

[I 2025-11-10 18:06:58,056] Trial 152 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.27559999216204556, 'n_estimators': 792, 'subsample': 0.9554871714378181, 'colsample_bytree': 0.6142307677411848, 'min_child_weight': 5, 'gamma': 4.322566066794483, 'reg_alpha': 1.5112886390299568e-08, 'reg_lambda': 0.028525275452179148, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  77%|███████▋  | 154/200 [02:08<00:36,  1.25it/s]

[I 2025-11-10 18:06:58,492] Trial 153 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.2744292258751452, 'n_estimators': 801, 'subsample': 0.9870917282044652, 'colsample_bytree': 0.6099729631037634, 'min_child_weight': 5, 'gamma': 4.876637130639133, 'reg_alpha': 3.3148803557126823e-08, 'reg_lambda': 0.028958954305524965, 'max_delta_step': 6}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  78%|███████▊  | 155/200 [02:09<00:29,  1.53it/s]

[I 2025-11-10 18:06:58,805] Trial 154 finished with value: 0.667309941520468 and parameters: {'max_depth': 4, 'learning_rate': 0.2721637097440334, 'n_estimators': 805, 'subsample': 0.9849683663469633, 'colsample_bytree': 0.5794016751156126, 'min_child_weight': 5, 'gamma': 4.895168884958011, 'reg_alpha': 1.5598073707304713e-08, 'reg_lambda': 0.04211438996869643, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  78%|███████▊  | 156/200 [02:11<00:46,  1.06s/it]

[I 2025-11-10 18:07:00,814] Trial 155 finished with value: 0.6706432748538013 and parameters: {'max_depth': 4, 'learning_rate': 0.23994468198510616, 'n_estimators': 796, 'subsample': 0.9866654879780609, 'colsample_bytree': 0.5752931641939544, 'min_child_weight': 5, 'gamma': 4.385185058696869, 'reg_alpha': 1.736143763495743e-08, 'reg_lambda': 0.05790109891054715, 'max_delta_step': 6}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  78%|███████▊  | 157/200 [02:11<00:40,  1.06it/s]

[I 2025-11-10 18:07:01,480] Trial 156 finished with value: 0.667309941520468 and parameters: {'max_depth': 4, 'learning_rate': 0.11052135160928402, 'n_estimators': 759, 'subsample': 0.9876975758950293, 'colsample_bytree': 0.580099789468691, 'min_child_weight': 5, 'gamma': 4.875562890064731, 'reg_alpha': 3.098399877724215e-08, 'reg_lambda': 0.04596769077393997, 'max_delta_step': 6}. Best is trial 105 with value: 0.6839766081871345.

[I 2025-11-10 18:07:01,961] Trial 157 finished with value: 0.6706432748538013 and parameters: {'max_depth': 4, 'learning_rate': 0.23475569600365737, 'n_estimators': 755, 'subsample': 0.9869019795994771, 'colsample_bytree': 0.5738145231693212, 'min_child_weight': 5, 'gamma': 4.44115443800148, 'reg_alpha': 1.048881497045328e-08, 'reg_lambda': 0.05243094862357891, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  80%|███████▉  | 159/200 [02:12<00:25,  1.62it/s]

[I 2025-11-10 18:07:02,141] Trial 158 finished with value: 0.6595321637426901 and parameters: {'max_depth': 5, 'learning_rate': 0.24046159434113606, 'n_estimators': 752, 'subsample': 0.9683027890134259, 'colsample_bytree': 0.5781604965586845, 'min_child_weight': 5, 'gamma': 3.8855306716592066, 'reg_alpha': 2.8993175097564898e-08, 'reg_lambda': 0.09283752458376444, 'max_delta_step': 8}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  80%|████████  | 160/200 [02:13<00:27,  1.43it/s]

[I 2025-11-10 18:07:03,035] Trial 162 pruned.

Best trial: 105. Best value: 0.683977:  80%|████████  | 161/200 [02:14<00:28,  1.39it/s]

[I 2025-11-10 18:07:03,803] Trial 163 pruned.

Best trial: 105. Best value: 0.683977:  81%|████████  | 162/200 [02:16<00:41,  1.09s/it]

[I 2025-11-10 18:07:05,767] Trial 159 finished with value: 0.6045029239766082 and parameters: {'max_depth': 4, 'learning_rate': 0.1124231805734441, 'n_estimators': 999, 'subsample': 0.9999390692987802, 'colsample_bytree': 0.6251793421189304, 'min_child_weight': 4, 'gamma': 3.988211143111773, 'reg_alpha': 1.01966521073008e-08, 'reg_lambda': 0.09472772588170265, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  82%|████████▏ | 163/200 [02:16<00:32,  1.13it/s]

[I 2025-11-10 18:07:06,167] Trial 161 finished with value: 0.5989863547758285 and parameters: {'max_depth': 5, 'learning_rate': 0.255889580637284, 'n_estimators': 889, 'subsample': 0.9684657928246991, 'colsample_bytree': 0.6246382871788557, 'min_child_weight': 4, 'gamma': 3.9930414955961293, 'reg_alpha': 4.41184551988582e-08, 'reg_lambda': 0.09747067528234613, 'max_delta_step': 8}. Best is trial 105 with value: 0.6839766081871345.
[I 2025-11-10 18:07:06,191] Trial 160 finished with value: 0.6139181286549709 and parameters: {'max_depth': 5, 'learning_rate': 0.2506538441052121, 'n_estimators': 991, 'subsample': 0.9697828177914262, 'colsample_bytree': 0.6260625220529331, 'min_child_weight': 4, 'gamma': 3.951962622341055, 'reg_alpha': 1.065775036260123e-08, 'reg_lambda': 0.10161291842607975, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  82%|████████▎ | 165/200 [02:17<00:21,  1.59it/s]

[I 2025-11-10 18:07:06,820] Trial 166 pruned.

Best trial: 105. Best value: 0.683977:  83%|████████▎ | 166/200 [02:18<00:23,  1.43it/s]

[I 2025-11-10 18:07:07,736] Trial 164 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.22922281133515932, 'n_estimators': 912, 'subsample': 0.9678456968032204, 'colsample_bytree': 0.6306830588343803, 'min_child_weight': 5, 'gamma': 4.592289289735045, 'reg_alpha': 1.0722617801328283e-08, 'reg_lambda': 0.10448034856794292, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  84%|████████▎ | 167/200 [02:20<00:34,  1.05s/it]

[I 2025-11-10 18:07:09,789] Trial 165 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.23070593880475773, 'n_estimators': 912, 'subsample': 0.9675078157264394, 'colsample_bytree': 0.657577400591259, 'min_child_weight': 5, 'gamma': 4.611521105013814, 'reg_alpha': 1.506954571804361e-08, 'reg_lambda': 0.11757627400628913, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  84%|████████▍ | 168/200 [02:20<00:28,  1.11it/s]

[I 2025-11-10 18:07:10,276] Trial 167 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.22757460020511677, 'n_estimators': 907, 'subsample': 0.9908521718178698, 'colsample_bytree': 0.6549909276033741, 'min_child_weight': 5, 'gamma': 4.602705136173188, 'reg_alpha': 1.6617647726993566e-08, 'reg_lambda': 0.14039865852689593, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  84%|████████▍ | 169/200 [02:21<00:24,  1.25it/s]

[I 2025-11-10 18:07:10,818] Trial 168 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.2213333428078022, 'n_estimators': 906, 'subsample': 0.9596800613085398, 'colsample_bytree': 0.6540254474275095, 'min_child_weight': 5, 'gamma': 4.5548689414402865, 'reg_alpha': 2.5886807897273724e-08, 'reg_lambda': 0.22328636110684266, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  85%|████████▌ | 170/200 [02:21<00:21,  1.39it/s]

[I 2025-11-10 18:07:11,343] Trial 169 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.16042327946483254, 'n_estimators': 836, 'subsample': 0.9286014695018905, 'colsample_bytree': 0.6012442807857177, 'min_child_weight': 5, 'gamma': 4.534020635625534, 'reg_alpha': 2.3882689836048683e-08, 'reg_lambda': 0.21601046351360345, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  86%|████████▌ | 171/200 [02:22<00:20,  1.40it/s]

[I 2025-11-10 18:07:12,045] Trial 173 pruned.

Best trial: 105. Best value: 0.683977:  86%|████████▌ | 172/200 [02:23<00:25,  1.09it/s]

[I 2025-11-10 18:07:13,449] Trial 170 finished with value: 0.6706432748538013 and parameters: {'max_depth': 3, 'learning_rate': 0.2675293673212424, 'n_estimators': 774, 'subsample': 0.9912853977314855, 'colsample_bytree': 0.6046132346641546, 'min_child_weight': 5, 'gamma': 4.224465622344841, 'reg_alpha': 2.4531680443394274e-08, 'reg_lambda': 0.20052223251450646, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  86%|████████▋ | 173/200 [02:23<00:19,  1.39it/s]

[I 2025-11-10 18:07:13,698] Trial 171 finished with value: 0.667309941520468 and parameters: {'max_depth': 3, 'learning_rate': 0.26322843849744487, 'n_estimators': 723, 'subsample': 0.9487528200833131, 'colsample_bytree': 0.6004851094031368, 'min_child_weight': 5, 'gamma': 4.218367114960564, 'reg_alpha': 2.7093677833211375e-08, 'reg_lambda': 0.21541337311838246, 'max_delta_step': 8}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  87%|████████▋ | 174/200 [02:24<00:16,  1.53it/s]

[I 2025-11-10 18:07:14,188] Trial 172 finished with value: 0.6736842105263159 and parameters: {'max_depth': 4, 'learning_rate': 0.06803144834786405, 'n_estimators': 717, 'subsample': 0.9477667987794823, 'colsample_bytree': 0.5375119228282855, 'min_child_weight': 5, 'gamma': 4.255486427318672, 'reg_alpha': 2.487118361414496e-08, 'reg_lambda': 0.0621168567869395, 'max_delta_step': 8}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  88%|████████▊ | 175/200 [02:25<00:21,  1.15it/s]

[I 2025-11-10 18:07:15,587] Trial 174 finished with value: 0.6706432748538013 and parameters: {'max_depth': 4, 'learning_rate': 0.26709000534218336, 'n_estimators': 780, 'subsample': 0.9880648833700926, 'colsample_bytree': 0.5565877805681443, 'min_child_weight': 5, 'gamma': 4.4074158268299914, 'reg_alpha': 2.8794754837432807e-08, 'reg_lambda': 0.06275133138459095, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  88%|████████▊ | 176/200 [02:27<00:26,  1.09s/it]

[I 2025-11-10 18:07:17,189] Trial 175 finished with value: 0.6706432748538014 and parameters: {'max_depth': 4, 'learning_rate': 0.24607841647577344, 'n_estimators': 821, 'subsample': 0.9805996643582604, 'colsample_bytree': 0.5394897127425029, 'min_child_weight': 5, 'gamma': 4.420950680215051, 'reg_alpha': 3.0702361075636216e-08, 'reg_lambda': 0.06286742878150307, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  88%|████████▊ | 177/200 [02:27<00:19,  1.17it/s]

[I 2025-11-10 18:07:17,480] Trial 176 finished with value: 0.6706432748538014 and parameters: {'max_depth': 4, 'learning_rate': 0.244091253075191, 'n_estimators': 826, 'subsample': 0.9799197261566749, 'colsample_bytree': 0.5529631548169266, 'min_child_weight': 5, 'gamma': 4.428717779937339, 'reg_alpha': 3.7307097547843797e-08, 'reg_lambda': 0.06414302981596164, 'max_delta_step': 7}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 105. Best value: 0.683977:  89%|████████▉ | 178/200 [02:27<00:14,  1.52it/s]

[I 2025-11-10 18:07:17,682] Trial 177 finished with value: 0.6706432748538014 and parameters: {'max_depth': 4, 'learning_rate': 0.244646191728106, 'n_estimators': 780, 'subsample': 0.9811161015902345, 'colsample_bytree': 0.5440512319026876, 'min_child_weight': 5, 'gamma': 4.398088204933998, 'reg_alpha': 1.602520618329199e-08, 'reg_lambda': 0.06582438836786543, 'max_delta_step': 8}. Best is trial 105 with value: 0.6839766081871345.

Best trial: 178. Best value: 0.691754:  90%|████████▉ | 179/200 [02:28<00:16,  1.30it/s]

[I 2025-11-10 18:07:18,714] Trial 178 finished with value: 0.6917543859649123 and parameters: {'max_depth': 4, 'learning_rate': 0.2998526004402225, 'n_estimators': 694, 'subsample': 0.9801036435690871, 'colsample_bytree': 0.5515507049313609, 'min_child_weight': 5, 'gamma': 4.429034437889781, 'reg_alpha': 1.648679195341101e-08, 'reg_lambda': 0.07222204580430834, 'max_delta_step': 8}. Best is trial 178 with value: 0.6917543859649123.

Best trial: 178. Best value: 0.691754:  90%|█████████ | 180/200 [02:31<00:24,  1.24s/it]

[I 2025-11-10 18:07:21,070] Trial 179 finished with value: 0.6706432748538013 and parameters: {'max_depth': 4, 'learning_rate': 0.24615070240734122, 'n_estimators': 861, 'subsample': 0.9441207017188341, 'colsample_bytree': 0.5368058208523119, 'min_child_weight': 5, 'gamma': 4.4296913110110685, 'reg_alpha': 4.226230505102153e-08, 'reg_lambda': 0.03758048412732577, 'max_delta_step': 8}. Best is trial 178 with value: 0.6917543859649123.

Best trial: 178. Best value: 0.691754:  90%|█████████ | 181/200 [02:31<00:18,  1.01it/s]

[I 2025-11-10 18:07:21,460] Trial 180 finished with value: 0.667309941520468 and parameters: {'max_depth': 4, 'learning_rate': 0.20469332172736845, 'n_estimators': 868, 'subsample': 0.9595942661181583, 'colsample_bytree': 0.5383615253887846, 'min_child_weight': 5, 'gamma': 4.0811882503159564, 'reg_alpha': 5.359489447876986e-08, 'reg_lambda': 0.034968336161694626, 'max_delta_step': 8}. Best is trial 178 with value: 0.6917543859649123.

Best trial: 178. Best value: 0.691754:  91%|█████████ | 182/200 [02:31<00:13,  1.33it/s]

[I 2025-11-10 18:07:21,663] Trial 181 finished with value: 0.6647953216374269 and parameters: {'max_depth': 4, 'learning_rate': 0.06291645884567151, 'n_estimators': 866, 'subsample': 0.9597768547733234, 'colsample_bytree': 0.5382152650432598, 'min_child_weight': 5, 'gamma': 4.086696732835863, 'reg_alpha': 3.840051581208331e-08, 'reg_lambda': 0.06693967905834085, 'max_delta_step': 8}. Best is trial 178 with value: 0.6917543859649123.

Best trial: 178. Best value: 0.691754:  92%|█████████▏| 183/200 [02:32<00:11,  1.48it/s]

[I 2025-11-10 18:07:22,159] Trial 184 pruned.

Best trial: 178. Best value: 0.691754:  92%|█████████▎| 185/200 [02:32<00:06,  2.23it/s]

[I 2025-11-10 18:07:22,519] Trial 185 pruned.
[I 2025-11-10 18:07:22,659] Trial 182 finished with value: 0.667309941520468 and parameters: {'max_depth': 4, 'learning_rate': 0.29201618116831257, 'n_estimators': 868, 'subsample': 0.9457772150892277, 'colsample_bytree': 0.535471534073471, 'min_child_weight': 5, 'gamma': 4.403970908136071, 'reg_alpha': 4.749779179841894e-08, 'reg_lambda': 0.0174253014835137, 'max_delta_step': 8}. Best is trial 178 with value: 0.6917543859649123.

Best trial: 178. Best value: 0.691754:  93%|█████████▎| 186/200 [02:33<00:06,  2.33it/s]

[I 2025-11-10 18:07:23,039] Trial 186 pruned.

Best trial: 178. Best value: 0.691754:  94%|█████████▍| 188/200 [02:33<00:03,  3.03it/s]

[I 2025-11-10 18:07:23,360] Trial 187 pruned.
[I 2025-11-10 18:07:23,532] Trial 188 pruned.

Best trial: 178. Best value: 0.691754:  94%|█████████▍| 189/200 [02:34<00:03,  2.91it/s]

[I 2025-11-10 18:07:23,909] Trial 189 pruned.

Best trial: 178. Best value: 0.691754:  95%|█████████▌| 190/200 [02:34<00:04,  2.30it/s]

[I 2025-11-10 18:07:24,561] Trial 192 pruned.

Best trial: 178. Best value: 0.691754:  96%|█████████▌| 191/200 [02:35<00:04,  2.03it/s]

[I 2025-11-10 18:07:25,180] Trial 183 finished with value: 0.667309941520468 and parameters: {'max_depth': 4, 'learning_rate': 0.2969256703042438, 'n_estimators': 828, 'subsample': 0.9580906458815778, 'colsample_bytree': 0.5339507400950517, 'min_child_weight': 5, 'gamma': 4.070918690593458, 'reg_alpha': 3.7730026253636696e-07, 'reg_lambda': 0.015637439765843263, 'max_delta_step': 8}. Best is trial 178 with value: 0.6917543859649123.

Best trial: 178. Best value: 0.691754:  96%|█████████▌| 192/200 [02:37<00:06,  1.16it/s]

[I 2025-11-10 18:07:26,917] Trial 191 finished with value: 0.667309941520468 and parameters: {'max_depth': 4, 'learning_rate': 0.12275184379452055, 'n_estimators': 777, 'subsample': 0.9603367658432438, 'colsample_bytree': 0.5669706132196134, 'min_child_weight': 5, 'gamma': 4.724910089545167, 'reg_alpha': 1.1531210336570046e-07, 'reg_lambda': 0.0251694168940759, 'max_delta_step': 8}. Best is trial 178 with value: 0.6917543859649123.
[I 2025-11-10 18:07:26,945] Trial 190 finished with value: 0.667309941520468 and parameters: {'max_depth': 4, 'learning_rate': 0.21090379404165446, 'n_estimators': 783, 'subsample': 0.9273021474303526, 'colsample_bytree': 0.5656794730368575, 'min_child_weight': 5, 'gamma': 4.751046176906078, 'reg_alpha': 1.2202684341245483e-07, 'reg_lambda': 0.009103055543403354, 'max_delta_step': 9}. Best is trial 178 with value: 0.6917543859649123.

Best trial: 178. Best value: 0.691754:  97%|█████████▋| 194/200 [02:38<00:04,  1.46it/s]

[I 2025-11-10 18:07:27,869] Trial 193 finished with value: 0.6706432748538013 and parameters: {'max_depth': 4, 'learning_rate': 0.2776158355335761, 'n_estimators': 738, 'subsample': 0.9985088296503599, 'colsample_bytree': 0.5138880371861824, 'min_child_weight': 5, 'gamma': 4.35319436428832, 'reg_alpha': 1.554161858126832e-08, 'reg_lambda': 0.023970087595062452, 'max_delta_step': 8}. Best is trial 178 with value: 0.6917543859649123.

Best trial: 178. Best value: 0.691754:  98%|█████████▊| 195/200 [02:38<00:03,  1.40it/s]

[I 2025-11-10 18:07:28,666] Trial 194 finished with value: 0.6706432748538013 and parameters: {'max_depth': 4, 'learning_rate': 0.26993214578467906, 'n_estimators': 798, 'subsample': 0.9986350282677658, 'colsample_bytree': 0.55658083260668, 'min_child_weight': 5, 'gamma': 4.332058372997119, 'reg_alpha': 1.515616901751947e-08, 'reg_lambda': 0.15000185338290178, 'max_delta_step': 7}. Best is trial 178 with value: 0.6917543859649123.

Best trial: 178. Best value: 0.691754:  98%|█████████▊| 196/200 [02:39<00:02,  1.39it/s]

[I 2025-11-10 18:07:29,396] Trial 198 pruned.

Best trial: 178. Best value: 0.691754:  98%|█████████▊| 197/200 [02:40<00:02,  1.31it/s]

[I 2025-11-10 18:07:30,287] Trial 195 finished with value: 0.6706432748538013 and parameters: {'max_depth': 4, 'learning_rate': 0.26714467701189215, 'n_estimators': 742, 'subsample': 0.9982860342452325, 'colsample_bytree': 0.5566269744853063, 'min_child_weight': 5, 'gamma': 4.354086869499181, 'reg_alpha': 1.565963557161963e-08, 'reg_lambda': 0.1335015937260714, 'max_delta_step': 7}. Best is trial 178 with value: 0.6917543859649123.

Best trial: 178. Best value: 0.691754: 100%|█████████▉| 199/200 [02:41<00:00,  2.00it/s]

[I 2025-11-10 18:07:30,575] Trial 196 finished with value: 0.6695321637426901 and parameters: {'max_depth': 4, 'learning_rate': 0.0743385134738496, 'n_estimators': 807, 'subsample': 0.990394749542591, 'colsample_bytree': 0.5534920049598357, 'min_child_weight': 5, 'gamma': 4.350316022382388, 'reg_alpha': 1.5257273208809874e-08, 'reg_lambda': 0.15111715145376362, 'max_delta_step': 7}. Best is trial 178 with value: 0.6917543859649123.
[I 2025-11-10 18:07:30,753] Trial 197 finished with value: 0.6706432748538014 and parameters: {'max_depth': 4, 'learning_rate': 0.2317087981620195, 'n_estimators': 680, 'subsample': 0.9841462423037448, 'colsample_bytree': 0.5556823163026564, 'min_child_weight': 5, 'gamma': 4.363668276927261, 'reg_alpha': 1.4342774094359769e-08, 'reg_lambda': 0.148129262564314, 'max_delta_step': 7}. Best is trial 178 with value: 0.6917543859649123.

Best trial: 178. Best value: 0.691754: 100%|██████████| 200/200 [02:41<00:00,  1.24it/s]

[I 2025-11-10 18:07:31,503] Trial 199 finished with value: 0.6628654970760234 and parameters: {'max_depth': 4, 'learning_rate': 0.07947993845470179, 'n_estimators': 687, 'subsample': 0.9856324457813225, 'colsample_bytree': 0.5425620877517199, 'min_child_weight': 5, 'gamma': 4.206829270220317, 'reg_alpha': 1.0322138656957601e-08, 'reg_lambda': 0.07453044530103604, 'max_delta_step': 7}. Best is trial 178 with value: 0.6917543859649123.

[I 2025-11-10 18:07:32,358] A new study created in memory with name: 3_4_roc_auc
Best trial: 1. Best value: 0.45194:   0%|          | 1/200 [00:02<08:08,  2.45s/it]

[I 2025-11-10 18:07:34,801] Trial 1 finished with value: 0.4519395711500975 and parameters: {'max_depth': 8, 'learning_rate': 0.2975924407517194, 'n_estimators': 432, 'subsample': 0.5988371539224006, 'colsample_bytree': 0.5783078839378832, 'min_child_weight': 1, 'gamma': 3.5604468495676054, 'reg_alpha': 2.661804581457401e-07, 'reg_lambda': 6.410884460931688, 'max_delta_step': 2}. Best is trial 1 with value: 0.4519395711500975.

Best trial: 0. Best value: 0.5:   1%|          | 2/200 [00:03<04:25,  1.34s/it]

[I 2025-11-10 18:07:35,375] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.12238322218894221, 'n_estimators': 689, 'subsample': 0.8175752677647865, 'colsample_bytree': 0.9976382106996744, 'min_child_weight': 5, 'gamma': 4.588381087800399, 'reg_alpha': 1.2956592066048313e-08, 'reg_lambda': 2.785225686397783, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   2%|▏         | 3/200 [00:03<02:55,  1.12it/s]

[I 2025-11-10 18:07:35,722] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.038441098775253923, 'n_estimators': 899, 'subsample': 0.5866689565608472, 'colsample_bytree': 0.5476847790619632, 'min_child_weight': 8, 'gamma': 3.511244272087235, 'reg_alpha': 0.0006143274392821418, 'reg_lambda': 0.7725585718751032, 'max_delta_step': 0}. Best is trial 0 with value: 0.5.

Best trial: 4. Best value: 0.576647:   2%|▏         | 4/200 [00:05<04:15,  1.31s/it]

[I 2025-11-10 18:07:37,664] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.09646800104062893, 'n_estimators': 1275, 'subsample': 0.9065067715338739, 'colsample_bytree': 0.9199120239371203, 'min_child_weight': 10, 'gamma': 1.3173944081884181, 'reg_alpha': 0.01568310691321851, 'reg_lambda': 0.0014355611085050087, 'max_delta_step': 2}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:07:37,740] Trial 4 finished with value: 0.5766471734892787 and parameters: {'max_depth': 6, 'learning_rate': 0.01078657968243122, 'n_estimators': 304, 'subsample': 0.5236524380910845, 'colsample_bytree': 0.5821534077044044, 'min_child_weight': 1, 'gamma': 1.9364278460493722, 'reg_alpha': 1.611055801268038e-08, 'reg_lambda': 1.982015665165523e-06, 'max_delta_step': 3}. Best is trial 4 with value: 0.5766471734892787.

Best trial: 4. Best value: 0.576647:   3%|▎         | 6/200 [00:06<02:52,  1.12it/s]

[I 2025-11-10 18:07:38,717] Trial 5 finished with value: 0.4892787524366472 and parameters: {'max_depth': 7, 'learning_rate': 0.027457346988751408, 'n_estimators': 790, 'subsample': 0.6954005372894251, 'colsample_bytree': 0.8715784380932349, 'min_child_weight': 4, 'gamma': 3.4191945509044923, 'reg_alpha': 0.006141667339717113, 'reg_lambda': 1.0254181489405434e-05, 'max_delta_step': 10}. Best is trial 4 with value: 0.5766471734892787.

Best trial: 4. Best value: 0.576647:   4%|▎         | 7/200 [00:07<03:30,  1.09s/it]

[I 2025-11-10 18:07:40,336] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.014339310963715149, 'n_estimators': 629, 'subsample': 0.6809380478043836, 'colsample_bytree': 0.7367287296273783, 'min_child_weight': 8, 'gamma': 2.766850987530902, 'reg_alpha': 0.02251267066184791, 'reg_lambda': 0.0007158706587204811, 'max_delta_step': 5}. Best is trial 4 with value: 0.5766471734892787.

Best trial: 4. Best value: 0.576647:   4%|▍         | 9/200 [00:08<02:10,  1.46it/s]

[I 2025-11-10 18:07:40,752] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.05877512552441796, 'n_estimators': 715, 'subsample': 0.5522383278991563, 'colsample_bytree': 0.8497345777803111, 'min_child_weight': 7, 'gamma': 0.11512723171984429, 'reg_alpha': 6.379188593447059e-07, 'reg_lambda': 4.97448802855526e-06, 'max_delta_step': 4}. Best is trial 4 with value: 0.5766471734892787.
[I 2025-11-10 18:07:40,892] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.06602637302080887, 'n_estimators': 1298, 'subsample': 0.563070466773453, 'colsample_bytree': 0.7555991059188294, 'min_child_weight': 6, 'gamma': 0.761720373539374, 'reg_alpha': 3.432464988196379, 'reg_lambda': 5.823631540917924e-07, 'max_delta_step': 10}. Best is trial 4 with value: 0.5766471734892787.

Best trial: 4. Best value: 0.576647:   5%|▌         | 10/200 [00:10<02:58,  1.06it/s]

[I 2025-11-10 18:07:42,458] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.10513886595569172, 'n_estimators': 348, 'subsample': 0.8409261714386208, 'colsample_bytree': 0.9497574678225484, 'min_child_weight': 6, 'gamma': 2.9405958863707493, 'reg_alpha': 0.0003104397137033354, 'reg_lambda': 3.556696697518788e-08, 'max_delta_step': 5}. Best is trial 4 with value: 0.5766471734892787.

Best trial: 4. Best value: 0.576647:   6%|▌         | 11/200 [00:10<02:37,  1.20it/s]

[I 2025-11-10 18:07:43,035] Trial 11 finished with value: 0.506588693957115 and parameters: {'max_depth': 10, 'learning_rate': 0.025270559328821142, 'n_estimators': 518, 'subsample': 0.9444133290902031, 'colsample_bytree': 0.7893594574682394, 'min_child_weight': 5, 'gamma': 3.3045887875131585, 'reg_alpha': 0.0006331953774369429, 'reg_lambda': 6.450445659455091e-08, 'max_delta_step': 6}. Best is trial 4 with value: 0.5766471734892787.

Best trial: 4. Best value: 0.576647:   6%|▌         | 12/200 [00:11<02:44,  1.14it/s]

[I 2025-11-10 18:07:44,006] Trial 9 finished with value: 0.49943469785575056 and parameters: {'max_depth': 6, 'learning_rate': 0.044407783074408916, 'n_estimators': 1089, 'subsample': 0.7549642780324728, 'colsample_bytree': 0.928703786808032, 'min_child_weight': 3, 'gamma': 3.392239685057597, 'reg_alpha': 0.07094275557966082, 'reg_lambda': 0.60389890308292, 'max_delta_step': 8}. Best is trial 4 with value: 0.5766471734892787.

Best trial: 14. Best value: 0.582612:   8%|▊         | 15/200 [00:13<01:51,  1.66it/s]

[I 2025-11-10 18:07:45,493] Trial 14 finished with value: 0.5826120857699805 and parameters: {'max_depth': 6, 'learning_rate': 0.010797074515278502, 'n_estimators': 209, 'subsample': 0.941417365155622, 'colsample_bytree': 0.6591410372442288, 'min_child_weight': 2, 'gamma': 1.7332663511464523, 'reg_alpha': 4.060004450223179e-05, 'reg_lambda': 1.1642120403388959e-08, 'max_delta_step': 7}. Best is trial 14 with value: 0.5826120857699805.
[I 2025-11-10 18:07:45,580] Trial 13 finished with value: 0.5314424951267057 and parameters: {'max_depth': 6, 'learning_rate': 0.010669750813570562, 'n_estimators': 204, 'subsample': 0.9919338827585742, 'colsample_bytree': 0.6458267684003762, 'min_child_weight': 1, 'gamma': 1.7483104396024376, 'reg_alpha': 1.2727032743516701e-05, 'reg_lambda': 1.2756426900390579e-08, 'max_delta_step': 0}. Best is trial 14 with value: 0.5826120857699805.
[I 2025-11-10 18:07:45,624] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.017967801540043234, 'n_estimators': 1461, 'subsample': 0.635777186488323, 'colsample_bytree': 0.6391979098236734, 'min_child_weight': 8, 'gamma': 1.7812749158187846, 'reg_alpha': 2.793394319546775e-05, 'reg_lambda': 5.591050093543169e-05, 'max_delta_step': 7}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:   8%|▊         | 16/200 [00:14<02:34,  1.19it/s]

[I 2025-11-10 18:07:47,198] Trial 15 finished with value: 0.5183430799220273 and parameters: {'max_depth': 7, 'learning_rate': 0.01184244353039904, 'n_estimators': 236, 'subsample': 0.9837664448145411, 'colsample_bytree': 0.6573577219280035, 'min_child_weight': 1, 'gamma': 1.788035903357348, 'reg_alpha': 1.159807929753143e-05, 'reg_lambda': 1.0489889790795e-08, 'max_delta_step': 7}. Best is trial 14 with value: 0.5826120857699805.
[I 2025-11-10 18:07:47,248] Trial 18 finished with value: 0.5462378167641325 and parameters: {'max_depth': 5, 'learning_rate': 0.011307687017965898, 'n_estimators': 213, 'subsample': 0.5065263587513729, 'colsample_bytree': 0.6656173355409108, 'min_child_weight': 2, 'gamma': 1.845582621798331, 'reg_alpha': 1.493991240016555e-08, 'reg_lambda': 5.17849393241149e-07, 'max_delta_step': 8}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:   9%|▉         | 18/200 [00:15<01:43,  1.76it/s]

[I 2025-11-10 18:07:47,553] Trial 17 finished with value: 0.5433138401559454 and parameters: {'max_depth': 5, 'learning_rate': 0.016579891926847057, 'n_estimators': 232, 'subsample': 0.6567113645177732, 'colsample_bytree': 0.6524658244417565, 'min_child_weight': 2, 'gamma': 2.0511883679983933, 'reg_alpha': 6.801542572173657e-06, 'reg_lambda': 2.8123585265144547e-05, 'max_delta_step': 7}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  10%|█         | 20/200 [00:16<01:43,  1.74it/s]

[I 2025-11-10 18:07:48,785] Trial 19 finished with value: 0.5100779727095517 and parameters: {'max_depth': 5, 'learning_rate': 0.01986624108504683, 'n_estimators': 363, 'subsample': 0.5015065193207262, 'colsample_bytree': 0.5070530291460995, 'min_child_weight': 3, 'gamma': 2.289838623725979, 'reg_alpha': 1.0566268945984497e-08, 'reg_lambda': 5.752779886733626e-07, 'max_delta_step': 2}. Best is trial 14 with value: 0.5826120857699805.
[I 2025-11-10 18:07:48,927] Trial 16 finished with value: 0.5284795321637427 and parameters: {'max_depth': 5, 'learning_rate': 0.01009367448447331, 'n_estimators': 220, 'subsample': 0.981962754089981, 'colsample_bytree': 0.6391028901419618, 'min_child_weight': 1, 'gamma': 1.8340152233410372, 'reg_alpha': 7.70562751644768e-06, 'reg_lambda': 4.508422070355566e-05, 'max_delta_step': 7}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  10%|█         | 21/200 [00:17<02:15,  1.32it/s]

[I 2025-11-10 18:07:50,194] Trial 20 finished with value: 0.5319493177387915 and parameters: {'max_depth': 5, 'learning_rate': 0.020182521345661866, 'n_estimators': 517, 'subsample': 0.8482826939827166, 'colsample_bytree': 0.5218756209660781, 'min_child_weight': 3, 'gamma': 2.3316247125705685, 'reg_alpha': 1.181418385043104e-06, 'reg_lambda': 0.016819017370012356, 'max_delta_step': 2}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  11%|█         | 22/200 [00:18<02:07,  1.40it/s]

[I 2025-11-10 18:07:50,799] Trial 21 finished with value: 0.5184405458089668 and parameters: {'max_depth': 3, 'learning_rate': 0.022773523847109137, 'n_estimators': 510, 'subsample': 0.7668660449554023, 'colsample_bytree': 0.5114748603475789, 'min_child_weight': 3, 'gamma': 0.919906373937039, 'reg_alpha': 0.6376356246557426, 'reg_lambda': 0.016743381791427547, 'max_delta_step': 2}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  12%|█▏        | 23/200 [00:19<02:00,  1.46it/s]

[I 2025-11-10 18:07:51,402] Trial 25 pruned.

Best trial: 14. Best value: 0.582612:  12%|█▏        | 24/200 [00:19<01:51,  1.58it/s]

[I 2025-11-10 18:07:51,909] Trial 23 finished with value: 0.49522417153996096 and parameters: {'max_depth': 4, 'learning_rate': 0.028128871565210697, 'n_estimators': 507, 'subsample': 0.773651113070567, 'colsample_bytree': 0.5724188379605369, 'min_child_weight': 3, 'gamma': 0.8082376844515382, 'reg_alpha': 2.483934852040937e-07, 'reg_lambda': 1.5920293887893998e-07, 'max_delta_step': 3}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  12%|█▎        | 25/200 [00:19<01:35,  1.83it/s]

[I 2025-11-10 18:07:52,242] Trial 22 finished with value: 0.536608187134503 and parameters: {'max_depth': 3, 'learning_rate': 0.029693060028151953, 'n_estimators': 557, 'subsample': 0.8441076895662092, 'colsample_bytree': 0.7080890554094732, 'min_child_weight': 3, 'gamma': 0.9797707377834163, 'reg_alpha': 4.499150427205699e-07, 'reg_lambda': 0.007895000911584495, 'max_delta_step': 3}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  13%|█▎        | 26/200 [00:20<01:45,  1.65it/s]

[I 2025-11-10 18:07:52,982] Trial 24 finished with value: 0.5299220272904483 and parameters: {'max_depth': 4, 'learning_rate': 0.013482563418944101, 'n_estimators': 375, 'subsample': 0.5171345924237074, 'colsample_bytree': 0.592075555561353, 'min_child_weight': 2, 'gamma': 1.2012256378225452, 'reg_alpha': 8.659969517853586e-08, 'reg_lambda': 5.227628065871077e-07, 'max_delta_step': 9}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  14%|█▎        | 27/200 [00:21<01:32,  1.86it/s]

[I 2025-11-10 18:07:53,365] Trial 29 pruned.

Best trial: 14. Best value: 0.582612:  14%|█▍        | 28/200 [00:21<01:37,  1.77it/s]

[I 2025-11-10 18:07:53,998] Trial 26 finished with value: 0.5512865497076023 and parameters: {'max_depth': 7, 'learning_rate': 0.01341803543674987, 'n_estimators': 328, 'subsample': 0.5381210368036758, 'colsample_bytree': 0.5849131465663336, 'min_child_weight': 2, 'gamma': 0.3801620518607771, 'reg_alpha': 6.595099943354292e-08, 'reg_lambda': 2.102923246556995e-06, 'max_delta_step': 9}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  15%|█▌        | 30/200 [00:22<01:21,  2.08it/s]

[I 2025-11-10 18:07:54,753] Trial 31 pruned.
[I 2025-11-10 18:07:54,900] Trial 28 finished with value: 0.5658674463937622 and parameters: {'max_depth': 7, 'learning_rate': 0.01321377197319417, 'n_estimators': 337, 'subsample': 0.5399711214060986, 'colsample_bytree': 0.609665619368998, 'min_child_weight': 2, 'gamma': 0.3250092064860368, 'reg_alpha': 2.3714247534054286e-08, 'reg_lambda': 2.3069981446672563e-06, 'max_delta_step': 9}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  16%|█▌        | 31/200 [00:25<03:09,  1.12s/it]

[I 2025-11-10 18:07:57,525] Trial 27 finished with value: 0.5432748538011697 and parameters: {'max_depth': 7, 'learning_rate': 0.013830287231967546, 'n_estimators': 960, 'subsample': 0.5305454938086067, 'colsample_bytree': 0.7038229336044246, 'min_child_weight': 2, 'gamma': 1.3445788689419964, 'reg_alpha': 3.8291473258923775e-08, 'reg_lambda': 1.7802733757170498e-06, 'max_delta_step': 9}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  16%|█▌        | 32/200 [00:25<02:23,  1.17it/s]

[I 2025-11-10 18:07:57,757] Trial 30 finished with value: 0.5180311890838206 and parameters: {'max_depth': 6, 'learning_rate': 0.18472711148787613, 'n_estimators': 912, 'subsample': 0.8960735047039903, 'colsample_bytree': 0.6036554784103048, 'min_child_weight': 2, 'gamma': 2.673818858917961, 'reg_alpha': 6.359344749920392e-05, 'reg_lambda': 2.1968779979587966e-06, 'max_delta_step': 9}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  16%|█▋        | 33/200 [00:26<02:23,  1.17it/s]

[I 2025-11-10 18:07:58,616] Trial 32 finished with value: 0.5755750487329434 and parameters: {'max_depth': 6, 'learning_rate': 0.016433379102536484, 'n_estimators': 663, 'subsample': 0.9004771281150943, 'colsample_bytree': 0.5997554250621746, 'min_child_weight': 2, 'gamma': 2.7000087889377635, 'reg_alpha': 1.5002520058660462e-06, 'reg_lambda': 2.5951844552812134e-06, 'max_delta_step': 4}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  17%|█▋        | 34/200 [00:26<01:48,  1.53it/s]

[I 2025-11-10 18:07:58,802] Trial 33 finished with value: 0.5757504873294346 and parameters: {'max_depth': 6, 'learning_rate': 0.034076306632793166, 'n_estimators': 665, 'subsample': 0.8008280648844711, 'colsample_bytree': 0.6183297486650359, 'min_child_weight': 1, 'gamma': 4.576447142510537, 'reg_alpha': 1.8232958378488304e-06, 'reg_lambda': 6.174612303096627e-08, 'max_delta_step': 4}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  18%|█▊        | 35/200 [00:27<02:02,  1.34it/s]

[I 2025-11-10 18:07:59,757] Trial 35 finished with value: 0.5613450292397661 and parameters: {'max_depth': 8, 'learning_rate': 0.01686322641220289, 'n_estimators': 312, 'subsample': 0.5857590307893427, 'colsample_bytree': 0.5517773260678568, 'min_child_weight': 1, 'gamma': 4.94548455400883, 'reg_alpha': 3.4222947701663248e-06, 'reg_lambda': 7.34271825746449e-08, 'max_delta_step': 8}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  18%|█▊        | 36/200 [00:28<01:59,  1.37it/s]

[I 2025-11-10 18:08:00,452] Trial 34 finished with value: 0.572475633528265 and parameters: {'max_depth': 6, 'learning_rate': 0.016724476175656096, 'n_estimators': 451, 'subsample': 0.5637507473162776, 'colsample_bytree': 0.5991576359998176, 'min_child_weight': 1, 'gamma': 4.248463751150952, 'reg_alpha': 2.1602270087605287e-06, 'reg_lambda': 7.804845860585664e-08, 'max_delta_step': 8}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  18%|█▊        | 37/200 [00:28<01:52,  1.45it/s]

[I 2025-11-10 18:08:01,050] Trial 39 pruned.

Best trial: 14. Best value: 0.582612:  19%|█▉        | 38/200 [00:29<01:40,  1.62it/s]

[I 2025-11-10 18:08:01,496] Trial 36 finished with value: 0.5336842105263158 and parameters: {'max_depth': 8, 'learning_rate': 0.016712731950097343, 'n_estimators': 440, 'subsample': 0.8948713266082275, 'colsample_bytree': 0.5488119710282551, 'min_child_weight': 1, 'gamma': 4.567665022666231, 'reg_alpha': 4.9758722675568e-06, 'reg_lambda': 1.1749685873458545e-05, 'max_delta_step': 4}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  20%|██        | 40/200 [00:29<01:11,  2.25it/s]

[I 2025-11-10 18:08:01,933] Trial 40 pruned.
[I 2025-11-10 18:08:02,098] Trial 41 pruned.

Best trial: 14. Best value: 0.582612:  20%|██        | 41/200 [00:30<01:16,  2.09it/s]

[I 2025-11-10 18:08:02,660] Trial 43 pruned.

Best trial: 14. Best value: 0.582612:  21%|██        | 42/200 [00:30<01:08,  2.29it/s]

[I 2025-11-10 18:08:02,997] Trial 42 pruned.

Best trial: 14. Best value: 0.582612:  22%|██▏       | 43/200 [00:30<01:01,  2.57it/s]

[I 2025-11-10 18:08:03,274] Trial 37 finished with value: 0.527719298245614 and parameters: {'max_depth': 6, 'learning_rate': 0.016977455504962338, 'n_estimators': 736, 'subsample': 0.8930460742171331, 'colsample_bytree': 0.5506666746178516, 'min_child_weight': 1, 'gamma': 4.82940647888807, 'reg_alpha': 2.695206282949145e-06, 'reg_lambda': 4.742318667309608e-08, 'max_delta_step': 4}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  22%|██▏       | 44/200 [00:31<01:29,  1.74it/s]

[I 2025-11-10 18:08:04,284] Trial 38 finished with value: 0.5420857699805068 and parameters: {'max_depth': 6, 'learning_rate': 0.04043889290579547, 'n_estimators': 771, 'subsample': 0.905815522507867, 'colsample_bytree': 0.5474989548490008, 'min_child_weight': 1, 'gamma': 3.9570733532463924, 'reg_alpha': 2.3620796322604982e-06, 'reg_lambda': 2.1569511023353218e-08, 'max_delta_step': 4}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  23%|██▎       | 46/200 [00:33<01:36,  1.60it/s]

[I 2025-11-10 18:08:05,696] Trial 44 finished with value: 0.5505847953216374 and parameters: {'max_depth': 6, 'learning_rate': 0.023281312384674648, 'n_estimators': 440, 'subsample': 0.8689512778959225, 'colsample_bytree': 0.6843278931285594, 'min_child_weight': 1, 'gamma': 4.090210045661036, 'reg_alpha': 1.829763721231307e-06, 'reg_lambda': 4.864292368314758e-08, 'max_delta_step': 6}. Best is trial 14 with value: 0.5826120857699805.
[I 2025-11-10 18:08:05,856] Trial 46 finished with value: 0.5501169590643276 and parameters: {'max_depth': 5, 'learning_rate': 0.03242403254564855, 'n_estimators': 416, 'subsample': 0.7122921258971844, 'colsample_bytree': 0.6682866269263892, 'min_child_weight': 1, 'gamma': 4.508664887987959, 'reg_alpha': 9.781018673327396e-07, 'reg_lambda': 1.6451335653490204e-08, 'max_delta_step': 6}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  24%|██▎       | 47/200 [00:33<01:14,  2.04it/s]

[I 2025-11-10 18:08:06,028] Trial 45 finished with value: 0.5607212475633527 and parameters: {'max_depth': 6, 'learning_rate': 0.022455990883783843, 'n_estimators': 430, 'subsample': 0.8656399058899051, 'colsample_bytree': 0.6776078017220368, 'min_child_weight': 1, 'gamma': 4.186604657746754, 'reg_alpha': 1.5729032250730222e-06, 'reg_lambda': 4.724376401083373e-08, 'max_delta_step': 6}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  24%|██▍       | 49/200 [00:34<00:54,  2.77it/s]

[I 2025-11-10 18:08:06,462] Trial 49 pruned.
[I 2025-11-10 18:08:06,564] Trial 48 pruned.

Best trial: 14. Best value: 0.582612:  26%|██▌       | 51/200 [00:34<00:37,  4.00it/s]

[I 2025-11-10 18:08:06,642] Trial 50 pruned.
[I 2025-11-10 18:08:06,803] Trial 51 pruned.

Best trial: 14. Best value: 0.582612:  26%|██▌       | 52/200 [00:35<00:48,  3.05it/s]

[I 2025-11-10 18:08:07,364] Trial 47 finished with value: 0.551812865497076 and parameters: {'max_depth': 5, 'learning_rate': 0.033336207698063614, 'n_estimators': 446, 'subsample': 0.72414707560448, 'colsample_bytree': 0.6744224158993113, 'min_child_weight': 1, 'gamma': 4.4721186176808345, 'reg_alpha': 1.068142140732524e-06, 'reg_lambda': 7.688535629655834e-08, 'max_delta_step': 6}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  26%|██▋       | 53/200 [00:36<01:44,  1.41it/s]

[I 2025-11-10 18:08:09,148] Trial 54 finished with value: 0.5582456140350878 and parameters: {'max_depth': 9, 'learning_rate': 0.01198156027261281, 'n_estimators': 282, 'subsample': 0.6164832465085196, 'colsample_bytree': 0.6107384854026117, 'min_child_weight': 2, 'gamma': 1.5513636280744738, 'reg_alpha': 1.2308996562981326e-07, 'reg_lambda': 3.926092613480531e-06, 'max_delta_step': 8}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  27%|██▋       | 54/200 [00:38<02:10,  1.12it/s]

[I 2025-11-10 18:08:10,536] Trial 52 finished with value: 0.5335282651072124 and parameters: {'max_depth': 5, 'learning_rate': 0.011641735203571115, 'n_estimators': 591, 'subsample': 0.8126966385991108, 'colsample_bytree': 0.5718011589533901, 'min_child_weight': 3, 'gamma': 1.5447026748015953, 'reg_alpha': 0.00020735247195502994, 'reg_lambda': 0.000202992670312844, 'max_delta_step': 5}. Best is trial 14 with value: 0.5826120857699805.
[I 2025-11-10 18:08:10,634] Trial 53 finished with value: 0.5537231968810916 and parameters: {'max_depth': 5, 'learning_rate': 0.012302275538741953, 'n_estimators': 576, 'subsample': 0.9631864574011895, 'colsample_bytree': 0.5319306791809886, 'min_child_weight': 3, 'gamma': 1.5371504484041465, 'reg_alpha': 0.0010080146329209164, 'reg_lambda': 0.8195078334328636, 'max_delta_step': 10}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  28%|██▊       | 57/200 [00:39<01:23,  1.72it/s]

[I 2025-11-10 18:08:11,499] Trial 57 pruned.
[I 2025-11-10 18:08:11,664] Trial 58 pruned.

Best trial: 14. Best value: 0.582612:  29%|██▉       | 58/200 [00:39<01:24,  1.68it/s]

[I 2025-11-10 18:08:12,302] Trial 55 finished with value: 0.558869395711501 and parameters: {'max_depth': 7, 'learning_rate': 0.012002801229749348, 'n_estimators': 848, 'subsample': 0.6040574667202407, 'colsample_bytree': 0.6111476243716467, 'min_child_weight': 2, 'gamma': 3.3065475849307866, 'reg_alpha': 1.4495144642832385e-07, 'reg_lambda': 7.365983303954807e-06, 'max_delta_step': 10}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  30%|██▉       | 59/200 [00:40<01:39,  1.42it/s]

[I 2025-11-10 18:08:13,307] Trial 60 finished with value: 0.5582846003898636 and parameters: {'max_depth': 6, 'learning_rate': 0.018416141570447464, 'n_estimators': 259, 'subsample': 0.6667680757292422, 'colsample_bytree': 0.613457443777512, 'min_child_weight': 2, 'gamma': 4.701685259013257, 'reg_alpha': 5.229086774080534e-07, 'reg_lambda': 2.7249167854171407e-07, 'max_delta_step': 7}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  30%|███       | 60/200 [00:41<01:21,  1.71it/s]

[I 2025-11-10 18:08:13,567] Trial 59 finished with value: 0.5370175438596492 and parameters: {'max_depth': 6, 'learning_rate': 0.014925796570087201, 'n_estimators': 259, 'subsample': 0.6560201413388884, 'colsample_bytree': 0.5941036716498911, 'min_child_weight': 2, 'gamma': 2.3586381632855646, 'reg_alpha': 1.590331782640197e-07, 'reg_lambda': 7.0742100778053615e-06, 'max_delta_step': 8}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  30%|███       | 61/200 [00:41<01:23,  1.66it/s]

[I 2025-11-10 18:08:14,223] Trial 61 finished with value: 0.5637037037037037 and parameters: {'max_depth': 8, 'learning_rate': 0.018385988488913464, 'n_estimators': 258, 'subsample': 0.6586351752496181, 'colsample_bytree': 0.5292523772891388, 'min_child_weight': 1, 'gamma': 4.73522533646822, 'reg_alpha': 5.135696950259649e-07, 'reg_lambda': 3.491493916831562e-07, 'max_delta_step': 7}. Best is trial 14 with value: 0.5826120857699805.
[I 2025-11-10 18:08:14,279] Trial 56 finished with value: 0.5361403508771929 and parameters: {'max_depth': 7, 'learning_rate': 0.012151284666278836, 'n_estimators': 826, 'subsample': 0.8125399589590759, 'colsample_bytree': 0.6406468114353902, 'min_child_weight': 3, 'gamma': 1.4961411751536249, 'reg_alpha': 2.920075041936522e-08, 'reg_lambda': 8.741735207677392e-06, 'max_delta_step': 10}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  32%|███▏      | 63/200 [00:44<01:55,  1.19it/s]

[I 2025-11-10 18:08:16,500] Trial 65 finished with value: 0.5535672514619883 and parameters: {'max_depth': 9, 'learning_rate': 0.026013852559725405, 'n_estimators': 384, 'subsample': 0.5274168367870055, 'colsample_bytree': 0.5287618318582928, 'min_child_weight': 1, 'gamma': 3.8229949564136274, 'reg_alpha': 4.861901307396299e-08, 'reg_lambda': 9.131255005107408e-07, 'max_delta_step': 7}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  32%|███▏      | 64/200 [00:44<01:34,  1.44it/s]

[I 2025-11-10 18:08:16,735] Trial 64 finished with value: 0.5686549707602339 and parameters: {'max_depth': 9, 'learning_rate': 0.010516800432660019, 'n_estimators': 384, 'subsample': 0.5280289130000401, 'colsample_bytree': 0.5290258860429321, 'min_child_weight': 1, 'gamma': 4.722130314938789, 'reg_alpha': 4.660054151488448e-08, 'reg_lambda': 1.018917863832081e-06, 'max_delta_step': 7}. Best is trial 14 with value: 0.5826120857699805.

Best trial: 14. Best value: 0.582612:  32%|███▎      | 65/200 [00:44<01:26,  1.56it/s]

[I 2025-11-10 18:08:17,220] Trial 66 pruned.

Best trial: 67. Best value: 0.58694:  33%|███▎      | 66/200 [00:47<02:51,  1.28s/it]

[I 2025-11-10 18:08:20,226] Trial 67 finished with value: 0.5869395711500974 and parameters: {'max_depth': 10, 'learning_rate': 0.010023952397395513, 'n_estimators': 314, 'subsample': 0.5187944950799337, 'colsample_bytree': 0.5037823975721084, 'min_child_weight': 1, 'gamma': 0.544065250304557, 'reg_alpha': 1.323471515589634e-08, 'reg_lambda': 1.1487609630987857e-06, 'max_delta_step': 3}. Best is trial 67 with value: 0.5869395711500974.

Best trial: 68. Best value: 0.591111:  34%|███▎      | 67/200 [00:48<02:35,  1.17s/it]

[I 2025-11-10 18:08:21,116] Trial 68 finished with value: 0.5911111111111111 and parameters: {'max_depth': 6, 'learning_rate': 0.013209309965940228, 'n_estimators': 320, 'subsample': 0.5383603759581488, 'colsample_bytree': 0.7240598627481428, 'min_child_weight': 1, 'gamma': 0.6200342889606221, 'reg_alpha': 6.080299364497749e-08, 'reg_lambda': 2.1539709667694606e-05, 'max_delta_step': 8}. Best is trial 68 with value: 0.5911111111111111.
[I 2025-11-10 18:08:21,178] Trial 63 finished with value: 0.5905068226120858 and parameters: {'max_depth': 10, 'learning_rate': 0.010187792567512956, 'n_estimators': 481, 'subsample': 0.7907767473313906, 'colsample_bytree': 0.8877084939609288, 'min_child_weight': 1, 'gamma': 0.5152987042783888, 'reg_alpha': 3.57986126728278e-08, 'reg_lambda': 1.3445207831672273e-06, 'max_delta_step': 3}. Best is trial 68 with value: 0.5911111111111111.

Best trial: 68. Best value: 0.591111:  34%|███▍      | 69/200 [00:51<02:53,  1.33s/it]

[I 2025-11-10 18:08:24,163] Trial 62 finished with value: 0.5580311890838207 and parameters: {'max_depth': 6, 'learning_rate': 0.010505761951112257, 'n_estimators': 1500, 'subsample': 0.7871246231026462, 'colsample_bytree': 0.5281979083915568, 'min_child_weight': 1, 'gamma': 0.5712462253810875, 'reg_alpha': 8.472434475616112e-06, 'reg_lambda': 1.0078398883434818e-06, 'max_delta_step': 3}. Best is trial 68 with value: 0.5911111111111111.

Best trial: 69. Best value: 0.596686:  35%|███▌      | 70/200 [00:52<02:17,  1.06s/it]

[I 2025-11-10 18:08:24,384] Trial 72 pruned.
[I 2025-11-10 18:08:24,390] Trial 69 finished with value: 0.5966861598440545 and parameters: {'max_depth': 10, 'learning_rate': 0.010211327210454894, 'n_estimators': 394, 'subsample': 0.5121255265143866, 'colsample_bytree': 0.5097428566996041, 'min_child_weight': 1, 'gamma': 0.537001885317951, 'reg_alpha': 1.1606214622885529e-08, 'reg_lambda': 1.0030835994928488e-07, 'max_delta_step': 3}. Best is trial 69 with value: 0.5966861598440545.

Best trial: 69. Best value: 0.596686:  36%|███▌      | 72/200 [00:52<01:32,  1.39it/s]

[I 2025-11-10 18:08:24,827] Trial 70 finished with value: 0.5898635477582845 and parameters: {'max_depth': 6, 'learning_rate': 0.01301684921637315, 'n_estimators': 309, 'subsample': 0.5185703380385898, 'colsample_bytree': 0.7240144262246173, 'min_child_weight': 1, 'gamma': 0.7129429968375494, 'reg_alpha': 1.0211249171449055e-08, 'reg_lambda': 4.4610547022047046e-05, 'max_delta_step': 3}. Best is trial 69 with value: 0.5966861598440545.

Best trial: 69. Best value: 0.596686:  36%|███▋      | 73/200 [00:54<02:00,  1.05it/s]

[I 2025-11-10 18:08:26,583] Trial 75 finished with value: 0.5381286549707602 and parameters: {'max_depth': 10, 'learning_rate': 0.12559328324797084, 'n_estimators': 332, 'subsample': 0.5133818165707984, 'colsample_bytree': 0.7313218590190254, 'min_child_weight': 1, 'gamma': 0.6360912806679477, 'reg_alpha': 1.0161947961850033e-08, 'reg_lambda': 0.001290916443459445, 'max_delta_step': 3}. Best is trial 69 with value: 0.5966861598440545.

Best trial: 69. Best value: 0.596686:  37%|███▋      | 74/200 [00:55<02:12,  1.05s/it]

[I 2025-11-10 18:08:27,941] Trial 74 finished with value: 0.5776608187134503 and parameters: {'max_depth': 10, 'learning_rate': 0.011302160051315504, 'n_estimators': 332, 'subsample': 0.5149843658998574, 'colsample_bytree': 0.5036247551739741, 'min_child_weight': 1, 'gamma': 0.5874840284088335, 'reg_alpha': 1.7695329660525285e-08, 'reg_lambda': 1.0363637754792033e-07, 'max_delta_step': 4}. Best is trial 69 with value: 0.5966861598440545.

Best trial: 69. Best value: 0.596686:  38%|███▊      | 75/200 [00:56<02:11,  1.05s/it]

[I 2025-11-10 18:08:28,989] Trial 71 finished with value: 0.5801169590643275 and parameters: {'max_depth': 10, 'learning_rate': 0.010804815654975002, 'n_estimators': 540, 'subsample': 0.8364780693851996, 'colsample_bytree': 0.9602791879121667, 'min_child_weight': 1, 'gamma': 0.7355586477987621, 'reg_alpha': 1.450164863060669e-08, 'reg_lambda': 1.7395130772589337e-05, 'max_delta_step': 3}. Best is trial 69 with value: 0.5966861598440545.

Best trial: 69. Best value: 0.596686:  38%|███▊      | 76/200 [00:57<02:09,  1.05s/it]

[I 2025-11-10 18:08:30,021] Trial 73 finished with value: 0.5830799220272904 and parameters: {'max_depth': 10, 'learning_rate': 0.01079716964427008, 'n_estimators': 320, 'subsample': 0.7443428321367476, 'colsample_bytree': 0.9753370669481283, 'min_child_weight': 1, 'gamma': 0.6479957611248027, 'reg_alpha': 1.4578285122048803e-08, 'reg_lambda': 0.0031795155764122516, 'max_delta_step': 4}. Best is trial 69 with value: 0.5966861598440545.

Best trial: 76. Best value: 0.614464:  38%|███▊      | 77/200 [00:58<01:56,  1.05it/s]

[I 2025-11-10 18:08:30,724] Trial 76 finished with value: 0.6144639376218324 and parameters: {'max_depth': 10, 'learning_rate': 0.011098273324840322, 'n_estimators': 307, 'subsample': 0.5145314121250053, 'colsample_bytree': 0.8082104599049516, 'min_child_weight': 1, 'gamma': 0.09482389154907961, 'reg_alpha': 1.9095031910384785e-08, 'reg_lambda': 2.5332896292251488e-05, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  39%|███▉      | 78/200 [00:59<01:45,  1.16it/s]

[I 2025-11-10 18:08:31,359] Trial 80 pruned.

Best trial: 76. Best value: 0.614464:  40%|███▉      | 79/200 [01:00<01:55,  1.05it/s]

[I 2025-11-10 18:08:32,543] Trial 77 finished with value: 0.6048343079922027 and parameters: {'max_depth': 10, 'learning_rate': 0.010760055525465578, 'n_estimators': 304, 'subsample': 0.5020251443492727, 'colsample_bytree': 0.9984899896753936, 'min_child_weight': 1, 'gamma': 0.046385770004810645, 'reg_alpha': 1.0170786386216677e-08, 'reg_lambda': 1.716057655475632e-05, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  40%|████      | 80/200 [01:00<01:41,  1.18it/s]

[I 2025-11-10 18:08:33,134] Trial 82 pruned.

Best trial: 76. Best value: 0.614464:  40%|████      | 81/200 [01:01<01:46,  1.12it/s]

[I 2025-11-10 18:08:34,130] Trial 81 finished with value: 0.5538206627680312 and parameters: {'max_depth': 10, 'learning_rate': 0.010166674870636822, 'n_estimators': 295, 'subsample': 0.5913648797185757, 'colsample_bytree': 0.8302969306539157, 'min_child_weight': 2, 'gamma': 0.32359457257579066, 'reg_alpha': 0.07186937888301617, 'reg_lambda': 0.00492677199995484, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  41%|████      | 82/200 [01:03<02:17,  1.17s/it]

[I 2025-11-10 18:08:35,948] Trial 78 finished with value: 0.5692397660818713 and parameters: {'max_depth': 10, 'learning_rate': 0.011201517721033992, 'n_estimators': 397, 'subsample': 0.8291428491917423, 'colsample_bytree': 0.9857202477926532, 'min_child_weight': 1, 'gamma': 0.594838941111518, 'reg_alpha': 1.1927547351839489e-08, 'reg_lambda': 2.1134729404042687e-05, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  42%|████▏     | 83/200 [01:05<02:32,  1.30s/it]

[I 2025-11-10 18:08:37,574] Trial 84 finished with value: 0.6013450292397661 and parameters: {'max_depth': 9, 'learning_rate': 0.011274938916736752, 'n_estimators': 230, 'subsample': 0.5194693286104517, 'colsample_bytree': 0.9919875975187255, 'min_child_weight': 1, 'gamma': 0.47853349106916016, 'reg_alpha': 1.1056010662336692e-08, 'reg_lambda': 3.066310485058534e-05, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  42%|████▏     | 84/200 [01:05<01:56,  1.00s/it]

[I 2025-11-10 18:08:37,864] Trial 83 finished with value: 0.5933528265107212 and parameters: {'max_depth': 9, 'learning_rate': 0.011494618092856982, 'n_estimators': 308, 'subsample': 0.5562491536339685, 'colsample_bytree': 0.8352485305424093, 'min_child_weight': 1, 'gamma': 0.018117995390886075, 'reg_alpha': 1.0296279531707886e-08, 'reg_lambda': 0.0651126095624012, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  42%|████▎     | 85/200 [01:06<01:53,  1.01it/s]

[I 2025-11-10 18:08:38,821] Trial 79 finished with value: 0.5720857699805069 and parameters: {'max_depth': 10, 'learning_rate': 0.01007548506820115, 'n_estimators': 478, 'subsample': 0.8314609054853427, 'colsample_bytree': 0.9790100212542459, 'min_child_weight': 1, 'gamma': 0.07654670651736073, 'reg_alpha': 0.1335190094133489, 'reg_lambda': 0.0030565479755069354, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  43%|████▎     | 86/200 [01:07<01:46,  1.07it/s]

[I 2025-11-10 18:08:39,619] Trial 85 finished with value: 0.5963157894736842 and parameters: {'max_depth': 9, 'learning_rate': 0.014535239381768015, 'n_estimators': 230, 'subsample': 0.551744511424934, 'colsample_bytree': 0.9468567947005155, 'min_child_weight': 1, 'gamma': 0.013545802651451569, 'reg_alpha': 2.626364136315774e-08, 'reg_lambda': 3.330668550266759e-05, 'max_delta_step': 3}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  44%|████▎     | 87/200 [01:07<01:29,  1.27it/s]

[I 2025-11-10 18:08:40,073] Trial 89 pruned.

Best trial: 76. Best value: 0.614464:  44%|████▍     | 88/200 [01:09<01:50,  1.02it/s]

[I 2025-11-10 18:08:41,514] Trial 87 finished with value: 0.5860623781676414 and parameters: {'max_depth': 9, 'learning_rate': 0.014410365028832334, 'n_estimators': 234, 'subsample': 0.555231410631361, 'colsample_bytree': 0.8611301892896557, 'min_child_weight': 1, 'gamma': 0.05237069035678613, 'reg_alpha': 2.7365626376161834e-08, 'reg_lambda': 0.00010713312473682119, 'max_delta_step': 0}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  44%|████▍     | 89/200 [01:09<01:37,  1.14it/s]

[I 2025-11-10 18:08:42,141] Trial 91 pruned.

Best trial: 76. Best value: 0.614464:  45%|████▌     | 90/200 [01:10<01:19,  1.38it/s]

[I 2025-11-10 18:08:42,511] Trial 88 finished with value: 0.5966666666666667 and parameters: {'max_depth': 9, 'learning_rate': 0.014508384570088018, 'n_estimators': 235, 'subsample': 0.5567067696529464, 'colsample_bytree': 0.8544131196677127, 'min_child_weight': 1, 'gamma': 0.014028524386031277, 'reg_alpha': 5.65667496140701e-08, 'reg_lambda': 7.5672323472515055, 'max_delta_step': 0}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  46%|████▌     | 91/200 [01:10<01:11,  1.52it/s]

[I 2025-11-10 18:08:43,009] Trial 86 finished with value: 0.5963157894736841 and parameters: {'max_depth': 9, 'learning_rate': 0.012913224770507886, 'n_estimators': 360, 'subsample': 0.5541407581789137, 'colsample_bytree': 0.9673836329638585, 'min_child_weight': 1, 'gamma': 0.011409043449777334, 'reg_alpha': 2.6646045309334136e-08, 'reg_lambda': 4.0816755852984095e-05, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  46%|████▌     | 92/200 [01:12<01:59,  1.11s/it]

[I 2025-11-10 18:08:45,162] Trial 90 finished with value: 0.5985185185185184 and parameters: {'max_depth': 9, 'learning_rate': 0.015539723424051702, 'n_estimators': 370, 'subsample': 0.5370520709372614, 'colsample_bytree': 0.8015422851793442, 'min_child_weight': 1, 'gamma': 0.25339920122712073, 'reg_alpha': 5.758271916556157e-08, 'reg_lambda': 0.0004974673672152427, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  46%|████▋     | 93/200 [01:13<01:42,  1.05it/s]

[I 2025-11-10 18:08:45,767] Trial 93 finished with value: 0.5913450292397661 and parameters: {'max_depth': 9, 'learning_rate': 0.015750491777286865, 'n_estimators': 205, 'subsample': 0.582781186289198, 'colsample_bytree': 0.8020931845401936, 'min_child_weight': 1, 'gamma': 0.8546462643835981, 'reg_alpha': 8.601353217098056e-08, 'reg_lambda': 0.12714499782524266, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  47%|████▋     | 94/200 [01:14<01:35,  1.11it/s]

[I 2025-11-10 18:08:46,536] Trial 92 finished with value: 0.585906432748538 and parameters: {'max_depth': 9, 'learning_rate': 0.015290236302000488, 'n_estimators': 358, 'subsample': 0.5022993725517576, 'colsample_bytree': 0.8027805265603791, 'min_child_weight': 1, 'gamma': 0.9210890069047908, 'reg_alpha': 8.40219588647257e-08, 'reg_lambda': 3.563665729772905e-05, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  48%|████▊     | 95/200 [01:15<01:51,  1.06s/it]

[I 2025-11-10 18:08:47,966] Trial 94 finished with value: 0.5877972709551657 and parameters: {'max_depth': 9, 'learning_rate': 0.01571945990977482, 'n_estimators': 360, 'subsample': 0.5805833945949812, 'colsample_bytree': 0.8080603948946978, 'min_child_weight': 1, 'gamma': 0.4537903785706523, 'reg_alpha': 1.284955151317084e-07, 'reg_lambda': 0.20258136636668878, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  48%|████▊     | 96/200 [01:17<02:15,  1.30s/it]

[I 2025-11-10 18:08:49,841] Trial 96 finished with value: 0.5934697855750487 and parameters: {'max_depth': 9, 'learning_rate': 0.015734052394731555, 'n_estimators': 282, 'subsample': 0.5813436533244833, 'colsample_bytree': 0.8127147830331942, 'min_child_weight': 1, 'gamma': 0.20029512602276422, 'reg_alpha': 9.224846553117815e-08, 'reg_lambda': 6.591266645902795, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  48%|████▊     | 97/200 [01:18<02:16,  1.33s/it]

[I 2025-11-10 18:08:51,232] Trial 98 finished with value: 0.6112670565302144 and parameters: {'max_depth': 9, 'learning_rate': 0.019805860402957086, 'n_estimators': 201, 'subsample': 0.6015177083763646, 'colsample_bytree': 0.8363848071415426, 'min_child_weight': 1, 'gamma': 0.02678583019790069, 'reg_alpha': 2.438755240896117e-07, 'reg_lambda': 9.373552823278473, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  49%|████▉     | 98/200 [01:20<02:10,  1.28s/it]

[I 2025-11-10 18:08:52,396] Trial 99 finished with value: 0.5566471734892786 and parameters: {'max_depth': 9, 'learning_rate': 0.01999708709945497, 'n_estimators': 278, 'subsample': 0.5642679011368331, 'colsample_bytree': 0.8363821230354773, 'min_child_weight': 2, 'gamma': 0.17029360478193575, 'reg_alpha': 2.5368802585386705e-07, 'reg_lambda': 3.796054569039793, 'max_delta_step': 0}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  50%|████▉     | 99/200 [01:21<02:08,  1.27s/it]

[I 2025-11-10 18:08:53,639] Trial 100 finished with value: 0.5419688109161793 and parameters: {'max_depth': 8, 'learning_rate': 0.019821779160557024, 'n_estimators': 246, 'subsample': 0.6061841358869552, 'colsample_bytree': 0.7814820164214942, 'min_child_weight': 2, 'gamma': 0.27035879362725324, 'reg_alpha': 2.781003599069386e-07, 'reg_lambda': 6.478351723862921, 'max_delta_step': 0}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  50%|█████     | 100/200 [01:22<02:03,  1.23s/it]

[I 2025-11-10 18:08:54,793] Trial 101 finished with value: 0.5420857699805068 and parameters: {'max_depth': 8, 'learning_rate': 0.021643812358618262, 'n_estimators': 250, 'subsample': 0.604646590901709, 'colsample_bytree': 0.7517078716402745, 'min_child_weight': 2, 'gamma': 0.2923713637450265, 'reg_alpha': 2.333963222761279e-08, 'reg_lambda': 7.056172808870252, 'max_delta_step': 0}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  50%|█████     | 101/200 [01:24<02:23,  1.45s/it]

[I 2025-11-10 18:08:56,740] Trial 97 finished with value: 0.5659259259259259 and parameters: {'max_depth': 9, 'learning_rate': 0.019899155299221115, 'n_estimators': 1284, 'subsample': 0.583576570698124, 'colsample_bytree': 0.8054465021671817, 'min_child_weight': 1, 'gamma': 0.00017920968429144084, 'reg_alpha': 2.1465821619083317e-07, 'reg_lambda': 0.2394370858094928, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  51%|█████     | 102/200 [01:24<01:51,  1.14s/it]

[I 2025-11-10 18:08:57,157] Trial 102 finished with value: 0.5943274853801169 and parameters: {'max_depth': 9, 'learning_rate': 0.01767398847785844, 'n_estimators': 228, 'subsample': 0.5944561865952069, 'colsample_bytree': 0.7544674019864663, 'min_child_weight': 1, 'gamma': 0.0031713056776527266, 'reg_alpha': 2.385472325708938e-08, 'reg_lambda': 9.487946168887783, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  52%|█████▏    | 103/200 [01:26<02:07,  1.32s/it]

[I 2025-11-10 18:08:58,889] Trial 103 finished with value: 0.5900000000000001 and parameters: {'max_depth': 9, 'learning_rate': 0.01727970325326389, 'n_estimators': 281, 'subsample': 0.5459937795674107, 'colsample_bytree': 0.96395501212606, 'min_child_weight': 1, 'gamma': 0.16391265145321315, 'reg_alpha': 1.4025780073655275e-07, 'reg_lambda': 1.702079587830946, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  52%|█████▏    | 104/200 [01:28<02:17,  1.43s/it]

[I 2025-11-10 18:09:00,585] Trial 104 finished with value: 0.5941910331384015 and parameters: {'max_depth': 9, 'learning_rate': 0.017602900414968176, 'n_estimators': 280, 'subsample': 0.5473254116051094, 'colsample_bytree': 0.849741737229212, 'min_child_weight': 1, 'gamma': 0.15031744215882167, 'reg_alpha': 4.083522126273093e-08, 'reg_lambda': 1.5238775658242958, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  52%|█████▎    | 105/200 [01:28<01:48,  1.15s/it]

[I 2025-11-10 18:09:01,069] Trial 95 finished with value: 0.5953216374269006 and parameters: {'max_depth': 9, 'learning_rate': 0.01582649398053124, 'n_estimators': 1351, 'subsample': 0.5472508157429445, 'colsample_bytree': 0.7985844390312246, 'min_child_weight': 1, 'gamma': 0.0012615698848424811, 'reg_alpha': 8.678534469460418e-08, 'reg_lambda': 5.364304903278063, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  53%|█████▎    | 106/200 [01:30<02:01,  1.30s/it]

[I 2025-11-10 18:09:02,718] Trial 106 finished with value: 0.5694931773879143 and parameters: {'max_depth': 9, 'learning_rate': 0.017486290030802095, 'n_estimators': 226, 'subsample': 0.6331045159384907, 'colsample_bytree': 0.9998706548706109, 'min_child_weight': 1, 'gamma': 0.16336522407552267, 'reg_alpha': 2.1910103122490853e-08, 'reg_lambda': 2.618175129546306, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  54%|█████▎    | 107/200 [01:31<02:02,  1.31s/it]

[I 2025-11-10 18:09:04,068] Trial 107 finished with value: 0.5927290448343081 and parameters: {'max_depth': 9, 'learning_rate': 0.01830685583576427, 'n_estimators': 232, 'subsample': 0.6356466056763052, 'colsample_bytree': 0.8572814421468267, 'min_child_weight': 1, 'gamma': 0.385008270990315, 'reg_alpha': 4.755806144588462e-08, 'reg_lambda': 3.223536806011311, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  55%|█████▍    | 109/200 [01:32<01:11,  1.27it/s]

[I 2025-11-10 18:09:04,505] Trial 110 pruned.
[I 2025-11-10 18:09:04,674] Trial 109 pruned.

Best trial: 76. Best value: 0.614464:  55%|█████▌    | 110/200 [01:37<03:04,  2.05s/it]

[I 2025-11-10 18:09:09,676] Trial 105 finished with value: 0.5737037037037037 and parameters: {'max_depth': 9, 'learning_rate': 0.018235591795012662, 'n_estimators': 1329, 'subsample': 0.5454257831422769, 'colsample_bytree': 0.8159485279482888, 'min_child_weight': 1, 'gamma': 0.1467228031509173, 'reg_alpha': 4.823260606796128e-08, 'reg_lambda': 2.69662906207826, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  56%|█████▌    | 111/200 [01:40<03:37,  2.45s/it]

[I 2025-11-10 18:09:13,044] Trial 108 finished with value: 0.5714814814814815 and parameters: {'max_depth': 9, 'learning_rate': 0.014416558919844974, 'n_estimators': 1189, 'subsample': 0.5294407045629128, 'colsample_bytree': 0.7884458707798305, 'min_child_weight': 1, 'gamma': 0.3833023036719038, 'reg_alpha': 2.1600275923947708e-08, 'reg_lambda': 4.198395949976115, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  56%|█████▌    | 112/200 [01:44<04:06,  2.80s/it]

[I 2025-11-10 18:09:16,678] Trial 112 finished with value: 0.5719688109161793 and parameters: {'max_depth': 9, 'learning_rate': 0.013767491684585726, 'n_estimators': 1151, 'subsample': 0.5938555326757969, 'colsample_bytree': 0.8198102716406528, 'min_child_weight': 1, 'gamma': 0.020271620275550892, 'reg_alpha': 1.964836892341886e-08, 'reg_lambda': 0.9304365409135258, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  56%|█████▋    | 113/200 [01:44<03:00,  2.07s/it]

[I 2025-11-10 18:09:17,056] Trial 111 finished with value: 0.5723586744639376 and parameters: {'max_depth': 9, 'learning_rate': 0.014031575999049814, 'n_estimators': 1330, 'subsample': 0.5677957591917814, 'colsample_bytree': 0.7681702932011794, 'min_child_weight': 1, 'gamma': 0.009087698488329507, 'reg_alpha': 7.637879470141549e-07, 'reg_lambda': 0.9118486451417049, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  57%|█████▋    | 114/200 [01:47<03:06,  2.16s/it]

[I 2025-11-10 18:09:19,430] Trial 113 finished with value: 0.5787719298245614 and parameters: {'max_depth': 10, 'learning_rate': 0.0244222028570541, 'n_estimators': 1208, 'subsample': 0.5097575377512438, 'colsample_bytree': 0.7427865704902796, 'min_child_weight': 1, 'gamma': 0.05808028822206612, 'reg_alpha': 1.8874169331338833e-08, 'reg_lambda': 1.370623996920548, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  57%|█████▊    | 115/200 [01:47<02:28,  1.75s/it]

[I 2025-11-10 18:09:20,213] Trial 117 pruned.

Best trial: 76. Best value: 0.614464:  58%|█████▊    | 116/200 [01:48<01:54,  1.36s/it]

[I 2025-11-10 18:09:20,657] Trial 116 finished with value: 0.5900000000000001 and parameters: {'max_depth': 10, 'learning_rate': 0.01223814839341764, 'n_estimators': 262, 'subsample': 0.5101769624588426, 'colsample_bytree': 0.8477799619524998, 'min_child_weight': 1, 'gamma': 0.27141941488473764, 'reg_alpha': 3.506746370990754e-08, 'reg_lambda': 1.691991372387613, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  58%|█████▊    | 117/200 [01:48<01:34,  1.14s/it]

[I 2025-11-10 18:09:21,274] Trial 119 pruned.

Best trial: 76. Best value: 0.614464:  59%|█████▉    | 118/200 [01:51<02:00,  1.47s/it]

[I 2025-11-10 18:09:23,522] Trial 114 finished with value: 0.5761793372319688 and parameters: {'max_depth': 9, 'learning_rate': 0.021582190437930384, 'n_estimators': 1077, 'subsample': 0.5689127133559421, 'colsample_bytree': 0.7642937079859309, 'min_child_weight': 1, 'gamma': 0.06826452979752841, 'reg_alpha': 3.669897320783685e-08, 'reg_lambda': 2.0116985750993672, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  60%|██████    | 120/200 [01:51<01:11,  1.12it/s]

[I 2025-11-10 18:09:24,106] Trial 118 finished with value: 0.5797465886939571 and parameters: {'max_depth': 9, 'learning_rate': 0.012268685629252265, 'n_estimators': 262, 'subsample': 0.5611773283829974, 'colsample_bytree': 0.8721162903040687, 'min_child_weight': 1, 'gamma': 0.13913549201513437, 'reg_alpha': 6.008658170798865e-08, 'reg_lambda': 1.5293718335823647, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.
[I 2025-11-10 18:09:24,282] Trial 120 finished with value: 0.5864327485380117 and parameters: {'max_depth': 8, 'learning_rate': 0.016080065680079244, 'n_estimators': 200, 'subsample': 0.5447461338779744, 'colsample_bytree': 0.9391512617110109, 'min_child_weight': 1, 'gamma': 0.11732254016317711, 'reg_alpha': 3.6771718006849606e-07, 'reg_lambda': 9.141243708271853, 'max_delta_step': 3}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  60%|██████    | 121/200 [01:52<00:58,  1.36it/s]

[I 2025-11-10 18:09:24,648] Trial 123 pruned.

Best trial: 76. Best value: 0.614464:  61%|██████    | 122/200 [01:53<01:17,  1.01it/s]

[I 2025-11-10 18:09:26,238] Trial 115 finished with value: 0.5816179337231968 and parameters: {'max_depth': 10, 'learning_rate': 0.021489746429807003, 'n_estimators': 1013, 'subsample': 0.5691977423032918, 'colsample_bytree': 0.8455999074410662, 'min_child_weight': 1, 'gamma': 0.29267993039570706, 'reg_alpha': 3.6302641760784015e-08, 'reg_lambda': 2.0836884247233924, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  62%|██████▏   | 123/200 [01:55<01:33,  1.22s/it]

[I 2025-11-10 18:09:27,975] Trial 122 finished with value: 0.584074074074074 and parameters: {'max_depth': 10, 'learning_rate': 0.01619065834666908, 'n_estimators': 296, 'subsample': 0.5440225646401441, 'colsample_bytree': 0.9351397089557314, 'min_child_weight': 1, 'gamma': 0.31391603104365956, 'reg_alpha': 8.200755558865839e-08, 'reg_lambda': 9.658119289006102, 'max_delta_step': 3}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  62%|██████▏   | 124/200 [01:56<01:21,  1.07s/it]

[I 2025-11-10 18:09:28,709] Trial 124 finished with value: 0.5928460038986355 and parameters: {'max_depth': 9, 'learning_rate': 0.01519239638853186, 'n_estimators': 291, 'subsample': 0.5393449859229543, 'colsample_bytree': 0.9172065556698497, 'min_child_weight': 1, 'gamma': 0.20334645893972852, 'reg_alpha': 1.0427156224673625e-07, 'reg_lambda': 5.2331938829686315, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  62%|██████▎   | 125/200 [01:56<01:09,  1.07it/s]

[I 2025-11-10 18:09:29,315] Trial 121 finished with value: 0.5917348927875243 and parameters: {'max_depth': 9, 'learning_rate': 0.015740017721385342, 'n_estimators': 412, 'subsample': 0.5427728257671645, 'colsample_bytree': 0.9400529779047794, 'min_child_weight': 1, 'gamma': 0.145427281318626, 'reg_alpha': 3.860242029157199e-07, 'reg_lambda': 9.490141990542972, 'max_delta_step': 3}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  63%|██████▎   | 126/200 [01:57<01:10,  1.04it/s]

[I 2025-11-10 18:09:30,335] Trial 125 finished with value: 0.5854191033138401 and parameters: {'max_depth': 9, 'learning_rate': 0.015167264279596509, 'n_estimators': 295, 'subsample': 0.5342417424898739, 'colsample_bytree': 0.9250714926752173, 'min_child_weight': 1, 'gamma': 0.20332067350262178, 'reg_alpha': 1.0944397077713213e-07, 'reg_lambda': 6.4205220345985135, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  64%|██████▎   | 127/200 [01:58<00:58,  1.25it/s]

[I 2025-11-10 18:09:30,761] Trial 129 pruned.

Best trial: 76. Best value: 0.614464:  64%|██████▍   | 128/200 [01:59<01:05,  1.09it/s]

[I 2025-11-10 18:09:31,946] Trial 126 finished with value: 0.5902534113060429 and parameters: {'max_depth': 9, 'learning_rate': 0.015485212755984254, 'n_estimators': 280, 'subsample': 0.5208423396021556, 'colsample_bytree': 0.9572144153149851, 'min_child_weight': 1, 'gamma': 0.19187230164693103, 'reg_alpha': 1.2711299991930196e-07, 'reg_lambda': 5.5580049886193414, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  64%|██████▍   | 129/200 [02:01<01:19,  1.12s/it]

[I 2025-11-10 18:09:33,544] Trial 128 finished with value: 0.5890058479532163 and parameters: {'max_depth': 9, 'learning_rate': 0.013118003731535184, 'n_estimators': 237, 'subsample': 0.6192886351403831, 'colsample_bytree': 0.99302695928969, 'min_child_weight': 1, 'gamma': 0.20685712018144925, 'reg_alpha': 0.007870559843288528, 'reg_lambda': 9.454123035065096e-05, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  65%|██████▌   | 130/200 [02:01<01:01,  1.13it/s]

[I 2025-11-10 18:09:33,878] Trial 132 pruned.

Best trial: 76. Best value: 0.614464:  66%|██████▌   | 131/200 [02:01<00:52,  1.32it/s]

[I 2025-11-10 18:09:34,335] Trial 133 pruned.

Best trial: 76. Best value: 0.614464:  66%|██████▌   | 132/200 [02:02<00:41,  1.65it/s]

[I 2025-11-10 18:09:34,588] Trial 127 finished with value: 0.5865692007797271 and parameters: {'max_depth': 9, 'learning_rate': 0.018948281581672943, 'n_estimators': 374, 'subsample': 0.6187820537997545, 'colsample_bytree': 0.9566827022093385, 'min_child_weight': 1, 'gamma': 0.21291985131391952, 'reg_alpha': 1.560119815412701e-08, 'reg_lambda': 5.768708957974389, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  66%|██████▋   | 133/200 [02:03<00:55,  1.21it/s]

[I 2025-11-10 18:09:35,932] Trial 130 finished with value: 0.5987719298245613 and parameters: {'max_depth': 9, 'learning_rate': 0.013079493611579606, 'n_estimators': 374, 'subsample': 0.52166728867006, 'colsample_bytree': 0.9839012658233807, 'min_child_weight': 1, 'gamma': 0.46932038072307236, 'reg_alpha': 1.538530961079691e-08, 'reg_lambda': 0.00016410699693870644, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  67%|██████▋   | 134/200 [02:04<01:03,  1.04it/s]

[I 2025-11-10 18:09:37,210] Trial 131 finished with value: 0.58953216374269 and parameters: {'max_depth': 9, 'learning_rate': 0.013175810575874317, 'n_estimators': 386, 'subsample': 0.5535119681598734, 'colsample_bytree': 0.9861433068757857, 'min_child_weight': 1, 'gamma': 0.44053411168802575, 'reg_alpha': 1.541138796702096e-08, 'reg_lambda': 3.18036815021778e-05, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  68%|██████▊   | 135/200 [02:06<01:16,  1.18s/it]

[I 2025-11-10 18:09:38,888] Trial 137 finished with value: 0.5949512670565301 and parameters: {'max_depth': 9, 'learning_rate': 0.281651522296629, 'n_estimators': 321, 'subsample': 0.5176592752158383, 'colsample_bytree': 0.9840483061238421, 'min_child_weight': 1, 'gamma': 0.09312325511459733, 'reg_alpha': 2.9031874689980407e-08, 'reg_lambda': 0.0008626585415510854, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  68%|██████▊   | 136/200 [02:06<00:56,  1.12it/s]

[I 2025-11-10 18:09:39,106] Trial 134 finished with value: 0.5881481481481481 and parameters: {'max_depth': 9, 'learning_rate': 0.011378770966323044, 'n_estimators': 327, 'subsample': 0.5117992475280713, 'colsample_bytree': 0.8350540114335882, 'min_child_weight': 1, 'gamma': 0.022768664026527025, 'reg_alpha': 1.0772120018629261e-08, 'reg_lambda': 0.0005988090362454594, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

[I 2025-11-10 18:09:39,356] Trial 138 pruned.

Best trial: 76. Best value: 0.614464:  70%|██████▉   | 139/200 [02:07<00:25,  2.40it/s]

[I 2025-11-10 18:09:39,541] Trial 139 pruned.
[I 2025-11-10 18:09:39,661] Trial 135 finished with value: 0.5975438596491228 and parameters: {'max_depth': 9, 'learning_rate': 0.011256317200363495, 'n_estimators': 320, 'subsample': 0.5560394723185784, 'colsample_bytree': 0.8599183985685541, 'min_child_weight': 1, 'gamma': 0.0781645522688614, 'reg_alpha': 1.1110991268533446e-08, 'reg_lambda': 1.2241313773737157e-05, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  70%|███████   | 140/200 [02:07<00:25,  2.39it/s]

[I 2025-11-10 18:09:40,086] Trial 142 pruned.

Best trial: 76. Best value: 0.614464:  70%|███████   | 141/200 [02:08<00:23,  2.53it/s]

[I 2025-11-10 18:09:40,428] Trial 141 pruned.
[I 2025-11-10 18:09:40,479] Trial 140 pruned.

Best trial: 76. Best value: 0.614464:  72%|███████▏  | 143/200 [02:08<00:19,  2.88it/s]

[I 2025-11-10 18:09:41,009] Trial 136 finished with value: 0.5961988304093566 and parameters: {'max_depth': 9, 'learning_rate': 0.01360688908906077, 'n_estimators': 320, 'subsample': 0.5559793190493886, 'colsample_bytree': 0.9852018187984873, 'min_child_weight': 1, 'gamma': 0.10379541959382793, 'reg_alpha': 2.6330119422250318e-08, 'reg_lambda': 0.0004356442098637201, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  72%|███████▏  | 144/200 [02:09<00:21,  2.58it/s]

[I 2025-11-10 18:09:41,518] Trial 144 pruned.

Best trial: 76. Best value: 0.614464:  72%|███████▎  | 145/200 [02:10<00:29,  1.88it/s]

[I 2025-11-10 18:09:42,461] Trial 145 finished with value: 0.55729044834308 and parameters: {'max_depth': 9, 'learning_rate': 0.1690223782733302, 'n_estimators': 306, 'subsample': 0.5352447143998033, 'colsample_bytree': 0.898455935981461, 'min_child_weight': 1, 'gamma': 0.09653260382796008, 'reg_alpha': 1.6227268378583844e-08, 'reg_lambda': 1.4990667426506087e-05, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  73%|███████▎  | 146/200 [02:12<01:01,  1.13s/it]

[I 2025-11-10 18:09:45,202] Trial 143 finished with value: 0.5939766081871345 and parameters: {'max_depth': 9, 'learning_rate': 0.012524157445619768, 'n_estimators': 350, 'subsample': 0.5016028611783483, 'colsample_bytree': 0.8900583351213154, 'min_child_weight': 1, 'gamma': 0.008766341261855826, 'reg_alpha': 1.0278474823798802e-08, 'reg_lambda': 0.0011671116171896516, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  74%|███████▎  | 147/200 [02:14<01:06,  1.25s/it]

[I 2025-11-10 18:09:46,759] Trial 146 finished with value: 0.5861988304093567 and parameters: {'max_depth': 9, 'learning_rate': 0.011008386161185612, 'n_estimators': 354, 'subsample': 0.5557137493383892, 'colsample_bytree': 0.9916528308297003, 'min_child_weight': 1, 'gamma': 0.017152541608430938, 'reg_alpha': 1.49734431769838e-08, 'reg_lambda': 1.5493427380039364e-05, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  74%|███████▍  | 148/200 [02:14<00:53,  1.03s/it]

[I 2025-11-10 18:09:47,231] Trial 147 finished with value: 0.58953216374269 and parameters: {'max_depth': 9, 'learning_rate': 0.010815804441124559, 'n_estimators': 358, 'subsample': 0.5326280337604966, 'colsample_bytree': 0.9984952524053837, 'min_child_weight': 1, 'gamma': 0.0040830097321625175, 'reg_alpha': 1.554674473458563e-08, 'reg_lambda': 0.0008716851987081855, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  74%|███████▍  | 149/200 [02:15<00:41,  1.24it/s]

[I 2025-11-10 18:09:47,486] Trial 148 finished with value: 0.5847173489278752 and parameters: {'max_depth': 9, 'learning_rate': 0.011112548397466308, 'n_estimators': 354, 'subsample': 0.5016265244337736, 'colsample_bytree': 0.9923850934881275, 'min_child_weight': 1, 'gamma': 0.3052073799815707, 'reg_alpha': 1.0110840396174464e-08, 'reg_lambda': 0.0010870907226517, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  75%|███████▌  | 150/200 [02:16<00:43,  1.15it/s]

[I 2025-11-10 18:09:48,515] Trial 151 pruned.

Best trial: 76. Best value: 0.614464:  76%|███████▌  | 151/200 [02:17<00:54,  1.11s/it]

[I 2025-11-10 18:09:50,190] Trial 149 finished with value: 0.5928460038986354 and parameters: {'max_depth': 9, 'learning_rate': 0.010910647445741566, 'n_estimators': 251, 'subsample': 0.6915857817734608, 'colsample_bytree': 0.9984960637326699, 'min_child_weight': 1, 'gamma': 0.27261821777689876, 'reg_alpha': 1.6516000295136984e-08, 'reg_lambda': 0.00014360141704751716, 'max_delta_step': 1}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  76%|███████▌  | 152/200 [02:18<00:42,  1.13it/s]

[I 2025-11-10 18:09:50,544] Trial 150 finished with value: 0.5942105263157895 and parameters: {'max_depth': 9, 'learning_rate': 0.013780782367476326, 'n_estimators': 247, 'subsample': 0.5336973362685422, 'colsample_bytree': 0.9956923949055884, 'min_child_weight': 1, 'gamma': 0.2721969261290644, 'reg_alpha': 2.1167439825637902e-08, 'reg_lambda': 0.0009358427375223642, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  76%|███████▋  | 153/200 [02:18<00:36,  1.27it/s]

[I 2025-11-10 18:09:51,101] Trial 152 finished with value: 0.5893957115009746 and parameters: {'max_depth': 10, 'learning_rate': 0.013692754907033762, 'n_estimators': 234, 'subsample': 0.572548659462463, 'colsample_bytree': 0.9517019530755978, 'min_child_weight': 1, 'gamma': 0.5077448470838694, 'reg_alpha': 2.404231491947086e-08, 'reg_lambda': 0.00013154768689129076, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  77%|███████▋  | 154/200 [02:19<00:38,  1.19it/s]

[I 2025-11-10 18:09:52,068] Trial 153 finished with value: 0.5703703703703703 and parameters: {'max_depth': 10, 'learning_rate': 0.013840697564779502, 'n_estimators': 220, 'subsample': 0.5715024548242007, 'colsample_bytree': 0.951968309814629, 'min_child_weight': 1, 'gamma': 0.5171968055031144, 'reg_alpha': 3.04402050001617e-08, 'reg_lambda': 0.00012954067408146711, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  78%|███████▊  | 156/200 [02:21<00:34,  1.28it/s]

[I 2025-11-10 18:09:53,611] Trial 154 finished with value: 0.5920077972709551 and parameters: {'max_depth': 9, 'learning_rate': 0.013807251669257873, 'n_estimators': 201, 'subsample': 0.5452137709312503, 'colsample_bytree': 0.9484729348468929, 'min_child_weight': 1, 'gamma': 0.1196898657768104, 'reg_alpha': 4.1495005955803876e-08, 'reg_lambda': 3.0394057709067238e-05, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.
[I 2025-11-10 18:09:53,762] Trial 155 finished with value: 0.5965692007797271 and parameters: {'max_depth': 9, 'learning_rate': 0.014193864427055752, 'n_estimators': 201, 'subsample': 0.5351309134544174, 'colsample_bytree': 0.9753979972062697, 'min_child_weight': 1, 'gamma': 0.5376774630985567, 'reg_alpha': 3.8513085209003255e-08, 'reg_lambda': 0.002611478469386715, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  78%|███████▊  | 157/200 [02:22<00:33,  1.27it/s]

[I 2025-11-10 18:09:54,563] Trial 156 finished with value: 0.5938401559454191 and parameters: {'max_depth': 9, 'learning_rate': 0.014111544443474755, 'n_estimators': 216, 'subsample': 0.535677085762692, 'colsample_bytree': 0.9840626016424178, 'min_child_weight': 1, 'gamma': 0.3696170476295485, 'reg_alpha': 3.6287012028690015e-08, 'reg_lambda': 0.011814391212617662, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 76. Best value: 0.614464:  79%|███████▉  | 158/200 [02:23<00:43,  1.04s/it]

[I 2025-11-10 18:09:56,199] Trial 157 finished with value: 0.5866861598440545 and parameters: {'max_depth': 9, 'learning_rate': 0.012224854980361572, 'n_estimators': 266, 'subsample': 0.5354931300872803, 'colsample_bytree': 0.9796429174696677, 'min_child_weight': 1, 'gamma': 0.383723951632905, 'reg_alpha': 4.8179660734030576e-08, 'reg_lambda': 5.879348384487746e-06, 'max_delta_step': 2}. Best is trial 76 with value: 0.6144639376218324.

Best trial: 159. Best value: 0.617544:  80%|███████▉  | 159/200 [02:25<00:51,  1.26s/it]

[I 2025-11-10 18:09:57,958] Trial 159 finished with value: 0.6175438596491227 and parameters: {'max_depth': 9, 'learning_rate': 0.012107806261078269, 'n_estimators': 321, 'subsample': 0.513903906431983, 'colsample_bytree': 0.9780965835977318, 'min_child_weight': 1, 'gamma': 0.8020261381723204, 'reg_alpha': 5.872227187549671e-08, 'reg_lambda': 9.223992621989752e-06, 'max_delta_step': 3}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  80%|████████  | 160/200 [02:25<00:38,  1.05it/s]

[I 2025-11-10 18:09:58,198] Trial 158 finished with value: 0.5947173489278752 and parameters: {'max_depth': 9, 'learning_rate': 0.011884205567619745, 'n_estimators': 313, 'subsample': 0.5354024834364185, 'colsample_bytree': 0.9750337272466031, 'min_child_weight': 1, 'gamma': 0.41253485838458714, 'reg_alpha': 5.070767922464841e-08, 'reg_lambda': 0.0017705984836953311, 'max_delta_step': 2}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  80%|████████  | 161/200 [02:26<00:30,  1.28it/s]

[I 2025-11-10 18:09:58,583] Trial 163 pruned.

Best trial: 159. Best value: 0.617544:  82%|████████▏ | 163/200 [02:26<00:17,  2.09it/s]

[I 2025-11-10 18:09:58,777] Trial 160 finished with value: 0.597037037037037 and parameters: {'max_depth': 9, 'learning_rate': 0.01187893782330369, 'n_estimators': 305, 'subsample': 0.5192759323522128, 'colsample_bytree': 0.9785393862300769, 'min_child_weight': 1, 'gamma': 0.6153495342588441, 'reg_alpha': 5.329900809697645e-08, 'reg_lambda': 0.0021813174818141714, 'max_delta_step': 3}. Best is trial 159 with value: 0.6175438596491227.
[I 2025-11-10 18:09:58,959] Trial 164 pruned.

Best trial: 159. Best value: 0.617544:  82%|████████▏ | 164/200 [02:27<00:21,  1.65it/s]

[I 2025-11-10 18:09:59,857] Trial 165 pruned.

Best trial: 159. Best value: 0.617544:  82%|████████▎ | 165/200 [02:27<00:17,  1.95it/s]

[I 2025-11-10 18:10:00,156] Trial 166 pruned.

Best trial: 159. Best value: 0.617544:  83%|████████▎ | 166/200 [02:28<00:18,  1.81it/s]

[I 2025-11-10 18:10:00,793] Trial 161 finished with value: 0.6033528265107211 and parameters: {'max_depth': 9, 'learning_rate': 0.010036669655043207, 'n_estimators': 311, 'subsample': 0.5150436203789747, 'colsample_bytree': 0.9739732447536474, 'min_child_weight': 1, 'gamma': 0.6789809499593893, 'reg_alpha': 7.687777099294726e-08, 'reg_lambda': 8.540851592300744e-06, 'max_delta_step': 3}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  84%|████████▎ | 167/200 [02:30<00:29,  1.14it/s]

[I 2025-11-10 18:10:02,440] Trial 162 finished with value: 0.6097660818713451 and parameters: {'max_depth': 10, 'learning_rate': 0.011667797819484283, 'n_estimators': 329, 'subsample': 0.5149522859383533, 'colsample_bytree': 0.968147764106267, 'min_child_weight': 1, 'gamma': 0.8435613161159171, 'reg_alpha': 8.659584453012197e-08, 'reg_lambda': 5.030468105456039e-05, 'max_delta_step': 3}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  84%|████████▍ | 168/200 [02:30<00:27,  1.15it/s]

[I 2025-11-10 18:10:03,288] Trial 170 pruned.

Best trial: 159. Best value: 0.617544:  84%|████████▍ | 169/200 [02:31<00:23,  1.31it/s]

[I 2025-11-10 18:10:03,809] Trial 171 pruned.

Best trial: 159. Best value: 0.617544:  85%|████████▌ | 170/200 [02:31<00:18,  1.60it/s]

[I 2025-11-10 18:10:04,111] Trial 167 finished with value: 0.5990253411306042 and parameters: {'max_depth': 9, 'learning_rate': 0.01022126410711763, 'n_estimators': 282, 'subsample': 0.5517023231331387, 'colsample_bytree': 0.9856882297115742, 'min_child_weight': 1, 'gamma': 0.874297397610378, 'reg_alpha': 1.8172392695462055e-07, 'reg_lambda': 1.0545713847500948e-05, 'max_delta_step': 3}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  86%|████████▌ | 171/200 [02:32<00:15,  1.92it/s]

[I 2025-11-10 18:10:04,392] Trial 168 finished with value: 0.5844444444444445 and parameters: {'max_depth': 8, 'learning_rate': 0.010082937872999877, 'n_estimators': 275, 'subsample': 0.5555672706116775, 'colsample_bytree': 0.9623238233260215, 'min_child_weight': 1, 'gamma': 0.8600406208371019, 'reg_alpha': 1.904481046993592e-07, 'reg_lambda': 0.00047134937007850644, 'max_delta_step': 4}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  86%|████████▋ | 173/200 [02:32<00:09,  2.80it/s]

[I 2025-11-10 18:10:04,703] Trial 169 finished with value: 0.6007602339181286 and parameters: {'max_depth': 3, 'learning_rate': 0.010079080686546836, 'n_estimators': 263, 'subsample': 0.5516247223784728, 'colsample_bytree': 0.9641680679608701, 'min_child_weight': 1, 'gamma': 0.7357026208171211, 'reg_alpha': 2.0147174632317033e-07, 'reg_lambda': 1.056286012555961e-05, 'max_delta_step': 4}. Best is trial 159 with value: 0.6175438596491227.
[I 2025-11-10 18:10:04,825] Trial 172 pruned.

Best trial: 159. Best value: 0.617544:  87%|████████▋ | 174/200 [02:35<00:32,  1.25s/it]

[I 2025-11-10 18:10:08,143] Trial 173 finished with value: 0.6025925925925926 and parameters: {'max_depth': 10, 'learning_rate': 0.010073273386364741, 'n_estimators': 269, 'subsample': 0.5096262447586014, 'colsample_bytree': 0.9457016794477353, 'min_child_weight': 1, 'gamma': 1.04181556487082, 'reg_alpha': 1.946829762973093e-07, 'reg_lambda': 2.81238590962042e-06, 'max_delta_step': 4}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  88%|████████▊ | 175/200 [02:36<00:24,  1.03it/s]

[I 2025-11-10 18:10:08,484] Trial 175 finished with value: 0.6069395711500973 and parameters: {'max_depth': 3, 'learning_rate': 0.010678251514824929, 'n_estimators': 250, 'subsample': 0.5270343554773107, 'colsample_bytree': 0.9477114217287951, 'min_child_weight': 1, 'gamma': 1.0506065121462431, 'reg_alpha': 1.990441809420761e-07, 'reg_lambda': 3.985818983734365e-06, 'max_delta_step': 4}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  88%|████████▊ | 176/200 [02:36<00:18,  1.29it/s]

[I 2025-11-10 18:10:08,791] Trial 176 finished with value: 0.5969395711500974 and parameters: {'max_depth': 10, 'learning_rate': 0.010729847466667088, 'n_estimators': 250, 'subsample': 0.526326177387881, 'colsample_bytree': 0.9467964823837645, 'min_child_weight': 1, 'gamma': 0.7192002950752596, 'reg_alpha': 6.854230175473237e-07, 'reg_lambda': 4.110538666345394e-06, 'max_delta_step': 3}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  88%|████████▊ | 177/200 [02:36<00:13,  1.66it/s]

[I 2025-11-10 18:10:08,995] Trial 174 finished with value: 0.6089083820662768 and parameters: {'max_depth': 10, 'learning_rate': 0.011770133951254374, 'n_estimators': 308, 'subsample': 0.5469773449914408, 'colsample_bytree': 0.8768887274982086, 'min_child_weight': 1, 'gamma': 0.7860908355202373, 'reg_alpha': 1.5124382843890488e-08, 'reg_lambda': 4.201450096856733e-06, 'max_delta_step': 3}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  89%|████████▉ | 178/200 [02:39<00:27,  1.24s/it]

[I 2025-11-10 18:10:11,736] Trial 177 finished with value: 0.6042300194931773 and parameters: {'max_depth': 3, 'learning_rate': 0.010704704092949465, 'n_estimators': 250, 'subsample': 0.5262670271760879, 'colsample_bytree': 0.9535712817992651, 'min_child_weight': 1, 'gamma': 1.1688081629402787, 'reg_alpha': 4.571485833263752e-07, 'reg_lambda': 4.276396493258906e-06, 'max_delta_step': 3}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  90%|█████████ | 180/200 [02:39<00:14,  1.33it/s]

[I 2025-11-10 18:10:12,204] Trial 178 finished with value: 0.6051851851851853 and parameters: {'max_depth': 3, 'learning_rate': 0.01072992038632355, 'n_estimators': 258, 'subsample': 0.5099476854168924, 'colsample_bytree': 0.9443989677827688, 'min_child_weight': 1, 'gamma': 0.9388092406504878, 'reg_alpha': 1.9468942919202586e-07, 'reg_lambda': 4.657481463009716e-06, 'max_delta_step': 4}. Best is trial 159 with value: 0.6175438596491227.
[I 2025-11-10 18:10:12,346] Trial 179 finished with value: 0.5966666666666667 and parameters: {'max_depth': 3, 'learning_rate': 0.010663836026070395, 'n_estimators': 257, 'subsample': 0.5077573648415569, 'colsample_bytree': 0.929804996739097, 'min_child_weight': 1, 'gamma': 1.231090013427852, 'reg_alpha': 6.868683644590903e-07, 'reg_lambda': 3.867193740080958e-06, 'max_delta_step': 4}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  90%|█████████ | 181/200 [02:40<00:13,  1.37it/s]

[I 2025-11-10 18:10:13,022] Trial 180 finished with value: 0.6088888888888888 and parameters: {'max_depth': 4, 'learning_rate': 0.010651436646850683, 'n_estimators': 302, 'subsample': 0.508599517614214, 'colsample_bytree': 0.9450574305547256, 'min_child_weight': 1, 'gamma': 1.3763371189799494, 'reg_alpha': 6.241988016959929e-07, 'reg_lambda': 4.991296826096727e-06, 'max_delta_step': 4}. Best is trial 159 with value: 0.6175438596491227.
[I 2025-11-10 18:10:13,112] Trial 182 pruned.

Best trial: 159. Best value: 0.617544:  92%|█████████▏| 183/200 [02:44<00:21,  1.28s/it]

[I 2025-11-10 18:10:16,878] Trial 181 finished with value: 0.5996491228070175 and parameters: {'max_depth': 3, 'learning_rate': 0.01092605303529274, 'n_estimators': 260, 'subsample': 0.5234493287523216, 'colsample_bytree': 0.9427580317926432, 'min_child_weight': 1, 'gamma': 1.1569864777909262, 'reg_alpha': 5.635522092007406e-07, 'reg_lambda': 3.38442845154273e-06, 'max_delta_step': 4}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  92%|█████████▏| 184/200 [02:45<00:18,  1.18s/it]

[I 2025-11-10 18:10:17,728] Trial 183 finished with value: 0.5974074074074073 and parameters: {'max_depth': 3, 'learning_rate': 0.01159028330418163, 'n_estimators': 301, 'subsample': 0.5151198470168783, 'colsample_bytree': 0.9406534975951656, 'min_child_weight': 1, 'gamma': 1.123962845455182, 'reg_alpha': 3.057607995163985e-07, 'reg_lambda': 5.888877930383316e-06, 'max_delta_step': 4}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  92%|█████████▎| 185/200 [02:45<00:15,  1.03s/it]

[I 2025-11-10 18:10:18,354] Trial 184 finished with value: 0.6007602339181286 and parameters: {'max_depth': 3, 'learning_rate': 0.011521303522171887, 'n_estimators': 299, 'subsample': 0.5161999302091482, 'colsample_bytree': 0.9562130113398436, 'min_child_weight': 1, 'gamma': 1.393207686050837, 'reg_alpha': 2.1256443647231647e-07, 'reg_lambda': 2.384844927289809e-06, 'max_delta_step': 4}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  93%|█████████▎| 186/200 [02:46<00:11,  1.18it/s]

[I 2025-11-10 18:10:18,705] Trial 185 finished with value: 0.613606237816764 and parameters: {'max_depth': 4, 'learning_rate': 0.011515588936134377, 'n_estimators': 304, 'subsample': 0.5180166662634146, 'colsample_bytree': 0.9613114858818905, 'min_child_weight': 1, 'gamma': 0.9885506427310831, 'reg_alpha': 3.0210679572494375e-07, 'reg_lambda': 5.280603353818414e-06, 'max_delta_step': 4}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  94%|█████████▎| 187/200 [02:48<00:14,  1.11s/it]

[I 2025-11-10 18:10:20,499] Trial 186 finished with value: 0.5971929824561403 and parameters: {'max_depth': 3, 'learning_rate': 0.010641865945293942, 'n_estimators': 275, 'subsample': 0.5262899510116713, 'colsample_bytree': 0.9221375724792349, 'min_child_weight': 1, 'gamma': 1.1270763068294156, 'reg_alpha': 3.4604130813842845e-07, 'reg_lambda': 1.654996418679724e-06, 'max_delta_step': 4}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  94%|█████████▍| 188/200 [02:49<00:12,  1.08s/it]

[I 2025-11-10 18:10:21,497] Trial 187 finished with value: 0.598167641325536 and parameters: {'max_depth': 3, 'learning_rate': 0.010024426617013442, 'n_estimators': 270, 'subsample': 0.52639160972476, 'colsample_bytree': 0.9558764715378093, 'min_child_weight': 1, 'gamma': 1.0077196811275733, 'reg_alpha': 1.2368353424111462e-06, 'reg_lambda': 1.1273918548783807e-05, 'max_delta_step': 4}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  94%|█████████▍| 189/200 [02:49<00:09,  1.14it/s]

[I 2025-11-10 18:10:21,881] Trial 188 finished with value: 0.5874074074074074 and parameters: {'max_depth': 3, 'learning_rate': 0.01058723704688184, 'n_estimators': 272, 'subsample': 0.5015351799556262, 'colsample_bytree': 0.924255817172106, 'min_child_weight': 1, 'gamma': 1.3465167566389793, 'reg_alpha': 4.3013808780822895e-07, 'reg_lambda': 1.9550843771964304e-06, 'max_delta_step': 4}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  96%|█████████▌| 191/200 [02:50<00:05,  1.77it/s]

[I 2025-11-10 18:10:22,280] Trial 191 pruned.
[I 2025-11-10 18:10:22,432] Trial 189 finished with value: 0.5842105263157895 and parameters: {'max_depth': 3, 'learning_rate': 0.010045794101660035, 'n_estimators': 275, 'subsample': 0.5261640858956973, 'colsample_bytree': 0.9253956902331798, 'min_child_weight': 1, 'gamma': 1.375887324827434, 'reg_alpha': 4.822492774623134e-07, 'reg_lambda': 1.8046400773227493e-06, 'max_delta_step': 4}. Best is trial 159 with value: 0.6175438596491227.

Best trial: 159. Best value: 0.617544:  96%|█████████▌| 192/200 [02:50<00:03,  2.25it/s]

[I 2025-11-10 18:10:22,595] Trial 193 pruned.

Best trial: 159. Best value: 0.617544:  96%|█████████▋| 193/200 [02:51<00:03,  1.82it/s]

[I 2025-11-10 18:10:23,391] Trial 194 pruned.

Best trial: 190. Best value: 0.617934:  97%|█████████▋| 194/200 [02:51<00:03,  1.61it/s]

[I 2025-11-10 18:10:24,187] Trial 190 finished with value: 0.6179337231968811 and parameters: {'max_depth': 4, 'learning_rate': 0.010022891790063404, 'n_estimators': 266, 'subsample': 0.5055264252867265, 'colsample_bytree': 0.9538676805696967, 'min_child_weight': 1, 'gamma': 1.3949012415069162, 'reg_alpha': 1.1006283230241055e-06, 'reg_lambda': 3.1662591131737026e-06, 'max_delta_step': 5}. Best is trial 190 with value: 0.6179337231968811.

Best trial: 190. Best value: 0.617934:  98%|█████████▊| 195/200 [02:52<00:03,  1.48it/s]

[I 2025-11-10 18:10:24,992] Trial 197 pruned.

Best trial: 190. Best value: 0.617934:  98%|█████████▊| 196/200 [02:53<00:02,  1.56it/s]

[I 2025-11-10 18:10:25,549] Trial 192 finished with value: 0.6089083820662768 and parameters: {'max_depth': 4, 'learning_rate': 0.010032563124052808, 'n_estimators': 250, 'subsample': 0.5120822169488427, 'colsample_bytree': 0.9337354936696775, 'min_child_weight': 1, 'gamma': 1.0198790518757381, 'reg_alpha': 4.826008154437978e-07, 'reg_lambda': 3.043398277399461e-06, 'max_delta_step': 5}. Best is trial 190 with value: 0.6179337231968811.

Best trial: 190. Best value: 0.617934:  98%|█████████▊| 197/200 [02:54<00:02,  1.28it/s]

[I 2025-11-10 18:10:26,656] Trial 195 finished with value: 0.6077972709551658 and parameters: {'max_depth': 4, 'learning_rate': 0.0120127462518677, 'n_estimators': 302, 'subsample': 0.5172749298932293, 'colsample_bytree': 0.9634840661454281, 'min_child_weight': 1, 'gamma': 0.9243090562454158, 'reg_alpha': 1.9273526888264185e-07, 'reg_lambda': 6.271878413739912e-06, 'max_delta_step': 5}. Best is trial 190 with value: 0.6179337231968811.

Best trial: 190. Best value: 0.617934:  99%|█████████▉| 198/200 [02:54<00:01,  1.47it/s]

[I 2025-11-10 18:10:27,105] Trial 196 finished with value: 0.6006237816764133 and parameters: {'max_depth': 3, 'learning_rate': 0.012174328616999828, 'n_estimators': 302, 'subsample': 0.51802411946457, 'colsample_bytree': 0.9389780270047254, 'min_child_weight': 1, 'gamma': 1.4795901604803465, 'reg_alpha': 7.360871531016057e-07, 'reg_lambda': 8.010340336078892e-06, 'max_delta_step': 5}. Best is trial 190 with value: 0.6179337231968811.

Best trial: 190. Best value: 0.617934: 100%|█████████▉| 199/200 [02:55<00:00,  1.33it/s]

[I 2025-11-10 18:10:28,019] Trial 198 finished with value: 0.6089083820662768 and parameters: {'max_depth': 4, 'learning_rate': 0.010894091056727681, 'n_estimators': 225, 'subsample': 0.5174225519035871, 'colsample_bytree': 0.9639094369573579, 'min_child_weight': 1, 'gamma': 1.1604572336404904, 'reg_alpha': 8.814229200484386e-07, 'reg_lambda': 3.5046268413687208e-06, 'max_delta_step': 5}. Best is trial 190 with value: 0.6179337231968811.

Best trial: 190. Best value: 0.617934: 100%|██████████| 200/200 [02:55<00:00,  1.14it/s]

[I 2025-11-10 18:10:28,305] Trial 199 finished with value: 0.6105068226120858 and parameters: {'max_depth': 4, 'learning_rate': 0.01083785714460862, 'n_estimators': 222, 'subsample': 0.5165676404683904, 'colsample_bytree': 0.9318972008981249, 'min_child_weight': 1, 'gamma': 1.6441187486361555, 'reg_alpha': 1.1769374728930422e-06, 'reg_lambda': 3.5310190434458505e-06, 'max_delta_step': 5}. Best is trial 190 with value: 0.6179337231968811.

[I 2025-11-10 18:10:29,194] A new study created in memory with name: 3_5_roc_auc
Best trial: 3. Best value: 0.5:   0%|          | 1/200 [00:01<05:19,  1.61s/it]

[I 2025-11-10 18:10:30,801] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.26039777587480906, 'n_estimators': 391, 'subsample': 0.8127391903565493, 'colsample_bytree': 0.9372789717571589, 'min_child_weight': 8, 'gamma': 1.0630607996654085, 'reg_alpha': 0.10193990825757002, 'reg_lambda': 0.005620608441194292, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 1. Best value: 0.579786:   1%|          | 2/200 [00:02<04:39,  1.41s/it]

[I 2025-11-10 18:10:32,080] Trial 1 finished with value: 0.5797855750487328 and parameters: {'max_depth': 5, 'learning_rate': 0.13542302889924365, 'n_estimators': 495, 'subsample': 0.9295547850152401, 'colsample_bytree': 0.9852262429843793, 'min_child_weight': 2, 'gamma': 1.1025065246318988, 'reg_alpha': 0.000343556365024539, 'reg_lambda': 0.004260820529346146, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:   2%|▏         | 3/200 [00:03<04:10,  1.27s/it]

[I 2025-11-10 18:10:33,184] Trial 2 finished with value: 0.5439376218323586 and parameters: {'max_depth': 8, 'learning_rate': 0.07155513713122642, 'n_estimators': 769, 'subsample': 0.5765031576218753, 'colsample_bytree': 0.5440706657906412, 'min_child_weight': 1, 'gamma': 2.0574705088672243, 'reg_alpha': 3.551276273271617, 'reg_lambda': 7.19033039762689e-08, 'max_delta_step': 10}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:   2%|▏         | 4/200 [00:05<04:31,  1.38s/it]

[I 2025-11-10 18:10:34,731] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.012065875894144916, 'n_estimators': 1360, 'subsample': 0.5904433334233644, 'colsample_bytree': 0.9396900165617192, 'min_child_weight': 9, 'gamma': 1.2869237564020353, 'reg_alpha': 2.3297574323621295e-07, 'reg_lambda': 0.1321170511334882, 'max_delta_step': 6}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:   2%|▎         | 5/200 [00:06<03:32,  1.09s/it]

[I 2025-11-10 18:10:35,300] Trial 5 finished with value: 0.5099220272904483 and parameters: {'max_depth': 9, 'learning_rate': 0.07290215168584833, 'n_estimators': 596, 'subsample': 0.9306684626921609, 'colsample_bytree': 0.8636650973691964, 'min_child_weight': 3, 'gamma': 2.762339406584327, 'reg_alpha': 6.719831353314227e-05, 'reg_lambda': 0.06525315856760246, 'max_delta_step': 1}. Best is trial 1 with value: 0.5797855750487328.
[I 2025-11-10 18:10:35,326] Trial 6 finished with value: 0.4776705653021442 and parameters: {'max_depth': 3, 'learning_rate': 0.025647081571186472, 'n_estimators': 510, 'subsample': 0.6278656822858515, 'colsample_bytree': 0.7024618647453102, 'min_child_weight': 4, 'gamma': 0.08568126396138243, 'reg_alpha': 0.0004971596396028624, 'reg_lambda': 0.9143806281222976, 'max_delta_step': 5}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:   4%|▎         | 7/200 [00:06<02:15,  1.42it/s]

[I 2025-11-10 18:10:35,955] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.037903892438485305, 'n_estimators': 1374, 'subsample': 0.9640410550085647, 'colsample_bytree': 0.5047318337752724, 'min_child_weight': 9, 'gamma': 1.0464943199317993, 'reg_alpha': 0.0002289597522532936, 'reg_lambda': 0.002681842979242681, 'max_delta_step': 0}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:   4%|▍         | 8/200 [00:07<02:26,  1.31it/s]

[I 2025-11-10 18:10:36,881] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.2307688783755925, 'n_estimators': 481, 'subsample': 0.7112608640561167, 'colsample_bytree': 0.9497630097578262, 'min_child_weight': 9, 'gamma': 1.423084685200704, 'reg_alpha': 4.251237590987345, 'reg_lambda': 0.48752329517583276, 'max_delta_step': 3}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:   4%|▍         | 9/200 [00:10<03:59,  1.25s/it]

[I 2025-11-10 18:10:39,417] Trial 8 finished with value: 0.5352046783625731 and parameters: {'max_depth': 8, 'learning_rate': 0.012482741112797707, 'n_estimators': 472, 'subsample': 0.5967319562421551, 'colsample_bytree': 0.8331517435169706, 'min_child_weight': 1, 'gamma': 3.149522238349938, 'reg_alpha': 6.9527758219199e-08, 'reg_lambda': 1.1779338244598522e-05, 'max_delta_step': 5}. Best is trial 1 with value: 0.5797855750487328.
[I 2025-11-10 18:10:39,423] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.22256443384300764, 'n_estimators': 679, 'subsample': 0.5521274130425222, 'colsample_bytree': 0.7732386305160406, 'min_child_weight': 6, 'gamma': 3.8735624080615456, 'reg_alpha': 7.174864629505243e-05, 'reg_lambda': 2.5601055018062257e-06, 'max_delta_step': 4}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:   6%|▌         | 11/200 [00:10<02:23,  1.32it/s]

[I 2025-11-10 18:10:39,680] Trial 12 pruned.
[I 2025-11-10 18:10:39,750] Trial 13 pruned.

Best trial: 1. Best value: 0.579786:   6%|▋         | 13/200 [00:10<01:43,  1.81it/s]

[I 2025-11-10 18:10:40,141] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.03397122325568165, 'n_estimators': 1259, 'subsample': 0.8966472166912013, 'colsample_bytree': 0.5186851491778699, 'min_child_weight': 9, 'gamma': 1.955425859223432, 'reg_alpha': 0.042382109960794355, 'reg_lambda': 0.23860394961187914, 'max_delta_step': 9}. Best is trial 1 with value: 0.5797855750487328.
[I 2025-11-10 18:10:40,165] Trial 10 finished with value: 0.5329629629629629 and parameters: {'max_depth': 9, 'learning_rate': 0.12527467923180075, 'n_estimators': 1017, 'subsample': 0.9077187743166447, 'colsample_bytree': 0.6367120113781577, 'min_child_weight': 4, 'gamma': 3.061951457641884, 'reg_alpha': 0.4186834569978041, 'reg_lambda': 0.014547427632683796, 'max_delta_step': 7}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:   8%|▊         | 15/200 [00:11<01:26,  2.13it/s]

[I 2025-11-10 18:10:40,774] Trial 15 pruned.

Best trial: 1. Best value: 0.579786:   8%|▊         | 16/200 [00:11<01:22,  2.23it/s]

[I 2025-11-10 18:10:41,139] Trial 17 pruned.

Best trial: 1. Best value: 0.579786:   8%|▊         | 17/200 [00:12<01:15,  2.44it/s]

[I 2025-11-10 18:10:41,417] Trial 18 pruned.

Best trial: 1. Best value: 0.579786:   9%|▉         | 18/200 [00:12<01:21,  2.24it/s]

[I 2025-11-10 18:10:41,974] Trial 19 pruned.

Best trial: 1. Best value: 0.579786:  10%|▉         | 19/200 [00:15<03:07,  1.04s/it]

[I 2025-11-10 18:10:44,722] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09897143531642592, 'n_estimators': 972, 'subsample': 0.7112730169409465, 'colsample_bytree': 0.5093363603365287, 'min_child_weight': 1, 'gamma': 2.0423518237565106, 'reg_alpha': 9.837048243582958, 'reg_lambda': 2.190020589661426e-08, 'max_delta_step': 10}. Best is trial 1 with value: 0.5797855750487328.
[I 2025-11-10 18:10:44,745] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.16582104049294072, 'n_estimators': 841, 'subsample': 0.9964941569381977, 'colsample_bytree': 0.7432061062298776, 'min_child_weight': 6, 'gamma': 0.5116919763191901, 'reg_alpha': 0.0026573997878574554, 'reg_lambda': 9.345729599232936e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  10%|█         | 21/200 [00:16<02:18,  1.29it/s]

[I 2025-11-10 18:10:45,544] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.07642659384378145, 'n_estimators': 1034, 'subsample': 0.500239461859779, 'colsample_bytree': 0.5851096593743412, 'min_child_weight': 1, 'gamma': 0.011707300778796448, 'reg_alpha': 9.083686876911406, 'reg_lambda': 1.0497197348494916e-08, 'max_delta_step': 7}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  11%|█         | 22/200 [00:16<02:07,  1.40it/s]

[I 2025-11-10 18:10:46,077] Trial 24 pruned.

Best trial: 1. Best value: 0.579786:  12%|█▏        | 23/200 [00:17<01:45,  1.68it/s]

[I 2025-11-10 18:10:46,313] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04662961314187764, 'n_estimators': 332, 'subsample': 0.662921347142846, 'colsample_bytree': 0.8255428373588998, 'min_child_weight': 7, 'gamma': 0.7186470773164311, 'reg_alpha': 0.809148728783301, 'reg_lambda': 6.410218944844309, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  12%|█▏        | 24/200 [00:17<01:26,  2.04it/s]

[I 2025-11-10 18:10:46,505] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04186076639181788, 'n_estimators': 1088, 'subsample': 0.6689183672211328, 'colsample_bytree': 0.7579946294376155, 'min_child_weight': 7, 'gamma': 0.6398711340815144, 'reg_alpha': 0.0014717300718385972, 'reg_lambda': 0.0007702034329187581, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  12%|█▎        | 25/200 [00:17<01:18,  2.22it/s]

[I 2025-11-10 18:10:46,852] Trial 25 pruned.

Best trial: 1. Best value: 0.579786:  14%|█▎        | 27/200 [00:18<00:56,  3.09it/s]

[I 2025-11-10 18:10:47,075] Trial 26 pruned.
[I 2025-11-10 18:10:47,241] Trial 27 pruned.

Best trial: 1. Best value: 0.579786:  14%|█▍        | 28/200 [00:18<00:58,  2.95it/s]

[I 2025-11-10 18:10:47,616] Trial 28 pruned.

Best trial: 1. Best value: 0.579786:  14%|█▍        | 29/200 [00:18<00:52,  3.28it/s]

[I 2025-11-10 18:10:47,838] Trial 29 pruned.

Best trial: 1. Best value: 0.579786:  15%|█▌        | 30/200 [00:18<00:46,  3.68it/s]

[I 2025-11-10 18:10:48,034] Trial 30 pruned.

Best trial: 1. Best value: 0.579786:  16%|█▌        | 31/200 [00:19<01:00,  2.79it/s]

[I 2025-11-10 18:10:48,594] Trial 31 pruned.

Best trial: 1. Best value: 0.579786:  16%|█▌        | 32/200 [00:19<00:57,  2.92it/s]

[I 2025-11-10 18:10:48,903] Trial 32 pruned.

Best trial: 1. Best value: 0.579786:  16%|█▋        | 33/200 [00:20<01:15,  2.20it/s]

[I 2025-11-10 18:10:49,619] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04656940145795487, 'n_estimators': 1139, 'subsample': 0.6571063668792121, 'colsample_bytree': 0.761915884718952, 'min_child_weight': 6, 'gamma': 0.793042046872382, 'reg_alpha': 0.0008971267427967838, 'reg_lambda': 5.6199359873466985, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

[I 2025-11-10 18:10:49,809] Trial 34 pruned.

Best trial: 1. Best value: 0.579786:  18%|█▊        | 35/200 [00:20<00:52,  3.15it/s]

[I 2025-11-10 18:10:49,991] Trial 35 pruned.

Best trial: 1. Best value: 0.579786:  18%|█▊        | 36/200 [00:21<01:03,  2.57it/s]

[I 2025-11-10 18:10:50,546] Trial 36 pruned.

Best trial: 1. Best value: 0.579786:  18%|█▊        | 37/200 [00:22<01:24,  1.93it/s]

[I 2025-11-10 18:10:51,363] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.15404339176553902, 'n_estimators': 304, 'subsample': 0.6156829286949898, 'colsample_bytree': 0.7011731387347215, 'min_child_weight': 5, 'gamma': 4.199416241371775, 'reg_alpha': 0.11249177734794541, 'reg_lambda': 0.006645564953420481, 'max_delta_step': 5}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  19%|█▉        | 38/200 [00:23<02:12,  1.23it/s]

[I 2025-11-10 18:10:52,877] Trial 33 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.01300528833241052, 'n_estimators': 1152, 'subsample': 0.6144063277651214, 'colsample_bytree': 0.694931905855273, 'min_child_weight': 5, 'gamma': 1.6301091055874808, 'reg_alpha': 8.053602503574492e-08, 'reg_lambda': 0.03257231691626123, 'max_delta_step': 2}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  20%|██        | 40/200 [00:24<01:36,  1.66it/s]

[I 2025-11-10 18:10:53,650] Trial 41 pruned.
[I 2025-11-10 18:10:53,786] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.18457894745626374, 'n_estimators': 763, 'subsample': 0.835717130801114, 'colsample_bytree': 0.7057576186093498, 'min_child_weight': 5, 'gamma': 4.277965021441548, 'reg_alpha': 0.05155191743102916, 'reg_lambda': 0.004400783427176562, 'max_delta_step': 5}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  20%|██        | 41/200 [00:26<02:16,  1.17it/s]

[I 2025-11-10 18:10:55,234] Trial 42 pruned.

Best trial: 1. Best value: 0.579786:  21%|██        | 42/200 [00:26<01:47,  1.47it/s]

[I 2025-11-10 18:10:55,508] Trial 43 pruned.

Best trial: 1. Best value: 0.579786:  22%|██▏       | 43/200 [00:26<01:36,  1.63it/s]

[I 2025-11-10 18:10:55,963] Trial 44 pruned.
[I 2025-11-10 18:10:55,993] Trial 37 finished with value: 0.4877777777777778 and parameters: {'max_depth': 9, 'learning_rate': 0.15989866050045898, 'n_estimators': 1472, 'subsample': 0.8358506833880718, 'colsample_bytree': 0.6879529218863684, 'min_child_weight': 5, 'gamma': 3.099833306568339, 'reg_alpha': 0.13692103530386918, 'reg_lambda': 0.014365422601535102, 'max_delta_step': 5}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  22%|██▎       | 45/200 [00:27<01:02,  2.48it/s]

[I 2025-11-10 18:10:56,275] Trial 45 pruned.

Best trial: 1. Best value: 0.579786:  23%|██▎       | 46/200 [00:27<01:01,  2.51it/s]

[I 2025-11-10 18:10:56,661] Trial 46 pruned.

Best trial: 1. Best value: 0.579786:  24%|██▎       | 47/200 [00:27<00:55,  2.74it/s]

[I 2025-11-10 18:10:56,931] Trial 47 pruned.
[I 2025-11-10 18:10:57,012] Trial 48 pruned.

Best trial: 1. Best value: 0.579786:  24%|██▍       | 49/200 [00:28<00:41,  3.64it/s]

[I 2025-11-10 18:10:57,237] Trial 40 finished with value: 0.47444444444444445 and parameters: {'max_depth': 8, 'learning_rate': 0.2996811605154223, 'n_estimators': 1466, 'subsample': 0.8381163205989899, 'colsample_bytree': 0.5566966113449744, 'min_child_weight': 5, 'gamma': 1.6054616978833942, 'reg_alpha': 1.972456949931035, 'reg_lambda': 0.0021923306612246624, 'max_delta_step': 3}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  25%|██▌       | 50/200 [00:28<00:51,  2.89it/s]

[I 2025-11-10 18:10:57,819] Trial 50 pruned.
[I 2025-11-10 18:10:57,854] Trial 51 pruned.

Best trial: 1. Best value: 0.579786:  26%|██▌       | 52/200 [00:29<00:42,  3.49it/s]

[I 2025-11-10 18:10:58,213] Trial 52 pruned.

Best trial: 1. Best value: 0.579786:  26%|██▋       | 53/200 [00:29<01:03,  2.30it/s]

[I 2025-11-10 18:10:59,161] Trial 53 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.0877935990963556, 'n_estimators': 277, 'subsample': 0.7423824415955087, 'colsample_bytree': 0.7235112478522626, 'min_child_weight': 10, 'gamma': 2.9070414657787063, 'reg_alpha': 8.85145228054892e-06, 'reg_lambda': 1.1442021202254372e-07, 'max_delta_step': 10}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  27%|██▋       | 54/200 [00:30<01:01,  2.37it/s]

[I 2025-11-10 18:10:59,549] Trial 55 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.010536124723873488, 'n_estimators': 269, 'subsample': 0.5198300315431661, 'colsample_bytree': 0.9769698230470009, 'min_child_weight': 9, 'gamma': 1.8359727097540532, 'reg_alpha': 5.6749489021540856e-08, 'reg_lambda': 0.9304792716309704, 'max_delta_step': 6}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  28%|██▊       | 55/200 [00:30<01:06,  2.18it/s]

[I 2025-11-10 18:11:00,108] Trial 54 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.06374747415553264, 'n_estimators': 463, 'subsample': 0.5179872184634916, 'colsample_bytree': 0.9694752739461542, 'min_child_weight': 9, 'gamma': 1.946134005772944, 'reg_alpha': 7.414163671062535e-08, 'reg_lambda': 1.2770900097121554, 'max_delta_step': 6}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  28%|██▊       | 56/200 [00:31<01:16,  1.89it/s]

[I 2025-11-10 18:11:00,827] Trial 49 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09077801381814464, 'n_estimators': 919, 'subsample': 0.5310809752785557, 'colsample_bytree': 0.7318647268737081, 'min_child_weight': 4, 'gamma': 1.8030824286413316, 'reg_alpha': 7.217517420666551e-07, 'reg_lambda': 1.0608236594563998, 'max_delta_step': 3}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  28%|██▊       | 57/200 [00:35<03:33,  1.49s/it]

[I 2025-11-10 18:11:04,839] Trial 56 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03263609482941926, 'n_estimators': 1334, 'subsample': 0.5198320328578852, 'colsample_bytree': 0.9215421609368322, 'min_child_weight': 9, 'gamma': 1.9010515527053073, 'reg_alpha': 3.524199655603148e-08, 'reg_lambda': 0.7018395993588913, 'max_delta_step': 6}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  29%|██▉       | 58/200 [00:35<02:41,  1.14s/it]

[I 2025-11-10 18:11:05,079] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.06533596033721134, 'n_estimators': 1315, 'subsample': 0.6890320636285423, 'colsample_bytree': 0.9239841711797976, 'min_child_weight': 8, 'gamma': 1.1716073042911517, 'reg_alpha': 0.00037128391842093867, 'reg_lambda': 0.6436167380251385, 'max_delta_step': 6}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  30%|██▉       | 59/200 [00:36<02:19,  1.01it/s]

[I 2025-11-10 18:11:05,704] Trial 58 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.030769661200448876, 'n_estimators': 1330, 'subsample': 0.596480547845331, 'colsample_bytree': 0.9215346071470387, 'min_child_weight': 10, 'gamma': 1.0703114396625946, 'reg_alpha': 1.1579970103043655e-06, 'reg_lambda': 0.3240502217906063, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  30%|███       | 60/200 [00:36<01:52,  1.25it/s]

[I 2025-11-10 18:11:06,049] Trial 59 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.0715596031537561, 'n_estimators': 1289, 'subsample': 0.597893716028874, 'colsample_bytree': 0.6019390421413442, 'min_child_weight': 8, 'gamma': 0.35487256969926595, 'reg_alpha': 0.0003868175416038576, 'reg_lambda': 1.0488885392238459e-06, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  30%|███       | 61/200 [00:37<01:41,  1.37it/s]

[I 2025-11-10 18:11:06,608] Trial 60 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.07237602404562579, 'n_estimators': 378, 'subsample': 0.9936621316235851, 'colsample_bytree': 0.5913463659789066, 'min_child_weight': 8, 'gamma': 1.3118996534048333, 'reg_alpha': 6.288776531763463, 'reg_lambda': 1.438137463364091e-06, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.
[I 2025-11-10 18:11:06,693] Trial 61 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.01874978846272198, 'n_estimators': 364, 'subsample': 0.5945580034421439, 'colsample_bytree': 0.5904621935080577, 'min_child_weight': 7, 'gamma': 0.3269524461065054, 'reg_alpha': 2.3712753308054283e-07, 'reg_lambda': 1.8998921943712114e-06, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  32%|███▏      | 64/200 [00:38<01:01,  2.22it/s]

[I 2025-11-10 18:11:07,298] Trial 65 pruned.
[I 2025-11-10 18:11:07,434] Trial 62 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.017739200165842284, 'n_estimators': 382, 'subsample': 0.9964201707829256, 'colsample_bytree': 0.5979045767657795, 'min_child_weight': 7, 'gamma': 0.33781074883636253, 'reg_alpha': 9.285570649695906e-05, 'reg_lambda': 0.0007254337672013976, 'max_delta_step': 7}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  32%|███▎      | 65/200 [00:38<00:59,  2.27it/s]

[I 2025-11-10 18:11:07,844] Trial 66 pruned.

Best trial: 1. Best value: 0.579786:  33%|███▎      | 66/200 [00:39<01:04,  2.09it/s]

[I 2025-11-10 18:11:08,424] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1905294438153965, 'n_estimators': 375, 'subsample': 0.9529095812189905, 'colsample_bytree': 0.8806305215016521, 'min_child_weight': 7, 'gamma': 0.841212218747172, 'reg_alpha': 2.4108242822745694e-07, 'reg_lambda': 0.0005081307091510114, 'max_delta_step': 4}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  34%|███▎      | 67/200 [00:39<00:54,  2.42it/s]

[I 2025-11-10 18:11:08,667] Trial 63 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.01856549852411882, 'n_estimators': 403, 'subsample': 0.9935250005192663, 'colsample_bytree': 0.8158947225694388, 'min_child_weight': 2, 'gamma': 1.2922516937129833, 'reg_alpha': 5.680070844483091, 'reg_lambda': 0.011511231045287885, 'max_delta_step': 7}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  34%|███▍      | 68/200 [00:39<00:46,  2.87it/s]

[I 2025-11-10 18:11:08,855] Trial 67 pruned.

Best trial: 1. Best value: 0.579786:  34%|███▍      | 69/200 [00:40<00:46,  2.81it/s]

[I 2025-11-10 18:11:09,230] Trial 69 pruned.

Best trial: 1. Best value: 0.579786:  36%|███▌      | 71/200 [00:40<00:37,  3.46it/s]

[I 2025-11-10 18:11:09,507] Trial 71 pruned.
[I 2025-11-10 18:11:09,690] Trial 70 pruned.

Best trial: 1. Best value: 0.579786:  36%|███▌      | 72/200 [00:42<01:23,  1.54it/s]

[I 2025-11-10 18:11:11,201] Trial 68 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.037792270763416284, 'n_estimators': 753, 'subsample': 0.8686302931840452, 'colsample_bytree': 0.8224095119555875, 'min_child_weight': 10, 'gamma': 0.6340226145673464, 'reg_alpha': 0.0009640354208856178, 'reg_lambda': 0.041982729635083677, 'max_delta_step': 1}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  36%|███▋      | 73/200 [00:43<01:56,  1.09it/s]

[I 2025-11-10 18:11:12,756] Trial 72 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.012762717819281748, 'n_estimators': 770, 'subsample': 0.6290199071846309, 'colsample_bytree': 0.7833662925026201, 'min_child_weight': 6, 'gamma': 0.6976389282806977, 'reg_alpha': 3.255534770394451e-06, 'reg_lambda': 0.046801384249991175, 'max_delta_step': 5}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  37%|███▋      | 74/200 [00:43<01:35,  1.32it/s]

[I 2025-11-10 18:11:13,125] Trial 73 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.011802665235193976, 'n_estimators': 747, 'subsample': 0.644085622962172, 'colsample_bytree': 0.9869789900137492, 'min_child_weight': 6, 'gamma': 1.4855591897243587, 'reg_alpha': 0.10129251050595271, 'reg_lambda': 0.19623788765624955, 'max_delta_step': 3}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  38%|███▊      | 75/200 [00:46<02:35,  1.25s/it]

[I 2025-11-10 18:11:15,522] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.012296970696208883, 'n_estimators': 1377, 'subsample': 0.9132478893666518, 'colsample_bytree': 0.5171794201608249, 'min_child_weight': 9, 'gamma': 1.4952275696295854, 'reg_alpha': 4.0060081484142395e-06, 'reg_lambda': 0.0031091967386147686, 'max_delta_step': 0}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  38%|███▊      | 76/200 [00:47<02:46,  1.34s/it]

[I 2025-11-10 18:11:17,093] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.011393850271502783, 'n_estimators': 1365, 'subsample': 0.9708123697057595, 'colsample_bytree': 0.5712381345769852, 'min_child_weight': 8, 'gamma': 1.4431838129911556, 'reg_alpha': 3.2442341326692123e-06, 'reg_lambda': 0.0035462204125776466, 'max_delta_step': 0}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  38%|███▊      | 77/200 [00:49<02:59,  1.46s/it]

[I 2025-11-10 18:11:18,813] Trial 76 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.011413904758574487, 'n_estimators': 1396, 'subsample': 0.9127695339487868, 'colsample_bytree': 0.5222703415999349, 'min_child_weight': 9, 'gamma': 1.4715567623046928, 'reg_alpha': 1.2463739759829954e-05, 'reg_lambda': 0.0032218414259297364, 'max_delta_step': 0}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  39%|███▉      | 78/200 [00:49<02:12,  1.09s/it]

[I 2025-11-10 18:11:19,044] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.02812709196451643, 'n_estimators': 1377, 'subsample': 0.9237141820003675, 'colsample_bytree': 0.5584171039093955, 'min_child_weight': 9, 'gamma': 1.4925928639671737, 'reg_alpha': 1.0565323209713228e-05, 'reg_lambda': 0.003640955779411915, 'max_delta_step': 2}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  40%|███▉      | 79/200 [00:51<02:19,  1.15s/it]

[I 2025-11-10 18:11:20,335] Trial 80 pruned.

Best trial: 1. Best value: 0.579786:  40%|████      | 80/200 [00:51<01:50,  1.09it/s]

[I 2025-11-10 18:11:20,720] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.014226990053611836, 'n_estimators': 1239, 'subsample': 0.9725225980816167, 'colsample_bytree': 0.5698706885536353, 'min_child_weight': 9, 'gamma': 1.6914161334007731, 'reg_alpha': 2.2920341731751517e-08, 'reg_lambda': 0.006474695537712222, 'max_delta_step': 0}. Best is trial 1 with value: 0.5797855750487328.
[I 2025-11-10 18:11:20,742] Trial 81 pruned.

Best trial: 1. Best value: 0.579786:  41%|████      | 82/200 [00:52<01:36,  1.23it/s]

[I 2025-11-10 18:11:22,100] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.027110543126844182, 'n_estimators': 1250, 'subsample': 0.5684254292680854, 'colsample_bytree': 0.5191692146763229, 'min_child_weight': 9, 'gamma': 1.1239394771423834, 'reg_alpha': 8.8505769180871e-06, 'reg_lambda': 0.0014012371236741844, 'max_delta_step': 2}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  42%|████▏     | 84/200 [00:53<01:12,  1.60it/s]

[I 2025-11-10 18:11:22,896] Trial 82 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.07918050606950205, 'n_estimators': 545, 'subsample': 0.5629454027121787, 'colsample_bytree': 0.8932947972529719, 'min_child_weight': 10, 'gamma': 1.169514109869156, 'reg_alpha': 0.19048559670571333, 'reg_lambda': 4.1475505769859914e-06, 'max_delta_step': 6}. Best is trial 1 with value: 0.5797855750487328.
[I 2025-11-10 18:11:23,001] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.0400836937339136, 'n_estimators': 492, 'subsample': 0.7286946872342306, 'colsample_bytree': 0.9322971716733042, 'min_child_weight': 10, 'gamma': 1.2144349793582623, 'reg_alpha': 1.654005345800245, 'reg_lambda': 3.328091950536146, 'max_delta_step': 10}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  42%|████▎     | 85/200 [00:54<01:03,  1.80it/s]

[I 2025-11-10 18:11:23,370] Trial 83 finished with value: 0.533411306042885 and parameters: {'max_depth': 9, 'learning_rate': 0.11764117162507232, 'n_estimators': 527, 'subsample': 0.8852935976463018, 'colsample_bytree': 0.5074744116754116, 'min_child_weight': 3, 'gamma': 2.0895131638816364, 'reg_alpha': 4.8080505039308734e-05, 'reg_lambda': 0.00014624171185487824, 'max_delta_step': 10}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  43%|████▎     | 86/200 [00:54<01:03,  1.79it/s]

[I 2025-11-10 18:11:23,938] Trial 88 pruned.

Best trial: 1. Best value: 0.579786:  44%|████▍     | 88/200 [00:55<00:46,  2.41it/s]

[I 2025-11-10 18:11:24,422] Trial 89 pruned.
[I 2025-11-10 18:11:24,537] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.117232700320375, 'n_estimators': 532, 'subsample': 0.9411840890236676, 'colsample_bytree': 0.504651347123168, 'min_child_weight': 10, 'gamma': 2.9377879758984653, 'reg_alpha': 1.7656332715388323, 'reg_lambda': 0.00023149217074985097, 'max_delta_step': 4}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  44%|████▍     | 89/200 [00:55<00:49,  2.23it/s]

[I 2025-11-10 18:11:25,070] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.11521321595274997, 'n_estimators': 451, 'subsample': 0.9393309242262677, 'colsample_bytree': 0.5079851875861671, 'min_child_weight': 8, 'gamma': 2.6165484036967013, 'reg_alpha': 1.3860634128450608, 'reg_lambda': 0.00014066587044809907, 'max_delta_step': 4}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  45%|████▌     | 90/200 [00:56<00:41,  2.66it/s]

[I 2025-11-10 18:11:25,272] Trial 91 pruned.

Best trial: 1. Best value: 0.579786:  46%|████▌     | 91/200 [00:56<00:41,  2.65it/s]

[I 2025-11-10 18:11:25,653] Trial 93 pruned.
[I 2025-11-10 18:11:25,677] Trial 90 pruned.

Best trial: 1. Best value: 0.579786:  46%|████▋     | 93/200 [00:56<00:33,  3.21it/s]

[I 2025-11-10 18:11:26,123] Trial 92 pruned.

Best trial: 1. Best value: 0.579786:  47%|████▋     | 94/200 [00:57<00:32,  3.26it/s]

[I 2025-11-10 18:11:26,411] Trial 95 pruned.

Best trial: 1. Best value: 0.579786:  48%|████▊     | 95/200 [00:58<00:53,  1.97it/s]

[I 2025-11-10 18:11:27,488] Trial 94 pruned.

Best trial: 1. Best value: 0.579786:  48%|████▊     | 96/200 [00:59<00:58,  1.78it/s]

[I 2025-11-10 18:11:28,201] Trial 97 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.09884303813414881, 'n_estimators': 420, 'subsample': 0.7723991781230082, 'colsample_bytree': 0.9812543937632692, 'min_child_weight': 8, 'gamma': 0.9971926449347597, 'reg_alpha': 1.6157864633465005e-07, 'reg_lambda': 0.08028574341602375, 'max_delta_step': 3}. Best is trial 1 with value: 0.5797855750487328.
[I 2025-11-10 18:11:28,223] Trial 96 pruned.

Best trial: 1. Best value: 0.579786:  49%|████▉     | 98/200 [01:00<00:57,  1.77it/s]

[I 2025-11-10 18:11:29,331] Trial 99 pruned.

Best trial: 1. Best value: 0.579786:  50%|████▉     | 99/200 [01:00<00:53,  1.91it/s]

[I 2025-11-10 18:11:29,728] Trial 87 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.11270211832638477, 'n_estimators': 1498, 'subsample': 0.944712625061259, 'colsample_bytree': 0.9838270620448781, 'min_child_weight': 8, 'gamma': 2.6462005467586738, 'reg_alpha': 0.06856906849411624, 'reg_lambda': 0.019787138383988042, 'max_delta_step': 4}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  50%|█████     | 100/200 [01:01<01:09,  1.43it/s]

[I 2025-11-10 18:11:30,934] Trial 100 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.021597843788259307, 'n_estimators': 585, 'subsample': 0.57775798312256, 'colsample_bytree': 0.9669507861634178, 'min_child_weight': 4, 'gamma': 2.4270941233264915, 'reg_alpha': 9.664973475437572, 'reg_lambda': 5.432201300161902e-07, 'max_delta_step': 6}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  50%|█████     | 101/200 [01:02<00:57,  1.71it/s]

[I 2025-11-10 18:11:31,211] Trial 98 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.09803258997625199, 'n_estimators': 805, 'subsample': 0.7686250929404385, 'colsample_bytree': 0.9333711206338555, 'min_child_weight': 4, 'gamma': 1.7680094928515453, 'reg_alpha': 7.923714657681338, 'reg_lambda': 5.704080431110689e-07, 'max_delta_step': 6}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  51%|█████     | 102/200 [01:02<00:52,  1.86it/s]

[I 2025-11-10 18:11:31,628] Trial 101 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.2977185556918524, 'n_estimators': 478, 'subsample': 0.5820720299191326, 'colsample_bytree': 0.9375454678361403, 'min_child_weight': 9, 'gamma': 3.961445202639843, 'reg_alpha': 6.341374619457553, 'reg_lambda': 2.9771058762967223e-05, 'max_delta_step': 7}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  52%|█████▏    | 103/200 [01:03<00:49,  1.97it/s]

[I 2025-11-10 18:11:32,056] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.07994554933406309, 'n_estimators': 484, 'subsample': 0.5760169318644861, 'colsample_bytree': 0.9354998779955627, 'min_child_weight': 9, 'gamma': 1.8009741486325275, 'reg_alpha': 0.025686746786705534, 'reg_lambda': 2.9200138815151345e-05, 'max_delta_step': 1}. Best is trial 1 with value: 0.5797855750487328.
[I 2025-11-10 18:11:32,237] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06153488160780018, 'n_estimators': 229, 'subsample': 0.9265420326127265, 'colsample_bytree': 0.9398018437657953, 'min_child_weight': 9, 'gamma': 3.85789728451264, 'reg_alpha': 0.016580110040093434, 'reg_lambda': 2.6843532418077288e-05, 'max_delta_step': 1}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  52%|█████▎    | 105/200 [01:04<01:03,  1.50it/s]

[I 2025-11-10 18:11:33,527] Trial 104 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.035060808421626496, 'n_estimators': 478, 'subsample': 0.9280940063912941, 'colsample_bytree': 0.5550482236529616, 'min_child_weight': 9, 'gamma': 1.9665114563741886, 'reg_alpha': 0.03429046196627877, 'reg_lambda': 0.1579834433395551, 'max_delta_step': 9}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  53%|█████▎    | 106/200 [01:05<01:10,  1.32it/s]

[I 2025-11-10 18:11:34,490] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.07858895930798977, 'n_estimators': 619, 'subsample': 0.9254736791102329, 'colsample_bytree': 0.5332416225136514, 'min_child_weight': 9, 'gamma': 1.3786397054757082, 'reg_alpha': 0.01648648141727962, 'reg_lambda': 0.007985894271960975, 'max_delta_step': 9}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  54%|█████▎    | 107/200 [01:07<01:45,  1.13s/it]

[I 2025-11-10 18:11:36,515] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.19335045806342532, 'n_estimators': 1045, 'subsample': 0.918925697596048, 'colsample_bytree': 0.5311689270394221, 'min_child_weight': 9, 'gamma': 1.3635870428508454, 'reg_alpha': 0.4658414899231543, 'reg_lambda': 0.17648712619838716, 'max_delta_step': 9}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  54%|█████▍    | 108/200 [01:07<01:22,  1.12it/s]

[I 2025-11-10 18:11:36,841] Trial 107 finished with value: 0.5222222222222221 and parameters: {'max_depth': 10, 'learning_rate': 0.05748811604756786, 'n_estimators': 1072, 'subsample': 0.8530189419113002, 'colsample_bytree': 0.549444575360857, 'min_child_weight': 5, 'gamma': 1.952083557410302, 'reg_alpha': 0.0005755495693118162, 'reg_lambda': 0.008413191014703642, 'max_delta_step': 9}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  55%|█████▌    | 110/200 [01:08<01:03,  1.43it/s]

[I 2025-11-10 18:11:37,885] Trial 110 pruned.
[I 2025-11-10 18:11:38,031] Trial 108 finished with value: 0.5166666666666667 and parameters: {'max_depth': 6, 'learning_rate': 0.15670823072539614, 'n_estimators': 1071, 'subsample': 0.8470107399297531, 'colsample_bytree': 0.5256966857578731, 'min_child_weight': 5, 'gamma': 1.2768848430231605, 'reg_alpha': 0.4945969246685113, 'reg_lambda': 0.007567957313926148, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  56%|█████▌    | 111/200 [01:10<01:22,  1.07it/s]

[I 2025-11-10 18:11:39,501] Trial 109 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05679107560874025, 'n_estimators': 1065, 'subsample': 0.8193966826581096, 'colsample_bytree': 0.8748773620157122, 'min_child_weight': 5, 'gamma': 2.1396454905526743, 'reg_alpha': 0.5175904044365942, 'reg_lambda': 0.4291098074451436, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  56%|█████▌    | 112/200 [01:12<02:00,  1.37s/it]

[I 2025-11-10 18:11:41,901] Trial 111 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.06666525831247107, 'n_estimators': 1141, 'subsample': 0.8215444021583509, 'colsample_bytree': 0.6118854249783455, 'min_child_weight': 5, 'gamma': 2.122372100436417, 'reg_alpha': 0.0005652597232866963, 'reg_lambda': 0.0011142776992149658, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  56%|█████▋    | 113/200 [01:13<01:38,  1.13s/it]

[I 2025-11-10 18:11:42,486] Trial 113 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05873053692873854, 'n_estimators': 1046, 'subsample': 0.815824717906706, 'colsample_bytree': 0.5001278179495703, 'min_child_weight': 5, 'gamma': 0.7890858032025674, 'reg_alpha': 0.0006190636636249962, 'reg_lambda': 0.0004019655653252029, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  57%|█████▋    | 114/200 [01:13<01:21,  1.06it/s]

[I 2025-11-10 18:11:42,974] Trial 112 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.048423509683979904, 'n_estimators': 1185, 'subsample': 0.8186648324873522, 'colsample_bytree': 0.5448023508779217, 'min_child_weight': 5, 'gamma': 2.7664033841766504, 'reg_alpha': 0.0005518207042317076, 'reg_lambda': 0.005523516047996754, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  57%|█████▊    | 115/200 [01:15<01:30,  1.06s/it]

[I 2025-11-10 18:11:44,312] Trial 114 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.15813393241198154, 'n_estimators': 1087, 'subsample': 0.8282606286887563, 'colsample_bytree': 0.5390504123622669, 'min_child_weight': 5, 'gamma': 1.2765569694389929, 'reg_alpha': 0.00047028256046183507, 'reg_lambda': 0.0009846334739266605, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  58%|█████▊    | 116/200 [01:17<01:57,  1.40s/it]

[I 2025-11-10 18:11:46,494] Trial 115 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.16191756256512874, 'n_estimators': 1008, 'subsample': 0.8577615771550122, 'colsample_bytree': 0.7554644601817361, 'min_child_weight': 6, 'gamma': 1.578866185001803, 'reg_alpha': 0.0027072327128479417, 'reg_lambda': 0.005208140513300167, 'max_delta_step': 10}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  58%|█████▊    | 117/200 [01:17<01:31,  1.11s/it]

[I 2025-11-10 18:11:46,921] Trial 119 pruned.

Best trial: 1. Best value: 0.579786:  60%|█████▉    | 119/200 [01:18<00:51,  1.56it/s]

[I 2025-11-10 18:11:47,228] Trial 116 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.16300669060100287, 'n_estimators': 1096, 'subsample': 0.8793110648097308, 'colsample_bytree': 0.5418431028436252, 'min_child_weight': 6, 'gamma': 1.2144978799876247, 'reg_alpha': 0.00027112884357220366, 'reg_lambda': 0.004974437320371664, 'max_delta_step': 7}. Best is trial 1 with value: 0.5797855750487328.
[I 2025-11-10 18:11:47,338] Trial 117 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.1608809039840828, 'n_estimators': 960, 'subsample': 0.87761196112089, 'colsample_bytree': 0.7622111422668981, 'min_child_weight': 6, 'gamma': 1.6456018351013766, 'reg_alpha': 1.1423435850939614, 'reg_lambda': 0.009174450042546632, 'max_delta_step': 7}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  60%|██████    | 120/200 [01:18<00:44,  1.79it/s]

[I 2025-11-10 18:11:47,708] Trial 122 pruned.

Best trial: 1. Best value: 0.579786:  60%|██████    | 121/200 [01:19<00:44,  1.78it/s]

[I 2025-11-10 18:11:48,279] Trial 120 pruned.

Best trial: 1. Best value: 0.579786:  61%|██████    | 122/200 [01:19<00:37,  2.06it/s]

[I 2025-11-10 18:11:48,582] Trial 123 pruned.
[I 2025-11-10 18:11:48,636] Trial 121 pruned.

Best trial: 1. Best value: 0.579786:  62%|██████▏   | 124/200 [01:19<00:25,  3.03it/s]

[I 2025-11-10 18:11:48,881] Trial 118 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.14492563202053205, 'n_estimators': 946, 'subsample': 0.8427831851332439, 'colsample_bytree': 0.766655666721747, 'min_child_weight': 6, 'gamma': 0.9174997221622521, 'reg_alpha': 1.1197764537665336, 'reg_lambda': 0.010057243556312632, 'max_delta_step': 7}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  62%|██████▎   | 125/200 [01:20<00:32,  2.34it/s]

[I 2025-11-10 18:11:49,605] Trial 124 pruned.

Best trial: 1. Best value: 0.579786:  63%|██████▎   | 126/200 [01:21<00:51,  1.44it/s]

[I 2025-11-10 18:11:51,062] Trial 126 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.20784711317130633, 'n_estimators': 516, 'subsample': 0.8912796999168084, 'colsample_bytree': 0.6450032163802081, 'min_child_weight': 10, 'gamma': 1.093839419690056, 'reg_alpha': 0.1536917781922242, 'reg_lambda': 1.54447802693393, 'max_delta_step': 10}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  64%|██████▎   | 127/200 [01:22<00:42,  1.70it/s]

[I 2025-11-10 18:11:51,356] Trial 127 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.22954954670407196, 'n_estimators': 549, 'subsample': 0.8891379769528219, 'colsample_bytree': 0.5153493745917552, 'min_child_weight': 10, 'gamma': 4.609611565700167, 'reg_alpha': 2.548471390348079, 'reg_lambda': 1.6170926019730139, 'max_delta_step': 10}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  64%|██████▍   | 128/200 [01:22<00:39,  1.82it/s]

[I 2025-11-10 18:11:51,817] Trial 128 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1082209688274849, 'n_estimators': 506, 'subsample': 0.8899791681701453, 'colsample_bytree': 0.5186497911025693, 'min_child_weight': 10, 'gamma': 1.5486645208530052, 'reg_alpha': 0.00011397112025983533, 'reg_lambda': 0.06765070171590852, 'max_delta_step': 10}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  64%|██████▍   | 129/200 [01:23<00:41,  1.69it/s]

[I 2025-11-10 18:11:52,504] Trial 131 pruned.

Best trial: 1. Best value: 0.579786:  65%|██████▌   | 130/200 [01:24<00:46,  1.51it/s]

[I 2025-11-10 18:11:53,346] Trial 130 pruned.

Best trial: 1. Best value: 0.579786:  66%|██████▌   | 131/200 [01:24<00:42,  1.62it/s]

[I 2025-11-10 18:11:53,857] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.14579136083651598, 'n_estimators': 1320, 'subsample': 0.5422704592229848, 'colsample_bytree': 0.5248931097574708, 'min_child_weight': 10, 'gamma': 1.5921300078135423, 'reg_alpha': 2.9097198823965345, 'reg_lambda': 0.05037222953762693, 'max_delta_step': 10}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  66%|██████▌   | 132/200 [01:25<00:55,  1.22it/s]

[I 2025-11-10 18:11:55,157] Trial 133 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.04580945101804985, 'n_estimators': 446, 'subsample': 0.7961521475856584, 'colsample_bytree': 0.5486214114177527, 'min_child_weight': 8, 'gamma': 1.3930025091018283, 'reg_alpha': 0.00032226586916261896, 'reg_lambda': 6.0411341256029147e-05, 'max_delta_step': 9}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  66%|██████▋   | 133/200 [01:27<01:18,  1.17s/it]

[I 2025-11-10 18:11:57,170] Trial 134 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.2240589264232732, 'n_estimators': 814, 'subsample': 0.5532857406055887, 'colsample_bytree': 0.9490397315025962, 'min_child_weight': 7, 'gamma': 4.0871849290372815, 'reg_alpha': 0.0002866679894404242, 'reg_lambda': 6.487679739102915e-05, 'max_delta_step': 4}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  67%|██████▋   | 134/200 [01:28<00:59,  1.10it/s]

[I 2025-11-10 18:11:57,442] Trial 135 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.21892611719316757, 'n_estimators': 558, 'subsample': 0.5328438724862996, 'colsample_bytree': 0.8029740875660242, 'min_child_weight': 9, 'gamma': 4.103115978268247, 'reg_alpha': 4.777517115403981e-05, 'reg_lambda': 6.467531527709231e-06, 'max_delta_step': 4}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  68%|██████▊   | 135/200 [01:28<00:48,  1.34it/s]

[I 2025-11-10 18:11:57,816] Trial 132 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.07193858803025009, 'n_estimators': 1403, 'subsample': 0.7021881071287711, 'colsample_bytree': 0.5495849180172114, 'min_child_weight': 8, 'gamma': 2.0430730268466637, 'reg_alpha': 0.08995849990330305, 'reg_lambda': 2.2557805721282138e-08, 'max_delta_step': 9}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  68%|██████▊   | 136/200 [01:29<00:44,  1.45it/s]

[I 2025-11-10 18:11:58,374] Trial 138 pruned.

Best trial: 1. Best value: 0.579786:  68%|██████▊   | 137/200 [01:30<01:01,  1.02it/s]

[I 2025-11-10 18:12:00,041] Trial 137 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.19536479025755635, 'n_estimators': 610, 'subsample': 0.5904022007913131, 'colsample_bytree': 0.7787307080063379, 'min_child_weight': 8, 'gamma': 2.0153346375566823, 'reg_alpha': 2.3596452001999498e-05, 'reg_lambda': 1.6184710972896688e-07, 'max_delta_step': 5}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  69%|██████▉   | 138/200 [01:32<01:06,  1.07s/it]

[I 2025-11-10 18:12:01,301] Trial 139 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.19864971253490882, 'n_estimators': 685, 'subsample': 0.5632572487986716, 'colsample_bytree': 0.8299862152443477, 'min_child_weight': 4, 'gamma': 2.5571235646488804, 'reg_alpha': 1.7562451710994662e-08, 'reg_lambda': 0.6720340073817846, 'max_delta_step': 5}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  70%|██████▉   | 139/200 [01:32<00:57,  1.06it/s]

[I 2025-11-10 18:12:01,951] Trial 129 finished with value: 0.5431578947368421 and parameters: {'max_depth': 9, 'learning_rate': 0.01376400579077276, 'n_estimators': 1206, 'subsample': 0.8685748838673957, 'colsample_bytree': 0.9465906799052023, 'min_child_weight': 1, 'gamma': 1.5483786412545695, 'reg_alpha': 0.08291036202859715, 'reg_lambda': 1.8156296816708148e-08, 'max_delta_step': 0}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  70%|███████   | 140/200 [01:33<00:47,  1.26it/s]

[I 2025-11-10 18:12:02,393] Trial 136 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.2646652029003932, 'n_estimators': 1351, 'subsample': 0.5940344445938633, 'colsample_bytree': 0.5067883746819587, 'min_child_weight': 9, 'gamma': 4.574559587955813, 'reg_alpha': 1.0748104795405404e-07, 'reg_lambda': 1.8913456212952684e-08, 'max_delta_step': 4}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  70%|███████   | 141/200 [01:33<00:42,  1.39it/s]

[I 2025-11-10 18:12:02,938] Trial 140 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03956390542396824, 'n_estimators': 728, 'subsample': 0.5093953684225351, 'colsample_bytree': 0.5024825441422816, 'min_child_weight': 4, 'gamma': 3.5595394651378625, 'reg_alpha': 1.5727412611388426e-07, 'reg_lambda': 0.11884785024831847, 'max_delta_step': 2}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  71%|███████   | 142/200 [01:34<00:48,  1.19it/s]

[I 2025-11-10 18:12:04,067] Trial 144 pruned.

Best trial: 1. Best value: 0.579786:  72%|███████▏  | 143/200 [01:35<00:39,  1.44it/s]

[I 2025-11-10 18:12:04,414] Trial 143 pruned.

Best trial: 1. Best value: 0.579786:  72%|███████▏  | 144/200 [01:36<00:40,  1.38it/s]

[I 2025-11-10 18:12:05,216] Trial 145 pruned.

Best trial: 1. Best value: 0.579786:  72%|███████▎  | 145/200 [01:37<00:54,  1.01it/s]

[I 2025-11-10 18:12:06,829] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0394058060338668, 'n_estimators': 1353, 'subsample': 0.604167840389543, 'colsample_bytree': 0.9728448432855958, 'min_child_weight': 5, 'gamma': 4.532681654172693, 'reg_alpha': 9.653438121241559e-08, 'reg_lambda': 0.12867665374334217, 'max_delta_step': 4}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  73%|███████▎  | 146/200 [01:37<00:42,  1.28it/s]

[I 2025-11-10 18:12:07,122] Trial 147 pruned.

Best trial: 1. Best value: 0.579786:  74%|███████▎  | 147/200 [01:38<00:40,  1.30it/s]

[I 2025-11-10 18:12:07,859] Trial 142 finished with value: 0.513411306042885 and parameters: {'max_depth': 9, 'learning_rate': 0.12920214067408267, 'n_estimators': 1155, 'subsample': 0.9034261496720806, 'colsample_bytree': 0.5013365294622261, 'min_child_weight': 1, 'gamma': 1.7423537039722516, 'reg_alpha': 1.6853384037618895e-06, 'reg_lambda': 1.241403064663913e-08, 'max_delta_step': 0}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  74%|███████▍  | 148/200 [01:39<00:36,  1.41it/s]

[I 2025-11-10 18:12:08,431] Trial 148 pruned.

Best trial: 1. Best value: 0.579786:  75%|███████▌  | 150/200 [01:39<00:25,  1.99it/s]

[I 2025-11-10 18:12:08,958] Trial 149 pruned.
[I 2025-11-10 18:12:09,101] Trial 150 pruned.

Best trial: 1. Best value: 0.579786:  76%|███████▌  | 151/200 [01:40<00:27,  1.76it/s]

[I 2025-11-10 18:12:09,821] Trial 151 pruned.

Best trial: 1. Best value: 0.579786:  76%|███████▌  | 152/200 [01:41<00:25,  1.88it/s]

[I 2025-11-10 18:12:10,270] Trial 152 pruned.
[I 2025-11-10 18:12:10,354] Trial 153 pruned.

Best trial: 1. Best value: 0.579786:  77%|███████▋  | 154/200 [01:43<00:38,  1.19it/s]

[I 2025-11-10 18:12:12,677] Trial 146 finished with value: 0.5467641325536062 and parameters: {'max_depth': 9, 'learning_rate': 0.13006699727126492, 'n_estimators': 1168, 'subsample': 0.8733317286408939, 'colsample_bytree': 0.9487447204280129, 'min_child_weight': 1, 'gamma': 3.7341765028280447, 'reg_alpha': 8.666237687542906e-05, 'reg_lambda': 0.00022883375895428138, 'max_delta_step': 1}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  78%|███████▊  | 155/200 [01:44<00:42,  1.06it/s]

[I 2025-11-10 18:12:13,940] Trial 154 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.08730532109252077, 'n_estimators': 1070, 'subsample': 0.7189195381469364, 'colsample_bytree': 0.538670963108673, 'min_child_weight': 9, 'gamma': 1.6573952394518028, 'reg_alpha': 0.0011508318201103203, 'reg_lambda': 0.0019455079072333088, 'max_delta_step': 0}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  78%|███████▊  | 156/200 [01:44<00:33,  1.31it/s]

[I 2025-11-10 18:12:14,178] Trial 157 pruned.

Best trial: 1. Best value: 0.579786:  78%|███████▊  | 157/200 [01:45<00:30,  1.40it/s]

[I 2025-11-10 18:12:14,763] Trial 156 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.10542793876509224, 'n_estimators': 1065, 'subsample': 0.8608769489018607, 'colsample_bytree': 0.9581472472103637, 'min_child_weight': 9, 'gamma': 1.5072862840147505, 'reg_alpha': 4.440783614242002, 'reg_lambda': 0.015791180259796495, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  79%|███████▉  | 158/200 [01:45<00:26,  1.60it/s]

[I 2025-11-10 18:12:15,164] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.08427692738428326, 'n_estimators': 1212, 'subsample': 0.8611170823412817, 'colsample_bytree': 0.7458601316707243, 'min_child_weight': 9, 'gamma': 3.7204429606100295, 'reg_alpha': 0.0012676835114009423, 'reg_lambda': 2.8699293960694123, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  80%|███████▉  | 159/200 [01:46<00:22,  1.79it/s]

[I 2025-11-10 18:12:15,558] Trial 159 pruned.

Best trial: 1. Best value: 0.579786:  80%|████████  | 160/200 [01:46<00:19,  2.00it/s]

[I 2025-11-10 18:12:15,912] Trial 158 pruned.

Best trial: 1. Best value: 0.579786:  80%|████████  | 161/200 [01:47<00:19,  2.00it/s]

[I 2025-11-10 18:12:16,413] Trial 160 pruned.

Best trial: 1. Best value: 0.579786:  81%|████████  | 162/200 [01:47<00:17,  2.13it/s]

[I 2025-11-10 18:12:16,806] Trial 161 pruned.

Best trial: 1. Best value: 0.579786:  82%|████████▏ | 163/200 [01:48<00:18,  2.05it/s]

[I 2025-11-10 18:12:17,342] Trial 165 pruned.
[I 2025-11-10 18:12:17,360] Trial 162 pruned.

Best trial: 1. Best value: 0.579786:  82%|████████▎ | 165/200 [01:48<00:10,  3.23it/s]

[I 2025-11-10 18:12:17,543] Trial 164 pruned.

Best trial: 1. Best value: 0.579786:  83%|████████▎ | 166/200 [01:48<00:13,  2.56it/s]

[I 2025-11-10 18:12:18,176] Trial 163 pruned.

Best trial: 1. Best value: 0.579786:  84%|████████▎ | 167/200 [01:49<00:11,  2.75it/s]

[I 2025-11-10 18:12:18,465] Trial 167 pruned.
[I 2025-11-10 18:12:18,562] Trial 168 pruned.

Best trial: 1. Best value: 0.579786:  84%|████████▍ | 169/200 [01:50<00:14,  2.17it/s]

[I 2025-11-10 18:12:19,642] Trial 170 pruned.

Best trial: 1. Best value: 0.579786:  85%|████████▌ | 170/200 [01:51<00:15,  1.91it/s]

[I 2025-11-10 18:12:20,369] Trial 169 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.18107751389576185, 'n_estimators': 470, 'subsample': 0.8974620696301799, 'colsample_bytree': 0.5013387861524079, 'min_child_weight': 7, 'gamma': 1.9689390584384114, 'reg_alpha': 8.407423315594684e-05, 'reg_lambda': 0.2680324386949711, 'max_delta_step': 9}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  86%|████████▌ | 171/200 [01:51<00:16,  1.76it/s]

[I 2025-11-10 18:12:21,081] Trial 171 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.025455890310421076, 'n_estimators': 525, 'subsample': 0.9598240219047646, 'colsample_bytree': 0.7346242378950083, 'min_child_weight': 7, 'gamma': 1.345504231485177, 'reg_alpha': 0.1552670271990848, 'reg_lambda': 0.028215511085958316, 'max_delta_step': 0}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  86%|████████▌ | 172/200 [01:52<00:18,  1.54it/s]

[I 2025-11-10 18:12:21,950] Trial 173 pruned.
[I 2025-11-10 18:12:21,960] Trial 172 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.013703331826145195, 'n_estimators': 525, 'subsample': 0.8840234060530612, 'colsample_bytree': 0.5261698936027704, 'min_child_weight': 9, 'gamma': 1.3536860603292908, 'reg_alpha': 0.00014334793148541367, 'reg_lambda': 2.4254923689153917e-08, 'max_delta_step': 0}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  87%|████████▋ | 174/200 [01:53<00:11,  2.23it/s]

[I 2025-11-10 18:12:22,315] Trial 166 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.28812124699277014, 'n_estimators': 1110, 'subsample': 0.9005177447448496, 'colsample_bytree': 0.5001783112222603, 'min_child_weight': 7, 'gamma': 1.9373858381559208, 'reg_alpha': 1.583123863022812e-05, 'reg_lambda': 2.3019215144897888e-08, 'max_delta_step': 3}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  88%|████████▊ | 175/200 [01:53<00:12,  1.94it/s]

[I 2025-11-10 18:12:23,051] Trial 176 pruned.

Best trial: 1. Best value: 0.579786:  88%|████████▊ | 176/200 [01:55<00:16,  1.45it/s]

[I 2025-11-10 18:12:24,256] Trial 178 pruned.

Best trial: 1. Best value: 0.579786:  88%|████████▊ | 177/200 [01:55<00:16,  1.37it/s]

[I 2025-11-10 18:12:25,096] Trial 179 pruned.

Best trial: 1. Best value: 0.579786:  89%|████████▉ | 178/200 [01:56<00:17,  1.22it/s]

[I 2025-11-10 18:12:26,142] Trial 174 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09491001175451895, 'n_estimators': 1025, 'subsample': 0.6666361024959273, 'colsample_bytree': 0.5232792699628389, 'min_child_weight': 1, 'gamma': 3.520048026048941, 'reg_alpha': 9.206591341396335, 'reg_lambda': 1.6043811111588075e-08, 'max_delta_step': 10}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  90%|████████▉ | 179/200 [01:57<00:16,  1.28it/s]

[I 2025-11-10 18:12:26,831] Trial 181 pruned.

Best trial: 1. Best value: 0.579786:  90%|█████████ | 181/200 [01:58<00:10,  1.76it/s]

[I 2025-11-10 18:12:27,427] Trial 175 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09737955980634105, 'n_estimators': 969, 'subsample': 0.7050821560021225, 'colsample_bytree': 0.7120159095502032, 'min_child_weight': 1, 'gamma': 4.313698667511639, 'reg_alpha': 7.887678934460991, 'reg_lambda': 0.0071752891135802525, 'max_delta_step': 10}. Best is trial 1 with value: 0.5797855750487328.
[I 2025-11-10 18:12:27,602] Trial 182 pruned.

Best trial: 1. Best value: 0.579786:  92%|█████████▏| 183/200 [01:58<00:06,  2.54it/s]

[I 2025-11-10 18:12:27,917] Trial 180 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.15574455040201246, 'n_estimators': 430, 'subsample': 0.9294663087079766, 'colsample_bytree': 0.8398493768336002, 'min_child_weight': 1, 'gamma': 2.0742531140308627, 'reg_alpha': 9.583422207664011, 'reg_lambda': 2.748304728825109e-06, 'max_delta_step': 7}. Best is trial 1 with value: 0.5797855750487328.
[I 2025-11-10 18:12:28,079] Trial 177 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09493438163607065, 'n_estimators': 962, 'subsample': 0.7051585605194877, 'colsample_bytree': 0.7846087280579208, 'min_child_weight': 1, 'gamma': 2.0729743818596487, 'reg_alpha': 7.777104879392412, 'reg_lambda': 0.00738547806572387, 'max_delta_step': 10}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  92%|█████████▏| 184/200 [01:59<00:06,  2.43it/s]

[I 2025-11-10 18:12:28,532] Trial 185 pruned.

Best trial: 1. Best value: 0.579786:  92%|█████████▎| 185/200 [02:02<00:16,  1.12s/it]

[I 2025-11-10 18:12:31,328] Trial 187 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.05771598111250536, 'n_estimators': 677, 'subsample': 0.5005688696574179, 'colsample_bytree': 0.986598420850241, 'min_child_weight': 6, 'gamma': 0.05607310191134093, 'reg_alpha': 1.0656649604495538e-08, 'reg_lambda': 8.642049698914536e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  93%|█████████▎| 186/200 [02:02<00:12,  1.13it/s]

[I 2025-11-10 18:12:31,652] Trial 186 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.07717833943598612, 'n_estimators': 674, 'subsample': 0.5315712023428745, 'colsample_bytree': 0.6174142029907724, 'min_child_weight': 1, 'gamma': 2.700595359445594, 'reg_alpha': 5.75747968150837, 'reg_lambda': 1.1085912307990859e-08, 'max_delta_step': 7}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  94%|█████████▎| 187/200 [02:02<00:09,  1.38it/s]

[I 2025-11-10 18:12:32,004] Trial 183 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.15491354625728465, 'n_estimators': 1049, 'subsample': 0.9146845549021843, 'colsample_bytree': 0.8383019543682493, 'min_child_weight': 9, 'gamma': 0.8524368232035107, 'reg_alpha': 0.0002172483194690911, 'reg_lambda': 4.083722097461072e-05, 'max_delta_step': 7}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  94%|█████████▍| 188/200 [02:03<00:08,  1.48it/s]

[I 2025-11-10 18:12:32,566] Trial 184 finished with value: 0.4877777777777778 and parameters: {'max_depth': 5, 'learning_rate': 0.059704105782106213, 'n_estimators': 921, 'subsample': 0.5002235376346361, 'colsample_bytree': 0.6026766016172439, 'min_child_weight': 1, 'gamma': 0.030817825680909294, 'reg_alpha': 5.856082691600386, 'reg_lambda': 1.1569311175637957e-08, 'max_delta_step': 6}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  94%|█████████▍| 189/200 [02:03<00:06,  1.65it/s]

[I 2025-11-10 18:12:33,012] Trial 190 pruned.

Best trial: 1. Best value: 0.579786:  95%|█████████▌| 190/200 [02:04<00:06,  1.59it/s]

[I 2025-11-10 18:12:33,691] Trial 191 pruned.

Best trial: 1. Best value: 0.579786:  96%|█████████▌| 191/200 [02:04<00:04,  1.81it/s]

[I 2025-11-10 18:12:34,071] Trial 192 pruned.

Best trial: 1. Best value: 0.579786:  96%|█████████▌| 192/200 [02:06<00:08,  1.01s/it]

[I 2025-11-10 18:12:36,134] Trial 188 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.07640009210628555, 'n_estimators': 1085, 'subsample': 0.5294239863722058, 'colsample_bytree': 0.5413902496512268, 'min_child_weight': 9, 'gamma': 1.8003960296454895, 'reg_alpha': 5.064576257571918, 'reg_lambda': 3.896876890131916e-08, 'max_delta_step': 7}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  96%|█████████▋| 193/200 [02:07<00:05,  1.31it/s]

[I 2025-11-10 18:12:36,336] Trial 189 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.011822839617465095, 'n_estimators': 1036, 'subsample': 0.6222169314739029, 'colsample_bytree': 0.6007890410509421, 'min_child_weight': 9, 'gamma': 2.222900716115344, 'reg_alpha': 3.4434196452906676, 'reg_lambda': 3.4749184150911686e-08, 'max_delta_step': 5}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  97%|█████████▋| 194/200 [02:08<00:05,  1.05it/s]

[I 2025-11-10 18:12:37,710] Trial 194 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.12579890696056129, 'n_estimators': 789, 'subsample': 0.7571361891784747, 'colsample_bytree': 0.6593171554186965, 'min_child_weight': 6, 'gamma': 0.38905440887836135, 'reg_alpha': 0.0007692205473480309, 'reg_lambda': 0.08042097708603785, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  98%|█████████▊| 195/200 [02:09<00:04,  1.04it/s]

[I 2025-11-10 18:12:38,712] Trial 193 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.24929914128687164, 'n_estimators': 1128, 'subsample': 0.514639913685934, 'colsample_bytree': 0.5669848356712511, 'min_child_weight': 9, 'gamma': 2.194382065544547, 'reg_alpha': 3.612737105225752, 'reg_lambda': 6.583760268966804e-08, 'max_delta_step': 9}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  98%|█████████▊| 197/200 [02:10<00:02,  1.37it/s]

[I 2025-11-10 18:12:39,701] Trial 195 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.12468744022971268, 'n_estimators': 784, 'subsample': 0.7563190697224967, 'colsample_bytree': 0.5209929935189938, 'min_child_weight': 6, 'gamma': 1.6054596487974846, 'reg_alpha': 0.00046127694245876364, 'reg_lambda': 1.1431381430913151e-06, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.
[I 2025-11-10 18:12:39,861] Trial 196 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.137533064800314, 'n_estimators': 781, 'subsample': 0.98313069424408, 'colsample_bytree': 0.5224907343809517, 'min_child_weight': 6, 'gamma': 1.4484062141195002, 'reg_alpha': 0.0007324748170223102, 'reg_lambda': 1.1199116635800972e-06, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786:  99%|█████████▉| 198/200 [02:11<00:01,  1.29it/s]

[I 2025-11-10 18:12:40,749] Trial 197 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.023241600018530213, 'n_estimators': 742, 'subsample': 0.6012249239997159, 'colsample_bytree': 0.519773940954051, 'min_child_weight': 6, 'gamma': 0.23089999868667982, 'reg_alpha': 0.011128512522521327, 'reg_lambda': 8.479343152704097e-06, 'max_delta_step': 9}. Best is trial 1 with value: 0.5797855750487328.

Best trial: 1. Best value: 0.579786: 100%|██████████| 200/200 [02:12<00:00,  1.51it/s]

[I 2025-11-10 18:12:41,277] Trial 198 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.11460869114961898, 'n_estimators': 724, 'subsample': 0.9994715965277332, 'colsample_bytree': 0.5155689867526447, 'min_child_weight': 6, 'gamma': 1.4735974134047671, 'reg_alpha': 0.009815028273295672, 'reg_lambda': 0.01125464094561024, 'max_delta_step': 8}. Best is trial 1 with value: 0.5797855750487328.
[I 2025-11-10 18:12:41,422] Trial 199 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1343528407501537, 'n_estimators': 503, 'subsample': 0.987341089806147, 'colsample_bytree': 0.8878205171601923, 'min_child_weight': 6, 'gamma': 0.24085993204367373, 'reg_alpha': 0.00010672744052432249, 'reg_lambda': 2.6639639007318205e-06, 'max_delta_step': 4}. Best is trial 1 with value: 0.5797855750487328.

[I 2025-11-10 18:12:42,255] A new study created in memory with name: 9_1_roc_auc
Best trial: 0. Best value: 0.483903:   0%|          | 1/200 [00:02<08:37,  2.60s/it]

[I 2025-11-10 18:12:44,853] Trial 0 finished with value: 0.48390297937356763 and parameters: {'max_depth': 10, 'learning_rate': 0.06513240384763588, 'n_estimators': 230, 'subsample': 0.9265617685679091, 'colsample_bytree': 0.6743056899908595, 'min_child_weight': 4, 'gamma': 4.776523970646941, 'reg_alpha': 0.01734681122447019, 'reg_lambda': 0.07483658398084804, 'max_delta_step': 1}. Best is trial 0 with value: 0.48390297937356763.

Best trial: 1. Best value: 0.632506:   1%|          | 2/200 [00:03<04:24,  1.34s/it]

[I 2025-11-10 18:12:45,301] Trial 1 finished with value: 0.6325057295645531 and parameters: {'max_depth': 10, 'learning_rate': 0.09790055305379292, 'n_estimators': 242, 'subsample': 0.9267957879366826, 'colsample_bytree': 0.5496695462306416, 'min_child_weight': 8, 'gamma': 0.12174104355317295, 'reg_alpha': 0.007497262291448413, 'reg_lambda': 1.3142690753114406e-05, 'max_delta_step': 4}. Best is trial 1 with value: 0.6325057295645531.

Best trial: 1. Best value: 0.632506:   2%|▏         | 3/200 [00:03<02:44,  1.20it/s]

[I 2025-11-10 18:12:45,537] Trial 2 finished with value: 0.5170374331550802 and parameters: {'max_depth': 7, 'learning_rate': 0.19605548126654182, 'n_estimators': 210, 'subsample': 0.8480372039214072, 'colsample_bytree': 0.8094221818256286, 'min_child_weight': 4, 'gamma': 0.4719824016837948, 'reg_alpha': 0.0008523772993591848, 'reg_lambda': 7.227132508894035e-06, 'max_delta_step': 8}. Best is trial 1 with value: 0.6325057295645531.

Best trial: 1. Best value: 0.632506:   2%|▏         | 4/200 [00:06<05:11,  1.59s/it]

[I 2025-11-10 18:12:48,285] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.04857567807517756, 'n_estimators': 959, 'subsample': 0.7861833228231683, 'colsample_bytree': 0.6501361289401355, 'min_child_weight': 10, 'gamma': 2.925120911279275, 'reg_alpha': 0.08557748420806716, 'reg_lambda': 2.5827319396591943, 'max_delta_step': 4}. Best is trial 1 with value: 0.6325057295645531.

Best trial: 1. Best value: 0.632506:   2%|▎         | 5/200 [00:10<08:26,  2.60s/it]

[I 2025-11-10 18:12:52,676] Trial 4 finished with value: 0.48368372803666926 and parameters: {'max_depth': 6, 'learning_rate': 0.25870913244468935, 'n_estimators': 724, 'subsample': 0.7539712024285508, 'colsample_bytree': 0.9064454036884155, 'min_child_weight': 3, 'gamma': 4.563423090983422, 'reg_alpha': 2.0602217933391548e-05, 'reg_lambda': 0.14609434974920285, 'max_delta_step': 0}. Best is trial 1 with value: 0.6325057295645531.

Best trial: 1. Best value: 0.632506:   3%|▎         | 6/200 [00:13<09:08,  2.83s/it]

[I 2025-11-10 18:12:55,949] Trial 5 finished with value: 0.5706676852559205 and parameters: {'max_depth': 8, 'learning_rate': 0.029291133758581802, 'n_estimators': 1473, 'subsample': 0.668603113542385, 'colsample_bytree': 0.8090789168075135, 'min_child_weight': 6, 'gamma': 4.088006334005727, 'reg_alpha': 3.059808141761202e-07, 'reg_lambda': 0.0029787004681196823, 'max_delta_step': 7}. Best is trial 1 with value: 0.6325057295645531.
[I 2025-11-10 18:12:55,971] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07069827596188613, 'n_estimators': 1316, 'subsample': 0.5139739224723368, 'colsample_bytree': 0.8225209028535483, 'min_child_weight': 9, 'gamma': 2.69589016271117, 'reg_alpha': 0.00024606707073697833, 'reg_lambda': 9.09270641424228e-06, 'max_delta_step': 2}. Best is trial 1 with value: 0.6325057295645531.

Best trial: 1. Best value: 0.632506:   4%|▍         | 8/200 [00:14<04:52,  1.52s/it]

[I 2025-11-10 18:12:56,311] Trial 8 finished with value: 0.511824293353705 and parameters: {'max_depth': 5, 'learning_rate': 0.2777314290967103, 'n_estimators': 278, 'subsample': 0.5332634746180214, 'colsample_bytree': 0.8112825944427089, 'min_child_weight': 1, 'gamma': 2.3798319672267603, 'reg_alpha': 3.923002073611244e-06, 'reg_lambda': 9.517457087028464e-07, 'max_delta_step': 4}. Best is trial 1 with value: 0.6325057295645531.

Best trial: 1. Best value: 0.632506:   4%|▍         | 9/200 [00:15<04:54,  1.54s/it]

[I 2025-11-10 18:12:57,903] Trial 6 finished with value: 0.5077830404889229 and parameters: {'max_depth': 3, 'learning_rate': 0.06053998515993276, 'n_estimators': 1248, 'subsample': 0.8750163928582546, 'colsample_bytree': 0.79571811881716, 'min_child_weight': 4, 'gamma': 2.699832214051996, 'reg_alpha': 4.1879905069263896e-05, 'reg_lambda': 3.03482857913102e-05, 'max_delta_step': 2}. Best is trial 1 with value: 0.6325057295645531.

Best trial: 1. Best value: 0.632506:   5%|▌         | 10/200 [00:16<04:42,  1.49s/it]

[I 2025-11-10 18:12:59,245] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.011214122440647557, 'n_estimators': 463, 'subsample': 0.6164943121771918, 'colsample_bytree': 0.6536690198816324, 'min_child_weight': 8, 'gamma': 3.3339584791454357, 'reg_alpha': 2.2534051386658485e-06, 'reg_lambda': 3.880423325579997e-05, 'max_delta_step': 3}. Best is trial 1 with value: 0.6325057295645531.

Best trial: 1. Best value: 0.632506:   6%|▌         | 11/200 [00:17<04:10,  1.32s/it]

[I 2025-11-10 18:13:00,146] Trial 10 pruned.

Best trial: 1. Best value: 0.632506:   6%|▌         | 12/200 [00:18<03:08,  1.01s/it]

[I 2025-11-10 18:13:00,351] Trial 13 pruned.

Best trial: 1. Best value: 0.632506:   6%|▋         | 13/200 [00:23<06:49,  2.19s/it]

[I 2025-11-10 18:13:05,459] Trial 12 finished with value: 0.5255248281130633 and parameters: {'max_depth': 8, 'learning_rate': 0.021670389416071096, 'n_estimators': 601, 'subsample': 0.7291814547790717, 'colsample_bytree': 0.6015830662514978, 'min_child_weight': 2, 'gamma': 4.548722235760764, 'reg_alpha': 0.14152741315034761, 'reg_lambda': 2.336619392124115e-06, 'max_delta_step': 2}. Best is trial 1 with value: 0.6325057295645531.

Best trial: 1. Best value: 0.632506:   7%|▋         | 14/200 [00:26<07:26,  2.40s/it]

[I 2025-11-10 18:13:08,355] Trial 9 finished with value: 0.6253002291825822 and parameters: {'max_depth': 6, 'learning_rate': 0.05312374719385554, 'n_estimators': 1458, 'subsample': 0.9295161914174964, 'colsample_bytree': 0.7678550788655607, 'min_child_weight': 8, 'gamma': 1.219926688972695, 'reg_alpha': 1.4494862693202433e-08, 'reg_lambda': 0.00011178121051467395, 'max_delta_step': 6}. Best is trial 1 with value: 0.6325057295645531.

Best trial: 1. Best value: 0.632506:   8%|▊         | 15/200 [00:27<06:53,  2.23s/it]

[I 2025-11-10 18:13:10,191] Trial 14 finished with value: 0.5697219251336898 and parameters: {'max_depth': 8, 'learning_rate': 0.02297958678492939, 'n_estimators': 717, 'subsample': 0.9816190871882774, 'colsample_bytree': 0.5189836290997891, 'min_child_weight': 7, 'gamma': 0.16584807192766313, 'reg_alpha': 2.4604171502454526e-08, 'reg_lambda': 1.2128938509503982e-08, 'max_delta_step': 7}. Best is trial 1 with value: 0.6325057295645531.

Best trial: 1. Best value: 0.632506:   8%|▊         | 16/200 [00:30<07:21,  2.40s/it]

[I 2025-11-10 18:13:12,989] Trial 15 finished with value: 0.5809060351413292 and parameters: {'max_depth': 8, 'learning_rate': 0.029415620182942845, 'n_estimators': 1428, 'subsample': 0.6854549578663616, 'colsample_bytree': 0.505147740006337, 'min_child_weight': 6, 'gamma': 1.3571473673427232, 'reg_alpha': 3.424139230230322e-07, 'reg_lambda': 0.002346208772930702, 'max_delta_step': 6}. Best is trial 1 with value: 0.6325057295645531.

Best trial: 1. Best value: 0.632506:   8%|▊         | 17/200 [00:32<06:17,  2.06s/it]

[I 2025-11-10 18:13:14,262] Trial 19 pruned.

Best trial: 1. Best value: 0.632506:   9%|▉         | 18/200 [00:34<07:02,  2.32s/it]

[I 2025-11-10 18:13:17,193] Trial 17 finished with value: 0.5631222307104661 and parameters: {'max_depth': 6, 'learning_rate': 0.13190967496906453, 'n_estimators': 892, 'subsample': 0.9967417023880729, 'colsample_bytree': 0.929029959200351, 'min_child_weight': 7, 'gamma': 1.2869589151626466, 'reg_alpha': 1.1063448684685489e-08, 'reg_lambda': 0.0007372255748174582, 'max_delta_step': 6}. Best is trial 1 with value: 0.6325057295645531.

Best trial: 20. Best value: 0.637785:  10%|▉         | 19/200 [00:36<06:38,  2.20s/it]

[I 2025-11-10 18:13:19,104] Trial 20 finished with value: 0.6377845683728037 and parameters: {'max_depth': 9, 'learning_rate': 0.042662754824217095, 'n_estimators': 435, 'subsample': 0.9114408719967532, 'colsample_bytree': 0.7183367241453871, 'min_child_weight': 8, 'gamma': 1.0619992722315525, 'reg_alpha': 1.4891625154934679e-08, 'reg_lambda': 0.0003790758359498506, 'max_delta_step': 5}. Best is trial 20 with value: 0.6377845683728037.

Best trial: 20. Best value: 0.637785:  10%|█         | 20/200 [00:37<05:13,  1.74s/it]

[I 2025-11-10 18:13:19,777] Trial 18 finished with value: 0.5555828877005349 and parameters: {'max_depth': 6, 'learning_rate': 0.13730950253631966, 'n_estimators': 997, 'subsample': 0.8631798757346879, 'colsample_bytree': 0.942947392566803, 'min_child_weight': 6, 'gamma': 1.1067857521789382, 'reg_alpha': 0.0040594901060079305, 'reg_lambda': 0.0009594152980672615, 'max_delta_step': 6}. Best is trial 20 with value: 0.6377845683728037.

Best trial: 20. Best value: 0.637785:  10%|█         | 21/200 [00:37<03:57,  1.33s/it]

[I 2025-11-10 18:13:20,129] Trial 16 finished with value: 0.5774025974025975 and parameters: {'max_depth': 8, 'learning_rate': 0.03089498997496422, 'n_estimators': 1435, 'subsample': 0.6762867425468526, 'colsample_bytree': 0.9603168324938268, 'min_child_weight': 6, 'gamma': 1.2712086384762114, 'reg_alpha': 1.812897110982504e-08, 'reg_lambda': 0.0009517022234861497, 'max_delta_step': 7}. Best is trial 20 with value: 0.6377845683728037.

Best trial: 20. Best value: 0.637785:  11%|█         | 22/200 [00:40<05:18,  1.79s/it]

[I 2025-11-10 18:13:23,009] Trial 21 finished with value: 0.6311886936592819 and parameters: {'max_depth': 9, 'learning_rate': 0.042248757327322216, 'n_estimators': 452, 'subsample': 0.9337933949096382, 'colsample_bytree': 0.7259514500248574, 'min_child_weight': 8, 'gamma': 0.7635767388129013, 'reg_alpha': 0.0007301874768706332, 'reg_lambda': 1.5504271425509537e-07, 'max_delta_step': 8}. Best is trial 20 with value: 0.6377845683728037.

Best trial: 20. Best value: 0.637785:  12%|█▏        | 23/200 [00:41<04:06,  1.39s/it]

[I 2025-11-10 18:13:23,470] Trial 22 finished with value: 0.597816653934301 and parameters: {'max_depth': 9, 'learning_rate': 0.03505664043360822, 'n_estimators': 422, 'subsample': 0.8081222306980873, 'colsample_bytree': 0.5876101539043356, 'min_child_weight': 8, 'gamma': 0.9061959637462018, 'reg_alpha': 0.000773804507971997, 'reg_lambda': 0.016873888735340882, 'max_delta_step': 4}. Best is trial 20 with value: 0.6377845683728037.

Best trial: 20. Best value: 0.637785:  12%|█▏        | 24/200 [00:41<03:15,  1.11s/it]

[I 2025-11-10 18:13:23,923] Trial 23 finished with value: 0.5903728036669214 and parameters: {'max_depth': 9, 'learning_rate': 0.040920665793856156, 'n_estimators': 407, 'subsample': 0.8034398020165567, 'colsample_bytree': 0.5789388941583979, 'min_child_weight': 8, 'gamma': 0.7218001186228546, 'reg_alpha': 0.0002646937763524459, 'reg_lambda': 0.017196693620837294, 'max_delta_step': 4}. Best is trial 20 with value: 0.6377845683728037.

Best trial: 20. Best value: 0.637785:  12%|█▎        | 25/200 [00:42<02:35,  1.13it/s]

[I 2025-11-10 18:13:24,284] Trial 26 pruned.

Best trial: 20. Best value: 0.637785:  13%|█▎        | 26/200 [00:43<03:13,  1.11s/it]

[I 2025-11-10 18:13:25,923] Trial 24 finished with value: 0.6322964094728801 and parameters: {'max_depth': 9, 'learning_rate': 0.04529973399558326, 'n_estimators': 450, 'subsample': 0.9203752162757866, 'colsample_bytree': 0.7320421449237066, 'min_child_weight': 8, 'gamma': 0.745357717975417, 'reg_alpha': 2.0690276321833822e-07, 'reg_lambda': 5.681715574088767e-05, 'max_delta_step': 5}. Best is trial 20 with value: 0.6377845683728037.

Best trial: 20. Best value: 0.637785:  14%|█▎        | 27/200 [00:43<02:30,  1.15it/s]

[I 2025-11-10 18:13:26,225] Trial 28 pruned.

Best trial: 20. Best value: 0.637785:  14%|█▍        | 29/200 [00:44<01:37,  1.75it/s]

[I 2025-11-10 18:13:26,700] Trial 30 pruned.
[I 2025-11-10 18:13:26,858] Trial 29 pruned.

Best trial: 20. Best value: 0.637785:  15%|█▌        | 30/200 [00:45<01:32,  1.85it/s]

[I 2025-11-10 18:13:27,324] Trial 31 pruned.

Best trial: 20. Best value: 0.637785:  16%|█▌        | 31/200 [00:45<01:31,  1.85it/s]

[I 2025-11-10 18:13:27,872] Trial 32 pruned.

Best trial: 20. Best value: 0.637785:  16%|█▋        | 33/200 [00:46<01:12,  2.30it/s]

[I 2025-11-10 18:13:28,454] Trial 33 pruned.
[I 2025-11-10 18:13:28,607] Trial 27 finished with value: 0.585368220015279 and parameters: {'max_depth': 9, 'learning_rate': 0.09772312347748902, 'n_estimators': 536, 'subsample': 0.9229972303486492, 'colsample_bytree': 0.6972349418264008, 'min_child_weight': 9, 'gamma': 1.7956874552800142, 'reg_alpha': 5.4805779350499136e-05, 'reg_lambda': 1.2410015263037293e-07, 'max_delta_step': 9}. Best is trial 20 with value: 0.6377845683728037.

Best trial: 20. Best value: 0.637785:  16%|█▋        | 33/200 [00:46<01:12,  2.30it/s]

[I 2025-11-10 18:13:28,684] Trial 25 finished with value: 0.6336287242169595 and parameters: {'max_depth': 9, 'learning_rate': 0.04403738728127367, 'n_estimators': 398, 'subsample': 0.92870833655366, 'colsample_bytree': 0.7071257829378029, 'min_child_weight': 8, 'gamma': 0.6395457718083508, 'reg_alpha': 0.000542608740823006, 'reg_lambda': 1.2900623691466257e-07, 'max_delta_step': 9}. Best is trial 20 with value: 0.6377845683728037.

Best trial: 20. Best value: 0.637785:  18%|█▊        | 36/200 [00:49<02:01,  1.35it/s]

[I 2025-11-10 18:13:31,646] Trial 37 finished with value: 0.6137249809014516 and parameters: {'max_depth': 10, 'learning_rate': 0.06464191594165078, 'n_estimators': 218, 'subsample': 0.7612874022549538, 'colsample_bytree': 0.6797526782474708, 'min_child_weight': 7, 'gamma': 0.4479054649990293, 'reg_alpha': 0.030159362021800838, 'reg_lambda': 1.0036674333097655e-08, 'max_delta_step': 5}. Best is trial 20 with value: 0.6377845683728037.
[I 2025-11-10 18:13:31,791] Trial 35 finished with value: 0.6337876241405653 and parameters: {'max_depth': 9, 'learning_rate': 0.06667694710011082, 'n_estimators': 231, 'subsample': 0.9490658199378741, 'colsample_bytree': 0.7275254401019643, 'min_child_weight': 8, 'gamma': 0.835473665302562, 'reg_alpha': 0.0406347036878458, 'reg_lambda': 1.146690151478843e-08, 'max_delta_step': 8}. Best is trial 20 with value: 0.6377845683728037.

Best trial: 36. Best value: 0.640385:  19%|█▉        | 38/200 [00:49<01:19,  2.03it/s]

[I 2025-11-10 18:13:32,061] Trial 38 pruned.
[I 2025-11-10 18:13:32,222] Trial 39 pruned.
[I 2025-11-10 18:13:32,230] Trial 36 finished with value: 0.6403850267379679 and parameters: {'max_depth': 9, 'learning_rate': 0.07013020749695767, 'n_estimators': 258, 'subsample': 0.9422216545234319, 'colsample_bytree': 0.7422404510825286, 'min_child_weight': 8, 'gamma': 0.766536759938218, 'reg_alpha': 0.03038883006459848, 'reg_lambda': 2.0276205798509062e-08, 'max_delta_step': 5}. Best is trial 36 with value: 0.6403850267379679.

Best trial: 36. Best value: 0.640385:  20%|██        | 40/200 [00:50<01:11,  2.23it/s]

[I 2025-11-10 18:13:33,004] Trial 42 pruned.

Best trial: 36. Best value: 0.640385:  20%|██        | 41/200 [00:52<01:50,  1.44it/s]

[I 2025-11-10 18:13:34,496] Trial 34 finished with value: 0.5810603514132925 and parameters: {'max_depth': 9, 'learning_rate': 0.06539130889562725, 'n_estimators': 494, 'subsample': 0.9454446196569458, 'colsample_bytree': 0.7276667709287723, 'min_child_weight': 7, 'gamma': 0.697647367592199, 'reg_alpha': 0.017557245190560566, 'reg_lambda': 2.837992198060975e-08, 'max_delta_step': 5}. Best is trial 36 with value: 0.6403850267379679.

Best trial: 36. Best value: 0.640385:  22%|██▏       | 43/200 [00:52<01:20,  1.94it/s]

[I 2025-11-10 18:13:34,991] Trial 43 pruned.
[I 2025-11-10 18:13:35,146] Trial 40 finished with value: 0.5850932009167303 and parameters: {'max_depth': 7, 'learning_rate': 0.07312291807554722, 'n_estimators': 274, 'subsample': 0.8790574886951433, 'colsample_bytree': 0.7627640175255075, 'min_child_weight': 7, 'gamma': 2.2671601604767933, 'reg_alpha': 0.03748191304928513, 'reg_lambda': 3.475052730755492e-08, 'max_delta_step': 9}. Best is trial 36 with value: 0.6403850267379679.

Best trial: 36. Best value: 0.640385:  22%|██▏       | 44/200 [00:54<02:10,  1.20it/s]

[I 2025-11-10 18:13:36,826] Trial 41 finished with value: 0.5583750954927427 and parameters: {'max_depth': 7, 'learning_rate': 0.022786675804478372, 'n_estimators': 296, 'subsample': 0.9615453192887079, 'colsample_bytree': 0.7737491421750731, 'min_child_weight': 7, 'gamma': 1.5672030504159993, 'reg_alpha': 1.0456070480341808, 'reg_lambda': 3.881694037661209e-08, 'max_delta_step': 9}. Best is trial 36 with value: 0.6403850267379679.

Best trial: 36. Best value: 0.640385:  22%|██▎       | 45/200 [00:55<02:35,  1.00s/it]

[I 2025-11-10 18:13:38,244] Trial 47 pruned.

Best trial: 36. Best value: 0.640385:  23%|██▎       | 46/200 [00:56<02:13,  1.15it/s]

[I 2025-11-10 18:13:38,780] Trial 44 finished with value: 0.626140565317036 and parameters: {'max_depth': 10, 'learning_rate': 0.05059389811763248, 'n_estimators': 266, 'subsample': 0.8831414852949981, 'colsample_bytree': 0.6638186961401564, 'min_child_weight': 8, 'gamma': 0.035099855410395855, 'reg_alpha': 0.16343601834634802, 'reg_lambda': 0.4193476637027026, 'max_delta_step': 4}. Best is trial 36 with value: 0.6403850267379679.

Best trial: 36. Best value: 0.640385:  24%|██▍       | 48/200 [00:57<01:35,  1.59it/s]

[I 2025-11-10 18:13:39,583] Trial 49 pruned.
[I 2025-11-10 18:13:39,681] Trial 45 finished with value: 0.6251168831168832 and parameters: {'max_depth': 10, 'learning_rate': 0.05084600647304973, 'n_estimators': 283, 'subsample': 0.8740825377477399, 'colsample_bytree': 0.7777858144736252, 'min_child_weight': 8, 'gamma': 0.37211845845626096, 'reg_alpha': 0.29203221191733275, 'reg_lambda': 1.6015990802221777e-05, 'max_delta_step': 4}. Best is trial 36 with value: 0.6403850267379679.

Best trial: 36. Best value: 0.640385:  24%|██▍       | 49/200 [00:57<01:15,  2.00it/s]

[I 2025-11-10 18:13:39,877] Trial 48 pruned.

Best trial: 36. Best value: 0.640385:  25%|██▌       | 50/200 [00:59<02:07,  1.18it/s]

[I 2025-11-10 18:13:41,557] Trial 46 finished with value: 0.6241268143621086 and parameters: {'max_depth': 10, 'learning_rate': 0.05295067867623205, 'n_estimators': 376, 'subsample': 0.9736903329897733, 'colsample_bytree': 0.7951217080962367, 'min_child_weight': 8, 'gamma': 0.34580078892514643, 'reg_alpha': 0.3650058228692496, 'reg_lambda': 8.803592691822775e-06, 'max_delta_step': 4}. Best is trial 36 with value: 0.6403850267379679.

Best trial: 36. Best value: 0.640385:  26%|██▌       | 51/200 [01:00<02:09,  1.15it/s]

[I 2025-11-10 18:13:42,463] Trial 53 pruned.

Best trial: 36. Best value: 0.640385:  26%|██▌       | 52/200 [01:02<03:17,  1.34s/it]

[I 2025-11-10 18:13:44,905] Trial 52 finished with value: 0.6027876241405653 and parameters: {'max_depth': 8, 'learning_rate': 0.03466507461355271, 'n_estimators': 496, 'subsample': 0.9798180965406491, 'colsample_bytree': 0.6896408889784017, 'min_child_weight': 9, 'gamma': 1.033717376970933, 'reg_alpha': 0.005531111669486655, 'reg_lambda': 3.575144175378166e-07, 'max_delta_step': 7}. Best is trial 36 with value: 0.6403850267379679.

Best trial: 36. Best value: 0.640385:  26%|██▋       | 53/200 [01:03<02:52,  1.17s/it]

[I 2025-11-10 18:13:45,693] Trial 51 finished with value: 0.5983216195569137 and parameters: {'max_depth': 8, 'learning_rate': 0.07644285786844333, 'n_estimators': 667, 'subsample': 0.9782203595626054, 'colsample_bytree': 0.7978216621879576, 'min_child_weight': 9, 'gamma': 1.0457353055565912, 'reg_alpha': 0.008713099377788646, 'reg_lambda': 3.7822452100537537e-07, 'max_delta_step': 6}. Best is trial 36 with value: 0.6403850267379679.

Best trial: 36. Best value: 0.640385:  27%|██▋       | 54/200 [01:03<02:18,  1.05it/s]

[I 2025-11-10 18:13:46,124] Trial 50 finished with value: 0.6360412528647823 and parameters: {'max_depth': 8, 'learning_rate': 0.10879633916118824, 'n_estimators': 668, 'subsample': 0.9808001594233171, 'colsample_bytree': 0.7895564776474286, 'min_child_weight': 8, 'gamma': 0.9582788054513005, 'reg_alpha': 0.007751657152650322, 'reg_lambda': 7.148766687485898e-06, 'max_delta_step': 6}. Best is trial 36 with value: 0.6403850267379679.

Best trial: 36. Best value: 0.640385:  28%|██▊       | 55/200 [01:05<03:02,  1.26s/it]

[I 2025-11-10 18:13:48,091] Trial 57 pruned.

Best trial: 36. Best value: 0.640385:  28%|██▊       | 56/200 [01:06<02:46,  1.16s/it]

[I 2025-11-10 18:13:49,028] Trial 55 finished with value: 0.6296699770817418 and parameters: {'max_depth': 9, 'learning_rate': 0.045224586573039856, 'n_estimators': 257, 'subsample': 0.9428266997904942, 'colsample_bytree': 0.7426308016302378, 'min_child_weight': 8, 'gamma': 0.6186895268657511, 'reg_alpha': 4.1647843594086956e-08, 'reg_lambda': 3.0008458824503e-06, 'max_delta_step': 5}. Best is trial 36 with value: 0.6403850267379679.

Best trial: 36. Best value: 0.640385:  28%|██▊       | 57/200 [01:07<02:16,  1.04it/s]

[I 2025-11-10 18:13:49,512] Trial 54 finished with value: 0.6357005347593583 and parameters: {'max_depth': 9, 'learning_rate': 0.026614513907873023, 'n_estimators': 478, 'subsample': 0.9330416877049098, 'colsample_bytree': 0.7471160978548378, 'min_child_weight': 8, 'gamma': 0.6436706745461731, 'reg_alpha': 0.007966195779520171, 'reg_lambda': 4.7601077909462873e-07, 'max_delta_step': 5}. Best is trial 36 with value: 0.6403850267379679.

Best trial: 36. Best value: 0.640385:  29%|██▉       | 58/200 [01:07<01:58,  1.20it/s]

[I 2025-11-10 18:13:50,054] Trial 58 pruned.

Best trial: 36. Best value: 0.640385:  30%|██▉       | 59/200 [01:08<02:11,  1.07it/s]

[I 2025-11-10 18:13:51,223] Trial 59 pruned.

Best trial: 36. Best value: 0.640385:  30%|███       | 60/200 [01:09<01:56,  1.20it/s]

[I 2025-11-10 18:13:51,811] Trial 61 pruned.

Best trial: 36. Best value: 0.640385:  30%|███       | 61/200 [01:10<01:45,  1.32it/s]

[I 2025-11-10 18:13:52,400] Trial 63 pruned.

Best trial: 36. Best value: 0.640385:  31%|███       | 62/200 [01:13<03:31,  1.53s/it]

[I 2025-11-10 18:13:55,736] Trial 56 finished with value: 0.6333934300993124 and parameters: {'max_depth': 9, 'learning_rate': 0.02546536401453581, 'n_estimators': 773, 'subsample': 0.9430653679860819, 'colsample_bytree': 0.7276653343308566, 'min_child_weight': 8, 'gamma': 0.6065135207473793, 'reg_alpha': 4.2719279524583776e-08, 'reg_lambda': 6.012118792346717e-06, 'max_delta_step': 5}. Best is trial 36 with value: 0.6403850267379679.

Best trial: 36. Best value: 0.640385:  32%|███▏      | 63/200 [01:15<03:56,  1.72s/it]

[I 2025-11-10 18:13:57,915] Trial 64 finished with value: 0.6065958747135218 and parameters: {'max_depth': 9, 'learning_rate': 0.025712427796598318, 'n_estimators': 361, 'subsample': 0.9084315371334959, 'colsample_bytree': 0.82166100814451, 'min_child_weight': 7, 'gamma': 1.1253576433531252, 'reg_alpha': 0.0014050880567456326, 'reg_lambda': 1.4113814077732815e-06, 'max_delta_step': 5}. Best is trial 36 with value: 0.6403850267379679.

Best trial: 36. Best value: 0.640385:  32%|███▏      | 64/200 [01:17<03:45,  1.66s/it]

[I 2025-11-10 18:13:59,419] Trial 66 pruned.

Best trial: 36. Best value: 0.640385:  32%|███▎      | 65/200 [01:19<03:56,  1.75s/it]

[I 2025-11-10 18:14:01,396] Trial 67 pruned.

Best trial: 36. Best value: 0.640385:  33%|███▎      | 66/200 [01:22<05:16,  2.37s/it]

[I 2025-11-10 18:14:05,186] Trial 65 finished with value: 0.5916287242169596 and parameters: {'max_depth': 9, 'learning_rate': 0.02739358331879503, 'n_estimators': 795, 'subsample': 0.9127296668886692, 'colsample_bytree': 0.7189820784239072, 'min_child_weight': 7, 'gamma': 1.1480675768379385, 'reg_alpha': 5.0165101912134135e-08, 'reg_lambda': 7.163829163763062e-08, 'max_delta_step': 5}. Best is trial 36 with value: 0.6403850267379679.

Best trial: 36. Best value: 0.640385:  34%|███▎      | 67/200 [01:24<04:23,  1.98s/it]

[I 2025-11-10 18:14:06,269] Trial 60 finished with value: 0.5394117647058823 and parameters: {'max_depth': 9, 'learning_rate': 0.018927646375626998, 'n_estimators': 815, 'subsample': 0.9990683156622848, 'colsample_bytree': 0.7132477013561891, 'min_child_weight': 1, 'gamma': 0.9175602275472187, 'reg_alpha': 0.0005357543977553173, 'reg_lambda': 6.712082587670103e-08, 'max_delta_step': 7}. Best is trial 36 with value: 0.6403850267379679.

Best trial: 36. Best value: 0.640385:  34%|███▍      | 68/200 [01:24<03:34,  1.63s/it]

[I 2025-11-10 18:14:07,075] Trial 62 finished with value: 0.5632681436210847 and parameters: {'max_depth': 9, 'learning_rate': 0.01955011623942294, 'n_estimators': 770, 'subsample': 0.8621346441689024, 'colsample_bytree': 0.7153722648737854, 'min_child_weight': 1, 'gamma': 1.3979870863947765, 'reg_alpha': 0.001319768338537375, 'reg_lambda': 7.968504661618423e-08, 'max_delta_step': 6}. Best is trial 36 with value: 0.6403850267379679.

Best trial: 36. Best value: 0.640385:  34%|███▍      | 69/200 [01:26<03:45,  1.72s/it]

[I 2025-11-10 18:14:09,021] Trial 68 finished with value: 0.5863773873185638 and parameters: {'max_depth': 9, 'learning_rate': 0.025913262621611564, 'n_estimators': 493, 'subsample': 0.9553621255819411, 'colsample_bytree': 0.729229862131975, 'min_child_weight': 7, 'gamma': 0.5608728286470098, 'reg_alpha': 0.0039983029416316785, 'reg_lambda': 0.0003588880752455833, 'max_delta_step': 7}. Best is trial 36 with value: 0.6403850267379679.

Best trial: 71. Best value: 0.642406:  35%|███▌      | 70/200 [01:31<05:56,  2.75s/it]

[I 2025-11-10 18:14:14,153] Trial 71 finished with value: 0.6424064171122995 and parameters: {'max_depth': 8, 'learning_rate': 0.03975100986005111, 'n_estimators': 505, 'subsample': 0.9683766516686187, 'colsample_bytree': 0.6863394049632177, 'min_child_weight': 8, 'gamma': 0.5927389181045063, 'reg_alpha': 0.003393435810965233, 'reg_lambda': 0.00026470294583824016, 'max_delta_step': 3}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  36%|███▌      | 71/200 [01:32<04:38,  2.16s/it]

[I 2025-11-10 18:14:14,949] Trial 69 finished with value: 0.6405958747135219 and parameters: {'max_depth': 9, 'learning_rate': 0.040170177066600914, 'n_estimators': 892, 'subsample': 0.9611646769546937, 'colsample_bytree': 0.6871611927474801, 'min_child_weight': 8, 'gamma': 0.797044139364995, 'reg_alpha': 0.0004091639047829545, 'reg_lambda': 2.3887994058202575e-07, 'max_delta_step': 7}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  36%|███▌      | 72/200 [01:33<03:29,  1.64s/it]

[I 2025-11-10 18:14:15,364] Trial 73 pruned.

Best trial: 71. Best value: 0.642406:  36%|███▋      | 73/200 [01:35<04:05,  1.93s/it]

[I 2025-11-10 18:14:17,995] Trial 72 finished with value: 0.6358533231474408 and parameters: {'max_depth': 8, 'learning_rate': 0.05871215809070412, 'n_estimators': 901, 'subsample': 0.9699926914216036, 'colsample_bytree': 0.6875038921432425, 'min_child_weight': 8, 'gamma': 0.650097416470368, 'reg_alpha': 1.859125859288822e-05, 'reg_lambda': 7.947264604350602, 'max_delta_step': 4}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  37%|███▋      | 74/200 [01:37<03:56,  1.88s/it]

[I 2025-11-10 18:14:19,745] Trial 70 finished with value: 0.6321588999236057 and parameters: {'max_depth': 8, 'learning_rate': 0.01229008274458066, 'n_estimators': 879, 'subsample': 0.9717083176189358, 'colsample_bytree': 0.7858768033082589, 'min_child_weight': 8, 'gamma': 0.6060007658618303, 'reg_alpha': 0.0028901382696780776, 'reg_lambda': 0.00037169662645824235, 'max_delta_step': 6}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  38%|███▊      | 76/200 [01:41<03:51,  1.87s/it]

[I 2025-11-10 18:14:24,078] Trial 75 finished with value: 0.6395248281130634 and parameters: {'max_depth': 8, 'learning_rate': 0.06383423906648854, 'n_estimators': 959, 'subsample': 0.9680150603780021, 'colsample_bytree': 0.6361980607984478, 'min_child_weight': 8, 'gamma': 0.7911978459038868, 'reg_alpha': 0.00033993450956529725, 'reg_lambda': 2.2017818050495355e-07, 'max_delta_step': 1}. Best is trial 71 with value: 0.6424064171122995.
[I 2025-11-10 18:14:24,211] Trial 74 finished with value: 0.6415431627196333 and parameters: {'max_depth': 8, 'learning_rate': 0.03885881156609762, 'n_estimators': 892, 'subsample': 0.9682338606810701, 'colsample_bytree': 0.6811254739155544, 'min_child_weight': 8, 'gamma': 0.7682081904888629, 'reg_alpha': 0.00012918624748398225, 'reg_lambda': 2.0908173855677664e-07, 'max_delta_step': 1}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  38%|███▊      | 77/200 [01:43<03:51,  1.88s/it]

[I 2025-11-10 18:14:26,120] Trial 79 pruned.

Best trial: 71. Best value: 0.642406:  39%|███▉      | 78/200 [01:44<03:02,  1.50s/it]

[I 2025-11-10 18:14:26,718] Trial 76 finished with value: 0.6326799083269672 and parameters: {'max_depth': 8, 'learning_rate': 0.059867995838705675, 'n_estimators': 900, 'subsample': 0.9665819190840313, 'colsample_bytree': 0.6468450880595957, 'min_child_weight': 8, 'gamma': 0.8282678647456283, 'reg_alpha': 1.7494526231485933e-05, 'reg_lambda': 6.37136420170927, 'max_delta_step': 3}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  40%|███▉      | 79/200 [01:46<03:16,  1.63s/it]

[I 2025-11-10 18:14:28,649] Trial 77 finished with value: 0.6031940412528648 and parameters: {'max_depth': 8, 'learning_rate': 0.0409458121412925, 'n_estimators': 963, 'subsample': 0.9839045559498839, 'colsample_bytree': 0.6324932083188894, 'min_child_weight': 9, 'gamma': 0.8492733957481304, 'reg_alpha': 8.852262430125492e-06, 'reg_lambda': 6.93966424565464, 'max_delta_step': 3}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  40%|████      | 80/200 [01:48<03:27,  1.73s/it]

[I 2025-11-10 18:14:30,623] Trial 82 pruned.

Best trial: 71. Best value: 0.642406:  40%|████      | 81/200 [01:49<03:20,  1.69s/it]

[I 2025-11-10 18:14:32,204] Trial 83 pruned.

Best trial: 71. Best value: 0.642406:  41%|████      | 82/200 [01:50<02:27,  1.25s/it]

[I 2025-11-10 18:14:32,450] Trial 78 finished with value: 0.6006760886172652 and parameters: {'max_depth': 7, 'learning_rate': 0.059341703225656406, 'n_estimators': 928, 'subsample': 0.9826096690384064, 'colsample_bytree': 0.6393898868273908, 'min_child_weight': 9, 'gamma': 0.7531923937547923, 'reg_alpha': 5.702568908089071e-05, 'reg_lambda': 9.985265663612784, 'max_delta_step': 1}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  42%|████▏     | 83/200 [01:52<02:46,  1.43s/it]

[I 2025-11-10 18:14:34,275] Trial 84 pruned.

Best trial: 71. Best value: 0.642406:  42%|████▏     | 84/200 [01:54<03:07,  1.62s/it]

[I 2025-11-10 18:14:36,349] Trial 81 finished with value: 0.5609404125286478 and parameters: {'max_depth': 8, 'learning_rate': 0.04015308363340208, 'n_estimators': 995, 'subsample': 0.9868800603064976, 'colsample_bytree': 0.618772620187845, 'min_child_weight': 7, 'gamma': 2.0381928127197684, 'reg_alpha': 6.805103254919399e-05, 'reg_lambda': 1.852904738805316e-07, 'max_delta_step': 2}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  42%|████▎     | 85/200 [01:54<02:25,  1.26s/it]

[I 2025-11-10 18:14:36,776] Trial 86 pruned.

Best trial: 71. Best value: 0.642406:  43%|████▎     | 86/200 [01:54<01:52,  1.01it/s]

[I 2025-11-10 18:14:37,135] Trial 80 finished with value: 0.5666378915202446 and parameters: {'max_depth': 8, 'learning_rate': 0.03996743078747422, 'n_estimators': 1045, 'subsample': 0.9651705026892123, 'colsample_bytree': 0.6374058534482024, 'min_child_weight': 7, 'gamma': 0.9862843452510114, 'reg_alpha': 0.0001270246137203239, 'reg_lambda': 9.401627556912375, 'max_delta_step': 2}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  44%|████▎     | 87/200 [01:56<02:03,  1.09s/it]

[I 2025-11-10 18:14:38,449] Trial 88 pruned.

Best trial: 71. Best value: 0.642406:  44%|████▍     | 88/200 [01:57<01:53,  1.02s/it]

[I 2025-11-10 18:14:39,297] Trial 87 pruned.

Best trial: 71. Best value: 0.642406:  44%|████▍     | 89/200 [01:57<01:40,  1.11it/s]

[I 2025-11-10 18:14:39,934] Trial 89 pruned.

Best trial: 71. Best value: 0.642406:  45%|████▌     | 90/200 [01:58<01:31,  1.21it/s]

[I 2025-11-10 18:14:40,593] Trial 90 pruned.

Best trial: 71. Best value: 0.642406:  46%|████▌     | 91/200 [01:59<01:29,  1.22it/s]

[I 2025-11-10 18:14:41,384] Trial 91 pruned.

Best trial: 71. Best value: 0.642406:  46%|████▌     | 92/200 [01:59<01:15,  1.44it/s]

[I 2025-11-10 18:14:41,796] Trial 92 pruned.

Best trial: 71. Best value: 0.642406:  46%|████▋     | 93/200 [02:00<01:07,  1.58it/s]

[I 2025-11-10 18:14:42,283] Trial 93 pruned.

Best trial: 71. Best value: 0.642406:  47%|████▋     | 94/200 [02:01<01:22,  1.28it/s]

[I 2025-11-10 18:14:43,412] Trial 94 pruned.

Best trial: 71. Best value: 0.642406:  48%|████▊     | 95/200 [02:01<01:11,  1.46it/s]

[I 2025-11-10 18:14:43,872] Trial 95 pruned.

Best trial: 71. Best value: 0.642406:  48%|████▊     | 96/200 [02:02<01:03,  1.64it/s]

[I 2025-11-10 18:14:44,310] Trial 98 pruned.

Best trial: 71. Best value: 0.642406:  48%|████▊     | 97/200 [02:02<00:50,  2.04it/s]

[I 2025-11-10 18:14:44,516] Trial 97 pruned.

Best trial: 71. Best value: 0.642406:  49%|████▉     | 98/200 [02:02<00:43,  2.33it/s]

[I 2025-11-10 18:14:44,803] Trial 85 finished with value: 0.6346042780748663 and parameters: {'max_depth': 8, 'learning_rate': 0.04018247810380604, 'n_estimators': 1185, 'subsample': 0.932257296924128, 'colsample_bytree': 0.6870801232274889, 'min_child_weight': 8, 'gamma': 1.2502713222054138, 'reg_alpha': 0.0003737399224811388, 'reg_lambda': 5.789161296385361e-07, 'max_delta_step': 0}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  50%|████▉     | 99/200 [02:03<00:46,  2.15it/s]

[I 2025-11-10 18:14:45,354] Trial 99 pruned.

Best trial: 71. Best value: 0.642406:  50%|█████     | 100/200 [02:03<00:43,  2.32it/s]

[I 2025-11-10 18:14:45,704] Trial 100 pruned.

Best trial: 71. Best value: 0.642406:  50%|█████     | 101/200 [02:04<01:01,  1.62it/s]

[I 2025-11-10 18:14:46,762] Trial 101 pruned.

Best trial: 71. Best value: 0.642406:  51%|█████     | 102/200 [02:04<00:54,  1.81it/s]

[I 2025-11-10 18:14:47,159] Trial 102 pruned.

Best trial: 71. Best value: 0.642406:  52%|█████▏    | 103/200 [02:05<00:57,  1.70it/s]

[I 2025-11-10 18:14:47,826] Trial 105 pruned.

Best trial: 71. Best value: 0.642406:  52%|█████▏    | 104/200 [02:06<01:11,  1.35it/s]

[I 2025-11-10 18:14:48,930] Trial 103 pruned.

Best trial: 71. Best value: 0.642406:  52%|█████▎    | 105/200 [02:07<01:19,  1.20it/s]

[I 2025-11-10 18:14:49,983] Trial 96 finished with value: 0.6085874713521772 and parameters: {'max_depth': 9, 'learning_rate': 0.06707683158491602, 'n_estimators': 916, 'subsample': 0.9472044109858492, 'colsample_bytree': 0.665484611978309, 'min_child_weight': 8, 'gamma': 2.8398448957713063, 'reg_alpha': 0.005931705789113391, 'reg_lambda': 1.8201139720610117e-08, 'max_delta_step': 5}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  53%|█████▎    | 106/200 [02:08<01:08,  1.37it/s]

[I 2025-11-10 18:14:50,474] Trial 104 pruned.

Best trial: 71. Best value: 0.642406:  54%|█████▎    | 107/200 [02:12<02:39,  1.72s/it]

[I 2025-11-10 18:14:54,491] Trial 106 finished with value: 0.6313353705118411 and parameters: {'max_depth': 9, 'learning_rate': 0.04257369067756181, 'n_estimators': 634, 'subsample': 0.9645369304772653, 'colsample_bytree': 0.7272378957646434, 'min_child_weight': 8, 'gamma': 1.0759195179228052, 'reg_alpha': 0.0008280570797347748, 'reg_lambda': 0.6914083814588288, 'max_delta_step': 1}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  54%|█████▍    | 108/200 [02:12<02:01,  1.32s/it]

[I 2025-11-10 18:14:54,879] Trial 107 finished with value: 0.6231741787624141 and parameters: {'max_depth': 9, 'learning_rate': 0.07960389323935874, 'n_estimators': 646, 'subsample': 0.9076596655122507, 'colsample_bytree': 0.7209278242618912, 'min_child_weight': 8, 'gamma': 1.6110972802120278, 'reg_alpha': 0.0027455164784614336, 'reg_lambda': 1.5475342825672083e-06, 'max_delta_step': 6}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  55%|█████▍    | 109/200 [02:14<02:13,  1.46s/it]

[I 2025-11-10 18:14:56,683] Trial 108 finished with value: 0.6332200152788388 and parameters: {'max_depth': 9, 'learning_rate': 0.043532399906234795, 'n_estimators': 626, 'subsample': 0.9091003206979219, 'colsample_bytree': 0.7180597665225336, 'min_child_weight': 8, 'gamma': 1.1241965667563008, 'reg_alpha': 0.0009270464500328313, 'reg_lambda': 1.7100940103576163e-06, 'max_delta_step': 6}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  55%|█████▌    | 110/200 [02:14<01:40,  1.12s/it]

[I 2025-11-10 18:14:57,001] Trial 111 pruned.
[I 2025-11-10 18:14:57,185] Trial 109 finished with value: 0.6259144385026738 and parameters: {'max_depth': 9, 'learning_rate': 0.03630294445595619, 'n_estimators': 624, 'subsample': 0.9636621834285248, 'colsample_bytree': 0.7268919780089369, 'min_child_weight': 8, 'gamma': 1.4635608887008371, 'reg_alpha': 0.0024560075934147553, 'reg_lambda': 1.7535778378995253e-06, 'max_delta_step': 6}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  56%|█████▌    | 112/200 [02:16<01:32,  1.05s/it]

[I 2025-11-10 18:14:58,712] Trial 114 pruned.

Best trial: 71. Best value: 0.642406:  56%|█████▋    | 113/200 [02:16<01:10,  1.24it/s]

[I 2025-11-10 18:14:58,972] Trial 112 pruned.

Best trial: 71. Best value: 0.642406:  57%|█████▋    | 114/200 [02:17<01:02,  1.37it/s]

[I 2025-11-10 18:14:59,520] Trial 115 pruned.

Best trial: 71. Best value: 0.642406:  57%|█████▊    | 115/200 [02:17<00:52,  1.62it/s]

[I 2025-11-10 18:14:59,864] Trial 116 pruned.

Best trial: 71. Best value: 0.642406:  58%|█████▊    | 116/200 [02:19<01:18,  1.07it/s]

[I 2025-11-10 18:15:01,545] Trial 118 pruned.

Best trial: 71. Best value: 0.642406:  58%|█████▊    | 117/200 [02:19<01:00,  1.37it/s]

[I 2025-11-10 18:15:01,794] Trial 117 pruned.

Best trial: 71. Best value: 0.642406:  59%|█████▉    | 118/200 [02:20<00:53,  1.52it/s]

[I 2025-11-10 18:15:02,285] Trial 119 pruned.

Best trial: 71. Best value: 0.642406:  60%|█████▉    | 119/200 [02:20<00:42,  1.92it/s]

[I 2025-11-10 18:15:02,482] Trial 110 finished with value: 0.6302062643239114 and parameters: {'max_depth': 10, 'learning_rate': 0.08001891249778295, 'n_estimators': 842, 'subsample': 0.9357975223327879, 'colsample_bytree': 0.7207209680950637, 'min_child_weight': 8, 'gamma': 1.505411965884957, 'reg_alpha': 0.0035780736086526415, 'reg_lambda': 1.0538055657952332e-05, 'max_delta_step': 6}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  60%|██████    | 120/200 [02:20<00:40,  1.96it/s]

[I 2025-11-10 18:15:02,969] Trial 120 pruned.

Best trial: 71. Best value: 0.642406:  60%|██████    | 121/200 [02:21<00:46,  1.68it/s]

[I 2025-11-10 18:15:03,756] Trial 122 pruned.

Best trial: 71. Best value: 0.642406:  61%|██████    | 122/200 [02:25<02:12,  1.70s/it]

[I 2025-11-10 18:15:08,054] Trial 121 finished with value: 0.6300977845683728 and parameters: {'max_depth': 8, 'learning_rate': 0.045319281571574666, 'n_estimators': 464, 'subsample': 0.957407874874561, 'colsample_bytree': 0.6732114280871009, 'min_child_weight': 8, 'gamma': 0.8303814152334967, 'reg_alpha': 0.012296734749535326, 'reg_lambda': 1.117239875356027e-05, 'max_delta_step': 4}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  62%|██████▏   | 123/200 [02:27<02:03,  1.61s/it]

[I 2025-11-10 18:15:09,439] Trial 123 finished with value: 0.6342597402597403 and parameters: {'max_depth': 9, 'learning_rate': 0.030091147635200276, 'n_estimators': 465, 'subsample': 0.9573309695225876, 'colsample_bytree': 0.6874441425558623, 'min_child_weight': 8, 'gamma': 0.6927839435375961, 'reg_alpha': 0.00027152741270429796, 'reg_lambda': 0.0006888676493206375, 'max_delta_step': 4}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  62%|██████▏   | 124/200 [02:27<01:29,  1.18s/it]

[I 2025-11-10 18:15:09,632] Trial 113 finished with value: 0.6144010695187166 and parameters: {'max_depth': 8, 'learning_rate': 0.0510638006220299, 'n_estimators': 1493, 'subsample': 0.9884435083126009, 'colsample_bytree': 0.7041451266062271, 'min_child_weight': 9, 'gamma': 1.4834109829172608, 'reg_alpha': 0.024148020927025293, 'reg_lambda': 2.9272995499451047e-08, 'max_delta_step': 2}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  62%|██████▎   | 125/200 [02:27<01:14,  1.01it/s]

[I 2025-11-10 18:15:10,169] Trial 125 pruned.

Best trial: 71. Best value: 0.642406:  63%|██████▎   | 126/200 [02:29<01:20,  1.08s/it]

[I 2025-11-10 18:15:11,475] Trial 128 pruned.

Best trial: 71. Best value: 0.642406:  64%|██████▎   | 127/200 [02:31<01:48,  1.49s/it]

[I 2025-11-10 18:15:13,909] Trial 124 finished with value: 0.6360106951871658 and parameters: {'max_depth': 9, 'learning_rate': 0.02366765412242761, 'n_estimators': 750, 'subsample': 0.9471781731185566, 'colsample_bytree': 0.7366236750599383, 'min_child_weight': 8, 'gamma': 0.6457368793151582, 'reg_alpha': 2.5690578467543876e-08, 'reg_lambda': 4.129176268829534e-07, 'max_delta_step': 5}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  64%|██████▍   | 128/200 [02:31<01:21,  1.13s/it]

[I 2025-11-10 18:15:14,200] Trial 127 finished with value: 0.627170359052712 and parameters: {'max_depth': 9, 'learning_rate': 0.029996755032007716, 'n_estimators': 283, 'subsample': 0.947433927755148, 'colsample_bytree': 0.6883525063004456, 'min_child_weight': 8, 'gamma': 0.6702823724457798, 'reg_alpha': 0.0002990313355468665, 'reg_lambda': 0.0006097926815890486, 'max_delta_step': 3}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  64%|██████▍   | 129/200 [02:33<01:22,  1.16s/it]

[I 2025-11-10 18:15:15,414] Trial 126 finished with value: 0.6326264323911382 and parameters: {'max_depth': 9, 'learning_rate': 0.040452824170911963, 'n_estimators': 391, 'subsample': 0.9488469786990543, 'colsample_bytree': 0.6887734754742122, 'min_child_weight': 8, 'gamma': 0.6623618695010034, 'reg_alpha': 0.00038525852384148097, 'reg_lambda': 0.0012451937182193476, 'max_delta_step': 3}. Best is trial 71 with value: 0.6424064171122995.
[I 2025-11-10 18:15:15,459] Trial 129 finished with value: 0.6289472880061115 and parameters: {'max_depth': 9, 'learning_rate': 0.035182386687242724, 'n_estimators': 254, 'subsample': 0.9706404884074441, 'colsample_bytree': 0.6917238710598045, 'min_child_weight': 8, 'gamma': 0.9902928380958165, 'reg_alpha': 0.0003985363523448657, 'reg_lambda': 0.000567688608110102, 'max_delta_step': 5}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  66%|██████▌   | 131/200 [02:34<01:04,  1.08it/s]

[I 2025-11-10 18:15:16,743] Trial 133 pruned.

Best trial: 71. Best value: 0.642406:  66%|██████▌   | 132/200 [02:37<01:36,  1.42s/it]

[I 2025-11-10 18:15:19,659] Trial 134 pruned.

Best trial: 71. Best value: 0.642406:  66%|██████▋   | 133/200 [02:40<02:03,  1.85s/it]

[I 2025-11-10 18:15:22,721] Trial 131 finished with value: 0.6237005347593583 and parameters: {'max_depth': 9, 'learning_rate': 0.023503986068302164, 'n_estimators': 681, 'subsample': 0.9697352438278489, 'colsample_bytree': 0.6084847738115161, 'min_child_weight': 8, 'gamma': 0.9207569435006866, 'reg_alpha': 1.030999788172041e-06, 'reg_lambda': 5.040814268466767e-07, 'max_delta_step': 5}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  67%|██████▋   | 134/200 [02:40<01:36,  1.46s/it]

[I 2025-11-10 18:15:23,117] Trial 130 finished with value: 0.6300366692131398 and parameters: {'max_depth': 9, 'learning_rate': 0.021253765184038983, 'n_estimators': 684, 'subsample': 0.9701686345211147, 'colsample_bytree': 0.7329247659074887, 'min_child_weight': 8, 'gamma': 0.9420561429347629, 'reg_alpha': 2.2443863160407855e-08, 'reg_lambda': 0.0009898042420304562, 'max_delta_step': 5}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  68%|██████▊   | 135/200 [02:41<01:19,  1.23s/it]

[I 2025-11-10 18:15:23,757] Trial 136 pruned.

Best trial: 71. Best value: 0.642406:  68%|██████▊   | 136/200 [02:42<01:06,  1.04s/it]

[I 2025-11-10 18:15:24,342] Trial 132 finished with value: 0.6272880061115356 and parameters: {'max_depth': 9, 'learning_rate': 0.022048284053602915, 'n_estimators': 677, 'subsample': 0.9758416931684931, 'colsample_bytree': 0.7349186862058771, 'min_child_weight': 8, 'gamma': 0.9231476137639404, 'reg_alpha': 9.715769438858214e-08, 'reg_lambda': 0.004358835540954941, 'max_delta_step': 5}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  68%|██████▊   | 137/200 [02:42<00:50,  1.24it/s]

[I 2025-11-10 18:15:24,558] Trial 137 pruned.

Best trial: 71. Best value: 0.642406:  69%|██████▉   | 138/200 [02:42<00:44,  1.40it/s]

[I 2025-11-10 18:15:25,060] Trial 138 pruned.

Best trial: 71. Best value: 0.642406:  70%|██████▉   | 139/200 [02:43<00:44,  1.37it/s]

[I 2025-11-10 18:15:25,822] Trial 139 pruned.

Best trial: 71. Best value: 0.642406:  70%|███████   | 140/200 [02:45<00:56,  1.06it/s]

[I 2025-11-10 18:15:27,266] Trial 135 finished with value: 0.6327838044308632 and parameters: {'max_depth': 9, 'learning_rate': 0.024397105071807243, 'n_estimators': 542, 'subsample': 0.9688085283119253, 'colsample_bytree': 0.78966675353879, 'min_child_weight': 8, 'gamma': 0.9225929717554031, 'reg_alpha': 1.4079891093804539e-08, 'reg_lambda': 2.7780469444385643e-07, 'max_delta_step': 4}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  70%|███████   | 141/200 [02:45<00:47,  1.25it/s]

[I 2025-11-10 18:15:27,741] Trial 142 pruned.

Best trial: 71. Best value: 0.642406:  71%|███████   | 142/200 [02:47<01:02,  1.08s/it]

[I 2025-11-10 18:15:29,464] Trial 144 pruned.

Best trial: 71. Best value: 0.642406:  72%|███████▏  | 143/200 [02:49<01:19,  1.40s/it]

[I 2025-11-10 18:15:31,624] Trial 145 pruned.

Best trial: 71. Best value: 0.642406:  72%|███████▏  | 144/200 [02:49<01:03,  1.14s/it]

[I 2025-11-10 18:15:32,165] Trial 143 finished with value: 0.5821940412528648 and parameters: {'max_depth': 10, 'learning_rate': 0.01634414004721097, 'n_estimators': 301, 'subsample': 0.9157490986569079, 'colsample_bytree': 0.7120374443720016, 'min_child_weight': 7, 'gamma': 1.0202596442593288, 'reg_alpha': 0.00014101520056493725, 'reg_lambda': 5.784912325537461e-06, 'max_delta_step': 8}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  72%|███████▎  | 145/200 [02:50<01:00,  1.10s/it]

[I 2025-11-10 18:15:33,172] Trial 141 finished with value: 0.6293995416348357 and parameters: {'max_depth': 10, 'learning_rate': 0.017510715500916308, 'n_estimators': 515, 'subsample': 0.9224788210944214, 'colsample_bytree': 0.7447622372895863, 'min_child_weight': 8, 'gamma': 0.7561628314150358, 'reg_alpha': 0.0007856512028231532, 'reg_lambda': 2.7119031774776923e-07, 'max_delta_step': 7}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  73%|███████▎  | 146/200 [02:51<00:47,  1.13it/s]

[I 2025-11-10 18:15:33,542] Trial 146 pruned.

Best trial: 71. Best value: 0.642406:  74%|███████▎  | 147/200 [02:51<00:37,  1.40it/s]

[I 2025-11-10 18:15:33,866] Trial 140 finished with value: 0.594646294881589 and parameters: {'max_depth': 8, 'learning_rate': 0.017585339777674642, 'n_estimators': 588, 'subsample': 0.9198864410509087, 'colsample_bytree': 0.6432063324111184, 'min_child_weight': 7, 'gamma': 0.7367388106138568, 'reg_alpha': 0.0011357244044107502, 'reg_lambda': 0.008687902447295653, 'max_delta_step': 0}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  74%|███████▍  | 148/200 [02:51<00:29,  1.77it/s]

[I 2025-11-10 18:15:34,084] Trial 149 pruned.

Best trial: 71. Best value: 0.642406:  74%|███████▍  | 149/200 [02:52<00:29,  1.70it/s]

[I 2025-11-10 18:15:34,719] Trial 150 pruned.
[I 2025-11-10 18:15:34,904] Trial 147 pruned.

Best trial: 71. Best value: 0.642406:  76%|███████▌  | 151/200 [02:53<00:30,  1.59it/s]

[I 2025-11-10 18:15:35,912] Trial 148 finished with value: 0.6210068754774637 and parameters: {'max_depth': 9, 'learning_rate': 0.2966201342785699, 'n_estimators': 235, 'subsample': 0.9997413185136873, 'colsample_bytree': 0.6996033657996306, 'min_child_weight': 8, 'gamma': 0.5526238220501146, 'reg_alpha': 2.204580962972192e-07, 'reg_lambda': 0.00019094132722941465, 'max_delta_step': 4}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  76%|███████▌  | 152/200 [02:54<00:30,  1.60it/s]

[I 2025-11-10 18:15:36,529] Trial 153 pruned.

Best trial: 71. Best value: 0.642406:  76%|███████▋  | 153/200 [02:55<00:31,  1.47it/s]

[I 2025-11-10 18:15:37,334] Trial 152 pruned.

Best trial: 71. Best value: 0.642406:  77%|███████▋  | 154/200 [02:55<00:31,  1.47it/s]

[I 2025-11-10 18:15:38,013] Trial 154 pruned.

Best trial: 71. Best value: 0.642406:  78%|███████▊  | 155/200 [02:56<00:37,  1.21it/s]

[I 2025-11-10 18:15:39,191] Trial 157 pruned.

Best trial: 71. Best value: 0.642406:  78%|███████▊  | 156/200 [02:59<00:52,  1.20s/it]

[I 2025-11-10 18:15:41,268] Trial 151 finished with value: 0.6365569136745608 and parameters: {'max_depth': 9, 'learning_rate': 0.025771498132403706, 'n_estimators': 448, 'subsample': 0.9988710272099841, 'colsample_bytree': 0.6975346341762049, 'min_child_weight': 8, 'gamma': 0.5314488034885645, 'reg_alpha': 8.66546972014452e-08, 'reg_lambda': 1.8333850603459583, 'max_delta_step': 6}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  78%|███████▊  | 157/200 [02:59<00:43,  1.00s/it]

[I 2025-11-10 18:15:41,795] Trial 155 finished with value: 0.6348349885408708 and parameters: {'max_depth': 9, 'learning_rate': 0.04274652514535887, 'n_estimators': 429, 'subsample': 0.9429492102444539, 'colsample_bytree': 0.7262823083430832, 'min_child_weight': 8, 'gamma': 1.229817568289012, 'reg_alpha': 0.00023825689553491375, 'reg_lambda': 2.49090440566222e-06, 'max_delta_step': 7}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  79%|███████▉  | 158/200 [03:00<00:40,  1.03it/s]

[I 2025-11-10 18:15:42,678] Trial 160 pruned.
[I 2025-11-10 18:15:42,688] Trial 156 finished with value: 0.6253055767761649 and parameters: {'max_depth': 9, 'learning_rate': 0.04374798405741198, 'n_estimators': 435, 'subsample': 0.907464706100786, 'colsample_bytree': 0.7269152223459878, 'min_child_weight': 8, 'gamma': 1.1433735470839776, 'reg_alpha': 0.000427523270643961, 'reg_lambda': 2.3637598858340223e-06, 'max_delta_step': 6}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  80%|████████  | 161/200 [03:01<00:22,  1.70it/s]

[I 2025-11-10 18:15:43,635] Trial 162 pruned.
[I 2025-11-10 18:15:43,757] Trial 161 pruned.

Best trial: 71. Best value: 0.642406:  81%|████████  | 162/200 [03:02<00:28,  1.35it/s]

[I 2025-11-10 18:15:44,921] Trial 163 pruned.

Best trial: 71. Best value: 0.642406:  82%|████████▏ | 163/200 [03:03<00:26,  1.37it/s]

[I 2025-11-10 18:15:45,625] Trial 164 pruned.

Best trial: 71. Best value: 0.642406:  82%|████████▏ | 164/200 [03:04<00:25,  1.40it/s]

[I 2025-11-10 18:15:46,300] Trial 165 pruned.

Best trial: 71. Best value: 0.642406:  82%|████████▎ | 165/200 [03:04<00:25,  1.40it/s]

[I 2025-11-10 18:15:47,021] Trial 166 pruned.

Best trial: 71. Best value: 0.642406:  83%|████████▎ | 166/200 [03:04<00:19,  1.77it/s]

[I 2025-11-10 18:15:47,212] Trial 158 finished with value: 0.6238090145148969 and parameters: {'max_depth': 8, 'learning_rate': 0.03762508053729267, 'n_estimators': 709, 'subsample': 0.8842129363723569, 'colsample_bytree': 0.7119928877852411, 'min_child_weight': 8, 'gamma': 1.204133449774127, 'reg_alpha': 0.0005131277658288082, 'reg_lambda': 6.816140284461131e-06, 'max_delta_step': 6}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  84%|████████▎ | 167/200 [03:06<00:30,  1.07it/s]

[I 2025-11-10 18:15:49,047] Trial 159 finished with value: 0.6378029029793735 and parameters: {'max_depth': 8, 'learning_rate': 0.029187881506572977, 'n_estimators': 464, 'subsample': 0.9812591237135764, 'colsample_bytree': 0.7109373022644028, 'min_child_weight': 8, 'gamma': 0.30688439423649566, 'reg_alpha': 2.471005117718233e-08, 'reg_lambda': 5.150957551760423, 'max_delta_step': 5}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  84%|████████▍ | 168/200 [03:07<00:24,  1.33it/s]

[I 2025-11-10 18:15:49,356] Trial 168 pruned.

Best trial: 71. Best value: 0.642406:  84%|████████▍ | 169/200 [03:08<00:25,  1.22it/s]

[I 2025-11-10 18:15:50,326] Trial 170 pruned.

Best trial: 71. Best value: 0.642406:  85%|████████▌ | 170/200 [03:08<00:22,  1.35it/s]

[I 2025-11-10 18:15:50,893] Trial 171 pruned.

Best trial: 71. Best value: 0.642406:  86%|████████▌ | 171/200 [03:09<00:24,  1.21it/s]

[I 2025-11-10 18:15:51,925] Trial 172 pruned.

Best trial: 71. Best value: 0.642406:  86%|████████▌ | 172/200 [03:10<00:23,  1.19it/s]

[I 2025-11-10 18:15:52,799] Trial 173 pruned.

Best trial: 71. Best value: 0.642406:  86%|████████▋ | 173/200 [03:10<00:17,  1.52it/s]

[I 2025-11-10 18:15:53,025] Trial 167 finished with value: 0.6300473644003055 and parameters: {'max_depth': 9, 'learning_rate': 0.031769919207869826, 'n_estimators': 413, 'subsample': 0.9643019878252724, 'colsample_bytree': 0.6946210648491884, 'min_child_weight': 8, 'gamma': 0.6693630064275378, 'reg_alpha': 6.631211318779874e-08, 'reg_lambda': 5.054797809175834e-06, 'max_delta_step': 6}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  87%|████████▋ | 174/200 [03:15<00:51,  1.98s/it]

[I 2025-11-10 18:15:58,113] Trial 175 finished with value: 0.6306340718105424 and parameters: {'max_depth': 9, 'learning_rate': 0.026502013031175362, 'n_estimators': 327, 'subsample': 0.9676128139978672, 'colsample_bytree': 0.7364538739766806, 'min_child_weight': 8, 'gamma': 0.6432658333845154, 'reg_alpha': 4.105837380617422e-08, 'reg_lambda': 8.16604669967882, 'max_delta_step': 5}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  88%|████████▊ | 175/200 [03:16<00:39,  1.57s/it]

[I 2025-11-10 18:15:58,702] Trial 174 finished with value: 0.6305324675324674 and parameters: {'max_depth': 9, 'learning_rate': 0.026355694610983832, 'n_estimators': 435, 'subsample': 0.9642601270291701, 'colsample_bytree': 0.7294424807842373, 'min_child_weight': 8, 'gamma': 0.6117843512804495, 'reg_alpha': 4.0743188483096324e-08, 'reg_lambda': 6.100730442314183, 'max_delta_step': 5}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  88%|████████▊ | 176/200 [03:16<00:29,  1.22s/it]

[I 2025-11-10 18:15:59,127] Trial 169 finished with value: 0.6334560733384264 and parameters: {'max_depth': 9, 'learning_rate': 0.02580905018698522, 'n_estimators': 867, 'subsample': 0.9884645918427917, 'colsample_bytree': 0.7736693512101969, 'min_child_weight': 8, 'gamma': 0.6371344547999493, 'reg_alpha': 1.4461339054443001e-07, 'reg_lambda': 1.6518489995569154, 'max_delta_step': 10}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  88%|████████▊ | 177/200 [03:18<00:29,  1.30s/it]

[I 2025-11-10 18:16:00,612] Trial 177 pruned.

Best trial: 71. Best value: 0.642406:  89%|████████▉ | 178/200 [03:18<00:22,  1.02s/it]

[I 2025-11-10 18:16:00,980] Trial 178 pruned.

Best trial: 71. Best value: 0.642406:  90%|████████▉ | 179/200 [03:20<00:24,  1.16s/it]

[I 2025-11-10 18:16:02,471] Trial 176 finished with value: 0.6317853323147441 and parameters: {'max_depth': 9, 'learning_rate': 0.04043614710487866, 'n_estimators': 824, 'subsample': 0.9499145045884032, 'colsample_bytree': 0.7334682621325741, 'min_child_weight': 8, 'gamma': 0.5862901968791112, 'reg_alpha': 2.8395803512835507e-08, 'reg_lambda': 8.393823273199379, 'max_delta_step': 5}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  90%|█████████ | 180/200 [03:21<00:23,  1.19s/it]

[I 2025-11-10 18:16:03,736] Trial 182 pruned.

Best trial: 71. Best value: 0.642406:  90%|█████████ | 181/200 [03:26<00:41,  2.20s/it]

[I 2025-11-10 18:16:08,283] Trial 179 finished with value: 0.6317196333078686 and parameters: {'max_depth': 5, 'learning_rate': 0.034746843194868274, 'n_estimators': 880, 'subsample': 0.9907505174034364, 'colsample_bytree': 0.7727021890909208, 'min_child_weight': 8, 'gamma': 0.8584558050990432, 'reg_alpha': 1.8060935168657575e-08, 'reg_lambda': 1.687668363085293, 'max_delta_step': 4}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  91%|█████████ | 182/200 [03:26<00:31,  1.77s/it]

[I 2025-11-10 18:16:09,038] Trial 181 finished with value: 0.6304377387318564 and parameters: {'max_depth': 8, 'learning_rate': 0.07443861624911809, 'n_estimators': 838, 'subsample': 0.9767112284974377, 'colsample_bytree': 0.7678307854027511, 'min_child_weight': 8, 'gamma': 0.9936223295349661, 'reg_alpha': 0.08352543871559089, 'reg_lambda': 2.862257894176924, 'max_delta_step': 9}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  92%|█████████▏| 184/200 [03:27<00:17,  1.08s/it]

[I 2025-11-10 18:16:09,876] Trial 184 pruned.
[I 2025-11-10 18:16:10,018] Trial 183 finished with value: 0.6303659281894577 and parameters: {'max_depth': 8, 'learning_rate': 0.03380219776937327, 'n_estimators': 508, 'subsample': 0.9771862765204693, 'colsample_bytree': 0.6704126220751827, 'min_child_weight': 8, 'gamma': 0.7354725755266229, 'reg_alpha': 0.015307347587003407, 'reg_lambda': 2.7398147958399703, 'max_delta_step': 10}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  92%|█████████▎| 185/200 [03:28<00:14,  1.06it/s]

[I 2025-11-10 18:16:10,622] Trial 180 finished with value: 0.6343934300993125 and parameters: {'max_depth': 8, 'learning_rate': 0.041193746709292864, 'n_estimators': 976, 'subsample': 0.9789390103263514, 'colsample_bytree': 0.7715535109964331, 'min_child_weight': 8, 'gamma': 0.8830056509192258, 'reg_alpha': 0.017513285880715837, 'reg_lambda': 2.2106421761633896, 'max_delta_step': 10}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  93%|█████████▎| 186/200 [03:29<00:12,  1.13it/s]

[I 2025-11-10 18:16:11,385] Trial 185 pruned.

Best trial: 71. Best value: 0.642406:  94%|█████████▎| 187/200 [03:30<00:11,  1.09it/s]

[I 2025-11-10 18:16:12,363] Trial 187 pruned.
[I 2025-11-10 18:16:12,451] Trial 186 pruned.

Best trial: 71. Best value: 0.642406:  94%|█████████▍| 189/200 [03:30<00:07,  1.51it/s]

[I 2025-11-10 18:16:13,105] Trial 188 pruned.

Best trial: 71. Best value: 0.642406:  95%|█████████▌| 190/200 [03:31<00:06,  1.56it/s]

[I 2025-11-10 18:16:13,684] Trial 189 pruned.

Best trial: 71. Best value: 0.642406:  96%|█████████▌| 191/200 [03:32<00:06,  1.49it/s]

[I 2025-11-10 18:16:14,439] Trial 190 pruned.

Best trial: 71. Best value: 0.642406:  96%|█████████▌| 192/200 [03:33<00:06,  1.28it/s]

[I 2025-11-10 18:16:15,509] Trial 194 pruned.

Best trial: 71. Best value: 0.642406:  96%|█████████▋| 193/200 [03:33<00:04,  1.44it/s]

[I 2025-11-10 18:16:15,976] Trial 191 finished with value: 0.6334598930481283 and parameters: {'max_depth': 8, 'learning_rate': 0.04221153859522662, 'n_estimators': 268, 'subsample': 0.9975549389172218, 'colsample_bytree': 0.8045974530108169, 'min_child_weight': 8, 'gamma': 0.8839534070742044, 'reg_alpha': 0.007773753001607444, 'reg_lambda': 1.0303379359837985, 'max_delta_step': 10}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  97%|█████████▋| 194/200 [03:34<00:04,  1.23it/s]

[I 2025-11-10 18:16:17,088] Trial 193 finished with value: 0.6258907563025209 and parameters: {'max_depth': 8, 'learning_rate': 0.04170811247726844, 'n_estimators': 267, 'subsample': 0.9825736475283567, 'colsample_bytree': 0.7586608957536145, 'min_child_weight': 8, 'gamma': 1.2837056547671775, 'reg_alpha': 0.02084268452889886, 'reg_lambda': 1.1615842639925876e-07, 'max_delta_step': 9}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  98%|█████████▊| 195/200 [03:35<00:03,  1.32it/s]

[I 2025-11-10 18:16:17,711] Trial 197 pruned.

Best trial: 71. Best value: 0.642406:  98%|█████████▊| 196/200 [03:35<00:02,  1.50it/s]

[I 2025-11-10 18:16:18,151] Trial 195 pruned.

Best trial: 71. Best value: 0.642406:  98%|█████████▊| 197/200 [03:36<00:02,  1.33it/s]

[I 2025-11-10 18:16:19,103] Trial 196 finished with value: 0.6276310160427807 and parameters: {'max_depth': 7, 'learning_rate': 0.040099830482055454, 'n_estimators': 201, 'subsample': 0.9979897431663854, 'colsample_bytree': 0.8116848715265539, 'min_child_weight': 8, 'gamma': 1.0813638471786131, 'reg_alpha': 0.012485352550035219, 'reg_lambda': 0.8988557146248218, 'max_delta_step': 10}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 71. Best value: 0.642406:  99%|█████████▉| 198/200 [03:38<00:02,  1.05s/it]

[I 2025-11-10 18:16:20,857] Trial 198 finished with value: 0.6373300229182582 and parameters: {'max_depth': 8, 'learning_rate': 0.04136791023338167, 'n_estimators': 210, 'subsample': 0.9947403923242961, 'colsample_bytree': 0.8206437703391023, 'min_child_weight': 8, 'gamma': 0.818605871779361, 'reg_alpha': 1.0474756099480092e-08, 'reg_lambda': 0.001855316083059651, 'max_delta_step': 10}. Best is trial 71 with value: 0.6424064171122995.

Best trial: 192. Best value: 0.647167: 100%|█████████▉| 199/200 [03:40<00:01,  1.31s/it]

[I 2025-11-10 18:16:22,788] Trial 192 finished with value: 0.6471673032849504 and parameters: {'max_depth': 8, 'learning_rate': 0.05210961037562223, 'n_estimators': 1150, 'subsample': 0.9663063136236829, 'colsample_bytree': 0.682113564171828, 'min_child_weight': 8, 'gamma': 0.8755193201188318, 'reg_alpha': 0.006765596214308256, 'reg_lambda': 1.2326035620420085e-07, 'max_delta_step': 9}. Best is trial 192 with value: 0.6471673032849504.

Best trial: 192. Best value: 0.647167: 100%|██████████| 200/200 [03:42<00:00,  1.11s/it]

[I 2025-11-10 18:16:24,627] Trial 199 finished with value: 0.6379786096256684 and parameters: {'max_depth': 8, 'learning_rate': 0.043812573693864966, 'n_estimators': 935, 'subsample': 0.9990144469867862, 'colsample_bytree': 0.7808330038429677, 'min_child_weight': 8, 'gamma': 0.8030634365132793, 'reg_alpha': 0.004129120440340793, 'reg_lambda': 0.4475721882672454, 'max_delta_step': 10}. Best is trial 192 with value: 0.6471673032849504.

[I 2025-11-10 18:16:26,166] A new study created in memory with name: 10_1_roc_auc
Best trial: 2. Best value: 0.5:   0%|          | 1/200 [00:02<07:03,  2.13s/it]

[I 2025-11-10 18:16:28,287] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.0817535724012558, 'n_estimators': 517, 'subsample': 0.7057964918605685, 'colsample_bytree': 0.5446644422831526, 'min_child_weight': 5, 'gamma': 3.2756641731444653, 'reg_alpha': 0.04992211460358807, 'reg_lambda': 4.392378416878932e-06, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 3. Best value: 0.520234:   1%|          | 2/200 [00:02<04:29,  1.36s/it]

[I 2025-11-10 18:16:29,109] Trial 3 finished with value: 0.5202339181286549 and parameters: {'max_depth': 3, 'learning_rate': 0.11782752323705317, 'n_estimators': 617, 'subsample': 0.9865422926399952, 'colsample_bytree': 0.5828281067449987, 'min_child_weight': 4, 'gamma': 2.333106834985099, 'reg_alpha': 0.15342169599885272, 'reg_lambda': 0.01646290938420686, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:   2%|▏         | 3/200 [00:03<03:24,  1.04s/it]

[I 2025-11-10 18:16:29,764] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01107557324938807, 'n_estimators': 328, 'subsample': 0.9233121907427131, 'colsample_bytree': 0.9086271768540164, 'min_child_weight': 9, 'gamma': 1.9191463530150705, 'reg_alpha': 7.328657218046303e-08, 'reg_lambda': 5.896865697482445e-08, 'max_delta_step': 8}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:   2%|▏         | 4/200 [00:05<05:03,  1.55s/it]

[I 2025-11-10 18:16:32,098] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.20872947583533338, 'n_estimators': 1445, 'subsample': 0.8840638840385778, 'colsample_bytree': 0.8232083828087138, 'min_child_weight': 8, 'gamma': 0.5380712115072478, 'reg_alpha': 1.7752957783393012e-07, 'reg_lambda': 4.5387744690455776e-05, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.
[I 2025-11-10 18:16:32,159] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.015148648451501422, 'n_estimators': 1446, 'subsample': 0.7498858963752433, 'colsample_bytree': 0.7917277872279702, 'min_child_weight': 9, 'gamma': 1.5617131995622968, 'reg_alpha': 3.62499457849177e-07, 'reg_lambda': 2.573390349054765e-06, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:   4%|▎         | 7/200 [00:07<02:26,  1.32it/s]

[I 2025-11-10 18:16:33,097] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.05345654796792611, 'n_estimators': 861, 'subsample': 0.6132338153765866, 'colsample_bytree': 0.5880767030410717, 'min_child_weight': 7, 'gamma': 2.551718914095989, 'reg_alpha': 1.8060030537250973, 'reg_lambda': 0.094281465751047, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.
[I 2025-11-10 18:16:33,241] Trial 5 finished with value: 0.4893957115009746 and parameters: {'max_depth': 6, 'learning_rate': 0.014707847854984354, 'n_estimators': 636, 'subsample': 0.5373548539951467, 'colsample_bytree': 0.9767933687486222, 'min_child_weight': 2, 'gamma': 3.6117506036932823, 'reg_alpha': 0.20499101973815928, 'reg_lambda': 1.6228116465372449e-06, 'max_delta_step': 3}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:   4%|▍         | 8/200 [00:09<03:37,  1.13s/it]

[I 2025-11-10 18:16:35,329] Trial 8 finished with value: 0.505438596491228 and parameters: {'max_depth': 4, 'learning_rate': 0.10984012055979747, 'n_estimators': 763, 'subsample': 0.9025674899002316, 'colsample_bytree': 0.6885466781619798, 'min_child_weight': 5, 'gamma': 3.4533519992053137, 'reg_alpha': 0.010081005897367426, 'reg_lambda': 0.004156653361155197, 'max_delta_step': 5}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:   4%|▍         | 9/200 [00:10<04:13,  1.33s/it]

[I 2025-11-10 18:16:37,142] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.10245630897639499, 'n_estimators': 963, 'subsample': 0.8247028952268907, 'colsample_bytree': 0.6588013309667402, 'min_child_weight': 7, 'gamma': 1.8467638802509638, 'reg_alpha': 0.10368456984387853, 'reg_lambda': 0.036827176169935215, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:   5%|▌         | 10/200 [00:11<03:44,  1.18s/it]

[I 2025-11-10 18:16:37,972] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.06292706914972082, 'n_estimators': 593, 'subsample': 0.5658522651073186, 'colsample_bytree': 0.9604996463994936, 'min_child_weight': 4, 'gamma': 2.355622747386464, 'reg_alpha': 2.6403185581467645e-08, 'reg_lambda': 2.8009137435141263, 'max_delta_step': 3}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:   6%|▌         | 11/200 [00:12<02:51,  1.10it/s]

[I 2025-11-10 18:16:38,214] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.019983604837685052, 'n_estimators': 1463, 'subsample': 0.9286847540436685, 'colsample_bytree': 0.8753682195569956, 'min_child_weight': 6, 'gamma': 3.9843462268472827, 'reg_alpha': 1.98456601514357, 'reg_lambda': 2.3470054633405537e-05, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:   6%|▌         | 12/200 [00:12<02:10,  1.44it/s]

[I 2025-11-10 18:16:38,402] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.15219305251285398, 'n_estimators': 1285, 'subsample': 0.7018452830935309, 'colsample_bytree': 0.7052869262846488, 'min_child_weight': 9, 'gamma': 0.0905904615327996, 'reg_alpha': 1.2260118588374342e-07, 'reg_lambda': 1.3567421255453479e-05, 'max_delta_step': 4}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:   7%|▋         | 14/200 [00:13<01:46,  1.75it/s]

[I 2025-11-10 18:16:39,292] Trial 14 pruned.
[I 2025-11-10 18:16:39,444] Trial 15 pruned.

Best trial: 3. Best value: 0.520234:   8%|▊         | 15/200 [00:13<01:44,  1.77it/s]

[I 2025-11-10 18:16:39,996] Trial 16 pruned.

Best trial: 3. Best value: 0.520234:   8%|▊         | 16/200 [00:14<01:26,  2.12it/s]

[I 2025-11-10 18:16:40,243] Trial 17 pruned.

Best trial: 3. Best value: 0.520234:   8%|▊         | 17/200 [00:14<01:13,  2.49it/s]

[I 2025-11-10 18:16:40,478] Trial 18 pruned.

Best trial: 3. Best value: 0.520234:   9%|▉         | 18/200 [00:14<01:11,  2.54it/s]

[I 2025-11-10 18:16:40,850] Trial 20 pruned.

Best trial: 3. Best value: 0.520234:  10%|▉         | 19/200 [00:15<01:20,  2.24it/s]

[I 2025-11-10 18:16:41,425] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.016955760289577494, 'n_estimators': 1072, 'subsample': 0.7120912095168858, 'colsample_bytree': 0.6759919624487263, 'min_child_weight': 7, 'gamma': 2.3034670584985, 'reg_alpha': 0.0013789221454403766, 'reg_lambda': 6.749184311381853e-05, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  10%|█         | 20/200 [00:15<01:11,  2.53it/s]

[I 2025-11-10 18:16:41,706] Trial 22 pruned.
[I 2025-11-10 18:16:41,765] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.12202611740792217, 'n_estimators': 327, 'subsample': 0.8144461503373794, 'colsample_bytree': 0.744913040717529, 'min_child_weight': 5, 'gamma': 1.0291183614346604, 'reg_alpha': 1.2941385423101265e-05, 'reg_lambda': 0.18016976192841958, 'max_delta_step': 7}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  11%|█         | 22/200 [00:18<02:21,  1.26it/s]

[I 2025-11-10 18:16:44,222] Trial 13 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03394199386059351, 'n_estimators': 1119, 'subsample': 0.9923566426578565, 'colsample_bytree': 0.5020088646234648, 'min_child_weight': 1, 'gamma': 4.713299711851907, 'reg_alpha': 5.100385341190788e-05, 'reg_lambda': 5.510015927784089, 'max_delta_step': 6}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  12%|█▏        | 23/200 [00:18<02:21,  1.25it/s]

[I 2025-11-10 18:16:45,037] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.08319774617215447, 'n_estimators': 822, 'subsample': 0.8881010787220642, 'colsample_bytree': 0.7448594154792717, 'min_child_weight': 6, 'gamma': 4.312263589511092, 'reg_alpha': 2.122702877600348e-05, 'reg_lambda': 0.6314287830176893, 'max_delta_step': 5}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  12%|█▏        | 24/200 [00:19<02:03,  1.43it/s]

[I 2025-11-10 18:16:45,459] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.029284841561502503, 'n_estimators': 1172, 'subsample': 0.7852631540869377, 'colsample_bytree': 0.5858566295363236, 'min_child_weight': 6, 'gamma': 2.412294112355511, 'reg_alpha': 0.016217307964662957, 'reg_lambda': 0.00026918999742921835, 'max_delta_step': 2}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  12%|█▎        | 25/200 [00:20<02:34,  1.14it/s]

[I 2025-11-10 18:16:46,823] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.189856533235071, 'n_estimators': 1238, 'subsample': 0.8856799929971338, 'colsample_bytree': 0.8252289617646735, 'min_child_weight': 10, 'gamma': 0.514018700866437, 'reg_alpha': 1.1819794815939982e-06, 'reg_lambda': 0.0002357533152427984, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  13%|█▎        | 26/200 [00:21<02:30,  1.15it/s]

[I 2025-11-10 18:16:47,657] Trial 27 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1878557246225446, 'n_estimators': 508, 'subsample': 0.8861842295149195, 'colsample_bytree': 0.8273650021488952, 'min_child_weight': 10, 'gamma': 0.018395005635378325, 'reg_alpha': 8.953155860928508, 'reg_lambda': 0.00022757423223703527, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  14%|█▎        | 27/200 [00:21<01:59,  1.45it/s]

[I 2025-11-10 18:16:47,897] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.17598583683494404, 'n_estimators': 845, 'subsample': 0.8836417545477823, 'colsample_bytree': 0.8304239071551822, 'min_child_weight': 10, 'gamma': 0.1753085043045446, 'reg_alpha': 1.8705589317607596e-06, 'reg_lambda': 0.00012035861344171583, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  14%|█▍        | 28/200 [00:23<03:15,  1.14s/it]

[I 2025-11-10 18:16:50,139] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.18913967888293298, 'n_estimators': 1198, 'subsample': 0.883775104281863, 'colsample_bytree': 0.8290154279375619, 'min_child_weight': 10, 'gamma': 0.035764870832773354, 'reg_alpha': 1.1838301001522041e-06, 'reg_lambda': 0.0003355610471936048, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  14%|█▍        | 29/200 [00:24<02:39,  1.07it/s]

[I 2025-11-10 18:16:50,577] Trial 28 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1851185470496856, 'n_estimators': 863, 'subsample': 0.9519593563671848, 'colsample_bytree': 0.8412178299060769, 'min_child_weight': 8, 'gamma': 0.013830012836377303, 'reg_alpha': 5.432947070085866, 'reg_lambda': 0.008923780441825778, 'max_delta_step': 4}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  15%|█▌        | 30/200 [00:25<02:37,  1.08it/s]

[I 2025-11-10 18:16:51,496] Trial 29 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1420795740186117, 'n_estimators': 886, 'subsample': 0.956376570408795, 'colsample_bytree': 0.7943743033748558, 'min_child_weight': 8, 'gamma': 3.317618144731782, 'reg_alpha': 0.008613165895637894, 'reg_lambda': 0.01042580489864317, 'max_delta_step': 4}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  16%|█▌        | 31/200 [00:25<02:19,  1.22it/s]

[I 2025-11-10 18:16:52,064] Trial 32 pruned.

Best trial: 3. Best value: 0.520234:  16%|█▌        | 32/200 [00:26<02:10,  1.29it/s]

[I 2025-11-10 18:16:52,723] Trial 33 pruned.

Best trial: 3. Best value: 0.520234:  16%|█▋        | 33/200 [00:27<02:15,  1.23it/s]

[I 2025-11-10 18:16:53,619] Trial 30 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.24313306140954904, 'n_estimators': 1358, 'subsample': 0.9446403941738564, 'colsample_bytree': 0.7771908831197851, 'min_child_weight': 8, 'gamma': 3.489984504267653, 'reg_alpha': 0.0076563801585132095, 'reg_lambda': 0.008931977141321951, 'max_delta_step': 4}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  17%|█▋        | 34/200 [00:29<03:34,  1.29s/it]

[I 2025-11-10 18:16:56,046] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.13780627564596573, 'n_estimators': 1347, 'subsample': 0.9536095708211012, 'colsample_bytree': 0.9089524940378211, 'min_child_weight': 8, 'gamma': 3.454747299440935, 'reg_alpha': 0.7536050290049344, 'reg_lambda': 0.008992291847297352, 'max_delta_step': 4}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  18%|█▊        | 35/200 [00:32<04:21,  1.58s/it]

[I 2025-11-10 18:16:58,309] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.0732377802118237, 'n_estimators': 1454, 'subsample': 0.7309267085587124, 'colsample_bytree': 0.8913094182001664, 'min_child_weight': 8, 'gamma': 1.4684071744335965, 'reg_alpha': 2.095636489482188e-07, 'reg_lambda': 2.4402766162034646e-06, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  18%|█▊        | 36/200 [00:32<03:31,  1.29s/it]

[I 2025-11-10 18:16:58,917] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.09150785553333657, 'n_estimators': 1469, 'subsample': 0.6626592875388079, 'colsample_bytree': 0.9060045294701218, 'min_child_weight': 9, 'gamma': 0.5074901275026565, 'reg_alpha': 3.8431381221254004e-07, 'reg_lambda': 1.3407597073686944e-06, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  18%|█▊        | 37/200 [00:33<03:09,  1.16s/it]

[I 2025-11-10 18:16:59,780] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.08252533435582213, 'n_estimators': 1453, 'subsample': 0.662152999730747, 'colsample_bytree': 0.9058810772167817, 'min_child_weight': 9, 'gamma': 0.5232621975928375, 'reg_alpha': 1.3855996251967513e-07, 'reg_lambda': 1.0157409124895505e-08, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  19%|█▉        | 38/200 [00:35<03:21,  1.24s/it]

[I 2025-11-10 18:17:01,207] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.010359199410937072, 'n_estimators': 703, 'subsample': 0.6666439779474636, 'colsample_bytree': 0.5525800414680502, 'min_child_weight': 9, 'gamma': 0.6450800492410393, 'reg_alpha': 2.840766509458598e-08, 'reg_lambda': 3.954434786856733e-08, 'max_delta_step': 10}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  20%|█▉        | 39/200 [00:35<02:52,  1.07s/it]

[I 2025-11-10 18:17:01,885] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.011766493904009414, 'n_estimators': 717, 'subsample': 0.6540758207383924, 'colsample_bytree': 0.5472231675779127, 'min_child_weight': 6, 'gamma': 1.9905720852523614, 'reg_alpha': 1.3799337540525373e-08, 'reg_lambda': 1.0843313770495335e-05, 'max_delta_step': 10}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  20%|██        | 40/200 [00:36<02:16,  1.18it/s]

[I 2025-11-10 18:17:02,217] Trial 37 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.08283390075092613, 'n_estimators': 1500, 'subsample': 0.6732856827063559, 'colsample_bytree': 0.7128816326161198, 'min_child_weight': 9, 'gamma': 0.7153734697624219, 'reg_alpha': 1.2186163015271678e-07, 'reg_lambda': 3.403342376454045e-06, 'max_delta_step': 8}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  20%|██        | 41/200 [00:36<01:46,  1.49it/s]

[I 2025-11-10 18:17:02,467] Trial 42 pruned.

Best trial: 3. Best value: 0.520234:  21%|██        | 42/200 [00:36<01:31,  1.73it/s]

[I 2025-11-10 18:17:02,825] Trial 40 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0233144197547954, 'n_estimators': 720, 'subsample': 0.8565117586514909, 'colsample_bytree': 0.5462471205882242, 'min_child_weight': 6, 'gamma': 2.029815030651608, 'reg_alpha': 0.047523950769382275, 'reg_lambda': 1.0349342875113786e-05, 'max_delta_step': 10}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  22%|██▏       | 43/200 [00:37<01:46,  1.48it/s]

[I 2025-11-10 18:17:03,731] Trial 41 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.012622384343854374, 'n_estimators': 552, 'subsample': 0.9154341461200299, 'colsample_bytree': 0.7256181740436907, 'min_child_weight': 6, 'gamma': 2.009835837291084, 'reg_alpha': 0.00011701024762517474, 'reg_lambda': 2.0346227372619635e-05, 'max_delta_step': 8}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  22%|██▏       | 44/200 [00:38<02:04,  1.25it/s]

[I 2025-11-10 18:17:04,811] Trial 43 finished with value: 0.5155555555555555 and parameters: {'max_depth': 3, 'learning_rate': 0.057355878842681465, 'n_estimators': 566, 'subsample': 0.8631621347242432, 'colsample_bytree': 0.6129138157401062, 'min_child_weight': 5, 'gamma': 2.672350676823357, 'reg_alpha': 3.634880346417668e-06, 'reg_lambda': 3.622525136990742e-05, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  22%|██▎       | 45/200 [00:38<01:37,  1.59it/s]

[I 2025-11-10 18:17:05,042] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.058085984315799644, 'n_estimators': 472, 'subsample': 0.7611174766355518, 'colsample_bytree': 0.6411216629244628, 'min_child_weight': 5, 'gamma': 3.1601250975380593, 'reg_alpha': 0.041587637277650025, 'reg_lambda': 2.8250929056040696e-05, 'max_delta_step': 7}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  23%|██▎       | 46/200 [00:39<01:26,  1.78it/s]

[I 2025-11-10 18:17:05,452] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.05573235198765557, 'n_estimators': 623, 'subsample': 0.5081627921448683, 'colsample_bytree': 0.8578475675636921, 'min_child_weight': 5, 'gamma': 2.0869870926098217, 'reg_alpha': 0.044870069167874095, 'reg_lambda': 4.0869218532092586e-05, 'max_delta_step': 7}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  24%|██▎       | 47/200 [00:39<01:19,  1.91it/s]

[I 2025-11-10 18:17:05,884] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.055676186130919576, 'n_estimators': 456, 'subsample': 0.7574107825100505, 'colsample_bytree': 0.6760692801705394, 'min_child_weight': 5, 'gamma': 3.01514551685457, 'reg_alpha': 0.11164616590892545, 'reg_lambda': 5.489968110482698e-05, 'max_delta_step': 7}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  24%|██▍       | 48/200 [00:40<01:47,  1.42it/s]

[I 2025-11-10 18:17:07,011] Trial 47 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.06120778246149613, 'n_estimators': 468, 'subsample': 0.8061162912505692, 'colsample_bytree': 0.6204054764123751, 'min_child_weight': 5, 'gamma': 3.1311248173387445, 'reg_alpha': 5.741400423689429e-06, 'reg_lambda': 3.925158040372253e-05, 'max_delta_step': 3}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  24%|██▍       | 49/200 [00:41<02:01,  1.24it/s]

[I 2025-11-10 18:17:08,046] Trial 48 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.0433180819739767, 'n_estimators': 674, 'subsample': 0.7933464452271022, 'colsample_bytree': 0.6672199128038369, 'min_child_weight': 7, 'gamma': 2.635435525139135, 'reg_alpha': 4.887522783106597e-06, 'reg_lambda': 4.69571948729761e-05, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  25%|██▌       | 50/200 [00:42<01:38,  1.53it/s]

[I 2025-11-10 18:17:08,347] Trial 49 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07045006796313955, 'n_estimators': 655, 'subsample': 0.9072508740617965, 'colsample_bytree': 0.6748928605933157, 'min_child_weight': 7, 'gamma': 2.6551112920601097, 'reg_alpha': 4.8021975335894e-06, 'reg_lambda': 0.0006871335052682757, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  26%|██▌       | 51/200 [00:42<01:42,  1.45it/s]

[I 2025-11-10 18:17:09,120] Trial 53 pruned.
[I 2025-11-10 18:17:09,137] Trial 52 pruned.

Best trial: 3. Best value: 0.520234:  26%|██▋       | 53/200 [00:43<01:14,  1.97it/s]

[I 2025-11-10 18:17:09,714] Trial 55 pruned.

Best trial: 3. Best value: 0.520234:  28%|██▊       | 55/200 [00:43<00:53,  2.69it/s]

[I 2025-11-10 18:17:09,971] Trial 50 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.044225174918061515, 'n_estimators': 942, 'subsample': 0.7957599235931271, 'colsample_bytree': 0.6207739325971967, 'min_child_weight': 7, 'gamma': 2.624367660495473, 'reg_alpha': 5.127937940794675e-06, 'reg_lambda': 0.0009997534860860453, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.
[I 2025-11-10 18:17:10,135] Trial 56 pruned.

Best trial: 3. Best value: 0.520234:  28%|██▊       | 56/200 [00:44<00:46,  3.08it/s]

[I 2025-11-10 18:17:10,333] Trial 54 pruned.

Best trial: 3. Best value: 0.520234:  28%|██▊       | 57/200 [00:44<00:43,  3.31it/s]

[I 2025-11-10 18:17:10,577] Trial 58 pruned.
[I 2025-11-10 18:17:10,599] Trial 51 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04593401027366469, 'n_estimators': 793, 'subsample': 0.9105449465995739, 'colsample_bytree': 0.6174209907795942, 'min_child_weight': 7, 'gamma': 2.6144941385893383, 'reg_alpha': 5.404299720945998e-07, 'reg_lambda': 0.0008558916808029228, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  30%|██▉       | 59/200 [00:45<00:48,  2.91it/s]

[I 2025-11-10 18:17:11,365] Trial 60 pruned.

Best trial: 3. Best value: 0.520234:  30%|███       | 60/200 [00:47<01:38,  1.43it/s]

[I 2025-11-10 18:17:13,196] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07347829392075604, 'n_estimators': 777, 'subsample': 0.5790727659829907, 'colsample_bytree': 0.5193030635820344, 'min_child_weight': 5, 'gamma': 2.8478014388694883, 'reg_alpha': 0.3690046151500101, 'reg_lambda': 5.11913549637861e-06, 'max_delta_step': 5}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  30%|███       | 61/200 [00:47<01:32,  1.51it/s]

[I 2025-11-10 18:17:13,753] Trial 59 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.15116184285616174, 'n_estimators': 775, 'subsample': 0.8316529307857397, 'colsample_bytree': 0.8043585344016647, 'min_child_weight': 5, 'gamma': 1.251335184425738, 'reg_alpha': 0.003485618985424709, 'reg_lambda': 0.0036392651343228623, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  31%|███       | 62/200 [00:48<01:43,  1.33it/s]

[I 2025-11-10 18:17:14,742] Trial 61 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.11532171494605112, 'n_estimators': 1024, 'subsample': 0.8319242324648448, 'colsample_bytree': 0.5177190323012822, 'min_child_weight': 5, 'gamma': 4.3562910849580065, 'reg_alpha': 0.002159747892252006, 'reg_lambda': 0.00011553926563006287, 'max_delta_step': 2}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  32%|███▏      | 63/200 [00:49<02:07,  1.07it/s]

[I 2025-11-10 18:17:16,141] Trial 65 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01633694763301288, 'n_estimators': 294, 'subsample': 0.9772665147426778, 'colsample_bytree': 0.9702517379251945, 'min_child_weight': 9, 'gamma': 2.421343355571368, 'reg_alpha': 5.358061684116199e-08, 'reg_lambda': 1.1118326551436194e-07, 'max_delta_step': 8}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  32%|███▏      | 64/200 [00:50<01:40,  1.35it/s]

[I 2025-11-10 18:17:16,404] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01536365093447069, 'n_estimators': 599, 'subsample': 0.856768800456618, 'colsample_bytree': 0.9750121167208039, 'min_child_weight': 10, 'gamma': 2.4200230965697913, 'reg_alpha': 1.1448205866523632e-08, 'reg_lambda': 1.8754752143068882e-07, 'max_delta_step': 8}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  32%|███▎      | 65/200 [00:50<01:29,  1.51it/s]

[I 2025-11-10 18:17:16,872] Trial 66 pruned.
[I 2025-11-10 18:17:16,916] Trial 62 finished with value: 0.49444444444444446 and parameters: {'max_depth': 6, 'learning_rate': 0.025036675972275563, 'n_estimators': 1279, 'subsample': 0.8658624472373818, 'colsample_bytree': 0.8033770477909856, 'min_child_weight': 5, 'gamma': 3.641955592316783, 'reg_alpha': 0.003173075769417627, 'reg_lambda': 0.0001353549834121198, 'max_delta_step': 5}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  34%|███▎      | 67/200 [00:51<01:13,  1.80it/s]

[I 2025-11-10 18:17:17,718] Trial 63 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2249697037636984, 'n_estimators': 1026, 'subsample': 0.8598577768827504, 'colsample_bytree': 0.8088104586443744, 'min_child_weight': 6, 'gamma': 1.2982983771394787, 'reg_alpha': 1.6509674928287064, 'reg_lambda': 0.2163226854606271, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  34%|███▍      | 68/200 [00:51<01:02,  2.13it/s]

[I 2025-11-10 18:17:17,929] Trial 67 pruned.
[I 2025-11-10 18:17:18,027] Trial 68 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.035565533726093564, 'n_estimators': 212, 'subsample': 0.9343087279354398, 'colsample_bytree': 0.85350766172719, 'min_child_weight': 8, 'gamma': 3.6945074541590035, 'reg_alpha': 1.0789413675442328e-07, 'reg_lambda': 0.00010644928919368321, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  36%|███▌      | 71/200 [00:52<00:51,  2.52it/s]

[I 2025-11-10 18:17:18,867] Trial 70 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.03590030987174253, 'n_estimators': 224, 'subsample': 0.9337661017835839, 'colsample_bytree': 0.6939986695946075, 'min_child_weight': 8, 'gamma': 3.3506500543124824, 'reg_alpha': 1.4443161269139692e-06, 'reg_lambda': 2.1250418317867963e-08, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.
[I 2025-11-10 18:17:19,015] Trial 69 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.036094679989531385, 'n_estimators': 414, 'subsample': 0.929490298806797, 'colsample_bytree': 0.9336473065402539, 'min_child_weight': 6, 'gamma': 0.2724346516191799, 'reg_alpha': 2.0600009873445653, 'reg_lambda': 0.45217332046867054, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  36%|███▌      | 72/200 [00:53<01:04,  2.00it/s]

[I 2025-11-10 18:17:19,832] Trial 71 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.010042620814707538, 'n_estimators': 393, 'subsample': 0.9663460910501814, 'colsample_bytree': 0.6957287442897716, 'min_child_weight': 9, 'gamma': 1.64888369591699, 'reg_alpha': 1.1263027353225313e-06, 'reg_lambda': 0.023475320895832312, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  36%|███▋      | 73/200 [00:54<01:23,  1.52it/s]

[I 2025-11-10 18:17:20,938] Trial 73 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.08869506122964901, 'n_estimators': 422, 'subsample': 0.9672774341062929, 'colsample_bytree': 0.8791466929198924, 'min_child_weight': 9, 'gamma': 0.23372837531215634, 'reg_alpha': 2.145535482886396e-07, 'reg_lambda': 0.05610946033990114, 'max_delta_step': 8}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  37%|███▋      | 74/200 [00:55<01:14,  1.70it/s]

[I 2025-11-10 18:17:21,346] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.01341950136162886, 'n_estimators': 528, 'subsample': 0.6131505410509513, 'colsample_bytree': 0.5797131680441496, 'min_child_weight': 9, 'gamma': 2.1984900219406365, 'reg_alpha': 0.2421469051420494, 'reg_lambda': 0.051859736758430745, 'max_delta_step': 10}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  38%|███▊      | 75/200 [00:56<01:46,  1.17it/s]

[I 2025-11-10 18:17:22,884] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.06630211517633636, 'n_estimators': 352, 'subsample': 0.9904878494437171, 'colsample_bytree': 0.5403657764717094, 'min_child_weight': 8, 'gamma': 1.863615183173467, 'reg_alpha': 0.013830505672715274, 'reg_lambda': 1.0881159483749805e-06, 'max_delta_step': 8}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  38%|███▊      | 76/200 [00:58<02:12,  1.07s/it]

[I 2025-11-10 18:17:24,483] Trial 72 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.08635520092273474, 'n_estimators': 1408, 'subsample': 0.9650576316848121, 'colsample_bytree': 0.8794874581974993, 'min_child_weight': 9, 'gamma': 0.8247635438164278, 'reg_alpha': 1.1207792880331615e-06, 'reg_lambda': 0.021055332588381326, 'max_delta_step': 8}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  38%|███▊      | 77/200 [00:59<02:13,  1.08s/it]

[I 2025-11-10 18:17:25,606] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.013293173710635075, 'n_estimators': 1417, 'subsample': 0.6363671084667973, 'colsample_bytree': 0.5694244362989775, 'min_child_weight': 8, 'gamma': 2.185257567414945, 'reg_alpha': 0.22679295740539368, 'reg_lambda': 0.07031329716480422, 'max_delta_step': 10}. Best is trial 3 with value: 0.5202339181286549.
[I 2025-11-10 18:17:25,638] Trial 76 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.09569756513329565, 'n_estimators': 1119, 'subsample': 0.8984315975327853, 'colsample_bytree': 0.5807494930401408, 'min_child_weight': 8, 'gamma': 2.2257815825988376, 'reg_alpha': 0.008830216932335436, 'reg_lambda': 0.1435281470813888, 'max_delta_step': 10}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  40%|███▉      | 79/200 [01:00<01:40,  1.20it/s]

[I 2025-11-10 18:17:26,665] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.12125437021202061, 'n_estimators': 497, 'subsample': 0.8955158608942511, 'colsample_bytree': 0.5676186849320979, 'min_child_weight': 6, 'gamma': 3.020411569650896, 'reg_alpha': 0.07562441292662637, 'reg_lambda': 6.025436792585404e-07, 'max_delta_step': 7}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  40%|████      | 80/200 [01:01<01:51,  1.08it/s]

[I 2025-11-10 18:17:27,882] Trial 81 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.16796167460982236, 'n_estimators': 510, 'subsample': 0.7413740321332469, 'colsample_bytree': 0.7697794509770791, 'min_child_weight': 7, 'gamma': 2.499490634485531, 'reg_alpha': 0.0726249214960057, 'reg_lambda': 1.4244913259136783e-05, 'max_delta_step': 7}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  40%|████      | 81/200 [01:02<01:45,  1.13it/s]

[I 2025-11-10 18:17:28,654] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.11641806491688927, 'n_estimators': 1418, 'subsample': 0.739573240998341, 'colsample_bytree': 0.5341467956384376, 'min_child_weight': 6, 'gamma': 0.9569775816873671, 'reg_alpha': 0.06495055996976888, 'reg_lambda': 0.1741492844875083, 'max_delta_step': 7}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  41%|████      | 82/200 [01:03<01:44,  1.12it/s]

[I 2025-11-10 18:17:29,548] Trial 82 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.16515800956377572, 'n_estimators': 678, 'subsample': 0.7710276683231092, 'colsample_bytree': 0.7511094267582586, 'min_child_weight': 10, 'gamma': 2.494457227132912, 'reg_alpha': 2.46853755427773e-06, 'reg_lambda': 1.8567356117430124e-05, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  42%|████▏     | 83/200 [01:04<01:40,  1.17it/s]

[I 2025-11-10 18:17:30,319] Trial 80 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.16861219522205503, 'n_estimators': 1103, 'subsample': 0.7355483784299569, 'colsample_bytree': 0.7576084703018804, 'min_child_weight': 6, 'gamma': 1.893761390349126, 'reg_alpha': 0.08931993057140745, 'reg_lambda': 1.2400177479843635, 'max_delta_step': 7}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  42%|████▏     | 84/200 [01:04<01:31,  1.27it/s]

[I 2025-11-10 18:17:30,933] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0510499661919445, 'n_estimators': 670, 'subsample': 0.7786926735080073, 'colsample_bytree': 0.9950930617960787, 'min_child_weight': 10, 'gamma': 3.509928203065555, 'reg_alpha': 4.821538294880795, 'reg_lambda': 0.0004644171856817954, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  42%|████▎     | 85/200 [01:06<01:45,  1.09it/s]

[I 2025-11-10 18:17:32,171] Trial 87 pruned.

Best trial: 3. Best value: 0.520234:  43%|████▎     | 86/200 [01:08<02:53,  1.52s/it]

[I 2025-11-10 18:17:35,148] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.018138688799035366, 'n_estimators': 1495, 'subsample': 0.5399440330649998, 'colsample_bytree': 0.9196119034022038, 'min_child_weight': 7, 'gamma': 4.802139485992747, 'reg_alpha': 6.938773969161569, 'reg_lambda': 1.7523713931772815, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  44%|████▎     | 87/200 [01:09<02:18,  1.23s/it]

[I 2025-11-10 18:17:35,684] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.018214922323438593, 'n_estimators': 1308, 'subsample': 0.6833222739291895, 'colsample_bytree': 0.5950703001172897, 'min_child_weight': 7, 'gamma': 4.809273364837294, 'reg_alpha': 7.080409456467945, 'reg_lambda': 0.0004244899609408785, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  44%|████▍     | 88/200 [01:09<01:50,  1.01it/s]

[I 2025-11-10 18:17:36,097] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.018747389709166718, 'n_estimators': 1485, 'subsample': 0.874546393901349, 'colsample_bytree': 0.8566512453883752, 'min_child_weight': 7, 'gamma': 4.114096006346228, 'reg_alpha': 4.954565305433182, 'reg_lambda': 0.001956957885308703, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  44%|████▍     | 89/200 [01:10<01:41,  1.09it/s]

[I 2025-11-10 18:17:36,837] Trial 90 pruned.

Best trial: 3. Best value: 0.520234:  45%|████▌     | 90/200 [01:11<01:24,  1.30it/s]

[I 2025-11-10 18:17:37,271] Trial 91 pruned.

Best trial: 3. Best value: 0.520234:  46%|████▌     | 91/200 [01:11<01:07,  1.61it/s]

[I 2025-11-10 18:17:37,540] Trial 88 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.011077109812485341, 'n_estimators': 1222, 'subsample': 0.6923170480088637, 'colsample_bytree': 0.85517260365725, 'min_child_weight': 7, 'gamma': 3.8715288067775573, 'reg_alpha': 2.895748309599657, 'reg_lambda': 0.0021450033372835296, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  46%|████▌     | 92/200 [01:13<01:53,  1.05s/it]

[I 2025-11-10 18:17:39,601] Trial 92 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.29610342408319945, 'n_estimators': 628, 'subsample': 0.8418975604374777, 'colsample_bytree': 0.739318577900675, 'min_child_weight': 5, 'gamma': 3.1707826292775274, 'reg_alpha': 3.2972531360227597, 'reg_lambda': 1.9785672500769025e-06, 'max_delta_step': 3}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  46%|████▋     | 93/200 [01:14<01:50,  1.03s/it]

[I 2025-11-10 18:17:40,585] Trial 89 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.13417629840236592, 'n_estimators': 1200, 'subsample': 0.9969639104874626, 'colsample_bytree': 0.851269364173285, 'min_child_weight': 7, 'gamma': 3.8166981390554953, 'reg_alpha': 3.3843046953032125, 'reg_lambda': 2.620581656009686e-05, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  47%|████▋     | 94/200 [01:16<02:34,  1.46s/it]

[I 2025-11-10 18:17:43,048] Trial 93 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.02822518943354696, 'n_estimators': 1382, 'subsample': 0.9446820324528415, 'colsample_bytree': 0.5564832018565978, 'min_child_weight': 5, 'gamma': 3.824377907146119, 'reg_alpha': 3.1181343221465787, 'reg_lambda': 1.8780061506593945e-06, 'max_delta_step': 3}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  48%|████▊     | 95/200 [01:17<01:59,  1.14s/it]

[I 2025-11-10 18:17:43,436] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.20772828540924765, 'n_estimators': 1410, 'subsample': 0.7174343418684963, 'colsample_bytree': 0.5030669613993886, 'min_child_weight': 5, 'gamma': 0.4164344841972924, 'reg_alpha': 3.055931593198938e-08, 'reg_lambda': 1.7464262435773547e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  48%|████▊     | 96/200 [01:19<02:30,  1.44s/it]

[I 2025-11-10 18:17:45,591] Trial 95 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.20920850640834182, 'n_estimators': 1433, 'subsample': 0.7131955230052047, 'colsample_bytree': 0.7170769658289652, 'min_child_weight': 9, 'gamma': 0.15180364247539413, 'reg_alpha': 7.489925296397857e-08, 'reg_lambda': 4.7422465778389175e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  48%|████▊     | 97/200 [01:20<02:13,  1.30s/it]

[I 2025-11-10 18:17:46,556] Trial 96 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.20704465087504334, 'n_estimators': 1430, 'subsample': 0.6431660287016895, 'colsample_bytree': 0.7908446230072893, 'min_child_weight': 9, 'gamma': 4.575409647322672, 'reg_alpha': 1.0272534791153108e-07, 'reg_lambda': 6.754123631917127e-05, 'max_delta_step': 4}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  49%|████▉     | 98/200 [01:20<01:48,  1.06s/it]

[I 2025-11-10 18:17:47,059] Trial 98 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.02126742680854964, 'n_estimators': 893, 'subsample': 0.8943484463476937, 'colsample_bytree': 0.6575177923065696, 'min_child_weight': 9, 'gamma': 0.10706343885084901, 'reg_alpha': 8.251044125244496e-08, 'reg_lambda': 0.00015943101499581408, 'max_delta_step': 4}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  50%|████▉     | 99/200 [01:22<02:12,  1.31s/it]

[I 2025-11-10 18:17:48,959] Trial 100 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.27225029376000875, 'n_estimators': 558, 'subsample': 0.9034821573009107, 'colsample_bytree': 0.8166053861099837, 'min_child_weight': 8, 'gamma': 2.380035777425628, 'reg_alpha': 1.0558052263650246, 'reg_lambda': 0.00016847811176578354, 'max_delta_step': 6}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  50%|█████     | 101/200 [01:23<01:12,  1.37it/s]

[I 2025-11-10 18:17:49,176] Trial 99 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.14881694712726354, 'n_estimators': 832, 'subsample': 0.902945337093243, 'colsample_bytree': 0.8201589628868947, 'min_child_weight': 8, 'gamma': 4.497844631389009, 'reg_alpha': 0.9800048011011441, 'reg_lambda': 6.984168014687353e-05, 'max_delta_step': 6}. Best is trial 3 with value: 0.5202339181286549.
[I 2025-11-10 18:17:49,318] Trial 97 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.22292418764718525, 'n_estimators': 1462, 'subsample': 0.9022229681236528, 'colsample_bytree': 0.8202181816220759, 'min_child_weight': 9, 'gamma': 4.505321088594073, 'reg_alpha': 2.4648278364273682e-08, 'reg_lambda': 3.7059823779865406e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  51%|█████     | 102/200 [01:24<01:29,  1.10it/s]

[I 2025-11-10 18:17:50,646] Trial 103 pruned.

Best trial: 3. Best value: 0.520234:  52%|█████▏    | 103/200 [01:24<01:07,  1.44it/s]

[I 2025-11-10 18:17:50,840] Trial 101 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07665536810833734, 'n_estimators': 819, 'subsample': 0.9168801531290058, 'colsample_bytree': 0.8925549005383075, 'min_child_weight': 6, 'gamma': 1.4405924576291202, 'reg_alpha': 2.800317218878504e-05, 'reg_lambda': 1.2707004914768029e-05, 'max_delta_step': 6}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  52%|█████▏    | 104/200 [01:26<01:38,  1.03s/it]

[I 2025-11-10 18:17:52,650] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07506792818707737, 'n_estimators': 826, 'subsample': 0.9162072956027034, 'colsample_bytree': 0.6859079006204115, 'min_child_weight': 6, 'gamma': 1.4928528645830845, 'reg_alpha': 0.44097792204162023, 'reg_lambda': 6.838330994746819e-05, 'max_delta_step': 5}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  52%|█████▎    | 105/200 [01:27<01:32,  1.03it/s]

[I 2025-11-10 18:17:53,481] Trial 104 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.0995830636700019, 'n_estimators': 954, 'subsample': 0.8123235809144398, 'colsample_bytree': 0.6822435635467637, 'min_child_weight': 6, 'gamma': 1.3554473800277294, 'reg_alpha': 0.3974120982752535, 'reg_lambda': 0.03342736701157209, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  53%|█████▎    | 106/200 [01:28<01:32,  1.02it/s]

[I 2025-11-10 18:17:54,499] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.1008568478846624, 'n_estimators': 872, 'subsample': 0.9181842078468802, 'colsample_bytree': 0.6128878495224219, 'min_child_weight': 6, 'gamma': 2.0935715705027667, 'reg_alpha': 0.13403402205678394, 'reg_lambda': 0.014745881996410052, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  54%|█████▎    | 107/200 [01:28<01:21,  1.14it/s]

[I 2025-11-10 18:17:55,123] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.1013186704859141, 'n_estimators': 973, 'subsample': 0.8105941228035622, 'colsample_bytree': 0.6113494775928805, 'min_child_weight': 6, 'gamma': 1.9216608906485235, 'reg_alpha': 0.16412950600679566, 'reg_lambda': 0.03368342520823535, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  54%|█████▍    | 108/200 [01:30<01:47,  1.17s/it]

[I 2025-11-10 18:17:56,991] Trial 107 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09410410087987528, 'n_estimators': 989, 'subsample': 0.7961799006354672, 'colsample_bytree': 0.6426426880720411, 'min_child_weight': 8, 'gamma': 2.0945691427569475, 'reg_alpha': 0.14862466469864796, 'reg_lambda': 0.035527329112269544, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  55%|█████▍    | 109/200 [01:31<01:27,  1.04it/s]

[I 2025-11-10 18:17:57,449] Trial 111 pruned.

Best trial: 3. Best value: 0.520234:  55%|█████▌    | 110/200 [01:31<01:07,  1.33it/s]

[I 2025-11-10 18:17:57,712] Trial 109 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.11065913584428724, 'n_estimators': 729, 'subsample': 0.7681518047981601, 'colsample_bytree': 0.7057102099861821, 'min_child_weight': 8, 'gamma': 2.954666828615254, 'reg_alpha': 2.9695535836965685e-07, 'reg_lambda': 0.00622750243015617, 'max_delta_step': 8}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  56%|█████▌    | 111/200 [01:33<01:32,  1.04s/it]

[I 2025-11-10 18:17:59,436] Trial 108 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.10981343010852734, 'n_estimators': 1379, 'subsample': 0.7486225286299177, 'colsample_bytree': 0.6570948872677929, 'min_child_weight': 8, 'gamma': 1.7061733384143296, 'reg_alpha': 0.014811412420872241, 'reg_lambda': 0.014802519505146664, 'max_delta_step': 8}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  56%|█████▌    | 112/200 [01:34<01:31,  1.04s/it]

[I 2025-11-10 18:18:00,479] Trial 114 pruned.

Best trial: 3. Best value: 0.520234:  56%|█████▋    | 113/200 [01:34<01:16,  1.13it/s]

[I 2025-11-10 18:18:00,993] Trial 110 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01422055505270019, 'n_estimators': 1376, 'subsample': 0.7504682964000295, 'colsample_bytree': 0.6425752770939623, 'min_child_weight': 8, 'gamma': 2.955188508437679, 'reg_alpha': 7.317878487064147e-07, 'reg_lambda': 0.0972184897508085, 'max_delta_step': 8}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  57%|█████▋    | 114/200 [01:36<01:38,  1.15s/it]

[I 2025-11-10 18:18:02,749] Trial 112 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.12370430456899419, 'n_estimators': 1270, 'subsample': 0.679774061215224, 'colsample_bytree': 0.6298587884696217, 'min_child_weight': 10, 'gamma': 1.1357213669793165, 'reg_alpha': 0.019422871239458163, 'reg_lambda': 0.005715737552775639, 'max_delta_step': 8}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  57%|█████▊    | 115/200 [01:36<01:15,  1.12it/s]

[I 2025-11-10 18:18:03,051] Trial 115 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06314902701274631, 'n_estimators': 565, 'subsample': 0.5603799850714816, 'colsample_bytree': 0.8701519175830996, 'min_child_weight': 4, 'gamma': 2.348198987593793, 'reg_alpha': 1.9647780282063865e-08, 'reg_lambda': 6.223767020860444e-08, 'max_delta_step': 3}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  58%|█████▊    | 116/200 [01:37<01:02,  1.33it/s]

[I 2025-11-10 18:18:03,469] Trial 113 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.013992880229167214, 'n_estimators': 1386, 'subsample': 0.8505194469377221, 'colsample_bytree': 0.6608737317552359, 'min_child_weight': 10, 'gamma': 2.2901394767220618, 'reg_alpha': 0.018056313706592365, 'reg_lambda': 7.507882334825576e-08, 'max_delta_step': 8}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  58%|█████▊    | 117/200 [01:38<01:07,  1.24it/s]

[I 2025-11-10 18:18:04,412] Trial 116 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.05768343986651919, 'n_estimators': 741, 'subsample': 0.5739407472670451, 'colsample_bytree': 0.8673537580767189, 'min_child_weight': 4, 'gamma': 2.335265963588519, 'reg_alpha': 1.700534409500371e-08, 'reg_lambda': 5.272719963029497, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  59%|█████▉    | 118/200 [01:39<01:12,  1.14it/s]

[I 2025-11-10 18:18:05,465] Trial 117 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.06293483992885468, 'n_estimators': 570, 'subsample': 0.5398767905460549, 'colsample_bytree': 0.9535170353081223, 'min_child_weight': 4, 'gamma': 2.588383133800183, 'reg_alpha': 5.462831194481245e-08, 'reg_lambda': 4.6795325318608635e-05, 'max_delta_step': 3}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  60%|█████▉    | 119/200 [01:39<00:56,  1.43it/s]

[I 2025-11-10 18:18:05,742] Trial 120 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.012086978580110371, 'n_estimators': 259, 'subsample': 0.5153890172387611, 'colsample_bytree': 0.9656116274534366, 'min_child_weight': 4, 'gamma': 3.5753741730818698, 'reg_alpha': 0.0005891004509266191, 'reg_lambda': 0.3017628816706525, 'max_delta_step': 10}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  60%|██████    | 120/200 [01:40<00:55,  1.44it/s]

[I 2025-11-10 18:18:06,425] Trial 118 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.05185443846968458, 'n_estimators': 740, 'subsample': 0.5055662659333413, 'colsample_bytree': 0.7927856805527592, 'min_child_weight': 4, 'gamma': 2.751296225214072, 'reg_alpha': 4.785770891076017e-08, 'reg_lambda': 0.2770663989886632, 'max_delta_step': 5}. Best is trial 3 with value: 0.5202339181286549.
[I 2025-11-10 18:18:06,444] Trial 122 pruned.

Best trial: 3. Best value: 0.520234:  61%|██████    | 122/200 [01:40<00:36,  2.12it/s]

[I 2025-11-10 18:18:06,855] Trial 119 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.05180094815334847, 'n_estimators': 697, 'subsample': 0.5054161637232086, 'colsample_bytree': 0.9583358036528575, 'min_child_weight': 4, 'gamma': 0.3478792327210527, 'reg_alpha': 0.00029800103030197387, 'reg_lambda': 3.8256058179154935e-05, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  62%|██████▏   | 123/200 [01:43<01:21,  1.06s/it]

[I 2025-11-10 18:18:09,695] Trial 123 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.0668968309078843, 'n_estimators': 689, 'subsample': 0.6105662244337599, 'colsample_bytree': 0.9937546026404822, 'min_child_weight': 5, 'gamma': 0.3331747652637562, 'reg_alpha': 0.03506688127995794, 'reg_lambda': 0.0002847010704833787, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  62%|██████▏   | 124/200 [01:44<01:20,  1.06s/it]

[I 2025-11-10 18:18:10,745] Trial 126 pruned.

Best trial: 3. Best value: 0.520234:  62%|██████▎   | 125/200 [01:44<01:02,  1.21it/s]

[I 2025-11-10 18:18:10,958] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01659502130947359, 'n_estimators': 1051, 'subsample': 0.7283204887235452, 'colsample_bytree': 0.6707798213734274, 'min_child_weight': 7, 'gamma': 2.5318740983510772, 'reg_alpha': 0.00676274921746036, 'reg_lambda': 9.908455238884663, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  64%|██████▎   | 127/200 [01:45<00:40,  1.80it/s]

[I 2025-11-10 18:18:11,403] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.016957219687500875, 'n_estimators': 1082, 'subsample': 0.6166153261433606, 'colsample_bytree': 0.6698832665264316, 'min_child_weight': 7, 'gamma': 2.588828551387556, 'reg_alpha': 0.005358615789007113, 'reg_lambda': 9.88705005855491e-05, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.
[I 2025-11-10 18:18:11,549] Trial 121 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.05204687582237481, 'n_estimators': 1340, 'subsample': 0.5100626421855441, 'colsample_bytree': 0.7834562848977566, 'min_child_weight': 5, 'gamma': 2.7170786732065366, 'reg_alpha': 0.0005840144823049519, 'reg_lambda': 1.4134739998079299e-08, 'max_delta_step': 10}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  64%|██████▍   | 128/200 [01:47<01:11,  1.01it/s]

[I 2025-11-10 18:18:13,597] Trial 127 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.14024312516616225, 'n_estimators': 654, 'subsample': 0.7242951218489444, 'colsample_bytree': 0.6730632961113411, 'min_child_weight': 7, 'gamma': 2.5422114853402022, 'reg_alpha': 0.0022050296765974376, 'reg_lambda': 1.0878975917029123e-08, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  64%|██████▍   | 129/200 [01:47<00:57,  1.23it/s]

[I 2025-11-10 18:18:13,994] Trial 129 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.020845318440780917, 'n_estimators': 609, 'subsample': 0.705838805653519, 'colsample_bytree': 0.6965378091970899, 'min_child_weight': 9, 'gamma': 3.2479815626562143, 'reg_alpha': 0.001093536447205773, 'reg_lambda': 0.8593425565302958, 'max_delta_step': 2}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  66%|██████▌   | 131/200 [01:48<00:36,  1.87it/s]

[I 2025-11-10 18:18:14,378] Trial 130 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.020746720951644704, 'n_estimators': 657, 'subsample': 0.5918794479003977, 'colsample_bytree': 0.7281287508507723, 'min_child_weight': 7, 'gamma': 4.974929557328671, 'reg_alpha': 0.050535771497126236, 'reg_lambda': 0.7157656058960854, 'max_delta_step': 2}. Best is trial 3 with value: 0.5202339181286549.
[I 2025-11-10 18:18:14,549] Trial 131 pruned.

Best trial: 3. Best value: 0.520234:  66%|██████▌   | 132/200 [01:49<00:56,  1.21it/s]

[I 2025-11-10 18:18:16,054] Trial 134 pruned.

Best trial: 3. Best value: 0.520234:  66%|██████▋   | 133/200 [01:50<00:43,  1.54it/s]

[I 2025-11-10 18:18:16,300] Trial 132 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.08299329420393095, 'n_estimators': 541, 'subsample': 0.8228556251917806, 'colsample_bytree': 0.8971243446246772, 'min_child_weight': 7, 'gamma': 1.6506759348517055, 'reg_alpha': 0.000128880309116994, 'reg_lambda': 3.6526548873371526e-05, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  67%|██████▋   | 134/200 [01:50<00:34,  1.93it/s]

[I 2025-11-10 18:18:16,502] Trial 128 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.021022737121178376, 'n_estimators': 1335, 'subsample': 0.6295064513172278, 'colsample_bytree': 0.7017553839260205, 'min_child_weight': 7, 'gamma': 3.354447098081809, 'reg_alpha': 0.0010362361771227462, 'reg_lambda': 0.0013491775602446382, 'max_delta_step': 2}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  68%|██████▊   | 135/200 [01:51<00:44,  1.45it/s]

[I 2025-11-10 18:18:17,601] Trial 137 pruned.

Best trial: 3. Best value: 0.520234:  68%|██████▊   | 136/200 [01:52<00:43,  1.49it/s]

[I 2025-11-10 18:18:18,231] Trial 133 finished with value: 0.5054970760233918 and parameters: {'max_depth': 6, 'learning_rate': 0.08398452204312543, 'n_estimators': 490, 'subsample': 0.9871865978303314, 'colsample_bytree': 0.8933667320940659, 'min_child_weight': 1, 'gamma': 3.409770493733367, 'reg_alpha': 0.6086049722381504, 'reg_lambda': 3.6156122959129367e-06, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  69%|██████▉   | 138/200 [01:54<00:51,  1.20it/s]

[I 2025-11-10 18:18:20,429] Trial 136 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.027011058688311773, 'n_estimators': 1036, 'subsample': 0.9750611270867308, 'colsample_bytree': 0.5147803878990431, 'min_child_weight': 9, 'gamma': 4.169113353030286, 'reg_alpha': 1.9452415952111118e-07, 'reg_lambda': 4.2826763656143365, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.
[I 2025-11-10 18:18:20,577] Trial 139 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09055803206783611, 'n_estimators': 495, 'subsample': 0.9792010132510772, 'colsample_bytree': 0.9213551179000792, 'min_child_weight': 9, 'gamma': 4.091208520867342, 'reg_alpha': 1.330532561403199, 'reg_lambda': 2.9574454933018262e-06, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  70%|██████▉   | 139/200 [01:54<00:44,  1.37it/s]

[I 2025-11-10 18:18:21,070] Trial 135 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.02562451596087305, 'n_estimators': 1121, 'subsample': 0.9816330226522973, 'colsample_bytree': 0.8937636362188583, 'min_child_weight': 6, 'gamma': 4.623204188386315, 'reg_alpha': 1.001588129441227e-08, 'reg_lambda': 1.7205407164256198e-05, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  70%|███████   | 140/200 [01:55<00:40,  1.47it/s]

[I 2025-11-10 18:18:21,632] Trial 142 pruned.

Best trial: 3. Best value: 0.520234:  70%|███████   | 141/200 [01:55<00:33,  1.77it/s]

[I 2025-11-10 18:18:21,925] Trial 138 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.040175689594931736, 'n_estimators': 1004, 'subsample': 0.9381064575576445, 'colsample_bytree': 0.5837120469894911, 'min_child_weight': 9, 'gamma': 4.3283463743863475, 'reg_alpha': 7.606068732658028e-07, 'reg_lambda': 1.7603821092696995e-05, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  71%|███████   | 142/200 [01:56<00:30,  1.88it/s]

[I 2025-11-10 18:18:22,375] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.12412534657533676, 'n_estimators': 368, 'subsample': 0.9505265740750751, 'colsample_bytree': 0.5818316081286437, 'min_child_weight': 6, 'gamma': 3.720569469038659, 'reg_alpha': 0.709644895786374, 'reg_lambda': 6.30993311130744e-06, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  72%|███████▏  | 143/200 [01:56<00:25,  2.27it/s]

[I 2025-11-10 18:18:22,604] Trial 144 pruned.

Best trial: 3. Best value: 0.520234:  72%|███████▏  | 144/200 [01:56<00:23,  2.39it/s]

[I 2025-11-10 18:18:22,973] Trial 140 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09236584865173329, 'n_estimators': 510, 'subsample': 0.9575551496973338, 'colsample_bytree': 0.9068919422575589, 'min_child_weight': 9, 'gamma': 3.4884868144851544, 'reg_alpha': 0.30998731866343393, 'reg_lambda': 6.838711754284187e-06, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  72%|███████▎  | 145/200 [01:57<00:23,  2.36it/s]

[I 2025-11-10 18:18:23,407] Trial 145 pruned.

Best trial: 3. Best value: 0.520234:  73%|███████▎  | 146/200 [01:58<00:30,  1.75it/s]

[I 2025-11-10 18:18:24,323] Trial 147 pruned.
[I 2025-11-10 18:18:24,346] Trial 146 pruned.

Best trial: 3. Best value: 0.520234:  74%|███████▍  | 148/200 [01:58<00:20,  2.54it/s]

[I 2025-11-10 18:18:24,698] Trial 148 pruned.

Best trial: 3. Best value: 0.520234:  74%|███████▍  | 149/200 [01:58<00:19,  2.67it/s]

[I 2025-11-10 18:18:25,012] Trial 150 pruned.

Best trial: 3. Best value: 0.520234:  75%|███████▌  | 150/200 [01:59<00:17,  2.94it/s]

[I 2025-11-10 18:18:25,256] Trial 149 pruned.

Best trial: 3. Best value: 0.520234:  76%|███████▌  | 151/200 [01:59<00:15,  3.15it/s]

[I 2025-11-10 18:18:25,515] Trial 151 pruned.
[I 2025-11-10 18:18:25,596] Trial 143 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.125200647912667, 'n_estimators': 854, 'subsample': 0.6556188430672927, 'colsample_bytree': 0.8406825876935239, 'min_child_weight': 5, 'gamma': 3.4373567567585708, 'reg_alpha': 7.73081752923206e-07, 'reg_lambda': 8.221570096066962e-06, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  76%|███████▋  | 153/200 [01:59<00:13,  3.47it/s]

[I 2025-11-10 18:18:26,016] Trial 152 pruned.

Best trial: 3. Best value: 0.520234:  77%|███████▋  | 154/200 [02:00<00:21,  2.14it/s]

[I 2025-11-10 18:18:27,056] Trial 154 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.14646919067736955, 'n_estimators': 325, 'subsample': 0.6956850891155097, 'colsample_bytree': 0.7122399036969166, 'min_child_weight': 5, 'gamma': 0.8370361914264878, 'reg_alpha': 1.6221866840983118e-05, 'reg_lambda': 0.07224667147560122, 'max_delta_step': 7}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  78%|███████▊  | 155/200 [02:01<00:17,  2.51it/s]

[I 2025-11-10 18:18:27,251] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.059781195253362694, 'n_estimators': 342, 'subsample': 0.6942428813672024, 'colsample_bytree': 0.7433661749265285, 'min_child_weight': 5, 'gamma': 1.1628576517570588, 'reg_alpha': 2.0102378120075204, 'reg_lambda': 0.06768069750543641, 'max_delta_step': 7}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  78%|███████▊  | 157/200 [02:02<00:20,  2.06it/s]

[I 2025-11-10 18:18:28,490] Trial 157 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.010959218722061334, 'n_estimators': 286, 'subsample': 0.6869182627549106, 'colsample_bytree': 0.7486263754397041, 'min_child_weight': 5, 'gamma': 1.2084863392230232, 'reg_alpha': 4.776695442046051e-05, 'reg_lambda': 0.1398776899697545, 'max_delta_step': 7}. Best is trial 3 with value: 0.5202339181286549.
[I 2025-11-10 18:18:28,615] Trial 158 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.11270252784967684, 'n_estimators': 277, 'subsample': 0.8522379948351354, 'colsample_bytree': 0.5930015196083436, 'min_child_weight': 6, 'gamma': 1.9544002036937587, 'reg_alpha': 4.789354745175996e-05, 'reg_lambda': 1.5916286700835471, 'max_delta_step': 8}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  79%|███████▉  | 158/200 [02:03<00:21,  1.93it/s]

[I 2025-11-10 18:18:29,212] Trial 153 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05929192817509625, 'n_estimators': 867, 'subsample': 0.6895779081487456, 'colsample_bytree': 0.6491949351945138, 'min_child_weight': 8, 'gamma': 1.9551803754746158, 'reg_alpha': 9.616773481222458, 'reg_lambda': 8.276344340084517e-05, 'max_delta_step': 5}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  80%|███████▉  | 159/200 [02:03<00:17,  2.31it/s]

[I 2025-11-10 18:18:29,435] Trial 159 pruned.

Best trial: 3. Best value: 0.520234:  80%|████████  | 160/200 [02:03<00:15,  2.55it/s]

[I 2025-11-10 18:18:29,731] Trial 156 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.15603308230558396, 'n_estimators': 797, 'subsample': 0.6909772190141826, 'colsample_bytree': 0.5009071019599178, 'min_child_weight': 5, 'gamma': 0.8708939981598101, 'reg_alpha': 1.1494624693468173e-05, 'reg_lambda': 1.9849286433068472, 'max_delta_step': 7}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  80%|████████  | 161/200 [02:05<00:28,  1.37it/s]

[I 2025-11-10 18:18:31,272] Trial 162 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.15770221824595237, 'n_estimators': 383, 'subsample': 0.7125785199978488, 'colsample_bytree': 0.5689505145303009, 'min_child_weight': 8, 'gamma': 0.9894996506456081, 'reg_alpha': 7.323409169865899e-08, 'reg_lambda': 2.5768079142767407e-05, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  81%|████████  | 162/200 [02:05<00:22,  1.70it/s]

[I 2025-11-10 18:18:31,524] Trial 163 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.12950241769357496, 'n_estimators': 380, 'subsample': 0.8668830097690674, 'colsample_bytree': 0.5713485094608458, 'min_child_weight': 8, 'gamma': 1.0850721803089056, 'reg_alpha': 9.78315960413005e-08, 'reg_lambda': 0.011193295943289435, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  82%|████████▏ | 163/200 [02:08<00:49,  1.35s/it]

[I 2025-11-10 18:18:34,669] Trial 161 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04704177812710415, 'n_estimators': 1283, 'subsample': 0.7923124216818334, 'colsample_bytree': 0.5655538099078006, 'min_child_weight': 8, 'gamma': 0.9525555381198373, 'reg_alpha': 2.6718785326572206e-05, 'reg_lambda': 3.18885237767237e-08, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  82%|████████▏ | 164/200 [02:09<00:39,  1.11s/it]

[I 2025-11-10 18:18:35,207] Trial 160 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.06921669839821314, 'n_estimators': 1442, 'subsample': 0.775722279931377, 'colsample_bytree': 0.8037129592369359, 'min_child_weight': 8, 'gamma': 0.4804276990661275, 'reg_alpha': 2.3441528511567374e-05, 'reg_lambda': 0.010417988917010809, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  83%|████████▎ | 166/200 [02:10<00:29,  1.15it/s]

[I 2025-11-10 18:18:36,526] Trial 164 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1357854248863246, 'n_estimators': 1158, 'subsample': 0.8237989228251859, 'colsample_bytree': 0.8071326669401336, 'min_child_weight': 6, 'gamma': 0.49095498106461666, 'reg_alpha': 0.039336766963956604, 'reg_lambda': 0.01277255111139329, 'max_delta_step': 3}. Best is trial 3 with value: 0.5202339181286549.
[I 2025-11-10 18:18:36,695] Trial 165 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.10194644426687818, 'n_estimators': 1157, 'subsample': 0.8024994003181564, 'colsample_bytree': 0.7703534548736928, 'min_child_weight': 6, 'gamma': 1.7802336456069585, 'reg_alpha': 0.025734152186067574, 'reg_lambda': 0.000266569168105794, 'max_delta_step': 3}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  83%|████████▎ | 166/200 [02:10<00:29,  1.15it/s]

[I 2025-11-10 18:18:36,784] Trial 167 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1044638708292647, 'n_estimators': 320, 'subsample': 0.7604060268334089, 'colsample_bytree': 0.6232412888726361, 'min_child_weight': 6, 'gamma': 1.8223686588674193, 'reg_alpha': 0.05999322723711415, 'reg_lambda': 0.4390811234768491, 'max_delta_step': 2}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  84%|████████▍ | 168/200 [02:11<00:23,  1.38it/s]

[I 2025-11-10 18:18:37,800] Trial 168 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.022985396293258232, 'n_estimators': 235, 'subsample': 0.801107134065888, 'colsample_bytree': 0.5523451591164187, 'min_child_weight': 6, 'gamma': 2.8586305187382077, 'reg_alpha': 0.06035282008609333, 'reg_lambda': 0.0001670584629196717, 'max_delta_step': 2}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  84%|████████▍ | 169/200 [02:13<00:31,  1.02s/it]

[I 2025-11-10 18:18:39,706] Trial 166 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.023616274826003446, 'n_estimators': 1160, 'subsample': 0.8133622229401393, 'colsample_bytree': 0.6146819638249212, 'min_child_weight': 6, 'gamma': 0.4413761927488055, 'reg_alpha': 0.024176828781268183, 'reg_lambda': 0.00021602747474709486, 'max_delta_step': 3}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  86%|████████▌ | 171/200 [02:16<00:29,  1.03s/it]

[I 2025-11-10 18:18:42,035] Trial 169 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.022252917817388838, 'n_estimators': 1249, 'subsample': 0.8331892953166447, 'colsample_bytree': 0.5502550664458811, 'min_child_weight': 7, 'gamma': 2.694507061978856, 'reg_alpha': 0.05855903802029499, 'reg_lambda': 0.00017388369481928214, 'max_delta_step': 2}. Best is trial 3 with value: 0.5202339181286549.
[I 2025-11-10 18:18:42,189] Trial 170 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.02233278561471345, 'n_estimators': 1186, 'subsample': 0.8939291422856743, 'colsample_bytree': 0.9132816048394699, 'min_child_weight': 7, 'gamma': 2.818206561322241, 'reg_alpha': 3.153833476280223e-08, 'reg_lambda': 4.5060384155628144e-05, 'max_delta_step': 2}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  86%|████████▌ | 172/200 [02:16<00:23,  1.19it/s]

[I 2025-11-10 18:18:42,524] Trial 171 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.012858513024442401, 'n_estimators': 1102, 'subsample': 0.8193168355473511, 'colsample_bytree': 0.6095897152455665, 'min_child_weight': 7, 'gamma': 2.7050931072486732, 'reg_alpha': 3.779832717136986e-07, 'reg_lambda': 0.0006182274924550677, 'max_delta_step': 3}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  86%|████████▋ | 173/200 [02:18<00:32,  1.19s/it]

[I 2025-11-10 18:18:44,612] Trial 172 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.019307597030908112, 'n_estimators': 1107, 'subsample': 0.7407196801821351, 'colsample_bytree': 0.9857197089659234, 'min_child_weight': 7, 'gamma': 2.381066477458078, 'reg_alpha': 0.0037931606874461433, 'reg_lambda': 4.625793235907696e-05, 'max_delta_step': 1}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  87%|████████▋ | 174/200 [02:19<00:32,  1.23s/it]

[I 2025-11-10 18:18:45,934] Trial 174 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01333788578204391, 'n_estimators': 894, 'subsample': 0.5239040818968859, 'colsample_bytree': 0.7573874245621683, 'min_child_weight': 5, 'gamma': 2.308364479640396, 'reg_alpha': 3.5071586762464704e-07, 'reg_lambda': 0.0004957740680300807, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  88%|████████▊ | 175/200 [02:20<00:25,  1.03s/it]

[I 2025-11-10 18:18:46,468] Trial 175 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07770699910204308, 'n_estimators': 898, 'subsample': 0.784642923753549, 'colsample_bytree': 0.9851713123707333, 'min_child_weight': 6, 'gamma': 4.283907264241599, 'reg_alpha': 8.179026408806808e-05, 'reg_lambda': 6.894436176594097, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  88%|████████▊ | 176/200 [02:20<00:20,  1.14it/s]

[I 2025-11-10 18:18:46,975] Trial 173 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.019101077734122677, 'n_estimators': 1103, 'subsample': 0.78616177210202, 'colsample_bytree': 0.91348322183999, 'min_child_weight': 7, 'gamma': 2.311975684263842, 'reg_alpha': 3.6682511870425663e-07, 'reg_lambda': 0.0004360687074216421, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  88%|████████▊ | 177/200 [02:22<00:26,  1.14s/it]

[I 2025-11-10 18:18:48,756] Trial 176 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04348320129799619, 'n_estimators': 975, 'subsample': 0.5238527579410172, 'colsample_bytree': 0.7338809191767127, 'min_child_weight': 5, 'gamma': 4.267685744471362, 'reg_alpha': 1.990516784452123e-06, 'reg_lambda': 7.124884461538125, 'max_delta_step': 9}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  89%|████████▉ | 178/200 [02:23<00:23,  1.09s/it]

[I 2025-11-10 18:18:49,709] Trial 179 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05491183261525808, 'n_estimators': 586, 'subsample': 0.5594997880925225, 'colsample_bytree': 0.9327745324149805, 'min_child_weight': 9, 'gamma': 4.426636015520919, 'reg_alpha': 8.070747325386987e-06, 'reg_lambda': 2.6338255316118695, 'max_delta_step': 5}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  90%|████████▉ | 179/200 [02:24<00:19,  1.07it/s]

[I 2025-11-10 18:18:50,291] Trial 177 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07754268418900773, 'n_estimators': 974, 'subsample': 0.8848930981543596, 'colsample_bytree': 0.7374197797400763, 'min_child_weight': 9, 'gamma': 2.1734963663965443, 'reg_alpha': 7.763967316587399e-06, 'reg_lambda': 0.18160039368208858, 'max_delta_step': 5}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  90%|█████████ | 180/200 [02:26<00:29,  1.49s/it]

[I 2025-11-10 18:18:53,066] Trial 178 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.06551979184842831, 'n_estimators': 1500, 'subsample': 0.6755567072486631, 'colsample_bytree': 0.7354642431076792, 'min_child_weight': 9, 'gamma': 4.37747824202591, 'reg_alpha': 8.381326235721028e-06, 'reg_lambda': 0.16446170455190756, 'max_delta_step': 5}. Best is trial 3 with value: 0.5202339181286549.
[I 2025-11-10 18:18:53,156] Trial 181 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.09686771287349324, 'n_estimators': 763, 'subsample': 0.880427233933643, 'colsample_bytree': 0.7115457916944135, 'min_child_weight': 10, 'gamma': 2.1979207490000183, 'reg_alpha': 1.4637886881068945e-07, 'reg_lambda': 0.21396392969460926, 'max_delta_step': 6}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  91%|█████████ | 182/200 [02:27<00:16,  1.11it/s]

[I 2025-11-10 18:18:53,485] Trial 180 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05475808810010854, 'n_estimators': 1073, 'subsample': 0.8759138669168341, 'colsample_bytree': 0.7056827932727735, 'min_child_weight': 9, 'gamma': 4.737637173275736, 'reg_alpha': 6.965992294524283e-06, 'reg_lambda': 0.19671498610556332, 'max_delta_step': 5}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  92%|█████████▏| 184/200 [02:30<00:17,  1.12s/it]

[I 2025-11-10 18:18:56,657] Trial 183 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.11762045833919399, 'n_estimators': 814, 'subsample': 0.8592623760804425, 'colsample_bytree': 0.5885990544644888, 'min_child_weight': 6, 'gamma': 1.3212283330517254, 'reg_alpha': 2.523340508635887, 'reg_lambda': 0.04749330638183652, 'max_delta_step': 6}. Best is trial 3 with value: 0.5202339181286549.
[I 2025-11-10 18:18:56,826] Trial 182 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.0964990278476564, 'n_estimators': 1496, 'subsample': 0.9699382236999177, 'colsample_bytree': 0.7078434443893251, 'min_child_weight': 6, 'gamma': 2.0783131797012695, 'reg_alpha': 1.567338461645729e-07, 'reg_lambda': 0.04077225139368452, 'max_delta_step': 8}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  92%|█████████▎| 185/200 [02:31<00:16,  1.10s/it]

[I 2025-11-10 18:18:57,849] Trial 186 pruned.

Best trial: 3. Best value: 0.520234:  93%|█████████▎| 186/200 [02:32<00:13,  1.05it/s]

[I 2025-11-10 18:18:58,428] Trial 188 pruned.

Best trial: 3. Best value: 0.520234:  94%|█████████▍| 188/200 [02:32<00:07,  1.68it/s]

[I 2025-11-10 18:18:58,791] Trial 185 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.17353982152076727, 'n_estimators': 1224, 'subsample': 0.8956589993136457, 'colsample_bytree': 0.5885545935821376, 'min_child_weight': 10, 'gamma': 0.5968489211858757, 'reg_alpha': 1.0308771533550298e-06, 'reg_lambda': 0.025575148838647206, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.
[I 2025-11-10 18:18:58,928] Trial 184 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.11671693745218752, 'n_estimators': 1241, 'subsample': 0.8966366094683383, 'colsample_bytree': 0.8274087091446076, 'min_child_weight': 10, 'gamma': 0.7475595783289416, 'reg_alpha': 0.01217873176914176, 'reg_lambda': 0.036516040633229004, 'max_delta_step': 0}. Best is trial 3 with value: 0.5202339181286549.

Best trial: 3. Best value: 0.520234:  94%|█████████▍| 189/200 [02:33<00:08,  1.36it/s]

[I 2025-11-10 18:18:59,992] Trial 191 pruned.

Best trial: 187. Best value: 0.558285:  95%|█████████▌| 190/200 [02:36<00:11,  1.16s/it]

[I 2025-11-10 18:19:02,186] Trial 187 finished with value: 0.5582846003898634 and parameters: {'max_depth': 9, 'learning_rate': 0.19478699850594147, 'n_estimators': 1216, 'subsample': 0.9163364634534232, 'colsample_bytree': 0.5753557433945917, 'min_child_weight': 5, 'gamma': 0.755264638882523, 'reg_alpha': 1.1450038359521987e-06, 'reg_lambda': 1.2346799286658073e-05, 'max_delta_step': 0}. Best is trial 187 with value: 0.5582846003898634.

Best trial: 187. Best value: 0.558285:  96%|█████████▌| 191/200 [02:36<00:08,  1.04it/s]

[I 2025-11-10 18:19:02,673] Trial 193 pruned.

Best trial: 187. Best value: 0.558285:  96%|█████████▌| 192/200 [02:37<00:07,  1.02it/s]

[I 2025-11-10 18:19:03,703] Trial 194 pruned.

Best trial: 187. Best value: 0.558285:  96%|█████████▋| 193/200 [02:37<00:05,  1.29it/s]

[I 2025-11-10 18:19:03,983] Trial 189 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.08457646817355129, 'n_estimators': 1222, 'subsample': 0.9871444893643646, 'colsample_bytree': 0.824667341975826, 'min_child_weight': 10, 'gamma': 3.9961739498326767, 'reg_alpha': 1.1707667063011679e-06, 'reg_lambda': 0.10293473362181241, 'max_delta_step': 0}. Best is trial 187 with value: 0.5582846003898634.

Best trial: 187. Best value: 0.558285:  97%|█████████▋| 194/200 [02:38<00:04,  1.21it/s]

[I 2025-11-10 18:19:04,928] Trial 190 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.23808792865285755, 'n_estimators': 1407, 'subsample': 0.8429394652939122, 'colsample_bytree': 0.8288328055036951, 'min_child_weight': 10, 'gamma': 0.2004527003983419, 'reg_alpha': 1.4766437196452433e-06, 'reg_lambda': 1.2003680838392772, 'max_delta_step': 1}. Best is trial 187 with value: 0.5582846003898634.

Best trial: 187. Best value: 0.558285:  98%|█████████▊| 195/200 [02:39<00:03,  1.51it/s]

[I 2025-11-10 18:19:05,210] Trial 196 pruned.

Best trial: 187. Best value: 0.558285:  98%|█████████▊| 196/200 [02:39<00:02,  1.76it/s]

[I 2025-11-10 18:19:05,556] Trial 192 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.18323526060184497, 'n_estimators': 1307, 'subsample': 0.9146629690900415, 'colsample_bytree': 0.5253063299586538, 'min_child_weight': 10, 'gamma': 0.2656435390675566, 'reg_alpha': 1.2067126246058397, 'reg_lambda': 6.602167792126286e-05, 'max_delta_step': 1}. Best is trial 187 with value: 0.5582846003898634.

Best trial: 187. Best value: 0.558285:  98%|█████████▊| 197/200 [02:41<00:03,  1.15s/it]

[I 2025-11-10 18:19:08,083] Trial 198 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.1835770290104797, 'n_estimators': 634, 'subsample': 0.8695429427328125, 'colsample_bytree': 0.7750921438722553, 'min_child_weight': 6, 'gamma': 0.6462271707009375, 'reg_alpha': 6.394470620989456e-07, 'reg_lambda': 5.717461070879054e-05, 'max_delta_step': 0}. Best is trial 187 with value: 0.5582846003898634.

Best trial: 187. Best value: 0.558285:  99%|█████████▉| 198/200 [02:42<00:02,  1.12s/it]

[I 2025-11-10 18:19:09,111] Trial 195 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.24783810278340038, 'n_estimators': 1295, 'subsample': 0.7646455105916075, 'colsample_bytree': 0.7798147323351808, 'min_child_weight': 5, 'gamma': 0.6428097622871796, 'reg_alpha': 1.3827474432792934, 'reg_lambda': 1.728755287027526e-05, 'max_delta_step': 1}. Best is trial 187 with value: 0.5582846003898634.

Best trial: 187. Best value: 0.558285: 100%|██████████| 200/200 [02:43<00:00,  1.22it/s]

[I 2025-11-10 18:19:09,686] Trial 197 finished with value: 0.5244444444444445 and parameters: {'max_depth': 5, 'learning_rate': 0.21725793483394978, 'n_estimators': 1295, 'subsample': 0.8718134275065883, 'colsample_bytree': 0.6598996611108505, 'min_child_weight': 5, 'gamma': 3.269137639391582, 'reg_alpha': 2.3896065890092285e-07, 'reg_lambda': 1.2570120553088094e-05, 'max_delta_step': 0}. Best is trial 187 with value: 0.5582846003898634.
[I 2025-11-10 18:19:09,810] Trial 199 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.26027734822687887, 'n_estimators': 1260, 'subsample': 0.8710376397615003, 'colsample_bytree': 0.5774289312819046, 'min_child_weight': 6, 'gamma': 2.4331025896236853, 'reg_alpha': 5.77528309523557e-07, 'reg_lambda': 0.0032798730132427103, 'max_delta_step': 0}. Best is trial 187 with value: 0.5582846003898634.

[I 2025-11-10 18:19:11,140] A new study created in memory with name: 15_1_roc_auc
Best trial: 2. Best value: 0.5:   0%|          | 1/200 [00:01<04:38,  1.40s/it]

[I 2025-11-10 18:19:12,535] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.17163192640515604, 'n_estimators': 333, 'subsample': 0.5197781726860784, 'colsample_bytree': 0.5720287326993183, 'min_child_weight': 8, 'gamma': 0.6315593424572963, 'reg_alpha': 0.5534094997569207, 'reg_lambda': 1.985571356839013e-05, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   1%|          | 2/200 [00:03<06:06,  1.85s/it]

[I 2025-11-10 18:19:14,703] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.0190123002579175, 'n_estimators': 875, 'subsample': 0.7500894693604923, 'colsample_bytree': 0.8626739125837593, 'min_child_weight': 7, 'gamma': 3.0725991786042446, 'reg_alpha': 0.8314097600036813, 'reg_lambda': 0.5686766348750099, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▏         | 3/200 [00:03<03:35,  1.10s/it]

[I 2025-11-10 18:19:14,892] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.15092909633848464, 'n_estimators': 970, 'subsample': 0.7845164912228204, 'colsample_bytree': 0.6347292335519726, 'min_child_weight': 8, 'gamma': 3.171631119804366, 'reg_alpha': 0.016162078393580883, 'reg_lambda': 5.909709497635142e-07, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▏         | 4/200 [00:04<03:40,  1.12s/it]

[I 2025-11-10 18:19:16,063] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10487082940188426, 'n_estimators': 340, 'subsample': 0.553910513956569, 'colsample_bytree': 0.6404518325080011, 'min_child_weight': 4, 'gamma': 3.0050974696206363, 'reg_alpha': 3.935010740068728, 'reg_lambda': 1.3267229516455685, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   2%|▎         | 5/200 [00:06<04:13,  1.30s/it]

[I 2025-11-10 18:19:17,678] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.05009265514899039, 'n_estimators': 1278, 'subsample': 0.5988184437420464, 'colsample_bytree': 0.9790982053269558, 'min_child_weight': 10, 'gamma': 4.068139847925654, 'reg_alpha': 6.251478290387525e-07, 'reg_lambda': 2.9706636113368997e-05, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   3%|▎         | 6/200 [00:07<03:46,  1.17s/it]

[I 2025-11-10 18:19:18,584] Trial 3 finished with value: 0.42448343079922024 and parameters: {'max_depth': 9, 'learning_rate': 0.09020308547866995, 'n_estimators': 1204, 'subsample': 0.9526529088788731, 'colsample_bytree': 0.6957939192645148, 'min_child_weight': 1, 'gamma': 4.471854508987882, 'reg_alpha': 0.0002458600052416976, 'reg_lambda': 2.224089515784279e-08, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   4%|▍         | 8/200 [00:08<02:12,  1.45it/s]

[I 2025-11-10 18:19:19,108] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.012159698936943818, 'n_estimators': 355, 'subsample': 0.5459366707549649, 'colsample_bytree': 0.6084841212463354, 'min_child_weight': 9, 'gamma': 2.0026752154579404, 'reg_alpha': 1.4442642836846845e-06, 'reg_lambda': 1.2127855487021127e-07, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:19:19,224] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.11573519691502004, 'n_estimators': 784, 'subsample': 0.9654284348976983, 'colsample_bytree': 0.9075664953378416, 'min_child_weight': 8, 'gamma': 3.0613331242942, 'reg_alpha': 1.8752116488822403e-06, 'reg_lambda': 0.1374174090599879, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:19:19,256] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.010296977733302562, 'n_estimators': 1120, 'subsample': 0.8914683500585827, 'colsample_bytree': 0.8131510288453134, 'min_child_weight': 9, 'gamma': 2.7200965875174674, 'reg_alpha': 1.2944486855605792, 'reg_lambda': 0.726325173215798, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   5%|▌         | 10/200 [00:10<02:58,  1.07it/s]

[I 2025-11-10 18:19:21,653] Trial 12 finished with value: 0.4828947368421052 and parameters: {'max_depth': 6, 'learning_rate': 0.22654860999589532, 'n_estimators': 585, 'subsample': 0.899631201279903, 'colsample_bytree': 0.6413580285220892, 'min_child_weight': 5, 'gamma': 3.2427679478842606, 'reg_alpha': 2.4020295969585596e-08, 'reg_lambda': 1.0204364071995386e-05, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   6%|▌         | 11/200 [00:10<02:32,  1.24it/s]

[I 2025-11-10 18:19:22,062] Trial 9 pruned.

Best trial: 2. Best value: 0.5:   6%|▌         | 12/200 [00:11<02:41,  1.16it/s]

[I 2025-11-10 18:19:23,071] Trial 13 pruned.

Best trial: 2. Best value: 0.5:   6%|▋         | 13/200 [00:12<02:35,  1.20it/s]

[I 2025-11-10 18:19:23,829] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.033843457034422826, 'n_estimators': 1180, 'subsample': 0.5656756460395242, 'colsample_bytree': 0.6133181794364118, 'min_child_weight': 9, 'gamma': 0.24458148093420506, 'reg_alpha': 1.3803646674419944e-05, 'reg_lambda': 4.6261675683629144e-07, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   7%|▋         | 14/200 [00:13<02:25,  1.27it/s]

[I 2025-11-10 18:19:24,498] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.04101093681555794, 'n_estimators': 1347, 'subsample': 0.9409638503423006, 'colsample_bytree': 0.6390964770676568, 'min_child_weight': 6, 'gamma': 2.316212905623431, 'reg_alpha': 1.8303915389656203e-05, 'reg_lambda': 2.796225093256201e-06, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   8%|▊         | 15/200 [00:15<03:31,  1.14s/it]

[I 2025-11-10 18:19:26,530] Trial 15 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03094970727532629, 'n_estimators': 803, 'subsample': 0.7954838052736978, 'colsample_bytree': 0.7591858901177084, 'min_child_weight': 6, 'gamma': 3.7893659426875637, 'reg_alpha': 0.02704101443356006, 'reg_lambda': 4.027303579468257e-07, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   8%|▊         | 16/200 [00:16<03:21,  1.09s/it]

[I 2025-11-10 18:19:27,502] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01881950161146353, 'n_estimators': 850, 'subsample': 0.7996125749713637, 'colsample_bytree': 0.7602383081588462, 'min_child_weight': 6, 'gamma': 3.952302814054832, 'reg_alpha': 0.020559159691918474, 'reg_lambda': 9.720218354096646, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   8%|▊         | 17/200 [00:16<02:53,  1.05it/s]

[I 2025-11-10 18:19:28,094] Trial 17 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.020804459186607678, 'n_estimators': 842, 'subsample': 0.803355756655282, 'colsample_bytree': 0.757157823712452, 'min_child_weight': 6, 'gamma': 3.838203464224553, 'reg_alpha': 0.0570932708735973, 'reg_lambda': 0.012378113941076836, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:   9%|▉         | 18/200 [00:17<02:15,  1.35it/s]

[I 2025-11-10 18:19:28,355] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.030029394615268667, 'n_estimators': 1490, 'subsample': 0.7753682008188798, 'colsample_bytree': 0.8283859676132089, 'min_child_weight': 7, 'gamma': 1.1529832833290459, 'reg_alpha': 0.022475294381259676, 'reg_lambda': 0.004105526952192853, 'max_delta_step': 10}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  10%|▉         | 19/200 [00:18<02:24,  1.25it/s]

[I 2025-11-10 18:19:29,282] Trial 18 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.019463281340666803, 'n_estimators': 623, 'subsample': 0.7966907016902957, 'colsample_bytree': 0.8812562931560896, 'min_child_weight': 7, 'gamma': 4.826873804817575, 'reg_alpha': 0.029469833297535296, 'reg_lambda': 0.014057125488611745, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  10%|█         | 20/200 [00:19<02:38,  1.14it/s]

[I 2025-11-10 18:19:30,360] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.019100708230055025, 'n_estimators': 648, 'subsample': 0.7199634129036497, 'colsample_bytree': 0.8910919342990951, 'min_child_weight': 7, 'gamma': 4.8090132272403014, 'reg_alpha': 0.1047129443905341, 'reg_lambda': 0.010928932495054106, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  10%|█         | 21/200 [00:19<02:15,  1.32it/s]

[I 2025-11-10 18:19:30,826] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06311714797419703, 'n_estimators': 612, 'subsample': 0.7010927021041922, 'colsample_bytree': 0.8810519240642412, 'min_child_weight': 7, 'gamma': 4.892764823736641, 'reg_alpha': 0.0009164763535778363, 'reg_lambda': 0.000450453138727431, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  11%|█         | 22/200 [00:21<03:14,  1.09s/it]

[I 2025-11-10 18:19:32,705] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06916747353441491, 'n_estimators': 996, 'subsample': 0.7096826167249497, 'colsample_bytree': 0.9396987266013518, 'min_child_weight': 7, 'gamma': 1.7542785442968418, 'reg_alpha': 0.0006999873486538934, 'reg_lambda': 0.00015486017312172577, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  12%|█▏        | 23/200 [00:22<03:01,  1.03s/it]

[I 2025-11-10 18:19:33,584] Trial 22 finished with value: 0.49920077972709553 and parameters: {'max_depth': 9, 'learning_rate': 0.075312634754848, 'n_estimators': 993, 'subsample': 0.6804786745155701, 'colsample_bytree': 0.7088236532734793, 'min_child_weight': 4, 'gamma': 3.378631968098734, 'reg_alpha': 0.0008794402104026188, 'reg_lambda': 0.0002441562544962932, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  12%|█▏        | 24/200 [00:22<02:18,  1.27it/s]

[I 2025-11-10 18:19:33,807] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.13977814626528956, 'n_estimators': 239, 'subsample': 0.8536173420410013, 'colsample_bytree': 0.5471752494933929, 'min_child_weight': 8, 'gamma': 0.23527934333646838, 'reg_alpha': 0.38359326682230077, 'reg_lambda': 3.0998291285896007e-06, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  12%|█▎        | 25/200 [00:23<02:33,  1.14it/s]

[I 2025-11-10 18:19:34,900] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1571010622278113, 'n_estimators': 1001, 'subsample': 0.5038440623681393, 'colsample_bytree': 0.519150321958953, 'min_child_weight': 8, 'gamma': 0.6790642113851191, 'reg_alpha': 0.6377213968257559, 'reg_lambda': 4.303598499349673e-05, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  14%|█▎        | 27/200 [00:24<01:32,  1.88it/s]

[I 2025-11-10 18:19:35,217] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.08416726363441093, 'n_estimators': 1069, 'subsample': 0.6643350996891312, 'colsample_bytree': 0.9854475024800671, 'min_child_weight': 10, 'gamma': 1.7480902896480441, 'reg_alpha': 9.883756174388294, 'reg_lambda': 0.00025651930348756584, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:19:35,335] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.16062436994673085, 'n_estimators': 403, 'subsample': 0.8474535296620792, 'colsample_bytree': 0.5172736396039553, 'min_child_weight': 8, 'gamma': 0.2598980581881342, 'reg_alpha': 0.4304902847285463, 'reg_lambda': 3.438980130526494e-06, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  14%|█▍        | 28/200 [00:24<01:31,  1.89it/s]

[I 2025-11-10 18:19:35,860] Trial 27 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.16322869675330828, 'n_estimators': 478, 'subsample': 0.5066896520557641, 'colsample_bytree': 0.5724472898336791, 'min_child_weight': 10, 'gamma': 0.6930926781739901, 'reg_alpha': 7.885591649183458, 'reg_lambda': 3.6439154930241015e-05, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  15%|█▌        | 30/200 [00:25<01:30,  1.87it/s]

[I 2025-11-10 18:19:36,965] Trial 28 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2999157205824849, 'n_estimators': 481, 'subsample': 0.6403900291742622, 'colsample_bytree': 0.5698428250830001, 'min_child_weight': 10, 'gamma': 2.651836467302486, 'reg_alpha': 6.9586672009268895, 'reg_lambda': 1.3520155587360978e-08, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:19:37,108] Trial 29 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2901646244473349, 'n_estimators': 435, 'subsample': 0.7530974641569654, 'colsample_bytree': 0.5666572359856796, 'min_child_weight': 8, 'gamma': 3.5051138082451283, 'reg_alpha': 0.24886025218137342, 'reg_lambda': 4.9413979669486694e-08, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  16%|█▌        | 31/200 [00:26<01:49,  1.54it/s]

[I 2025-11-10 18:19:38,023] Trial 32 pruned.

Best trial: 2. Best value: 0.5:  16%|█▌        | 32/200 [00:27<01:35,  1.76it/s]

[I 2025-11-10 18:19:38,403] Trial 30 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2775950559699319, 'n_estimators': 708, 'subsample': 0.6344796161994352, 'colsample_bytree': 0.6932708692097536, 'min_child_weight': 5, 'gamma': 3.4391518957937377, 'reg_alpha': 0.003472465009283006, 'reg_lambda': 1.5521790937014757e-08, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  16%|█▋        | 33/200 [00:27<01:28,  1.88it/s]

[I 2025-11-10 18:19:38,849] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.287933475689256, 'n_estimators': 702, 'subsample': 0.7540451613862698, 'colsample_bytree': 0.6863250113443714, 'min_child_weight': 5, 'gamma': 3.439820519426597, 'reg_alpha': 0.003779173587144739, 'reg_lambda': 1.8626274172006156e-08, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  17%|█▋        | 34/200 [00:29<02:09,  1.28it/s]

[I 2025-11-10 18:19:40,214] Trial 33 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.21915874890533102, 'n_estimators': 728, 'subsample': 0.7428016174248163, 'colsample_bytree': 0.6914231414695227, 'min_child_weight': 5, 'gamma': 4.394856780371567, 'reg_alpha': 0.003224361796683643, 'reg_lambda': 6.10598224365411e-07, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  18%|█▊        | 35/200 [00:32<04:10,  1.52s/it]

[I 2025-11-10 18:19:43,459] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04606726155883485, 'n_estimators': 1263, 'subsample': 0.6090522402200489, 'colsample_bytree': 0.983109420782516, 'min_child_weight': 9, 'gamma': 4.300443059959077, 'reg_alpha': 1.254806865198208e-08, 'reg_lambda': 1.871407075920852e-05, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  18%|█▊        | 36/200 [00:32<03:23,  1.24s/it]

[I 2025-11-10 18:19:44,034] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.10040838399854703, 'n_estimators': 1320, 'subsample': 0.6008826916493509, 'colsample_bytree': 0.9827431940662145, 'min_child_weight': 9, 'gamma': 3.9938461502733045, 'reg_alpha': 1.7026271240432387, 'reg_lambda': 7.923684528704532e-07, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  18%|█▊        | 37/200 [00:33<02:40,  1.02it/s]

[I 2025-11-10 18:19:44,433] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.11060102220573216, 'n_estimators': 1335, 'subsample': 0.596213002235372, 'colsample_bytree': 0.9951633192551814, 'min_child_weight': 9, 'gamma': 4.256396848252969, 'reg_alpha': 2.6339731841577195e-08, 'reg_lambda': 6.581706687577696e-07, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  19%|█▉        | 38/200 [00:34<02:42,  1.00s/it]

[I 2025-11-10 18:19:45,470] Trial 40 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.012818673447406961, 'n_estimators': 220, 'subsample': 0.5386763426577357, 'colsample_bytree': 0.8386883650578955, 'min_child_weight': 10, 'gamma': 3.0531321667925106, 'reg_alpha': 2.323920455148779e-07, 'reg_lambda': 0.001513710434164652, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  20%|█▉        | 39/200 [00:34<02:04,  1.29it/s]

[I 2025-11-10 18:19:45,711] Trial 37 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.104752635092203, 'n_estimators': 1292, 'subsample': 0.5863706709321957, 'colsample_bytree': 0.9541198669871419, 'min_child_weight': 9, 'gamma': 4.221670105079727, 'reg_alpha': 0.00020463463769736362, 'reg_lambda': 3.221033642596332e-05, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  20%|██        | 40/200 [00:36<02:50,  1.07s/it]

[I 2025-11-10 18:19:47,471] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.11451955513468014, 'n_estimators': 908, 'subsample': 0.5939843893607639, 'colsample_bytree': 0.9446523284886729, 'min_child_weight': 9, 'gamma': 2.9317996389782395, 'reg_alpha': 0.00013779582138763178, 'reg_lambda': 0.23704257575784635, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  20%|██        | 41/200 [00:36<02:27,  1.08it/s]

[I 2025-11-10 18:19:48,074] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.013311244835151378, 'n_estimators': 919, 'subsample': 0.543129510998589, 'colsample_bytree': 0.926231149704309, 'min_child_weight': 9, 'gamma': 2.9078194669416195, 'reg_alpha': 8.109815913731984e-08, 'reg_lambda': 0.0017768892801808887, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  21%|██        | 42/200 [00:38<02:48,  1.07s/it]

[I 2025-11-10 18:19:49,456] Trial 42 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.12579737609999858, 'n_estimators': 923, 'subsample': 0.9941539757079981, 'colsample_bytree': 0.6108305584124734, 'min_child_weight': 8, 'gamma': 2.694137629606848, 'reg_alpha': 1.840869315237356, 'reg_lambda': 0.09651909595884496, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  22%|██▏       | 43/200 [00:39<02:43,  1.04s/it]

[I 2025-11-10 18:19:50,448] Trial 41 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.12847140473432475, 'n_estimators': 1155, 'subsample': 0.5689827372501054, 'colsample_bytree': 0.9422996630747286, 'min_child_weight': 8, 'gamma': 2.7687944321806692, 'reg_alpha': 4.150679140172624e-05, 'reg_lambda': 0.06334859253536175, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  22%|██▏       | 44/200 [00:39<02:13,  1.17it/s]

[I 2025-11-10 18:19:50,863] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.18937617023811082, 'n_estimators': 312, 'subsample': 0.5683986381177235, 'colsample_bytree': 0.651338133932545, 'min_child_weight': 4, 'gamma': 2.3247828227445817, 'reg_alpha': 3.323366051300666e-05, 'reg_lambda': 9.253847063034273, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  22%|██▎       | 45/200 [00:40<02:28,  1.04it/s]

[I 2025-11-10 18:19:52,063] Trial 47 pruned.
[I 2025-11-10 18:19:52,079] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.2065898205757613, 'n_estimators': 352, 'subsample': 0.5266420203782355, 'colsample_bytree': 0.7337303539377845, 'min_child_weight': 4, 'gamma': 2.301362635411532, 'reg_alpha': 1.8571520639466625, 'reg_lambda': 2.806037627612947, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  24%|██▎       | 47/200 [00:41<01:36,  1.59it/s]

[I 2025-11-10 18:19:52,554] Trial 43 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.013860275674573808, 'n_estimators': 1179, 'subsample': 0.8348572400088375, 'colsample_bytree': 0.7900048328728887, 'min_child_weight': 8, 'gamma': 2.7864313105806917, 'reg_alpha': 1.3730838977214683, 'reg_lambda': 1.5950332958651647, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

[I 2025-11-10 18:19:52,782] Trial 49 pruned.

Best trial: 2. Best value: 0.5:  24%|██▍       | 49/200 [00:41<01:06,  2.29it/s]

[I 2025-11-10 18:19:52,959] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.19691908195979477, 'n_estimators': 1156, 'subsample': 0.5253029435774664, 'colsample_bytree': 0.6400835028788866, 'min_child_weight': 4, 'gamma': 2.257360614004984, 'reg_alpha': 1.9282789992143228, 'reg_lambda': 3.34662305862357, 'max_delta_step': 3}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  25%|██▌       | 50/200 [00:42<01:16,  1.97it/s]

[I 2025-11-10 18:19:53,655] Trial 48 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.08833030812036274, 'n_estimators': 342, 'subsample': 0.5230201839162163, 'colsample_bytree': 0.5898348002185393, 'min_child_weight': 7, 'gamma': 2.014795408965928, 'reg_alpha': 0.8970599290468437, 'reg_lambda': 7.090857125977948e-06, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  26%|██▌       | 51/200 [00:42<01:14,  2.00it/s]

[I 2025-11-10 18:19:54,134] Trial 50 pruned.

Best trial: 2. Best value: 0.5:  26%|██▌       | 52/200 [00:47<03:59,  1.62s/it]

[I 2025-11-10 18:19:58,545] Trial 51 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09279060964205846, 'n_estimators': 1407, 'subsample': 0.8998775206932421, 'colsample_bytree': 0.6004288339332225, 'min_child_weight': 6, 'gamma': 2.1286469947745434, 'reg_alpha': 0.010317558321009822, 'reg_lambda': 0.054694314203585455, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  26%|██▋       | 53/200 [00:47<03:02,  1.24s/it]

[I 2025-11-10 18:19:58,859] Trial 54 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.010645073908852207, 'n_estimators': 1088, 'subsample': 0.885855239615774, 'colsample_bytree': 0.7862942066927607, 'min_child_weight': 6, 'gamma': 3.736800835064674, 'reg_alpha': 0.0143850524420809, 'reg_lambda': 0.03870165176603672, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:19:58,864] Trial 52 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.010227731291503252, 'n_estimators': 1429, 'subsample': 0.6734772896570833, 'colsample_bytree': 0.5936955057147016, 'min_child_weight': 6, 'gamma': 3.7183837577840855, 'reg_alpha': 4.326757206762633e-06, 'reg_lambda': 8.887451721964621e-06, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  28%|██▊       | 55/200 [00:48<02:12,  1.10it/s]

[I 2025-11-10 18:19:59,887] Trial 53 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.062131433879926756, 'n_estimators': 1409, 'subsample': 0.68075373791317, 'colsample_bytree': 0.8530425610993984, 'min_child_weight': 6, 'gamma': 4.600395590409311, 'reg_alpha': 0.10168468390598076, 'reg_lambda': 0.00011803746588062856, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  28%|██▊       | 56/200 [00:51<03:10,  1.32s/it]

[I 2025-11-10 18:20:02,485] Trial 56 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.017102006601521915, 'n_estimators': 855, 'subsample': 0.9172349335960366, 'colsample_bytree': 0.5378195548100214, 'min_child_weight': 10, 'gamma': 2.5249338073238263, 'reg_alpha': 0.12028034866859914, 'reg_lambda': 0.7095175231509994, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:20:02,493] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.016552985751689352, 'n_estimators': 857, 'subsample': 0.7794553560272494, 'colsample_bytree': 0.5446468738673828, 'min_child_weight': 10, 'gamma': 1.6878449795903692, 'reg_alpha': 0.08495389104226676, 'reg_lambda': 0.00011109914163400308, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  29%|██▉       | 58/200 [00:52<02:11,  1.08it/s]

[I 2025-11-10 18:20:03,191] Trial 55 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.010987079171792358, 'n_estimators': 1055, 'subsample': 0.8836823571153846, 'colsample_bytree': 0.7894700618031644, 'min_child_weight': 10, 'gamma': 3.6289556651136987, 'reg_alpha': 0.11135878205578993, 'reg_lambda': 0.036562036569345396, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  30%|██▉       | 59/200 [00:52<01:48,  1.30it/s]

[I 2025-11-10 18:20:03,437] Trial 58 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.02715992639567716, 'n_estimators': 836, 'subsample': 0.9562413605143679, 'colsample_bytree': 0.5438981342029785, 'min_child_weight': 10, 'gamma': 1.413374454518347, 'reg_alpha': 0.04769783496937315, 'reg_lambda': 0.6235154336598074, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  30%|███       | 60/200 [00:52<01:37,  1.44it/s]

[I 2025-11-10 18:20:03,902] Trial 59 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.023948398240040074, 'n_estimators': 289, 'subsample': 0.8746481131025157, 'colsample_bytree': 0.7253383213441627, 'min_child_weight': 7, 'gamma': 1.1930019284514692, 'reg_alpha': 3.9355002306802382, 'reg_lambda': 0.22317191953922788, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  31%|███       | 62/200 [00:55<02:16,  1.01it/s]

[I 2025-11-10 18:20:06,946] Trial 60 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.02267218921063632, 'n_estimators': 1044, 'subsample': 0.9545896146223719, 'colsample_bytree': 0.90601930955762, 'min_child_weight': 7, 'gamma': 1.2484920782255378, 'reg_alpha': 3.895044025362178, 'reg_lambda': 0.2810474692797913, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:20:07,086] Trial 61 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.025780671044700897, 'n_estimators': 958, 'subsample': 0.7318359834549206, 'colsample_bytree': 0.7370966665094136, 'min_child_weight': 7, 'gamma': 3.312204470451611, 'reg_alpha': 4.242368158301218, 'reg_lambda': 0.1991266469769135, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  32%|███▏      | 63/200 [00:57<02:30,  1.10s/it]

[I 2025-11-10 18:20:08,471] Trial 62 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1476455650167407, 'n_estimators': 1238, 'subsample': 0.7392508175008032, 'colsample_bytree': 0.7259269496153531, 'min_child_weight': 7, 'gamma': 2.944812911511298, 'reg_alpha': 4.444130364654618, 'reg_lambda': 1.3424354236223902e-06, 'max_delta_step': 7}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  32%|███▏      | 64/200 [00:57<02:12,  1.03it/s]

[I 2025-11-10 18:20:09,126] Trial 63 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.14771741431138927, 'n_estimators': 1258, 'subsample': 0.5605805807580394, 'colsample_bytree': 0.8148555397043746, 'min_child_weight': 7, 'gamma': 0.6057223074154321, 'reg_alpha': 0.2590059342414659, 'reg_lambda': 1.767945822332609e-06, 'max_delta_step': 10}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  32%|███▎      | 65/200 [01:00<02:55,  1.30s/it]

[I 2025-11-10 18:20:11,223] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.17797332182386413, 'n_estimators': 977, 'subsample': 0.9360885536783832, 'colsample_bytree': 0.8717675244314469, 'min_child_weight': 8, 'gamma': 3.334417306308947, 'reg_alpha': 2.674992215718296e-06, 'reg_lambda': 1.5907519171848768e-06, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  33%|███▎      | 66/200 [01:00<02:14,  1.00s/it]

[I 2025-11-10 18:20:11,514] Trial 67 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.17848858783884217, 'n_estimators': 542, 'subsample': 0.9778287643682462, 'colsample_bytree': 0.9034587742858758, 'min_child_weight': 8, 'gamma': 0.016718943592537228, 'reg_alpha': 9.562195889437482e-07, 'reg_lambda': 2.8844214833069186, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  34%|███▎      | 67/200 [01:00<01:48,  1.23it/s]

[I 2025-11-10 18:20:11,872] Trial 66 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.24558098451708985, 'n_estimators': 769, 'subsample': 0.975129487193038, 'colsample_bytree': 0.8675569168521056, 'min_child_weight': 8, 'gamma': 3.918787959205765, 'reg_alpha': 1.0650015383662183e-06, 'reg_lambda': 5.175025328405062, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  34%|███▍      | 68/200 [01:01<01:39,  1.33it/s]

[I 2025-11-10 18:20:12,489] Trial 65 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.14761575371464108, 'n_estimators': 1254, 'subsample': 0.9714986594728847, 'colsample_bytree': 0.8158180478028897, 'min_child_weight': 8, 'gamma': 2.941213321242493, 'reg_alpha': 4.777009743917068e-07, 'reg_lambda': 4.458401631377111, 'max_delta_step': 5}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  34%|███▍      | 69/200 [01:02<01:44,  1.26it/s]

[I 2025-11-10 18:20:13,378] Trial 68 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.07737517420984587, 'n_estimators': 432, 'subsample': 0.8132244958756337, 'colsample_bytree': 0.9143635166908217, 'min_child_weight': 8, 'gamma': 3.99421647577625, 'reg_alpha': 8.077361185927405e-06, 'reg_lambda': 2.442340754962891e-07, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  35%|███▌      | 70/200 [01:03<01:48,  1.19it/s]

[I 2025-11-10 18:20:14,313] Trial 71 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.07608769507185631, 'n_estimators': 404, 'subsample': 0.7727712367681812, 'colsample_bytree': 0.6735244701021083, 'min_child_weight': 9, 'gamma': 0.8820947865551422, 'reg_alpha': 9.98069518762195e-06, 'reg_lambda': 1.7819669881882657e-07, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  36%|███▌      | 71/200 [01:03<01:34,  1.36it/s]

[I 2025-11-10 18:20:14,807] Trial 69 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.23888988331694866, 'n_estimators': 770, 'subsample': 0.7758384555536177, 'colsample_bytree': 0.5058588358181814, 'min_child_weight': 9, 'gamma': 3.9088631817125106, 'reg_alpha': 2.523535058853774e-07, 'reg_lambda': 1.811935073527447e-07, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  36%|███▌      | 72/200 [01:04<01:26,  1.49it/s]

[I 2025-11-10 18:20:15,330] Trial 70 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03991969216622871, 'n_estimators': 650, 'subsample': 0.695114462901138, 'colsample_bytree': 0.9649102578463696, 'min_child_weight': 9, 'gamma': 3.046007567166498, 'reg_alpha': 7.639980869172405e-06, 'reg_lambda': 7.122840347899104e-05, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  36%|███▋      | 73/200 [01:06<02:12,  1.05s/it]

[I 2025-11-10 18:20:17,258] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.01215463652830386, 'n_estimators': 203, 'subsample': 0.6958450739116969, 'colsample_bytree': 0.9698421588668209, 'min_child_weight': 9, 'gamma': 3.101204350396466, 'reg_alpha': 0.33741058226870946, 'reg_lambda': 4.520599665442776e-08, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  37%|███▋      | 74/200 [01:08<03:09,  1.50s/it]

[I 2025-11-10 18:20:19,821] Trial 72 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.125724495324826, 'n_estimators': 1132, 'subsample': 0.6909717348856722, 'colsample_bytree': 0.9551839221104744, 'min_child_weight': 9, 'gamma': 3.0717113345184597, 'reg_alpha': 0.39321057516715524, 'reg_lambda': 0.01781262599093424, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  38%|███▊      | 75/200 [01:09<02:56,  1.41s/it]

[I 2025-11-10 18:20:21,024] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.015832101711878266, 'n_estimators': 280, 'subsample': 0.5000020379273039, 'colsample_bytree': 0.5664195902164569, 'min_child_weight': 9, 'gamma': 2.5856878852710263, 'reg_alpha': 6.794949612512984e-08, 'reg_lambda': 0.10859670066730218, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:20:21,030] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.01160782132247219, 'n_estimators': 1124, 'subsample': 0.5479350907367462, 'colsample_bytree': 0.628587396942095, 'min_child_weight': 9, 'gamma': 2.6082700794658638, 'reg_alpha': 2.5903838311515597e-06, 'reg_lambda': 3.147793274386442e-08, 'max_delta_step': 1}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  39%|███▉      | 78/200 [01:10<01:30,  1.34it/s]

[I 2025-11-10 18:20:21,828] Trial 76 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.014260820892578463, 'n_estimators': 1110, 'subsample': 0.5452932046183343, 'colsample_bytree': 0.6241371707897766, 'min_child_weight': 9, 'gamma': 2.672859002490616, 'reg_alpha': 0.0015291293334255534, 'reg_lambda': 1.7623352952286945e-05, 'max_delta_step': 2}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:20:21,964] Trial 73 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.042265657756409614, 'n_estimators': 1497, 'subsample': 0.704207590965624, 'colsample_bytree': 0.7679773733601832, 'min_child_weight': 9, 'gamma': 3.1099663769116375, 'reg_alpha': 0.31284612652189475, 'reg_lambda': 0.0008396122082566334, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  40%|███▉      | 79/200 [01:11<01:30,  1.34it/s]

[I 2025-11-10 18:20:22,719] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.014904505788476165, 'n_estimators': 351, 'subsample': 0.5747577798939689, 'colsample_bytree': 0.7730073911954052, 'min_child_weight': 8, 'gamma': 1.8976999956610354, 'reg_alpha': 0.7994857552104369, 'reg_lambda': 4.632024600069479e-06, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  40%|████      | 80/200 [01:11<01:17,  1.55it/s]

[I 2025-11-10 18:20:23,092] Trial 80 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.032918066667535974, 'n_estimators': 250, 'subsample': 0.7229748531660544, 'colsample_bytree': 0.6593265189531894, 'min_child_weight': 8, 'gamma': 4.988184799163614, 'reg_alpha': 8.097497185685178e-05, 'reg_lambda': 4.727280612513788e-06, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  40%|████      | 81/200 [01:12<01:05,  1.82it/s]

[I 2025-11-10 18:20:23,398] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.014861805555628617, 'n_estimators': 498, 'subsample': 0.6593683246136087, 'colsample_bytree': 0.8890132100281579, 'min_child_weight': 8, 'gamma': 3.255497660886975, 'reg_alpha': 0.8399779513621384, 'reg_lambda': 4.762190252402489e-06, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  41%|████      | 82/200 [01:13<01:24,  1.39it/s]

[I 2025-11-10 18:20:24,532] Trial 84 pruned.

Best trial: 2. Best value: 0.5:  42%|████▏     | 83/200 [01:13<01:15,  1.54it/s]

[I 2025-11-10 18:20:25,012] Trial 82 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03035370989562062, 'n_estimators': 496, 'subsample': 0.86067698935906, 'colsample_bytree': 0.8293765815129771, 'min_child_weight': 10, 'gamma': 2.390835319685533, 'reg_alpha': 0.00011526655655962063, 'reg_lambda': 0.8889703638600097, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  42%|████▏     | 84/200 [01:15<01:59,  1.03s/it]

[I 2025-11-10 18:20:26,967] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02011378330250923, 'n_estimators': 883, 'subsample': 0.6530816584823471, 'colsample_bytree': 0.932378672227666, 'min_child_weight': 10, 'gamma': 2.4286212356678094, 'reg_alpha': 0.00037031924797167984, 'reg_lambda': 1.64504850513747, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:20:27,005] Trial 81 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.014962532191527841, 'n_estimators': 1210, 'subsample': 0.5190047452704446, 'colsample_bytree': 0.670713382476558, 'min_child_weight': 8, 'gamma': 3.5157538012070875, 'reg_alpha': 0.9128755132640867, 'reg_lambda': 1.333220593546457, 'max_delta_step': 4}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  43%|████▎     | 86/200 [01:18<02:25,  1.28s/it]

[I 2025-11-10 18:20:30,111] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05096974182796302, 'n_estimators': 1347, 'subsample': 0.5835709182790425, 'colsample_bytree': 0.580642340265707, 'min_child_weight': 6, 'gamma': 2.8129560063417616, 'reg_alpha': 0.0004083422792812383, 'reg_lambda': 1.373231807014305e-05, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:20:30,132] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.019838349609371694, 'n_estimators': 1217, 'subsample': 0.9977659466983438, 'colsample_bytree': 0.6060537349108068, 'min_child_weight': 6, 'gamma': 2.739192735732212, 'reg_alpha': 0.0004286796382226008, 'reg_lambda': 1.856376097764438e-05, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  44%|████▍     | 88/200 [01:21<02:12,  1.18s/it]

[I 2025-11-10 18:20:32,166] Trial 87 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.09847066951788135, 'n_estimators': 1197, 'subsample': 0.9932064881253833, 'colsample_bytree': 0.580385133666623, 'min_child_weight': 6, 'gamma': 2.180250221880428, 'reg_alpha': 4.114060000710839e-07, 'reg_lambda': 9.684162493748378e-07, 'max_delta_step': 8}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  44%|████▍     | 89/200 [01:21<01:52,  1.02s/it]

[I 2025-11-10 18:20:32,603] Trial 88 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.11194237289269085, 'n_estimators': 1297, 'subsample': 0.9189706891916349, 'colsample_bytree': 0.5825111037764253, 'min_child_weight': 6, 'gamma': 2.833766268392255, 'reg_alpha': 1.7926231445757962e-06, 'reg_lambda': 4.878105864779779e-07, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.

Best trial: 2. Best value: 0.5:  45%|████▌     | 90/200 [01:21<01:38,  1.11it/s]

[I 2025-11-10 18:20:33,124] Trial 91 pruned.

Best trial: 2. Best value: 0.5:  46%|████▌     | 91/200 [01:22<01:40,  1.08it/s]

[I 2025-11-10 18:20:34,133] Trial 92 pruned.

Best trial: 89. Best value: 0.56117:  46%|████▋     | 93/200 [01:23<01:05,  1.64it/s]

[I 2025-11-10 18:20:34,571] Trial 90 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.11765138932401939, 'n_estimators': 1023, 'subsample': 0.9136220939265014, 'colsample_bytree': 0.5580807018182552, 'min_child_weight': 5, 'gamma': 4.623045801668505, 'reg_alpha': 9.357052924714962, 'reg_lambda': 3.9867257020676335e-07, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:20:34,684] Trial 89 finished with value: 0.5611695906432749 and parameters: {'max_depth': 8, 'learning_rate': 0.11944328892393857, 'n_estimators': 1021, 'subsample': 0.9064508017212284, 'colsample_bytree': 0.6008627703710215, 'min_child_weight': 5, 'gamma': 4.646949872177505, 'reg_alpha': 1.6525548889863452e-06, 'reg_lambda': 4.075086564945234e-07, 'max_delta_step': 9}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  47%|████▋     | 94/200 [01:25<01:34,  1.12it/s]

[I 2025-11-10 18:20:36,303] Trial 95 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.045617614340997106, 'n_estimators': 398, 'subsample': 0.6261556340863721, 'colsample_bytree': 0.6469382215363242, 'min_child_weight': 7, 'gamma': 0.411563319384578, 'reg_alpha': 1.848814606091326e-05, 'reg_lambda': 0.45373954098560915, 'max_delta_step': 10}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  48%|████▊     | 95/200 [01:26<01:34,  1.11it/s]

[I 2025-11-10 18:20:37,228] Trial 97 pruned.

Best trial: 89. Best value: 0.56117:  48%|████▊     | 96/200 [01:26<01:29,  1.16it/s]

[I 2025-11-10 18:20:37,984] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.06915437314354257, 'n_estimators': 943, 'subsample': 0.5389178098839865, 'colsample_bytree': 0.6414672998325853, 'min_child_weight': 7, 'gamma': 0.34332966704346257, 'reg_alpha': 1.5611094964434442e-05, 'reg_lambda': 0.0002713503001974244, 'max_delta_step': 10}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  48%|████▊     | 97/200 [01:27<01:20,  1.28it/s]

[I 2025-11-10 18:20:38,574] Trial 96 finished with value: 0.5444444444444445 and parameters: {'max_depth': 7, 'learning_rate': 0.13225832700153906, 'n_estimators': 928, 'subsample': 0.6192396897090472, 'colsample_bytree': 0.6506084454211282, 'min_child_weight': 4, 'gamma': 4.170412939397737, 'reg_alpha': 5.830836078887612e-07, 'reg_lambda': 2.6761176223471516e-06, 'max_delta_step': 7}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  49%|████▉     | 98/200 [01:28<01:14,  1.37it/s]

[I 2025-11-10 18:20:39,190] Trial 93 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.017771365968254054, 'n_estimators': 1454, 'subsample': 0.5573254917933733, 'colsample_bytree': 0.6174453428534601, 'min_child_weight': 7, 'gamma': 1.5968737824912147, 'reg_alpha': 0.00739710916839244, 'reg_lambda': 0.4804167370956824, 'max_delta_step': 7}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  50%|████▉     | 99/200 [01:28<00:59,  1.69it/s]

[I 2025-11-10 18:20:39,454] Trial 100 pruned.

Best trial: 89. Best value: 0.56117:  50%|█████     | 100/200 [01:29<01:04,  1.54it/s]

[I 2025-11-10 18:20:40,233] Trial 102 pruned.

Best trial: 89. Best value: 0.56117:  50%|█████     | 101/200 [01:30<01:19,  1.25it/s]

[I 2025-11-10 18:20:41,387] Trial 98 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.15926759185095674, 'n_estimators': 944, 'subsample': 0.7921900484573475, 'colsample_bytree': 0.5989678211122436, 'min_child_weight': 7, 'gamma': 1.5604578227280868, 'reg_alpha': 9.719779371929447e-08, 'reg_lambda': 2.4660747483997664e-06, 'max_delta_step': 6}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  51%|█████     | 102/200 [01:30<01:12,  1.35it/s]

[I 2025-11-10 18:20:41,991] Trial 99 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.16289963185095777, 'n_estimators': 812, 'subsample': 0.5130155396952558, 'colsample_bytree': 0.9988129062486321, 'min_child_weight': 4, 'gamma': 4.141262988047319, 'reg_alpha': 1.8833711155602669e-07, 'reg_lambda': 0.1659071668264358, 'max_delta_step': 9}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  52%|█████▏    | 103/200 [01:31<01:17,  1.26it/s]

[I 2025-11-10 18:20:42,915] Trial 105 pruned.

Best trial: 89. Best value: 0.56117:  52%|█████▏    | 104/200 [01:32<01:01,  1.57it/s]

[I 2025-11-10 18:20:43,183] Trial 101 finished with value: 0.5166666666666666 and parameters: {'max_depth': 7, 'learning_rate': 0.17013609743706462, 'n_estimators': 895, 'subsample': 0.6171996938667252, 'colsample_bytree': 0.6015889459385213, 'min_child_weight': 4, 'gamma': 4.224680147870174, 'reg_alpha': 1.1804278805716508e-07, 'reg_lambda': 2.297425911115063e-06, 'max_delta_step': 1}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  52%|█████▎    | 105/200 [01:32<00:56,  1.67it/s]

[I 2025-11-10 18:20:43,694] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1615708437899223, 'n_estimators': 784, 'subsample': 0.5130916004890401, 'colsample_bytree': 0.5322141348359899, 'min_child_weight': 4, 'gamma': 3.4364731674904507, 'reg_alpha': 6.34055051719891e-07, 'reg_lambda': 7.534520375106431e-08, 'max_delta_step': 3}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  53%|█████▎    | 106/200 [01:33<00:53,  1.77it/s]

[I 2025-11-10 18:20:44,179] Trial 107 pruned.
[I 2025-11-10 18:20:44,200] Trial 106 pruned.

Best trial: 89. Best value: 0.56117:  54%|█████▍    | 108/200 [01:33<00:46,  1.96it/s]

[I 2025-11-10 18:20:45,070] Trial 109 pruned.

Best trial: 89. Best value: 0.56117:  55%|█████▍    | 109/200 [01:34<00:58,  1.55it/s]

[I 2025-11-10 18:20:46,122] Trial 104 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.012821433493781861, 'n_estimators': 1079, 'subsample': 0.5093408582869001, 'colsample_bytree': 0.7002379245958138, 'min_child_weight': 4, 'gamma': 4.337137020314434, 'reg_alpha': 1.6383777656633172e-06, 'reg_lambda': 1.1170356580211897e-07, 'max_delta_step': 8}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  55%|█████▌    | 110/200 [01:36<01:17,  1.16it/s]

[I 2025-11-10 18:20:47,599] Trial 108 finished with value: 0.5248148148148148 and parameters: {'max_depth': 7, 'learning_rate': 0.2061531960452707, 'n_estimators': 866, 'subsample': 0.5323505962951248, 'colsample_bytree': 0.8015810335541271, 'min_child_weight': 3, 'gamma': 4.26703117292412, 'reg_alpha': 1.420532518725857e-07, 'reg_lambda': 9.304695995153142e-06, 'max_delta_step': 1}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  56%|█████▌    | 111/200 [01:36<01:03,  1.41it/s]

[I 2025-11-10 18:20:47,899] Trial 110 finished with value: 0.4892592592592592 and parameters: {'max_depth': 4, 'learning_rate': 0.1347822700722448, 'n_estimators': 866, 'subsample': 0.5310402422382603, 'colsample_bytree': 0.5882801501865785, 'min_child_weight': 3, 'gamma': 3.6871961255864427, 'reg_alpha': 2.6526408097951504, 'reg_lambda': 7.98757064008524e-06, 'max_delta_step': 1}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  56%|█████▌    | 112/200 [01:37<00:55,  1.59it/s]

[I 2025-11-10 18:20:48,330] Trial 113 pruned.

Best trial: 89. Best value: 0.56117:  56%|█████▋    | 113/200 [01:37<00:49,  1.74it/s]

[I 2025-11-10 18:20:48,761] Trial 115 pruned.
[I 2025-11-10 18:20:48,782] Trial 114 pruned.

Best trial: 89. Best value: 0.56117:  57%|█████▊    | 115/200 [01:37<00:32,  2.58it/s]

[I 2025-11-10 18:20:49,080] Trial 111 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.13548185550007105, 'n_estimators': 873, 'subsample': 0.5307178331383995, 'colsample_bytree': 0.8014726244125976, 'min_child_weight': 5, 'gamma': 4.353573165268604, 'reg_alpha': 2.7517562455743637e-07, 'reg_lambda': 6.396860831758776e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  58%|█████▊    | 116/200 [01:38<00:38,  2.17it/s]

[I 2025-11-10 18:20:49,767] Trial 117 pruned.

Best trial: 89. Best value: 0.56117:  59%|█████▉    | 118/200 [01:39<00:27,  2.99it/s]

[I 2025-11-10 18:20:50,065] Trial 112 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.13315644268440874, 'n_estimators': 876, 'subsample': 0.5869027378332481, 'colsample_bytree': 0.6615530984928625, 'min_child_weight': 5, 'gamma': 3.222932326305483, 'reg_alpha': 0.033112734480062536, 'reg_lambda': 2.2499179331880277, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.
[I 2025-11-10 18:20:50,173] Trial 118 pruned.

Best trial: 89. Best value: 0.56117:  60%|█████▉    | 119/200 [01:39<00:23,  3.40it/s]

[I 2025-11-10 18:20:50,360] Trial 119 pruned.

Best trial: 89. Best value: 0.56117:  60%|██████    | 120/200 [01:40<00:35,  2.23it/s]

[I 2025-11-10 18:20:51,195] Trial 120 pruned.

Best trial: 89. Best value: 0.56117:  60%|██████    | 121/200 [01:40<00:45,  1.75it/s]

[I 2025-11-10 18:20:52,073] Trial 121 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.2229335861023659, 'n_estimators': 383, 'subsample': 0.5526493484307554, 'colsample_bytree': 0.8503005086329217, 'min_child_weight': 10, 'gamma': 1.049035566389776, 'reg_alpha': 1.3205558149442506e-07, 'reg_lambda': 2.8360630539956927e-06, 'max_delta_step': 5}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  61%|██████    | 122/200 [01:41<00:51,  1.52it/s]

[I 2025-11-10 18:20:52,932] Trial 116 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.2004146379499979, 'n_estimators': 906, 'subsample': 0.5509153352023375, 'colsample_bytree': 0.6600767589516507, 'min_child_weight': 5, 'gamma': 0.9818288536062181, 'reg_alpha': 1.3527416564423369e-07, 'reg_lambda': 2.8147831172413384e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  62%|██████▏   | 123/200 [01:42<00:59,  1.30it/s]

[I 2025-11-10 18:20:53,978] Trial 122 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.20416858786639702, 'n_estimators': 832, 'subsample': 0.5563157735392494, 'colsample_bytree': 0.5729892987158137, 'min_child_weight': 10, 'gamma': 0.9936704956353939, 'reg_alpha': 6.113852838569557, 'reg_lambda': 2.9041039083261734e-06, 'max_delta_step': 5}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  62%|██████▏   | 124/200 [01:43<00:47,  1.60it/s]

[I 2025-11-10 18:20:54,258] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.20103927475066388, 'n_estimators': 443, 'subsample': 0.8776318407286533, 'colsample_bytree': 0.8292151399655431, 'min_child_weight': 8, 'gamma': 2.064832009212071, 'reg_alpha': 5.947422510402091, 'reg_lambda': 1.3109400268520134e-05, 'max_delta_step': 6}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  62%|██████▎   | 125/200 [01:44<00:55,  1.36it/s]

[I 2025-11-10 18:20:55,253] Trial 123 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.22062506807722404, 'n_estimators': 922, 'subsample': 0.890338548165618, 'colsample_bytree': 0.606303110138508, 'min_child_weight': 10, 'gamma': 0.8710355755082406, 'reg_alpha': 8.659210667188515e-07, 'reg_lambda': 1.2499212476142854e-05, 'max_delta_step': 6}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  63%|██████▎   | 126/200 [01:45<01:05,  1.14it/s]

[I 2025-11-10 18:20:56,475] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.17368086839203992, 'n_estimators': 837, 'subsample': 0.8813386296637679, 'colsample_bytree': 0.5729829478181498, 'min_child_weight': 8, 'gamma': 4.2196217603453725, 'reg_alpha': 1.0136199546220602e-06, 'reg_lambda': 1.927056548871219e-06, 'max_delta_step': 7}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  64%|██████▎   | 127/200 [01:48<01:51,  1.53s/it]

[I 2025-11-10 18:20:59,520] Trial 126 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1720798500902586, 'n_estimators': 1367, 'subsample': 0.9297570652162492, 'colsample_bytree': 0.6246113127159453, 'min_child_weight': 8, 'gamma': 4.039436128357909, 'reg_alpha': 1.001294038915549e-06, 'reg_lambda': 1.1629432122081798e-05, 'max_delta_step': 6}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  64%|██████▍   | 128/200 [01:48<01:25,  1.19s/it]

[I 2025-11-10 18:20:59,928] Trial 127 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.057169115475876844, 'n_estimators': 1380, 'subsample': 0.9272592892081066, 'colsample_bytree': 0.605646449164573, 'min_child_weight': 8, 'gamma': 3.995966059375355, 'reg_alpha': 9.043902970232593e-07, 'reg_lambda': 1.7686988938592567e-06, 'max_delta_step': 7}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  64%|██████▍   | 129/200 [01:49<01:12,  1.02s/it]

[I 2025-11-10 18:21:00,558] Trial 128 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.036746751286192196, 'n_estimators': 1301, 'subsample': 0.9264556201457315, 'colsample_bytree': 0.6482868008625877, 'min_child_weight': 8, 'gamma': 4.083413638139826, 'reg_alpha': 1.2959737330818251e-06, 'reg_lambda': 2.5629686317686152e-05, 'max_delta_step': 7}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  65%|██████▌   | 130/200 [01:51<01:24,  1.21s/it]

[I 2025-11-10 18:21:02,215] Trial 129 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01163994904052169, 'n_estimators': 1300, 'subsample': 0.5343826514750571, 'colsample_bytree': 0.8914545299411899, 'min_child_weight': 9, 'gamma': 2.5368720490639665, 'reg_alpha': 2.4318525858170177, 'reg_lambda': 4.633538644795229e-06, 'max_delta_step': 1}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  66%|██████▌   | 131/200 [01:53<01:53,  1.64s/it]

[I 2025-11-10 18:21:04,870] Trial 132 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.01147239078690547, 'n_estimators': 957, 'subsample': 0.8969404272549925, 'colsample_bytree': 0.8974900799063064, 'min_child_weight': 9, 'gamma': 4.542769959024771, 'reg_alpha': 0.002148869065373119, 'reg_lambda': 4.2421676232041135e-06, 'max_delta_step': 1}. Best is trial 89 with value: 0.5611695906432749.
[I 2025-11-10 18:21:04,912] Trial 130 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.14919174633720572, 'n_estimators': 1289, 'subsample': 0.567427912465354, 'colsample_bytree': 0.6470728331685501, 'min_child_weight': 9, 'gamma': 2.6813176235005654, 'reg_alpha': 2.6020195394300676, 'reg_lambda': 4.166377495666099e-06, 'max_delta_step': 1}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  66%|██████▋   | 133/200 [01:54<01:05,  1.02it/s]

[I 2025-11-10 18:21:05,273] Trial 131 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.14840164237423298, 'n_estimators': 1169, 'subsample': 0.5715411977285377, 'colsample_bytree': 0.8863271557307381, 'min_child_weight': 9, 'gamma': 3.5798690685749284, 'reg_alpha': 3.492299036565596e-06, 'reg_lambda': 5.0221509808426e-06, 'max_delta_step': 1}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  67%|██████▋   | 134/200 [01:55<01:07,  1.02s/it]

[I 2025-11-10 18:21:06,428] Trial 133 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.15066555929564207, 'n_estimators': 961, 'subsample': 0.6337106095531866, 'colsample_bytree': 0.6199995134781833, 'min_child_weight': 6, 'gamma': 2.237125817800819, 'reg_alpha': 0.00137161316733358, 'reg_lambda': 0.6754131247986325, 'max_delta_step': 8}. Best is trial 89 with value: 0.5611695906432749.
[I 2025-11-10 18:21:06,507] Trial 135 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04493753152118936, 'n_estimators': 324, 'subsample': 0.7225618479892488, 'colsample_bytree': 0.6198267546006551, 'min_child_weight': 9, 'gamma': 1.8677692342203618, 'reg_alpha': 3.9037395656009435e-06, 'reg_lambda': 2.1594003847335845e-07, 'max_delta_step': 9}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  68%|██████▊   | 136/200 [01:55<00:43,  1.46it/s]

[I 2025-11-10 18:21:06,835] Trial 136 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.049117150579170564, 'n_estimators': 316, 'subsample': 0.6139401496951823, 'colsample_bytree': 0.6198446779194273, 'min_child_weight': 9, 'gamma': 2.213317542016219, 'reg_alpha': 1.2075216397445585, 'reg_lambda': 8.402140140721085e-07, 'max_delta_step': 9}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  69%|██████▉   | 138/200 [01:56<00:37,  1.64it/s]

[I 2025-11-10 18:21:07,819] Trial 138 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1120662163074594, 'n_estimators': 279, 'subsample': 0.5209299678366144, 'colsample_bytree': 0.5930020461693525, 'min_child_weight': 7, 'gamma': 0.05616936519217669, 'reg_alpha': 4.5607587788739474e-05, 'reg_lambda': 0.0004812012618476197, 'max_delta_step': 9}. Best is trial 89 with value: 0.5611695906432749.
[I 2025-11-10 18:21:07,997] Trial 137 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.050197904723128906, 'n_estimators': 316, 'subsample': 0.6105818398689437, 'colsample_bytree': 0.5933672086576893, 'min_child_weight': 9, 'gamma': 0.036818739227043845, 'reg_alpha': 6.1254610254128096e-06, 'reg_lambda': 7.747070543771938, 'max_delta_step': 9}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  70%|██████▉   | 139/200 [01:57<00:32,  1.89it/s]

[I 2025-11-10 18:21:08,297] Trial 139 finished with value: 0.5312280701754386 and parameters: {'max_depth': 5, 'learning_rate': 0.10833981288375018, 'n_estimators': 273, 'subsample': 0.8663016848027352, 'colsample_bytree': 0.8774913986761137, 'min_child_weight': 5, 'gamma': 0.05308131673061944, 'reg_alpha': 4.4667318453362826e-05, 'reg_lambda': 6.5217823097316145, 'max_delta_step': 9}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  70%|███████   | 140/200 [01:57<00:27,  2.17it/s]

[I 2025-11-10 18:21:08,575] Trial 140 pruned.

Best trial: 89. Best value: 0.56117:  70%|███████   | 141/200 [01:57<00:24,  2.38it/s]

[I 2025-11-10 18:21:08,888] Trial 143 pruned.

Best trial: 89. Best value: 0.56117:  71%|███████   | 142/200 [01:58<00:22,  2.56it/s]

[I 2025-11-10 18:21:09,202] Trial 141 pruned.

Best trial: 89. Best value: 0.56117:  72%|███████▏  | 144/200 [01:58<00:16,  3.38it/s]

[I 2025-11-10 18:21:09,459] Trial 142 pruned.
[I 2025-11-10 18:21:09,619] Trial 145 pruned.

Best trial: 89. Best value: 0.56117:  72%|███████▎  | 145/200 [01:58<00:16,  3.29it/s]

[I 2025-11-10 18:21:09,942] Trial 146 pruned.

Best trial: 89. Best value: 0.56117:  73%|███████▎  | 146/200 [01:59<00:16,  3.19it/s]

[I 2025-11-10 18:21:10,278] Trial 134 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04753111938461372, 'n_estimators': 1137, 'subsample': 0.5732946336070804, 'colsample_bytree': 0.6198647060378866, 'min_child_weight': 9, 'gamma': 0.5019408679477817, 'reg_alpha': 2.9274790540297467e-05, 'reg_lambda': 2.0011099610124502e-07, 'max_delta_step': 9}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  74%|███████▎  | 147/200 [01:59<00:22,  2.36it/s]

[I 2025-11-10 18:21:10,967] Trial 147 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.18546212966526368, 'n_estimators': 274, 'subsample': 0.5964322965298225, 'colsample_bytree': 0.6272281676421373, 'min_child_weight': 6, 'gamma': 0.3859249707696785, 'reg_alpha': 3.227307055321043e-05, 'reg_lambda': 3.818730580587112e-08, 'max_delta_step': 9}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  74%|███████▍  | 148/200 [02:00<00:26,  1.97it/s]

[I 2025-11-10 18:21:11,666] Trial 148 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.018166935334744262, 'n_estimators': 347, 'subsample': 0.5641296094447005, 'colsample_bytree': 0.8787464673161336, 'min_child_weight': 6, 'gamma': 3.3562375874228083, 'reg_alpha': 3.42969901540706e-05, 'reg_lambda': 0.27407894654993803, 'max_delta_step': 8}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  74%|███████▍  | 149/200 [02:01<00:29,  1.72it/s]

[I 2025-11-10 18:21:12,429] Trial 151 pruned.

Best trial: 89. Best value: 0.56117:  75%|███████▌  | 150/200 [02:02<00:45,  1.09it/s]

[I 2025-11-10 18:21:14,127] Trial 144 finished with value: 0.5390058479532164 and parameters: {'max_depth': 5, 'learning_rate': 0.03369384801869199, 'n_estimators': 1130, 'subsample': 0.8609725253641057, 'colsample_bytree': 0.8791443437113554, 'min_child_weight': 5, 'gamma': 0.36167774427402305, 'reg_alpha': 1.2411846738063828e-05, 'reg_lambda': 0.00015644974608956954, 'max_delta_step': 9}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  76%|███████▌  | 151/200 [02:03<00:36,  1.33it/s]

[I 2025-11-10 18:21:14,494] Trial 150 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.08445501776226765, 'n_estimators': 784, 'subsample': 0.8688915952196956, 'colsample_bytree': 0.8387488158336464, 'min_child_weight': 7, 'gamma': 3.014330754797771, 'reg_alpha': 0.0001967278189612386, 'reg_lambda': 0.09293053829345235, 'max_delta_step': 8}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  76%|███████▌  | 152/200 [02:04<00:45,  1.05it/s]

[I 2025-11-10 18:21:15,908] Trial 149 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.021684171760824725, 'n_estimators': 1232, 'subsample': 0.6006881284387582, 'colsample_bytree': 0.8774835778113702, 'min_child_weight': 6, 'gamma': 3.0013183328386974, 'reg_alpha': 0.0001978567111432235, 'reg_lambda': 0.3740196457969276, 'max_delta_step': 8}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  76%|███████▋  | 153/200 [02:06<00:56,  1.20s/it]

[I 2025-11-10 18:21:17,703] Trial 152 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.11230770830284902, 'n_estimators': 1237, 'subsample': 0.8055917546599158, 'colsample_bytree': 0.6047678344931081, 'min_child_weight': 7, 'gamma': 3.1456194035962617, 'reg_alpha': 2.7375902839744113e-06, 'reg_lambda': 0.14321961732366814, 'max_delta_step': 2}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  77%|███████▋  | 154/200 [02:07<00:55,  1.20s/it]

[I 2025-11-10 18:21:18,895] Trial 153 finished with value: 0.5022222222222222 and parameters: {'max_depth': 8, 'learning_rate': 0.027238385123549085, 'n_estimators': 1053, 'subsample': 0.847366579646528, 'colsample_bytree': 0.923440092796161, 'min_child_weight': 5, 'gamma': 2.9240856133504867, 'reg_alpha': 2.6566623271130176e-06, 'reg_lambda': 2.0722783961699068e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  78%|███████▊  | 155/200 [02:08<00:47,  1.05s/it]

[I 2025-11-10 18:21:19,611] Trial 154 finished with value: 0.49000000000000005 and parameters: {'max_depth': 5, 'learning_rate': 0.032139155184287074, 'n_estimators': 1169, 'subsample': 0.8144172997718974, 'colsample_bytree': 0.8004628217286736, 'min_child_weight': 5, 'gamma': 0.24826887056405947, 'reg_alpha': 1.592515811095512e-05, 'reg_lambda': 0.00012694127957723917, 'max_delta_step': 10}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  78%|███████▊  | 156/200 [02:09<00:47,  1.09s/it]

[I 2025-11-10 18:21:20,776] Trial 155 finished with value: 0.5022222222222222 and parameters: {'max_depth': 5, 'learning_rate': 0.032756802593335056, 'n_estimators': 1101, 'subsample': 0.844304290865937, 'colsample_bytree': 0.9009528804659263, 'min_child_weight': 5, 'gamma': 0.3458130687043617, 'reg_alpha': 1.2799756228877381e-05, 'reg_lambda': 5.3586773622653966e-05, 'max_delta_step': 10}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  78%|███████▊  | 157/200 [02:11<00:59,  1.39s/it]

[I 2025-11-10 18:21:22,867] Trial 156 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.029448364688613716, 'n_estimators': 1192, 'subsample': 0.541961078673523, 'colsample_bytree': 0.9287513906430255, 'min_child_weight': 5, 'gamma': 0.31651691761031975, 'reg_alpha': 1.9565673812575245e-06, 'reg_lambda': 0.00012742699755367883, 'max_delta_step': 10}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  79%|███████▉  | 158/200 [02:12<00:46,  1.11s/it]

[I 2025-11-10 18:21:23,337] Trial 157 finished with value: 0.5022222222222222 and parameters: {'max_depth': 8, 'learning_rate': 0.038539092107289, 'n_estimators': 1039, 'subsample': 0.8437221813405232, 'colsample_bytree': 0.9294486129698316, 'min_child_weight': 5, 'gamma': 2.771488909349643, 'reg_alpha': 0.4581089642819028, 'reg_lambda': 0.0001260259486288546, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  80%|███████▉  | 159/200 [02:12<00:41,  1.01s/it]

[I 2025-11-10 18:21:24,121] Trial 158 finished with value: 0.5022222222222222 and parameters: {'max_depth': 8, 'learning_rate': 0.02413324495551887, 'n_estimators': 1052, 'subsample': 0.8487566372941429, 'colsample_bytree': 0.9415170259868714, 'min_child_weight': 5, 'gamma': 2.8305481253583618, 'reg_alpha': 1.693216874728871e-06, 'reg_lambda': 1.0060296029212352e-08, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  80%|████████  | 160/200 [02:14<00:42,  1.07s/it]

[I 2025-11-10 18:21:25,306] Trial 159 finished with value: 0.5055555555555555 and parameters: {'max_depth': 5, 'learning_rate': 0.026649633116315404, 'n_estimators': 1050, 'subsample': 0.8582152075495729, 'colsample_bytree': 0.9255108351547505, 'min_child_weight': 5, 'gamma': 2.775557034888069, 'reg_alpha': 2.045509031125804e-06, 'reg_lambda': 3.929687927847946e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  80%|████████  | 161/200 [02:16<00:56,  1.45s/it]

[I 2025-11-10 18:21:27,646] Trial 161 finished with value: 0.49000000000000005 and parameters: {'max_depth': 8, 'learning_rate': 0.027164939195117976, 'n_estimators': 1027, 'subsample': 0.8337230397620081, 'colsample_bytree': 0.9051258765866765, 'min_child_weight': 5, 'gamma': 2.7902990311615183, 'reg_alpha': 0.5185539996452228, 'reg_lambda': 0.00017560490087316008, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.
[I 2025-11-10 18:21:27,663] Trial 160 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.12490748751441078, 'n_estimators': 1098, 'subsample': 0.8367940303992655, 'colsample_bytree': 0.9215055224753123, 'min_child_weight': 5, 'gamma': 2.893270024088425, 'reg_alpha': 1.0587430029692162e-05, 'reg_lambda': 5.53533119993752e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  82%|████████▏ | 163/200 [02:17<00:39,  1.08s/it]

[I 2025-11-10 18:21:28,933] Trial 162 finished with value: 0.49000000000000005 and parameters: {'max_depth': 8, 'learning_rate': 0.027726647019264073, 'n_estimators': 1109, 'subsample': 0.8500315444834727, 'colsample_bytree': 0.9474995067284503, 'min_child_weight': 5, 'gamma': 2.800496479296232, 'reg_alpha': 0.958826238121401, 'reg_lambda': 2.189043286345239e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  82%|████████▏ | 164/200 [02:18<00:38,  1.06s/it]

[I 2025-11-10 18:21:29,962] Trial 163 finished with value: 0.5022222222222222 and parameters: {'max_depth': 5, 'learning_rate': 0.025532318172518085, 'n_estimators': 1056, 'subsample': 0.8418519916489371, 'colsample_bytree': 0.9555142754014817, 'min_child_weight': 5, 'gamma': 2.821361970801539, 'reg_alpha': 0.061078336377267624, 'reg_lambda': 3.8612768976648385e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  83%|████████▎ | 166/200 [02:21<00:35,  1.06s/it]

[I 2025-11-10 18:21:32,336] Trial 165 finished with value: 0.5022222222222222 and parameters: {'max_depth': 5, 'learning_rate': 0.02857379978605498, 'n_estimators': 1062, 'subsample': 0.8470846605981273, 'colsample_bytree': 0.950534530552213, 'min_child_weight': 5, 'gamma': 2.7218033601496554, 'reg_alpha': 0.23577283282773853, 'reg_lambda': 4.182247956020901e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.
[I 2025-11-10 18:21:32,454] Trial 164 finished with value: 0.5022222222222222 and parameters: {'max_depth': 5, 'learning_rate': 0.02772930200185643, 'n_estimators': 1111, 'subsample': 0.8431500077319715, 'colsample_bytree': 0.9257427147693741, 'min_child_weight': 5, 'gamma': 2.866944640647834, 'reg_alpha': 0.0672853978649661, 'reg_lambda': 6.165079778223685e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  84%|████████▎ | 167/200 [02:22<00:34,  1.06s/it]

[I 2025-11-10 18:21:33,506] Trial 166 finished with value: 0.5311111111111112 and parameters: {'max_depth': 5, 'learning_rate': 0.023845613586032335, 'n_estimators': 1047, 'subsample': 0.8641529170033491, 'colsample_bytree': 0.9302458181602742, 'min_child_weight': 5, 'gamma': 2.7228189181521234, 'reg_alpha': 0.21739164165980926, 'reg_lambda': 3.515045280871802e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  84%|████████▍ | 168/200 [02:23<00:33,  1.04s/it]

[I 2025-11-10 18:21:34,504] Trial 167 finished with value: 0.5022222222222222 and parameters: {'max_depth': 5, 'learning_rate': 0.024286885900806708, 'n_estimators': 1064, 'subsample': 0.843983708085571, 'colsample_bytree': 0.9579954816375869, 'min_child_weight': 5, 'gamma': 2.7128363867019583, 'reg_alpha': 1.4762673248211612e-06, 'reg_lambda': 7.611866979528112e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  85%|████████▌ | 170/200 [02:25<00:30,  1.03s/it]

[I 2025-11-10 18:21:36,811] Trial 168 finished with value: 0.5022222222222222 and parameters: {'max_depth': 5, 'learning_rate': 0.024641179085201522, 'n_estimators': 1047, 'subsample': 0.8426841722952421, 'colsample_bytree': 0.9369754927867512, 'min_child_weight': 5, 'gamma': 2.675074030549019, 'reg_alpha': 0.05973428976960396, 'reg_lambda': 4.324360912701522e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.
[I 2025-11-10 18:21:36,931] Trial 169 finished with value: 0.5022222222222222 and parameters: {'max_depth': 5, 'learning_rate': 0.02487592067724308, 'n_estimators': 1073, 'subsample': 0.8414709376325792, 'colsample_bytree': 0.9374008920008488, 'min_child_weight': 5, 'gamma': 2.896216300758549, 'reg_alpha': 0.07016515898090127, 'reg_lambda': 3.9411317508684206e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  86%|████████▌ | 171/200 [02:26<00:30,  1.06s/it]

[I 2025-11-10 18:21:38,050] Trial 170 finished with value: 0.5022222222222222 and parameters: {'max_depth': 5, 'learning_rate': 0.0246658479554745, 'n_estimators': 1056, 'subsample': 0.842366613999091, 'colsample_bytree': 0.9580954234408422, 'min_child_weight': 5, 'gamma': 2.63261479136875, 'reg_alpha': 0.02317482974499768, 'reg_lambda': 9.478689061827516e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  86%|████████▌ | 172/200 [02:27<00:29,  1.04s/it]

[I 2025-11-10 18:21:39,052] Trial 171 finished with value: 0.5022222222222222 and parameters: {'max_depth': 5, 'learning_rate': 0.023505212814194248, 'n_estimators': 1050, 'subsample': 0.8429685122994817, 'colsample_bytree': 0.9366060903115456, 'min_child_weight': 5, 'gamma': 2.6138976546818196, 'reg_alpha': 0.06280558979108844, 'reg_lambda': 4.330505824863932e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  86%|████████▋ | 173/200 [02:30<00:39,  1.45s/it]

[I 2025-11-10 18:21:41,457] Trial 173 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.023648253881303677, 'n_estimators': 1052, 'subsample': 0.8242689173789558, 'colsample_bytree': 0.959803978904274, 'min_child_weight': 5, 'gamma': 2.6026387731621456, 'reg_alpha': 0.15304344804561057, 'reg_lambda': 8.065242354301505e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.
[I 2025-11-10 18:21:41,497] Trial 172 finished with value: 0.5022222222222222 and parameters: {'max_depth': 5, 'learning_rate': 0.02363395616734304, 'n_estimators': 1054, 'subsample': 0.842694398259201, 'colsample_bytree': 0.9603475474972744, 'min_child_weight': 5, 'gamma': 2.6008410458163507, 'reg_alpha': 0.05550740256677128, 'reg_lambda': 9.30275356396266e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  88%|████████▊ | 175/200 [02:31<00:26,  1.07s/it]

[I 2025-11-10 18:21:42,715] Trial 174 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.022947570450984223, 'n_estimators': 1060, 'subsample': 0.8257394386445306, 'colsample_bytree': 0.9447048670561605, 'min_child_weight': 5, 'gamma': 2.716339582455282, 'reg_alpha': 0.04693424635382865, 'reg_lambda': 4.17222447670277e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  88%|████████▊ | 176/200 [02:32<00:25,  1.06s/it]

[I 2025-11-10 18:21:43,753] Trial 175 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.029272428962078736, 'n_estimators': 1072, 'subsample': 0.8223023385476246, 'colsample_bytree': 0.9435629256047242, 'min_child_weight': 5, 'gamma': 2.6834019329748373, 'reg_alpha': 0.20672671742450435, 'reg_lambda': 4.638057438269515e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  89%|████████▉ | 178/200 [02:35<00:22,  1.04s/it]

[I 2025-11-10 18:21:46,063] Trial 176 finished with value: 0.5211111111111111 and parameters: {'max_depth': 5, 'learning_rate': 0.02617961845745535, 'n_estimators': 1079, 'subsample': 0.8608337333029463, 'colsample_bytree': 0.9425886725190409, 'min_child_weight': 5, 'gamma': 2.7235302459355646, 'reg_alpha': 0.07524284648599812, 'reg_lambda': 4.3694828401544734e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.
[I 2025-11-10 18:21:46,184] Trial 177 finished with value: 0.5155555555555555 and parameters: {'max_depth': 5, 'learning_rate': 0.029481506480061547, 'n_estimators': 1085, 'subsample': 0.8639926613472811, 'colsample_bytree': 0.9476580853226363, 'min_child_weight': 5, 'gamma': 2.7141270402429853, 'reg_alpha': 0.08662906827004252, 'reg_lambda': 4.2006990790778656e-05, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  90%|████████▉ | 179/200 [02:35<00:20,  1.00it/s]

[I 2025-11-10 18:21:47,069] Trial 178 finished with value: 0.5155555555555555 and parameters: {'max_depth': 5, 'learning_rate': 0.029071650423286848, 'n_estimators': 1005, 'subsample': 0.8649967415529126, 'colsample_bytree': 0.9283817991010187, 'min_child_weight': 5, 'gamma': 2.8894084674394995, 'reg_alpha': 0.08914834979149058, 'reg_lambda': 0.0001818728844127517, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  90%|█████████ | 180/200 [02:36<00:20,  1.01s/it]

[I 2025-11-10 18:21:48,120] Trial 179 finished with value: 0.5211111111111111 and parameters: {'max_depth': 5, 'learning_rate': 0.025659663182234026, 'n_estimators': 1010, 'subsample': 0.8611486686147223, 'colsample_bytree': 0.9300814146330763, 'min_child_weight': 5, 'gamma': 2.4557592611844354, 'reg_alpha': 0.09484500495637099, 'reg_lambda': 0.00024438415916040474, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  90%|█████████ | 181/200 [02:39<00:26,  1.41s/it]

[I 2025-11-10 18:21:50,499] Trial 180 finished with value: 0.5211111111111111 and parameters: {'max_depth': 5, 'learning_rate': 0.028142846339544773, 'n_estimators': 1017, 'subsample': 0.860784426742027, 'colsample_bytree': 0.9249463643396735, 'min_child_weight': 5, 'gamma': 2.4712582444253703, 'reg_alpha': 0.0889479058164614, 'reg_lambda': 0.00022614334609778568, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  91%|█████████ | 182/200 [02:39<00:20,  1.16s/it]

[I 2025-11-10 18:21:51,060] Trial 181 finished with value: 0.5144444444444444 and parameters: {'max_depth': 5, 'learning_rate': 0.028498028787259495, 'n_estimators': 1113, 'subsample': 0.8591557188065692, 'colsample_bytree': 0.9274517615132771, 'min_child_weight': 5, 'gamma': 2.4729067831133467, 'reg_alpha': 0.09797585058278085, 'reg_lambda': 0.0002650486079260112, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  92%|█████████▏| 183/200 [02:40<00:15,  1.08it/s]

[I 2025-11-10 18:21:51,430] Trial 182 finished with value: 0.5211111111111111 and parameters: {'max_depth': 5, 'learning_rate': 0.028673922294134232, 'n_estimators': 1008, 'subsample': 0.8610450754561241, 'colsample_bytree': 0.9233878208621519, 'min_child_weight': 5, 'gamma': 2.3677386020618507, 'reg_alpha': 0.1146143660183842, 'reg_lambda': 0.00019035481034529653, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  92%|█████████▏| 184/200 [02:41<00:15,  1.00it/s]

[I 2025-11-10 18:21:52,586] Trial 183 finished with value: 0.5211111111111111 and parameters: {'max_depth': 5, 'learning_rate': 0.026204096655958395, 'n_estimators': 1008, 'subsample': 0.8612953953395139, 'colsample_bytree': 0.9250847888537028, 'min_child_weight': 5, 'gamma': 2.4556974175621926, 'reg_alpha': 0.1515280415323035, 'reg_lambda': 0.0006792309145042514, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  92%|█████████▎| 185/200 [02:43<00:20,  1.38s/it]

[I 2025-11-10 18:21:54,867] Trial 184 finished with value: 0.5177777777777778 and parameters: {'max_depth': 5, 'learning_rate': 0.026412486578656993, 'n_estimators': 1000, 'subsample': 0.8637702590006523, 'colsample_bytree': 0.9251403818530703, 'min_child_weight': 5, 'gamma': 2.862235061767148, 'reg_alpha': 0.1511004637956211, 'reg_lambda': 0.0001924658016454673, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  93%|█████████▎| 186/200 [02:44<00:16,  1.16s/it]

[I 2025-11-10 18:21:55,516] Trial 185 finished with value: 0.5144444444444444 and parameters: {'max_depth': 5, 'learning_rate': 0.03069316278181113, 'n_estimators': 995, 'subsample': 0.8590065880575826, 'colsample_bytree': 0.9143551285125726, 'min_child_weight': 5, 'gamma': 2.428773722638627, 'reg_alpha': 0.09625517782853209, 'reg_lambda': 0.0002964181967923706, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  94%|█████████▎| 187/200 [02:44<00:11,  1.12it/s]

[I 2025-11-10 18:21:55,770] Trial 186 finished with value: 0.5390058479532164 and parameters: {'max_depth': 5, 'learning_rate': 0.03153192558606255, 'n_estimators': 998, 'subsample': 0.8601974504224519, 'colsample_bytree': 0.9119526142950792, 'min_child_weight': 5, 'gamma': 2.389352017901966, 'reg_alpha': 0.039391245602290584, 'reg_lambda': 0.0009043370420673098, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  94%|█████████▍| 188/200 [02:45<00:11,  1.01it/s]

[I 2025-11-10 18:21:56,998] Trial 187 finished with value: 0.5211111111111111 and parameters: {'max_depth': 5, 'learning_rate': 0.02993291809518912, 'n_estimators': 1016, 'subsample': 0.8602808459372104, 'colsample_bytree': 0.9112173123179708, 'min_child_weight': 5, 'gamma': 2.4854155643870524, 'reg_alpha': 0.11793343664048915, 'reg_lambda': 0.00019722772183469145, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  94%|█████████▍| 189/200 [02:47<00:14,  1.30s/it]

[I 2025-11-10 18:21:59,026] Trial 188 finished with value: 0.5088888888888888 and parameters: {'max_depth': 5, 'learning_rate': 0.03094574882686187, 'n_estimators': 980, 'subsample': 0.8622854829461019, 'colsample_bytree': 0.9174755070550362, 'min_child_weight': 5, 'gamma': 2.384829717484982, 'reg_alpha': 0.10645127795824559, 'reg_lambda': 0.0007912580845514467, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  95%|█████████▌| 190/200 [02:48<00:11,  1.17s/it]

[I 2025-11-10 18:21:59,886] Trial 189 finished with value: 0.5155555555555555 and parameters: {'max_depth': 5, 'learning_rate': 0.02705396571953678, 'n_estimators': 994, 'subsample': 0.8628090203738141, 'colsample_bytree': 0.9128129176621353, 'min_child_weight': 5, 'gamma': 2.3669035420508058, 'reg_alpha': 0.11069678612525259, 'reg_lambda': 0.0009089653336527831, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  96%|█████████▌| 192/200 [02:49<00:05,  1.51it/s]

[I 2025-11-10 18:22:00,106] Trial 192 pruned.
[I 2025-11-10 18:22:00,249] Trial 190 finished with value: 0.5412280701754386 and parameters: {'max_depth': 5, 'learning_rate': 0.03086404146586674, 'n_estimators': 1003, 'subsample': 0.8614570480630676, 'colsample_bytree': 0.914648467487674, 'min_child_weight': 5, 'gamma': 2.482934092669812, 'reg_alpha': 0.12291207202710298, 'reg_lambda': 0.0007552925679202958, 'max_delta_step': 1}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  97%|█████████▋| 194/200 [02:50<00:03,  1.91it/s]

[I 2025-11-10 18:22:01,024] Trial 193 pruned.
[I 2025-11-10 18:22:01,145] Trial 194 pruned.

Best trial: 89. Best value: 0.56117:  98%|█████████▊| 195/200 [02:50<00:02,  2.48it/s]

[I 2025-11-10 18:22:01,265] Trial 195 pruned.

Best trial: 89. Best value: 0.56117:  98%|█████████▊| 196/200 [02:50<00:01,  2.54it/s]

[I 2025-11-10 18:22:01,636] Trial 191 finished with value: 0.5333333333333334 and parameters: {'max_depth': 5, 'learning_rate': 0.031404932987794044, 'n_estimators': 1001, 'subsample': 0.8683960388367913, 'colsample_bytree': 0.9019833497683264, 'min_child_weight': 5, 'gamma': 2.358870301953019, 'reg_alpha': 0.11393984053309493, 'reg_lambda': 0.0013649328754325042, 'max_delta_step': 0}. Best is trial 89 with value: 0.5611695906432749.

Best trial: 89. Best value: 0.56117:  99%|█████████▉| 198/200 [02:51<00:00,  2.45it/s]

[I 2025-11-10 18:22:02,083] Trial 196 pruned.
[I 2025-11-10 18:22:02,101] Trial 197 pruned.
[I 2025-11-10 18:22:02,165] Trial 198 pruned.

Best trial: 89. Best value: 0.56117: 100%|██████████| 200/200 [02:51<00:00,  1.17it/s]

[I 2025-11-10 18:22:02,347] Trial 199 pruned.

[I 2025-11-10 18:22:03,319] A new study created in memory with name: 16_1_roc_auc
Best trial: 3. Best value: 0.5:   0%|          | 1/200 [00:02<08:18,  2.50s/it]

[I 2025-11-10 18:22:05,814] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.12930070998911994, 'n_estimators': 661, 'subsample': 0.5612989699975525, 'colsample_bytree': 0.612828528636995, 'min_child_weight': 6, 'gamma': 2.8911937360588897, 'reg_alpha': 1.6102091783383878e-07, 'reg_lambda': 0.5580118589916889, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   1%|          | 2/200 [00:02<03:57,  1.20s/it]

[I 2025-11-10 18:22:06,103] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.023411727102069225, 'n_estimators': 707, 'subsample': 0.7733147245171585, 'colsample_bytree': 0.7570190990470052, 'min_child_weight': 9, 'gamma': 3.455443537033476, 'reg_alpha': 4.0828197335340417e-08, 'reg_lambda': 0.0047942819406833976, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 2. Best value: 0.516101:   2%|▏         | 4/200 [00:05<03:27,  1.06s/it]

[I 2025-11-10 18:22:08,347] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03618743324174674, 'n_estimators': 631, 'subsample': 0.9487237929617076, 'colsample_bytree': 0.8582885992204461, 'min_child_weight': 6, 'gamma': 0.887259993570701, 'reg_alpha': 0.0010965053826436835, 'reg_lambda': 0.0001881480510950493, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.
[I 2025-11-10 18:22:08,459] Trial 2 finished with value: 0.5161013645224172 and parameters: {'max_depth': 3, 'learning_rate': 0.04093248588177553, 'n_estimators': 734, 'subsample': 0.7002112597064876, 'colsample_bytree': 0.8732189761718179, 'min_child_weight': 1, 'gamma': 2.8201114466653605, 'reg_alpha': 0.0031285838988001917, 'reg_lambda': 0.0010602200080750963, 'max_delta_step': 7}. Best is trial 2 with value: 0.5161013645224172.

Best trial: 2. Best value: 0.516101:   2%|▎         | 5/200 [00:05<02:39,  1.22it/s]

[I 2025-11-10 18:22:08,854] Trial 0 finished with value: 0.4860623781676413 and parameters: {'max_depth': 5, 'learning_rate': 0.16839041181673226, 'n_estimators': 1382, 'subsample': 0.5636375321520559, 'colsample_bytree': 0.5824118130786968, 'min_child_weight': 2, 'gamma': 1.0117623847597124, 'reg_alpha': 0.001090258771051523, 'reg_lambda': 0.0006196003399010958, 'max_delta_step': 5}. Best is trial 2 with value: 0.5161013645224172.

Best trial: 2. Best value: 0.516101:   3%|▎         | 6/200 [00:07<03:48,  1.18s/it]

[I 2025-11-10 18:22:10,731] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1902574402948951, 'n_estimators': 1152, 'subsample': 0.9376496516851229, 'colsample_bytree': 0.9339247179744166, 'min_child_weight': 10, 'gamma': 0.039940844295472955, 'reg_alpha': 8.195522337790973e-05, 'reg_lambda': 0.08818411958185086, 'max_delta_step': 9}. Best is trial 2 with value: 0.5161013645224172.

Best trial: 8. Best value: 0.533236:   4%|▎         | 7/200 [00:08<03:17,  1.02s/it]

[I 2025-11-10 18:22:11,430] Trial 8 finished with value: 0.5332358674463937 and parameters: {'max_depth': 4, 'learning_rate': 0.047734893533192095, 'n_estimators': 571, 'subsample': 0.5760040800374144, 'colsample_bytree': 0.5821621826685102, 'min_child_weight': 3, 'gamma': 1.3449314616821062, 'reg_alpha': 1.044241102405335e-08, 'reg_lambda': 1.5746100893795396e-08, 'max_delta_step': 5}. Best is trial 8 with value: 0.5332358674463937.

Best trial: 8. Best value: 0.533236:   4%|▍         | 8/200 [00:10<04:15,  1.33s/it]

[I 2025-11-10 18:22:13,427] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.021548087345866135, 'n_estimators': 670, 'subsample': 0.7436741813194283, 'colsample_bytree': 0.7545762506558417, 'min_child_weight': 8, 'gamma': 4.882403104801271, 'reg_alpha': 0.00021693540648037686, 'reg_lambda': 2.857054700663148e-05, 'max_delta_step': 5}. Best is trial 8 with value: 0.5332358674463937.

Best trial: 8. Best value: 0.533236:   4%|▍         | 9/200 [00:10<03:08,  1.01it/s]

[I 2025-11-10 18:22:13,655] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.014935270066105134, 'n_estimators': 1264, 'subsample': 0.6754491709849784, 'colsample_bytree': 0.9322931523449578, 'min_child_weight': 8, 'gamma': 2.912928312670969, 'reg_alpha': 2.521395842879793e-06, 'reg_lambda': 4.004096714566791e-08, 'max_delta_step': 8}. Best is trial 8 with value: 0.5332358674463937.

Best trial: 8. Best value: 0.533236:   5%|▌         | 10/200 [00:11<02:53,  1.10it/s]

[I 2025-11-10 18:22:14,401] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.20486212801985224, 'n_estimators': 745, 'subsample': 0.6911251682246685, 'colsample_bytree': 0.760234013885012, 'min_child_weight': 5, 'gamma': 0.6776177443297071, 'reg_alpha': 0.0001651997654435538, 'reg_lambda': 0.00023232998152734028, 'max_delta_step': 2}. Best is trial 8 with value: 0.5332358674463937.

Best trial: 8. Best value: 0.533236:   6%|▌         | 12/200 [00:12<02:08,  1.46it/s]

[I 2025-11-10 18:22:15,327] Trial 13 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.07514870620446672, 'n_estimators': 220, 'subsample': 0.502613232222149, 'colsample_bytree': 0.5306681044471417, 'min_child_weight': 3, 'gamma': 1.7147496473880397, 'reg_alpha': 4.14577373075519, 'reg_lambda': 1.61483063229331e-08, 'max_delta_step': 0}. Best is trial 8 with value: 0.5332358674463937.
[I 2025-11-10 18:22:15,480] Trial 6 finished with value: 0.5294736842105262 and parameters: {'max_depth': 5, 'learning_rate': 0.06265175944875305, 'n_estimators': 1470, 'subsample': 0.685086561685993, 'colsample_bytree': 0.6362128802875616, 'min_child_weight': 1, 'gamma': 0.201561347000761, 'reg_alpha': 5.849125858278487e-06, 'reg_lambda': 3.218209797132698e-08, 'max_delta_step': 1}. Best is trial 8 with value: 0.5332358674463937.

Best trial: 8. Best value: 0.533236:   6%|▋         | 13/200 [00:12<01:49,  1.71it/s]

[I 2025-11-10 18:22:15,831] Trial 15 pruned.

Best trial: 8. Best value: 0.533236:   7%|▋         | 14/200 [00:14<03:05,  1.00it/s]

[I 2025-11-10 18:22:17,781] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1697916269246876, 'n_estimators': 1158, 'subsample': 0.6428480666018918, 'colsample_bytree': 0.7633197613393325, 'min_child_weight': 6, 'gamma': 3.0517651258651273, 'reg_alpha': 2.9512624635215467e-05, 'reg_lambda': 6.3500198422962785e-06, 'max_delta_step': 0}. Best is trial 8 with value: 0.5332358674463937.
[I 2025-11-10 18:22:17,845] Trial 14 finished with value: 0.5235477582846004 and parameters: {'max_depth': 3, 'learning_rate': 0.07203807806864927, 'n_estimators': 369, 'subsample': 0.6289952805762616, 'colsample_bytree': 0.6652606466478457, 'min_child_weight': 1, 'gamma': 2.2326577235700324, 'reg_alpha': 0.1611851161986883, 'reg_lambda': 4.843201609832517e-06, 'max_delta_step': 7}. Best is trial 8 with value: 0.5332358674463937.

Best trial: 16. Best value: 0.557485:   8%|▊         | 16/200 [00:17<03:53,  1.27s/it]

[I 2025-11-10 18:22:20,961] Trial 16 finished with value: 0.557485380116959 and parameters: {'max_depth': 10, 'learning_rate': 0.06461425204964807, 'n_estimators': 1020, 'subsample': 0.6107905901065664, 'colsample_bytree': 0.6817264139102553, 'min_child_weight': 1, 'gamma': 0.04582018163501722, 'reg_alpha': 8.741551495441225e-07, 'reg_lambda': 4.7465342436279275e-07, 'max_delta_step': 0}. Best is trial 16 with value: 0.557485380116959.

Best trial: 18. Best value: 0.597427:   8%|▊         | 17/200 [00:18<03:26,  1.13s/it]

[I 2025-11-10 18:22:21,662] Trial 18 finished with value: 0.5974269005847953 and parameters: {'max_depth': 6, 'learning_rate': 0.04931398245408023, 'n_estimators': 1020, 'subsample': 0.5863316374934415, 'colsample_bytree': 0.5013311697772854, 'min_child_weight': 4, 'gamma': 0.2878399829843079, 'reg_alpha': 1.5558961964091198e-06, 'reg_lambda': 2.1232029657313164e-07, 'max_delta_step': 3}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:   9%|▉         | 18/200 [00:18<02:40,  1.13it/s]

[I 2025-11-10 18:22:21,855] Trial 12 finished with value: 0.5338206627680311 and parameters: {'max_depth': 3, 'learning_rate': 0.01980460937894733, 'n_estimators': 1108, 'subsample': 0.6116490485724749, 'colsample_bytree': 0.939745904575797, 'min_child_weight': 1, 'gamma': 3.8847017989945813, 'reg_alpha': 0.09055239193568503, 'reg_lambda': 0.02389796651769187, 'max_delta_step': 6}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  10%|▉         | 19/200 [00:19<02:27,  1.22it/s]

[I 2025-11-10 18:22:22,493] Trial 17 finished with value: 0.5435282651072125 and parameters: {'max_depth': 4, 'learning_rate': 0.06781413990238985, 'n_estimators': 904, 'subsample': 0.6050275320770544, 'colsample_bytree': 0.6696548897077159, 'min_child_weight': 1, 'gamma': 0.09606906037309937, 'reg_alpha': 1.177634387043537e-06, 'reg_lambda': 2.734064801822406e-07, 'max_delta_step': 3}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  10%|█         | 20/200 [00:19<02:26,  1.23it/s]

[I 2025-11-10 18:22:23,299] Trial 19 pruned.

Best trial: 18. Best value: 0.597427:  10%|█         | 21/200 [00:20<02:32,  1.18it/s]

[I 2025-11-10 18:22:24,237] Trial 21 pruned.
[I 2025-11-10 18:22:24,245] Trial 20 pruned.

Best trial: 18. Best value: 0.597427:  12%|█▏        | 23/200 [00:21<01:50,  1.60it/s]

[I 2025-11-10 18:22:24,936] Trial 22 pruned.

Best trial: 18. Best value: 0.597427:  12%|█▏        | 24/200 [00:22<01:43,  1.70it/s]

[I 2025-11-10 18:22:25,412] Trial 25 pruned.

Best trial: 18. Best value: 0.597427:  12%|█▎        | 25/200 [00:22<01:37,  1.80it/s]

[I 2025-11-10 18:22:25,870] Trial 23 pruned.

Best trial: 18. Best value: 0.597427:  13%|█▎        | 26/200 [00:22<01:24,  2.06it/s]

[I 2025-11-10 18:22:26,166] Trial 26 pruned.

Best trial: 18. Best value: 0.597427:  14%|█▎        | 27/200 [00:26<03:58,  1.38s/it]

[I 2025-11-10 18:22:29,864] Trial 28 finished with value: 0.5246393762183235 and parameters: {'max_depth': 6, 'learning_rate': 0.059809921896447335, 'n_estimators': 798, 'subsample': 0.751522010435942, 'colsample_bytree': 0.8052517749945122, 'min_child_weight': 2, 'gamma': 1.1382253603472827, 'reg_alpha': 2.276905077004638e-06, 'reg_lambda': 2.148157705860817e-06, 'max_delta_step': 4}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  14%|█▍        | 28/200 [00:26<02:59,  1.04s/it]

[I 2025-11-10 18:22:30,066] Trial 29 finished with value: 0.5148927875243665 and parameters: {'max_depth': 6, 'learning_rate': 0.05315646983836328, 'n_estimators': 838, 'subsample': 0.775211540182265, 'colsample_bytree': 0.5720456529013734, 'min_child_weight': 2, 'gamma': 1.125797604015236, 'reg_alpha': 6.440273035663929e-08, 'reg_lambda': 1.6359697106425453e-06, 'max_delta_step': 4}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  14%|█▍        | 29/200 [00:27<02:36,  1.09it/s]

[I 2025-11-10 18:22:30,672] Trial 27 finished with value: 0.5565692007797272 and parameters: {'max_depth': 6, 'learning_rate': 0.055921428422808464, 'n_estimators': 846, 'subsample': 0.7421085459828181, 'colsample_bytree': 0.8050087860828523, 'min_child_weight': 2, 'gamma': 1.110225132249726, 'reg_alpha': 6.895329772373146e-08, 'reg_lambda': 7.206149739237564, 'max_delta_step': 1}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  15%|█▌        | 30/200 [00:28<02:47,  1.02it/s]

[I 2025-11-10 18:22:31,823] Trial 24 finished with value: 0.5597076023391813 and parameters: {'max_depth': 7, 'learning_rate': 0.028340075389154094, 'n_estimators': 1035, 'subsample': 0.6056403135805528, 'colsample_bytree': 0.6989760940428937, 'min_child_weight': 2, 'gamma': 0.10281865125619824, 'reg_alpha': 1.0798717839026336e-05, 'reg_lambda': 7.918789281581022, 'max_delta_step': 1}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  16%|█▌        | 31/200 [00:29<02:45,  1.02it/s]

[I 2025-11-10 18:22:32,787] Trial 30 pruned.

Best trial: 18. Best value: 0.597427:  16%|█▌        | 32/200 [00:29<02:09,  1.30it/s]

[I 2025-11-10 18:22:33,066] Trial 31 pruned.

Best trial: 18. Best value: 0.597427:  16%|█▋        | 33/200 [00:30<02:05,  1.33it/s]

[I 2025-11-10 18:22:33,762] Trial 35 pruned.

Best trial: 18. Best value: 0.597427:  17%|█▋        | 34/200 [00:30<01:45,  1.58it/s]

[I 2025-11-10 18:22:34,120] Trial 34 pruned.

Best trial: 18. Best value: 0.597427:  18%|█▊        | 35/200 [00:32<02:58,  1.08s/it]

[I 2025-11-10 18:22:36,257] Trial 32 finished with value: 0.5352046783625731 and parameters: {'max_depth': 8, 'learning_rate': 0.010363827473942069, 'n_estimators': 1291, 'subsample': 0.8608371091708948, 'colsample_bytree': 0.8867729230121852, 'min_child_weight': 5, 'gamma': 0.8727613829309384, 'reg_alpha': 1.2275265495999641e-07, 'reg_lambda': 1.6423282855418961, 'max_delta_step': 0}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  18%|█▊        | 36/200 [00:33<02:32,  1.08it/s]

[I 2025-11-10 18:22:36,822] Trial 33 finished with value: 0.5692397660818713 and parameters: {'max_depth': 8, 'learning_rate': 0.011094505257293788, 'n_estimators': 1281, 'subsample': 0.8718892184908329, 'colsample_bytree': 0.5615378072605389, 'min_child_weight': 5, 'gamma': 0.6753466543239577, 'reg_alpha': 0.0015923427754721156, 'reg_lambda': 7.07382916972781e-05, 'max_delta_step': 0}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  18%|█▊        | 37/200 [00:34<02:36,  1.04it/s]

[I 2025-11-10 18:22:37,857] Trial 39 pruned.

Best trial: 18. Best value: 0.597427:  20%|█▉        | 39/200 [00:35<02:29,  1.07it/s]

[I 2025-11-10 18:22:38,720] Trial 37 finished with value: 0.575204678362573 and parameters: {'max_depth': 6, 'learning_rate': 0.04177739003031618, 'n_estimators': 806, 'subsample': 0.7209634386776013, 'colsample_bytree': 0.7276711983882419, 'min_child_weight': 2, 'gamma': 1.5225392069180093, 'reg_alpha': 2.8705196204147948e-08, 'reg_lambda': 9.665213983211176, 'max_delta_step': 1}. Best is trial 18 with value: 0.5974269005847953.
[I 2025-11-10 18:22:38,746] Trial 36 finished with value: 0.5686159844054581 and parameters: {'max_depth': 6, 'learning_rate': 0.03753988887766307, 'n_estimators': 841, 'subsample': 0.5489098211482206, 'colsample_bytree': 0.9890039645421451, 'min_child_weight': 2, 'gamma': 1.5354165403688802, 'reg_alpha': 1.566901545698984e-07, 'reg_lambda': 8.280163266025527, 'max_delta_step': 0}. Best is trial 18 with value: 0.5974269005847953.
[I 2025-11-10 18:22:38,755] Trial 40 pruned.

Best trial: 18. Best value: 0.597427:  20%|██        | 41/200 [00:36<01:27,  1.82it/s]

[I 2025-11-10 18:22:39,476] Trial 43 pruned.

Best trial: 18. Best value: 0.597427:  21%|██        | 42/200 [00:36<01:19,  1.99it/s]

[I 2025-11-10 18:22:39,804] Trial 41 pruned.

Best trial: 18. Best value: 0.597427:  22%|██▏       | 43/200 [00:36<01:12,  2.17it/s]

[I 2025-11-10 18:22:40,133] Trial 42 pruned.

Best trial: 18. Best value: 0.597427:  22%|██▏       | 44/200 [00:37<01:29,  1.75it/s]

[I 2025-11-10 18:22:41,033] Trial 38 finished with value: 0.5656335282651072 and parameters: {'max_depth': 6, 'learning_rate': 0.0387753553891866, 'n_estimators': 815, 'subsample': 0.7228868267232951, 'colsample_bytree': 0.7240850904974296, 'min_child_weight': 2, 'gamma': 1.4422304670007735, 'reg_alpha': 3.4571442093625464e-08, 'reg_lambda': 0.20341444172369316, 'max_delta_step': 1}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  22%|██▎       | 45/200 [00:37<01:15,  2.06it/s]

[I 2025-11-10 18:22:41,278] Trial 45 pruned.

Best trial: 18. Best value: 0.597427:  23%|██▎       | 46/200 [00:38<01:21,  1.88it/s]

[I 2025-11-10 18:22:41,929] Trial 48 pruned.

Best trial: 18. Best value: 0.597427:  24%|██▎       | 47/200 [00:39<01:22,  1.85it/s]

[I 2025-11-10 18:22:42,493] Trial 49 pruned.

Best trial: 18. Best value: 0.597427:  24%|██▍       | 48/200 [00:41<02:17,  1.10it/s]

[I 2025-11-10 18:22:44,321] Trial 47 finished with value: 0.5521832358674463 and parameters: {'max_depth': 5, 'learning_rate': 0.038170414445789294, 'n_estimators': 708, 'subsample': 0.7250244203727066, 'colsample_bytree': 0.6274945579002977, 'min_child_weight': 3, 'gamma': 2.566147964303065, 'reg_alpha': 2.4039566582048228e-08, 'reg_lambda': 0.0050820524614892055, 'max_delta_step': 0}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  24%|██▍       | 49/200 [00:42<02:41,  1.07s/it]

[I 2025-11-10 18:22:45,784] Trial 46 finished with value: 0.5562573099415206 and parameters: {'max_depth': 5, 'learning_rate': 0.02365864797891022, 'n_estimators': 1374, 'subsample': 0.5483341554161367, 'colsample_bytree': 0.7310814338173472, 'min_child_weight': 3, 'gamma': 2.629140406892831, 'reg_alpha': 0.0005677100184395247, 'reg_lambda': 0.002893643977957341, 'max_delta_step': 0}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  25%|██▌       | 50/200 [00:42<02:06,  1.19it/s]

[I 2025-11-10 18:22:46,075] Trial 50 finished with value: 0.5471734892787523 and parameters: {'max_depth': 6, 'learning_rate': 0.044913781321946296, 'n_estimators': 511, 'subsample': 0.6725367877466366, 'colsample_bytree': 0.8443867901366136, 'min_child_weight': 1, 'gamma': 3.2545811156150446, 'reg_alpha': 0.0009450876261787149, 'reg_lambda': 0.8143798516117966, 'max_delta_step': 1}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  26%|██▌       | 51/200 [00:42<01:36,  1.55it/s]

[I 2025-11-10 18:22:46,253] Trial 44 finished with value: 0.5604483430799221 and parameters: {'max_depth': 6, 'learning_rate': 0.023507137925575808, 'n_estimators': 1498, 'subsample': 0.5446428151974776, 'colsample_bytree': 0.9974777144391442, 'min_child_weight': 3, 'gamma': 2.0704646199016628, 'reg_alpha': 1.8753057154386648e-08, 'reg_lambda': 0.004118251496093646, 'max_delta_step': 1}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  26%|██▌       | 52/200 [00:43<01:31,  1.62it/s]

[I 2025-11-10 18:22:46,800] Trial 53 pruned.

Best trial: 18. Best value: 0.597427:  26%|██▋       | 53/200 [00:45<02:11,  1.12it/s]

[I 2025-11-10 18:22:48,357] Trial 51 finished with value: 0.56953216374269 and parameters: {'max_depth': 6, 'learning_rate': 0.012364417457688506, 'n_estimators': 532, 'subsample': 0.5830033220754145, 'colsample_bytree': 0.782159023944877, 'min_child_weight': 1, 'gamma': 3.9233093832268784, 'reg_alpha': 0.04620964530443136, 'reg_lambda': 1.290892179164847, 'max_delta_step': 1}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  27%|██▋       | 54/200 [00:45<01:59,  1.22it/s]

[I 2025-11-10 18:22:48,999] Trial 56 pruned.

Best trial: 18. Best value: 0.597427:  28%|██▊       | 55/200 [00:46<01:42,  1.41it/s]

[I 2025-11-10 18:22:49,443] Trial 54 finished with value: 0.5756140350877194 and parameters: {'max_depth': 6, 'learning_rate': 0.011695211214378179, 'n_estimators': 798, 'subsample': 0.5886822840793773, 'colsample_bytree': 0.9638807398072835, 'min_child_weight': 4, 'gamma': 1.9788042617278068, 'reg_alpha': 1.68421581214526e-07, 'reg_lambda': 0.06650056269783022, 'max_delta_step': 2}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  28%|██▊       | 56/200 [00:46<01:38,  1.46it/s]

[I 2025-11-10 18:22:50,073] Trial 55 finished with value: 0.5025730994152047 and parameters: {'max_depth': 6, 'learning_rate': 0.012518213570988061, 'n_estimators': 817, 'subsample': 0.5840931564661076, 'colsample_bytree': 0.9705696222667676, 'min_child_weight': 4, 'gamma': 1.5832563621363689, 'reg_alpha': 1.2836804764517643e-07, 'reg_lambda': 0.0003531373602093028, 'max_delta_step': 1}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  28%|██▊       | 57/200 [00:47<01:27,  1.63it/s]

[I 2025-11-10 18:22:50,513] Trial 52 finished with value: 0.5505068226120857 and parameters: {'max_depth': 6, 'learning_rate': 0.011740854445978447, 'n_estimators': 546, 'subsample': 0.5801767503343886, 'colsample_bytree': 0.9687627543902456, 'min_child_weight': 1, 'gamma': 3.7857600640183318, 'reg_alpha': 6.747951632988152e-05, 'reg_lambda': 0.5183931036211019, 'max_delta_step': 6}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  29%|██▉       | 58/200 [00:47<01:17,  1.84it/s]

[I 2025-11-10 18:22:50,896] Trial 60 pruned.

Best trial: 18. Best value: 0.597427:  30%|██▉       | 59/200 [00:47<01:03,  2.22it/s]

[I 2025-11-10 18:22:51,127] Trial 58 finished with value: 0.5578362573099416 and parameters: {'max_depth': 5, 'learning_rate': 0.012902262782081097, 'n_estimators': 395, 'subsample': 0.5870988190837845, 'colsample_bytree': 0.947185460578315, 'min_child_weight': 4, 'gamma': 4.0391681850764325, 'reg_alpha': 0.03800801054263283, 'reg_lambda': 0.5170419194112169, 'max_delta_step': 2}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  30%|███       | 61/200 [00:48<00:48,  2.84it/s]

[I 2025-11-10 18:22:51,528] Trial 61 pruned.
[I 2025-11-10 18:22:51,686] Trial 62 pruned.

Best trial: 18. Best value: 0.597427:  31%|███       | 62/200 [00:48<00:41,  3.31it/s]

[I 2025-11-10 18:22:51,872] Trial 63 pruned.

Best trial: 18. Best value: 0.597427:  32%|███▏      | 63/200 [00:49<00:57,  2.36it/s]

[I 2025-11-10 18:22:52,576] Trial 64 pruned.

Best trial: 18. Best value: 0.597427:  32%|███▏      | 64/200 [00:50<01:31,  1.48it/s]

[I 2025-11-10 18:22:53,843] Trial 66 pruned.

Best trial: 18. Best value: 0.597427:  32%|███▎      | 65/200 [00:51<01:23,  1.62it/s]

[I 2025-11-10 18:22:54,324] Trial 59 finished with value: 0.5635867446393761 and parameters: {'max_depth': 7, 'learning_rate': 0.011649061174845475, 'n_estimators': 449, 'subsample': 0.6367383203102551, 'colsample_bytree': 0.961672225588666, 'min_child_weight': 1, 'gamma': 3.5503316339532374, 'reg_alpha': 1.649655691889316, 'reg_lambda': 0.5071778259911482, 'max_delta_step': 3}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  33%|███▎      | 66/200 [00:53<02:47,  1.25s/it]

[I 2025-11-10 18:22:57,055] Trial 57 finished with value: 0.5276608187134503 and parameters: {'max_depth': 5, 'learning_rate': 0.0119889910703757, 'n_estimators': 786, 'subsample': 0.5836143522654449, 'colsample_bytree': 0.9589366757694193, 'min_child_weight': 1, 'gamma': 1.5738801737187158, 'reg_alpha': 0.028245284658754248, 'reg_lambda': 0.5941785677230474, 'max_delta_step': 1}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  34%|███▎      | 67/200 [00:54<02:38,  1.19s/it]

[I 2025-11-10 18:22:58,096] Trial 69 pruned.

Best trial: 18. Best value: 0.597427:  34%|███▍      | 68/200 [00:55<02:08,  1.02it/s]

[I 2025-11-10 18:22:58,578] Trial 68 finished with value: 0.5373684210526316 and parameters: {'max_depth': 6, 'learning_rate': 0.034052497105331675, 'n_estimators': 885, 'subsample': 0.6788541624364306, 'colsample_bytree': 0.5018703323848566, 'min_child_weight': 2, 'gamma': 1.5459955775469445, 'reg_alpha': 5.666927152239315e-08, 'reg_lambda': 2.354149366395653, 'max_delta_step': 4}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  34%|███▍      | 69/200 [00:55<01:42,  1.28it/s]

[I 2025-11-10 18:22:58,913] Trial 65 finished with value: 0.5687914230019493 and parameters: {'max_depth': 6, 'learning_rate': 0.01440875976372065, 'n_estimators': 962, 'subsample': 0.77010083648144, 'colsample_bytree': 0.8562295732513504, 'min_child_weight': 2, 'gamma': 1.2471973120349598, 'reg_alpha': 2.4119281722908827e-07, 'reg_lambda': 2.9357961169133744, 'max_delta_step': 0}. Best is trial 18 with value: 0.5974269005847953.
[I 2025-11-10 18:22:58,935] Trial 70 pruned.

Best trial: 18. Best value: 0.597427:  36%|███▌      | 71/200 [00:55<01:05,  1.97it/s]

[I 2025-11-10 18:22:59,280] Trial 71 pruned.

Best trial: 18. Best value: 0.597427:  36%|███▋      | 73/200 [00:56<00:54,  2.31it/s]

[I 2025-11-10 18:22:59,862] Trial 72 pruned.
[I 2025-11-10 18:23:00,029] Trial 67 finished with value: 0.5633138401559454 and parameters: {'max_depth': 9, 'learning_rate': 0.031272833183707396, 'n_estimators': 1112, 'subsample': 0.6313984484927497, 'colsample_bytree': 0.7669931242782364, 'min_child_weight': 2, 'gamma': 1.2058758841492208, 'reg_alpha': 5.076178574868569e-08, 'reg_lambda': 2.3574581011504114, 'max_delta_step': 1}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  37%|███▋      | 74/200 [01:01<03:17,  1.57s/it]

[I 2025-11-10 18:23:04,652] Trial 73 finished with value: 0.5667836257309942 and parameters: {'max_depth': 9, 'learning_rate': 0.014338270089027475, 'n_estimators': 1100, 'subsample': 0.8811101695699392, 'colsample_bytree': 0.8285208763140149, 'min_child_weight': 4, 'gamma': 1.0011148872935887, 'reg_alpha': 2.8887627943217685e-06, 'reg_lambda': 5.52735991197723, 'max_delta_step': 0}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  38%|███▊      | 75/200 [01:02<03:18,  1.59s/it]

[I 2025-11-10 18:23:06,292] Trial 75 finished with value: 0.5775828460038986 and parameters: {'max_depth': 7, 'learning_rate': 0.010007679191995219, 'n_estimators': 982, 'subsample': 0.9320487612294573, 'colsample_bytree': 0.5242519471291891, 'min_child_weight': 2, 'gamma': 1.2796753797770746, 'reg_alpha': 1.0916856423490162e-07, 'reg_lambda': 3.626865608598952, 'max_delta_step': 1}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  38%|███▊      | 76/200 [01:03<02:42,  1.31s/it]

[I 2025-11-10 18:23:06,896] Trial 76 finished with value: 0.5582846003898636 and parameters: {'max_depth': 7, 'learning_rate': 0.010021094488012581, 'n_estimators': 933, 'subsample': 0.7945270039137378, 'colsample_bytree': 0.7136510810415843, 'min_child_weight': 2, 'gamma': 1.2786666756460074, 'reg_alpha': 1.055507136705501e-07, 'reg_lambda': 4.8010654175603165, 'max_delta_step': 1}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  38%|███▊      | 77/200 [01:03<02:02,  1.00it/s]

[I 2025-11-10 18:23:07,128] Trial 74 finished with value: 0.5854775828460039 and parameters: {'max_depth': 7, 'learning_rate': 0.01006488662444981, 'n_estimators': 988, 'subsample': 0.9181642775709692, 'colsample_bytree': 0.6705904524906909, 'min_child_weight': 2, 'gamma': 0.9903331655526464, 'reg_alpha': 1.2407644672728897e-07, 'reg_lambda': 3.9653351550677964, 'max_delta_step': 1}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  39%|███▉      | 78/200 [01:05<02:10,  1.07s/it]

[I 2025-11-10 18:23:08,386] Trial 79 pruned.

Best trial: 18. Best value: 0.597427:  40%|███▉      | 79/200 [01:05<01:38,  1.23it/s]

[I 2025-11-10 18:23:08,574] Trial 80 pruned.

Best trial: 18. Best value: 0.597427:  40%|████      | 80/200 [01:07<02:29,  1.24s/it]

[I 2025-11-10 18:23:10,837] Trial 77 finished with value: 0.545672514619883 and parameters: {'max_depth': 8, 'learning_rate': 0.010584142895976896, 'n_estimators': 984, 'subsample': 0.9324948708114216, 'colsample_bytree': 0.8355440394579613, 'min_child_weight': 4, 'gamma': 0.9077028678751488, 'reg_alpha': 5.061879384766828e-07, 'reg_lambda': 4.188967919237579, 'max_delta_step': 0}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  40%|████      | 81/200 [01:09<02:44,  1.38s/it]

[I 2025-11-10 18:23:12,552] Trial 78 finished with value: 0.5312280701754386 and parameters: {'max_depth': 7, 'learning_rate': 0.01033117287270961, 'n_estimators': 907, 'subsample': 0.9744194500756038, 'colsample_bytree': 0.5147024518031098, 'min_child_weight': 3, 'gamma': 0.6562869142507202, 'reg_alpha': 1.0001767157816353e-07, 'reg_lambda': 5.11068265351526, 'max_delta_step': 1}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  41%|████      | 82/200 [01:13<04:33,  2.32s/it]

[I 2025-11-10 18:23:17,078] Trial 81 finished with value: 0.5447173489278752 and parameters: {'max_depth': 7, 'learning_rate': 0.010825330728398608, 'n_estimators': 1052, 'subsample': 0.9262371017912076, 'colsample_bytree': 0.5772061260383926, 'min_child_weight': 1, 'gamma': 0.9776041199742636, 'reg_alpha': 1.1217500759140327e-06, 'reg_lambda': 1.2262625541575007, 'max_delta_step': 2}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  42%|████▏     | 83/200 [01:13<03:17,  1.69s/it]

[I 2025-11-10 18:23:17,294] Trial 82 finished with value: 0.5408576998050683 and parameters: {'max_depth': 7, 'learning_rate': 0.013528964881139858, 'n_estimators': 1061, 'subsample': 0.9880031872292451, 'colsample_bytree': 0.6779311062091459, 'min_child_weight': 1, 'gamma': 0.9412527643678179, 'reg_alpha': 2.476734603670075e-07, 'reg_lambda': 2.9606188328476315, 'max_delta_step': 3}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  42%|████▏     | 84/200 [01:14<02:40,  1.39s/it]

[I 2025-11-10 18:23:17,964] Trial 85 pruned.

Best trial: 18. Best value: 0.597427:  42%|████▎     | 85/200 [01:14<02:00,  1.05s/it]

[I 2025-11-10 18:23:18,234] Trial 86 pruned.

Best trial: 18. Best value: 0.597427:  43%|████▎     | 86/200 [01:16<02:08,  1.13s/it]

[I 2025-11-10 18:23:19,539] Trial 83 finished with value: 0.5132163742690058 and parameters: {'max_depth': 7, 'learning_rate': 0.013839710329764008, 'n_estimators': 1057, 'subsample': 0.9912540244675105, 'colsample_bytree': 0.6697531055924079, 'min_child_weight': 1, 'gamma': 0.3903094528050491, 'reg_alpha': 2.0251173831830967e-07, 'reg_lambda': 6.193137335841995e-07, 'max_delta_step': 3}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  44%|████▍     | 88/200 [01:17<01:32,  1.21it/s]

[I 2025-11-10 18:23:20,645] Trial 84 finished with value: 0.5231968810916179 and parameters: {'max_depth': 7, 'learning_rate': 0.013651324301509546, 'n_estimators': 1197, 'subsample': 0.9993408066645006, 'colsample_bytree': 0.6778641775520297, 'min_child_weight': 1, 'gamma': 1.7988250353296205, 'reg_alpha': 2.1555850898723886e-07, 'reg_lambda': 1.2069896377084655, 'max_delta_step': 1}. Best is trial 18 with value: 0.5974269005847953.
[I 2025-11-10 18:23:20,773] Trial 89 pruned.

Best trial: 18. Best value: 0.597427:  44%|████▍     | 89/200 [01:18<01:51,  1.00s/it]

[I 2025-11-10 18:23:22,194] Trial 91 pruned.

Best trial: 18. Best value: 0.597427:  45%|████▌     | 90/200 [01:19<01:39,  1.11it/s]

[I 2025-11-10 18:23:22,859] Trial 87 finished with value: 0.5706237816764133 and parameters: {'max_depth': 6, 'learning_rate': 0.018685795650460257, 'n_estimators': 849, 'subsample': 0.9603406945868607, 'colsample_bytree': 0.5403823643434332, 'min_child_weight': 2, 'gamma': 1.7951334656488953, 'reg_alpha': 8.907032726328251e-08, 'reg_lambda': 1.707960347447834, 'max_delta_step': 0}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  46%|████▌     | 91/200 [01:20<01:27,  1.24it/s]

[I 2025-11-10 18:23:23,443] Trial 92 pruned.

Best trial: 18. Best value: 0.597427:  46%|████▋     | 93/200 [01:20<00:54,  1.95it/s]

[I 2025-11-10 18:23:23,797] Trial 88 finished with value: 0.5349317738791423 and parameters: {'max_depth': 6, 'learning_rate': 0.02673158564866736, 'n_estimators': 837, 'subsample': 0.82783201773059, 'colsample_bytree': 0.9813138250684221, 'min_child_weight': 2, 'gamma': 2.0672853169413483, 'reg_alpha': 0.00035222756542853113, 'reg_lambda': 0.3207090087886344, 'max_delta_step': 0}. Best is trial 18 with value: 0.5974269005847953.
[I 2025-11-10 18:23:23,941] Trial 93 pruned.

Best trial: 18. Best value: 0.597427:  47%|████▋     | 94/200 [01:23<02:09,  1.22s/it]

[I 2025-11-10 18:23:26,807] Trial 90 finished with value: 0.544093567251462 and parameters: {'max_depth': 6, 'learning_rate': 0.018236761801851405, 'n_estimators': 851, 'subsample': 0.9499941707123591, 'colsample_bytree': 0.9855606834247489, 'min_child_weight': 2, 'gamma': 2.026895658901199, 'reg_alpha': 0.00040008587945447745, 'reg_lambda': 1.0089943112573163e-08, 'max_delta_step': 0}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  48%|████▊     | 95/200 [01:24<02:10,  1.25s/it]

[I 2025-11-10 18:23:28,116] Trial 94 finished with value: 0.5655555555555556 and parameters: {'max_depth': 6, 'learning_rate': 0.05709618078154312, 'n_estimators': 900, 'subsample': 0.9555910582646213, 'colsample_bytree': 0.5314101619253108, 'min_child_weight': 2, 'gamma': 1.6609959110801735, 'reg_alpha': 9.980509969699623e-08, 'reg_lambda': 1.8335577517007533, 'max_delta_step': 0}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  48%|████▊     | 96/200 [01:25<01:38,  1.06it/s]

[I 2025-11-10 18:23:28,362] Trial 95 finished with value: 0.5543469785575048 and parameters: {'max_depth': 6, 'learning_rate': 0.05449289401176624, 'n_estimators': 900, 'subsample': 0.9575655290799094, 'colsample_bytree': 0.545717568695957, 'min_child_weight': 2, 'gamma': 2.280557331095724, 'reg_alpha': 8.631204851595011e-08, 'reg_lambda': 1.8730575752524607, 'max_delta_step': 0}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  48%|████▊     | 97/200 [01:25<01:27,  1.17it/s]

[I 2025-11-10 18:23:28,999] Trial 96 finished with value: 0.5513645224171541 and parameters: {'max_depth': 6, 'learning_rate': 0.0416286516417665, 'n_estimators': 1002, 'subsample': 0.9478326005202306, 'colsample_bytree': 0.5322484707271365, 'min_child_weight': 2, 'gamma': 1.6474528720015627, 'reg_alpha': 8.34223436154824e-08, 'reg_lambda': 0.8590680769645841, 'max_delta_step': 5}. Best is trial 18 with value: 0.5974269005847953.

Best trial: 18. Best value: 0.597427:  49%|████▉     | 98/200 [01:26<01:19,  1.28it/s]

[I 2025-11-10 18:23:29,612] Trial 100 pruned.

Best trial: 18. Best value: 0.597427:  50%|████▉     | 99/200 [01:27<01:41,  1.00s/it]

[I 2025-11-10 18:23:31,133] Trial 101 pruned.

Best trial: 18. Best value: 0.597427:  50%|█████     | 100/200 [01:28<01:33,  1.07it/s]

[I 2025-11-10 18:23:31,898] Trial 102 pruned.

Best trial: 98. Best value: 0.611559:  50%|█████     | 101/200 [01:29<01:23,  1.19it/s]

[I 2025-11-10 18:23:32,529] Trial 98 finished with value: 0.6115594541910332 and parameters: {'max_depth': 6, 'learning_rate': 0.015466435611980196, 'n_estimators': 1012, 'subsample': 0.9710475762198232, 'colsample_bytree': 0.6535770080566055, 'min_child_weight': 5, 'gamma': 2.2560128475169514, 'reg_alpha': 3.38538678952146e-08, 'reg_lambda': 0.1498379840134802, 'max_delta_step': 5}. Best is trial 98 with value: 0.6115594541910332.

Best trial: 98. Best value: 0.611559:  51%|█████     | 102/200 [01:29<01:12,  1.36it/s]

[I 2025-11-10 18:23:33,026] Trial 97 finished with value: 0.5605068226120858 and parameters: {'max_depth': 6, 'learning_rate': 0.012563883209458818, 'n_estimators': 1007, 'subsample': 0.9655901873407265, 'colsample_bytree': 0.5363534363489496, 'min_child_weight': 2, 'gamma': 2.271824887518648, 'reg_alpha': 8.338564542172628e-08, 'reg_lambda': 0.6810536332230087, 'max_delta_step': 1}. Best is trial 98 with value: 0.6115594541910332.

Best trial: 98. Best value: 0.611559:  52%|█████▏    | 103/200 [01:30<01:16,  1.26it/s]

[I 2025-11-10 18:23:33,942] Trial 99 finished with value: 0.5878362573099416 and parameters: {'max_depth': 6, 'learning_rate': 0.015642102269194474, 'n_estimators': 1366, 'subsample': 0.9731554326157879, 'colsample_bytree': 0.5013626183120504, 'min_child_weight': 5, 'gamma': 1.157572259060876, 'reg_alpha': 1.7838314449952215e-08, 'reg_lambda': 0.8990706750026074, 'max_delta_step': 1}. Best is trial 98 with value: 0.6115594541910332.

Best trial: 98. Best value: 0.611559:  52%|█████▏    | 104/200 [01:33<02:09,  1.35s/it]

[I 2025-11-10 18:23:36,589] Trial 103 finished with value: 0.5439766081871344 and parameters: {'max_depth': 6, 'learning_rate': 0.011194940391624456, 'n_estimators': 752, 'subsample': 0.9675499060847459, 'colsample_bytree': 0.6526831555187234, 'min_child_weight': 3, 'gamma': 2.2207753248407958, 'reg_alpha': 3.4533043630909526e-08, 'reg_lambda': 0.712634780670105, 'max_delta_step': 1}. Best is trial 98 with value: 0.6115594541910332.

Best trial: 104. Best value: 0.619942:  52%|█████▎    | 105/200 [01:33<01:43,  1.08s/it]

[I 2025-11-10 18:23:37,058] Trial 104 finished with value: 0.6199415204678363 and parameters: {'max_depth': 6, 'learning_rate': 0.011371692361802141, 'n_estimators': 1034, 'subsample': 0.9657182866962445, 'colsample_bytree': 0.5063139149629812, 'min_child_weight': 5, 'gamma': 2.1841677847458203, 'reg_alpha': 3.450778993678898e-08, 'reg_lambda': 0.17231822681816591, 'max_delta_step': 7}. Best is trial 104 with value: 0.6199415204678363.

Best trial: 105. Best value: 0.62615:  53%|█████▎    | 106/200 [01:34<01:23,  1.12it/s]

[I 2025-11-10 18:23:37,490] Trial 105 finished with value: 0.626150097465887 and parameters: {'max_depth': 6, 'learning_rate': 0.011322748645483497, 'n_estimators': 1036, 'subsample': 0.892752645485539, 'colsample_bytree': 0.6573294616995176, 'min_child_weight': 5, 'gamma': 2.4501123482678313, 'reg_alpha': 4.560941170690872e-08, 'reg_lambda': 0.08148794294220513, 'max_delta_step': 5}. Best is trial 105 with value: 0.626150097465887.

Best trial: 105. Best value: 0.62615:  54%|█████▎    | 107/200 [01:36<01:58,  1.28s/it]

[I 2025-11-10 18:23:39,671] Trial 106 finished with value: 0.599317738791423 and parameters: {'max_depth': 6, 'learning_rate': 0.015240297555080896, 'n_estimators': 1331, 'subsample': 0.9776001663353399, 'colsample_bytree': 0.6478539849243414, 'min_child_weight': 5, 'gamma': 1.0671025524812194, 'reg_alpha': 1.212356708176035e-08, 'reg_lambda': 0.11137288147378457, 'max_delta_step': 5}. Best is trial 105 with value: 0.626150097465887.

Best trial: 105. Best value: 0.62615:  54%|█████▍    | 108/200 [01:38<02:21,  1.54s/it]

[I 2025-11-10 18:23:41,813] Trial 109 finished with value: 0.6024171539961014 and parameters: {'max_depth': 6, 'learning_rate': 0.0153388026299295, 'n_estimators': 1033, 'subsample': 0.9272019266927264, 'colsample_bytree': 0.5031164808951032, 'min_child_weight': 5, 'gamma': 2.6653686444164335, 'reg_alpha': 1.844151473558082e-08, 'reg_lambda': 0.09955853816224063, 'max_delta_step': 7}. Best is trial 105 with value: 0.626150097465887.

Best trial: 105. Best value: 0.62615:  55%|█████▍    | 109/200 [01:39<01:57,  1.29s/it]

[I 2025-11-10 18:23:42,527] Trial 107 finished with value: 0.602027290448343 and parameters: {'max_depth': 6, 'learning_rate': 0.015663856013688793, 'n_estimators': 1388, 'subsample': 0.9792943771689147, 'colsample_bytree': 0.5017318202253914, 'min_child_weight': 5, 'gamma': 1.2437701845893552, 'reg_alpha': 1.1964414851482339e-08, 'reg_lambda': 0.12210080664590851, 'max_delta_step': 7}. Best is trial 105 with value: 0.626150097465887.

Best trial: 105. Best value: 0.62615:  55%|█████▌    | 110/200 [01:39<01:34,  1.05s/it]

[I 2025-11-10 18:23:43,025] Trial 108 finished with value: 0.619317738791423 and parameters: {'max_depth': 5, 'learning_rate': 0.017246626734899503, 'n_estimators': 1393, 'subsample': 0.9821293568744741, 'colsample_bytree': 0.5059473827147118, 'min_child_weight': 5, 'gamma': 2.7138747081297256, 'reg_alpha': 1.3303961662079308e-08, 'reg_lambda': 0.09729280283790963, 'max_delta_step': 7}. Best is trial 105 with value: 0.626150097465887.

Best trial: 105. Best value: 0.62615:  56%|█████▌    | 111/200 [01:42<02:11,  1.48s/it]

[I 2025-11-10 18:23:45,512] Trial 110 finished with value: 0.6231384015594541 and parameters: {'max_depth': 5, 'learning_rate': 0.015443042070287438, 'n_estimators': 1349, 'subsample': 0.9767532562480938, 'colsample_bytree': 0.5017366314895736, 'min_child_weight': 5, 'gamma': 2.7221603262526406, 'reg_alpha': 1.2776923731718986e-08, 'reg_lambda': 0.1414849028724351, 'max_delta_step': 5}. Best is trial 105 with value: 0.626150097465887.

Best trial: 105. Best value: 0.62615:  56%|█████▌    | 112/200 [01:44<02:19,  1.59s/it]

[I 2025-11-10 18:23:47,346] Trial 111 finished with value: 0.617231968810916 and parameters: {'max_depth': 5, 'learning_rate': 0.01506100916357894, 'n_estimators': 1331, 'subsample': 0.9792704109756566, 'colsample_bytree': 0.5056422110535247, 'min_child_weight': 5, 'gamma': 2.4795390821441194, 'reg_alpha': 1.0376195154215034e-08, 'reg_lambda': 0.0455306934401962, 'max_delta_step': 7}. Best is trial 105 with value: 0.626150097465887.

Best trial: 105. Best value: 0.62615:  56%|█████▋    | 113/200 [01:44<01:55,  1.33s/it]

[I 2025-11-10 18:23:48,079] Trial 112 finished with value: 0.6030019493177388 and parameters: {'max_depth': 5, 'learning_rate': 0.022187777846352338, 'n_estimators': 1328, 'subsample': 0.9819918748478301, 'colsample_bytree': 0.5004687812559139, 'min_child_weight': 5, 'gamma': 2.7327513244160286, 'reg_alpha': 1.0555841568000336e-08, 'reg_lambda': 0.11196069615090755, 'max_delta_step': 7}. Best is trial 105 with value: 0.626150097465887.

Best trial: 105. Best value: 0.62615:  57%|█████▋    | 114/200 [01:45<01:41,  1.18s/it]

[I 2025-11-10 18:23:48,893] Trial 113 finished with value: 0.6230214424951267 and parameters: {'max_depth': 5, 'learning_rate': 0.015244567883767544, 'n_estimators': 1360, 'subsample': 0.9836406740986242, 'colsample_bytree': 0.5015250445958592, 'min_child_weight': 5, 'gamma': 2.7934125287697786, 'reg_alpha': 1.2627849065856066e-08, 'reg_lambda': 0.11389029558154576, 'max_delta_step': 7}. Best is trial 105 with value: 0.626150097465887.

Best trial: 105. Best value: 0.62615:  57%|█████▊    | 115/200 [01:48<02:16,  1.61s/it]

[I 2025-11-10 18:23:51,512] Trial 114 finished with value: 0.6180896686159845 and parameters: {'max_depth': 4, 'learning_rate': 0.02213876709748294, 'n_estimators': 1429, 'subsample': 0.9794298408515006, 'colsample_bytree': 0.5029941329401391, 'min_child_weight': 5, 'gamma': 2.467615558019466, 'reg_alpha': 1.3168573677012371e-08, 'reg_lambda': 0.12025200286786848, 'max_delta_step': 7}. Best is trial 105 with value: 0.626150097465887.

Best trial: 105. Best value: 0.62615:  58%|█████▊    | 116/200 [01:49<02:19,  1.66s/it]

[I 2025-11-10 18:23:53,302] Trial 115 finished with value: 0.6229044834307992 and parameters: {'max_depth': 4, 'learning_rate': 0.015181083334325593, 'n_estimators': 1377, 'subsample': 0.9786195134098381, 'colsample_bytree': 0.5061606358060726, 'min_child_weight': 5, 'gamma': 2.7133453599608544, 'reg_alpha': 1.2364521174320002e-08, 'reg_lambda': 0.12393704038830076, 'max_delta_step': 7}. Best is trial 105 with value: 0.626150097465887.

Best trial: 105. Best value: 0.62615:  58%|█████▊    | 117/200 [01:50<01:51,  1.34s/it]

[I 2025-11-10 18:23:53,887] Trial 116 finished with value: 0.612280701754386 and parameters: {'max_depth': 4, 'learning_rate': 0.017275326590765284, 'n_estimators': 1342, 'subsample': 0.9844574582804564, 'colsample_bytree': 0.5015090886718494, 'min_child_weight': 5, 'gamma': 2.727748028943634, 'reg_alpha': 1.1336391891872997e-08, 'reg_lambda': 0.10553683169446647, 'max_delta_step': 7}. Best is trial 105 with value: 0.626150097465887.

Best trial: 105. Best value: 0.62615:  59%|█████▉    | 118/200 [01:51<01:38,  1.20s/it]

[I 2025-11-10 18:23:54,747] Trial 117 finished with value: 0.617719298245614 and parameters: {'max_depth': 4, 'learning_rate': 0.01711784916204052, 'n_estimators': 1310, 'subsample': 0.9839253943979288, 'colsample_bytree': 0.5094570950758414, 'min_child_weight': 5, 'gamma': 2.7519750051355714, 'reg_alpha': 1.0192951716760464e-08, 'reg_lambda': 0.13958199668847007, 'max_delta_step': 7}. Best is trial 105 with value: 0.626150097465887.

Best trial: 105. Best value: 0.62615:  60%|█████▉    | 119/200 [01:52<01:38,  1.21s/it]

[I 2025-11-10 18:23:56,005] Trial 121 pruned.

Best trial: 105. Best value: 0.62615:  60%|██████    | 120/200 [01:53<01:39,  1.24s/it]

[I 2025-11-10 18:23:57,313] Trial 118 finished with value: 0.5897855750487329 and parameters: {'max_depth': 4, 'learning_rate': 0.022159181747475536, 'n_estimators': 1331, 'subsample': 0.9802914942896773, 'colsample_bytree': 0.5156647842642195, 'min_child_weight': 5, 'gamma': 2.695799230494162, 'reg_alpha': 1.0733299718848815e-08, 'reg_lambda': 0.11412350035198343, 'max_delta_step': 7}. Best is trial 105 with value: 0.626150097465887.

Best trial: 105. Best value: 0.62615:  60%|██████    | 121/200 [01:56<01:57,  1.49s/it]

[I 2025-11-10 18:23:59,368] Trial 119 finished with value: 0.622046783625731 and parameters: {'max_depth': 4, 'learning_rate': 0.016891962618606475, 'n_estimators': 1420, 'subsample': 0.9829502382541345, 'colsample_bytree': 0.5098246999107456, 'min_child_weight': 5, 'gamma': 2.7362250102796404, 'reg_alpha': 1.0423886248695426e-08, 'reg_lambda': 0.02949930138745863, 'max_delta_step': 7}. Best is trial 105 with value: 0.626150097465887.

Best trial: 105. Best value: 0.62615:  61%|██████    | 122/200 [01:56<01:38,  1.26s/it]

[I 2025-11-10 18:24:00,094] Trial 120 finished with value: 0.623391812865497 and parameters: {'max_depth': 4, 'learning_rate': 0.021649613516067034, 'n_estimators': 1420, 'subsample': 0.9875988855685219, 'colsample_bytree': 0.5146243989765017, 'min_child_weight': 5, 'gamma': 2.733309212589075, 'reg_alpha': 2.2721784232923334e-08, 'reg_lambda': 0.03733528347181635, 'max_delta_step': 7}. Best is trial 105 with value: 0.626150097465887.

Best trial: 122. Best value: 0.630936:  62%|██████▏   | 123/200 [01:58<01:41,  1.32s/it]

[I 2025-11-10 18:24:01,571] Trial 122 finished with value: 0.6309356725146199 and parameters: {'max_depth': 4, 'learning_rate': 0.017391630773337153, 'n_estimators': 1317, 'subsample': 0.9859487550347773, 'colsample_bytree': 0.5118248777558314, 'min_child_weight': 5, 'gamma': 3.2539276482039745, 'reg_alpha': 3.219962266965742e-08, 'reg_lambda': 0.18211028221491185, 'max_delta_step': 8}. Best is trial 122 with value: 0.6309356725146199.

Best trial: 123. Best value: 0.643528:  62%|██████▏   | 124/200 [01:59<01:37,  1.29s/it]

[I 2025-11-10 18:24:02,779] Trial 126 pruned.
[I 2025-11-10 18:24:02,817] Trial 123 finished with value: 0.6435282651072125 and parameters: {'max_depth': 3, 'learning_rate': 0.0171782185129396, 'n_estimators': 1313, 'subsample': 0.9895137505281503, 'colsample_bytree': 0.5107418395244546, 'min_child_weight': 5, 'gamma': 3.1822601057775715, 'reg_alpha': 2.6178261426301096e-08, 'reg_lambda': 0.06450464598899318, 'max_delta_step': 8}. Best is trial 123 with value: 0.6435282651072125.

Best trial: 123. Best value: 0.643528:  63%|██████▎   | 126/200 [02:01<01:28,  1.19s/it]

[I 2025-11-10 18:24:04,938] Trial 124 finished with value: 0.6301949317738792 and parameters: {'max_depth': 3, 'learning_rate': 0.01719222225724306, 'n_estimators': 1307, 'subsample': 0.9893362242079983, 'colsample_bytree': 0.5121265997805723, 'min_child_weight': 5, 'gamma': 2.762972206094752, 'reg_alpha': 2.7873559341662724e-08, 'reg_lambda': 0.05933344129121311, 'max_delta_step': 8}. Best is trial 123 with value: 0.6435282651072125.

Best trial: 123. Best value: 0.643528:  64%|██████▎   | 127/200 [02:02<01:27,  1.20s/it]

[I 2025-11-10 18:24:06,169] Trial 125 finished with value: 0.6242690058479532 and parameters: {'max_depth': 3, 'learning_rate': 0.01968278294053926, 'n_estimators': 1428, 'subsample': 0.9862398517385167, 'colsample_bytree': 0.5121291928460402, 'min_child_weight': 5, 'gamma': 2.508882775228657, 'reg_alpha': 2.5689320087642733e-08, 'reg_lambda': 0.05812827940177968, 'max_delta_step': 8}. Best is trial 123 with value: 0.6435282651072125.

Best trial: 123. Best value: 0.643528:  64%|██████▍   | 128/200 [02:04<01:28,  1.22s/it]

[I 2025-11-10 18:24:07,450] Trial 130 pruned.

Best trial: 123. Best value: 0.643528:  64%|██████▍   | 129/200 [02:05<01:32,  1.30s/it]

[I 2025-11-10 18:24:08,965] Trial 128 finished with value: 0.6316569200779727 and parameters: {'max_depth': 3, 'learning_rate': 0.017075419780093012, 'n_estimators': 1406, 'subsample': 0.9936234798590001, 'colsample_bytree': 0.527130035105787, 'min_child_weight': 5, 'gamma': 2.497642867161603, 'reg_alpha': 2.7806281713777742e-08, 'reg_lambda': 0.01856204728221395, 'max_delta_step': 8}. Best is trial 123 with value: 0.6435282651072125.

Best trial: 123. Best value: 0.643528:  65%|██████▌   | 130/200 [02:06<01:15,  1.08s/it]

[I 2025-11-10 18:24:09,487] Trial 127 finished with value: 0.6294541910331384 and parameters: {'max_depth': 4, 'learning_rate': 0.016979941562292582, 'n_estimators': 1492, 'subsample': 0.9864228805894523, 'colsample_bytree': 0.5255193047760073, 'min_child_weight': 5, 'gamma': 2.808274380880251, 'reg_alpha': 4.546327460486779e-08, 'reg_lambda': 0.01718833133272117, 'max_delta_step': 6}. Best is trial 123 with value: 0.6435282651072125.

Best trial: 123. Best value: 0.643528:  66%|██████▌   | 132/200 [02:07<00:55,  1.23it/s]

[I 2025-11-10 18:24:10,591] Trial 133 pruned.
[I 2025-11-10 18:24:10,734] Trial 129 finished with value: 0.6370955165692008 and parameters: {'max_depth': 3, 'learning_rate': 0.01712784502432873, 'n_estimators': 1295, 'subsample': 0.9969079803109315, 'colsample_bytree': 0.5246267436177677, 'min_child_weight': 5, 'gamma': 2.9674216603228527, 'reg_alpha': 2.826292936300046e-08, 'reg_lambda': 0.016523346898653302, 'max_delta_step': 8}. Best is trial 123 with value: 0.6435282651072125.

Best trial: 123. Best value: 0.643528:  66%|██████▋   | 133/200 [02:10<01:36,  1.44s/it]

[I 2025-11-10 18:24:13,688] Trial 131 finished with value: 0.6141325536062378 and parameters: {'max_depth': 3, 'learning_rate': 0.02073895906758928, 'n_estimators': 1407, 'subsample': 0.9431350228367431, 'colsample_bytree': 0.5527015513833223, 'min_child_weight': 5, 'gamma': 3.0948719602103263, 'reg_alpha': 2.7070158868559973e-08, 'reg_lambda': 0.011262898329338345, 'max_delta_step': 8}. Best is trial 123 with value: 0.6435282651072125.

Best trial: 123. Best value: 0.643528:  67%|██████▋   | 134/200 [02:11<01:19,  1.20s/it]

[I 2025-11-10 18:24:14,316] Trial 132 finished with value: 0.6079727095516569 and parameters: {'max_depth': 3, 'learning_rate': 0.020302789819345298, 'n_estimators': 1234, 'subsample': 0.9423483065922185, 'colsample_bytree': 0.5515098135700168, 'min_child_weight': 5, 'gamma': 3.406061517079554, 'reg_alpha': 2.7909335351722523e-08, 'reg_lambda': 0.011171029762579655, 'max_delta_step': 9}. Best is trial 123 with value: 0.6435282651072125.

Best trial: 123. Best value: 0.643528:  68%|██████▊   | 135/200 [02:11<01:10,  1.09s/it]

[I 2025-11-10 18:24:15,131] Trial 136 pruned.

Best trial: 123. Best value: 0.643528:  68%|██████▊   | 136/200 [02:12<01:00,  1.07it/s]

[I 2025-11-10 18:24:15,721] Trial 137 pruned.

Best trial: 135. Best value: 0.649727:  68%|██████▊   | 137/200 [02:13<01:02,  1.01it/s]

[I 2025-11-10 18:24:16,838] Trial 134 finished with value: 0.6427875243664717 and parameters: {'max_depth': 3, 'learning_rate': 0.01687357131659756, 'n_estimators': 1391, 'subsample': 0.9924981832300152, 'colsample_bytree': 0.521019060180308, 'min_child_weight': 5, 'gamma': 3.3555126559660486, 'reg_alpha': 4.935556622529595e-08, 'reg_lambda': 0.009613056880542536, 'max_delta_step': 6}. Best is trial 123 with value: 0.6435282651072125.
[I 2025-11-10 18:24:16,866] Trial 135 finished with value: 0.649727095516569 and parameters: {'max_depth': 3, 'learning_rate': 0.019916334362144898, 'n_estimators': 1461, 'subsample': 0.994594932442832, 'colsample_bytree': 0.5234578624839886, 'min_child_weight': 5, 'gamma': 3.2985246048176937, 'reg_alpha': 3.9898826311642615e-08, 'reg_lambda': 0.0061250022230064025, 'max_delta_step': 9}. Best is trial 135 with value: 0.649727095516569.

Best trial: 135. Best value: 0.649727:  70%|██████▉   | 139/200 [02:14<00:48,  1.26it/s]

[I 2025-11-10 18:24:17,969] Trial 141 pruned.

Best trial: 135. Best value: 0.649727:  70%|███████   | 140/200 [02:17<01:22,  1.38s/it]

[I 2025-11-10 18:24:21,131] Trial 138 finished with value: 0.609083820662768 and parameters: {'max_depth': 3, 'learning_rate': 0.017582956081696077, 'n_estimators': 1364, 'subsample': 0.9638670034098455, 'colsample_bytree': 0.5189555796512413, 'min_child_weight': 5, 'gamma': 2.8428775890487734, 'reg_alpha': 5.476185491484021e-08, 'reg_lambda': 0.021295626312469784, 'max_delta_step': 6}. Best is trial 135 with value: 0.649727095516569.
[I 2025-11-10 18:24:21,310] Trial 139 finished with value: 0.6281189083820662 and parameters: {'max_depth': 4, 'learning_rate': 0.2460406393017319, 'n_estimators': 1295, 'subsample': 0.9633589375400917, 'colsample_bytree': 0.5171172939607788, 'min_child_weight': 5, 'gamma': 2.9138599892576815, 'reg_alpha': 6.275008193418434e-08, 'reg_lambda': 0.02703398263952631, 'max_delta_step': 6}. Best is trial 135 with value: 0.649727095516569.

Best trial: 135. Best value: 0.649727:  71%|███████   | 142/200 [02:19<01:06,  1.15s/it]

[I 2025-11-10 18:24:22,666] Trial 140 finished with value: 0.604756335282651 and parameters: {'max_depth': 4, 'learning_rate': 0.018815212132995585, 'n_estimators': 1284, 'subsample': 0.9651473883784122, 'colsample_bytree': 0.5169410994384943, 'min_child_weight': 5, 'gamma': 2.5586370264615677, 'reg_alpha': 6.570033135516744e-08, 'reg_lambda': 0.01938878595984389, 'max_delta_step': 6}. Best is trial 135 with value: 0.649727095516569.

Best trial: 135. Best value: 0.649727:  72%|███████▏  | 143/200 [02:20<01:06,  1.17s/it]

[I 2025-11-10 18:24:23,892] Trial 142 finished with value: 0.6200487329434698 and parameters: {'max_depth': 3, 'learning_rate': 0.01953693767128055, 'n_estimators': 1358, 'subsample': 0.9651074281495081, 'colsample_bytree': 0.5343735404755079, 'min_child_weight': 5, 'gamma': 3.625703158668345, 'reg_alpha': 2.052944129660616e-08, 'reg_lambda': 0.039742324198559054, 'max_delta_step': 8}. Best is trial 135 with value: 0.649727095516569.

Best trial: 144. Best value: 0.676384:  72%|███████▏  | 144/200 [02:23<01:40,  1.79s/it]

[I 2025-11-10 18:24:27,237] Trial 144 finished with value: 0.6763840155945419 and parameters: {'max_depth': 3, 'learning_rate': 0.2746814931186174, 'n_estimators': 1364, 'subsample': 0.9530013326848659, 'colsample_bytree': 0.5370511155522081, 'min_child_weight': 5, 'gamma': 3.3096138719571013, 'reg_alpha': 2.380956500097338e-08, 'reg_lambda': 0.04112101510831578, 'max_delta_step': 8}. Best is trial 144 with value: 0.6763840155945419.

Best trial: 144. Best value: 0.676384:  72%|███████▎  | 145/200 [02:24<01:17,  1.41s/it]

[I 2025-11-10 18:24:27,706] Trial 143 finished with value: 0.6671345029239766 and parameters: {'max_depth': 3, 'learning_rate': 0.01889574779586624, 'n_estimators': 1486, 'subsample': 0.9657528336023321, 'colsample_bytree': 0.5323610881719142, 'min_child_weight': 5, 'gamma': 3.620362356459798, 'reg_alpha': 2.3888487666184288e-08, 'reg_lambda': 0.25425330212685654, 'max_delta_step': 8}. Best is trial 144 with value: 0.6763840155945419.

Best trial: 144. Best value: 0.676384:  73%|███████▎  | 146/200 [02:25<01:10,  1.31s/it]

[I 2025-11-10 18:24:28,788] Trial 145 finished with value: 0.6360331384015595 and parameters: {'max_depth': 3, 'learning_rate': 0.19590218562646874, 'n_estimators': 1357, 'subsample': 0.9917342774468346, 'colsample_bytree': 0.5311185960244468, 'min_child_weight': 5, 'gamma': 3.3607274819136332, 'reg_alpha': 2.070912012938748e-08, 'reg_lambda': 0.002666571845167099, 'max_delta_step': 8}. Best is trial 144 with value: 0.6763840155945419.

Best trial: 144. Best value: 0.676384:  74%|███████▎  | 147/200 [02:25<00:54,  1.03s/it]

[I 2025-11-10 18:24:29,139] Trial 148 pruned.

Best trial: 144. Best value: 0.676384:  74%|███████▍  | 148/200 [02:26<00:51,  1.00it/s]

[I 2025-11-10 18:24:30,067] Trial 149 pruned.

Best trial: 144. Best value: 0.676384:  75%|███████▌  | 150/200 [02:27<00:30,  1.65it/s]

[I 2025-11-10 18:24:30,391] Trial 150 pruned.
[I 2025-11-10 18:24:30,555] Trial 146 finished with value: 0.6638791423001948 and parameters: {'max_depth': 3, 'learning_rate': 0.15822880199633724, 'n_estimators': 1494, 'subsample': 0.9536745353558546, 'colsample_bytree': 0.5435284336533601, 'min_child_weight': 5, 'gamma': 3.3628038612991284, 'reg_alpha': 2.2312088227159258e-08, 'reg_lambda': 0.0646927546464184, 'max_delta_step': 8}. Best is trial 144 with value: 0.6763840155945419.

Best trial: 144. Best value: 0.676384:  76%|███████▌  | 151/200 [02:28<00:33,  1.44it/s]

[I 2025-11-10 18:24:31,443] Trial 151 pruned.

Best trial: 144. Best value: 0.676384:  76%|███████▌  | 152/200 [02:28<00:27,  1.75it/s]

[I 2025-11-10 18:24:31,732] Trial 152 pruned.

Best trial: 144. Best value: 0.676384:  76%|███████▋  | 153/200 [02:28<00:22,  2.10it/s]

[I 2025-11-10 18:24:31,986] Trial 153 pruned.

Best trial: 144. Best value: 0.676384:  77%|███████▋  | 154/200 [02:29<00:26,  1.73it/s]

[I 2025-11-10 18:24:32,794] Trial 154 pruned.

Best trial: 144. Best value: 0.676384:  78%|███████▊  | 155/200 [02:30<00:32,  1.37it/s]

[I 2025-11-10 18:24:33,880] Trial 147 finished with value: 0.6606432748538011 and parameters: {'max_depth': 3, 'learning_rate': 0.2695938378021833, 'n_estimators': 1480, 'subsample': 0.9530885119471426, 'colsample_bytree': 0.5457737003027693, 'min_child_weight': 5, 'gamma': 3.3066429395892762, 'reg_alpha': 2.546709258342505e-08, 'reg_lambda': 0.003003421500202443, 'max_delta_step': 8}. Best is trial 144 with value: 0.6763840155945419.

Best trial: 144. Best value: 0.676384:  78%|███████▊  | 156/200 [02:34<01:10,  1.59s/it]

[I 2025-11-10 18:24:37,497] Trial 156 finished with value: 0.5889181286549707 and parameters: {'max_depth': 3, 'learning_rate': 0.14764728800492713, 'n_estimators': 1301, 'subsample': 0.9590495440210445, 'colsample_bytree': 0.5475309806884807, 'min_child_weight': 5, 'gamma': 2.9401725223790844, 'reg_alpha': 2.9518516422018194e-08, 'reg_lambda': 0.03460887314529555, 'max_delta_step': 8}. Best is trial 144 with value: 0.6763840155945419.

Best trial: 144. Best value: 0.676384:  78%|███████▊  | 157/200 [02:34<00:55,  1.28s/it]

[I 2025-11-10 18:24:38,051] Trial 155 finished with value: 0.5815399610136451 and parameters: {'max_depth': 3, 'learning_rate': 0.1616347752981204, 'n_estimators': 1471, 'subsample': 0.9686688083808077, 'colsample_bytree': 0.5471437146566985, 'min_child_weight': 5, 'gamma': 3.0389374412091636, 'reg_alpha': 1.460926362884982e-07, 'reg_lambda': 0.03138672348001186, 'max_delta_step': 8}. Best is trial 144 with value: 0.6763840155945419.

Best trial: 144. Best value: 0.676384:  79%|███████▉  | 158/200 [02:35<00:49,  1.18s/it]

[I 2025-11-10 18:24:39,006] Trial 157 finished with value: 0.6338304093567252 and parameters: {'max_depth': 3, 'learning_rate': 0.20591538320031527, 'n_estimators': 1435, 'subsample': 0.9690118962562577, 'colsample_bytree': 0.5504739649900541, 'min_child_weight': 5, 'gamma': 2.942008403459867, 'reg_alpha': 2.625659723672479e-08, 'reg_lambda': 0.013157716848450351, 'max_delta_step': 8}. Best is trial 144 with value: 0.6763840155945419.

Best trial: 144. Best value: 0.676384:  80%|███████▉  | 159/200 [02:35<00:36,  1.12it/s]

[I 2025-11-10 18:24:39,226] Trial 160 pruned.

Best trial: 144. Best value: 0.676384:  80%|████████  | 160/200 [02:36<00:28,  1.41it/s]

[I 2025-11-10 18:24:39,503] Trial 158 finished with value: 0.621140350877193 and parameters: {'max_depth': 3, 'learning_rate': 0.14399036716883648, 'n_estimators': 1309, 'subsample': 0.9573315796324138, 'colsample_bytree': 0.5786990373747817, 'min_child_weight': 5, 'gamma': 3.4283849827131347, 'reg_alpha': 3.398630653543234e-08, 'reg_lambda': 0.011724089687943261, 'max_delta_step': 8}. Best is trial 144 with value: 0.6763840155945419.

Best trial: 144. Best value: 0.676384:  80%|████████  | 161/200 [02:36<00:28,  1.38it/s]

[I 2025-11-10 18:24:40,264] Trial 161 pruned.

Best trial: 144. Best value: 0.676384:  81%|████████  | 162/200 [02:37<00:25,  1.51it/s]

[I 2025-11-10 18:24:40,777] Trial 163 pruned.

Best trial: 144. Best value: 0.676384:  82%|████████▏ | 163/200 [02:40<00:48,  1.30s/it]

[I 2025-11-10 18:24:43,574] Trial 159 finished with value: 0.6064035087719298 and parameters: {'max_depth': 3, 'learning_rate': 0.20923702691384025, 'n_estimators': 1472, 'subsample': 0.8958009316463789, 'colsample_bytree': 0.5594129387697746, 'min_child_weight': 5, 'gamma': 3.072165033198181, 'reg_alpha': 4.0421986877028844e-08, 'reg_lambda': 0.013081448227852255, 'max_delta_step': 8}. Best is trial 144 with value: 0.6763840155945419.

Best trial: 144. Best value: 0.676384:  82%|████████▏ | 164/200 [02:42<00:53,  1.50s/it]

[I 2025-11-10 18:24:45,520] Trial 162 finished with value: 0.5964035087719298 and parameters: {'max_depth': 3, 'learning_rate': 0.21976892268478895, 'n_estimators': 1500, 'subsample': 0.8967739614684459, 'colsample_bytree': 0.5811800799644984, 'min_child_weight': 5, 'gamma': 3.0748296070806482, 'reg_alpha': 4.456455924831243e-08, 'reg_lambda': 0.009070633174957047, 'max_delta_step': 8}. Best is trial 144 with value: 0.6763840155945419.

Best trial: 144. Best value: 0.676384:  82%|████████▎ | 165/200 [02:43<00:46,  1.33s/it]

[I 2025-11-10 18:24:46,474] Trial 164 finished with value: 0.5797563352826511 and parameters: {'max_depth': 3, 'learning_rate': 0.22312054598337822, 'n_estimators': 1500, 'subsample': 0.9706763162433037, 'colsample_bytree': 0.5209487053545913, 'min_child_weight': 5, 'gamma': 3.0666216245387035, 'reg_alpha': 1.8693368384817996e-08, 'reg_lambda': 0.07078167431612381, 'max_delta_step': 8}. Best is trial 144 with value: 0.6763840155945419.
[I 2025-11-10 18:24:46,518] Trial 165 finished with value: 0.6017933723196881 and parameters: {'max_depth': 3, 'learning_rate': 0.20674444238699793, 'n_estimators': 1442, 'subsample': 0.9697789666814486, 'colsample_bytree': 0.5224811972827718, 'min_child_weight': 5, 'gamma': 3.0557894238116625, 'reg_alpha': 2.042785483971648e-08, 'reg_lambda': 0.007142804995267701, 'max_delta_step': 8}. Best is trial 144 with value: 0.6763840155945419.

Best trial: 144. Best value: 0.676384:  84%|████████▎ | 167/200 [02:44<00:33,  1.03s/it]

[I 2025-11-10 18:24:47,817] Trial 169 pruned.

Best trial: 166. Best value: 0.687476:  84%|████████▍ | 168/200 [02:46<00:39,  1.22s/it]

[I 2025-11-10 18:24:49,622] Trial 166 finished with value: 0.6874756335282652 and parameters: {'max_depth': 3, 'learning_rate': 0.20099890066093082, 'n_estimators': 1439, 'subsample': 0.9712305034961529, 'colsample_bytree': 0.5241747882615452, 'min_child_weight': 5, 'gamma': 3.7272502755043195, 'reg_alpha': 1.954257667167359e-08, 'reg_lambda': 0.07549348904372694, 'max_delta_step': 8}. Best is trial 166 with value: 0.6874756335282652.

Best trial: 166. Best value: 0.687476:  84%|████████▍ | 169/200 [02:48<00:45,  1.48s/it]

[I 2025-11-10 18:24:51,845] Trial 167 finished with value: 0.6060526315789473 and parameters: {'max_depth': 3, 'learning_rate': 0.23654609226453652, 'n_estimators': 1449, 'subsample': 0.971414485430602, 'colsample_bytree': 0.5229269153605344, 'min_child_weight': 5, 'gamma': 2.9113288639837, 'reg_alpha': 1.9117520271991483e-08, 'reg_lambda': 0.07809230780496251, 'max_delta_step': 9}. Best is trial 166 with value: 0.6874756335282652.

Best trial: 166. Best value: 0.687476:  85%|████████▌ | 170/200 [02:49<00:41,  1.37s/it]

[I 2025-11-10 18:24:52,905] Trial 168 finished with value: 0.6580896686159845 and parameters: {'max_depth': 3, 'learning_rate': 0.18643840774619935, 'n_estimators': 1434, 'subsample': 0.936515014049501, 'colsample_bytree': 0.524668995182162, 'min_child_weight': 5, 'gamma': 2.9469141058875894, 'reg_alpha': 1.8782442899798343e-08, 'reg_lambda': 0.0005439474855311178, 'max_delta_step': 9}. Best is trial 166 with value: 0.6874756335282652.

Best trial: 166. Best value: 0.687476:  86%|████████▌ | 171/200 [02:50<00:36,  1.26s/it]

[I 2025-11-10 18:24:53,871] Trial 170 finished with value: 0.6242884990253412 and parameters: {'max_depth': 3, 'learning_rate': 0.1837347318362227, 'n_estimators': 1412, 'subsample': 0.9369568156245129, 'colsample_bytree': 0.525273347110933, 'min_child_weight': 5, 'gamma': 2.36242832924873, 'reg_alpha': 2.6433876267818498e-08, 'reg_lambda': 0.059762593937897505, 'max_delta_step': 6}. Best is trial 166 with value: 0.6874756335282652.

Best trial: 166. Best value: 0.687476:  86%|████████▌ | 172/200 [02:52<00:38,  1.38s/it]

[I 2025-11-10 18:24:55,566] Trial 171 finished with value: 0.6254385964912281 and parameters: {'max_depth': 3, 'learning_rate': 0.18023721749989138, 'n_estimators': 1405, 'subsample': 0.9375082076533277, 'colsample_bytree': 0.5243691139549908, 'min_child_weight': 5, 'gamma': 4.151874312991037, 'reg_alpha': 1.6026377577786847e-08, 'reg_lambda': 0.0003869744032014806, 'max_delta_step': 9}. Best is trial 166 with value: 0.6874756335282652.

Best trial: 166. Best value: 0.687476:  86%|████████▋ | 173/200 [02:54<00:44,  1.65s/it]

[I 2025-11-10 18:24:57,869] Trial 172 finished with value: 0.6729727095516569 and parameters: {'max_depth': 3, 'learning_rate': 0.20083880300388837, 'n_estimators': 1403, 'subsample': 0.9481989418533464, 'colsample_bytree': 0.5508004643994152, 'min_child_weight': 5, 'gamma': 3.7211579959750543, 'reg_alpha': 2.8681324643270425e-08, 'reg_lambda': 0.02393608586567168, 'max_delta_step': 6}. Best is trial 166 with value: 0.6874756335282652.

Best trial: 166. Best value: 0.687476:  87%|████████▋ | 174/200 [02:55<00:37,  1.45s/it]

[I 2025-11-10 18:24:58,848] Trial 173 finished with value: 0.6290448343079922 and parameters: {'max_depth': 3, 'learning_rate': 0.18943313128720518, 'n_estimators': 1402, 'subsample': 0.9462417929407188, 'colsample_bytree': 0.5439139245631135, 'min_child_weight': 5, 'gamma': 3.337497628041449, 'reg_alpha': 1.846967716737426e-08, 'reg_lambda': 0.0004454733426951404, 'max_delta_step': 10}. Best is trial 166 with value: 0.6874756335282652.

Best trial: 166. Best value: 0.687476:  88%|████████▊ | 175/200 [02:56<00:30,  1.24s/it]

[I 2025-11-10 18:24:59,572] Trial 174 finished with value: 0.6740838206627681 and parameters: {'max_depth': 4, 'learning_rate': 0.19644776478296316, 'n_estimators': 1373, 'subsample': 0.94649801079283, 'colsample_bytree': 0.5471168636955748, 'min_child_weight': 5, 'gamma': 3.761833806030013, 'reg_alpha': 1.8161644752705528e-08, 'reg_lambda': 0.004793114524060649, 'max_delta_step': 10}. Best is trial 166 with value: 0.6874756335282652.

Best trial: 166. Best value: 0.687476:  88%|████████▊ | 176/200 [02:57<00:28,  1.19s/it]

[I 2025-11-10 18:25:00,666] Trial 178 pruned.

Best trial: 166. Best value: 0.687476:  88%|████████▊ | 177/200 [02:57<00:22,  1.04it/s]

[I 2025-11-10 18:25:01,088] Trial 175 finished with value: 0.5883625730994153 and parameters: {'max_depth': 4, 'learning_rate': 0.1647893022791932, 'n_estimators': 1326, 'subsample': 0.9606822273320478, 'colsample_bytree': 0.5472722074783591, 'min_child_weight': 5, 'gamma': 3.335904354991609, 'reg_alpha': 7.177021997014498e-08, 'reg_lambda': 0.00013315731792091723, 'max_delta_step': 10}. Best is trial 166 with value: 0.6874756335282652.

Best trial: 176. Best value: 0.695195:  89%|████████▉ | 178/200 [03:00<00:31,  1.41s/it]

[I 2025-11-10 18:25:03,560] Trial 176 finished with value: 0.695194931773879 and parameters: {'max_depth': 3, 'learning_rate': 0.19781147204694796, 'n_estimators': 1379, 'subsample': 0.9522055050671586, 'colsample_bytree': 0.5450748015607529, 'min_child_weight': 5, 'gamma': 3.7999964878939045, 'reg_alpha': 1.7074778604992228e-08, 'reg_lambda': 0.0014121571857730227, 'max_delta_step': 10}. Best is trial 176 with value: 0.695194931773879.

Best trial: 176. Best value: 0.695195:  90%|████████▉ | 179/200 [03:01<00:29,  1.39s/it]

[I 2025-11-10 18:25:04,908] Trial 177 finished with value: 0.6596393762183237 and parameters: {'max_depth': 3, 'learning_rate': 0.16511648324692527, 'n_estimators': 1433, 'subsample': 0.9457859459208834, 'colsample_bytree': 0.5478011847561012, 'min_child_weight': 5, 'gamma': 3.6968210521338047, 'reg_alpha': 1.702020091543072e-08, 'reg_lambda': 0.0001948822901656044, 'max_delta_step': 10}. Best is trial 176 with value: 0.695194931773879.

Best trial: 176. Best value: 0.695195:  90%|█████████ | 180/200 [03:02<00:27,  1.38s/it]

[I 2025-11-10 18:25:06,250] Trial 182 pruned.

Best trial: 176. Best value: 0.695195:  90%|█████████ | 181/200 [03:03<00:21,  1.13s/it]

[I 2025-11-10 18:25:06,782] Trial 179 finished with value: 0.6774756335282651 and parameters: {'max_depth': 3, 'learning_rate': 0.19674232215980708, 'n_estimators': 1433, 'subsample': 0.9291683361818124, 'colsample_bytree': 0.5611516430060823, 'min_child_weight': 5, 'gamma': 3.702623235629741, 'reg_alpha': 2.8241196465540823e-08, 'reg_lambda': 0.0016853075906923878, 'max_delta_step': 8}. Best is trial 176 with value: 0.695194931773879.

Best trial: 176. Best value: 0.695195:  91%|█████████ | 182/200 [03:03<00:16,  1.10it/s]

[I 2025-11-10 18:25:07,197] Trial 180 finished with value: 0.6594054580896687 and parameters: {'max_depth': 3, 'learning_rate': 0.20923629230739116, 'n_estimators': 1438, 'subsample': 0.9741531200864707, 'colsample_bytree': 0.5331887472734409, 'min_child_weight': 5, 'gamma': 3.658446187617241, 'reg_alpha': 2.9979948343008054e-08, 'reg_lambda': 0.0020245426476264788, 'max_delta_step': 8}. Best is trial 176 with value: 0.695194931773879.

Best trial: 176. Best value: 0.695195:  92%|█████████▏| 183/200 [03:04<00:15,  1.12it/s]

[I 2025-11-10 18:25:08,041] Trial 184 pruned.

Best trial: 176. Best value: 0.695195:  92%|█████████▏| 184/200 [03:05<00:11,  1.34it/s]

[I 2025-11-10 18:25:08,451] Trial 185 pruned.

Best trial: 176. Best value: 0.695195:  92%|█████████▎| 185/200 [03:06<00:12,  1.17it/s]

[I 2025-11-10 18:25:09,545] Trial 181 finished with value: 0.6364327485380116 and parameters: {'max_depth': 3, 'learning_rate': 0.2032934687837265, 'n_estimators': 1349, 'subsample': 0.9309876487761218, 'colsample_bytree': 0.5619567118322257, 'min_child_weight': 5, 'gamma': 3.8573946439761495, 'reg_alpha': 3.025481368133916e-08, 'reg_lambda': 0.002057377451525768, 'max_delta_step': 10}. Best is trial 176 with value: 0.695194931773879.

Best trial: 176. Best value: 0.695195:  93%|█████████▎| 186/200 [03:08<00:19,  1.40s/it]

[I 2025-11-10 18:25:12,213] Trial 183 finished with value: 0.5894736842105264 and parameters: {'max_depth': 3, 'learning_rate': 0.2047028981425532, 'n_estimators': 1382, 'subsample': 0.9152723774707019, 'colsample_bytree': 0.5704768739979323, 'min_child_weight': 5, 'gamma': 3.8794833992273317, 'reg_alpha': 2.7786566626925738e-08, 'reg_lambda': 0.0011784988317143897, 'max_delta_step': 10}. Best is trial 176 with value: 0.695194931773879.

Best trial: 176. Best value: 0.695195:  94%|█████████▎| 187/200 [03:10<00:18,  1.43s/it]

[I 2025-11-10 18:25:13,737] Trial 186 finished with value: 0.5934502923976608 and parameters: {'max_depth': 3, 'learning_rate': 0.14923029816042402, 'n_estimators': 1381, 'subsample': 0.9236703075791276, 'colsample_bytree': 0.568574879238232, 'min_child_weight': 5, 'gamma': 3.872605724475539, 'reg_alpha': 1.679836861725727e-08, 'reg_lambda': 0.0036943769218608807, 'max_delta_step': 10}. Best is trial 176 with value: 0.695194931773879.

Best trial: 176. Best value: 0.695195:  94%|█████████▍| 188/200 [03:11<00:14,  1.20s/it]

[I 2025-11-10 18:25:14,376] Trial 187 finished with value: 0.5854288499025342 and parameters: {'max_depth': 3, 'learning_rate': 0.14131909046940686, 'n_estimators': 1437, 'subsample': 0.9270100909781881, 'colsample_bytree': 0.5700893907108615, 'min_child_weight': 5, 'gamma': 3.5624436119941527, 'reg_alpha': 1.5595894614343668e-08, 'reg_lambda': 0.0005631899703736054, 'max_delta_step': 9}. Best is trial 176 with value: 0.695194931773879.

Best trial: 176. Best value: 0.695195:  94%|█████████▍| 189/200 [03:12<00:13,  1.20s/it]

[I 2025-11-10 18:25:15,583] Trial 191 pruned.
[I 2025-11-10 18:25:15,627] Trial 188 finished with value: 0.5778947368421052 and parameters: {'max_depth': 3, 'learning_rate': 0.1454369891184367, 'n_estimators': 1459, 'subsample': 0.9228335570868539, 'colsample_bytree': 0.5605755729539222, 'min_child_weight': 5, 'gamma': 3.863740534004839, 'reg_alpha': 1.744414318595387e-08, 'reg_lambda': 0.0005855480013220196, 'max_delta_step': 10}. Best is trial 176 with value: 0.695194931773879.

Best trial: 176. Best value: 0.695195:  96%|█████████▌| 191/200 [03:15<00:12,  1.35s/it]

[I 2025-11-10 18:25:18,634] Trial 189 finished with value: 0.5884892787524366 and parameters: {'max_depth': 3, 'learning_rate': 0.17279814045931846, 'n_estimators': 1436, 'subsample': 0.9249321395507465, 'colsample_bytree': 0.5571677539423167, 'min_child_weight': 5, 'gamma': 3.5485303061156475, 'reg_alpha': 1.7622957503395186e-08, 'reg_lambda': 0.0022828467947404486, 'max_delta_step': 9}. Best is trial 176 with value: 0.695194931773879.

Best trial: 176. Best value: 0.695195:  96%|█████████▌| 192/200 [03:16<00:11,  1.41s/it]

[I 2025-11-10 18:25:20,210] Trial 190 finished with value: 0.6493469785575048 and parameters: {'max_depth': 3, 'learning_rate': 0.17269430388020585, 'n_estimators': 1459, 'subsample': 0.9452383312087007, 'colsample_bytree': 0.5552469768502627, 'min_child_weight': 5, 'gamma': 3.5639871707053983, 'reg_alpha': 1.5068193958780963e-08, 'reg_lambda': 0.0022230593865139774, 'max_delta_step': 9}. Best is trial 176 with value: 0.695194931773879.

Best trial: 192. Best value: 0.696248:  96%|█████████▋| 193/200 [03:18<00:10,  1.46s/it]

[I 2025-11-10 18:25:21,831] Trial 192 finished with value: 0.6962475633528266 and parameters: {'max_depth': 3, 'learning_rate': 0.22356714784008044, 'n_estimators': 1422, 'subsample': 0.9519008219698468, 'colsample_bytree': 0.5511364361754173, 'min_child_weight': 5, 'gamma': 3.801665007602567, 'reg_alpha': 3.789368184281951e-08, 'reg_lambda': 0.001879526796151609, 'max_delta_step': 9}. Best is trial 192 with value: 0.6962475633528266.
[I 2025-11-10 18:25:21,874] Trial 193 finished with value: 0.6321052631578947 and parameters: {'max_depth': 3, 'learning_rate': 0.17228768559537902, 'n_estimators': 1424, 'subsample': 0.9479547577939808, 'colsample_bytree': 0.5477907935529058, 'min_child_weight': 5, 'gamma': 4.1863242071717455, 'reg_alpha': 3.6587813845183186e-08, 'reg_lambda': 0.0017456670631115466, 'max_delta_step': 9}. Best is trial 192 with value: 0.6962475633528266.

Best trial: 192. Best value: 0.696248:  98%|█████████▊| 195/200 [03:21<00:07,  1.43s/it]

[I 2025-11-10 18:25:24,610] Trial 194 finished with value: 0.6342105263157893 and parameters: {'max_depth': 3, 'learning_rate': 0.22658157471169404, 'n_estimators': 1414, 'subsample': 0.9494643393474523, 'colsample_bytree': 0.5378607246052985, 'min_child_weight': 5, 'gamma': 4.008612039073603, 'reg_alpha': 3.53419367943337e-08, 'reg_lambda': 0.00396502425507827, 'max_delta_step': 8}. Best is trial 192 with value: 0.6962475633528266.

Best trial: 192. Best value: 0.696248:  98%|█████████▊| 196/200 [03:23<00:06,  1.51s/it]

[I 2025-11-10 18:25:26,384] Trial 195 finished with value: 0.6285380116959065 and parameters: {'max_depth': 3, 'learning_rate': 0.12984105668372514, 'n_estimators': 1465, 'subsample': 0.9483607407953024, 'colsample_bytree': 0.5464600756253937, 'min_child_weight': 5, 'gamma': 4.035720308296695, 'reg_alpha': 3.408726585007344e-08, 'reg_lambda': 0.0016329728765967714, 'max_delta_step': 9}. Best is trial 192 with value: 0.6962475633528266.

Best trial: 192. Best value: 0.696248:  98%|█████████▊| 197/200 [03:24<00:04,  1.41s/it]

[I 2025-11-10 18:25:27,493] Trial 197 finished with value: 0.6460623781676412 and parameters: {'max_depth': 3, 'learning_rate': 0.2250647565517384, 'n_estimators': 1346, 'subsample': 0.9350452198650671, 'colsample_bytree': 0.5381450111423073, 'min_child_weight': 5, 'gamma': 3.7344715969008977, 'reg_alpha': 4.7385730055948946e-08, 'reg_lambda': 0.005033834537689332, 'max_delta_step': 9}. Best is trial 192 with value: 0.6962475633528266.
[I 2025-11-10 18:25:27,493] Trial 196 finished with value: 0.6309941520467837 and parameters: {'max_depth': 3, 'learning_rate': 0.1905795720204256, 'n_estimators': 1358, 'subsample': 0.9469723603640618, 'colsample_bytree': 0.5425248557235577, 'min_child_weight': 5, 'gamma': 4.017811748079139, 'reg_alpha': 4.656223814485194e-08, 'reg_lambda': 0.0015502077125174698, 'max_delta_step': 9}. Best is trial 192 with value: 0.6962475633528266.

Best trial: 192. Best value: 0.696248: 100%|█████████▉| 199/200 [03:25<00:01,  1.15s/it]

[I 2025-11-10 18:25:29,080] Trial 198 finished with value: 0.6380311890838206 and parameters: {'max_depth': 3, 'learning_rate': 0.19348559925013753, 'n_estimators': 1359, 'subsample': 0.9347812762944134, 'colsample_bytree': 0.5364930086425509, 'min_child_weight': 5, 'gamma': 3.7651596316120677, 'reg_alpha': 5.567024389358937e-08, 'reg_lambda': 0.0014599298906138821, 'max_delta_step': 9}. Best is trial 192 with value: 0.6962475633528266.

Best trial: 192. Best value: 0.696248: 100%|██████████| 200/200 [03:26<00:00,  1.03s/it]

[I 2025-11-10 18:25:29,883] Trial 199 finished with value: 0.6183430799220273 and parameters: {'max_depth': 3, 'learning_rate': 0.19228646112093647, 'n_estimators': 1353, 'subsample': 0.9368601120585772, 'colsample_bytree': 0.5347908856852647, 'min_child_weight': 5, 'gamma': 3.7583093327996466, 'reg_alpha': 1.0060921506841844e-08, 'reg_lambda': 0.0002876552666792445, 'max_delta_step': 9}. Best is trial 192 with value: 0.6962475633528266.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\utils\_plotting.py:28: RuntimeWarning:

More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.

[I 2025-11-10 18:25:30,975] A new study created in memory with name: 17_1_roc_auc
Best trial: 1. Best value: 0.57655:   0%|          | 1/200 [00:02<08:30,  2.57s/it]

[I 2025-11-10 18:25:33,537] Trial 1 finished with value: 0.5765497076023391 and parameters: {'max_depth': 5, 'learning_rate': 0.034618212784378516, 'n_estimators': 520, 'subsample': 0.635361966883861, 'colsample_bytree': 0.5302865247588979, 'min_child_weight': 2, 'gamma': 4.875896329216617, 'reg_alpha': 4.21309723552203e-06, 'reg_lambda': 0.001558443994754288, 'max_delta_step': 8}. Best is trial 1 with value: 0.5765497076023391.

Best trial: 1. Best value: 0.57655:   1%|          | 2/200 [00:03<04:28,  1.36s/it]

[I 2025-11-10 18:25:34,044] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.07185532172719798, 'n_estimators': 788, 'subsample': 0.511136224486195, 'colsample_bytree': 0.5993874135289536, 'min_child_weight': 5, 'gamma': 3.2290390404972746, 'reg_alpha': 4.0845569606019306e-05, 'reg_lambda': 1.1601761126660396e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5765497076023391.

Best trial: 1. Best value: 0.57655:   2%|▏         | 3/200 [00:04<03:48,  1.16s/it]

[I 2025-11-10 18:25:34,971] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01658691490703856, 'n_estimators': 968, 'subsample': 0.506608705816469, 'colsample_bytree': 0.8454917625797872, 'min_child_weight': 6, 'gamma': 3.194314900524127, 'reg_alpha': 0.02553652855031404, 'reg_lambda': 0.0026884510668750226, 'max_delta_step': 2}. Best is trial 1 with value: 0.5765497076023391.

Best trial: 1. Best value: 0.57655:   2%|▎         | 5/200 [00:05<02:28,  1.31it/s]

[I 2025-11-10 18:25:36,033] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.011208376566257247, 'n_estimators': 506, 'subsample': 0.815359253152524, 'colsample_bytree': 0.6528997047494176, 'min_child_weight': 6, 'gamma': 2.770699996743866, 'reg_alpha': 1.996805737815564e-06, 'reg_lambda': 3.9261022074924786e-08, 'max_delta_step': 5}. Best is trial 1 with value: 0.5765497076023391.
[I 2025-11-10 18:25:36,156] Trial 2 finished with value: 0.5616959064327486 and parameters: {'max_depth': 5, 'learning_rate': 0.018506297516659703, 'n_estimators': 1168, 'subsample': 0.7117442608136346, 'colsample_bytree': 0.8798898043681358, 'min_child_weight': 4, 'gamma': 0.9812410872375832, 'reg_alpha': 0.15245953158467962, 'reg_lambda': 0.0022271820425722134, 'max_delta_step': 0}. Best is trial 1 with value: 0.5765497076023391.

Best trial: 1. Best value: 0.57655:   3%|▎         | 6/200 [00:06<02:31,  1.28it/s]

[I 2025-11-10 18:25:36,977] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.18188987240992888, 'n_estimators': 852, 'subsample': 0.6520175667675463, 'colsample_bytree': 0.8196378750120833, 'min_child_weight': 6, 'gamma': 1.672502820334797, 'reg_alpha': 0.06814171642954246, 'reg_lambda': 0.0008363296751494971, 'max_delta_step': 3}. Best is trial 1 with value: 0.5765497076023391.

Best trial: 1. Best value: 0.57655:   4%|▎         | 7/200 [00:07<03:05,  1.04it/s]

[I 2025-11-10 18:25:38,300] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.028062874914524437, 'n_estimators': 824, 'subsample': 0.5485774943713522, 'colsample_bytree': 0.7902964546175795, 'min_child_weight': 4, 'gamma': 2.799682281148775, 'reg_alpha': 0.30722259407029695, 'reg_lambda': 2.8030726588899104e-08, 'max_delta_step': 0}. Best is trial 1 with value: 0.5765497076023391.

Best trial: 1. Best value: 0.57655:   4%|▍         | 8/200 [00:08<03:30,  1.10s/it]

[I 2025-11-10 18:25:39,698] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1821950617819537, 'n_estimators': 820, 'subsample': 0.8006046117864523, 'colsample_bytree': 0.9350076475976716, 'min_child_weight': 6, 'gamma': 2.55036743945391, 'reg_alpha': 0.0005856271752386727, 'reg_lambda': 0.6361551222624726, 'max_delta_step': 3}. Best is trial 1 with value: 0.5765497076023391.
[I 2025-11-10 18:25:39,777] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.1452702588133617, 'n_estimators': 968, 'subsample': 0.6781982112302714, 'colsample_bytree': 0.572743355736293, 'min_child_weight': 6, 'gamma': 2.2140895224922064, 'reg_alpha': 8.293660422803337e-08, 'reg_lambda': 0.0047378772988332365, 'max_delta_step': 6}. Best is trial 1 with value: 0.5765497076023391.

Best trial: 1. Best value: 0.57655:   5%|▌         | 10/200 [00:10<03:07,  1.01it/s]

[I 2025-11-10 18:25:41,434] Trial 12 finished with value: 0.5286062378167642 and parameters: {'max_depth': 9, 'learning_rate': 0.062288936044662596, 'n_estimators': 342, 'subsample': 0.832421634273097, 'colsample_bytree': 0.9373514108463905, 'min_child_weight': 4, 'gamma': 4.711302112877326, 'reg_alpha': 2.0634075789725314e-08, 'reg_lambda': 0.014087254453963579, 'max_delta_step': 9}. Best is trial 1 with value: 0.5765497076023391.

Best trial: 1. Best value: 0.57655:   6%|▌         | 12/200 [00:10<02:01,  1.54it/s]

[I 2025-11-10 18:25:41,849] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.013578171211222324, 'n_estimators': 522, 'subsample': 0.5238957834959073, 'colsample_bytree': 0.8610493803160842, 'min_child_weight': 10, 'gamma': 1.714409857979386, 'reg_alpha': 0.00018134448198876225, 'reg_lambda': 0.005321627951692842, 'max_delta_step': 8}. Best is trial 1 with value: 0.5765497076023391.
[I 2025-11-10 18:25:41,961] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.010381288375418277, 'n_estimators': 1223, 'subsample': 0.6536942627979949, 'colsample_bytree': 0.7843562954288592, 'min_child_weight': 9, 'gamma': 4.562976752877443, 'reg_alpha': 2.7322077680125823e-06, 'reg_lambda': 0.005796094835038903, 'max_delta_step': 7}. Best is trial 1 with value: 0.5765497076023391.

Best trial: 1. Best value: 0.57655:   6%|▋         | 13/200 [00:12<03:00,  1.04it/s]

[I 2025-11-10 18:25:43,759] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.08399708959259657, 'n_estimators': 1366, 'subsample': 0.7698396315064464, 'colsample_bytree': 0.7766334222793214, 'min_child_weight': 5, 'gamma': 4.072177710706564, 'reg_alpha': 0.02329534712578381, 'reg_lambda': 5.565151513220722, 'max_delta_step': 2}. Best is trial 1 with value: 0.5765497076023391.

Best trial: 1. Best value: 0.57655:   7%|▋         | 14/200 [00:13<03:10,  1.02s/it]

[I 2025-11-10 18:25:44,927] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03002729730476803, 'n_estimators': 205, 'subsample': 0.9936722685871389, 'colsample_bytree': 0.6672609668880825, 'min_child_weight': 1, 'gamma': 0.14652631447108533, 'reg_alpha': 6.572476420544523, 'reg_lambda': 1.9551289157153702e-05, 'max_delta_step': 10}. Best is trial 1 with value: 0.5765497076023391.

Best trial: 13. Best value: 0.582359:   8%|▊         | 15/200 [00:17<05:41,  1.85s/it]

[I 2025-11-10 18:25:48,819] Trial 13 finished with value: 0.5823586744639376 and parameters: {'max_depth': 3, 'learning_rate': 0.03951527514864849, 'n_estimators': 1437, 'subsample': 0.9971845767889199, 'colsample_bytree': 0.5142105925160381, 'min_child_weight': 1, 'gamma': 4.693461664341601, 'reg_alpha': 0.0004257689712780279, 'reg_lambda': 8.739265632034798e-06, 'max_delta_step': 10}. Best is trial 13 with value: 0.5823586744639376.

Best trial: 14. Best value: 0.588772:   8%|▊         | 16/200 [00:18<04:38,  1.51s/it]

[I 2025-11-10 18:25:49,519] Trial 14 finished with value: 0.5887719298245614 and parameters: {'max_depth': 4, 'learning_rate': 0.027058741335156896, 'n_estimators': 1404, 'subsample': 0.9683107422992614, 'colsample_bytree': 0.5066744855404635, 'min_child_weight': 1, 'gamma': 0.3782736536259216, 'reg_alpha': 3.6014537866685403, 'reg_lambda': 1.746754797905172e-05, 'max_delta_step': 10}. Best is trial 14 with value: 0.5887719298245614.

Best trial: 15. Best value: 0.606023:   8%|▊         | 17/200 [00:18<03:29,  1.15s/it]

[I 2025-11-10 18:25:49,788] Trial 15 finished with value: 0.6060233918128655 and parameters: {'max_depth': 4, 'learning_rate': 0.030383559858153487, 'n_estimators': 1488, 'subsample': 0.911508216782177, 'colsample_bytree': 0.5050607911577277, 'min_child_weight': 1, 'gamma': 0.16899853691561617, 'reg_alpha': 4.53970424201607, 'reg_lambda': 1.0410559151752018e-05, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:   9%|▉         | 18/200 [00:20<03:50,  1.27s/it]

[I 2025-11-10 18:25:51,337] Trial 17 finished with value: 0.5178557504873295 and parameters: {'max_depth': 4, 'learning_rate': 0.030445589677173663, 'n_estimators': 1197, 'subsample': 0.7191297758098631, 'colsample_bytree': 0.5334600179281788, 'min_child_weight': 1, 'gamma': 0.3684886975852384, 'reg_alpha': 0.0015299424211314477, 'reg_lambda': 9.039916916977169e-06, 'max_delta_step': 0}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  10%|▉         | 19/200 [00:21<03:23,  1.13s/it]

[I 2025-11-10 18:25:52,125] Trial 18 finished with value: 0.5830994152046782 and parameters: {'max_depth': 3, 'learning_rate': 0.039813341259486025, 'n_estimators': 594, 'subsample': 0.9908783879050673, 'colsample_bytree': 0.5028843094282892, 'min_child_weight': 1, 'gamma': 3.928878692431244, 'reg_alpha': 0.00147424814143873, 'reg_lambda': 1.2508613633115081e-05, 'max_delta_step': 9}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  10%|█         | 20/200 [00:21<02:55,  1.03it/s]

[I 2025-11-10 18:25:52,742] Trial 21 pruned.

Best trial: 15. Best value: 0.606023:  10%|█         | 21/200 [00:22<02:41,  1.11it/s]

[I 2025-11-10 18:25:53,469] Trial 22 pruned.

Best trial: 15. Best value: 0.606023:  11%|█         | 22/200 [00:25<04:46,  1.61s/it]

[I 2025-11-10 18:25:56,755] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04087360452086598, 'n_estimators': 1485, 'subsample': 0.9905118487706225, 'colsample_bytree': 0.5042386988743389, 'min_child_weight': 1, 'gamma': 0.18027965264116863, 'reg_alpha': 8.084644197782916, 'reg_lambda': 1.0042116001233001e-05, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  12%|█▏        | 23/200 [00:26<03:54,  1.32s/it]

[I 2025-11-10 18:25:57,400] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.05041026282616, 'n_estimators': 1299, 'subsample': 0.8805017428173733, 'colsample_bytree': 0.5973212475282814, 'min_child_weight': 8, 'gamma': 1.0699259607050142, 'reg_alpha': 1.2268737824042344, 'reg_lambda': 0.00011103588486646535, 'max_delta_step': 6}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  12%|█▏        | 24/200 [00:26<03:11,  1.09s/it]

[I 2025-11-10 18:25:57,938] Trial 20 finished with value: 0.5535867446393763 and parameters: {'max_depth': 4, 'learning_rate': 0.022828006040689745, 'n_estimators': 1480, 'subsample': 0.9091938126262602, 'colsample_bytree': 0.6797005361874918, 'min_child_weight': 2, 'gamma': 0.01591384175871663, 'reg_alpha': 5.002987232123676, 'reg_lambda': 1.588160197012522e-06, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  12%|█▎        | 25/200 [00:28<03:56,  1.35s/it]

[I 2025-11-10 18:25:59,914] Trial 24 finished with value: 0.5158869395711501 and parameters: {'max_depth': 4, 'learning_rate': 0.0450098446868095, 'n_estimators': 1310, 'subsample': 0.8937910601666744, 'colsample_bytree': 0.597970316331984, 'min_child_weight': 2, 'gamma': 3.8833120682510907, 'reg_alpha': 0.5244423768182912, 'reg_lambda': 7.29915654288455e-05, 'max_delta_step': 9}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  14%|█▎        | 27/200 [00:29<02:24,  1.20it/s]

[I 2025-11-10 18:26:00,517] Trial 28 pruned.
[I 2025-11-10 18:26:00,671] Trial 26 finished with value: 0.5428265107212475 and parameters: {'max_depth': 4, 'learning_rate': 0.09496536683550169, 'n_estimators': 650, 'subsample': 0.9347195891289287, 'colsample_bytree': 0.5639676440776077, 'min_child_weight': 2, 'gamma': 3.9598463907049033, 'reg_alpha': 0.004334287674732709, 'reg_lambda': 0.0001402230235591393, 'max_delta_step': 9}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  14%|█▍        | 28/200 [00:30<02:30,  1.14it/s]

[I 2025-11-10 18:26:01,639] Trial 29 pruned.

Best trial: 15. Best value: 0.606023:  15%|█▌        | 30/200 [00:32<02:10,  1.30it/s]

[I 2025-11-10 18:26:03,093] Trial 27 finished with value: 0.5470175438596492 and parameters: {'max_depth': 4, 'learning_rate': 0.09253350978708201, 'n_estimators': 1065, 'subsample': 0.9428438527669445, 'colsample_bytree': 0.5648153609810004, 'min_child_weight': 2, 'gamma': 3.9375540102451487, 'reg_alpha': 0.006111302595365998, 'reg_lambda': 0.0001599640146798703, 'max_delta_step': 9}. Best is trial 15 with value: 0.6060233918128655.
[I 2025-11-10 18:26:03,207] Trial 25 finished with value: 0.5245224171539961 and parameters: {'max_depth': 4, 'learning_rate': 0.04870593227346037, 'n_estimators': 1287, 'subsample': 0.8864262663229725, 'colsample_bytree': 0.5793747814546544, 'min_child_weight': 2, 'gamma': 3.8339376246265497, 'reg_alpha': 0.697299005143737, 'reg_lambda': 8.657180192209483e-05, 'max_delta_step': 9}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  16%|█▌        | 31/200 [00:33<02:13,  1.27it/s]

[I 2025-11-10 18:26:04,041] Trial 32 pruned.

Best trial: 15. Best value: 0.606023:  16%|█▌        | 32/200 [00:36<04:01,  1.44s/it]

[I 2025-11-10 18:26:06,989] Trial 30 finished with value: 0.5918518518518519 and parameters: {'max_depth': 5, 'learning_rate': 0.053432161084838586, 'n_estimators': 1096, 'subsample': 0.8667892060296418, 'colsample_bytree': 0.639233777002942, 'min_child_weight': 1, 'gamma': 2.0694554288142952, 'reg_alpha': 0.6264158900473639, 'reg_lambda': 2.282068673640182e-06, 'max_delta_step': 7}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  17%|█▋        | 34/200 [00:37<02:46,  1.01s/it]

[I 2025-11-10 18:26:08,277] Trial 31 finished with value: 0.5508771929824561 and parameters: {'max_depth': 5, 'learning_rate': 0.025470067134173862, 'n_estimators': 1098, 'subsample': 0.9603448462407735, 'colsample_bytree': 0.6267697158881788, 'min_child_weight': 1, 'gamma': 1.3642030796638334, 'reg_alpha': 2.7920165139541826e-05, 'reg_lambda': 0.04399699645751218, 'max_delta_step': 7}. Best is trial 15 with value: 0.6060233918128655.
[I 2025-11-10 18:26:08,381] Trial 33 finished with value: 0.541812865497076 and parameters: {'max_depth': 5, 'learning_rate': 0.015649774812987786, 'n_estimators': 637, 'subsample': 0.8484298988140642, 'colsample_bytree': 0.6342471744152407, 'min_child_weight': 1, 'gamma': 1.2998949160977151, 'reg_alpha': 0.035826292403814394, 'reg_lambda': 2.542121243486659e-07, 'max_delta_step': 7}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  18%|█▊        | 35/200 [00:38<02:35,  1.06it/s]

[I 2025-11-10 18:26:09,183] Trial 37 pruned.

Best trial: 15. Best value: 0.606023:  18%|█▊        | 36/200 [00:40<03:26,  1.26s/it]

[I 2025-11-10 18:26:11,183] Trial 34 finished with value: 0.5881481481481481 and parameters: {'max_depth': 3, 'learning_rate': 0.037456712353278854, 'n_estimators': 1385, 'subsample': 0.9944580767675992, 'colsample_bytree': 0.5278844838790661, 'min_child_weight': 1, 'gamma': 4.271081541293248, 'reg_alpha': 5.735453882563885e-05, 'reg_lambda': 4.064982797573313e-06, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  18%|█▊        | 37/200 [00:41<03:19,  1.22s/it]

[I 2025-11-10 18:26:12,323] Trial 39 pruned.

Best trial: 15. Best value: 0.606023:  19%|█▉        | 38/200 [00:42<03:16,  1.21s/it]

[I 2025-11-10 18:26:13,505] Trial 40 pruned.

Best trial: 15. Best value: 0.606023:  20%|█▉        | 39/200 [00:42<02:29,  1.08it/s]

[I 2025-11-10 18:26:13,764] Trial 35 finished with value: 0.5434113060428849 and parameters: {'max_depth': 3, 'learning_rate': 0.037874544960803704, 'n_estimators': 1138, 'subsample': 0.8616687860647073, 'colsample_bytree': 0.6293583789929655, 'min_child_weight': 1, 'gamma': 2.0229442240174076, 'reg_alpha': 1.3480572965468034, 'reg_lambda': 3.04367979710774e-05, 'max_delta_step': 8}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  20%|██        | 40/200 [00:43<02:29,  1.07it/s]

[I 2025-11-10 18:26:14,726] Trial 41 pruned.

Best trial: 15. Best value: 0.606023:  20%|██        | 41/200 [00:44<01:56,  1.36it/s]

[I 2025-11-10 18:26:14,984] Trial 36 finished with value: 0.5160038986354776 and parameters: {'max_depth': 3, 'learning_rate': 0.27831354408204967, 'n_estimators': 1384, 'subsample': 0.8508089893007341, 'colsample_bytree': 0.5425113128854041, 'min_child_weight': 1, 'gamma': 1.9074231371305208, 'reg_alpha': 0.17116042258473357, 'reg_lambda': 2.833950255045843e-05, 'max_delta_step': 8}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  22%|██▏       | 43/200 [00:45<01:31,  1.71it/s]

[I 2025-11-10 18:26:15,810] Trial 43 pruned.
[I 2025-11-10 18:26:15,982] Trial 42 pruned.

Best trial: 15. Best value: 0.606023:  22%|██▎       | 45/200 [00:45<01:13,  2.12it/s]

[I 2025-11-10 18:26:16,625] Trial 38 finished with value: 0.548869395711501 and parameters: {'max_depth': 3, 'learning_rate': 0.03658657261097374, 'n_estimators': 1377, 'subsample': 0.9700903517238562, 'colsample_bytree': 0.5345328799542263, 'min_child_weight': 1, 'gamma': 0.5858868942836604, 'reg_alpha': 0.17030334360417665, 'reg_lambda': 4.300668890594383e-06, 'max_delta_step': 8}. Best is trial 15 with value: 0.6060233918128655.
[I 2025-11-10 18:26:16,792] Trial 46 pruned.

Best trial: 15. Best value: 0.606023:  23%|██▎       | 46/200 [00:46<01:25,  1.79it/s]

[I 2025-11-10 18:26:17,553] Trial 47 pruned.

Best trial: 15. Best value: 0.606023:  24%|██▎       | 47/200 [00:47<01:25,  1.78it/s]

[I 2025-11-10 18:26:18,121] Trial 48 pruned.

Best trial: 15. Best value: 0.606023:  24%|██▍       | 48/200 [00:48<02:21,  1.08it/s]

[I 2025-11-10 18:26:19,907] Trial 49 finished with value: 0.5645808966861597 and parameters: {'max_depth': 8, 'learning_rate': 0.04302029505380654, 'n_estimators': 444, 'subsample': 0.9981643902589712, 'colsample_bytree': 0.5617865533407722, 'min_child_weight': 2, 'gamma': 4.926860686612008, 'reg_alpha': 0.00014852676685029285, 'reg_lambda': 8.636393165074879e-07, 'max_delta_step': 6}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  24%|██▍       | 49/200 [00:49<01:47,  1.41it/s]

[I 2025-11-10 18:26:20,112] Trial 44 finished with value: 0.5532748538011696 and parameters: {'max_depth': 4, 'learning_rate': 0.057877198502844784, 'n_estimators': 942, 'subsample': 0.9778102485034347, 'colsample_bytree': 0.5185273251220979, 'min_child_weight': 1, 'gamma': 4.4024390358435035, 'reg_alpha': 0.0001227827054873292, 'reg_lambda': 2.159142205313612e-06, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  25%|██▌       | 50/200 [00:49<01:33,  1.60it/s]

[I 2025-11-10 18:26:20,531] Trial 50 finished with value: 0.6007797270955166 and parameters: {'max_depth': 3, 'learning_rate': 0.030749959491234442, 'n_estimators': 423, 'subsample': 0.9894533522610566, 'colsample_bytree': 0.5631524997127615, 'min_child_weight': 2, 'gamma': 3.6998233783126477, 'reg_alpha': 0.0001455055563718129, 'reg_lambda': 8.725661393784234e-07, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  26%|██▌       | 51/200 [00:49<01:18,  1.89it/s]

[I 2025-11-10 18:26:20,841] Trial 53 pruned.
[I 2025-11-10 18:26:20,901] Trial 52 pruned.

Best trial: 15. Best value: 0.606023:  26%|██▋       | 53/200 [00:50<00:57,  2.57it/s]

[I 2025-11-10 18:26:21,292] Trial 45 finished with value: 0.5746978557504874 and parameters: {'max_depth': 4, 'learning_rate': 0.05917085808478963, 'n_estimators': 952, 'subsample': 0.9766472061894028, 'colsample_bytree': 0.5250522430802768, 'min_child_weight': 1, 'gamma': 2.3260672366516344, 'reg_alpha': 0.00010571681615043055, 'reg_lambda': 4.715214283469859e-06, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  28%|██▊       | 55/200 [00:52<01:34,  1.53it/s]

[I 2025-11-10 18:26:23,455] Trial 54 finished with value: 0.5735672514619883 and parameters: {'max_depth': 3, 'learning_rate': 0.024546728412251202, 'n_estimators': 421, 'subsample': 0.98344846081546, 'colsample_bytree': 0.5588232854733753, 'min_child_weight': 1, 'gamma': 4.181142297718105, 'reg_alpha': 0.00105648292939014, 'reg_lambda': 1.0285707440331116e-05, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.
[I 2025-11-10 18:26:23,618] Trial 56 finished with value: 0.5878947368421052 and parameters: {'max_depth': 3, 'learning_rate': 0.02359913605838833, 'n_estimators': 370, 'subsample': 0.9440716716225201, 'colsample_bytree': 0.5513267389450494, 'min_child_weight': 1, 'gamma': 4.210760416244591, 'reg_alpha': 0.0005490314364324806, 'reg_lambda': 1.520987716468798e-05, 'max_delta_step': 9}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  28%|██▊       | 56/200 [00:52<01:15,  1.91it/s]

[I 2025-11-10 18:26:23,795] Trial 55 finished with value: 0.5798635477582845 and parameters: {'max_depth': 3, 'learning_rate': 0.02580417731536749, 'n_estimators': 457, 'subsample': 0.9448853435009849, 'colsample_bytree': 0.5521222533642305, 'min_child_weight': 1, 'gamma': 4.195793151128024, 'reg_alpha': 0.0009634624456988518, 'reg_lambda': 9.054426380288558e-07, 'max_delta_step': 9}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  29%|██▉       | 58/200 [00:53<00:53,  2.65it/s]

[I 2025-11-10 18:26:24,086] Trial 58 pruned.
[I 2025-11-10 18:26:24,254] Trial 59 pruned.

Best trial: 15. Best value: 0.606023:  30%|██▉       | 59/200 [00:53<00:59,  2.37it/s]

[I 2025-11-10 18:26:24,787] Trial 57 pruned.
[I 2025-11-10 18:26:24,793] Trial 51 finished with value: 0.5597270955165692 and parameters: {'max_depth': 3, 'learning_rate': 0.03065346726102874, 'n_estimators': 752, 'subsample': 0.7345916550901334, 'colsample_bytree': 0.6519965509661909, 'min_child_weight': 1, 'gamma': 3.6294614846371687, 'reg_alpha': 0.015565755384325102, 'reg_lambda': 2.4222036239557185e-07, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  30%|███       | 61/200 [00:54<00:44,  3.16it/s]

[I 2025-11-10 18:26:25,168] Trial 60 pruned.

Best trial: 15. Best value: 0.606023:  31%|███       | 62/200 [00:55<01:04,  2.15it/s]

[I 2025-11-10 18:26:26,097] Trial 61 pruned.

Best trial: 15. Best value: 0.606023:  32%|███▏      | 63/200 [00:55<00:59,  2.31it/s]

[I 2025-11-10 18:26:26,432] Trial 63 pruned.

Best trial: 15. Best value: 0.606023:  32%|███▏      | 64/200 [00:56<01:17,  1.74it/s]

[I 2025-11-10 18:26:27,388] Trial 64 finished with value: 0.5787719298245614 and parameters: {'max_depth': 3, 'learning_rate': 0.04789716827981943, 'n_estimators': 383, 'subsample': 0.9862971241327559, 'colsample_bytree': 0.5020404666483959, 'min_child_weight': 1, 'gamma': 3.760693301382147, 'reg_alpha': 0.0003424072920004305, 'reg_lambda': 1.5912402218500754e-05, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  32%|███▎      | 65/200 [00:56<01:15,  1.78it/s]

[I 2025-11-10 18:26:27,913] Trial 65 finished with value: 0.5867056530214425 and parameters: {'max_depth': 3, 'learning_rate': 0.04633187720057034, 'n_estimators': 304, 'subsample': 0.9998200903007419, 'colsample_bytree': 0.5004704395033518, 'min_child_weight': 1, 'gamma': 3.74856401613984, 'reg_alpha': 0.000600406704854024, 'reg_lambda': 1.4395145887511813e-05, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  33%|███▎      | 66/200 [00:57<01:11,  1.86it/s]

[I 2025-11-10 18:26:28,390] Trial 66 finished with value: 0.5603898635477582 and parameters: {'max_depth': 3, 'learning_rate': 0.0411966506775265, 'n_estimators': 321, 'subsample': 0.9968575583670125, 'colsample_bytree': 0.5044751202596748, 'min_child_weight': 1, 'gamma': 3.7124434192878564, 'reg_alpha': 4.969996946428335e-05, 'reg_lambda': 1.2967821653470834e-05, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.
[I 2025-11-10 18:26:28,478] Trial 68 pruned.

Best trial: 15. Best value: 0.606023:  34%|███▍      | 68/200 [00:57<00:48,  2.71it/s]

[I 2025-11-10 18:26:28,716] Trial 69 pruned.

Best trial: 15. Best value: 0.606023:  34%|███▍      | 69/200 [00:59<01:33,  1.41it/s]

[I 2025-11-10 18:26:30,492] Trial 70 finished with value: 0.5684990253411306 and parameters: {'max_depth': 4, 'learning_rate': 0.029466098092596406, 'n_estimators': 276, 'subsample': 0.6867635633336542, 'colsample_bytree': 0.5480593842620407, 'min_child_weight': 1, 'gamma': 3.227991231267998, 'reg_alpha': 0.011840698646343906, 'reg_lambda': 4.076391255494537e-07, 'max_delta_step': 9}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  35%|███▌      | 70/200 [00:59<01:15,  1.73it/s]

[I 2025-11-10 18:26:30,686] Trial 67 finished with value: 0.5438011695906432 and parameters: {'max_depth': 3, 'learning_rate': 0.042177023599711545, 'n_estimators': 291, 'subsample': 0.9548788324001025, 'colsample_bytree': 0.8304860442412039, 'min_child_weight': 1, 'gamma': 0.027212481437103808, 'reg_alpha': 0.011939548826962304, 'reg_lambda': 4.6719007833272154e-07, 'max_delta_step': 9}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  36%|███▌      | 72/200 [01:01<01:15,  1.68it/s]

[I 2025-11-10 18:26:31,965] Trial 73 pruned.
[I 2025-11-10 18:26:32,110] Trial 72 pruned.

Best trial: 15. Best value: 0.606023:  36%|███▋      | 73/200 [01:04<02:45,  1.31s/it]

[I 2025-11-10 18:26:35,214] Trial 74 finished with value: 0.5921247563352827 and parameters: {'max_depth': 3, 'learning_rate': 0.05244835627288873, 'n_estimators': 595, 'subsample': 0.9651789537989395, 'colsample_bytree': 0.5226498408219078, 'min_child_weight': 1, 'gamma': 4.035520765147156, 'reg_alpha': 0.6865020695186403, 'reg_lambda': 6.817459715015146e-05, 'max_delta_step': 9}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  37%|███▋      | 74/200 [01:04<02:21,  1.12s/it]

[I 2025-11-10 18:26:35,875] Trial 71 finished with value: 0.5827485380116959 and parameters: {'max_depth': 5, 'learning_rate': 0.033497675910423734, 'n_estimators': 1336, 'subsample': 0.8761453524351488, 'colsample_bytree': 0.5484550330987361, 'min_child_weight': 1, 'gamma': 4.566051901564923, 'reg_alpha': 1.1349659669657592e-06, 'reg_lambda': 6.597455385350904e-07, 'max_delta_step': 9}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  38%|███▊      | 75/200 [01:06<02:21,  1.13s/it]

[I 2025-11-10 18:26:37,033] Trial 62 finished with value: 0.5283625730994153 and parameters: {'max_depth': 4, 'learning_rate': 0.011803976305758123, 'n_estimators': 1437, 'subsample': 0.8988360035026228, 'colsample_bytree': 0.6969054978522262, 'min_child_weight': 1, 'gamma': 0.408013557455399, 'reg_alpha': 0.000319971698285411, 'reg_lambda': 3.876335468240181e-07, 'max_delta_step': 1}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  38%|███▊      | 77/200 [01:07<01:39,  1.24it/s]

[I 2025-11-10 18:26:37,991] Trial 76 finished with value: 0.5744444444444444 and parameters: {'max_depth': 3, 'learning_rate': 0.05331805538537694, 'n_estimators': 480, 'subsample': 0.964264041001666, 'colsample_bytree': 0.5227822534627523, 'min_child_weight': 1, 'gamma': 4.0274753608531455, 'reg_alpha': 0.6045559926975654, 'reg_lambda': 3.957018340683409e-05, 'max_delta_step': 8}. Best is trial 15 with value: 0.6060233918128655.
[I 2025-11-10 18:26:38,146] Trial 77 finished with value: 0.5855750487329434 and parameters: {'max_depth': 3, 'learning_rate': 0.051574597098418266, 'n_estimators': 381, 'subsample': 0.9658428543262676, 'colsample_bytree': 0.5229326828286668, 'min_child_weight': 1, 'gamma': 4.309559631261292, 'reg_alpha': 0.44237109657440443, 'reg_lambda': 0.00018156324713628107, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  39%|███▉      | 78/200 [01:07<01:18,  1.56it/s]

[I 2025-11-10 18:26:38,398] Trial 75 finished with value: 0.5878167641325536 and parameters: {'max_depth': 3, 'learning_rate': 0.03433324477311712, 'n_estimators': 1204, 'subsample': 0.9794054764122787, 'colsample_bytree': 0.5180897243445021, 'min_child_weight': 1, 'gamma': 3.991058500102609, 'reg_alpha': 0.002573075361153133, 'reg_lambda': 2.0409003842122713e-05, 'max_delta_step': 9}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  40%|███▉      | 79/200 [01:08<01:15,  1.60it/s]

[I 2025-11-10 18:26:38,977] Trial 79 pruned.

Best trial: 15. Best value: 0.606023:  40%|████      | 81/200 [01:08<00:50,  2.37it/s]

[I 2025-11-10 18:26:39,285] Trial 80 pruned.
[I 2025-11-10 18:26:39,454] Trial 78 finished with value: 0.5777582846003898 and parameters: {'max_depth': 3, 'learning_rate': 0.07900555616541365, 'n_estimators': 379, 'subsample': 0.9639494215903007, 'colsample_bytree': 0.5247384874403431, 'min_child_weight': 1, 'gamma': 4.018884568866849, 'reg_alpha': 0.8818599265851733, 'reg_lambda': 6.330176492518074e-05, 'max_delta_step': 8}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  41%|████      | 82/200 [01:08<00:48,  2.45it/s]

[I 2025-11-10 18:26:39,832] Trial 81 pruned.

Best trial: 15. Best value: 0.606023:  42%|████▏     | 83/200 [01:09<00:40,  2.92it/s]

[I 2025-11-10 18:26:40,021] Trial 82 pruned.

Best trial: 15. Best value: 0.606023:  42%|████▏     | 84/200 [01:09<00:37,  3.09it/s]

[I 2025-11-10 18:26:40,299] Trial 83 pruned.

Best trial: 15. Best value: 0.606023:  42%|████▎     | 85/200 [01:09<00:46,  2.45it/s]

[I 2025-11-10 18:26:40,904] Trial 86 pruned.

Best trial: 15. Best value: 0.606023:  43%|████▎     | 86/200 [01:10<01:05,  1.75it/s]

[I 2025-11-10 18:26:41,856] Trial 87 pruned.

Best trial: 15. Best value: 0.606023:  44%|████▎     | 87/200 [01:11<01:08,  1.65it/s]

[I 2025-11-10 18:26:42,550] Trial 88 pruned.

Best trial: 15. Best value: 0.606023:  44%|████▍     | 88/200 [01:12<01:17,  1.45it/s]

[I 2025-11-10 18:26:43,424] Trial 89 pruned.

Best trial: 15. Best value: 0.606023:  44%|████▍     | 89/200 [01:13<01:22,  1.35it/s]

[I 2025-11-10 18:26:44,295] Trial 91 pruned.

Best trial: 15. Best value: 0.606023:  45%|████▌     | 90/200 [01:14<01:34,  1.16it/s]

[I 2025-11-10 18:26:45,441] Trial 85 finished with value: 0.5811306042884989 and parameters: {'max_depth': 3, 'learning_rate': 0.03416615394630056, 'n_estimators': 1006, 'subsample': 0.9817262156174279, 'colsample_bytree': 0.5359508070597653, 'min_child_weight': 1, 'gamma': 3.8665598378268604, 'reg_alpha': 0.0026823161650200308, 'reg_lambda': 2.1308152666130855e-06, 'max_delta_step': 9}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  46%|████▌     | 91/200 [01:14<01:16,  1.42it/s]

[I 2025-11-10 18:26:45,776] Trial 92 pruned.

Best trial: 15. Best value: 0.606023:  46%|████▌     | 92/200 [01:15<01:15,  1.43it/s]

[I 2025-11-10 18:26:46,461] Trial 84 finished with value: 0.5896296296296295 and parameters: {'max_depth': 3, 'learning_rate': 0.033577243520125165, 'n_estimators': 1259, 'subsample': 0.9841456018623286, 'colsample_bytree': 0.5417340448283422, 'min_child_weight': 1, 'gamma': 4.3167515580883595, 'reg_alpha': 0.0019933693829969745, 'reg_lambda': 7.138584037119858e-06, 'max_delta_step': 9}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  46%|████▋     | 93/200 [01:15<01:06,  1.60it/s]

[I 2025-11-10 18:26:46,908] Trial 93 pruned.

Best trial: 15. Best value: 0.606023:  47%|████▋     | 94/200 [01:16<01:11,  1.48it/s]

[I 2025-11-10 18:26:47,701] Trial 94 finished with value: 0.5805068226120857 and parameters: {'max_depth': 3, 'learning_rate': 0.05467713746958254, 'n_estimators': 303, 'subsample': 0.9583159100158167, 'colsample_bytree': 0.5150917472515418, 'min_child_weight': 1, 'gamma': 4.37896750616897, 'reg_alpha': 0.35441318767906316, 'reg_lambda': 0.00027592912572870767, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  48%|████▊     | 95/200 [01:17<01:26,  1.21it/s]

[I 2025-11-10 18:26:48,879] Trial 90 finished with value: 0.5765497076023391 and parameters: {'max_depth': 3, 'learning_rate': 0.02764224538925834, 'n_estimators': 1158, 'subsample': 0.9541472204160539, 'colsample_bytree': 0.5110398161375265, 'min_child_weight': 1, 'gamma': 3.550815287001969, 'reg_alpha': 2.7416231042388427e-05, 'reg_lambda': 2.7444586082566505e-05, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  48%|████▊     | 96/200 [01:18<01:15,  1.38it/s]

[I 2025-11-10 18:26:49,374] Trial 95 pruned.

Best trial: 15. Best value: 0.606023:  48%|████▊     | 97/200 [01:20<01:58,  1.15s/it]

[I 2025-11-10 18:26:51,502] Trial 98 pruned.

Best trial: 15. Best value: 0.606023:  49%|████▉     | 98/200 [01:21<01:53,  1.11s/it]

[I 2025-11-10 18:26:52,524] Trial 100 pruned.

Best trial: 15. Best value: 0.606023:  50%|████▉     | 99/200 [01:21<01:27,  1.15it/s]

[I 2025-11-10 18:26:52,829] Trial 96 finished with value: 0.5715204678362573 and parameters: {'max_depth': 3, 'learning_rate': 0.04671817713221875, 'n_estimators': 1145, 'subsample': 0.9696082102706198, 'colsample_bytree': 0.5003283699922276, 'min_child_weight': 1, 'gamma': 4.298064209861365, 'reg_alpha': 2.6990893528472292e-05, 'reg_lambda': 1.5538634454416236e-05, 'max_delta_step': 9}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  50%|█████     | 100/200 [01:22<01:31,  1.10it/s]

[I 2025-11-10 18:26:53,842] Trial 101 pruned.

Best trial: 15. Best value: 0.606023:  51%|█████     | 102/200 [01:23<00:54,  1.81it/s]

[I 2025-11-10 18:26:54,155] Trial 103 pruned.
[I 2025-11-10 18:26:54,290] Trial 102 pruned.

Best trial: 15. Best value: 0.606023:  52%|█████▏    | 103/200 [01:23<00:43,  2.21it/s]

[I 2025-11-10 18:26:54,511] Trial 97 finished with value: 0.5790253411306043 and parameters: {'max_depth': 4, 'learning_rate': 0.04679372521882097, 'n_estimators': 1286, 'subsample': 0.9720083837065844, 'colsample_bytree': 0.640725996830575, 'min_child_weight': 2, 'gamma': 4.083899160764313, 'reg_alpha': 2.5717208653574173e-05, 'reg_lambda': 1.6803496801030474e-05, 'max_delta_step': 9}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  52%|█████▏    | 104/200 [01:23<00:38,  2.49it/s]

[I 2025-11-10 18:26:54,791] Trial 105 pruned.

Best trial: 15. Best value: 0.606023:  52%|█████▎    | 105/200 [01:24<00:43,  2.19it/s]

[I 2025-11-10 18:26:55,374] Trial 104 pruned.

Best trial: 15. Best value: 0.606023:  53%|█████▎    | 106/200 [01:24<00:41,  2.27it/s]

[I 2025-11-10 18:26:55,780] Trial 106 pruned.

Best trial: 15. Best value: 0.606023:  54%|█████▍    | 108/200 [01:25<00:29,  3.13it/s]

[I 2025-11-10 18:26:56,056] Trial 108 pruned.
[I 2025-11-10 18:26:56,210] Trial 107 pruned.

Best trial: 15. Best value: 0.606023:  55%|█████▍    | 109/200 [01:25<00:31,  2.86it/s]

[I 2025-11-10 18:26:56,627] Trial 99 finished with value: 0.5813840155945419 and parameters: {'max_depth': 4, 'learning_rate': 0.02215651723645858, 'n_estimators': 1358, 'subsample': 0.9917311221173275, 'colsample_bytree': 0.5484148379213221, 'min_child_weight': 2, 'gamma': 4.032880729944718, 'reg_alpha': 0.0006539074874027909, 'reg_lambda': 5.89477988543787e-06, 'max_delta_step': 9}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  56%|█████▌    | 111/200 [01:27<00:44,  2.02it/s]

[I 2025-11-10 18:26:57,984] Trial 111 finished with value: 0.5698830409356725 and parameters: {'max_depth': 3, 'learning_rate': 0.02524294732574786, 'n_estimators': 242, 'subsample': 0.9487362323884669, 'colsample_bytree': 0.5733811303027149, 'min_child_weight': 1, 'gamma': 3.990545468038703, 'reg_alpha': 1.3595125107230585e-05, 'reg_lambda': 0.0001014925998145472, 'max_delta_step': 5}. Best is trial 15 with value: 0.6060233918128655.
[I 2025-11-10 18:26:58,116] Trial 112 pruned.

Best trial: 15. Best value: 0.606023:  56%|█████▌    | 112/200 [01:28<01:04,  1.37it/s]

[I 2025-11-10 18:26:59,384] Trial 113 pruned.

Best trial: 15. Best value: 0.606023:  56%|█████▋    | 113/200 [01:31<01:57,  1.36s/it]

[I 2025-11-10 18:27:02,204] Trial 110 finished with value: 0.581598440545809 and parameters: {'max_depth': 3, 'learning_rate': 0.04995034702175898, 'n_estimators': 1183, 'subsample': 0.9471973999472063, 'colsample_bytree': 0.5125913562935351, 'min_child_weight': 1, 'gamma': 4.631551417084168, 'reg_alpha': 0.8011652298684859, 'reg_lambda': 0.0001147641264109274, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  57%|█████▋    | 114/200 [01:31<01:27,  1.02s/it]

[I 2025-11-10 18:27:02,443] Trial 114 finished with value: 0.5750682261208577 and parameters: {'max_depth': 3, 'learning_rate': 0.03982051009580102, 'n_estimators': 819, 'subsample': 0.9602858595567922, 'colsample_bytree': 0.5005597566179549, 'min_child_weight': 1, 'gamma': 4.269938608675657, 'reg_alpha': 0.007035602242714995, 'reg_lambda': 1.0973324721116398e-05, 'max_delta_step': 8}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  57%|█████▊    | 115/200 [01:32<01:16,  1.10it/s]

[I 2025-11-10 18:27:03,078] Trial 116 pruned.
[I 2025-11-10 18:27:03,084] Trial 117 pruned.

Best trial: 15. Best value: 0.606023:  59%|█████▉    | 118/200 [01:32<00:40,  2.04it/s]

[I 2025-11-10 18:27:03,575] Trial 109 finished with value: 0.5675438596491228 and parameters: {'max_depth': 3, 'learning_rate': 0.04064919894857513, 'n_estimators': 1454, 'subsample': 0.9861592061039569, 'colsample_bytree': 0.5105615556017475, 'min_child_weight': 1, 'gamma': 4.25934770535869, 'reg_alpha': 0.8622847824461479, 'reg_lambda': 1.6229671173686093e-06, 'max_delta_step': 5}. Best is trial 15 with value: 0.6060233918128655.
[I 2025-11-10 18:27:03,727] Trial 115 finished with value: 0.5695126705653022 and parameters: {'max_depth': 3, 'learning_rate': 0.03243329864109219, 'n_estimators': 697, 'subsample': 0.9614417450819909, 'colsample_bytree': 0.5418582850691763, 'min_child_weight': 1, 'gamma': 0.7394375091112025, 'reg_alpha': 0.02447465006262147, 'reg_lambda': 3.275629880667588e-06, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  60%|█████▉    | 119/200 [01:33<00:36,  2.23it/s]

[I 2025-11-10 18:27:04,056] Trial 121 pruned.

Best trial: 15. Best value: 0.606023:  60%|██████    | 120/200 [01:33<00:44,  1.80it/s]

[I 2025-11-10 18:27:04,905] Trial 118 pruned.

Best trial: 15. Best value: 0.606023:  60%|██████    | 121/200 [01:34<00:38,  2.06it/s]

[I 2025-11-10 18:27:05,206] Trial 122 pruned.

Best trial: 15. Best value: 0.606023:  61%|██████    | 122/200 [01:35<00:46,  1.70it/s]

[I 2025-11-10 18:27:06,053] Trial 123 pruned.

Best trial: 15. Best value: 0.606023:  62%|██████▏   | 123/200 [01:35<00:37,  2.06it/s]

[I 2025-11-10 18:27:06,290] Trial 119 finished with value: 0.5780506822612086 and parameters: {'max_depth': 3, 'learning_rate': 0.04291484002395897, 'n_estimators': 453, 'subsample': 0.9744962816146145, 'colsample_bytree': 0.5209200737004798, 'min_child_weight': 1, 'gamma': 0.6666361908726888, 'reg_alpha': 0.00021097968168036342, 'reg_lambda': 9.055552395627669e-07, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  62%|██████▏   | 124/200 [01:35<00:32,  2.37it/s]

[I 2025-11-10 18:27:06,553] Trial 120 finished with value: 0.6002729044834307 and parameters: {'max_depth': 3, 'learning_rate': 0.05853961575272551, 'n_estimators': 459, 'subsample': 0.9745844227082714, 'colsample_bytree': 0.5207005928888438, 'min_child_weight': 1, 'gamma': 2.6348539627129495, 'reg_alpha': 0.003875382213891417, 'reg_lambda': 0.00016663809263423837, 'max_delta_step': 10}. Best is trial 15 with value: 0.6060233918128655.

Best trial: 15. Best value: 0.606023:  62%|██████▎   | 125/200 [01:36<00:37,  1.99it/s]

[I 2025-11-10 18:27:07,247] Trial 127 pruned.

Best trial: 15. Best value: 0.606023:  63%|██████▎   | 126/200 [01:36<00:35,  2.08it/s]

[I 2025-11-10 18:27:07,678] Trial 125 pruned.

Best trial: 15. Best value: 0.606023:  64%|██████▍   | 128/200 [01:37<00:24,  2.97it/s]

[I 2025-11-10 18:27:07,917] Trial 128 pruned.
[I 2025-11-10 18:27:08,084] Trial 126 pruned.

Best trial: 15. Best value: 0.606023:  64%|██████▍   | 129/200 [01:37<00:27,  2.63it/s]

[I 2025-11-10 18:27:08,568] Trial 130 pruned.

Best trial: 15. Best value: 0.606023:  66%|██████▌   | 131/200 [01:37<00:18,  3.71it/s]

[I 2025-11-10 18:27:08,814] Trial 129 pruned.
[I 2025-11-10 18:27:08,917] Trial 131 pruned.

Best trial: 15. Best value: 0.606023:  66%|██████▌   | 132/200 [01:39<00:35,  1.92it/s]

[I 2025-11-10 18:27:10,023] Trial 133 pruned.

Best trial: 134. Best value: 0.625088:  66%|██████▋   | 133/200 [01:40<00:51,  1.29it/s]

[I 2025-11-10 18:27:11,390] Trial 134 finished with value: 0.6250877192982456 and parameters: {'max_depth': 6, 'learning_rate': 0.026595174296891826, 'n_estimators': 362, 'subsample': 0.9922534629490151, 'colsample_bytree': 0.5552561968108838, 'min_child_weight': 1, 'gamma': 2.489453083012419, 'reg_alpha': 0.007669261823510242, 'reg_lambda': 0.0006190890542352551, 'max_delta_step': 9}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 134. Best value: 0.625088:  67%|██████▋   | 134/200 [01:41<00:49,  1.34it/s]

[I 2025-11-10 18:27:12,067] Trial 132 finished with value: 0.6030994152046784 and parameters: {'max_depth': 3, 'learning_rate': 0.026619060612944737, 'n_estimators': 577, 'subsample': 0.9737333153625193, 'colsample_bytree': 0.5356042529835584, 'min_child_weight': 1, 'gamma': 2.4342115178688273, 'reg_alpha': 0.00012979238530915423, 'reg_lambda': 5.650206315580776e-06, 'max_delta_step': 10}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 134. Best value: 0.625088:  68%|██████▊   | 135/200 [01:41<00:48,  1.34it/s]

[I 2025-11-10 18:27:12,819] Trial 124 finished with value: 0.5809941520467836 and parameters: {'max_depth': 4, 'learning_rate': 0.04290345981421634, 'n_estimators': 1333, 'subsample': 0.8672701500338001, 'colsample_bytree': 0.5644053321098983, 'min_child_weight': 1, 'gamma': 4.8102996642748925, 'reg_alpha': 3.951834111764373e-07, 'reg_lambda': 8.777883478739697e-07, 'max_delta_step': 9}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 134. Best value: 0.625088:  68%|██████▊   | 136/200 [01:42<00:39,  1.61it/s]

[I 2025-11-10 18:27:13,147] Trial 138 pruned.

Best trial: 134. Best value: 0.625088:  68%|██████▊   | 137/200 [01:42<00:42,  1.49it/s]

[I 2025-11-10 18:27:13,937] Trial 136 finished with value: 0.5911111111111111 and parameters: {'max_depth': 6, 'learning_rate': 0.060538001615582614, 'n_estimators': 418, 'subsample': 0.9994869772535981, 'colsample_bytree': 0.5607508229533452, 'min_child_weight': 1, 'gamma': 2.7460667169372885, 'reg_alpha': 0.009865031099378724, 'reg_lambda': 0.0005520937274876432, 'max_delta_step': 9}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 134. Best value: 0.625088:  69%|██████▉   | 138/200 [01:43<00:40,  1.53it/s]

[I 2025-11-10 18:27:14,553] Trial 140 pruned.

Best trial: 134. Best value: 0.625088:  70%|██████▉   | 139/200 [01:43<00:32,  1.87it/s]

[I 2025-11-10 18:27:14,802] Trial 137 finished with value: 0.5903898635477584 and parameters: {'max_depth': 5, 'learning_rate': 0.026324330023011877, 'n_estimators': 353, 'subsample': 0.9487053144373745, 'colsample_bytree': 0.5538663064922531, 'min_child_weight': 1, 'gamma': 2.48869934538406, 'reg_alpha': 0.039675710704773534, 'reg_lambda': 0.0007804985010508911, 'max_delta_step': 10}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 134. Best value: 0.625088:  70%|███████   | 140/200 [01:44<00:35,  1.67it/s]

[I 2025-11-10 18:27:15,552] Trial 142 pruned.

Best trial: 134. Best value: 0.625088:  70%|███████   | 141/200 [01:44<00:31,  1.89it/s]

[I 2025-11-10 18:27:15,916] Trial 139 finished with value: 0.6070370370370369 and parameters: {'max_depth': 3, 'learning_rate': 0.026041211144225376, 'n_estimators': 416, 'subsample': 0.9904310205003407, 'colsample_bytree': 0.5448347911136432, 'min_child_weight': 1, 'gamma': 2.7317542031725273, 'reg_alpha': 0.007823662222582298, 'reg_lambda': 0.001529618468907915, 'max_delta_step': 10}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 134. Best value: 0.625088:  71%|███████   | 142/200 [01:46<00:43,  1.33it/s]

[I 2025-11-10 18:27:17,189] Trial 135 finished with value: 0.5708576998050683 and parameters: {'max_depth': 6, 'learning_rate': 0.0274403853738176, 'n_estimators': 1266, 'subsample': 0.8813127868936301, 'colsample_bytree': 0.5518449531030599, 'min_child_weight': 1, 'gamma': 2.4486986628031104, 'reg_alpha': 9.830554163289221e-08, 'reg_lambda': 2.4521407847110443e-06, 'max_delta_step': 9}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 134. Best value: 0.625088:  72%|███████▏  | 143/200 [01:46<00:40,  1.41it/s]

[I 2025-11-10 18:27:17,799] Trial 145 pruned.

Best trial: 134. Best value: 0.625088:  72%|███████▏  | 144/200 [01:47<00:37,  1.50it/s]

[I 2025-11-10 18:27:18,369] Trial 146 pruned.

Best trial: 134. Best value: 0.625088:  72%|███████▎  | 145/200 [01:47<00:28,  1.91it/s]

[I 2025-11-10 18:27:18,554] Trial 141 finished with value: 0.5830994152046782 and parameters: {'max_depth': 6, 'learning_rate': 0.026110683194311722, 'n_estimators': 566, 'subsample': 0.9880274474496549, 'colsample_bytree': 0.6039014613334408, 'min_child_weight': 1, 'gamma': 2.504612400553204, 'reg_alpha': 0.0195287791478377, 'reg_lambda': 0.0008248708364952953, 'max_delta_step': 9}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 134. Best value: 0.625088:  73%|███████▎  | 146/200 [01:48<00:27,  1.96it/s]

[I 2025-11-10 18:27:19,037] Trial 144 finished with value: 0.5735867446393762 and parameters: {'max_depth': 7, 'learning_rate': 0.01951778760243821, 'n_estimators': 435, 'subsample': 0.9869050656387234, 'colsample_bytree': 0.568965914730555, 'min_child_weight': 1, 'gamma': 2.908826828572805, 'reg_alpha': 0.04057014526904481, 'reg_lambda': 0.004855694670237058, 'max_delta_step': 9}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 134. Best value: 0.625088:  74%|███████▎  | 147/200 [01:48<00:23,  2.29it/s]

[I 2025-11-10 18:27:19,297] Trial 148 pruned.
[I 2025-11-10 18:27:19,313] Trial 143 finished with value: 0.6050682261208576 and parameters: {'max_depth': 7, 'learning_rate': 0.030513719833192017, 'n_estimators': 568, 'subsample': 0.9877989062670616, 'colsample_bytree': 0.5729156153943561, 'min_child_weight': 1, 'gamma': 2.4530980211436653, 'reg_alpha': 0.004615652584154211, 'reg_lambda': 0.004335860286692999, 'max_delta_step': 9}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 134. Best value: 0.625088:  75%|███████▌  | 150/200 [01:50<00:29,  1.72it/s]

[I 2025-11-10 18:27:21,465] Trial 150 finished with value: 0.5649512670565302 and parameters: {'max_depth': 7, 'learning_rate': 0.02315485324361685, 'n_estimators': 324, 'subsample': 0.9638266452462104, 'colsample_bytree': 0.6162690624448117, 'min_child_weight': 2, 'gamma': 2.8214856966602335, 'reg_alpha': 0.004495848118782087, 'reg_lambda': 0.00153084429028715, 'max_delta_step': 10}. Best is trial 134 with value: 0.6250877192982456.
[I 2025-11-10 18:27:21,576] Trial 151 finished with value: 0.5560623781676414 and parameters: {'max_depth': 7, 'learning_rate': 0.02268283500055791, 'n_estimators': 339, 'subsample': 0.9543416111848463, 'colsample_bytree': 0.5587818383698754, 'min_child_weight': 2, 'gamma': 2.6062238210901496, 'reg_alpha': 0.005144402063001527, 'reg_lambda': 0.007348802823183257, 'max_delta_step': 10}. Best is trial 134 with value: 0.6250877192982456.
[I 2025-11-10 18:27:21,582] Trial 147 finished with value: 0.5737037037037037 and parameters: {'max_depth': 6, 'learning_rate': 0.023065491312730495, 'n_estimators': 440, 'subsample': 0.973486978685642, 'colsample_bytree': 0.5566994612290848, 'min_child_weight': 1, 'gamma': 2.6094012853830257, 'reg_alpha': 0.004968660198912278, 'reg_lambda': 0.0005867860256679419, 'max_delta_step': 10}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 134. Best value: 0.625088:  76%|███████▋  | 153/200 [01:51<00:19,  2.46it/s]

[I 2025-11-10 18:27:22,253] Trial 152 pruned.
[I 2025-11-10 18:27:22,409] Trial 154 pruned.

Best trial: 134. Best value: 0.625088:  76%|███████▋  | 153/200 [01:51<00:19,  2.46it/s]

[I 2025-11-10 18:27:22,455] Trial 153 pruned.

Best trial: 134. Best value: 0.625088:  78%|███████▊  | 155/200 [01:51<00:14,  3.02it/s]

[I 2025-11-10 18:27:22,840] Trial 149 finished with value: 0.584074074074074 and parameters: {'max_depth': 7, 'learning_rate': 0.023010797904548668, 'n_estimators': 513, 'subsample': 0.9757051523320024, 'colsample_bytree': 0.5549875324161715, 'min_child_weight': 1, 'gamma': 2.602913143385756, 'reg_alpha': 0.0029005195834578903, 'reg_lambda': 0.0005868976132014646, 'max_delta_step': 10}. Best is trial 134 with value: 0.6250877192982456.
[I 2025-11-10 18:27:22,900] Trial 155 pruned.

Best trial: 134. Best value: 0.625088:  78%|███████▊  | 157/200 [01:52<00:15,  2.78it/s]

[I 2025-11-10 18:27:23,664] Trial 159 pruned.

Best trial: 134. Best value: 0.625088:  79%|███████▉  | 158/200 [01:53<00:15,  2.80it/s]

[I 2025-11-10 18:27:24,012] Trial 157 pruned.

Best trial: 134. Best value: 0.625088:  80%|███████▉  | 159/200 [01:53<00:13,  3.13it/s]

[I 2025-11-10 18:27:24,203] Trial 156 pruned.
[I 2025-11-10 18:27:24,245] Trial 158 pruned.

Best trial: 134. Best value: 0.625088:  80%|████████  | 161/200 [01:53<00:12,  3.13it/s]

[I 2025-11-10 18:27:24,839] Trial 163 pruned.

Best trial: 134. Best value: 0.625088:  82%|████████▏ | 163/200 [01:54<00:10,  3.39it/s]

[I 2025-11-10 18:27:25,282] Trial 161 pruned.
[I 2025-11-10 18:27:25,410] Trial 160 pruned.

Best trial: 134. Best value: 0.625088:  82%|████████▏ | 164/200 [01:55<00:16,  2.16it/s]

[I 2025-11-10 18:27:26,370] Trial 166 pruned.

Best trial: 134. Best value: 0.625088:  82%|████████▎ | 165/200 [01:55<00:15,  2.20it/s]

[I 2025-11-10 18:27:26,803] Trial 164 finished with value: 0.5686549707602339 and parameters: {'max_depth': 3, 'learning_rate': 0.0609882764038705, 'n_estimators': 301, 'subsample': 0.9865377674097919, 'colsample_bytree': 0.5162740579552545, 'min_child_weight': 1, 'gamma': 2.8621479074350513, 'reg_alpha': 0.00030192480134061443, 'reg_lambda': 0.0010272881549114818, 'max_delta_step': 10}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 134. Best value: 0.625088:  83%|████████▎ | 166/200 [01:56<00:14,  2.41it/s]

[I 2025-11-10 18:27:27,108] Trial 162 pruned.

Best trial: 134. Best value: 0.625088:  84%|████████▎ | 167/200 [01:56<00:15,  2.09it/s]

[I 2025-11-10 18:27:27,754] Trial 165 finished with value: 0.5779337231968811 and parameters: {'max_depth': 3, 'learning_rate': 0.0600618359656853, 'n_estimators': 400, 'subsample': 0.9889035769702241, 'colsample_bytree': 0.5151102743380365, 'min_child_weight': 1, 'gamma': 2.5151625102422646, 'reg_alpha': 0.0002452431478714933, 'reg_lambda': 9.200599350631762e-06, 'max_delta_step': 10}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 134. Best value: 0.625088:  84%|████████▍ | 168/200 [01:57<00:18,  1.76it/s]

[I 2025-11-10 18:27:28,542] Trial 170 pruned.

Best trial: 134. Best value: 0.625088:  84%|████████▍ | 169/200 [01:57<00:14,  2.11it/s]

[I 2025-11-10 18:27:28,784] Trial 167 finished with value: 0.5980311890838207 and parameters: {'max_depth': 3, 'learning_rate': 0.028990282800983695, 'n_estimators': 319, 'subsample': 0.9888349891094806, 'colsample_bytree': 0.5104529592437782, 'min_child_weight': 1, 'gamma': 2.4937750847242643, 'reg_alpha': 0.00022459193663427313, 'reg_lambda': 7.063278064744544e-06, 'max_delta_step': 10}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 134. Best value: 0.625088:  85%|████████▌ | 170/200 [01:58<00:15,  1.95it/s]

[I 2025-11-10 18:27:29,392] Trial 168 finished with value: 0.616588693957115 and parameters: {'max_depth': 3, 'learning_rate': 0.0286550048563305, 'n_estimators': 351, 'subsample': 0.9820075148898714, 'colsample_bytree': 0.5408574300480014, 'min_child_weight': 1, 'gamma': 2.4375124022366466, 'reg_alpha': 0.00632610251861011, 'reg_lambda': 3.946241065814853e-06, 'max_delta_step': 10}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 134. Best value: 0.625088:  86%|████████▌ | 171/200 [01:58<00:14,  2.05it/s]

[I 2025-11-10 18:27:29,823] Trial 173 pruned.
[I 2025-11-10 18:27:29,839] Trial 172 pruned.

Best trial: 134. Best value: 0.625088:  86%|████████▋ | 173/200 [01:59<00:11,  2.29it/s]

[I 2025-11-10 18:27:30,574] Trial 175 pruned.

Best trial: 134. Best value: 0.625088:  87%|████████▋ | 174/200 [01:59<00:09,  2.64it/s]

[I 2025-11-10 18:27:30,774] Trial 171 pruned.

Best trial: 134. Best value: 0.625088:  88%|████████▊ | 175/200 [02:00<00:10,  2.47it/s]

[I 2025-11-10 18:27:31,256] Trial 177 pruned.

Best trial: 134. Best value: 0.625088:  88%|████████▊ | 177/200 [02:01<00:13,  1.67it/s]

[I 2025-11-10 18:27:32,367] Trial 169 finished with value: 0.5955750487329434 and parameters: {'max_depth': 3, 'learning_rate': 0.02949129140402605, 'n_estimators': 893, 'subsample': 0.9809951300889053, 'colsample_bytree': 0.5013130573954127, 'min_child_weight': 1, 'gamma': 2.7606049899918546, 'reg_alpha': 0.0009576352627721551, 'reg_lambda': 6.480280382566012e-06, 'max_delta_step': 10}. Best is trial 134 with value: 0.6250877192982456.
[I 2025-11-10 18:27:32,387] Trial 174 finished with value: 0.5811306042884989 and parameters: {'max_depth': 3, 'learning_rate': 0.03235790367062843, 'n_estimators': 363, 'subsample': 0.9755764076876561, 'colsample_bytree': 0.5411399369076871, 'min_child_weight': 1, 'gamma': 2.7959580217413564, 'reg_alpha': 0.00014344916607843277, 'reg_lambda': 1.7284580205649289e-06, 'max_delta_step': 10}. Best is trial 134 with value: 0.6250877192982456.
[I 2025-11-10 18:27:32,399] Trial 178 pruned.

Best trial: 134. Best value: 0.625088:  90%|████████▉ | 179/200 [02:01<00:06,  3.04it/s]

[I 2025-11-10 18:27:32,664] Trial 176 finished with value: 0.5958284600389863 and parameters: {'max_depth': 3, 'learning_rate': 0.02869613922221117, 'n_estimators': 235, 'subsample': 0.968698078564313, 'colsample_bytree': 0.5454086265804676, 'min_child_weight': 1, 'gamma': 2.4057158926279234, 'reg_alpha': 0.007901536111308607, 'reg_lambda': 1.3915087679005933e-05, 'max_delta_step': 10}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 134. Best value: 0.625088:  90%|█████████ | 180/200 [02:02<00:07,  2.75it/s]

[I 2025-11-10 18:27:33,163] Trial 181 pruned.

Best trial: 134. Best value: 0.625088:  90%|█████████ | 181/200 [02:04<00:13,  1.44it/s]

[I 2025-11-10 18:27:35,005] Trial 183 finished with value: 0.6199220272904483 and parameters: {'max_depth': 3, 'learning_rate': 0.028712062575971465, 'n_estimators': 271, 'subsample': 0.9903716112750149, 'colsample_bytree': 0.5007362083960764, 'min_child_weight': 1, 'gamma': 2.6838014932312113, 'reg_alpha': 0.025841782467634637, 'reg_lambda': 3.0078659279344614e-06, 'max_delta_step': 10}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 134. Best value: 0.625088:  91%|█████████ | 182/200 [02:05<00:16,  1.12it/s]

[I 2025-11-10 18:27:36,500] Trial 182 finished with value: 0.6122417153996101 and parameters: {'max_depth': 3, 'learning_rate': 0.029171810153171655, 'n_estimators': 660, 'subsample': 0.9917214172823449, 'colsample_bytree': 0.5014749556944208, 'min_child_weight': 1, 'gamma': 2.3443990794481557, 'reg_alpha': 0.0191125343770933, 'reg_lambda': 6.566347563915338e-06, 'max_delta_step': 10}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 134. Best value: 0.625088:  92%|█████████▏| 183/200 [02:05<00:13,  1.31it/s]

[I 2025-11-10 18:27:36,903] Trial 184 finished with value: 0.6069200779727095 and parameters: {'max_depth': 3, 'learning_rate': 0.028324094318545497, 'n_estimators': 267, 'subsample': 0.9911456875648856, 'colsample_bytree': 0.5018920508024645, 'min_child_weight': 1, 'gamma': 2.686502353888936, 'reg_alpha': 0.026197979846111108, 'reg_lambda': 2.677876116521841e-06, 'max_delta_step': 10}. Best is trial 134 with value: 0.6250877192982456.

Best trial: 180. Best value: 0.627329:  92%|█████████▏| 184/200 [02:06<00:10,  1.57it/s]

[I 2025-11-10 18:27:37,188] Trial 180 finished with value: 0.6273294346978557 and parameters: {'max_depth': 3, 'learning_rate': 0.025245144958174953, 'n_estimators': 797, 'subsample': 0.967200137327435, 'colsample_bytree': 0.5005881032637411, 'min_child_weight': 1, 'gamma': 2.393989000326891, 'reg_alpha': 0.0009826732541027845, 'reg_lambda': 2.624545182840353e-06, 'max_delta_step': 10}. Best is trial 180 with value: 0.6273294346978557.

Best trial: 180. Best value: 0.627329:  92%|█████████▎| 185/200 [02:06<00:07,  1.92it/s]

[I 2025-11-10 18:27:37,415] Trial 186 pruned.

Best trial: 180. Best value: 0.627329:  93%|█████████▎| 186/200 [02:06<00:05,  2.34it/s]

[I 2025-11-10 18:27:37,605] Trial 187 pruned.

[I 2025-11-10 18:27:37,844] Trial 188 pruned.

Best trial: 180. Best value: 0.627329:  94%|█████████▍| 188/200 [02:07<00:03,  3.16it/s]

[I 2025-11-10 18:27:38,022] Trial 179 finished with value: 0.5776608187134503 and parameters: {'max_depth': 3, 'learning_rate': 0.107520282401355, 'n_estimators': 1005, 'subsample': 0.9482869181040094, 'colsample_bytree': 0.50174341753902, 'min_child_weight': 1, 'gamma': 2.7243718649570194, 'reg_alpha': 0.0001860612440494485, 'reg_lambda': 2.7570189699909084e-06, 'max_delta_step': 3}. Best is trial 180 with value: 0.6273294346978557.

Best trial: 180. Best value: 0.627329:  94%|█████████▍| 189/200 [02:07<00:04,  2.61it/s]

[I 2025-11-10 18:27:38,571] Trial 185 finished with value: 0.5894152046783625 and parameters: {'max_depth': 3, 'learning_rate': 0.12351454723482416, 'n_estimators': 294, 'subsample': 0.9886931271968002, 'colsample_bytree': 0.5063555062405091, 'min_child_weight': 1, 'gamma': 2.669610072575314, 'reg_alpha': 0.02700612704389427, 'reg_lambda': 2.4230255136420785e-06, 'max_delta_step': 10}. Best is trial 180 with value: 0.6273294346978557.

Best trial: 180. Best value: 0.627329:  95%|█████████▌| 190/200 [02:07<00:03,  2.79it/s]

[I 2025-11-10 18:27:38,867] Trial 191 pruned.

Best trial: 180. Best value: 0.627329:  96%|█████████▌| 191/200 [02:08<00:04,  2.14it/s]

[I 2025-11-10 18:27:39,593] Trial 193 pruned.

Best trial: 180. Best value: 0.627329:  96%|█████████▌| 192/200 [02:10<00:06,  1.24it/s]

[I 2025-11-10 18:27:41,195] Trial 194 finished with value: 0.6185380116959064 and parameters: {'max_depth': 3, 'learning_rate': 0.030373312561194864, 'n_estimators': 207, 'subsample': 0.9823769439245322, 'colsample_bytree': 0.5197016198584695, 'min_child_weight': 1, 'gamma': 2.540031536039226, 'reg_alpha': 0.008425706562755247, 'reg_lambda': 1.2753817549009332e-06, 'max_delta_step': 10}. Best is trial 180 with value: 0.6273294346978557.

Best trial: 180. Best value: 0.627329:  96%|█████████▋| 193/200 [02:11<00:05,  1.25it/s]

[I 2025-11-10 18:27:41,990] Trial 189 finished with value: 0.6153411306042885 and parameters: {'max_depth': 3, 'learning_rate': 0.029756142657031893, 'n_estimators': 719, 'subsample': 0.9672808210014276, 'colsample_bytree': 0.5180373706145887, 'min_child_weight': 1, 'gamma': 2.5412300448819067, 'reg_alpha': 0.024408217238694352, 'reg_lambda': 1.5011487617397226e-06, 'max_delta_step': 10}. Best is trial 180 with value: 0.6273294346978557.

Best trial: 180. Best value: 0.627329:  97%|█████████▋| 194/200 [02:11<00:04,  1.42it/s]

[I 2025-11-10 18:27:42,459] Trial 190 finished with value: 0.6091617933723197 and parameters: {'max_depth': 3, 'learning_rate': 0.029017956348625626, 'n_estimators': 748, 'subsample': 0.9830090140122777, 'colsample_bytree': 0.5202967915125418, 'min_child_weight': 1, 'gamma': 2.367745909164903, 'reg_alpha': 0.05566608422273076, 'reg_lambda': 2.8844663387098595e-06, 'max_delta_step': 10}. Best is trial 180 with value: 0.6273294346978557.

Best trial: 180. Best value: 0.627329:  98%|█████████▊| 195/200 [02:11<00:02,  1.77it/s]

[I 2025-11-10 18:27:42,702] Trial 192 finished with value: 0.6156920077972708 and parameters: {'max_depth': 3, 'learning_rate': 0.029146747501230315, 'n_estimators': 656, 'subsample': 0.9810536069805242, 'colsample_bytree': 0.5193695180084181, 'min_child_weight': 1, 'gamma': 2.3325998841905675, 'reg_alpha': 0.014797432032249485, 'reg_lambda': 0.0008364402635959663, 'max_delta_step': 10}. Best is trial 180 with value: 0.6273294346978557.

Best trial: 180. Best value: 0.627329:  98%|█████████▊| 196/200 [02:13<00:04,  1.06s/it]

[I 2025-11-10 18:27:44,924] Trial 195 finished with value: 0.619766081871345 and parameters: {'max_depth': 3, 'learning_rate': 0.02521679661863493, 'n_estimators': 639, 'subsample': 0.9995837043131278, 'colsample_bytree': 0.5142297834620169, 'min_child_weight': 1, 'gamma': 2.5118370324227404, 'reg_alpha': 0.017987864703634282, 'reg_lambda': 1.470057548011434e-06, 'max_delta_step': 10}. Best is trial 180 with value: 0.6273294346978557.

Best trial: 196. Best value: 0.634834:  98%|█████████▊| 197/200 [02:14<00:02,  1.00it/s]

[I 2025-11-10 18:27:45,778] Trial 196 finished with value: 0.6348343079922028 and parameters: {'max_depth': 3, 'learning_rate': 0.03069223697312786, 'n_estimators': 658, 'subsample': 0.999457802049029, 'colsample_bytree': 0.5168182401951774, 'min_child_weight': 1, 'gamma': 2.1766487590317363, 'reg_alpha': 0.018012007258287128, 'reg_lambda': 1.0368115740190318e-06, 'max_delta_step': 10}. Best is trial 196 with value: 0.6348343079922028.

Best trial: 196. Best value: 0.634834:  99%|█████████▉| 198/200 [02:15<00:01,  1.07it/s]

[I 2025-11-10 18:27:46,559] Trial 197 finished with value: 0.6028849902534112 and parameters: {'max_depth': 3, 'learning_rate': 0.030041277744376867, 'n_estimators': 745, 'subsample': 0.9815412341627467, 'colsample_bytree': 0.5160552252806547, 'min_child_weight': 1, 'gamma': 2.396738482423332, 'reg_alpha': 0.01146357610299862, 'reg_lambda': 1.322048689853301e-06, 'max_delta_step': 10}. Best is trial 196 with value: 0.6348343079922028.

Best trial: 196. Best value: 0.634834: 100%|█████████▉| 199/200 [02:15<00:00,  1.41it/s]

[I 2025-11-10 18:27:46,746] Trial 198 finished with value: 0.6194346978557504 and parameters: {'max_depth': 3, 'learning_rate': 0.030746862682241916, 'n_estimators': 755, 'subsample': 0.9791308835918766, 'colsample_bytree': 0.5170717230884634, 'min_child_weight': 1, 'gamma': 2.1681427056522415, 'reg_alpha': 0.01687219035905353, 'reg_lambda': 1.1782959534517778e-06, 'max_delta_step': 10}. Best is trial 196 with value: 0.6348343079922028.

Best trial: 196. Best value: 0.634834: 100%|██████████| 200/200 [02:17<00:00,  1.46it/s]

[I 2025-11-10 18:27:48,216] Trial 199 finished with value: 0.5983235867446393 and parameters: {'max_depth': 3, 'learning_rate': 0.030617801835232977, 'n_estimators': 739, 'subsample': 0.9817548734527811, 'colsample_bytree': 0.5152294197966217, 'min_child_weight': 1, 'gamma': 2.3957920645556885, 'reg_alpha': 0.012681313721793321, 'reg_lambda': 1.3386488441595369e-06, 'max_delta_step': 10}. Best is trial 196 with value: 0.6348343079922028.

C:\Users\tenNovy\AppData\Local\Temp\ipykernel_11656\1094786132.py:137: RuntimeWarning:

More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.

[I 2025-11-10 18:27:49,161] A new study created in memory with name: 18_1_roc_auc
Best trial: 1. Best value: 0.5:   0%|          | 1/200 [00:02<06:47,  2.05s/it]

[I 2025-11-10 18:27:51,199] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1825738605991475, 'n_estimators': 483, 'subsample': 0.6864935830931251, 'colsample_bytree': 0.819877868150493, 'min_child_weight': 6, 'gamma': 3.7641065573899404, 'reg_alpha': 0.002398771637174003, 'reg_lambda': 1.7178604952120967e-05, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 0. Best value: 0.599844:   1%|          | 2/200 [00:03<05:23,  1.64s/it]

[I 2025-11-10 18:27:52,550] Trial 0 finished with value: 0.5998440545808967 and parameters: {'max_depth': 6, 'learning_rate': 0.19007699326397953, 'n_estimators': 793, 'subsample': 0.817908850100189, 'colsample_bytree': 0.77548611989812, 'min_child_weight': 4, 'gamma': 1.016904802237727, 'reg_alpha': 7.847921828945974e-05, 'reg_lambda': 0.7634334338155663, 'max_delta_step': 10}. Best is trial 0 with value: 0.5998440545808967.

Best trial: 0. Best value: 0.599844:   2%|▏         | 3/200 [00:03<03:31,  1.07s/it]

[I 2025-11-10 18:27:52,950] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.29313777334649616, 'n_estimators': 926, 'subsample': 0.8296539655708906, 'colsample_bytree': 0.830633866012849, 'min_child_weight': 10, 'gamma': 3.7437770699536905, 'reg_alpha': 5.5633031476277796e-05, 'reg_lambda': 0.0005254618905939233, 'max_delta_step': 0}. Best is trial 0 with value: 0.5998440545808967.

Best trial: 0. Best value: 0.599844:   2%|▏         | 4/200 [00:04<02:30,  1.31it/s]

[I 2025-11-10 18:27:53,250] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.036332414163899845, 'n_estimators': 495, 'subsample': 0.7455763234282049, 'colsample_bytree': 0.8228578530175465, 'min_child_weight': 5, 'gamma': 4.278907882227726, 'reg_alpha': 1.1226599938435793, 'reg_lambda': 2.2555006476885037e-06, 'max_delta_step': 9}. Best is trial 0 with value: 0.5998440545808967.

Best trial: 3. Best value: 0.608285:   2%|▎         | 5/200 [00:06<03:57,  1.22s/it]

[I 2025-11-10 18:27:55,270] Trial 3 finished with value: 0.6082846003898636 and parameters: {'max_depth': 4, 'learning_rate': 0.024715286805436835, 'n_estimators': 1176, 'subsample': 0.7303138823151911, 'colsample_bytree': 0.5458691657589552, 'min_child_weight': 2, 'gamma': 2.5654181687569033, 'reg_alpha': 0.6861543522209734, 'reg_lambda': 2.411270219673998e-07, 'max_delta_step': 3}. Best is trial 3 with value: 0.6082846003898636.

Best trial: 3. Best value: 0.608285:   3%|▎         | 6/200 [00:07<04:14,  1.31s/it]

[I 2025-11-10 18:27:56,762] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.2909985389597134, 'n_estimators': 1030, 'subsample': 0.5956256206775019, 'colsample_bytree': 0.8510221621708062, 'min_child_weight': 8, 'gamma': 2.380821236592957, 'reg_alpha': 0.04695040869322191, 'reg_lambda': 0.055028169400727404, 'max_delta_step': 3}. Best is trial 3 with value: 0.6082846003898636.

Best trial: 3. Best value: 0.608285:   4%|▎         | 7/200 [00:09<04:18,  1.34s/it]

[I 2025-11-10 18:27:58,164] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1368171690481054, 'n_estimators': 1244, 'subsample': 0.6805257061568983, 'colsample_bytree': 0.7325602090631345, 'min_child_weight': 6, 'gamma': 3.052954316125662, 'reg_alpha': 7.982071653905344e-06, 'reg_lambda': 4.0717601943335644e-07, 'max_delta_step': 6}. Best is trial 3 with value: 0.6082846003898636.

Best trial: 3. Best value: 0.608285:   4%|▍         | 8/200 [00:10<04:02,  1.26s/it]

[I 2025-11-10 18:27:59,264] Trial 6 finished with value: 0.579512670565302 and parameters: {'max_depth': 3, 'learning_rate': 0.1588250141007042, 'n_estimators': 1423, 'subsample': 0.9719125047533168, 'colsample_bytree': 0.8337254182762943, 'min_child_weight': 4, 'gamma': 2.080773641322899, 'reg_alpha': 0.017817392001314294, 'reg_lambda': 4.6834489634254727e-07, 'max_delta_step': 10}. Best is trial 3 with value: 0.6082846003898636.

Best trial: 3. Best value: 0.608285:   4%|▍         | 9/200 [00:11<03:39,  1.15s/it]

[I 2025-11-10 18:28:00,162] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.010908559762208007, 'n_estimators': 512, 'subsample': 0.9203497585551863, 'colsample_bytree': 0.5172326528892841, 'min_child_weight': 10, 'gamma': 4.523496686105611, 'reg_alpha': 0.2583219035006091, 'reg_lambda': 0.0004513114327872333, 'max_delta_step': 1}. Best is trial 3 with value: 0.6082846003898636.

Best trial: 3. Best value: 0.608285:   5%|▌         | 10/200 [00:11<02:52,  1.10it/s]

[I 2025-11-10 18:28:00,536] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03735145568643887, 'n_estimators': 1383, 'subsample': 0.7757452549171135, 'colsample_bytree': 0.5145930038245754, 'min_child_weight': 7, 'gamma': 4.7049669286253755, 'reg_alpha': 8.606832465029726e-06, 'reg_lambda': 0.05997738575251654, 'max_delta_step': 7}. Best is trial 3 with value: 0.6082846003898636.

Best trial: 3. Best value: 0.608285:   6%|▌         | 11/200 [00:11<02:31,  1.25it/s]

[I 2025-11-10 18:28:01,091] Trial 9 finished with value: 0.5905458089668616 and parameters: {'max_depth': 5, 'learning_rate': 0.034056123919013866, 'n_estimators': 1045, 'subsample': 0.996382513197388, 'colsample_bytree': 0.6640245935630273, 'min_child_weight': 5, 'gamma': 2.1534128063567626, 'reg_alpha': 1.844488565299002e-05, 'reg_lambda': 0.029411786095013513, 'max_delta_step': 7}. Best is trial 3 with value: 0.6082846003898636.

Best trial: 3. Best value: 0.608285:   6%|▋         | 13/200 [00:12<01:49,  1.71it/s]

[I 2025-11-10 18:28:01,787] Trial 13 pruned.
[I 2025-11-10 18:28:01,949] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.2000647058795465, 'n_estimators': 446, 'subsample': 0.8946217106717749, 'colsample_bytree': 0.57656362580513, 'min_child_weight': 8, 'gamma': 1.5275835399823663, 'reg_alpha': 0.12620561507936637, 'reg_lambda': 0.004726464672544006, 'max_delta_step': 0}. Best is trial 3 with value: 0.6082846003898636.

Best trial: 3. Best value: 0.608285:   7%|▋         | 14/200 [00:13<01:48,  1.72it/s]

[I 2025-11-10 18:28:02,526] Trial 11 finished with value: 0.4876023391812866 and parameters: {'max_depth': 5, 'learning_rate': 0.033834624712484454, 'n_estimators': 760, 'subsample': 0.7033836135434798, 'colsample_bytree': 0.6261271350581894, 'min_child_weight': 3, 'gamma': 2.7062306328632824, 'reg_alpha': 4.892555483520114, 'reg_lambda': 0.01253597540189639, 'max_delta_step': 8}. Best is trial 3 with value: 0.6082846003898636.

Best trial: 3. Best value: 0.608285:   8%|▊         | 15/200 [00:17<04:46,  1.55s/it]

[I 2025-11-10 18:28:06,309] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.06322500000945663, 'n_estimators': 729, 'subsample': 0.826334628454028, 'colsample_bytree': 0.9410222382863792, 'min_child_weight': 1, 'gamma': 0.2696493711775809, 'reg_alpha': 9.367655690922541, 'reg_lambda': 8.216576273595283, 'max_delta_step': 3}. Best is trial 3 with value: 0.6082846003898636.

Best trial: 3. Best value: 0.608285:   8%|▊         | 16/200 [00:17<03:32,  1.16s/it]

[I 2025-11-10 18:28:06,553] Trial 15 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.07607680805349926, 'n_estimators': 773, 'subsample': 0.8521151324503033, 'colsample_bytree': 0.946588806718467, 'min_child_weight': 1, 'gamma': 0.993503714420978, 'reg_alpha': 6.5703871099679425, 'reg_lambda': 2.522901226952038, 'max_delta_step': 4}. Best is trial 3 with value: 0.6082846003898636.
[I 2025-11-10 18:28:06,613] Trial 18 pruned.

Best trial: 3. Best value: 0.608285:   9%|▉         | 18/200 [00:17<02:10,  1.39it/s]

[I 2025-11-10 18:28:06,968] Trial 19 pruned.

Best trial: 3. Best value: 0.608285:  10%|▉         | 19/200 [00:18<02:16,  1.33it/s]

[I 2025-11-10 18:28:07,834] Trial 20 pruned.

Best trial: 3. Best value: 0.608285:  10%|█         | 20/200 [00:18<01:49,  1.65it/s]

[I 2025-11-10 18:28:08,028] Trial 21 pruned.

Best trial: 17. Best value: 0.660195:  12%|█▏        | 23/200 [00:19<01:05,  2.71it/s]

[I 2025-11-10 18:28:08,646] Trial 17 finished with value: 0.6601949317738791 and parameters: {'max_depth': 5, 'learning_rate': 0.08333980191328762, 'n_estimators': 755, 'subsample': 0.8389029413139689, 'colsample_bytree': 0.9819103660981845, 'min_child_weight': 1, 'gamma': 0.13095108542179035, 'reg_alpha': 0.0012430821680156953, 'reg_lambda': 3.410889112105733, 'max_delta_step': 4}. Best is trial 17 with value: 0.6601949317738791.
[I 2025-11-10 18:28:08,724] Trial 23 pruned.
[I 2025-11-10 18:28:08,762] Trial 22 pruned.

Best trial: 17. Best value: 0.660195:  12%|█▏        | 24/200 [00:19<01:01,  2.88it/s]

[I 2025-11-10 18:28:09,044] Trial 14 finished with value: 0.6020467836257309 and parameters: {'max_depth': 4, 'learning_rate': 0.014178624674687314, 'n_estimators': 803, 'subsample': 0.5047598171510924, 'colsample_bytree': 0.9772385162059418, 'min_child_weight': 1, 'gamma': 0.5200416423362935, 'reg_alpha': 1.7883203552981553e-08, 'reg_lambda': 1.5104201872478984e-08, 'max_delta_step': 4}. Best is trial 17 with value: 0.6601949317738791.

Best trial: 17. Best value: 0.660195:  12%|█▎        | 25/200 [00:20<01:11,  2.44it/s]

[I 2025-11-10 18:28:09,640] Trial 24 pruned.

Best trial: 17. Best value: 0.660195:  13%|█▎        | 26/200 [00:20<01:06,  2.63it/s]

[I 2025-11-10 18:28:09,938] Trial 26 pruned.

Best trial: 17. Best value: 0.660195:  14%|█▎        | 27/200 [00:21<01:01,  2.79it/s]

[I 2025-11-10 18:28:10,238] Trial 27 pruned.

Best trial: 17. Best value: 0.660195:  14%|█▍        | 28/200 [00:22<01:32,  1.86it/s]

[I 2025-11-10 18:28:11,223] Trial 28 pruned.
[I 2025-11-10 18:28:11,229] Trial 30 pruned.

Best trial: 17. Best value: 0.660195:  16%|█▌        | 31/200 [00:23<01:27,  1.92it/s]

[I 2025-11-10 18:28:12,763] Trial 31 pruned.
[I 2025-11-10 18:28:12,907] Trial 32 pruned.

Best trial: 17. Best value: 0.660195:  16%|█▌        | 32/200 [00:24<01:50,  1.52it/s]

[I 2025-11-10 18:28:13,962] Trial 34 pruned.

Best trial: 17. Best value: 0.660195:  16%|█▋        | 33/200 [00:25<01:32,  1.80it/s]

[I 2025-11-10 18:28:14,242] Trial 33 pruned.

Best trial: 17. Best value: 0.660195:  17%|█▋        | 34/200 [00:25<01:18,  2.11it/s]

[I 2025-11-10 18:28:14,502] Trial 25 finished with value: 0.6471150097465888 and parameters: {'max_depth': 6, 'learning_rate': 0.047304977631980466, 'n_estimators': 893, 'subsample': 0.8062081561875124, 'colsample_bytree': 0.7834302350966855, 'min_child_weight': 1, 'gamma': 0.11301130674379237, 'reg_alpha': 0.00014885225550030837, 'reg_lambda': 0.12239335682999454, 'max_delta_step': 4}. Best is trial 17 with value: 0.6601949317738791.

Best trial: 17. Best value: 0.660195:  18%|█▊        | 35/200 [00:25<01:14,  2.22it/s]

[I 2025-11-10 18:28:14,890] Trial 35 pruned.

Best trial: 17. Best value: 0.660195:  18%|█▊        | 36/200 [00:25<01:03,  2.58it/s]

[I 2025-11-10 18:28:15,124] Trial 36 pruned.

Best trial: 17. Best value: 0.660195:  19%|█▉        | 38/200 [00:26<00:58,  2.79it/s]

[I 2025-11-10 18:28:15,751] Trial 38 pruned.
[I 2025-11-10 18:28:15,871] Trial 37 pruned.

Best trial: 17. Best value: 0.660195:  20%|█▉        | 39/200 [00:27<01:20,  2.00it/s]

[I 2025-11-10 18:28:16,711] Trial 39 pruned.

Best trial: 17. Best value: 0.660195:  20%|██        | 40/200 [00:28<01:46,  1.50it/s]

[I 2025-11-10 18:28:17,764] Trial 40 pruned.

Best trial: 17. Best value: 0.660195:  20%|██        | 41/200 [00:29<01:37,  1.63it/s]

[I 2025-11-10 18:28:18,254] Trial 41 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.04185620297679668, 'n_estimators': 586, 'subsample': 0.5449516342567129, 'colsample_bytree': 0.9084392413793931, 'min_child_weight': 5, 'gamma': 2.4318570676367797, 'reg_alpha': 0.0073394258783051, 'reg_lambda': 0.16508426860221187, 'max_delta_step': 1}. Best is trial 17 with value: 0.6601949317738791.

Best trial: 17. Best value: 0.660195:  21%|██        | 42/200 [00:29<01:20,  1.97it/s]

[I 2025-11-10 18:28:18,512] Trial 29 finished with value: 0.6076023391812865 and parameters: {'max_depth': 3, 'learning_rate': 0.01027305989657059, 'n_estimators': 687, 'subsample': 0.5656300194479136, 'colsample_bytree': 0.9766418143778135, 'min_child_weight': 1, 'gamma': 0.4741043208701511, 'reg_alpha': 2.1393513307664627e-08, 'reg_lambda': 1.1791889707515833e-07, 'max_delta_step': 6}. Best is trial 17 with value: 0.6601949317738791.

Best trial: 17. Best value: 0.660195:  22%|██▏       | 43/200 [00:29<01:21,  1.92it/s]

[I 2025-11-10 18:28:19,070] Trial 44 pruned.

Best trial: 17. Best value: 0.660195:  22%|██▏       | 44/200 [00:30<01:25,  1.82it/s]

[I 2025-11-10 18:28:19,681] Trial 45 pruned.

Best trial: 17. Best value: 0.660195:  23%|██▎       | 46/200 [00:31<01:11,  2.15it/s]

[I 2025-11-10 18:28:20,405] Trial 42 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.018641592923118858, 'n_estimators': 935, 'subsample': 0.5539757075676299, 'colsample_bytree': 0.9257991482700331, 'min_child_weight': 5, 'gamma': 2.3539558733278567, 'reg_alpha': 2.952774488695073e-06, 'reg_lambda': 0.0014612212294075025, 'max_delta_step': 5}. Best is trial 17 with value: 0.6601949317738791.
[I 2025-11-10 18:28:20,547] Trial 47 pruned.

Best trial: 17. Best value: 0.660195:  24%|██▎       | 47/200 [00:32<01:29,  1.72it/s]

[I 2025-11-10 18:28:21,406] Trial 43 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.018290700612115955, 'n_estimators': 970, 'subsample': 0.5647081679768715, 'colsample_bytree': 0.5483293713995036, 'min_child_weight': 5, 'gamma': 2.3962540110049524, 'reg_alpha': 2.3037993119977036e-06, 'reg_lambda': 0.0019125534076933567, 'max_delta_step': 5}. Best is trial 17 with value: 0.6601949317738791.

Best trial: 17. Best value: 0.660195:  24%|██▍       | 48/200 [00:32<01:33,  1.62it/s]

[I 2025-11-10 18:28:22,105] Trial 48 pruned.

Best trial: 17. Best value: 0.660195:  24%|██▍       | 49/200 [00:33<01:42,  1.48it/s]

[I 2025-11-10 18:28:22,925] Trial 50 pruned.

Best trial: 17. Best value: 0.660195:  25%|██▌       | 50/200 [00:34<02:00,  1.25it/s]

[I 2025-11-10 18:28:24,019] Trial 49 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.012277789118083499, 'n_estimators': 847, 'subsample': 0.5301240062053565, 'colsample_bytree': 0.9769984855104649, 'min_child_weight': 9, 'gamma': 1.8758687324932592, 'reg_alpha': 2.444724109027171e-05, 'reg_lambda': 0.01960663412974571, 'max_delta_step': 4}. Best is trial 17 with value: 0.6601949317738791.

Best trial: 17. Best value: 0.660195:  26%|██▌       | 51/200 [00:35<02:11,  1.13it/s]

[I 2025-11-10 18:28:25,083] Trial 51 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0728045382817024, 'n_estimators': 781, 'subsample': 0.5291876955977461, 'colsample_bytree': 0.6235867189471271, 'min_child_weight': 9, 'gamma': 0.09008355410370866, 'reg_alpha': 0.10204764219868209, 'reg_lambda': 0.01768791738956555, 'max_delta_step': 4}. Best is trial 17 with value: 0.6601949317738791.

Best trial: 17. Best value: 0.660195:  26%|██▌       | 52/200 [00:36<02:09,  1.15it/s]

[I 2025-11-10 18:28:25,935] Trial 54 pruned.
[I 2025-11-10 18:28:26,025] Trial 52 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.09012844884085536, 'n_estimators': 748, 'subsample': 0.621743667975201, 'colsample_bytree': 0.8269756815725368, 'min_child_weight': 6, 'gamma': 4.965916190001931, 'reg_alpha': 0.14010007780521128, 'reg_lambda': 3.5986482552896736e-08, 'max_delta_step': 8}. Best is trial 17 with value: 0.6601949317738791.

Best trial: 17. Best value: 0.660195:  27%|██▋       | 54/200 [00:37<01:41,  1.43it/s]

[I 2025-11-10 18:28:26,923] Trial 55 pruned.
[I 2025-11-10 18:28:26,953] Trial 56 pruned.

Best trial: 17. Best value: 0.660195:  28%|██▊       | 56/200 [00:38<01:20,  1.80it/s]

[I 2025-11-10 18:28:27,602] Trial 46 finished with value: 0.607719298245614 and parameters: {'max_depth': 3, 'learning_rate': 0.01218422002395458, 'n_estimators': 870, 'subsample': 0.542827737128669, 'colsample_bytree': 0.9652756778560697, 'min_child_weight': 1, 'gamma': 0.8860854194487219, 'reg_alpha': 3.2486300483224554e-08, 'reg_lambda': 1.0190128285466913e-07, 'max_delta_step': 6}. Best is trial 17 with value: 0.6601949317738791.

Best trial: 17. Best value: 0.660195:  28%|██▊       | 57/200 [00:39<01:23,  1.71it/s]

[I 2025-11-10 18:28:28,296] Trial 53 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07322081592229363, 'n_estimators': 1032, 'subsample': 0.6234037860525793, 'colsample_bytree': 0.9315824723554201, 'min_child_weight': 6, 'gamma': 0.5738931862854695, 'reg_alpha': 5.460395011471299e-07, 'reg_lambda': 3.5453245921112174e-08, 'max_delta_step': 3}. Best is trial 17 with value: 0.6601949317738791.

Best trial: 17. Best value: 0.660195:  29%|██▉       | 58/200 [00:39<01:16,  1.86it/s]

[I 2025-11-10 18:28:28,680] Trial 58 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.15569254742891095, 'n_estimators': 390, 'subsample': 0.903006007275383, 'colsample_bytree': 0.9302373867100406, 'min_child_weight': 7, 'gamma': 2.701794626090265, 'reg_alpha': 2.1260029841171313e-07, 'reg_lambda': 1.128761374324981e-08, 'max_delta_step': 9}. Best is trial 17 with value: 0.6601949317738791.

Best trial: 17. Best value: 0.660195:  30%|██▉       | 59/200 [00:40<01:45,  1.33it/s]

[I 2025-11-10 18:28:30,046] Trial 61 pruned.

Best trial: 17. Best value: 0.660195:  30%|███       | 60/200 [00:42<02:02,  1.14it/s]

[I 2025-11-10 18:28:31,279] Trial 62 pruned.

Best trial: 17. Best value: 0.660195:  30%|███       | 61/200 [00:42<01:49,  1.27it/s]

[I 2025-11-10 18:28:31,824] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.1195574409380859, 'n_estimators': 1320, 'subsample': 0.8560623301666022, 'colsample_bytree': 0.7555838826441945, 'min_child_weight': 7, 'gamma': 2.656701985672375, 'reg_alpha': 3.339917197897101e-07, 'reg_lambda': 1.2544420632124095e-08, 'max_delta_step': 9}. Best is trial 17 with value: 0.6601949317738791.

Best trial: 17. Best value: 0.660195:  31%|███       | 62/200 [00:43<01:46,  1.30it/s]

[I 2025-11-10 18:28:32,551] Trial 64 pruned.

Best trial: 17. Best value: 0.660195:  32%|███▏      | 63/200 [00:44<01:58,  1.16it/s]

[I 2025-11-10 18:28:33,645] Trial 65 pruned.

Best trial: 17. Best value: 0.660195:  32%|███▏      | 64/200 [00:45<01:55,  1.18it/s]

[I 2025-11-10 18:28:34,469] Trial 66 pruned.

Best trial: 17. Best value: 0.660195:  32%|███▎      | 65/200 [00:46<01:55,  1.17it/s]

[I 2025-11-10 18:28:35,341] Trial 67 pruned.

Best trial: 59. Best value: 0.704639:  33%|███▎      | 66/200 [00:46<01:47,  1.25it/s]

[I 2025-11-10 18:28:36,006] Trial 59 finished with value: 0.7046393762183236 and parameters: {'max_depth': 3, 'learning_rate': 0.015358193171965018, 'n_estimators': 1038, 'subsample': 0.7171668196413468, 'colsample_bytree': 0.9968907256789461, 'min_child_weight': 1, 'gamma': 2.6306336624135316, 'reg_alpha': 2.6364000436287057e-08, 'reg_lambda': 1.3389054579244893e-08, 'max_delta_step': 6}. Best is trial 59 with value: 0.7046393762183236.

Best trial: 59. Best value: 0.704639:  34%|███▎      | 67/200 [00:48<02:20,  1.05s/it]

[I 2025-11-10 18:28:37,661] Trial 69 pruned.

Best trial: 59. Best value: 0.704639:  34%|███▍      | 68/200 [00:49<02:02,  1.08it/s]

[I 2025-11-10 18:28:38,280] Trial 60 finished with value: 0.6445224171539962 and parameters: {'max_depth': 3, 'learning_rate': 0.016659989359533025, 'n_estimators': 1308, 'subsample': 0.7163754906670639, 'colsample_bytree': 0.9979870744519028, 'min_child_weight': 1, 'gamma': 0.24397309177202084, 'reg_alpha': 1.3028651645839745e-07, 'reg_lambda': 1.0631973973151923e-08, 'max_delta_step': 6}. Best is trial 59 with value: 0.7046393762183236.

Best trial: 63. Best value: 0.705029:  34%|███▍      | 69/200 [00:49<01:42,  1.27it/s]

[I 2025-11-10 18:28:38,741] Trial 63 finished with value: 0.7050292397660819 and parameters: {'max_depth': 3, 'learning_rate': 0.013088010530945408, 'n_estimators': 911, 'subsample': 0.7744988415152444, 'colsample_bytree': 0.9578929803910683, 'min_child_weight': 1, 'gamma': 2.8863859729765022, 'reg_alpha': 1.182070097941969e-08, 'reg_lambda': 1.1899555683235273e-05, 'max_delta_step': 6}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  35%|███▌      | 70/200 [00:49<01:24,  1.54it/s]

[I 2025-11-10 18:28:39,065] Trial 70 pruned.

Best trial: 63. Best value: 0.705029:  36%|███▌      | 71/200 [00:50<01:31,  1.41it/s]

[I 2025-11-10 18:28:39,911] Trial 72 pruned.
[I 2025-11-10 18:28:39,931] Trial 71 pruned.

Best trial: 63. Best value: 0.705029:  36%|███▋      | 73/200 [00:51<01:19,  1.59it/s]

[I 2025-11-10 18:28:40,987] Trial 73 pruned.

Best trial: 63. Best value: 0.705029:  37%|███▋      | 74/200 [00:52<01:15,  1.67it/s]

[I 2025-11-10 18:28:41,500] Trial 75 pruned.

Best trial: 63. Best value: 0.705029:  38%|███▊      | 75/200 [00:55<02:46,  1.33s/it]

[I 2025-11-10 18:28:44,907] Trial 68 finished with value: 0.6985964912280702 and parameters: {'max_depth': 4, 'learning_rate': 0.011158697699015858, 'n_estimators': 868, 'subsample': 0.7528270425623865, 'colsample_bytree': 0.9498058911289937, 'min_child_weight': 1, 'gamma': 0.7277528608353121, 'reg_alpha': 0.01407506402419521, 'reg_lambda': 0.2966335337039241, 'max_delta_step': 8}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  38%|███▊      | 76/200 [00:58<03:45,  1.82s/it]

[I 2025-11-10 18:28:48,029] Trial 77 finished with value: 0.6837816764132554 and parameters: {'max_depth': 3, 'learning_rate': 0.015057755122786275, 'n_estimators': 881, 'subsample': 0.7481393768792444, 'colsample_bytree': 0.9950404797507779, 'min_child_weight': 1, 'gamma': 2.8121794901514834, 'reg_alpha': 1.0295434306595766e-08, 'reg_lambda': 3.2570159948701074e-07, 'max_delta_step': 5}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  39%|███▉      | 78/200 [00:59<02:04,  1.02s/it]

[I 2025-11-10 18:28:48,251] Trial 74 finished with value: 0.6895711500974658 and parameters: {'max_depth': 3, 'learning_rate': 0.013578742333486138, 'n_estimators': 1160, 'subsample': 0.6653913919079544, 'colsample_bytree': 0.9705502018644971, 'min_child_weight': 1, 'gamma': 2.571944627049449, 'reg_alpha': 4.962110655424442e-08, 'reg_lambda': 1.962614827365735e-07, 'max_delta_step': 6}. Best is trial 63 with value: 0.7050292397660819.
[I 2025-11-10 18:28:48,385] Trial 76 finished with value: 0.6943859649122807 and parameters: {'max_depth': 3, 'learning_rate': 0.010112178840547804, 'n_estimators': 859, 'subsample': 0.7441616478451235, 'colsample_bytree': 0.9934510096644834, 'min_child_weight': 1, 'gamma': 2.5424950339480388, 'reg_alpha': 3.086582012303145e-08, 'reg_lambda': 1.9036937172301665e-07, 'max_delta_step': 5}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  40%|███▉      | 79/200 [01:00<02:10,  1.08s/it]

[I 2025-11-10 18:28:49,618] Trial 81 pruned.

Best trial: 63. Best value: 0.705029:  40%|████      | 80/200 [01:01<02:24,  1.21s/it]

[I 2025-11-10 18:28:51,123] Trial 82 pruned.

Best trial: 63. Best value: 0.705029:  40%|████      | 81/200 [01:03<02:46,  1.40s/it]

[I 2025-11-10 18:28:52,975] Trial 78 finished with value: 0.6817933723196881 and parameters: {'max_depth': 4, 'learning_rate': 0.017759233665423067, 'n_estimators': 1167, 'subsample': 0.74818405779401, 'colsample_bytree': 0.9886610289289948, 'min_child_weight': 1, 'gamma': 2.87816332204489, 'reg_alpha': 0.004452637975931886, 'reg_lambda': 0.05583799305187864, 'max_delta_step': 5}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  41%|████      | 82/200 [01:06<03:32,  1.80s/it]

[I 2025-11-10 18:28:55,739] Trial 80 finished with value: 0.6884600389863548 and parameters: {'max_depth': 4, 'learning_rate': 0.017616277964471332, 'n_estimators': 1076, 'subsample': 0.7457054616644363, 'colsample_bytree': 0.9872040241863445, 'min_child_weight': 1, 'gamma': 2.892880195442604, 'reg_alpha': 0.0044804614402733315, 'reg_lambda': 4.282705865325723e-05, 'max_delta_step': 5}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  42%|████▏     | 83/200 [01:06<02:37,  1.35s/it]

[I 2025-11-10 18:28:56,020] Trial 79 finished with value: 0.6901949317738791 and parameters: {'max_depth': 4, 'learning_rate': 0.016544934252271888, 'n_estimators': 1175, 'subsample': 0.7451143115516476, 'colsample_bytree': 0.9383191608002867, 'min_child_weight': 1, 'gamma': 2.7981260574753315, 'reg_alpha': 0.0035585051473604923, 'reg_lambda': 5.545450613250783e-05, 'max_delta_step': 5}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  42%|████▏     | 84/200 [01:08<02:50,  1.47s/it]

[I 2025-11-10 18:28:57,765] Trial 83 finished with value: 0.6879922027290448 and parameters: {'max_depth': 3, 'learning_rate': 0.014490879828307346, 'n_estimators': 852, 'subsample': 0.7790501771511735, 'colsample_bytree': 0.9436524236221937, 'min_child_weight': 1, 'gamma': 1.9886192248430667, 'reg_alpha': 0.01126641595824283, 'reg_lambda': 8.502470603860482e-07, 'max_delta_step': 8}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  42%|████▎     | 85/200 [01:11<03:48,  1.99s/it]

[I 2025-11-10 18:29:00,983] Trial 84 finished with value: 0.6835282651072124 and parameters: {'max_depth': 3, 'learning_rate': 0.015213178459348354, 'n_estimators': 1148, 'subsample': 0.7708807553439319, 'colsample_bytree': 0.9374467874025313, 'min_child_weight': 1, 'gamma': 2.5899303421871784, 'reg_alpha': 0.013099199652354298, 'reg_lambda': 0.2718833576200745, 'max_delta_step': 5}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  43%|████▎     | 86/200 [01:13<03:26,  1.81s/it]

[I 2025-11-10 18:29:02,385] Trial 88 pruned.

Best trial: 63. Best value: 0.705029:  44%|████▎     | 87/200 [01:14<03:03,  1.63s/it]

[I 2025-11-10 18:29:03,574] Trial 85 finished with value: 0.6798245614035088 and parameters: {'max_depth': 4, 'learning_rate': 0.014696518953481369, 'n_estimators': 1113, 'subsample': 0.7751470859185035, 'colsample_bytree': 0.9411046743162932, 'min_child_weight': 1, 'gamma': 3.2040905411294816, 'reg_alpha': 0.003965266299288435, 'reg_lambda': 6.102921433421701e-05, 'max_delta_step': 5}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  44%|████▍     | 88/200 [01:14<02:22,  1.27s/it]

[I 2025-11-10 18:29:04,023] Trial 86 finished with value: 0.6948927875243665 and parameters: {'max_depth': 4, 'learning_rate': 0.014982575387680983, 'n_estimators': 1153, 'subsample': 0.7765528562534084, 'colsample_bytree': 0.9380197298075704, 'min_child_weight': 1, 'gamma': 3.200684277600934, 'reg_alpha': 0.017243432110797645, 'reg_lambda': 3.956506056553381e-05, 'max_delta_step': 5}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  44%|████▍     | 89/200 [01:15<02:04,  1.12s/it]

[I 2025-11-10 18:29:04,792] Trial 90 pruned.

Best trial: 63. Best value: 0.705029:  45%|████▌     | 90/200 [01:16<01:41,  1.08it/s]

[I 2025-11-10 18:29:05,255] Trial 91 pruned.

Best trial: 63. Best value: 0.705029:  46%|████▌     | 91/200 [01:16<01:25,  1.27it/s]

[I 2025-11-10 18:29:05,712] Trial 87 finished with value: 0.686120857699805 and parameters: {'max_depth': 3, 'learning_rate': 0.01427453165396263, 'n_estimators': 1108, 'subsample': 0.77637285836736, 'colsample_bytree': 0.9397529124870181, 'min_child_weight': 1, 'gamma': 3.1861682300415524, 'reg_alpha': 0.030065449648463093, 'reg_lambda': 6.188888015263784e-05, 'max_delta_step': 8}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  46%|████▌     | 92/200 [01:17<01:34,  1.14it/s]

[I 2025-11-10 18:29:06,802] Trial 93 pruned.

Best trial: 63. Best value: 0.705029:  46%|████▋     | 93/200 [01:18<01:23,  1.28it/s]

[I 2025-11-10 18:29:07,365] Trial 94 pruned.

Best trial: 63. Best value: 0.705029:  47%|████▋     | 94/200 [01:20<02:22,  1.35s/it]

[I 2025-11-10 18:29:10,026] Trial 89 finished with value: 0.6784600389863547 and parameters: {'max_depth': 3, 'learning_rate': 0.019208853598732714, 'n_estimators': 1099, 'subsample': 0.8007023476936236, 'colsample_bytree': 0.9216853733643657, 'min_child_weight': 1, 'gamma': 2.056390192754897, 'reg_alpha': 0.01769451083061742, 'reg_lambda': 3.431778743183519e-05, 'max_delta_step': 8}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  48%|████▊     | 95/200 [01:23<03:03,  1.75s/it]

[I 2025-11-10 18:29:12,708] Trial 92 finished with value: 0.6551267056530213 and parameters: {'max_depth': 4, 'learning_rate': 0.011129148359836772, 'n_estimators': 1097, 'subsample': 0.7973283555339851, 'colsample_bytree': 0.9257002805500213, 'min_child_weight': 1, 'gamma': 3.9805958813793927, 'reg_alpha': 0.016138352332761216, 'reg_lambda': 6.511084267331801e-06, 'max_delta_step': 6}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  48%|████▊     | 96/200 [01:26<03:27,  2.00s/it]

[I 2025-11-10 18:29:15,296] Trial 95 finished with value: 0.6792007797270956 and parameters: {'max_depth': 3, 'learning_rate': 0.013129559708323586, 'n_estimators': 1226, 'subsample': 0.786808525167097, 'colsample_bytree': 0.9469646079204753, 'min_child_weight': 1, 'gamma': 3.129954683017155, 'reg_alpha': 0.02667749275328479, 'reg_lambda': 0.00017006551208010722, 'max_delta_step': 8}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  48%|████▊     | 97/200 [01:26<02:36,  1.52s/it]

[I 2025-11-10 18:29:15,687] Trial 96 finished with value: 0.6835282651072124 and parameters: {'max_depth': 3, 'learning_rate': 0.0167179055288674, 'n_estimators': 1262, 'subsample': 0.7650395390012292, 'colsample_bytree': 0.8976516259405828, 'min_child_weight': 1, 'gamma': 2.4732470115852934, 'reg_alpha': 0.03215749482830445, 'reg_lambda': 6.2970330356650315e-06, 'max_delta_step': 8}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  50%|████▉     | 99/200 [01:27<01:42,  1.01s/it]

[I 2025-11-10 18:29:16,789] Trial 99 pruned.
[I 2025-11-10 18:29:16,921] Trial 100 pruned.

Best trial: 63. Best value: 0.705029:  50%|█████     | 100/200 [01:29<02:08,  1.29s/it]

[I 2025-11-10 18:29:18,844] Trial 97 finished with value: 0.6897270955165692 and parameters: {'max_depth': 3, 'learning_rate': 0.01735237519215326, 'n_estimators': 1263, 'subsample': 0.7618965123926491, 'colsample_bytree': 0.9630585037350057, 'min_child_weight': 1, 'gamma': 2.4727600170039428, 'reg_alpha': 0.058809112650065526, 'reg_lambda': 6.1835169458390515e-06, 'max_delta_step': 7}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  50%|█████     | 101/200 [01:31<02:28,  1.50s/it]

[I 2025-11-10 18:29:20,859] Trial 98 finished with value: 0.6902144249512671 and parameters: {'max_depth': 3, 'learning_rate': 0.01747559499818024, 'n_estimators': 1217, 'subsample': 0.7586914259376655, 'colsample_bytree': 0.9038261203107756, 'min_child_weight': 1, 'gamma': 2.4818159635226418, 'reg_alpha': 0.03684229307049823, 'reg_lambda': 9.574702249525204e-07, 'max_delta_step': 7}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  51%|█████     | 102/200 [01:35<03:30,  2.15s/it]

[I 2025-11-10 18:29:24,506] Trial 101 finished with value: 0.6842690058479532 and parameters: {'max_depth': 3, 'learning_rate': 0.017937699891754255, 'n_estimators': 1146, 'subsample': 0.7343907300661571, 'colsample_bytree': 0.9620852330813467, 'min_child_weight': 1, 'gamma': 2.7223649265069376, 'reg_alpha': 0.0005764770118533502, 'reg_lambda': 8.026268766487782e-07, 'max_delta_step': 7}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  52%|█████▏    | 103/200 [01:37<03:28,  2.15s/it]

[I 2025-11-10 18:29:26,647] Trial 102 finished with value: 0.6961208576998051 and parameters: {'max_depth': 4, 'learning_rate': 0.010066312096437009, 'n_estimators': 1166, 'subsample': 0.7388327977404536, 'colsample_bytree': 0.9832505179715898, 'min_child_weight': 1, 'gamma': 1.6817662720520592, 'reg_alpha': 0.06625598715324371, 'reg_lambda': 1.9466069814973518e-05, 'max_delta_step': 10}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  52%|█████▏    | 104/200 [01:38<02:54,  1.82s/it]

[I 2025-11-10 18:29:27,701] Trial 103 finished with value: 0.6983430799220274 and parameters: {'max_depth': 4, 'learning_rate': 0.010057203885166684, 'n_estimators': 1152, 'subsample': 0.7342808681083038, 'colsample_bytree': 0.9834346897876237, 'min_child_weight': 1, 'gamma': 2.7305016412584417, 'reg_alpha': 0.06887115285288035, 'reg_lambda': 2.1140600902918482e-06, 'max_delta_step': 6}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  52%|█████▎    | 105/200 [01:39<02:24,  1.52s/it]

[I 2025-11-10 18:29:28,521] Trial 106 pruned.

Best trial: 63. Best value: 0.705029:  53%|█████▎    | 106/200 [01:40<02:01,  1.29s/it]

[I 2025-11-10 18:29:29,286] Trial 104 finished with value: 0.6793372319688109 and parameters: {'max_depth': 3, 'learning_rate': 0.015580156348866513, 'n_estimators': 1208, 'subsample': 0.733531785435541, 'colsample_bytree': 0.9824314482267832, 'min_child_weight': 1, 'gamma': 2.716557571625061, 'reg_alpha': 0.007239864761384102, 'reg_lambda': 8.36624508191198e-07, 'max_delta_step': 6}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  54%|█████▎    | 107/200 [01:41<01:50,  1.19s/it]

[I 2025-11-10 18:29:30,224] Trial 108 pruned.

Best trial: 63. Best value: 0.705029:  54%|█████▍    | 108/200 [01:41<01:33,  1.02s/it]

[I 2025-11-10 18:29:30,842] Trial 109 pruned.

Best trial: 63. Best value: 0.705029:  55%|█████▍    | 109/200 [01:43<01:41,  1.11s/it]

[I 2025-11-10 18:29:32,181] Trial 110 pruned.

Best trial: 63. Best value: 0.705029:  55%|█████▌    | 110/200 [01:43<01:26,  1.04it/s]

[I 2025-11-10 18:29:32,776] Trial 111 pruned.

Best trial: 63. Best value: 0.705029:  56%|█████▌    | 111/200 [01:44<01:22,  1.08it/s]

[I 2025-11-10 18:29:33,637] Trial 105 finished with value: 0.6887134502923976 and parameters: {'max_depth': 3, 'learning_rate': 0.01572785203798624, 'n_estimators': 1202, 'subsample': 0.7525584688266311, 'colsample_bytree': 0.9831861203483291, 'min_child_weight': 1, 'gamma': 1.6746219275393415, 'reg_alpha': 0.06407562155635599, 'reg_lambda': 1.9767689955707187e-06, 'max_delta_step': 6}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  56%|█████▌    | 112/200 [01:45<01:13,  1.20it/s]

[I 2025-11-10 18:29:34,247] Trial 112 pruned.

Best trial: 63. Best value: 0.705029:  56%|█████▋    | 113/200 [01:45<01:01,  1.41it/s]

[I 2025-11-10 18:29:34,671] Trial 113 pruned.

Best trial: 63. Best value: 0.705029:  57%|█████▋    | 114/200 [01:48<01:58,  1.38s/it]

[I 2025-11-10 18:29:37,601] Trial 107 finished with value: 0.6921637426900585 and parameters: {'max_depth': 4, 'learning_rate': 0.010609332256685373, 'n_estimators': 1203, 'subsample': 0.7087697133913461, 'colsample_bytree': 0.9714562089983108, 'min_child_weight': 1, 'gamma': 2.6234309079692886, 'reg_alpha': 0.06885018078511043, 'reg_lambda': 2.6482528732108466e-06, 'max_delta_step': 6}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  57%|█████▊    | 115/200 [01:49<01:42,  1.21s/it]

[I 2025-11-10 18:29:38,414] Trial 116 pruned.

Best trial: 63. Best value: 0.705029:  58%|█████▊    | 116/200 [01:50<01:30,  1.07s/it]

[I 2025-11-10 18:29:39,178] Trial 117 pruned.

Best trial: 63. Best value: 0.705029:  58%|█████▊    | 117/200 [01:50<01:26,  1.04s/it]

[I 2025-11-10 18:29:40,132] Trial 118 pruned.

Best trial: 63. Best value: 0.705029:  59%|█████▉    | 118/200 [01:51<01:22,  1.01s/it]

[I 2025-11-10 18:29:41,079] Trial 119 pruned.

Best trial: 63. Best value: 0.705029:  60%|█████▉    | 119/200 [01:52<01:23,  1.03s/it]

[I 2025-11-10 18:29:42,153] Trial 121 pruned.

Best trial: 63. Best value: 0.705029:  60%|██████    | 120/200 [01:53<01:20,  1.01s/it]

[I 2025-11-10 18:29:43,114] Trial 114 finished with value: 0.672046783625731 and parameters: {'max_depth': 3, 'learning_rate': 0.01171063975513934, 'n_estimators': 1238, 'subsample': 0.6939084784314818, 'colsample_bytree': 0.9689691363514276, 'min_child_weight': 1, 'gamma': 2.638451148489438, 'reg_alpha': 0.04456654967054791, 'reg_lambda': 2.2658049296836635e-06, 'max_delta_step': 10}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  60%|██████    | 121/200 [01:54<01:12,  1.10it/s]

[I 2025-11-10 18:29:43,803] Trial 115 finished with value: 0.6924171539961014 and parameters: {'max_depth': 3, 'learning_rate': 0.010900504614580373, 'n_estimators': 1136, 'subsample': 0.7565270172324988, 'colsample_bytree': 0.967943397253843, 'min_child_weight': 1, 'gamma': 1.5836697630578964, 'reg_alpha': 0.038590022079460946, 'reg_lambda': 4.122178903226739e-07, 'max_delta_step': 6}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  61%|██████    | 122/200 [01:54<00:57,  1.35it/s]

[I 2025-11-10 18:29:44,144] Trial 122 pruned.

Best trial: 63. Best value: 0.705029:  62%|██████▏   | 123/200 [01:56<01:16,  1.01it/s]

[I 2025-11-10 18:29:45,709] Trial 124 pruned.

Best trial: 63. Best value: 0.705029:  62%|██████▏   | 124/200 [01:56<00:58,  1.29it/s]

[I 2025-11-10 18:29:45,983] Trial 125 pruned.

Best trial: 63. Best value: 0.705029:  62%|██████▎   | 125/200 [01:57<00:58,  1.28it/s]

[I 2025-11-10 18:29:46,785] Trial 123 pruned.

Best trial: 63. Best value: 0.705029:  63%|██████▎   | 126/200 [01:58<01:03,  1.17it/s]

[I 2025-11-10 18:29:47,811] Trial 127 pruned.

Best trial: 63. Best value: 0.705029:  64%|██████▎   | 127/200 [01:59<00:58,  1.24it/s]

[I 2025-11-10 18:29:48,499] Trial 129 pruned.

Best trial: 63. Best value: 0.705029:  64%|██████▍   | 128/200 [02:00<01:09,  1.04it/s]

[I 2025-11-10 18:29:49,827] Trial 120 finished with value: 0.6980896686159844 and parameters: {'max_depth': 4, 'learning_rate': 0.01353752861818651, 'n_estimators': 1317, 'subsample': 0.7247757227352715, 'colsample_bytree': 0.9607238905917139, 'min_child_weight': 1, 'gamma': 3.0561269131264113, 'reg_alpha': 0.031135737407823494, 'reg_lambda': 8.714893006368842e-06, 'max_delta_step': 5}. Best is trial 63 with value: 0.7050292397660819.

Best trial: 63. Best value: 0.705029:  64%|██████▍   | 129/200 [02:02<01:20,  1.14s/it]

[I 2025-11-10 18:29:51,373] Trial 131 pruned.

Best trial: 126. Best value: 0.707135:  65%|██████▌   | 130/200 [02:06<02:16,  1.96s/it]

[I 2025-11-10 18:29:55,240] Trial 128 finished with value: 0.6945224171539961 and parameters: {'max_depth': 4, 'learning_rate': 0.010971862503746857, 'n_estimators': 1064, 'subsample': 0.7464774560929225, 'colsample_bytree': 0.9554712555125446, 'min_child_weight': 1, 'gamma': 2.3968101584485875, 'reg_alpha': 0.009426025710863163, 'reg_lambda': 1.3036907141331486e-06, 'max_delta_step': 5}. Best is trial 63 with value: 0.7050292397660819.
[I 2025-11-10 18:29:55,282] Trial 126 finished with value: 0.7071345029239765 and parameters: {'max_depth': 3, 'learning_rate': 0.010435552954228162, 'n_estimators': 1130, 'subsample': 0.7803067307368368, 'colsample_bytree': 0.9514728909244374, 'min_child_weight': 1, 'gamma': 1.2533961316402946, 'reg_alpha': 0.024631945471370664, 'reg_lambda': 3.8308451887241105e-06, 'max_delta_step': 6}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  66%|██████▌   | 132/200 [02:07<01:38,  1.45s/it]

[I 2025-11-10 18:29:56,980] Trial 130 finished with value: 0.692300194931774 and parameters: {'max_depth': 3, 'learning_rate': 0.012208369157725937, 'n_estimators': 1126, 'subsample': 0.7457296821193635, 'colsample_bytree': 0.9976418618933507, 'min_child_weight': 1, 'gamma': 2.2696771696082876, 'reg_alpha': 0.010374591409208305, 'reg_lambda': 1.418738640230996e-07, 'max_delta_step': 7}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  66%|██████▋   | 133/200 [02:09<01:33,  1.40s/it]

[I 2025-11-10 18:29:58,209] Trial 132 finished with value: 0.6899415204678363 and parameters: {'max_depth': 5, 'learning_rate': 0.011053872204151192, 'n_estimators': 836, 'subsample': 0.7462379006156458, 'colsample_bytree': 0.9919772436707209, 'min_child_weight': 1, 'gamma': 3.0218843576693626, 'reg_alpha': 0.036741997325107745, 'reg_lambda': 9.320315790622575e-06, 'max_delta_step': 4}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  67%|██████▋   | 134/200 [02:09<01:21,  1.23s/it]

[I 2025-11-10 18:29:58,980] Trial 134 pruned.

Best trial: 126. Best value: 0.707135:  68%|██████▊   | 135/200 [02:11<01:35,  1.47s/it]

[I 2025-11-10 18:30:01,080] Trial 135 pruned.

Best trial: 126. Best value: 0.707135:  68%|██████▊   | 136/200 [02:12<01:24,  1.32s/it]

[I 2025-11-10 18:30:02,012] Trial 136 pruned.

Best trial: 126. Best value: 0.707135:  68%|██████▊   | 137/200 [02:13<01:16,  1.21s/it]

[I 2025-11-10 18:30:02,958] Trial 138 pruned.

Best trial: 126. Best value: 0.707135:  70%|██████▉   | 139/200 [02:14<00:47,  1.28it/s]

[I 2025-11-10 18:30:03,628] Trial 133 finished with value: 0.6864912280701755 and parameters: {'max_depth': 5, 'learning_rate': 0.010772067234157643, 'n_estimators': 1068, 'subsample': 0.7484360171532514, 'colsample_bytree': 0.9919447907643839, 'min_child_weight': 1, 'gamma': 3.4491917203304983, 'reg_alpha': 0.036604953204182215, 'reg_lambda': 6.766318223351858e-07, 'max_delta_step': 4}. Best is trial 126 with value: 0.7071345029239765.
[I 2025-11-10 18:30:03,744] Trial 139 pruned.

Best trial: 126. Best value: 0.707135:  70%|███████   | 140/200 [02:15<00:53,  1.13it/s]

[I 2025-11-10 18:30:04,889] Trial 141 pruned.

Best trial: 126. Best value: 0.707135:  70%|███████   | 141/200 [02:16<00:42,  1.38it/s]

[I 2025-11-10 18:30:05,228] Trial 142 pruned.

Best trial: 126. Best value: 0.707135:  71%|███████   | 142/200 [02:16<00:38,  1.51it/s]

[I 2025-11-10 18:30:05,735] Trial 143 pruned.

Best trial: 126. Best value: 0.707135:  72%|███████▏  | 143/200 [02:19<01:12,  1.28s/it]

[I 2025-11-10 18:30:08,456] Trial 137 finished with value: 0.7053996101364521 and parameters: {'max_depth': 4, 'learning_rate': 0.011729333955947418, 'n_estimators': 1068, 'subsample': 0.7321664425557018, 'colsample_bytree': 0.9990896399024063, 'min_child_weight': 1, 'gamma': 1.2003648964069276, 'reg_alpha': 0.019469055246861145, 'reg_lambda': 6.700588567899466e-07, 'max_delta_step': 6}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  72%|███████▏  | 144/200 [02:21<01:34,  1.69s/it]

[I 2025-11-10 18:30:11,129] Trial 140 finished with value: 0.7066471734892787 and parameters: {'max_depth': 3, 'learning_rate': 0.012529944981371235, 'n_estimators': 1040, 'subsample': 0.7689213076605708, 'colsample_bytree': 0.9997770736220168, 'min_child_weight': 1, 'gamma': 2.2378272186326846, 'reg_alpha': 0.00829879223881254, 'reg_lambda': 1.8103808514879574e-07, 'max_delta_step': 5}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  72%|███████▎  | 145/200 [02:24<01:45,  1.93s/it]

[I 2025-11-10 18:30:13,605] Trial 144 finished with value: 0.6916959064327486 and parameters: {'max_depth': 4, 'learning_rate': 0.0157750956219217, 'n_estimators': 1176, 'subsample': 0.7699610689042055, 'colsample_bytree': 0.923842989895139, 'min_child_weight': 1, 'gamma': 1.8243535186398654, 'reg_alpha': 0.021753256822278546, 'reg_lambda': 2.6934071449028392e-05, 'max_delta_step': 5}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  73%|███████▎  | 146/200 [02:24<01:20,  1.50s/it]

[I 2025-11-10 18:30:14,092] Trial 145 finished with value: 0.6946393762183236 and parameters: {'max_depth': 4, 'learning_rate': 0.015270362151341485, 'n_estimators': 1215, 'subsample': 0.7187913406298376, 'colsample_bytree': 0.9221689309007798, 'min_child_weight': 1, 'gamma': 1.7410295049460485, 'reg_alpha': 0.0011429768729199093, 'reg_lambda': 7.281702950852882e-05, 'max_delta_step': 5}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  74%|███████▎  | 147/200 [02:29<02:00,  2.28s/it]

[I 2025-11-10 18:30:18,210] Trial 146 finished with value: 0.7026900584795321 and parameters: {'max_depth': 4, 'learning_rate': 0.011567793299452575, 'n_estimators': 865, 'subsample': 0.7148572336190014, 'colsample_bytree': 0.9826556213201494, 'min_child_weight': 1, 'gamma': 1.132318846219778, 'reg_alpha': 0.08118896576687494, 'reg_lambda': 3.031866465920516e-07, 'max_delta_step': 6}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  74%|███████▍  | 148/200 [02:30<01:45,  2.03s/it]

[I 2025-11-10 18:30:19,661] Trial 147 finished with value: 0.6924171539961014 and parameters: {'max_depth': 4, 'learning_rate': 0.01162755490417799, 'n_estimators': 801, 'subsample': 0.717490744288981, 'colsample_bytree': 0.984767574960144, 'min_child_weight': 1, 'gamma': 1.8020921546415565, 'reg_alpha': 0.006219409251689667, 'reg_lambda': 1.450649180352302e-07, 'max_delta_step': 6}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  74%|███████▍  | 149/200 [02:34<02:08,  2.52s/it]

[I 2025-11-10 18:30:23,321] Trial 149 finished with value: 0.6883430799220273 and parameters: {'max_depth': 4, 'learning_rate': 0.014448117940053488, 'n_estimators': 1017, 'subsample': 0.7178296934604045, 'colsample_bytree': 0.9852769103667162, 'min_child_weight': 1, 'gamma': 1.6022155193045382, 'reg_alpha': 0.0014421863619050101, 'reg_lambda': 1.229579599429076e-07, 'max_delta_step': 5}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  75%|███████▌  | 150/200 [02:34<01:33,  1.88s/it]

[I 2025-11-10 18:30:23,692] Trial 148 finished with value: 0.6898440545808967 and parameters: {'max_depth': 4, 'learning_rate': 0.011520351779140242, 'n_estimators': 1008, 'subsample': 0.7192954218037475, 'colsample_bytree': 0.9833645386742443, 'min_child_weight': 1, 'gamma': 1.2078242755929396, 'reg_alpha': 0.005012248737748612, 'reg_lambda': 3.35972516642001e-08, 'max_delta_step': 6}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  76%|███████▌  | 151/200 [02:36<01:31,  1.88s/it]

[I 2025-11-10 18:30:25,569] Trial 150 finished with value: 0.6820662768031188 and parameters: {'max_depth': 4, 'learning_rate': 0.014339353120939957, 'n_estimators': 868, 'subsample': 0.7209417412303032, 'colsample_bytree': 0.9840360537811541, 'min_child_weight': 1, 'gamma': 1.2197388334726331, 'reg_alpha': 0.0012733505029852944, 'reg_lambda': 9.692699614634625e-05, 'max_delta_step': 5}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  76%|███████▌  | 152/200 [02:37<01:21,  1.69s/it]

[I 2025-11-10 18:30:26,832] Trial 151 finished with value: 0.6689863547758285 and parameters: {'max_depth': 4, 'learning_rate': 0.014592648867175612, 'n_estimators': 862, 'subsample': 0.6795634354458899, 'colsample_bytree': 0.9617771189861833, 'min_child_weight': 1, 'gamma': 1.150715933698099, 'reg_alpha': 0.0011291353938491001, 'reg_lambda': 9.641678981694526e-05, 'max_delta_step': 5}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  76%|███████▋  | 153/200 [02:42<01:59,  2.53s/it]

[I 2025-11-10 18:30:31,325] Trial 152 finished with value: 0.705906432748538 and parameters: {'max_depth': 4, 'learning_rate': 0.014000883061979661, 'n_estimators': 978, 'subsample': 0.738266588625556, 'colsample_bytree': 0.9597254072498399, 'min_child_weight': 1, 'gamma': 1.2193390812765956, 'reg_alpha': 4.9086303637550545e-05, 'reg_lambda': 2.952565482347219e-07, 'max_delta_step': 5}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  77%|███████▋  | 154/200 [02:42<01:28,  1.93s/it]

[I 2025-11-10 18:30:31,833] Trial 153 finished with value: 0.6857699805068226 and parameters: {'max_depth': 4, 'learning_rate': 0.014135319990688792, 'n_estimators': 866, 'subsample': 0.736836290177601, 'colsample_bytree': 0.9586669191863835, 'min_child_weight': 1, 'gamma': 0.7244796139129602, 'reg_alpha': 0.10402843125629703, 'reg_lambda': 0.00012033565471199026, 'max_delta_step': 5}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  78%|███████▊  | 155/200 [02:43<01:12,  1.62s/it]

[I 2025-11-10 18:30:32,744] Trial 154 finished with value: 0.6990838206627681 and parameters: {'max_depth': 4, 'learning_rate': 0.01150117873863624, 'n_estimators': 793, 'subsample': 0.7015155527575296, 'colsample_bytree': 0.9620240549163164, 'min_child_weight': 1, 'gamma': 1.6919674109869745, 'reg_alpha': 0.003050533659158103, 'reg_lambda': 2.925091640968112e-07, 'max_delta_step': 6}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  78%|███████▊  | 156/200 [02:44<01:06,  1.51s/it]

[I 2025-11-10 18:30:33,998] Trial 155 finished with value: 0.7057504873294347 and parameters: {'max_depth': 4, 'learning_rate': 0.011484821843242206, 'n_estimators': 780, 'subsample': 0.7412434306317278, 'colsample_bytree': 0.9741260638574902, 'min_child_weight': 1, 'gamma': 1.7458267858484722, 'reg_alpha': 0.014618459769157115, 'reg_lambda': 3.429599292432281e-07, 'max_delta_step': 6}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  78%|███████▊  | 157/200 [02:50<02:00,  2.80s/it]

[I 2025-11-10 18:30:39,793] Trial 156 finished with value: 0.700701754385965 and parameters: {'max_depth': 4, 'learning_rate': 0.012764392154009199, 'n_estimators': 970, 'subsample': 0.7325835639325754, 'colsample_bytree': 0.9622722062994938, 'min_child_weight': 1, 'gamma': 0.9969079088249828, 'reg_alpha': 0.1135787891682616, 'reg_lambda': 3.393169321761544e-07, 'max_delta_step': 5}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  79%|███████▉  | 158/200 [02:50<01:25,  2.04s/it]

[I 2025-11-10 18:30:40,084] Trial 157 finished with value: 0.7005847953216374 and parameters: {'max_depth': 4, 'learning_rate': 0.012196785087068994, 'n_estimators': 910, 'subsample': 0.7949809929390242, 'colsample_bytree': 0.9731411458783098, 'min_child_weight': 1, 'gamma': 0.9670283481317122, 'reg_alpha': 3.19096207401787e-05, 'reg_lambda': 2.9408199630928856e-07, 'max_delta_step': 5}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  80%|████████  | 160/200 [02:51<00:49,  1.23s/it]

[I 2025-11-10 18:30:41,002] Trial 158 finished with value: 0.6813255360623781 and parameters: {'max_depth': 4, 'learning_rate': 0.012555858244457072, 'n_estimators': 927, 'subsample': 0.7031586623702328, 'colsample_bytree': 0.9751112721417163, 'min_child_weight': 1, 'gamma': 1.0494267104884483, 'reg_alpha': 0.003129427345020756, 'reg_lambda': 2.084591936278694e-07, 'max_delta_step': 5}. Best is trial 126 with value: 0.7071345029239765.
[I 2025-11-10 18:30:41,132] Trial 160 pruned.

Best trial: 126. Best value: 0.707135:  80%|████████  | 161/200 [02:52<00:39,  1.00s/it]

[I 2025-11-10 18:30:41,597] Trial 159 finished with value: 0.7011890838206627 and parameters: {'max_depth': 4, 'learning_rate': 0.012698182339203529, 'n_estimators': 915, 'subsample': 0.7053372362746434, 'colsample_bytree': 0.9754094100605543, 'min_child_weight': 1, 'gamma': 1.751927009295019, 'reg_alpha': 0.000794201557563134, 'reg_lambda': 2.834176771901615e-07, 'max_delta_step': 6}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  81%|████████  | 162/200 [02:53<00:36,  1.03it/s]

[I 2025-11-10 18:30:42,501] Trial 162 pruned.

Best trial: 126. Best value: 0.707135:  82%|████████▏ | 163/200 [02:59<01:30,  2.45s/it]

[I 2025-11-10 18:30:48,386] Trial 161 finished with value: 0.6898440545808967 and parameters: {'max_depth': 4, 'learning_rate': 0.012702965660436112, 'n_estimators': 913, 'subsample': 0.704604744269859, 'colsample_bytree': 0.9791774797378153, 'min_child_weight': 1, 'gamma': 1.06099345785794, 'reg_alpha': 2.3164419118988644e-05, 'reg_lambda': 2.1555494539605253e-07, 'max_delta_step': 6}. Best is trial 126 with value: 0.7071345029239765.

Best trial: 126. Best value: 0.707135:  82%|████████▏ | 164/200 [03:00<01:19,  2.22s/it]

[I 2025-11-10 18:30:50,063] Trial 166 pruned.

Best trial: 164. Best value: 0.710702:  82%|████████▎ | 165/200 [03:01<00:57,  1.63s/it]

[I 2025-11-10 18:30:50,321] Trial 164 finished with value: 0.710701754385965 and parameters: {'max_depth': 4, 'learning_rate': 0.01201296752578619, 'n_estimators': 905, 'subsample': 0.7957975255753605, 'colsample_bytree': 0.9999097057105963, 'min_child_weight': 1, 'gamma': 0.8479542510104583, 'reg_alpha': 1.3473386773658244e-05, 'reg_lambda': 7.759987404936843e-08, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  83%|████████▎ | 166/200 [03:01<00:42,  1.26s/it]

[I 2025-11-10 18:30:50,719] Trial 163 finished with value: 0.7066471734892786 and parameters: {'max_depth': 4, 'learning_rate': 0.012233121381918243, 'n_estimators': 976, 'subsample': 0.7948920758690619, 'colsample_bytree': 0.9997863054459091, 'min_child_weight': 1, 'gamma': 0.9085162784299314, 'reg_alpha': 0.23405807766748313, 'reg_lambda': 7.443762406044804e-08, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  84%|████████▎ | 167/200 [03:01<00:32,  1.02it/s]

[I 2025-11-10 18:30:51,060] Trial 165 finished with value: 0.6814424951267056 and parameters: {'max_depth': 4, 'learning_rate': 0.012028748984149166, 'n_estimators': 971, 'subsample': 0.700074598602555, 'colsample_bytree': 0.96536947920774, 'min_child_weight': 1, 'gamma': 1.280567709487184, 'reg_alpha': 3.8199350225965665e-05, 'reg_lambda': 3.135866909332631e-07, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  84%|████████▍ | 168/200 [03:03<00:40,  1.26s/it]

[I 2025-11-10 18:30:52,962] Trial 167 pruned.

Best trial: 164. Best value: 0.710702:  84%|████████▍ | 169/200 [03:04<00:37,  1.21s/it]

[I 2025-11-10 18:30:54,056] Trial 168 pruned.

Best trial: 164. Best value: 0.710702:  85%|████████▌ | 170/200 [03:05<00:32,  1.08s/it]

[I 2025-11-10 18:30:54,820] Trial 171 pruned.

Best trial: 164. Best value: 0.710702:  86%|████████▌ | 171/200 [03:07<00:37,  1.28s/it]

[I 2025-11-10 18:30:56,587] Trial 173 pruned.

Best trial: 164. Best value: 0.710702:  86%|████████▌ | 172/200 [03:09<00:41,  1.50s/it]

[I 2025-11-10 18:30:58,586] Trial 170 finished with value: 0.6892202729044834 and parameters: {'max_depth': 4, 'learning_rate': 0.013531171763281918, 'n_estimators': 721, 'subsample': 0.790535633839178, 'colsample_bytree': 0.9998013932964831, 'min_child_weight': 1, 'gamma': 0.8636217210778374, 'reg_alpha': 5.847083687817023e-05, 'reg_lambda': 2.247084961104586e-08, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  86%|████████▋ | 173/200 [03:10<00:35,  1.32s/it]

[I 2025-11-10 18:30:59,483] Trial 169 finished with value: 0.6856335282651072 and parameters: {'max_depth': 4, 'learning_rate': 0.013625439123576989, 'n_estimators': 953, 'subsample': 0.8069404928032158, 'colsample_bytree': 0.9988833179102842, 'min_child_weight': 1, 'gamma': 0.8414964992715013, 'reg_alpha': 8.837429794884663e-05, 'reg_lambda': 8.793974990483693e-08, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  87%|████████▋ | 174/200 [03:11<00:31,  1.21s/it]

[I 2025-11-10 18:31:00,441] Trial 175 pruned.

Best trial: 164. Best value: 0.710702:  88%|████████▊ | 175/200 [03:14<00:48,  1.94s/it]

[I 2025-11-10 18:31:04,071] Trial 172 finished with value: 0.7010721247563352 and parameters: {'max_depth': 4, 'learning_rate': 0.013671861090200741, 'n_estimators': 988, 'subsample': 0.803345330043572, 'colsample_bytree': 0.9993004003551756, 'min_child_weight': 1, 'gamma': 0.6384244953759479, 'reg_alpha': 0.3462716049046045, 'reg_lambda': 2.619815277416865e-08, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  88%|████████▊ | 176/200 [03:16<00:42,  1.77s/it]

[I 2025-11-10 18:31:05,442] Trial 174 finished with value: 0.6899610136452241 and parameters: {'max_depth': 4, 'learning_rate': 0.012267548896097989, 'n_estimators': 811, 'subsample': 0.7911733561664236, 'colsample_bytree': 0.9864307672275643, 'min_child_weight': 1, 'gamma': 0.8427182292174327, 'reg_alpha': 0.22023313904363326, 'reg_lambda': 4.0578761307194847e-07, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  88%|████████▊ | 177/200 [03:18<00:44,  1.95s/it]

[I 2025-11-10 18:31:07,839] Trial 176 finished with value: 0.7013255360623782 and parameters: {'max_depth': 4, 'learning_rate': 0.012497073582542878, 'n_estimators': 888, 'subsample': 0.796674084204023, 'colsample_bytree': 0.9865939552012724, 'min_child_weight': 1, 'gamma': 0.9450088707241033, 'reg_alpha': 1.0350134391128105e-05, 'reg_lambda': 4.985755542597664e-07, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  89%|████████▉ | 178/200 [03:20<00:42,  1.91s/it]

[I 2025-11-10 18:31:09,659] Trial 177 finished with value: 0.7029239766081871 and parameters: {'max_depth': 4, 'learning_rate': 0.010043428509078842, 'n_estimators': 816, 'subsample': 0.7922900834191928, 'colsample_bytree': 0.9783295973862489, 'min_child_weight': 1, 'gamma': 0.9859701984707893, 'reg_alpha': 0.24487157877382953, 'reg_lambda': 2.879462181242765e-07, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  90%|████████▉ | 179/200 [03:21<00:33,  1.60s/it]

[I 2025-11-10 18:31:10,520] Trial 180 pruned.

Best trial: 164. Best value: 0.710702:  90%|█████████ | 180/200 [03:23<00:33,  1.66s/it]

[I 2025-11-10 18:31:12,333] Trial 182 pruned.
[I 2025-11-10 18:31:12,352] Trial 178 finished with value: 0.6946393762183236 and parameters: {'max_depth': 4, 'learning_rate': 0.01265519220133939, 'n_estimators': 804, 'subsample': 0.7895075065967414, 'colsample_bytree': 0.9718187688219694, 'min_child_weight': 1, 'gamma': 0.9957457233991269, 'reg_alpha': 0.2822193888698831, 'reg_lambda': 5.17893978092621e-08, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  91%|█████████ | 182/200 [03:25<00:23,  1.32s/it]

[I 2025-11-10 18:31:14,184] Trial 183 pruned.

Best trial: 164. Best value: 0.710702:  92%|█████████▏| 183/200 [03:25<00:19,  1.17s/it]

[I 2025-11-10 18:31:14,891] Trial 179 finished with value: 0.6897076023391813 and parameters: {'max_depth': 4, 'learning_rate': 0.012557335942259029, 'n_estimators': 896, 'subsample': 0.8225478749826931, 'colsample_bytree': 0.9721747114288242, 'min_child_weight': 1, 'gamma': 0.7212701759161821, 'reg_alpha': 0.3661423194625007, 'reg_lambda': 5.5140891553237735e-08, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  92%|█████████▏| 184/200 [03:27<00:19,  1.24s/it]

[I 2025-11-10 18:31:16,323] Trial 184 pruned.

Best trial: 164. Best value: 0.710702:  92%|█████████▎| 185/200 [03:28<00:19,  1.32s/it]

[I 2025-11-10 18:31:17,846] Trial 181 finished with value: 0.6984795321637426 and parameters: {'max_depth': 4, 'learning_rate': 0.011474572932411307, 'n_estimators': 759, 'subsample': 0.8273501724229941, 'colsample_bytree': 0.9748444230902299, 'min_child_weight': 1, 'gamma': 0.9368159248766582, 'reg_alpha': 9.632244660377792e-06, 'reg_lambda': 1.5927231902102816e-08, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  93%|█████████▎| 186/200 [03:29<00:15,  1.11s/it]

[I 2025-11-10 18:31:18,428] Trial 187 pruned.

Best trial: 164. Best value: 0.710702:  94%|█████████▎| 187/200 [03:34<00:28,  2.16s/it]

[I 2025-11-10 18:31:23,225] Trial 185 finished with value: 0.6892202729044834 and parameters: {'max_depth': 4, 'learning_rate': 0.01138693157819782, 'n_estimators': 893, 'subsample': 0.7786784182815648, 'colsample_bytree': 0.9910333663278355, 'min_child_weight': 1, 'gamma': 0.6776694246799156, 'reg_alpha': 1.3357507314224607e-05, 'reg_lambda': 1.4137835388389097e-07, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  94%|█████████▍| 188/200 [03:35<00:23,  1.93s/it]

[I 2025-11-10 18:31:24,583] Trial 190 pruned.

Best trial: 164. Best value: 0.710702:  94%|█████████▍| 189/200 [03:35<00:16,  1.51s/it]

[I 2025-11-10 18:31:25,082] Trial 186 finished with value: 0.690448343079922 and parameters: {'max_depth': 4, 'learning_rate': 0.01132764319574776, 'n_estimators': 835, 'subsample': 0.7828775868473606, 'colsample_bytree': 0.9868885120485066, 'min_child_weight': 1, 'gamma': 0.592162570299195, 'reg_alpha': 0.73540207523822, 'reg_lambda': 1.4462854669445792e-07, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  95%|█████████▌| 190/200 [03:37<00:14,  1.44s/it]

[I 2025-11-10 18:31:26,366] Trial 191 pruned.

Best trial: 164. Best value: 0.710702:  96%|█████████▌| 191/200 [03:37<00:10,  1.14s/it]

[I 2025-11-10 18:31:26,777] Trial 189 finished with value: 0.6985964912280702 and parameters: {'max_depth': 7, 'learning_rate': 0.011647554252588331, 'n_estimators': 838, 'subsample': 0.8478829054963377, 'colsample_bytree': 0.9528963750537117, 'min_child_weight': 1, 'gamma': 0.9701937967129894, 'reg_alpha': 1.5597392458720453e-05, 'reg_lambda': 2.915586278219123e-08, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  96%|█████████▌| 192/200 [03:38<00:07,  1.06it/s]

[I 2025-11-10 18:31:27,259] Trial 188 finished with value: 0.6813060428849903 and parameters: {'max_depth': 7, 'learning_rate': 0.011540707236328246, 'n_estimators': 829, 'subsample': 0.8067685176611092, 'colsample_bytree': 0.9896675468996389, 'min_child_weight': 1, 'gamma': 0.5066036475336828, 'reg_alpha': 1.43467337697507e-05, 'reg_lambda': 2.6375065120062156e-08, 'max_delta_step': 7}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  96%|█████████▋| 193/200 [03:40<00:10,  1.48s/it]

[I 2025-11-10 18:31:29,994] Trial 194 pruned.

Best trial: 164. Best value: 0.710702:  97%|█████████▋| 194/200 [03:42<00:09,  1.61s/it]

[I 2025-11-10 18:31:31,932] Trial 192 finished with value: 0.6897076023391813 and parameters: {'max_depth': 4, 'learning_rate': 0.01234194723664971, 'n_estimators': 788, 'subsample': 0.8111111406549435, 'colsample_bytree': 0.6924405850262458, 'min_child_weight': 1, 'gamma': 0.9166109093103612, 'reg_alpha': 1.2034100527668321e-05, 'reg_lambda': 2.477033977073288e-08, 'max_delta_step': 7}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  98%|█████████▊| 195/200 [03:45<00:10,  2.02s/it]

[I 2025-11-10 18:31:34,886] Trial 193 finished with value: 0.687738791423002 and parameters: {'max_depth': 4, 'learning_rate': 0.012789068828531697, 'n_estimators': 946, 'subsample': 0.7679118555173968, 'colsample_bytree': 0.9757616260769948, 'min_child_weight': 1, 'gamma': 0.9474923706082554, 'reg_alpha': 9.39002374689757e-06, 'reg_lambda': 7.013759044592078e-07, 'max_delta_step': 7}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  98%|█████████▊| 196/200 [03:46<00:06,  1.59s/it]

[I 2025-11-10 18:31:35,492] Trial 195 finished with value: 0.6919298245614035 and parameters: {'max_depth': 8, 'learning_rate': 0.013089126284930875, 'n_estimators': 800, 'subsample': 0.8618784193980732, 'colsample_bytree': 0.9663990184447121, 'min_child_weight': 1, 'gamma': 0.9773858563972305, 'reg_alpha': 0.145335140221974, 'reg_lambda': 1.708237015013742e-08, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  98%|█████████▊| 197/200 [03:49<00:06,  2.12s/it]

[I 2025-11-10 18:31:38,853] Trial 196 finished with value: 0.6898245614035087 and parameters: {'max_depth': 4, 'learning_rate': 0.010684292375340639, 'n_estimators': 881, 'subsample': 0.8559443962255114, 'colsample_bytree': 0.9648929185528593, 'min_child_weight': 1, 'gamma': 1.2092113168908871, 'reg_alpha': 0.18427421475710412, 'reg_lambda': 1.4788182542634781e-08, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702:  99%|█████████▉| 198/200 [03:51<00:03,  1.91s/it]

[I 2025-11-10 18:31:40,260] Trial 197 finished with value: 0.6947758284600389 and parameters: {'max_depth': 7, 'learning_rate': 0.01072970602397916, 'n_estimators': 873, 'subsample': 0.7673407858906364, 'colsample_bytree': 0.9647626912723671, 'min_child_weight': 1, 'gamma': 1.2073842985756629, 'reg_alpha': 9.166895136678849e-06, 'reg_lambda': 2.79993990452136e-07, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702: 100%|█████████▉| 199/200 [03:53<00:01,  1.94s/it]

[I 2025-11-10 18:31:42,258] Trial 198 finished with value: 0.6942690058479531 and parameters: {'max_depth': 4, 'learning_rate': 0.010400984725898926, 'n_estimators': 746, 'subsample': 0.7962387726150953, 'colsample_bytree': 0.955906882338927, 'min_child_weight': 1, 'gamma': 1.2098631372032986, 'reg_alpha': 2.7300467162792736e-05, 'reg_lambda': 1.3002566080992372e-08, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

Best trial: 164. Best value: 0.710702: 100%|██████████| 200/200 [03:53<00:00,  1.17s/it]

[I 2025-11-10 18:31:42,957] Trial 199 finished with value: 0.7092202729044834 and parameters: {'max_depth': 7, 'learning_rate': 0.010698532893112038, 'n_estimators': 744, 'subsample': 0.7954509844150388, 'colsample_bytree': 0.9999521751393834, 'min_child_weight': 1, 'gamma': 1.185080964054804, 'reg_alpha': 4.8742206413575306e-06, 'reg_lambda': 2.533000027503891e-07, 'max_delta_step': 6}. Best is trial 164 with value: 0.710701754385965.

[I 2025-11-10 18:31:44,447] A new study created in memory with name: 19_1_roc_auc
Best trial: 1. Best value: 0.5:   1%|          | 2/200 [00:01<02:05,  1.58it/s]

[I 2025-11-10 18:31:45,737] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.01411048802663746, 'n_estimators': 329, 'subsample': 0.649300398632042, 'colsample_bytree': 0.5348076512746139, 'min_child_weight': 10, 'gamma': 0.33196057971255355, 'reg_alpha': 2.407697729271969e-06, 'reg_lambda': 1.159767621534627, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:31:45,906] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.07651106393738319, 'n_estimators': 332, 'subsample': 0.9253597492343233, 'colsample_bytree': 0.9187084957858562, 'min_child_weight': 7, 'gamma': 0.6271370162661305, 'reg_alpha': 0.0012235856291451525, 'reg_lambda': 1.2000133031104907, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 3. Best value: 0.564575:   2%|▏         | 3/200 [00:02<02:31,  1.30it/s]

[I 2025-11-10 18:31:46,843] Trial 3 finished with value: 0.5645751633986928 and parameters: {'max_depth': 4, 'learning_rate': 0.03323788683386639, 'n_estimators': 303, 'subsample': 0.6527817595528191, 'colsample_bytree': 0.7907910224078663, 'min_child_weight': 1, 'gamma': 2.9026359678469644, 'reg_alpha': 0.0015315646813514245, 'reg_lambda': 1.2616686303048408e-07, 'max_delta_step': 9}. Best is trial 3 with value: 0.5645751633986928.

Best trial: 3. Best value: 0.564575:   2%|▏         | 4/200 [00:03<03:10,  1.03it/s]

[I 2025-11-10 18:31:48,123] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.052505332420196504, 'n_estimators': 315, 'subsample': 0.7074501161140504, 'colsample_bytree': 0.6054740197089783, 'min_child_weight': 9, 'gamma': 4.3242975365941865, 'reg_alpha': 0.0002968772359171437, 'reg_lambda': 0.08660230958183929, 'max_delta_step': 5}. Best is trial 3 with value: 0.5645751633986928.

Best trial: 3. Best value: 0.564575:   2%|▎         | 5/200 [00:04<02:39,  1.22it/s]

[I 2025-11-10 18:31:48,664] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.0489764741781818, 'n_estimators': 674, 'subsample': 0.5945964478927286, 'colsample_bytree': 0.7978815742428097, 'min_child_weight': 10, 'gamma': 4.277817898717705, 'reg_alpha': 0.0464133294031506, 'reg_lambda': 0.07728129292817329, 'max_delta_step': 1}. Best is trial 3 with value: 0.5645751633986928.
[I 2025-11-10 18:31:48,756] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.08446182927118559, 'n_estimators': 1141, 'subsample': 0.7340867937936211, 'colsample_bytree': 0.582941626461875, 'min_child_weight': 7, 'gamma': 4.053986176879722, 'reg_alpha': 2.137522329732835e-06, 'reg_lambda': 1.1821695394769982, 'max_delta_step': 7}. Best is trial 3 with value: 0.5645751633986928.

Best trial: 7. Best value: 0.599477:   4%|▎         | 7/200 [00:06<03:02,  1.06it/s]

[I 2025-11-10 18:31:50,804] Trial 7 finished with value: 0.5994771241830066 and parameters: {'max_depth': 10, 'learning_rate': 0.015493340769304252, 'n_estimators': 584, 'subsample': 0.8142886625532617, 'colsample_bytree': 0.7362147523641124, 'min_child_weight': 4, 'gamma': 3.7604187017617092, 'reg_alpha': 0.0022318089008949056, 'reg_lambda': 1.98421399395116e-07, 'max_delta_step': 1}. Best is trial 7 with value: 0.5994771241830066.

Best trial: 4. Best value: 0.622876:   4%|▍         | 9/200 [00:07<02:12,  1.44it/s]

[I 2025-11-10 18:31:51,650] Trial 4 finished with value: 0.6228758169934641 and parameters: {'max_depth': 7, 'learning_rate': 0.05042087751449352, 'n_estimators': 1470, 'subsample': 0.7084984402999946, 'colsample_bytree': 0.5633845448830157, 'min_child_weight': 4, 'gamma': 0.006804897336207816, 'reg_alpha': 6.2581782314524596e-06, 'reg_lambda': 0.004011431576827637, 'max_delta_step': 3}. Best is trial 4 with value: 0.6228758169934641.
[I 2025-11-10 18:31:51,751] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.014881454348601967, 'n_estimators': 726, 'subsample': 0.5670588634812175, 'colsample_bytree': 0.650906733655799, 'min_child_weight': 7, 'gamma': 0.21945750695385347, 'reg_alpha': 7.022662738961407e-08, 'reg_lambda': 0.006738719433667323, 'max_delta_step': 0}. Best is trial 4 with value: 0.6228758169934641.

Best trial: 4. Best value: 0.622876:   5%|▌         | 10/200 [00:08<02:27,  1.29it/s]

[I 2025-11-10 18:31:52,736] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.1748519463706, 'n_estimators': 986, 'subsample': 0.6144960511546556, 'colsample_bytree': 0.616262113901551, 'min_child_weight': 5, 'gamma': 2.245994834388246, 'reg_alpha': 9.456307124350515e-07, 'reg_lambda': 0.7720016028843852, 'max_delta_step': 4}. Best is trial 4 with value: 0.6228758169934641.

Best trial: 4. Best value: 0.622876:   6%|▌         | 11/200 [00:10<03:24,  1.08s/it]

[I 2025-11-10 18:31:54,579] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.015099923510447099, 'n_estimators': 710, 'subsample': 0.5894058592295602, 'colsample_bytree': 0.6278884008708759, 'min_child_weight': 9, 'gamma': 0.5481297005725461, 'reg_alpha': 1.736778815692084e-08, 'reg_lambda': 0.008522653851896761, 'max_delta_step': 10}. Best is trial 4 with value: 0.6228758169934641.

Best trial: 4. Best value: 0.622876:   6%|▌         | 12/200 [00:12<04:06,  1.31s/it]

[I 2025-11-10 18:31:56,455] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05830488178188992, 'n_estimators': 1431, 'subsample': 0.7116679934343078, 'colsample_bytree': 0.5926436241344373, 'min_child_weight': 7, 'gamma': 3.2949911725948935, 'reg_alpha': 0.5202726142288929, 'reg_lambda': 0.00017504205863292575, 'max_delta_step': 0}. Best is trial 4 with value: 0.6228758169934641.

Best trial: 4. Best value: 0.622876:   6%|▋         | 13/200 [00:12<03:41,  1.18s/it]

[I 2025-11-10 18:31:57,325] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.12491592363675587, 'n_estimators': 1381, 'subsample': 0.972828044704675, 'colsample_bytree': 0.856390211846535, 'min_child_weight': 6, 'gamma': 3.8483591032737174, 'reg_alpha': 3.3487395733757646e-05, 'reg_lambda': 2.8988046011007147, 'max_delta_step': 0}. Best is trial 4 with value: 0.6228758169934641.

Best trial: 4. Best value: 0.622876:   7%|▋         | 14/200 [00:15<04:40,  1.51s/it]

[I 2025-11-10 18:31:59,608] Trial 13 finished with value: 0.582875816993464 and parameters: {'max_depth': 7, 'learning_rate': 0.2624673524230931, 'n_estimators': 1496, 'subsample': 0.8472172706850297, 'colsample_bytree': 0.5045849758577845, 'min_child_weight': 2, 'gamma': 1.4738324221073973, 'reg_alpha': 3.3677337621547245, 'reg_lambda': 1.748976853441436e-05, 'max_delta_step': 3}. Best is trial 4 with value: 0.6228758169934641.

Best trial: 4. Best value: 0.622876:   8%|▊         | 15/200 [00:15<03:56,  1.28s/it]

[I 2025-11-10 18:32:00,337] Trial 16 finished with value: 0.5671895424836602 and parameters: {'max_depth': 8, 'learning_rate': 0.027887507860091348, 'n_estimators': 524, 'subsample': 0.8421514330873217, 'colsample_bytree': 0.7092248121968148, 'min_child_weight': 3, 'gamma': 1.6182630266294915, 'reg_alpha': 0.02085850695812459, 'reg_lambda': 6.015673102473401e-06, 'max_delta_step': 3}. Best is trial 4 with value: 0.6228758169934641.

Best trial: 4. Best value: 0.622876:   8%|▊         | 16/200 [00:17<04:09,  1.35s/it]

[I 2025-11-10 18:32:01,877] Trial 17 finished with value: 0.6094771241830065 and parameters: {'max_depth': 8, 'learning_rate': 0.023746600474032913, 'n_estimators': 525, 'subsample': 0.8224509623064141, 'colsample_bytree': 0.7144784935720241, 'min_child_weight': 4, 'gamma': 4.955910514475653, 'reg_alpha': 0.008159131116514472, 'reg_lambda': 5.624610093394965e-08, 'max_delta_step': 2}. Best is trial 4 with value: 0.6228758169934641.
[I 2025-11-10 18:32:01,963] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.027425534161276927, 'n_estimators': 1418, 'subsample': 0.8662019739831235, 'colsample_bytree': 0.998542094538422, 'min_child_weight': 3, 'gamma': 2.78056536636755, 'reg_alpha': 7.787386499572324, 'reg_lambda': 8.975165000629807e-06, 'max_delta_step': 3}. Best is trial 4 with value: 0.6228758169934641.

Best trial: 4. Best value: 0.622876:   9%|▉         | 18/200 [00:18<03:14,  1.07s/it]

[I 2025-11-10 18:32:03,336] Trial 15 finished with value: 0.5786928104575163 and parameters: {'max_depth': 8, 'learning_rate': 0.02656928179493155, 'n_estimators': 1435, 'subsample': 0.8481576077758801, 'colsample_bytree': 0.7156969859587178, 'min_child_weight': 3, 'gamma': 1.693865002858388, 'reg_alpha': 0.0001093678437328643, 'reg_lambda': 7.404679331958735e-06, 'max_delta_step': 3}. Best is trial 4 with value: 0.6228758169934641.

Best trial: 4. Best value: 0.622876:  10%|▉         | 19/200 [00:20<03:47,  1.26s/it]

[I 2025-11-10 18:32:05,163] Trial 18 finished with value: 0.6176470588235293 and parameters: {'max_depth': 9, 'learning_rate': 0.02675034989495563, 'n_estimators': 1125, 'subsample': 0.8257328532148758, 'colsample_bytree': 0.7028973593697936, 'min_child_weight': 4, 'gamma': 4.9922915600699795, 'reg_alpha': 4.661819018191836e-05, 'reg_lambda': 5.6325540948762296e-08, 'max_delta_step': 2}. Best is trial 4 with value: 0.6228758169934641.

Best trial: 4. Best value: 0.622876:  10%|█         | 20/200 [00:21<03:18,  1.10s/it]

[I 2025-11-10 18:32:05,838] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.021795483246325867, 'n_estimators': 956, 'subsample': 0.7694095890926442, 'colsample_bytree': 0.6856169702937829, 'min_child_weight': 5, 'gamma': 1.257866085347223, 'reg_alpha': 5.497955737691148e-05, 'reg_lambda': 0.00042736509208904643, 'max_delta_step': 7}. Best is trial 4 with value: 0.6228758169934641.

Best trial: 4. Best value: 0.622876:  10%|█         | 21/200 [00:22<03:23,  1.13s/it]

[I 2025-11-10 18:32:07,054] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.01058415019335715, 'n_estimators': 938, 'subsample': 0.776209387170403, 'colsample_bytree': 0.6730840258720672, 'min_child_weight': 5, 'gamma': 4.937428387903106, 'reg_alpha': 2.5427955033464125e-05, 'reg_lambda': 3.378411959795366e-08, 'max_delta_step': 7}. Best is trial 4 with value: 0.6228758169934641.
[I 2025-11-10 18:32:07,099] Trial 19 finished with value: 0.6138562091503268 and parameters: {'max_depth': 8, 'learning_rate': 0.027242390692340992, 'n_estimators': 1164, 'subsample': 0.7666531302426606, 'colsample_bytree': 0.9867281653049055, 'min_child_weight': 4, 'gamma': 4.951572361742014, 'reg_alpha': 5.124459539313895e-05, 'reg_lambda': 1.4020990358182184e-08, 'max_delta_step': 2}. Best is trial 4 with value: 0.6228758169934641.

Best trial: 4. Best value: 0.622876:  12%|█▏        | 23/200 [00:25<03:38,  1.23s/it]

[I 2025-11-10 18:32:09,770] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.010583052435948067, 'n_estimators': 1220, 'subsample': 0.5015052883901332, 'colsample_bytree': 0.6733485034253377, 'min_child_weight': 5, 'gamma': 0.8983232694667365, 'reg_alpha': 2.5606508190189496e-05, 'reg_lambda': 0.0006622513328749452, 'max_delta_step': 7}. Best is trial 4 with value: 0.6228758169934641.

Best trial: 25. Best value: 0.64085:  12%|█▏        | 24/200 [00:27<04:18,  1.47s/it]

[I 2025-11-10 18:32:11,992] Trial 25 finished with value: 0.6408496732026144 and parameters: {'max_depth': 9, 'learning_rate': 0.03987887202636611, 'n_estimators': 1219, 'subsample': 0.6743656474276855, 'colsample_bytree': 0.9925845927120844, 'min_child_weight': 4, 'gamma': 4.6272499482405465, 'reg_alpha': 7.912792428232604e-06, 'reg_lambda': 7.346849132625887e-07, 'max_delta_step': 2}. Best is trial 25 with value: 0.6408496732026144.
[I 2025-11-10 18:32:12,167] Trial 24 finished with value: 0.6086274509803922 and parameters: {'max_depth': 9, 'learning_rate': 0.03625571879156075, 'n_estimators': 1204, 'subsample': 0.9031246781045701, 'colsample_bytree': 0.7901430941886068, 'min_child_weight': 4, 'gamma': 4.959053462059721, 'reg_alpha': 0.013590198947449077, 'reg_lambda': 6.238483836118419e-07, 'max_delta_step': 2}. Best is trial 25 with value: 0.6408496732026144.

Best trial: 25. Best value: 0.64085:  13%|█▎        | 26/200 [00:29<03:46,  1.30s/it]

[I 2025-11-10 18:32:13,919] Trial 23 finished with value: 0.5793464052287582 and parameters: {'max_depth': 9, 'learning_rate': 0.010198855154961836, 'n_estimators': 1262, 'subsample': 0.7703971940649316, 'colsample_bytree': 0.5485478332855038, 'min_child_weight': 1, 'gamma': 2.2017771917043722, 'reg_alpha': 1.1984899095614651e-05, 'reg_lambda': 1.986228692912712e-08, 'max_delta_step': 7}. Best is trial 25 with value: 0.6408496732026144.

Best trial: 25. Best value: 0.64085:  14%|█▍        | 28/200 [00:30<02:38,  1.08it/s]

[I 2025-11-10 18:32:15,021] Trial 29 pruned.
[I 2025-11-10 18:32:15,125] Trial 26 finished with value: 0.6101960784313725 and parameters: {'max_depth': 9, 'learning_rate': 0.04042466898935163, 'n_estimators': 1218, 'subsample': 0.902148317582265, 'colsample_bytree': 0.9096266704329644, 'min_child_weight': 4, 'gamma': 4.574590715377877, 'reg_alpha': 6.127016457801733e-07, 'reg_lambda': 5.76010169413601e-07, 'max_delta_step': 2}. Best is trial 25 with value: 0.6408496732026144.

Best trial: 25. Best value: 0.64085:  14%|█▍        | 29/200 [00:34<04:50,  1.70s/it]

[I 2025-11-10 18:32:18,751] Trial 27 finished with value: 0.5467973856209151 and parameters: {'max_depth': 9, 'learning_rate': 0.03954359897488904, 'n_estimators': 1270, 'subsample': 0.6790260794704459, 'colsample_bytree': 0.8834001944543989, 'min_child_weight': 2, 'gamma': 4.4492379217702585, 'reg_alpha': 2.4808490401081776e-07, 'reg_lambda': 9.867038852533906e-07, 'max_delta_step': 2}. Best is trial 25 with value: 0.6408496732026144.
[I 2025-11-10 18:32:18,813] Trial 28 finished with value: 0.5648366013071895 and parameters: {'max_depth': 9, 'learning_rate': 0.04592124789182352, 'n_estimators': 1292, 'subsample': 0.6760352701412594, 'colsample_bytree': 0.8583410516303913, 'min_child_weight': 2, 'gamma': 3.4327717682645105, 'reg_alpha': 3.4663910187052695e-07, 'reg_lambda': 8.058773669012487e-07, 'max_delta_step': 4}. Best is trial 25 with value: 0.6408496732026144.

Best trial: 25. Best value: 0.64085:  16%|█▌        | 31/200 [00:34<02:56,  1.05s/it]

[I 2025-11-10 18:32:19,252] Trial 30 pruned.
[I 2025-11-10 18:32:19,254] Trial 31 pruned.

Best trial: 25. Best value: 0.64085:  16%|█▋        | 33/200 [00:36<02:54,  1.05s/it]

[I 2025-11-10 18:32:21,346] Trial 32 pruned.

Best trial: 25. Best value: 0.64085:  17%|█▋        | 34/200 [00:39<03:41,  1.33s/it]

[I 2025-11-10 18:32:23,708] Trial 33 finished with value: 0.6354248366013072 and parameters: {'max_depth': 6, 'learning_rate': 0.09067085406856007, 'n_estimators': 1056, 'subsample': 0.7974854815391234, 'colsample_bytree': 0.9675577070401096, 'min_child_weight': 3, 'gamma': 0.015078043037369806, 'reg_alpha': 5.473008514816156e-06, 'reg_lambda': 0.003567883053597476, 'max_delta_step': 1}. Best is trial 25 with value: 0.6408496732026144.

Best trial: 25. Best value: 0.64085:  18%|█▊        | 35/200 [00:40<03:27,  1.26s/it]

[I 2025-11-10 18:32:24,733] Trial 35 finished with value: 0.5813071895424836 and parameters: {'max_depth': 7, 'learning_rate': 0.019701559076560703, 'n_estimators': 1080, 'subsample': 0.7380583226779263, 'colsample_bytree': 0.9909167959802829, 'min_child_weight': 3, 'gamma': 4.68999343056795, 'reg_alpha': 0.00022959114562439562, 'reg_lambda': 1.3135459582884403e-08, 'max_delta_step': 1}. Best is trial 25 with value: 0.6408496732026144.

Best trial: 25. Best value: 0.64085:  18%|█▊        | 36/200 [00:41<03:28,  1.27s/it]

[I 2025-11-10 18:32:26,028] Trial 34 finished with value: 0.6163398692810457 and parameters: {'max_depth': 7, 'learning_rate': 0.018955252333212484, 'n_estimators': 1074, 'subsample': 0.7941826262668314, 'colsample_bytree': 0.9822876041312194, 'min_child_weight': 3, 'gamma': 0.006491039726805687, 'reg_alpha': 0.00021346855773369297, 'reg_lambda': 1.6430615847925855e-08, 'max_delta_step': 1}. Best is trial 25 with value: 0.6408496732026144.

Best trial: 25. Best value: 0.64085:  18%|█▊        | 37/200 [00:42<03:19,  1.23s/it]

[I 2025-11-10 18:32:27,131] Trial 36 finished with value: 0.547843137254902 and parameters: {'max_depth': 7, 'learning_rate': 0.01917052167055728, 'n_estimators': 1084, 'subsample': 0.796180662732322, 'colsample_bytree': 0.9990178659234953, 'min_child_weight': 3, 'gamma': 4.0526144040863805, 'reg_alpha': 0.00038797563265235177, 'reg_lambda': 1.0384278266499061e-08, 'max_delta_step': 1}. Best is trial 25 with value: 0.6408496732026144.

Best trial: 25. Best value: 0.64085:  19%|█▉        | 38/200 [00:43<02:42,  1.00s/it]

[I 2025-11-10 18:32:27,547] Trial 37 finished with value: 0.6250980392156863 and parameters: {'max_depth': 5, 'learning_rate': 0.09819464100856133, 'n_estimators': 834, 'subsample': 0.7966040589696647, 'colsample_bytree': 0.939497890376489, 'min_child_weight': 3, 'gamma': 0.44219545810799304, 'reg_alpha': 2.53238821866562e-06, 'reg_lambda': 0.002829275528443312, 'max_delta_step': 1}. Best is trial 25 with value: 0.6408496732026144.

Best trial: 25. Best value: 0.64085:  20%|█▉        | 39/200 [00:44<02:47,  1.04s/it]

[I 2025-11-10 18:32:28,678] Trial 38 finished with value: 0.6347712418300653 and parameters: {'max_depth': 5, 'learning_rate': 0.1059787414002984, 'n_estimators': 854, 'subsample': 0.7944662767503876, 'colsample_bytree': 0.951550991909888, 'min_child_weight': 3, 'gamma': 0.008136069509619759, 'reg_alpha': 1.922214756728642e-06, 'reg_lambda': 0.002463997784851698, 'max_delta_step': 1}. Best is trial 25 with value: 0.6408496732026144.

Best trial: 25. Best value: 0.64085:  20%|██        | 40/200 [00:44<02:25,  1.10it/s]

[I 2025-11-10 18:32:29,262] Trial 39 finished with value: 0.6328104575163398 and parameters: {'max_depth': 5, 'learning_rate': 0.12105985134996274, 'n_estimators': 849, 'subsample': 0.6505650455461726, 'colsample_bytree': 0.5531337785719744, 'min_child_weight': 4, 'gamma': 0.42849235285129944, 'reg_alpha': 2.4672163488027715e-06, 'reg_lambda': 0.002718925806045551, 'max_delta_step': 3}. Best is trial 25 with value: 0.6408496732026144.

Best trial: 25. Best value: 0.64085:  20%|██        | 41/200 [00:45<02:23,  1.11it/s]

[I 2025-11-10 18:32:30,152] Trial 43 pruned.

Best trial: 40. Best value: 0.659804:  21%|██        | 42/200 [00:46<02:05,  1.25it/s]

[I 2025-11-10 18:32:30,693] Trial 40 finished with value: 0.6598039215686275 and parameters: {'max_depth': 4, 'learning_rate': 0.08822878887570967, 'n_estimators': 868, 'subsample': 0.6356521287302448, 'colsample_bytree': 0.9472701149410735, 'min_child_weight': 4, 'gamma': 0.39583246315740006, 'reg_alpha': 2.288233735344284e-06, 'reg_lambda': 0.0025493165285747107, 'max_delta_step': 6}. Best is trial 40 with value: 0.6598039215686275.

Best trial: 40. Best value: 0.659804:  22%|██▏       | 43/200 [00:46<01:58,  1.33it/s]

[I 2025-11-10 18:32:31,343] Trial 45 pruned.

Best trial: 40. Best value: 0.659804:  22%|██▏       | 44/200 [00:47<01:51,  1.40it/s]

[I 2025-11-10 18:32:31,966] Trial 41 finished with value: 0.6010457516339869 and parameters: {'max_depth': 5, 'learning_rate': 0.10084830015968561, 'n_estimators': 844, 'subsample': 0.6318791810857671, 'colsample_bytree': 0.9433109421171599, 'min_child_weight': 1, 'gamma': 0.5416277696893261, 'reg_alpha': 2.216611160081336e-06, 'reg_lambda': 0.001905228997770623, 'max_delta_step': 6}. Best is trial 40 with value: 0.6598039215686275.

Best trial: 40. Best value: 0.659804:  22%|██▎       | 45/200 [00:47<01:29,  1.73it/s]

[I 2025-11-10 18:32:32,219] Trial 47 pruned.

Best trial: 40. Best value: 0.659804:  23%|██▎       | 46/200 [00:48<01:39,  1.55it/s]

[I 2025-11-10 18:32:33,021] Trial 48 pruned.

Best trial: 40. Best value: 0.659804:  24%|██▎       | 47/200 [00:49<01:38,  1.55it/s]

[I 2025-11-10 18:32:33,667] Trial 49 pruned.

Best trial: 40. Best value: 0.659804:  24%|██▍       | 48/200 [00:49<01:17,  1.95it/s]

[I 2025-11-10 18:32:33,869] Trial 42 finished with value: 0.6037908496732026 and parameters: {'max_depth': 5, 'learning_rate': 0.10876674475893335, 'n_estimators': 843, 'subsample': 0.8851783194529471, 'colsample_bytree': 0.9385228949946631, 'min_child_weight': 1, 'gamma': 0.4605799280739822, 'reg_alpha': 2.6883292077220756e-06, 'reg_lambda': 0.04195780110130818, 'max_delta_step': 0}. Best is trial 40 with value: 0.6598039215686275.

Best trial: 40. Best value: 0.659804:  24%|██▍       | 49/200 [00:50<01:23,  1.80it/s]

[I 2025-11-10 18:32:34,526] Trial 44 finished with value: 0.6215686274509804 and parameters: {'max_depth': 5, 'learning_rate': 0.09809972387919907, 'n_estimators': 867, 'subsample': 0.6356803677923709, 'colsample_bytree': 0.9550013319803415, 'min_child_weight': 2, 'gamma': 0.37131620289145595, 'reg_alpha': 1.490248363626426e-06, 'reg_lambda': 0.0015851059120017058, 'max_delta_step': 1}. Best is trial 40 with value: 0.6598039215686275.

Best trial: 46. Best value: 0.668954:  25%|██▌       | 50/200 [00:50<01:27,  1.72it/s]

[I 2025-11-10 18:32:35,163] Trial 46 finished with value: 0.6689542483660131 and parameters: {'max_depth': 4, 'learning_rate': 0.09195414259043248, 'n_estimators': 892, 'subsample': 0.6492574418481711, 'colsample_bytree': 0.9364450096281416, 'min_child_weight': 4, 'gamma': 0.7176966403894679, 'reg_alpha': 9.514969890272445e-07, 'reg_lambda': 0.025209325572903184, 'max_delta_step': 5}. Best is trial 46 with value: 0.6689542483660131.

Best trial: 46. Best value: 0.668954:  26%|██▌       | 51/200 [00:51<01:40,  1.49it/s]

[I 2025-11-10 18:32:36,051] Trial 53 pruned.

Best trial: 46. Best value: 0.668954:  26%|██▌       | 52/200 [00:52<01:32,  1.61it/s]

[I 2025-11-10 18:32:36,556] Trial 50 finished with value: 0.6505882352941176 and parameters: {'max_depth': 6, 'learning_rate': 0.1715651679700357, 'n_estimators': 639, 'subsample': 0.7186200698223921, 'colsample_bytree': 0.9364742338545718, 'min_child_weight': 4, 'gamma': 0.14655369059217346, 'reg_alpha': 3.384036440617397e-06, 'reg_lambda': 0.11276194371195311, 'max_delta_step': 0}. Best is trial 46 with value: 0.6689542483660131.
[I 2025-11-10 18:32:36,620] Trial 51 finished with value: 0.6541176470588235 and parameters: {'max_depth': 6, 'learning_rate': 0.19179779282764542, 'n_estimators': 631, 'subsample': 0.7062406252519428, 'colsample_bytree': 0.8845819523366725, 'min_child_weight': 4, 'gamma': 0.07159343048835182, 'reg_alpha': 2.994339074176843e-08, 'reg_lambda': 0.15298774876729562, 'max_delta_step': 3}. Best is trial 46 with value: 0.6689542483660131.

Best trial: 46. Best value: 0.668954:  27%|██▋       | 54/200 [00:52<00:55,  2.64it/s]

[I 2025-11-10 18:32:36,744] Trial 54 pruned.

Best trial: 46. Best value: 0.668954:  28%|██▊       | 56/200 [00:52<00:47,  3.04it/s]

[I 2025-11-10 18:32:37,175] Trial 56 pruned.
[I 2025-11-10 18:32:37,327] Trial 57 pruned.

Best trial: 46. Best value: 0.668954:  29%|██▉       | 58/200 [00:54<01:14,  1.90it/s]

[I 2025-11-10 18:32:38,928] Trial 52 finished with value: 0.6675163398692809 and parameters: {'max_depth': 4, 'learning_rate': 0.15623815299865398, 'n_estimators': 996, 'subsample': 0.7180672294472737, 'colsample_bytree': 0.8917092576870893, 'min_child_weight': 4, 'gamma': 0.15113797682957528, 'reg_alpha': 1.4558265469585422e-08, 'reg_lambda': 0.41509950321079364, 'max_delta_step': 3}. Best is trial 46 with value: 0.6689542483660131.
[I 2025-11-10 18:32:39,070] Trial 58 finished with value: 0.583921568627451 and parameters: {'max_depth': 6, 'learning_rate': 0.2070269337113634, 'n_estimators': 396, 'subsample': 0.7474255609391877, 'colsample_bytree': 0.9643498213181442, 'min_child_weight': 4, 'gamma': 2.090908655450259, 'reg_alpha': 1.6867728326678415e-08, 'reg_lambda': 2.2907418152483254, 'max_delta_step': 0}. Best is trial 46 with value: 0.6689542483660131.

Best trial: 46. Best value: 0.668954:  30%|███       | 61/200 [00:55<00:40,  3.40it/s]

[I 2025-11-10 18:32:39,481] Trial 61 pruned.
[I 2025-11-10 18:32:39,531] Trial 55 finished with value: 0.6079084967320261 and parameters: {'max_depth': 6, 'learning_rate': 0.15577651830476305, 'n_estimators': 639, 'subsample': 0.705323472292377, 'colsample_bytree': 0.9248941907078402, 'min_child_weight': 4, 'gamma': 0.0828499000085199, 'reg_alpha': 9.653368378401263e-06, 'reg_lambda': 0.18868634106912538, 'max_delta_step': 0}. Best is trial 46 with value: 0.6689542483660131.
[I 2025-11-10 18:32:39,579] Trial 59 finished with value: 0.5966013071895425 and parameters: {'max_depth': 3, 'learning_rate': 0.20478830259461747, 'n_estimators': 473, 'subsample': 0.749279959175792, 'colsample_bytree': 0.9301454434764894, 'min_child_weight': 4, 'gamma': 1.2870238046378644, 'reg_alpha': 1.643809983605237e-08, 'reg_lambda': 5.4840830066488575, 'max_delta_step': 0}. Best is trial 46 with value: 0.6689542483660131.

Best trial: 46. Best value: 0.668954:  31%|███       | 62/200 [00:55<00:54,  2.55it/s]

[I 2025-11-10 18:32:40,281] Trial 63 pruned.

Best trial: 46. Best value: 0.668954:  32%|███▏      | 63/200 [00:56<01:11,  1.93it/s]

[I 2025-11-10 18:32:41,165] Trial 60 finished with value: 0.5934640522875817 and parameters: {'max_depth': 3, 'learning_rate': 0.1971700375576891, 'n_estimators': 447, 'subsample': 0.7491524354040677, 'colsample_bytree': 0.9033245265509894, 'min_child_weight': 4, 'gamma': 1.250033155492994, 'reg_alpha': 1.3519515030465864e-07, 'reg_lambda': 7.998483192848383, 'max_delta_step': 6}. Best is trial 46 with value: 0.6689542483660131.

Best trial: 46. Best value: 0.668954:  32%|███▏      | 64/200 [00:57<01:37,  1.40it/s]

[I 2025-11-10 18:32:42,408] Trial 62 finished with value: 0.6473202614379086 and parameters: {'max_depth': 4, 'learning_rate': 0.22097761669384625, 'n_estimators': 658, 'subsample': 0.6604993118118455, 'colsample_bytree': 0.8920426093168907, 'min_child_weight': 4, 'gamma': 1.2552262888627834, 'reg_alpha': 1.3569708033813542e-07, 'reg_lambda': 6.171319258096992, 'max_delta_step': 3}. Best is trial 46 with value: 0.6689542483660131.

Best trial: 46. Best value: 0.668954:  33%|███▎      | 66/200 [00:58<01:07,  1.99it/s]

[I 2025-11-10 18:32:42,905] Trial 67 pruned.
[I 2025-11-10 18:32:43,027] Trial 64 finished with value: 0.6623529411764706 and parameters: {'max_depth': 4, 'learning_rate': 0.21877375207980376, 'n_estimators': 754, 'subsample': 0.6618881843487109, 'colsample_bytree': 0.8722372580547003, 'min_child_weight': 3, 'gamma': 0.2827900546812807, 'reg_alpha': 8.389395706527054e-07, 'reg_lambda': 0.019739581312263877, 'max_delta_step': 3}. Best is trial 46 with value: 0.6689542483660131.

Best trial: 46. Best value: 0.668954:  34%|███▍      | 68/200 [00:59<00:53,  2.45it/s]

[I 2025-11-10 18:32:43,590] Trial 68 pruned.
[I 2025-11-10 18:32:43,728] Trial 69 pruned.

Best trial: 46. Best value: 0.668954:  34%|███▍      | 69/200 [00:59<00:59,  2.20it/s]

[I 2025-11-10 18:32:44,296] Trial 70 pruned.
[I 2025-11-10 18:32:44,381] Trial 71 pruned.

Best trial: 46. Best value: 0.668954:  36%|███▌      | 71/200 [01:00<00:47,  2.69it/s]

[I 2025-11-10 18:32:44,840] Trial 66 pruned.

Best trial: 46. Best value: 0.668954:  36%|███▌      | 72/200 [01:01<00:55,  2.30it/s]

[I 2025-11-10 18:32:45,468] Trial 65 finished with value: 0.6460130718954249 and parameters: {'max_depth': 4, 'learning_rate': 0.054324260710447055, 'n_estimators': 1009, 'subsample': 0.6612258174791451, 'colsample_bytree': 0.9734146540560804, 'min_child_weight': 3, 'gamma': 0.24541362793691968, 'reg_alpha': 1.678587476096337e-07, 'reg_lambda': 0.014284345538682693, 'max_delta_step': 2}. Best is trial 46 with value: 0.6689542483660131.

Best trial: 72. Best value: 0.690719:  37%|███▋      | 74/200 [01:03<01:34,  1.33it/s]

[I 2025-11-10 18:32:48,038] Trial 72 finished with value: 0.6907189542483659 and parameters: {'max_depth': 3, 'learning_rate': 0.2922425586123587, 'n_estimators': 903, 'subsample': 0.612297450875573, 'colsample_bytree': 0.773581504641385, 'min_child_weight': 4, 'gamma': 0.22376148294702555, 'reg_alpha': 8.383847493858697e-07, 'reg_lambda': 1.3085922409969972, 'max_delta_step': 3}. Best is trial 72 with value: 0.6907189542483659.
[I 2025-11-10 18:32:48,140] Trial 74 finished with value: 0.6269281045751633 and parameters: {'max_depth': 3, 'learning_rate': 0.17590170792500115, 'n_estimators': 757, 'subsample': 0.7246565236467977, 'colsample_bytree': 0.9001144285469607, 'min_child_weight': 4, 'gamma': 1.0864490621875695, 'reg_alpha': 3.656285336831532e-08, 'reg_lambda': 0.007318006617790492, 'max_delta_step': 3}. Best is trial 72 with value: 0.6907189542483659.

Best trial: 72. Best value: 0.690719:  38%|███▊      | 75/200 [01:04<01:20,  1.54it/s]

[I 2025-11-10 18:32:48,525] Trial 73 finished with value: 0.6106535947712418 and parameters: {'max_depth': 3, 'learning_rate': 0.281318145111387, 'n_estimators': 992, 'subsample': 0.6908321637875842, 'colsample_bytree': 0.7865194540585084, 'min_child_weight': 4, 'gamma': 0.7988748144695643, 'reg_alpha': 3.6184683766401384e-08, 'reg_lambda': 0.0070663166855651485, 'max_delta_step': 3}. Best is trial 72 with value: 0.6907189542483659.

Best trial: 72. Best value: 0.690719:  38%|███▊      | 76/200 [01:04<01:25,  1.46it/s]

[I 2025-11-10 18:32:49,310] Trial 78 pruned.

Best trial: 72. Best value: 0.690719:  38%|███▊      | 77/200 [01:05<01:06,  1.84it/s]

[I 2025-11-10 18:32:49,502] Trial 75 finished with value: 0.6491503267973855 and parameters: {'max_depth': 3, 'learning_rate': 0.29535532261732184, 'n_estimators': 923, 'subsample': 0.6668371856825565, 'colsample_bytree': 0.9032489686271845, 'min_child_weight': 4, 'gamma': 1.1025608286392463, 'reg_alpha': 3.2388055468772186e-08, 'reg_lambda': 0.004859091775651468, 'max_delta_step': 3}. Best is trial 72 with value: 0.6907189542483659.

Best trial: 72. Best value: 0.690719:  39%|███▉      | 78/200 [01:05<01:10,  1.73it/s]

[I 2025-11-10 18:32:50,159] Trial 79 pruned.

Best trial: 72. Best value: 0.690719:  40%|███▉      | 79/200 [01:05<00:57,  2.11it/s]

[I 2025-11-10 18:32:50,388] Trial 80 pruned.

Best trial: 72. Best value: 0.690719:  40%|████      | 80/200 [01:06<00:57,  2.09it/s]

[I 2025-11-10 18:32:50,877] Trial 81 pruned.

Best trial: 72. Best value: 0.690719:  40%|████      | 81/200 [01:07<01:12,  1.65it/s]

[I 2025-11-10 18:32:51,782] Trial 83 pruned.

Best trial: 77. Best value: 0.698431:  41%|████      | 82/200 [01:07<01:02,  1.87it/s]

[I 2025-11-10 18:32:52,150] Trial 76 finished with value: 0.6497385620915033 and parameters: {'max_depth': 3, 'learning_rate': 0.2886848554749112, 'n_estimators': 926, 'subsample': 0.6174970771752808, 'colsample_bytree': 0.771606070281005, 'min_child_weight': 4, 'gamma': 0.5079761566216611, 'reg_alpha': 0.1213933739251929, 'reg_lambda': 1.171039453480892, 'max_delta_step': 3}. Best is trial 72 with value: 0.6907189542483659.
[I 2025-11-10 18:32:52,168] Trial 77 finished with value: 0.6984313725490197 and parameters: {'max_depth': 3, 'learning_rate': 0.2972290325712204, 'n_estimators': 922, 'subsample': 0.613590303864606, 'colsample_bytree': 0.7601091200193312, 'min_child_weight': 4, 'gamma': 0.7142143883580299, 'reg_alpha': 3.2177859959255313e-07, 'reg_lambda': 1.3070666828043196, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  42%|████▏     | 84/200 [01:08<00:49,  2.33it/s]

[I 2025-11-10 18:32:52,760] Trial 84 pruned.

Best trial: 77. Best value: 0.698431:  42%|████▎     | 85/200 [01:08<00:45,  2.50it/s]

[I 2025-11-10 18:32:53,071] Trial 85 pruned.
[I 2025-11-10 18:32:53,079] Trial 86 pruned.

Best trial: 77. Best value: 0.698431:  44%|████▎     | 87/200 [01:09<00:40,  2.81it/s]

[I 2025-11-10 18:32:53,659] Trial 87 pruned.

Best trial: 77. Best value: 0.698431:  44%|████▍     | 88/200 [01:09<00:37,  2.98it/s]

[I 2025-11-10 18:32:53,926] Trial 88 pruned.

Best trial: 77. Best value: 0.698431:  44%|████▍     | 89/200 [01:09<00:35,  3.12it/s]

[I 2025-11-10 18:32:54,198] Trial 89 pruned.

Best trial: 77. Best value: 0.698431:  46%|████▌     | 91/200 [01:10<00:34,  3.20it/s]

[I 2025-11-10 18:32:54,709] Trial 90 pruned.
[I 2025-11-10 18:32:54,870] Trial 91 pruned.

Best trial: 77. Best value: 0.698431:  46%|████▌     | 92/200 [01:10<00:29,  3.66it/s]

[I 2025-11-10 18:32:55,040] Trial 92 pruned.

Best trial: 77. Best value: 0.698431:  46%|████▋     | 93/200 [01:11<00:34,  3.13it/s]

[I 2025-11-10 18:32:55,475] Trial 82 finished with value: 0.6207843137254901 and parameters: {'max_depth': 3, 'learning_rate': 0.11731356628553855, 'n_estimators': 961, 'subsample': 0.955919379293197, 'colsample_bytree': 0.877943005310896, 'min_child_weight': 3, 'gamma': 0.10583730023232713, 'reg_alpha': 1.2829433633725098e-08, 'reg_lambda': 0.027823449721312277, 'max_delta_step': 8}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  47%|████▋     | 94/200 [01:14<02:06,  1.19s/it]

[I 2025-11-10 18:32:58,814] Trial 94 finished with value: 0.6677777777777777 and parameters: {'max_depth': 3, 'learning_rate': 0.2984300236853657, 'n_estimators': 919, 'subsample': 0.6670105441225975, 'colsample_bytree': 0.9290305844091531, 'min_child_weight': 4, 'gamma': 0.5388445219015806, 'reg_alpha': 2.6463954261536345e-08, 'reg_lambda': 0.03044236629540942, 'max_delta_step': 4}. Best is trial 77 with value: 0.6984313725490197.
[I 2025-11-10 18:32:58,911] Trial 95 finished with value: 0.6375816993464052 and parameters: {'max_depth': 3, 'learning_rate': 0.29470925905940537, 'n_estimators': 899, 'subsample': 0.6695168140449136, 'colsample_bytree': 0.9318590065519129, 'min_child_weight': 4, 'gamma': 0.49438844505019086, 'reg_alpha': 2.4429631041728316e-08, 'reg_lambda': 0.004789526860062649, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  48%|████▊     | 96/200 [01:14<01:15,  1.37it/s]

[I 2025-11-10 18:32:59,143] Trial 93 finished with value: 0.6224836601307189 and parameters: {'max_depth': 5, 'learning_rate': 0.15785187588512092, 'n_estimators': 1029, 'subsample': 0.6878837122484079, 'colsample_bytree': 0.7962271462832754, 'min_child_weight': 4, 'gamma': 0.6624169284583801, 'reg_alpha': 3.28457834054313e-07, 'reg_lambda': 0.03522092743497179, 'max_delta_step': 4}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  48%|████▊     | 97/200 [01:15<01:05,  1.58it/s]

[I 2025-11-10 18:32:59,480] Trial 98 pruned.
[I 2025-11-10 18:32:59,652] Trial 96 finished with value: 0.6575816993464052 and parameters: {'max_depth': 3, 'learning_rate': 0.06773146555411798, 'n_estimators': 926, 'subsample': 0.6667742440601313, 'colsample_bytree': 0.9345745956274929, 'min_child_weight': 4, 'gamma': 0.5543023456106888, 'reg_alpha': 2.4582704762682363e-08, 'reg_lambda': 0.08793589069123627, 'max_delta_step': 4}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  50%|████▉     | 99/200 [01:15<00:41,  2.43it/s]

[I 2025-11-10 18:32:59,790] Trial 99 pruned.

Best trial: 77. Best value: 0.698431:  50%|█████     | 100/200 [01:16<00:52,  1.91it/s]

[I 2025-11-10 18:33:00,604] Trial 102 pruned.

Best trial: 77. Best value: 0.698431:  50%|█████     | 101/200 [01:18<01:37,  1.01it/s]

[I 2025-11-10 18:33:02,760] Trial 97 finished with value: 0.6403921568627451 and parameters: {'max_depth': 3, 'learning_rate': 0.06638380718748058, 'n_estimators': 887, 'subsample': 0.6292913577306848, 'colsample_bytree': 0.6414706836826002, 'min_child_weight': 4, 'gamma': 0.49981397900868463, 'reg_alpha': 5.653702524131686e-08, 'reg_lambda': 1.0570640416334092, 'max_delta_step': 4}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  52%|█████▏    | 103/200 [01:18<01:01,  1.58it/s]

[I 2025-11-10 18:33:03,265] Trial 100 finished with value: 0.6161437908496732 and parameters: {'max_depth': 3, 'learning_rate': 0.06677850695299348, 'n_estimators': 875, 'subsample': 0.6266919349648147, 'colsample_bytree': 0.6334960162956612, 'min_child_weight': 4, 'gamma': 0.9245315671373284, 'reg_alpha': 1.2390300274325224e-06, 'reg_lambda': 0.9147774501452399, 'max_delta_step': 5}. Best is trial 77 with value: 0.6984313725490197.
[I 2025-11-10 18:33:03,381] Trial 104 pruned.
[I 2025-11-10 18:33:03,387] Trial 103 finished with value: 0.6355555555555557 and parameters: {'max_depth': 4, 'learning_rate': 0.07953152570721386, 'n_estimators': 635, 'subsample': 0.6983822811784027, 'colsample_bytree': 0.6429459468137818, 'min_child_weight': 4, 'gamma': 0.8938265644195835, 'reg_alpha': 1.2998778440721466e-06, 'reg_lambda': 0.1289554901771265, 'max_delta_step': 6}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  53%|█████▎    | 106/200 [01:19<00:35,  2.62it/s]

[I 2025-11-10 18:33:03,850] Trial 101 finished with value: 0.6323529411764706 and parameters: {'max_depth': 3, 'learning_rate': 0.06565896501388557, 'n_estimators': 871, 'subsample': 0.7132041346003045, 'colsample_bytree': 0.9832846016814363, 'min_child_weight': 4, 'gamma': 3.044737398554311, 'reg_alpha': 8.507712716218553e-07, 'reg_lambda': 0.0869468735056002, 'max_delta_step': 5}. Best is trial 77 with value: 0.6984313725490197.
[I 2025-11-10 18:33:04,015] Trial 105 pruned.

Best trial: 77. Best value: 0.698431:  54%|█████▎    | 107/200 [01:19<00:29,  3.10it/s]

[I 2025-11-10 18:33:04,168] Trial 106 pruned.
[I 2025-11-10 18:33:04,185] Trial 107 pruned.

Best trial: 77. Best value: 0.698431:  55%|█████▍    | 109/200 [01:20<00:27,  3.28it/s]

[I 2025-11-10 18:33:04,729] Trial 109 pruned.

Best trial: 77. Best value: 0.698431:  55%|█████▌    | 110/200 [01:20<00:32,  2.76it/s]

[I 2025-11-10 18:33:05,280] Trial 111 pruned.

Best trial: 77. Best value: 0.698431:  56%|█████▌    | 111/200 [01:21<00:40,  2.18it/s]

[I 2025-11-10 18:33:06,032] Trial 113 pruned.

Best trial: 77. Best value: 0.698431:  56%|█████▌    | 112/200 [01:24<01:28,  1.00s/it]

[I 2025-11-10 18:33:08,556] Trial 110 finished with value: 0.6320261437908496 and parameters: {'max_depth': 6, 'learning_rate': 0.060141605947989084, 'n_estimators': 754, 'subsample': 0.7393440151294361, 'colsample_bytree': 0.9380197119016545, 'min_child_weight': 3, 'gamma': 0.27574431055394155, 'reg_alpha': 1.0179206925510647e-07, 'reg_lambda': 1.9648890446354002, 'max_delta_step': 2}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  56%|█████▋    | 113/200 [01:24<01:09,  1.25it/s]

[I 2025-11-10 18:33:08,815] Trial 108 finished with value: 0.6281045751633988 and parameters: {'max_depth': 6, 'learning_rate': 0.08561421829908614, 'n_estimators': 927, 'subsample': 0.7392783385469771, 'colsample_bytree': 0.9134806728906393, 'min_child_weight': 3, 'gamma': 0.010310987270436119, 'reg_alpha': 1.9361076864437084e-08, 'reg_lambda': 1.8215913310605776, 'max_delta_step': 2}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  57%|█████▋    | 114/200 [01:24<00:58,  1.48it/s]

[I 2025-11-10 18:33:09,171] Trial 112 finished with value: 0.6312418300653595 and parameters: {'max_depth': 4, 'learning_rate': 0.060742473467640584, 'n_estimators': 930, 'subsample': 0.6684675313301545, 'colsample_bytree': 0.7718265150031531, 'min_child_weight': 3, 'gamma': 0.20353802819488975, 'reg_alpha': 4.594512384960163e-08, 'reg_lambda': 0.1903878276579657, 'max_delta_step': 4}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  58%|█████▊    | 116/200 [01:25<00:45,  1.83it/s]

[I 2025-11-10 18:33:09,957] Trial 114 finished with value: 0.6398039215686275 and parameters: {'max_depth': 3, 'learning_rate': 0.278894528904068, 'n_estimators': 930, 'subsample': 0.6701629379448111, 'colsample_bytree': 0.9115774798771005, 'min_child_weight': 4, 'gamma': 1.0602595420471206, 'reg_alpha': 4.796338943844263e-08, 'reg_lambda': 0.00533769704664368, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.
[I 2025-11-10 18:33:10,113] Trial 117 pruned.

Best trial: 77. Best value: 0.698431:  58%|█████▊    | 117/200 [01:26<00:49,  1.69it/s]

[I 2025-11-10 18:33:10,812] Trial 119 pruned.

Best trial: 77. Best value: 0.698431:  59%|█████▉    | 118/200 [01:28<01:21,  1.01it/s]

[I 2025-11-10 18:33:12,753] Trial 115 finished with value: 0.6395424836601306 and parameters: {'max_depth': 3, 'learning_rate': 0.047670728604851796, 'n_estimators': 915, 'subsample': 0.6617770115044865, 'colsample_bytree': 0.912496626457534, 'min_child_weight': 4, 'gamma': 1.1007894191191328, 'reg_alpha': 4.3975398080391225e-08, 'reg_lambda': 0.009583773511766603, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  60%|█████▉    | 119/200 [01:28<01:03,  1.27it/s]

[I 2025-11-10 18:33:13,063] Trial 120 finished with value: 0.6388235294117647 and parameters: {'max_depth': 4, 'learning_rate': 0.2987691444195446, 'n_estimators': 502, 'subsample': 0.6636137194221605, 'colsample_bytree': 0.8620662307986272, 'min_child_weight': 4, 'gamma': 0.39565228078014014, 'reg_alpha': 3.5733025029584814e-06, 'reg_lambda': 0.01697059537242065, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  60%|██████    | 120/200 [01:28<00:52,  1.53it/s]

[I 2025-11-10 18:33:13,406] Trial 116 finished with value: 0.6430718954248367 and parameters: {'max_depth': 3, 'learning_rate': 0.048249667109540983, 'n_estimators': 1026, 'subsample': 0.6642986418594082, 'colsample_bytree': 0.895255573985442, 'min_child_weight': 4, 'gamma': 1.0888302901026419, 'reg_alpha': 4.479525342330884e-08, 'reg_lambda': 0.01083905725223096, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  60%|██████    | 121/200 [01:29<00:42,  1.86it/s]

[I 2025-11-10 18:33:13,665] Trial 121 pruned.

Best trial: 77. Best value: 0.698431:  61%|██████    | 122/200 [01:29<00:38,  2.04it/s]

[I 2025-11-10 18:33:14,045] Trial 122 pruned.

Best trial: 77. Best value: 0.698431:  62%|██████▏   | 123/200 [01:29<00:31,  2.42it/s]

[I 2025-11-10 18:33:14,280] Trial 123 pruned.

Best trial: 77. Best value: 0.698431:  62%|██████▏   | 124/200 [01:30<00:30,  2.46it/s]

[I 2025-11-10 18:33:14,673] Trial 125 pruned.
[I 2025-11-10 18:33:14,709] Trial 118 finished with value: 0.6416993464052287 and parameters: {'max_depth': 3, 'learning_rate': 0.04740210789062634, 'n_estimators': 981, 'subsample': 0.7653669653424082, 'colsample_bytree': 0.8945792245597338, 'min_child_weight': 4, 'gamma': 0.5819793930942139, 'reg_alpha': 2.341303181112377e-07, 'reg_lambda': 0.011259176830426305, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  63%|██████▎   | 126/200 [01:30<00:25,  2.88it/s]

[I 2025-11-10 18:33:15,224] Trial 126 pruned.

Best trial: 77. Best value: 0.698431:  64%|██████▎   | 127/200 [01:33<01:01,  1.18it/s]

[I 2025-11-10 18:33:17,585] Trial 127 finished with value: 0.6279084967320261 and parameters: {'max_depth': 4, 'learning_rate': 0.19941466096543056, 'n_estimators': 656, 'subsample': 0.6838713491097953, 'colsample_bytree': 0.8893109588078613, 'min_child_weight': 4, 'gamma': 0.503992205932996, 'reg_alpha': 1.018767906729144e-08, 'reg_lambda': 0.6063377917904161, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  64%|██████▍   | 128/200 [01:33<00:48,  1.47it/s]

[I 2025-11-10 18:33:17,796] Trial 124 finished with value: 0.6637908496732026 and parameters: {'max_depth': 4, 'learning_rate': 0.23135074212920215, 'n_estimators': 981, 'subsample': 0.6497303451971931, 'colsample_bytree': 0.5162701757557531, 'min_child_weight': 4, 'gamma': 1.396014560300321, 'reg_alpha': 1.0119381078630972e-08, 'reg_lambda': 4.923172612721743, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  64%|██████▍   | 129/200 [01:33<00:41,  1.71it/s]

[I 2025-11-10 18:33:18,121] Trial 129 finished with value: 0.6552287581699346 and parameters: {'max_depth': 3, 'learning_rate': 0.19857663820044652, 'n_estimators': 660, 'subsample': 0.620760606844874, 'colsample_bytree': 0.8762619172229247, 'min_child_weight': 4, 'gamma': 0.47582813165399584, 'reg_alpha': 3.3369857634720424e-08, 'reg_lambda': 0.5356738321778614, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  65%|██████▌   | 130/200 [01:33<00:34,  2.03it/s]

[I 2025-11-10 18:33:18,383] Trial 130 pruned.

Best trial: 77. Best value: 0.698431:  66%|██████▌   | 132/200 [01:34<00:24,  2.83it/s]

[I 2025-11-10 18:33:18,646] Trial 128 finished with value: 0.6522875816993464 and parameters: {'max_depth': 4, 'learning_rate': 0.19252364258951316, 'n_estimators': 869, 'subsample': 0.6827565211882975, 'colsample_bytree': 0.8782554745978901, 'min_child_weight': 4, 'gamma': 1.2121764342576942, 'reg_alpha': 4.477055463289056e-07, 'reg_lambda': 0.5934308185507986, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.
[I 2025-11-10 18:33:18,818] Trial 131 pruned.

Best trial: 77. Best value: 0.698431:  66%|██████▌   | 132/200 [01:34<00:24,  2.83it/s]

[I 2025-11-10 18:33:18,896] Trial 132 pruned.

Best trial: 77. Best value: 0.698431:  68%|██████▊   | 135/200 [01:38<00:52,  1.23it/s]

[I 2025-11-10 18:33:22,520] Trial 136 finished with value: 0.6719607843137255 and parameters: {'max_depth': 4, 'learning_rate': 0.18826959231439977, 'n_estimators': 857, 'subsample': 0.6357992169694303, 'colsample_bytree': 0.8533341337927506, 'min_child_weight': 4, 'gamma': 1.7740094537853077, 'reg_alpha': 2.8209564815188227e-06, 'reg_lambda': 0.6745514796369922, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.
[I 2025-11-10 18:33:22,651] Trial 133 finished with value: 0.6542483660130719 and parameters: {'max_depth': 3, 'learning_rate': 0.1901049601097565, 'n_estimators': 956, 'subsample': 0.6336031013041324, 'colsample_bytree': 0.6144445790868782, 'min_child_weight': 3, 'gamma': 0.11366793182907242, 'reg_alpha': 1.4795069908096474e-08, 'reg_lambda': 0.6084612723043633, 'max_delta_step': 4}. Best is trial 77 with value: 0.6984313725490197.
[I 2025-11-10 18:33:22,667] Trial 135 finished with value: 0.6331372549019608 and parameters: {'max_depth': 4, 'learning_rate': 0.18718427797635048, 'n_estimators': 855, 'subsample': 0.7215260170695997, 'colsample_bytree': 0.8616541677669132, 'min_child_weight': 4, 'gamma': 0.16136656550998274, 'reg_alpha': 1.621744211833199e-08, 'reg_lambda': 0.2504930957822029, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  68%|██████▊   | 137/200 [01:38<00:33,  1.88it/s]

[I 2025-11-10 18:33:22,919] Trial 134 finished with value: 0.6569934640522875 and parameters: {'max_depth': 4, 'learning_rate': 0.18830817769263336, 'n_estimators': 946, 'subsample': 0.6339152268234668, 'colsample_bytree': 0.863810800244291, 'min_child_weight': 4, 'gamma': 0.17892559624850435, 'reg_alpha': 1.7773273690433242e-08, 'reg_lambda': 0.3003571816351886, 'max_delta_step': 4}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  69%|██████▉   | 138/200 [01:39<00:33,  1.87it/s]

[I 2025-11-10 18:33:23,462] Trial 139 pruned.

Best trial: 77. Best value: 0.698431:  70%|██████▉   | 139/200 [01:39<00:32,  1.89it/s]

[I 2025-11-10 18:33:23,966] Trial 140 pruned.

Best trial: 77. Best value: 0.698431:  70%|███████   | 140/200 [01:40<00:32,  1.86it/s]

[I 2025-11-10 18:33:24,529] Trial 141 pruned.

Best trial: 77. Best value: 0.698431:  70%|███████   | 141/200 [01:40<00:37,  1.57it/s]

[I 2025-11-10 18:33:25,433] Trial 143 pruned.

Best trial: 77. Best value: 0.698431:  71%|███████   | 142/200 [01:41<00:41,  1.39it/s]

[I 2025-11-10 18:33:26,368] Trial 137 finished with value: 0.6205882352941176 and parameters: {'max_depth': 4, 'learning_rate': 0.16155309776689283, 'n_estimators': 862, 'subsample': 0.6803520252436815, 'colsample_bytree': 0.5749230355317935, 'min_child_weight': 4, 'gamma': 1.3328005080435132, 'reg_alpha': 1.1333968353455783e-06, 'reg_lambda': 0.7337794646436936, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  72%|███████▏  | 143/200 [01:42<00:33,  1.72it/s]

[I 2025-11-10 18:33:26,607] Trial 138 finished with value: 0.6318954248366013 and parameters: {'max_depth': 4, 'learning_rate': 0.18865335842910166, 'n_estimators': 875, 'subsample': 0.6372097673434219, 'colsample_bytree': 0.5288743854900403, 'min_child_weight': 3, 'gamma': 1.82144219565218, 'reg_alpha': 1.053729028524524e-08, 'reg_lambda': 0.8895710812734932, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  72%|███████▏  | 144/200 [01:44<00:53,  1.05it/s]

[I 2025-11-10 18:33:28,457] Trial 142 finished with value: 0.6064052287581699 and parameters: {'max_depth': 5, 'learning_rate': 0.15920235985060618, 'n_estimators': 1055, 'subsample': 0.6331234737159607, 'colsample_bytree': 0.5817000069159802, 'min_child_weight': 3, 'gamma': 2.607771352119923, 'reg_alpha': 7.030219601400316e-08, 'reg_lambda': 0.00013246224519966167, 'max_delta_step': 5}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  72%|███████▎  | 145/200 [01:44<00:49,  1.12it/s]

[I 2025-11-10 18:33:29,223] Trial 144 finished with value: 0.6415686274509803 and parameters: {'max_depth': 4, 'learning_rate': 0.20344372102940494, 'n_estimators': 869, 'subsample': 0.6556222297325672, 'colsample_bytree': 0.8550284622702327, 'min_child_weight': 4, 'gamma': 2.335011980436337, 'reg_alpha': 8.809551121295405e-07, 'reg_lambda': 0.5464072672432153, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  74%|███████▎  | 147/200 [01:45<00:37,  1.41it/s]

[I 2025-11-10 18:33:30,261] Trial 145 finished with value: 0.6488888888888888 and parameters: {'max_depth': 4, 'learning_rate': 0.18227411538853464, 'n_estimators': 906, 'subsample': 0.624607361558979, 'colsample_bytree': 0.845215145907898, 'min_child_weight': 4, 'gamma': 1.465743179074667, 'reg_alpha': 2.7501890483358552e-08, 'reg_lambda': 0.6018378670110666, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.
[I 2025-11-10 18:33:30,433] Trial 146 finished with value: 0.6499346405228759 and parameters: {'max_depth': 5, 'learning_rate': 0.20472536381013917, 'n_estimators': 890, 'subsample': 0.6261645826478954, 'colsample_bytree': 0.8539259142510771, 'min_child_weight': 4, 'gamma': 0.4413680454912183, 'reg_alpha': 3.034269502436927e-08, 'reg_lambda': 2.6425886517160517, 'max_delta_step': 4}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  74%|███████▍  | 148/200 [01:46<00:40,  1.29it/s]

[I 2025-11-10 18:33:31,361] Trial 150 pruned.

Best trial: 77. Best value: 0.698431:  74%|███████▍  | 149/200 [01:47<00:38,  1.32it/s]

[I 2025-11-10 18:33:32,086] Trial 151 pruned.

Best trial: 77. Best value: 0.698431:  75%|███████▌  | 150/200 [01:48<00:32,  1.53it/s]

[I 2025-11-10 18:33:32,485] Trial 147 finished with value: 0.6471241830065361 and parameters: {'max_depth': 4, 'learning_rate': 0.23294656833167415, 'n_estimators': 900, 'subsample': 0.65617601583961, 'colsample_bytree': 0.8589481193145938, 'min_child_weight': 4, 'gamma': 1.4306515666377746, 'reg_alpha': 2.7404759179902915e-08, 'reg_lambda': 0.5693927156605729, 'max_delta_step': 4}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  76%|███████▌  | 151/200 [01:48<00:29,  1.64it/s]

[I 2025-11-10 18:33:32,992] Trial 152 pruned.

Best trial: 77. Best value: 0.698431:  76%|███████▋  | 153/200 [01:49<00:19,  2.44it/s]

[I 2025-11-10 18:33:33,334] Trial 148 finished with value: 0.6780392156862745 and parameters: {'max_depth': 4, 'learning_rate': 0.1789343386441737, 'n_estimators': 902, 'subsample': 0.6250074955552721, 'colsample_bytree': 0.866460093617128, 'min_child_weight': 4, 'gamma': 0.30614071646708724, 'reg_alpha': 3.377242253057002e-08, 'reg_lambda': 0.16402215538216888, 'max_delta_step': 4}. Best is trial 77 with value: 0.6984313725490197.
[I 2025-11-10 18:33:33,464] Trial 153 pruned.

Best trial: 77. Best value: 0.698431:  77%|███████▋  | 154/200 [01:50<00:29,  1.54it/s]

[I 2025-11-10 18:33:34,671] Trial 149 finished with value: 0.6165359477124183 and parameters: {'max_depth': 4, 'learning_rate': 0.22582476574099383, 'n_estimators': 952, 'subsample': 0.6069417479059173, 'colsample_bytree': 0.8762466907181947, 'min_child_weight': 4, 'gamma': 0.28566001557877385, 'reg_alpha': 2.579964491212993e-06, 'reg_lambda': 1.3472966896679133, 'max_delta_step': 4}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  78%|███████▊  | 155/200 [01:51<00:33,  1.36it/s]

[I 2025-11-10 18:33:35,603] Trial 157 pruned.

Best trial: 77. Best value: 0.698431:  78%|███████▊  | 156/200 [01:52<00:44,  1.00s/it]

[I 2025-11-10 18:33:37,232] Trial 154 finished with value: 0.5854901960784313 and parameters: {'max_depth': 4, 'learning_rate': 0.1763946116163655, 'n_estimators': 981, 'subsample': 0.6897578547526262, 'colsample_bytree': 0.7154162843754386, 'min_child_weight': 4, 'gamma': 0.11726065940068497, 'reg_alpha': 3.8807036851041815e-07, 'reg_lambda': 0.21225212060074888, 'max_delta_step': 5}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  79%|███████▉  | 158/200 [01:53<00:26,  1.59it/s]

[I 2025-11-10 18:33:37,669] Trial 155 finished with value: 0.6475816993464052 and parameters: {'max_depth': 4, 'learning_rate': 0.072606730638628, 'n_estimators': 987, 'subsample': 0.6179270803399923, 'colsample_bytree': 0.8616803923904196, 'min_child_weight': 4, 'gamma': 0.1964129337704833, 'reg_alpha': 5.614591869892921e-08, 'reg_lambda': 0.1806439573540941, 'max_delta_step': 4}. Best is trial 77 with value: 0.6984313725490197.
[I 2025-11-10 18:33:37,821] Trial 156 finished with value: 0.6350980392156863 and parameters: {'max_depth': 4, 'learning_rate': 0.09424490090011772, 'n_estimators': 986, 'subsample': 0.6111265015312353, 'colsample_bytree': 0.87228843860603, 'min_child_weight': 4, 'gamma': 0.19021022341329008, 'reg_alpha': 4.984045128807804e-08, 'reg_lambda': 0.33417406845065417, 'max_delta_step': 4}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  80%|███████▉  | 159/200 [01:54<00:28,  1.43it/s]

[I 2025-11-10 18:33:38,677] Trial 161 pruned.

Best trial: 77. Best value: 0.698431:  80%|████████  | 160/200 [01:55<00:28,  1.39it/s]

[I 2025-11-10 18:33:39,446] Trial 162 pruned.

Best trial: 77. Best value: 0.698431:  80%|████████  | 161/200 [01:55<00:22,  1.75it/s]

[I 2025-11-10 18:33:39,673] Trial 158 finished with value: 0.668562091503268 and parameters: {'max_depth': 4, 'learning_rate': 0.20001332704651567, 'n_estimators': 912, 'subsample': 0.6156884555244162, 'colsample_bytree': 0.8657794039192703, 'min_child_weight': 4, 'gamma': 0.5179680819583088, 'reg_alpha': 3.850429750946438e-08, 'reg_lambda': 0.0004493273109649523, 'max_delta_step': 5}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  81%|████████  | 162/200 [01:55<00:21,  1.75it/s]

[I 2025-11-10 18:33:40,240] Trial 163 pruned.

Best trial: 77. Best value: 0.698431:  82%|████████▏ | 163/200 [01:56<00:23,  1.54it/s]

[I 2025-11-10 18:33:41,069] Trial 165 pruned.

Best trial: 77. Best value: 0.698431:  82%|████████▏ | 164/200 [01:56<00:19,  1.81it/s]

[I 2025-11-10 18:33:41,396] Trial 159 finished with value: 0.6415032679738563 and parameters: {'max_depth': 4, 'learning_rate': 0.09155671551739396, 'n_estimators': 911, 'subsample': 0.6223543533518107, 'colsample_bytree': 0.8710822577754129, 'min_child_weight': 4, 'gamma': 0.4368759737898437, 'reg_alpha': 1.7361609772354054e-08, 'reg_lambda': 0.1288849209292661, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  83%|████████▎ | 166/200 [01:57<00:13,  2.45it/s]

[I 2025-11-10 18:33:41,827] Trial 160 finished with value: 0.6529411764705882 and parameters: {'max_depth': 4, 'learning_rate': 0.19720972807195383, 'n_estimators': 914, 'subsample': 0.6551382541592453, 'colsample_bytree': 0.8640930168344259, 'min_child_weight': 4, 'gamma': 0.4696244253769185, 'reg_alpha': 1.7395036267878596e-08, 'reg_lambda': 0.00043512466901929174, 'max_delta_step': 3}. Best is trial 77 with value: 0.6984313725490197.
[I 2025-11-10 18:33:41,991] Trial 166 pruned.

Best trial: 77. Best value: 0.698431:  84%|████████▎ | 167/200 [01:57<00:12,  2.64it/s]

[I 2025-11-10 18:33:42,297] Trial 167 pruned.

Best trial: 77. Best value: 0.698431:  84%|████████▍ | 168/200 [01:59<00:22,  1.40it/s]

[I 2025-11-10 18:33:43,786] Trial 164 finished with value: 0.6536601307189542 and parameters: {'max_depth': 4, 'learning_rate': 0.1919294296478286, 'n_estimators': 910, 'subsample': 0.6275189542449701, 'colsample_bytree': 0.9049408625445468, 'min_child_weight': 4, 'gamma': 0.46289001732635515, 'reg_alpha': 1.509560766648045e-08, 'reg_lambda': 0.0013628512531565825, 'max_delta_step': 5}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  84%|████████▍ | 169/200 [02:00<00:23,  1.32it/s]

[I 2025-11-10 18:33:44,656] Trial 171 pruned.

Best trial: 77. Best value: 0.698431:  85%|████████▌ | 170/200 [02:01<00:27,  1.10it/s]

[I 2025-11-10 18:33:45,903] Trial 169 finished with value: 0.6269281045751633 and parameters: {'max_depth': 3, 'learning_rate': 0.27709044076893474, 'n_estimators': 936, 'subsample': 0.6007787931353674, 'colsample_bytree': 0.8354758829867653, 'min_child_weight': 4, 'gamma': 0.320894290078007, 'reg_alpha': 3.659362329508219e-08, 'reg_lambda': 0.0005761508465475114, 'max_delta_step': 4}. Best is trial 77 with value: 0.6984313725490197.
[I 2025-11-10 18:33:45,909] Trial 168 finished with value: 0.6768627450980392 and parameters: {'max_depth': 5, 'learning_rate': 0.2509145905024709, 'n_estimators': 940, 'subsample': 0.6394854380533991, 'colsample_bytree': 0.838930173063732, 'min_child_weight': 4, 'gamma': 0.3241586851537787, 'reg_alpha': 3.5408384692110904e-08, 'reg_lambda': 0.0021186885643623495, 'max_delta_step': 5}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  86%|████████▌ | 172/200 [02:02<00:17,  1.63it/s]

[I 2025-11-10 18:33:46,451] Trial 170 finished with value: 0.6486274509803922 and parameters: {'max_depth': 3, 'learning_rate': 0.2086394291557352, 'n_estimators': 934, 'subsample': 0.6140845425045893, 'colsample_bytree': 0.8386397394057139, 'min_child_weight': 3, 'gamma': 0.6024243011785168, 'reg_alpha': 3.647882949875456e-08, 'reg_lambda': 4.328040541325274e-05, 'max_delta_step': 4}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  86%|████████▋ | 173/200 [02:04<00:29,  1.11s/it]

[I 2025-11-10 18:33:49,061] Trial 172 finished with value: 0.5867973856209151 and parameters: {'max_depth': 3, 'learning_rate': 0.17505590489137193, 'n_estimators': 1003, 'subsample': 0.6108861412323807, 'colsample_bytree': 0.9310834273376031, 'min_child_weight': 4, 'gamma': 0.8017505259148052, 'reg_alpha': 1.388528175406505e-08, 'reg_lambda': 0.00039897652400706034, 'max_delta_step': 6}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 77. Best value: 0.698431:  87%|████████▋ | 174/200 [02:05<00:28,  1.10s/it]

[I 2025-11-10 18:33:50,148] Trial 175 finished with value: 0.6698692810457516 and parameters: {'max_depth': 5, 'learning_rate': 0.26683065284148555, 'n_estimators': 842, 'subsample': 0.6423815971081055, 'colsample_bytree': 0.9418163063317158, 'min_child_weight': 4, 'gamma': 0.7692281227576143, 'reg_alpha': 1.3351396171765734e-08, 'reg_lambda': 1.969597242620189, 'max_delta_step': 5}. Best is trial 77 with value: 0.6984313725490197.

Best trial: 173. Best value: 0.698824:  88%|████████▊ | 175/200 [02:05<00:21,  1.15it/s]

[I 2025-11-10 18:33:50,396] Trial 174 finished with value: 0.6860130718954248 and parameters: {'max_depth': 5, 'learning_rate': 0.20674193271200428, 'n_estimators': 1010, 'subsample': 0.6120676628047138, 'colsample_bytree': 0.9431013258822214, 'min_child_weight': 4, 'gamma': 0.7647421243650423, 'reg_alpha': 2.2775827795960294e-08, 'reg_lambda': 0.003620107536107257, 'max_delta_step': 6}. Best is trial 77 with value: 0.6984313725490197.
[I 2025-11-10 18:33:50,396] Trial 173 finished with value: 0.6988235294117646 and parameters: {'max_depth': 5, 'learning_rate': 0.20790479003162562, 'n_estimators': 1012, 'subsample': 0.6140263762858663, 'colsample_bytree': 0.9199981419616079, 'min_child_weight': 4, 'gamma': 0.7478791232632145, 'reg_alpha': 2.5236879282757247e-08, 'reg_lambda': 0.0009321886220292077, 'max_delta_step': 6}. Best is trial 173 with value: 0.6988235294117646.

Best trial: 173. Best value: 0.698824:  88%|████████▊ | 177/200 [02:06<00:14,  1.58it/s]

[I 2025-11-10 18:33:51,048] Trial 177 pruned.

Best trial: 173. Best value: 0.698824:  89%|████████▉ | 178/200 [02:06<00:12,  1.76it/s]

[I 2025-11-10 18:33:51,410] Trial 179 pruned.

Best trial: 173. Best value: 0.698824:  90%|████████▉ | 179/200 [02:07<00:12,  1.73it/s]

[I 2025-11-10 18:33:52,019] Trial 180 pruned.

Best trial: 173. Best value: 0.698824:  90%|█████████ | 180/200 [02:07<00:10,  1.95it/s]

[I 2025-11-10 18:33:52,346] Trial 181 pruned.

Best trial: 173. Best value: 0.698824:  90%|█████████ | 181/200 [02:08<00:10,  1.85it/s]

[I 2025-11-10 18:33:52,959] Trial 176 finished with value: 0.6813725490196079 and parameters: {'max_depth': 5, 'learning_rate': 0.267172763765403, 'n_estimators': 849, 'subsample': 0.6452824308516275, 'colsample_bytree': 0.7827962731333171, 'min_child_weight': 4, 'gamma': 0.3653498836168966, 'reg_alpha': 2.224904270899083e-08, 'reg_lambda': 0.0013270972129342284, 'max_delta_step': 5}. Best is trial 173 with value: 0.6988235294117646.
[I 2025-11-10 18:33:52,967] Trial 182 pruned.

Best trial: 173. Best value: 0.698824:  92%|█████████▏| 183/200 [02:09<00:07,  2.16it/s]

[I 2025-11-10 18:33:53,693] Trial 185 pruned.
[I 2025-11-10 18:33:53,697] Trial 184 pruned.

Best trial: 173. Best value: 0.698824:  92%|█████████▎| 185/200 [02:10<00:06,  2.31it/s]

[I 2025-11-10 18:33:54,459] Trial 186 pruned.

Best trial: 173. Best value: 0.698824:  93%|█████████▎| 186/200 [02:10<00:07,  1.98it/s]

[I 2025-11-10 18:33:55,229] Trial 178 finished with value: 0.6670588235294118 and parameters: {'max_depth': 5, 'learning_rate': 0.26866783234019853, 'n_estimators': 1048, 'subsample': 0.6428834793330106, 'colsample_bytree': 0.9487937487721255, 'min_child_weight': 4, 'gamma': 0.8817799777353238, 'reg_alpha': 2.2749639991283554e-08, 'reg_lambda': 0.0012089798158779997, 'max_delta_step': 6}. Best is trial 173 with value: 0.6988235294117646.

Best trial: 173. Best value: 0.698824:  94%|█████████▎| 187/200 [02:11<00:07,  1.73it/s]

[I 2025-11-10 18:33:56,038] Trial 189 pruned.

Best trial: 173. Best value: 0.698824:  94%|█████████▍| 189/200 [02:12<00:05,  1.91it/s]

[I 2025-11-10 18:33:56,933] Trial 183 finished with value: 0.6903921568627451 and parameters: {'max_depth': 5, 'learning_rate': 0.23962279551386353, 'n_estimators': 1006, 'subsample': 0.6448592703904771, 'colsample_bytree': 0.9610699069075425, 'min_child_weight': 4, 'gamma': 0.8413687114139607, 'reg_alpha': 1.0276487592384805e-08, 'reg_lambda': 0.0017025417921906498, 'max_delta_step': 6}. Best is trial 173 with value: 0.6988235294117646.
[I 2025-11-10 18:33:57,084] Trial 190 pruned.

Best trial: 187. Best value: 0.699216:  95%|█████████▌| 190/200 [02:13<00:05,  1.98it/s]

[I 2025-11-10 18:33:57,544] Trial 187 finished with value: 0.6992156862745099 and parameters: {'max_depth': 5, 'learning_rate': 0.2539406251563845, 'n_estimators': 823, 'subsample': 0.6624238519579974, 'colsample_bytree': 0.9704873492406735, 'min_child_weight': 4, 'gamma': 0.8440155522922821, 'reg_alpha': 4.3941341245282506e-08, 'reg_lambda': 0.0020465076677226414, 'max_delta_step': 6}. Best is trial 187 with value: 0.6992156862745099.

Best trial: 187. Best value: 0.699216:  96%|█████████▌| 191/200 [02:13<00:05,  1.74it/s]

[I 2025-11-10 18:33:58,291] Trial 188 finished with value: 0.6694117647058824 and parameters: {'max_depth': 5, 'learning_rate': 0.23498244548136624, 'n_estimators': 861, 'subsample': 0.616884060163457, 'colsample_bytree': 0.9636752691668607, 'min_child_weight': 4, 'gamma': 0.890064755071861, 'reg_alpha': 2.1443465692146658e-08, 'reg_lambda': 0.007266935929271012, 'max_delta_step': 5}. Best is trial 187 with value: 0.6992156862745099.

Best trial: 187. Best value: 0.699216:  96%|█████████▌| 192/200 [02:16<00:09,  1.19s/it]

[I 2025-11-10 18:34:01,007] Trial 193 finished with value: 0.6594771241830065 and parameters: {'max_depth': 5, 'learning_rate': 0.24749445626168362, 'n_estimators': 809, 'subsample': 0.6515128511892286, 'colsample_bytree': 0.9801584844838996, 'min_child_weight': 4, 'gamma': 0.8617144917781209, 'reg_alpha': 1.2173687517068743e-07, 'reg_lambda': 0.0030980697130401085, 'max_delta_step': 7}. Best is trial 187 with value: 0.6992156862745099.

Best trial: 187. Best value: 0.699216:  97%|█████████▋| 194/200 [02:17<00:04,  1.35it/s]

[I 2025-11-10 18:34:01,560] Trial 191 finished with value: 0.6681045751633987 and parameters: {'max_depth': 5, 'learning_rate': 0.2371474055233767, 'n_estimators': 1058, 'subsample': 0.656816792183077, 'colsample_bytree': 0.9753169878513435, 'min_child_weight': 4, 'gamma': 0.9595941028813986, 'reg_alpha': 1.0889115849784773e-08, 'reg_lambda': 0.003296750144461656, 'max_delta_step': 7}. Best is trial 187 with value: 0.6992156862745099.
[I 2025-11-10 18:34:01,662] Trial 192 finished with value: 0.6510457516339868 and parameters: {'max_depth': 5, 'learning_rate': 0.2403522335980662, 'n_estimators': 1059, 'subsample': 0.6519045645279533, 'colsample_bytree': 0.9584051553702478, 'min_child_weight': 4, 'gamma': 1.0027079228842304, 'reg_alpha': 1.1697717395189675e-07, 'reg_lambda': 0.0027376216138810428, 'max_delta_step': 7}. Best is trial 187 with value: 0.6992156862745099.

Best trial: 187. Best value: 0.699216:  98%|█████████▊| 196/200 [02:17<00:01,  2.26it/s]

[I 2025-11-10 18:34:01,833] Trial 194 finished with value: 0.6515032679738562 and parameters: {'max_depth': 5, 'learning_rate': 0.2360726297789945, 'n_estimators': 804, 'subsample': 0.6506324182463286, 'colsample_bytree': 0.9718301325776137, 'min_child_weight': 4, 'gamma': 0.980016730671831, 'reg_alpha': 1.0645702980224892e-07, 'reg_lambda': 0.007262578348908646, 'max_delta_step': 7}. Best is trial 187 with value: 0.6992156862745099.
[I 2025-11-10 18:34:01,966] Trial 195 pruned.

Best trial: 187. Best value: 0.699216:  98%|█████████▊| 197/200 [02:21<00:04,  1.62s/it]

[I 2025-11-10 18:34:06,364] Trial 196 finished with value: 0.6696078431372549 and parameters: {'max_depth': 5, 'learning_rate': 0.2381245543612135, 'n_estimators': 1081, 'subsample': 0.6456291983615545, 'colsample_bytree': 0.9673869354257646, 'min_child_weight': 4, 'gamma': 0.9993004349137273, 'reg_alpha': 1.0087497637974546e-08, 'reg_lambda': 0.007930734802726666, 'max_delta_step': 6}. Best is trial 187 with value: 0.6992156862745099.

Best trial: 187. Best value: 0.699216:  99%|█████████▉| 198/200 [02:22<00:02,  1.20s/it]

[I 2025-11-10 18:34:06,572] Trial 199 finished with value: 0.6957516339869281 and parameters: {'max_depth': 5, 'learning_rate': 0.263050785840379, 'n_estimators': 1077, 'subsample': 0.6694953560383353, 'colsample_bytree': 0.9993132489770923, 'min_child_weight': 4, 'gamma': 0.7836875570365811, 'reg_alpha': 1.2780805794948163e-08, 'reg_lambda': 0.004456158474708875, 'max_delta_step': 5}. Best is trial 187 with value: 0.6992156862745099.
[I 2025-11-10 18:34:06,650] Trial 197 finished with value: 0.6626143790849672 and parameters: {'max_depth': 5, 'learning_rate': 0.22019079903438674, 'n_estimators': 1153, 'subsample': 0.6679747925378531, 'colsample_bytree': 0.971190747188859, 'min_child_weight': 4, 'gamma': 1.0016639302588022, 'reg_alpha': 1.0360302768530782e-08, 'reg_lambda': 0.006891086372674175, 'max_delta_step': 6}. Best is trial 187 with value: 0.6992156862745099.

Best trial: 187. Best value: 0.699216: 100%|██████████| 200/200 [02:22<00:00,  1.41it/s]

[I 2025-11-10 18:34:06,773] Trial 198 finished with value: 0.6826143790849674 and parameters: {'max_depth': 5, 'learning_rate': 0.26615036009120907, 'n_estimators': 1181, 'subsample': 0.6675615054642889, 'colsample_bytree': 0.9943457026362503, 'min_child_weight': 4, 'gamma': 0.834764092060206, 'reg_alpha': 1.057180469384795e-08, 'reg_lambda': 0.004660488100651674, 'max_delta_step': 6}. Best is trial 187 with value: 0.6992156862745099.
   dataset  cv_best_value  test_balanced_accuracy  test_roc_auc  n_trials
0      3_3       0.691754                0.748447      0.878882       200
1     17_1       0.634834                0.698758      0.726708       200
2      3_5       0.579786                0.649068      0.546584       200
3     18_1       0.710702                0.621118      0.757764       200
4     16_1       0.696248                0.605590      0.723602       200
5      3_1       0.561754                0.574534      0.450311       200
6      3_4       0.617934                0.512422      0.552795       200
7      9_1       0.647167                0.506119      0.486888       200
8      1_1       0.500000                0.500000      0.500000       200
9      3_2       0.500000                0.500000      0.500000       200
10    10_1       0.558285                0.496894      0.465839       200
11    19_1       0.699216                0.484848      0.428030       200
12    15_1       0.561170                0.425466      0.419255       200

In [110]:
# Combined embedings
datasets = task_comb_dfs

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="roc_auc",     # or "roc_auc"
    n_trials=200,
    n_splits=5,
    output_dir="xgb_results_combined",
)
print(summary)

[I 2025-11-10 18:34:07,803] A new study created in memory with name: 1_1_roc_auc
Best trial: 0. Best value: 0.5:   0%|          | 1/200 [00:01<04:52,  1.47s/it]

[I 2025-11-10 18:34:09,266] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.017715524591923888, 'n_estimators': 346, 'subsample': 0.9046891625996505, 'colsample_bytree': 0.8698761953553409, 'min_child_weight': 10, 'gamma': 0.15787730531047484, 'reg_alpha': 0.024639554818429287, 'reg_lambda': 0.009041282162397812, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   1%|          | 2/200 [00:02<03:27,  1.05s/it]

[I 2025-11-10 18:34:10,015] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.15541201827410808, 'n_estimators': 541, 'subsample': 0.971226156189978, 'colsample_bytree': 0.6349115848907274, 'min_child_weight': 8, 'gamma': 0.3603216440363227, 'reg_alpha': 0.19154316535316024, 'reg_lambda': 4.375201487866999, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   2%|▏         | 3/200 [00:04<04:35,  1.40s/it]

[I 2025-11-10 18:34:11,839] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.13464321229766404, 'n_estimators': 989, 'subsample': 0.7518166924609752, 'colsample_bytree': 0.8995875854843345, 'min_child_weight': 5, 'gamma': 3.732311078669472, 'reg_alpha': 0.00675083799830493, 'reg_lambda': 0.00013704339376224468, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   2%|▏         | 4/200 [00:05<05:00,  1.54s/it]

[I 2025-11-10 18:34:13,579] Trial 3 finished with value: 0.3782066276803119 and parameters: {'max_depth': 6, 'learning_rate': 0.022805565045055612, 'n_estimators': 1028, 'subsample': 0.7733757921680846, 'colsample_bytree': 0.8792128380165133, 'min_child_weight': 3, 'gamma': 1.7710113979109336, 'reg_alpha': 1.5411727325431062e-05, 'reg_lambda': 6.548525854999265e-05, 'max_delta_step': 9}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   2%|▎         | 5/200 [00:05<03:24,  1.05s/it]

[I 2025-11-10 18:34:13,770] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.05710953175933059, 'n_estimators': 1153, 'subsample': 0.7979461345885817, 'colsample_bytree': 0.848530649869319, 'min_child_weight': 6, 'gamma': 0.3216305961770799, 'reg_alpha': 1.73871845255568e-05, 'reg_lambda': 0.4327774027610267, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   3%|▎         | 6/200 [00:07<03:54,  1.21s/it]

[I 2025-11-10 18:34:15,288] Trial 5 finished with value: 0.41898635477582846 and parameters: {'max_depth': 5, 'learning_rate': 0.24650652301703302, 'n_estimators': 830, 'subsample': 0.8362527508866351, 'colsample_bytree': 0.8307665078669708, 'min_child_weight': 1, 'gamma': 2.0717214568258786, 'reg_alpha': 4.848779539140232e-08, 'reg_lambda': 4.895243395333822e-05, 'max_delta_step': 1}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   4%|▎         | 7/200 [00:08<03:17,  1.02s/it]

[I 2025-11-10 18:34:15,935] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.060848060691110914, 'n_estimators': 1084, 'subsample': 0.6162206693904221, 'colsample_bytree': 0.6902015741840994, 'min_child_weight': 7, 'gamma': 4.0300714169610234, 'reg_alpha': 2.718011347462574e-05, 'reg_lambda': 2.46251822041647e-07, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   4%|▍         | 8/200 [00:08<02:47,  1.15it/s]

[I 2025-11-10 18:34:16,476] Trial 7 finished with value: 0.43089668615984406 and parameters: {'max_depth': 8, 'learning_rate': 0.25607920307276427, 'n_estimators': 673, 'subsample': 0.7289238727559304, 'colsample_bytree': 0.6766570400288899, 'min_child_weight': 3, 'gamma': 4.39217851033748, 'reg_alpha': 0.0007173101732618867, 'reg_lambda': 1.8747801934470874e-08, 'max_delta_step': 10}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   4%|▍         | 9/200 [00:10<03:29,  1.09s/it]

[I 2025-11-10 18:34:18,063] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.12859822995902626, 'n_estimators': 418, 'subsample': 0.8096087306242834, 'colsample_bytree': 0.6440968996403462, 'min_child_weight': 7, 'gamma': 4.658852957453608, 'reg_alpha': 9.020457120554134e-06, 'reg_lambda': 0.0006742743395475178, 'max_delta_step': 10}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   5%|▌         | 10/200 [00:12<04:14,  1.34s/it]

[I 2025-11-10 18:34:19,943] Trial 12 finished with value: 0.4336062378167641 and parameters: {'max_depth': 4, 'learning_rate': 0.05141218651370946, 'n_estimators': 463, 'subsample': 0.6471626133980868, 'colsample_bytree': 0.9965165039777495, 'min_child_weight': 4, 'gamma': 3.503537351278252, 'reg_alpha': 5.831278676540805e-06, 'reg_lambda': 1.363651241111674e-05, 'max_delta_step': 0}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   6%|▌         | 11/200 [00:13<03:51,  1.22s/it]

[I 2025-11-10 18:34:20,906] Trial 13 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.010285443860160741, 'n_estimators': 204, 'subsample': 0.989218335025516, 'colsample_bytree': 0.5472058263902106, 'min_child_weight': 10, 'gamma': 1.4129172940182233, 'reg_alpha': 4.785181690275727, 'reg_lambda': 0.02377681369119701, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   6%|▌         | 12/200 [00:13<02:56,  1.06it/s]

[I 2025-11-10 18:34:21,202] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.17184169971878502, 'n_estimators': 1089, 'subsample': 0.9279250154637502, 'colsample_bytree': 0.8051091958420864, 'min_child_weight': 3, 'gamma': 3.369087208437164, 'reg_alpha': 7.96157998822697, 'reg_lambda': 1.1085959129240519e-05, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   6%|▋         | 13/200 [00:13<02:21,  1.32it/s]

[I 2025-11-10 18:34:21,532] Trial 8 pruned.

Best trial: 0. Best value: 0.5:   7%|▋         | 14/200 [00:15<03:19,  1.07s/it]

[I 2025-11-10 18:34:23,332] Trial 9 finished with value: 0.39575048732943474 and parameters: {'max_depth': 8, 'learning_rate': 0.010208675318720632, 'n_estimators': 1246, 'subsample': 0.9137428065674529, 'colsample_bytree': 0.8843745622449605, 'min_child_weight': 2, 'gamma': 2.60802630612472, 'reg_alpha': 0.3051496332860712, 'reg_lambda': 4.292794715152381, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   8%|▊         | 15/200 [00:18<05:08,  1.67s/it]

[I 2025-11-10 18:34:26,380] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.010220474119711614, 'n_estimators': 1303, 'subsample': 0.5144240510895872, 'colsample_bytree': 0.9762391283001361, 'min_child_weight': 9, 'gamma': 2.883234078648324, 'reg_alpha': 0.011382967379533858, 'reg_lambda': 0.003982733063872864, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:   8%|▊         | 17/200 [00:19<03:01,  1.01it/s]

[I 2025-11-10 18:34:26,980] Trial 17 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.026493018560394103, 'n_estimators': 824, 'subsample': 0.5093852139011696, 'colsample_bytree': 0.9657426337698025, 'min_child_weight': 10, 'gamma': 1.0514591283469858, 'reg_alpha': 0.005252102292492605, 'reg_lambda': 0.00458494184703999, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:34:27,153] Trial 18 pruned.

Best trial: 0. Best value: 0.5:   9%|▉         | 18/200 [00:19<02:19,  1.30it/s]

[I 2025-11-10 18:34:27,399] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.010630775582106951, 'n_estimators': 1341, 'subsample': 0.5322182976580305, 'colsample_bytree': 0.9481509823553045, 'min_child_weight': 10, 'gamma': 2.641144131417194, 'reg_alpha': 0.010707186941071764, 'reg_lambda': 0.0056605268169098244, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:34:27,406] Trial 15 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.012441780902516278, 'n_estimators': 1486, 'subsample': 0.5371614181685551, 'colsample_bytree': 0.951187381215429, 'min_child_weight': 10, 'gamma': 2.8312044528029716, 'reg_alpha': 0.009113040601408851, 'reg_lambda': 0.006265193197708218, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  10%|█         | 20/200 [00:20<01:48,  1.65it/s]

[I 2025-11-10 18:34:28,227] Trial 19 finished with value: 0.4955555555555556 and parameters: {'max_depth': 9, 'learning_rate': 0.09574643985732269, 'n_estimators': 237, 'subsample': 0.8752146680702959, 'colsample_bytree': 0.9179297102750483, 'min_child_weight': 5, 'gamma': 4.988935870163255, 'reg_alpha': 0.04553161199175379, 'reg_lambda': 0.08890881889333477, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  11%|█         | 22/200 [00:20<01:16,  2.33it/s]

[I 2025-11-10 18:34:28,567] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.09795139856737713, 'n_estimators': 232, 'subsample': 0.6674410071785115, 'colsample_bytree': 0.740443486970134, 'min_child_weight': 5, 'gamma': 3.9981638955645487, 'reg_alpha': 0.19762359203251664, 'reg_lambda': 0.00030781560702662706, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:34:28,692] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.09119244893377529, 'n_estimators': 285, 'subsample': 0.7082627147074004, 'colsample_bytree': 0.9068725163560407, 'min_child_weight': 5, 'gamma': 4.986458655494222, 'reg_alpha': 0.13109637611942085, 'reg_lambda': 0.0004824982402961173, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  12%|█▏        | 23/200 [00:23<02:44,  1.08it/s]

[I 2025-11-10 18:34:30,948] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.17172980194946583, 'n_estimators': 549, 'subsample': 0.7196546605355519, 'colsample_bytree': 0.5448232673409016, 'min_child_weight': 8, 'gamma': 0.07328411329974077, 'reg_alpha': 0.719114854757829, 'reg_lambda': 0.631785714043065, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  12%|█▏        | 24/200 [00:23<02:12,  1.33it/s]

[I 2025-11-10 18:34:31,254] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.017943801433680923, 'n_estimators': 659, 'subsample': 0.7041381268615833, 'colsample_bytree': 0.7547017668617094, 'min_child_weight': 6, 'gamma': 3.9065342784889054, 'reg_alpha': 0.0002650953876027185, 'reg_lambda': 9.253649361120338e-07, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  12%|█▎        | 25/200 [00:23<01:50,  1.59it/s]

[I 2025-11-10 18:34:31,575] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.19522620834605953, 'n_estimators': 658, 'subsample': 0.9464184545830105, 'colsample_bytree': 0.578848336691147, 'min_child_weight': 8, 'gamma': 0.047346768384602334, 'reg_alpha': 1.001153225614605, 'reg_lambda': 4.370981903728784, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  13%|█▎        | 26/200 [00:24<01:31,  1.90it/s]

[I 2025-11-10 18:34:31,852] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.09261750885894714, 'n_estimators': 971, 'subsample': 0.7106109519785746, 'colsample_bytree': 0.7374249461314296, 'min_child_weight': 5, 'gamma': 3.9994596986777404, 'reg_alpha': 0.2183384232806548, 'reg_lambda': 9.368512300524637e-07, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  14%|█▍        | 28/200 [00:26<01:59,  1.44it/s]

[I 2025-11-10 18:34:33,753] Trial 29 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.0413881596384892, 'n_estimators': 413, 'subsample': 0.899294871589805, 'colsample_bytree': 0.6195764589632419, 'min_child_weight': 9, 'gamma': 0.5949590366251141, 'reg_alpha': 0.0012670520683890016, 'reg_lambda': 0.4018362944296943, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:34:33,883] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.033167515846657517, 'n_estimators': 632, 'subsample': 0.9402620988559486, 'colsample_bytree': 0.5951267922355421, 'min_child_weight': 8, 'gamma': 0.5430426247274655, 'reg_alpha': 0.00026812406732296427, 'reg_lambda': 6.647561827983172, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  14%|█▍        | 29/200 [00:27<02:47,  1.02it/s]

[I 2025-11-10 18:34:35,549] Trial 27 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03549138792079052, 'n_estimators': 969, 'subsample': 0.935399848781511, 'colsample_bytree': 0.6033578255077034, 'min_child_weight': 8, 'gamma': 0.5512468445576142, 'reg_alpha': 0.00032818666050959413, 'reg_lambda': 7.635846984079455, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  15%|█▌        | 30/200 [00:28<02:13,  1.27it/s]

[I 2025-11-10 18:34:35,875] Trial 28 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03316745372725583, 'n_estimators': 955, 'subsample': 0.8996888283534922, 'colsample_bytree': 0.6150220829104541, 'min_child_weight': 9, 'gamma': 0.5298500176567702, 'reg_alpha': 0.0013395320766628922, 'reg_lambda': 0.25738686551957857, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  16%|█▌        | 31/200 [00:28<01:50,  1.53it/s]

[I 2025-11-10 18:34:36,210] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.1299667985728526, 'n_estimators': 503, 'subsample': 0.9941818156090467, 'colsample_bytree': 0.7808957317760923, 'min_child_weight': 9, 'gamma': 2.154564545528425, 'reg_alpha': 0.04152529359594787, 'reg_lambda': 0.001291727207472975, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  16%|█▌        | 32/200 [00:29<02:07,  1.32it/s]

[I 2025-11-10 18:34:37,213] Trial 32 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.13311185770511338, 'n_estimators': 346, 'subsample': 0.7615507572414816, 'colsample_bytree': 0.8648291976240721, 'min_child_weight': 9, 'gamma': 2.0910432123815, 'reg_alpha': 0.02877910030555362, 'reg_lambda': 8.296747357431966e-05, 'max_delta_step': 9}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  16%|█▋        | 33/200 [00:29<01:51,  1.49it/s]

[I 2025-11-10 18:34:37,678] Trial 33 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.12830624095107473, 'n_estimators': 367, 'subsample': 0.9989978097488568, 'colsample_bytree': 0.86341423416688, 'min_child_weight': 7, 'gamma': 2.0968484837989054, 'reg_alpha': 0.03760785798377371, 'reg_lambda': 0.00011994503603005962, 'max_delta_step': 9}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  17%|█▋        | 34/200 [00:30<01:37,  1.70it/s]

[I 2025-11-10 18:34:38,081] Trial 30 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.13136287918070427, 'n_estimators': 915, 'subsample': 0.9815275488894317, 'colsample_bytree': 0.8448894693551041, 'min_child_weight': 8, 'gamma': 0.7704438092015929, 'reg_alpha': 0.00019136950569650463, 'reg_lambda': 9.403046288246633, 'max_delta_step': 9}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  18%|█▊        | 35/200 [00:31<01:45,  1.57it/s]

[I 2025-11-10 18:34:38,831] Trial 36 pruned.

Best trial: 0. Best value: 0.5:  18%|█▊        | 36/200 [00:33<03:09,  1.16s/it]

[I 2025-11-10 18:34:41,203] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.06245772549089819, 'n_estimators': 1141, 'subsample': 0.7879626600485821, 'colsample_bytree': 0.8433386336035537, 'min_child_weight': 6, 'gamma': 0.9818922774564353, 'reg_alpha': 1.5231986349374105e-07, 'reg_lambda': 1.3180886094215847, 'max_delta_step': 9}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  18%|█▊        | 37/200 [00:34<03:14,  1.20s/it]

[I 2025-11-10 18:34:42,489] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07432122846439682, 'n_estimators': 1176, 'subsample': 0.791594037075282, 'colsample_bytree': 0.8400169956784185, 'min_child_weight': 6, 'gamma': 1.0694802562235908, 'reg_alpha': 3.089147830630741e-08, 'reg_lambda': 1.1245097148988785, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  20%|█▉        | 39/200 [00:35<02:07,  1.26it/s]

[I 2025-11-10 18:34:43,307] Trial 37 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.017688270152188035, 'n_estimators': 1174, 'subsample': 0.8015018285973782, 'colsample_bytree': 0.8276721856713798, 'min_child_weight': 6, 'gamma': 1.666417897286129, 'reg_alpha': 1.244971483823871e-06, 'reg_lambda': 1.0256863622727723, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:34:43,417] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.22146663422075472, 'n_estimators': 1097, 'subsample': 0.837165333943899, 'colsample_bytree': 0.503556011361444, 'min_child_weight': 6, 'gamma': 0.24645773295464352, 'reg_alpha': 1.2154343756357363e-06, 'reg_lambda': 1.232162352497216, 'max_delta_step': 2}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  20%|██        | 40/200 [00:35<01:37,  1.64it/s]

[I 2025-11-10 18:34:43,608] Trial 40 pruned.

Best trial: 0. Best value: 0.5:  20%|██        | 41/200 [00:36<01:32,  1.72it/s]

[I 2025-11-10 18:34:44,115] Trial 41 pruned.

Best trial: 0. Best value: 0.5:  22%|██▏       | 43/200 [00:36<00:55,  2.82it/s]

[I 2025-11-10 18:34:44,296] Trial 42 pruned.
[I 2025-11-10 18:34:44,406] Trial 43 pruned.

Best trial: 0. Best value: 0.5:  22%|██▏       | 44/200 [00:36<00:54,  2.87it/s]

[I 2025-11-10 18:34:44,737] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.2975242624536378, 'n_estimators': 747, 'subsample': 0.8324747765420223, 'colsample_bytree': 0.6782589705733921, 'min_child_weight': 6, 'gamma': 0.2574810601015754, 'reg_alpha': 8.209423493817249e-07, 'reg_lambda': 0.022890949277508975, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  23%|██▎       | 46/200 [00:41<02:40,  1.04s/it]

[I 2025-11-10 18:34:48,710] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.04693992607658763, 'n_estimators': 1055, 'subsample': 0.5815366600431038, 'colsample_bytree': 0.6848915053211535, 'min_child_weight': 7, 'gamma': 3.674313384064064, 'reg_alpha': 4.47433613379656e-05, 'reg_lambda': 3.962029411566948e-07, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:34:48,832] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.04619012411272112, 'n_estimators': 1036, 'subsample': 0.5964651134239293, 'colsample_bytree': 0.663019034041821, 'min_child_weight': 7, 'gamma': 3.6707866282537114, 'reg_alpha': 3.518851244904008e-05, 'reg_lambda': 1.1134303698042772e-07, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  24%|██▎       | 47/200 [00:41<02:11,  1.16it/s]

[I 2025-11-10 18:34:49,276] Trial 47 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1602064308819845, 'n_estimators': 1034, 'subsample': 0.6325970821609478, 'colsample_bytree': 0.8035137713532912, 'min_child_weight': 7, 'gamma': 4.311149763530763, 'reg_alpha': 0.0020537819232261468, 'reg_lambda': 1.722159423217026e-07, 'max_delta_step': 10}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  24%|██▍       | 48/200 [00:42<01:59,  1.27it/s]

[I 2025-11-10 18:34:49,891] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1598750256374954, 'n_estimators': 1258, 'subsample': 0.5731357110547444, 'colsample_bytree': 0.6583930830717082, 'min_child_weight': 7, 'gamma': 4.334597202103065, 'reg_alpha': 2.950392695814361e-05, 'reg_lambda': 4.956652407351554e-07, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  24%|██▍       | 49/200 [00:43<02:30,  1.00it/s]

[I 2025-11-10 18:34:51,369] Trial 51 pruned.

Best trial: 0. Best value: 0.5:  25%|██▌       | 50/200 [00:46<03:52,  1.55s/it]

[I 2025-11-10 18:34:54,225] Trial 48 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05729639222862173, 'n_estimators': 1308, 'subsample': 0.6106786656838347, 'colsample_bytree': 0.6486835403260713, 'min_child_weight': 7, 'gamma': 4.370208574179387, 'reg_alpha': 8.244243561535459e-05, 'reg_lambda': 1.9615387985789284e-07, 'max_delta_step': 10}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  26%|██▌       | 51/200 [00:47<03:15,  1.31s/it]

[I 2025-11-10 18:34:54,983] Trial 49 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05933957841672711, 'n_estimators': 1402, 'subsample': 0.6413051543218377, 'colsample_bytree': 0.7962756757596638, 'min_child_weight': 7, 'gamma': 4.404931839424872, 'reg_alpha': 0.0001060726015092002, 'reg_lambda': 2.0467183671196147e-05, 'max_delta_step': 10}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  26%|██▌       | 52/200 [00:47<02:33,  1.04s/it]

[I 2025-11-10 18:34:55,378] Trial 50 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.109900547108725, 'n_estimators': 1379, 'subsample': 0.675553848607797, 'colsample_bytree': 0.6412048715060568, 'min_child_weight': 7, 'gamma': 4.514424947790225, 'reg_alpha': 0.07991694966738395, 'reg_lambda': 2.586432457670351e-05, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  27%|██▋       | 54/200 [00:48<01:40,  1.45it/s]

[I 2025-11-10 18:34:56,065] Trial 54 pruned.
[I 2025-11-10 18:34:56,191] Trial 52 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.11043983065886426, 'n_estimators': 1103, 'subsample': 0.6851625922637916, 'colsample_bytree': 0.7707209943182025, 'min_child_weight': 10, 'gamma': 4.647337219413906, 'reg_alpha': 0.08038423791814914, 'reg_lambda': 3.445127795827101e-06, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  28%|██▊       | 55/200 [00:52<04:03,  1.68s/it]

[I 2025-11-10 18:35:00,179] Trial 53 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.10923445470744078, 'n_estimators': 1415, 'subsample': 0.6734305777360122, 'colsample_bytree': 0.9196250082637012, 'min_child_weight': 10, 'gamma': 4.670392503083993, 'reg_alpha': 9.081304823579928e-06, 'reg_lambda': 3.309490221086117e-06, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  28%|██▊       | 57/200 [00:53<02:35,  1.09s/it]

[I 2025-11-10 18:35:01,234] Trial 56 finished with value: 0.45555555555555555 and parameters: {'max_depth': 4, 'learning_rate': 0.08011720079831033, 'n_estimators': 1098, 'subsample': 0.7437342957754671, 'colsample_bytree': 0.9195911088661154, 'min_child_weight': 3, 'gamma': 3.173037832982399, 'reg_alpha': 4.719836144796154, 'reg_lambda': 3.447678002073346e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:35:01,379] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2195747609379049, 'n_estimators': 998, 'subsample': 0.9265501031276281, 'colsample_bytree': 0.9221340793152883, 'min_child_weight': 3, 'gamma': 3.3408572773569274, 'reg_alpha': 5.358967652813426, 'reg_lambda': 0.0018770413378496752, 'max_delta_step': 0}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  29%|██▉       | 58/200 [00:53<02:04,  1.14it/s]

[I 2025-11-10 18:35:01,765] Trial 55 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.07908808638270591, 'n_estimators': 1235, 'subsample': 0.9137641101838792, 'colsample_bytree': 0.921423090041002, 'min_child_weight': 3, 'gamma': 3.204474086662666, 'reg_alpha': 9.048958579493723, 'reg_lambda': 2.8075738052814108e-06, 'max_delta_step': 1}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  30%|██▉       | 59/200 [00:54<02:00,  1.17it/s]

[I 2025-11-10 18:35:02,569] Trial 60 pruned.

Best trial: 0. Best value: 0.5:  30%|███       | 60/200 [00:56<02:37,  1.13s/it]

[I 2025-11-10 18:35:04,331] Trial 62 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.013653303792930564, 'n_estimators': 461, 'subsample': 0.8209539817364552, 'colsample_bytree': 0.8115940941190033, 'min_child_weight': 5, 'gamma': 3.827403477524467, 'reg_alpha': 0.011776833817828765, 'reg_lambda': 0.016171064112310743, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:35:04,420] Trial 61 finished with value: 0.3981091617933723 and parameters: {'max_depth': 3, 'learning_rate': 0.18345223897807036, 'n_estimators': 440, 'subsample': 0.8834009155834299, 'colsample_bytree': 0.8686322321514938, 'min_child_weight': 2, 'gamma': 2.4317531425242414, 'reg_alpha': 0.43976004805912505, 'reg_lambda': 0.015388948879412277, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  31%|███       | 62/200 [00:57<01:38,  1.40it/s]

[I 2025-11-10 18:35:04,802] Trial 63 pruned.

Best trial: 0. Best value: 0.5:  32%|███▏      | 63/200 [00:57<01:42,  1.34it/s]

[I 2025-11-10 18:35:05,647] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.14079376795623522, 'n_estimators': 283, 'subsample': 0.9608712742486382, 'colsample_bytree': 0.634019304761677, 'min_child_weight': 8, 'gamma': 4.140037434735295, 'reg_alpha': 4.506313862012734e-06, 'reg_lambda': 0.00017613444261330274, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  32%|███▏      | 64/200 [00:58<01:33,  1.45it/s]

[I 2025-11-10 18:35:06,172] Trial 65 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.15312667934536384, 'n_estimators': 295, 'subsample': 0.7358670805082064, 'colsample_bytree': 0.8881176025872564, 'min_child_weight': 8, 'gamma': 4.1320873105594895, 'reg_alpha': 4.097884961340977e-06, 'reg_lambda': 0.00025479576939656544, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  32%|███▎      | 65/200 [00:58<01:22,  1.63it/s]

[I 2025-11-10 18:35:06,579] Trial 58 finished with value: 0.48888888888888893 and parameters: {'max_depth': 4, 'learning_rate': 0.22171015118515106, 'n_estimators': 1231, 'subsample': 0.9219292606100525, 'colsample_bytree': 0.8101495778601765, 'min_child_weight': 3, 'gamma': 2.3972055034184825, 'reg_alpha': 2.9476520729586975, 'reg_lambda': 3.242600001491122e-08, 'max_delta_step': 0}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  33%|███▎      | 66/200 [00:59<01:30,  1.47it/s]

[I 2025-11-10 18:35:07,423] Trial 66 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1492310727128212, 'n_estimators': 407, 'subsample': 0.7727466816724107, 'colsample_bytree': 0.7265054157705688, 'min_child_weight': 8, 'gamma': 4.076584393679794, 'reg_alpha': 0.0005198386990110985, 'reg_lambda': 0.00038874049957828076, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  34%|███▍      | 68/200 [01:00<01:05,  2.02it/s]

[I 2025-11-10 18:35:07,997] Trial 69 pruned.
[I 2025-11-10 18:35:08,125] Trial 67 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02576287142539912, 'n_estimators': 397, 'subsample': 0.7749570730544713, 'colsample_bytree': 0.9768235843286865, 'min_child_weight': 6, 'gamma': 4.745294358968399, 'reg_alpha': 0.0006083112883436091, 'reg_lambda': 0.0007405741855575436, 'max_delta_step': 9}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  34%|███▍      | 69/200 [01:00<00:54,  2.41it/s]

[I 2025-11-10 18:35:08,337] Trial 68 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.039178697754619796, 'n_estimators': 384, 'subsample': 0.7750413999532076, 'colsample_bytree': 0.5756882183238333, 'min_child_weight': 5, 'gamma': 4.8132937106478275, 'reg_alpha': 0.0007222286431287813, 'reg_lambda': 0.0005610221921700025, 'max_delta_step': 9}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  35%|███▌      | 70/200 [01:01<00:59,  2.17it/s]

[I 2025-11-10 18:35:08,911] Trial 59 finished with value: 0.3887134502923977 and parameters: {'max_depth': 4, 'learning_rate': 0.21052792635869044, 'n_estimators': 1254, 'subsample': 0.9143784648284445, 'colsample_bytree': 0.8122815639952938, 'min_child_weight': 2, 'gamma': 3.4466799146359692, 'reg_alpha': 0.5507661548047157, 'reg_lambda': 0.0014299736406085401, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  36%|███▌      | 71/200 [01:04<02:40,  1.25s/it]

[I 2025-11-10 18:35:12,025] Trial 70 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03695938128106462, 'n_estimators': 933, 'subsample': 0.8613462389177995, 'colsample_bytree': 0.5810131977366255, 'min_child_weight': 6, 'gamma': 3.4521494722858934, 'reg_alpha': 0.0024291591902618295, 'reg_lambda': 4.060961382946489e-05, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  36%|███▌      | 72/200 [01:04<02:07,  1.00it/s]

[I 2025-11-10 18:35:12,431] Trial 71 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.089855374727827, 'n_estimators': 944, 'subsample': 0.807946676410288, 'colsample_bytree': 0.564475512252055, 'min_child_weight': 9, 'gamma': 3.5093104947969165, 'reg_alpha': 0.008660856883682929, 'reg_lambda': 4.461541173541807e-05, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  36%|███▋      | 73/200 [01:04<01:40,  1.26it/s]

[I 2025-11-10 18:35:12,733] Trial 72 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.08981836824878991, 'n_estimators': 936, 'subsample': 0.8169608480563941, 'colsample_bytree': 0.8995008956024698, 'min_child_weight': 9, 'gamma': 3.593950815744907, 'reg_alpha': 0.005470082004827232, 'reg_lambda': 3.76165616824505e-05, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  37%|███▋      | 74/200 [01:05<01:23,  1.51it/s]

[I 2025-11-10 18:35:13,098] Trial 73 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.08485075274366465, 'n_estimators': 947, 'subsample': 0.8090802013180783, 'colsample_bytree': 0.6267346603177536, 'min_child_weight': 9, 'gamma': 0.02000782474585794, 'reg_alpha': 0.01956857918518554, 'reg_lambda': 7.424263243209582e-06, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  38%|███▊      | 75/200 [01:06<01:26,  1.44it/s]

[I 2025-11-10 18:35:13,871] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.011823158246420537, 'n_estimators': 278, 'subsample': 0.9844542852225902, 'colsample_bytree': 0.6245868849985465, 'min_child_weight': 10, 'gamma': 0.053525788642218686, 'reg_alpha': 1.9198032284472077, 'reg_lambda': 0.04543793259817722, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:35:13,960] Trial 76 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.013090493593494413, 'n_estimators': 230, 'subsample': 0.9872106960184444, 'colsample_bytree': 0.5413913954089752, 'min_child_weight': 10, 'gamma': 0.0853405086359843, 'reg_alpha': 0.017345520273500822, 'reg_lambda': 0.039256555605547146, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  38%|███▊      | 77/200 [01:06<00:55,  2.21it/s]

[I 2025-11-10 18:35:14,201] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.011774881199826486, 'n_estimators': 200, 'subsample': 0.979089086857322, 'colsample_bytree': 0.5448655475083475, 'min_child_weight': 10, 'gamma': 0.4446528453912266, 'reg_alpha': 0.1989734813464205, 'reg_lambda': 0.0036536558723278714, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  39%|███▉      | 78/200 [01:09<02:07,  1.04s/it]

[I 2025-11-10 18:35:17,043] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.011463167311038759, 'n_estimators': 1128, 'subsample': 0.9829019373525935, 'colsample_bytree': 0.6271738306556685, 'min_child_weight': 9, 'gamma': 0.7424067942805825, 'reg_alpha': 1.1899943062440124, 'reg_lambda': 0.05221545060697006, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  40%|███▉      | 79/200 [01:10<02:04,  1.03s/it]

[I 2025-11-10 18:35:18,044] Trial 80 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.015819356787347312, 'n_estimators': 848, 'subsample': 0.9440130169256069, 'colsample_bytree': 0.7430009120701302, 'min_child_weight': 7, 'gamma': 0.6792333988800787, 'reg_alpha': 1.7756028795588841e-06, 'reg_lambda': 0.329370051171106, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  40%|████      | 80/200 [01:11<01:57,  1.02it/s]

[I 2025-11-10 18:35:18,877] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.013874348445013757, 'n_estimators': 1150, 'subsample': 0.9440762324248172, 'colsample_bytree': 0.6036923890270691, 'min_child_weight': 10, 'gamma': 0.7409689973450533, 'reg_alpha': 0.14020171507242193, 'reg_lambda': 2.3863536583152083, 'max_delta_step': 2}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  40%|████      | 81/200 [01:11<01:32,  1.29it/s]

[I 2025-11-10 18:35:19,143] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.06862278830860263, 'n_estimators': 1148, 'subsample': 0.9483383280514712, 'colsample_bytree': 0.8531817312807747, 'min_child_weight': 7, 'gamma': 3.8691905117731507, 'reg_alpha': 0.17701681282378467, 'reg_lambda': 0.004017509304525813, 'max_delta_step': 2}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  41%|████      | 82/200 [01:11<01:23,  1.41it/s]

[I 2025-11-10 18:35:19,679] Trial 82 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.02279494463329876, 'n_estimators': 329, 'subsample': 0.9539058020669742, 'colsample_bytree': 0.6021177933221205, 'min_child_weight': 8, 'gamma': 1.285609149167618, 'reg_alpha': 0.00018038490625300416, 'reg_lambda': 2.5449393008580357, 'max_delta_step': 2}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  42%|████▏     | 83/200 [01:13<02:02,  1.05s/it]

[I 2025-11-10 18:35:21,548] Trial 81 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.015040969884158734, 'n_estimators': 1008, 'subsample': 0.948533037224567, 'colsample_bytree': 0.6028031520016243, 'min_child_weight': 8, 'gamma': 1.2358479389528594, 'reg_alpha': 4.743840292529362e-07, 'reg_lambda': 2.8288355740006312, 'max_delta_step': 2}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  42%|████▏     | 84/200 [01:13<01:32,  1.26it/s]

[I 2025-11-10 18:35:21,735] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.06882979845523342, 'n_estimators': 572, 'subsample': 0.9609702869221924, 'colsample_bytree': 0.8555686089257096, 'min_child_weight': 6, 'gamma': 1.2839822268505694, 'reg_alpha': 8.01501475512481e-06, 'reg_lambda': 9.746833243218584e-06, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  42%|████▎     | 85/200 [01:14<01:31,  1.25it/s]

[I 2025-11-10 18:35:22,543] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.010229403416936029, 'n_estimators': 604, 'subsample': 0.5230306935681502, 'colsample_bytree': 0.938494001286382, 'min_child_weight': 9, 'gamma': 2.9806926706596446, 'reg_alpha': 9.791309206229097e-06, 'reg_lambda': 9.419691035986344e-05, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  43%|████▎     | 86/200 [01:15<01:37,  1.17it/s]

[I 2025-11-10 18:35:23,525] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01057838189964266, 'n_estimators': 994, 'subsample': 0.5298850817719705, 'colsample_bytree': 0.665998697945642, 'min_child_weight': 8, 'gamma': 2.7065406630984397, 'reg_alpha': 4.6042917558067007e-07, 'reg_lambda': 0.007073070378042557, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  44%|████▎     | 87/200 [01:16<01:33,  1.21it/s]

[I 2025-11-10 18:35:24,299] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.010041515824134485, 'n_estimators': 571, 'subsample': 0.515402912937929, 'colsample_bytree': 0.9437236596233414, 'min_child_weight': 9, 'gamma': 2.965714854699601, 'reg_alpha': 9.033089276283838e-06, 'reg_lambda': 0.007307447934995943, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  44%|████▍     | 88/200 [01:17<01:22,  1.36it/s]

[I 2025-11-10 18:35:24,814] Trial 88 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.12072659516105434, 'n_estimators': 503, 'subsample': 0.5654650104972437, 'colsample_bytree': 0.6680798064564277, 'min_child_weight': 9, 'gamma': 1.8934119408501373, 'reg_alpha': 0.04773075178375598, 'reg_lambda': 0.0086348884881184, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  44%|████▍     | 89/200 [01:18<01:57,  1.05s/it]

[I 2025-11-10 18:35:26,613] Trial 87 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.010176416370954181, 'n_estimators': 1069, 'subsample': 0.5093404946212435, 'colsample_bytree': 0.9537841975533765, 'min_child_weight': 9, 'gamma': 2.9331062287240584, 'reg_alpha': 1.4871177740153278e-05, 'reg_lambda': 0.006717652523384563, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  45%|████▌     | 90/200 [01:20<02:12,  1.21s/it]

[I 2025-11-10 18:35:28,185] Trial 89 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.17328137252136688, 'n_estimators': 1057, 'subsample': 0.7285146103639298, 'colsample_bytree': 0.9660798634212241, 'min_child_weight': 10, 'gamma': 3.0417450035602642, 'reg_alpha': 0.003470223289690526, 'reg_lambda': 0.0009224466615654691, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  46%|████▌     | 91/200 [01:21<02:01,  1.12s/it]

[I 2025-11-10 18:35:29,094] Trial 90 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.11802405040035757, 'n_estimators': 1067, 'subsample': 0.5540759009206945, 'colsample_bytree': 0.9597429039358586, 'min_child_weight': 10, 'gamma': 2.3017760336953246, 'reg_alpha': 9.635518852754043, 'reg_lambda': 0.0008954217338418111, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  46%|████▌     | 92/200 [01:21<01:36,  1.11it/s]

[I 2025-11-10 18:35:29,472] Trial 91 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.05335265647033065, 'n_estimators': 1051, 'subsample': 0.5518208768302975, 'colsample_bytree': 0.9643739701752454, 'min_child_weight': 10, 'gamma': 0.18668877469840311, 'reg_alpha': 0.004985489807271658, 'reg_lambda': 0.18483029661908135, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  46%|████▋     | 93/200 [01:24<02:31,  1.41s/it]

[I 2025-11-10 18:35:32,087] Trial 92 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.05108394878376158, 'n_estimators': 1295, 'subsample': 0.7028345314856096, 'colsample_bytree': 0.6973713981422343, 'min_child_weight': 10, 'gamma': 3.7291577737347055, 'reg_alpha': 7.83136383985104, 'reg_lambda': 0.5405743689686828, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  47%|████▋     | 94/200 [01:26<02:59,  1.69s/it]

[I 2025-11-10 18:35:34,435] Trial 93 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.031052350256140896, 'n_estimators': 1471, 'subsample': 0.6959438922394356, 'colsample_bytree': 0.8778536392247003, 'min_child_weight': 7, 'gamma': 2.2681265572321028, 'reg_alpha': 1.4108822458221426, 'reg_lambda': 0.6571152887350246, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  48%|████▊     | 95/200 [01:27<02:32,  1.45s/it]

[I 2025-11-10 18:35:35,315] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.020936711481748638, 'n_estimators': 1469, 'subsample': 0.5532441948739867, 'colsample_bytree': 0.8822567527920219, 'min_child_weight': 10, 'gamma': 2.615342949030579, 'reg_alpha': 0.006869739771960911, 'reg_lambda': 0.13815392838437066, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:35:35,409] Trial 96 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.020723127221927446, 'n_estimators': 702, 'subsample': 0.5466372281487861, 'colsample_bytree': 0.9886255557895085, 'min_child_weight': 4, 'gamma': 2.783202061287569, 'reg_alpha': 0.025661898116376647, 'reg_lambda': 0.023240812233319627, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  48%|████▊     | 97/200 [01:27<01:31,  1.13it/s]

[I 2025-11-10 18:35:35,786] Trial 95 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01663123830281688, 'n_estimators': 1441, 'subsample': 0.6992866541773062, 'colsample_bytree': 0.9885130129746199, 'min_child_weight': 10, 'gamma': 0.45094749326468114, 'reg_alpha': 0.026184641409286835, 'reg_lambda': 0.0026204168566035893, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  50%|████▉     | 99/200 [01:32<02:20,  1.39s/it]

[I 2025-11-10 18:35:40,517] Trial 99 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2412203124334553, 'n_estimators': 1182, 'subsample': 0.6239745110861818, 'colsample_bytree': 0.9028460410467639, 'min_child_weight': 8, 'gamma': 3.29939941360805, 'reg_alpha': 0.0013661379541513525, 'reg_lambda': 0.002258271013157343, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:35:40,642] Trial 97 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.020625315570902202, 'n_estimators': 1448, 'subsample': 0.5431666263547144, 'colsample_bytree': 0.7812209794825326, 'min_child_weight': 10, 'gamma': 2.783454388037796, 'reg_alpha': 0.022741233351996896, 'reg_lambda': 0.0028056849790742515, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  50%|█████     | 101/200 [01:33<01:23,  1.19it/s]

[I 2025-11-10 18:35:40,963] Trial 98 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.011270038265668955, 'n_estimators': 1210, 'subsample': 0.5402801618040236, 'colsample_bytree': 0.980619703501476, 'min_child_weight': 4, 'gamma': 3.3291095613183725, 'reg_alpha': 0.013568504164376499, 'reg_lambda': 0.015333926655085003, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:35:41,126] Trial 100 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.01277788119060963, 'n_estimators': 1202, 'subsample': 0.6203228820856915, 'colsample_bytree': 0.9094637136921099, 'min_child_weight': 6, 'gamma': 3.312023820933585, 'reg_alpha': 0.0011454499531542762, 'reg_lambda': 0.00022472130559820537, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  51%|█████     | 102/200 [01:33<01:13,  1.34it/s]

[I 2025-11-10 18:35:41,643] Trial 104 pruned.

Best trial: 0. Best value: 0.5:  52%|█████▏    | 104/200 [01:38<02:03,  1.29s/it]

[I 2025-11-10 18:35:45,933] Trial 101 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.012771658112974042, 'n_estimators': 1207, 'subsample': 0.9344713679259615, 'colsample_bytree': 0.833164868548919, 'min_child_weight': 6, 'gamma': 4.242867127423341, 'reg_alpha': 1.1615521459405988e-08, 'reg_lambda': 0.0002008884093854442, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:35:46,051] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.012090476199979197, 'n_estimators': 1209, 'subsample': 0.902980830391127, 'colsample_bytree': 0.8324233152138623, 'min_child_weight': 6, 'gamma': 4.2549624804390245, 'reg_alpha': 3.7400726941146565, 'reg_lambda': 0.013071143265658738, 'max_delta_step': 10}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  52%|█████▎    | 105/200 [01:38<01:42,  1.08s/it]

[I 2025-11-10 18:35:46,615] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.012823523265321064, 'n_estimators': 1358, 'subsample': 0.7605899046961165, 'colsample_bytree': 0.5171047360630515, 'min_child_weight': 6, 'gamma': 0.8651166619416041, 'reg_alpha': 0.05179254162937691, 'reg_lambda': 0.00024271985366624868, 'max_delta_step': 10}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  53%|█████▎    | 106/200 [01:39<01:33,  1.00it/s]

[I 2025-11-10 18:35:47,429] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01241366308751852, 'n_estimators': 1288, 'subsample': 0.9994467703393006, 'colsample_bytree': 0.9348387161268477, 'min_child_weight': 9, 'gamma': 2.5784538361499676, 'reg_alpha': 0.009356041546302755, 'reg_lambda': 0.0012895546757815909, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  54%|█████▍    | 108/200 [01:44<02:15,  1.47s/it]

[I 2025-11-10 18:35:51,926] Trial 107 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.10127581248791122, 'n_estimators': 1363, 'subsample': 0.5009967080250665, 'colsample_bytree': 0.9281572466401574, 'min_child_weight': 9, 'gamma': 0.36394519900578887, 'reg_alpha': 5.0432761100841294e-05, 'reg_lambda': 0.030419929641781817, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:35:52,053] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.09890439427937253, 'n_estimators': 1354, 'subsample': 0.6556462379953596, 'colsample_bytree': 0.9298996268145067, 'min_child_weight': 10, 'gamma': 2.527016405229463, 'reg_alpha': 3.969627143091165, 'reg_lambda': 0.027660240424130157, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  55%|█████▍    | 109/200 [01:44<01:37,  1.07s/it]

[I 2025-11-10 18:35:52,183] Trial 108 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.010940038174424788, 'n_estimators': 1278, 'subsample': 0.6588122440588767, 'colsample_bytree': 0.9476324832509795, 'min_child_weight': 9, 'gamma': 3.9991708529502876, 'reg_alpha': 0.010276970721923387, 'reg_lambda': 0.0753286747849301, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  55%|█████▌    | 110/200 [01:45<01:36,  1.07s/it]

[I 2025-11-10 18:35:53,271] Trial 109 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.011120119427123397, 'n_estimators': 1332, 'subsample': 0.5003381214994784, 'colsample_bytree': 0.9267052829299299, 'min_child_weight': 10, 'gamma': 4.5278423382333886, 'reg_alpha': 5.003498300148965e-05, 'reg_lambda': 0.06653270872111036, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  56%|█████▌    | 111/200 [01:45<01:18,  1.13it/s]

[I 2025-11-10 18:35:53,714] Trial 110 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.010928647392519268, 'n_estimators': 354, 'subsample': 0.6584551852987182, 'colsample_bytree': 0.6498727696399746, 'min_child_weight': 10, 'gamma': 3.96256185921616, 'reg_alpha': 0.002284316180192184, 'reg_lambda': 7.494609982401789, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  56%|█████▌    | 112/200 [01:49<02:41,  1.83s/it]

[I 2025-11-10 18:35:57,762] Trial 112 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.13660541025328393, 'n_estimators': 1316, 'subsample': 0.586912503708034, 'colsample_bytree': 0.6473105871341863, 'min_child_weight': 7, 'gamma': 3.7604147269877566, 'reg_alpha': 0.002948222197724148, 'reg_lambda': 1.0230271214405317e-06, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:35:57,776] Trial 111 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.13550269880215646, 'n_estimators': 1323, 'subsample': 0.5814294601982947, 'colsample_bytree': 0.7197499867499202, 'min_child_weight': 7, 'gamma': 3.9706220210071472, 'reg_alpha': 0.0030948616762898518, 'reg_lambda': 5.0156876773537435, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  57%|█████▋    | 114/200 [01:50<01:42,  1.20s/it]

[I 2025-11-10 18:35:58,665] Trial 116 pruned.

Best trial: 0. Best value: 0.5:  57%|█████▊    | 115/200 [01:51<01:23,  1.02it/s]

[I 2025-11-10 18:35:58,985] Trial 114 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.14136664294436468, 'n_estimators': 1120, 'subsample': 0.5331173396164668, 'colsample_bytree': 0.9697177963352511, 'min_child_weight': 10, 'gamma': 1.0882164002141075, 'reg_alpha': 0.0032023599851767723, 'reg_lambda': 7.956063497497657e-07, 'max_delta_step': 9}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  58%|█████▊    | 116/200 [01:51<01:10,  1.20it/s]

[I 2025-11-10 18:35:59,417] Trial 113 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.14376343123968727, 'n_estimators': 1399, 'subsample': 0.5893216929321815, 'colsample_bytree': 0.7156995015401508, 'min_child_weight': 7, 'gamma': 3.763438334515776, 'reg_alpha': 2.23385289562378e-06, 'reg_lambda': 5.124028648899338, 'max_delta_step': 9}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  58%|█████▊    | 117/200 [01:52<01:11,  1.15it/s]

[I 2025-11-10 18:36:00,362] Trial 118 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.043618062489373624, 'n_estimators': 264, 'subsample': 0.9695476033855635, 'colsample_bytree': 0.952563689969853, 'min_child_weight': 10, 'gamma': 0.1444557976466669, 'reg_alpha': 0.8034718128981758, 'reg_lambda': 0.0004922568005405135, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  59%|█████▉    | 118/200 [01:54<01:43,  1.27s/it]

[I 2025-11-10 18:36:02,666] Trial 117 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.16231174168836948, 'n_estimators': 886, 'subsample': 0.7867110848983397, 'colsample_bytree': 0.976396265065688, 'min_child_weight': 10, 'gamma': 0.21132949900654988, 'reg_alpha': 0.864222973535869, 'reg_lambda': 6.276618123735171e-05, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  60%|█████▉    | 119/200 [01:55<01:18,  1.03it/s]

[I 2025-11-10 18:36:02,881] Trial 115 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.17793693743420744, 'n_estimators': 1102, 'subsample': 0.5289396733176503, 'colsample_bytree': 0.9730872649195089, 'min_child_weight': 10, 'gamma': 1.5438287882848551, 'reg_alpha': 0.006865649928400385, 'reg_lambda': 0.000517491646926542, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  60%|██████    | 121/200 [01:57<01:12,  1.09it/s]

[I 2025-11-10 18:36:04,829] Trial 120 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.16098766181787993, 'n_estimators': 976, 'subsample': 0.8512067468142052, 'colsample_bytree': 0.9782340493248133, 'min_child_weight': 8, 'gamma': 4.93085915712354, 'reg_alpha': 0.015114146148719029, 'reg_lambda': 0.0014602335870745188, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:36:04,941] Trial 121 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.06532814041050689, 'n_estimators': 478, 'subsample': 0.5132754649330827, 'colsample_bytree': 0.9111444629517641, 'min_child_weight': 8, 'gamma': 3.1236021517333454, 'reg_alpha': 0.015002753333933201, 'reg_lambda': 7.2783474280633e-08, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  61%|██████    | 122/200 [01:58<01:17,  1.00it/s]

[I 2025-11-10 18:36:06,138] Trial 119 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.043098201500707825, 'n_estimators': 1491, 'subsample': 0.561340242074927, 'colsample_bytree': 0.9547425903995417, 'min_child_weight': 10, 'gamma': 3.084377498789419, 'reg_alpha': 0.09405326383784718, 'reg_lambda': 0.0006056904297341118, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  62%|██████▏   | 123/200 [01:58<01:02,  1.22it/s]

[I 2025-11-10 18:36:06,518] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.0758486603031408, 'n_estimators': 321, 'subsample': 0.5687155257613223, 'colsample_bytree': 0.8894084959384757, 'min_child_weight': 5, 'gamma': 4.506885890572981, 'reg_alpha': 0.2796263811464811, 'reg_lambda': 0.011398003056086254, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  62%|██████▏   | 124/200 [01:59<00:59,  1.28it/s]

[I 2025-11-10 18:36:07,213] Trial 123 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.014738919019619741, 'n_estimators': 495, 'subsample': 0.7197905216329216, 'colsample_bytree': 0.758199805850002, 'min_child_weight': 5, 'gamma': 3.596826863573455, 'reg_alpha': 2.057153516121444e-05, 'reg_lambda': 0.01300503685448415, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:36:07,257] Trial 122 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.018381472251556556, 'n_estimators': 979, 'subsample': 0.5637371848214376, 'colsample_bytree': 0.7578773127305569, 'min_child_weight': 8, 'gamma': 2.70098852866814, 'reg_alpha': 2.3686536608892537e-05, 'reg_lambda': 0.010173976386560108, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  63%|██████▎   | 126/200 [01:59<00:37,  1.97it/s]

[I 2025-11-10 18:36:07,590] Trial 125 finished with value: 0.4955555555555556 and parameters: {'max_depth': 10, 'learning_rate': 0.07413846785538729, 'n_estimators': 249, 'subsample': 0.8705271352634306, 'colsample_bytree': 0.8938478305709981, 'min_child_weight': 5, 'gamma': 4.798487205118987, 'reg_alpha': 2.0801297251150692e-05, 'reg_lambda': 0.003653385083215857, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  64%|██████▍   | 128/200 [02:00<00:33,  2.15it/s]

[I 2025-11-10 18:36:08,336] Trial 127 finished with value: 0.4955555555555556 and parameters: {'max_depth': 10, 'learning_rate': 0.12057855810381564, 'n_estimators': 203, 'subsample': 0.8721433705920753, 'colsample_bytree': 0.9080085319897881, 'min_child_weight': 5, 'gamma': 4.776633905999123, 'reg_alpha': 0.13861644662728503, 'reg_lambda': 0.0028674668449371497, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:36:08,508] Trial 126 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.057561629066731505, 'n_estimators': 386, 'subsample': 0.7513454662949968, 'colsample_bytree': 0.7594904765077052, 'min_child_weight': 9, 'gamma': 0.3391200454936747, 'reg_alpha': 0.03470969872148618, 'reg_lambda': 0.00012852742096076985, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  64%|██████▍   | 128/200 [02:00<00:33,  2.15it/s]

[I 2025-11-10 18:36:08,597] Trial 128 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05602645943913122, 'n_estimators': 231, 'subsample': 0.7520768945325579, 'colsample_bytree': 0.8734196840476576, 'min_child_weight': 5, 'gamma': 4.867821708119631, 'reg_alpha': 0.136922039896258, 'reg_lambda': 0.003703472037861033, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  65%|██████▌   | 130/200 [02:01<00:29,  2.34it/s]

[I 2025-11-10 18:36:09,262] Trial 130 pruned.

Best trial: 0. Best value: 0.5:  66%|██████▌   | 132/200 [02:01<00:22,  3.02it/s]

[I 2025-11-10 18:36:09,549] Trial 129 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.05894744760907488, 'n_estimators': 367, 'subsample': 0.5984709730073536, 'colsample_bytree': 0.8725044901870508, 'min_child_weight': 9, 'gamma': 0.32761290020549183, 'reg_alpha': 0.033920538531720786, 'reg_lambda': 0.00015357842608779772, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:36:09,692] Trial 131 pruned.

Best trial: 0. Best value: 0.5:  66%|██████▋   | 133/200 [02:02<00:23,  2.81it/s]

[I 2025-11-10 18:36:10,119] Trial 132 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.013734095169213204, 'n_estimators': 294, 'subsample': 0.7847209566979103, 'colsample_bytree': 0.9437177695889415, 'min_child_weight': 9, 'gamma': 0.5300580026890316, 'reg_alpha': 0.00018276997095374733, 'reg_lambda': 5.317623327367786e-06, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  67%|██████▋   | 134/200 [02:03<00:30,  2.18it/s]

[I 2025-11-10 18:36:10,847] Trial 133 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04918340127851858, 'n_estimators': 305, 'subsample': 0.6099389545960373, 'colsample_bytree': 0.8622864363053725, 'min_child_weight': 9, 'gamma': 2.8372419496162213, 'reg_alpha': 0.06398293506101638, 'reg_lambda': 0.0009937915265551607, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  68%|██████▊   | 135/200 [02:03<00:25,  2.54it/s]

[I 2025-11-10 18:36:11,076] Trial 134 finished with value: 0.44168615984405457 and parameters: {'max_depth': 8, 'learning_rate': 0.09166611950240301, 'n_estimators': 290, 'subsample': 0.7092838415776205, 'colsample_bytree': 0.7299314391121273, 'min_child_weight': 4, 'gamma': 4.681070062245612, 'reg_alpha': 0.38806539754159913, 'reg_lambda': 2.1166320298634647e-07, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  68%|██████▊   | 136/200 [02:03<00:22,  2.87it/s]

[I 2025-11-10 18:36:11,314] Trial 135 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.06416733877676038, 'n_estimators': 307, 'subsample': 0.7156941228445111, 'colsample_bytree': 0.8611204866650393, 'min_child_weight': 5, 'gamma': 4.624099656243278, 'reg_alpha': 0.06353521374771803, 'reg_lambda': 2.53584084380863e-07, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  68%|██████▊   | 137/200 [02:07<01:19,  1.26s/it]

[I 2025-11-10 18:36:14,808] Trial 136 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.09211811060726252, 'n_estimators': 1017, 'subsample': 0.8336530831041546, 'colsample_bytree': 0.998127755466265, 'min_child_weight': 5, 'gamma': 4.962585381115659, 'reg_alpha': 0.32824749513651835, 'reg_lambda': 2.0664764783512735e-07, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  69%|██████▉   | 138/200 [02:07<01:04,  1.04s/it]

[I 2025-11-10 18:36:15,303] Trial 137 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.08584147256658246, 'n_estimators': 1017, 'subsample': 0.7381404522151109, 'colsample_bytree': 0.6778562963808878, 'min_child_weight': 5, 'gamma': 4.10686252922336, 'reg_alpha': 0.3253957342990799, 'reg_lambda': 4.681458475404009e-07, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  70%|██████▉   | 139/200 [02:08<00:53,  1.14it/s]

[I 2025-11-10 18:36:15,800] Trial 138 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.08258110869656472, 'n_estimators': 1025, 'subsample': 0.715876723443637, 'colsample_bytree': 0.9995620817250991, 'min_child_weight': 5, 'gamma': 4.9654812837127675, 'reg_alpha': 0.0015550632966698764, 'reg_lambda': 7.332618108280733e-07, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  70%|███████   | 140/200 [02:08<00:42,  1.42it/s]

[I 2025-11-10 18:36:16,092] Trial 139 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01706902603109366, 'n_estimators': 1017, 'subsample': 0.7350447671802267, 'colsample_bytree': 0.9997262129556332, 'min_child_weight': 6, 'gamma': 4.17364821169023, 'reg_alpha': 5.481415099533001, 'reg_lambda': 1.270863522065736e-06, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  70%|███████   | 141/200 [02:11<01:20,  1.36s/it]

[I 2025-11-10 18:36:18,998] Trial 140 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.010011272604252185, 'n_estimators': 923, 'subsample': 0.990832637192109, 'colsample_bytree': 0.8019987466240107, 'min_child_weight': 6, 'gamma': 4.064674639408738, 'reg_alpha': 0.00011635687738283874, 'reg_lambda': 1.5048030586908408e-05, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  71%|███████   | 142/200 [02:12<01:14,  1.28s/it]

[I 2025-11-10 18:36:20,088] Trial 143 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.11058702117214432, 'n_estimators': 910, 'subsample': 0.6877971101827989, 'colsample_bytree': 0.7742285824198998, 'min_child_weight': 10, 'gamma': 3.52342219193083, 'reg_alpha': 0.21967157594259615, 'reg_lambda': 1.855913788330176e-06, 'max_delta_step': 2}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  72%|███████▏  | 143/200 [02:12<00:55,  1.02it/s]

[I 2025-11-10 18:36:20,367] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.10397480838463999, 'n_estimators': 1160, 'subsample': 0.6415768320320765, 'colsample_bytree': 0.6146601040226056, 'min_child_weight': 10, 'gamma': 3.483071458819886, 'reg_alpha': 5.827001466689653, 'reg_lambda': 1.2040099597859873e-06, 'max_delta_step': 2}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  72%|███████▏  | 144/200 [02:13<00:46,  1.21it/s]

[I 2025-11-10 18:36:20,825] Trial 142 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.010086209090492517, 'n_estimators': 1073, 'subsample': 0.797727849519156, 'colsample_bytree': 0.784876468538654, 'min_child_weight': 6, 'gamma': 3.442188695488054, 'reg_alpha': 0.008505738374399822, 'reg_lambda': 0.005255319887817785, 'max_delta_step': 2}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  72%|███████▎  | 145/200 [02:13<00:39,  1.41it/s]

[I 2025-11-10 18:36:21,270] Trial 145 pruned.

Best trial: 0. Best value: 0.5:  73%|███████▎  | 146/200 [02:14<00:40,  1.34it/s]

[I 2025-11-10 18:36:22,098] Trial 147 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1486785324278722, 'n_estimators': 255, 'subsample': 0.674019292625875, 'colsample_bytree': 0.7335477276453074, 'min_child_weight': 5, 'gamma': 2.3327895941186716, 'reg_alpha': 0.020218179525324932, 'reg_lambda': 0.00040185668170877734, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  74%|███████▎  | 147/200 [02:14<00:33,  1.60it/s]

[I 2025-11-10 18:36:22,445] Trial 148 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.14924731957228024, 'n_estimators': 222, 'subsample': 0.6754857698484191, 'colsample_bytree': 0.7107622962782536, 'min_child_weight': 7, 'gamma': 3.819701433646789, 'reg_alpha': 1.382429117928591, 'reg_lambda': 6.132081391542446e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  74%|███████▍  | 148/200 [02:15<00:35,  1.45it/s]

[I 2025-11-10 18:36:23,284] Trial 149 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.124491269748423, 'n_estimators': 227, 'subsample': 0.9076016024883623, 'colsample_bytree': 0.7412764645397013, 'min_child_weight': 10, 'gamma': 2.687182101119447, 'reg_alpha': 0.10497806638884266, 'reg_lambda': 0.019484983501771184, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  74%|███████▍  | 149/200 [02:16<00:34,  1.48it/s]

[I 2025-11-10 18:36:23,934] Trial 151 pruned.

Best trial: 0. Best value: 0.5:  75%|███████▌  | 150/200 [02:16<00:26,  1.88it/s]

[I 2025-11-10 18:36:24,129] Trial 144 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.1080256156844464, 'n_estimators': 1082, 'subsample': 0.6745224973022171, 'colsample_bytree': 0.7773831063805912, 'min_child_weight': 10, 'gamma': 3.8706572696420642, 'reg_alpha': 0.18341931811813778, 'reg_lambda': 1.7320382741010955e-06, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  76%|███████▌  | 151/200 [02:16<00:24,  1.97it/s]

[I 2025-11-10 18:36:24,574] Trial 146 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.12722431285815444, 'n_estimators': 858, 'subsample': 0.7652351054780401, 'colsample_bytree': 0.7344096420613964, 'min_child_weight': 5, 'gamma': 3.876561404903738, 'reg_alpha': 0.008821284191617495, 'reg_lambda': 5.289328073688863e-08, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  76%|███████▌  | 152/200 [02:17<00:32,  1.49it/s]

[I 2025-11-10 18:36:25,621] Trial 152 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.026921012271649544, 'n_estimators': 344, 'subsample': 0.5087391130880501, 'colsample_bytree': 0.5572225343478185, 'min_child_weight': 10, 'gamma': 4.437468426878521, 'reg_alpha': 0.5464181806052636, 'reg_lambda': 0.0012739137434988692, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  76%|███████▋  | 153/200 [02:18<00:25,  1.87it/s]

[I 2025-11-10 18:36:25,838] Trial 153 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.011505337872955426, 'n_estimators': 341, 'subsample': 0.5065698851370589, 'colsample_bytree': 0.5527634602904421, 'min_child_weight': 10, 'gamma': 3.6188096452613556, 'reg_alpha': 0.6689343132929476, 'reg_lambda': 0.006423866438660025, 'max_delta_step': 9}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  77%|███████▋  | 154/200 [02:18<00:24,  1.85it/s]

[I 2025-11-10 18:36:26,402] Trial 154 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.02681755367378888, 'n_estimators': 346, 'subsample': 0.5364820356803036, 'colsample_bytree': 0.7905048034075159, 'min_child_weight': 6, 'gamma': 4.409035196440877, 'reg_alpha': 0.0003852553796876544, 'reg_lambda': 9.996150139719553e-08, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:36:26,424] Trial 150 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.12416201469332093, 'n_estimators': 848, 'subsample': 0.7692662356132813, 'colsample_bytree': 0.562924648266604, 'min_child_weight': 10, 'gamma': 2.676153637470222, 'reg_alpha': 0.00039413900038035244, 'reg_lambda': 0.0003040409437774496, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  78%|███████▊  | 156/200 [02:20<00:28,  1.57it/s]

[I 2025-11-10 18:36:27,893] Trial 156 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.016134880627470347, 'n_estimators': 431, 'subsample': 0.6859615986128047, 'colsample_bytree': 0.7467368156112222, 'min_child_weight': 6, 'gamma': 4.030919998923304, 'reg_alpha': 0.005978103436553415, 'reg_lambda': 3.370662162918309e-06, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  78%|███████▊  | 157/200 [02:20<00:24,  1.73it/s]

[I 2025-11-10 18:36:28,293] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.185832593894895, 'n_estimators': 526, 'subsample': 0.7256592036362781, 'colsample_bytree': 0.6609534466210746, 'min_child_weight': 6, 'gamma': 3.666331895666661, 'reg_alpha': 1.0882331165059126e-05, 'reg_lambda': 0.0003434116597313672, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:36:28,314] Trial 159 pruned.

Best trial: 0. Best value: 0.5:  80%|███████▉  | 159/200 [02:21<00:22,  1.83it/s]

[I 2025-11-10 18:36:29,294] Trial 157 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03243854115374986, 'n_estimators': 613, 'subsample': 0.6899063774054849, 'colsample_bytree': 0.7065956635439619, 'min_child_weight': 6, 'gamma': 4.26424366233075, 'reg_alpha': 0.004592892681686629, 'reg_lambda': 0.0003254308922291803, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  80%|████████  | 160/200 [02:23<00:33,  1.19it/s]

[I 2025-11-10 18:36:31,140] Trial 161 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.01996103992561337, 'n_estimators': 608, 'subsample': 0.7067311877810258, 'colsample_bytree': 0.8243691679451104, 'min_child_weight': 7, 'gamma': 1.984495790628281, 'reg_alpha': 0.0008723434188532178, 'reg_lambda': 1.14191175053393e-08, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  80%|████████  | 161/200 [02:23<00:30,  1.27it/s]

[I 2025-11-10 18:36:31,748] Trial 158 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.02196623738214924, 'n_estimators': 1131, 'subsample': 0.520321678211146, 'colsample_bytree': 0.8132747655430969, 'min_child_weight': 6, 'gamma': 1.4870841534756831, 'reg_alpha': 0.0008114644676827012, 'reg_lambda': 3.770037771741005e-07, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  81%|████████  | 162/200 [02:24<00:27,  1.37it/s]

[I 2025-11-10 18:36:32,316] Trial 162 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.010844742321457466, 'n_estimators': 669, 'subsample': 0.5223923891037718, 'colsample_bytree': 0.818471696065429, 'min_child_weight': 7, 'gamma': 0.0060692461429186495, 'reg_alpha': 7.783788049872046e-05, 'reg_lambda': 6.515223206185876e-06, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  82%|████████▏ | 163/200 [02:25<00:29,  1.24it/s]

[I 2025-11-10 18:36:33,326] Trial 160 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.16875127542333845, 'n_estimators': 1122, 'subsample': 0.5221085119186765, 'colsample_bytree': 0.8168810470522762, 'min_child_weight': 7, 'gamma': 4.319851774014083, 'reg_alpha': 0.003912265235748929, 'reg_lambda': 7.86106027196825e-05, 'max_delta_step': 9}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  82%|████████▏ | 164/200 [02:26<00:30,  1.20it/s]

[I 2025-11-10 18:36:34,241] Trial 163 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.011928142842279041, 'n_estimators': 676, 'subsample': 0.6632400260518662, 'colsample_bytree': 0.6954336000462807, 'min_child_weight': 7, 'gamma': 0.6507752104547548, 'reg_alpha': 0.011681949759305464, 'reg_lambda': 6.971471877112002e-05, 'max_delta_step': 1}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  82%|████████▎ | 165/200 [02:26<00:25,  1.38it/s]

[I 2025-11-10 18:36:34,687] Trial 165 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.159689006026687, 'n_estimators': 523, 'subsample': 0.7275193732412903, 'colsample_bytree': 0.5079383284821696, 'min_child_weight': 8, 'gamma': 0.09222919978046104, 'reg_alpha': 0.09821488052998288, 'reg_lambda': 0.7666149628895238, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  83%|████████▎ | 166/200 [02:27<00:22,  1.52it/s]

[I 2025-11-10 18:36:35,179] Trial 164 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.1688492577059612, 'n_estimators': 676, 'subsample': 0.698422414243163, 'colsample_bytree': 0.9620538189368577, 'min_child_weight': 8, 'gamma': 0.4089664641744264, 'reg_alpha': 0.013103574034482203, 'reg_lambda': 1.2433493605876975, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  84%|████████▎ | 167/200 [02:28<00:29,  1.13it/s]

[I 2025-11-10 18:36:36,618] Trial 166 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.19736088681687686, 'n_estimators': 713, 'subsample': 0.7453762504494439, 'colsample_bytree': 0.5457446446152481, 'min_child_weight': 8, 'gamma': 0.1697861187641814, 'reg_alpha': 0.09233934500024364, 'reg_lambda': 0.24751862478925662, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  84%|████████▍ | 168/200 [02:29<00:23,  1.33it/s]

[I 2025-11-10 18:36:37,045] Trial 167 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.15735101979458596, 'n_estimators': 555, 'subsample': 0.724541743403208, 'colsample_bytree': 0.9647786957950732, 'min_child_weight': 8, 'gamma': 0.11246140669160454, 'reg_alpha': 0.036165025915687675, 'reg_lambda': 0.859804966183312, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  84%|████████▍ | 169/200 [02:30<00:26,  1.19it/s]

[I 2025-11-10 18:36:38,101] Trial 168 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2133613568233971, 'n_estimators': 716, 'subsample': 0.7454416053557806, 'colsample_bytree': 0.8455706805557883, 'min_child_weight': 8, 'gamma': 0.5071339798108174, 'reg_alpha': 0.02523676312172536, 'reg_lambda': 0.12831182308329914, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  85%|████████▌ | 170/200 [02:30<00:21,  1.42it/s]

[I 2025-11-10 18:36:38,480] Trial 169 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.18907264932096854, 'n_estimators': 728, 'subsample': 0.7399869647628647, 'colsample_bytree': 0.5309609256497857, 'min_child_weight': 8, 'gamma': 0.48167564029035004, 'reg_alpha': 0.2285739896033266, 'reg_lambda': 0.35166316774416767, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  86%|████████▌ | 171/200 [02:34<00:48,  1.66s/it]

[I 2025-11-10 18:36:42,390] Trial 172 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07213438791842369, 'n_estimators': 956, 'subsample': 0.9626868587540119, 'colsample_bytree': 0.91816065929831, 'min_child_weight': 9, 'gamma': 0.23615933160477304, 'reg_alpha': 0.2507303001744025, 'reg_lambda': 0.37415755725619126, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  86%|████████▋ | 173/200 [02:35<00:26,  1.03it/s]

[I 2025-11-10 18:36:42,917] Trial 171 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1845852989247533, 'n_estimators': 1407, 'subsample': 0.9633959709761712, 'colsample_bytree': 0.531804806979206, 'min_child_weight': 9, 'gamma': 0.23692933703464414, 'reg_alpha': 0.22162014388078852, 'reg_lambda': 0.42058060007835857, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:36:43,053] Trial 174 pruned.
[I 2025-11-10 18:36:43,097] Trial 170 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.030483974767571587, 'n_estimators': 1416, 'subsample': 0.967350039223883, 'colsample_bytree': 0.8405626343200511, 'min_child_weight': 9, 'gamma': 0.46480373299699473, 'reg_alpha': 0.027226125373159465, 'reg_lambda': 0.03708007772824857, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  88%|████████▊ | 175/200 [02:36<00:19,  1.29it/s]

[I 2025-11-10 18:36:44,156] Trial 175 pruned.

Best trial: 0. Best value: 0.5:  88%|████████▊ | 176/200 [02:37<00:19,  1.22it/s]

[I 2025-11-10 18:36:45,109] Trial 173 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.0725197789679476, 'n_estimators': 1412, 'subsample': 0.707329221233909, 'colsample_bytree': 0.9409587471980287, 'min_child_weight': 9, 'gamma': 2.8759449484735824, 'reg_alpha': 0.4559448919381678, 'reg_lambda': 1.3172653191290796e-07, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  88%|████████▊ | 177/200 [02:37<00:16,  1.38it/s]

[I 2025-11-10 18:36:45,569] Trial 176 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2039773322179163, 'n_estimators': 544, 'subsample': 0.7077017345727815, 'colsample_bytree': 0.5760575118986462, 'min_child_weight': 5, 'gamma': 3.2241765261405764, 'reg_alpha': 1.7942810818851547, 'reg_lambda': 6.464949773855378, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  89%|████████▉ | 178/200 [02:38<00:17,  1.25it/s]

[I 2025-11-10 18:36:46,566] Trial 180 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.17451732690331762, 'n_estimators': 203, 'subsample': 0.9285413760285448, 'colsample_bytree': 0.6102463888929314, 'min_child_weight': 5, 'gamma': 3.7422523232824494, 'reg_alpha': 9.240359618182227, 'reg_lambda': 9.29272368145861, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  90%|████████▉ | 179/200 [02:39<00:13,  1.55it/s]

[I 2025-11-10 18:36:46,819] Trial 177 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09513505138807932, 'n_estimators': 793, 'subsample': 0.7067707898030142, 'colsample_bytree': 0.5964908465568552, 'min_child_weight': 5, 'gamma': 2.841919183568193, 'reg_alpha': 8.036268662087025, 'reg_lambda': 5.902854502491543, 'max_delta_step': 10}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:36:46,834] Trial 178 finished with value: 0.4698148148148148 and parameters: {'max_depth': 4, 'learning_rate': 0.03794637024264662, 'n_estimators': 546, 'subsample': 0.986088756588458, 'colsample_bytree': 0.5934297028685251, 'min_child_weight': 5, 'gamma': 2.9085592332011316, 'reg_alpha': 0.515060572978746, 'reg_lambda': 3.5322149742281845, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  90%|█████████ | 181/200 [02:40<00:13,  1.45it/s]

[I 2025-11-10 18:36:48,297] Trial 179 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09485454027274548, 'n_estimators': 652, 'subsample': 0.952922960605779, 'colsample_bytree': 0.5749455600916742, 'min_child_weight': 5, 'gamma': 2.497031740003749, 'reg_alpha': 2.039699746685565, 'reg_lambda': 5.110637678740698, 'max_delta_step': 10}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  92%|█████████▏| 183/200 [02:41<00:08,  2.03it/s]

[I 2025-11-10 18:36:48,660] Trial 181 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03676264353560196, 'n_estimators': 406, 'subsample': 0.5441949825483458, 'colsample_bytree': 0.8959873720609479, 'min_child_weight': 10, 'gamma': 2.4837565867881946, 'reg_alpha': 3.0945513486970433, 'reg_lambda': 0.009239249070741182, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:36:48,809] Trial 182 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.019173241527520982, 'n_estimators': 400, 'subsample': 0.9530097507916768, 'colsample_bytree': 0.644213223515106, 'min_child_weight': 10, 'gamma': 2.4695684693931987, 'reg_alpha': 6.752591981455654e-06, 'reg_lambda': 3.633694977641617, 'max_delta_step': 4}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  92%|█████████▏| 184/200 [02:41<00:06,  2.32it/s]

[I 2025-11-10 18:36:49,069] Trial 183 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.018951110529504118, 'n_estimators': 427, 'subsample': 0.9520553004964268, 'colsample_bytree': 0.9829816981891726, 'min_child_weight': 10, 'gamma': 0.10115288932521743, 'reg_alpha': 2.392898272278563, 'reg_lambda': 0.009289023147696689, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  92%|█████████▎| 185/200 [02:43<00:13,  1.09it/s]

[I 2025-11-10 18:36:51,252] Trial 184 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.0243119620245294, 'n_estimators': 585, 'subsample': 0.9361281937999351, 'colsample_bytree': 0.9852018224174824, 'min_child_weight': 8, 'gamma': 0.332227241211554, 'reg_alpha': 3.1062856463041904, 'reg_lambda': 0.007504678274111808, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  93%|█████████▎| 186/200 [02:43<00:11,  1.26it/s]

[I 2025-11-10 18:36:51,741] Trial 186 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.029766894428547387, 'n_estimators': 597, 'subsample': 0.9343640383290953, 'colsample_bytree': 0.9884246211543518, 'min_child_weight': 8, 'gamma': 1.7250762196342304, 'reg_alpha': 0.0002475638372638737, 'reg_lambda': 0.0020735513775547235, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  94%|█████████▎| 187/200 [02:44<00:10,  1.20it/s]

[I 2025-11-10 18:36:52,663] Trial 188 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.13661342599461235, 'n_estimators': 274, 'subsample': 0.9161622182892246, 'colsample_bytree': 0.631490638051714, 'min_child_weight': 8, 'gamma': 3.0366657467490366, 'reg_alpha': 0.0002507535980567365, 'reg_lambda': 9.80115080838855, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  94%|█████████▍| 188/200 [02:45<00:10,  1.17it/s]

[I 2025-11-10 18:36:53,575] Trial 187 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1365787345474604, 'n_estimators': 1050, 'subsample': 0.9328836507680923, 'colsample_bytree': 0.5655132720338365, 'min_child_weight': 8, 'gamma': 1.1505402337114279, 'reg_alpha': 0.0002010366013140598, 'reg_lambda': 9.959398736216936, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  94%|█████████▍| 189/200 [02:46<00:09,  1.20it/s]

[I 2025-11-10 18:36:54,359] Trial 185 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01074733437654883, 'n_estimators': 1269, 'subsample': 0.9412610591693973, 'colsample_bytree': 0.6391231449205392, 'min_child_weight': 8, 'gamma': 0.09646271388791208, 'reg_alpha': 0.9040782203530672, 'reg_lambda': 0.002401782319889133, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  95%|█████████▌| 190/200 [02:47<00:09,  1.07it/s]

[I 2025-11-10 18:36:55,535] Trial 190 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.040162009755266515, 'n_estimators': 638, 'subsample': 0.9791462561411708, 'colsample_bytree': 0.5416270727404501, 'min_child_weight': 8, 'gamma': 1.1892237504325909, 'reg_alpha': 0.00011768822430983271, 'reg_lambda': 1.0300447839271287e-05, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  96%|█████████▌| 191/200 [02:49<00:10,  1.12s/it]

[I 2025-11-10 18:36:57,104] Trial 192 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.012323235184418763, 'n_estimators': 634, 'subsample': 0.995176625588273, 'colsample_bytree': 0.5372321627613365, 'min_child_weight': 7, 'gamma': 0.858629664371641, 'reg_alpha': 1.171919247968128e-05, 'reg_lambda': 1.8051627653479327, 'max_delta_step': 3}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  96%|█████████▌| 192/200 [02:49<00:07,  1.11it/s]

[I 2025-11-10 18:36:57,493] Trial 189 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.0536439698947739, 'n_estimators': 1257, 'subsample': 0.9164781724006115, 'colsample_bytree': 0.6385452676765289, 'min_child_weight': 8, 'gamma': 1.1544197421548146, 'reg_alpha': 0.0019700952038023177, 'reg_lambda': 0.0035991738787413676, 'max_delta_step': 8}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  96%|█████████▋| 193/200 [02:51<00:07,  1.14s/it]

[I 2025-11-10 18:36:59,176] Trial 191 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04566341555996393, 'n_estimators': 1278, 'subsample': 0.9772827463769493, 'colsample_bytree': 0.6215224313924465, 'min_child_weight': 7, 'gamma': 0.7968131544715912, 'reg_alpha': 0.00010866540232427606, 'reg_lambda': 2.046124133141503, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  97%|█████████▋| 194/200 [02:53<00:08,  1.46s/it]

[I 2025-11-10 18:37:01,387] Trial 194 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03604064401845892, 'n_estimators': 961, 'subsample': 0.6295982855714245, 'colsample_bytree': 0.619524565769634, 'min_child_weight': 7, 'gamma': 0.6155359880804969, 'reg_alpha': 1.5854965355255844e-05, 'reg_lambda': 4.1121432342136925, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  98%|█████████▊| 195/200 [02:54<00:05,  1.18s/it]

[I 2025-11-10 18:37:01,929] Trial 195 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04753278160513076, 'n_estimators': 986, 'subsample': 0.6291722716410885, 'colsample_bytree': 0.6205984815149996, 'min_child_weight': 7, 'gamma': 0.6167981761067632, 'reg_alpha': 0.1484859915266266, 'reg_lambda': 3.7532450714188688, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  98%|█████████▊| 196/200 [02:54<00:03,  1.10it/s]

[I 2025-11-10 18:37:02,194] Trial 193 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05458535747855063, 'n_estimators': 1498, 'subsample': 0.9973040896146639, 'colsample_bytree': 0.6547175682839859, 'min_child_weight': 7, 'gamma': 3.9825712216404696, 'reg_alpha': 0.0022714213933797797, 'reg_lambda': 1.724522869579641, 'max_delta_step': 5}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  98%|█████████▊| 197/200 [02:55<00:03,  1.00s/it]

[I 2025-11-10 18:37:03,414] Trial 196 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07956692895612916, 'n_estimators': 965, 'subsample': 0.6945928755768043, 'colsample_bytree': 0.5882515660918549, 'min_child_weight': 10, 'gamma': 4.152606724343359, 'reg_alpha': 0.006169395211862621, 'reg_lambda': 3.692384352820261, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  99%|█████████▉| 198/200 [02:57<00:02,  1.25s/it]

[I 2025-11-10 18:37:05,249] Trial 199 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.08535289495576512, 'n_estimators': 902, 'subsample': 0.8887104228066653, 'colsample_bytree': 0.5884265055792359, 'min_child_weight': 8, 'gamma': 4.161082593703974, 'reg_alpha': 5.673905891918248e-05, 'reg_lambda': 6.981749757563296e-07, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.
[I 2025-11-10 18:37:05,323] Trial 197 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03327447416448489, 'n_estimators': 1098, 'subsample': 0.6954194547672463, 'colsample_bytree': 0.5889972716678028, 'min_child_weight': 8, 'gamma': 3.955291780143126, 'reg_alpha': 0.13530302587559628, 'reg_lambda': 0.005326157900035861, 'max_delta_step': 9}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5: 100%|██████████| 200/200 [02:57<00:00,  1.13it/s]
c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

[I 2025-11-10 18:37:05,553] Trial 198 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03467720319207902, 'n_estimators': 1096, 'subsample': 0.5332502649302442, 'colsample_bytree': 0.6048583456093668, 'min_child_weight': 8, 'gamma': 4.159263300223015, 'reg_alpha': 0.0005292364835663645, 'reg_lambda': 6.946906213762262e-07, 'max_delta_step': 9}. Best is trial 0 with value: 0.5.

[I 2025-11-10 18:37:06,232] A new study created in memory with name: 3_1_roc_auc
Best trial: 2. Best value: 0.5:   0%|          | 1/200 [00:01<04:36,  1.39s/it]

[I 2025-11-10 18:37:07,616] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04113970579350738, 'n_estimators': 370, 'subsample': 0.6744110869235274, 'colsample_bytree': 0.7575360532694577, 'min_child_weight': 7, 'gamma': 3.46857696922335, 'reg_alpha': 0.006720442419226271, 'reg_lambda': 0.0004739186673277705, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.

Best trial: 3. Best value: 0.513938:   1%|          | 2/200 [00:05<09:32,  2.89s/it]

[I 2025-11-10 18:37:11,557] Trial 1 finished with value: 0.48621832358674466 and parameters: {'max_depth': 8, 'learning_rate': 0.09931241836999073, 'n_estimators': 1122, 'subsample': 0.5035592406653524, 'colsample_bytree': 0.59694475455648, 'min_child_weight': 1, 'gamma': 4.3436516846322935, 'reg_alpha': 1.5806145602895975e-08, 'reg_lambda': 3.328609125785191e-06, 'max_delta_step': 9}. Best is trial 2 with value: 0.5.
[I 2025-11-10 18:37:11,584] Trial 3 finished with value: 0.5139376218323586 and parameters: {'max_depth': 3, 'learning_rate': 0.018070174211946854, 'n_estimators': 939, 'subsample': 0.9671536121652807, 'colsample_bytree': 0.9604756232770209, 'min_child_weight': 3, 'gamma': 3.0771378045777342, 'reg_alpha': 1.854381675575487e-08, 'reg_lambda': 2.802995597866304e-08, 'max_delta_step': 0}. Best is trial 3 with value: 0.5139376218323586.

Best trial: 4. Best value: 0.534854:   2%|▏         | 4/200 [00:06<04:33,  1.40s/it]

[I 2025-11-10 18:37:12,573] Trial 4 finished with value: 0.5348538011695907 and parameters: {'max_depth': 5, 'learning_rate': 0.2205747896689275, 'n_estimators': 1296, 'subsample': 0.5990794403308302, 'colsample_bytree': 0.8829275827618539, 'min_child_weight': 4, 'gamma': 3.7965491263233, 'reg_alpha': 0.012678834504920791, 'reg_lambda': 0.22619402900070681, 'max_delta_step': 5}. Best is trial 4 with value: 0.5348538011695907.
[I 2025-11-10 18:37:12,593] Trial 0 finished with value: 0.5317348927875243 and parameters: {'max_depth': 7, 'learning_rate': 0.01830089115748968, 'n_estimators': 978, 'subsample': 0.5790560729787333, 'colsample_bytree': 0.7817254359275564, 'min_child_weight': 1, 'gamma': 2.7116741181991113, 'reg_alpha': 7.786761834847527e-08, 'reg_lambda': 6.867400380424772e-05, 'max_delta_step': 9}. Best is trial 4 with value: 0.5348538011695907.

Best trial: 4. Best value: 0.534854:   3%|▎         | 6/200 [00:09<04:27,  1.38s/it]

[I 2025-11-10 18:37:15,294] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.030176853131767226, 'n_estimators': 657, 'subsample': 0.8018411556475706, 'colsample_bytree': 0.8105476443662214, 'min_child_weight': 7, 'gamma': 1.1140359382585947, 'reg_alpha': 0.009904770528730122, 'reg_lambda': 0.0001809586509522077, 'max_delta_step': 3}. Best is trial 4 with value: 0.5348538011695907.

Best trial: 4. Best value: 0.534854:   4%|▎         | 7/200 [00:10<04:22,  1.36s/it]

[I 2025-11-10 18:37:16,600] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.016705516456858284, 'n_estimators': 1273, 'subsample': 0.6605296127384239, 'colsample_bytree': 0.6053765942733649, 'min_child_weight': 5, 'gamma': 1.7120088705306646, 'reg_alpha': 9.809272332505429e-06, 'reg_lambda': 0.005622215566149701, 'max_delta_step': 3}. Best is trial 4 with value: 0.5348538011695907.

Best trial: 5. Best value: 0.572144:   4%|▍         | 8/200 [00:11<04:18,  1.34s/it]

[I 2025-11-10 18:37:17,895] Trial 5 finished with value: 0.5721442495126705 and parameters: {'max_depth': 6, 'learning_rate': 0.11544378203005275, 'n_estimators': 1210, 'subsample': 0.6102855700272429, 'colsample_bytree': 0.9561004527930084, 'min_child_weight': 2, 'gamma': 4.302752072719876, 'reg_alpha': 0.001012243955777261, 'reg_lambda': 0.031078730586879055, 'max_delta_step': 7}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:   4%|▍         | 9/200 [00:12<03:45,  1.18s/it]

[I 2025-11-10 18:37:18,639] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01708553394017102, 'n_estimators': 1445, 'subsample': 0.7122450786386522, 'colsample_bytree': 0.8835163338312078, 'min_child_weight': 10, 'gamma': 1.7945057442112304, 'reg_alpha': 1.8889302820377333e-07, 'reg_lambda': 8.384010131996484e-08, 'max_delta_step': 2}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:   5%|▌         | 10/200 [00:13<03:36,  1.14s/it]

[I 2025-11-10 18:37:19,672] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.036433426053159745, 'n_estimators': 1130, 'subsample': 0.7014986720236345, 'colsample_bytree': 0.6341810983404981, 'min_child_weight': 5, 'gamma': 3.609532959090501, 'reg_alpha': 0.0007424189913459692, 'reg_lambda': 6.877310525167737e-06, 'max_delta_step': 3}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:   6%|▌         | 12/200 [00:14<02:45,  1.13it/s]

[I 2025-11-10 18:37:21,001] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.16967865430557846, 'n_estimators': 1096, 'subsample': 0.8801987476988344, 'colsample_bytree': 0.7755121000648015, 'min_child_weight': 7, 'gamma': 4.946078601088127, 'reg_alpha': 0.0007803891900277132, 'reg_lambda': 0.0004144740947314692, 'max_delta_step': 2}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:37:21,130] Trial 13 pruned.

Best trial: 5. Best value: 0.572144:   6%|▋         | 13/200 [00:15<02:08,  1.45it/s]

[I 2025-11-10 18:37:21,346] Trial 11 finished with value: 0.529551656920078 and parameters: {'max_depth': 6, 'learning_rate': 0.11056681219809078, 'n_estimators': 498, 'subsample': 0.8838142630594827, 'colsample_bytree': 0.8110917763529937, 'min_child_weight': 1, 'gamma': 3.639869366253832, 'reg_alpha': 5.063966593389791e-05, 'reg_lambda': 1.238390754270665e-07, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:   7%|▋         | 14/200 [00:16<02:28,  1.26it/s]

[I 2025-11-10 18:37:22,402] Trial 15 pruned.
[I 2025-11-10 18:37:22,418] Trial 14 pruned.

Best trial: 5. Best value: 0.572144:   8%|▊         | 16/200 [00:16<01:32,  1.99it/s]

[I 2025-11-10 18:37:22,715] Trial 16 pruned.
[I 2025-11-10 18:37:22,755] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.2833237460838016, 'n_estimators': 1052, 'subsample': 0.5309313887968095, 'colsample_bytree': 0.5594626975338921, 'min_child_weight': 10, 'gamma': 1.3631267662671758, 'reg_alpha': 6.912462789113927e-08, 'reg_lambda': 0.010036035530851403, 'max_delta_step': 8}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:   9%|▉         | 18/200 [00:17<01:38,  1.85it/s]

[I 2025-11-10 18:37:23,913] Trial 20 pruned.

Best trial: 5. Best value: 0.572144:  10%|▉         | 19/200 [00:19<02:12,  1.37it/s]

[I 2025-11-10 18:37:25,314] Trial 21 pruned.

Best trial: 5. Best value: 0.572144:  10%|█         | 21/200 [00:21<02:39,  1.12it/s]

[I 2025-11-10 18:37:27,778] Trial 18 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.16640595713782483, 'n_estimators': 1268, 'subsample': 0.5018105561597582, 'colsample_bytree': 0.5008149651210925, 'min_child_weight': 4, 'gamma': 2.699182152609264, 'reg_alpha': 0.037239868585299436, 'reg_lambda': 0.04719812021325343, 'max_delta_step': 8}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:37:27,920] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.15764441209521884, 'n_estimators': 1258, 'subsample': 0.5122081293294514, 'colsample_bytree': 0.5179429896331472, 'min_child_weight': 4, 'gamma': 2.396439464240707, 'reg_alpha': 0.03180978532062694, 'reg_lambda': 0.015428993536015444, 'max_delta_step': 8}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  11%|█         | 22/200 [00:22<02:17,  1.30it/s]

[I 2025-11-10 18:37:28,368] Trial 17 finished with value: 0.5461403508771928 and parameters: {'max_depth': 5, 'learning_rate': 0.2606653653759915, 'n_estimators': 1293, 'subsample': 0.6021143130100813, 'colsample_bytree': 0.9045651564813225, 'min_child_weight': 4, 'gamma': 0.1479007490985933, 'reg_alpha': 0.07511033726384386, 'reg_lambda': 0.06332716146843725, 'max_delta_step': 7}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  12%|█▏        | 23/200 [00:22<02:07,  1.38it/s]

[I 2025-11-10 18:37:28,964] Trial 24 pruned.

Best trial: 5. Best value: 0.572144:  12%|█▏        | 24/200 [00:22<01:42,  1.72it/s]

[I 2025-11-10 18:37:29,182] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.06774384616744383, 'n_estimators': 845, 'subsample': 0.6208163396766607, 'colsample_bytree': 0.9301369684628382, 'min_child_weight': 6, 'gamma': 2.7637232771574394, 'reg_alpha': 0.08449936607406798, 'reg_lambda': 0.7211402620233516, 'max_delta_step': 5}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  12%|█▎        | 25/200 [00:24<02:05,  1.40it/s]

[I 2025-11-10 18:37:30,233] Trial 26 pruned.

Best trial: 5. Best value: 0.572144:  13%|█▎        | 26/200 [00:24<01:40,  1.73it/s]

[I 2025-11-10 18:37:30,479] Trial 27 pruned.

Best trial: 5. Best value: 0.572144:  14%|█▎        | 27/200 [00:25<02:02,  1.41it/s]

[I 2025-11-10 18:37:31,494] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.0726277840059159, 'n_estimators': 801, 'subsample': 0.6149204057132742, 'colsample_bytree': 0.9446539703016477, 'min_child_weight': 6, 'gamma': 3.0412116029313125, 'reg_alpha': 0.00014258739970096553, 'reg_lambda': 1.3630762740875102, 'max_delta_step': 5}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  14%|█▍        | 28/200 [00:25<01:53,  1.51it/s]

[I 2025-11-10 18:37:32,052] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.06886966470574199, 'n_estimators': 809, 'subsample': 0.6277875945673813, 'colsample_bytree': 0.9330904357590516, 'min_child_weight': 6, 'gamma': 0.25361707109929643, 'reg_alpha': 0.00011992500803739898, 'reg_lambda': 0.6022499656135352, 'max_delta_step': 5}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  14%|█▍        | 29/200 [00:29<04:19,  1.52s/it]

[I 2025-11-10 18:37:35,598] Trial 29 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.12898631026813356, 'n_estimators': 1194, 'subsample': 0.5413920203044904, 'colsample_bytree': 0.921836928776455, 'min_child_weight': 6, 'gamma': 4.090338970522405, 'reg_alpha': 0.2271545526176704, 'reg_lambda': 0.08493686144465222, 'max_delta_step': 4}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  15%|█▌        | 30/200 [00:29<03:25,  1.21s/it]

[I 2025-11-10 18:37:36,071] Trial 28 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.20958867399656497, 'n_estimators': 1367, 'subsample': 0.54741981101774, 'colsample_bytree': 0.8396601255463217, 'min_child_weight': 6, 'gamma': 0.663022255689147, 'reg_alpha': 0.2980704305075156, 'reg_lambda': 0.002140711347552026, 'max_delta_step': 7}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  16%|█▌        | 31/200 [00:30<02:45,  1.02it/s]

[I 2025-11-10 18:37:36,513] Trial 30 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.13209988273950873, 'n_estimators': 1145, 'subsample': 0.558976553505582, 'colsample_bytree': 0.8593462615885964, 'min_child_weight': 5, 'gamma': 0.7184547186297303, 'reg_alpha': 8.668986750075218, 'reg_lambda': 0.06821206668880656, 'max_delta_step': 7}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  16%|█▋        | 33/200 [00:30<01:44,  1.60it/s]

[I 2025-11-10 18:37:37,003] Trial 33 pruned.
[I 2025-11-10 18:37:37,143] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.11591204824926186, 'n_estimators': 1190, 'subsample': 0.5540636840436675, 'colsample_bytree': 0.8396329030774798, 'min_child_weight': 5, 'gamma': 0.6624933722399764, 'reg_alpha': 0.19624792496085666, 'reg_lambda': 0.07084048543460243, 'max_delta_step': 7}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  17%|█▋        | 34/200 [00:31<01:52,  1.48it/s]

[I 2025-11-10 18:37:37,934] Trial 34 pruned.

Best trial: 5. Best value: 0.572144:  18%|█▊        | 37/200 [00:32<00:57,  2.82it/s]

[I 2025-11-10 18:37:38,317] Trial 37 pruned.
[I 2025-11-10 18:37:38,333] Trial 35 pruned.
[I 2025-11-10 18:37:38,483] Trial 36 pruned.

Best trial: 5. Best value: 0.572144:  19%|█▉        | 38/200 [00:33<01:18,  2.08it/s]

[I 2025-11-10 18:37:39,350] Trial 39 pruned.

Best trial: 5. Best value: 0.572144:  20%|█▉        | 39/200 [00:33<01:06,  2.41it/s]

[I 2025-11-10 18:37:39,576] Trial 40 pruned.

Best trial: 5. Best value: 0.572144:  20%|██        | 40/200 [00:33<01:03,  2.54it/s]

[I 2025-11-10 18:37:39,908] Trial 38 pruned.
[I 2025-11-10 18:37:39,914] Trial 32 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.012343152676644403, 'n_estimators': 1007, 'subsample': 0.5574141228709751, 'colsample_bytree': 0.8440366019718464, 'min_child_weight': 4, 'gamma': 0.8081479131301447, 'reg_alpha': 0.007376223367340872, 'reg_lambda': 0.0022837361476876587, 'max_delta_step': 7}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  22%|██▏       | 44/200 [00:34<00:41,  3.78it/s]

[I 2025-11-10 18:37:40,625] Trial 41 pruned.
[I 2025-11-10 18:37:40,631] Trial 44 pruned.
[I 2025-11-10 18:37:40,791] Trial 43 pruned.

Best trial: 5. Best value: 0.572144:  22%|██▎       | 45/200 [00:35<00:48,  3.20it/s]

[I 2025-11-10 18:37:41,282] Trial 47 pruned.

Best trial: 5. Best value: 0.572144:  23%|██▎       | 46/200 [00:35<01:05,  2.35it/s]

[I 2025-11-10 18:37:42,073] Trial 48 pruned.

Best trial: 5. Best value: 0.572144:  24%|██▍       | 48/200 [00:36<00:55,  2.74it/s]

[I 2025-11-10 18:37:42,605] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.10596372609819715, 'n_estimators': 415, 'subsample': 0.872109806517992, 'colsample_bytree': 0.7530760329250431, 'min_child_weight': 9, 'gamma': 3.693587203467684, 'reg_alpha': 0.00038977887569092653, 'reg_lambda': 3.785958889615863e-07, 'max_delta_step': 1}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:37:42,728] Trial 49 pruned.

Best trial: 5. Best value: 0.572144:  24%|██▍       | 49/200 [00:36<00:57,  2.62it/s]

[I 2025-11-10 18:37:43,151] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.1054111115456681, 'n_estimators': 519, 'subsample': 0.9090093172431617, 'colsample_bytree': 0.9023402466896515, 'min_child_weight': 9, 'gamma': 3.8404681537069396, 'reg_alpha': 0.0003647769609847862, 'reg_lambda': 4.343750831021686e-07, 'max_delta_step': 1}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  25%|██▌       | 50/200 [00:39<02:30,  1.00s/it]

[I 2025-11-10 18:37:45,735] Trial 42 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.23277931959287235, 'n_estimators': 1401, 'subsample': 0.5996156119609275, 'colsample_bytree': 0.7961389039275063, 'min_child_weight': 9, 'gamma': 3.7729678766553745, 'reg_alpha': 2.7094047348434003e-08, 'reg_lambda': 3.4029539288590653e-07, 'max_delta_step': 6}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  26%|██▌       | 51/200 [00:41<03:07,  1.26s/it]

[I 2025-11-10 18:37:47,638] Trial 50 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.14707061155862874, 'n_estimators': 1109, 'subsample': 0.783112807765171, 'colsample_bytree': 0.9967871298578523, 'min_child_weight': 8, 'gamma': 4.97684971764909, 'reg_alpha': 4.111179931663898e-07, 'reg_lambda': 1.9647184664281285, 'max_delta_step': 6}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  26%|██▌       | 52/200 [00:41<02:28,  1.00s/it]

[I 2025-11-10 18:37:48,019] Trial 51 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.24265706570485898, 'n_estimators': 1181, 'subsample': 0.9301243665803479, 'colsample_bytree': 0.9069859250466072, 'min_child_weight': 8, 'gamma': 2.777547684143818, 'reg_alpha': 0.0015969863033599113, 'reg_lambda': 0.0005682168709416026, 'max_delta_step': 8}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  26%|██▋       | 53/200 [00:42<01:56,  1.26it/s]

[I 2025-11-10 18:37:48,304] Trial 52 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.17878241682252083, 'n_estimators': 1201, 'subsample': 0.6013341636555594, 'colsample_bytree': 0.7754800463511834, 'min_child_weight': 5, 'gamma': 2.847714172555482, 'reg_alpha': 0.002270458357640275, 'reg_lambda': 0.00039921788618407225, 'max_delta_step': 10}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  27%|██▋       | 54/200 [00:42<01:54,  1.27it/s]

[I 2025-11-10 18:37:49,071] Trial 56 pruned.
[I 2025-11-10 18:37:49,115] Trial 54 pruned.

Best trial: 5. Best value: 0.572144:  28%|██▊       | 56/200 [00:43<01:20,  1.79it/s]

[I 2025-11-10 18:37:49,656] Trial 55 pruned.

Best trial: 5. Best value: 0.572144:  28%|██▊       | 57/200 [00:44<01:27,  1.64it/s]

[I 2025-11-10 18:37:50,416] Trial 59 pruned.
[I 2025-11-10 18:37:50,454] Trial 57 pruned.

Best trial: 5. Best value: 0.572144:  30%|██▉       | 59/200 [00:44<00:58,  2.40it/s]

[I 2025-11-10 18:37:50,702] Trial 53 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.18487916054326947, 'n_estimators': 1169, 'subsample': 0.5208651532708926, 'colsample_bytree': 0.6449565939625983, 'min_child_weight': 5, 'gamma': 2.956445781406696, 'reg_alpha': 0.0021675719206331965, 'reg_lambda': 0.00033420916808531007, 'max_delta_step': 10}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  30%|███       | 60/200 [00:45<01:05,  2.14it/s]

[I 2025-11-10 18:37:51,338] Trial 61 pruned.

Best trial: 5. Best value: 0.572144:  30%|███       | 61/200 [00:45<01:17,  1.79it/s]

[I 2025-11-10 18:37:52,181] Trial 62 pruned.

Best trial: 5. Best value: 0.572144:  31%|███       | 62/200 [00:46<01:18,  1.76it/s]

[I 2025-11-10 18:37:52,778] Trial 63 pruned.

Best trial: 5. Best value: 0.572144:  32%|███▏      | 63/200 [00:47<01:17,  1.76it/s]

[I 2025-11-10 18:37:53,343] Trial 65 pruned.

Best trial: 5. Best value: 0.572144:  32%|███▏      | 64/200 [00:47<01:18,  1.72it/s]

[I 2025-11-10 18:37:53,954] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.057078467975088004, 'n_estimators': 414, 'subsample': 0.6382125207109128, 'colsample_bytree': 0.759363081159466, 'min_child_weight': 7, 'gamma': 3.5545563146132877, 'reg_alpha': 0.027458212825459044, 'reg_lambda': 0.007550865513314358, 'max_delta_step': 1}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  32%|███▎      | 65/200 [00:48<01:21,  1.66it/s]

[I 2025-11-10 18:37:54,620] Trial 66 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.05744716961616349, 'n_estimators': 270, 'subsample': 0.6824560316455149, 'colsample_bytree': 0.8651242819873054, 'min_child_weight': 7, 'gamma': 3.2039167388899186, 'reg_alpha': 0.6320993331008556, 'reg_lambda': 1.2752050844198627e-07, 'max_delta_step': 8}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  33%|███▎      | 66/200 [00:48<01:14,  1.81it/s]

[I 2025-11-10 18:37:55,044] Trial 58 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03524525371010732, 'n_estimators': 1319, 'subsample': 0.521536457888135, 'colsample_bytree': 0.9595724598643206, 'min_child_weight': 4, 'gamma': 3.0703027984053497, 'reg_alpha': 0.08745602593531492, 'reg_lambda': 8.524448605494119e-08, 'max_delta_step': 3}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  34%|███▎      | 67/200 [00:49<00:59,  2.24it/s]

[I 2025-11-10 18:37:55,232] Trial 67 pruned.

Best trial: 5. Best value: 0.572144:  34%|███▍      | 68/200 [00:49<00:54,  2.41it/s]

[I 2025-11-10 18:37:55,577] Trial 70 pruned.

Best trial: 5. Best value: 0.572144:  34%|███▍      | 69/200 [00:51<02:09,  1.01it/s]

[I 2025-11-10 18:37:57,920] Trial 60 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.025715791535749075, 'n_estimators': 1323, 'subsample': 0.5260149266735734, 'colsample_bytree': 0.9547982558405766, 'min_child_weight': 2, 'gamma': 4.744220213975462, 'reg_alpha': 5.617051341004365e-06, 'reg_lambda': 9.32510059107732, 'max_delta_step': 2}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  35%|███▌      | 70/200 [00:53<02:24,  1.11s/it]

[I 2025-11-10 18:37:59,309] Trial 68 finished with value: 0.5585964912280702 and parameters: {'max_depth': 4, 'learning_rate': 0.2655335525247145, 'n_estimators': 1071, 'subsample': 0.6050075826055427, 'colsample_bytree': 0.8869546676584434, 'min_child_weight': 4, 'gamma': 4.1237282912387565, 'reg_alpha': 0.09817288345578758, 'reg_lambda': 0.018123384363524016, 'max_delta_step': 7}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  36%|███▌      | 71/200 [00:54<02:18,  1.08s/it]

[I 2025-11-10 18:38:00,317] Trial 69 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.014056101482418409, 'n_estimators': 1231, 'subsample': 0.6073446023686744, 'colsample_bytree': 0.7861409249541303, 'min_child_weight': 5, 'gamma': 4.1007674225751884, 'reg_alpha': 6.168549750505472e-05, 'reg_lambda': 0.027716275698381847, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  36%|███▌      | 72/200 [00:54<01:57,  1.09it/s]

[I 2025-11-10 18:38:00,869] Trial 71 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08475348449618945, 'n_estimators': 1245, 'subsample': 0.723123430982945, 'colsample_bytree': 0.7903002078728777, 'min_child_weight': 5, 'gamma': 4.061568962338086, 'reg_alpha': 0.0007907079840342548, 'reg_lambda': 0.002867171146223866, 'max_delta_step': 7}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  36%|███▋      | 73/200 [00:55<01:44,  1.22it/s]

[I 2025-11-10 18:38:01,462] Trial 74 pruned.

Best trial: 5. Best value: 0.572144:  37%|███▋      | 74/200 [00:55<01:29,  1.41it/s]

[I 2025-11-10 18:38:01,913] Trial 75 pruned.

Best trial: 5. Best value: 0.572144:  38%|███▊      | 75/200 [00:56<01:18,  1.58it/s]

[I 2025-11-10 18:38:02,358] Trial 76 pruned.

Best trial: 5. Best value: 0.572144:  38%|███▊      | 77/200 [00:56<00:52,  2.32it/s]

[I 2025-11-10 18:38:02,781] Trial 77 pruned.
[I 2025-11-10 18:38:02,892] Trial 72 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08996752718612824, 'n_estimators': 1114, 'subsample': 0.7274335950192228, 'colsample_bytree': 0.7874938070025218, 'min_child_weight': 5, 'gamma': 2.547283853123677, 'reg_alpha': 0.01504166684408844, 'reg_lambda': 0.4656474656722438, 'max_delta_step': 7}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  39%|███▉      | 78/200 [00:57<01:00,  2.01it/s]

[I 2025-11-10 18:38:03,545] Trial 78 pruned.

Best trial: 5. Best value: 0.572144:  40%|████      | 80/200 [00:57<00:46,  2.56it/s]

[I 2025-11-10 18:38:04,049] Trial 79 pruned.
[I 2025-11-10 18:38:04,183] Trial 80 pruned.
[I 2025-11-10 18:38:04,198] Trial 73 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.26651477232330867, 'n_estimators': 1081, 'subsample': 0.5412222495297944, 'colsample_bytree': 0.9373855892320793, 'min_child_weight': 5, 'gamma': 4.1823608978168485, 'reg_alpha': 4.805821558462371, 'reg_lambda': 0.0048101191869099336, 'max_delta_step': 7}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  41%|████      | 82/200 [00:58<00:50,  2.31it/s]

[I 2025-11-10 18:38:05,141] Trial 82 pruned.

Best trial: 5. Best value: 0.572144:  42%|████▏     | 83/200 [01:01<02:06,  1.08s/it]

[I 2025-11-10 18:38:08,202] Trial 81 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.019976439658097797, 'n_estimators': 1026, 'subsample': 0.7629466263026009, 'colsample_bytree': 0.9129639515732857, 'min_child_weight': 6, 'gamma': 3.3992025892468334, 'reg_alpha': 0.00019318228753403707, 'reg_lambda': 0.00019936138896242567, 'max_delta_step': 5}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  42%|████▏     | 84/200 [01:02<01:46,  1.09it/s]

[I 2025-11-10 18:38:08,653] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.0154628526885392, 'n_estimators': 1028, 'subsample': 0.5607575826846669, 'colsample_bytree': 0.675267435343442, 'min_child_weight': 6, 'gamma': 1.7330758078365496, 'reg_alpha': 2.0310946845512077e-06, 'reg_lambda': 0.00015275725865124121, 'max_delta_step': 5}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:38:08,718] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.1551431457266564, 'n_estimators': 1012, 'subsample': 0.5642856179869614, 'colsample_bytree': 0.8530576954430119, 'min_child_weight': 6, 'gamma': 3.6529559882009752, 'reg_alpha': 4.5568783874425016e-08, 'reg_lambda': 1.7830329189821292, 'max_delta_step': 5}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  43%|████▎     | 86/200 [01:03<01:15,  1.50it/s]

[I 2025-11-10 18:38:09,308] Trial 86 pruned.

Best trial: 5. Best value: 0.572144:  44%|████▍     | 88/200 [01:03<00:55,  2.01it/s]

[I 2025-11-10 18:38:09,741] Trial 87 pruned.
[I 2025-11-10 18:38:09,900] Trial 88 pruned.

Best trial: 5. Best value: 0.572144:  44%|████▍     | 89/200 [01:04<01:02,  1.78it/s]

[I 2025-11-10 18:38:10,638] Trial 89 pruned.

Best trial: 5. Best value: 0.572144:  45%|████▌     | 90/200 [01:04<00:56,  1.96it/s]

[I 2025-11-10 18:38:11,015] Trial 90 pruned.

Best trial: 5. Best value: 0.572144:  46%|████▌     | 91/200 [01:05<00:51,  2.10it/s]

[I 2025-11-10 18:38:11,404] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.16409876413335261, 'n_estimators': 1375, 'subsample': 0.6201902320458927, 'colsample_bytree': 0.8578782416704898, 'min_child_weight': 6, 'gamma': 4.427962841388755, 'reg_alpha': 0.0038221682295822294, 'reg_lambda': 0.015484556596069829, 'max_delta_step': 5}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  46%|████▌     | 92/200 [01:05<00:52,  2.07it/s]

[I 2025-11-10 18:38:11,906] Trial 92 pruned.

Best trial: 5. Best value: 0.572144:  46%|████▋     | 93/200 [01:06<01:12,  1.48it/s]

[I 2025-11-10 18:38:13,055] Trial 93 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.21730450348656152, 'n_estimators': 463, 'subsample': 0.5851708061289276, 'colsample_bytree': 0.8169717422497189, 'min_child_weight': 8, 'gamma': 4.580510307334495, 'reg_alpha': 0.005765922605120616, 'reg_lambda': 1.070755448313401, 'max_delta_step': 1}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  47%|████▋     | 94/200 [01:07<01:05,  1.61it/s]

[I 2025-11-10 18:38:13,540] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.04002697288065376, 'n_estimators': 468, 'subsample': 0.8507892740412313, 'colsample_bytree': 0.8108969742018084, 'min_child_weight': 8, 'gamma': 0.5514261965373495, 'reg_alpha': 0.010314225609559226, 'reg_lambda': 6.323688949866521e-05, 'max_delta_step': 3}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  48%|████▊     | 95/200 [01:08<01:19,  1.32it/s]

[I 2025-11-10 18:38:14,626] Trial 95 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.040902004928345795, 'n_estimators': 604, 'subsample': 0.830250118210674, 'colsample_bytree': 0.8148602186689864, 'min_child_weight': 8, 'gamma': 0.9307663249827179, 'reg_alpha': 0.0100085294930287, 'reg_lambda': 7.22856501641388e-05, 'max_delta_step': 1}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  48%|████▊     | 97/200 [01:09<01:12,  1.43it/s]

[I 2025-11-10 18:38:16,044] Trial 91 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.012342615403989572, 'n_estimators': 1349, 'subsample': 0.5847224513001865, 'colsample_bytree': 0.8647871076026703, 'min_child_weight': 7, 'gamma': 0.5009590119789944, 'reg_alpha': 2.1742277951149963e-07, 'reg_lambda': 0.04991844533719008, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:38:16,145] Trial 97 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.02844998485249778, 'n_estimators': 574, 'subsample': 0.5964453075214244, 'colsample_bytree': 0.8353068588527061, 'min_child_weight': 7, 'gamma': 0.8036636203052184, 'reg_alpha': 2.982207604934471e-07, 'reg_lambda': 6.7177315262839715e-06, 'max_delta_step': 6}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  49%|████▉     | 98/200 [01:10<01:08,  1.49it/s]

[I 2025-11-10 18:38:16,747] Trial 96 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03038391444825689, 'n_estimators': 794, 'subsample': 0.8552355489262845, 'colsample_bytree': 0.8406050372099984, 'min_child_weight': 7, 'gamma': 0.8370311627921895, 'reg_alpha': 0.011095911333028011, 'reg_lambda': 4.9489362727217965e-05, 'max_delta_step': 3}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  50%|████▉     | 99/200 [01:11<01:19,  1.28it/s]

[I 2025-11-10 18:38:17,797] Trial 99 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03126585289676127, 'n_estimators': 340, 'subsample': 0.9168002184277506, 'colsample_bytree': 0.8871899380482215, 'min_child_weight': 7, 'gamma': 3.3145498008880887, 'reg_alpha': 0.001483005464169033, 'reg_lambda': 0.0014281323466591462, 'max_delta_step': 10}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  50%|█████     | 100/200 [01:12<01:10,  1.42it/s]

[I 2025-11-10 18:38:18,312] Trial 98 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.062205423945718194, 'n_estimators': 796, 'subsample': 0.7946506842309176, 'colsample_bytree': 0.8302331571344727, 'min_child_weight': 7, 'gamma': 0.020530512564237213, 'reg_alpha': 2.2461262602396298e-07, 'reg_lambda': 3.191597986877776e-08, 'max_delta_step': 3}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  50%|█████     | 101/200 [01:13<01:33,  1.06it/s]

[I 2025-11-10 18:38:19,818] Trial 101 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.016716672284648917, 'n_estimators': 669, 'subsample': 0.7891023814191461, 'colsample_bytree': 0.8921114657435097, 'min_child_weight': 10, 'gamma': 2.9197080617984428, 'reg_alpha': 0.2103315874850667, 'reg_lambda': 2.0073507154997552e-05, 'max_delta_step': 10}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  51%|█████     | 102/200 [01:15<01:50,  1.13s/it]

[I 2025-11-10 18:38:21,390] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.052394113308848, 'n_estimators': 648, 'subsample': 0.693099872158497, 'colsample_bytree': 0.9717729606048655, 'min_child_weight': 5, 'gamma': 2.6977728575794426, 'reg_alpha': 7.13319078769693e-07, 'reg_lambda': 1.0768334796028333e-05, 'max_delta_step': 2}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  52%|█████▏    | 103/200 [01:15<01:23,  1.17it/s]

[I 2025-11-10 18:38:21,604] Trial 100 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.022142011498392712, 'n_estimators': 1281, 'subsample': 0.9265702350712114, 'colsample_bytree': 0.5036709877497008, 'min_child_weight': 7, 'gamma': 2.6865708976491005, 'reg_alpha': 0.1543983036069395, 'reg_lambda': 2.6911615920845383e-05, 'max_delta_step': 3}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  52%|█████▏    | 104/200 [01:17<01:59,  1.24s/it]

[I 2025-11-10 18:38:23,742] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04789260123837098, 'n_estimators': 1298, 'subsample': 0.8037259912838841, 'colsample_bytree': 0.9709405768183035, 'min_child_weight': 10, 'gamma': 0.1727669325434439, 'reg_alpha': 0.32892697801111676, 'reg_lambda': 1.7296566212356332e-07, 'max_delta_step': 7}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  52%|█████▎    | 105/200 [01:18<01:59,  1.26s/it]

[I 2025-11-10 18:38:25,057] Trial 107 pruned.

Best trial: 5. Best value: 0.572144:  53%|█████▎    | 106/200 [01:19<01:28,  1.06it/s]

[I 2025-11-10 18:38:25,265] Trial 104 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.022677828129638197, 'n_estimators': 1304, 'subsample': 0.6959157179614024, 'colsample_bytree': 0.5039812166627479, 'min_child_weight': 10, 'gamma': 1.2985952331661537, 'reg_alpha': 8.340218274401858e-07, 'reg_lambda': 1.5459298401539631e-07, 'max_delta_step': 2}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  54%|█████▎    | 107/200 [01:20<01:34,  1.02s/it]

[I 2025-11-10 18:38:26,444] Trial 108 pruned.

Best trial: 5. Best value: 0.572144:  54%|█████▍    | 108/200 [01:20<01:11,  1.28it/s]

[I 2025-11-10 18:38:26,675] Trial 109 pruned.

Best trial: 5. Best value: 0.572144:  55%|█████▍    | 109/200 [01:21<01:09,  1.30it/s]

[I 2025-11-10 18:38:27,414] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.018307060751294187, 'n_estimators': 1289, 'subsample': 0.9666741420291172, 'colsample_bytree': 0.911122442151339, 'min_child_weight': 9, 'gamma': 1.6799442624471848, 'reg_alpha': 4.236885442328525e-05, 'reg_lambda': 2.9590722874513718e-08, 'max_delta_step': 2}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  55%|█████▌    | 110/200 [01:21<01:04,  1.40it/s]

[I 2025-11-10 18:38:28,003] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.017964971836201295, 'n_estimators': 1474, 'subsample': 0.7095852282833514, 'colsample_bytree': 0.9215042012580078, 'min_child_weight': 10, 'gamma': 1.6064103209313327, 'reg_alpha': 3.60739023687797e-05, 'reg_lambda': 1.3805407225963328e-07, 'max_delta_step': 2}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  56%|█████▌    | 111/200 [01:22<01:12,  1.23it/s]

[I 2025-11-10 18:38:29,052] Trial 112 pruned.

Best trial: 5. Best value: 0.572144:  56%|█████▌    | 112/200 [01:23<00:58,  1.51it/s]

[I 2025-11-10 18:38:29,362] Trial 113 pruned.

Best trial: 5. Best value: 0.572144:  57%|█████▋    | 114/200 [01:24<00:59,  1.44it/s]

[I 2025-11-10 18:38:30,908] Trial 110 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.27929646651997764, 'n_estimators': 984, 'subsample': 0.962514069614687, 'colsample_bytree': 0.9069285756038848, 'min_child_weight': 9, 'gamma': 1.9292122704282997, 'reg_alpha': 1.653713729789932e-08, 'reg_lambda': 3.0410464259749854e-08, 'max_delta_step': 1}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:38:31,066] Trial 111 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03344735039461408, 'n_estimators': 974, 'subsample': 0.6757590622309931, 'colsample_bytree': 0.9031615052604263, 'min_child_weight': 9, 'gamma': 3.747657392268528, 'reg_alpha': 0.021359173486198757, 'reg_lambda': 0.15197595600173386, 'max_delta_step': 8}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  57%|█████▊    | 115/200 [01:27<01:48,  1.28s/it]

[I 2025-11-10 18:38:33,712] Trial 114 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.037072907055599916, 'n_estimators': 1064, 'subsample': 0.6783272808787935, 'colsample_bytree': 0.6220521982848448, 'min_child_weight': 5, 'gamma': 3.5828381598958035, 'reg_alpha': 0.00033766821668673025, 'reg_lambda': 6.866072931720714e-07, 'max_delta_step': 4}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  58%|█████▊    | 116/200 [01:28<01:42,  1.22s/it]

[I 2025-11-10 18:38:34,776] Trial 115 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03372825096188716, 'n_estimators': 1261, 'subsample': 0.6837993128534299, 'colsample_bytree': 0.5799228639378128, 'min_child_weight': 5, 'gamma': 3.6111492321248635, 'reg_alpha': 1.8216539334848428e-08, 'reg_lambda': 0.00022809217426238889, 'max_delta_step': 4}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  58%|█████▊    | 117/200 [01:29<01:22,  1.01it/s]

[I 2025-11-10 18:38:35,252] Trial 118 pruned.

Best trial: 5. Best value: 0.572144:  60%|█████▉    | 119/200 [01:30<00:59,  1.37it/s]

[I 2025-11-10 18:38:36,159] Trial 117 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.016826687581349607, 'n_estimators': 1190, 'subsample': 0.762221605959152, 'colsample_bytree': 0.6145795188511017, 'min_child_weight': 5, 'gamma': 3.511959024675182, 'reg_alpha': 0.00047534213669002894, 'reg_lambda': 0.00029426267542425905, 'max_delta_step': 3}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:38:36,341] Trial 119 pruned.

Best trial: 5. Best value: 0.572144:  60%|██████    | 121/200 [01:30<00:33,  2.33it/s]

[I 2025-11-10 18:38:36,362] Trial 116 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03449381085576379, 'n_estimators': 1268, 'subsample': 0.7399210683619177, 'colsample_bytree': 0.6228867891042505, 'min_child_weight': 5, 'gamma': 3.4833242994453997, 'reg_alpha': 0.0002500354293533823, 'reg_lambda': 3.2805345531312804e-06, 'max_delta_step': 3}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:38:36,493] Trial 120 pruned.

Best trial: 5. Best value: 0.572144:  61%|██████    | 122/200 [01:31<00:45,  1.73it/s]

[I 2025-11-10 18:38:37,516] Trial 123 pruned.

Best trial: 5. Best value: 0.572144:  62%|██████▏   | 123/200 [01:33<01:07,  1.14it/s]

[I 2025-11-10 18:38:39,229] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.19144164065062708, 'n_estimators': 362, 'subsample': 0.9855959878469507, 'colsample_bytree': 0.7463516468905931, 'min_child_weight': 6, 'gamma': 4.12265630839963, 'reg_alpha': 8.861448781664444e-05, 'reg_lambda': 0.00036062756631028185, 'max_delta_step': 2}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  62%|██████▎   | 125/200 [01:35<01:08,  1.10it/s]

[I 2025-11-10 18:38:41,314] Trial 121 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.12991432676152154, 'n_estimators': 1146, 'subsample': 0.6460140175577116, 'colsample_bytree': 0.6355541543866237, 'min_child_weight': 6, 'gamma': 4.135877445240151, 'reg_alpha': 0.0001059423464663899, 'reg_lambda': 0.0005717013126231479, 'max_delta_step': 7}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:38:41,469] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.24464722721456328, 'n_estimators': 1094, 'subsample': 0.6427685883274608, 'colsample_bytree': 0.7991173172495378, 'min_child_weight': 6, 'gamma': 4.807722550321074, 'reg_alpha': 0.00010348002296309102, 'reg_lambda': 0.0010475051357266892, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  63%|██████▎   | 126/200 [01:35<00:52,  1.42it/s]

[I 2025-11-10 18:38:41,665] Trial 122 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2992791927663195, 'n_estimators': 1158, 'subsample': 0.9806291632313798, 'colsample_bytree': 0.7821056633288918, 'min_child_weight': 6, 'gamma': 2.459152897107678, 'reg_alpha': 0.07631285178041107, 'reg_lambda': 0.007685557038383516, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  64%|██████▎   | 127/200 [01:36<00:52,  1.40it/s]

[I 2025-11-10 18:38:42,406] Trial 128 pruned.
[I 2025-11-10 18:38:42,429] Trial 127 pruned.

Best trial: 5. Best value: 0.572144:  64%|██████▍   | 129/200 [01:36<00:31,  2.25it/s]

[I 2025-11-10 18:38:42,639] Trial 129 pruned.

Best trial: 5. Best value: 0.572144:  65%|██████▌   | 130/200 [01:37<00:37,  1.86it/s]

[I 2025-11-10 18:38:43,467] Trial 126 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.014051198499569276, 'n_estimators': 905, 'subsample': 0.6399126928233001, 'colsample_bytree': 0.7985922407459329, 'min_child_weight': 6, 'gamma': 3.1493216326897184, 'reg_alpha': 0.006512086167610269, 'reg_lambda': 0.0005157900392269817, 'max_delta_step': 4}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:38:43,489] Trial 131 pruned.

Best trial: 5. Best value: 0.572144:  66%|██████▌   | 132/200 [01:40<01:09,  1.02s/it]

[I 2025-11-10 18:38:46,871] Trial 130 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.043811948130357006, 'n_estimators': 943, 'subsample': 0.8159083933010381, 'colsample_bytree': 0.877954418101671, 'min_child_weight': 8, 'gamma': 3.3247696983987463, 'reg_alpha': 0.0018103613623106523, 'reg_lambda': 0.02568358925304305, 'max_delta_step': 6}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  66%|██████▋   | 133/200 [01:41<01:03,  1.05it/s]

[I 2025-11-10 18:38:47,608] Trial 132 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.22046610238892111, 'n_estimators': 1116, 'subsample': 0.6641012198679211, 'colsample_bytree': 0.677635901209745, 'min_child_weight': 8, 'gamma': 3.1869570204649382, 'reg_alpha': 0.001933432709539402, 'reg_lambda': 0.07259669328360586, 'max_delta_step': 6}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  67%|██████▋   | 134/200 [01:41<00:53,  1.24it/s]

[I 2025-11-10 18:38:47,954] Trial 134 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.2555268904588674, 'n_estimators': 1050, 'subsample': 0.5311952875756727, 'colsample_bytree': 0.5543964472185449, 'min_child_weight': 10, 'gamma': 1.788694454986937, 'reg_alpha': 5.301754469019245e-08, 'reg_lambda': 0.019749594122743568, 'max_delta_step': 9}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  68%|██████▊   | 135/200 [01:42<00:52,  1.23it/s]

[I 2025-11-10 18:38:48,784] Trial 137 pruned.

Best trial: 5. Best value: 0.572144:  68%|██████▊   | 136/200 [01:42<00:42,  1.51it/s]

[I 2025-11-10 18:38:49,041] Trial 133 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.043939388267862485, 'n_estimators': 1247, 'subsample': 0.6977818010126227, 'colsample_bytree': 0.6750151175191951, 'min_child_weight': 8, 'gamma': 2.1075112254431763, 'reg_alpha': 2.6493174063059327e-06, 'reg_lambda': 0.0698824264355559, 'max_delta_step': 6}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  68%|██████▊   | 137/200 [01:43<00:35,  1.79it/s]

[I 2025-11-10 18:38:49,333] Trial 138 pruned.

Best trial: 5. Best value: 0.572144:  69%|██████▉   | 138/200 [01:44<00:49,  1.26it/s]

[I 2025-11-10 18:38:50,714] Trial 140 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.14264766803216034, 'n_estimators': 293, 'subsample': 0.6087145353086192, 'colsample_bytree': 0.7375953066510549, 'min_child_weight': 7, 'gamma': 3.8503622343188693, 'reg_alpha': 2.8549671401692523e-08, 'reg_lambda': 3.0198610978564052e-05, 'max_delta_step': 7}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  70%|██████▉   | 139/200 [01:45<00:52,  1.16it/s]

[I 2025-11-10 18:38:51,747] Trial 135 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.14190797923720927, 'n_estimators': 1107, 'subsample': 0.8368550387307719, 'colsample_bytree': 0.5532907973302225, 'min_child_weight': 10, 'gamma': 1.78588739616068, 'reg_alpha': 1.4839192382928465e-07, 'reg_lambda': 0.06877203056234873, 'max_delta_step': 8}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  70%|███████   | 140/200 [01:46<00:55,  1.08it/s]

[I 2025-11-10 18:38:52,834] Trial 136 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.25862742722018517, 'n_estimators': 1182, 'subsample': 0.548915835440736, 'colsample_bytree': 0.5457340449485171, 'min_child_weight': 10, 'gamma': 2.113206796165313, 'reg_alpha': 0.0006241764472853476, 'reg_lambda': 0.011566422532342151, 'max_delta_step': 9}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  70%|███████   | 141/200 [01:47<00:52,  1.12it/s]

[I 2025-11-10 18:38:53,624] Trial 139 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.2935980737203096, 'n_estimators': 997, 'subsample': 0.5090468129946902, 'colsample_bytree': 0.726207694127259, 'min_child_weight': 10, 'gamma': 3.857992770671944, 'reg_alpha': 0.0006130018845950598, 'reg_lambda': 8.495977458970781e-08, 'max_delta_step': 8}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  71%|███████   | 142/200 [01:49<01:06,  1.14s/it]

[I 2025-11-10 18:38:55,382] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.020190477520864537, 'n_estimators': 1038, 'subsample': 0.5521045511096205, 'colsample_bytree': 0.7188016403729773, 'min_child_weight': 10, 'gamma': 3.6352327444988246, 'reg_alpha': 0.0010657473244487146, 'reg_lambda': 0.011755046978479509, 'max_delta_step': 9}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  72%|███████▏  | 143/200 [01:50<01:01,  1.09s/it]

[I 2025-11-10 18:38:56,328] Trial 145 pruned.
[I 2025-11-10 18:38:56,370] Trial 142 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.24005506393282636, 'n_estimators': 1036, 'subsample': 0.5142457926472588, 'colsample_bytree': 0.7121456546067744, 'min_child_weight': 5, 'gamma': 3.692681846044103, 'reg_alpha': 0.0013315816031840748, 'reg_lambda': 8.060214622058718e-08, 'max_delta_step': 1}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  72%|███████▎  | 145/200 [01:51<00:48,  1.12it/s]

[I 2025-11-10 18:38:57,649] Trial 143 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.020195511378703748, 'n_estimators': 1044, 'subsample': 0.5750344098233137, 'colsample_bytree': 0.7074145934471953, 'min_child_weight': 5, 'gamma': 3.697405912959189, 'reg_alpha': 8.356636443050753e-08, 'reg_lambda': 0.006054687307396828, 'max_delta_step': 1}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  73%|███████▎  | 146/200 [01:52<00:51,  1.06it/s]

[I 2025-11-10 18:38:58,762] Trial 148 pruned.

Best trial: 5. Best value: 0.572144:  74%|███████▎  | 147/200 [01:53<00:47,  1.12it/s]

[I 2025-11-10 18:38:59,512] Trial 144 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.19514515556424294, 'n_estimators': 1331, 'subsample': 0.5046554601198269, 'colsample_bytree': 0.5199571228086431, 'min_child_weight': 4, 'gamma': 2.6822713326107284, 'reg_alpha': 0.03128800986223019, 'reg_lambda': 0.0064064934376199655, 'max_delta_step': 8}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  74%|███████▍  | 148/200 [01:53<00:41,  1.26it/s]

[I 2025-11-10 18:39:00,030] Trial 149 pruned.

Best trial: 5. Best value: 0.572144:  74%|███████▍  | 149/200 [01:54<00:41,  1.21it/s]

[I 2025-11-10 18:39:00,933] Trial 150 pruned.

Best trial: 5. Best value: 0.572144:  75%|███████▌  | 150/200 [01:55<00:39,  1.26it/s]

[I 2025-11-10 18:39:01,662] Trial 147 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.17016787702631955, 'n_estimators': 1239, 'subsample': 0.5378764165155699, 'colsample_bytree': 0.5237225251765101, 'min_child_weight': 4, 'gamma': 2.698204085352702, 'reg_alpha': 0.016108610423886643, 'reg_lambda': 0.2894135073977919, 'max_delta_step': 7}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  76%|███████▌  | 151/200 [01:55<00:31,  1.56it/s]

[I 2025-11-10 18:39:01,929] Trial 151 pruned.

Best trial: 5. Best value: 0.572144:  76%|███████▌  | 152/200 [01:56<00:29,  1.62it/s]

[I 2025-11-10 18:39:02,481] Trial 146 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.23511230605260255, 'n_estimators': 1324, 'subsample': 0.5100429736246579, 'colsample_bytree': 0.8696824219027259, 'min_child_weight': 5, 'gamma': 3.0168287992515674, 'reg_alpha': 0.032519325262931664, 'reg_lambda': 0.2769351325576497, 'max_delta_step': 7}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  76%|███████▋  | 153/200 [01:57<00:31,  1.49it/s]

[I 2025-11-10 18:39:03,279] Trial 152 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.09931694797697445, 'n_estimators': 486, 'subsample': 0.5927076174848845, 'colsample_bytree': 0.8980841587707686, 'min_child_weight': 9, 'gamma': 1.3787746332164277, 'reg_alpha': 0.5423600290411691, 'reg_lambda': 0.3244052734935725, 'max_delta_step': 2}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  78%|███████▊  | 155/200 [02:01<00:56,  1.26s/it]

[I 2025-11-10 18:39:07,565] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1560783554910668, 'n_estimators': 1279, 'subsample': 0.5001099614536777, 'colsample_bytree': 0.5131159325399574, 'min_child_weight': 4, 'gamma': 2.2233503418505447, 'reg_alpha': 0.05150200326212149, 'reg_lambda': 0.018656059941846454, 'max_delta_step': 8}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:39:07,691] Trial 154 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.159233293142921, 'n_estimators': 1399, 'subsample': 0.5202266215156562, 'colsample_bytree': 0.5071254050738001, 'min_child_weight': 4, 'gamma': 4.327171607344586, 'reg_alpha': 0.04317793566168601, 'reg_lambda': 0.00022556822397244456, 'max_delta_step': 9}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  78%|███████▊  | 156/200 [02:01<00:45,  1.04s/it]

[I 2025-11-10 18:39:08,215] Trial 153 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.12465756134511309, 'n_estimators': 1400, 'subsample': 0.7351016526711667, 'colsample_bytree': 0.9638321702959117, 'min_child_weight': 5, 'gamma': 0.9712823893732654, 'reg_alpha': 0.6105975269106683, 'reg_lambda': 0.00019365669715922751, 'max_delta_step': 2}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  78%|███████▊  | 157/200 [02:02<00:35,  1.21it/s]

[I 2025-11-10 18:39:08,546] Trial 158 pruned.

[I 2025-11-10 18:39:09,143] Trial 156 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.27132606413176835, 'n_estimators': 1404, 'subsample': 0.5245533435156995, 'colsample_bytree': 0.50101335895051, 'min_child_weight': 4, 'gamma': 2.2193155441689454, 'reg_alpha': 0.20351111222545756, 'reg_lambda': 0.00019531120120320036, 'max_delta_step': 8}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  80%|███████▉  | 159/200 [02:03<00:24,  1.70it/s]

[I 2025-11-10 18:39:09,329] Trial 159 pruned.

Best trial: 5. Best value: 0.572144:  80%|████████  | 160/200 [02:03<00:20,  1.93it/s]

[I 2025-11-10 18:39:09,682] Trial 160 finished with value: 0.5031578947368421 and parameters: {'max_depth': 7, 'learning_rate': 0.27440261950674355, 'n_estimators': 203, 'subsample': 0.5831759859257052, 'colsample_bytree': 0.9310774907648567, 'min_child_weight': 4, 'gamma': 3.2983251569413996, 'reg_alpha': 0.0035215454143916677, 'reg_lambda': 1.9116310300401416e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  80%|████████  | 161/200 [02:04<00:31,  1.24it/s]

[I 2025-11-10 18:39:11,169] Trial 163 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.2535465319016773, 'n_estimators': 299, 'subsample': 0.5802227408114359, 'colsample_bytree': 0.9271315867850385, 'min_child_weight': 7, 'gamma': 3.3453163339085883, 'reg_alpha': 0.003729421928761247, 'reg_lambda': 2.0176650131843987e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  81%|████████  | 162/200 [02:05<00:24,  1.58it/s]

[I 2025-11-10 18:39:11,395] Trial 162 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.13298270761444564, 'n_estimators': 413, 'subsample': 0.5829452879181017, 'colsample_bytree': 0.7908897629899355, 'min_child_weight': 7, 'gamma': 2.618223553655327, 'reg_alpha': 0.0001535400627316113, 'reg_lambda': 6.519491904624872e-07, 'max_delta_step': 9}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  82%|████████▏ | 163/200 [02:05<00:19,  1.91it/s]

[I 2025-11-10 18:39:11,664] Trial 165 pruned.

Best trial: 5. Best value: 0.572144:  82%|████████▏ | 164/200 [02:06<00:21,  1.66it/s]

[I 2025-11-10 18:39:12,450] Trial 164 finished with value: 0.5387719298245613 and parameters: {'max_depth': 7, 'learning_rate': 0.017516894137597404, 'n_estimators': 222, 'subsample': 0.610806143616832, 'colsample_bytree': 0.8873192765816114, 'min_child_weight': 4, 'gamma': 2.5783138435060753, 'reg_alpha': 0.00874171540715335, 'reg_lambda': 1.6574321561801203e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  83%|████████▎ | 166/200 [02:07<00:21,  1.62it/s]

[I 2025-11-10 18:39:13,797] Trial 167 finished with value: 0.5387719298245613 and parameters: {'max_depth': 7, 'learning_rate': 0.01581804776771032, 'n_estimators': 268, 'subsample': 0.6127790318130343, 'colsample_bytree': 0.8836158264124869, 'min_child_weight': 4, 'gamma': 3.4007487704975463, 'reg_alpha': 0.00378782237197091, 'reg_lambda': 2.3549171760932855e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:39:13,932] Trial 157 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.12203985445416457, 'n_estimators': 1401, 'subsample': 0.5203443939335908, 'colsample_bytree': 0.5116991869382275, 'min_child_weight': 4, 'gamma': 4.316274381320248, 'reg_alpha': 0.00017314952308716708, 'reg_lambda': 0.00022834508194303967, 'max_delta_step': 9}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  84%|████████▎ | 167/200 [02:08<00:17,  1.88it/s]

[I 2025-11-10 18:39:14,261] Trial 166 finished with value: 0.5227485380116959 and parameters: {'max_depth': 7, 'learning_rate': 0.018827177879283983, 'n_estimators': 561, 'subsample': 0.609143537295629, 'colsample_bytree': 0.5321830528627293, 'min_child_weight': 4, 'gamma': 3.26729281730969, 'reg_alpha': 0.06681136428999593, 'reg_lambda': 0.00011268144201896116, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  84%|████████▍ | 169/200 [02:08<00:14,  2.17it/s]

[I 2025-11-10 18:39:14,988] Trial 161 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.05096798372658726, 'n_estimators': 1178, 'subsample': 0.657814364259272, 'colsample_bytree': 0.8865492415244212, 'min_child_weight': 7, 'gamma': 2.559489189640422, 'reg_alpha': 1.4630964837647315e-06, 'reg_lambda': 8.918440464038014e-05, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:39:15,145] Trial 168 finished with value: 0.5387719298245613 and parameters: {'max_depth': 7, 'learning_rate': 0.017481243488609317, 'n_estimators': 234, 'subsample': 0.6118867779030539, 'colsample_bytree': 0.8861810235065164, 'min_child_weight': 4, 'gamma': 3.3923692925041866, 'reg_alpha': 0.004534142794767613, 'reg_lambda': 1.468615142091145e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  84%|████████▍ | 169/200 [02:09<00:14,  2.17it/s]

[I 2025-11-10 18:39:15,232] Trial 169 finished with value: 0.5387719298245613 and parameters: {'max_depth': 7, 'learning_rate': 0.013792171638261342, 'n_estimators': 216, 'subsample': 0.6109956140115461, 'colsample_bytree': 0.8951047324307362, 'min_child_weight': 4, 'gamma': 3.2919700325223102, 'reg_alpha': 0.0029433503162559172, 'reg_lambda': 2.1781009451404247e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  86%|████████▌ | 171/200 [02:09<00:10,  2.74it/s]

[I 2025-11-10 18:39:15,651] Trial 170 finished with value: 0.5409941520467837 and parameters: {'max_depth': 7, 'learning_rate': 0.016340992679641363, 'n_estimators': 242, 'subsample': 0.6138099500551008, 'colsample_bytree': 0.8888759292620328, 'min_child_weight': 4, 'gamma': 3.30577721977349, 'reg_alpha': 0.0031246778816707583, 'reg_lambda': 1.7447013506503218e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  86%|████████▌ | 172/200 [02:10<00:12,  2.18it/s]

[I 2025-11-10 18:39:16,401] Trial 171 finished with value: 0.5387719298245613 and parameters: {'max_depth': 7, 'learning_rate': 0.017123752630164944, 'n_estimators': 242, 'subsample': 0.6086347744261156, 'colsample_bytree': 0.8874949264643945, 'min_child_weight': 4, 'gamma': 3.246689202544708, 'reg_alpha': 0.00262242102419338, 'reg_lambda': 1.7827366263868854e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:39:16,484] Trial 172 finished with value: 0.5409941520467837 and parameters: {'max_depth': 7, 'learning_rate': 0.017412527467527285, 'n_estimators': 231, 'subsample': 0.6135890784829342, 'colsample_bytree': 0.881923285717234, 'min_child_weight': 4, 'gamma': 3.316687283930094, 'reg_alpha': 0.0039489726804427935, 'reg_lambda': 1.0112219672848723e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  87%|████████▋ | 174/200 [02:10<00:08,  3.11it/s]

[I 2025-11-10 18:39:16,652] Trial 173 finished with value: 0.5387719298245613 and parameters: {'max_depth': 7, 'learning_rate': 0.013292425632428388, 'n_estimators': 243, 'subsample': 0.6109194443956255, 'colsample_bytree': 0.8838140876608376, 'min_child_weight': 4, 'gamma': 3.241579620054576, 'reg_alpha': 0.00350423322850424, 'reg_lambda': 1.3758961620403505e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  88%|████████▊ | 175/200 [02:10<00:08,  3.03it/s]

[I 2025-11-10 18:39:17,011] Trial 174 finished with value: 0.5387719298245613 and parameters: {'max_depth': 7, 'learning_rate': 0.017300322722452608, 'n_estimators': 234, 'subsample': 0.6124942991256515, 'colsample_bytree': 0.8836613277444811, 'min_child_weight': 4, 'gamma': 3.3543103793717393, 'reg_alpha': 0.004577713758869455, 'reg_lambda': 1.2808770643659721e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  88%|████████▊ | 176/200 [02:11<00:10,  2.25it/s]

[I 2025-11-10 18:39:17,802] Trial 176 finished with value: 0.5387719298245613 and parameters: {'max_depth': 7, 'learning_rate': 0.017269592551011147, 'n_estimators': 238, 'subsample': 0.6090191203371605, 'colsample_bytree': 0.8954970382165666, 'min_child_weight': 4, 'gamma': 3.22846259653885, 'reg_alpha': 0.003647753593721531, 'reg_lambda': 1.4013947936307934e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:39:17,868] Trial 175 finished with value: 0.5387719298245613 and parameters: {'max_depth': 7, 'learning_rate': 0.01740949812172692, 'n_estimators': 243, 'subsample': 0.612936931289383, 'colsample_bytree': 0.8935707358914017, 'min_child_weight': 4, 'gamma': 3.258971720784289, 'reg_alpha': 0.0033959545780237565, 'reg_lambda': 1.4161690641566733e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  89%|████████▉ | 178/200 [02:11<00:07,  3.13it/s]

[I 2025-11-10 18:39:18,088] Trial 177 finished with value: 0.5387719298245613 and parameters: {'max_depth': 7, 'learning_rate': 0.013846932884868537, 'n_estimators': 251, 'subsample': 0.6127862382047584, 'colsample_bytree': 0.8808065300721997, 'min_child_weight': 4, 'gamma': 3.2610210370870885, 'reg_alpha': 0.003293227713760069, 'reg_lambda': 1.1423841941353227e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  90%|████████▉ | 179/200 [02:12<00:06,  3.10it/s]

[I 2025-11-10 18:39:18,423] Trial 178 finished with value: 0.5409941520467837 and parameters: {'max_depth': 7, 'learning_rate': 0.014107565825410753, 'n_estimators': 243, 'subsample': 0.6146996698689974, 'colsample_bytree': 0.8957170267901147, 'min_child_weight': 4, 'gamma': 3.2445554395603486, 'reg_alpha': 0.0031248491332691573, 'reg_lambda': 1.0198512154471662e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  90%|█████████ | 181/200 [02:13<00:06,  2.88it/s]

[I 2025-11-10 18:39:19,198] Trial 179 finished with value: 0.5387719298245613 and parameters: {'max_depth': 7, 'learning_rate': 0.014021919012307664, 'n_estimators': 245, 'subsample': 0.613429419614052, 'colsample_bytree': 0.8801715735575071, 'min_child_weight': 4, 'gamma': 3.2253488470112748, 'reg_alpha': 0.004881512611293418, 'reg_lambda': 1.1243661939565067e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:39:19,299] Trial 180 finished with value: 0.5387719298245613 and parameters: {'max_depth': 7, 'learning_rate': 0.014081823471704977, 'n_estimators': 241, 'subsample': 0.6120235081985299, 'colsample_bytree': 0.8822638736327183, 'min_child_weight': 4, 'gamma': 3.2312243972842256, 'reg_alpha': 0.0028283382420003973, 'reg_lambda': 1.1383982301228812e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  91%|█████████ | 182/200 [02:13<00:05,  3.33it/s]

[I 2025-11-10 18:39:19,473] Trial 181 finished with value: 0.5409941520467837 and parameters: {'max_depth': 7, 'learning_rate': 0.013728835318738123, 'n_estimators': 243, 'subsample': 0.614763732962219, 'colsample_bytree': 0.8788493386155964, 'min_child_weight': 4, 'gamma': 3.2313693661128213, 'reg_alpha': 0.004998812147814143, 'reg_lambda': 1.0609753574372947e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  92%|█████████▏| 183/200 [02:13<00:05,  3.26it/s]

[I 2025-11-10 18:39:19,798] Trial 182 finished with value: 0.5354385964912282 and parameters: {'max_depth': 7, 'learning_rate': 0.0133368852186049, 'n_estimators': 243, 'subsample': 0.6174881052078354, 'colsample_bytree': 0.8952725934606424, 'min_child_weight': 4, 'gamma': 3.0918191463616855, 'reg_alpha': 0.005229718990572482, 'reg_lambda': 1.0174023408847628e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  92%|█████████▏| 184/200 [02:14<00:06,  2.32it/s]

[I 2025-11-10 18:39:20,541] Trial 183 finished with value: 0.5409941520467837 and parameters: {'max_depth': 7, 'learning_rate': 0.01166267558483669, 'n_estimators': 236, 'subsample': 0.6152545711941655, 'colsample_bytree': 0.8818587116374544, 'min_child_weight': 4, 'gamma': 3.1233400413160655, 'reg_alpha': 0.004714628105274709, 'reg_lambda': 1.1099980466312374e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  93%|█████████▎| 186/200 [02:14<00:04,  3.37it/s]

[I 2025-11-10 18:39:20,722] Trial 184 finished with value: 0.5354385964912282 and parameters: {'max_depth': 7, 'learning_rate': 0.013706797634095881, 'n_estimators': 244, 'subsample': 0.6215289759832339, 'colsample_bytree': 0.880083220908429, 'min_child_weight': 4, 'gamma': 3.093646909305277, 'reg_alpha': 0.005212442811154228, 'reg_lambda': 1.0709135867808313e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:39:20,869] Trial 185 finished with value: 0.5354385964912282 and parameters: {'max_depth': 7, 'learning_rate': 0.01109738788979612, 'n_estimators': 237, 'subsample': 0.6216444878830544, 'colsample_bytree': 0.8817732528750276, 'min_child_weight': 4, 'gamma': 3.2255515767591274, 'reg_alpha': 0.002666445583635976, 'reg_lambda': 1.0720331392141242e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  94%|█████████▎| 187/200 [02:14<00:04,  3.25it/s]

[I 2025-11-10 18:39:21,202] Trial 186 finished with value: 0.5387719298245613 and parameters: {'max_depth': 7, 'learning_rate': 0.011316583361722208, 'n_estimators': 244, 'subsample': 0.60213853138774, 'colsample_bytree': 0.8819100613421641, 'min_child_weight': 4, 'gamma': 3.2168492081506765, 'reg_alpha': 0.003105421564405725, 'reg_lambda': 1.36827645733791e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  94%|█████████▍| 188/200 [02:15<00:03,  3.19it/s]

[I 2025-11-10 18:39:21,530] Trial 190 pruned.

Best trial: 5. Best value: 0.572144:  94%|█████████▍| 189/200 [02:15<00:04,  2.73it/s]

[I 2025-11-10 18:39:22,023] Trial 187 finished with value: 0.5250877192982456 and parameters: {'max_depth': 7, 'learning_rate': 0.011499095002781014, 'n_estimators': 254, 'subsample': 0.5994586013781522, 'colsample_bytree': 0.8649306255729908, 'min_child_weight': 4, 'gamma': 3.359224429728829, 'reg_alpha': 0.002894241953693876, 'reg_lambda': 1.624595546110613e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  96%|█████████▌| 191/200 [02:16<00:02,  3.53it/s]

[I 2025-11-10 18:39:22,317] Trial 188 finished with value: 0.5250877192982456 and parameters: {'max_depth': 7, 'learning_rate': 0.010773593763812896, 'n_estimators': 275, 'subsample': 0.599421086650514, 'colsample_bytree': 0.864214654957818, 'min_child_weight': 4, 'gamma': 3.3652732471954923, 'reg_alpha': 0.002762912821776693, 'reg_lambda': 1.6147277033237276e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:39:22,457] Trial 189 finished with value: 0.5250877192982456 and parameters: {'max_depth': 7, 'learning_rate': 0.011786811455360514, 'n_estimators': 277, 'subsample': 0.5995528759938672, 'colsample_bytree': 0.8655102391735544, 'min_child_weight': 4, 'gamma': 3.4002689952054084, 'reg_alpha': 0.007170762510999183, 'reg_lambda': 1.932115474849928e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  96%|█████████▌| 192/200 [02:17<00:03,  2.25it/s]

[I 2025-11-10 18:39:23,275] Trial 191 finished with value: 0.5587719298245614 and parameters: {'max_depth': 7, 'learning_rate': 0.012107611140871766, 'n_estimators': 317, 'subsample': 0.6018064837381462, 'colsample_bytree': 0.902735753325738, 'min_child_weight': 4, 'gamma': 3.412508278982442, 'reg_alpha': 0.007413319760346358, 'reg_lambda': 3.6864974187095176e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  96%|█████████▋| 193/200 [02:17<00:03,  2.28it/s]

[I 2025-11-10 18:39:23,702] Trial 192 finished with value: 0.5387719298245613 and parameters: {'max_depth': 7, 'learning_rate': 0.012557259962085551, 'n_estimators': 309, 'subsample': 0.6107287865622836, 'colsample_bytree': 0.9006477736479814, 'min_child_weight': 4, 'gamma': 3.448020279928814, 'reg_alpha': 0.007724457647698167, 'reg_lambda': 3.9870847810962606e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  98%|█████████▊| 196/200 [02:17<00:00,  4.12it/s]

[I 2025-11-10 18:39:24,034] Trial 193 finished with value: 0.5587719298245614 and parameters: {'max_depth': 7, 'learning_rate': 0.01262095623398108, 'n_estimators': 317, 'subsample': 0.6120414166988338, 'colsample_bytree': 0.9046032115665836, 'min_child_weight': 4, 'gamma': 3.4169954833476317, 'reg_alpha': 0.0016994568622828439, 'reg_lambda': 3.78621496278055e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:39:24,123] Trial 196 pruned.
[I 2025-11-10 18:39:24,133] Trial 194 finished with value: 0.5587719298245614 and parameters: {'max_depth': 7, 'learning_rate': 0.01467643629371439, 'n_estimators': 315, 'subsample': 0.611893084906483, 'colsample_bytree': 0.9010217792386899, 'min_child_weight': 4, 'gamma': 3.2002143686946107, 'reg_alpha': 0.0015985633908480994, 'reg_lambda': 4.338838954286876e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144:  98%|█████████▊| 197/200 [02:18<00:00,  3.66it/s]

[I 2025-11-10 18:39:24,501] Trial 197 pruned.

Best trial: 5. Best value: 0.572144:  99%|█████████▉| 198/200 [02:18<00:00,  3.11it/s]

[I 2025-11-10 18:39:24,961] Trial 195 finished with value: 0.5587719298245614 and parameters: {'max_depth': 7, 'learning_rate': 0.014932983989467383, 'n_estimators': 330, 'subsample': 0.6101664052965879, 'colsample_bytree': 0.9030591753681065, 'min_child_weight': 4, 'gamma': 3.4728740829011167, 'reg_alpha': 0.0017515258143668364, 'reg_lambda': 4.2850259972947435e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.
[I 2025-11-10 18:39:25,061] Trial 199 finished with value: 0.5476023391812866 and parameters: {'max_depth': 7, 'learning_rate': 0.0176554188811097, 'n_estimators': 215, 'subsample': 0.5892393145860102, 'colsample_bytree': 0.9113051099300152, 'min_child_weight': 4, 'gamma': 3.451355928917035, 'reg_alpha': 0.001501979966309827, 'reg_lambda': 3.961471515582759e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

Best trial: 5. Best value: 0.572144: 100%|██████████| 200/200 [02:19<00:00,  1.44it/s]

[I 2025-11-10 18:39:25,305] Trial 198 finished with value: 0.5331578947368422 and parameters: {'max_depth': 7, 'learning_rate': 0.017158739311118523, 'n_estimators': 316, 'subsample': 0.5912669341149568, 'colsample_bytree': 0.910540081495546, 'min_child_weight': 4, 'gamma': 3.458827953429539, 'reg_alpha': 0.0018001353042327673, 'reg_lambda': 4.369166547238962e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5721442495126705.

[I 2025-11-10 18:39:26,471] A new study created in memory with name: 3_2_roc_auc
Best trial: 1. Best value: 0.5:   0%|          | 1/200 [00:01<06:05,  1.84s/it]

[I 2025-11-10 18:39:28,302] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.013870720430933875, 'n_estimators': 455, 'subsample': 0.7279483802490034, 'colsample_bytree': 0.5581945438548339, 'min_child_weight': 10, 'gamma': 4.380134612070004, 'reg_alpha': 0.02805254066324669, 'reg_lambda': 0.07701713249795757, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:39:28,305] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.12417179849157613, 'n_estimators': 446, 'subsample': 0.8304298100293726, 'colsample_bytree': 0.6102773362205045, 'min_child_weight': 8, 'gamma': 2.7404579916915965, 'reg_alpha': 7.882901834768925e-06, 'reg_lambda': 3.8230028429001205e-08, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   2%|▏         | 3/200 [00:02<01:48,  1.81it/s]

[I 2025-11-10 18:39:28,509] Trial 0 finished with value: 0.36289473684210527 and parameters: {'max_depth': 9, 'learning_rate': 0.09098703837906989, 'n_estimators': 470, 'subsample': 0.6542745886736734, 'colsample_bytree': 0.7096547470214363, 'min_child_weight': 4, 'gamma': 3.6680417292892384, 'reg_alpha': 0.005425502414941427, 'reg_lambda': 0.11467820940923416, 'max_delta_step': 2}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   2%|▏         | 4/200 [00:02<02:10,  1.50it/s]

[I 2025-11-10 18:39:29,395] Trial 3 finished with value: 0.42222222222222217 and parameters: {'max_depth': 8, 'learning_rate': 0.01633413106605773, 'n_estimators': 321, 'subsample': 0.9762389750826397, 'colsample_bytree': 0.7134764013739536, 'min_child_weight': 3, 'gamma': 0.23854552424706854, 'reg_alpha': 2.0675553396092104e-08, 'reg_lambda': 2.957726628213532, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   2%|▎         | 5/200 [00:04<03:17,  1.01s/it]

[I 2025-11-10 18:39:31,104] Trial 6 finished with value: 0.4232163742690059 and parameters: {'max_depth': 7, 'learning_rate': 0.10019833537787158, 'n_estimators': 559, 'subsample': 0.8911906720284962, 'colsample_bytree': 0.5132394944683281, 'min_child_weight': 3, 'gamma': 2.100477266144434, 'reg_alpha': 0.9746131412530171, 'reg_lambda': 0.0002661852989586474, 'max_delta_step': 1}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   3%|▎         | 6/200 [00:06<04:09,  1.29s/it]

[I 2025-11-10 18:39:32,975] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07018241730938327, 'n_estimators': 991, 'subsample': 0.5007419423798747, 'colsample_bytree': 0.5900623308733064, 'min_child_weight': 10, 'gamma': 4.21632349948947, 'reg_alpha': 0.07878702418367449, 'reg_lambda': 5.4985226356043243e-08, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   4%|▎         | 7/200 [00:08<04:48,  1.50s/it]

[I 2025-11-10 18:39:34,930] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.014348861468285925, 'n_estimators': 999, 'subsample': 0.6362704741468703, 'colsample_bytree': 0.7905362933535541, 'min_child_weight': 10, 'gamma': 2.81123024647913, 'reg_alpha': 0.005191049716385775, 'reg_lambda': 2.8855569522328173e-07, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   4%|▍         | 8/200 [00:09<04:22,  1.37s/it]

[I 2025-11-10 18:39:36,006] Trial 4 finished with value: 0.40504873294346977 and parameters: {'max_depth': 6, 'learning_rate': 0.015422907584536755, 'n_estimators': 1441, 'subsample': 0.8428196660241772, 'colsample_bytree': 0.7301156785548596, 'min_child_weight': 3, 'gamma': 1.040755129508677, 'reg_alpha': 2.132491875168803e-06, 'reg_lambda': 1.584879403726121e-08, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   6%|▌         | 11/200 [00:10<02:21,  1.33it/s]

[I 2025-11-10 18:39:37,329] Trial 11 finished with value: 0.41730019493177384 and parameters: {'max_depth': 5, 'learning_rate': 0.2043739964265283, 'n_estimators': 291, 'subsample': 0.9881261866371367, 'colsample_bytree': 0.9004531515872911, 'min_child_weight': 5, 'gamma': 1.8855315236286996, 'reg_alpha': 1.269132640147985e-06, 'reg_lambda': 1.1974661426505153, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:39:37,409] Trial 5 finished with value: 0.360224171539961 and parameters: {'max_depth': 10, 'learning_rate': 0.21174288668973246, 'n_estimators': 1491, 'subsample': 0.9226973251880901, 'colsample_bytree': 0.9934338496013634, 'min_child_weight': 2, 'gamma': 3.06481673265818, 'reg_alpha': 7.178609909034614e-07, 'reg_lambda': 1.0687789747826619e-08, 'max_delta_step': 2}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:39:37,433] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.16090780924000228, 'n_estimators': 1213, 'subsample': 0.5538431439055742, 'colsample_bytree': 0.6107425416782589, 'min_child_weight': 7, 'gamma': 0.33197826550827425, 'reg_alpha': 1.0811733754522056e-07, 'reg_lambda': 1.3959985993174622e-06, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   6%|▌         | 12/200 [00:11<02:20,  1.34it/s]

[I 2025-11-10 18:39:38,190] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.08588774187020119, 'n_estimators': 764, 'subsample': 0.8734713374783168, 'colsample_bytree': 0.875451685983786, 'min_child_weight': 10, 'gamma': 4.93322022411999, 'reg_alpha': 7.390475034978139e-08, 'reg_lambda': 7.267535236460543e-05, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   6%|▋         | 13/200 [00:11<01:55,  1.61it/s]

[I 2025-11-10 18:39:38,454] Trial 12 pruned.

Best trial: 1. Best value: 0.5:   7%|▋         | 14/200 [00:13<02:54,  1.07it/s]

[I 2025-11-10 18:39:40,235] Trial 13 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03153389475980151, 'n_estimators': 682, 'subsample': 0.7292533818046393, 'colsample_bytree': 0.509923816135065, 'min_child_weight': 7, 'gamma': 4.758285324920747, 'reg_alpha': 4.558739268121272, 'reg_lambda': 0.0030274913527784577, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:39:40,256] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.038024225361471466, 'n_estimators': 690, 'subsample': 0.7687747071456064, 'colsample_bytree': 0.5137689961433319, 'min_child_weight': 8, 'gamma': 4.9537803151827084, 'reg_alpha': 6.741781185204754e-05, 'reg_lambda': 0.0009164693071906119, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   8%|▊         | 16/200 [00:14<01:59,  1.54it/s]

[I 2025-11-10 18:39:40,793] Trial 15 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.02587186727368684, 'n_estimators': 627, 'subsample': 0.7500355512737304, 'colsample_bytree': 0.5063277493222076, 'min_child_weight': 8, 'gamma': 4.941226306924953, 'reg_alpha': 8.146672345436856e-05, 'reg_lambda': 0.014176933417035168, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  10%|▉         | 19/200 [00:14<01:10,  2.57it/s]

[I 2025-11-10 18:39:41,247] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.033505111777662126, 'n_estimators': 652, 'subsample': 0.7701724393094781, 'colsample_bytree': 0.5025929915816687, 'min_child_weight': 8, 'gamma': 4.8970527047487495, 'reg_alpha': 0.00011807078648168934, 'reg_lambda': 0.005322955465165677, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:39:41,344] Trial 17 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.03338868062175872, 'n_estimators': 217, 'subsample': 0.790642250259378, 'colsample_bytree': 0.5694110460111179, 'min_child_weight': 8, 'gamma': 3.8632648456381773, 'reg_alpha': 0.00013067675042181318, 'reg_lambda': 7.709555613072452e-06, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:39:41,399] Trial 18 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.0283495381743474, 'n_estimators': 221, 'subsample': 0.795377218722903, 'colsample_bytree': 0.6431307531843445, 'min_child_weight': 8, 'gamma': 3.678849153160916, 'reg_alpha': 0.0009922864910589144, 'reg_lambda': 6.35300363450277e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  10%|█         | 20/200 [00:15<01:14,  2.41it/s]

[I 2025-11-10 18:39:41,902] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.14421868289930018, 'n_estimators': 202, 'subsample': 0.8138081577170347, 'colsample_bytree': 0.6578777567948685, 'min_child_weight': 8, 'gamma': 3.610788665697882, 'reg_alpha': 0.001839923376894983, 'reg_lambda': 7.04236562407691e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  11%|█         | 22/200 [00:16<01:27,  2.02it/s]

[I 2025-11-10 18:39:43,201] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01066574254072619, 'n_estimators': 415, 'subsample': 0.8292671397637165, 'colsample_bytree': 0.6641676606627533, 'min_child_weight': 9, 'gamma': 3.5897140290966316, 'reg_alpha': 0.002237845840864541, 'reg_lambda': 6.940762343908079e-06, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:39:43,306] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.2822410575519673, 'n_estimators': 423, 'subsample': 0.6763555031696673, 'colsample_bytree': 0.6533751660497382, 'min_child_weight': 9, 'gamma': 3.372257431504498, 'reg_alpha': 0.003949237921995986, 'reg_lambda': 0.1640213016802154, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  11%|█         | 22/200 [00:16<01:27,  2.02it/s]

[I 2025-11-10 18:39:43,402] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.13094396550926024, 'n_estimators': 432, 'subsample': 0.6911277223129224, 'colsample_bytree': 0.6647330759468542, 'min_child_weight': 6, 'gamma': 1.4811398025687272, 'reg_alpha': 0.2600042386214507, 'reg_lambda': 0.1916850739149939, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  12%|█▏        | 24/200 [00:17<01:20,  2.20it/s]

[I 2025-11-10 18:39:44,110] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.12239378279198614, 'n_estimators': 457, 'subsample': 0.6340985511215727, 'colsample_bytree': 0.8066693060013271, 'min_child_weight': 6, 'gamma': 1.5359085487013822, 'reg_alpha': 0.09605838692808183, 'reg_lambda': 0.10761700178066352, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  12%|█▎        | 25/200 [00:20<02:59,  1.02s/it]

[I 2025-11-10 18:39:47,015] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08092841734833274, 'n_estimators': 885, 'subsample': 0.5178200995668041, 'colsample_bytree': 0.5627684170560642, 'min_child_weight': 10, 'gamma': 4.2376337815296, 'reg_alpha': 0.11124163553354591, 'reg_lambda': 1.0420496932664947e-07, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:39:47,048] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.05914102308440488, 'n_estimators': 875, 'subsample': 0.5011945450184055, 'colsample_bytree': 0.5704693562630295, 'min_child_weight': 10, 'gamma': 4.3590914188686405, 'reg_alpha': 0.0367859934330557, 'reg_lambda': 1.0747914702918944e-07, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  14%|█▎        | 27/200 [00:20<01:54,  1.51it/s]

[I 2025-11-10 18:39:47,255] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.061342939727964084, 'n_estimators': 917, 'subsample': 0.5371394141806266, 'colsample_bytree': 0.5859726719941902, 'min_child_weight': 10, 'gamma': 4.312592760127336, 'reg_alpha': 0.10151415084095328, 'reg_lambda': 2.3984432544896e-07, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  14%|█▍        | 28/200 [00:21<01:58,  1.45it/s]

[I 2025-11-10 18:39:48,033] Trial 27 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.060420867189156166, 'n_estimators': 919, 'subsample': 0.5522936636907577, 'colsample_bytree': 0.5630087738716555, 'min_child_weight': 10, 'gamma': 4.254216021025038, 'reg_alpha': 0.03694125109645393, 'reg_lambda': 1.3094031095750086e-07, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  14%|█▍        | 29/200 [00:25<03:50,  1.35s/it]

[I 2025-11-10 18:39:51,470] Trial 29 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04974535736382946, 'n_estimators': 1084, 'subsample': 0.5728797957612979, 'colsample_bytree': 0.604999859219358, 'min_child_weight': 9, 'gamma': 4.23599531100163, 'reg_alpha': 9.871627082943325, 'reg_lambda': 8.733758706568583e-05, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  15%|█▌        | 30/200 [00:25<03:03,  1.08s/it]

[I 2025-11-10 18:39:51,758] Trial 30 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.047787448805491115, 'n_estimators': 1092, 'subsample': 0.589483933097325, 'colsample_bytree': 0.6092182085740893, 'min_child_weight': 9, 'gamma': 2.412943248742704, 'reg_alpha': 1.5140186913150927e-05, 'reg_lambda': 3.549300595417489e-05, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:39:51,782] Trial 28 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.05839610570188945, 'n_estimators': 1147, 'subsample': 0.5875059889998071, 'colsample_bytree': 0.5820037345997707, 'min_child_weight': 9, 'gamma': 4.2294585894330545, 'reg_alpha': 0.025467639641559955, 'reg_lambda': 1.3732469409934388e-07, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  16%|█▌        | 32/200 [00:26<02:20,  1.20it/s]

[I 2025-11-10 18:39:52,767] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.045605505337191675, 'n_estimators': 1141, 'subsample': 0.5828006717785985, 'colsample_bytree': 0.6077467648653737, 'min_child_weight': 9, 'gamma': 3.155898990215644, 'reg_alpha': 1.2668362992606437e-05, 'reg_lambda': 5.363410841476056e-05, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  16%|█▋        | 33/200 [00:28<03:16,  1.17s/it]

[I 2025-11-10 18:39:55,063] Trial 33 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.021463142982692637, 'n_estimators': 788, 'subsample': 0.7045108216577363, 'colsample_bytree': 0.6987404877657052, 'min_child_weight': 7, 'gamma': 3.301604414451315, 'reg_alpha': 7.0869877169630815e-06, 'reg_lambda': 9.365653541660603, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:39:55,085] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.010086373409592744, 'n_estimators': 773, 'subsample': 0.6329492613350762, 'colsample_bytree': 0.7921648080328946, 'min_child_weight': 10, 'gamma': 2.9750077021713324, 'reg_alpha': 0.011134581391199846, 'reg_lambda': 7.692168670485532e-07, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  18%|█▊        | 35/200 [00:30<02:49,  1.03s/it]

[I 2025-11-10 18:39:56,663] Trial 32 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.04510702957737705, 'n_estimators': 1213, 'subsample': 0.5963471530673996, 'colsample_bytree': 0.7618539628301905, 'min_child_weight': 9, 'gamma': 2.330956941363504, 'reg_alpha': 1.0443798993617356e-05, 'reg_lambda': 2.939638413637344e-08, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  18%|█▊        | 36/200 [00:30<02:28,  1.10it/s]

[I 2025-11-10 18:39:57,161] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.01933872557143426, 'n_estimators': 1017, 'subsample': 0.7080950175264307, 'colsample_bytree': 0.7685812288299417, 'min_child_weight': 10, 'gamma': 2.77862289741565, 'reg_alpha': 0.00839203671253515, 'reg_lambda': 5.559403769499255e-08, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  18%|█▊        | 37/200 [00:31<02:34,  1.05it/s]

[I 2025-11-10 18:39:58,234] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.014332448057314554, 'n_estimators': 338, 'subsample': 0.6580686257557129, 'colsample_bytree': 0.8763784764820581, 'min_child_weight': 10, 'gamma': 2.7238726246961917, 'reg_alpha': 0.7839091121512012, 'reg_lambda': 3.959490574889759e-08, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  19%|█▉        | 38/200 [00:32<02:16,  1.19it/s]

[I 2025-11-10 18:39:58,760] Trial 40 pruned.

Best trial: 1. Best value: 0.5:  20%|█▉        | 39/200 [00:33<02:16,  1.18it/s]

[I 2025-11-10 18:39:59,622] Trial 37 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.014636467609538939, 'n_estimators': 1037, 'subsample': 0.7205697895785832, 'colsample_bytree': 0.7684186293421191, 'min_child_weight': 10, 'gamma': 2.4959996811577247, 'reg_alpha': 0.0005882891287879769, 'reg_lambda': 3.267715088554126e-08, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  20%|██        | 40/200 [00:34<02:25,  1.10it/s]

[I 2025-11-10 18:40:00,702] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01373916178042806, 'n_estimators': 1258, 'subsample': 0.6345535475557875, 'colsample_bytree': 0.7736962528048819, 'min_child_weight': 10, 'gamma': 2.718919635736274, 'reg_alpha': 0.01319061964423708, 'reg_lambda': 6.849375410096522e-07, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  20%|██        | 41/200 [00:36<03:04,  1.16s/it]

[I 2025-11-10 18:40:02,499] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.012627374320921803, 'n_estimators': 1294, 'subsample': 0.6643909200230548, 'colsample_bytree': 0.7001897817506656, 'min_child_weight': 5, 'gamma': 3.9405131587015325, 'reg_alpha': 1.0963594869158348, 'reg_lambda': 6.658152625499568e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:40:02,536] Trial 43 pruned.

Best trial: 1. Best value: 0.5:  22%|██▏       | 43/200 [00:37<02:48,  1.07s/it]

[I 2025-11-10 18:40:04,422] Trial 41 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.013315932722076254, 'n_estimators': 1375, 'subsample': 0.9164467451066718, 'colsample_bytree': 0.5385787082784251, 'min_child_weight': 7, 'gamma': 3.9904084610675166, 'reg_alpha': 0.00030199794299775803, 'reg_lambda': 6.394194114763251e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  22%|██▏       | 44/200 [00:38<02:27,  1.06it/s]

[I 2025-11-10 18:40:04,982] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.17324189507132012, 'n_estimators': 548, 'subsample': 0.5268508378038089, 'colsample_bytree': 0.5454506587886885, 'min_child_weight': 7, 'gamma': 0.2461257586245041, 'reg_alpha': 3.361136921754588e-08, 'reg_lambda': 1.7685772354205961e-06, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  22%|██▎       | 45/200 [00:39<02:23,  1.08it/s]

[I 2025-11-10 18:40:05,836] Trial 42 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.08045692962455618, 'n_estimators': 1406, 'subsample': 0.893292661890525, 'colsample_bytree': 0.8432034770584567, 'min_child_weight': 7, 'gamma': 3.908814784619144, 'reg_alpha': 2.2558224900589796e-07, 'reg_lambda': 4.897345974525518e-07, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  23%|██▎       | 46/200 [00:41<03:32,  1.38s/it]

[I 2025-11-10 18:40:08,459] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.1779107308071315, 'n_estimators': 1404, 'subsample': 0.5462821217273328, 'colsample_bytree': 0.5430955169808745, 'min_child_weight': 7, 'gamma': 0.36466625235178984, 'reg_alpha': 1.4418043633345867e-08, 'reg_lambda': 1.6123117041106681e-06, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  24%|██▎       | 47/200 [00:42<02:40,  1.05s/it]

[I 2025-11-10 18:40:08,657] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.16733660542872464, 'n_estimators': 986, 'subsample': 0.5524675135348329, 'colsample_bytree': 0.538094136018679, 'min_child_weight': 7, 'gamma': 0.01695878702595266, 'reg_alpha': 5.376727679241947e-08, 'reg_lambda': 1.8857759076358051e-06, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:40:08,683] Trial 47 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.24519100172418354, 'n_estimators': 814, 'subsample': 0.5500891142364692, 'colsample_bytree': 0.7330313952055716, 'min_child_weight': 6, 'gamma': 1.8485308579264674, 'reg_alpha': 1.1656671739377821e-07, 'reg_lambda': 3.0778871394494373e-07, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  24%|██▍       | 49/200 [00:43<02:19,  1.09it/s]

[I 2025-11-10 18:40:10,167] Trial 48 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2516096970275105, 'n_estimators': 997, 'subsample': 0.5669726685165709, 'colsample_bytree': 0.6277171966620779, 'min_child_weight': 6, 'gamma': 2.053700386072399, 'reg_alpha': 6.239261152460655e-08, 'reg_lambda': 2.393065902857534e-06, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  25%|██▌       | 50/200 [00:45<02:42,  1.08s/it]

[I 2025-11-10 18:40:11,766] Trial 51 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.019209533688261296, 'n_estimators': 722, 'subsample': 0.6138091895882282, 'colsample_bytree': 0.6189737603995408, 'min_child_weight': 8, 'gamma': 1.011623997467731, 'reg_alpha': 6.021136959642919e-07, 'reg_lambda': 1.0031868470364926e-08, 'max_delta_step': 1}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  26%|██▌       | 52/200 [00:45<01:47,  1.38it/s]

[I 2025-11-10 18:40:12,280] Trial 49 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.018217635766221332, 'n_estimators': 820, 'subsample': 0.559789577023797, 'colsample_bytree': 0.999925028244486, 'min_child_weight': 6, 'gamma': 2.1139856533966883, 'reg_alpha': 1.8641842558582843e-06, 'reg_lambda': 0.6454138995160633, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:40:12,420] Trial 50 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.01756089351776391, 'n_estimators': 822, 'subsample': 0.6146697146393769, 'colsample_bytree': 0.9603233845396754, 'min_child_weight': 6, 'gamma': 1.9980654975878038, 'reg_alpha': 2.3912682101049994e-06, 'reg_lambda': 0.000671026641226701, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  26%|██▋       | 53/200 [00:46<01:58,  1.24it/s]

[I 2025-11-10 18:40:13,438] Trial 52 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.019141996931254283, 'n_estimators': 718, 'subsample': 0.7474716534981644, 'colsample_bytree': 0.9198593764029017, 'min_child_weight': 8, 'gamma': 4.636148896781806, 'reg_alpha': 1.3483243085741585e-06, 'reg_lambda': 1.657544536582887e-08, 'max_delta_step': 1}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  27%|██▋       | 54/200 [00:47<01:53,  1.29it/s]

[I 2025-11-10 18:40:14,138] Trial 55 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.10995924699233246, 'n_estimators': 354, 'subsample': 0.7563369432524019, 'colsample_bytree': 0.9399932952443782, 'min_child_weight': 9, 'gamma': 4.8254333508248655, 'reg_alpha': 0.0042383007794175795, 'reg_lambda': 0.03171643990769739, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  28%|██▊       | 55/200 [00:48<01:37,  1.48it/s]

[I 2025-11-10 18:40:14,559] Trial 53 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.06902700716631975, 'n_estimators': 605, 'subsample': 0.7509150167157063, 'colsample_bytree': 0.6848281079143942, 'min_child_weight': 9, 'gamma': 4.692924302051922, 'reg_alpha': 0.38984719238293636, 'reg_lambda': 1.950065770700864e-05, 'max_delta_step': 2}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  28%|██▊       | 56/200 [00:49<02:11,  1.09it/s]

[I 2025-11-10 18:40:16,027] Trial 56 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.10131461877707787, 'n_estimators': 350, 'subsample': 0.8592394717530203, 'colsample_bytree': 0.6823655820416811, 'min_child_weight': 9, 'gamma': 4.685265259269568, 'reg_alpha': 3.8007499516433337e-06, 'reg_lambda': 0.01785926709004351, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  28%|██▊       | 57/200 [00:50<01:55,  1.23it/s]

[I 2025-11-10 18:40:16,603] Trial 54 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.10423340029030996, 'n_estimators': 611, 'subsample': 0.858061564793629, 'colsample_bytree': 0.9628555437562454, 'min_child_weight': 9, 'gamma': 4.599334797037919, 'reg_alpha': 4.9401244096371884e-06, 'reg_lambda': 0.0003535121345658318, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  29%|██▉       | 58/200 [00:51<02:11,  1.08it/s]

[I 2025-11-10 18:40:17,827] Trial 59 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.14730618477965396, 'n_estimators': 260, 'subsample': 0.8023836839986986, 'colsample_bytree': 0.854332246730791, 'min_child_weight': 10, 'gamma': 4.461693194456358, 'reg_alpha': 0.001817348257335702, 'reg_lambda': 0.002233190498373195, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  30%|███       | 60/200 [00:51<01:21,  1.73it/s]

[I 2025-11-10 18:40:18,214] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.0709940157316073, 'n_estimators': 611, 'subsample': 0.8562798223342449, 'colsample_bytree': 0.6787474274243218, 'min_child_weight': 9, 'gamma': 4.498916065925924, 'reg_alpha': 1.0790503037992794e-08, 'reg_lambda': 1.7441978191929737e-05, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:40:18,355] Trial 58 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08850686421631578, 'n_estimators': 497, 'subsample': 0.8523601370815467, 'colsample_bytree': 0.8787096322338911, 'min_child_weight': 10, 'gamma': 4.449856852675325, 'reg_alpha': 1.0092097440216506e-08, 'reg_lambda': 0.0018704216109204687, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  30%|███       | 61/200 [00:52<01:23,  1.67it/s]

[I 2025-11-10 18:40:18,989] Trial 60 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.09138737840049245, 'n_estimators': 507, 'subsample': 0.5021764600027422, 'colsample_bytree': 0.6379424628606722, 'min_child_weight': 10, 'gamma': 4.999682176815514, 'reg_alpha': 2.5499337814991676e-05, 'reg_lambda': 0.001398207813535363, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  31%|███       | 62/200 [00:53<01:54,  1.20it/s]

[I 2025-11-10 18:40:20,369] Trial 61 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.022974878284783142, 'n_estimators': 515, 'subsample': 0.965597659957506, 'colsample_bytree': 0.8796982037520036, 'min_child_weight': 8, 'gamma': 3.4552367800767825, 'reg_alpha': 1.2222758117314897e-08, 'reg_lambda': 0.0001290737924079385, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  32%|███▏      | 63/200 [00:56<03:04,  1.34s/it]

[I 2025-11-10 18:40:22,914] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.024517117471479697, 'n_estimators': 922, 'subsample': 0.7304878797126653, 'colsample_bytree': 0.5102820971168989, 'min_child_weight': 8, 'gamma': 4.075899561213799, 'reg_alpha': 5.729708756050877, 'reg_lambda': 0.00019082065403381728, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  32%|███▎      | 65/200 [00:56<01:41,  1.33it/s]

[I 2025-11-10 18:40:23,163] Trial 65 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03036190798278463, 'n_estimators': 663, 'subsample': 0.7793412445249119, 'colsample_bytree': 0.5171519014598231, 'min_child_weight': 8, 'gamma': 4.048479438552689, 'reg_alpha': 6.912611248752701, 'reg_lambda': 0.007107982199480181, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:40:23,293] Trial 63 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03670726681429693, 'n_estimators': 1160, 'subsample': 0.5010504012734249, 'colsample_bytree': 0.589425767064065, 'min_child_weight': 8, 'gamma': 3.7397451058273825, 'reg_alpha': 0.06058220634885871, 'reg_lambda': 7.378909768938826e-08, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  33%|███▎      | 66/200 [00:58<02:08,  1.05it/s]

[I 2025-11-10 18:40:24,728] Trial 62 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.09019320561615723, 'n_estimators': 1484, 'subsample': 0.5013039348487659, 'colsample_bytree': 0.7292516562225541, 'min_child_weight': 8, 'gamma': 4.988987558195621, 'reg_alpha': 0.06179805303355963, 'reg_lambda': 7.554472426172128e-08, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  34%|███▎      | 67/200 [00:58<01:44,  1.28it/s]

[I 2025-11-10 18:40:25,108] Trial 68 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.142614540318734, 'n_estimators': 402, 'subsample': 0.8309254336057543, 'colsample_bytree': 0.7260094900070482, 'min_child_weight': 5, 'gamma': 4.811575608519637, 'reg_alpha': 2.748066607982672, 'reg_lambda': 2.2002021213807863e-07, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  34%|███▍      | 68/200 [00:59<01:36,  1.36it/s]

[I 2025-11-10 18:40:25,728] Trial 69 pruned.

Best trial: 1. Best value: 0.5:  34%|███▍      | 69/200 [01:01<02:33,  1.17s/it]

[I 2025-11-10 18:40:27,911] Trial 66 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.031984942290187314, 'n_estimators': 1172, 'subsample': 0.7867514314210529, 'colsample_bytree': 0.5890724599245509, 'min_child_weight': 5, 'gamma': 3.654871100584274, 'reg_alpha': 2.6220642928092976, 'reg_lambda': 0.05162342480440276, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  35%|███▌      | 70/200 [01:01<01:56,  1.12it/s]

[I 2025-11-10 18:40:28,168] Trial 70 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.011645429445222562, 'n_estimators': 735, 'subsample': 0.6822395943907902, 'colsample_bytree': 0.5931469889029654, 'min_child_weight': 10, 'gamma': 2.9763186188892297, 'reg_alpha': 0.020688762591497805, 'reg_lambda': 0.09133216909189881, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  36%|███▌      | 71/200 [01:02<01:47,  1.20it/s]

[I 2025-11-10 18:40:28,864] Trial 71 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.016372947737737058, 'n_estimators': 751, 'subsample': 0.6856169917395607, 'colsample_bytree': 0.5633533978156556, 'min_child_weight': 10, 'gamma': 0.9662846642831953, 'reg_alpha': 0.1795643773928979, 'reg_lambda': 0.09624059786407378, 'max_delta_step': 2}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  36%|███▌      | 72/200 [01:02<01:36,  1.33it/s]

[I 2025-11-10 18:40:29,423] Trial 67 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.011263644647046166, 'n_estimators': 1482, 'subsample': 0.8821487959410512, 'colsample_bytree': 0.5805333693901193, 'min_child_weight': 5, 'gamma': 3.7776052631869512, 'reg_alpha': 3.4658305316809166, 'reg_lambda': 7.256399932085996e-08, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  36%|███▋      | 73/200 [01:05<02:40,  1.27s/it]

[I 2025-11-10 18:40:31,890] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.03990216002475403, 'n_estimators': 690, 'subsample': 0.8787758981735188, 'colsample_bytree': 0.5219160140612678, 'min_child_weight': 7, 'gamma': 3.1572154203241203, 'reg_alpha': 5.1644689019080915e-05, 'reg_lambda': 0.004093221635430551, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  37%|███▋      | 74/200 [01:05<02:01,  1.03it/s]

[I 2025-11-10 18:40:32,158] Trial 72 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.012400447340026648, 'n_estimators': 951, 'subsample': 0.6792826773958653, 'colsample_bytree': 0.5196733321104575, 'min_child_weight': 10, 'gamma': 3.0432074781422784, 'reg_alpha': 5.3617350256768405e-05, 'reg_lambda': 0.00413300796293059, 'max_delta_step': 2}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  38%|███▊      | 75/200 [01:05<01:33,  1.33it/s]

[I 2025-11-10 18:40:32,399] Trial 73 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.05217723074937972, 'n_estimators': 966, 'subsample': 0.8808803345321776, 'colsample_bytree': 0.5220300800097178, 'min_child_weight': 10, 'gamma': 1.5222612013045937, 'reg_alpha': 0.14800849885537667, 'reg_lambda': 1.9489941068409348e-08, 'max_delta_step': 2}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  38%|███▊      | 76/200 [01:06<01:35,  1.30it/s]

[I 2025-11-10 18:40:33,210] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.03948866987792052, 'n_estimators': 871, 'subsample': 0.8107453518678653, 'colsample_bytree': 0.5232956585589816, 'min_child_weight': 7, 'gamma': 4.396704057046124, 'reg_alpha': 4.712969010865983e-05, 'reg_lambda': 0.409476510253446, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  38%|███▊      | 77/200 [01:08<02:03,  1.01s/it]

[I 2025-11-10 18:40:34,772] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.052232998625004086, 'n_estimators': 582, 'subsample': 0.8060758345708717, 'colsample_bytree': 0.5534980713929443, 'min_child_weight': 9, 'gamma': 1.24871214630729, 'reg_alpha': 0.0001563127640716009, 'reg_lambda': 1.9002431206851228e-08, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  40%|███▉      | 79/200 [01:09<01:38,  1.22it/s]

[I 2025-11-10 18:40:36,091] Trial 76 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.055115101585190715, 'n_estimators': 945, 'subsample': 0.7336718128537784, 'colsample_bytree': 0.5239518241046245, 'min_child_weight': 9, 'gamma': 4.189509190583718, 'reg_alpha': 0.00021830710973535044, 'reg_lambda': 0.382635546823552, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:40:36,247] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.11680305420935806, 'n_estimators': 658, 'subsample': 0.7316708257693209, 'colsample_bytree': 0.5524817040062124, 'min_child_weight': 9, 'gamma': 1.1976173451404701, 'reg_alpha': 0.0001826164549840519, 'reg_lambda': 0.0005825270819476979, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  40%|████      | 80/200 [01:09<01:13,  1.64it/s]

[I 2025-11-10 18:40:36,382] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06701303010690156, 'n_estimators': 892, 'subsample': 0.7640272139600774, 'colsample_bytree': 0.501497026359203, 'min_child_weight': 9, 'gamma': 4.172055529728946, 'reg_alpha': 0.0008634524564049505, 'reg_lambda': 0.0010994604458881862, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  40%|████      | 81/200 [01:10<01:14,  1.60it/s]

[I 2025-11-10 18:40:37,038] Trial 80 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.0694289420784189, 'n_estimators': 456, 'subsample': 0.7673536783383164, 'colsample_bytree': 0.8034894396271562, 'min_child_weight': 9, 'gamma': 4.164376151647176, 'reg_alpha': 0.0009652775178813157, 'reg_lambda': 0.0004833446165159845, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  42%|████▏     | 83/200 [01:12<01:12,  1.62it/s]

[I 2025-11-10 18:40:38,369] Trial 82 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02837604506589611, 'n_estimators': 450, 'subsample': 0.7029169884721181, 'colsample_bytree': 0.6525665887404313, 'min_child_weight': 7, 'gamma': 2.285419360185525, 'reg_alpha': 0.0009758432471077761, 'reg_lambda': 4.422306726708271e-06, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:40:38,475] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2031177179277547, 'n_estimators': 459, 'subsample': 0.7077428706949007, 'colsample_bytree': 0.5713257854840444, 'min_child_weight': 7, 'gamma': 2.268164943952197, 'reg_alpha': 1.680865514490814e-07, 'reg_lambda': 2.6755138650122388, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  42%|████▏     | 84/200 [01:12<01:12,  1.59it/s]

[I 2025-11-10 18:40:39,121] Trial 81 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.06889998268343098, 'n_estimators': 657, 'subsample': 0.7047655816279911, 'colsample_bytree': 0.5566561190199901, 'min_child_weight': 7, 'gamma': 4.846150813670382, 'reg_alpha': 2.0158430242969364e-07, 'reg_lambda': 0.0005863855190060371, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  42%|████▎     | 85/200 [01:13<01:25,  1.34it/s]

[I 2025-11-10 18:40:40,139] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.024855574493312278, 'n_estimators': 700, 'subsample': 0.8360181011708947, 'colsample_bytree': 0.5738630263928896, 'min_child_weight': 8, 'gamma': 4.849243548802164, 'reg_alpha': 0.00010486078020108207, 'reg_lambda': 0.01187429171680603, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:40:40,180] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.026292940129609865, 'n_estimators': 384, 'subsample': 0.5230508224721861, 'colsample_bytree': 0.5346961176565173, 'min_child_weight': 8, 'gamma': 4.874341934483606, 'reg_alpha': 1.634366350017791e-07, 'reg_lambda': 0.011795525875929901, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  44%|████▎     | 87/200 [01:15<01:33,  1.21it/s]

[I 2025-11-10 18:40:41,983] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.02490472715366132, 'n_estimators': 788, 'subsample': 0.6473199414834325, 'colsample_bytree': 0.5357281853574736, 'min_child_weight': 8, 'gamma': 4.8653173874764635, 'reg_alpha': 9.65695626498357e-05, 'reg_lambda': 0.0119268456271501, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  44%|████▍     | 88/200 [01:17<01:53,  1.02s/it]

[I 2025-11-10 18:40:43,581] Trial 88 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.043575620350560035, 'n_estimators': 785, 'subsample': 0.5212790029194136, 'colsample_bytree': 0.5354924947098334, 'min_child_weight': 8, 'gamma': 1.7104615204530957, 'reg_alpha': 0.002034887375625134, 'reg_lambda': 0.03234919237428628, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:40:43,674] Trial 89 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.035450228295554324, 'n_estimators': 784, 'subsample': 0.6491063195396161, 'colsample_bytree': 0.6127063341474225, 'min_child_weight': 10, 'gamma': 4.542255845121404, 'reg_alpha': 9.279767857477284e-05, 'reg_lambda': 0.028297725893811243, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  45%|████▌     | 90/200 [01:17<01:14,  1.47it/s]

[I 2025-11-10 18:40:43,980] Trial 87 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.015443566652395534, 'n_estimators': 1107, 'subsample': 0.5280640605779839, 'colsample_bytree': 0.5378199456799215, 'min_child_weight': 8, 'gamma': 2.827983485422363, 'reg_alpha': 0.007216060116142317, 'reg_lambda': 0.009936588126017018, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  46%|████▌     | 91/200 [01:18<01:12,  1.50it/s]

[I 2025-11-10 18:40:44,611] Trial 90 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.021509275866149407, 'n_estimators': 573, 'subsample': 0.5342926610884409, 'colsample_bytree': 0.6035432405033117, 'min_child_weight': 10, 'gamma': 2.613532563592152, 'reg_alpha': 2.1813374405628594e-05, 'reg_lambda': 0.03622165912113702, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  46%|████▌     | 92/200 [01:20<01:43,  1.04it/s]

[I 2025-11-10 18:40:46,467] Trial 93 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.02212807571941775, 'n_estimators': 567, 'subsample': 0.6059967224940604, 'colsample_bytree': 0.5039883065482371, 'min_child_weight': 6, 'gamma': 0.7265887026574882, 'reg_alpha': 2.140764068069131e-05, 'reg_lambda': 1.509250101652687e-07, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  46%|████▋     | 93/200 [01:20<01:41,  1.05it/s]

[I 2025-11-10 18:40:47,394] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.028960009407516106, 'n_estimators': 640, 'subsample': 0.7751577263801595, 'colsample_bytree': 0.5004337311333138, 'min_child_weight': 10, 'gamma': 4.9994225275727615, 'reg_alpha': 0.46720211834671865, 'reg_lambda': 0.002878237354120028, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  47%|████▋     | 94/200 [01:21<01:41,  1.05it/s]

[I 2025-11-10 18:40:48,354] Trial 91 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.016004884373698573, 'n_estimators': 1110, 'subsample': 0.9107900882691373, 'colsample_bytree': 0.5089808706965948, 'min_child_weight': 10, 'gamma': 2.8212242863546613, 'reg_alpha': 2.7049126234267554e-05, 'reg_lambda': 6.785302888264594e-05, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  48%|████▊     | 95/200 [01:22<01:23,  1.25it/s]

[I 2025-11-10 18:40:48,748] Trial 92 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.02106004867151433, 'n_estimators': 1115, 'subsample': 0.9405782143975795, 'colsample_bytree': 0.6002316837558953, 'min_child_weight': 6, 'gamma': 2.6478363558179336, 'reg_alpha': 0.006691456900053861, 'reg_lambda': 4.547221389749866e-08, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  48%|████▊     | 96/200 [01:22<01:15,  1.38it/s]

[I 2025-11-10 18:40:49,294] Trial 95 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.03873923031040172, 'n_estimators': 633, 'subsample': 0.7739345651830296, 'colsample_bytree': 0.5026982497911866, 'min_child_weight': 9, 'gamma': 4.321554190979383, 'reg_alpha': 0.00046020392448301907, 'reg_lambda': 0.002110204991340661, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  48%|████▊     | 97/200 [01:23<00:59,  1.73it/s]

[I 2025-11-10 18:40:49,506] Trial 98 pruned.

Best trial: 1. Best value: 0.5:  49%|████▉     | 98/200 [01:23<01:08,  1.48it/s]

[I 2025-11-10 18:40:50,422] Trial 99 pruned.

Best trial: 1. Best value: 0.5:  50%|████▉     | 99/200 [01:25<01:35,  1.06it/s]

[I 2025-11-10 18:40:52,018] Trial 97 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.16030809078283642, 'n_estimators': 843, 'subsample': 0.7229600380443543, 'colsample_bytree': 0.6252881859904492, 'min_child_weight': 8, 'gamma': 4.3262509509096345, 'reg_alpha': 4.473705356710275e-07, 'reg_lambda': 0.006291414159733905, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  50%|█████     | 100/200 [01:26<01:27,  1.14it/s]

[I 2025-11-10 18:40:52,718] Trial 96 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1569196610767708, 'n_estimators': 1226, 'subsample': 0.7421875744378162, 'colsample_bytree': 0.5523108341598597, 'min_child_weight': 9, 'gamma': 4.356565075068274, 'reg_alpha': 0.00036405653101062016, 'reg_lambda': 0.0068481715654803285, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  50%|█████     | 101/200 [01:26<01:17,  1.29it/s]

[I 2025-11-10 18:40:53,273] Trial 100 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.032282019710317404, 'n_estimators': 850, 'subsample': 0.7908963022275545, 'colsample_bytree': 0.7518183097150289, 'min_child_weight': 7, 'gamma': 4.706676084387635, 'reg_alpha': 7.875651532944606e-08, 'reg_lambda': 0.004828002537039623, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  51%|█████     | 102/200 [01:27<01:28,  1.11it/s]

[I 2025-11-10 18:40:54,452] Trial 104 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.041995493595681575, 'n_estimators': 263, 'subsample': 0.8189881704499211, 'colsample_bytree': 0.6387417148278496, 'min_child_weight': 8, 'gamma': 4.563892242261376, 'reg_alpha': 1.248023885438115, 'reg_lambda': 2.9784956367445552e-05, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  52%|█████▏    | 103/200 [01:29<01:49,  1.12s/it]

[I 2025-11-10 18:40:56,098] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04354113330756247, 'n_estimators': 749, 'subsample': 0.8180906056793742, 'colsample_bytree': 0.9099460149463833, 'min_child_weight': 7, 'gamma': 4.591322636600038, 'reg_alpha': 2.1944894847548894e-08, 'reg_lambda': 0.02084127283007397, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  52%|█████▏    | 104/200 [01:29<01:21,  1.18it/s]

[I 2025-11-10 18:40:56,298] Trial 101 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.13420605783528697, 'n_estimators': 1305, 'subsample': 0.7393082346460077, 'colsample_bytree': 0.8636774504368764, 'min_child_weight': 7, 'gamma': 4.733996481681026, 'reg_alpha': 8.555847910695219e-06, 'reg_lambda': 0.0072951483065866836, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  52%|█████▎    | 105/200 [01:30<01:26,  1.10it/s]

[I 2025-11-10 18:40:57,368] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.01001678635198296, 'n_estimators': 1201, 'subsample': 0.7571975835277033, 'colsample_bytree': 0.7489015131643193, 'min_child_weight': 7, 'gamma': 4.725737237340115, 'reg_alpha': 2.345703821602533e-08, 'reg_lambda': 0.0002796230962368341, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  53%|█████▎    | 106/200 [01:31<01:05,  1.44it/s]

[I 2025-11-10 18:40:57,551] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.04732596543467542, 'n_estimators': 684, 'subsample': 0.5779785343551511, 'colsample_bytree': 0.7921173067905167, 'min_child_weight': 7, 'gamma': 3.524366406815529, 'reg_alpha': 6.9164545669215815e-06, 'reg_lambda': 9.377838104114323e-06, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  54%|█████▎    | 107/200 [01:31<01:09,  1.34it/s]

[I 2025-11-10 18:40:58,414] Trial 108 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.19887706915052353, 'n_estimators': 206, 'subsample': 0.669815853552966, 'colsample_bytree': 0.5631428176163009, 'min_child_weight': 8, 'gamma': 3.8766683494216316, 'reg_alpha': 0.00272490375151816, 'reg_lambda': 9.433597101905783e-07, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  54%|█████▍    | 108/200 [01:32<01:01,  1.50it/s]

[I 2025-11-10 18:40:58,898] Trial 109 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.19576492233597256, 'n_estimators': 280, 'subsample': 0.8440376143892226, 'colsample_bytree': 0.5665298443805833, 'min_child_weight': 8, 'gamma': 3.273052064620805, 'reg_alpha': 0.04112488786180691, 'reg_lambda': 2.8597637826198156e-08, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  55%|█████▍    | 109/200 [01:33<00:58,  1.55it/s]

[I 2025-11-10 18:40:59,487] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.18694206420659076, 'n_estimators': 693, 'subsample': 0.7591988159206726, 'colsample_bytree': 0.7797073807260845, 'min_child_weight': 8, 'gamma': 4.91739640768386, 'reg_alpha': 0.05026579032382223, 'reg_lambda': 1.0114946560750533e-06, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  55%|█████▌    | 110/200 [01:33<00:46,  1.93it/s]

[I 2025-11-10 18:40:59,718] Trial 107 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.035927335925954096, 'n_estimators': 700, 'subsample': 0.8412415361955483, 'colsample_bytree': 0.7809981867112217, 'min_child_weight': 8, 'gamma': 3.3663189274969545, 'reg_alpha': 0.012667263885817227, 'reg_lambda': 1.1295695166850859e-06, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  56%|█████▌    | 111/200 [01:33<00:50,  1.77it/s]

[I 2025-11-10 18:41:00,390] Trial 111 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.06093325674423585, 'n_estimators': 304, 'subsample': 0.7821147440445348, 'colsample_bytree': 0.5272254293346313, 'min_child_weight': 9, 'gamma': 4.923243499400088, 'reg_alpha': 7.540463537386971e-05, 'reg_lambda': 3.431389887106403e-06, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  56%|█████▌    | 112/200 [01:34<00:49,  1.76it/s]

[I 2025-11-10 18:41:00,966] Trial 110 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.06428943333907339, 'n_estimators': 536, 'subsample': 0.7150881636293798, 'colsample_bytree': 0.5447714302035315, 'min_child_weight': 9, 'gamma': 4.930530669142868, 'reg_alpha': 7.773435743872015e-05, 'reg_lambda': 4.687881507471704e-06, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  56%|█████▋    | 113/200 [01:35<00:49,  1.77it/s]

[I 2025-11-10 18:41:01,525] Trial 114 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.027139184594219823, 'n_estimators': 219, 'subsample': 0.7952307128519487, 'colsample_bytree': 0.6504824507065307, 'min_child_weight': 10, 'gamma': 2.490309412844141, 'reg_alpha': 0.0002761301952134026, 'reg_lambda': 1.3599011726338945e-05, 'max_delta_step': 1}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  57%|█████▋    | 114/200 [01:35<00:45,  1.89it/s]

[I 2025-11-10 18:41:01,972] Trial 112 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.026811400080665914, 'n_estimators': 529, 'subsample': 0.7175763654550147, 'colsample_bytree': 0.5277768286052632, 'min_child_weight': 9, 'gamma': 4.43812255314375, 'reg_alpha': 7.52137305261154e-05, 'reg_lambda': 4.5345178960213224e-06, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  57%|█████▊    | 115/200 [01:35<00:37,  2.24it/s]

[I 2025-11-10 18:41:02,219] Trial 115 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.08279183046684992, 'n_estimators': 234, 'subsample': 0.6938884138921697, 'colsample_bytree': 0.6145542747809001, 'min_child_weight': 10, 'gamma': 4.465870604492872, 'reg_alpha': 0.0002616768000505366, 'reg_lambda': 9.632443026111905e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  58%|█████▊    | 116/200 [01:36<00:45,  1.83it/s]

[I 2025-11-10 18:41:02,998] Trial 116 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.07443511843246507, 'n_estimators': 312, 'subsample': 0.5101040285267542, 'colsample_bytree': 0.513080840412275, 'min_child_weight': 8, 'gamma': 3.8213178575973186, 'reg_alpha': 0.0040335645253502085, 'reg_lambda': 6.795232586333226e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  58%|█████▊    | 117/200 [01:36<00:36,  2.25it/s]

[I 2025-11-10 18:41:03,209] Trial 117 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.033543039516297314, 'n_estimators': 235, 'subsample': 0.6266245711506684, 'colsample_bytree': 0.6659225947681633, 'min_child_weight': 8, 'gamma': 4.041207688694263, 'reg_alpha': 0.000641808561697953, 'reg_lambda': 8.467386159320231e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  59%|█████▉    | 118/200 [01:37<00:37,  2.19it/s]

[I 2025-11-10 18:41:03,693] Trial 118 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.030925833473417413, 'n_estimators': 321, 'subsample': 0.7681210910775378, 'colsample_bytree': 0.5116535587790718, 'min_child_weight': 8, 'gamma': 4.017959804792761, 'reg_alpha': 0.00015605284695690373, 'reg_lambda': 4.025906941720497e-07, 'max_delta_step': 1}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  60%|█████▉    | 119/200 [01:38<00:46,  1.76it/s]

[I 2025-11-10 18:41:04,525] Trial 113 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.0627346879074404, 'n_estimators': 1061, 'subsample': 0.7195984134967711, 'colsample_bytree': 0.5472631022511217, 'min_child_weight': 9, 'gamma': 4.504638211672824, 'reg_alpha': 0.00026137440779961643, 'reg_lambda': 3.5420822363739603e-06, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  60%|██████    | 120/200 [01:38<00:38,  2.08it/s]

[I 2025-11-10 18:41:04,802] Trial 119 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.02978752188258344, 'n_estimators': 374, 'subsample': 0.7693567876144599, 'colsample_bytree': 0.5810022816925448, 'min_child_weight': 8, 'gamma': 4.783542859379064, 'reg_alpha': 0.00014646043798461394, 'reg_lambda': 0.0001665644492430467, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  60%|██████    | 121/200 [01:40<01:22,  1.04s/it]

[I 2025-11-10 18:41:07,154] Trial 122 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.22935642635256734, 'n_estimators': 597, 'subsample': 0.5640747442677043, 'colsample_bytree': 0.5785270427251307, 'min_child_weight': 10, 'gamma': 3.589256812288535, 'reg_alpha': 0.0011940774172387895, 'reg_lambda': 0.00011941357112900474, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  61%|██████    | 122/200 [01:40<01:03,  1.23it/s]

[I 2025-11-10 18:41:07,431] Trial 123 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.017393458380840488, 'n_estimators': 596, 'subsample': 0.8048811552379813, 'colsample_bytree': 0.5907134679890553, 'min_child_weight': 10, 'gamma': 3.582289568034943, 'reg_alpha': 0.001201732019823484, 'reg_lambda': 1.5822340389357932e-07, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  62%|██████▏   | 123/200 [01:41<00:55,  1.38it/s]

[I 2025-11-10 18:41:07,961] Trial 120 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.017515077165965495, 'n_estimators': 1056, 'subsample': 0.7731990730325937, 'colsample_bytree': 0.5981158461739013, 'min_child_weight': 10, 'gamma': 3.6953071859767532, 'reg_alpha': 0.01777535659561708, 'reg_lambda': 0.00015898178122564856, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  62%|██████▏   | 124/200 [01:41<00:49,  1.54it/s]

[I 2025-11-10 18:41:08,428] Trial 121 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.014277777781960509, 'n_estimators': 1053, 'subsample': 0.802390531842182, 'colsample_bytree': 0.5800305010883, 'min_child_weight': 10, 'gamma': 3.6493579014473916, 'reg_alpha': 0.002749818680686879, 'reg_lambda': 3.599767153386916e-05, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  62%|██████▎   | 125/200 [01:42<00:38,  1.96it/s]

[I 2025-11-10 18:41:08,616] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.13578319171749065, 'n_estimators': 276, 'subsample': 0.8072773284720002, 'colsample_bytree': 0.5975626782386523, 'min_child_weight': 8, 'gamma': 3.727046499032378, 'reg_alpha': 0.002941588417738628, 'reg_lambda': 1.6181996295534048e-07, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  63%|██████▎   | 126/200 [01:42<00:42,  1.74it/s]

[I 2025-11-10 18:41:09,344] Trial 126 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.09578292669671978, 'n_estimators': 264, 'subsample': 0.7893767055026697, 'colsample_bytree': 0.6362290350768849, 'min_child_weight': 8, 'gamma': 4.124454364482016, 'reg_alpha': 0.0006532998186433545, 'reg_lambda': 0.05292445793783464, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  64%|██████▎   | 127/200 [01:43<00:41,  1.74it/s]

[I 2025-11-10 18:41:09,913] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.11393352730023804, 'n_estimators': 497, 'subsample': 0.825085921143942, 'colsample_bytree': 0.6651798890483598, 'min_child_weight': 8, 'gamma': 3.6811827154583434, 'reg_alpha': 0.002713512478301171, 'reg_lambda': 2.807900570765802e-05, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  64%|██████▍   | 128/200 [01:44<00:44,  1.61it/s]

[I 2025-11-10 18:41:10,644] Trial 128 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.09397705353501533, 'n_estimators': 418, 'subsample': 0.8306176458317479, 'colsample_bytree': 0.6310462522671717, 'min_child_weight': 6, 'gamma': 3.9251348339778014, 'reg_alpha': 0.08992385624247455, 'reg_lambda': 1.5996515013238504e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  64%|██████▍   | 129/200 [01:45<01:00,  1.18it/s]

[I 2025-11-10 18:41:12,024] Trial 127 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.11673233583536208, 'n_estimators': 757, 'subsample': 0.8257105215849421, 'colsample_bytree': 0.8193270795510941, 'min_child_weight': 8, 'gamma': 3.1616226915704915, 'reg_alpha': 3.5012445551178054e-05, 'reg_lambda': 2.3184111186283e-06, 'max_delta_step': 1}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  65%|██████▌   | 130/200 [01:46<00:56,  1.24it/s]

[I 2025-11-10 18:41:12,727] Trial 129 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.11086273843732178, 'n_estimators': 754, 'subsample': 0.8678514468537925, 'colsample_bytree': 0.6676266046602487, 'min_child_weight': 6, 'gamma': 2.8990396153028213, 'reg_alpha': 3.4921624938888405e-05, 'reg_lambda': 0.1393742655267574, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  66%|██████▌   | 131/200 [01:47<01:01,  1.12it/s]

[I 2025-11-10 18:41:13,814] Trial 133 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.14281846805033005, 'n_estimators': 229, 'subsample': 0.7595087030773101, 'colsample_bytree': 0.7123324519882237, 'min_child_weight': 9, 'gamma': 4.6447822281606115, 'reg_alpha': 5.1402804134897604e-08, 'reg_lambda': 9.926370736693566e-08, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  66%|██████▌   | 132/200 [01:47<00:49,  1.37it/s]

[I 2025-11-10 18:41:14,169] Trial 131 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03790959763645829, 'n_estimators': 764, 'subsample': 0.8661536652979359, 'colsample_bytree': 0.9798842333849352, 'min_child_weight': 7, 'gamma': 3.171516250999098, 'reg_alpha': 3.353844856398104e-05, 'reg_lambda': 8.466232168191577e-08, 'max_delta_step': 1}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  66%|██████▋   | 133/200 [01:48<00:42,  1.59it/s]

[I 2025-11-10 18:41:14,563] Trial 130 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01315270607637578, 'n_estimators': 1009, 'subsample': 0.8990001566319611, 'colsample_bytree': 0.813541494422986, 'min_child_weight': 7, 'gamma': 3.213728632083705, 'reg_alpha': 3.356796608115119e-05, 'reg_lambda': 9.729771248527121e-08, 'max_delta_step': 1}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  67%|██████▋   | 134/200 [01:49<00:47,  1.39it/s]

[I 2025-11-10 18:41:15,505] Trial 132 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.012902465543636332, 'n_estimators': 720, 'subsample': 0.8688478231107473, 'colsample_bytree': 0.9671596606760519, 'min_child_weight': 9, 'gamma': 2.874819410182246, 'reg_alpha': 1.5029433674488557e-05, 'reg_lambda': 0.1509856067747107, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  68%|██████▊   | 135/200 [01:49<00:41,  1.58it/s]

[I 2025-11-10 18:41:15,924] Trial 134 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.011244312173575207, 'n_estimators': 431, 'subsample': 0.8142327431747824, 'colsample_bytree': 0.6470408030431983, 'min_child_weight': 9, 'gamma': 3.3113096838147813, 'reg_alpha': 1.4565157396364217e-05, 'reg_lambda': 1.526972593472984e-05, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:41:16,014] Trial 135 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.01093152938818267, 'n_estimators': 374, 'subsample': 0.8936388974310832, 'colsample_bytree': 0.6115095353086573, 'min_child_weight': 9, 'gamma': 3.399583781643673, 'reg_alpha': 0.0016701701355278265, 'reg_lambda': 0.0012806660224624238, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  68%|██████▊   | 137/200 [01:50<00:35,  1.79it/s]

[I 2025-11-10 18:41:16,867] Trial 136 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.011663018723978326, 'n_estimators': 479, 'subsample': 0.7519125747102673, 'colsample_bytree': 0.6490568705787845, 'min_child_weight': 9, 'gamma': 3.4586453008839255, 'reg_alpha': 0.011439765082408664, 'reg_lambda': 1.8065637256154168e-05, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  70%|██████▉   | 139/200 [01:51<00:28,  2.15it/s]

[I 2025-11-10 18:41:17,570] Trial 138 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03361094294294833, 'n_estimators': 331, 'subsample': 0.7845589969787222, 'colsample_bytree': 0.6913059747734334, 'min_child_weight': 8, 'gamma': 4.800668278700713, 'reg_alpha': 0.0016726579260036986, 'reg_lambda': 0.000966037925554184, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:41:17,672] Trial 137 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03396655587557453, 'n_estimators': 436, 'subsample': 0.7838255665842828, 'colsample_bytree': 0.6505963237261081, 'min_child_weight': 9, 'gamma': 3.419544586852041, 'reg_alpha': 0.001673579211786641, 'reg_lambda': 2.1067089983956725e-05, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  70%|███████   | 140/200 [01:51<00:30,  1.95it/s]

[I 2025-11-10 18:41:18,309] Trial 139 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.019980594565713217, 'n_estimators': 474, 'subsample': 0.848592814958038, 'colsample_bytree': 0.6956112497849796, 'min_child_weight': 8, 'gamma': 4.2515175380818695, 'reg_alpha': 0.005490644667606044, 'reg_lambda': 0.0024568456461191435, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  70%|███████   | 141/200 [01:52<00:27,  2.13it/s]

[I 2025-11-10 18:41:18,666] Trial 140 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03301335877441705, 'n_estimators': 343, 'subsample': 0.9988596802274077, 'colsample_bytree': 0.8969218552471947, 'min_child_weight': 8, 'gamma': 3.856818740029759, 'reg_alpha': 0.005700447871112785, 'reg_lambda': 0.0037119914940270953, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  71%|███████   | 142/200 [01:52<00:31,  1.82it/s]

[I 2025-11-10 18:41:19,424] Trial 143 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.12732878559157776, 'n_estimators': 204, 'subsample': 0.8377324018005983, 'colsample_bytree': 0.8969610658787768, 'min_child_weight': 10, 'gamma': 3.8132924952028953, 'reg_alpha': 0.0003829768430113098, 'reg_lambda': 5.3313391667794466e-05, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  72%|███████▏  | 143/200 [01:54<00:40,  1.42it/s]

[I 2025-11-10 18:41:20,505] Trial 144 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.29153985836360047, 'n_estimators': 402, 'subsample': 0.6938295004753304, 'colsample_bytree': 0.615876606698119, 'min_child_weight': 10, 'gamma': 3.0626976763178124, 'reg_alpha': 0.0005222714153350828, 'reg_lambda': 1.3043354182248836, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  72%|███████▎  | 145/200 [01:54<00:24,  2.23it/s]

[I 2025-11-10 18:41:20,812] Trial 142 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.024162548129404774, 'n_estimators': 672, 'subsample': 0.8523658254269402, 'colsample_bytree': 0.6768829925325501, 'min_child_weight': 10, 'gamma': 3.029856790686285, 'reg_alpha': 0.00045921877692842134, 'reg_lambda': 5.368610741891667e-05, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:41:20,927] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.024545560345231015, 'n_estimators': 659, 'subsample': 0.5432238527235644, 'colsample_bytree': 0.9311306697337884, 'min_child_weight': 10, 'gamma': 4.997464682305197, 'reg_alpha': 0.006185337167724694, 'reg_lambda': 4.425498093067145e-05, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  73%|███████▎  | 146/200 [01:55<00:41,  1.31it/s]

[I 2025-11-10 18:41:22,442] Trial 145 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.2977409207813853, 'n_estimators': 660, 'subsample': 0.5424205418402148, 'colsample_bytree': 0.6822038256802769, 'min_child_weight': 10, 'gamma': 3.5144167970190887, 'reg_alpha': 1.0750522286851981e-07, 'reg_lambda': 3.012193801324617e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  74%|███████▎  | 147/200 [01:57<00:46,  1.14it/s]

[I 2025-11-10 18:41:23,578] Trial 146 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.05634393866454951, 'n_estimators': 653, 'subsample': 0.6629793850599874, 'colsample_bytree': 0.6818217781448377, 'min_child_weight': 10, 'gamma': 4.996777408144924, 'reg_alpha': 3.281965782273303e-06, 'reg_lambda': 6.357291873938061e-06, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  74%|███████▍  | 148/200 [01:57<00:35,  1.48it/s]

[I 2025-11-10 18:41:23,785] Trial 148 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.2185347753934558, 'n_estimators': 627, 'subsample': 0.7442606422803943, 'colsample_bytree': 0.6236024180692002, 'min_child_weight': 8, 'gamma': 3.5150731044031227, 'reg_alpha': 0.008977649496459355, 'reg_lambda': 0.289959680401338, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  74%|███████▍  | 149/200 [01:58<00:35,  1.45it/s]

[I 2025-11-10 18:41:24,510] Trial 147 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.17901416529661085, 'n_estimators': 812, 'subsample': 0.544890180324366, 'colsample_bytree': 0.6214661322328752, 'min_child_weight': 8, 'gamma': 4.995856588310285, 'reg_alpha': 0.00911492579120306, 'reg_lambda': 0.06327050147620922, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  75%|███████▌  | 150/200 [01:59<00:49,  1.00it/s]

[I 2025-11-10 18:41:26,228] Trial 149 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.17124476101601288, 'n_estimators': 818, 'subsample': 0.7490623286955211, 'colsample_bytree': 0.6287239151940994, 'min_child_weight': 8, 'gamma': 4.782012916382246, 'reg_alpha': 0.00936341513211044, 'reg_lambda': 0.30418615072541716, 'max_delta_step': 2}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  76%|███████▌  | 151/200 [02:00<00:48,  1.01it/s]

[I 2025-11-10 18:41:27,195] Trial 150 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.08517095732059299, 'n_estimators': 810, 'subsample': 0.7343050204108507, 'colsample_bytree': 0.5138683348236378, 'min_child_weight': 8, 'gamma': 2.3978332458812917, 'reg_alpha': 0.009139513760966039, 'reg_lambda': 0.2302426576255177, 'max_delta_step': 2}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  76%|███████▌  | 152/200 [02:00<00:36,  1.33it/s]

[I 2025-11-10 18:41:27,395] Trial 151 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.17473263155799446, 'n_estimators': 808, 'subsample': 0.588005896878545, 'colsample_bytree': 0.5284722998854932, 'min_child_weight': 7, 'gamma': 0.06717503455169355, 'reg_alpha': 0.004034768509504237, 'reg_lambda': 0.08277335878074024, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  77%|███████▋  | 154/200 [02:01<00:22,  2.07it/s]

[I 2025-11-10 18:41:27,713] Trial 153 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2635323551603328, 'n_estimators': 296, 'subsample': 0.636596804207893, 'colsample_bytree': 0.5542506742376702, 'min_child_weight': 9, 'gamma': 2.535784606352195, 'reg_alpha': 0.024593758609052777, 'reg_lambda': 6.682262199829924e-07, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:41:27,878] Trial 152 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.027807652912588954, 'n_estimators': 720, 'subsample': 0.7262135112815821, 'colsample_bytree': 0.5158598601297103, 'min_child_weight': 9, 'gamma': 2.4433057379308445, 'reg_alpha': 0.028083997852649704, 'reg_lambda': 0.23399641991362363, 'max_delta_step': 2}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  78%|███████▊  | 155/200 [02:02<00:33,  1.33it/s]

[I 2025-11-10 18:41:29,264] Trial 154 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.12387507124841525, 'n_estimators': 420, 'subsample': 0.5922359520015799, 'colsample_bytree': 0.6625254634439492, 'min_child_weight': 7, 'gamma': 0.007792898696989958, 'reg_alpha': 0.34981677063896216, 'reg_lambda': 2.660423484500192e-08, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  78%|███████▊  | 156/200 [02:03<00:29,  1.48it/s]

[I 2025-11-10 18:41:29,756] Trial 157 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.0408803325948713, 'n_estimators': 406, 'subsample': 0.6051403816782674, 'colsample_bytree': 0.6383372582996157, 'min_child_weight': 7, 'gamma': 0.36042071507146467, 'reg_alpha': 0.22871693603179857, 'reg_lambda': 0.017937281625276892, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  78%|███████▊  | 157/200 [02:03<00:25,  1.69it/s]

[I 2025-11-10 18:41:30,142] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1048223395975096, 'n_estimators': 562, 'subsample': 0.6737429172688559, 'colsample_bytree': 0.6626088036341574, 'min_child_weight': 7, 'gamma': 1.6032871602960739, 'reg_alpha': 0.20900697320414394, 'reg_lambda': 2.9565769377356448e-08, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  79%|███████▉  | 158/200 [02:03<00:19,  2.13it/s]

[I 2025-11-10 18:41:30,330] Trial 156 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.10380361384834025, 'n_estimators': 550, 'subsample': 0.7253840013814933, 'colsample_bytree': 0.6615604866123977, 'min_child_weight': 7, 'gamma': 0.41605501135145584, 'reg_alpha': 0.2693695267485707, 'reg_lambda': 0.5448776324805852, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  80%|███████▉  | 159/200 [02:05<00:32,  1.24it/s]

[I 2025-11-10 18:41:31,912] Trial 158 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.0414436376252709, 'n_estimators': 559, 'subsample': 0.6762275638311686, 'colsample_bytree': 0.6584217671094532, 'min_child_weight': 6, 'gamma': 1.5132724268010946, 'reg_alpha': 1.6708812100374741, 'reg_lambda': 0.016625767929799806, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  80%|████████  | 160/200 [02:06<00:30,  1.31it/s]

[I 2025-11-10 18:41:32,585] Trial 160 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.0296446158123046, 'n_estimators': 518, 'subsample': 0.7959528769671121, 'colsample_bytree': 0.6565265594358686, 'min_child_weight': 6, 'gamma': 0.6230987586829829, 'reg_alpha': 0.11932241268401944, 'reg_lambda': 0.7043463972986562, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  80%|████████  | 161/200 [02:06<00:27,  1.42it/s]

[I 2025-11-10 18:41:33,146] Trial 162 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.03042513616707532, 'n_estimators': 255, 'subsample': 0.6922118552933852, 'colsample_bytree': 0.6071169130305811, 'min_child_weight': 8, 'gamma': 0.7952490200713634, 'reg_alpha': 0.10410513327402247, 'reg_lambda': 1.0822343751326472e-05, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  81%|████████  | 162/200 [02:07<00:27,  1.37it/s]

[I 2025-11-10 18:41:33,935] Trial 159 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.05079984973200028, 'n_estimators': 904, 'subsample': 0.6939399681208018, 'colsample_bytree': 0.6071652255020278, 'min_child_weight': 6, 'gamma': 0.836838214523567, 'reg_alpha': 1.7719148489257386, 'reg_lambda': 5.640211856342962e-08, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  82%|████████▏ | 163/200 [02:07<00:22,  1.63it/s]

[I 2025-11-10 18:41:34,273] Trial 161 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.0295471799217125, 'n_estimators': 888, 'subsample': 0.7105563392793378, 'colsample_bytree': 0.6064927714747895, 'min_child_weight': 8, 'gamma': 0.8790159119885828, 'reg_alpha': 1.6259439842062813, 'reg_lambda': 2.972773507494202e-07, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:41:34,280] Trial 163 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.13499656966993592, 'n_estimators': 365, 'subsample': 0.6904228772358464, 'colsample_bytree': 0.5007706128214893, 'min_child_weight': 5, 'gamma': 1.882811002174536, 'reg_alpha': 0.0762132828041689, 'reg_lambda': 2.4812295674331144e-07, 'max_delta_step': 3}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  82%|████████▎ | 165/200 [02:08<00:20,  1.67it/s]

[I 2025-11-10 18:41:35,434] Trial 164 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.14742257723946361, 'n_estimators': 475, 'subsample': 0.6153444002491089, 'colsample_bytree': 0.8409252786804439, 'min_child_weight': 6, 'gamma': 1.9610127523791672, 'reg_alpha': 0.7476315169121872, 'reg_lambda': 0.12263208611182151, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  83%|████████▎ | 166/200 [02:09<00:22,  1.53it/s]

[I 2025-11-10 18:41:36,271] Trial 165 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.14644695875682343, 'n_estimators': 491, 'subsample': 0.6192240123275203, 'colsample_bytree': 0.7570382669187183, 'min_child_weight': 5, 'gamma': 1.3399506977311548, 'reg_alpha': 3.750577213115883e-08, 'reg_lambda': 0.001658277709355329, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  84%|████████▎ | 167/200 [02:10<00:18,  1.80it/s]

[I 2025-11-10 18:41:36,540] Trial 167 finished with value: 0.49766081871345025 and parameters: {'max_depth': 8, 'learning_rate': 0.15225477952688027, 'n_estimators': 467, 'subsample': 0.6226483264593015, 'colsample_bytree': 0.8446255820306076, 'min_child_weight': 4, 'gamma': 2.24260794016392, 'reg_alpha': 0.5355654872089314, 'reg_lambda': 0.11649805055714424, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:41:36,555] Trial 166 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.15234658405277104, 'n_estimators': 484, 'subsample': 0.639433380070459, 'colsample_bytree': 0.7432012110543533, 'min_child_weight': 6, 'gamma': 2.192592902846026, 'reg_alpha': 3.0160334312636626e-07, 'reg_lambda': 0.1343517628363923, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  84%|████████▍ | 169/200 [02:10<00:11,  2.79it/s]

[I 2025-11-10 18:41:36,726] Trial 169 pruned.

Best trial: 1. Best value: 0.5:  86%|████████▌ | 171/200 [02:12<00:16,  1.77it/s]

[I 2025-11-10 18:41:38,595] Trial 171 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.07686887247903779, 'n_estimators': 444, 'subsample': 0.7767805045473541, 'colsample_bytree': 0.5732363579690026, 'min_child_weight': 8, 'gamma': 2.75441471849017, 'reg_alpha': 0.040996791458496926, 'reg_lambda': 6.458152178669465e-06, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:41:38,723] Trial 170 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.07724408023673844, 'n_estimators': 445, 'subsample': 0.645153887684889, 'colsample_bytree': 0.6723485814648683, 'min_child_weight': 6, 'gamma': 2.7020542288561957, 'reg_alpha': 3.0704697101127746e-07, 'reg_lambda': 1.3857752165331888e-06, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  86%|████████▌ | 172/200 [02:12<00:12,  2.25it/s]

[I 2025-11-10 18:41:38,834] Trial 172 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.0359541694630848, 'n_estimators': 435, 'subsample': 0.6580466897322602, 'colsample_bytree': 0.7232791517361499, 'min_child_weight': 8, 'gamma': 3.9474671892348674, 'reg_alpha': 0.03884139715120927, 'reg_lambda': 1.4567260838369698e-06, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  86%|████████▋ | 173/200 [02:14<00:21,  1.27it/s]

[I 2025-11-10 18:41:40,536] Trial 173 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1226513053275387, 'n_estimators': 398, 'subsample': 0.6565299747284381, 'colsample_bytree': 0.8612991321947613, 'min_child_weight': 9, 'gamma': 4.631277285909478, 'reg_alpha': 0.01643989081156671, 'reg_lambda': 0.0004446979941281201, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  87%|████████▋ | 174/200 [02:14<00:20,  1.25it/s]

[I 2025-11-10 18:41:41,357] Trial 168 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.11994928967601473, 'n_estimators': 1295, 'subsample': 0.6547447734769152, 'colsample_bytree': 0.7953803993418478, 'min_child_weight': 5, 'gamma': 4.8425932607599815, 'reg_alpha': 0.04173720993478279, 'reg_lambda': 0.0017179975657845368, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  88%|████████▊ | 176/200 [02:16<00:18,  1.29it/s]

[I 2025-11-10 18:41:43,002] Trial 175 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.12246596880414011, 'n_estimators': 958, 'subsample': 0.5185818382505474, 'colsample_bytree': 0.5948075613210086, 'min_child_weight': 10, 'gamma': 4.89084592582769, 'reg_alpha': 0.0639702366695106, 'reg_lambda': 1.4807005161587729e-08, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:41:43,131] Trial 174 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.047418541209688074, 'n_estimators': 932, 'subsample': 0.5140738152485622, 'colsample_bytree': 0.7939194768805089, 'min_child_weight': 10, 'gamma': 4.863194729028021, 'reg_alpha': 0.1460137952216213, 'reg_lambda': 0.00037067087576013235, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  88%|████████▊ | 177/200 [02:18<00:22,  1.02it/s]

[I 2025-11-10 18:41:44,609] Trial 176 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.013878957653376867, 'n_estimators': 932, 'subsample': 0.5103517048975519, 'colsample_bytree': 0.5869229618783931, 'min_child_weight': 10, 'gamma': 4.163475764324707, 'reg_alpha': 0.15501127713251642, 'reg_lambda': 4.101464467296618e-08, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  89%|████████▉ | 178/200 [02:19<00:21,  1.01it/s]

[I 2025-11-10 18:41:45,635] Trial 177 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.014737026710137215, 'n_estimators': 985, 'subsample': 0.5101086342191297, 'colsample_bytree': 0.5935279596232017, 'min_child_weight': 10, 'gamma': 4.294334549801147, 'reg_alpha': 0.15222460220707584, 'reg_lambda': 1.5040729033846254e-08, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  90%|████████▉ | 179/200 [02:20<00:25,  1.22s/it]

[I 2025-11-10 18:41:47,377] Trial 178 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.012194626814984568, 'n_estimators': 1009, 'subsample': 0.5726543080397449, 'colsample_bytree': 0.5891853243149452, 'min_child_weight': 10, 'gamma': 3.619916873212486, 'reg_alpha': 0.14663291941474219, 'reg_lambda': 0.21377425187085203, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  90%|█████████ | 180/200 [02:21<00:18,  1.06it/s]

[I 2025-11-10 18:41:47,662] Trial 179 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01473483856298588, 'n_estimators': 985, 'subsample': 0.5338688387024061, 'colsample_bytree': 0.7659291639047993, 'min_child_weight': 10, 'gamma': 3.774794866666062, 'reg_alpha': 0.0008248252261382157, 'reg_lambda': 4.6502194631953564e-07, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  90%|█████████ | 181/200 [02:22<00:17,  1.11it/s]

[I 2025-11-10 18:41:48,476] Trial 180 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.014795424561129991, 'n_estimators': 865, 'subsample': 0.815574681610041, 'colsample_bytree': 0.6422685863502973, 'min_child_weight': 10, 'gamma': 1.1377645317636063, 'reg_alpha': 4.176089660022812, 'reg_lambda': 2.2326697764793506e-06, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  91%|█████████ | 182/200 [02:22<00:13,  1.29it/s]

[I 2025-11-10 18:41:48,944] Trial 181 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.13243151042595525, 'n_estimators': 731, 'subsample': 0.5548507333306174, 'colsample_bytree': 0.5308327514434785, 'min_child_weight': 10, 'gamma': 3.772111971159725, 'reg_alpha': 1.0688390485215434e-06, 'reg_lambda': 0.18349258035625982, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  92%|█████████▏| 183/200 [02:24<00:17,  1.01s/it]

[I 2025-11-10 18:41:50,528] Trial 183 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.1328939300291008, 'n_estimators': 617, 'subsample': 0.5553081685904382, 'colsample_bytree': 0.5073458837586343, 'min_child_weight': 8, 'gamma': 4.724097802213958, 'reg_alpha': 4.583337389060229, 'reg_lambda': 0.004950341910031679, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  92%|█████████▏| 184/200 [02:26<00:22,  1.42s/it]

[I 2025-11-10 18:41:52,895] Trial 185 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.010485612731010825, 'n_estimators': 908, 'subsample': 0.5290345175242499, 'colsample_bytree': 0.5595707599143328, 'min_child_weight': 10, 'gamma': 4.099774681881348, 'reg_alpha': 0.08500919345279181, 'reg_lambda': 1.5915654669998688e-07, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  92%|█████████▎| 185/200 [02:27<00:17,  1.18s/it]

[I 2025-11-10 18:41:53,523] Trial 186 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07185423980013295, 'n_estimators': 698, 'subsample': 0.5314780875058615, 'colsample_bytree': 0.5633577205257042, 'min_child_weight': 10, 'gamma': 4.02348589235055, 'reg_alpha': 5.406699657777844e-05, 'reg_lambda': 0.07692147766165926, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  93%|█████████▎| 186/200 [02:27<00:13,  1.07it/s]

[I 2025-11-10 18:41:53,880] Trial 182 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.010328697555829795, 'n_estimators': 1436, 'subsample': 0.8087546055742704, 'colsample_bytree': 0.6384177248000293, 'min_child_weight': 10, 'gamma': 4.543022325914865, 'reg_alpha': 6.314202577686542e-05, 'reg_lambda': 0.06949870576728505, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  94%|█████████▎| 187/200 [02:28<00:12,  1.07it/s]

[I 2025-11-10 18:41:54,822] Trial 184 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.057801179730438454, 'n_estimators': 1439, 'subsample': 0.5286132033476874, 'colsample_bytree': 0.5414854057609687, 'min_child_weight': 10, 'gamma': 4.397957724684328, 'reg_alpha': 0.06848692189826436, 'reg_lambda': 6.120359234557288e-08, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  94%|█████████▍| 188/200 [02:31<00:18,  1.51s/it]

[I 2025-11-10 18:41:57,665] Trial 189 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.057019117278881204, 'n_estimators': 865, 'subsample': 0.7624719122236713, 'colsample_bytree': 0.5450833199086188, 'min_child_weight': 8, 'gamma': 4.4150092234400224, 'reg_alpha': 0.0002116358022385665, 'reg_lambda': 5.990267655360596e-08, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  94%|█████████▍| 189/200 [02:31<00:12,  1.17s/it]

[I 2025-11-10 18:41:58,029] Trial 187 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.06923571968040453, 'n_estimators': 1143, 'subsample': 0.7948427472734585, 'colsample_bytree': 0.5436224473858592, 'min_child_weight': 10, 'gamma': 4.513859624210117, 'reg_alpha': 7.542933801536225, 'reg_lambda': 0.073026810527168, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  95%|█████████▌| 190/200 [02:32<00:11,  1.17s/it]

[I 2025-11-10 18:41:59,219] Trial 190 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.06500223384878857, 'n_estimators': 1025, 'subsample': 0.7634564510055721, 'colsample_bytree': 0.5184401899269394, 'min_child_weight': 9, 'gamma': 4.26386875542853, 'reg_alpha': 0.0001093688046475767, 'reg_lambda': 1.200387314780589e-07, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  96%|█████████▌| 191/200 [02:33<00:08,  1.01it/s]

[I 2025-11-10 18:41:59,793] Trial 188 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.05938399831158827, 'n_estimators': 1430, 'subsample': 0.7656714188778757, 'colsample_bytree': 0.5437371161167149, 'min_child_weight': 8, 'gamma': 4.300149793821465, 'reg_alpha': 8.388464940882087e-08, 'reg_lambda': 2.2395734207385137e-07, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:41:59,801] Trial 192 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.06476334583906805, 'n_estimators': 382, 'subsample': 0.5032924575922638, 'colsample_bytree': 0.5720927910395187, 'min_child_weight': 9, 'gamma': 4.22230340299342, 'reg_alpha': 0.003239920097346969, 'reg_lambda': 1.2739678922212885e-07, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  96%|█████████▋| 193/200 [02:33<00:04,  1.49it/s]

[I 2025-11-10 18:42:00,390] Trial 193 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09737607638108778, 'n_estimators': 217, 'subsample': 0.5031929528085128, 'colsample_bytree': 0.5003848744734021, 'min_child_weight': 8, 'gamma': 1.7449598669976913, 'reg_alpha': 0.0033211682790644163, 'reg_lambda': 3.176078019667938e-06, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  97%|█████████▋| 194/200 [02:34<00:03,  1.56it/s]

[I 2025-11-10 18:42:00,937] Trial 194 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.0842352234212126, 'n_estimators': 204, 'subsample': 0.5037240131559878, 'colsample_bytree': 0.5843689596400753, 'min_child_weight': 10, 'gamma': 3.931107642541193, 'reg_alpha': 0.02944066471853529, 'reg_lambda': 0.00794694031021725, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  98%|█████████▊| 196/200 [02:37<00:03,  1.11it/s]

[I 2025-11-10 18:42:03,652] Trial 191 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.08360852352469314, 'n_estimators': 1345, 'subsample': 0.5048308396406311, 'colsample_bytree': 0.5732429942581238, 'min_child_weight': 9, 'gamma': 3.930095423367365, 'reg_alpha': 9.638981034543724, 'reg_lambda': 0.0033061492815226537, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:42:03,782] Trial 195 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.09333389721133815, 'n_estimators': 886, 'subsample': 0.5024090264571165, 'colsample_bytree': 0.5766794455733698, 'min_child_weight': 10, 'gamma': 3.906415036197962, 'reg_alpha': 0.028974090750078764, 'reg_lambda': 3.338351996111332e-07, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  98%|█████████▊| 197/200 [02:37<00:02,  1.26it/s]

[I 2025-11-10 18:42:04,303] Trial 196 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.05262411160412581, 'n_estimators': 875, 'subsample': 0.5155604553106573, 'colsample_bytree': 0.5771789345964659, 'min_child_weight': 10, 'gamma': 2.6033854906010587, 'reg_alpha': 0.0012899582535512825, 'reg_lambda': 4.17938703938789e-08, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  99%|█████████▉| 198/200 [02:38<00:01,  1.48it/s]

[I 2025-11-10 18:42:04,695] Trial 197 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03205775464426508, 'n_estimators': 896, 'subsample': 0.783911927349939, 'colsample_bytree': 0.5712563783512439, 'min_child_weight': 10, 'gamma': 4.620736651254383, 'reg_alpha': 0.2697570499735963, 'reg_lambda': 3.544983494716766e-07, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5: 100%|██████████| 200/200 [02:39<00:00,  1.25it/s]

[I 2025-11-10 18:42:06,105] Trial 198 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.05198456333657581, 'n_estimators': 891, 'subsample': 0.7532359558256265, 'colsample_bytree': 0.5591542368844955, 'min_child_weight': 10, 'gamma': 4.634459274386945, 'reg_alpha': 0.0013356512840272021, 'reg_lambda': 3.5878618888026336e-07, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.
[I 2025-11-10 18:42:06,167] Trial 199 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.0259450437896429, 'n_estimators': 912, 'subsample': 0.520009876070756, 'colsample_bytree': 0.5219528143466013, 'min_child_weight': 7, 'gamma': 4.721170066656653, 'reg_alpha': 0.0012951674166229263, 'reg_lambda': 4.0773683641126854e-08, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

[I 2025-11-10 18:42:06,945] A new study created in memory with name: 3_3_roc_auc
Best trial: 3. Best value: 0.5:   0%|          | 1/200 [00:01<04:29,  1.36s/it]

[I 2025-11-10 18:42:08,295] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.01707064859601557, 'n_estimators': 322, 'subsample': 0.7096695234322042, 'colsample_bytree': 0.8693534536949608, 'min_child_weight': 7, 'gamma': 0.7140762137298556, 'reg_alpha': 4.3891869798248056e-07, 'reg_lambda': 5.666982859283244e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   1%|          | 2/200 [00:01<02:21,  1.40it/s]

[I 2025-11-10 18:42:08,559] Trial 0 finished with value: 0.49902534113060437 and parameters: {'max_depth': 10, 'learning_rate': 0.02260383128377193, 'n_estimators': 230, 'subsample': 0.8233209414762171, 'colsample_bytree': 0.7414696224924459, 'min_child_weight': 2, 'gamma': 3.922629517152067, 'reg_alpha': 2.1788103742482416e-06, 'reg_lambda': 3.1195951167622044e-05, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.
[I 2025-11-10 18:42:08,742] Trial 1 finished with value: 0.5680701754385964 and parameters: {'max_depth': 3, 'learning_rate': 0.06841841759153017, 'n_estimators': 313, 'subsample': 0.7278426199582694, 'colsample_bytree': 0.686129146659588, 'min_child_weight': 2, 'gamma': 2.994029827704549, 'reg_alpha': 0.033384017488533986, 'reg_lambda': 0.001378303062134428, 'max_delta_step': 0}. Best is trial 1 with value: 0.5680701754385964.

Best trial: 1. Best value: 0.56807:   2%|▏         | 4/200 [00:03<03:11,  1.02it/s]

[I 2025-11-10 18:42:10,488] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.11706812151665698, 'n_estimators': 967, 'subsample': 0.7792121911607917, 'colsample_bytree': 0.6386733358444632, 'min_child_weight': 9, 'gamma': 3.514739051051592, 'reg_alpha': 3.1336607235217533e-07, 'reg_lambda': 8.263581641159701e-08, 'max_delta_step': 8}. Best is trial 1 with value: 0.5680701754385964.

Best trial: 1. Best value: 0.56807:   2%|▎         | 5/200 [00:03<02:31,  1.28it/s]

[I 2025-11-10 18:42:10,924] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.07219835221437954, 'n_estimators': 596, 'subsample': 0.593531801636509, 'colsample_bytree': 0.9152382750202186, 'min_child_weight': 10, 'gamma': 0.7219150566450933, 'reg_alpha': 5.073148750595219e-06, 'reg_lambda': 0.00016699849572324776, 'max_delta_step': 1}. Best is trial 1 with value: 0.5680701754385964.

Best trial: 1. Best value: 0.56807:   3%|▎         | 6/200 [00:04<02:35,  1.25it/s]

[I 2025-11-10 18:42:11,759] Trial 6 finished with value: 0.5643664717348928 and parameters: {'max_depth': 7, 'learning_rate': 0.021959621238564285, 'n_estimators': 582, 'subsample': 0.9040351334148466, 'colsample_bytree': 0.6769795704429126, 'min_child_weight': 3, 'gamma': 3.0043962130518582, 'reg_alpha': 3.642234609968623e-05, 'reg_lambda': 1.07204620942524, 'max_delta_step': 0}. Best is trial 1 with value: 0.5680701754385964.

Best trial: 1. Best value: 0.56807:   4%|▎         | 7/200 [00:05<01:59,  1.62it/s]

[I 2025-11-10 18:42:12,004] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.23745206990308657, 'n_estimators': 277, 'subsample': 0.633476584244796, 'colsample_bytree': 0.5840499740956637, 'min_child_weight': 9, 'gamma': 4.609513197503471, 'reg_alpha': 7.215325160326948e-05, 'reg_lambda': 0.00011617564804028103, 'max_delta_step': 2}. Best is trial 1 with value: 0.5680701754385964.

Best trial: 1. Best value: 0.56807:   4%|▍         | 8/200 [00:05<01:41,  1.89it/s]

[I 2025-11-10 18:42:12,345] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.22260856886121147, 'n_estimators': 462, 'subsample': 0.938747045866239, 'colsample_bytree': 0.7681292161380494, 'min_child_weight': 6, 'gamma': 3.2740468382096974, 'reg_alpha': 0.0022652453914977643, 'reg_lambda': 1.998130738226809e-05, 'max_delta_step': 2}. Best is trial 1 with value: 0.5680701754385964.

Best trial: 1. Best value: 0.56807:   4%|▍         | 9/200 [00:06<01:59,  1.60it/s]

[I 2025-11-10 18:42:13,183] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07741693340503447, 'n_estimators': 205, 'subsample': 0.9596835143784541, 'colsample_bytree': 0.5413908886581711, 'min_child_weight': 6, 'gamma': 4.010695761265453, 'reg_alpha': 0.013566781537946467, 'reg_lambda': 0.0001897196931263914, 'max_delta_step': 3}. Best is trial 1 with value: 0.5680701754385964.

Best trial: 1. Best value: 0.56807:   5%|▌         | 10/200 [00:07<02:35,  1.22it/s]

[I 2025-11-10 18:42:14,440] Trial 9 finished with value: 0.5358479532163744 and parameters: {'max_depth': 8, 'learning_rate': 0.02167766630128866, 'n_estimators': 276, 'subsample': 0.9605202993833037, 'colsample_bytree': 0.5478247523062456, 'min_child_weight': 2, 'gamma': 0.5191843820272918, 'reg_alpha': 4.226625762788874e-08, 'reg_lambda': 1.1840246484819093e-08, 'max_delta_step': 1}. Best is trial 1 with value: 0.5680701754385964.

Best trial: 1. Best value: 0.56807:   6%|▌         | 11/200 [00:09<04:03,  1.29s/it]

[I 2025-11-10 18:42:16,781] Trial 4 finished with value: 0.535906432748538 and parameters: {'max_depth': 9, 'learning_rate': 0.01108999699484645, 'n_estimators': 1092, 'subsample': 0.6883634635913396, 'colsample_bytree': 0.8207465056764686, 'min_child_weight': 1, 'gamma': 3.101617374546472, 'reg_alpha': 0.0002823137136869017, 'reg_lambda': 0.012229333901963336, 'max_delta_step': 1}. Best is trial 1 with value: 0.5680701754385964.

Best trial: 1. Best value: 0.56807:   6%|▌         | 12/200 [00:10<03:07,  1.00it/s]

[I 2025-11-10 18:42:17,109] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.11915101556772917, 'n_estimators': 1385, 'subsample': 0.8928753893286188, 'colsample_bytree': 0.6391527040711713, 'min_child_weight': 8, 'gamma': 1.6593085936982566, 'reg_alpha': 0.005880660459329665, 'reg_lambda': 1.2894816137510775e-06, 'max_delta_step': 6}. Best is trial 1 with value: 0.5680701754385964.

Best trial: 1. Best value: 0.56807:   6%|▋         | 13/200 [00:10<02:29,  1.25it/s]

[I 2025-11-10 18:42:17,460] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07936045724728671, 'n_estimators': 1088, 'subsample': 0.8730533505415201, 'colsample_bytree': 0.8341693344425702, 'min_child_weight': 7, 'gamma': 4.705091582958878, 'reg_alpha': 5.562135366364846e-05, 'reg_lambda': 0.00027957805109511127, 'max_delta_step': 2}. Best is trial 1 with value: 0.5680701754385964.

Best trial: 1. Best value: 0.56807:   7%|▋         | 14/200 [00:12<03:45,  1.21s/it]

[I 2025-11-10 18:42:19,624] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04006054216628905, 'n_estimators': 660, 'subsample': 0.5149128951614556, 'colsample_bytree': 0.6899610110052158, 'min_child_weight': 4, 'gamma': 2.0206219998683066, 'reg_alpha': 3.4721399239968713, 'reg_lambda': 8.446848541836895, 'max_delta_step': 0}. Best is trial 1 with value: 0.5680701754385964.

Best trial: 1. Best value: 0.56807:   8%|▊         | 16/200 [00:13<02:09,  1.42it/s]

[I 2025-11-10 18:42:20,025] Trial 13 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.040215382075088166, 'n_estimators': 1369, 'subsample': 0.5053432252630797, 'colsample_bytree': 0.7852160095600059, 'min_child_weight': 4, 'gamma': 1.9592921619508736, 'reg_alpha': 2.4016800856866616, 'reg_lambda': 0.09062138084698271, 'max_delta_step': 10}. Best is trial 1 with value: 0.5680701754385964.
[I 2025-11-10 18:42:20,128] Trial 15 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0413147951405365, 'n_estimators': 661, 'subsample': 0.8352047637283979, 'colsample_bytree': 0.7087705172499406, 'min_child_weight': 4, 'gamma': 2.0743648313936447, 'reg_alpha': 4.365689264854125, 'reg_lambda': 8.593666325545765, 'max_delta_step': 0}. Best is trial 1 with value: 0.5680701754385964.

Best trial: 1. Best value: 0.56807:   8%|▊         | 17/200 [00:13<01:40,  1.83it/s]

[I 2025-11-10 18:42:20,308] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03670185707495381, 'n_estimators': 665, 'subsample': 0.5183356518574077, 'colsample_bytree': 0.697903438798115, 'min_child_weight': 4, 'gamma': 2.226795389296487, 'reg_alpha': 1.9513218654801667, 'reg_lambda': 6.508705603404372, 'max_delta_step': 0}. Best is trial 1 with value: 0.5680701754385964.

Best trial: 17. Best value: 0.57731:   9%|▉         | 18/200 [00:15<03:16,  1.08s/it]

[I 2025-11-10 18:42:22,628] Trial 17 finished with value: 0.5773099415204678 and parameters: {'max_depth': 5, 'learning_rate': 0.03820940279299304, 'n_estimators': 639, 'subsample': 0.7931581381332384, 'colsample_bytree': 0.9752542467401613, 'min_child_weight': 4, 'gamma': 2.688309271259514, 'reg_alpha': 0.17279417063275307, 'reg_lambda': 0.16239476147950754, 'max_delta_step': 10}. Best is trial 17 with value: 0.5773099415204678.

Best trial: 19. Best value: 0.579591:  10%|▉         | 19/200 [00:15<02:29,  1.21it/s]

[I 2025-11-10 18:42:22,864] Trial 19 finished with value: 0.5795906432748538 and parameters: {'max_depth': 6, 'learning_rate': 0.01055299002317095, 'n_estimators': 441, 'subsample': 0.7606661647281743, 'colsample_bytree': 0.6365998657007572, 'min_child_weight': 3, 'gamma': 2.758883004316451, 'reg_alpha': 0.12322320866219323, 'reg_lambda': 0.019155122732698933, 'max_delta_step': 4}. Best is trial 19 with value: 0.5795906432748538.

Best trial: 18. Best value: 0.588343:  10%|█         | 20/200 [00:16<02:08,  1.40it/s]

[I 2025-11-10 18:42:23,316] Trial 18 finished with value: 0.5883430799220273 and parameters: {'max_depth': 5, 'learning_rate': 0.03631649860422886, 'n_estimators': 704, 'subsample': 0.7787909764352364, 'colsample_bytree': 0.9918218109138991, 'min_child_weight': 4, 'gamma': 2.5998841906971513, 'reg_alpha': 0.1405475047573884, 'reg_lambda': 0.027719477338027036, 'max_delta_step': 0}. Best is trial 18 with value: 0.5883430799220273.
[I 2025-11-10 18:42:23,342] Trial 21 pruned.

Best trial: 18. Best value: 0.588343:  11%|█         | 22/200 [00:16<01:29,  1.99it/s]

[I 2025-11-10 18:42:23,830] Trial 20 finished with value: 0.5496491228070175 and parameters: {'max_depth': 6, 'learning_rate': 0.011407930214762264, 'n_estimators': 479, 'subsample': 0.757902756905223, 'colsample_bytree': 0.6382474549217629, 'min_child_weight': 2, 'gamma': 2.7399780518951653, 'reg_alpha': 0.11283470686602598, 'reg_lambda': 0.005222168214495476, 'max_delta_step': 4}. Best is trial 18 with value: 0.5883430799220273.

Best trial: 18. Best value: 0.588343:  12%|█▏        | 23/200 [00:19<03:03,  1.04s/it]

[I 2025-11-10 18:42:26,479] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.01029710154088371, 'n_estimators': 830, 'subsample': 0.7776269585230037, 'colsample_bytree': 0.9634618113311211, 'min_child_weight': 5, 'gamma': 1.397074336567831, 'reg_alpha': 0.1923898345925205, 'reg_lambda': 0.07654553240769774, 'max_delta_step': 10}. Best is trial 18 with value: 0.5883430799220273.

Best trial: 18. Best value: 0.588343:  12%|█▏        | 24/200 [00:19<02:34,  1.14it/s]

[I 2025-11-10 18:42:26,903] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.010023141644816075, 'n_estimators': 814, 'subsample': 0.6613851295296789, 'colsample_bytree': 0.9722662394046974, 'min_child_weight': 5, 'gamma': 1.174387391266034, 'reg_alpha': 0.13629667633262424, 'reg_lambda': 0.005404654755114414, 'max_delta_step': 5}. Best is trial 18 with value: 0.5883430799220273.
[I 2025-11-10 18:42:26,919] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.011062771309189773, 'n_estimators': 811, 'subsample': 0.7919996246606924, 'colsample_bytree': 0.9825811398328197, 'min_child_weight': 5, 'gamma': 2.5976363341535684, 'reg_alpha': 0.23820971774591854, 'reg_lambda': 0.11804342943727693, 'max_delta_step': 8}. Best is trial 18 with value: 0.5883430799220273.

Best trial: 18. Best value: 0.588343:  13%|█▎        | 26/200 [00:20<01:44,  1.66it/s]

[I 2025-11-10 18:42:27,379] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.027897453819396133, 'n_estimators': 807, 'subsample': 0.803789340066681, 'colsample_bytree': 0.985831479056861, 'min_child_weight': 5, 'gamma': 2.594135227250237, 'reg_alpha': 0.2791032246771858, 'reg_lambda': 0.09775230198018857, 'max_delta_step': 8}. Best is trial 18 with value: 0.5883430799220273.

Best trial: 18. Best value: 0.588343:  14%|█▎        | 27/200 [00:22<03:01,  1.05s/it]

[I 2025-11-10 18:42:29,893] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.029817956605227427, 'n_estimators': 810, 'subsample': 0.8150558571447959, 'colsample_bytree': 0.9350715794138196, 'min_child_weight': 5, 'gamma': 2.520040585698753, 'reg_alpha': 0.0012229592244212544, 'reg_lambda': 0.15415998609698203, 'max_delta_step': 8}. Best is trial 18 with value: 0.5883430799220273.

Best trial: 28. Best value: 0.602027:  14%|█▍        | 28/200 [00:24<03:09,  1.10s/it]

[I 2025-11-10 18:42:31,141] Trial 27 finished with value: 0.577270955165692 and parameters: {'max_depth': 4, 'learning_rate': 0.027808703461851835, 'n_estimators': 782, 'subsample': 0.8153670095480998, 'colsample_bytree': 0.9195672971083948, 'min_child_weight': 3, 'gamma': 2.5841712336982194, 'reg_alpha': 0.001530118702897868, 'reg_lambda': 0.11445268727640401, 'max_delta_step': 7}. Best is trial 18 with value: 0.5883430799220273.
[I 2025-11-10 18:42:31,233] Trial 28 finished with value: 0.602027290448343 and parameters: {'max_depth': 4, 'learning_rate': 0.02956857876029857, 'n_estimators': 954, 'subsample': 0.8383049877275908, 'colsample_bytree': 0.9352751492722506, 'min_child_weight': 4, 'gamma': 3.6843612302522875, 'reg_alpha': 0.001382508733473961, 'reg_lambda': 0.34766441849130064, 'max_delta_step': 8}. Best is trial 28 with value: 0.602027290448343.

Best trial: 28. Best value: 0.602027:  15%|█▌        | 30/200 [00:25<02:38,  1.07it/s]

[I 2025-11-10 18:42:32,527] Trial 29 finished with value: 0.5623781676413255 and parameters: {'max_depth': 4, 'learning_rate': 0.015047793575031467, 'n_estimators': 942, 'subsample': 0.860536474531221, 'colsample_bytree': 0.8914482528659365, 'min_child_weight': 3, 'gamma': 3.6079620948026228, 'reg_alpha': 0.001493780928391659, 'reg_lambda': 0.6528542180909291, 'max_delta_step': 7}. Best is trial 28 with value: 0.602027290448343.

Best trial: 28. Best value: 0.602027:  16%|█▌        | 31/200 [00:28<03:51,  1.37s/it]

[I 2025-11-10 18:42:35,360] Trial 30 finished with value: 0.5564327485380117 and parameters: {'max_depth': 4, 'learning_rate': 0.016376225708839478, 'n_estimators': 955, 'subsample': 0.9997291300461529, 'colsample_bytree': 0.9173635073367572, 'min_child_weight': 3, 'gamma': 3.390508626238508, 'reg_alpha': 0.024666496585933992, 'reg_lambda': 0.46118903802185335, 'max_delta_step': 6}. Best is trial 28 with value: 0.602027290448343.

Best trial: 28. Best value: 0.602027:  16%|█▌        | 32/200 [00:28<03:00,  1.08s/it]

[I 2025-11-10 18:42:35,552] Trial 31 finished with value: 0.5829044834307993 and parameters: {'max_depth': 7, 'learning_rate': 0.05437856196363963, 'n_estimators': 965, 'subsample': 0.6941449969685162, 'colsample_bytree': 0.8673164610967937, 'min_child_weight': 3, 'gamma': 3.4082681763969003, 'reg_alpha': 0.7590372441729212, 'reg_lambda': 0.866656067348495, 'max_delta_step': 4}. Best is trial 28 with value: 0.602027290448343.

Best trial: 28. Best value: 0.602027:  16%|█▋        | 33/200 [00:29<02:46,  1.00it/s]

[I 2025-11-10 18:42:36,322] Trial 32 finished with value: 0.5875828460038987 and parameters: {'max_depth': 4, 'learning_rate': 0.016400915476601097, 'n_estimators': 954, 'subsample': 0.8511828854883877, 'colsample_bytree': 0.8656537481053534, 'min_child_weight': 3, 'gamma': 3.83195539834626, 'reg_alpha': 0.01690525196626088, 'reg_lambda': 0.9180862716016928, 'max_delta_step': 6}. Best is trial 28 with value: 0.602027290448343.

Best trial: 34. Best value: 0.634893:  18%|█▊        | 35/200 [00:31<02:26,  1.13it/s]

[I 2025-11-10 18:42:37,994] Trial 36 pruned.
[I 2025-11-10 18:42:38,131] Trial 34 finished with value: 0.6348927875243664 and parameters: {'max_depth': 5, 'learning_rate': 0.053003168626715336, 'n_estimators': 532, 'subsample': 0.8469444033043555, 'colsample_bytree': 0.8710771524077349, 'min_child_weight': 4, 'gamma': 3.8802097317355146, 'reg_alpha': 0.9959803731037314, 'reg_lambda': 0.021639032692207523, 'max_delta_step': 9}. Best is trial 34 with value: 0.6348927875243664.

Best trial: 34. Best value: 0.634893:  18%|█▊        | 36/200 [00:32<02:24,  1.14it/s]

[I 2025-11-10 18:42:38,988] Trial 33 finished with value: 0.5778362573099416 and parameters: {'max_depth': 7, 'learning_rate': 0.05381092860660567, 'n_estimators': 1265, 'subsample': 0.8377351691776306, 'colsample_bytree': 0.8308345089796743, 'min_child_weight': 3, 'gamma': 4.0255828183598386, 'reg_alpha': 0.020249687613129813, 'reg_lambda': 0.016035323802221217, 'max_delta_step': 5}. Best is trial 34 with value: 0.6348927875243664.

Best trial: 34. Best value: 0.634893:  18%|█▊        | 37/200 [00:34<03:25,  1.26s/it]

[I 2025-11-10 18:42:41,177] Trial 35 finished with value: 0.5715594541910332 and parameters: {'max_depth': 7, 'learning_rate': 0.05434819645927523, 'n_estimators': 1148, 'subsample': 0.7009674084200254, 'colsample_bytree': 0.8655712592451392, 'min_child_weight': 3, 'gamma': 4.164320374537222, 'reg_alpha': 1.0274730412898543, 'reg_lambda': 0.021138686929127366, 'max_delta_step': 4}. Best is trial 34 with value: 0.6348927875243664.

Best trial: 34. Best value: 0.634893:  19%|█▉        | 38/200 [00:35<03:05,  1.14s/it]

[I 2025-11-10 18:42:42,043] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.01876121748328812, 'n_estimators': 738, 'subsample': 0.8901148500722457, 'colsample_bytree': 0.9386803004688814, 'min_child_weight': 6, 'gamma': 3.7358612302517917, 'reg_alpha': 0.005160957109841702, 'reg_lambda': 0.0013356681950605174, 'max_delta_step': 9}. Best is trial 34 with value: 0.6348927875243664.

Best trial: 34. Best value: 0.634893:  20%|█▉        | 39/200 [00:35<02:45,  1.03s/it]

[I 2025-11-10 18:42:42,795] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0590079595348294, 'n_estimators': 1158, 'subsample': 0.8978244099615277, 'colsample_bytree': 0.8125122497299216, 'min_child_weight': 6, 'gamma': 4.37665648312031, 'reg_alpha': 8.880652406024227, 'reg_lambda': 0.018580123357645365, 'max_delta_step': 9}. Best is trial 34 with value: 0.6348927875243664.

Best trial: 34. Best value: 0.634893:  20%|██        | 40/200 [00:36<02:17,  1.16it/s]

[I 2025-11-10 18:42:43,262] Trial 41 pruned.

Best trial: 34. Best value: 0.634893:  20%|██        | 41/200 [00:37<02:11,  1.21it/s]

[I 2025-11-10 18:42:43,998] Trial 37 finished with value: 0.5753801169590643 and parameters: {'max_depth': 4, 'learning_rate': 0.049666507917986664, 'n_estimators': 1277, 'subsample': 0.7054914719395712, 'colsample_bytree': 0.8860867274204068, 'min_child_weight': 3, 'gamma': 4.232525495907675, 'reg_alpha': 0.009601336298135863, 'reg_lambda': 0.0009969898355712756, 'max_delta_step': 9}. Best is trial 34 with value: 0.6348927875243664.

Best trial: 34. Best value: 0.634893:  21%|██        | 42/200 [00:37<01:42,  1.55it/s]

[I 2025-11-10 18:42:44,227] Trial 40 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.019257647236022, 'n_estimators': 724, 'subsample': 0.9026787536221788, 'colsample_bytree': 0.9435904606902851, 'min_child_weight': 6, 'gamma': 3.77175074144275, 'reg_alpha': 0.00035397551854527033, 'reg_lambda': 0.0009075192345902596, 'max_delta_step': 9}. Best is trial 34 with value: 0.6348927875243664.

Best trial: 34. Best value: 0.634893:  22%|██▏       | 43/200 [00:39<03:08,  1.20s/it]

[I 2025-11-10 18:42:46,733] Trial 42 finished with value: 0.5654580896686159 and parameters: {'max_depth': 3, 'learning_rate': 0.031475898988411355, 'n_estimators': 545, 'subsample': 0.9245783070065235, 'colsample_bytree': 0.8967513539004616, 'min_child_weight': 1, 'gamma': 4.9504003375268635, 'reg_alpha': 0.000535184766785437, 'reg_lambda': 2.989773060731889, 'max_delta_step': 7}. Best is trial 34 with value: 0.6348927875243664.

Best trial: 43. Best value: 0.653314:  22%|██▎       | 45/200 [00:41<02:23,  1.08it/s]

[I 2025-11-10 18:42:48,087] Trial 45 finished with value: 0.6346296296296297 and parameters: {'max_depth': 8, 'learning_rate': 0.014131109855525821, 'n_estimators': 898, 'subsample': 0.7318913920447907, 'colsample_bytree': 0.8961188054876558, 'min_child_weight': 4, 'gamma': 3.2165647061058116, 'reg_alpha': 0.7047374012737199, 'reg_lambda': 2.014161299142898, 'max_delta_step': 7}. Best is trial 34 with value: 0.6348927875243664.
[I 2025-11-10 18:42:48,262] Trial 43 finished with value: 0.6533138401559455 and parameters: {'max_depth': 3, 'learning_rate': 0.013742236313882003, 'n_estimators': 1062, 'subsample': 0.8705286405991735, 'colsample_bytree': 0.8904275738582783, 'min_child_weight': 4, 'gamma': 4.950386011742388, 'reg_alpha': 0.00034170597791229664, 'reg_lambda': 1.7290821647167607, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  23%|██▎       | 46/200 [00:41<01:45,  1.45it/s]

[I 2025-11-10 18:42:48,394] Trial 44 finished with value: 0.6524951267056531 and parameters: {'max_depth': 8, 'learning_rate': 0.03082272772309792, 'n_estimators': 1030, 'subsample': 0.7290046124310633, 'colsample_bytree': 0.8918934306522587, 'min_child_weight': 4, 'gamma': 4.9346355605407215, 'reg_alpha': 0.0002269408338353376, 'reg_lambda': 1.9452188951354956, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  24%|██▎       | 47/200 [00:44<03:32,  1.39s/it]

[I 2025-11-10 18:42:51,419] Trial 46 finished with value: 0.628615984405458 and parameters: {'max_depth': 8, 'learning_rate': 0.025211804000731915, 'n_estimators': 1025, 'subsample': 0.7302894614225613, 'colsample_bytree': 0.850525306876699, 'min_child_weight': 4, 'gamma': 3.1213145834322695, 'reg_alpha': 0.8294245024811934, 'reg_lambda': 0.40412363356169, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  24%|██▍       | 48/200 [00:45<03:09,  1.25s/it]

[I 2025-11-10 18:42:52,333] Trial 50 pruned.

Best trial: 43. Best value: 0.653314:  25%|██▌       | 50/200 [00:46<01:53,  1.32it/s]

[I 2025-11-10 18:42:52,840] Trial 47 finished with value: 0.6432943469785575 and parameters: {'max_depth': 8, 'learning_rate': 0.02429068063875863, 'n_estimators': 1035, 'subsample': 0.7709428531683116, 'colsample_bytree': 0.7402506247825974, 'min_child_weight': 4, 'gamma': 3.255583574351095, 'reg_alpha': 0.03769277740082517, 'reg_lambda': 1.7806886706880403, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.
[I 2025-11-10 18:42:52,980] Trial 48 finished with value: 0.6129239766081872 and parameters: {'max_depth': 8, 'learning_rate': 0.014709326464914062, 'n_estimators': 1034, 'subsample': 0.7218478960162994, 'colsample_bytree': 0.7480256683367925, 'min_child_weight': 4, 'gamma': 3.139348509274738, 'reg_alpha': 7.420311236707928e-06, 'reg_lambda': 0.3402825107757141, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.
[I 2025-11-10 18:42:53,012] Trial 49 finished with value: 0.6471150097465888 and parameters: {'max_depth': 8, 'learning_rate': 0.013353094464408969, 'n_estimators': 1048, 'subsample': 0.6567382759282498, 'colsample_bytree': 0.7488733138842849, 'min_child_weight': 4, 'gamma': 4.626404754665374, 'reg_alpha': 9.695271274785497e-06, 'reg_lambda': 0.34273238906893005, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  26%|██▌       | 52/200 [00:46<01:15,  1.97it/s]

[I 2025-11-10 18:42:53,404] Trial 51 pruned.

Best trial: 43. Best value: 0.653314:  27%|██▋       | 54/200 [00:46<00:55,  2.63it/s]

[I 2025-11-10 18:42:53,740] Trial 52 pruned.
[I 2025-11-10 18:42:53,883] Trial 53 pruned.

Best trial: 43. Best value: 0.653314:  28%|██▊       | 55/200 [00:47<00:44,  3.27it/s]

[I 2025-11-10 18:42:53,987] Trial 54 pruned.

Best trial: 43. Best value: 0.653314:  28%|██▊       | 56/200 [00:47<00:45,  3.16it/s]

[I 2025-11-10 18:42:54,331] Trial 55 pruned.

Best trial: 43. Best value: 0.653314:  28%|██▊       | 57/200 [00:47<00:52,  2.72it/s]

[I 2025-11-10 18:42:54,826] Trial 56 pruned.

Best trial: 43. Best value: 0.653314:  29%|██▉       | 58/200 [00:48<00:44,  3.18it/s]

[I 2025-11-10 18:42:55,012] Trial 58 pruned.
[I 2025-11-10 18:42:55,028] Trial 57 pruned.

Best trial: 43. Best value: 0.653314:  30%|███       | 60/200 [00:48<00:44,  3.14it/s]

[I 2025-11-10 18:42:55,660] Trial 62 pruned.

Best trial: 43. Best value: 0.653314:  30%|███       | 61/200 [00:49<00:53,  2.58it/s]

[I 2025-11-10 18:42:56,262] Trial 60 pruned.

Best trial: 43. Best value: 0.653314:  32%|███▏      | 63/200 [00:49<00:45,  3.01it/s]

[I 2025-11-10 18:42:56,739] Trial 61 pruned.
[I 2025-11-10 18:42:56,859] Trial 63 pruned.

Best trial: 43. Best value: 0.653314:  32%|███▏      | 64/200 [00:50<01:01,  2.23it/s]

[I 2025-11-10 18:42:57,611] Trial 65 pruned.

Best trial: 43. Best value: 0.653314:  32%|███▎      | 65/200 [00:53<02:42,  1.21s/it]

[I 2025-11-10 18:43:00,725] Trial 64 finished with value: 0.6004678362573099 and parameters: {'max_depth': 8, 'learning_rate': 0.017149915663834985, 'n_estimators': 1018, 'subsample': 0.6806677742101683, 'colsample_bytree': 0.8161545783009125, 'min_child_weight': 4, 'gamma': 0.12742022175561996, 'reg_alpha': 0.4644917543503055, 'reg_lambda': 0.272484053582725, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  33%|███▎      | 66/200 [00:53<02:02,  1.10it/s]

[I 2025-11-10 18:43:00,907] Trial 59 finished with value: 0.5700779727095517 and parameters: {'max_depth': 10, 'learning_rate': 0.01953417320658407, 'n_estimators': 1222, 'subsample': 0.55156716210959, 'colsample_bytree': 0.7942500456843312, 'min_child_weight': 2, 'gamma': 4.483616627533256, 'reg_alpha': 6.097200659709925e-07, 'reg_lambda': 0.06064184753233972, 'max_delta_step': 8}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  34%|███▎      | 67/200 [00:54<01:34,  1.40it/s]

[I 2025-11-10 18:43:01,143] Trial 66 finished with value: 0.641803118908382 and parameters: {'max_depth': 7, 'learning_rate': 0.025516799648173525, 'n_estimators': 999, 'subsample': 0.6840571908245715, 'colsample_bytree': 0.8106301443723817, 'min_child_weight': 4, 'gamma': 3.508762343243273, 'reg_alpha': 0.43302958484430404, 'reg_lambda': 0.240556593021725, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  34%|███▍      | 68/200 [00:55<01:41,  1.30it/s]

[I 2025-11-10 18:43:02,046] Trial 67 finished with value: 0.6313157894736843 and parameters: {'max_depth': 7, 'learning_rate': 0.01739304675815188, 'n_estimators': 1014, 'subsample': 0.6821565615761855, 'colsample_bytree': 0.8459347834276529, 'min_child_weight': 4, 'gamma': 2.3035841297286277, 'reg_alpha': 1.814741345252909, 'reg_lambda': 0.21623426647411526, 'max_delta_step': 5}. Best is trial 43 with value: 0.6533138401559455.
[I 2025-11-10 18:43:02,073] Trial 70 pruned.

Best trial: 43. Best value: 0.653314:  35%|███▌      | 70/200 [00:56<01:23,  1.56it/s]

[I 2025-11-10 18:43:03,018] Trial 71 pruned.

Best trial: 43. Best value: 0.653314:  36%|███▌      | 71/200 [00:58<02:17,  1.07s/it]

[I 2025-11-10 18:43:05,394] Trial 68 finished with value: 0.6533138401559455 and parameters: {'max_depth': 7, 'learning_rate': 0.024966995206718686, 'n_estimators': 996, 'subsample': 0.871512034817631, 'colsample_bytree': 0.8428334552892915, 'min_child_weight': 4, 'gamma': 3.9190111772409972, 'reg_alpha': 2.1514790058546023, 'reg_lambda': 0.8172913405371932, 'max_delta_step': 5}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  36%|███▌      | 72/200 [00:59<02:01,  1.05it/s]

[I 2025-11-10 18:43:06,021] Trial 69 finished with value: 0.6228557504873296 and parameters: {'max_depth': 7, 'learning_rate': 0.025409169541200535, 'n_estimators': 1076, 'subsample': 0.8714109924069355, 'colsample_bytree': 0.8441903544357571, 'min_child_weight': 4, 'gamma': 3.5041351934848706, 'reg_alpha': 1.442102845650229, 'reg_lambda': 0.7844510750311889, 'max_delta_step': 5}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  36%|███▋      | 73/200 [00:59<01:40,  1.27it/s]

[I 2025-11-10 18:43:06,367] Trial 74 pruned.

Best trial: 43. Best value: 0.653314:  37%|███▋      | 74/200 [01:00<01:34,  1.33it/s]

[I 2025-11-10 18:43:07,020] Trial 75 pruned.

Best trial: 43. Best value: 0.653314:  38%|███▊      | 75/200 [01:00<01:21,  1.53it/s]

[I 2025-11-10 18:43:07,435] Trial 72 finished with value: 0.6172319688109162 and parameters: {'max_depth': 6, 'learning_rate': 0.01514797641341642, 'n_estimators': 988, 'subsample': 0.8678482551821654, 'colsample_bytree': 0.9535919701654668, 'min_child_weight': 3, 'gamma': 3.3335730665614225, 'reg_alpha': 3.903620374258239, 'reg_lambda': 0.740831051953206, 'max_delta_step': 10}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  38%|███▊      | 76/200 [01:01<01:20,  1.54it/s]

[I 2025-11-10 18:43:08,066] Trial 73 finished with value: 0.5717738791423002 and parameters: {'max_depth': 6, 'learning_rate': 0.014322438986321883, 'n_estimators': 859, 'subsample': 0.8000492735125103, 'colsample_bytree': 0.9106346111458065, 'min_child_weight': 3, 'gamma': 3.269730516793167, 'reg_alpha': 0.06078110452500429, 'reg_lambda': 0.6682531810850684, 'max_delta_step': 10}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  38%|███▊      | 77/200 [01:02<01:29,  1.38it/s]

[I 2025-11-10 18:43:08,976] Trial 79 pruned.

Best trial: 43. Best value: 0.653314:  39%|███▉      | 78/200 [01:03<02:04,  1.02s/it]

[I 2025-11-10 18:43:10,717] Trial 76 finished with value: 0.6026705653021442 and parameters: {'max_depth': 6, 'learning_rate': 0.015406917080961377, 'n_estimators': 922, 'subsample': 0.7922396970968613, 'colsample_bytree': 0.9163731127081665, 'min_child_weight': 4, 'gamma': 3.917419681594067, 'reg_alpha': 0.06753719338091325, 'reg_lambda': 0.035453924302587154, 'max_delta_step': 3}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  40%|███▉      | 79/200 [01:04<01:44,  1.15it/s]

[I 2025-11-10 18:43:11,212] Trial 78 finished with value: 0.620233918128655 and parameters: {'max_depth': 7, 'learning_rate': 0.022827597991462396, 'n_estimators': 769, 'subsample': 0.8140691415720489, 'colsample_bytree': 0.9144468454150882, 'min_child_weight': 4, 'gamma': 4.233224603620039, 'reg_alpha': 0.06758913855071506, 'reg_lambda': 0.034937870653582725, 'max_delta_step': 8}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  40%|████      | 80/200 [01:05<01:48,  1.11it/s]

[I 2025-11-10 18:43:12,189] Trial 82 pruned.

[I 2025-11-10 18:43:12,460] Trial 77 finished with value: 0.6016569200779728 and parameters: {'max_depth': 7, 'learning_rate': 0.022683456659570955, 'n_estimators': 1123, 'subsample': 0.8208099468872504, 'colsample_bytree': 0.9103320736667041, 'min_child_weight': 4, 'gamma': 3.8550094909345614, 'reg_alpha': 0.3380208974045097, 'reg_lambda': 0.008969267631363381, 'max_delta_step': 8}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  41%|████      | 82/200 [01:05<01:05,  1.81it/s]

[I 2025-11-10 18:43:12,635] Trial 83 pruned.

Best trial: 43. Best value: 0.653314:  42%|████▏     | 83/200 [01:07<01:42,  1.14it/s]

[I 2025-11-10 18:43:14,271] Trial 80 finished with value: 0.6188986354775828 and parameters: {'max_depth': 9, 'learning_rate': 0.026688805317394395, 'n_estimators': 1134, 'subsample': 0.7717358800869495, 'colsample_bytree': 0.916451172999713, 'min_child_weight': 4, 'gamma': 4.237719644425705, 'reg_alpha': 0.002625214321160117, 'reg_lambda': 0.008224357859883598, 'max_delta_step': 8}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  42%|████▏     | 84/200 [01:08<02:05,  1.08s/it]

[I 2025-11-10 18:43:15,829] Trial 81 finished with value: 0.6213255360623783 and parameters: {'max_depth': 9, 'learning_rate': 0.026680890027378733, 'n_estimators': 1124, 'subsample': 0.7385004997882988, 'colsample_bytree': 0.8044368356282388, 'min_child_weight': 4, 'gamma': 3.6277380253418112, 'reg_alpha': 0.0035534693258919823, 'reg_lambda': 0.007868961406941172, 'max_delta_step': 9}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  42%|████▎     | 85/200 [01:10<02:11,  1.14s/it]

[I 2025-11-10 18:43:17,125] Trial 84 finished with value: 0.6270662768031188 and parameters: {'max_depth': 7, 'learning_rate': 0.017694703954015248, 'n_estimators': 1052, 'subsample': 0.7061301911008413, 'colsample_bytree': 0.8363163372927602, 'min_child_weight': 4, 'gamma': 2.407448329938587, 'reg_alpha': 2.1643213301857855, 'reg_lambda': 1.3776981930198362, 'max_delta_step': 4}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  43%|████▎     | 86/200 [01:11<02:00,  1.06s/it]

[I 2025-11-10 18:43:17,981] Trial 88 pruned.
[I 2025-11-10 18:43:18,027] Trial 85 finished with value: 0.6212085769980507 and parameters: {'max_depth': 7, 'learning_rate': 0.012046181624387052, 'n_estimators': 1171, 'subsample': 0.7047535694670579, 'colsample_bytree': 0.8590454837817357, 'min_child_weight': 4, 'gamma': 2.2361493159307053, 'reg_alpha': 2.14656796326738, 'reg_lambda': 0.17785521974860283, 'max_delta_step': 4}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  44%|████▍     | 88/200 [01:11<01:26,  1.29it/s]

[I 2025-11-10 18:43:18,875] Trial 89 pruned.

Best trial: 43. Best value: 0.653314:  44%|████▍     | 89/200 [01:12<01:11,  1.56it/s]

[I 2025-11-10 18:43:19,106] Trial 86 finished with value: 0.6082261208576998 and parameters: {'max_depth': 7, 'learning_rate': 0.017711982728169307, 'n_estimators': 1055, 'subsample': 0.7094918231590454, 'colsample_bytree': 0.8622600116271748, 'min_child_weight': 4, 'gamma': 1.8489945186817178, 'reg_alpha': 1.9095963098640374, 'reg_lambda': 0.1968504998477342, 'max_delta_step': 4}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  45%|████▌     | 90/200 [01:12<01:08,  1.60it/s]

[I 2025-11-10 18:43:19,690] Trial 91 pruned.

Best trial: 43. Best value: 0.653314:  46%|████▌     | 91/200 [01:15<02:00,  1.10s/it]

[I 2025-11-10 18:43:22,070] Trial 87 finished with value: 0.5729044834307992 and parameters: {'max_depth': 7, 'learning_rate': 0.017311518153700266, 'n_estimators': 1176, 'subsample': 0.6984212361014154, 'colsample_bytree': 0.8611567466628371, 'min_child_weight': 3, 'gamma': 2.1221620351454065, 'reg_alpha': 2.2427849833586166, 'reg_lambda': 0.16943403543156468, 'max_delta_step': 5}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  46%|████▌     | 92/200 [01:16<01:55,  1.07s/it]

[I 2025-11-10 18:43:23,051] Trial 92 finished with value: 0.6242690058479533 and parameters: {'max_depth': 8, 'learning_rate': 0.01622966278517077, 'n_estimators': 975, 'subsample': 0.8831239795210017, 'colsample_bytree': 0.775852847662218, 'min_child_weight': 5, 'gamma': 4.360152212199221, 'reg_alpha': 0.0006339656463464562, 'reg_lambda': 0.527401503230071, 'max_delta_step': 6}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  46%|████▋     | 93/200 [01:16<01:28,  1.21it/s]

[I 2025-11-10 18:43:23,281] Trial 93 finished with value: 0.5679922027290448 and parameters: {'max_depth': 8, 'learning_rate': 0.011149378384523517, 'n_estimators': 531, 'subsample': 0.8870702325909732, 'colsample_bytree': 0.7388986478162201, 'min_child_weight': 3, 'gamma': 2.444009378418495, 'reg_alpha': 0.009668354176491171, 'reg_lambda': 0.5501510053905865, 'max_delta_step': 6}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  47%|████▋     | 94/200 [01:16<01:21,  1.30it/s]

[I 2025-11-10 18:43:23,895] Trial 90 finished with value: 0.5619298245614035 and parameters: {'max_depth': 8, 'learning_rate': 0.011490700898672351, 'n_estimators': 931, 'subsample': 0.8874734487750471, 'colsample_bytree': 0.8787922484737913, 'min_child_weight': 3, 'gamma': 2.8153412722886264, 'reg_alpha': 4.021825128017803e-05, 'reg_lambda': 0.09293836310512175, 'max_delta_step': 5}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  48%|████▊     | 95/200 [01:19<02:22,  1.36s/it]

[I 2025-11-10 18:43:26,678] Trial 94 finished with value: 0.6084795321637426 and parameters: {'max_depth': 8, 'learning_rate': 0.011238771990674076, 'n_estimators': 1027, 'subsample': 0.7296332642330384, 'colsample_bytree': 0.7792833854484025, 'min_child_weight': 4, 'gamma': 3.1688073929675378, 'reg_alpha': 0.9207440793842199, 'reg_lambda': 0.46997831059464695, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  48%|████▊     | 96/200 [01:20<02:09,  1.24s/it]

[I 2025-11-10 18:43:27,644] Trial 95 finished with value: 0.5978557504873294 and parameters: {'max_depth': 8, 'learning_rate': 0.033324863197511795, 'n_estimators': 1006, 'subsample': 0.7302231045035928, 'colsample_bytree': 0.8850773883351147, 'min_child_weight': 4, 'gamma': 2.455164015536198, 'reg_alpha': 0.8986791008770465, 'reg_lambda': 0.08480737719512205, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  48%|████▊     | 97/200 [01:20<01:37,  1.05it/s]

[I 2025-11-10 18:43:27,903] Trial 96 finished with value: 0.6167641325536062 and parameters: {'max_depth': 8, 'learning_rate': 0.03287743457008633, 'n_estimators': 1027, 'subsample': 0.7294563733445307, 'colsample_bytree': 0.8865966311534594, 'min_child_weight': 4, 'gamma': 3.0468331900175643, 'reg_alpha': 1.0138759104994368, 'reg_lambda': 0.09880719929416995, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  49%|████▉     | 98/200 [01:21<01:24,  1.21it/s]

[I 2025-11-10 18:43:28,430] Trial 97 finished with value: 0.6353703703703704 and parameters: {'max_depth': 3, 'learning_rate': 0.03840575379748683, 'n_estimators': 1031, 'subsample': 0.6769730477275208, 'colsample_bytree': 0.8490664897022779, 'min_child_weight': 4, 'gamma': 3.199348795675036, 'reg_alpha': 0.8656309253110941, 'reg_lambda': 0.3771507998109438, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  50%|█████     | 100/200 [01:21<00:50,  1.99it/s]

[I 2025-11-10 18:43:28,670] Trial 99 pruned.
[I 2025-11-10 18:43:28,826] Trial 100 pruned.

Best trial: 43. Best value: 0.653314:  51%|█████     | 102/200 [01:22<00:39,  2.46it/s]

[I 2025-11-10 18:43:29,381] Trial 101 pruned.
[I 2025-11-10 18:43:29,525] Trial 102 pruned.

Best trial: 43. Best value: 0.653314:  52%|█████▏    | 103/200 [01:22<00:37,  2.57it/s]

[I 2025-11-10 18:43:29,881] Trial 103 pruned.

Best trial: 43. Best value: 0.653314:  52%|█████▏    | 104/200 [01:23<00:47,  2.02it/s]

[I 2025-11-10 18:43:30,615] Trial 105 pruned.

Best trial: 43. Best value: 0.653314:  52%|█████▎    | 105/200 [01:24<00:44,  2.12it/s]

[I 2025-11-10 18:43:31,028] Trial 106 pruned.

Best trial: 43. Best value: 0.653314:  53%|█████▎    | 106/200 [01:24<00:44,  2.11it/s]

[I 2025-11-10 18:43:31,516] Trial 98 finished with value: 0.6098245614035088 and parameters: {'max_depth': 3, 'learning_rate': 0.03176611810501888, 'n_estimators': 862, 'subsample': 0.9501105257941416, 'colsample_bytree': 0.9307363910038357, 'min_child_weight': 4, 'gamma': 3.0508166267020966, 'reg_alpha': 0.4222858248789332, 'reg_lambda': 1.2397599609610248, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  54%|█████▎    | 107/200 [01:25<00:44,  2.08it/s]

[I 2025-11-10 18:43:32,012] Trial 108 pruned.

Best trial: 43. Best value: 0.653314:  54%|█████▍    | 108/200 [01:25<00:41,  2.20it/s]

[I 2025-11-10 18:43:32,400] Trial 110 pruned.

Best trial: 43. Best value: 0.653314:  55%|█████▍    | 109/200 [01:25<00:38,  2.35it/s]

[I 2025-11-10 18:43:32,766] Trial 109 finished with value: 0.635477582846004 and parameters: {'max_depth': 7, 'learning_rate': 0.06205998977582589, 'n_estimators': 246, 'subsample': 0.6855773630101751, 'colsample_bytree': 0.8417511452786038, 'min_child_weight': 4, 'gamma': 3.2255119316146046, 'reg_alpha': 2.6310304447808752e-06, 'reg_lambda': 1.8928923378726614, 'max_delta_step': 8}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  55%|█████▌    | 110/200 [01:26<00:44,  2.01it/s]

[I 2025-11-10 18:43:33,419] Trial 104 finished with value: 0.5944054580896687 and parameters: {'max_depth': 3, 'learning_rate': 0.05970089428312264, 'n_estimators': 868, 'subsample': 0.6533121397750707, 'colsample_bytree': 0.8486035352587075, 'min_child_weight': 4, 'gamma': 3.266302943229478, 'reg_alpha': 0.16279151602904526, 'reg_lambda': 0.31843423666483345, 'max_delta_step': 8}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  56%|█████▌    | 111/200 [01:27<00:55,  1.60it/s]

[I 2025-11-10 18:43:34,349] Trial 112 finished with value: 0.6321637426900584 and parameters: {'max_depth': 7, 'learning_rate': 0.06137044784834551, 'n_estimators': 318, 'subsample': 0.6341836873586687, 'colsample_bytree': 0.868667033867816, 'min_child_weight': 3, 'gamma': 3.262059780022274, 'reg_alpha': 2.2400377671085304e-06, 'reg_lambda': 6.215800996759135, 'max_delta_step': 9}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  56%|█████▌    | 112/200 [01:27<00:45,  1.94it/s]

[I 2025-11-10 18:43:34,611] Trial 114 pruned.

Best trial: 43. Best value: 0.653314:  56%|█████▋    | 113/200 [01:28<00:47,  1.84it/s]

[I 2025-11-10 18:43:35,214] Trial 113 finished with value: 0.6214619883040935 and parameters: {'max_depth': 7, 'learning_rate': 0.0974598187516082, 'n_estimators': 357, 'subsample': 0.6260353283403377, 'colsample_bytree': 0.7159608045490485, 'min_child_weight': 3, 'gamma': 3.2413703042592985, 'reg_alpha': 3.9536081717465365e-06, 'reg_lambda': 7.138469472544647, 'max_delta_step': 9}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  57%|█████▊    | 115/200 [01:28<00:30,  2.79it/s]

[I 2025-11-10 18:43:35,499] Trial 116 pruned.
[I 2025-11-10 18:43:35,605] Trial 107 finished with value: 0.6122514619883039 and parameters: {'max_depth': 5, 'learning_rate': 0.06286284856490965, 'n_estimators': 1069, 'subsample': 0.687873465401705, 'colsample_bytree': 0.8491222118806235, 'min_child_weight': 4, 'gamma': 3.2075417520127756, 'reg_alpha': 3.429057608427459e-06, 'reg_lambda': 0.2987767993335475, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  58%|█████▊    | 116/200 [01:29<00:39,  2.15it/s]

[I 2025-11-10 18:43:36,322] Trial 115 finished with value: 0.6212378167641325 and parameters: {'max_depth': 7, 'learning_rate': 0.08892607341953052, 'n_estimators': 322, 'subsample': 0.6086514163301193, 'colsample_bytree': 0.7553610211835078, 'min_child_weight': 3, 'gamma': 2.6995249690677294, 'reg_alpha': 1.5059965772446407e-06, 'reg_lambda': 5.592250710556252, 'max_delta_step': 9}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  59%|█████▉    | 118/200 [01:30<00:30,  2.67it/s]

[I 2025-11-10 18:43:36,805] Trial 117 finished with value: 0.6317933723196881 and parameters: {'max_depth': 6, 'learning_rate': 0.0664041463716721, 'n_estimators': 238, 'subsample': 0.6870931161532526, 'colsample_bytree': 0.8642070563018878, 'min_child_weight': 4, 'gamma': 2.328905985644484, 'reg_alpha': 3.504296804095073e-07, 'reg_lambda': 2.59104514937476, 'max_delta_step': 9}. Best is trial 43 with value: 0.6533138401559455.
[I 2025-11-10 18:43:36,954] Trial 119 pruned.

Best trial: 43. Best value: 0.653314:  60%|█████▉    | 119/200 [01:30<00:25,  3.22it/s]

[I 2025-11-10 18:43:37,121] Trial 120 pruned.

Best trial: 43. Best value: 0.653314:  60%|██████    | 121/200 [01:30<00:18,  4.23it/s]

[I 2025-11-10 18:43:37,324] Trial 118 finished with value: 0.6338888888888891 and parameters: {'max_depth': 6, 'learning_rate': 0.08800215619125251, 'n_estimators': 314, 'subsample': 0.7475748813214061, 'colsample_bytree': 0.8682790672979325, 'min_child_weight': 4, 'gamma': 3.582982472898784, 'reg_alpha': 2.9446642948822696e-07, 'reg_lambda': 2.4306132612484657, 'max_delta_step': 9}. Best is trial 43 with value: 0.6533138401559455.
[I 2025-11-10 18:43:37,453] Trial 122 pruned.

Best trial: 43. Best value: 0.653314:  61%|██████    | 122/200 [01:31<00:28,  2.76it/s]

[I 2025-11-10 18:43:38,116] Trial 111 finished with value: 0.6423391812865498 and parameters: {'max_depth': 9, 'learning_rate': 0.013157752509358654, 'n_estimators': 987, 'subsample': 0.7466890903935333, 'colsample_bytree': 0.9053337837492909, 'min_child_weight': 3, 'gamma': 3.2092485914776767, 'reg_alpha': 3.0524079676559452, 'reg_lambda': 0.912697052419676, 'max_delta_step': 6}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  62%|██████▏   | 124/200 [01:31<00:21,  3.53it/s]

[I 2025-11-10 18:43:38,388] Trial 121 finished with value: 0.6283040935672515 and parameters: {'max_depth': 6, 'learning_rate': 0.05069877238467603, 'n_estimators': 221, 'subsample': 0.8619691490843713, 'colsample_bytree': 0.904354978794405, 'min_child_weight': 4, 'gamma': 2.9216138269183407, 'reg_alpha': 7.4437946942935785e-06, 'reg_lambda': 3.070967085016177, 'max_delta_step': 9}. Best is trial 43 with value: 0.6533138401559455.
[I 2025-11-10 18:43:38,551] Trial 125 pruned.

Best trial: 43. Best value: 0.653314:  62%|██████▎   | 125/200 [01:31<00:22,  3.38it/s]

[I 2025-11-10 18:43:38,874] Trial 126 pruned.

Best trial: 43. Best value: 0.653314:  63%|██████▎   | 126/200 [01:32<00:24,  3.06it/s]

[I 2025-11-10 18:43:39,281] Trial 128 pruned.

Best trial: 43. Best value: 0.653314:  64%|██████▎   | 127/200 [01:32<00:24,  2.97it/s]

[I 2025-11-10 18:43:39,633] Trial 124 finished with value: 0.6447368421052632 and parameters: {'max_depth': 6, 'learning_rate': 0.11686835660595307, 'n_estimators': 426, 'subsample': 0.6685929797384792, 'colsample_bytree': 0.9077217498455977, 'min_child_weight': 4, 'gamma': 3.3950235723734035, 'reg_alpha': 1.9334513949881706e-07, 'reg_lambda': 2.697457805405912, 'max_delta_step': 9}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  64%|██████▍   | 128/200 [01:33<00:24,  2.90it/s]

[I 2025-11-10 18:43:39,996] Trial 123 finished with value: 0.5955165692007797 and parameters: {'max_depth': 7, 'learning_rate': 0.05070275723736733, 'n_estimators': 410, 'subsample': 0.8465328337709932, 'colsample_bytree': 0.8812822453316698, 'min_child_weight': 3, 'gamma': 4.713083144505509, 'reg_alpha': 1.5207684418305283e-07, 'reg_lambda': 0.8811793805667434, 'max_delta_step': 10}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  64%|██████▍   | 129/200 [01:33<00:28,  2.53it/s]

[I 2025-11-10 18:43:40,517] Trial 131 pruned.

Best trial: 43. Best value: 0.653314:  65%|██████▌   | 130/200 [01:33<00:24,  2.83it/s]

[I 2025-11-10 18:43:40,770] Trial 127 finished with value: 0.5631968810916179 and parameters: {'max_depth': 9, 'learning_rate': 0.11163085162211348, 'n_estimators': 380, 'subsample': 0.718419475150196, 'colsample_bytree': 0.8926964470097717, 'min_child_weight': 3, 'gamma': 3.767147813078102, 'reg_alpha': 3.840788790859309e-08, 'reg_lambda': 0.0004800588789326096, 'max_delta_step': 8}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  66%|██████▌   | 131/200 [01:34<00:23,  2.89it/s]

[I 2025-11-10 18:43:41,104] Trial 132 pruned.

Best trial: 43. Best value: 0.653314:  66%|██████▋   | 133/200 [01:34<00:17,  3.84it/s]

[I 2025-11-10 18:43:41,304] Trial 133 pruned.
[I 2025-11-10 18:43:41,468] Trial 129 finished with value: 0.5989668615984407 and parameters: {'max_depth': 7, 'learning_rate': 0.046123615071686, 'n_estimators': 386, 'subsample': 0.7392712553352728, 'colsample_bytree': 0.9515576699778653, 'min_child_weight': 4, 'gamma': 3.3798112098154243, 'reg_alpha': 2.2111429582113784e-07, 'reg_lambda': 6.894047244318819e-06, 'max_delta_step': 6}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  68%|██████▊   | 135/200 [01:34<00:14,  4.42it/s]

[I 2025-11-10 18:43:41,698] Trial 135 pruned.
[I 2025-11-10 18:43:41,861] Trial 136 pruned.

Best trial: 43. Best value: 0.653314:  68%|██████▊   | 136/200 [01:35<00:12,  5.03it/s]

[I 2025-11-10 18:43:41,996] Trial 130 finished with value: 0.6087134502923977 and parameters: {'max_depth': 5, 'learning_rate': 0.12930041222874525, 'n_estimators': 406, 'subsample': 0.7693025607997866, 'colsample_bytree': 0.9461909786032772, 'min_child_weight': 4, 'gamma': 3.3640151254476987, 'reg_alpha': 2.2919248264194833e-07, 'reg_lambda': 0.5798509177375646, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  68%|██████▊   | 137/200 [01:35<00:14,  4.40it/s]

[I 2025-11-10 18:43:42,290] Trial 134 pruned.

Best trial: 43. Best value: 0.653314:  69%|██████▉   | 138/200 [01:35<00:21,  2.86it/s]

[I 2025-11-10 18:43:42,924] Trial 137 pruned.

Best trial: 43. Best value: 0.653314:  70%|██████▉   | 139/200 [01:36<00:20,  2.95it/s]

[I 2025-11-10 18:43:43,240] Trial 138 pruned.
[I 2025-11-10 18:43:43,312] Trial 139 pruned.

Best trial: 43. Best value: 0.653314:  70%|███████   | 141/200 [01:36<00:15,  3.73it/s]

[I 2025-11-10 18:43:43,609] Trial 140 pruned.

Best trial: 43. Best value: 0.653314:  72%|███████▏  | 143/200 [01:37<00:13,  4.32it/s]

[I 2025-11-10 18:43:43,909] Trial 144 pruned.
[I 2025-11-10 18:43:44,011] Trial 143 pruned.

Best trial: 43. Best value: 0.653314:  72%|███████▏  | 144/200 [01:37<00:11,  5.04it/s]

[I 2025-11-10 18:43:44,125] Trial 141 pruned.

Best trial: 43. Best value: 0.653314:  73%|███████▎  | 146/200 [01:37<00:10,  5.29it/s]

[I 2025-11-10 18:43:44,385] Trial 142 pruned.
[I 2025-11-10 18:43:44,509] Trial 146 pruned.

Best trial: 43. Best value: 0.653314:  73%|███████▎  | 146/200 [01:37<00:10,  5.29it/s]

[I 2025-11-10 18:43:44,600] Trial 147 pruned.

Best trial: 43. Best value: 0.653314:  74%|███████▍  | 148/200 [01:37<00:09,  5.33it/s]

[I 2025-11-10 18:43:44,882] Trial 148 pruned.

Best trial: 43. Best value: 0.653314:  74%|███████▍  | 149/200 [01:38<00:10,  4.92it/s]

[I 2025-11-10 18:43:45,133] Trial 149 pruned.

Best trial: 43. Best value: 0.653314:  75%|███████▌  | 150/200 [01:38<00:11,  4.48it/s]

[I 2025-11-10 18:43:45,413] Trial 152 pruned.

Best trial: 43. Best value: 0.653314:  76%|███████▌  | 151/200 [01:38<00:12,  3.82it/s]

[I 2025-11-10 18:43:45,778] Trial 145 finished with value: 0.6461013645224172 and parameters: {'max_depth': 6, 'learning_rate': 0.06174328706312996, 'n_estimators': 280, 'subsample': 0.6933559960166022, 'colsample_bytree': 0.9089251813127227, 'min_child_weight': 4, 'gamma': 3.0719510253136564, 'reg_alpha': 0.0007313057194201724, 'reg_lambda': 2.4673424715766337, 'max_delta_step': 10}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  76%|███████▌  | 152/200 [01:39<00:15,  3.11it/s]

[I 2025-11-10 18:43:46,255] Trial 150 finished with value: 0.6390058479532164 and parameters: {'max_depth': 7, 'learning_rate': 0.015721547660395078, 'n_estimators': 283, 'subsample': 0.7096030826001161, 'colsample_bytree': 0.8935065019867706, 'min_child_weight': 4, 'gamma': 3.133085873966897, 'reg_alpha': 1.8338010054263977e-06, 'reg_lambda': 2.737088155525038, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  76%|███████▋  | 153/200 [01:39<00:16,  2.82it/s]

[I 2025-11-10 18:43:46,691] Trial 153 pruned.

Best trial: 43. Best value: 0.653314:  77%|███████▋  | 154/200 [01:40<00:17,  2.59it/s]

[I 2025-11-10 18:43:47,156] Trial 154 finished with value: 0.6357992202729046 and parameters: {'max_depth': 6, 'learning_rate': 0.07226649707466948, 'n_estimators': 255, 'subsample': 0.73940290688413, 'colsample_bytree': 0.8953886936733005, 'min_child_weight': 4, 'gamma': 3.161489202526679, 'reg_alpha': 0.000338396482311186, 'reg_lambda': 3.5016211247522917, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  78%|███████▊  | 156/200 [01:40<00:15,  2.90it/s]

[I 2025-11-10 18:43:47,720] Trial 155 finished with value: 0.6404191033138401 and parameters: {'max_depth': 7, 'learning_rate': 0.01584572797320967, 'n_estimators': 281, 'subsample': 0.7410041979356699, 'colsample_bytree': 0.9220742679606719, 'min_child_weight': 4, 'gamma': 3.0727943186527233, 'reg_alpha': 0.00035433839267508293, 'reg_lambda': 4.534943247827638, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.
[I 2025-11-10 18:43:47,839] Trial 151 finished with value: 0.6424366471734893 and parameters: {'max_depth': 7, 'learning_rate': 0.015810104712027442, 'n_estimators': 499, 'subsample': 0.8742743239658576, 'colsample_bytree': 0.7647691851234835, 'min_child_weight': 4, 'gamma': 3.1362603861129354, 'reg_alpha': 0.6870710215706081, 'reg_lambda': 3.362045999843549, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  78%|███████▊  | 157/200 [01:41<00:15,  2.73it/s]

[I 2025-11-10 18:43:48,257] Trial 159 pruned.

Best trial: 43. Best value: 0.653314:  79%|███████▉  | 158/200 [01:41<00:14,  2.96it/s]

[I 2025-11-10 18:43:48,532] Trial 156 finished with value: 0.6303508771929824 and parameters: {'max_depth': 7, 'learning_rate': 0.018700293275218143, 'n_estimators': 289, 'subsample': 0.8302325487386881, 'colsample_bytree': 0.9216460606523271, 'min_child_weight': 4, 'gamma': 3.1965299075466773, 'reg_alpha': 0.0003107133330633521, 'reg_lambda': 1.8047327899925496, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  80%|████████  | 160/200 [01:41<00:13,  3.00it/s]

[I 2025-11-10 18:43:48,851] Trial 157 finished with value: 0.6186647173489279 and parameters: {'max_depth': 6, 'learning_rate': 0.029143312208054193, 'n_estimators': 288, 'subsample': 0.7389887081114987, 'colsample_bytree': 0.9225660225860431, 'min_child_weight': 4, 'gamma': 3.1195838926652852, 'reg_alpha': 0.0002961944820461227, 'reg_lambda': 0.7673300653855984, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.
[I 2025-11-10 18:43:48,872] Trial 160 pruned.
[I 2025-11-10 18:43:48,919] Trial 161 pruned.

Best trial: 43. Best value: 0.653314:  81%|████████  | 162/200 [01:42<00:10,  3.46it/s]

[I 2025-11-10 18:43:49,615] Trial 158 finished with value: 0.6021832358674464 and parameters: {'max_depth': 7, 'learning_rate': 0.014719196027929378, 'n_estimators': 285, 'subsample': 0.734562364180265, 'colsample_bytree': 0.9339845425537784, 'min_child_weight': 4, 'gamma': 3.1432595281346933, 'reg_alpha': 0.0002343227691119901, 'reg_lambda': 8.884746933909921e-05, 'max_delta_step': 7}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  82%|████████▏ | 163/200 [01:44<00:22,  1.62it/s]

[I 2025-11-10 18:43:51,459] Trial 162 finished with value: 0.6479434697855752 and parameters: {'max_depth': 7, 'learning_rate': 0.015499501667943952, 'n_estimators': 440, 'subsample': 0.8593042681064199, 'colsample_bytree': 0.9365463617571594, 'min_child_weight': 4, 'gamma': 2.726407934014148, 'reg_alpha': 0.00013756919854084924, 'reg_lambda': 4.371598148977467, 'max_delta_step': 6}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  82%|████████▏ | 164/200 [01:44<00:19,  1.87it/s]

[I 2025-11-10 18:43:51,721] Trial 163 finished with value: 0.6507894736842106 and parameters: {'max_depth': 7, 'learning_rate': 0.01641504492160821, 'n_estimators': 582, 'subsample': 0.7198044376324176, 'colsample_bytree': 0.8144117557852852, 'min_child_weight': 4, 'gamma': 2.972889320486474, 'reg_alpha': 0.000983597420447251, 'reg_lambda': 3.9810373055827033, 'max_delta_step': 6}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  82%|████████▎ | 165/200 [01:45<00:16,  2.15it/s]

[I 2025-11-10 18:43:51,972] Trial 164 finished with value: 0.6449317738791424 and parameters: {'max_depth': 8, 'learning_rate': 0.016455586164217474, 'n_estimators': 618, 'subsample': 0.7335848903607896, 'colsample_bytree': 0.7876847775014212, 'min_child_weight': 4, 'gamma': 2.9025433892607144, 'reg_alpha': 0.0005544874206124551, 'reg_lambda': 3.739353442859667, 'max_delta_step': 6}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  83%|████████▎ | 166/200 [01:45<00:15,  2.14it/s]

[I 2025-11-10 18:43:52,449] Trial 165 finished with value: 0.6472709551656919 and parameters: {'max_depth': 8, 'learning_rate': 0.021251946886567355, 'n_estimators': 575, 'subsample': 0.7260421718785073, 'colsample_bytree': 0.8855369470328737, 'min_child_weight': 4, 'gamma': 2.8827003563055356, 'reg_alpha': 9.580087113078422e-05, 'reg_lambda': 3.797493045937944, 'max_delta_step': 6}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  84%|████████▎ | 167/200 [01:46<00:24,  1.36it/s]

[I 2025-11-10 18:43:53,887] Trial 167 finished with value: 0.6423879142300194 and parameters: {'max_depth': 7, 'learning_rate': 0.01688216762975173, 'n_estimators': 440, 'subsample': 0.7187631494929692, 'colsample_bytree': 0.8035291140758545, 'min_child_weight': 4, 'gamma': 2.8567574503214312, 'reg_alpha': 0.00048515473459654934, 'reg_lambda': 3.3706456108199387, 'max_delta_step': 6}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  84%|████████▍ | 168/200 [01:47<00:19,  1.68it/s]

[I 2025-11-10 18:43:54,130] Trial 166 finished with value: 0.6413255360623783 and parameters: {'max_depth': 7, 'learning_rate': 0.016502992620884983, 'n_estimators': 439, 'subsample': 0.8682257027456439, 'colsample_bytree': 0.9732697487082972, 'min_child_weight': 4, 'gamma': 2.9764825359556175, 'reg_alpha': 0.0005218364342779116, 'reg_lambda': 4.331017165999682, 'max_delta_step': 6}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  84%|████████▍ | 169/200 [01:47<00:16,  1.90it/s]

[I 2025-11-10 18:43:54,487] Trial 170 pruned.

Best trial: 43. Best value: 0.653314:  85%|████████▌ | 170/200 [01:47<00:13,  2.16it/s]

[I 2025-11-10 18:43:54,795] Trial 171 pruned.

Best trial: 43. Best value: 0.653314:  86%|████████▌ | 171/200 [01:48<00:11,  2.55it/s]

[I 2025-11-10 18:43:55,012] Trial 168 finished with value: 0.6383138401559455 and parameters: {'max_depth': 7, 'learning_rate': 0.01623578045628553, 'n_estimators': 595, 'subsample': 0.7576974892852403, 'colsample_bytree': 0.7894351786568157, 'min_child_weight': 4, 'gamma': 2.8666089509048605, 'reg_alpha': 0.00045775567822847816, 'reg_lambda': 3.8021648175643143, 'max_delta_step': 6}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  86%|████████▌ | 172/200 [01:48<00:11,  2.37it/s]

[I 2025-11-10 18:43:55,504] Trial 174 pruned.
[I 2025-11-10 18:43:55,581] Trial 169 finished with value: 0.6339863547758284 and parameters: {'max_depth': 8, 'learning_rate': 0.016715017975477458, 'n_estimators': 610, 'subsample': 0.7552240688096482, 'colsample_bytree': 0.7820707674905836, 'min_child_weight': 4, 'gamma': 2.7655705524663405, 'reg_alpha': 0.00048505419791476385, 'reg_lambda': 4.227528597073722, 'max_delta_step': 6}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  87%|████████▋ | 174/200 [01:49<00:10,  2.53it/s]

[I 2025-11-10 18:43:56,229] Trial 176 pruned.

Best trial: 43. Best value: 0.653314:  88%|████████▊ | 175/200 [01:50<00:14,  1.72it/s]

[I 2025-11-10 18:43:57,384] Trial 173 finished with value: 0.633859649122807 and parameters: {'max_depth': 8, 'learning_rate': 0.022201323514349582, 'n_estimators': 451, 'subsample': 0.8932946064315214, 'colsample_bytree': 0.8049324885123748, 'min_child_weight': 4, 'gamma': 2.7234766990702024, 'reg_alpha': 0.0010086804893973131, 'reg_lambda': 4.946188663891565, 'max_delta_step': 6}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 43. Best value: 0.653314:  88%|████████▊ | 176/200 [01:50<00:11,  2.02it/s]

[I 2025-11-10 18:43:57,635] Trial 172 finished with value: 0.6456042884990254 and parameters: {'max_depth': 8, 'learning_rate': 0.02200295126365385, 'n_estimators': 585, 'subsample': 0.7226249697765992, 'colsample_bytree': 0.9980353058315802, 'min_child_weight': 4, 'gamma': 2.836008686565858, 'reg_alpha': 0.0009592804705347325, 'reg_lambda': 4.6370865482031425, 'max_delta_step': 6}. Best is trial 43 with value: 0.6533138401559455.

Best trial: 175. Best value: 0.665712:  89%|████████▉ | 178/200 [01:52<00:12,  1.83it/s]

[I 2025-11-10 18:43:58,929] Trial 177 finished with value: 0.6321150097465887 and parameters: {'max_depth': 7, 'learning_rate': 0.018382422467332196, 'n_estimators': 494, 'subsample': 0.871568005507538, 'colsample_bytree': 0.8100713357621921, 'min_child_weight': 4, 'gamma': 2.9871931005892973, 'reg_alpha': 0.0016055753220676967, 'reg_lambda': 3.007098628967398, 'max_delta_step': 5}. Best is trial 43 with value: 0.6533138401559455.
[I 2025-11-10 18:43:59,053] Trial 175 finished with value: 0.6657115009746588 and parameters: {'max_depth': 7, 'learning_rate': 0.015133893080323093, 'n_estimators': 701, 'subsample': 0.7259382423329088, 'colsample_bytree': 0.9939996131885289, 'min_child_weight': 4, 'gamma': 2.532135414008178, 'reg_alpha': 9.51744164091432e-05, 'reg_lambda': 7.775912006036232, 'max_delta_step': 6}. Best is trial 175 with value: 0.6657115009746588.

Best trial: 175. Best value: 0.665712:  90%|████████▉ | 179/200 [01:52<00:11,  1.90it/s]

[I 2025-11-10 18:43:59,528] Trial 180 pruned.
[I 2025-11-10 18:43:59,627] Trial 181 pruned.

Best trial: 175. Best value: 0.665712:  91%|█████████ | 182/200 [01:53<00:06,  2.89it/s]

[I 2025-11-10 18:44:00,073] Trial 178 finished with value: 0.6349805068226122 and parameters: {'max_depth': 7, 'learning_rate': 0.01539283880777392, 'n_estimators': 508, 'subsample': 0.7257936561610273, 'colsample_bytree': 0.8015326279097527, 'min_child_weight': 4, 'gamma': 2.9964457298724376, 'reg_alpha': 0.0017263356062218042, 'reg_lambda': 3.0508801407389687, 'max_delta_step': 5}. Best is trial 175 with value: 0.6657115009746588.
[I 2025-11-10 18:44:00,209] Trial 182 pruned.

Best trial: 175. Best value: 0.665712:  91%|█████████ | 182/200 [01:53<00:06,  2.89it/s]

[I 2025-11-10 18:44:00,302] Trial 183 pruned.

Best trial: 175. Best value: 0.665712:  92%|█████████▏| 184/200 [01:53<00:05,  3.18it/s]

[I 2025-11-10 18:44:00,750] Trial 179 finished with value: 0.6485185185185186 and parameters: {'max_depth': 8, 'learning_rate': 0.01817353002598452, 'n_estimators': 509, 'subsample': 0.8555313118076351, 'colsample_bytree': 0.996269505606883, 'min_child_weight': 4, 'gamma': 2.605125205054179, 'reg_alpha': 0.00016150460131648706, 'reg_lambda': 8.120627243215303, 'max_delta_step': 5}. Best is trial 175 with value: 0.6657115009746588.

Best trial: 175. Best value: 0.665712:  92%|█████████▎| 185/200 [01:54<00:04,  3.15it/s]

[I 2025-11-10 18:44:01,077] Trial 185 pruned.

Best trial: 175. Best value: 0.665712:  93%|█████████▎| 186/200 [01:56<00:09,  1.41it/s]

[I 2025-11-10 18:44:03,005] Trial 184 finished with value: 0.6015594541910332 and parameters: {'max_depth': 8, 'learning_rate': 0.020252421099184757, 'n_estimators': 571, 'subsample': 0.7444753249393488, 'colsample_bytree': 0.9865514402153804, 'min_child_weight': 4, 'gamma': 2.5495030132536742, 'reg_alpha': 9.122561600023882e-05, 'reg_lambda': 1.5692247201134089, 'max_delta_step': 6}. Best is trial 175 with value: 0.6657115009746588.

Best trial: 175. Best value: 0.665712:  94%|█████████▎| 187/200 [01:56<00:08,  1.61it/s]

[I 2025-11-10 18:44:03,363] Trial 186 finished with value: 0.648684210526316 and parameters: {'max_depth': 9, 'learning_rate': 0.013170176211088276, 'n_estimators': 639, 'subsample': 0.7463800146928572, 'colsample_bytree': 0.9688354231023996, 'min_child_weight': 4, 'gamma': 2.6833558543757134, 'reg_alpha': 0.0006266002400257795, 'reg_lambda': 5.277154933755791, 'max_delta_step': 6}. Best is trial 175 with value: 0.6657115009746588.

Best trial: 175. Best value: 0.665712:  94%|█████████▍| 188/200 [01:56<00:06,  1.84it/s]

[I 2025-11-10 18:44:03,702] Trial 188 finished with value: 0.650029239766082 and parameters: {'max_depth': 8, 'learning_rate': 0.01851243490385453, 'n_estimators': 474, 'subsample': 0.8791626176687811, 'colsample_bytree': 0.9819874076161856, 'min_child_weight': 4, 'gamma': 2.578068654157712, 'reg_alpha': 0.0007000219215276913, 'reg_lambda': 5.884464860895681, 'max_delta_step': 5}. Best is trial 175 with value: 0.6657115009746588.

Best trial: 175. Best value: 0.665712:  94%|█████████▍| 189/200 [01:57<00:05,  2.01it/s]

[I 2025-11-10 18:44:04,080] Trial 190 pruned.

Best trial: 175. Best value: 0.665712:  95%|█████████▌| 190/200 [01:57<00:04,  2.37it/s]

[I 2025-11-10 18:44:04,307] Trial 187 finished with value: 0.6512768031189085 and parameters: {'max_depth': 9, 'learning_rate': 0.018630818647275987, 'n_estimators': 650, 'subsample': 0.8813856028639974, 'colsample_bytree': 0.9934242998391359, 'min_child_weight': 4, 'gamma': 2.54787392878663, 'reg_alpha': 0.0007632667905602551, 'reg_lambda': 5.990836394780806, 'max_delta_step': 6}. Best is trial 175 with value: 0.6657115009746588.

Best trial: 175. Best value: 0.665712:  96%|█████████▌| 191/200 [01:58<00:04,  1.84it/s]

[I 2025-11-10 18:44:05,147] Trial 192 pruned.

Best trial: 175. Best value: 0.665712:  96%|█████████▌| 192/200 [01:58<00:04,  1.78it/s]

[I 2025-11-10 18:44:05,754] Trial 194 pruned.
[I 2025-11-10 18:44:05,782] Trial 189 finished with value: 0.656588693957115 and parameters: {'max_depth': 8, 'learning_rate': 0.018499549989675197, 'n_estimators': 467, 'subsample': 0.8813688061378873, 'colsample_bytree': 0.978348920916437, 'min_child_weight': 4, 'gamma': 2.7158227083312134, 'reg_alpha': 0.0007141631777899807, 'reg_lambda': 6.203476142424899, 'max_delta_step': 5}. Best is trial 175 with value: 0.6657115009746588.

Best trial: 175. Best value: 0.665712:  97%|█████████▋| 194/200 [01:59<00:02,  2.08it/s]

[I 2025-11-10 18:44:06,523] Trial 191 finished with value: 0.641578947368421 and parameters: {'max_depth': 9, 'learning_rate': 0.018048364451297524, 'n_estimators': 473, 'subsample': 0.8862031744514338, 'colsample_bytree': 0.96489756981409, 'min_child_weight': 4, 'gamma': 2.408529031077116, 'reg_alpha': 0.002150659247645603, 'reg_lambda': 5.971812079710524, 'max_delta_step': 5}. Best is trial 175 with value: 0.6657115009746588.

Best trial: 175. Best value: 0.665712:  98%|█████████▊| 195/200 [02:00<00:03,  1.50it/s]

[I 2025-11-10 18:44:07,756] Trial 193 finished with value: 0.6491033138401561 and parameters: {'max_depth': 9, 'learning_rate': 0.018890291437776922, 'n_estimators': 647, 'subsample': 0.8735292714103376, 'colsample_bytree': 0.9657044955892806, 'min_child_weight': 4, 'gamma': 2.4295586750415854, 'reg_alpha': 0.0017606606221414805, 'reg_lambda': 7.063149784603879, 'max_delta_step': 5}. Best is trial 175 with value: 0.6657115009746588.

Best trial: 175. Best value: 0.665712:  98%|█████████▊| 196/200 [02:01<00:03,  1.33it/s]

[I 2025-11-10 18:44:08,764] Trial 195 finished with value: 0.6501461988304094 and parameters: {'max_depth': 9, 'learning_rate': 0.014520054230893295, 'n_estimators': 644, 'subsample': 0.7175325642264442, 'colsample_bytree': 0.96691976301513, 'min_child_weight': 4, 'gamma': 2.410971299901055, 'reg_alpha': 0.00019023702323118472, 'reg_lambda': 7.040594066339397, 'max_delta_step': 6}. Best is trial 175 with value: 0.6657115009746588.

Best trial: 175. Best value: 0.665712:  98%|█████████▊| 197/200 [02:02<00:02,  1.48it/s]

[I 2025-11-10 18:44:09,230] Trial 196 finished with value: 0.6590643274853801 and parameters: {'max_depth': 8, 'learning_rate': 0.02132468349653228, 'n_estimators': 634, 'subsample': 0.9176050159344994, 'colsample_bytree': 0.9659235857018836, 'min_child_weight': 4, 'gamma': 2.3273839323156227, 'reg_alpha': 0.0014207786653585963, 'reg_lambda': 7.144431231639644, 'max_delta_step': 5}. Best is trial 175 with value: 0.6657115009746588.

Best trial: 175. Best value: 0.665712:  99%|█████████▉| 198/200 [02:02<00:01,  1.55it/s]

[I 2025-11-10 18:44:09,799] Trial 197 finished with value: 0.6445029239766081 and parameters: {'max_depth': 8, 'learning_rate': 0.021458976425154222, 'n_estimators': 629, 'subsample': 0.9272465429247669, 'colsample_bytree': 0.9987684412971641, 'min_child_weight': 4, 'gamma': 2.367615870691153, 'reg_alpha': 0.00020611728766588405, 'reg_lambda': 6.88836574095411, 'max_delta_step': 4}. Best is trial 175 with value: 0.6657115009746588.

Best trial: 175. Best value: 0.665712: 100%|█████████▉| 199/200 [02:03<00:00,  1.48it/s]

[I 2025-11-10 18:44:10,557] Trial 198 finished with value: 0.6527777777777779 and parameters: {'max_depth': 8, 'learning_rate': 0.019551693850041324, 'n_estimators': 633, 'subsample': 0.9235327775184283, 'colsample_bytree': 0.9963439149887634, 'min_child_weight': 4, 'gamma': 2.3151784542500766, 'reg_alpha': 0.0011007869273197673, 'reg_lambda': 9.510640122158911, 'max_delta_step': 4}. Best is trial 175 with value: 0.6657115009746588.

Best trial: 175. Best value: 0.665712: 100%|██████████| 200/200 [02:04<00:00,  1.61it/s]

[I 2025-11-10 18:44:11,089] Trial 199 finished with value: 0.6530214424951267 and parameters: {'max_depth': 9, 'learning_rate': 0.0214128093948023, 'n_estimators': 620, 'subsample': 0.9261199129582021, 'colsample_bytree': 0.9672246941973429, 'min_child_weight': 4, 'gamma': 2.228631953019927, 'reg_alpha': 0.001320135169965435, 'reg_lambda': 8.605754236815663, 'max_delta_step': 5}. Best is trial 175 with value: 0.6657115009746588.

[I 2025-11-10 18:44:11,947] A new study created in memory with name: 3_4_roc_auc
Best trial: 3. Best value: 0.5:   0%|          | 1/200 [00:01<04:54,  1.48s/it]

[I 2025-11-10 18:44:13,423] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.20890422652704138, 'n_estimators': 345, 'subsample': 0.8329155281208152, 'colsample_bytree': 0.7601344955853151, 'min_child_weight': 8, 'gamma': 1.6119943878049314, 'reg_alpha': 5.176887971375259e-07, 'reg_lambda': 1.3170193555008995e-05, 'max_delta_step': 6}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   1%|          | 2/200 [00:02<03:53,  1.18s/it]

[I 2025-11-10 18:44:14,389] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.08955477328294731, 'n_estimators': 595, 'subsample': 0.8565630798089612, 'colsample_bytree': 0.7328868382936533, 'min_child_weight': 10, 'gamma': 2.0854446755619933, 'reg_alpha': 0.012393115747975395, 'reg_lambda': 0.028434871011297803, 'max_delta_step': 1}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   2%|▏         | 3/200 [00:02<02:32,  1.29it/s]

[I 2025-11-10 18:44:14,681] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01799723674619539, 'n_estimators': 690, 'subsample': 0.6735665364768929, 'colsample_bytree': 0.5982770321841004, 'min_child_weight': 6, 'gamma': 4.577526604008451, 'reg_alpha': 0.0015087202842489279, 'reg_lambda': 0.0002236482123564532, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 4. Best value: 0.505926:   2%|▏         | 4/200 [00:03<02:22,  1.38it/s]

[I 2025-11-10 18:44:15,333] Trial 4 finished with value: 0.5059259259259259 and parameters: {'max_depth': 9, 'learning_rate': 0.2903862126643718, 'n_estimators': 414, 'subsample': 0.9313230585816274, 'colsample_bytree': 0.9894533947091465, 'min_child_weight': 4, 'gamma': 1.2595082382314033, 'reg_alpha': 0.2271362721242494, 'reg_lambda': 3.5438207248007143e-06, 'max_delta_step': 3}. Best is trial 4 with value: 0.5059259259259259.

Best trial: 1. Best value: 0.540819:   2%|▎         | 5/200 [00:06<04:49,  1.48s/it]

[I 2025-11-10 18:44:18,160] Trial 1 finished with value: 0.5408187134502924 and parameters: {'max_depth': 6, 'learning_rate': 0.1401631522696885, 'n_estimators': 1273, 'subsample': 0.5040204311188756, 'colsample_bytree': 0.9321101933448481, 'min_child_weight': 2, 'gamma': 1.3918052685021909, 'reg_alpha': 3.0537141536594943, 'reg_lambda': 9.895024482480792e-08, 'max_delta_step': 2}. Best is trial 1 with value: 0.5408187134502924.

Best trial: 1. Best value: 0.540819:   3%|▎         | 6/200 [00:07<04:20,  1.34s/it]

[I 2025-11-10 18:44:19,224] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.026161591666670488, 'n_estimators': 1145, 'subsample': 0.817215387050734, 'colsample_bytree': 0.9543887912819076, 'min_child_weight': 7, 'gamma': 2.0131096827728183, 'reg_alpha': 0.021211669216434078, 'reg_lambda': 6.802739810947944e-08, 'max_delta_step': 5}. Best is trial 1 with value: 0.5408187134502924.

Best trial: 1. Best value: 0.540819:   4%|▍         | 8/200 [00:08<02:34,  1.24it/s]

[I 2025-11-10 18:44:19,873] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.053587888102292515, 'n_estimators': 1183, 'subsample': 0.7340698637268334, 'colsample_bytree': 0.8073484245662875, 'min_child_weight': 7, 'gamma': 0.6400491423225574, 'reg_alpha': 1.92675994547503e-06, 'reg_lambda': 1.7150690100834505, 'max_delta_step': 1}. Best is trial 1 with value: 0.5408187134502924.
[I 2025-11-10 18:44:20,023] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.018394049614765155, 'n_estimators': 989, 'subsample': 0.9864116897382926, 'colsample_bytree': 0.8582394391543962, 'min_child_weight': 2, 'gamma': 3.3229264808961076, 'reg_alpha': 8.601321023381947, 'reg_lambda': 3.344275794323601, 'max_delta_step': 2}. Best is trial 1 with value: 0.5408187134502924.

Best trial: 1. Best value: 0.540819:   4%|▍         | 9/200 [00:08<02:03,  1.55it/s]

[I 2025-11-10 18:44:20,312] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.053394654239265635, 'n_estimators': 529, 'subsample': 0.9630246324558871, 'colsample_bytree': 0.8978346251047724, 'min_child_weight': 7, 'gamma': 3.7868298277683654, 'reg_alpha': 0.0013482161603569466, 'reg_lambda': 7.368224871787896e-07, 'max_delta_step': 9}. Best is trial 1 with value: 0.5408187134502924.

Best trial: 1. Best value: 0.540819:   5%|▌         | 10/200 [00:09<02:56,  1.08it/s]

[I 2025-11-10 18:44:21,881] Trial 10 finished with value: 0.5138401559454191 and parameters: {'max_depth': 9, 'learning_rate': 0.2431489687259727, 'n_estimators': 439, 'subsample': 0.9223603066483699, 'colsample_bytree': 0.9117331216989608, 'min_child_weight': 4, 'gamma': 1.693435366106275, 'reg_alpha': 3.0387208773521e-05, 'reg_lambda': 0.0003567371940895098, 'max_delta_step': 1}. Best is trial 1 with value: 0.5408187134502924.

Best trial: 1. Best value: 0.540819:   6%|▌         | 11/200 [00:10<03:00,  1.05it/s]

[I 2025-11-10 18:44:22,894] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.12795332482406882, 'n_estimators': 586, 'subsample': 0.6545634160155318, 'colsample_bytree': 0.9809643093813711, 'min_child_weight': 6, 'gamma': 0.6422726154586461, 'reg_alpha': 1.3321953820915983e-06, 'reg_lambda': 0.00018907168090549311, 'max_delta_step': 10}. Best is trial 1 with value: 0.5408187134502924.

Best trial: 1. Best value: 0.540819:   6%|▌         | 12/200 [00:11<02:55,  1.07it/s]

[I 2025-11-10 18:44:23,772] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.013847159452646491, 'n_estimators': 875, 'subsample': 0.8724121124739838, 'colsample_bytree': 0.5434957314720865, 'min_child_weight': 10, 'gamma': 3.4928899954051835, 'reg_alpha': 0.08603478858432434, 'reg_lambda': 0.41254022220031167, 'max_delta_step': 7}. Best is trial 1 with value: 0.5408187134502924.

Best trial: 1. Best value: 0.540819:   6%|▋         | 13/200 [00:12<03:06,  1.00it/s]

[I 2025-11-10 18:44:24,925] Trial 9 finished with value: 0.5345029239766081 and parameters: {'max_depth': 6, 'learning_rate': 0.02684550818549503, 'n_estimators': 1301, 'subsample': 0.6239264486465035, 'colsample_bytree': 0.6827458339905348, 'min_child_weight': 3, 'gamma': 4.730573808053695, 'reg_alpha': 1.297023538093949e-07, 'reg_lambda': 0.07720981682004148, 'max_delta_step': 4}. Best is trial 1 with value: 0.5408187134502924.

Best trial: 1. Best value: 0.540819:   7%|▋         | 14/200 [00:17<05:58,  1.93s/it]

[I 2025-11-10 18:44:29,004] Trial 13 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1204551233093141, 'n_estimators': 1450, 'subsample': 0.508450191982708, 'colsample_bytree': 0.5369574450118402, 'min_child_weight': 1, 'gamma': 0.08430645762072153, 'reg_alpha': 9.050673590270817, 'reg_lambda': 1.0071325636304247e-08, 'max_delta_step': 5}. Best is trial 1 with value: 0.5408187134502924.

Best trial: 15. Best value: 0.549844:   8%|▊         | 15/200 [00:18<05:02,  1.64s/it]

[I 2025-11-10 18:44:29,966] Trial 15 finished with value: 0.5498440545808967 and parameters: {'max_depth': 7, 'learning_rate': 0.1545805174072318, 'n_estimators': 1462, 'subsample': 0.5144421427699983, 'colsample_bytree': 0.9039528500243826, 'min_child_weight': 1, 'gamma': 0.1797912545508864, 'reg_alpha': 3.673526327199569e-05, 'reg_lambda': 0.01116309926163612, 'max_delta_step': 0}. Best is trial 15 with value: 0.5498440545808967.

Best trial: 14. Best value: 0.583392:   8%|▊         | 16/200 [00:18<03:47,  1.24s/it]

[I 2025-11-10 18:44:30,276] Trial 14 finished with value: 0.5833918128654971 and parameters: {'max_depth': 7, 'learning_rate': 0.1750067059981042, 'n_estimators': 1495, 'subsample': 0.5374955659064838, 'colsample_bytree': 0.6666868932072813, 'min_child_weight': 1, 'gamma': 2.996953480480915, 'reg_alpha': 3.0880620457314184e-05, 'reg_lambda': 1.7559482610850122e-08, 'max_delta_step': 0}. Best is trial 14 with value: 0.5833918128654971.

Best trial: 16. Best value: 0.583821:   8%|▊         | 17/200 [00:20<04:23,  1.44s/it]

[I 2025-11-10 18:44:32,191] Trial 16 finished with value: 0.5838206627680312 and parameters: {'max_depth': 7, 'learning_rate': 0.03254120916066032, 'n_estimators': 1405, 'subsample': 0.5252463757495717, 'colsample_bytree': 0.6636589114606899, 'min_child_weight': 1, 'gamma': 2.7669967241976217, 'reg_alpha': 1.3907335446555604e-08, 'reg_lambda': 0.02013682163915609, 'max_delta_step': 4}. Best is trial 16 with value: 0.5838206627680312.

Best trial: 16. Best value: 0.583821:   9%|▉         | 18/200 [00:22<05:29,  1.81s/it]

[I 2025-11-10 18:44:34,863] Trial 17 finished with value: 0.5138206627680312 and parameters: {'max_depth': 7, 'learning_rate': 0.03441255254192532, 'n_estimators': 1472, 'subsample': 0.5499300684148427, 'colsample_bytree': 0.6577681376056559, 'min_child_weight': 3, 'gamma': 4.989050387891585, 'reg_alpha': 1.155251708076206e-08, 'reg_lambda': 0.007931770255510985, 'max_delta_step': 4}. Best is trial 16 with value: 0.5838206627680312.

Best trial: 16. Best value: 0.583821:  10%|▉         | 19/200 [00:24<05:17,  1.75s/it]

[I 2025-11-10 18:44:36,479] Trial 18 finished with value: 0.5578947368421053 and parameters: {'max_depth': 7, 'learning_rate': 0.15081952846963476, 'n_estimators': 1492, 'subsample': 0.5059775405243371, 'colsample_bytree': 0.8395808790402729, 'min_child_weight': 1, 'gamma': 0.008276908841059666, 'reg_alpha': 3.379772516953036e-05, 'reg_lambda': 0.004689900807726085, 'max_delta_step': 0}. Best is trial 16 with value: 0.5838206627680312.

Best trial: 16. Best value: 0.583821:  10%|█         | 20/200 [00:25<04:52,  1.62s/it]

[I 2025-11-10 18:44:37,800] Trial 19 finished with value: 0.5537037037037037 and parameters: {'max_depth': 8, 'learning_rate': 0.07643992743583922, 'n_estimators': 1475, 'subsample': 0.555957820156117, 'colsample_bytree': 0.6579428263012614, 'min_child_weight': 1, 'gamma': 2.944715486619923, 'reg_alpha': 1.2663584142948577e-08, 'reg_lambda': 0.006085811738620588, 'max_delta_step': 0}. Best is trial 16 with value: 0.5838206627680312.
[I 2025-11-10 18:44:37,825] Trial 20 pruned.

Best trial: 16. Best value: 0.583821:  11%|█         | 22/200 [00:26<03:10,  1.07s/it]

[I 2025-11-10 18:44:38,646] Trial 23 pruned.

Best trial: 16. Best value: 0.583821:  12%|█▏        | 23/200 [00:28<03:38,  1.24s/it]

[I 2025-11-10 18:44:40,393] Trial 21 finished with value: 0.5704873294346979 and parameters: {'max_depth': 8, 'learning_rate': 0.08112716683732069, 'n_estimators': 1033, 'subsample': 0.5859149974379758, 'colsample_bytree': 0.6214398629770933, 'min_child_weight': 1, 'gamma': 2.8059266307838033, 'reg_alpha': 2.5057150974703717e-05, 'reg_lambda': 0.002032960328367403, 'max_delta_step': 8}. Best is trial 16 with value: 0.5838206627680312.

Best trial: 16. Best value: 0.583821:  12%|█▏        | 24/200 [00:28<02:51,  1.03it/s]

[I 2025-11-10 18:44:40,620] Trial 22 finished with value: 0.5491228070175438 and parameters: {'max_depth': 8, 'learning_rate': 0.07495324191100816, 'n_estimators': 1055, 'subsample': 0.6020997573538002, 'colsample_bytree': 0.6180247250609998, 'min_child_weight': 4, 'gamma': 2.883133943313708, 'reg_alpha': 1.5457802020356483e-08, 'reg_lambda': 1.6119476206902846e-05, 'max_delta_step': 8}. Best is trial 16 with value: 0.5838206627680312.

Best trial: 16. Best value: 0.583821:  12%|█▎        | 25/200 [00:31<04:29,  1.54s/it]

[I 2025-11-10 18:44:43,668] Trial 24 finished with value: 0.5500584795321638 and parameters: {'max_depth': 8, 'learning_rate': 0.08029161326725334, 'n_estimators': 1306, 'subsample': 0.6036736917196177, 'colsample_bytree': 0.7146280188861823, 'min_child_weight': 2, 'gamma': 4.076958715931905, 'reg_alpha': 3.275630175107828e-05, 'reg_lambda': 0.10355144727682773, 'max_delta_step': 0}. Best is trial 16 with value: 0.5838206627680312.

Best trial: 16. Best value: 0.583821:  13%|█▎        | 26/200 [00:32<04:08,  1.43s/it]

[I 2025-11-10 18:44:44,808] Trial 25 finished with value: 0.5487329434697855 and parameters: {'max_depth': 7, 'learning_rate': 0.18026189501027165, 'n_estimators': 1316, 'subsample': 0.7296384445601348, 'colsample_bytree': 0.7342055711297275, 'min_child_weight': 2, 'gamma': 3.934990386797411, 'reg_alpha': 7.865757898841901e-06, 'reg_lambda': 0.17166378502524673, 'max_delta_step': 0}. Best is trial 16 with value: 0.5838206627680312.

Best trial: 16. Best value: 0.583821:  14%|█▎        | 27/200 [00:34<04:07,  1.43s/it]

[I 2025-11-10 18:44:46,245] Trial 26 finished with value: 0.5207017543859649 and parameters: {'max_depth': 8, 'learning_rate': 0.08043264637688845, 'n_estimators': 1304, 'subsample': 0.6230448141261875, 'colsample_bytree': 0.709997695349317, 'min_child_weight': 2, 'gamma': 4.083988888991287, 'reg_alpha': 8.428274337913307e-06, 'reg_lambda': 0.2841960875154391, 'max_delta_step': 6}. Best is trial 16 with value: 0.5838206627680312.

Best trial: 16. Best value: 0.583821:  14%|█▍        | 28/200 [00:34<03:07,  1.09s/it]

[I 2025-11-10 18:44:46,503] Trial 30 pruned.

Best trial: 16. Best value: 0.583821:  14%|█▍        | 29/200 [00:34<02:33,  1.11it/s]

[I 2025-11-10 18:44:46,936] Trial 27 finished with value: 0.5407407407407409 and parameters: {'max_depth': 8, 'learning_rate': 0.09567216059450472, 'n_estimators': 1314, 'subsample': 0.7298681337871404, 'colsample_bytree': 0.7104324895570042, 'min_child_weight': 2, 'gamma': 3.928534601874714, 'reg_alpha': 6.888670685596695e-06, 'reg_lambda': 0.15607805410720543, 'max_delta_step': 6}. Best is trial 16 with value: 0.5838206627680312.

Best trial: 16. Best value: 0.583821:  15%|█▌        | 30/200 [00:35<01:59,  1.42it/s]

[I 2025-11-10 18:44:47,175] Trial 28 finished with value: 0.5288304093567251 and parameters: {'max_depth': 5, 'learning_rate': 0.1893602812586061, 'n_estimators': 791, 'subsample': 0.712698797591327, 'colsample_bytree': 0.6973606776786084, 'min_child_weight': 2, 'gamma': 2.3592006397211347, 'reg_alpha': 4.418549613613617e-06, 'reg_lambda': 0.0012797791333382029, 'max_delta_step': 6}. Best is trial 16 with value: 0.5838206627680312.

Best trial: 16. Best value: 0.583821:  16%|█▌        | 31/200 [00:36<02:04,  1.35it/s]

[I 2025-11-10 18:44:48,000] Trial 29 finished with value: 0.521130604288499 and parameters: {'max_depth': 5, 'learning_rate': 0.107491637697738, 'n_estimators': 819, 'subsample': 0.6878265534868315, 'colsample_bytree': 0.5073478654106306, 'min_child_weight': 3, 'gamma': 2.3497532724464723, 'reg_alpha': 1.4129000309900076e-07, 'reg_lambda': 0.0014193635480695128, 'max_delta_step': 6}. Best is trial 16 with value: 0.5838206627680312.

Best trial: 31. Best value: 0.591871:  16%|█▌        | 32/200 [00:38<03:42,  1.33s/it]

[I 2025-11-10 18:44:50,715] Trial 31 finished with value: 0.5918713450292398 and parameters: {'max_depth': 6, 'learning_rate': 0.1024465300611405, 'n_estimators': 812, 'subsample': 0.5496493657515298, 'colsample_bytree': 0.7776980084464643, 'min_child_weight': 1, 'gamma': 2.415404218308886, 'reg_alpha': 0.00037253425385034536, 'reg_lambda': 1.6161382437028908e-06, 'max_delta_step': 10}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  16%|█▋        | 33/200 [00:40<03:47,  1.36s/it]

[I 2025-11-10 18:44:52,162] Trial 32 finished with value: 0.5660428849902533 and parameters: {'max_depth': 6, 'learning_rate': 0.01094276099103349, 'n_estimators': 756, 'subsample': 0.5395578232602465, 'colsample_bytree': 0.7590536059545229, 'min_child_weight': 1, 'gamma': 3.30268548081234, 'reg_alpha': 0.00023090856375797964, 'reg_lambda': 0.03631588436580285, 'max_delta_step': 10}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  17%|█▋        | 34/200 [00:40<02:54,  1.05s/it]

[I 2025-11-10 18:44:52,488] Trial 33 finished with value: 0.5428849902534114 and parameters: {'max_depth': 10, 'learning_rate': 0.099261123743071, 'n_estimators': 918, 'subsample': 0.7799662562125282, 'colsample_bytree': 0.7901850912052713, 'min_child_weight': 1, 'gamma': 3.357155390687462, 'reg_alpha': 0.00035555168049685056, 'reg_lambda': 0.028665710301615042, 'max_delta_step': 4}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  18%|█▊        | 35/200 [00:42<03:50,  1.40s/it]

[I 2025-11-10 18:44:54,696] Trial 35 finished with value: 0.5681286549707603 and parameters: {'max_depth': 6, 'learning_rate': 0.06595484869383202, 'n_estimators': 720, 'subsample': 0.5512555468099258, 'colsample_bytree': 0.8116719781123698, 'min_child_weight': 1, 'gamma': 3.256892135421616, 'reg_alpha': 0.000235636734192523, 'reg_lambda': 5.338794800987461e-07, 'max_delta_step': 10}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  18%|█▊        | 36/200 [00:43<03:03,  1.12s/it]

[I 2025-11-10 18:44:55,162] Trial 34 finished with value: 0.5839181286549706 and parameters: {'max_depth': 7, 'learning_rate': 0.06304331001508783, 'n_estimators': 1386, 'subsample': 0.5323546612528761, 'colsample_bytree': 0.8039515022845135, 'min_child_weight': 1, 'gamma': 3.3721850909024256, 'reg_alpha': 0.0007129815397981365, 'reg_lambda': 0.028992887042930557, 'max_delta_step': 3}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  18%|█▊        | 37/200 [00:43<02:39,  1.02it/s]

[I 2025-11-10 18:44:55,814] Trial 38 pruned.

Best trial: 31. Best value: 0.591871:  19%|█▉        | 38/200 [00:44<02:01,  1.33it/s]

[I 2025-11-10 18:44:56,033] Trial 37 finished with value: 0.5797270955165692 and parameters: {'max_depth': 6, 'learning_rate': 0.05930398486973005, 'n_estimators': 690, 'subsample': 0.5324283365001008, 'colsample_bytree': 0.6088661371379891, 'min_child_weight': 1, 'gamma': 1.9846762749980518, 'reg_alpha': 0.0024398038459010557, 'reg_lambda': 1.4712195051630217e-07, 'max_delta_step': 9}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  20%|█▉        | 39/200 [00:44<01:34,  1.70it/s]

[I 2025-11-10 18:44:56,238] Trial 39 pruned.

Best trial: 31. Best value: 0.591871:  20%|██        | 40/200 [00:44<01:38,  1.63it/s]

[I 2025-11-10 18:44:56,914] Trial 40 pruned.

Best trial: 31. Best value: 0.591871:  20%|██        | 41/200 [00:45<01:19,  2.00it/s]

[I 2025-11-10 18:44:57,149] Trial 41 pruned.

Best trial: 31. Best value: 0.591871:  21%|██        | 42/200 [00:45<01:11,  2.22it/s]

[I 2025-11-10 18:44:57,486] Trial 42 pruned.
[I 2025-11-10 18:44:57,513] Trial 36 finished with value: 0.5644444444444444 and parameters: {'max_depth': 6, 'learning_rate': 0.0605192994667513, 'n_estimators': 896, 'subsample': 0.5788644073825542, 'colsample_bytree': 0.7942310560336305, 'min_child_weight': 1, 'gamma': 2.725173304868479, 'reg_alpha': 0.0014572975030052017, 'reg_lambda': 6.155524178341527e-07, 'max_delta_step': 9}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  22%|██▎       | 45/200 [00:46<00:48,  3.17it/s]

[I 2025-11-10 18:44:58,006] Trial 44 pruned.
[I 2025-11-10 18:44:58,178] Trial 46 pruned.

Best trial: 31. Best value: 0.591871:  23%|██▎       | 46/200 [00:46<00:39,  3.86it/s]

[I 2025-11-10 18:44:58,276] Trial 45 pruned.
[I 2025-11-10 18:44:58,323] Trial 43 pruned.

Best trial: 31. Best value: 0.591871:  24%|██▍       | 48/200 [00:47<00:53,  2.84it/s]

[I 2025-11-10 18:44:59,229] Trial 47 pruned.

Best trial: 31. Best value: 0.591871:  24%|██▍       | 49/200 [00:47<00:50,  3.01it/s]

[I 2025-11-10 18:44:59,495] Trial 49 pruned.

Best trial: 31. Best value: 0.591871:  25%|██▌       | 50/200 [00:49<01:48,  1.38it/s]

[I 2025-11-10 18:45:01,387] Trial 50 finished with value: 0.5573879142300195 and parameters: {'max_depth': 6, 'learning_rate': 0.12030859740198127, 'n_estimators': 509, 'subsample': 0.6067763850423437, 'colsample_bytree': 0.664977308832716, 'min_child_weight': 1, 'gamma': 2.1215763881127407, 'reg_alpha': 0.000953882327751888, 'reg_lambda': 1.5448377215952183, 'max_delta_step': 5}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  26%|██▌       | 51/200 [00:50<01:45,  1.41it/s]

[I 2025-11-10 18:45:02,066] Trial 51 finished with value: 0.5479142300194931 and parameters: {'max_depth': 9, 'learning_rate': 0.11526606918074213, 'n_estimators': 564, 'subsample': 0.6072710419606556, 'colsample_bytree': 0.6759553679919061, 'min_child_weight': 1, 'gamma': 0.9513938839290914, 'reg_alpha': 0.0007546252496985113, 'reg_lambda': 3.6842341489682055e-08, 'max_delta_step': 1}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  26%|██▌       | 52/200 [00:51<02:14,  1.10it/s]

[I 2025-11-10 18:45:03,497] Trial 52 finished with value: 0.5908771929824561 and parameters: {'max_depth': 9, 'learning_rate': 0.02049534256751736, 'n_estimators': 520, 'subsample': 0.6198943587322168, 'colsample_bytree': 0.6368231443374128, 'min_child_weight': 1, 'gamma': 1.769767041586076, 'reg_alpha': 8.761370675050105e-05, 'reg_lambda': 0.8612674399259932, 'max_delta_step': 1}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  26%|██▋       | 53/200 [00:51<01:45,  1.39it/s]

[I 2025-11-10 18:45:03,731] Trial 48 finished with value: 0.5357699805068226 and parameters: {'max_depth': 6, 'learning_rate': 0.04972488406352221, 'n_estimators': 1397, 'subsample': 0.5036773912623792, 'colsample_bytree': 0.6786596941491951, 'min_child_weight': 3, 'gamma': 3.6496142427824636, 'reg_alpha': 0.000841679065744054, 'reg_lambda': 3.900640613387472e-08, 'max_delta_step': 7}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  27%|██▋       | 54/200 [00:54<03:21,  1.38s/it]

[I 2025-11-10 18:45:06,750] Trial 56 finished with value: 0.5812280701754385 and parameters: {'max_depth': 10, 'learning_rate': 0.019000336090342906, 'n_estimators': 396, 'subsample': 0.552033364439563, 'colsample_bytree': 0.631787802213342, 'min_child_weight': 1, 'gamma': 1.8488312345212206, 'reg_alpha': 9.350601951947284e-05, 'reg_lambda': 2.171209463996899, 'max_delta_step': 1}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  28%|██▊       | 55/200 [00:55<02:31,  1.04s/it]

[I 2025-11-10 18:45:06,975] Trial 54 finished with value: 0.5540740740740739 and parameters: {'max_depth': 9, 'learning_rate': 0.052530518965819874, 'n_estimators': 958, 'subsample': 0.5486327752546514, 'colsample_bytree': 0.6300059426678081, 'min_child_weight': 1, 'gamma': 2.7434672729206815, 'reg_alpha': 0.00012602062870917908, 'reg_lambda': 0.014412909585747117, 'max_delta_step': 4}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  28%|██▊       | 56/200 [00:55<02:00,  1.19it/s]

[I 2025-11-10 18:45:07,321] Trial 57 pruned.

Best trial: 31. Best value: 0.591871:  28%|██▊       | 57/200 [00:55<01:34,  1.52it/s]

[I 2025-11-10 18:45:07,553] Trial 58 pruned.

Best trial: 31. Best value: 0.591871:  29%|██▉       | 58/200 [00:55<01:14,  1.91it/s]

[I 2025-11-10 18:45:07,754] Trial 55 finished with value: 0.5751851851851851 and parameters: {'max_depth': 9, 'learning_rate': 0.016256949010903937, 'n_estimators': 437, 'subsample': 0.5517654504033108, 'colsample_bytree': 0.638200629318163, 'min_child_weight': 1, 'gamma': 1.0645413319955197, 'reg_alpha': 0.00010032790033861753, 'reg_lambda': 0.7010877162282521, 'max_delta_step': 1}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  30%|██▉       | 59/200 [00:57<01:48,  1.30it/s]

[I 2025-11-10 18:45:09,099] Trial 53 finished with value: 0.5687719298245614 and parameters: {'max_depth': 9, 'learning_rate': 0.01968176071944444, 'n_estimators': 944, 'subsample': 0.7838346184161051, 'colsample_bytree': 0.8372952664099478, 'min_child_weight': 1, 'gamma': 0.9938301236131448, 'reg_alpha': 0.0001087291841389666, 'reg_lambda': 3.708189275228878e-08, 'max_delta_step': 1}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  30%|███       | 60/200 [00:58<02:14,  1.04it/s]

[I 2025-11-10 18:45:10,506] Trial 60 finished with value: 0.5549512670565303 and parameters: {'max_depth': 9, 'learning_rate': 0.017119334202421146, 'n_estimators': 399, 'subsample': 0.6285077105787622, 'colsample_bytree': 0.8108921104515526, 'min_child_weight': 1, 'gamma': 2.4947034088907, 'reg_alpha': 4.441704090635788e-07, 'reg_lambda': 4.5581405805406225, 'max_delta_step': 3}. Best is trial 31 with value: 0.5918713450292398.
[I 2025-11-10 18:45:10,514] Trial 61 finished with value: 0.5527485380116959 and parameters: {'max_depth': 10, 'learning_rate': 0.015295815506830108, 'n_estimators': 329, 'subsample': 0.6646505960524329, 'colsample_bytree': 0.8449934116615857, 'min_child_weight': 1, 'gamma': 2.4860881211490855, 'reg_alpha': 4.116308773198379e-07, 'reg_lambda': 3.7075892190175175, 'max_delta_step': 0}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  31%|███       | 62/200 [00:59<01:41,  1.36it/s]

[I 2025-11-10 18:45:11,454] Trial 64 pruned.

Best trial: 31. Best value: 0.591871:  32%|███▏      | 64/200 [00:59<01:09,  1.97it/s]

[I 2025-11-10 18:45:11,773] Trial 63 pruned.
[I 2025-11-10 18:45:11,927] Trial 59 finished with value: 0.572729044834308 and parameters: {'max_depth': 10, 'learning_rate': 0.01501515726425027, 'n_estimators': 437, 'subsample': 0.6209212752861477, 'colsample_bytree': 0.8298145106772179, 'min_child_weight': 1, 'gamma': 1.126056579477914, 'reg_alpha': 8.228133828537936e-05, 'reg_lambda': 6.245232516700221, 'max_delta_step': 1}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  32%|███▎      | 65/200 [01:00<00:55,  2.42it/s]

[I 2025-11-10 18:45:12,087] Trial 62 finished with value: 0.5559259259259259 and parameters: {'max_depth': 10, 'learning_rate': 0.013498545122906946, 'n_estimators': 508, 'subsample': 0.6266939404204434, 'colsample_bytree': 0.6984512174698888, 'min_child_weight': 2, 'gamma': 2.5429093937454064, 'reg_alpha': 4.481302047691825e-07, 'reg_lambda': 4.476916021437928, 'max_delta_step': 3}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  33%|███▎      | 66/200 [01:00<01:02,  2.15it/s]

[I 2025-11-10 18:45:12,696] Trial 67 pruned.
[I 2025-11-10 18:45:12,763] Trial 68 pruned.

Best trial: 31. Best value: 0.591871:  34%|███▍      | 68/200 [01:01<01:07,  1.95it/s]

[I 2025-11-10 18:45:13,836] Trial 70 pruned.

Best trial: 31. Best value: 0.591871:  34%|███▍      | 69/200 [01:02<01:00,  2.18it/s]

[I 2025-11-10 18:45:14,119] Trial 69 finished with value: 0.5831968810916178 and parameters: {'max_depth': 8, 'learning_rate': 0.21693447629373047, 'n_estimators': 240, 'subsample': 0.5731455642659571, 'colsample_bytree': 0.6058433228063562, 'min_child_weight': 1, 'gamma': 1.9424715517787237, 'reg_alpha': 1.60909378685549e-05, 'reg_lambda': 0.049966585232244905, 'max_delta_step': 0}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  35%|███▌      | 70/200 [01:02<00:53,  2.42it/s]

[I 2025-11-10 18:45:14,405] Trial 72 pruned.

Best trial: 31. Best value: 0.591871:  36%|███▌      | 71/200 [01:02<00:49,  2.60it/s]

[I 2025-11-10 18:45:14,713] Trial 73 pruned.

Best trial: 31. Best value: 0.591871:  36%|███▌      | 72/200 [01:02<00:42,  2.99it/s]

[I 2025-11-10 18:45:14,917] Trial 65 finished with value: 0.5828460038986355 and parameters: {'max_depth': 7, 'learning_rate': 0.0308099636503476, 'n_estimators': 493, 'subsample': 0.5371988388665588, 'colsample_bytree': 0.601333398689674, 'min_child_weight': 1, 'gamma': 1.9275721543181834, 'reg_alpha': 1.4115730741264597e-05, 'reg_lambda': 0.04069574754513748, 'max_delta_step': 0}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  36%|███▋      | 73/200 [01:03<01:00,  2.11it/s]

[I 2025-11-10 18:45:15,736] Trial 71 finished with value: 0.5698635477582845 and parameters: {'max_depth': 5, 'learning_rate': 0.07002368013787183, 'n_estimators': 233, 'subsample': 0.9125957002012566, 'colsample_bytree': 0.6513681060967406, 'min_child_weight': 1, 'gamma': 2.265493831541721, 'reg_alpha': 0.07967821451900388, 'reg_lambda': 0.0003728504052358483, 'max_delta_step': 9}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  37%|███▋      | 74/200 [01:04<00:59,  2.12it/s]

[I 2025-11-10 18:45:16,205] Trial 76 pruned.

Best trial: 31. Best value: 0.591871:  38%|███▊      | 75/200 [01:04<00:50,  2.50it/s]

[I 2025-11-10 18:45:16,429] Trial 74 finished with value: 0.5882456140350877 and parameters: {'max_depth': 7, 'learning_rate': 0.17545941912561566, 'n_estimators': 293, 'subsample': 0.5772396498354578, 'colsample_bytree': 0.6552752298161589, 'min_child_weight': 1, 'gamma': 1.942352082278142, 'reg_alpha': 0.00024313949011043438, 'reg_lambda': 0.009798609771455656, 'max_delta_step': 0}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  38%|███▊      | 76/200 [01:04<00:47,  2.63it/s]

[I 2025-11-10 18:45:16,764] Trial 78 pruned.

Best trial: 31. Best value: 0.591871:  38%|███▊      | 77/200 [01:05<00:54,  2.24it/s]

[I 2025-11-10 18:45:17,370] Trial 75 finished with value: 0.5600974658869395 and parameters: {'max_depth': 7, 'learning_rate': 0.022387511276424698, 'n_estimators': 265, 'subsample': 0.8749963940775018, 'colsample_bytree': 0.6897610611075325, 'min_child_weight': 1, 'gamma': 2.890335935514831, 'reg_alpha': 2.7580392104852125e-06, 'reg_lambda': 0.016894176284058662, 'max_delta_step': 0}. Best is trial 31 with value: 0.5918713450292398.

Best trial: 31. Best value: 0.591871:  39%|███▉      | 78/200 [01:05<00:50,  2.44it/s]

[I 2025-11-10 18:45:17,689] Trial 80 pruned.
[I 2025-11-10 18:45:17,697] Trial 79 pruned.

Best trial: 31. Best value: 0.591871:  40%|████      | 80/200 [01:06<00:42,  2.83it/s]

[I 2025-11-10 18:45:18,266] Trial 66 finished with value: 0.5762962962962963 and parameters: {'max_depth': 7, 'learning_rate': 0.0326966822514894, 'n_estimators': 1103, 'subsample': 0.5376109314428433, 'colsample_bytree': 0.6023612094214299, 'min_child_weight': 1, 'gamma': 1.9313755762356557, 'reg_alpha': 0.05391218952667555, 'reg_lambda': 0.05716578293625195, 'max_delta_step': 10}. Best is trial 31 with value: 0.5918713450292398.
[I 2025-11-10 18:45:18,270] Trial 82 pruned.

Best trial: 84. Best value: 0.650877:  42%|████▏     | 83/200 [01:07<00:49,  2.34it/s]

[I 2025-11-10 18:45:19,809] Trial 84 finished with value: 0.650877192982456 and parameters: {'max_depth': 8, 'learning_rate': 0.2516112537378362, 'n_estimators': 291, 'subsample': 0.5174705320656434, 'colsample_bytree': 0.6224894349719515, 'min_child_weight': 1, 'gamma': 1.8288406686366818, 'reg_alpha': 0.000354504190475689, 'reg_lambda': 0.1771511886118081, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.
[I 2025-11-10 18:45:19,911] Trial 83 finished with value: 0.6079142300194931 and parameters: {'max_depth': 8, 'learning_rate': 0.24110439573869066, 'n_estimators': 297, 'subsample': 0.5598707820362758, 'colsample_bytree': 0.6232815083799165, 'min_child_weight': 1, 'gamma': 1.8320951953083329, 'reg_alpha': 1.0723824747737882e-06, 'reg_lambda': 0.16975592353357072, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  42%|████▏     | 84/200 [01:08<00:46,  2.47it/s]

[I 2025-11-10 18:45:20,243] Trial 86 pruned.

Best trial: 84. Best value: 0.650877:  42%|████▎     | 85/200 [01:08<00:42,  2.72it/s]

[I 2025-11-10 18:45:20,504] Trial 81 finished with value: 0.6070760233918129 and parameters: {'max_depth': 7, 'learning_rate': 0.14719167222155213, 'n_estimators': 479, 'subsample': 0.6012622240431176, 'colsample_bytree': 0.5972642538439782, 'min_child_weight': 1, 'gamma': 2.3669606209192073, 'reg_alpha': 1.7360505875521682e-05, 'reg_lambda': 0.048527905987536375, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.
[I 2025-11-10 18:45:20,508] Trial 87 pruned.

Best trial: 84. Best value: 0.650877:  44%|████▎     | 87/200 [01:09<00:44,  2.55it/s]

[I 2025-11-10 18:45:21,349] Trial 85 finished with value: 0.5765302144249513 and parameters: {'max_depth': 8, 'learning_rate': 0.23441259225543798, 'n_estimators': 287, 'subsample': 0.5165330369993895, 'colsample_bytree': 0.6210310679607512, 'min_child_weight': 2, 'gamma': 1.6572671673812986, 'reg_alpha': 0.00040132102539317617, 'reg_lambda': 0.13030501748587142, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  44%|████▍     | 88/200 [01:09<00:44,  2.54it/s]

[I 2025-11-10 18:45:21,751] Trial 77 finished with value: 0.6288888888888888 and parameters: {'max_depth': 8, 'learning_rate': 0.2279428089364776, 'n_estimators': 1135, 'subsample': 0.5164284497985617, 'colsample_bytree': 0.5630473124063733, 'min_child_weight': 1, 'gamma': 1.889975731063511, 'reg_alpha': 1.2034186858449846e-05, 'reg_lambda': 0.30218999591671125, 'max_delta_step': 0}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  45%|████▌     | 90/200 [01:10<00:32,  3.42it/s]

[I 2025-11-10 18:45:21,968] Trial 89 pruned.
[I 2025-11-10 18:45:22,099] Trial 88 pruned.

Best trial: 84. Best value: 0.650877:  46%|████▌     | 91/200 [01:10<00:28,  3.81it/s]

[I 2025-11-10 18:45:22,286] Trial 91 pruned.

Best trial: 84. Best value: 0.650877:  46%|████▌     | 92/200 [01:10<00:36,  2.99it/s]

[I 2025-11-10 18:45:22,802] Trial 92 pruned.

Best trial: 84. Best value: 0.650877:  46%|████▋     | 93/200 [01:11<00:47,  2.27it/s]

[I 2025-11-10 18:45:23,517] Trial 90 finished with value: 0.5528460038986355 and parameters: {'max_depth': 6, 'learning_rate': 0.1370424153902031, 'n_estimators': 368, 'subsample': 0.6139631780668685, 'colsample_bytree': 0.5890474281757726, 'min_child_weight': 1, 'gamma': 2.4162561284228534, 'reg_alpha': 0.000165336660957011, 'reg_lambda': 0.008697227871013723, 'max_delta_step': 4}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  47%|████▋     | 94/200 [01:12<00:51,  2.05it/s]

[I 2025-11-10 18:45:24,112] Trial 93 finished with value: 0.559766081871345 and parameters: {'max_depth': 9, 'learning_rate': 0.198571264147907, 'n_estimators': 361, 'subsample': 0.5649969595697354, 'colsample_bytree': 0.5901974685299853, 'min_child_weight': 1, 'gamma': 2.1140188147020007, 'reg_alpha': 6.033493725339706e-06, 'reg_lambda': 0.4531508437571095, 'max_delta_step': 2}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  48%|████▊     | 95/200 [01:13<01:04,  1.63it/s]

[I 2025-11-10 18:45:25,040] Trial 96 pruned.

Best trial: 84. Best value: 0.650877:  48%|████▊     | 96/200 [01:13<01:08,  1.51it/s]

[I 2025-11-10 18:45:25,807] Trial 97 pruned.

Best trial: 84. Best value: 0.650877:  48%|████▊     | 97/200 [01:14<01:03,  1.63it/s]

[I 2025-11-10 18:45:26,305] Trial 98 pruned.

Best trial: 84. Best value: 0.650877:  49%|████▉     | 98/200 [01:15<01:03,  1.60it/s]

[I 2025-11-10 18:45:26,958] Trial 99 pruned.

Best trial: 84. Best value: 0.650877:  50%|████▉     | 99/200 [01:15<00:49,  2.02it/s]

[I 2025-11-10 18:45:27,150] Trial 100 pruned.

Best trial: 84. Best value: 0.650877:  50%|█████     | 100/200 [01:15<00:47,  2.12it/s]

[I 2025-11-10 18:45:27,561] Trial 102 pruned.

Best trial: 84. Best value: 0.650877:  50%|█████     | 101/200 [01:16<00:51,  1.94it/s]

[I 2025-11-10 18:45:28,184] Trial 101 pruned.

Best trial: 84. Best value: 0.650877:  51%|█████     | 102/200 [01:16<00:51,  1.90it/s]

[I 2025-11-10 18:45:28,732] Trial 103 pruned.

Best trial: 84. Best value: 0.650877:  52%|█████▏    | 103/200 [01:17<00:45,  2.14it/s]

[I 2025-11-10 18:45:29,065] Trial 105 pruned.

Best trial: 84. Best value: 0.650877:  52%|█████▏    | 104/200 [01:17<00:51,  1.86it/s]

[I 2025-11-10 18:45:29,770] Trial 104 finished with value: 0.5896491228070175 and parameters: {'max_depth': 8, 'learning_rate': 0.14687792398771357, 'n_estimators': 255, 'subsample': 0.5810535069287371, 'colsample_bytree': 0.6294516621335725, 'min_child_weight': 1, 'gamma': 1.8084492461423436, 'reg_alpha': 2.0519462268197772e-05, 'reg_lambda': 0.103633359492307, 'max_delta_step': 0}. Best is trial 84 with value: 0.650877192982456.
[I 2025-11-10 18:45:29,789] Trial 95 finished with value: 0.5671539961013645 and parameters: {'max_depth': 6, 'learning_rate': 0.1341529444978491, 'n_estimators': 1435, 'subsample': 0.5642526604827645, 'colsample_bytree': 0.5692119702953338, 'min_child_weight': 1, 'gamma': 2.7975074048809763, 'reg_alpha': 5.237487576717197e-05, 'reg_lambda': 0.0256421104032743, 'max_delta_step': 2}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  53%|█████▎    | 106/200 [01:18<00:35,  2.66it/s]

[I 2025-11-10 18:45:30,143] Trial 94 finished with value: 0.5765497076023391 and parameters: {'max_depth': 6, 'learning_rate': 0.19956240339483966, 'n_estimators': 1429, 'subsample': 0.563071393015166, 'colsample_bytree': 0.7812606424919232, 'min_child_weight': 1, 'gamma': 2.4243049927428335, 'reg_alpha': 5.2901930115703386e-06, 'reg_lambda': 0.24357287290193883, 'max_delta_step': 3}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  54%|█████▎    | 107/200 [01:18<00:31,  2.96it/s]

[I 2025-11-10 18:45:30,355] Trial 107 pruned.
[I 2025-11-10 18:45:30,532] Trial 109 pruned.

Best trial: 84. Best value: 0.650877:  55%|█████▍    | 109/200 [01:19<00:30,  3.03it/s]

[I 2025-11-10 18:45:30,957] Trial 111 pruned.

Best trial: 84. Best value: 0.650877:  55%|█████▌    | 110/200 [01:19<00:36,  2.44it/s]

[I 2025-11-10 18:45:31,573] Trial 112 pruned.
[I 2025-11-10 18:45:31,579] Trial 106 finished with value: 0.6077777777777778 and parameters: {'max_depth': 8, 'learning_rate': 0.2972135815457664, 'n_estimators': 421, 'subsample': 0.5636257424881115, 'colsample_bytree': 0.6107506695881445, 'min_child_weight': 1, 'gamma': 3.2102201115360005, 'reg_alpha': 3.479976288278062e-06, 'reg_lambda': 0.05249479705820203, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  56%|█████▌    | 112/200 [01:19<00:26,  3.27it/s]

[I 2025-11-10 18:45:31,926] Trial 114 pruned.

Best trial: 84. Best value: 0.650877:  56%|█████▋    | 113/200 [01:20<00:25,  3.45it/s]

[I 2025-11-10 18:45:32,166] Trial 110 pruned.

Best trial: 84. Best value: 0.650877:  57%|█████▋    | 114/200 [01:20<00:22,  3.79it/s]

[I 2025-11-10 18:45:32,353] Trial 113 pruned.

Best trial: 84. Best value: 0.650877:  57%|█████▊    | 115/200 [01:20<00:22,  3.79it/s]

[I 2025-11-10 18:45:32,616] Trial 108 finished with value: 0.604307992202729 and parameters: {'max_depth': 8, 'learning_rate': 0.1430442967604347, 'n_estimators': 410, 'subsample': 0.6368213463524972, 'colsample_bytree': 0.6630503410667276, 'min_child_weight': 1, 'gamma': 2.419201968829473, 'reg_alpha': 3.5697307892466345e-06, 'reg_lambda': 9.509312608903934e-06, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  58%|█████▊    | 116/200 [01:21<00:37,  2.27it/s]

[I 2025-11-10 18:45:33,520] Trial 115 pruned.

Best trial: 84. Best value: 0.650877:  58%|█████▊    | 117/200 [01:22<00:40,  2.07it/s]

[I 2025-11-10 18:45:34,110] Trial 119 pruned.

Best trial: 84. Best value: 0.650877:  59%|█████▉    | 118/200 [01:23<00:50,  1.63it/s]

[I 2025-11-10 18:45:35,045] Trial 116 finished with value: 0.5577777777777777 and parameters: {'max_depth': 8, 'learning_rate': 0.29061851921942927, 'n_estimators': 569, 'subsample': 0.582428203699731, 'colsample_bytree': 0.6827760779127091, 'min_child_weight': 1, 'gamma': 1.4074354969578036, 'reg_alpha': 8.453531545444304e-06, 'reg_lambda': 0.08582087211908242, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  60%|█████▉    | 119/200 [01:23<00:41,  1.94it/s]

[I 2025-11-10 18:45:35,322] Trial 118 finished with value: 0.5534502923976609 and parameters: {'max_depth': 9, 'learning_rate': 0.0970248152743098, 'n_estimators': 464, 'subsample': 0.5803684029058551, 'colsample_bytree': 0.5788561282791403, 'min_child_weight': 1, 'gamma': 1.8258340225325929, 'reg_alpha': 1.5505588311298778e-06, 'reg_lambda': 0.15281812338706632, 'max_delta_step': 2}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  60%|██████    | 120/200 [01:24<00:54,  1.46it/s]

[I 2025-11-10 18:45:36,417] Trial 120 finished with value: 0.5686549707602339 and parameters: {'max_depth': 8, 'learning_rate': 0.2893838969121413, 'n_estimators': 432, 'subsample': 0.6950070668328537, 'colsample_bytree': 0.6553802218597193, 'min_child_weight': 2, 'gamma': 2.309438071178185, 'reg_alpha': 7.686824991096549e-08, 'reg_lambda': 1.8130257987379692, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  60%|██████    | 121/200 [01:24<00:47,  1.65it/s]

[I 2025-11-10 18:45:36,839] Trial 123 pruned.

Best trial: 84. Best value: 0.650877:  61%|██████    | 122/200 [01:25<00:43,  1.81it/s]

[I 2025-11-10 18:45:37,266] Trial 124 pruned.
[I 2025-11-10 18:45:37,283] Trial 121 finished with value: 0.5476413255360624 and parameters: {'max_depth': 9, 'learning_rate': 0.12321063603664337, 'n_estimators': 418, 'subsample': 0.7848664326848892, 'colsample_bytree': 0.5780591796636311, 'min_child_weight': 2, 'gamma': 1.7810570271846495, 'reg_alpha': 3.8863508526735155e-06, 'reg_lambda': 0.04374698394639329, 'max_delta_step': 2}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  62%|██████▏   | 124/200 [01:25<00:30,  2.49it/s]

[I 2025-11-10 18:45:37,709] Trial 126 pruned.
[I 2025-11-10 18:45:37,760] Trial 122 finished with value: 0.5445614035087719 and parameters: {'max_depth': 8, 'learning_rate': 0.042786571464168734, 'n_estimators': 382, 'subsample': 0.7999907967048083, 'colsample_bytree': 0.5516444614363386, 'min_child_weight': 2, 'gamma': 2.372234319387546, 'reg_alpha': 0.00024560464451406887, 'reg_lambda': 0.04515207847007256, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  63%|██████▎   | 126/200 [01:26<00:24,  2.99it/s]

[I 2025-11-10 18:45:38,178] Trial 117 finished with value: 0.5709941520467836 and parameters: {'max_depth': 7, 'learning_rate': 0.2947701307879486, 'n_estimators': 1151, 'subsample': 0.5849115671068733, 'colsample_bytree': 0.8179767030658137, 'min_child_weight': 1, 'gamma': 1.4316392599902676, 'reg_alpha': 2.8335229470439844e-05, 'reg_lambda': 0.1311563810088229, 'max_delta_step': 7}. Best is trial 84 with value: 0.650877192982456.
[I 2025-11-10 18:45:38,236] Trial 128 pruned.

Best trial: 84. Best value: 0.650877:  64%|██████▍   | 128/200 [01:26<00:21,  3.39it/s]

[I 2025-11-10 18:45:38,629] Trial 130 pruned.

Best trial: 84. Best value: 0.650877:  64%|██████▍   | 129/200 [01:27<00:27,  2.54it/s]

[I 2025-11-10 18:45:39,396] Trial 125 finished with value: 0.5975243664717349 and parameters: {'max_depth': 7, 'learning_rate': 0.0417665555933886, 'n_estimators': 296, 'subsample': 0.526889573526239, 'colsample_bytree': 0.5963333951871006, 'min_child_weight': 1, 'gamma': 2.9803400044243564, 'reg_alpha': 1.864448157847949e-05, 'reg_lambda': 6.456377285871253e-06, 'max_delta_step': 0}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  65%|██████▌   | 130/200 [01:27<00:28,  2.47it/s]

[I 2025-11-10 18:45:39,847] Trial 132 pruned.

Best trial: 84. Best value: 0.650877:  66%|██████▌   | 131/200 [01:28<00:32,  2.10it/s]

[I 2025-11-10 18:45:40,542] Trial 133 pruned.

Best trial: 84. Best value: 0.650877:  66%|██████▌   | 132/200 [01:29<00:37,  1.83it/s]

[I 2025-11-10 18:45:41,278] Trial 129 finished with value: 0.5598830409356725 and parameters: {'max_depth': 7, 'learning_rate': 0.15724626912752604, 'n_estimators': 531, 'subsample': 0.7402101548993133, 'colsample_bytree': 0.6535898032604002, 'min_child_weight': 1, 'gamma': 3.4640471560799977, 'reg_alpha': 0.00016731214301761357, 'reg_lambda': 0.012609534514927315, 'max_delta_step': 0}. Best is trial 84 with value: 0.650877192982456.
[I 2025-11-10 18:45:41,285] Trial 127 finished with value: 0.5938401559454191 and parameters: {'max_depth': 7, 'learning_rate': 0.043230500503540055, 'n_estimators': 543, 'subsample': 0.6054919082633677, 'colsample_bytree': 0.6725659047991207, 'min_child_weight': 1, 'gamma': 2.6638096065735493, 'reg_alpha': 0.00021540036082173515, 'reg_lambda': 2.5634360135773852e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  68%|██████▊   | 136/200 [01:33<00:51,  1.25it/s]

[I 2025-11-10 18:45:45,649] Trial 131 finished with value: 0.572475633528265 and parameters: {'max_depth': 7, 'learning_rate': 0.012384784654235691, 'n_estimators': 802, 'subsample': 0.5701667378694156, 'colsample_bytree': 0.9589221440307127, 'min_child_weight': 1, 'gamma': 1.6212330938425767, 'reg_alpha': 0.00020416583504415616, 'reg_lambda': 0.013289521262388174, 'max_delta_step': 0}. Best is trial 84 with value: 0.650877192982456.
[I 2025-11-10 18:45:45,677] Trial 134 finished with value: 0.5816179337231968 and parameters: {'max_depth': 7, 'learning_rate': 0.04293146310475378, 'n_estimators': 859, 'subsample': 0.5242197312896193, 'colsample_bytree': 0.8792494058568776, 'min_child_weight': 1, 'gamma': 2.967316193114974, 'reg_alpha': 4.09117895627373e-05, 'reg_lambda': 0.01322515298417414, 'max_delta_step': 0}. Best is trial 84 with value: 0.650877192982456.
[I 2025-11-10 18:45:45,794] Trial 136 finished with value: 0.569766081871345 and parameters: {'max_depth': 6, 'learning_rate': 0.04293528969371386, 'n_estimators': 791, 'subsample': 0.6267584657883839, 'colsample_bytree': 0.6371113358369419, 'min_child_weight': 1, 'gamma': 2.5571498667567867, 'reg_alpha': 0.0004313946128402451, 'reg_lambda': 1.2838424852876475e-06, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  68%|██████▊   | 137/200 [01:34<00:44,  1.41it/s]

[I 2025-11-10 18:45:46,166] Trial 135 finished with value: 0.5949707602339182 and parameters: {'max_depth': 6, 'learning_rate': 0.04252282012399256, 'n_estimators': 859, 'subsample': 0.6518003136344873, 'colsample_bytree': 0.6191949087188541, 'min_child_weight': 1, 'gamma': 2.5101414728365814, 'reg_alpha': 0.0016271423865133372, 'reg_lambda': 2.1545358537368143e-06, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  69%|██████▉   | 138/200 [01:36<01:02,  1.00s/it]

[I 2025-11-10 18:45:48,141] Trial 137 finished with value: 0.5785380116959064 and parameters: {'max_depth': 7, 'learning_rate': 0.04160375888039584, 'n_estimators': 363, 'subsample': 0.6315689537547128, 'colsample_bytree': 0.6185676752606665, 'min_child_weight': 1, 'gamma': 3.292683418146717, 'reg_alpha': 0.00043571238146307125, 'reg_lambda': 2.6374785246679793e-06, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  70%|██████▉   | 139/200 [01:36<00:53,  1.14it/s]

[I 2025-11-10 18:45:48,628] Trial 139 finished with value: 0.5771734892787523 and parameters: {'max_depth': 8, 'learning_rate': 0.05189185900691096, 'n_estimators': 483, 'subsample': 0.5532549771826032, 'colsample_bytree': 0.6200971933527404, 'min_child_weight': 1, 'gamma': 2.8510287531435106, 'reg_alpha': 0.002043720124966457, 'reg_lambda': 1.1351266649517547e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  70%|███████   | 140/200 [01:37<00:45,  1.31it/s]

[I 2025-11-10 18:45:49,081] Trial 138 finished with value: 0.5832163742690059 and parameters: {'max_depth': 8, 'learning_rate': 0.02900512311614032, 'n_estimators': 484, 'subsample': 0.629888067090838, 'colsample_bytree': 0.6186235010326436, 'min_child_weight': 1, 'gamma': 2.8432808226275887, 'reg_alpha': 9.138521602932001e-05, 'reg_lambda': 1.47017908853459e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  71%|███████   | 142/200 [01:38<00:35,  1.64it/s]

[I 2025-11-10 18:45:49,902] Trial 141 finished with value: 0.6085380116959065 and parameters: {'max_depth': 6, 'learning_rate': 0.06314596831206236, 'n_estimators': 230, 'subsample': 0.6528087622084259, 'colsample_bytree': 0.5949433568126073, 'min_child_weight': 1, 'gamma': 2.0208303581651093, 'reg_alpha': 0.0019093433322938372, 'reg_lambda': 5.686750388756781e-06, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.
[I 2025-11-10 18:45:50,070] Trial 143 pruned.

Best trial: 84. Best value: 0.650877:  72%|███████▏  | 143/200 [01:38<00:31,  1.81it/s]

[I 2025-11-10 18:45:50,488] Trial 145 pruned.

Best trial: 84. Best value: 0.650877:  72%|███████▏  | 144/200 [01:39<00:43,  1.28it/s]

[I 2025-11-10 18:45:51,831] Trial 144 finished with value: 0.5868031189083821 and parameters: {'max_depth': 6, 'learning_rate': 0.0698509471211411, 'n_estimators': 271, 'subsample': 0.696186742786683, 'colsample_bytree': 0.594127464306223, 'min_child_weight': 1, 'gamma': 1.9689692954581155, 'reg_alpha': 0.005337129755322822, 'reg_lambda': 5.0114413087571995e-06, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  73%|███████▎  | 146/200 [01:40<00:26,  2.01it/s]

[I 2025-11-10 18:45:52,155] Trial 140 finished with value: 0.6110136452241715 and parameters: {'max_depth': 6, 'learning_rate': 0.050986221881675564, 'n_estimators': 1084, 'subsample': 0.6469140584444261, 'colsample_bytree': 0.6184472577233098, 'min_child_weight': 1, 'gamma': 1.9976701993014885, 'reg_alpha': 0.00028643690950389965, 'reg_lambda': 3.5735022867650658e-06, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.
[I 2025-11-10 18:45:52,292] Trial 147 pruned.

Best trial: 84. Best value: 0.650877:  74%|███████▎  | 147/200 [01:41<00:35,  1.50it/s]

[I 2025-11-10 18:45:53,365] Trial 148 pruned.

Best trial: 84. Best value: 0.650877:  74%|███████▍  | 148/200 [01:42<00:45,  1.15it/s]

[I 2025-11-10 18:45:54,717] Trial 150 pruned.

Best trial: 84. Best value: 0.650877:  74%|███████▍  | 149/200 [01:43<00:41,  1.23it/s]

[I 2025-11-10 18:45:55,400] Trial 146 finished with value: 0.6101364522417153 and parameters: {'max_depth': 6, 'learning_rate': 0.06291623832788087, 'n_estimators': 907, 'subsample': 0.6455047903263622, 'colsample_bytree': 0.5595663557134172, 'min_child_weight': 1, 'gamma': 1.7141159841622213, 'reg_alpha': 0.0017947318475594366, 'reg_lambda': 2.5342808664609405e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  75%|███████▌  | 150/200 [01:44<00:40,  1.24it/s]

[I 2025-11-10 18:45:56,179] Trial 152 pruned.

Best trial: 84. Best value: 0.650877:  76%|███████▌  | 151/200 [01:44<00:33,  1.45it/s]

[I 2025-11-10 18:45:56,606] Trial 142 finished with value: 0.5917543859649123 and parameters: {'max_depth': 6, 'learning_rate': 0.010616456532199925, 'n_estimators': 1027, 'subsample': 0.6485511917701002, 'colsample_bytree': 0.6024328092387363, 'min_child_weight': 1, 'gamma': 1.9844959610514266, 'reg_alpha': 0.00011607979362589522, 'reg_lambda': 5.469347193022929e-06, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  76%|███████▌  | 152/200 [01:46<00:47,  1.00it/s]

[I 2025-11-10 18:45:58,323] Trial 149 finished with value: 0.5719883040935672 and parameters: {'max_depth': 5, 'learning_rate': 0.03706792085428258, 'n_estimators': 1050, 'subsample': 0.6674293871358841, 'colsample_bytree': 0.6441742578561249, 'min_child_weight': 1, 'gamma': 0.3477979680842984, 'reg_alpha': 0.00029082124784620864, 'reg_lambda': 3.236040802945936e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  76%|███████▋  | 153/200 [01:48<00:57,  1.23s/it]

[I 2025-11-10 18:46:00,079] Trial 151 finished with value: 0.5733333333333334 and parameters: {'max_depth': 6, 'learning_rate': 0.039560851914032406, 'n_estimators': 924, 'subsample': 0.6685899284126773, 'colsample_bytree': 0.6106487496747736, 'min_child_weight': 1, 'gamma': 2.073615867036988, 'reg_alpha': 0.000679319950253193, 'reg_lambda': 3.959543336938877e-06, 'max_delta_step': 2}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  78%|███████▊  | 155/200 [01:49<00:40,  1.12it/s]

[I 2025-11-10 18:46:01,225] Trial 156 pruned.
[I 2025-11-10 18:46:01,391] Trial 153 finished with value: 0.5729824561403507 and parameters: {'max_depth': 5, 'learning_rate': 0.05705261824888452, 'n_estimators': 966, 'subsample': 0.6620480604121823, 'colsample_bytree': 0.5827412224223836, 'min_child_weight': 1, 'gamma': 2.4939028227738556, 'reg_alpha': 1.1103179709281317e-05, 'reg_lambda': 2.1476073904315253e-05, 'max_delta_step': 2}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  78%|███████▊  | 156/200 [01:50<00:35,  1.23it/s]

[I 2025-11-10 18:46:02,017] Trial 154 finished with value: 0.6033528265107213 and parameters: {'max_depth': 6, 'learning_rate': 0.055745928857912325, 'n_estimators': 971, 'subsample': 0.6619244279378417, 'colsample_bytree': 0.6082767266709354, 'min_child_weight': 1, 'gamma': 1.8949726591011475, 'reg_alpha': 0.009393380065004711, 'reg_lambda': 7.927520867146576e-06, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  78%|███████▊  | 157/200 [01:51<00:45,  1.05s/it]

[I 2025-11-10 18:46:03,622] Trial 155 finished with value: 0.6180311890838206 and parameters: {'max_depth': 6, 'learning_rate': 0.057604295972336225, 'n_estimators': 969, 'subsample': 0.6475319621332067, 'colsample_bytree': 0.612949584536468, 'min_child_weight': 1, 'gamma': 2.055339828533959, 'reg_alpha': 0.0008453333219015406, 'reg_lambda': 2.074106813734061e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  79%|███████▉  | 158/200 [01:52<00:41,  1.02it/s]

[I 2025-11-10 18:46:04,428] Trial 160 pruned.

Best trial: 84. Best value: 0.650877:  80%|███████▉  | 159/200 [01:53<00:45,  1.12s/it]

[I 2025-11-10 18:46:05,876] Trial 158 finished with value: 0.5977777777777777 and parameters: {'max_depth': 6, 'learning_rate': 0.07921755717180225, 'n_estimators': 871, 'subsample': 0.6447262160590723, 'colsample_bytree': 0.5996277901627449, 'min_child_weight': 1, 'gamma': 1.6035891833206641, 'reg_alpha': 0.0029082592998319018, 'reg_lambda': 1.9659777081121865e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  80%|████████  | 160/200 [01:54<00:40,  1.02s/it]

[I 2025-11-10 18:46:06,672] Trial 159 finished with value: 0.6123586744639375 and parameters: {'max_depth': 6, 'learning_rate': 0.07793788565723417, 'n_estimators': 880, 'subsample': 0.6444002240266116, 'colsample_bytree': 0.6041054365049336, 'min_child_weight': 1, 'gamma': 2.178235269770398, 'reg_alpha': 0.009074475193870888, 'reg_lambda': 1.6833154071860884e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  80%|████████  | 161/200 [01:56<00:43,  1.11s/it]

[I 2025-11-10 18:46:07,989] Trial 157 finished with value: 0.5833528265107212 and parameters: {'max_depth': 6, 'learning_rate': 0.024815717306175707, 'n_estimators': 1132, 'subsample': 0.651308397836016, 'colsample_bytree': 0.5984224311809198, 'min_child_weight': 1, 'gamma': 2.479777122570322, 'reg_alpha': 0.0033230791585721112, 'reg_lambda': 2.2589005029520298e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  81%|████████  | 162/200 [01:58<00:51,  1.37s/it]

[I 2025-11-10 18:46:09,961] Trial 161 finished with value: 0.6153411306042885 and parameters: {'max_depth': 6, 'learning_rate': 0.05292870848429985, 'n_estimators': 1022, 'subsample': 0.6478811500588617, 'colsample_bytree': 0.569977474895797, 'min_child_weight': 1, 'gamma': 2.3755866298822226, 'reg_alpha': 0.000956776378110433, 'reg_lambda': 6.204433696733879e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  82%|████████▏ | 163/200 [01:59<00:48,  1.30s/it]

[I 2025-11-10 18:46:11,103] Trial 162 finished with value: 0.58729044834308 and parameters: {'max_depth': 6, 'learning_rate': 0.05188549032004648, 'n_estimators': 882, 'subsample': 0.6837258442020483, 'colsample_bytree': 0.5660787465091762, 'min_child_weight': 1, 'gamma': 2.3448159146804692, 'reg_alpha': 0.00920439791490465, 'reg_lambda': 8.061784019777499e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  82%|████████▏ | 164/200 [01:59<00:40,  1.12s/it]

[I 2025-11-10 18:46:11,800] Trial 163 finished with value: 0.5883040935672514 and parameters: {'max_depth': 6, 'learning_rate': 0.05346167288298983, 'n_estimators': 883, 'subsample': 0.6376415309420196, 'colsample_bytree': 0.5685408409464098, 'min_child_weight': 1, 'gamma': 2.3794215169451505, 'reg_alpha': 0.011901052840932602, 'reg_lambda': 5.576430953507172e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  82%|████████▎ | 165/200 [02:01<00:40,  1.16s/it]

[I 2025-11-10 18:46:13,037] Trial 164 finished with value: 0.5937231968810915 and parameters: {'max_depth': 6, 'learning_rate': 0.05951140971257618, 'n_estimators': 865, 'subsample': 0.6360135315541094, 'colsample_bytree': 0.5669170623423, 'min_child_weight': 1, 'gamma': 2.173482577406937, 'reg_alpha': 0.007196201158357254, 'reg_lambda': 8.79684396494851e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  83%|████████▎ | 166/200 [02:03<00:47,  1.41s/it]

[I 2025-11-10 18:46:15,039] Trial 165 finished with value: 0.5884405458089669 and parameters: {'max_depth': 6, 'learning_rate': 0.05288820343694519, 'n_estimators': 863, 'subsample': 0.6380375735643246, 'colsample_bytree': 0.5707542302317261, 'min_child_weight': 1, 'gamma': 2.3663127969798503, 'reg_alpha': 0.034844031817933434, 'reg_lambda': 7.630469529742184e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  84%|████████▎ | 167/200 [02:03<00:41,  1.25s/it]

[I 2025-11-10 18:46:15,933] Trial 166 finished with value: 0.6079337231968811 and parameters: {'max_depth': 6, 'learning_rate': 0.057819888126580225, 'n_estimators': 856, 'subsample': 0.6393623570024344, 'colsample_bytree': 0.5776464556539161, 'min_child_weight': 1, 'gamma': 2.1870591845284997, 'reg_alpha': 0.04055357558582255, 'reg_lambda': 6.315304930784581e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  84%|████████▍ | 168/200 [02:04<00:30,  1.05it/s]

[I 2025-11-10 18:46:16,171] Trial 169 pruned.

Best trial: 84. Best value: 0.650877:  84%|████████▍ | 169/200 [02:04<00:23,  1.33it/s]

[I 2025-11-10 18:46:16,460] Trial 167 finished with value: 0.58729044834308 and parameters: {'max_depth': 6, 'learning_rate': 0.05725921860912609, 'n_estimators': 831, 'subsample': 0.6347072905040585, 'colsample_bytree': 0.5742710300679964, 'min_child_weight': 1, 'gamma': 1.5814202008602272, 'reg_alpha': 0.0498673420659375, 'reg_lambda': 1.237131086741364e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  85%|████████▌ | 170/200 [02:04<00:19,  1.50it/s]

[I 2025-11-10 18:46:16,928] Trial 171 pruned.

Best trial: 84. Best value: 0.650877:  86%|████████▌ | 171/200 [02:05<00:17,  1.65it/s]

[I 2025-11-10 18:46:17,399] Trial 172 pruned.

Best trial: 84. Best value: 0.650877:  86%|████████▌ | 172/200 [02:05<00:15,  1.77it/s]

[I 2025-11-10 18:46:17,865] Trial 173 pruned.

Best trial: 84. Best value: 0.650877:  86%|████████▋ | 173/200 [02:06<00:15,  1.71it/s]

[I 2025-11-10 18:46:18,487] Trial 168 finished with value: 0.5918908382066277 and parameters: {'max_depth': 6, 'learning_rate': 0.04539011555437676, 'n_estimators': 935, 'subsample': 0.6596300870155212, 'colsample_bytree': 0.5464194211934944, 'min_child_weight': 1, 'gamma': 1.5823554569735538, 'reg_alpha': 0.0012548228649773333, 'reg_lambda': 1.4412274312353904e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  87%|████████▋ | 174/200 [02:06<00:12,  2.13it/s]

[I 2025-11-10 18:46:18,698] Trial 174 pruned.

Best trial: 84. Best value: 0.650877:  88%|████████▊ | 175/200 [02:09<00:25,  1.01s/it]

[I 2025-11-10 18:46:20,976] Trial 170 finished with value: 0.5900194931773879 and parameters: {'max_depth': 6, 'learning_rate': 0.0745604892896839, 'n_estimators': 923, 'subsample': 0.6528501966211873, 'colsample_bytree': 0.5442974449265173, 'min_child_weight': 1, 'gamma': 2.056369017841338, 'reg_alpha': 0.047961175525023055, 'reg_lambda': 9.976928873993141e-06, 'max_delta_step': 2}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  88%|████████▊ | 176/200 [02:09<00:23,  1.01it/s]

[I 2025-11-10 18:46:21,898] Trial 178 pruned.

Best trial: 84. Best value: 0.650877:  88%|████████▊ | 177/200 [02:11<00:24,  1.07s/it]

[I 2025-11-10 18:46:23,163] Trial 177 finished with value: 0.5925925925925926 and parameters: {'max_depth': 6, 'learning_rate': 0.0830075101481792, 'n_estimators': 894, 'subsample': 0.6292070130984799, 'colsample_bytree': 0.5924278083557206, 'min_child_weight': 1, 'gamma': 2.0400478428733306, 'reg_alpha': 0.0022322381137650344, 'reg_lambda': 0.00019054503088498367, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  89%|████████▉ | 178/200 [02:11<00:18,  1.22it/s]

[I 2025-11-10 18:46:23,396] Trial 175 finished with value: 0.5588888888888889 and parameters: {'max_depth': 6, 'learning_rate': 0.045743560254756455, 'n_estimators': 1007, 'subsample': 0.6227553550629861, 'colsample_bytree': 0.6092155839198432, 'min_child_weight': 1, 'gamma': 2.043568875625412, 'reg_alpha': 0.0021263315885443803, 'reg_lambda': 7.007857510651433e-06, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  90%|████████▉ | 179/200 [02:11<00:15,  1.36it/s]

[I 2025-11-10 18:46:23,936] Trial 176 finished with value: 0.5670565302144249 and parameters: {'max_depth': 6, 'learning_rate': 0.0485738916560274, 'n_estimators': 1002, 'subsample': 0.6210417740876222, 'colsample_bytree': 0.6069653381072562, 'min_child_weight': 1, 'gamma': 2.198505329149642, 'reg_alpha': 0.001735607148625468, 'reg_lambda': 0.0001905813991195165, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  90%|█████████ | 180/200 [02:12<00:12,  1.58it/s]

[I 2025-11-10 18:46:24,336] Trial 180 pruned.

Best trial: 84. Best value: 0.650877:  90%|█████████ | 181/200 [02:12<00:10,  1.82it/s]

[I 2025-11-10 18:46:24,687] Trial 181 pruned.

Best trial: 84. Best value: 0.650877:  91%|█████████ | 182/200 [02:13<00:10,  1.65it/s]

[I 2025-11-10 18:46:25,419] Trial 182 pruned.

Best trial: 84. Best value: 0.650877:  92%|█████████▏| 183/200 [02:13<00:08,  1.93it/s]

[I 2025-11-10 18:46:25,736] Trial 183 pruned.

Best trial: 84. Best value: 0.650877:  92%|█████████▏| 184/200 [02:14<00:09,  1.65it/s]

[I 2025-11-10 18:46:26,544] Trial 179 finished with value: 0.5751072124756336 and parameters: {'max_depth': 6, 'learning_rate': 0.04972896613905803, 'n_estimators': 769, 'subsample': 0.6091560545971522, 'colsample_bytree': 0.6154515737188253, 'min_child_weight': 1, 'gamma': 2.6468511191912807, 'reg_alpha': 0.0007981576374297702, 'reg_lambda': 0.00016495475059735793, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  92%|█████████▎| 185/200 [02:17<00:18,  1.25s/it]

[I 2025-11-10 18:46:29,314] Trial 184 finished with value: 0.5896491228070175 and parameters: {'max_depth': 6, 'learning_rate': 0.059080062610866416, 'n_estimators': 850, 'subsample': 0.6069459736607313, 'colsample_bytree': 0.5844789497297782, 'min_child_weight': 1, 'gamma': 2.302224262348882, 'reg_alpha': 0.010137279653080238, 'reg_lambda': 9.334388905696793e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  93%|█████████▎| 186/200 [02:18<00:15,  1.10s/it]

[I 2025-11-10 18:46:30,044] Trial 186 finished with value: 0.6124951267056531 and parameters: {'max_depth': 6, 'learning_rate': 0.05998389551588184, 'n_estimators': 787, 'subsample': 0.6427532311586511, 'colsample_bytree': 0.5812848177840096, 'min_child_weight': 1, 'gamma': 2.2457552114626536, 'reg_alpha': 0.009803941319064738, 'reg_lambda': 7.602273548971545e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  94%|█████████▎| 187/200 [02:18<00:10,  1.22it/s]

[I 2025-11-10 18:46:30,225] Trial 185 finished with value: 0.5933528265107212 and parameters: {'max_depth': 6, 'learning_rate': 0.06342520261273714, 'n_estimators': 866, 'subsample': 0.6431827782586983, 'colsample_bytree': 0.5829712885982434, 'min_child_weight': 1, 'gamma': 2.2730840635589966, 'reg_alpha': 0.012116607497923461, 'reg_lambda': 3.3901845208794725e-06, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  94%|█████████▍| 188/200 [02:18<00:07,  1.57it/s]

[I 2025-11-10 18:46:30,434] Trial 188 pruned.

Best trial: 84. Best value: 0.650877:  94%|█████████▍| 189/200 [02:18<00:06,  1.76it/s]

[I 2025-11-10 18:46:30,836] Trial 190 pruned.

Best trial: 84. Best value: 0.650877:  95%|█████████▌| 190/200 [02:19<00:05,  1.76it/s]

[I 2025-11-10 18:46:31,410] Trial 187 finished with value: 0.5855945419103314 and parameters: {'max_depth': 6, 'learning_rate': 0.06090407578047575, 'n_estimators': 878, 'subsample': 0.638505994379387, 'colsample_bytree': 0.5794054454119731, 'min_child_weight': 1, 'gamma': 2.272824362712981, 'reg_alpha': 0.0034081690603178973, 'reg_lambda': 9.840795772365988e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  96%|█████████▌| 191/200 [02:20<00:06,  1.36it/s]

[I 2025-11-10 18:46:32,540] Trial 193 pruned.

Best trial: 84. Best value: 0.650877:  96%|█████████▌| 192/200 [02:20<00:04,  1.67it/s]

[I 2025-11-10 18:46:32,817] Trial 191 finished with value: 0.5768421052631579 and parameters: {'max_depth': 5, 'learning_rate': 0.270872071177094, 'n_estimators': 441, 'subsample': 0.6677889609037847, 'colsample_bytree': 0.6006922295207836, 'min_child_weight': 1, 'gamma': 1.944874630269382, 'reg_alpha': 0.0035474553450694107, 'reg_lambda': 2.328991519269146e-05, 'max_delta_step': 0}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  97%|█████████▋| 194/200 [02:23<00:04,  1.23it/s]

[I 2025-11-10 18:46:35,095] Trial 189 finished with value: 0.5950682261208576 and parameters: {'max_depth': 6, 'learning_rate': 0.06949947977125977, 'n_estimators': 901, 'subsample': 0.6661068727008403, 'colsample_bytree': 0.6002733053822121, 'min_child_weight': 1, 'gamma': 1.9424329678445786, 'reg_alpha': 0.006800132176083462, 'reg_lambda': 2.49147376152276e-05, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.
[I 2025-11-10 18:46:35,247] Trial 192 finished with value: 0.5676608187134503 and parameters: {'max_depth': 6, 'learning_rate': 0.24525299493616462, 'n_estimators': 906, 'subsample': 0.6449474012775127, 'colsample_bytree': 0.6194855603308829, 'min_child_weight': 1, 'gamma': 1.9107958001776113, 'reg_alpha': 6.824532061103917e-07, 'reg_lambda': 5.789321280558502e-05, 'max_delta_step': 0}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  98%|█████████▊| 195/200 [02:25<00:05,  1.13s/it]

[I 2025-11-10 18:46:37,112] Trial 194 finished with value: 0.6188109161793373 and parameters: {'max_depth': 6, 'learning_rate': 0.05783369217937953, 'n_estimators': 824, 'subsample': 0.6453580951498915, 'colsample_bytree': 0.5635947832025129, 'min_child_weight': 1, 'gamma': 2.4100013039885924, 'reg_alpha': 0.0034827695298180797, 'reg_lambda': 0.00042175040240556165, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  98%|█████████▊| 196/200 [02:25<00:03,  1.18it/s]

[I 2025-11-10 18:46:37,305] Trial 195 finished with value: 0.6065497076023393 and parameters: {'max_depth': 6, 'learning_rate': 0.057185884096744716, 'n_estimators': 822, 'subsample': 0.6454983351208146, 'colsample_bytree': 0.5588580351782514, 'min_child_weight': 1, 'gamma': 2.1678617154878888, 'reg_alpha': 0.007863959756923613, 'reg_lambda': 5.905891718095693e-06, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877:  98%|█████████▊| 197/200 [02:26<00:02,  1.18it/s]

[I 2025-11-10 18:46:38,153] Trial 199 pruned.

Best trial: 84. Best value: 0.650877:  99%|█████████▉| 198/200 [02:27<00:01,  1.02it/s]

[I 2025-11-10 18:46:39,450] Trial 197 finished with value: 0.6337426900584796 and parameters: {'max_depth': 6, 'learning_rate': 0.07169086446303147, 'n_estimators': 815, 'subsample': 0.6542901042594014, 'colsample_bytree': 0.616956556797527, 'min_child_weight': 1, 'gamma': 1.7872238496353767, 'reg_alpha': 0.0048431867323183095, 'reg_lambda': 6.179755882780798e-06, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877: 100%|█████████▉| 199/200 [02:28<00:00,  1.16it/s]

[I 2025-11-10 18:46:40,031] Trial 196 finished with value: 0.613625730994152 and parameters: {'max_depth': 6, 'learning_rate': 0.07017635274867108, 'n_estimators': 1027, 'subsample': 0.6531757391996823, 'colsample_bytree': 0.6259349203024498, 'min_child_weight': 1, 'gamma': 1.7831676906053708, 'reg_alpha': 5.959101231268718e-07, 'reg_lambda': 5.6288466483324384e-06, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

Best trial: 84. Best value: 0.650877: 100%|██████████| 200/200 [02:28<00:00,  1.35it/s]

[I 2025-11-10 18:46:40,366] Trial 198 finished with value: 0.5937426900584796 and parameters: {'max_depth': 6, 'learning_rate': 0.0688866776381019, 'n_estimators': 736, 'subsample': 0.6564858529656478, 'colsample_bytree': 0.5893588062664743, 'min_child_weight': 1, 'gamma': 1.7738183503319396, 'reg_alpha': 0.004720670461422535, 'reg_lambda': 5.334973189589298e-06, 'max_delta_step': 1}. Best is trial 84 with value: 0.650877192982456.

[I 2025-11-10 18:46:41,406] A new study created in memory with name: 3_5_roc_auc
Best trial: 1. Best value: 0.5:   0%|          | 1/200 [00:02<09:29,  2.86s/it]

[I 2025-11-10 18:46:44,260] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.15464362719140895, 'n_estimators': 713, 'subsample': 0.9594779750491454, 'colsample_bytree': 0.6399013349187295, 'min_child_weight': 9, 'gamma': 3.179722958394951, 'reg_alpha': 0.0003701673244196755, 'reg_lambda': 0.00021156181813142315, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   1%|          | 2/200 [00:03<04:23,  1.33s/it]

[I 2025-11-10 18:46:44,523] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.04143939509933001, 'n_estimators': 785, 'subsample': 0.6868290746258585, 'colsample_bytree': 0.6408060604642908, 'min_child_weight': 6, 'gamma': 1.3056417137906, 'reg_alpha': 0.005740272502040834, 'reg_lambda': 0.010319267562965296, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 3. Best value: 0.506296:   2%|▏         | 3/200 [00:04<03:41,  1.13s/it]

[I 2025-11-10 18:46:45,405] Trial 3 finished with value: 0.5062962962962962 and parameters: {'max_depth': 4, 'learning_rate': 0.29703021641824046, 'n_estimators': 892, 'subsample': 0.5387429558410806, 'colsample_bytree': 0.7252198190932835, 'min_child_weight': 2, 'gamma': 4.330723268114393, 'reg_alpha': 0.4023635190056967, 'reg_lambda': 0.34795465695991823, 'max_delta_step': 6}. Best is trial 3 with value: 0.5062962962962962.

Best trial: 3. Best value: 0.506296:   2%|▏         | 4/200 [00:04<02:38,  1.24it/s]

[I 2025-11-10 18:46:45,727] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1094928333880308, 'n_estimators': 284, 'subsample': 0.5464336830839114, 'colsample_bytree': 0.8425244836091899, 'min_child_weight': 7, 'gamma': 2.9053680012203262, 'reg_alpha': 3.489015380590807e-05, 'reg_lambda': 0.04754858544513132, 'max_delta_step': 9}. Best is trial 3 with value: 0.5062962962962962.

Best trial: 3. Best value: 0.506296:   2%|▎         | 5/200 [00:04<02:21,  1.38it/s]

[I 2025-11-10 18:46:46,306] Trial 2 finished with value: 0.46423976608187134 and parameters: {'max_depth': 6, 'learning_rate': 0.047784780713715044, 'n_estimators': 1275, 'subsample': 0.9605067203634066, 'colsample_bytree': 0.5322882790880041, 'min_child_weight': 5, 'gamma': 3.396714434717272, 'reg_alpha': 0.00444619463097449, 'reg_lambda': 1.2934869106050852e-08, 'max_delta_step': 6}. Best is trial 3 with value: 0.5062962962962962.

Best trial: 4. Best value: 0.54616:   3%|▎         | 6/200 [00:05<02:33,  1.27it/s]

[I 2025-11-10 18:46:47,222] Trial 4 finished with value: 0.546159844054581 and parameters: {'max_depth': 4, 'learning_rate': 0.2939256885688973, 'n_estimators': 501, 'subsample': 0.7809270219154848, 'colsample_bytree': 0.6751924944798386, 'min_child_weight': 1, 'gamma': 1.2544593050491932, 'reg_alpha': 4.856035459703757, 'reg_lambda': 0.002893994493005315, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:   4%|▎         | 7/200 [00:06<02:16,  1.41it/s]

[I 2025-11-10 18:46:47,758] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.026092645491320877, 'n_estimators': 308, 'subsample': 0.7872009758511791, 'colsample_bytree': 0.8629584913002566, 'min_child_weight': 5, 'gamma': 4.6075929665327084, 'reg_alpha': 2.423584272539563e-06, 'reg_lambda': 5.556495730059133, 'max_delta_step': 5}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:   4%|▍         | 9/200 [00:07<01:51,  1.71it/s]

[I 2025-11-10 18:46:48,756] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.030070656424249085, 'n_estimators': 850, 'subsample': 0.9279428790219297, 'colsample_bytree': 0.5653476370509389, 'min_child_weight': 9, 'gamma': 3.242915046551979, 'reg_alpha': 0.00023666360087911209, 'reg_lambda': 3.6355214835401146e-08, 'max_delta_step': 0}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:46:48,872] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.013669069755559194, 'n_estimators': 380, 'subsample': 0.6003626759048322, 'colsample_bytree': 0.6360332989707407, 'min_child_weight': 6, 'gamma': 1.367452502022322, 'reg_alpha': 0.00017901872709119958, 'reg_lambda': 6.655120702613601, 'max_delta_step': 2}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:   5%|▌         | 10/200 [00:08<02:28,  1.28it/s]

[I 2025-11-10 18:46:50,100] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.09460922800157508, 'n_estimators': 538, 'subsample': 0.838495048361642, 'colsample_bytree': 0.7389294685257455, 'min_child_weight': 8, 'gamma': 2.8946379735921752, 'reg_alpha': 1.866983212094519e-05, 'reg_lambda': 0.11623440784889605, 'max_delta_step': 10}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:   6%|▌         | 11/200 [00:09<02:01,  1.56it/s]

[I 2025-11-10 18:46:50,419] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.086233736273061, 'n_estimators': 1187, 'subsample': 0.6300292832316416, 'colsample_bytree': 0.511174714809701, 'min_child_weight': 9, 'gamma': 2.5542445982755675, 'reg_alpha': 3.4308730109193844e-05, 'reg_lambda': 0.3454901163622133, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:   6%|▌         | 12/200 [00:09<01:43,  1.82it/s]

[I 2025-11-10 18:46:50,762] Trial 11 pruned.

Best trial: 4. Best value: 0.54616:   6%|▋         | 13/200 [00:09<01:41,  1.85it/s]

[I 2025-11-10 18:46:51,282] Trial 13 pruned.

Best trial: 4. Best value: 0.54616:   7%|▋         | 14/200 [00:10<01:32,  2.01it/s]

[I 2025-11-10 18:46:51,678] Trial 14 pruned.

Best trial: 4. Best value: 0.54616:   8%|▊         | 15/200 [00:12<03:02,  1.02it/s]

[I 2025-11-10 18:46:53,789] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.051128306587302066, 'n_estimators': 1296, 'subsample': 0.5239947644721272, 'colsample_bytree': 0.6869688543926311, 'min_child_weight': 4, 'gamma': 1.5776907073540525, 'reg_alpha': 0.003232841333090431, 'reg_lambda': 3.080655407735707e-05, 'max_delta_step': 6}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:   8%|▊         | 16/200 [00:14<03:58,  1.30s/it]

[I 2025-11-10 18:46:55,806] Trial 17 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1639285997220406, 'n_estimators': 993, 'subsample': 0.7329607924898104, 'colsample_bytree': 0.7497881386433096, 'min_child_weight': 3, 'gamma': 1.322325177711675, 'reg_alpha': 8.534261312626292, 'reg_lambda': 0.003331764235744069, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:   8%|▊         | 17/200 [00:14<03:01,  1.01it/s]

[I 2025-11-10 18:46:56,087] Trial 15 finished with value: 0.4844444444444445 and parameters: {'max_depth': 4, 'learning_rate': 0.2713781886138689, 'n_estimators': 1014, 'subsample': 0.5016202329275012, 'colsample_bytree': 0.7339804106878318, 'min_child_weight': 1, 'gamma': 0.016549835612311714, 'reg_alpha': 6.135245012024356, 'reg_lambda': 0.00035708927151798485, 'max_delta_step': 6}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:   9%|▉         | 18/200 [00:15<02:40,  1.13it/s]

[I 2025-11-10 18:46:56,715] Trial 20 pruned.
[I 2025-11-10 18:46:56,810] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.19383266909238978, 'n_estimators': 1046, 'subsample': 0.5277951306121235, 'colsample_bytree': 0.7455714211860378, 'min_child_weight': 1, 'gamma': 1.5615620608567617, 'reg_alpha': 9.962046300037747, 'reg_lambda': 0.0015474398023862547, 'max_delta_step': 6}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  10%|█         | 20/200 [00:16<01:54,  1.58it/s]

[I 2025-11-10 18:46:57,404] Trial 22 pruned.
[I 2025-11-10 18:46:57,412] Trial 19 pruned.

Best trial: 4. Best value: 0.54616:  11%|█         | 22/200 [00:16<01:15,  2.35it/s]

[I 2025-11-10 18:46:57,629] Trial 21 pruned.

Best trial: 4. Best value: 0.54616:  12%|█▏        | 23/200 [00:17<01:55,  1.53it/s]

[I 2025-11-10 18:46:59,091] Trial 18 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.15882493933316277, 'n_estimators': 988, 'subsample': 0.7322505242532824, 'colsample_bytree': 0.8355504405605959, 'min_child_weight': 2, 'gamma': 0.810319280835392, 'reg_alpha': 6.823881050405229, 'reg_lambda': 0.0046618405620313975, 'max_delta_step': 3}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  12%|█▏        | 24/200 [00:18<02:18,  1.27it/s]

[I 2025-11-10 18:47:00,292] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03036767957470886, 'n_estimators': 704, 'subsample': 0.6557072003494573, 'colsample_bytree': 0.6011443235483842, 'min_child_weight': 7, 'gamma': 3.8081493063280214, 'reg_alpha': 0.0164551407502746, 'reg_lambda': 0.014355631180339584, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  12%|█▎        | 25/200 [00:19<02:02,  1.43it/s]

[I 2025-11-10 18:47:00,735] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03347710592838965, 'n_estimators': 813, 'subsample': 0.6641825191869373, 'colsample_bytree': 0.6153243598742244, 'min_child_weight': 7, 'gamma': 0.743354470075409, 'reg_alpha': 0.020035456762466392, 'reg_lambda': 0.006956374825733093, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  13%|█▎        | 26/200 [00:19<01:41,  1.71it/s]

[I 2025-11-10 18:47:01,007] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03344061896937093, 'n_estimators': 820, 'subsample': 0.6692314561196985, 'colsample_bytree': 0.6022803463744938, 'min_child_weight': 7, 'gamma': 0.7003448516728663, 'reg_alpha': 0.025305605535931197, 'reg_lambda': 0.012630453723233728, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  14%|█▎        | 27/200 [00:20<01:34,  1.83it/s]

[I 2025-11-10 18:47:01,448] Trial 29 pruned.

Best trial: 4. Best value: 0.54616:  14%|█▍        | 28/200 [00:21<01:54,  1.51it/s]

[I 2025-11-10 18:47:02,412] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.06942734969985317, 'n_estimators': 780, 'subsample': 0.6670966542209712, 'colsample_bytree': 0.6131444922643723, 'min_child_weight': 7, 'gamma': 4.9365098903708535, 'reg_alpha': 0.02178652903826201, 'reg_lambda': 0.019746198639433048, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  14%|█▍        | 29/200 [00:21<01:35,  1.80it/s]

[I 2025-11-10 18:47:02,703] Trial 28 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.0663964405405006, 'n_estimators': 426, 'subsample': 0.5760203294209826, 'colsample_bytree': 0.6852317716325532, 'min_child_weight': 6, 'gamma': 4.9288095960581275, 'reg_alpha': 1.5874429375532901, 'reg_lambda': 0.04527468694423259, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  15%|█▌        | 30/200 [00:22<01:56,  1.46it/s]

[I 2025-11-10 18:47:03,693] Trial 32 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.02143294741061526, 'n_estimators': 207, 'subsample': 0.7795490716780061, 'colsample_bytree': 0.6598208423698539, 'min_child_weight': 10, 'gamma': 1.0762015560320422, 'reg_alpha': 1.0035369265913725, 'reg_lambda': 0.0006089924434333854, 'max_delta_step': 10}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  16%|█▌        | 31/200 [00:22<01:30,  1.86it/s]

[I 2025-11-10 18:47:03,885] Trial 27 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06619331046797809, 'n_estimators': 822, 'subsample': 0.5818635847821217, 'colsample_bytree': 0.6796083807531657, 'min_child_weight': 6, 'gamma': 0.7476868053348718, 'reg_alpha': 0.028322220802548776, 'reg_lambda': 0.021047418161713096, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  16%|█▋        | 33/200 [00:23<01:14,  2.25it/s]

[I 2025-11-10 18:47:04,517] Trial 33 pruned.
[I 2025-11-10 18:47:04,674] Trial 30 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.02125576901821689, 'n_estimators': 712, 'subsample': 0.79064330720597, 'colsample_bytree': 0.6905864378704972, 'min_child_weight': 6, 'gamma': 4.828580649922625, 'reg_alpha': 0.9705981089612548, 'reg_lambda': 0.03655146207199842, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  17%|█▋        | 34/200 [00:24<02:14,  1.23it/s]

[I 2025-11-10 18:47:06,353] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.019835553026341924, 'n_estimators': 907, 'subsample': 0.7747065335136518, 'colsample_bytree': 0.6852647517904991, 'min_child_weight': 6, 'gamma': 2.4366774507039275, 'reg_alpha': 1.0406099502364408, 'reg_lambda': 0.0009127115206722771, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  18%|█▊        | 35/200 [00:25<02:01,  1.36it/s]

[I 2025-11-10 18:47:06,903] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.23792436472478248, 'n_estimators': 692, 'subsample': 0.9954238315844894, 'colsample_bytree': 0.7156910119769718, 'min_child_weight': 9, 'gamma': 3.715923706972627, 'reg_alpha': 0.0008885869056992386, 'reg_lambda': 7.110005191777996e-05, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  18%|█▊        | 36/200 [00:26<01:53,  1.45it/s]

[I 2025-11-10 18:47:07,487] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.21781584471402587, 'n_estimators': 658, 'subsample': 0.9596374920707583, 'colsample_bytree': 0.5778191439356315, 'min_child_weight': 10, 'gamma': 3.36845146852382, 'reg_alpha': 0.0032252988856425586, 'reg_lambda': 4.464178911590921e-05, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  18%|█▊        | 37/200 [00:26<01:31,  1.77it/s]

[I 2025-11-10 18:47:07,754] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2182267246963936, 'n_estimators': 719, 'subsample': 0.9518118189491294, 'colsample_bytree': 0.7134749189106955, 'min_child_weight': 10, 'gamma': 3.4227480781246955, 'reg_alpha': 0.0052108905548163735, 'reg_lambda': 6.613121436086265e-05, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  19%|█▉        | 38/200 [00:28<03:05,  1.14s/it]

[I 2025-11-10 18:47:10,259] Trial 37 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2136755272468944, 'n_estimators': 907, 'subsample': 0.9550062862666482, 'colsample_bytree': 0.567363387141991, 'min_child_weight': 9, 'gamma': 3.476051736943974, 'reg_alpha': 0.0017632852560531774, 'reg_lambda': 1.994127181823348e-05, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  20%|█▉        | 39/200 [00:29<02:39,  1.01it/s]

[I 2025-11-10 18:47:10,880] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04466384915000331, 'n_estimators': 941, 'subsample': 0.9549027719930014, 'colsample_bytree': 0.5590354667310033, 'min_child_weight': 10, 'gamma': 3.263087410804315, 'reg_alpha': 0.004637775748351078, 'reg_lambda': 7.440353004303688e-06, 'max_delta_step': 5}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  20%|██        | 40/200 [00:29<02:08,  1.24it/s]

[I 2025-11-10 18:47:11,256] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.12988904849079314, 'n_estimators': 878, 'subsample': 0.700138709027714, 'colsample_bytree': 0.6490497802572862, 'min_child_weight': 8, 'gamma': 2.926832190176733, 'reg_alpha': 9.482315686191774e-05, 'reg_lambda': 1.2796624636331417e-05, 'max_delta_step': 5}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  20%|██        | 41/200 [00:30<01:49,  1.45it/s]

[I 2025-11-10 18:47:11,675] Trial 40 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04170325746674792, 'n_estimators': 934, 'subsample': 0.6953847121849571, 'colsample_bytree': 0.5592641670947625, 'min_child_weight': 8, 'gamma': 2.858338330285579, 'reg_alpha': 5.254038690303447e-06, 'reg_lambda': 6.511617700646338e-06, 'max_delta_step': 5}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  21%|██        | 42/200 [00:31<01:52,  1.40it/s]

[I 2025-11-10 18:47:12,449] Trial 41 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04154971534607039, 'n_estimators': 497, 'subsample': 0.7003296613492302, 'colsample_bytree': 0.6552136866974059, 'min_child_weight': 8, 'gamma': 3.055378899596748, 'reg_alpha': 4.288335866480009e-06, 'reg_lambda': 1.0826729424899948, 'max_delta_step': 5}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  22%|██▏       | 44/200 [00:31<01:18,  1.98it/s]

[I 2025-11-10 18:47:13,004] Trial 42 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.13359799638013206, 'n_estimators': 472, 'subsample': 0.6267967441539879, 'colsample_bytree': 0.6477289103591896, 'min_child_weight': 8, 'gamma': 2.877370594593411, 'reg_alpha': 9.449956452468621e-05, 'reg_lambda': 0.09367076683622202, 'max_delta_step': 10}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:47:13,134] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.09733758275015619, 'n_estimators': 301, 'subsample': 0.6216333890776861, 'colsample_bytree': 0.7805067922616006, 'min_child_weight': 5, 'gamma': 4.290440222295472, 'reg_alpha': 3.972539025379814e-07, 'reg_lambda': 0.12781228618977197, 'max_delta_step': 10}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  22%|██▎       | 45/200 [00:31<01:02,  2.46it/s]

[I 2025-11-10 18:47:13,305] Trial 43 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04344994989307846, 'n_estimators': 474, 'subsample': 0.6310473925155413, 'colsample_bytree': 0.5177663675969009, 'min_child_weight': 5, 'gamma': 4.426389621590464, 'reg_alpha': 0.06567120637777667, 'reg_lambda': 0.5391709836669468, 'max_delta_step': 0}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  23%|██▎       | 46/200 [00:32<01:06,  2.31it/s]

[I 2025-11-10 18:47:13,807] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08937063395686995, 'n_estimators': 274, 'subsample': 0.5578091017253249, 'colsample_bytree': 0.5126392150945238, 'min_child_weight': 5, 'gamma': 4.311222260250699, 'reg_alpha': 7.13036937661283e-07, 'reg_lambda': 0.14912381802331207, 'max_delta_step': 10}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  24%|██▎       | 47/200 [00:33<01:27,  1.75it/s]

[I 2025-11-10 18:47:14,699] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.09222105771595195, 'n_estimators': 337, 'subsample': 0.549735137198677, 'colsample_bytree': 0.7825315118231372, 'min_child_weight': 5, 'gamma': 4.449211370357631, 'reg_alpha': 2.747205499120219e-07, 'reg_lambda': 0.20757431861826542, 'max_delta_step': 0}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  24%|██▍       | 48/200 [00:33<01:11,  2.12it/s]

[I 2025-11-10 18:47:14,936] Trial 47 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08397584428347846, 'n_estimators': 359, 'subsample': 0.5621370831106514, 'colsample_bytree': 0.882581244382794, 'min_child_weight': 5, 'gamma': 2.5668356003681088, 'reg_alpha': 0.000297090618732183, 'reg_lambda': 0.46219379863486665, 'max_delta_step': 0}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:47:15,032] Trial 48 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08608338771991174, 'n_estimators': 338, 'subsample': 0.5468619153132671, 'colsample_bytree': 0.8739327295689174, 'min_child_weight': 4, 'gamma': 0.35044390930247094, 'reg_alpha': 0.00025470048638472276, 'reg_lambda': 5.870959960383566, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  25%|██▌       | 50/200 [00:33<00:46,  3.26it/s]

[I 2025-11-10 18:47:15,167] Trial 50 pruned.

Best trial: 4. Best value: 0.54616:  26%|██▌       | 51/200 [00:34<00:50,  2.94it/s]

[I 2025-11-10 18:47:15,607] Trial 49 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.29529336954974744, 'n_estimators': 391, 'subsample': 0.5335610560896711, 'colsample_bytree': 0.6298026066248531, 'min_child_weight': 4, 'gamma': 0.42251914167513427, 'reg_alpha': 2.808517497292856e-05, 'reg_lambda': 2.7685910857379565, 'max_delta_step': 6}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  26%|██▌       | 52/200 [00:34<01:04,  2.29it/s]

[I 2025-11-10 18:47:16,318] Trial 52 pruned.

Best trial: 4. Best value: 0.54616:  26%|██▋       | 53/200 [00:35<01:01,  2.38it/s]

[I 2025-11-10 18:47:16,691] Trial 53 pruned.

Best trial: 4. Best value: 0.54616:  27%|██▋       | 54/200 [00:37<02:13,  1.09it/s]

[I 2025-11-10 18:47:18,879] Trial 55 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.17752922139026056, 'n_estimators': 595, 'subsample': 0.9263293610137528, 'colsample_bytree': 0.5982561000748693, 'min_child_weight': 9, 'gamma': 2.615491671698915, 'reg_alpha': 9.428611675179493e-05, 'reg_lambda': 0.003145240368835988, 'max_delta_step': 1}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  28%|██▊       | 55/200 [00:38<02:06,  1.15it/s]

[I 2025-11-10 18:47:19,649] Trial 51 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.29761018343708073, 'n_estimators': 1099, 'subsample': 0.5372072214431406, 'colsample_bytree': 0.7182691628332057, 'min_child_weight': 9, 'gamma': 1.767190709479081, 'reg_alpha': 2.4049108334219453e-05, 'reg_lambda': 0.0015381741294967415, 'max_delta_step': 6}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  28%|██▊       | 56/200 [00:38<01:40,  1.43it/s]

[I 2025-11-10 18:47:19,928] Trial 56 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.025602569233656943, 'n_estimators': 766, 'subsample': 0.92396971805711, 'colsample_bytree': 0.5856904015006134, 'min_child_weight': 9, 'gamma': 2.6565607108276525, 'reg_alpha': 0.0004806885167370783, 'reg_lambda': 4.00049046105141e-08, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  28%|██▊       | 57/200 [00:38<01:22,  1.72it/s]

[I 2025-11-10 18:47:20,216] Trial 54 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.18726186693791874, 'n_estimators': 1107, 'subsample': 0.9977580926487495, 'colsample_bytree': 0.5899000749322125, 'min_child_weight': 9, 'gamma': 1.6835861357668347, 'reg_alpha': 7.997483726902888e-05, 'reg_lambda': 2.002755617894643e-08, 'max_delta_step': 1}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  29%|██▉       | 58/200 [00:39<01:18,  1.81it/s]

[I 2025-11-10 18:47:20,700] Trial 58 pruned.

Best trial: 4. Best value: 0.54616:  30%|██▉       | 59/200 [00:39<01:11,  1.96it/s]

[I 2025-11-10 18:47:21,107] Trial 60 pruned.

Best trial: 4. Best value: 0.54616:  30%|███       | 60/200 [00:40<01:37,  1.43it/s]

[I 2025-11-10 18:47:22,253] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.055429338577858214, 'n_estimators': 764, 'subsample': 0.996699598294591, 'colsample_bytree': 0.7638647571351347, 'min_child_weight': 7, 'gamma': 4.016916594117003, 'reg_alpha': 0.000503872890467892, 'reg_lambda': 3.806735057048336e-08, 'max_delta_step': 4}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  30%|███       | 61/200 [00:41<01:26,  1.61it/s]

[I 2025-11-10 18:47:22,687] Trial 59 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.055456679455434754, 'n_estimators': 636, 'subsample': 0.8927581266084837, 'colsample_bytree': 0.6286201606320486, 'min_child_weight': 7, 'gamma': 1.188141435611222, 'reg_alpha': 3.543075272803971, 'reg_lambda': 2.777141131982008e-07, 'max_delta_step': 4}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  31%|███       | 62/200 [00:41<01:12,  1.91it/s]

[I 2025-11-10 18:47:22,989] Trial 63 pruned.

Best trial: 4. Best value: 0.54616:  32%|███▏      | 64/200 [00:42<00:50,  2.67it/s]

[I 2025-11-10 18:47:23,368] Trial 61 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.25128533218211463, 'n_estimators': 620, 'subsample': 0.5057840396590898, 'colsample_bytree': 0.6214695266486231, 'min_child_weight': 7, 'gamma': 3.974826661631771, 'reg_alpha': 0.35666347778713203, 'reg_lambda': 0.0072295037798233335, 'max_delta_step': 4}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:47:23,493] Trial 62 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.2454316179479296, 'n_estimators': 531, 'subsample': 0.6072312207138558, 'colsample_bytree': 0.5443620970590852, 'min_child_weight': 7, 'gamma': 4.056314838605516, 'reg_alpha': 3.6289297938483136, 'reg_lambda': 0.059786179446572045, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  32%|███▎      | 65/200 [00:46<03:21,  1.49s/it]

[I 2025-11-10 18:47:27,608] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.14495364031574276, 'n_estimators': 1173, 'subsample': 0.606486548545876, 'colsample_bytree': 0.5274337059164437, 'min_child_weight': 6, 'gamma': 2.256013375897886, 'reg_alpha': 8.070166369170189e-06, 'reg_lambda': 0.007802305195122119, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  33%|███▎      | 66/200 [00:46<02:39,  1.19s/it]

[I 2025-11-10 18:47:28,094] Trial 65 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.14765597073855644, 'n_estimators': 1187, 'subsample': 0.9206407682426585, 'colsample_bytree': 0.5372872404876978, 'min_child_weight': 8, 'gamma': 2.343010338478913, 'reg_alpha': 8.901867049622424e-06, 'reg_lambda': 0.005392382717176689, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  34%|███▎      | 67/200 [00:47<02:25,  1.09s/it]

[I 2025-11-10 18:47:28,945] Trial 67 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.14533983223936056, 'n_estimators': 1278, 'subsample': 0.6426820210181302, 'colsample_bytree': 0.669261092304913, 'min_child_weight': 8, 'gamma': 3.1622407467348097, 'reg_alpha': 7.773540764234118e-06, 'reg_lambda': 0.34192596683301596, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:47:29,046] Trial 66 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.14007182843091795, 'n_estimators': 1364, 'subsample': 0.6136953188217221, 'colsample_bytree': 0.5388959872444194, 'min_child_weight': 8, 'gamma': 2.2577794154427835, 'reg_alpha': 0.080327181263989, 'reg_lambda': 0.3813431097208128, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  34%|███▍      | 69/200 [00:48<01:51,  1.17it/s]

[I 2025-11-10 18:47:30,093] Trial 69 pruned.

Best trial: 4. Best value: 0.54616:  35%|███▌      | 70/200 [00:49<01:43,  1.26it/s]

[I 2025-11-10 18:47:30,704] Trial 70 pruned.

Best trial: 4. Best value: 0.54616:  36%|███▌      | 71/200 [00:51<02:41,  1.26s/it]

[I 2025-11-10 18:47:33,273] Trial 68 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.10378729101609577, 'n_estimators': 1395, 'subsample': 0.6522926663029579, 'colsample_bytree': 0.5033179962835781, 'min_child_weight': 8, 'gamma': 3.24402873028761, 'reg_alpha': 0.09842080989878797, 'reg_lambda': 2.1149550925348223e-06, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  36%|███▌      | 72/200 [00:52<02:04,  1.03it/s]

[I 2025-11-10 18:47:33,481] Trial 71 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1035470425681293, 'n_estimators': 1018, 'subsample': 0.5191533016032306, 'colsample_bytree': 0.8357741703851611, 'min_child_weight': 10, 'gamma': 0.9404782401659009, 'reg_alpha': 0.00019239179260907742, 'reg_lambda': 2.2992049477521257e-06, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  36%|███▋      | 73/200 [00:53<02:04,  1.02it/s]

[I 2025-11-10 18:47:34,484] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.02767481658499299, 'n_estimators': 229, 'subsample': 0.7518479554913418, 'colsample_bytree': 0.9476523824312993, 'min_child_weight': 10, 'gamma': 4.61011504195837, 'reg_alpha': 1.8948089458739006e-06, 'reg_lambda': 1.734140571188098, 'max_delta_step': 2}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:47:34,573] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.02877164788777, 'n_estimators': 201, 'subsample': 0.767591241717602, 'colsample_bytree': 0.8551350772184231, 'min_child_weight': 9, 'gamma': 4.688235486686908, 'reg_alpha': 2.342703271362799e-06, 'reg_lambda': 2.8070645414454196, 'max_delta_step': 2}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  38%|███▊      | 75/200 [00:53<01:17,  1.61it/s]

[I 2025-11-10 18:47:34,828] Trial 72 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.028552440010221086, 'n_estimators': 1036, 'subsample': 0.9745588261825477, 'colsample_bytree': 0.6959891683538313, 'min_child_weight': 10, 'gamma': 1.9448281144256976, 'reg_alpha': 1.3247217016715822e-06, 'reg_lambda': 3.169245351282892, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  38%|███▊      | 76/200 [00:53<01:07,  1.85it/s]

[I 2025-11-10 18:47:35,120] Trial 73 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03823325269898388, 'n_estimators': 1031, 'subsample': 0.5186966717964034, 'colsample_bytree': 0.5054548390123839, 'min_child_weight': 10, 'gamma': 2.6952669159288964, 'reg_alpha': 0.0014118121369468943, 'reg_lambda': 2.2830422498878393, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  38%|███▊      | 77/200 [00:54<01:09,  1.76it/s]

[I 2025-11-10 18:47:35,764] Trial 76 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.016447309273708594, 'n_estimators': 251, 'subsample': 0.7179495943846882, 'colsample_bytree': 0.7988864196517674, 'min_child_weight': 9, 'gamma': 4.6224888351258, 'reg_alpha': 4.4722121003717134e-05, 'reg_lambda': 0.020054537642278946, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  39%|███▉      | 78/200 [00:55<01:22,  1.47it/s]

[I 2025-11-10 18:47:36,744] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.015531711643673887, 'n_estimators': 428, 'subsample': 0.7180912223806007, 'colsample_bytree': 0.7987629844976682, 'min_child_weight': 6, 'gamma': 2.7640225157658316, 'reg_alpha': 0.0013300610738574104, 'reg_lambda': 0.02872867853313666, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  40%|███▉      | 79/200 [00:56<01:32,  1.31it/s]

[I 2025-11-10 18:47:37,725] Trial 81 pruned.

Best trial: 4. Best value: 0.54616:  40%|████      | 80/200 [00:57<01:43,  1.16it/s]

[I 2025-11-10 18:47:38,835] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.017271512267811873, 'n_estimators': 968, 'subsample': 0.730082225345517, 'colsample_bytree': 0.8170490231800647, 'min_child_weight': 6, 'gamma': 2.802485967069538, 'reg_alpha': 6.587770395883907e-08, 'reg_lambda': 0.02198899139121459, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  40%|████      | 81/200 [00:57<01:26,  1.38it/s]

[I 2025-11-10 18:47:39,233] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.018004950896850228, 'n_estimators': 966, 'subsample': 0.7310478718493043, 'colsample_bytree': 0.6684721296806243, 'min_child_weight': 6, 'gamma': 3.823909710279962, 'reg_alpha': 1.0682414183164789e-08, 'reg_lambda': 0.028895333813864884, 'max_delta_step': 10}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  41%|████      | 82/200 [00:58<01:31,  1.29it/s]

[I 2025-11-10 18:47:40,131] Trial 80 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.023287491167244802, 'n_estimators': 980, 'subsample': 0.6790958977502689, 'colsample_bytree': 0.901946912056409, 'min_child_weight': 6, 'gamma': 3.561403918735577, 'reg_alpha': 0.6480215156042193, 'reg_lambda': 0.030068626460757555, 'max_delta_step': 10}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  42%|████▏     | 84/200 [00:59<01:04,  1.81it/s]

[I 2025-11-10 18:47:40,674] Trial 85 pruned.
[I 2025-11-10 18:47:40,855] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.013316003987171527, 'n_estimators': 305, 'subsample': 0.5884814166296041, 'colsample_bytree': 0.6068863942134054, 'min_child_weight': 2, 'gamma': 1.5300542569565845, 'reg_alpha': 8.601748424619373, 'reg_lambda': 9.596556143626286, 'max_delta_step': 1}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  42%|████▎     | 85/200 [01:01<01:52,  1.02it/s]

[I 2025-11-10 18:47:42,835] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07727643483429744, 'n_estimators': 866, 'subsample': 0.5774357127723706, 'colsample_bytree': 0.8897157985832059, 'min_child_weight': 9, 'gamma': 2.437372463358884, 'reg_alpha': 9.318876634405985, 'reg_lambda': 0.6210311032333123, 'max_delta_step': 1}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  43%|████▎     | 86/200 [01:03<02:14,  1.18s/it]

[I 2025-11-10 18:47:44,504] Trial 82 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07491814868892957, 'n_estimators': 1497, 'subsample': 0.586351613950611, 'colsample_bytree': 0.8979100099792336, 'min_child_weight': 6, 'gamma': 2.111768503606534, 'reg_alpha': 9.476137765851183, 'reg_lambda': 0.7427431906269023, 'max_delta_step': 1}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  44%|████▎     | 87/200 [01:04<02:30,  1.33s/it]

[I 2025-11-10 18:47:46,183] Trial 88 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.04903626209165037, 'n_estimators': 806, 'subsample': 0.8247262179381863, 'colsample_bytree': 0.571470660074387, 'min_child_weight': 5, 'gamma': 1.507068310090277, 'reg_alpha': 4.581266889083567e-05, 'reg_lambda': 5.829490176296127, 'max_delta_step': 3}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  44%|████▍     | 88/200 [01:05<02:14,  1.20s/it]

[I 2025-11-10 18:47:47,089] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01152992386976464, 'n_estimators': 1495, 'subsample': 0.5673109722198606, 'colsample_bytree': 0.6162180434059604, 'min_child_weight': 5, 'gamma': 4.829102681384168, 'reg_alpha': 0.0007131614823855691, 'reg_lambda': 5.080154050364412, 'max_delta_step': 3}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:47:47,134] Trial 87 finished with value: 0.5088888888888888 and parameters: {'max_depth': 10, 'learning_rate': 0.04871784787209712, 'n_estimators': 1496, 'subsample': 0.5758138557359156, 'colsample_bytree': 0.5699698188578483, 'min_child_weight': 4, 'gamma': 2.5074845704075472, 'reg_alpha': 0.000729735057904814, 'reg_lambda': 0.7963357093927304, 'max_delta_step': 2}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  45%|████▌     | 90/200 [01:06<01:41,  1.08it/s]

[I 2025-11-10 18:47:48,283] Trial 89 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.047065933069813444, 'n_estimators': 813, 'subsample': 0.8423889095614778, 'colsample_bytree': 0.865544941523682, 'min_child_weight': 5, 'gamma': 1.4080025551901394, 'reg_alpha': 3.953734883603273e-05, 'reg_lambda': 4.973297753136309, 'max_delta_step': 3}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  46%|████▌     | 91/200 [01:07<01:29,  1.22it/s]

[I 2025-11-10 18:47:48,780] Trial 90 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.12130107662925074, 'n_estimators': 552, 'subsample': 0.9400564741157719, 'colsample_bytree': 0.6946786914654044, 'min_child_weight': 7, 'gamma': 4.802491831990057, 'reg_alpha': 0.0008371632401142266, 'reg_lambda': 0.011223805243943457, 'max_delta_step': 5}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  46%|████▌     | 92/200 [01:07<01:12,  1.48it/s]

[I 2025-11-10 18:47:49,048] Trial 93 pruned.

Best trial: 4. Best value: 0.54616:  46%|████▋     | 93/200 [01:08<01:29,  1.19it/s]

[I 2025-11-10 18:47:50,333] Trial 92 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.03471470324019311, 'n_estimators': 727, 'subsample': 0.5481948485409442, 'colsample_bytree': 0.5526416226559732, 'min_child_weight': 4, 'gamma': 2.493412358105344, 'reg_alpha': 0.006920578412620797, 'reg_lambda': 0.2297424517506922, 'max_delta_step': 0}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  48%|████▊     | 95/200 [01:09<00:53,  1.96it/s]

[I 2025-11-10 18:47:50,531] Trial 95 pruned.
[I 2025-11-10 18:47:50,662] Trial 91 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.062301997869908275, 'n_estimators': 735, 'subsample': 0.8430321092163534, 'colsample_bytree': 0.8651783622934872, 'min_child_weight': 7, 'gamma': 4.154486929708293, 'reg_alpha': 0.00016092428533503864, 'reg_lambda': 0.20496795214241212, 'max_delta_step': 0}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  48%|████▊     | 96/200 [01:09<00:52,  1.97it/s]

[I 2025-11-10 18:47:51,160] Trial 97 pruned.

Best trial: 4. Best value: 0.54616:  48%|████▊     | 97/200 [01:10<00:52,  1.96it/s]

[I 2025-11-10 18:47:51,679] Trial 98 pruned.

Best trial: 4. Best value: 0.54616:  50%|████▉     | 99/200 [01:10<00:35,  2.87it/s]

[I 2025-11-10 18:47:51,961] Trial 96 pruned.
[I 2025-11-10 18:47:52,087] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03841337960793499, 'n_estimators': 723, 'subsample': 0.5458679701926636, 'colsample_bytree': 0.6411502702907207, 'min_child_weight': 4, 'gamma': 2.561023377233567, 'reg_alpha': 0.0001296238618066452, 'reg_lambda': 0.1538404304577502, 'max_delta_step': 2}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  50%|█████     | 100/200 [01:12<01:03,  1.57it/s]

[I 2025-11-10 18:47:53,407] Trial 101 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.2302902938680032, 'n_estimators': 320, 'subsample': 0.5951867749209787, 'colsample_bytree': 0.585462416860586, 'min_child_weight': 5, 'gamma': 3.0568267830331184, 'reg_alpha': 0.00011130018016902058, 'reg_lambda': 0.0036291277309906805, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  50%|█████     | 101/200 [01:12<01:05,  1.51it/s]

[I 2025-11-10 18:47:54,129] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.20096274358532973, 'n_estimators': 465, 'subsample': 0.6008633274194889, 'colsample_bytree': 0.5805073336355662, 'min_child_weight': 5, 'gamma': 3.0205080079734774, 'reg_alpha': 0.002476302818746078, 'reg_lambda': 0.0023561340250758587, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  51%|█████     | 102/200 [01:13<01:13,  1.33it/s]

[I 2025-11-10 18:47:55,093] Trial 99 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03846580875815433, 'n_estimators': 890, 'subsample': 0.5972756397339569, 'colsample_bytree': 0.5964188872719591, 'min_child_weight': 5, 'gamma': 3.0016503176381417, 'reg_alpha': 0.0003297418870903233, 'reg_lambda': 0.06961038066582438, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  52%|█████▏    | 103/200 [01:15<01:30,  1.07it/s]

[I 2025-11-10 18:47:56,454] Trial 104 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1603802647498514, 'n_estimators': 528, 'subsample': 0.8102026515894684, 'colsample_bytree': 0.7480380868116522, 'min_child_weight': 9, 'gamma': 2.71035864901818, 'reg_alpha': 3.119511692221867e-05, 'reg_lambda': 0.012458250048450343, 'max_delta_step': 10}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  52%|█████▏    | 104/200 [01:15<01:28,  1.09it/s]

[I 2025-11-10 18:47:57,339] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.08165143445572298, 'n_estimators': 497, 'subsample': 0.7626134196190945, 'colsample_bytree': 0.7033793229826076, 'min_child_weight': 8, 'gamma': 2.8993043108873455, 'reg_alpha': 1.4945152429165117e-05, 'reg_lambda': 0.3424097011710908, 'max_delta_step': 5}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  52%|█████▎    | 105/200 [01:16<01:13,  1.29it/s]

[I 2025-11-10 18:47:57,782] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.2605893739676728, 'n_estimators': 259, 'subsample': 0.5667333047598717, 'colsample_bytree': 0.7270936063992082, 'min_child_weight': 8, 'gamma': 2.90557120184096, 'reg_alpha': 7.50918189153791e-05, 'reg_lambda': 0.2917638393848218, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  53%|█████▎    | 106/200 [01:16<00:58,  1.61it/s]

[I 2025-11-10 18:47:58,041] Trial 100 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.04102453508509818, 'n_estimators': 1432, 'subsample': 0.6024385677427396, 'colsample_bytree': 0.6744592844275394, 'min_child_weight': 5, 'gamma': 2.9784698788472714, 'reg_alpha': 0.0005447619200296935, 'reg_lambda': 0.0025547648850942125, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:47:58,110] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03976814363847771, 'n_estimators': 1067, 'subsample': 0.5685588854538216, 'colsample_bytree': 0.6786905752940581, 'min_child_weight': 9, 'gamma': 1.0115637461417784, 'reg_alpha': 1.3085499253685452e-05, 'reg_lambda': 0.32767873311540174, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  54%|█████▍    | 108/200 [01:17<00:46,  1.99it/s]

[I 2025-11-10 18:47:58,769] Trial 107 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.2716696753944133, 'n_estimators': 270, 'subsample': 0.5635502545049585, 'colsample_bytree': 0.6238426002719221, 'min_child_weight': 8, 'gamma': 2.1300247821209775, 'reg_alpha': 6.63985755036942e-05, 'reg_lambda': 0.11495345810641927, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  55%|█████▍    | 109/200 [01:18<00:58,  1.56it/s]

[I 2025-11-10 18:47:59,837] Trial 109 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.09459849509441286, 'n_estimators': 365, 'subsample': 0.8833668450753901, 'colsample_bytree': 0.733125711561118, 'min_child_weight': 6, 'gamma': 1.849571753700611, 'reg_alpha': 1.166835922800362e-05, 'reg_lambda': 3.8048539462055753, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  55%|█████▌    | 110/200 [01:19<01:07,  1.33it/s]

[I 2025-11-10 18:48:00,893] Trial 108 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.044605774326751876, 'n_estimators': 672, 'subsample': 0.5312643475779842, 'colsample_bytree': 0.75698052265298, 'min_child_weight': 9, 'gamma': 3.4816507126017107, 'reg_alpha': 4.399769515867396e-06, 'reg_lambda': 0.10027731644510533, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  56%|█████▌    | 111/200 [01:19<00:56,  1.58it/s]

[I 2025-11-10 18:48:01,207] Trial 110 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.09183475867515288, 'n_estimators': 665, 'subsample': 0.5302699446336219, 'colsample_bytree': 0.7375658619172205, 'min_child_weight': 6, 'gamma': 4.457795179861919, 'reg_alpha': 0.19980540624025214, 'reg_lambda': 0.10775821334935351, 'max_delta_step': 10}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  56%|█████▌    | 112/200 [01:20<00:54,  1.62it/s]

[I 2025-11-10 18:48:01,791] Trial 112 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.17816240617578774, 'n_estimators': 409, 'subsample': 0.7935101870206537, 'colsample_bytree': 0.7617876025971227, 'min_child_weight': 7, 'gamma': 4.397790875176723, 'reg_alpha': 3.789772864280496e-06, 'reg_lambda': 0.5131887867103049, 'max_delta_step': 10}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  56%|█████▋    | 113/200 [01:20<00:44,  1.97it/s]

[I 2025-11-10 18:48:02,021] Trial 111 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.09403651837506964, 'n_estimators': 681, 'subsample': 0.7997594303165232, 'colsample_bytree': 0.7636867548494101, 'min_child_weight': 7, 'gamma': 3.1539412075267963, 'reg_alpha': 2.2063897386028028e-05, 'reg_lambda': 0.04446400141904939, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  57%|█████▊    | 115/200 [01:21<00:39,  2.13it/s]

[I 2025-11-10 18:48:02,829] Trial 113 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.07048000288044003, 'n_estimators': 411, 'subsample': 0.7887194709552842, 'colsample_bytree': 0.5642471093984167, 'min_child_weight': 7, 'gamma': 4.463479256697515, 'reg_alpha': 1.741695274935766, 'reg_lambda': 0.042294177206963456, 'max_delta_step': 10}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:48:02,992] Trial 115 pruned.

Best trial: 4. Best value: 0.54616:  58%|█████▊    | 116/200 [01:22<00:42,  1.98it/s]

[I 2025-11-10 18:48:03,589] Trial 116 pruned.

Best trial: 4. Best value: 0.54616:  58%|█████▊    | 117/200 [01:22<00:39,  2.13it/s]

[I 2025-11-10 18:48:03,977] Trial 118 pruned.

Best trial: 4. Best value: 0.54616:  59%|█████▉    | 118/200 [01:22<00:36,  2.28it/s]

[I 2025-11-10 18:48:04,341] Trial 117 pruned.

Best trial: 4. Best value: 0.54616:  60%|█████▉    | 119/200 [01:23<00:40,  2.01it/s]

[I 2025-11-10 18:48:04,974] Trial 119 pruned.

Best trial: 4. Best value: 0.54616:  60%|██████    | 120/200 [01:24<00:53,  1.50it/s]

[I 2025-11-10 18:48:06,043] Trial 121 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.019794525619804042, 'n_estimators': 352, 'subsample': 0.6845850627849097, 'colsample_bytree': 0.6880229992668901, 'min_child_weight': 9, 'gamma': 2.812250235988246, 'reg_alpha': 4.755081169657817, 'reg_lambda': 0.00011391451023104523, 'max_delta_step': 4}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  61%|██████    | 122/200 [01:25<00:36,  2.12it/s]

[I 2025-11-10 18:48:06,479] Trial 114 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.12590702890820724, 'n_estimators': 1174, 'subsample': 0.5200227232676818, 'colsample_bytree': 0.6559754815333573, 'min_child_weight': 7, 'gamma': 1.0903435232259182, 'reg_alpha': 0.0013139633791786236, 'reg_lambda': 0.5003219999657248, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:48:06,651] Trial 122 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.12847071632928947, 'n_estimators': 345, 'subsample': 0.7429653470789791, 'colsample_bytree': 0.6839762156672615, 'min_child_weight': 6, 'gamma': 1.619599484893828, 'reg_alpha': 5.231457728718777, 'reg_lambda': 0.0009008857243820099, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  62%|██████▏   | 123/200 [01:26<00:51,  1.50it/s]

[I 2025-11-10 18:48:07,768] Trial 124 pruned.

Best trial: 4. Best value: 0.54616:  62%|██████▏   | 124/200 [01:27<00:53,  1.43it/s]

[I 2025-11-10 18:48:08,549] Trial 123 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.0255796354956312, 'n_estimators': 581, 'subsample': 0.6562924695418602, 'colsample_bytree': 0.6104470020590841, 'min_child_weight': 6, 'gamma': 0.8835033008801246, 'reg_alpha': 0.000987865619758389, 'reg_lambda': 0.0011080989733268439, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  62%|██████▎   | 125/200 [01:27<00:45,  1.64it/s]

[I 2025-11-10 18:48:08,950] Trial 126 pruned.

Best trial: 4. Best value: 0.54616:  63%|██████▎   | 126/200 [01:27<00:39,  1.90it/s]

[I 2025-11-10 18:48:09,287] Trial 120 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.12666022657437048, 'n_estimators': 1185, 'subsample': 0.7767742346436559, 'colsample_bytree': 0.6850564794954048, 'min_child_weight': 9, 'gamma': 1.671876156491909, 'reg_alpha': 0.049033879207617634, 'reg_lambda': 1.0096570132309212e-05, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  64%|██████▎   | 127/200 [01:28<00:31,  2.30it/s]

[I 2025-11-10 18:48:09,501] Trial 127 pruned.

Best trial: 4. Best value: 0.54616:  64%|██████▍   | 128/200 [01:28<00:27,  2.66it/s]

[I 2025-11-10 18:48:09,739] Trial 128 pruned.

Best trial: 4. Best value: 0.54616:  64%|██████▍   | 129/200 [01:28<00:25,  2.80it/s]

[I 2025-11-10 18:48:10,055] Trial 131 pruned.

Best trial: 4. Best value: 0.54616:  65%|██████▌   | 130/200 [01:28<00:21,  3.19it/s]

[I 2025-11-10 18:48:10,267] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.11368789755309625, 'n_estimators': 784, 'subsample': 0.5118077152361739, 'colsample_bytree': 0.747297373934368, 'min_child_weight': 9, 'gamma': 1.425140909420108, 'reg_alpha': 2.704889302476147, 'reg_lambda': 0.00047519318431421125, 'max_delta_step': 6}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  66%|██████▌   | 132/200 [01:29<00:16,  4.22it/s]

[I 2025-11-10 18:48:10,496] Trial 129 pruned.
[I 2025-11-10 18:48:10,612] Trial 130 pruned.

Best trial: 4. Best value: 0.54616:  66%|██████▋   | 133/200 [01:29<00:25,  2.61it/s]

[I 2025-11-10 18:48:11,338] Trial 133 pruned.

Best trial: 4. Best value: 0.54616:  67%|██████▋   | 134/200 [01:32<01:14,  1.12s/it]

[I 2025-11-10 18:48:14,179] Trial 135 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1355956815391867, 'n_estimators': 864, 'subsample': 0.7592596411837443, 'colsample_bytree': 0.5147559496563021, 'min_child_weight': 4, 'gamma': 3.763981351494652, 'reg_alpha': 7.406185212055452, 'reg_lambda': 0.008422789632463292, 'max_delta_step': 5}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  68%|██████▊   | 135/200 [01:33<01:04,  1.00it/s]

[I 2025-11-10 18:48:14,897] Trial 132 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.16991842462637094, 'n_estimators': 1067, 'subsample': 0.5570723632204848, 'colsample_bytree': 0.9208495664296791, 'min_child_weight': 4, 'gamma': 3.790286259073369, 'reg_alpha': 5.454612939342496e-07, 'reg_lambda': 0.0005132642026863725, 'max_delta_step': 5}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  68%|██████▊   | 136/200 [01:33<00:49,  1.30it/s]

[I 2025-11-10 18:48:15,131] Trial 134 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.18069949657794598, 'n_estimators': 1001, 'subsample': 0.8094593578453178, 'colsample_bytree': 0.7718467354441464, 'min_child_weight': 4, 'gamma': 1.3476717115501216, 'reg_alpha': 6.24881818019402, 'reg_lambda': 0.008842665714964832, 'max_delta_step': 5}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:48:15,148] Trial 137 pruned.

Best trial: 4. Best value: 0.54616:  69%|██████▉   | 138/200 [01:34<00:38,  1.63it/s]

[I 2025-11-10 18:48:15,994] Trial 138 pruned.

Best trial: 4. Best value: 0.54616:  70%|██████▉   | 139/200 [01:34<00:31,  1.91it/s]

[I 2025-11-10 18:48:16,246] Trial 136 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.18637974110829056, 'n_estimators': 993, 'subsample': 0.761092822657266, 'colsample_bytree': 0.7066275872588887, 'min_child_weight': 3, 'gamma': 1.287144431725862, 'reg_alpha': 6.515860246519106, 'reg_lambda': 0.016097104015468586, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  70%|███████   | 140/200 [01:35<00:39,  1.50it/s]

[I 2025-11-10 18:48:17,312] Trial 140 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01423197832734361, 'n_estimators': 445, 'subsample': 0.501619388229687, 'colsample_bytree': 0.8359551742807668, 'min_child_weight': 8, 'gamma': 2.0515466854069917, 'reg_alpha': 3.75645698637114, 'reg_lambda': 0.01579820138386932, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  70%|███████   | 141/200 [01:36<00:44,  1.32it/s]

[I 2025-11-10 18:48:18,317] Trial 142 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.10020109147653362, 'n_estimators': 454, 'subsample': 0.6682491484126123, 'colsample_bytree': 0.7522132287229395, 'min_child_weight': 8, 'gamma': 0.8195514673927298, 'reg_alpha': 0.01569100226486937, 'reg_lambda': 4.6100702264636e-06, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  71%|███████   | 142/200 [01:37<00:37,  1.57it/s]

[I 2025-11-10 18:48:18,646] Trial 143 pruned.

Best trial: 4. Best value: 0.54616:  72%|███████▏  | 144/200 [01:38<00:30,  1.86it/s]

[I 2025-11-10 18:48:19,458] Trial 144 pruned.
[I 2025-11-10 18:48:19,628] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.05939715126880471, 'n_estimators': 824, 'subsample': 0.6784171587913115, 'colsample_bytree': 0.6346232128973457, 'min_child_weight': 8, 'gamma': 0.787396480326331, 'reg_alpha': 1.5995819916975218, 'reg_lambda': 2.1553835623943147, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  72%|███████▎  | 145/200 [01:38<00:28,  1.96it/s]

[I 2025-11-10 18:48:20,071] Trial 145 pruned.

Best trial: 4. Best value: 0.54616:  73%|███████▎  | 146/200 [01:38<00:23,  2.29it/s]

[I 2025-11-10 18:48:20,337] Trial 139 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.014375869660600338, 'n_estimators': 1133, 'subsample': 0.5401341862632519, 'colsample_bytree': 0.8458221200923718, 'min_child_weight': 8, 'gamma': 4.984250602106242, 'reg_alpha': 1.5315285583913296, 'reg_lambda': 7.607933198272995, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  74%|███████▎  | 147/200 [01:39<00:25,  2.06it/s]

[I 2025-11-10 18:48:20,934] Trial 147 pruned.
[I 2025-11-10 18:48:20,977] Trial 146 pruned.

Best trial: 4. Best value: 0.54616:  74%|███████▍  | 149/200 [01:42<00:42,  1.19it/s]

[I 2025-11-10 18:48:23,461] Trial 148 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.04460976053158551, 'n_estimators': 752, 'subsample': 0.6977878662484425, 'colsample_bytree': 0.8075343324921593, 'min_child_weight': 10, 'gamma': 2.195024920614019, 'reg_alpha': 9.886077031060923, 'reg_lambda': 0.006198453642764318, 'max_delta_step': 1}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  75%|███████▌  | 150/200 [01:43<00:43,  1.14it/s]

[I 2025-11-10 18:48:24,447] Trial 150 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.08498205077921812, 'n_estimators': 752, 'subsample': 0.6986225370281685, 'colsample_bytree': 0.8797910687802754, 'min_child_weight': 9, 'gamma': 1.0179183614078258, 'reg_alpha': 9.667987915889826, 'reg_lambda': 1.1414068720634933, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  76%|███████▌  | 151/200 [01:43<00:34,  1.41it/s]

[I 2025-11-10 18:48:24,673] Trial 149 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.16765897289931406, 'n_estimators': 939, 'subsample': 0.9432738158239989, 'colsample_bytree': 0.8149852386498541, 'min_child_weight': 10, 'gamma': 3.2346061308901333, 'reg_alpha': 3.6559445595157616, 'reg_lambda': 1.108460747634488, 'max_delta_step': 1}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  76%|███████▌  | 152/200 [01:43<00:28,  1.70it/s]

[I 2025-11-10 18:48:24,935] Trial 152 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.06795944307525902, 'n_estimators': 283, 'subsample': 0.876024816336659, 'colsample_bytree': 0.5331039746293255, 'min_child_weight': 9, 'gamma': 1.5437423835026245, 'reg_alpha': 0.5572029887773926, 'reg_lambda': 4.310026054790601, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  77%|███████▋  | 154/200 [01:45<00:29,  1.56it/s]

[I 2025-11-10 18:48:26,380] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.03257124768139965, 'n_estimators': 321, 'subsample': 0.6331036607031619, 'colsample_bytree': 0.575905733285694, 'min_child_weight': 6, 'gamma': 3.451943767487594, 'reg_alpha': 0.005313767657346445, 'reg_lambda': 0.02332223958607128, 'max_delta_step': 3}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:48:26,553] Trial 151 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.084974447738564, 'n_estimators': 1288, 'subsample': 0.7278000305883898, 'colsample_bytree': 0.5752339954861088, 'min_child_weight': 9, 'gamma': 4.569546051922207, 'reg_alpha': 3.8374268155289104, 'reg_lambda': 1.1494237246610233, 'max_delta_step': 6}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  78%|███████▊  | 155/200 [01:47<00:45,  1.02s/it]

[I 2025-11-10 18:48:28,515] Trial 153 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.06915398254028467, 'n_estimators': 889, 'subsample': 0.5794370300058326, 'colsample_bytree': 0.7906762088284675, 'min_child_weight': 6, 'gamma': 2.735010044174768, 'reg_alpha': 0.29873543738482367, 'reg_lambda': 3.493136327248385, 'max_delta_step': 4}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  78%|███████▊  | 157/200 [01:48<00:52,  1.22s/it]

[I 2025-11-10 18:48:30,229] Trial 156 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02463852957166382, 'n_estimators': 891, 'subsample': 0.8343938415559483, 'colsample_bytree': 0.5998042331721379, 'min_child_weight': 6, 'gamma': 3.879443726315155, 'reg_alpha': 0.002138780749668146, 'reg_lambda': 0.14282591247614312, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:48:30,246] Trial 154 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02512516278999353, 'n_estimators': 1298, 'subsample': 0.6301949257049982, 'colsample_bytree': 0.5917931767775362, 'min_child_weight': 6, 'gamma': 3.8897561191477252, 'reg_alpha': 0.024608309022469646, 'reg_lambda': 3.6256216920502222, 'max_delta_step': 6}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:48:30,254] Trial 157 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03671964897964752, 'n_estimators': 880, 'subsample': 0.6495464126727608, 'colsample_bytree': 0.5914316332802572, 'min_child_weight': 6, 'gamma': 4.07767102928934, 'reg_alpha': 0.009852746278518234, 'reg_lambda': 0.16423228606760568, 'max_delta_step': 4}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  80%|███████▉  | 159/200 [01:49<00:28,  1.46it/s]

[I 2025-11-10 18:48:30,979] Trial 159 pruned.

Best trial: 4. Best value: 0.54616:  80%|████████  | 160/200 [01:50<00:26,  1.50it/s]

[I 2025-11-10 18:48:31,582] Trial 158 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.026703222604002125, 'n_estimators': 643, 'subsample': 0.6483203902914745, 'colsample_bytree': 0.5539728784088181, 'min_child_weight': 7, 'gamma': 3.531968259050662, 'reg_alpha': 0.0031269935139376487, 'reg_lambda': 0.1512239991058473, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  80%|████████  | 161/200 [01:51<00:27,  1.41it/s]

[I 2025-11-10 18:48:32,440] Trial 163 pruned.

Best trial: 4. Best value: 0.54616:  81%|████████  | 162/200 [01:51<00:24,  1.53it/s]

[I 2025-11-10 18:48:32,923] Trial 160 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.0422826592187537, 'n_estimators': 546, 'subsample': 0.9603331593658516, 'colsample_bytree': 0.5476462564623664, 'min_child_weight': 7, 'gamma': 3.56151533022884, 'reg_alpha': 0.0034483652355340477, 'reg_lambda': 0.011958926015076615, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  82%|████████▏ | 163/200 [01:51<00:21,  1.73it/s]

[I 2025-11-10 18:48:33,293] Trial 161 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.029099629984728006, 'n_estimators': 611, 'subsample': 0.6606202763212962, 'colsample_bytree': 0.6701355141746046, 'min_child_weight': 7, 'gamma': 4.316236468651442, 'reg_alpha': 0.0007605949442325013, 'reg_lambda': 1.9042220889592865e-08, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  82%|████████▏ | 164/200 [01:53<00:31,  1.13it/s]

[I 2025-11-10 18:48:35,003] Trial 164 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03378587880923719, 'n_estimators': 554, 'subsample': 0.6637495628142625, 'colsample_bytree': 0.6148484047207339, 'min_child_weight': 7, 'gamma': 0.6470146007304904, 'reg_alpha': 0.006218455788916195, 'reg_lambda': 0.00396902276618145, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  82%|████████▎ | 165/200 [01:54<00:35,  1.01s/it]

[I 2025-11-10 18:48:36,314] Trial 165 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.033554885299247876, 'n_estimators': 809, 'subsample': 0.6576591650768244, 'colsample_bytree': 0.6226992634466111, 'min_child_weight': 7, 'gamma': 3.665191782558511, 'reg_alpha': 0.01310905568563586, 'reg_lambda': 0.005521339394260244, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  83%|████████▎ | 166/200 [01:55<00:32,  1.06it/s]

[I 2025-11-10 18:48:37,096] Trial 167 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.29591269853485913, 'n_estimators': 494, 'subsample': 0.5555277646242684, 'colsample_bytree': 0.6198676205587001, 'min_child_weight': 7, 'gamma': 0.39952083945296446, 'reg_alpha': 0.016142379213511235, 'reg_lambda': 0.0002758876486491591, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:48:37,278] Trial 162 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.020588826122900444, 'n_estimators': 1424, 'subsample': 0.7464323454867615, 'colsample_bytree': 0.6175060141291872, 'min_child_weight': 7, 'gamma': 3.6225438206932346, 'reg_alpha': 0.0033824140677871507, 'reg_lambda': 0.012592742162105966, 'max_delta_step': 10}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  84%|████████▍ | 168/200 [01:57<00:26,  1.19it/s]

[I 2025-11-10 18:48:38,400] Trial 169 pruned.

Best trial: 4. Best value: 0.54616:  84%|████████▍ | 169/200 [01:57<00:26,  1.15it/s]

[I 2025-11-10 18:48:39,349] Trial 166 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.034665616078119084, 'n_estimators': 1438, 'subsample': 0.5492646780740387, 'colsample_bytree': 0.6232619559810681, 'min_child_weight': 7, 'gamma': 4.708178168271361, 'reg_alpha': 0.006202589307579377, 'reg_lambda': 0.0043694082141884204, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  85%|████████▌ | 170/200 [01:58<00:21,  1.40it/s]

[I 2025-11-10 18:48:39,684] Trial 172 pruned.

Best trial: 4. Best value: 0.54616:  86%|████████▌ | 171/200 [01:59<00:24,  1.19it/s]

[I 2025-11-10 18:48:40,840] Trial 173 pruned.
[I 2025-11-10 18:48:40,857] Trial 170 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0369173426823871, 'n_estimators': 829, 'subsample': 0.7836346682181498, 'colsample_bytree': 0.6419025570474791, 'min_child_weight': 5, 'gamma': 0.9104941838893905, 'reg_alpha': 0.04035810617947832, 'reg_lambda': 4.542434206668951e-05, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  86%|████████▋ | 173/200 [02:01<00:23,  1.14it/s]

[I 2025-11-10 18:48:42,677] Trial 168 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.2923620900976255, 'n_estimators': 1439, 'subsample': 0.5546287431365288, 'colsample_bytree': 0.6352584208701791, 'min_child_weight': 7, 'gamma': 0.40332639189339403, 'reg_alpha': 0.04955033227264072, 'reg_lambda': 0.0036754465996672358, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  87%|████████▋ | 174/200 [02:02<00:23,  1.09it/s]

[I 2025-11-10 18:48:43,722] Trial 176 pruned.

Best trial: 4. Best value: 0.54616:  88%|████████▊ | 176/200 [02:03<00:15,  1.52it/s]

[I 2025-11-10 18:48:44,357] Trial 175 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.030682728442639248, 'n_estimators': 793, 'subsample': 0.7278986065184283, 'colsample_bytree': 0.6021241046627708, 'min_child_weight': 8, 'gamma': 1.1669492161246686, 'reg_alpha': 0.017919046079421967, 'reg_lambda': 0.0015118332520799034, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:48:44,511] Trial 174 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02745648654768623, 'n_estimators': 822, 'subsample': 0.6888313168560463, 'colsample_bytree': 0.6379719723881796, 'min_child_weight': 8, 'gamma': 0.4549008307634608, 'reg_alpha': 0.04270597722996301, 'reg_lambda': 0.008617176079104555, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  88%|████████▊ | 177/200 [02:03<00:13,  1.76it/s]

[I 2025-11-10 18:48:44,849] Trial 171 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.011601709259217115, 'n_estimators': 1472, 'subsample': 0.6114591816708341, 'colsample_bytree': 0.604341681106334, 'min_child_weight': 5, 'gamma': 0.47827240254290304, 'reg_alpha': 2.25593918778766e-06, 'reg_lambda': 0.001488045038470345, 'max_delta_step': 0}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  89%|████████▉ | 178/200 [02:04<00:13,  1.63it/s]

[I 2025-11-10 18:48:45,574] Trial 179 pruned.

Best trial: 4. Best value: 0.54616:  90%|████████▉ | 179/200 [02:04<00:11,  1.88it/s]

[I 2025-11-10 18:48:45,907] Trial 180 pruned.

Best trial: 4. Best value: 0.54616:  90%|█████████ | 180/200 [02:05<00:15,  1.32it/s]

[I 2025-11-10 18:48:47,200] Trial 181 pruned.

Best trial: 4. Best value: 0.54616:  90%|█████████ | 181/200 [02:06<00:15,  1.19it/s]

[I 2025-11-10 18:48:48,244] Trial 178 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07589302623791673, 'n_estimators': 862, 'subsample': 0.9768061074156681, 'colsample_bytree': 0.742906673472101, 'min_child_weight': 8, 'gamma': 0.17323517943106315, 'reg_alpha': 3.73503475939469e-05, 'reg_lambda': 1.7865191404617832e-05, 'max_delta_step': 6}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  91%|█████████ | 182/200 [02:07<00:11,  1.51it/s]

[I 2025-11-10 18:48:48,479] Trial 177 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07678569043755983, 'n_estimators': 1038, 'subsample': 0.7235537353025392, 'colsample_bytree': 0.7458241671838939, 'min_child_weight': 8, 'gamma': 1.1742045580930816, 'reg_alpha': 0.019333734681499952, 'reg_lambda': 0.0015649497930750383, 'max_delta_step': 6}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  92%|█████████▏| 183/200 [02:07<00:10,  1.64it/s]

[I 2025-11-10 18:48:48,961] Trial 182 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0785520096971995, 'n_estimators': 708, 'subsample': 0.9818027211238585, 'colsample_bytree': 0.5836877105751098, 'min_child_weight': 9, 'gamma': 0.7179817664733741, 'reg_alpha': 5.04590817152616, 'reg_lambda': 0.006454813242505102, 'max_delta_step': 2}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  92%|█████████▏| 184/200 [02:08<00:12,  1.24it/s]

[I 2025-11-10 18:48:50,235] Trial 185 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.0897596190769781, 'n_estimators': 384, 'subsample': 0.7043354059197272, 'colsample_bytree': 0.5804738412162759, 'min_child_weight': 7, 'gamma': 4.564309132675432, 'reg_alpha': 0.09745629048761208, 'reg_lambda': 0.0538309366400148, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  92%|█████████▎| 185/200 [02:10<00:13,  1.10it/s]

[I 2025-11-10 18:48:51,392] Trial 183 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.105891154035091, 'n_estimators': 961, 'subsample': 0.9835225195075683, 'colsample_bytree': 0.5006317797586237, 'min_child_weight': 9, 'gamma': 1.0265368335217147, 'reg_alpha': 0.00015853970124705277, 'reg_lambda': 0.05095551689833182, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:48:51,410] Trial 184 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.10910812225862525, 'n_estimators': 707, 'subsample': 0.6896188099148632, 'colsample_bytree': 0.5862421802164799, 'min_child_weight': 7, 'gamma': 4.79011371903573, 'reg_alpha': 0.024167066900352325, 'reg_lambda': 0.04947843806551788, 'max_delta_step': 9}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  94%|█████████▎| 187/200 [02:11<00:09,  1.37it/s]

[I 2025-11-10 18:48:52,420] Trial 186 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.11046976293435004, 'n_estimators': 770, 'subsample': 0.6898250206336896, 'colsample_bytree': 0.6150747002713892, 'min_child_weight': 7, 'gamma': 4.857684030380177, 'reg_alpha': 0.009286368597663299, 'reg_lambda': 0.025291104495945963, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  94%|█████████▍| 188/200 [02:12<00:10,  1.12it/s]

[I 2025-11-10 18:48:53,802] Trial 187 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.05415532391379979, 'n_estimators': 776, 'subsample': 0.6607587851126856, 'colsample_bytree': 0.6135918838351522, 'min_child_weight': 7, 'gamma': 4.918428323841574, 'reg_alpha': 0.010825131191539121, 'reg_lambda': 0.0065356902003837316, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  94%|█████████▍| 189/200 [02:13<00:10,  1.03it/s]

[I 2025-11-10 18:48:54,993] Trial 189 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.056064205018394, 'n_estimators': 784, 'subsample': 0.6639756635697862, 'colsample_bytree': 0.6139599032802552, 'min_child_weight': 6, 'gamma': 4.993020328973442, 'reg_alpha': 0.010590382486249265, 'reg_lambda': 0.0218502128332733, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:48:55,044] Trial 188 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.054950377778651714, 'n_estimators': 772, 'subsample': 0.6651910347441237, 'colsample_bytree': 0.7156813274673587, 'min_child_weight': 7, 'gamma': 4.771384349366325, 'reg_alpha': 0.02900649313258856, 'reg_lambda': 0.029703118156083952, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  96%|█████████▌| 191/200 [02:14<00:07,  1.26it/s]

[I 2025-11-10 18:48:56,122] Trial 190 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.056331032804194194, 'n_estimators': 795, 'subsample': 0.6683326257824189, 'colsample_bytree': 0.7165784944742962, 'min_child_weight': 6, 'gamma': 2.565288116535185, 'reg_alpha': 0.0010423970837862345, 'reg_lambda': 0.01692644826827807, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  96%|█████████▌| 192/200 [02:17<00:09,  1.18s/it]

[I 2025-11-10 18:48:58,561] Trial 192 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.22473095638296853, 'n_estimators': 800, 'subsample': 0.675838937196693, 'colsample_bytree': 0.6497284503233309, 'min_child_weight': 7, 'gamma': 1.5096000051410303, 'reg_alpha': 7.0766401488943895, 'reg_lambda': 0.018078395880530663, 'max_delta_step': 5}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:48:58,585] Trial 193 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09828008482480473, 'n_estimators': 806, 'subsample': 0.6761554043683202, 'colsample_bytree': 0.773370119662984, 'min_child_weight': 6, 'gamma': 1.2883717598611226, 'reg_alpha': 0.001146248100746361, 'reg_lambda': 0.0007839309271521048, 'max_delta_step': 5}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  98%|█████████▊| 195/200 [02:18<00:03,  1.30it/s]

[I 2025-11-10 18:48:59,761] Trial 191 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.06339770746823835, 'n_estimators': 1334, 'subsample': 0.671231529639603, 'colsample_bytree': 0.7149309079625125, 'min_child_weight': 6, 'gamma': 1.4400791197438696, 'reg_alpha': 7.051921858633035, 'reg_lambda': 0.017987121480656666, 'max_delta_step': 8}. Best is trial 4 with value: 0.546159844054581.
[I 2025-11-10 18:48:59,911] Trial 194 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09898815910748175, 'n_estimators': 841, 'subsample': 0.5814203144145373, 'colsample_bytree': 0.694774377230578, 'min_child_weight': 6, 'gamma': 0.7802822237482198, 'reg_alpha': 6.7839894428919205, 'reg_lambda': 0.016209719067415754, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  98%|█████████▊| 196/200 [02:18<00:02,  1.56it/s]

[I 2025-11-10 18:49:00,139] Trial 195 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.06443381519544783, 'n_estimators': 293, 'subsample': 0.5979695615207854, 'colsample_bytree': 0.680212973831238, 'min_child_weight': 6, 'gamma': 1.2896768693787108, 'reg_alpha': 0.07534903300070261, 'reg_lambda': 0.07626231358070339, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616:  98%|█████████▊| 197/200 [02:19<00:02,  1.45it/s]

[I 2025-11-10 18:49:00,978] Trial 199 pruned.

Best trial: 4. Best value: 0.54616:  99%|█████████▉| 198/200 [02:19<00:01,  1.72it/s]

[I 2025-11-10 18:49:01,259] Trial 198 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07207212184675844, 'n_estimators': 282, 'subsample': 0.5419923681693102, 'colsample_bytree': 0.6767643810606917, 'min_child_weight': 4, 'gamma': 0.5536327812454078, 'reg_alpha': 0.0002709683168607639, 'reg_lambda': 0.009911155273286284, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616: 100%|█████████▉| 199/200 [02:20<00:00,  1.65it/s]

[I 2025-11-10 18:49:01,934] Trial 196 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.06333946393431011, 'n_estimators': 834, 'subsample': 0.5954309341532058, 'colsample_bytree': 0.696213350400359, 'min_child_weight': 6, 'gamma': 0.7540593490389889, 'reg_alpha': 0.18960746636118284, 'reg_lambda': 1.080743684663878e-06, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

Best trial: 4. Best value: 0.54616: 100%|██████████| 200/200 [02:21<00:00,  1.42it/s]

[I 2025-11-10 18:49:02,631] Trial 197 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.06561256374116699, 'n_estimators': 832, 'subsample': 0.5839259410513195, 'colsample_bytree': 0.9678600772010815, 'min_child_weight': 6, 'gamma': 0.8572874910964131, 'reg_alpha': 0.0005771370339515013, 'reg_lambda': 0.003273851055812543, 'max_delta_step': 7}. Best is trial 4 with value: 0.546159844054581.

[I 2025-11-10 18:49:03,577] A new study created in memory with name: 9_1_roc_auc
Best trial: 2. Best value: 0.5:   0%|          | 1/200 [00:03<11:00,  3.32s/it]

[I 2025-11-10 18:49:06,894] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.08864081610432653, 'n_estimators': 526, 'subsample': 0.5401908844430201, 'colsample_bytree': 0.8376507845681752, 'min_child_weight': 9, 'gamma': 3.3652259618786746, 'reg_alpha': 1.7309257489292983e-06, 'reg_lambda': 3.7010904874870625e-06, 'max_delta_step': 6}. Best is trial 2 with value: 0.5.

Best trial: 1. Best value: 0.53984:   1%|          | 2/200 [00:07<12:43,  3.85s/it]

[I 2025-11-10 18:49:11,120] Trial 1 finished with value: 0.5398395721925133 and parameters: {'max_depth': 5, 'learning_rate': 0.274141871998465, 'n_estimators': 1169, 'subsample': 0.6434847511681604, 'colsample_bytree': 0.5212897343799929, 'min_child_weight': 5, 'gamma': 4.465359415518181, 'reg_alpha': 5.217709507128615e-05, 'reg_lambda': 3.3339050995147624e-08, 'max_delta_step': 8}. Best is trial 1 with value: 0.5398395721925133.

Best trial: 1. Best value: 0.53984:   2%|▏         | 3/200 [00:08<07:54,  2.41s/it]

[I 2025-11-10 18:49:11,810] Trial 0 finished with value: 0.536057295645531 and parameters: {'max_depth': 10, 'learning_rate': 0.270201744180079, 'n_estimators': 1475, 'subsample': 0.8650378453368415, 'colsample_bytree': 0.5602044977491397, 'min_child_weight': 9, 'gamma': 2.3655460295073882, 'reg_alpha': 2.0749244349030902e-08, 'reg_lambda': 7.15516149711727e-07, 'max_delta_step': 6}. Best is trial 1 with value: 0.5398395721925133.

Best trial: 1. Best value: 0.53984:   2%|▏         | 4/200 [00:11<09:31,  2.91s/it]

[I 2025-11-10 18:49:15,497] Trial 4 finished with value: 0.5177563025210083 and parameters: {'max_depth': 3, 'learning_rate': 0.04712502922445772, 'n_estimators': 1451, 'subsample': 0.935632129704014, 'colsample_bytree': 0.8168296482780124, 'min_child_weight': 10, 'gamma': 1.1257381540206683, 'reg_alpha': 0.0009045400541575828, 'reg_lambda': 0.8723748906135373, 'max_delta_step': 1}. Best is trial 1 with value: 0.5398395721925133.

Best trial: 5. Best value: 0.541196:   2%|▎         | 5/200 [00:13<07:31,  2.32s/it]

[I 2025-11-10 18:49:16,760] Trial 5 finished with value: 0.541196333078686 and parameters: {'max_depth': 10, 'learning_rate': 0.026475398151104917, 'n_estimators': 811, 'subsample': 0.9504854596051245, 'colsample_bytree': 0.8399581049522071, 'min_child_weight': 9, 'gamma': 3.5557290984214553, 'reg_alpha': 0.0017162049696874352, 'reg_lambda': 8.518609959233594e-08, 'max_delta_step': 6}. Best is trial 5 with value: 0.541196333078686.

Best trial: 3. Best value: 0.551881:   3%|▎         | 6/200 [00:16<08:07,  2.52s/it]

[I 2025-11-10 18:49:19,659] Trial 3 finished with value: 0.5518808250572956 and parameters: {'max_depth': 4, 'learning_rate': 0.06738551806465859, 'n_estimators': 1442, 'subsample': 0.6973579815337427, 'colsample_bytree': 0.7517340332737776, 'min_child_weight': 1, 'gamma': 3.5098227630507957, 'reg_alpha': 0.007404660423280432, 'reg_lambda': 2.038375480505351e-05, 'max_delta_step': 7}. Best is trial 3 with value: 0.5518808250572956.

Best trial: 3. Best value: 0.551881:   4%|▎         | 7/200 [00:18<07:39,  2.38s/it]

[I 2025-11-10 18:49:21,755] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.028641572940811315, 'n_estimators': 327, 'subsample': 0.5994568134034821, 'colsample_bytree': 0.6158020092553584, 'min_child_weight': 9, 'gamma': 2.4938374031360713, 'reg_alpha': 2.0334792499218714e-06, 'reg_lambda': 4.3492719307580564e-08, 'max_delta_step': 4}. Best is trial 3 with value: 0.5518808250572956.

Best trial: 3. Best value: 0.551881:   4%|▍         | 8/200 [00:19<06:19,  1.97s/it]

[I 2025-11-10 18:49:22,866] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.012945993977632702, 'n_estimators': 1287, 'subsample': 0.6839840337378638, 'colsample_bytree': 0.6131220223305927, 'min_child_weight': 9, 'gamma': 4.095545001005999, 'reg_alpha': 7.00549426617691e-05, 'reg_lambda': 0.10372295089265923, 'max_delta_step': 6}. Best is trial 3 with value: 0.5518808250572956.

Best trial: 3. Best value: 0.551881:   4%|▍         | 9/200 [00:20<05:56,  1.86s/it]

[I 2025-11-10 18:49:24,488] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.043292244455242955, 'n_estimators': 1304, 'subsample': 0.5506725455135518, 'colsample_bytree': 0.5543355282840451, 'min_child_weight': 10, 'gamma': 3.0983845736932514, 'reg_alpha': 1.760703216063873e-06, 'reg_lambda': 0.43069025143856693, 'max_delta_step': 1}. Best is trial 3 with value: 0.5518808250572956.

Best trial: 10. Best value: 0.551947:   5%|▌         | 10/200 [00:24<07:48,  2.46s/it]

[I 2025-11-10 18:49:28,295] Trial 10 finished with value: 0.5519465240641711 and parameters: {'max_depth': 6, 'learning_rate': 0.019355981490162266, 'n_estimators': 482, 'subsample': 0.9325203224976858, 'colsample_bytree': 0.617954800593618, 'min_child_weight': 6, 'gamma': 0.9687394782779607, 'reg_alpha': 1.8438920636444638e-07, 'reg_lambda': 1.3071108399742322e-05, 'max_delta_step': 4}. Best is trial 10 with value: 0.5519465240641711.

Best trial: 10. Best value: 0.551947:   6%|▌         | 11/200 [00:26<06:56,  2.20s/it]

[I 2025-11-10 18:49:29,905] Trial 12 finished with value: 0.5083109243697479 and parameters: {'max_depth': 10, 'learning_rate': 0.022739329204416407, 'n_estimators': 855, 'subsample': 0.6949730539223596, 'colsample_bytree': 0.7412479498753413, 'min_child_weight': 8, 'gamma': 3.220884794785293, 'reg_alpha': 0.0015314777558109764, 'reg_lambda': 0.22581820570050865, 'max_delta_step': 8}. Best is trial 10 with value: 0.5519465240641711.

Best trial: 10. Best value: 0.551947:   6%|▌         | 12/200 [00:26<05:12,  1.66s/it]

[I 2025-11-10 18:49:30,330] Trial 6 finished with value: 0.5452024446142093 and parameters: {'max_depth': 5, 'learning_rate': 0.014180063215018487, 'n_estimators': 1185, 'subsample': 0.733650890460906, 'colsample_bytree': 0.8275362744830959, 'min_child_weight': 4, 'gamma': 0.3334328773496459, 'reg_alpha': 1.9555343358231893e-06, 'reg_lambda': 7.207258037878741e-08, 'max_delta_step': 6}. Best is trial 10 with value: 0.5519465240641711.

Best trial: 10. Best value: 0.551947:   6%|▋         | 13/200 [00:31<07:57,  2.55s/it]

[I 2025-11-10 18:49:34,940] Trial 11 finished with value: 0.5425210084033614 and parameters: {'max_depth': 3, 'learning_rate': 0.04537438225622913, 'n_estimators': 1168, 'subsample': 0.7394269015823738, 'colsample_bytree': 0.7921147720298904, 'min_child_weight': 3, 'gamma': 2.521133681802387, 'reg_alpha': 0.002289629698312456, 'reg_lambda': 3.396823630968318e-07, 'max_delta_step': 7}. Best is trial 10 with value: 0.5519465240641711.

Best trial: 10. Best value: 0.551947:   7%|▋         | 14/200 [00:34<08:24,  2.71s/it]

[I 2025-11-10 18:49:38,023] Trial 13 finished with value: 0.5098181818181818 and parameters: {'max_depth': 8, 'learning_rate': 0.011402186329368616, 'n_estimators': 645, 'subsample': 0.8358249065047961, 'colsample_bytree': 0.9962022448626373, 'min_child_weight': 5, 'gamma': 0.10527483065762144, 'reg_alpha': 3.8690606534718857, 'reg_lambda': 0.001692428183669835, 'max_delta_step': 10}. Best is trial 10 with value: 0.5519465240641711.

Best trial: 15. Best value: 0.570443:   8%|▊         | 15/200 [00:35<06:44,  2.18s/it]

[I 2025-11-10 18:49:38,979] Trial 15 finished with value: 0.5704430863254393 and parameters: {'max_depth': 3, 'learning_rate': 0.09460906246617881, 'n_estimators': 652, 'subsample': 0.8234097930615769, 'colsample_bytree': 0.9772696442767241, 'min_child_weight': 1, 'gamma': 1.6195305718602029, 'reg_alpha': 1.769963539678049, 'reg_lambda': 0.0002664225408490328, 'max_delta_step': 10}. Best is trial 15 with value: 0.5704430863254393.

Best trial: 14. Best value: 0.573011:   8%|▊         | 16/200 [00:37<06:52,  2.24s/it]

[I 2025-11-10 18:49:41,360] Trial 17 finished with value: 0.5479327731092436 and parameters: {'max_depth': 4, 'learning_rate': 0.10513607721625258, 'n_estimators': 250, 'subsample': 0.8347080644334536, 'colsample_bytree': 0.7011105105408901, 'min_child_weight': 2, 'gamma': 1.3884250467885908, 'reg_alpha': 1.5845887797926333e-08, 'reg_lambda': 8.750696452172647e-05, 'max_delta_step': 3}. Best is trial 15 with value: 0.5704430863254393.
[I 2025-11-10 18:49:41,448] Trial 14 finished with value: 0.5730114591291062 and parameters: {'max_depth': 3, 'learning_rate': 0.09451464757347111, 'n_estimators': 684, 'subsample': 0.8011141394994781, 'colsample_bytree': 0.9648228146375334, 'min_child_weight': 1, 'gamma': 0.1276659671003979, 'reg_alpha': 1.5212489430515674, 'reg_lambda': 0.00018186339376054957, 'max_delta_step': 10}. Best is trial 14 with value: 0.5730114591291062.

Best trial: 18. Best value: 0.594956:   9%|▉         | 18/200 [00:38<04:19,  1.43s/it]

[I 2025-11-10 18:49:42,308] Trial 18 finished with value: 0.5949564553093964 and parameters: {'max_depth': 8, 'learning_rate': 0.1096709657149603, 'n_estimators': 344, 'subsample': 0.8312790221920623, 'colsample_bytree': 0.9812873420063923, 'min_child_weight': 7, 'gamma': 1.4180767379451515, 'reg_alpha': 1.1604588853155466, 'reg_lambda': 0.0005338448227327835, 'max_delta_step': 3}. Best is trial 18 with value: 0.5949564553093964.

Best trial: 18. Best value: 0.594956:  10%|▉         | 19/200 [00:40<04:14,  1.41s/it]

[I 2025-11-10 18:49:43,661] Trial 20 pruned.

Best trial: 18. Best value: 0.594956:  10%|█         | 20/200 [00:41<04:23,  1.46s/it]

[I 2025-11-10 18:49:45,280] Trial 16 finished with value: 0.5702108479755539 and parameters: {'max_depth': 8, 'learning_rate': 0.10365764843580531, 'n_estimators': 704, 'subsample': 0.8319592886344467, 'colsample_bytree': 0.9623611807263562, 'min_child_weight': 1, 'gamma': 1.2130969721608826, 'reg_alpha': 0.5046260938413557, 'reg_lambda': 6.597678037782109e-05, 'max_delta_step': 10}. Best is trial 18 with value: 0.5949564553093964.

Best trial: 18. Best value: 0.594956:  10%|█         | 21/200 [00:43<04:16,  1.44s/it]

[I 2025-11-10 18:49:46,643] Trial 19 finished with value: 0.5518686019862491 and parameters: {'max_depth': 8, 'learning_rate': 0.12227131297073511, 'n_estimators': 541, 'subsample': 0.9980075896648096, 'colsample_bytree': 0.9904286250849519, 'min_child_weight': 7, 'gamma': 1.3551361307675354, 'reg_alpha': 0.3571650801146341, 'reg_lambda': 0.0020143490043053147, 'max_delta_step': 10}. Best is trial 18 with value: 0.5949564553093964.

Best trial: 22. Best value: 0.59515:  12%|█▏        | 23/200 [00:44<02:50,  1.04it/s]

[I 2025-11-10 18:49:47,568] Trial 22 finished with value: 0.5951504965622613 and parameters: {'max_depth': 8, 'learning_rate': 0.15295078957388689, 'n_estimators': 391, 'subsample': 0.8905405683641413, 'colsample_bytree': 0.9299432561303876, 'min_child_weight': 7, 'gamma': 0.7274244880937667, 'reg_alpha': 0.125676358729391, 'reg_lambda': 0.009606267982325315, 'max_delta_step': 2}. Best is trial 22 with value: 0.5951504965622613.
[I 2025-11-10 18:49:47,700] Trial 24 pruned.

Best trial: 22. Best value: 0.59515:  12%|█▏        | 24/200 [00:46<03:37,  1.24s/it]

[I 2025-11-10 18:49:49,607] Trial 23 finished with value: 0.5686004583651643 and parameters: {'max_depth': 8, 'learning_rate': 0.17027805044079225, 'n_estimators': 415, 'subsample': 0.9986737545279928, 'colsample_bytree': 0.917888545693865, 'min_child_weight': 7, 'gamma': 0.564764546045317, 'reg_alpha': 0.09998575189763544, 'reg_lambda': 8.64377136572155, 'max_delta_step': 2}. Best is trial 22 with value: 0.5951504965622613.

Best trial: 22. Best value: 0.59515:  12%|█▎        | 25/200 [00:46<02:56,  1.01s/it]

[I 2025-11-10 18:49:50,064] Trial 21 finished with value: 0.5555019098548512 and parameters: {'max_depth': 8, 'learning_rate': 0.14350368325132587, 'n_estimators': 928, 'subsample': 0.7838256281300625, 'colsample_bytree': 0.9211338714583902, 'min_child_weight': 6, 'gamma': 0.8214908558393975, 'reg_alpha': 0.15154126191306855, 'reg_lambda': 0.005918610312672333, 'max_delta_step': 2}. Best is trial 22 with value: 0.5951504965622613.

Best trial: 26. Best value: 0.611974:  13%|█▎        | 26/200 [00:47<02:32,  1.14it/s]

[I 2025-11-10 18:49:50,634] Trial 26 finished with value: 0.611974025974026 and parameters: {'max_depth': 7, 'learning_rate': 0.2038401414645798, 'n_estimators': 272, 'subsample': 0.892115394805884, 'colsample_bytree': 0.9109006164588718, 'min_child_weight': 7, 'gamma': 0.7660980032846898, 'reg_alpha': 0.09511294806787822, 'reg_lambda': 0.019834485112121644, 'max_delta_step': 0}. Best is trial 26 with value: 0.611974025974026.

Best trial: 26. Best value: 0.611974:  14%|█▎        | 27/200 [00:48<02:36,  1.10it/s]

[I 2025-11-10 18:49:51,604] Trial 25 finished with value: 0.5922245989304813 and parameters: {'max_depth': 9, 'learning_rate': 0.16747394418545547, 'n_estimators': 385, 'subsample': 0.8806961972845121, 'colsample_bytree': 0.9110854087015244, 'min_child_weight': 7, 'gamma': 0.6063891030876666, 'reg_alpha': 0.04609460069731954, 'reg_lambda': 0.015302336453154968, 'max_delta_step': 2}. Best is trial 26 with value: 0.611974025974026.

Best trial: 29. Best value: 0.613022:  14%|█▍        | 28/200 [00:49<02:43,  1.05it/s]

[I 2025-11-10 18:49:52,672] Trial 29 finished with value: 0.6130221543162719 and parameters: {'max_depth': 7, 'learning_rate': 0.19720184631078022, 'n_estimators': 200, 'subsample': 0.8805363513231056, 'colsample_bytree': 0.8918366395640376, 'min_child_weight': 7, 'gamma': 1.921546483329744, 'reg_alpha': 0.020862649275710257, 'reg_lambda': 0.014662363681922384, 'max_delta_step': 0}. Best is trial 29 with value: 0.6130221543162719.
[I 2025-11-10 18:49:52,854] Trial 28 finished with value: 0.6039633307868603 and parameters: {'max_depth': 7, 'learning_rate': 0.06886039870456889, 'n_estimators': 244, 'subsample': 0.8831328358916906, 'colsample_bytree': 0.8808708601675186, 'min_child_weight': 7, 'gamma': 1.8550585601226248, 'reg_alpha': 0.02986724246154, 'reg_lambda': 0.03813018043762326, 'max_delta_step': 0}. Best is trial 29 with value: 0.6130221543162719.

Best trial: 29. Best value: 0.613022:  15%|█▌        | 30/200 [00:49<01:41,  1.68it/s]

[I 2025-11-10 18:49:53,150] Trial 27 finished with value: 0.610113063407181 and parameters: {'max_depth': 7, 'learning_rate': 0.06777407690168637, 'n_estimators': 229, 'subsample': 0.8808917288728353, 'colsample_bytree': 0.9029631077111028, 'min_child_weight': 7, 'gamma': 0.016921281265155325, 'reg_alpha': 0.0256298493074398, 'reg_lambda': 0.012545176837806019, 'max_delta_step': 0}. Best is trial 29 with value: 0.6130221543162719.

Best trial: 30. Best value: 0.632898:  16%|█▌        | 31/200 [00:49<01:31,  1.84it/s]

[I 2025-11-10 18:49:53,573] Trial 30 finished with value: 0.6328976317799846 and parameters: {'max_depth': 7, 'learning_rate': 0.22180373030823625, 'n_estimators': 209, 'subsample': 0.8837470996174549, 'colsample_bytree': 0.8904935793374812, 'min_child_weight': 8, 'gamma': 1.8863568611567672, 'reg_alpha': 0.010363995942214998, 'reg_lambda': 0.03698559838189125, 'max_delta_step': 0}. Best is trial 30 with value: 0.6328976317799846.

Best trial: 30. Best value: 0.632898:  16%|█▌        | 32/200 [00:51<01:56,  1.44it/s]

[I 2025-11-10 18:49:54,619] Trial 31 finished with value: 0.6159029793735676 and parameters: {'max_depth': 7, 'learning_rate': 0.23949836248726147, 'n_estimators': 208, 'subsample': 0.8988246736611817, 'colsample_bytree': 0.8714741706360273, 'min_child_weight': 8, 'gamma': 1.955082662144522, 'reg_alpha': 0.011001881083573806, 'reg_lambda': 0.05338647621973708, 'max_delta_step': 0}. Best is trial 30 with value: 0.6328976317799846.

Best trial: 30. Best value: 0.632898:  16%|█▋        | 33/200 [00:51<01:35,  1.75it/s]

[I 2025-11-10 18:49:54,902] Trial 32 finished with value: 0.6195064935064936 and parameters: {'max_depth': 7, 'learning_rate': 0.2921866789557214, 'n_estimators': 229, 'subsample': 0.8951393623455702, 'colsample_bytree': 0.8726824560186477, 'min_child_weight': 8, 'gamma': 1.9952951082867951, 'reg_alpha': 0.00798025817060807, 'reg_lambda': 0.05391977388342134, 'max_delta_step': 0}. Best is trial 30 with value: 0.6328976317799846.

Best trial: 30. Best value: 0.632898:  17%|█▋        | 34/200 [00:51<01:32,  1.78it/s]

[I 2025-11-10 18:49:55,438] Trial 33 finished with value: 0.5981367456073338 and parameters: {'max_depth': 7, 'learning_rate': 0.21861090075711406, 'n_estimators': 258, 'subsample': 0.9154164368878508, 'colsample_bytree': 0.8723930128189133, 'min_child_weight': 8, 'gamma': 2.078962610415592, 'reg_alpha': 0.005847059163114335, 'reg_lambda': 1.9464074865860674, 'max_delta_step': 0}. Best is trial 30 with value: 0.6328976317799846.
[I 2025-11-10 18:49:55,473] Trial 34 finished with value: 0.5995362872421696 and parameters: {'max_depth': 7, 'learning_rate': 0.19985054152573137, 'n_estimators': 205, 'subsample': 0.9106024734601741, 'colsample_bytree': 0.8793558079482144, 'min_child_weight': 8, 'gamma': 2.104162229963445, 'reg_alpha': 0.010536636325355925, 'reg_lambda': 1.987490358852507, 'max_delta_step': 0}. Best is trial 30 with value: 0.6328976317799846.

Best trial: 30. Best value: 0.632898:  18%|█▊        | 36/200 [00:52<01:21,  2.02it/s]

[I 2025-11-10 18:49:56,277] Trial 38 pruned.

Best trial: 30. Best value: 0.632898:  18%|█▊        | 37/200 [00:53<01:28,  1.83it/s]

[I 2025-11-10 18:49:56,975] Trial 36 finished with value: 0.614603514132926 and parameters: {'max_depth': 6, 'learning_rate': 0.2996804035752458, 'n_estimators': 224, 'subsample': 0.9603459944035273, 'colsample_bytree': 0.8805114079117888, 'min_child_weight': 8, 'gamma': 2.1124737064989416, 'reg_alpha': 0.00014106624734811686, 'reg_lambda': 3.8012312580912355, 'max_delta_step': 1}. Best is trial 30 with value: 0.6328976317799846.

Best trial: 30. Best value: 0.632898:  19%|█▉        | 38/200 [00:53<01:14,  2.18it/s]

[I 2025-11-10 18:49:57,182] Trial 35 finished with value: 0.6067219251336897 and parameters: {'max_depth': 6, 'learning_rate': 0.22161488468040877, 'n_estimators': 287, 'subsample': 0.9113001969766223, 'colsample_bytree': 0.8739293798814624, 'min_child_weight': 8, 'gamma': 2.003117700639242, 'reg_alpha': 0.006693492780608705, 'reg_lambda': 2.5802029031650426, 'max_delta_step': 0}. Best is trial 30 with value: 0.6328976317799846.

Best trial: 30. Best value: 0.632898:  20%|█▉        | 39/200 [00:53<01:08,  2.36it/s]

[I 2025-11-10 18:49:57,517] Trial 40 pruned.

Best trial: 30. Best value: 0.632898:  20%|██        | 40/200 [00:54<01:12,  2.21it/s]

[I 2025-11-10 18:49:58,045] Trial 41 pruned.

Best trial: 30. Best value: 0.632898:  20%|██        | 41/200 [00:54<01:09,  2.27it/s]

[I 2025-11-10 18:49:58,453] Trial 42 pruned.

Best trial: 30. Best value: 0.632898:  22%|██▏       | 43/200 [00:55<00:54,  2.90it/s]

[I 2025-11-10 18:49:58,846] Trial 43 pruned.
[I 2025-11-10 18:49:58,996] Trial 44 pruned.

Best trial: 30. Best value: 0.632898:  22%|██▏       | 44/200 [00:55<00:52,  2.98it/s]

[I 2025-11-10 18:49:59,307] Trial 45 pruned.

Best trial: 30. Best value: 0.632898:  23%|██▎       | 46/200 [00:56<00:42,  3.64it/s]

[I 2025-11-10 18:49:59,589] Trial 37 finished with value: 0.6214690603514134 and parameters: {'max_depth': 6, 'learning_rate': 0.29663384027379514, 'n_estimators': 466, 'subsample': 0.9711041581741814, 'colsample_bytree': 0.8542321052265587, 'min_child_weight': 8, 'gamma': 2.178398488946553, 'reg_alpha': 0.00019203994926075114, 'reg_lambda': 0.0744102057554963, 'max_delta_step': 1}. Best is trial 30 with value: 0.6328976317799846.
[I 2025-11-10 18:49:59,758] Trial 39 finished with value: 0.535899923605806 and parameters: {'max_depth': 6, 'learning_rate': 0.29050243942063864, 'n_estimators': 315, 'subsample': 0.9695891575947604, 'colsample_bytree': 0.8561761320920876, 'min_child_weight': 6, 'gamma': 2.290276857149732, 'reg_alpha': 6.68405056692567e-05, 'reg_lambda': 0.09004622208686461, 'max_delta_step': 1}. Best is trial 30 with value: 0.6328976317799846.

Best trial: 46. Best value: 0.634283:  24%|██▎       | 47/200 [00:58<01:52,  1.36it/s]

[I 2025-11-10 18:50:01,578] Trial 46 finished with value: 0.634283422459893 and parameters: {'max_depth': 7, 'learning_rate': 0.1935919552709926, 'n_estimators': 320, 'subsample': 0.8549082245881711, 'colsample_bytree': 0.8336090409014657, 'min_child_weight': 8, 'gamma': 1.546916745575711, 'reg_alpha': 0.002516692302326943, 'reg_lambda': 0.05664223961737439, 'max_delta_step': 3}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  24%|██▍       | 48/200 [00:58<01:44,  1.45it/s]

[I 2025-11-10 18:50:02,155] Trial 47 finished with value: 0.6019870129870128 and parameters: {'max_depth': 6, 'learning_rate': 0.13556349843997045, 'n_estimators': 339, 'subsample': 0.9275506073782573, 'colsample_bytree': 0.7557152005717722, 'min_child_weight': 8, 'gamma': 2.5773494658376523, 'reg_alpha': 0.003410627961810838, 'reg_lambda': 1.1460296546215651e-08, 'max_delta_step': 3}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  24%|██▍       | 49/200 [00:58<01:25,  1.77it/s]

[I 2025-11-10 18:50:02,434] Trial 48 finished with value: 0.6000542398777693 and parameters: {'max_depth': 5, 'learning_rate': 0.1260813138035456, 'n_estimators': 343, 'subsample': 0.9358459771922799, 'colsample_bytree': 0.7488748177273014, 'min_child_weight': 8, 'gamma': 2.4576781987681016, 'reg_alpha': 0.0001448509549673683, 'reg_lambda': 0.20595329645739252, 'max_delta_step': 3}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  25%|██▌       | 50/200 [00:59<01:16,  1.96it/s]

[I 2025-11-10 18:50:02,820] Trial 51 pruned.

Best trial: 46. Best value: 0.634283:  26%|██▌       | 51/200 [00:59<01:08,  2.18it/s]

[I 2025-11-10 18:50:03,155] Trial 52 pruned.

Best trial: 46. Best value: 0.634283:  26%|██▌       | 52/200 [00:59<01:02,  2.38it/s]

[I 2025-11-10 18:50:03,486] Trial 49 finished with value: 0.6039304812834224 and parameters: {'max_depth': 5, 'learning_rate': 0.14110218084331372, 'n_estimators': 446, 'subsample': 0.9299117003760771, 'colsample_bytree': 0.7522056141559292, 'min_child_weight': 8, 'gamma': 2.5799719724244405, 'reg_alpha': 0.003088839114746846, 'reg_lambda': 0.885245615937648, 'max_delta_step': 3}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  27%|██▋       | 54/200 [01:00<00:51,  2.86it/s]

[I 2025-11-10 18:50:03,925] Trial 55 pruned.
[I 2025-11-10 18:50:04,097] Trial 53 pruned.

Best trial: 46. Best value: 0.634283:  28%|██▊       | 55/200 [01:00<00:55,  2.62it/s]

[I 2025-11-10 18:50:04,553] Trial 56 pruned.

Best trial: 46. Best value: 0.634283:  28%|██▊       | 56/200 [01:01<01:17,  1.85it/s]

[I 2025-11-10 18:50:05,464] Trial 50 finished with value: 0.6050977845683727 and parameters: {'max_depth': 5, 'learning_rate': 0.12873259355449135, 'n_estimators': 447, 'subsample': 0.9364765724221856, 'colsample_bytree': 0.7484128270475644, 'min_child_weight': 8, 'gamma': 2.5940204229903103, 'reg_alpha': 0.003749806751743271, 'reg_lambda': 0.20576184871212352, 'max_delta_step': 3}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  28%|██▊       | 57/200 [01:02<01:02,  2.29it/s]

[I 2025-11-10 18:50:05,661] Trial 57 pruned.

Best trial: 46. Best value: 0.634283:  29%|██▉       | 58/200 [01:02<00:51,  2.76it/s]

[I 2025-11-10 18:50:05,847] Trial 54 finished with value: 0.6197738731856377 and parameters: {'max_depth': 6, 'learning_rate': 0.24685711467939617, 'n_estimators': 281, 'subsample': 0.948955003217849, 'colsample_bytree': 0.8382985447803453, 'min_child_weight': 8, 'gamma': 1.6869446072657488, 'reg_alpha': 1.958472541029678e-05, 'reg_lambda': 0.03659396503920641, 'max_delta_step': 1}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  30%|██▉       | 59/200 [01:03<01:06,  2.11it/s]

[I 2025-11-10 18:50:06,580] Trial 61 pruned.

Best trial: 46. Best value: 0.634283:  30%|███       | 60/200 [01:03<01:00,  2.32it/s]

[I 2025-11-10 18:50:06,912] Trial 59 pruned.

Best trial: 46. Best value: 0.634283:  30%|███       | 61/200 [01:03<01:00,  2.31it/s]

[I 2025-11-10 18:50:07,347] Trial 58 finished with value: 0.6177211611917495 and parameters: {'max_depth': 7, 'learning_rate': 0.26794693898571953, 'n_estimators': 298, 'subsample': 0.9483458292525171, 'colsample_bytree': 0.8600809002572872, 'min_child_weight': 8, 'gamma': 1.5185873363260067, 'reg_alpha': 0.014792985116346599, 'reg_lambda': 0.0035723147486562386, 'max_delta_step': 1}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  31%|███       | 62/200 [01:04<00:57,  2.40it/s]

[I 2025-11-10 18:50:07,727] Trial 62 pruned.

Best trial: 46. Best value: 0.634283:  32%|███▏      | 63/200 [01:06<02:32,  1.11s/it]

[I 2025-11-10 18:50:10,459] Trial 64 finished with value: 0.6203689839572192 and parameters: {'max_depth': 8, 'learning_rate': 0.23720954510780928, 'n_estimators': 355, 'subsample': 0.9932071162487532, 'colsample_bytree': 0.8956740158392847, 'min_child_weight': 8, 'gamma': 1.7752278223067717, 'reg_alpha': 2.872590570260908e-07, 'reg_lambda': 0.0409537076732032, 'max_delta_step': 0}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  32%|███▏      | 64/200 [01:07<02:09,  1.05it/s]

[I 2025-11-10 18:50:11,030] Trial 65 finished with value: 0.6240695187165775 and parameters: {'max_depth': 7, 'learning_rate': 0.16045667376835476, 'n_estimators': 365, 'subsample': 0.9890437292947175, 'colsample_bytree': 0.8952005911064282, 'min_child_weight': 8, 'gamma': 1.3187556188666882, 'reg_alpha': 0.012798202117986478, 'reg_lambda': 0.0061842121555542645, 'max_delta_step': 1}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  32%|███▎      | 65/200 [01:08<02:01,  1.11it/s]

[I 2025-11-10 18:50:11,814] Trial 67 pruned.

Best trial: 46. Best value: 0.634283:  33%|███▎      | 66/200 [01:08<01:40,  1.33it/s]

[I 2025-11-10 18:50:12,223] Trial 60 finished with value: 0.6266783804430862 and parameters: {'max_depth': 7, 'learning_rate': 0.2657490948771167, 'n_estimators': 769, 'subsample': 0.9862055473981823, 'colsample_bytree': 0.8847559581425253, 'min_child_weight': 8, 'gamma': 1.4520138263088773, 'reg_alpha': 0.013536175088356944, 'reg_lambda': 0.0349723693515235, 'max_delta_step': 1}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  34%|███▎      | 67/200 [01:09<01:44,  1.28it/s]

[I 2025-11-10 18:50:13,080] Trial 69 pruned.

Best trial: 46. Best value: 0.634283:  34%|███▍      | 68/200 [01:09<01:31,  1.44it/s]

[I 2025-11-10 18:50:13,561] Trial 63 finished with value: 0.607855614973262 and parameters: {'max_depth': 8, 'learning_rate': 0.15732958696405722, 'n_estimators': 804, 'subsample': 0.9999640868563768, 'colsample_bytree': 0.7817804965204376, 'min_child_weight': 8, 'gamma': 1.715962597166977, 'reg_alpha': 2.736860742647089e-07, 'reg_lambda': 0.0015124083733447618, 'max_delta_step': 0}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  35%|███▌      | 70/200 [01:10<00:59,  2.19it/s]

[I 2025-11-10 18:50:13,970] Trial 66 finished with value: 0.630048128342246 and parameters: {'max_depth': 8, 'learning_rate': 0.16005104816112678, 'n_estimators': 357, 'subsample': 0.9883078675189304, 'colsample_bytree': 0.8939480970123773, 'min_child_weight': 8, 'gamma': 1.3162409201300491, 'reg_alpha': 2.615905751230713e-07, 'reg_lambda': 0.00609029081550725, 'max_delta_step': 2}. Best is trial 46 with value: 0.634283422459893.
[I 2025-11-10 18:50:14,078] Trial 70 pruned.

Best trial: 46. Best value: 0.634283:  36%|███▌      | 71/200 [01:12<02:12,  1.03s/it]

[I 2025-11-10 18:50:16,430] Trial 72 pruned.

Best trial: 46. Best value: 0.634283:  36%|███▌      | 72/200 [01:14<02:19,  1.09s/it]

[I 2025-11-10 18:50:17,681] Trial 74 pruned.
[I 2025-11-10 18:50:17,719] Trial 73 pruned.

Best trial: 46. Best value: 0.634283:  37%|███▋      | 74/200 [01:16<02:32,  1.21s/it]

[I 2025-11-10 18:50:20,379] Trial 71 finished with value: 0.6020122230710465 and parameters: {'max_depth': 6, 'learning_rate': 0.01643466776575028, 'n_estimators': 487, 'subsample': 0.7151195381237367, 'colsample_bytree': 0.8935345544899033, 'min_child_weight': 7, 'gamma': 1.3195816518037824, 'reg_alpha': 5.7910191218922335e-06, 'reg_lambda': 0.027903764345043137, 'max_delta_step': 9}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  38%|███▊      | 75/200 [01:17<02:07,  1.02s/it]

[I 2025-11-10 18:50:20,834] Trial 76 finished with value: 0.6201650114591291 and parameters: {'max_depth': 8, 'learning_rate': 0.1741370095694975, 'n_estimators': 363, 'subsample': 0.92133133000963, 'colsample_bytree': 0.8954589164009452, 'min_child_weight': 8, 'gamma': 1.4216311391259089, 'reg_alpha': 1.260883647879851e-08, 'reg_lambda': 0.018724396882190065, 'max_delta_step': 1}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  38%|███▊      | 76/200 [01:17<01:45,  1.18it/s]

[I 2025-11-10 18:50:21,187] Trial 75 finished with value: 0.6176470588235294 and parameters: {'max_depth': 8, 'learning_rate': 0.07956431394335094, 'n_estimators': 366, 'subsample': 0.9769575813679926, 'colsample_bytree': 0.8919150557520145, 'min_child_weight': 8, 'gamma': 1.56803274509752, 'reg_alpha': 3.3124267746492726e-08, 'reg_lambda': 0.02415700258482805, 'max_delta_step': 1}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  38%|███▊      | 77/200 [01:18<01:29,  1.38it/s]

[I 2025-11-10 18:50:21,579] Trial 78 pruned.

Best trial: 46. Best value: 0.634283:  39%|███▉      | 78/200 [01:18<01:29,  1.36it/s]

[I 2025-11-10 18:50:22,345] Trial 79 pruned.

Best trial: 46. Best value: 0.634283:  40%|███▉      | 79/200 [01:20<02:00,  1.00it/s]

[I 2025-11-10 18:50:23,988] Trial 77 finished with value: 0.6245141329258976 and parameters: {'max_depth': 8, 'learning_rate': 0.08348332270582234, 'n_estimators': 361, 'subsample': 0.9804008719201468, 'colsample_bytree': 0.9630489320512646, 'min_child_weight': 8, 'gamma': 1.466567543854569, 'reg_alpha': 1.2414534454120492e-06, 'reg_lambda': 0.018459009401130037, 'max_delta_step': 1}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  40%|████      | 80/200 [01:20<01:33,  1.28it/s]

[I 2025-11-10 18:50:24,236] Trial 68 finished with value: 0.5973880825057295 and parameters: {'max_depth': 8, 'learning_rate': 0.08463814437643796, 'n_estimators': 1393, 'subsample': 0.992667521273487, 'colsample_bytree': 0.8893466546177246, 'min_child_weight': 9, 'gamma': 0.9472744175753551, 'reg_alpha': 1.1137492295737569e-07, 'reg_lambda': 0.0011598065192565702, 'max_delta_step': 0}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  40%|████      | 81/200 [01:23<02:45,  1.39s/it]

[I 2025-11-10 18:50:27,108] Trial 81 finished with value: 0.6279824293353705 and parameters: {'max_depth': 8, 'learning_rate': 0.030892183842786594, 'n_estimators': 406, 'subsample': 0.9558215294549428, 'colsample_bytree': 0.8848293967964431, 'min_child_weight': 8, 'gamma': 1.076949809868981, 'reg_alpha': 7.46909225726291e-07, 'reg_lambda': 0.0028161518123682168, 'max_delta_step': 0}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  41%|████      | 82/200 [01:24<02:12,  1.12s/it]

[I 2025-11-10 18:50:27,582] Trial 80 finished with value: 0.6336249045072574 and parameters: {'max_depth': 10, 'learning_rate': 0.17396413793210697, 'n_estimators': 738, 'subsample': 0.958545345761642, 'colsample_bytree': 0.8878671095126196, 'min_child_weight': 8, 'gamma': 1.85235972666413, 'reg_alpha': 1.1367913023397364e-08, 'reg_lambda': 0.0027534359344542868, 'max_delta_step': 2}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  42%|████▏     | 83/200 [01:24<01:39,  1.17it/s]

[I 2025-11-10 18:50:27,800] Trial 82 finished with value: 0.6251390374331551 and parameters: {'max_depth': 7, 'learning_rate': 0.11483814291597293, 'n_estimators': 407, 'subsample': 0.964299487885321, 'colsample_bytree': 0.9798604436916265, 'min_child_weight': 8, 'gamma': 1.7927688517484226, 'reg_alpha': 8.081319644767938e-07, 'reg_lambda': 0.14336022337771287, 'max_delta_step': 0}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  42%|████▏     | 84/200 [01:24<01:34,  1.22it/s]

[I 2025-11-10 18:50:28,530] Trial 83 finished with value: 0.6187922077922078 and parameters: {'max_depth': 7, 'learning_rate': 0.03033922468390514, 'n_estimators': 411, 'subsample': 0.9801223294356334, 'colsample_bytree': 0.9777717642166097, 'min_child_weight': 8, 'gamma': 1.8390455050911636, 'reg_alpha': 0.06627460657344461, 'reg_lambda': 0.00029817775075089846, 'max_delta_step': 0}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  42%|████▎     | 85/200 [01:26<01:50,  1.04it/s]

[I 2025-11-10 18:50:29,820] Trial 85 pruned.

Best trial: 46. Best value: 0.634283:  43%|████▎     | 86/200 [01:26<01:32,  1.23it/s]

[I 2025-11-10 18:50:30,295] Trial 87 pruned.

Best trial: 46. Best value: 0.634283:  44%|████▍     | 88/200 [01:27<01:10,  1.59it/s]

[I 2025-11-10 18:50:31,196] Trial 84 finished with value: 0.6196432391138273 and parameters: {'max_depth': 7, 'learning_rate': 0.041382428748258586, 'n_estimators': 402, 'subsample': 0.9596502632831173, 'colsample_bytree': 0.9353797285171979, 'min_child_weight': 8, 'gamma': 1.8707177835147861, 'reg_alpha': 1.5254352875620396e-06, 'reg_lambda': 0.12622531369809853, 'max_delta_step': 0}. Best is trial 46 with value: 0.634283422459893.
[I 2025-11-10 18:50:31,327] Trial 88 pruned.

Best trial: 46. Best value: 0.634283:  45%|████▌     | 90/200 [01:29<01:07,  1.63it/s]

[I 2025-11-10 18:50:32,562] Trial 90 pruned.
[I 2025-11-10 18:50:32,716] Trial 91 pruned.

Best trial: 46. Best value: 0.634283:  46%|████▌     | 91/200 [01:29<01:09,  1.56it/s]

[I 2025-11-10 18:50:33,416] Trial 93 pruned.

Best trial: 46. Best value: 0.634283:  46%|████▋     | 93/200 [01:30<00:53,  2.01it/s]

[I 2025-11-10 18:50:34,134] Trial 92 pruned.
[I 2025-11-10 18:50:34,244] Trial 86 finished with value: 0.6271512605042016 and parameters: {'max_depth': 9, 'learning_rate': 0.11607015611808083, 'n_estimators': 747, 'subsample': 0.9582314676874816, 'colsample_bytree': 0.986374508325554, 'min_child_weight': 8, 'gamma': 1.879483451463003, 'reg_alpha': 6.01010647530356e-07, 'reg_lambda': 0.002346350581778347, 'max_delta_step': 0}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  47%|████▋     | 94/200 [01:31<00:53,  2.00it/s]

[I 2025-11-10 18:50:34,753] Trial 95 pruned.

Best trial: 46. Best value: 0.634283:  48%|████▊     | 95/200 [01:31<00:53,  1.98it/s]

[I 2025-11-10 18:50:35,272] Trial 96 pruned.

Best trial: 46. Best value: 0.634283:  48%|████▊     | 96/200 [01:32<01:14,  1.40it/s]

[I 2025-11-10 18:50:36,476] Trial 94 finished with value: 0.6120939648586707 and parameters: {'max_depth': 7, 'learning_rate': 0.03436899398180404, 'n_estimators': 320, 'subsample': 0.9709973543890724, 'colsample_bytree': 0.8447952984507068, 'min_child_weight': 8, 'gamma': 2.2248321643408118, 'reg_alpha': 6.229673815421974e-07, 'reg_lambda': 0.010237007493484798, 'max_delta_step': 1}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  48%|████▊     | 97/200 [01:35<01:58,  1.15s/it]

[I 2025-11-10 18:50:38,635] Trial 89 finished with value: 0.6254262796027502 and parameters: {'max_depth': 7, 'learning_rate': 0.11920629140830949, 'n_estimators': 990, 'subsample': 0.9660501456398749, 'colsample_bytree': 0.9992502967364638, 'min_child_weight': 8, 'gamma': 1.911015067226353, 'reg_alpha': 0.20441596858221858, 'reg_lambda': 0.003802368953018403, 'max_delta_step': 3}. Best is trial 46 with value: 0.634283422459893.

Best trial: 46. Best value: 0.634283:  49%|████▉     | 98/200 [01:36<02:05,  1.23s/it]

[I 2025-11-10 18:50:40,061] Trial 97 finished with value: 0.6144300993124523 and parameters: {'max_depth': 10, 'learning_rate': 0.13496074886622997, 'n_estimators': 678, 'subsample': 0.9293544929632209, 'colsample_bytree': 0.9512488782800086, 'min_child_weight': 8, 'gamma': 1.361832929619578, 'reg_alpha': 4.9079498439675544e-06, 'reg_lambda': 0.010818170435674485, 'max_delta_step': 0}. Best is trial 46 with value: 0.634283422459893.

Best trial: 98. Best value: 0.636062:  50%|████▉     | 99/200 [01:38<02:22,  1.42s/it]

[I 2025-11-10 18:50:41,908] Trial 101 pruned.
[I 2025-11-10 18:50:41,989] Trial 98 finished with value: 0.6360618792971733 and parameters: {'max_depth': 10, 'learning_rate': 0.13800930658536517, 'n_estimators': 835, 'subsample': 0.9800162242470815, 'colsample_bytree': 0.982026484032937, 'min_child_weight': 8, 'gamma': 1.5969002489371362, 'reg_alpha': 4.000833315300348e-06, 'reg_lambda': 0.0006783468187338672, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  51%|█████     | 102/200 [01:39<01:23,  1.18it/s]

[I 2025-11-10 18:50:43,306] Trial 102 pruned.
[I 2025-11-10 18:50:43,436] Trial 99 finished with value: 0.6281459129106187 and parameters: {'max_depth': 10, 'learning_rate': 0.06119280258793225, 'n_estimators': 806, 'subsample': 0.9584658636828215, 'colsample_bytree': 0.9841871772499533, 'min_child_weight': 8, 'gamma': 1.60268126884668, 'reg_alpha': 1.6879417505614123e-07, 'reg_lambda': 4.651623267557289e-05, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  51%|█████     | 102/200 [01:39<01:23,  1.18it/s]

[I 2025-11-10 18:50:43,495] Trial 103 pruned.

Best trial: 98. Best value: 0.636062:  52%|█████▏    | 104/200 [01:41<01:25,  1.13it/s]

[I 2025-11-10 18:50:45,324] Trial 100 finished with value: 0.6331268143621085 and parameters: {'max_depth': 10, 'learning_rate': 0.1028434706383542, 'n_estimators': 815, 'subsample': 0.9334361756212645, 'colsample_bytree': 0.9798483253841302, 'min_child_weight': 8, 'gamma': 1.9417772604196326, 'reg_alpha': 5.460950188090185e-06, 'reg_lambda': 3.6238623972039355e-07, 'max_delta_step': 3}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  52%|█████▎    | 105/200 [01:43<01:53,  1.19s/it]

[I 2025-11-10 18:50:47,552] Trial 107 pruned.

Best trial: 98. Best value: 0.636062:  53%|█████▎    | 106/200 [01:45<01:52,  1.19s/it]

[I 2025-11-10 18:50:48,749] Trial 108 pruned.

Best trial: 98. Best value: 0.636062:  54%|█████▎    | 107/200 [01:46<01:53,  1.22s/it]

[I 2025-11-10 18:50:50,059] Trial 109 pruned.

Best trial: 98. Best value: 0.636062:  55%|█████▌    | 110/200 [01:47<01:04,  1.40it/s]

[I 2025-11-10 18:50:51,240] Trial 105 finished with value: 0.5812650878533232 and parameters: {'max_depth': 10, 'learning_rate': 0.0603603086893932, 'n_estimators': 791, 'subsample': 0.9415280079212658, 'colsample_bytree': 0.9850916647752852, 'min_child_weight': 7, 'gamma': 1.6294784243613032, 'reg_alpha': 1.7934031312167728e-07, 'reg_lambda': 0.00039198041590584633, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.
[I 2025-11-10 18:50:51,258] Trial 106 finished with value: 0.6236936592818946 and parameters: {'max_depth': 10, 'learning_rate': 0.02390226173309091, 'n_estimators': 810, 'subsample': 0.9450119538122669, 'colsample_bytree': 0.968652341551458, 'min_child_weight': 8, 'gamma': 1.758831319479199, 'reg_alpha': 4.43964366714064e-06, 'reg_lambda': 0.00017567156817967417, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.
[I 2025-11-10 18:50:51,382] Trial 104 finished with value: 0.6271084797555385 and parameters: {'max_depth': 10, 'learning_rate': 0.06049872782870564, 'n_estimators': 885, 'subsample': 0.9805838986769987, 'colsample_bytree': 0.9685085657317304, 'min_child_weight': 8, 'gamma': 1.5862596761494232, 'reg_alpha': 1.6051438577414767e-07, 'reg_lambda': 0.001801690685026707, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  56%|█████▌    | 111/200 [01:49<01:16,  1.16it/s]

[I 2025-11-10 18:50:52,706] Trial 113 pruned.

Best trial: 98. Best value: 0.636062:  56%|█████▌    | 112/200 [01:53<02:43,  1.85s/it]

[I 2025-11-10 18:50:57,490] Trial 112 finished with value: 0.5973162719633307 and parameters: {'max_depth': 10, 'learning_rate': 0.14070645413815608, 'n_estimators': 887, 'subsample': 0.9540308054090666, 'colsample_bytree': 0.8817826333818879, 'min_child_weight': 9, 'gamma': 1.5431701413471348, 'reg_alpha': 3.088060430842115e-05, 'reg_lambda': 0.00411024854613939, 'max_delta_step': 5}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  57%|█████▋    | 114/200 [01:55<01:51,  1.30s/it]

[I 2025-11-10 18:50:58,884] Trial 111 finished with value: 0.6248479755538578 and parameters: {'max_depth': 10, 'learning_rate': 0.0497205177522839, 'n_estimators': 906, 'subsample': 0.9511840859115483, 'colsample_bytree': 0.8834429623422008, 'min_child_weight': 8, 'gamma': 2.0465733036928824, 'reg_alpha': 3.4180113219739155e-05, 'reg_lambda': 4.9543043343253143e-05, 'max_delta_step': 3}. Best is trial 98 with value: 0.6360618792971733.
[I 2025-11-10 18:50:59,034] Trial 110 finished with value: 0.5825767761650115 and parameters: {'max_depth': 10, 'learning_rate': 0.07126689236983805, 'n_estimators': 948, 'subsample': 0.9432187800196767, 'colsample_bytree': 0.9994754222271286, 'min_child_weight': 7, 'gamma': 2.085920213089764, 'reg_alpha': 1.603612796746407e-07, 'reg_lambda': 5.8324368808638935e-05, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  57%|█████▊    | 115/200 [01:56<01:55,  1.36s/it]

[I 2025-11-10 18:51:00,541] Trial 116 pruned.

Best trial: 98. Best value: 0.636062:  58%|█████▊    | 116/200 [01:57<01:27,  1.04s/it]

[I 2025-11-10 18:51:00,800] Trial 114 finished with value: 0.6336982429335369 and parameters: {'max_depth': 10, 'learning_rate': 0.07169850784964905, 'n_estimators': 947, 'subsample': 0.9565552826161257, 'colsample_bytree': 0.9978999301580395, 'min_child_weight': 8, 'gamma': 1.5454235861659533, 'reg_alpha': 7.662326903892266e-06, 'reg_lambda': 1.670099389542988e-06, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  58%|█████▊    | 117/200 [02:01<02:49,  2.04s/it]

[I 2025-11-10 18:51:05,262] Trial 115 finished with value: 0.6214759358288771 and parameters: {'max_depth': 9, 'learning_rate': 0.07283310716026371, 'n_estimators': 929, 'subsample': 0.9755285277245305, 'colsample_bytree': 0.9441030748854055, 'min_child_weight': 8, 'gamma': 1.8912495405622542, 'reg_alpha': 7.5781487425489e-06, 'reg_lambda': 0.001069852650303029, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  59%|█████▉    | 118/200 [02:03<02:35,  1.90s/it]

[I 2025-11-10 18:51:06,841] Trial 117 finished with value: 0.6261779984721161 and parameters: {'max_depth': 9, 'learning_rate': 0.06324873825366578, 'n_estimators': 952, 'subsample': 0.9751898976006185, 'colsample_bytree': 0.9370584156183884, 'min_child_weight': 8, 'gamma': 1.8634279511439933, 'reg_alpha': 2.4438178660521603e-08, 'reg_lambda': 1.647771247962973e-06, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  60%|█████▉    | 119/200 [02:04<02:12,  1.64s/it]

[I 2025-11-10 18:51:07,863] Trial 119 finished with value: 0.6235263559969443 and parameters: {'max_depth': 9, 'learning_rate': 0.06637714747098694, 'n_estimators': 840, 'subsample': 0.9770035397877397, 'colsample_bytree': 0.9564401896037888, 'min_child_weight': 8, 'gamma': 1.542926154194538, 'reg_alpha': 7.382281167968254e-06, 'reg_lambda': 7.14948475154214e-06, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  60%|██████    | 121/200 [02:05<01:26,  1.09s/it]

[I 2025-11-10 18:51:09,004] Trial 118 finished with value: 0.6098632543926662 and parameters: {'max_depth': 9, 'learning_rate': 0.06423341787559488, 'n_estimators': 1057, 'subsample': 0.9774597028704358, 'colsample_bytree': 0.8663381412401393, 'min_child_weight': 8, 'gamma': 2.3323237040801996, 'reg_alpha': 9.015371089194666e-06, 'reg_lambda': 0.0010095425367806776, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.
[I 2025-11-10 18:51:09,147] Trial 122 pruned.

Best trial: 98. Best value: 0.636062:  61%|██████    | 122/200 [02:06<01:32,  1.18s/it]

[I 2025-11-10 18:51:10,543] Trial 123 pruned.

Best trial: 98. Best value: 0.636062:  62%|██████▏   | 123/200 [02:07<01:13,  1.05it/s]

[I 2025-11-10 18:51:10,966] Trial 120 finished with value: 0.6266974789915967 and parameters: {'max_depth': 10, 'learning_rate': 0.06199530507049585, 'n_estimators': 761, 'subsample': 0.9848409419864189, 'colsample_bytree': 0.5698416759506555, 'min_child_weight': 8, 'gamma': 1.551024245976945, 'reg_alpha': 2.0179628640913164e-08, 'reg_lambda': 1.0436711264790348e-07, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  62%|██████▏   | 124/200 [02:10<02:05,  1.66s/it]

[I 2025-11-10 18:51:14,266] Trial 121 finished with value: 0.6264774637127578 and parameters: {'max_depth': 10, 'learning_rate': 0.06233592403210331, 'n_estimators': 850, 'subsample': 0.9870204600142007, 'colsample_bytree': 0.958682417975438, 'min_child_weight': 8, 'gamma': 1.5774006902004747, 'reg_alpha': 7.090438609051327e-08, 'reg_lambda': 9.479167782754441e-08, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  62%|██████▎   | 125/200 [02:12<01:58,  1.58s/it]

[I 2025-11-10 18:51:15,664] Trial 127 pruned.

Best trial: 98. Best value: 0.636062:  63%|██████▎   | 126/200 [02:12<01:27,  1.19s/it]

[I 2025-11-10 18:51:15,928] Trial 124 finished with value: 0.6291252864782276 and parameters: {'max_depth': 10, 'learning_rate': 0.07563515799110535, 'n_estimators': 779, 'subsample': 0.9895994621523803, 'colsample_bytree': 0.9303628533903048, 'min_child_weight': 8, 'gamma': 1.6662913497335043, 'reg_alpha': 2.4454971708310596e-08, 'reg_lambda': 8.679992713673933e-08, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  64%|██████▎   | 127/200 [02:12<01:14,  1.02s/it]

[I 2025-11-10 18:51:16,545] Trial 126 finished with value: 0.6268319327731092 and parameters: {'max_depth': 10, 'learning_rate': 0.07525501341481106, 'n_estimators': 697, 'subsample': 0.9908649469176314, 'colsample_bytree': 0.6890298029758741, 'min_child_weight': 8, 'gamma': 1.1250271523518574, 'reg_alpha': 3.635072222776559e-08, 'reg_lambda': 4.458106079441915e-08, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  64%|██████▍   | 128/200 [02:13<00:55,  1.29it/s]

[I 2025-11-10 18:51:16,759] Trial 125 finished with value: 0.6149236058059587 and parameters: {'max_depth': 10, 'learning_rate': 0.21503643238649306, 'n_estimators': 722, 'subsample': 0.9867857840196637, 'colsample_bytree': 0.9606670804112397, 'min_child_weight': 8, 'gamma': 2.172051408063725, 'reg_alpha': 2.5326031668197714e-08, 'reg_lambda': 1.9003310413990517e-07, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  64%|██████▍   | 129/200 [02:13<00:47,  1.50it/s]

[I 2025-11-10 18:51:17,170] Trial 129 pruned.

Best trial: 98. Best value: 0.636062:  65%|██████▌   | 130/200 [02:14<00:51,  1.35it/s]

[I 2025-11-10 18:51:18,095] Trial 130 pruned.

Best trial: 98. Best value: 0.636062:  66%|██████▌   | 131/200 [02:14<00:41,  1.68it/s]

[I 2025-11-10 18:51:18,345] Trial 131 pruned.

Best trial: 98. Best value: 0.636062:  66%|██████▌   | 132/200 [02:15<00:33,  2.02it/s]

[I 2025-11-10 18:51:18,609] Trial 132 pruned.

Best trial: 98. Best value: 0.636062:  66%|██████▋   | 133/200 [02:15<00:38,  1.76it/s]

[I 2025-11-10 18:51:19,353] Trial 133 pruned.

Best trial: 98. Best value: 0.636062:  67%|██████▋   | 134/200 [02:19<01:30,  1.37s/it]

[I 2025-11-10 18:51:22,599] Trial 128 finished with value: 0.6230947288006112 and parameters: {'max_depth': 10, 'learning_rate': 0.043747878790695124, 'n_estimators': 711, 'subsample': 0.9933583155724829, 'colsample_bytree': 0.9745442158561606, 'min_child_weight': 8, 'gamma': 1.7390362311428897, 'reg_alpha': 3.52263020514721e-08, 'reg_lambda': 1.5354130542205958e-07, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  68%|██████▊   | 135/200 [02:20<01:23,  1.28s/it]

[I 2025-11-10 18:51:23,670] Trial 134 finished with value: 0.626938884644767 and parameters: {'max_depth': 10, 'learning_rate': 0.06584258663516426, 'n_estimators': 657, 'subsample': 0.9578434685633974, 'colsample_bytree': 0.5459519648941455, 'min_child_weight': 8, 'gamma': 1.257257660593151, 'reg_alpha': 1.2346502279744925e-07, 'reg_lambda': 2.049983494767152e-08, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  68%|██████▊   | 136/200 [02:20<01:07,  1.05s/it]

[I 2025-11-10 18:51:24,192] Trial 135 finished with value: 0.6276447669977082 and parameters: {'max_depth': 10, 'learning_rate': 0.055904458375713874, 'n_estimators': 667, 'subsample': 0.9538461605697046, 'colsample_bytree': 0.5694993833947435, 'min_child_weight': 8, 'gamma': 1.2806923669380008, 'reg_alpha': 4.6747685177351807e-07, 'reg_lambda': 2.850605116943396e-08, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  69%|██████▉   | 138/200 [02:22<00:53,  1.16it/s]

[I 2025-11-10 18:51:25,674] Trial 139 pruned.
[I 2025-11-10 18:51:25,802] Trial 136 finished with value: 0.6339579831932773 and parameters: {'max_depth': 10, 'learning_rate': 0.05640015007022738, 'n_estimators': 788, 'subsample': 0.9544809798222846, 'colsample_bytree': 0.5646424316729081, 'min_child_weight': 8, 'gamma': 1.3188266076266926, 'reg_alpha': 4.4932594357058317e-07, 'reg_lambda': 4.751568119036161e-08, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  70%|██████▉   | 139/200 [02:23<01:01,  1.00s/it]

[I 2025-11-10 18:51:27,126] Trial 141 pruned.

Best trial: 98. Best value: 0.636062:  70%|███████   | 140/200 [02:25<01:18,  1.31s/it]

[I 2025-11-10 18:51:29,168] Trial 138 finished with value: 0.625838808250573 and parameters: {'max_depth': 10, 'learning_rate': 0.0666058614793945, 'n_estimators': 639, 'subsample': 0.9569280943538659, 'colsample_bytree': 0.6583997091208565, 'min_child_weight': 8, 'gamma': 1.2812483243834927, 'reg_alpha': 4.635273942147636e-07, 'reg_lambda': 6.161273683044339e-08, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  70%|███████   | 141/200 [02:26<01:06,  1.13s/it]

[I 2025-11-10 18:51:29,857] Trial 137 finished with value: 0.6280320855614973 and parameters: {'max_depth': 10, 'learning_rate': 0.057625399275547655, 'n_estimators': 855, 'subsample': 0.9558922992919155, 'colsample_bytree': 0.6730316053649795, 'min_child_weight': 8, 'gamma': 1.2761023508260663, 'reg_alpha': 4.2932728088386096e-07, 'reg_lambda': 4.7564663862085144e-08, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  71%|███████   | 142/200 [02:27<01:12,  1.26s/it]

[I 2025-11-10 18:51:31,419] Trial 140 finished with value: 0.6350588235294117 and parameters: {'max_depth': 10, 'learning_rate': 0.06876951629587705, 'n_estimators': 595, 'subsample': 0.958294830558927, 'colsample_bytree': 0.9908481763629416, 'min_child_weight': 8, 'gamma': 1.3821080812568347, 'reg_alpha': 1.0103542539848235e-06, 'reg_lambda': 5.5633959385450135e-08, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  72%|███████▏  | 143/200 [02:28<01:00,  1.05s/it]

[I 2025-11-10 18:51:31,995] Trial 142 finished with value: 0.6185294117647059 and parameters: {'max_depth': 9, 'learning_rate': 0.03783854684196134, 'n_estimators': 597, 'subsample': 0.8759647422765767, 'colsample_bytree': 0.5669972881309701, 'min_child_weight': 8, 'gamma': 1.4897711539800438, 'reg_alpha': 3.3982068573818474e-07, 'reg_lambda': 0.0017299335482908766, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  72%|███████▏  | 144/200 [02:32<01:55,  2.07s/it]

[I 2025-11-10 18:51:36,426] Trial 144 finished with value: 0.6266959511077157 and parameters: {'max_depth': 9, 'learning_rate': 0.04678020104698694, 'n_estimators': 830, 'subsample': 0.9372254463620212, 'colsample_bytree': 0.5238164942301318, 'min_child_weight': 8, 'gamma': 1.4442496628626706, 'reg_alpha': 8.744344494474944e-07, 'reg_lambda': 3.2283292221048663e-07, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  72%|███████▎  | 145/200 [02:33<01:25,  1.56s/it]

[I 2025-11-10 18:51:36,812] Trial 145 finished with value: 0.633327731092437 and parameters: {'max_depth': 9, 'learning_rate': 0.039251857823105134, 'n_estimators': 610, 'subsample': 0.936900158884205, 'colsample_bytree': 0.5854241125970373, 'min_child_weight': 8, 'gamma': 1.4923469156562317, 'reg_alpha': 9.78074102321614e-07, 'reg_lambda': 2.2919952184882016e-07, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 98. Best value: 0.636062:  73%|███████▎  | 146/200 [02:34<01:11,  1.32s/it]

[I 2025-11-10 18:51:37,554] Trial 147 pruned.
[I 2025-11-10 18:51:37,595] Trial 146 finished with value: 0.6332597402597402 and parameters: {'max_depth': 10, 'learning_rate': 0.04621281636099252, 'n_estimators': 663, 'subsample': 0.9310261464704582, 'colsample_bytree': 0.5332337981824797, 'min_child_weight': 8, 'gamma': 1.3837026088051674, 'reg_alpha': 1.8206577027687354e-06, 'reg_lambda': 1.451100716996161e-08, 'max_delta_step': 0}. Best is trial 98 with value: 0.6360618792971733.

Best trial: 143. Best value: 0.638954:  74%|███████▍  | 149/200 [02:34<00:32,  1.57it/s]

[I 2025-11-10 18:51:37,901] Trial 143 finished with value: 0.6389541634835753 and parameters: {'max_depth': 9, 'learning_rate': 0.046198936538622073, 'n_estimators': 895, 'subsample': 0.9351229463439332, 'colsample_bytree': 0.9880717049655129, 'min_child_weight': 8, 'gamma': 1.4272334840006256, 'reg_alpha': 2.5964908128194357e-07, 'reg_lambda': 0.0014791725430823295, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.
[I 2025-11-10 18:51:38,074] Trial 148 pruned.

Best trial: 143. Best value: 0.638954:  75%|███████▌  | 150/200 [02:35<00:30,  1.65it/s]

[I 2025-11-10 18:51:38,601] Trial 150 pruned.

Best trial: 143. Best value: 0.638954:  76%|███████▌  | 151/200 [02:35<00:24,  2.03it/s]

[I 2025-11-10 18:51:38,790] Trial 149 pruned.

Best trial: 143. Best value: 0.638954:  76%|███████▌  | 152/200 [02:35<00:23,  2.01it/s]

[I 2025-11-10 18:51:39,299] Trial 151 pruned.
[I 2025-11-10 18:51:39,318] Trial 152 pruned.

Best trial: 143. Best value: 0.638954:  77%|███████▋  | 154/200 [02:36<00:21,  2.11it/s]

[I 2025-11-10 18:51:40,187] Trial 153 pruned.

Best trial: 143. Best value: 0.638954:  78%|███████▊  | 155/200 [02:37<00:20,  2.17it/s]

[I 2025-11-10 18:51:40,612] Trial 156 pruned.

Best trial: 143. Best value: 0.638954:  78%|███████▊  | 156/200 [02:37<00:19,  2.28it/s]

[I 2025-11-10 18:51:40,982] Trial 155 pruned.

Best trial: 143. Best value: 0.638954:  78%|███████▊  | 157/200 [02:38<00:26,  1.64it/s]

[I 2025-11-10 18:51:42,054] Trial 159 pruned.

Best trial: 143. Best value: 0.638954:  79%|███████▉  | 158/200 [02:38<00:24,  1.74it/s]

[I 2025-11-10 18:51:42,536] Trial 160 pruned.

Best trial: 143. Best value: 0.638954:  80%|███████▉  | 159/200 [02:39<00:21,  1.88it/s]

[I 2025-11-10 18:51:42,964] Trial 157 finished with value: 0.6123170359052713 and parameters: {'max_depth': 9, 'learning_rate': 0.026267360285761737, 'n_estimators': 234, 'subsample': 0.932937477635468, 'colsample_bytree': 0.5126000793127736, 'min_child_weight': 8, 'gamma': 1.459264203579644, 'reg_alpha': 2.7689996763790275e-06, 'reg_lambda': 0.0005706874986445299, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.

Best trial: 143. Best value: 0.638954:  80%|████████  | 160/200 [02:43<01:03,  1.59s/it]

[I 2025-11-10 18:51:47,185] Trial 154 finished with value: 0.6264820473644003 and parameters: {'max_depth': 10, 'learning_rate': 0.041581097118860565, 'n_estimators': 894, 'subsample': 0.9282325247556746, 'colsample_bytree': 0.98944742437086, 'min_child_weight': 8, 'gamma': 1.6686416636127068, 'reg_alpha': 2.5903251648753224e-06, 'reg_lambda': 0.0004693100367734219, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.

Best trial: 143. Best value: 0.638954:  81%|████████  | 162/200 [02:45<00:43,  1.14s/it]

[I 2025-11-10 18:51:48,692] Trial 163 pruned.
[I 2025-11-10 18:51:48,798] Trial 158 finished with value: 0.6236508785332315 and parameters: {'max_depth': 9, 'learning_rate': 0.02497302706372909, 'n_estimators': 775, 'subsample': 0.9322858456516714, 'colsample_bytree': 0.9867953836061765, 'min_child_weight': 8, 'gamma': 1.5136790827176931, 'reg_alpha': 0.005253349226737332, 'reg_lambda': 1.2836793125998153e-07, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.

Best trial: 143. Best value: 0.638954:  82%|████████▏ | 163/200 [02:46<00:39,  1.06s/it]

[I 2025-11-10 18:51:49,670] Trial 162 finished with value: 0.6235477463712757 and parameters: {'max_depth': 8, 'learning_rate': 0.06875777327655917, 'n_estimators': 857, 'subsample': 0.919544143824619, 'colsample_bytree': 0.6298923317708469, 'min_child_weight': 8, 'gamma': 1.7851317462358012, 'reg_alpha': 0.005145766495746535, 'reg_lambda': 3.62552967131954e-05, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.

Best trial: 143. Best value: 0.638954:  82%|████████▏ | 164/200 [02:46<00:35,  1.02it/s]

[I 2025-11-10 18:51:50,473] Trial 161 finished with value: 0.624885408708938 and parameters: {'max_depth': 8, 'learning_rate': 0.025089594500685763, 'n_estimators': 780, 'subsample': 0.9334681911139128, 'colsample_bytree': 0.8701642976733153, 'min_child_weight': 8, 'gamma': 1.4900173760070314, 'reg_alpha': 1.2623721781105086e-05, 'reg_lambda': 4.655146735426513e-06, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.

Best trial: 143. Best value: 0.638954:  82%|████████▎ | 165/200 [02:47<00:26,  1.32it/s]

[I 2025-11-10 18:51:50,708] Trial 165 pruned.

Best trial: 143. Best value: 0.638954:  83%|████████▎ | 166/200 [02:47<00:21,  1.57it/s]

[I 2025-11-10 18:51:51,050] Trial 166 pruned.

Best trial: 143. Best value: 0.638954:  84%|████████▎ | 167/200 [02:48<00:20,  1.64it/s]

[I 2025-11-10 18:51:51,594] Trial 167 pruned.

Best trial: 143. Best value: 0.638954:  84%|████████▍ | 168/200 [02:48<00:16,  1.90it/s]

[I 2025-11-10 18:51:51,926] Trial 169 pruned.

Best trial: 143. Best value: 0.638954:  84%|████████▍ | 169/200 [02:50<00:27,  1.13it/s]

[I 2025-11-10 18:51:53,645] Trial 171 pruned.

Best trial: 143. Best value: 0.638954:  85%|████████▌ | 170/200 [02:50<00:23,  1.29it/s]

[I 2025-11-10 18:51:54,178] Trial 164 finished with value: 0.6216516424751719 and parameters: {'max_depth': 10, 'learning_rate': 0.051111117192660566, 'n_estimators': 629, 'subsample': 0.9465320100619272, 'colsample_bytree': 0.501734659338577, 'min_child_weight': 8, 'gamma': 1.2740984516686606, 'reg_alpha': 4.7629051567369803e-07, 'reg_lambda': 3.13127132169701e-08, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.

Best trial: 143. Best value: 0.638954:  86%|████████▌ | 171/200 [02:51<00:21,  1.33it/s]

[I 2025-11-10 18:51:54,868] Trial 172 pruned.

Best trial: 143. Best value: 0.638954:  86%|████████▌ | 172/200 [02:51<00:18,  1.48it/s]

[I 2025-11-10 18:51:55,358] Trial 173 pruned.

Best trial: 143. Best value: 0.638954:  87%|████████▋ | 174/200 [02:52<00:10,  2.38it/s]

[I 2025-11-10 18:51:55,619] Trial 168 finished with value: 0.6208999236058059 and parameters: {'max_depth': 10, 'learning_rate': 0.17896101456562483, 'n_estimators': 618, 'subsample': 0.9658056912190385, 'colsample_bytree': 0.57966680038553, 'min_child_weight': 8, 'gamma': 1.3411295869394426, 'reg_alpha': 4.1499141220049617e-07, 'reg_lambda': 3.435469200164301e-08, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.
[I 2025-11-10 18:51:55,739] Trial 170 finished with value: 0.6258556149732619 and parameters: {'max_depth': 10, 'learning_rate': 0.05547430016224291, 'n_estimators': 476, 'subsample': 0.9625085113621401, 'colsample_bytree': 0.5796234272253041, 'min_child_weight': 8, 'gamma': 1.5832246488301998, 'reg_alpha': 3.384407573615644e-07, 'reg_lambda': 1.55928258545585e-08, 'max_delta_step': 4}. Best is trial 143 with value: 0.6389541634835753.

Best trial: 143. Best value: 0.638954:  88%|████████▊ | 175/200 [02:53<00:16,  1.48it/s]

[I 2025-11-10 18:51:57,007] Trial 177 pruned.
[I 2025-11-10 18:51:57,017] Trial 176 pruned.

Best trial: 143. Best value: 0.638954:  88%|████████▊ | 177/200 [02:56<00:25,  1.09s/it]

[I 2025-11-10 18:52:00,178] Trial 178 finished with value: 0.615411000763942 and parameters: {'max_depth': 9, 'learning_rate': 0.06127356758844895, 'n_estimators': 295, 'subsample': 0.9559750604871119, 'colsample_bytree': 0.9981120300863917, 'min_child_weight': 8, 'gamma': 1.6973059345981545, 'reg_alpha': 7.089879939948086e-07, 'reg_lambda': 0.0012054407419098193, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.

Best trial: 143. Best value: 0.638954:  89%|████████▉ | 178/200 [02:57<00:21,  1.01it/s]

[I 2025-11-10 18:52:00,861] Trial 174 finished with value: 0.62622230710466 and parameters: {'max_depth': 9, 'learning_rate': 0.13140326802220928, 'n_estimators': 665, 'subsample': 0.9597430321515619, 'colsample_bytree': 0.9991049381120576, 'min_child_weight': 8, 'gamma': 2.006568234444577, 'reg_alpha': 7.263291020152275e-07, 'reg_lambda': 0.0026348111796877112, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.

Best trial: 143. Best value: 0.638954:  90%|████████▉ | 179/200 [02:57<00:18,  1.17it/s]

[I 2025-11-10 18:52:01,338] Trial 180 pruned.

Best trial: 143. Best value: 0.638954:  90%|█████████ | 180/200 [02:58<00:18,  1.09it/s]

[I 2025-11-10 18:52:02,424] Trial 175 finished with value: 0.6344178762414056 and parameters: {'max_depth': 9, 'learning_rate': 0.15229198889091403, 'n_estimators': 806, 'subsample': 0.9597560265275015, 'colsample_bytree': 0.9958556541198421, 'min_child_weight': 8, 'gamma': 1.991768727674657, 'reg_alpha': 6.162322420474542e-07, 'reg_lambda': 0.0007744907426361135, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.

Best trial: 143. Best value: 0.638954:  91%|█████████ | 182/200 [02:59<00:10,  1.77it/s]

[I 2025-11-10 18:52:02,706] Trial 179 finished with value: 0.6226050420168068 and parameters: {'max_depth': 9, 'learning_rate': 0.14650885970540167, 'n_estimators': 670, 'subsample': 0.8876068505704978, 'colsample_bytree': 0.9989084762681558, 'min_child_weight': 8, 'gamma': 1.7018808814563804, 'reg_alpha': 6.972079426015143e-07, 'reg_lambda': 0.0008556816951022857, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.
[I 2025-11-10 18:52:02,832] Trial 182 pruned.

Best trial: 143. Best value: 0.638954:  92%|█████████▏| 183/200 [03:00<00:11,  1.48it/s]

[I 2025-11-10 18:52:03,775] Trial 183 pruned.

Best trial: 143. Best value: 0.638954:  92%|█████████▏| 184/200 [03:01<00:13,  1.17it/s]

[I 2025-11-10 18:52:05,054] Trial 186 pruned.

Best trial: 143. Best value: 0.638954:  92%|█████████▎| 185/200 [03:02<00:15,  1.02s/it]

[I 2025-11-10 18:52:06,461] Trial 187 pruned.

Best trial: 143. Best value: 0.638954:  93%|█████████▎| 186/200 [03:03<00:11,  1.19it/s]

[I 2025-11-10 18:52:06,891] Trial 181 finished with value: 0.622881588999236 and parameters: {'max_depth': 10, 'learning_rate': 0.14994219816788748, 'n_estimators': 813, 'subsample': 0.8043872831530634, 'colsample_bytree': 0.9686452671773464, 'min_child_weight': 8, 'gamma': 1.840159349016913, 'reg_alpha': 6.106282367799641e-06, 'reg_lambda': 0.0007738118725111664, 'max_delta_step': 3}. Best is trial 143 with value: 0.6389541634835753.

Best trial: 143. Best value: 0.638954:  94%|█████████▎| 187/200 [03:04<00:13,  1.05s/it]

[I 2025-11-10 18:52:08,433] Trial 189 pruned.

Best trial: 143. Best value: 0.638954:  94%|█████████▍| 188/200 [03:05<00:12,  1.04s/it]

[I 2025-11-10 18:52:09,445] Trial 185 finished with value: 0.6299809014514895 and parameters: {'max_depth': 9, 'learning_rate': 0.1625615696967387, 'n_estimators': 798, 'subsample': 0.9422906268919213, 'colsample_bytree': 0.9792889452502662, 'min_child_weight': 8, 'gamma': 1.8932040095946694, 'reg_alpha': 4.970315617376212e-06, 'reg_lambda': 0.0022453887506359506, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.

Best trial: 143. Best value: 0.638954:  94%|█████████▍| 189/200 [03:06<00:08,  1.23it/s]

[I 2025-11-10 18:52:09,723] Trial 184 finished with value: 0.6256653934300993 and parameters: {'max_depth': 10, 'learning_rate': 0.09821169839670882, 'n_estimators': 799, 'subsample': 0.9766293814845555, 'colsample_bytree': 0.9852849277438235, 'min_child_weight': 8, 'gamma': 1.9026183019310623, 'reg_alpha': 2.3686363570756352e-07, 'reg_lambda': 0.001899450178066622, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.

Best trial: 143. Best value: 0.638954:  95%|█████████▌| 190/200 [03:09<00:15,  1.57s/it]

[I 2025-11-10 18:52:13,086] Trial 192 finished with value: 0.6259511077158136 and parameters: {'max_depth': 10, 'learning_rate': 0.047072296550569874, 'n_estimators': 321, 'subsample': 0.9128315926035839, 'colsample_bytree': 0.9481209066254895, 'min_child_weight': 8, 'gamma': 1.6185712502240528, 'reg_alpha': 4.841833720008809e-06, 'reg_lambda': 5.348815280203214e-08, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.

Best trial: 143. Best value: 0.638954:  96%|█████████▌| 192/200 [03:11<00:13,  1.63s/it]

[I 2025-11-10 18:52:14,846] Trial 193 pruned.
[I 2025-11-10 18:52:14,864] Trial 188 finished with value: 0.6227532467532468 and parameters: {'max_depth': 9, 'learning_rate': 0.07037321000772907, 'n_estimators': 945, 'subsample': 0.97142249296867, 'colsample_bytree': 0.9819465634344032, 'min_child_weight': 8, 'gamma': 1.5118615482493976, 'reg_alpha': 2.832636034821417e-07, 'reg_lambda': 0.001632242734661961, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.
[I 2025-11-10 18:52:15,020] Trial 190 finished with value: 0.6266195569136747 and parameters: {'max_depth': 10, 'learning_rate': 0.06959853034685448, 'n_estimators': 728, 'subsample': 0.9526884160021492, 'colsample_bytree': 0.9847284637633639, 'min_child_weight': 8, 'gamma': 1.6005391126650064, 'reg_alpha': 1.2603459544666185e-06, 'reg_lambda': 0.0013144779568744062, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.

Best trial: 143. Best value: 0.638954:  97%|█████████▋| 194/200 [03:11<00:04,  1.36it/s]

[I 2025-11-10 18:52:15,200] Trial 191 finished with value: 0.6152994652406416 and parameters: {'max_depth': 10, 'learning_rate': 0.2315086430345505, 'n_estimators': 800, 'subsample': 0.941073897012014, 'colsample_bytree': 0.5548094416082131, 'min_child_weight': 8, 'gamma': 2.1611500147982388, 'reg_alpha': 0.0027899826389363724, 'reg_lambda': 5.2258984082745166e-08, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.

Best trial: 143. Best value: 0.638954:  98%|█████████▊| 195/200 [03:12<00:04,  1.22it/s]

[I 2025-11-10 18:52:16,247] Trial 195 pruned.

Best trial: 143. Best value: 0.638954:  98%|█████████▊| 196/200 [03:14<00:03,  1.03it/s]

[I 2025-11-10 18:52:17,642] Trial 198 pruned.

Best trial: 143. Best value: 0.638954:  98%|█████████▊| 197/200 [03:17<00:04,  1.57s/it]

[I 2025-11-10 18:52:20,740] Trial 197 finished with value: 0.6204789915966387 and parameters: {'max_depth': 9, 'learning_rate': 0.1884766309033174, 'n_estimators': 776, 'subsample': 0.9520604611214079, 'colsample_bytree': 0.6172368191691012, 'min_child_weight': 8, 'gamma': 1.7369408291105037, 'reg_alpha': 4.251922801261273e-07, 'reg_lambda': 0.0038485291591987877, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.

Best trial: 143. Best value: 0.638954:  99%|█████████▉| 198/200 [03:17<00:02,  1.24s/it]

[I 2025-11-10 18:52:21,167] Trial 196 finished with value: 0.6354430863254393 and parameters: {'max_depth': 9, 'learning_rate': 0.13863757188509462, 'n_estimators': 764, 'subsample': 0.9393517416772853, 'colsample_bytree': 0.9945033067334101, 'min_child_weight': 8, 'gamma': 2.005747514393582, 'reg_alpha': 0.002786054071976881, 'reg_lambda': 0.005176575964650394, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.
[I 2025-11-10 18:52:21,215] Trial 194 finished with value: 0.6337746371275783 and parameters: {'max_depth': 9, 'learning_rate': 0.1392085206646494, 'n_estimators': 736, 'subsample': 0.9546042902026338, 'colsample_bytree': 0.9927013649170121, 'min_child_weight': 8, 'gamma': 2.0937993651147626, 'reg_alpha': 0.0025698134060935405, 'reg_lambda': 0.0013243781113313298, 'max_delta_step': 0}. Best is trial 143 with value: 0.6389541634835753.

Best trial: 143. Best value: 0.638954: 100%|██████████| 200/200 [03:18<00:00,  1.01it/s]

[I 2025-11-10 18:52:22,189] Trial 199 finished with value: 0.6170488922841864 and parameters: {'max_depth': 9, 'learning_rate': 0.12286417071404075, 'n_estimators': 774, 'subsample': 0.9343513397326384, 'colsample_bytree': 0.6172805428432929, 'min_child_weight': 8, 'gamma': 1.9896415691702654, 'reg_alpha': 8.225296911106178e-07, 'reg_lambda': 0.007172044980243618, 'max_delta_step': 1}. Best is trial 143 with value: 0.6389541634835753.

[I 2025-11-10 18:52:23,557] A new study created in memory with name: 10_1_roc_auc
Best trial: 1. Best value: 0.5:   0%|          | 1/200 [00:03<11:30,  3.47s/it]

[I 2025-11-10 18:52:27,028] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.14970950827307666, 'n_estimators': 864, 'subsample': 0.6991120436322217, 'colsample_bytree': 0.9907918511859777, 'min_child_weight': 7, 'gamma': 4.702834025954622, 'reg_alpha': 0.0003084334348832327, 'reg_lambda': 1.4464824966194899e-05, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   1%|          | 2/200 [00:04<06:25,  1.95s/it]

[I 2025-11-10 18:52:27,895] Trial 3 finished with value: 0.45816764132553606 and parameters: {'max_depth': 5, 'learning_rate': 0.1929420061035418, 'n_estimators': 791, 'subsample': 0.8963056838577739, 'colsample_bytree': 0.7472108008336307, 'min_child_weight': 2, 'gamma': 2.6299499578296706, 'reg_alpha': 0.0007934527318103367, 'reg_lambda': 1.8524489506516078e-06, 'max_delta_step': 9}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   2%|▏         | 3/200 [00:04<04:26,  1.35s/it]

[I 2025-11-10 18:52:28,542] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07432289550709324, 'n_estimators': 1405, 'subsample': 0.9718581255850458, 'colsample_bytree': 0.5305151366707543, 'min_child_weight': 10, 'gamma': 0.7862066584091049, 'reg_alpha': 9.370348028963006, 'reg_lambda': 4.0169968350601824e-07, 'max_delta_step': 10}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   2%|▏         | 4/200 [00:05<03:29,  1.07s/it]

[I 2025-11-10 18:52:29,184] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.020115038138316277, 'n_estimators': 304, 'subsample': 0.7047424918296714, 'colsample_bytree': 0.9103825154568621, 'min_child_weight': 10, 'gamma': 2.067911826310006, 'reg_alpha': 0.00030159447630747596, 'reg_lambda': 1.028247243894346e-05, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 0. Best value: 0.549181:   2%|▎         | 5/200 [00:07<04:12,  1.30s/it]

[I 2025-11-10 18:52:30,880] Trial 0 finished with value: 0.5491812865497077 and parameters: {'max_depth': 5, 'learning_rate': 0.015585969684681776, 'n_estimators': 1107, 'subsample': 0.9632548042524494, 'colsample_bytree': 0.9561615418732512, 'min_child_weight': 4, 'gamma': 0.07763747054969239, 'reg_alpha': 0.02314111975439079, 'reg_lambda': 1.6952203448704404e-07, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:   3%|▎         | 6/200 [00:08<03:32,  1.10s/it]

[I 2025-11-10 18:52:31,593] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.0589982281619981, 'n_estimators': 1215, 'subsample': 0.6382790712071047, 'colsample_bytree': 0.6116250608776366, 'min_child_weight': 10, 'gamma': 4.035548382749294, 'reg_alpha': 7.0962755508714e-06, 'reg_lambda': 0.00019293484363442436, 'max_delta_step': 7}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:   4%|▎         | 7/200 [00:08<03:01,  1.06it/s]

[I 2025-11-10 18:52:32,223] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.047433306252363944, 'n_estimators': 910, 'subsample': 0.6592928553190193, 'colsample_bytree': 0.9246049330058855, 'min_child_weight': 6, 'gamma': 0.554854874771919, 'reg_alpha': 0.0017423197640903383, 'reg_lambda': 1.125966174564792, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:   4%|▍         | 8/200 [00:09<02:42,  1.18it/s]

[I 2025-11-10 18:52:32,863] Trial 9 finished with value: 0.472046783625731 and parameters: {'max_depth': 3, 'learning_rate': 0.12963197843593788, 'n_estimators': 264, 'subsample': 0.8128624849065964, 'colsample_bytree': 0.6006435912744508, 'min_child_weight': 3, 'gamma': 3.677183729713886, 'reg_alpha': 7.551574028112602e-08, 'reg_lambda': 3.9964075182637664e-07, 'max_delta_step': 9}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:   4%|▍         | 9/200 [00:10<03:18,  1.04s/it]

[I 2025-11-10 18:52:34,310] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.12672963083308733, 'n_estimators': 1302, 'subsample': 0.8819278852246968, 'colsample_bytree': 0.912396812741098, 'min_child_weight': 6, 'gamma': 2.920883206629022, 'reg_alpha': 1.1584422140217783e-06, 'reg_lambda': 2.3053289852821252e-07, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:52:34,359] Trial 11 finished with value: 0.49000000000000005 and parameters: {'max_depth': 9, 'learning_rate': 0.0610855150563513, 'n_estimators': 379, 'subsample': 0.8981413129302752, 'colsample_bytree': 0.5194271590982088, 'min_child_weight': 5, 'gamma': 4.605293503196324, 'reg_alpha': 0.023651584288603936, 'reg_lambda': 2.7428394344021636e-07, 'max_delta_step': 1}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:   6%|▌         | 11/200 [00:11<02:14,  1.41it/s]

[I 2025-11-10 18:52:34,998] Trial 12 pruned.

Best trial: 0. Best value: 0.549181:   6%|▌         | 12/200 [00:11<02:01,  1.55it/s]

[I 2025-11-10 18:52:35,451] Trial 8 pruned.

Best trial: 0. Best value: 0.549181:   6%|▋         | 13/200 [00:13<02:57,  1.05it/s]

[I 2025-11-10 18:52:37,251] Trial 13 pruned.

Best trial: 0. Best value: 0.549181:   7%|▋         | 14/200 [00:13<02:21,  1.32it/s]

[I 2025-11-10 18:52:37,509] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09034723365054205, 'n_estimators': 1413, 'subsample': 0.8430790064257533, 'colsample_bytree': 0.7847419050162463, 'min_child_weight': 8, 'gamma': 2.737945972889137, 'reg_alpha': 0.00013344355067162645, 'reg_lambda': 0.000269216946460402, 'max_delta_step': 9}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:   8%|▊         | 15/200 [00:14<02:18,  1.34it/s]

[I 2025-11-10 18:52:38,222] Trial 17 pruned.

Best trial: 0. Best value: 0.549181:   8%|▊         | 16/200 [00:15<02:28,  1.24it/s]

[I 2025-11-10 18:52:39,166] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.011167383137448514, 'n_estimators': 1030, 'subsample': 0.5859026857069791, 'colsample_bytree': 0.9967163406382147, 'min_child_weight': 8, 'gamma': 0.11406744761392407, 'reg_alpha': 0.12691776878024788, 'reg_lambda': 0.004446911933289155, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:   8%|▊         | 17/200 [00:16<02:23,  1.27it/s]

[I 2025-11-10 18:52:39,912] Trial 15 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.028960631306747357, 'n_estimators': 1082, 'subsample': 0.783603947857839, 'colsample_bytree': 0.9945839430186986, 'min_child_weight': 8, 'gamma': 1.2009267279973024, 'reg_alpha': 0.5107027792211783, 'reg_lambda': 0.00010905125670437072, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:   9%|▉         | 18/200 [00:16<02:04,  1.46it/s]

[I 2025-11-10 18:52:40,353] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.031276279319503233, 'n_estimators': 721, 'subsample': 0.768265366944423, 'colsample_bytree': 0.993191770526781, 'min_child_weight': 8, 'gamma': 1.370384419935832, 'reg_alpha': 1.93507536949575e-05, 'reg_lambda': 1.1219062549082225e-08, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  10%|▉         | 19/200 [00:17<01:53,  1.60it/s]

[I 2025-11-10 18:52:40,836] Trial 18 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.24746224825164279, 'n_estimators': 596, 'subsample': 0.5573636902624134, 'colsample_bytree': 0.9909731225675588, 'min_child_weight': 8, 'gamma': 4.863118946041271, 'reg_alpha': 2.517326013514022e-05, 'reg_lambda': 1.8397977863780584e-05, 'max_delta_step': 4}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  10%|█         | 20/200 [00:18<01:59,  1.50it/s]

[I 2025-11-10 18:52:41,594] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.209989369959969, 'n_estimators': 560, 'subsample': 0.7513256340021043, 'colsample_bytree': 0.8536705056057426, 'min_child_weight': 7, 'gamma': 4.887115246668773, 'reg_alpha': 5.6226617129773147e-05, 'reg_lambda': 1.3308997616034535e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  10%|█         | 21/200 [00:18<02:03,  1.45it/s]

[I 2025-11-10 18:52:42,344] Trial 23 pruned.

Best trial: 0. Best value: 0.549181:  11%|█         | 22/200 [00:19<01:44,  1.70it/s]

[I 2025-11-10 18:52:42,699] Trial 21 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2821952323070474, 'n_estimators': 535, 'subsample': 0.7035814755412442, 'colsample_bytree': 0.8451672784073573, 'min_child_weight': 5, 'gamma': 3.5520966700849343, 'reg_alpha': 2.78827680850161e-05, 'reg_lambda': 1.160306795848786e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:52:42,725] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.29060755639692004, 'n_estimators': 658, 'subsample': 0.7094437569549459, 'colsample_bytree': 0.8455281169319873, 'min_child_weight': 5, 'gamma': 4.831993830634338, 'reg_alpha': 3.24167886277267e-05, 'reg_lambda': 1.4198006222668173e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  12%|█▏        | 24/200 [00:21<02:33,  1.14it/s]

[I 2025-11-10 18:52:45,112] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2725475676452322, 'n_estimators': 940, 'subsample': 0.7114360934143418, 'colsample_bytree': 0.8528570953631119, 'min_child_weight': 5, 'gamma': 3.330788237065442, 'reg_alpha': 0.01094097742763323, 'reg_lambda': 1.1841768053001756e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  13%|█▎        | 26/200 [00:25<03:21,  1.16s/it]

[I 2025-11-10 18:52:48,592] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.11883722926214395, 'n_estimators': 1434, 'subsample': 0.9454346991763363, 'colsample_bytree': 0.5229802301850879, 'min_child_weight': 9, 'gamma': 0.7286881016605236, 'reg_alpha': 2.1783315755167156, 'reg_lambda': 7.884008564185311e-07, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:52:48,735] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.13248656080173432, 'n_estimators': 1486, 'subsample': 0.9403071345864878, 'colsample_bytree': 0.6616807935202539, 'min_child_weight': 5, 'gamma': 0.8217929419430999, 'reg_alpha': 5.786846809378287, 'reg_lambda': 7.457599036936565e-08, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  14%|█▎        | 27/200 [00:25<02:40,  1.08it/s]

[I 2025-11-10 18:52:49,038] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.13523689024835622, 'n_estimators': 1482, 'subsample': 0.9352144613458504, 'colsample_bytree': 0.6846334287547846, 'min_child_weight': 9, 'gamma': 0.49195423460874077, 'reg_alpha': 7.3096049457871475, 'reg_lambda': 8.851445091344466e-08, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  14%|█▍        | 28/200 [00:26<02:50,  1.01it/s]

[I 2025-11-10 18:52:50,196] Trial 30 pruned.

Best trial: 0. Best value: 0.549181:  14%|█▍        | 29/200 [00:27<02:56,  1.03s/it]

[I 2025-11-10 18:52:51,323] Trial 27 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.13625092972177222, 'n_estimators': 1494, 'subsample': 0.9268426453723724, 'colsample_bytree': 0.689262164342255, 'min_child_weight': 9, 'gamma': 0.7077324598816933, 'reg_alpha': 4.40636040962464, 'reg_lambda': 1.573031173126347e-06, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  15%|█▌        | 30/200 [00:30<04:36,  1.63s/it]

[I 2025-11-10 18:52:54,421] Trial 29 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.08366265223856653, 'n_estimators': 1200, 'subsample': 0.9411984004099263, 'colsample_bytree': 0.6743530358841017, 'min_child_weight': 3, 'gamma': 0.40462433264042674, 'reg_alpha': 7.525909987593384, 'reg_lambda': 3.1970502863641663e-06, 'max_delta_step': 0}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  16%|█▌        | 31/200 [00:31<03:25,  1.22s/it]

[I 2025-11-10 18:52:54,647] Trial 28 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.1640969183045305, 'n_estimators': 1254, 'subsample': 0.9431078993579856, 'colsample_bytree': 0.6894153499779142, 'min_child_weight': 3, 'gamma': 0.5949326428393156, 'reg_alpha': 4.526869365791953, 'reg_lambda': 9.018746721503641e-08, 'max_delta_step': 0}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  16%|█▌        | 32/200 [00:32<03:19,  1.19s/it]

[I 2025-11-10 18:52:55,762] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.17574860262879985, 'n_estimators': 1332, 'subsample': 0.6481203236608888, 'colsample_bytree': 0.9464701604340191, 'min_child_weight': 7, 'gamma': 1.015684263380026, 'reg_alpha': 3.0809911899856773e-06, 'reg_lambda': 2.062786202957521e-05, 'max_delta_step': 8}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  16%|█▋        | 33/200 [00:32<02:44,  1.01it/s]

[I 2025-11-10 18:52:56,271] Trial 32 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.18383754900622168, 'n_estimators': 1165, 'subsample': 0.8820454699071908, 'colsample_bytree': 0.9466207545326004, 'min_child_weight': 7, 'gamma': 4.269084658043468, 'reg_alpha': 0.0007977076834168805, 'reg_lambda': 5.644283850342681e-05, 'max_delta_step': 0}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  17%|█▋        | 34/200 [00:35<04:36,  1.67s/it]

[I 2025-11-10 18:52:59,547] Trial 33 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1704183263885647, 'n_estimators': 1136, 'subsample': 0.8754068955164478, 'colsample_bytree': 0.8852115548043216, 'min_child_weight': 7, 'gamma': 4.237124797731241, 'reg_alpha': 0.0010513833940973365, 'reg_lambda': 2.127639761588849e-05, 'max_delta_step': 8}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  18%|█▊        | 35/200 [00:36<03:46,  1.37s/it]

[I 2025-11-10 18:53:00,226] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.0586755170933699, 'n_estimators': 1353, 'subsample': 0.6376526426639499, 'colsample_bytree': 0.5597673926890587, 'min_child_weight': 10, 'gamma': 4.241341131912373, 'reg_alpha': 4.066667631923822e-06, 'reg_lambda': 5.565019127284926e-05, 'max_delta_step': 8}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  18%|█▊        | 36/200 [00:37<03:02,  1.11s/it]

[I 2025-11-10 18:53:00,721] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.060895486574750815, 'n_estimators': 1168, 'subsample': 0.6129322806173125, 'colsample_bytree': 0.5991989942459974, 'min_child_weight': 10, 'gamma': 4.335142800755998, 'reg_alpha': 0.0007202672389762959, 'reg_lambda': 6.710914227916166e-05, 'max_delta_step': 7}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  18%|█▊        | 37/200 [00:38<03:05,  1.14s/it]

[I 2025-11-10 18:53:01,924] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.055486650085774886, 'n_estimators': 1331, 'subsample': 0.6342671365292903, 'colsample_bytree': 0.6010593121162984, 'min_child_weight': 10, 'gamma': 4.146500576568977, 'reg_alpha': 1.5063236515263166e-06, 'reg_lambda': 0.0029731424006313963, 'max_delta_step': 7}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  19%|█▉        | 38/200 [00:40<03:48,  1.41s/it]

[I 2025-11-10 18:53:03,979] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.04378399529602534, 'n_estimators': 914, 'subsample': 0.6082253194263407, 'colsample_bytree': 0.6235044716513315, 'min_child_weight': 10, 'gamma': 4.005004707058177, 'reg_alpha': 0.0002202235121168007, 'reg_lambda': 0.0010853515223131233, 'max_delta_step': 7}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  20%|█▉        | 39/200 [00:41<03:15,  1.21s/it]

[I 2025-11-10 18:53:04,726] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.040072802826515735, 'n_estimators': 979, 'subsample': 0.6828214457091002, 'colsample_bytree': 0.6336045985758918, 'min_child_weight': 10, 'gamma': 3.924036633039086, 'reg_alpha': 5.718996420964734e-07, 'reg_lambda': 0.000934948101389353, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  20%|██        | 40/200 [00:41<02:31,  1.05it/s]

[I 2025-11-10 18:53:05,053] Trial 37 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.06212917407038681, 'n_estimators': 1356, 'subsample': 0.6204842002388731, 'colsample_bytree': 0.605989148494922, 'min_child_weight': 10, 'gamma': 4.173086903817622, 'reg_alpha': 1.9812566585391353e-06, 'reg_lambda': 0.0023585532004534943, 'max_delta_step': 7}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  20%|██        | 41/200 [00:42<02:25,  1.10it/s]

[I 2025-11-10 18:53:05,886] Trial 40 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.043615691381662554, 'n_estimators': 944, 'subsample': 0.6856335254843577, 'colsample_bytree': 0.6360657804739898, 'min_child_weight': 6, 'gamma': 3.906348157845606, 'reg_alpha': 1.1730811698886107e-07, 'reg_lambda': 0.0014233335201538592, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  21%|██        | 42/200 [00:43<02:41,  1.02s/it]

[I 2025-11-10 18:53:07,169] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01879518420026891, 'n_estimators': 255, 'subsample': 0.7282289878246815, 'colsample_bytree': 0.9032093135672596, 'min_child_weight': 9, 'gamma': 2.427062118565691, 'reg_alpha': 0.002734851742480321, 'reg_lambda': 7.263736112737256e-06, 'max_delta_step': 9}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  22%|██▏       | 43/200 [00:44<02:45,  1.05s/it]

[I 2025-11-10 18:53:08,288] Trial 41 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01971244222743345, 'n_estimators': 1009, 'subsample': 0.6753610613550556, 'colsample_bytree': 0.545953260580456, 'min_child_weight': 6, 'gamma': 2.310385237371214, 'reg_alpha': 1.724534630219875e-07, 'reg_lambda': 0.00045434657340784855, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  22%|██▎       | 45/200 [00:45<01:33,  1.67it/s]

[I 2025-11-10 18:53:08,480] Trial 43 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.09846645060401707, 'n_estimators': 808, 'subsample': 0.6674097951528813, 'colsample_bytree': 0.5451558765514307, 'min_child_weight': 9, 'gamma': 2.5123562008377216, 'reg_alpha': 2.2783542572107002e-07, 'reg_lambda': 5.923156468191829e-07, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:53:08,629] Trial 42 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.01902983614328075, 'n_estimators': 856, 'subsample': 0.6718868921551916, 'colsample_bytree': 0.7297192034526397, 'min_child_weight': 6, 'gamma': 2.241607053502039, 'reg_alpha': 1.9850753250456518e-07, 'reg_lambda': 7.510361826798667e-06, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  24%|██▎       | 47/200 [00:45<01:10,  2.17it/s]

[I 2025-11-10 18:53:09,195] Trial 48 pruned.
[I 2025-11-10 18:53:09,350] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.015988863245275098, 'n_estimators': 441, 'subsample': 0.975137864812251, 'colsample_bytree': 0.9493082900755929, 'min_child_weight': 9, 'gamma': 1.8648308312234958, 'reg_alpha': 0.00012855230378141323, 'reg_lambda': 0.00035247484435646655, 'max_delta_step': 9}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  24%|██▍       | 48/200 [00:46<01:01,  2.47it/s]

[I 2025-11-10 18:53:09,628] Trial 47 pruned.

Best trial: 0. Best value: 0.549181:  24%|██▍       | 49/200 [00:47<01:35,  1.59it/s]

[I 2025-11-10 18:53:10,782] Trial 50 pruned.

Best trial: 0. Best value: 0.549181:  25%|██▌       | 50/200 [00:47<01:23,  1.81it/s]

[I 2025-11-10 18:53:11,158] Trial 51 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.010199828892016557, 'n_estimators': 338, 'subsample': 0.807009544989271, 'colsample_bytree': 0.9711781916234267, 'min_child_weight': 8, 'gamma': 0.22154234053833036, 'reg_alpha': 9.292485460288768e-06, 'reg_lambda': 1.6165371089818223e-07, 'max_delta_step': 4}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  26%|██▌       | 51/200 [00:48<01:35,  1.56it/s]

[I 2025-11-10 18:53:12,006] Trial 46 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.022117565283795538, 'n_estimators': 835, 'subsample': 0.8033110316455689, 'colsample_bytree': 0.9642020551085015, 'min_child_weight': 9, 'gamma': 1.7924949287270535, 'reg_alpha': 9.916269976777158e-05, 'reg_lambda': 4.808050871823886e-07, 'max_delta_step': 8}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  26%|██▋       | 53/200 [00:49<01:11,  2.05it/s]

[I 2025-11-10 18:53:12,606] Trial 52 pruned.
[I 2025-11-10 18:53:12,763] Trial 53 pruned.

Best trial: 0. Best value: 0.549181:  27%|██▋       | 54/200 [00:50<01:39,  1.47it/s]

[I 2025-11-10 18:53:13,897] Trial 49 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.010357830035927702, 'n_estimators': 1068, 'subsample': 0.5129916739279422, 'colsample_bytree': 0.9693588394435863, 'min_child_weight': 9, 'gamma': 2.910755095463453, 'reg_alpha': 0.528502695280083, 'reg_lambda': 0.01199643948156158, 'max_delta_step': 9}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  28%|██▊       | 55/200 [00:51<02:14,  1.08it/s]

[I 2025-11-10 18:53:15,390] Trial 54 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.07104094301590563, 'n_estimators': 769, 'subsample': 0.515459616984697, 'colsample_bytree': 0.9181000455032717, 'min_child_weight': 8, 'gamma': 0.20864648392975832, 'reg_alpha': 0.24736645226144835, 'reg_lambda': 0.011733464987960202, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  28%|██▊       | 57/200 [00:52<01:24,  1.68it/s]

[I 2025-11-10 18:53:15,810] Trial 55 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.07011229648536041, 'n_estimators': 713, 'subsample': 0.5743900694612591, 'colsample_bytree': 0.9034427932943082, 'min_child_weight': 7, 'gamma': 4.604443232069978, 'reg_alpha': 0.2556177036574023, 'reg_lambda': 0.14070430096203126, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:53:15,986] Trial 56 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.033906023345190495, 'n_estimators': 726, 'subsample': 0.7305298140342815, 'colsample_bytree': 0.8793072608067372, 'min_child_weight': 6, 'gamma': 1.519262819060051, 'reg_alpha': 0.021499638434962588, 'reg_lambda': 4.8622611065642, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  29%|██▉       | 58/200 [00:54<02:40,  1.13s/it]

[I 2025-11-10 18:53:18,366] Trial 58 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.06996256466588224, 'n_estimators': 697, 'subsample': 0.732415898349512, 'colsample_bytree': 0.8218795022415435, 'min_child_weight': 10, 'gamma': 1.4513205204556678, 'reg_alpha': 0.01991724609179567, 'reg_lambda': 5.026787865576934e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  30%|██▉       | 59/200 [00:56<02:44,  1.17s/it]

[I 2025-11-10 18:53:19,622] Trial 61 pruned.

Best trial: 0. Best value: 0.549181:  30%|███       | 60/200 [00:56<02:09,  1.08it/s]

[I 2025-11-10 18:53:19,985] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03484985304485062, 'n_estimators': 1396, 'subsample': 0.9967449857663164, 'colsample_bytree': 0.9226024364700043, 'min_child_weight': 6, 'gamma': 1.4947941237708442, 'reg_alpha': 0.026581602468387852, 'reg_lambda': 0.0682547670240912, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  30%|███       | 61/200 [00:56<01:42,  1.36it/s]

[I 2025-11-10 18:53:20,273] Trial 62 pruned.

Best trial: 0. Best value: 0.549181:  31%|███       | 62/200 [00:57<01:34,  1.46it/s]

[I 2025-11-10 18:53:20,845] Trial 63 pruned.

Best trial: 0. Best value: 0.549181:  32%|███▏      | 64/200 [00:58<01:18,  1.74it/s]

[I 2025-11-10 18:53:21,820] Trial 60 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.10303340740491529, 'n_estimators': 1393, 'subsample': 0.6506090857869484, 'colsample_bytree': 0.8231776424725012, 'min_child_weight': 10, 'gamma': 0.02486551649849692, 'reg_alpha': 0.0020177579708932102, 'reg_lambda': 4.2771577826915863e-08, 'max_delta_step': 7}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:53:21,932] Trial 59 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.034547198264107924, 'n_estimators': 1425, 'subsample': 0.7328476592901226, 'colsample_bytree': 0.8163038094132036, 'min_child_weight': 6, 'gamma': 1.4436420781556283, 'reg_alpha': 0.01486359580495784, 'reg_lambda': 3.2253530697163404, 'max_delta_step': 7}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  32%|███▎      | 65/200 [00:58<01:00,  2.22it/s]

[I 2025-11-10 18:53:22,090] Trial 65 pruned.

Best trial: 0. Best value: 0.549181:  33%|███▎      | 66/200 [01:02<03:18,  1.48s/it]

[I 2025-11-10 18:53:25,973] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2130748681869345, 'n_estimators': 1309, 'subsample': 0.8476080207100986, 'colsample_bytree': 0.9854152114766763, 'min_child_weight': 5, 'gamma': 3.1557664015827687, 'reg_alpha': 0.002183370612960095, 'reg_lambda': 1.8347611778176518, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  34%|███▎      | 67/200 [01:03<03:02,  1.37s/it]

[I 2025-11-10 18:53:27,098] Trial 66 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.15421807772942034, 'n_estimators': 1223, 'subsample': 0.7715029043532017, 'colsample_bytree': 0.936805098686833, 'min_child_weight': 5, 'gamma': 3.638445957719191, 'reg_alpha': 4.611761921428608e-05, 'reg_lambda': 2.5591661883041225e-07, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:53:27,114] Trial 67 finished with value: 0.49000000000000005 and parameters: {'max_depth': 4, 'learning_rate': 0.14215735806358396, 'n_estimators': 1196, 'subsample': 0.8549332908841477, 'colsample_bytree': 0.988707060608611, 'min_child_weight': 5, 'gamma': 3.216869916808081, 'reg_alpha': 4.715033432203967e-05, 'reg_lambda': 2.1308175585824053e-07, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  34%|███▍      | 69/200 [01:03<01:46,  1.23it/s]

[I 2025-11-10 18:53:27,411] Trial 68 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.15242063271466552, 'n_estimators': 1224, 'subsample': 0.8494835856257417, 'colsample_bytree': 0.9390406228910017, 'min_child_weight': 7, 'gamma': 4.99277484696565, 'reg_alpha': 1.8264172320057732, 'reg_lambda': 1.3547515273876977e-05, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  35%|███▌      | 70/200 [01:04<01:52,  1.15it/s]

[I 2025-11-10 18:53:28,451] Trial 72 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.011993407880107443, 'n_estimators': 213, 'subsample': 0.9093115240456202, 'colsample_bytree': 0.8700784518281769, 'min_child_weight': 10, 'gamma': 1.2486058899072727, 'reg_alpha': 1.630117610251745e-05, 'reg_lambda': 0.00010105600104913722, 'max_delta_step': 4}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  36%|███▌      | 71/200 [01:05<01:59,  1.08it/s]

[I 2025-11-10 18:53:29,548] Trial 71 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.11805719390323603, 'n_estimators': 522, 'subsample': 0.912609744812545, 'colsample_bytree': 0.866954171627272, 'min_child_weight': 7, 'gamma': 0.44994948276109514, 'reg_alpha': 5.351630497301315e-07, 'reg_lambda': 1.499859574473964e-05, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  36%|███▌      | 72/200 [01:07<02:33,  1.20s/it]

[I 2025-11-10 18:53:31,479] Trial 69 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.012554623348084853, 'n_estimators': 1216, 'subsample': 0.7697958514347998, 'colsample_bytree': 0.9992517663783481, 'min_child_weight': 8, 'gamma': 3.7250280782185055, 'reg_alpha': 1.576306926073832, 'reg_lambda': 2.3954397202399137e-05, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  36%|███▋      | 73/200 [01:08<02:07,  1.00s/it]

[I 2025-11-10 18:53:31,967] Trial 70 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.08895699377944585, 'n_estimators': 1150, 'subsample': 0.9182116275494815, 'colsample_bytree': 0.5815529098702945, 'min_child_weight': 8, 'gamma': 4.959371380915416, 'reg_alpha': 1.5955638776997145, 'reg_lambda': 0.00015019946535173786, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  37%|███▋      | 74/200 [01:09<02:23,  1.14s/it]

[I 2025-11-10 18:53:33,454] Trial 73 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.11950559577446283, 'n_estimators': 1135, 'subsample': 0.7508568109488332, 'colsample_bytree': 0.8647451059894317, 'min_child_weight': 8, 'gamma': 0.3388120881519936, 'reg_alpha': 0.0003965173329762454, 'reg_lambda': 2.673516906225222e-06, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  38%|███▊      | 75/200 [01:11<02:22,  1.14s/it]

[I 2025-11-10 18:53:34,590] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.09204783607595583, 'n_estimators': 1135, 'subsample': 0.6929984691419391, 'colsample_bytree': 0.895276842448467, 'min_child_weight': 8, 'gamma': 2.7975855317601246, 'reg_alpha': 0.0003953112119538387, 'reg_lambda': 3.19809178805332e-05, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  38%|███▊      | 76/200 [01:13<02:53,  1.40s/it]

[I 2025-11-10 18:53:36,629] Trial 76 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07504513757966358, 'n_estimators': 1125, 'subsample': 0.8802294558815771, 'colsample_bytree': 0.7494360159975457, 'min_child_weight': 7, 'gamma': 2.7412006819692, 'reg_alpha': 0.0003098643614021371, 'reg_lambda': 3.1377289104862796e-06, 'max_delta_step': 9}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  38%|███▊      | 77/200 [01:13<02:28,  1.21s/it]

[I 2025-11-10 18:53:37,379] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.08871466945773547, 'n_estimators': 1456, 'subsample': 0.8881470574990011, 'colsample_bytree': 0.5848838402492722, 'min_child_weight': 8, 'gamma': 2.7217717844878067, 'reg_alpha': 0.0003748185265563504, 'reg_lambda': 0.00018671257976387434, 'max_delta_step': 8}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  39%|███▉      | 78/200 [01:14<01:54,  1.06it/s]

[I 2025-11-10 18:53:37,679] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.07676973873544514, 'n_estimators': 1001, 'subsample': 0.8817923706093939, 'colsample_bytree': 0.7552558334355708, 'min_child_weight': 7, 'gamma': 2.699404945066666, 'reg_alpha': 0.055444698321229474, 'reg_lambda': 4.335433501765667e-05, 'max_delta_step': 9}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  40%|███▉      | 79/200 [01:17<03:10,  1.58s/it]

[I 2025-11-10 18:53:40,758] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.0784981334628494, 'n_estimators': 1462, 'subsample': 0.8810513947978701, 'colsample_bytree': 0.7518154613806971, 'min_child_weight': 7, 'gamma': 0.5996444955366484, 'reg_alpha': 0.051872934175465596, 'reg_lambda': 1.4333668513067964e-06, 'max_delta_step': 9}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  40%|████      | 80/200 [01:18<02:49,  1.41s/it]

[I 2025-11-10 18:53:41,786] Trial 80 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.054157933128141954, 'n_estimators': 996, 'subsample': 0.7095434642905556, 'colsample_bytree': 0.8393708020635869, 'min_child_weight': 6, 'gamma': 0.5598247611384544, 'reg_alpha': 0.04284325893057049, 'reg_lambda': 0.0005338121549782516, 'max_delta_step': 9}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  40%|████      | 81/200 [01:19<02:33,  1.29s/it]

[I 2025-11-10 18:53:42,786] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05109513936344058, 'n_estimators': 1454, 'subsample': 0.8955655115332104, 'colsample_bytree': 0.7055395445067236, 'min_child_weight': 6, 'gamma': 0.7098109884668191, 'reg_alpha': 7.764568353002095e-05, 'reg_lambda': 0.0006721238534775187, 'max_delta_step': 8}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  41%|████      | 82/200 [01:19<02:12,  1.12s/it]

[I 2025-11-10 18:53:43,525] Trial 81 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.050816250826067735, 'n_estimators': 1372, 'subsample': 0.7110462592555675, 'colsample_bytree': 0.6481205271973578, 'min_child_weight': 6, 'gamma': 0.6025223390070623, 'reg_alpha': 0.0011375890145011256, 'reg_lambda': 1.0275410640638898e-06, 'max_delta_step': 2}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  42%|████▏     | 83/200 [01:23<03:18,  1.70s/it]

[I 2025-11-10 18:53:46,557] Trial 82 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.04905501507470606, 'n_estimators': 1355, 'subsample': 0.7119623321339941, 'colsample_bytree': 0.7043226011988499, 'min_child_weight': 6, 'gamma': 3.0553860677456424, 'reg_alpha': 0.0010668685181999342, 'reg_lambda': 0.0007936372570422514, 'max_delta_step': 8}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  42%|████▏     | 84/200 [01:23<02:46,  1.43s/it]

[I 2025-11-10 18:53:47,376] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.015048392847203716, 'n_estimators': 1040, 'subsample': 0.5425592825446827, 'colsample_bytree': 0.9512272638706865, 'min_child_weight': 9, 'gamma': 4.470629921758143, 'reg_alpha': 0.11743206813222029, 'reg_lambda': 0.40973207439837445, 'max_delta_step': 1}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  42%|████▎     | 85/200 [01:24<02:13,  1.16s/it]

[I 2025-11-10 18:53:47,906] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.047559084056541856, 'n_estimators': 1376, 'subsample': 0.8277930331984327, 'colsample_bytree': 0.9508210406886612, 'min_child_weight': 9, 'gamma': 3.4778399343357935, 'reg_alpha': 0.0010911000097441814, 'reg_lambda': 8.222619284647433e-05, 'max_delta_step': 8}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  43%|████▎     | 86/200 [01:24<01:40,  1.14it/s]

[I 2025-11-10 18:53:48,129] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.014218102787115421, 'n_estimators': 1053, 'subsample': 0.5606253657206723, 'colsample_bytree': 0.9552662750613675, 'min_child_weight': 9, 'gamma': 0.15785919189190745, 'reg_alpha': 0.008317682389453239, 'reg_lambda': 4.890038314091328e-07, 'max_delta_step': 1}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  44%|████▍     | 88/200 [01:27<02:02,  1.10s/it]

[I 2025-11-10 18:53:51,093] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.014319153713665322, 'n_estimators': 1040, 'subsample': 0.5675833963842637, 'colsample_bytree': 0.951883652808854, 'min_child_weight': 9, 'gamma': 2.492540174445602, 'reg_alpha': 0.11247453604125107, 'reg_lambda': 0.6932286977714125, 'max_delta_step': 1}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:53:51,240] Trial 87 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.01745863680260801, 'n_estimators': 892, 'subsample': 0.6241049135276753, 'colsample_bytree': 0.93172014033736, 'min_child_weight': 10, 'gamma': 3.456900347600172, 'reg_alpha': 8.256933568272712e-07, 'reg_lambda': 0.0034098104250289253, 'max_delta_step': 2}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  45%|████▌     | 90/200 [01:28<01:23,  1.32it/s]

[I 2025-11-10 18:53:52,068] Trial 88 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.06435460589950676, 'n_estimators': 954, 'subsample': 0.6297186570454548, 'colsample_bytree': 0.9753723754110927, 'min_child_weight': 10, 'gamma': 4.78386091321674, 'reg_alpha': 0.008855720580694922, 'reg_lambda': 4.664363797509019e-06, 'max_delta_step': 4}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:53:52,231] Trial 89 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.01745006802525769, 'n_estimators': 934, 'subsample': 0.624611746562937, 'colsample_bytree': 0.9758458321444674, 'min_child_weight': 10, 'gamma': 0.11986807331002725, 'reg_alpha': 0.1259766041849242, 'reg_lambda': 5.868097501204597e-06, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  46%|████▌     | 91/200 [01:29<01:38,  1.11it/s]

[I 2025-11-10 18:53:53,448] Trial 92 pruned.

Best trial: 0. Best value: 0.549181:  46%|████▌     | 92/200 [01:31<02:04,  1.15s/it]

[I 2025-11-10 18:53:55,194] Trial 90 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.011396197072803843, 'n_estimators': 924, 'subsample': 0.6223482201715012, 'colsample_bytree': 0.9790269182406024, 'min_child_weight': 10, 'gamma': 4.764828351073413, 'reg_alpha': 8.440103024207039e-07, 'reg_lambda': 6.170005635958163e-06, 'max_delta_step': 2}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  46%|████▋     | 93/200 [01:33<02:13,  1.25s/it]

[I 2025-11-10 18:53:56,678] Trial 93 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.025322074309689968, 'n_estimators': 1100, 'subsample': 0.6048380276315435, 'colsample_bytree': 0.5124280693593171, 'min_child_weight': 7, 'gamma': 1.6637190054619733, 'reg_alpha': 1.6185967876795226e-05, 'reg_lambda': 1.8576575781676343e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  47%|████▋     | 94/200 [01:33<01:41,  1.04it/s]

[I 2025-11-10 18:53:56,955] Trial 91 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.06609036702654236, 'n_estimators': 1298, 'subsample': 0.5905692086432333, 'colsample_bytree': 0.9182468112117204, 'min_child_weight': 10, 'gamma': 4.77257485107871, 'reg_alpha': 7.186604420820282e-08, 'reg_lambda': 1.8832957394926276e-08, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  48%|████▊     | 95/200 [01:35<02:03,  1.18s/it]

[I 2025-11-10 18:53:58,645] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.020021395955776435, 'n_estimators': 1173, 'subsample': 0.7866360194169117, 'colsample_bytree': 0.9937549802821348, 'min_child_weight': 8, 'gamma': 1.2502692916517293, 'reg_alpha': 0.9425190061795993, 'reg_lambda': 0.00010975308558701168, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:53:58,663] Trial 95 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.027335395869424895, 'n_estimators': 781, 'subsample': 0.7819928462353845, 'colsample_bytree': 0.9951940533972301, 'min_child_weight': 8, 'gamma': 0.813855398809125, 'reg_alpha': 0.6905702343047452, 'reg_lambda': 0.0002491819841566859, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  48%|████▊     | 97/200 [01:36<01:32,  1.11it/s]

[I 2025-11-10 18:53:59,784] Trial 98 pruned.

Best trial: 0. Best value: 0.549181:  49%|████▉     | 98/200 [01:36<01:19,  1.28it/s]

[I 2025-11-10 18:54:00,220] Trial 96 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02073726523779084, 'n_estimators': 789, 'subsample': 0.9804588184473081, 'colsample_bytree': 0.9150052925105818, 'min_child_weight': 8, 'gamma': 1.068712604148097, 'reg_alpha': 3.4332245246718696, 'reg_lambda': 0.0003104707446060523, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  50%|████▉     | 99/200 [01:37<01:07,  1.50it/s]

[I 2025-11-10 18:54:00,557] Trial 97 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.030944664173783276, 'n_estimators': 810, 'subsample': 0.9822927492703959, 'colsample_bytree': 0.9970872857524872, 'min_child_weight': 8, 'gamma': 0.7805934875996543, 'reg_alpha': 3.855738045025304, 'reg_lambda': 0.0002772463428722172, 'max_delta_step': 4}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  50%|█████     | 100/200 [01:39<01:51,  1.11s/it]

[I 2025-11-10 18:54:02,861] Trial 99 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.19744773629291917, 'n_estimators': 962, 'subsample': 0.9591982326811204, 'colsample_bytree': 0.7786706120206828, 'min_child_weight': 7, 'gamma': 0.32491293230334717, 'reg_alpha': 8.74273317828059, 'reg_lambda': 0.00035670367696800606, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  50%|█████     | 101/200 [01:40<01:38,  1.00it/s]

[I 2025-11-10 18:54:03,565] Trial 100 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.05845379295492995, 'n_estimators': 879, 'subsample': 0.8627411552038147, 'colsample_bytree': 0.544734979840921, 'min_child_weight': 9, 'gamma': 1.0827851788046199, 'reg_alpha': 0.000654875733523995, 'reg_lambda': 0.0003588258506247843, 'max_delta_step': 4}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  51%|█████     | 102/200 [01:42<02:14,  1.37s/it]

[I 2025-11-10 18:54:05,874] Trial 104 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.042923508229934175, 'n_estimators': 490, 'subsample': 0.6614290100616307, 'colsample_bytree': 0.9601038285893383, 'min_child_weight': 7, 'gamma': 1.2744147261261707, 'reg_alpha': 3.2733889287608125e-05, 'reg_lambda': 1.0301723541855304e-05, 'max_delta_step': 7}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  52%|█████▏    | 103/200 [01:42<01:42,  1.05s/it]

[I 2025-11-10 18:54:06,150] Trial 101 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.0559558332492486, 'n_estimators': 1324, 'subsample': 0.8231303903249902, 'colsample_bytree': 0.7825232023788808, 'min_child_weight': 7, 'gamma': 0.4388913898126535, 'reg_alpha': 0.0006939996323896111, 'reg_lambda': 1.0614304007959911e-05, 'max_delta_step': 4}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  52%|█████▏    | 104/200 [01:42<01:20,  1.20it/s]

[I 2025-11-10 18:54:06,457] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.1270211160206339, 'n_estimators': 1329, 'subsample': 0.8193311054381117, 'colsample_bytree': 0.7908212343570901, 'min_child_weight': 7, 'gamma': 0.3449178314121917, 'reg_alpha': 9.493376602360808, 'reg_lambda': 1.3192079350161249e-07, 'max_delta_step': 7}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  52%|█████▎    | 105/200 [01:44<01:27,  1.08it/s]

[I 2025-11-10 18:54:07,590] Trial 105 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.03135296429062407, 'n_estimators': 343, 'subsample': 0.8252094973405855, 'colsample_bytree': 0.9401104119279842, 'min_child_weight': 9, 'gamma': 2.1033869035165256, 'reg_alpha': 1.0756657464233702e-05, 'reg_lambda': 7.00831517136173e-08, 'max_delta_step': 2}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  53%|█████▎    | 106/200 [01:44<01:10,  1.34it/s]

[I 2025-11-10 18:54:07,924] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.037433291547123576, 'n_estimators': 359, 'subsample': 0.7576560117533799, 'colsample_bytree': 0.9404903864932087, 'min_child_weight': 8, 'gamma': 2.3359851500279545, 'reg_alpha': 2.0654069287333924e-06, 'reg_lambda': 6.547159471751644e-08, 'max_delta_step': 2}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  54%|█████▎    | 107/200 [01:44<00:59,  1.57it/s]

[I 2025-11-10 18:54:08,290] Trial 107 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.021676196384197457, 'n_estimators': 370, 'subsample': 0.7580814343117752, 'colsample_bytree': 0.9396967770018001, 'min_child_weight': 8, 'gamma': 2.0126114155212265, 'reg_alpha': 2.1013159030840484e-06, 'reg_lambda': 8.963054986542498e-08, 'max_delta_step': 2}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  54%|█████▍    | 108/200 [01:45<00:49,  1.85it/s]

[I 2025-11-10 18:54:08,607] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.058643042781713735, 'n_estimators': 1329, 'subsample': 0.6655690824578958, 'colsample_bytree': 0.5384369438499027, 'min_child_weight': 9, 'gamma': 1.1094413264700753, 'reg_alpha': 0.0006758629210840442, 'reg_lambda': 1.1404672353494582e-07, 'max_delta_step': 7}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  55%|█████▍    | 109/200 [01:48<02:08,  1.41s/it]

[I 2025-11-10 18:54:12,066] Trial 108 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.016907760544782373, 'n_estimators': 1028, 'subsample': 0.9309580071792466, 'colsample_bytree': 0.9663365208326659, 'min_child_weight': 8, 'gamma': 2.607309255605371, 'reg_alpha': 9.422165567451668e-05, 'reg_lambda': 0.0053310768692343075, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  55%|█████▌    | 110/200 [01:49<02:02,  1.36s/it]

[I 2025-11-10 18:54:13,294] Trial 110 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02376787219680558, 'n_estimators': 1190, 'subsample': 0.6410199901162781, 'colsample_bytree': 0.983513494826622, 'min_child_weight': 9, 'gamma': 4.031856133996304, 'reg_alpha': 8.562927189484024e-05, 'reg_lambda': 3.347508791200669e-07, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:54:13,322] Trial 109 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.023339129500333157, 'n_estimators': 1273, 'subsample': 0.7225001502248434, 'colsample_bytree': 0.9654746267355815, 'min_child_weight': 8, 'gamma': 1.1463287392130936, 'reg_alpha': 7.602199996327569e-05, 'reg_lambda': 4.5067743582118826e-05, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  56%|█████▌    | 112/200 [01:50<01:21,  1.08it/s]

[I 2025-11-10 18:54:14,124] Trial 111 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.016770972234657296, 'n_estimators': 1272, 'subsample': 0.6838713992498677, 'colsample_bytree': 0.9853308441000793, 'min_child_weight': 5, 'gamma': 2.592824913419065, 'reg_alpha': 6.714127568037368e-05, 'reg_lambda': 4.520891821762307e-05, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  56%|█████▋    | 113/200 [01:51<01:14,  1.17it/s]

[I 2025-11-10 18:54:14,775] Trial 112 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.013054217050746579, 'n_estimators': 611, 'subsample': 0.7229242700672003, 'colsample_bytree': 0.8896401114601044, 'min_child_weight': 5, 'gamma': 4.094435802646896, 'reg_alpha': 0.32129812032282506, 'reg_lambda': 4.7388251681800524e-05, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:54:14,857] Trial 113 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.08289914707341217, 'n_estimators': 302, 'subsample': 0.7423715803171149, 'colsample_bytree': 0.8963787037810752, 'min_child_weight': 5, 'gamma': 4.376453379388065, 'reg_alpha': 4.514180418833588e-06, 'reg_lambda': 5.690771488426195e-05, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  57%|█████▊    | 115/200 [01:52<00:58,  1.46it/s]

[I 2025-11-10 18:54:15,660] Trial 115 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.09572287190076166, 'n_estimators': 290, 'subsample': 0.7442234932392761, 'colsample_bytree': 0.9292336774622227, 'min_child_weight': 6, 'gamma': 4.3554289062460345, 'reg_alpha': 0.00016856947384127254, 'reg_lambda': 2.0655391283140296e-05, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  58%|█████▊    | 116/200 [01:52<00:57,  1.47it/s]

[I 2025-11-10 18:54:16,336] Trial 114 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.08343336122491052, 'n_estimators': 677, 'subsample': 0.5410493697849864, 'colsample_bytree': 0.6155277303606055, 'min_child_weight': 6, 'gamma': 4.502658987156352, 'reg_alpha': 2.8223597561961702e-05, 'reg_lambda': 0.0001233010124078618, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  58%|█████▊    | 117/200 [01:53<00:52,  1.59it/s]

[I 2025-11-10 18:54:16,806] Trial 117 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.17939289713835255, 'n_estimators': 415, 'subsample': 0.550161550017925, 'colsample_bytree': 0.6669864590758188, 'min_child_weight': 6, 'gamma': 3.8059159768621913, 'reg_alpha': 0.00019390502101532473, 'reg_lambda': 0.0001543938786568364, 'max_delta_step': 4}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  59%|█████▉    | 118/200 [01:54<00:55,  1.47it/s]

[I 2025-11-10 18:54:17,619] Trial 116 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.2525581249690803, 'n_estimators': 587, 'subsample': 0.8394826158375188, 'colsample_bytree': 0.9108579383870401, 'min_child_weight': 6, 'gamma': 3.7840707574390944, 'reg_alpha': 2.616979774832387e-05, 'reg_lambda': 0.0001566867305653505, 'max_delta_step': 4}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  60%|██████    | 120/200 [01:55<00:55,  1.45it/s]

[I 2025-11-10 18:54:19,167] Trial 118 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1773550110195632, 'n_estimators': 761, 'subsample': 0.5450314954030572, 'colsample_bytree': 0.9704698747142321, 'min_child_weight': 8, 'gamma': 1.3419033886128584, 'reg_alpha': 2.1755007707282425e-05, 'reg_lambda': 1.9394830486702065e-06, 'max_delta_step': 4}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:54:19,279] Trial 119 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2523875044783013, 'n_estimators': 636, 'subsample': 0.8404645342228054, 'colsample_bytree': 0.9733208781101303, 'min_child_weight': 10, 'gamma': 3.7852955540949647, 'reg_alpha': 1.369587171996255e-05, 'reg_lambda': 8.637300646547917, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  60%|██████    | 121/200 [01:55<00:42,  1.87it/s]

[I 2025-11-10 18:54:19,428] Trial 120 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.2628146820414142, 'n_estimators': 560, 'subsample': 0.8417347989883638, 'colsample_bytree': 0.9119092637261261, 'min_child_weight': 10, 'gamma': 4.646415882777099, 'reg_alpha': 1.2529448484883076e-05, 'reg_lambda': 6.558984705662045e-07, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  61%|██████    | 122/200 [01:57<01:05,  1.20it/s]

[I 2025-11-10 18:54:21,001] Trial 121 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.26023300559173007, 'n_estimators': 756, 'subsample': 0.7943251153418486, 'colsample_bytree': 0.9882646781171472, 'min_child_weight': 10, 'gamma': 0.03132071986160012, 'reg_alpha': 6.64042248379941e-06, 'reg_lambda': 1.9784794736163674e-06, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  62%|██████▏   | 123/200 [01:59<01:31,  1.19s/it]

[I 2025-11-10 18:54:23,049] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.22342151515186254, 'n_estimators': 850, 'subsample': 0.5788099009871339, 'colsample_bytree': 0.857282985455646, 'min_child_weight': 7, 'gamma': 4.913891262817451, 'reg_alpha': 4.2902025253964634e-05, 'reg_lambda': 2.7642605593994693e-08, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:54:23,097] Trial 123 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.11294510308158542, 'n_estimators': 862, 'subsample': 0.9990217503800934, 'colsample_bytree': 0.9869260663592155, 'min_child_weight': 9, 'gamma': 4.883435860503879, 'reg_alpha': 6.3433618327520184e-06, 'reg_lambda': 6.817458317636728e-07, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  62%|██████▎   | 125/200 [02:01<01:17,  1.03s/it]

[I 2025-11-10 18:54:24,714] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.28846077555697014, 'n_estimators': 848, 'subsample': 0.5816576951216953, 'colsample_bytree': 0.8545774252663446, 'min_child_weight': 7, 'gamma': 4.909833177204015, 'reg_alpha': 3.955154062238039e-05, 'reg_lambda': 1.7188747723650497e-08, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  63%|██████▎   | 126/200 [02:01<01:07,  1.10it/s]

[I 2025-11-10 18:54:25,253] Trial 127 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.28780639652345946, 'n_estimators': 470, 'subsample': 0.6910892310587227, 'colsample_bytree': 0.8040909945058009, 'min_child_weight': 8, 'gamma': 4.668807966550129, 'reg_alpha': 0.0001272123823683795, 'reg_lambda': 1.835935047978711e-08, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  64%|██████▎   | 127/200 [02:02<00:55,  1.32it/s]

[I 2025-11-10 18:54:25,585] Trial 122 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.25002670943713573, 'n_estimators': 1407, 'subsample': 0.6990268128947222, 'colsample_bytree': 0.9905521490074496, 'min_child_weight': 10, 'gamma': 0.08154134804558177, 'reg_alpha': 7.306460957871956e-06, 'reg_lambda': 7.773021915628009e-07, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  64%|██████▍   | 129/200 [02:02<00:40,  1.76it/s]

[I 2025-11-10 18:54:26,297] Trial 130 pruned.
[I 2025-11-10 18:54:26,406] Trial 126 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.29654926941463494, 'n_estimators': 727, 'subsample': 0.7749004899086813, 'colsample_bytree': 0.8079412094212873, 'min_child_weight': 8, 'gamma': 4.639985819046066, 'reg_alpha': 0.030023702689487206, 'reg_lambda': 1.0103529237946258e-08, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  65%|██████▌   | 130/200 [02:03<00:32,  2.12it/s]

[I 2025-11-10 18:54:26,630] Trial 129 pruned.

Best trial: 0. Best value: 0.549181:  66%|██████▌   | 131/200 [02:03<00:30,  2.29it/s]

[I 2025-11-10 18:54:26,981] Trial 128 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.15398145556065407, 'n_estimators': 460, 'subsample': 0.7004106299764868, 'colsample_bytree': 0.834395441948412, 'min_child_weight': 8, 'gamma': 4.692741407986153, 'reg_alpha': 0.16274558822250074, 'reg_lambda': 2.457792644703622e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  66%|██████▌   | 132/200 [02:07<01:33,  1.37s/it]

[I 2025-11-10 18:54:30,627] Trial 133 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.018538061888324082, 'n_estimators': 979, 'subsample': 0.9452443692812631, 'colsample_bytree': 0.8320033345729013, 'min_child_weight': 7, 'gamma': 2.85582668864442, 'reg_alpha': 0.0002611235547626047, 'reg_lambda': 0.0015154198274707586, 'max_delta_step': 4}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  66%|██████▋   | 133/200 [02:07<01:17,  1.15s/it]

[I 2025-11-10 18:54:31,249] Trial 135 pruned.

Best trial: 0. Best value: 0.549181:  67%|██████▋   | 134/200 [02:08<01:03,  1.04it/s]

[I 2025-11-10 18:54:31,764] Trial 136 pruned.

Best trial: 0. Best value: 0.549181:  68%|██████▊   | 135/200 [02:09<01:01,  1.06it/s]

[I 2025-11-10 18:54:32,668] Trial 131 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.19162624916153573, 'n_estimators': 1490, 'subsample': 0.6730539191686332, 'colsample_bytree': 0.8363427398537321, 'min_child_weight': 8, 'gamma': 0.23220452619683973, 'reg_alpha': 3.1067787946834565e-06, 'reg_lambda': 3.225786118284473e-05, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  68%|██████▊   | 137/200 [02:09<00:34,  1.83it/s]

[I 2025-11-10 18:54:32,860] Trial 132 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.19702286452264128, 'n_estimators': 1496, 'subsample': 0.9422102721435202, 'colsample_bytree': 0.9619596163196139, 'min_child_weight': 7, 'gamma': 2.994643342756418, 'reg_alpha': 0.16086083966739187, 'reg_lambda': 1.7342851532396286e-07, 'max_delta_step': 8}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:54:32,996] Trial 137 pruned.

Best trial: 0. Best value: 0.549181:  69%|██████▉   | 138/200 [02:09<00:32,  1.90it/s]

[I 2025-11-10 18:54:33,477] Trial 134 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.22884675972894947, 'n_estimators': 1495, 'subsample': 0.8676326045347074, 'colsample_bytree': 0.9612097261764958, 'min_child_weight': 7, 'gamma': 0.21508752695668376, 'reg_alpha': 5.1296627656256035e-05, 'reg_lambda': 1.3642309767810758e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  70%|██████▉   | 139/200 [02:11<00:58,  1.05it/s]

[I 2025-11-10 18:54:35,431] Trial 138 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.045694022365411556, 'n_estimators': 605, 'subsample': 0.740691833658833, 'colsample_bytree': 0.7297320588503883, 'min_child_weight': 5, 'gamma': 0.5339922458394888, 'reg_alpha': 0.00010852877329140251, 'reg_lambda': 0.1935602974344101, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  70%|███████   | 140/200 [02:14<01:21,  1.36s/it]

[I 2025-11-10 18:54:37,749] Trial 140 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.2320922876112446, 'n_estimators': 1080, 'subsample': 0.7375003861241808, 'colsample_bytree': 0.8862955471944403, 'min_child_weight': 6, 'gamma': 4.5287309719188285, 'reg_alpha': 0.07493445658742363, 'reg_lambda': 1.530234468155304e-05, 'max_delta_step': 7}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  70%|███████   | 141/200 [02:14<01:02,  1.06s/it]

[I 2025-11-10 18:54:38,093] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.02684190870490208, 'n_estimators': 1079, 'subsample': 0.7175227474838044, 'colsample_bytree': 0.7383943128284371, 'min_child_weight': 6, 'gamma': 4.484740246620381, 'reg_alpha': 0.6763766722552603, 'reg_lambda': 7.523841966011663e-05, 'max_delta_step': 9}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  71%|███████   | 142/200 [02:14<00:50,  1.15it/s]

[I 2025-11-10 18:54:38,533] Trial 139 finished with value: 0.5139766081871345 and parameters: {'max_depth': 8, 'learning_rate': 0.01111525420457467, 'n_estimators': 1238, 'subsample': 0.8669930485928586, 'colsample_bytree': 0.8835142405695339, 'min_child_weight': 5, 'gamma': 0.5515579806512688, 'reg_alpha': 3.5760475424078025e-07, 'reg_lambda': 7.731835807573198e-05, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:54:38,549] Trial 142 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.02907064274793093, 'n_estimators': 695, 'subsample': 0.7182823280005235, 'colsample_bytree': 0.8740186408502678, 'min_child_weight': 6, 'gamma': 0.6896361212100701, 'reg_alpha': 1.0566206957810955, 'reg_lambda': 1.7382317152306432e-05, 'max_delta_step': 7}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  72%|███████▏  | 144/200 [02:16<00:40,  1.37it/s]

[I 2025-11-10 18:54:39,660] Trial 145 pruned.

Best trial: 0. Best value: 0.549181:  72%|███████▎  | 145/200 [02:16<00:40,  1.35it/s]

[I 2025-11-10 18:54:40,434] Trial 143 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.011169278358930359, 'n_estimators': 555, 'subsample': 0.7519276511650854, 'colsample_bytree': 0.8739177241347178, 'min_child_weight': 9, 'gamma': 1.8152578199609002, 'reg_alpha': 0.46905527677821096, 'reg_lambda': 0.0005294835306842725, 'max_delta_step': 9}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  73%|███████▎  | 146/200 [02:17<00:33,  1.60it/s]

[I 2025-11-10 18:54:40,728] Trial 144 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.06894419615111, 'n_estimators': 545, 'subsample': 0.7521105640387507, 'colsample_bytree': 0.8700649715978385, 'min_child_weight': 5, 'gamma': 4.212897310583928, 'reg_alpha': 1.0154396672869492, 'reg_lambda': 4.026553496817253e-08, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  74%|███████▎  | 147/200 [02:18<00:40,  1.30it/s]

[I 2025-11-10 18:54:41,877] Trial 149 pruned.

Best trial: 0. Best value: 0.549181:  74%|███████▍  | 148/200 [02:18<00:36,  1.42it/s]

[I 2025-11-10 18:54:42,423] Trial 147 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.011224104706738958, 'n_estimators': 571, 'subsample': 0.7568032897595578, 'colsample_bytree': 0.9765513033539179, 'min_child_weight': 5, 'gamma': 1.800476255929091, 'reg_alpha': 1.1397914863422912e-06, 'reg_lambda': 1.0661297833377117, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  74%|███████▍  | 149/200 [02:20<00:45,  1.11it/s]

[I 2025-11-10 18:54:43,801] Trial 146 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.011704802131656167, 'n_estimators': 1178, 'subsample': 0.8074662342920095, 'colsample_bytree': 0.8815897891243494, 'min_child_weight': 5, 'gamma': 1.8014664585982225, 'reg_alpha': 3.9396119087914316e-07, 'reg_lambda': 1.0287848899890862e-05, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  75%|███████▌  | 150/200 [02:22<01:02,  1.25s/it]

[I 2025-11-10 18:54:45,909] Trial 150 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.012472772384886805, 'n_estimators': 908, 'subsample': 0.9676232175077958, 'colsample_bytree': 0.9990540404499801, 'min_child_weight': 8, 'gamma': 4.813642057144849, 'reg_alpha': 3.318184103839463e-07, 'reg_lambda': 0.024100142445835342, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  76%|███████▌  | 151/200 [02:23<00:56,  1.16s/it]

[I 2025-11-10 18:54:46,854] Trial 148 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.012912528200304151, 'n_estimators': 1444, 'subsample': 0.6127328543904712, 'colsample_bytree': 0.978619561812769, 'min_child_weight': 5, 'gamma': 1.5983175131689609, 'reg_alpha': 5.5557935554328426e-08, 'reg_lambda': 1.0030763127599147, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  76%|███████▌  | 152/200 [02:23<00:49,  1.02s/it]

[I 2025-11-10 18:54:47,550] Trial 152 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.013027658135730404, 'n_estimators': 911, 'subsample': 0.8561949185282621, 'colsample_bytree': 0.5868742435903623, 'min_child_weight': 8, 'gamma': 0.765822531560972, 'reg_alpha': 1.250622809271544e-07, 'reg_lambda': 3.6161804286958374e-07, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  76%|███████▋  | 153/200 [02:24<00:47,  1.02s/it]

[I 2025-11-10 18:54:48,553] Trial 151 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.012324144996887143, 'n_estimators': 1442, 'subsample': 0.807465753793339, 'colsample_bytree': 0.8471734993370458, 'min_child_weight': 8, 'gamma': 1.5962449499824847, 'reg_alpha': 0.01406405655061653, 'reg_lambda': 0.02724079102802421, 'max_delta_step': 7}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  77%|███████▋  | 154/200 [02:25<00:41,  1.11it/s]

[I 2025-11-10 18:54:49,184] Trial 156 pruned.

Best trial: 0. Best value: 0.549181:  78%|███████▊  | 155/200 [02:26<00:35,  1.28it/s]

[I 2025-11-10 18:54:49,682] Trial 154 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.26957844910350776, 'n_estimators': 611, 'subsample': 0.7066494294042709, 'colsample_bytree': 0.8464789305877867, 'min_child_weight': 4, 'gamma': 4.719111290231538, 'reg_alpha': 2.467119685624487, 'reg_lambda': 1.0822016091717988e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  78%|███████▊  | 156/200 [02:26<00:35,  1.25it/s]

[I 2025-11-10 18:54:50,523] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.010081340708329556, 'n_estimators': 631, 'subsample': 0.7092328615090466, 'colsample_bytree': 0.8442478260134677, 'min_child_weight': 6, 'gamma': 2.1668727396467142, 'reg_alpha': 0.0005075615703017021, 'reg_lambda': 1.0922864172428442e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  78%|███████▊  | 157/200 [02:27<00:29,  1.46it/s]

[I 2025-11-10 18:54:50,941] Trial 153 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.0742553562886387, 'n_estimators': 1120, 'subsample': 0.5594069012278536, 'colsample_bytree': 0.907893096052042, 'min_child_weight': 8, 'gamma': 1.6719759916242298, 'reg_alpha': 1.1420021810019116e-07, 'reg_lambda': 9.469605575567093e-05, 'max_delta_step': 4}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  79%|███████▉  | 158/200 [02:28<00:27,  1.50it/s]

[I 2025-11-10 18:54:51,559] Trial 157 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.015579735398728109, 'n_estimators': 500, 'subsample': 0.6467495089704971, 'colsample_bytree': 0.8192287093475399, 'min_child_weight': 6, 'gamma': 3.598537613850609, 'reg_alpha': 2.420313523158184, 'reg_lambda': 1.1592922087596532e-06, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  80%|███████▉  | 159/200 [02:29<00:34,  1.18it/s]

[I 2025-11-10 18:54:52,824] Trial 159 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.128112252236851, 'n_estimators': 508, 'subsample': 0.5558184436131325, 'colsample_bytree': 0.5323771777835499, 'min_child_weight': 10, 'gamma': 3.63233270721274, 'reg_alpha': 1.6498830795392558e-05, 'reg_lambda': 7.521594969176759e-05, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  80%|████████  | 160/200 [02:29<00:30,  1.33it/s]

[I 2025-11-10 18:54:53,356] Trial 160 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.015852586922042312, 'n_estimators': 504, 'subsample': 0.6385936284705941, 'colsample_bytree': 0.8929555323248975, 'min_child_weight': 10, 'gamma': 0.41021211627753307, 'reg_alpha': 5.967002868288194, 'reg_lambda': 0.00020577645572231174, 'max_delta_step': 7}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  80%|████████  | 161/200 [02:31<00:44,  1.13s/it]

[I 2025-11-10 18:54:55,383] Trial 158 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0745749323302931, 'n_estimators': 1249, 'subsample': 0.648535885944558, 'colsample_bytree': 0.9476081690348546, 'min_child_weight': 6, 'gamma': 4.983287592684602, 'reg_alpha': 9.811256499255424e-06, 'reg_lambda': 8.54416045397384e-05, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  81%|████████  | 162/200 [02:32<00:40,  1.07s/it]

[I 2025-11-10 18:54:56,297] Trial 163 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.10718218648553818, 'n_estimators': 663, 'subsample': 0.9893378247058292, 'colsample_bytree': 0.9356488885244059, 'min_child_weight': 9, 'gamma': 0.096048720235002, 'reg_alpha': 0.00025005359607382417, 'reg_lambda': 4.3892532226671346e-06, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  82%|████████▏ | 163/200 [02:33<00:33,  1.11it/s]

[I 2025-11-10 18:54:56,817] Trial 161 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.12524937139068806, 'n_estimators': 1237, 'subsample': 0.7293637386969954, 'colsample_bytree': 0.652491073344643, 'min_child_weight': 10, 'gamma': 4.9665571824811865, 'reg_alpha': 1.650379451813637e-05, 'reg_lambda': 2.438763624256797e-08, 'max_delta_step': 7}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  82%|████████▏ | 164/200 [02:34<00:34,  1.03it/s]

[I 2025-11-10 18:54:57,951] Trial 166 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.2871786091682712, 'n_estimators': 225, 'subsample': 0.680635017937415, 'colsample_bytree': 0.8634248334286715, 'min_child_weight': 5, 'gamma': 2.8360382457315723, 'reg_alpha': 0.012692713761358247, 'reg_lambda': 3.8300184748725904e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  82%|████████▎ | 165/200 [02:34<00:29,  1.20it/s]

[I 2025-11-10 18:54:58,455] Trial 162 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.0401435908435508, 'n_estimators': 1251, 'subsample': 0.7923942039248907, 'colsample_bytree': 0.8955139626084309, 'min_child_weight': 5, 'gamma': 3.3870989299966583, 'reg_alpha': 1.0339737770047652e-05, 'reg_lambda': 2.2398812937804122e-08, 'max_delta_step': 7}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:54:58,473] Trial 164 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2745141896163055, 'n_estimators': 659, 'subsample': 0.6862141785281192, 'colsample_bytree': 0.9287747416875521, 'min_child_weight': 5, 'gamma': 3.3511391941153557, 'reg_alpha': 0.00678301187824011, 'reg_lambda': 2.4040322255749153e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  84%|████████▎ | 167/200 [02:37<00:32,  1.02it/s]

[I 2025-11-10 18:55:00,765] Trial 165 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.2809128506616027, 'n_estimators': 1018, 'subsample': 0.6864260570485797, 'colsample_bytree': 0.8290225939725726, 'min_child_weight': 5, 'gamma': 3.2008307708521833, 'reg_alpha': 0.006200747769739521, 'reg_lambda': 2.184294371169081e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  84%|████████▍ | 168/200 [02:38<00:35,  1.10s/it]

[I 2025-11-10 18:55:02,226] Trial 167 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.26955687879047313, 'n_estimators': 1012, 'subsample': 0.7913187123936607, 'colsample_bytree': 0.831133394145763, 'min_child_weight': 5, 'gamma': 3.3436074418277872, 'reg_alpha': 0.003963615678323369, 'reg_lambda': 1.791592688818155e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  85%|████████▌ | 170/200 [02:39<00:20,  1.44it/s]

[I 2025-11-10 18:55:02,544] Trial 168 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.28062915011885725, 'n_estimators': 938, 'subsample': 0.6585348892612003, 'colsample_bytree': 0.830654973274955, 'min_child_weight': 5, 'gamma': 3.3123947066480133, 'reg_alpha': 0.02902092698901081, 'reg_lambda': 8.750657591889848e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:55:02,705] Trial 169 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.24174349768245862, 'n_estimators': 976, 'subsample': 0.7637036932602309, 'colsample_bytree': 0.8284182758323007, 'min_child_weight': 5, 'gamma': 3.1724606026559887, 'reg_alpha': 5.7119250863157206e-05, 'reg_lambda': 1.5793673014670036e-08, 'max_delta_step': 8}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  86%|████████▌ | 171/200 [02:41<00:33,  1.15s/it]

[I 2025-11-10 18:55:05,010] Trial 170 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.24245663569470743, 'n_estimators': 948, 'subsample': 0.7833722633508351, 'colsample_bytree': 0.9926797292778407, 'min_child_weight': 5, 'gamma': 0.2953692182786049, 'reg_alpha': 0.0034666082168030837, 'reg_lambda': 7.01178085053035e-08, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  86%|████████▌ | 172/200 [02:42<00:33,  1.20s/it]

[I 2025-11-10 18:55:06,329] Trial 174 pruned.

Best trial: 0. Best value: 0.549181:  86%|████████▋ | 173/200 [02:43<00:27,  1.01s/it]

[I 2025-11-10 18:55:06,894] Trial 172 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.24339400485044807, 'n_estimators': 974, 'subsample': 0.7659177418190519, 'colsample_bytree': 0.9863343661076671, 'min_child_weight': 7, 'gamma': 3.548583353981799, 'reg_alpha': 0.044975922777692946, 'reg_lambda': 5.425394964979253e-08, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  87%|████████▋ | 174/200 [02:44<00:28,  1.11s/it]

[I 2025-11-10 18:55:08,255] Trial 171 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.2462135275261787, 'n_estimators': 1352, 'subsample': 0.8921280296466982, 'colsample_bytree': 0.9993838411815857, 'min_child_weight': 7, 'gamma': 3.9344436764425486, 'reg_alpha': 0.030167650731599934, 'reg_lambda': 3.859877575861078e-08, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  88%|████████▊ | 175/200 [02:45<00:23,  1.08it/s]

[I 2025-11-10 18:55:08,744] Trial 173 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.2172877891661534, 'n_estimators': 1372, 'subsample': 0.9189680195906247, 'colsample_bytree': 0.9175586266591218, 'min_child_weight': 7, 'gamma': 3.8921630166440275, 'reg_alpha': 3.514016169311896e-05, 'reg_lambda': 0.0008684728971192396, 'max_delta_step': 3}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  88%|████████▊ | 176/200 [02:47<00:30,  1.28s/it]

[I 2025-11-10 18:55:10,840] Trial 177 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.06173691530473318, 'n_estimators': 586, 'subsample': 0.9244917747511268, 'colsample_bytree': 0.6785987516783524, 'min_child_weight': 6, 'gamma': 1.1796186486506102, 'reg_alpha': 0.00017040463195554557, 'reg_lambda': 4.688404102397726, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  88%|████████▊ | 177/200 [02:48<00:26,  1.14s/it]

[I 2025-11-10 18:55:11,671] Trial 179 pruned.

Best trial: 0. Best value: 0.549181:  89%|████████▉ | 178/200 [02:48<00:20,  1.10it/s]

[I 2025-11-10 18:55:12,029] Trial 175 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.06222287059493063, 'n_estimators': 1295, 'subsample': 0.9249317340053356, 'colsample_bytree': 0.6941383970360042, 'min_child_weight': 7, 'gamma': 1.018776998631782, 'reg_alpha': 3.1198976659548925e-05, 'reg_lambda': 4.3737513631058695e-08, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  90%|████████▉ | 179/200 [02:49<00:17,  1.22it/s]

[I 2025-11-10 18:55:12,633] Trial 176 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.16666691207133985, 'n_estimators': 1297, 'subsample': 0.9585390796719894, 'colsample_bytree': 0.702117132148422, 'min_child_weight': 6, 'gamma': 1.0301211252999274, 'reg_alpha': 0.0014742677509397707, 'reg_lambda': 3.726904681600756e-08, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:55:12,652] Trial 178 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.14126696115205753, 'n_estimators': 874, 'subsample': 0.9608263957393471, 'colsample_bytree': 0.6833721194196232, 'min_child_weight': 6, 'gamma': 1.0096225988071885, 'reg_alpha': 6.50137269704627, 'reg_lambda': 1.1964411559657169e-07, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  90%|█████████ | 181/200 [02:53<00:25,  1.35s/it]

[I 2025-11-10 18:55:16,572] Trial 181 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.16726331643157888, 'n_estimators': 1058, 'subsample': 0.7272382103195414, 'colsample_bytree': 0.5583817225331438, 'min_child_weight': 8, 'gamma': 0.7417153832600532, 'reg_alpha': 7.993075972596454e-05, 'reg_lambda': 1.1368034609304732e-07, 'max_delta_step': 4}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  91%|█████████ | 182/200 [02:53<00:21,  1.20s/it]

[I 2025-11-10 18:55:17,306] Trial 182 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.11563475880755325, 'n_estimators': 1053, 'subsample': 0.7270119250037442, 'colsample_bytree': 0.8108092269366233, 'min_child_weight': 8, 'gamma': 2.9882739064302344, 'reg_alpha': 7.616176025030327e-05, 'reg_lambda': 0.000250402552042931, 'max_delta_step': 4}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  92%|█████████▏| 183/200 [02:54<00:16,  1.05it/s]

[I 2025-11-10 18:55:17,584] Trial 180 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.13813069437802197, 'n_estimators': 1306, 'subsample': 0.727402928765434, 'colsample_bytree': 0.7988444434358117, 'min_child_weight': 8, 'gamma': 4.793371736073624, 'reg_alpha': 3.7057862005867155, 'reg_lambda': 0.00021676970194918463, 'max_delta_step': 4}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  92%|█████████▏| 184/200 [02:55<00:18,  1.15s/it]

[I 2025-11-10 18:55:19,261] Trial 183 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.2994713548956023, 'n_estimators': 1473, 'subsample': 0.7316982162224303, 'colsample_bytree': 0.9054552571417122, 'min_child_weight': 8, 'gamma': 2.9776684089779866, 'reg_alpha': 8.344164292301534e-05, 'reg_lambda': 2.6777730397243116e-05, 'max_delta_step': 4}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  92%|█████████▎| 185/200 [02:58<00:25,  1.72s/it]

[I 2025-11-10 18:55:22,424] Trial 184 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.14754278203021814, 'n_estimators': 1403, 'subsample': 0.6967407346216006, 'colsample_bytree': 0.7159087395098862, 'min_child_weight': 9, 'gamma': 0.5080645914510418, 'reg_alpha': 8.149388861593328, 'reg_lambda': 0.0002372870211179916, 'max_delta_step': 9}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  93%|█████████▎| 186/200 [02:59<00:20,  1.48s/it]

[I 2025-11-10 18:55:23,326] Trial 185 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.13438428759854235, 'n_estimators': 1420, 'subsample': 0.9343741322804274, 'colsample_bytree': 0.7170666169391289, 'min_child_weight': 10, 'gamma': 0.5551932241038509, 'reg_alpha': 9.262922522545818, 'reg_lambda': 0.00013159745584494074, 'max_delta_step': 9}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  94%|█████████▎| 187/200 [03:00<00:15,  1.16s/it]

[I 2025-11-10 18:55:23,696] Trial 186 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.1019051798994822, 'n_estimators': 1477, 'subsample': 0.9071116730057902, 'colsample_bytree': 0.6561822433106118, 'min_child_weight': 9, 'gamma': 0.5565119936332437, 'reg_alpha': 5.26824743784415, 'reg_lambda': 5.095626278561384e-07, 'max_delta_step': 9}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  94%|█████████▍| 188/200 [03:01<00:16,  1.33s/it]

[I 2025-11-10 18:55:25,455] Trial 187 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.10143619968230237, 'n_estimators': 1461, 'subsample': 0.941722034960106, 'colsample_bytree': 0.6277746993411083, 'min_child_weight': 9, 'gamma': 0.5400013525092431, 'reg_alpha': 5.470444077913785, 'reg_lambda': 0.00013973767352021198, 'max_delta_step': 9}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  94%|█████████▍| 189/200 [03:05<00:20,  1.89s/it]

[I 2025-11-10 18:55:28,669] Trial 188 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.12227130657669849, 'n_estimators': 1466, 'subsample': 0.9354894234278779, 'colsample_bytree': 0.6633915041397686, 'min_child_weight': 9, 'gamma': 0.6494121389688229, 'reg_alpha': 5.162327741111209, 'reg_lambda': 3.798224926250526e-07, 'max_delta_step': 9}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  95%|█████████▌| 190/200 [03:06<00:16,  1.69s/it]

[I 2025-11-10 18:55:29,885] Trial 189 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.10245892914873418, 'n_estimators': 1468, 'subsample': 0.9013724030490441, 'colsample_bytree': 0.8536989894892467, 'min_child_weight': 9, 'gamma': 0.8333127102174755, 'reg_alpha': 4.517322455774377, 'reg_lambda': 4.821673126024214e-07, 'max_delta_step': 8}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:55:29,916] Trial 190 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.12303629299961136, 'n_estimators': 1462, 'subsample': 0.975743175795596, 'colsample_bytree': 0.6390980192930051, 'min_child_weight': 10, 'gamma': 2.7013275157838286, 'reg_alpha': 0.00040397475528662147, 'reg_lambda': 3.505866379706059e-07, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  96%|█████████▋| 193/200 [03:07<00:06,  1.09it/s]

[I 2025-11-10 18:55:31,002] Trial 193 pruned.
[I 2025-11-10 18:55:31,137] Trial 191 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.12199884999007904, 'n_estimators': 1209, 'subsample': 0.5896479265654887, 'colsample_bytree': 0.9692236337386589, 'min_child_weight': 10, 'gamma': 0.7975216692964231, 'reg_alpha': 0.0003638113233550675, 'reg_lambda': 2.355425130003951e-07, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  97%|█████████▋| 194/200 [03:10<00:08,  1.47s/it]

[I 2025-11-10 18:55:34,179] Trial 192 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.05217828275131938, 'n_estimators': 1156, 'subsample': 0.9743173790919893, 'colsample_bytree': 0.8485230279136423, 'min_child_weight': 10, 'gamma': 1.381421339822241, 'reg_alpha': 0.26781592790973635, 'reg_lambda': 8.043110695613135e-06, 'max_delta_step': 5}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  98%|█████████▊| 195/200 [03:11<00:06,  1.24s/it]

[I 2025-11-10 18:55:34,821] Trial 194 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08535724125501767, 'n_estimators': 1099, 'subsample': 0.8762317849380685, 'colsample_bytree': 0.5041459830471485, 'min_child_weight': 10, 'gamma': 1.3842280809183534, 'reg_alpha': 1.7895207115768992, 'reg_lambda': 9.581294009423104e-06, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  98%|█████████▊| 196/200 [03:13<00:05,  1.45s/it]

[I 2025-11-10 18:55:36,795] Trial 198 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09280229895356273, 'n_estimators': 411, 'subsample': 0.5670450445922298, 'colsample_bytree': 0.8827184046792079, 'min_child_weight': 8, 'gamma': 0.30188360663227276, 'reg_alpha': 2.7274647021182514, 'reg_lambda': 1.0098666688685876e-08, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181:  98%|█████████▊| 197/200 [03:13<00:03,  1.17s/it]

[I 2025-11-10 18:55:37,259] Trial 195 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.08807135372376826, 'n_estimators': 1438, 'subsample': 0.8777528339986144, 'colsample_bytree': 0.524651251533865, 'min_child_weight': 10, 'gamma': 0.37046854581401023, 'reg_alpha': 1.7832688591767245, 'reg_lambda': 7.441775656679018e-06, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.
[I 2025-11-10 18:55:37,286] Trial 196 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.08679200185535407, 'n_estimators': 1442, 'subsample': 0.8737819983133477, 'colsample_bytree': 0.5231104792285747, 'min_child_weight': 10, 'gamma': 0.35320571998466155, 'reg_alpha': 2.607201101626301, 'reg_lambda': 1.4110139694512673e-08, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181: 100%|█████████▉| 199/200 [03:15<00:01,  1.12s/it]

[I 2025-11-10 18:55:39,380] Trial 197 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.021376273465659068, 'n_estimators': 1425, 'subsample': 0.9486702655262197, 'colsample_bytree': 0.8851659244172345, 'min_child_weight': 8, 'gamma': 0.394271265671488, 'reg_alpha': 2.0108152175912246, 'reg_lambda': 1.3014597483625783e-08, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

Best trial: 0. Best value: 0.549181: 100%|██████████| 200/200 [03:16<00:00,  1.02it/s]

[I 2025-11-10 18:55:40,253] Trial 199 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.021667236479819756, 'n_estimators': 1432, 'subsample': 0.6647560486674398, 'colsample_bytree': 0.5139787703749186, 'min_child_weight': 5, 'gamma': 0.19282062258962684, 'reg_alpha': 2.272559209954724e-05, 'reg_lambda': 8.923407595555556e-07, 'max_delta_step': 10}. Best is trial 0 with value: 0.5491812865497077.

[I 2025-11-10 18:55:41,600] A new study created in memory with name: 15_1_roc_auc
Best trial: 3. Best value: 0.5:   0%|          | 1/200 [00:03<10:51,  3.28s/it]

[I 2025-11-10 18:55:44,873] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.12882121535722363, 'n_estimators': 837, 'subsample': 0.7702541634081168, 'colsample_bytree': 0.6634249222108726, 'min_child_weight': 8, 'gamma': 0.7401079132348853, 'reg_alpha': 0.007379376960203885, 'reg_lambda': 1.9521880305480414e-06, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   1%|          | 2/200 [00:03<05:31,  1.67s/it]

[I 2025-11-10 18:55:45,424] Trial 0 finished with value: 0.3821052631578947 and parameters: {'max_depth': 7, 'learning_rate': 0.057591085998764516, 'n_estimators': 591, 'subsample': 0.9712210920833452, 'colsample_bytree': 0.8166446000459076, 'min_child_weight': 2, 'gamma': 0.621594843352446, 'reg_alpha': 1.7345278582301644e-06, 'reg_lambda': 0.002195288114737262, 'max_delta_step': 5}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   2%|▏         | 3/200 [00:04<03:45,  1.15s/it]

[I 2025-11-10 18:55:45,938] Trial 2 finished with value: 0.4204873294346978 and parameters: {'max_depth': 3, 'learning_rate': 0.04669654347001681, 'n_estimators': 841, 'subsample': 0.8041469343413017, 'colsample_bytree': 0.5122282335425397, 'min_child_weight': 2, 'gamma': 2.3133854783559737, 'reg_alpha': 0.01657991207640214, 'reg_lambda': 9.382776510867736e-05, 'max_delta_step': 8}. Best is trial 3 with value: 0.5.
[I 2025-11-10 18:55:45,960] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0655084684644127, 'n_estimators': 1166, 'subsample': 0.910467087853241, 'colsample_bytree': 0.5738068698382449, 'min_child_weight': 10, 'gamma': 3.455834134499036, 'reg_alpha': 0.15195470703984706, 'reg_lambda': 0.0002410729749777766, 'max_delta_step': 2}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   2%|▎         | 5/200 [00:06<03:16,  1.01s/it]

[I 2025-11-10 18:55:47,743] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.04779120130317513, 'n_estimators': 413, 'subsample': 0.8545780834402742, 'colsample_bytree': 0.9709280461631178, 'min_child_weight': 6, 'gamma': 1.7442854492670334, 'reg_alpha': 3.0707839604377324e-06, 'reg_lambda': 4.883847518738639e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   3%|▎         | 6/200 [00:06<02:57,  1.09it/s]

[I 2025-11-10 18:55:48,437] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.047706078577706854, 'n_estimators': 757, 'subsample': 0.6121045905977969, 'colsample_bytree': 0.7381103152724654, 'min_child_weight': 7, 'gamma': 1.8820400867700888, 'reg_alpha': 1.1224036304040594e-08, 'reg_lambda': 1.340741483354679, 'max_delta_step': 9}. Best is trial 3 with value: 0.5.

Best trial: 7. Best value: 0.517193:   4%|▎         | 7/200 [00:08<03:28,  1.08s/it]

[I 2025-11-10 18:55:49,908] Trial 7 finished with value: 0.5171929824561403 and parameters: {'max_depth': 3, 'learning_rate': 0.04101532089738766, 'n_estimators': 993, 'subsample': 0.527068397169711, 'colsample_bytree': 0.6036072982217726, 'min_child_weight': 3, 'gamma': 4.460197093444981, 'reg_alpha': 2.6551151097454265e-06, 'reg_lambda': 5.7352513612761583e-05, 'max_delta_step': 5}. Best is trial 7 with value: 0.5171929824561403.

Best trial: 7. Best value: 0.517193:   4%|▍         | 9/200 [00:08<01:58,  1.61it/s]

[I 2025-11-10 18:55:50,151] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.010203960368854868, 'n_estimators': 426, 'subsample': 0.7675732111398608, 'colsample_bytree': 0.528387681579031, 'min_child_weight': 9, 'gamma': 1.2755841355198394, 'reg_alpha': 1.7753480406292592e-08, 'reg_lambda': 5.584392435165289e-07, 'max_delta_step': 10}. Best is trial 7 with value: 0.5171929824561403.
[I 2025-11-10 18:55:50,267] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.014061666919204284, 'n_estimators': 1297, 'subsample': 0.5396773125253116, 'colsample_bytree': 0.970448278543609, 'min_child_weight': 5, 'gamma': 1.275461163193052, 'reg_alpha': 1.493397239718539e-08, 'reg_lambda': 1.5136758152800118, 'max_delta_step': 4}. Best is trial 7 with value: 0.5171929824561403.

Best trial: 7. Best value: 0.517193:   6%|▌         | 11/200 [00:10<02:11,  1.44it/s]

[I 2025-11-10 18:55:51,945] Trial 8 finished with value: 0.4363352826510722 and parameters: {'max_depth': 4, 'learning_rate': 0.07501032923402576, 'n_estimators': 792, 'subsample': 0.9530385181144543, 'colsample_bytree': 0.685432365983231, 'min_child_weight': 3, 'gamma': 4.9098471657046705, 'reg_alpha': 1.0918398825296699e-07, 'reg_lambda': 0.01666240678672463, 'max_delta_step': 0}. Best is trial 7 with value: 0.5171929824561403.
[I 2025-11-10 18:55:52,082] Trial 10 pruned.

Best trial: 7. Best value: 0.517193:   6%|▌         | 12/200 [00:11<02:49,  1.11it/s]

[I 2025-11-10 18:55:53,458] Trial 14 pruned.

Best trial: 11. Best value: 0.536784:   6%|▋         | 13/200 [00:13<03:31,  1.13s/it]

[I 2025-11-10 18:55:55,135] Trial 11 finished with value: 0.5367836257309941 and parameters: {'max_depth': 8, 'learning_rate': 0.04135242397224702, 'n_estimators': 1233, 'subsample': 0.8604259187193921, 'colsample_bytree': 0.6608932836904435, 'min_child_weight': 5, 'gamma': 1.437888081764065, 'reg_alpha': 2.8940001709771297e-07, 'reg_lambda': 9.657416318942669e-06, 'max_delta_step': 8}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:   7%|▋         | 14/200 [00:14<03:26,  1.11s/it]

[I 2025-11-10 18:55:56,199] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.09918325659748012, 'n_estimators': 1397, 'subsample': 0.9021336848948457, 'colsample_bytree': 0.8819221189263624, 'min_child_weight': 7, 'gamma': 4.427851272272141, 'reg_alpha': 2.917119561464927e-06, 'reg_lambda': 0.07938674812163654, 'max_delta_step': 0}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:   8%|▊         | 15/200 [00:15<02:49,  1.09it/s]

[I 2025-11-10 18:55:56,653] Trial 13 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.26324367474260507, 'n_estimators': 1082, 'subsample': 0.658266291532678, 'colsample_bytree': 0.8369762605423194, 'min_child_weight': 4, 'gamma': 3.560780692671746, 'reg_alpha': 9.704340185346936, 'reg_lambda': 2.307371096029391e-08, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:   8%|▊         | 16/200 [00:15<02:24,  1.28it/s]

[I 2025-11-10 18:55:57,134] Trial 17 pruned.

Best trial: 11. Best value: 0.536784:   8%|▊         | 17/200 [00:16<02:29,  1.22it/s]

[I 2025-11-10 18:55:58,035] Trial 15 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.01766533109820511, 'n_estimators': 1102, 'subsample': 0.6741836236546309, 'colsample_bytree': 0.6042730652774806, 'min_child_weight': 10, 'gamma': 3.430822353107997, 'reg_alpha': 6.235931287785333, 'reg_lambda': 9.980199342142584e-05, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:   9%|▉         | 18/200 [00:18<03:25,  1.13s/it]

[I 2025-11-10 18:55:59,872] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.02313306708248847, 'n_estimators': 1074, 'subsample': 0.7003321548425168, 'colsample_bytree': 0.8321622761612928, 'min_child_weight': 5, 'gamma': 2.8987576187772204, 'reg_alpha': 5.2383727055408354e-05, 'reg_lambda': 2.9041499121458145e-05, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  10%|▉         | 19/200 [00:18<02:36,  1.16it/s]

[I 2025-11-10 18:56:00,132] Trial 21 pruned.

Best trial: 11. Best value: 0.536784:  10%|█         | 20/200 [00:19<02:35,  1.15it/s]

[I 2025-11-10 18:56:01,009] Trial 18 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.023529263427756363, 'n_estimators': 1021, 'subsample': 0.5068183693819184, 'colsample_bytree': 0.6355773104687871, 'min_child_weight': 5, 'gamma': 2.643656720787118, 'reg_alpha': 6.895244675434816e-05, 'reg_lambda': 2.295707422577834e-05, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  10%|█         | 21/200 [00:19<02:10,  1.37it/s]

[I 2025-11-10 18:56:01,417] Trial 19 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.02627438733939176, 'n_estimators': 1006, 'subsample': 0.5640313646719237, 'colsample_bytree': 0.7325675228277451, 'min_child_weight': 5, 'gamma': 2.8053630226232507, 'reg_alpha': 7.033139371280625e-05, 'reg_lambda': 1.34224995154272e-05, 'max_delta_step': 6}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  11%|█         | 22/200 [00:21<02:45,  1.08it/s]

[I 2025-11-10 18:56:02,803] Trial 23 pruned.

Best trial: 11. Best value: 0.536784:  12%|█▏        | 23/200 [00:22<03:08,  1.07s/it]

[I 2025-11-10 18:56:04,192] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.02458511800623143, 'n_estimators': 1472, 'subsample': 0.5122002947023444, 'colsample_bytree': 0.7307728275758604, 'min_child_weight': 5, 'gamma': 2.819414639361999, 'reg_alpha': 7.579474777415926e-05, 'reg_lambda': 2.074799977473776e-07, 'max_delta_step': 6}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  12%|█▏        | 24/200 [00:24<04:00,  1.37s/it]

[I 2025-11-10 18:56:06,267] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.14201892504818295, 'n_estimators': 1481, 'subsample': 0.5868536074791418, 'colsample_bytree': 0.7007904621721756, 'min_child_weight': 6, 'gamma': 4.9908801099164535, 'reg_alpha': 5.030178932030904e-05, 'reg_lambda': 1.7402270086488143e-07, 'max_delta_step': 6}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  12%|█▎        | 25/200 [00:25<03:41,  1.27s/it]

[I 2025-11-10 18:56:07,300] Trial 24 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.13302354807412656, 'n_estimators': 1479, 'subsample': 0.8316211120779528, 'colsample_bytree': 0.5706891015897297, 'min_child_weight': 7, 'gamma': 4.2956364266930125, 'reg_alpha': 0.39489552584017173, 'reg_lambda': 0.0011880597710936319, 'max_delta_step': 2}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  13%|█▎        | 26/200 [00:26<03:08,  1.09s/it]

[I 2025-11-10 18:56:07,959] Trial 25 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.0723955791200647, 'n_estimators': 1222, 'subsample': 0.9239154801675872, 'colsample_bytree': 0.5750007640986585, 'min_child_weight': 10, 'gamma': 4.94604259617852, 'reg_alpha': 0.1892770196275581, 'reg_lambda': 0.0011174653186387638, 'max_delta_step': 2}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  14%|█▎        | 27/200 [00:27<03:04,  1.07s/it]

[I 2025-11-10 18:56:08,986] Trial 29 pruned.

Best trial: 11. Best value: 0.536784:  14%|█▍        | 28/200 [00:27<02:26,  1.17it/s]

[I 2025-11-10 18:56:09,344] Trial 26 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.06964873190539893, 'n_estimators': 1219, 'subsample': 0.9193975946996665, 'colsample_bytree': 0.5591175159536581, 'min_child_weight': 10, 'gamma': 4.981107591460607, 'reg_alpha': 0.2558981617311425, 'reg_lambda': 0.0018239093633630173, 'max_delta_step': 2}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  14%|█▍        | 29/200 [00:29<03:29,  1.23s/it]

[I 2025-11-10 18:56:11,441] Trial 27 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03556044431154905, 'n_estimators': 1211, 'subsample': 0.9314788017037697, 'colsample_bytree': 0.5628055801384564, 'min_child_weight': 10, 'gamma': 4.232115723646652, 'reg_alpha': 0.08410975495242366, 'reg_lambda': 0.0006801942485785686, 'max_delta_step': 2}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  16%|█▌        | 31/200 [00:30<02:24,  1.17it/s]

[I 2025-11-10 18:56:12,410] Trial 28 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.035173373100466046, 'n_estimators': 1228, 'subsample': 0.9275853531653574, 'colsample_bytree': 0.5708819623383767, 'min_child_weight': 10, 'gamma': 3.454331469749462, 'reg_alpha': 0.20977584707053923, 'reg_lambda': 0.0004246963152953647, 'max_delta_step': 2}. Best is trial 11 with value: 0.5367836257309941.
[I 2025-11-10 18:56:12,564] Trial 32 pruned.

Best trial: 11. Best value: 0.536784:  16%|█▌        | 32/200 [00:31<02:25,  1.16it/s]

[I 2025-11-10 18:56:13,456] Trial 33 pruned.

Best trial: 11. Best value: 0.536784:  16%|█▋        | 33/200 [00:32<02:07,  1.31it/s]

[I 2025-11-10 18:56:13,999] Trial 30 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.0649445034168826, 'n_estimators': 1177, 'subsample': 0.7297790847416132, 'colsample_bytree': 0.614720024990562, 'min_child_weight': 8, 'gamma': 3.8942031418197196, 'reg_alpha': 9.070489754113308e-06, 'reg_lambda': 4.5567906345142725e-06, 'max_delta_step': 4}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  17%|█▋        | 34/200 [00:32<01:44,  1.58it/s]

[I 2025-11-10 18:56:14,315] Trial 31 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.0354160635141834, 'n_estimators': 1169, 'subsample': 0.7352252702772917, 'colsample_bytree': 0.6267222377509692, 'min_child_weight': 8, 'gamma': 3.8215477369606363, 'reg_alpha': 8.564730619761749e-06, 'reg_lambda': 0.02611818228097405, 'max_delta_step': 4}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  18%|█▊        | 35/200 [00:34<02:57,  1.08s/it]

[I 2025-11-10 18:56:16,433] Trial 34 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.20827334473616338, 'n_estimators': 922, 'subsample': 0.748449850747673, 'colsample_bytree': 0.6512166101751917, 'min_child_weight': 8, 'gamma': 0.4231292866023111, 'reg_alpha': 0.004323693882049345, 'reg_lambda': 2.603726668726537e-06, 'max_delta_step': 10}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  18%|█▊        | 36/200 [00:37<04:03,  1.49s/it]

[I 2025-11-10 18:56:18,868] Trial 35 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.09546229956589548, 'n_estimators': 1351, 'subsample': 0.7775007474023312, 'colsample_bytree': 0.6652385276107485, 'min_child_weight': 8, 'gamma': 0.37818088855936144, 'reg_alpha': 0.0077037001258239805, 'reg_lambda': 3.0013381442227615e-06, 'max_delta_step': 9}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  18%|█▊        | 37/200 [00:38<03:26,  1.27s/it]

[I 2025-11-10 18:56:19,637] Trial 36 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.19709660860640893, 'n_estimators': 1359, 'subsample': 0.8043888739830151, 'colsample_bytree': 0.650363591859117, 'min_child_weight': 9, 'gamma': 0.48342402932827633, 'reg_alpha': 0.006175945947453844, 'reg_lambda': 1.6053250845735754e-06, 'max_delta_step': 9}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  19%|█▉        | 38/200 [00:38<02:33,  1.06it/s]

[I 2025-11-10 18:56:19,831] Trial 37 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.09372565324808692, 'n_estimators': 1348, 'subsample': 0.7791015411036336, 'colsample_bytree': 0.6653761465928205, 'min_child_weight': 8, 'gamma': 0.46279715811570615, 'reg_alpha': 0.009890813863068247, 'reg_lambda': 2.0374911899568e-06, 'max_delta_step': 9}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  20%|█▉        | 39/200 [00:40<03:12,  1.20s/it]

[I 2025-11-10 18:56:21,608] Trial 39 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.09938677790860136, 'n_estimators': 635, 'subsample': 0.8012330872945664, 'colsample_bytree': 0.5150815223744935, 'min_child_weight': 9, 'gamma': 0.8149017637506172, 'reg_alpha': 0.04568592833040535, 'reg_lambda': 0.00014447997763302495, 'max_delta_step': 9}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  20%|██        | 40/200 [00:40<02:32,  1.05it/s]

[I 2025-11-10 18:56:21,992] Trial 38 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.08238029458204979, 'n_estimators': 1319, 'subsample': 0.7848837061186401, 'colsample_bytree': 0.6752003342947857, 'min_child_weight': 9, 'gamma': 0.8696076212849769, 'reg_alpha': 0.021961965706455783, 'reg_lambda': 0.00012777339759546534, 'max_delta_step': 9}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  20%|██        | 41/200 [00:41<02:30,  1.06it/s]

[I 2025-11-10 18:56:22,926] Trial 41 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.051266028121150185, 'n_estimators': 684, 'subsample': 0.8717245756775187, 'colsample_bytree': 0.7855629682502618, 'min_child_weight': 6, 'gamma': 1.0766407681173022, 'reg_alpha': 0.02440886004351038, 'reg_lambda': 0.0001047434883414429, 'max_delta_step': 8}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  21%|██        | 42/200 [00:41<01:58,  1.34it/s]

[I 2025-11-10 18:56:23,203] Trial 40 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.0902224972446174, 'n_estimators': 825, 'subsample': 0.8730971696914858, 'colsample_bytree': 0.502100062858509, 'min_child_weight': 9, 'gamma': 1.1385160822217806, 'reg_alpha': 0.04786002138846182, 'reg_lambda': 0.0001417582580544001, 'max_delta_step': 8}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  22%|██▏       | 43/200 [00:43<02:48,  1.07s/it]

[I 2025-11-10 18:56:25,044] Trial 42 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.054581743354052095, 'n_estimators': 801, 'subsample': 0.8755222559001177, 'colsample_bytree': 0.7663972583165394, 'min_child_weight': 6, 'gamma': 1.507113472663099, 'reg_alpha': 4.919627290209047e-08, 'reg_lambda': 1.0175569094302524e-05, 'max_delta_step': 8}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  22%|██▏       | 44/200 [00:44<02:26,  1.06it/s]

[I 2025-11-10 18:56:25,672] Trial 43 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.04992995900112446, 'n_estimators': 832, 'subsample': 0.8577415778740616, 'colsample_bytree': 0.7757994782094667, 'min_child_weight': 6, 'gamma': 1.5806429850705173, 'reg_alpha': 5.815314032457981e-08, 'reg_lambda': 1.2784087485073143e-05, 'max_delta_step': 8}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  22%|██▎       | 45/200 [00:44<01:59,  1.30it/s]

[I 2025-11-10 18:56:26,043] Trial 46 pruned.

Best trial: 11. Best value: 0.536784:  23%|██▎       | 46/200 [00:44<01:39,  1.54it/s]

[I 2025-11-10 18:56:26,402] Trial 44 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.010556019852138778, 'n_estimators': 777, 'subsample': 0.6110323110421559, 'colsample_bytree': 0.9214921405071839, 'min_child_weight': 7, 'gamma': 1.3282021368314083, 'reg_alpha': 4.526777366459833e-08, 'reg_lambda': 0.2690983776327872, 'max_delta_step': 5}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  24%|██▎       | 47/200 [00:45<01:22,  1.85it/s]

[I 2025-11-10 18:56:26,696] Trial 45 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.011564727649340249, 'n_estimators': 756, 'subsample': 0.6198358677497797, 'colsample_bytree': 0.9495594802068331, 'min_child_weight': 7, 'gamma': 1.5316552280961873, 'reg_alpha': 2.8780728159263106e-08, 'reg_lambda': 0.4696044672933347, 'max_delta_step': 5}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  24%|██▍       | 48/200 [00:49<03:56,  1.55s/it]

[I 2025-11-10 18:56:30,615] Trial 47 finished with value: 0.4866666666666667 and parameters: {'max_depth': 5, 'learning_rate': 0.013805026169948548, 'n_estimators': 1128, 'subsample': 0.6290483801446861, 'colsample_bytree': 0.9482958796074054, 'min_child_weight': 4, 'gamma': 2.0743515116239446, 'reg_alpha': 1.3285763866152611e-08, 'reg_lambda': 7.240333656625632, 'max_delta_step': 5}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  25%|██▌       | 50/200 [00:50<02:31,  1.01s/it]

[I 2025-11-10 18:56:31,560] Trial 48 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.018443773986689057, 'n_estimators': 1286, 'subsample': 0.5507324010018116, 'colsample_bytree': 0.8951108909537292, 'min_child_weight': 4, 'gamma': 3.192040721280131, 'reg_alpha': 1.035536673383732e-06, 'reg_lambda': 6.371074926762011, 'max_delta_step': 5}. Best is trial 11 with value: 0.5367836257309941.
[I 2025-11-10 18:56:31,718] Trial 51 pruned.

Best trial: 11. Best value: 0.536784:  26%|██▌       | 51/200 [00:50<01:51,  1.34it/s]

[I 2025-11-10 18:56:31,852] Trial 49 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.01492643150330019, 'n_estimators': 1270, 'subsample': 0.5562422401080703, 'colsample_bytree': 0.8833101990974672, 'min_child_weight': 4, 'gamma': 2.297620676700635, 'reg_alpha': 1.3538609546069398e-08, 'reg_lambda': 2.352289983565547, 'max_delta_step': 3}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  26%|██▌       | 52/200 [00:50<01:35,  1.55it/s]

[I 2025-11-10 18:56:32,269] Trial 50 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.016118981344570224, 'n_estimators': 1290, 'subsample': 0.5660284328957192, 'colsample_bytree': 0.8866687671166257, 'min_child_weight': 4, 'gamma': 3.1019506159554804, 'reg_alpha': 1.1777917530146923e-08, 'reg_lambda': 9.778325916342072e-07, 'max_delta_step': 10}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  26%|██▋       | 53/200 [00:51<01:21,  1.79it/s]

[I 2025-11-10 18:56:32,616] Trial 52 pruned.

Best trial: 11. Best value: 0.536784:  28%|██▊       | 55/200 [00:51<00:53,  2.72it/s]

[I 2025-11-10 18:56:32,821] Trial 55 pruned.
[I 2025-11-10 18:56:32,994] Trial 53 pruned.

Best trial: 11. Best value: 0.536784:  28%|██▊       | 56/200 [00:52<01:23,  1.72it/s]

[I 2025-11-10 18:56:34,072] Trial 54 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.0449579873026819, 'n_estimators': 473, 'subsample': 0.5363009405822856, 'colsample_bytree': 0.9977005345998197, 'min_child_weight': 5, 'gamma': 4.493566826605474, 'reg_alpha': 0.001133156876334674, 'reg_lambda': 1.4787881629692248, 'max_delta_step': 10}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  28%|██▊       | 57/200 [00:53<01:39,  1.44it/s]

[I 2025-11-10 18:56:35,028] Trial 56 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.04033880794911863, 'n_estimators': 572, 'subsample': 0.5274404396545611, 'colsample_bytree': 0.7075401979544296, 'min_child_weight': 5, 'gamma': 4.642863749385054, 'reg_alpha': 1.0713809692286205, 'reg_lambda': 1.9293992649771694, 'max_delta_step': 1}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  29%|██▉       | 58/200 [00:55<02:20,  1.01it/s]

[I 2025-11-10 18:56:36,709] Trial 58 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.028462944798633056, 'n_estimators': 871, 'subsample': 0.5350389169640615, 'colsample_bytree': 0.8138794361339675, 'min_child_weight': 7, 'gamma': 4.706919998947431, 'reg_alpha': 1.3069617127870994, 'reg_lambda': 3.8551570478815314e-05, 'max_delta_step': 10}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  30%|██▉       | 59/200 [00:56<02:44,  1.16s/it]

[I 2025-11-10 18:56:38,280] Trial 60 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.030126207652034255, 'n_estimators': 726, 'subsample': 0.5905130846596414, 'colsample_bytree': 0.8458143449236896, 'min_child_weight': 7, 'gamma': 0.08717719404000701, 'reg_alpha': 2.1358224547966183e-06, 'reg_lambda': 2.138453641883018e-05, 'max_delta_step': 0}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  30%|███       | 60/200 [00:56<02:06,  1.11it/s]

[I 2025-11-10 18:56:38,577] Trial 59 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.02991405805386251, 'n_estimators': 1047, 'subsample': 0.5310117582268533, 'colsample_bytree': 0.7099598879408262, 'min_child_weight': 7, 'gamma': 0.8473833019250844, 'reg_alpha': 2.685568269827204e-06, 'reg_lambda': 2.52119625497298e-05, 'max_delta_step': 0}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  30%|███       | 61/200 [00:57<01:44,  1.33it/s]

[I 2025-11-10 18:56:38,974] Trial 57 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.044460771927453645, 'n_estimators': 1417, 'subsample': 0.528784697967055, 'colsample_bytree': 0.8072005219103787, 'min_child_weight': 7, 'gamma': 0.08886655126735077, 'reg_alpha': 1.7440843069061514e-07, 'reg_lambda': 3.887448597585048e-05, 'max_delta_step': 10}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  31%|███       | 62/200 [00:57<01:25,  1.62it/s]

[I 2025-11-10 18:56:39,274] Trial 62 pruned.

Best trial: 11. Best value: 0.536784:  32%|███▏      | 63/200 [00:57<01:10,  1.94it/s]

[I 2025-11-10 18:56:39,549] Trial 63 pruned.

Best trial: 11. Best value: 0.536784:  32%|███▏      | 64/200 [00:58<01:24,  1.60it/s]

[I 2025-11-10 18:56:40,433] Trial 65 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.02202660974984783, 'n_estimators': 244, 'subsample': 0.8220944424095914, 'colsample_bytree': 0.5436752803723789, 'min_child_weight': 6, 'gamma': 1.811389677389583, 'reg_alpha': 0.0013624498246936156, 'reg_lambda': 5.880668532140805e-06, 'max_delta_step': 6}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  32%|███▎      | 65/200 [00:59<01:07,  1.99it/s]

[I 2025-11-10 18:56:40,647] Trial 64 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.17299956083566564, 'n_estimators': 328, 'subsample': 0.8410366698395344, 'colsample_bytree': 0.857522229683966, 'min_child_weight': 6, 'gamma': 1.7836937242556283, 'reg_alpha': 2.268730684644766e-05, 'reg_lambda': 5.5318561559408355e-08, 'max_delta_step': 6}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  33%|███▎      | 66/200 [00:59<01:22,  1.63it/s]

[I 2025-11-10 18:56:41,517] Trial 61 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.021600735232704178, 'n_estimators': 1067, 'subsample': 0.6643691904750553, 'colsample_bytree': 0.7159628366464367, 'min_child_weight': 6, 'gamma': 1.3262045799527165, 'reg_alpha': 2.3003683866702113e-06, 'reg_lambda': 3.117473125151615e-07, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  34%|███▎      | 67/200 [01:00<01:11,  1.85it/s]

[I 2025-11-10 18:56:41,887] Trial 67 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.059660051618153284, 'n_estimators': 316, 'subsample': 0.6819225346483662, 'colsample_bytree': 0.7450476567480527, 'min_child_weight': 6, 'gamma': 4.137337147729275, 'reg_alpha': 3.122210871249713e-05, 'reg_lambda': 0.0002975468840319174, 'max_delta_step': 4}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  34%|███▍      | 68/200 [01:03<02:38,  1.20s/it]

[I 2025-11-10 18:56:44,619] Trial 66 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.038944863935566544, 'n_estimators': 1171, 'subsample': 0.8432153456605891, 'colsample_bytree': 0.7422948846825217, 'min_child_weight': 6, 'gamma': 4.115343631515703, 'reg_alpha': 0.0017116601698176244, 'reg_lambda': 8.480237157341488e-06, 'max_delta_step': 4}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  34%|███▍      | 69/200 [01:04<02:42,  1.24s/it]

[I 2025-11-10 18:56:45,946] Trial 68 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.03888258734820703, 'n_estimators': 1160, 'subsample': 0.6537072746522785, 'colsample_bytree': 0.9679725690180501, 'min_child_weight': 6, 'gamma': 4.1955640750460885, 'reg_alpha': 4.279505866608111e-06, 'reg_lambda': 6.893743340096101e-06, 'max_delta_step': 4}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  35%|███▌      | 70/200 [01:04<02:08,  1.01it/s]

[I 2025-11-10 18:56:46,370] Trial 69 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.06358988687537619, 'n_estimators': 1135, 'subsample': 0.9396204941901486, 'colsample_bytree': 0.7473064783272534, 'min_child_weight': 8, 'gamma': 0.6450163300681019, 'reg_alpha': 2.0995172317005155e-05, 'reg_lambda': 0.00025640550916554254, 'max_delta_step': 4}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  36%|███▌      | 71/200 [01:05<01:56,  1.10it/s]

[I 2025-11-10 18:56:47,064] Trial 70 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.039556768429343796, 'n_estimators': 1165, 'subsample': 0.9465226871108493, 'colsample_bytree': 0.9713767172931157, 'min_child_weight': 8, 'gamma': 0.6215256158624121, 'reg_alpha': 6.238992502936423e-06, 'reg_lambda': 6.587672784537997e-06, 'max_delta_step': 4}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  36%|███▌      | 72/200 [01:06<02:00,  1.06it/s]

[I 2025-11-10 18:56:48,099] Trial 73 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.07742525974661106, 'n_estimators': 397, 'subsample': 0.9070692070072977, 'colsample_bytree': 0.6888950618186781, 'min_child_weight': 10, 'gamma': 2.224751202960566, 'reg_alpha': 2.1434691281717464e-08, 'reg_lambda': 7.631942749958556e-05, 'max_delta_step': 9}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  36%|███▋      | 73/200 [01:07<01:45,  1.21it/s]

[I 2025-11-10 18:56:48,657] Trial 72 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.06926309513642322, 'n_estimators': 626, 'subsample': 0.9446772334841389, 'colsample_bytree': 0.6352786372358167, 'min_child_weight': 8, 'gamma': 2.2162839030925356, 'reg_alpha': 8.413791132438304e-08, 'reg_lambda': 0.0002739410450191146, 'max_delta_step': 1}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  37%|███▋      | 74/200 [01:07<01:26,  1.46it/s]

[I 2025-11-10 18:56:49,003] Trial 74 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.07848038003611152, 'n_estimators': 422, 'subsample': 0.7015497111259729, 'colsample_bytree': 0.6342017661635563, 'min_child_weight': 9, 'gamma': 0.9415053166158595, 'reg_alpha': 2.762892857728769e-08, 'reg_lambda': 3.7729689780440563e-07, 'max_delta_step': 9}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  38%|███▊      | 75/200 [01:08<01:55,  1.08it/s]

[I 2025-11-10 18:56:50,486] Trial 76 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.010383318539004786, 'n_estimators': 410, 'subsample': 0.7637706802096677, 'colsample_bytree': 0.5340328234313503, 'min_child_weight': 9, 'gamma': 1.1881673628360923, 'reg_alpha': 3.4489383642550007e-07, 'reg_lambda': 3.584235986596813e-07, 'max_delta_step': 9}. Best is trial 11 with value: 0.5367836257309941.
[I 2025-11-10 18:56:50,519] Trial 71 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.08127622909845855, 'n_estimators': 1389, 'subsample': 0.9492706159568257, 'colsample_bytree': 0.6394698209131253, 'min_child_weight': 8, 'gamma': 2.2623094446823115, 'reg_alpha': 4.415090888458416e-06, 'reg_lambda': 0.12328791938492248, 'max_delta_step': 1}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  38%|███▊      | 77/200 [01:09<01:20,  1.52it/s]

[I 2025-11-10 18:56:51,185] Trial 77 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.010223650975736806, 'n_estimators': 516, 'subsample': 0.7566439977984898, 'colsample_bytree': 0.523264176713484, 'min_child_weight': 9, 'gamma': 1.1901891627155652, 'reg_alpha': 0.00016271925263381548, 'reg_lambda': 3.3611201098426444e-06, 'max_delta_step': 10}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  39%|███▉      | 78/200 [01:11<01:53,  1.07it/s]

[I 2025-11-10 18:56:52,958] Trial 78 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.25124602669157237, 'n_estimators': 545, 'subsample': 0.8057827319532636, 'colsample_bytree': 0.6109660350259022, 'min_child_weight': 10, 'gamma': 1.4463899121621109, 'reg_alpha': 0.0028953318135300633, 'reg_lambda': 1.1995765952217331e-06, 'max_delta_step': 10}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  40%|███▉      | 79/200 [01:12<01:47,  1.13it/s]

[I 2025-11-10 18:56:53,713] Trial 79 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.032697866033711956, 'n_estimators': 716, 'subsample': 0.797306407471186, 'colsample_bytree': 0.6050126008939695, 'min_child_weight': 10, 'gamma': 1.4171194841478172, 'reg_alpha': 0.00019997324718021254, 'reg_lambda': 1.2096319861067573e-06, 'max_delta_step': 10}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  40%|████      | 80/200 [01:12<01:30,  1.32it/s]

[I 2025-11-10 18:56:54,122] Trial 75 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.032764058071911066, 'n_estimators': 1399, 'subsample': 0.7614666199054703, 'colsample_bytree': 0.6326980717112008, 'min_child_weight': 9, 'gamma': 0.9938901020600205, 'reg_alpha': 7.916919356672663e-08, 'reg_lambda': 5.046167580023878e-07, 'max_delta_step': 9}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  40%|████      | 81/200 [01:13<01:30,  1.31it/s]

[I 2025-11-10 18:56:54,888] Trial 82 pruned.

Best trial: 11. Best value: 0.536784:  41%|████      | 82/200 [01:14<01:53,  1.04it/s]

[I 2025-11-10 18:56:56,349] Trial 80 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.051951106347986165, 'n_estimators': 1204, 'subsample': 0.8093085173303052, 'colsample_bytree': 0.6110354750363963, 'min_child_weight': 10, 'gamma': 0.9954115671538539, 'reg_alpha': 7.248529884059621e-07, 'reg_lambda': 1.498759818633045e-06, 'max_delta_step': 8}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  42%|████▏     | 84/200 [01:17<02:07,  1.10s/it]

[I 2025-11-10 18:56:59,196] Trial 81 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04637217068019676, 'n_estimators': 1429, 'subsample': 0.5822249262485023, 'colsample_bytree': 0.5999258514248546, 'min_child_weight': 10, 'gamma': 2.6161630417636825, 'reg_alpha': 1.2621210836296158e-06, 'reg_lambda': 6.654357709047396e-05, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.
[I 2025-11-10 18:56:59,310] Trial 83 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.050272506169301956, 'n_estimators': 1215, 'subsample': 0.8225678746819965, 'colsample_bytree': 0.5811307612378102, 'min_child_weight': 5, 'gamma': 2.6769883436287305, 'reg_alpha': 7.737874366297257e-07, 'reg_lambda': 5.6263720929964564e-05, 'max_delta_step': 8}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  43%|████▎     | 86/200 [01:18<01:32,  1.23it/s]

[I 2025-11-10 18:57:00,448] Trial 85 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.10550587025028936, 'n_estimators': 954, 'subsample': 0.8883848424018982, 'colsample_bytree': 0.5563582944874895, 'min_child_weight': 7, 'gamma': 1.6470087559324162, 'reg_alpha': 0.11676739970602187, 'reg_lambda': 2.9358516726242163, 'max_delta_step': 2}. Best is trial 11 with value: 0.5367836257309941.
[I 2025-11-10 18:57:00,559] Trial 84 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.1111591283292579, 'n_estimators': 1333, 'subsample': 0.8560340637966829, 'colsample_bytree': 0.563161990911214, 'min_child_weight': 7, 'gamma': 1.6308705526114724, 'reg_alpha': 5.543680658975823e-07, 'reg_lambda': 3.013801444165123, 'max_delta_step': 8}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  44%|████▎     | 87/200 [01:23<03:24,  1.81s/it]

[I 2025-11-10 18:57:04,736] Trial 86 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.13278515358393117, 'n_estimators': 1315, 'subsample': 0.8656944320554805, 'colsample_bytree': 0.5585545113342762, 'min_child_weight': 7, 'gamma': 1.6530335411987973, 'reg_alpha': 1.8849193124713013e-08, 'reg_lambda': 4.320622378360678, 'max_delta_step': 2}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  44%|████▍     | 88/200 [01:23<02:39,  1.43s/it]

[I 2025-11-10 18:57:05,246] Trial 87 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.10713607233958564, 'n_estimators': 1326, 'subsample': 0.8907578308452476, 'colsample_bytree': 0.9194243211641042, 'min_child_weight': 7, 'gamma': 4.415571565463363, 'reg_alpha': 2.330902941750121e-08, 'reg_lambda': 3.0853168371797097, 'max_delta_step': 2}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  44%|████▍     | 89/200 [01:25<02:44,  1.48s/it]

[I 2025-11-10 18:57:06,854] Trial 88 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.08677479603759898, 'n_estimators': 1455, 'subsample': 0.9088542101777934, 'colsample_bytree': 0.9173927789654907, 'min_child_weight': 7, 'gamma': 4.44742213978494, 'reg_alpha': 1.2821684711505974e-05, 'reg_lambda': 0.4122054376430889, 'max_delta_step': 0}. Best is trial 11 with value: 0.5367836257309941.
[I 2025-11-10 18:57:06,888] Trial 89 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1273118177297727, 'n_estimators': 1450, 'subsample': 0.9214968250494515, 'colsample_bytree': 0.915363298128768, 'min_child_weight': 8, 'gamma': 1.9449359983755612, 'reg_alpha': 1.982444224305863e-08, 'reg_lambda': 0.43045552864742226, 'max_delta_step': 0}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  46%|████▌     | 91/200 [01:28<02:40,  1.47s/it]

[I 2025-11-10 18:57:09,767] Trial 90 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.14160997798906663, 'n_estimators': 1096, 'subsample': 0.8870798516968181, 'colsample_bytree': 0.9260700169533441, 'min_child_weight': 8, 'gamma': 4.453935038342869, 'reg_alpha': 0.5433915200003785, 'reg_lambda': 0.6770534645137515, 'max_delta_step': 5}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  46%|████▌     | 92/200 [01:28<02:05,  1.16s/it]

[I 2025-11-10 18:57:09,990] Trial 91 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.08815003641899201, 'n_estimators': 1094, 'subsample': 0.7394933663715463, 'colsample_bytree': 0.6634620146300791, 'min_child_weight': 8, 'gamma': 1.951657178883518, 'reg_alpha': 5.592177852354834, 'reg_lambda': 1.081724750708962, 'max_delta_step': 5}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  47%|████▋     | 94/200 [01:31<02:00,  1.14s/it]

[I 2025-11-10 18:57:12,509] Trial 92 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.12811990248615146, 'n_estimators': 1372, 'subsample': 0.9195913796216405, 'colsample_bytree': 0.6641424968022412, 'min_child_weight': 8, 'gamma': 4.800019613872436, 'reg_alpha': 1.071288536277582e-08, 'reg_lambda': 0.9196654616735606, 'max_delta_step': 5}. Best is trial 11 with value: 0.5367836257309941.
[I 2025-11-10 18:57:12,634] Trial 93 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.011755565464719573, 'n_estimators': 1382, 'subsample': 0.5169577363075006, 'colsample_bytree': 0.6566624349661437, 'min_child_weight': 9, 'gamma': 4.742674854542423, 'reg_alpha': 1.0009463478850415e-08, 'reg_lambda': 1.0010680365591502, 'max_delta_step': 5}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  48%|████▊     | 95/200 [01:31<01:52,  1.07s/it]

[I 2025-11-10 18:57:13,540] Trial 97 pruned.

Best trial: 11. Best value: 0.536784:  48%|████▊     | 96/200 [01:32<01:34,  1.10it/s]

[I 2025-11-10 18:57:14,045] Trial 94 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.29541048336701503, 'n_estimators': 1011, 'subsample': 0.6035801676423909, 'colsample_bytree': 0.6592041966832021, 'min_child_weight': 4, 'gamma': 4.802914790992471, 'reg_alpha': 2.374246061421338, 'reg_lambda': 4.5366924142461764e-08, 'max_delta_step': 9}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  48%|████▊     | 97/200 [01:32<01:18,  1.32it/s]

[I 2025-11-10 18:57:14,424] Trial 95 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.25501506349800235, 'n_estimators': 1010, 'subsample': 0.5462548011306129, 'colsample_bytree': 0.8626354262407343, 'min_child_weight': 4, 'gamma': 3.911731727833991, 'reg_alpha': 5.451679882746819, 'reg_lambda': 1.0524707198300019e-08, 'max_delta_step': 9}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  49%|████▉     | 98/200 [01:33<01:09,  1.47it/s]

[I 2025-11-10 18:57:14,925] Trial 99 pruned.

Best trial: 11. Best value: 0.536784:  50%|████▉     | 99/200 [01:34<01:09,  1.46it/s]

[I 2025-11-10 18:57:15,623] Trial 100 pruned.

Best trial: 11. Best value: 0.536784:  50%|█████     | 100/200 [01:37<02:24,  1.44s/it]

[I 2025-11-10 18:57:18,866] Trial 96 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.25168340634558684, 'n_estimators': 1260, 'subsample': 0.7207450742924996, 'colsample_bytree': 0.9493438601380798, 'min_child_weight': 3, 'gamma': 3.377289707734218, 'reg_alpha': 8.417125024068715, 'reg_lambda': 6.536582820491972e-08, 'max_delta_step': 9}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  50%|█████     | 101/200 [01:37<01:53,  1.15s/it]

[I 2025-11-10 18:57:19,310] Trial 98 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.23211148525052566, 'n_estimators': 1246, 'subsample': 0.6029511958248235, 'colsample_bytree': 0.9582083078859203, 'min_child_weight': 3, 'gamma': 3.322038450684854, 'reg_alpha': 5.591269574653673, 'reg_lambda': 1.1100647934912399e-07, 'max_delta_step': 8}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  52%|█████▏    | 104/200 [01:39<01:02,  1.54it/s]

[I 2025-11-10 18:57:20,476] Trial 101 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.05827272967392972, 'n_estimators': 1256, 'subsample': 0.6395294513969864, 'colsample_bytree': 0.9595369308575898, 'min_child_weight': 5, 'gamma': 4.298584617079995, 'reg_alpha': 0.012990956196174389, 'reg_lambda': 0.0044543497546350895, 'max_delta_step': 8}. Best is trial 11 with value: 0.5367836257309941.
[I 2025-11-10 18:57:20,569] Trial 103 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.05839855611836571, 'n_estimators': 360, 'subsample': 0.7854697543316851, 'colsample_bytree': 0.7249520462819085, 'min_child_weight': 5, 'gamma': 4.285656272685187, 'reg_alpha': 0.04041738019240721, 'reg_lambda': 0.003318536755406077, 'max_delta_step': 8}. Best is trial 11 with value: 0.5367836257309941.
[I 2025-11-10 18:57:20,593] Trial 102 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.05762055313275312, 'n_estimators': 1193, 'subsample': 0.7080537318298886, 'colsample_bytree': 0.6803166145773805, 'min_child_weight': 5, 'gamma': 4.31271620939662, 'reg_alpha': 0.0401540996004082, 'reg_lambda': 0.0062812214378543335, 'max_delta_step': 8}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  52%|█████▎    | 105/200 [01:40<01:17,  1.23it/s]

[I 2025-11-10 18:57:21,904] Trial 105 pruned.
[I 2025-11-10 18:57:21,920] Trial 107 pruned.

Best trial: 11. Best value: 0.536784:  54%|█████▎    | 107/200 [01:42<01:24,  1.10it/s]

[I 2025-11-10 18:57:23,988] Trial 104 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.016270718064430582, 'n_estimators': 1079, 'subsample': 0.669965346672047, 'colsample_bytree': 0.6804819672842916, 'min_child_weight': 5, 'gamma': 3.5376331837288983, 'reg_alpha': 2.9122837442111558, 'reg_lambda': 0.18194521045441908, 'max_delta_step': 6}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  54%|█████▍    | 108/200 [01:43<01:27,  1.06it/s]

[I 2025-11-10 18:57:25,067] Trial 106 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.014532525887009116, 'n_estimators': 1069, 'subsample': 0.5845476321208931, 'colsample_bytree': 0.6768338610081183, 'min_child_weight': 10, 'gamma': 0.28119660725196527, 'reg_alpha': 2.087898040927079, 'reg_lambda': 3.623577821886822e-06, 'max_delta_step': 6}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  55%|█████▍    | 109/200 [01:44<01:17,  1.17it/s]

[I 2025-11-10 18:57:25,635] Trial 109 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.013473961208574513, 'n_estimators': 809, 'subsample': 0.6609000079451214, 'colsample_bytree': 0.9031236051968087, 'min_child_weight': 10, 'gamma': 2.889000661228321, 'reg_alpha': 1.0832795852272876, 'reg_lambda': 0.0018118924212084761, 'max_delta_step': 6}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  55%|█████▌    | 110/200 [01:44<01:08,  1.32it/s]

[I 2025-11-10 18:57:26,112] Trial 110 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.15217443283267573, 'n_estimators': 466, 'subsample': 0.579949481376937, 'colsample_bytree': 0.7593868783860355, 'min_child_weight': 10, 'gamma': 2.970385949423047, 'reg_alpha': 9.899498904020135, 'reg_lambda': 1.6555475686764657e-05, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  56%|█████▌    | 111/200 [01:45<01:02,  1.42it/s]

[I 2025-11-10 18:57:26,673] Trial 108 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.013392399086637134, 'n_estimators': 1067, 'subsample': 0.518617572639087, 'colsample_bytree': 0.7626738237348422, 'min_child_weight': 10, 'gamma': 2.812694324272358, 'reg_alpha': 0.3827867821950201, 'reg_lambda': 0.0005008228413640036, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  56%|█████▌    | 112/200 [01:46<01:11,  1.23it/s]

[I 2025-11-10 18:57:27,761] Trial 112 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.02552262862782039, 'n_estimators': 461, 'subsample': 0.5733946629199891, 'colsample_bytree': 0.9334816678886847, 'min_child_weight': 6, 'gamma': 3.069783733155102, 'reg_alpha': 9.829821181600405, 'reg_lambda': 0.0005368333515992743, 'max_delta_step': 10}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  56%|█████▋    | 113/200 [01:47<01:12,  1.20it/s]

[I 2025-11-10 18:57:28,653] Trial 115 pruned.

Best trial: 11. Best value: 0.536784:  57%|█████▋    | 114/200 [01:47<00:55,  1.54it/s]

[I 2025-11-10 18:57:28,855] Trial 111 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.15441968828363123, 'n_estimators': 844, 'subsample': 0.7443959036765156, 'colsample_bytree': 0.9850712928651058, 'min_child_weight': 9, 'gamma': 2.9553962814376744, 'reg_alpha': 0.0004984972606189563, 'reg_lambda': 0.000615670078789861, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  57%|█████▊    | 115/200 [01:48<01:17,  1.10it/s]

[I 2025-11-10 18:57:30,387] Trial 113 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.01133253899030552, 'n_estimators': 968, 'subsample': 0.7713758179619928, 'colsample_bytree': 0.9382124937548908, 'min_child_weight': 6, 'gamma': 3.775673520787039, 'reg_alpha': 1.1776194344383383e-07, 'reg_lambda': 9.853932828703815, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  58%|█████▊    | 116/200 [01:49<01:10,  1.20it/s]

[I 2025-11-10 18:57:31,043] Trial 114 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.025642910107804742, 'n_estimators': 974, 'subsample': 0.7743169277807568, 'colsample_bytree': 0.8441385469549714, 'min_child_weight': 6, 'gamma': 3.2521324987379265, 'reg_alpha': 5.0015293202485414e-06, 'reg_lambda': 3.549269764920094e-05, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  58%|█████▊    | 117/200 [01:51<01:31,  1.11s/it]

[I 2025-11-10 18:57:32,798] Trial 116 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.023768441226478525, 'n_estimators': 905, 'subsample': 0.6889557746471618, 'colsample_bytree': 0.9820453423542975, 'min_child_weight': 6, 'gamma': 0.6945447636916456, 'reg_alpha': 4.337485985365703e-06, 'reg_lambda': 2.7581892600230033e-05, 'max_delta_step': 1}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  59%|█████▉    | 118/200 [01:51<01:13,  1.12it/s]

[I 2025-11-10 18:57:33,179] Trial 117 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.02380310489003796, 'n_estimators': 979, 'subsample': 0.6940876984307647, 'colsample_bytree': 0.8373218606027681, 'min_child_weight': 5, 'gamma': 2.4255390845551634, 'reg_alpha': 8.584126849683695e-05, 'reg_lambda': 3.2039691504666736e-05, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  60%|█████▉    | 119/200 [01:52<01:13,  1.10it/s]

[I 2025-11-10 18:57:34,130] Trial 121 pruned.

Best trial: 11. Best value: 0.536784:  60%|██████    | 120/200 [01:53<01:20,  1.01s/it]

[I 2025-11-10 18:57:35,367] Trial 118 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.042663175827017265, 'n_estimators': 1112, 'subsample': 0.6904078470389596, 'colsample_bytree': 0.846137376342449, 'min_child_weight': 5, 'gamma': 3.2362019020913504, 'reg_alpha': 5.1784140027612394e-05, 'reg_lambda': 2.6281312295399272e-05, 'max_delta_step': 8}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  60%|██████    | 121/200 [01:54<01:22,  1.05s/it]

[I 2025-11-10 18:57:36,503] Trial 123 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.03720734619521218, 'n_estimators': 244, 'subsample': 0.8504373069712797, 'colsample_bytree': 0.6946087151696438, 'min_child_weight': 9, 'gamma': 3.981342777857516, 'reg_alpha': 0.158184938705419, 'reg_lambda': 0.058481709466918705, 'max_delta_step': 10}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  62%|██████▏   | 123/200 [01:56<00:59,  1.30it/s]

[I 2025-11-10 18:57:37,528] Trial 122 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03675361964781295, 'n_estimators': 768, 'subsample': 0.8459709407999796, 'colsample_bytree': 0.6961658710880329, 'min_child_weight': 5, 'gamma': 1.1490645421458274, 'reg_alpha': 6.49128236980272e-08, 'reg_lambda': 0.046668916797538706, 'max_delta_step': 8}. Best is trial 11 with value: 0.5367836257309941.
[I 2025-11-10 18:57:37,668] Trial 119 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.042923165332826876, 'n_estimators': 1500, 'subsample': 0.6878451697833399, 'colsample_bytree': 0.6964721169079257, 'min_child_weight': 5, 'gamma': 0.7187586356349713, 'reg_alpha': 0.00010015271269164914, 'reg_lambda': 0.03644231226396102, 'max_delta_step': 1}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  62%|██████▏   | 124/200 [01:56<00:49,  1.53it/s]

[I 2025-11-10 18:57:38,046] Trial 120 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04407996542264414, 'n_estimators': 1127, 'subsample': 0.6510703372965634, 'colsample_bytree': 0.8314714506699503, 'min_child_weight': 5, 'gamma': 2.3930364180162744, 'reg_alpha': 1.0976292619947864e-05, 'reg_lambda': 0.00016127233776656465, 'max_delta_step': 8}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  62%|██████▎   | 125/200 [01:57<00:56,  1.34it/s]

[I 2025-11-10 18:57:39,014] Trial 127 pruned.

Best trial: 11. Best value: 0.536784:  63%|██████▎   | 126/200 [02:00<01:44,  1.41s/it]

[I 2025-11-10 18:57:41,986] Trial 125 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.0187362661762924, 'n_estimators': 1032, 'subsample': 0.6325204023084241, 'colsample_bytree': 0.5909018400483909, 'min_child_weight': 5, 'gamma': 2.7113953704179106, 'reg_alpha': 0.003996204935800784, 'reg_lambda': 9.56671348559492e-06, 'max_delta_step': 6}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  64%|██████▎   | 127/200 [02:01<01:29,  1.23s/it]

[I 2025-11-10 18:57:42,771] Trial 126 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.018215492044482678, 'n_estimators': 1150, 'subsample': 0.5038964143798627, 'colsample_bytree': 0.6444186172268671, 'min_child_weight': 4, 'gamma': 2.6713894456961107, 'reg_alpha': 3.062673738568306e-05, 'reg_lambda': 9.12652447271852e-06, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  64%|██████▍   | 128/200 [02:01<01:07,  1.07it/s]

[I 2025-11-10 18:57:43,032] Trial 124 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.04739896907793278, 'n_estimators': 1497, 'subsample': 0.676342704470959, 'colsample_bytree': 0.5944051110611246, 'min_child_weight': 5, 'gamma': 2.6440489643118292, 'reg_alpha': 3.0308317768113897e-06, 'reg_lambda': 5.501347322413501e-05, 'max_delta_step': 6}. Best is trial 11 with value: 0.5367836257309941.
[I 2025-11-10 18:57:43,070] Trial 128 finished with value: 0.48775828460038984 and parameters: {'max_depth': 10, 'learning_rate': 0.04749787706658994, 'n_estimators': 925, 'subsample': 0.6244259355265999, 'colsample_bytree': 0.5928350222004346, 'min_child_weight': 4, 'gamma': 1.3804618826794863, 'reg_alpha': 0.0037407854815560203, 'reg_lambda': 1.0108410958758479e-05, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  65%|██████▌   | 130/200 [02:05<01:36,  1.38s/it]

[I 2025-11-10 18:57:46,824] Trial 129 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.027813566680224427, 'n_estimators': 1151, 'subsample': 0.5604712411493243, 'colsample_bytree': 0.6029015395193489, 'min_child_weight': 6, 'gamma': 1.0845555339601531, 'reg_alpha': 2.704702338499727e-06, 'reg_lambda': 2.274169806231529e-07, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.
[I 2025-11-10 18:57:46,846] Trial 130 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.047662575097344353, 'n_estimators': 936, 'subsample': 0.5417838022429742, 'colsample_bytree': 0.5201955428941402, 'min_child_weight': 6, 'gamma': 1.4135169073252447, 'reg_alpha': 0.00026331805962571486, 'reg_lambda': 5.4040364274255734e-06, 'max_delta_step': 5}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  66%|██████▌   | 132/200 [02:05<00:59,  1.15it/s]

[I 2025-11-10 18:57:47,032] Trial 131 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.02795603924717178, 'n_estimators': 924, 'subsample': 0.5591685534255918, 'colsample_bytree': 0.5218204586238034, 'min_child_weight': 9, 'gamma': 2.553625808849237, 'reg_alpha': 3.331635581443034e-08, 'reg_lambda': 0.00010853783181574806, 'max_delta_step': 5}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  66%|██████▋   | 133/200 [02:06<01:08,  1.02s/it]

[I 2025-11-10 18:57:48,573] Trial 132 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.06570863601997587, 'n_estimators': 1286, 'subsample': 0.9114869740688426, 'colsample_bytree': 0.5168937125641748, 'min_child_weight': 9, 'gamma': 2.0560300398368474, 'reg_alpha': 2.948981399858785e-08, 'reg_lambda': 0.0001027176590747712, 'max_delta_step': 3}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  67%|██████▋   | 134/200 [02:09<01:37,  1.48s/it]

[I 2025-11-10 18:57:51,491] Trial 134 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.02208147348917814, 'n_estimators': 1005, 'subsample': 0.5211309759911823, 'colsample_bytree': 0.7301254944164359, 'min_child_weight': 5, 'gamma': 2.5704610292337184, 'reg_alpha': 6.998575154839291e-06, 'reg_lambda': 0.00011074175594936593, 'max_delta_step': 5}. Best is trial 11 with value: 0.5367836257309941.
[I 2025-11-10 18:57:51,500] Trial 135 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.02057772571254219, 'n_estimators': 1009, 'subsample': 0.5204924511445321, 'colsample_bytree': 0.7325324254088919, 'min_child_weight': 5, 'gamma': 3.1500574121489633, 'reg_alpha': 1.847029446150881e-05, 'reg_lambda': 1.9656674086670674e-05, 'max_delta_step': 3}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  68%|██████▊   | 137/200 [02:11<00:54,  1.15it/s]

[I 2025-11-10 18:57:52,482] Trial 133 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.015201025309967165, 'n_estimators': 1307, 'subsample': 0.5179132522668987, 'colsample_bytree': 0.5288275704857751, 'min_child_weight': 7, 'gamma': 2.1221916947054016, 'reg_alpha': 0.00026774465459145937, 'reg_lambda': 4.9033769014773025e-06, 'max_delta_step': 3}. Best is trial 11 with value: 0.5367836257309941.
[I 2025-11-10 18:57:52,647] Trial 137 pruned.

Best trial: 11. Best value: 0.536784:  69%|██████▉   | 138/200 [02:11<00:50,  1.23it/s]

[I 2025-11-10 18:57:53,272] Trial 136 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.015377108841223263, 'n_estimators': 1022, 'subsample': 0.5155535494931663, 'colsample_bytree': 0.7801995205137853, 'min_child_weight': 5, 'gamma': 1.7361583083966559, 'reg_alpha': 0.00010848630279111032, 'reg_lambda': 2.4955749747692016e-06, 'max_delta_step': 9}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  70%|██████▉   | 139/200 [02:12<00:54,  1.12it/s]

[I 2025-11-10 18:57:54,405] Trial 138 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.01243290978295535, 'n_estimators': 622, 'subsample': 0.9280093276750423, 'colsample_bytree': 0.780467910825437, 'min_child_weight': 7, 'gamma': 4.5867058738002475, 'reg_alpha': 9.796845897272514e-05, 'reg_lambda': 6.155880346661512e-07, 'max_delta_step': 0}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  70%|███████   | 140/200 [02:13<00:57,  1.04it/s]

[I 2025-11-10 18:57:55,561] Trial 140 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.0335805133182055, 'n_estimators': 627, 'subsample': 0.6129398320800398, 'colsample_bytree': 0.8838002740653648, 'min_child_weight': 6, 'gamma': 1.7176007876799795, 'reg_alpha': 6.532704296434621e-05, 'reg_lambda': 7.081072709663269e-07, 'max_delta_step': 9}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  70%|███████   | 141/200 [02:14<00:47,  1.23it/s]

[I 2025-11-10 18:57:55,970] Trial 141 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03371872507097261, 'n_estimators': 613, 'subsample': 0.6094747530929384, 'colsample_bytree': 0.5485942011691302, 'min_child_weight': 10, 'gamma': 4.566727862116278, 'reg_alpha': 4.123146330043667e-05, 'reg_lambda': 0.0002622152134794925, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  72%|███████▏  | 143/200 [02:15<00:41,  1.39it/s]

[I 2025-11-10 18:57:57,271] Trial 144 pruned.
[I 2025-11-10 18:57:57,429] Trial 139 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09804824610958048, 'n_estimators': 1098, 'subsample': 0.5954809854747772, 'colsample_bytree': 0.7779736184846318, 'min_child_weight': 5, 'gamma': 1.8611611543181428, 'reg_alpha': 1.5244746927224488e-08, 'reg_lambda': 5.409566397792989e-05, 'max_delta_step': 9}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  72%|███████▏  | 144/200 [02:16<00:33,  1.66it/s]

[I 2025-11-10 18:57:57,740] Trial 142 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.03452705544652677, 'n_estimators': 728, 'subsample': 0.6158673010995015, 'colsample_bytree': 0.8791933092897524, 'min_child_weight': 10, 'gamma': 2.84175984651802, 'reg_alpha': 5.222678747377083e-07, 'reg_lambda': 1.3437290626297027e-05, 'max_delta_step': 2}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  72%|███████▎  | 145/200 [02:17<00:40,  1.34it/s]

[I 2025-11-10 18:57:58,824] Trial 143 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.09626187455309539, 'n_estimators': 728, 'subsample': 0.790002962018627, 'colsample_bytree': 0.6204119993687901, 'min_child_weight': 10, 'gamma': 2.8209372664340937, 'reg_alpha': 3.8592869432358183, 'reg_lambda': 0.00035697866421677624, 'max_delta_step': 8}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  73%|███████▎  | 146/200 [02:17<00:33,  1.63it/s]

[I 2025-11-10 18:57:59,130] Trial 147 pruned.

Best trial: 11. Best value: 0.536784:  74%|███████▎  | 147/200 [02:19<00:47,  1.11it/s]

[I 2025-11-10 18:58:00,714] Trial 149 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.020229144673884238, 'n_estimators': 354, 'subsample': 0.5354383495149101, 'colsample_bytree': 0.7577314110851916, 'min_child_weight': 8, 'gamma': 3.493506722442756, 'reg_alpha': 0.0021092012671409003, 'reg_lambda': 1.4399598146489716, 'max_delta_step': 6}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  74%|███████▍  | 148/200 [02:20<00:54,  1.05s/it]

[I 2025-11-10 18:58:02,119] Trial 145 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.023407479326084404, 'n_estimators': 1107, 'subsample': 0.5002896865999774, 'colsample_bytree': 0.7536347754754416, 'min_child_weight': 5, 'gamma': 3.464601455384063, 'reg_alpha': 1.6743812006014348e-08, 'reg_lambda': 1.3638630113972321e-06, 'max_delta_step': 6}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  74%|███████▍  | 149/200 [02:20<00:41,  1.22it/s]

[I 2025-11-10 18:58:02,396] Trial 150 pruned.

Best trial: 11. Best value: 0.536784:  75%|███████▌  | 150/200 [02:21<00:41,  1.20it/s]

[I 2025-11-10 18:58:03,272] Trial 146 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.03023970734428007, 'n_estimators': 1410, 'subsample': 0.5363245083180329, 'colsample_bytree': 0.6497353486837933, 'min_child_weight': 8, 'gamma': 2.9789868534271555, 'reg_alpha': 3.591960939936644, 'reg_lambda': 1.5150612508449834e-08, 'max_delta_step': 6}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  76%|███████▌  | 151/200 [02:22<00:39,  1.23it/s]

[I 2025-11-10 18:58:04,037] Trial 148 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.05360330178881562, 'n_estimators': 1181, 'subsample': 0.5337882114427165, 'colsample_bytree': 0.7372646729966865, 'min_child_weight': 4, 'gamma': 1.218977180091571, 'reg_alpha': 0.0003991502376887032, 'reg_lambda': 1.6341899910170103e-06, 'max_delta_step': 6}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  76%|███████▌  | 152/200 [02:25<01:16,  1.60s/it]

[I 2025-11-10 18:58:07,467] Trial 151 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.02592475483492853, 'n_estimators': 1189, 'subsample': 0.8658657590791833, 'colsample_bytree': 0.6454468372929016, 'min_child_weight': 6, 'gamma': 1.5514522157101602, 'reg_alpha': 0.06325393129030911, 'reg_lambda': 1.9834426511390998e-05, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.
[I 2025-11-10 18:58:07,483] Trial 152 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.05340210477679508, 'n_estimators': 1183, 'subsample': 0.8703154101101529, 'colsample_bytree': 0.5783962977548899, 'min_child_weight': 6, 'gamma': 1.531210665331479, 'reg_alpha': 1.6732989342453783, 'reg_lambda': 2.8523323870140316e-06, 'max_delta_step': 10}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  77%|███████▋  | 154/200 [02:26<00:51,  1.12s/it]

[I 2025-11-10 18:58:08,586] Trial 153 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.026762617123374112, 'n_estimators': 1218, 'subsample': 0.9616698628591994, 'colsample_bytree': 0.6115799280980935, 'min_child_weight': 6, 'gamma': 3.6555103125116486, 'reg_alpha': 0.7510094031706187, 'reg_lambda': 2.5933810506448033e-07, 'max_delta_step': 4}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  78%|███████▊  | 155/200 [02:28<00:59,  1.32s/it]

[I 2025-11-10 18:58:10,502] Trial 154 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.19042834687930651, 'n_estimators': 1451, 'subsample': 0.551493173529637, 'colsample_bytree': 0.7041749629398535, 'min_child_weight': 6, 'gamma': 4.89094212844636, 'reg_alpha': 0.08417848652251894, 'reg_lambda': 4.6401795647432346e-07, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  78%|███████▊  | 156/200 [02:30<01:01,  1.39s/it]

[I 2025-11-10 18:58:12,091] Trial 156 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.119163970611211, 'n_estimators': 1056, 'subsample': 0.5707835408697295, 'colsample_bytree': 0.6706866591069464, 'min_child_weight': 6, 'gamma': 0.9045301349704516, 'reg_alpha': 0.0002191917043313061, 'reg_lambda': 2.1330129749740377e-07, 'max_delta_step': 4}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  78%|███████▊  | 157/200 [02:32<01:03,  1.47s/it]

[I 2025-11-10 18:58:13,785] Trial 155 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.19802461625497506, 'n_estimators': 1466, 'subsample': 0.5716763914619452, 'colsample_bytree': 0.6321184330267441, 'min_child_weight': 6, 'gamma': 4.8566181987731225, 'reg_alpha': 5.898781378527473e-05, 'reg_lambda': 1.603222857318778e-07, 'max_delta_step': 5}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  79%|███████▉  | 158/200 [02:33<00:58,  1.38s/it]

[I 2025-11-10 18:58:14,945] Trial 157 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.21318430834111002, 'n_estimators': 1475, 'subsample': 0.7542620669511195, 'colsample_bytree': 0.7050679477712675, 'min_child_weight': 5, 'gamma': 2.3769397288882033, 'reg_alpha': 0.00018590966290461024, 'reg_lambda': 3.9606322327677754e-08, 'max_delta_step': 5}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  80%|███████▉  | 159/200 [02:35<01:02,  1.53s/it]

[I 2025-11-10 18:58:16,857] Trial 158 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.21874553671425004, 'n_estimators': 1478, 'subsample': 0.5715347551758415, 'colsample_bytree': 0.6304463721555787, 'min_child_weight': 5, 'gamma': 2.429194402183885, 'reg_alpha': 0.0008329517061424877, 'reg_lambda': 8.167970776130561e-08, 'max_delta_step': 5}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  80%|████████  | 160/200 [02:36<01:01,  1.54s/it]

[I 2025-11-10 18:58:18,401] Trial 159 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.21198102689805037, 'n_estimators': 1480, 'subsample': 0.7297688807511824, 'colsample_bytree': 0.6847342791105792, 'min_child_weight': 7, 'gamma': 4.924466793093775, 'reg_alpha': 0.021079275318098337, 'reg_lambda': 7.959649779532128e-08, 'max_delta_step': 5}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  80%|████████  | 161/200 [02:37<00:47,  1.22s/it]

[I 2025-11-10 18:58:18,853] Trial 161 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.14304001561685947, 'n_estimators': 899, 'subsample': 0.819042010973694, 'colsample_bytree': 0.7258157936908526, 'min_child_weight': 7, 'gamma': 2.503347747469446, 'reg_alpha': 1.661410736520543e-07, 'reg_lambda': 6.997622792421416e-08, 'max_delta_step': 8}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  81%|████████  | 162/200 [02:38<00:49,  1.29s/it]

[I 2025-11-10 18:58:20,313] Trial 160 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.017678935987859253, 'n_estimators': 1485, 'subsample': 0.815434403888153, 'colsample_bytree': 0.7465597349654634, 'min_child_weight': 5, 'gamma': 2.50024102116098, 'reg_alpha': 0.023588614584309275, 'reg_lambda': 1.0688247146493413e-07, 'max_delta_step': 6}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  82%|████████▏ | 163/200 [02:39<00:38,  1.04s/it]

[I 2025-11-10 18:58:20,763] Trial 163 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1654866693015034, 'n_estimators': 511, 'subsample': 0.5882016494453474, 'colsample_bytree': 0.721503387428303, 'min_child_weight': 5, 'gamma': 3.7854259335837486, 'reg_alpha': 3.200856568337061e-05, 'reg_lambda': 7.456439853098425e-06, 'max_delta_step': 6}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  82%|████████▏ | 164/200 [02:39<00:28,  1.26it/s]

[I 2025-11-10 18:58:20,967] Trial 162 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.14409245090011732, 'n_estimators': 864, 'subsample': 0.5881542477826792, 'colsample_bytree': 0.9689160256172387, 'min_child_weight': 7, 'gamma': 4.934690540911042, 'reg_alpha': 3.2698401888448665e-05, 'reg_lambda': 0.015154586491035396, 'max_delta_step': 6}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  82%|████████▎ | 165/200 [02:43<01:00,  1.73s/it]

[I 2025-11-10 18:58:24,905] Trial 164 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.16601181470838344, 'n_estimators': 1433, 'subsample': 0.8997338257138204, 'colsample_bytree': 0.714207086627686, 'min_child_weight': 7, 'gamma': 3.8543197084237373, 'reg_alpha': 2.2747814107254704e-05, 'reg_lambda': 0.00019826498132922608, 'max_delta_step': 6}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  83%|████████▎ | 166/200 [02:44<00:53,  1.57s/it]

[I 2025-11-10 18:58:26,110] Trial 165 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.15345439285508214, 'n_estimators': 1397, 'subsample': 0.8324672825353512, 'colsample_bytree': 0.537170555045143, 'min_child_weight': 7, 'gamma': 4.201514854129994, 'reg_alpha': 4.464346893703583e-08, 'reg_lambda': 9.293211289491548e-07, 'max_delta_step': 1}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  84%|████████▎ | 167/200 [02:45<00:41,  1.26s/it]

[I 2025-11-10 18:58:26,625] Trial 166 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.1211980565327918, 'n_estimators': 1427, 'subsample': 0.8979664909013559, 'colsample_bytree': 0.5654522822279703, 'min_child_weight': 7, 'gamma': 4.388694511854167, 'reg_alpha': 0.3322698763197777, 'reg_lambda': 0.0001990294212862275, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  84%|████████▍ | 168/200 [02:45<00:34,  1.09s/it]

[I 2025-11-10 18:58:27,311] Trial 167 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.13032785690788493, 'n_estimators': 1436, 'subsample': 0.9040605740905576, 'colsample_bytree': 0.8200572243504272, 'min_child_weight': 7, 'gamma': 4.703411508973054, 'reg_alpha': 1.6405717609750506e-06, 'reg_lambda': 0.00020189828084664655, 'max_delta_step': 1}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  84%|████████▍ | 169/200 [02:46<00:29,  1.07it/s]

[I 2025-11-10 18:58:27,896] Trial 169 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.12321603942128877, 'n_estimators': 381, 'subsample': 0.5120021672787022, 'colsample_bytree': 0.5636971773366294, 'min_child_weight': 8, 'gamma': 4.366155371075614, 'reg_alpha': 0.0064955311783323096, 'reg_lambda': 0.0010872952566833352, 'max_delta_step': 2}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  85%|████████▌ | 170/200 [02:47<00:26,  1.15it/s]

[I 2025-11-10 18:58:28,604] Trial 168 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.1328689306000301, 'n_estimators': 828, 'subsample': 0.6627236781560447, 'colsample_bytree': 0.5635601909361061, 'min_child_weight': 7, 'gamma': 4.374599055188927, 'reg_alpha': 1.930703216904108e-06, 'reg_lambda': 0.28795117651378965, 'max_delta_step': 1}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  86%|████████▌ | 171/200 [02:47<00:24,  1.18it/s]

[I 2025-11-10 18:58:29,408] Trial 171 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.03934242651616541, 'n_estimators': 432, 'subsample': 0.8806099292712305, 'colsample_bytree': 0.7984571954582688, 'min_child_weight': 9, 'gamma': 3.978568697344098, 'reg_alpha': 0.006900852872299291, 'reg_lambda': 0.001933410213849871, 'max_delta_step': 4}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  86%|████████▋ | 173/200 [02:49<00:18,  1.43it/s]

[I 2025-11-10 18:58:30,541] Trial 170 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.13364480597439532, 'n_estimators': 823, 'subsample': 0.8851957953668619, 'colsample_bytree': 0.9027587628542466, 'min_child_weight': 8, 'gamma': 4.730853259166367, 'reg_alpha': 1.6906027103505402e-06, 'reg_lambda': 0.0017366254301445013, 'max_delta_step': 8}. Best is trial 11 with value: 0.5367836257309941.
[I 2025-11-10 18:58:30,694] Trial 174 pruned.

Best trial: 11. Best value: 0.536784:  87%|████████▋ | 174/200 [02:50<00:19,  1.30it/s]

[I 2025-11-10 18:58:31,624] Trial 172 finished with value: 0.5055555555555555 and parameters: {'max_depth': 5, 'learning_rate': 0.11039865694055834, 'n_estimators': 818, 'subsample': 0.8566119553625192, 'colsample_bytree': 0.5829920097903976, 'min_child_weight': 5, 'gamma': 3.973015623956279, 'reg_alpha': 1.4198684315477817e-05, 'reg_lambda': 0.26302259235607883, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  88%|████████▊ | 175/200 [02:52<00:29,  1.17s/it]

[I 2025-11-10 18:58:33,714] Trial 173 finished with value: 0.4966666666666667 and parameters: {'max_depth': 5, 'learning_rate': 0.10347722404646863, 'n_estimators': 1053, 'subsample': 0.8548367755614015, 'colsample_bytree': 0.9066328841169037, 'min_child_weight': 5, 'gamma': 4.543983738760056, 'reg_alpha': 3.1220226088730343e-07, 'reg_lambda': 3.911378969380419e-05, 'max_delta_step': 4}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  88%|████████▊ | 176/200 [02:53<00:29,  1.24s/it]

[I 2025-11-10 18:58:35,128] Trial 177 finished with value: 0.4966666666666667 and parameters: {'max_depth': 8, 'learning_rate': 0.021175894926234506, 'n_estimators': 802, 'subsample': 0.8581791336485797, 'colsample_bytree': 0.5833295743128055, 'min_child_weight': 5, 'gamma': 4.0364755700893955, 'reg_alpha': 1.5093832695856877e-05, 'reg_lambda': 0.10864876158513082, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.
[I 2025-11-10 18:58:35,144] Trial 175 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.0719895727107233, 'n_estimators': 1050, 'subsample': 0.858650172803242, 'colsample_bytree': 0.5833865283741885, 'min_child_weight': 10, 'gamma': 4.5333889460904695, 'reg_alpha': 0.2911052109572251, 'reg_lambda': 4.309762585436053, 'max_delta_step': 2}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  89%|████████▉ | 178/200 [02:53<00:16,  1.36it/s]

[I 2025-11-10 18:58:35,416] Trial 176 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.07737346494843009, 'n_estimators': 1071, 'subsample': 0.8619350929322156, 'colsample_bytree': 0.5773312618797655, 'min_child_weight': 10, 'gamma': 4.138477113704254, 'reg_alpha': 0.29404693112898905, 'reg_lambda': 2.099786050643635e-05, 'max_delta_step': 2}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  90%|████████▉ | 179/200 [02:55<00:20,  1.01it/s]

[I 2025-11-10 18:58:37,170] Trial 178 finished with value: 0.5288888888888889 and parameters: {'max_depth': 8, 'learning_rate': 0.11326809682148503, 'n_estimators': 776, 'subsample': 0.8605269647190745, 'colsample_bytree': 0.6571098868873346, 'min_child_weight': 5, 'gamma': 3.2935445616878276, 'reg_alpha': 6.974463549783231e-06, 'reg_lambda': 0.5305415753016246, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  90%|█████████ | 180/200 [02:56<00:18,  1.06it/s]

[I 2025-11-10 18:58:37,998] Trial 180 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.11569437694676957, 'n_estimators': 669, 'subsample': 0.7097787988535188, 'colsample_bytree': 0.5756371062719113, 'min_child_weight': 5, 'gamma': 3.165791443096271, 'reg_alpha': 9.246365961075198e-06, 'reg_lambda': 0.6688496060186744, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  90%|█████████ | 181/200 [02:57<00:20,  1.07s/it]

[I 2025-11-10 18:58:39,391] Trial 179 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.011208855306923985, 'n_estimators': 990, 'subsample': 0.8374900898221564, 'colsample_bytree': 0.5754360842482321, 'min_child_weight': 5, 'gamma': 3.2358724754633834, 'reg_alpha': 9.051185099821487e-06, 'reg_lambda': 1.3728420828564685, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  91%|█████████ | 182/200 [02:58<00:18,  1.02s/it]

[I 2025-11-10 18:58:40,294] Trial 181 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.011196826040893367, 'n_estimators': 1133, 'subsample': 0.5271146465885296, 'colsample_bytree': 0.6159624678177417, 'min_child_weight': 5, 'gamma': 3.2400667414447195, 'reg_alpha': 8.240722896129097e-05, 'reg_lambda': 0.024849073557885515, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  92%|█████████▏| 183/200 [02:58<00:13,  1.23it/s]

[I 2025-11-10 18:58:40,592] Trial 182 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.11112419091882397, 'n_estimators': 787, 'subsample': 0.5495778647796763, 'colsample_bytree': 0.6765064941955499, 'min_child_weight': 5, 'gamma': 3.274994833640016, 'reg_alpha': 3.3708120434002825e-06, 'reg_lambda': 0.48035583491630657, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  92%|█████████▏| 184/200 [02:59<00:13,  1.21it/s]

[I 2025-11-10 18:58:41,463] Trial 183 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.11336328284791962, 'n_estimators': 769, 'subsample': 0.8399628720182819, 'colsample_bytree': 0.6557811815723499, 'min_child_weight': 5, 'gamma': 3.7061904683312927, 'reg_alpha': 6.524618835967139e-06, 'reg_lambda': 2.1532151064938354, 'max_delta_step': 7}. Best is trial 11 with value: 0.5367836257309941.

Best trial: 11. Best value: 0.536784:  92%|█████████▎| 185/200 [03:00<00:12,  1.19it/s]

[I 2025-11-10 18:58:42,337] Trial 187 pruned.

Best trial: 11. Best value: 0.536784:  93%|█████████▎| 186/200 [03:01<00:10,  1.28it/s]

[I 2025-11-10 18:58:42,975] Trial 188 pruned.

Best trial: 184. Best value: 0.575673:  94%|█████████▎| 187/200 [03:01<00:08,  1.59it/s]

[I 2025-11-10 18:58:43,231] Trial 184 finished with value: 0.5756725146198831 and parameters: {'max_depth': 8, 'learning_rate': 0.10372136464580343, 'n_estimators': 846, 'subsample': 0.8707900565760043, 'colsample_bytree': 0.6625173036793552, 'min_child_weight': 5, 'gamma': 3.681561124705326, 'reg_alpha': 4.916223685939241e-06, 'reg_lambda': 0.29894341172942607, 'max_delta_step': 7}. Best is trial 184 with value: 0.5756725146198831.

Best trial: 184. Best value: 0.575673:  94%|█████████▍| 188/200 [03:02<00:07,  1.61it/s]

[I 2025-11-10 18:58:43,842] Trial 185 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.10689356774431599, 'n_estimators': 772, 'subsample': 0.5451690920929706, 'colsample_bytree': 0.5512175727965265, 'min_child_weight': 5, 'gamma': 3.7206369200835, 'reg_alpha': 5.370628501727541e-06, 'reg_lambda': 2.014622167866569, 'max_delta_step': 7}. Best is trial 184 with value: 0.5756725146198831.

Best trial: 184. Best value: 0.575673:  94%|█████████▍| 189/200 [03:02<00:05,  1.93it/s]

[I 2025-11-10 18:58:44,113] Trial 190 pruned.

Best trial: 184. Best value: 0.575673:  95%|█████████▌| 190/200 [03:02<00:04,  2.38it/s]

[I 2025-11-10 18:58:44,306] Trial 186 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.014007063760053914, 'n_estimators': 759, 'subsample': 0.8456751818357131, 'colsample_bytree': 0.8731868118540916, 'min_child_weight': 5, 'gamma': 3.4593995844113117, 'reg_alpha': 5.038879461940807e-06, 'reg_lambda': 0.24445852712508157, 'max_delta_step': 7}. Best is trial 184 with value: 0.5756725146198831.

Best trial: 184. Best value: 0.575673:  96%|█████████▌| 191/200 [03:03<00:04,  2.05it/s]

[I 2025-11-10 18:58:44,953] Trial 192 pruned.

Best trial: 184. Best value: 0.575673:  96%|█████████▌| 192/200 [03:04<00:05,  1.37it/s]

[I 2025-11-10 18:58:46,246] Trial 194 pruned.

Best trial: 184. Best value: 0.575673:  96%|█████████▋| 193/200 [03:04<00:04,  1.68it/s]

[I 2025-11-10 18:58:46,526] Trial 189 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.018931372632413217, 'n_estimators': 747, 'subsample': 0.7938923756696402, 'colsample_bytree': 0.5973724551235465, 'min_child_weight': 5, 'gamma': 3.07668446763211, 'reg_alpha': 9.750398199624864e-07, 'reg_lambda': 0.36018674147991586, 'max_delta_step': 6}. Best is trial 184 with value: 0.5756725146198831.

Best trial: 184. Best value: 0.575673:  97%|█████████▋| 194/200 [03:05<00:03,  1.55it/s]

[I 2025-11-10 18:58:47,292] Trial 191 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.019185478132120792, 'n_estimators': 699, 'subsample': 0.7692362440829891, 'colsample_bytree': 0.8569373758115808, 'min_child_weight': 5, 'gamma': 3.624762429546494, 'reg_alpha': 9.711713402522415e-07, 'reg_lambda': 0.3193466873130523, 'max_delta_step': 8}. Best is trial 184 with value: 0.5756725146198831.

Best trial: 184. Best value: 0.575673:  98%|█████████▊| 195/200 [03:06<00:03,  1.54it/s]

[I 2025-11-10 18:58:47,949] Trial 193 finished with value: 0.554561403508772 and parameters: {'max_depth': 7, 'learning_rate': 0.10266642375550039, 'n_estimators': 804, 'subsample': 0.8758920005161154, 'colsample_bytree': 0.656487422912236, 'min_child_weight': 5, 'gamma': 3.6132781711076967, 'reg_alpha': 1.3612850522661778e-05, 'reg_lambda': 0.09336366260385644, 'max_delta_step': 7}. Best is trial 184 with value: 0.5756725146198831.

Best trial: 184. Best value: 0.575673:  98%|█████████▊| 196/200 [03:07<00:03,  1.17it/s]

[I 2025-11-10 18:58:49,282] Trial 195 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.09859280386274939, 'n_estimators': 686, 'subsample': 0.8738676711524649, 'colsample_bytree': 0.6555890591443684, 'min_child_weight': 6, 'gamma': 0.8011162227772823, 'reg_alpha': 1.2858215176594185e-05, 'reg_lambda': 1.0427274324110014, 'max_delta_step': 7}. Best is trial 184 with value: 0.5756725146198831.

Best trial: 184. Best value: 0.575673:  98%|█████████▊| 197/200 [03:08<00:02,  1.19it/s]

[I 2025-11-10 18:58:50,081] Trial 199 pruned.
[I 2025-11-10 18:58:50,171] Trial 196 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.012360298187257429, 'n_estimators': 850, 'subsample': 0.8654936623979916, 'colsample_bytree': 0.6370340390629781, 'min_child_weight': 6, 'gamma': 2.762157683915364, 'reg_alpha': 2.4863438662671994e-06, 'reg_lambda': 0.9892473750029586, 'max_delta_step': 7}. Best is trial 184 with value: 0.5756725146198831.

Best trial: 184. Best value: 0.575673: 100%|██████████| 200/200 [03:09<00:00,  1.06it/s]

[I 2025-11-10 18:58:50,956] Trial 197 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0983878335983066, 'n_estimators': 890, 'subsample': 0.5987296009191702, 'colsample_bytree': 0.9599498698618197, 'min_child_weight': 6, 'gamma': 2.759542639813745, 'reg_alpha': 7.451325703787726, 'reg_lambda': 1.0481415139884356, 'max_delta_step': 7}. Best is trial 184 with value: 0.5756725146198831.
[I 2025-11-10 18:58:51,045] Trial 198 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1013434938949031, 'n_estimators': 886, 'subsample': 0.8679855784985608, 'colsample_bytree': 0.6422759968891887, 'min_child_weight': 6, 'gamma': 3.368365007853794, 'reg_alpha': 1.492714685622595e-05, 'reg_lambda': 0.12340065636216932, 'max_delta_step': 7}. Best is trial 184 with value: 0.5756725146198831.

[I 2025-11-10 18:58:51,913] A new study created in memory with name: 16_1_roc_auc
Best trial: 1. Best value: 0.5:   0%|          | 1/200 [00:01<04:01,  1.21s/it]

[I 2025-11-10 18:58:53,120] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.06755413781110625, 'n_estimators': 256, 'subsample': 0.7564809630275968, 'colsample_bytree': 0.8261627009327707, 'min_child_weight': 10, 'gamma': 0.024557395318121622, 'reg_alpha': 0.0016915073665087642, 'reg_lambda': 0.0019142390831399243, 'max_delta_step': 2}. Best is trial 1 with value: 0.5.

Best trial: 3. Best value: 0.606082:   1%|          | 2/200 [00:02<03:30,  1.06s/it]

[I 2025-11-10 18:58:54,076] Trial 3 finished with value: 0.6060818713450293 and parameters: {'max_depth': 3, 'learning_rate': 0.09380484165312196, 'n_estimators': 469, 'subsample': 0.8878128065688615, 'colsample_bytree': 0.9469012854067127, 'min_child_weight': 5, 'gamma': 1.540605027280122, 'reg_alpha': 0.004929367757340053, 'reg_lambda': 3.899597557418844, 'max_delta_step': 4}. Best is trial 3 with value: 0.6060818713450293.

Best trial: 3. Best value: 0.606082:   2%|▏         | 4/200 [00:04<03:05,  1.06it/s]

[I 2025-11-10 18:58:55,989] Trial 2 finished with value: 0.567046783625731 and parameters: {'max_depth': 9, 'learning_rate': 0.26214547609985506, 'n_estimators': 940, 'subsample': 0.9086642064895236, 'colsample_bytree': 0.8443447572447111, 'min_child_weight': 5, 'gamma': 0.057512762017747354, 'reg_alpha': 0.2282662859967244, 'reg_lambda': 0.10726736008386731, 'max_delta_step': 4}. Best is trial 3 with value: 0.6060818713450293.
[I 2025-11-10 18:58:56,163] Trial 4 finished with value: 0.5856920077972709 and parameters: {'max_depth': 9, 'learning_rate': 0.012955273748096787, 'n_estimators': 648, 'subsample': 0.7752794549315984, 'colsample_bytree': 0.6904320164856719, 'min_child_weight': 4, 'gamma': 3.696907253824438, 'reg_alpha': 0.7828444794435427, 'reg_lambda': 0.27551214261006973, 'max_delta_step': 3}. Best is trial 3 with value: 0.6060818713450293.

Best trial: 3. Best value: 0.606082:   2%|▎         | 5/200 [00:04<02:48,  1.16it/s]

[I 2025-11-10 18:58:56,883] Trial 0 finished with value: 0.5730311890838207 and parameters: {'max_depth': 5, 'learning_rate': 0.17209066215539406, 'n_estimators': 1264, 'subsample': 0.8936014885487096, 'colsample_bytree': 0.5103451010015609, 'min_child_weight': 5, 'gamma': 3.272508851711116, 'reg_alpha': 0.10785931362067235, 'reg_lambda': 0.016755592661497874, 'max_delta_step': 1}. Best is trial 3 with value: 0.6060818713450293.

Best trial: 3. Best value: 0.606082:   3%|▎         | 6/200 [00:05<02:30,  1.29it/s]

[I 2025-11-10 18:58:57,486] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.0754538620119458, 'n_estimators': 282, 'subsample': 0.8488533593398977, 'colsample_bytree': 0.8055029880854478, 'min_child_weight': 8, 'gamma': 2.002212081487402, 'reg_alpha': 0.00028492573949239603, 'reg_lambda': 4.82346899522429e-05, 'max_delta_step': 4}. Best is trial 3 with value: 0.6060818713450293.

Best trial: 3. Best value: 0.606082:   4%|▎         | 7/200 [00:06<02:42,  1.19it/s]

[I 2025-11-10 18:58:58,471] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.09408795497629796, 'n_estimators': 602, 'subsample': 0.5147863489860582, 'colsample_bytree': 0.6112917951674008, 'min_child_weight': 6, 'gamma': 0.1074043076192488, 'reg_alpha': 8.678849773126624e-06, 'reg_lambda': 0.0004218078721227354, 'max_delta_step': 8}. Best is trial 3 with value: 0.6060818713450293.

Best trial: 3. Best value: 0.606082:   4%|▍         | 8/200 [00:07<03:00,  1.06it/s]

[I 2025-11-10 18:58:59,620] Trial 5 finished with value: 0.5365107212475634 and parameters: {'max_depth': 5, 'learning_rate': 0.03529511772685096, 'n_estimators': 1252, 'subsample': 0.950322007885162, 'colsample_bytree': 0.6408360137930493, 'min_child_weight': 4, 'gamma': 0.7982612371695746, 'reg_alpha': 8.209868979514536e-08, 'reg_lambda': 0.0007927979732851567, 'max_delta_step': 4}. Best is trial 3 with value: 0.6060818713450293.

Best trial: 3. Best value: 0.606082:   4%|▍         | 9/200 [00:08<02:56,  1.08it/s]

[I 2025-11-10 18:59:00,515] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.07493522398769849, 'n_estimators': 697, 'subsample': 0.9013976422499447, 'colsample_bytree': 0.9543191447760947, 'min_child_weight': 9, 'gamma': 4.135571780480865, 'reg_alpha': 0.1853945578205767, 'reg_lambda': 3.54356076749062e-05, 'max_delta_step': 8}. Best is trial 3 with value: 0.6060818713450293.

Best trial: 3. Best value: 0.606082:   5%|▌         | 10/200 [00:09<02:43,  1.16it/s]

[I 2025-11-10 18:59:01,224] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.013818224706827354, 'n_estimators': 383, 'subsample': 0.5353180622237397, 'colsample_bytree': 0.6499578401325246, 'min_child_weight': 4, 'gamma': 3.083339842032923, 'reg_alpha': 1.480208629466059e-05, 'reg_lambda': 2.973961409019411e-06, 'max_delta_step': 3}. Best is trial 3 with value: 0.6060818713450293.

Best trial: 3. Best value: 0.606082:   6%|▌         | 11/200 [00:09<02:12,  1.43it/s]

[I 2025-11-10 18:59:01,560] Trial 12 pruned.

Best trial: 3. Best value: 0.606082:   6%|▌         | 12/200 [00:10<01:54,  1.64it/s]

[I 2025-11-10 18:59:01,966] Trial 10 pruned.

Best trial: 3. Best value: 0.606082:   6%|▋         | 13/200 [00:10<01:41,  1.85it/s]

[I 2025-11-10 18:59:02,347] Trial 14 pruned.

Best trial: 3. Best value: 0.606082:   7%|▋         | 14/200 [00:11<02:02,  1.51it/s]

[I 2025-11-10 18:59:03,285] Trial 8 finished with value: 0.5719688109161793 and parameters: {'max_depth': 5, 'learning_rate': 0.040287956210224934, 'n_estimators': 1373, 'subsample': 0.8049433217103977, 'colsample_bytree': 0.9063901861876366, 'min_child_weight': 4, 'gamma': 0.06588821710440007, 'reg_alpha': 1.7172642024470066, 'reg_lambda': 3.7050486657653137e-06, 'max_delta_step': 7}. Best is trial 3 with value: 0.6060818713450293.
[I 2025-11-10 18:59:03,325] Trial 16 pruned.

Best trial: 3. Best value: 0.606082:   8%|▊         | 16/200 [00:12<01:37,  1.89it/s]

[I 2025-11-10 18:59:04,040] Trial 17 pruned.

Best trial: 3. Best value: 0.606082:   8%|▊         | 17/200 [00:12<01:33,  1.95it/s]

[I 2025-11-10 18:59:04,507] Trial 19 pruned.

Best trial: 3. Best value: 0.606082:   9%|▉         | 18/200 [00:13<01:35,  1.91it/s]

[I 2025-11-10 18:59:05,056] Trial 20 pruned.

Best trial: 3. Best value: 0.606082:  10%|▉         | 19/200 [00:13<01:25,  2.11it/s]

[I 2025-11-10 18:59:05,403] Trial 21 pruned.

Best trial: 3. Best value: 0.606082:  10%|█         | 20/200 [00:14<01:28,  2.03it/s]

[I 2025-11-10 18:59:05,941] Trial 15 finished with value: 0.5439766081871344 and parameters: {'max_depth': 7, 'learning_rate': 0.025202381924828966, 'n_estimators': 520, 'subsample': 0.7807193915800366, 'colsample_bytree': 0.9941122051067401, 'min_child_weight': 1, 'gamma': 4.982432462405379, 'reg_alpha': 2.114039786532063, 'reg_lambda': 1.6944508261756066e-08, 'max_delta_step': 6}. Best is trial 3 with value: 0.6060818713450293.

Best trial: 3. Best value: 0.606082:  10%|█         | 21/200 [00:14<01:24,  2.12it/s]

[I 2025-11-10 18:59:06,361] Trial 22 pruned.

Best trial: 3. Best value: 0.606082:  11%|█         | 22/200 [00:14<01:12,  2.45it/s]

[I 2025-11-10 18:59:06,614] Trial 23 pruned.

Best trial: 3. Best value: 0.606082:  12%|█▏        | 23/200 [00:16<02:04,  1.42it/s]

[I 2025-11-10 18:59:08,034] Trial 18 finished with value: 0.5645808966861598 and parameters: {'max_depth': 8, 'learning_rate': 0.010528086866803649, 'n_estimators': 768, 'subsample': 0.7288758108787157, 'colsample_bytree': 0.7261926555326019, 'min_child_weight': 2, 'gamma': 3.7361605575089154, 'reg_alpha': 0.011871766542229177, 'reg_lambda': 0.35627021995542923, 'max_delta_step': 2}. Best is trial 3 with value: 0.6060818713450293.

Best trial: 3. Best value: 0.606082:  12%|█▏        | 24/200 [00:16<02:06,  1.39it/s]

[I 2025-11-10 18:59:08,793] Trial 13 finished with value: 0.5759259259259258 and parameters: {'max_depth': 7, 'learning_rate': 0.031330559553843555, 'n_estimators': 993, 'subsample': 0.6575414262279298, 'colsample_bytree': 0.9929081315074914, 'min_child_weight': 1, 'gamma': 1.8395807560871618, 'reg_alpha': 1.0349093507775656e-08, 'reg_lambda': 8.0369912398115, 'max_delta_step': 10}. Best is trial 3 with value: 0.6060818713450293.

Best trial: 3. Best value: 0.606082:  12%|█▎        | 25/200 [00:17<01:51,  1.57it/s]

[I 2025-11-10 18:59:09,226] Trial 24 finished with value: 0.5519200779727096 and parameters: {'max_depth': 6, 'learning_rate': 0.16840580881877557, 'n_estimators': 761, 'subsample': 0.8917063996769654, 'colsample_bytree': 0.5686265320759404, 'min_child_weight': 5, 'gamma': 3.4324022404324492, 'reg_alpha': 0.053180509814325545, 'reg_lambda': 0.03678889136154804, 'max_delta_step': 1}. Best is trial 3 with value: 0.6060818713450293.

Best trial: 3. Best value: 0.606082:  13%|█▎        | 26/200 [00:17<01:47,  1.62it/s]

[I 2025-11-10 18:59:09,802] Trial 27 pruned.

Best trial: 3. Best value: 0.606082:  14%|█▎        | 27/200 [00:18<01:34,  1.83it/s]

[I 2025-11-10 18:59:10,186] Trial 28 pruned.

Best trial: 3. Best value: 0.606082:  14%|█▍        | 28/200 [00:18<01:30,  1.91it/s]

[I 2025-11-10 18:59:10,656] Trial 25 finished with value: 0.5301656920077973 and parameters: {'max_depth': 6, 'learning_rate': 0.15543614645332096, 'n_estimators': 1089, 'subsample': 0.891032941952905, 'colsample_bytree': 0.503319924785504, 'min_child_weight': 5, 'gamma': 3.0924218204662672, 'reg_alpha': 0.04890146821298808, 'reg_lambda': 0.035785128072569714, 'max_delta_step': 1}. Best is trial 3 with value: 0.6060818713450293.

Best trial: 3. Best value: 0.606082:  14%|█▍        | 29/200 [00:19<01:44,  1.63it/s]

[I 2025-11-10 18:59:11,472] Trial 30 pruned.

Best trial: 26. Best value: 0.614269:  15%|█▌        | 30/200 [00:20<01:53,  1.50it/s]

[I 2025-11-10 18:59:12,266] Trial 26 finished with value: 0.6142690058479532 and parameters: {'max_depth': 6, 'learning_rate': 0.14373630886945804, 'n_estimators': 1154, 'subsample': 0.8896131225306443, 'colsample_bytree': 0.5266643195021652, 'min_child_weight': 5, 'gamma': 2.9019897444580316, 'reg_alpha': 0.18270642565745093, 'reg_lambda': 0.044008042907822224, 'max_delta_step': 1}. Best is trial 26 with value: 0.6142690058479532.
[I 2025-11-10 18:59:12,273] Trial 32 pruned.

Best trial: 26. Best value: 0.614269:  16%|█▌        | 32/200 [00:21<01:36,  1.75it/s]

[I 2025-11-10 18:59:13,194] Trial 34 pruned.
[I 2025-11-10 18:59:13,196] Trial 33 pruned.

Best trial: 26. Best value: 0.614269:  18%|█▊        | 35/200 [00:22<01:09,  2.38it/s]

[I 2025-11-10 18:59:13,968] Trial 36 pruned.
[I 2025-11-10 18:59:14,108] Trial 35 pruned.

Best trial: 26. Best value: 0.614269:  18%|█▊        | 36/200 [00:22<01:01,  2.67it/s]

[I 2025-11-10 18:59:14,340] Trial 37 pruned.
[I 2025-11-10 18:59:14,425] Trial 38 pruned.

Best trial: 26. Best value: 0.614269:  19%|█▉        | 38/200 [00:23<00:55,  2.94it/s]

[I 2025-11-10 18:59:14,919] Trial 39 pruned.

Best trial: 26. Best value: 0.614269:  20%|█▉        | 39/200 [00:23<00:49,  3.24it/s]

[I 2025-11-10 18:59:15,122] Trial 40 pruned.

Best trial: 26. Best value: 0.614269:  20%|██        | 40/200 [00:23<00:48,  3.28it/s]

[I 2025-11-10 18:59:15,410] Trial 29 finished with value: 0.5644639376218323 and parameters: {'max_depth': 9, 'learning_rate': 0.01585582181066331, 'n_estimators': 637, 'subsample': 0.6543755779183686, 'colsample_bytree': 0.9611854698424008, 'min_child_weight': 1, 'gamma': 2.8159473449513195, 'reg_alpha': 5.34303251129655e-07, 'reg_lambda': 2.005311938408896, 'max_delta_step': 3}. Best is trial 26 with value: 0.6142690058479532.

Best trial: 26. Best value: 0.614269:  21%|██        | 42/200 [00:24<00:51,  3.05it/s]

[I 2025-11-10 18:59:16,039] Trial 41 pruned.
[I 2025-11-10 18:59:16,205] Trial 42 pruned.

Best trial: 26. Best value: 0.614269:  22%|██▏       | 43/200 [00:24<00:46,  3.39it/s]

[I 2025-11-10 18:59:16,412] Trial 43 pruned.
[I 2025-11-10 18:59:16,428] Trial 45 pruned.

Best trial: 26. Best value: 0.614269:  22%|██▎       | 45/200 [00:25<00:47,  3.29it/s]

[I 2025-11-10 18:59:17,042] Trial 31 finished with value: 0.5464327485380116 and parameters: {'max_depth': 8, 'learning_rate': 0.015124465588060753, 'n_estimators': 627, 'subsample': 0.6740820970666677, 'colsample_bytree': 0.7671875407666187, 'min_child_weight': 1, 'gamma': 1.2740845177988471, 'reg_alpha': 0.0017773098322563402, 'reg_lambda': 1.4532503074877499, 'max_delta_step': 3}. Best is trial 26 with value: 0.6142690058479532.

Best trial: 26. Best value: 0.614269:  23%|██▎       | 46/200 [00:25<00:45,  3.39it/s]

[I 2025-11-10 18:59:17,310] Trial 44 pruned.

Best trial: 26. Best value: 0.614269:  24%|██▍       | 48/200 [00:25<00:40,  3.76it/s]

[I 2025-11-10 18:59:17,656] Trial 46 pruned.
[I 2025-11-10 18:59:17,805] Trial 47 pruned.

Best trial: 26. Best value: 0.614269:  24%|██▍       | 49/200 [00:26<00:48,  3.11it/s]

[I 2025-11-10 18:59:18,272] Trial 51 pruned.

Best trial: 26. Best value: 0.614269:  26%|██▌       | 51/200 [00:26<00:42,  3.52it/s]

[I 2025-11-10 18:59:18,709] Trial 50 pruned.
[I 2025-11-10 18:59:18,819] Trial 49 pruned.

Best trial: 26. Best value: 0.614269:  26%|██▌       | 52/200 [00:28<01:18,  1.89it/s]

[I 2025-11-10 18:59:19,944] Trial 53 pruned.

Best trial: 26. Best value: 0.614269:  26%|██▋       | 53/200 [00:28<01:13,  2.00it/s]

[I 2025-11-10 18:59:20,381] Trial 54 pruned.

Best trial: 26. Best value: 0.614269:  27%|██▋       | 54/200 [00:29<01:25,  1.70it/s]

[I 2025-11-10 18:59:21,171] Trial 55 pruned.

Best trial: 26. Best value: 0.614269:  28%|██▊       | 55/200 [00:29<01:19,  1.83it/s]

[I 2025-11-10 18:59:21,623] Trial 56 pruned.

Best trial: 26. Best value: 0.614269:  28%|██▊       | 56/200 [00:30<01:35,  1.51it/s]

[I 2025-11-10 18:59:22,558] Trial 58 pruned.

Best trial: 26. Best value: 0.614269:  29%|██▉       | 58/200 [00:31<01:02,  2.27it/s]

[I 2025-11-10 18:59:22,953] Trial 57 finished with value: 0.5392397660818713 and parameters: {'max_depth': 5, 'learning_rate': 0.020007747520486348, 'n_estimators': 396, 'subsample': 0.8926686814757323, 'colsample_bytree': 0.8052427506481935, 'min_child_weight': 5, 'gamma': 2.375763839088695, 'reg_alpha': 0.9030755111060889, 'reg_lambda': 0.00012699319774974734, 'max_delta_step': 6}. Best is trial 26 with value: 0.6142690058479532.
[I 2025-11-10 18:59:23,056] Trial 59 pruned.

Best trial: 48. Best value: 0.627076:  30%|██▉       | 59/200 [00:31<00:59,  2.36it/s]

[I 2025-11-10 18:59:23,445] Trial 48 finished with value: 0.6270760233918129 and parameters: {'max_depth': 6, 'learning_rate': 0.061002791985203406, 'n_estimators': 1410, 'subsample': 0.9745184642920233, 'colsample_bytree': 0.9177129397699769, 'min_child_weight': 5, 'gamma': 4.450072670814217, 'reg_alpha': 0.020781962709768537, 'reg_lambda': 0.9364867405339476, 'max_delta_step': 7}. Best is trial 48 with value: 0.6270760233918129.

Best trial: 48. Best value: 0.627076:  30%|███       | 61/200 [00:31<00:42,  3.26it/s]

[I 2025-11-10 18:59:23,769] Trial 52 finished with value: 0.5789278752436647 and parameters: {'max_depth': 7, 'learning_rate': 0.043882521380486206, 'n_estimators': 983, 'subsample': 0.9127683910442166, 'colsample_bytree': 0.5398025541202909, 'min_child_weight': 2, 'gamma': 3.2157099871172092, 'reg_alpha': 0.005064378345174439, 'reg_lambda': 8.105604563341326e-07, 'max_delta_step': 4}. Best is trial 48 with value: 0.6270760233918129.
[I 2025-11-10 18:59:23,871] Trial 60 pruned.

Best trial: 48. Best value: 0.627076:  31%|███       | 62/200 [00:32<00:37,  3.71it/s]

[I 2025-11-10 18:59:24,055] Trial 62 pruned.

Best trial: 48. Best value: 0.627076:  32%|███▏      | 63/200 [00:32<00:36,  3.76it/s]

[I 2025-11-10 18:59:24,311] Trial 61 pruned.

Best trial: 48. Best value: 0.627076:  32%|███▏      | 64/200 [00:33<00:51,  2.64it/s]

[I 2025-11-10 18:59:24,952] Trial 64 pruned.

Best trial: 48. Best value: 0.627076:  32%|███▎      | 65/200 [00:33<00:48,  2.77it/s]

[I 2025-11-10 18:59:25,275] Trial 65 pruned.

Best trial: 48. Best value: 0.627076:  33%|███▎      | 66/200 [00:33<00:41,  3.22it/s]

[I 2025-11-10 18:59:25,466] Trial 66 pruned.

Best trial: 48. Best value: 0.627076:  34%|███▎      | 67/200 [00:34<00:46,  2.83it/s]

[I 2025-11-10 18:59:25,918] Trial 67 pruned.

Best trial: 48. Best value: 0.627076:  34%|███▍      | 68/200 [00:34<00:56,  2.32it/s]

[I 2025-11-10 18:59:26,533] Trial 69 pruned.
[I 2025-11-10 18:59:26,555] Trial 68 pruned.

Best trial: 48. Best value: 0.627076:  35%|███▌      | 70/200 [00:34<00:37,  3.50it/s]

[I 2025-11-10 18:59:26,763] Trial 70 pruned.

Best trial: 48. Best value: 0.627076:  36%|███▌      | 71/200 [00:35<01:02,  2.05it/s]

[I 2025-11-10 18:59:27,860] Trial 73 pruned.

Best trial: 48. Best value: 0.627076:  36%|███▌      | 72/200 [00:37<01:28,  1.45it/s]

[I 2025-11-10 18:59:29,124] Trial 63 finished with value: 0.5757504873294346 and parameters: {'max_depth': 7, 'learning_rate': 0.09143120517145632, 'n_estimators': 825, 'subsample': 0.9696773137271237, 'colsample_bytree': 0.8698671946836967, 'min_child_weight': 2, 'gamma': 3.656629009698943, 'reg_alpha': 0.0008655653641886886, 'reg_lambda': 7.968682085714271e-08, 'max_delta_step': 5}. Best is trial 48 with value: 0.6270760233918129.

Best trial: 48. Best value: 0.627076:  36%|███▋      | 73/200 [00:37<01:11,  1.76it/s]

[I 2025-11-10 18:59:29,363] Trial 74 pruned.

Best trial: 48. Best value: 0.627076:  37%|███▋      | 74/200 [00:38<01:28,  1.43it/s]

[I 2025-11-10 18:59:30,397] Trial 76 pruned.
[I 2025-11-10 18:59:30,405] Trial 71 finished with value: 0.5639766081871345 and parameters: {'max_depth': 8, 'learning_rate': 0.03166800873255673, 'n_estimators': 967, 'subsample': 0.8786984528123829, 'colsample_bytree': 0.5763886877869945, 'min_child_weight': 5, 'gamma': 2.6778085112675925, 'reg_alpha': 0.004217669682869121, 'reg_lambda': 0.060370199311601654, 'max_delta_step': 10}. Best is trial 48 with value: 0.6270760233918129.

Best trial: 72. Best value: 0.640175:  38%|███▊      | 76/200 [00:38<00:53,  2.31it/s]

[I 2025-11-10 18:59:30,600] Trial 72 finished with value: 0.6401754385964912 and parameters: {'max_depth': 3, 'learning_rate': 0.0767071208190185, 'n_estimators': 967, 'subsample': 0.9966220799184182, 'colsample_bytree': 0.7439787165837428, 'min_child_weight': 5, 'gamma': 2.588896034121129, 'reg_alpha': 0.004317020272744229, 'reg_lambda': 0.34304756608000436, 'max_delta_step': 10}. Best is trial 72 with value: 0.6401754385964912.

Best trial: 72. Best value: 0.640175:  38%|███▊      | 77/200 [00:39<01:04,  1.92it/s]

[I 2025-11-10 18:59:31,400] Trial 77 pruned.

Best trial: 72. Best value: 0.640175:  40%|███▉      | 79/200 [00:40<00:55,  2.19it/s]

[I 2025-11-10 18:59:32,172] Trial 80 pruned.
[I 2025-11-10 18:59:32,278] Trial 75 finished with value: 0.6283040935672515 and parameters: {'max_depth': 7, 'learning_rate': 0.11037741328376231, 'n_estimators': 695, 'subsample': 0.8799725074611859, 'colsample_bytree': 0.9561061690516329, 'min_child_weight': 5, 'gamma': 1.4685891430445186, 'reg_alpha': 0.00016932903429868262, 'reg_lambda': 3.92297659326993e-08, 'max_delta_step': 4}. Best is trial 72 with value: 0.6401754385964912.

Best trial: 72. Best value: 0.640175:  40%|████      | 80/200 [00:40<00:55,  2.16it/s]

[I 2025-11-10 18:59:32,757] Trial 82 pruned.

Best trial: 72. Best value: 0.640175:  40%|████      | 81/200 [00:41<00:58,  2.04it/s]

[I 2025-11-10 18:59:33,316] Trial 81 pruned.

Best trial: 72. Best value: 0.640175:  41%|████      | 82/200 [00:41<00:51,  2.30it/s]

[I 2025-11-10 18:59:33,617] Trial 83 pruned.

Best trial: 72. Best value: 0.640175:  42%|████▏     | 83/200 [00:42<01:02,  1.88it/s]

[I 2025-11-10 18:59:34,385] Trial 85 pruned.

Best trial: 72. Best value: 0.640175:  42%|████▏     | 84/200 [00:43<01:05,  1.77it/s]

[I 2025-11-10 18:59:35,027] Trial 86 pruned.

Best trial: 72. Best value: 0.640175:  43%|████▎     | 86/200 [00:44<00:58,  1.96it/s]

[I 2025-11-10 18:59:35,906] Trial 79 finished with value: 0.5631189083820662 and parameters: {'max_depth': 3, 'learning_rate': 0.07124688431440307, 'n_estimators': 899, 'subsample': 0.9406694531942257, 'colsample_bytree': 0.6871745087012588, 'min_child_weight': 2, 'gamma': 1.9271164366290536, 'reg_alpha': 0.00014056626661624027, 'reg_lambda': 4.101033580972875, 'max_delta_step': 9}. Best is trial 72 with value: 0.6401754385964912.
[I 2025-11-10 18:59:36,069] Trial 87 pruned.

Best trial: 84. Best value: 0.645887:  44%|████▎     | 87/200 [00:44<00:57,  1.97it/s]

[I 2025-11-10 18:59:36,569] Trial 84 finished with value: 0.6458869395711501 and parameters: {'max_depth': 8, 'learning_rate': 0.1390893838345554, 'n_estimators': 727, 'subsample': 0.9772762453392054, 'colsample_bytree': 0.9653292721554563, 'min_child_weight': 5, 'gamma': 1.6345554334373438, 'reg_alpha': 0.01811225510437672, 'reg_lambda': 8.087120505424996e-08, 'max_delta_step': 4}. Best is trial 84 with value: 0.6458869395711501.
[I 2025-11-10 18:59:36,664] Trial 89 pruned.

Best trial: 84. Best value: 0.645887:  44%|████▍     | 89/200 [00:45<00:39,  2.78it/s]

[I 2025-11-10 18:59:36,940] Trial 88 pruned.

Best trial: 84. Best value: 0.645887:  45%|████▌     | 90/200 [00:45<00:38,  2.87it/s]

[I 2025-11-10 18:59:37,256] Trial 90 pruned.

Best trial: 84. Best value: 0.645887:  46%|████▌     | 91/200 [00:45<00:41,  2.64it/s]

[I 2025-11-10 18:59:37,719] Trial 78 finished with value: 0.5665692007797272 and parameters: {'max_depth': 7, 'learning_rate': 0.14088305066628817, 'n_estimators': 1037, 'subsample': 0.9944703262195563, 'colsample_bytree': 0.9592705337956103, 'min_child_weight': 2, 'gamma': 1.4155738060523508, 'reg_alpha': 0.04878628313085336, 'reg_lambda': 4.540924679543284, 'max_delta_step': 5}. Best is trial 84 with value: 0.6458869395711501.

Best trial: 84. Best value: 0.645887:  46%|████▌     | 92/200 [00:46<00:49,  2.16it/s]

[I 2025-11-10 18:59:38,408] Trial 94 pruned.

Best trial: 84. Best value: 0.645887:  46%|████▋     | 93/200 [00:47<00:58,  1.83it/s]

[I 2025-11-10 18:59:39,164] Trial 95 pruned.
[I 2025-11-10 18:59:39,170] Trial 92 finished with value: 0.607943469785575 and parameters: {'max_depth': 9, 'learning_rate': 0.1801504714414528, 'n_estimators': 478, 'subsample': 0.9500266169380603, 'colsample_bytree': 0.9847391788247821, 'min_child_weight': 5, 'gamma': 1.5721689167491528, 'reg_alpha': 0.05856050896455069, 'reg_lambda': 0.1944010055251386, 'max_delta_step': 4}. Best is trial 84 with value: 0.6458869395711501.

Best trial: 91. Best value: 0.669688:  48%|████▊     | 95/200 [00:48<00:53,  1.97it/s]

[I 2025-11-10 18:59:40,091] Trial 91 finished with value: 0.6696881091617934 and parameters: {'max_depth': 8, 'learning_rate': 0.14527810346811532, 'n_estimators': 734, 'subsample': 0.9857327659718986, 'colsample_bytree': 0.9613524776761677, 'min_child_weight': 5, 'gamma': 1.5563243718663684, 'reg_alpha': 0.054132463920454905, 'reg_lambda': 0.21817603036572777, 'max_delta_step': 3}. Best is trial 91 with value: 0.6696881091617934.

Best trial: 91. Best value: 0.669688:  48%|████▊     | 96/200 [00:48<00:52,  2.00it/s]

[I 2025-11-10 18:59:40,566] Trial 93 finished with value: 0.6162475633528264 and parameters: {'max_depth': 9, 'learning_rate': 0.17455504291743648, 'n_estimators': 706, 'subsample': 0.9045447007687547, 'colsample_bytree': 0.948246496123367, 'min_child_weight': 5, 'gamma': 1.613001263222588, 'reg_alpha': 0.07451574623227311, 'reg_lambda': 0.5330219544228644, 'max_delta_step': 10}. Best is trial 91 with value: 0.6696881091617934.

Best trial: 91. Best value: 0.669688:  48%|████▊     | 97/200 [00:49<00:51,  1.99it/s]

[I 2025-11-10 18:59:41,073] Trial 99 pruned.
[I 2025-11-10 18:59:41,093] Trial 96 finished with value: 0.6395808966861599 and parameters: {'max_depth': 9, 'learning_rate': 0.17125131572318658, 'n_estimators': 379, 'subsample': 0.904737657657812, 'colsample_bytree': 0.9882995253287407, 'min_child_weight': 5, 'gamma': 1.7109369883459817, 'reg_alpha': 0.07431905909143754, 'reg_lambda': 0.24671507111567173, 'max_delta_step': 4}. Best is trial 91 with value: 0.6696881091617934.

Best trial: 91. Best value: 0.669688:  50%|█████     | 100/200 [00:49<00:32,  3.11it/s]

[I 2025-11-10 18:59:41,455] Trial 97 finished with value: 0.628206627680312 and parameters: {'max_depth': 9, 'learning_rate': 0.157062801897038, 'n_estimators': 470, 'subsample': 0.9548979072071008, 'colsample_bytree': 0.9482272591091891, 'min_child_weight': 5, 'gamma': 1.734987451414762, 'reg_alpha': 0.42697482044224844, 'reg_lambda': 0.27690038409581724, 'max_delta_step': 4}. Best is trial 91 with value: 0.6696881091617934.
[I 2025-11-10 18:59:41,614] Trial 100 pruned.

Best trial: 91. Best value: 0.669688:  50%|█████     | 101/200 [00:50<00:42,  2.34it/s]

[I 2025-11-10 18:59:42,364] Trial 98 finished with value: 0.6419103313840155 and parameters: {'max_depth': 10, 'learning_rate': 0.16863753624999123, 'n_estimators': 445, 'subsample': 0.982493812030631, 'colsample_bytree': 0.9669438205593239, 'min_child_weight': 5, 'gamma': 1.7406867148327094, 'reg_alpha': 0.33113212167323447, 'reg_lambda': 0.24004425956108633, 'max_delta_step': 4}. Best is trial 91 with value: 0.6696881091617934.

Best trial: 91. Best value: 0.669688:  51%|█████     | 102/200 [00:51<00:50,  1.94it/s]

[I 2025-11-10 18:59:43,129] Trial 101 finished with value: 0.6558771929824562 and parameters: {'max_depth': 9, 'learning_rate': 0.20868135483195452, 'n_estimators': 403, 'subsample': 0.9779725748905401, 'colsample_bytree': 0.9688262779057062, 'min_child_weight': 5, 'gamma': 1.578217936321578, 'reg_alpha': 0.034324474785871736, 'reg_lambda': 0.5449909270317892, 'max_delta_step': 4}. Best is trial 91 with value: 0.6696881091617934.

Best trial: 91. Best value: 0.669688:  52%|█████▏    | 103/200 [00:51<00:45,  2.13it/s]

[I 2025-11-10 18:59:43,473] Trial 102 finished with value: 0.647953216374269 and parameters: {'max_depth': 9, 'learning_rate': 0.185796072959887, 'n_estimators': 397, 'subsample': 0.9814283894180102, 'colsample_bytree': 0.9674404327154722, 'min_child_weight': 5, 'gamma': 1.3276692595547348, 'reg_alpha': 0.15977612170025393, 'reg_lambda': 0.4888430655151831, 'max_delta_step': 4}. Best is trial 91 with value: 0.6696881091617934.

Best trial: 91. Best value: 0.669688:  52%|█████▏    | 104/200 [00:51<00:39,  2.41it/s]

[I 2025-11-10 18:59:43,746] Trial 103 finished with value: 0.6381578947368421 and parameters: {'max_depth': 9, 'learning_rate': 0.20815268309421694, 'n_estimators': 426, 'subsample': 0.9786818505813668, 'colsample_bytree': 0.9676970505825735, 'min_child_weight': 5, 'gamma': 1.5978727960423174, 'reg_alpha': 0.0666706770799931, 'reg_lambda': 0.18842596858337946, 'max_delta_step': 3}. Best is trial 91 with value: 0.6696881091617934.

Best trial: 91. Best value: 0.669688:  52%|█████▎    | 105/200 [00:52<00:41,  2.31it/s]

[I 2025-11-10 18:59:44,222] Trial 104 finished with value: 0.6341520467836258 and parameters: {'max_depth': 10, 'learning_rate': 0.20064550039565207, 'n_estimators': 364, 'subsample': 0.9757389722484165, 'colsample_bytree': 0.9705903148934067, 'min_child_weight': 5, 'gamma': 1.2988506087872347, 'reg_alpha': 0.12846607949106512, 'reg_lambda': 0.02603128990575502, 'max_delta_step': 3}. Best is trial 91 with value: 0.6696881091617934.

Best trial: 91. Best value: 0.669688:  53%|█████▎    | 106/200 [00:52<00:39,  2.40it/s]

[I 2025-11-10 18:59:44,604] Trial 108 pruned.

Best trial: 105. Best value: 0.692583:  54%|█████▎    | 107/200 [00:53<00:39,  2.37it/s]

[I 2025-11-10 18:59:45,033] Trial 105 finished with value: 0.6925828460038985 and parameters: {'max_depth': 10, 'learning_rate': 0.2676949131710634, 'n_estimators': 354, 'subsample': 0.9796763286430278, 'colsample_bytree': 0.9725157821907215, 'min_child_weight': 5, 'gamma': 1.7711216652637838, 'reg_alpha': 0.14000203323336796, 'reg_lambda': 0.09638999893219506, 'max_delta_step': 3}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  54%|█████▍    | 108/200 [00:53<00:38,  2.42it/s]

[I 2025-11-10 18:59:45,427] Trial 110 pruned.

Best trial: 105. Best value: 0.692583:  55%|█████▌    | 110/200 [00:54<00:28,  3.12it/s]

[I 2025-11-10 18:59:45,838] Trial 106 finished with value: 0.6516861598440545 and parameters: {'max_depth': 10, 'learning_rate': 0.20522839469550552, 'n_estimators': 447, 'subsample': 0.9780724172447436, 'colsample_bytree': 0.9660377418314383, 'min_child_weight': 5, 'gamma': 1.2711591052406304, 'reg_alpha': 0.14298558968677375, 'reg_lambda': 0.4912246200573488, 'max_delta_step': 3}. Best is trial 105 with value: 0.6925828460038985.
[I 2025-11-10 18:59:45,940] Trial 111 pruned.

Best trial: 105. Best value: 0.692583:  56%|█████▌    | 111/200 [00:54<00:24,  3.62it/s]

[I 2025-11-10 18:59:46,113] Trial 107 finished with value: 0.6207602339181287 and parameters: {'max_depth': 10, 'learning_rate': 0.20103507715167127, 'n_estimators': 441, 'subsample': 0.9831445439370695, 'colsample_bytree': 0.9695983747844188, 'min_child_weight': 5, 'gamma': 1.7358353795551837, 'reg_alpha': 0.12765783567273956, 'reg_lambda': 0.027927757301759594, 'max_delta_step': 3}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  56%|█████▋    | 113/200 [00:54<00:19,  4.44it/s]

[I 2025-11-10 18:59:46,333] Trial 113 pruned.
[I 2025-11-10 18:59:46,480] Trial 112 pruned.

Best trial: 105. Best value: 0.692583:  56%|█████▋    | 113/200 [00:54<00:19,  4.44it/s]

[I 2025-11-10 18:59:46,574] Trial 114 pruned.

Best trial: 105. Best value: 0.692583:  58%|█████▊    | 116/200 [00:55<00:15,  5.31it/s]

[I 2025-11-10 18:59:46,850] Trial 115 pruned.
[I 2025-11-10 18:59:46,981] Trial 116 pruned.
[I 2025-11-10 18:59:47,038] Trial 117 pruned.

Best trial: 105. Best value: 0.692583:  59%|█████▉    | 118/200 [00:55<00:13,  5.94it/s]

[I 2025-11-10 18:59:47,264] Trial 109 finished with value: 0.6447270955165691 and parameters: {'max_depth': 10, 'learning_rate': 0.20638721009251174, 'n_estimators': 444, 'subsample': 0.9746222413021342, 'colsample_bytree': 0.9866350530994255, 'min_child_weight': 5, 'gamma': 1.755862685513242, 'reg_alpha': 0.12023477018168854, 'reg_lambda': 0.07950618004081393, 'max_delta_step': 3}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  60%|█████▉    | 119/200 [00:55<00:18,  4.39it/s]

[I 2025-11-10 18:59:47,691] Trial 121 pruned.

Best trial: 105. Best value: 0.692583:  60%|██████    | 120/200 [00:56<00:24,  3.25it/s]

[I 2025-11-10 18:59:48,242] Trial 120 finished with value: 0.626793372319688 and parameters: {'max_depth': 9, 'learning_rate': 0.1909504894361832, 'n_estimators': 202, 'subsample': 0.9733833334963629, 'colsample_bytree': 0.9558737943549672, 'min_child_weight': 5, 'gamma': 0.7739726174930008, 'reg_alpha': 0.04395798175938948, 'reg_lambda': 0.162326055592645, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  60%|██████    | 121/200 [00:56<00:27,  2.91it/s]

[I 2025-11-10 18:59:48,689] Trial 118 finished with value: 0.6649122807017545 and parameters: {'max_depth': 9, 'learning_rate': 0.2485183657167419, 'n_estimators': 333, 'subsample': 0.9998526708955665, 'colsample_bytree': 0.9846439091719514, 'min_child_weight': 5, 'gamma': 0.714989768845489, 'reg_alpha': 0.03192261564020158, 'reg_lambda': 0.1637503065103491, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  61%|██████    | 122/200 [00:56<00:23,  3.32it/s]

[I 2025-11-10 18:59:48,874] Trial 122 finished with value: 0.61724171539961 and parameters: {'max_depth': 10, 'learning_rate': 0.23514736829304703, 'n_estimators': 214, 'subsample': 0.9523243599326866, 'colsample_bytree': 0.9642647105703323, 'min_child_weight': 5, 'gamma': 1.1349141799685685, 'reg_alpha': 0.041869811396136936, 'reg_lambda': 0.00858796567760777, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  62%|██████▏   | 123/200 [00:57<00:31,  2.46it/s]

[I 2025-11-10 18:59:49,558] Trial 119 finished with value: 0.6432358674463938 and parameters: {'max_depth': 9, 'learning_rate': 0.19078570463898425, 'n_estimators': 514, 'subsample': 0.9999685869372542, 'colsample_bytree': 0.9554936836471978, 'min_child_weight': 5, 'gamma': 0.8157687768161261, 'reg_alpha': 0.03571661777111429, 'reg_lambda': 0.1507316938366053, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  62%|██████▎   | 125/200 [00:58<00:31,  2.41it/s]

[I 2025-11-10 18:59:50,372] Trial 124 finished with value: 0.6486549707602339 and parameters: {'max_depth': 9, 'learning_rate': 0.2345306780497837, 'n_estimators': 328, 'subsample': 0.9472796383147459, 'colsample_bytree': 0.9868815494780816, 'min_child_weight': 5, 'gamma': 0.6955737145580568, 'reg_alpha': 0.03799653162903409, 'reg_lambda': 0.008140379303719667, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.
[I 2025-11-10 18:59:50,520] Trial 125 finished with value: 0.6432748538011696 and parameters: {'max_depth': 9, 'learning_rate': 0.1634957182982157, 'n_estimators': 318, 'subsample': 0.9892929130786065, 'colsample_bytree': 0.9842663084871303, 'min_child_weight': 5, 'gamma': 1.533904905245021, 'reg_alpha': 0.27479599994064197, 'reg_lambda': 0.6698181158112151, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  63%|██████▎   | 126/200 [00:59<00:29,  2.49it/s]

[I 2025-11-10 18:59:50,885] Trial 128 pruned.
[I 2025-11-10 18:59:50,957] Trial 123 finished with value: 0.6215399610136452 and parameters: {'max_depth': 10, 'learning_rate': 0.19294053652282067, 'n_estimators': 521, 'subsample': 0.9577345867357424, 'colsample_bytree': 0.984031164072116, 'min_child_weight': 5, 'gamma': 1.1616066000856813, 'reg_alpha': 0.03316010609688959, 'reg_lambda': 0.7843412283115556, 'max_delta_step': 3}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  64%|██████▍   | 129/200 [00:59<00:20,  3.41it/s]

[I 2025-11-10 18:59:51,400] Trial 126 finished with value: 0.6488304093567251 and parameters: {'max_depth': 9, 'learning_rate': 0.16431850354000677, 'n_estimators': 334, 'subsample': 0.9898485850262814, 'colsample_bytree': 0.9874711160510754, 'min_child_weight': 5, 'gamma': 0.7184706805704992, 'reg_alpha': 0.03314154262555278, 'reg_lambda': 0.787694646898568, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.
[I 2025-11-10 18:59:51,567] Trial 129 pruned.

Best trial: 105. Best value: 0.692583:  64%|██████▍   | 129/200 [00:59<00:20,  3.41it/s]

[I 2025-11-10 18:59:51,590] Trial 130 pruned.

Best trial: 105. Best value: 0.692583:  66%|██████▌   | 132/200 [01:00<00:14,  4.62it/s]

[I 2025-11-10 18:59:51,919] Trial 131 pruned.
[I 2025-11-10 18:59:52,040] Trial 132 pruned.

Best trial: 105. Best value: 0.692583:  66%|██████▋   | 133/200 [01:00<00:15,  4.32it/s]

[I 2025-11-10 18:59:52,310] Trial 135 pruned.

Best trial: 105. Best value: 0.692583:  67%|██████▋   | 134/200 [01:01<00:24,  2.69it/s]

[I 2025-11-10 18:59:53,089] Trial 133 finished with value: 0.6449805068226121 and parameters: {'max_depth': 9, 'learning_rate': 0.29766955636760145, 'n_estimators': 253, 'subsample': 0.9463537148701802, 'colsample_bytree': 0.9556485002108471, 'min_child_weight': 5, 'gamma': 0.45320585823926474, 'reg_alpha': 0.2669906655064822, 'reg_lambda': 0.0016780002308917608, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  68%|██████▊   | 135/200 [01:01<00:21,  2.97it/s]

[I 2025-11-10 18:59:53,330] Trial 127 finished with value: 0.6488304093567251 and parameters: {'max_depth': 9, 'learning_rate': 0.16707665506067654, 'n_estimators': 513, 'subsample': 0.9890482878140048, 'colsample_bytree': 0.9876624986267498, 'min_child_weight': 5, 'gamma': 0.666457066387225, 'reg_alpha': 0.027069207493840793, 'reg_lambda': 0.9536609225566104, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  68%|██████▊   | 137/200 [01:01<00:16,  3.85it/s]

[I 2025-11-10 18:59:53,522] Trial 134 finished with value: 0.6365594541910331 and parameters: {'max_depth': 9, 'learning_rate': 0.22664958280091602, 'n_estimators': 300, 'subsample': 0.9644899902761298, 'colsample_bytree': 0.7399935526959902, 'min_child_weight': 5, 'gamma': 0.36251815374051377, 'reg_alpha': 0.01592423196485205, 'reg_lambda': 0.3226423628247302, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.
[I 2025-11-10 18:59:53,690] Trial 138 pruned.

Best trial: 105. Best value: 0.692583:  70%|██████▉   | 139/200 [01:02<00:12,  4.79it/s]

[I 2025-11-10 18:59:53,916] Trial 139 pruned.
[I 2025-11-10 18:59:54,022] Trial 136 finished with value: 0.6424463937621833 and parameters: {'max_depth': 9, 'learning_rate': 0.2282992216219031, 'n_estimators': 293, 'subsample': 0.9785025456950103, 'colsample_bytree': 0.9933914003676074, 'min_child_weight': 5, 'gamma': 0.1741592485247423, 'reg_alpha': 0.02719691051758846, 'reg_lambda': 0.10292084998235392, 'max_delta_step': 5}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  70%|███████   | 140/200 [01:02<00:21,  2.73it/s]

[I 2025-11-10 18:59:54,772] Trial 137 finished with value: 0.6311695906432748 and parameters: {'max_depth': 9, 'learning_rate': 0.24395867457935239, 'n_estimators': 283, 'subsample': 0.9357906655208643, 'colsample_bytree': 0.9905276544501398, 'min_child_weight': 5, 'gamma': 0.8428922699739446, 'reg_alpha': 0.44887746910797605, 'reg_lambda': 0.005907472597636171, 'max_delta_step': 5}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  70%|███████   | 141/200 [01:03<00:28,  2.10it/s]

[I 2025-11-10 18:59:55,503] Trial 140 finished with value: 0.6089668615984405 and parameters: {'max_depth': 8, 'learning_rate': 0.25078049822044574, 'n_estimators': 343, 'subsample': 0.9767340537866147, 'colsample_bytree': 0.9890220989996075, 'min_child_weight': 5, 'gamma': 0.2533168303994555, 'reg_alpha': 0.5999736295127308, 'reg_lambda': 0.004422706797263396, 'max_delta_step': 5}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  71%|███████   | 142/200 [01:03<00:22,  2.56it/s]

[I 2025-11-10 18:59:55,690] Trial 141 finished with value: 0.6059356725146199 and parameters: {'max_depth': 8, 'learning_rate': 0.23832155158741256, 'n_estimators': 341, 'subsample': 0.9361334390637273, 'colsample_bytree': 0.9573959048576213, 'min_child_weight': 5, 'gamma': 0.46789130882557783, 'reg_alpha': 0.17594801731202825, 'reg_lambda': 0.0028429904320074434, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.

[I 2025-11-10 18:59:56,075] Trial 142 finished with value: 0.616588693957115 and parameters: {'max_depth': 8, 'learning_rate': 0.25245994625536894, 'n_estimators': 413, 'subsample': 0.9335695627750281, 'colsample_bytree': 0.9565273208824814, 'min_child_weight': 5, 'gamma': 0.6256736623021135, 'reg_alpha': 0.628480187752921, 'reg_lambda': 0.0091596398509573, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  72%|███████▏  | 144/200 [01:04<00:18,  3.03it/s]

[I 2025-11-10 18:59:56,254] Trial 145 pruned.

Best trial: 105. Best value: 0.692583:  74%|███████▎  | 147/200 [01:04<00:11,  4.60it/s]

[I 2025-11-10 18:59:56,608] Trial 147 pruned.
[I 2025-11-10 18:59:56,640] Trial 143 finished with value: 0.6628070175438596 and parameters: {'max_depth': 8, 'learning_rate': 0.25199641930224737, 'n_estimators': 344, 'subsample': 0.946784850302018, 'colsample_bytree': 0.9506641230482376, 'min_child_weight': 5, 'gamma': 0.23483196798381223, 'reg_alpha': 0.22066786975126154, 'reg_lambda': 0.0030653214527096733, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.
[I 2025-11-10 18:59:56,772] Trial 146 pruned.

Best trial: 105. Best value: 0.692583:  74%|███████▍  | 149/200 [01:05<00:11,  4.31it/s]

[I 2025-11-10 18:59:57,189] Trial 148 pruned.
[I 2025-11-10 18:59:57,323] Trial 144 finished with value: 0.6235380116959064 and parameters: {'max_depth': 9, 'learning_rate': 0.21308618957474176, 'n_estimators': 289, 'subsample': 0.9893487032531751, 'colsample_bytree': 0.9587630731601667, 'min_child_weight': 5, 'gamma': 0.48255443373564966, 'reg_alpha': 0.19891129808694058, 'reg_lambda': 0.037146352982504405, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.
[I 2025-11-10 18:59:57,339] Trial 150 pruned.

Best trial: 105. Best value: 0.692583:  76%|███████▌  | 152/200 [01:05<00:09,  5.12it/s]

[I 2025-11-10 18:59:57,724] Trial 151 pruned.
[I 2025-11-10 18:59:57,839] Trial 152 pruned.
[I 2025-11-10 18:59:57,846] Trial 153 pruned.

Best trial: 105. Best value: 0.692583:  77%|███████▋  | 154/200 [01:06<00:10,  4.26it/s]

[I 2025-11-10 18:59:58,432] Trial 154 pruned.

Best trial: 105. Best value: 0.692583:  78%|███████▊  | 156/200 [01:07<00:10,  4.09it/s]

[I 2025-11-10 18:59:58,810] Trial 157 pruned.
[I 2025-11-10 18:59:58,981] Trial 149 finished with value: 0.5880409356725147 and parameters: {'max_depth': 8, 'learning_rate': 0.18698817320751418, 'n_estimators': 389, 'subsample': 0.9482224256981183, 'colsample_bytree': 0.9493221026817991, 'min_child_weight': 5, 'gamma': 0.5941672221795865, 'reg_alpha': 0.21537077273511154, 'reg_lambda': 0.0013765097071616736, 'max_delta_step': 3}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  78%|███████▊  | 157/200 [01:07<00:12,  3.54it/s]

[I 2025-11-10 18:59:59,375] Trial 159 pruned.

Best trial: 105. Best value: 0.692583:  79%|███████▉  | 158/200 [01:07<00:11,  3.51it/s]

[I 2025-11-10 18:59:59,667] Trial 155 finished with value: 0.6480019493177388 and parameters: {'max_depth': 9, 'learning_rate': 0.23060175496046284, 'n_estimators': 320, 'subsample': 0.9823749336802735, 'colsample_bytree': 0.977013434869597, 'min_child_weight': 5, 'gamma': 0.10698063534901459, 'reg_alpha': 0.05089690991779864, 'reg_lambda': 0.12751612058946063, 'max_delta_step': 5}. Best is trial 105 with value: 0.6925828460038985.
[I 2025-11-10 18:59:59,715] Trial 160 pruned.

Best trial: 105. Best value: 0.692583:  80%|████████  | 160/200 [01:08<00:15,  2.54it/s]

[I 2025-11-10 19:00:00,746] Trial 158 finished with value: 0.6797076023391813 and parameters: {'max_depth': 9, 'learning_rate': 0.1553609029526776, 'n_estimators': 349, 'subsample': 0.9814170181137313, 'colsample_bytree': 0.9864748694034144, 'min_child_weight': 5, 'gamma': 0.31628307584826926, 'reg_alpha': 0.054524726345285365, 'reg_lambda': 0.5782511466834418, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  80%|████████  | 161/200 [01:09<00:14,  2.75it/s]

[I 2025-11-10 19:00:01,006] Trial 156 finished with value: 0.6680019493177387 and parameters: {'max_depth': 9, 'learning_rate': 0.22906041780752479, 'n_estimators': 586, 'subsample': 0.9794447412976004, 'colsample_bytree': 0.9777334170244074, 'min_child_weight': 5, 'gamma': 0.049312896308098306, 'reg_alpha': 0.052781278451976804, 'reg_lambda': 0.002146111808490155, 'max_delta_step': 5}. Best is trial 105 with value: 0.6925828460038985.
[I 2025-11-10 19:00:01,091] Trial 161 finished with value: 0.6423391812865497 and parameters: {'max_depth': 10, 'learning_rate': 0.2577542634552199, 'n_estimators': 247, 'subsample': 0.9677418882256844, 'colsample_bytree': 0.9737640583246195, 'min_child_weight': 5, 'gamma': 0.27844544108299474, 'reg_alpha': 0.06534181843468974, 'reg_lambda': 0.00224317142598488, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  82%|████████▏ | 163/200 [01:09<00:11,  3.34it/s]

[I 2025-11-10 19:00:01,414] Trial 162 finished with value: 0.5877972709551657 and parameters: {'max_depth': 10, 'learning_rate': 0.2551741832068061, 'n_estimators': 312, 'subsample': 0.9677592744589678, 'colsample_bytree': 0.9331391548662905, 'min_child_weight': 5, 'gamma': 0.023881388782281715, 'reg_alpha': 1.0028438482197566, 'reg_lambda': 0.002054566749081567, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  82%|████████▏ | 164/200 [01:09<00:11,  3.23it/s]

[I 2025-11-10 19:00:01,759] Trial 165 pruned.

Best trial: 105. Best value: 0.692583:  82%|████████▎ | 165/200 [01:10<00:11,  3.05it/s]

[I 2025-11-10 19:00:02,143] Trial 167 pruned.

Best trial: 105. Best value: 0.692583:  83%|████████▎ | 166/200 [01:10<00:11,  2.91it/s]

[I 2025-11-10 19:00:02,535] Trial 163 finished with value: 0.6359649122807018 and parameters: {'max_depth': 10, 'learning_rate': 0.29695481128230833, 'n_estimators': 322, 'subsample': 0.9678943817648356, 'colsample_bytree': 0.9661628292406593, 'min_child_weight': 5, 'gamma': 0.008354854636893172, 'reg_alpha': 0.14577600432011784, 'reg_lambda': 1.7911922825453048, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.
[I 2025-11-10 19:00:02,547] Trial 168 pruned.

Best trial: 105. Best value: 0.692583:  84%|████████▍ | 168/200 [01:11<00:09,  3.27it/s]

[I 2025-11-10 19:00:03,037] Trial 170 pruned.

Best trial: 105. Best value: 0.692583:  84%|████████▍ | 169/200 [01:11<00:11,  2.71it/s]

[I 2025-11-10 19:00:03,621] Trial 166 finished with value: 0.6526900584795322 and parameters: {'max_depth': 9, 'learning_rate': 0.2987449669771408, 'n_estimators': 418, 'subsample': 0.9836986353206091, 'colsample_bytree': 0.9630190854419673, 'min_child_weight': 5, 'gamma': 0.154310079649777, 'reg_alpha': 0.11924508127358788, 'reg_lambda': 0.0038658438355958953, 'max_delta_step': 5}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  85%|████████▌ | 170/200 [01:12<00:11,  2.54it/s]

[I 2025-11-10 19:00:04,086] Trial 164 finished with value: 0.640224171539961 and parameters: {'max_depth': 9, 'learning_rate': 0.24974225969378636, 'n_estimators': 604, 'subsample': 0.9662693824837246, 'colsample_bytree': 0.96700974332145, 'min_child_weight': 5, 'gamma': 0.05515694062621203, 'reg_alpha': 0.14960220439376742, 'reg_lambda': 0.0022022024184222442, 'max_delta_step': 6}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  86%|████████▌ | 171/200 [01:12<00:14,  2.06it/s]

[I 2025-11-10 19:00:04,832] Trial 173 pruned.

Best trial: 105. Best value: 0.692583:  86%|████████▌ | 172/200 [01:13<00:13,  2.07it/s]

[I 2025-11-10 19:00:05,309] Trial 174 pruned.

Best trial: 105. Best value: 0.692583:  86%|████████▋ | 173/200 [01:13<00:12,  2.16it/s]

[I 2025-11-10 19:00:05,718] Trial 175 pruned.
[I 2025-11-10 19:00:05,728] Trial 172 finished with value: 0.6569980506822611 and parameters: {'max_depth': 9, 'learning_rate': 0.2740600740087862, 'n_estimators': 424, 'subsample': 0.9785750258539534, 'colsample_bytree': 0.9624247248597911, 'min_child_weight': 5, 'gamma': 0.171103435647476, 'reg_alpha': 0.07767984420785193, 'reg_lambda': 0.0036363220670068194, 'max_delta_step': 6}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  88%|████████▊ | 175/200 [01:14<00:07,  3.21it/s]

[I 2025-11-10 19:00:05,964] Trial 171 finished with value: 0.6450877192982457 and parameters: {'max_depth': 9, 'learning_rate': 0.2054391879170869, 'n_estimators': 580, 'subsample': 0.9891451622626669, 'colsample_bytree': 0.9882572258678903, 'min_child_weight': 5, 'gamma': 1.477722560922032, 'reg_alpha': 0.08086456741958029, 'reg_lambda': 0.43552075635180604, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  88%|████████▊ | 176/200 [01:14<00:07,  3.15it/s]

[I 2025-11-10 19:00:06,299] Trial 177 pruned.
[I 2025-11-10 19:00:06,313] Trial 176 pruned.

Best trial: 105. Best value: 0.692583:  89%|████████▉ | 178/200 [01:14<00:05,  3.87it/s]

[I 2025-11-10 19:00:06,646] Trial 178 pruned.
[I 2025-11-10 19:00:06,662] Trial 169 finished with value: 0.6468615984405458 and parameters: {'max_depth': 9, 'learning_rate': 0.2321626352945956, 'n_estimators': 789, 'subsample': 0.9820988460310218, 'colsample_bytree': 0.9833801170004437, 'min_child_weight': 5, 'gamma': 0.2954444860803135, 'reg_alpha': 2.658171594887663, 'reg_lambda': 0.005780403382181764, 'max_delta_step': 5}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  90%|█████████ | 181/200 [01:15<00:04,  4.67it/s]

[I 2025-11-10 19:00:07,034] Trial 180 pruned.
[I 2025-11-10 19:00:07,167] Trial 179 pruned.

Best trial: 105. Best value: 0.692583:  91%|█████████ | 182/200 [01:15<00:03,  4.79it/s]

[I 2025-11-10 19:00:07,357] Trial 181 pruned.
[I 2025-11-10 19:00:07,361] Trial 182 pruned.

Best trial: 105. Best value: 0.692583:  92%|█████████▏| 184/200 [01:15<00:03,  4.30it/s]

[I 2025-11-10 19:00:07,896] Trial 183 pruned.

Best trial: 105. Best value: 0.692583:  92%|█████████▎| 185/200 [01:16<00:03,  3.79it/s]

[I 2025-11-10 19:00:08,265] Trial 185 pruned.
[I 2025-11-10 19:00:08,275] Trial 186 pruned.

Best trial: 105. Best value: 0.692583:  94%|█████████▎| 187/200 [01:16<00:03,  3.93it/s]

[I 2025-11-10 19:00:08,749] Trial 189 pruned.

Best trial: 105. Best value: 0.692583:  94%|█████████▍| 188/200 [01:18<00:07,  1.55it/s]

[I 2025-11-10 19:00:10,818] Trial 184 finished with value: 0.6843274853801169 and parameters: {'max_depth': 9, 'learning_rate': 0.2573326592034906, 'n_estimators': 751, 'subsample': 0.99398019013835, 'colsample_bytree': 0.9751835984561632, 'min_child_weight': 5, 'gamma': 0.37713808049013775, 'reg_alpha': 0.09030144271887186, 'reg_lambda': 0.0009384496972367443, 'max_delta_step': 5}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  94%|█████████▍| 189/200 [01:19<00:07,  1.56it/s]

[I 2025-11-10 19:00:11,439] Trial 187 finished with value: 0.6375146198830409 and parameters: {'max_depth': 9, 'learning_rate': 0.25395467582680714, 'n_estimators': 767, 'subsample': 0.9902640666474885, 'colsample_bytree': 0.9975275511995811, 'min_child_weight': 5, 'gamma': 0.3837667354500064, 'reg_alpha': 0.08310512191415868, 'reg_lambda': 1.023967301848034, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  95%|█████████▌| 190/200 [01:19<00:05,  1.80it/s]

[I 2025-11-10 19:00:11,744] Trial 188 finished with value: 0.6098927875243665 and parameters: {'max_depth': 9, 'learning_rate': 0.2101332401203826, 'n_estimators': 753, 'subsample': 0.9721033218611059, 'colsample_bytree': 0.9425034202736683, 'min_child_weight': 5, 'gamma': 0.7111650996356219, 'reg_alpha': 0.03209912714947426, 'reg_lambda': 0.0017626466597129996, 'max_delta_step': 5}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  96%|█████████▌| 192/200 [01:20<00:03,  2.46it/s]

[I 2025-11-10 19:00:12,123] Trial 190 finished with value: 0.6449025341130603 and parameters: {'max_depth': 9, 'learning_rate': 0.20788622758665393, 'n_estimators': 741, 'subsample': 0.9843460177624144, 'colsample_bytree': 0.9831408588089592, 'min_child_weight': 5, 'gamma': 0.724603809885043, 'reg_alpha': 0.07990647329452692, 'reg_lambda': 0.0009145938543521322, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.
[I 2025-11-10 19:00:12,259] Trial 192 pruned.

Best trial: 105. Best value: 0.692583:  96%|█████████▋| 193/200 [01:20<00:02,  2.51it/s]

[I 2025-11-10 19:00:12,636] Trial 194 pruned.

Best trial: 105. Best value: 0.692583:  97%|█████████▋| 194/200 [01:21<00:02,  2.59it/s]

[I 2025-11-10 19:00:12,990] Trial 195 pruned.

Best trial: 105. Best value: 0.692583:  98%|█████████▊| 195/200 [01:22<00:03,  1.65it/s]

[I 2025-11-10 19:00:14,130] Trial 191 finished with value: 0.6471247563352825 and parameters: {'max_depth': 8, 'learning_rate': 0.20800570001638138, 'n_estimators': 693, 'subsample': 0.9859243919034036, 'colsample_bytree': 0.982804286972274, 'min_child_weight': 5, 'gamma': 1.2307264428027263, 'reg_alpha': 0.07197496624291334, 'reg_lambda': 0.0008463634026200818, 'max_delta_step': 5}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  98%|█████████▊| 196/200 [01:24<00:04,  1.05s/it]

[I 2025-11-10 19:00:16,232] Trial 193 finished with value: 0.6464035087719298 and parameters: {'max_depth': 8, 'learning_rate': 0.20685182099074823, 'n_estimators': 729, 'subsample': 0.9841030896602505, 'colsample_bytree': 0.9821095040669169, 'min_child_weight': 5, 'gamma': 0.5314756495778503, 'reg_alpha': 0.022179708964472113, 'reg_lambda': 0.0007792951463925291, 'max_delta_step': 5}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  98%|█████████▊| 197/200 [01:25<00:03,  1.03s/it]

[I 2025-11-10 19:00:17,226] Trial 196 finished with value: 0.6261988304093566 and parameters: {'max_depth': 8, 'learning_rate': 0.22180555619405184, 'n_estimators': 720, 'subsample': 0.9739724015663558, 'colsample_bytree': 0.9656940698805494, 'min_child_weight': 5, 'gamma': 0.5078482994496651, 'reg_alpha': 3.4376678231708273, 'reg_lambda': 0.2458648389311472, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583:  99%|█████████▉| 198/200 [01:25<00:01,  1.24it/s]

[I 2025-11-10 19:00:17,517] Trial 197 finished with value: 0.665672514619883 and parameters: {'max_depth': 9, 'learning_rate': 0.12274863320239726, 'n_estimators': 725, 'subsample': 0.9740142917005881, 'colsample_bytree': 0.9654972785673233, 'min_child_weight': 5, 'gamma': 1.2373351757625337, 'reg_alpha': 2.6998121672705944, 'reg_lambda': 0.0024335298208857017, 'max_delta_step': 4}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583: 100%|█████████▉| 199/200 [01:26<00:00,  1.30it/s]

[I 2025-11-10 19:00:18,197] Trial 198 finished with value: 0.6677095516569201 and parameters: {'max_depth': 8, 'learning_rate': 0.2183060466000014, 'n_estimators': 719, 'subsample': 0.9742705850864847, 'colsample_bytree': 0.9784689999802254, 'min_child_weight': 5, 'gamma': 1.3500892265842888, 'reg_alpha': 0.05413821586007572, 'reg_lambda': 0.0005082796331211326, 'max_delta_step': 5}. Best is trial 105 with value: 0.6925828460038985.

Best trial: 105. Best value: 0.692583: 100%|██████████| 200/200 [01:26<00:00,  2.30it/s]

[I 2025-11-10 19:00:18,769] Trial 199 finished with value: 0.6293762183235867 and parameters: {'max_depth': 8, 'learning_rate': 0.21808201111434863, 'n_estimators': 716, 'subsample': 0.9742023851970205, 'colsample_bytree': 0.9670603350560434, 'min_child_weight': 5, 'gamma': 1.1962743073745268, 'reg_alpha': 0.021440763589358605, 'reg_lambda': 0.00023584472947892442, 'max_delta_step': 5}. Best is trial 105 with value: 0.6925828460038985.

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\utils\_plotting.py:28: RuntimeWarning:

More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.

[I 2025-11-10 19:00:19,474] A new study created in memory with name: 17_1_roc_auc
Best trial: 1. Best value: 0.5:   0%|          | 1/200 [00:01<03:54,  1.18s/it]

[I 2025-11-10 19:00:20,643] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 10, 'learning_rate': 0.013844206279977072, 'n_estimators': 300, 'subsample': 0.5340846575574362, 'colsample_bytree': 0.8089406231781069, 'min_child_weight': 7, 'gamma': 2.9138128481305263, 'reg_alpha': 3.471165545523572e-06, 'reg_lambda': 0.0004804232937088626, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:   1%|          | 2/200 [00:01<01:59,  1.66it/s]

[I 2025-11-10 19:00:20,844] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.06605604997010944, 'n_estimators': 327, 'subsample': 0.6692375713438963, 'colsample_bytree': 0.9799124691013392, 'min_child_weight': 6, 'gamma': 2.2760539948622722, 'reg_alpha': 1.2040651714873127, 'reg_lambda': 1.9521505271251294e-07, 'max_delta_step': 7}. Best is trial 1 with value: 0.5.

Best trial: 0. Best value: 0.501813:   2%|▏         | 3/200 [00:03<03:39,  1.12s/it]

[I 2025-11-10 19:00:22,573] Trial 0 finished with value: 0.5018128654970759 and parameters: {'max_depth': 10, 'learning_rate': 0.11764275353607537, 'n_estimators': 565, 'subsample': 0.7398394656432521, 'colsample_bytree': 0.8847309816890373, 'min_child_weight': 1, 'gamma': 0.46417239793675735, 'reg_alpha': 0.015736150165905814, 'reg_lambda': 2.4839469060939797e-06, 'max_delta_step': 1}. Best is trial 0 with value: 0.5018128654970759.

Best trial: 2. Best value: 0.53922:   2%|▏         | 4/200 [00:04<04:23,  1.34s/it]

[I 2025-11-10 19:00:24,266] Trial 2 finished with value: 0.5392202729044835 and parameters: {'max_depth': 10, 'learning_rate': 0.017989357741321533, 'n_estimators': 661, 'subsample': 0.5771062741861201, 'colsample_bytree': 0.9370220583606195, 'min_child_weight': 1, 'gamma': 4.594765992485938, 'reg_alpha': 0.09325885805852523, 'reg_lambda': 2.7114955595312115e-06, 'max_delta_step': 3}. Best is trial 2 with value: 0.5392202729044835.

Best trial: 4. Best value: 0.547251:   2%|▎         | 5/200 [00:06<04:19,  1.33s/it]

[I 2025-11-10 19:00:25,581] Trial 4 finished with value: 0.547251461988304 and parameters: {'max_depth': 8, 'learning_rate': 0.014087958878321144, 'n_estimators': 1385, 'subsample': 0.7156752811318882, 'colsample_bytree': 0.6810724099698349, 'min_child_weight': 4, 'gamma': 3.5957150659245563, 'reg_alpha': 1.6633723068104612e-08, 'reg_lambda': 0.00016237697181030724, 'max_delta_step': 8}. Best is trial 4 with value: 0.547251461988304.
[I 2025-11-10 19:00:25,756] Trial 5 finished with value: 0.5088888888888888 and parameters: {'max_depth': 5, 'learning_rate': 0.012722402284275828, 'n_estimators': 922, 'subsample': 0.5991681326490021, 'colsample_bytree': 0.7510947914351016, 'min_child_weight': 1, 'gamma': 2.732524235067274, 'reg_alpha': 5.663476685157517, 'reg_lambda': 1.9042600683828156e-06, 'max_delta_step': 7}. Best is trial 4 with value: 0.547251461988304.

Best trial: 4. Best value: 0.547251:   4%|▎         | 7/200 [00:08<03:54,  1.21s/it]

[I 2025-11-10 19:00:27,537] Trial 6 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.04594841982346151, 'n_estimators': 1370, 'subsample': 0.8829609071245332, 'colsample_bytree': 0.7186504168871604, 'min_child_weight': 6, 'gamma': 2.0619642704335113, 'reg_alpha': 0.0001487412739219517, 'reg_lambda': 4.11493948071334e-05, 'max_delta_step': 2}. Best is trial 4 with value: 0.547251461988304.

Best trial: 4. Best value: 0.547251:   4%|▍         | 8/200 [00:09<04:08,  1.29s/it]

[I 2025-11-10 19:00:28,997] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.1915200127999611, 'n_estimators': 767, 'subsample': 0.7851232051933992, 'colsample_bytree': 0.8639722971285912, 'min_child_weight': 1, 'gamma': 3.054150431311575, 'reg_alpha': 6.7931338104701995, 'reg_lambda': 0.20586280411838845, 'max_delta_step': 5}. Best is trial 4 with value: 0.547251461988304.

Best trial: 4. Best value: 0.547251:   4%|▍         | 9/200 [00:10<04:05,  1.29s/it]

[I 2025-11-10 19:00:30,273] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.02200636195310526, 'n_estimators': 1228, 'subsample': 0.5932906713415704, 'colsample_bytree': 0.6324920915680037, 'min_child_weight': 9, 'gamma': 4.8255056516516355, 'reg_alpha': 1.548127446004425e-06, 'reg_lambda': 1.3156833567304556e-05, 'max_delta_step': 10}. Best is trial 4 with value: 0.547251461988304.

Best trial: 4. Best value: 0.547251:   5%|▌         | 10/200 [00:11<03:06,  1.02it/s]

[I 2025-11-10 19:00:30,573] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 5, 'learning_rate': 0.0488401060464763, 'n_estimators': 1294, 'subsample': 0.6503327044229225, 'colsample_bytree': 0.7391852241162135, 'min_child_weight': 8, 'gamma': 1.3459020768228414, 'reg_alpha': 2.335564927497036, 'reg_lambda': 0.6522817034796491, 'max_delta_step': 1}. Best is trial 4 with value: 0.547251461988304.

Best trial: 4. Best value: 0.547251:   6%|▌         | 11/200 [00:13<04:06,  1.30s/it]

[I 2025-11-10 19:00:32,607] Trial 10 finished with value: 0.4964717348927875 and parameters: {'max_depth': 7, 'learning_rate': 0.05866103944617815, 'n_estimators': 1096, 'subsample': 0.9706364733573565, 'colsample_bytree': 0.542876632923248, 'min_child_weight': 3, 'gamma': 2.1608154235596833, 'reg_alpha': 0.006856946613301016, 'reg_lambda': 0.0015941556012333917, 'max_delta_step': 8}. Best is trial 4 with value: 0.547251461988304.
[I 2025-11-10 19:00:32,632] Trial 11 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.05699014530378289, 'n_estimators': 845, 'subsample': 0.5040216765779157, 'colsample_bytree': 0.9304376975645614, 'min_child_weight': 6, 'gamma': 1.0854413224035357, 'reg_alpha': 0.00020257276498935868, 'reg_lambda': 1.6508255467686836, 'max_delta_step': 2}. Best is trial 4 with value: 0.547251461988304.

Best trial: 13. Best value: 0.580585:   6%|▋         | 13/200 [00:15<03:55,  1.26s/it]

[I 2025-11-10 19:00:35,033] Trial 13 finished with value: 0.5805847953216374 and parameters: {'max_depth': 7, 'learning_rate': 0.028066063218870497, 'n_estimators': 1043, 'subsample': 0.9442274409420073, 'colsample_bytree': 0.501308158853296, 'min_child_weight': 4, 'gamma': 3.89709450993995, 'reg_alpha': 1.3348657186541514e-08, 'reg_lambda': 0.0048283751770815024, 'max_delta_step': 10}. Best is trial 13 with value: 0.5805847953216374.
[I 2025-11-10 19:00:35,125] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.047673295445871657, 'n_estimators': 1153, 'subsample': 0.5664729804896502, 'colsample_bytree': 0.8598745776818364, 'min_child_weight': 4, 'gamma': 2.078997460390815, 'reg_alpha': 5.695591930960978e-06, 'reg_lambda': 0.000697791958913733, 'max_delta_step': 0}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:   8%|▊         | 15/200 [00:16<02:36,  1.18it/s]

[I 2025-11-10 19:00:35,484] Trial 14 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.022074648147940204, 'n_estimators': 637, 'subsample': 0.5170295800815189, 'colsample_bytree': 0.9935644266058713, 'min_child_weight': 4, 'gamma': 4.429340893051807, 'reg_alpha': 1.894954071145323e-08, 'reg_lambda': 3.3343922584028574e-08, 'max_delta_step': 3}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:   8%|▊         | 16/200 [00:17<02:54,  1.05it/s]

[I 2025-11-10 19:00:36,795] Trial 18 pruned.

Best trial: 13. Best value: 0.580585:   8%|▊         | 17/200 [00:19<03:38,  1.19s/it]

[I 2025-11-10 19:00:38,756] Trial 15 finished with value: 0.5102826510721248 and parameters: {'max_depth': 8, 'learning_rate': 0.027991962955222046, 'n_estimators': 1481, 'subsample': 0.7475331648686186, 'colsample_bytree': 0.6325791868778101, 'min_child_weight': 4, 'gamma': 4.341479280116069, 'reg_alpha': 1.3985054426655374e-08, 'reg_lambda': 3.246033004839413e-08, 'max_delta_step': 4}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:   9%|▉         | 18/200 [00:20<03:18,  1.09s/it]

[I 2025-11-10 19:00:39,552] Trial 16 finished with value: 0.5358869395711502 and parameters: {'max_depth': 7, 'learning_rate': 0.0269282397014531, 'n_estimators': 1117, 'subsample': 0.8352704988647754, 'colsample_bytree': 0.5001120728534172, 'min_child_weight': 4, 'gamma': 3.7396678166766253, 'reg_alpha': 2.19705137509536e-08, 'reg_lambda': 0.00521525144741304, 'max_delta_step': 10}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  10%|▉         | 19/200 [00:21<03:16,  1.09s/it]

[I 2025-11-10 19:00:40,627] Trial 21 pruned.

Best trial: 13. Best value: 0.580585:  10%|█         | 20/200 [00:21<02:31,  1.19it/s]

[I 2025-11-10 19:00:40,826] Trial 17 finished with value: 0.5253996101364522 and parameters: {'max_depth': 8, 'learning_rate': 0.026983394605533156, 'n_estimators': 1434, 'subsample': 0.8092526624030252, 'colsample_bytree': 0.5194601803277337, 'min_child_weight': 4, 'gamma': 3.9094068387191476, 'reg_alpha': 1.717807968314345e-08, 'reg_lambda': 0.0175359336319123, 'max_delta_step': 10}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  10%|█         | 21/200 [00:22<02:38,  1.13it/s]

[I 2025-11-10 19:00:41,832] Trial 19 finished with value: 0.5721247563352827 and parameters: {'max_depth': 6, 'learning_rate': 0.010520474775385072, 'n_estimators': 1017, 'subsample': 0.9850575807507499, 'colsample_bytree': 0.6266826154449611, 'min_child_weight': 4, 'gamma': 3.7780795850004787, 'reg_alpha': 1.6013810051634032e-07, 'reg_lambda': 0.010255212231970295, 'max_delta_step': 9}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  12%|█▏        | 23/200 [00:23<01:53,  1.56it/s]

[I 2025-11-10 19:00:42,613] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.010608366032385129, 'n_estimators': 930, 'subsample': 0.9640212826984391, 'colsample_bytree': 0.605263902708985, 'min_child_weight': 10, 'gamma': 3.6755580104958128, 'reg_alpha': 3.049123107144705e-07, 'reg_lambda': 0.008145902459662235, 'max_delta_step': 8}. Best is trial 13 with value: 0.5805847953216374.
[I 2025-11-10 19:00:42,732] Trial 24 pruned.

Best trial: 13. Best value: 0.580585:  12%|█▏        | 24/200 [00:24<01:59,  1.47it/s]

[I 2025-11-10 19:00:43,494] Trial 25 pruned.

Best trial: 13. Best value: 0.580585:  12%|█▎        | 25/200 [00:25<02:25,  1.21it/s]

[I 2025-11-10 19:00:44,689] Trial 23 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.2989662399989356, 'n_estimators': 1006, 'subsample': 0.9101237947737033, 'colsample_bytree': 0.5811124441100901, 'min_child_weight': 10, 'gamma': 3.2765832019400905, 'reg_alpha': 2.2776116092284443e-07, 'reg_lambda': 9.515056371709973, 'max_delta_step': 7}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  13%|█▎        | 26/200 [00:25<01:53,  1.54it/s]

[I 2025-11-10 19:00:44,913] Trial 27 pruned.

Best trial: 13. Best value: 0.580585:  14%|█▎        | 27/200 [00:26<02:07,  1.36it/s]

[I 2025-11-10 19:00:45,852] Trial 22 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.10660399651755406, 'n_estimators': 1331, 'subsample': 0.9051760936358572, 'colsample_bytree': 0.6764562519518347, 'min_child_weight': 10, 'gamma': 3.333846344692537, 'reg_alpha': 3.4345099067550244e-07, 'reg_lambda': 3.6210762387581065e-05, 'max_delta_step': 7}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  14%|█▍        | 28/200 [00:27<02:26,  1.18it/s]

[I 2025-11-10 19:00:46,968] Trial 30 pruned.

Best trial: 13. Best value: 0.580585:  14%|█▍        | 29/200 [00:29<03:19,  1.17s/it]

[I 2025-11-10 19:00:48,877] Trial 29 finished with value: 0.5246393762183236 and parameters: {'max_depth': 4, 'learning_rate': 0.034528626184713085, 'n_estimators': 811, 'subsample': 0.7120971551273371, 'colsample_bytree': 0.556447073859862, 'min_child_weight': 2, 'gamma': 2.5584251486256635, 'reg_alpha': 2.390542723495516e-05, 'reg_lambda': 0.22251928273823454, 'max_delta_step': 9}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  15%|█▌        | 30/200 [00:30<03:03,  1.08s/it]

[I 2025-11-10 19:00:49,759] Trial 26 finished with value: 0.5520857699805067 and parameters: {'max_depth': 5, 'learning_rate': 0.016417964275269897, 'n_estimators': 1221, 'subsample': 0.9130646256733551, 'colsample_bytree': 0.6865247960636142, 'min_child_weight': 2, 'gamma': 4.08442538324215, 'reg_alpha': 2.361615356494431e-05, 'reg_lambda': 0.10851964425316142, 'max_delta_step': 7}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  16%|█▌        | 31/200 [00:30<02:26,  1.15it/s]

[I 2025-11-10 19:00:50,132] Trial 31 finished with value: 0.48619883040935663 and parameters: {'max_depth': 7, 'learning_rate': 0.03601761470431545, 'n_estimators': 795, 'subsample': 0.9955046021595123, 'colsample_bytree': 0.6476933696253491, 'min_child_weight': 5, 'gamma': 4.080195213330868, 'reg_alpha': 5.783307229567944e-08, 'reg_lambda': 0.001176049792069327, 'max_delta_step': 9}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  16%|█▌        | 32/200 [00:31<02:07,  1.32it/s]

[I 2025-11-10 19:00:50,623] Trial 33 pruned.

Best trial: 13. Best value: 0.580585:  17%|█▋        | 34/200 [00:31<01:30,  1.84it/s]

[I 2025-11-10 19:00:51,274] Trial 32 finished with value: 0.4916374269005847 and parameters: {'max_depth': 7, 'learning_rate': 0.03785321539522566, 'n_estimators': 523, 'subsample': 0.9983422048936329, 'colsample_bytree': 0.7998569784195324, 'min_child_weight': 5, 'gamma': 4.079576266093483, 'reg_alpha': 1.1293939745238245e-06, 'reg_lambda': 0.0019846483184040344, 'max_delta_step': 9}. Best is trial 13 with value: 0.5805847953216374.
[I 2025-11-10 19:00:51,397] Trial 28 finished with value: 0.5344054580896687 and parameters: {'max_depth': 5, 'learning_rate': 0.01907588743648512, 'n_estimators': 1279, 'subsample': 0.7024461758840987, 'colsample_bytree': 0.6761130249804586, 'min_child_weight': 2, 'gamma': 4.12724209020709, 'reg_alpha': 8.65095021552983e-06, 'reg_lambda': 0.07402291463570933, 'max_delta_step': 9}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  18%|█▊        | 35/200 [00:33<02:16,  1.21it/s]

[I 2025-11-10 19:00:52,892] Trial 35 pruned.

Best trial: 13. Best value: 0.580585:  18%|█▊        | 36/200 [00:34<02:05,  1.31it/s]

[I 2025-11-10 19:00:53,508] Trial 36 pruned.
[I 2025-11-10 19:00:53,540] Trial 37 pruned.

Best trial: 13. Best value: 0.580585:  19%|█▉        | 38/200 [00:35<01:59,  1.36it/s]

[I 2025-11-10 19:00:54,912] Trial 39 pruned.

Best trial: 13. Best value: 0.580585:  20%|█▉        | 39/200 [00:36<02:21,  1.14it/s]

[I 2025-11-10 19:00:56,225] Trial 34 finished with value: 0.5534307992202728 and parameters: {'max_depth': 5, 'learning_rate': 0.014727675859366695, 'n_estimators': 1103, 'subsample': 0.9343315433246738, 'colsample_bytree': 0.7865198515859061, 'min_child_weight': 3, 'gamma': 4.61952240990158, 'reg_alpha': 1.1521032370928343e-06, 'reg_lambda': 0.0026448338264936553, 'max_delta_step': 6}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  20%|██        | 40/200 [00:39<03:18,  1.24s/it]

[I 2025-11-10 19:00:58,475] Trial 38 finished with value: 0.5588304093567251 and parameters: {'max_depth': 8, 'learning_rate': 0.015442618244767163, 'n_estimators': 1124, 'subsample': 0.7782908687227076, 'colsample_bytree': 0.7647651956382951, 'min_child_weight': 3, 'gamma': 3.573417031508642, 'reg_alpha': 0.08264540289860459, 'reg_lambda': 0.0002429645985812518, 'max_delta_step': 6}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  20%|██        | 41/200 [00:40<03:29,  1.32s/it]

[I 2025-11-10 19:01:00,010] Trial 40 finished with value: 0.5036452241715399 and parameters: {'max_depth': 8, 'learning_rate': 0.016574500962255417, 'n_estimators': 1204, 'subsample': 0.8599002878283836, 'colsample_bytree': 0.7671736861754997, 'min_child_weight': 3, 'gamma': 0.1222130302318778, 'reg_alpha': 6.171534956652188e-08, 'reg_lambda': 3.820419221383012e-06, 'max_delta_step': 7}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  21%|██        | 42/200 [00:40<02:39,  1.01s/it]

[I 2025-11-10 19:01:00,231] Trial 41 finished with value: 0.5576023391812865 and parameters: {'max_depth': 8, 'learning_rate': 0.07981781536095621, 'n_estimators': 917, 'subsample': 0.6624876429294836, 'colsample_bytree': 0.6540701370148104, 'min_child_weight': 1, 'gamma': 2.9329229554556084, 'reg_alpha': 0.07364182725287734, 'reg_lambda': 0.4184809395000367, 'max_delta_step': 7}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  22%|██▏       | 43/200 [00:41<02:38,  1.01s/it]

[I 2025-11-10 19:01:01,243] Trial 45 pruned.

Best trial: 13. Best value: 0.580585:  22%|██▏       | 44/200 [00:42<02:14,  1.16it/s]

[I 2025-11-10 19:01:01,748] Trial 42 finished with value: 0.5591228070175439 and parameters: {'max_depth': 4, 'learning_rate': 0.022846404078682193, 'n_estimators': 916, 'subsample': 0.9490883923844537, 'colsample_bytree': 0.644294471887437, 'min_child_weight': 1, 'gamma': 4.952644484094409, 'reg_alpha': 8.619455735882959e-05, 'reg_lambda': 0.031506747405686875, 'max_delta_step': 5}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  22%|██▎       | 45/200 [00:44<03:35,  1.39s/it]

[I 2025-11-10 19:01:04,408] Trial 43 finished with value: 0.5471150097465887 and parameters: {'max_depth': 8, 'learning_rate': 0.022863783126374375, 'n_estimators': 921, 'subsample': 0.9581369471677255, 'colsample_bytree': 0.8165355766938847, 'min_child_weight': 1, 'gamma': 4.993728435607574, 'reg_alpha': 0.053659154664488805, 'reg_lambda': 0.004340313747430646, 'max_delta_step': 5}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  23%|██▎       | 46/200 [00:46<03:41,  1.44s/it]

[I 2025-11-10 19:01:05,954] Trial 48 finished with value: 0.5510916179337231 and parameters: {'max_depth': 3, 'learning_rate': 0.07685238069277313, 'n_estimators': 220, 'subsample': 0.6574004947724306, 'colsample_bytree': 0.7420242643189974, 'min_child_weight': 1, 'gamma': 2.946247732756399, 'reg_alpha': 0.2345066094038537, 'reg_lambda': 0.031032966743656246, 'max_delta_step': 4}. Best is trial 13 with value: 0.5805847953216374.

[I 2025-11-10 19:01:06,345] Trial 46 finished with value: 0.5246393762183235 and parameters: {'max_depth': 8, 'learning_rate': 0.08354104232151967, 'n_estimators': 902, 'subsample': 0.6497078946283612, 'colsample_bytree': 0.8172479510752256, 'min_child_weight': 1, 'gamma': 2.7806455765319824, 'reg_alpha': 0.3269347473976988, 'reg_lambda': 0.025308010719504403, 'max_delta_step': 5}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  24%|██▍       | 48/200 [00:47<02:08,  1.19it/s]

[I 2025-11-10 19:01:06,522] Trial 44 finished with value: 0.558849902534113 and parameters: {'max_depth': 5, 'learning_rate': 0.022250557524577174, 'n_estimators': 933, 'subsample': 0.9428762766399322, 'colsample_bytree': 0.8223233071089353, 'min_child_weight': 1, 'gamma': 2.9320364738016647, 'reg_alpha': 0.06974434646847581, 'reg_lambda': 0.0035946851817799685, 'max_delta_step': 5}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  25%|██▌       | 50/200 [00:47<01:18,  1.92it/s]

[I 2025-11-10 19:01:06,873] Trial 47 finished with value: 0.5135282651072124 and parameters: {'max_depth': 3, 'learning_rate': 0.0740885491985942, 'n_estimators': 909, 'subsample': 0.6704199911445108, 'colsample_bytree': 0.7321543364076892, 'min_child_weight': 1, 'gamma': 2.813774276315499, 'reg_alpha': 0.3702332950750244, 'reg_lambda': 0.8081456431111185, 'max_delta_step': 5}. Best is trial 13 with value: 0.5805847953216374.
[I 2025-11-10 19:01:06,978] Trial 49 pruned.

Best trial: 13. Best value: 0.580585:  26%|██▌       | 51/200 [00:50<03:24,  1.37s/it]

[I 2025-11-10 19:01:10,337] Trial 50 finished with value: 0.5451461988304094 and parameters: {'max_depth': 9, 'learning_rate': 0.012047181722852103, 'n_estimators': 700, 'subsample': 0.7712035462197719, 'colsample_bytree': 0.6407005015649294, 'min_child_weight': 2, 'gamma': 3.5178184729493935, 'reg_alpha': 0.025197296018468318, 'reg_lambda': 0.631951767755094, 'max_delta_step': 4}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  26%|██▌       | 52/200 [00:51<03:00,  1.22s/it]

[I 2025-11-10 19:01:11,201] Trial 51 finished with value: 0.5693957115009747 and parameters: {'max_depth': 4, 'learning_rate': 0.012039705535005505, 'n_estimators': 715, 'subsample': 0.9625237881306197, 'colsample_bytree': 0.8571033870087775, 'min_child_weight': 2, 'gamma': 3.4440489230914406, 'reg_alpha': 0.01824782907244865, 'reg_lambda': 0.007483071135031038, 'max_delta_step': 4}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  26%|██▋       | 53/200 [00:53<03:28,  1.42s/it]

[I 2025-11-10 19:01:13,086] Trial 53 finished with value: 0.5592592592592592 and parameters: {'max_depth': 4, 'learning_rate': 0.02410974360943575, 'n_estimators': 1036, 'subsample': 0.9585928384071621, 'colsample_bytree': 0.8943622046528378, 'min_child_weight': 2, 'gamma': 3.5333349653960706, 'reg_alpha': 0.01630886479769214, 'reg_lambda': 0.0005901885675805915, 'max_delta_step': 3}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  27%|██▋       | 54/200 [00:54<03:13,  1.32s/it]

[I 2025-11-10 19:01:14,186] Trial 52 finished with value: 0.5145614035087719 and parameters: {'max_depth': 4, 'learning_rate': 0.011910086729099266, 'n_estimators': 1060, 'subsample': 0.963249765307219, 'colsample_bytree': 0.9087114310048625, 'min_child_weight': 2, 'gamma': 1.5483278892806074, 'reg_alpha': 0.0193959901565473, 'reg_lambda': 0.0005525379289899986, 'max_delta_step': 4}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  28%|██▊       | 55/200 [00:55<02:31,  1.05s/it]

[I 2025-11-10 19:01:14,585] Trial 55 finished with value: 0.5060233918128655 and parameters: {'max_depth': 4, 'learning_rate': 0.02559147772240594, 'n_estimators': 490, 'subsample': 0.9701339089846615, 'colsample_bytree': 0.9278670707478047, 'min_child_weight': 2, 'gamma': 1.9027654491156825, 'reg_alpha': 0.004969639151070567, 'reg_lambda': 0.0005778778886868811, 'max_delta_step': 3}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  28%|██▊       | 56/200 [00:56<02:57,  1.24s/it]

[I 2025-11-10 19:01:16,268] Trial 58 pruned.

Best trial: 13. Best value: 0.580585:  28%|██▊       | 57/200 [00:57<02:25,  1.02s/it]

[I 2025-11-10 19:01:16,779] Trial 59 pruned.

Best trial: 13. Best value: 0.580585:  29%|██▉       | 58/200 [00:57<01:52,  1.26it/s]

[I 2025-11-10 19:01:17,046] Trial 54 finished with value: 0.5384990253411306 and parameters: {'max_depth': 4, 'learning_rate': 0.02356299646509889, 'n_estimators': 1071, 'subsample': 0.9655392200665169, 'colsample_bytree': 0.924178713249627, 'min_child_weight': 2, 'gamma': 2.401793249982946, 'reg_alpha': 1.356203824195924, 'reg_lambda': 0.0005407627710213806, 'max_delta_step': 3}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  30%|██▉       | 59/200 [00:57<01:28,  1.60it/s]

[I 2025-11-10 19:01:17,280] Trial 57 finished with value: 0.5749512670565302 and parameters: {'max_depth': 4, 'learning_rate': 0.023344080432068624, 'n_estimators': 452, 'subsample': 0.9798074555050178, 'colsample_bytree': 0.8840967227577936, 'min_child_weight': 2, 'gamma': 3.915216320720208, 'reg_alpha': 0.0010438233001115555, 'reg_lambda': 0.00674623999309543, 'max_delta_step': 3}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  30%|███       | 60/200 [00:58<01:17,  1.80it/s]

[I 2025-11-10 19:01:17,670] Trial 62 pruned.

Best trial: 13. Best value: 0.580585:  30%|███       | 61/200 [00:58<01:03,  2.20it/s]

[I 2025-11-10 19:01:17,888] Trial 61 pruned.

Best trial: 13. Best value: 0.580585:  31%|███       | 62/200 [00:59<01:12,  1.91it/s]

[I 2025-11-10 19:01:18,577] Trial 63 pruned.

Best trial: 13. Best value: 0.580585:  32%|███▏      | 63/200 [00:59<01:25,  1.60it/s]

[I 2025-11-10 19:01:19,436] Trial 56 finished with value: 0.5216959064327485 and parameters: {'max_depth': 4, 'learning_rate': 0.04173929640261173, 'n_estimators': 1066, 'subsample': 0.9690461317198358, 'colsample_bytree': 0.9125079971197761, 'min_child_weight': 2, 'gamma': 1.6325778429880753, 'reg_alpha': 0.000564780949519625, 'reg_lambda': 0.0009403218108755649, 'max_delta_step': 3}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  32%|███▏      | 64/200 [01:01<02:11,  1.03it/s]

[I 2025-11-10 19:01:21,211] Trial 65 finished with value: 0.5438206627680311 and parameters: {'max_depth': 4, 'learning_rate': 0.029494429226383134, 'n_estimators': 405, 'subsample': 0.9482862574908852, 'colsample_bytree': 0.8345727904632406, 'min_child_weight': 2, 'gamma': 3.461732528256882, 'reg_alpha': 0.029976986765765715, 'reg_lambda': 0.017102410162045875, 'max_delta_step': 1}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  32%|███▎      | 65/200 [01:02<01:45,  1.28it/s]

[I 2025-11-10 19:01:21,554] Trial 64 finished with value: 0.5528654970760234 and parameters: {'max_depth': 4, 'learning_rate': 0.030529186332667973, 'n_estimators': 579, 'subsample': 0.9506622104319389, 'colsample_bytree': 0.8946832385128056, 'min_child_weight': 2, 'gamma': 3.492248154024767, 'reg_alpha': 0.010529148719085408, 'reg_lambda': 8.612747519311865e-07, 'max_delta_step': 3}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  33%|███▎      | 66/200 [01:02<01:43,  1.30it/s]

[I 2025-11-10 19:01:22,295] Trial 67 pruned.

Best trial: 13. Best value: 0.580585:  34%|███▎      | 67/200 [01:03<01:36,  1.38it/s]

[I 2025-11-10 19:01:22,917] Trial 66 finished with value: 0.5757699805068226 and parameters: {'max_depth': 5, 'learning_rate': 0.0297630675093565, 'n_estimators': 453, 'subsample': 0.8937214796409443, 'colsample_bytree': 0.8617878966513921, 'min_child_weight': 1, 'gamma': 3.5142685860474807, 'reg_alpha': 0.03442020239179594, 'reg_lambda': 0.04279807670218067, 'max_delta_step': 1}. Best is trial 13 with value: 0.5805847953216374.
[I 2025-11-10 19:01:22,960] Trial 60 finished with value: 0.5462573099415204 and parameters: {'max_depth': 4, 'learning_rate': 0.031763859311703106, 'n_estimators': 1051, 'subsample': 0.921379159021735, 'colsample_bytree': 0.8934660834337462, 'min_child_weight': 2, 'gamma': 3.100184885089865, 'reg_alpha': 1.8358628077784818, 'reg_lambda': 0.011964562494655944, 'max_delta_step': 3}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 13. Best value: 0.580585:  35%|███▌      | 70/200 [01:04<00:58,  2.24it/s]

[I 2025-11-10 19:01:23,610] Trial 71 pruned.
[I 2025-11-10 19:01:23,745] Trial 70 pruned.

Best trial: 13. Best value: 0.580585:  36%|███▌      | 71/200 [01:04<00:51,  2.51it/s]

[I 2025-11-10 19:01:24,007] Trial 72 pruned.

Best trial: 13. Best value: 0.580585:  36%|███▌      | 72/200 [01:07<02:36,  1.22s/it]

[I 2025-11-10 19:01:27,433] Trial 73 finished with value: 0.5645614035087719 and parameters: {'max_depth': 5, 'learning_rate': 0.024944945113330043, 'n_estimators': 709, 'subsample': 0.9810584468599981, 'colsample_bytree': 0.5286096332931586, 'min_child_weight': 1, 'gamma': 4.2976497036156545, 'reg_alpha': 5.066475376305478e-05, 'reg_lambda': 0.13808058379806962, 'max_delta_step': 0}. Best is trial 13 with value: 0.5805847953216374.

Best trial: 68. Best value: 0.60306:  36%|███▋      | 73/200 [01:09<02:30,  1.19s/it]

[I 2025-11-10 19:01:28,527] Trial 68 finished with value: 0.6030604288499026 and parameters: {'max_depth': 5, 'learning_rate': 0.01818235175501871, 'n_estimators': 966, 'subsample': 0.9833147665733513, 'colsample_bytree': 0.865537850300097, 'min_child_weight': 1, 'gamma': 3.178665209570817, 'reg_alpha': 0.002198889185890922, 'reg_lambda': 0.0036234692664412482, 'max_delta_step': 10}. Best is trial 68 with value: 0.6030604288499026.

Best trial: 68. Best value: 0.60306:  37%|███▋      | 74/200 [01:10<02:19,  1.11s/it]

[I 2025-11-10 19:01:29,446] Trial 74 finished with value: 0.5759064327485379 and parameters: {'max_depth': 5, 'learning_rate': 0.0253705892562854, 'n_estimators': 974, 'subsample': 0.9534120400903356, 'colsample_bytree': 0.6149373044357213, 'min_child_weight': 1, 'gamma': 3.645811712005155, 'reg_alpha': 0.03857872264238698, 'reg_lambda': 0.12378287934455619, 'max_delta_step': 5}. Best is trial 68 with value: 0.6030604288499026.
[I 2025-11-10 19:01:29,474] Trial 69 finished with value: 0.5765107212475634 and parameters: {'max_depth': 5, 'learning_rate': 0.01861251094291135, 'n_estimators': 981, 'subsample': 0.891950297465753, 'colsample_bytree': 0.9518446067379638, 'min_child_weight': 1, 'gamma': 3.7205432403793512, 'reg_alpha': 0.00012580797752502287, 'reg_lambda': 0.001453093711279593, 'max_delta_step': 10}. Best is trial 68 with value: 0.6030604288499026.

Best trial: 68. Best value: 0.60306:  38%|███▊      | 76/200 [01:11<02:10,  1.05s/it]

[I 2025-11-10 19:01:31,406] Trial 75 finished with value: 0.574093567251462 and parameters: {'max_depth': 6, 'learning_rate': 0.026367463820611302, 'n_estimators': 745, 'subsample': 0.9905184207082575, 'colsample_bytree': 0.5158354085754397, 'min_child_weight': 1, 'gamma': 3.647549443386432, 'reg_alpha': 8.398090161594861e-06, 'reg_lambda': 0.11045941915928699, 'max_delta_step': 0}. Best is trial 68 with value: 0.6030604288499026.

Best trial: 68. Best value: 0.60306:  38%|███▊      | 77/200 [01:13<02:12,  1.07s/it]

[I 2025-11-10 19:01:32,548] Trial 76 finished with value: 0.5791228070175439 and parameters: {'max_depth': 6, 'learning_rate': 0.025752973980511813, 'n_estimators': 727, 'subsample': 0.9914662474512983, 'colsample_bytree': 0.5283325732015286, 'min_child_weight': 1, 'gamma': 3.6444655387130065, 'reg_alpha': 0.0021261359214590726, 'reg_lambda': 0.0012557015081006157, 'max_delta_step': 0}. Best is trial 68 with value: 0.6030604288499026.

Best trial: 68. Best value: 0.60306:  39%|███▉      | 78/200 [01:13<01:59,  1.02it/s]

[I 2025-11-10 19:01:33,260] Trial 77 finished with value: 0.5660428849902535 and parameters: {'max_depth': 6, 'learning_rate': 0.025785806353772277, 'n_estimators': 706, 'subsample': 0.9859121872033032, 'colsample_bytree': 0.5408179642277687, 'min_child_weight': 1, 'gamma': 3.6663981934897505, 'reg_alpha': 0.0026464874619256304, 'reg_lambda': 1.7375007007022436, 'max_delta_step': 0}. Best is trial 68 with value: 0.6030604288499026.

Best trial: 68. Best value: 0.60306:  40%|███▉      | 79/200 [01:17<03:27,  1.71s/it]

[I 2025-11-10 19:01:36,964] Trial 79 finished with value: 0.5590253411306042 and parameters: {'max_depth': 6, 'learning_rate': 0.027241413796820414, 'n_estimators': 998, 'subsample': 0.8287641915818645, 'colsample_bytree': 0.6133003798515131, 'min_child_weight': 1, 'gamma': 3.6685068540939265, 'reg_alpha': 4.485428555811397e-06, 'reg_lambda': 1.195848078912955, 'max_delta_step': 10}. Best is trial 68 with value: 0.6030604288499026.

Best trial: 68. Best value: 0.60306:  40%|████      | 80/200 [01:17<02:39,  1.33s/it]

[I 2025-11-10 19:01:37,291] Trial 78 finished with value: 0.567251461988304 and parameters: {'max_depth': 6, 'learning_rate': 0.011095255897255322, 'n_estimators': 973, 'subsample': 0.841769679334886, 'colsample_bytree': 0.9873714641326122, 'min_child_weight': 1, 'gamma': 3.6381132968554524, 'reg_alpha': 0.0018903914575498027, 'reg_lambda': 0.0013325636792498176, 'max_delta_step': 10}. Best is trial 68 with value: 0.6030604288499026.

Best trial: 68. Best value: 0.60306:  40%|████      | 81/200 [01:18<02:12,  1.12s/it]

[I 2025-11-10 19:01:37,874] Trial 80 finished with value: 0.5775243664717349 and parameters: {'max_depth': 6, 'learning_rate': 0.026121454531284515, 'n_estimators': 988, 'subsample': 0.997108704693568, 'colsample_bytree': 0.5486565128973514, 'min_child_weight': 1, 'gamma': 3.73344621183866, 'reg_alpha': 0.0015439608462885876, 'reg_lambda': 1.32091697653509, 'max_delta_step': 0}. Best is trial 68 with value: 0.6030604288499026.

Best trial: 68. Best value: 0.60306:  41%|████      | 82/200 [01:18<01:51,  1.05it/s]

[I 2025-11-10 19:01:38,409] Trial 81 finished with value: 0.5711111111111111 and parameters: {'max_depth': 6, 'learning_rate': 0.02084886809439033, 'n_estimators': 980, 'subsample': 0.8442642840645602, 'colsample_bytree': 0.5120270647761271, 'min_child_weight': 1, 'gamma': 3.994418909062782, 'reg_alpha': 0.00025333574673163804, 'reg_lambda': 0.0017762305054678585, 'max_delta_step': 10}. Best is trial 68 with value: 0.6030604288499026.

Best trial: 68. Best value: 0.60306:  42%|████▏     | 83/200 [01:20<01:59,  1.02s/it]

[I 2025-11-10 19:01:39,597] Trial 85 pruned.

Best trial: 68. Best value: 0.60306:  42%|████▏     | 84/200 [01:20<01:52,  1.03it/s]

[I 2025-11-10 19:01:40,470] Trial 86 pruned.

Best trial: 68. Best value: 0.60306:  42%|████▎     | 85/200 [01:22<02:05,  1.09s/it]

[I 2025-11-10 19:01:41,838] Trial 83 finished with value: 0.590487329434698 and parameters: {'max_depth': 7, 'learning_rate': 0.03437302769427293, 'n_estimators': 799, 'subsample': 0.8866215116276036, 'colsample_bytree': 0.562826723371894, 'min_child_weight': 1, 'gamma': 3.333531613122092, 'reg_alpha': 1.1884421351164346e-05, 'reg_lambda': 9.804557714105912e-05, 'max_delta_step': 0}. Best is trial 68 with value: 0.6030604288499026.

Best trial: 68. Best value: 0.60306:  43%|████▎     | 86/200 [01:23<02:10,  1.14s/it]

[I 2025-11-10 19:01:43,103] Trial 82 finished with value: 0.5860623781676414 and parameters: {'max_depth': 7, 'learning_rate': 0.03374151887961526, 'n_estimators': 1168, 'subsample': 0.8818281918764671, 'colsample_bytree': 0.5085815206704304, 'min_child_weight': 1, 'gamma': 4.022315969192123, 'reg_alpha': 0.0014434409162061438, 'reg_lambda': 0.0013358487255812229, 'max_delta_step': 0}. Best is trial 68 with value: 0.6030604288499026.

Best trial: 68. Best value: 0.60306:  44%|████▍     | 88/200 [01:24<01:24,  1.32it/s]

[I 2025-11-10 19:01:43,852] Trial 89 pruned.
[I 2025-11-10 19:01:43,976] Trial 84 finished with value: 0.5765497076023391 and parameters: {'max_depth': 7, 'learning_rate': 0.03423581313956416, 'n_estimators': 1143, 'subsample': 0.9974443813975785, 'colsample_bytree': 0.509420798449916, 'min_child_weight': 1, 'gamma': 3.3220062698778987, 'reg_alpha': 0.0001597880848348106, 'reg_lambda': 0.00012126227413796284, 'max_delta_step': 0}. Best is trial 68 with value: 0.6030604288499026.

Best trial: 68. Best value: 0.60306:  44%|████▍     | 89/200 [01:25<01:38,  1.13it/s]

[I 2025-11-10 19:01:45,172] Trial 87 finished with value: 0.5867836257309941 and parameters: {'max_depth': 5, 'learning_rate': 0.027300032833946917, 'n_estimators': 863, 'subsample': 0.8810521090819289, 'colsample_bytree': 0.5065116839063307, 'min_child_weight': 1, 'gamma': 3.981871012662158, 'reg_alpha': 0.00045706445951600427, 'reg_lambda': 0.09515316597035355, 'max_delta_step': 0}. Best is trial 68 with value: 0.6030604288499026.

Best trial: 68. Best value: 0.60306:  45%|████▌     | 90/200 [01:27<01:58,  1.08s/it]

[I 2025-11-10 19:01:46,703] Trial 88 finished with value: 0.601364522417154 and parameters: {'max_depth': 7, 'learning_rate': 0.03892391695712113, 'n_estimators': 867, 'subsample': 0.8763657282628945, 'colsample_bytree': 0.5694324449446521, 'min_child_weight': 1, 'gamma': 4.001723184447281, 'reg_alpha': 0.0004558825846759613, 'reg_lambda': 8.664154282615554e-05, 'max_delta_step': 0}. Best is trial 68 with value: 0.6030604288499026.

Best trial: 68. Best value: 0.60306:  46%|████▌     | 91/200 [01:29<02:34,  1.42s/it]

[I 2025-11-10 19:01:48,910] Trial 93 pruned.

Best trial: 68. Best value: 0.60306:  46%|████▌     | 92/200 [01:30<02:32,  1.41s/it]

[I 2025-11-10 19:01:50,306] Trial 90 finished with value: 0.5603508771929824 and parameters: {'max_depth': 7, 'learning_rate': 0.0417321569278157, 'n_estimators': 1167, 'subsample': 0.8588523824038113, 'colsample_bytree': 0.5026330048178167, 'min_child_weight': 1, 'gamma': 3.2162734777703275, 'reg_alpha': 0.0004324908865121173, 'reg_lambda': 3.0095762509818133e-05, 'max_delta_step': 0}. Best is trial 68 with value: 0.6030604288499026.
[I 2025-11-10 19:01:50,402] Trial 91 finished with value: 0.5565497076023391 and parameters: {'max_depth': 7, 'learning_rate': 0.033833355432780314, 'n_estimators': 1162, 'subsample': 0.8674001432291519, 'colsample_bytree': 0.5028250455170129, 'min_child_weight': 1, 'gamma': 3.3282517990803218, 'reg_alpha': 0.00011185971244525378, 'reg_lambda': 2.42357461308274e-05, 'max_delta_step': 0}. Best is trial 68 with value: 0.6030604288499026.

Best trial: 68. Best value: 0.60306:  47%|████▋     | 94/200 [01:32<01:49,  1.03s/it]

[I 2025-11-10 19:01:51,483] Trial 92 finished with value: 0.5720857699805069 and parameters: {'max_depth': 7, 'learning_rate': 0.04721973829462778, 'n_estimators': 1186, 'subsample': 0.8581573743154906, 'colsample_bytree': 0.5041575114358923, 'min_child_weight': 1, 'gamma': 4.405613874982604, 'reg_alpha': 0.00017537210016340107, 'reg_lambda': 2.2268524708045382e-05, 'max_delta_step': 0}. Best is trial 68 with value: 0.6030604288499026.

Best trial: 68. Best value: 0.60306:  48%|████▊     | 95/200 [01:34<02:24,  1.38s/it]

[I 2025-11-10 19:01:53,911] Trial 94 finished with value: 0.5905068226120858 and parameters: {'max_depth': 7, 'learning_rate': 0.03328509576405341, 'n_estimators': 881, 'subsample': 0.876966091931558, 'colsample_bytree': 0.5061566486135446, 'min_child_weight': 1, 'gamma': 4.029011363869056, 'reg_alpha': 0.00014946388717621247, 'reg_lambda': 0.00011303702936201807, 'max_delta_step': 0}. Best is trial 68 with value: 0.6030604288499026.

Best trial: 95. Best value: 0.609669:  48%|████▊     | 97/200 [01:35<01:42,  1.00it/s]

[I 2025-11-10 19:01:55,089] Trial 95 finished with value: 0.6096686159844055 and parameters: {'max_depth': 7, 'learning_rate': 0.034751364382264414, 'n_estimators': 878, 'subsample': 0.8724049146892594, 'colsample_bytree': 0.5540767517034713, 'min_child_weight': 1, 'gamma': 4.077655053339542, 'reg_alpha': 0.00017024367944064523, 'reg_lambda': 0.00010987761636432192, 'max_delta_step': 0}. Best is trial 95 with value: 0.6096686159844055.
[I 2025-11-10 19:01:55,204] Trial 96 finished with value: 0.5748538011695906 and parameters: {'max_depth': 7, 'learning_rate': 0.028972118528216045, 'n_estimators': 827, 'subsample': 0.8223571845431523, 'colsample_bytree': 0.5842176221738274, 'min_child_weight': 1, 'gamma': 4.049459017701576, 'reg_alpha': 0.00015883251220066364, 'reg_lambda': 5.498958811197899e-05, 'max_delta_step': 1}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  49%|████▉     | 98/200 [01:36<01:37,  1.04it/s]

[I 2025-11-10 19:01:56,065] Trial 100 pruned.

Best trial: 95. Best value: 0.609669:  50%|████▉     | 99/200 [01:36<01:15,  1.33it/s]

[I 2025-11-10 19:01:56,298] Trial 97 finished with value: 0.5771539961013645 and parameters: {'max_depth': 7, 'learning_rate': 0.028212767545990704, 'n_estimators': 815, 'subsample': 0.8162325718132802, 'colsample_bytree': 0.5943615145776376, 'min_child_weight': 1, 'gamma': 4.180255552887057, 'reg_alpha': 0.0015721457508749025, 'reg_lambda': 0.00036708636028280704, 'max_delta_step': 1}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  50%|█████     | 100/200 [01:37<01:05,  1.54it/s]

[I 2025-11-10 19:01:56,699] Trial 101 pruned.

Best trial: 95. Best value: 0.609669:  50%|█████     | 101/200 [01:37<00:52,  1.88it/s]

[I 2025-11-10 19:01:56,945] Trial 99 pruned.

Best trial: 95. Best value: 0.609669:  51%|█████     | 102/200 [01:38<00:57,  1.72it/s]

[I 2025-11-10 19:01:57,651] Trial 103 pruned.

Best trial: 95. Best value: 0.609669:  52%|█████▏    | 103/200 [01:39<01:23,  1.16it/s]

[I 2025-11-10 19:01:59,166] Trial 98 finished with value: 0.5742105263157895 and parameters: {'max_depth': 7, 'learning_rate': 0.03768463756212657, 'n_estimators': 879, 'subsample': 0.8023129937452668, 'colsample_bytree': 0.593235097812328, 'min_child_weight': 1, 'gamma': 4.157683153927521, 'reg_alpha': 0.0016722219994942918, 'reg_lambda': 9.819601238610545e-05, 'max_delta_step': 1}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  52%|█████▏    | 104/200 [01:41<01:36,  1.01s/it]

[I 2025-11-10 19:02:00,531] Trial 102 finished with value: 0.5422027290448345 and parameters: {'max_depth': 6, 'learning_rate': 0.05161434896787212, 'n_estimators': 864, 'subsample': 0.876911713852396, 'colsample_bytree': 0.5567413547853761, 'min_child_weight': 2, 'gamma': 4.5299104030526545, 'reg_alpha': 0.0038240441357476253, 'reg_lambda': 8.735655218723497e-06, 'max_delta_step': 0}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  52%|█████▎    | 105/200 [01:41<01:27,  1.08it/s]

[I 2025-11-10 19:02:01,255] Trial 104 finished with value: 0.5915984405458089 and parameters: {'max_depth': 7, 'learning_rate': 0.03968081449119945, 'n_estimators': 763, 'subsample': 0.8712641750348895, 'colsample_bytree': 0.549975034704257, 'min_child_weight': 1, 'gamma': 4.433955027881847, 'reg_alpha': 0.0004107563518372395, 'reg_lambda': 9.262017044293178e-06, 'max_delta_step': 0}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  53%|█████▎    | 106/200 [01:42<01:21,  1.15it/s]

[I 2025-11-10 19:02:01,995] Trial 105 finished with value: 0.5932358674463938 and parameters: {'max_depth': 7, 'learning_rate': 0.038991654556945615, 'n_estimators': 760, 'subsample': 0.8777741012672282, 'colsample_bytree': 0.5612552899131164, 'min_child_weight': 1, 'gamma': 4.55106123021182, 'reg_alpha': 0.0007854903441250889, 'reg_lambda': 1.4068273966718288e-05, 'max_delta_step': 0}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  54%|█████▎    | 107/200 [01:42<01:02,  1.49it/s]

[I 2025-11-10 19:02:02,205] Trial 108 pruned.

Best trial: 95. Best value: 0.609669:  54%|█████▍    | 108/200 [01:44<01:44,  1.13s/it]

[I 2025-11-10 19:02:04,422] Trial 106 finished with value: 0.6045808966861598 and parameters: {'max_depth': 8, 'learning_rate': 0.028037130059778016, 'n_estimators': 946, 'subsample': 0.879292183299653, 'colsample_bytree': 0.5618514646450585, 'min_child_weight': 1, 'gamma': 4.491172404106361, 'reg_alpha': 0.003948281362838792, 'reg_lambda': 1.4284653447353828e-05, 'max_delta_step': 0}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  55%|█████▍    | 109/200 [01:45<01:29,  1.02it/s]

[I 2025-11-10 19:02:05,043] Trial 107 finished with value: 0.5613450292397661 and parameters: {'max_depth': 8, 'learning_rate': 0.03979594381549013, 'n_estimators': 817, 'subsample': 0.738385545617264, 'colsample_bytree': 0.5755276834657167, 'min_child_weight': 1, 'gamma': 3.8489939539655946, 'reg_alpha': 0.0007524313055708573, 'reg_lambda': 4.791570980411604e-05, 'max_delta_step': 0}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  55%|█████▌    | 110/200 [01:46<01:24,  1.06it/s]

[I 2025-11-10 19:02:05,903] Trial 110 finished with value: 0.5819883040935672 and parameters: {'max_depth': 8, 'learning_rate': 0.044180140892032954, 'n_estimators': 687, 'subsample': 0.8718062818173757, 'colsample_bytree': 0.5350392507715647, 'min_child_weight': 1, 'gamma': 4.847130207014431, 'reg_alpha': 5.563885178199152e-05, 'reg_lambda': 1.3781169368182747e-05, 'max_delta_step': 0}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  56%|█████▌    | 111/200 [01:46<01:07,  1.32it/s]

[I 2025-11-10 19:02:06,215] Trial 109 finished with value: 0.5840545808966862 and parameters: {'max_depth': 8, 'learning_rate': 0.04545325051407419, 'n_estimators': 747, 'subsample': 0.8817591137674631, 'colsample_bytree': 0.5648774462229571, 'min_child_weight': 1, 'gamma': 4.789654044406915, 'reg_alpha': 0.000746737907329806, 'reg_lambda': 1.3064519281482959e-05, 'max_delta_step': 0}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  56%|█████▌    | 112/200 [01:48<01:36,  1.09s/it]

[I 2025-11-10 19:02:08,091] Trial 111 finished with value: 0.5810136452241716 and parameters: {'max_depth': 8, 'learning_rate': 0.03575032580836721, 'n_estimators': 672, 'subsample': 0.8735468907543699, 'colsample_bytree': 0.537851620421515, 'min_child_weight': 1, 'gamma': 4.783039753082662, 'reg_alpha': 6.728147186738589e-05, 'reg_lambda': 9.85062311396531e-06, 'max_delta_step': 1}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  57%|█████▋    | 114/200 [01:50<01:14,  1.16it/s]

[I 2025-11-10 19:02:09,412] Trial 113 finished with value: 0.5826315789473684 and parameters: {'max_depth': 8, 'learning_rate': 0.04624865332769009, 'n_estimators': 646, 'subsample': 0.8736179669525707, 'colsample_bytree': 0.5369051600589838, 'min_child_weight': 1, 'gamma': 4.804602746347632, 'reg_alpha': 3.847923555994585e-05, 'reg_lambda': 4.9993815878251415e-06, 'max_delta_step': 1}. Best is trial 95 with value: 0.6096686159844055.
[I 2025-11-10 19:02:09,572] Trial 115 pruned.

Best trial: 95. Best value: 0.609669:  57%|█████▊    | 115/200 [01:50<01:00,  1.41it/s]

[I 2025-11-10 19:02:09,937] Trial 114 finished with value: 0.5883040935672514 and parameters: {'max_depth': 8, 'learning_rate': 0.05003252718572155, 'n_estimators': 671, 'subsample': 0.8741518890662285, 'colsample_bytree': 0.5395503035345246, 'min_child_weight': 1, 'gamma': 4.722585400290155, 'reg_alpha': 3.9075706640837934e-05, 'reg_lambda': 1.1884223666520252e-05, 'max_delta_step': 0}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  58%|█████▊    | 116/200 [01:50<00:47,  1.79it/s]

[I 2025-11-10 19:02:10,144] Trial 112 finished with value: 0.5812475633528266 and parameters: {'max_depth': 8, 'learning_rate': 0.04490977169631016, 'n_estimators': 944, 'subsample': 0.8764234471535037, 'colsample_bytree': 0.5192267905648809, 'min_child_weight': 1, 'gamma': 4.784926189206741, 'reg_alpha': 5.9431718928753715e-05, 'reg_lambda': 4.5511013709992685e-06, 'max_delta_step': 1}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  58%|█████▊    | 117/200 [01:51<00:50,  1.65it/s]

[I 2025-11-10 19:02:10,852] Trial 118 pruned.

Best trial: 95. Best value: 0.609669:  59%|█████▉    | 118/200 [01:51<00:48,  1.69it/s]

[I 2025-11-10 19:02:11,419] Trial 119 pruned.

Best trial: 95. Best value: 0.609669:  60%|█████▉    | 119/200 [01:52<00:54,  1.49it/s]

[I 2025-11-10 19:02:12,268] Trial 121 pruned.

Best trial: 95. Best value: 0.609669:  60%|██████    | 120/200 [01:53<00:59,  1.34it/s]

[I 2025-11-10 19:02:13,196] Trial 116 finished with value: 0.6042300194931775 and parameters: {'max_depth': 9, 'learning_rate': 0.049989459708483064, 'n_estimators': 624, 'subsample': 0.850730732301787, 'colsample_bytree': 0.5618846977805115, 'min_child_weight': 1, 'gamma': 4.495203015979683, 'reg_alpha': 0.000283007829625516, 'reg_lambda': 3.22095702429284e-06, 'max_delta_step': 0}. Best is trial 95 with value: 0.6096686159844055.
[I 2025-11-10 19:02:13,238] Trial 117 finished with value: 0.5733333333333333 and parameters: {'max_depth': 9, 'learning_rate': 0.049540352095223006, 'n_estimators': 616, 'subsample': 0.8322982556740344, 'colsample_bytree': 0.5632778965793652, 'min_child_weight': 1, 'gamma': 4.700266221643735, 'reg_alpha': 2.756239861913398e-05, 'reg_lambda': 4.472411231118071e-06, 'max_delta_step': 1}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  61%|██████    | 122/200 [01:54<00:47,  1.66it/s]

[I 2025-11-10 19:02:14,072] Trial 120 finished with value: 0.5669590643274854 and parameters: {'max_depth': 9, 'learning_rate': 0.05403337158796933, 'n_estimators': 603, 'subsample': 0.8538621777924265, 'colsample_bytree': 0.5596319211115629, 'min_child_weight': 2, 'gamma': 4.921833994410317, 'reg_alpha': 1.637068837723444e-05, 'reg_lambda': 2.107884623265451e-06, 'max_delta_step': 0}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  62%|██████▏   | 124/200 [01:57<01:02,  1.22it/s]

[I 2025-11-10 19:02:16,535] Trial 122 finished with value: 0.5767056530214425 and parameters: {'max_depth': 7, 'learning_rate': 0.052840653259730384, 'n_estimators': 775, 'subsample': 0.8501462209935695, 'colsample_bytree': 0.5766429562299807, 'min_child_weight': 1, 'gamma': 4.551226192880674, 'reg_alpha': 0.0003319938275387305, 'reg_lambda': 4.385893537139718e-05, 'max_delta_step': 1}. Best is trial 95 with value: 0.6096686159844055.
[I 2025-11-10 19:02:16,667] Trial 123 finished with value: 0.5928265107212476 and parameters: {'max_depth': 7, 'learning_rate': 0.05073408460134931, 'n_estimators': 606, 'subsample': 0.8504651234536351, 'colsample_bytree': 0.5810870464170035, 'min_child_weight': 1, 'gamma': 4.280652963137892, 'reg_alpha': 0.0002940972794839298, 'reg_lambda': 7.272629310893404e-06, 'max_delta_step': 0}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  62%|██████▎   | 125/200 [01:57<00:52,  1.43it/s]

[I 2025-11-10 19:02:17,047] Trial 125 finished with value: 0.582943469785575 and parameters: {'max_depth': 10, 'learning_rate': 0.06725327804067986, 'n_estimators': 551, 'subsample': 0.9052768109114908, 'colsample_bytree': 0.5151138966476205, 'min_child_weight': 1, 'gamma': 4.568932995864142, 'reg_alpha': 0.00024496266573083845, 'reg_lambda': 3.3174694266634306e-05, 'max_delta_step': 0}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  63%|██████▎   | 126/200 [01:58<00:50,  1.46it/s]

[I 2025-11-10 19:02:17,693] Trial 124 finished with value: 0.5741910331384016 and parameters: {'max_depth': 10, 'learning_rate': 0.033241172248180115, 'n_estimators': 788, 'subsample': 0.851818251846335, 'colsample_bytree': 0.5754705489679429, 'min_child_weight': 1, 'gamma': 4.549307215589599, 'reg_alpha': 0.0010543632666039947, 'reg_lambda': 3.991597584324125e-05, 'max_delta_step': 0}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  64%|██████▎   | 127/200 [01:59<00:52,  1.40it/s]

[I 2025-11-10 19:02:18,472] Trial 129 pruned.

Best trial: 95. Best value: 0.609669:  64%|██████▍   | 128/200 [01:59<00:50,  1.42it/s]

[I 2025-11-10 19:02:19,155] Trial 130 pruned.

Best trial: 95. Best value: 0.609669:  64%|██████▍   | 129/200 [02:00<00:47,  1.51it/s]

[I 2025-11-10 19:02:19,725] Trial 127 finished with value: 0.5707407407407408 and parameters: {'max_depth': 10, 'learning_rate': 0.06553305598964891, 'n_estimators': 534, 'subsample': 0.9097171928648017, 'colsample_bytree': 0.5492433560572166, 'min_child_weight': 1, 'gamma': 4.440341165373548, 'reg_alpha': 0.00025760518762577977, 'reg_lambda': 6.686397222455352e-06, 'max_delta_step': 0}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 95. Best value: 0.609669:  65%|██████▌   | 130/200 [02:00<00:37,  1.89it/s]

[I 2025-11-10 19:02:19,928] Trial 126 finished with value: 0.5993762183235868 and parameters: {'max_depth': 7, 'learning_rate': 0.032428349378941686, 'n_estimators': 559, 'subsample': 0.9093438380878904, 'colsample_bytree': 0.551646844482062, 'min_child_weight': 1, 'gamma': 4.383854450070703, 'reg_alpha': 0.00023086728828194708, 'reg_lambda': 7.125115017120664e-06, 'max_delta_step': 0}. Best is trial 95 with value: 0.6096686159844055.

Best trial: 128. Best value: 0.613236:  66%|██████▌   | 131/200 [02:01<00:36,  1.87it/s]

[I 2025-11-10 19:02:20,478] Trial 128 finished with value: 0.6132358674463938 and parameters: {'max_depth': 7, 'learning_rate': 0.03303217086763754, 'n_estimators': 546, 'subsample': 0.864824455883988, 'colsample_bytree': 0.5833346450134411, 'min_child_weight': 1, 'gamma': 4.42849544892163, 'reg_alpha': 8.782974507090378e-05, 'reg_lambda': 7.1523448565567135e-06, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 128. Best value: 0.613236:  66%|██████▌   | 132/200 [02:01<00:30,  2.23it/s]

[I 2025-11-10 19:02:20,721] Trial 132 pruned.

Best trial: 128. Best value: 0.613236:  66%|██████▋   | 133/200 [02:02<00:45,  1.46it/s]

[I 2025-11-10 19:02:21,959] Trial 133 pruned.

Best trial: 128. Best value: 0.613236:  67%|██████▋   | 134/200 [02:03<01:00,  1.09it/s]

[I 2025-11-10 19:02:23,436] Trial 131 finished with value: 0.5927290448343079 and parameters: {'max_depth': 7, 'learning_rate': 0.03609629710496011, 'n_estimators': 734, 'subsample': 0.8640146924697577, 'colsample_bytree': 0.5263167453598618, 'min_child_weight': 1, 'gamma': 4.000409954022475, 'reg_alpha': 0.00021152655134277677, 'reg_lambda': 0.00015898918102560274, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 128. Best value: 0.613236:  68%|██████▊   | 136/200 [02:04<00:35,  1.80it/s]

[I 2025-11-10 19:02:23,721] Trial 134 finished with value: 0.6114814814814815 and parameters: {'max_depth': 7, 'learning_rate': 0.03593238321035722, 'n_estimators': 509, 'subsample': 0.8657116064889674, 'colsample_bytree': 0.6070243510968985, 'min_child_weight': 1, 'gamma': 4.361488565357703, 'reg_alpha': 3.5634876056645526e-05, 'reg_lambda': 7.789421206945324e-07, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.
[I 2025-11-10 19:02:23,871] Trial 135 finished with value: 0.6005068226120858 and parameters: {'max_depth': 7, 'learning_rate': 0.030361929714982642, 'n_estimators': 504, 'subsample': 0.9325482711887046, 'colsample_bytree': 0.5852908194954516, 'min_child_weight': 1, 'gamma': 4.258157341891439, 'reg_alpha': 0.00012791911083076229, 'reg_lambda': 3.651966746111523e-07, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 128. Best value: 0.613236:  68%|██████▊   | 137/200 [02:04<00:32,  1.92it/s]

[I 2025-11-10 19:02:24,308] Trial 137 pruned.

Best trial: 128. Best value: 0.613236:  69%|██████▉   | 138/200 [02:05<00:37,  1.65it/s]

[I 2025-11-10 19:02:25,114] Trial 139 pruned.

Best trial: 128. Best value: 0.613236:  70%|███████   | 140/200 [02:06<00:26,  2.25it/s]

[I 2025-11-10 19:02:25,627] Trial 140 pruned.
[I 2025-11-10 19:02:25,755] Trial 141 pruned.

[I 2025-11-10 19:02:26,014] Trial 136 finished with value: 0.600233918128655 and parameters: {'max_depth': 7, 'learning_rate': 0.03061298503396724, 'n_estimators': 663, 'subsample': 0.9315109499729773, 'colsample_bytree': 0.5778538037649623, 'min_child_weight': 1, 'gamma': 4.477300549747697, 'reg_alpha': 3.6859232073853265e-05, 'reg_lambda': 9.612450231155073e-06, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 128. Best value: 0.613236:  71%|███████   | 142/200 [02:06<00:18,  3.08it/s]

[I 2025-11-10 19:02:26,192] Trial 142 pruned.

Best trial: 128. Best value: 0.613236:  72%|███████▏  | 143/200 [02:07<00:20,  2.81it/s]

[I 2025-11-10 19:02:26,619] Trial 143 pruned.

Best trial: 128. Best value: 0.613236:  72%|███████▎  | 145/200 [02:07<00:15,  3.58it/s]

[I 2025-11-10 19:02:26,866] Trial 144 pruned.
[I 2025-11-10 19:02:27,044] Trial 145 pruned.

Best trial: 128. Best value: 0.613236:  73%|███████▎  | 146/200 [02:08<00:18,  2.89it/s]

[I 2025-11-10 19:02:27,541] Trial 138 finished with value: 0.5977582846003898 and parameters: {'max_depth': 7, 'learning_rate': 0.039457627384263595, 'n_estimators': 556, 'subsample': 0.8952629241265446, 'colsample_bytree': 0.5834199799379852, 'min_child_weight': 1, 'gamma': 2.6667340983542225, 'reg_alpha': 8.866122127622796e-06, 'reg_lambda': 3.432176595041281e-07, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.
[I 2025-11-10 19:02:27,553] Trial 147 pruned.

Best trial: 128. Best value: 0.613236:  74%|███████▍  | 148/200 [02:10<00:36,  1.44it/s]

[I 2025-11-10 19:02:29,752] Trial 148 finished with value: 0.582962962962963 and parameters: {'max_depth': 7, 'learning_rate': 0.03214957283040666, 'n_estimators': 458, 'subsample': 0.9205503042163707, 'colsample_bytree': 0.5464177202215315, 'min_child_weight': 1, 'gamma': 4.388604200206951, 'reg_alpha': 0.00020532659766739223, 'reg_lambda': 8.036144962538486e-07, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 128. Best value: 0.613236:  74%|███████▍  | 149/200 [02:10<00:31,  1.60it/s]

[I 2025-11-10 19:02:30,173] Trial 149 finished with value: 0.5827095516569201 and parameters: {'max_depth': 7, 'learning_rate': 0.04127987135878281, 'n_estimators': 408, 'subsample': 0.9242853609005993, 'colsample_bytree': 0.5522843078843954, 'min_child_weight': 1, 'gamma': 2.3981952765726615, 'reg_alpha': 6.3182081425475e-06, 'reg_lambda': 6.198502472712186e-07, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.
[I 2025-11-10 19:02:30,187] Trial 146 finished with value: 0.5834502923976608 and parameters: {'max_depth': 7, 'learning_rate': 0.03623253479536071, 'n_estimators': 586, 'subsample': 0.8641030913506831, 'colsample_bytree': 0.5710030809399118, 'min_child_weight': 1, 'gamma': 4.476142442452735, 'reg_alpha': 0.00016928921792593003, 'reg_lambda': 6.823329256919719e-07, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 128. Best value: 0.613236:  76%|███████▌  | 151/200 [02:11<00:21,  2.33it/s]

[I 2025-11-10 19:02:30,472] Trial 151 pruned.

Best trial: 128. Best value: 0.613236:  76%|███████▋  | 153/200 [02:11<00:16,  2.78it/s]

[I 2025-11-10 19:02:30,880] Trial 152 pruned.
[I 2025-11-10 19:02:31,041] Trial 153 pruned.
[I 2025-11-10 19:02:31,063] Trial 150 finished with value: 0.5934502923976608 and parameters: {'max_depth': 7, 'learning_rate': 0.04184604988361887, 'n_estimators': 552, 'subsample': 0.923733339647909, 'colsample_bytree': 0.5515385838671499, 'min_child_weight': 1, 'gamma': 2.097965772793638, 'reg_alpha': 0.000576955927492536, 'reg_lambda': 7.078958139700801e-07, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 128. Best value: 0.613236:  78%|███████▊  | 155/200 [02:11<00:12,  3.52it/s]

[I 2025-11-10 19:02:31,394] Trial 154 pruned.

Best trial: 128. Best value: 0.613236:  78%|███████▊  | 156/200 [02:12<00:14,  2.97it/s]

[I 2025-11-10 19:02:31,903] Trial 156 pruned.

Best trial: 128. Best value: 0.613236:  78%|███████▊  | 157/200 [02:13<00:18,  2.36it/s]

[I 2025-11-10 19:02:32,603] Trial 159 pruned.

Best trial: 128. Best value: 0.613236:  79%|███████▉  | 158/200 [02:13<00:22,  1.86it/s]

[I 2025-11-10 19:02:33,460] Trial 160 pruned.

Best trial: 128. Best value: 0.613236:  80%|███████▉  | 159/200 [02:15<00:27,  1.50it/s]

[I 2025-11-10 19:02:34,479] Trial 158 finished with value: 0.578888888888889 and parameters: {'max_depth': 7, 'learning_rate': 0.04600346546455441, 'n_estimators': 479, 'subsample': 0.8928493710629886, 'colsample_bytree': 0.5573306571361224, 'min_child_weight': 1, 'gamma': 1.8163811575712003, 'reg_alpha': 0.0031567105448004917, 'reg_lambda': 1.2142946366847846e-08, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 128. Best value: 0.613236:  80%|████████  | 160/200 [02:15<00:24,  1.65it/s]

[I 2025-11-10 19:02:34,926] Trial 155 finished with value: 0.5745808966861599 and parameters: {'max_depth': 7, 'learning_rate': 0.034529978804197385, 'n_estimators': 628, 'subsample': 0.8905766055670825, 'colsample_bytree': 0.5260131721459927, 'min_child_weight': 1, 'gamma': 2.0176593562801157, 'reg_alpha': 7.51497373833691e-05, 'reg_lambda': 7.160357171580236e-08, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.
[I 2025-11-10 19:02:34,935] Trial 157 finished with value: 0.5733333333333333 and parameters: {'max_depth': 7, 'learning_rate': 0.047490798401067444, 'n_estimators': 631, 'subsample': 0.8909025861936603, 'colsample_bytree': 0.5532109820024513, 'min_child_weight': 1, 'gamma': 2.068072273268273, 'reg_alpha': 0.002795080733139564, 'reg_lambda': 5.7464389502132274e-08, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 128. Best value: 0.613236:  81%|████████  | 162/200 [02:16<00:21,  1.74it/s]

[I 2025-11-10 19:02:36,004] Trial 164 pruned.

Best trial: 128. Best value: 0.613236:  82%|████████▏ | 163/200 [02:17<00:23,  1.57it/s]

[I 2025-11-10 19:02:36,840] Trial 161 finished with value: 0.5856725146198831 and parameters: {'max_depth': 7, 'learning_rate': 0.03867523785487584, 'n_estimators': 506, 'subsample': 0.8917264663833909, 'colsample_bytree': 0.56677828612587, 'min_child_weight': 1, 'gamma': 2.015119503050503, 'reg_alpha': 0.0004284890150194612, 'reg_lambda': 2.424756429307263e-05, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 128. Best value: 0.613236:  82%|████████▏ | 164/200 [02:19<00:32,  1.11it/s]

[I 2025-11-10 19:02:38,501] Trial 162 finished with value: 0.5775438596491228 and parameters: {'max_depth': 8, 'learning_rate': 0.03964945313444574, 'n_estimators': 645, 'subsample': 0.8268892548519156, 'colsample_bytree': 0.588350908178599, 'min_child_weight': 1, 'gamma': 1.9609474128431112, 'reg_alpha': 0.0003020898871519372, 'reg_lambda': 1.4018260340867216e-07, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 128. Best value: 0.613236:  82%|████████▎ | 165/200 [02:19<00:27,  1.29it/s]

[I 2025-11-10 19:02:38,942] Trial 165 finished with value: 0.591598440545809 and parameters: {'max_depth': 7, 'learning_rate': 0.05794206643220061, 'n_estimators': 510, 'subsample': 0.8798610737629791, 'colsample_bytree': 0.5681596782546154, 'min_child_weight': 1, 'gamma': 4.2411132856803215, 'reg_alpha': 0.00046581184186736207, 'reg_lambda': 1.5008474758307656e-07, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 128. Best value: 0.613236:  83%|████████▎ | 166/200 [02:20<00:29,  1.14it/s]

[I 2025-11-10 19:02:40,083] Trial 163 finished with value: 0.5846978557504873 and parameters: {'max_depth': 7, 'learning_rate': 0.03167369122025232, 'n_estimators': 906, 'subsample': 0.8533358398056218, 'colsample_bytree': 0.5701192568600636, 'min_child_weight': 1, 'gamma': 3.960643341620376, 'reg_alpha': 0.00027696940624396074, 'reg_lambda': 2.28170925362488e-05, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 128. Best value: 0.613236:  84%|████████▎ | 167/200 [02:21<00:24,  1.35it/s]

[I 2025-11-10 19:02:40,474] Trial 166 finished with value: 0.5965497076023392 and parameters: {'max_depth': 7, 'learning_rate': 0.032360969293048894, 'n_estimators': 596, 'subsample': 0.8743159665614351, 'colsample_bytree': 0.5928773559829467, 'min_child_weight': 1, 'gamma': 4.21679920218316, 'reg_alpha': 0.00027061941331075047, 'reg_lambda': 1.3120698439447477e-07, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 128. Best value: 0.613236:  84%|████████▍ | 168/200 [02:22<00:30,  1.05it/s]

[I 2025-11-10 19:02:41,966] Trial 167 finished with value: 0.6005263157894737 and parameters: {'max_depth': 7, 'learning_rate': 0.03154851640381573, 'n_estimators': 590, 'subsample': 0.8764247224484798, 'colsample_bytree': 0.5725608034434831, 'min_child_weight': 1, 'gamma': 4.240141945172616, 'reg_alpha': 5.697463036492473e-07, 'reg_lambda': 0.00021192009348185224, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 128. Best value: 0.613236:  85%|████████▌ | 170/200 [02:23<00:18,  1.64it/s]

[I 2025-11-10 19:02:42,372] Trial 168 finished with value: 0.5933333333333334 and parameters: {'max_depth': 6, 'learning_rate': 0.043704095008796164, 'n_estimators': 587, 'subsample': 0.8754802436382068, 'colsample_bytree': 0.567761159708521, 'min_child_weight': 1, 'gamma': 4.253268889327478, 'reg_alpha': 0.0009895474046881228, 'reg_lambda': 1.1412621646220656e-06, 'max_delta_step': 8}. Best is trial 128 with value: 0.6132358674463938.
[I 2025-11-10 19:02:42,535] Trial 171 pruned.

Best trial: 128. Best value: 0.613236:  86%|████████▌ | 171/200 [02:23<00:15,  1.83it/s]

[I 2025-11-10 19:02:42,935] Trial 172 pruned.

Best trial: 128. Best value: 0.613236:  86%|████████▌ | 172/200 [02:24<00:17,  1.61it/s]

[I 2025-11-10 19:02:43,732] Trial 169 finished with value: 0.5692592592592594 and parameters: {'max_depth': 6, 'learning_rate': 0.05777992058182062, 'n_estimators': 595, 'subsample': 0.8725958457121276, 'colsample_bytree': 0.591482044397345, 'min_child_weight': 1, 'gamma': 4.254300364148637, 'reg_alpha': 0.0010871011062211949, 'reg_lambda': 9.472939699954855e-07, 'max_delta_step': 1}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 128. Best value: 0.613236:  86%|████████▋ | 173/200 [02:24<00:13,  1.95it/s]

[I 2025-11-10 19:02:43,989] Trial 170 finished with value: 0.5750682261208577 and parameters: {'max_depth': 6, 'learning_rate': 0.057804209629870845, 'n_estimators': 589, 'subsample': 0.907124663988321, 'colsample_bytree': 0.5933480317913746, 'min_child_weight': 1, 'gamma': 4.256116497876303, 'reg_alpha': 1.0809608399120741e-05, 'reg_lambda': 4.765042716862014e-07, 'max_delta_step': 1}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 128. Best value: 0.613236:  88%|████████▊ | 175/200 [02:26<00:18,  1.34it/s]

[I 2025-11-10 19:02:46,119] Trial 173 finished with value: 0.5828654970760233 and parameters: {'max_depth': 6, 'learning_rate': 0.024521793504567888, 'n_estimators': 573, 'subsample': 0.9147428549235808, 'colsample_bytree': 0.5909076186248386, 'min_child_weight': 1, 'gamma': 4.29548090331418, 'reg_alpha': 6.085365633334439e-07, 'reg_lambda': 9.434063283979954e-07, 'max_delta_step': 1}. Best is trial 128 with value: 0.6132358674463938.
[I 2025-11-10 19:02:46,275] Trial 174 finished with value: 0.5972709551656921 and parameters: {'max_depth': 7, 'learning_rate': 0.033287643796745946, 'n_estimators': 561, 'subsample': 0.8688656115859625, 'colsample_bytree': 0.5793426516750692, 'min_child_weight': 1, 'gamma': 4.1809271929520255, 'reg_alpha': 0.0010274128672040455, 'reg_lambda': 5.164498918491138e-07, 'max_delta_step': 7}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 128. Best value: 0.613236:  88%|████████▊ | 177/200 [02:27<00:12,  1.79it/s]

[I 2025-11-10 19:02:47,018] Trial 178 pruned.
[I 2025-11-10 19:02:47,140] Trial 175 finished with value: 0.5892592592592593 and parameters: {'max_depth': 7, 'learning_rate': 0.0348892190866011, 'n_estimators': 562, 'subsample': 0.8627335067097325, 'colsample_bytree': 0.5784604849072789, 'min_child_weight': 1, 'gamma': 4.1329195689494425, 'reg_alpha': 0.0005928649709096423, 'reg_lambda': 5.015885642307355e-07, 'max_delta_step': 0}. Best is trial 128 with value: 0.6132358674463938.

Best trial: 176. Best value: 0.61423:  89%|████████▉ | 178/200 [02:27<00:09,  2.29it/s]

[I 2025-11-10 19:02:47,294] Trial 176 finished with value: 0.6142300194931775 and parameters: {'max_depth': 7, 'learning_rate': 0.03413917095810269, 'n_estimators': 560, 'subsample': 0.8617132592317515, 'colsample_bytree': 0.5767111154084688, 'min_child_weight': 1, 'gamma': 4.110875172848443, 'reg_alpha': 7.624765749324457e-07, 'reg_lambda': 0.00027375956820040805, 'max_delta_step': 7}. Best is trial 176 with value: 0.6142300194931775.

Best trial: 176. Best value: 0.61423:  90%|████████▉ | 179/200 [02:28<00:10,  1.92it/s]

[I 2025-11-10 19:02:48,009] Trial 181 pruned.

Best trial: 176. Best value: 0.61423:  90%|█████████ | 180/200 [02:29<00:11,  1.78it/s]

[I 2025-11-10 19:02:48,672] Trial 182 pruned.

Best trial: 176. Best value: 0.61423:  90%|█████████ | 181/200 [02:30<00:12,  1.49it/s]

[I 2025-11-10 19:02:49,598] Trial 177 finished with value: 0.5941910331384015 and parameters: {'max_depth': 7, 'learning_rate': 0.03260963836040001, 'n_estimators': 552, 'subsample': 0.8382191750249536, 'colsample_bytree': 0.5800177221595406, 'min_child_weight': 1, 'gamma': 4.120964263055234, 'reg_alpha': 0.0006528182764437364, 'reg_lambda': 2.2228883187448195e-06, 'max_delta_step': 7}. Best is trial 176 with value: 0.6142300194931775.

Best trial: 176. Best value: 0.61423:  91%|█████████ | 182/200 [02:30<00:12,  1.45it/s]

[I 2025-11-10 19:02:50,333] Trial 184 pruned.

Best trial: 176. Best value: 0.61423:  92%|█████████▏| 183/200 [02:31<00:09,  1.78it/s]

[I 2025-11-10 19:02:50,593] Trial 180 finished with value: 0.5902534113060429 and parameters: {'max_depth': 7, 'learning_rate': 0.026721016461395422, 'n_estimators': 552, 'subsample': 0.9459642735532205, 'colsample_bytree': 0.5594298983294386, 'min_child_weight': 1, 'gamma': 4.548801539349373, 'reg_alpha': 0.001103592379993304, 'reg_lambda': 3.1710198563046894e-06, 'max_delta_step': 9}. Best is trial 176 with value: 0.6142300194931775.
[I 2025-11-10 19:02:50,685] Trial 179 finished with value: 0.5853021442495127 and parameters: {'max_depth': 7, 'learning_rate': 0.027039424365255815, 'n_estimators': 561, 'subsample': 0.9457448485026139, 'colsample_bytree': 0.5788561515431679, 'min_child_weight': 1, 'gamma': 4.098600267848869, 'reg_alpha': 0.0008182674550382584, 'reg_lambda': 2.6167935062144273e-06, 'max_delta_step': 9}. Best is trial 176 with value: 0.6142300194931775.

Best trial: 176. Best value: 0.61423:  93%|█████████▎| 186/200 [02:31<00:05,  2.71it/s]

[I 2025-11-10 19:02:51,170] Trial 185 pruned.
[I 2025-11-10 19:02:51,335] Trial 187 pruned.

Best trial: 176. Best value: 0.61423:  94%|█████████▎| 187/200 [02:32<00:04,  3.20it/s]

[I 2025-11-10 19:02:51,489] Trial 186 pruned.

Best trial: 176. Best value: 0.61423:  94%|█████████▍| 188/200 [02:32<00:03,  3.04it/s]

[I 2025-11-10 19:02:51,864] Trial 188 pruned.

Best trial: 176. Best value: 0.61423:  94%|█████████▍| 189/200 [02:33<00:05,  2.10it/s]

[I 2025-11-10 19:02:52,721] Trial 183 finished with value: 0.5946978557504873 and parameters: {'max_depth': 7, 'learning_rate': 0.03155298581452153, 'n_estimators': 549, 'subsample': 0.9257499389620081, 'colsample_bytree': 0.7851395142774251, 'min_child_weight': 1, 'gamma': 4.554854902290437, 'reg_alpha': 7.152105336040182e-07, 'reg_lambda': 0.0002681341779802088, 'max_delta_step': 7}. Best is trial 176 with value: 0.6142300194931775.

Best trial: 176. Best value: 0.61423:  95%|█████████▌| 190/200 [02:34<00:06,  1.45it/s]

[I 2025-11-10 19:02:53,952] Trial 192 pruned.

Best trial: 176. Best value: 0.61423:  96%|█████████▌| 191/200 [02:35<00:06,  1.42it/s]

[I 2025-11-10 19:02:54,689] Trial 193 pruned.

Best trial: 176. Best value: 0.61423:  96%|█████████▌| 192/200 [02:35<00:05,  1.41it/s]

[I 2025-11-10 19:02:55,413] Trial 189 finished with value: 0.5848148148148147 and parameters: {'max_depth': 7, 'learning_rate': 0.0318369660110389, 'n_estimators': 656, 'subsample': 0.8699015023053946, 'colsample_bytree': 0.6110284320556498, 'min_child_weight': 1, 'gamma': 3.0154198219314603, 'reg_alpha': 8.584241435703715e-07, 'reg_lambda': 7.283625064747304e-07, 'max_delta_step': 7}. Best is trial 176 with value: 0.6142300194931775.

Best trial: 176. Best value: 0.61423:  96%|█████████▋| 193/200 [02:36<00:04,  1.65it/s]

[I 2025-11-10 19:02:55,774] Trial 191 finished with value: 0.5956725146198831 and parameters: {'max_depth': 7, 'learning_rate': 0.03133667291278972, 'n_estimators': 655, 'subsample': 0.9246505037172487, 'colsample_bytree': 0.5580786002669935, 'min_child_weight': 1, 'gamma': 2.870382846935243, 'reg_alpha': 0.010992781885555705, 'reg_lambda': 5.1428802397216495e-06, 'max_delta_step': 7}. Best is trial 176 with value: 0.6142300194931775.

Best trial: 176. Best value: 0.61423:  97%|█████████▋| 194/200 [02:37<00:04,  1.27it/s]

[I 2025-11-10 19:02:56,986] Trial 196 pruned.

Best trial: 176. Best value: 0.61423:  98%|█████████▊| 195/200 [02:38<00:03,  1.43it/s]

[I 2025-11-10 19:02:57,477] Trial 190 finished with value: 0.5807407407407407 and parameters: {'max_depth': 7, 'learning_rate': 0.03048330750940827, 'n_estimators': 1024, 'subsample': 0.8574003173826286, 'colsample_bytree': 0.6090262679782485, 'min_child_weight': 1, 'gamma': 4.47818103873482, 'reg_alpha': 0.002205059773636885, 'reg_lambda': 4.223347449381618e-06, 'max_delta_step': 6}. Best is trial 176 with value: 0.6142300194931775.

Best trial: 176. Best value: 0.61423:  98%|█████████▊| 197/200 [02:38<00:01,  2.03it/s]

[I 2025-11-10 19:02:57,965] Trial 197 pruned.
[I 2025-11-10 19:02:58,126] Trial 194 finished with value: 0.5930994152046785 and parameters: {'max_depth': 7, 'learning_rate': 0.04186508590212442, 'n_estimators': 610, 'subsample': 0.8581895903051334, 'colsample_bytree': 0.5445342961978434, 'min_child_weight': 1, 'gamma': 4.637522166653577, 'reg_alpha': 8.547450308105167e-08, 'reg_lambda': 6.672415353081454e-07, 'max_delta_step': 7}. Best is trial 176 with value: 0.6142300194931775.

Best trial: 176. Best value: 0.61423:  99%|█████████▉| 198/200 [02:38<00:00,  2.42it/s]

[I 2025-11-10 19:02:58,350] Trial 198 pruned.

Best trial: 176. Best value: 0.61423: 100%|█████████▉| 199/200 [02:39<00:00,  1.86it/s]

[I 2025-11-10 19:02:59,178] Trial 195 finished with value: 0.5855750487329435 and parameters: {'max_depth': 7, 'learning_rate': 0.041121026989764844, 'n_estimators': 611, 'subsample': 0.8571263908877825, 'colsample_bytree': 0.7594129187390621, 'min_child_weight': 1, 'gamma': 4.637346249490595, 'reg_alpha': 1.1901450220341756e-07, 'reg_lambda': 8.100425010861222e-05, 'max_delta_step': 8}. Best is trial 176 with value: 0.6142300194931775.

Best trial: 176. Best value: 0.61423: 100%|██████████| 200/200 [02:41<00:00,  1.24it/s]

[I 2025-11-10 19:03:00,576] Trial 199 finished with value: 0.6019883040935673 and parameters: {'max_depth': 7, 'learning_rate': 0.03294682327277205, 'n_estimators': 601, 'subsample': 0.9292335859815917, 'colsample_bytree': 0.5442654787726128, 'min_child_weight': 1, 'gamma': 2.812260870359061, 'reg_alpha': 1.6678345250778382e-06, 'reg_lambda': 0.0004497016954218402, 'max_delta_step': 7}. Best is trial 176 with value: 0.6142300194931775.

C:\Users\tenNovy\AppData\Local\Temp\ipykernel_11656\1094786132.py:137: RuntimeWarning:

More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`). Consider using `matplotlib.pyplot.close()`.

[I 2025-11-10 19:03:01,518] A new study created in memory with name: 18_1_roc_auc
Best trial: 2. Best value: 0.5:   0%|          | 1/200 [00:03<10:14,  3.09s/it]

[I 2025-11-10 19:03:04,599] Trial 2 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.04632456239238506, 'n_estimators': 726, 'subsample': 0.6018867908724403, 'colsample_bytree': 0.8535283818085244, 'min_child_weight': 3, 'gamma': 4.84578020425037, 'reg_alpha': 2.159564456175781, 'reg_lambda': 4.1796499561076904e-05, 'max_delta_step': 0}. Best is trial 2 with value: 0.5.
[I 2025-11-10 19:03:04,783] Trial 0 finished with value: 0.6128654970760234 and parameters: {'max_depth': 4, 'learning_rate': 0.16717015868952212, 'n_estimators': 642, 'subsample': 0.9592806862654095, 'colsample_bytree': 0.598670194900193, 'min_child_weight': 2, 'gamma': 2.027789485262539, 'reg_alpha': 2.4504682925502697, 'reg_lambda': 1.6462762446636794e-06, 'max_delta_step': 4}. Best is trial 0 with value: 0.6128654970760234.

Best trial: 0. Best value: 0.612865:   2%|▏         | 3/200 [00:04<03:36,  1.10s/it]

[I 2025-11-10 19:03:05,550] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.017552862079010325, 'n_estimators': 1100, 'subsample': 0.640129303144553, 'colsample_bytree': 0.6748439337148637, 'min_child_weight': 10, 'gamma': 2.5529587037360555, 'reg_alpha': 0.014248705314150484, 'reg_lambda': 2.3390119646087994e-05, 'max_delta_step': 2}. Best is trial 0 with value: 0.6128654970760234.

Best trial: 0. Best value: 0.612865:   2%|▏         | 4/200 [00:05<04:30,  1.38s/it]

[I 2025-11-10 19:03:07,370] Trial 3 finished with value: 0.5957894736842105 and parameters: {'max_depth': 3, 'learning_rate': 0.030971248939722026, 'n_estimators': 1342, 'subsample': 0.6048829712098973, 'colsample_bytree': 0.9418225388178001, 'min_child_weight': 3, 'gamma': 2.1543200439083288, 'reg_alpha': 0.0025334868381723975, 'reg_lambda': 0.09908716929353673, 'max_delta_step': 0}. Best is trial 0 with value: 0.6128654970760234.

Best trial: 0. Best value: 0.612865:   2%|▎         | 5/200 [00:07<04:24,  1.36s/it]

[I 2025-11-10 19:03:08,688] Trial 7 finished with value: 0.5964912280701755 and parameters: {'max_depth': 7, 'learning_rate': 0.10980373581349662, 'n_estimators': 341, 'subsample': 0.61441629565316, 'colsample_bytree': 0.5295735373051881, 'min_child_weight': 4, 'gamma': 2.8414770529965647, 'reg_alpha': 0.3459760739962829, 'reg_lambda': 0.020997727181606782, 'max_delta_step': 7}. Best is trial 0 with value: 0.6128654970760234.

Best trial: 0. Best value: 0.612865:   3%|▎         | 6/200 [00:08<04:12,  1.30s/it]

[I 2025-11-10 19:03:09,871] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.07211071516137081, 'n_estimators': 1320, 'subsample': 0.6969615460642409, 'colsample_bytree': 0.7572624104367428, 'min_child_weight': 8, 'gamma': 1.1575452533239665, 'reg_alpha': 4.5738741016802944e-07, 'reg_lambda': 5.457158834707549e-05, 'max_delta_step': 1}. Best is trial 0 with value: 0.6128654970760234.

Best trial: 0. Best value: 0.612865:   4%|▎         | 7/200 [00:08<03:19,  1.04s/it]

[I 2025-11-10 19:03:10,362] Trial 8 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.013226926542752369, 'n_estimators': 420, 'subsample': 0.800498932702455, 'colsample_bytree': 0.8432995768873193, 'min_child_weight': 8, 'gamma': 3.0282965825408676, 'reg_alpha': 1.0263330054243457e-08, 'reg_lambda': 0.01720660143743315, 'max_delta_step': 1}. Best is trial 0 with value: 0.6128654970760234.

Best trial: 0. Best value: 0.612865:   4%|▍         | 9/200 [00:09<02:01,  1.58it/s]

[I 2025-11-10 19:03:10,792] Trial 6 finished with value: 0.5957894736842105 and parameters: {'max_depth': 6, 'learning_rate': 0.010744235545266196, 'n_estimators': 1015, 'subsample': 0.6097026575616983, 'colsample_bytree': 0.9782699645484807, 'min_child_weight': 3, 'gamma': 2.2779319708935297, 'reg_alpha': 4.567352773604676e-08, 'reg_lambda': 1.4910750638706384e-05, 'max_delta_step': 3}. Best is trial 0 with value: 0.6128654970760234.
[I 2025-11-10 19:03:10,965] Trial 9 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.23564384013580977, 'n_estimators': 268, 'subsample': 0.9508147747125553, 'colsample_bytree': 0.5801664356126961, 'min_child_weight': 9, 'gamma': 2.9786198972283806, 'reg_alpha': 0.002609745453498079, 'reg_lambda': 0.07262747640630339, 'max_delta_step': 10}. Best is trial 0 with value: 0.6128654970760234.

Best trial: 4. Best value: 0.647251:   6%|▌         | 11/200 [00:10<01:52,  1.68it/s]

[I 2025-11-10 19:03:12,090] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.18785834398722673, 'n_estimators': 481, 'subsample': 0.568793072055973, 'colsample_bytree': 0.6343037232611634, 'min_child_weight': 8, 'gamma': 3.72361135545019, 'reg_alpha': 0.004004578923463031, 'reg_lambda': 2.1565788131985385e-06, 'max_delta_step': 1}. Best is trial 0 with value: 0.6128654970760234.
[I 2025-11-10 19:03:12,256] Trial 4 finished with value: 0.6472514619883041 and parameters: {'max_depth': 8, 'learning_rate': 0.0368634980656321, 'n_estimators': 1169, 'subsample': 0.6803337332672379, 'colsample_bytree': 0.8385048875787616, 'min_child_weight': 1, 'gamma': 1.5539889408148073, 'reg_alpha': 0.1514313747737032, 'reg_lambda': 6.31425533659749e-06, 'max_delta_step': 0}. Best is trial 4 with value: 0.6472514619883041.

Best trial: 4. Best value: 0.647251:   6%|▌         | 12/200 [00:12<02:57,  1.06it/s]

[I 2025-11-10 19:03:13,992] Trial 11 finished with value: 0.5871539961013645 and parameters: {'max_depth': 8, 'learning_rate': 0.030179282040977647, 'n_estimators': 609, 'subsample': 0.7848906543392153, 'colsample_bytree': 0.9700963817108237, 'min_child_weight': 3, 'gamma': 2.030125647249559, 'reg_alpha': 0.0016027979378624925, 'reg_lambda': 4.732193033918877e-06, 'max_delta_step': 4}. Best is trial 4 with value: 0.6472514619883041.

Best trial: 4. Best value: 0.647251:   6%|▋         | 13/200 [00:12<02:28,  1.26it/s]

[I 2025-11-10 19:03:14,437] Trial 14 pruned.

Best trial: 4. Best value: 0.647251:   7%|▋         | 14/200 [00:13<01:53,  1.64it/s]

[I 2025-11-10 19:03:14,630] Trial 12 finished with value: 0.6232553606237816 and parameters: {'max_depth': 6, 'learning_rate': 0.0577049395405258, 'n_estimators': 429, 'subsample': 0.7215636658102793, 'colsample_bytree': 0.982652397799955, 'min_child_weight': 1, 'gamma': 1.106893513502063, 'reg_alpha': 1.930798428460751, 'reg_lambda': 1.7267592788015369e-07, 'max_delta_step': 9}. Best is trial 4 with value: 0.6472514619883041.

Best trial: 13. Best value: 0.687719:   8%|▊         | 15/200 [00:13<02:00,  1.54it/s]

[I 2025-11-10 19:03:15,371] Trial 13 finished with value: 0.6877192982456141 and parameters: {'max_depth': 10, 'learning_rate': 0.13604092038690144, 'n_estimators': 713, 'subsample': 0.9955046136968296, 'colsample_bytree': 0.6897916667943821, 'min_child_weight': 1, 'gamma': 0.10538808377111297, 'reg_alpha': 1.4677354606398104e-05, 'reg_lambda': 1.0054934376517057e-08, 'max_delta_step': 5}. Best is trial 13 with value: 0.6877192982456141.

Best trial: 13. Best value: 0.687719:   8%|▊         | 17/200 [00:14<01:35,  1.91it/s]

[I 2025-11-10 19:03:16,110] Trial 17 pruned.
[I 2025-11-10 19:03:16,278] Trial 15 pruned.

Best trial: 13. Best value: 0.687719:   9%|▉         | 18/200 [00:15<01:39,  1.83it/s]

[I 2025-11-10 19:03:16,875] Trial 18 pruned.

Best trial: 13. Best value: 0.687719:  10%|▉         | 19/200 [00:15<01:20,  2.24it/s]

[I 2025-11-10 19:03:17,088] Trial 19 pruned.

Best trial: 13. Best value: 0.687719:  10%|█         | 20/200 [00:15<01:06,  2.72it/s]

[I 2025-11-10 19:03:17,274] Trial 20 pruned.

Best trial: 13. Best value: 0.687719:  10%|█         | 21/200 [00:16<01:35,  1.87it/s]

[I 2025-11-10 19:03:18,198] Trial 22 pruned.

Best trial: 13. Best value: 0.687719:  12%|█▏        | 23/200 [00:17<01:06,  2.64it/s]

[I 2025-11-10 19:03:18,598] Trial 24 pruned.
[I 2025-11-10 19:03:18,709] Trial 23 pruned.
[I 2025-11-10 19:03:18,739] Trial 21 pruned.

Best trial: 13. Best value: 0.687719:  12%|█▎        | 25/200 [00:17<00:55,  3.13it/s]

[I 2025-11-10 19:03:19,208] Trial 25 pruned.

Best trial: 13. Best value: 0.687719:  13%|█▎        | 26/200 [00:17<00:52,  3.30it/s]

[I 2025-11-10 19:03:19,460] Trial 26 pruned.

Best trial: 13. Best value: 0.687719:  14%|█▎        | 27/200 [00:18<01:06,  2.58it/s]

[I 2025-11-10 19:03:20,086] Trial 29 pruned.

Best trial: 13. Best value: 0.687719:  14%|█▍        | 28/200 [00:18<01:01,  2.78it/s]

[I 2025-11-10 19:03:20,370] Trial 28 pruned.

Best trial: 16. Best value: 0.704581:  15%|█▌        | 30/200 [00:19<00:52,  3.27it/s]

[I 2025-11-10 19:03:20,721] Trial 16 finished with value: 0.7045808966861598 and parameters: {'max_depth': 9, 'learning_rate': 0.11810752858227948, 'n_estimators': 947, 'subsample': 0.9951702150332329, 'colsample_bytree': 0.833003418269028, 'min_child_weight': 1, 'gamma': 1.1975387069371957, 'reg_alpha': 1.1151232844026378e-05, 'reg_lambda': 1.2703030664686833e-07, 'max_delta_step': 6}. Best is trial 16 with value: 0.7045808966861598.
[I 2025-11-10 19:03:20,899] Trial 30 pruned.

Best trial: 16. Best value: 0.704581:  16%|█▌        | 32/200 [00:20<01:07,  2.49it/s]

[I 2025-11-10 19:03:21,907] Trial 31 pruned.
[I 2025-11-10 19:03:22,049] Trial 32 pruned.

Best trial: 16. Best value: 0.704581:  16%|█▋        | 33/200 [00:20<00:55,  3.02it/s]

[I 2025-11-10 19:03:22,212] Trial 33 pruned.

Best trial: 16. Best value: 0.704581:  17%|█▋        | 34/200 [00:21<01:01,  2.72it/s]

[I 2025-11-10 19:03:22,669] Trial 27 finished with value: 0.6654970760233918 and parameters: {'max_depth': 5, 'learning_rate': 0.07256670326957945, 'n_estimators': 546, 'subsample': 0.7448260514474878, 'colsample_bytree': 0.9917583929945147, 'min_child_weight': 1, 'gamma': 0.8839975170557496, 'reg_alpha': 0.00017601987444522082, 'reg_lambda': 4.1107872580662665e-07, 'max_delta_step': 9}. Best is trial 16 with value: 0.7045808966861598.

Best trial: 16. Best value: 0.704581:  18%|█▊        | 35/200 [00:21<01:06,  2.49it/s]

[I 2025-11-10 19:03:23,142] Trial 35 pruned.
[I 2025-11-10 19:03:23,150] Trial 34 pruned.

Best trial: 16. Best value: 0.704581:  20%|█▉        | 39/200 [00:22<00:37,  4.28it/s]

[I 2025-11-10 19:03:23,706] Trial 37 pruned.
[I 2025-11-10 19:03:23,744] Trial 39 pruned.
[I 2025-11-10 19:03:23,830] Trial 38 pruned.

Best trial: 16. Best value: 0.704581:  20%|██        | 41/200 [00:22<00:40,  3.89it/s]

[I 2025-11-10 19:03:24,300] Trial 40 pruned.
[I 2025-11-10 19:03:24,470] Trial 41 pruned.

Best trial: 16. Best value: 0.704581:  20%|██        | 41/200 [00:23<00:40,  3.89it/s]

[I 2025-11-10 19:03:24,555] Trial 42 pruned.

Best trial: 16. Best value: 0.704581:  22%|██▏       | 43/200 [00:23<00:47,  3.29it/s]

[I 2025-11-10 19:03:25,209] Trial 45 pruned.

Best trial: 16. Best value: 0.704581:  22%|██▏       | 44/200 [00:24<00:48,  3.23it/s]

[I 2025-11-10 19:03:25,539] Trial 43 pruned.

Best trial: 16. Best value: 0.704581:  22%|██▎       | 45/200 [00:24<00:47,  3.25it/s]

[I 2025-11-10 19:03:25,843] Trial 46 pruned.

Best trial: 16. Best value: 0.704581:  23%|██▎       | 46/200 [00:24<00:49,  3.09it/s]

[I 2025-11-10 19:03:26,210] Trial 47 pruned.

Best trial: 16. Best value: 0.704581:  24%|██▎       | 47/200 [00:25<01:18,  1.94it/s]

[I 2025-11-10 19:03:27,246] Trial 48 pruned.

Best trial: 16. Best value: 0.704581:  24%|██▍       | 48/200 [00:26<01:08,  2.22it/s]

[I 2025-11-10 19:03:27,525] Trial 49 pruned.

Best trial: 16. Best value: 0.704581:  24%|██▍       | 49/200 [00:26<00:59,  2.52it/s]

[I 2025-11-10 19:03:27,789] Trial 44 finished with value: 0.6871150097465888 and parameters: {'max_depth': 6, 'learning_rate': 0.04827444332435404, 'n_estimators': 380, 'subsample': 0.7095977173999696, 'colsample_bytree': 0.9542720094606396, 'min_child_weight': 1, 'gamma': 1.13282579551083, 'reg_alpha': 7.64025195783145e-06, 'reg_lambda': 1.0631098937473823e-07, 'max_delta_step': 9}. Best is trial 16 with value: 0.7045808966861598.

Best trial: 16. Best value: 0.704581:  25%|██▌       | 50/200 [00:26<01:12,  2.08it/s]

[I 2025-11-10 19:03:28,480] Trial 50 pruned.

Best trial: 16. Best value: 0.704581:  26%|██▌       | 51/200 [00:27<01:10,  2.13it/s]

[I 2025-11-10 19:03:28,922] Trial 53 pruned.

Best trial: 36. Best value: 0.719727:  26%|██▌       | 52/200 [00:28<01:20,  1.83it/s]

[I 2025-11-10 19:03:29,654] Trial 36 finished with value: 0.7197270955165691 and parameters: {'max_depth': 10, 'learning_rate': 0.059339900097580243, 'n_estimators': 1023, 'subsample': 0.9929318591561702, 'colsample_bytree': 0.8448777024210329, 'min_child_weight': 1, 'gamma': 2.5310605222223312, 'reg_alpha': 0.5509625308923319, 'reg_lambda': 1.352104096679528e-08, 'max_delta_step': 7}. Best is trial 36 with value: 0.7197270955165691.

Best trial: 36. Best value: 0.719727:  26%|██▋       | 53/200 [00:29<01:58,  1.24it/s]

[I 2025-11-10 19:03:31,082] Trial 51 finished with value: 0.6364912280701753 and parameters: {'max_depth': 4, 'learning_rate': 0.053609809652445176, 'n_estimators': 648, 'subsample': 0.805671040347729, 'colsample_bytree': 0.5043195858794316, 'min_child_weight': 1, 'gamma': 0.28881371890579566, 'reg_alpha': 0.006879188150060046, 'reg_lambda': 3.513252448162136e-08, 'max_delta_step': 8}. Best is trial 36 with value: 0.7197270955165691.

Best trial: 36. Best value: 0.719727:  27%|██▋       | 54/200 [00:30<02:07,  1.14it/s]

[I 2025-11-10 19:03:32,113] Trial 56 pruned.

Best trial: 36. Best value: 0.719727:  28%|██▊       | 55/200 [00:30<01:38,  1.47it/s]

[I 2025-11-10 19:03:32,340] Trial 54 finished with value: 0.6783430799220274 and parameters: {'max_depth': 10, 'learning_rate': 0.051652309761250896, 'n_estimators': 454, 'subsample': 0.7147462829689035, 'colsample_bytree': 0.9770681784194757, 'min_child_weight': 1, 'gamma': 1.6310572633695852, 'reg_alpha': 1.4245606474374493e-05, 'reg_lambda': 6.793202791772029e-07, 'max_delta_step': 8}. Best is trial 36 with value: 0.7197270955165691.

Best trial: 36. Best value: 0.719727:  28%|██▊       | 56/200 [00:31<01:22,  1.74it/s]

[I 2025-11-10 19:03:32,668] Trial 52 finished with value: 0.686608187134503 and parameters: {'max_depth': 4, 'learning_rate': 0.035524997459702536, 'n_estimators': 653, 'subsample': 0.808387289480928, 'colsample_bytree': 0.8276870751785643, 'min_child_weight': 1, 'gamma': 1.3237346087768742, 'reg_alpha': 1.2771084603134462e-05, 'reg_lambda': 3.6993560651379353e-08, 'max_delta_step': 8}. Best is trial 36 with value: 0.7197270955165691.

Best trial: 36. Best value: 0.719727:  28%|██▊       | 57/200 [00:31<01:12,  1.97it/s]

[I 2025-11-10 19:03:33,016] Trial 58 pruned.

Best trial: 36. Best value: 0.719727:  29%|██▉       | 58/200 [00:31<01:04,  2.21it/s]

[I 2025-11-10 19:03:33,342] Trial 59 pruned.

Best trial: 36. Best value: 0.719727:  30%|██▉       | 59/200 [00:34<02:27,  1.04s/it]

[I 2025-11-10 19:03:35,772] Trial 55 finished with value: 0.6722027290448344 and parameters: {'max_depth': 10, 'learning_rate': 0.049863675209689935, 'n_estimators': 983, 'subsample': 0.9703091973334317, 'colsample_bytree': 0.7754086889059711, 'min_child_weight': 1, 'gamma': 2.9675861425014283, 'reg_alpha': 0.00909098154126504, 'reg_lambda': 5.322071934928571e-07, 'max_delta_step': 7}. Best is trial 36 with value: 0.7197270955165691.

Best trial: 36. Best value: 0.719727:  30%|███       | 60/200 [00:35<02:27,  1.06s/it]

[I 2025-11-10 19:03:36,853] Trial 60 finished with value: 0.6764912280701754 and parameters: {'max_depth': 10, 'learning_rate': 0.012407880021164398, 'n_estimators': 328, 'subsample': 0.9213087057874021, 'colsample_bytree': 0.7307522752783068, 'min_child_weight': 1, 'gamma': 1.6702668781337682, 'reg_alpha': 5.490167298943562e-05, 'reg_lambda': 9.044880888251972e-08, 'max_delta_step': 7}. Best is trial 36 with value: 0.7197270955165691.

Best trial: 36. Best value: 0.719727:  30%|███       | 61/200 [00:36<02:17,  1.01it/s]

[I 2025-11-10 19:03:37,681] Trial 63 pruned.

Best trial: 36. Best value: 0.719727:  31%|███       | 62/200 [00:36<01:55,  1.20it/s]

[I 2025-11-10 19:03:38,159] Trial 57 finished with value: 0.6892592592592592 and parameters: {'max_depth': 10, 'learning_rate': 0.04100233295656106, 'n_estimators': 1131, 'subsample': 0.9494210113668722, 'colsample_bytree': 0.5680546606767883, 'min_child_weight': 1, 'gamma': 2.794483849197875, 'reg_alpha': 6.2340424792081494e-06, 'reg_lambda': 5.070908911890224e-07, 'max_delta_step': 6}. Best is trial 36 with value: 0.7197270955165691.

Best trial: 36. Best value: 0.719727:  32%|███▏      | 63/200 [00:37<02:03,  1.11it/s]

[I 2025-11-10 19:03:39,219] Trial 65 pruned.

Best trial: 36. Best value: 0.719727:  32%|███▏      | 64/200 [00:38<02:00,  1.13it/s]

[I 2025-11-10 19:03:40,071] Trial 61 finished with value: 0.7025341130604288 and parameters: {'max_depth': 10, 'learning_rate': 0.04259387609994839, 'n_estimators': 1088, 'subsample': 0.9694651525078979, 'colsample_bytree': 0.7278811759034979, 'min_child_weight': 1, 'gamma': 1.7207318792958, 'reg_alpha': 3.709367862963661e-06, 'reg_lambda': 2.162633205408287, 'max_delta_step': 7}. Best is trial 36 with value: 0.7197270955165691.

Best trial: 36. Best value: 0.719727:  32%|███▎      | 65/200 [00:40<02:36,  1.16s/it]

[I 2025-11-10 19:03:41,871] Trial 64 finished with value: 0.6739181286549707 and parameters: {'max_depth': 10, 'learning_rate': 0.010343328399069724, 'n_estimators': 354, 'subsample': 0.9043863895907761, 'colsample_bytree': 0.7344224491079865, 'min_child_weight': 1, 'gamma': 1.6671855099686237, 'reg_alpha': 5.34666003549078e-05, 'reg_lambda': 1.2415905913536e-07, 'max_delta_step': 7}. Best is trial 36 with value: 0.7197270955165691.

Best trial: 36. Best value: 0.719727:  33%|███▎      | 66/200 [00:40<02:08,  1.04it/s]

[I 2025-11-10 19:03:42,363] Trial 67 pruned.

Best trial: 36. Best value: 0.719727:  34%|███▍      | 68/200 [00:41<01:26,  1.52it/s]

[I 2025-11-10 19:03:43,071] Trial 62 finished with value: 0.6985964912280702 and parameters: {'max_depth': 10, 'learning_rate': 0.028426952128637818, 'n_estimators': 1106, 'subsample': 0.9148425649022727, 'colsample_bytree': 0.8655503030917241, 'min_child_weight': 1, 'gamma': 1.6800350418154908, 'reg_alpha': 3.797546891658389e-05, 'reg_lambda': 2.8372589851467502e-08, 'max_delta_step': 8}. Best is trial 36 with value: 0.7197270955165691.
[I 2025-11-10 19:03:43,200] Trial 68 pruned.

Best trial: 36. Best value: 0.719727:  34%|███▍      | 69/200 [00:42<01:21,  1.61it/s]

[I 2025-11-10 19:03:43,736] Trial 69 pruned.

Best trial: 36. Best value: 0.719727:  35%|███▌      | 70/200 [00:43<01:25,  1.52it/s]

[I 2025-11-10 19:03:44,475] Trial 71 pruned.
[I 2025-11-10 19:03:44,513] Trial 70 pruned.

Best trial: 36. Best value: 0.719727:  36%|███▌      | 72/200 [00:45<01:46,  1.21it/s]

[I 2025-11-10 19:03:46,536] Trial 66 finished with value: 0.7087524366471735 and parameters: {'max_depth': 9, 'learning_rate': 0.03141021084159811, 'n_estimators': 1112, 'subsample': 0.952941743560176, 'colsample_bytree': 0.8996274697507421, 'min_child_weight': 1, 'gamma': 2.7027060133317606, 'reg_alpha': 1.3319757904914576e-05, 'reg_lambda': 1.9315798024474363e-07, 'max_delta_step': 6}. Best is trial 36 with value: 0.7197270955165691.

Best trial: 36. Best value: 0.719727:  36%|███▋      | 73/200 [00:48<02:58,  1.41s/it]

[I 2025-11-10 19:03:49,701] Trial 73 pruned.

Best trial: 72. Best value: 0.719786:  37%|███▋      | 74/200 [00:48<02:33,  1.22s/it]

[I 2025-11-10 19:03:50,379] Trial 72 finished with value: 0.719785575048733 and parameters: {'max_depth': 10, 'learning_rate': 0.24821728534313975, 'n_estimators': 1109, 'subsample': 0.9992802144982255, 'colsample_bytree': 0.8660821097054235, 'min_child_weight': 1, 'gamma': 3.2424694071644704, 'reg_alpha': 1.4894322995561468e-06, 'reg_lambda': 0.2708587237790979, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  38%|███▊      | 75/200 [00:49<01:58,  1.05it/s]

[I 2025-11-10 19:03:50,611] Trial 74 finished with value: 0.6898245614035088 and parameters: {'max_depth': 10, 'learning_rate': 0.03169242792878503, 'n_estimators': 1002, 'subsample': 0.8764983144210535, 'colsample_bytree': 0.8316906401484893, 'min_child_weight': 1, 'gamma': 2.0088399874222684, 'reg_alpha': 4.181692946735023e-06, 'reg_lambda': 4.4412480250608874e-08, 'max_delta_step': 8}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  38%|███▊      | 76/200 [00:50<02:13,  1.07s/it]

[I 2025-11-10 19:03:52,007] Trial 75 pruned.

Best trial: 72. Best value: 0.719786:  38%|███▊      | 77/200 [00:51<02:17,  1.12s/it]

[I 2025-11-10 19:03:53,242] Trial 79 pruned.

Best trial: 72. Best value: 0.719786:  39%|███▉      | 78/200 [00:52<02:02,  1.00s/it]

[I 2025-11-10 19:03:53,964] Trial 80 pruned.

Best trial: 72. Best value: 0.719786:  40%|███▉      | 79/200 [00:54<02:43,  1.35s/it]

[I 2025-11-10 19:03:56,146] Trial 78 pruned.

Best trial: 72. Best value: 0.719786:  40%|████      | 80/200 [00:55<02:08,  1.07s/it]

[I 2025-11-10 19:03:56,557] Trial 76 finished with value: 0.7050292397660819 and parameters: {'max_depth': 9, 'learning_rate': 0.03367482830571799, 'n_estimators': 1080, 'subsample': 0.9823904579992302, 'colsample_bytree': 0.9000666597656656, 'min_child_weight': 1, 'gamma': 3.1348560227530484, 'reg_alpha': 5.108424621979939e-06, 'reg_lambda': 2.453426519725474e-07, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  40%|████      | 81/200 [00:55<01:48,  1.10it/s]

[I 2025-11-10 19:03:57,086] Trial 77 finished with value: 0.7062670565302144 and parameters: {'max_depth': 9, 'learning_rate': 0.18188199210267866, 'n_estimators': 1079, 'subsample': 0.9795694081816466, 'colsample_bytree': 0.9026390100583811, 'min_child_weight': 1, 'gamma': 3.298370141206613, 'reg_alpha': 5.280922279132069e-06, 'reg_lambda': 0.30873981490207303, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  41%|████      | 82/200 [00:56<01:37,  1.21it/s]

[I 2025-11-10 19:03:57,707] Trial 82 pruned.

Best trial: 72. Best value: 0.719786:  42%|████▏     | 83/200 [00:56<01:18,  1.49it/s]

[I 2025-11-10 19:03:58,010] Trial 83 pruned.

Best trial: 72. Best value: 0.719786:  42%|████▏     | 84/200 [00:57<01:20,  1.44it/s]

[I 2025-11-10 19:03:58,766] Trial 85 pruned.

Best trial: 72. Best value: 0.719786:  42%|████▎     | 85/200 [00:57<01:18,  1.47it/s]

[I 2025-11-10 19:03:59,416] Trial 84 pruned.

Best trial: 72. Best value: 0.719786:  43%|████▎     | 86/200 [00:58<01:18,  1.46it/s]

[I 2025-11-10 19:04:00,111] Trial 87 pruned.

Best trial: 72. Best value: 0.719786:  44%|████▎     | 87/200 [00:59<01:40,  1.12it/s]

[I 2025-11-10 19:04:01,486] Trial 81 finished with value: 0.6825536062378167 and parameters: {'max_depth': 9, 'learning_rate': 0.02189781047730595, 'n_estimators': 1126, 'subsample': 0.9564345901831982, 'colsample_bytree': 0.8455303860645171, 'min_child_weight': 1, 'gamma': 2.8618034349156813, 'reg_alpha': 4.4976493637958116e-06, 'reg_lambda': 0.32596460422693696, 'max_delta_step': 8}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  44%|████▍     | 88/200 [01:01<01:50,  1.01it/s]

[I 2025-11-10 19:04:02,688] Trial 90 pruned.

Best trial: 72. Best value: 0.719786:  44%|████▍     | 89/200 [01:01<01:37,  1.14it/s]

[I 2025-11-10 19:04:03,309] Trial 86 pruned.

Best trial: 72. Best value: 0.719786:  45%|████▌     | 90/200 [01:04<02:22,  1.29s/it]

[I 2025-11-10 19:04:05,580] Trial 89 pruned.

Best trial: 72. Best value: 0.719786:  46%|████▌     | 91/200 [01:04<01:45,  1.04it/s]

[I 2025-11-10 19:04:05,776] Trial 88 finished with value: 0.6612280701754385 and parameters: {'max_depth': 9, 'learning_rate': 0.21533769779708434, 'n_estimators': 1056, 'subsample': 0.9978377093765929, 'colsample_bytree': 0.8715573482412087, 'min_child_weight': 1, 'gamma': 3.259622731405199, 'reg_alpha': 3.4950651454883046e-06, 'reg_lambda': 0.03987083644528533, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  46%|████▌     | 92/200 [01:05<01:41,  1.07it/s]

[I 2025-11-10 19:04:06,648] Trial 93 pruned.

Best trial: 72. Best value: 0.719786:  46%|████▋     | 93/200 [01:07<02:12,  1.24s/it]

[I 2025-11-10 19:04:08,605] Trial 91 finished with value: 0.7043957115009747 and parameters: {'max_depth': 10, 'learning_rate': 0.23006234183213017, 'n_estimators': 999, 'subsample': 0.976950920722646, 'colsample_bytree': 0.8739958503209728, 'min_child_weight': 1, 'gamma': 2.985712448174647, 'reg_alpha': 3.5559641711268546e-07, 'reg_lambda': 5.3965925254068235e-08, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  47%|████▋     | 94/200 [01:07<01:58,  1.12s/it]

[I 2025-11-10 19:04:09,435] Trial 92 finished with value: 0.6828265107212476 and parameters: {'max_depth': 10, 'learning_rate': 0.23485543322845265, 'n_estimators': 1026, 'subsample': 0.9286354770339945, 'colsample_bytree': 0.8719004283153978, 'min_child_weight': 1, 'gamma': 3.0687393892425017, 'reg_alpha': 0.035131218576682034, 'reg_lambda': 5.5557730722888325e-08, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  48%|████▊     | 95/200 [01:11<03:00,  1.72s/it]

[I 2025-11-10 19:04:12,547] Trial 94 finished with value: 0.7160428849902534 and parameters: {'max_depth': 10, 'learning_rate': 0.03178040790246099, 'n_estimators': 1023, 'subsample': 0.9427511060869916, 'colsample_bytree': 0.8917546176763309, 'min_child_weight': 1, 'gamma': 2.940298244431538, 'reg_alpha': 0.02249219461618557, 'reg_lambda': 8.367097660732091e-06, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  48%|████▊     | 96/200 [01:11<02:14,  1.30s/it]

[I 2025-11-10 19:04:12,861] Trial 95 finished with value: 0.7078752436647173 and parameters: {'max_depth': 10, 'learning_rate': 0.03943250436179185, 'n_estimators': 1020, 'subsample': 0.9732945767103479, 'colsample_bytree': 0.8356575099334222, 'min_child_weight': 1, 'gamma': 2.884520036367128, 'reg_alpha': 6.77224816280452e-06, 'reg_lambda': 0.00018921187003426582, 'max_delta_step': 5}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  49%|████▉     | 98/200 [01:12<01:23,  1.22it/s]

[I 2025-11-10 19:04:13,557] Trial 96 pruned.
[I 2025-11-10 19:04:13,693] Trial 98 pruned.

Best trial: 72. Best value: 0.719786:  50%|████▉     | 99/200 [01:12<01:08,  1.46it/s]

[I 2025-11-10 19:04:14,054] Trial 99 pruned.

Best trial: 72. Best value: 0.719786:  50%|█████     | 101/200 [01:13<01:06,  1.48it/s]

[I 2025-11-10 19:04:14,703] Trial 100 pruned.
[I 2025-11-10 19:04:14,715] Trial 102 pruned.
[I 2025-11-10 19:04:14,731] Trial 101 pruned.

Best trial: 72. Best value: 0.719786:  52%|█████▏    | 103/200 [01:13<00:43,  2.24it/s]

[I 2025-11-10 19:04:15,510] Trial 97 finished with value: 0.6930311890838207 and parameters: {'max_depth': 10, 'learning_rate': 0.16495638459731118, 'n_estimators': 958, 'subsample': 0.9753676003763576, 'colsample_bytree': 0.8870197778552645, 'min_child_weight': 1, 'gamma': 3.5138293235546074, 'reg_alpha': 1.4054458449205636e-07, 'reg_lambda': 1.686689618372254e-07, 'max_delta_step': 5}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  52%|█████▏    | 104/200 [01:15<01:02,  1.54it/s]

[I 2025-11-10 19:04:16,925] Trial 106 pruned.

Best trial: 72. Best value: 0.719786:  52%|█████▎    | 105/200 [01:18<01:51,  1.17s/it]

[I 2025-11-10 19:04:19,826] Trial 103 finished with value: 0.6966959064327486 and parameters: {'max_depth': 8, 'learning_rate': 0.1979789189595592, 'n_estimators': 846, 'subsample': 0.9887108538731372, 'colsample_bytree': 0.91672584454397, 'min_child_weight': 1, 'gamma': 2.76390330256244, 'reg_alpha': 2.751568398976009e-07, 'reg_lambda': 8.86480840300606e-06, 'max_delta_step': 4}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  53%|█████▎    | 106/200 [01:19<01:50,  1.18s/it]

[I 2025-11-10 19:04:21,014] Trial 104 finished with value: 0.7028265107212477 and parameters: {'max_depth': 10, 'learning_rate': 0.044443888914923006, 'n_estimators': 1072, 'subsample': 0.9859619664878881, 'colsample_bytree': 0.7967804580845954, 'min_child_weight': 1, 'gamma': 2.7913802712048637, 'reg_alpha': 1.0478240097188411e-05, 'reg_lambda': 1.1617593219217266e-06, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  54%|█████▎    | 107/200 [01:20<01:33,  1.01s/it]

[I 2025-11-10 19:04:21,546] Trial 105 finished with value: 0.7068810916179338 and parameters: {'max_depth': 10, 'learning_rate': 0.03456834565826756, 'n_estimators': 1078, 'subsample': 0.9868132486590837, 'colsample_bytree': 0.8354818265019628, 'min_child_weight': 1, 'gamma': 2.731875355267871, 'reg_alpha': 0.0005352300171436659, 'reg_lambda': 9.11590613242256e-06, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  54%|█████▍    | 108/200 [01:22<02:09,  1.41s/it]

[I 2025-11-10 19:04:24,042] Trial 107 finished with value: 0.7082456140350877 and parameters: {'max_depth': 10, 'learning_rate': 0.037763402320973846, 'n_estimators': 1104, 'subsample': 0.9913064550772486, 'colsample_bytree': 0.914754614000566, 'min_child_weight': 1, 'gamma': 2.564038788217629, 'reg_alpha': 0.02096354428822723, 'reg_lambda': 8.484889526144861e-06, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  55%|█████▍    | 109/200 [01:24<02:28,  1.63s/it]

[I 2025-11-10 19:04:26,233] Trial 111 pruned.

Best trial: 72. Best value: 0.719786:  55%|█████▌    | 110/200 [01:24<01:51,  1.24s/it]

[I 2025-11-10 19:04:26,501] Trial 108 finished with value: 0.7072514619883041 and parameters: {'max_depth': 10, 'learning_rate': 0.03683738678910517, 'n_estimators': 1103, 'subsample': 0.9862365607591359, 'colsample_bytree': 0.8189328026651381, 'min_child_weight': 1, 'gamma': 2.520847196442473, 'reg_alpha': 1.1584151517516927e-05, 'reg_lambda': 3.716685846122967e-05, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  56%|█████▌    | 111/200 [01:25<01:41,  1.14s/it]

[I 2025-11-10 19:04:27,381] Trial 113 pruned.
[I 2025-11-10 19:04:27,389] Trial 109 finished with value: 0.7180116959064327 and parameters: {'max_depth': 9, 'learning_rate': 0.04358927952682748, 'n_estimators': 1068, 'subsample': 0.9857785083577393, 'colsample_bytree': 0.7978620820830721, 'min_child_weight': 1, 'gamma': 2.508080872317419, 'reg_alpha': 9.94768403333051e-06, 'reg_lambda': 1.3263688417430483e-06, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  56%|█████▋    | 113/200 [01:26<01:10,  1.24it/s]

[I 2025-11-10 19:04:28,211] Trial 110 finished with value: 0.7133138401559455 and parameters: {'max_depth': 9, 'learning_rate': 0.0378739496090382, 'n_estimators': 1055, 'subsample': 0.9879091998076066, 'colsample_bytree': 0.8003617560836632, 'min_child_weight': 1, 'gamma': 2.527050284109537, 'reg_alpha': 0.004218858099040001, 'reg_lambda': 2.9721774317480013e-06, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  57%|█████▋    | 114/200 [01:28<01:34,  1.10s/it]

[I 2025-11-10 19:04:30,223] Trial 115 pruned.

Best trial: 72. Best value: 0.719786:  57%|█████▊    | 115/200 [01:31<02:18,  1.63s/it]

[I 2025-11-10 19:04:33,359] Trial 112 finished with value: 0.698635477582846 and parameters: {'max_depth': 10, 'learning_rate': 0.03463582016983951, 'n_estimators': 1054, 'subsample': 0.9876676267376177, 'colsample_bytree': 0.9419059022819791, 'min_child_weight': 1, 'gamma': 2.5702945268608217, 'reg_alpha': 0.0007788645922957221, 'reg_lambda': 2.864701799571962e-06, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  58%|█████▊    | 116/200 [01:32<01:58,  1.41s/it]

[I 2025-11-10 19:04:34,168] Trial 114 finished with value: 0.7196296296296296 and parameters: {'max_depth': 9, 'learning_rate': 0.05517412886045286, 'n_estimators': 1152, 'subsample': 0.9578935261346707, 'colsample_bytree': 0.8065835343215535, 'min_child_weight': 1, 'gamma': 2.376809119102291, 'reg_alpha': 0.14194856425447236, 'reg_lambda': 2.9863331040023725e-06, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  58%|█████▊    | 117/200 [01:33<01:48,  1.30s/it]

[I 2025-11-10 19:04:35,200] Trial 116 finished with value: 0.7030799220272904 and parameters: {'max_depth': 9, 'learning_rate': 0.03360878839296215, 'n_estimators': 1145, 'subsample': 0.9605112785136971, 'colsample_bytree': 0.8026270963238066, 'min_child_weight': 1, 'gamma': 2.346205746072818, 'reg_alpha': 0.0006350358082645842, 'reg_lambda': 3.349509849386837e-06, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  59%|█████▉    | 118/200 [01:35<01:50,  1.35s/it]

[I 2025-11-10 19:04:36,653] Trial 117 finished with value: 0.6870175438596491 and parameters: {'max_depth': 10, 'learning_rate': 0.03746346422546176, 'n_estimators': 1105, 'subsample': 0.9587753297944066, 'colsample_bytree': 0.7774349522450957, 'min_child_weight': 1, 'gamma': 2.552420312793716, 'reg_alpha': 0.000715836492110584, 'reg_lambda': 2.988065295757306e-06, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  60%|█████▉    | 119/200 [01:38<02:35,  1.92s/it]

[I 2025-11-10 19:04:40,001] Trial 118 finished with value: 0.7075243664717349 and parameters: {'max_depth': 9, 'learning_rate': 0.03693563891932619, 'n_estimators': 1103, 'subsample': 0.9567700853712676, 'colsample_bytree': 0.8157407556108319, 'min_child_weight': 1, 'gamma': 2.2969060294451844, 'reg_alpha': 0.025320692475538455, 'reg_lambda': 7.58211720564515e-05, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  60%|██████    | 120/200 [01:39<02:20,  1.75s/it]

[I 2025-11-10 19:04:41,341] Trial 122 pruned.

Best trial: 72. Best value: 0.719786:  60%|██████    | 121/200 [01:40<01:52,  1.42s/it]

[I 2025-11-10 19:04:41,964] Trial 119 finished with value: 0.6996296296296296 and parameters: {'max_depth': 10, 'learning_rate': 0.05498780631184399, 'n_estimators': 1334, 'subsample': 0.9548911502258014, 'colsample_bytree': 0.820752201716769, 'min_child_weight': 1, 'gamma': 2.210081994951973, 'reg_alpha': 0.15811428691627918, 'reg_lambda': 6.568810747135429e-06, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  61%|██████    | 122/200 [01:41<01:41,  1.30s/it]

[I 2025-11-10 19:04:42,985] Trial 120 finished with value: 0.687504873294347 and parameters: {'max_depth': 10, 'learning_rate': 0.0604017967673607, 'n_estimators': 1324, 'subsample': 0.9320021675511261, 'colsample_bytree': 0.8201676739968878, 'min_child_weight': 1, 'gamma': 2.1615217993545386, 'reg_alpha': 0.069985308479157, 'reg_lambda': 6.379353951067813e-06, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  62%|██████▏   | 123/200 [01:42<01:29,  1.16s/it]

[I 2025-11-10 19:04:43,807] Trial 121 finished with value: 0.7130799220272903 and parameters: {'max_depth': 10, 'learning_rate': 0.0571772456674549, 'n_estimators': 1188, 'subsample': 0.969753050755088, 'colsample_bytree': 0.823560211018183, 'min_child_weight': 1, 'gamma': 2.4327348189938878, 'reg_alpha': 0.062125621080635816, 'reg_lambda': 6.6161352249491164e-06, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  62%|██████▏   | 124/200 [01:46<02:34,  2.03s/it]

[I 2025-11-10 19:04:47,895] Trial 123 finished with value: 0.6934502923976609 and parameters: {'max_depth': 10, 'learning_rate': 0.04644814823017643, 'n_estimators': 1149, 'subsample': 0.8999592806996592, 'colsample_bytree': 0.7469610909676268, 'min_child_weight': 1, 'gamma': 2.1357453147638306, 'reg_alpha': 0.025910907120441227, 'reg_lambda': 2.616737125176789e-05, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  62%|██████▎   | 125/200 [01:47<02:10,  1.74s/it]

[I 2025-11-10 19:04:48,951] Trial 124 finished with value: 0.6845614035087719 and parameters: {'max_depth': 9, 'learning_rate': 0.046691987412114604, 'n_estimators': 1186, 'subsample': 0.968591108691229, 'colsample_bytree': 0.8171307500308236, 'min_child_weight': 1, 'gamma': 2.6829425762021866, 'reg_alpha': 0.023156461119532033, 'reg_lambda': 2.3565419924372207e-05, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  63%|██████▎   | 126/200 [01:48<01:47,  1.45s/it]

[I 2025-11-10 19:04:49,734] Trial 128 pruned.

Best trial: 72. Best value: 0.719786:  64%|██████▎   | 127/200 [01:48<01:19,  1.09s/it]

[I 2025-11-10 19:04:49,961] Trial 125 finished with value: 0.6988888888888889 and parameters: {'max_depth': 9, 'learning_rate': 0.0419602833204212, 'n_estimators': 1108, 'subsample': 0.9696264181009292, 'colsample_bytree': 0.8413739564064786, 'min_child_weight': 1, 'gamma': 2.703323399890055, 'reg_alpha': 0.024289456657951392, 'reg_lambda': 1.697556469994268e-05, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  64%|██████▍   | 128/200 [01:49<01:17,  1.07s/it]

[I 2025-11-10 19:04:50,994] Trial 126 finished with value: 0.7044444444444444 and parameters: {'max_depth': 10, 'learning_rate': 0.047293382875557705, 'n_estimators': 1194, 'subsample': 0.9674109856531969, 'colsample_bytree': 0.8385159720304745, 'min_child_weight': 1, 'gamma': 2.716942955888442, 'reg_alpha': 0.022308584454310762, 'reg_lambda': 2.9386943554113554e-05, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  64%|██████▍   | 129/200 [01:54<02:30,  2.12s/it]

[I 2025-11-10 19:04:55,567] Trial 127 finished with value: 0.7053021442495128 and parameters: {'max_depth': 10, 'learning_rate': 0.026226755903267826, 'n_estimators': 1234, 'subsample': 0.9690780169035546, 'colsample_bytree': 0.8420102734152766, 'min_child_weight': 1, 'gamma': 2.6653929642194583, 'reg_alpha': 0.005921260764795132, 'reg_lambda': 1.2385875240140293e-05, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  65%|██████▌   | 130/200 [01:55<02:13,  1.91s/it]

[I 2025-11-10 19:04:56,978] Trial 129 finished with value: 0.6998635477582846 and parameters: {'max_depth': 10, 'learning_rate': 0.05183888266949841, 'n_estimators': 1243, 'subsample': 0.9666144100986312, 'colsample_bytree': 0.8400840212973911, 'min_child_weight': 1, 'gamma': 2.527757199065057, 'reg_alpha': 0.004430397841395131, 'reg_lambda': 5.528991104120231e-05, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  66%|██████▌   | 131/200 [01:55<01:42,  1.48s/it]

[I 2025-11-10 19:04:57,476] Trial 130 finished with value: 0.7107407407407408 and parameters: {'max_depth': 10, 'learning_rate': 0.02581616350865913, 'n_estimators': 1242, 'subsample': 0.9403782305326772, 'colsample_bytree': 0.7687551618374231, 'min_child_weight': 1, 'gamma': 2.428831161773394, 'reg_alpha': 0.006242003014309369, 'reg_lambda': 5.74385463921902e-05, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  66%|██████▌   | 132/200 [01:56<01:23,  1.22s/it]

[I 2025-11-10 19:04:58,086] Trial 131 finished with value: 0.7028265107212475 and parameters: {'max_depth': 10, 'learning_rate': 0.05276900693480924, 'n_estimators': 1242, 'subsample': 0.9401822682270851, 'colsample_bytree': 0.7984782063496785, 'min_child_weight': 1, 'gamma': 2.5258991434407108, 'reg_alpha': 0.007414646521229328, 'reg_lambda': 6.813289321663805e-05, 'max_delta_step': 4}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  66%|██████▋   | 133/200 [01:57<01:07,  1.01s/it]

[I 2025-11-10 19:04:58,590] Trial 133 pruned.

Best trial: 72. Best value: 0.719786:  67%|██████▋   | 134/200 [01:57<01:01,  1.07it/s]

[I 2025-11-10 19:04:59,355] Trial 135 pruned.

Best trial: 72. Best value: 0.719786:  68%|██████▊   | 135/200 [01:58<00:56,  1.15it/s]

[I 2025-11-10 19:05:00,085] Trial 136 pruned.

Best trial: 72. Best value: 0.719786:  68%|██████▊   | 136/200 [02:00<01:18,  1.22s/it]

[I 2025-11-10 19:05:02,120] Trial 132 finished with value: 0.7041910331384016 and parameters: {'max_depth': 10, 'learning_rate': 0.051511676957959274, 'n_estimators': 1039, 'subsample': 0.9443782866081653, 'colsample_bytree': 0.8087832821342044, 'min_child_weight': 1, 'gamma': 2.4304351586378314, 'reg_alpha': 0.03730323740631614, 'reg_lambda': 6.412395089581071e-05, 'max_delta_step': 4}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  68%|██████▊   | 137/200 [02:01<01:01,  1.03it/s]

[I 2025-11-10 19:05:02,514] Trial 137 pruned.

Best trial: 72. Best value: 0.719786:  69%|██████▉   | 138/200 [02:03<01:25,  1.38s/it]

[I 2025-11-10 19:05:04,848] Trial 134 finished with value: 0.7112280701754387 and parameters: {'max_depth': 10, 'learning_rate': 0.031057554366330994, 'n_estimators': 1146, 'subsample': 0.9484783259582293, 'colsample_bytree': 0.7699475945772661, 'min_child_weight': 1, 'gamma': 2.4368331712221893, 'reg_alpha': 0.0431499916364129, 'reg_lambda': 0.00012565628312142556, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  70%|██████▉   | 139/200 [02:06<02:00,  1.98s/it]

[I 2025-11-10 19:05:08,228] Trial 138 finished with value: 0.7054191033138402 and parameters: {'max_depth': 10, 'learning_rate': 0.02678569991853048, 'n_estimators': 1291, 'subsample': 0.9827899597061227, 'colsample_bytree': 0.8246756542153296, 'min_child_weight': 1, 'gamma': 1.9713314222038731, 'reg_alpha': 0.014568902597397761, 'reg_lambda': 4.1135164667639054e-05, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  70%|███████   | 140/200 [02:07<01:34,  1.58s/it]

[I 2025-11-10 19:05:08,869] Trial 139 finished with value: 0.709746588693957 and parameters: {'max_depth': 9, 'learning_rate': 0.06575535938186619, 'n_estimators': 1132, 'subsample': 0.97950087879427, 'colsample_bytree': 0.8253699073541856, 'min_child_weight': 1, 'gamma': 1.9795662289501808, 'reg_alpha': 0.09150898920957391, 'reg_lambda': 7.704540198502083e-06, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  70%|███████   | 141/200 [02:07<01:15,  1.28s/it]

[I 2025-11-10 19:05:09,452] Trial 142 pruned.

Best trial: 72. Best value: 0.719786:  72%|███████▏  | 143/200 [02:08<00:46,  1.22it/s]

[I 2025-11-10 19:05:10,173] Trial 143 pruned.
[I 2025-11-10 19:05:10,300] Trial 140 finished with value: 0.7031968810916178 and parameters: {'max_depth': 9, 'learning_rate': 0.07724356744396242, 'n_estimators': 1291, 'subsample': 0.9996904275486964, 'colsample_bytree': 0.8242371035482694, 'min_child_weight': 1, 'gamma': 1.9794426478274723, 'reg_alpha': 0.2472308105780453, 'reg_lambda': 4.0056730174371735e-05, 'max_delta_step': 5}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  72%|███████▏  | 144/200 [02:09<00:42,  1.32it/s]

[I 2025-11-10 19:05:10,925] Trial 144 pruned.

Best trial: 72. Best value: 0.719786:  72%|███████▎  | 145/200 [02:10<00:40,  1.37it/s]

[I 2025-11-10 19:05:11,588] Trial 146 pruned.

Best trial: 72. Best value: 0.719786:  73%|███████▎  | 146/200 [02:10<00:31,  1.71it/s]

[I 2025-11-10 19:05:11,838] Trial 145 pruned.

Best trial: 72. Best value: 0.719786:  74%|███████▍  | 148/200 [02:11<00:23,  2.18it/s]

[I 2025-11-10 19:05:12,418] Trial 148 pruned.
[I 2025-11-10 19:05:12,582] Trial 141 finished with value: 0.7051656920077972 and parameters: {'max_depth': 9, 'learning_rate': 0.0643706553003763, 'n_estimators': 1289, 'subsample': 0.9361791484413939, 'colsample_bytree': 0.7936914166256416, 'min_child_weight': 1, 'gamma': 2.028837274205076, 'reg_alpha': 0.014591038396290838, 'reg_lambda': 0.00016323030508541995, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  74%|███████▍  | 149/200 [02:12<00:32,  1.55it/s]

[I 2025-11-10 19:05:13,656] Trial 147 pruned.

Best trial: 72. Best value: 0.719786:  75%|███████▌  | 150/200 [02:12<00:27,  1.80it/s]

[I 2025-11-10 19:05:14,013] Trial 151 pruned.

Best trial: 72. Best value: 0.719786:  76%|███████▌  | 151/200 [02:16<01:20,  1.65s/it]

[I 2025-11-10 19:05:18,201] Trial 149 finished with value: 0.6960428849902534 and parameters: {'max_depth': 10, 'learning_rate': 0.03199900640462232, 'n_estimators': 1023, 'subsample': 0.9360987457231514, 'colsample_bytree': 0.7727559031395363, 'min_child_weight': 1, 'gamma': 2.544224955556019, 'reg_alpha': 0.03469359593088056, 'reg_lambda': 4.9399578156142455e-06, 'max_delta_step': 5}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  76%|███████▌  | 152/200 [02:17<01:09,  1.44s/it]

[I 2025-11-10 19:05:19,160] Trial 150 finished with value: 0.706803118908382 and parameters: {'max_depth': 10, 'learning_rate': 0.044025143469600375, 'n_estimators': 1150, 'subsample': 0.9335025575821934, 'colsample_bytree': 0.7724781947403185, 'min_child_weight': 1, 'gamma': 2.5512930832431344, 'reg_alpha': 0.06535460343610526, 'reg_lambda': 8.39608430815707e-07, 'max_delta_step': 5}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  76%|███████▋  | 153/200 [02:18<00:53,  1.13s/it]

[I 2025-11-10 19:05:19,572] Trial 154 pruned.

Best trial: 72. Best value: 0.719786:  77%|███████▋  | 154/200 [02:18<00:46,  1.01s/it]

[I 2025-11-10 19:05:20,312] Trial 152 finished with value: 0.707270955165692 and parameters: {'max_depth': 10, 'learning_rate': 0.04350940826836971, 'n_estimators': 1128, 'subsample': 0.992908642519227, 'colsample_bytree': 0.7733842554310933, 'min_child_weight': 1, 'gamma': 2.5934251310648038, 'reg_alpha': 0.037798635061533865, 'reg_lambda': 0.00038584947933568693, 'max_delta_step': 5}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  78%|███████▊  | 155/200 [02:19<00:36,  1.24it/s]

[I 2025-11-10 19:05:20,643] Trial 155 pruned.

Best trial: 72. Best value: 0.719786:  78%|███████▊  | 156/200 [02:19<00:29,  1.50it/s]

[I 2025-11-10 19:05:20,973] Trial 153 finished with value: 0.6954191033138402 and parameters: {'max_depth': 10, 'learning_rate': 0.029725113168931123, 'n_estimators': 1062, 'subsample': 0.947196951865623, 'colsample_bytree': 0.8078081000108733, 'min_child_weight': 1, 'gamma': 2.6052897072041423, 'reg_alpha': 0.07503026930889428, 'reg_lambda': 1.571990665628699e-05, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  78%|███████▊  | 157/200 [02:20<00:27,  1.54it/s]

[I 2025-11-10 19:05:21,589] Trial 157 pruned.

Best trial: 72. Best value: 0.719786:  79%|███████▉  | 158/200 [02:20<00:26,  1.57it/s]

[I 2025-11-10 19:05:22,191] Trial 159 pruned.

Best trial: 72. Best value: 0.719786:  80%|███████▉  | 159/200 [02:21<00:27,  1.47it/s]

[I 2025-11-10 19:05:22,976] Trial 160 pruned.

Best trial: 72. Best value: 0.719786:  80%|████████  | 160/200 [02:22<00:33,  1.20it/s]

[I 2025-11-10 19:05:24,170] Trial 162 pruned.

Best trial: 72. Best value: 0.719786:  81%|████████  | 162/200 [02:23<00:24,  1.58it/s]

[I 2025-11-10 19:05:24,995] Trial 161 pruned.
[I 2025-11-10 19:05:25,163] Trial 156 pruned.

Best trial: 72. Best value: 0.719786:  82%|████████▏ | 163/200 [02:23<00:19,  1.88it/s]

[I 2025-11-10 19:05:25,465] Trial 163 pruned.

Best trial: 72. Best value: 0.719786:  82%|████████▏ | 164/200 [02:26<00:36,  1.02s/it]

[I 2025-11-10 19:05:27,616] Trial 158 finished with value: 0.7126120857699805 and parameters: {'max_depth': 10, 'learning_rate': 0.04799793524681771, 'n_estimators': 1123, 'subsample': 0.9514196739684938, 'colsample_bytree': 0.7957955408024192, 'min_child_weight': 1, 'gamma': 2.387776554747055, 'reg_alpha': 0.05434137594120777, 'reg_lambda': 1.8529405613069457e-05, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  82%|████████▎ | 165/200 [02:28<00:53,  1.53s/it]

[I 2025-11-10 19:05:30,346] Trial 167 pruned.

Best trial: 72. Best value: 0.719786:  83%|████████▎ | 166/200 [02:30<00:48,  1.44s/it]

[I 2025-11-10 19:05:31,555] Trial 164 finished with value: 0.7022027290448343 and parameters: {'max_depth': 10, 'learning_rate': 0.03607753801670283, 'n_estimators': 1049, 'subsample': 0.9839977645247269, 'colsample_bytree': 0.8322309396097648, 'min_child_weight': 1, 'gamma': 2.7389423421610686, 'reg_alpha': 0.0016843546017389032, 'reg_lambda': 3.8709193312570983e-07, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  84%|████████▎ | 167/200 [02:30<00:37,  1.13s/it]

[I 2025-11-10 19:05:31,966] Trial 165 finished with value: 0.718635477582846 and parameters: {'max_depth': 10, 'learning_rate': 0.036034844725874385, 'n_estimators': 1092, 'subsample': 0.9761498585933136, 'colsample_bytree': 0.8312985436043854, 'min_child_weight': 1, 'gamma': 2.770479550388867, 'reg_alpha': 0.051888138915083745, 'reg_lambda': 7.497484287057634e-06, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  84%|████████▍ | 168/200 [02:31<00:31,  1.03it/s]

[I 2025-11-10 19:05:32,577] Trial 166 finished with value: 0.7176413255360623 and parameters: {'max_depth': 10, 'learning_rate': 0.03684675311377862, 'n_estimators': 1162, 'subsample': 0.9806320753907544, 'colsample_bytree': 0.8342054268477235, 'min_child_weight': 1, 'gamma': 2.759575180092361, 'reg_alpha': 0.016942537007238967, 'reg_lambda': 6.91682931230594e-06, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  84%|████████▍ | 169/200 [02:35<01:01,  1.99s/it]

[I 2025-11-10 19:05:36,956] Trial 168 finished with value: 0.6995126705653021 and parameters: {'max_depth': 10, 'learning_rate': 0.04914657267774955, 'n_estimators': 1132, 'subsample': 0.9528979040728277, 'colsample_bytree': 0.7900072912108487, 'min_child_weight': 1, 'gamma': 2.31404204760538, 'reg_alpha': 0.0404268723916757, 'reg_lambda': 3.718547316998808e-06, 'max_delta_step': 6}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  85%|████████▌ | 170/200 [02:36<00:54,  1.83s/it]

[I 2025-11-10 19:05:38,393] Trial 169 finished with value: 0.7149512670565302 and parameters: {'max_depth': 10, 'learning_rate': 0.05020364915694208, 'n_estimators': 1139, 'subsample': 0.9528356337801656, 'colsample_bytree': 0.7963835418744281, 'min_child_weight': 1, 'gamma': 2.3073308325835993, 'reg_alpha': 0.017550067735323138, 'reg_lambda': 3.1560087464217785e-06, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  86%|████████▌ | 171/200 [02:37<00:39,  1.35s/it]

[I 2025-11-10 19:05:38,641] Trial 172 pruned.
[I 2025-11-10 19:05:38,667] Trial 170 finished with value: 0.7019688109161792 and parameters: {'max_depth': 10, 'learning_rate': 0.05007331995087832, 'n_estimators': 1130, 'subsample': 0.952830274264177, 'colsample_bytree': 0.7911391040807918, 'min_child_weight': 1, 'gamma': 2.8824582819455715, 'reg_alpha': 0.045383022787812644, 'reg_lambda': 7.354959104544473e-06, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  86%|████████▋ | 173/200 [02:38<00:28,  1.05s/it]

[I 2025-11-10 19:05:40,015] Trial 171 finished with value: 0.7071539961013645 and parameters: {'max_depth': 10, 'learning_rate': 0.049566694545697884, 'n_estimators': 1209, 'subsample': 0.9487920771474682, 'colsample_bytree': 0.8631725183275629, 'min_child_weight': 1, 'gamma': 2.830382737353133, 'reg_alpha': 0.0202391245695749, 'reg_lambda': 3.227049647024238e-06, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  87%|████████▋ | 174/200 [02:43<00:54,  2.11s/it]

[I 2025-11-10 19:05:45,352] Trial 174 finished with value: 0.708401559454191 and parameters: {'max_depth': 10, 'learning_rate': 0.05573896511479077, 'n_estimators': 1171, 'subsample': 0.9472867706104274, 'colsample_bytree': 0.8133959700865596, 'min_child_weight': 1, 'gamma': 2.1382064731362953, 'reg_alpha': 0.017173193025015156, 'reg_lambda': 2.6049133472999493e-06, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  88%|████████▊ | 175/200 [02:44<00:42,  1.69s/it]

[I 2025-11-10 19:05:45,850] Trial 175 finished with value: 0.6846783625730994 and parameters: {'max_depth': 10, 'learning_rate': 0.04062865977805118, 'n_estimators': 1184, 'subsample': 0.962500904496518, 'colsample_bytree': 0.8311414665472755, 'min_child_weight': 1, 'gamma': 2.7681653037288005, 'reg_alpha': 0.00507820357997892, 'reg_lambda': 3.197536826259625e-06, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.
[I 2025-11-10 19:05:45,890] Trial 173 finished with value: 0.6971734892787524 and parameters: {'max_depth': 10, 'learning_rate': 0.09746924372199636, 'n_estimators': 1216, 'subsample': 0.9745067869894241, 'colsample_bytree': 0.8685556373757246, 'min_child_weight': 1, 'gamma': 2.895699312330045, 'reg_alpha': 0.004839696830906038, 'reg_lambda': 6.119310075223069e-06, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  88%|████████▊ | 177/200 [02:45<00:26,  1.17s/it]

[I 2025-11-10 19:05:46,787] Trial 179 pruned.

Best trial: 72. Best value: 0.719786:  89%|████████▉ | 178/200 [02:45<00:20,  1.05it/s]

[I 2025-11-10 19:05:47,023] Trial 177 pruned.

Best trial: 72. Best value: 0.719786:  90%|████████▉ | 179/200 [02:45<00:16,  1.30it/s]

[I 2025-11-10 19:05:47,252] Trial 176 finished with value: 0.7166666666666666 and parameters: {'max_depth': 10, 'learning_rate': 0.04072370168555201, 'n_estimators': 1172, 'subsample': 0.9637832171869052, 'colsample_bytree': 0.8312918111555991, 'min_child_weight': 1, 'gamma': 2.1241891410796216, 'reg_alpha': 0.006071607906697984, 'reg_lambda': 1.1338213793274302e-05, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  90%|█████████ | 180/200 [02:45<00:12,  1.61it/s]

[I 2025-11-10 19:05:47,451] Trial 178 pruned.

Best trial: 72. Best value: 0.719786:  90%|█████████ | 181/200 [02:46<00:13,  1.43it/s]

[I 2025-11-10 19:05:48,369] Trial 181 pruned.

Best trial: 72. Best value: 0.719786:  91%|█████████ | 182/200 [02:47<00:10,  1.76it/s]

[I 2025-11-10 19:05:48,600] Trial 182 pruned.

Best trial: 72. Best value: 0.719786:  92%|█████████▏| 183/200 [02:47<00:08,  1.96it/s]

[I 2025-11-10 19:05:48,964] Trial 183 pruned.

Best trial: 72. Best value: 0.719786:  92%|█████████▏| 184/200 [02:50<00:18,  1.17s/it]

[I 2025-11-10 19:05:51,753] Trial 186 pruned.

Best trial: 72. Best value: 0.719786:  92%|█████████▎| 185/200 [02:52<00:23,  1.59s/it]

[I 2025-11-10 19:05:54,339] Trial 187 pruned.

Best trial: 72. Best value: 0.719786:  93%|█████████▎| 186/200 [02:53<00:16,  1.20s/it]

[I 2025-11-10 19:05:54,620] Trial 180 finished with value: 0.693196881091618 and parameters: {'max_depth': 10, 'learning_rate': 0.05626871913408962, 'n_estimators': 1181, 'subsample': 0.9255668892045562, 'colsample_bytree': 0.9113477974557549, 'min_child_weight': 1, 'gamma': 3.1098211117919803, 'reg_alpha': 0.007788365006250638, 'reg_lambda': 1.227414282154488e-05, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.

Best trial: 72. Best value: 0.719786:  94%|█████████▎| 187/200 [02:54<00:16,  1.27s/it]

[I 2025-11-10 19:05:56,066] Trial 184 finished with value: 0.7074074074074075 and parameters: {'max_depth': 10, 'learning_rate': 0.04045539982826386, 'n_estimators': 1248, 'subsample': 0.9425822548653431, 'colsample_bytree': 0.8481089162661358, 'min_child_weight': 1, 'gamma': 2.448897021299299, 'reg_alpha': 0.008857949154956241, 'reg_lambda': 2.5255902541632847e-06, 'max_delta_step': 7}. Best is trial 72 with value: 0.719785575048733.

Best trial: 185. Best value: 0.721365:  94%|█████████▍| 188/200 [02:55<00:12,  1.06s/it]

[I 2025-11-10 19:05:56,615] Trial 185 finished with value: 0.721364522417154 and parameters: {'max_depth': 10, 'learning_rate': 0.03313429583617478, 'n_estimators': 1257, 'subsample': 0.9442174142277765, 'colsample_bytree': 0.844108456823389, 'min_child_weight': 1, 'gamma': 2.4449119971292386, 'reg_alpha': 0.06413050883890378, 'reg_lambda': 2.0499779327818634e-06, 'max_delta_step': 7}. Best is trial 185 with value: 0.721364522417154.

Best trial: 185. Best value: 0.721365:  94%|█████████▍| 189/200 [02:56<00:11,  1.01s/it]

[I 2025-11-10 19:05:57,519] Trial 190 pruned.
[I 2025-11-10 19:05:57,579] Trial 189 pruned.

Best trial: 185. Best value: 0.721365:  96%|█████████▌| 191/200 [02:57<00:07,  1.28it/s]

[I 2025-11-10 19:05:58,553] Trial 193 pruned.

Best trial: 185. Best value: 0.721365:  96%|█████████▌| 192/200 [02:57<00:06,  1.30it/s]

[I 2025-11-10 19:05:59,274] Trial 192 pruned.

Best trial: 185. Best value: 0.721365:  96%|█████████▋| 193/200 [02:59<00:06,  1.01it/s]

[I 2025-11-10 19:06:00,890] Trial 195 pruned.

Best trial: 185. Best value: 0.721365:  97%|█████████▋| 194/200 [03:00<00:05,  1.06it/s]

[I 2025-11-10 19:06:01,718] Trial 188 finished with value: 0.7065497076023391 and parameters: {'max_depth': 10, 'learning_rate': 0.05301378260796114, 'n_estimators': 1144, 'subsample': 0.9699874603701395, 'colsample_bytree': 0.8335048168439534, 'min_child_weight': 1, 'gamma': 2.482886242601477, 'reg_alpha': 0.02707517537851263, 'reg_lambda': 1.9592514847775396e-06, 'max_delta_step': 6}. Best is trial 185 with value: 0.721364522417154.

Best trial: 185. Best value: 0.721365:  98%|█████████▊| 195/200 [03:00<00:04,  1.24it/s]

[I 2025-11-10 19:06:02,172] Trial 196 pruned.

Best trial: 185. Best value: 0.721365:  98%|█████████▊| 196/200 [03:02<00:04,  1.06s/it]

[I 2025-11-10 19:06:03,844] Trial 191 finished with value: 0.6938206627680312 and parameters: {'max_depth': 10, 'learning_rate': 0.08564359206379027, 'n_estimators': 1139, 'subsample': 0.9589990195343463, 'colsample_bytree': 0.8323294327827593, 'min_child_weight': 1, 'gamma': 2.3325539829257305, 'reg_alpha': 0.05745931863270307, 'reg_lambda': 5.561509276343259e-06, 'max_delta_step': 6}. Best is trial 185 with value: 0.721364522417154.

Best trial: 185. Best value: 0.721365:  98%|█████████▊| 197/200 [03:03<00:03,  1.10s/it]

[I 2025-11-10 19:06:05,071] Trial 199 pruned.
[I 2025-11-10 19:06:05,147] Trial 198 pruned.

Best trial: 185. Best value: 0.721365: 100%|█████████▉| 199/200 [03:04<00:00,  1.15it/s]

[I 2025-11-10 19:06:06,258] Trial 194 finished with value: 0.7158089668615985 and parameters: {'max_depth': 10, 'learning_rate': 0.053208301951764216, 'n_estimators': 1219, 'subsample': 0.979434583288656, 'colsample_bytree': 0.8584000100262089, 'min_child_weight': 1, 'gamma': 2.5114700146011186, 'reg_alpha': 0.05460337937763791, 'reg_lambda': 7.877138400421495e-07, 'max_delta_step': 7}. Best is trial 185 with value: 0.721364522417154.

Best trial: 185. Best value: 0.721365: 100%|██████████| 200/200 [03:06<00:00,  1.07it/s]

[I 2025-11-10 19:06:08,036] Trial 197 finished with value: 0.7098830409356726 and parameters: {'max_depth': 10, 'learning_rate': 0.03865379408465556, 'n_estimators': 1093, 'subsample': 0.9809947779558841, 'colsample_bytree': 0.8402555364130974, 'min_child_weight': 1, 'gamma': 1.82374218385391, 'reg_alpha': 0.05513609724789764, 'reg_lambda': 3.6784225809117716e-06, 'max_delta_step': 7}. Best is trial 185 with value: 0.721364522417154.

[I 2025-11-10 19:06:09,580] A new study created in memory with name: 19_1_roc_auc
Best trial: 1. Best value: 0.5:   0%|          | 1/200 [00:02<07:03,  2.13s/it]

[I 2025-11-10 19:06:11,707] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.03769482541198023, 'n_estimators': 563, 'subsample': 0.8375430767203994, 'colsample_bytree': 0.5036025423847286, 'min_child_weight': 7, 'gamma': 3.4578148964480753, 'reg_alpha': 8.376148582880307e-06, 'reg_lambda': 0.5092237133942554, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 3. Best value: 0.562484:   1%|          | 2/200 [00:02<04:19,  1.31s/it]

[I 2025-11-10 19:06:12,444] Trial 3 finished with value: 0.5624836601307189 and parameters: {'max_depth': 8, 'learning_rate': 0.06394023237375944, 'n_estimators': 543, 'subsample': 0.6829567687838665, 'colsample_bytree': 0.68177695425481, 'min_child_weight': 2, 'gamma': 3.317707634418723, 'reg_alpha': 7.866823597533674e-08, 'reg_lambda': 2.168861629070652e-06, 'max_delta_step': 5}. Best is trial 3 with value: 0.5624836601307189.

Best trial: 3. Best value: 0.562484:   2%|▏         | 3/200 [00:04<04:04,  1.24s/it]

[I 2025-11-10 19:06:13,596] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.08868052891067797, 'n_estimators': 496, 'subsample': 0.9807711366787611, 'colsample_bytree': 0.5356909853179781, 'min_child_weight': 7, 'gamma': 3.6367056909686464, 'reg_alpha': 0.0004248115126432667, 'reg_lambda': 0.2600130501610225, 'max_delta_step': 2}. Best is trial 3 with value: 0.5624836601307189.

Best trial: 3. Best value: 0.562484:   2%|▏         | 4/200 [00:05<04:44,  1.45s/it]

[I 2025-11-10 19:06:15,370] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.01433814725288405, 'n_estimators': 1481, 'subsample': 0.5307021489362675, 'colsample_bytree': 0.69046355738919, 'min_child_weight': 6, 'gamma': 1.7798365957588307, 'reg_alpha': 0.0007770368080400497, 'reg_lambda': 5.262224045754352, 'max_delta_step': 6}. Best is trial 3 with value: 0.5624836601307189.

Best trial: 2. Best value: 0.590458:   2%|▎         | 5/200 [00:06<03:34,  1.10s/it]

[I 2025-11-10 19:06:15,848] Trial 2 finished with value: 0.5904575163398692 and parameters: {'max_depth': 9, 'learning_rate': 0.061786800381159634, 'n_estimators': 1337, 'subsample': 0.6322688255041284, 'colsample_bytree': 0.7906289524839878, 'min_child_weight': 2, 'gamma': 1.401757249583628, 'reg_alpha': 0.00014307553583013435, 'reg_lambda': 0.00047536702783906675, 'max_delta_step': 10}. Best is trial 2 with value: 0.5904575163398692.

Best trial: 2. Best value: 0.590458:   3%|▎         | 6/200 [00:06<02:45,  1.17it/s]

[I 2025-11-10 19:06:16,229] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.06860645569626439, 'n_estimators': 970, 'subsample': 0.516430570047588, 'colsample_bytree': 0.5657317802601649, 'min_child_weight': 4, 'gamma': 4.6104239348595915, 'reg_alpha': 0.6467916807141348, 'reg_lambda': 0.0017058245444216628, 'max_delta_step': 10}. Best is trial 2 with value: 0.5904575163398692.

Best trial: 2. Best value: 0.590458:   4%|▎         | 7/200 [00:06<02:03,  1.56it/s]

[I 2025-11-10 19:06:16,432] Trial 6 finished with value: 0.5895424836601307 and parameters: {'max_depth': 5, 'learning_rate': 0.14241173659306552, 'n_estimators': 750, 'subsample': 0.6804801632577725, 'colsample_bytree': 0.52237096600976, 'min_child_weight': 4, 'gamma': 2.267017535087255, 'reg_alpha': 0.0025829932412638435, 'reg_lambda': 5.157440128505301e-06, 'max_delta_step': 5}. Best is trial 2 with value: 0.5904575163398692.

Best trial: 7. Best value: 0.596209:   4%|▍         | 8/200 [00:09<03:42,  1.16s/it]

[I 2025-11-10 19:06:18,696] Trial 7 finished with value: 0.5962091503267973 and parameters: {'max_depth': 9, 'learning_rate': 0.09962545115976662, 'n_estimators': 779, 'subsample': 0.6695468351360179, 'colsample_bytree': 0.9463604444555591, 'min_child_weight': 3, 'gamma': 1.9847325329161603, 'reg_alpha': 0.0009709162804904188, 'reg_lambda': 1.774390378081754, 'max_delta_step': 9}. Best is trial 7 with value: 0.5962091503267973.

Best trial: 7. Best value: 0.596209:   4%|▍         | 9/200 [00:10<04:19,  1.36s/it]

[I 2025-11-10 19:06:20,499] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0906721589061207, 'n_estimators': 1175, 'subsample': 0.7945588826924721, 'colsample_bytree': 0.7388783037218258, 'min_child_weight': 5, 'gamma': 0.3018590923203912, 'reg_alpha': 0.06647272332077682, 'reg_lambda': 0.003193261672650922, 'max_delta_step': 3}. Best is trial 7 with value: 0.5962091503267973.

Best trial: 7. Best value: 0.596209:   5%|▌         | 10/200 [00:11<03:19,  1.05s/it]

[I 2025-11-10 19:06:20,860] Trial 9 finished with value: 0.5416339869281044 and parameters: {'max_depth': 3, 'learning_rate': 0.07762894789831652, 'n_estimators': 852, 'subsample': 0.8960708559083514, 'colsample_bytree': 0.7955499600381087, 'min_child_weight': 2, 'gamma': 4.011989733871176, 'reg_alpha': 0.00126209342658646, 'reg_lambda': 3.5305831839990225e-07, 'max_delta_step': 4}. Best is trial 7 with value: 0.5962091503267973.

Best trial: 7. Best value: 0.596209:   6%|▌         | 11/200 [00:11<02:39,  1.19it/s]

[I 2025-11-10 19:06:21,231] Trial 11 pruned.

Best trial: 7. Best value: 0.596209:   6%|▌         | 12/200 [00:11<02:04,  1.51it/s]

[I 2025-11-10 19:06:21,477] Trial 13 pruned.

Best trial: 12. Best value: 0.664967:   6%|▋         | 13/200 [00:12<02:20,  1.34it/s]

[I 2025-11-10 19:06:22,427] Trial 8 finished with value: 0.5596078431372549 and parameters: {'max_depth': 5, 'learning_rate': 0.022154058957432055, 'n_estimators': 989, 'subsample': 0.8302046568333166, 'colsample_bytree': 0.7025887140764835, 'min_child_weight': 1, 'gamma': 1.2997149395635983, 'reg_alpha': 1.7917014348755303e-08, 'reg_lambda': 2.6208391990583996e-07, 'max_delta_step': 2}. Best is trial 7 with value: 0.5962091503267973.
[I 2025-11-10 19:06:22,505] Trial 12 finished with value: 0.6649673202614379 and parameters: {'max_depth': 6, 'learning_rate': 0.19495281417260585, 'n_estimators': 537, 'subsample': 0.650205810435221, 'colsample_bytree': 0.6337566175976792, 'min_child_weight': 4, 'gamma': 3.5740506227075053, 'reg_alpha': 1.6267497861454076e-06, 'reg_lambda': 1.0928947652409748, 'max_delta_step': 7}. Best is trial 12 with value: 0.6649673202614379.

Best trial: 12. Best value: 0.664967:   8%|▊         | 15/200 [00:13<01:40,  1.84it/s]

[I 2025-11-10 19:06:23,042] Trial 14 finished with value: 0.5031372549019608 and parameters: {'max_depth': 10, 'learning_rate': 0.2686273413276987, 'n_estimators': 265, 'subsample': 0.6567081797930994, 'colsample_bytree': 0.9983279350381762, 'min_child_weight': 1, 'gamma': 1.269052979277123, 'reg_alpha': 6.86049114746942e-06, 'reg_lambda': 8.14244386866225e-05, 'max_delta_step': 10}. Best is trial 12 with value: 0.6649673202614379.

Best trial: 12. Best value: 0.664967:   8%|▊         | 16/200 [00:13<01:26,  2.13it/s]

[I 2025-11-10 19:06:23,287] Trial 15 pruned.

Best trial: 12. Best value: 0.664967:   8%|▊         | 17/200 [00:14<01:38,  1.85it/s]

[I 2025-11-10 19:06:24,023] Trial 17 finished with value: 0.6014379084967321 and parameters: {'max_depth': 10, 'learning_rate': 0.29491624369288816, 'n_estimators': 323, 'subsample': 0.7337118416156814, 'colsample_bytree': 0.9828353456063438, 'min_child_weight': 4, 'gamma': 2.6512458141039845, 'reg_alpha': 1.759931187519505e-05, 'reg_lambda': 0.04291259122728461, 'max_delta_step': 8}. Best is trial 12 with value: 0.6649673202614379.

Best trial: 12. Best value: 0.664967:   9%|▉         | 18/200 [00:14<01:29,  2.04it/s]

[I 2025-11-10 19:06:24,384] Trial 20 pruned.

Best trial: 12. Best value: 0.664967:  10%|▉         | 19/200 [00:15<01:31,  1.98it/s]

[I 2025-11-10 19:06:24,922] Trial 21 pruned.

Best trial: 12. Best value: 0.664967:  10%|█         | 20/200 [00:15<01:22,  2.17it/s]

[I 2025-11-10 19:06:25,277] Trial 22 pruned.

Best trial: 12. Best value: 0.664967:  10%|█         | 21/200 [00:16<01:28,  2.02it/s]

[I 2025-11-10 19:06:25,854] Trial 18 finished with value: 0.5855555555555555 and parameters: {'max_depth': 7, 'learning_rate': 0.15108747478082885, 'n_estimators': 649, 'subsample': 0.7521131006656658, 'colsample_bytree': 0.61445443673769, 'min_child_weight': 4, 'gamma': 2.565019784283063, 'reg_alpha': 0.03612128809197238, 'reg_lambda': 0.034796098704682636, 'max_delta_step': 8}. Best is trial 12 with value: 0.6649673202614379.

Best trial: 12. Best value: 0.664967:  11%|█         | 22/200 [00:16<01:16,  2.34it/s]

[I 2025-11-10 19:06:26,119] Trial 19 finished with value: 0.6151633986928104 and parameters: {'max_depth': 7, 'learning_rate': 0.15257688618149404, 'n_estimators': 669, 'subsample': 0.7389765018430857, 'colsample_bytree': 0.6107419359949569, 'min_child_weight': 4, 'gamma': 2.587911004933871, 'reg_alpha': 0.01686888599342293, 'reg_lambda': 0.03207578867855317, 'max_delta_step': 8}. Best is trial 12 with value: 0.6649673202614379.

Best trial: 12. Best value: 0.664967:  12%|█▏        | 23/200 [00:16<01:05,  2.71it/s]

[I 2025-11-10 19:06:26,347] Trial 24 pruned.

Best trial: 12. Best value: 0.664967:  12%|█▏        | 24/200 [00:17<00:59,  2.97it/s]

[I 2025-11-10 19:06:26,608] Trial 25 pruned.

Best trial: 12. Best value: 0.664967:  12%|█▎        | 25/200 [00:17<00:57,  3.04it/s]

[I 2025-11-10 19:06:26,920] Trial 27 pruned.

Best trial: 12. Best value: 0.664967:  13%|█▎        | 26/200 [00:17<01:03,  2.73it/s]

[I 2025-11-10 19:06:27,375] Trial 23 finished with value: 0.5734640522875818 and parameters: {'max_depth': 3, 'learning_rate': 0.13705165481719417, 'n_estimators': 406, 'subsample': 0.7746943292979884, 'colsample_bytree': 0.6079498096088896, 'min_child_weight': 3, 'gamma': 4.368624578227443, 'reg_alpha': 1.4146003032932982e-07, 'reg_lambda': 5.740746038985255, 'max_delta_step': 0}. Best is trial 12 with value: 0.6649673202614379.
[I 2025-11-10 19:06:27,409] Trial 26 pruned.

Best trial: 12. Best value: 0.664967:  14%|█▍        | 28/200 [00:18<01:21,  2.12it/s]

[I 2025-11-10 19:06:28,569] Trial 16 finished with value: 0.6359477124183006 and parameters: {'max_depth': 10, 'learning_rate': 0.17875736820456214, 'n_estimators': 1337, 'subsample': 0.6653365633987293, 'colsample_bytree': 0.9386322526375542, 'min_child_weight': 3, 'gamma': 1.1812739096486122, 'reg_alpha': 2.3806295652492186e-05, 'reg_lambda': 7.614570427723879e-05, 'max_delta_step': 10}. Best is trial 12 with value: 0.6649673202614379.

Best trial: 12. Best value: 0.664967:  14%|█▍        | 29/200 [00:19<01:38,  1.73it/s]

[I 2025-11-10 19:06:29,466] Trial 31 pruned.

Best trial: 28. Best value: 0.680654:  15%|█▌        | 30/200 [00:20<01:23,  2.04it/s]

[I 2025-11-10 19:06:29,709] Trial 28 finished with value: 0.6806535947712419 and parameters: {'max_depth': 4, 'learning_rate': 0.13158874600448087, 'n_estimators': 640, 'subsample': 0.8786090535714454, 'colsample_bytree': 0.7445554989373149, 'min_child_weight': 5, 'gamma': 3.962494671214909, 'reg_alpha': 2.8649290410105756e-07, 'reg_lambda': 0.006379531368727192, 'max_delta_step': 6}. Best is trial 28 with value: 0.6806535947712419.

Best trial: 30. Best value: 0.686536:  16%|█▌        | 32/200 [00:20<00:59,  2.80it/s]

[I 2025-11-10 19:06:30,047] Trial 29 finished with value: 0.675032679738562 and parameters: {'max_depth': 8, 'learning_rate': 0.04402100005404259, 'n_estimators': 639, 'subsample': 0.8634633529771324, 'colsample_bytree': 0.7233633798382372, 'min_child_weight': 5, 'gamma': 3.037712914162819, 'reg_alpha': 2.062990895628752e-06, 'reg_lambda': 0.007908973435359457, 'max_delta_step': 9}. Best is trial 28 with value: 0.6806535947712419.
[I 2025-11-10 19:06:30,166] Trial 30 finished with value: 0.6865359477124183 and parameters: {'max_depth': 8, 'learning_rate': 0.29154299956286783, 'n_estimators': 644, 'subsample': 0.8763066683908518, 'colsample_bytree': 0.7444415502251458, 'min_child_weight': 5, 'gamma': 3.0899812482292424, 'reg_alpha': 0.005924777497731882, 'reg_lambda': 0.003062176340300783, 'max_delta_step': 9}. Best is trial 30 with value: 0.6865359477124183.

Best trial: 30. Best value: 0.686536:  16%|█▋        | 33/200 [00:21<01:07,  2.47it/s]

[I 2025-11-10 19:06:30,695] Trial 35 pruned.
[I 2025-11-10 19:06:30,715] Trial 32 pruned.

Best trial: 30. Best value: 0.686536:  18%|█▊        | 35/200 [00:21<00:50,  3.24it/s]

[I 2025-11-10 19:06:31,076] Trial 33 pruned.

Best trial: 30. Best value: 0.686536:  18%|█▊        | 37/200 [00:21<00:49,  3.31it/s]

[I 2025-11-10 19:06:31,358] Trial 34 pruned.
[I 2025-11-10 19:06:31,414] Trial 36 pruned.
[I 2025-11-10 19:06:31,430] Trial 37 pruned.

Best trial: 30. Best value: 0.686536:  20%|██        | 40/200 [00:22<00:34,  4.66it/s]

[I 2025-11-10 19:06:31,831] Trial 38 pruned.
[I 2025-11-10 19:06:31,985] Trial 40 pruned.
[I 2025-11-10 19:06:31,991] Trial 41 pruned.

Best trial: 30. Best value: 0.686536:  21%|██        | 42/200 [00:22<00:26,  5.92it/s]

[I 2025-11-10 19:06:32,165] Trial 39 pruned.

Best trial: 30. Best value: 0.686536:  22%|██▏       | 43/200 [00:22<00:31,  4.91it/s]

[I 2025-11-10 19:06:32,500] Trial 44 pruned.

Best trial: 30. Best value: 0.686536:  22%|██▏       | 44/200 [00:23<00:36,  4.27it/s]

[I 2025-11-10 19:06:32,842] Trial 43 pruned.

Best trial: 30. Best value: 0.686536:  22%|██▎       | 45/200 [00:24<00:57,  2.70it/s]

[I 2025-11-10 19:06:33,641] Trial 46 pruned.

Best trial: 42. Best value: 0.688431:  24%|██▎       | 47/200 [00:24<00:49,  3.06it/s]

[I 2025-11-10 19:06:34,128] Trial 47 pruned.
[I 2025-11-10 19:06:34,243] Trial 42 finished with value: 0.6884313725490195 and parameters: {'max_depth': 9, 'learning_rate': 0.06283783944828851, 'n_estimators': 532, 'subsample': 0.9996656715970837, 'colsample_bytree': 0.7601198230539635, 'min_child_weight': 5, 'gamma': 3.7374284584349486, 'reg_alpha': 2.9651019998446275e-07, 'reg_lambda': 0.15602110987561893, 'max_delta_step': 5}. Best is trial 42 with value: 0.6884313725490195.

Best trial: 42. Best value: 0.688431:  24%|██▍       | 48/200 [00:24<00:47,  3.22it/s]

[I 2025-11-10 19:06:34,517] Trial 48 pruned.

Best trial: 42. Best value: 0.688431:  24%|██▍       | 49/200 [00:27<02:18,  1.09it/s]

[I 2025-11-10 19:06:36,969] Trial 51 finished with value: 0.613921568627451 and parameters: {'max_depth': 8, 'learning_rate': 0.04048453213209365, 'n_estimators': 503, 'subsample': 0.9706377185694202, 'colsample_bytree': 0.7971423999901219, 'min_child_weight': 4, 'gamma': 4.006123872772359, 'reg_alpha': 3.505075348187655e-07, 'reg_lambda': 0.008745314975174329, 'max_delta_step': 5}. Best is trial 42 with value: 0.6884313725490195.

Best trial: 42. Best value: 0.688431:  26%|██▌       | 51/200 [00:28<01:32,  1.61it/s]

[I 2025-11-10 19:06:37,572] Trial 50 finished with value: 0.6752941176470588 and parameters: {'max_depth': 3, 'learning_rate': 0.04269952590954595, 'n_estimators': 813, 'subsample': 0.9572168590224652, 'colsample_bytree': 0.6751350470849544, 'min_child_weight': 5, 'gamma': 4.481181235901456, 'reg_alpha': 6.146112311914448e-07, 'reg_lambda': 0.012480509715442201, 'max_delta_step': 4}. Best is trial 42 with value: 0.6884313725490195.
[I 2025-11-10 19:06:37,684] Trial 49 finished with value: 0.6164052287581698 and parameters: {'max_depth': 3, 'learning_rate': 0.09473268748532629, 'n_estimators': 822, 'subsample': 0.8633314674313597, 'colsample_bytree': 0.6577450860522231, 'min_child_weight': 4, 'gamma': 4.350165801425111, 'reg_alpha': 2.720097788263661e-07, 'reg_lambda': 0.01130949057266791, 'max_delta_step': 4}. Best is trial 42 with value: 0.6884313725490195.

Best trial: 42. Best value: 0.688431:  26%|██▌       | 51/200 [00:28<01:32,  1.61it/s]

[I 2025-11-10 19:06:37,766] Trial 45 finished with value: 0.5613071895424837 and parameters: {'max_depth': 9, 'learning_rate': 0.19148195036530952, 'n_estimators': 967, 'subsample': 0.9800558075509512, 'colsample_bytree': 0.7682285745164817, 'min_child_weight': 2, 'gamma': 2.3036511919711327, 'reg_alpha': 0.00024546476087141094, 'reg_lambda': 0.00012374418675074468, 'max_delta_step': 10}. Best is trial 42 with value: 0.6884313725490195.

Best trial: 55. Best value: 0.692222:  27%|██▋       | 54/200 [00:30<01:46,  1.37it/s]

[I 2025-11-10 19:06:40,228] Trial 55 finished with value: 0.6922222222222222 and parameters: {'max_depth': 3, 'learning_rate': 0.06301114668386512, 'n_estimators': 608, 'subsample': 0.9546753840540921, 'colsample_bytree': 0.7340966485241099, 'min_child_weight': 5, 'gamma': 3.980238046284237, 'reg_alpha': 3.81360870145327e-08, 'reg_lambda': 0.19931370089568493, 'max_delta_step': 5}. Best is trial 55 with value: 0.6922222222222222.
[I 2025-11-10 19:06:40,376] Trial 52 finished with value: 0.6727450980392157 and parameters: {'max_depth': 5, 'learning_rate': 0.08684562413691503, 'n_estimators': 819, 'subsample': 0.9620382164980101, 'colsample_bytree': 0.7274272605302909, 'min_child_weight': 5, 'gamma': 3.4195103623618994, 'reg_alpha': 0.0030470117201347306, 'reg_lambda': 0.013894721747338724, 'max_delta_step': 5}. Best is trial 55 with value: 0.6922222222222222.

Best trial: 55. Best value: 0.692222:  27%|██▋       | 54/200 [00:30<01:46,  1.37it/s]

[I 2025-11-10 19:06:40,472] Trial 54 finished with value: 0.6793464052287581 and parameters: {'max_depth': 3, 'learning_rate': 0.059306067030252374, 'n_estimators': 616, 'subsample': 0.9971060623071577, 'colsample_bytree': 0.7293172423024694, 'min_child_weight': 5, 'gamma': 3.4441583862310163, 'reg_alpha': 2.1100014193490395e-08, 'reg_lambda': 0.32170302996097483, 'max_delta_step': 3}. Best is trial 55 with value: 0.6922222222222222.

Best trial: 53. Best value: 0.693007:  28%|██▊       | 56/200 [00:31<01:25,  1.68it/s]

[I 2025-11-10 19:06:41,183] Trial 53 finished with value: 0.6930065359477123 and parameters: {'max_depth': 3, 'learning_rate': 0.060368895533781566, 'n_estimators': 820, 'subsample': 0.9958028312492552, 'colsample_bytree': 0.7253049340757907, 'min_child_weight': 5, 'gamma': 4.334340536459309, 'reg_alpha': 2.2596879627786514e-08, 'reg_lambda': 0.0015482629478433645, 'max_delta_step': 3}. Best is trial 53 with value: 0.6930065359477123.

Best trial: 53. Best value: 0.693007:  28%|██▊       | 57/200 [00:32<01:26,  1.65it/s]

[I 2025-11-10 19:06:41,824] Trial 59 pruned.

Best trial: 53. Best value: 0.693007:  29%|██▉       | 58/200 [00:33<01:44,  1.36it/s]

[I 2025-11-10 19:06:42,966] Trial 56 finished with value: 0.6929411764705882 and parameters: {'max_depth': 3, 'learning_rate': 0.06164135195176733, 'n_estimators': 619, 'subsample': 0.9591786642558219, 'colsample_bytree': 0.7294514716823144, 'min_child_weight': 5, 'gamma': 4.542361866529426, 'reg_alpha': 2.7651681440312435e-08, 'reg_lambda': 0.0012906033238346078, 'max_delta_step': 3}. Best is trial 53 with value: 0.6930065359477123.

Best trial: 53. Best value: 0.693007:  30%|██▉       | 59/200 [00:33<01:23,  1.68it/s]

[I 2025-11-10 19:06:43,160] Trial 57 finished with value: 0.6896078431372549 and parameters: {'max_depth': 3, 'learning_rate': 0.05960478851596928, 'n_estimators': 618, 'subsample': 0.9952432658018109, 'colsample_bytree': 0.6821669557850544, 'min_child_weight': 5, 'gamma': 4.56085614213953, 'reg_alpha': 1.021325597898839e-08, 'reg_lambda': 0.23410306109048012, 'max_delta_step': 3}. Best is trial 53 with value: 0.6930065359477123.

Best trial: 53. Best value: 0.693007:  30%|███       | 61/200 [00:34<00:59,  2.35it/s]

[I 2025-11-10 19:06:43,483] Trial 58 finished with value: 0.6790196078431372 and parameters: {'max_depth': 3, 'learning_rate': 0.05980675892154468, 'n_estimators': 691, 'subsample': 0.9928054934563112, 'colsample_bytree': 0.6832098693481361, 'min_child_weight': 5, 'gamma': 4.6846666011901, 'reg_alpha': 3.6719657933937066e-08, 'reg_lambda': 0.251890637188849, 'max_delta_step': 3}. Best is trial 53 with value: 0.6930065359477123.
[I 2025-11-10 19:06:43,655] Trial 61 pruned.

Best trial: 53. Best value: 0.693007:  31%|███       | 62/200 [00:34<00:49,  2.78it/s]

[I 2025-11-10 19:06:43,852] Trial 62 pruned.

Best trial: 53. Best value: 0.693007:  32%|███▏      | 63/200 [00:34<00:51,  2.64it/s]

[I 2025-11-10 19:06:44,278] Trial 64 pruned.

Best trial: 53. Best value: 0.693007:  32%|███▏      | 64/200 [00:34<00:44,  3.08it/s]

[I 2025-11-10 19:06:44,469] Trial 65 pruned.
[I 2025-11-10 19:06:44,563] Trial 60 finished with value: 0.6749673202614378 and parameters: {'max_depth': 3, 'learning_rate': 0.06113046590107916, 'n_estimators': 600, 'subsample': 0.9335269021460874, 'colsample_bytree': 0.6859418732720994, 'min_child_weight': 5, 'gamma': 3.905922626616831, 'reg_alpha': 1.1048135406942548e-08, 'reg_lambda': 0.3794193559318277, 'max_delta_step': 2}. Best is trial 53 with value: 0.6930065359477123.

Best trial: 53. Best value: 0.693007:  33%|███▎      | 66/200 [00:35<00:40,  3.30it/s]

[I 2025-11-10 19:06:45,027] Trial 68 pruned.

Best trial: 53. Best value: 0.693007:  34%|███▎      | 67/200 [00:36<00:58,  2.27it/s]

[I 2025-11-10 19:06:45,891] Trial 63 finished with value: 0.6090196078431372 and parameters: {'max_depth': 4, 'learning_rate': 0.07576780947498102, 'n_estimators': 449, 'subsample': 0.9370626426252604, 'colsample_bytree': 0.8084940587442627, 'min_child_weight': 4, 'gamma': 4.9000134649664595, 'reg_alpha': 1.1980523108443441e-08, 'reg_lambda': 0.0013512552656496357, 'max_delta_step': 2}. Best is trial 53 with value: 0.6930065359477123.

Best trial: 66. Best value: 0.693464:  34%|███▍      | 69/200 [00:37<00:56,  2.33it/s]

[I 2025-11-10 19:06:46,652] Trial 66 finished with value: 0.6934640522875817 and parameters: {'max_depth': 4, 'learning_rate': 0.10358082319449716, 'n_estimators': 513, 'subsample': 0.9651725953307249, 'colsample_bytree': 0.7486716715418248, 'min_child_weight': 5, 'gamma': 4.952989301573882, 'reg_alpha': 9.164981881535258e-08, 'reg_lambda': 0.05907594880683506, 'max_delta_step': 3}. Best is trial 66 with value: 0.6934640522875817.
[I 2025-11-10 19:06:46,825] Trial 67 finished with value: 0.563921568627451 and parameters: {'max_depth': 4, 'learning_rate': 0.06466397672405472, 'n_estimators': 524, 'subsample': 0.9702217230045466, 'colsample_bytree': 0.7489187310924856, 'min_child_weight': 5, 'gamma': 4.884807938375125, 'reg_alpha': 0.15669636844042373, 'reg_lambda': 2.9311310626019935, 'max_delta_step': 3}. Best is trial 66 with value: 0.6934640522875817.

Best trial: 66. Best value: 0.693464:  35%|███▌      | 70/200 [00:37<00:49,  2.62it/s]

[I 2025-11-10 19:06:47,079] Trial 71 pruned.
[I 2025-11-10 19:06:47,085] Trial 69 finished with value: 0.6812418300653594 and parameters: {'max_depth': 3, 'learning_rate': 0.03626240628401289, 'n_estimators': 454, 'subsample': 0.9720993125238934, 'colsample_bytree': 0.7403185540942229, 'min_child_weight': 5, 'gamma': 4.505548795701499, 'reg_alpha': 0.2247757820896715, 'reg_lambda': 0.025172809849858372, 'max_delta_step': 4}. Best is trial 66 with value: 0.6934640522875817.

Best trial: 66. Best value: 0.693464:  36%|███▌      | 72/200 [00:37<00:34,  3.70it/s]

[I 2025-11-10 19:06:47,344] Trial 72 pruned.

Best trial: 66. Best value: 0.693464:  36%|███▋      | 73/200 [00:38<00:51,  2.48it/s]

[I 2025-11-10 19:06:48,169] Trial 70 finished with value: 0.6918300653594771 and parameters: {'max_depth': 3, 'learning_rate': 0.06631638987910794, 'n_estimators': 486, 'subsample': 0.9605729338214204, 'colsample_bytree': 0.7456279459315268, 'min_child_weight': 5, 'gamma': 4.510654886901817, 'reg_alpha': 0.24677009024327318, 'reg_lambda': 0.059084231648478404, 'max_delta_step': 4}. Best is trial 66 with value: 0.6934640522875817.

[I 2025-11-10 19:06:49,184] Trial 75 finished with value: 0.6826143790849672 and parameters: {'max_depth': 3, 'learning_rate': 0.04664076149812552, 'n_estimators': 413, 'subsample': 0.9793678059507829, 'colsample_bytree': 0.740281785391203, 'min_child_weight': 5, 'gamma': 4.495943163878356, 'reg_alpha': 0.2075076402977619, 'reg_lambda': 0.01762324077454172, 'max_delta_step': 3}. Best is trial 66 with value: 0.6934640522875817.
[I 2025-11-10 19:06:49,353] Trial 73 finished with value: 0.68359477124183 and parameters: {'max_depth': 3, 'learning_rate': 0.10325362196259766, 'n_estimators': 483, 'subsample': 0.9816595144903959, 'colsample_bytree': 0.7406110740171958, 'min_child_weight': 5, 'gamma': 4.528689026758508, 'reg_alpha': 0.21707838137201735, 'reg_lambda': 0.02322740905778779, 'max_delta_step': 5}. Best is trial 66 with value: 0.6934640522875817.

Best trial: 66. Best value: 0.693464:  38%|███▊      | 75/200 [00:39<00:56,  2.20it/s]

[I 2025-11-10 19:06:49,367] Trial 74 finished with value: 0.6874509803921568 and parameters: {'max_depth': 3, 'learning_rate': 0.10307745042837965, 'n_estimators': 482, 'subsample': 0.9824458561846708, 'colsample_bytree': 0.7685056075566082, 'min_child_weight': 5, 'gamma': 4.541983148747731, 'reg_alpha': 0.9650223263175917, 'reg_lambda': 0.06313782184736623, 'max_delta_step': 5}. Best is trial 66 with value: 0.6934640522875817.

Best trial: 66. Best value: 0.693464:  39%|███▉      | 78/200 [00:40<00:33,  3.69it/s]

[I 2025-11-10 19:06:49,597] Trial 76 finished with value: 0.669607843137255 and parameters: {'max_depth': 3, 'learning_rate': 0.046868034966432603, 'n_estimators': 280, 'subsample': 0.98297798395585, 'colsample_bytree': 0.7164926981392573, 'min_child_weight': 5, 'gamma': 4.34561132791398, 'reg_alpha': 1.4068989778838847, 'reg_lambda': 0.018652830770975792, 'max_delta_step': 5}. Best is trial 66 with value: 0.6934640522875817.
[I 2025-11-10 19:06:49,741] Trial 79 pruned.

Best trial: 66. Best value: 0.693464:  40%|████      | 80/200 [00:40<00:24,  4.80it/s]

[I 2025-11-10 19:06:49,806] Trial 78 pruned.
[I 2025-11-10 19:06:49,968] Trial 77 pruned.

Best trial: 66. Best value: 0.693464:  40%|████      | 81/200 [00:40<00:25,  4.61it/s]

[I 2025-11-10 19:06:50,218] Trial 82 pruned.
[I 2025-11-10 19:06:50,239] Trial 80 pruned.

Best trial: 66. Best value: 0.693464:  42%|████▏     | 84/200 [00:40<00:18,  6.29it/s]

[I 2025-11-10 19:06:50,434] Trial 83 pruned.
[I 2025-11-10 19:06:50,539] Trial 81 pruned.

Best trial: 66. Best value: 0.693464:  42%|████▎     | 85/200 [00:41<00:30,  3.78it/s]

[I 2025-11-10 19:06:51,141] Trial 87 pruned.

Best trial: 66. Best value: 0.693464:  43%|████▎     | 86/200 [00:43<01:21,  1.40it/s]

[I 2025-11-10 19:06:53,170] Trial 85 finished with value: 0.6844444444444443 and parameters: {'max_depth': 4, 'learning_rate': 0.05565436553686257, 'n_estimators': 649, 'subsample': 0.9492934980208915, 'colsample_bytree': 0.7628148432085344, 'min_child_weight': 5, 'gamma': 4.07475111440272, 'reg_alpha': 0.008954418308450481, 'reg_lambda': 0.8994842350550287, 'max_delta_step': 3}. Best is trial 66 with value: 0.6934640522875817.
[I 2025-11-10 19:06:53,177] Trial 84 finished with value: 0.6822222222222222 and parameters: {'max_depth': 4, 'learning_rate': 0.09197969044333666, 'n_estimators': 654, 'subsample': 0.947647016751369, 'colsample_bytree': 0.7663579039476713, 'min_child_weight': 5, 'gamma': 4.989695994985062, 'reg_alpha': 0.08317512363328386, 'reg_lambda': 0.20607155893476206, 'max_delta_step': 3}. Best is trial 66 with value: 0.6934640522875817.

Best trial: 66. Best value: 0.693464:  44%|████▍     | 88/200 [00:43<00:54,  2.07it/s]

[I 2025-11-10 19:06:53,508] Trial 86 finished with value: 0.6819607843137254 and parameters: {'max_depth': 5, 'learning_rate': 0.05377181679804398, 'n_estimators': 676, 'subsample': 0.9472168465742009, 'colsample_bytree': 0.7609122125371944, 'min_child_weight': 5, 'gamma': 4.454167164863156, 'reg_alpha': 0.0005421680648611666, 'reg_lambda': 0.0029621871835487485, 'max_delta_step': 3}. Best is trial 66 with value: 0.6934640522875817.

Best trial: 66. Best value: 0.693464:  45%|████▌     | 90/200 [00:44<00:43,  2.52it/s]

[I 2025-11-10 19:06:53,989] Trial 91 pruned.
[I 2025-11-10 19:06:54,125] Trial 88 finished with value: 0.681045751633987 and parameters: {'max_depth': 3, 'learning_rate': 0.12403814383328977, 'n_estimators': 638, 'subsample': 0.9523917118408198, 'colsample_bytree': 0.8179322302450521, 'min_child_weight': 5, 'gamma': 3.8939833281265384, 'reg_alpha': 2.1756835312204504e-08, 'reg_lambda': 0.21384623544996265, 'max_delta_step': 3}. Best is trial 66 with value: 0.6934640522875817.

Best trial: 66. Best value: 0.693464:  46%|████▌     | 91/200 [00:44<00:43,  2.51it/s]

[I 2025-11-10 19:06:54,526] Trial 93 pruned.

Best trial: 66. Best value: 0.693464:  46%|████▌     | 92/200 [00:45<00:39,  2.76it/s]

[I 2025-11-10 19:06:54,795] Trial 92 pruned.

Best trial: 66. Best value: 0.693464:  46%|████▋     | 93/200 [00:46<00:52,  2.04it/s]

[I 2025-11-10 19:06:55,610] Trial 90 finished with value: 0.6798039215686275 and parameters: {'max_depth': 10, 'learning_rate': 0.048367055137589, 'n_estimators': 513, 'subsample': 0.9620064075749154, 'colsample_bytree': 0.7288714603566481, 'min_child_weight': 5, 'gamma': 4.656963273219036, 'reg_alpha': 0.0010660486914103463, 'reg_lambda': 0.03266502050194427, 'max_delta_step': 2}. Best is trial 66 with value: 0.6934640522875817.
[I 2025-11-10 19:06:55,628] Trial 89 finished with value: 0.6610457516339869 and parameters: {'max_depth': 10, 'learning_rate': 0.07433578717203564, 'n_estimators': 520, 'subsample': 0.9617343136172413, 'colsample_bytree': 0.7284088527616134, 'min_child_weight': 5, 'gamma': 2.940511598651171, 'reg_alpha': 0.00112042977530634, 'reg_lambda': 0.04943937756466884, 'max_delta_step': 2}. Best is trial 66 with value: 0.6934640522875817.

Best trial: 94. Best value: 0.69902:  48%|████▊     | 95/200 [00:48<01:19,  1.33it/s]

[I 2025-11-10 19:06:57,776] Trial 94 finished with value: 0.6990196078431372 and parameters: {'max_depth': 3, 'learning_rate': 0.1528128987977205, 'n_estimators': 718, 'subsample': 0.9870026654770616, 'colsample_bytree': 0.7918750033892232, 'min_child_weight': 5, 'gamma': 3.6703479972892605, 'reg_alpha': 0.012584463591042568, 'reg_lambda': 1.3585286519912565, 'max_delta_step': 2}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  48%|████▊     | 96/200 [00:48<01:08,  1.51it/s]

[I 2025-11-10 19:06:58,147] Trial 95 finished with value: 0.6704575163398692 and parameters: {'max_depth': 3, 'learning_rate': 0.057354112561323875, 'n_estimators': 792, 'subsample': 0.9253320783979583, 'colsample_bytree': 0.7047057786149648, 'min_child_weight': 5, 'gamma': 4.09211228520766, 'reg_alpha': 0.009172296951200302, 'reg_lambda': 0.9475437234687516, 'max_delta_step': 3}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  48%|████▊     | 97/200 [00:48<00:56,  1.82it/s]

[I 2025-11-10 19:06:58,373] Trial 97 finished with value: 0.6678431372549019 and parameters: {'max_depth': 3, 'learning_rate': 0.013859691909428375, 'n_estimators': 629, 'subsample': 0.9283775610842542, 'colsample_bytree': 0.7019812098541925, 'min_child_weight': 5, 'gamma': 4.091833458412427, 'reg_alpha': 0.004579380591375616, 'reg_lambda': 1.164655984549695, 'max_delta_step': 3}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  49%|████▉     | 98/200 [00:48<00:46,  2.20it/s]

[I 2025-11-10 19:06:58,570] Trial 98 pruned.

Best trial: 94. Best value: 0.69902:  50%|█████     | 101/200 [00:49<00:27,  3.63it/s]

[I 2025-11-10 19:06:58,993] Trial 96 finished with value: 0.6849673202614379 and parameters: {'max_depth': 3, 'learning_rate': 0.05805859514905946, 'n_estimators': 778, 'subsample': 0.88414751644148, 'colsample_bytree': 0.7041492504285113, 'min_child_weight': 5, 'gamma': 4.100756212218497, 'reg_alpha': 0.028642733525777994, 'reg_lambda': 0.4171490176942453, 'max_delta_step': 3}. Best is trial 94 with value: 0.6990196078431372.
[I 2025-11-10 19:06:59,089] Trial 99 pruned.
[I 2025-11-10 19:06:59,095] Trial 100 pruned.

Best trial: 94. Best value: 0.69902:  51%|█████     | 102/200 [00:49<00:28,  3.45it/s]

[I 2025-11-10 19:06:59,446] Trial 101 pruned.

Best trial: 94. Best value: 0.69902:  52%|█████▏    | 103/200 [00:50<00:29,  3.32it/s]

[I 2025-11-10 19:06:59,781] Trial 103 pruned.
[I 2025-11-10 19:06:59,831] Trial 104 pruned.

Best trial: 94. Best value: 0.69902:  52%|█████▎    | 105/200 [00:50<00:25,  3.73it/s]

[I 2025-11-10 19:07:00,228] Trial 105 pruned.

Best trial: 94. Best value: 0.69902:  54%|█████▎    | 107/200 [00:51<00:23,  3.97it/s]

[I 2025-11-10 19:07:00,612] Trial 106 pruned.
[I 2025-11-10 19:07:00,730] Trial 107 pruned.

Best trial: 94. Best value: 0.69902:  55%|█████▍    | 109/200 [00:51<00:20,  4.40it/s]

[I 2025-11-10 19:07:01,065] Trial 108 pruned.
[I 2025-11-10 19:07:01,169] Trial 109 pruned.

Best trial: 94. Best value: 0.69902:  55%|█████▌    | 110/200 [00:51<00:17,  5.10it/s]

[I 2025-11-10 19:07:01,285] Trial 110 pruned.

Best trial: 94. Best value: 0.69902:  56%|█████▌    | 112/200 [00:52<00:23,  3.81it/s]

[I 2025-11-10 19:07:01,841] Trial 112 pruned.
[I 2025-11-10 19:07:02,013] Trial 113 pruned.

Best trial: 94. Best value: 0.69902:  56%|█████▋    | 113/200 [00:53<00:42,  2.06it/s]

[I 2025-11-10 19:07:03,037] Trial 102 finished with value: 0.6392156862745099 and parameters: {'max_depth': 9, 'learning_rate': 0.24688288412974413, 'n_estimators': 721, 'subsample': 0.9848257064973812, 'colsample_bytree': 0.7779682514365726, 'min_child_weight': 4, 'gamma': 3.596970511762075, 'reg_alpha': 6.241987575283603e-05, 'reg_lambda': 4.547132792632688, 'max_delta_step': 1}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  57%|█████▋    | 114/200 [00:53<00:38,  2.25it/s]

[I 2025-11-10 19:07:03,386] Trial 111 finished with value: 0.6822222222222222 and parameters: {'max_depth': 3, 'learning_rate': 0.09605778068716236, 'n_estimators': 475, 'subsample': 0.9856048274018333, 'colsample_bytree': 0.737539730469008, 'min_child_weight': 5, 'gamma': 4.413881764079444, 'reg_alpha': 5.516886375787418e-07, 'reg_lambda': 0.0007583641211317559, 'max_delta_step': 3}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  57%|█████▊    | 115/200 [00:54<00:55,  1.54it/s]

[I 2025-11-10 19:07:04,519] Trial 114 finished with value: 0.6854901960784313 and parameters: {'max_depth': 4, 'learning_rate': 0.043296200442429086, 'n_estimators': 587, 'subsample': 0.9794854109693213, 'colsample_bytree': 0.7657382222536355, 'min_child_weight': 5, 'gamma': 4.011783076708711, 'reg_alpha': 0.006455030459597206, 'reg_lambda': 0.9012008608675645, 'max_delta_step': 3}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  58%|█████▊    | 116/200 [00:55<00:42,  1.95it/s]

[I 2025-11-10 19:07:04,708] Trial 115 finished with value: 0.6844444444444443 and parameters: {'max_depth': 4, 'learning_rate': 0.05807351189449503, 'n_estimators': 617, 'subsample': 0.9493185306943713, 'colsample_bytree': 0.7581987112948406, 'min_child_weight': 5, 'gamma': 4.240322801563468, 'reg_alpha': 0.005874668929080948, 'reg_lambda': 0.8687942881427424, 'max_delta_step': 3}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  58%|█████▊    | 117/200 [00:55<00:39,  2.09it/s]

[I 2025-11-10 19:07:05,111] Trial 118 pruned.

Best trial: 94. Best value: 0.69902:  59%|█████▉    | 118/200 [00:56<00:40,  2.04it/s]

[I 2025-11-10 19:07:05,626] Trial 116 finished with value: 0.6831372549019609 and parameters: {'max_depth': 4, 'learning_rate': 0.042524095918105964, 'n_estimators': 582, 'subsample': 0.9567009354598042, 'colsample_bytree': 0.7582978893367249, 'min_child_weight': 5, 'gamma': 4.1727189379139515, 'reg_alpha': 0.005047913793331584, 'reg_lambda': 0.8189411937276302, 'max_delta_step': 3}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  60%|█████▉    | 119/200 [00:56<00:37,  2.17it/s]

[I 2025-11-10 19:07:06,015] Trial 117 finished with value: 0.6735294117647059 and parameters: {'max_depth': 4, 'learning_rate': 0.0445101238026396, 'n_estimators': 584, 'subsample': 0.9554523097039634, 'colsample_bytree': 0.7572308193803486, 'min_child_weight': 5, 'gamma': 4.160161863165007, 'reg_alpha': 0.006391375051863129, 'reg_lambda': 0.6398261278655564, 'max_delta_step': 3}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  60%|██████    | 120/200 [00:57<00:41,  1.94it/s]

[I 2025-11-10 19:07:06,654] Trial 122 pruned.

Best trial: 94. Best value: 0.69902:  60%|██████    | 121/200 [00:57<00:46,  1.69it/s]

[I 2025-11-10 19:07:07,428] Trial 119 finished with value: 0.6856209150326797 and parameters: {'max_depth': 7, 'learning_rate': 0.03319316495979444, 'n_estimators': 579, 'subsample': 0.9982227845650604, 'colsample_bytree': 0.720002171805044, 'min_child_weight': 5, 'gamma': 3.8514150087862067, 'reg_alpha': 0.0020227597633874833, 'reg_lambda': 0.6016337307471041, 'max_delta_step': 5}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  62%|██████▏   | 123/200 [00:58<00:36,  2.14it/s]

[I 2025-11-10 19:07:08,123] Trial 121 finished with value: 0.649607843137255 and parameters: {'max_depth': 3, 'learning_rate': 0.2148050388330977, 'n_estimators': 545, 'subsample': 0.9976918669956311, 'colsample_bytree': 0.8160425646667965, 'min_child_weight': 5, 'gamma': 3.9993815999273137, 'reg_alpha': 0.001676282875907757, 'reg_lambda': 0.00038289846969705193, 'max_delta_step': 4}. Best is trial 94 with value: 0.6990196078431372.
[I 2025-11-10 19:07:08,231] Trial 120 finished with value: 0.6769934640522876 and parameters: {'max_depth': 3, 'learning_rate': 0.04152206957923539, 'n_estimators': 680, 'subsample': 0.997997036331653, 'colsample_bytree': 0.7700126430345134, 'min_child_weight': 5, 'gamma': 3.8292746931126924, 'reg_alpha': 0.003409263287058494, 'reg_lambda': 0.002007553463782564, 'max_delta_step': 4}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  62%|██████▎   | 125/200 [00:59<00:26,  2.79it/s]

[I 2025-11-10 19:07:08,599] Trial 125 pruned.
[I 2025-11-10 19:07:08,769] Trial 126 pruned.

Best trial: 94. Best value: 0.69902:  63%|██████▎   | 126/200 [00:59<00:20,  3.53it/s]

[I 2025-11-10 19:07:08,877] Trial 123 finished with value: 0.6803921568627451 and parameters: {'max_depth': 3, 'learning_rate': 0.05085523732950683, 'n_estimators': 440, 'subsample': 0.9987484484425005, 'colsample_bytree': 0.709352142686298, 'min_child_weight': 5, 'gamma': 4.294437770940976, 'reg_alpha': 0.002085006388153164, 'reg_lambda': 0.0019712718244712843, 'max_delta_step': 4}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  64%|██████▍   | 128/200 [01:00<00:21,  3.37it/s]

[I 2025-11-10 19:07:09,477] Trial 128 pruned.
[I 2025-11-10 19:07:09,583] Trial 129 pruned.

Best trial: 94. Best value: 0.69902:  65%|██████▌   | 130/200 [01:00<00:19,  3.56it/s]

[I 2025-11-10 19:07:10,048] Trial 130 pruned.
[I 2025-11-10 19:07:10,173] Trial 124 finished with value: 0.6803921568627451 and parameters: {'max_depth': 7, 'learning_rate': 0.031670857414397104, 'n_estimators': 541, 'subsample': 0.9990759724806327, 'colsample_bytree': 0.7456352759148738, 'min_child_weight': 5, 'gamma': 3.981695290650028, 'reg_alpha': 3.5537702081381656e-08, 'reg_lambda': 1.7440633349509977, 'max_delta_step': 5}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  66%|██████▌   | 131/200 [01:01<00:23,  2.93it/s]

[I 2025-11-10 19:07:10,661] Trial 133 pruned.
[I 2025-11-10 19:07:10,749] Trial 132 pruned.

Best trial: 94. Best value: 0.69902:  67%|██████▋   | 134/200 [01:01<00:17,  3.71it/s]

[I 2025-11-10 19:07:11,268] Trial 134 pruned.
[I 2025-11-10 19:07:11,370] Trial 135 pruned.

Best trial: 94. Best value: 0.69902:  68%|██████▊   | 135/200 [01:01<00:14,  4.37it/s]

[I 2025-11-10 19:07:11,481] Trial 127 finished with value: 0.6848366013071895 and parameters: {'max_depth': 6, 'learning_rate': 0.02769903588675056, 'n_estimators': 540, 'subsample': 0.9997265096053767, 'colsample_bytree': 0.7448408198898112, 'min_child_weight': 5, 'gamma': 4.330416058464434, 'reg_alpha': 4.900787181295778e-08, 'reg_lambda': 0.29264680578805596, 'max_delta_step': 6}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  68%|██████▊   | 136/200 [01:02<00:19,  3.25it/s]

[I 2025-11-10 19:07:12,003] Trial 136 pruned.

Best trial: 94. Best value: 0.69902:  68%|██████▊   | 137/200 [01:03<00:24,  2.54it/s]

[I 2025-11-10 19:07:12,619] Trial 131 finished with value: 0.6776470588235294 and parameters: {'max_depth': 7, 'learning_rate': 0.02383230617323582, 'n_estimators': 610, 'subsample': 0.963774650317149, 'colsample_bytree': 0.6756850757726688, 'min_child_weight': 5, 'gamma': 4.551025959125147, 'reg_alpha': 2.9401719667674674e-08, 'reg_lambda': 0.062139844175570516, 'max_delta_step': 5}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  69%|██████▉   | 138/200 [01:04<00:43,  1.42it/s]

[I 2025-11-10 19:07:14,104] Trial 138 finished with value: 0.6833333333333333 and parameters: {'max_depth': 6, 'learning_rate': 0.025755104700005887, 'n_estimators': 569, 'subsample': 0.979685065391205, 'colsample_bytree': 0.7702056972312232, 'min_child_weight': 5, 'gamma': 4.765964463462884, 'reg_alpha': 1.0837227088155344e-07, 'reg_lambda': 0.12018190959315574, 'max_delta_step': 8}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  70%|██████▉   | 139/200 [01:04<00:34,  1.79it/s]

[I 2025-11-10 19:07:14,304] Trial 137 finished with value: 0.663921568627451 and parameters: {'max_depth': 3, 'learning_rate': 0.06407757284809262, 'n_estimators': 651, 'subsample': 0.9782532172128483, 'colsample_bytree': 0.7698254461181461, 'min_child_weight': 5, 'gamma': 4.700198926553559, 'reg_alpha': 0.013616170034054137, 'reg_lambda': 1.0608182472225136, 'max_delta_step': 3}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  70%|███████   | 140/200 [01:05<00:29,  2.06it/s]

[I 2025-11-10 19:07:14,611] Trial 139 finished with value: 0.6784967320261438 and parameters: {'max_depth': 8, 'learning_rate': 0.024918278634377792, 'n_estimators': 569, 'subsample': 0.9805794711258373, 'colsample_bytree': 0.6925243739051217, 'min_child_weight': 5, 'gamma': 4.720413484286422, 'reg_alpha': 4.269696610539543e-06, 'reg_lambda': 0.08915400104105585, 'max_delta_step': 5}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  70%|███████   | 141/200 [01:05<00:27,  2.16it/s]

[I 2025-11-10 19:07:15,018] Trial 141 pruned.

Best trial: 94. Best value: 0.69902:  71%|███████   | 142/200 [01:05<00:23,  2.42it/s]

[I 2025-11-10 19:07:15,312] Trial 140 finished with value: 0.6633333333333333 and parameters: {'max_depth': 8, 'learning_rate': 0.15910074536188046, 'n_estimators': 582, 'subsample': 0.9821728589981755, 'colsample_bytree': 0.6963065036934717, 'min_child_weight': 5, 'gamma': 4.687727523838511, 'reg_alpha': 8.368201822828386e-08, 'reg_lambda': 0.09581792532660906, 'max_delta_step': 6}. Best is trial 94 with value: 0.6990196078431372.

Best trial: 94. Best value: 0.69902:  72%|███████▏  | 144/200 [01:06<00:16,  3.41it/s]

[I 2025-11-10 19:07:15,516] Trial 143 pruned.
[I 2025-11-10 19:07:15,675] Trial 142 pruned.

Best trial: 94. Best value: 0.69902:  73%|███████▎  | 146/200 [01:06<00:11,  4.66it/s]

[I 2025-11-10 19:07:15,785] Trial 144 pruned.
[I 2025-11-10 19:07:15,943] Trial 145 pruned.

Best trial: 146. Best value: 0.707516:  74%|███████▍  | 148/200 [01:08<00:28,  1.81it/s]

[I 2025-11-10 19:07:17,911] Trial 146 finished with value: 0.707516339869281 and parameters: {'max_depth': 4, 'learning_rate': 0.10651145287760364, 'n_estimators': 504, 'subsample': 0.9686082720134803, 'colsample_bytree': 0.7529211648785743, 'min_child_weight': 5, 'gamma': 4.017726925211898, 'reg_alpha': 0.009755826618884945, 'reg_lambda': 0.5811168542390962, 'max_delta_step': 4}. Best is trial 146 with value: 0.707516339869281.
[I 2025-11-10 19:07:18,032] Trial 149 finished with value: 0.6912418300653593 and parameters: {'max_depth': 4, 'learning_rate': 0.11211538899759806, 'n_estimators': 464, 'subsample': 0.9453147102586359, 'colsample_bytree': 0.7580522157014006, 'min_child_weight': 5, 'gamma': 4.431478348308341, 'reg_alpha': 2.218107392788749e-07, 'reg_lambda': 0.6171789239086816, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  74%|███████▍  | 149/200 [01:08<00:28,  1.81it/s]

[I 2025-11-10 19:07:18,100] Trial 148 finished with value: 0.6898692810457516 and parameters: {'max_depth': 4, 'learning_rate': 0.06187066721587157, 'n_estimators': 499, 'subsample': 0.943160375314387, 'colsample_bytree': 0.7541585822884336, 'min_child_weight': 5, 'gamma': 4.229294539970534, 'reg_alpha': 1.667045662166104e-08, 'reg_lambda': 0.40011927014265336, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.
[I 2025-11-10 19:07:18,106] Trial 147 finished with value: 0.6916339869281045 and parameters: {'max_depth': 4, 'learning_rate': 0.10813211727337889, 'n_estimators': 513, 'subsample': 0.9661324065787514, 'colsample_bytree': 0.7849141656456537, 'min_child_weight': 5, 'gamma': 4.456068974026955, 'reg_alpha': 1.4451905404987633e-08, 'reg_lambda': 0.46252028622196634, 'max_delta_step': 4}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  76%|███████▋  | 153/200 [01:09<00:11,  4.01it/s]

[I 2025-11-10 19:07:18,546] Trial 152 pruned.
[I 2025-11-10 19:07:18,568] Trial 151 pruned.
[I 2025-11-10 19:07:18,712] Trial 153 pruned.

Best trial: 146. Best value: 0.707516:  77%|███████▋  | 154/200 [01:10<00:23,  1.92it/s]

[I 2025-11-10 19:07:20,325] Trial 150 finished with value: 0.7012418300653593 and parameters: {'max_depth': 4, 'learning_rate': 0.10712228555733562, 'n_estimators': 470, 'subsample': 0.9555737963880727, 'colsample_bytree': 0.7883593492020972, 'min_child_weight': 5, 'gamma': 4.4551290701154205, 'reg_alpha': 0.3344327998746938, 'reg_lambda': 0.4652250061010608, 'max_delta_step': 5}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  78%|███████▊  | 155/200 [01:11<00:23,  1.91it/s]

[I 2025-11-10 19:07:20,855] Trial 154 finished with value: 0.6898039215686274 and parameters: {'max_depth': 4, 'learning_rate': 0.1190754423854671, 'n_estimators': 499, 'subsample': 0.9461610904198184, 'colsample_bytree': 0.7915226987573187, 'min_child_weight': 5, 'gamma': 4.569301553343807, 'reg_alpha': 1.6670318401059005e-08, 'reg_lambda': 0.5301767884934433, 'max_delta_step': 4}. Best is trial 146 with value: 0.707516339869281.
[I 2025-11-10 19:07:20,865] Trial 155 finished with value: 0.6783006535947712 and parameters: {'max_depth': 4, 'learning_rate': 0.12188594411279037, 'n_estimators': 496, 'subsample': 0.9365517375419945, 'colsample_bytree': 0.7607744550779698, 'min_child_weight': 5, 'gamma': 4.5545727397729205, 'reg_alpha': 1.8775533506380266e-08, 'reg_lambda': 0.5679708227619169, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  78%|███████▊  | 157/200 [01:11<00:15,  2.76it/s]

[I 2025-11-10 19:07:21,068] Trial 156 finished with value: 0.6959477124183006 and parameters: {'max_depth': 4, 'learning_rate': 0.1184149411792281, 'n_estimators': 507, 'subsample': 0.9341790933684242, 'colsample_bytree': 0.7503183607526537, 'min_child_weight': 5, 'gamma': 4.539504958928796, 'reg_alpha': 1.8627750866557308e-08, 'reg_lambda': 0.4980890195677835, 'max_delta_step': 8}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  79%|███████▉  | 158/200 [01:13<00:26,  1.60it/s]

[I 2025-11-10 19:07:22,655] Trial 157 finished with value: 0.6698692810457516 and parameters: {'max_depth': 4, 'learning_rate': 0.12188576703865261, 'n_estimators': 502, 'subsample': 0.94668839127759, 'colsample_bytree': 0.7545602432998829, 'min_child_weight': 5, 'gamma': 4.520099991253252, 'reg_alpha': 1.3958918873985462, 'reg_lambda': 0.47364974367392454, 'max_delta_step': 5}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  80%|████████  | 160/200 [01:13<00:17,  2.30it/s]

[I 2025-11-10 19:07:22,872] Trial 158 finished with value: 0.6994771241830064 and parameters: {'max_depth': 4, 'learning_rate': 0.10380614490459433, 'n_estimators': 413, 'subsample': 0.9478320737228113, 'colsample_bytree': 0.8234163990231815, 'min_child_weight': 5, 'gamma': 4.6037269721899365, 'reg_alpha': 0.8377480435505127, 'reg_lambda': 0.1727034685187582, 'max_delta_step': 4}. Best is trial 146 with value: 0.707516339869281.
[I 2025-11-10 19:07:23,020] Trial 159 finished with value: 0.7007843137254901 and parameters: {'max_depth': 4, 'learning_rate': 0.10303809929362745, 'n_estimators': 443, 'subsample': 0.9471459925110461, 'colsample_bytree': 0.7931471372234835, 'min_child_weight': 5, 'gamma': 4.247021533808867, 'reg_alpha': 1.0419923616803066, 'reg_lambda': 0.16588406881285925, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.
[I 2025-11-10 19:07:23,034] Trial 160 finished with value: 0.694313725490196 and parameters: {'max_depth': 4, 'learning_rate': 0.1287603614904288, 'n_estimators': 422, 'subsample': 0.9470029800333409, 'colsample_bytree': 0.7912419044923975, 'min_child_weight': 5, 'gamma': 4.64501407682882, 'reg_alpha': 2.7768464383723878e-08, 'reg_lambda': 0.1433930020631681, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  81%|████████  | 162/200 [01:15<00:23,  1.62it/s]

[I 2025-11-10 19:07:24,763] Trial 161 finished with value: 0.6912418300653594 and parameters: {'max_depth': 4, 'learning_rate': 0.13032401481294206, 'n_estimators': 433, 'subsample': 0.9285631701706761, 'colsample_bytree': 0.7901892296628853, 'min_child_weight': 5, 'gamma': 4.824204664108304, 'reg_alpha': 2.585991350034747e-08, 'reg_lambda': 0.1597631506884882, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  82%|████████▏ | 164/200 [01:15<00:18,  1.91it/s]

[I 2025-11-10 19:07:24,972] Trial 164 finished with value: 0.6912418300653594 and parameters: {'max_depth': 4, 'learning_rate': 0.13182395465875016, 'n_estimators': 411, 'subsample': 0.9303375581234578, 'colsample_bytree': 0.8320873882699343, 'min_child_weight': 5, 'gamma': 4.616848246980731, 'reg_alpha': 0.3875055260366331, 'reg_lambda': 0.18552719475872712, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.
[I 2025-11-10 19:07:24,982] Trial 163 finished with value: 0.6830065359477124 and parameters: {'max_depth': 4, 'learning_rate': 0.13650011189333253, 'n_estimators': 416, 'subsample': 0.9305226860667514, 'colsample_bytree': 0.8224357364975203, 'min_child_weight': 5, 'gamma': 4.614468106740032, 'reg_alpha': 0.8697592042307558, 'reg_lambda': 0.19473930510479903, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.
[I 2025-11-10 19:07:24,992] Trial 162 finished with value: 0.6915032679738562 and parameters: {'max_depth': 4, 'learning_rate': 0.1005660714325976, 'n_estimators': 426, 'subsample': 0.9325398139548766, 'colsample_bytree': 0.8344385112524062, 'min_child_weight': 5, 'gamma': 4.615596608731585, 'reg_alpha': 2.8896060915708587e-08, 'reg_lambda': 0.14908820066037715, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  83%|████████▎ | 166/200 [01:17<00:17,  1.99it/s]

[I 2025-11-10 19:07:26,416] Trial 165 finished with value: 0.6856862745098039 and parameters: {'max_depth': 4, 'learning_rate': 0.13402886929272842, 'n_estimators': 327, 'subsample': 0.9276174074207121, 'colsample_bytree': 0.8366084228502207, 'min_child_weight': 5, 'gamma': 4.8490609316408495, 'reg_alpha': 3.668844152191243e-08, 'reg_lambda': 0.14146326022256903, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.
[I 2025-11-10 19:07:26,600] Trial 166 finished with value: 0.6465359477124182 and parameters: {'max_depth': 4, 'learning_rate': 0.10268889297348703, 'n_estimators': 326, 'subsample': 0.9300641501732441, 'colsample_bytree': 0.8433421174056808, 'min_child_weight': 5, 'gamma': 4.856672094445189, 'reg_alpha': 0.3149562495066941, 'reg_lambda': 0.23807495012189722, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  85%|████████▌ | 170/200 [01:17<00:08,  3.63it/s]

[I 2025-11-10 19:07:26,877] Trial 169 pruned.
[I 2025-11-10 19:07:26,931] Trial 167 finished with value: 0.6794771241830065 and parameters: {'max_depth': 4, 'learning_rate': 0.10118966726929832, 'n_estimators': 381, 'subsample': 0.9277130155355857, 'colsample_bytree': 0.8476702678546342, 'min_child_weight': 5, 'gamma': 4.843805377130489, 'reg_alpha': 0.2979225071219171, 'reg_lambda': 0.12053701026699852, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.
[I 2025-11-10 19:07:26,995] Trial 168 finished with value: 0.6750980392156862 and parameters: {'max_depth': 4, 'learning_rate': 0.14681780725121746, 'n_estimators': 390, 'subsample': 0.9305190262460352, 'colsample_bytree': 0.8464662228301152, 'min_child_weight': 5, 'gamma': 4.863334780965866, 'reg_alpha': 0.42320977345812466, 'reg_lambda': 0.17203249284511626, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  86%|████████▌ | 171/200 [01:17<00:07,  3.93it/s]

[I 2025-11-10 19:07:27,181] Trial 170 pruned.

Best trial: 146. Best value: 0.707516:  86%|████████▌ | 172/200 [01:18<00:09,  2.90it/s]

[I 2025-11-10 19:07:27,824] Trial 171 pruned.

Best trial: 146. Best value: 0.707516:  86%|████████▋ | 173/200 [01:19<00:15,  1.71it/s]

[I 2025-11-10 19:07:29,123] Trial 172 finished with value: 0.6645098039215687 and parameters: {'max_depth': 4, 'learning_rate': 0.14815412357119798, 'n_estimators': 410, 'subsample': 0.9538727573333418, 'colsample_bytree': 0.8084695041866098, 'min_child_weight': 5, 'gamma': 4.626783315076944, 'reg_alpha': 2.0422927217879088, 'reg_lambda': 0.026991057107473952, 'max_delta_step': 8}. Best is trial 146 with value: 0.707516339869281.
[I 2025-11-10 19:07:29,217] Trial 173 finished with value: 0.6662745098039216 and parameters: {'max_depth': 4, 'learning_rate': 0.13027105689341348, 'n_estimators': 423, 'subsample': 0.9551344191688442, 'colsample_bytree': 0.8688082209884412, 'min_child_weight': 5, 'gamma': 4.645473126632925, 'reg_alpha': 2.1900170764531253, 'reg_lambda': 0.077092486759446, 'max_delta_step': 8}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  88%|████████▊ | 175/200 [01:19<00:09,  2.51it/s]

[I 2025-11-10 19:07:29,397] Trial 174 finished with value: 0.6774509803921569 and parameters: {'max_depth': 4, 'learning_rate': 0.11469421666272649, 'n_estimators': 430, 'subsample': 0.9537042022126676, 'colsample_bytree': 0.8682805259859417, 'min_child_weight': 5, 'gamma': 4.3521266969649135, 'reg_alpha': 1.8833532698843536, 'reg_lambda': 0.3914821002930841, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  88%|████████▊ | 177/200 [01:20<00:07,  3.01it/s]

[I 2025-11-10 19:07:29,832] Trial 178 pruned.
[I 2025-11-10 19:07:29,937] Trial 175 finished with value: 0.6971241830065359 and parameters: {'max_depth': 4, 'learning_rate': 0.0886997169657529, 'n_estimators': 429, 'subsample': 0.955144330070557, 'colsample_bytree': 0.8257570777464482, 'min_child_weight': 5, 'gamma': 4.391485328751021, 'reg_alpha': 2.8591675036451045e-08, 'reg_lambda': 0.3115102420269287, 'max_delta_step': 8}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  89%|████████▉ | 178/200 [01:20<00:07,  2.76it/s]

[I 2025-11-10 19:07:30,385] Trial 180 pruned.

Best trial: 146. Best value: 0.707516:  90%|████████▉ | 179/200 [01:21<00:07,  2.67it/s]

[I 2025-11-10 19:07:30,794] Trial 181 pruned.

Best trial: 146. Best value: 0.707516:  90%|█████████ | 180/200 [01:21<00:09,  2.20it/s]

[I 2025-11-10 19:07:31,454] Trial 176 finished with value: 0.6990196078431372 and parameters: {'max_depth': 4, 'learning_rate': 0.12806496377219329, 'n_estimators': 452, 'subsample': 0.9469467310318729, 'colsample_bytree': 0.8171796660500428, 'min_child_weight': 5, 'gamma': 4.377016644576186, 'reg_alpha': 2.8647104880584854e-08, 'reg_lambda': 0.35278770996210573, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.
[I 2025-11-10 19:07:31,471] Trial 177 finished with value: 0.6959477124183006 and parameters: {'max_depth': 4, 'learning_rate': 0.09052354893928491, 'n_estimators': 450, 'subsample': 0.9436151331564653, 'colsample_bytree': 0.8272751655033475, 'min_child_weight': 5, 'gamma': 4.377342922121646, 'reg_alpha': 0.12206761166229248, 'reg_lambda': 0.3751624553457745, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  91%|█████████ | 182/200 [01:22<00:07,  2.50it/s]

[I 2025-11-10 19:07:32,119] Trial 179 finished with value: 0.6444444444444445 and parameters: {'max_depth': 4, 'learning_rate': 0.08758348465747987, 'n_estimators': 449, 'subsample': 0.9443944459859827, 'colsample_bytree': 0.8238851603643393, 'min_child_weight': 5, 'gamma': 0.9785353349153416, 'reg_alpha': 0.1310935332711067, 'reg_lambda': 3.879854970157611e-05, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  92%|█████████▏| 183/200 [01:23<00:08,  1.90it/s]

[I 2025-11-10 19:07:33,044] Trial 182 finished with value: 0.6994771241830066 and parameters: {'max_depth': 4, 'learning_rate': 0.08648764696874933, 'n_estimators': 462, 'subsample': 0.9461550491783894, 'colsample_bytree': 0.8238014812409769, 'min_child_weight': 5, 'gamma': 4.513985445896703, 'reg_alpha': 3.25970236044376e-08, 'reg_lambda': 0.2879926746580354, 'max_delta_step': 8}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  92%|█████████▎| 185/200 [01:24<00:06,  2.45it/s]

[I 2025-11-10 19:07:33,509] Trial 184 finished with value: 0.6735947712418302 and parameters: {'max_depth': 4, 'learning_rate': 0.09742031780640971, 'n_estimators': 428, 'subsample': 0.937214430729645, 'colsample_bytree': 0.8315471565271499, 'min_child_weight': 5, 'gamma': 4.514623901988001, 'reg_alpha': 0.6763929984165075, 'reg_lambda': 0.3301128955100784, 'max_delta_step': 8}. Best is trial 146 with value: 0.707516339869281.
[I 2025-11-10 19:07:33,636] Trial 183 finished with value: 0.6844444444444445 and parameters: {'max_depth': 4, 'learning_rate': 0.08503250145722838, 'n_estimators': 440, 'subsample': 0.9354651377676406, 'colsample_bytree': 0.8319176918916062, 'min_child_weight': 5, 'gamma': 4.528647971390443, 'reg_alpha': 2.4444320876462395e-08, 'reg_lambda': 0.16454449962859935, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  93%|█████████▎| 186/200 [01:24<00:05,  2.47it/s]

[I 2025-11-10 19:07:34,033] Trial 187 pruned.

Best trial: 146. Best value: 0.707516:  94%|█████████▍| 188/200 [01:24<00:03,  3.67it/s]

[I 2025-11-10 19:07:34,216] Trial 188 pruned.
[I 2025-11-10 19:07:34,319] Trial 185 finished with value: 0.6843137254901961 and parameters: {'max_depth': 4, 'learning_rate': 0.0957589607258747, 'n_estimators': 421, 'subsample': 0.9533435404074061, 'colsample_bytree': 0.8333558138750248, 'min_child_weight': 5, 'gamma': 4.5061244012611015, 'reg_alpha': 3.010683958004554e-08, 'reg_lambda': 9.05014797383302e-08, 'max_delta_step': 7}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  95%|█████████▌| 190/200 [01:25<00:02,  4.38it/s]

[I 2025-11-10 19:07:34,579] Trial 189 pruned.
[I 2025-11-10 19:07:34,710] Trial 190 pruned.

Best trial: 146. Best value: 0.707516:  96%|█████████▌| 191/200 [01:25<00:02,  4.40it/s]

[I 2025-11-10 19:07:34,931] Trial 191 pruned.

Best trial: 146. Best value: 0.707516:  96%|█████████▋| 193/200 [01:25<00:01,  4.88it/s]

[I 2025-11-10 19:07:35,209] Trial 192 pruned.
[I 2025-11-10 19:07:35,328] Trial 193 pruned.

Best trial: 146. Best value: 0.707516:  97%|█████████▋| 194/200 [01:25<00:01,  5.18it/s]

[I 2025-11-10 19:07:35,494] Trial 194 pruned.

Best trial: 146. Best value: 0.707516:  98%|█████████▊| 195/200 [01:26<00:00,  5.06it/s]

[I 2025-11-10 19:07:35,703] Trial 186 finished with value: 0.7000653594771241 and parameters: {'max_depth': 4, 'learning_rate': 0.09540471349698382, 'n_estimators': 476, 'subsample': 0.9555792470065771, 'colsample_bytree': 0.809345475503148, 'min_child_weight': 5, 'gamma': 4.311490044485196, 'reg_alpha': 3.509750793824042e-08, 'reg_lambda': 0.3243007484572579, 'max_delta_step': 8}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516:  98%|█████████▊| 196/200 [01:26<00:00,  4.34it/s]

[I 2025-11-10 19:07:36,008] Trial 197 pruned.

Best trial: 146. Best value: 0.707516:  98%|█████████▊| 197/200 [01:26<00:00,  4.36it/s]

[I 2025-11-10 19:07:36,235] Trial 198 pruned.

Best trial: 146. Best value: 0.707516:  99%|█████████▉| 198/200 [01:27<00:00,  2.54it/s]

[I 2025-11-10 19:07:37,013] Trial 195 finished with value: 0.6583006535947712 and parameters: {'max_depth': 4, 'learning_rate': 0.13126285673660038, 'n_estimators': 406, 'subsample': 0.9230797789725373, 'colsample_bytree': 0.7893324031932147, 'min_child_weight': 5, 'gamma': 4.596131446124028, 'reg_alpha': 0.9599866219498702, 'reg_lambda': 0.18785345932299324, 'max_delta_step': 4}. Best is trial 146 with value: 0.707516339869281.
[I 2025-11-10 19:07:37,196] Trial 196 finished with value: 0.6618300653594772 and parameters: {'max_depth': 4, 'learning_rate': 0.12803307122460833, 'n_estimators': 454, 'subsample': 0.9216209298821925, 'colsample_bytree': 0.8549568866815723, 'min_child_weight': 5, 'gamma': 4.634731904689864, 'reg_alpha': 0.61066539420667, 'reg_lambda': 0.16820123578618237, 'max_delta_step': 4}. Best is trial 146 with value: 0.707516339869281.

Best trial: 146. Best value: 0.707516: 100%|██████████| 200/200 [01:27<00:00,  2.27it/s]

[I 2025-11-10 19:07:37,565] Trial 199 finished with value: 0.6796078431372549 and parameters: {'max_depth': 4, 'learning_rate': 0.10676818365025616, 'n_estimators': 492, 'subsample': 0.9409445302523645, 'colsample_bytree': 0.7894775276861313, 'min_child_weight': 5, 'gamma': 4.2525741270928545, 'reg_alpha': 1.5528729342446036e-08, 'reg_lambda': 0.6885565769340228, 'max_delta_step': 8}. Best is trial 146 with value: 0.707516339869281.
   dataset  cv_best_value  test_balanced_accuracy  test_roc_auc  n_trials
0     17_1       0.614230                0.627329      0.813665       200
1     10_1       0.549181                0.611801      0.590062       200
2      3_1       0.572144                0.605590      0.596273       200
3      3_3       0.665712                0.605590      0.832298       200
4     16_1       0.692583                0.605590      0.630435       200
5     18_1       0.721365                0.599379      0.714286       200
6      3_4       0.650877                0.555901      0.658385       200
7      9_1       0.638954                0.544580      0.488636       200
8      3_5       0.546160                0.518634      0.381988       200
9      1_1       0.500000                0.500000      0.500000       200
10     3_2       0.500000                0.500000      0.500000       200
11    19_1       0.707516                0.446970      0.409091       200
12    15_1       0.575673                0.425466      0.437888       200