In [1398]:
import pathlib as Path
import numpy as np
import pandas as pd


## Create dataframe from embeddings

In [1399]:
#-----Frequency Embeddings dataframe creation-----
def create_embeddings_dataframe(root_path):
    emb_root = Path.Path(root_path)
    emb_files = emb_root.rglob("embeddings_samples.npz")
    
    all_data = []
    
    for emb_file in emb_files:
        emb = np.load(emb_file)
        X = emb['X']
        y = emb['y']
        subjects = emb['subs']
        
        for i in range(X.shape[0]):
            data_point = {
                'embedding': X[i],
                'label': y[i],
                'subject': subjects[i],
                'file_path': str(emb_file)
            }
            all_data.append(data_point)
    
    df = pd.DataFrame(all_data)
    return df


## Clean embedding DF

In [1400]:

def df_cleaning(df, emb_size=384):
        # --- Expand embedding column into 381 separate columns ---
    embedding_df = pd.DataFrame(df["embedding"].tolist(),
                                columns=[f"emb_{i}" for i in range(emb_size)])

    # --- Concatenate back to the original DataFrame (optional) ---
    df_expanded = pd.concat([df.drop(columns=["embedding"]), embedding_df], axis=1)
    return df_expanded

In [1401]:
#-----Frequency Embeddings dataframe creation-----
freq_emb= create_embeddings_dataframe("C://dev//dolphin_initial_testing//DOLPHIN//out_prelbd_task_wise//frequency_emb_stored//")
#-----Temporal Embeddings dataframe creation-----
temp_emb= create_embeddings_dataframe("C://dev//dolphin_initial_testing//DOLPHIN//out_prelbd_task_wise//temporal_emb_stored//")
#-----Combined Embeddings dataframe creation-----
comb_emb= create_embeddings_dataframe("C://dev//dolphin_initial_testing//DOLPHIN//out_prelbd_task_wise//emb_stored//")

freq_emb_df= df_cleaning(freq_emb, emb_size=384)
temp_emb_df= df_cleaning(temp_emb, emb_size=384)
comb_emb_df= df_cleaning(comb_emb, emb_size=768)

In [1402]:
freq_emb_df

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_374,emb_375,emb_376,emb_377,emb_378,emb_379,emb_380,emb_381,emb_382,emb_383
0,1,COBEN-WTABLET-AS-HCD05,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.020803,0.024742,-0.001459,-0.030411,0.005069,-0.071482,0.019421,...,0.009478,0.034411,0.014662,-0.090859,0.069126,-0.047900,0.006064,0.018750,0.061787,-0.008002
1,1,COBEN-WTABLET-BB-PD08,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.019917,0.024111,-0.002791,-0.029054,0.005171,-0.070701,0.019973,...,0.010498,0.034390,0.016988,-0.092144,0.067938,-0.048388,0.005863,0.019660,0.060609,-0.008458
2,1,COBEN-WTABLET-DM-AD15,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.018108,0.025302,-0.001694,-0.028552,0.005417,-0.068487,0.017704,...,0.009714,0.035088,0.015138,-0.094040,0.067323,-0.048907,0.007274,0.020602,0.062291,-0.008537
3,1,COBEN-WTABLET-DM-PD17,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.019036,0.021408,-0.004025,-0.027294,0.004202,-0.070225,0.019877,...,0.012248,0.033855,0.017426,-0.091839,0.065746,-0.050177,0.005471,0.024139,0.059553,-0.007032
4,1,COBEN-WTABLET-DS-HC36,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.021802,0.026779,-0.001436,-0.032483,0.004540,-0.069463,0.018237,...,0.008617,0.035733,0.016321,-0.092127,0.071785,-0.046817,0.006332,0.016091,0.062483,-0.007423
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3430,1,pre-LBD-94#2,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.005028,0.034374,0.061780,0.096021,-0.090914,0.009212,-0.036042,...,0.008554,0.041628,0.071675,-0.009670,-0.037761,-0.050154,-0.028794,-0.038353,0.011298,-0.001504
3431,1,pre-LBD-96#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.000751,0.024619,0.056822,0.087980,-0.087306,0.005802,-0.030083,...,-0.002332,0.043072,0.091577,0.005234,-0.022814,-0.044438,-0.027096,-0.046104,0.014481,0.000398
3432,1,pre-LBD-97#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.002169,0.023951,0.058569,0.092896,-0.085801,0.012066,-0.028993,...,0.001909,0.046956,0.091510,-0.001470,-0.026675,-0.046634,-0.031475,-0.044283,0.010021,-0.001683
3433,1,pre-LBD-98#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.003187,0.033540,0.066936,0.097512,-0.089142,0.006719,-0.040898,...,0.002540,0.036012,0.074694,-0.002932,-0.039761,-0.050872,-0.029519,-0.038850,0.010978,-0.004932
3434,1,pre-LBD-99#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,-0.003345,0.023292,0.056422,0.090034,-0.088472,0.011161,-0.024125,...,-0.000490,0.048869,0.095669,0.000146,-0.021082,-0.044887,-0.032762,-0.042210,0.009381,-0.000027

In [1403]:

metadata_path = ('C://dev//dolphin_initial_testing//DOLPHIN//data-raw//LBD_CZ_002_metadata//preDLB_shared(PSY_RAW).csv')
df_metadata = pd.read_csv(metadata_path, sep=";", encoding="utf-8-sig")

In [1404]:
clinical_data_path = ('C://dev//dolphin_initial_testing//DOLPHIN//data-raw//LBD_CZ_002_metadata//clinical_data_csv.csv')
df_clinical = pd.read_csv(clinical_data_path, sep=",", encoding="utf-8-sig")

In [1405]:
handcrafted_features_path = ('C://dev//dolphin_initial_testing//DOLPHIN//data-raw//LBD_CZ_002_hf//corpus_LBD_CZ_002_writing_results_table_original_filtered_extended.csv')
df_handcrafted_features = pd.read_csv(handcrafted_features_path, sep=";", encoding="utf-8-sig")

In [1406]:
import re
import pandas as pd

def append_col_when_main_contains_source(
    df_main, df_source, *, 
    match_col_main="subject",            # in df_main
    match_col_source="ID_1.meranie",     # in df_source
    value_col="HC0_nHC1_MCI2_MCILB3_baseline",
    new_col_name="diagnosis",
    case=False
):
    df_main = df_main.copy()
    df_source = df_source.copy()

    # normalize + keep only rows in source with non-missing values
    df_main[match_col_main] = df_main[match_col_main].astype(str).str.strip()
    df_source[match_col_source] = df_source[match_col_source].astype(str).str.strip()
    df_source = df_source.dropna(subset=[value_col])

    # init target column
    if new_col_name not in df_main:
        df_main[new_col_name] = pd.NA

    # for each source row, mark all main rows whose subject CONTAINS the source token
    for _, r in df_source.iterrows():
        token = r[match_col_source]
        if not token:
            continue
        mask = df_main[match_col_main].str.contains(re.escape(token), na=False, case=not case)
        # write only where we don't have a value yet (keeps first hit)
        to_set = mask & df_main[new_col_name].isna()
        df_main.loc[to_set, new_col_name] = r[value_col]

    return df_main

In [1407]:
freq_emb_df_lbl = append_col_when_main_contains_source(
    df_main=freq_emb_df,
    df_source=df_metadata,
    match_col_main="subject",
    match_col_source="ID_1.meranie",
    value_col="HC0_nHC1_MCI2_MCILB3_baseline",
    new_col_name="diagnosis",
    case=False
)

In [1408]:
freq_emb_df_lbl.to_csv("LBD_CZ_002_COBEN_dfs/freq_emb_df_half_lbl.csv", sep=";")

In [1409]:

temp_emb_df_lbl = append_col_when_main_contains_source(
    df_main=temp_emb_df,
    df_source=df_metadata,
    match_col_main="subject",
    match_col_source="ID_1.meranie",
    value_col="HC0_nHC1_MCI2_MCILB3_baseline",
    new_col_name="diagnosis",
    case=False
)

In [1410]:

temp_emb_df_lbl.to_csv("LBD_CZ_002_COBEN_dfs/temp_emb_df_half__lbl.csv", sep=";")

In [1411]:

comb_emb_df_lbl = append_col_when_main_contains_source(
    df_main=comb_emb_df,
    df_source=df_metadata,
    match_col_main="subject",
    match_col_source="ID_1.meranie",
    value_col="HC0_nHC1_MCI2_MCILB3_baseline",
    new_col_name="diagnosis",
    case=False
)

In [1412]:
comb_emb_df_lbl.to_csv("LBD_CZ_002_COBEN_dfs/comb_emb_df_half__lbl.csv", sep=";")

In [1413]:

df_handcrafted_lbl = append_col_when_main_contains_source(
    df_main=df_handcrafted_features,
    df_source=df_metadata,
    match_col_main="ID",
    match_col_source="ID_1.meranie",
    value_col="HC0_nHC1_MCI2_MCILB3_baseline",
    new_col_name="diagnosis",
    case=False
)

In [1414]:

df_handcrafted_lbl.to_csv("LBD_CZ_002_COBEN_dfs/df_handcrafted_half_lbl.csv", sep=";")

In [1415]:
#temp_emb_df_complet_lbl = pd.read_csv("LBD_CZ_002_COBEN_dfs/temp_emb_df_lbl.csv", sep=";")

#freq_emb_df_complet_lbl= pd.read_csv("./LBD_CZ_002_COBEN_dfs/freq_emb_df_lbl.csv", sep=";")

#comb_emb_df_complet_lbl= pd.read_csv("LBD_CZ_002_COBEN_dfs/comb_emb_df_lbl.csv", sep=";")

hf_emb_df_complet_lbl= pd.read_csv("LBD_CZ_002_COBEN_dfs/df_handcrafted_lbl.csv", sep=";")

In [1416]:

import pandas as pd

def assign_diagnosis(df: pd.DataFrame,
                     subject_col: str = "subject",
                     diagnosis_col: str = "diagnosis") -> pd.DataFrame:
    """Populate `diagnosis_col` based on text in `subject_col`.

    - rows whose subject contains '#' are left untouched
    - 'HC' → 0.0, 'AD' → 2.0, 'PD' → 4.0
    """
    if diagnosis_col not in df.columns:
        df[diagnosis_col] = pd.NA

    subj = df[subject_col].astype(str)
    has_hash = subj.str.contains("#", na=False)

    mapping = {"HC": 0.0, "AD": 2.0, "PD": 4.0}
    for key, value in mapping.items():
        mask = (~has_hash) & subj.str.contains(key, na=False)
        df.loc[mask, diagnosis_col] = value

    return df

In [1417]:
temp_emb_df_complet_lbl = assign_diagnosis(temp_emb_df_lbl)

freq_emb_df_complet_lbl= assign_diagnosis(freq_emb_df_lbl)

comb_emb_df_complet_lbl=assign_diagnosis(comb_emb_df_lbl)

In [1418]:
import pandas as pd

def assign_diagnosis(df: pd.DataFrame,
                     subject_col: str = "subject",
                     diagnosis_col: str = "diagnosis") -> pd.DataFrame:
    """Populate `diagnosis_col` based on text in `subject_col`.

    - rows whose subject contains '#' are left untouched
    - 'HC' → 0.0, 'AD' → 2.0, 'PD' → 4.0
    """
    if diagnosis_col not in df.columns:
        df[diagnosis_col] = pd.NA

    subj = df[subject_col].astype(str)
    has_hash = subj.str.contains("#", na=False)

    mapping = {"HC": 0.0, "AD": 2.0, "PD": 4.0}
    for key, value in mapping.items():
        mask = (~has_hash) & subj.str.contains(key, na=False)
        df.loc[mask, diagnosis_col] = value

    return df

In [1419]:
def append_multiple_cols_when_main_contains_source(
    df_main, df_source, *,
    match_col_main="subject",
    match_col_source="ID_1.meranie",
    value_cols=("HC0_nHC1_MCI2_MCILB3_baseline",),
    case=False
):
    df_main = df_main.copy()
    df_source = df_source.copy()

    # normalize + clean
    df_main[match_col_main] = df_main[match_col_main].astype(str).str.strip()
    df_source[match_col_source] = df_source[match_col_source].astype(str).str.strip()

    # initialize missing columns
    for col in value_cols:
        if col not in df_main.columns:
            df_main[col] = pd.NA

    # iterate through source
    for _, r in df_source.iterrows():
        token = r[match_col_source]
        if not token or pd.isna(token):
            continue

        # use 'case' argument as passed (was inverted before)
        mask = df_main[match_col_main].str.contains(re.escape(str(token)), na=False, case=case)
        to_set = mask

        # assign all defined value columns
        for col in value_cols:
            if col not in r or pd.isna(r[col]):
                continue
            df_main.loc[to_set & df_main[col].isna(), col] = r[col]

    return df_main

In [1420]:
clinical_hf_emb_df_complet_lbl = append_multiple_cols_when_main_contains_source(
    df_main=hf_emb_df_complet_lbl,
    df_source=df_clinical,
    match_col_main="ID",
    match_col_source="#personalID",
    value_cols=["age",
                "gender",
                "MOCA",
                "education type",
                "education length",
                "memory z-score",
                "visuo-spatial z-score",
                "attention z-score",
                "executive function z-score",
                "GDS"]
)

In [1421]:
temp_emb_df_complet_lbl_2 = temp_emb_df_complet_lbl.drop(temp_emb_df_complet_lbl.columns[0], axis=1)
freq_emb_df_complet_lbl_2 = freq_emb_df_complet_lbl.drop(freq_emb_df_complet_lbl.columns[0], axis=1)
comb_emb_df_complet_lbl_2 = comb_emb_df_complet_lbl.drop(comb_emb_df_complet_lbl.columns[0], axis=1)
hf_emb_df_complet_lbl_2 = hf_emb_df_complet_lbl.drop(hf_emb_df_complet_lbl.columns[0], axis=1)

In [1422]:

hf_emb_df_complet_lbl = hf_emb_df_complet_lbl.drop(hf_emb_df_complet_lbl.columns[0], axis=1)

# Spearsman correlation / finding covariants

In [1423]:

cols_to_convert = clinical_hf_emb_df_complet_lbl.columns[1:]

clinical_hf_emb_df_complet_lbl[cols_to_convert] = (
    clinical_hf_emb_df_complet_lbl[cols_to_convert]
    .apply(lambda col: pd.to_numeric(col.astype(str).str.replace(',', '.'), errors='coerce'))
)

In [1424]:
clinical_hf_emb_df_complet_lbl.dtypes

Unnamed: 0                                                    int64
ID                                                          float64
w.cz.fnusa.15_1_95th percentile of acceleration (in-air)    float64
w.cz.fnusa.16_1_95th percentile of acceleration (in-air)    float64
w.cz.fnusa.17_1_95th percentile of acceleration (in-air)    float64
                                                             ...
memory z-score                                              float64
visuo-spatial z-score                                       float64
attention z-score                                           float64
executive function z-score                                  float64
GDS                                                         float64
Length: 463, dtype: object

In [1425]:

from scipy import stats
import numpy as np

meta_cols=["age",
         #   "gender",
            "MOCA",
            "education type",
            "education length",
            "memory z-score",
            "visuo-spatial z-score",
            "attention z-score",
            "executive function z-score",
            "GDS"]

feature_cols = clinical_hf_emb_df_complet_lbl.drop(columns=['ID', 'diagnosis','gender'] + meta_cols).columns.tolist()


def correlation_to_df(df, feature_cols, meta_cols, corr_type='spearman'):
    from scipy import stats
    corr_results = []
    for feature in feature_cols:
        for meta in meta_cols:
            feature_data = pd.to_numeric(df[feature], errors='coerce')
            meta_data = pd.to_numeric(df[meta], errors='coerce')
            if corr_type == 'spearman':
                corr, p_value = stats.spearmanr(feature_data, meta_data, nan_policy='omit')
            elif corr_type == 'pearson':
                corr, p_value = stats.pearsonr(feature_data.dropna(), meta_data.dropna())
            else:
                raise ValueError("corr_type must be 'spearman' or 'pearson'")
            corr_results.append({
                'feature': feature,
                'meta_variable': meta,
                'correlation': corr,
                'p_value': p_value
            })
    corr_df = pd.DataFrame(corr_results)
    return corr_df

In [1426]:
import numpy as np
import pandas as pd
from scipy import stats

def safe_spearman(x, y, min_n=3):
    """
    x, y: 1D array-like
    returns (rho, p, n_used)
    """
    x = pd.to_numeric(pd.Series(x), errors="coerce")
    y = pd.to_numeric(pd.Series(y), errors="coerce")

    mask = x.notna() & y.notna()
    x2 = x[mask].values
    y2 = y[mask].values
    n = len(x2)

    if n < min_n:
        return np.nan, np.nan, n

    # constant vectors -> undefined correlation
    if np.all(x2 == x2[0]) or np.all(y2 == y2[0]):
        return np.nan, np.nan, n

    rho, p = stats.spearmanr(x2, y2)
    # spearmanr can still return nan if ties/degenerate
    if not np.isfinite(rho):
        rho, p = np.nan, np.nan
    return rho, p, n


def correlation_to_df(df, feature_cols, meta_cols, corr_type="spearman", min_n=3):
    rows = []
    for feat in feature_cols:
        feature_data = df[feat]

        for meta in meta_cols:
            meta_data = df[meta]

            if corr_type == "spearman":
                corr, p_value, n_used = safe_spearman(feature_data, meta_data, min_n=min_n)
            elif corr_type == "pearson":
                # paired dropna for pearson too
                x = pd.to_numeric(feature_data, errors="coerce")
                y = pd.to_numeric(meta_data, errors="coerce")
                mask = x.notna() & y.notna()
                x2, y2 = x[mask].values, y[mask].values
                n_used = len(x2)
                if n_used < min_n or np.all(x2 == x2[0]) or np.all(y2 == y2[0]):
                    corr, p_value = np.nan, np.nan
                else:
                    corr, p_value = stats.pearsonr(x2, y2)
            else:
                raise ValueError("corr_type must be 'spearman' or 'pearson'")

            rows.append({
                "feature": feat,
                "meta": meta,
                "corr": corr,
                "p_value": p_value,
                "n_used": n_used
            })

    return pd.DataFrame(rows)

In [1427]:
clinical_hf_emb_df_complet_lbl

,Unnamed: 0,ID,w.cz.fnusa.15_1_95th percentile of acceleration (in-air),w.cz.fnusa.16_1_95th percentile of acceleration (in-air),w.cz.fnusa.17_1_95th percentile of acceleration (in-air),w.cz.fnusa.18_1_95th percentile of acceleration (in-air),w.cz.fnusa.19_1_95th percentile of acceleration (in-air),w.cz.fnusa.9_1_95th percentile of acceleration (in-air),w.cz.fnusa.15_1_95th percentile of acceleration (on-surface),w.cz.fnusa.16_1_95th percentile of acceleration (on-surface),...,age,gender,MOCA,education type,education length,memory z-score,visuo-spatial z-score,attention z-score,executive function z-score,GDS
0,0,NaN,1382.947668,2062.000865,2892.979665,2192.046228,2013.070361,2235.580284,586.734694,1627.424458,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,2184.038058,2960.491263,2833.151798,NaN,2643.941418,2704.362771,1705.984308,1274.972304,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,NaN,2129.216623,3373.868306,1686.794432,NaN,3212.659823,3435.479391,1657.058812,1573.868658,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,NaN,3973.130385,3650.787752,2810.386562,NaN,3278.226429,2390.344711,2226.888919,2314.558206,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,NaN,973.083976,1194.677753,2163.527710,NaN,1601.144846,1533.402248,581.075743,1754.342814,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,261,NaN,1771.638967,2223.266011,2726.863796,NaN,NaN,NaN,1248.437707,2379.581423,...,55.0,1.0,27.0,2.0,12.0,-0.43,-0.25,0.00,0.22,13.0
262,262,NaN,1587.495217,3116.456725,5244.552340,NaN,3146.502315,3071.576595,1670.497532,5487.155540,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,263,NaN,1529.780961,2846.530626,3170.341400,NaN,2702.591544,1901.945515,914.354564,4092.897902,...,70.0,0.0,26.0,3.0,13.0,-0.66,1.08,-0.33,-1.17,4.0
264,264,NaN,1875.912627,2772.534223,3176.331668,NaN,2088.759949,2417.683099,775.466348,1565.536158,...,75.0,1.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,19.0
265,265,NaN,2703.445789,2786.521814,3986.122126,NaN,3537.716624,3013.638309,1474.404309,4968.999221,...,75.0,0.0,21.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0

In [1428]:
df_hf_clinical_corr = correlation_to_df(clinical_hf_emb_df_complet_lbl, feature_cols, meta_cols, corr_type='spearman')

In [1429]:
df_hf_clinical_corr

,feature,meta,corr,p_value,n_used
0,Unnamed: 0,age,0.221721,0.027412,99
1,Unnamed: 0,MOCA,-0.371650,0.000178,97
2,Unnamed: 0,education type,-0.337577,0.000769,96
3,Unnamed: 0,education length,-0.358016,0.000342,96
4,Unnamed: 0,memory z-score,0.102028,0.325190,95
...,...,...,...,...,...
4054,w.cz.fnusa.1_1_zero-crossing rate of spiral,memory z-score,0.142506,0.168318,95
4055,w.cz.fnusa.1_1_zero-crossing rate of spiral,visuo-spatial z-score,0.122164,0.240807,94
4056,w.cz.fnusa.1_1_zero-crossing rate of spiral,attention z-score,0.209750,0.041343,95
4057,w.cz.fnusa.1_1_zero-crossing rate of spiral,executive function z-score,0.268764,0.008450,95
4058,w.cz.fnusa.1_1_zero-crossing rate of spiral,GDS,-0.162664,0.111405,97

In [1430]:
df_hf_clinical_corr = df_hf_clinical_corr.drop(df_hf_clinical_corr.columns[-1], axis=1)

In [1431]:
df_hf_clinical_corr

,feature,meta,corr,p_value
0,Unnamed: 0,age,0.221721,0.027412
1,Unnamed: 0,MOCA,-0.371650,0.000178
2,Unnamed: 0,education type,-0.337577,0.000769
3,Unnamed: 0,education length,-0.358016,0.000342
4,Unnamed: 0,memory z-score,0.102028,0.325190
...,...,...,...,...
4054,w.cz.fnusa.1_1_zero-crossing rate of spiral,memory z-score,0.142506,0.168318
4055,w.cz.fnusa.1_1_zero-crossing rate of spiral,visuo-spatial z-score,0.122164,0.240807
4056,w.cz.fnusa.1_1_zero-crossing rate of spiral,attention z-score,0.209750,0.041343
4057,w.cz.fnusa.1_1_zero-crossing rate of spiral,executive function z-score,0.268764,0.008450
4058,w.cz.fnusa.1_1_zero-crossing rate of spiral,GDS,-0.162664,0.111405

In [1432]:
# Create separate pivots for correlation and p-value
#df_corr_pivot = df_hf_clinical_corr.pivot(
#    index='feature',
#    columns='meta',
#    values='corr'
#)

df_pval_pivot = df_hf_clinical_corr.pivot(
    index='feature',
    columns='meta',
    values='p_value'
)

In [1433]:
df_pval_pivot[df_pval_pivot < 0.05].count()

meta
GDS                           70
MOCA                          66
age                           43
attention z-score             61
education length              53
education type                53
executive function z-score    24
memory z-score                11
visuo-spatial z-score         69
dtype: int64

# FDR correction

In [1434]:

import numpy as np
import pandas as pd
from statsmodels.stats.multitest import multipletests

def fdr_correction_matrix(df_pvals: pd.DataFrame, alpha: float = 0.05, method: str = "fdr_bh"):
    df = df_pvals.copy()

    # Only numeric columns (skip "feature")
    numeric_cols = df.select_dtypes(include=[float, int]).columns
    arr = df[numeric_cols].to_numpy(dtype=float)

    # Mask NaNs
    mask_na = np.isnan(arr)

    # Take only valid p-values (flatten)
    pvals_flat = arr[~mask_na]

    # FDR
    reject, pvals_corr, _, _ = multipletests(pvals_flat, alpha=alpha, method=method)

    # Prepare output arrays
    arr_fdr = np.full_like(arr, np.nan, dtype=float)
    arr_sig = np.zeros_like(arr, dtype=bool)

    # Fill corrected values
    arr_fdr[~mask_na] = pvals_corr
    arr_sig[~mask_na] = reject

    # Back to DataFrames
    df_fdr = df.copy()
    df_sig = df.copy()

    df_fdr[numeric_cols] = arr_fdr
    df_sig[numeric_cols] = arr_sig

    return df_fdr, df_sig

In [1435]:

df_fdr, df_sig = fdr_correction_matrix(df_pval_pivot, alpha=0.05)

#Show significant (feature, metadata) pairs
significant_pairs = (
    df_sig
         .iloc[:, 1:]         # skip the 'feature' column
         .stack()             # long format
         .loc[lambda s: s]    # keep only True
         .index
         .to_frame(name=["feature", "metadata"])
)
##
significant_pairs

                                                                                                                    feature  \
feature                                            meta
Unnamed: 0                                         MOCA                                                          Unnamed: 0
                                                   visuo-spatial z-score                                         Unnamed: 0
w.cz.fnusa.17_1_slope of velocity (in-air)         visuo-spatial z-score         w.cz.fnusa.17_1_slope of velocity (in-air)
w.cz.fnusa.17_1_slope of vertical velocity (in-... visuo-spatial z-score  w.cz.fnusa.17_1_slope of vertical velocity (in...

                                                                                       metadata
feature                                            meta
Unnamed: 0                                         MOCA                                    MOCA
                                                   visuo-spatial z-score  visuo-spatial z-score
w.cz.fnusa.17_1_slope of velocity (in-air)         visuo-spatial z-score  visuo-spatial z-score
w.cz.fnusa.17_1_slope of vertical velocity (in-... visuo-spatial z-score  visuo-spatial z-score

In [1436]:

df_after_fdr = df_fdr[df_sig]

In [1437]:

df_after_fdr.dropna(how='all', inplace=True)
df_after_fdr

meta,GDS,MOCA,age,attention z-score,education length,education type,executive function z-score,memory z-score,visuo-spatial z-score
feature,,,,,,,,,
Unnamed: 0,0.000039,0.044494,NaN,NaN,NaN,NaN,NaN,NaN,0.032332
w.cz.fnusa.16_1_95th percentile of acceleration (on-surface),0.036790,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.16_1_95th percentile of horizontal acceleration (on-surface),0.044494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.16_1_95th percentile of velocity (on-surface),0.032332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.16_1_95th percentile of vertical acceleration (on-surface),0.040616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.16_1_95th percentile of vertical velocity (on-surface),0.036790,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.17_1_95th percentile of acceleration (on-surface),0.032332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.17_1_95th percentile of angular velocity (on-surface),0.044494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.17_1_95th percentile of horizontal acceleration (on-surface),0.036790,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.17_1_95th percentile of velocity (on-surface),0.040616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.17_1_95th percentile of vertical acceleration (on-surface),0.044494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.17_1_95th percentile of vertical velocity (on-surface),0.040616,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.17_1_median of horizontal velocity (on-surface),0.044494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.17_1_slope of velocity (in-air),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.032332
w.cz.fnusa.17_1_slope of vertical velocity (in-air),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.044494
w.cz.fnusa.19_1_95th percentile of angular velocity (on-surface),0.044160,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
w.cz.fnusa.19_1_95th percentile of horizontal velocity (on-surface),0.044494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Task-wise Dataframe dictionaries creation

- temp_emb_df_complet_lbl_2
- freq_emb_df_complet_lbl_2
- comb_emb_df_complet_lbl_2
- hf_emb_df_complet_lbl_2

In [1438]:
import re

_TASK_RE_CACHE = {}

def task_wise_df_creation(df, task_name):
    # compile once per task to avoid recompilation on every call
    if task_name not in _TASK_RE_CACHE:
        pattern = rf"(?<!\d){re.escape(task_name)}(?!\d)"
        _TASK_RE_CACHE[task_name] = re.compile(pattern)
    mask = df['file_path'].str.contains(_TASK_RE_CACHE[task_name])
    return df[mask].reset_index(drop=True)

In [1726]:

task_list = ['16_1']

task_freq_dfs = {task: task_wise_df_creation(freq_emb_df_complet_lbl, task) for task in task_list}
task_temp_dfs = {task: task_wise_df_creation(temp_emb_df_complet_lbl, task) for task in task_list}
task_comb_dfs = {task: task_wise_df_creation(comb_emb_df_complet_lbl, task) for task in task_list}

In [1728]:
task_freq_dfs.get('16_1')

,label,subject,file_path,emb_0,emb_1,emb_2,emb_3,emb_4,emb_5,emb_6,...,emb_375,emb_376,emb_377,emb_378,emb_379,emb_380,emb_381,emb_382,emb_383,diagnosis
0,1,COBEN-WTABLET-AS-HCD05,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.083544,-0.060777,0.012891,-0.029015,-0.054637,-0.011625,0.056499,...,0.043210,0.009849,0.009091,0.059365,-0.098779,-0.082762,-0.031908,-0.041151,0.010780,0.0
1,1,COBEN-WTABLET-BB-PD08,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.085136,-0.061838,0.014681,-0.029713,-0.055765,-0.011472,0.054101,...,0.046130,0.008138,0.006144,0.060526,-0.098164,-0.083803,-0.030776,-0.038068,0.014324,4.0
2,1,COBEN-WTABLET-DM-AD15,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.084036,-0.060729,0.011847,-0.023066,-0.048384,-0.013491,0.056703,...,0.039476,0.013022,0.012321,0.066669,-0.097668,-0.083027,-0.034101,-0.043573,0.007424,2.0
3,1,COBEN-WTABLET-DM-PD17,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.086901,-0.058496,0.012757,-0.027098,-0.052094,-0.013247,0.052285,...,0.042959,0.007660,0.004263,0.064546,-0.097533,-0.084296,-0.032466,-0.040135,0.020138,4.0
4,1,COBEN-WTABLET-DS-HC36,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.084190,-0.059496,0.013517,-0.022742,-0.046996,-0.010028,0.054389,...,0.044619,0.003740,0.011535,0.067567,-0.097984,-0.085886,-0.035731,-0.040821,0.021223,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260,1,pre-LBD-95#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.082439,-0.059522,0.014227,-0.027601,-0.055028,-0.006960,0.059842,...,0.046694,0.006180,0.012180,0.061367,-0.097433,-0.085698,-0.035846,-0.038183,0.017017,1.0
261,1,pre-LBD-96#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.087452,-0.060449,0.015381,-0.031911,-0.057457,-0.012814,0.054230,...,0.046708,0.006868,0.005021,0.061489,-0.103683,-0.082333,-0.028623,-0.032462,0.017648,1.0
262,1,pre-LBD-97#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.080478,-0.057881,0.012482,-0.026031,-0.050208,-0.015441,0.055298,...,0.038363,0.006159,0.005757,0.064482,-0.095817,-0.082105,-0.031901,-0.042417,0.019951,1.0
263,1,pre-LBD-98#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.083369,-0.061950,0.011937,-0.028328,-0.052157,-0.012789,0.052953,...,0.042043,0.007920,0.005962,0.061730,-0.099253,-0.082583,-0.032489,-0.040236,0.014321,1.0
264,1,pre-LBD-99#1,C:\dev\dolphin_initial_testing\DOLPHIN\out_pre...,0.082913,-0.061125,0.011886,-0.030245,-0.052753,-0.015531,0.053066,...,0.040913,0.010106,0.005992,0.059750,-0.099343,-0.079841,-0.031156,-0.042182,0.017514,1.0

In [1729]:
import re

task_list = ['16_1']

task_hf_dfs = {
    task: hf_emb_df_complet_lbl.loc[
        :,
        hf_emb_df_complet_lbl.columns.astype(str).str.contains(
            rf"(?<!\d){re.escape(task)}(?!\d)", case=False
        )
        | hf_emb_df_complet_lbl.columns.isin(['diagnosis', 'ID'])
    ].copy()
    for task in task_list
}

In [1730]:
task_hf_dfs.get('16_1')

,ID,w.cz.fnusa.16_1_95th percentile of acceleration (in-air),w.cz.fnusa.16_1_95th percentile of acceleration (on-surface),w.cz.fnusa.16_1_95th percentile of angular velocity (in-air),w.cz.fnusa.16_1_95th percentile of angular velocity (on-surface),w.cz.fnusa.16_1_95th percentile of horizontal acceleration (in-air),w.cz.fnusa.16_1_95th percentile of horizontal acceleration (on-surface),w.cz.fnusa.16_1_95th percentile of horizontal velocity (in-air),w.cz.fnusa.16_1_95th percentile of horizontal velocity (on-surface),w.cz.fnusa.16_1_95th percentile of velocity (in-air),...,w.cz.fnusa.16_1_slope of duration of stroke (on-surface),w.cz.fnusa.16_1_slope of horizontal velocity (in-air),w.cz.fnusa.16_1_slope of horizontal velocity (on-surface),w.cz.fnusa.16_1_slope of pressure,w.cz.fnusa.16_1_slope of ratio of the on-surface/in-air stroke duration,w.cz.fnusa.16_1_slope of velocity (in-air),w.cz.fnusa.16_1_slope of velocity (on-surface),w.cz.fnusa.16_1_slope of vertical velocity (in-air),w.cz.fnusa.16_1_slope of vertical velocity (on-surface),diagnosis
0,COBEN-WTABLET-AS-HCD05,"2062,000865","1627,424458","42,99532799","41,26248794","1581,632653","1237,244898","73,8125","43,34821429","88,66874353",...,"0,1425","0,014401847","0,007373697","0,00032611","-0,7985946","-0,013774133","0,008478175","-0,02636724","0,006340195",0.0
1,COBEN-WTABLET-BB-PD08,"2960,491263","1274,972304","10,53834157","35,47426365","2235,331633","1071,428571","87,04464286","41,25892857","129,5622387",...,"0,017333333","1,030485278","0,004103943","1,95E-06","10,6143617","0,731721993","-0,001197435","0,366729957","-0,004777726",4.0
2,COBEN-WTABLET-DM-AD15,"3373,868306","1573,868658","73,4036016","35,14117913","2463,647959","1071,428571","74,0625","42,17857143","99,92483341",...,"-0,122071429","0,020171621","0,000421667","8,86E-05","-0,355756179","-0,013465093","0,006677814","-0,019352612","0,007012501",2.0
3,COBEN-WTABLET-DM-PD17,"3650,787752","2314,558206","44,35833837","63,45305763","3459,183673","2078,125","115,375","59,46428571","122,4343128",...,"-0,007321429","-0,263798196","0,005616518","0,000229657","1,448717156","-0,261007002","0,005623929","-0,014346181","-0,002356657",4.0
4,COBEN-WTABLET-DS-HC36,"1194,677753","1754,342814","48,65182289","35,02544296","657,286352","519,3718112","20,17857143","21,25","58,18485106",...,"-0,060662791","-0,033605945","-0,001419521","0,000426095","-0,763875407","0,071379301","-0,013601043","0,102128131","-0,011902214",0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,pre-LBD-95#1,"2223,266011","2379,581423","98,17477042","57,79995441","2665,816327","1327,248087","101,6339286","45,3125","102,6342612",...,"0,777833333","0,376336799","0,014955242","0,000107672","-1,468404869","0,046830316","0,015143139","-0,304771504","0,005616385",1.0
262,pre-LBD-96#1,"3116,456725","5487,15554","1,954318478","67,92230767","2671,795281","3529,496173","137,0982143","120,0714286","199,5193741",...,"0,312","3,51078668","0,129372445","0,000430134","2,9703125","5,277057484","0,060551212","3,875137363","-0,052747195",1.0
263,pre-LBD-97#1,"2846,530626","4092,897902","16,37973042","55,93971564","1730,867347","2560,586735","58,75","69,80803571","94,75849744",...,"-0,021709091","0,042404153","0,049780347","0,000200622","-0,085893362","-0,094693024","0,005602815","-0,174059881","-0,03408421",1.0
264,pre-LBD-98#1,"2772,534223","1565,536158","45,96436491","30,34264743","2161,272321","1198,979592","95,96875","44,375","115,2120955",...,"0,009715736","0,084958312","0,005701995","-1,48E-05","0,645916702","0,048104771","0,006482702","-0,006622452","0,002900855",1.0
265,pre-LBD-99#1,"2786,521814","4968,999221","42,52884274","62,14960584","1849,489796","2992,1875","73,03571429","77,67857143","118,9675261",...,"-0,1194","-0,570756428","0,102624067","0,000608448","0,496356033","-0,900080738","0,11759691","-0,697495945","0,031105267",1.0

## MCI-LBD vs HC

In [1731]:

task_freq_dfs_lbd_hc = {k: v[~v["diagnosis"].isin([1, 2, 4])].reset_index(drop=True) for k, v in task_freq_dfs.items()}
task_temp_dfs_lbd_hc = {k: v[~v["diagnosis"].isin([1, 2, 4])].reset_index(drop=True) for k, v in task_temp_dfs.items()}
task_comb_dfs_lbd_hc = {k: v[~v["diagnosis"].isin([1, 2, 4])].reset_index(drop=True) for k, v in task_comb_dfs.items()}
task_hf_dfs_lbd_hc = {k: v[~v["diagnosis"].isin([1, 2, 4])].reset_index(drop=True) for k, v in task_hf_dfs.items()}

## MCI-AD vs HC

In [1732]:
task_freq_dfs_ad_hc = {k: v[~v["diagnosis"].isin([1, 3, 4])].reset_index(drop=True) for k, v in task_freq_dfs.items()}
task_temp_dfs_ad_hc = {k: v[~v["diagnosis"].isin([1, 3, 4])].reset_index(drop=True) for k, v in task_temp_dfs.items()}
task_comb_dfs_ad_hc = {k: v[~v["diagnosis"].isin([1, 3, 4])].reset_index(drop=True) for k, v in task_comb_dfs.items()}
task_hf_dfs_ad_hc = {k: v[~v["diagnosis"].isin([1, 3, 4])].reset_index(drop=True) for k, v in task_hf_dfs.items()}

## MCI-PD vs HC

In [1733]:

task_freq_dfs_pd_hc = {k: v[~v["diagnosis"].isin([1, 3, 2])].reset_index(drop=True) for k, v in task_freq_dfs.items()}
task_temp_dfs_pd_hc = {k: v[~v["diagnosis"].isin([1, 3, 2])].reset_index(drop=True) for k, v in task_temp_dfs.items()}
task_comb_dfs_pd_hc = {k: v[~v["diagnosis"].isin([1, 3, 2])].reset_index(drop=True) for k, v in task_comb_dfs.items()}
task_hf_dfs_pd_hc = {k: v[~v["diagnosis"].isin([1, 3, 2])].reset_index(drop=True) for k, v in task_hf_dfs.items()}

## MCI-LBD vs MCI-AD

In [1734]:

task_freq_dfs_ad_lbd = {k: v[~v["diagnosis"].isin([1, 0, 4])].reset_index(drop=True) for k, v in task_freq_dfs.items()}
task_temp_dfs_ad_lbd = {k: v[~v["diagnosis"].isin([1, 0, 4])].reset_index(drop=True) for k, v in task_temp_dfs.items()}
task_comb_dfs_ad_lbd = {k: v[~v["diagnosis"].isin([1, 0, 4])].reset_index(drop=True) for k, v in task_comb_dfs.items()}
task_hf_dfs_ad_lbd = {k: v[~v["diagnosis"].isin([1, 0, 4])].reset_index(drop=True) for k, v in task_hf_dfs.items()}

In [1735]:
task_freq_dfs_lbd_hc = {k: v.drop(columns=['label', 'file_path']) for k, v in task_freq_dfs_lbd_hc.items()}
task_temp_dfs_lbd_hc = {k: v.drop(columns=['label', 'file_path']) for k, v in task_temp_dfs_lbd_hc.items()}
task_comb_dfs_lbd_hc = {k: v.drop(columns=['label', 'file_path']) for k, v in task_comb_dfs_lbd_hc.items()}

In [1736]:

task_freq_dfs_ad_hc = {k: v.drop(columns=['label', 'file_path']) for k, v in task_freq_dfs_ad_hc.items()}
task_temp_dfs_ad_hc = {k: v.drop(columns=['label', 'file_path']) for k, v in task_temp_dfs_ad_hc.items()}
task_comb_dfs_ad_hc = {k: v.drop(columns=['label', 'file_path']) for k, v in task_comb_dfs_ad_hc.items()}

In [1737]:
task_freq_dfs_pd_hc = {k: v.drop(columns=['label', 'file_path']) for k, v in task_freq_dfs_pd_hc.items()}
task_temp_dfs_pd_hc = {k: v.drop(columns=['label', 'file_path']) for k, v in task_temp_dfs_pd_hc.items()}
task_comb_dfs_pd_hc = {k: v.drop(columns=['label', 'file_path']) for k, v in task_comb_dfs_pd_hc.items()}

In [1738]:

task_freq_dfs_ad_lbd = {k: v.drop(columns=['label', 'file_path']) for k, v in task_freq_dfs_ad_lbd.items()}
task_temp_dfs_ad_lbd = {k: v.drop(columns=['label', 'file_path']) for k, v in task_temp_dfs_ad_lbd.items()}
task_comb_dfs_ad_lbd = {k: v.drop(columns=['label', 'file_path']) for k, v in task_comb_dfs_ad_lbd.items()}

In [1739]:
for dfs in (task_freq_dfs_lbd_hc, task_temp_dfs_lbd_hc, task_comb_dfs_lbd_hc, task_hf_dfs_lbd_hc):
    
    for k, v in dfs.items():
        if "diagnosis" in v.columns:
            v["diagnosis"] = v["diagnosis"].replace({3.0: 1, 0.0: 0})

C:\Users\tenNovy\AppData\Local\Temp\ipykernel_1420\2570176340.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  v["diagnosis"] = v["diagnosis"].replace({3.0: 1, 0.0: 0})

In [1740]:
for dfs in (task_freq_dfs_ad_hc, task_temp_dfs_ad_hc, task_comb_dfs_ad_hc, task_hf_dfs_ad_hc):
    
    for k, v in dfs.items():
        if "diagnosis" in v.columns:
            v["diagnosis"] = v["diagnosis"].replace({2.0: 1, 0.0: 0})

C:\Users\tenNovy\AppData\Local\Temp\ipykernel_1420\856415710.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  v["diagnosis"] = v["diagnosis"].replace({2.0: 1, 0.0: 0})

In [1741]:

for dfs in (task_freq_dfs_ad_lbd, task_temp_dfs_ad_lbd, task_comb_dfs_ad_lbd, task_hf_dfs_ad_lbd):
    
    for k, v in dfs.items():
        if "diagnosis" in v.columns:
            v["diagnosis"] = v["diagnosis"].replace({3.0: 1, 2.0: 0})

C:\Users\tenNovy\AppData\Local\Temp\ipykernel_1420\676543069.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  v["diagnosis"] = v["diagnosis"].replace({3.0: 1, 2.0: 0})

In [1742]:
for dfs in (task_freq_dfs_pd_hc, task_temp_dfs_pd_hc, task_comb_dfs_pd_hc, task_hf_dfs_pd_hc):
    
    for k, v in dfs.items():
        if "diagnosis" in v.columns:
            v["diagnosis"] = v["diagnosis"].replace({4.0: 1, 0.0: 0})

C:\Users\tenNovy\AppData\Local\Temp\ipykernel_1420\1503130897.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  v["diagnosis"] = v["diagnosis"].replace({4.0: 1, 0.0: 0})

In [1454]:
task_freq_dfs_ad_hc.get("1_1")

In [1743]:

def miss_val_clean(df, percent_threshold=0.8):
    """
    Cleans the DataFrame by removing columns with more than the specified percentage of missing values.
    
    Parameters
    ----------
    df : pd.DataFrame
        The input DataFrame to be cleaned.
    percent_threshold : float
        The maximum allowed percentage of missing values in a column (between 0 and 1).
        
    Returns
    -------
    pd.DataFrame
        The cleaned DataFrame with columns exceeding the missing value threshold removed.
    """
    df_cleaned = df.copy()
    df_cleaned = df_cleaned.loc[:, df_cleaned.isnull().mean() <= percent_threshold]
    
    cols_to_convert = df_cleaned.columns[1:-1]

    df_cleaned[cols_to_convert] = (
        df_cleaned[cols_to_convert]
        .apply(lambda col: pd.to_numeric(col.astype(str).str.replace(',', '.'), errors='coerce'))
    )

    df_cleaned = df_cleaned.fillna(df_cleaned.mean(numeric_only=True))
    return df_cleaned

In [1744]:

task_hf_dfs_clean_lbd_hc = {k: miss_val_clean(v, percent_threshold=0.8) for k, v in task_hf_dfs_lbd_hc.items()}
task_hf_dfs_clean_ad_hc = {k: miss_val_clean(v, percent_threshold=0.8) for k, v in task_hf_dfs_ad_hc.items()}
task_hf_dfs_clean_ad_lbd = {k: miss_val_clean(v, percent_threshold=0.8) for k, v in task_hf_dfs_ad_lbd.items()}
task_hf_dfs_clean_pd_hc = {k: miss_val_clean(v, percent_threshold=0.8) for k, v in task_hf_dfs_pd_hc.items()}

In [1745]:
task_temp_dfs_lbd_hc.get('19_1')

In [1746]:

# Use this one 
def merge_on_subject_agg_right(df1, df2):
    df1 = df1.copy(); df2 = df2.copy()
    if 'subject' not in df1 and 'ID' in df1: df1 = df1.rename(columns={'ID':'subject'})
    if 'subject' not in df2 and 'ID' in df2: df2 = df2.rename(columns={'ID':'subject'})
    num_cols = df2.select_dtypes('number').columns.tolist()
    agg = {c:'first' for c in df2.columns if c not in num_cols and c!='subject'}
    agg.update({c:'mean' for c in num_cols})
    df2 = df2.groupby('subject', as_index=False).agg(agg)
    return pd.merge(df1, df2, on='subject', how='inner', validate='many_to_one', sort=False)

### MCI-LBD vs HC

In [1747]:
task_hf_compensated_freq_emb_lbl_lbd_hc = {
    k: merge_on_subject_agg_right(task_freq_dfs_lbd_hc[k], task_hf_dfs_clean_lbd_hc[k])
    for k in task_freq_dfs_lbd_hc.keys() & task_hf_dfs_clean_lbd_hc.keys()
}

In [1748]:

task_hf_compensated_temp_emb_lbl_lbd_hc = {
    k: merge_on_subject_agg_right(task_temp_dfs_lbd_hc[k], task_hf_dfs_clean_lbd_hc[k])
    for k in task_temp_dfs_lbd_hc.keys() & task_hf_dfs_clean_lbd_hc.keys()
}

In [1749]:

task_hf_compensated_comb_emb_lbl_lbd_hc = {
    k: merge_on_subject_agg_right(task_comb_dfs_lbd_hc[k], task_hf_dfs_clean_lbd_hc[k])
    for k in task_comb_dfs_lbd_hc.keys() & task_hf_dfs_clean_lbd_hc.keys()
}

In [1750]:
task_hf_comb_emb_lbl_lbd_hc = {
    k: merge_on_subject_agg_right(task_comb_dfs_lbd_hc[k], task_hf_dfs_clean_lbd_hc[k])
    for k in task_comb_dfs_lbd_hc.keys() & task_hf_dfs_clean_lbd_hc.keys()
}

In [1751]:
task_hf_freq_emb_lbl_lbd_hc = {
    k: merge_on_subject_agg_right(task_freq_dfs_lbd_hc[k], task_hf_dfs_clean_lbd_hc[k])
    for k in task_freq_dfs_lbd_hc.keys() & task_hf_dfs_clean_lbd_hc.keys()
}

In [1752]:
task_hf_temp_emb_lbl_lbd_hc = {
    k: merge_on_subject_agg_right(task_temp_dfs_lbd_hc[k], task_hf_dfs_clean_lbd_hc[k])
    for k in task_temp_dfs_lbd_hc.keys() & task_hf_dfs_clean_lbd_hc.keys()
}

### MCI-AD vs HC

In [1753]:
### MCI-AD vs HC
task_hf_compensated_freq_emb_lbl_ad_hc = {
    k: merge_on_subject_agg_right(task_freq_dfs_ad_hc[k], task_hf_dfs_clean_ad_hc[k])
    for k in task_freq_dfs_ad_hc.keys() & task_hf_dfs_clean_ad_hc.keys()
}

task_hf_compensated_temp_emb_lbl_ad_hc = {
    k: merge_on_subject_agg_right(task_temp_dfs_ad_hc[k], task_hf_dfs_clean_ad_hc[k])
    for k in task_temp_dfs_ad_hc.keys() & task_hf_dfs_clean_ad_hc.keys()
}

task_hf_compensated_comb_emb_lbl_ad_hc = {
    k: merge_on_subject_agg_right(task_comb_dfs_ad_hc[k], task_hf_dfs_clean_ad_hc[k])
    for k in task_comb_dfs_ad_hc.keys() & task_hf_dfs_clean_ad_hc.keys()
}
task_hf_comb_emb_lbl_ad_hc= {
    k: merge_on_subject_agg_right(task_comb_dfs_ad_hc[k], task_hf_dfs_clean_ad_hc[k])
    for k in task_comb_dfs_ad_hc.keys() & task_hf_dfs_clean_ad_hc.keys()
}
task_hf_freq_emb_lbl_ad_hc = {
    k: merge_on_subject_agg_right(task_freq_dfs_ad_hc[k], task_hf_dfs_clean_ad_hc[k])
    for k in task_freq_dfs_ad_hc.keys() & task_hf_dfs_clean_ad_hc.keys()
}
task_hf_temp_emb_lbl_ad_hc = {
    k: merge_on_subject_agg_right(task_temp_dfs_ad_hc[k], task_hf_dfs_clean_ad_hc[k])
    for k in task_temp_dfs_ad_hc.keys() & task_hf_dfs_clean_ad_hc.keys()
}

### MCI-LBD vs MCI-AD

In [1754]:
### MCI-LBD vs MCI-LBD
task_hf_compensated_freq_emb_lbl_ad_lbd = {
    k: merge_on_subject_agg_right(task_freq_dfs_ad_lbd[k], task_hf_dfs_clean_ad_lbd[k])
    for k in task_freq_dfs_ad_lbd.keys() & task_hf_dfs_clean_ad_lbd.keys()
}

task_hf_compensated_temp_emb_lbl_ad_lbd = {
    k: merge_on_subject_agg_right(task_temp_dfs_ad_lbd[k], task_hf_dfs_clean_ad_lbd[k])
    for k in task_temp_dfs_ad_lbd.keys() & task_hf_dfs_clean_ad_lbd.keys()
}

task_hf_compensated_comb_emb_lbl_ad_lbd = {
    k: merge_on_subject_agg_right(task_comb_dfs_ad_lbd[k], task_hf_dfs_clean_ad_lbd[k])
    for k in task_comb_dfs_ad_lbd.keys() & task_hf_dfs_clean_ad_lbd.keys()
}
task_hf_comb_emb_lbl_ad_lbd= {
    k: merge_on_subject_agg_right(task_comb_dfs_ad_lbd[k], task_hf_dfs_clean_ad_lbd[k])
    for k in task_comb_dfs_ad_lbd.keys() & task_hf_dfs_clean_ad_lbd.keys()
}
task_hf_freq_emb_lbl_ad_lbd = {
    k: merge_on_subject_agg_right(task_freq_dfs_ad_lbd[k], task_hf_dfs_clean_ad_lbd[k])
    for k in task_freq_dfs_ad_lbd.keys() & task_hf_dfs_clean_ad_lbd.keys()
}
task_hf_temp_emb_lbl_ad_lbd = {
    k: merge_on_subject_agg_right(task_temp_dfs_ad_lbd[k], task_hf_dfs_clean_ad_lbd[k])
    for k in task_temp_dfs_ad_lbd.keys() & task_hf_dfs_clean_ad_lbd.keys()
}

### PD vs HC

In [1755]:

### MCI-AD vs HC
task_hf_compensated_freq_emb_lbl_pd_hc = {
    k: merge_on_subject_agg_right(task_freq_dfs_pd_hc[k], task_hf_dfs_clean_pd_hc[k])
    for k in task_freq_dfs_pd_hc.keys() & task_hf_dfs_clean_pd_hc.keys()
}

task_hf_compensated_temp_emb_lbl_pd_hc = {
    k: merge_on_subject_agg_right(task_temp_dfs_pd_hc[k], task_hf_dfs_clean_pd_hc[k])
    for k in task_temp_dfs_pd_hc.keys() & task_hf_dfs_clean_pd_hc.keys()
}

task_hf_compensated_comb_emb_lbl_pd_hc = {
    k: merge_on_subject_agg_right(task_comb_dfs_pd_hc[k], task_hf_dfs_clean_pd_hc[k])
    for k in task_comb_dfs_pd_hc.keys() & task_hf_dfs_clean_pd_hc.keys()
}
task_hf_comp_emb_lbl_pd_hc= {
    k: merge_on_subject_agg_right(task_comb_dfs_pd_hc[k], task_hf_dfs_clean_pd_hc[k])
    for k in task_comb_dfs_pd_hc.keys() & task_hf_dfs_clean_pd_hc.keys()
}
task_hf_freq_emb_lbl_pd_hc = {
    k: merge_on_subject_agg_right(task_freq_dfs_pd_hc[k], task_hf_dfs_clean_pd_hc[k])
    for k in task_freq_dfs_pd_hc.keys() & task_hf_dfs_clean_pd_hc.keys()
}
task_hf_temp_emb_lbl_pd_hc = {
    k: merge_on_subject_agg_right(task_temp_dfs_pd_hc[k], task_hf_dfs_clean_pd_hc[k])
    for k in task_temp_dfs_pd_hc.keys() & task_hf_dfs_clean_pd_hc.keys()
}

In [1756]:
def x_y_split(df, split_param):
    if split_param is None or split_param == "diagnosis_y":
        #embedding_cols = df[1:-1]
        X = df.iloc[:,1:-2].values
        y = df["diagnosis_y"].values
    elif split_param != None: 
        embedding_cols = [c for c in df.columns if c.startswith(split_param)]
        #X = df[embedding_cols].values
        X = df.iloc[:,1:-2].values
        y = df["diagnosis"].values
    
    return X, y

In [1757]:
def remove_leaking_labels(df, label_string = 'diagnosis_x'):
    df_cleaned = df.copy()
    df_cleaned = df_cleaned.drop(label_string, axis = 1)
    return df_cleaned

In [1758]:
task_hf_compensated_freq_emb_lbl_ad_hc = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_freq_emb_lbl_ad_hc.items()}
task_hf_compensated_temp_emb_lbl_ad_hc = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_temp_emb_lbl_ad_hc.items()}
task_hf_compensated_comb_emb_lbl_ad_hc = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_comb_emb_lbl_ad_hc.items()}

task_hf_compensated_freq_emb_lbl_lbd_hc = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_freq_emb_lbl_lbd_hc.items()}
task_hf_compensated_temp_emb_lbl_lbd_hc = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_temp_emb_lbl_lbd_hc.items()}
task_hf_compensated_comb_emb_lbl_lbd_hc = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_comb_emb_lbl_lbd_hc.items()}


task_hf_compensated_freq_emb_lbl_ad_lbd = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_freq_emb_lbl_ad_lbd.items()}
task_hf_compensated_temp_emb_lbl_ad_lbd = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_temp_emb_lbl_ad_lbd.items()}
task_hf_compensated_comb_emb_lbl_ad_lbd = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_comb_emb_lbl_ad_lbd.items()}

task_hf_compensated_freq_emb_lbl_pd_hc = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_freq_emb_lbl_pd_hc.items()}
task_hf_compensated_temp_emb_lbl_pd_hc = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_temp_emb_lbl_pd_hc.items()}
task_hf_compensated_comb_emb_lbl_pd_hc = {k: remove_leaking_labels(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_comb_emb_lbl_pd_hc.items()}

In [1759]:
def leaking_sanity_test(df, label_string='diagnosis_x'):
    if label_string in df.columns:
        print(f"Leaking label '{label_string}' found in DataFrame columns.")
    else:
        print(f"No leaking label '{label_string}' found in DataFrame columns.")

In [1760]:
{k: leaking_sanity_test(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_freq_emb_lbl_ad_hc.items()}
{k: leaking_sanity_test(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_temp_emb_lbl_ad_hc.items()}
{k: leaking_sanity_test(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_comb_emb_lbl_ad_hc.items()}

{k: leaking_sanity_test(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_freq_emb_lbl_lbd_hc.items()}
{k: leaking_sanity_test(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_temp_emb_lbl_lbd_hc.items()}
{k: leaking_sanity_test(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_comb_emb_lbl_lbd_hc.items()}


{k: leaking_sanity_test(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_freq_emb_lbl_ad_lbd.items()}
{k: leaking_sanity_test(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_temp_emb_lbl_ad_lbd.items()}
{k: leaking_sanity_test(v, label_string = 'diagnosis_x') for k,v in task_hf_compensated_comb_emb_lbl_ad_lbd.items()}

No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.
No leaking label 'diagnosis_x' found in DataFrame columns.

{'16_1': None}

# OPTUNA + XGBoost

In [1473]:

#import os, json
#import numpy as np
#import pandas as pd
#import optuna, xgboost as xgb
#from typing import Dict, Tuple
#from sklearn.model_selection import StratifiedKFold, train_test_split
#from sklearn.model_selection import LeaveOneOut
#from sklearn.metrics import (
    #balanced_accuracy_score,
    #roc_auc_score,
    #confusion_matrix,
    #classification_report,
    #RocCurveDisplay,
    #ConfusionMatrixDisplay,
    #matthews_corrcoef
#)
#
## def x_y_split(df): ...  # your splitter (must return X, y)
#def _safe_feature_names(X, fallback_dim=None):
    #if hasattr(X, "columns"):
        #return list(X.columns)
    #if hasattr(X, "feature_names_in_"):
        #return list(X.feature_names_in_)
    #if fallback_dim is None and hasattr(X, "shape"):
        #fallback_dim = X.shape[1]
    #return [f"f{i}" for i in range(int(fallback_dim or 0))]
#
#def _plot_feature_importance(model, feature_names, out_dir: str):
    #"""Save multiple feature-importance views from XGBoost."""
    #import matplotlib.pyplot as plt
    #import numpy as np
    #from collections import defaultdict
    #os.makedirs(out_dir, exist_ok=True)
#
    ## 1) sklearn API importances (gain-based)
    #try:
        #importances = getattr(model, "feature_importances_", None)
        #if importances is not None and len(importances) == len(feature_names):
            #order = np.argsort(importances)[::-1]
            #top_idx = order[:50]  # limit to top-50 for readability
            #plt.figure()
            #plt.barh([feature_names[i] for i in top_idx][::-1], importances[top_idx][::-1])
            #plt.title("XGB feature_importances_ (top-50)")
            #plt.tight_layout()
            #plt.savefig(os.path.join(out_dir, "feature_importances_sklearn.png"), dpi=200, bbox_inches="tight")
            #plt.close()
    #except Exception:
        #pass
#
    ## 2) Booster importances (weight/gain/cover)
    #try:
        #booster = model.get_booster()
        #for typ in ["weight", "gain", "cover", "total_gain", "total_cover"]:
            #score_dict = booster.get_score(importance_type=typ)
            #if not score_dict:
                #continue
            ## Map 'f0'.. to friendly names
            #vals = []
            #names = []
            #for k, v in score_dict.items():
                #if k.startswith("f"):
                    #idx = int(k[1:])
                    #if 0 <= idx < len(feature_names):
                        #names.append(feature_names[idx])
                    #else:
                        #names.append(k)
                #else:
                    #names.append(k)
                #vals.append(v)
            #order = np.argsort(vals)[::-1]
            #top = min(50, len(order))
            #plt.figure()
            #plt.barh([names[i] for i in order[:top]][::-1], np.array(vals)[order[:top]][::-1])
            #plt.title(f"Booster feature importance — {typ} (top-{top})")
            #plt.tight_layout()
            #plt.savefig(os.path.join(out_dir, f"feature_importances_{typ}.png"), dpi=200, bbox_inches="tight")
            #plt.close()
    #except Exception:
        #pass
#
#def _save_shap_summaries(model, X_ref, feature_names, out_dir: str, max_display: int = 30, sample: int = 1000):
    #"""
    #Compute SHAP (TreeExplainer) and save bar + beeswarm plots.
    #Skips silently if shap not installed or backend issues arise.
    #"""
    #try:
        #import shap
        #import numpy as np
        #import matplotlib.pyplot as plt
    #except Exception:
        #return
#
    #try:
        ## Downsample for speed
        #if hasattr(X_ref, "iloc"):
            #X_use = X_ref.sample(min(sample, len(X_ref)), random_state=0)
            #X_np = X_use.values
        #else:
            #X_np = X_ref
            #if X_np.shape[0] > sample:
                #rng = np.random.default_rng(0)
                #idx = rng.choice(X_np.shape[0], size=sample, replace=False)
                #X_np = X_np[idx]
#
        #explainer = shap.TreeExplainer(model)
        #shap_values = explainer.shap_values(X_np)
#
        ## Handle binary classification: shap returns array (n, p)
        #if isinstance(shap_values, list) and len(shap_values) == 2:
            ## pick positive class
            #sv = shap_values[1]
        #else:
            #sv = shap_values
#
        ## Bar plot (mean |SHAP|)
        #try:
            #plt.figure()
            #shap.summary_plot(sv, X_np, feature_names=feature_names, plot_type="bar", show=False, max_display=max_display)
            #plt.tight_layout()
            #plt.savefig(os.path.join(out_dir, "shap_summary_bar.png"), dpi=200, bbox_inches="tight")
            #plt.close()
        #except Exception:
            #pass
#
        ## Beeswarm
        #try:
            #plt.figure()
            #shap.summary_plot(sv, X_np, feature_names=feature_names, show=False, max_display=max_display)
            #plt.tight_layout()
            #plt.savefig(os.path.join(out_dir, "shap_summary_beeswarm.png"), dpi=200, bbox_inches="tight")
            #plt.close()
        #except Exception:
            #pass
    #except Exception:
        ## Any SHAP error -> skip silently
        #return
#
#def _pick_device():
    #try:
        #_ = xgb.core.get_cuda_compute_capabilities()
        #return {"tree_method": "hist", "device": "cuda"}
    #except Exception:
        #return {"tree_method": "hist", "device": "cpu"}
#
#def _ensure_dir(path: str):
    #os.makedirs(path, exist_ok=True)
#
#def _save_json(d: dict, path: str):
    #with open(path, "w", encoding="utf-8") as f:
        #json.dump(d, f, indent=2, ensure_ascii=False)
#
#def make_xgb_objective(X, y, scoring: str = "balanced_accuracy", n_splits: int = 5, random_state: int = 42):
    #if scoring == "balanced_accuracy":
        #from sklearn.metrics import balanced_accuracy_score as metric_fn
        #needs_proba = False
        #eval_metric = "logloss"
    #elif scoring == "roc_auc":
        #from sklearn.metrics import roc_auc_score as metric_fn
        #needs_proba = True
        #eval_metric = "auc"
    #else:
        #raise ValueError("scoring must be 'balanced_accuracy' or 'roc_auc'")
#
    #folds = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    ##folds = LeaveOneOut()
    #device_kwargs = _pick_device()
#
    #pos_ratio = float(np.mean(y))
    #scale_pos_weight = ((1.0 - pos_ratio) / pos_ratio) if 0 < pos_ratio < 1 else 1.0
#
    #def objective(trial: optuna.Trial) -> float:
        #params = {
            #"max_depth": trial.suggest_int("max_depth", 3, 10),
            #"learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
            #"n_estimators": trial.suggest_int("n_estimators", 200, 1500),
            #"subsample": trial.suggest_float("subsample", 0.5, 1.0),
            #"colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
            #"min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
            #"gamma": trial.suggest_float("gamma", 0.0, 5.0),
            #"reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
            #"reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
            #"max_delta_step": trial.suggest_int("max_delta_step", 0, 10),
            #"objective": "binary:logistic",
            #"eval_metric": eval_metric,
            #"n_jobs": 1,  # keep each trial single-threaded
            #"scale_pos_weight": scale_pos_weight,
            #**device_kwargs,
        #}
#
        #scores = []
        #for tr_idx, va_idx in folds.split(X, y):
            #if hasattr(X, "iloc"):
                #X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
                #y_tr, y_va = y.iloc[tr_idx], y.iloc[va_idx]
            #else:
                #X_tr, X_va = X[tr_idx], X[va_idx]
                #y_tr, y_va = y[tr_idx], y[va_idx]
#
            #model = xgb.XGBClassifier(**params)
            #model.fit(
                #X_tr, y_tr,
                #eval_set=[(X_va, y_va)],
                ##early_stopping_rounds=50,
                #verbose=False,
            #)
#
            #if needs_proba:
                #y_score = model.predict_proba(X_va)[:, 1]
                #score = metric_fn(y_va, y_score)
            #else:
                #y_pred = model.predict(X_va)
                #score = metric_fn(y_va, y_pred)
            #scores.append(score)
#
            #trial.report(np.mean(scores), len(scores))
            #if trial.should_prune():
                #raise optuna.TrialPruned()
#
        #return float(np.mean(scores))
#
    #return objective
#
#def _evaluate_and_save(name: str, model, X_test, y_test, out_dir: str, feature_names=None, X_ref_for_shap=None):
    #"""Compute metrics, plot ROC + confusion matrix, and save everything."""
    #_ensure_dir(out_dir)
#
    ## Predictions
    #y_proba = None
    #try:
        #y_proba = model.predict_proba(X_test)[:, 1]
    #except Exception:
        #pass
    #y_pred = model.predict(X_test)
#
    ## Metrics
    #metrics = {
        #"balanced_accuracy": float(balanced_accuracy_score(y_test, y_pred)),
        #"mcc": None,
        #"roc_auc": None,
        #"sensitivity": None,   # <-- NEW
        #"specificity": None,   # <-- NEW
        #"classification_report": None,
    #}
    ## MCC
    #try:
        #metrics["mcc"] = float(matthews_corrcoef(y_test, y_pred))
    #except Exception:
        #pass
    ## ROC-AUC if both classes present and proba available
    #try:
        #if y_proba is not None and len(np.unique(y_test)) == 2:
            #metrics["roc_auc"] = float(roc_auc_score(y_test, y_proba))
        #else:
            #metrics["roc_auc"] = None
    #except Exception:
        #metrics["roc_auc"] = None
    ## --- Sensitivity & Specificity (labels fixed to [0,1]) ---
    #try:
        #cm = confusion_matrix(y_test, y_pred, labels=[0, 1])
        #tn, fp, fn, tp = cm.ravel()
        #sens_den = tp + fn
        #spec_den = tn + fp
        #metrics["sensitivity"] = float(tp / sens_den) if sens_den > 0 else None
        #metrics["specificity"] = float(tn / spec_den) if spec_den > 0 else None
    #except Exception:
        #pass
#
#
    ## Classification report (as dict)
    #try:
        #metrics["classification_report"] = classification_report(y_test, y_pred, output_dict=True)
    #except Exception:
        #metrics["classification_report"] = None
#
    ## Confusion matrix plot
    #try:
        #cm = confusion_matrix(y_test, y_pred)
        #disp = ConfusionMatrixDisplay(cm)
        #import matplotlib.pyplot as plt
        #plt.figure()
        #disp.plot(values_format="d")
        #plt.title(f"Confusion Matrix — {name}")
        #plt.savefig(os.path.join(out_dir, "confusion_matrix.png"), dpi=200, bbox_inches="tight")
        #plt.close()
    #except Exception:
        #pass
#
    ## ROC curve plot
    #try:
        #if y_proba is not None and len(np.unique(y_test)) == 2:
            #import matplotlib.pyplot as plt
            #plt.figure()
            #RocCurveDisplay.from_predictions(y_test, y_proba)
            #plt.title(f"ROC Curve — {name}")
            #plt.savefig(os.path.join(out_dir, "roc_curve.png"), dpi=200, bbox_inches="tight")
            #plt.close()
    #except Exception:
        #pass
#
    ## Feature names
    #if feature_names is None:
        #feature_names = _safe_feature_names(X_test)
#
    ## Feature importance plots
    #try:
        #_plot_feature_importance(model, feature_names, out_dir)
    #except Exception:
        #pass
#
    ## SHAP plots (optional)
    #try:
        #if X_ref_for_shap is None:
            #X_ref_for_shap = X_test
        #_save_shap_summaries(model, X_ref_for_shap, feature_names, out_dir)
    #except Exception:
        #pass
#
    ## Save metrics JSON
    #_save_json(metrics, os.path.join(out_dir, "metrics.json"))
    #return metrics
#
#def optimize_many(
    #dfs: Dict[str, pd.DataFrame],
    #x_y_split_fn,
    #scoring: str = "balanced_accuracy",
    #n_trials: int = 500,
    #n_splits: int = 5,
    #random_state: int = 42,
    #n_jobs_trials: int = -1,
    #output_dir: str = "xgb_results",
    #test_size: float = 0.20,
    #split_param: str = "emb_",
#) -> Tuple[pd.DataFrame, Dict[str, xgb.XGBClassifier], Dict[str, optuna.Study]]:
    #"""
    #Runs Optuna per dataset, evaluates on a held-out test set,
    #and saves plots + metrics in output_dir/<dataset_name>/
    #"""
    #results = []
    #best_models: Dict[str, xgb.XGBClassifier] = {}
    #studies: Dict[str, optuna.Study] = {}
#
    #_ensure_dir(output_dir)
#
    #for name, df in dfs.items():
        #X, y = x_y_split_fn(df, split_param=split_param)
#
        ## To numpy for fast indexing, but keep DataFrame support
        #X_arr = X.values if hasattr(X, "values") else X
        #y_arr = y.values if hasattr(y, "values") else y
#
        #feature_names = _safe_feature_names(X)
        ## Keep names before converting to numpy
#
        ## Hold-out test split (kept untouched for final evaluation)
        #X_train, X_test, y_train, y_test = train_test_split(
            #X_arr, y_arr, test_size=test_size, random_state=random_state, stratify=y_arr
        #)
#
        ## Build objective on TRAIN ONLY
        #objective = make_xgb_objective(X_train, y_train, scoring=scoring, n_splits=n_splits, random_state=random_state)
#
        #study = optuna.create_study(
            #study_name=f"{name}_{scoring}",
            #direction="maximize",
            #sampler=optuna.samplers.TPESampler(seed=random_state),
            #pruner=optuna.pruners.MedianPruner(n_startup_trials=10),
        #)
        #study.optimize(objective, n_trials=n_trials, show_progress_bar=True, n_jobs=n_jobs_trials)
        #studies[name] = study
#
        ## Train final model on TRAIN using best params (with small VA split for early stopping)
        #device_kwargs = _pick_device()
        #pos_ratio = float(np.mean(y_train))
        #spw = ((1.0 - pos_ratio) / pos_ratio) if 0 < pos_ratio < 1 else 1.0
#
        #best_params = {
            #**study.best_params,
            #"objective": "binary:logistic",
            #"eval_metric": "auc" if scoring == "roc_auc" else "logloss",
            #"n_jobs": 0,
            #"scale_pos_weight": spw,
            #**device_kwargs,
        #}
        #final_model = xgb.XGBClassifier(**best_params)
#
        ## Early stopping split inside TRAIN
        #X_tr, X_va, y_tr, y_va = train_test_split(
            #X_train, y_train, test_size=0.15, random_state=random_state, stratify=y_train
        #)
        #final_model.fit(
            #X_tr, y_tr,
            #eval_set=[(X_va, y_va)],
            ##early_stopping_rounds=50,
            #verbose=False,
        #)
#
        ## Save per-dataset artifacts
        #ds_out = os.path.join(output_dir, name)
        #_ensure_dir(ds_out)
#
        ## Evaluate on TEST and save plots/metrics
        #metrics = _evaluate_and_save(
            #name, final_model, X_test, y_test, ds_out,
            #feature_names=feature_names,
            #X_ref_for_shap=X_test
        #)
#
        ## Save best params + study summary
        #_save_json({"best_params": study.best_params, "best_value": study.best_value}, os.path.join(ds_out, "best.json"))
#
        ## Optional: save model
        #try:
            #import joblib
            #joblib.dump(final_model, os.path.join(ds_out, "model.joblib"))
        #except Exception:
            #pass
#
        #best_models[name] = final_model
        #results.append({
            #"dataset": name,
            #"cv_best_value": study.best_value,
            #"test_balanced_accuracy": metrics.get("balanced_accuracy"),
            #"test_roc_auc": metrics.get("roc_auc"),
            #"n_trials": len(study.trials),
        #})
#
    #summary_df = pd.DataFrame(results).sort_values(by="test_balanced_accuracy", ascending=False).reset_index(drop=True)
    ## Save a global summary too
    #summary_df.to_csv(os.path.join(output_dir, "summary.csv"), index=False)
    #return summary_df, best_models, studies
#

In [1474]:
#import os, json
#import numpy as np
#import pandas as pd
#import optuna, xgboost as xgb
#from typing import Dict, Tuple
#from sklearn.model_selection import StratifiedKFold, train_test_split, LeaveOneOut
#from sklearn.metrics import (
    #balanced_accuracy_score,
    #roc_auc_score,
    #confusion_matrix,
    #classification_report,
    #RocCurveDisplay,
    #ConfusionMatrixDisplay,
    #matthews_corrcoef
#)
#
## def x_y_split(df): ...  # your splitter (must return X, y)
#def _safe_feature_names(X, fallback_dim=None):
    #if hasattr(X, "columns"):
        #return list(X.columns)
    #if hasattr(X, "feature_names_in_"):
        #return list(X.feature_names_in_)
    #if fallback_dim is None and hasattr(X, "shape"):
        #fallback_dim = X.shape[1]
    #return [f"f{i}" for i in range(int(fallback_dim or 0))]
#
#def _plot_feature_importance(model, feature_names, out_dir: str):
    #"""Save multiple feature-importance views from XGBoost."""
    #import matplotlib.pyplot as plt
    #import numpy as np
    #from collections import defaultdict
    #os.makedirs(out_dir, exist_ok=True)
#
    ## 1) sklearn API importances (gain-based)
    #try:
        #importances = getattr(model, "feature_importances_", None)
        #if importances is not None and len(importances) == len(feature_names):
            #order = np.argsort(importances)[::-1]
            #top_idx = order[:50]  # limit to top-50 for readability
            #plt.figure()
            #plt.barh([feature_names[i] for i in top_idx][::-1], importances[top_idx][::-1])
            #plt.title("XGB feature_importances_ (top-50)")
            #plt.tight_layout()
            #plt.savefig(os.path.join(out_dir, "feature_importances_sklearn.png"), dpi=200, bbox_inches="tight")
            #plt.close()
    #except Exception:
        #pass
#
    ## 2) Booster importances (weight/gain/cover)
    #try:
        #booster = model.get_booster()
        #for typ in ["weight", "gain", "cover", "total_gain", "total_cover"]:
            #score_dict = booster.get_score(importance_type=typ)
            #if not score_dict:
                #continue
            ## Map 'f0'.. to friendly names
            #vals = []
            #names = []
            #for k, v in score_dict.items():
                #if k.startswith("f"):
                    #idx = int(k[1:])
                    #if 0 <= idx < len(feature_names):
                        #names.append(feature_names[idx])
                    #else:
                        #names.append(k)
                #else:
                    #names.append(k)
                #vals.append(v)
            #order = np.argsort(vals)[::-1]
            #top = min(50, len(order))
            #plt.figure()
            #plt.barh([names[i] for i in order[:top]][::-1], np.array(vals)[order[:top]][::-1])
            #plt.title(f"Booster feature importance — {typ} (top-{top})")
            #plt.tight_layout()
            #plt.savefig(os.path.join(out_dir, f"feature_importances_{typ}.png"), dpi=200, bbox_inches="tight")
            #plt.close()
    #except Exception:
        #pass
#
#def _save_shap_summaries(model, X_ref, feature_names, out_dir: str, max_display: int = 30, sample: int = 1000):
    #"""
    #Compute SHAP (TreeExplainer) and save bar + beeswarm plots.
    #Skips silently if shap not installed or backend issues arise.
    #"""
    #try:
        #import shap
        #import numpy as np
        #import matplotlib.pyplot as plt
    #except Exception:
        #return
#
    #try:
        ## Downsample for speed
        #if hasattr(X_ref, "iloc"):
            #X_use = X_ref.sample(min(sample, len(X_ref)), random_state=0)
            #X_np = X_use.values
        #else:
            #X_np = X_ref
            #if X_np.shape[0] > sample:
                #rng = np.random.default_rng(0)
                #idx = rng.choice(X_np.shape[0], size=sample, replace=False)
                #X_np = X_np[idx]
#
        #explainer = shap.TreeExplainer(model)
        #shap_values = explainer.shap_values(X_np)
#
        ## Handle binary classification: shap returns array (n, p)
        #if isinstance(shap_values, list) and len(shap_values) == 2:
            ## pick positive class
            #sv = shap_values[1]
        #else:
            #sv = shap_values
#
        ## Bar plot (mean |SHAP|)
        #try:
            #plt.figure()
            #shap.summary_plot(sv, X_np, feature_names=feature_names, plot_type="bar", show=False, max_display=max_display)
            #plt.tight_layout()
            #plt.savefig(os.path.join(out_dir, "shap_summary_bar.png"), dpi=200, bbox_inches="tight")
            #plt.close()
        #except Exception:
            #pass
#
        ## Beeswarm
        #try:
            #plt.figure()
            #shap.summary_plot(sv, X_np, feature_names=feature_names, show=False, max_display=max_display)
            #plt.tight_layout()
            #plt.savefig(os.path.join(out_dir, "shap_summary_beeswarm.png"), dpi=200, bbox_inches="tight")
            #plt.close()
        #except Exception:
            #pass
    #except Exception:
        ## Any SHAP error -> skip silently
        #return
#
#def _pick_device():
    #try:
        #_ = xgb.core.get_cuda_compute_capabilities()
        #return {"tree_method": "hist", "device": "cuda"}
    #except Exception:
        #return {"tree_method": "hist", "device": "cpu"}
#
#def _ensure_dir(path: str):
    #os.makedirs(path, exist_ok=True)
#
#def _save_json(d: dict, path: str):
    #with open(path, "w", encoding="utf-8") as f:
        #json.dump(d, f, indent=2, ensure_ascii=False)
#
#def make_xgb_objective(X, y, scoring: str = "balanced_accuracy", cv_strategy: str = "loo", 
                       #n_splits: int = 5, random_state: int = 42):
    #"""
    #Create Optuna objective function with configurable CV strategy.
    #
    #Parameters:
    #-----------
    #cv_strategy : str
        #Either 'skf' (StratifiedKFold) or 'loo' (LeaveOneOut)
    #n_splits : int
        #Number of splits for StratifiedKFold (ignored for LOO)
    #"""
    #if scoring == "balanced_accuracy":
        #from sklearn.metrics import balanced_accuracy_score as metric_fn
        #needs_proba = False
        #eval_metric = "logloss"
    #elif scoring == "roc_auc":
        #from sklearn.metrics import roc_auc_score as metric_fn
        #needs_proba = True
        #eval_metric = "auc"
    #else:
        #raise ValueError("scoring must be 'balanced_accuracy' or 'roc_auc'")
#
    ## Choose CV strategy
    #if cv_strategy == "loo":
        #folds = LeaveOneOut()
        #print(f"Using Leave-One-Out CV with {len(y)} folds")
    #elif cv_strategy == "skf":
        #folds = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=random_state)
        #print(f"Using Stratified K-Fold CV with {n_splits} folds")
    #else:
        #raise ValueError("cv_strategy must be 'skf' or 'loo'")
#
    #device_kwargs = _pick_device()
#
    #pos_ratio = float(np.mean(y))
    #scale_pos_weight = ((1.0 - pos_ratio) / pos_ratio) if 0 < pos_ratio < 1 else 1.0
#
    #def objective(trial: optuna.Trial) -> float:
        #params = {
            #"max_depth": trial.suggest_int("max_depth", 3, 10),
            #"learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
            #"n_estimators": trial.suggest_int("n_estimators", 200, 1500),
            #"subsample": trial.suggest_float("subsample", 0.5, 1.0),
            #"colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
            #"min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
            #"gamma": trial.suggest_float("gamma", 0.0, 5.0),
            #"reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
            #"reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
            #"max_delta_step": trial.suggest_int("max_delta_step", 0, 10),
            #"objective": "binary:logistic",
            #"eval_metric": eval_metric,
            #"n_jobs": 1,  # keep each trial single-threaded
            #"scale_pos_weight": scale_pos_weight,
            #**device_kwargs,
        #}
#
        #scores = []
        #for fold_idx, (tr_idx, va_idx) in enumerate(folds.split(X, y)):
            #if hasattr(X, "iloc"):
                #X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
                #y_tr, y_va = y.iloc[tr_idx], y.iloc[va_idx]
            #else:
                #X_tr, X_va = X[tr_idx], X[va_idx]
                #y_tr, y_va = y[tr_idx], y[va_idx]
#
            #model = xgb.XGBClassifier(**params)
            #
            ## For LOO, skip early stopping (only 1 validation sample)
            #if cv_strategy == "loo":
                #model.fit(X_tr, y_tr, verbose=False)
            #else:
                #model.fit(
                    #X_tr, y_tr,
                    #eval_set=[(X_va, y_va)],
                    #verbose=False,
                #)
#
            #if needs_proba:
                #y_score = model.predict_proba(X_va)[:, 1]
                #score = metric_fn(y_va, y_score)
            #else:
                #y_pred = model.predict(X_va)
                #score = metric_fn(y_va, y_pred)
            #scores.append(score)
#
            ## Report intermediate values and check for pruning
            ## For LOO: report every 10 folds to reduce overhead
            #if cv_strategy == "loo":
                #if (fold_idx + 1) % 10 == 0:
                    #trial.report(np.mean(scores), fold_idx)
                    #if trial.should_prune():
                        #raise optuna.TrialPruned()
            #else:
                #trial.report(np.mean(scores), fold_idx)
                #if trial.should_prune():
                    #raise optuna.TrialPruned()
#
        #return float(np.mean(scores))
#
    #return objective
#
#def _evaluate_and_save(name: str, model, X_test, y_test, out_dir: str, feature_names=None, X_ref_for_shap=None):
    #"""Compute metrics, plot ROC + confusion matrix, and save everything."""
    #_ensure_dir(out_dir)
#
    ## Predictions
    #y_proba = None
    #try:
        #y_proba = model.predict_proba(X_test)[:, 1]
    #except Exception:
        #pass
    #y_pred = model.predict(X_test)
#
    ## Metrics
    #metrics = {
        #"balanced_accuracy": float(balanced_accuracy_score(y_test, y_pred)),
        #"mcc": None,
        #"roc_auc": None,
        #"sensitivity": None,
        #"specificity": None,
        #"classification_report": None,
    #}
    ## MCC
    #try:
        #metrics["mcc"] = float(matthews_corrcoef(y_test, y_pred))
    #except Exception:
        #pass
    ## ROC-AUC if both classes present and proba available
    #try:
        #if y_proba is not None and len(np.unique(y_test)) == 2:
            #metrics["roc_auc"] = float(roc_auc_score(y_test, y_proba))
        #else:
            #metrics["roc_auc"] = None
    #except Exception:
        #metrics["roc_auc"] = None
    ## --- Sensitivity & Specificity (labels fixed to [0,1]) ---
    #try:
        #cm = confusion_matrix(y_test, y_pred, labels=[0, 1])
        #tn, fp, fn, tp = cm.ravel()
        #sens_den = tp + fn
        #spec_den = tn + fp
        #metrics["sensitivity"] = float(tp / sens_den) if sens_den > 0 else None
        #metrics["specificity"] = float(tn / spec_den) if spec_den > 0 else None
    #except Exception:
        #pass
#
    ## Classification report (as dict)
    #try:
        #metrics["classification_report"] = classification_report(y_test, y_pred, output_dict=True)
    #except Exception:
        #metrics["classification_report"] = None
#
    ## Confusion matrix plot
    #try:
        #cm = confusion_matrix(y_test, y_pred)
        #disp = ConfusionMatrixDisplay(cm)
        #import matplotlib.pyplot as plt
        #plt.figure()
        #disp.plot(values_format="d")
        #plt.title(f"Confusion Matrix — {name}")
        #plt.savefig(os.path.join(out_dir, "confusion_matrix.png"), dpi=200, bbox_inches="tight")
        #plt.close()
    #except Exception:
        #pass
#
    ## ROC curve plot
    #try:
        #if y_proba is not None and len(np.unique(y_test)) == 2:
            #import matplotlib.pyplot as plt
            #plt.figure()
            #RocCurveDisplay.from_predictions(y_test, y_proba)
            #plt.title(f"ROC Curve — {name}")
            #plt.savefig(os.path.join(out_dir, "roc_curve.png"), dpi=200, bbox_inches="tight")
            #plt.close()
    #except Exception:
        #pass
#
    ## Feature names
    #if feature_names is None:
        #feature_names = _safe_feature_names(X_test)
#
    ## Feature importance plots
    #try:
        #_plot_feature_importance(model, feature_names, out_dir)
    #except Exception:
        #pass
#
    ## SHAP plots (optional)
    #try:
        #if X_ref_for_shap is None:
            #X_ref_for_shap = X_test
        #_save_shap_summaries(model, X_ref_for_shap, feature_names, out_dir)
    #except Exception:
        #pass
#
    ## Save metrics JSON
    #_save_json(metrics, os.path.join(out_dir, "metrics.json"))
    #return metrics
#
#def optimize_many(
    #dfs: Dict[str, pd.DataFrame],
    #x_y_split_fn,
    #scoring: str = "balanced_accuracy",
    #cv_strategy: str = "loo",  # NEW: 'skf' or 'loo'
    #n_trials: int = 500,
    #n_splits: int = 5,
    #random_state: int = 42,
    #n_jobs_trials: int = -1,
    #output_dir: str = "xgb_results",
    #test_size: float = 0.20,
    #split_param: str = "emb_",
#) -> Tuple[pd.DataFrame, Dict[str, xgb.XGBClassifier], Dict[str, optuna.Study]]:
    #"""
    #Runs Optuna per dataset, evaluates on a held-out test set,
    #and saves plots + metrics in output_dir/<dataset_name>/
    #
    #Parameters:
    #-----------
    #cv_strategy : str
        #Either 'skf' (StratifiedKFold) or 'loo' (LeaveOneOut)
    #"""
    #results = []
    #best_models: Dict[str, xgb.XGBClassifier] = {}
    #studies: Dict[str, optuna.Study] = {}
#
    #_ensure_dir(output_dir)
#
    #for name, df in dfs.items():
        #print(f"\n{'='*60}")
        #print(f"Processing dataset: {name}")
        #print(f"{'='*60}")
        #
        #X, y = x_y_split_fn(df, split_param=split_param)
#
        ## To numpy for fast indexing, but keep DataFrame support
        #X_arr = X.values if hasattr(X, "values") else X
        #y_arr = y.values if hasattr(y, "values") else y
#
        #feature_names = _safe_feature_names(X)
#
        ## Hold-out test split (kept untouched for final evaluation)
        #X_train, X_test, y_train, y_test = train_test_split(
            #X_arr, y_arr, test_size=test_size, random_state=random_state, stratify=y_arr
        #)
#
        #print(f"Train size: {len(X_train)}, Test size: {len(X_test)}")
#
        ## Build objective on TRAIN ONLY
        #objective = make_xgb_objective(
            #X_train, y_train, 
            #scoring=scoring, 
            #cv_strategy=cv_strategy,
            #n_splits=n_splits, 
            #random_state=random_state
        #)
#
        #study = optuna.create_study(
            #study_name=f"{name}_{scoring}",
            #direction="maximize",
            #sampler=optuna.samplers.TPESampler(seed=random_state),
            #pruner=optuna.pruners.MedianPruner(n_startup_trials=10),
        #)
        #
        #print(f"Starting optimization with {n_trials} trials...")
        #study.optimize(objective, n_trials=n_trials, show_progress_bar=True, n_jobs=n_jobs_trials)
        #studies[name] = study
#
        ## Train final model on TRAIN using best params
        #device_kwargs = _pick_device()
        #pos_ratio = float(np.mean(y_train))
        #spw = ((1.0 - pos_ratio) / pos_ratio) if 0 < pos_ratio < 1 else 1.0
#
        #best_params = {
            #**study.best_params,
            #"objective": "binary:logistic",
            #"eval_metric": "auc" if scoring == "roc_auc" else "logloss",
            #"n_jobs": 0,
            #"scale_pos_weight": spw,
            #**device_kwargs,
        #}
        #final_model = xgb.XGBClassifier(**best_params)
#
        ## For final model training:
        ## - If LOO was used in CV, train on full training set
        ## - If SKF was used, use early stopping split
        #if cv_strategy == "loo":
            #print("Training final model on full training set (LOO strategy)...")
            #final_model.fit(X_train, y_train, verbose=False)
        #else:
            #print("Training final model with early stopping validation split...")
            #X_tr, X_va, y_tr, y_va = train_test_split(
                #X_train, y_train, test_size=0.15, random_state=random_state, stratify=y_train
            #)
            #final_model.fit(
                #X_tr, y_tr,
                #eval_set=[(X_va, y_va)],
                #verbose=False,
            #)
#
        ## Save per-dataset artifacts
        #ds_out = os.path.join(output_dir, name)
        #_ensure_dir(ds_out)
#
        ## Evaluate on TEST and save plots/metrics
        #print("Evaluating on test set...")
        #metrics = _evaluate_and_save(
            #name, final_model, X_test, y_test, ds_out,
            #feature_names=feature_names,
            #X_ref_for_shap=X_test
        #)
#
        ## Save best params + study summary
        #_save_json({
            #"best_params": study.best_params, 
            #"best_value": study.best_value,
            #"cv_strategy": cv_strategy,
            #"n_folds": len(y_train) if cv_strategy == "loo" else n_splits
        #}, os.path.join(ds_out, "best.json"))
#
        ## Optional: save model
        #try:
            #import joblib
            #joblib.dump(final_model, os.path.join(ds_out, "model.joblib"))
        #except Exception:
            #pass
#
        #best_models[name] = final_model
        #results.append({
            #"dataset": name,
            #"cv_strategy": cv_strategy,
            #"cv_best_value": study.best_value,
            #"test_balanced_accuracy": metrics.get("balanced_accuracy"),
            #"test_roc_auc": metrics.get("roc_auc"),
            #"test_mcc": metrics.get("mcc"),
            #"test_sensitivity": metrics.get("sensitivity"),
            #"test_specificity": metrics.get("specificity"),
            #"n_trials": len(study.trials),
            #"train_size": len(X_train),
            #"test_size": len(X_test),
        #})
#
    #summary_df = pd.DataFrame(results).sort_values(by="test_balanced_accuracy", ascending=False).reset_index(drop=True)
    ## Save a global summary too
    #summary_df.to_csv(os.path.join(output_dir, "summary.csv"), index=False)
    #
    #print(f"\n{'='*60}")
    #print("All datasets processed. Summary:")
    #print(f"{'='*60}")
    #print(summary_df)
    #
    #return summary_df, best_models, studies

In [1475]:
import os, json
import numpy as np
import pandas as pd
import optuna, xgboost as xgb
from typing import Dict, Tuple
from sklearn.model_selection import StratifiedKFold, train_test_split, LeaveOneOut
from sklearn.metrics import (
    balanced_accuracy_score,
    roc_auc_score,
    confusion_matrix,
    classification_report,
    RocCurveDisplay,
    ConfusionMatrixDisplay,
    matthews_corrcoef
)

# def x_y_split(df): ...  # your splitter (must return X, y)
def _safe_feature_names(X, fallback_dim=None):
    if hasattr(X, "columns"):
        return list(X.columns)
    if hasattr(X, "feature_names_in_"):
        return list(X.feature_names_in_)
    if fallback_dim is None and hasattr(X, "shape"):
        fallback_dim = X.shape[1]
    return [f"f{i}" for i in range(int(fallback_dim or 0))]

def _plot_feature_importance(model, feature_names, out_dir: str):
    """Save multiple feature-importance views from XGBoost."""
    import matplotlib.pyplot as plt
    import numpy as np
    from collections import defaultdict
    os.makedirs(out_dir, exist_ok=True)

    # 1) sklearn API importances (gain-based)
    try:
        importances = getattr(model, "feature_importances_", None)
        if importances is not None and len(importances) == len(feature_names):
            order = np.argsort(importances)[::-1]
            top_idx = order[:50]  # limit to top-50 for readability
            plt.figure()
            plt.barh([feature_names[i] for i in top_idx][::-1], importances[top_idx][::-1])
            plt.title("XGB feature_importances_ (top-50)")
            plt.tight_layout()
            plt.savefig(os.path.join(out_dir, "feature_importances_sklearn.png"), dpi=200, bbox_inches="tight")
            plt.close()
    except Exception:
        pass

    # 2) Booster importances (weight/gain/cover)
    try:
        booster = model.get_booster()
        for typ in ["weight", "gain", "cover", "total_gain", "total_cover"]:
            score_dict = booster.get_score(importance_type=typ)
            if not score_dict:
                continue
            vals, names = [], []
            for k, v in score_dict.items():
                if k.startswith("f"):
                    idx = int(k[1:])
                    names.append(feature_names[idx] if 0 <= idx < len(feature_names) else k)
                else:
                    names.append(k)
                vals.append(v)
            order = np.argsort(vals)[::-1]
            top = min(50, len(order))
            plt.figure()
            plt.barh([names[i] for i in order[:top]][::-1], np.array(vals)[order[:top]][::-1])
            plt.title(f"Booster feature importance — {typ} (top-{top})")
            plt.tight_layout()
            plt.savefig(os.path.join(out_dir, f"feature_importances_{typ}.png"), dpi=200, bbox_inches="tight")
            plt.close()
    except Exception:
        pass

def _save_shap_summaries(model, X_ref, feature_names, out_dir: str, max_display: int = 30, sample: int = 1000):
    """
    Compute SHAP (TreeExplainer) and save bar + beeswarm plots.
    Skips silently if shap not installed or backend issues arise.
    """
    try:
        import shap
        import numpy as np
        import matplotlib.pyplot as plt
    except Exception:
        return

    try:
        if hasattr(X_ref, "iloc"):
            X_use = X_ref.sample(min(sample, len(X_ref)), random_state=0)
            X_np = X_use.values
        else:
            X_np = X_ref
            if X_np.shape[0] > sample:
                rng = np.random.default_rng(0)
                idx = rng.choice(X_np.shape[0], size=sample, replace=False)
                X_np = X_np[idx]

        explainer = shap.TreeExplainer(model)
        shap_values = explainer.shap_values(X_np)
        sv = shap_values[1] if isinstance(shap_values, list) and len(shap_values) == 2 else shap_values

        try:
            plt.figure()
            shap.summary_plot(sv, X_np, feature_names=feature_names, plot_type="bar", show=False, max_display=max_display)
            plt.tight_layout()
            plt.savefig(os.path.join(out_dir, "shap_summary_bar.png"), dpi=200, bbox_inches="tight")
            plt.close()
        except Exception:
            pass

        try:
            plt.figure()
            shap.summary_plot(sv, X_np, feature_names=feature_names, show=False, max_display=max_display)
            plt.tight_layout()
            plt.savefig(os.path.join(out_dir, "shap_summary_beeswarm.png"), dpi=200, bbox_inches="tight")
            plt.close()
        except Exception:
            pass
    except Exception:
        return

def _pick_device():
    try:
        _ = xgb.core.get_cuda_compute_capabilities()
        return {"tree_method": "hist", "device": "cuda"}
    except Exception:
        return {"tree_method": "hist", "device": "cpu"}

def _ensure_dir(path: str):
    os.makedirs(path, exist_ok=True)

def _save_json(d: dict, path: str):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(d, f, indent=2, ensure_ascii=False)

def make_xgb_objective(
    X, y,
    scoring: str = "balanced_accuracy",
    cv_strategy: str = "loo",
    n_splits: int = 5,
    random_state: int = 42
):
    """Create Optuna objective with configurable CV strategy."""
    if scoring == "balanced_accuracy":
        from sklearn.metrics import balanced_accuracy_score as metric_fn
        needs_proba = False
        eval_metric = "logloss"
    elif scoring == "roc_auc":
        from sklearn.metrics import roc_auc_score as metric_fn
        needs_proba = True
        eval_metric = "auc"
    else:
        raise ValueError("scoring must be 'balanced_accuracy' or 'roc_auc'")

    if cv_strategy == "loo":
        folds = LeaveOneOut()
        print(f"Using Leave-One-Out CV with {len(y)} folds")
    elif cv_strategy == "skf":
        folds = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=random_state)
        print(f"Using Stratified K-Fold CV with {n_splits} folds")
    else:
        raise ValueError("cv_strategy must be 'skf' or 'loo'")

    device_kwargs = _pick_device()
    pos_ratio = float(np.mean(y))
    scale_pos_weight = ((1.0 - pos_ratio) / pos_ratio) if 0 < pos_ratio < 1 else 1.0

    y_array = y.to_numpy() if hasattr(y, "to_numpy") else np.asarray(y)
    n_samples = len(y_array)

    def objective(trial: optuna.Trial) -> float:
        params = {
            #To Tune leabes, branches, trees, regularization
            "max_depth": trial.suggest_int("max_depth", 3, 10),
            "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.3, log=True),
            "n_estimators": trial.suggest_int("n_estimators", 200, 1500),
            "subsample": trial.suggest_float("subsample", 0.5, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.5, 1.0),
            "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
            "gamma": trial.suggest_float("gamma", 0.0, 5.0),
            "reg_alpha": trial.suggest_float("reg_alpha", 1e-8, 10.0, log=True),
            "reg_lambda": trial.suggest_float("reg_lambda", 1e-8, 10.0, log=True),
            "max_delta_step": trial.suggest_int("max_delta_step", 0, 10),
            "objective": "binary:logistic",
            "eval_metric": eval_metric,
            "n_jobs": 1,
            "scale_pos_weight": scale_pos_weight,
            **device_kwargs,
        }

        oof_predictions = np.zeros(n_samples, dtype=float)
        filled_mask = np.zeros(n_samples, dtype=bool)

        for fold_idx, (tr_idx, va_idx) in enumerate(folds.split(X, y)):
            if hasattr(X, "iloc"):
                X_tr, X_va = X.iloc[tr_idx], X.iloc[va_idx]
                y_tr, y_va = y.iloc[tr_idx], y.iloc[va_idx]
            else:
                X_tr, X_va = X[tr_idx], X[va_idx]
                y_tr, y_va = y[tr_idx], y[va_idx]

            model = xgb.XGBClassifier(**params)
            model.fit(X_tr, y_tr, verbose=False)

            preds = model.predict_proba(X_va)[:, 1] if needs_proba else model.predict(X_va)
            oof_predictions[va_idx] = preds
            filled_mask[va_idx] = True

            y_seen = y_array[filled_mask]
            preds_seen = oof_predictions[filled_mask]

            if np.unique(y_seen).size < 2:
                continue

            score = metric_fn(y_seen, preds_seen)
            if cv_strategy == "loo":
                if (fold_idx + 1) % 10 == 0:
                    trial.report(score, fold_idx)
                    if trial.should_prune():
                        raise optuna.TrialPruned()
            else:
                trial.report(score, fold_idx)
                if trial.should_prune():
                    raise optuna.TrialPruned()

        final_score = metric_fn(y_array, oof_predictions)
        return float(final_score)

    return objective

def _evaluate_and_save(name: str, model, X_test, y_test, out_dir: str, feature_names=None, X_ref_for_shap=None):
    """Compute metrics, plot ROC + confusion matrix, and save everything."""
    _ensure_dir(out_dir)

    y_proba = None
    try:
        y_proba = model.predict_proba(X_test)[:, 1]
    except Exception:
        pass
    y_pred = model.predict(X_test)

    metrics = {
        "balanced_accuracy": float(balanced_accuracy_score(y_test, y_pred)),
        "mcc": None,
        "roc_auc": None,
        "sensitivity": None,
        "specificity": None,
        "classification_report": None,
    }
    try:
        metrics["mcc"] = float(matthews_corrcoef(y_test, y_pred))
    except Exception:
        pass
    try:
        if y_proba is not None and len(np.unique(y_test)) == 2:
            metrics["roc_auc"] = float(roc_auc_score(y_test, y_proba))
        else:
            metrics["roc_auc"] = None
    except Exception:
        metrics["roc_auc"] = None
    try:
        cm = confusion_matrix(y_test, y_pred, labels=[0, 1])
        tn, fp, fn, tp = cm.ravel()
        sens_den = tp + fn
        spec_den = tn + fp
        metrics["sensitivity"] = float(tp / sens_den) if sens_den > 0 else None
        metrics["specificity"] = float(tn / spec_den) if spec_den > 0 else None
    except Exception:
        pass
    try:
        metrics["classification_report"] = classification_report(y_test, y_pred, output_dict=True)
    except Exception:
        metrics["classification_report"] = None

    try:
        cm = confusion_matrix(y_test, y_pred)
        disp = ConfusionMatrixDisplay(cm)
        import matplotlib.pyplot as plt
        plt.figure()
        disp.plot(values_format="d")
        plt.title(f"Confusion Matrix — {name}")
        plt.savefig(os.path.join(out_dir, "confusion_matrix.png"), dpi=200, bbox_inches="tight")
        plt.close()
    except Exception:
        pass

    try:
        if y_proba is not None and len(np.unique(y_test)) == 2:
            import matplotlib.pyplot as plt
            plt.figure()
            RocCurveDisplay.from_predictions(y_test, y_proba)
            plt.title(f"ROC Curve — {name}")
            plt.savefig(os.path.join(out_dir, "roc_curve.png"), dpi=200, bbox_inches="tight")
            plt.close()
    except Exception:
        pass

    if feature_names is None:
        feature_names = _safe_feature_names(X_test)

    try:
        _plot_feature_importance(model, feature_names, out_dir)
    except Exception:
        pass

    try:
        if X_ref_for_shap is None:
            X_ref_for_shap = X_test
        _save_shap_summaries(model, X_ref_for_shap, feature_names, out_dir)
    except Exception:
        pass

    _save_json(metrics, os.path.join(out_dir, "metrics.json"))
    return metrics

def optimize_many(
    dfs: Dict[str, pd.DataFrame],
    x_y_split_fn,
    scoring: str = "balanced_accuracy",
    cv_strategy: str = "loo",
    n_trials: int = 500,
    n_splits: int = 5,
    random_state: int = 42,
    n_jobs_trials: int = -1,
    output_dir: str = "xgb_results",
    test_size: float = 0.20,
    split_param: str = "emb_",
) -> Tuple[pd.DataFrame, Dict[str, xgb.XGBClassifier], Dict[str, optuna.Study]]:
    """
    Runs Optuna per dataset, evaluates on a held-out test set,
    and saves plots + metrics in output_dir/<dataset_name>/
    """
    results = []
    best_models: Dict[str, xgb.XGBClassifier] = {}
    studies: Dict[str, optuna.Study] = {}

    _ensure_dir(output_dir)

    for name, df in dfs.items():
        print(f"\n{'='*60}")
        print(f"Processing dataset: {name}")
        print(f"{'='*60}")
        
        X, y = x_y_split_fn(df, split_param=split_param)

        X_arr = X.values if hasattr(X, "values") else X
        y_arr = y.values if hasattr(y, "values") else y

        feature_names = _safe_feature_names(X)

        X_train, X_test, y_train, y_test = train_test_split(
            X_arr, y_arr, test_size=test_size, random_state=random_state, stratify=y_arr
        )

        print(f"Train size: {len(X_train)}, Test size: {len(X_test)}")

        objective = make_xgb_objective(
            X_train, y_train,
            scoring=scoring,
            cv_strategy=cv_strategy,
            n_splits=n_splits,
            random_state=random_state
        )

        study = optuna.create_study(
            study_name=f"{name}_{scoring}",
            direction="maximize",
            sampler=optuna.samplers.TPESampler(seed=random_state),
            pruner=optuna.pruners.MedianPruner(n_startup_trials=10),
        )
        
        print(f"Starting optimization with {n_trials} trials...")
        study.optimize(objective, n_trials=n_trials, show_progress_bar=True, n_jobs=n_jobs_trials)
        studies[name] = study

        device_kwargs = _pick_device()
        pos_ratio = float(np.mean(y_train))
        spw = ((1.0 - pos_ratio) / pos_ratio) if 0 < pos_ratio < 1 else 1.0

        best_params = {
            **study.best_params,
            "objective": "binary:logistic",
            "eval_metric": "auc" if scoring == "roc_auc" else "logloss",
            "n_jobs": 0,
            "scale_pos_weight": spw,
            **device_kwargs,
        }
        final_model = xgb.XGBClassifier(**best_params)

        if cv_strategy == "loo":
            print("Training final model on full training set (LOO strategy)...")
            final_model.fit(X_train, y_train, verbose=False)
        else:
            print("Training final model with early stopping validation split...")
            X_tr, X_va, y_tr, y_va = train_test_split(
                X_train, y_train, test_size=0.15, random_state=random_state, stratify=y_train
            )
            final_model.fit(
                X_tr, y_tr,
                eval_set=[(X_va, y_va)],
                verbose=False,
            )

        ds_out = os.path.join(output_dir, name)
        _ensure_dir(ds_out)

        print("Evaluating on test set...")
        metrics = _evaluate_and_save(
            name, final_model, X_test, y_test, ds_out,
            feature_names=feature_names,
            X_ref_for_shap=X_test
        )

        _save_json({
            "best_params": study.best_params,
            "best_value": study.best_value,
            "cv_strategy": cv_strategy,
            "n_folds": len(y_train) if cv_strategy == "loo" else n_splits
        }, os.path.join(ds_out, "best.json"))

        try:
            import joblib
            joblib.dump(final_model, os.path.join(ds_out, "model.joblib"))
        except Exception:
            pass

        best_models[name] = final_model
        results.append({
            "dataset": name,
            "cv_strategy": cv_strategy,
            "cv_best_value": study.best_value,
            "test_balanced_accuracy": metrics.get("balanced_accuracy"),
            "test_roc_auc": metrics.get("roc_auc"),
            "test_mcc": metrics.get("mcc"),
            "test_sensitivity": metrics.get("sensitivity"),
            "test_specificity": metrics.get("specificity"),
            "n_trials": len(study.trials),
            "train_size": len(X_train),
            "test_size": len(X_test),
        })

    summary_df = pd.DataFrame(results).sort_values(by="test_balanced_accuracy", ascending=False).reset_index(drop=True)
    summary_df.to_csv(os.path.join(output_dir, "summary.csv"), index=False)
    
    print(f"\n{'='*60}")
    print("All datasets processed. Summary:")
    print(f"{'='*60}")
    print(summary_df)
    
    return summary_df, best_models, studies

In [1762]:
print(
task_hf_compensated_comb_emb_lbl_lbd_hc.get('16_1').shape,
task_hf_compensated_temp_emb_lbl_lbd_hc.get('16_1').shape,
task_hf_compensated_freq_emb_lbl_lbd_hc.get('16_1').shape,

task_comb_dfs_lbd_hc.get('16_1').shape,
task_temp_dfs_lbd_hc.get('16_1').shape,
task_freq_dfs_lbd_hc.get('16_1').shape,

task_hf_dfs_clean_lbd_hc.get('16_1').shape,
)

(84, 836) (84, 452) (84, 452) (84, 770) (84, 386) (84, 386) (84, 68)

In [1477]:

task_hf_dfs_clean_lbd_hc.get('19_1')

,ID,w.cz.fnusa.19_1_95th percentile of acceleration (in-air),w.cz.fnusa.19_1_95th percentile of acceleration (on-surface),w.cz.fnusa.19_1_95th percentile of angular velocity (in-air),w.cz.fnusa.19_1_95th percentile of angular velocity (on-surface),w.cz.fnusa.19_1_95th percentile of horizontal acceleration (in-air),w.cz.fnusa.19_1_95th percentile of horizontal acceleration (on-surface),w.cz.fnusa.19_1_95th percentile of horizontal velocity (in-air),w.cz.fnusa.19_1_95th percentile of horizontal velocity (on-surface),w.cz.fnusa.19_1_95th percentile of velocity (in-air),...,w.cz.fnusa.19_1_slope of horizontal velocity (on-surface),w.cz.fnusa.19_1_slope of pressure,w.cz.fnusa.19_1_slope of ratio of the on-surface/in-air stroke duration,w.cz.fnusa.19_1_slope of velocity (in-air),w.cz.fnusa.19_1_slope of velocity (on-surface),w.cz.fnusa.19_1_slope of vertical velocity (in-air),w.cz.fnusa.19_1_slope of vertical velocity (on-surface),w.cz.fnusa.19_1_tempo (in-air),w.cz.fnusa.19_1_tempo (on-surface),diagnosis
0,COBEN-WTABLET-AS-HCD05,2013.070361,1642.987099,46.843778,48.470925,1748.565051,1239.397321,76.366071,38.571429,87.376313,...,0.001500,-0.000006,0.102963,0.037244,0.000153,0.006966,-0.001003,3.020668,1.249609,0.0
1,COBEN-WTABLET-DS-HC36,1601.144846,1391.497940,49.003420,36.335628,1122.448980,714.285714,47.500000,25.714286,72.653394,...,-0.000333,0.000026,0.207307,-0.017636,-0.002187,-0.021440,-0.002413,3.143666,1.281504,0.0
2,COBEN-WTABLET-EH-HC35,1652.772266,1688.511011,37.926735,42.858113,1645.169005,1084.183673,61.875000,39.343750,74.940719,...,0.001398,0.000016,0.014616,-0.000928,0.001441,-0.004459,0.000301,2.909620,1.786778,0.0
3,COBEN-WTABLET-FG-HC38,2362.984031,1948.188792,57.365741,48.811784,2256.377551,1464.923469,71.464286,46.285714,84.637299,...,0.000362,-0.000023,0.020852,-0.006053,-0.003346,-0.006564,-0.004395,1.870972,1.785031,0.0
4,COBEN-WTABLET-HJ-HC21,1418.678841,2158.744274,48.235334,48.685071,1493.463010,1709.183673,43.572981,53.125000,53.282775,...,-0.001205,0.000059,0.008865,0.001029,-0.005189,-0.000683,-0.005806,1.783040,1.852116,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,pre-LBD-56#1,4023.215341,2231.029217,68.107989,54.928067,4410.873724,2015.306122,126.125000,62.857143,134.421706,...,0.000308,0.000045,-0.039991,-0.040449,-0.000562,-0.002531,-0.001846,3.220612,1.202008,1.0
80,pre-LBD-57#1,2283.694720,3340.507560,39.631727,38.770321,2346.938776,2345.663265,85.513393,49.312500,93.657516,...,0.000338,0.000014,0.005092,-0.000391,-0.001769,-0.002900,-0.003869,3.606103,6.519806,1.0
81,pre-LBD-57#2,2649.771312,2386.383366,49.519532,53.682256,2498.955580,1798.121612,87.127092,54.564397,107.131158,...,0.000661,0.000037,0.030424,-0.016281,-0.002721,-0.014982,-0.004203,3.361922,1.718276,1.0
82,pre-LBD-58#1,2287.153015,1848.561662,35.755660,57.841684,2835.937500,1190.609056,131.875000,37.857143,134.361918,...,0.002208,0.000017,0.177180,-0.026706,0.001567,0.009638,0.000220,3.263052,1.099937,1.0
83,pre-LBD-59#1,1892.883348,1561.286701,44.802950,43.614013,1618.781888,1309.311224,72.937500,39.285714,87.139827,...,0.007033,0.000094,0.053816,-0.001149,0.005414,-0.002069,0.000218,2.769100,3.215176,1.0

# MCI_LBD vs HC -> OPTUNA + XGB

In [ ]:
# parameters
NUM_TRIALS = 50
CV_STRATEGY = 'loo'  # 'loo' or 'skf'
TASK_SET = "1_1_18_1"

# From this one

In [ ]:
datasets = task_hf_compensated_comb_emb_lbl_lbd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir= f"xgb_lbd_hc_{CV_STRATEGY}_tasks_tasks_{TASK_SET}/xgb_results_handcrafted_combined_emb_lbd_hc_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param= "diagnosis_y",
)
print(summary)

[I 2025-12-02 16:48:15,565] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 67, Test size: 17
Using Leave-One-Out CV with 67 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.207317:   2%|▏         | 1/50 [00:54<44:47, 54.85s/it]

[I 2025-12-02 16:49:10,391] Trial 2 finished with value: 0.2073170731707317 and parameters: {'max_depth': 7, 'learning_rate': 0.08851629122453492, 'n_estimators': 485, 'subsample': 0.887432834887442, 'colsample_bytree': 0.6080815186507282, 'min_child_weight': 10, 'gamma': 4.534784557867325, 'reg_alpha': 0.010394231039431509, 'reg_lambda': 9.144514170566215e-07, 'max_delta_step': 1}. Best is trial 2 with value: 0.2073170731707317.

Best trial: 3. Best value: 0.49015:   4%|▍         | 2/50 [01:11<25:56, 32.43s/it]

[I 2025-12-02 16:49:27,135] Trial 3 finished with value: 0.4901500938086304 and parameters: {'max_depth': 6, 'learning_rate': 0.04277798008906799, 'n_estimators': 277, 'subsample': 0.5992005405711609, 'colsample_bytree': 0.5922199822837494, 'min_child_weight': 1, 'gamma': 4.380173912428172, 'reg_alpha': 2.8252385984301785e-06, 'reg_lambda': 3.0603695208381326e-05, 'max_delta_step': 10}. Best is trial 3 with value: 0.4901500938086304.

Best trial: 3. Best value: 0.49015:   6%|▌         | 3/50 [01:41<24:19, 31.06s/it]

[I 2025-12-02 16:49:56,562] Trial 1 finished with value: 0.4169793621013133 and parameters: {'max_depth': 3, 'learning_rate': 0.12608206235093466, 'n_estimators': 618, 'subsample': 0.8915360015926166, 'colsample_bytree': 0.6547778410610796, 'min_child_weight': 3, 'gamma': 2.437789530338335, 'reg_alpha': 0.012171599223006679, 'reg_lambda': 5.794531563644052, 'max_delta_step': 8}. Best is trial 3 with value: 0.4901500938086304.

Best trial: 0. Best value: 0.5:   8%|▊         | 4/50 [01:50<17:10, 22.40s/it]

[I 2025-12-02 16:50:05,688] Trial 0 finished with value: 0.5 and parameters: {'max_depth': 8, 'learning_rate': 0.12465296470516032, 'n_estimators': 1057, 'subsample': 0.6538337788686703, 'colsample_bytree': 0.9173950276716951, 'min_child_weight': 10, 'gamma': 1.4376948193654888, 'reg_alpha': 2.9820753241788386e-05, 'reg_lambda': 2.5580628049617257e-06, 'max_delta_step': 6}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  10%|█         | 5/50 [02:45<25:38, 34.19s/it]

[I 2025-12-02 16:51:00,777] Trial 4 finished with value: 0.40290806754221387 and parameters: {'max_depth': 3, 'learning_rate': 0.04677287065219624, 'n_estimators': 1080, 'subsample': 0.8922559581737498, 'colsample_bytree': 0.9220261215789163, 'min_child_weight': 8, 'gamma': 2.7110113323648433, 'reg_alpha': 1.2416713708548587e-08, 'reg_lambda': 0.9350106156902231, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  12%|█▏        | 6/50 [02:49<17:42, 24.14s/it]

[I 2025-12-02 16:51:05,416] Trial 5 finished with value: 0.4146341463414634 and parameters: {'max_depth': 7, 'learning_rate': 0.1489987859656336, 'n_estimators': 1073, 'subsample': 0.8284926406021226, 'colsample_bytree': 0.9351765741738447, 'min_child_weight': 10, 'gamma': 1.486578605922488, 'reg_alpha': 1.4842902524694756e-07, 'reg_lambda': 0.00013013214316613656, 'max_delta_step': 9}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  14%|█▍        | 7/50 [03:05<15:19, 21.39s/it]

[I 2025-12-02 16:51:21,139] Trial 6 finished with value: 0.44136960600375236 and parameters: {'max_depth': 9, 'learning_rate': 0.24231351891688388, 'n_estimators': 614, 'subsample': 0.7588923161945647, 'colsample_bytree': 0.9858010847325092, 'min_child_weight': 4, 'gamma': 3.88991803945389, 'reg_alpha': 0.7546754589216684, 'reg_lambda': 0.6019257595843058, 'max_delta_step': 0}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  16%|█▌        | 8/50 [04:05<23:39, 33.80s/it]

[I 2025-12-02 16:52:21,505] Trial 10 finished with value: 0.42213883677298314 and parameters: {'max_depth': 4, 'learning_rate': 0.21909389094012585, 'n_estimators': 489, 'subsample': 0.8174006350449765, 'colsample_bytree': 0.9221815861605888, 'min_child_weight': 4, 'gamma': 2.6120994378444347, 'reg_alpha': 0.1501347416961143, 'reg_lambda': 0.012093395762793072, 'max_delta_step': 7}. Best is trial 0 with value: 0.5.

Best trial: 0. Best value: 0.5:  18%|█▊        | 9/50 [04:27<20:25, 29.88s/it]

[I 2025-12-02 16:52:42,787] Trial 8 finished with value: 0.036585365853658534 and parameters: {'max_depth': 6, 'learning_rate': 0.1439701300760099, 'n_estimators': 1160, 'subsample': 0.740425191524611, 'colsample_bytree': 0.783201987232357, 'min_child_weight': 10, 'gamma': 2.866248964847484, 'reg_alpha': 1.712927148104192, 'reg_lambda': 0.8906068604099581, 'max_delta_step': 2}. Best is trial 0 with value: 0.5.

Best trial: 7. Best value: 0.509381:  20%|██        | 10/50 [05:08<22:15, 33.40s/it]

[I 2025-12-02 16:53:24,058] Trial 7 finished with value: 0.5093808630393997 and parameters: {'max_depth': 8, 'learning_rate': 0.022709197607212, 'n_estimators': 1160, 'subsample': 0.8905604098670545, 'colsample_bytree': 0.7615290925864728, 'min_child_weight': 2, 'gamma': 4.496097857785079, 'reg_alpha': 0.000294536280324212, 'reg_lambda': 9.450639279201597e-05, 'max_delta_step': 10}. Best is trial 7 with value: 0.5093808630393997.

Best trial: 11. Best value: 0.540807:  22%|██▏       | 11/50 [06:14<28:17, 43.52s/it]

[I 2025-12-02 16:54:30,526] Trial 11 finished with value: 0.5408067542213884 and parameters: {'max_depth': 8, 'learning_rate': 0.24257402854767096, 'n_estimators': 1399, 'subsample': 0.7739658555907212, 'colsample_bytree': 0.6487465972875046, 'min_child_weight': 3, 'gamma': 2.5196183154977456, 'reg_alpha': 3.997912210257965e-08, 'reg_lambda': 0.033778470558702554, 'max_delta_step': 5}. Best is trial 11 with value: 0.5408067542213884.

Best trial: 11. Best value: 0.540807:  24%|██▍       | 12/50 [06:31<22:26, 35.43s/it]

[I 2025-12-02 16:54:47,455] Trial 12 finished with value: 0.43621013133208253 and parameters: {'max_depth': 9, 'learning_rate': 0.11341433176774168, 'n_estimators': 1291, 'subsample': 0.9562970328727853, 'colsample_bytree': 0.5560676300119749, 'min_child_weight': 6, 'gamma': 3.8791105824068417, 'reg_alpha': 3.809806360093602e-07, 'reg_lambda': 0.06261600157174503, 'max_delta_step': 4}. Best is trial 11 with value: 0.5408067542213884.

Best trial: 9. Best value: 0.565197:  26%|██▌       | 13/50 [07:35<27:10, 44.06s/it]

[I 2025-12-02 16:55:51,386] Trial 9 finished with value: 0.5651969981238274 and parameters: {'max_depth': 10, 'learning_rate': 0.010913996222066515, 'n_estimators': 1006, 'subsample': 0.8985297977214888, 'colsample_bytree': 0.7157714193113904, 'min_child_weight': 1, 'gamma': 2.252478336615878, 'reg_alpha': 0.00022203857224451865, 'reg_lambda': 1.0782747430205345e-07, 'max_delta_step': 4}. Best is trial 9 with value: 0.5651969981238274.

Best trial: 9. Best value: 0.565197:  28%|██▊       | 14/50 [11:54<1:05:15, 108.77s/it]

[I 2025-12-02 17:00:09,668] Trial 15 finished with value: 0.5093808630393997 and parameters: {'max_depth': 10, 'learning_rate': 0.018121025016618948, 'n_estimators': 1448, 'subsample': 0.5091506028463186, 'colsample_bytree': 0.7405309902308665, 'min_child_weight': 1, 'gamma': 0.3296630641905849, 'reg_alpha': 0.00012013662108759847, 'reg_lambda': 0.0030046321228674408, 'max_delta_step': 4}. Best is trial 9 with value: 0.5651969981238274.

Best trial: 9. Best value: 0.565197:  30%|███       | 15/50 [11:58<45:01, 77.17s/it]

[I 2025-12-02 17:00:13,618] Trial 13 finished with value: 0.49718574108818014 and parameters: {'max_depth': 9, 'learning_rate': 0.014637628879405703, 'n_estimators': 1447, 'subsample': 0.987306839107167, 'colsample_bytree': 0.7650340109295267, 'min_child_weight': 1, 'gamma': 0.2081165376879528, 'reg_alpha': 0.0006446195084575386, 'reg_lambda': 3.812353765138553e-08, 'max_delta_step': 4}. Best is trial 9 with value: 0.5651969981238274.

Best trial: 9. Best value: 0.565197:  32%|███▏      | 16/50 [12:46<38:52, 68.60s/it]

[I 2025-12-02 17:01:02,313] Trial 17 pruned.

Best trial: 9. Best value: 0.565197:  34%|███▍      | 17/50 [12:47<26:33, 48.28s/it]

[I 2025-12-02 17:01:03,327] Trial 14 finished with value: 0.4849906191369606 and parameters: {'max_depth': 10, 'learning_rate': 0.0151983846417082, 'n_estimators': 1495, 'subsample': 0.9974303449882203, 'colsample_bytree': 0.7324333279077799, 'min_child_weight': 1, 'gamma': 0.508415513250742, 'reg_alpha': 0.00034064210819936776, 'reg_lambda': 0.0034510034714440125, 'max_delta_step': 4}. Best is trial 9 with value: 0.5651969981238274.

Best trial: 9. Best value: 0.565197:  36%|███▌      | 18/50 [13:27<24:23, 45.74s/it]

[I 2025-12-02 17:01:43,143] Trial 19 pruned.

Best trial: 9. Best value: 0.565197:  38%|███▊      | 19/50 [13:28<16:37, 32.18s/it]

[I 2025-12-02 17:01:43,766] Trial 20 pruned.

Best trial: 9. Best value: 0.565197:  40%|████      | 20/50 [13:54<15:16, 30.56s/it]

[I 2025-12-02 17:02:10,519] Trial 18 finished with value: 0.4849906191369606 and parameters: {'max_depth': 10, 'learning_rate': 0.02916511266403199, 'n_estimators': 854, 'subsample': 0.7104567482987397, 'colsample_bytree': 0.6810787173525352, 'min_child_weight': 5, 'gamma': 1.6482755734366752, 'reg_alpha': 4.981674433199401e-06, 'reg_lambda': 1.594402316336122e-08, 'max_delta_step': 3}. Best is trial 9 with value: 0.5651969981238274.

Best trial: 9. Best value: 0.565197:  42%|████▏     | 21/50 [14:52<18:41, 38.68s/it]

[I 2025-12-02 17:03:08,157] Trial 16 finished with value: 0.4849906191369606 and parameters: {'max_depth': 10, 'learning_rate': 0.01062863093363461, 'n_estimators': 1491, 'subsample': 0.9974473375882157, 'colsample_bytree': 0.6715255389911065, 'min_child_weight': 1, 'gamma': 0.6259773539921967, 'reg_alpha': 0.0001210489603956201, 'reg_lambda': 1.7298224943359766e-08, 'max_delta_step': 4}. Best is trial 9 with value: 0.5651969981238274.

Best trial: 9. Best value: 0.565197:  44%|████▍     | 22/50 [15:30<17:56, 38.44s/it]

[I 2025-12-02 17:03:46,018] Trial 22 finished with value: 0.43949343339587243 and parameters: {'max_depth': 5, 'learning_rate': 0.07203710615589363, 'n_estimators': 1299, 'subsample': 0.811726515035251, 'colsample_bytree': 0.5107247102574748, 'min_child_weight': 5, 'gamma': 2.0035892167365073, 'reg_alpha': 7.97963144595608e-07, 'reg_lambda': 2.06112590393896e-05, 'max_delta_step': 2}. Best is trial 9 with value: 0.5651969981238274.

Best trial: 9. Best value: 0.565197:  46%|████▌     | 23/50 [15:33<12:29, 27.74s/it]

[I 2025-12-02 17:03:48,815] Trial 21 finished with value: 0.45872420262664165 and parameters: {'max_depth': 5, 'learning_rate': 0.062409621602635926, 'n_estimators': 1300, 'subsample': 0.8187911289008017, 'colsample_bytree': 0.5026757853905266, 'min_child_weight': 5, 'gamma': 1.8305083604208172, 'reg_alpha': 6.071632365132059e-07, 'reg_lambda': 5.503389705386358e-07, 'max_delta_step': 6}. Best is trial 9 with value: 0.5651969981238274.

Best trial: 9. Best value: 0.565197:  48%|████▊     | 24/50 [16:05<12:33, 28.98s/it]

[I 2025-12-02 17:04:20,673] Trial 24 pruned.

Best trial: 9. Best value: 0.565197:  50%|█████     | 25/50 [16:12<09:19, 22.38s/it]

[I 2025-12-02 17:04:27,674] Trial 23 finished with value: 0.49718574108818014 and parameters: {'max_depth': 5, 'learning_rate': 0.07638644305364184, 'n_estimators': 1313, 'subsample': 0.8088221137663075, 'colsample_bytree': 0.52425670968683, 'min_child_weight': 2, 'gamma': 0.8803912654195869, 'reg_alpha': 0.004747504393061895, 'reg_lambda': 1.722737741871924e-05, 'max_delta_step': 2}. Best is trial 9 with value: 0.5651969981238274.

Best trial: 9. Best value: 0.565197:  52%|█████▏    | 26/50 [16:34<08:56, 22.37s/it]

[I 2025-12-02 17:04:50,001] Trial 28 pruned.

Best trial: 9. Best value: 0.565197:  54%|█████▍    | 27/50 [16:43<07:03, 18.40s/it]

[I 2025-12-02 17:04:59,130] Trial 26 pruned.

Best trial: 9. Best value: 0.565197:  56%|█████▌    | 28/50 [17:14<08:04, 22.01s/it]

[I 2025-12-02 17:05:29,545] Trial 30 pruned.

Best trial: 9. Best value: 0.565197:  58%|█████▊    | 29/50 [17:20<06:05, 17.40s/it]

[I 2025-12-02 17:05:36,211] Trial 25 pruned.

Best trial: 9. Best value: 0.565197:  60%|██████    | 30/50 [18:06<08:40, 26.03s/it]

[I 2025-12-02 17:06:22,396] Trial 31 pruned.

Best trial: 9. Best value: 0.565197:  62%|██████▏   | 31/50 [19:00<10:49, 34.17s/it]

[I 2025-12-02 17:07:15,566] Trial 32 finished with value: 0.4606003752345216 and parameters: {'max_depth': 7, 'learning_rate': 0.28019962449900765, 'n_estimators': 1003, 'subsample': 0.7738811358738347, 'colsample_bytree': 0.6208206576406852, 'min_child_weight': 3, 'gamma': 3.8354303268443197, 'reg_alpha': 2.507489665987865e-05, 'reg_lambda': 1.7031817806027202e-07, 'max_delta_step': 5}. Best is trial 9 with value: 0.5651969981238274.

Best trial: 9. Best value: 0.565197:  64%|██████▍   | 32/50 [19:35<10:19, 34.44s/it]

[I 2025-12-02 17:07:50,631] Trial 27 finished with value: 0.5164165103189493 and parameters: {'max_depth': 8, 'learning_rate': 0.024181834298196266, 'n_estimators': 1202, 'subsample': 0.9033495076525119, 'colsample_bytree': 0.8353059994224659, 'min_child_weight': 2, 'gamma': 4.9138855123088065, 'reg_alpha': 0.0022579769831424326, 'reg_lambda': 0.05013743507467579, 'max_delta_step': 10}. Best is trial 9 with value: 0.5651969981238274.

Best trial: 9. Best value: 0.565197:  66%|██████▌   | 33/50 [19:43<07:31, 26.57s/it]

[I 2025-12-02 17:07:58,821] Trial 33 finished with value: 0.48686679174484054 and parameters: {'max_depth': 9, 'learning_rate': 0.291302986108856, 'n_estimators': 1157, 'subsample': 0.6691033773268843, 'colsample_bytree': 0.875136687849097, 'min_child_weight': 7, 'gamma': 1.163746476525903, 'reg_alpha': 2.3236564736928058e-05, 'reg_lambda': 3.6923935312878382e-06, 'max_delta_step': 5}. Best is trial 9 with value: 0.5651969981238274.

Best trial: 9. Best value: 0.565197:  68%|██████▊   | 34/50 [19:48<05:20, 20.06s/it]

[I 2025-12-02 17:08:03,689] Trial 29 finished with value: 0.5286116322701688 and parameters: {'max_depth': 7, 'learning_rate': 0.03888276457926329, 'n_estimators': 1160, 'subsample': 0.8679322257865334, 'colsample_bytree': 0.8258710467215201, 'min_child_weight': 2, 'gamma': 3.151161189144733, 'reg_alpha': 0.08174026884754435, 'reg_lambda': 0.0002488680057580702, 'max_delta_step': 8}. Best is trial 9 with value: 0.5651969981238274.

Best trial: 9. Best value: 0.565197:  70%|███████   | 35/50 [21:24<10:42, 42.80s/it]

[I 2025-12-02 17:09:39,569] Trial 36 pruned.

Best trial: 9. Best value: 0.565197:  72%|███████▏  | 36/50 [21:32<07:33, 32.40s/it]

[I 2025-12-02 17:09:47,688] Trial 34 pruned.

Best trial: 9. Best value: 0.565197:  74%|███████▍  | 37/50 [21:54<06:21, 29.33s/it]

[I 2025-12-02 17:10:09,856] Trial 35 pruned.

Best trial: 9. Best value: 0.565197:  76%|███████▌  | 38/50 [21:57<04:18, 21.50s/it]

[I 2025-12-02 17:10:13,095] Trial 39 pruned.

Best trial: 9. Best value: 0.565197:  78%|███████▊  | 39/50 [22:34<04:48, 26.20s/it]

[I 2025-12-02 17:10:50,252] Trial 38 pruned.

Best trial: 9. Best value: 0.565197:  80%|████████  | 40/50 [22:38<03:13, 19.39s/it]

[I 2025-12-02 17:10:53,755] Trial 41 pruned.

Best trial: 9. Best value: 0.565197:  82%|████████▏ | 41/50 [22:47<02:26, 16.29s/it]

[I 2025-12-02 17:11:02,812] Trial 40 pruned.

Best trial: 9. Best value: 0.565197:  84%|████████▍ | 42/50 [22:54<01:48, 13.55s/it]

[I 2025-12-02 17:11:09,964] Trial 43 pruned.

Best trial: 9. Best value: 0.565197:  86%|████████▌ | 43/50 [23:18<01:57, 16.77s/it]

[I 2025-12-02 17:11:34,234] Trial 42 pruned.

Best trial: 9. Best value: 0.565197:  88%|████████▊ | 44/50 [23:29<01:29, 14.97s/it]

[I 2025-12-02 17:11:45,013] Trial 37 finished with value: 0.4849906191369606 and parameters: {'max_depth': 6, 'learning_rate': 0.03673866604372865, 'n_estimators': 1357, 'subsample': 0.8789021074647957, 'colsample_bytree': 0.7939721846545116, 'min_child_weight': 3, 'gamma': 2.1484361430109025, 'reg_alpha': 0.03771578870093395, 'reg_lambda': 5.238066235233127, 'max_delta_step': 9}. Best is trial 9 with value: 0.5651969981238274.

Best trial: 9. Best value: 0.565197:  90%|█████████ | 45/50 [23:51<01:25, 17.16s/it]

[I 2025-12-02 17:12:07,275] Trial 47 pruned.

Best trial: 9. Best value: 0.565197:  92%|█████████▏| 46/50 [24:33<01:37, 24.45s/it]

[I 2025-12-02 17:12:48,732] Trial 44 pruned.

Best trial: 9. Best value: 0.565197:  94%|█████████▍| 47/50 [24:34<00:52, 17.39s/it]

[I 2025-12-02 17:12:49,661] Trial 45 pruned.

Best trial: 9. Best value: 0.565197:  96%|█████████▌| 48/50 [25:37<01:02, 31.33s/it]

[I 2025-12-02 17:13:53,531] Trial 49 pruned.

Best trial: 9. Best value: 0.565197:  98%|█████████▊| 49/50 [26:22<00:35, 35.37s/it]

[I 2025-12-02 17:14:38,326] Trial 46 finished with value: 0.5356472795497186 and parameters: {'max_depth': 8, 'learning_rate': 0.025689558297112527, 'n_estimators': 1202, 'subsample': 0.9498647423110439, 'colsample_bytree': 0.7614089086388132, 'min_child_weight': 2, 'gamma': 4.708312526420417, 'reg_alpha': 0.0001331073624193287, 'reg_lambda': 9.50049004643017e-05, 'max_delta_step': 10}. Best is trial 9 with value: 0.5651969981238274.

Best trial: 9. Best value: 0.565197: 100%|██████████| 50/50 [26:37<00:00, 31.95s/it]

[I 2025-12-02 17:14:52,886] Trial 48 finished with value: 0.5408067542213884 and parameters: {'max_depth': 8, 'learning_rate': 0.024400962688896976, 'n_estimators': 1221, 'subsample': 0.7801736155834661, 'colsample_bytree': 0.7009862656536213, 'min_child_weight': 2, 'gamma': 4.670669820854538, 'reg_alpha': 2.315900288376976e-06, 'reg_lambda': 4.677390582366098e-05, 'max_delta_step': 10}. Best is trial 9 with value: 0.5651969981238274.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.565197                0.557143      0.485714

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.117698          0.714286               0.4        50          67

   test_size
0         17
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.565197                0.557143      0.485714

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.117698          0.714286               0.4        50          67

   test_size
0         17

In [ ]:

datasets = task_hf_compensated_temp_emb_lbl_lbd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_lbd_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_handcrafted_temporal_emb_compensated_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param= "diagnosis_y",
)
print(summary)

[I 2025-12-02 17:15:02,182] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 67, Test size: 17
Using Leave-One-Out CV with 67 folds
Starting optimization with 50 trials...

  0%|          | 0/50 [00:00<?, ?it/s]

Best trial: 3. Best value: 0.553002:   2%|▏         | 1/50 [00:37<30:22, 37.18s/it]

[I 2025-12-02 17:15:39,358] Trial 3 finished with value: 0.5530018761726079 and parameters: {'max_depth': 10, 'learning_rate': 0.037566500706595826, 'n_estimators': 291, 'subsample': 0.535888673668272, 'colsample_bytree': 0.8656761433102635, 'min_child_weight': 3, 'gamma': 3.448271477832003, 'reg_alpha': 0.6558628951108106, 'reg_lambda': 1.8334686661480223e-06, 'max_delta_step': 9}. Best is trial 3 with value: 0.5530018761726079.

Best trial: 3. Best value: 0.553002:   4%|▍         | 2/50 [00:39<13:11, 16.48s/it]

[I 2025-12-02 17:15:41,347] Trial 1 finished with value: 0.5478424015009381 and parameters: {'max_depth': 7, 'learning_rate': 0.13275803229655028, 'n_estimators': 562, 'subsample': 0.9417458491276333, 'colsample_bytree': 0.67156072424599, 'min_child_weight': 7, 'gamma': 0.8815230253529416, 'reg_alpha': 0.27953554974158284, 'reg_lambda': 0.05080738753887593, 'max_delta_step': 4}. Best is trial 3 with value: 0.5530018761726079.

Best trial: 3. Best value: 0.553002:   6%|▌         | 3/50 [00:52<11:44, 14.99s/it]

[I 2025-12-02 17:15:54,565] Trial 2 finished with value: 0.45121951219512196 and parameters: {'max_depth': 5, 'learning_rate': 0.026105381973091913, 'n_estimators': 868, 'subsample': 0.6417422197906693, 'colsample_bytree': 0.9662899579843158, 'min_child_weight': 10, 'gamma': 1.6311782660479224, 'reg_alpha': 0.18916868629576297, 'reg_lambda': 3.3327662658286015e-06, 'max_delta_step': 4}. Best is trial 3 with value: 0.5530018761726079.

Best trial: 3. Best value: 0.553002:   8%|▊         | 4/50 [00:57<08:23, 10.94s/it]

[I 2025-12-02 17:15:59,303] Trial 0 finished with value: 0.5182926829268293 and parameters: {'max_depth': 10, 'learning_rate': 0.018636680720859427, 'n_estimators': 812, 'subsample': 0.9795877691819148, 'colsample_bytree': 0.9922259411923362, 'min_child_weight': 9, 'gamma': 2.350366574975167, 'reg_alpha': 7.401772614315063e-05, 'reg_lambda': 2.1459269235209134e-06, 'max_delta_step': 0}. Best is trial 3 with value: 0.5530018761726079.

Best trial: 3. Best value: 0.553002:  10%|█         | 5/50 [01:48<19:12, 25.61s/it]

[I 2025-12-02 17:16:50,932] Trial 4 finished with value: 0.5478424015009381 and parameters: {'max_depth': 4, 'learning_rate': 0.08463209283686858, 'n_estimators': 1177, 'subsample': 0.9893390509925472, 'colsample_bytree': 0.5809519698839659, 'min_child_weight': 5, 'gamma': 4.001956490132089, 'reg_alpha': 0.0011818692055222924, 'reg_lambda': 0.0002971966596062394, 'max_delta_step': 5}. Best is trial 3 with value: 0.5530018761726079.

Best trial: 3. Best value: 0.553002:  12%|█▏        | 6/50 [02:02<15:55, 21.71s/it]

[I 2025-12-02 17:17:05,052] Trial 6 finished with value: 0.5286116322701688 and parameters: {'max_depth': 10, 'learning_rate': 0.12275020456167895, 'n_estimators': 975, 'subsample': 0.9107208831561968, 'colsample_bytree': 0.9411921575965867, 'min_child_weight': 4, 'gamma': 4.15358072005264, 'reg_alpha': 0.0005195640977843192, 'reg_lambda': 3.440993315472624e-06, 'max_delta_step': 1}. Best is trial 3 with value: 0.5530018761726079.

Best trial: 3. Best value: 0.553002:  14%|█▍        | 7/50 [02:08<11:52, 16.56s/it]

[I 2025-12-02 17:17:11,018] Trial 7 finished with value: 0.5530018761726079 and parameters: {'max_depth': 4, 'learning_rate': 0.19474323488219178, 'n_estimators': 1371, 'subsample': 0.6559604212260921, 'colsample_bytree': 0.8173595946528771, 'min_child_weight': 6, 'gamma': 3.8786021888838773, 'reg_alpha': 3.7585965650042166, 'reg_lambda': 0.004583773909571503, 'max_delta_step': 5}. Best is trial 3 with value: 0.5530018761726079.

Best trial: 3. Best value: 0.553002:  16%|█▌        | 8/50 [02:27<12:08, 17.34s/it]

[I 2025-12-02 17:17:30,019] Trial 5 finished with value: 0.5356472795497186 and parameters: {'max_depth': 4, 'learning_rate': 0.2672345163907743, 'n_estimators': 1397, 'subsample': 0.6722464501594808, 'colsample_bytree': 0.659067108890969, 'min_child_weight': 1, 'gamma': 2.0648611380336037, 'reg_alpha': 0.24364544437661315, 'reg_lambda': 3.2102730086099207, 'max_delta_step': 9}. Best is trial 3 with value: 0.5530018761726079.

Best trial: 3. Best value: 0.553002:  18%|█▊        | 9/50 [02:34<09:27, 13.85s/it]

[I 2025-12-02 17:17:36,190] Trial 10 finished with value: 0.5408067542213884 and parameters: {'max_depth': 9, 'learning_rate': 0.04660618149658831, 'n_estimators': 374, 'subsample': 0.6414885239198505, 'colsample_bytree': 0.6637401399955408, 'min_child_weight': 7, 'gamma': 1.3846543941242935, 'reg_alpha': 1.6862058341934862, 'reg_lambda': 1.535174914015117e-05, 'max_delta_step': 2}. Best is trial 3 with value: 0.5530018761726079.

Best trial: 3. Best value: 0.553002:  20%|██        | 10/50 [02:50<09:42, 14.56s/it]

[I 2025-12-02 17:17:52,342] Trial 12 finished with value: 0.16557223264540338 and parameters: {'max_depth': 7, 'learning_rate': 0.25391713929740506, 'n_estimators': 242, 'subsample': 0.5739803773541056, 'colsample_bytree': 0.5564526954824716, 'min_child_weight': 7, 'gamma': 4.54663293647674, 'reg_alpha': 7.740393344085136, 'reg_lambda': 0.00014950677714744017, 'max_delta_step': 8}. Best is trial 3 with value: 0.5530018761726079.

Best trial: 8. Best value: 0.584428:  22%|██▏       | 11/50 [02:51<06:53, 10.59s/it]

[I 2025-12-02 17:17:53,949] Trial 8 finished with value: 0.5844277673545966 and parameters: {'max_depth': 5, 'learning_rate': 0.03741162811054951, 'n_estimators': 466, 'subsample': 0.9074995362592462, 'colsample_bytree': 0.5130648524327521, 'min_child_weight': 1, 'gamma': 0.412411948941368, 'reg_alpha': 2.1845668808993226e-08, 'reg_lambda': 4.148790164364198e-05, 'max_delta_step': 1}. Best is trial 8 with value: 0.5844277673545966.

Best trial: 8. Best value: 0.584428:  24%|██▍       | 12/50 [03:08<07:49, 12.37s/it]

[I 2025-12-02 17:18:10,367] Trial 9 finished with value: 0.5844277673545966 and parameters: {'max_depth': 9, 'learning_rate': 0.010076893772168208, 'n_estimators': 822, 'subsample': 0.5784511134569282, 'colsample_bytree': 0.5401134273120463, 'min_child_weight': 4, 'gamma': 4.828889890589171, 'reg_alpha': 3.5652380841112037, 'reg_lambda': 4.7122035866793697e-07, 'max_delta_step': 2}. Best is trial 8 with value: 0.5844277673545966.

Best trial: 8. Best value: 0.584428:  26%|██▌       | 13/50 [03:15<06:46, 10.99s/it]

[I 2025-12-02 17:18:18,171] Trial 14 pruned.

Best trial: 8. Best value: 0.584428:  28%|██▊       | 14/50 [03:39<08:46, 14.62s/it]

[I 2025-12-02 17:18:41,205] Trial 16 pruned.

Best trial: 8. Best value: 0.584428:  30%|███       | 15/50 [03:49<07:52, 13.51s/it]

[I 2025-12-02 17:18:52,129] Trial 15 pruned.

Best trial: 8. Best value: 0.584428:  32%|███▏      | 16/50 [04:02<07:30, 13.24s/it]

[I 2025-12-02 17:19:04,760] Trial 11 finished with value: 0.5651969981238274 and parameters: {'max_depth': 5, 'learning_rate': 0.01074781175915415, 'n_estimators': 1150, 'subsample': 0.8295109023400427, 'colsample_bytree': 0.9899001930218213, 'min_child_weight': 7, 'gamma': 3.9653676102440576, 'reg_alpha': 0.000500010089995934, 'reg_lambda': 0.5270901107362549, 'max_delta_step': 4}. Best is trial 8 with value: 0.5844277673545966.

Best trial: 8. Best value: 0.584428:  34%|███▍      | 17/50 [04:16<07:20, 13.35s/it]

[I 2025-12-02 17:19:18,356] Trial 18 pruned.

Best trial: 8. Best value: 0.584428:  36%|███▌      | 18/50 [04:17<05:07,  9.62s/it]

[I 2025-12-02 17:19:19,305] Trial 19 pruned.

Best trial: 8. Best value: 0.584428:  38%|███▊      | 19/50 [04:20<04:00,  7.76s/it]

[I 2025-12-02 17:19:22,742] Trial 13 finished with value: 0.5651969981238274 and parameters: {'max_depth': 8, 'learning_rate': 0.010581375941742025, 'n_estimators': 572, 'subsample': 0.5190734377580226, 'colsample_bytree': 0.834957288391013, 'min_child_weight': 2, 'gamma': 3.1392741655595167, 'reg_alpha': 1.516989226270923e-08, 'reg_lambda': 4.3873529040359974e-08, 'max_delta_step': 10}. Best is trial 8 with value: 0.5844277673545966.

Best trial: 8. Best value: 0.584428:  40%|████      | 20/50 [04:25<03:23,  6.80s/it]

[I 2025-12-02 17:19:27,285] Trial 17 pruned.

Best trial: 8. Best value: 0.584428:  42%|████▏     | 21/50 [04:25<02:20,  4.85s/it]

[I 2025-12-02 17:19:27,578] Trial 20 pruned.

Best trial: 8. Best value: 0.584428:  44%|████▍     | 22/50 [04:26<01:43,  3.69s/it]

[I 2025-12-02 17:19:28,590] Trial 21 pruned.

Best trial: 8. Best value: 0.584428:  46%|████▌     | 23/50 [04:28<01:24,  3.15s/it]

[I 2025-12-02 17:19:30,464] Trial 22 pruned.

Best trial: 8. Best value: 0.584428:  48%|████▊     | 24/50 [04:33<01:41,  3.91s/it]

[I 2025-12-02 17:19:36,151] Trial 23 pruned.

Best trial: 8. Best value: 0.584428:  50%|█████     | 25/50 [04:40<01:58,  4.75s/it]

[I 2025-12-02 17:19:42,877] Trial 24 pruned.

Best trial: 8. Best value: 0.584428:  52%|█████▏    | 26/50 [04:41<01:22,  3.44s/it]

[I 2025-12-02 17:19:43,251] Trial 25 pruned.

Best trial: 8. Best value: 0.584428:  54%|█████▍    | 27/50 [04:45<01:29,  3.88s/it]

[I 2025-12-02 17:19:48,152] Trial 27 pruned.

Best trial: 8. Best value: 0.584428:  56%|█████▌    | 28/50 [04:55<02:02,  5.57s/it]

[I 2025-12-02 17:19:57,668] Trial 29 pruned.

Best trial: 8. Best value: 0.584428:  58%|█████▊    | 29/50 [04:56<01:28,  4.21s/it]

[I 2025-12-02 17:19:58,718] Trial 30 pruned.

Best trial: 8. Best value: 0.584428:  60%|██████    | 30/50 [05:04<01:47,  5.38s/it]

[I 2025-12-02 17:20:06,822] Trial 31 pruned.

Best trial: 8. Best value: 0.584428:  62%|██████▏   | 31/50 [05:24<03:06,  9.79s/it]

[I 2025-12-02 17:20:26,897] Trial 33 pruned.

Best trial: 8. Best value: 0.584428:  64%|██████▍   | 32/50 [05:40<03:30, 11.71s/it]

[I 2025-12-02 17:20:43,102] Trial 28 finished with value: 0.5722326454033771 and parameters: {'max_depth': 5, 'learning_rate': 0.029288155724257605, 'n_estimators': 930, 'subsample': 0.7928816543833372, 'colsample_bytree': 0.9105238523063959, 'min_child_weight': 8, 'gamma': 4.33453884249392, 'reg_alpha': 7.613072910280017e-05, 'reg_lambda': 0.615182080003075, 'max_delta_step': 6}. Best is trial 8 with value: 0.5844277673545966.

Best trial: 8. Best value: 0.584428:  66%|██████▌   | 33/50 [05:46<02:45,  9.75s/it]

[I 2025-12-02 17:20:48,284] Trial 26 finished with value: 0.5478424015009381 and parameters: {'max_depth': 5, 'learning_rate': 0.015094563537396856, 'n_estimators': 1231, 'subsample': 0.8732225253265564, 'colsample_bytree': 0.905233173026642, 'min_child_weight': 9, 'gamma': 4.959614919151496, 'reg_alpha': 8.952413918920815e-05, 'reg_lambda': 2.7645232558840034, 'max_delta_step': 6}. Best is trial 8 with value: 0.5844277673545966.

Best trial: 8. Best value: 0.584428:  68%|██████▊   | 34/50 [05:57<02:43, 10.22s/it]

[I 2025-12-02 17:20:59,605] Trial 36 pruned.

Best trial: 8. Best value: 0.584428:  70%|███████   | 35/50 [06:03<02:15,  9.07s/it]

[I 2025-12-02 17:21:05,953] Trial 32 finished with value: 0.5426829268292683 and parameters: {'max_depth': 7, 'learning_rate': 0.017055325202142698, 'n_estimators': 1124, 'subsample': 0.9568735620867552, 'colsample_bytree': 0.5427992198617082, 'min_child_weight': 9, 'gamma': 2.4397703838620015, 'reg_alpha': 8.911521032625891e-05, 'reg_lambda': 1.532757400658754e-05, 'max_delta_step': 1}. Best is trial 8 with value: 0.5844277673545966.

Best trial: 8. Best value: 0.584428:  72%|███████▏  | 36/50 [06:30<03:20, 14.31s/it]

[I 2025-12-02 17:21:32,523] Trial 34 finished with value: 0.5773921200750469 and parameters: {'max_depth': 9, 'learning_rate': 0.010042912178759859, 'n_estimators': 622, 'subsample': 0.5898468342675939, 'colsample_bytree': 0.8055386941357349, 'min_child_weight': 4, 'gamma': 3.0578970368573732, 'reg_alpha': 1.2275014814569272e-08, 'reg_lambda': 4.93177606534577e-08, 'max_delta_step': 10}. Best is trial 8 with value: 0.5844277673545966.

Best trial: 8. Best value: 0.584428:  74%|███████▍  | 37/50 [06:36<02:34, 11.92s/it]

[I 2025-12-02 17:21:38,854] Trial 39 pruned.

Best trial: 8. Best value: 0.584428:  76%|███████▌  | 38/50 [06:45<02:11, 10.97s/it]

[I 2025-12-02 17:21:47,606] Trial 40 pruned.

Best trial: 8. Best value: 0.584428:  78%|███████▊  | 39/50 [06:52<01:47,  9.80s/it]

[I 2025-12-02 17:21:54,682] Trial 37 finished with value: 0.5651969981238274 and parameters: {'max_depth': 6, 'learning_rate': 0.03714348347297857, 'n_estimators': 872, 'subsample': 0.7668798896011901, 'colsample_bytree': 0.951719820694985, 'min_child_weight': 8, 'gamma': 2.724865906826824, 'reg_alpha': 0.09803975594074796, 'reg_lambda': 0.47763978225796866, 'max_delta_step': 4}. Best is trial 8 with value: 0.5844277673545966.

Best trial: 8. Best value: 0.584428:  80%|████████  | 40/50 [06:53<01:12,  7.26s/it]

[I 2025-12-02 17:21:56,030] Trial 41 pruned.

Best trial: 8. Best value: 0.584428:  82%|████████▏ | 41/50 [06:56<00:53,  5.93s/it]

[I 2025-12-02 17:21:58,836] Trial 35 finished with value: 0.5844277673545966 and parameters: {'max_depth': 4, 'learning_rate': 0.01722815145871331, 'n_estimators': 1108, 'subsample': 0.9518151142293135, 'colsample_bytree': 0.9346724199443724, 'min_child_weight': 8, 'gamma': 4.2777967973995805, 'reg_alpha': 0.0011435019208178806, 'reg_lambda': 0.039907265105307406, 'max_delta_step': 7}. Best is trial 8 with value: 0.5844277673545966.

Best trial: 8. Best value: 0.584428:  84%|████████▍ | 42/50 [06:58<00:37,  4.72s/it]

[I 2025-12-02 17:22:00,732] Trial 43 pruned.

Best trial: 8. Best value: 0.584428:  88%|████████▊ | 44/50 [06:59<00:14,  2.43s/it]

[I 2025-12-02 17:22:01,082] Trial 38 finished with value: 0.5651969981238274 and parameters: {'max_depth': 6, 'learning_rate': 0.03574592811401242, 'n_estimators': 853, 'subsample': 0.7670802504941462, 'colsample_bytree': 0.9735134488426094, 'min_child_weight': 8, 'gamma': 3.793250973687573, 'reg_alpha': 0.06512174941962934, 'reg_lambda': 0.7139588994298496, 'max_delta_step': 4}. Best is trial 8 with value: 0.5844277673545966.
[I 2025-12-02 17:22:01,214] Trial 42 pruned.

Best trial: 8. Best value: 0.584428:  90%|█████████ | 45/50 [07:04<00:17,  3.45s/it]

[I 2025-12-02 17:22:07,057] Trial 44 pruned.

Best trial: 8. Best value: 0.584428:  92%|█████████▏| 46/50 [07:10<00:16,  4.02s/it]

[I 2025-12-02 17:22:12,412] Trial 46 pruned.

Best trial: 8. Best value: 0.584428:  94%|█████████▍| 47/50 [07:10<00:08,  2.89s/it]

[I 2025-12-02 17:22:12,669] Trial 47 pruned.

Best trial: 8. Best value: 0.584428:  96%|█████████▌| 48/50 [07:12<00:05,  2.69s/it]

[I 2025-12-02 17:22:14,898] Trial 48 pruned.

Best trial: 8. Best value: 0.584428:  98%|█████████▊| 49/50 [07:15<00:02,  2.80s/it]

[I 2025-12-02 17:22:17,951] Trial 49 pruned.

Best trial: 8. Best value: 0.584428: 100%|██████████| 50/50 [07:44<00:00,  9.29s/it]

[I 2025-12-02 17:22:46,682] Trial 45 finished with value: 0.5478424015009381 and parameters: {'max_depth': 4, 'learning_rate': 0.023882640647269842, 'n_estimators': 972, 'subsample': 0.9910510847657078, 'colsample_bytree': 0.9148191122580948, 'min_child_weight': 8, 'gamma': 4.536260215796161, 'reg_alpha': 0.4671883666984413, 'reg_lambda': 0.02925265613377138, 'max_delta_step': 7}. Best is trial 8 with value: 0.5844277673545966.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.584428                0.485714      0.485714

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.028571          0.571429               0.4        50          67

   test_size
0         17
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.584428                0.485714      0.485714

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.028571          0.571429               0.4        50          67

   test_size
0         17

In [ ]:

datasets = task_hf_compensated_freq_emb_lbl_lbd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_lbd_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_handcrafted_frerq_emb_compensated_extended_{CV_STRATEGY}_tasks",
    split_param= "diagnosis_y",
)
print(summary)
## MCI-AD vs HC -> OPTUNA + XGB

[I 2025-12-02 17:22:52,571] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 67, Test size: 17
Using Leave-One-Out CV with 67 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.219512:   2%|▏         | 1/50 [00:46<38:00, 46.55s/it]

[I 2025-12-02 17:23:39,110] Trial 1 finished with value: 0.21951219512195122 and parameters: {'max_depth': 5, 'learning_rate': 0.08042073004535306, 'n_estimators': 777, 'subsample': 0.6777435341169851, 'colsample_bytree': 0.891761441162852, 'min_child_weight': 10, 'gamma': 2.022096647162395, 'reg_alpha': 0.005906924544951022, 'reg_lambda': 1.987284590182949e-08, 'max_delta_step': 4}. Best is trial 1 with value: 0.21951219512195122.

Best trial: 2. Best value: 0.484991:   4%|▍         | 2/50 [00:59<21:16, 26.60s/it]

[I 2025-12-02 17:23:51,743] Trial 2 finished with value: 0.4849906191369606 and parameters: {'max_depth': 7, 'learning_rate': 0.01857475650174317, 'n_estimators': 826, 'subsample': 0.9776981250955434, 'colsample_bytree': 0.5022499559230489, 'min_child_weight': 8, 'gamma': 0.30970143697293284, 'reg_alpha': 1.520586333672906e-07, 'reg_lambda': 2.8164207508100675e-05, 'max_delta_step': 4}. Best is trial 2 with value: 0.4849906191369606.

Best trial: 3. Best value: 0.5:   6%|▌         | 3/50 [01:04<13:23, 17.10s/it]

[I 2025-12-02 17:23:57,538] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.010300250782771773, 'n_estimators': 1139, 'subsample': 0.7059586771185687, 'colsample_bytree': 0.7951136012103796, 'min_child_weight': 9, 'gamma': 1.918800073256644, 'reg_alpha': 0.0008314302006356763, 'reg_lambda': 2.88626598329797e-06, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:   8%|▊         | 4/50 [01:08<08:52, 11.57s/it]

[I 2025-12-02 17:24:00,619] Trial 0 finished with value: 0.476078799249531 and parameters: {'max_depth': 9, 'learning_rate': 0.2239235166353557, 'n_estimators': 1107, 'subsample': 0.7826672971813528, 'colsample_bytree': 0.9623429556152732, 'min_child_weight': 4, 'gamma': 1.936888506949277, 'reg_alpha': 0.039332750947743675, 'reg_lambda': 0.24622892303595628, 'max_delta_step': 3}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  10%|█         | 5/50 [01:17<08:12, 10.95s/it]

[I 2025-12-02 17:24:10,471] Trial 4 finished with value: 0.46575984990619135 and parameters: {'max_depth': 10, 'learning_rate': 0.010941062582149483, 'n_estimators': 384, 'subsample': 0.6837762372022121, 'colsample_bytree': 0.8369982599581285, 'min_child_weight': 7, 'gamma': 0.6031163395897887, 'reg_alpha': 0.00017507778538232655, 'reg_lambda': 7.221070820995593e-05, 'max_delta_step': 7}. Best is trial 3 with value: 0.5.

Best trial: 3. Best value: 0.5:  12%|█▏        | 6/50 [01:48<12:59, 17.72s/it]

[I 2025-12-02 17:24:41,349] Trial 6 finished with value: 0.34146341463414637 and parameters: {'max_depth': 9, 'learning_rate': 0.04840375698831192, 'n_estimators': 781, 'subsample': 0.6799786554425131, 'colsample_bytree': 0.8058022850333071, 'min_child_weight': 10, 'gamma': 4.813369555930624, 'reg_alpha': 3.7259016363299636e-06, 'reg_lambda': 0.3414838598857288, 'max_delta_step': 10}. Best is trial 3 with value: 0.5.

Best trial: 5. Best value: 0.528612:  14%|█▍        | 7/50 [02:08<13:11, 18.42s/it]

[I 2025-12-02 17:25:01,191] Trial 5 finished with value: 0.5286116322701688 and parameters: {'max_depth': 4, 'learning_rate': 0.279714694054324, 'n_estimators': 1190, 'subsample': 0.5316942785113923, 'colsample_bytree': 0.9821586948225077, 'min_child_weight': 5, 'gamma': 1.0214995062801098, 'reg_alpha': 9.367151664646464e-06, 'reg_lambda': 1.7865109497976899, 'max_delta_step': 0}. Best is trial 5 with value: 0.5286116322701688.

Best trial: 5. Best value: 0.528612:  16%|█▌        | 8/50 [02:30<13:34, 19.39s/it]

[I 2025-12-02 17:25:22,682] Trial 7 finished with value: 0.49718574108818014 and parameters: {'max_depth': 5, 'learning_rate': 0.07345362076829313, 'n_estimators': 1388, 'subsample': 0.6460229549924481, 'colsample_bytree': 0.8354243943974257, 'min_child_weight': 5, 'gamma': 2.8720300576268087, 'reg_alpha': 0.00011649328876793755, 'reg_lambda': 5.493874916639431e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.5286116322701688.

Best trial: 5. Best value: 0.528612:  18%|█▊        | 9/50 [03:01<15:45, 23.06s/it]

[I 2025-12-02 17:25:53,813] Trial 8 finished with value: 0.4901500938086304 and parameters: {'max_depth': 9, 'learning_rate': 0.08708786480886868, 'n_estimators': 1267, 'subsample': 0.9583604561274981, 'colsample_bytree': 0.8716123281033445, 'min_child_weight': 4, 'gamma': 0.3772490926821781, 'reg_alpha': 3.05878403066122, 'reg_lambda': 0.0003867000775839595, 'max_delta_step': 9}. Best is trial 5 with value: 0.5286116322701688.

Best trial: 5. Best value: 0.528612:  20%|██        | 10/50 [03:08<12:03, 18.09s/it]

[I 2025-12-02 17:26:00,783] Trial 9 finished with value: 0.5093808630393997 and parameters: {'max_depth': 6, 'learning_rate': 0.07327449551587598, 'n_estimators': 1422, 'subsample': 0.6172076509212998, 'colsample_bytree': 0.57867565663556, 'min_child_weight': 5, 'gamma': 4.791636033171881, 'reg_alpha': 0.004320149148367712, 'reg_lambda': 6.982888198182636e-08, 'max_delta_step': 6}. Best is trial 5 with value: 0.5286116322701688.

Best trial: 5. Best value: 0.528612:  22%|██▏       | 11/50 [03:10<08:38, 13.29s/it]

[I 2025-12-02 17:26:03,164] Trial 12 pruned.

Best trial: 5. Best value: 0.528612:  24%|██▍       | 12/50 [03:11<06:00,  9.48s/it]

[I 2025-12-02 17:26:03,924] Trial 13 pruned.

Best trial: 5. Best value: 0.528612:  26%|██▌       | 13/50 [03:16<04:58,  8.06s/it]

[I 2025-12-02 17:26:08,708] Trial 11 pruned.

Best trial: 10. Best value: 0.588649:  28%|██▊       | 14/50 [03:16<03:29,  5.81s/it]

[I 2025-12-02 17:26:09,347] Trial 10 finished with value: 0.5886491557223265 and parameters: {'max_depth': 6, 'learning_rate': 0.2653940412629463, 'n_estimators': 1234, 'subsample': 0.966978603585821, 'colsample_bytree': 0.7854383166045973, 'min_child_weight': 10, 'gamma': 1.692887191295915, 'reg_alpha': 2.1911894920760554e-06, 'reg_lambda': 5.911443478666218e-06, 'max_delta_step': 9}. Best is trial 10 with value: 0.5886491557223265.

Best trial: 10. Best value: 0.588649:  30%|███       | 15/50 [03:24<03:47,  6.50s/it]

[I 2025-12-02 17:26:17,440] Trial 15 pruned.

Best trial: 10. Best value: 0.588649:  32%|███▏      | 16/50 [03:27<03:06,  5.47s/it]

[I 2025-12-02 17:26:20,520] Trial 14 pruned.

Best trial: 10. Best value: 0.588649:  34%|███▍      | 17/50 [03:34<03:10,  5.77s/it]

[I 2025-12-02 17:26:26,985] Trial 18 pruned.

Best trial: 10. Best value: 0.588649:  36%|███▌      | 18/50 [03:37<02:35,  4.87s/it]

[I 2025-12-02 17:26:29,776] Trial 19 pruned.

Best trial: 10. Best value: 0.588649:  38%|███▊      | 19/50 [03:52<04:05,  7.91s/it]

[I 2025-12-02 17:26:44,758] Trial 20 pruned.

Best trial: 10. Best value: 0.588649:  40%|████      | 20/50 [04:08<05:15, 10.53s/it]

[I 2025-12-02 17:27:01,387] Trial 22 pruned.

Best trial: 10. Best value: 0.588649:  42%|████▏     | 21/50 [04:10<03:47,  7.83s/it]

[I 2025-12-02 17:27:02,928] Trial 21 pruned.

Best trial: 10. Best value: 0.588649:  44%|████▍     | 22/50 [04:17<03:36,  7.74s/it]

[I 2025-12-02 17:27:10,442] Trial 17 finished with value: 0.49718574108818014 and parameters: {'max_depth': 7, 'learning_rate': 0.15572856736449642, 'n_estimators': 982, 'subsample': 0.8232903615898617, 'colsample_bytree': 0.9908281972770365, 'min_child_weight': 7, 'gamma': 1.209175220197591, 'reg_alpha': 1.0086279514748157e-08, 'reg_lambda': 0.008363892425679214, 'max_delta_step': 2}. Best is trial 10 with value: 0.5886491557223265.

Best trial: 10. Best value: 0.588649:  46%|████▌     | 23/50 [04:23<03:14,  7.22s/it]

[I 2025-12-02 17:27:16,455] Trial 24 pruned.

Best trial: 10. Best value: 0.588649:  48%|████▊     | 24/50 [04:34<03:32,  8.18s/it]

[I 2025-12-02 17:27:26,883] Trial 26 pruned.

Best trial: 10. Best value: 0.588649:  50%|█████     | 25/50 [04:38<02:54,  6.99s/it]

[I 2025-12-02 17:27:31,081] Trial 16 finished with value: 0.44840525328330205 and parameters: {'max_depth': 7, 'learning_rate': 0.14357860232768904, 'n_estimators': 1489, 'subsample': 0.5018047826822218, 'colsample_bytree': 0.606001729271628, 'min_child_weight': 6, 'gamma': 4.9900567979768615, 'reg_alpha': 3.0619582536226176e-06, 'reg_lambda': 0.01933669999556664, 'max_delta_step': 2}. Best is trial 10 with value: 0.5886491557223265.

Best trial: 10. Best value: 0.588649:  52%|█████▏    | 26/50 [04:53<03:48,  9.51s/it]

[I 2025-12-02 17:27:46,469] Trial 28 pruned.

Best trial: 10. Best value: 0.588649:  54%|█████▍    | 27/50 [04:54<02:37,  6.83s/it]

[I 2025-12-02 17:27:47,063] Trial 23 finished with value: 0.4953095684803002 and parameters: {'max_depth': 6, 'learning_rate': 0.12689920226097812, 'n_estimators': 634, 'subsample': 0.8901935135053967, 'colsample_bytree': 0.7576950587190915, 'min_child_weight': 6, 'gamma': 2.2409666923313027, 'reg_alpha': 5.802599353808218e-07, 'reg_lambda': 0.10263507601244398, 'max_delta_step': 10}. Best is trial 10 with value: 0.5886491557223265.

Best trial: 10. Best value: 0.588649:  56%|█████▌    | 28/50 [05:20<04:36, 12.55s/it]

[I 2025-12-02 17:28:12,945] Trial 29 pruned.

Best trial: 10. Best value: 0.588649:  58%|█████▊    | 29/50 [05:22<03:17,  9.42s/it]

[I 2025-12-02 17:28:15,076] Trial 30 pruned.

Best trial: 10. Best value: 0.588649:  60%|██████    | 30/50 [05:32<03:11,  9.60s/it]

[I 2025-12-02 17:28:25,068] Trial 32 pruned.

Best trial: 10. Best value: 0.588649:  62%|██████▏   | 31/50 [05:40<02:52,  9.09s/it]

[I 2025-12-02 17:28:32,995] Trial 31 pruned.

Best trial: 10. Best value: 0.588649:  64%|██████▍   | 32/50 [05:41<02:00,  6.67s/it]

[I 2025-12-02 17:28:34,015] Trial 25 finished with value: 0.5023452157598499 and parameters: {'max_depth': 6, 'learning_rate': 0.055314235399020965, 'n_estimators': 1360, 'subsample': 0.5826797124671768, 'colsample_bytree': 0.5454758448626551, 'min_child_weight': 5, 'gamma': 2.3860685732626177, 'reg_alpha': 0.0014029949811328387, 'reg_lambda': 1.8001532617744978e-07, 'max_delta_step': 10}. Best is trial 10 with value: 0.5886491557223265.

Best trial: 10. Best value: 0.588649:  66%|██████▌   | 33/50 [05:50<02:05,  7.39s/it]

[I 2025-12-02 17:28:43,078] Trial 34 pruned.

Best trial: 10. Best value: 0.588649:  68%|██████▊   | 34/50 [05:53<01:36,  6.02s/it]

[I 2025-12-02 17:28:45,892] Trial 35 pruned.

Best trial: 10. Best value: 0.588649:  70%|███████   | 35/50 [06:07<02:05,  8.35s/it]

[I 2025-12-02 17:28:59,695] Trial 27 finished with value: 0.5215759849906192 and parameters: {'max_depth': 5, 'learning_rate': 0.05213101772988681, 'n_estimators': 1406, 'subsample': 0.5648425135373923, 'colsample_bytree': 0.7314082033190012, 'min_child_weight': 4, 'gamma': 2.3241265557231117, 'reg_alpha': 4.677363646750003e-05, 'reg_lambda': 1.2881801204779697e-05, 'max_delta_step': 8}. Best is trial 10 with value: 0.5886491557223265.

Best trial: 10. Best value: 0.588649:  72%|███████▏  | 36/50 [06:18<02:11,  9.36s/it]

[I 2025-12-02 17:29:11,415] Trial 38 pruned.

Best trial: 10. Best value: 0.588649:  74%|███████▍  | 37/50 [06:44<03:04, 14.18s/it]

[I 2025-12-02 17:29:36,827] Trial 33 finished with value: 0.4606003752345216 and parameters: {'max_depth': 5, 'learning_rate': 0.20327126850869917, 'n_estimators': 1191, 'subsample': 0.7244416274493738, 'colsample_bytree': 0.7094709544909381, 'min_child_weight': 8, 'gamma': 2.4870479907064116, 'reg_alpha': 0.27252551402871544, 'reg_lambda': 5.735219840437947e-06, 'max_delta_step': 5}. Best is trial 10 with value: 0.5886491557223265.

Best trial: 10. Best value: 0.588649:  76%|███████▌  | 38/50 [06:45<02:05, 10.42s/it]

[I 2025-12-02 17:29:38,464] Trial 39 pruned.

Best trial: 10. Best value: 0.588649:  78%|███████▊  | 39/50 [06:53<01:46,  9.72s/it]

[I 2025-12-02 17:29:46,555] Trial 41 pruned.

Best trial: 10. Best value: 0.588649:  80%|████████  | 40/50 [06:59<01:23,  8.34s/it]

[I 2025-12-02 17:29:51,679] Trial 40 pruned.

Best trial: 10. Best value: 0.588649:  82%|████████▏ | 41/50 [07:08<01:17,  8.64s/it]

[I 2025-12-02 17:30:00,994] Trial 37 finished with value: 0.3400562851782364 and parameters: {'max_depth': 6, 'learning_rate': 0.061389803778488204, 'n_estimators': 1321, 'subsample': 0.5994001047767747, 'colsample_bytree': 0.532905946930281, 'min_child_weight': 8, 'gamma': 1.7267181229633823, 'reg_alpha': 0.012150633453449782, 'reg_lambda': 2.0693965606642743e-05, 'max_delta_step': 8}. Best is trial 10 with value: 0.5886491557223265.

Best trial: 10. Best value: 0.588649:  84%|████████▍ | 42/50 [07:10<00:52,  6.53s/it]

[I 2025-12-02 17:30:02,604] Trial 36 finished with value: 0.5511257035647279 and parameters: {'max_depth': 6, 'learning_rate': 0.054162747608036174, 'n_estimators': 1198, 'subsample': 0.6072947948317048, 'colsample_bytree': 0.5517290937200878, 'min_child_weight': 4, 'gamma': 0.021783589345513055, 'reg_alpha': 0.009029326297558149, 'reg_lambda': 3.1919686500931205e-08, 'max_delta_step': 9}. Best is trial 10 with value: 0.5886491557223265.

Best trial: 10. Best value: 0.588649:  86%|████████▌ | 43/50 [07:14<00:42,  6.03s/it]

[I 2025-12-02 17:30:07,487] Trial 43 pruned.

Best trial: 10. Best value: 0.588649:  88%|████████▊ | 44/50 [07:20<00:35,  5.90s/it]

[I 2025-12-02 17:30:13,082] Trial 44 pruned.

Best trial: 10. Best value: 0.588649:  90%|█████████ | 45/50 [07:29<00:34,  6.94s/it]

[I 2025-12-02 17:30:22,461] Trial 47 pruned.

Best trial: 10. Best value: 0.588649:  92%|█████████▏| 46/50 [07:34<00:24,  6.13s/it]

[I 2025-12-02 17:30:26,682] Trial 42 pruned.

Best trial: 10. Best value: 0.588649:  94%|█████████▍| 47/50 [07:34<00:13,  4.41s/it]

[I 2025-12-02 17:30:27,073] Trial 46 pruned.

Best trial: 10. Best value: 0.588649:  96%|█████████▌| 48/50 [07:43<00:11,  5.92s/it]

[I 2025-12-02 17:30:36,536] Trial 48 pruned.

Best trial: 10. Best value: 0.588649:  98%|█████████▊| 49/50 [07:44<00:04,  4.22s/it]

[I 2025-12-02 17:30:36,771] Trial 49 pruned.

Best trial: 10. Best value: 0.588649: 100%|██████████| 50/50 [08:06<00:00,  9.73s/it]

[I 2025-12-02 17:30:59,068] Trial 45 finished with value: 0.5093808630393997 and parameters: {'max_depth': 5, 'learning_rate': 0.04964655492731728, 'n_estimators': 1222, 'subsample': 0.541040960683458, 'colsample_bytree': 0.834865062804554, 'min_child_weight': 5, 'gamma': 0.3676762035683159, 'reg_alpha': 1.6620079997677441e-06, 'reg_lambda': 0.00047865080359967704, 'max_delta_step': 9}. Best is trial 10 with value: 0.5886491557223265.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.588649                0.535714      0.614286

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0   0.07043          0.571429               0.5        50          67

   test_size
0         17
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.588649                0.535714      0.614286

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0   0.07043          0.571429               0.5        50          67

   test_size
0         17

In [ ]:

datasets = task_freq_dfs_lbd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_lbd_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_freq_lbd_hc_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param="emb_",
)
print(summary)

[I 2025-12-02 17:31:02,336] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 67, Test size: 17
Using Leave-One-Out CV with 67 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.44137:   2%|▏         | 1/50 [00:45<36:51, 45.14s/it]

[I 2025-12-02 17:31:47,469] Trial 0 finished with value: 0.44136960600375236 and parameters: {'max_depth': 3, 'learning_rate': 0.2946412210777808, 'n_estimators': 613, 'subsample': 0.9202284121330888, 'colsample_bytree': 0.9004642850294684, 'min_child_weight': 4, 'gamma': 4.121428147324186, 'reg_alpha': 2.220122614926347e-08, 'reg_lambda': 1.0015727839709397e-05, 'max_delta_step': 3}. Best is trial 0 with value: 0.44136960600375236.

Best trial: 0. Best value: 0.44137:   4%|▍         | 2/50 [01:04<23:51, 29.82s/it]

[I 2025-12-02 17:32:06,565] Trial 3 finished with value: 0.42401500938086306 and parameters: {'max_depth': 5, 'learning_rate': 0.023913863744313268, 'n_estimators': 879, 'subsample': 0.8291010476507032, 'colsample_bytree': 0.6781542960331002, 'min_child_weight': 5, 'gamma': 4.438098479750727, 'reg_alpha': 0.5000880632131888, 'reg_lambda': 2.44899498086121, 'max_delta_step': 7}. Best is trial 0 with value: 0.44136960600375236.

Best trial: 0. Best value: 0.44137:   6%|▌         | 3/50 [01:07<13:58, 17.84s/it]

[I 2025-12-02 17:32:10,158] Trial 2 finished with value: 0.43433395872420266 and parameters: {'max_depth': 8, 'learning_rate': 0.03532101932391344, 'n_estimators': 1126, 'subsample': 0.5366049757589648, 'colsample_bytree': 0.7603512514110644, 'min_child_weight': 5, 'gamma': 2.48312214216217, 'reg_alpha': 0.0036822107694308125, 'reg_lambda': 3.622150313194825e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.44136960600375236.

Best trial: 1. Best value: 0.5:   8%|▊         | 4/50 [01:15<10:31, 13.74s/it]

[I 2025-12-02 17:32:17,596] Trial 1 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.12772910697877612, 'n_estimators': 1497, 'subsample': 0.7599026867810253, 'colsample_bytree': 0.5908271113923773, 'min_child_weight': 10, 'gamma': 0.5602010211211084, 'reg_alpha': 6.600354076199905e-05, 'reg_lambda': 0.38649955136102704, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  10%|█         | 5/50 [01:44<14:30, 19.34s/it]

[I 2025-12-02 17:32:46,876] Trial 5 finished with value: 0.4099437148217636 and parameters: {'max_depth': 8, 'learning_rate': 0.29358331189967934, 'n_estimators': 643, 'subsample': 0.5138072337803259, 'colsample_bytree': 0.8926119358901144, 'min_child_weight': 5, 'gamma': 0.5303430333147963, 'reg_alpha': 5.954505925516468, 'reg_lambda': 0.0003155544340692013, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  12%|█▏        | 6/50 [01:51<10:58, 14.96s/it]

[I 2025-12-02 17:32:53,344] Trial 4 finished with value: 0.13414634146341464 and parameters: {'max_depth': 3, 'learning_rate': 0.017561196780035274, 'n_estimators': 1181, 'subsample': 0.7587801853101388, 'colsample_bytree': 0.8125993115999418, 'min_child_weight': 10, 'gamma': 3.2306945810831555, 'reg_alpha': 1.2386772701188031, 'reg_lambda': 0.14836279961427934, 'max_delta_step': 5}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  14%|█▍        | 7/50 [01:58<08:53, 12.41s/it]

[I 2025-12-02 17:33:00,492] Trial 6 finished with value: 0.2926829268292683 and parameters: {'max_depth': 6, 'learning_rate': 0.02967997071694721, 'n_estimators': 876, 'subsample': 0.5073324298919994, 'colsample_bytree': 0.935091015247975, 'min_child_weight': 10, 'gamma': 2.7074140945026546, 'reg_alpha': 6.577802385298405e-07, 'reg_lambda': 0.000517069258051516, 'max_delta_step': 0}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  16%|█▌        | 8/50 [02:25<12:01, 17.19s/it]

[I 2025-12-02 17:33:27,911] Trial 10 finished with value: 0.42213883677298314 and parameters: {'max_depth': 5, 'learning_rate': 0.06614449271124541, 'n_estimators': 368, 'subsample': 0.7628631253682274, 'colsample_bytree': 0.9921330784069453, 'min_child_weight': 6, 'gamma': 2.826619640182384, 'reg_alpha': 0.00028285956123433775, 'reg_lambda': 6.835433648437888e-08, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  18%|█▊        | 9/50 [02:40<11:13, 16.42s/it]

[I 2025-12-02 17:33:42,643] Trial 8 finished with value: 0.0975609756097561 and parameters: {'max_depth': 6, 'learning_rate': 0.010863178026560597, 'n_estimators': 1023, 'subsample': 0.5140371502112848, 'colsample_bytree': 0.7230067748171709, 'min_child_weight': 10, 'gamma': 0.9070699432480084, 'reg_alpha': 4.986842286650116e-05, 'reg_lambda': 0.0016043839137252604, 'max_delta_step': 4}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  20%|██        | 10/50 [02:40<07:38, 11.46s/it]

[I 2025-12-02 17:33:42,986] Trial 7 finished with value: 0.44840525328330205 and parameters: {'max_depth': 3, 'learning_rate': 0.01990656348961266, 'n_estimators': 1311, 'subsample': 0.8993016529916295, 'colsample_bytree': 0.5252294212649191, 'min_child_weight': 5, 'gamma': 4.08710246465045, 'reg_alpha': 5.445262466007032e-06, 'reg_lambda': 4.381467492947818e-05, 'max_delta_step': 6}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  22%|██▏       | 11/50 [02:43<05:49,  8.96s/it]

[I 2025-12-02 17:33:46,270] Trial 11 pruned.

Best trial: 1. Best value: 0.5:  24%|██▍       | 12/50 [02:45<04:11,  6.62s/it]

[I 2025-12-02 17:33:47,546] Trial 12 pruned.

Best trial: 1. Best value: 0.5:  26%|██▌       | 13/50 [02:54<04:37,  7.49s/it]

[I 2025-12-02 17:33:57,043] Trial 13 pruned.

Best trial: 1. Best value: 0.5:  28%|██▊       | 14/50 [02:58<03:47,  6.33s/it]

[I 2025-12-02 17:34:00,696] Trial 14 pruned.

Best trial: 1. Best value: 0.5:  30%|███       | 15/50 [02:58<02:39,  4.57s/it]

[I 2025-12-02 17:34:01,172] Trial 15 pruned.

Best trial: 1. Best value: 0.5:  32%|███▏      | 16/50 [03:07<03:12,  5.68s/it]

[I 2025-12-02 17:34:09,428] Trial 9 finished with value: 0.42213883677298314 and parameters: {'max_depth': 7, 'learning_rate': 0.04062410166153883, 'n_estimators': 1235, 'subsample': 0.7366979122029471, 'colsample_bytree': 0.654573649928659, 'min_child_weight': 5, 'gamma': 2.0893953355951576, 'reg_alpha': 0.001157126212298134, 'reg_lambda': 5.471387612611084e-07, 'max_delta_step': 2}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  34%|███▍      | 17/50 [03:10<02:47,  5.07s/it]

[I 2025-12-02 17:34:13,077] Trial 17 pruned.

Best trial: 1. Best value: 0.5:  36%|███▌      | 18/50 [03:22<03:42,  6.94s/it]

[I 2025-12-02 17:34:24,373] Trial 20 pruned.

Best trial: 1. Best value: 0.5:  38%|███▊      | 19/50 [03:33<04:19,  8.38s/it]

[I 2025-12-02 17:34:36,115] Trial 21 pruned.

Best trial: 1. Best value: 0.5:  40%|████      | 20/50 [03:45<04:38,  9.30s/it]

[I 2025-12-02 17:34:47,551] Trial 22 pruned.

Best trial: 1. Best value: 0.5:  42%|████▏     | 21/50 [03:53<04:21,  9.02s/it]

[I 2025-12-02 17:34:55,936] Trial 23 pruned.

Best trial: 1. Best value: 0.5:  44%|████▍     | 22/50 [04:05<04:34,  9.80s/it]

[I 2025-12-02 17:35:07,564] Trial 18 pruned.

Best trial: 1. Best value: 0.5:  46%|████▌     | 23/50 [04:20<05:06, 11.36s/it]

[I 2025-12-02 17:35:22,537] Trial 19 finished with value: 0.43433395872420266 and parameters: {'max_depth': 4, 'learning_rate': 0.17359113742607657, 'n_estimators': 1320, 'subsample': 0.6780116926120816, 'colsample_bytree': 0.6093232543260864, 'min_child_weight': 3, 'gamma': 0.038403082947934375, 'reg_alpha': 9.701990626826062e-08, 'reg_lambda': 1.5573638379008277e-05, 'max_delta_step': 8}. Best is trial 1 with value: 0.5.

Best trial: 1. Best value: 0.5:  48%|████▊     | 24/50 [04:26<04:18,  9.94s/it]

[I 2025-12-02 17:35:29,175] Trial 26 pruned.

Best trial: 1. Best value: 0.5:  50%|█████     | 25/50 [04:34<03:49,  9.17s/it]

[I 2025-12-02 17:35:36,554] Trial 25 pruned.

Best trial: 16. Best value: 0.528612:  52%|█████▏    | 26/50 [04:34<02:39,  6.65s/it]

[I 2025-12-02 17:35:37,311] Trial 16 finished with value: 0.5286116322701688 and parameters: {'max_depth': 4, 'learning_rate': 0.1259424418947858, 'n_estimators': 1493, 'subsample': 0.986884539316466, 'colsample_bytree': 0.5099464222436907, 'min_child_weight': 3, 'gamma': 4.795725216781525, 'reg_alpha': 5.026236751377277e-06, 'reg_lambda': 1.0121182854270608e-05, 'max_delta_step': 9}. Best is trial 16 with value: 0.5286116322701688.

Best trial: 16. Best value: 0.528612:  54%|█████▍    | 27/50 [04:39<02:18,  6.02s/it]

[I 2025-12-02 17:35:41,852] Trial 28 pruned.

Best trial: 16. Best value: 0.528612:  56%|█████▌    | 28/50 [04:41<01:45,  4.81s/it]

[I 2025-12-02 17:35:43,865] Trial 24 finished with value: 0.44840525328330205 and parameters: {'max_depth': 3, 'learning_rate': 0.27322039279173477, 'n_estimators': 654, 'subsample': 0.9290194116451795, 'colsample_bytree': 0.6999900673245713, 'min_child_weight': 3, 'gamma': 4.056193470880142, 'reg_alpha': 1.1133338080800175e-08, 'reg_lambda': 2.5858929810885572e-05, 'max_delta_step': 2}. Best is trial 16 with value: 0.5286116322701688.

Best trial: 16. Best value: 0.528612:  58%|█████▊    | 29/50 [04:48<01:54,  5.44s/it]

[I 2025-12-02 17:35:50,767] Trial 29 pruned.

Best trial: 16. Best value: 0.528612:  60%|██████    | 30/50 [04:53<01:46,  5.31s/it]

[I 2025-12-02 17:35:55,781] Trial 30 pruned.

Best trial: 16. Best value: 0.528612:  62%|██████▏   | 31/50 [04:59<01:46,  5.62s/it]

[I 2025-12-02 17:36:02,106] Trial 32 pruned.

Best trial: 16. Best value: 0.528612:  64%|██████▍   | 32/50 [05:03<01:32,  5.16s/it]

[I 2025-12-02 17:36:06,187] Trial 33 pruned.

Best trial: 16. Best value: 0.528612:  66%|██████▌   | 33/50 [05:09<01:30,  5.34s/it]

[I 2025-12-02 17:36:11,954] Trial 31 pruned.

Best trial: 16. Best value: 0.528612:  68%|██████▊   | 34/50 [05:18<01:40,  6.29s/it]

[I 2025-12-02 17:36:20,459] Trial 27 finished with value: 0.474671669793621 and parameters: {'max_depth': 3, 'learning_rate': 0.08219213497557416, 'n_estimators': 742, 'subsample': 0.9548257298876947, 'colsample_bytree': 0.6999116632058602, 'min_child_weight': 6, 'gamma': 4.19517019642314, 'reg_alpha': 6.733454750914192e-06, 'reg_lambda': 5.481715010927937e-07, 'max_delta_step': 4}. Best is trial 16 with value: 0.5286116322701688.

Best trial: 16. Best value: 0.528612:  70%|███████   | 35/50 [05:28<01:52,  7.50s/it]

[I 2025-12-02 17:36:30,782] Trial 37 pruned.

Best trial: 34. Best value: 0.577392:  72%|███████▏  | 36/50 [05:50<02:45, 11.83s/it]

[I 2025-12-02 17:36:52,734] Trial 34 finished with value: 0.5773921200750469 and parameters: {'max_depth': 3, 'learning_rate': 0.21652722993303372, 'n_estimators': 704, 'subsample': 0.8746637204206233, 'colsample_bytree': 0.6768157687656905, 'min_child_weight': 2, 'gamma': 4.258675970496892, 'reg_alpha': 7.739048182630408e-07, 'reg_lambda': 0.00022640579719264618, 'max_delta_step': 0}. Best is trial 34 with value: 0.5773921200750469.

Best trial: 34. Best value: 0.577392:  74%|███████▍  | 37/50 [05:53<01:59,  9.16s/it]

[I 2025-12-02 17:36:55,642] Trial 36 finished with value: 0.47795497185741087 and parameters: {'max_depth': 3, 'learning_rate': 0.22428297198698804, 'n_estimators': 765, 'subsample': 0.8808810568277595, 'colsample_bytree': 0.6958978858214903, 'min_child_weight': 6, 'gamma': 4.213013734730272, 'reg_alpha': 2.252571057095883e-05, 'reg_lambda': 0.00022624117089276385, 'max_delta_step': 0}. Best is trial 34 with value: 0.5773921200750469.

Best trial: 34. Best value: 0.577392:  76%|███████▌  | 38/50 [05:56<01:29,  7.49s/it]

[I 2025-12-02 17:36:59,247] Trial 39 pruned.

Best trial: 34. Best value: 0.577392:  78%|███████▊  | 39/50 [05:58<01:02,  5.69s/it]

[I 2025-12-02 17:37:00,733] Trial 35 finished with value: 0.5600375234521576 and parameters: {'max_depth': 3, 'learning_rate': 0.2071359502466126, 'n_estimators': 737, 'subsample': 0.9527243507122123, 'colsample_bytree': 0.6889951910662413, 'min_child_weight': 2, 'gamma': 4.163751068856093, 'reg_alpha': 1.8205623358844666e-06, 'reg_lambda': 0.00017779978999337857, 'max_delta_step': 0}. Best is trial 34 with value: 0.5773921200750469.

Best trial: 34. Best value: 0.577392:  80%|████████  | 40/50 [06:00<00:44,  4.48s/it]

[I 2025-12-02 17:37:02,380] Trial 40 pruned.

Best trial: 34. Best value: 0.577392:  84%|████████▍ | 42/50 [06:10<00:34,  4.30s/it]

[I 2025-12-02 17:37:12,214] Trial 43 pruned.
[I 2025-12-02 17:37:12,357] Trial 42 pruned.

Best trial: 34. Best value: 0.577392:  86%|████████▌ | 43/50 [06:10<00:21,  3.05s/it]

[I 2025-12-02 17:37:12,487] Trial 38 finished with value: 0.40478424015009384 and parameters: {'max_depth': 3, 'learning_rate': 0.2041252472953776, 'n_estimators': 820, 'subsample': 0.5770840804996399, 'colsample_bytree': 0.5719316992816565, 'min_child_weight': 7, 'gamma': 4.1918871968169675, 'reg_alpha': 1.9054595538575545e-06, 'reg_lambda': 0.5156688594290871, 'max_delta_step': 4}. Best is trial 34 with value: 0.5773921200750469.

Best trial: 34. Best value: 0.577392:  88%|████████▊ | 44/50 [06:24<00:38,  6.39s/it]

[I 2025-12-02 17:37:26,673] Trial 45 pruned.

Best trial: 44. Best value: 0.635084:  90%|█████████ | 45/50 [06:45<00:54, 10.94s/it]

[I 2025-12-02 17:37:48,238] Trial 44 finished with value: 0.6350844277673546 and parameters: {'max_depth': 9, 'learning_rate': 0.222926934678825, 'n_estimators': 531, 'subsample': 0.8738953810726743, 'colsample_bytree': 0.6346999447496744, 'min_child_weight': 2, 'gamma': 4.24690706729607, 'reg_alpha': 2.336564204463277e-05, 'reg_lambda': 0.00014250663760982936, 'max_delta_step': 1}. Best is trial 44 with value: 0.6350844277673546.

Best trial: 44. Best value: 0.635084:  92%|█████████▏| 46/50 [06:59<00:46, 11.68s/it]

[I 2025-12-02 17:38:01,636] Trial 46 finished with value: 0.6280487804878049 and parameters: {'max_depth': 4, 'learning_rate': 0.1991748220197117, 'n_estimators': 704, 'subsample': 0.879489318672012, 'colsample_bytree': 0.6342929094629004, 'min_child_weight': 1, 'gamma': 3.3688384291197577, 'reg_alpha': 2.0578792005111673e-05, 'reg_lambda': 7.318488631165322e-05, 'max_delta_step': 1}. Best is trial 44 with value: 0.6350844277673546.

Best trial: 44. Best value: 0.635084:  94%|█████████▍| 47/50 [07:00<00:25,  8.39s/it]

[I 2025-12-02 17:38:02,340] Trial 41 finished with value: 0.5670731707317074 and parameters: {'max_depth': 6, 'learning_rate': 0.20917404629964523, 'n_estimators': 943, 'subsample': 0.8573503434446523, 'colsample_bytree': 0.7826579481698468, 'min_child_weight': 2, 'gamma': 2.715536923669867, 'reg_alpha': 3.496063666054242e-07, 'reg_lambda': 0.0001445003766377751, 'max_delta_step': 1}. Best is trial 44 with value: 0.6350844277673546.

Best trial: 44. Best value: 0.635084:  96%|█████████▌| 48/50 [07:02<00:13,  6.54s/it]

[I 2025-12-02 17:38:04,578] Trial 49 pruned.

Best trial: 44. Best value: 0.635084:  98%|█████████▊| 49/50 [07:13<00:07,  7.82s/it]

[I 2025-12-02 17:38:15,363] Trial 47 finished with value: 0.4901500938086304 and parameters: {'max_depth': 3, 'learning_rate': 0.12751390731616222, 'n_estimators': 909, 'subsample': 0.8870745948655071, 'colsample_bytree': 0.7304664742600137, 'min_child_weight': 4, 'gamma': 2.3833242208272787, 'reg_alpha': 8.983163662898502e-05, 'reg_lambda': 0.00015181591267320765, 'max_delta_step': 0}. Best is trial 44 with value: 0.6350844277673546.

Best trial: 44. Best value: 0.635084: 100%|██████████| 50/50 [07:16<00:00,  8.73s/it]

[I 2025-12-02 17:38:18,942] Trial 48 finished with value: 0.5966228893058161 and parameters: {'max_depth': 9, 'learning_rate': 0.13221450078376848, 'n_estimators': 496, 'subsample': 0.9765564957398681, 'colsample_bytree': 0.6443231032003356, 'min_child_weight': 2, 'gamma': 3.69123505091884, 'reg_alpha': 0.004144498211473321, 'reg_lambda': 0.00020696333243478543, 'max_delta_step': 1}. Best is trial 44 with value: 0.6350844277673546.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.635084                0.585714      0.614286

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.169031          0.571429               0.6        50          67

   test_size
0         17
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.635084                0.585714      0.614286

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.169031          0.571429               0.6        50          67

   test_size
0         17

In [ ]:

# Temporal embedings
datasets = task_temp_dfs_lbd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    #    scoring="balanced_accuracy",     # or "roc_auc"
    scoring="balanced_accuracy",      
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_lbd_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_temp_lbd_hc_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param="emb_",
)
print(summary)

[I 2025-12-02 17:38:25,053] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 67, Test size: 17
Using Leave-One-Out CV with 67 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.567073:   2%|▏         | 1/50 [00:18<15:06, 18.50s/it]

[I 2025-12-02 17:38:43,553] Trial 1 finished with value: 0.5670731707317074 and parameters: {'max_depth': 6, 'learning_rate': 0.19381458663921958, 'n_estimators': 226, 'subsample': 0.6455953130901168, 'colsample_bytree': 0.643291930927643, 'min_child_weight': 4, 'gamma': 4.87201918889706, 'reg_alpha': 0.9663620234836144, 'reg_lambda': 1.1503915056860427e-05, 'max_delta_step': 9}. Best is trial 1 with value: 0.5670731707317074.

Best trial: 1. Best value: 0.567073:   4%|▍         | 2/50 [01:02<26:41, 33.36s/it]

[I 2025-12-02 17:39:27,307] Trial 2 finished with value: 0.449812382739212 and parameters: {'max_depth': 6, 'learning_rate': 0.016399943202240728, 'n_estimators': 1124, 'subsample': 0.9422129245577899, 'colsample_bytree': 0.8215103290506063, 'min_child_weight': 10, 'gamma': 3.288855914953755, 'reg_alpha': 0.0008004957388164854, 'reg_lambda': 0.41930794594812776, 'max_delta_step': 3}. Best is trial 1 with value: 0.5670731707317074.

Best trial: 1. Best value: 0.567073:   6%|▌         | 3/50 [01:12<17:56, 22.90s/it]

[I 2025-12-02 17:39:37,771] Trial 4 finished with value: 0.46575984990619135 and parameters: {'max_depth': 8, 'learning_rate': 0.011652220795715854, 'n_estimators': 991, 'subsample': 0.6947962790574682, 'colsample_bytree': 0.6345737630833208, 'min_child_weight': 8, 'gamma': 0.10144067465925, 'reg_alpha': 0.0004008087808738235, 'reg_lambda': 4.080450518189532e-06, 'max_delta_step': 6}. Best is trial 1 with value: 0.5670731707317074.

Best trial: 1. Best value: 0.567073:   8%|▊         | 4/50 [01:14<11:17, 14.72s/it]

[I 2025-12-02 17:39:39,949] Trial 0 finished with value: 0.5600375234521576 and parameters: {'max_depth': 7, 'learning_rate': 0.11410636906869706, 'n_estimators': 1336, 'subsample': 0.967272422092743, 'colsample_bytree': 0.5482911255591311, 'min_child_weight': 4, 'gamma': 0.3465600459020757, 'reg_alpha': 1.969783880129817e-08, 'reg_lambda': 5.976112777315668e-05, 'max_delta_step': 10}. Best is trial 1 with value: 0.5670731707317074.

Best trial: 1. Best value: 0.567073:  10%|█         | 5/50 [01:28<10:43, 14.30s/it]

[I 2025-12-02 17:39:53,487] Trial 3 finished with value: 0.5389305816135084 and parameters: {'max_depth': 3, 'learning_rate': 0.05469956982486388, 'n_estimators': 1100, 'subsample': 0.5666701067278457, 'colsample_bytree': 0.827977878657717, 'min_child_weight': 1, 'gamma': 0.14589449174770397, 'reg_alpha': 0.12160105077629887, 'reg_lambda': 0.03079944021709638, 'max_delta_step': 9}. Best is trial 1 with value: 0.5670731707317074.

Best trial: 1. Best value: 0.567073:  12%|█▏        | 6/50 [01:39<09:39, 13.16s/it]

[I 2025-12-02 17:40:04,449] Trial 5 finished with value: 0.5356472795497186 and parameters: {'max_depth': 10, 'learning_rate': 0.22038808078480834, 'n_estimators': 548, 'subsample': 0.6583716213863906, 'colsample_bytree': 0.6390063272845419, 'min_child_weight': 3, 'gamma': 4.089323281299842, 'reg_alpha': 0.3347885369464171, 'reg_lambda': 0.009482613308182938, 'max_delta_step': 6}. Best is trial 1 with value: 0.5670731707317074.

Best trial: 1. Best value: 0.567073:  14%|█▍        | 7/50 [01:47<08:14, 11.50s/it]

[I 2025-12-02 17:40:12,521] Trial 8 finished with value: 0.4606003752345216 and parameters: {'max_depth': 4, 'learning_rate': 0.05147663412760044, 'n_estimators': 278, 'subsample': 0.9753666617762545, 'colsample_bytree': 0.8512600491085671, 'min_child_weight': 9, 'gamma': 3.714985356929634, 'reg_alpha': 9.971345708903588e-06, 'reg_lambda': 7.794028432050412e-08, 'max_delta_step': 9}. Best is trial 1 with value: 0.5670731707317074.

Best trial: 1. Best value: 0.567073:  16%|█▌        | 8/50 [01:58<08:00, 11.45s/it]

[I 2025-12-02 17:40:23,874] Trial 9 finished with value: 0.5600375234521576 and parameters: {'max_depth': 6, 'learning_rate': 0.02967134176537022, 'n_estimators': 209, 'subsample': 0.5915187190138275, 'colsample_bytree': 0.7984746254932342, 'min_child_weight': 5, 'gamma': 3.274311967699637, 'reg_alpha': 6.368063903847218e-07, 'reg_lambda': 0.04709914982009828, 'max_delta_step': 1}. Best is trial 1 with value: 0.5670731707317074.

Best trial: 1. Best value: 0.567073:  18%|█▊        | 9/50 [02:00<05:40,  8.29s/it]

[I 2025-12-02 17:40:25,221] Trial 7 finished with value: 0.5670731707317074 and parameters: {'max_depth': 7, 'learning_rate': 0.08716243208796903, 'n_estimators': 803, 'subsample': 0.7139431782829482, 'colsample_bytree': 0.5084995110623995, 'min_child_weight': 6, 'gamma': 4.729630873301068, 'reg_alpha': 5.996609314684445e-06, 'reg_lambda': 1.0703507048154355, 'max_delta_step': 8}. Best is trial 1 with value: 0.5670731707317074.

Best trial: 1. Best value: 0.567073:  20%|██        | 10/50 [02:23<08:37, 12.93s/it]

[I 2025-12-02 17:40:48,540] Trial 6 finished with value: 0.3902439024390244 and parameters: {'max_depth': 7, 'learning_rate': 0.021428667574815194, 'n_estimators': 1316, 'subsample': 0.5730216444446796, 'colsample_bytree': 0.9470223482040323, 'min_child_weight': 8, 'gamma': 4.291893404219315, 'reg_alpha': 1.491008011654241e-06, 'reg_lambda': 1.891867647574617e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5670731707317074.

Best trial: 1. Best value: 0.567073:  22%|██▏       | 11/50 [02:31<07:20, 11.30s/it]

[I 2025-12-02 17:40:56,149] Trial 13 pruned.

Best trial: 1. Best value: 0.567073:  24%|██▍       | 12/50 [02:33<05:24,  8.53s/it]

[I 2025-12-02 17:40:58,342] Trial 12 pruned.

Best trial: 1. Best value: 0.567073:  26%|██▌       | 13/50 [02:45<05:57,  9.65s/it]

[I 2025-12-02 17:41:10,569] Trial 11 finished with value: 0.5530018761726079 and parameters: {'max_depth': 8, 'learning_rate': 0.01684345856305297, 'n_estimators': 368, 'subsample': 0.9433090613747174, 'colsample_bytree': 0.5195735488249982, 'min_child_weight': 3, 'gamma': 0.11775616862021998, 'reg_alpha': 0.005779188667053922, 'reg_lambda': 1.53590311009069e-07, 'max_delta_step': 3}. Best is trial 1 with value: 0.5670731707317074.

Best trial: 1. Best value: 0.567073:  28%|██▊       | 14/50 [02:49<04:44,  7.90s/it]

[I 2025-12-02 17:41:14,438] Trial 14 pruned.

Best trial: 1. Best value: 0.567073:  30%|███       | 15/50 [03:03<05:40,  9.74s/it]

[I 2025-12-02 17:41:28,440] Trial 16 pruned.

Best trial: 10. Best value: 0.598499:  32%|███▏      | 16/50 [03:09<04:49,  8.53s/it]

[I 2025-12-02 17:41:34,147] Trial 10 finished with value: 0.5984990619136961 and parameters: {'max_depth': 6, 'learning_rate': 0.01402063284818405, 'n_estimators': 1137, 'subsample': 0.8952300707300446, 'colsample_bytree': 0.6862438817287516, 'min_child_weight': 6, 'gamma': 2.3135070790312477, 'reg_alpha': 6.489443946234792e-07, 'reg_lambda': 8.360685441411166e-06, 'max_delta_step': 9}. Best is trial 10 with value: 0.5984990619136961.

Best trial: 10. Best value: 0.598499:  34%|███▍      | 17/50 [03:10<03:26,  6.25s/it]

[I 2025-12-02 17:41:35,091] Trial 15 finished with value: 0.5984990619136961 and parameters: {'max_depth': 5, 'learning_rate': 0.13142051584097203, 'n_estimators': 628, 'subsample': 0.7895820351849173, 'colsample_bytree': 0.501165838132027, 'min_child_weight': 6, 'gamma': 4.987413715481522, 'reg_alpha': 2.9731583686813723e-05, 'reg_lambda': 4.822460276757604, 'max_delta_step': 8}. Best is trial 10 with value: 0.5984990619136961.

Best trial: 10. Best value: 0.598499:  36%|███▌      | 18/50 [03:25<04:49,  9.03s/it]

[I 2025-12-02 17:41:50,605] Trial 18 pruned.

Best trial: 10. Best value: 0.598499:  38%|███▊      | 19/50 [03:34<04:34,  8.87s/it]

[I 2025-12-02 17:41:59,098] Trial 17 finished with value: 0.5863039399624765 and parameters: {'max_depth': 5, 'learning_rate': 0.14874330977609357, 'n_estimators': 796, 'subsample': 0.6841426516066982, 'colsample_bytree': 0.5960771694411191, 'min_child_weight': 6, 'gamma': 4.9977165086766, 'reg_alpha': 1.0985764080390788e-05, 'reg_lambda': 0.0018926332470845346, 'max_delta_step': 10}. Best is trial 10 with value: 0.5984990619136961.

Best trial: 10. Best value: 0.598499:  40%|████      | 20/50 [03:36<03:26,  6.90s/it]

[I 2025-12-02 17:42:01,402] Trial 20 pruned.

Best trial: 10. Best value: 0.598499:  42%|████▏     | 21/50 [03:40<02:52,  5.96s/it]

[I 2025-12-02 17:42:05,181] Trial 19 pruned.

Best trial: 10. Best value: 0.598499:  44%|████▍     | 22/50 [03:53<03:46,  8.09s/it]

[I 2025-12-02 17:42:18,219] Trial 22 pruned.

Best trial: 10. Best value: 0.598499:  46%|████▌     | 23/50 [03:53<02:35,  5.76s/it]

[I 2025-12-02 17:42:18,547] Trial 21 pruned.

Best trial: 10. Best value: 0.598499:  48%|████▊     | 24/50 [03:54<01:52,  4.33s/it]

[I 2025-12-02 17:42:19,551] Trial 23 pruned.

Best trial: 10. Best value: 0.598499:  50%|█████     | 25/50 [03:58<01:46,  4.28s/it]

[I 2025-12-02 17:42:23,706] Trial 26 pruned.

Best trial: 10. Best value: 0.598499:  52%|█████▏    | 26/50 [04:02<01:41,  4.21s/it]

[I 2025-12-02 17:42:27,753] Trial 25 pruned.

Best trial: 10. Best value: 0.598499:  54%|█████▍    | 27/50 [04:07<01:38,  4.29s/it]

[I 2025-12-02 17:42:32,235] Trial 24 pruned.

Best trial: 27. Best value: 0.622889:  56%|█████▌    | 28/50 [04:24<02:58,  8.13s/it]

[I 2025-12-02 17:42:49,310] Trial 27 finished with value: 0.6228893058161351 and parameters: {'max_depth': 6, 'learning_rate': 0.15256872294423335, 'n_estimators': 447, 'subsample': 0.7454695804131171, 'colsample_bytree': 0.5986919162638256, 'min_child_weight': 5, 'gamma': 2.9413147437504024, 'reg_alpha': 1.136648297012022e-06, 'reg_lambda': 0.0006785525922606906, 'max_delta_step': 7}. Best is trial 27 with value: 0.6228893058161351.

Best trial: 27. Best value: 0.622889:  58%|█████▊    | 29/50 [04:29<02:29,  7.12s/it]

[I 2025-12-02 17:42:54,072] Trial 31 pruned.

Best trial: 27. Best value: 0.622889:  62%|██████▏   | 31/50 [04:45<02:11,  6.93s/it]

[I 2025-12-02 17:43:10,247] Trial 29 finished with value: 0.6036585365853658 and parameters: {'max_depth': 6, 'learning_rate': 0.13603243231019183, 'n_estimators': 708, 'subsample': 0.8287844711671892, 'colsample_bytree': 0.6118948890381632, 'min_child_weight': 6, 'gamma': 4.4252155474305646, 'reg_alpha': 5.11180790060854e-07, 'reg_lambda': 0.18262884984220012, 'max_delta_step': 9}. Best is trial 27 with value: 0.6228893058161351.
[I 2025-12-02 17:43:10,397] Trial 28 finished with value: 0.5914634146341464 and parameters: {'max_depth': 6, 'learning_rate': 0.14313827481005809, 'n_estimators': 740, 'subsample': 0.8064856353220947, 'colsample_bytree': 0.5984721184251933, 'min_child_weight': 5, 'gamma': 4.4371336793000955, 'reg_alpha': 2.5139425425070344e-07, 'reg_lambda': 0.21902819184105715, 'max_delta_step': 9}. Best is trial 27 with value: 0.6228893058161351.

Best trial: 27. Best value: 0.622889:  64%|██████▍   | 32/50 [04:50<01:57,  6.51s/it]

[I 2025-12-02 17:43:15,938] Trial 30 finished with value: 0.6177298311444652 and parameters: {'max_depth': 6, 'learning_rate': 0.15279824038159437, 'n_estimators': 727, 'subsample': 0.8142264002524489, 'colsample_bytree': 0.6747228843720887, 'min_child_weight': 6, 'gamma': 4.428733622785151, 'reg_alpha': 3.9631620104646333e-07, 'reg_lambda': 0.2731894803656216, 'max_delta_step': 9}. Best is trial 27 with value: 0.6228893058161351.

Best trial: 27. Best value: 0.622889:  66%|██████▌   | 33/50 [04:59<02:01,  7.17s/it]

[I 2025-12-02 17:43:24,645] Trial 35 pruned.

Best trial: 27. Best value: 0.622889:  68%|██████▊   | 34/50 [05:11<02:15,  8.49s/it]

[I 2025-12-02 17:43:36,203] Trial 36 pruned.

Best trial: 27. Best value: 0.622889:  70%|███████   | 35/50 [05:17<01:58,  7.89s/it]

[I 2025-12-02 17:43:42,685] Trial 37 pruned.

Best trial: 27. Best value: 0.622889:  72%|███████▏  | 36/50 [05:24<01:46,  7.62s/it]

[I 2025-12-02 17:43:49,691] Trial 34 finished with value: 0.6228893058161351 and parameters: {'max_depth': 7, 'learning_rate': 0.11246255541885254, 'n_estimators': 669, 'subsample': 0.83269051068704, 'colsample_bytree': 0.5441566139631836, 'min_child_weight': 6, 'gamma': 3.5773602891592793, 'reg_alpha': 5.7882139159125723e-08, 'reg_lambda': 1.5425506764009194, 'max_delta_step': 9}. Best is trial 27 with value: 0.6228893058161351.

Best trial: 27. Best value: 0.622889:  74%|███████▍  | 37/50 [05:38<02:04,  9.54s/it]

[I 2025-12-02 17:44:03,713] Trial 38 pruned.

Best trial: 27. Best value: 0.622889:  76%|███████▌  | 38/50 [05:40<01:25,  7.09s/it]

[I 2025-12-02 17:44:05,067] Trial 39 pruned.

Best trial: 27. Best value: 0.622889:  78%|███████▊  | 39/50 [05:54<01:41,  9.21s/it]

[I 2025-12-02 17:44:19,248] Trial 40 pruned.

Best trial: 27. Best value: 0.622889:  80%|████████  | 40/50 [05:54<01:06,  6.68s/it]

[I 2025-12-02 17:44:20,013] Trial 41 pruned.

Best trial: 27. Best value: 0.622889:  82%|████████▏ | 41/50 [05:58<00:52,  5.81s/it]

[I 2025-12-02 17:44:23,805] Trial 32 finished with value: 0.5773921200750469 and parameters: {'max_depth': 8, 'learning_rate': 0.12350500507295603, 'n_estimators': 1290, 'subsample': 0.8421379279693637, 'colsample_bytree': 0.538081623847269, 'min_child_weight': 2, 'gamma': 3.486028641237599, 'reg_alpha': 1.1362094560454329e-07, 'reg_lambda': 3.474818154382766e-05, 'max_delta_step': 9}. Best is trial 27 with value: 0.6228893058161351.

Best trial: 33. Best value: 0.628049:  84%|████████▍ | 42/50 [05:59<00:33,  4.24s/it]

[I 2025-12-02 17:44:24,368] Trial 33 finished with value: 0.6280487804878049 and parameters: {'max_depth': 8, 'learning_rate': 0.1081604264345988, 'n_estimators': 1261, 'subsample': 0.8349536194405578, 'colsample_bytree': 0.5539271248423729, 'min_child_weight': 2, 'gamma': 0.6495835181936211, 'reg_alpha': 6.65103232486521e-08, 'reg_lambda': 3.3300890226056645e-05, 'max_delta_step': 9}. Best is trial 33 with value: 0.6280487804878049.

Best trial: 33. Best value: 0.628049:  86%|████████▌ | 43/50 [06:05<00:33,  4.80s/it]

[I 2025-12-02 17:44:30,472] Trial 44 pruned.

Best trial: 33. Best value: 0.628049:  88%|████████▊ | 44/50 [06:07<00:23,  3.96s/it]

[I 2025-12-02 17:44:32,475] Trial 45 pruned.

Best trial: 33. Best value: 0.628049:  90%|█████████ | 45/50 [06:12<00:20,  4.16s/it]

[I 2025-12-02 17:44:37,090] Trial 46 pruned.

Best trial: 33. Best value: 0.628049:  92%|█████████▏| 46/50 [06:13<00:13,  3.28s/it]

[I 2025-12-02 17:44:38,312] Trial 43 pruned.

Best trial: 33. Best value: 0.628049:  94%|█████████▍| 47/50 [06:14<00:08,  2.76s/it]

[I 2025-12-02 17:44:39,870] Trial 47 pruned.

Best trial: 33. Best value: 0.628049:  96%|█████████▌| 48/50 [06:17<00:05,  2.81s/it]

[I 2025-12-02 17:44:42,792] Trial 48 pruned.

Best trial: 33. Best value: 0.628049:  98%|█████████▊| 49/50 [06:20<00:02,  2.79s/it]

[I 2025-12-02 17:44:45,541] Trial 49 pruned.

Best trial: 42. Best value: 0.629925: 100%|██████████| 50/50 [06:21<00:00,  7.64s/it]

[I 2025-12-02 17:44:46,850] Trial 42 finished with value: 0.6299249530956847 and parameters: {'max_depth': 7, 'learning_rate': 0.2286556388220608, 'n_estimators': 475, 'subsample': 0.7618079232836794, 'colsample_bytree': 0.6257221586788932, 'min_child_weight': 5, 'gamma': 4.132241463605353, 'reg_alpha': 4.2631822345282957e-07, 'reg_lambda': 0.011124891620501155, 'max_delta_step': 7}. Best is trial 42 with value: 0.6299249530956847.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.629925                0.657143      0.685714

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0   0.30989          0.714286               0.6        50          67

   test_size
0         17
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.629925                0.657143      0.685714

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0   0.30989          0.714286               0.6        50          67

   test_size
0         17

In [ ]:
# Combined embedings
datasets = task_comb_dfs_lbd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_lbd_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_comb_lbd_hc_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param="emb_",
)
print(summary)

[I 2025-12-02 17:44:51,173] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 67, Test size: 17
Using Leave-One-Out CV with 67 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.0121951:   2%|▏         | 1/50 [00:40<32:47, 40.15s/it]

[I 2025-12-02 17:45:31,315] Trial 2 finished with value: 0.012195121951219513 and parameters: {'max_depth': 8, 'learning_rate': 0.0107915032282912, 'n_estimators': 295, 'subsample': 0.9126630303044003, 'colsample_bytree': 0.6067486140417554, 'min_child_weight': 3, 'gamma': 4.7346341784519534, 'reg_alpha': 7.314666747625201, 'reg_lambda': 2.296380524797102e-06, 'max_delta_step': 7}. Best is trial 2 with value: 0.012195121951219513.

Best trial: 1. Best value: 0.509381:   4%|▍         | 2/50 [01:24<34:06, 42.64s/it]

[I 2025-12-02 17:46:15,707] Trial 1 finished with value: 0.5093808630393997 and parameters: {'max_depth': 4, 'learning_rate': 0.0498935676619666, 'n_estimators': 914, 'subsample': 0.6490164689044804, 'colsample_bytree': 0.563904047951526, 'min_child_weight': 6, 'gamma': 0.6153789323182746, 'reg_alpha': 8.473998595935903e-05, 'reg_lambda': 5.296713658046761e-05, 'max_delta_step': 1}. Best is trial 1 with value: 0.5093808630393997.

Best trial: 1. Best value: 0.509381:   6%|▌         | 3/50 [01:43<24:54, 31.79s/it]

[I 2025-12-02 17:46:34,568] Trial 0 finished with value: 0.43949343339587243 and parameters: {'max_depth': 8, 'learning_rate': 0.26464631920694803, 'n_estimators': 864, 'subsample': 0.5840664816931322, 'colsample_bytree': 0.8077884784666398, 'min_child_weight': 2, 'gamma': 4.726899749625423, 'reg_alpha': 6.210533953799522e-06, 'reg_lambda': 0.19624278926280964, 'max_delta_step': 10}. Best is trial 1 with value: 0.5093808630393997.

Best trial: 3. Best value: 0.516417:   8%|▊         | 4/50 [02:06<21:52, 28.53s/it]

[I 2025-12-02 17:46:58,118] Trial 3 finished with value: 0.5164165103189493 and parameters: {'max_depth': 6, 'learning_rate': 0.08543002596580634, 'n_estimators': 1339, 'subsample': 0.8635559286508473, 'colsample_bytree': 0.8058499541907704, 'min_child_weight': 6, 'gamma': 0.9110831058761182, 'reg_alpha': 2.246358679115313e-08, 'reg_lambda': 0.6099860049984509, 'max_delta_step': 1}. Best is trial 3 with value: 0.5164165103189493.

Best trial: 3. Best value: 0.516417:  10%|█         | 5/50 [03:17<32:45, 43.67s/it]

[I 2025-12-02 17:48:08,627] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.01989160216760492, 'n_estimators': 1254, 'subsample': 0.8329746104703275, 'colsample_bytree': 0.9175918290145629, 'min_child_weight': 10, 'gamma': 0.4106934237652371, 'reg_alpha': 0.0021291995614742894, 'reg_lambda': 6.900518092715772e-06, 'max_delta_step': 9}. Best is trial 3 with value: 0.5164165103189493.

Best trial: 3. Best value: 0.516417:  12%|█▏        | 6/50 [03:20<21:48, 29.73s/it]

[I 2025-12-02 17:48:11,298] Trial 4 finished with value: 0.5023452157598499 and parameters: {'max_depth': 8, 'learning_rate': 0.016107914143593277, 'n_estimators': 934, 'subsample': 0.9015457137174627, 'colsample_bytree': 0.7623329389315978, 'min_child_weight': 3, 'gamma': 4.740940795695633, 'reg_alpha': 0.005462848093591408, 'reg_lambda': 1.4970730523932892e-07, 'max_delta_step': 6}. Best is trial 3 with value: 0.5164165103189493.

Best trial: 3. Best value: 0.516417:  14%|█▍        | 7/50 [03:45<20:15, 28.27s/it]

[I 2025-12-02 17:48:36,554] Trial 6 finished with value: 0.4901500938086304 and parameters: {'max_depth': 3, 'learning_rate': 0.02223288917312726, 'n_estimators': 668, 'subsample': 0.9138517005183157, 'colsample_bytree': 0.8417477787937837, 'min_child_weight': 5, 'gamma': 1.320954622047657, 'reg_alpha': 2.7975946909365957e-08, 'reg_lambda': 0.09280246547480067, 'max_delta_step': 0}. Best is trial 3 with value: 0.5164165103189493.

Best trial: 3. Best value: 0.516417:  16%|█▌        | 8/50 [03:45<13:34, 19.38s/it]

[I 2025-12-02 17:48:36,906] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.035914878216226666, 'n_estimators': 206, 'subsample': 0.686248168932007, 'colsample_bytree': 0.6069984274571261, 'min_child_weight': 4, 'gamma': 2.2951675954595525, 'reg_alpha': 8.855202713076498, 'reg_lambda': 5.663069227505312, 'max_delta_step': 6}. Best is trial 3 with value: 0.5164165103189493.

Best trial: 3. Best value: 0.516417:  18%|█▊        | 9/50 [04:24<17:27, 25.54s/it]

[I 2025-12-02 17:49:16,012] Trial 7 finished with value: 0.5164165103189493 and parameters: {'max_depth': 7, 'learning_rate': 0.01111147262157244, 'n_estimators': 479, 'subsample': 0.7362187066420571, 'colsample_bytree': 0.5849011868166893, 'min_child_weight': 1, 'gamma': 3.9691015812787924, 'reg_alpha': 0.00011087420134952529, 'reg_lambda': 1.9220869575069757e-06, 'max_delta_step': 3}. Best is trial 3 with value: 0.5164165103189493.

Best trial: 10. Best value: 0.535647:  20%|██        | 10/50 [04:33<13:39, 20.48s/it]

[I 2025-12-02 17:49:25,155] Trial 10 finished with value: 0.5356472795497186 and parameters: {'max_depth': 10, 'learning_rate': 0.02655795725347195, 'n_estimators': 459, 'subsample': 0.78425801255403, 'colsample_bytree': 0.6626345384277477, 'min_child_weight': 8, 'gamma': 4.050942600577133, 'reg_alpha': 1.3804621168656972e-08, 'reg_lambda': 6.805495423777622e-08, 'max_delta_step': 2}. Best is trial 10 with value: 0.5356472795497186.

Best trial: 10. Best value: 0.535647:  22%|██▏       | 11/50 [05:09<16:19, 25.13s/it]

[I 2025-12-02 17:50:00,810] Trial 11 finished with value: 0.5145403377110694 and parameters: {'max_depth': 5, 'learning_rate': 0.13518407993564782, 'n_estimators': 929, 'subsample': 0.5067882031742745, 'colsample_bytree': 0.5937154634643085, 'min_child_weight': 3, 'gamma': 1.7260411605394677, 'reg_alpha': 3.623407015292386e-07, 'reg_lambda': 0.9589083809849774, 'max_delta_step': 4}. Best is trial 10 with value: 0.5356472795497186.

Best trial: 10. Best value: 0.535647:  24%|██▍       | 12/50 [05:23<13:42, 21.65s/it]

[I 2025-12-02 17:50:14,523] Trial 13 finished with value: 0.5304878048780488 and parameters: {'max_depth': 10, 'learning_rate': 0.11685519099094767, 'n_estimators': 543, 'subsample': 0.9954957363468077, 'colsample_bytree': 0.6833592239484015, 'min_child_weight': 9, 'gamma': 3.3768792655777746, 'reg_alpha': 7.369965548003233e-07, 'reg_lambda': 1.4795725774744001e-08, 'max_delta_step': 3}. Best is trial 10 with value: 0.5356472795497186.

Best trial: 10. Best value: 0.535647:  26%|██▌       | 13/50 [05:25<09:45, 15.83s/it]

[I 2025-12-02 17:50:16,968] Trial 12 finished with value: 0.5093808630393997 and parameters: {'max_depth': 10, 'learning_rate': 0.028023081545397843, 'n_estimators': 531, 'subsample': 0.9774223183869013, 'colsample_bytree': 0.9242626817643826, 'min_child_weight': 9, 'gamma': 3.614865149175712, 'reg_alpha': 2.1026820503418282e-05, 'reg_lambda': 1.2146097385833672, 'max_delta_step': 7}. Best is trial 10 with value: 0.5356472795497186.

Best trial: 10. Best value: 0.535647:  28%|██▊       | 14/50 [06:10<14:48, 24.67s/it]

[I 2025-12-02 17:51:02,048] Trial 15 finished with value: 0.5234521575984991 and parameters: {'max_depth': 10, 'learning_rate': 0.11262780050965773, 'n_estimators': 538, 'subsample': 0.9980058418405565, 'colsample_bytree': 0.6862026874824222, 'min_child_weight': 9, 'gamma': 3.5242170191991247, 'reg_alpha': 9.885445430959903e-07, 'reg_lambda': 2.5751092115636617e-08, 'max_delta_step': 3}. Best is trial 10 with value: 0.5356472795497186.

Best trial: 10. Best value: 0.535647:  30%|███       | 15/50 [06:20<11:41, 20.05s/it]

[I 2025-12-02 17:51:11,383] Trial 14 pruned.

Best trial: 16. Best value: 0.547842:  32%|███▏      | 16/50 [06:20<08:01, 14.17s/it]

[I 2025-12-02 17:51:11,894] Trial 16 finished with value: 0.5478424015009381 and parameters: {'max_depth': 10, 'learning_rate': 0.08515444725986118, 'n_estimators': 637, 'subsample': 0.7956235356864265, 'colsample_bytree': 0.688216384921255, 'min_child_weight': 8, 'gamma': 3.1490117082556486, 'reg_alpha': 6.03884301391056e-07, 'reg_lambda': 2.2773525028530756e-08, 'max_delta_step': 3}. Best is trial 16 with value: 0.5478424015009381.

Best trial: 16. Best value: 0.547842:  34%|███▍      | 17/50 [06:43<09:07, 16.61s/it]

[I 2025-12-02 17:51:34,175] Trial 18 pruned.

Best trial: 16. Best value: 0.547842:  36%|███▌      | 18/50 [06:47<06:59, 13.10s/it]

[I 2025-12-02 17:51:39,097] Trial 9 finished with value: 0.5286116322701688 and parameters: {'max_depth': 7, 'learning_rate': 0.018294749894981453, 'n_estimators': 780, 'subsample': 0.7073052874929584, 'colsample_bytree': 0.8947445925856957, 'min_child_weight': 1, 'gamma': 3.301740536119734, 'reg_alpha': 0.4392697543759445, 'reg_lambda': 1.0790973405146936e-08, 'max_delta_step': 1}. Best is trial 16 with value: 0.5478424015009381.

Best trial: 16. Best value: 0.547842:  38%|███▊      | 19/50 [06:48<04:52,  9.44s/it]

[I 2025-12-02 17:51:40,010] Trial 20 pruned.

Best trial: 16. Best value: 0.547842:  40%|████      | 20/50 [06:54<04:12,  8.41s/it]

[I 2025-12-02 17:51:46,030] Trial 22 pruned.

Best trial: 16. Best value: 0.547842:  42%|████▏     | 21/50 [07:08<04:53, 10.11s/it]

[I 2025-12-02 17:52:00,101] Trial 23 pruned.

Best trial: 16. Best value: 0.547842:  44%|████▍     | 22/50 [07:09<03:26,  7.37s/it]

[I 2025-12-02 17:52:01,094] Trial 17 finished with value: 0.5478424015009381 and parameters: {'max_depth': 10, 'learning_rate': 0.22828384755230044, 'n_estimators': 712, 'subsample': 0.7947673129500749, 'colsample_bytree': 0.6980106982018619, 'min_child_weight': 8, 'gamma': 2.8382807400672143, 'reg_alpha': 1.9276479301270638e-07, 'reg_lambda': 0.0026819425161831033, 'max_delta_step': 2}. Best is trial 16 with value: 0.5478424015009381.

Best trial: 16. Best value: 0.547842:  46%|████▌     | 23/50 [07:23<04:12,  9.37s/it]

[I 2025-12-02 17:52:15,109] Trial 19 finished with value: 0.5337711069418387 and parameters: {'max_depth': 9, 'learning_rate': 0.057350210432773455, 'n_estimators': 727, 'subsample': 0.7635069116645031, 'colsample_bytree': 0.5230898649663233, 'min_child_weight': 7, 'gamma': 2.4705139929343516, 'reg_alpha': 1.9158972632419095e-07, 'reg_lambda': 0.0011848133484743948, 'max_delta_step': 5}. Best is trial 16 with value: 0.5478424015009381.

Best trial: 16. Best value: 0.547842:  48%|████▊     | 24/50 [07:30<03:41,  8.50s/it]

[I 2025-12-02 17:52:21,602] Trial 21 finished with value: 0.5234521575984991 and parameters: {'max_depth': 9, 'learning_rate': 0.06331462871802071, 'n_estimators': 400, 'subsample': 0.785936220994931, 'colsample_bytree': 0.7137500930985677, 'min_child_weight': 7, 'gamma': 2.4773202308164, 'reg_alpha': 1.1989054888030136e-07, 'reg_lambda': 3.574646310025649e-07, 'max_delta_step': 5}. Best is trial 16 with value: 0.5478424015009381.

Best trial: 16. Best value: 0.547842:  50%|█████     | 25/50 [07:41<03:53,  9.33s/it]

[I 2025-12-02 17:52:32,862] Trial 24 pruned.

Best trial: 25. Best value: 0.554878:  52%|█████▏    | 26/50 [08:08<05:50, 14.62s/it]

[I 2025-12-02 17:52:59,813] Trial 25 finished with value: 0.5548780487804879 and parameters: {'max_depth': 10, 'learning_rate': 0.17298557089996897, 'n_estimators': 711, 'subsample': 0.7990049210900687, 'colsample_bytree': 0.6411146587594779, 'min_child_weight': 7, 'gamma': 2.8175842348912865, 'reg_alpha': 4.242250630276174e-06, 'reg_lambda': 5.58221613429907e-05, 'max_delta_step': 2}. Best is trial 25 with value: 0.5548780487804879.

Best trial: 25. Best value: 0.554878:  54%|█████▍    | 27/50 [08:17<04:56, 12.87s/it]

[I 2025-12-02 17:53:08,611] Trial 26 finished with value: 0.5356472795497186 and parameters: {'max_depth': 10, 'learning_rate': 0.17979406125283057, 'n_estimators': 638, 'subsample': 0.8278647786341515, 'colsample_bytree': 0.6465743218706118, 'min_child_weight': 8, 'gamma': 2.970868289073285, 'reg_alpha': 5.628474086233383e-06, 'reg_lambda': 5.315430496895167e-05, 'max_delta_step': 2}. Best is trial 25 with value: 0.5548780487804879.

Best trial: 25. Best value: 0.554878:  56%|█████▌    | 28/50 [08:22<03:52, 10.57s/it]

[I 2025-12-02 17:53:13,800] Trial 29 pruned.

Best trial: 25. Best value: 0.554878:  58%|█████▊    | 29/50 [08:33<03:43, 10.63s/it]

[I 2025-12-02 17:53:24,572] Trial 31 pruned.

Best trial: 25. Best value: 0.554878:  60%|██████    | 30/50 [08:43<03:31, 10.59s/it]

[I 2025-12-02 17:53:35,092] Trial 28 pruned.

Best trial: 25. Best value: 0.554878:  62%|██████▏   | 31/50 [08:54<03:20, 10.55s/it]

[I 2025-12-02 17:53:45,524] Trial 33 pruned.

Best trial: 25. Best value: 0.554878:  64%|██████▍   | 32/50 [08:55<02:21,  7.84s/it]

[I 2025-12-02 17:53:47,038] Trial 27 finished with value: 0.5023452157598499 and parameters: {'max_depth': 10, 'learning_rate': 0.15779928769269067, 'n_estimators': 1065, 'subsample': 0.8622555865691867, 'colsample_bytree': 0.6474210272774786, 'min_child_weight': 8, 'gamma': 3.0087279490695833, 'reg_alpha': 3.693521057729966e-06, 'reg_lambda': 1.363625221827936e-05, 'max_delta_step': 2}. Best is trial 25 with value: 0.5548780487804879.

Best trial: 25. Best value: 0.554878:  66%|██████▌   | 33/50 [09:05<02:21,  8.33s/it]

[I 2025-12-02 17:53:56,521] Trial 32 pruned.

Best trial: 25. Best value: 0.554878:  68%|██████▊   | 34/50 [09:24<03:07, 11.70s/it]

[I 2025-12-02 17:54:16,097] Trial 36 pruned.

Best trial: 25. Best value: 0.554878:  70%|███████   | 35/50 [09:45<03:36, 14.41s/it]

[I 2025-12-02 17:54:36,828] Trial 34 finished with value: 0.49718574108818014 and parameters: {'max_depth': 10, 'learning_rate': 0.22643793126671943, 'n_estimators': 593, 'subsample': 0.7902355227369696, 'colsample_bytree': 0.5551661469827887, 'min_child_weight': 8, 'gamma': 3.819315057493292, 'reg_alpha': 5.970350411203131e-08, 'reg_lambda': 4.933528888588048e-08, 'max_delta_step': 2}. Best is trial 25 with value: 0.5548780487804879.

Best trial: 25. Best value: 0.554878:  72%|███████▏  | 36/50 [09:49<02:37, 11.23s/it]

[I 2025-12-02 17:54:40,642] Trial 35 finished with value: 0.5478424015009381 and parameters: {'max_depth': 10, 'learning_rate': 0.22313069771282248, 'n_estimators': 592, 'subsample': 0.6799279810983164, 'colsample_bytree': 0.7742632878749257, 'min_child_weight': 7, 'gamma': 3.8340373531037333, 'reg_alpha': 4.57032073545285e-08, 'reg_lambda': 5.4129001828049395e-08, 'max_delta_step': 1}. Best is trial 25 with value: 0.5548780487804879.

Best trial: 25. Best value: 0.554878:  74%|███████▍  | 37/50 [09:49<01:43,  7.97s/it]

[I 2025-12-02 17:54:41,003] Trial 30 finished with value: 0.5215759849906192 and parameters: {'max_depth': 8, 'learning_rate': 0.266667549584367, 'n_estimators': 1067, 'subsample': 0.6996235403162301, 'colsample_bytree': 0.7810282840266831, 'min_child_weight': 6, 'gamma': 2.018628530251198, 'reg_alpha': 2.291398792566737e-06, 'reg_lambda': 0.013950737065261636, 'max_delta_step': 4}. Best is trial 25 with value: 0.5548780487804879.

Best trial: 25. Best value: 0.554878:  76%|███████▌  | 38/50 [09:54<01:22,  6.85s/it]

[I 2025-12-02 17:54:45,251] Trial 37 pruned.

Best trial: 25. Best value: 0.554878:  78%|███████▊  | 39/50 [10:03<01:24,  7.66s/it]

[I 2025-12-02 17:54:54,802] Trial 41 pruned.

Best trial: 25. Best value: 0.554878:  80%|████████  | 40/50 [10:18<01:38,  9.84s/it]

[I 2025-12-02 17:55:09,709] Trial 38 pruned.

Best trial: 25. Best value: 0.554878:  82%|████████▏ | 41/50 [10:18<01:02,  6.95s/it]

[I 2025-12-02 17:55:09,908] Trial 39 pruned.
[I 2025-12-02 17:55:09,926] Trial 40 pruned.

Best trial: 25. Best value: 0.554878:  86%|████████▌ | 43/50 [10:32<00:48,  6.87s/it]

[I 2025-12-02 17:55:23,493] Trial 42 pruned.

Best trial: 25. Best value: 0.554878:  88%|████████▊ | 44/50 [10:40<00:43,  7.24s/it]

[I 2025-12-02 17:55:31,832] Trial 46 pruned.

Best trial: 25. Best value: 0.554878:  90%|█████████ | 45/50 [11:05<00:59, 11.89s/it]

[I 2025-12-02 17:55:56,847] Trial 43 pruned.

Best trial: 25. Best value: 0.554878:  92%|█████████▏| 46/50 [11:06<00:35,  8.84s/it]

[I 2025-12-02 17:55:57,548] Trial 44 finished with value: 0.5286116322701688 and parameters: {'max_depth': 10, 'learning_rate': 0.13702476003260836, 'n_estimators': 452, 'subsample': 0.8898463316228146, 'colsample_bytree': 0.62497981236368, 'min_child_weight': 7, 'gamma': 2.650370952581374, 'reg_alpha': 3.895921330847847e-07, 'reg_lambda': 6.342130516468551e-08, 'max_delta_step': 1}. Best is trial 25 with value: 0.5548780487804879.

Best trial: 25. Best value: 0.554878:  94%|█████████▍| 47/50 [11:06<00:19,  6.51s/it]

[I 2025-12-02 17:55:58,068] Trial 47 finished with value: 0.40290806754221387 and parameters: {'max_depth': 10, 'learning_rate': 0.12597704873578033, 'n_estimators': 228, 'subsample': 0.556404651752848, 'colsample_bytree': 0.6031955867845965, 'min_child_weight': 7, 'gamma': 3.9304972470280357, 'reg_alpha': 3.301151214074237e-08, 'reg_lambda': 0.0004832271965248883, 'max_delta_step': 3}. Best is trial 25 with value: 0.5548780487804879.

Best trial: 25. Best value: 0.554878:  98%|█████████▊| 49/50 [11:08<00:03,  3.71s/it]

[I 2025-12-02 17:55:59,940] Trial 48 pruned.
[I 2025-12-02 17:56:00,045] Trial 45 pruned.

Best trial: 25. Best value: 0.554878: 100%|██████████| 50/50 [11:09<00:00, 13.39s/it]

[I 2025-12-02 17:56:00,425] Trial 49 pruned.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.554878                0.292857           0.2

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.408491          0.285714               0.3        50          67

   test_size
0         17
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.554878                0.292857           0.2

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.408491          0.285714               0.3        50          67

   test_size
0         17

In [ ]:

datasets = task_hf_dfs_clean_lbd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_lbd_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_handcrafted_lbd_hc_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param="w.cz.fnusa",
)
print(summary)

[I 2025-12-02 17:56:04,905] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 67, Test size: 17
Using Leave-One-Out CV with 67 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.579268:   2%|▏         | 1/50 [00:36<29:33, 36.20s/it]

[I 2025-12-02 17:56:41,097] Trial 2 finished with value: 0.5792682926829269 and parameters: {'max_depth': 7, 'learning_rate': 0.030379471171701332, 'n_estimators': 583, 'subsample': 0.6429680779904716, 'colsample_bytree': 0.621556480320094, 'min_child_weight': 2, 'gamma': 4.760245583661868, 'reg_alpha': 0.006076572723528809, 'reg_lambda': 0.23150499589770024, 'max_delta_step': 1}. Best is trial 2 with value: 0.5792682926829269.

Best trial: 1. Best value: 0.615854:   4%|▍         | 2/50 [00:41<14:14, 17.80s/it]

[I 2025-12-02 17:56:46,005] Trial 1 finished with value: 0.6158536585365854 and parameters: {'max_depth': 8, 'learning_rate': 0.013503037129398777, 'n_estimators': 579, 'subsample': 0.7019362484777095, 'colsample_bytree': 0.9259866344508898, 'min_child_weight': 3, 'gamma': 0.36685230644252553, 'reg_alpha': 0.00017768926370150082, 'reg_lambda': 4.1977983731790307e-07, 'max_delta_step': 5}. Best is trial 1 with value: 0.6158536585365854.

Best trial: 1. Best value: 0.615854:   6%|▌         | 3/50 [00:41<07:52, 10.06s/it]

[I 2025-12-02 17:56:46,864] Trial 0 finished with value: 0.3067542213883677 and parameters: {'max_depth': 6, 'learning_rate': 0.011481293877766587, 'n_estimators': 754, 'subsample': 0.8078799170235462, 'colsample_bytree': 0.9398684337615746, 'min_child_weight': 9, 'gamma': 4.97976559161336, 'reg_alpha': 0.005825409251834241, 'reg_lambda': 5.4027178540948295, 'max_delta_step': 6}. Best is trial 1 with value: 0.6158536585365854.

Best trial: 1. Best value: 0.615854:  10%|█         | 5/50 [01:05<07:26,  9.93s/it]

[I 2025-12-02 17:57:10,588] Trial 3 finished with value: 0.5426829268292683 and parameters: {'max_depth': 3, 'learning_rate': 0.02568642275862967, 'n_estimators': 1043, 'subsample': 0.9493440589946742, 'colsample_bytree': 0.7166390503558833, 'min_child_weight': 7, 'gamma': 0.048311010279021294, 'reg_alpha': 3.6733525741963358, 'reg_lambda': 3.7807623085452696e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.6158536585365854.
[I 2025-12-02 17:57:10,725] Trial 4 finished with value: 0.47983114446529085 and parameters: {'max_depth': 10, 'learning_rate': 0.10136413758017386, 'n_estimators': 475, 'subsample': 0.9720595712258717, 'colsample_bytree': 0.8661877931773351, 'min_child_weight': 8, 'gamma': 4.155941527895085, 'reg_alpha': 0.68711831573251, 'reg_lambda': 6.4613166111823345e-06, 'max_delta_step': 2}. Best is trial 1 with value: 0.6158536585365854.

Best trial: 1. Best value: 0.615854:  12%|█▏        | 6/50 [01:17<07:48, 10.64s/it]

[I 2025-12-02 17:57:22,750] Trial 6 finished with value: 0.024390243902439025 and parameters: {'max_depth': 9, 'learning_rate': 0.03152589552080839, 'n_estimators': 600, 'subsample': 0.7285803887942777, 'colsample_bytree': 0.5863027267899567, 'min_child_weight': 10, 'gamma': 1.61020775514314, 'reg_alpha': 3.1033780069510683e-06, 'reg_lambda': 4.343812983169896e-06, 'max_delta_step': 10}. Best is trial 1 with value: 0.6158536585365854.

Best trial: 1. Best value: 0.615854:  14%|█▍        | 7/50 [01:43<11:07, 15.53s/it]

[I 2025-12-02 17:57:48,356] Trial 5 finished with value: 0.5164165103189493 and parameters: {'max_depth': 3, 'learning_rate': 0.022933445794701253, 'n_estimators': 1026, 'subsample': 0.6984744809669683, 'colsample_bytree': 0.7068205111794971, 'min_child_weight': 8, 'gamma': 0.016444266835131116, 'reg_alpha': 0.0849639546154771, 'reg_lambda': 4.033693400833407e-05, 'max_delta_step': 10}. Best is trial 1 with value: 0.6158536585365854.

Best trial: 1. Best value: 0.615854:  16%|█▌        | 8/50 [01:49<08:47, 12.57s/it]

[I 2025-12-02 17:57:54,570] Trial 8 finished with value: 0.37288930581613505 and parameters: {'max_depth': 6, 'learning_rate': 0.29006810288385676, 'n_estimators': 705, 'subsample': 0.9016981390379815, 'colsample_bytree': 0.8890105468680052, 'min_child_weight': 10, 'gamma': 1.5805337349301012, 'reg_alpha': 0.12925186300729138, 'reg_lambda': 3.0467050653467094e-07, 'max_delta_step': 1}. Best is trial 1 with value: 0.6158536585365854.

Best trial: 1. Best value: 0.615854:  18%|█▊        | 9/50 [01:59<07:58, 11.68s/it]

[I 2025-12-02 17:58:04,302] Trial 7 finished with value: 0.5286116322701688 and parameters: {'max_depth': 8, 'learning_rate': 0.012634594798904825, 'n_estimators': 851, 'subsample': 0.7512415757231391, 'colsample_bytree': 0.8745433464749512, 'min_child_weight': 8, 'gamma': 1.229218671092902, 'reg_alpha': 3.007724059020073e-07, 'reg_lambda': 5.069863668428076e-07, 'max_delta_step': 5}. Best is trial 1 with value: 0.6158536585365854.

Best trial: 1. Best value: 0.615854:  20%|██        | 10/50 [02:15<08:45, 13.13s/it]

[I 2025-12-02 17:58:20,667] Trial 9 finished with value: 0.36585365853658536 and parameters: {'max_depth': 7, 'learning_rate': 0.07709195049012645, 'n_estimators': 959, 'subsample': 0.5725154444964907, 'colsample_bytree': 0.6502723880452221, 'min_child_weight': 9, 'gamma': 4.241816904194211, 'reg_alpha': 1.1314794376869128e-05, 'reg_lambda': 5.515196437867603, 'max_delta_step': 5}. Best is trial 1 with value: 0.6158536585365854.

Best trial: 1. Best value: 0.615854:  22%|██▏       | 11/50 [02:16<05:59,  9.22s/it]

[I 2025-12-02 17:58:21,023] Trial 11 pruned.

Best trial: 1. Best value: 0.615854:  24%|██▍       | 12/50 [02:18<04:34,  7.22s/it]

[I 2025-12-02 17:58:23,678] Trial 12 pruned.

Best trial: 1. Best value: 0.615854:  26%|██▌       | 13/50 [02:22<03:47,  6.16s/it]

[I 2025-12-02 17:58:27,393] Trial 10 finished with value: 0.5042213883677298 and parameters: {'max_depth': 7, 'learning_rate': 0.04054587241498827, 'n_estimators': 621, 'subsample': 0.8634245457627227, 'colsample_bytree': 0.7047387266756049, 'min_child_weight': 9, 'gamma': 1.0868820056196098, 'reg_alpha': 0.2574701939903719, 'reg_lambda': 6.117921343674488, 'max_delta_step': 1}. Best is trial 1 with value: 0.6158536585365854.

Best trial: 1. Best value: 0.615854:  28%|██▊       | 14/50 [02:23<02:41,  4.48s/it]

[I 2025-12-02 17:58:28,008] Trial 14 pruned.

Best trial: 1. Best value: 0.615854:  30%|███       | 15/50 [02:27<02:34,  4.40s/it]

[I 2025-12-02 17:58:32,216] Trial 16 pruned.

Best trial: 1. Best value: 0.615854:  32%|███▏      | 16/50 [02:29<02:08,  3.78s/it]

[I 2025-12-02 17:58:34,545] Trial 17 pruned.

Best trial: 1. Best value: 0.615854:  34%|███▍      | 17/50 [02:32<01:50,  3.35s/it]

[I 2025-12-02 17:58:36,904] Trial 13 finished with value: 0.5984990619136961 and parameters: {'max_depth': 5, 'learning_rate': 0.1591344120888065, 'n_estimators': 227, 'subsample': 0.5067742186426577, 'colsample_bytree': 0.9946115233740058, 'min_child_weight': 3, 'gamma': 2.844131072237123, 'reg_alpha': 1.4730268727061872e-08, 'reg_lambda': 1.3176842161008424e-08, 'max_delta_step': 3}. Best is trial 1 with value: 0.6158536585365854.
[I 2025-12-02 17:58:36,915] Trial 18 pruned.

Best trial: 1. Best value: 0.615854:  38%|███▊      | 19/50 [02:36<01:24,  2.73s/it]

[I 2025-12-02 17:58:40,922] Trial 20 pruned.

Best trial: 1. Best value: 0.615854:  40%|████      | 20/50 [02:47<02:23,  4.80s/it]

[I 2025-12-02 17:58:51,984] Trial 15 finished with value: 0.5670731707317074 and parameters: {'max_depth': 7, 'learning_rate': 0.04792758171771319, 'n_estimators': 413, 'subsample': 0.5057952030985968, 'colsample_bytree': 0.7909249118136611, 'min_child_weight': 2, 'gamma': 2.8994345555285874, 'reg_alpha': 0.00035727397935846853, 'reg_lambda': 0.01436047994609145, 'max_delta_step': 0}. Best is trial 1 with value: 0.6158536585365854.

Best trial: 19. Best value: 0.649156:  42%|████▏     | 21/50 [02:57<03:01,  6.25s/it]

[I 2025-12-02 17:59:02,322] Trial 19 finished with value: 0.6491557223264541 and parameters: {'max_depth': 8, 'learning_rate': 0.05475389880689917, 'n_estimators': 418, 'subsample': 0.567380434471358, 'colsample_bytree': 0.7932398198063451, 'min_child_weight': 4, 'gamma': 2.324815456501722, 'reg_alpha': 0.003966047821733259, 'reg_lambda': 1.8568334955505186e-08, 'max_delta_step': 3}. Best is trial 19 with value: 0.6491557223264541.

Best trial: 19. Best value: 0.649156:  44%|████▍     | 22/50 [02:58<02:15,  4.83s/it]

[I 2025-12-02 17:59:03,360] Trial 21 finished with value: 0.5966228893058161 and parameters: {'max_depth': 5, 'learning_rate': 0.15187184872327877, 'n_estimators': 403, 'subsample': 0.5153323239932389, 'colsample_bytree': 0.9946813493299814, 'min_child_weight': 4, 'gamma': 0.7105360670042162, 'reg_alpha': 1.1307997880477663e-08, 'reg_lambda': 1.5189527231672637e-08, 'max_delta_step': 3}. Best is trial 19 with value: 0.6491557223264541.

Best trial: 19. Best value: 0.649156:  46%|████▌     | 23/50 [03:01<01:59,  4.42s/it]

[I 2025-12-02 17:59:06,715] Trial 24 pruned.

Best trial: 19. Best value: 0.649156:  48%|████▊     | 24/50 [03:03<01:35,  3.68s/it]

[I 2025-12-02 17:59:08,541] Trial 25 pruned.

Best trial: 19. Best value: 0.649156:  50%|█████     | 25/50 [03:11<02:03,  4.93s/it]

[I 2025-12-02 17:59:16,547] Trial 26 pruned.

Best trial: 19. Best value: 0.649156:  52%|█████▏    | 26/50 [03:37<04:28, 11.19s/it]

[I 2025-12-02 17:59:42,850] Trial 27 finished with value: 0.5426829268292683 and parameters: {'max_depth': 10, 'learning_rate': 0.1074069730530199, 'n_estimators': 516, 'subsample': 0.772586187316883, 'colsample_bytree': 0.834226303262072, 'min_child_weight': 1, 'gamma': 3.3266037678952403, 'reg_alpha': 2.894064658223961e-07, 'reg_lambda': 3.3426092262725957e-06, 'max_delta_step': 2}. Best is trial 19 with value: 0.6491557223264541.

Best trial: 19. Best value: 0.649156:  54%|█████▍    | 27/50 [03:47<04:07, 10.77s/it]

[I 2025-12-02 17:59:52,629] Trial 22 finished with value: 0.5811444652908067 and parameters: {'max_depth': 5, 'learning_rate': 0.19280005008651657, 'n_estimators': 1204, 'subsample': 0.5770905579394967, 'colsample_bytree': 0.9322153868783255, 'min_child_weight': 4, 'gamma': 0.6851371942051871, 'reg_alpha': 1.7220291234409564e-08, 'reg_lambda': 1.2257582110203586e-08, 'max_delta_step': 4}. Best is trial 19 with value: 0.6491557223264541.

Best trial: 19. Best value: 0.649156:  56%|█████▌    | 28/50 [04:00<04:13, 11.51s/it]

[I 2025-12-02 18:00:05,888] Trial 23 finished with value: 0.6439962476547842 and parameters: {'max_depth': 5, 'learning_rate': 0.19241981595339566, 'n_estimators': 1256, 'subsample': 0.5743846298850434, 'colsample_bytree': 0.9324759634563156, 'min_child_weight': 4, 'gamma': 2.0486342814064047, 'reg_alpha': 1.5128421892435465e-08, 'reg_lambda': 1.0991332362495504e-08, 'max_delta_step': 3}. Best is trial 19 with value: 0.6491557223264541.

Best trial: 19. Best value: 0.649156:  58%|█████▊    | 29/50 [04:01<02:53,  8.28s/it]

[I 2025-12-02 18:00:06,534] Trial 29 pruned.

Best trial: 19. Best value: 0.649156:  60%|██████    | 30/50 [04:03<02:05,  6.28s/it]

[I 2025-12-02 18:00:08,066] Trial 30 pruned.

Best trial: 19. Best value: 0.649156:  62%|██████▏   | 31/50 [04:09<01:59,  6.28s/it]

[I 2025-12-02 18:00:14,406] Trial 32 pruned.

Best trial: 19. Best value: 0.649156:  64%|██████▍   | 32/50 [04:13<01:40,  5.59s/it]

[I 2025-12-02 18:00:18,362] Trial 31 pruned.

Best trial: 19. Best value: 0.649156:  66%|██████▌   | 33/50 [04:14<01:13,  4.30s/it]

[I 2025-12-02 18:00:19,660] Trial 33 pruned.

Best trial: 19. Best value: 0.649156:  68%|██████▊   | 34/50 [04:20<01:16,  4.80s/it]

[I 2025-12-02 18:00:25,613] Trial 35 pruned.

Best trial: 19. Best value: 0.649156:  70%|███████   | 35/50 [04:30<01:32,  6.15s/it]

[I 2025-12-02 18:00:34,914] Trial 28 finished with value: 0.6491557223264541 and parameters: {'max_depth': 6, 'learning_rate': 0.18809863753719855, 'n_estimators': 1238, 'subsample': 0.7711017930053629, 'colsample_bytree': 0.8376978562369164, 'min_child_weight': 1, 'gamma': 3.352214010457044, 'reg_alpha': 3.1168850762655397e-07, 'reg_lambda': 2.8760978104879894e-06, 'max_delta_step': 2}. Best is trial 19 with value: 0.6491557223264541.

Best trial: 19. Best value: 0.649156:  72%|███████▏  | 36/50 [04:30<01:03,  4.55s/it]

[I 2025-12-02 18:00:35,735] Trial 34 pruned.

Best trial: 19. Best value: 0.649156:  74%|███████▍  | 37/50 [04:35<00:59,  4.57s/it]

[I 2025-12-02 18:00:40,361] Trial 36 finished with value: 0.574108818011257 and parameters: {'max_depth': 4, 'learning_rate': 0.24122982639279258, 'n_estimators': 316, 'subsample': 0.5431275954089309, 'colsample_bytree': 0.9583265097731818, 'min_child_weight': 3, 'gamma': 2.728922095176371, 'reg_alpha': 7.15142508697258e-08, 'reg_lambda': 5.266140855118571e-08, 'max_delta_step': 3}. Best is trial 19 with value: 0.6491557223264541.

Best trial: 19. Best value: 0.649156:  76%|███████▌  | 38/50 [04:40<00:55,  4.63s/it]

[I 2025-12-02 18:00:45,115] Trial 39 pruned.

Best trial: 19. Best value: 0.649156:  78%|███████▊  | 39/50 [04:54<01:21,  7.42s/it]

[I 2025-12-02 18:00:59,068] Trial 37 finished with value: 0.6106941838649156 and parameters: {'max_depth': 7, 'learning_rate': 0.13000043579126921, 'n_estimators': 545, 'subsample': 0.5330277171095407, 'colsample_bytree': 0.951563099447416, 'min_child_weight': 3, 'gamma': 2.6504849317033417, 'reg_alpha': 2.630065836332413e-06, 'reg_lambda': 1.4879225256014532e-05, 'max_delta_step': 5}. Best is trial 19 with value: 0.6491557223264541.

Best trial: 19. Best value: 0.649156:  80%|████████  | 40/50 [05:00<01:11,  7.12s/it]

[I 2025-12-02 18:01:05,482] Trial 41 pruned.

Best trial: 19. Best value: 0.649156:  82%|████████▏ | 41/50 [05:10<01:11,  7.92s/it]

[I 2025-12-02 18:01:15,258] Trial 43 pruned.

Best trial: 19. Best value: 0.649156:  84%|████████▍ | 42/50 [05:16<00:58,  7.26s/it]

[I 2025-12-02 18:01:20,998] Trial 44 pruned.

Best trial: 19. Best value: 0.649156:  86%|████████▌ | 43/50 [05:42<01:30, 12.91s/it]

[I 2025-12-02 18:01:47,092] Trial 38 finished with value: 0.5670731707317074 and parameters: {'max_depth': 7, 'learning_rate': 0.08268770985055453, 'n_estimators': 1163, 'subsample': 0.7971397626741172, 'colsample_bytree': 0.9025478580575897, 'min_child_weight': 1, 'gamma': 0.31099637267687746, 'reg_alpha': 1.152967383821514e-06, 'reg_lambda': 1.0167351038814646e-05, 'max_delta_step': 2}. Best is trial 19 with value: 0.6491557223264541.

Best trial: 19. Best value: 0.649156:  88%|████████▊ | 44/50 [05:43<00:56,  9.39s/it]

[I 2025-12-02 18:01:48,250] Trial 40 finished with value: 0.5670731707317074 and parameters: {'max_depth': 7, 'learning_rate': 0.1166015872960623, 'n_estimators': 1121, 'subsample': 0.794905611430809, 'colsample_bytree': 0.9101801135029228, 'min_child_weight': 1, 'gamma': 0.2979202934498092, 'reg_alpha': 1.5211942451723391e-06, 'reg_lambda': 1.1981214859867282e-05, 'max_delta_step': 2}. Best is trial 19 with value: 0.6491557223264541.

Best trial: 19. Best value: 0.649156:  90%|█████████ | 45/50 [05:49<00:42,  8.55s/it]

[I 2025-12-02 18:01:54,837] Trial 47 pruned.

Best trial: 19. Best value: 0.649156:  92%|█████████▏| 46/50 [05:53<00:28,  7.10s/it]

[I 2025-12-02 18:01:58,577] Trial 46 pruned.

Best trial: 19. Best value: 0.649156:  94%|█████████▍| 47/50 [06:02<00:22,  7.64s/it]

[I 2025-12-02 18:02:07,454] Trial 42 finished with value: 0.6036585365853658 and parameters: {'max_depth': 8, 'learning_rate': 0.08147582172393092, 'n_estimators': 1113, 'subsample': 0.7354731835442232, 'colsample_bytree': 0.8700486968069931, 'min_child_weight': 1, 'gamma': 0.17972132456554046, 'reg_alpha': 0.0022569921722407254, 'reg_lambda': 6.195831600828818e-07, 'max_delta_step': 1}. Best is trial 19 with value: 0.6491557223264541.

Best trial: 19. Best value: 0.649156:  96%|█████████▌| 48/50 [06:11<00:15,  7.90s/it]

[I 2025-12-02 18:02:15,959] Trial 48 pruned.

Best trial: 19. Best value: 0.649156:  98%|█████████▊| 49/50 [06:25<00:09,  9.84s/it]

[I 2025-12-02 18:02:30,345] Trial 45 finished with value: 0.5984990619136961 and parameters: {'max_depth': 8, 'learning_rate': 0.19280226460658814, 'n_estimators': 1488, 'subsample': 0.72671782648219, 'colsample_bytree': 0.9020846570811679, 'min_child_weight': 5, 'gamma': 3.9540375943207584, 'reg_alpha': 8.601621628491215e-07, 'reg_lambda': 0.00011616409848610947, 'max_delta_step': 5}. Best is trial 19 with value: 0.6491557223264541.

Best trial: 19. Best value: 0.649156: 100%|██████████| 50/50 [06:26<00:00,  7.73s/it]

[I 2025-12-02 18:02:31,424] Trial 49 pruned.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.649156                0.485714      0.514286

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.028571          0.571429               0.4        50          67

   test_size
0         17
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.649156                0.485714      0.514286

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.028571          0.571429               0.4        50          67

   test_size
0         17

## MCI-AD vs HC -> OPTUNA + XGB

In [ ]:

datasets = task_hf_compensated_comb_emb_lbl_ad_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_handcrafted_comb_emb_ad_hc_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param= "diagnosis_y",
)
print(summary)

[I 2025-12-02 18:02:36,496] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.497433:   2%|▏         | 1/50 [00:57<46:42, 57.20s/it]

[I 2025-12-02 18:03:33,685] Trial 3 finished with value: 0.4974326059050064 and parameters: {'max_depth': 7, 'learning_rate': 0.09062987113749937, 'n_estimators': 546, 'subsample': 0.7174216552609215, 'colsample_bytree': 0.9494938826622588, 'min_child_weight': 4, 'gamma': 4.551629867410868, 'reg_alpha': 1.7178744517164496e-05, 'reg_lambda': 2.149746719714904e-08, 'max_delta_step': 3}. Best is trial 3 with value: 0.4974326059050064.

Best trial: 3. Best value: 0.497433:   4%|▍         | 2/50 [01:04<22:27, 28.07s/it]

[I 2025-12-02 18:03:41,372] Trial 0 finished with value: 0.4486521181001284 and parameters: {'max_depth': 5, 'learning_rate': 0.012477442007765197, 'n_estimators': 394, 'subsample': 0.7842868036057511, 'colsample_bytree': 0.8989711721392745, 'min_child_weight': 4, 'gamma': 3.5066122863734, 'reg_alpha': 2.6798796722548093, 'reg_lambda': 6.880723274703934, 'max_delta_step': 0}. Best is trial 3 with value: 0.4974326059050064.

Best trial: 3. Best value: 0.497433:   6%|▌         | 3/50 [01:24<19:07, 24.41s/it]

[I 2025-12-02 18:04:01,426] Trial 5 finished with value: 0.4473684210526316 and parameters: {'max_depth': 3, 'learning_rate': 0.04869615917669944, 'n_estimators': 245, 'subsample': 0.5232121308180847, 'colsample_bytree': 0.5902570249309035, 'min_child_weight': 8, 'gamma': 2.523637619181369, 'reg_alpha': 0.6664030971454413, 'reg_lambda': 3.067674980309837e-05, 'max_delta_step': 2}. Best is trial 3 with value: 0.4974326059050064.

Best trial: 2. Best value: 0.535944:   8%|▊         | 4/50 [02:26<29:57, 39.08s/it]

[I 2025-12-02 18:05:02,983] Trial 2 finished with value: 0.5359435173299101 and parameters: {'max_depth': 9, 'learning_rate': 0.057759322542057, 'n_estimators': 1464, 'subsample': 0.6498693558890477, 'colsample_bytree': 0.758251197095563, 'min_child_weight': 2, 'gamma': 3.1098450008259464, 'reg_alpha': 0.0015620146049082201, 'reg_lambda': 1.4951160072810617e-06, 'max_delta_step': 4}. Best is trial 2 with value: 0.5359435173299101.

Best trial: 2. Best value: 0.535944:  10%|█         | 5/50 [02:46<24:02, 32.06s/it]

[I 2025-12-02 18:05:22,595] Trial 4 finished with value: 0.5096277278562259 and parameters: {'max_depth': 9, 'learning_rate': 0.15117002594342385, 'n_estimators': 995, 'subsample': 0.8322115549522706, 'colsample_bytree': 0.674925342815428, 'min_child_weight': 2, 'gamma': 3.5831531615997014, 'reg_alpha': 2.220852741646371e-05, 'reg_lambda': 0.00016785669035492825, 'max_delta_step': 1}. Best is trial 2 with value: 0.5359435173299101.

Best trial: 1. Best value: 0.562259:  12%|█▏        | 6/50 [02:53<17:23, 23.72s/it]

[I 2025-12-02 18:05:30,124] Trial 1 finished with value: 0.5622593068035944 and parameters: {'max_depth': 6, 'learning_rate': 0.012273149713817872, 'n_estimators': 664, 'subsample': 0.9466876753262399, 'colsample_bytree': 0.6822865496400083, 'min_child_weight': 2, 'gamma': 1.8166331738875292, 'reg_alpha': 2.657580305898039, 'reg_lambda': 5.429539178770351, 'max_delta_step': 9}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:  14%|█▍        | 7/50 [03:21<18:03, 25.19s/it]

[I 2025-12-02 18:05:58,349] Trial 6 finished with value: 0.558408215661104 and parameters: {'max_depth': 9, 'learning_rate': 0.11955632293049658, 'n_estimators': 1034, 'subsample': 0.9884506704521916, 'colsample_bytree': 0.9011765436823191, 'min_child_weight': 2, 'gamma': 0.9736913558726901, 'reg_alpha': 0.0051477195976748205, 'reg_lambda': 8.269235069604192e-05, 'max_delta_step': 0}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:  16%|█▌        | 8/50 [03:25<12:45, 18.24s/it]

[I 2025-12-02 18:06:01,698] Trial 8 finished with value: 0.4871630295250321 and parameters: {'max_depth': 9, 'learning_rate': 0.1178929106567749, 'n_estimators': 433, 'subsample': 0.6280053039200425, 'colsample_bytree': 0.612546171422542, 'min_child_weight': 6, 'gamma': 1.335082298461308, 'reg_alpha': 3.4956961565385137e-07, 'reg_lambda': 5.392270456827661e-08, 'max_delta_step': 6}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:  18%|█▊        | 9/50 [03:48<13:26, 19.68s/it]

[I 2025-12-02 18:06:24,541] Trial 9 finished with value: 0.14634146341463414 and parameters: {'max_depth': 8, 'learning_rate': 0.012449345179142892, 'n_estimators': 640, 'subsample': 0.9604559992038708, 'colsample_bytree': 0.9535577258317008, 'min_child_weight': 10, 'gamma': 4.915261602934591, 'reg_alpha': 0.04092109724552695, 'reg_lambda': 0.0054504303979698255, 'max_delta_step': 10}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:  20%|██        | 10/50 [04:24<16:31, 24.80s/it]

[I 2025-12-02 18:07:00,808] Trial 7 finished with value: 0.5237483953786906 and parameters: {'max_depth': 4, 'learning_rate': 0.061718465071707564, 'n_estimators': 1439, 'subsample': 0.9673063806120842, 'colsample_bytree': 0.8894239138005404, 'min_child_weight': 7, 'gamma': 0.6717825366580238, 'reg_alpha': 0.0706471802024436, 'reg_lambda': 3.3511172844608366e-07, 'max_delta_step': 8}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:  22%|██▏       | 11/50 [04:35<13:21, 20.56s/it]

[I 2025-12-02 18:07:11,754] Trial 10 pruned.

Best trial: 1. Best value: 0.562259:  24%|██▍       | 12/50 [04:39<09:49, 15.51s/it]

[I 2025-12-02 18:07:15,705] Trial 11 finished with value: 0.511553273427471 and parameters: {'max_depth': 9, 'learning_rate': 0.0687525087191989, 'n_estimators': 664, 'subsample': 0.709158817431861, 'colsample_bytree': 0.5368418633207871, 'min_child_weight': 2, 'gamma': 4.573822022965582, 'reg_alpha': 5.498114244368534, 'reg_lambda': 0.013244404253074757, 'max_delta_step': 9}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:  26%|██▌       | 13/50 [05:39<17:54, 29.04s/it]

[I 2025-12-02 18:08:15,888] Trial 12 finished with value: 0.5359435173299101 and parameters: {'max_depth': 5, 'learning_rate': 0.015146162742822152, 'n_estimators': 601, 'subsample': 0.6350504942912036, 'colsample_bytree': 0.8073754423886851, 'min_child_weight': 2, 'gamma': 3.7263548390167793, 'reg_alpha': 0.00014196749698681735, 'reg_lambda': 0.00423433751096038, 'max_delta_step': 0}. Best is trial 1 with value: 0.5622593068035944.

Best trial: 1. Best value: 0.562259:  28%|██▊       | 14/50 [06:06<17:03, 28.44s/it]

[I 2025-12-02 18:08:42,946] Trial 14 pruned.

Best trial: 15. Best value: 0.57638:  30%|███       | 15/50 [06:25<14:52, 25.49s/it]

[I 2025-12-02 18:09:01,584] Trial 15 finished with value: 0.576379974326059 and parameters: {'max_depth': 7, 'learning_rate': 0.2510106100431653, 'n_estimators': 876, 'subsample': 0.8788812471493955, 'colsample_bytree': 0.7896298057222656, 'min_child_weight': 1, 'gamma': 1.6489697915901946, 'reg_alpha': 0.015475986690519198, 'reg_lambda': 0.059712193301289664, 'max_delta_step': 5}. Best is trial 15 with value: 0.576379974326059.

Best trial: 15. Best value: 0.57638:  32%|███▏      | 16/50 [06:41<12:56, 22.84s/it]

[I 2025-12-02 18:09:18,276] Trial 13 finished with value: 0.5378690629011553 and parameters: {'max_depth': 6, 'learning_rate': 0.024479778189459223, 'n_estimators': 781, 'subsample': 0.8746916752707701, 'colsample_bytree': 0.5102905765794199, 'min_child_weight': 1, 'gamma': 1.7881361220580212, 'reg_alpha': 3.91827138954768e-08, 'reg_lambda': 9.775653070877771, 'max_delta_step': 10}. Best is trial 15 with value: 0.576379974326059.

Best trial: 15. Best value: 0.57638:  34%|███▍      | 17/50 [06:44<09:16, 16.87s/it]

[I 2025-12-02 18:09:21,255] Trial 16 finished with value: 0.5500641848523748 and parameters: {'max_depth': 7, 'learning_rate': 0.2731326041799135, 'n_estimators': 890, 'subsample': 0.8894565572219452, 'colsample_bytree': 0.685579459454231, 'min_child_weight': 4, 'gamma': 1.8032819533974465, 'reg_alpha': 0.007449311341106137, 'reg_lambda': 0.1399549020674051, 'max_delta_step': 6}. Best is trial 15 with value: 0.576379974326059.

Best trial: 15. Best value: 0.57638:  36%|███▌      | 18/50 [07:16<11:22, 21.32s/it]

[I 2025-12-02 18:09:52,932] Trial 19 pruned.

Best trial: 15. Best value: 0.57638:  38%|███▊      | 19/50 [07:21<08:32, 16.52s/it]

[I 2025-12-02 18:09:58,274] Trial 17 finished with value: 0.511553273427471 and parameters: {'max_depth': 10, 'learning_rate': 0.25729436551214235, 'n_estimators': 1059, 'subsample': 0.8887858843774306, 'colsample_bytree': 0.6897673237474105, 'min_child_weight': 4, 'gamma': 0.01855747522983897, 'reg_alpha': 0.015475314043149134, 'reg_lambda': 8.459588260318986e-06, 'max_delta_step': 5}. Best is trial 15 with value: 0.576379974326059.

Best trial: 15. Best value: 0.57638:  40%|████      | 20/50 [07:25<06:21, 12.71s/it]

[I 2025-12-02 18:10:02,120] Trial 18 finished with value: 0.5359435173299101 and parameters: {'max_depth': 6, 'learning_rate': 0.294525659148957, 'n_estimators': 822, 'subsample': 0.8947947233594453, 'colsample_bytree': 0.664736391834875, 'min_child_weight': 4, 'gamma': 0.07539865481735442, 'reg_alpha': 0.15071540292041768, 'reg_lambda': 0.2843322128456066, 'max_delta_step': 5}. Best is trial 15 with value: 0.576379974326059.

Best trial: 15. Best value: 0.57638:  42%|████▏     | 21/50 [08:04<09:56, 20.57s/it]

[I 2025-12-02 18:10:40,994] Trial 20 finished with value: 0.5359435173299101 and parameters: {'max_depth': 5, 'learning_rate': 0.28168625251262525, 'n_estimators': 1096, 'subsample': 0.9187926043177342, 'colsample_bytree': 0.6962041553397963, 'min_child_weight': 4, 'gamma': 0.11075344038338031, 'reg_alpha': 0.3205811706639664, 'reg_lambda': 0.25214705245197083, 'max_delta_step': 5}. Best is trial 15 with value: 0.576379974326059.

Best trial: 15. Best value: 0.57638:  44%|████▍     | 22/50 [09:30<18:43, 40.13s/it]

[I 2025-12-02 18:12:06,762] Trial 21 finished with value: 0.5481386392811296 and parameters: {'max_depth': 8, 'learning_rate': 0.03508171974893925, 'n_estimators': 1256, 'subsample': 0.8177106442214858, 'colsample_bytree': 0.8297762231228238, 'min_child_weight': 3, 'gamma': 0.10433247907553289, 'reg_alpha': 0.3093856175630303, 'reg_lambda': 0.15103893162239285, 'max_delta_step': 7}. Best is trial 15 with value: 0.576379974326059.

Best trial: 15. Best value: 0.57638:  46%|████▌     | 23/50 [09:45<14:43, 32.73s/it]

[I 2025-12-02 18:12:22,233] Trial 23 finished with value: 0.5622593068035944 and parameters: {'max_depth': 8, 'learning_rate': 0.03438810441312549, 'n_estimators': 1257, 'subsample': 0.8099432359348538, 'colsample_bytree': 0.8116521317552853, 'min_child_weight': 3, 'gamma': 2.2767618522280224, 'reg_alpha': 0.7564152012210041, 'reg_lambda': 0.0009963657984856575, 'max_delta_step': 8}. Best is trial 15 with value: 0.576379974326059.

Best trial: 15. Best value: 0.57638:  48%|████▊     | 24/50 [09:47<10:09, 23.46s/it]

[I 2025-12-02 18:12:24,059] Trial 22 finished with value: 0.5481386392811296 and parameters: {'max_depth': 8, 'learning_rate': 0.0370134145367207, 'n_estimators': 1330, 'subsample': 0.8095152868179253, 'colsample_bytree': 0.8488927804513566, 'min_child_weight': 3, 'gamma': 2.1625553193703344, 'reg_alpha': 0.3402881941945287, 'reg_lambda': 0.39245912833754215, 'max_delta_step': 8}. Best is trial 15 with value: 0.576379974326059.

Best trial: 15. Best value: 0.57638:  50%|█████     | 25/50 [10:35<12:53, 30.93s/it]

[I 2025-12-02 18:13:12,413] Trial 24 finished with value: 0.5603337612323491 and parameters: {'max_depth': 8, 'learning_rate': 0.1725759670369025, 'n_estimators': 1256, 'subsample': 0.995556586850456, 'colsample_bytree': 0.8330062567005406, 'min_child_weight': 1, 'gamma': 0.8112522117424019, 'reg_alpha': 0.002783187511756245, 'reg_lambda': 0.0005576485128880523, 'max_delta_step': 2}. Best is trial 15 with value: 0.576379974326059.

Best trial: 15. Best value: 0.57638:  52%|█████▏    | 26/50 [11:07<12:30, 31.27s/it]

[I 2025-12-02 18:13:44,461] Trial 27 pruned.

Best trial: 25. Best value: 0.609114:  54%|█████▍    | 27/50 [11:32<11:11, 29.21s/it]

[I 2025-12-02 18:14:08,884] Trial 25 finished with value: 0.6091142490372272 and parameters: {'max_depth': 8, 'learning_rate': 0.16791049556067178, 'n_estimators': 911, 'subsample': 0.9751435920075642, 'colsample_bytree': 0.8571801019379172, 'min_child_weight': 1, 'gamma': 1.0935591030911525, 'reg_alpha': 0.0033193247347465408, 'reg_lambda': 0.001099859919851331, 'max_delta_step': 3}. Best is trial 25 with value: 0.6091142490372272.

Best trial: 25. Best value: 0.609114:  56%|█████▌    | 28/50 [11:43<08:44, 23.82s/it]

[I 2025-12-02 18:14:20,133] Trial 26 pruned.

Best trial: 25. Best value: 0.609114:  58%|█████▊    | 29/50 [11:52<06:47, 19.40s/it]

[I 2025-12-02 18:14:29,200] Trial 28 pruned.

Best trial: 25. Best value: 0.609114:  60%|██████    | 30/50 [12:04<05:42, 17.15s/it]

[I 2025-12-02 18:14:41,105] Trial 29 pruned.

Best trial: 25. Best value: 0.609114:  62%|██████▏   | 31/50 [12:28<06:03, 19.12s/it]

[I 2025-12-02 18:15:04,804] Trial 33 pruned.

Best trial: 25. Best value: 0.609114:  64%|██████▍   | 32/50 [12:46<05:40, 18.90s/it]

[I 2025-12-02 18:15:23,199] Trial 32 pruned.

Best trial: 25. Best value: 0.609114:  66%|██████▌   | 33/50 [12:54<04:24, 15.58s/it]

[I 2025-12-02 18:15:31,044] Trial 31 finished with value: 0.5481386392811296 and parameters: {'max_depth': 6, 'learning_rate': 0.20019551844098613, 'n_estimators': 907, 'subsample': 0.9369700442994023, 'colsample_bytree': 0.724153128211418, 'min_child_weight': 5, 'gamma': 1.3203771831899256, 'reg_alpha': 0.0009372088213609813, 'reg_lambda': 1.9443265993078915, 'max_delta_step': 3}. Best is trial 25 with value: 0.6091142490372272.

Best trial: 25. Best value: 0.609114:  68%|██████▊   | 34/50 [13:31<05:52, 22.04s/it]

[I 2025-12-02 18:16:08,156] Trial 35 finished with value: 0.5885750962772786 and parameters: {'max_depth': 10, 'learning_rate': 0.13718681478443664, 'n_estimators': 336, 'subsample': 0.7892741153524869, 'colsample_bytree': 0.7913479884063033, 'min_child_weight': 2, 'gamma': 1.5920190002522294, 'reg_alpha': 0.02026095728624686, 'reg_lambda': 0.020813480456703143, 'max_delta_step': 4}. Best is trial 25 with value: 0.6091142490372272.

Best trial: 25. Best value: 0.609114:  70%|███████   | 35/50 [13:48<05:07, 20.48s/it]

[I 2025-12-02 18:16:24,988] Trial 37 pruned.

Best trial: 25. Best value: 0.609114:  72%|███████▏  | 36/50 [13:54<03:47, 16.27s/it]

[I 2025-12-02 18:16:31,448] Trial 30 finished with value: 0.5481386392811296 and parameters: {'max_depth': 6, 'learning_rate': 0.1943217430263932, 'n_estimators': 895, 'subsample': 0.9210519987433152, 'colsample_bytree': 0.9960293475189512, 'min_child_weight': 1, 'gamma': 1.2180229327181737, 'reg_alpha': 0.0005520685940474095, 'reg_lambda': 1.9423685486223776, 'max_delta_step': 3}. Best is trial 25 with value: 0.6091142490372272.

Best trial: 25. Best value: 0.609114:  74%|███████▍  | 37/50 [14:04<03:03, 14.12s/it]

[I 2025-12-02 18:16:40,534] Trial 36 finished with value: 0.5885750962772786 and parameters: {'max_depth': 10, 'learning_rate': 0.0840868528350048, 'n_estimators': 378, 'subsample': 0.8623710158456119, 'colsample_bytree': 0.7932470996502683, 'min_child_weight': 2, 'gamma': 0.5094873820430552, 'reg_alpha': 3.2238298725089902, 'reg_lambda': 0.0275084587073269, 'max_delta_step': 4}. Best is trial 25 with value: 0.6091142490372272.

Best trial: 25. Best value: 0.609114:  76%|███████▌  | 38/50 [14:16<02:41, 13.50s/it]

[I 2025-12-02 18:16:52,585] Trial 38 pruned.

Best trial: 25. Best value: 0.609114:  78%|███████▊  | 39/50 [14:43<03:14, 17.66s/it]

[I 2025-12-02 18:17:19,965] Trial 41 pruned.

Best trial: 25. Best value: 0.609114:  80%|████████  | 40/50 [14:43<02:05, 12.51s/it]

[I 2025-12-02 18:17:20,460] Trial 39 finished with value: 0.5744544287548139 and parameters: {'max_depth': 10, 'learning_rate': 0.09578762586828914, 'n_estimators': 327, 'subsample': 0.8536639013270384, 'colsample_bytree': 0.7593860035477605, 'min_child_weight': 2, 'gamma': 1.7557681749835459, 'reg_alpha': 4.1008022500878976e-06, 'reg_lambda': 0.003525069403317996, 'max_delta_step': 4}. Best is trial 25 with value: 0.6091142490372272.

Best trial: 25. Best value: 0.609114:  82%|████████▏ | 41/50 [14:51<01:39, 11.09s/it]

[I 2025-12-02 18:17:28,255] Trial 40 finished with value: 0.5866495507060334 and parameters: {'max_depth': 10, 'learning_rate': 0.09314271394556073, 'n_estimators': 332, 'subsample': 0.8628743515933315, 'colsample_bytree': 0.7887236869138023, 'min_child_weight': 2, 'gamma': 0.5694173898292165, 'reg_alpha': 4.089793089503389e-06, 'reg_lambda': 0.00407438701728605, 'max_delta_step': 4}. Best is trial 25 with value: 0.6091142490372272.

Best trial: 25. Best value: 0.609114:  84%|████████▍ | 42/50 [15:00<01:21, 10.25s/it]

[I 2025-12-02 18:17:36,524] Trial 43 pruned.

Best trial: 25. Best value: 0.609114:  86%|████████▌ | 43/50 [15:22<01:37, 13.88s/it]

[I 2025-12-02 18:17:58,881] Trial 44 finished with value: 0.5359435173299101 and parameters: {'max_depth': 9, 'learning_rate': 0.15319677140247084, 'n_estimators': 228, 'subsample': 0.7845998599259077, 'colsample_bytree': 0.7983228292384724, 'min_child_weight': 3, 'gamma': 0.9633998092691494, 'reg_alpha': 2.970044532989027e-06, 'reg_lambda': 0.030296746280723548, 'max_delta_step': 2}. Best is trial 25 with value: 0.6091142490372272.

Best trial: 25. Best value: 0.609114:  88%|████████▊ | 44/50 [15:26<01:05, 10.86s/it]

[I 2025-12-02 18:18:02,681] Trial 42 finished with value: 0.5603337612323491 and parameters: {'max_depth': 10, 'learning_rate': 0.15730955695222812, 'n_estimators': 339, 'subsample': 0.8535098519289819, 'colsample_bytree': 0.8012098963761862, 'min_child_weight': 2, 'gamma': 0.9003514402478789, 'reg_alpha': 0.02082131714998119, 'reg_lambda': 0.018291087526052983, 'max_delta_step': 2}. Best is trial 25 with value: 0.6091142490372272.

Best trial: 25. Best value: 0.609114:  90%|█████████ | 45/50 [15:44<01:04, 12.98s/it]

[I 2025-12-02 18:18:20,604] Trial 45 finished with value: 0.5462130937098845 and parameters: {'max_depth': 10, 'learning_rate': 0.11075285749381072, 'n_estimators': 342, 'subsample': 0.7852968276996051, 'colsample_bytree': 0.7954768209826876, 'min_child_weight': 2, 'gamma': 0.6704372745083619, 'reg_alpha': 8.806836329257406e-06, 'reg_lambda': 2.3038380204919985e-05, 'max_delta_step': 4}. Best is trial 25 with value: 0.6091142490372272.

Best trial: 25. Best value: 0.609114:  92%|█████████▏| 46/50 [15:44<00:36,  9.22s/it]

[I 2025-12-02 18:18:21,047] Trial 47 pruned.

Best trial: 25. Best value: 0.609114:  94%|█████████▍| 47/50 [15:53<00:27,  9.18s/it]

[I 2025-12-02 18:18:30,144] Trial 46 pruned.

Best trial: 25. Best value: 0.609114:  96%|█████████▌| 48/50 [15:57<00:15,  7.59s/it]

[I 2025-12-02 18:18:34,010] Trial 48 pruned.

Best trial: 25. Best value: 0.609114:  98%|█████████▊| 49/50 [16:00<00:06,  6.06s/it]

[I 2025-12-02 18:18:36,517] Trial 49 pruned.

Best trial: 25. Best value: 0.609114: 100%|██████████| 50/50 [16:15<00:00, 19.51s/it]

[I 2025-12-02 18:18:52,068] Trial 34 pruned.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.609114                     0.4           0.4

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0      -0.2               0.2               0.6        50          60

   test_size
0         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.609114                     0.4           0.4

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0      -0.2               0.2               0.6        50          60

   test_size
0         15

In [ ]:

datasets = task_hf_compensated_temp_emb_lbl_ad_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_handcrafted_temp_emb_compensated_ad_hc_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param= "diagnosis_y",
)
print(summary)

[I 2025-12-02 18:18:58,749] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.458922:   2%|▏         | 1/50 [00:43<35:22, 43.31s/it]

[I 2025-12-02 18:19:42,049] Trial 0 finished with value: 0.45892169448010267 and parameters: {'max_depth': 4, 'learning_rate': 0.020963215768440922, 'n_estimators': 741, 'subsample': 0.5501746977210555, 'colsample_bytree': 0.6061043699677534, 'min_child_weight': 5, 'gamma': 1.3874521103841038, 'reg_alpha': 4.588325797809998e-07, 'reg_lambda': 2.135422583342988e-07, 'max_delta_step': 3}. Best is trial 0 with value: 0.45892169448010267.

Best trial: 0. Best value: 0.458922:   4%|▍         | 2/50 [01:07<25:44, 32.19s/it]

[I 2025-12-02 18:20:06,448] Trial 1 finished with value: 0.4326059050064185 and parameters: {'max_depth': 4, 'learning_rate': 0.09530422528231136, 'n_estimators': 1208, 'subsample': 0.8443761746392916, 'colsample_bytree': 0.9887452131645317, 'min_child_weight': 4, 'gamma': 2.245673650428942, 'reg_alpha': 0.2520063311123921, 'reg_lambda': 0.012311696370516753, 'max_delta_step': 1}. Best is trial 0 with value: 0.45892169448010267.

Best trial: 0. Best value: 0.458922:   6%|▌         | 3/50 [01:09<14:28, 18.48s/it]

[I 2025-12-02 18:20:08,625] Trial 2 finished with value: 0.4120667522464698 and parameters: {'max_depth': 3, 'learning_rate': 0.2217776470257041, 'n_estimators': 1437, 'subsample': 0.5534087617507744, 'colsample_bytree': 0.95028642709439, 'min_child_weight': 5, 'gamma': 0.18494130145061627, 'reg_alpha': 0.32804106547292133, 'reg_lambda': 0.01164052014441151, 'max_delta_step': 2}. Best is trial 0 with value: 0.45892169448010267.

Best trial: 0. Best value: 0.458922:   8%|▊         | 4/50 [01:20<11:47, 15.39s/it]

[I 2025-12-02 18:20:19,276] Trial 5 finished with value: 0.14634146341463414 and parameters: {'max_depth': 5, 'learning_rate': 0.12633504881628743, 'n_estimators': 204, 'subsample': 0.8898259375995865, 'colsample_bytree': 0.8477669405844489, 'min_child_weight': 10, 'gamma': 2.5440231697601052, 'reg_alpha': 1.097662861665726e-07, 'reg_lambda': 2.616489926446289, 'max_delta_step': 1}. Best is trial 0 with value: 0.45892169448010267.

Best trial: 3. Best value: 0.471117:  10%|█         | 5/50 [01:31<10:27, 13.94s/it]

[I 2025-12-02 18:20:30,655] Trial 3 finished with value: 0.4711168164313222 and parameters: {'max_depth': 7, 'learning_rate': 0.01969977254037483, 'n_estimators': 958, 'subsample': 0.5330166838394229, 'colsample_bytree': 0.690554961770198, 'min_child_weight': 1, 'gamma': 2.3453774550936055, 'reg_alpha': 2.136856164974379e-06, 'reg_lambda': 1.5690811333920797e-08, 'max_delta_step': 1}. Best is trial 3 with value: 0.4711168164313222.

Best trial: 3. Best value: 0.471117:  12%|█▏        | 6/50 [02:05<15:02, 20.51s/it]

[I 2025-12-02 18:21:03,916] Trial 7 finished with value: 0.4467265725288832 and parameters: {'max_depth': 6, 'learning_rate': 0.20499997681330234, 'n_estimators': 861, 'subsample': 0.7169877008693475, 'colsample_bytree': 0.8559501472102381, 'min_child_weight': 5, 'gamma': 3.6160965471688233, 'reg_alpha': 0.31544170028988144, 'reg_lambda': 9.856560098104335e-06, 'max_delta_step': 9}. Best is trial 3 with value: 0.4711168164313222.

Best trial: 6. Best value: 0.474968:  14%|█▍        | 7/50 [02:12<11:42, 16.35s/it]

[I 2025-12-02 18:21:11,686] Trial 6 finished with value: 0.4749679075738126 and parameters: {'max_depth': 8, 'learning_rate': 0.22596637624700686, 'n_estimators': 1386, 'subsample': 0.5085191569388323, 'colsample_bytree': 0.5207999459093329, 'min_child_weight': 5, 'gamma': 4.2731315644894305, 'reg_alpha': 7.65672245056433e-05, 'reg_lambda': 3.4328046839030795, 'max_delta_step': 1}. Best is trial 6 with value: 0.4749679075738126.

Best trial: 6. Best value: 0.474968:  16%|█▌        | 8/50 [02:19<09:21, 13.37s/it]

[I 2025-12-02 18:21:18,692] Trial 4 finished with value: 0.45892169448010267 and parameters: {'max_depth': 10, 'learning_rate': 0.02905336658886623, 'n_estimators': 1493, 'subsample': 0.8174703050612809, 'colsample_bytree': 0.9363827784640109, 'min_child_weight': 4, 'gamma': 4.344995035962559, 'reg_alpha': 0.0003624071374725212, 'reg_lambda': 5.129666939480704e-06, 'max_delta_step': 10}. Best is trial 6 with value: 0.4749679075738126.

Best trial: 6. Best value: 0.474968:  18%|█▊        | 9/50 [02:23<07:06, 10.40s/it]

[I 2025-12-02 18:21:22,563] Trial 8 finished with value: 0.38575096277278564 and parameters: {'max_depth': 9, 'learning_rate': 0.013475898290381282, 'n_estimators': 921, 'subsample': 0.7222508613473373, 'colsample_bytree': 0.9711981455520651, 'min_child_weight': 8, 'gamma': 3.692734675431269, 'reg_alpha': 2.824488956530586e-06, 'reg_lambda': 1.0979760087887401e-07, 'max_delta_step': 3}. Best is trial 6 with value: 0.4749679075738126.

Best trial: 6. Best value: 0.474968:  20%|██        | 10/50 [03:04<13:08, 19.71s/it]

[I 2025-12-02 18:22:03,113] Trial 9 finished with value: 0.46919127086007706 and parameters: {'max_depth': 5, 'learning_rate': 0.04293598450003839, 'n_estimators': 874, 'subsample': 0.7365919014716675, 'colsample_bytree': 0.7281094112084251, 'min_child_weight': 2, 'gamma': 0.20410390378385268, 'reg_alpha': 0.015242198009700758, 'reg_lambda': 3.225838529943239e-05, 'max_delta_step': 10}. Best is trial 6 with value: 0.4749679075738126.

Best trial: 6. Best value: 0.474968:  22%|██▏       | 11/50 [03:08<09:42, 14.92s/it]

[I 2025-12-02 18:22:07,190] Trial 13 pruned.

Best trial: 6. Best value: 0.474968:  24%|██▍       | 12/50 [03:09<06:51, 10.82s/it]

[I 2025-12-02 18:22:08,624] Trial 12 pruned.

Best trial: 6. Best value: 0.474968:  26%|██▌       | 13/50 [03:13<05:23,  8.75s/it]

[I 2025-12-02 18:22:12,603] Trial 10 pruned.

Best trial: 11. Best value: 0.495507:  28%|██▊       | 14/50 [04:15<14:49, 24.72s/it]

[I 2025-12-02 18:23:14,230] Trial 11 finished with value: 0.49550706033376124 and parameters: {'max_depth': 9, 'learning_rate': 0.011125550322420021, 'n_estimators': 606, 'subsample': 0.5463260201410813, 'colsample_bytree': 0.8754854262445684, 'min_child_weight': 1, 'gamma': 0.2142703406716906, 'reg_alpha': 1.1172977453951399e-07, 'reg_lambda': 1.8866028290007442e-08, 'max_delta_step': 10}. Best is trial 11 with value: 0.49550706033376124.

Best trial: 11. Best value: 0.495507:  30%|███       | 15/50 [04:28<12:26, 21.34s/it]

[I 2025-12-02 18:23:27,726] Trial 17 pruned.

Best trial: 11. Best value: 0.495507:  32%|███▏      | 16/50 [04:33<09:13, 16.27s/it]

[I 2025-12-02 18:23:32,231] Trial 18 pruned.

Best trial: 11. Best value: 0.495507:  34%|███▍      | 17/50 [04:41<07:39, 13.94s/it]

[I 2025-12-02 18:23:40,742] Trial 19 pruned.

Best trial: 11. Best value: 0.495507:  36%|███▌      | 18/50 [04:50<06:33, 12.29s/it]

[I 2025-12-02 18:23:49,179] Trial 20 pruned.

Best trial: 11. Best value: 0.495507:  38%|███▊      | 19/50 [04:58<05:42, 11.03s/it]

[I 2025-12-02 18:23:57,300] Trial 21 pruned.

Best trial: 14. Best value: 0.56611:  40%|████      | 20/50 [04:59<03:58,  7.96s/it]

[I 2025-12-02 18:23:58,105] Trial 14 finished with value: 0.5661103979460848 and parameters: {'max_depth': 7, 'learning_rate': 0.010173691468103712, 'n_estimators': 1249, 'subsample': 0.9939699158435257, 'colsample_bytree': 0.6736989589303324, 'min_child_weight': 2, 'gamma': 2.734577912359128, 'reg_alpha': 1.1193654005008736e-05, 'reg_lambda': 0.005782533152911408, 'max_delta_step': 0}. Best is trial 14 with value: 0.5661103979460848.

Best trial: 14. Best value: 0.56611:  42%|████▏     | 21/50 [05:02<03:12,  6.65s/it]

[I 2025-12-02 18:24:01,711] Trial 22 pruned.

Best trial: 14. Best value: 0.56611:  44%|████▍     | 22/50 [05:06<02:40,  5.72s/it]

[I 2025-12-02 18:24:05,254] Trial 15 finished with value: 0.4833119383825417 and parameters: {'max_depth': 8, 'learning_rate': 0.010878308288580526, 'n_estimators': 1117, 'subsample': 0.5130678631288949, 'colsample_bytree': 0.6741028146297839, 'min_child_weight': 1, 'gamma': 2.3864029980436734, 'reg_alpha': 3.400035033789449e-05, 'reg_lambda': 1.602905685995385e-08, 'max_delta_step': 0}. Best is trial 14 with value: 0.5661103979460848.

Best trial: 14. Best value: 0.56611:  46%|████▌     | 23/50 [05:12<02:37,  5.83s/it]

[I 2025-12-02 18:24:11,328] Trial 16 finished with value: 0.4833119383825417 and parameters: {'max_depth': 8, 'learning_rate': 0.010593289794230827, 'n_estimators': 1109, 'subsample': 0.5042137358500445, 'colsample_bytree': 0.689526119292171, 'min_child_weight': 1, 'gamma': 2.400392147369062, 'reg_alpha': 4.391357168611461e-05, 'reg_lambda': 0.00042617658311978803, 'max_delta_step': 0}. Best is trial 14 with value: 0.5661103979460848.

Best trial: 14. Best value: 0.56611:  48%|████▊     | 24/50 [06:07<08:51, 20.45s/it]

[I 2025-12-02 18:25:05,892] Trial 23 finished with value: 0.5397946084724006 and parameters: {'max_depth': 7, 'learning_rate': 0.010556718946667046, 'n_estimators': 412, 'subsample': 0.9890019816740301, 'colsample_bytree': 0.8087981406366735, 'min_child_weight': 2, 'gamma': 1.9989892549193033, 'reg_alpha': 2.3136573800189916e-07, 'reg_lambda': 0.0008409760649504743, 'max_delta_step': 7}. Best is trial 14 with value: 0.5661103979460848.

Best trial: 14. Best value: 0.56611:  50%|█████     | 25/50 [06:36<09:40, 23.24s/it]

[I 2025-12-02 18:25:35,628] Trial 24 finished with value: 0.5661103979460848 and parameters: {'max_depth': 7, 'learning_rate': 0.015093017028426749, 'n_estimators': 1310, 'subsample': 0.9918354349639545, 'colsample_bytree': 0.5496126998555457, 'min_child_weight': 2, 'gamma': 4.037181473237509, 'reg_alpha': 1.8647504884959368e-07, 'reg_lambda': 0.3100597438623595, 'max_delta_step': 0}. Best is trial 14 with value: 0.5661103979460848.

Best trial: 14. Best value: 0.56611:  52%|█████▏    | 26/50 [06:56<08:49, 22.06s/it]

[I 2025-12-02 18:25:54,940] Trial 25 finished with value: 0.5661103979460848 and parameters: {'max_depth': 7, 'learning_rate': 0.010551699335247277, 'n_estimators': 1266, 'subsample': 0.9955391160185392, 'colsample_bytree': 0.661749038482258, 'min_child_weight': 2, 'gamma': 2.91386191147054, 'reg_alpha': 2.4755119136096843e-07, 'reg_lambda': 8.012295536501305e-08, 'max_delta_step': 0}. Best is trial 14 with value: 0.5661103979460848.

Best trial: 14. Best value: 0.56611:  54%|█████▍    | 27/50 [07:01<06:34, 17.14s/it]

[I 2025-12-02 18:26:00,593] Trial 26 finished with value: 0.5359435173299101 and parameters: {'max_depth': 7, 'learning_rate': 0.014649556522607916, 'n_estimators': 1262, 'subsample': 0.9761704930589277, 'colsample_bytree': 0.6528157901435593, 'min_child_weight': 2, 'gamma': 0.7939120088429259, 'reg_alpha': 2.560765227951497e-07, 'reg_lambda': 1.379613209524606e-07, 'max_delta_step': 4}. Best is trial 14 with value: 0.5661103979460848.

Best trial: 14. Best value: 0.56611:  56%|█████▌    | 28/50 [07:10<05:21, 14.63s/it]

[I 2025-12-02 18:26:09,373] Trial 27 finished with value: 0.511553273427471 and parameters: {'max_depth': 7, 'learning_rate': 0.01796320351351976, 'n_estimators': 477, 'subsample': 0.9991727513353902, 'colsample_bytree': 0.8937874242197881, 'min_child_weight': 3, 'gamma': 0.6680887937686448, 'reg_alpha': 1.2327713883948554e-07, 'reg_lambda': 0.002214695136134575, 'max_delta_step': 9}. Best is trial 14 with value: 0.5661103979460848.

Best trial: 14. Best value: 0.56611:  58%|█████▊    | 29/50 [07:16<04:09, 11.90s/it]

[I 2025-12-02 18:26:14,924] Trial 30 pruned.

Best trial: 14. Best value: 0.56611:  60%|██████    | 30/50 [07:24<03:39, 10.97s/it]

[I 2025-12-02 18:26:23,728] Trial 31 pruned.

Best trial: 14. Best value: 0.56611:  62%|██████▏   | 31/50 [07:27<02:42,  8.57s/it]

[I 2025-12-02 18:26:26,682] Trial 32 pruned.

Best trial: 14. Best value: 0.56611:  64%|██████▍   | 32/50 [07:36<02:33,  8.53s/it]

[I 2025-12-02 18:26:35,131] Trial 33 pruned.

Best trial: 14. Best value: 0.56611:  66%|██████▌   | 33/50 [07:59<03:38, 12.85s/it]

[I 2025-12-02 18:26:58,056] Trial 28 finished with value: 0.5500641848523748 and parameters: {'max_depth': 7, 'learning_rate': 0.01486159529735748, 'n_estimators': 1265, 'subsample': 0.987077959879658, 'colsample_bytree': 0.5505761409745789, 'min_child_weight': 3, 'gamma': 3.0075186216502434, 'reg_alpha': 2.611699344939143e-07, 'reg_lambda': 0.11154030945848455, 'max_delta_step': 4}. Best is trial 14 with value: 0.5661103979460848.

Best trial: 14. Best value: 0.56611:  68%|██████▊   | 34/50 [08:24<04:27, 16.70s/it]

[I 2025-12-02 18:27:23,740] Trial 29 finished with value: 0.5096277278562259 and parameters: {'max_depth': 6, 'learning_rate': 0.015415382838726545, 'n_estimators': 1316, 'subsample': 0.9475329923701954, 'colsample_bytree': 0.5956648130975148, 'min_child_weight': 3, 'gamma': 2.984599557966385, 'reg_alpha': 8.91583878689949e-07, 'reg_lambda': 0.2059283649116863, 'max_delta_step': 4}. Best is trial 14 with value: 0.5661103979460848.

Best trial: 14. Best value: 0.56611:  70%|███████   | 35/50 [08:29<03:16, 13.08s/it]

[I 2025-12-02 18:27:28,365] Trial 34 finished with value: 0.4974326059050064 and parameters: {'max_depth': 7, 'learning_rate': 0.02285854906191724, 'n_estimators': 713, 'subsample': 0.8860324249471262, 'colsample_bytree': 0.727776305879067, 'min_child_weight': 2, 'gamma': 1.6565073265737063, 'reg_alpha': 1.0283784769286316e-08, 'reg_lambda': 4.906948841646166e-05, 'max_delta_step': 0}. Best is trial 14 with value: 0.5661103979460848.

Best trial: 14. Best value: 0.56611:  72%|███████▏  | 36/50 [08:37<02:42, 11.59s/it]

[I 2025-12-02 18:27:36,499] Trial 37 pruned.

Best trial: 14. Best value: 0.56611:  74%|███████▍  | 37/50 [08:40<01:56,  8.93s/it]

[I 2025-12-02 18:27:39,199] Trial 38 pruned.

Best trial: 14. Best value: 0.56611:  76%|███████▌  | 38/50 [08:52<01:57,  9.76s/it]

[I 2025-12-02 18:27:50,911] Trial 39 pruned.

Best trial: 14. Best value: 0.56611:  78%|███████▊  | 39/50 [08:55<01:25,  7.79s/it]

[I 2025-12-02 18:27:54,095] Trial 40 pruned.

Best trial: 14. Best value: 0.56611:  80%|████████  | 40/50 [09:01<01:12,  7.22s/it]

[I 2025-12-02 18:27:59,977] Trial 35 finished with value: 0.5096277278562259 and parameters: {'max_depth': 7, 'learning_rate': 0.01007168070213589, 'n_estimators': 771, 'subsample': 0.8835151850558429, 'colsample_bytree': 0.7252897381792213, 'min_child_weight': 2, 'gamma': 1.9647715943563124, 'reg_alpha': 6.608691328040736e-06, 'reg_lambda': 7.14807823035952e-05, 'max_delta_step': 4}. Best is trial 14 with value: 0.5661103979460848.

Best trial: 14. Best value: 0.56611:  82%|████████▏ | 41/50 [09:07<01:02,  6.97s/it]

[I 2025-12-02 18:28:06,373] Trial 42 pruned.

Best trial: 14. Best value: 0.56611:  84%|████████▍ | 42/50 [09:12<00:50,  6.31s/it]

[I 2025-12-02 18:28:11,157] Trial 36 finished with value: 0.4486521181001284 and parameters: {'max_depth': 7, 'learning_rate': 0.032634292961371714, 'n_estimators': 1025, 'subsample': 0.8813284628327085, 'colsample_bytree': 0.721167557737924, 'min_child_weight': 2, 'gamma': 3.270459671023231, 'reg_alpha': 4.9719951478149025e-08, 'reg_lambda': 0.04226685360812179, 'max_delta_step': 4}. Best is trial 14 with value: 0.5661103979460848.

Best trial: 14. Best value: 0.56611:  86%|████████▌ | 43/50 [10:19<02:51, 24.55s/it]

[I 2025-12-02 18:29:18,263] Trial 41 finished with value: 0.5237483953786906 and parameters: {'max_depth': 7, 'learning_rate': 0.01285031534650163, 'n_estimators': 1187, 'subsample': 0.9675641256999153, 'colsample_bytree': 0.6405475261205682, 'min_child_weight': 3, 'gamma': 2.0929733911834374, 'reg_alpha': 5.223606647715674e-08, 'reg_lambda': 0.04603175166052733, 'max_delta_step': 2}. Best is trial 14 with value: 0.5661103979460848.

Best trial: 14. Best value: 0.56611:  88%|████████▊ | 44/50 [10:23<01:49, 18.24s/it]

[I 2025-12-02 18:29:21,764] Trial 43 finished with value: 0.5237483953786906 and parameters: {'max_depth': 8, 'learning_rate': 0.012819853801585783, 'n_estimators': 1182, 'subsample': 0.9716570058014945, 'colsample_bytree': 0.6256076606121073, 'min_child_weight': 3, 'gamma': 3.868816960372981, 'reg_alpha': 5.379028791391048e-08, 'reg_lambda': 0.024730721989680238, 'max_delta_step': 3}. Best is trial 14 with value: 0.5661103979460848.

Best trial: 14. Best value: 0.56611:  90%|█████████ | 45/50 [11:04<02:06, 25.24s/it]

[I 2025-12-02 18:30:03,342] Trial 44 finished with value: 0.5397946084724006 and parameters: {'max_depth': 7, 'learning_rate': 0.012746223028764188, 'n_estimators': 1236, 'subsample': 0.9970944052990715, 'colsample_bytree': 0.7706288436819116, 'min_child_weight': 1, 'gamma': 2.694488472872597, 'reg_alpha': 2.368770595151526e-07, 'reg_lambda': 0.0013302615536022867, 'max_delta_step': 6}. Best is trial 14 with value: 0.5661103979460848.

Best trial: 14. Best value: 0.56611:  92%|█████████▏| 46/50 [11:05<01:11, 17.88s/it]

[I 2025-12-02 18:30:04,040] Trial 45 finished with value: 0.5256739409499358 and parameters: {'max_depth': 8, 'learning_rate': 0.012391318982424657, 'n_estimators': 1242, 'subsample': 0.9987567956205643, 'colsample_bytree': 0.6696854460939342, 'min_child_weight': 1, 'gamma': 2.134733373782704, 'reg_alpha': 3.5592171445513404e-07, 'reg_lambda': 0.0017850698235467874, 'max_delta_step': 6}. Best is trial 14 with value: 0.5661103979460848.

Best trial: 14. Best value: 0.56611:  94%|█████████▍| 47/50 [11:22<00:52, 17.66s/it]

[I 2025-12-02 18:30:21,187] Trial 48 pruned.

Best trial: 14. Best value: 0.56611:  96%|█████████▌| 48/50 [11:24<00:25, 12.98s/it]

[I 2025-12-02 18:30:23,269] Trial 49 pruned.

Best trial: 14. Best value: 0.56611:  98%|█████████▊| 49/50 [12:06<00:21, 21.82s/it]

[I 2025-12-02 18:31:05,704] Trial 47 finished with value: 0.5397946084724006 and parameters: {'max_depth': 6, 'learning_rate': 0.012271769176469058, 'n_estimators': 1447, 'subsample': 0.9993156808972065, 'colsample_bytree': 0.7638786288206793, 'min_child_weight': 1, 'gamma': 4.55484799255363, 'reg_alpha': 3.074981584564521e-07, 'reg_lambda': 6.794693238027089e-07, 'max_delta_step': 6}. Best is trial 14 with value: 0.5661103979460848.

Best trial: 14. Best value: 0.56611: 100%|██████████| 50/50 [12:09<00:00, 14.59s/it]

[I 2025-12-02 18:31:08,369] Trial 46 finished with value: 0.5397946084724006 and parameters: {'max_depth': 8, 'learning_rate': 0.01258289222949131, 'n_estimators': 1496, 'subsample': 0.9940932443450583, 'colsample_bytree': 0.7714250969245505, 'min_child_weight': 1, 'gamma': 4.636504592010489, 'reg_alpha': 2.365524765309229e-07, 'reg_lambda': 7.466614671396837e-07, 'max_delta_step': 6}. Best is trial 14 with value: 0.5661103979460848.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo        0.56611                     0.5          0.54

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0       0.0               0.2               0.8        50          60

   test_size
0         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo        0.56611                     0.5          0.54

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0       0.0               0.2               0.8        50          60

   test_size
0         15

In [ ]:

datasets = task_hf_compensated_freq_emb_lbl_ad_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_handcrafted_frerq_emb_compensated_ad_hc_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param= "diagnosis_y",
)
print(summary)
## MCI-AD vs HC -> OPTUNA + XGB

[I 2025-12-02 18:31:14,947] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.487163:   2%|▏         | 1/50 [00:32<26:38, 32.61s/it]

[I 2025-12-02 18:31:47,549] Trial 3 finished with value: 0.4871630295250321 and parameters: {'max_depth': 4, 'learning_rate': 0.052044727691106366, 'n_estimators': 374, 'subsample': 0.762966311661122, 'colsample_bytree': 0.9348840159032084, 'min_child_weight': 3, 'gamma': 4.896270726793778, 'reg_alpha': 0.00034207269383858296, 'reg_lambda': 0.0016006791499645586, 'max_delta_step': 5}. Best is trial 3 with value: 0.4871630295250321.

Best trial: 3. Best value: 0.487163:   4%|▍         | 2/50 [00:50<19:13, 24.04s/it]

[I 2025-12-02 18:32:05,578] Trial 0 finished with value: 0.3716302952503209 and parameters: {'max_depth': 5, 'learning_rate': 0.010294285579183769, 'n_estimators': 785, 'subsample': 0.8687489057269087, 'colsample_bytree': 0.7333158838758509, 'min_child_weight': 8, 'gamma': 2.7774676146494475, 'reg_alpha': 4.977543500941308e-06, 'reg_lambda': 1.6862138285952454e-06, 'max_delta_step': 2}. Best is trial 3 with value: 0.4871630295250321.
[I 2025-12-02 18:32:05,587] Trial 1 finished with value: 0.45892169448010267 and parameters: {'max_depth': 10, 'learning_rate': 0.19134448382566713, 'n_estimators': 907, 'subsample': 0.566597691631135, 'colsample_bytree': 0.9505963747045234, 'min_child_weight': 2, 'gamma': 0.49297535092053923, 'reg_alpha': 0.0008659291973547319, 'reg_lambda': 6.177707864981924e-08, 'max_delta_step': 5}. Best is trial 3 with value: 0.4871630295250321.

Best trial: 2. Best value: 0.501284:   8%|▊         | 4/50 [01:02<09:36, 12.54s/it]

[I 2025-12-02 18:32:16,985] Trial 2 finished with value: 0.5012836970474968 and parameters: {'max_depth': 6, 'learning_rate': 0.1410151516636672, 'n_estimators': 1332, 'subsample': 0.645628235522568, 'colsample_bytree': 0.505671784302703, 'min_child_weight': 8, 'gamma': 0.32440457475123974, 'reg_alpha': 0.007193294031754009, 'reg_lambda': 0.0005101827307098399, 'max_delta_step': 8}. Best is trial 2 with value: 0.5012836970474968.

Best trial: 2. Best value: 0.501284:  10%|█         | 5/50 [01:08<07:58, 10.62s/it]

[I 2025-12-02 18:32:23,335] Trial 6 finished with value: 0.25609756097560976 and parameters: {'max_depth': 6, 'learning_rate': 0.18818110805455798, 'n_estimators': 256, 'subsample': 0.9112891632801725, 'colsample_bytree': 0.8946555985683043, 'min_child_weight': 10, 'gamma': 2.022693476524748, 'reg_alpha': 0.1480756471015055, 'reg_lambda': 2.578447075880002e-08, 'max_delta_step': 2}. Best is trial 2 with value: 0.5012836970474968.

Best trial: 2. Best value: 0.501284:  12%|█▏        | 6/50 [01:36<11:38, 15.87s/it]

[I 2025-12-02 18:32:51,076] Trial 4 finished with value: 0.40629011553273425 and parameters: {'max_depth': 8, 'learning_rate': 0.17733348851901143, 'n_estimators': 1315, 'subsample': 0.7682763086219042, 'colsample_bytree': 0.6123717833749267, 'min_child_weight': 6, 'gamma': 4.645910615351046, 'reg_alpha': 0.003196994644085595, 'reg_lambda': 0.5692448172687156, 'max_delta_step': 6}. Best is trial 2 with value: 0.5012836970474968.

Best trial: 8. Best value: 0.537869:  14%|█▍        | 7/50 [01:42<09:22, 13.08s/it]

[I 2025-12-02 18:32:57,768] Trial 8 finished with value: 0.5378690629011553 and parameters: {'max_depth': 9, 'learning_rate': 0.011282329703047841, 'n_estimators': 460, 'subsample': 0.9987908211286906, 'colsample_bytree': 0.5259806567462936, 'min_child_weight': 6, 'gamma': 3.030398657250278, 'reg_alpha': 4.0265896216888715e-05, 'reg_lambda': 0.07965320275716992, 'max_delta_step': 9}. Best is trial 8 with value: 0.5378690629011553.

Best trial: 8. Best value: 0.537869:  16%|█▌        | 8/50 [01:43<06:25,  9.18s/it]

[I 2025-12-02 18:32:58,006] Trial 7 finished with value: 0.4993581514762516 and parameters: {'max_depth': 4, 'learning_rate': 0.010608872264579575, 'n_estimators': 293, 'subsample': 0.7004644701688636, 'colsample_bytree': 0.8534773283237912, 'min_child_weight': 3, 'gamma': 4.397799256950191, 'reg_alpha': 6.005602978282556e-06, 'reg_lambda': 3.1814168628553386e-05, 'max_delta_step': 1}. Best is trial 8 with value: 0.5378690629011553.

Best trial: 8. Best value: 0.537869:  18%|█▊        | 9/50 [01:55<06:51, 10.05s/it]

[I 2025-12-02 18:33:10,040] Trial 5 finished with value: 0.3979460847240051 and parameters: {'max_depth': 9, 'learning_rate': 0.023360509388425977, 'n_estimators': 1288, 'subsample': 0.7570196188168707, 'colsample_bytree': 0.7871736733870611, 'min_child_weight': 8, 'gamma': 4.707163394168756, 'reg_alpha': 6.152510387335439e-07, 'reg_lambda': 2.0529004445321664e-05, 'max_delta_step': 2}. Best is trial 8 with value: 0.5378690629011553.

Best trial: 8. Best value: 0.537869:  20%|██        | 10/50 [02:04<06:29,  9.74s/it]

[I 2025-12-02 18:33:19,063] Trial 9 finished with value: 0.4974326059050064 and parameters: {'max_depth': 4, 'learning_rate': 0.06588196677574398, 'n_estimators': 412, 'subsample': 0.7117587600244373, 'colsample_bytree': 0.5450361032314994, 'min_child_weight': 2, 'gamma': 1.6131501914614859, 'reg_alpha': 1.2698117626910609e-08, 'reg_lambda': 0.0002491700958215324, 'max_delta_step': 9}. Best is trial 8 with value: 0.5378690629011553.

Best trial: 8. Best value: 0.537869:  22%|██▏       | 11/50 [02:05<04:37,  7.11s/it]

[I 2025-12-02 18:33:20,062] Trial 10 pruned.

Best trial: 8. Best value: 0.537869:  24%|██▍       | 12/50 [02:05<03:13,  5.08s/it]

[I 2025-12-02 18:33:20,442] Trial 12 pruned.

Best trial: 8. Best value: 0.537869:  26%|██▌       | 13/50 [02:10<03:08,  5.10s/it]

[I 2025-12-02 18:33:25,584] Trial 14 pruned.

Best trial: 8. Best value: 0.537869:  28%|██▊       | 14/50 [02:23<04:29,  7.47s/it]

[I 2025-12-02 18:33:38,578] Trial 16 pruned.

Best trial: 8. Best value: 0.537869:  30%|███       | 15/50 [02:31<04:26,  7.62s/it]

[I 2025-12-02 18:33:46,527] Trial 17 pruned.

Best trial: 8. Best value: 0.537869:  32%|███▏      | 16/50 [02:36<03:47,  6.69s/it]

[I 2025-12-02 18:33:51,067] Trial 18 pruned.

Best trial: 8. Best value: 0.537869:  34%|███▍      | 17/50 [02:45<04:11,  7.63s/it]

[I 2025-12-02 18:34:00,894] Trial 13 finished with value: 0.5378690629011553 and parameters: {'max_depth': 8, 'learning_rate': 0.028441704876681493, 'n_estimators': 671, 'subsample': 0.9942627205042386, 'colsample_bytree': 0.6595872178428228, 'min_child_weight': 5, 'gamma': 3.229891725692559, 'reg_alpha': 6.8568679085417275, 'reg_lambda': 6.709150142924258, 'max_delta_step': 10}. Best is trial 8 with value: 0.5378690629011553.

Best trial: 8. Best value: 0.537869:  36%|███▌      | 18/50 [02:46<02:54,  5.44s/it]

[I 2025-12-02 18:34:01,232] Trial 19 pruned.

Best trial: 8. Best value: 0.537869:  38%|███▊      | 19/50 [03:00<04:07,  7.97s/it]

[I 2025-12-02 18:34:15,104] Trial 11 finished with value: 0.48523748395378685 and parameters: {'max_depth': 8, 'learning_rate': 0.01508766740889299, 'n_estimators': 1004, 'subsample': 0.9937051545203289, 'colsample_bytree': 0.6526022969833462, 'min_child_weight': 2, 'gamma': 4.595504107902473, 'reg_alpha': 0.00021867227609207357, 'reg_lambda': 6.166772674006245e-08, 'max_delta_step': 3}. Best is trial 8 with value: 0.5378690629011553.

Best trial: 8. Best value: 0.537869:  40%|████      | 20/50 [03:04<03:30,  7.03s/it]

[I 2025-12-02 18:34:19,939] Trial 15 finished with value: 0.5237483953786906 and parameters: {'max_depth': 7, 'learning_rate': 0.06847745675395843, 'n_estimators': 998, 'subsample': 0.99628316359234, 'colsample_bytree': 0.5155189376009064, 'min_child_weight': 5, 'gamma': 0.10637157021438348, 'reg_alpha': 1.7243867601287763, 'reg_lambda': 0.037981473561522365, 'max_delta_step': 10}. Best is trial 8 with value: 0.5378690629011553.

Best trial: 8. Best value: 0.537869:  42%|████▏     | 21/50 [03:23<05:02, 10.43s/it]

[I 2025-12-02 18:34:38,313] Trial 20 finished with value: 0.4749679075738126 and parameters: {'max_depth': 9, 'learning_rate': 0.017724004505835854, 'n_estimators': 565, 'subsample': 0.9792586929600007, 'colsample_bytree': 0.6950377069167053, 'min_child_weight': 4, 'gamma': 3.7849549651404564, 'reg_alpha': 6.358141172287689, 'reg_lambda': 8.495838986865259, 'max_delta_step': 10}. Best is trial 8 with value: 0.5378690629011553.

Best trial: 8. Best value: 0.537869:  44%|████▍     | 22/50 [03:31<04:33,  9.76s/it]

[I 2025-12-02 18:34:46,494] Trial 24 pruned.

Best trial: 8. Best value: 0.537869:  46%|████▌     | 23/50 [03:32<03:10,  7.06s/it]

[I 2025-12-02 18:34:47,274] Trial 21 finished with value: 0.5256739409499358 and parameters: {'max_depth': 9, 'learning_rate': 0.016463351163712763, 'n_estimators': 607, 'subsample': 0.9364691189929547, 'colsample_bytree': 0.6577541528985207, 'min_child_weight': 4, 'gamma': 3.745818325258207, 'reg_alpha': 3.1582917765224856, 'reg_lambda': 4.128681018123552, 'max_delta_step': 10}. Best is trial 8 with value: 0.5378690629011553.

Best trial: 8. Best value: 0.537869:  48%|████▊     | 24/50 [03:42<03:24,  7.85s/it]

[I 2025-12-02 18:34:56,958] Trial 26 pruned.

Best trial: 8. Best value: 0.537869:  50%|█████     | 25/50 [03:49<03:10,  7.64s/it]

[I 2025-12-02 18:35:04,100] Trial 27 pruned.

Best trial: 8. Best value: 0.537869:  52%|█████▏    | 26/50 [03:53<02:37,  6.58s/it]

[I 2025-12-02 18:35:08,207] Trial 22 finished with value: 0.5134788189987163 and parameters: {'max_depth': 9, 'learning_rate': 0.016797489261669896, 'n_estimators': 640, 'subsample': 0.9228061625355161, 'colsample_bytree': 0.793382265026217, 'min_child_weight': 4, 'gamma': 3.798693419369346, 'reg_alpha': 1.298356792881709, 'reg_lambda': 8.818292084172725, 'max_delta_step': 9}. Best is trial 8 with value: 0.5378690629011553.

Best trial: 8. Best value: 0.537869:  54%|█████▍    | 27/50 [03:55<02:00,  5.22s/it]

[I 2025-12-02 18:35:10,258] Trial 23 finished with value: 0.4993581514762516 and parameters: {'max_depth': 9, 'learning_rate': 0.018597239469039493, 'n_estimators': 660, 'subsample': 0.8327467743216624, 'colsample_bytree': 0.7834163144413464, 'min_child_weight': 4, 'gamma': 3.87414026221576, 'reg_alpha': 1.836880257786949e-07, 'reg_lambda': 2.5036219973867246, 'max_delta_step': 6}. Best is trial 8 with value: 0.5378690629011553.

Best trial: 8. Best value: 0.537869:  56%|█████▌    | 28/50 [03:57<01:35,  4.35s/it]

[I 2025-12-02 18:35:12,571] Trial 28 pruned.

Best trial: 8. Best value: 0.537869:  58%|█████▊    | 29/50 [04:02<01:36,  4.61s/it]

[I 2025-12-02 18:35:17,794] Trial 30 pruned.

Best trial: 8. Best value: 0.537869:  60%|██████    | 30/50 [04:05<01:23,  4.16s/it]

[I 2025-12-02 18:35:20,919] Trial 31 pruned.

Best trial: 8. Best value: 0.537869:  62%|██████▏   | 31/50 [04:06<00:56,  2.98s/it]

[I 2025-12-02 18:35:21,127] Trial 29 pruned.

Best trial: 8. Best value: 0.537869:  64%|██████▍   | 32/50 [04:08<00:52,  2.92s/it]

[I 2025-12-02 18:35:23,907] Trial 32 pruned.

Best trial: 8. Best value: 0.537869:  66%|██████▌   | 33/50 [04:15<01:08,  4.05s/it]

[I 2025-12-02 18:35:30,582] Trial 33 pruned.

Best trial: 8. Best value: 0.537869:  68%|██████▊   | 34/50 [04:18<00:56,  3.55s/it]

[I 2025-12-02 18:35:32,963] Trial 35 pruned.

Best trial: 8. Best value: 0.537869:  70%|███████   | 35/50 [04:27<01:20,  5.34s/it]

[I 2025-12-02 18:35:42,486] Trial 25 finished with value: 0.5256739409499358 and parameters: {'max_depth': 7, 'learning_rate': 0.01684579348198438, 'n_estimators': 675, 'subsample': 0.8731981347460104, 'colsample_bytree': 0.627848153056052, 'min_child_weight': 4, 'gamma': 3.2252989637633744, 'reg_alpha': 0.9983339319314509, 'reg_lambda': 0.8387735892639296, 'max_delta_step': 9}. Best is trial 8 with value: 0.5378690629011553.

Best trial: 8. Best value: 0.537869:  72%|███████▏  | 36/50 [04:40<01:48,  7.77s/it]

[I 2025-12-02 18:35:55,920] Trial 38 pruned.

Best trial: 8. Best value: 0.537869:  74%|███████▍  | 37/50 [04:46<01:32,  7.10s/it]

[I 2025-12-02 18:36:01,479] Trial 39 pruned.

Best trial: 8. Best value: 0.537869:  76%|███████▌  | 38/50 [04:54<01:29,  7.45s/it]

[I 2025-12-02 18:36:09,732] Trial 40 pruned.

Best trial: 8. Best value: 0.537869:  78%|███████▊  | 39/50 [05:00<01:17,  7.00s/it]

[I 2025-12-02 18:36:15,694] Trial 34 finished with value: 0.5378690629011553 and parameters: {'max_depth': 7, 'learning_rate': 0.040355329929882416, 'n_estimators': 918, 'subsample': 0.9449071982650862, 'colsample_bytree': 0.5507338598066847, 'min_child_weight': 5, 'gamma': 2.876993789398181, 'reg_alpha': 3.0524249354488706, 'reg_lambda': 0.049402970435589166, 'max_delta_step': 10}. Best is trial 8 with value: 0.5378690629011553.

Best trial: 8. Best value: 0.537869:  80%|████████  | 40/50 [05:04<00:58,  5.89s/it]

[I 2025-12-02 18:36:18,985] Trial 41 pruned.

Best trial: 8. Best value: 0.537869:  82%|████████▏ | 41/50 [05:11<00:56,  6.31s/it]

[I 2025-12-02 18:36:26,262] Trial 36 finished with value: 0.5378690629011553 and parameters: {'max_depth': 7, 'learning_rate': 0.038552374759335435, 'n_estimators': 938, 'subsample': 0.9632998376849595, 'colsample_bytree': 0.5639507282711613, 'min_child_weight': 5, 'gamma': 2.550783641258499, 'reg_alpha': 2.7092059091220824, 'reg_lambda': 0.04322557991101103, 'max_delta_step': 10}. Best is trial 8 with value: 0.5378690629011553.

Best trial: 8. Best value: 0.537869:  84%|████████▍ | 42/50 [05:14<00:43,  5.46s/it]

[I 2025-12-02 18:36:29,741] Trial 43 pruned.

Best trial: 8. Best value: 0.537869:  86%|████████▌ | 43/50 [05:21<00:41,  5.96s/it]

[I 2025-12-02 18:36:36,861] Trial 44 pruned.

Best trial: 8. Best value: 0.537869:  88%|████████▊ | 44/50 [05:23<00:28,  4.78s/it]

[I 2025-12-02 18:36:38,896] Trial 37 finished with value: 0.5256739409499358 and parameters: {'max_depth': 7, 'learning_rate': 0.09601592505613767, 'n_estimators': 1143, 'subsample': 0.9961220646724225, 'colsample_bytree': 0.5007736199890038, 'min_child_weight': 3, 'gamma': 0.7199110382030209, 'reg_alpha': 3.48315765185975, 'reg_lambda': 1.6056174895413409, 'max_delta_step': 10}. Best is trial 8 with value: 0.5378690629011553.

Best trial: 8. Best value: 0.537869:  90%|█████████ | 45/50 [05:32<00:29,  5.96s/it]

[I 2025-12-02 18:36:47,614] Trial 47 pruned.

Best trial: 42. Best value: 0.578306:  92%|█████████▏| 46/50 [05:59<00:49, 12.31s/it]

[I 2025-12-02 18:37:14,741] Trial 42 finished with value: 0.5783055198973043 and parameters: {'max_depth': 6, 'learning_rate': 0.0487566666297045, 'n_estimators': 1173, 'subsample': 0.9419328563264169, 'colsample_bytree': 0.5478321339012663, 'min_child_weight': 7, 'gamma': 4.093251024273703, 'reg_alpha': 4.511636076164446, 'reg_lambda': 0.0027698371878500682, 'max_delta_step': 10}. Best is trial 42 with value: 0.5783055198973043.

Best trial: 42. Best value: 0.578306:  94%|█████████▍| 47/50 [06:05<00:31, 10.43s/it]

[I 2025-12-02 18:37:20,800] Trial 45 finished with value: 0.5256739409499358 and parameters: {'max_depth': 6, 'learning_rate': 0.03787877267700475, 'n_estimators': 844, 'subsample': 0.9678658052218994, 'colsample_bytree': 0.5778207874574698, 'min_child_weight': 5, 'gamma': 2.452301035431955, 'reg_alpha': 3.02160034728824, 'reg_lambda': 3.004288738911727, 'max_delta_step': 10}. Best is trial 42 with value: 0.5783055198973043.

Best trial: 42. Best value: 0.578306:  96%|█████████▌| 48/50 [06:09<00:16,  8.29s/it]

[I 2025-12-02 18:37:24,061] Trial 49 pruned.

Best trial: 42. Best value: 0.578306:  98%|█████████▊| 49/50 [06:13<00:06,  6.96s/it]

[I 2025-12-02 18:37:27,955] Trial 46 finished with value: 0.5134788189987163 and parameters: {'max_depth': 6, 'learning_rate': 0.03204922423993509, 'n_estimators': 884, 'subsample': 0.9100665719489215, 'colsample_bytree': 0.5837033747324241, 'min_child_weight': 5, 'gamma': 2.9818842315015526, 'reg_alpha': 0.0007224869608354899, 'reg_lambda': 2.667234669577741, 'max_delta_step': 9}. Best is trial 42 with value: 0.5783055198973043.

Best trial: 42. Best value: 0.578306: 100%|██████████| 50/50 [06:16<00:00,  7.54s/it]

[I 2025-12-02 18:37:31,707] Trial 48 finished with value: 0.5237483953786906 and parameters: {'max_depth': 9, 'learning_rate': 0.03396703039699993, 'n_estimators': 824, 'subsample': 0.97113486470423, 'colsample_bytree': 0.5908519303632377, 'min_child_weight': 5, 'gamma': 2.972784083233776, 'reg_alpha': 0.25758757483782146, 'reg_lambda': 0.000456994385817025, 'max_delta_step': 9}. Best is trial 42 with value: 0.5783055198973043.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.578306                     0.5          0.66

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0       0.0               0.4               0.6        50          60

   test_size
0         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.578306                     0.5          0.66

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0       0.0               0.4               0.6        50          60

   test_size
0         15

In [ ]:
datasets = task_freq_dfs_ad_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_freq_ad_hc_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param="emb_",
)
print(summary)

[I 2025-12-02 18:37:35,686] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.210526:   2%|▏         | 1/50 [00:35<28:42, 35.14s/it]

[I 2025-12-02 18:38:10,821] Trial 1 finished with value: 0.21052631578947367 and parameters: {'max_depth': 8, 'learning_rate': 0.018310543828081897, 'n_estimators': 614, 'subsample': 0.6721554201518797, 'colsample_bytree': 0.9002605595157891, 'min_child_weight': 9, 'gamma': 0.5758821869227887, 'reg_alpha': 1.0743185851253069e-06, 'reg_lambda': 0.48125766253276897, 'max_delta_step': 9}. Best is trial 1 with value: 0.21052631578947367.

Best trial: 0. Best value: 0.304878:   4%|▍         | 2/50 [00:40<13:59, 17.49s/it]

[I 2025-12-02 18:38:15,962] Trial 0 finished with value: 0.3048780487804878 and parameters: {'max_depth': 4, 'learning_rate': 0.049031060195800946, 'n_estimators': 740, 'subsample': 0.9312274808588703, 'colsample_bytree': 0.7925157432509395, 'min_child_weight': 10, 'gamma': 1.271284930534637, 'reg_alpha': 8.200933558844264e-08, 'reg_lambda': 3.879201303973193e-05, 'max_delta_step': 5}. Best is trial 0 with value: 0.3048780487804878.

Best trial: 3. Best value: 0.5:   6%|▌         | 3/50 [00:55<12:59, 16.58s/it]

[I 2025-12-02 18:38:31,465] Trial 3 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.0655948518108788, 'n_estimators': 1095, 'subsample': 0.5465608395110766, 'colsample_bytree': 0.7025122585438257, 'min_child_weight': 10, 'gamma': 3.5740315583555073, 'reg_alpha': 0.05894778838439036, 'reg_lambda': 0.024187723605464388, 'max_delta_step': 0}. Best is trial 3 with value: 0.5.

Best trial: 5. Best value: 0.555841:   8%|▊         | 4/50 [00:59<08:46, 11.44s/it]

[I 2025-12-02 18:38:35,030] Trial 5 finished with value: 0.5558408215661104 and parameters: {'max_depth': 5, 'learning_rate': 0.013833697554360447, 'n_estimators': 291, 'subsample': 0.7488657254468247, 'colsample_bytree': 0.9177729606891201, 'min_child_weight': 8, 'gamma': 2.711232093386701, 'reg_alpha': 1.2550889619225139e-06, 'reg_lambda': 7.257223045709271e-08, 'max_delta_step': 5}. Best is trial 5 with value: 0.5558408215661104.

Best trial: 5. Best value: 0.555841:  10%|█         | 5/50 [01:10<08:25, 11.23s/it]

[I 2025-12-02 18:38:45,884] Trial 2 finished with value: 0.15789473684210525 and parameters: {'max_depth': 3, 'learning_rate': 0.06662347250978216, 'n_estimators': 1422, 'subsample': 0.7915060008238642, 'colsample_bytree': 0.5931494046373491, 'min_child_weight': 10, 'gamma': 4.683791443504195, 'reg_alpha': 2.0823454339821684e-08, 'reg_lambda': 1.259757951932471e-06, 'max_delta_step': 4}. Best is trial 5 with value: 0.5558408215661104.

Best trial: 5. Best value: 0.555841:  12%|█▏        | 6/50 [01:23<08:51, 12.09s/it]

[I 2025-12-02 18:38:59,635] Trial 7 finished with value: 0.3575096277278562 and parameters: {'max_depth': 10, 'learning_rate': 0.03574169818594844, 'n_estimators': 269, 'subsample': 0.7295983024692068, 'colsample_bytree': 0.8318166788010048, 'min_child_weight': 5, 'gamma': 0.6265869511028904, 'reg_alpha': 0.024182200768462458, 'reg_lambda': 0.0002783354613353193, 'max_delta_step': 8}. Best is trial 5 with value: 0.5558408215661104.

Best trial: 5. Best value: 0.555841:  14%|█▍        | 7/50 [01:39<09:29, 13.25s/it]

[I 2025-12-02 18:39:15,279] Trial 6 finished with value: 0.3453145057766367 and parameters: {'max_depth': 10, 'learning_rate': 0.018566141132658528, 'n_estimators': 687, 'subsample': 0.7991341878647171, 'colsample_bytree': 0.5725520835519755, 'min_child_weight': 7, 'gamma': 0.28077550664321327, 'reg_alpha': 0.32846360233387606, 'reg_lambda': 5.109304767554072e-08, 'max_delta_step': 1}. Best is trial 5 with value: 0.5558408215661104.

Best trial: 5. Best value: 0.555841:  16%|█▌        | 8/50 [01:50<08:49, 12.61s/it]

[I 2025-12-02 18:39:26,525] Trial 4 finished with value: 0.33119383825417203 and parameters: {'max_depth': 6, 'learning_rate': 0.028277410157512624, 'n_estimators': 1159, 'subsample': 0.7010472996308588, 'colsample_bytree': 0.8663481956165363, 'min_child_weight': 4, 'gamma': 0.8675170533995025, 'reg_alpha': 1.9306055126168678e-07, 'reg_lambda': 1.5779979885460695e-05, 'max_delta_step': 4}. Best is trial 5 with value: 0.5558408215661104.

Best trial: 5. Best value: 0.555841:  18%|█▊        | 9/50 [02:00<08:00, 11.71s/it]

[I 2025-12-02 18:39:36,247] Trial 8 finished with value: 0.4120667522464698 and parameters: {'max_depth': 5, 'learning_rate': 0.05668960705102508, 'n_estimators': 1032, 'subsample': 0.8097905260124505, 'colsample_bytree': 0.6362690921679035, 'min_child_weight': 8, 'gamma': 3.921431382895228, 'reg_alpha': 0.0005773216522209524, 'reg_lambda': 3.5119996003840463e-06, 'max_delta_step': 7}. Best is trial 5 with value: 0.5558408215661104.

Best trial: 5. Best value: 0.555841:  20%|██        | 10/50 [02:21<09:37, 14.44s/it]

[I 2025-12-02 18:39:56,786] Trial 9 finished with value: 0.3575096277278562 and parameters: {'max_depth': 8, 'learning_rate': 0.040305371749663935, 'n_estimators': 1001, 'subsample': 0.7993090704483656, 'colsample_bytree': 0.9464130782061195, 'min_child_weight': 7, 'gamma': 2.718818345869854, 'reg_alpha': 0.02058927642872112, 'reg_lambda': 4.608828437791894e-08, 'max_delta_step': 1}. Best is trial 5 with value: 0.5558408215661104.

Best trial: 5. Best value: 0.555841:  22%|██▏       | 11/50 [02:25<07:25, 11.42s/it]

[I 2025-12-02 18:40:01,379] Trial 10 finished with value: 0.40821566110397944 and parameters: {'max_depth': 4, 'learning_rate': 0.1988505330190021, 'n_estimators': 923, 'subsample': 0.5957281102072618, 'colsample_bytree': 0.5856833149601907, 'min_child_weight': 6, 'gamma': 2.1347554692652473, 'reg_alpha': 1.5395556972289397e-07, 'reg_lambda': 5.597562358443834, 'max_delta_step': 0}. Best is trial 5 with value: 0.5558408215661104.

Best trial: 5. Best value: 0.555841:  24%|██▍       | 12/50 [02:26<05:05,  8.05s/it]

[I 2025-12-02 18:40:01,711] Trial 13 pruned.

Best trial: 5. Best value: 0.555841:  26%|██▌       | 13/50 [02:28<03:50,  6.24s/it]

[I 2025-12-02 18:40:03,800] Trial 14 pruned.

Best trial: 5. Best value: 0.555841:  28%|██▊       | 14/50 [02:50<06:36, 11.02s/it]

[I 2025-12-02 18:40:25,858] Trial 15 finished with value: 0.47368421052631576 and parameters: {'max_depth': 5, 'learning_rate': 0.11279991217578124, 'n_estimators': 455, 'subsample': 0.5092248274073484, 'colsample_bytree': 0.7283724348457082, 'min_child_weight': 9, 'gamma': 3.203517400697276, 'reg_alpha': 0.00010931213832379376, 'reg_lambda': 0.011054907218437895, 'max_delta_step': 3}. Best is trial 5 with value: 0.5558408215661104.

Best trial: 5. Best value: 0.555841:  30%|███       | 15/50 [02:53<05:07,  8.78s/it]

[I 2025-12-02 18:40:29,441] Trial 16 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.010956797677446839, 'n_estimators': 483, 'subsample': 0.5169105217631437, 'colsample_bytree': 0.707208872244022, 'min_child_weight': 10, 'gamma': 3.4835654593947827, 'reg_alpha': 0.0013596228393019235, 'reg_lambda': 0.004037043536052211, 'max_delta_step': 6}. Best is trial 5 with value: 0.5558408215661104.

Best trial: 5. Best value: 0.555841:  32%|███▏      | 16/50 [02:53<03:30,  6.20s/it]

[I 2025-12-02 18:40:29,642] Trial 11 finished with value: 0.3575096277278562 and parameters: {'max_depth': 9, 'learning_rate': 0.16915077194483466, 'n_estimators': 1100, 'subsample': 0.8374177003276961, 'colsample_bytree': 0.5456010521100583, 'min_child_weight': 3, 'gamma': 2.8739317211859987, 'reg_alpha': 0.0076419255126079205, 'reg_lambda': 7.797534759898744e-07, 'max_delta_step': 2}. Best is trial 5 with value: 0.5558408215661104.

Best trial: 5. Best value: 0.555841:  34%|███▍      | 17/50 [03:05<04:13,  7.69s/it]

[I 2025-12-02 18:40:40,797] Trial 19 pruned.

Best trial: 5. Best value: 0.555841:  36%|███▌      | 18/50 [03:06<03:02,  5.69s/it]

[I 2025-12-02 18:40:41,838] Trial 12 finished with value: 0.5 and parameters: {'max_depth': 4, 'learning_rate': 0.017618956045586328, 'n_estimators': 1307, 'subsample': 0.5227156523218328, 'colsample_bytree': 0.7318359031662295, 'min_child_weight': 9, 'gamma': 4.095945019065214, 'reg_alpha': 4.992114918127373e-05, 'reg_lambda': 0.004251580720474714, 'max_delta_step': 4}. Best is trial 5 with value: 0.5558408215661104.

Best trial: 5. Best value: 0.555841:  38%|███▊      | 19/50 [03:46<08:15, 15.98s/it]

[I 2025-12-02 18:41:21,773] Trial 20 finished with value: 0.3453145057766367 and parameters: {'max_depth': 4, 'learning_rate': 0.0782584969048352, 'n_estimators': 811, 'subsample': 0.6405440506934755, 'colsample_bytree': 0.6516020016381411, 'min_child_weight': 6, 'gamma': 1.6278093135987588, 'reg_alpha': 2.219596501092783e-06, 'reg_lambda': 0.511929381523942, 'max_delta_step': 6}. Best is trial 5 with value: 0.5558408215661104.

Best trial: 21. Best value: 0.568036:  40%|████      | 20/50 [03:47<05:46, 11.56s/it]

[I 2025-12-02 18:41:23,028] Trial 21 finished with value: 0.5680359435173299 and parameters: {'max_depth': 7, 'learning_rate': 0.08252734801797341, 'n_estimators': 797, 'subsample': 0.8927530382783784, 'colsample_bytree': 0.5008565700111157, 'min_child_weight': 6, 'gamma': 1.740756193061126, 'reg_alpha': 7.296352314443867, 'reg_lambda': 0.7575144164318468, 'max_delta_step': 7}. Best is trial 21 with value: 0.5680359435173299.

Best trial: 21. Best value: 0.568036:  42%|████▏     | 21/50 [03:52<04:35,  9.50s/it]

[I 2025-12-02 18:41:27,738] Trial 23 pruned.

Best trial: 21. Best value: 0.568036:  44%|████▍     | 22/50 [04:00<04:14,  9.11s/it]

[I 2025-12-02 18:41:35,929] Trial 18 finished with value: 0.5417201540436457 and parameters: {'max_depth': 5, 'learning_rate': 0.08173848178159057, 'n_estimators': 1252, 'subsample': 0.6240117535124927, 'colsample_bytree': 0.5036459081140574, 'min_child_weight': 3, 'gamma': 4.90739379063862, 'reg_alpha': 6.103886420464997, 'reg_lambda': 0.00046699198237799047, 'max_delta_step': 2}. Best is trial 21 with value: 0.5680359435173299.

Best trial: 21. Best value: 0.568036:  46%|████▌     | 23/50 [04:04<03:29,  7.78s/it]

[I 2025-12-02 18:41:40,597] Trial 17 finished with value: 0.5680359435173299 and parameters: {'max_depth': 3, 'learning_rate': 0.010103962114351201, 'n_estimators': 1311, 'subsample': 0.6287574813573493, 'colsample_bytree': 0.5041312926006584, 'min_child_weight': 3, 'gamma': 4.170714888730361, 'reg_alpha': 6.61993836903986, 'reg_lambda': 0.0022544881665226453, 'max_delta_step': 7}. Best is trial 21 with value: 0.5680359435173299.

Best trial: 21. Best value: 0.568036:  48%|████▊     | 24/50 [04:18<04:09,  9.60s/it]

[I 2025-12-02 18:41:54,465] Trial 22 finished with value: 0.5539152759948652 and parameters: {'max_depth': 7, 'learning_rate': 0.026780802852223923, 'n_estimators': 537, 'subsample': 0.8797638226505791, 'colsample_bytree': 0.9216837987510583, 'min_child_weight': 7, 'gamma': 3.67685433058701, 'reg_alpha': 4.719227750066526, 'reg_lambda': 1.6152456218054072e-08, 'max_delta_step': 2}. Best is trial 21 with value: 0.5680359435173299.

Best trial: 21. Best value: 0.568036:  50%|█████     | 25/50 [04:19<02:56,  7.07s/it]

[I 2025-12-02 18:41:55,617] Trial 26 pruned.

Best trial: 21. Best value: 0.568036:  52%|█████▏    | 26/50 [04:27<02:51,  7.15s/it]

[I 2025-12-02 18:42:02,962] Trial 28 pruned.

Best trial: 24. Best value: 0.606547:  54%|█████▍    | 27/50 [04:34<02:48,  7.31s/it]

[I 2025-12-02 18:42:10,657] Trial 24 finished with value: 0.6065468549422337 and parameters: {'max_depth': 6, 'learning_rate': 0.08648257801971701, 'n_estimators': 860, 'subsample': 0.8859436517614181, 'colsample_bytree': 0.6568619169329409, 'min_child_weight': 7, 'gamma': 2.2372964721198345, 'reg_alpha': 6.749771738762638, 'reg_lambda': 0.32069759727250113, 'max_delta_step': 7}. Best is trial 24 with value: 0.6065468549422337.

Best trial: 24. Best value: 0.606547:  56%|█████▌    | 28/50 [04:36<02:01,  5.51s/it]

[I 2025-12-02 18:42:11,932] Trial 29 pruned.

Best trial: 24. Best value: 0.606547:  58%|█████▊    | 29/50 [04:40<01:49,  5.21s/it]

[I 2025-12-02 18:42:16,449] Trial 27 pruned.

Best trial: 24. Best value: 0.606547:  60%|██████    | 30/50 [04:43<01:30,  4.50s/it]

[I 2025-12-02 18:42:19,304] Trial 31 pruned.

Best trial: 24. Best value: 0.606547:  62%|██████▏   | 31/50 [05:16<04:05, 12.94s/it]

[I 2025-12-02 18:42:51,945] Trial 25 finished with value: 0.5680359435173299 and parameters: {'max_depth': 6, 'learning_rate': 0.08923167468457313, 'n_estimators': 1462, 'subsample': 0.7502613551086049, 'colsample_bytree': 0.5020165446730479, 'min_child_weight': 2, 'gamma': 4.987473762991652, 'reg_alpha': 5.195225365978739, 'reg_lambda': 5.421913900117648, 'max_delta_step': 6}. Best is trial 24 with value: 0.6065468549422337.

Best trial: 24. Best value: 0.606547:  64%|██████▍   | 32/50 [05:22<03:14, 10.80s/it]

[I 2025-12-02 18:42:57,733] Trial 32 finished with value: 0.5943517329910142 and parameters: {'max_depth': 9, 'learning_rate': 0.14804803707952938, 'n_estimators': 805, 'subsample': 0.933071950683442, 'colsample_bytree': 0.5539722864740964, 'min_child_weight': 6, 'gamma': 1.3617038089231606, 'reg_alpha': 6.894435970860427, 'reg_lambda': 0.13938822047682925, 'max_delta_step': 9}. Best is trial 24 with value: 0.6065468549422337.

Best trial: 24. Best value: 0.606547:  66%|██████▌   | 33/50 [05:22<02:13,  7.83s/it]

[I 2025-12-02 18:42:58,646] Trial 30 finished with value: 0.46277278562259305 and parameters: {'max_depth': 8, 'learning_rate': 0.14681276254883202, 'n_estimators': 906, 'subsample': 0.953405871561264, 'colsample_bytree': 0.5379998069534306, 'min_child_weight': 4, 'gamma': 1.359852513412675, 'reg_alpha': 8.675273803158905, 'reg_lambda': 0.15499675800021512, 'max_delta_step': 8}. Best is trial 24 with value: 0.6065468549422337.

Best trial: 24. Best value: 0.606547:  68%|██████▊   | 34/50 [05:23<01:28,  5.56s/it]

[I 2025-12-02 18:42:58,911] Trial 33 finished with value: 0.46277278562259305 and parameters: {'max_depth': 9, 'learning_rate': 0.04707818158628708, 'n_estimators': 711, 'subsample': 0.9365041340805912, 'colsample_bytree': 0.5231531119709377, 'min_child_weight': 4, 'gamma': 1.888500302159501, 'reg_alpha': 7.21393166379836, 'reg_lambda': 0.9722252838649387, 'max_delta_step': 8}. Best is trial 24 with value: 0.6065468549422337.

Best trial: 24. Best value: 0.606547:  70%|███████   | 35/50 [05:28<01:21,  5.43s/it]

[I 2025-12-02 18:43:04,032] Trial 35 pruned.

Best trial: 24. Best value: 0.606547:  72%|███████▏  | 36/50 [05:28<00:55,  3.97s/it]

[I 2025-12-02 18:43:04,589] Trial 37 pruned.

Best trial: 24. Best value: 0.606547:  74%|███████▍  | 37/50 [05:29<00:38,  2.96s/it]

[I 2025-12-02 18:43:05,211] Trial 36 pruned.

Best trial: 24. Best value: 0.606547:  76%|███████▌  | 38/50 [06:08<02:45, 13.79s/it]

[I 2025-12-02 18:43:44,262] Trial 38 finished with value: 0.38189987163029526 and parameters: {'max_depth': 9, 'learning_rate': 0.27971763315882653, 'n_estimators': 787, 'subsample': 0.9816293970947488, 'colsample_bytree': 0.6061548098544863, 'min_child_weight': 7, 'gamma': 2.004148255288134, 'reg_alpha': 1.206296861647983, 'reg_lambda': 0.0864032608778682, 'max_delta_step': 9}. Best is trial 24 with value: 0.6065468549422337.

Best trial: 24. Best value: 0.606547:  78%|███████▊  | 39/50 [06:09<01:49,  9.95s/it]

[I 2025-12-02 18:43:45,258] Trial 39 finished with value: 0.41014120667522463 and parameters: {'max_depth': 7, 'learning_rate': 0.2638177822104161, 'n_estimators': 787, 'subsample': 0.995636371609371, 'colsample_bytree': 0.6777679075411996, 'min_child_weight': 7, 'gamma': 1.9566733276531325, 'reg_alpha': 1.2647012213228832, 'reg_lambda': 0.10198428761936765, 'max_delta_step': 9}. Best is trial 24 with value: 0.6065468549422337.

Best trial: 24. Best value: 0.606547:  80%|████████  | 40/50 [06:13<01:22,  8.27s/it]

[I 2025-12-02 18:43:49,603] Trial 40 finished with value: 0.3838254172015404 and parameters: {'max_depth': 7, 'learning_rate': 0.06809505967108058, 'n_estimators': 791, 'subsample': 0.9992101207562685, 'colsample_bytree': 0.6793859894859304, 'min_child_weight': 7, 'gamma': 2.445484656861946, 'reg_alpha': 1.0839388565658896, 'reg_lambda': 0.08399652802794824, 'max_delta_step': 9}. Best is trial 24 with value: 0.6065468549422337.

Best trial: 24. Best value: 0.606547:  82%|████████▏ | 41/50 [06:18<01:04,  7.19s/it]

[I 2025-12-02 18:43:54,294] Trial 42 pruned.

Best trial: 24. Best value: 0.606547:  84%|████████▍ | 42/50 [06:20<00:45,  5.66s/it]

[I 2025-12-02 18:43:56,359] Trial 41 pruned.

Best trial: 24. Best value: 0.606547:  86%|████████▌ | 43/50 [06:23<00:33,  4.80s/it]

[I 2025-12-02 18:43:59,175] Trial 43 pruned.

Best trial: 24. Best value: 0.606547:  88%|████████▊ | 44/50 [06:32<00:36,  6.01s/it]

[I 2025-12-02 18:44:07,997] Trial 44 pruned.

Best trial: 24. Best value: 0.606547:  90%|█████████ | 45/50 [06:34<00:24,  4.83s/it]

[I 2025-12-02 18:44:10,064] Trial 45 pruned.

Best trial: 24. Best value: 0.606547:  92%|█████████▏| 46/50 [06:36<00:16,  4.05s/it]

[I 2025-12-02 18:44:12,314] Trial 46 pruned.
[I 2025-12-02 18:44:12,343] Trial 34 finished with value: 0.3979460847240051 and parameters: {'max_depth': 7, 'learning_rate': 0.046550265944970526, 'n_estimators': 1372, 'subsample': 0.9161249661421154, 'colsample_bytree': 0.525994625532051, 'min_child_weight': 2, 'gamma': 4.598074314743573, 'reg_alpha': 8.338200826122819, 'reg_lambda': 1.7395587132793735, 'max_delta_step': 8}. Best is trial 24 with value: 0.6065468549422337.

Best trial: 24. Best value: 0.606547:  96%|█████████▌| 48/50 [06:43<00:07,  3.71s/it]

[I 2025-12-02 18:44:18,938] Trial 49 pruned.

Best trial: 24. Best value: 0.606547:  98%|█████████▊| 49/50 [06:44<00:03,  3.09s/it]

[I 2025-12-02 18:44:20,146] Trial 48 pruned.

Best trial: 24. Best value: 0.606547: 100%|██████████| 50/50 [07:18<00:00,  8.78s/it]

[I 2025-12-02 18:44:54,511] Trial 47 finished with value: 0.5821566110397947 and parameters: {'max_depth': 3, 'learning_rate': 0.09966692242486982, 'n_estimators': 1398, 'subsample': 0.7694162637234615, 'colsample_bytree': 0.5174779444623681, 'min_child_weight': 2, 'gamma': 4.535192525060007, 'reg_alpha': 8.705036709495838, 'reg_lambda': 2.5299253738153094, 'max_delta_step': 7}. Best is trial 24 with value: 0.6065468549422337.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.606547                    0.65           0.7

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.288675               0.8               0.5        50          60

   test_size
0         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.606547                    0.65           0.7

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.288675               0.8               0.5        50          60

   test_size
0         15

In [ ]:
# Temporal embedings
datasets = task_temp_dfs_ad_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    #    scoring="balanced_accuracy",     # or "roc_auc"
    scoring="balanced_accuracy",      
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_temp_ad_hc_extended{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param="emb_",
)
print(summary)

[I 2025-12-02 18:44:57,892] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.320924:   2%|▏         | 1/50 [00:17<14:17, 17.49s/it]

[I 2025-12-02 18:45:15,374] Trial 3 finished with value: 0.3209242618741977 and parameters: {'max_depth': 5, 'learning_rate': 0.19280791411388543, 'n_estimators': 249, 'subsample': 0.9539749100516606, 'colsample_bytree': 0.8990611506671865, 'min_child_weight': 5, 'gamma': 2.35729244688071, 'reg_alpha': 0.0015490786840469083, 'reg_lambda': 7.925724601735968e-06, 'max_delta_step': 6}. Best is trial 3 with value: 0.3209242618741977.

Best trial: 0. Best value: 0.434531:   4%|▍         | 2/50 [00:42<17:18, 21.64s/it]

[I 2025-12-02 18:45:39,923] Trial 0 finished with value: 0.4345314505776637 and parameters: {'max_depth': 4, 'learning_rate': 0.010047348926516337, 'n_estimators': 271, 'subsample': 0.9260351823192214, 'colsample_bytree': 0.9990506920354647, 'min_child_weight': 4, 'gamma': 1.3604395597418533, 'reg_alpha': 2.776358117925827e-08, 'reg_lambda': 0.005930918876805417, 'max_delta_step': 2}. Best is trial 0 with value: 0.4345314505776637.

Best trial: 2. Best value: 0.440308:   6%|▌         | 3/50 [00:55<14:01, 17.90s/it]

[I 2025-12-02 18:45:53,363] Trial 2 finished with value: 0.44030808729139925 and parameters: {'max_depth': 3, 'learning_rate': 0.02266446968516495, 'n_estimators': 1076, 'subsample': 0.641539367710919, 'colsample_bytree': 0.9147323647006848, 'min_child_weight': 7, 'gamma': 0.3089677788553835, 'reg_alpha': 2.2266740014706934e-08, 'reg_lambda': 3.245232900683283e-07, 'max_delta_step': 5}. Best is trial 2 with value: 0.44030808729139925.

Best trial: 1. Best value: 0.489089:   8%|▊         | 4/50 [01:06<11:34, 15.09s/it]

[I 2025-12-02 18:46:04,145] Trial 1 finished with value: 0.48908857509627723 and parameters: {'max_depth': 4, 'learning_rate': 0.17807377765567298, 'n_estimators': 1395, 'subsample': 0.5040630650408802, 'colsample_bytree': 0.9201264651606728, 'min_child_weight': 6, 'gamma': 0.9541605840918016, 'reg_alpha': 0.001385508851980187, 'reg_lambda': 2.156922063315216e-06, 'max_delta_step': 4}. Best is trial 1 with value: 0.48908857509627723.

Best trial: 1. Best value: 0.489089:  10%|█         | 5/50 [01:21<11:19, 15.09s/it]

[I 2025-12-02 18:46:19,220] Trial 4 finished with value: 0.46277278562259305 and parameters: {'max_depth': 4, 'learning_rate': 0.23850066677501866, 'n_estimators': 1241, 'subsample': 0.8352489075004192, 'colsample_bytree': 0.9786247938992607, 'min_child_weight': 4, 'gamma': 0.7135764832344155, 'reg_alpha': 3.19528719138823e-08, 'reg_lambda': 4.235869955755565e-07, 'max_delta_step': 9}. Best is trial 1 with value: 0.48908857509627723.

Best trial: 1. Best value: 0.489089:  12%|█▏        | 6/50 [01:46<13:38, 18.60s/it]

[I 2025-12-02 18:46:44,651] Trial 6 finished with value: 0.3735558408215661 and parameters: {'max_depth': 4, 'learning_rate': 0.06405050094217159, 'n_estimators': 918, 'subsample': 0.8583352948126648, 'colsample_bytree': 0.5613157666199429, 'min_child_weight': 8, 'gamma': 0.5145657305020945, 'reg_alpha': 4.8637285474620855, 'reg_lambda': 7.689070315409822e-05, 'max_delta_step': 3}. Best is trial 1 with value: 0.48908857509627723.
[I 2025-12-02 18:46:44,667] Trial 5 finished with value: 0.43645699614890887 and parameters: {'max_depth': 3, 'learning_rate': 0.04610442110296871, 'n_estimators': 1135, 'subsample': 0.7627699232696084, 'colsample_bytree': 0.7391247127488703, 'min_child_weight': 5, 'gamma': 4.748139723087953, 'reg_alpha': 0.7546262515504791, 'reg_lambda': 8.724544323830622e-08, 'max_delta_step': 3}. Best is trial 1 with value: 0.48908857509627723.

Best trial: 1. Best value: 0.489089:  16%|█▌        | 8/50 [01:50<07:10, 10.26s/it]

[I 2025-12-02 18:46:47,993] Trial 8 finished with value: 0.3960205391527599 and parameters: {'max_depth': 5, 'learning_rate': 0.19216910357991537, 'n_estimators': 428, 'subsample': 0.7153354322669355, 'colsample_bytree': 0.9111879739305347, 'min_child_weight': 3, 'gamma': 4.561459923550316, 'reg_alpha': 3.5551586391643285e-06, 'reg_lambda': 0.00712348244888351, 'max_delta_step': 3}. Best is trial 1 with value: 0.48908857509627723.

Best trial: 1. Best value: 0.489089:  18%|█▊        | 9/50 [02:08<08:32, 12.49s/it]

[I 2025-12-02 18:47:06,830] Trial 7 finished with value: 0.23684210526315788 and parameters: {'max_depth': 8, 'learning_rate': 0.035593704360835726, 'n_estimators': 1308, 'subsample': 0.5968903655981469, 'colsample_bytree': 0.7702123023683737, 'min_child_weight': 9, 'gamma': 3.574564623611672, 'reg_alpha': 0.0029093038372948435, 'reg_lambda': 0.11312190730462736, 'max_delta_step': 4}. Best is trial 1 with value: 0.48908857509627723.

Best trial: 1. Best value: 0.489089:  20%|██        | 10/50 [02:16<07:21, 11.05s/it]

[I 2025-12-02 18:47:14,001] Trial 11 finished with value: 0.48908857509627723 and parameters: {'max_depth': 6, 'learning_rate': 0.03529129202136556, 'n_estimators': 354, 'subsample': 0.5278081780267212, 'colsample_bytree': 0.948463473248831, 'min_child_weight': 5, 'gamma': 2.855931751448014, 'reg_alpha': 2.9774005034750943, 'reg_lambda': 2.165283420565354e-08, 'max_delta_step': 8}. Best is trial 1 with value: 0.48908857509627723.

Best trial: 1. Best value: 0.489089:  22%|██▏       | 11/50 [02:21<06:03,  9.33s/it]

[I 2025-12-02 18:47:18,889] Trial 9 pruned.

Best trial: 1. Best value: 0.489089:  24%|██▍       | 12/50 [02:24<04:52,  7.70s/it]

[I 2025-12-02 18:47:22,497] Trial 13 pruned.

Best trial: 1. Best value: 0.489089:  26%|██▌       | 13/50 [02:25<03:37,  5.87s/it]

[I 2025-12-02 18:47:23,874] Trial 12 pruned.

Best trial: 10. Best value: 0.5:  28%|██▊       | 14/50 [02:34<03:54,  6.51s/it]

[I 2025-12-02 18:47:31,941] Trial 10 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.09527750900963101, 'n_estimators': 952, 'subsample': 0.5028240587596626, 'colsample_bytree': 0.9056726863453437, 'min_child_weight': 10, 'gamma': 1.3842953085826504, 'reg_alpha': 0.0009891848052257777, 'reg_lambda': 0.011520214144229832, 'max_delta_step': 3}. Best is trial 10 with value: 0.5.

Best trial: 10. Best value: 0.5:  30%|███       | 15/50 [02:36<03:03,  5.26s/it]

[I 2025-12-02 18:47:34,193] Trial 15 pruned.

Best trial: 10. Best value: 0.5:  32%|███▏      | 16/50 [02:37<02:17,  4.06s/it]

[I 2025-12-02 18:47:35,403] Trial 16 pruned.

Best trial: 10. Best value: 0.5:  34%|███▍      | 17/50 [02:45<02:50,  5.17s/it]

[I 2025-12-02 18:47:43,189] Trial 17 pruned.

Best trial: 10. Best value: 0.5:  36%|███▌      | 18/50 [02:46<02:05,  3.94s/it]

[I 2025-12-02 18:47:44,225] Trial 19 pruned.

Best trial: 10. Best value: 0.5:  38%|███▊      | 19/50 [03:15<05:55, 11.48s/it]

[I 2025-12-02 18:48:13,430] Trial 21 pruned.

Best trial: 10. Best value: 0.5:  40%|████      | 20/50 [03:23<05:17, 10.57s/it]

[I 2025-12-02 18:48:21,867] Trial 18 finished with value: 0.34210526315789475 and parameters: {'max_depth': 8, 'learning_rate': 0.10677737789049756, 'n_estimators': 975, 'subsample': 0.6508652756864826, 'colsample_bytree': 0.6447276902719219, 'min_child_weight': 10, 'gamma': 0.9872956844744238, 'reg_alpha': 0.0001226293684747835, 'reg_lambda': 4.522400458367673e-05, 'max_delta_step': 1}. Best is trial 10 with value: 0.5.

Best trial: 10. Best value: 0.5:  42%|████▏     | 21/50 [03:25<03:45,  7.77s/it]

[I 2025-12-02 18:48:23,077] Trial 22 pruned.

Best trial: 10. Best value: 0.5:  44%|████▍     | 22/50 [03:29<03:11,  6.83s/it]

[I 2025-12-02 18:48:27,723] Trial 24 pruned.

Best trial: 10. Best value: 0.5:  46%|████▌     | 23/50 [03:32<02:34,  5.72s/it]

[I 2025-12-02 18:48:30,849] Trial 20 finished with value: 0.5 and parameters: {'max_depth': 6, 'learning_rate': 0.12479058739541092, 'n_estimators': 957, 'subsample': 0.6002703522427767, 'colsample_bytree': 0.6659373171576403, 'min_child_weight': 10, 'gamma': 0.9860516489626514, 'reg_alpha': 0.00013661923495534214, 'reg_lambda': 0.0012666292931522748, 'max_delta_step': 1}. Best is trial 10 with value: 0.5.

Best trial: 10. Best value: 0.5:  48%|████▊     | 24/50 [03:33<01:51,  4.29s/it]

[I 2025-12-02 18:48:31,796] Trial 23 pruned.

Best trial: 10. Best value: 0.5:  50%|█████     | 25/50 [03:36<01:37,  3.90s/it]

[I 2025-12-02 18:48:34,790] Trial 25 pruned.

Best trial: 10. Best value: 0.5:  52%|█████▏    | 26/50 [03:38<01:16,  3.20s/it]

[I 2025-12-02 18:48:36,361] Trial 26 pruned.

Best trial: 10. Best value: 0.5:  54%|█████▍    | 27/50 [03:39<00:58,  2.55s/it]

[I 2025-12-02 18:48:37,395] Trial 27 pruned.

Best trial: 10. Best value: 0.5:  56%|█████▌    | 28/50 [03:46<01:23,  3.78s/it]

[I 2025-12-02 18:48:44,047] Trial 28 pruned.

Best trial: 10. Best value: 0.5:  58%|█████▊    | 29/50 [03:49<01:14,  3.55s/it]

[I 2025-12-02 18:48:47,037] Trial 30 pruned.

Best trial: 10. Best value: 0.5:  60%|██████    | 30/50 [03:53<01:16,  3.82s/it]

[I 2025-12-02 18:48:51,491] Trial 31 pruned.

Best trial: 10. Best value: 0.5:  62%|██████▏   | 31/50 [04:03<01:49,  5.75s/it]

[I 2025-12-02 18:49:01,759] Trial 14 finished with value: 0.48523748395378685 and parameters: {'max_depth': 7, 'learning_rate': 0.09857598687685785, 'n_estimators': 1500, 'subsample': 0.5268860696069256, 'colsample_bytree': 0.8256617697477544, 'min_child_weight': 1, 'gamma': 2.1825281944634645, 'reg_alpha': 0.0472590883900066, 'reg_lambda': 1.0430512273878612e-08, 'max_delta_step': 8}. Best is trial 10 with value: 0.5.

Best trial: 10. Best value: 0.5:  64%|██████▍   | 32/50 [04:09<01:41,  5.62s/it]

[I 2025-12-02 18:49:07,077] Trial 34 pruned.

Best trial: 10. Best value: 0.5:  66%|██████▌   | 33/50 [04:44<04:08, 14.64s/it]

[I 2025-12-02 18:49:42,764] Trial 29 finished with value: 0.4762516046213094 and parameters: {'max_depth': 9, 'learning_rate': 0.2971636829844309, 'n_estimators': 1500, 'subsample': 0.6924716398771011, 'colsample_bytree': 0.6971494781361266, 'min_child_weight': 9, 'gamma': 0.7368280725069813, 'reg_alpha': 0.0006810838733209365, 'reg_lambda': 0.03618133792164908, 'max_delta_step': 2}. Best is trial 10 with value: 0.5.

Best trial: 10. Best value: 0.5:  68%|██████▊   | 34/50 [05:00<03:58, 14.91s/it]

[I 2025-12-02 18:49:58,312] Trial 35 finished with value: 0.4749679075738126 and parameters: {'max_depth': 5, 'learning_rate': 0.011928109980856761, 'n_estimators': 538, 'subsample': 0.6143505881817521, 'colsample_bytree': 0.9911304639738838, 'min_child_weight': 4, 'gamma': 2.795894131518774, 'reg_alpha': 0.005703232190665935, 'reg_lambda': 0.00010515400179008691, 'max_delta_step': 6}. Best is trial 10 with value: 0.5.

Best trial: 10. Best value: 0.5:  70%|███████   | 35/50 [05:03<02:52, 11.48s/it]

[I 2025-12-02 18:50:01,772] Trial 37 pruned.

Best trial: 10. Best value: 0.5:  72%|███████▏  | 36/50 [05:08<02:12,  9.45s/it]

[I 2025-12-02 18:50:06,478] Trial 33 finished with value: 0.4608472400513479 and parameters: {'max_depth': 4, 'learning_rate': 0.011038184148266227, 'n_estimators': 766, 'subsample': 0.6095350722869213, 'colsample_bytree': 0.8060307541507319, 'min_child_weight': 3, 'gamma': 1.3333592066168023, 'reg_alpha': 4.391567188239088e-07, 'reg_lambda': 0.00299121192353322, 'max_delta_step': 3}. Best is trial 10 with value: 0.5.

Best trial: 10. Best value: 0.5:  74%|███████▍  | 37/50 [05:11<01:38,  7.54s/it]

[I 2025-12-02 18:50:09,563] Trial 36 pruned.

Best trial: 10. Best value: 0.5:  76%|███████▌  | 38/50 [05:14<01:12,  6.07s/it]

[I 2025-12-02 18:50:12,217] Trial 32 finished with value: 0.4871630295250321 and parameters: {'max_depth': 7, 'learning_rate': 0.01122830712695482, 'n_estimators': 917, 'subsample': 0.6157779247057484, 'colsample_bytree': 0.8030018343705104, 'min_child_weight': 3, 'gamma': 1.2720588335101475, 'reg_alpha': 3.742035345662477e-07, 'reg_lambda': 0.009203698446037042, 'max_delta_step': 3}. Best is trial 10 with value: 0.5.
[I 2025-12-02 18:50:12,228] Trial 39 pruned.

Best trial: 10. Best value: 0.5:  80%|████████  | 40/50 [05:23<00:53,  5.33s/it]

[I 2025-12-02 18:50:21,146] Trial 41 pruned.
[I 2025-12-02 18:50:21,183] Trial 42 pruned.

Best trial: 10. Best value: 0.5:  84%|████████▍ | 42/50 [05:24<00:27,  3.44s/it]

[I 2025-12-02 18:50:22,297] Trial 40 pruned.

Best trial: 10. Best value: 0.5:  86%|████████▌ | 43/50 [05:36<00:37,  5.29s/it]

[I 2025-12-02 18:50:34,085] Trial 44 pruned.

Best trial: 10. Best value: 0.5:  88%|████████▊ | 44/50 [05:50<00:44,  7.47s/it]

[I 2025-12-02 18:50:48,451] Trial 43 pruned.

Best trial: 10. Best value: 0.5:  90%|█████████ | 45/50 [06:04<00:45,  9.02s/it]

[I 2025-12-02 18:51:01,995] Trial 38 finished with value: 0.4486521181001284 and parameters: {'max_depth': 6, 'learning_rate': 0.03148889494665026, 'n_estimators': 763, 'subsample': 0.5248282388637682, 'colsample_bytree': 0.7949841028489149, 'min_child_weight': 3, 'gamma': 1.2182132220050224, 'reg_alpha': 1.5915831164337828, 'reg_lambda': 0.5881931680364405, 'max_delta_step': 4}. Best is trial 10 with value: 0.5.

Best trial: 10. Best value: 0.5:  92%|█████████▏| 46/50 [06:10<00:33,  8.44s/it]

[I 2025-12-02 18:51:08,852] Trial 45 finished with value: 0.47304236200256744 and parameters: {'max_depth': 8, 'learning_rate': 0.23180916449612832, 'n_estimators': 946, 'subsample': 0.5217668071659244, 'colsample_bytree': 0.9266908013604778, 'min_child_weight': 2, 'gamma': 1.2223209222286724, 'reg_alpha': 1.2050009286707106e-07, 'reg_lambda': 0.009870652673874167, 'max_delta_step': 3}. Best is trial 10 with value: 0.5.

Best trial: 10. Best value: 0.5:  94%|█████████▍| 47/50 [06:13<00:20,  6.90s/it]

[I 2025-12-02 18:51:11,715] Trial 48 pruned.

Best trial: 10. Best value: 0.5:  96%|█████████▌| 48/50 [06:24<00:15,  7.92s/it]

[I 2025-12-02 18:51:22,224] Trial 49 pruned.

Best trial: 10. Best value: 0.5:  98%|█████████▊| 49/50 [06:46<00:11, 11.91s/it]

[I 2025-12-02 18:51:43,989] Trial 46 finished with value: 0.47304236200256744 and parameters: {'max_depth': 7, 'learning_rate': 0.014181322061628488, 'n_estimators': 834, 'subsample': 0.5385588723850848, 'colsample_bytree': 0.9167749239334939, 'min_child_weight': 2, 'gamma': 1.3020258698087699, 'reg_alpha': 1.1666036837183259e-07, 'reg_lambda': 5.579797823271656e-07, 'max_delta_step': 3}. Best is trial 10 with value: 0.5.

Best trial: 10. Best value: 0.5: 100%|██████████| 50/50 [06:49<00:00,  8.20s/it]

[I 2025-12-02 18:51:47,738] Trial 47 pruned.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\tenNovy\miniconda3\envs\dolphin\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo            0.5                     0.5           0.5

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0       0.0               1.0               0.0        50          60

   test_size
0         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo            0.5                     0.5           0.5

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0       0.0               1.0               0.0        50          60

   test_size
0         15

In [ ]:

# Combined embedings
datasets = task_comb_dfs_ad_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_combined_ad_hc_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param="emb_",
)
print(summary)

[I 2025-12-02 18:51:50,241] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.473042:   2%|▏         | 1/50 [01:02<51:16, 62.79s/it]

[I 2025-12-02 18:52:53,021] Trial 0 finished with value: 0.47304236200256744 and parameters: {'max_depth': 8, 'learning_rate': 0.2326817786954312, 'n_estimators': 721, 'subsample': 0.7231597609833884, 'colsample_bytree': 0.535609366715359, 'min_child_weight': 2, 'gamma': 4.892986363630392, 'reg_alpha': 7.369235297551141e-06, 'reg_lambda': 1.0779739768854907e-06, 'max_delta_step': 6}. Best is trial 0 with value: 0.47304236200256744.

Best trial: 0. Best value: 0.473042:   4%|▍         | 2/50 [01:05<22:08, 27.67s/it]

[I 2025-12-02 18:52:56,115] Trial 1 finished with value: 0.23170731707317074 and parameters: {'max_depth': 7, 'learning_rate': 0.02668486385806186, 'n_estimators': 1061, 'subsample': 0.9563939313033589, 'colsample_bytree': 0.5001526999573567, 'min_child_weight': 10, 'gamma': 1.6607886224570305, 'reg_alpha': 0.24542208403792168, 'reg_lambda': 0.0014018836927912248, 'max_delta_step': 3}. Best is trial 0 with value: 0.47304236200256744.

Best trial: 3. Best value: 0.521823:   6%|▌         | 3/50 [01:15<15:18, 19.53s/it]

[I 2025-12-02 18:53:05,959] Trial 3 finished with value: 0.5218228498074454 and parameters: {'max_depth': 9, 'learning_rate': 0.057779660079713406, 'n_estimators': 920, 'subsample': 0.6088361392094466, 'colsample_bytree': 0.8023626012164602, 'min_child_weight': 3, 'gamma': 1.8910871647189187, 'reg_alpha': 7.643379228320103e-07, 'reg_lambda': 2.61631615995735e-05, 'max_delta_step': 9}. Best is trial 3 with value: 0.5218228498074454.

Best trial: 3. Best value: 0.521823:   8%|▊         | 4/50 [01:26<12:23, 16.16s/it]

[I 2025-12-02 18:53:16,942] Trial 4 finished with value: 0.48523748395378685 and parameters: {'max_depth': 3, 'learning_rate': 0.07199577324692019, 'n_estimators': 238, 'subsample': 0.9811716033995781, 'colsample_bytree': 0.5774852931887874, 'min_child_weight': 7, 'gamma': 1.2309414749222531, 'reg_alpha': 0.07907744333503076, 'reg_lambda': 1.554253551361503, 'max_delta_step': 4}. Best is trial 3 with value: 0.5218228498074454.

Best trial: 3. Best value: 0.521823:  10%|█         | 5/50 [01:29<08:37, 11.51s/it]

[I 2025-12-02 18:53:20,196] Trial 2 finished with value: 0.4345314505776637 and parameters: {'max_depth': 3, 'learning_rate': 0.019116074889230266, 'n_estimators': 1181, 'subsample': 0.9562206140217422, 'colsample_bytree': 0.7918914649333744, 'min_child_weight': 8, 'gamma': 0.5423542305817602, 'reg_alpha': 8.888262425236933e-06, 'reg_lambda': 0.0003838544007334104, 'max_delta_step': 3}. Best is trial 3 with value: 0.5218228498074454.

Best trial: 3. Best value: 0.521823:  12%|█▏        | 6/50 [01:43<08:59, 12.26s/it]

[I 2025-12-02 18:53:33,932] Trial 5 finished with value: 0.5006418485237484 and parameters: {'max_depth': 4, 'learning_rate': 0.04335926111084871, 'n_estimators': 563, 'subsample': 0.7654520206822246, 'colsample_bytree': 0.6642384173885358, 'min_child_weight': 9, 'gamma': 4.11941139786942, 'reg_alpha': 8.653731697976379e-07, 'reg_lambda': 1.350611467067789e-07, 'max_delta_step': 3}. Best is trial 3 with value: 0.5218228498074454.

Best trial: 3. Best value: 0.521823:  14%|█▍        | 7/50 [02:17<13:50, 19.32s/it]

[I 2025-12-02 18:54:07,771] Trial 8 finished with value: 0.4467265725288832 and parameters: {'max_depth': 5, 'learning_rate': 0.20150844149416933, 'n_estimators': 696, 'subsample': 0.6386891879567621, 'colsample_bytree': 0.8502502469825883, 'min_child_weight': 6, 'gamma': 3.412678596538944, 'reg_alpha': 1.814835015675965, 'reg_lambda': 3.4354324066691697e-07, 'max_delta_step': 2}. Best is trial 3 with value: 0.5218228498074454.

Best trial: 3. Best value: 0.521823:  16%|█▌        | 8/50 [02:21<10:01, 14.32s/it]

[I 2025-12-02 18:54:11,382] Trial 6 finished with value: 0.5218228498074454 and parameters: {'max_depth': 10, 'learning_rate': 0.10410622828524851, 'n_estimators': 766, 'subsample': 0.8497403817948654, 'colsample_bytree': 0.7170015897857004, 'min_child_weight': 2, 'gamma': 0.1534659196445909, 'reg_alpha': 1.7474196854844402e-05, 'reg_lambda': 6.28708085328334e-07, 'max_delta_step': 1}. Best is trial 3 with value: 0.5218228498074454.

Best trial: 3. Best value: 0.521823:  18%|█▊        | 9/50 [02:31<08:50, 12.93s/it]

[I 2025-12-02 18:54:21,259] Trial 7 finished with value: 0.5 and parameters: {'max_depth': 3, 'learning_rate': 0.14542592915825253, 'n_estimators': 1060, 'subsample': 0.512283355395071, 'colsample_bytree': 0.5599913879284063, 'min_child_weight': 10, 'gamma': 2.502393958940629, 'reg_alpha': 2.7258447698199695, 'reg_lambda': 8.572536868864904e-06, 'max_delta_step': 2}. Best is trial 3 with value: 0.5218228498074454.

Best trial: 9. Best value: 0.537869:  20%|██        | 10/50 [03:03<12:39, 19.00s/it]

[I 2025-12-02 18:54:53,838] Trial 9 finished with value: 0.5378690629011553 and parameters: {'max_depth': 10, 'learning_rate': 0.17857456263921126, 'n_estimators': 1320, 'subsample': 0.9338815387688049, 'colsample_bytree': 0.6626859965644591, 'min_child_weight': 8, 'gamma': 0.0565787296604614, 'reg_alpha': 2.8319411724266e-07, 'reg_lambda': 0.1346261130143671, 'max_delta_step': 7}. Best is trial 9 with value: 0.5378690629011553.

Best trial: 9. Best value: 0.537869:  22%|██▏       | 11/50 [03:05<08:54, 13.71s/it]

[I 2025-12-02 18:54:55,556] Trial 10 pruned.

Best trial: 9. Best value: 0.537869:  24%|██▍       | 12/50 [03:05<06:05,  9.62s/it]

[I 2025-12-02 18:54:55,820] Trial 12 pruned.

Best trial: 9. Best value: 0.537869:  26%|██▌       | 13/50 [03:40<10:41, 17.33s/it]

[I 2025-12-02 18:55:30,892] Trial 11 pruned.

Best trial: 9. Best value: 0.537869:  28%|██▊       | 14/50 [03:57<10:13, 17.04s/it]

[I 2025-12-02 18:55:47,266] Trial 15 pruned.

Best trial: 9. Best value: 0.537869:  30%|███       | 15/50 [04:00<07:31, 12.90s/it]

[I 2025-12-02 18:55:50,557] Trial 14 pruned.

Best trial: 9. Best value: 0.537869:  32%|███▏      | 16/50 [04:15<07:37, 13.45s/it]

[I 2025-12-02 18:56:05,278] Trial 18 pruned.

Best trial: 9. Best value: 0.537869:  34%|███▍      | 17/50 [04:31<07:53, 14.33s/it]

[I 2025-12-02 18:56:21,676] Trial 17 pruned.

Best trial: 9. Best value: 0.537869:  36%|███▌      | 18/50 [04:50<08:28, 15.89s/it]

[I 2025-12-02 18:56:41,198] Trial 20 pruned.

Best trial: 9. Best value: 0.537869:  38%|███▊      | 19/50 [05:08<08:31, 16.51s/it]

[I 2025-12-02 18:56:59,157] Trial 13 pruned.

Best trial: 9. Best value: 0.537869:  40%|████      | 20/50 [05:28<08:41, 17.37s/it]

[I 2025-12-02 18:57:18,518] Trial 16 finished with value: 0.511553273427471 and parameters: {'max_depth': 9, 'learning_rate': 0.04800621452541977, 'n_estimators': 1472, 'subsample': 0.5523924481482396, 'colsample_bytree': 0.8514802697109309, 'min_child_weight': 4, 'gamma': 2.969429074359502, 'reg_alpha': 3.284959560923543e-08, 'reg_lambda': 0.015043066142389193, 'max_delta_step': 9}. Best is trial 9 with value: 0.5378690629011553.

Best trial: 9. Best value: 0.537869:  42%|████▏     | 21/50 [05:42<07:57, 16.48s/it]

[I 2025-12-02 18:57:32,931] Trial 22 pruned.

Best trial: 9. Best value: 0.537869:  44%|████▍     | 22/50 [05:44<05:34, 11.96s/it]

[I 2025-12-02 18:57:34,346] Trial 19 finished with value: 0.5096277278562259 and parameters: {'max_depth': 6, 'learning_rate': 0.13019663071128876, 'n_estimators': 1356, 'subsample': 0.8324499684191405, 'colsample_bytree': 0.7788931628091196, 'min_child_weight': 5, 'gamma': 3.1926356518913463, 'reg_alpha': 0.0026205754902647958, 'reg_lambda': 0.004663067158409807, 'max_delta_step': 10}. Best is trial 9 with value: 0.5378690629011553.

Best trial: 9. Best value: 0.537869:  46%|████▌     | 23/50 [05:54<05:06, 11.35s/it]

[I 2025-12-02 18:57:44,268] Trial 24 pruned.

Best trial: 9. Best value: 0.537869:  48%|████▊     | 24/50 [05:54<03:30,  8.10s/it]

[I 2025-12-02 18:57:44,796] Trial 25 pruned.

Best trial: 9. Best value: 0.537869:  50%|█████     | 25/50 [06:21<05:42, 13.69s/it]

[I 2025-12-02 18:58:11,529] Trial 21 finished with value: 0.5096277278562259 and parameters: {'max_depth': 8, 'learning_rate': 0.28895255773449197, 'n_estimators': 915, 'subsample': 0.819273437996492, 'colsample_bytree': 0.6381129869723391, 'min_child_weight': 1, 'gamma': 3.706489475603644, 'reg_alpha': 8.36714078273463e-05, 'reg_lambda': 2.1307153064633293e-05, 'max_delta_step': 10}. Best is trial 9 with value: 0.5378690629011553.

Best trial: 26. Best value: 0.560334:  52%|█████▏    | 26/50 [07:00<08:34, 21.44s/it]

[I 2025-12-02 18:58:51,053] Trial 26 finished with value: 0.5603337612323491 and parameters: {'max_depth': 10, 'learning_rate': 0.06392412872671183, 'n_estimators': 553, 'subsample': 0.9090232245106105, 'colsample_bytree': 0.6300473620497555, 'min_child_weight': 1, 'gamma': 0.6634209862261268, 'reg_alpha': 7.855461306843342e-07, 'reg_lambda': 9.064295597140286e-05, 'max_delta_step': 6}. Best is trial 26 with value: 0.5603337612323491.

Best trial: 26. Best value: 0.560334:  54%|█████▍    | 27/50 [07:04<06:07, 16.00s/it]

[I 2025-12-02 18:58:54,345] Trial 28 finished with value: 0.4974326059050064 and parameters: {'max_depth': 9, 'learning_rate': 0.18088490182380937, 'n_estimators': 544, 'subsample': 0.7662750127248867, 'colsample_bytree': 0.8146028595195469, 'min_child_weight': 3, 'gamma': 0.7984751842246124, 'reg_alpha': 8.456536865696731e-07, 'reg_lambda': 1.1132022677322583e-08, 'max_delta_step': 6}. Best is trial 26 with value: 0.5603337612323491.

Best trial: 26. Best value: 0.560334:  56%|█████▌    | 28/50 [07:04<04:11, 11.42s/it]

[I 2025-12-02 18:58:55,086] Trial 23 finished with value: 0.5237483953786906 and parameters: {'max_depth': 8, 'learning_rate': 0.29635159424819346, 'n_estimators': 969, 'subsample': 0.7973776868579447, 'colsample_bytree': 0.6567154560979874, 'min_child_weight': 1, 'gamma': 3.754803236948418, 'reg_alpha': 0.00016027073340706198, 'reg_lambda': 1.759666870356467e-05, 'max_delta_step': 8}. Best is trial 26 with value: 0.5603337612323491.

Best trial: 26. Best value: 0.560334:  58%|█████▊    | 29/50 [07:28<05:18, 15.17s/it]

[I 2025-12-02 18:59:18,996] Trial 27 finished with value: 0.5462130937098845 and parameters: {'max_depth': 9, 'learning_rate': 0.1058086930452469, 'n_estimators': 960, 'subsample': 0.7984815706058525, 'colsample_bytree': 0.638941267342794, 'min_child_weight': 1, 'gamma': 1.3648981311483974, 'reg_alpha': 6.698757548074146e-07, 'reg_lambda': 6.493195559591642e-05, 'max_delta_step': 6}. Best is trial 26 with value: 0.5603337612323491.

Best trial: 26. Best value: 0.560334:  60%|██████    | 30/50 [07:33<03:58, 11.94s/it]

[I 2025-12-02 18:59:23,402] Trial 32 pruned.

Best trial: 31. Best value: 0.574454:  62%|██████▏   | 31/50 [07:52<04:28, 14.13s/it]

[I 2025-12-02 18:59:42,634] Trial 31 finished with value: 0.5744544287548139 and parameters: {'max_depth': 7, 'learning_rate': 0.2248916757578237, 'n_estimators': 395, 'subsample': 0.9375635616252046, 'colsample_bytree': 0.6284211493055416, 'min_child_weight': 1, 'gamma': 1.413258163202486, 'reg_alpha': 0.006529571549474031, 'reg_lambda': 0.00012374409272888443, 'max_delta_step': 6}. Best is trial 31 with value: 0.5744544287548139.

Best trial: 31. Best value: 0.574454:  64%|██████▍   | 32/50 [08:08<04:24, 14.68s/it]

[I 2025-12-02 18:59:58,596] Trial 29 finished with value: 0.5359435173299101 and parameters: {'max_depth': 9, 'learning_rate': 0.03411299012947243, 'n_estimators': 523, 'subsample': 0.9335699543735879, 'colsample_bytree': 0.623175429546132, 'min_child_weight': 3, 'gamma': 0.6439294648520304, 'reg_alpha': 7.625760895694642e-07, 'reg_lambda': 0.00017520742664430203, 'max_delta_step': 6}. Best is trial 31 with value: 0.5744544287548139.

Best trial: 31. Best value: 0.574454:  66%|██████▌   | 33/50 [08:13<03:20, 11.78s/it]

[I 2025-12-02 19:00:03,622] Trial 34 pruned.

Best trial: 30. Best value: 0.598845:  68%|██████▊   | 34/50 [08:16<02:27,  9.21s/it]

[I 2025-12-02 19:00:06,826] Trial 30 finished with value: 0.5988446726572528 and parameters: {'max_depth': 9, 'learning_rate': 0.03527692187163214, 'n_estimators': 375, 'subsample': 0.9387000523322148, 'colsample_bytree': 0.6227274027294483, 'min_child_weight': 1, 'gamma': 1.5392856350951112, 'reg_alpha': 1.233749493364773e-07, 'reg_lambda': 0.00018016132364530337, 'max_delta_step': 8}. Best is trial 30 with value: 0.5988446726572528.

Best trial: 30. Best value: 0.598845:  70%|███████   | 35/50 [08:30<02:38, 10.55s/it]

[I 2025-12-02 19:00:20,504] Trial 33 pruned.

Best trial: 35. Best value: 0.612965:  72%|███████▏  | 36/50 [08:46<02:50, 12.21s/it]

[I 2025-12-02 19:00:36,586] Trial 35 finished with value: 0.6129653401797176 and parameters: {'max_depth': 5, 'learning_rate': 0.22354322641747465, 'n_estimators': 307, 'subsample': 0.9768263504323994, 'colsample_bytree': 0.5023574547188643, 'min_child_weight': 1, 'gamma': 1.4582153736891843, 'reg_alpha': 0.012993847556363689, 'reg_lambda': 0.0006519274774787429, 'max_delta_step': 5}. Best is trial 35 with value: 0.6129653401797176.

Best trial: 35. Best value: 0.612965:  74%|███████▍  | 37/50 [09:01<02:48, 12.95s/it]

[I 2025-12-02 19:00:51,248] Trial 36 finished with value: 0.6129653401797176 and parameters: {'max_depth': 8, 'learning_rate': 0.12185241693957628, 'n_estimators': 396, 'subsample': 0.9761639963895469, 'colsample_bytree': 0.5036930312951686, 'min_child_weight': 1, 'gamma': 1.4003322760879688, 'reg_alpha': 1.5751635440467632e-07, 'reg_lambda': 0.002200242267478003, 'max_delta_step': 5}. Best is trial 35 with value: 0.6129653401797176.

Best trial: 38. Best value: 0.637356:  76%|███████▌  | 38/50 [09:32<03:42, 18.56s/it]

[I 2025-12-02 19:01:22,908] Trial 38 finished with value: 0.6373555840821565 and parameters: {'max_depth': 8, 'learning_rate': 0.06046197698573596, 'n_estimators': 410, 'subsample': 0.9809472973880848, 'colsample_bytree': 0.5717178181312409, 'min_child_weight': 1, 'gamma': 1.4649555649426769, 'reg_alpha': 0.08304948476545874, 'reg_lambda': 0.0007946523013630072, 'max_delta_step': 8}. Best is trial 38 with value: 0.6373555840821565.

Best trial: 38. Best value: 0.637356:  78%|███████▊  | 39/50 [09:57<03:44, 20.44s/it]

[I 2025-12-02 19:01:47,740] Trial 37 finished with value: 0.6373555840821565 and parameters: {'max_depth': 8, 'learning_rate': 0.016281446007975413, 'n_estimators': 417, 'subsample': 0.9879612553191697, 'colsample_bytree': 0.5195715796757501, 'min_child_weight': 1, 'gamma': 1.5067433849474334, 'reg_alpha': 0.1909805202146632, 'reg_lambda': 0.0008537107115545689, 'max_delta_step': 5}. Best is trial 38 with value: 0.6373555840821565.

Best trial: 39. Best value: 0.649551:  80%|████████  | 40/50 [10:19<03:27, 20.76s/it]

[I 2025-12-02 19:02:09,258] Trial 39 finished with value: 0.6495507060333761 and parameters: {'max_depth': 5, 'learning_rate': 0.019089513758844632, 'n_estimators': 433, 'subsample': 0.9791005140168185, 'colsample_bytree': 0.5095552690101759, 'min_child_weight': 1, 'gamma': 1.5933728475227855, 'reg_alpha': 0.02891064890618858, 'reg_lambda': 0.0013321014183477798, 'max_delta_step': 5}. Best is trial 39 with value: 0.6495507060333761.

Best trial: 39. Best value: 0.649551:  82%|████████▏ | 41/50 [10:24<02:25, 16.17s/it]

[I 2025-12-02 19:02:14,697] Trial 40 finished with value: 0.6129653401797176 and parameters: {'max_depth': 6, 'learning_rate': 0.017210202806716944, 'n_estimators': 391, 'subsample': 0.9951032077484733, 'colsample_bytree': 0.5532043900552837, 'min_child_weight': 2, 'gamma': 1.5624096371792897, 'reg_alpha': 0.036699833755731194, 'reg_lambda': 0.0012834857399294027, 'max_delta_step': 5}. Best is trial 39 with value: 0.6495507060333761.

Best trial: 39. Best value: 0.649551:  84%|████████▍ | 42/50 [10:30<01:45, 13.15s/it]

[I 2025-12-02 19:02:20,797] Trial 41 finished with value: 0.6392811296534018 and parameters: {'max_depth': 5, 'learning_rate': 0.01862532076407372, 'n_estimators': 215, 'subsample': 0.9976479724380439, 'colsample_bytree': 0.5086806216626196, 'min_child_weight': 2, 'gamma': 2.187011326529155, 'reg_alpha': 0.06482577413855145, 'reg_lambda': 0.0016963197019522114, 'max_delta_step': 5}. Best is trial 39 with value: 0.6495507060333761.

Best trial: 39. Best value: 0.649551:  86%|████████▌ | 43/50 [10:46<01:37, 13.89s/it]

[I 2025-12-02 19:02:36,415] Trial 44 pruned.

Best trial: 39. Best value: 0.649551:  88%|████████▊ | 44/50 [10:58<01:20, 13.34s/it]

[I 2025-12-02 19:02:48,467] Trial 42 finished with value: 0.625160462130937 and parameters: {'max_depth': 5, 'learning_rate': 0.01631659649065545, 'n_estimators': 203, 'subsample': 0.9970535273526425, 'colsample_bytree': 0.5042926836211876, 'min_child_weight': 2, 'gamma': 2.209363530956526, 'reg_alpha': 0.05975363410113417, 'reg_lambda': 0.0010024769736876405, 'max_delta_step': 5}. Best is trial 39 with value: 0.6495507060333761.

Best trial: 39. Best value: 0.649551:  90%|█████████ | 45/50 [11:20<01:19, 16.00s/it]

[I 2025-12-02 19:03:10,671] Trial 43 finished with value: 0.625160462130937 and parameters: {'max_depth': 4, 'learning_rate': 0.015044761740309852, 'n_estimators': 204, 'subsample': 0.9995505829209045, 'colsample_bytree': 0.5471895640138358, 'min_child_weight': 2, 'gamma': 2.1788131196072404, 'reg_alpha': 0.0866298351734458, 'reg_lambda': 0.006890199966076677, 'max_delta_step': 5}. Best is trial 39 with value: 0.6495507060333761.

Best trial: 39. Best value: 0.649551:  92%|█████████▏| 46/50 [11:41<01:09, 17.42s/it]

[I 2025-12-02 19:03:31,404] Trial 45 finished with value: 0.625160462130937 and parameters: {'max_depth': 5, 'learning_rate': 0.016273729704719603, 'n_estimators': 264, 'subsample': 0.9722297050962977, 'colsample_bytree': 0.5091756404016547, 'min_child_weight': 2, 'gamma': 2.1927682637539077, 'reg_alpha': 0.3077298173104755, 'reg_lambda': 0.006553123830021727, 'max_delta_step': 4}. Best is trial 39 with value: 0.6495507060333761.

Best trial: 39. Best value: 0.649551:  94%|█████████▍| 47/50 [11:46<00:41, 13.75s/it]

[I 2025-12-02 19:03:36,588] Trial 48 pruned.

Best trial: 39. Best value: 0.649551:  96%|█████████▌| 48/50 [12:01<00:28, 14.04s/it]

[I 2025-12-02 19:03:51,313] Trial 46 finished with value: 0.625160462130937 and parameters: {'max_depth': 5, 'learning_rate': 0.02348882852976158, 'n_estimators': 474, 'subsample': 0.9960024868525984, 'colsample_bytree': 0.5541166715824702, 'min_child_weight': 2, 'gamma': 2.155704402492321, 'reg_alpha': 0.09570986101874931, 'reg_lambda': 0.0009266632668213277, 'max_delta_step': 4}. Best is trial 39 with value: 0.6495507060333761.

Best trial: 39. Best value: 0.649551:  98%|█████████▊| 49/50 [12:03<00:10, 10.67s/it]

[I 2025-12-02 19:03:54,119] Trial 49 pruned.

Best trial: 39. Best value: 0.649551: 100%|██████████| 50/50 [12:08<00:00, 14.56s/it]

[I 2025-12-02 19:03:58,353] Trial 47 finished with value: 0.625160462130937 and parameters: {'max_depth': 4, 'learning_rate': 0.022385738087358737, 'n_estimators': 469, 'subsample': 0.9908905189603078, 'colsample_bytree': 0.5565913041407037, 'min_child_weight': 2, 'gamma': 2.2308098021932246, 'reg_alpha': 0.19296680292505045, 'reg_lambda': 0.004796999591707403, 'max_delta_step': 3}. Best is trial 39 with value: 0.6495507060333761.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.649551                    0.45          0.58

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0   -0.1066               0.2               0.7        50          60

   test_size
0         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.649551                    0.45          0.58

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0   -0.1066               0.2               0.7        50          60

   test_size
0         15

In [ ]:

datasets = task_hf_dfs_clean_ad_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_handcrafted_ad_hc_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param="w.cz.fnusa",
)
print(summary)

[I 2025-12-02 19:04:05,922] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.602696:   2%|▏         | 1/50 [00:23<19:03, 23.34s/it]

[I 2025-12-02 19:04:29,248] Trial 0 finished with value: 0.6026957637997432 and parameters: {'max_depth': 5, 'learning_rate': 0.034630369528544265, 'n_estimators': 395, 'subsample': 0.9270068810426852, 'colsample_bytree': 0.5025825037118967, 'min_child_weight': 3, 'gamma': 4.219751029028097, 'reg_alpha': 0.002640532327318351, 'reg_lambda': 0.008830825949185444, 'max_delta_step': 8}. Best is trial 0 with value: 0.6026957637997432.

Best trial: 0. Best value: 0.602696:   4%|▍         | 2/50 [00:31<11:18, 14.14s/it]

[I 2025-12-02 19:04:36,951] Trial 1 finished with value: 0.5359435173299101 and parameters: {'max_depth': 10, 'learning_rate': 0.06663038755185831, 'n_estimators': 543, 'subsample': 0.6070614669651864, 'colsample_bytree': 0.9744553543562112, 'min_child_weight': 3, 'gamma': 2.7035230848456884, 'reg_alpha': 4.705141340288932e-07, 'reg_lambda': 3.2288520596614636e-08, 'max_delta_step': 8}. Best is trial 0 with value: 0.6026957637997432.

Best trial: 0. Best value: 0.602696:   6%|▌         | 3/50 [00:58<15:53, 20.30s/it]

[I 2025-12-02 19:05:04,574] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.04250441146955122, 'n_estimators': 1131, 'subsample': 0.8536588316027325, 'colsample_bytree': 0.7560663332250418, 'min_child_weight': 10, 'gamma': 4.129842557427173, 'reg_alpha': 0.03880720719505859, 'reg_lambda': 3.905451697625947e-06, 'max_delta_step': 0}. Best is trial 0 with value: 0.6026957637997432.

Best trial: 0. Best value: 0.602696:   8%|▊         | 4/50 [01:11<13:11, 17.20s/it]

[I 2025-12-02 19:05:17,021] Trial 5 finished with value: 0.5988446726572528 and parameters: {'max_depth': 8, 'learning_rate': 0.044751647613383246, 'n_estimators': 716, 'subsample': 0.5467956150782449, 'colsample_bytree': 0.9429653546532849, 'min_child_weight': 2, 'gamma': 3.499630110947956, 'reg_alpha': 0.07846306985565024, 'reg_lambda': 0.00031810158160927663, 'max_delta_step': 3}. Best is trial 0 with value: 0.6026957637997432.

Best trial: 0. Best value: 0.602696:  10%|█         | 5/50 [01:14<09:10, 12.24s/it]

[I 2025-12-02 19:05:20,460] Trial 6 finished with value: 0.34210526315789475 and parameters: {'max_depth': 10, 'learning_rate': 0.1372656087964744, 'n_estimators': 263, 'subsample': 0.5282238674175651, 'colsample_bytree': 0.8479472508873296, 'min_child_weight': 9, 'gamma': 1.0852581949062263, 'reg_alpha': 0.0004871664506856605, 'reg_lambda': 9.799744989964082e-07, 'max_delta_step': 8}. Best is trial 0 with value: 0.6026957637997432.

Best trial: 0. Best value: 0.602696:  12%|█▏        | 6/50 [01:15<06:12,  8.47s/it]

[I 2025-12-02 19:05:21,626] Trial 4 finished with value: 0.5519897304236201 and parameters: {'max_depth': 3, 'learning_rate': 0.16248946426963737, 'n_estimators': 940, 'subsample': 0.9582560476139865, 'colsample_bytree': 0.9065592575207562, 'min_child_weight': 3, 'gamma': 4.637765100273687, 'reg_alpha': 0.008188318029017216, 'reg_lambda': 0.3030002367954385, 'max_delta_step': 4}. Best is trial 0 with value: 0.6026957637997432.

Best trial: 0. Best value: 0.602696:  14%|█▍        | 7/50 [01:17<04:31,  6.32s/it]

[I 2025-12-02 19:05:23,503] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.056333295495784, 'n_estimators': 1482, 'subsample': 0.9277334923383913, 'colsample_bytree': 0.7995500668322109, 'min_child_weight': 10, 'gamma': 2.0110616008192155, 'reg_alpha': 4.420285099062542, 'reg_lambda': 1.25287297396725e-07, 'max_delta_step': 0}. Best is trial 0 with value: 0.6026957637997432.

Best trial: 0. Best value: 0.602696:  16%|█▌        | 8/50 [01:38<07:45, 11.07s/it]

[I 2025-12-02 19:05:44,765] Trial 9 finished with value: 0.5661103979460848 and parameters: {'max_depth': 4, 'learning_rate': 0.26322222810896206, 'n_estimators': 389, 'subsample': 0.906761330208349, 'colsample_bytree': 0.736515536459506, 'min_child_weight': 5, 'gamma': 3.205910515082864, 'reg_alpha': 1.5506976505581637e-07, 'reg_lambda': 2.8583790291410025e-05, 'max_delta_step': 10}. Best is trial 0 with value: 0.6026957637997432.

Best trial: 0. Best value: 0.602696:  18%|█▊        | 9/50 [01:44<06:21,  9.30s/it]

[I 2025-12-02 19:05:50,175] Trial 7 finished with value: 0.4473684210526316 and parameters: {'max_depth': 3, 'learning_rate': 0.03672183564409679, 'n_estimators': 611, 'subsample': 0.5267332329424396, 'colsample_bytree': 0.8346396053792086, 'min_child_weight': 10, 'gamma': 4.667769117649488, 'reg_alpha': 0.9743750290438371, 'reg_lambda': 1.3445478814023266e-06, 'max_delta_step': 9}. Best is trial 0 with value: 0.6026957637997432.

Best trial: 0. Best value: 0.602696:  20%|██        | 10/50 [01:52<05:57,  8.94s/it]

[I 2025-12-02 19:05:58,314] Trial 8 finished with value: 0.4473684210526316 and parameters: {'max_depth': 5, 'learning_rate': 0.01846320466350203, 'n_estimators': 689, 'subsample': 0.5500122909592482, 'colsample_bytree': 0.5404255743110209, 'min_child_weight': 9, 'gamma': 3.7286587821461827, 'reg_alpha': 2.486633989945368, 'reg_lambda': 1.3786692569800354e-05, 'max_delta_step': 0}. Best is trial 0 with value: 0.6026957637997432.

Best trial: 0. Best value: 0.602696:  22%|██▏       | 11/50 [01:52<04:09,  6.39s/it]

[I 2025-12-02 19:05:58,903] Trial 11 pruned.

Best trial: 0. Best value: 0.602696:  24%|██▍       | 12/50 [02:05<05:16,  8.33s/it]

[I 2025-12-02 19:06:11,683] Trial 13 finished with value: 0.6026957637997432 and parameters: {'max_depth': 6, 'learning_rate': 0.01353697589853534, 'n_estimators': 218, 'subsample': 0.7972223112354734, 'colsample_bytree': 0.507012220675715, 'min_child_weight': 6, 'gamma': 0.08328877595189699, 'reg_alpha': 7.758609431644719e-06, 'reg_lambda': 0.053069146677148, 'max_delta_step': 6}. Best is trial 0 with value: 0.6026957637997432.

Best trial: 0. Best value: 0.602696:  26%|██▌       | 13/50 [02:18<05:51,  9.51s/it]

[I 2025-12-02 19:06:23,917] Trial 10 pruned.

Best trial: 0. Best value: 0.602696:  28%|██▊       | 14/50 [02:20<04:27,  7.44s/it]

[I 2025-12-02 19:06:26,554] Trial 15 finished with value: 0.5885750962772786 and parameters: {'max_depth': 7, 'learning_rate': 0.01172817153237029, 'n_estimators': 238, 'subsample': 0.7635127258174819, 'colsample_bytree': 0.519022572776795, 'min_child_weight': 6, 'gamma': 2.073432748151646, 'reg_alpha': 1.3517705972901157e-05, 'reg_lambda': 0.006847782322974044, 'max_delta_step': 6}. Best is trial 0 with value: 0.6026957637997432.

Best trial: 0. Best value: 0.602696:  30%|███       | 15/50 [02:30<04:50,  8.31s/it]

[I 2025-12-02 19:06:36,886] Trial 16 finished with value: 0.5905006418485237 and parameters: {'max_depth': 6, 'learning_rate': 0.010014243462235143, 'n_estimators': 202, 'subsample': 0.7857166072419105, 'colsample_bytree': 0.6334308880914574, 'min_child_weight': 5, 'gamma': 1.6778384331178104, 'reg_alpha': 8.04973474905273e-06, 'reg_lambda': 0.0059056309095981965, 'max_delta_step': 6}. Best is trial 0 with value: 0.6026957637997432.

Best trial: 12. Best value: 0.693838:  32%|███▏      | 16/50 [02:33<03:42,  6.54s/it]

[I 2025-12-02 19:06:39,319] Trial 12 finished with value: 0.6938382541720154 and parameters: {'max_depth': 5, 'learning_rate': 0.17130673205427702, 'n_estimators': 948, 'subsample': 0.9042377630893681, 'colsample_bytree': 0.6450810819239645, 'min_child_weight': 5, 'gamma': 4.588982564140199, 'reg_alpha': 6.877430739343908, 'reg_lambda': 7.117194855233676e-05, 'max_delta_step': 6}. Best is trial 12 with value: 0.6938382541720154.

Best trial: 12. Best value: 0.693838:  34%|███▍      | 17/50 [02:45<04:29,  8.17s/it]

[I 2025-12-02 19:06:51,283] Trial 14 finished with value: 0.6007702182284981 and parameters: {'max_depth': 7, 'learning_rate': 0.01836429376947012, 'n_estimators': 994, 'subsample': 0.7077003343554402, 'colsample_bytree': 0.5273915861596168, 'min_child_weight': 1, 'gamma': 3.4029318008199, 'reg_alpha': 0.01573825874139547, 'reg_lambda': 0.003285633007866338, 'max_delta_step': 5}. Best is trial 12 with value: 0.6938382541720154.

Best trial: 12. Best value: 0.693838:  36%|███▌      | 18/50 [02:50<03:52,  7.27s/it]

[I 2025-12-02 19:06:56,468] Trial 17 finished with value: 0.6129653401797176 and parameters: {'max_depth': 6, 'learning_rate': 0.0213549851125714, 'n_estimators': 433, 'subsample': 0.7829823604145574, 'colsample_bytree': 0.6327746955146721, 'min_child_weight': 1, 'gamma': 0.3904835066183292, 'reg_alpha': 1.8184719828867404e-06, 'reg_lambda': 4.347467861744897, 'max_delta_step': 6}. Best is trial 12 with value: 0.6938382541720154.

Best trial: 12. Best value: 0.693838:  38%|███▊      | 19/50 [03:00<04:11,  8.10s/it]

[I 2025-12-02 19:07:06,512] Trial 21 pruned.

Best trial: 12. Best value: 0.693838:  40%|████      | 20/50 [03:07<03:51,  7.73s/it]

[I 2025-12-02 19:07:13,371] Trial 18 finished with value: 0.6129653401797176 and parameters: {'max_depth': 6, 'learning_rate': 0.022359396197196086, 'n_estimators': 513, 'subsample': 0.8326932248370907, 'colsample_bytree': 0.6192855681184716, 'min_child_weight': 1, 'gamma': 0.14329582843600086, 'reg_alpha': 0.000700495557897668, 'reg_lambda': 5.714302417234697, 'max_delta_step': 5}. Best is trial 12 with value: 0.6938382541720154.

Best trial: 12. Best value: 0.693838:  42%|████▏     | 21/50 [03:21<04:38,  9.61s/it]

[I 2025-12-02 19:07:27,376] Trial 19 finished with value: 0.5905006418485237 and parameters: {'max_depth': 5, 'learning_rate': 0.08732190079394715, 'n_estimators': 985, 'subsample': 0.6946017787686725, 'colsample_bytree': 0.6310842145680821, 'min_child_weight': 1, 'gamma': 4.844776688757525, 'reg_alpha': 0.0006177020124863777, 'reg_lambda': 2.7080275316415716, 'max_delta_step': 3}. Best is trial 12 with value: 0.6938382541720154.

Best trial: 12. Best value: 0.693838:  44%|████▍     | 22/50 [03:26<03:47,  8.12s/it]

[I 2025-12-02 19:07:32,015] Trial 24 pruned.

Best trial: 12. Best value: 0.693838:  46%|████▌     | 23/50 [03:33<03:36,  8.02s/it]

[I 2025-12-02 19:07:39,813] Trial 20 pruned.

Best trial: 12. Best value: 0.693838:  48%|████▊     | 24/50 [03:47<04:14,  9.79s/it]

[I 2025-12-02 19:07:53,717] Trial 22 finished with value: 0.6148908857509627 and parameters: {'max_depth': 6, 'learning_rate': 0.025303999947506504, 'n_estimators': 861, 'subsample': 0.8339486174826461, 'colsample_bytree': 0.6291306846429789, 'min_child_weight': 4, 'gamma': 0.8424556725974495, 'reg_alpha': 6.80967676412236e-07, 'reg_lambda': 6.770097176553707, 'max_delta_step': 2}. Best is trial 12 with value: 0.6938382541720154.

Best trial: 12. Best value: 0.693838:  50%|█████     | 25/50 [03:55<03:45,  9.04s/it]

[I 2025-12-02 19:08:00,996] Trial 27 pruned.

Best trial: 12. Best value: 0.693838:  52%|█████▏    | 26/50 [03:55<02:38,  6.59s/it]

[I 2025-12-02 19:08:01,864] Trial 23 finished with value: 0.5885750962772786 and parameters: {'max_depth': 9, 'learning_rate': 0.028022538880532223, 'n_estimators': 882, 'subsample': 0.8676150502629151, 'colsample_bytree': 0.5935820294534685, 'min_child_weight': 4, 'gamma': 0.9291296342309725, 'reg_alpha': 2.5592543740998095e-07, 'reg_lambda': 5.999439834297967, 'max_delta_step': 2}. Best is trial 12 with value: 0.6938382541720154.

Best trial: 12. Best value: 0.693838:  54%|█████▍    | 27/50 [04:10<03:25,  8.92s/it]

[I 2025-12-02 19:08:16,226] Trial 25 finished with value: 0.5885750962772786 and parameters: {'max_depth': 7, 'learning_rate': 0.022814077823286552, 'n_estimators': 829, 'subsample': 0.8307442161207387, 'colsample_bytree': 0.569442705300845, 'min_child_weight': 2, 'gamma': 1.3590881597337254, 'reg_alpha': 1.1094170535844185e-06, 'reg_lambda': 0.4781255977751014, 'max_delta_step': 7}. Best is trial 12 with value: 0.6938382541720154.

Best trial: 12. Best value: 0.693838:  56%|█████▌    | 28/50 [04:19<03:15,  8.87s/it]

[I 2025-12-02 19:08:24,974] Trial 30 pruned.

Best trial: 12. Best value: 0.693838:  58%|█████▊    | 29/50 [04:22<02:30,  7.15s/it]

[I 2025-12-02 19:08:28,116] Trial 26 finished with value: 0.6270860077021823 and parameters: {'max_depth': 7, 'learning_rate': 0.025648417480779454, 'n_estimators': 819, 'subsample': 0.8245624115029009, 'colsample_bytree': 0.5863858547030784, 'min_child_weight': 2, 'gamma': 0.5276179137770348, 'reg_alpha': 4.998363948469066e-07, 'reg_lambda': 8.22082340737213, 'max_delta_step': 7}. Best is trial 12 with value: 0.6938382541720154.

Best trial: 12. Best value: 0.693838:  60%|██████    | 30/50 [04:30<02:29,  7.50s/it]

[I 2025-12-02 19:08:36,423] Trial 31 pruned.

Best trial: 12. Best value: 0.693838:  62%|██████▏   | 31/50 [04:37<02:19,  7.33s/it]

[I 2025-12-02 19:08:43,347] Trial 33 pruned.

Best trial: 12. Best value: 0.693838:  64%|██████▍   | 32/50 [04:40<01:50,  6.16s/it]

[I 2025-12-02 19:08:46,800] Trial 34 pruned.

Best trial: 12. Best value: 0.693838:  66%|██████▌   | 33/50 [04:41<01:14,  4.38s/it]

[I 2025-12-02 19:08:47,033] Trial 28 finished with value: 0.6007702182284981 and parameters: {'max_depth': 9, 'learning_rate': 0.01662880333414629, 'n_estimators': 810, 'subsample': 0.8902110356876393, 'colsample_bytree': 0.7016016999638127, 'min_child_weight': 4, 'gamma': 0.4613430088363356, 'reg_alpha': 2.471311729081602e-08, 'reg_lambda': 0.00042119939688354017, 'max_delta_step': 7}. Best is trial 12 with value: 0.6938382541720154.

Best trial: 12. Best value: 0.693838:  68%|██████▊   | 34/50 [04:53<01:49,  6.87s/it]

[I 2025-12-02 19:08:59,706] Trial 29 finished with value: 0.6392811296534018 and parameters: {'max_depth': 7, 'learning_rate': 0.016343055994371265, 'n_estimators': 1058, 'subsample': 0.653571341290588, 'colsample_bytree': 0.6915136837347794, 'min_child_weight': 2, 'gamma': 2.751337164595281, 'reg_alpha': 1.8420901581866942e-08, 'reg_lambda': 0.0002703507612499251, 'max_delta_step': 7}. Best is trial 12 with value: 0.6938382541720154.

Best trial: 12. Best value: 0.693838:  70%|███████   | 35/50 [05:14<02:46, 11.12s/it]

[I 2025-12-02 19:09:20,744] Trial 36 finished with value: 0.6148908857509627 and parameters: {'max_depth': 7, 'learning_rate': 0.057307116229380214, 'n_estimators': 621, 'subsample': 0.758515505628073, 'colsample_bytree': 0.5981487464588923, 'min_child_weight': 2, 'gamma': 1.3281950086910412, 'reg_alpha': 1.5736657500394232e-06, 'reg_lambda': 0.7251810717542633, 'max_delta_step': 6}. Best is trial 12 with value: 0.6938382541720154.

Best trial: 12. Best value: 0.693838:  72%|███████▏  | 36/50 [05:15<01:53,  8.11s/it]

[I 2025-12-02 19:09:21,845] Trial 35 finished with value: 0.6514762516046213 and parameters: {'max_depth': 7, 'learning_rate': 0.05554471647507965, 'n_estimators': 600, 'subsample': 0.7377634212422988, 'colsample_bytree': 0.5701097005656479, 'min_child_weight': 2, 'gamma': 0.4787162389789971, 'reg_alpha': 4.598539107396417e-08, 'reg_lambda': 8.483673751474873, 'max_delta_step': 6}. Best is trial 12 with value: 0.6938382541720154.

Best trial: 12. Best value: 0.693838:  74%|███████▍  | 37/50 [05:27<01:57,  9.02s/it]

[I 2025-12-02 19:09:32,963] Trial 32 finished with value: 0.5500641848523748 and parameters: {'max_depth': 7, 'learning_rate': 0.2809716352290305, 'n_estimators': 1269, 'subsample': 0.8955467978797625, 'colsample_bytree': 0.7175489365135811, 'min_child_weight': 2, 'gamma': 2.7146576293769105, 'reg_alpha': 8.915770061502587e-08, 'reg_lambda': 5.895100531726537e-05, 'max_delta_step': 7}. Best is trial 12 with value: 0.6938382541720154.

Best trial: 12. Best value: 0.693838:  76%|███████▌  | 38/50 [05:35<01:46,  8.84s/it]

[I 2025-12-02 19:09:41,379] Trial 40 pruned.

Best trial: 12. Best value: 0.693838:  78%|███████▊  | 39/50 [05:45<01:42,  9.30s/it]

[I 2025-12-02 19:09:51,777] Trial 41 pruned.

Best trial: 12. Best value: 0.693838:  80%|████████  | 40/50 [05:51<01:21,  8.16s/it]

[I 2025-12-02 19:09:57,260] Trial 42 pruned.

Best trial: 12. Best value: 0.693838:  82%|████████▏ | 41/50 [05:52<00:55,  6.15s/it]

[I 2025-12-02 19:09:58,741] Trial 37 finished with value: 0.5885750962772786 and parameters: {'max_depth': 7, 'learning_rate': 0.05656707795934153, 'n_estimators': 1082, 'subsample': 0.6284216476036933, 'colsample_bytree': 0.7958008203766447, 'min_child_weight': 3, 'gamma': 4.103990735654558, 'reg_alpha': 4.73036797659311e-08, 'reg_lambda': 0.7560939327151688, 'max_delta_step': 9}. Best is trial 12 with value: 0.6938382541720154.

Best trial: 12. Best value: 0.693838:  84%|████████▍ | 42/50 [06:02<00:58,  7.31s/it]

[I 2025-12-02 19:10:08,725] Trial 44 pruned.

Best trial: 12. Best value: 0.693838:  86%|████████▌ | 43/50 [06:14<00:59,  8.53s/it]

[I 2025-12-02 19:10:20,113] Trial 39 finished with value: 0.6270860077021823 and parameters: {'max_depth': 8, 'learning_rate': 0.07363294065063201, 'n_estimators': 1080, 'subsample': 0.6305227239395531, 'colsample_bytree': 0.5621658006295193, 'min_child_weight': 3, 'gamma': 4.106436013219103, 'reg_alpha': 5.5221143183401385e-08, 'reg_lambda': 8.821592220687661e-05, 'max_delta_step': 9}. Best is trial 12 with value: 0.6938382541720154.

Best trial: 12. Best value: 0.693838:  88%|████████▊ | 44/50 [06:14<00:36,  6.04s/it]

[I 2025-12-02 19:10:20,358] Trial 38 finished with value: 0.6392811296534018 and parameters: {'max_depth': 8, 'learning_rate': 0.045871123503286294, 'n_estimators': 1083, 'subsample': 0.648260052878001, 'colsample_bytree': 0.775310489824109, 'min_child_weight': 3, 'gamma': 4.20352748609716, 'reg_alpha': 5.464884124441182e-08, 'reg_lambda': 0.00010910642345451541, 'max_delta_step': 9}. Best is trial 12 with value: 0.6938382541720154.

Best trial: 12. Best value: 0.693838:  90%|█████████ | 45/50 [06:24<00:35,  7.18s/it]

[I 2025-12-02 19:10:30,184] Trial 46 pruned.

Best trial: 12. Best value: 0.693838:  92%|█████████▏| 46/50 [06:25<00:20,  5.25s/it]

[I 2025-12-02 19:10:30,927] Trial 47 pruned.

Best trial: 12. Best value: 0.693838:  94%|█████████▍| 47/50 [06:31<00:16,  5.49s/it]

[I 2025-12-02 19:10:36,981] Trial 48 pruned.

Best trial: 12. Best value: 0.693838:  96%|█████████▌| 48/50 [06:31<00:07,  4.00s/it]

[I 2025-12-02 19:10:37,492] Trial 49 pruned.

Best trial: 12. Best value: 0.693838:  98%|█████████▊| 49/50 [06:36<00:04,  4.38s/it]

[I 2025-12-02 19:10:42,787] Trial 45 finished with value: 0.5744544287548139 and parameters: {'max_depth': 7, 'learning_rate': 0.2061228691069676, 'n_estimators': 701, 'subsample': 0.8204923513601687, 'colsample_bytree': 0.6100730818446323, 'min_child_weight': 3, 'gamma': 1.7499556253385138, 'reg_alpha': 1.5919850560770363e-07, 'reg_lambda': 0.0018133291799426923, 'max_delta_step': 8}. Best is trial 12 with value: 0.6938382541720154.

Best trial: 12. Best value: 0.693838: 100%|██████████| 50/50 [06:39<00:00,  8.00s/it]

[I 2025-12-02 19:10:45,793] Trial 43 finished with value: 0.6148908857509627 and parameters: {'max_depth': 7, 'learning_rate': 0.013678020838286476, 'n_estimators': 1108, 'subsample': 0.7373809610765082, 'colsample_bytree': 0.6526870838054153, 'min_child_weight': 3, 'gamma': 4.365912043178488, 'reg_alpha': 0.08644962543063182, 'reg_lambda': 0.0016813357622393647, 'max_delta_step': 5}. Best is trial 12 with value: 0.6938382541720154.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.693838                    0.55          0.57

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.094491               0.6               0.5        50          60

   test_size
0         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.693838                    0.55          0.57

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.094491               0.6               0.5        50          60

   test_size
0         15

## MCI-LBD vs MCI-AD -> OTPUNA + XBG

In [ ]:
datasets = task_hf_compensated_comb_emb_lbl_ad_lbd

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_lbd_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_handcrafted_combined_emb_compensated_ad_lbd_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param= "diagnosis_y",
)
print(summary)

[I 2025-12-02 19:10:49,150] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 45, Test size: 12
Using Leave-One-Out CV with 45 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0:   2%|▏         | 1/50 [00:21<17:33, 21.50s/it]

[I 2025-12-02 19:11:10,639] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.011771536358915292, 'n_estimators': 458, 'subsample': 0.7439359417790818, 'colsample_bytree': 0.9173055308079203, 'min_child_weight': 8, 'gamma': 2.431679400999529, 'reg_alpha': 0.006194048494529491, 'reg_lambda': 3.4623773424119226e-07, 'max_delta_step': 4}. Best is trial 3 with value: 0.0.

Best trial: 3. Best value: 0:   4%|▍         | 2/50 [00:32<12:26, 15.56s/it]

[I 2025-12-02 19:11:22,038] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.021752645093410253, 'n_estimators': 237, 'subsample': 0.6344902223135683, 'colsample_bytree': 0.9030802516953441, 'min_child_weight': 10, 'gamma': 2.315866375565321, 'reg_alpha': 1.8699199725297708, 'reg_lambda': 0.0034364809666852696, 'max_delta_step': 3}. Best is trial 3 with value: 0.0.

Best trial: 2. Best value: 0.511134:   6%|▌         | 3/50 [00:34<07:06,  9.08s/it]

[I 2025-12-02 19:11:23,412] Trial 2 finished with value: 0.5111336032388664 and parameters: {'max_depth': 7, 'learning_rate': 0.09712201302004471, 'n_estimators': 723, 'subsample': 0.633785941527186, 'colsample_bytree': 0.6677619476015821, 'min_child_weight': 2, 'gamma': 4.750302369853404, 'reg_alpha': 0.08150158973398633, 'reg_lambda': 0.1518957015483072, 'max_delta_step': 0}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 2. Best value: 0.511134:   8%|▊         | 4/50 [00:38<05:31,  7.20s/it]

[I 2025-12-02 19:11:27,724] Trial 1 finished with value: 0.34615384615384615 and parameters: {'max_depth': 7, 'learning_rate': 0.17915387007939684, 'n_estimators': 930, 'subsample': 0.6993205007189691, 'colsample_bytree': 0.742785853369835, 'min_child_weight': 5, 'gamma': 0.7349950764362156, 'reg_alpha': 1.3002409940157045e-07, 'reg_lambda': 8.370097739989125, 'max_delta_step': 8}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 2. Best value: 0.511134:  10%|█         | 5/50 [00:55<07:56, 10.59s/it]

[I 2025-12-02 19:11:44,324] Trial 0 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.011054357553809383, 'n_estimators': 816, 'subsample': 0.7540178969417027, 'colsample_bytree': 0.865391563447335, 'min_child_weight': 1, 'gamma': 4.420009343860976, 'reg_alpha': 5.721732827037844, 'reg_lambda': 0.0013015139150173963, 'max_delta_step': 2}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 2. Best value: 0.511134:  12%|█▏        | 6/50 [01:06<07:53, 10.76s/it]

[I 2025-12-02 19:11:55,419] Trial 6 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.02693611323216609, 'n_estimators': 797, 'subsample': 0.5449098535521772, 'colsample_bytree': 0.5881513190011521, 'min_child_weight': 10, 'gamma': 2.0146270415391685, 'reg_alpha': 6.827641780021022e-05, 'reg_lambda': 1.308795091546891e-05, 'max_delta_step': 7}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 2. Best value: 0.511134:  14%|█▍        | 7/50 [01:26<09:53, 13.79s/it]

[I 2025-12-02 19:12:15,452] Trial 9 finished with value: 0.17307692307692307 and parameters: {'max_depth': 6, 'learning_rate': 0.24862930219570833, 'n_estimators': 472, 'subsample': 0.8421064020223274, 'colsample_bytree': 0.5431887421827435, 'min_child_weight': 8, 'gamma': 4.393741490448982, 'reg_alpha': 0.5330176100468855, 'reg_lambda': 0.0025849714600264663, 'max_delta_step': 10}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 2. Best value: 0.511134:  16%|█▌        | 8/50 [01:32<07:54, 11.30s/it]

[I 2025-12-02 19:12:21,410] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.08185229928963302, 'n_estimators': 1394, 'subsample': 0.6848520867400376, 'colsample_bytree': 0.5404990110543808, 'min_child_weight': 7, 'gamma': 4.73577375505568, 'reg_alpha': 3.3196242768406755e-07, 'reg_lambda': 2.5253844866526596e-08, 'max_delta_step': 1}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 2. Best value: 0.511134:  18%|█▊        | 9/50 [01:32<05:24,  7.92s/it]

[I 2025-12-02 19:12:21,901] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.01273792997397666, 'n_estimators': 1072, 'subsample': 0.6132274989147399, 'colsample_bytree': 0.5902810477921255, 'min_child_weight': 1, 'gamma': 4.015829742845157, 'reg_alpha': 8.37033350577559, 'reg_lambda': 5.339511404927842e-08, 'max_delta_step': 9}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 2. Best value: 0.511134:  20%|██        | 10/50 [01:38<04:53,  7.34s/it]

[I 2025-12-02 19:12:27,935] Trial 8 finished with value: 0.11538461538461539 and parameters: {'max_depth': 4, 'learning_rate': 0.104680482087463, 'n_estimators': 1052, 'subsample': 0.8502616478411741, 'colsample_bytree': 0.6991593804006302, 'min_child_weight': 8, 'gamma': 3.4788103740166045, 'reg_alpha': 3.8655055532240004e-07, 'reg_lambda': 3.706886152205801e-05, 'max_delta_step': 0}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 2. Best value: 0.511134:  22%|██▏       | 11/50 [01:41<03:54,  6.00s/it]

[I 2025-12-02 19:12:30,917] Trial 10 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.08935852576389544, 'n_estimators': 305, 'subsample': 0.9965556749372284, 'colsample_bytree': 0.9838860411604117, 'min_child_weight': 8, 'gamma': 3.4001338032100534, 'reg_alpha': 0.007863180583321411, 'reg_lambda': 0.002347743444829691, 'max_delta_step': 3}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 2. Best value: 0.511134:  24%|██▍       | 12/50 [02:09<07:56, 12.54s/it]

[I 2025-12-02 19:12:58,400] Trial 14 finished with value: 0.46153846153846156 and parameters: {'max_depth': 7, 'learning_rate': 0.21321591254052324, 'n_estimators': 626, 'subsample': 0.5020472158192519, 'colsample_bytree': 0.7363783083673644, 'min_child_weight': 4, 'gamma': 0.47457133506410853, 'reg_alpha': 1.443336480829232e-08, 'reg_lambda': 7.041250314561618, 'max_delta_step': 6}. Best is trial 2 with value: 0.5111336032388664.
[I 2025-12-02 19:12:58,586] Trial 11 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.14769378451905893, 'n_estimators': 907, 'subsample': 0.6920584213340792, 'colsample_bytree': 0.5106373419070341, 'min_child_weight': 8, 'gamma': 2.538430980474117, 'reg_alpha': 2.2360175334073, 'reg_lambda': 0.0028266536730575066, 'max_delta_step': 4}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 2. Best value: 0.511134:  28%|██▊       | 14/50 [02:32<07:47, 12.99s/it]

[I 2025-12-02 19:13:21,272] Trial 12 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.19654990493932084, 'n_estimators': 1336, 'subsample': 0.9137288987490622, 'colsample_bytree': 0.9199822736738597, 'min_child_weight': 5, 'gamma': 0.9477931325878286, 'reg_alpha': 7.075531283331641e-08, 'reg_lambda': 1.9700756820814613, 'max_delta_step': 5}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 2. Best value: 0.511134:  30%|███       | 15/50 [02:37<06:15, 10.73s/it]

[I 2025-12-02 19:13:26,751] Trial 15 finished with value: 0.45344129554655865 and parameters: {'max_depth': 8, 'learning_rate': 0.13912648620081589, 'n_estimators': 617, 'subsample': 0.5017557804788438, 'colsample_bytree': 0.6703321908565604, 'min_child_weight': 3, 'gamma': 0.021708447296249878, 'reg_alpha': 3.033561357390545e-05, 'reg_lambda': 2.585484675477461, 'max_delta_step': 6}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 2. Best value: 0.511134:  32%|███▏      | 16/50 [02:38<04:24,  7.77s/it]

[I 2025-12-02 19:13:27,647] Trial 16 finished with value: 0.5111336032388664 and parameters: {'max_depth': 8, 'learning_rate': 0.0406608778095261, 'n_estimators': 619, 'subsample': 0.523864455556976, 'colsample_bytree': 0.6853761951253163, 'min_child_weight': 3, 'gamma': 0.4388601976263624, 'reg_alpha': 0.0001795292158725645, 'reg_lambda': 2.9268790719136444, 'max_delta_step': 6}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 2. Best value: 0.511134:  34%|███▍      | 17/50 [02:43<03:51,  7.03s/it]

[I 2025-12-02 19:13:32,948] Trial 13 finished with value: 0.42004048582995945 and parameters: {'max_depth': 3, 'learning_rate': 0.05053776790504485, 'n_estimators': 1451, 'subsample': 0.9912673779151943, 'colsample_bytree': 0.6815090274104197, 'min_child_weight': 3, 'gamma': 0.021113300787697575, 'reg_alpha': 0.007111957570803563, 'reg_lambda': 0.8412498369633451, 'max_delta_step': 6}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 2. Best value: 0.511134:  36%|███▌      | 18/50 [03:00<05:14,  9.84s/it]

[I 2025-12-02 19:13:49,329] Trial 17 finished with value: 0.4726720647773279 and parameters: {'max_depth': 3, 'learning_rate': 0.045802994963343856, 'n_estimators': 608, 'subsample': 0.5311823924127731, 'colsample_bytree': 0.6792996744192487, 'min_child_weight': 3, 'gamma': 0.0031179764513820096, 'reg_alpha': 0.00017434280041513168, 'reg_lambda': 0.1971009075795852, 'max_delta_step': 6}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 2. Best value: 0.511134:  38%|███▊      | 19/50 [03:09<05:02,  9.74s/it]

[I 2025-12-02 19:13:58,851] Trial 18 finished with value: 0.5111336032388664 and parameters: {'max_depth': 3, 'learning_rate': 0.05007652331010116, 'n_estimators': 665, 'subsample': 0.5698786173363581, 'colsample_bytree': 0.8192878738699941, 'min_child_weight': 3, 'gamma': 1.5615826471629157, 'reg_alpha': 0.008578627408927475, 'reg_lambda': 0.15971494403619094, 'max_delta_step': 6}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 2. Best value: 0.511134:  40%|████      | 20/50 [03:10<03:31,  7.04s/it]

[I 2025-12-02 19:13:59,607] Trial 19 finished with value: 0.4848178137651822 and parameters: {'max_depth': 3, 'learning_rate': 0.04567998022229332, 'n_estimators': 650, 'subsample': 0.5802248674228837, 'colsample_bytree': 0.8227993639830877, 'min_child_weight': 3, 'gamma': 1.5857561217411984, 'reg_alpha': 0.029499148835328393, 'reg_lambda': 0.13366929154932652, 'max_delta_step': 0}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 2. Best value: 0.511134:  42%|████▏     | 21/50 [03:21<03:56,  8.15s/it]

[I 2025-12-02 19:14:10,349] Trial 20 finished with value: 0.4342105263157895 and parameters: {'max_depth': 9, 'learning_rate': 0.039208478849140596, 'n_estimators': 672, 'subsample': 0.5845047076228314, 'colsample_bytree': 0.7904233326824517, 'min_child_weight': 2, 'gamma': 1.1607203189162316, 'reg_alpha': 0.08668151424249408, 'reg_lambda': 0.08365988522652795, 'max_delta_step': 0}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 2. Best value: 0.511134:  44%|████▍     | 22/50 [03:35<04:40, 10.00s/it]

[I 2025-12-02 19:14:24,660] Trial 22 finished with value: 0.4726720647773279 and parameters: {'max_depth': 9, 'learning_rate': 0.03210932900952524, 'n_estimators': 410, 'subsample': 0.6076618098177596, 'colsample_bytree': 0.7890008760038993, 'min_child_weight': 2, 'gamma': 3.0438661256913715, 'reg_alpha': 0.10392668453057534, 'reg_lambda': 0.05342779572117489, 'max_delta_step': 0}. Best is trial 2 with value: 0.5111336032388664.

Best trial: 24. Best value: 0.537449:  46%|████▌     | 23/50 [03:45<04:26,  9.87s/it]

[I 2025-12-02 19:14:34,233] Trial 24 finished with value: 0.5374493927125505 and parameters: {'max_depth': 8, 'learning_rate': 0.07089662384039062, 'n_estimators': 450, 'subsample': 0.6417049445415929, 'colsample_bytree': 0.6305688537750265, 'min_child_weight': 2, 'gamma': 1.676906579784889, 'reg_alpha': 0.0008969197254230472, 'reg_lambda': 0.029866680068340264, 'max_delta_step': 8}. Best is trial 24 with value: 0.5374493927125505.

Best trial: 24. Best value: 0.537449:  48%|████▊     | 24/50 [04:01<05:03, 11.69s/it]

[I 2025-12-02 19:14:50,152] Trial 21 finished with value: 0.4919028340080972 and parameters: {'max_depth': 9, 'learning_rate': 0.034382589239337076, 'n_estimators': 1206, 'subsample': 0.5908905240009267, 'colsample_bytree': 0.8256697086536323, 'min_child_weight': 2, 'gamma': 3.0585919553323277, 'reg_alpha': 0.06577091968085148, 'reg_lambda': 0.0418777031691462, 'max_delta_step': 0}. Best is trial 24 with value: 0.5374493927125505.

Best trial: 24. Best value: 0.537449:  50%|█████     | 25/50 [04:07<04:11, 10.08s/it]

[I 2025-12-02 19:14:56,480] Trial 23 finished with value: 0.4919028340080972 and parameters: {'max_depth': 9, 'learning_rate': 0.02227985262349918, 'n_estimators': 1161, 'subsample': 0.6199334257261471, 'colsample_bytree': 0.6296217487843021, 'min_child_weight': 2, 'gamma': 3.0742435313652443, 'reg_alpha': 6.80687063536155e-06, 'reg_lambda': 0.026923089391934114, 'max_delta_step': 8}. Best is trial 24 with value: 0.5374493927125505.

Best trial: 24. Best value: 0.537449:  52%|█████▏    | 26/50 [04:08<02:58,  7.44s/it]

[I 2025-12-02 19:14:57,753] Trial 25 finished with value: 0.38461538461538464 and parameters: {'max_depth': 8, 'learning_rate': 0.060934307507829924, 'n_estimators': 757, 'subsample': 0.653484242063845, 'colsample_bytree': 0.627491100499876, 'min_child_weight': 4, 'gamma': 1.3756494200970368, 'reg_alpha': 0.0010087937434762714, 'reg_lambda': 0.02057368917936894, 'max_delta_step': 8}. Best is trial 24 with value: 0.5374493927125505.

Best trial: 24. Best value: 0.537449:  54%|█████▍    | 27/50 [04:11<02:19,  6.09s/it]

[I 2025-12-02 19:15:00,694] Trial 26 finished with value: 0.4392712550607287 and parameters: {'max_depth': 8, 'learning_rate': 0.0728571968259704, 'n_estimators': 513, 'subsample': 0.633277883293985, 'colsample_bytree': 0.6110614223376308, 'min_child_weight': 2, 'gamma': 1.7024939124013236, 'reg_alpha': 1.2329452410256095e-05, 'reg_lambda': 0.011961082413281504, 'max_delta_step': 8}. Best is trial 24 with value: 0.5374493927125505.

Best trial: 24. Best value: 0.537449:  56%|█████▌    | 28/50 [04:18<02:20,  6.37s/it]

[I 2025-12-02 19:15:07,707] Trial 27 finished with value: 0.36538461538461536 and parameters: {'max_depth': 8, 'learning_rate': 0.06477987437946776, 'n_estimators': 354, 'subsample': 0.6504763528284582, 'colsample_bytree': 0.6244400319641776, 'min_child_weight': 4, 'gamma': 1.5484722044016623, 'reg_alpha': 8.712843374602906e-06, 'reg_lambda': 0.012028031611228701, 'max_delta_step': 8}. Best is trial 24 with value: 0.5374493927125505.

Best trial: 24. Best value: 0.537449:  58%|█████▊    | 29/50 [04:23<02:06,  6.02s/it]

[I 2025-12-02 19:15:12,936] Trial 28 pruned.

Best trial: 24. Best value: 0.537449:  60%|██████    | 30/50 [04:34<02:31,  7.55s/it]

[I 2025-12-02 19:15:24,056] Trial 30 finished with value: 0.4919028340080972 and parameters: {'max_depth': 10, 'learning_rate': 0.09708451347067715, 'n_estimators': 303, 'subsample': 0.7473490618911225, 'colsample_bytree': 0.7114779904401548, 'min_child_weight': 1, 'gamma': 0.6154218821654021, 'reg_alpha': 0.0007958125740503408, 'reg_lambda': 0.5081339961534846, 'max_delta_step': 10}. Best is trial 24 with value: 0.5374493927125505.

Best trial: 29. Best value: 0.563765:  62%|██████▏   | 31/50 [04:48<02:59,  9.47s/it]

[I 2025-12-02 19:15:37,992] Trial 29 finished with value: 0.5637651821862348 and parameters: {'max_depth': 10, 'learning_rate': 0.07081886123864249, 'n_estimators': 525, 'subsample': 0.7477270586082062, 'colsample_bytree': 0.6148306080272667, 'min_child_weight': 1, 'gamma': 2.0115447036442817, 'reg_alpha': 3.0460963588229307e-06, 'reg_lambda': 0.5652171972468268, 'max_delta_step': 10}. Best is trial 29 with value: 0.5637651821862348.

Best trial: 29. Best value: 0.563765:  64%|██████▍   | 32/50 [04:53<02:22,  7.94s/it]

[I 2025-12-02 19:15:42,374] Trial 31 finished with value: 0.5111336032388664 and parameters: {'max_depth': 10, 'learning_rate': 0.11047999501694968, 'n_estimators': 499, 'subsample': 0.7666007816969892, 'colsample_bytree': 0.7239341521625934, 'min_child_weight': 1, 'gamma': 0.502563315921239, 'reg_alpha': 0.0005319945151969334, 'reg_lambda': 0.6479595094068749, 'max_delta_step': 10}. Best is trial 29 with value: 0.5637651821862348.

Best trial: 29. Best value: 0.563765:  66%|██████▌   | 33/50 [05:11<03:09, 11.16s/it]

[I 2025-12-02 19:16:01,043] Trial 32 finished with value: 0.4919028340080972 and parameters: {'max_depth': 10, 'learning_rate': 0.1202217891469061, 'n_estimators': 747, 'subsample': 0.7447590208383301, 'colsample_bytree': 0.7145506750919765, 'min_child_weight': 1, 'gamma': 2.0077235499422406, 'reg_alpha': 0.0010013064994074299, 'reg_lambda': 0.00028464657461358815, 'max_delta_step': 10}. Best is trial 29 with value: 0.5637651821862348.

Best trial: 29. Best value: 0.563765:  68%|██████▊   | 34/50 [05:20<02:46, 10.42s/it]

[I 2025-12-02 19:16:09,732] Trial 33 finished with value: 0.5374493927125505 and parameters: {'max_depth': 6, 'learning_rate': 0.12055564565218421, 'n_estimators': 759, 'subsample': 0.7988993626510877, 'colsample_bytree': 0.5543235687207897, 'min_child_weight': 1, 'gamma': 2.0581404509699217, 'reg_alpha': 2.507205834639609e-06, 'reg_lambda': 9.457995028731168e-05, 'max_delta_step': 2}. Best is trial 29 with value: 0.5637651821862348.

Best trial: 29. Best value: 0.563765:  70%|███████   | 35/50 [05:31<02:39, 10.61s/it]

[I 2025-12-02 19:16:20,795] Trial 34 finished with value: 0.5182186234817814 and parameters: {'max_depth': 10, 'learning_rate': 0.12080022745341805, 'n_estimators': 724, 'subsample': 0.8030586471147823, 'colsample_bytree': 0.6588102538391585, 'min_child_weight': 1, 'gamma': 1.9081368363210574, 'reg_alpha': 3.856856176541824e-06, 'reg_lambda': 0.0001882728889997079, 'max_delta_step': 9}. Best is trial 29 with value: 0.5637651821862348.

Best trial: 29. Best value: 0.563765:  72%|███████▏  | 36/50 [05:35<02:01,  8.67s/it]

[I 2025-12-02 19:16:24,940] Trial 35 finished with value: 0.4919028340080972 and parameters: {'max_depth': 10, 'learning_rate': 0.1360820847932178, 'n_estimators': 738, 'subsample': 0.790837870921278, 'colsample_bytree': 0.6560982065523537, 'min_child_weight': 1, 'gamma': 2.022693951763996, 'reg_alpha': 0.0002075399589214947, 'reg_lambda': 0.0005370051863055939, 'max_delta_step': 9}. Best is trial 29 with value: 0.5637651821862348.

Best trial: 29. Best value: 0.563765:  76%|███████▌  | 38/50 [06:12<02:23, 11.98s/it]

[I 2025-12-02 19:17:01,491] Trial 36 finished with value: 0.5040485829959513 and parameters: {'max_depth': 6, 'learning_rate': 0.08250841001820824, 'n_estimators': 863, 'subsample': 0.8128557405535854, 'colsample_bytree': 0.6576357017460144, 'min_child_weight': 1, 'gamma': 2.633632896745598, 'reg_alpha': 3.386712889910041e-06, 'reg_lambda': 6.316364417061001, 'max_delta_step': 9}. Best is trial 29 with value: 0.5637651821862348.
[I 2025-12-02 19:17:01,657] Trial 37 finished with value: 0.4726720647773279 and parameters: {'max_depth': 6, 'learning_rate': 0.15321403287699564, 'n_estimators': 924, 'subsample': 0.8217053886160287, 'colsample_bytree': 0.5541950737891918, 'min_child_weight': 1, 'gamma': 2.6180677385701228, 'reg_alpha': 1.5331027842552273e-06, 'reg_lambda': 0.00018194838299781887, 'max_delta_step': 2}. Best is trial 29 with value: 0.5637651821862348.

Best trial: 29. Best value: 0.563765:  78%|███████▊  | 39/50 [06:17<01:48,  9.89s/it]

[I 2025-12-02 19:17:06,690] Trial 38 finished with value: 0.4726720647773279 and parameters: {'max_depth': 10, 'learning_rate': 0.29960232457863406, 'n_estimators': 863, 'subsample': 0.8120427510547645, 'colsample_bytree': 0.560885064925337, 'min_child_weight': 1, 'gamma': 2.135403285818755, 'reg_alpha': 2.6959247265221687e-06, 'reg_lambda': 0.000250671690578823, 'max_delta_step': 9}. Best is trial 29 with value: 0.5637651821862348.

Best trial: 29. Best value: 0.563765:  80%|████████  | 40/50 [06:25<01:32,  9.21s/it]

[I 2025-12-02 19:17:14,315] Trial 39 finished with value: 0.4726720647773279 and parameters: {'max_depth': 6, 'learning_rate': 0.16561516639635895, 'n_estimators': 863, 'subsample': 0.8171226877708286, 'colsample_bytree': 0.5717920429885676, 'min_child_weight': 1, 'gamma': 2.760086864623203, 'reg_alpha': 1.7466043338025346e-06, 'reg_lambda': 2.1733370988288125e-05, 'max_delta_step': 9}. Best is trial 29 with value: 0.5637651821862348.

Best trial: 29. Best value: 0.563765:  82%|████████▏ | 41/50 [06:28<01:06,  7.35s/it]

[I 2025-12-02 19:17:17,328] Trial 40 finished with value: 0.46558704453441296 and parameters: {'max_depth': 10, 'learning_rate': 0.1734770502852583, 'n_estimators': 202, 'subsample': 0.8852572744470133, 'colsample_bytree': 0.556628015349983, 'min_child_weight': 1, 'gamma': 2.268052872571122, 'reg_alpha': 1.1919037372380297e-06, 'reg_lambda': 4.0761601342938116e-05, 'max_delta_step': 2}. Best is trial 29 with value: 0.5637651821862348.

Best trial: 29. Best value: 0.563765:  84%|████████▍ | 42/50 [06:31<00:49,  6.25s/it]

[I 2025-12-02 19:17:20,991] Trial 43 pruned.

Best trial: 29. Best value: 0.563765:  86%|████████▌ | 43/50 [06:34<00:35,  5.12s/it]

[I 2025-12-02 19:17:23,482] Trial 41 finished with value: 0.5637651821862348 and parameters: {'max_depth': 10, 'learning_rate': 0.16593184672821326, 'n_estimators': 428, 'subsample': 0.7114577906202136, 'colsample_bytree': 0.5827608055284139, 'min_child_weight': 2, 'gamma': 2.272205375509182, 'reg_alpha': 8.233729861132027e-07, 'reg_lambda': 4.461746820539968e-06, 'max_delta_step': 7}. Best is trial 29 with value: 0.5637651821862348.

Best trial: 29. Best value: 0.563765:  88%|████████▊ | 44/50 [06:57<01:02, 10.41s/it]

[I 2025-12-02 19:17:46,240] Trial 46 finished with value: 0.4726720647773279 and parameters: {'max_depth': 9, 'learning_rate': 0.08355765043425167, 'n_estimators': 437, 'subsample': 0.7185136331236371, 'colsample_bytree': 0.5951289158679608, 'min_child_weight': 2, 'gamma': 1.8102328521875681, 'reg_alpha': 3.7449460467875745e-07, 'reg_lambda': 2.908813328505261e-06, 'max_delta_step': 7}. Best is trial 29 with value: 0.5637651821862348.

Best trial: 29. Best value: 0.563765:  90%|█████████ | 45/50 [07:03<00:46,  9.33s/it]

[I 2025-12-02 19:17:53,040] Trial 42 finished with value: 0.5374493927125505 and parameters: {'max_depth': 5, 'learning_rate': 0.17053604889779184, 'n_estimators': 1021, 'subsample': 0.8878607794426057, 'colsample_bytree': 0.5836572164843783, 'min_child_weight': 2, 'gamma': 1.7612849468822502, 'reg_alpha': 5.730004387050385e-07, 'reg_lambda': 3.195561825539322e-06, 'max_delta_step': 7}. Best is trial 29 with value: 0.5637651821862348.

Best trial: 29. Best value: 0.563765:  92%|█████████▏| 46/50 [07:11<00:35,  8.85s/it]

[I 2025-12-02 19:18:00,772] Trial 44 finished with value: 0.4989878542510121 and parameters: {'max_depth': 7, 'learning_rate': 0.1224297177281382, 'n_estimators': 985, 'subsample': 0.7173765124325664, 'colsample_bytree': 0.5026207757185157, 'min_child_weight': 2, 'gamma': 1.8708022498025776, 'reg_alpha': 7.428704431508026e-08, 'reg_lambda': 6.724430256641687e-07, 'max_delta_step': 1}. Best is trial 29 with value: 0.5637651821862348.

Best trial: 29. Best value: 0.563765:  94%|█████████▍| 47/50 [07:14<00:21,  7.17s/it]

[I 2025-12-02 19:18:04,020] Trial 47 finished with value: 0.5111336032388664 and parameters: {'max_depth': 10, 'learning_rate': 0.22158365157050447, 'n_estimators': 355, 'subsample': 0.7120560718369027, 'colsample_bytree': 0.5253283749834929, 'min_child_weight': 2, 'gamma': 2.303735025467794, 'reg_alpha': 7.985434345472942e-08, 'reg_lambda': 2.079459227435491e-06, 'max_delta_step': 7}. Best is trial 29 with value: 0.5637651821862348.

Best trial: 29. Best value: 0.563765:  96%|█████████▌| 48/50 [07:15<00:10,  5.34s/it]

[I 2025-12-02 19:18:05,099] Trial 49 pruned.

Best trial: 29. Best value: 0.563765:  98%|█████████▊| 49/50 [07:18<00:04,  4.55s/it]

[I 2025-12-02 19:18:07,811] Trial 45 finished with value: 0.46558704453441296 and parameters: {'max_depth': 7, 'learning_rate': 0.08331588639908291, 'n_estimators': 980, 'subsample': 0.7128456515340246, 'colsample_bytree': 0.5905175662639947, 'min_child_weight': 2, 'gamma': 4.24695916873525, 'reg_alpha': 2.774386774152318e-07, 'reg_lambda': 3.891879920517488e-06, 'max_delta_step': 1}. Best is trial 29 with value: 0.5637651821862348.

Best trial: 48. Best value: 0.616397: 100%|██████████| 50/50 [07:32<00:00,  9.06s/it]

[I 2025-12-02 19:18:22,030] Trial 48 finished with value: 0.6163967611336032 and parameters: {'max_depth': 4, 'learning_rate': 0.22113882733880424, 'n_estimators': 1010, 'subsample': 0.7201231333517965, 'colsample_bytree': 0.5310709958282599, 'min_child_weight': 2, 'gamma': 1.062013225429728, 'reg_alpha': 5.174390733890012e-08, 'reg_lambda': 3.265892251653168e-07, 'max_delta_step': 5}. Best is trial 48 with value: 0.6163967611336032.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.616397                0.457143      0.542857

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  -0.09759          0.714286               0.2        50          45

   test_size
0         12
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.616397                0.457143      0.542857

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  -0.09759          0.714286               0.2        50          45

   test_size
0         12

In [ ]:

datasets = task_hf_compensated_temp_emb_lbl_ad_lbd

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_lbd_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_handcrafted_temporal_emb_compensated_ad_lbd_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param= "diagnosis_y",
)
print(summary)

[I 2025-12-02 19:18:27,110] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 45, Test size: 12
Using Leave-One-Out CV with 45 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.504049:   2%|▏         | 1/50 [00:23<19:00, 23.27s/it]

[I 2025-12-02 19:18:50,370] Trial 1 finished with value: 0.5040485829959513 and parameters: {'max_depth': 6, 'learning_rate': 0.2635032767359791, 'n_estimators': 538, 'subsample': 0.6875277935734925, 'colsample_bytree': 0.7745306117094798, 'min_child_weight': 6, 'gamma': 2.712516126001801, 'reg_alpha': 5.530576911155926e-08, 'reg_lambda': 0.01074907901690856, 'max_delta_step': 4}. Best is trial 1 with value: 0.5040485829959513.

Best trial: 1. Best value: 0.504049:   4%|▍         | 2/50 [00:26<09:21, 11.71s/it]

[I 2025-12-02 19:18:53,984] Trial 2 finished with value: 0.057692307692307696 and parameters: {'max_depth': 6, 'learning_rate': 0.060877246587161996, 'n_estimators': 666, 'subsample': 0.7232783874990687, 'colsample_bytree': 0.634864977416617, 'min_child_weight': 7, 'gamma': 4.231396055756187, 'reg_alpha': 2.718094419903265e-05, 'reg_lambda': 1.2232418691807755e-08, 'max_delta_step': 1}. Best is trial 1 with value: 0.5040485829959513.

Best trial: 1. Best value: 0.504049:   6%|▌         | 3/50 [00:39<09:31, 12.16s/it]

[I 2025-12-02 19:19:06,685] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.07468162447935571, 'n_estimators': 998, 'subsample': 0.96338675346606, 'colsample_bytree': 0.796133326908828, 'min_child_weight': 5, 'gamma': 3.572447037885854, 'reg_alpha': 0.0009696053698610202, 'reg_lambda': 0.05953626224459054, 'max_delta_step': 9}. Best is trial 1 with value: 0.5040485829959513.

Best trial: 1. Best value: 0.504049:   8%|▊         | 4/50 [00:58<11:17, 14.73s/it]

[I 2025-12-02 19:19:25,358] Trial 0 finished with value: 0.3360323886639676 and parameters: {'max_depth': 4, 'learning_rate': 0.01660104382995504, 'n_estimators': 1461, 'subsample': 0.723152775361062, 'colsample_bytree': 0.8849431596375923, 'min_child_weight': 4, 'gamma': 1.421207544186135, 'reg_alpha': 4.980220601210072e-06, 'reg_lambda': 0.0006106395523073803, 'max_delta_step': 6}. Best is trial 1 with value: 0.5040485829959513.

Best trial: 1. Best value: 0.504049:  10%|█         | 5/50 [01:01<08:04, 10.77s/it]

[I 2025-12-02 19:19:29,096] Trial 6 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.07562645290849913, 'n_estimators': 531, 'subsample': 0.5155209817781068, 'colsample_bytree': 0.939297029986875, 'min_child_weight': 7, 'gamma': 0.7253905316950127, 'reg_alpha': 0.071568947997431, 'reg_lambda': 0.0002714221377634606, 'max_delta_step': 1}. Best is trial 1 with value: 0.5040485829959513.

Best trial: 1. Best value: 0.504049:  12%|█▏        | 6/50 [01:09<06:58,  9.52s/it]

[I 2025-12-02 19:19:36,186] Trial 4 finished with value: 0.42004048582995945 and parameters: {'max_depth': 5, 'learning_rate': 0.2983146294356798, 'n_estimators': 1171, 'subsample': 0.828541476650352, 'colsample_bytree': 0.7798889407228586, 'min_child_weight': 3, 'gamma': 2.1308288805602382, 'reg_alpha': 0.0016930350767191235, 'reg_lambda': 0.8126764810012044, 'max_delta_step': 6}. Best is trial 1 with value: 0.5040485829959513.

Best trial: 1. Best value: 0.504049:  14%|█▍        | 7/50 [01:15<06:01,  8.40s/it]

[I 2025-12-02 19:19:42,292] Trial 7 finished with value: 0.10526315789473684 and parameters: {'max_depth': 6, 'learning_rate': 0.03849287507004524, 'n_estimators': 414, 'subsample': 0.7686218600919352, 'colsample_bytree': 0.6216189533365996, 'min_child_weight': 8, 'gamma': 4.4157839259793805, 'reg_alpha': 0.0014405230378769012, 'reg_lambda': 3.259253181857488e-06, 'max_delta_step': 5}. Best is trial 1 with value: 0.5040485829959513.

Best trial: 1. Best value: 0.504049:  16%|█▌        | 8/50 [01:20<05:13,  7.47s/it]

[I 2025-12-02 19:19:47,770] Trial 8 finished with value: 0.34615384615384615 and parameters: {'max_depth': 9, 'learning_rate': 0.03861121070653785, 'n_estimators': 444, 'subsample': 0.6759823111512868, 'colsample_bytree': 0.7918208309885448, 'min_child_weight': 4, 'gamma': 0.7475002504239903, 'reg_alpha': 5.038574928231548e-08, 'reg_lambda': 9.936047572566054e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.5040485829959513.

Best trial: 5. Best value: 0.539474:  18%|█▊        | 9/50 [01:22<03:50,  5.61s/it]

[I 2025-12-02 19:19:49,303] Trial 5 finished with value: 0.5394736842105263 and parameters: {'max_depth': 9, 'learning_rate': 0.07944332768079601, 'n_estimators': 1439, 'subsample': 0.7513092334860034, 'colsample_bytree': 0.8162340332708475, 'min_child_weight': 4, 'gamma': 1.458298371155119, 'reg_alpha': 0.824122023947682, 'reg_lambda': 0.008700876841912055, 'max_delta_step': 7}. Best is trial 5 with value: 0.5394736842105263.

Best trial: 5. Best value: 0.539474:  20%|██        | 10/50 [01:33<04:51,  7.28s/it]

[I 2025-12-02 19:20:00,301] Trial 11 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.11127706971212126, 'n_estimators': 288, 'subsample': 0.8779583113972833, 'colsample_bytree': 0.8162577913260562, 'min_child_weight': 9, 'gamma': 0.4530382474331518, 'reg_alpha': 1.2126787304701069e-06, 'reg_lambda': 0.05100342568601845, 'max_delta_step': 6}. Best is trial 5 with value: 0.5394736842105263.

Best trial: 5. Best value: 0.539474:  22%|██▏       | 11/50 [01:33<03:21,  5.17s/it]

[I 2025-12-02 19:20:00,677] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.02836205370124635, 'n_estimators': 573, 'subsample': 0.7398527142535629, 'colsample_bytree': 0.9735384779309793, 'min_child_weight': 7, 'gamma': 4.399684610323039, 'reg_alpha': 0.01887227162762834, 'reg_lambda': 9.995082958755291e-05, 'max_delta_step': 0}. Best is trial 5 with value: 0.5394736842105263.

Best trial: 5. Best value: 0.539474:  24%|██▍       | 12/50 [01:39<03:25,  5.40s/it]

[I 2025-12-02 19:20:06,601] Trial 10 finished with value: 0.3269230769230769 and parameters: {'max_depth': 6, 'learning_rate': 0.177933385225307, 'n_estimators': 596, 'subsample': 0.838236784541007, 'colsample_bytree': 0.811051122741238, 'min_child_weight': 5, 'gamma': 1.7341217141684862, 'reg_alpha': 1.0146051214740089e-08, 'reg_lambda': 3.737031099495792e-07, 'max_delta_step': 10}. Best is trial 5 with value: 0.5394736842105263.

Best trial: 5. Best value: 0.539474:  26%|██▌       | 13/50 [01:41<02:41,  4.37s/it]

[I 2025-12-02 19:20:08,612] Trial 12 pruned.

Best trial: 5. Best value: 0.539474:  28%|██▊       | 14/50 [01:45<02:32,  4.24s/it]

[I 2025-12-02 19:20:12,564] Trial 13 pruned.

Best trial: 5. Best value: 0.539474:  30%|███       | 15/50 [01:52<02:54,  4.97s/it]

[I 2025-12-02 19:20:19,228] Trial 17 pruned.

Best trial: 5. Best value: 0.539474:  32%|███▏      | 16/50 [02:08<04:45,  8.39s/it]

[I 2025-12-02 19:20:35,549] Trial 14 finished with value: 0.3724696356275303 and parameters: {'max_depth': 8, 'learning_rate': 0.25069610706754675, 'n_estimators': 812, 'subsample': 0.6000515172787549, 'colsample_bytree': 0.7187799740276718, 'min_child_weight': 1, 'gamma': 2.6273798732777838, 'reg_alpha': 4.564164203259668, 'reg_lambda': 0.012235033250336194, 'max_delta_step': 4}. Best is trial 5 with value: 0.5394736842105263.

Best trial: 5. Best value: 0.539474:  34%|███▍      | 17/50 [02:11<03:43,  6.76s/it]

[I 2025-12-02 19:20:38,522] Trial 19 pruned.

Best trial: 5. Best value: 0.539474:  36%|███▌      | 18/50 [02:15<03:14,  6.07s/it]

[I 2025-12-02 19:20:42,982] Trial 15 finished with value: 0.4109311740890689 and parameters: {'max_depth': 8, 'learning_rate': 0.27164562246403295, 'n_estimators': 873, 'subsample': 0.6113767840777152, 'colsample_bytree': 0.6785695358363592, 'min_child_weight': 1, 'gamma': 2.665456797950653, 'reg_alpha': 5.381644695677882, 'reg_lambda': 0.012447233964010535, 'max_delta_step': 4}. Best is trial 5 with value: 0.5394736842105263.

Best trial: 5. Best value: 0.539474:  38%|███▊      | 19/50 [02:26<03:48,  7.36s/it]

[I 2025-12-02 19:20:53,343] Trial 18 finished with value: 0.31376518218623484 and parameters: {'max_depth': 10, 'learning_rate': 0.15316713790990225, 'n_estimators': 922, 'subsample': 0.6189110914248177, 'colsample_bytree': 0.8861774890760288, 'min_child_weight': 6, 'gamma': 2.8737405155422624, 'reg_alpha': 2.6632780493282474e-07, 'reg_lambda': 0.007018149307214322, 'max_delta_step': 8}. Best is trial 5 with value: 0.5394736842105263.

Best trial: 5. Best value: 0.539474:  40%|████      | 20/50 [02:40<04:42,  9.43s/it]

[I 2025-12-02 19:21:07,585] Trial 16 finished with value: 0.3269230769230769 and parameters: {'max_depth': 8, 'learning_rate': 0.2908112059793196, 'n_estimators': 1492, 'subsample': 0.6008909060083951, 'colsample_bytree': 0.5209738344547433, 'min_child_weight': 1, 'gamma': 2.9582510460916986, 'reg_alpha': 5.582125699185399, 'reg_lambda': 0.006771766482469921, 'max_delta_step': 3}. Best is trial 5 with value: 0.5394736842105263.

Best trial: 20. Best value: 0.563765:  42%|████▏     | 21/50 [03:01<06:16, 12.98s/it]

[I 2025-12-02 19:21:28,850] Trial 20 finished with value: 0.5637651821862348 and parameters: {'max_depth': 10, 'learning_rate': 0.11911931316979585, 'n_estimators': 1280, 'subsample': 0.9976884497776713, 'colsample_bytree': 0.8592253467370127, 'min_child_weight': 3, 'gamma': 0.013044427062685493, 'reg_alpha': 1.4565596595406124e-05, 'reg_lambda': 0.5953700905688567, 'max_delta_step': 8}. Best is trial 20 with value: 0.5637651821862348.

Best trial: 20. Best value: 0.563765:  44%|████▍     | 22/50 [03:05<04:42, 10.09s/it]

[I 2025-12-02 19:21:32,199] Trial 21 finished with value: 0.4676113360323887 and parameters: {'max_depth': 10, 'learning_rate': 0.13992795009874817, 'n_estimators': 1275, 'subsample': 0.7892516022565678, 'colsample_bytree': 0.8606761256809566, 'min_child_weight': 4, 'gamma': 1.8597947607192655, 'reg_alpha': 5.5711217378375184e-05, 'reg_lambda': 0.4179485125393595, 'max_delta_step': 8}. Best is trial 20 with value: 0.5637651821862348.

Best trial: 20. Best value: 0.563765:  46%|████▌     | 23/50 [03:14<04:24,  9.80s/it]

[I 2025-12-02 19:21:41,336] Trial 22 finished with value: 0.4463562753036437 and parameters: {'max_depth': 7, 'learning_rate': 0.10310022405859492, 'n_estimators': 1217, 'subsample': 0.7851148693060798, 'colsample_bytree': 0.8455877064362038, 'min_child_weight': 3, 'gamma': 1.859537949913137, 'reg_alpha': 0.0001262890020177372, 'reg_lambda': 0.31722073977468757, 'max_delta_step': 7}. Best is trial 20 with value: 0.5637651821862348.

Best trial: 20. Best value: 0.563765:  48%|████▊     | 24/50 [03:30<05:08, 11.87s/it]

[I 2025-12-02 19:21:58,015] Trial 23 finished with value: 0.4463562753036437 and parameters: {'max_depth': 7, 'learning_rate': 0.10183728428691657, 'n_estimators': 1272, 'subsample': 0.7736545495636955, 'colsample_bytree': 0.8572734467947478, 'min_child_weight': 3, 'gamma': 1.953185431055926, 'reg_alpha': 6.666102700465739e-05, 'reg_lambda': 0.503644516232145, 'max_delta_step': 7}. Best is trial 20 with value: 0.5637651821862348.

Best trial: 20. Best value: 0.563765:  50%|█████     | 25/50 [03:39<04:34, 10.97s/it]

[I 2025-12-02 19:22:06,889] Trial 27 pruned.

Best trial: 24. Best value: 0.616397:  52%|█████▏    | 26/50 [03:53<04:39, 11.67s/it]

[I 2025-12-02 19:22:20,181] Trial 24 finished with value: 0.6163967611336032 and parameters: {'max_depth': 10, 'learning_rate': 0.10058097500377051, 'n_estimators': 1296, 'subsample': 0.9759329856296408, 'colsample_bytree': 0.8352173795507929, 'min_child_weight': 3, 'gamma': 0.09689924735076642, 'reg_alpha': 4.556087511515366e-05, 'reg_lambda': 0.5624341386461892, 'max_delta_step': 7}. Best is trial 24 with value: 0.6163967611336032.

Best trial: 24. Best value: 0.616397:  54%|█████▍    | 27/50 [03:57<03:37,  9.47s/it]

[I 2025-12-02 19:22:24,525] Trial 25 finished with value: 0.5374493927125505 and parameters: {'max_depth': 9, 'learning_rate': 0.09677206669643515, 'n_estimators': 1314, 'subsample': 0.9918842069975851, 'colsample_bytree': 0.8560111267015849, 'min_child_weight': 3, 'gamma': 0.021624268754406487, 'reg_alpha': 9.965798810292428e-05, 'reg_lambda': 0.26472940572301884, 'max_delta_step': 7}. Best is trial 24 with value: 0.6163967611336032.

Best trial: 24. Best value: 0.616397:  56%|█████▌    | 28/50 [04:07<03:32,  9.64s/it]

[I 2025-12-02 19:22:34,576] Trial 26 finished with value: 0.5708502024291497 and parameters: {'max_depth': 9, 'learning_rate': 0.18507954325237536, 'n_estimators': 1364, 'subsample': 0.9381880644525549, 'colsample_bytree': 0.7560885111166531, 'min_child_weight': 3, 'gamma': 0.21406237004851764, 'reg_alpha': 7.71622975387524e-06, 'reg_lambda': 6.269759659406927, 'max_delta_step': 7}. Best is trial 24 with value: 0.6163967611336032.

Best trial: 24. Best value: 0.616397:  58%|█████▊    | 29/50 [04:31<04:53, 13.98s/it]

[I 2025-12-02 19:22:58,665] Trial 28 finished with value: 0.42004048582995945 and parameters: {'max_depth': 9, 'learning_rate': 0.054333139574079245, 'n_estimators': 1357, 'subsample': 0.6860682866002947, 'colsample_bytree': 0.7581222505917012, 'min_child_weight': 2, 'gamma': 0.12191299341203653, 'reg_alpha': 0.009332690668371411, 'reg_lambda': 0.10103365470487756, 'max_delta_step': 9}. Best is trial 24 with value: 0.6163967611336032.

Best trial: 24. Best value: 0.616397:  60%|██████    | 30/50 [04:49<05:04, 15.22s/it]

[I 2025-12-02 19:23:16,783] Trial 29 finished with value: 0.4989878542510121 and parameters: {'max_depth': 10, 'learning_rate': 0.08128665607934404, 'n_estimators': 1352, 'subsample': 0.9351783924626115, 'colsample_bytree': 0.7404794487737882, 'min_child_weight': 2, 'gamma': 1.032889385921469, 'reg_alpha': 0.015039159386888733, 'reg_lambda': 3.040396284186215, 'max_delta_step': 9}. Best is trial 24 with value: 0.6163967611336032.

Best trial: 24. Best value: 0.616397:  62%|██████▏   | 31/50 [04:57<04:08, 13.06s/it]

[I 2025-12-02 19:23:24,788] Trial 31 finished with value: 0.4919028340080972 and parameters: {'max_depth': 10, 'learning_rate': 0.19756606469056467, 'n_estimators': 1376, 'subsample': 0.9251718324259051, 'colsample_bytree': 0.7324278772466096, 'min_child_weight': 2, 'gamma': 0.4706405926622807, 'reg_alpha': 4.212899567963676e-06, 'reg_lambda': 3.329666663663879, 'max_delta_step': 9}. Best is trial 24 with value: 0.6163967611336032.

Best trial: 24. Best value: 0.616397:  64%|██████▍   | 32/50 [05:00<02:58,  9.89s/it]

[I 2025-12-02 19:23:27,290] Trial 30 finished with value: 0.4726720647773279 and parameters: {'max_depth': 10, 'learning_rate': 0.052268311811904854, 'n_estimators': 1371, 'subsample': 0.9451457048947125, 'colsample_bytree': 0.9912468187521127, 'min_child_weight': 2, 'gamma': 1.0693157604545198, 'reg_alpha': 0.007851777685758081, 'reg_lambda': 2.1234047890815098, 'max_delta_step': 9}. Best is trial 24 with value: 0.6163967611336032.

Best trial: 24. Best value: 0.616397:  66%|██████▌   | 33/50 [05:17<03:24, 12.03s/it]

[I 2025-12-02 19:23:44,303] Trial 32 finished with value: 0.4008097165991903 and parameters: {'max_depth': 10, 'learning_rate': 0.20106718298220097, 'n_estimators': 1091, 'subsample': 0.9357337472888335, 'colsample_bytree': 0.9127868508281545, 'min_child_weight': 2, 'gamma': 0.9605742906768338, 'reg_alpha': 5.669960815983456e-06, 'reg_lambda': 2.396897465944584, 'max_delta_step': 9}. Best is trial 24 with value: 0.6163967611336032.

Best trial: 24. Best value: 0.616397:  68%|██████▊   | 34/50 [05:29<03:12, 12.02s/it]

[I 2025-12-02 19:23:56,296] Trial 36 pruned.

Best trial: 24. Best value: 0.616397:  70%|███████   | 35/50 [05:32<02:20,  9.35s/it]

[I 2025-12-02 19:23:59,420] Trial 33 finished with value: 0.6093117408906883 and parameters: {'max_depth': 10, 'learning_rate': 0.1881739685322732, 'n_estimators': 1111, 'subsample': 0.9262095370373292, 'colsample_bytree': 0.9336056986667493, 'min_child_weight': 4, 'gamma': 0.4889424294572107, 'reg_alpha': 1.2072711077985062e-05, 'reg_lambda': 2.016065414406517, 'max_delta_step': 5}. Best is trial 24 with value: 0.6163967611336032.

Best trial: 24. Best value: 0.616397:  72%|███████▏  | 36/50 [05:43<02:20, 10.01s/it]

[I 2025-12-02 19:24:10,966] Trial 35 finished with value: 0.6163967611336032 and parameters: {'max_depth': 9, 'learning_rate': 0.12685191867942922, 'n_estimators': 1125, 'subsample': 0.9050714511865527, 'colsample_bytree': 0.9195325397531863, 'min_child_weight': 4, 'gamma': 0.4134063212567193, 'reg_alpha': 9.487234564472245e-06, 'reg_lambda': 1.166972660779489, 'max_delta_step': 6}. Best is trial 24 with value: 0.6163967611336032.

Best trial: 24. Best value: 0.616397:  74%|███████▍  | 37/50 [05:53<02:07,  9.78s/it]

[I 2025-12-02 19:24:20,198] Trial 34 finished with value: 0.5516194331983806 and parameters: {'max_depth': 10, 'learning_rate': 0.06001372468767591, 'n_estimators': 1442, 'subsample': 0.9572311065264743, 'colsample_bytree': 0.9118016951009795, 'min_child_weight': 4, 'gamma': 1.2393337774493929, 'reg_alpha': 1.7845577154636406e-05, 'reg_lambda': 1.4725577727206252, 'max_delta_step': 6}. Best is trial 24 with value: 0.6163967611336032.

Best trial: 24. Best value: 0.616397:  76%|███████▌  | 38/50 [06:01<01:52,  9.38s/it]

[I 2025-12-02 19:24:28,671] Trial 40 pruned.

Best trial: 24. Best value: 0.616397:  78%|███████▊  | 39/50 [06:12<01:47,  9.75s/it]

[I 2025-12-02 19:24:39,270] Trial 41 pruned.

Best trial: 24. Best value: 0.616397:  80%|████████  | 40/50 [06:16<01:20,  8.06s/it]

[I 2025-12-02 19:24:43,388] Trial 37 finished with value: 0.5445344129554656 and parameters: {'max_depth': 9, 'learning_rate': 0.08379073884816045, 'n_estimators': 1218, 'subsample': 0.970758828965277, 'colsample_bytree': 0.8276978002970098, 'min_child_weight': 4, 'gamma': 0.37410198996799204, 'reg_alpha': 0.00035387135931876974, 'reg_lambda': 0.001951234165996159, 'max_delta_step': 8}. Best is trial 24 with value: 0.6163967611336032.

Best trial: 24. Best value: 0.616397:  82%|████████▏ | 41/50 [06:22<01:07,  7.45s/it]

[I 2025-12-02 19:24:49,410] Trial 42 pruned.

Best trial: 24. Best value: 0.616397:  84%|████████▍ | 42/50 [06:22<00:43,  5.38s/it]

[I 2025-12-02 19:24:49,962] Trial 39 finished with value: 0.5708502024291497 and parameters: {'max_depth': 9, 'learning_rate': 0.1529532947244828, 'n_estimators': 987, 'subsample': 0.913071057872511, 'colsample_bytree': 0.960327565898646, 'min_child_weight': 4, 'gamma': 0.3567458530559973, 'reg_alpha': 0.0005356559323138084, 'reg_lambda': 1.2016900666794825, 'max_delta_step': 5}. Best is trial 24 with value: 0.6163967611336032.

Best trial: 24. Best value: 0.616397:  86%|████████▌ | 43/50 [06:23<00:27,  3.91s/it]

[I 2025-12-02 19:24:50,448] Trial 38 finished with value: 0.597165991902834 and parameters: {'max_depth': 10, 'learning_rate': 0.16412906577237632, 'n_estimators': 1188, 'subsample': 0.9687108288960035, 'colsample_bytree': 0.9471403878781595, 'min_child_weight': 3, 'gamma': 0.31900773031154656, 'reg_alpha': 1.4570628887443086e-06, 'reg_lambda': 9.445416053584863, 'max_delta_step': 5}. Best is trial 24 with value: 0.6163967611336032.

Best trial: 24. Best value: 0.616397:  88%|████████▊ | 44/50 [06:25<00:20,  3.37s/it]

[I 2025-12-02 19:24:52,553] Trial 43 pruned.

Best trial: 24. Best value: 0.616397:  90%|█████████ | 45/50 [06:33<00:23,  4.71s/it]

[I 2025-12-02 19:25:00,399] Trial 46 pruned.

Best trial: 24. Best value: 0.616397:  92%|█████████▏| 46/50 [06:33<00:13,  3.48s/it]

[I 2025-12-02 19:25:00,992] Trial 47 pruned.

Best trial: 24. Best value: 0.616397:  94%|█████████▍| 47/50 [07:01<00:32, 10.70s/it]

[I 2025-12-02 19:25:28,540] Trial 48 finished with value: 0.5708502024291497 and parameters: {'max_depth': 10, 'learning_rate': 0.09256011792869172, 'n_estimators': 708, 'subsample': 0.9720677473065793, 'colsample_bytree': 0.7709418941499906, 'min_child_weight': 3, 'gamma': 0.2297625362103688, 'reg_alpha': 1.350812035214004e-06, 'reg_lambda': 0.16718903701215174, 'max_delta_step': 6}. Best is trial 24 with value: 0.6163967611336032.

Best trial: 24. Best value: 0.616397:  96%|█████████▌| 48/50 [07:05<00:17,  8.56s/it]

[I 2025-12-02 19:25:32,104] Trial 45 finished with value: 0.5253036437246963 and parameters: {'max_depth': 10, 'learning_rate': 0.20743257941695473, 'n_estimators': 1090, 'subsample': 0.8714574274930728, 'colsample_bytree': 0.921593826790741, 'min_child_weight': 3, 'gamma': 0.2652275410305428, 'reg_alpha': 0.003580141949961681, 'reg_lambda': 1.2062478856806795, 'max_delta_step': 6}. Best is trial 24 with value: 0.6163967611336032.
[I 2025-12-02 19:25:32,299] Trial 44 finished with value: 0.5637651821862348 and parameters: {'max_depth': 10, 'learning_rate': 0.12696027459474796, 'n_estimators': 1098, 'subsample': 0.9939640392035, 'colsample_bytree': 0.9096134734471591, 'min_child_weight': 3, 'gamma': 0.22749001144549233, 'reg_alpha': 2.3821022515624677e-05, 'reg_lambda': 0.8641785843702031, 'max_delta_step': 6}. Best is trial 24 with value: 0.6163967611336032.

Best trial: 24. Best value: 0.616397: 100%|██████████| 50/50 [07:12<00:00,  8.65s/it]

[I 2025-12-02 19:25:39,637] Trial 49 finished with value: 0.597165991902834 and parameters: {'max_depth': 4, 'learning_rate': 0.0648182133652866, 'n_estimators': 1130, 'subsample': 0.9699431122657554, 'colsample_bytree': 0.8930676323456191, 'min_child_weight': 3, 'gamma': 1.4765749869893274, 'reg_alpha': 2.7858429149197088e-05, 'reg_lambda': 0.19432545749173943, 'max_delta_step': 2}. Best is trial 24 with value: 0.6163967611336032.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.616397                0.414286      0.342857

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.169031          0.428571               0.4        50          45

   test_size
0         12
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.616397                0.414286      0.342857

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.169031          0.428571               0.4        50          45

   test_size
0         12

In [ ]:

datasets = task_hf_compensated_freq_emb_lbl_ad_lbd

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_lbd_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_handcrafted_frerq_emb_compensated_ad_lbd_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param= "diagnosis_y",
)
print(summary)
## MCI-AD vs HC -> OPTUNA + XGB

[I 2025-12-02 19:25:44,237] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 45, Test size: 12
Using Leave-One-Out CV with 45 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.537449:   2%|▏         | 1/50 [00:16<13:17, 16.28s/it]

[I 2025-12-02 19:26:00,514] Trial 0 finished with value: 0.5374493927125505 and parameters: {'max_depth': 3, 'learning_rate': 0.0625809898756767, 'n_estimators': 360, 'subsample': 0.6441164084560411, 'colsample_bytree': 0.8216501111007256, 'min_child_weight': 3, 'gamma': 2.3177921007211433, 'reg_alpha': 0.0036668429482628775, 'reg_lambda': 1.446910027733432e-07, 'max_delta_step': 0}. Best is trial 0 with value: 0.5374493927125505.

Best trial: 0. Best value: 0.537449:   4%|▍         | 2/50 [00:31<12:42, 15.88s/it]

[I 2025-12-02 19:26:16,110] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.08532890727930449, 'n_estimators': 777, 'subsample': 0.8401979550997669, 'colsample_bytree': 0.9125589518814454, 'min_child_weight': 5, 'gamma': 1.649574853565428, 'reg_alpha': 4.998551271521254e-07, 'reg_lambda': 4.339641260240818, 'max_delta_step': 5}. Best is trial 0 with value: 0.5374493927125505.

Best trial: 0. Best value: 0.537449:   6%|▌         | 3/50 [00:36<08:29, 10.83s/it]

[I 2025-12-02 19:26:20,930] Trial 3 finished with value: 0.5354251012145749 and parameters: {'max_depth': 8, 'learning_rate': 0.03016492190356521, 'n_estimators': 878, 'subsample': 0.5033830033547615, 'colsample_bytree': 0.5684496839455331, 'min_child_weight': 2, 'gamma': 2.748878446598739, 'reg_alpha': 1.262240594898337e-05, 'reg_lambda': 9.166097353282568, 'max_delta_step': 10}. Best is trial 0 with value: 0.5374493927125505.

Best trial: 0. Best value: 0.537449:   8%|▊         | 4/50 [00:48<08:28, 11.05s/it]

[I 2025-12-02 19:26:32,315] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.11742098801874452, 'n_estimators': 1284, 'subsample': 0.618173981278058, 'colsample_bytree': 0.7076478526030368, 'min_child_weight': 10, 'gamma': 2.569054286323639, 'reg_alpha': 0.011295135664729205, 'reg_lambda': 3.8725912301932017, 'max_delta_step': 6}. Best is trial 0 with value: 0.5374493927125505.

Best trial: 0. Best value: 0.537449:  10%|█         | 5/50 [00:54<06:55,  9.23s/it]

[I 2025-12-02 19:26:38,331] Trial 6 finished with value: 0.5374493927125505 and parameters: {'max_depth': 8, 'learning_rate': 0.06575901091297787, 'n_estimators': 277, 'subsample': 0.7324024367011595, 'colsample_bytree': 0.7769226699597072, 'min_child_weight': 1, 'gamma': 3.8300410622709586, 'reg_alpha': 0.17663040046828568, 'reg_lambda': 0.0003224268403051448, 'max_delta_step': 1}. Best is trial 0 with value: 0.5374493927125505.

Best trial: 0. Best value: 0.537449:  12%|█▏        | 6/50 [01:02<06:33,  8.95s/it]

[I 2025-12-02 19:26:46,726] Trial 4 finished with value: 0.5 and parameters: {'max_depth': 7, 'learning_rate': 0.1955915177990755, 'n_estimators': 1232, 'subsample': 0.739349711252943, 'colsample_bytree': 0.6287554176791634, 'min_child_weight': 7, 'gamma': 0.7562514765251899, 'reg_alpha': 2.8673241527865494e-07, 'reg_lambda': 0.042038426790124865, 'max_delta_step': 3}. Best is trial 0 with value: 0.5374493927125505.

Best trial: 0. Best value: 0.537449:  14%|█▍        | 7/50 [01:03<04:29,  6.26s/it]

[I 2025-12-02 19:26:47,445] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.025584493636025385, 'n_estimators': 325, 'subsample': 0.9652700974614303, 'colsample_bytree': 0.9330113938657254, 'min_child_weight': 8, 'gamma': 2.8826516373372906, 'reg_alpha': 0.022652734503218943, 'reg_lambda': 1.5505580472396646e-05, 'max_delta_step': 5}. Best is trial 0 with value: 0.5374493927125505.

Best trial: 0. Best value: 0.537449:  16%|█▌        | 8/50 [01:16<06:02,  8.62s/it]

[I 2025-12-02 19:27:01,136] Trial 5 finished with value: 0.2692307692307692 and parameters: {'max_depth': 6, 'learning_rate': 0.1577086208695866, 'n_estimators': 1186, 'subsample': 0.5099915749385994, 'colsample_bytree': 0.5022040693628014, 'min_child_weight': 4, 'gamma': 1.7033427300473991, 'reg_alpha': 0.002743879864527928, 'reg_lambda': 4.670220682539614, 'max_delta_step': 5}. Best is trial 0 with value: 0.5374493927125505.

Best trial: 0. Best value: 0.537449:  18%|█▊        | 9/50 [01:23<05:25,  7.94s/it]

[I 2025-12-02 19:27:07,582] Trial 9 finished with value: 0.4919028340080972 and parameters: {'max_depth': 7, 'learning_rate': 0.023440572598417916, 'n_estimators': 402, 'subsample': 0.9234147313052714, 'colsample_bytree': 0.6134145722107411, 'min_child_weight': 2, 'gamma': 2.9931381550665552, 'reg_alpha': 0.007737306158092208, 'reg_lambda': 1.5840428631719362e-05, 'max_delta_step': 3}. Best is trial 0 with value: 0.5374493927125505.

Best trial: 0. Best value: 0.537449:  20%|██        | 10/50 [01:28<04:42,  7.07s/it]

[I 2025-12-02 19:27:12,709] Trial 8 finished with value: 0.057692307692307696 and parameters: {'max_depth': 8, 'learning_rate': 0.03651389239898184, 'n_estimators': 926, 'subsample': 0.5882403861111707, 'colsample_bytree': 0.613409917268948, 'min_child_weight': 6, 'gamma': 1.5244989485294003, 'reg_alpha': 6.975854334009072e-06, 'reg_lambda': 0.0022193057317070014, 'max_delta_step': 10}. Best is trial 0 with value: 0.5374493927125505.

Best trial: 0. Best value: 0.537449:  22%|██▏       | 11/50 [01:34<04:20,  6.67s/it]

[I 2025-12-02 19:27:18,461] Trial 13 pruned.

Best trial: 0. Best value: 0.537449:  24%|██▍       | 12/50 [01:35<03:09,  5.00s/it]

[I 2025-12-02 19:27:19,629] Trial 10 pruned.

Best trial: 0. Best value: 0.537449:  26%|██▌       | 13/50 [01:44<03:50,  6.22s/it]

[I 2025-12-02 19:27:28,681] Trial 11 finished with value: 0.4230769230769231 and parameters: {'max_depth': 10, 'learning_rate': 0.2869921397569004, 'n_estimators': 756, 'subsample': 0.7507619379406987, 'colsample_bytree': 0.5933250180169749, 'min_child_weight': 6, 'gamma': 3.400824012161781, 'reg_alpha': 0.005354637289180677, 'reg_lambda': 0.0006717143668118164, 'max_delta_step': 1}. Best is trial 0 with value: 0.5374493927125505.

Best trial: 0. Best value: 0.537449:  28%|██▊       | 14/50 [01:46<03:00,  5.00s/it]

[I 2025-12-02 19:27:30,868] Trial 15 finished with value: 0.5374493927125505 and parameters: {'max_depth': 3, 'learning_rate': 0.06644879126656039, 'n_estimators': 205, 'subsample': 0.7184356814576601, 'colsample_bytree': 0.7821653707308724, 'min_child_weight': 1, 'gamma': 4.373424770765896, 'reg_alpha': 1.7313534198628067, 'reg_lambda': 1.0055430187509402e-08, 'max_delta_step': 0}. Best is trial 0 with value: 0.5374493927125505.

Best trial: 14. Best value: 0.563765:  30%|███       | 15/50 [01:47<02:06,  3.61s/it]

[I 2025-12-02 19:27:31,231] Trial 14 finished with value: 0.5637651821862348 and parameters: {'max_depth': 3, 'learning_rate': 0.06845950014894704, 'n_estimators': 227, 'subsample': 0.7387406225390402, 'colsample_bytree': 0.8033848280710988, 'min_child_weight': 1, 'gamma': 4.327921911148075, 'reg_alpha': 1.026598710043553, 'reg_lambda': 1.0843965731295857e-08, 'max_delta_step': 0}. Best is trial 14 with value: 0.5637651821862348.

Best trial: 16. Best value: 0.621457:  32%|███▏      | 16/50 [01:58<03:20,  5.90s/it]

[I 2025-12-02 19:27:42,464] Trial 16 finished with value: 0.6214574898785425 and parameters: {'max_depth': 3, 'learning_rate': 0.06104665750102346, 'n_estimators': 233, 'subsample': 0.7362534018889004, 'colsample_bytree': 0.7864393397033661, 'min_child_weight': 1, 'gamma': 4.406262878202838, 'reg_alpha': 0.8141399538452739, 'reg_lambda': 3.723046690905502e-08, 'max_delta_step': 0}. Best is trial 16 with value: 0.6214574898785425.

Best trial: 16. Best value: 0.621457:  34%|███▍      | 17/50 [01:59<02:33,  4.64s/it]

[I 2025-12-02 19:27:44,150] Trial 12 finished with value: 0.5445344129554656 and parameters: {'max_depth': 8, 'learning_rate': 0.013072664936025867, 'n_estimators': 870, 'subsample': 0.7600476463211436, 'colsample_bytree': 0.8903469143158924, 'min_child_weight': 3, 'gamma': 3.9407860852220944, 'reg_alpha': 0.00010288518997101723, 'reg_lambda': 1.9931447841944308e-06, 'max_delta_step': 3}. Best is trial 16 with value: 0.6214574898785425.

Best trial: 18. Best value: 0.635628:  36%|███▌      | 18/50 [02:10<03:27,  6.50s/it]

[I 2025-12-02 19:27:54,996] Trial 18 finished with value: 0.6356275303643725 and parameters: {'max_depth': 5, 'learning_rate': 0.04480579013998324, 'n_estimators': 555, 'subsample': 0.844824106270179, 'colsample_bytree': 0.9924124477608146, 'min_child_weight': 3, 'gamma': 4.78116086964693, 'reg_alpha': 6.229138613449953e-05, 'reg_lambda': 2.4497008131415386e-07, 'max_delta_step': 7}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628:  38%|███▊      | 19/50 [02:11<02:31,  4.90s/it]

[I 2025-12-02 19:27:56,158] Trial 17 finished with value: 0.5637651821862348 and parameters: {'max_depth': 4, 'learning_rate': 0.05293206203260982, 'n_estimators': 473, 'subsample': 0.7936136037545176, 'colsample_bytree': 0.7344919624435774, 'min_child_weight': 1, 'gamma': 3.647400022315699, 'reg_alpha': 0.24077670557172337, 'reg_lambda': 3.7935609131983163e-07, 'max_delta_step': 2}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628:  40%|████      | 20/50 [02:19<02:49,  5.66s/it]

[I 2025-12-02 19:28:03,595] Trial 19 finished with value: 0.582995951417004 and parameters: {'max_depth': 5, 'learning_rate': 0.043404458030919156, 'n_estimators': 463, 'subsample': 0.838145815578584, 'colsample_bytree': 0.9954698465550564, 'min_child_weight': 3, 'gamma': 4.976664287596753, 'reg_alpha': 0.48996973385828124, 'reg_lambda': 3.6223763184596455e-07, 'max_delta_step': 8}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628:  42%|████▏     | 21/50 [02:25<02:49,  5.84s/it]

[I 2025-12-02 19:28:09,867] Trial 20 finished with value: 0.582995951417004 and parameters: {'max_depth': 5, 'learning_rate': 0.04135752184638264, 'n_estimators': 501, 'subsample': 0.8202735312894841, 'colsample_bytree': 0.7027828086170673, 'min_child_weight': 1, 'gamma': 4.7793398201306205, 'reg_alpha': 0.6920875949523106, 'reg_lambda': 2.004781045306921e-07, 'max_delta_step': 7}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628:  44%|████▍     | 22/50 [02:33<02:57,  6.34s/it]

[I 2025-12-02 19:28:17,358] Trial 21 finished with value: 0.582995951417004 and parameters: {'max_depth': 5, 'learning_rate': 0.04178346006471544, 'n_estimators': 533, 'subsample': 0.8318872081196222, 'colsample_bytree': 0.9916618952102696, 'min_child_weight': 3, 'gamma': 4.927949571123191, 'reg_alpha': 2.4672051126669797e-08, 'reg_lambda': 2.5147666195815645e-07, 'max_delta_step': 8}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628:  46%|████▌     | 23/50 [02:36<02:24,  5.34s/it]

[I 2025-12-02 19:28:20,363] Trial 22 finished with value: 0.582995951417004 and parameters: {'max_depth': 5, 'learning_rate': 0.041926933500498045, 'n_estimators': 547, 'subsample': 0.8938633521169568, 'colsample_bytree': 0.9985981348214545, 'min_child_weight': 3, 'gamma': 4.899745261180495, 'reg_alpha': 1.1907960191791409e-08, 'reg_lambda': 3.1995477093041574e-05, 'max_delta_step': 8}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628:  48%|████▊     | 24/50 [02:41<02:20,  5.40s/it]

[I 2025-12-02 19:28:25,919] Trial 26 pruned.

Best trial: 18. Best value: 0.635628:  50%|█████     | 25/50 [02:43<01:48,  4.36s/it]

[I 2025-12-02 19:28:27,838] Trial 23 finished with value: 0.5566801619433198 and parameters: {'max_depth': 5, 'learning_rate': 0.015327012706338879, 'n_estimators': 609, 'subsample': 0.8930983795671468, 'colsample_bytree': 0.6776685366351523, 'min_child_weight': 4, 'gamma': 4.989519408128915, 'reg_alpha': 2.0441940523925036e-08, 'reg_lambda': 2.4922687690918194e-05, 'max_delta_step': 7}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628:  52%|█████▏    | 26/50 [02:46<01:30,  3.78s/it]

[I 2025-12-02 19:28:30,264] Trial 25 pruned.

Best trial: 18. Best value: 0.635628:  54%|█████▍    | 27/50 [02:48<01:18,  3.42s/it]

[I 2025-12-02 19:28:32,860] Trial 28 pruned.

Best trial: 18. Best value: 0.635628:  56%|█████▌    | 28/50 [02:56<01:42,  4.67s/it]

[I 2025-12-02 19:28:40,450] Trial 24 finished with value: 0.582995951417004 and parameters: {'max_depth': 5, 'learning_rate': 0.016380715288239086, 'n_estimators': 654, 'subsample': 0.8759936889329771, 'colsample_bytree': 0.9932106429681153, 'min_child_weight': 3, 'gamma': 4.922048693095734, 'reg_alpha': 0.00018121330305428943, 'reg_lambda': 1.8184093406529958e-05, 'max_delta_step': 8}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628:  58%|█████▊    | 29/50 [03:29<04:38, 13.28s/it]

[I 2025-12-02 19:29:13,802] Trial 30 finished with value: 0.5759109311740891 and parameters: {'max_depth': 6, 'learning_rate': 0.04789279710722896, 'n_estimators': 1039, 'subsample': 0.787242147584814, 'colsample_bytree': 0.8489968060495742, 'min_child_weight': 2, 'gamma': 4.017206180143428, 'reg_alpha': 0.0759854157807417, 'reg_lambda': 8.482982588282085e-07, 'max_delta_step': 6}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628:  60%|██████    | 30/50 [03:32<03:24, 10.20s/it]

[I 2025-12-02 19:29:16,839] Trial 32 pruned.

Best trial: 18. Best value: 0.635628:  62%|██████▏   | 31/50 [03:39<02:52,  9.09s/it]

[I 2025-12-02 19:29:23,329] Trial 27 finished with value: 0.6356275303643725 and parameters: {'max_depth': 4, 'learning_rate': 0.09947360418554282, 'n_estimators': 1482, 'subsample': 0.8739839513541843, 'colsample_bytree': 0.8708413038233737, 'min_child_weight': 2, 'gamma': 3.470422692532253, 'reg_alpha': 0.00022553637307544752, 'reg_lambda': 5.623870490988525e-08, 'max_delta_step': 9}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628:  64%|██████▍   | 32/50 [03:39<01:56,  6.47s/it]

[I 2025-12-02 19:29:23,696] Trial 31 finished with value: 0.5637651821862348 and parameters: {'max_depth': 6, 'learning_rate': 0.03310606965181629, 'n_estimators': 1064, 'subsample': 0.8075541211031693, 'colsample_bytree': 0.8536419994393771, 'min_child_weight': 2, 'gamma': 4.016190385898013, 'reg_alpha': 0.09492333637532402, 'reg_lambda': 1.1195546471716118e-06, 'max_delta_step': 6}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628:  66%|██████▌   | 33/50 [03:40<01:24,  4.96s/it]

[I 2025-12-02 19:29:25,122] Trial 29 finished with value: 0.5637651821862348 and parameters: {'max_depth': 4, 'learning_rate': 0.0902436627625933, 'n_estimators': 1460, 'subsample': 0.7945458271326626, 'colsample_bytree': 0.8575449849515546, 'min_child_weight': 2, 'gamma': 3.457912439320741, 'reg_alpha': 2.0069236806692488e-05, 'reg_lambda': 7.275536398216748e-08, 'max_delta_step': 6}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628:  68%|██████▊   | 34/50 [03:50<01:43,  6.46s/it]

[I 2025-12-02 19:29:35,092] Trial 35 pruned.

Best trial: 18. Best value: 0.635628:  70%|███████   | 35/50 [03:51<01:10,  4.70s/it]

[I 2025-12-02 19:29:35,671] Trial 33 finished with value: 0.5637651821862348 and parameters: {'max_depth': 6, 'learning_rate': 0.0328463203998996, 'n_estimators': 365, 'subsample': 0.7913727307837725, 'colsample_bytree': 0.8492310445688581, 'min_child_weight': 2, 'gamma': 1.9904023934900823, 'reg_alpha': 0.0016354343259263075, 'reg_lambda': 8.363561381279547e-08, 'max_delta_step': 6}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628:  72%|███████▏  | 36/50 [03:54<00:58,  4.20s/it]

[I 2025-12-02 19:29:38,719] Trial 36 finished with value: 0.6356275303643725 and parameters: {'max_depth': 3, 'learning_rate': 0.130737260407747, 'n_estimators': 303, 'subsample': 0.8467801828502158, 'colsample_bytree': 0.9238600328124384, 'min_child_weight': 3, 'gamma': 2.187859949693863, 'reg_alpha': 0.0010263102898450437, 'reg_lambda': 1.7851400212507803e-07, 'max_delta_step': 7}. Best is trial 18 with value: 0.6356275303643725.
[I 2025-12-02 19:29:38,721] Trial 37 pruned.

Best trial: 18. Best value: 0.635628:  76%|███████▌  | 38/50 [03:56<00:31,  2.67s/it]

[I 2025-12-02 19:29:40,465] Trial 38 pruned.

Best trial: 18. Best value: 0.635628:  78%|███████▊  | 39/50 [03:57<00:24,  2.20s/it]

[I 2025-12-02 19:29:41,260] Trial 39 pruned.

Best trial: 18. Best value: 0.635628:  80%|████████  | 40/50 [04:02<00:30,  3.04s/it]

[I 2025-12-02 19:29:46,677] Trial 41 pruned.

Best trial: 18. Best value: 0.635628:  82%|████████▏ | 41/50 [04:17<00:56,  6.32s/it]

[I 2025-12-02 19:30:01,780] Trial 40 pruned.

Best trial: 18. Best value: 0.635628:  84%|████████▍ | 42/50 [04:21<00:46,  5.78s/it]

[I 2025-12-02 19:30:06,176] Trial 44 pruned.

Best trial: 18. Best value: 0.635628:  86%|████████▌ | 43/50 [04:34<00:53,  7.60s/it]

[I 2025-12-02 19:30:18,309] Trial 45 finished with value: 0.4919028340080972 and parameters: {'max_depth': 4, 'learning_rate': 0.22138793114289085, 'n_estimators': 274, 'subsample': 0.8310495239428266, 'colsample_bytree': 0.8131233511627258, 'min_child_weight': 2, 'gamma': 0.08139863214694065, 'reg_alpha': 0.35317465034043305, 'reg_lambda': 4.460743077978805e-07, 'max_delta_step': 4}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628:  88%|████████▊ | 44/50 [04:38<00:40,  6.81s/it]

[I 2025-12-02 19:30:23,180] Trial 34 finished with value: 0.6356275303643725 and parameters: {'max_depth': 4, 'learning_rate': 0.1107823431817744, 'n_estimators': 1488, 'subsample': 0.8168961328976787, 'colsample_bytree': 0.8569179999724196, 'min_child_weight': 2, 'gamma': 3.4084157497501906, 'reg_alpha': 0.0013050836519159885, 'reg_lambda': 8.909962970900904e-08, 'max_delta_step': 9}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628:  90%|█████████ | 45/50 [04:39<00:24,  4.98s/it]

[I 2025-12-02 19:30:23,741] Trial 42 finished with value: 0.5374493927125505 and parameters: {'max_depth': 4, 'learning_rate': 0.13278407732210648, 'n_estimators': 1079, 'subsample': 0.7703786139100522, 'colsample_bytree': 0.7619835929917474, 'min_child_weight': 1, 'gamma': 1.0296338757798051, 'reg_alpha': 0.0007218320633251043, 'reg_lambda': 7.46823703948604e-05, 'max_delta_step': 4}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628:  92%|█████████▏| 46/50 [04:49<00:25,  6.35s/it]

[I 2025-12-02 19:30:33,376] Trial 43 finished with value: 0.5182186234817814 and parameters: {'max_depth': 4, 'learning_rate': 0.07243838537733069, 'n_estimators': 1154, 'subsample': 0.5846948896903349, 'colsample_bytree': 0.8167445078231138, 'min_child_weight': 1, 'gamma': 1.0226273747630497, 'reg_alpha': 6.035577815128796e-07, 'reg_lambda': 3.229993359384013e-08, 'max_delta_step': 10}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628:  94%|█████████▍| 47/50 [04:52<00:16,  5.51s/it]

[I 2025-12-02 19:30:36,891] Trial 47 pruned.

Best trial: 18. Best value: 0.635628:  96%|█████████▌| 48/50 [05:13<00:19,  9.95s/it]

[I 2025-12-02 19:30:57,318] Trial 46 finished with value: 0.5759109311740891 and parameters: {'max_depth': 5, 'learning_rate': 0.07451223961856916, 'n_estimators': 1172, 'subsample': 0.8656204703022142, 'colsample_bytree': 0.7673464414446686, 'min_child_weight': 3, 'gamma': 4.237165419973352, 'reg_alpha': 0.026480798168662417, 'reg_lambda': 2.2573461818545086e-08, 'max_delta_step': 10}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628:  98%|█████████▊| 49/50 [05:23<00:09,  9.99s/it]

[I 2025-12-02 19:31:07,406] Trial 48 finished with value: 0.4848178137651822 and parameters: {'max_depth': 3, 'learning_rate': 0.11048670479669898, 'n_estimators': 1473, 'subsample': 0.5575275756934115, 'colsample_bytree': 0.8803296280248265, 'min_child_weight': 2, 'gamma': 3.2080232619481386, 'reg_alpha': 0.023711132803955082, 'reg_lambda': 4.317447722972842e-06, 'max_delta_step': 10}. Best is trial 18 with value: 0.6356275303643725.

Best trial: 18. Best value: 0.635628: 100%|██████████| 50/50 [05:31<00:00,  6.63s/it]

[I 2025-12-02 19:31:15,720] Trial 49 finished with value: 0.5637651821862348 and parameters: {'max_depth': 3, 'learning_rate': 0.1104623023349447, 'n_estimators': 1483, 'subsample': 0.8687008473174562, 'colsample_bytree': 0.8839954434256494, 'min_child_weight': 2, 'gamma': 3.1872373340071696, 'reg_alpha': 0.0035397614454965496, 'reg_lambda': 3.6006589287923877e-06, 'max_delta_step': 9}. Best is trial 18 with value: 0.6356275303643725.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.635628                0.557143      0.514286

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.119523          0.714286               0.4        50          45

   test_size
0         12
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.635628                0.557143      0.514286

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.119523          0.714286               0.4        50          45

   test_size
0         12

In [ ]:
datasets = task_freq_dfs_ad_lbd

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_lbd_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_freq_ad_lbd_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param="emb_",
)
print(summary)

[I 2025-12-02 19:31:18,998] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 45, Test size: 12
Using Leave-One-Out CV with 45 folds
Starting optimization with 50 trials...

Best trial: 2. Best value: 0.544534:   2%|▏         | 1/50 [00:14<11:34, 14.17s/it]

[I 2025-12-02 19:31:33,155] Trial 2 finished with value: 0.5445344129554656 and parameters: {'max_depth': 7, 'learning_rate': 0.022265343314150407, 'n_estimators': 239, 'subsample': 0.7806504613775492, 'colsample_bytree': 0.5629624332461913, 'min_child_weight': 2, 'gamma': 2.418008996678669, 'reg_alpha': 0.03761144783660554, 'reg_lambda': 0.00020075465825085658, 'max_delta_step': 2}. Best is trial 2 with value: 0.5445344129554656.

Best trial: 2. Best value: 0.544534:   4%|▍         | 2/50 [00:14<05:00,  6.27s/it]

[I 2025-12-02 19:31:33,892] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.11227888200439591, 'n_estimators': 341, 'subsample': 0.9689883574338136, 'colsample_bytree': 0.9042244708164053, 'min_child_weight': 9, 'gamma': 1.6789612445412132, 'reg_alpha': 0.5768630465674977, 'reg_lambda': 0.013590854235708513, 'max_delta_step': 3}. Best is trial 2 with value: 0.5445344129554656.

Best trial: 2. Best value: 0.544534:   6%|▌         | 3/50 [00:22<05:32,  7.07s/it]

[I 2025-12-02 19:31:41,924] Trial 0 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.055589575380992184, 'n_estimators': 613, 'subsample': 0.9056410971996041, 'colsample_bytree': 0.5772148847503883, 'min_child_weight': 9, 'gamma': 2.270548689816017, 'reg_alpha': 0.0007787419838184189, 'reg_lambda': 3.374414339700207e-08, 'max_delta_step': 10}. Best is trial 2 with value: 0.5445344129554656.

Best trial: 2. Best value: 0.544534:   8%|▊         | 4/50 [00:35<07:12,  9.41s/it]

[I 2025-12-02 19:31:54,915] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.04664585414019154, 'n_estimators': 965, 'subsample': 0.998400795106724, 'colsample_bytree': 0.774127782163752, 'min_child_weight': 5, 'gamma': 1.5629418060545797, 'reg_alpha': 3.678832962425748e-07, 'reg_lambda': 9.840128844487223e-06, 'max_delta_step': 8}. Best is trial 2 with value: 0.5445344129554656.

Best trial: 2. Best value: 0.544534:  10%|█         | 5/50 [00:44<06:52,  9.18s/it]

[I 2025-12-02 19:32:03,675] Trial 4 finished with value: 0.5303643724696356 and parameters: {'max_depth': 6, 'learning_rate': 0.1410875793720796, 'n_estimators': 615, 'subsample': 0.6631028995554598, 'colsample_bytree': 0.8923963925452938, 'min_child_weight': 1, 'gamma': 2.9360499622286707, 'reg_alpha': 1.6399553511700467e-07, 'reg_lambda': 2.8808320827284308e-05, 'max_delta_step': 7}. Best is trial 2 with value: 0.5445344129554656.

Best trial: 2. Best value: 0.544534:  12%|█▏        | 6/50 [00:59<08:12, 11.20s/it]

[I 2025-12-02 19:32:18,795] Trial 5 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.03548121473654281, 'n_estimators': 1171, 'subsample': 0.7669386120463055, 'colsample_bytree': 0.7564178930761278, 'min_child_weight': 4, 'gamma': 4.63157024212709, 'reg_alpha': 4.716891471590582, 'reg_lambda': 1.4388277691514535e-07, 'max_delta_step': 0}. Best is trial 2 with value: 0.5445344129554656.

Best trial: 2. Best value: 0.544534:  14%|█▍        | 7/50 [01:19<09:56, 13.88s/it]

[I 2025-12-02 19:32:38,200] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.021525866533592983, 'n_estimators': 922, 'subsample': 0.7288924994489672, 'colsample_bytree': 0.6154640644558355, 'min_child_weight': 10, 'gamma': 4.009483219747065, 'reg_alpha': 0.0032677124023261193, 'reg_lambda': 9.963004983484036e-06, 'max_delta_step': 0}. Best is trial 2 with value: 0.5445344129554656.

Best trial: 2. Best value: 0.544534:  16%|█▌        | 8/50 [01:19<06:41,  9.56s/it]

[I 2025-12-02 19:32:38,502] Trial 6 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.010241906348191259, 'n_estimators': 1478, 'subsample': 0.9615479314236781, 'colsample_bytree': 0.9370909630058948, 'min_child_weight': 6, 'gamma': 4.119840501240515, 'reg_alpha': 0.28134578007584726, 'reg_lambda': 7.869065342539712e-06, 'max_delta_step': 5}. Best is trial 2 with value: 0.5445344129554656.

Best trial: 2. Best value: 0.544534:  18%|█▊        | 9/50 [01:27<06:13,  9.11s/it]

[I 2025-12-02 19:32:46,634] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.011721348860222455, 'n_estimators': 1444, 'subsample': 0.7579115729893903, 'colsample_bytree': 0.6431255359615451, 'min_child_weight': 8, 'gamma': 4.53925450853651, 'reg_alpha': 3.92559409698977e-06, 'reg_lambda': 6.042494985066765, 'max_delta_step': 7}. Best is trial 2 with value: 0.5445344129554656.

Best trial: 2. Best value: 0.544534:  20%|██        | 10/50 [01:38<06:29,  9.73s/it]

[I 2025-12-02 19:32:57,739] Trial 9 finished with value: 0.3076923076923077 and parameters: {'max_depth': 7, 'learning_rate': 0.012165356648618907, 'n_estimators': 785, 'subsample': 0.8773025516673617, 'colsample_bytree': 0.8433751274838835, 'min_child_weight': 1, 'gamma': 2.327083051432176, 'reg_alpha': 4.686112687575721, 'reg_lambda': 0.05658904424375975, 'max_delta_step': 2}. Best is trial 2 with value: 0.5445344129554656.

Best trial: 2. Best value: 0.544534:  22%|██▏       | 11/50 [01:39<04:36,  7.09s/it]

[I 2025-12-02 19:32:58,836] Trial 10 finished with value: 0.5111336032388664 and parameters: {'max_depth': 9, 'learning_rate': 0.16617526166417707, 'n_estimators': 478, 'subsample': 0.7073955524379831, 'colsample_bytree': 0.6418707025484014, 'min_child_weight': 1, 'gamma': 2.8311171787106586, 'reg_alpha': 5.941426860597767e-08, 'reg_lambda': 0.7267080007099236, 'max_delta_step': 10}. Best is trial 2 with value: 0.5445344129554656.

Best trial: 2. Best value: 0.544534:  24%|██▍       | 12/50 [01:45<04:07,  6.50s/it]

[I 2025-12-02 19:33:04,012] Trial 11 finished with value: 0.4797570850202429 and parameters: {'max_depth': 8, 'learning_rate': 0.18344915822984434, 'n_estimators': 582, 'subsample': 0.8381269721610591, 'colsample_bytree': 0.9407445162581771, 'min_child_weight': 2, 'gamma': 4.399703043872122, 'reg_alpha': 0.012958789636892872, 'reg_lambda': 0.0006971162736641188, 'max_delta_step': 3}. Best is trial 2 with value: 0.5445344129554656.

Best trial: 2. Best value: 0.544534:  26%|██▌       | 13/50 [01:49<03:34,  5.79s/it]

[I 2025-12-02 19:33:08,143] Trial 14 finished with value: 0.4919028340080972 and parameters: {'max_depth': 6, 'learning_rate': 0.2410036769370233, 'n_estimators': 206, 'subsample': 0.5508149126973241, 'colsample_bytree': 0.5106922543436805, 'min_child_weight': 3, 'gamma': 0.01024989768540241, 'reg_alpha': 1.965513856455041e-05, 'reg_lambda': 0.0006719258164930548, 'max_delta_step': 5}. Best is trial 2 with value: 0.5445344129554656.

Best trial: 13. Best value: 0.640688:  28%|██▊       | 14/50 [01:50<02:40,  4.45s/it]

[I 2025-12-02 19:33:09,506] Trial 13 finished with value: 0.6406882591093117 and parameters: {'max_depth': 7, 'learning_rate': 0.023485412122831055, 'n_estimators': 267, 'subsample': 0.5400914853539223, 'colsample_bytree': 0.5210102672227692, 'min_child_weight': 3, 'gamma': 0.11812919669903588, 'reg_alpha': 0.025876930849051103, 'reg_lambda': 0.0021645864535841347, 'max_delta_step': 3}. Best is trial 13 with value: 0.6406882591093117.

Best trial: 13. Best value: 0.640688:  32%|███▏      | 16/50 [01:56<01:59,  3.50s/it]

[I 2025-12-02 19:33:15,635] Trial 12 pruned.
[I 2025-12-02 19:33:15,756] Trial 15 finished with value: 0.5445344129554656 and parameters: {'max_depth': 6, 'learning_rate': 0.28913479391051905, 'n_estimators': 255, 'subsample': 0.5741479299526183, 'colsample_bytree': 0.5210588782484399, 'min_child_weight': 3, 'gamma': 3.221386014333508, 'reg_alpha': 3.454242396139649e-05, 'reg_lambda': 0.0002976859907620825, 'max_delta_step': 6}. Best is trial 13 with value: 0.6406882591093117.

Best trial: 13. Best value: 0.640688:  34%|███▍      | 17/50 [02:00<01:58,  3.59s/it]

[I 2025-12-02 19:33:19,552] Trial 16 finished with value: 0.582995951417004 and parameters: {'max_depth': 6, 'learning_rate': 0.08264109216087212, 'n_estimators': 215, 'subsample': 0.6186467853417661, 'colsample_bytree': 0.9947075971516854, 'min_child_weight': 3, 'gamma': 3.2442182509440833, 'reg_alpha': 7.555089929292761e-05, 'reg_lambda': 1.1207180387060415e-06, 'max_delta_step': 7}. Best is trial 13 with value: 0.6406882591093117.

Best trial: 13. Best value: 0.640688:  36%|███▌      | 18/50 [02:02<01:39,  3.11s/it]

[I 2025-12-02 19:33:21,538] Trial 17 finished with value: 0.6143724696356275 and parameters: {'max_depth': 7, 'learning_rate': 0.023013338199530022, 'n_estimators': 249, 'subsample': 0.536975237855668, 'colsample_bytree': 0.5337195287509627, 'min_child_weight': 3, 'gamma': 0.012334193995515275, 'reg_alpha': 0.03429034939688579, 'reg_lambda': 0.011984109866929065, 'max_delta_step': 2}. Best is trial 13 with value: 0.6406882591093117.

Best trial: 13. Best value: 0.640688:  38%|███▊      | 19/50 [02:05<01:30,  2.93s/it]

[I 2025-12-02 19:33:24,051] Trial 20 pruned.

Best trial: 13. Best value: 0.640688:  40%|████      | 20/50 [02:07<01:19,  2.64s/it]

[I 2025-12-02 19:33:26,006] Trial 21 pruned.

Best trial: 13. Best value: 0.640688:  42%|████▏     | 21/50 [02:07<00:55,  1.91s/it]

[I 2025-12-02 19:33:26,210] Trial 18 finished with value: 0.5809716599190283 and parameters: {'max_depth': 5, 'learning_rate': 0.024728052547700368, 'n_estimators': 211, 'subsample': 0.5247220636188799, 'colsample_bytree': 0.502950616051017, 'min_child_weight': 3, 'gamma': 0.0839093855761949, 'reg_alpha': 0.07338644373151476, 'reg_lambda': 0.00015633449630294232, 'max_delta_step': 2}. Best is trial 13 with value: 0.6406882591093117.

Best trial: 13. Best value: 0.640688:  44%|████▍     | 22/50 [02:12<01:18,  2.81s/it]

[I 2025-12-02 19:33:31,117] Trial 22 pruned.

Best trial: 13. Best value: 0.640688:  46%|████▌     | 23/50 [02:14<01:09,  2.59s/it]

[I 2025-12-02 19:33:33,187] Trial 24 pruned.
[I 2025-12-02 19:33:33,213] Trial 23 pruned.

Best trial: 13. Best value: 0.640688:  50%|█████     | 25/50 [02:14<00:36,  1.46s/it]

[I 2025-12-02 19:33:33,496] Trial 19 finished with value: 0.6072874493927125 and parameters: {'max_depth': 5, 'learning_rate': 0.020738065048927983, 'n_estimators': 409, 'subsample': 0.5009317267249928, 'colsample_bytree': 0.5557500481014077, 'min_child_weight': 3, 'gamma': 0.4032079174059793, 'reg_alpha': 0.02072364485698194, 'reg_lambda': 0.12506128613185374, 'max_delta_step': 2}. Best is trial 13 with value: 0.6406882591093117.

Best trial: 13. Best value: 0.640688:  52%|█████▏    | 26/50 [02:19<00:55,  2.30s/it]

[I 2025-12-02 19:33:38,340] Trial 25 pruned.

Best trial: 13. Best value: 0.640688:  54%|█████▍    | 27/50 [02:31<01:50,  4.79s/it]

[I 2025-12-02 19:33:50,151] Trial 27 finished with value: 0.5566801619433198 and parameters: {'max_depth': 7, 'learning_rate': 0.017499451375020663, 'n_estimators': 337, 'subsample': 0.59637025195525, 'colsample_bytree': 0.812431111820169, 'min_child_weight': 2, 'gamma': 3.4193207893252597, 'reg_alpha': 0.00010253867675422658, 'reg_lambda': 1.2715802487520343e-06, 'max_delta_step': 4}. Best is trial 13 with value: 0.6406882591093117.

Best trial: 13. Best value: 0.640688:  56%|█████▌    | 28/50 [02:35<01:43,  4.68s/it]

[I 2025-12-02 19:33:54,538] Trial 30 pruned.

Best trial: 13. Best value: 0.640688:  58%|█████▊    | 29/50 [02:36<01:17,  3.68s/it]

[I 2025-12-02 19:33:55,646] Trial 26 finished with value: 0.582995951417004 and parameters: {'max_depth': 7, 'learning_rate': 0.035577608149438215, 'n_estimators': 511, 'subsample': 0.5933395737041908, 'colsample_bytree': 0.8107384387026122, 'min_child_weight': 2, 'gamma': 0.7419152061651, 'reg_alpha': 0.00022226803319398767, 'reg_lambda': 2.145325112348505e-06, 'max_delta_step': 4}. Best is trial 13 with value: 0.6406882591093117.

Best trial: 13. Best value: 0.640688:  60%|██████    | 30/50 [02:40<01:15,  3.76s/it]

[I 2025-12-02 19:33:59,620] Trial 28 finished with value: 0.5759109311740891 and parameters: {'max_depth': 4, 'learning_rate': 0.015618065206280599, 'n_estimators': 517, 'subsample': 0.586157614498479, 'colsample_bytree': 0.5415377591794651, 'min_child_weight': 2, 'gamma': 0.4958390306613308, 'reg_alpha': 0.010174432868612526, 'reg_lambda': 2.9050138575786533, 'max_delta_step': 4}. Best is trial 13 with value: 0.6406882591093117.

Best trial: 13. Best value: 0.640688:  62%|██████▏   | 31/50 [02:44<01:13,  3.89s/it]

[I 2025-12-02 19:34:03,808] Trial 29 finished with value: 0.5566801619433198 and parameters: {'max_depth': 4, 'learning_rate': 0.016718880875136885, 'n_estimators': 543, 'subsample': 0.5768692963121302, 'colsample_bytree': 0.5408864534314469, 'min_child_weight': 2, 'gamma': 1.225169697238895, 'reg_alpha': 0.007869012400320103, 'reg_lambda': 2.106278550363051, 'max_delta_step': 3}. Best is trial 13 with value: 0.6406882591093117.

Best trial: 13. Best value: 0.640688:  64%|██████▍   | 32/50 [02:46<00:56,  3.13s/it]

[I 2025-12-02 19:34:05,102] Trial 33 pruned.

Best trial: 34. Best value: 0.647773:  66%|██████▌   | 33/50 [02:57<01:32,  5.46s/it]

[I 2025-12-02 19:34:16,144] Trial 34 finished with value: 0.6477732793522267 and parameters: {'max_depth': 6, 'learning_rate': 0.04945668091204574, 'n_estimators': 292, 'subsample': 0.5005969389714806, 'colsample_bytree': 0.5988434802954146, 'min_child_weight': 3, 'gamma': 0.37025767025655076, 'reg_alpha': 0.0005871892994230894, 'reg_lambda': 0.069994249138968, 'max_delta_step': 8}. Best is trial 34 with value: 0.6477732793522267.

Best trial: 34. Best value: 0.647773:  68%|██████▊   | 34/50 [02:58<01:08,  4.25s/it]

[I 2025-12-02 19:34:17,531] Trial 35 finished with value: 0.6214574898785425 and parameters: {'max_depth': 6, 'learning_rate': 0.05510459601699414, 'n_estimators': 291, 'subsample': 0.5005609428352596, 'colsample_bytree': 0.5937801448630604, 'min_child_weight': 3, 'gamma': 0.34983213426997095, 'reg_alpha': 3.128959887396938e-06, 'reg_lambda': 3.2681893090487984e-08, 'max_delta_step': 9}. Best is trial 34 with value: 0.6477732793522267.

Best trial: 34. Best value: 0.647773:  70%|███████   | 35/50 [02:58<00:45,  3.06s/it]

[I 2025-12-02 19:34:17,767] Trial 31 finished with value: 0.5182186234817814 and parameters: {'max_depth': 5, 'learning_rate': 0.0352792668150726, 'n_estimators': 496, 'subsample': 0.5501504120101878, 'colsample_bytree': 0.6137416921044913, 'min_child_weight': 2, 'gamma': 0.42844813112172636, 'reg_alpha': 0.01877797198571898, 'reg_lambda': 0.0403680259340429, 'max_delta_step': 3}. Best is trial 34 with value: 0.6477732793522267.

Best trial: 34. Best value: 0.647773:  72%|███████▏  | 36/50 [03:02<00:43,  3.11s/it]

[I 2025-12-02 19:34:20,992] Trial 37 pruned.

Best trial: 34. Best value: 0.647773:  74%|███████▍  | 37/50 [03:02<00:29,  2.30s/it]

[I 2025-12-02 19:34:21,410] Trial 38 pruned.

Best trial: 34. Best value: 0.647773:  76%|███████▌  | 38/50 [03:03<00:23,  1.97s/it]

[I 2025-12-02 19:34:22,590] Trial 32 finished with value: 0.5303643724696356 and parameters: {'max_depth': 5, 'learning_rate': 0.04880025695196988, 'n_estimators': 670, 'subsample': 0.5546904319899428, 'colsample_bytree': 0.5946316919953575, 'min_child_weight': 3, 'gamma': 0.42058582801320926, 'reg_alpha': 0.00789202980597508, 'reg_lambda': 0.039535390742457814, 'max_delta_step': 3}. Best is trial 34 with value: 0.6477732793522267.

Best trial: 34. Best value: 0.647773:  78%|███████▊  | 39/50 [03:06<00:25,  2.35s/it]

[I 2025-12-02 19:34:25,828] Trial 36 pruned.

Best trial: 34. Best value: 0.647773:  80%|████████  | 40/50 [03:13<00:37,  3.79s/it]

[I 2025-12-02 19:34:32,977] Trial 39 finished with value: 0.5951417004048583 and parameters: {'max_depth': 6, 'learning_rate': 0.05846957515230204, 'n_estimators': 293, 'subsample': 0.538076726532514, 'colsample_bytree': 0.6643066904608836, 'min_child_weight': 3, 'gamma': 1.9597127093549804, 'reg_alpha': 4.350213921161932e-07, 'reg_lambda': 0.0012718130516572988, 'max_delta_step': 9}. Best is trial 34 with value: 0.6477732793522267.

Best trial: 34. Best value: 0.647773:  82%|████████▏ | 41/50 [03:15<00:27,  3.05s/it]

[I 2025-12-02 19:34:34,306] Trial 40 finished with value: 0.5951417004048583 and parameters: {'max_depth': 7, 'learning_rate': 0.05816351666570358, 'n_estimators': 310, 'subsample': 0.5040618282232042, 'colsample_bytree': 0.6535274883418578, 'min_child_weight': 3, 'gamma': 1.8338644664350672, 'reg_alpha': 6.676985806747052e-07, 'reg_lambda': 0.0018685403929534956, 'max_delta_step': 8}. Best is trial 34 with value: 0.6477732793522267.

Best trial: 34. Best value: 0.647773:  84%|████████▍ | 42/50 [03:18<00:25,  3.23s/it]

[I 2025-12-02 19:34:37,962] Trial 44 pruned.

Best trial: 34. Best value: 0.647773:  86%|████████▌ | 43/50 [03:21<00:21,  3.01s/it]

[I 2025-12-02 19:34:40,442] Trial 41 finished with value: 0.5495951417004048 and parameters: {'max_depth': 9, 'learning_rate': 0.030224118290712306, 'n_estimators': 296, 'subsample': 0.6376668771857384, 'colsample_bytree': 0.6730515461583836, 'min_child_weight': 1, 'gamma': 1.7060592051346777, 'reg_alpha': 1.2374315652415365e-08, 'reg_lambda': 4.843501556529447e-05, 'max_delta_step': 9}. Best is trial 34 with value: 0.6477732793522267.
[I 2025-12-02 19:34:40,622] Trial 42 finished with value: 0.458502024291498 and parameters: {'max_depth': 7, 'learning_rate': 0.0647345323251025, 'n_estimators': 278, 'subsample': 0.6473593913991734, 'colsample_bytree': 0.6379573152367124, 'min_child_weight': 1, 'gamma': 1.8615113714803286, 'reg_alpha': 1.4711625672674166e-08, 'reg_lambda': 8.878679558329797e-05, 'max_delta_step': 8}. Best is trial 34 with value: 0.6477732793522267.

Best trial: 34. Best value: 0.647773:  90%|█████████ | 45/50 [03:25<00:13,  2.64s/it]

[I 2025-12-02 19:34:44,373] Trial 47 pruned.

Best trial: 34. Best value: 0.647773:  92%|█████████▏| 46/50 [03:25<00:07,  1.96s/it]

[I 2025-12-02 19:34:44,750] Trial 46 pruned.

Best trial: 34. Best value: 0.647773:  94%|█████████▍| 47/50 [03:34<00:11,  3.96s/it]

[I 2025-12-02 19:34:53,386] Trial 49 pruned.

Best trial: 34. Best value: 0.647773:  96%|█████████▌| 48/50 [03:40<00:09,  4.75s/it]

[I 2025-12-02 19:34:59,984] Trial 45 finished with value: 0.5232793522267206 and parameters: {'max_depth': 3, 'learning_rate': 0.028491272148742322, 'n_estimators': 396, 'subsample': 0.5183828194093413, 'colsample_bytree': 0.5369041835661313, 'min_child_weight': 1, 'gamma': 0.23149647941110502, 'reg_alpha': 0.42049046644294225, 'reg_lambda': 0.2156452921900047, 'max_delta_step': 0}. Best is trial 34 with value: 0.6477732793522267.

Best trial: 34. Best value: 0.647773:  98%|█████████▊| 49/50 [03:47<00:05,  5.33s/it]

[I 2025-12-02 19:35:06,668] Trial 43 finished with value: 0.5040485829959513 and parameters: {'max_depth': 9, 'learning_rate': 0.09553602820101702, 'n_estimators': 1080, 'subsample': 0.6504456864670595, 'colsample_bytree': 0.70136515184243, 'min_child_weight': 1, 'gamma': 1.0619713483521358, 'reg_alpha': 9.282570734221423e-06, 'reg_lambda': 4.7799968269313484e-05, 'max_delta_step': 8}. Best is trial 34 with value: 0.6477732793522267.

Best trial: 34. Best value: 0.647773: 100%|██████████| 50/50 [03:52<00:00,  4.65s/it]

[I 2025-12-02 19:35:11,262] Trial 48 finished with value: 0.582995951417004 and parameters: {'max_depth': 6, 'learning_rate': 0.02705870102966562, 'n_estimators': 1017, 'subsample': 0.5735722934816428, 'colsample_bytree': 0.5610209822860027, 'min_child_weight': 2, 'gamma': 0.23959467231984505, 'reg_alpha': 0.21062617997838826, 'reg_lambda': 0.40886378122748634, 'max_delta_step': 0}. Best is trial 34 with value: 0.6477732793522267.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.647773                0.557143           0.6

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.119523          0.714286               0.4        50          45

   test_size
0         12
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.647773                0.557143           0.6

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.119523          0.714286               0.4        50          45

   test_size
0         12

In [ ]:

# Temporal embedings
datasets = task_temp_dfs_ad_lbd

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    #    scoring="balanced_accuracy",     # or "roc_auc"
    scoring="balanced_accuracy",      
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_lbd_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_temporal_ad_lbd_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param="emb_",
)
print(summary)

[I 2025-12-02 19:35:14,980] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 45, Test size: 12
Using Leave-One-Out CV with 45 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.609312:   2%|▏         | 1/50 [00:13<10:38, 13.03s/it]

[I 2025-12-02 19:35:27,997] Trial 1 finished with value: 0.6093117408906883 and parameters: {'max_depth': 4, 'learning_rate': 0.02545444170288978, 'n_estimators': 212, 'subsample': 0.6087580641211778, 'colsample_bytree': 0.8024918478089389, 'min_child_weight': 2, 'gamma': 1.6235557460797971, 'reg_alpha': 0.05475700144104953, 'reg_lambda': 2.052107003840236e-06, 'max_delta_step': 9}. Best is trial 1 with value: 0.6093117408906883.
[I 2025-12-02 19:35:28,051] Trial 3 finished with value: 0.48684210526315785 and parameters: {'max_depth': 10, 'learning_rate': 0.02427213721626625, 'n_estimators': 299, 'subsample': 0.8649509308579983, 'colsample_bytree': 0.7688574483091162, 'min_child_weight': 4, 'gamma': 3.7755798315684403, 'reg_alpha': 0.2039113478869218, 'reg_lambda': 1.1896914640663263, 'max_delta_step': 3}. Best is trial 1 with value: 0.6093117408906883.

Best trial: 1. Best value: 0.609312:   6%|▌         | 3/50 [00:16<03:45,  4.80s/it]

[I 2025-12-02 19:35:31,828] Trial 0 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.014010106094993246, 'n_estimators': 403, 'subsample': 0.9489587662056627, 'colsample_bytree': 0.5855807648239513, 'min_child_weight': 8, 'gamma': 3.132144236799606, 'reg_alpha': 7.289746578219178e-06, 'reg_lambda': 1.9410829684441493, 'max_delta_step': 3}. Best is trial 1 with value: 0.6093117408906883.

Best trial: 1. Best value: 0.609312:   8%|▊         | 4/50 [00:38<08:01, 10.48s/it]

[I 2025-12-02 19:35:53,040] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.03769267646928694, 'n_estimators': 996, 'subsample': 0.668380335682653, 'colsample_bytree': 0.7886704503207913, 'min_child_weight': 9, 'gamma': 0.8510681582645008, 'reg_alpha': 2.597963821590241, 'reg_lambda': 1.4536097820355849, 'max_delta_step': 3}. Best is trial 1 with value: 0.6093117408906883.

Best trial: 1. Best value: 0.609312:  10%|█         | 5/50 [00:42<06:25,  8.56s/it]

[I 2025-12-02 19:35:57,713] Trial 6 finished with value: 0.5111336032388664 and parameters: {'max_depth': 4, 'learning_rate': 0.12224825302106494, 'n_estimators': 488, 'subsample': 0.5611917349162878, 'colsample_bytree': 0.5860388782855125, 'min_child_weight': 1, 'gamma': 0.09531297064616528, 'reg_alpha': 0.03132760172842304, 'reg_lambda': 3.2070378321384343, 'max_delta_step': 8}. Best is trial 1 with value: 0.6093117408906883.

Best trial: 1. Best value: 0.609312:  12%|█▏        | 6/50 [00:43<04:21,  5.94s/it]

[I 2025-12-02 19:35:58,131] Trial 4 finished with value: 0.02631578947368421 and parameters: {'max_depth': 6, 'learning_rate': 0.12532167892788385, 'n_estimators': 811, 'subsample': 0.6782718082846139, 'colsample_bytree': 0.5514128050083964, 'min_child_weight': 7, 'gamma': 4.254268018834897, 'reg_alpha': 4.4208198289309586e-07, 'reg_lambda': 1.9316557978251974e-06, 'max_delta_step': 5}. Best is trial 1 with value: 0.6093117408906883.

Best trial: 1. Best value: 0.609312:  14%|█▍        | 7/50 [00:53<05:17,  7.39s/it]

[I 2025-12-02 19:36:08,687] Trial 5 finished with value: 0.582995951417004 and parameters: {'max_depth': 7, 'learning_rate': 0.05803249090971495, 'n_estimators': 1097, 'subsample': 0.636265941556078, 'colsample_bytree': 0.5754007583064932, 'min_child_weight': 2, 'gamma': 2.0362522580684193, 'reg_alpha': 4.060736434192853e-05, 'reg_lambda': 0.00014213761721620075, 'max_delta_step': 10}. Best is trial 1 with value: 0.6093117408906883.

Best trial: 1. Best value: 0.609312:  16%|█▌        | 8/50 [00:54<03:45,  5.36s/it]

[I 2025-12-02 19:36:09,513] Trial 7 finished with value: 0.4919028340080972 and parameters: {'max_depth': 7, 'learning_rate': 0.0101268708075264, 'n_estimators': 207, 'subsample': 0.8241779316828475, 'colsample_bytree': 0.7759922890677136, 'min_child_weight': 1, 'gamma': 3.8057632393474057, 'reg_alpha': 0.7763212771466358, 'reg_lambda': 1.2031208434323507e-07, 'max_delta_step': 9}. Best is trial 1 with value: 0.6093117408906883.

Best trial: 1. Best value: 0.609312:  18%|█▊        | 9/50 [01:06<05:05,  7.45s/it]

[I 2025-12-02 19:36:21,694] Trial 8 finished with value: 0.5445344129554656 and parameters: {'max_depth': 10, 'learning_rate': 0.038922729637688336, 'n_estimators': 463, 'subsample': 0.871755528442814, 'colsample_bytree': 0.9880325772592649, 'min_child_weight': 2, 'gamma': 2.4534589338553885, 'reg_alpha': 0.0007607623485649306, 'reg_lambda': 0.00041847578280314156, 'max_delta_step': 7}. Best is trial 1 with value: 0.6093117408906883.

Best trial: 1. Best value: 0.609312:  20%|██        | 10/50 [01:10<04:16,  6.41s/it]

[I 2025-12-02 19:36:25,730] Trial 9 finished with value: 0.5182186234817814 and parameters: {'max_depth': 10, 'learning_rate': 0.04680613419951472, 'n_estimators': 754, 'subsample': 0.7869079817079614, 'colsample_bytree': 0.5100765495872691, 'min_child_weight': 3, 'gamma': 3.870872018359276, 'reg_alpha': 1.0007625154095678e-05, 'reg_lambda': 4.518786926525581e-05, 'max_delta_step': 5}. Best is trial 1 with value: 0.6093117408906883.
[I 2025-12-02 19:36:25,825] Trial 11 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.010230867955485666, 'n_estimators': 407, 'subsample': 0.6765315016728357, 'colsample_bytree': 0.8980573866747066, 'min_child_weight': 4, 'gamma': 3.527850768415472, 'reg_alpha': 1.927993226160776, 'reg_lambda': 0.4635991445905064, 'max_delta_step': 7}. Best is trial 1 with value: 0.6093117408906883.

Best trial: 1. Best value: 0.609312:  24%|██▍       | 12/50 [01:13<02:31,  3.98s/it]

[I 2025-12-02 19:36:28,093] Trial 10 pruned.

Best trial: 1. Best value: 0.609312:  26%|██▌       | 13/50 [01:20<02:59,  4.86s/it]

[I 2025-12-02 19:36:35,615] Trial 12 pruned.

Best trial: 1. Best value: 0.609312:  28%|██▊       | 14/50 [01:33<04:10,  6.96s/it]

[I 2025-12-02 19:36:48,458] Trial 16 pruned.

Best trial: 1. Best value: 0.609312:  30%|███       | 15/50 [01:35<03:20,  5.74s/it]

[I 2025-12-02 19:36:50,958] Trial 13 pruned.

Best trial: 1. Best value: 0.609312:  32%|███▏      | 16/50 [02:05<07:03, 12.44s/it]

[I 2025-12-02 19:37:20,582] Trial 14 finished with value: 0.2560728744939271 and parameters: {'max_depth': 3, 'learning_rate': 0.2090287483945256, 'n_estimators': 1391, 'subsample': 0.5058663485893018, 'colsample_bytree': 0.6775137368422042, 'min_child_weight': 6, 'gamma': 1.7542870148232077, 'reg_alpha': 0.002557390998093038, 'reg_lambda': 0.001572147961091998, 'max_delta_step': 10}. Best is trial 1 with value: 0.6093117408906883.

Best trial: 1. Best value: 0.609312:  34%|███▍      | 17/50 [02:11<05:44, 10.44s/it]

[I 2025-12-02 19:37:26,025] Trial 15 finished with value: 0.2034412955465587 and parameters: {'max_depth': 3, 'learning_rate': 0.07207705694457488, 'n_estimators': 1492, 'subsample': 0.5121604756007787, 'colsample_bytree': 0.6696782970024863, 'min_child_weight': 6, 'gamma': 1.6260837745014058, 'reg_alpha': 0.0013635894107047243, 'reg_lambda': 0.002714187093871862, 'max_delta_step': 10}. Best is trial 1 with value: 0.6093117408906883.

Best trial: 1. Best value: 0.609312:  36%|███▌      | 18/50 [02:15<04:38,  8.72s/it]

[I 2025-12-02 19:37:30,522] Trial 19 pruned.

Best trial: 18. Best value: 0.616397:  38%|███▊      | 19/50 [02:19<03:47,  7.34s/it]

[I 2025-12-02 19:37:34,546] Trial 18 finished with value: 0.6163967611336032 and parameters: {'max_depth': 6, 'learning_rate': 0.07889838967198333, 'n_estimators': 1081, 'subsample': 0.6269297357975334, 'colsample_bytree': 0.6820782602780556, 'min_child_weight': 2, 'gamma': 1.7669520182269527, 'reg_alpha': 1.9093776822964112e-08, 'reg_lambda': 0.0008385015871196516, 'max_delta_step': 10}. Best is trial 18 with value: 0.6163967611336032.

Best trial: 18. Best value: 0.616397:  40%|████      | 20/50 [02:23<03:12,  6.42s/it]

[I 2025-12-02 19:37:38,761] Trial 17 finished with value: 0.5182186234817814 and parameters: {'max_depth': 6, 'learning_rate': 0.0710098447527892, 'n_estimators': 1244, 'subsample': 0.5959032891436798, 'colsample_bytree': 0.6868715122290089, 'min_child_weight': 2, 'gamma': 1.6329952532567866, 'reg_alpha': 1.683217770751406e-08, 'reg_lambda': 0.0020091936299710847, 'max_delta_step': 0}. Best is trial 18 with value: 0.6163967611336032.

Best trial: 18. Best value: 0.616397:  42%|████▏     | 21/50 [02:28<02:53,  5.99s/it]

[I 2025-12-02 19:37:43,752] Trial 23 pruned.

Best trial: 18. Best value: 0.616397:  44%|████▍     | 22/50 [02:42<03:53,  8.32s/it]

[I 2025-12-02 19:37:57,572] Trial 21 finished with value: 0.6163967611336032 and parameters: {'max_depth': 5, 'learning_rate': 0.027016205839214342, 'n_estimators': 623, 'subsample': 0.6263943401173347, 'colsample_bytree': 0.7199240512678102, 'min_child_weight': 2, 'gamma': 2.2414565709961476, 'reg_alpha': 9.001551596352828e-05, 'reg_lambda': 5.4005141678576635e-05, 'max_delta_step': 8}. Best is trial 18 with value: 0.6163967611336032.

Best trial: 20. Best value: 0.628543:  46%|████▌     | 23/50 [02:54<04:12,  9.35s/it]

[I 2025-12-02 19:38:09,351] Trial 20 finished with value: 0.6285425101214575 and parameters: {'max_depth': 6, 'learning_rate': 0.026752080857573524, 'n_estimators': 1039, 'subsample': 0.6411592058450252, 'colsample_bytree': 0.7164304473569585, 'min_child_weight': 2, 'gamma': 0.6673133834317895, 'reg_alpha': 4.5300177460239195e-05, 'reg_lambda': 9.302393792239123e-07, 'max_delta_step': 1}. Best is trial 20 with value: 0.6285425101214575.

Best trial: 20. Best value: 0.628543:  48%|████▊     | 24/50 [02:58<03:24,  7.86s/it]

[I 2025-12-02 19:38:13,696] Trial 24 pruned.

Best trial: 20. Best value: 0.628543:  50%|█████     | 25/50 [03:04<03:01,  7.27s/it]

[I 2025-12-02 19:38:19,605] Trial 22 finished with value: 0.5253036437246963 and parameters: {'max_depth': 5, 'learning_rate': 0.028216438340019735, 'n_estimators': 1237, 'subsample': 0.7013383941004795, 'colsample_bytree': 0.7118380987739199, 'min_child_weight': 3, 'gamma': 0.9831831074503103, 'reg_alpha': 1.2945103146333299e-08, 'reg_lambda': 0.050447877232775815, 'max_delta_step': 8}. Best is trial 20 with value: 0.6285425101214575.

Best trial: 20. Best value: 0.628543:  52%|█████▏    | 26/50 [03:28<04:52, 12.20s/it]

[I 2025-12-02 19:38:43,337] Trial 25 finished with value: 0.5182186234817814 and parameters: {'max_depth': 5, 'learning_rate': 0.02593988516321065, 'n_estimators': 953, 'subsample': 0.7026541145924601, 'colsample_bytree': 0.7179308420116385, 'min_child_weight': 1, 'gamma': 4.974123796670235, 'reg_alpha': 8.394155003190502e-05, 'reg_lambda': 1.4387970940809815e-05, 'max_delta_step': 8}. Best is trial 20 with value: 0.6285425101214575.

Best trial: 20. Best value: 0.628543:  54%|█████▍    | 27/50 [03:29<03:27,  9.03s/it]

[I 2025-12-02 19:38:44,953] Trial 26 finished with value: 0.5374493927125505 and parameters: {'max_depth': 5, 'learning_rate': 0.031661762343351274, 'n_estimators': 926, 'subsample': 0.715195127493429, 'colsample_bytree': 0.7221947794139684, 'min_child_weight': 3, 'gamma': 0.0514222699597644, 'reg_alpha': 9.58367182312807e-05, 'reg_lambda': 1.897793515688439e-05, 'max_delta_step': 1}. Best is trial 20 with value: 0.6285425101214575.

Best trial: 20. Best value: 0.628543:  56%|█████▌    | 28/50 [03:34<02:51,  7.80s/it]

[I 2025-12-02 19:38:49,862] Trial 29 pruned.

Best trial: 20. Best value: 0.628543:  58%|█████▊    | 29/50 [03:35<01:56,  5.54s/it]

[I 2025-12-02 19:38:50,151] Trial 27 finished with value: 0.5445344129554656 and parameters: {'max_depth': 5, 'learning_rate': 0.017540389380021795, 'n_estimators': 901, 'subsample': 0.7130962159580305, 'colsample_bytree': 0.7238015147655161, 'min_child_weight': 3, 'gamma': 0.24499759127679466, 'reg_alpha': 1.9246664838485637e-07, 'reg_lambda': 2.995763103960556e-07, 'max_delta_step': 1}. Best is trial 20 with value: 0.6285425101214575.

Best trial: 20. Best value: 0.628543:  60%|██████    | 30/50 [03:35<01:21,  4.07s/it]

[I 2025-12-02 19:38:50,778] Trial 30 pruned.

Best trial: 20. Best value: 0.628543:  62%|██████▏   | 31/50 [03:40<01:22,  4.35s/it]

[I 2025-12-02 19:38:55,791] Trial 28 finished with value: 0.4797570850202429 and parameters: {'max_depth': 5, 'learning_rate': 0.018809592787310554, 'n_estimators': 923, 'subsample': 0.7228484036290581, 'colsample_bytree': 0.6165641734515073, 'min_child_weight': 3, 'gamma': 4.964437756635723, 'reg_alpha': 2.0937775712409668e-07, 'reg_lambda': 2.7364303356516717e-07, 'max_delta_step': 1}. Best is trial 20 with value: 0.6285425101214575.

Best trial: 20. Best value: 0.628543:  64%|██████▍   | 32/50 [03:42<01:04,  3.56s/it]

[I 2025-12-02 19:38:57,503] Trial 31 pruned.

Best trial: 20. Best value: 0.628543:  66%|██████▌   | 33/50 [03:42<00:44,  2.63s/it]

[I 2025-12-02 19:38:57,972] Trial 32 pruned.

Best trial: 20. Best value: 0.628543:  68%|██████▊   | 34/50 [03:46<00:45,  2.84s/it]

[I 2025-12-02 19:39:01,295] Trial 33 pruned.

Best trial: 20. Best value: 0.628543:  70%|███████   | 35/50 [03:47<00:37,  2.47s/it]

[I 2025-12-02 19:39:02,901] Trial 36 pruned.

Best trial: 20. Best value: 0.628543:  72%|███████▏  | 36/50 [03:50<00:34,  2.47s/it]

[I 2025-12-02 19:39:05,358] Trial 37 pruned.

Best trial: 20. Best value: 0.628543:  74%|███████▍  | 37/50 [03:52<00:31,  2.44s/it]

[I 2025-12-02 19:39:07,732] Trial 38 pruned.

Best trial: 20. Best value: 0.628543:  76%|███████▌  | 38/50 [03:58<00:41,  3.49s/it]

[I 2025-12-02 19:39:13,669] Trial 39 pruned.

Best trial: 20. Best value: 0.628543:  78%|███████▊  | 39/50 [04:12<01:12,  6.55s/it]

[I 2025-12-02 19:39:27,359] Trial 34 finished with value: 0.4989878542510121 and parameters: {'max_depth': 4, 'learning_rate': 0.013950222219671217, 'n_estimators': 557, 'subsample': 0.9914704039177579, 'colsample_bytree': 0.8328279191846243, 'min_child_weight': 2, 'gamma': 1.238718170305518, 'reg_alpha': 4.563021950450272e-06, 'reg_lambda': 2.588044189437104e-06, 'max_delta_step': 6}. Best is trial 20 with value: 0.6285425101214575.

Best trial: 20. Best value: 0.628543:  80%|████████  | 40/50 [04:21<01:12,  7.26s/it]

[I 2025-12-02 19:39:36,286] Trial 35 finished with value: 0.5445344129554656 and parameters: {'max_depth': 4, 'learning_rate': 0.044714449376644844, 'n_estimators': 1059, 'subsample': 0.6041996026949675, 'colsample_bytree': 0.8138609163394673, 'min_child_weight': 2, 'gamma': 1.2708411721934612, 'reg_alpha': 5.012079167061162e-06, 'reg_lambda': 3.0714441596499548e-06, 'max_delta_step': 9}. Best is trial 20 with value: 0.6285425101214575.

Best trial: 20. Best value: 0.628543:  82%|████████▏ | 41/50 [04:24<00:54,  6.06s/it]

[I 2025-12-02 19:39:39,543] Trial 40 pruned.

Best trial: 20. Best value: 0.628543:  84%|████████▍ | 42/50 [04:33<00:56,  7.01s/it]

[I 2025-12-02 19:39:48,773] Trial 41 pruned.

Best trial: 20. Best value: 0.628543:  86%|████████▌ | 43/50 [04:44<00:57,  8.26s/it]

[I 2025-12-02 19:39:59,959] Trial 42 pruned.

Best trial: 20. Best value: 0.628543:  88%|████████▊ | 44/50 [04:53<00:49,  8.30s/it]

[I 2025-12-02 19:40:08,355] Trial 46 pruned.

Best trial: 20. Best value: 0.628543:  90%|█████████ | 45/50 [04:54<00:30,  6.13s/it]

[I 2025-12-02 19:40:09,422] Trial 43 pruned.

Best trial: 20. Best value: 0.628543:  92%|█████████▏| 46/50 [04:56<00:19,  4.96s/it]

[I 2025-12-02 19:40:11,652] Trial 47 pruned.

Best trial: 20. Best value: 0.628543:  94%|█████████▍| 47/50 [05:07<00:20,  6.71s/it]

[I 2025-12-02 19:40:22,458] Trial 49 pruned.

Best trial: 20. Best value: 0.628543:  96%|█████████▌| 48/50 [05:08<00:10,  5.14s/it]

[I 2025-12-02 19:40:23,927] Trial 44 finished with value: 0.5445344129554656 and parameters: {'max_depth': 7, 'learning_rate': 0.05588145332392069, 'n_estimators': 1156, 'subsample': 0.5422037326312834, 'colsample_bytree': 0.5774292947899063, 'min_child_weight': 1, 'gamma': 2.342860289651968, 'reg_alpha': 2.8985922628261088e-05, 'reg_lambda': 0.0009001117548889321, 'max_delta_step': 10}. Best is trial 20 with value: 0.6285425101214575.

Best trial: 20. Best value: 0.628543:  98%|█████████▊| 49/50 [05:09<00:03,  3.89s/it]

[I 2025-12-02 19:40:24,911] Trial 48 finished with value: 0.5637651821862348 and parameters: {'max_depth': 9, 'learning_rate': 0.05521938741817017, 'n_estimators': 377, 'subsample': 0.5359196241132221, 'colsample_bytree': 0.5837525012646667, 'min_child_weight': 2, 'gamma': 1.8868438121971982, 'reg_alpha': 0.0005590933039295273, 'reg_lambda': 8.7361447074064e-06, 'max_delta_step': 8}. Best is trial 20 with value: 0.6285425101214575.

Best trial: 20. Best value: 0.628543: 100%|██████████| 50/50 [05:14<00:00,  6.29s/it]

[I 2025-12-02 19:40:29,459] Trial 45 finished with value: 0.5374493927125505 and parameters: {'max_depth': 7, 'learning_rate': 0.05386710044229904, 'n_estimators': 1147, 'subsample': 0.6794930801100961, 'colsample_bytree': 0.5665231998135175, 'min_child_weight': 1, 'gamma': 1.8946828734795105, 'reg_alpha': 0.0002792483921778351, 'reg_lambda': 0.0006450975887147743, 'max_delta_step': 10}. Best is trial 20 with value: 0.6285425101214575.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.628543                0.314286      0.171429

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.371429          0.428571               0.2        50          45

   test_size
0         12
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.628543                0.314286      0.171429

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.371429          0.428571               0.2        50          45

   test_size
0         12

In [ ]:

# Combined embedings
datasets = task_comb_dfs_ad_lbd

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_lbd_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_combined_ad_lbd_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param="emb_",
)
print(summary)

[I 2025-12-02 19:40:35,333] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 45, Test size: 12
Using Leave-One-Out CV with 45 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0:   2%|▏         | 1/50 [00:20<16:59, 20.82s/it]

[I 2025-12-02 19:40:56,141] Trial 3 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.10793668256167428, 'n_estimators': 440, 'subsample': 0.5838503068279008, 'colsample_bytree': 0.9797530232235989, 'min_child_weight': 9, 'gamma': 0.3834143310146737, 'reg_alpha': 2.68642185214544e-06, 'reg_lambda': 5.170673458154929e-08, 'max_delta_step': 7}. Best is trial 3 with value: 0.0.

Best trial: 3. Best value: 0:   4%|▍         | 2/50 [00:35<13:41, 17.11s/it]

[I 2025-12-02 19:41:10,656] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 3, 'learning_rate': 0.277675772144458, 'n_estimators': 335, 'subsample': 0.9899059909912773, 'colsample_bytree': 0.5150962196898464, 'min_child_weight': 9, 'gamma': 2.486759374923055, 'reg_alpha': 0.22083615082430486, 'reg_lambda': 6.61179256618377e-08, 'max_delta_step': 0}. Best is trial 3 with value: 0.0.

Best trial: 3. Best value: 0:   6%|▌         | 3/50 [00:36<07:46,  9.93s/it]

[I 2025-12-02 19:41:12,038] Trial 1 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.03276478199401491, 'n_estimators': 908, 'subsample': 0.8069104056300547, 'colsample_bytree': 0.6268258804268647, 'min_child_weight': 10, 'gamma': 1.8467576821224236, 'reg_alpha': 0.003023248303104937, 'reg_lambda': 0.0004409311090640945, 'max_delta_step': 5}. Best is trial 3 with value: 0.0.

Best trial: 3. Best value: 0:   8%|▊         | 4/50 [00:48<08:11, 10.68s/it]

[I 2025-12-02 19:41:23,878] Trial 2 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.01442642388561356, 'n_estimators': 1213, 'subsample': 0.8334485655156112, 'colsample_bytree': 0.6599026518609337, 'min_child_weight': 7, 'gamma': 4.518915018837776, 'reg_alpha': 0.681267442903194, 'reg_lambda': 0.00021414813142767232, 'max_delta_step': 2}. Best is trial 3 with value: 0.0.

Best trial: 5. Best value: 0.365385:  10%|█         | 5/50 [00:54<06:47,  9.06s/it]

[I 2025-12-02 19:41:30,072] Trial 5 finished with value: 0.36538461538461536 and parameters: {'max_depth': 7, 'learning_rate': 0.09451162623981423, 'n_estimators': 438, 'subsample': 0.6180251321096385, 'colsample_bytree': 0.7023480447163604, 'min_child_weight': 6, 'gamma': 1.9778902472857385, 'reg_alpha': 4.4935226812302265e-08, 'reg_lambda': 0.06470438337157544, 'max_delta_step': 0}. Best is trial 5 with value: 0.36538461538461536.

Best trial: 5. Best value: 0.365385:  12%|█▏        | 6/50 [01:01<06:02,  8.24s/it]

[I 2025-12-02 19:41:36,699] Trial 6 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.09515337327758773, 'n_estimators': 607, 'subsample': 0.923861411726844, 'colsample_bytree': 0.5949963606328709, 'min_child_weight': 7, 'gamma': 3.290260251059003, 'reg_alpha': 0.0002668470237455702, 'reg_lambda': 1.6668470043989575e-05, 'max_delta_step': 10}. Best is trial 5 with value: 0.36538461538461536.

Best trial: 0. Best value: 0.55668:  14%|█▍        | 7/50 [01:04<04:46,  6.65s/it]

[I 2025-12-02 19:41:40,099] Trial 0 finished with value: 0.5566801619433198 and parameters: {'max_depth': 6, 'learning_rate': 0.015022688345631323, 'n_estimators': 1460, 'subsample': 0.7054604955958979, 'colsample_bytree': 0.7096405491332085, 'min_child_weight': 3, 'gamma': 3.4866296287843674, 'reg_alpha': 0.011587779775717354, 'reg_lambda': 0.09345170347646391, 'max_delta_step': 6}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  16%|█▌        | 8/50 [01:41<11:23, 16.28s/it]

[I 2025-12-02 19:42:16,999] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.05886009316512184, 'n_estimators': 1304, 'subsample': 0.8311256750694471, 'colsample_bytree': 0.9925349185642901, 'min_child_weight': 9, 'gamma': 4.901505947074509, 'reg_alpha': 1.1475418327805816e-05, 'reg_lambda': 4.4564497843107946e-08, 'max_delta_step': 10}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  18%|█▊        | 9/50 [01:45<08:23, 12.29s/it]

[I 2025-12-02 19:42:20,498] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.016732473764421538, 'n_estimators': 1028, 'subsample': 0.9187400976347677, 'colsample_bytree': 0.9928095129076875, 'min_child_weight': 7, 'gamma': 3.891345496853202, 'reg_alpha': 0.26942001715464137, 'reg_lambda': 1.8173133451292268e-07, 'max_delta_step': 6}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  20%|██        | 10/50 [01:46<05:53,  8.84s/it]

[I 2025-12-02 19:42:21,612] Trial 8 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.034244679916810225, 'n_estimators': 1296, 'subsample': 0.9465571322404676, 'colsample_bytree': 0.7743166111676923, 'min_child_weight': 9, 'gamma': 1.6971530116393096, 'reg_alpha': 0.007568426615700728, 'reg_lambda': 0.15960139880007707, 'max_delta_step': 8}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  22%|██▏       | 11/50 [01:57<06:11,  9.52s/it]

[I 2025-12-02 19:42:32,677] Trial 10 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.0751843371088367, 'n_estimators': 1400, 'subsample': 0.5297694742991919, 'colsample_bytree': 0.5523519250309705, 'min_child_weight': 8, 'gamma': 0.14289035403451167, 'reg_alpha': 2.7466897436124943e-07, 'reg_lambda': 0.00971440278352262, 'max_delta_step': 8}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  24%|██▍       | 12/50 [02:06<05:53,  9.31s/it]

[I 2025-12-02 19:42:41,503] Trial 11 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.013617556972266427, 'n_estimators': 589, 'subsample': 0.8349327801812787, 'colsample_bytree': 0.8090858608361653, 'min_child_weight': 10, 'gamma': 1.9797283435953101, 'reg_alpha': 6.643735490164568e-05, 'reg_lambda': 5.979824819634289e-08, 'max_delta_step': 6}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  26%|██▌       | 13/50 [02:12<05:07,  8.30s/it]

[I 2025-12-02 19:42:47,487] Trial 12 finished with value: 0.5303643724696356 and parameters: {'max_depth': 6, 'learning_rate': 0.02901997846128393, 'n_estimators': 473, 'subsample': 0.639962312424271, 'colsample_bytree': 0.8666809934895572, 'min_child_weight': 2, 'gamma': 4.29224486710721, 'reg_alpha': 1.9019108324706431e-06, 'reg_lambda': 0.14990517981737772, 'max_delta_step': 0}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  28%|██▊       | 14/50 [02:27<06:15, 10.43s/it]

[I 2025-12-02 19:43:02,818] Trial 14 finished with value: 0.5232793522267206 and parameters: {'max_depth': 5, 'learning_rate': 0.19244032188860952, 'n_estimators': 676, 'subsample': 0.6647190803572686, 'colsample_bytree': 0.7954160808969962, 'min_child_weight': 3, 'gamma': 3.2207045214374386, 'reg_alpha': 4.570112601440082e-08, 'reg_lambda': 9.610426703182512, 'max_delta_step': 4}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  30%|███       | 15/50 [02:39<06:23, 10.97s/it]

[I 2025-12-02 19:43:15,047] Trial 15 finished with value: 0.5425101214574899 and parameters: {'max_depth': 7, 'learning_rate': 0.2399733060196516, 'n_estimators': 763, 'subsample': 0.6813708760651874, 'colsample_bytree': 0.7162990092070025, 'min_child_weight': 3, 'gamma': 3.1973748773582127, 'reg_alpha': 1.2292267310108358e-08, 'reg_lambda': 9.621250707400279, 'max_delta_step': 3}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  32%|███▏      | 16/50 [02:44<05:14,  9.24s/it]

[I 2025-12-02 19:43:20,265] Trial 17 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.025533372714740977, 'n_estimators': 228, 'subsample': 0.6991263321911867, 'colsample_bytree': 0.8685334864026231, 'min_child_weight': 1, 'gamma': 3.8678936837005704, 'reg_alpha': 9.196490052371429, 'reg_lambda': 4.045184382850705, 'max_delta_step': 3}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  34%|███▍      | 17/50 [02:57<05:40, 10.31s/it]

[I 2025-12-02 19:43:33,078] Trial 16 finished with value: 0.49696356275303644 and parameters: {'max_depth': 5, 'learning_rate': 0.025338889839972796, 'n_estimators': 756, 'subsample': 0.6932496951483562, 'colsample_bytree': 0.8636971020751195, 'min_child_weight': 2, 'gamma': 3.5049972263538223, 'reg_alpha': 0.005792100162545702, 'reg_lambda': 7.399299748285263, 'max_delta_step': 3}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  36%|███▌      | 18/50 [03:15<06:42, 12.57s/it]

[I 2025-12-02 19:43:50,901] Trial 19 finished with value: 0.47773279352226716 and parameters: {'max_depth': 7, 'learning_rate': 0.17883941668823716, 'n_estimators': 828, 'subsample': 0.7425113543218207, 'colsample_bytree': 0.7065205935454196, 'min_child_weight': 4, 'gamma': 2.99284554598444, 'reg_alpha': 0.0057645445655402664, 'reg_lambda': 2.6362932663351835, 'max_delta_step': 2}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  38%|███▊      | 19/50 [03:19<05:05,  9.87s/it]

[I 2025-12-02 19:43:54,477] Trial 18 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.15508628139977748, 'n_estimators': 1081, 'subsample': 0.714591200259285, 'colsample_bytree': 0.6923072713585927, 'min_child_weight': 4, 'gamma': 3.2811691972413617, 'reg_alpha': 6.092542507150067, 'reg_lambda': 9.036960721495683, 'max_delta_step': 3}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  40%|████      | 20/50 [03:25<04:22,  8.77s/it]

[I 2025-12-02 19:44:00,663] Trial 13 finished with value: 0.41295546558704455 and parameters: {'max_depth': 4, 'learning_rate': 0.010421802804193676, 'n_estimators': 1475, 'subsample': 0.6724708603212857, 'colsample_bytree': 0.825753257880059, 'min_child_weight': 1, 'gamma': 3.3922526591171565, 'reg_alpha': 9.957306612266552e-05, 'reg_lambda': 7.933732673535048, 'max_delta_step': 4}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  42%|████▏     | 21/50 [03:37<04:43,  9.79s/it]

[I 2025-12-02 19:44:12,852] Trial 20 finished with value: 0.4919028340080972 and parameters: {'max_depth': 7, 'learning_rate': 0.18301395380091887, 'n_estimators': 1061, 'subsample': 0.7474256113774571, 'colsample_bytree': 0.713865053315579, 'min_child_weight': 4, 'gamma': 2.755404565810903, 'reg_alpha': 1.0327963729991893e-08, 'reg_lambda': 0.7391137236292852, 'max_delta_step': 2}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  44%|████▍     | 22/50 [03:56<05:54, 12.66s/it]

[I 2025-12-02 19:44:32,200] Trial 21 finished with value: 0.19230769230769232 and parameters: {'max_depth': 8, 'learning_rate': 0.04926494770101834, 'n_estimators': 1062, 'subsample': 0.7514166694116372, 'colsample_bytree': 0.7071054901153832, 'min_child_weight': 5, 'gamma': 2.5891721553453713, 'reg_alpha': 0.00040766003232291427, 'reg_lambda': 0.00976169112789128, 'max_delta_step': 5}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  46%|████▌     | 23/50 [04:01<04:35, 10.19s/it]

[I 2025-12-02 19:44:36,639] Trial 24 finished with value: 0.5495951417004048 and parameters: {'max_depth': 6, 'learning_rate': 0.03928642909419571, 'n_estimators': 492, 'subsample': 0.6038156299353, 'colsample_bytree': 0.9267471834774541, 'min_child_weight': 3, 'gamma': 4.21144152686744, 'reg_alpha': 8.476555599603864e-07, 'reg_lambda': 0.022177968959291968, 'max_delta_step': 1}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  48%|████▊     | 24/50 [04:03<03:23,  7.84s/it]

[I 2025-12-02 19:44:38,998] Trial 23 finished with value: 0.0 and parameters: {'max_depth': 8, 'learning_rate': 0.04615595533161734, 'n_estimators': 981, 'subsample': 0.7768824670912267, 'colsample_bytree': 0.7424128550262288, 'min_child_weight': 5, 'gamma': 2.662287754218687, 'reg_alpha': 0.03928194075675806, 'reg_lambda': 0.005698850066896214, 'max_delta_step': 5}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  50%|█████     | 25/50 [04:16<03:57,  9.48s/it]

[I 2025-12-02 19:44:52,307] Trial 22 finished with value: 0.23076923076923078 and parameters: {'max_depth': 8, 'learning_rate': 0.010489402540863715, 'n_estimators': 1492, 'subsample': 0.7750604194385793, 'colsample_bytree': 0.7392142079669419, 'min_child_weight': 5, 'gamma': 2.6057181532429547, 'reg_alpha': 0.0007303236239587447, 'reg_lambda': 0.009451099853948434, 'max_delta_step': 5}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  52%|█████▏    | 26/50 [04:29<04:08, 10.34s/it]

[I 2025-12-02 19:45:04,631] Trial 25 finished with value: 0.5566801619433198 and parameters: {'max_depth': 6, 'learning_rate': 0.019776947194156104, 'n_estimators': 508, 'subsample': 0.616887347780315, 'colsample_bytree': 0.9142509688706044, 'min_child_weight': 2, 'gamma': 4.1117312735562, 'reg_alpha': 1.0700273676091026e-06, 'reg_lambda': 0.2764832634342462, 'max_delta_step': 1}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  54%|█████▍    | 27/50 [04:38<03:47,  9.89s/it]

[I 2025-12-02 19:45:13,495] Trial 27 finished with value: 0.5111336032388664 and parameters: {'max_depth': 6, 'learning_rate': 0.020208897279459934, 'n_estimators': 714, 'subsample': 0.5626648214282433, 'colsample_bytree': 0.929214659739682, 'min_child_weight': 3, 'gamma': 3.9913778950886067, 'reg_alpha': 4.575966819513132e-07, 'reg_lambda': 0.5874784697731126, 'max_delta_step': 1}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  56%|█████▌    | 28/50 [04:41<02:52,  7.83s/it]

[I 2025-12-02 19:45:16,495] Trial 26 finished with value: 0.5111336032388664 and parameters: {'max_depth': 6, 'learning_rate': 0.04486051460744463, 'n_estimators': 880, 'subsample': 0.5567467693952166, 'colsample_bytree': 0.9200669940670656, 'min_child_weight': 3, 'gamma': 4.025025577563117, 'reg_alpha': 3.2819882562211485e-07, 'reg_lambda': 0.010537329981844428, 'max_delta_step': 2}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  58%|█████▊    | 29/50 [04:45<02:19,  6.64s/it]

[I 2025-12-02 19:45:20,361] Trial 28 finished with value: 0.5111336032388664 and parameters: {'max_depth': 6, 'learning_rate': 0.019576972382778106, 'n_estimators': 559, 'subsample': 0.5828236543438164, 'colsample_bytree': 0.9278503072921842, 'min_child_weight': 3, 'gamma': 3.962040432363538, 'reg_alpha': 5.408699200870928e-07, 'reg_lambda': 0.0008861714859341828, 'max_delta_step': 1}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  60%|██████    | 30/50 [04:50<02:05,  6.29s/it]

[I 2025-12-02 19:45:25,853] Trial 29 finished with value: 0.5374493927125505 and parameters: {'max_depth': 6, 'learning_rate': 0.019657587340312133, 'n_estimators': 257, 'subsample': 0.5587699407707204, 'colsample_bytree': 0.923267126466033, 'min_child_weight': 2, 'gamma': 3.9360563774753654, 'reg_alpha': 6.811215264393868e-07, 'reg_lambda': 0.5078169408132586, 'max_delta_step': 1}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  62%|██████▏   | 31/50 [04:56<01:57,  6.18s/it]

[I 2025-12-02 19:45:31,766] Trial 30 finished with value: 0.5303643724696356 and parameters: {'max_depth': 5, 'learning_rate': 0.020167246640922856, 'n_estimators': 212, 'subsample': 0.5154107323697741, 'colsample_bytree': 0.9347398775370279, 'min_child_weight': 2, 'gamma': 4.689738994233926, 'reg_alpha': 1.2858345784845521e-05, 'reg_lambda': 0.0004470210881987622, 'max_delta_step': 1}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  64%|██████▍   | 32/50 [05:01<01:46,  5.91s/it]

[I 2025-12-02 19:45:37,044] Trial 31 finished with value: 0.5303643724696356 and parameters: {'max_depth': 5, 'learning_rate': 0.020570969117497794, 'n_estimators': 226, 'subsample': 0.506352819966009, 'colsample_bytree': 0.9336263444349586, 'min_child_weight': 2, 'gamma': 4.826865486742527, 'reg_alpha': 1.7367501151619303e-05, 'reg_lambda': 0.0016307871243199646, 'max_delta_step': 1}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 0. Best value: 0.55668:  66%|██████▌   | 33/50 [05:03<01:21,  4.77s/it]

[I 2025-12-02 19:45:39,155] Trial 32 finished with value: 0.5111336032388664 and parameters: {'max_depth': 5, 'learning_rate': 0.03521761864058035, 'n_estimators': 227, 'subsample': 0.6231424178139455, 'colsample_bytree': 0.6060200821442056, 'min_child_weight': 2, 'gamma': 4.98797543231417, 'reg_alpha': 3.939639870964569e-06, 'reg_lambda': 0.001008481336000286, 'max_delta_step': 1}. Best is trial 0 with value: 0.5566801619433198.

Best trial: 33. Best value: 0.575911:  68%|██████▊   | 34/50 [05:17<01:56,  7.30s/it]

[I 2025-12-02 19:45:52,346] Trial 33 finished with value: 0.5759109311740891 and parameters: {'max_depth': 5, 'learning_rate': 0.036633165644318906, 'n_estimators': 335, 'subsample': 0.6105631450305609, 'colsample_bytree': 0.6457996964492488, 'min_child_weight': 1, 'gamma': 4.983811880856114, 'reg_alpha': 1.3994476235825059e-05, 'reg_lambda': 0.0010626343951782543, 'max_delta_step': 7}. Best is trial 33 with value: 0.5759109311740891.

Best trial: 33. Best value: 0.575911:  70%|███████   | 35/50 [05:26<02:01,  8.08s/it]

[I 2025-12-02 19:46:02,271] Trial 35 finished with value: 0.5759109311740891 and parameters: {'max_depth': 7, 'learning_rate': 0.03635632502146153, 'n_estimators': 358, 'subsample': 0.6197365197415999, 'colsample_bytree': 0.6472745350406858, 'min_child_weight': 1, 'gamma': 4.312582178032087, 'reg_alpha': 6.622500183884346e-08, 'reg_lambda': 0.05627174678713739, 'max_delta_step': 4}. Best is trial 33 with value: 0.5759109311740891.

Best trial: 33. Best value: 0.575911:  72%|███████▏  | 36/50 [05:31<01:37,  6.96s/it]

[I 2025-12-02 19:46:06,605] Trial 34 finished with value: 0.5759109311740891 and parameters: {'max_depth': 7, 'learning_rate': 0.039513193903501574, 'n_estimators': 507, 'subsample': 0.621941775344942, 'colsample_bytree': 0.663632460136928, 'min_child_weight': 1, 'gamma': 4.45066744772171, 'reg_alpha': 4.423645144098957e-08, 'reg_lambda': 0.07289237873951548, 'max_delta_step': 4}. Best is trial 33 with value: 0.5759109311740891.

Best trial: 33. Best value: 0.575911:  74%|███████▍  | 37/50 [05:42<01:47,  8.25s/it]

[I 2025-12-02 19:46:17,873] Trial 36 finished with value: 0.5759109311740891 and parameters: {'max_depth': 7, 'learning_rate': 0.013555939394961216, 'n_estimators': 512, 'subsample': 0.6560154592009464, 'colsample_bytree': 0.649969137719132, 'min_child_weight': 1, 'gamma': 4.538270775247299, 'reg_alpha': 1.0017568429094495e-08, 'reg_lambda': 0.050682802990015534, 'max_delta_step': 3}. Best is trial 33 with value: 0.5759109311740891.

Best trial: 33. Best value: 0.575911:  76%|███████▌  | 38/50 [05:46<01:23,  6.95s/it]

[I 2025-12-02 19:46:21,792] Trial 37 finished with value: 0.5303643724696356 and parameters: {'max_depth': 3, 'learning_rate': 0.013295457076572571, 'n_estimators': 350, 'subsample': 0.6032981477733232, 'colsample_bytree': 0.6559819087254641, 'min_child_weight': 1, 'gamma': 4.4708882892681165, 'reg_alpha': 5.2589575683555535e-05, 'reg_lambda': 4.952660655152013e-05, 'max_delta_step': 7}. Best is trial 33 with value: 0.5759109311740891.

Best trial: 33. Best value: 0.575911:  78%|███████▊  | 39/50 [05:50<01:07,  6.16s/it]

[I 2025-12-02 19:46:26,092] Trial 38 finished with value: 0.5759109311740891 and parameters: {'max_depth': 3, 'learning_rate': 0.06574931377715985, 'n_estimators': 348, 'subsample': 0.6570412359786245, 'colsample_bytree': 0.6456997459902182, 'min_child_weight': 1, 'gamma': 4.590636595495329, 'reg_alpha': 8.937600278138767e-08, 'reg_lambda': 7.718439945383202e-05, 'max_delta_step': 7}. Best is trial 33 with value: 0.5759109311740891.

Best trial: 33. Best value: 0.575911:  80%|████████  | 40/50 [05:55<00:56,  5.69s/it]

[I 2025-12-02 19:46:30,700] Trial 39 finished with value: 0.5566801619433198 and parameters: {'max_depth': 9, 'learning_rate': 0.05609733439961628, 'n_estimators': 362, 'subsample': 0.6394598235610486, 'colsample_bytree': 0.6532716488622482, 'min_child_weight': 1, 'gamma': 4.4869091821590645, 'reg_alpha': 1.1531960193833427e-07, 'reg_lambda': 0.000129472876806066, 'max_delta_step': 7}. Best is trial 33 with value: 0.5759109311740891.

Best trial: 40. Best value: 0.602227:  82%|████████▏ | 41/50 [06:06<01:05,  7.31s/it]

[I 2025-12-02 19:46:41,775] Trial 40 finished with value: 0.6022267206477733 and parameters: {'max_depth': 9, 'learning_rate': 0.06360931804679941, 'n_estimators': 362, 'subsample': 0.6454014459296461, 'colsample_bytree': 0.6581509871716087, 'min_child_weight': 1, 'gamma': 4.592101633969283, 'reg_alpha': 4.988346539672228e-08, 'reg_lambda': 5.6693488466852735e-05, 'max_delta_step': 4}. Best is trial 40 with value: 0.6022267206477733.

Best trial: 40. Best value: 0.602227:  84%|████████▍ | 42/50 [06:11<00:52,  6.60s/it]

[I 2025-12-02 19:46:46,737] Trial 41 finished with value: 0.6022267206477733 and parameters: {'max_depth': 9, 'learning_rate': 0.06245755780755114, 'n_estimators': 368, 'subsample': 0.6519510280901463, 'colsample_bytree': 0.6534338755117511, 'min_child_weight': 1, 'gamma': 4.562631381297621, 'reg_alpha': 7.931778024708376e-08, 'reg_lambda': 8.573552933667404e-05, 'max_delta_step': 4}. Best is trial 40 with value: 0.6022267206477733.

Best trial: 40. Best value: 0.602227:  86%|████████▌ | 43/50 [06:16<00:43,  6.25s/it]

[I 2025-12-02 19:46:52,169] Trial 42 finished with value: 0.582995951417004 and parameters: {'max_depth': 9, 'learning_rate': 0.07511120008526913, 'n_estimators': 409, 'subsample': 0.6323026247095627, 'colsample_bytree': 0.586165598350727, 'min_child_weight': 1, 'gamma': 4.457379734155874, 'reg_alpha': 6.377738067354742e-08, 'reg_lambda': 0.04989719188181505, 'max_delta_step': 4}. Best is trial 40 with value: 0.6022267206477733.

Best trial: 40. Best value: 0.602227:  88%|████████▊ | 44/50 [06:22<00:36,  6.11s/it]

[I 2025-12-02 19:46:57,962] Trial 43 pruned.

Best trial: 40. Best value: 0.602227:  90%|█████████ | 45/50 [06:26<00:27,  5.47s/it]

[I 2025-12-02 19:47:01,923] Trial 47 pruned.

Best trial: 40. Best value: 0.602227:  92%|█████████▏| 46/50 [06:32<00:22,  5.51s/it]

[I 2025-12-02 19:47:07,543] Trial 45 finished with value: 0.46558704453441296 and parameters: {'max_depth': 10, 'learning_rate': 0.07471424050025126, 'n_estimators': 293, 'subsample': 0.580190643419131, 'colsample_bytree': 0.5732618660570575, 'min_child_weight': 1, 'gamma': 4.780091238465073, 'reg_alpha': 3.099396843487872e-08, 'reg_lambda': 2.9699256709159678e-06, 'max_delta_step': 4}. Best is trial 40 with value: 0.6022267206477733.

Best trial: 40. Best value: 0.602227:  94%|█████████▍| 47/50 [06:32<00:12,  4.00s/it]

[I 2025-12-02 19:47:08,020] Trial 44 finished with value: 0.5516194331983806 and parameters: {'max_depth': 10, 'learning_rate': 0.06900426159722249, 'n_estimators': 406, 'subsample': 0.5845291754859571, 'colsample_bytree': 0.5855849141707062, 'min_child_weight': 1, 'gamma': 3.5800290674223834, 'reg_alpha': 2.298656876525365e-08, 'reg_lambda': 1.1931856542534645e-05, 'max_delta_step': 4}. Best is trial 40 with value: 0.6022267206477733.

Best trial: 40. Best value: 0.602227:  96%|█████████▌| 48/50 [06:35<00:07,  3.74s/it]

[I 2025-12-02 19:47:11,163] Trial 49 pruned.

Best trial: 40. Best value: 0.602227:  98%|█████████▊| 49/50 [06:38<00:03,  3.46s/it]

[I 2025-12-02 19:47:13,951] Trial 46 finished with value: 0.5374493927125505 and parameters: {'max_depth': 10, 'learning_rate': 0.07992679124508685, 'n_estimators': 420, 'subsample': 0.5821931617012909, 'colsample_bytree': 0.5679127188577563, 'min_child_weight': 1, 'gamma': 0.8213544466791993, 'reg_alpha': 2.8080747524381048e-08, 'reg_lambda': 5.683631205825147e-06, 'max_delta_step': 4}. Best is trial 40 with value: 0.6022267206477733.

Best trial: 48. Best value: 0.635628: 100%|██████████| 50/50 [06:41<00:00,  8.04s/it]

[I 2025-12-02 19:47:17,122] Trial 48 finished with value: 0.6356275303643725 and parameters: {'max_depth': 9, 'learning_rate': 0.11316892181858225, 'n_estimators': 417, 'subsample': 0.545385964294068, 'colsample_bytree': 0.6127937518077117, 'min_child_weight': 2, 'gamma': 4.803206318806229, 'reg_alpha': 1.565823738725408e-07, 'reg_lambda': 6.259228251435669e-06, 'max_delta_step': 4}. Best is trial 48 with value: 0.6356275303643725.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.635628                0.628571      0.542857

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0   0.29277          0.857143               0.4        50          45

   test_size
0         12
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.635628                0.628571      0.542857

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0   0.29277          0.857143               0.4        50          45

   test_size
0         12

In [ ]:

datasets = task_hf_dfs_clean_ad_lbd

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_ad_lbd_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_handcrafted_ad_lbd_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param="w.cz.fnusa",
)
print(summary)

[I 2025-12-02 19:47:21,706] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 45, Test size: 12
Using Leave-One-Out CV with 45 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0:   2%|▏         | 1/50 [00:45<37:02, 45.36s/it]

[I 2025-12-02 19:48:07,058] Trial 0 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.2731793887440604, 'n_estimators': 1102, 'subsample': 0.924203992731768, 'colsample_bytree': 0.6256553496991136, 'min_child_weight': 8, 'gamma': 4.954957072691332, 'reg_alpha': 0.06291767164027327, 'reg_lambda': 0.027533766266619467, 'max_delta_step': 3}. Best is trial 0 with value: 0.0.

Best trial: 3. Best value: 0.458502:   4%|▍         | 2/50 [00:49<16:39, 20.83s/it]

[I 2025-12-02 19:48:10,713] Trial 3 finished with value: 0.458502024291498 and parameters: {'max_depth': 5, 'learning_rate': 0.07988482635501488, 'n_estimators': 1197, 'subsample': 0.6171663743613478, 'colsample_bytree': 0.67635323359354, 'min_child_weight': 1, 'gamma': 0.15195583454661932, 'reg_alpha': 0.02778457724399599, 'reg_lambda': 1.927702174799711e-06, 'max_delta_step': 9}. Best is trial 3 with value: 0.458502024291498.

Best trial: 3. Best value: 0.458502:   6%|▌         | 3/50 [00:51<09:42, 12.40s/it]

[I 2025-12-02 19:48:13,069] Trial 2 finished with value: 0.42105263157894735 and parameters: {'max_depth': 5, 'learning_rate': 0.13953325203099035, 'n_estimators': 1273, 'subsample': 0.6173992728952828, 'colsample_bytree': 0.5380502982296522, 'min_child_weight': 6, 'gamma': 2.9399665949240594, 'reg_alpha': 0.00023140791249506092, 'reg_lambda': 1.6238007037010889, 'max_delta_step': 10}. Best is trial 3 with value: 0.458502024291498.

Best trial: 3. Best value: 0.458502:   8%|▊         | 4/50 [00:57<07:40, 10.02s/it]

[I 2025-12-02 19:48:19,445] Trial 1 finished with value: 0.40789473684210525 and parameters: {'max_depth': 5, 'learning_rate': 0.07169633046146827, 'n_estimators': 1419, 'subsample': 0.9449323911566778, 'colsample_bytree': 0.8465965843230151, 'min_child_weight': 4, 'gamma': 0.8138021605224893, 'reg_alpha': 0.13249001226128757, 'reg_lambda': 6.424825523768389e-06, 'max_delta_step': 3}. Best is trial 3 with value: 0.458502024291498.

Best trial: 3. Best value: 0.458502:  10%|█         | 5/50 [01:10<08:07, 10.84s/it]

[I 2025-12-02 19:48:31,749] Trial 4 finished with value: 0.0 and parameters: {'max_depth': 4, 'learning_rate': 0.010205973767316044, 'n_estimators': 605, 'subsample': 0.5626429952921395, 'colsample_bytree': 0.8187864573135355, 'min_child_weight': 7, 'gamma': 3.5523284661055166, 'reg_alpha': 7.681473624179374, 'reg_lambda': 0.009914940539758834, 'max_delta_step': 6}. Best is trial 3 with value: 0.458502024291498.

Best trial: 3. Best value: 0.458502:  12%|█▏        | 6/50 [01:19<07:38, 10.42s/it]

[I 2025-12-02 19:48:41,347] Trial 6 finished with value: 0.0 and parameters: {'max_depth': 10, 'learning_rate': 0.022367772872058045, 'n_estimators': 715, 'subsample': 0.8954579913704434, 'colsample_bytree': 0.6647441064348432, 'min_child_weight': 5, 'gamma': 4.955372140375914, 'reg_alpha': 0.14383210966556176, 'reg_lambda': 1.0836081557586064, 'max_delta_step': 3}. Best is trial 3 with value: 0.458502024291498.

Best trial: 8. Best value: 0.511134:  14%|█▍        | 7/50 [01:20<05:14,  7.31s/it]

[I 2025-12-02 19:48:42,247] Trial 8 finished with value: 0.5111336032388664 and parameters: {'max_depth': 6, 'learning_rate': 0.018228992686513755, 'n_estimators': 217, 'subsample': 0.8913363381401287, 'colsample_bytree': 0.9832618341931461, 'min_child_weight': 1, 'gamma': 3.092538970522736, 'reg_alpha': 0.029153607156948612, 'reg_lambda': 0.29341630552774045, 'max_delta_step': 5}. Best is trial 8 with value: 0.5111336032388664.

Best trial: 8. Best value: 0.511134:  16%|█▌        | 8/50 [01:30<05:39,  8.09s/it]

[I 2025-12-02 19:48:52,007] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.03280821507156904, 'n_estimators': 246, 'subsample': 0.8460850216057737, 'colsample_bytree': 0.689589845714764, 'min_child_weight': 9, 'gamma': 1.705376907765923, 'reg_alpha': 0.014612959112714017, 'reg_lambda': 0.7431069210870144, 'max_delta_step': 10}. Best is trial 8 with value: 0.5111336032388664.

Best trial: 8. Best value: 0.511134:  18%|█▊        | 9/50 [01:32<04:20,  6.35s/it]

[I 2025-12-02 19:48:54,549] Trial 10 finished with value: 0.47368421052631576 and parameters: {'max_depth': 10, 'learning_rate': 0.21319280588886735, 'n_estimators': 272, 'subsample': 0.6315176531667896, 'colsample_bytree': 0.6757224998145333, 'min_child_weight': 7, 'gamma': 0.9714538737016148, 'reg_alpha': 0.003373477309864994, 'reg_lambda': 1.2894536809272944e-06, 'max_delta_step': 0}. Best is trial 8 with value: 0.5111336032388664.

Best trial: 8. Best value: 0.511134:  20%|██        | 10/50 [01:38<04:02,  6.07s/it]

[I 2025-12-02 19:48:59,989] Trial 5 finished with value: 0.3603238866396761 and parameters: {'max_depth': 8, 'learning_rate': 0.2437561003989257, 'n_estimators': 1188, 'subsample': 0.8940063283150999, 'colsample_bytree': 0.8767903093084399, 'min_child_weight': 1, 'gamma': 1.0094641441001306, 'reg_alpha': 5.056164515723492, 'reg_lambda': 4.854289909061337e-08, 'max_delta_step': 3}. Best is trial 8 with value: 0.5111336032388664.

Best trial: 8. Best value: 0.511134:  22%|██▏       | 11/50 [01:40<03:13,  4.97s/it]

[I 2025-12-02 19:49:02,456] Trial 11 pruned.

Best trial: 8. Best value: 0.511134:  24%|██▍       | 12/50 [01:52<04:32,  7.17s/it]

[I 2025-12-02 19:49:14,668] Trial 14 finished with value: 0.4271255060728745 and parameters: {'max_depth': 8, 'learning_rate': 0.010663246067670983, 'n_estimators': 265, 'subsample': 0.7500630515051157, 'colsample_bytree': 0.9965965168377946, 'min_child_weight': 3, 'gamma': 3.6149606722613, 'reg_alpha': 1.288343081478144e-07, 'reg_lambda': 1.2376050174385668e-08, 'max_delta_step': 0}. Best is trial 8 with value: 0.5111336032388664.

Best trial: 8. Best value: 0.511134:  26%|██▌       | 13/50 [01:55<03:36,  5.86s/it]

[I 2025-12-02 19:49:17,501] Trial 7 finished with value: 0.5111336032388664 and parameters: {'max_depth': 9, 'learning_rate': 0.013372195714572216, 'n_estimators': 1369, 'subsample': 0.7579777807231307, 'colsample_bytree': 0.9758388321554234, 'min_child_weight': 1, 'gamma': 1.5993680166196778, 'reg_alpha': 2.6737291129391788e-06, 'reg_lambda': 1.0280578012545818e-08, 'max_delta_step': 0}. Best is trial 8 with value: 0.5111336032388664.

Best trial: 12. Best value: 0.537449:  28%|██▊       | 14/50 [02:05<04:15,  7.10s/it]

[I 2025-12-02 19:49:27,459] Trial 12 finished with value: 0.5374493927125505 and parameters: {'max_depth': 3, 'learning_rate': 0.039894023979382985, 'n_estimators': 783, 'subsample': 0.662365318811265, 'colsample_bytree': 0.8487600826509458, 'min_child_weight': 1, 'gamma': 3.7839080968932826, 'reg_alpha': 3.918128377261611e-06, 'reg_lambda': 0.21020822914911358, 'max_delta_step': 3}. Best is trial 12 with value: 0.5374493927125505.

Best trial: 12. Best value: 0.537449:  30%|███       | 15/50 [02:12<04:07,  7.07s/it]

[I 2025-12-02 19:49:34,472] Trial 15 finished with value: 0.42004048582995945 and parameters: {'max_depth': 8, 'learning_rate': 0.03121076628756902, 'n_estimators': 457, 'subsample': 0.7575747124565297, 'colsample_bytree': 0.998138730137369, 'min_child_weight': 3, 'gamma': 2.889443888865405, 'reg_alpha': 2.459813493457449e-06, 'reg_lambda': 7.957774393998066e-05, 'max_delta_step': 6}. Best is trial 12 with value: 0.5374493927125505.

Best trial: 12. Best value: 0.537449:  32%|███▏      | 16/50 [02:13<02:57,  5.21s/it]

[I 2025-12-02 19:49:35,372] Trial 13 finished with value: 0.4271255060728745 and parameters: {'max_depth': 3, 'learning_rate': 0.010585611754638796, 'n_estimators': 864, 'subsample': 0.750142159273933, 'colsample_bytree': 0.9661115403480106, 'min_child_weight': 3, 'gamma': 3.6997735625532835, 'reg_alpha': 1.9662284549852568e-08, 'reg_lambda': 0.0017017938730368401, 'max_delta_step': 7}. Best is trial 12 with value: 0.5374493927125505.

Best trial: 12. Best value: 0.537449:  34%|███▍      | 17/50 [02:29<04:33,  8.29s/it]

[I 2025-12-02 19:49:50,805] Trial 18 pruned.

Best trial: 12. Best value: 0.537449:  36%|███▌      | 18/50 [02:36<04:11,  7.87s/it]

[I 2025-12-02 19:49:57,721] Trial 16 finished with value: 0.5303643724696356 and parameters: {'max_depth': 8, 'learning_rate': 0.0184213623880712, 'n_estimators': 936, 'subsample': 0.7732639018854401, 'colsample_bytree': 0.9934656589400044, 'min_child_weight': 2, 'gamma': 2.759113400426895, 'reg_alpha': 2.2428267248083294e-06, 'reg_lambda': 0.0005201736869718027, 'max_delta_step': 5}. Best is trial 12 with value: 0.5374493927125505.

Best trial: 12. Best value: 0.537449:  38%|███▊      | 19/50 [02:43<04:00,  7.76s/it]

[I 2025-12-02 19:50:05,202] Trial 17 finished with value: 0.42004048582995945 and parameters: {'max_depth': 8, 'learning_rate': 0.038771480299531265, 'n_estimators': 917, 'subsample': 0.7370474916450148, 'colsample_bytree': 0.9213059675853572, 'min_child_weight': 3, 'gamma': 4.23639447628657, 'reg_alpha': 1.6040919688537727e-06, 'reg_lambda': 0.00032709060710366567, 'max_delta_step': 5}. Best is trial 12 with value: 0.5374493927125505.

Best trial: 12. Best value: 0.537449:  40%|████      | 20/50 [02:54<04:19,  8.64s/it]

[I 2025-12-02 19:50:15,913] Trial 22 pruned.

Best trial: 12. Best value: 0.537449:  42%|████▏     | 21/50 [02:55<03:04,  6.35s/it]

[I 2025-12-02 19:50:16,920] Trial 19 finished with value: 0.4726720647773279 and parameters: {'max_depth': 3, 'learning_rate': 0.0183753752562731, 'n_estimators': 968, 'subsample': 0.5224618662346301, 'colsample_bytree': 0.9157989316014351, 'min_child_weight': 2, 'gamma': 4.187154685170048, 'reg_alpha': 7.362268004623412e-06, 'reg_lambda': 0.06818618312076244, 'max_delta_step': 1}. Best is trial 12 with value: 0.5374493927125505.

Best trial: 12. Best value: 0.537449:  44%|████▍     | 22/50 [03:00<02:50,  6.10s/it]

[I 2025-12-02 19:50:22,437] Trial 23 pruned.

Best trial: 12. Best value: 0.537449:  46%|████▌     | 23/50 [03:11<03:20,  7.44s/it]

[I 2025-12-02 19:50:32,995] Trial 20 finished with value: 0.4919028340080972 and parameters: {'max_depth': 3, 'learning_rate': 0.0414519909019959, 'n_estimators': 978, 'subsample': 0.8055352884906816, 'colsample_bytree': 0.800348984603027, 'min_child_weight': 2, 'gamma': 1.9209280806395914, 'reg_alpha': 3.4609175447891703e-06, 'reg_lambda': 7.300609134382757, 'max_delta_step': 2}. Best is trial 12 with value: 0.5374493927125505.

Best trial: 12. Best value: 0.537449:  48%|████▊     | 24/50 [03:18<03:13,  7.44s/it]

[I 2025-12-02 19:50:40,443] Trial 21 finished with value: 0.4726720647773279 and parameters: {'max_depth': 3, 'learning_rate': 0.04034417387789672, 'n_estimators': 1029, 'subsample': 0.5015739669224617, 'colsample_bytree': 0.7806107271880562, 'min_child_weight': 2, 'gamma': 4.326447141527231, 'reg_alpha': 2.824863037170984e-06, 'reg_lambda': 0.10217925391946232, 'max_delta_step': 5}. Best is trial 12 with value: 0.5374493927125505.

Best trial: 12. Best value: 0.537449:  50%|█████     | 25/50 [03:55<06:44, 16.18s/it]

[I 2025-12-02 19:51:17,000] Trial 24 finished with value: 0.5111336032388664 and parameters: {'max_depth': 9, 'learning_rate': 0.024862578988857256, 'n_estimators': 1490, 'subsample': 0.6742660840393049, 'colsample_bytree': 0.7953617650172337, 'min_child_weight': 2, 'gamma': 1.751427754291102, 'reg_alpha': 3.2635501342316393e-07, 'reg_lambda': 2.425543955597274e-05, 'max_delta_step': 2}. Best is trial 12 with value: 0.5374493927125505.

Best trial: 12. Best value: 0.537449:  52%|█████▏    | 26/50 [03:59<05:05, 12.71s/it]

[I 2025-12-02 19:51:21,635] Trial 25 finished with value: 0.45344129554655865 and parameters: {'max_depth': 9, 'learning_rate': 0.024878896183160075, 'n_estimators': 1430, 'subsample': 0.6911554910300683, 'colsample_bytree': 0.941737017501405, 'min_child_weight': 2, 'gamma': 1.6580353430085606, 'reg_alpha': 1.5837883742523901e-06, 'reg_lambda': 1.8588806265089976e-05, 'max_delta_step': 2}. Best is trial 12 with value: 0.5374493927125505.

Best trial: 12. Best value: 0.537449:  54%|█████▍    | 27/50 [04:06<04:08, 10.80s/it]

[I 2025-12-02 19:51:27,971] Trial 29 pruned.

Best trial: 26. Best value: 0.575911:  56%|█████▌    | 28/50 [04:11<03:21,  9.17s/it]

[I 2025-12-02 19:51:33,352] Trial 26 finished with value: 0.5759109311740891 and parameters: {'max_depth': 9, 'learning_rate': 0.023880798993313506, 'n_estimators': 1478, 'subsample': 0.9981055787779461, 'colsample_bytree': 0.9394569930050507, 'min_child_weight': 1, 'gamma': 1.5312630838368302, 'reg_alpha': 3.11048803486346e-07, 'reg_lambda': 1.546370302211839e-05, 'max_delta_step': 4}. Best is trial 26 with value: 0.5759109311740891.

Best trial: 26. Best value: 0.575911:  58%|█████▊    | 29/50 [04:15<02:39,  7.58s/it]

[I 2025-12-02 19:51:37,201] Trial 31 pruned.

Best trial: 26. Best value: 0.575911:  60%|██████    | 30/50 [04:18<02:06,  6.34s/it]

[I 2025-12-02 19:51:40,649] Trial 27 finished with value: 0.5303643724696356 and parameters: {'max_depth': 9, 'learning_rate': 0.02432536262429777, 'n_estimators': 1478, 'subsample': 0.6861794597545925, 'colsample_bytree': 0.8694460387503032, 'min_child_weight': 1, 'gamma': 1.511721605166803, 'reg_alpha': 3.033315929145068e-07, 'reg_lambda': 1.575874793996253e-05, 'max_delta_step': 4}. Best is trial 26 with value: 0.5759109311740891.

Best trial: 26. Best value: 0.575911:  62%|██████▏   | 31/50 [04:25<02:03,  6.52s/it]

[I 2025-12-02 19:51:47,609] Trial 33 pruned.

Best trial: 26. Best value: 0.575911:  64%|██████▍   | 32/50 [04:28<01:34,  5.26s/it]

[I 2025-12-02 19:51:49,924] Trial 28 finished with value: 0.5445344129554656 and parameters: {'max_depth': 9, 'learning_rate': 0.013417041473201632, 'n_estimators': 753, 'subsample': 0.6876004350306425, 'colsample_bytree': 0.9514264870267268, 'min_child_weight': 1, 'gamma': 2.574810115020475, 'reg_alpha': 0.0005653168723604871, 'reg_lambda': 4.045588415547014e-07, 'max_delta_step': 4}. Best is trial 26 with value: 0.5759109311740891.

Best trial: 26. Best value: 0.575911:  66%|██████▌   | 33/50 [04:29<01:08,  4.06s/it]

[I 2025-12-02 19:51:51,169] Trial 30 finished with value: 0.5303643724696356 and parameters: {'max_depth': 7, 'learning_rate': 0.01350970011758014, 'n_estimators': 532, 'subsample': 0.6521394086392223, 'colsample_bytree': 0.7350158583057304, 'min_child_weight': 1, 'gamma': 2.804476539640483, 'reg_alpha': 0.0002503750660777, 'reg_lambda': 0.002131746698865625, 'max_delta_step': 6}. Best is trial 26 with value: 0.5759109311740891.

Best trial: 26. Best value: 0.575911:  68%|██████▊   | 34/50 [04:30<00:48,  3.03s/it]

[I 2025-12-02 19:51:51,815] Trial 32 pruned.

Best trial: 26. Best value: 0.575911:  70%|███████   | 35/50 [04:52<02:10,  8.73s/it]

[I 2025-12-02 19:52:13,833] Trial 35 finished with value: 0.4919028340080972 and parameters: {'max_depth': 8, 'learning_rate': 0.014420268098830428, 'n_estimators': 543, 'subsample': 0.6561291166479607, 'colsample_bytree': 0.9495011128125143, 'min_child_weight': 1, 'gamma': 2.082111469597493, 'reg_alpha': 0.00035127067475026927, 'reg_lambda': 7.430682668348492e-07, 'max_delta_step': 5}. Best is trial 26 with value: 0.5759109311740891.

Best trial: 26. Best value: 0.575911:  72%|███████▏  | 36/50 [04:54<01:33,  6.71s/it]

[I 2025-12-02 19:52:15,828] Trial 37 finished with value: 0.4848178137651822 and parameters: {'max_depth': 8, 'learning_rate': 0.02062473215126512, 'n_estimators': 576, 'subsample': 0.7152234303745505, 'colsample_bytree': 0.9543819580148306, 'min_child_weight': 2, 'gamma': 2.1567534328697984, 'reg_alpha': 0.0016669871615223434, 'reg_lambda': 8.35450532163502e-07, 'max_delta_step': 3}. Best is trial 26 with value: 0.5759109311740891.

Best trial: 26. Best value: 0.575911:  74%|███████▍  | 37/50 [04:58<01:19,  6.11s/it]

[I 2025-12-02 19:52:20,536] Trial 38 pruned.

Best trial: 26. Best value: 0.575911:  76%|███████▌  | 38/50 [05:01<01:02,  5.22s/it]

[I 2025-12-02 19:52:23,685] Trial 36 finished with value: 0.4989878542510121 and parameters: {'max_depth': 8, 'learning_rate': 0.01957937362727259, 'n_estimators': 767, 'subsample': 0.5770120670564003, 'colsample_bytree': 0.9445007625853369, 'min_child_weight': 1, 'gamma': 2.2566506332928133, 'reg_alpha': 0.0019167263909592603, 'reg_lambda': 4.6475349180019037e-07, 'max_delta_step': 3}. Best is trial 26 with value: 0.5759109311740891.

Best trial: 26. Best value: 0.575911:  78%|███████▊  | 39/50 [05:13<01:17,  7.05s/it]

[I 2025-12-02 19:52:35,001] Trial 41 pruned.

Best trial: 26. Best value: 0.575911:  80%|████████  | 40/50 [05:20<01:09,  6.99s/it]

[I 2025-12-02 19:52:41,852] Trial 34 finished with value: 0.5445344129554656 and parameters: {'max_depth': 9, 'learning_rate': 0.023018383895078272, 'n_estimators': 1322, 'subsample': 0.5837515601167079, 'colsample_bytree': 0.8399628051252988, 'min_child_weight': 1, 'gamma': 0.4711990159030739, 'reg_alpha': 6.096772522233528e-07, 'reg_lambda': 8.374954276190674e-07, 'max_delta_step': 4}. Best is trial 26 with value: 0.5759109311740891.

Best trial: 26. Best value: 0.575911:  82%|████████▏ | 41/50 [05:25<00:59,  6.56s/it]

[I 2025-12-02 19:52:47,414] Trial 42 pruned.

Best trial: 26. Best value: 0.575911:  84%|████████▍ | 42/50 [05:40<01:11,  8.88s/it]

[I 2025-12-02 19:53:01,709] Trial 39 finished with value: 0.5182186234817814 and parameters: {'max_depth': 10, 'learning_rate': 0.03174040428470996, 'n_estimators': 1100, 'subsample': 0.5613998134439208, 'colsample_bytree': 0.9028487956088532, 'min_child_weight': 1, 'gamma': 0.5080193679755429, 'reg_alpha': 1.2272097754325576e-05, 'reg_lambda': 4.432635988184317e-06, 'max_delta_step': 7}. Best is trial 26 with value: 0.5759109311740891.

Best trial: 26. Best value: 0.575911:  86%|████████▌ | 43/50 [05:50<01:04,  9.26s/it]

[I 2025-12-02 19:53:11,859] Trial 44 pruned.

Best trial: 26. Best value: 0.575911:  88%|████████▊ | 44/50 [05:51<00:41,  6.90s/it]

[I 2025-12-02 19:53:13,225] Trial 40 finished with value: 0.5374493927125505 and parameters: {'max_depth': 6, 'learning_rate': 0.08307615488885285, 'n_estimators': 1303, 'subsample': 0.8550808821058592, 'colsample_bytree': 0.5736002629276007, 'min_child_weight': 1, 'gamma': 3.183500175570063, 'reg_alpha': 6.14181439996574e-05, 'reg_lambda': 1.715532075407065e-07, 'max_delta_step': 7}. Best is trial 26 with value: 0.5759109311740891.

Best trial: 26. Best value: 0.575911:  90%|█████████ | 45/50 [06:02<00:41,  8.21s/it]

[I 2025-12-02 19:53:24,523] Trial 47 pruned.

Best trial: 26. Best value: 0.575911:  92%|█████████▏| 46/50 [06:14<00:37,  9.34s/it]

[I 2025-12-02 19:53:36,477] Trial 43 finished with value: 0.5253036437246963 and parameters: {'max_depth': 5, 'learning_rate': 0.03281771612307179, 'n_estimators': 1316, 'subsample': 0.540686265569567, 'colsample_bytree': 0.8350865228478105, 'min_child_weight': 1, 'gamma': 0.236237574368108, 'reg_alpha': 9.545390875552597e-06, 'reg_lambda': 2.971471029261586e-06, 'max_delta_step': 4}. Best is trial 26 with value: 0.5759109311740891.

Best trial: 26. Best value: 0.575911:  94%|█████████▍| 47/50 [06:15<00:20,  6.78s/it]

[I 2025-12-02 19:53:37,296] Trial 48 pruned.

Best trial: 26. Best value: 0.575911:  96%|█████████▌| 48/50 [06:30<00:18,  9.12s/it]

[I 2025-12-02 19:53:51,888] Trial 49 pruned.

Best trial: 26. Best value: 0.575911:  98%|█████████▊| 49/50 [06:30<00:06,  6.59s/it]

[I 2025-12-02 19:53:52,568] Trial 45 finished with value: 0.5040485829959513 and parameters: {'max_depth': 9, 'learning_rate': 0.012160607335288622, 'n_estimators': 1322, 'subsample': 0.6010865466260531, 'colsample_bytree': 0.8196850319470247, 'min_child_weight': 1, 'gamma': 1.2788893469138558, 'reg_alpha': 6.75940714692172e-08, 'reg_lambda': 4.941537526439507e-08, 'max_delta_step': 4}. Best is trial 26 with value: 0.5759109311740891.

Best trial: 26. Best value: 0.575911: 100%|██████████| 50/50 [06:33<00:00,  7.87s/it]

[I 2025-12-02 19:53:55,092] Trial 46 finished with value: 0.5759109311740891 and parameters: {'max_depth': 9, 'learning_rate': 0.04906689382603011, 'n_estimators': 1330, 'subsample': 0.9599995921628548, 'colsample_bytree': 0.9313819849785002, 'min_child_weight': 1, 'gamma': 1.2621455608692882, 'reg_alpha': 8.746669775880476e-05, 'reg_lambda': 9.631657033643342e-08, 'max_delta_step': 4}. Best is trial 26 with value: 0.5759109311740891.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.575911                0.414286      0.571429

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.169031          0.428571               0.4        50          45

   test_size
0         12
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.575911                0.414286      0.571429

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.169031          0.428571               0.4        50          45

   test_size
0         12

## MCI-PD vs HC -> OPTUNA + XGB

In [ ]:
datasets = task_hf_compensated_comb_emb_lbl_pd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_pd_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_handcrafted_comb_emb_pd_hc_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param= "diagnosis_y",
)
print(summary)

[I 2025-12-02 19:54:00,068] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 0. Best value: 0.730424:   2%|▏         | 1/50 [01:06<54:35, 66.85s/it]

[I 2025-12-02 19:55:06,909] Trial 0 finished with value: 0.730423620025674 and parameters: {'max_depth': 7, 'learning_rate': 0.010168468297759855, 'n_estimators': 344, 'subsample': 0.7269661604242821, 'colsample_bytree': 0.8397591416335008, 'min_child_weight': 4, 'gamma': 1.956802553162692, 'reg_alpha': 0.0011562350093180505, 'reg_lambda': 6.228191985671175, 'max_delta_step': 8}. Best is trial 0 with value: 0.730423620025674.

Best trial: 0. Best value: 0.730424:   4%|▍         | 2/50 [01:30<32:59, 41.23s/it]

[I 2025-12-02 19:55:30,212] Trial 2 finished with value: 0.730423620025674 and parameters: {'max_depth': 7, 'learning_rate': 0.07893789954546362, 'n_estimators': 1383, 'subsample': 0.8496419062489275, 'colsample_bytree': 0.516133923701825, 'min_child_weight': 9, 'gamma': 0.40181530407410626, 'reg_alpha': 0.024686250120272382, 'reg_lambda': 0.6209782645749294, 'max_delta_step': 1}. Best is trial 0 with value: 0.730423620025674.

Best trial: 3. Best value: 0.742619:   6%|▌         | 3/50 [01:33<18:52, 24.11s/it]

[I 2025-12-02 19:55:33,937] Trial 3 finished with value: 0.7426187419768935 and parameters: {'max_depth': 4, 'learning_rate': 0.0312527018757423, 'n_estimators': 771, 'subsample': 0.8441275903193628, 'colsample_bytree': 0.7537366411683537, 'min_child_weight': 2, 'gamma': 0.2550035704471121, 'reg_alpha': 4.0512708300328967e-05, 'reg_lambda': 0.005051664408781142, 'max_delta_step': 2}. Best is trial 3 with value: 0.7426187419768935.

Best trial: 1. Best value: 0.79525:   8%|▊         | 4/50 [01:50<16:19, 21.30s/it]

[I 2025-12-02 19:55:50,941] Trial 1 finished with value: 0.7952503209242618 and parameters: {'max_depth': 9, 'learning_rate': 0.16526506614998338, 'n_estimators': 1080, 'subsample': 0.5801535167573268, 'colsample_bytree': 0.5579627183712201, 'min_child_weight': 2, 'gamma': 0.3385839725214912, 'reg_alpha': 6.848951092877586, 'reg_lambda': 0.001092729401644146, 'max_delta_step': 3}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  10%|█         | 5/50 [02:01<12:59, 17.32s/it]

[I 2025-12-02 19:56:01,204] Trial 6 finished with value: 0.6534017971758665 and parameters: {'max_depth': 7, 'learning_rate': 0.20932025555962533, 'n_estimators': 304, 'subsample': 0.7800722223744853, 'colsample_bytree': 0.557958450602506, 'min_child_weight': 4, 'gamma': 2.7874127339156916, 'reg_alpha': 0.062150208849709725, 'reg_lambda': 4.805891395553767e-06, 'max_delta_step': 4}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  12%|█▏        | 6/50 [02:28<15:09, 20.67s/it]

[I 2025-12-02 19:56:28,385] Trial 4 finished with value: 0.7426187419768935 and parameters: {'max_depth': 5, 'learning_rate': 0.03279390741603807, 'n_estimators': 870, 'subsample': 0.880635848960751, 'colsample_bytree': 0.7602134207476873, 'min_child_weight': 4, 'gamma': 2.4118758758963175, 'reg_alpha': 3.009817555296956e-05, 'reg_lambda': 1.3479916138957672e-06, 'max_delta_step': 8}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  14%|█▍        | 7/50 [02:37<12:03, 16.83s/it]

[I 2025-12-02 19:56:37,287] Trial 5 finished with value: 0.6675224646983312 and parameters: {'max_depth': 4, 'learning_rate': 0.012146759133269174, 'n_estimators': 909, 'subsample': 0.8379180060085369, 'colsample_bytree': 0.5242326936440556, 'min_child_weight': 9, 'gamma': 2.7390180084618256, 'reg_alpha': 0.00022857362782635515, 'reg_lambda': 1.4051283182831435e-05, 'max_delta_step': 10}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  16%|█▌        | 8/50 [02:42<09:13, 13.18s/it]

[I 2025-12-02 19:56:42,654] Trial 8 finished with value: 0.7182284980744544 and parameters: {'max_depth': 9, 'learning_rate': 0.05442446113032311, 'n_estimators': 206, 'subsample': 0.9293377661502393, 'colsample_bytree': 0.6193479620561617, 'min_child_weight': 1, 'gamma': 1.4697123402311973, 'reg_alpha': 0.01538512353379408, 'reg_lambda': 0.0012728727364887157, 'max_delta_step': 6}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  18%|█▊        | 9/50 [03:24<15:11, 22.22s/it]

[I 2025-12-02 19:57:24,772] Trial 9 finished with value: 0.6797175866495507 and parameters: {'max_depth': 3, 'learning_rate': 0.06988726490357311, 'n_estimators': 764, 'subsample': 0.5697735737231961, 'colsample_bytree': 0.7722007294191913, 'min_child_weight': 7, 'gamma': 0.5637305390490649, 'reg_alpha': 0.8452019429271436, 'reg_lambda': 0.007641878873618119, 'max_delta_step': 5}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  20%|██        | 10/50 [03:59<17:22, 26.07s/it]

[I 2025-12-02 19:57:59,438] Trial 10 finished with value: 0.42105263157894735 and parameters: {'max_depth': 5, 'learning_rate': 0.01235177799820197, 'n_estimators': 1108, 'subsample': 0.50622169660821, 'colsample_bytree': 0.8258187139520949, 'min_child_weight': 7, 'gamma': 3.705175126555331, 'reg_alpha': 1.8209556663108676e-05, 'reg_lambda': 0.7976926985014958, 'max_delta_step': 3}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  22%|██▏       | 11/50 [04:00<11:54, 18.33s/it]

[I 2025-12-02 19:58:00,232] Trial 7 finished with value: 0.7933247753530167 and parameters: {'max_depth': 10, 'learning_rate': 0.07092939124980471, 'n_estimators': 1360, 'subsample': 0.555862435847269, 'colsample_bytree': 0.9963699032139592, 'min_child_weight': 2, 'gamma': 2.7464827368071276, 'reg_alpha': 1.464987164031962, 'reg_lambda': 0.0002181303018244872, 'max_delta_step': 3}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  24%|██▍       | 12/50 [04:17<11:22, 17.96s/it]

[I 2025-12-02 19:58:17,353] Trial 11 finished with value: 0.730423620025674 and parameters: {'max_depth': 10, 'learning_rate': 0.016760245671082443, 'n_estimators': 1262, 'subsample': 0.8752872413938275, 'colsample_bytree': 0.6476468300337934, 'min_child_weight': 8, 'gamma': 0.1189185324122305, 'reg_alpha': 0.006983215249737552, 'reg_lambda': 5.625433072026801e-08, 'max_delta_step': 5}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  26%|██▌       | 13/50 [04:22<08:46, 14.22s/it]

[I 2025-12-02 19:58:22,952] Trial 12 finished with value: 0.730423620025674 and parameters: {'max_depth': 7, 'learning_rate': 0.015331991411191896, 'n_estimators': 624, 'subsample': 0.7805527044755678, 'colsample_bytree': 0.582729111666208, 'min_child_weight': 7, 'gamma': 3.1854812432388817, 'reg_alpha': 1.4085391702814587, 'reg_lambda': 2.3159713887822915, 'max_delta_step': 4}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  28%|██▊       | 14/50 [04:31<07:25, 12.39s/it]

[I 2025-12-02 19:58:31,101] Trial 14 pruned.

Best trial: 1. Best value: 0.79525:  30%|███       | 15/50 [04:39<06:27, 11.08s/it]

[I 2025-12-02 19:58:39,170] Trial 16 pruned.

Best trial: 1. Best value: 0.79525:  32%|███▏      | 16/50 [04:40<04:38,  8.20s/it]

[I 2025-12-02 19:58:40,655] Trial 15 pruned.

Best trial: 1. Best value: 0.79525:  34%|███▍      | 17/50 [05:57<15:52, 28.87s/it]

[I 2025-12-02 19:59:57,618] Trial 13 finished with value: 0.730423620025674 and parameters: {'max_depth': 10, 'learning_rate': 0.2745620142263597, 'n_estimators': 1457, 'subsample': 0.6415234480784513, 'colsample_bytree': 0.9900759980863469, 'min_child_weight': 2, 'gamma': 4.678069808469358, 'reg_alpha': 3.4410328205103907e-08, 'reg_lambda': 1.053301185057528e-08, 'max_delta_step': 0}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  36%|███▌      | 18/50 [06:06<12:15, 22.98s/it]

[I 2025-12-02 20:00:06,874] Trial 17 finished with value: 0.7426187419768935 and parameters: {'max_depth': 9, 'learning_rate': 0.14251915710812343, 'n_estimators': 1116, 'subsample': 0.6356245258429698, 'colsample_bytree': 0.9645665767654857, 'min_child_weight': 1, 'gamma': 1.3769404310616111, 'reg_alpha': 1.0636256002118374e-06, 'reg_lambda': 0.00011910047281856992, 'max_delta_step': 2}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  38%|███▊      | 19/50 [06:09<08:43, 16.89s/it]

[I 2025-12-02 20:00:09,591] Trial 18 finished with value: 0.7708600770218228 and parameters: {'max_depth': 9, 'learning_rate': 0.126179817947884, 'n_estimators': 1147, 'subsample': 0.5017256073336444, 'colsample_bytree': 0.8719370490518197, 'min_child_weight': 5, 'gamma': 1.3849884634347447, 'reg_alpha': 7.463129716375108, 'reg_lambda': 0.04790604986874785, 'max_delta_step': 2}. Best is trial 1 with value: 0.7952503209242618.
[I 2025-12-02 20:00:09,674] Trial 19 finished with value: 0.7445442875481387 and parameters: {'max_depth': 8, 'learning_rate': 0.11319539695997256, 'n_estimators': 1282, 'subsample': 0.5396571284498889, 'colsample_bytree': 0.6684917396693512, 'min_child_weight': 5, 'gamma': 1.203437110460559, 'reg_alpha': 0.3995411203839614, 'reg_lambda': 0.017189216150732295, 'max_delta_step': 2}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  42%|████▏     | 21/50 [07:20<12:21, 25.57s/it]

[I 2025-12-02 20:01:20,966] Trial 20 finished with value: 0.7952503209242618 and parameters: {'max_depth': 8, 'learning_rate': 0.12838302244551905, 'n_estimators': 1273, 'subsample': 0.5043862179813977, 'colsample_bytree': 0.6730048440424649, 'min_child_weight': 5, 'gamma': 1.2898160062093451, 'reg_alpha': 0.20246476567739108, 'reg_lambda': 0.07332736363591699, 'max_delta_step': 2}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  44%|████▍     | 22/50 [07:24<09:26, 20.24s/it]

[I 2025-12-02 20:01:25,041] Trial 23 finished with value: 0.754813863928113 and parameters: {'max_depth': 8, 'learning_rate': 0.04200743713763683, 'n_estimators': 981, 'subsample': 0.5893209732851464, 'colsample_bytree': 0.6940232849160134, 'min_child_weight': 3, 'gamma': 3.891732777038126, 'reg_alpha': 0.09581148597142611, 'reg_lambda': 0.10363405242378984, 'max_delta_step': 7}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  46%|████▌     | 23/50 [07:29<07:12, 16.03s/it]

[I 2025-12-02 20:01:29,178] Trial 21 finished with value: 0.7830551989730423 and parameters: {'max_depth': 8, 'learning_rate': 0.12130029605785388, 'n_estimators': 1268, 'subsample': 0.5096934046611727, 'colsample_bytree': 0.6835706316872594, 'min_child_weight': 5, 'gamma': 3.7760349843887493, 'reg_alpha': 0.34547461900449095, 'reg_lambda': 0.0815036895997579, 'max_delta_step': 3}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  48%|████▊     | 24/50 [07:39<06:13, 14.38s/it]

[I 2025-12-02 20:01:39,151] Trial 22 finished with value: 0.7567394094993581 and parameters: {'max_depth': 8, 'learning_rate': 0.09187177852054786, 'n_estimators': 1296, 'subsample': 0.5656984765253714, 'colsample_bytree': 0.6902807528419156, 'min_child_weight': 3, 'gamma': 3.766304633167758, 'reg_alpha': 0.20443556051508158, 'reg_lambda': 0.07847747945214861, 'max_delta_step': 6}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  50%|█████     | 25/50 [07:52<05:50, 14.03s/it]

[I 2025-12-02 20:01:52,282] Trial 27 pruned.

Best trial: 1. Best value: 0.79525:  52%|█████▏    | 26/50 [08:05<05:33, 13.91s/it]

[I 2025-12-02 20:02:05,907] Trial 28 pruned.

Best trial: 1. Best value: 0.79525:  54%|█████▍    | 27/50 [08:50<08:46, 22.88s/it]

[I 2025-12-02 20:02:50,746] Trial 24 finished with value: 0.7811296534017972 and parameters: {'max_depth': 8, 'learning_rate': 0.09037653468026277, 'n_estimators': 1285, 'subsample': 0.5888081506091069, 'colsample_bytree': 0.6924454195266082, 'min_child_weight': 3, 'gamma': 0.8929764206240285, 'reg_alpha': 0.1451632348684511, 'reg_lambda': 0.11309350677598537, 'max_delta_step': 3}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  56%|█████▌    | 28/50 [08:53<06:15, 17.07s/it]

[I 2025-12-02 20:02:53,795] Trial 25 finished with value: 0.7811296534017972 and parameters: {'max_depth': 8, 'learning_rate': 0.09300068816092223, 'n_estimators': 1298, 'subsample': 0.5806998594808869, 'colsample_bytree': 0.5961426945926938, 'min_child_weight': 3, 'gamma': 0.7784280515980629, 'reg_alpha': 0.5454036520265636, 'reg_lambda': 0.0012289897431355936, 'max_delta_step': 3}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 1. Best value: 0.79525:  58%|█████▊    | 29/50 [09:10<05:54, 16.86s/it]

[I 2025-12-02 20:03:10,142] Trial 26 finished with value: 0.7670089858793325 and parameters: {'max_depth': 10, 'learning_rate': 0.08551895352049667, 'n_estimators': 1340, 'subsample': 0.5834298159497239, 'colsample_bytree': 0.9224372679168902, 'min_child_weight': 3, 'gamma': 0.8266763659877506, 'reg_alpha': 0.0034038901473461575, 'reg_lambda': 0.0016455461287116376, 'max_delta_step': 4}. Best is trial 1 with value: 0.7952503209242618.

Best trial: 29. Best value: 0.819641:  60%|██████    | 30/50 [09:47<07:36, 22.81s/it]

[I 2025-12-02 20:03:47,072] Trial 29 finished with value: 0.8196405648267009 and parameters: {'max_depth': 10, 'learning_rate': 0.09626660161652056, 'n_estimators': 1399, 'subsample': 0.5447518233344585, 'colsample_bytree': 0.6138954850283956, 'min_child_weight': 3, 'gamma': 0.7311979167997129, 'reg_alpha': 2.143738991260338, 'reg_lambda': 2.0460115998401152e-05, 'max_delta_step': 1}. Best is trial 29 with value: 0.8196405648267009.

Best trial: 29. Best value: 0.819641:  62%|██████▏   | 31/50 [09:54<05:44, 18.13s/it]

[I 2025-12-02 20:03:54,146] Trial 33 pruned.

Best trial: 29. Best value: 0.819641:  64%|██████▍   | 32/50 [10:44<08:19, 27.74s/it]

[I 2025-12-02 20:04:44,497] Trial 30 finished with value: 0.7426187419768935 and parameters: {'max_depth': 10, 'learning_rate': 0.16698484324387736, 'n_estimators': 1197, 'subsample': 0.5451296740948821, 'colsample_bytree': 0.6245813532590632, 'min_child_weight': 1, 'gamma': 2.18658595736921, 'reg_alpha': 2.1830076033592722, 'reg_lambda': 2.1599056924121047e-05, 'max_delta_step': 1}. Best is trial 29 with value: 0.8196405648267009.

Best trial: 29. Best value: 0.819641:  66%|██████▌   | 33/50 [10:59<06:47, 24.00s/it]

[I 2025-12-02 20:04:59,710] Trial 35 pruned.

Best trial: 29. Best value: 0.819641:  68%|██████▊   | 34/50 [11:06<04:59, 18.73s/it]

[I 2025-12-02 20:05:06,115] Trial 32 finished with value: 0.7670089858793325 and parameters: {'max_depth': 9, 'learning_rate': 0.04580646743763296, 'n_estimators': 988, 'subsample': 0.7057004810859682, 'colsample_bytree': 0.8065988267844932, 'min_child_weight': 1, 'gamma': 1.917530009109489, 'reg_alpha': 0.00046891931487753034, 'reg_lambda': 1.085083576424498e-06, 'max_delta_step': 1}. Best is trial 29 with value: 0.8196405648267009.

Best trial: 29. Best value: 0.819641:  70%|███████   | 35/50 [11:06<03:18, 13.25s/it]

[I 2025-12-02 20:05:06,523] Trial 31 finished with value: 0.7933247753530167 and parameters: {'max_depth': 10, 'learning_rate': 0.16086334733482452, 'n_estimators': 1402, 'subsample': 0.534559089492872, 'colsample_bytree': 0.6308026239212849, 'min_child_weight': 1, 'gamma': 1.8711256669363827, 'reg_alpha': 2.460928787698909, 'reg_lambda': 1.650237536841471e-05, 'max_delta_step': 1}. Best is trial 29 with value: 0.8196405648267009.

Best trial: 29. Best value: 0.819641:  72%|███████▏  | 36/50 [11:19<03:06, 13.32s/it]

[I 2025-12-02 20:05:20,010] Trial 38 pruned.

Best trial: 29. Best value: 0.819641:  74%|███████▍  | 37/50 [12:03<04:52, 22.51s/it]

[I 2025-12-02 20:06:03,990] Trial 34 finished with value: 0.7670089858793325 and parameters: {'max_depth': 10, 'learning_rate': 0.10876969203782477, 'n_estimators': 1184, 'subsample': 0.5381638393624972, 'colsample_bytree': 0.7256667439543908, 'min_child_weight': 1, 'gamma': 1.6694761147653172, 'reg_alpha': 2.688562154393827, 'reg_lambda': 9.1998877272436e-06, 'max_delta_step': 1}. Best is trial 29 with value: 0.8196405648267009.

Best trial: 29. Best value: 0.819641:  76%|███████▌  | 38/50 [12:38<05:11, 25.98s/it]

[I 2025-12-02 20:06:38,078] Trial 36 finished with value: 0.7952503209242618 and parameters: {'max_depth': 10, 'learning_rate': 0.04648170381146604, 'n_estimators': 1384, 'subsample': 0.5330247909827707, 'colsample_bytree': 0.7216343452332417, 'min_child_weight': 4, 'gamma': 0.4774240023636762, 'reg_alpha': 0.0004307965609488187, 'reg_lambda': 1.779100393760843e-06, 'max_delta_step': 2}. Best is trial 29 with value: 0.8196405648267009.

Best trial: 29. Best value: 0.819641:  78%|███████▊  | 39/50 [12:44<03:42, 20.20s/it]

[I 2025-12-02 20:06:44,794] Trial 37 finished with value: 0.7689345314505777 and parameters: {'max_depth': 10, 'learning_rate': 0.1026795324998148, 'n_estimators': 1385, 'subsample': 0.5365042043388215, 'colsample_bytree': 0.7229486082544854, 'min_child_weight': 4, 'gamma': 0.5085208888658798, 'reg_alpha': 0.060125722067328545, 'reg_lambda': 7.330788297632016, 'max_delta_step': 2}. Best is trial 29 with value: 0.8196405648267009.

Best trial: 29. Best value: 0.819641:  80%|████████  | 40/50 [12:54<02:51, 17.16s/it]

[I 2025-12-02 20:06:54,841] Trial 39 finished with value: 0.7567394094993581 and parameters: {'max_depth': 7, 'learning_rate': 0.23538780486567057, 'n_estimators': 1478, 'subsample': 0.5381153164378577, 'colsample_bytree': 0.5016988910471945, 'min_child_weight': 2, 'gamma': 3.1039248816007143, 'reg_alpha': 0.07301886540394892, 'reg_lambda': 3.225093171478074e-06, 'max_delta_step': 2}. Best is trial 29 with value: 0.8196405648267009.

Best trial: 29. Best value: 0.819641:  82%|████████▏ | 41/50 [13:56<04:35, 30.56s/it]

[I 2025-12-02 20:07:56,673] Trial 40 finished with value: 0.7811296534017972 and parameters: {'max_depth': 7, 'learning_rate': 0.07433357084028641, 'n_estimators': 1492, 'subsample': 0.618734454384334, 'colsample_bytree': 0.5413823449220803, 'min_child_weight': 3, 'gamma': 2.60526618199514, 'reg_alpha': 0.09043955657788148, 'reg_lambda': 7.0157325096424525, 'max_delta_step': 10}. Best is trial 29 with value: 0.8196405648267009.

Best trial: 29. Best value: 0.819641:  84%|████████▍ | 42/50 [14:16<03:39, 27.41s/it]

[I 2025-12-02 20:08:16,751] Trial 43 finished with value: 0.7811296534017972 and parameters: {'max_depth': 9, 'learning_rate': 0.0274751855205718, 'n_estimators': 1067, 'subsample': 0.6190362838103484, 'colsample_bytree': 0.7792242501876079, 'min_child_weight': 5, 'gamma': 1.1980485560964849, 'reg_alpha': 1.478491976033018e-06, 'reg_lambda': 6.80100465795559e-07, 'max_delta_step': 9}. Best is trial 29 with value: 0.8196405648267009.

Best trial: 29. Best value: 0.819641:  86%|████████▌ | 43/50 [14:20<02:21, 20.23s/it]

[I 2025-12-02 20:08:20,200] Trial 41 finished with value: 0.7811296534017972 and parameters: {'max_depth': 7, 'learning_rate': 0.02617300574093666, 'n_estimators': 1494, 'subsample': 0.6110430179727252, 'colsample_bytree': 0.5135834879971143, 'min_child_weight': 5, 'gamma': 0.3812701644230527, 'reg_alpha': 5.031307111589358e-06, 'reg_lambda': 2.1965371178518702e-07, 'max_delta_step': 2}. Best is trial 29 with value: 0.8196405648267009.

Best trial: 29. Best value: 0.819641:  88%|████████▊ | 44/50 [14:24<01:32, 15.37s/it]

[I 2025-12-02 20:08:24,246] Trial 42 finished with value: 0.7811296534017972 and parameters: {'max_depth': 7, 'learning_rate': 0.0283883120821706, 'n_estimators': 1468, 'subsample': 0.6177273865615156, 'colsample_bytree': 0.5098445454525495, 'min_child_weight': 5, 'gamma': 1.1327421481775382, 'reg_alpha': 0.00010425770120787666, 'reg_lambda': 3.221947431042155e-07, 'max_delta_step': 9}. Best is trial 29 with value: 0.8196405648267009.

Best trial: 29. Best value: 0.819641:  90%|█████████ | 45/50 [15:18<02:15, 27.01s/it]

[I 2025-12-02 20:09:18,416] Trial 44 finished with value: 0.7933247753530167 and parameters: {'max_depth': 9, 'learning_rate': 0.026531038970447247, 'n_estimators': 1052, 'subsample': 0.5568717986405625, 'colsample_bytree': 0.7785513795833029, 'min_child_weight': 5, 'gamma': 1.136699104050457, 'reg_alpha': 1.0828798178999602e-05, 'reg_lambda': 2.4735170998083954e-07, 'max_delta_step': 4}. Best is trial 29 with value: 0.8196405648267009.

Best trial: 29. Best value: 0.819641:  92%|█████████▏| 46/50 [15:27<01:26, 21.55s/it]

[I 2025-12-02 20:09:27,222] Trial 47 finished with value: 0.7811296534017972 and parameters: {'max_depth': 10, 'learning_rate': 0.04899087437039601, 'n_estimators': 808, 'subsample': 0.5603439841607276, 'colsample_bytree': 0.6583507395548894, 'min_child_weight': 4, 'gamma': 0.2867903311920476, 'reg_alpha': 0.8240207844021018, 'reg_lambda': 0.007934901172406054, 'max_delta_step': 5}. Best is trial 29 with value: 0.8196405648267009.

Best trial: 29. Best value: 0.819641:  94%|█████████▍| 47/50 [15:54<01:09, 23.27s/it]

[I 2025-12-02 20:09:54,499] Trial 45 finished with value: 0.8074454428754814 and parameters: {'max_depth': 10, 'learning_rate': 0.03701936050653281, 'n_estimators': 1358, 'subsample': 0.5645923446811425, 'colsample_bytree': 0.6534121867494078, 'min_child_weight': 4, 'gamma': 0.2707746060586048, 'reg_alpha': 8.295260139793596e-05, 'reg_lambda': 1.837268515119276e-07, 'max_delta_step': 4}. Best is trial 29 with value: 0.8196405648267009.

Best trial: 29. Best value: 0.819641:  96%|█████████▌| 48/50 [15:55<00:32, 16.49s/it]

[I 2025-12-02 20:09:55,173] Trial 46 finished with value: 0.7689345314505777 and parameters: {'max_depth': 10, 'learning_rate': 0.04861541132395817, 'n_estimators': 1340, 'subsample': 0.5614711127244072, 'colsample_bytree': 0.6513127840185942, 'min_child_weight': 4, 'gamma': 0.03617699225997595, 'reg_alpha': 0.0001782271036389851, 'reg_lambda': 4.37303244521198e-05, 'max_delta_step': 3}. Best is trial 29 with value: 0.8196405648267009.

Best trial: 29. Best value: 0.819641:  98%|█████████▊| 49/50 [16:33<00:23, 23.11s/it]

[I 2025-12-02 20:10:33,755] Trial 48 finished with value: 0.7933247753530167 and parameters: {'max_depth': 10, 'learning_rate': 0.05151806185266735, 'n_estimators': 1351, 'subsample': 0.5121740177981238, 'colsample_bytree': 0.6569929938240785, 'min_child_weight': 4, 'gamma': 0.024703249016232443, 'reg_alpha': 0.823927813147216, 'reg_lambda': 0.004486232519456545, 'max_delta_step': 3}. Best is trial 29 with value: 0.8196405648267009.

Best trial: 29. Best value: 0.819641: 100%|██████████| 50/50 [16:35<00:00, 19.91s/it]

[I 2025-12-02 20:10:35,666] Trial 49 finished with value: 0.7933247753530167 and parameters: {'max_depth': 10, 'learning_rate': 0.03323662713893254, 'n_estimators': 1225, 'subsample': 0.6696321894949934, 'colsample_bytree': 0.5956618033116357, 'min_child_weight': 4, 'gamma': 2.2677099787351964, 'reg_alpha': 0.008517802259723314, 'reg_lambda': 3.5373728183513273e-06, 'max_delta_step': 3}. Best is trial 29 with value: 0.8196405648267009.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.819641                     0.4          0.42

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.188982               0.4               0.4        50          60

   test_size
0         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.819641                     0.4          0.42

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.188982               0.4               0.4        50          60

   test_size
0         15

In [ ]:

datasets = task_hf_compensated_temp_emb_lbl_pd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_pd_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_handcrafted_temp_emb_pd_hc_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param= "diagnosis_y",
)
print(summary)

[I 2025-12-02 20:10:41,854] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.732349:   2%|▏         | 1/50 [00:22<18:37, 22.81s/it]

[I 2025-12-02 20:11:04,663] Trial 3 finished with value: 0.7323491655969192 and parameters: {'max_depth': 7, 'learning_rate': 0.018033194252183832, 'n_estimators': 331, 'subsample': 0.6495170945751083, 'colsample_bytree': 0.621592077562443, 'min_child_weight': 5, 'gamma': 4.709651453584471, 'reg_alpha': 2.3592770298594967e-05, 'reg_lambda': 1.1689853273998144e-08, 'max_delta_step': 8}. Best is trial 3 with value: 0.7323491655969192.

Best trial: 3. Best value: 0.732349:   4%|▍         | 2/50 [00:34<13:04, 16.34s/it]

[I 2025-12-02 20:11:16,462] Trial 0 finished with value: 0.6655969191270861 and parameters: {'max_depth': 5, 'learning_rate': 0.24577202667509573, 'n_estimators': 634, 'subsample': 0.8004462883482534, 'colsample_bytree': 0.6059100742772112, 'min_child_weight': 2, 'gamma': 2.446787144450848, 'reg_alpha': 0.0002470629602093025, 'reg_lambda': 0.23143335091140935, 'max_delta_step': 7}. Best is trial 3 with value: 0.7323491655969192.

Best trial: 2. Best value: 0.837612:   6%|▌         | 3/50 [00:54<13:54, 17.75s/it]

[I 2025-12-02 20:11:35,885] Trial 2 finished with value: 0.8376123234916559 and parameters: {'max_depth': 5, 'learning_rate': 0.1578354308632094, 'n_estimators': 905, 'subsample': 0.8509415952430199, 'colsample_bytree': 0.9217266273475256, 'min_child_weight': 6, 'gamma': 2.3366888864735773, 'reg_alpha': 8.572790098262475, 'reg_lambda': 3.911362450264868e-08, 'max_delta_step': 0}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:   8%|▊         | 4/50 [01:03<11:02, 14.41s/it]

[I 2025-12-02 20:11:45,172] Trial 5 finished with value: 0.7182284980744544 and parameters: {'max_depth': 5, 'learning_rate': 0.0957360295745634, 'n_estimators': 322, 'subsample': 0.8383997579923437, 'colsample_bytree': 0.9812851686950936, 'min_child_weight': 1, 'gamma': 1.2037199109553902, 'reg_alpha': 5.320776260531758e-08, 'reg_lambda': 1.9619992309119833e-07, 'max_delta_step': 9}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  10%|█         | 5/50 [01:08<08:13, 10.97s/it]

[I 2025-12-02 20:11:50,055] Trial 4 finished with value: 0.730423620025674 and parameters: {'max_depth': 6, 'learning_rate': 0.07697624682124568, 'n_estimators': 967, 'subsample': 0.9167644883730377, 'colsample_bytree': 0.5300927080318685, 'min_child_weight': 5, 'gamma': 2.53708759445363, 'reg_alpha': 0.0008006320197655855, 'reg_lambda': 6.539028368034203e-06, 'max_delta_step': 5}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  12%|█▏        | 6/50 [01:18<07:54, 10.77s/it]

[I 2025-12-02 20:12:00,437] Trial 1 finished with value: 0.7041078305519897 and parameters: {'max_depth': 9, 'learning_rate': 0.05059507548641304, 'n_estimators': 1247, 'subsample': 0.5871232490447432, 'colsample_bytree': 0.7457728243929194, 'min_child_weight': 1, 'gamma': 0.1308736980723907, 'reg_alpha': 1.4457966402706031e-05, 'reg_lambda': 3.70012086395613e-05, 'max_delta_step': 1}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  14%|█▍        | 7/50 [01:26<07:01,  9.80s/it]

[I 2025-12-02 20:12:08,255] Trial 7 finished with value: 0.7041078305519897 and parameters: {'max_depth': 7, 'learning_rate': 0.097730361907966, 'n_estimators': 350, 'subsample': 0.7777521837067496, 'colsample_bytree': 0.6250967043591047, 'min_child_weight': 4, 'gamma': 1.123230622892295, 'reg_alpha': 1.4047983099355148e-07, 'reg_lambda': 0.4630901818528134, 'max_delta_step': 2}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  16%|█▌        | 8/50 [01:36<07:02, 10.05s/it]

[I 2025-12-02 20:12:18,825] Trial 8 finished with value: 0.7708600770218228 and parameters: {'max_depth': 5, 'learning_rate': 0.028324005648715282, 'n_estimators': 318, 'subsample': 0.7679133655176896, 'colsample_bytree': 0.8814156873865894, 'min_child_weight': 4, 'gamma': 4.031331706828873, 'reg_alpha': 0.00025558380289226296, 'reg_lambda': 8.048705102475164, 'max_delta_step': 6}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  18%|█▊        | 9/50 [01:40<05:22,  7.87s/it]

[I 2025-12-02 20:12:21,906] Trial 6 finished with value: 0.7201540436456997 and parameters: {'max_depth': 6, 'learning_rate': 0.1091852111001877, 'n_estimators': 901, 'subsample': 0.577172880736056, 'colsample_bytree': 0.9102226444816588, 'min_child_weight': 6, 'gamma': 2.030212581029268, 'reg_alpha': 4.919623774019992e-05, 'reg_lambda': 4.460081395942015e-06, 'max_delta_step': 5}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  20%|██        | 10/50 [02:02<08:13, 12.34s/it]

[I 2025-12-02 20:12:44,249] Trial 11 finished with value: 0.772785622593068 and parameters: {'max_depth': 4, 'learning_rate': 0.10980508184059379, 'n_estimators': 419, 'subsample': 0.5303408386779517, 'colsample_bytree': 0.9943762023810347, 'min_child_weight': 6, 'gamma': 0.9397680871280445, 'reg_alpha': 2.7783233877096907e-05, 'reg_lambda': 5.851803969308432e-06, 'max_delta_step': 10}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  22%|██▏       | 11/50 [02:08<06:44, 10.38s/it]

[I 2025-12-02 20:12:50,189] Trial 9 finished with value: 0.7464698331193838 and parameters: {'max_depth': 10, 'learning_rate': 0.013818402827832131, 'n_estimators': 950, 'subsample': 0.5895949000743994, 'colsample_bytree': 0.7557274547006805, 'min_child_weight': 7, 'gamma': 0.7406186862503222, 'reg_alpha': 4.178637519255335e-08, 'reg_lambda': 0.00034320649809581756, 'max_delta_step': 3}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  24%|██▍       | 12/50 [02:14<05:44,  9.06s/it]

[I 2025-12-02 20:12:56,243] Trial 13 pruned.

Best trial: 2. Best value: 0.837612:  26%|██▌       | 13/50 [02:20<04:57,  8.05s/it]

[I 2025-12-02 20:13:01,966] Trial 15 pruned.

Best trial: 2. Best value: 0.837612:  28%|██▊       | 14/50 [02:24<04:11,  6.99s/it]

[I 2025-12-02 20:13:06,501] Trial 12 finished with value: 0.7445442875481387 and parameters: {'max_depth': 5, 'learning_rate': 0.01900019429531379, 'n_estimators': 724, 'subsample': 0.7506684356761119, 'colsample_bytree': 0.6184254906000866, 'min_child_weight': 6, 'gamma': 3.1201378367542185, 'reg_alpha': 0.721777260725665, 'reg_lambda': 0.5560266198185635, 'max_delta_step': 1}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  30%|███       | 15/50 [02:34<04:33,  7.80s/it]

[I 2025-12-02 20:13:16,166] Trial 17 pruned.

Best trial: 2. Best value: 0.837612:  32%|███▏      | 16/50 [02:41<04:14,  7.48s/it]

[I 2025-12-02 20:13:22,905] Trial 10 finished with value: 0.7567394094993581 and parameters: {'max_depth': 7, 'learning_rate': 0.1608124463791891, 'n_estimators': 1366, 'subsample': 0.8772446359223397, 'colsample_bytree': 0.9480406662618766, 'min_child_weight': 4, 'gamma': 0.2985730760951083, 'reg_alpha': 6.458582041058886e-05, 'reg_lambda': 7.707423436225017, 'max_delta_step': 8}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  34%|███▍      | 17/50 [02:44<03:30,  6.37s/it]

[I 2025-12-02 20:13:26,706] Trial 14 finished with value: 0.8112965340179717 and parameters: {'max_depth': 3, 'learning_rate': 0.2659352614902735, 'n_estimators': 672, 'subsample': 0.9970743491450321, 'colsample_bytree': 0.9877257906858473, 'min_child_weight': 9, 'gamma': 3.110837790007843, 'reg_alpha': 2.228402487408637, 'reg_lambda': 1.3151786961504378e-08, 'max_delta_step': 10}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  36%|███▌      | 18/50 [02:49<03:07,  5.85s/it]

[I 2025-12-02 20:13:31,329] Trial 20 pruned.

Best trial: 2. Best value: 0.837612:  38%|███▊      | 19/50 [02:49<02:10,  4.22s/it]

[I 2025-12-02 20:13:31,778] Trial 19 pruned.

Best trial: 2. Best value: 0.837612:  40%|████      | 20/50 [02:50<01:30,  3.02s/it]

[I 2025-12-02 20:13:31,999] Trial 18 pruned.

Best trial: 2. Best value: 0.837612:  42%|████▏     | 21/50 [02:56<01:56,  4.02s/it]

[I 2025-12-02 20:13:38,344] Trial 16 finished with value: 0.6957637997432606 and parameters: {'max_depth': 4, 'learning_rate': 0.05098775804121635, 'n_estimators': 645, 'subsample': 0.6840666812905778, 'colsample_bytree': 0.8900220253063124, 'min_child_weight': 8, 'gamma': 2.9367170979550496, 'reg_alpha': 0.04852127190965115, 'reg_lambda': 1.4796103755214156e-07, 'max_delta_step': 3}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  44%|████▍     | 22/50 [02:59<01:40,  3.60s/it]

[I 2025-12-02 20:13:40,978] Trial 21 pruned.

Best trial: 2. Best value: 0.837612:  46%|████▌     | 23/50 [03:03<01:44,  3.85s/it]

[I 2025-12-02 20:13:45,418] Trial 22 pruned.

Best trial: 2. Best value: 0.837612:  48%|████▊     | 24/50 [03:21<03:27,  8.00s/it]

[I 2025-12-02 20:14:03,086] Trial 26 finished with value: 0.7971758664955071 and parameters: {'max_depth': 3, 'learning_rate': 0.11695248240908816, 'n_estimators': 204, 'subsample': 0.8322557227249243, 'colsample_bytree': 0.9589165749017476, 'min_child_weight': 3, 'gamma': 2.261750650508089, 'reg_alpha': 6.151621532704832, 'reg_lambda': 2.7046715197968566e-08, 'max_delta_step': 8}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  50%|█████     | 25/50 [03:29<03:25,  8.21s/it]

[I 2025-12-02 20:14:11,802] Trial 23 finished with value: 0.7586649550706033 and parameters: {'max_depth': 9, 'learning_rate': 0.23218869829444838, 'n_estimators': 797, 'subsample': 0.927992828018817, 'colsample_bytree': 0.9326399942785464, 'min_child_weight': 9, 'gamma': 3.8401488488365123, 'reg_alpha': 0.27107055226659593, 'reg_lambda': 0.004266996482377646, 'max_delta_step': 0}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  52%|█████▏    | 26/50 [03:38<03:20,  8.34s/it]

[I 2025-12-02 20:14:20,447] Trial 27 finished with value: 0.7586649550706033 and parameters: {'max_depth': 3, 'learning_rate': 0.2996250194646299, 'n_estimators': 216, 'subsample': 0.835519482892165, 'colsample_bytree': 0.9253494207555288, 'min_child_weight': 3, 'gamma': 2.5335844582441234, 'reg_alpha': 9.485780098368101, 'reg_lambda': 2.8872566660196085e-08, 'max_delta_step': 8}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  54%|█████▍    | 27/50 [03:40<02:27,  6.43s/it]

[I 2025-12-02 20:14:22,424] Trial 25 finished with value: 0.8112965340179717 and parameters: {'max_depth': 3, 'learning_rate': 0.12174551146687897, 'n_estimators': 793, 'subsample': 0.8340814151618517, 'colsample_bytree': 0.9484950334729482, 'min_child_weight': 7, 'gamma': 2.4333620329441614, 'reg_alpha': 9.498931260913853, 'reg_lambda': 3.78613779143326e-06, 'max_delta_step': 8}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  56%|█████▌    | 28/50 [03:41<01:45,  4.78s/it]

[I 2025-12-02 20:14:23,354] Trial 24 finished with value: 0.8376123234916559 and parameters: {'max_depth': 3, 'learning_rate': 0.23472251386280682, 'n_estimators': 824, 'subsample': 0.9306090844163402, 'colsample_bytree': 0.9484597089851885, 'min_child_weight': 7, 'gamma': 3.8092994384088947, 'reg_alpha': 9.576127797922334, 'reg_lambda': 1.6813248374538543e-06, 'max_delta_step': 8}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  58%|█████▊    | 29/50 [03:48<01:55,  5.50s/it]

[I 2025-12-02 20:14:30,522] Trial 28 finished with value: 0.7849807445442876 and parameters: {'max_depth': 3, 'learning_rate': 0.07741245371273003, 'n_estimators': 203, 'subsample': 0.8369129303465376, 'colsample_bytree': 0.9582012587647093, 'min_child_weight': 3, 'gamma': 2.334897512703804, 'reg_alpha': 9.534167532275752, 'reg_lambda': 3.890124301502253e-08, 'max_delta_step': 8}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  60%|██████    | 30/50 [03:49<01:20,  4.02s/it]

[I 2025-12-02 20:14:31,077] Trial 29 pruned.

Best trial: 2. Best value: 0.837612:  62%|██████▏   | 31/50 [03:56<01:34,  4.99s/it]

[I 2025-12-02 20:14:38,334] Trial 33 pruned.

Best trial: 2. Best value: 0.837612:  64%|██████▍   | 32/50 [04:02<01:36,  5.36s/it]

[I 2025-12-02 20:14:44,560] Trial 34 pruned.

Best trial: 2. Best value: 0.837612:  66%|██████▌   | 33/50 [04:09<01:39,  5.84s/it]

[I 2025-12-02 20:14:51,521] Trial 35 pruned.

Best trial: 2. Best value: 0.837612:  68%|██████▊   | 34/50 [04:17<01:43,  6.44s/it]

[I 2025-12-02 20:14:59,374] Trial 36 pruned.

Best trial: 2. Best value: 0.837612:  70%|███████   | 35/50 [04:34<02:22,  9.49s/it]

[I 2025-12-02 20:15:15,963] Trial 30 finished with value: 0.7586649550706033 and parameters: {'max_depth': 6, 'learning_rate': 0.07544499601051824, 'n_estimators': 1014, 'subsample': 0.9659561923620584, 'colsample_bytree': 0.8759285103385314, 'min_child_weight': 7, 'gamma': 2.786375579559352, 'reg_alpha': 0.0054325237940390314, 'reg_lambda': 1.1535222096878285e-06, 'max_delta_step': 6}. Best is trial 2 with value: 0.8376123234916559.
[I 2025-12-02 20:15:15,976] Trial 31 finished with value: 0.8234916559691913 and parameters: {'max_depth': 6, 'learning_rate': 0.1376804751822019, 'n_estimators': 1029, 'subsample': 0.999843708933915, 'colsample_bytree': 0.8738416086277069, 'min_child_weight': 9, 'gamma': 4.683042122757826, 'reg_alpha': 0.002345059097443077, 'reg_lambda': 9.821134738353616e-07, 'max_delta_step': 6}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  74%|███████▍  | 37/50 [04:42<01:30,  6.94s/it]

[I 2025-12-02 20:15:23,919] Trial 32 finished with value: 0.8112965340179717 and parameters: {'max_depth': 6, 'learning_rate': 0.24582569099898177, 'n_estimators': 1004, 'subsample': 0.9998223195433783, 'colsample_bytree': 0.890770930722352, 'min_child_weight': 9, 'gamma': 4.8138807596622755, 'reg_alpha': 0.001958847777485274, 'reg_lambda': 1.0938533296845242e-06, 'max_delta_step': 6}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  76%|███████▌  | 38/50 [04:44<01:09,  5.82s/it]

[I 2025-12-02 20:15:26,317] Trial 38 pruned.

Best trial: 2. Best value: 0.837612:  78%|███████▊  | 39/50 [04:45<00:50,  4.63s/it]

[I 2025-12-02 20:15:27,579] Trial 39 pruned.

Best trial: 2. Best value: 0.837612:  80%|████████  | 40/50 [04:53<00:54,  5.42s/it]

[I 2025-12-02 20:15:35,114] Trial 40 pruned.

Best trial: 2. Best value: 0.837612:  82%|████████▏ | 41/50 [04:54<00:38,  4.26s/it]

[I 2025-12-02 20:15:36,379] Trial 41 pruned.

Best trial: 2. Best value: 0.837612:  84%|████████▍ | 42/50 [04:57<00:30,  3.77s/it]

[I 2025-12-02 20:15:38,934] Trial 42 pruned.

Best trial: 2. Best value: 0.837612:  86%|████████▌ | 43/50 [05:02<00:29,  4.20s/it]

[I 2025-12-02 20:15:44,189] Trial 43 pruned.

Best trial: 2. Best value: 0.837612:  88%|████████▊ | 44/50 [05:06<00:25,  4.31s/it]

[I 2025-12-02 20:15:48,773] Trial 45 pruned.

Best trial: 2. Best value: 0.837612:  90%|█████████ | 45/50 [05:09<00:19,  3.88s/it]

[I 2025-12-02 20:15:51,628] Trial 46 pruned.

Best trial: 2. Best value: 0.837612:  92%|█████████▏| 46/50 [05:14<00:16,  4.17s/it]

[I 2025-12-02 20:15:56,474] Trial 47 pruned.

Best trial: 2. Best value: 0.837612:  94%|█████████▍| 47/50 [05:15<00:09,  3.11s/it]

[I 2025-12-02 20:15:57,082] Trial 37 finished with value: 0.7586649550706033 and parameters: {'max_depth': 3, 'learning_rate': 0.23845711841578698, 'n_estimators': 1036, 'subsample': 0.8885853892724995, 'colsample_bytree': 0.9661382596244396, 'min_child_weight': 6, 'gamma': 3.490466035044307, 'reg_alpha': 2.1613833401833196, 'reg_lambda': 5.076979976296606e-08, 'max_delta_step': 6}. Best is trial 2 with value: 0.8376123234916559.

Best trial: 2. Best value: 0.837612:  96%|█████████▌| 48/50 [05:17<00:05,  2.98s/it]

[I 2025-12-02 20:15:59,758] Trial 48 pruned.

Best trial: 2. Best value: 0.837612:  98%|█████████▊| 49/50 [05:20<00:02,  2.86s/it]

[I 2025-12-02 20:16:02,344] Trial 49 pruned.

Best trial: 2. Best value: 0.837612: 100%|██████████| 50/50 [05:35<00:00,  6.71s/it]

[I 2025-12-02 20:16:17,271] Trial 44 finished with value: 0.7708600770218228 and parameters: {'max_depth': 5, 'learning_rate': 0.13191892595048013, 'n_estimators': 857, 'subsample': 0.9755599862071588, 'colsample_bytree': 0.9720426663138166, 'min_child_weight': 5, 'gamma': 1.922104890913639, 'reg_alpha': 3.5988070872687294, 'reg_lambda': 0.0001694666220146927, 'max_delta_step': 9}. Best is trial 2 with value: 0.8376123234916559.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.837612                    0.35          0.32

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.288675               0.4               0.3        50          60

   test_size
0         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.837612                    0.35          0.32

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.288675               0.4               0.3        50          60

   test_size
0         15

In [ ]:

datasets = task_hf_compensated_freq_emb_lbl_pd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_pd_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_handcrafted_frerq_emb_pd_hc_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param= "diagnosis_y",
)
print(summary)
## MCI-AD vs HC -> OPTUNA + XGB

[I 2025-12-02 20:16:20,223] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.245828:   2%|▏         | 1/50 [00:34<28:25, 34.80s/it]

[I 2025-12-02 20:16:55,014] Trial 1 finished with value: 0.24582798459563543 and parameters: {'max_depth': 4, 'learning_rate': 0.23798074847548928, 'n_estimators': 647, 'subsample': 0.5753896586418707, 'colsample_bytree': 0.7330556203010179, 'min_child_weight': 10, 'gamma': 1.3445315649371765, 'reg_alpha': 2.2909330526324503e-06, 'reg_lambda': 0.0002963671845604144, 'max_delta_step': 0}. Best is trial 1 with value: 0.24582798459563543.

Best trial: 0. Best value: 0.706033:   4%|▍         | 2/50 [00:46<16:48, 21.02s/it]

[I 2025-12-02 20:17:06,383] Trial 0 finished with value: 0.7060333761232349 and parameters: {'max_depth': 8, 'learning_rate': 0.023666095506560177, 'n_estimators': 742, 'subsample': 0.7639305538513248, 'colsample_bytree': 0.8344380021831599, 'min_child_weight': 6, 'gamma': 1.5277016819765699, 'reg_alpha': 3.141529359526296e-08, 'reg_lambda': 0.011809457953103064, 'max_delta_step': 2}. Best is trial 0 with value: 0.7060333761232349.

Best trial: 2. Best value: 0.734275:   6%|▌         | 3/50 [00:48<09:45, 12.46s/it]

[I 2025-12-02 20:17:08,651] Trial 2 finished with value: 0.7342747111681642 and parameters: {'max_depth': 5, 'learning_rate': 0.06226431759629723, 'n_estimators': 940, 'subsample': 0.8082486621693843, 'colsample_bytree': 0.5779183345886882, 'min_child_weight': 9, 'gamma': 0.16580570891773339, 'reg_alpha': 0.011150623467095238, 'reg_lambda': 7.2803009213390455, 'max_delta_step': 2}. Best is trial 2 with value: 0.7342747111681642.

Best trial: 2. Best value: 0.734275:   8%|▊         | 4/50 [01:01<09:39, 12.59s/it]

[I 2025-12-02 20:17:21,442] Trial 4 finished with value: 0.7060333761232349 and parameters: {'max_depth': 8, 'learning_rate': 0.03989701133834196, 'n_estimators': 464, 'subsample': 0.9416069289273283, 'colsample_bytree': 0.6865928734455652, 'min_child_weight': 7, 'gamma': 2.0663913824426308, 'reg_alpha': 1.7538211729328884e-05, 'reg_lambda': 2.0494605126948473e-06, 'max_delta_step': 0}. Best is trial 2 with value: 0.7342747111681642.

Best trial: 2. Best value: 0.734275:  10%|█         | 5/50 [01:10<08:35, 11.47s/it]

[I 2025-12-02 20:17:30,918] Trial 3 finished with value: 0.6007702182284981 and parameters: {'max_depth': 8, 'learning_rate': 0.16846886153129612, 'n_estimators': 1367, 'subsample': 0.7135569670466331, 'colsample_bytree': 0.7721561418095579, 'min_child_weight': 3, 'gamma': 1.1978264991199072, 'reg_alpha': 0.004001155328700415, 'reg_lambda': 0.05797049296288498, 'max_delta_step': 9}. Best is trial 2 with value: 0.7342747111681642.

Best trial: 2. Best value: 0.734275:  12%|█▏        | 6/50 [01:43<13:45, 18.77s/it]

[I 2025-12-02 20:18:03,865] Trial 6 finished with value: 0.7060333761232349 and parameters: {'max_depth': 3, 'learning_rate': 0.025496521518841558, 'n_estimators': 1044, 'subsample': 0.7281201398191373, 'colsample_bytree': 0.6746408907387886, 'min_child_weight': 4, 'gamma': 3.333587557867183, 'reg_alpha': 0.005377739877179788, 'reg_lambda': 0.00019858191398448068, 'max_delta_step': 0}. Best is trial 2 with value: 0.7342747111681642.

Best trial: 5. Best value: 0.811297:  14%|█▍        | 7/50 [01:58<12:29, 17.44s/it]

[I 2025-12-02 20:18:18,564] Trial 5 finished with value: 0.8112965340179717 and parameters: {'max_depth': 5, 'learning_rate': 0.027796210440548003, 'n_estimators': 814, 'subsample': 0.7540342674813401, 'colsample_bytree': 0.9756742845980508, 'min_child_weight': 1, 'gamma': 4.320536872727675, 'reg_alpha': 8.055455860891296, 'reg_lambda': 1.7898357044221265, 'max_delta_step': 1}. Best is trial 5 with value: 0.8112965340179717.

Best trial: 5. Best value: 0.811297:  16%|█▌        | 8/50 [02:06<10:05, 14.43s/it]

[I 2025-12-02 20:18:26,548] Trial 8 finished with value: 0.7849807445442876 and parameters: {'max_depth': 5, 'learning_rate': 0.013532911221011792, 'n_estimators': 1148, 'subsample': 0.9326220326157837, 'colsample_bytree': 0.8655831883636569, 'min_child_weight': 9, 'gamma': 1.9274412341112246, 'reg_alpha': 4.051811459751693e-08, 'reg_lambda': 1.1475461653056557e-06, 'max_delta_step': 8}. Best is trial 5 with value: 0.8112965340179717.

Best trial: 5. Best value: 0.811297:  18%|█▊        | 9/50 [02:09<07:28, 10.95s/it]

[I 2025-12-02 20:18:29,839] Trial 9 finished with value: 0.7586649550706033 and parameters: {'max_depth': 10, 'learning_rate': 0.13826006151675127, 'n_estimators': 473, 'subsample': 0.9282648530409575, 'colsample_bytree': 0.8845773837887959, 'min_child_weight': 7, 'gamma': 1.2090500500643608, 'reg_alpha': 0.09927351020844345, 'reg_lambda': 4.318307431009489e-06, 'max_delta_step': 2}. Best is trial 5 with value: 0.8112965340179717.

Best trial: 5. Best value: 0.811297:  20%|██        | 10/50 [02:10<05:14,  7.85s/it]

[I 2025-12-02 20:18:30,770] Trial 7 finished with value: 0.7586649550706033 and parameters: {'max_depth': 6, 'learning_rate': 0.011694439058282383, 'n_estimators': 1493, 'subsample': 0.7625348302501367, 'colsample_bytree': 0.6381154952031394, 'min_child_weight': 8, 'gamma': 2.9381971153841677, 'reg_alpha': 3.688761290649191e-05, 'reg_lambda': 1.8094648800569315e-06, 'max_delta_step': 5}. Best is trial 5 with value: 0.8112965340179717.

Best trial: 5. Best value: 0.811297:  22%|██▏       | 11/50 [02:17<04:58,  7.64s/it]

[I 2025-12-02 20:18:37,937] Trial 12 pruned.

Best trial: 5. Best value: 0.811297:  24%|██▍       | 12/50 [02:26<05:08,  8.13s/it]

[I 2025-12-02 20:18:47,163] Trial 10 finished with value: 0.6392811296534018 and parameters: {'max_depth': 4, 'learning_rate': 0.11261082576306303, 'n_estimators': 529, 'subsample': 0.5394458756535465, 'colsample_bytree': 0.669174142916666, 'min_child_weight': 3, 'gamma': 4.323022440543338, 'reg_alpha': 0.2494766054116403, 'reg_lambda': 2.15457666686403e-08, 'max_delta_step': 0}. Best is trial 5 with value: 0.8112965340179717.

Best trial: 5. Best value: 0.811297:  26%|██▌       | 13/50 [02:34<04:50,  7.84s/it]

[I 2025-12-02 20:18:54,355] Trial 11 finished with value: 0.7971758664955071 and parameters: {'max_depth': 5, 'learning_rate': 0.06866101189990972, 'n_estimators': 554, 'subsample': 0.898322651484253, 'colsample_bytree': 0.6008634703798201, 'min_child_weight': 8, 'gamma': 4.493691135975314, 'reg_alpha': 4.4226159553992455, 'reg_lambda': 0.0005377784560491515, 'max_delta_step': 3}. Best is trial 5 with value: 0.8112965340179717.

Best trial: 5. Best value: 0.811297:  28%|██▊       | 14/50 [02:42<04:44,  7.89s/it]

[I 2025-12-02 20:19:02,360] Trial 13 finished with value: 0.7849807445442876 and parameters: {'max_depth': 3, 'learning_rate': 0.0742858364636597, 'n_estimators': 336, 'subsample': 0.501271411647165, 'colsample_bytree': 0.9838047207516738, 'min_child_weight': 1, 'gamma': 4.636125930841694, 'reg_alpha': 1.5722022756366467, 'reg_lambda': 7.04085726163315, 'max_delta_step': 5}. Best is trial 5 with value: 0.8112965340179717.

Best trial: 17. Best value: 0.837612:  30%|███       | 15/50 [02:54<05:22,  9.20s/it]

[I 2025-12-02 20:19:14,601] Trial 17 finished with value: 0.8376123234916559 and parameters: {'max_depth': 6, 'learning_rate': 0.03501044915172519, 'n_estimators': 200, 'subsample': 0.6455700440738994, 'colsample_bytree': 0.5119472916628306, 'min_child_weight': 5, 'gamma': 4.845187578651593, 'reg_alpha': 8.969327213781947, 'reg_lambda': 0.09740529299280483, 'max_delta_step': 4}. Best is trial 17 with value: 0.8376123234916559.

Best trial: 17. Best value: 0.837612:  32%|███▏      | 16/50 [02:57<04:11,  7.39s/it]

[I 2025-12-02 20:19:17,772] Trial 16 finished with value: 0.8112965340179717 and parameters: {'max_depth': 6, 'learning_rate': 0.07440153601314044, 'n_estimators': 222, 'subsample': 0.6461660567271604, 'colsample_bytree': 0.9941040001862186, 'min_child_weight': 1, 'gamma': 4.980086711919228, 'reg_alpha': 4.736713720600117, 'reg_lambda': 3.814228739872198, 'max_delta_step': 5}. Best is trial 17 with value: 0.8376123234916559.

Best trial: 17. Best value: 0.837612:  34%|███▍      | 17/50 [02:58<03:03,  5.57s/it]

[I 2025-12-02 20:19:19,128] Trial 15 finished with value: 0.8376123234916559 and parameters: {'max_depth': 6, 'learning_rate': 0.016407747071864015, 'n_estimators': 221, 'subsample': 0.9917178296069638, 'colsample_bytree': 0.9919202323768523, 'min_child_weight': 1, 'gamma': 4.991979021777036, 'reg_alpha': 5.8858454754614264, 'reg_lambda': 4.984295953597137, 'max_delta_step': 9}. Best is trial 17 with value: 0.8376123234916559.

Best trial: 17. Best value: 0.837612:  36%|███▌      | 18/50 [03:04<02:55,  5.48s/it]

[I 2025-12-02 20:19:24,378] Trial 19 pruned.

Best trial: 17. Best value: 0.837612:  38%|███▊      | 19/50 [03:08<02:36,  5.05s/it]

[I 2025-12-02 20:19:28,418] Trial 21 pruned.

Best trial: 17. Best value: 0.837612:  40%|████      | 20/50 [03:15<02:52,  5.75s/it]

[I 2025-12-02 20:19:35,826] Trial 22 pruned.

Best trial: 17. Best value: 0.837612:  42%|████▏     | 21/50 [03:18<02:22,  4.90s/it]

[I 2025-12-02 20:19:38,735] Trial 23 pruned.

Best trial: 17. Best value: 0.837612:  44%|████▍     | 22/50 [03:20<01:56,  4.17s/it]

[I 2025-12-02 20:19:41,209] Trial 20 finished with value: 0.7182284980744544 and parameters: {'max_depth': 7, 'learning_rate': 0.017023748895360707, 'n_estimators': 209, 'subsample': 0.9999358255446295, 'colsample_bytree': 0.5042542796681176, 'min_child_weight': 4, 'gamma': 3.602347604076543, 'reg_alpha': 0.3094943084439345, 'reg_lambda': 0.16614097922900847, 'max_delta_step': 7}. Best is trial 17 with value: 0.8376123234916559.

Best trial: 17. Best value: 0.837612:  46%|████▌     | 23/50 [03:21<01:21,  3.04s/it]

[I 2025-12-02 20:19:41,596] Trial 18 finished with value: 0.8112965340179717 and parameters: {'max_depth': 7, 'learning_rate': 0.031974301698080215, 'n_estimators': 332, 'subsample': 0.6441696770968712, 'colsample_bytree': 0.5100154466949616, 'min_child_weight': 1, 'gamma': 4.9757522238775245, 'reg_alpha': 7.491126612959286, 'reg_lambda': 0.07791165908393961, 'max_delta_step': 6}. Best is trial 17 with value: 0.8376123234916559.

Best trial: 17. Best value: 0.837612:  48%|████▊     | 24/50 [03:50<04:39, 10.74s/it]

[I 2025-12-02 20:20:10,289] Trial 25 finished with value: 0.8376123234916559 and parameters: {'max_depth': 6, 'learning_rate': 0.030731504694889836, 'n_estimators': 357, 'subsample': 0.6818248268174291, 'colsample_bytree': 0.9455431807967153, 'min_child_weight': 2, 'gamma': 4.204888497986854, 'reg_alpha': 9.606134994432807, 'reg_lambda': 1.0169861657782189, 'max_delta_step': 4}. Best is trial 17 with value: 0.8376123234916559.

Best trial: 17. Best value: 0.837612:  50%|█████     | 25/50 [03:55<03:50,  9.22s/it]

[I 2025-12-02 20:20:15,965] Trial 27 pruned.

Best trial: 17. Best value: 0.837612:  52%|█████▏    | 26/50 [04:06<03:54,  9.76s/it]

[I 2025-12-02 20:20:26,986] Trial 28 pruned.

Best trial: 17. Best value: 0.837612:  54%|█████▍    | 27/50 [04:11<03:11,  8.31s/it]

[I 2025-12-02 20:20:31,925] Trial 24 finished with value: 0.8376123234916559 and parameters: {'max_depth': 6, 'learning_rate': 0.017234684466431522, 'n_estimators': 648, 'subsample': 0.6736406854877637, 'colsample_bytree': 0.9425244262933448, 'min_child_weight': 2, 'gamma': 4.114208174862799, 'reg_alpha': 8.554166661010525, 'reg_lambda': 1.5796598422505113, 'max_delta_step': 4}. Best is trial 17 with value: 0.8376123234916559.

Best trial: 17. Best value: 0.837612:  56%|█████▌    | 28/50 [04:19<03:02,  8.28s/it]

[I 2025-12-02 20:20:40,144] Trial 30 pruned.

Best trial: 17. Best value: 0.837612:  58%|█████▊    | 29/50 [04:25<02:38,  7.54s/it]

[I 2025-12-02 20:20:45,936] Trial 14 finished with value: 0.7445442875481387 and parameters: {'max_depth': 6, 'learning_rate': 0.011534276864697325, 'n_estimators': 1279, 'subsample': 0.6104043637447292, 'colsample_bytree': 0.999201276246399, 'min_child_weight': 1, 'gamma': 4.784050668070419, 'reg_alpha': 3.1226477984064944, 'reg_lambda': 1.9019331679985708e-08, 'max_delta_step': 9}. Best is trial 17 with value: 0.8376123234916559.

Best trial: 17. Best value: 0.837612:  60%|██████    | 30/50 [04:29<02:10,  6.51s/it]

[I 2025-12-02 20:20:50,044] Trial 31 pruned.

Best trial: 17. Best value: 0.837612:  62%|██████▏   | 31/50 [04:33<01:49,  5.78s/it]

[I 2025-12-02 20:20:54,128] Trial 32 pruned.

Best trial: 17. Best value: 0.837612:  64%|██████▍   | 32/50 [04:38<01:35,  5.32s/it]

[I 2025-12-02 20:20:58,366] Trial 33 pruned.

Best trial: 17. Best value: 0.837612:  66%|██████▌   | 33/50 [04:38<01:05,  3.84s/it]

[I 2025-12-02 20:20:58,756] Trial 29 finished with value: 0.7060333761232349 and parameters: {'max_depth': 6, 'learning_rate': 0.019103770278602585, 'n_estimators': 299, 'subsample': 0.8152913201933953, 'colsample_bytree': 0.8355467910115483, 'min_child_weight': 3, 'gamma': 4.635617344214217, 'reg_alpha': 0.7482212626734005, 'reg_lambda': 0.002287391426573963, 'max_delta_step': 4}. Best is trial 17 with value: 0.8376123234916559.

Best trial: 17. Best value: 0.837612:  68%|██████▊   | 34/50 [04:43<01:07,  4.22s/it]

[I 2025-12-02 20:21:03,880] Trial 35 pruned.

Best trial: 17. Best value: 0.837612:  70%|███████   | 35/50 [04:49<01:12,  4.82s/it]

[I 2025-12-02 20:21:10,096] Trial 26 finished with value: 0.8376123234916559 and parameters: {'max_depth': 6, 'learning_rate': 0.010102411300282436, 'n_estimators': 1209, 'subsample': 0.5939519450704784, 'colsample_bytree': 0.941499118186859, 'min_child_weight': 2, 'gamma': 4.15148804134306, 'reg_alpha': 9.601358971580671, 'reg_lambda': 1.214128354344676, 'max_delta_step': 4}. Best is trial 17 with value: 0.8376123234916559.

Best trial: 17. Best value: 0.837612:  72%|███████▏  | 36/50 [05:03<01:45,  7.55s/it]

[I 2025-12-02 20:21:24,018] Trial 34 finished with value: 0.8376123234916559 and parameters: {'max_depth': 5, 'learning_rate': 0.03024684112030245, 'n_estimators': 323, 'subsample': 0.6894716426393043, 'colsample_bytree': 0.9537562420175463, 'min_child_weight': 2, 'gamma': 4.066250101778289, 'reg_alpha': 9.959267866677415, 'reg_lambda': 1.1227417403483497, 'max_delta_step': 4}. Best is trial 17 with value: 0.8376123234916559.

Best trial: 17. Best value: 0.837612:  74%|███████▍  | 37/50 [05:16<01:57,  9.01s/it]

[I 2025-12-02 20:21:36,440] Trial 36 finished with value: 0.8376123234916559 and parameters: {'max_depth': 5, 'learning_rate': 0.030878501481702632, 'n_estimators': 438, 'subsample': 0.690553297317142, 'colsample_bytree': 0.9447757154073063, 'min_child_weight': 2, 'gamma': 4.083558200885447, 'reg_alpha': 9.476908943658033, 'reg_lambda': 1.3200218302120101, 'max_delta_step': 6}. Best is trial 17 with value: 0.8376123234916559.

Best trial: 17. Best value: 0.837612:  76%|███████▌  | 38/50 [05:16<01:17,  6.44s/it]

[I 2025-12-02 20:21:36,884] Trial 38 finished with value: 0.8112965340179717 and parameters: {'max_depth': 5, 'learning_rate': 0.035890405378563014, 'n_estimators': 415, 'subsample': 0.7197238575776248, 'colsample_bytree': 0.7279979980011811, 'min_child_weight': 5, 'gamma': 3.7259296158457573, 'reg_alpha': 2.7516072942613476, 'reg_lambda': 9.772923701935168, 'max_delta_step': 6}. Best is trial 17 with value: 0.8376123234916559.

Best trial: 17. Best value: 0.837612:  78%|███████▊  | 39/50 [05:21<01:05,  5.96s/it]

[I 2025-12-02 20:21:41,735] Trial 40 pruned.

Best trial: 17. Best value: 0.837612:  80%|████████  | 40/50 [05:26<00:57,  5.78s/it]

[I 2025-12-02 20:21:47,070] Trial 42 pruned.

Best trial: 17. Best value: 0.837612:  82%|████████▏ | 41/50 [05:34<00:56,  6.25s/it]

[I 2025-12-02 20:21:54,421] Trial 37 finished with value: 0.8112965340179717 and parameters: {'max_depth': 5, 'learning_rate': 0.03817448458474917, 'n_estimators': 443, 'subsample': 0.5509740669219079, 'colsample_bytree': 0.953657726725614, 'min_child_weight': 2, 'gamma': 0.20376455136490934, 'reg_alpha': 8.030134557546054, 'reg_lambda': 9.227551865971636, 'max_delta_step': 6}. Best is trial 17 with value: 0.8376123234916559.

Best trial: 17. Best value: 0.837612:  84%|████████▍ | 42/50 [05:34<00:35,  4.45s/it]

[I 2025-12-02 20:21:54,684] Trial 39 finished with value: 0.7586649550706033 and parameters: {'max_depth': 8, 'learning_rate': 0.038717794338442545, 'n_estimators': 433, 'subsample': 0.7277559898197683, 'colsample_bytree': 0.7451464668144102, 'min_child_weight': 4, 'gamma': 3.718799692570576, 'reg_alpha': 2.581921404408754, 'reg_lambda': 7.558851082056904, 'max_delta_step': 6}. Best is trial 17 with value: 0.8376123234916559.

Best trial: 17. Best value: 0.837612:  86%|████████▌ | 43/50 [05:49<00:53,  7.60s/it]

[I 2025-12-02 20:22:09,628] Trial 41 finished with value: 0.7849807445442876 and parameters: {'max_depth': 8, 'learning_rate': 0.052823023384947695, 'n_estimators': 557, 'subsample': 0.5682783066652394, 'colsample_bytree': 0.8888111510037615, 'min_child_weight': 4, 'gamma': 4.443976060893653, 'reg_alpha': 0.014675596777004375, 'reg_lambda': 3.4227870665908373, 'max_delta_step': 1}. Best is trial 17 with value: 0.8376123234916559.

Best trial: 17. Best value: 0.837612:  88%|████████▊ | 44/50 [05:54<00:40,  6.77s/it]

[I 2025-12-02 20:22:14,456] Trial 45 pruned.

Best trial: 17. Best value: 0.837612:  90%|█████████ | 45/50 [06:07<00:44,  8.83s/it]

[I 2025-12-02 20:22:28,099] Trial 47 pruned.

Best trial: 17. Best value: 0.837612:  92%|█████████▏| 46/50 [06:09<00:26,  6.62s/it]

[I 2025-12-02 20:22:29,568] Trial 46 pruned.

Best trial: 17. Best value: 0.837612:  94%|█████████▍| 47/50 [06:15<00:19,  6.50s/it]

[I 2025-12-02 20:22:35,790] Trial 48 pruned.

Best trial: 17. Best value: 0.837612:  96%|█████████▌| 48/50 [06:18<00:10,  5.50s/it]

[I 2025-12-02 20:22:38,954] Trial 49 pruned.

Best trial: 17. Best value: 0.837612:  98%|█████████▊| 49/50 [06:25<00:05,  5.84s/it]

[I 2025-12-02 20:22:45,587] Trial 43 finished with value: 0.730423620025674 and parameters: {'max_depth': 7, 'learning_rate': 0.02530858600572761, 'n_estimators': 744, 'subsample': 0.643064738118209, 'colsample_bytree': 0.5604246813616138, 'min_child_weight': 1, 'gamma': 2.1324610358175438, 'reg_alpha': 0.0012504724963652237, 'reg_lambda': 2.6893012719196814, 'max_delta_step': 1}. Best is trial 17 with value: 0.8376123234916559.

Best trial: 17. Best value: 0.837612: 100%|██████████| 50/50 [07:06<00:00,  8.54s/it]

[I 2025-12-02 20:23:27,176] Trial 44 finished with value: 0.7182284980744544 and parameters: {'max_depth': 6, 'learning_rate': 0.014295635237276394, 'n_estimators': 1213, 'subsample': 0.6391093674880223, 'colsample_bytree': 0.8715039720248198, 'min_child_weight': 1, 'gamma': 4.398533268797637, 'reg_alpha': 0.6076709995925408, 'reg_lambda': 3.452600551900792, 'max_delta_step': 3}. Best is trial 17 with value: 0.8376123234916559.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.837612                    0.35          0.53

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.288675               0.4               0.3        50          60

   test_size
0         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.837612                    0.35          0.53

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.288675               0.4               0.3        50          60

   test_size
0         15

In [ ]:
datasets = task_freq_dfs_pd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_pd_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_freq_pd_hc_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param="emb_",
)
print(summary)

[I 2025-12-02 20:23:29,904] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.501284:   2%|▏         | 1/50 [00:18<15:19, 18.77s/it]

[I 2025-12-02 20:23:48,665] Trial 3 finished with value: 0.5012836970474968 and parameters: {'max_depth': 5, 'learning_rate': 0.17130654385239677, 'n_estimators': 295, 'subsample': 0.7292016159793753, 'colsample_bytree': 0.5916943869593463, 'min_child_weight': 6, 'gamma': 1.2701914580096207, 'reg_alpha': 0.7465663748329668, 'reg_lambda': 7.303166814080031, 'max_delta_step': 6}. Best is trial 3 with value: 0.5012836970474968.

Best trial: 0. Best value: 0.509628:   4%|▍         | 2/50 [00:24<08:49, 11.04s/it]

[I 2025-12-02 20:23:54,296] Trial 0 finished with value: 0.5096277278562259 and parameters: {'max_depth': 6, 'learning_rate': 0.04596560535296241, 'n_estimators': 209, 'subsample': 0.7032065562310146, 'colsample_bytree': 0.7810739955764237, 'min_child_weight': 2, 'gamma': 2.003498099348784, 'reg_alpha': 0.00019184022757996256, 'reg_lambda': 0.3193987597826473, 'max_delta_step': 5}. Best is trial 0 with value: 0.5096277278562259.

Best trial: 0. Best value: 0.509628:   6%|▌         | 3/50 [00:48<13:25, 17.14s/it]

[I 2025-12-02 20:24:18,699] Trial 4 finished with value: 0.49550706033376124 and parameters: {'max_depth': 8, 'learning_rate': 0.07552888870263287, 'n_estimators': 413, 'subsample': 0.9348709633760373, 'colsample_bytree': 0.8459887815554049, 'min_child_weight': 3, 'gamma': 0.16482608611324334, 'reg_alpha': 6.254894384060005e-06, 'reg_lambda': 0.008582996720710664, 'max_delta_step': 0}. Best is trial 0 with value: 0.5096277278562259.

Best trial: 0. Best value: 0.509628:   8%|▊         | 4/50 [00:57<10:36, 13.84s/it]

[I 2025-12-02 20:24:27,487] Trial 2 finished with value: 0.5012836970474968 and parameters: {'max_depth': 7, 'learning_rate': 0.019389876772199142, 'n_estimators': 1044, 'subsample': 0.8699156710886455, 'colsample_bytree': 0.7504241100931244, 'min_child_weight': 7, 'gamma': 4.0228083048351575, 'reg_alpha': 5.631436330696536e-05, 'reg_lambda': 8.163557516743217e-05, 'max_delta_step': 9}. Best is trial 0 with value: 0.5096277278562259.

Best trial: 1. Best value: 0.511553:  10%|█         | 5/50 [01:16<11:44, 15.65s/it]

[I 2025-12-02 20:24:46,344] Trial 1 finished with value: 0.511553273427471 and parameters: {'max_depth': 10, 'learning_rate': 0.017116209390788388, 'n_estimators': 981, 'subsample': 0.76550252296127, 'colsample_bytree': 0.8482030678790291, 'min_child_weight': 3, 'gamma': 3.9197505984906256, 'reg_alpha': 3.0407332825921004e-06, 'reg_lambda': 0.0012117178206634423, 'max_delta_step': 6}. Best is trial 1 with value: 0.511553273427471.

Best trial: 1. Best value: 0.511553:  12%|█▏        | 6/50 [01:28<10:29, 14.30s/it]

[I 2025-12-02 20:24:58,035] Trial 6 finished with value: 0.48908857509627723 and parameters: {'max_depth': 3, 'learning_rate': 0.10252182834020541, 'n_estimators': 770, 'subsample': 0.8177366679066993, 'colsample_bytree': 0.6476267941790539, 'min_child_weight': 9, 'gamma': 4.666435044492029, 'reg_alpha': 0.00019660331086260158, 'reg_lambda': 1.2012164261191007, 'max_delta_step': 7}. Best is trial 1 with value: 0.511553273427471.

Best trial: 1. Best value: 0.511553:  14%|█▍        | 7/50 [01:33<08:07, 11.33s/it]

[I 2025-12-02 20:25:03,236] Trial 5 finished with value: 0.5 and parameters: {'max_depth': 9, 'learning_rate': 0.023774489113639028, 'n_estimators': 1479, 'subsample': 0.5060042887330792, 'colsample_bytree': 0.5978300432637309, 'min_child_weight': 9, 'gamma': 0.5582223892611171, 'reg_alpha': 8.228738581737604e-08, 'reg_lambda': 0.0004882927045668775, 'max_delta_step': 3}. Best is trial 1 with value: 0.511553273427471.

Best trial: 10. Best value: 0.569961:  16%|█▌        | 8/50 [01:51<09:28, 13.54s/it]

[I 2025-12-02 20:25:21,519] Trial 10 finished with value: 0.5699614890885751 and parameters: {'max_depth': 5, 'learning_rate': 0.09375623956837106, 'n_estimators': 331, 'subsample': 0.6829305464504394, 'colsample_bytree': 0.965726159062638, 'min_child_weight': 8, 'gamma': 4.776678024959795, 'reg_alpha': 8.010511504970712e-08, 'reg_lambda': 1.0239612784763857e-06, 'max_delta_step': 3}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961:  18%|█▊        | 9/50 [02:04<09:01, 13.20s/it]

[I 2025-12-02 20:25:33,953] Trial 8 finished with value: 0.5134788189987163 and parameters: {'max_depth': 7, 'learning_rate': 0.011889848885258849, 'n_estimators': 755, 'subsample': 0.9049693736969946, 'colsample_bytree': 0.6784334349153731, 'min_child_weight': 8, 'gamma': 3.288196954438338, 'reg_alpha': 0.0006476688819356154, 'reg_lambda': 0.19612790610817835, 'max_delta_step': 2}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961:  20%|██        | 10/50 [02:14<08:17, 12.43s/it]

[I 2025-12-02 20:25:44,673] Trial 7 finished with value: 0.511553273427471 and parameters: {'max_depth': 5, 'learning_rate': 0.05766290858382111, 'n_estimators': 1311, 'subsample': 0.6969686642055422, 'colsample_bytree': 0.5852221538911175, 'min_child_weight': 3, 'gamma': 4.134762737615084, 'reg_alpha': 0.001144542008936794, 'reg_lambda': 0.21413194086134954, 'max_delta_step': 10}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961:  22%|██▏       | 11/50 [02:23<07:17, 11.21s/it]

[I 2025-12-02 20:25:53,118] Trial 12 pruned.

Best trial: 10. Best value: 0.569961:  24%|██▍       | 12/50 [02:25<05:18,  8.38s/it]

[I 2025-12-02 20:25:55,025] Trial 13 pruned.

Best trial: 10. Best value: 0.569961:  26%|██▌       | 13/50 [02:29<04:26,  7.21s/it]

[I 2025-12-02 20:25:59,527] Trial 14 pruned.

Best trial: 10. Best value: 0.569961:  28%|██▊       | 14/50 [02:30<03:07,  5.22s/it]

[I 2025-12-02 20:26:00,157] Trial 11 finished with value: 0.47881899871630296 and parameters: {'max_depth': 9, 'learning_rate': 0.24715691547359664, 'n_estimators': 682, 'subsample': 0.7809750491537288, 'colsample_bytree': 0.5581877235299573, 'min_child_weight': 8, 'gamma': 1.4846679425325164, 'reg_alpha': 0.09245678137084319, 'reg_lambda': 3.882196490404395e-08, 'max_delta_step': 9}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961:  30%|███       | 15/50 [02:34<02:53,  4.97s/it]

[I 2025-12-02 20:26:04,548] Trial 17 pruned.

Best trial: 10. Best value: 0.569961:  32%|███▏      | 16/50 [02:43<03:28,  6.14s/it]

[I 2025-12-02 20:26:13,400] Trial 9 finished with value: 0.4993581514762516 and parameters: {'max_depth': 5, 'learning_rate': 0.16087240867643887, 'n_estimators': 1365, 'subsample': 0.9352830138319604, 'colsample_bytree': 0.7708692554129295, 'min_child_weight': 5, 'gamma': 2.8255055310958777, 'reg_alpha': 0.00044155135280262694, 'reg_lambda': 0.07220675759608776, 'max_delta_step': 4}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961:  34%|███▍      | 17/50 [03:11<06:56, 12.61s/it]

[I 2025-12-02 20:26:41,068] Trial 16 finished with value: 0.48908857509627723 and parameters: {'max_depth': 5, 'learning_rate': 0.03593468145888747, 'n_estimators': 758, 'subsample': 0.8531640119876229, 'colsample_bytree': 0.6615547910337677, 'min_child_weight': 7, 'gamma': 4.958140030171001, 'reg_alpha': 0.2620806017745482, 'reg_lambda': 1.3419947993134603e-06, 'max_delta_step': 2}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961:  36%|███▌      | 18/50 [03:12<04:53,  9.16s/it]

[I 2025-12-02 20:26:42,189] Trial 15 finished with value: 0.5519897304236201 and parameters: {'max_depth': 5, 'learning_rate': 0.03244980007469607, 'n_estimators': 709, 'subsample': 0.9992692750717731, 'colsample_bytree': 0.9847125956727489, 'min_child_weight': 7, 'gamma': 3.035138905207865, 'reg_alpha': 0.024260001166124413, 'reg_lambda': 3.4798059212400096e-06, 'max_delta_step': 1}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961:  38%|███▊      | 19/50 [03:15<03:50,  7.42s/it]

[I 2025-12-02 20:26:45,566] Trial 20 pruned.

Best trial: 10. Best value: 0.569961:  40%|████      | 20/50 [03:20<03:20,  6.68s/it]

[I 2025-12-02 20:26:50,522] Trial 18 finished with value: 0.5012836970474968 and parameters: {'max_depth': 7, 'learning_rate': 0.04280861161156415, 'n_estimators': 863, 'subsample': 0.6484622782817637, 'colsample_bytree': 0.5159125803068817, 'min_child_weight': 6, 'gamma': 3.5213459960997406, 'reg_alpha': 0.0074305602765029725, 'reg_lambda': 0.01604498626683229, 'max_delta_step': 4}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961:  42%|████▏     | 21/50 [03:27<03:14,  6.70s/it]

[I 2025-12-02 20:26:57,282] Trial 23 pruned.

Best trial: 10. Best value: 0.569961:  44%|████▍     | 22/50 [03:31<02:49,  6.04s/it]

[I 2025-12-02 20:27:01,769] Trial 19 finished with value: 0.5295250320924262 and parameters: {'max_depth': 7, 'learning_rate': 0.03686634620828921, 'n_estimators': 880, 'subsample': 0.6168207395548747, 'colsample_bytree': 0.8918336899959957, 'min_child_weight': 7, 'gamma': 3.7147780919206763, 'reg_alpha': 1.4760478332092867e-06, 'reg_lambda': 4.301801789108887e-06, 'max_delta_step': 0}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961:  46%|████▌     | 23/50 [03:39<02:54,  6.46s/it]

[I 2025-12-02 20:27:09,223] Trial 25 pruned.

Best trial: 10. Best value: 0.569961:  48%|████▊     | 24/50 [03:49<03:15,  7.53s/it]

[I 2025-12-02 20:27:19,246] Trial 26 pruned.

Best trial: 10. Best value: 0.569961:  50%|█████     | 25/50 [03:55<03:01,  7.26s/it]

[I 2025-12-02 20:27:25,864] Trial 22 finished with value: 0.5256739409499358 and parameters: {'max_depth': 4, 'learning_rate': 0.03568192942308924, 'n_estimators': 565, 'subsample': 0.9837724537977166, 'colsample_bytree': 0.9112642622128366, 'min_child_weight': 6, 'gamma': 2.171134363768538, 'reg_alpha': 0.010047796240015587, 'reg_lambda': 2.537478186087277e-07, 'max_delta_step': 1}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961:  52%|█████▏    | 26/50 [03:57<02:13,  5.54s/it]

[I 2025-12-02 20:27:27,411] Trial 27 pruned.

Best trial: 10. Best value: 0.569961:  54%|█████▍    | 27/50 [04:03<02:07,  5.55s/it]

[I 2025-12-02 20:27:32,961] Trial 21 finished with value: 0.5397946084724006 and parameters: {'max_depth': 4, 'learning_rate': 0.0865827512189401, 'n_estimators': 941, 'subsample': 0.6293658366429151, 'colsample_bytree': 0.9080381363803386, 'min_child_weight': 6, 'gamma': 3.4609154525789085, 'reg_alpha': 0.015376253062123507, 'reg_lambda': 2.810388763947167e-05, 'max_delta_step': 0}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961:  56%|█████▌    | 28/50 [04:05<01:44,  4.74s/it]

[I 2025-12-02 20:27:35,836] Trial 28 pruned.

Best trial: 10. Best value: 0.569961:  58%|█████▊    | 29/50 [04:08<01:25,  4.09s/it]

[I 2025-12-02 20:27:38,387] Trial 29 pruned.

[I 2025-12-02 20:27:42,019] Trial 31 pruned.

Best trial: 10. Best value: 0.569961:  62%|██████▏   | 31/50 [04:12<00:53,  2.82s/it]

[I 2025-12-02 20:27:42,206] Trial 32 pruned.

Best trial: 10. Best value: 0.569961:  64%|██████▍   | 32/50 [04:12<00:38,  2.14s/it]

[I 2025-12-02 20:27:42,739] Trial 30 pruned.

Best trial: 10. Best value: 0.569961:  66%|██████▌   | 33/50 [04:17<00:51,  3.03s/it]

[I 2025-12-02 20:27:47,870] Trial 33 pruned.

Best trial: 10. Best value: 0.569961:  68%|██████▊   | 34/50 [04:20<00:46,  2.93s/it]

[I 2025-12-02 20:27:50,554] Trial 34 pruned.

Best trial: 10. Best value: 0.569961:  70%|███████   | 35/50 [04:21<00:33,  2.25s/it]

[I 2025-12-02 20:27:51,219] Trial 35 pruned.

Best trial: 10. Best value: 0.569961:  72%|███████▏  | 36/50 [04:21<00:23,  1.68s/it]

[I 2025-12-02 20:27:51,581] Trial 24 finished with value: 0.5012836970474968 and parameters: {'max_depth': 6, 'learning_rate': 0.012856371819221139, 'n_estimators': 873, 'subsample': 0.9049155417428034, 'colsample_bytree': 0.9048255237292627, 'min_child_weight': 8, 'gamma': 3.2174747404533894, 'reg_alpha': 2.1248624272283282e-05, 'reg_lambda': 1.1454484703797463e-05, 'max_delta_step': 1}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961:  74%|███████▍  | 37/50 [04:26<00:34,  2.69s/it]

[I 2025-12-02 20:27:56,613] Trial 36 pruned.

Best trial: 10. Best value: 0.569961:  76%|███████▌  | 38/50 [04:29<00:34,  2.85s/it]

[I 2025-12-02 20:27:59,855] Trial 37 pruned.

Best trial: 10. Best value: 0.569961:  78%|███████▊  | 39/50 [04:34<00:35,  3.25s/it]

[I 2025-12-02 20:28:04,036] Trial 41 pruned.

Best trial: 10. Best value: 0.569961:  80%|████████  | 40/50 [04:40<00:43,  4.30s/it]

[I 2025-12-02 20:28:10,798] Trial 40 pruned.

Best trial: 10. Best value: 0.569961:  82%|████████▏ | 41/50 [05:00<01:20,  8.96s/it]

[I 2025-12-02 20:28:30,601] Trial 39 finished with value: 0.5012836970474968 and parameters: {'max_depth': 5, 'learning_rate': 0.019690502695611893, 'n_estimators': 648, 'subsample': 0.7760550747516686, 'colsample_bytree': 0.9386549396067023, 'min_child_weight': 7, 'gamma': 3.9117700068068797, 'reg_alpha': 2.3607721454908954e-06, 'reg_lambda': 0.0033999773512192184, 'max_delta_step': 0}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961:  84%|████████▍ | 42/50 [05:10<01:13,  9.23s/it]

[I 2025-12-02 20:28:40,487] Trial 38 finished with value: 0.5519897304236201 and parameters: {'max_depth': 5, 'learning_rate': 0.01874333410782656, 'n_estimators': 828, 'subsample': 0.6245294916400257, 'colsample_bytree': 0.9439679561634989, 'min_child_weight': 6, 'gamma': 4.033777091116304, 'reg_alpha': 2.5394446324798093e-06, 'reg_lambda': 0.0012527056911023878, 'max_delta_step': 1}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961:  86%|████████▌ | 43/50 [05:20<01:06,  9.44s/it]

[I 2025-12-02 20:28:50,414] Trial 42 finished with value: 0.5519897304236201 and parameters: {'max_depth': 5, 'learning_rate': 0.0172454961257949, 'n_estimators': 805, 'subsample': 0.714895691224338, 'colsample_bytree': 0.9975670524313968, 'min_child_weight': 7, 'gamma': 4.058003740747865, 'reg_alpha': 4.9676723328486795e-06, 'reg_lambda': 1.9076052956272518e-07, 'max_delta_step': 7}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961:  88%|████████▊ | 44/50 [05:22<00:43,  7.19s/it]

[I 2025-12-02 20:28:52,344] Trial 43 finished with value: 0.5539152759948652 and parameters: {'max_depth': 3, 'learning_rate': 0.09469298965248196, 'n_estimators': 808, 'subsample': 0.6594350501376228, 'colsample_bytree': 0.9984549726335731, 'min_child_weight': 7, 'gamma': 4.197065744812647, 'reg_alpha': 5.651980195992881e-08, 'reg_lambda': 0.005518455834713925, 'max_delta_step': 2}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961:  90%|█████████ | 45/50 [05:29<00:36,  7.24s/it]

[I 2025-12-02 20:28:59,701] Trial 47 pruned.

Best trial: 10. Best value: 0.569961:  92%|█████████▏| 46/50 [05:38<00:31,  7.80s/it]

[I 2025-12-02 20:29:08,825] Trial 46 pruned.

Best trial: 10. Best value: 0.569961:  94%|█████████▍| 47/50 [05:52<00:28,  9.63s/it]

[I 2025-12-02 20:29:22,702] Trial 44 finished with value: 0.5641848523748395 and parameters: {'max_depth': 3, 'learning_rate': 0.03193287328367199, 'n_estimators': 793, 'subsample': 0.9894024027026401, 'colsample_bytree': 0.9797991110670491, 'min_child_weight': 6, 'gamma': 2.190103957277178, 'reg_alpha': 0.01150895502167549, 'reg_lambda': 2.463546721595083e-07, 'max_delta_step': 1}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961:  96%|█████████▌| 48/50 [05:57<00:16,  8.21s/it]

[I 2025-12-02 20:29:27,621] Trial 45 finished with value: 0.5012836970474968 and parameters: {'max_depth': 3, 'learning_rate': 0.014970907430953324, 'n_estimators': 805, 'subsample': 0.6639456359201621, 'colsample_bytree': 0.9832316651071149, 'min_child_weight': 6, 'gamma': 4.7933401629476124, 'reg_alpha': 5.562828789026564e-06, 'reg_lambda': 9.938659573648796e-05, 'max_delta_step': 2}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961:  98%|█████████▊| 49/50 [06:07<00:08,  8.54s/it]

[I 2025-12-02 20:29:36,926] Trial 48 finished with value: 0.5134788189987163 and parameters: {'max_depth': 3, 'learning_rate': 0.014939798391268647, 'n_estimators': 796, 'subsample': 0.6641291649470041, 'colsample_bytree': 0.978266280801101, 'min_child_weight': 7, 'gamma': 4.231799414801998, 'reg_alpha': 3.2404629314975314e-07, 'reg_lambda': 0.06744757919270997, 'max_delta_step': 8}. Best is trial 10 with value: 0.5699614890885751.

Best trial: 10. Best value: 0.569961: 100%|██████████| 50/50 [06:10<00:00,  7.40s/it]

[I 2025-12-02 20:29:40,095] Trial 49 finished with value: 0.5256739409499358 and parameters: {'max_depth': 5, 'learning_rate': 0.01648411463549617, 'n_estimators': 738, 'subsample': 0.6619986592249208, 'colsample_bytree': 0.9749395290147826, 'min_child_weight': 7, 'gamma': 4.182307442214945, 'reg_alpha': 4.4042720278928925e-08, 'reg_lambda': 0.0029940705189127424, 'max_delta_step': 8}. Best is trial 10 with value: 0.5699614890885751.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.569961                    0.55          0.58

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.094491               0.6               0.5        50          60

   test_size
0         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.569961                    0.55          0.58

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0  0.094491               0.6               0.5        50          60

   test_size
0         15

In [ ]:

# Temporal embedings
datasets = task_temp_dfs_pd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    #    scoring="balanced_accuracy",     # or "roc_auc"
    scoring="balanced_accuracy",      
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_pd_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_temporal_pd_hc_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param="emb_",
)
print(summary)

[I 2025-12-02 20:29:43,229] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 3. Best value: 0.627086:   2%|▏         | 1/50 [00:22<18:32, 22.70s/it]

[I 2025-12-02 20:30:05,926] Trial 3 finished with value: 0.6270860077021823 and parameters: {'max_depth': 3, 'learning_rate': 0.0711507139722273, 'n_estimators': 231, 'subsample': 0.6475197815285479, 'colsample_bytree': 0.9301822726462365, 'min_child_weight': 3, 'gamma': 1.0728165523244793, 'reg_alpha': 0.001078722160808616, 'reg_lambda': 2.4613185913358144, 'max_delta_step': 8}. Best is trial 3 with value: 0.6270860077021823.

Best trial: 0. Best value: 0.655327:   4%|▍         | 2/50 [00:44<17:42, 22.15s/it]

[I 2025-12-02 20:30:27,678] Trial 0 finished with value: 0.6553273427471117 and parameters: {'max_depth': 8, 'learning_rate': 0.0506309051968922, 'n_estimators': 809, 'subsample': 0.779480726914763, 'colsample_bytree': 0.7902446601943782, 'min_child_weight': 6, 'gamma': 1.2284273573021136, 'reg_alpha': 3.2671921143197876e-08, 'reg_lambda': 2.3965094945282863e-05, 'max_delta_step': 1}. Best is trial 0 with value: 0.6553273427471117.

Best trial: 0. Best value: 0.655327:   6%|▌         | 3/50 [00:50<11:32, 14.74s/it]

[I 2025-12-02 20:30:33,607] Trial 2 finished with value: 0.6431322207958922 and parameters: {'max_depth': 10, 'learning_rate': 0.07833914556713685, 'n_estimators': 1036, 'subsample': 0.6922355791074778, 'colsample_bytree': 0.5492456874959278, 'min_child_weight': 7, 'gamma': 3.805089126718371, 'reg_alpha': 0.7687133928768568, 'reg_lambda': 0.00079290750272817, 'max_delta_step': 5}. Best is trial 0 with value: 0.6553273427471117.

Best trial: 4. Best value: 0.693838:   8%|▊         | 4/50 [01:04<11:00, 14.37s/it]

[I 2025-12-02 20:30:47,402] Trial 4 finished with value: 0.6938382541720154 and parameters: {'max_depth': 3, 'learning_rate': 0.023144838439482895, 'n_estimators': 764, 'subsample': 0.8406198005193499, 'colsample_bytree': 0.6124712719338307, 'min_child_weight': 7, 'gamma': 3.3511440645584574, 'reg_alpha': 2.227633594054613e-07, 'reg_lambda': 1.4387977535883455e-08, 'max_delta_step': 2}. Best is trial 4 with value: 0.6938382541720154.

Best trial: 4. Best value: 0.693838:  10%|█         | 5/50 [01:21<11:31, 15.36s/it]

[I 2025-12-02 20:31:04,519] Trial 6 finished with value: 0.6431322207958922 and parameters: {'max_depth': 7, 'learning_rate': 0.03187399766483786, 'n_estimators': 563, 'subsample': 0.5178658687324991, 'colsample_bytree': 0.6584474543813605, 'min_child_weight': 6, 'gamma': 0.5419619505901241, 'reg_alpha': 0.0005539773415951795, 'reg_lambda': 0.002312834095446619, 'max_delta_step': 1}. Best is trial 4 with value: 0.6938382541720154.

Best trial: 4. Best value: 0.693838:  12%|█▏        | 6/50 [01:28<09:13, 12.58s/it]

[I 2025-12-02 20:31:11,686] Trial 7 finished with value: 0.0 and parameters: {'max_depth': 9, 'learning_rate': 0.014768312350889209, 'n_estimators': 446, 'subsample': 0.8638219352324623, 'colsample_bytree': 0.706101953299741, 'min_child_weight': 10, 'gamma': 1.6443361674876844, 'reg_alpha': 0.3987880227631887, 'reg_lambda': 0.008208160964843404, 'max_delta_step': 8}. Best is trial 4 with value: 0.6938382541720154.

Best trial: 4. Best value: 0.693838:  14%|█▍        | 7/50 [01:34<07:31, 10.51s/it]

[I 2025-12-02 20:31:17,954] Trial 1 finished with value: 0.5905006418485237 and parameters: {'max_depth': 10, 'learning_rate': 0.017022914298208406, 'n_estimators': 1425, 'subsample': 0.6192745636315771, 'colsample_bytree': 0.9164327895418604, 'min_child_weight': 3, 'gamma': 3.891265937979716, 'reg_alpha': 9.9065442438782e-05, 'reg_lambda': 5.186619407880627e-05, 'max_delta_step': 10}. Best is trial 4 with value: 0.6938382541720154.

Best trial: 4. Best value: 0.693838:  16%|█▌        | 8/50 [01:44<07:06, 10.16s/it]

[I 2025-12-02 20:31:27,368] Trial 8 finished with value: 0.4473684210526316 and parameters: {'max_depth': 9, 'learning_rate': 0.015226760939270135, 'n_estimators': 425, 'subsample': 0.5098893871938597, 'colsample_bytree': 0.6615472016169264, 'min_child_weight': 9, 'gamma': 2.2060617959120425, 'reg_alpha': 0.09500947213222107, 'reg_lambda': 0.11321920772961958, 'max_delta_step': 10}. Best is trial 4 with value: 0.6938382541720154.

Best trial: 4. Best value: 0.693838:  18%|█▊        | 9/50 [01:52<06:35,  9.64s/it]

[I 2025-12-02 20:31:35,842] Trial 5 finished with value: 0.6938382541720154 and parameters: {'max_depth': 8, 'learning_rate': 0.16595245970074093, 'n_estimators': 1344, 'subsample': 0.619414228042015, 'colsample_bytree': 0.6890902279444004, 'min_child_weight': 5, 'gamma': 1.1492034852963013, 'reg_alpha': 0.29592260193850767, 'reg_lambda': 1.4277899044524713, 'max_delta_step': 5}. Best is trial 4 with value: 0.6938382541720154.

Best trial: 4. Best value: 0.693838:  20%|██        | 10/50 [02:29<11:58, 17.96s/it]

[I 2025-12-02 20:32:12,424] Trial 10 finished with value: 0.6148908857509627 and parameters: {'max_depth': 4, 'learning_rate': 0.08046073450488699, 'n_estimators': 1059, 'subsample': 0.8940316220498977, 'colsample_bytree': 0.6340578467997973, 'min_child_weight': 5, 'gamma': 1.0407649721760959, 'reg_alpha': 1.1789167146557475e-08, 'reg_lambda': 0.0007258027764702992, 'max_delta_step': 9}. Best is trial 4 with value: 0.6938382541720154.

Best trial: 4. Best value: 0.693838:  22%|██▏       | 11/50 [02:37<09:50, 15.15s/it]

[I 2025-12-02 20:32:21,222] Trial 9 finished with value: 0.6431322207958922 and parameters: {'max_depth': 6, 'learning_rate': 0.012153134453456541, 'n_estimators': 1153, 'subsample': 0.7197424257009809, 'colsample_bytree': 0.9139964894065867, 'min_child_weight': 6, 'gamma': 2.0223661736694454, 'reg_alpha': 1.4911462556897745e-07, 'reg_lambda': 0.6275534071726656, 'max_delta_step': 9}. Best is trial 4 with value: 0.6938382541720154.

Best trial: 4. Best value: 0.693838:  24%|██▍       | 12/50 [02:40<07:13, 11.41s/it]

[I 2025-12-02 20:32:24,091] Trial 11 finished with value: 0.6534017971758665 and parameters: {'max_depth': 7, 'learning_rate': 0.010282742835050186, 'n_estimators': 751, 'subsample': 0.7759914224074288, 'colsample_bytree': 0.5665027676986735, 'min_child_weight': 3, 'gamma': 4.606384877364155, 'reg_alpha': 1.3471218682133408e-07, 'reg_lambda': 1.992691957082033e-07, 'max_delta_step': 5}. Best is trial 4 with value: 0.6938382541720154.

Best trial: 4. Best value: 0.693838:  26%|██▌       | 13/50 [02:41<04:56,  8.02s/it]

[I 2025-12-02 20:32:24,308] Trial 12 finished with value: 0.6534017971758665 and parameters: {'max_depth': 7, 'learning_rate': 0.09696852770098251, 'n_estimators': 950, 'subsample': 0.584899137627475, 'colsample_bytree': 0.704056930904688, 'min_child_weight': 3, 'gamma': 2.3289425679196327, 'reg_alpha': 0.00044674181750572177, 'reg_lambda': 0.005741856521473603, 'max_delta_step': 6}. Best is trial 4 with value: 0.6938382541720154.

Best trial: 4. Best value: 0.693838:  28%|██▊       | 14/50 [02:53<05:31,  9.20s/it]

[I 2025-12-02 20:32:36,236] Trial 15 pruned.

Best trial: 4. Best value: 0.693838:  30%|███       | 15/50 [03:08<06:23, 10.95s/it]

[I 2025-12-02 20:32:51,252] Trial 13 finished with value: 0.6694480102695763 and parameters: {'max_depth': 5, 'learning_rate': 0.03141819149138916, 'n_estimators': 790, 'subsample': 0.9757599326021205, 'colsample_bytree': 0.5011085176935701, 'min_child_weight': 8, 'gamma': 4.5992289999346285, 'reg_alpha': 2.934230772631507e-06, 'reg_lambda': 1.1632531003005152e-08, 'max_delta_step': 3}. Best is trial 4 with value: 0.6938382541720154.

Best trial: 4. Best value: 0.693838:  32%|███▏      | 16/50 [03:20<06:27, 11.39s/it]

[I 2025-12-02 20:33:03,659] Trial 14 pruned.

Best trial: 4. Best value: 0.693838:  34%|███▍      | 17/50 [03:29<05:49, 10.59s/it]

[I 2025-12-02 20:33:12,397] Trial 17 pruned.

Best trial: 4. Best value: 0.693838:  36%|███▌      | 18/50 [03:49<07:16, 13.64s/it]

[I 2025-12-02 20:33:33,113] Trial 16 finished with value: 0.6835686777920411 and parameters: {'max_depth': 5, 'learning_rate': 0.2498103433358714, 'n_estimators': 1471, 'subsample': 0.9682888118556923, 'colsample_bytree': 0.8039241896889385, 'min_child_weight': 8, 'gamma': 3.2985019638987447, 'reg_alpha': 3.5820343110684587e-06, 'reg_lambda': 5.053269973142809e-08, 'max_delta_step': 3}. Best is trial 4 with value: 0.6938382541720154.

Best trial: 4. Best value: 0.693838:  38%|███▊      | 19/50 [03:52<05:17, 10.25s/it]

[I 2025-12-02 20:33:35,487] Trial 19 pruned.

Best trial: 4. Best value: 0.693838:  40%|████      | 20/50 [04:02<05:06, 10.20s/it]

[I 2025-12-02 20:33:45,577] Trial 20 finished with value: 0.6290115532734275 and parameters: {'max_depth': 8, 'learning_rate': 0.14469095739263804, 'n_estimators': 674, 'subsample': 0.8173673344176965, 'colsample_bytree': 0.6119661786040604, 'min_child_weight': 5, 'gamma': 2.900583603814842, 'reg_alpha': 0.025151205515926856, 'reg_lambda': 5.723408230199456e-06, 'max_delta_step': 0}. Best is trial 4 with value: 0.6938382541720154.

Best trial: 4. Best value: 0.693838:  42%|████▏     | 21/50 [04:06<04:05,  8.48s/it]

[I 2025-12-02 20:33:50,029] Trial 21 pruned.

Best trial: 4. Best value: 0.693838:  44%|████▍     | 22/50 [04:29<05:52, 12.60s/it]

[I 2025-12-02 20:34:12,230] Trial 22 finished with value: 0.6431322207958922 and parameters: {'max_depth': 8, 'learning_rate': 0.026757738015130827, 'n_estimators': 626, 'subsample': 0.5683654467512272, 'colsample_bytree': 0.5885617317502716, 'min_child_weight': 4, 'gamma': 2.704187686770402, 'reg_alpha': 0.005098695311770372, 'reg_lambda': 7.127264111210686, 'max_delta_step': 6}. Best is trial 4 with value: 0.6938382541720154.

Best trial: 4. Best value: 0.693838:  46%|████▌     | 23/50 [04:30<04:11,  9.31s/it]

[I 2025-12-02 20:34:13,879] Trial 18 finished with value: 0.6553273427471117 and parameters: {'max_depth': 3, 'learning_rate': 0.18227005714386643, 'n_estimators': 1287, 'subsample': 0.8260561571727462, 'colsample_bytree': 0.5890712172877847, 'min_child_weight': 1, 'gamma': 3.0251894652947096, 'reg_alpha': 0.00944070365723994, 'reg_lambda': 9.480825246788877, 'max_delta_step': 3}. Best is trial 4 with value: 0.6938382541720154.

Best trial: 4. Best value: 0.693838:  48%|████▊     | 24/50 [04:31<02:55,  6.74s/it]

[I 2025-12-02 20:34:14,615] Trial 23 pruned.

Best trial: 4. Best value: 0.693838:  50%|█████     | 25/50 [04:36<02:33,  6.15s/it]

[I 2025-12-02 20:34:19,383] Trial 24 pruned.

Best trial: 4. Best value: 0.693838:  52%|█████▏    | 26/50 [04:41<02:24,  6.03s/it]

[I 2025-12-02 20:34:25,141] Trial 27 pruned.

Best trial: 4. Best value: 0.693838:  54%|█████▍    | 27/50 [04:48<02:24,  6.30s/it]

[I 2025-12-02 20:34:32,074] Trial 28 pruned.

Best trial: 4. Best value: 0.693838:  56%|█████▌    | 28/50 [04:53<02:10,  5.94s/it]

[I 2025-12-02 20:34:37,186] Trial 29 pruned.

Best trial: 4. Best value: 0.693838:  58%|█████▊    | 29/50 [05:01<02:13,  6.35s/it]

[I 2025-12-02 20:34:44,473] Trial 30 pruned.

Best trial: 4. Best value: 0.693838:  60%|██████    | 30/50 [05:02<01:38,  4.91s/it]

[I 2025-12-02 20:34:46,023] Trial 31 pruned.

Best trial: 4. Best value: 0.693838:  62%|██████▏   | 31/50 [05:10<01:50,  5.81s/it]

[I 2025-12-02 20:34:53,950] Trial 33 pruned.

Best trial: 4. Best value: 0.693838:  64%|██████▍   | 32/50 [05:18<01:53,  6.30s/it]

[I 2025-12-02 20:35:01,397] Trial 26 finished with value: 0.6694480102695763 and parameters: {'max_depth': 4, 'learning_rate': 0.26349898940441085, 'n_estimators': 892, 'subsample': 0.7168454727762952, 'colsample_bytree': 0.8423237475344145, 'min_child_weight': 7, 'gamma': 3.95084226188284, 'reg_alpha': 7.355536877729343e-07, 'reg_lambda': 1.1117793046999343e-08, 'max_delta_step': 2}. Best is trial 4 with value: 0.6938382541720154.

Best trial: 4. Best value: 0.693838:  66%|██████▌   | 33/50 [05:18<01:16,  4.51s/it]

[I 2025-12-02 20:35:01,718] Trial 34 pruned.

Best trial: 4. Best value: 0.693838:  68%|██████▊   | 34/50 [05:24<01:17,  4.85s/it]

[I 2025-12-02 20:35:07,361] Trial 32 pruned.

Best trial: 4. Best value: 0.693838:  70%|███████   | 35/50 [05:24<00:52,  3.51s/it]

[I 2025-12-02 20:35:07,758] Trial 35 pruned.

Best trial: 4. Best value: 0.693838:  72%|███████▏  | 36/50 [05:31<01:04,  4.59s/it]

[I 2025-12-02 20:35:14,869] Trial 37 pruned.

Best trial: 4. Best value: 0.693838:  74%|███████▍  | 37/50 [05:34<00:52,  4.04s/it]

[I 2025-12-02 20:35:17,628] Trial 25 finished with value: 0.6450577663671373 and parameters: {'max_depth': 4, 'learning_rate': 0.2990744293841343, 'n_estimators': 1283, 'subsample': 0.9310458958779292, 'colsample_bytree': 0.8680695235197786, 'min_child_weight': 8, 'gamma': 3.761522563786454, 'reg_alpha': 5.379149446519886e-07, 'reg_lambda': 1.09096404590255e-08, 'max_delta_step': 2}. Best is trial 4 with value: 0.6938382541720154.

Best trial: 4. Best value: 0.693838:  78%|███████▊  | 39/50 [05:39<00:33,  3.06s/it]

[I 2025-12-02 20:35:22,549] Trial 36 pruned.
[I 2025-12-02 20:35:22,694] Trial 40 pruned.

Best trial: 4. Best value: 0.693838:  80%|████████  | 40/50 [05:42<00:30,  3.03s/it]

[I 2025-12-02 20:35:25,674] Trial 42 pruned.

Best trial: 41. Best value: 0.695764:  82%|████████▏ | 41/50 [06:05<01:20,  8.95s/it]

[I 2025-12-02 20:35:48,436] Trial 41 finished with value: 0.6957637997432606 and parameters: {'max_depth': 10, 'learning_rate': 0.0658077406390361, 'n_estimators': 404, 'subsample': 0.6168289119950613, 'colsample_bytree': 0.6869456908576461, 'min_child_weight': 6, 'gamma': 0.6411846105930102, 'reg_alpha': 0.00021719959053488434, 'reg_lambda': 0.054210391779810026, 'max_delta_step': 1}. Best is trial 41 with value: 0.6957637997432606.

Best trial: 41. Best value: 0.695764:  84%|████████▍ | 42/50 [06:14<01:11,  8.93s/it]

[I 2025-12-02 20:35:57,316] Trial 44 pruned.

Best trial: 41. Best value: 0.695764:  86%|████████▌ | 43/50 [06:18<00:52,  7.57s/it]

[I 2025-12-02 20:36:01,695] Trial 43 pruned.

Best trial: 41. Best value: 0.695764:  88%|████████▊ | 44/50 [06:19<00:34,  5.67s/it]

[I 2025-12-02 20:36:02,941] Trial 45 pruned.

Best trial: 41. Best value: 0.695764:  90%|█████████ | 45/50 [06:22<00:24,  4.82s/it]

[I 2025-12-02 20:36:05,789] Trial 46 pruned.

Best trial: 41. Best value: 0.695764:  92%|█████████▏| 46/50 [06:23<00:14,  3.59s/it]

[I 2025-12-02 20:36:06,509] Trial 47 pruned.

Best trial: 41. Best value: 0.695764:  94%|█████████▍| 47/50 [06:31<00:14,  4.89s/it]

[I 2025-12-02 20:36:14,440] Trial 39 finished with value: 0.6675224646983312 and parameters: {'max_depth': 10, 'learning_rate': 0.06576910221409484, 'n_estimators': 1097, 'subsample': 0.621313416511625, 'colsample_bytree': 0.7569751169257987, 'min_child_weight': 6, 'gamma': 0.56267940637618, 'reg_alpha': 2.0734518251061487e-08, 'reg_lambda': 5.102600320208296e-08, 'max_delta_step': 1}. Best is trial 41 with value: 0.6957637997432606.

Best trial: 41. Best value: 0.695764:  96%|█████████▌| 48/50 [06:31<00:07,  3.64s/it]

[I 2025-12-02 20:36:15,170] Trial 38 finished with value: 0.6553273427471117 and parameters: {'max_depth': 7, 'learning_rate': 0.019118972381048788, 'n_estimators': 1129, 'subsample': 0.8886993721514367, 'colsample_bytree': 0.6881005725910343, 'min_child_weight': 6, 'gamma': 3.4900991099966543, 'reg_alpha': 0.00016364577734391303, 'reg_lambda': 1.567935927890464e-07, 'max_delta_step': 6}. Best is trial 41 with value: 0.6957637997432606.

Best trial: 41. Best value: 0.695764:  98%|█████████▊| 49/50 [06:35<00:03,  3.55s/it]

[I 2025-12-02 20:36:18,513] Trial 49 pruned.

Best trial: 41. Best value: 0.695764: 100%|██████████| 50/50 [06:41<00:00,  8.03s/it]

[I 2025-12-02 20:36:24,691] Trial 48 finished with value: 0.6816431322207959 and parameters: {'max_depth': 7, 'learning_rate': 0.033236861673585395, 'n_estimators': 532, 'subsample': 0.591422129607235, 'colsample_bytree': 0.5454553712541241, 'min_child_weight': 6, 'gamma': 1.980089015230412, 'reg_alpha': 1.711511500928292e-08, 'reg_lambda': 0.0013670303502096482, 'max_delta_step': 3}. Best is trial 41 with value: 0.6957637997432606.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.695764                     0.5          0.42

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0       0.0               0.4               0.6        50          60

   test_size
0         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.695764                     0.5          0.42

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0       0.0               0.4               0.6        50          60

   test_size
0         15

In [ ]:

# Combined embedings
datasets = task_comb_dfs_pd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_pd_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_combined_pd_hc_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param="emb_",
)
print(summary)

[I 2025-12-02 20:36:29,398] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.677792:   2%|▏         | 1/50 [00:46<38:22, 46.98s/it]

[I 2025-12-02 20:37:16,371] Trial 1 finished with value: 0.6777920410783055 and parameters: {'max_depth': 3, 'learning_rate': 0.2612497126231554, 'n_estimators': 700, 'subsample': 0.6191910829876306, 'colsample_bytree': 0.9669843627512891, 'min_child_weight': 7, 'gamma': 2.274105410955998, 'reg_alpha': 0.001006999849999072, 'reg_lambda': 1.4550266664357538e-06, 'max_delta_step': 0}. Best is trial 1 with value: 0.6777920410783055.

Best trial: 3. Best value: 0.744544:   4%|▍         | 2/50 [01:08<25:27, 31.81s/it]

[I 2025-12-02 20:37:37,568] Trial 3 finished with value: 0.7445442875481387 and parameters: {'max_depth': 3, 'learning_rate': 0.044762794776801604, 'n_estimators': 1111, 'subsample': 0.7229893166529962, 'colsample_bytree': 0.5010654805540995, 'min_child_weight': 6, 'gamma': 3.536190086020061, 'reg_alpha': 0.10689419238446486, 'reg_lambda': 6.638797611710577e-07, 'max_delta_step': 10}. Best is trial 3 with value: 0.7445442875481387.

Best trial: 3. Best value: 0.744544:   6%|▌         | 3/50 [01:20<18:01, 23.01s/it]

[I 2025-12-02 20:37:50,094] Trial 2 finished with value: 0.6392811296534018 and parameters: {'max_depth': 7, 'learning_rate': 0.03727983379832762, 'n_estimators': 1142, 'subsample': 0.7318008046722131, 'colsample_bytree': 0.6967005752102868, 'min_child_weight': 4, 'gamma': 0.22916376089842205, 'reg_alpha': 0.026034145442998004, 'reg_lambda': 9.456027197020594e-08, 'max_delta_step': 5}. Best is trial 3 with value: 0.7445442875481387.

Best trial: 3. Best value: 0.744544:   8%|▊         | 4/50 [01:25<12:07, 15.82s/it]

[I 2025-12-02 20:37:54,890] Trial 0 finished with value: 0.6797175866495507 and parameters: {'max_depth': 9, 'learning_rate': 0.025004508108947776, 'n_estimators': 1190, 'subsample': 0.710854077512107, 'colsample_bytree': 0.9548643367432246, 'min_child_weight': 6, 'gamma': 3.029074666369154, 'reg_alpha': 0.0021809129075839226, 'reg_lambda': 0.05330838353947187, 'max_delta_step': 1}. Best is trial 3 with value: 0.7445442875481387.

Best trial: 3. Best value: 0.744544:  10%|█         | 5/50 [02:18<21:53, 29.20s/it]

[I 2025-12-02 20:38:47,815] Trial 4 finished with value: 0.6919127086007703 and parameters: {'max_depth': 10, 'learning_rate': 0.016606414932695227, 'n_estimators': 1427, 'subsample': 0.9731918689910575, 'colsample_bytree': 0.5192697292561417, 'min_child_weight': 8, 'gamma': 4.195836753107171, 'reg_alpha': 0.9190032717329739, 'reg_lambda': 2.2381460279974226, 'max_delta_step': 5}. Best is trial 3 with value: 0.7445442875481387.

Best trial: 3. Best value: 0.744544:  12%|█▏        | 6/50 [02:20<14:37, 19.94s/it]

[I 2025-12-02 20:38:49,778] Trial 6 finished with value: 0.6919127086007703 and parameters: {'max_depth': 9, 'learning_rate': 0.04748744315819508, 'n_estimators': 621, 'subsample': 0.9903389889112422, 'colsample_bytree': 0.5074999553871165, 'min_child_weight': 2, 'gamma': 1.2835742731192434, 'reg_alpha': 0.0019398248244999086, 'reg_lambda': 3.217566534752479e-07, 'max_delta_step': 6}. Best is trial 3 with value: 0.7445442875481387.

Best trial: 3. Best value: 0.744544:  14%|█▍        | 7/50 [02:34<12:57, 18.08s/it]

[I 2025-12-02 20:39:04,026] Trial 7 finished with value: 0.6270860077021823 and parameters: {'max_depth': 4, 'learning_rate': 0.031556741734206493, 'n_estimators': 870, 'subsample': 0.7807752754012468, 'colsample_bytree': 0.9173980392009043, 'min_child_weight': 5, 'gamma': 1.1885748308865578, 'reg_alpha': 0.003841829173688531, 'reg_lambda': 7.726054806641106e-08, 'max_delta_step': 4}. Best is trial 3 with value: 0.7445442875481387.

Best trial: 3. Best value: 0.744544:  16%|█▌        | 8/50 [03:03<15:03, 21.51s/it]

[I 2025-12-02 20:39:32,886] Trial 10 finished with value: 0.0 and parameters: {'max_depth': 7, 'learning_rate': 0.03216441250997279, 'n_estimators': 479, 'subsample': 0.7622588926700432, 'colsample_bytree': 0.6884717338440551, 'min_child_weight': 10, 'gamma': 2.918960048642859, 'reg_alpha': 1.271760636166185e-07, 'reg_lambda': 3.263730602428173e-07, 'max_delta_step': 6}. Best is trial 3 with value: 0.7445442875481387.

Best trial: 8. Best value: 0.77086:  18%|█▊        | 9/50 [03:11<11:49, 17.31s/it]

[I 2025-12-02 20:39:40,960] Trial 8 finished with value: 0.7708600770218228 and parameters: {'max_depth': 10, 'learning_rate': 0.21052395287375159, 'n_estimators': 941, 'subsample': 0.8743806728090646, 'colsample_bytree': 0.5588142620586665, 'min_child_weight': 6, 'gamma': 4.8695004203982, 'reg_alpha': 1.2112557375318286e-08, 'reg_lambda': 0.001723118858929358, 'max_delta_step': 3}. Best is trial 8 with value: 0.7708600770218228.

Best trial: 8. Best value: 0.77086:  20%|██        | 10/50 [03:42<14:19, 21.48s/it]

[I 2025-12-02 20:40:11,768] Trial 9 finished with value: 0.7041078305519897 and parameters: {'max_depth': 8, 'learning_rate': 0.10351223101344006, 'n_estimators': 1386, 'subsample': 0.8774136286983847, 'colsample_bytree': 0.6996814896733836, 'min_child_weight': 7, 'gamma': 0.22280278484504978, 'reg_alpha': 0.00015440903737281225, 'reg_lambda': 0.023478840378868764, 'max_delta_step': 5}. Best is trial 8 with value: 0.7708600770218228.

Best trial: 8. Best value: 0.77086:  22%|██▏       | 11/50 [03:51<11:29, 17.67s/it]

[I 2025-12-02 20:40:20,802] Trial 11 pruned.

Best trial: 8. Best value: 0.77086:  24%|██▍       | 12/50 [03:54<08:25, 13.30s/it]

[I 2025-12-02 20:40:24,115] Trial 13 pruned.

Best trial: 8. Best value: 0.77086:  26%|██▌       | 13/50 [03:56<06:00,  9.75s/it]

[I 2025-12-02 20:40:25,674] Trial 14 pruned.

Best trial: 8. Best value: 0.77086:  28%|██▊       | 14/50 [04:10<06:36, 11.02s/it]

[I 2025-12-02 20:40:39,644] Trial 15 pruned.

Best trial: 8. Best value: 0.77086:  30%|███       | 15/50 [04:11<04:41,  8.05s/it]

[I 2025-12-02 20:40:40,798] Trial 16 pruned.

Best trial: 8. Best value: 0.77086:  32%|███▏      | 16/50 [04:25<05:30,  9.72s/it]

[I 2025-12-02 20:40:54,405] Trial 18 pruned.

Best trial: 8. Best value: 0.77086:  34%|███▍      | 17/50 [04:33<05:04,  9.21s/it]

[I 2025-12-02 20:41:02,439] Trial 19 pruned.

Best trial: 8. Best value: 0.77086:  36%|███▌      | 18/50 [04:45<05:28, 10.26s/it]

[I 2025-12-02 20:41:15,157] Trial 12 finished with value: 0.7182284980744544 and parameters: {'max_depth': 10, 'learning_rate': 0.03567925835649969, 'n_estimators': 1469, 'subsample': 0.8582270498668672, 'colsample_bytree': 0.5651810956805869, 'min_child_weight': 8, 'gamma': 3.376932125537241, 'reg_alpha': 1.9251627668802678e-05, 'reg_lambda': 0.008517785804748126, 'max_delta_step': 7}. Best is trial 8 with value: 0.7708600770218228.

Best trial: 8. Best value: 0.77086:  38%|███▊      | 19/50 [04:48<04:05,  7.93s/it]

[I 2025-12-02 20:41:17,632] Trial 5 finished with value: 0.689987163029525 and parameters: {'max_depth': 9, 'learning_rate': 0.01355253165217986, 'n_estimators': 1390, 'subsample': 0.8062525663034155, 'colsample_bytree': 0.8061054546048355, 'min_child_weight': 1, 'gamma': 2.60098841905896, 'reg_alpha': 1.2867142186778293, 'reg_lambda': 8.298851150937095e-07, 'max_delta_step': 8}. Best is trial 8 with value: 0.7708600770218228.

Best trial: 8. Best value: 0.77086:  40%|████      | 20/50 [04:59<04:31,  9.04s/it]

[I 2025-12-02 20:41:29,278] Trial 21 pruned.

Best trial: 17. Best value: 0.78113:  42%|████▏     | 21/50 [05:27<07:04, 14.63s/it]

[I 2025-12-02 20:41:56,927] Trial 17 finished with value: 0.7811296534017972 and parameters: {'max_depth': 10, 'learning_rate': 0.1258201740647919, 'n_estimators': 1226, 'subsample': 0.638899874430912, 'colsample_bytree': 0.8431769828265414, 'min_child_weight': 6, 'gamma': 3.56201466620292, 'reg_alpha': 5.910378655986575e-06, 'reg_lambda': 6.405171943808915e-06, 'max_delta_step': 3}. Best is trial 17 with value: 0.7811296534017972.

Best trial: 17. Best value: 0.78113:  44%|████▍     | 22/50 [05:38<06:16, 13.45s/it]

[I 2025-12-02 20:42:07,628] Trial 24 pruned.

Best trial: 17. Best value: 0.78113:  46%|████▌     | 23/50 [05:52<06:08, 13.65s/it]

[I 2025-12-02 20:42:21,748] Trial 20 finished with value: 0.6919127086007703 and parameters: {'max_depth': 8, 'learning_rate': 0.1641929052828059, 'n_estimators': 1294, 'subsample': 0.8208199329069092, 'colsample_bytree': 0.8019797881359074, 'min_child_weight': 8, 'gamma': 3.5935577957363583, 'reg_alpha': 2.9183769971972515e-05, 'reg_lambda': 4.032929959004113e-06, 'max_delta_step': 3}. Best is trial 17 with value: 0.7811296534017972.

Best trial: 17. Best value: 0.78113:  48%|████▊     | 24/50 [05:59<05:00, 11.56s/it]

[I 2025-12-02 20:42:28,435] Trial 23 finished with value: 0.6919127086007703 and parameters: {'max_depth': 5, 'learning_rate': 0.16251521220455742, 'n_estimators': 978, 'subsample': 0.9405405310028426, 'colsample_bytree': 0.639488456664024, 'min_child_weight': 8, 'gamma': 1.6962228914805297, 'reg_alpha': 3.952477188481252e-07, 'reg_lambda': 0.0012609406451076065, 'max_delta_step': 2}. Best is trial 17 with value: 0.7811296534017972.

Best trial: 17. Best value: 0.78113:  50%|█████     | 25/50 [06:03<03:54,  9.37s/it]

[I 2025-12-02 20:42:32,682] Trial 22 finished with value: 0.7445442875481387 and parameters: {'max_depth': 8, 'learning_rate': 0.17801262752752872, 'n_estimators': 1270, 'subsample': 0.5239616264028326, 'colsample_bytree': 0.5015201921591511, 'min_child_weight': 4, 'gamma': 4.091232648125169, 'reg_alpha': 0.06162453077567327, 'reg_lambda': 0.0016478027175479007, 'max_delta_step': 3}. Best is trial 17 with value: 0.7811296534017972.

Best trial: 17. Best value: 0.78113:  52%|█████▏    | 26/50 [06:12<03:44,  9.33s/it]

[I 2025-12-02 20:42:41,934] Trial 27 pruned.

Best trial: 17. Best value: 0.78113:  54%|█████▍    | 27/50 [06:17<03:07,  8.17s/it]

[I 2025-12-02 20:42:47,390] Trial 28 pruned.

Best trial: 17. Best value: 0.78113:  56%|█████▌    | 28/50 [06:22<02:38,  7.21s/it]

[I 2025-12-02 20:42:52,348] Trial 29 pruned.

Best trial: 17. Best value: 0.78113:  58%|█████▊    | 29/50 [06:27<02:14,  6.39s/it]

[I 2025-12-02 20:42:56,845] Trial 30 pruned.

Best trial: 17. Best value: 0.78113:  60%|██████    | 30/50 [06:31<01:55,  5.77s/it]

[I 2025-12-02 20:43:01,151] Trial 31 pruned.

Best trial: 17. Best value: 0.78113:  62%|██████▏   | 31/50 [06:47<02:45,  8.69s/it]

[I 2025-12-02 20:43:16,663] Trial 32 pruned.

Best trial: 17. Best value: 0.78113:  64%|██████▍   | 32/50 [07:01<03:04, 10.25s/it]

[I 2025-12-02 20:43:30,544] Trial 34 pruned.

Best trial: 17. Best value: 0.78113:  66%|██████▌   | 33/50 [07:06<02:28,  8.73s/it]

[I 2025-12-02 20:43:35,728] Trial 25 finished with value: 0.7182284980744544 and parameters: {'max_depth': 9, 'learning_rate': 0.08262920691976251, 'n_estimators': 1234, 'subsample': 0.6752124746019021, 'colsample_bytree': 0.884628764351227, 'min_child_weight': 5, 'gamma': 3.997616236382908, 'reg_alpha': 4.013549161492845e-07, 'reg_lambda': 3.440329197970847e-06, 'max_delta_step': 3}. Best is trial 17 with value: 0.7811296534017972.

Best trial: 17. Best value: 0.78113:  68%|██████▊   | 34/50 [07:13<02:12,  8.27s/it]

[I 2025-12-02 20:43:42,933] Trial 26 finished with value: 0.730423620025674 and parameters: {'max_depth': 10, 'learning_rate': 0.08280288457834892, 'n_estimators': 1125, 'subsample': 0.6862758771961565, 'colsample_bytree': 0.8915565776273398, 'min_child_weight': 5, 'gamma': 4.438827354505337, 'reg_alpha': 3.196955996158248e-07, 'reg_lambda': 0.0007823935339647955, 'max_delta_step': 4}. Best is trial 17 with value: 0.7811296534017972.

Best trial: 17. Best value: 0.78113:  70%|███████   | 35/50 [08:10<05:42, 22.80s/it]

[I 2025-12-02 20:44:39,651] Trial 36 finished with value: 0.7426187419768935 and parameters: {'max_depth': 10, 'learning_rate': 0.12764693982089986, 'n_estimators': 1068, 'subsample': 0.7213082113609655, 'colsample_bytree': 0.5029488496972189, 'min_child_weight': 4, 'gamma': 3.28529976371548, 'reg_alpha': 0.025090839319389793, 'reg_lambda': 0.0003437265712610196, 'max_delta_step': 4}. Best is trial 17 with value: 0.7811296534017972.

Best trial: 17. Best value: 0.78113:  72%|███████▏  | 36/50 [08:13<03:57, 16.95s/it]

[I 2025-12-02 20:44:42,924] Trial 35 finished with value: 0.7567394094993581 and parameters: {'max_depth': 9, 'learning_rate': 0.13863576189843513, 'n_estimators': 1226, 'subsample': 0.7210605760871283, 'colsample_bytree': 0.5040058136889424, 'min_child_weight': 6, 'gamma': 3.2823857016385314, 'reg_alpha': 0.0004776479567691209, 'reg_lambda': 0.0006970079275262997, 'max_delta_step': 4}. Best is trial 17 with value: 0.7811296534017972.

Best trial: 17. Best value: 0.78113:  74%|███████▍  | 37/50 [08:22<03:09, 14.61s/it]

[I 2025-12-02 20:44:52,070] Trial 38 pruned.

Best trial: 17. Best value: 0.78113:  76%|███████▌  | 38/50 [08:24<02:08, 10.67s/it]

[I 2025-12-02 20:44:53,544] Trial 37 finished with value: 0.7426187419768935 and parameters: {'max_depth': 9, 'learning_rate': 0.22124611742603903, 'n_estimators': 1192, 'subsample': 0.7242564418618758, 'colsample_bytree': 0.501392371276992, 'min_child_weight': 4, 'gamma': 4.980816637273256, 'reg_alpha': 0.026983815971850508, 'reg_lambda': 0.029620792588100492, 'max_delta_step': 2}. Best is trial 17 with value: 0.7811296534017972.

Best trial: 17. Best value: 0.78113:  78%|███████▊  | 39/50 [08:29<01:40,  9.14s/it]

[I 2025-12-02 20:44:59,122] Trial 33 finished with value: 0.7426187419768935 and parameters: {'max_depth': 9, 'learning_rate': 0.023397151184635936, 'n_estimators': 1200, 'subsample': 0.7228789550125745, 'colsample_bytree': 0.9948729072904705, 'min_child_weight': 3, 'gamma': 3.2071507510115813, 'reg_alpha': 0.009882653401125638, 'reg_lambda': 1.5319156552652463e-08, 'max_delta_step': 1}. Best is trial 17 with value: 0.7811296534017972.

Best trial: 17. Best value: 0.78113:  80%|████████  | 40/50 [08:39<01:34,  9.45s/it]

[I 2025-12-02 20:45:09,293] Trial 42 pruned.

Best trial: 17. Best value: 0.78113:  82%|████████▏ | 41/50 [08:53<01:36, 10.78s/it]

[I 2025-12-02 20:45:23,166] Trial 43 pruned.

Best trial: 17. Best value: 0.78113:  84%|████████▍ | 42/50 [09:09<01:37, 12.16s/it]

[I 2025-12-02 20:45:38,542] Trial 44 pruned.

Best trial: 17. Best value: 0.78113:  86%|████████▌ | 43/50 [09:20<01:24, 12.01s/it]

[I 2025-12-02 20:45:50,210] Trial 45 pruned.

Best trial: 17. Best value: 0.78113:  88%|████████▊ | 44/50 [09:27<01:03, 10.53s/it]

[I 2025-12-02 20:45:57,284] Trial 40 finished with value: 0.7182284980744544 and parameters: {'max_depth': 9, 'learning_rate': 0.04236433638665457, 'n_estimators': 934, 'subsample': 0.7414996033294922, 'colsample_bytree': 0.6314694008525208, 'min_child_weight': 6, 'gamma': 2.0649279884784653, 'reg_alpha': 0.00045184126905753095, 'reg_lambda': 5.566965479383704e-08, 'max_delta_step': 6}. Best is trial 17 with value: 0.7811296534017972.

Best trial: 17. Best value: 0.78113:  90%|█████████ | 45/50 [09:40<00:55, 11.12s/it]

[I 2025-12-02 20:46:09,800] Trial 39 finished with value: 0.7426187419768935 and parameters: {'max_depth': 9, 'learning_rate': 0.22910293598053802, 'n_estimators': 1391, 'subsample': 0.7407394596432887, 'colsample_bytree': 0.5383602596142264, 'min_child_weight': 6, 'gamma': 2.5790876868203165, 'reg_alpha': 0.00027190680598409574, 'reg_lambda': 0.012290289817599595, 'max_delta_step': 6}. Best is trial 17 with value: 0.7811296534017972.

Best trial: 17. Best value: 0.78113:  92%|█████████▏| 46/50 [09:49<00:41, 10.49s/it]

[I 2025-12-02 20:46:18,809] Trial 41 finished with value: 0.730423620025674 and parameters: {'max_depth': 10, 'learning_rate': 0.14259857720094715, 'n_estimators': 1361, 'subsample': 0.9257429637234906, 'colsample_bytree': 0.6258826950542901, 'min_child_weight': 6, 'gamma': 2.2822427585434513, 'reg_alpha': 0.00037435882760971447, 'reg_lambda': 4.003995258274723e-08, 'max_delta_step': 6}. Best is trial 17 with value: 0.7811296534017972.

Best trial: 17. Best value: 0.78113:  94%|█████████▍| 47/50 [09:54<00:26,  8.94s/it]

[I 2025-12-02 20:46:24,128] Trial 48 pruned.

Best trial: 17. Best value: 0.78113:  96%|█████████▌| 48/50 [10:30<00:34, 17.13s/it]

[I 2025-12-02 20:47:00,372] Trial 46 finished with value: 0.6797175866495507 and parameters: {'max_depth': 9, 'learning_rate': 0.10091384582163192, 'n_estimators': 1334, 'subsample': 0.8365893323031671, 'colsample_bytree': 0.5210643230175712, 'min_child_weight': 6, 'gamma': 4.351295553281243, 'reg_alpha': 0.005433506219814965, 'reg_lambda': 0.00037501786753629373, 'max_delta_step': 4}. Best is trial 17 with value: 0.7811296534017972.

Best trial: 17. Best value: 0.78113:  98%|█████████▊| 49/50 [10:38<00:14, 14.29s/it]

[I 2025-12-02 20:47:08,040] Trial 47 finished with value: 0.7426187419768935 and parameters: {'max_depth': 8, 'learning_rate': 0.09809018358723803, 'n_estimators': 1483, 'subsample': 0.8410591225444952, 'colsample_bytree': 0.5195158221011894, 'min_child_weight': 8, 'gamma': 0.7513909650712427, 'reg_alpha': 4.794274646597162e-05, 'reg_lambda': 0.0003568141606496023, 'max_delta_step': 4}. Best is trial 17 with value: 0.7811296534017972.

Best trial: 17. Best value: 0.78113: 100%|██████████| 50/50 [10:50<00:00, 13.00s/it]

[I 2025-12-02 20:47:19,498] Trial 49 finished with value: 0.7708600770218228 and parameters: {'max_depth': 7, 'learning_rate': 0.19234786096642909, 'n_estimators': 1459, 'subsample': 0.5412516148082142, 'colsample_bytree': 0.5173929416544993, 'min_child_weight': 5, 'gamma': 4.734554071740785, 'reg_alpha': 0.003966010289555688, 'reg_lambda': 6.988600973148406e-07, 'max_delta_step': 4}. Best is trial 17 with value: 0.7811296534017972.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo        0.78113                    0.35           0.5

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.288675               0.4               0.3        50          60

   test_size
0         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo        0.78113                    0.35           0.5

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.288675               0.4               0.3        50          60

   test_size
0         15

In [ ]:

datasets = task_hf_dfs_clean_pd_hc

summary, models, studies = optimize_many(
    datasets,
    x_y_split_fn=x_y_split,          # your splitter
    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="roc_auc",    
    n_trials=NUM_TRIALS,
    cv_strategy=CV_STRATEGY,
    output_dir=f"xgb_pd_hc_{CV_STRATEGY}_tasks_{TASK_SET}/xgb_results_handcrafted_pd_hc_extended_{CV_STRATEGY}_tasks_{TASK_SET}",
    split_param="w.cz.fnusa",
)
print(summary)

[I 2025-12-02 20:47:23,472] A new study created in memory with name: 16_1_balanced_accuracy

============================================================
Processing dataset: 16_1
============================================================
Train size: 60, Test size: 15
Using Leave-One-Out CV with 60 folds
Starting optimization with 50 trials...

Best trial: 1. Best value: 0.784981:   2%|▏         | 1/50 [00:18<14:52, 18.21s/it]

[I 2025-12-02 20:47:41,669] Trial 1 finished with value: 0.7849807445442876 and parameters: {'max_depth': 4, 'learning_rate': 0.1581534674598974, 'n_estimators': 290, 'subsample': 0.9514494136005898, 'colsample_bytree': 0.8299489350571772, 'min_child_weight': 6, 'gamma': 2.39173807288368, 'reg_alpha': 1.4045660443525396e-07, 'reg_lambda': 2.24600210818503, 'max_delta_step': 2}. Best is trial 1 with value: 0.7849807445442876.

Best trial: 1. Best value: 0.784981:   4%|▍         | 2/50 [00:52<22:09, 27.71s/it]

[I 2025-12-02 20:48:16,021] Trial 3 finished with value: 0.02631578947368421 and parameters: {'max_depth': 6, 'learning_rate': 0.042033586528552325, 'n_estimators': 936, 'subsample': 0.6342750957292583, 'colsample_bytree': 0.8053482262810023, 'min_child_weight': 10, 'gamma': 3.7661444078940165, 'reg_alpha': 0.06596984793251402, 'reg_lambda': 1.0569479707693678e-06, 'max_delta_step': 8}. Best is trial 1 with value: 0.7849807445442876.

Best trial: 1. Best value: 0.784981:   6%|▌         | 3/50 [01:10<18:19, 23.39s/it]

[I 2025-12-02 20:48:34,285] Trial 0 finished with value: 0.0 and parameters: {'max_depth': 6, 'learning_rate': 0.010277597365450399, 'n_estimators': 1298, 'subsample': 0.7877450470445861, 'colsample_bytree': 0.5615879142503419, 'min_child_weight': 10, 'gamma': 0.9354130121266763, 'reg_alpha': 1.755739343426313e-08, 'reg_lambda': 1.7194778446265065e-05, 'max_delta_step': 6}. Best is trial 1 with value: 0.7849807445442876.

Best trial: 1. Best value: 0.784981:   8%|▊         | 4/50 [01:17<12:46, 16.65s/it]

[I 2025-12-02 20:48:40,601] Trial 2 finished with value: 0.42105263157894735 and parameters: {'max_depth': 6, 'learning_rate': 0.18060928703264859, 'n_estimators': 1430, 'subsample': 0.5495865704738024, 'colsample_bytree': 0.7385568072261017, 'min_child_weight': 8, 'gamma': 3.1953701320482812, 'reg_alpha': 6.068479768246449, 'reg_lambda': 4.129504930496254e-08, 'max_delta_step': 6}. Best is trial 1 with value: 0.7849807445442876.

Best trial: 1. Best value: 0.784981:  10%|█         | 5/50 [01:19<08:29, 11.33s/it]

[I 2025-12-02 20:48:42,501] Trial 4 finished with value: 0.7079589216944802 and parameters: {'max_depth': 3, 'learning_rate': 0.2294448363894479, 'n_estimators': 1114, 'subsample': 0.6793517825851983, 'colsample_bytree': 0.6731009138407285, 'min_child_weight': 4, 'gamma': 0.23375957973390316, 'reg_alpha': 0.0005438421028616683, 'reg_lambda': 0.00038133414378228864, 'max_delta_step': 6}. Best is trial 1 with value: 0.7849807445442876.

Best trial: 1. Best value: 0.784981:  12%|█▏        | 6/50 [01:29<08:01, 10.95s/it]

[I 2025-12-02 20:48:52,703] Trial 5 finished with value: 0.754813863928113 and parameters: {'max_depth': 4, 'learning_rate': 0.13871119621807237, 'n_estimators': 626, 'subsample': 0.8417014279381796, 'colsample_bytree': 0.6258458944209648, 'min_child_weight': 1, 'gamma': 3.5509841148298324, 'reg_alpha': 1.7790335334445248e-06, 'reg_lambda': 1.4305768756619089e-05, 'max_delta_step': 0}. Best is trial 1 with value: 0.7849807445442876.

Best trial: 1. Best value: 0.784981:  14%|█▍        | 7/50 [01:32<06:08,  8.58s/it]

[I 2025-12-02 20:48:56,408] Trial 7 finished with value: 0.7586649550706033 and parameters: {'max_depth': 9, 'learning_rate': 0.16094457000566387, 'n_estimators': 268, 'subsample': 0.6876263104709872, 'colsample_bytree': 0.9289147528576138, 'min_child_weight': 5, 'gamma': 0.34092243436953384, 'reg_alpha': 0.3191871337100856, 'reg_lambda': 0.00026322170575586717, 'max_delta_step': 9}. Best is trial 1 with value: 0.7849807445442876.

Best trial: 1. Best value: 0.784981:  16%|█▌        | 8/50 [01:39<05:31,  7.89s/it]

[I 2025-12-02 20:49:02,835] Trial 8 finished with value: 0.7708600770218228 and parameters: {'max_depth': 10, 'learning_rate': 0.014993018447634527, 'n_estimators': 349, 'subsample': 0.8004484507265095, 'colsample_bytree': 0.5200928962063509, 'min_child_weight': 9, 'gamma': 2.0962678683936935, 'reg_alpha': 0.5392786492055934, 'reg_lambda': 2.6480129597843595e-07, 'max_delta_step': 3}. Best is trial 1 with value: 0.7849807445442876.

Best trial: 1. Best value: 0.784981:  18%|█▊        | 9/50 [01:42<04:28,  6.54s/it]

[I 2025-12-02 20:49:06,401] Trial 9 finished with value: 0.0 and parameters: {'max_depth': 5, 'learning_rate': 0.06014443276413847, 'n_estimators': 219, 'subsample': 0.6142171336214641, 'colsample_bytree': 0.7504327990211175, 'min_child_weight': 9, 'gamma': 2.672548033348524, 'reg_alpha': 9.1965298809298, 'reg_lambda': 3.096410890681623e-08, 'max_delta_step': 9}. Best is trial 1 with value: 0.7849807445442876.

Best trial: 11. Best value: 0.809371:  20%|██        | 10/50 [02:19<10:30, 15.77s/it]

[I 2025-12-02 20:49:42,824] Trial 11 finished with value: 0.8093709884467266 and parameters: {'max_depth': 3, 'learning_rate': 0.0981995043289313, 'n_estimators': 698, 'subsample': 0.8967648543016078, 'colsample_bytree': 0.5262405261712566, 'min_child_weight': 1, 'gamma': 4.958190639264844, 'reg_alpha': 0.03629684666395586, 'reg_lambda': 7.37543419568536e-05, 'max_delta_step': 9}. Best is trial 11 with value: 0.8093709884467266.

Best trial: 11. Best value: 0.809371:  22%|██▏       | 11/50 [02:23<07:56, 12.23s/it]

[I 2025-12-02 20:49:47,027] Trial 6 finished with value: 0.7830551989730423 and parameters: {'max_depth': 10, 'learning_rate': 0.08078631122154044, 'n_estimators': 1344, 'subsample': 0.7183486162941617, 'colsample_bytree': 0.9145716118900444, 'min_child_weight': 3, 'gamma': 3.638666314490151, 'reg_alpha': 5.244745247557611e-07, 'reg_lambda': 6.652817533693959e-06, 'max_delta_step': 2}. Best is trial 11 with value: 0.8093709884467266.

Best trial: 10. Best value: 0.811297:  24%|██▍       | 12/50 [02:33<07:20, 11.58s/it]

[I 2025-12-02 20:49:57,142] Trial 10 finished with value: 0.8112965340179717 and parameters: {'max_depth': 4, 'learning_rate': 0.016412454962940772, 'n_estimators': 1119, 'subsample': 0.8175221329079041, 'colsample_bytree': 0.65509639709056, 'min_child_weight': 7, 'gamma': 1.8101389397295986, 'reg_alpha': 1.7090124950497518, 'reg_lambda': 0.0005638432744276924, 'max_delta_step': 3}. Best is trial 10 with value: 0.8112965340179717.

Best trial: 10. Best value: 0.811297:  26%|██▌       | 13/50 [02:46<07:28, 12.11s/it]

[I 2025-12-02 20:50:10,459] Trial 12 finished with value: 0.7586649550706033 and parameters: {'max_depth': 10, 'learning_rate': 0.1643727074451126, 'n_estimators': 1209, 'subsample': 0.5053881284490641, 'colsample_bytree': 0.5492317149781212, 'min_child_weight': 5, 'gamma': 0.2072306715466632, 'reg_alpha': 0.46413200648895614, 'reg_lambda': 2.856414319315032e-07, 'max_delta_step': 4}. Best is trial 10 with value: 0.8112965340179717.

Best trial: 14. Best value: 0.837612:  28%|██▊       | 14/50 [02:55<06:36, 11.03s/it]

[I 2025-12-02 20:50:18,981] Trial 14 finished with value: 0.8376123234916559 and parameters: {'max_depth': 3, 'learning_rate': 0.09194223586299138, 'n_estimators': 577, 'subsample': 0.9894230649970498, 'colsample_bytree': 0.8399875706647131, 'min_child_weight': 7, 'gamma': 4.836321324608671, 'reg_alpha': 0.0018262223610531324, 'reg_lambda': 2.8402127791859613, 'max_delta_step': 4}. Best is trial 14 with value: 0.8376123234916559.

Best trial: 14. Best value: 0.837612:  30%|███       | 15/50 [02:59<05:13,  8.96s/it]

[I 2025-12-02 20:50:23,137] Trial 13 finished with value: 0.7952503209242618 and parameters: {'max_depth': 8, 'learning_rate': 0.06127151642481242, 'n_estimators': 671, 'subsample': 0.9714525065520636, 'colsample_bytree': 0.9767873709517405, 'min_child_weight': 1, 'gamma': 4.923045320670873, 'reg_alpha': 0.0011908336570337372, 'reg_lambda': 0.05556005908766138, 'max_delta_step': 10}. Best is trial 14 with value: 0.8376123234916559.

Best trial: 14. Best value: 0.837612:  32%|███▏      | 16/50 [03:00<03:40,  6.49s/it]

[I 2025-12-02 20:50:23,882] Trial 16 pruned.

Best trial: 14. Best value: 0.837612:  34%|███▍      | 17/50 [03:13<04:37,  8.42s/it]

[I 2025-12-02 20:50:36,816] Trial 15 finished with value: 0.7849807445442876 and parameters: {'max_depth': 3, 'learning_rate': 0.028159390324160073, 'n_estimators': 717, 'subsample': 0.9136753007615978, 'colsample_bytree': 0.6104507904643961, 'min_child_weight': 7, 'gamma': 4.488207913832524, 'reg_alpha': 0.003742209178964741, 'reg_lambda': 0.009476106634105088, 'max_delta_step': 4}. Best is trial 14 with value: 0.8376123234916559.

Best trial: 14. Best value: 0.837612:  36%|███▌      | 18/50 [03:16<03:38,  6.82s/it]

[I 2025-12-02 20:50:39,917] Trial 18 pruned.

Best trial: 14. Best value: 0.837612:  38%|███▊      | 19/50 [03:35<05:28, 10.60s/it]

[I 2025-12-02 20:50:59,327] Trial 21 pruned.

Best trial: 14. Best value: 0.837612:  40%|████      | 20/50 [03:47<05:30, 11.03s/it]

[I 2025-12-02 20:51:11,337] Trial 17 finished with value: 0.8254172015404364 and parameters: {'max_depth': 8, 'learning_rate': 0.030089610513243634, 'n_estimators': 948, 'subsample': 0.9685807926771626, 'colsample_bytree': 0.8554493372054575, 'min_child_weight': 7, 'gamma': 1.5260069039618214, 'reg_alpha': 0.0007930967255564744, 'reg_lambda': 5.244920848716964, 'max_delta_step': 0}. Best is trial 14 with value: 0.8376123234916559.

Best trial: 14. Best value: 0.837612:  42%|████▏     | 21/50 [03:53<04:31,  9.37s/it]

[I 2025-12-02 20:51:16,845] Trial 19 finished with value: 0.8112965340179717 and parameters: {'max_depth': 4, 'learning_rate': 0.022402608711475234, 'n_estimators': 931, 'subsample': 0.8705474962112587, 'colsample_bytree': 0.8466874793643393, 'min_child_weight': 7, 'gamma': 1.242563637612432, 'reg_alpha': 3.383731402297385e-05, 'reg_lambda': 4.835787098959805, 'max_delta_step': 0}. Best is trial 14 with value: 0.8376123234916559.

Best trial: 14. Best value: 0.837612:  44%|████▍     | 22/50 [04:05<04:47, 10.27s/it]

[I 2025-12-02 20:51:29,227] Trial 22 finished with value: 0.7971758664955071 and parameters: {'max_depth': 7, 'learning_rate': 0.2881480092605233, 'n_estimators': 532, 'subsample': 0.8673198305019767, 'colsample_bytree': 0.7393598906169214, 'min_child_weight': 3, 'gamma': 2.8762699301784007, 'reg_alpha': 1.032230553076964e-05, 'reg_lambda': 0.49905383468870906, 'max_delta_step': 5}. Best is trial 14 with value: 0.8376123234916559.

Best trial: 14. Best value: 0.837612:  46%|████▌     | 23/50 [04:07<03:27,  7.70s/it]

[I 2025-12-02 20:51:30,925] Trial 20 finished with value: 0.8112965340179717 and parameters: {'max_depth': 5, 'learning_rate': 0.020860721136513292, 'n_estimators': 978, 'subsample': 0.8555966974522871, 'colsample_bytree': 0.8436587016950574, 'min_child_weight': 7, 'gamma': 1.5392010013765216, 'reg_alpha': 1.7641347493780965e-05, 'reg_lambda': 9.637772790440481, 'max_delta_step': 0}. Best is trial 14 with value: 0.8376123234916559.

Best trial: 14. Best value: 0.837612:  48%|████▊     | 24/50 [04:17<03:36,  8.31s/it]

[I 2025-12-02 20:51:40,653] Trial 23 finished with value: 0.8112965340179717 and parameters: {'max_depth': 8, 'learning_rate': 0.2879371324151761, 'n_estimators': 497, 'subsample': 0.8737946774275476, 'colsample_bytree': 0.8837190845740702, 'min_child_weight': 4, 'gamma': 2.8873939059908325, 'reg_alpha': 1.5940164496722423e-05, 'reg_lambda': 0.2525396917749068, 'max_delta_step': 0}. Best is trial 14 with value: 0.8376123234916559.

Best trial: 24. Best value: 0.849807:  50%|█████     | 25/50 [04:21<02:55,  7.01s/it]

[I 2025-12-02 20:51:44,632] Trial 24 finished with value: 0.8498074454428755 and parameters: {'max_depth': 8, 'learning_rate': 0.04139544530028549, 'n_estimators': 481, 'subsample': 0.9984323687308887, 'colsample_bytree': 0.759330957974263, 'min_child_weight': 9, 'gamma': 1.8922439274191336, 'reg_alpha': 0.017328777129291276, 'reg_lambda': 0.3702258122674578, 'max_delta_step': 1}. Best is trial 24 with value: 0.8498074454428755.

Best trial: 24. Best value: 0.849807:  52%|█████▏    | 26/50 [04:35<03:39,  9.16s/it]

[I 2025-12-02 20:51:58,818] Trial 26 finished with value: 0.8376123234916559 and parameters: {'max_depth': 8, 'learning_rate': 0.044155757090657326, 'n_estimators': 481, 'subsample': 0.9946001104466228, 'colsample_bytree': 0.9046099565348187, 'min_child_weight': 8, 'gamma': 1.893463597564243, 'reg_alpha': 0.013896817022620503, 'reg_lambda': 0.35606161439810907, 'max_delta_step': 1}. Best is trial 24 with value: 0.8498074454428755.

Best trial: 24. Best value: 0.849807:  54%|█████▍    | 27/50 [04:36<02:34,  6.71s/it]

[I 2025-12-02 20:51:59,813] Trial 25 finished with value: 0.8376123234916559 and parameters: {'max_depth': 8, 'learning_rate': 0.012203829141759999, 'n_estimators': 510, 'subsample': 0.9924560672860143, 'colsample_bytree': 0.9030129797081978, 'min_child_weight': 8, 'gamma': 1.9376296618885807, 'reg_alpha': 0.022859761847401214, 'reg_lambda': 0.24559276967490604, 'max_delta_step': 1}. Best is trial 24 with value: 0.8498074454428755.

Best trial: 24. Best value: 0.849807:  56%|█████▌    | 28/50 [04:47<02:54,  7.94s/it]

[I 2025-12-02 20:52:10,615] Trial 28 finished with value: 0.8498074454428755 and parameters: {'max_depth': 8, 'learning_rate': 0.04644177167495098, 'n_estimators': 454, 'subsample': 0.9886282318379052, 'colsample_bytree': 0.7928597081895784, 'min_child_weight': 9, 'gamma': 0.7498119589236539, 'reg_alpha': 0.01574491378273866, 'reg_lambda': 0.9021937125399596, 'max_delta_step': 1}. Best is trial 24 with value: 0.8498074454428755.

Best trial: 24. Best value: 0.849807:  58%|█████▊    | 29/50 [04:59<03:13,  9.20s/it]

[I 2025-12-02 20:52:22,748] Trial 29 finished with value: 0.8498074454428755 and parameters: {'max_depth': 7, 'learning_rate': 0.04372624329354435, 'n_estimators': 409, 'subsample': 0.9979024774640737, 'colsample_bytree': 0.7849893955994928, 'min_child_weight': 9, 'gamma': 2.1967356296858958, 'reg_alpha': 0.015529934007448372, 'reg_lambda': 0.5121207525423238, 'max_delta_step': 1}. Best is trial 24 with value: 0.8498074454428755.

Best trial: 24. Best value: 0.849807:  60%|██████    | 30/50 [05:00<02:16,  6.80s/it]

[I 2025-12-02 20:52:23,964] Trial 30 finished with value: 0.8234916559691913 and parameters: {'max_depth': 7, 'learning_rate': 0.10493277816471058, 'n_estimators': 405, 'subsample': 0.9410262674637415, 'colsample_bytree': 0.7882964024587366, 'min_child_weight': 9, 'gamma': 2.28702865105817, 'reg_alpha': 0.010192398925261716, 'reg_lambda': 0.003055502690349686, 'max_delta_step': 1}. Best is trial 24 with value: 0.8498074454428755.

Best trial: 24. Best value: 0.849807:  62%|██████▏   | 31/50 [05:03<01:44,  5.49s/it]

[I 2025-12-02 20:52:26,402] Trial 27 finished with value: 0.8376123234916559 and parameters: {'max_depth': 8, 'learning_rate': 0.04091985219803872, 'n_estimators': 819, 'subsample': 0.9943181248395567, 'colsample_bytree': 0.7784064290250372, 'min_child_weight': 8, 'gamma': 2.1180266009397277, 'reg_alpha': 0.025331324231487064, 'reg_lambda': 0.001976355912089279, 'max_delta_step': 3}. Best is trial 24 with value: 0.8498074454428755.
[I 2025-12-02 20:52:26,586] Trial 32 pruned.

Best trial: 24. Best value: 0.849807:  66%|██████▌   | 33/50 [05:06<01:05,  3.85s/it]

[I 2025-12-02 20:52:30,321] Trial 34 pruned.

Best trial: 24. Best value: 0.849807:  68%|██████▊   | 34/50 [05:09<00:53,  3.35s/it]

[I 2025-12-02 20:52:32,517] Trial 33 pruned.

Best trial: 24. Best value: 0.849807:  70%|███████   | 35/50 [05:09<00:36,  2.40s/it]

[I 2025-12-02 20:52:32,704] Trial 35 pruned.

Best trial: 24. Best value: 0.849807:  72%|███████▏  | 36/50 [05:12<00:36,  2.62s/it]

[I 2025-12-02 20:52:35,806] Trial 31 finished with value: 0.8234916559691913 and parameters: {'max_depth': 7, 'learning_rate': 0.09404460526913842, 'n_estimators': 398, 'subsample': 0.9338869326510157, 'colsample_bytree': 0.7796021002267338, 'min_child_weight': 9, 'gamma': 0.7378463379933495, 'reg_alpha': 0.004829013257260025, 'reg_lambda': 0.8542802369403646, 'max_delta_step': 3}. Best is trial 24 with value: 0.8498074454428755.

Best trial: 24. Best value: 0.849807:  74%|███████▍  | 37/50 [05:31<01:39,  7.66s/it]

[I 2025-12-02 20:52:55,247] Trial 39 finished with value: 0.8498074454428755 and parameters: {'max_depth': 6, 'learning_rate': 0.055060915585316256, 'n_estimators': 320, 'subsample': 0.9664289649188171, 'colsample_bytree': 0.820296952166785, 'min_child_weight': 8, 'gamma': 3.186518040965302, 'reg_alpha': 0.12378536313198592, 'reg_lambda': 2.570612061394714, 'max_delta_step': 7}. Best is trial 24 with value: 0.8498074454428755.

Best trial: 24. Best value: 0.849807:  76%|███████▌  | 38/50 [05:41<01:37,  8.14s/it]

[I 2025-12-02 20:53:04,512] Trial 36 finished with value: 0.8234916559691913 and parameters: {'max_depth': 9, 'learning_rate': 0.05230465668116136, 'n_estimators': 583, 'subsample': 0.958343262372601, 'colsample_bytree': 0.8141376145933613, 'min_child_weight': 9, 'gamma': 0.9837179172866293, 'reg_alpha': 0.0024039034630710305, 'reg_lambda': 1.3327857590387193, 'max_delta_step': 7}. Best is trial 24 with value: 0.8498074454428755.

Best trial: 24. Best value: 0.849807:  78%|███████▊  | 39/50 [05:42<01:06,  6.02s/it]

[I 2025-12-02 20:53:05,573] Trial 38 finished with value: 0.8234916559691913 and parameters: {'max_depth': 6, 'learning_rate': 0.055531298458513026, 'n_estimators': 565, 'subsample': 0.9622815216862677, 'colsample_bytree': 0.8143385337524242, 'min_child_weight': 9, 'gamma': 2.498416311569245, 'reg_alpha': 0.002359789541798624, 'reg_lambda': 1.2567758546319008, 'max_delta_step': 7}. Best is trial 24 with value: 0.8498074454428755.

Best trial: 24. Best value: 0.849807:  80%|████████  | 40/50 [05:42<00:44,  4.44s/it]

[I 2025-12-02 20:53:06,326] Trial 37 finished with value: 0.8234916559691913 and parameters: {'max_depth': 7, 'learning_rate': 0.05158032098102263, 'n_estimators': 582, 'subsample': 0.9573136368423791, 'colsample_bytree': 0.7044336692926061, 'min_child_weight': 9, 'gamma': 1.1032478743908112, 'reg_alpha': 2.7266780181967242e-08, 'reg_lambda': 1.3926079765263322, 'max_delta_step': 7}. Best is trial 24 with value: 0.8498074454428755.

Best trial: 24. Best value: 0.849807:  82%|████████▏ | 41/50 [05:52<00:53,  5.95s/it]

[I 2025-12-02 20:53:15,819] Trial 40 finished with value: 0.8234916559691913 and parameters: {'max_depth': 6, 'learning_rate': 0.053092467381939054, 'n_estimators': 332, 'subsample': 0.9623766080388979, 'colsample_bytree': 0.7032313516014057, 'min_child_weight': 9, 'gamma': 2.5172802860002785, 'reg_alpha': 0.1434420448592522, 'reg_lambda': 0.09742776743555161, 'max_delta_step': 7}. Best is trial 24 with value: 0.8498074454428755.

Best trial: 24. Best value: 0.849807:  84%|████████▍ | 42/50 [05:59<00:49,  6.21s/it]

[I 2025-12-02 20:53:22,620] Trial 42 finished with value: 0.7849807445442876 and parameters: {'max_depth': 6, 'learning_rate': 0.03607633765514329, 'n_estimators': 280, 'subsample': 0.8989562184887154, 'colsample_bytree': 0.7031041735912, 'min_child_weight': 8, 'gamma': 3.323749015003435, 'reg_alpha': 0.1349820744072471, 'reg_lambda': 0.06860029375495207, 'max_delta_step': 7}. Best is trial 24 with value: 0.8498074454428755.

Best trial: 24. Best value: 0.849807:  86%|████████▌ | 43/50 [06:00<00:33,  4.82s/it]

[I 2025-12-02 20:53:24,206] Trial 41 finished with value: 0.7849807445442876 and parameters: {'max_depth': 6, 'learning_rate': 0.03491969097664392, 'n_estimators': 322, 'subsample': 0.9115518145904117, 'colsample_bytree': 0.7012178946606452, 'min_child_weight': 8, 'gamma': 3.3218457792154688, 'reg_alpha': 0.10795029134586313, 'reg_lambda': 0.13056157618619307, 'max_delta_step': 7}. Best is trial 24 with value: 0.8498074454428755.

Best trial: 24. Best value: 0.849807:  88%|████████▊ | 44/50 [06:01<00:21,  3.56s/it]

[I 2025-12-02 20:53:24,820] Trial 43 finished with value: 0.8234916559691913 and parameters: {'max_depth': 6, 'learning_rate': 0.035437569747012274, 'n_estimators': 301, 'subsample': 0.8849874074646815, 'colsample_bytree': 0.7505461784232169, 'min_child_weight': 8, 'gamma': 3.2546442584045034, 'reg_alpha': 0.1987790126469129, 'reg_lambda': 0.10909695056022888, 'max_delta_step': 5}. Best is trial 24 with value: 0.8498074454428755.

Best trial: 24. Best value: 0.849807:  90%|█████████ | 45/50 [06:05<00:18,  3.63s/it]

[I 2025-12-02 20:53:28,595] Trial 46 pruned.

Best trial: 24. Best value: 0.849807:  92%|█████████▏| 46/50 [06:06<00:11,  2.93s/it]

[I 2025-12-02 20:53:29,895] Trial 44 finished with value: 0.8234916559691913 and parameters: {'max_depth': 6, 'learning_rate': 0.035684937053904325, 'n_estimators': 213, 'subsample': 0.9087608409121768, 'colsample_bytree': 0.876987897614022, 'min_child_weight': 8, 'gamma': 3.3484145200795385, 'reg_alpha': 1.937158193011609, 'reg_lambda': 3.56543945793934, 'max_delta_step': 5}. Best is trial 24 with value: 0.8498074454428755.

Best trial: 24. Best value: 0.849807:  94%|█████████▍| 47/50 [06:07<00:07,  2.38s/it]

[I 2025-12-02 20:53:31,002] Trial 48 pruned.

Best trial: 24. Best value: 0.849807:  96%|█████████▌| 48/50 [06:12<00:06,  3.02s/it]

[I 2025-12-02 20:53:35,515] Trial 49 pruned.

Best trial: 24. Best value: 0.849807:  98%|█████████▊| 49/50 [06:18<00:03,  3.91s/it]

[I 2025-12-02 20:53:41,516] Trial 45 finished with value: 0.8376123234916559 and parameters: {'max_depth': 7, 'learning_rate': 0.12516151542905632, 'n_estimators': 469, 'subsample': 0.9795188427031682, 'colsample_bytree': 0.875127597338167, 'min_child_weight': 8, 'gamma': 3.786854001442395, 'reg_alpha': 1.0317959151950888, 'reg_lambda': 2.871761466144942, 'max_delta_step': 6}. Best is trial 24 with value: 0.8498074454428755.

Best trial: 24. Best value: 0.849807: 100%|██████████| 50/50 [06:18<00:00,  7.57s/it]

[I 2025-12-02 20:53:41,811] Trial 47 finished with value: 0.8376123234916559 and parameters: {'max_depth': 7, 'learning_rate': 0.13270336284575956, 'n_estimators': 441, 'subsample': 0.9792758345800034, 'colsample_bytree': 0.9408480886134127, 'min_child_weight': 6, 'gamma': 4.473450947962708, 'reg_alpha': 2.2066657627498913, 'reg_lambda': 3.0059934927300906, 'max_delta_step': 4}. Best is trial 24 with value: 0.8498074454428755.
Training final model on full training set (LOO strategy)...
Evaluating on test set...

============================================================
All datasets processed. Summary:
============================================================
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.849807                    0.35          0.49

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.288675               0.4               0.3        50          60

   test_size
0         15
  dataset cv_strategy  cv_best_value  test_balanced_accuracy  test_roc_auc  \
0    16_1         loo       0.849807                    0.35          0.49

   test_mcc  test_sensitivity  test_specificity  n_trials  train_size  \
0 -0.288675               0.4               0.3        50          60

   test_size
0         15

# MCI-LBD vs HC - 9_1 - Long Sentence

In [1874]:
#task_9_1_comb_emb_hf_lbd_hc = {"9_1": task_hf_compensated_comb_emb_lbl_lbd_hc.get("9_1")}
#task_9_1_temp_emb_hf_lbd_hc = {"9_1": task_hf_compensated_temp_emb_lbl_lbd_hc.get("9_1")}
#task_9_1_freq_emb_hf_lbd_hc = {"9_1": task_hf_compensated_freq_emb_lbl_lbd_hc.get("9_1")}
#
#task_9_1_comb_emb_lbd_hc = {"9_1": task_comb_dfs_lbd_hc.get("9_1")}
#task_9_1_temp_emb_lbd_hc = {"9_1": task_temp_dfs_lbd_hc.get("9_1")}
#task_9_1_freq_emb_lbd_hc = {"9_1": task_freq_dfs_lbd_hc.get("9_1")}
#
#task_9_1_hf_lbd_hc = {"9_1": task_hf_dfs_clean_lbd_hc.get("9_1")}

In [1875]:
#print(
#task_9_1_comb_emb_hf_lbd_hc.get('9_1').shape, 
#task_9_1_temp_emb_hf_lbd_hc.get('9_1').shape,
#task_9_1_freq_emb_hf_lbd_hc.get('9_1').shape,
#
#task_9_1_comb_emb_lbd_hc.get('9_1').shape,
#task_9_1_temp_emb_lbd_hc.get('9_1').shape,
#ttask_9_1_freq_emb_lbd_hc.get('9_1')ask_9_1_freq_emb_lbd_hc.get('9_1').shape,
#
#task_9_1_hf_lbd_hc.get('9_1').shape,
#)

In [1876]:
#task_9_1_hf_lbd_hc.get('9_1')

In [1877]:
#task_9_1_freq_emb_lbd_hc.get('9_1')

In [1878]:

#print(
#task_9_1_comb_emb_hf_ad_hc.get('9_1').shape, 
#task_9_1_temp_emb_hf_ad_hc.get('9_1').shape,
#task_9_1_freq_emb_hf_ad_hc.get('9_1').shape,
#
#task_9_1_comb_emb_ad_hc.get('9_1').shape,
#task_9_1_temp_emb_ad_hc.get('9_1').shape,
#task_9_1_freq_emb_ad_hc.get('9_1').shape,
#
#task_9_1_hf_ad_hc.get('9_1').shape,

In [1879]:

#print(
    #task_9_1_comb_emb_hf_ad_lbd.get('9_1').shape, 
    #task_9_1_temp_emb_hf_ad_lbd.get('9_1').shape,
    #task_9_1_freq_emb_hf_ad_lbd.get('9_1').shape,
#
    #task_9_1_comb_emb_ad_lbd.get('9_1').shape,
    #task_9_1_temp_emb_ad_lbd.get('9_1').shape,
    #task_9_1_freq_emb_ad_lbd.get('9_1').shape,
#
    #task_9_1_hf_ad_lbd.get('9_1').shape,
#)

In [1880]:
#import pandas as pd
#import umap
#import matplotlib.pyplot as plt
#
#def plot_umap(df, label_col="diagnosis", subject_col="subject"):
    ## pick feature columns (exclude subject, diagnosis, and anything non-numeric)
    #feature_cols = df.select_dtypes(include=["float", "int"]).columns.tolist()
    #feature_cols = [c for c in feature_cols if c not in [label_col]]  # keep features only
#
    #X = df[feature_cols].values
    #y = df[label_col].values  # labels [0,1]

    # Initialize UMAP
    #reducer = umap.UMAP(
        #n_neighbors=15,
        #min_dist=0.1,
        #metric='euclidean',
        #random_state=42
    #)
#
    #embedding = reducer.fit_transform(X)
#
    ## Plot
    #plt.figure(figsize=(8,6))
    #scatter = plt.scatter(
        #embedding[:, 0], embedding[:, 1],
        #c=y,
        #cmap='coolwarm',
        #alpha=0.8,
        #s=70
    #)
#
    #cbar = plt.colorbar(scatter)
    #cbar.set_label("Diagnosis (0=Control, 1=Patient)")
#
    #plt.title("UMAP projection of subjects")
    #plt.xlabel("UMAP-1")
    #plt.ylabel("UMAP-2")
    #plt.grid(True)
    #plt.show()
#
#

In [1881]:
#plot_umap(task_9_1_comb_emb_hf_lbd_hc.get('9_1'), label_col = 'diagnosis_y')
#plot_umap(task_9_1_temp_emb_hf_lbd_hc.get('9_1'), label_col = 'diagnosis_y')
#plot_umap(task_9_1_freq_emb_hf_lbd_hc.get('9_1'), label_col = 'diagnosis_y')

#plot_umap(task_9_1_comb_emb_lbd_hc.get('9_1'), label_col = 'diagnosis')
#plot_umap(task_9_1_temp_emb_lbd_hc.get('9_1'), label_col = 'diagnosis')
#plot_umap(task_9_1_freq_emb_lbd_hc.get('9_1'), label_col = 'diagnosis')

#plot_umap(task_9_1_hf_lbd_hc.get('9_1'), label_col = 'diagnosis')

In [1882]:
#print(task_9_1_comb_emb_hf_lbd_hc)

In [1883]:
#task_9_1_comb_emb_hf_lbd_hc

In [1884]:
#datasets = task_9_1_comb_emb_hf_lbd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials = 50,
    #cv_strategy="loo",
    #output_dir="xgb_lbd_hc_loo_9_1/xgb_results_handcrafted_combined_emb_loo_9_1_lbd_hc",
    #split_param= "diagnosis_y",
#)
#print(summary)
#

In [1885]:

#datasets = task_9_1_temp_emb_hf_lbd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_lbd_hc_loo_9_1/xgb_results_handcrafted_temporal_emb_loo_9_1_lbd_hc",
    #split_param= "diagnosis_y",
#)
#print(summary)
#

In [1886]:

#datasets = task_9_1_freq_emb_hf_lbd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_lbd_hc_loo_9_1/xgb_results_handcrafted_frerq_emb_loo_9_1_lbd_hc",
    #split_param= "diagnosis_y",
#)
#print(summary)
### MCI-AD vs HC -> OPTUNA + XGB

In [1887]:
#task_9_1_freq_emb_hf_lbd_hc.get("9_1")

In [1888]:
#datasets = task_9_1_comb_emb_lbd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_lbd_hc_loo_9_1/xgb_results_comb_loo_9_1_lbd_hc",
    #split_param="emb_",
#)
#print(summary)
#

In [1889]:
#
## Temporal embedings
#datasets = task_9_1_temp_emb_lbd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    ##    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="balanced_accuracy",      
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_lbd_hc_loo_9_1/xgb_results_temp_loo_9_1_lbd_hc",
    #split_param="emb_",
#)
#print(summary)
#

In [1890]:

# Combined embedings
#datasets = task_9_1_freq_emb_lbd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_lbd_hc_loo_9_1/xgb_results_freq_loo_9_1_lbd_hc",
    #split_param="emb_",
#)
#print(summary)
#
#

In [1891]:

#datasets = task_9_1_hf_lbd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_lbd_hc_loo_9_1/xgb_results_handcrafted_loo_9_1_lbd_hc",
    #split_param="w.cz.fnusa",
#)
#print(summary)

# MCI-AD vs HC - 9_1 - Long Sentence

In [1892]:
#task_9_1_comb_emb_hf_ad_hc = {"9_1": task_hf_compensated_comb_emb_lbl_ad_hc.get("9_1")}
#task_9_1_temp_emb_hf_ad_hc = {"9_1": task_hf_compensated_temp_emb_lbl_ad_hc.get("9_1")}
#task_9_1_freq_emb_hf_ad_hc = {"9_1": task_hf_compensated_freq_emb_lbl_ad_hc.get("9_1")}
#
#task_9_1_comb_emb_ad_hc = {"9_1": task_comb_dfs_ad_hc.get("9_1")}
#task_9_1_temp_emb_ad_hc = {"9_1": task_temp_dfs_ad_hc.get("9_1")}
#task_9_1_freq_emb_ad_hc = {"9_1": task_freq_dfs_ad_hc.get("9_1")}
#
#task_9_1_hf_lbd_hc = {"9_1": task_hf_dfs_clean_ad_hc.get("9_1")}

In [1893]:
#task_9_1_hf_ad_hc.get("9_1")

In [1894]:
#task_9_1_comb_emb_hf_ad_hc

In [1895]:
#datasets = task_9_1_comb_emb_hf_ad_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy ="loo",
    #output_dir="xgb_ad_hc_loo_9_1/xgb_results_handcrafted_combined_emb_loo_9_1_ad_hc",
    #split_param= "diagnosis_y",
#)
#print(summary)
#

In [1896]:

#datasets = task_9_1_temp_emb_hf_ad_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_hc_loo_9_1/xgb_results_handcrafted_temporal_emb_loo_9_1_ad_hc",
    #split_param= "diagnosis_y",
#)
#print(summary)
#

In [1897]:

#datasets = task_9_1_freq_emb_hf_ad_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_hc_loo_9_1/xgb_results_handcrafted_frerq_emb_loo_9_1_ad_hc",
    #split_param= "diagnosis_y",
#)
#print(summary)
### MCI-AD vs HC -> OPTUNA + XGB

In [1898]:
#datasets = task_9_1_comb_emb_ad_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_hc_loo_9_1/xgb_results_comb_loo_9_1_ad_hc",
    #split_param="emb_",
#)
#print(summary)
#

In [1899]:

## Temporal embedings
#datasets = task_9_1_temp_emb_ad_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    ##    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="balanced_accuracy",      
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_hc_loo_9_1/xgb_results_temp_loo_9_1_ad_hc",
    #split_param="emb_",
#)
#print(summary)
#

In [1900]:

## Combined embedings
#datasets = task_9_1_freq_emb_ad_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_hc_loo_9_1/xgb_results_freq_loo_9_1_ad_hc",
    #split_param="emb_",
#)
#print(summary)
#
##

In [1901]:
#task_9_1_hf_ad_hc.get('9_1')

In [1902]:

## Combined embedings
#datasets = task_9_1_hf_ad_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_hc_loo_9_1/xgb_results_hc_loo_9_1_ad_hc",
    #split_param="emb_",
#)
#print(summary)
#
#

# MCI-LBD vs MCI-AD - 9_1 - Long Sentence

In [1903]:
#task_9_1_comb_emb_hf_ad_lbd = {"9_1": task_hf_compensated_comb_emb_lbl_ad_lbd.get("9_1")}
#task_9_1_temp_emb_hf_ad_lbd = {"9_1": task_hf_compensated_temp_emb_lbl_ad_lbd.get("9_1")}
#task_9_1_freq_emb_hf_ad_lbd = {"9_1": task_hf_compensated_freq_emb_lbl_ad_lbd.get("9_1")}
#
#task_9_1_comb_emb_ad_lbd = {"9_1": task_comb_dfs_ad_lbd.get("9_1")}
#task_9_1_temp_emb_ad_lbd = {"9_1": task_temp_dfs_ad_lbd.get("9_1")}
#task_9_1_freq_emb_ad_lbd = {"9_1": task_freq_dfs_ad_lbd.get("9_1")}
#
#task_9_1_hf_ad_lbd = {"9_1": task_hf_dfs_clean_ad_lbd.get("9_1")}

In [1904]:
#task_9_1_freq_emb_ad_lbd.get('9_1')

In [1905]:
#datasets = task_9_1_comb_emb_hf_ad_lbd
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy ="loo",
    #output_dir="xgb_ad_lbd_loo_9_1/xgb_results_handcrafted_combined_emb_loo_9_1_ad_lbd",
    #split_param= "diagnosis_y",
#)
#print(summary)
#

In [1906]:

#datasets = task_9_1_temp_emb_hf_ad_lbd
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_lbd_loo_9_1/xgb_results_handcrafted_temporal_emb_loo_9_1_ad_lbd",
    #split_param= "diagnosis_y",
#)
#print(summary)
#

In [1907]:
#task_9_1_freq_emb_hf_ad_lbd.get('9_1')

In [1908]:

#datasets = task_9_1_freq_emb_hf_ad_lbd
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_lbd_loo_9_1/xgb_results_handcrafted_frerq_emb_loo_9_1_ad_lbd",
    #split_param= "diagnosis_y",
#)
#print(summary)
### MCI-AD vs HC -> OPTUNA + XGB

In [1909]:
#datasets = task_9_1_comb_emb_ad_lbd
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_lbd_loo_9_1/xgb_results_comb_loo_9_1_ad_lbd",
    #split_param="emb_",
#)
#print(summary)
#

In [1910]:
#task_9_1_temp_emb_ad_lbd.get('9_1')et

In [1911]:

# Temporal embedings
#datasets = task_9_1_temp_emb_ad_lbd
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    ##    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="balanced_accuracy",      
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_lbd_loo_9_1/xgb_results_temp_loo_9_1_ad_lbd",
    #split_param="emb_",
#)
#print(summary)
#

In [1912]:

# Combined embedings
#datasets = task_9_1_freq_emb_ad_lbd
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_lbd_loo_9_1/xgb_results_freq_loo_9_1_ad_lbd",
    #split_param="emb_",
#)
#print(summary)
#
#

In [1913]:
#task_9_1_hf_ad_hc.get('9_1')

In [1914]:

# Handcrafted features
#datasets = task_9_1_hf_ad_lbd
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_ad_lbd_loo_9_1/xgb_results_hc_loo_9_1_ad_lbd",
    #split_param="emb_",
#)
#print(summary)
#
#

# PD vs HC - 9_1 - Long Sentence

In [1915]:
#task_9_1_comb_emb_hf_pd_hc = {"9_1": task_hf_compensated_comb_emb_lbl_pd_hc.get("9_1")}
#task_9_1_temp_emb_hf_pd_hc = {"9_1": task_hf_compensated_temp_emb_lbl_pd_hc.get("9_1")}
#task_9_1_freq_emb_hf_pd_hc = {"9_1": task_hf_compensated_freq_emb_lbl_pd_hc.get("9_1")}
#
#task_9_1_comb_emb_pd_hc = {"9_1": task_comb_dfs_pd_hc.get("9_1")}
#task_9_1_temp_emb_pd_hc = {"9_1": task_temp_dfs_pd_hc.get("9_1")}
#task_9_1_freq_emb_pd_hc = {"9_1": task_freq_dfs_pd_hc.get("9_1")}
#
#task_9_1_hf_pd_hc = {"9_1": task_hf_dfs_clean_pd_hc.get("9_1")}

In [1916]:
#task_9_1_hf_pd_hc.get('9_1')

In [1917]:
#datasets = task_9_1_comb_emb_hf_pd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy ="loo",
    #output_dir="xgb_pd_hc_loo_9_1/xgb_results_handcrafted_combined_emb_loo_9_1_pd_hc",
    #split_param= "diagnosis_y",
#)
#print(summary)
#

In [1918]:

#datasets = task_9_1_temp_emb_hf_pd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_pd_hc_loo_9_1/xgb_results_handcrafted_temporal_emb_loo_9_1_pd_hc",
    #split_param= "diagnosis_y",
#)
#print(summary)
#

In [1919]:
#task_9_1_freq_emb_hf_pd_hc.get('9_1')

In [1920]:
#
#datpd_hc = task_9_1_freq_emb_hf_pd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_pd_hc_loo_9_1/xgb_results_handcrafted_frerq_emb_loo_9_1_pd_hc",
    #split_param= "diagnosis_y",
#)
#print(summary)
### MCI-AD vs HC -> OPTUNA + XGB

In [1921]:
#datasets = task_9_1_comb_emb_pd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    ##scoring="roc_auc",    
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_pd_hc_loo_9_1/xgb_results_comb_loo_9_1_pd_hc",
    #split_param="emb_",
#)
#print(summary)
#

In [1922]:
#task_9_1_temp_emb_pd_hc.get('9_1')

In [1923]:
#
## Temporal embedings
#datasets = task_9_1_temp_emb_pd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    ##    scoring="balanced_accuracy",     # or "roc_auc"
    #scoring="balanced_accuracy",      
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_pd_hc_loo_9_1/xgb_results_temp_loo_9_1_pd_hc",
    #split_param="emb_",
#)
#print(summary)

In [1924]:

## Combined embedings
#datasets = task_9_1_freq_emb_pd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_pd_hc_loo_9_1/xgb_results_freq_loo_9_1_pd_hc",
    #split_param="emb_",
#)
#print(summary)
#
#

In [1925]:
#task_9_1_hf_pd_hc.get('9_1')

In [1926]:

# Handcrafted features
#datasets = task_9_1_hf_pd_hc
#
#summary, models, studies = optimize_many(
    #datasets,
    #x_y_split_fn=x_y_split,          # your splitter
    #scoring="balanced_accuracy",     # or "roc_auc"
    #n_trials=50,
    #cv_strategy="loo",
    #output_dir="xgb_pd_hc_loo_9_1/xgb_results_hc_loo_9_1_pd_hc",
    #split_param="emb_",
#)
#print(summary)
#
#